### ISSUE TITLE
_.date and _.time ?

### ISSUE THREAD

**Issue by octref** [lodash/lodash#1000]
Hey, I'm wondering if we could add these two methods to lodash.

```
_.date( [fullYear = false ], [delimiter = '-'] )
_.time( [showSec = true], [delimiter = ':'] )

Usage:

_.date()
-> '15-02-25'
_.date(true, '/')
-> '2015/02/25'

_.time(false)
-> '18:14'

```

What do you guys think?

**Comment by megawac** [comment]
I think this is better off in a different library such as moment

**Comment by octref** [comment]
@megawac 
I don't think people would want to include a whole library just to get the current date / time.
You can do it with a few lines of JS, but then you have to remember the peculiar `new Date().getMonth() + 1`, as January matches to 0.
I think `_.date` and `_.time` would be more useful compared to `_.now`, the only function in Date section now.

**Comment by megawac** [comment]
The difference is `_.now` is useful internally whereas this wouldn't be. This can also be done natively like `new Date().toISOString().slice(0, 10)`. There are so many different date formats to consider implementing I don't think its worth going down that path

**Comment by octref** [comment]
You make a good point. 
Thanks for your comment :-)

**Comment by jdalton** [comment]
Ya moment.js and lodash are bffs.
