### ISSUE TITLE
_.round

### ISSUE THREAD

**Issue by thejameskyle** [lodash/lodash#1001]
@jdalton you [knew this was coming](https://github.com/lodash/lodash/pull/987#issuecomment-75475069). :stuck_out_tongue_winking_eye: 

It would be super useful to have a `Math.round` equivalent that supported the precision that it can be rounded to. 

```js
_.round(4.006);
// => 4

_.round(4.006, 2);
// => 4.01

_.round(4060, -2);
// => 4100
```

It also would be ultra simple to add support for [`_.ceil` and `_.floor`](https://github.com/lodash/lodash/pull/987#issuecomment-75475528) without [duplicating code](http://jsbin.com/jacusa/1/edit?js,console).

**Comment by jdalton** [comment]
Thanks James! I think we'll hold off until there's demand.

**Comment by benshope** [comment]
Yea this would be a nice feature

**Comment by ianwsperber** [comment]
+1!!

**Comment by sankethkatta** [comment]
:+1: Would love to have this feature.

**Comment by maxtsepkov** [comment]
I demand! :)
