### ISSUE TITLE
_.max always returns -Infinity when comparing strings

### ISSUE THREAD

**Issue by dben** [lodash/lodash#1002]
When comparing strings, _.max will always return -Infinity. ( Likewise, _.min will always return Infinity.)

I had expected that they would return the max user based on a string compare ('fred', since 'fred' > 'barney')

```
var users = [
  { 'user': 'barney', 'age': 36 },
  { 'user': 'fred',   'age': 40 }
];

console.log(
  _.max(users, function(chr) {
    return chr.user;
  })
);

console.log(_.max(users, 'user'));
```

**Comment by jdalton** [comment]
`_.min` and `_.max` aren't really intended for comparing string values as they mimic `Math.min` and `Math.max`.

**Comment by octref** [comment]
I think you can do it this way:
`_.last(_.sortBy(users, 'user'))`

It sorts `users` ascendingly by `user`, so the last one is the one with max `user` value.
