### ISSUE TITLE
unclear how to use the module `chain` alone

### ISSUE THREAD

**Issue by oriSomething** [lodash/lodash#1003]
can't get how to use `chain` when i'm using it, via `require('lodash/chain/chain')`. how do i add exist methods as `map` for example? maybe it's hidden somewhere in the docs?
thanks

**Comment by jdalton** [comment]
There's isn't any easy way to use them. You can [mimic the scaffolding](https://github.com/lodash/lodash/issues/966#issuecomment-74384259) of the monolithic using the modules.
