### ISSUE TITLE
A way to iterate over several arrays simultaneously

### ISSUE THREAD

**Issue by Suor** [lodash/lodash#1007]
Like:
```js
_.forEach(['a', 'b', 'c'], [1, 2, 3], function (name, score) {
// ...
})
```
Not sure this is doable with `forEach`, different name may be required.

**Comment by arseniew** [comment]
You could combine _.spread and _.zip for that. 

_.forEach(_.zip(['a', 'b', 'c'], [1, 2, 3]), _.spread(function(name, score){ /* */ }));

**Comment by Suor** [comment]
3 functions to do the job?

**Comment by davidkpiano** [comment]
@Suor Yes, since your original `_.forEach` goes against the `item, index, collection` arguments pattern for iterables, and it would be difficult to accommodate that for two collections.

**Comment by jdalton** [comment]
Hi @Suor. I've opened a [gitter](https://gitter.im/lodash/lodash) chat room for lodash. Feel free to pop in and ask questions there too.

**Comment by StreetStrider** [comment]
`zip-spread` here is not just workaround, but also a redundant things to do. i.e. worse perfomance. The only reason to use `zip` here is if we want to combine input arrays anyway (on a later stage). In this case we can just combine them earlier and do the job with ordinary lodash functions. However, if we need to `spread` them later it's an indicator the all `zip-spread` thing is wrong.

**Comment by avesus** [comment]
:+1:

**Comment by avesus** [comment]
What about `_.forEach(_.zipObject())`?

**Comment by ripfoghorn** [comment]
```javascript
_.zipWith(arr,` arr_2, function(a, b){ /* */ });
```
