### ISSUE TITLE
lodash.template with '${}' evaluating for some reason

### ISSUE THREAD

**Issue by olsonpm** [lodash/lodash#1009]
Why does the following code throw an error?

```
var lodash = require('lodash');

var compiled = lodash.template('${ok}');
console.log(compiled());

// throws
// undefined:8
// ((__t = (ok)) == null ? '' : __t);
// ReferencError: ok is not defined
// ...
```

I looked at the code and couldn't figure out why it's choosing to evaluate ${ } - which just happens to be a variable in a bash script.  I don't see any relevant documentation in lodash nor in erb.

**Comment by olsonpm** [comment]
Well after searching a bit more in the code I saw the keyword I was missing "ES6 delimiter".

Closing as #399 resolves my problem

**Comment by jdalton** [comment]
You can disable ES6 delimiter support by providing a custom `interpolate` delimiter. It can a new regexp matching the old pattern. For example:
```js
_.template(string, { 'interpolate': /<%=([\s\S]+?)%>/g })(source);
```
