### ISSUE TITLE
Alias for _.constant

### ISSUE THREAD

**Issue by j0tunn** [lodash/lodash#1010]
It would be nice to have some meaningful alias for `_.constant` method.
Example:
```js
var errors = _({
        'File does not exist': !fileExists,
        'Some condition is not fulfilled': someBoolResult,
        // ...
    })
    .pick(_.constant) // This doesn't seem very clear
    // .pick(_.val) // Much better
    .keys()
    .value();

return _.isEmpty(errors) || q.reject(errors.join('\n'));
```

**Comment by jdalton** [comment]
I think your use of [_.constant](https://lodash.com/docs#constant) isn't quite right. It creates a function which returns a constant value.

**Comment by j0tunn** [comment]
So can you suggest any alternative to
```js
pick(function(val) { return val; })
```
?

**Comment by jdalton** [comment]
Try [_.identity](https://lodash.com/docs#identity).

**Comment by j0tunn** [comment]
Thanks, that works. But still doesn't very clear.

**Comment by jdalton** [comment]
It's an [identity function](http://en.wikipedia.org/wiki/Identity_function). It's been around in Underscore since 2009 and Prototype since 2005 (as [Prototype.K](http://api.prototypejs.org/Prototype/K/)

**Comment by StreetStrider** [comment]
@j0tunn, your use of `_.constant` is not correct, as was mentioned before.
Maybe this will help to make things clear:
1. `identity` is a function which return its argument without any transformation. It is like `1` for multiplication, or `0` for addition. It works with any value and return **the same value**.
2. On the other side `constant` takes value and return **function which return this value**. It is like constructor or factory returning the same value each time it invoked.

**Comment by j0tunn** [comment]
@jdalton @StreetStrider thanks for the explanation, now its clear.
