### ISSUE TITLE
Incorrect shortcut fusion with drop and dropWhile

### ISSUE THREAD

**Issue by pavadeli** [lodash/lodash#1011]
When mixing `drop` and `dropWhile` in a lodash chain I get incorrect results (using version 3.3.1).

```javascript
var arr = [{v:1}, {v:2}, {v:3}, {v:4}];
_(arr)
    .dropWhile('v', 1)
    .drop()
    .dropWhile('v', 3)
    .value()
// Result: [ { v: 3 }, { v: 4 } ]
// Expected: [ { v: 4 } ]
```

When I break shortcut fusion by tapping into the intermediate result before the last `dropWhile` I get the correct result:
```javascript
_(arr)
    .dropWhile('v', 1)
    .drop()
    .tap(_.noop)
    .dropWhile('v', 3)
    .value()
// Result: [ { v: 4 } ]
```

**Comment by jdalton** [comment]
The quick fix is to make a full stop on `dropWhile` and `takeWhile` methods which flattens the chain down to a single value (this removes and shortcut fusion from any preceding chain actions). I'd like to dig a bit to see if that can be avoided.

**Comment by pavadeli** [comment]
Thanks, that was fast. Will use the workaround for now.

**Comment by jdalton** [comment]
Tonight I'll update with tests and a more narrow fix to just full stop `dropWhile` calls that happen after a `filter`.
