### ISSUE TITLE
Incosistency when going back and forth between camelCase and snakeCase

### ISSUE THREAD

**Issue by ivanakimov** [lodash/lodash#1012]
When converting back and forth between camelCase and snakeCase, seems like output does not stay the same when numbers are involved. Any way to make it consistent?

	_.snakeCase('enable24hFormat');    /* "enable_24_h_format" */
	_.camelCase('enable_24_h_format'); /* "enable24HFormat" */
	_.snakeCase('enable24HFormat');    /* "enable_24_hf_ormat" */

**Comment by jdalton** [comment]
Ya, the bug looks like HF is considered a word after the capitalization which is bogus. The good news fixing it in `_.words` fixes it in other places.

```js
_.words('enable24HFormat')
// => ["enable", "24", "HF", "ormat"]
```

**Comment by ivanakimov** [comment]
Great. Thank you.

**Comment by jdalton** [comment]
The fix is to change `{2,}` in `reWords` to a `+`. Will patch tonight.

**Comment by ivanakimov** [comment]
:+1:

**Comment by jdalton** [comment]
A little more tweaking and we can get it to correctly identify `h` as a unit and so return:
```
["enable", "24h", "Format"]
```

**Comment by ivanakimov** [comment]
Thanks for the quick fix @jdalton.
