### ISSUE TITLE
Add string built-ins to lodash wrapper?

### ISSUE THREAD

**Issue by jasonkarns** [lodash/lodash#1016]
It's super handy that a bunch of the built-in `Array` methods (`concat`, `join`, `pop`, `push`, etc) are all added to the wrapper object. Thus when an array is wrapped, one can use any of the built-in array methods directly on the chain as if operating directly on the array.

Now that lodash has a suite of String methods, I was a bit surprised to learn that the `String` built-ins *aren't* added to the wrapper object as well.

Was this intentional or an oversight? I would love to be able to use methods like `split` or `replace` directly on a lodash-wrapped string.

**Comment by jdalton** [comment]
I can dig a couple helpers. Let's open it to PRs :D

**Comment by megawac** [comment]
If these are back on the table it may be a good time to reconsider https://github.com/lodash/lodash/issues/821?

**Comment by jdalton** [comment]
Still not wanting method proxies. Chaining is pretty scenario specific.

**Comment by octref** [comment]
I guess I can help :-)
I'll spend today and tomorrow looking for some possible implementations & post them here & do the PR in this weekend.

**Comment by jdalton** [comment]
Rock, let's reuse the loop that's handling the array methods, adding just `replace`, and `split`, and toggle based on a regexp match of their names similar to how it's handled in other places.

**Comment by d10** [comment]
:+1: `split` and `replace` are a good start!

**Comment by jdalton** [comment]
Taking it to #1016.
