### ISSUE TITLE
Chained groupBy and forEach doesn't seem to work properly

### ISSUE THREAD

**Issue by joshperry** [lodash/lodash#1017]
Did these symantics change in v3?

```javascript
_([{color: 'green', name: 'foo'}, {color:'red', name:'bar'}, {color:'green', name: 'baz'}])
    .groupBy('color')
    .forEach(function(b) {
        console.log(b); // Never called
    })
```
Works in v2: https://jsfiddle.net/bg3cvrx2/

**Comment by jdalton** [comment]
There's lots of things that have changed in v3. Please review the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v300). In v3 chaining is deferred/lazy until an implicit or explicit `value()` is required. So to execute the chain you need to call `value()`.

**Comment by joshperry** [comment]
@jdalton Thanks, was just reading that as you responded. Consider this a request for certain functions (like `forEach` that don't add to the chain) to be considered "terminating" functions. Seems like it would make a little more semantic sense.

**Comment by jdalton** [comment]
Our `each` method has chained for 2 years and will continue to chain in the future.

**Comment by joshperry** [comment]
@jdalton Fair enough. Thanks again.
