### ISSUE TITLE
Allow static (constant) value for _.times?

### ISSUE THREAD

**Issue by jmversteeg** [lodash/lodash#1019]
I just asked a [question on StackOverflow](http://stackoverflow.com/questions/28862151/lodash-underscore-js-function-to-create-array-consisting-of-n-copies-of-x) and I realized that the number of use cases for the `_.times` method might significantly benefit from optionally accepting a static (constant) value instead of an iteratee (such that ` _.times(3, 'foo');` will return `['foo', 'foo', 'foo']` ) same as using `_.times(3, _.constant('foo'));`.

**Comment by jdalton** [comment]
I've thought about this and it doesn't mesh well with our existing iteratee shorthands. We also provide [_.fill](https://lodash.com/docs#fill):

```js
_.fill(Array(5), 'foo');
// => ["foo", "foo", "foo", "foo", "foo"]
```

**Comment by jmversteeg** [comment]
Okay, very reasonable, thank you.
