### ISSUE TITLE
Add _.isInteger

### ISSUE THREAD

**Issue by brandonhorst** [lodash/lodash#1020]
This would mirror ES6 [Number.isInteger](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-number.isinteger).

**Comment by jdalton** [comment]
I'm cool with it but first

* Explain a use case
* Create a PR with documentation & unit tests (don't forget to sign the [CLA](http://dojofoundation.org/about/claForm) if you haven't)

**Comment by octref** [comment]
@jdalton 
Perhaps you are not aware of this:
![issue](https://cloud.githubusercontent.com/assets/4033249/6539766/b46c6cd6-c44b-11e4-9e26-3a849732d75b.png)

I think you can add a section in `CONTRIBUTING.md` to tell people you'd like them to provide use cases for feature requests, check docs / 3.0 changelogs before reporting an issue, etc.

**Comment by jdalton** [comment]
Naw. It's easy enough.

**Comment by jdalton** [comment]
Added via https://github.com/lodash/lodash/commit/49266dce89b7ac62b45a193a14d05188212d1eca.
