### ISSUE TITLE
_.replace(collection, match, new)

### ISSUE THREAD

**Issue by octref** [lodash/lodash#1022]
Before adding the `replace` on `StringWrapper` in #1016, I thought about adding `replace`:

Replace matches in `collection` with `new`
`match` is a normal `[predicate=_.identity]`
`new` can be either:
- A value with which matched items will be replaced
- A function which takes in the old value and returns the new value.
```
_.replace(collection, match, new)

function isEven(x) { return x % 2 == 0; }
_.replace([1, 2, 3], isEven, 42)
// -> [1, 42, 3]
_.replace([1, 2, 3], isEven, function(x) { return x + 1; )
// -> [1, 3, 3]
_.replace([1, null, 3], _.isNull, 42)
// -> [1, 42, 3]
```

Why not just a `_.map`?
`_.replace([1, null, 3], _.isNull, 42)` looks really intuitive. The `isNull` can be any function you built to validate your data.

**Comment by jdalton** [comment]
Let's keep it simple with the chaining string sugar for now (though if/when we wouldn't use `replace` as its name).

**Comment by octref** [comment]
Roger.

**Comment by jdalton** [comment]
BTW I'm really digging your enthusiasm!

**Comment by octref** [comment]
Thanks for you encouraging words!
Instead of trying to get a 4.0 in college I decided to do some more Open Source. My grade suffers a little bit but who cares as long as I can graduate. Coding is much more fun and rewarding :-)

**Comment by michaeljcalkins** [comment]
@jdalton I'm looking for this kind for this particular function right now actually.  Did this function ever get merged?

`var newArr = _.replace(original, { id: 1 }, replacement);`

http://codepen.io/michaeljcalkins/pen/xGjmzo?editors=001

**Comment by jdalton** [comment]
@michaeljcalkins 
> Did this function ever get merged?

Nope, I opted to keep things simple and rely on the chaining sugar.

**Comment by bcherny** [comment]
Immutable replace would be very helpful - similar to http://facebook.github.io/immutable-js/docs/#/List/updateIn

**Comment by jfmengels** [comment]
There are two similar proposals (one being mine, though this one is the oldest): https://github.com/lodash/lodash/issues/1967 and https://github.com/lodash/lodash/issues/2053.

Differences: This one requests a function as the predicate, #2053 requested an index and #1967 either of those.

**Comment by bcherny** [comment]
@jfmengels thanks, I voted.
