### ISSUE TITLE
Can yield enforce synchronization in _.each?

### ISSUE THREAD

**Issue by khanh-nguyen** [lodash/lodash#1024]
I want to execute tasks in an array synchronously without using `async` or iterator.
```
var readFile = thunkify(fs.readFile);

function* short() {
    yield []; 
    console.log('Short task');
};

function* long() {
    yield readFile('foo.txt');
    console.log('Long task');
}

var arr = [long, short];
co(function*() {
    yield _.each(arr, function*(task) {
        yield task();
    });
});
```
Result:
```
$ node --harmony test
Short task
Long task
```
If I change `_.each` to a native `for` loop, then it works synchronously.
```
for (let i = 0; i < arr.length; i++){
    yield arr[i]();
}; 
```
Result:
```
$ node --harmony test
Long task
Short task
```
Can someone clarify?
Thanks,

**Comment by jdalton** [comment]
I have zero experience working with generators, iterators, and yield. This is outside the scope of lodash. Try the [babel gitter room](https://gitter.im/babel/babel).

**Comment by d10** [comment]
This is because lodash doesn't have explicit support for generator functions, so it will not know what to do with `yield`ed stuff. IIRC, Co supports yielding an array of generator functions so you should be able to do this:
```js
var arr = [long, short];
co(function*() {
    yield arr;
});
```

**Comment by khanh-nguyen** [comment]
Thanks for confirming.
@d10 yes, you're right, `co` supports yielding array. But the above code still results in short being executed first, followed by long.

**Comment by overlookmotel** [comment]
@khanh-nguyen I just wrote a module [co-series](https://www.npmjs.com/package/co-series) to solve this problem.

```js
var series = require('co-series');

var arr = [long, short];
co(function*() {
    yield arr.map(series(function*(task) {
        yield task();
    }));
});
```
