### ISSUE TITLE
_.isSymbol, _.isMap, _.isSet

### ISSUE THREAD

**Issue by thejameskyle** [lodash/lodash#1025]
`_.isSymbol` is the biggest one here, but `_.isMap` and `_.isSet` would be easy enough to add.

**Comment by jdalton** [comment]
Got a use case for them? I know io.js added a helper for `isSymbol`.

**Comment by thejameskyle** [comment]
Well my current use case is building a better pretty-printer for the Babel online REPL than `JSON.stringify`, but I can imagine wanting to use it again in the future.

**Comment by jdalton** [comment]
With shims for `Map` and `Set` it might get tricky detecting them without duck typing. Symbols on the other hand aren't shimmable (am I right?).

**Comment by thejameskyle** [comment]
They'd have look _something_ like this:

```js
var isMap = typeof Map === 'function' ? function(val) {
  return val instanceof Map;
} : function(val) {
  return val && val.toString() === '[object Map]'
};
```

```js
var isSet = typeof Set === 'function' ? function(val) {
  return val instanceof Set;
} : function(val) {
  return val && val.toString() === '[object Set]'
};
```

```js
var symRegExp = /^Symbol\(.*\)$/;
var isSymbol = typeof Symbol === 'function' ? function(val) {
  return typeof val === 'symbol';
} : function(val) {
  return val && symRegExp.test(val.toString())
};
```

**Comment by thejameskyle** [comment]
Also: https://github.com/zloirock/core-js/blob/master/src/es6.symbol.js

**Comment by thejameskyle** [comment]
Actually you wouldn't want to do `typeof symbol` because that wouldn't work for polyfills.

**Comment by jdalton** [comment]
I'll only add `_.isSymbol` if it cannot be polyfilled. If it can be polyfilled then I don't want to deal with duck typing.

**Comment by jdalton** [comment]
So it looks like there's a shim for symbols so it's right out.

**Comment by Xotic750** [comment]
@jdalton I don't quite follow your reason for not having these `is` functions, if it is just because they can be shimmed/shammed then I don't quite follow why lodash has `_.isTypedArray` and brethren? ES6 seems to be causing you a little turmoil in what to make a general utility. Just curious.

**Comment by chicoxyzzy** [comment]
Why shouldn't `isMap` and `isSet` exist just for native types?

**Comment by jdalton** [comment]
Let's add them! PRs please.

**Comment by jdalton** [comment]
I think I have a form of them internally.
