### ISSUE TITLE
filter + rest + map => trouble

### ISSUE THREAD

**Issue by j0tunn** [lodash/lodash#1026]
Hi, I have some problem using `filter`, `rest` and `map` in chain. After `filter` and `rest` applied `map` still can iterate over elements of the array even though there are no elements already.
Here is minimal case in interactive mode:
```bash
> require('lodash')([1]).rest().map(function(v) { console.log(v); }).value();
[] # OK
> require('lodash')([1]).filter(function(v) { return v; }).rest().map(function(v) { console.log(v); }).value();
1 # WTF?!
[]
> 
```

I think the problem is in the lazy evaluation.

**Comment by j0tunn** [comment]
@egavr

**Comment by eGavr** [comment]
:+1:

**Comment by jdalton** [comment]
Welp, I was hoping I got all the bugs. Next time!

**Comment by j0tunn** [comment]
Thanks for the fix. When should we expect new version?

**Comment by jdalton** [comment]
We update weekly.
