### ISSUE TITLE
A string formatting function?

### ISSUE THREAD

**Issue by iirelu** [lodash/lodash#1027]
_.template is kinda unwieldy for tiny things, a _.format function would be much more helpful. I'm imagining functionality like (basing off of [how Rust does it](http://doc.rust-lang.org/std/fmt/index.html)):

```js
var world = "world";
var helloworld = _.format("Hello {}!", world); // -> Hello world!
console.log(_.format("{} is {}!", "Lo-dash", "fun")); // Prints "Lo-dash is fun!"
```

Would be useful for getting rid of awkward string adding, like `"Hello " + name + "!"`.

**Comment by jdalton** [comment]
I've held off on a `sprintf` function because its implementation is hefty. For now you can check out https://www.npmjs.com/search?q=sprintf.

**Comment by iirelu** [comment]
Doesn't have to be a hefty printf-style thing, and anyway, you've already got a whole templating system.

Tiny sample implementation:

```js
function format() {
  var fmtstring = arguments[0],
      length = arguments.length,
      args = Array(length ? length - 1 : 0);

  while (--length > 0) {
    args[length - 1] = arguments[length];
  }
  args = args.reverse();

  return fmtstring.replace(/{}/g, function() {
    return args.pop();
  });
}
```

Of course, it doesn't have much functionality, but it doesn't *need* much functionality. A string helpers category with no formatting functionality just feels *weird*, especially for a language with no built-in string formatting.

**Comment by jdalton** [comment]
I can see this easily expanding to something like a `sprintf` though. If it's too simple it doesn't offer much over `String#replace`. I'll keep an eye on this though if an implementation emerges as something devs can get behind we'll add it.

**Comment by slavafomin** [comment]
Hello! I would really appreciate `sprintf()` in lodash. `template()` is way too complex to use for simple string formatting. Thank you!

**Comment by undercloud** [comment]
I create something like in php with sprintf
``` PHP
                public static function template()
		{
			$args = func_get_args();
			$tmpl = array_shift($args);
			$args = array_map(function ($item) {
				if (is_array($item)) {
					return implode(', ', array_filter($item, function ($el) {
						return (is_scalar($el) and !self::isBlank($el));
					}));
				}
				return $item;
			}, $args);
			$tmpl = preg_replace_callback('~\{[0-9]{1,2}\}~', function ($e) {
				return '%' . trim($e[0], '{}') . '$s';
			}, $tmpl);
			return vsprintf($tmpl, $args);
		}
```
usage
```PHP
template('Hello {1} Your age {2}','John', 40)
```

**Comment by StreetStrider** [comment]
[string-format](https://github.com/davidchambers/string-format).

**Comment by PaulDejardin** [comment]
:+1:

**Comment by c-dante** [comment]
Alternative, start adopting ES6 string templates:

```js
var x = 10;
var y = [1, 2, 3];
console.log(`X: ${x}, Y: [${y.join(',')}], Mapped: [${y.map(a => a + x).join(',')}]`);
```

**Comment by u01jmg3** [comment]
https://www.npmjs.com/package/voca
