### ISSUE TITLE
`map` over object in `chain` after `reduce`

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [lodash/lodash#1028]
Hello,

In the following example

```
var items = [ 'a', 'b', 'a' ];

var test = function() {
  return _(items).reduce(function(acc, item) {
    acc[item] = acc[item] ? acc[item] : 0;
    ++acc[item];
    return acc;
  }, { }).map(function(value) {
    return value;
  });
};

console.log(test());
```

the exception 

```
/home/user/Projects/nodejs/test/main.js
  }, { }).map(function(value) {
          ^
TypeError: undefined is not a function
```

is thrown.

It would be very useful to be able `map` over an object in a `chain` after `reduce`.

Is it a regular `map` behavior when chaining or am I doing something wrong?

Thanks

**Comment by jdalton** [comment]
The `reduce` function implicitly calls `.value()` to end the chain because it's resolving a value. You can force chaining by using the `chain()` method before.
```js
_(items).chain().reduce(...).value();
```

**Comment by volodymyrprokopyuk** [comment]
Thank you very much!
