### ISSUE TITLE
Cannot merge nested json. 

### ISSUE THREAD

**Issue by AlexCppns** [lodash/lodash#1029]
I am trying to find a method to merge 2 NESTED jsons. I tried `_.assign`,  `_.merge` and `_.defaults`. Do I have to write a recursion to loop over all the internal keys??

**Comment by jdalton** [comment]
[_.merge](http://lodash.com/docs#merge) is what you're looking for. It accepts a `customizer` callback if you want to tweak how it merges certain types.

**Comment by AlexCppns** [comment]
Sorry but I cannot get it to work, I am even using a recursion:
```
lineItemForm.mergeRecursion = function(destination, source){
    var self = this;
    var merged = _.merge({}, destination, source, function(dest, sour){
      if(dest === ''){ return sour; }
      if(sour === ''){ return dest; }
      if(dest === []){ return sour; }
      if(sour === []){ return dest; }
      console.log(dest);
      console.log(sour);

      if(_.isObject(dest) && _.isObject(sour)){
        console.log(Object.keys(dest).length);
        console.log(Object.keys(sour).length);
        if(Object.keys(dest).length === 0){
          console.log("source value is ..");
          console.log(sour);
          // relevant value returned here:
          return sour;
        } else {
          return self.mergeRecursion(dest, sour);
        }
      }
    });

    console.log(merged);
    return merged;
  };
```

I am even making sure the value I am interested is returned but when I check the 'merged' variable, it's not there.

**Comment by jdalton** [comment]
Sorry you can't get it to work. Try [stackoverflow](http://stackoverflow.com/) or [gitter](https://gitter.im/lodash/lodash) for assistance.

**Comment by AlexCppns** [comment]
I am sorry I found the problem.. angularJS and data binding will do that...
