### ISSUE TITLE
_.combinations(collection, n, iteratee) or something similar

### ISSUE THREAD

**Issue by barberboy** [lodash/lodash#1032]
I'm looking for something in lodash that will let me iterate through combinations of `n` elements from a collection. Something like:

    _.combinations([1, 2, 3, 4], 2, function(c){
       console.log(c);
    });
    // logs:
    //  [1, 2]
    //  [1, 3]
    //  [1, 4]
    //  [2, 3]
    //  [2, 4]
    //  [3, 4]

Ideally there would also be some way to stop the iteration. Perhaps returning `false` from the iteratee would halt the iteration, and the current combination would be returned by `_.combinations`.

Does something like this already exist in lodash that I'm missing?

**Comment by jdalton** [comment]
There's something like this in [underscore-contrib](https://github.com/documentcloud/underscore-contrib/blob/edf72d6bed76b01364a3c52b7eb034ffad0ebd2b/underscore.array.builders.js#L191-L199). You should ping [lodash-contrib](https://github.com/TheNodeILs/lodash-contrib) to update so you can get the lodash flavor.

**Comment by barberboy** [comment]
Perfect—thanks!

**Comment by refack** [comment]
:+1:

**Comment by cjhveal** [comment]
:+1:

**Comment by nitoloz** [comment]
Hi @barberboy!
Did you find smth that could produce those combinations?
