### ISSUE TITLE
Inexplicable error when using `reduce` on an object

### ISSUE THREAD

**Issue by bioball** [lodash/lodash#1033]
I run a production site where I capture all client-side exceptions on my server. Currently, I'm trying to debug this error that I can't explain, nor reproduce, so I'm hoping that you guys would have some clue...

I'm doing a reduce operation on an object that looks like this:

```json
{
  "4": {
    "quantity": 0,
    "id": 4
  },
  "13": {
    "quantity": 0,
    "id": 13
  },
  "17": {
    "quantity": 0,
    "id": 17
  },
  "18": {
    "quantity": 0,
    "id": 18
  },
  "20": {
    "quantity": 0,
    "id": 20
  },
  "22": {
    "quantity": 0,
    "id": 22
  },
  "23": {
    "quantity": 0,
    "id": 23
  },
  "36": {
    "quantity": 0,
    "id": 36
  },
  "37": {
    "quantity": 0,
    "id": 37
  }
}
```

Basically, it's a hash of line-items, and I `reduce` it to get the total number of items. Here's my code, copy and pasted.

```js
_.reduce(items, function(sum, product){
  return sum + product.quantity;
}, 0);
```

And results in this kind of error message: `Cannot read property "quantity" of undefined`.

This error only appears on iPhone Safari, it seems, just by inspecting the browser useragent. Here's the some of the useragents that errored:

* Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) GSA/5.2.43972 Mobile/12B440 Safari/600.1.4
* Mozilla/5.0 (iPad; CPU OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B466 Safari/600.1.4

I can't reproduce this on my own iPhone. Any idea what's is going on? Maybe because my keys can be parsed as ints, the object gets false interpreted as an Array?

This is on lodash 2.4

**Comment by jdalton** [comment]
iOS has had [some JIT](https://github.com/lodash/lodash/issues/799) bugs pop up that affect lodash pre 3.0 and Underscore. Can you try with lodash v3.5.0 and report back.

**Comment by bioball** [comment]
Ok. That most likely is it. Couldn't find anything via Google related to this issue, so I should work on my Google-fu. I'll close this for now, and will re-open if this issue still comes up.

**Comment by bioball** [comment]
Just to put this to rest, this error has disappeared entirely since upping my version.

**Comment by jdalton** [comment]
Nice!
