### ISSUE TITLE
[Feature Request] _.guid() to create a new guid

### ISSUE THREAD

**Issue by BrianRosamilia** [lodash/lodash#1034]
I was intrigued to find so many people using ad-hoc methods for generating guids in JavaScript 

http://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript (+1300)

(myself included in copy-pasting some boilerplate from this post)  Some people even appear to be using web services to generate them.. I was also surprised to find that this has never been brought up in either the lodash project or the underscore project.

I think this feature would fit nicely under the 'Number' utility functions in lodash.  What do you think?

**Comment by jdalton** [comment]
guids seem a bit brittle in JS land or require a lot of code. I'm happy to punt on it for now in favor of our simple [_.uniqueId](https://lodash.com/docs#uniqueId) method. If you're wanting a guid implementation there's plenty on npm https://www.npmjs.com/search?q=guid.
