### ISSUE TITLE
Unable to use _.every in _.takeWhile

### ISSUE THREAD

**Issue by haphut** [lodash/lodash#1035]
I can't fathom why `_(foo).zip(bar).takeWhile(_.every)` does not work as I hoped it would. I've written [a small example](https://jsfiddle.net/4y6os404/) where I expected to see the same output twice. The example currently uses lodash 3.3.0 because of the CDN but I've verified the same behaviour on 3.5.0.

Is it the expected behaviour?

**Comment by d10** [comment]
Seems like a bug to me. Will try to debug and fix soon.

**Comment by davidkpiano** [comment]
Your first `_.every` is being called with just the collection. Your second `_.every` (in `.takeWhile(_.every)`) is being called with three arguments - the value (each array in the zipped arrays), the index, and the collection - which don't match the signature of `_.every`.

A quick solution is to limit `_.every` to only one argument: `_(foo).zip(bar).takeWhile(_.ary(_.every, 1))`

@jdalton could this benefit from an `isIterateeCall` check?

**Comment by haphut** [comment]
Thank you both. That makes sense and is documented behaviour for `_.takeWhile`.

Btw, if you need to consider use cases, my intention was to whip up a quick solution for a `_.zip` that would not continue past the shortest array. It would have worked for my input but not for falsy yet valid values in the arrays. `_(foo).zip(bar).take(minimumSize([foo, bar]))` does not look clean because of the argument repetition but it'll do.

Though I can see myself needing to `AND` zipped arrays of booleans in the future.

**Comment by jdalton** [comment]
@davidkpiano 
> could this benefit from an `isIterateeCall` check? There also doesn't seem to be a unit test for `_.every` should work as iteratee for `_.map`

Yap it's being used in a way that would benefit from it so we can add it. There's not a test because we don't have a guard to ensure anything other than its usual behavior.
