### ISSUE TITLE
Using the `_.property` callback shorthand with `_.difference`

### ISSUE THREAD

**Issue by soygul** [lodash/lodash#1037]
```javascript
var diff = _.difference(array1, array2, 'id');
```

Is it possible (doesn't seems so from the docs/source). If not, is it intentional not provided or just a missing feature. If so, I'll make a PR.

**Comment by jdalton** [comment]
It's the intended behavior. The `_.difference` method supports accepting 2 or more arrays so function sugar gets a bit more clunky. I think in v4 we'll split `_.uniq` out into `_.uniqBy` for the callback functionality (I'll add it to the [roadmap](https://github.com/lodash/lodash/wiki/Roadmap)). At that time we'll consider adding transform callbacks to others like `_.difference`. Until then you can do:
```js
var diff = _.difference(_.pluck(array1, 'id'), _.pluck(array2, 'id'));
```
or whichever combination of `pluck` is needed.

**Comment by soygul** [comment]
Ok will go w/ the pluck. 

Thanks for the neat maintenance.. guava/lodash/go-std; you guys are saving world resources!
