### ISSUE TITLE
_.difference returns values to exclude when provided with undefined as first param

### ISSUE THREAD

**Issue by jeffcharles** [lodash/lodash#1038]
```
_.difference(undefined, [1])
[1]
_.difference([1], undefined)
[1]
_.difference([], [1])
[]
_.difference([1], [2])
[1]
_.difference([2], [1])
[2]
```

I would've expected the first call to return an empty array. It's easy to miss a conditional or an or to coerce an undefined value to an empty array.

**Comment by jdalton** [comment]
This is [intentional](https://github.com/lodash/lodash/commit/0e828e5b3b8c18f22b94cb914e464f9c81b67913). It aligns better with `_.intersection`, `_.union`, & `_.xor`.

**Comment by jeffcharles** [comment]
Fair enough. I'd argue that's a less than ideal API since the three functions you outlined are commutative whereas `_.difference` is definitely not. It's your call though.

**Comment by jdalton** [comment]
I'll reconsider it.

**Comment by jeffcharles** [comment]
:+1: thanks!
