### ISSUE TITLE
_.pluck not working with maps

### ISSUE THREAD

**Issue by MaluTom** [lodash/lodash#1039]
Hi,

I'm attempting to upgrade from lodash 2.4.1 to 3.5.0 and the following code snippet is not working with 3.5.0

```
var data=[{"bs":20229,"ts":"2015-03-10T00:00:56.000"},{"bs":28054,"ts":"2015-03-10T00:01:56.000"},{"bs":17957,"ts":"2015-03-10T00:02:56.000"}];
 var dataMap = data.map(function(v) {
        return [v.ts, v.bs];
      });

var x=_(dataMap).pluck(function(val) { return val[1]; })
console.log(x);
```

x evaluates to 20229,28054,17957 in 2.4.1 but only evaluates to ,, in 3.5

**Comment by jdalton** [comment]
The `_.pluck` method was never documented to support a callback. The 2.4.1 behavior was a side effect of it using `map` internally so use `map` instead.
