### ISSUE TITLE
Should there a difference between _([1,2,3]).each(function(){}) and _.each([1,2,3], function(){})?

### ISSUE THREAD

**Issue by fir3pho3nixx** [lodash/lodash#1040]
Hi

I recently received a breaking change on grunt-spawn when using the latest version of lodash. The only reason I selfishly prefer the former is because I like the jQuery style of invocation. Snippet below demonstrating the problem.

var _ = require('lodash');
console.log(' *** LODASH TEST *** ');
console.log('jQuery style');
_([1,2,3]).each(function(){
	console.log(arguments); // Outputs nothing
});
console.log('Functional style');
_.each([1,2,3], function(){
	console.log(arguments); // Outputs arguments, see below
});

/*** OUTPUT ***/

$ node index.js 
 *** LODASH TEST *** 
jQuery style
Functional style
{ '0': 1, '1': 0, '2': [ 1, 2, 3 ] }
{ '0': 2, '1': 1, '2': [ 1, 2, 3 ] }
{ '0': 3, '1': 2, '2': [ 1, 2, 3 ] }

Is this intentional or perhaps a bug?

~Gavin

**Comment by davidkpiano** [comment]
The output in the first style is wrapped. Use `_([1,2,3]).each(function(){...}).value()`

**Comment by fir3pho3nixx** [comment]
Ok, cool. 

So this change came about in version 3.<somewhere> I am guessing. Rechecked the docs and found it right there, apologies. 

Is this a general rule for wrapped/non-wrapped invocations or is there any other info I should be reading to gain a better understanding?

Thanks again.

**Comment by jdalton** [comment]
See https://lodash.com/docs#_.

**Comment by gildorwang** [comment]
Hi there, I understand why this happens, but the current behavior is odd to me. It actually caused a lot of regression bugs in our application. Consider the following code: 
````JS
_(nodes)
    .filter(function (node, i) { return i % 2 === 0; })
    .forEach(function (node) {
        var pos = node.getPos();
        // do something with pos
    });
````
I would assume `forEach` will iterate the collection immediately, as it did before. However it does not until I add `.value()` to the end. This is very confusing and inconvenient. And in my opinion, making `forEach` lazy does not make much sense. Can you reconsider it?

**Comment by octref** [comment]
@jdalton 
How about adding an optional flag to `_(value)`, like this:
`_(value, isLazy)`

**Comment by jdalton** [comment]
Nope. It's been chainable for more than 2 years. I think a `.value()` call is painless.

**Comment by jdalton** [comment]
lodash is also customizable so you can change the chaining behavior of `forEach`:
```js
var _ = require('lodash').runInContext();
_.mixin({ 'forEach': _.each, 'each': _.each }, false);
_([1,2,3]).each(function(v) { console.log(v); }); 
// => logs 1 then 2 then 3
```

**Comment by fir3pho3nixx** [comment]
Yeah, this is what happened to me. I had to re-plumb all my code to support .value(). I can deduce the breaking change happened after 2.4.1(current ver 3.x). Fair enough really ... major version has changed. :)

**Comment by fir3pho3nixx** [comment]
Mixin support is cool btw
