### ISSUE TITLE
Simpler but longer function names for FP newbies

### ISSUE THREAD

**Issue by koresar** [lodash/lodash#1043]
> Programs must be written for people to read, and only incidentally for machines to execute. 
[(c)](http://www.goodreads.com/quotes/9168-programs-must-be-written-for-people-to-read-and-only)

And

> There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.
[(c)](http://www.randomprogramming.com/2014/09/quote-of-the-week-hard-things/)

I know most of the lodash function names are well known functional style names. Although, lodash has about 300 functions. Remembering what they do is kind of hard. I keep lodash docs website opened without closing it for few months already.

Trying to teach a student I always find that it's really hard for them to remember what some of the lodash functions purpose is. Map and reduce names is something people can remember. It's good you introduced new `all` and `any` aliases. But there are few very short misleading names. Especially for newbies.

Examples. (It's just a quick list. I did not think about the names much.)

Array:
* `_.rest` -> the better name would be `_.allButFirst`.
* `_.zipObject` -> `_.composeObject`.
* `_.reject` -> `_.allBut` or/and `_.filterNot`.
* `_.sample` -> `_.pickRandom`.
* `_.after` and `_.before` -> `_.invokeAfter` or `_.callBefore`.
* `_.ary` -> confusing as hell. `_.acceptMaxArgsNumber`. Yeah, a very long one.
* `_.bindKey` -> `_.bindObjectFuncToArgs`
* `_.curry` -> `_.waitAllArgs`.
* `_.flow` -> too generic name. `_.invokeSequential` or kind of would be more clear.
* `_.momoize` -> `_.cacheCallResult`.
* `_.once` -> `_.invokeOnce`.
* `_.rearg` -> `_.rearrangeArguments`.
* `_.functions` -> `_.getObjectFunctions`.
* `_.invert` -> `_.invertKeysWithValues`.
* `_.keys` -> would be good to have alias `_.ownKeys`. Same for `_.ownValues`.
* `_.keysIn` -> same reasoning, `_.allKeys`. Same for `_.allValues`.
* `_.mapValue` -> this one is very clear actually. I wish all the rest were like it.
* `_.omit` -> `_.cloneExcept`.
* `_.pick` -> `_.cloneOnly`.
* `_.pair` -> `_.keyValuePairs`.
* `_.attempt` -> `_.getResultOrException`.

I understand that JS code doesn't like long names because traffic and typos. Although, people do better (functional) programming when function names do not allow many interpretations.

I am looking for a way to solve this issue. Any ideas?

P.S. I understand that I can create and maintain a separate module like "lodash-long-names". `require('lodash-long-names').assignAliases(_);`. Although, I think it's better to keep lodash activities under the same brilliant umbrella of @jdalton.

**Comment by StreetStrider** [comment]
Have a look at this issue at different angle. The problem of short names is in its context. LoDash functions belongs to different contexts, but placed in one flat namespace (`_`). I think this is by historical reasons: Underscore started as library with simple utility-belt functions which was absent in JS' std. And look at LoDash now: it works with arrays, objects, arrays of objects, functions, strings and less with other objects like dates and numbers. But they belong to one single namespace anyway. Look at documentation: it's also splitted into sections by context.

This is not the certain problem you speak about, but they have much in common. Many short names can be more descriptive, if they belong to descriptive context.

I personally stand for simple names, event if they're not fully descriptive, however they must be putted in such namespaces, that I can fastly determine what they do by its context.

**Comment by octref** [comment]
I don't think you'd have to remember all functions almost like reciting them. You'd better let the student understand the corresponding notions like curry, ary, memoization, so they would naturally remember the functions. These are jargons they are gonna be dealing with everyday if they become a programmer.

**Comment by koresar** [comment]
> Embrace simplicity in your product & in your code. The value is in what gets used, not what gets built.
[(c)](http://firstround.com/review/The-one-cost-engineers-and-product-managers-dont-consider/)

@octref It's not about students only. The majority of experienced programmers are not familiar with the jargon. I wish they could use lodash without a steep learning curve. I wish they could read the code without opening lodash docs or browsing through a source code.
We are facing developers migration from java/c#/php to JS. Is there a way they can fall in love with lodash without the timewasting pain of learning new wording for the things they already know?

@StreetStrider Namespacing would improve things. Although, not for every function name. For example `_.func.ary()` would look as mind blowing as it is now.

I beg you to look at the issue from FP newbies angle.

We can boost lodash popularity by lowering its learning curve. Agree?

**Comment by jdalton** [comment]
Many of the methods are inspired by the language (keys, map, filter, some, every, bind, find, findIndex, includes, indexOf, lastIndexOf, trim, isArray, spread), ruby (all, any, takeWhile, reject, dropWhile, chunk, detect, inject, sortBy, zip, trunc), haskell (rest, initial, head, tail, last, pairs, fold, foldr).

Besides being based on languages some have roots in several JS libraries like Prototype, MooTools, & jQuery too.

Methods like `curry`, `partial`, `memoize`, & `sample` are all terms developers should learn.
For example `ary` is based on [n-ary](http://en.wikipedia.org/wiki/Arity#n-ary).

Instead of long names I wouldn't mind helping review and contribute to a reference of the history-of or story-behind the APIs. I think that would expose your students to lots of other languages, history, & libraries.

**Comment by koresar** [comment]
Ok. Let's leave the learning curve as is.

Thanks for the fast decision making.
