### ISSUE TITLE
Feature: _.template recursive flag

### ISSUE THREAD

**Issue by sheo13666** [lodash/lodash#1044]

**Comment by sheo13666** [comment]
@jdalton why closed?

**Comment by jdalton** [comment]
You've gotta put a bit more effort into a feature request besides a title :smile_cat: 
You're essentially requesting I take on all the effort of sussing out what you want, implementing it, testing it, and supporting it until a major version bump and all you could manage was an issue title. That's a little too one sided for my liking.

**Comment by d10** [comment]
Yeah, what does recursive even mean? ;)

**Comment by sheo13666** [comment]
@d10 
```javascript
options = {
    url: 'http://domain.ru/<%= path %>',
    path: 'path/subPath/',
};
_.template('<%= url %>', options);
```

**Comment by jdalton** [comment]
@sheo13666 Thank you for the usage example!

I want to keep `_.template` simple as there are other [more robust templating alternatives](http://handlebarsjs.com/) already.
You can tackle this by:
```js
_.template('<%= _.template(url)(obj) %>')(options);
options.path = 'anotherPath/subPath';
_.template('<%= _.template(url)(obj) %>')(options);
```

**Comment by sheo13666** [comment]
@jdalton fast solution https://gist.github.com/sheo13666/9ad22fab960294c44f0c

**Comment by jdalton** [comment]
That's a pretty neat approach : )
