### ISSUE TITLE
More descriptive readme and website

### ISSUE THREAD

**Issue by javierbyte** [lodash/lodash#1045]
The readme doesn't tell much about what lodash can do. It can be very helpful for people that just discovered lodash to have a list of features.

Also, as lodash is becoming more popular than underscore, we shouldn't asume that people know what underscore is in the website. Instead of saying "Features not in Underscore" we can say "Features in lodash" and then highlight in some way the ones that are lodash exclusive.

I can help with this, but my english is not very good.

Thank you for the excellent library!

**Comment by jdalton** [comment]
Hi @javierbyte! I want to keep the master branch readme light and used primarily as a spring board to other areas (site, roadmap, documentation). That said I'm open to tweaking it's wording/sections. As per tweaking the messaging I'm OK with that too. You can create a PR against the [npm branch readme](https://github.com/lodash/lodash/blob/npm/README.md) as that is what the site is based on.

**Comment by octref** [comment]
I think I can help here. 

More and more people start to use lodash. Two types of them are having a hard time getting up to speed.

- As @javierbyte said here, people who have never used underscore & jump straight to lodash.
- And as @koresar mentioned in #1043 , people who have little exposure to FP.

I think it would be helpful to include a tutorial on the website, something like "Getting Started", where you'd 
- give an overview
- explain some major features like lazy-evaluation, mixin, etc
- explain some concepts like customizer, iteratee, predicate. (and with this you don't have to do things like explaining `predicate` with `_.property`, `_.matchesProperty`, `_.matches` everytime)
- explain things like `[values] (…*)` cuz some people might not know Python
- whatnot

> Instead of long names I wouldn't mind helping review and contribute to a reference of the history-of or story-behind the APIs. I think that would expose your students to lots of other languages, history, & libraries.

I can give it a shot. But I certainly need your help.
Ideally something like a `lodash.com/story-behind` that explains the history/naming-choice of each function, each linked from the definition at `lodash.com/docs` .

However, compared to the story-behind, I think the tutorial is more important. 

Finally, usability-wise, I have a suggestion for the doc site:
- Get some keybindings so one could navigate without using mouse. For example, /map goes to `_.map`, /find goes to `_.findIndex`, etc.
