### ISSUE TITLE
Unexpected result returned by _.where

### ISSUE THREAD

**Issue by mtrias** [lodash/lodash#1046]
Hey! 

Apologies if something changed in `_ 3.5` that i'm not aware of, but today i found a test failing in my project because _.where returned an unexpected result.

Please take a look at this plunkr: http://plnkr.co/edit/3vkqWrC1T1Lh9XinjdEk?p=preview

**Comment by jdalton** [comment]
[_.where](https://lodash.com/docs#where) does not accept a predicate. What you were seeing was an implementation detail leaking out in pre 3.0. You should use `_.filter` instead.

**Comment by mtrias** [comment]
Awesome!. I knew it must be me. Thanks for your fast response :)

**Comment by jordan112** [comment]
Is there a reason to ever use _.where since it seems like _.filter supports both a function predicate and an json to filter by?

**Comment by jdalton** [comment]
> Is there a reason to ever use _.where since it seems like _.filter supports both a function predicate and an json to filter by?

Naw, it comes down to preference.
