### ISSUE TITLE
Add _.update (aka non-mutating _.assign)

### ISSUE THREAD

**Issue by brandonhorst** [lodash/lodash#1047]
`_.assign` and `_.merge` cause problems when working with immutable data, because they modify the inputs.

```js
let x = {a: 1, b: 2}, y = {a: 3}
_.assign(x, y) // {a: 3, b: 2}
x // {a: 3, b: 2}
```
```js
let x = {a: 1, b: 2}, y = {a: 3}
_.update(x, y) // {a: 3, b: 2}
x // {a: 1, b: 2}
```
Dummy implementation:
```js
function update(x, y) {
  return _.assign(_.clone(x), y)
}
```

**Comment by StreetStrider** [comment]
```javascript
_.assign({}, x, y);
```
Huh?

**Comment by jdalton** [comment]
Yap [_.assign](https://lodash.com/docs#assign) is based on ES6 [Object.assign](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object.assign) and [_.merge](https://lodash.com/docs#merge) is based on [jQuery.extend(true, ...)](http://api.jquery.com/jQuery.extend/#jQuery-extend-deep-target-object1-objectN).

@StreetStrider has the right idea.

**Comment by ejc3** [comment]
We got bit by an accidental mutating _.merge in a Node.js app (it mutated a global shared object used and the changes affected subsequent requests). We could write our own immutableMerge object or always remember to make the first argument {}, but it would be nice if the library had an object for something like this.

Thanks!

**Comment by jdalton** [comment]
You can use [lodash/fp](https://github.com/lodash/lodash/wiki/FP-Guide) for non-mutating flavors of methods.

**Comment by ejc3** [comment]
Sorry, I missed this:  "with its methods wrapped to produce immutable auto-curried iteratee-first data-last methods"

Thanks!

**Comment by jvitela** [comment]
You can also use setWith and clone together:

```
let x   = {a: 1, b: 2}
let x2 = _.setWith(_.clone(x), 'a',  3,  _.clone);
x  // {a: 1, b: 2}
x2 // {a: 1, b: 2}

```
