### ISSUE TITLE
why _.sum cannot be called with iteratee?

### ISSUE THREAD

**Issue by qsona** [lodash/lodash#1048]
Hi, I like that some math methods are added, but I found that `_.sum` doesn't expect iteratee function as the 2nd argument.

```js
_.sum([{a:1}, {a:2}], 'a') // I expected 3 but got 0
```

Is there any reason?
Thanks.

**Comment by octref** [comment]
`_.sum(_.pluck([{a:1}, {a:2}], 'a'))`
[_.sum doc](https://lodash.com/docs#sum)

It's ok if you want an iteratee added as a feature, but don't just "expect" something. 
The doc clearly says it doesn't take an iteratee.
Check the doc when in doubt.

**Comment by qsona** [comment]
I'm sorry if my English is not good. I read the doc and I created this issue because I think that there may be clear reason why `_.sum` doesn't get iteratee by design. Almost all lodash methods get iteratee if it can,  except `_.sum`.

**Comment by octref** [comment]
I guess @jdalton wanted to keep `add` and `sum` simple, but let's hear what he says.
And maybe the guy who wrote it:
/cc @thejameskyle

**Comment by jdalton** [comment]
@qsona Please send the PR. @octref is right, I did want to keep it simple though that was diminished when I had to have `_.sum` support collections. Since `_.max` and `_.min` support an iteratee so should `_.sum`. In v4 we'll split it out into `_.maxBy`, `_.minBy`, `_.sumBy` ([`sumBy` to love](https://www.youtube.com/watch?v=kijpcUv-b8M)).

**Comment by jdalton** [comment]
Closes via #1053.

**Comment by qsona** [comment]
@jdalton Maybe I understood what you mean. There are many methods that takes iteratee, and almost all of them require it strongly (calling without an iteratee is not a main usage). But `_.max`, `_.min`, _.sum` and `_.uniq` seem to be exceptions, so they should be split out to `_.xxxBy`. ( `_.uniq` is also better to be spilt to `_.uniqBy`, isn't it?)
Anyway, I frequently want to get summation of collection with a mapping so I like sumBy too :) Thanks to accepting the PR.
