### ISSUE TITLE
`sortBy`, `max`, `min` doc inconsistency

### ISSUE THREAD

**Issue by octref** [lodash/lodash#1049]
The function signature uses `iteratee` but the description uses `predicate`. 

Possible to confuse some people.

In `max`, we even have mixed use of `iteratee` and `predicate` within just the function description

`_.max(collection, [iteratee], [thisArg])`

> Gets the maximum value of collection. If collection is empty or falsey -Infinity is returned. If an iteratee function is provided it is invoked for each value in collection to generate the criterion by which the value is ranked. The **iteratee** is bound to thisArg and invoked with three arguments; (value, index, collection). 

> If a property name is provided for **predicate** the created _.property style callback returns the property value of the given element. 

> If a value is also provided for thisArg the created _.matchesProperty style callback returns true for elements that have a matching property value, else false. 

> If an object is provided for **predicate** the created _.matches style callback returns true for elements that have the properties of the given object, else false.

I'm actually not quite sure which one you want -- `iteratee` or `predicate`. Can you clarify the difference between these two notions a little bit?

**Comment by d10** [comment]
This should be iteratee. The difference between the two of them is that predicates are used for filtering values, i.e. returning a Boolean value eg. filter, some, any, while iteratee is for function like map/ to return a value which is used to construct the final value.

**Comment by octref** [comment]
I just found `_.sortedIndex` also suffer from this mismatch. It seems this paragraph is copied verbatim in a lot of places:

> If a property name is provided for predicate the created _.property style callback returns the property value of the given element. 
> If a value is also provided for thisArg the created _.matchesProperty style callback returns true for elements that have a matching property value, else false. 
> If an object is provided for predicate the created _.matches style callback returns true for elements that have the properties of the given object, else false.

As I commented [here](https://github.com/lodash/lodash/issues/1045), how about we write a "Introduction" or "Getting started", where you'd explain all the terms? This way we can keep the doc more succint, and make it easier for users to learn lodash.

**Comment by jdalton** [comment]
Thanks, for staying on top of the docs you all!

**Comment by octref** [comment]
@jdalton 
Just wondering, what's your opinion of centralizing explanation of some common terms used in lodash like `predicate`, `iteratee`, `customizer`, and leave this kind of verbatim out of doc to keep the doc succint?

24 occurence of this on the doc:
> If a property name is provided for predicate the created _.property style callback returns the property value of the given element. 
> If a value is also provided for thisArg the created _.matchesProperty style callback returns true for elements that have a matching property value, else false. 
> If an object is provided for predicate the created _.matches style callback returns true for elements that have the properties of the given object, else false.
