### ISSUE TITLE
How to include in project compiled with Closure Compiler?

### ISSUE THREAD

**Issue by gcaini** [lodash/lodash#1051]
If I understand correctly, to maximize the benefits of Closure Compiler's dead code removal, I should compile lodash together with my own code, so that the compiler knows which lodash functions to keep around. (I know I can make a custom build of lodash with only the needed functions, but I'm hoping to let the compiler keep track of them.) Is this possible?

I'm assuming that lodash supports the Closure Compiler because the lodash-cli tool uses the Closure Compiler on lodash.

I tried concatenating the lodash.js file from the github release to my code and running the compiler on that, and the compiler complained about undeclared variable "module" in "var freeModule = objectTypes[typeof module] && module && !module.nodeType && module;". (It may be relevant that I run the compiler with --warning_level=VERBOSE.) I could try adding "module" as an extern, but I thought I'd ask for an "official" solution before trying hacks.

**Comment by jdalton** [comment]
We use `warning_level` of `quiet`. Also just a heads up I wouldn't recommend running the Closure Compiler in advanced mode against lodash because it requires lots of property escaping and corrections for overly aggressive minifications (it removes code it thinks is dead but is required for feature detections).

**Comment by d10** [comment]
You can also use [find-used-lodash](https://github.com/pgilad/find-used-lodash) with lodash-cli to build custom lodash builds using only the functions you use.
