### ISSUE TITLE
Browserify bundle with require("lodash") crashes the chrome remote debugger 

### ISSUE THREAD

**Issue by timcash** [lodash/lodash#1052]
Browserify bundle with require("lodash") crashes the chrome remote debugger

using lodash 3.3.0 and 3.5.0

e.g. 

    // install lodash
    npm install lodash

    //in main.js
    var lo = require("lodash")
    
    // on the command line
    browserify main.js --outfile bundle.js

    //in index.html
    <script type="text/javascript" src="bundle.js"></script>

Next attach an android device via usb and begin remote debugging
the debugger will crash after a second or two.

I have tried many other npm modules with the method and they all seem to work fine in the remote debugger.

As a side note using webpack instead of browserify seems to work fine.

**Comment by jdalton** [comment]
Hi @timcash! I'm not sure if there's anything actionable for us at the moment. Let me know if you find out more.
