### ISSUE TITLE
`_.isElement(document.body)` is returning `false`.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [lodash/lodash#1055]
I am testing this in plunker. And i saw `_.isElement(document.body)` is returning false. But as per the documentation, it should return true.

**Comment by megawac** [comment]
What version - can't reproduce

**Comment by jdalton** [comment]
I can't repro either, we have unit tests for this stuff too that run [in our supported browsers](https://saucelabs.com/u/lodash).

**Comment by rajeshwarpatlolla** [comment]
Have a look at this plunker. Check out the console.
http://plnkr.co/edit/AYgHD72j4ujgvDKHXfng?p=preview

**Comment by miguelmota** [comment]
@rajeshwarpatlolla that's because the script is in the head so document body has not had a chance to load. Move the script to the body, or wait until DOMContentLoaded.

**Comment by octref** [comment]
As @miguelmota said, you have to wait until DOM loaded.
In this case, you are using a very outdated version of Underscore.

![image](https://cloud.githubusercontent.com/assets/4033249/6660623/cf2e6c7a-cb73-11e4-8282-68a894d1326b.png)

**Comment by rajeshwarpatlolla** [comment]
Thanks @miguelmota.
