### ISSUE TITLE
Merge two collection2?

### ISSUE THREAD

**Issue by wanjarus** [lodash/lodash#1058]
I'm using merge or union two collections then result not answer need.

and I need like this: 
result:
```js
[
  {code: 'A', name: 'SuperSong'},
  {code: 'B', name: 'Sapoka', desc: 'For Beginer'},
  {code: 'C', name: 'Dokoto', desc: 'For PP2'},
  {code: 'D', name: 'Karato'}
]
```
collection s1:
```js
[
  {code: 'A', name: 'SuperSong'},
  {code: 'B', name: 'Sapoka'},
  {code: 'C', name: 'Dokoto'},
  {code: 'D', name: 'Karato'}
]
```

collection s2:
```js
[
  {code: 'B', desc: 'For Beginer'},
  {code: 'C', desc: 'For PP2'},
]
```

**Comment by hgwood** [comment]
Try using `indexBy` before merging, so lodash knows which objet should be merged with which. It will convert your arrays to objects though, so you will need to call `values` at the end.

```js
_.values(_.merge(
  _.indexBy(collection1, "code"),
  _.indexBy(collection2, "code")))
```

**Comment by wanjarus** [comment]
Its works!
Thank you.

**Comment by wanjarus** [comment]
dear

Can i delete field 'code' in collection s1 after _.indexBy(collection2, "code") ?

result collection s2 as i need:
{
  "B": {desc: 'For Beginer'},
  "C": { desc: 'For PP2'},
}

Thank you.

**Comment by hgwood** [comment]
Yes you can.

**Comment by wanjarus** [comment]
Thanks.
