### ISSUE TITLE
Add function to get nested property value

### ISSUE THREAD

**Issue by rfgamaral** [lodash/lodash#1060]
The only thing I really miss from lodash is the `get` function that MOUT implements to get nested property value, returning `undefined` if it doesn't exist.

MOUT API Documentation: http://moutjs.com/docs/latest/object.html#get

Would it be possible to implement a similar function for lodash?

**Comment by KenanY** [comment]
@rfgamaral It's on the [roadmap](https://github.com/lodash/lodash/wiki/Roadmap). https://github.com/lodash/lodash/issues/700

**Comment by jdalton** [comment]
I think we'll end up with accepting an array are list of args to avoid the dot delimiter issue. It should also allow adding the feature without a major bump. Let's take it to PRs.

**Comment by rfgamaral** [comment]
I know one should never ask such thing, but any ETA? Just so I can decide the best course of action for my problem. But I understand if no estimate can be made.

Just for context, here's my actual use case:

We have this Angular library that is used across multiple projects in the company and we have "misc utils" factory which implements, well, utils methods. Some of them are better implemented (and unit tested) on lodash (an open source library used by lots of people, it's tested on real case scenarios) and one of them (this get), it's not.

The idea is to get all these common functions out of this "misc utils" factory and just use lodash. But the idea is to provide an Angular "lodash" factory (with just the methods we need with the grunt plugin) instead of using the global `window._`. This is already done. The thing is, I just want to do this once, for one library. Currently, lodash is missing this `get` which we really need. And I really don't want to include another library (case in point, MOUT) just for a single method.

Not to put any pressure or anyone, just wanted to clarify my scenario.

Thanks for the replies :)

**Comment by sankargorthi** [comment]
You can always write your own mixins and remove them when the utility lands. There are a few examples of deep object access in the wild.

**Comment by octref** [comment]
I'll do some research and give it a try tomorrow.
@jdalton , can I get some clarification:

1. Do you want to improve on `_.pluck`, so it can take a list of properties, or would you like a new function?
2. Is `get` a too generic name? To keep it consistent, is it better to name it something like `pluckDeep` or `pluckNested`?
3. Does this look right?
```
var foo = {
  bar: {
    baz: 'qux'
  }
}

// _.get(object, props)
_.get(foo, 'bar', 'baz')
// -> 'qux'
_.get(foo, ['bar', 'baz'])
// -> 'qux'
```

**Comment by jdalton** [comment]
@phated, I think you have opinions on this right?

**Comment by octref** [comment]
I'll wait for more comments before working on it.

**Comment by octref** [comment]
@phated Hey do you mind sharing with us how you think about this issue :-)

**Comment by rmcdaniel** [comment]
@octref I don't think _.get(foo, ['bar', 'baz']) should return 'qux' because _.pluck(foo, 'bar') would not return {baz: 'qux'}; it would return undefined.

**Comment by rmcdaniel** [comment]
Here is sort of what I am thinking:

````
function get(collection, keys) {
    return _.map(collection, function(value, index, collection) {
        return _.reduce(keys, function(accumulator, value, index, collection) {
            return accumulator[value];
        }, value);
    });
}
````

http://jsfiddle.net/xhtLmy3w/

**Comment by megawac** [comment]
Is theres going to be a `getPath` and a `hasPath`. Also whoever submits a pr I recommend you checkout [underscore-contribs implementation](https://github.com/documentcloud/underscore-contrib/blob/master/underscore.object.selectors.js#L79-108)

**Comment by octref** [comment]
@rmcdaniel 
You're right. I was thinking about `_.property`.

Actually I'm wondering how we do the "deep property helpers" feature.
How about creating a `_.deepProperty`, which is like `_.property`, but takes an array, and allow iteratee to take an array and create a `_.deepProperty` callback?

```
var foo = {
  bar: {
    baz: 'qux'
  }
};
_.deepProperty(['bar', 'baz'])(foo);
// => 'quz'
_map([foo], ['bar', 'baz'])
// => ['quz']

**Comment by StreetStrider** [comment]
> and allow iteratee to take an array and create a _.deepProperty callback?

This is the only strong reason to have it implemented in LoDash. For any other cases there are a bunch of modules solving that certain task. For instance [object-path](https://github.com/mariocasciaro/object-path).

**Comment by jdalton** [comment]
For naming consistency it would be `_.propertyDeep` (like `_.cloneDeep` and `_.flattenDeep`)

**Comment by jdalton** [comment]
Moving discussion over to #1081.
