### ISSUE TITLE
Why can't _.fill populate an empty array?

### ISSUE THREAD

**Issue by tandrewnichols** [lodash/lodash#1063]
After some trial and error, I understand how `_.fill` works. However, I initially thought I'd be able to do something like `_.fill([], 'blah', 0, 5)` to get `['blah', 'blah', 'blah', 'blah', 'blah']`. Is there some reason this _can't_ work? Or maybe a `_.populate` to create an array of default values? I understand what `fill` does, but not _why_ it only does that. Is there a technical (or semantic) reason that `_.fill` can't populate non-existent indices?

(FWIW, `_.fill([0, 0, 0], 'blah', 0, 5)` functions similarly. It returns `['blah', 'blah', 'blah']` rather than `['blah', 'blah', 'blah', 'blah']`.)

**Comment by jdalton** [comment]
`_.fill` is modeled on ES6 [Array#fill](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-array.prototype.fill). We'll keep it aligned for the time being.

**Comment by tandrewnichols** [comment]
Got it. Didn't realize there was a prototype version. For anyone else interested, you can do `_.fill(new Array(7), 'blah')` to achieve a kind of defaults thing.

**Comment by jdalton** [comment]
You can even nix the `new` `_.fill(Array(7), 'blah')`. I just noticed `_.fill` is missing a doc example. I'll add that.

**Comment by online-lorno** [comment]
Question, is `_.fill(Array(4), [])` equal to `[[], [], [], []]`?

**Comment by jdalton** [comment]
An array is an object and so by using it as the fill value you're saying you want to fill with the same array value like
```js
var a = [];
var test = [a,a,a,a];
```

This is how built-in `Array(4).fill([])` works too.
