### ISSUE TITLE
Allow callback for step parameter in _.range

### ISSUE THREAD

**Issue by shanimal** [lodash/lodash#1064]
Obviously I can do what im trying to accomplish here in other ways, but having a callback for step would be pretty awesome.
```js
var min = new Date("9/11/2001"),
    max = new Date(),    
    step = function(currentValue){
      currentValue.setMonth(currentValue.getMonth() - 1);
      return currentValue;
    }; 

_.range(min, max, step);
```

**Comment by jdalton** [comment]
The range params `start` and `end` are coerced to numbers so `step` would be receiving those and not a date object. This feels like it would be better as another method or part of a date helper.
