### ISSUE TITLE
Errors in documentation examples

### ISSUE THREAD

**Issue by venning** [lodash/lodash#1065]
After noticing an error in one of the **documentation examples**, I ran them all through a script and found a few more.  There are small errors in three examples that I can fix:

* [the example for **`_.trim`**](https://lodash.com/docs#trim) is missing a single-quote
* [the example for **`_.matchesProperty`**](https://lodash.com/docs#matchesProperty) is using the wrong starting `users` object to produce the stated result
* [the example for **`_.property`**](https://lodash.com/docs#property) is missing a single-quote

There are also errors in four more examples that I'm not sure exactly how to fix:

* [the example for **`_.runInContext`**](https://lodash.com/docs#runInContext) assumes that `_.add` doesn't exist by default, which is no longer true as of v3.4.0; so the example not only makes less sense, it also shows `lodash.isFunction(lodash.add);` returning `false` when it will now return `true` in the current version; I'm not sure what would make a better example
* [the example for **`_.thru`**](https://lodash.com/docs#thru) errors when `_.last()` returns a `Number` and then tries to call the `thru` method of that `Number`; I have no idea what you're trying to do with that example, so I have no suggestions on how to correct it
* [the example for **`_.forEachRight`**](https://lodash.com/docs#forEachRight) states that it "returns the array", but it actually returns a concatenation of the array's contents care of `Array.prototype.join`; this is probably a copy-and-paste from `_.forEach` where the final chained call is to `_#value`; not sure if you'd rather change it back to `_#value` or fix the result description
* [the example for **`_.escapeRegExp`**](https://lodash.com/docs#escapeRegExp) does not show *slashes* being escaped, which is matched by the description which also does not list *slashes* as being escaped; but [the codebase shows](https://github.com/lodash/lodash/blob/master/lodash.src.js#L120) *slash* being part of `reRegExpChars`; the documentation links to this [article on `RegExp` characters](http://www.regular-expressions.info/characters.html#special) which does not list *slash* as special; either the documentation and example need to show *slash* as being escaped or the code needs to remove *slash* from the characters that are escaped

My assumption is that you are using `lodash.src.js` for the codebase and deriving documentation from that.  If that's the case, I'll submit a pull request for the first three fixes and either let you fix the next four or I'll submit a pull request for those on your suggestion on which way you'd like to fix them.

*(I should state that I've never submitted a pull request for an open source project before, so I may be going about this haphazardly.)*

**Comment by jdalton** [comment]
@venning these are great thanks!

**Comment by octref** [comment]
Great work @venning :+1:  ! I'm curious what's your script though.

**Comment by venning** [comment]
Ugh.  Extremely ugly.

Starting from [this example](https://bitbucket.org/ariya/missing-doc/src/master/missing-doc.js) of how to parse the source file: `esprima` into `estraverse` into `doctrine` looking for `leadingComments` on each node in the AST, parsing for `@example` tags.  That's pretty copy-and-paste, but make sure to set up `doctrine.parse` to accept badly-formed JSDoc or it will only pick up 66 of the 187 `@example` tags.  This `options` object worked for me: `{ unwrap: true, tags: [ 'example' ], recoverable: true }` (It's the `recoverable` that's key.)  I'm really interested in what you use to acutally derive the documentation, as that probably would save some time.

Once there, go through the example line-by-line, accumulating code until coming to a line that starts with `// =>`, then run the code through **`require('vm').runInContext(code, sandbox)`** making sure to reuse the same `sandbox` for a given example block so that it can keep building the context, starting with a global context object that includes `_`.  Then compare the result of running that code segment with what came after `// =>`.

There were many, many edge cases:

* Lots of results were just English descriptions of what to expect, so I had to manually check those.
* Anything random number will (probably) be wrong when run.
* Some things required objects I didn't have; e.g., `document.body` or `jQuery` or `WeakMap`.
* Anything that was a `var` statement returns undefined in the `vm` so I had to keep track of the last `var` assigned and return it again to check.

Many had to be hand-tested and others I'm just assuming work.

I should have gone to sleep hours ago, but this was bothering me too much, so my code has deteriorated badly.  If you actually want to take a look, I can clean it up a bit and throw it in a *gist*.

**Comment by venning** [comment]
I should note that I only know about `require('vm')` by examining `n_` and seeing `require('repl')`.

**Comment by jdalton** [comment]
> If you actually want to take a look, I can clean it up a bit and throw it in a gist

Wow, yes please!

**Comment by venning** [comment]
@jdalton & @octref 

https://gist.github.com/venning/fa50c61e9c20b26a8f49

**Comment by octref** [comment]
@venning 
Well done, sir. Thanks a lot! :smiley:

**Comment by jdalton** [comment]
Thanks @venning!

**Comment by d10** [comment]
Seems similar to @dtao’s [autodoc](https://github.com/dtao/autodoc) library.
