### ISSUE TITLE
dicussion: .matches works but makes lodash very messy conceptually

### ISSUE THREAD

**Issue by robertbak** [lodash/lodash#1067]
Hey, I've noticed there are some bugs related to the .matches behaviour (#892, #899, #909, #937,  #939, #945 ). It does feel very weird. It works but makes lodash very messy conceptually. It seems that .matches is really .matchesOwnProperties, just with a misleading name and description (_"returns true for elements that have the properties of the given object"_ should probably be something like _"returns true for elements that have the properties of the given object as their own, non-inherited properties"_). It might be the most natural way to match objects (although opinions will probably vary) but certainly not the most general. It's a bit like naming a function .isAnimal while it only works for mammals. This confusion is amplified by the fact that there's .matchesProperty which is more specific than .matches in one aspect (finds only a single property) but more general in that it looks for both own and inherited properties. 

This also means that suddenly most examples only show part of the story (they all use own properties where there's little difference), and to show how a function behaves would require to show cases where both types of properties (own and inherited) are defined. Again, this shows that the use of lodash got much more complex, and being able to just read an example and know what a function does was a great thing, especially for people who are new to it. 

On top of this before someone uses something like find he needs to understand much more about lodash implementation and also make sure any object he or she might be looking for is not using inheritance (which is ok in case they are created by you, but in fact requires checking the internals of any library you might be getting objects from (at least by hasOwnProperty)). So even if someone knows the difference between .matches and .matchesProperty going from searching by a single property to matching by 2 is suddenly a whole big thing, and even when searching by a single property the difference between these two is a debugging nightmare waiting to happen:
```_.result(_.find(users, 'active', false), 'user');```
```_.result(_.find(users, {'active': false}), 'user');```

**Comment by jdalton** [comment]
Keep it simple. Keep it short. That said your timing is pretty great as I'm loosening up some of the restrictions on `matches` because it is effecting usability.

**Comment by robertbak** [comment]
Awesome, thanks! I started with a simple issue but found that it was already closed as invalid before ;)

**Comment by theoephraim** [comment]
Just wanted to chime in that when using lodash with an ORM, this has been causing lots of sneaky bugs in our codebase migrating (our code and our heads) from v2 to v3.

I'd think either an alternate set of methods, or some type of flag that puts lodash into a more relaxed comparison mode would help?

**Comment by jdalton** [comment]
@theoephraim the loosening of `_.matches` and related methods is already in v3.6 which should be more v2 like.
