### ISSUE TITLE
deburr not working for certain strings

### ISSUE THREAD

**Issue by DrDanRyan** [lodash/lodash#1070]
I am trying to fix some filenames that have non-standard characters and I thought that `deburr` was going to be a big help. However, it doesn't have any effect on certain strings, i.e. (copy and pasted from a filename giving me trouble):
Etchéa Art Déco

Is it because this string is encoded using something other than Latin-1? How would I be able to tell that?

**Comment by jdalton** [comment]
Yap it's because your character isn't the latin-1 flavor:
```js
'é' === 'é' // false
```

They sure do look the same though. I'll dig in and see if we can expand to accept some of these.

**Comment by jdalton** [comment]
@mathiasbynens halp!

https://mothereff.in/js-escapes#1%C3%A9%20e%CC%81
```js
'é é'
// => '\xE9 e\u0301'
```

**Comment by jdalton** [comment]
These are a set of [combining diacritical marks](http://en.wikipedia.org/wiki/Combining_Diacritical_Marks).

**Comment by mathiasbynens** [comment]
https://mathiasbynens.be/notes/javascript-unicode#accounting-for-lookalikes

**Comment by mathiasbynens** [comment]
@jdalton You could just [strip combining marks](https://github.com/mathiasbynens/strip-combining-marks).

**Comment by jdalton** [comment]
Nice!

**Comment by jdalton** [comment]
Cool. What's the reason your regexp is so complex compared to something like `/[\u0300-\u036F]/g`.

**Comment by jdalton** [comment]
Ah I see yours covers more than just those outlined [here](http://en.wikipedia.org/wiki/Combining_Diacritical_Marks).

**Comment by jdalton** [comment]
@mathiasbynens What are your thoughts on limiting removal to the smaller subset?

**Comment by mathiasbynens** [comment]
strip-combining-marks looks for characters followed by one or more combining marks, and then replaces such groups with just the chars. But for deburr you don’t need this robustness — you could just remove all combining chars regardless of what precedes them. For that, all you need is [the last capturing group here](https://github.com/mathiasbynens/strip-combining-marks/blob/4b635be0b92e275c3aa7be1591a6f4212bb5770c/strip-combining-marks.js#L20) At the moment, that’s:

```
([\u0300-\u036F\u1AB0-\u1AFF\u1DC0-\u1DFF\u20D0-\u20FF\uFE20-\uFE2F]+)
```

Seems compact enough, no?

**Comment by jdalton** [comment]
Rock. I think I'll do a combo of the common combined diacritical marks and the half marks:
```js
/[\u0300-\u036F\uFE20-\uE23]/g
```
