### ISSUE TITLE
Documentation: predicate and iteratee mixed up

### ISSUE THREAD

**Issue by venning** [lodash/lodash#1071]
(Referencing #1049, this is something that I encountered as well.)

After noticing a mix of `iteratee` parameters with `predicate` descriptions, I repurposed the documentation checker to look for offending descriptions.  The following all take `iteratee` as a parameter but reference `predicate` in their descriptions:

* [`_.uniq`](https://lodash.com/docs#uniq)
* [`_.countBy`](https://lodash.com/docs#countBy)
* [`_.groupBy`](https://lodash.com/docs#groupBy)
* [`_.indexBy`](https://lodash.com/docs#indexBy)
* [`_.map`](https://lodash.com/docs#map)

The current documentation on lodash.com contains more examples of this than those five, but the current codebase seems to have fixed all but these five.  There are no examples of the opposite problem (`predicate` for `iteratee`).  [Script for checking this here](https://gist.github.com/venning/55173b5e5f80aea39995).

*I noticed the use of `@param-` to hide params that are used only for functional purposes.  Doctrine does not parse them correctly, which is probably the point.  There are no `iteratee` or `predicate` params hidden this way, as far as I can tell.  If there are other subtleties to the documentation that affect this, I missed them.*

---

Additionally, I had a similar idea to @octref's regarding [pulling out the verbatim descriptions](https://github.com/lodash/lodash/issues/1049#issuecomment-79081841) of `iteratee`, `predicate`, etc and replacing them with references describing how to use them.  My tendency when reading the docs is to assume that the lines are repeated because they are subtly different between individual functions, with some sort of function-specific nuance.  That means I read them each time, which is slow and, assuming they are in face identical, unnecessary.  I can mock up an example or two of how to represent this differently, if there's desire.

**Comment by jdalton** [comment]
>  I can mock up an example or two of how to represent this differently, if there's desire.

Sure, go for it.

**Comment by venning** [comment]
Alright, probably some time tomorrow.

**Comment by octref** [comment]
@venning 
Thanks a lot for picking up that idea :+1:
