### ISSUE TITLE
_.and, _.or, and _.not for combining predicates?

### ISSUE THREAD

**Issue by aearly** [lodash/lodash#1072]
Apologies if this has been suggested before, it's practically impossible to search for.

What would you think about adding `_.and`, `_.or`, and `_.not` combinators that allow you to combine predicates?  With these functions, you could do things like:

```js
var onlyNonEmptyArrays = _.filter(coll, _.and(Array.isArray, _.not(_.isEmpty));

var isCollection = _.or(_.isArray, _.isPlainObject, _.isArguments);
```

**Comment by jdalton** [comment]
The names `_.and`, `_.or`, and `_.not` are used for lots of things. To create these 3 methods we would use  a helper function. I think the utility is in that function. Would you like to brain storm usage and argument signature of that?

**Comment by aearly** [comment]
A single helper method might not be possible because the "and" and "or" versions are *n*-ary, while "not" is unary.

I see that lodash-contrib adds a `_.not` function that takes in a boolean, not a predicate. (`_.not(true) === false`)  The same pattern could be expanded to `_.and` and `_.or` functions that take in booleans.  (`_.or(true, false) === true`) Maybe the helper function would be a function that combines predicates in a certain way?

```js
// either this is what _.or is, or you have to define it yourself
function or(a, b) { return a || b; }

// _.combinePredicates could take in an array or be variadic
var isCollection = _.combinePredicates(or, [_.isArray, _.isPlainObject, _.isArguments]);
```

The implementation of this would just be a fairly basic `reduce` operation.

This doesn't work for the "not" combinator.  Perhaps it could be called something like `_.inverse`?

**Comment by jdalton** [comment]
Hmm, let's have this simmer a bit. If you want, create a mixin lib that tackled this to proof out various APIs.

**Comment by Delapouite** [comment]
Nice proposal @aearly 

In Ramda, these functions are part of the logic category : http://ramdajs.com/docs/#not

**Comment by jdalton** [comment]
@Delapouite You're mistaken. The they have the same name, like those [in lodash-contrib](https://github.com/TheNodeILs/lodash-contrib/blob/v241.4.15/_.util.operators.js#L114-L116) but they are not what the original methods proposed.

**Comment by StreetStrider** [comment]
The proposed `not` I call  [`negate`](https://github.com/StreetStrider/aux.js/blob/3912116fa71d016c16db56304fc06e7733d36990/fn/negate.js). `and`, `or` are like compose but for predicates. Might be interesting. But this names are become ambiguous outside of the «functools context».

Ramda's `not` is just a function analogue for operator `!` to use it in compositions & predicates.

**Comment by StreetStrider** [comment]
Instead of `and`, `or` can be used `conj` and `disj` (like conjunction and disjunction). And LoDash already has `negate`, we forgot about it.

**Comment by aearly** [comment]
I had overlooked `_.negate` -- that is exactly what i propsoed `_.not` to be.

`R.and` and `R.or` are like lodash-contrib `_.and` and `_.or` -- they are functions that wrap the boolean operators.  The only place I've seen something like this implemented is in gcanti's fcomb:  https://github.com/gcanti/fcomb/blob/master/index.js#L21

There is some similarities in feel between what I propose and `_.every` and `_.some`, but instead of matching a list of values to a single predicate, we are matching a list of predicates to a single value (or rather, returning a function that does that).

I think `conj` or `disj` would be confusing -- in clojure, those functions add and remove items from collections.

**Comment by megawac** [comment]
For functions I'd say the term used for `and` should be `allPass` and `or` would by `anyPass`. Related https://github.com/jashkenas/underscore/issues/2008

**Comment by aearly** [comment]
Here's a tentative "combine predicates" function

```js
var combinePredicates = _.spread(function (everyOrSome, predicates) {
  return function combinedPredicate(value) {
    return everyOrSome(predicates, function matchesPredicate(predicate) {
      return predicate(value);
    });
  };
});
```

You would use it like this:

```js
var isCollection = combinePredicates(_.some, _.isArray, _.isPlainObject, _.isArguments);
```

You could create the what I proposed `_.and` or `_.or` should be through partial application:

```js
var andPredicate = _.partial(combinePredicates, _.every);
var orPredicate = _.partial(combinePredicates, _.some);
```

I dont know if you'd ever want to use a function other than `_.some` or `_.every` with it, though.

**Comment by aearly** [comment]
`anyPass` and `allPass` are good names -- like the aliases `_.any` and `_.all`.

**Comment by megawac** [comment]
Also aligns with ramda:

https://github.com/ramda/ramda/blob/master/src/anyPass.js
https://github.com/ramda/ramda/blob/master/src/allPass.js
https://github.com/ramda/ramda/blob/master/src/internal/_predicateWrap.js

**Comment by jridgewell** [comment]
Third-order functions? :smile:

@aearly: I like the idea, but how about passing context and args?

```javascript
function combinePredicates(method) {
    return restParam(function(predicates) {
        return restParam(function(args) {
            var thisArg = this;
            return method(predicates, function(predicate) { return predicate.apply(thisArg, args); });
        });
    });
};

_.allPass = combinePredicates(_.every);
_.anyPass = combinePredicates(_.some);
_.nonePass = _.negate(_.anyPass); // jashkenas/underscore#2118
```

- - -

Has anyone else had a use for calling a bunch of functions and collecting the results? It would clean up that `method(predicates, function(predicate) { return predicate.apply(thisArg, args); })`...

```javascript
_.mapFn([fn1, fn2, fn3], thisArg, [arg1, arg2, arg3])
_.everyFn([fn1, fn2, fn3], thisArg, [arg1, arg2, arg3])
_.someFn([fn1, fn2, fn3], thisArg, [arg1, arg2, arg3])
// etc...
```

**Comment by aearly** [comment]
@jridgewell I like it.  I'd be happy to submit a PR with docs and tests if I get the :+1:.

**Comment by jridgewell** [comment]
Ha, I was planning on cross posting a PR to underscore with it. :grin:

**Comment by bstro** [comment]
So, what's the deal here? Does this exist yet?

**Comment by TomLingham** [comment]
I think this is mainly redundant. Doing this work in lodash (While nice) probably isn't worth the effort. Even though there are already things in lodash that I think this is far more useful than.

A way to implement something like this would be using `_.every` and `_.some`

```javascript
_.every([
  Array.isArray,
  _.negate(_.isEmpty),
  isValid,
], f => f(q))
```

**Comment by robinpokorny** [comment]
For those, who found this now, like me, **everything is already implemented** under different names. Hope it helps!

* **‘not’**: `_.negate` (also `_.complement` in lodash/fp)
```js
const isNotString = _.negate(_.isString))

isNotString(3)
// true
isNotString('hi')
// false
```
* **‘and’**: `_.overEvery` (also `_.allPass` in lodash/fp) 
```js
const isEmptyArray = _.overEvery(_.isArray, _.isEmpty)

isEmptyArray([])
// true
isEmptyArray([1, 2])
// false
```
* **‘or’**: `_.overSome` (also `_.anyPass` in lodash/fp)
```js
const isCollection = _.overSome(_.isArray, _.isPlainObject, _.isArguments);

isCollection([1, 2])
// true
isCollection('hi')
// false
```

Please note that in lodash/fp both `_.overEvery` and `_.overSome` have an arity of one and predicates have to be passed as an array.

**Comment by felds** [comment]
Nice find, @robinpokorny. I just find it a little weird that `overSome` and friends have a different signature from `flow` or `combine`, as they seem to do similar work…

**Comment by robinpokorny** [comment]
@felds, true. Looked into that. It seems that nothing prevents that. Plus it is backwards compatible.

**Comment by felds** [comment]
@jdalton should we go for it?

**Comment by jcjolley** [comment]
@felds @jdalton Please do! :)
