### ISSUE TITLE
_.extend not modifying parameter

### ISSUE THREAD

**Issue by cancerberoSgx** [lodash/lodash#1073]
Hello, I'm trying to migrate my code from underscore to lodash and get stuck with the following:

```
var Animal = function(){
this.init();...
}
_(Animal.prototype).extend({init:function(){...}})

```
with underscore this works but not with lodash . error is in this.init() - 'undefined is not a function'. 
Rewriting it like this seems to fix it :
```
Animal.prototype = _.extend(Animal.prototype, {init:function(){...}})
```
Unfortunately rewriting is not in my short-term plans. 

Is this an issue ?- or is this a fact of life? It is a requirement of lodash to fully emulate underscore API ? 

Thanks in advance - any workaround for this is very appreciated and sorry if this is not an issue. :)

P/D: I also test this in 'compat' mode - this is running 'lodash compat'  but without luck.

**Comment by jdalton** [comment]
The compat mode is about fixing iteration issues in older environments. In lodash chaining is deferred until an explicit or implicit `.value()` is called.

**Comment by cancerberoSgx** [comment]
thanks, very appreciated - looking for a workaround now instead having to refactor my (big) code :)

**Comment by jdalton** [comment]
Use the v2.4.1 `require('lodash/dist/lodash.underscore')` or use Underscore and supplement with lodash modules like `require('lodash/object/merge')` or `require('lodash.merge')`.

**Comment by cancerberoSgx** [comment]
thanks! using AMD here but I think I got it. thanks again

**Comment by jdalton** [comment]
> thanks! using AMD here but I think I got it. thanks again

Using AMD? Check out our [AMD branch](https://github.com/lodash/lodash/tree/3.5.0-amd).

The Underscore compat build of v2.4.1 can be [found on cdnjs](https://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.underscore.js) too

**Comment by cancerberoSgx** [comment]
Just replaced my plain old underscore.js with EXACTLY 2.4.1 (the link you provided) and worked like a charm. :) THANKS - no extra work required ! - now let test for/if any performance gain .... Promise  I will share my results - this is a BIG application heavily using backbone&underscore. Thanks again!

**Comment by jdalton** [comment]
> THANKS - no extra work required !

Yep. It's the Underscore compat build which means all of the cool things in lodash are missing. You're missing out on features (merge, deep clone, string methods), performance, & consistency fixes of lodash.

**Comment by cancerberoSgx** [comment]
:( well nevertheless I'm measuring if there is any change in performance with underscore compat build and then I will try to integrate with vanilla lodash. Thanks!
