### ISSUE TITLE
Add possibility to pass equality tester to _.difference

### ISSUE THREAD

**Issue by titarenko** [lodash/lodash#1074]
There is no possibility to compute difference of arrays of objects (no chance to override `===` operator). It would be just great to have a way to pass equality tester (function) to `_.difference` in order to define which objects are equal in context of their content.

**Comment by jdalton** [comment]
Hi @titarenko. See the discussion on [#246](https://github.com/lodash/lodash/issues/246#issuecomment-64502232).

**Comment by jdalton** [comment]
I'm adding `_.uniqWith`, `_.differenceWith`, and friends to lodash v4 which accepts a `comparator` function.
```js
_.uniqWith(objects, _.isEqual);
```
