### ISSUE TITLE
Documentation: display if a function is chainable or not

### ISSUE THREAD

**Issue by Delapouite** [lodash/lodash#1077]
Hi

In the documentation each function currently has # Ⓢ Ⓣ Ⓝ links.

I suggest adding a Ⓒ indicating that the function is chainable. Clicking on this symbol could point to the *_* anchor.

A Ⓕ could be used for function like _.filter supporting shortcut fusion.

**Comment by jdalton** [comment]
Not sure how we'd associate this data with the method. Is there anything in jsdoc that would allow this?

**Comment by jdalton** [comment]
If you figure out a way to represent this in jsdoc we'll look into adding it.
