### ISSUE TITLE
_.head() should be aliased to _.take(), not _.first()

### ISSUE THREAD

**Issue by thatneat** [lodash/lodash#1078]
Expected behavior: `head([1, 2, 3], 2) -> [1, 2]`
Current behavior: `head([1, 2, 3], 2) -> [1, 2, 3]`

`_.head()` was initially aliased to `_.first()` when `_.first()` had more than one argument. Since `first()` now takes only one argument, `_.head()` should probably alias to `_.take()` instead.

In fact, why not alias `_.first()` to `_.take()`?

**Comment by jdalton** [comment]
Naw, see http://zvon.org/other/haskell/Outputprelude/head_f.html.
