### ISSUE TITLE
Question about _.remove index arg behavior

### ISSUE THREAD

**Issue by mcamac** [lodash/lodash#1079]
```javascript
var x = [0, 1, 2, 3, 4, 5];
_.remove(x, function (e, i, a) {
    console.log(e, i, a); return i % 2 === 0;
}); //=> [0, 1, 2, 3, 4, 5]
x//=> 0
```

Logs:
```
0 0 [0, 1, 2, 3, 4, 5]
1 0 [1, 2, 3, 4, 5]
2 0 [2, 3, 4, 5]
3 0 [3, 4, 5]
4 0 [4, 5]
5 0 [5]
```

Looking at the source, one sees that `_.remove` splices the array/decrements index as it removes elements, so that in the above case index will always be 0. Was there a reason this behavior was chosen (I don't see a test case which is immediately relevant, so perhaps it's an edge case)? This behavior can be changed by iterating backwards instead of forwards, I believe. Either way, perhaps could use some documentation - would be happy to submit a PR.

**Comment by jdalton** [comment]
This is by design. The index is the index of the value being provided so you can do of the 3 arguments, `value`, `index`, `array`, that `array[index] === `value`. I'll add a test for it.

**Comment by jridgewell** [comment]
I think he's really asking is why the array is mutated before determining all the elements to be removed. It would take two passes to support, but seems like it be less of a gotcha?

**Comment by mcamac** [comment]
Yeah - in the above example I would expect even elements to be removed but
instead all elements are.

**Comment by d10** [comment]
Yep, this seems weird. Reopening for now.

**Comment by jdalton** [comment]
Ok, I'm cool with patching it.
