### ISSUE TITLE
Documentation: "T" icons do nothing

### ISSUE THREAD

**Issue by venning** [lodash/lodash#1080]
As mentioned in [#1076](https://github.com/lodash/lodash/issues/1076#issuecomment-86063939), the "T" links in the documentation do not work.  Right now there are 207 instances of `<a href="#array" title="Jump back to the TOC.">&#x24C9;</a>` in the markup.  None of those links work because there is no element with an `id` attribute of `array`.  Additionally, it doesn't make sense for them to all be the same link.  I'm assuming something is just going wrong in the documentation generation step.  This is a useful feature generally, but of even more benefit on mobile.

Three things are needed to fix this:
* each TOC item needs an `id` attribute (not including the aliases)
* each "T" link needs to change the `href` attribute from `#array` to the above-mentioned `id` values
* (optionally) some kind of visual affordance to signify the jump

I mocked up [an example of how this could work](http://lodash-docs-work.s3-website-us-east-1.amazonaws.com/docs-toc/).  I added the yellow highlight just to indicate what happened.  I tested in Firefox, Chrome, and Safari.

*(Seriously, tell me to stop if these are coming too fast.  Your roadmap doesn't mention documentation right now, so I don't want to take anyone off track.  I love lodash.  You guys are making my job so much better.  Thank you.)*

**Comment by jdalton** [comment]
I fixed this on the site at the time you mentioned it in the issue. It was an oversight on my part. In the repo the anchor of `#array` works but in the site it should be configured to `#docs`. You'll notice when the site is in two column mode the T is hidden and only shows when the TOC is in a single column.
