### ISSUE TITLE
Extra String utilities?

### ISSUE THREAD

**Issue by jh3y** [lodash/lodash#1084]
Hey.

It may not be necessary but I recently read through the API and noticed there were no String utilities for things like replacing all instances of a string within a string. Is this because the native way of doing this is good enough or these type of functions don't fit in with lodashs design?

For example; `_.replaceAll('abcdefg, 'abc', 'x')` would cover something like

```javascript
var string = 'abcdefg';
string = string.replace(new RegExp('abc', 'g'), 'x');
```

It was just a `question` as I'd imagine this has been considered before but I couldn't find the issue in the history. It'd be nice to chain something like that in some instances.

@jh3y

**Comment by arthurvr** [comment]
I think the native methods cover this quite well.

```js
'abcdefg'.replace('abc', 'x');
//=> "xdefg"
```

**Comment by StreetStrider** [comment]
@arthurvr, he speaks about «**all** instances of a string within a string».
Your code will replace only first entry:
```javascript
'abcdefgabc'.replace('abc', 'x');
// 'xdefgabc'
```
The proper way to do it is to use RegExp:
```
'abcdefgabc'.replace(/abc/g, 'x');
// 'xdefgx'
```

I think the reason why @jh3y asks it is because RegExp literal has no simple way to interact with strings. So, if you wanna to replace all occurences of string, but this string is unknown (i.e. we're using variable), this would be ugly.

**Comment by StreetStrider** [comment]
```javascript
function replaceAll (str, from, to)
{
  from = new RegExp(from, 'g');
  return str.replace(from, to);
}

console.log(replaceAll('abcdefgabc', 'abc', 'x'));
```

**Comment by arthurvr** [comment]
@StreetStrider Yup. Sorry!

**Comment by jh3y** [comment]
Yeah @StreetStrider , that's what I was getting at. It abstracts away from the user having to write this `replaceAll` utility function within their code when doing replacements.

'''javascript
function replaceAll(str, from, to) {
  return str.replace(new RegExp(from, 'g'), to);
}
'''

It was just to see whether this had been brought up before.

@jh3y

**Comment by jdalton** [comment]
If you go that route don't forget to use [_.escapeRegExp](https://lodash.com/docs#escapeRegExp) on the `from` param. I think the normal `String#replace` is fine, but if there's a demand I'll reevaluate.

**Comment by katherine-barn2door** [comment]
Probably can't vote anymore, but :+1: for replaceAll(), especially since it isn't in native.

**Comment by jdalton** [comment]
> Probably can't vote anymore

No worries, voting is totally open : )

**Comment by cezarykluczynski** [comment]
+1

**Comment by jfmengels** [comment]
:+1: looks like a pretty common case to me.

**Comment by bkniffler** [comment]
:+1: This would fit nicely into lodash!

**Comment by gauravarora** [comment]
+1

**Comment by roddik** [comment]
+1

**Comment by abenhamdine** [comment]
+1 very common case, used to use https://github.com/leecrossley/replaceall til now but it adds a dependancy just for one function.

**Comment by jdalton** [comment]
I believe github only counts [upvote reactions](https://help.github.com/articles/about-discussions-in-issues-and-pull-requests/) for sorting so all those :+1: comments should be changed to reactions.

**Comment by eromano** [comment]
:+1:

**Comment by gadeschaos** [comment]
Surealy a much needed and common use case, upvoted ^^

**Comment by mk-pmb** [comment]
I think we should really clarify how replaceAll should work:
 * Should it feed your string to the RegExp constructor so you don't have to backslash-escape slashes (quotes instead), or
 * should it make sure that exactly that string is replaced, saving you from having to deal with RegExps?

About the latest use case example:
```javascript
function replaceAll(str, from, to) {
  return str.replace(new RegExp(from, 'g'), to);
}
```

How would this function be useful? If you can call that function with the string as an argument, you could easily invoke the `.replace` method on str.

I could, however, see a benefit in a function that takes the string as its last argument:

```javascript
_.curryReplace = function (rgxWhat, rplWith, text) {
  return String(text).replace(rgxWhat, rplWith);
};

var cl = console.log,
  nOo0ez = _.curryReplace.bind(null, /([oO0°])/g),
  becomeOne = nOo0ez.bind(null, 1),
  doubleThem = nOo0ez.bind(null, '$1$1'),
  noVowels = _.curryReplace.bind(null, /[aeiou]/ig, ''),
  cold = ['Oregon', 'at 0° C'];

cl(cold.map(becomeOne));          //= `[ '1reg1n', 'at 11 C' ]`
cl(cold.map(doubleThem));         //= `[ 'OOregoon', 'at 00°° C' ]`
cl(cold.map(noVowels));           //= `[ 'rgn', 't 0° C' ]`
cl(nOo0ez('()', 'hello world'));  //= `hell() w()rld`
cl(noVowels('hello world'));      //= `hll wrld`
```

**Comment by nmaro** [comment]
+1

**Comment by koresar** [comment]
I need this function drastically like one a month. I was looking for a way to safely replace substring like "[bla]" with "value". 
`"I am [name]."` -> `"I am John-David Dalton."`

For all the people who was looking the same here is how you do it:
```js
str.replace(new RegExp(_.escapeRegExp("[name]"), "g"), "John-David Dalton");
```

Hey @jdalton, since `String.prototype.replaceAll` is a [Stage 1 proposal](https://github.com/tc39/proposals) now do you think we can have it in lodash too?

**Comment by buzzware** [comment]
I actually can't believe 
1) this isn't the default behaviour of replace 
2) lodash has no replaceAll as a result

**Comment by mk-pmb** [comment]
@buzzware you could make your comment slightly more useful if you edit it to clarify which behavior (regexp? literal? case-sensitive?) you require.

**Comment by koresar** [comment]
The [replaceAll](https://github.com/tc39/proposal-string-replaceall) is Stage 2 as of July 2019.

**Comment by buzzware** [comment]
I agree with the replaceAll proposal on strings. I think the default single instance replacement is the special case - I almost always want to replace all instances.
With regexs, I would expect replaceAll to implicitly add the global attribute.

**Comment by sid0-0** [comment]
Been a while since this had any traction. This is an important util.
Can someone open this issue as a feature request again? I'm willing to work on it as well.

**Comment by mk-pmb** [comment]
@sid0-0
> This is an important util.

In fact the importance has meanwhile been recognised by browser vendors. Try `'hello'.replaceAll('l', 'y')` in any modern browser, it should return `'heyyo'`.
