### ISSUE TITLE
_intersection behavior

### ISSUE THREAD

**Issue by nikmartin** [lodash/lodash#1085]
I just upgraded to 3.6 and this test:

    _.intersection(val, [3325, 3330]);

will return [3325,3330] 

if val is undefined. in 2.4.0 it returns []

Is this change by design? It is a major breaking change I cannot find documented anywhere.

**Comment by jdalton** [comment]
Naw, it's a super gross bug.

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash/commit/c6ff845ecb3891089afe8b8696f7586a19452f07.
