### ISSUE TITLE
Method helper

### ISSUE THREAD

**Issue by gampleman** [lodash/lodash#1086]
A handly lodash extension we made is this one:

```javascript
  _.method = function() {
      var args, meth;
      meth = arguments[0], args = 2 <= arguments.length ? [].slice.call(arguments, 1) : [];
      return function(object) {
        return object[meth].apply(object, args);
      };
    }
```

This allows to create a function from a method:

```javascript
var toStr = _.method('toString');
toStr([3]);  // => '3'
toStr(3);    // => '3'
toStr({a: 3}) // => '[object Object]'

var matchesTag = _.method('match', /^(\w+):(\w+)=(.+)$/)
matchesTag('ns:key=value'); // => ['ns:key=value', 'ns', 'key', 'value']
```

Also very handy for iteration:

```javascript
var waysToSumToEleven = _.map(_.zip(_.range(1, 10), _.range(10, 1, -1)), _.method('join', ' + '))
// => ["1 + 10", "2 + 9", "3 + 8", "4 + 7", "5 + 6", "6 + 5", "7 + 4", "8 + 3", "9 + 2"]
```

I think it would make a nice addition.

**Comment by jdalton** [comment]
Something like:
```js
var matchesTag = _.bind(_.call, ''.match, _, /^(\w+):(\w+)=(.+)$/);
matchesTag('ns:key=value'); // => ['ns:key=value', 'ns', 'key', 'value']
```
The name `method` is pretty generic. We have a `bindKey` which is close but not right. This is like a `partial`+`invoke`.

I think I've seen this request before so I'll note a :+1: for it. Let's keep an eye on it and see if demand picks up.

**Comment by jdalton** [comment]
Something like:
```js
var matchesTag = _.bind(_.call, ''.match, _, /^(\w+):(\w+)=(.+)$/);
matchesTag('ns:key=value'); // => ['ns:key=value', 'ns', 'key', 'value']
```
The name `method` is pretty generic. We have a `bindKey` which is close but not right. This is like a `partial`+`invoke`.

I think I've seen this request before so I'll note a :+1: for it. Let's keep an eye on it and see if demand picks up.

**Comment by jridgewell** [comment]
I had a need for something like this [yesterday](https://github.com/jashkenas/underscore/pull/2124#issuecomment-86682834)...

**Comment by jdalton** [comment]
Like an `_.invokeOf` or something.

**Comment by jridgewell** [comment]
Exactly, but `_.invokeOf` reminds me of `_.propertyOf` which takes an object. I actually called `call()` from the comment `method()` originally, but didn't want `method('method')` in my example. If we keep these as calling cousins of `_.property`, `_.method` and `_.methodOf` seem perfect to me.

**Comment by gampleman** [comment]
I'd like to add a bit more of an explanation to this. 

In functional languages functions are typically written as free standing, think `map fn xs`, whereas in object-oriented they are typically written as methods on a reciever, like this `xs.map(fn)` (NB: by free-standing I don't mean namespacing, but that the receiver is actual input to the function).

JavaScript is somewhat between those two worlds. So the proposed function exists to convert from the object-oriented to the functional style. 

As an aside, the 'inverse' in some sense would the look like this:

~~~javascript
var inverse = function(object, name, fn) {
  object[name] = function() {
    return fn.apply(null, [this].concat(arguments));
  };
}

inverse(Array.prototype, 'partition', _.partition);
[1,2,3,4].partition(function(n) { return n % 2 === 0; }) // [[1,3], [2,4]]
~~~

I think however that this 'inverse' function wouldn't be terribly useful.

**Comment by CrossEye** [comment]
You might want to have a look at https://github.com/paldepind/functionize, which is trying to combine something like this with the ideas of `rearg` into a generic way to turn an `obj.method(args..)` API into a `func(arg.., obj)`.  The code is brand-new, and I don't think the API is completely thought through yet, but there's some interesting ideas there.

**Comment by paldepind** [comment]
Thanks for mentioning functionize :) It is indeed brand new, and everything is in flux/up for debate. It is partially inspired by the transformation going on inside lodash-fn.

Regarding this proposal: There is a few ways such a function can be implemented if one wants to embrace currying. Take a look at [Ramdas version](http://ramdajs.com/docs/#invoker) and maybe also the [discussion leading to its current implementation](https://github.com/ramda/ramda/pull/510).

A version suitable for lodash could optionally support currying by taking an optional arity argument.

```javascript
_.invoker('slice') // No arity – non-curried invoker
_.invoker(2, 'slice') // Arity supplied – curried invoker
```

**Comment by jdalton** [comment]
@paldepind Currying is fine but we'll keep it simple for the common case. We have [lodash-fp](https://www.npmjs.com/package/lodash-fp) to handle auto-currying.

@jridgewell makes a good point about "calling cousins" (btw I love that phrase) so while `method` is a blah name on it's own when paired with `_.property` and `_.propertyOf` it makes more sense. This also highlights an issue with deep property extensions, being discussed in other PRs. With these additions the deep variants would also be needed and that inflates the API a lot. I think for the deep variants the normal methods should just be modified to accept deep properties to keep the variants to a minimum.

**Comment by paldepind** [comment]
> Currying is fine but we'll keep it simple for the common case. We have lodash-fp to handle auto-currying.

What I proposed would not make `method` any less simple for the common case.

**Comment by jdalton** [comment]
> What I proposed would not make method any less simple for the common case.

Hybrid behavior complicates it, I'd rather keep it simple.

**Comment by CrossEye** [comment]
There is an issue, though, that something like `invoker` cannot be curried as simply as functions that properly report their own arity.  You really have to curry it to a particular length.  So this is not a matter of auto-currying.  I don't know if lodash-fp also does this sort of currying to a specified arity.

**Comment by jdalton** [comment]
> You really have to curry it to a particular length. So this is not a matter of auto-currying. I don't know if lodash-fp also does this sort of currying to a specified arity.

lodash-fp combines [_.ary](lodash.com/docs#ary) + [_.rearg](lodash.com/docs#rearg) + [_.curry](lodash.com/docs#curry). If any other work is needed then we'll tackle it on the lodash-fp side.

Let's keep the thread on track. The proposed methods won't be curried in lodash.
