### ISSUE TITLE
enhance _.compact(obj) on objects to remove keys with falsy values

### ISSUE THREAD

**Issue by guymguym** [lodash/lodash#1093]
just like _.compact(array) has the effect as _.filter(array, _.identity)
then _.compact(obj) can be a a readable shortcut for _.pick(object, _.identity).

I find myself using it a lot when constructing an object from values which might be empty and I wish to avoid sending the `key: undefined` over a JSON protocol for no reason.

so this:
```
var reply = {}
if (time) reply.time = time;
if (place) reply.place = place;
...
return reply;
```

will be written as:

```
return _.compact({
  time: time,
  place: place,
  ...
})
```

**Comment by jdalton** [comment]
Thanks, but I'd like to keep `_.compact` as an array only method for simplicity.

**Comment by guymguym** [comment]
Maybe for the sake of simplicity the name should be `_.compactValues`?
(just like `_.mapValues` is the object version of `_.map(array,..)`)

**Comment by jdalton** [comment]
Rock! I'll keep an eye on demand.

**Comment by guymguym** [comment]
:+1:

**Comment by Jokero** [comment]
+1

**Comment by roko-p** [comment]
+1

**Comment by Katochimoto** [comment]
:+1:

**Comment by jdalton** [comment]
With v4 you can do `_.pickBy(object)` as the default iteratee is `_.identity`.

**Comment by shahzaibalikhan** [comment]
+1

**Comment by madpeteruvic** [comment]
+1

**Comment by jdalton** [comment]
I think I'm OK deferring to `_.pickBy(object)` for this.

**Comment by guymguym** [comment]
@jdalton how about making `_.compact` an alias? 
I think it's just unexpected that calling `_.pickBy(obj)` will do that, and while it works, it comes with the price of readability, and I am willing to put money that it will not be adopted this way.

**Comment by guymguym** [comment]
not sure if a lot of money :) but definitely some!

**Comment by jdalton** [comment]
I'm cutting down on aliases in v4 so that won't likely happen. Users are free to create their own alias mixins however they see fit.

**Comment by megawac** [comment]
Yeah I'd be :-1: on a `compact` alias. If users want to make `_.pickBy(obj)` more explict they can use `_.pickBy(obj, Boolean)` (filter truthy values) or `_.pickBy(obj, _.negate(_.isUndefined))`

**Comment by guymguym** [comment]
I just think the main potential of lodash is to be that library that always has the utility function you look for. 
not a library that you need to work for or learn it's quirky language.
I can see that we don't think alike on that.

**Comment by jdalton** [comment]
> I just think the main potential of lodash is to be that library that always has the utility function you look for.

Ya it's a balance for sure. I'm dropping `_.pluck(objects, prop)` for `_.map(objects, prop)` which may bite back but worse case we correct course in a future release.

**Comment by crapthings** [comment]
_.omitBy(source, _.isEmpty)

http://stackoverflow.com/questions/14058193/remove-empty-properties-falsy-values-from-object-with-underscore-js#comment63840688_32386362

**Comment by akofman** [comment]
Yep but `omitBy` is not recursive.

**Comment by AaronHarris** [comment]
I understand omit is far slower than pick. In this case, would we still expect _.pickBy(obj, _.identity) to be considerably faster than _.omitBy(obj, _.isEmpty)?

**Comment by fyyyyy** [comment]
Please note:
```
_.isEmpty(5)
// true
```

**Comment by kewitz** [comment]
To be extra explicit.
```js
const compactObject = pickBy(negate(isUndefined))
```
