### ISSUE TITLE
An helper proposal, useful for async calls

### ISSUE THREAD

**Issue by apendua** [lodash/lodash#1094]
When dealing with a lot of async callbacks or promises we always run into the following pattern:
```javascript
doSomeAsyncTask(function (err, res) {
  if (err) {
    // do something with error
  } else {
    // do something with result
  }
});
```
It's even more common when I want to wrap an async task within a promise:
```javascript
new Promise(function (resolve, reject) {
  doSomeAsyncTask(function (err, res) {
    if (err) {
      reject(err);
    }  else {
     resolve(res);
    }
  });
});
```
Because I do it really often in my code I came up with a very simple helper, which allows me to do this
```javascript
new Promise(function (resolve, reject) {
  doSomeAsyncTask(either(reject).or(resolve));
});
```
which I have found a very expressive and useful pattern. I am wondering if it's easily achievable with `lodash`. If not, then the question is whether it would be reasonable to add a similar feature to the library.

**Comment by oriSomething** [comment]
async tasks with lazy evaluation! not kidding, that's can be very call

**Comment by jdalton** [comment]
This looks specialized to the `err, res` params which maps well to [async](https://github.com/caolan/async). I'll leave async specialization to other libs for the time being.

**Comment by qsona** [comment]
Hi, I'd like to introduce [Neo-Async](https://github.com/suguru03/neo-async/), which is an enhancement of async. The author of neo-async @suguru03 is a hardcore fan of @jdalton and developed it inspired by lodash. lol
