### ISSUE TITLE
Description of range() should be improved

### ISSUE THREAD

**Issue by PhiLhoSoft** [lodash/lodash#1095]
What I read for 3.6.0 for _.range: "_Creates an array of numbers (positive and/or negative) progressing from start up to, but not including, end. If end is not specified it is set to start with start then set to 0. If start is less than end a zero-length range is created unless a negative step is specified._"
But:
- end is not marked as optional. Perhaps the signature should be: `_.range([start=0, [end=start, [step=1]]])`
- "_If start is less than end_" should be "if end is than or equal to start".

**Comment by jdalton** [comment]
I think `end=start` is a bit confusing. The `end` even if its the first param is still required which is why it's not marked as optional.There isn't a great way to tackle this but I'll mix in some of your suggestions.

**Comment by PhiLhoSoft** [comment]
Yes, there is no simple & elegant way to tackle this in one shot, I fear. Note that lodash gracefully accepts no parameters at all, that's why I marked everything as optional, but of course it isn't a realistic use case... :smile:
