### ISSUE TITLE
Apply 'xor' to object

### ISSUE THREAD

**Issue by richzw** [lodash/lodash#1096]
Given two arrays as following

```javascript
arr1 = [{id: 1, val: 31, key: 51}, {id: 8, val: 32, key: 52},
           {id: 3, val: 33, key: 53}, {id: 6, val: 36, key: 56}];
arr2 = [{id: 2, val: 35}, {id: 8, val: 32}, {id: 6, val: 36}];
```

Now I want to remove those same objects with same `id` in those two arrays, and the results are

```javascript
arr1 = [{id: 1, val: 31, key: 51},  {id: 3, val: 33, key: 53}];
arr2 = [{id: 2, val: 35}];
```

Based on the current API, here are my implementation.

```javascript
arr1Ids = _.pluck(arr1, 'id');
arr2Ids = _.pluck(arr2, 'id');
sameIds = _.intersection(arr1Ids, arr2Ids);
_.remove(arr1, function(a) { return _.includes(sameIds, a.id);} )
_.remove(arr2, function(a) { return _.includes(sameIds, a.id);});
```

Is that possible to apply something api like `xor` or `xorBy` to Object?

**Comment by jdalton** [comment]
Our [roadmap](https://github.com/lodash/lodash/wiki/Roadmap) has eventually splitting `uniq` out into `uniqBy`. I could see something like `xorBy` coming at that time.
