### ISSUE TITLE
_.isDefined()

### ISSUE THREAD

**Issue by hanifbbz** [lodash/lodash#1097]
In our code base we had a lot of instances of `typeof variable === 'undefined'` which we could replace with `if (_.isUndefined(variable))`.

But we had even more instances of `typeof variable !== 'undefined'` which ended up looking like `if (!_.isUndefined(variable))` and it reads like "if variable is not undefined" which is kinda weird.

I want to propose a `_.isDefined()` function which is the opposite of `_.isUndefined()` to make the code more readable.

Sidenot: comparing string inequality is arguably faster than string equality since the processor doesn't have to swipe the whole string to compute the result.

**Comment by jdalton** [comment]
Hi @hanifbbz! This has been brought up a few times and I'm not interested in adding such a method to lodash. You can always [create a mixin](https://lodash.com/docs#mixin).

**Comment by hanifbbz** [comment]
@jdalton well, if it's decided, there's nothing I can say to change your mind, but if the code readability and performance is not important then what is? I appreciate the focus, but if this is a popular demand, maybe someone in the team can reconsider?

**Comment by jacobp100** [comment]
This won't work. If you shove an undefined variable into a function, it will throw a ReferenceError. It only works with typeof, because typeof is a special operator.

**Comment by hanifbbz** [comment]
@jacobp100 not sure if I understand what you mean.
The code I had in mind is like this:

```
_.isDefined = function (a) {
  return typeof a !== 'undefined';
}
```

**Comment by jdalton** [comment]
Jacob is referring to undeclared variables.
```js
_.isDefined(someUndeclaredVar); // ReferenceError
```

**Comment by jacobp100** [comment]
@hanifbbz I’m not sure why you’re including the `typeof`. You can directly check for undefined via `a === undefined`.

**Comment by jdalton** [comment]
Ok this thread has reached its end.

**Comment by sneakyfildy** [comment]
+100000!
