### ISSUE TITLE
Support filtering with `assign()`

### ISSUE THREAD

**Issue by jwarkentin** [lodash/lodash#1098]
I've just run into an interesting use case where I want to use `assign(objA, objB)` but I want to be able to provide a whitelist of properties that are allowed to be assigned to `objA` from `objB` (or any other objects). Obviously I can manually filter each object before passing it to `assign`, but it'd be awesome if I could just pass an option or something with a list of allowed properties that will be assigned to `objA`, ignoring any properties that aren't in the list. Maybe `assign` could support a `filter` option or somehow take advantage of the `customizer` function to simply ignore certain properties.

**Comment by jdalton** [comment]
I don't think the `customizer` can be tweaked to allow this. At the point it reaches the customizer it's being assigned. The `customizer` just allows customizing what's assigned. I think a mixin that combos `_.omit` and `_.assign` would do.
