### ISSUE TITLE
Maybe a bug with _.inRange()

### ISSUE THREAD

**Issue by albertvazquezm** [lodash/lodash#1099]
Hi,

`_.inRange(n, [start=0], end)` seems to be not working with negative numbers.

**Comment by jdalton** [comment]
I can't repro:
```js
_.range(-6, -2);
// => [-6, -5, -4, -3]
```

**Comment by d10** [comment]
@jdalton This issue is for `_.inRange`, not `_.range` ;)

@albertvazquezm Could we have more details? I.e. your usage?

**Comment by jdalton** [comment]
> This issue is for `_.inRange`, not `_.range` ;)

Doh.

**Comment by jdalton** [comment]
Hmmm even then I can't repro:
```js
_.inRange(-3, -6, -2); // => true
```

**Comment by jridgewell** [comment]
It's more than likely he has a negative step, which `_.inRange` doesn't handle.

```javascript
_.inRange(-3, -2, -6); // => false
```

**Comment by jdalton** [comment]
@jridgewell So the issue is if `start` is greater than `end` flip them?

**Comment by jridgewell** [comment]
That's what I was thinking. `(-2..-6)` feels like it includes `-3` to me.

However, other languages don't seem to agree...

```ruby
#ruby
(-6..-2).include? -3 # => true
(-2..-6).include? -3 # => false
```

```python
#python
-3 in range(-6, -2) # => true
-3 in range(-2, -6) # => false
```

**Comment by jdalton** [comment]
Since you can get there with a negative step `_.range(-2, -6, -1)` I'm cool supporting the param swap in `_.inRange`.
