### ISSUE TITLE
Add _.ordinalize(integer) function

### ISSUE THREAD

**Issue by blainekasten** [lodash/lodash#1100]
Would you guys be interested in an ordinalize funtion for numbers to coerce them to the readable string?

I've found a really simple implementation we could copy
http://ecommerce.shopify.com/c/ecommerce-design/t/ordinal-number-in-javascript-1st-2nd-3rd-4th-29259

this would allow the following:

    _.ordinalize(3) // => "3rd"
    _.ordinalize(726) // => "726th"
    //etc

**Comment by jdalton** [comment]
Thanks @blainekasten. That is a really simple implementation. I'd probably call it `_.toOrdinal`. For now I'll keep an eye on this request and see if it gets traction.

**Comment by seiyria** [comment]
Did this ever get implemented? I didn't see it under `number`.

**Comment by jdalton** [comment]
> Did this ever get implemented? I didn't see it under `number`.

Nope, still waiting on demand to rise a bit.

**Comment by StreetStrider** [comment]
This thing is natural language-related :confused:

**Comment by seiyria** [comment]
It's not actually that bad. I'm currently using this solution: http://stackoverflow.com/a/31615643/926845

It just seems like something that would work well with Lodash.

**Comment by megawac** [comment]
I'd be -1 on this as it won't support i18n

**Comment by jdalton** [comment]
Ya it gets complicated pretty fast.

**Comment by falsyvalues** [comment]
:-1:
