### ISSUE TITLE
_.matches with function properties

### ISSUE THREAD

**Issue by bathos** [lodash/lodash#1101]
_.matches and family members like _.where seem to ignore properties whose values are functions. This is consistent, I think, with the documentation ("This method supports comparing arrays, booleans, Date objects, numbers, Object objects, regexes, and strings.") suggesting it may be intended behavior. Then again, even the "name" property gets ignored, so it doesn't seem to compare functions as regular objects either.

I don't know how much importance is given to consistency between Lodash methods and their analogs in Underscore -- so this may be irrelevant -- but I was surprised to find _.where gave such different results.

If it is a deliberate design decision, what's the reasoning behind it?

**Comment by jdalton** [comment]
Functions are compared by reference, `===`, because there isn't a great way to test equivalence (and ya I know about coercing them to strings). Even if we iterated them the `name` property wouldn't be checked because it's non-enumerable.

**Comment by bathos** [comment]
@jdalton Comparison by reference is actually the behavior I did expect --  but it's not what I encountered. Properties with function values are being compared only by type; any function is a match for any other function:

    var arr = [
        { name: 'bob', fn: JSON.stringify },
        { name: 'lou', fn: function one() {} },
        { name: 'zoe', fn: function two() {} }
     ];

    _.where(arr, { name: 'bob' }); // correctly returns array with just bob

    _.where(arr, { name: 'bob', fn: function wat() {} }); // ...still returns bob.

    _.where(arr, { name: 'bob', fn: 'any-non-function-value' }); // empty array

    _.where(arr, { fn: function() {} }); // returns array with all three

    _.where(arr, { fn: JSON.stringify }); // returns array with all three

That's with V 3.6.0.

**Comment by jdalton** [comment]
Hmm I can't repro:
```js
_.where(arr, { name: 'bob', fn: function wat() {} }); // returns an empty array in v3.6.0
```

**Comment by jdalton** [comment]
Opps I was testing v3.5.0 :P. This is a bug.
