### ISSUE TITLE
letting .each/.forEach run eagerly

### ISSUE THREAD

**Issue by staeke** [lodash/lodash#1102]
Just upgraded to 3.6 from 2.4 and realized everything is lazy now. That's great in many cases, but a very common use case seems to be ending a chain with ```each```/```forEach```. It would be nice if these could be run eagerly. So that

```
_(items).filter({ x: 'y' }).each(doSomething)
```

...would work. Rather than the clumsy and slightly confusing

```
_(items).filter({ x: 'y' }).each(doSomething).value();
```

What do you say?

**Comment by jdalton** [comment]
Dig through some of the related issues. Because `_.each` returns `collection` it is chainable and so requires the `.value()` to end the chain.

**Comment by staeke** [comment]
My question was not **why** ```value()``` is required. It was a comment that I think it shold be done differently, to allow for easier use. Then getting the reply "This is how it works" doesn't make much sense. If you don't agree, fine, but then it would be interesting to hear your comment as to why.

My proposal is thus that you break theg general chainable = lazy evaluation premise that was introduced with version 3, and instead make ```each``` run eagerly. 

In pseudo code, something like:

```
collection.protoype.each = function(cb) {
  var fixed = this.value();
  fixed.forEach(cb);
  return _(fixed);
}
```

**Comment by staeke** [comment]
So I dug some more in issues and I've seen that a lot of other people have the same opinion. Basically, imo, you render the pattern above pretty useless if you require ```.value()``` or ```run()``` as poeple are thinking about ```each``` as in non-lazy terminology and write long each/for each bodies. In fact, it's a very non-functional paradigm. Thus being wrapped in a lazy monad is just contrary to intuition. But I realize that you seem to have a strong opinion on this @jdalton . Care to ellaborate?

**Comment by jdalton** [comment]
The chaining behavior has existed for a while now. Lazy chaining as simply put a spotlight on it. By the rules of chaining `forEach` should not terminate the chain.

**Comment by staeke** [comment]
I appreciate that they've been there for a while. My bad to not have looked into it until now. To summarize this discussion, this is what I hear:

Me: This rule/principle seems bad in this case. Could you consider changing the rules? If not, why?
You: No, because by our rules they work that way.

That very much sounds like a circular argument to me. Sorry, I don't mean to sound like an asshole or anything, and I really appreciate your work. It's just that I think it would make an improvement in that a lot of people would avoid potential bugs - especially from upgrades.

**Comment by jdalton** [comment]
> That very much sounds like a circular argument to me.

Yap. I won't revisit the chaining rules until v4.

> It's just that I think it would make an improvement in that a lot of people would avoid potential bugs - especially from upgrades.

The longer v3 is out, the more people switch the less upgrade noise we'll hear.
