### ISSUE TITLE
.reduce on a chain returns the output, not a wrapped object

### ISSUE THREAD

**Issue by joeybaker** [lodash/lodash#1104]
I was surprised to learn 
```js
_([1,2,3]).reduce(function(out, i){ return out += i }, 0) // returns 6
```

I was expecting a wrapped lodash object. Is this a bug? If not, maybe the bug is that that docs should state that `.reduce` commits a chain?

**Comment by jdalton** [comment]
Not a bug this is by design because it reduces a value. See [_](https://lodash.com/docs#_).
> Methods that return a boolean or single value will automatically end the chain returning the unwrapped value. Explicit chaining may be enabled using `_.chain`.

You can force chaining using `_.chain` or `_(arr).chain()`.

**Comment by jdalton** [comment]
Related to #1077.
