### ISSUE TITLE
Union in chained calls

### ISSUE THREAD

**Issue by adamboduch** [lodash/lodash#1105]
It would be useful if I could call `union()` on an array of arrays. The scenario is, I have a wrapper, and the chained calls generate an array of arrays:

```javascript
var coll = [
    { first: true, second: true },
    { first: true, second: true },
    { first: true, second: true }
];

_(coll).map(_keys).value();
// →
// [
//   [ 'first', 'second' ],
//   [ 'first', 'second' ],
//   [ 'first', 'second' ]
// ]
```

Since I don't want duplicates, I can do this:

```javascript
_(coll).map(_keys).flatten().uniq().value();
// → [ 'first', 'second' ]
```

It would be cool if I could just shorten it to:

```javascript
_(coll).map(_keys).union().value();
```

Also seems a little more obvious what the code is doing. Anyway, just an idea, I'm sure there are other use cases for using union in chained calls like this, I wasn't sure how feasible something like this is (`union()` accepting a collection of arrays in addition to array arguments).

Thanks!

**Comment by jdalton** [comment]
Hi Adam!

I think in this case you can use `thru`:
```js
_(coll).map(_keys).thru(_.spread(_.union)).value();
```

**Comment by adamboduch** [comment]
Thanks, forgot about spread().

On Thu, Apr 2, 2015 at 11:52 AM, John-David Dalton <notifications@github.com
