### ISSUE TITLE
Add automatic submission of new version to CDN

### ISSUE THREAD

**Issue by NameFILIP** [lodash/lodash#1107]
I can't find the new version of library on https://cdnjs.com/. Although, it's possible to manually upload it there, I think it would be useful to add some procedure to automatically add it there as part of the release process.

**Comment by jdalton** [comment]
That's an issue for them to tackle. They should have a process to monitor our tags, though it seems to not have kicked in for 3.6.0.

**Comment by megawac** [comment]
Any reason a map file isn't created with the tags? https://github.com/lodash/lodash/tree/3.6.0

**Comment by megawac** [comment]
Also one of the main issues for this packages (from jsdelivrs perspective) is that not all the tags are relevant (e.g. `-npm` `-npm-packages`, `amd`, etc) and this one isn't pushed to `npm` https://github.com/lodash/lodash/tree/3.6.0

**Comment by jdalton** [comment]
map files are opt-in so devs don't get the missing map file in their logs. Also becuase generating a map file means only using 1 minifier and we use a hybrid approach by default (choosing the best of uglify, closure compiler simple, closure compiler advanced, hybrid (uglify + cc simple), hybrid (uglify + cc advanced).

**Comment by jdalton** [comment]
> Also one of the main issues for this packages (from jsdelivrs perspective) is that not all the tags are relevant (e.g. -npm -npm-packages, amd, etc) and this one isn't pushed to npm

They've solved it by simply pulling from master branches or someone has as they've created cdn entries for `lodash/lodash

**Comment by megawac** [comment]
Neither jsDelivr nor cdnjs have solved this for jsdelivr since 3.0 as it doesn't seem appropriate to roll a solution for one module. Upon review, it'd be possible to do with `bower`.

@jdalton can you add the `compat` and `modern` builds (+ others?) to bower? It'd also be nice to also have all the modules published there in categorized folders

**Comment by jdalton** [comment]
> Neither jsDelivr nor cdnjs have solved this for jsdelivr since 3.0 as it doesn't seem appropriate to roll a solution for one module. Upon review, it'd be possible to do with bower.

It does when its lodash. We're big enough to get the red carpet treatment.

> can you add the compat and modern builds (+ others?) to bower? It'd also be nice to also have all the modules published there in categorized folders

I'm not interested in changing our structure to solve a cdn-made problem. It's not hard for them to create something that pulls from template paths
`'https://github.com/lodash/lodash/blob/<%- version %>/lodash.js'` to lodash.js
`'https://github.com/lodash/lodash/blob/<%- version %>/lodash.min.js'` to lodash.min.js
`'https://github.com/lodash/lodash-compat/blob/<%- version %>/lodash.js'` to lodash.compat.js
`'https://github.com/lodash/lodash-compat/blob/<%- version %>/lodash.min.js'` to lodash.compat.min.js

**Comment by megawac** [comment]
> It does when its lodash. We're big enough to get the red carpet treatment.

AFAIK both cdnjs's autoupdate and jsDelivr's libgrabber are maintained by
volunteers. They both support releases on bower|npm|github but expect a)
consistent file structure between tags b) all files to be included on
tagged releases. It seems reasonable to expect repos to conform to these
practices in at least one of npm|bower|github.

Is there a good reason you don't include the alternate build files (and
source map files) in the bower releases as that seems useful for more than
just CDNs

On Sat, Apr 4, 2015 at 11:38 AM, John-David Dalton <notifications@github.com

**Comment by jdalton** [comment]
> AFAIK both cdnjs's autoupdate and jsDelivr's libgrabber are maintained by
volunteers.

And? lodash is primarily maintained by me. I'm able to do it because I automate things.

>  It seems reasonable to expect repos to conform to these
practices in at least one of npm|bower|github.

Nope. They'll bend or another CDN that does will get the promotion/attention.

> Is there a good reason you don't include the alternate build files (and
source map files) in the bower releases as that seems useful for more than
just CDNs

I've covered the `.map` issue previously. As for other builds we have them separated by repo.

**Comment by PeterDaveHello** [comment]
Seems somebody use force push to rewrite the history of this repo, so make the local repo can't sync with this repo, fixed now.

**Comment by jdalton** [comment]
> Seems somebody use force push to rewrite the history of this repo, so make the local repo can't sync with this repo, fixed now.

That'll happen a lot.

**Comment by PeterDaveHello** [comment]
> That'll happen a lot.
I use `fetch` instead of `pull` to prevent this problem, no offence, but it's not a good idea to do it in a public repo.

**Comment by jdalton** [comment]
> I use fetch instead of pull to prevent this problem, no offence, but it's not a good idea to do it in a public repo, especially this is a famous repo.

I'll manage the repo as I see fit, thanks.
