### ISSUE TITLE
In addition to explicitly-chainable wrappers, offer explicitly-unchainable ones.

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [lodash/lodash#1112]
I use CoffeeScript (yes, still, in 2015. :P) A *huge* reason I loved CoffeeScript was how beautiful CoffeeScript's implicit indentation and short function syntax is when combined with many of the Lodash tools:

    _(@content).remove (entry)->
       return false if accessor? and entry.accessor != accessor
       _(entry.masks).remove (m)-> m.conflictsWith mask
       return true if entry.masks.length == 0

Unfortunately, with Lodash 3.0.0's lazy chains, a huge quantity of my code now breaks. The explicit fix would be to replace *all* of my CoffeeScript using Lodash with something more like the following:

    _(@content).remove((entry)->
       return false if accessor? and entry.accessor != accessor
       _(entry.masks).remove((m)-> m.conflictsWith mask).commit()
       return true if entry.masks.length == 0
    ).commit()

I find this a hell of a lot uglier (and this is a simple example, with only two nested Lodash iterators; I've got situations where several happen *on one line*!). I understand the rationale for the lazy-by-default / chain-by-default; but in addition to the existing `_.chain()` (which explicitly *enables* method-chaining), I'd like to see something like `_.just()` that explicitly disables chaining on the wrapped object (and a correspondingly `_.proto.just()` to explicitly disable chaining on a pre-existing wrapped object).

With that, I could do something like the following:

    __ = _.just

    func = ->
       __(object).iterator (ele)-> maipulate ele

… and boom, all the beauty of CoffeeScript's implicit functions and implicit returns is restored to me.

**Comment by jdalton** [comment]
Instead of rewriting large chunks of your code you can leverage the modules of v3 in your v2 code. lodash v3 supports cherry-picking, `require('lodash/array/chunk')` or [individual npm packages](https://www.npmjs.com/browse/keyword/lodash-modularized).

**Comment by ELLIOTTCABLE** [comment]
Hm. Instead of the proposed functionality, you think it's better that users using CoffeeScript stick to Lodash 2.x, and then cherry-pick the specific functions from 3.0 and later that they need updated? /=

**Comment by jdalton** [comment]
> Instead of the proposed functionality, you think it's better that users using CoffeeScript stick to Lodash 2.x.

I suggested it for your situation to avoid a huge quantity of your code breaking. It looks like from your examples your use case is one off calls which aren't really chained. Instead you could just use the traditional syntax:
```cs
_(@content, entry).remove ->
```

**Comment by d10** [comment]
@jdalton Should that be `_.remove @content, (entry) ->`?
