### ISSUE TITLE
Note in iterator methods whether or not the iterator can mutate the collection

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [lodash/lodash#1113]
I'm running into this issue today:

    _(collection).find (item, index)->
       collection.splice(index, 0) if item.predicate()

After updating Lodash through quite a few versions (my own fault for letting it lag behind, but hey.), the code of that form ceased working. I've discovered that that `find()` is now returning an undefined result, presumably because it tries to access the element by index *after* my iterator function mutates the collection.

Looking through the documentation, I can find no mention of mutating iterators. If this approach is more performant, I'm fine with it; but it should probably be mentioned in the documentation which Lodash function-arguments are expected to be pure, and which can mutate the environment Lodash operates in.

**Comment by jdalton** [comment]
The old behavior you're describing would definitely have been a bug. Iteratees can mutate just as they can in JavaScript built-ins like `Array#each`, `Array#map`, and others. We document which methods augment values provided but beyond that devs can augment lots of things in JS land. I don't think a doc note is explicitly needed for that.

**Comment by ELLIOTTCABLE** [comment]
Hm, so this is a bug then. I'll try and reproduce for a test-case.
