### ISSUE TITLE
_.removeFirst / _.removeLast in addition to _.remove

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [lodash/lodash#1114]
Title's pretty self-explanatory. Trying to replace the broken code from #1113, and surprised to find that this functionality isn't explicitly exposed by Lodash.

As `_.remove(array, predicate)`, except it ceases iteration on the first truthy-result, removes that result, and returns it (leaving remaining elements of the array untested / untouched.)

**Comment by jdalton** [comment]
Thanks @ELLIOTTCABLE! I'll keep an eye on this to see if it gets future requests. This would carry with it baggage for `_.pull` too and I don't want to inflate the API for those at the moment.

Until then something with `_.findIndex()` + `Arraysplice` may be doable.

**Comment by kevinawoo** [comment]
+1 for `_.removeFirst(array, predicate)`.

**Comment by saaqibz** [comment]
the workaround is fine but +1 for requesting this shortcut.

**Comment by asn007** [comment]
+1 for requesting this, would be lovely

**Comment by datico** [comment]
First time trying to use lodash for me, having just discovered it...
._removeLast() is exactly the functionality I need, and it's not there. _.findLast is....
Why leave an incomplete feature set? If I was going to write extra code (the aforementioned workaround), I wouldn't be using _.lodash in the first place. ;-)   

+1 for this request.

**Comment by jdalton** [comment]
Folks, don't forget to [vote with the :+1: reaction](https://help.github.com/articles/about-discussions-in-issues-and-pull-requests/). It makes [sorting](https://help.github.com/articles/about-discussions-in-issues-and-pull-requests/#sorting-issues-and-pull-requests-by-reaction) popular requests easier.

**Comment by jfmengels** [comment]
Am I correctly understanding that this is a request for a mutating [`initial`](https://lodash.com/docs#initial) and [`tail`](https://lodash.com/docs#tail)?

**Comment by rizoom** [comment]
No, it is a `remove` that stop iterating once predicate returns a truthy result as explicity stated by OP.
I'll use the given workaround for the moment.

**Comment by simonered** [comment]
any news?

**Comment by prolink007** [comment]
Anything new on this? I would love to see removeFirst as well.
