### ISSUE TITLE
handling of special chars in i.e. startCase

### ISSUE THREAD

**Issue by hrmoller** [lodash/lodash#1115]
It would be nice if lodash could handle special chars (i.e. æ ø å)
example:
```
_.startCase('høst');
// returns 'Host'
```

**Comment by jdalton** [comment]
Because this is a case method it's made to play nice with other case methods which means deburring compound words. That said as with everything it can always be re-evaluate at a later time. If you're wanting to capitalize there's `_.capitalize`.
