### ISSUE TITLE
pluralize using similar implementation to underscore.inflection

### ISSUE THREAD

**Issue by meg2208** [lodash/lodash#1116]
Could we get an implementation like this:

https://github.com/jeremyruppel/underscore.inflection

into lodash?

**Comment by jdalton** [comment]
Figuring out proper plural cases [is complex](https://github.com/jeremyruppel/underscore.inflection/blob/3edafa30b5c4f1178e34cf70322dbdd2f65049cd/lib/underscore.inflection.js#L179-L249). I wanna stay out of localization for now as there are project dedicated entirely to that.

**Comment by internalfx** [comment]
+1
