### ISSUE TITLE
Reduce return value on empty array

### ISSUE THREAD

**Issue by aug-riedinger** [lodash/lodash#1117]
I would definitely expect `_.reduce([], true)` to return `true` but it returns `undefined` instead.

As mentionned in the doc:

> [accumulator] (*): The initial value.
> (*): Returns the accumulated value.

So the looping behavior went on 0 time, but the initial value of the accumulator should be returned, shouldn't it?

If that's on purpose, could I get some explanation on why?

**Comment by jridgewell** [comment]
The call signature is `_.reduce(collection, [iteratee=_.identity], [accumulator], [thisArg])`. The initial accumulator is the third argument, not the second.

```javascript
_.reduce([], _.identity, true); // => true
```

**Comment by aug-riedinger** [comment]
Thanks!

I guess I'd expected it to have a jquery-like signature: if second argument is not a function, then it is the accumulator.
