### ISSUE TITLE
How can I manipulate the foreach statement to provide a line break

### ISSUE THREAD

**Issue by xtianus79** [lodash/lodash#1120]
for example: 
```js
// using the "evaluate" delimiter to execute JavaScript and generate HTML
var compiled = _.template('<% _.forEach(users, function(user) { %><li><%- user %></li><% }); %>');
compiled({ 'users': ['fred', 'barney'] });
// → '<li>fred</li><li>barney</li>'
```
having <li>fred and <li> barney on the same line is not desirable.

**Comment by jdalton** [comment]
Try:
```js
_.template('<% _.forEach(users, function(user) { %><li><%- user %></li>\n<% }); %>');
```

**Comment by xtianus79** [comment]
that's not wokring.. here is my output. 

_.template('<li>Star Wars!</li>\n<li>Foundation5Application</li>\n');

**Comment by jdalton** [comment]
Looks like this isn't a lodash issue as I verified the newlines do work. Look for whatever is handling your template as it's probably performing the extra escaping.
