### ISSUE TITLE
Supporting ES6 Map

### ISSUE THREAD

**Issue by tgriesser** [lodash/lodash#1121]
Did a bit of searching and didn't see related tickets right away, so I wanted to check if there were any plans to support iterating structures like ES6 `Map` or I guess more generally ES6 iterables:

```js
var m = new Map([['a', 1], ['b', 2]])

_.forEach(m, (val, key) => {
  console.log(val) // 1, 2
})
```

This would be great because maps eliminate weird edge cases of treating an object like map (among other things). I'm currently using other libraries which support unified iteration between object/map but it'd be great if this were a case lodash could support.

If performance is a concern, perhaps it could be opt-in as a superset of collection?

```js
import forEach from 'lodash/iteration/forEach'
```

**Comment by jdalton** [comment]
See #737. Adding support for it is a bit hefty. For your example IE11 doesn't support `new Map([['a', 1], ['b', 2]])`, creates an empty map, but does support `Map#.forEach`. As demand picks up I'll consider it, but currently I'm holding off.

**Comment by tgriesser** [comment]
Ah I gotcha, thanks... somehow missed that one. I'll subscribe there, hopefully it'll get reconsidered once ES6/2015? becomes official.
