### ISSUE TITLE
Spread Last Parameter

### ISSUE THREAD

**Issue by jridgewell** [lodash/lodash#1122]
To make `_.restParam` and `_.spread` match, what do you think of spreading the last parameter to `_.spread`? Isn't very pretty, but shows how it could be used:

```javascript
var nativeBind = _.spread(Function.prototype.bind);
var bind = _.restParam(function(fn, context, args) {
    return nativeBind.call(fn, context, args);
});
```

Even better might be to add an instantly invoking `_.spreadParam` (`_.spreadArgs`? :stuck_out_tongue:), since the spread argument is usually used at runtime, where `_.restParam` would mainly be used at parse-time.

```javascript
var nativeBind = Function.prototype.bind;
var bind = _.restParam(function(fn, context, args) {
    return _.spreadParam(nativeBind, fn, context, args);
});
```

As you might guess, this is because of this [shenanigans](https://github.com/jridgewell/underscore/commit/6cc4bce16e7ec6cb2e4bb95cbea16727032ff33d).

**Comment by jdalton** [comment]
I'm not sure I understand. You mean mean making the last param of function created by `_.spread` a rest param?

`_.spread` just does:
```js
    function spread(func) {
      if (typeof func != 'function') {
        throw new TypeError(FUNC_ERROR_TEXT);
      }
      return function(array) {
        return func.apply(this, array);
      };
    }
```

So in your example:
```js
var nativeBind = _.spread(Function.prototype.bind);
```

Would call `nativeBind(context)` only which seems odd.

**Comment by jridgewell** [comment]
My example is very bad, but it's what got me thinking of it.

`_.restParam` aggregates into the last parameter of the function. `_.spread` should spread it's last argument.

```javascript
function spread() {
  return function() {
    var length = arguments.length - 1,
        index = -1,
        args = Array(length),
        spread = arguments[length];
    while (++index < length) {
      args[index] = arguments[index];
    }
    index = -1;
    length = spread.length;
    while (++index < length) {
      args.push(spread[index]);
    }
    func.apply(this, args);
  };
};

**Comment by jdalton** [comment]
Ah I see.

**Comment by jridgewell** [comment]
Yah, this might work better as `_.spreadParam`, leaving the current implementation as `_.spread`.

But it would match (a little closer) to an ES6 spread param:

```javascript
fn(1, 2, ...[1, 2, 3]);
_.spreadParam(fn, 1, 2, [1, 2, 3]);

**Comment by jdalton** [comment]
I think adding an `index` param like `_.restParam` and defaulting to `func.length - 1` is fine. We kept `_.spread` simple to begin with the idea of possibly expanding it. So this is fine.

**Comment by jridgewell** [comment]
> and defaulting to func.length - 1

Well, it's not `func` that has the right length, it's whatever the invoked function's `arguments.length` is:

```javascript
var fn = _.spread(funciton() {
  return arguments;
});

fn(1, 2, [3, 4]); // => 1, 2, 3, 4
fn(1, 2, 3, [4, 5]); // => 1, 2, 3, 4, 5
```

That's why I was suggesting `_.spreadParam`. Since rest parameters are static (since they're _part_ of the parameter list of the function when it's parsed), it's fine to return a function from `_.restParam`.

```javascript
var fn = function(a, b, ...args) {
  return args;
}
fn(1, 2, 3, 4, 5); // => 3, 4, 5

fn = _.restParam(function(a, b, args) {
  return args;
});
fn(1, 2, 3, 4, 5); // => 3, 4, 5
```

But, spread operators are for when you're invoking a function at runtime, so they're not tied to the function but to the invocation.

```javascript
var fn = function() {
  return argumetns;
};
fn(1, 2, ...[3, 4, 5]); // => 1, 2, 3, 4, 5

_.spreadParam(fn, 1, 2, [3, 4, 5]); // => 1, 2, 3, 4, 5
```

While `_.spread` is fine, it's made for creating a new function at parse time which'll prevent you from using it in a loop unless you want to wrap the function beforehand, which isn't quite as useful:

```javascript
class Test {
    fn(a, b, ...args) {
        return args;
    }
}


(function(n) {
  var test = new Test();
  var fn = _.spread(test.fn);
  _.times(n, function() {
    fn(1, 2, [3, 4, 5]);
    // Opposed to spread operator just calling the method
    test.fn(1, 2, ...[3, 4, 5])
    _.spreadParam(fn, 1, 2, [3, 4, 5]);
  });
)(100);
```

- - -

Now that I think about it some more, it might need a context, too:

```javascript
_.spreadOperator = _.restParam(function(func, context, args) {
  var spread = args.pop(),
      index = -1,
      length = getLength(spread);
  while (++index < length) {
    args.push(spread[index]);
  }
  func.apply(context, args);
};
```

**Comment by jridgewell** [comment]
Sorry, I'm bored waiting for people and leaving way to long of comments.

```javascript
    function baseSpread(func, context, args) {
      var spread = args.pop(),
          index = -1,
          length = getLength(spread);
      while (++index < length) {
        args.push(spread[index]);
      }
      return func.apply(context, args);
    }

    function spread(func) {
      if (typeof func != 'function') {
        throw new TypeError(FUNC_ERROR_TEXT);
      }
      return restParam(function(args) {
        return baseSpread(func, this, args);
      });
    }

    var spreadOperator = restParam(baseSpread);
```

**Comment by jdalton** [comment]
Ah thanks for clarifying. Lets hold off a bit. I wanna get some other dev feedback on `restParam` and `spread` before adding additional `spread` like methods.
