### ISSUE TITLE
Feature: Deep freeze, immutable "mutators"

### ISSUE THREAD

**Issue by Ciantic** [lodash/lodash#1124]
I'm not sure what is the stated goal of Lodash, but it would be nice to have a deep freezing capability of objects. `Object.freeze` freezes the object properties, not their contents. There could be other immutable mutator functions which may be useful to implement. E.g. to modify a frozen object one creates a clone, then modifies it, and freezes again.

**Comment by jdalton** [comment]
Hi @Ciantic! I want to avoid functionality that would be completely broken in older environments. Our use of ES5 and ES6 has been done in a way that still keeps the behaviors of the API consistent across environments.

**Comment by Ciantic** [comment]
You want to create utility library without modern utility functions? I think the target should move, ever so slowly, towards newer parts of the JS, immutability is really important part in latest frameworks such as React and Angular 2.

I know that it could create a class of functions, that does not work with older browsers, but in case of immutability the functions could be named to support freezing etc.

**Comment by jdalton** [comment]
> You want to create utility library without modern utility functions?

lodash is already using `Array.isArray`, `Date.now`, `Object.create`, `Object.assign`, `Set`, `WeakMap`, `_.memoize` has a `Map` interface, we have `_.isTypedArray` and support cloning typed arrays, and we supports Symbols and has an ES module build.

**Comment by Ciantic** [comment]
I see, so the difference is that the ones you list have a fallback mechanism. `Object.freeze` will never be supported in older browsers, and there never will be a fallback mechanism. But soon a lot of utility functions is required to deal with immutables, ignoring them seems short sighted.

I suppose you could state a goal in the website, that the functionality you plan to implement should have backwards compatibility.

**Comment by jdalton** [comment]
> But soon a lot of utility functions is required to deal with immutables, ignoring them seems short sighted.

Plenty of lodash methods work with immutables.

> I suppose you could state a goal in the website,

Naw, take your sour grapes elsewhere.
