### ISSUE TITLE
Enhancement proposal : Improve lazy evaluation 

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [lodash/lodash#1127]
Hello, 

I have an idea of a useful feature for lodash. Sometimes we have a lot of data and we want to make operations on it (map) and then find any one of them who satisfy some predicate (find). But I remarked that the lazy evaluation is not lazy at all (maybe I'm not using it correctly). I think when we do map followed by a find (or any) we should check the predicate as soon as we have one value available. Currently in lodash we wait for the map to be finished for all values. 

In a more formal we we can say that

```
a.map(f).find(p)  = a.find(f°p) 
```

I know this is true only if we assume that f does not produce any side-effects (maybe it is the reason why it is not implemented already) but the second one is much faster.

Do you think it would be a good idea ?

I didn't dive into the code yet but I think it would be easy. (I assume the chaining of operations are implemented using a stack of operations that are only called when value() is called). We just need to check when value() is called if such a pattern happens and replace the operations in the stack.

I know some functional languages already do this kind of optimization (scala which has also the problem with side-effects).

Best regards

**Comment by jdalton** [comment]
Hi @GuillaumeLeclerc we have lazy-eval/shortcut-fusion [in several methods](https://lodash.com/docs#_). Next on the list is to investigate making `_.reduce` and `_.reduceRight` support it. Methods like `_.find` are further down the list.

**Comment by GuillaumeLeclerc** [comment]
I already looked at this list (I saw find was not in it, that's why I made this issue). But I don't see your "investigation list" where reduce and reduceRight come before find. 

Which shortcut fusion do you want to implement with reduce ?

Do you need help implementing them ?

**Comment by jdalton** [comment]
> But I don't see your "investigation list" where `_.reduce` and `_.reduceRight` come before find.

You can check the [roadmap](https://github.com/lodash/lodash/wiki/Roadmap) for planned features and changes.

> Which shortcut fusion do you want to implement with `_.reduce`?

The `_.reduce` and `_.reduceRight` will terminate the lazy sequence. I haven't dug too deep into it at the moment.

> Do you need help implementing them?

Not at the moment. I'm tackling this a bit later.
