### ISSUE TITLE
zipWith, is this something people might want?

### ISSUE THREAD

**Issue by thirdcreed** [lodash/lodash#1128]
I've ended up using a function enough in Haskell, that I thought it might merit addition to lodash.
It's called `zipWith`:
```js
_.zipWith([1,2,3],[10,11,12], function(a,b){
      return a + b;
});

//=> [11,14,15]   
```

It can be done with by reducing a lists of lists, but I like this layer of abstraction, for reasoning about the combining of lists,  If I want to combine lists I specify how I would like them combined with a folding function, and then give the `n` lists that I want to combine in that way.

I've written a version of this on my fork, does anyone else see merit in something like this?

**Comment by jdalton** [comment]
I can dig it. I've seen methods like this around too.

**Comment by thirdcreed** [comment]
Great I can send a pull request , my implementation uses a lot of other lodash functions, is there a general preference for native imperative internals?

**Comment by thirdcreed** [comment]
I'll write two versions and send two requests

**Comment by jdalton** [comment]
> my implementation uses a lot of other lodash functions, is there a general preference for native imperative internals?

Naw keep it as 1 version. We can tweak and adjust once you have PR.

**Comment by thirdcreed** [comment]
Sounds good.

**Comment by jdalton** [comment]
Moving to #1129.
