### ISSUE TITLE
_.slice

### ISSUE THREAD

**Issue by AjaxSolutions** [lodash/lodash#1131]
"Note: This function is used instead of Array#slice to support node lists in IE < 9 and to ensure dense arrays are returned."

Can you provide an example showing how Array.prototype slice can fail and why _.slice should be used instead?  Underscore doesn't provide the _.slice method.

**Comment by jdalton** [comment]
Sure thing.
```js
Array.prototype.slice.call(document.getElementsByTagName('*'));
```
