### ISSUE TITLE
Initial counter value for uniqueId()

### ISSUE THREAD

**Issue by adamboduch** [lodash/lodash#1132]
It would be super handy if `uniqueId()` could accept an optional second argument. Call it `start` maybe? Basically, I'd like to start counting from where I last left off instead of at 0. Something along the lines of:

```javascript
function uniqueId(prefix, start) {
  if (start && idCounter === 0) {
      idCounter = start;
  }
  var id = ++idCounter;
  return baseToString(prefix) + id;
}
```

**Comment by jdalton** [comment]
Hi Adam!

When you use `_.runInContext()` it would create a fresh `idCounter` but currently we don't have a way to customize it. The method is so simple, and I dig that, I think if push came to shove it could be overwritten with the correct seed. I'll keep an eye on the request though to see if we need to beef up `_.uniqueId`.

**Comment by cyonder** [comment]
+1
