### ISSUE TITLE
invokeRight

### ISSUE THREAD

**Issue by bcherny** [lodash/lodash#1135]
```js
let array = [1,2,3]

// before
_(array)
  .forEachRight (_) => _.method()
  .value()

// after
_(array)
  .invokeRight 'method'
  .value()
```

**Comment by jdalton** [comment]
I'm not sure why iteration order would matter here. What's the use case for it?
With v3.7 you can also do:
```js
_(array)
  .forEachRight (_.method('method'))
  .value()
```

**Comment by bcherny** [comment]
I need to close modals in the opposite order in which they were opened. In general, it's nice to have reverse loop equivalents for common operations.

**Comment by StreetStrider** [comment]
@bcherny, how many modals you have? Maybe you should just `reverse` collection? `right` methods are applicable when reversing collection is too expesive.

**Comment by jdalton** [comment]
While making a right form is trivial I want to avoid it because `invoke` has map baggage and would create an array that may be iterated over oddly in older enviros. It would have its values assigned from right to left and some older envrios may iterate over them in that order when doing something like a for-in or shimmed `Object.keys`.

**Comment by bcherny** [comment]
@StreetStrider i was mostly interested in it for syntax purposes-

```js
// ugly
let n = array.length
while (n--) {
  array[n].method()
}

// better
_ array
  .slice()
  .reverse()
  .forEach (_) => _.method()
  .value()

// even better
_ array
  .forEachRight (_) => _.method()
  .value()

// best
_(array)
  .invokeRight 'method'
  .value()
```

**Comment by StreetStrider** [comment]
@bcherny, yeah, looks very compact.

**Comment by jridgewell** [comment]
@jdalton pointed out that their is a Lodash method called `#method` in 3.7. Since you're using `_` as your iteration value, it's not apparent:

```javascript
_(array).forEachRight((obj) => obj.method()).value()

// Using #method
_.(array).forEachRight(_.method('method')).value()
```
