### ISSUE TITLE
_.pick does not work for function properties

### ISSUE THREAD

**Issue by akloeber** [lodash/lodash#1137]
If a property is a function it does not get picked (even if the function returns a truthy value):
````
_.pick({
  foo: _.noop
}, 'foo');
-> {}
````
whereas:
````
_.pick({
  foo: 0
}, 'foo');
-> {"foo":0}
````
Is there something that I'm missing? The documentation does not mention any conditions for the property types.

__Environment:__
lodash 3.7.0
node v0.12.0

**Comment by jdalton** [comment]
Hi @akloeber! I cannot repro this issue as it returns `{ 'foo: noop }`.

**Comment by akloeber** [comment]
Sorry, my fault. I had a strange behavior and wanted to make a minimal example. In fact the logging library used `JSON.stringify()` which eliminated the function property and set me on the wrong track. In fact `_.pick` works as expected.
