### ISSUE TITLE
_.has examples do not work.

### ISSUE THREAD

**Issue by rBurgett** [lodash/lodash#1138]
The _.has examples from https://lodash.com/docs#has doe not actually work. There are three examples on the page:

var object = { 'a': { 'b': { 'c': 3 } } };
_.has(object, 'a');
// → true
_.has(object, 'a.b.c');
// → true
_.has(object, ['a', 'b', 'c']);
// → true

Only the first actually returns true. The other two return false. Just thought I'd share :-).

**Comment by jdalton** [comment]
Works for me. Try clearing your browser cache.

**Comment by pidofme** [comment]
Didn't work for me too. Test in Node.js v0.12.2, get true false false.
