### ISSUE TITLE
Pluck should return same collection type and maintain keys

### ISSUE THREAD

**Issue by jonahbron** [lodash/lodash#1141]
Right now, `pluck` always returns an array, regardless of the type of collection you give it.  A use case I'm running into is using `indexBy` and `pluck` to adapt an array of objects.  I'd expect to be able to do this with:

    _.pluck(_.indexBy(data, 'id'), 'value');

To turn this:

    [
        {
            "id": 1,
            "value": "foo"
        }
    ]

Into this:

    {
        "1": "foo"
    }

But the actual result is an array with they keys lost.

    [
        "foo"
    ]

I'd be happy to submit a pull-request to fix this, but I want to know if this is a desired behavior before I go to the trouble.  Is there a particular reason that it _should_ always return an array?

**Comment by megawac** [comment]
Use `mapValues` instead of `pluck`

**Comment by jonahbron** [comment]
@megawac Yes, that would do the trick.  Am I to understand that `pluck` is explicitly meant to return an array?

**Comment by jridgewell** [comment]
> Am I to understand that pluck is explicitly meant to return an array?

Yup.

**Comment by jonahbron** [comment]
All righty, thanks.

**Comment by jdalton** [comment]
> Am I to understand that pluck is explicitly meant to return an array?

Yap `_.pluck` can be seen as a more clear version of `_.map(array, _.property('propName')` or `_.map(array, 'propName')`.

**Comment by jonahbron** [comment]
@jdalton Ah, that makes sense.  Thanks :smile:

**Comment by jonahbron** [comment]
I feel like that smiley is a little too aggressively happy.
