### ISSUE TITLE
_.push

### ISSUE THREAD

**Issue by tgriesser** [lodash/lodash#1145]
Wondering if there's ever been a request for a convenience function similar to `_.set`, but for deeply pushing a value onto an array, creating one if it doesn't exist:

```js
_.push = function(obj, path, value) {
  var arr = _.get(obj, path.slice(0, -1), [])
  if (!_.isArray(arr)) arr = []
  arr.push(val)
  return _.set(obj, path.slice(0, -1), arr)
}
```

**Comment by jdalton** [comment]
That's a bit too far off the built-in `push` to be named that. I'm wondering if other path sugar would be appropriate. I've seen some allow `-1` fro `length - 1`. I'm not sure how `push` would be represented. Any ideas?

**Comment by tgriesser** [comment]
Actually, maybe just a deep `_.update` would be a good start, so you could do:

```js
_.update(obj, path, function(val) {
  return (isArray(val) ? val : []).concat(someVal)
})
```

**Comment by gibson042** [comment]
FWIW, JSON Pointer and JSON Patch use "-" for end of array: https://tools.ietf.org/html/rfc6901#section-4 https://tools.ietf.org/html/rfc6902#section-4.1

**Comment by jdalton** [comment]
Hmm. Ok I think I'm cool with punting to `_.get(object, path).push(value)`.

**Comment by JulianKingman** [comment]
I realize this is long since closed, but I just came across this. What do you think about doing `_.set(object, 'path.[]', value)`?

**Comment by f3l1x** [comment]
I've just solved it with `_.get(object, path, []).push(value)`. As @jdalton posted. Thanks.

**Comment by kbsanders** [comment]
@jdalton, @f3l1x correct me if I'm wrong, but `_.get(object, path, []).push(value)` won't actually mutate `object` so in the end you're still left with the same base object you started with, without the appended path or pushed value.

In contrast, `_.set()` creates portions of `path` that don't exist.

I agree with @JulianKingman that `_.set(object, 'path[]', value)` makes the most sense.

**Comment by felds** [comment]
I'm trying to wrap my head around it but I'm failing to see an use case… Can you guys help me with that?

**Comment by StreetStrider** [comment]
@felds don't bother yourself. There's no actual use-case in pushing to/modifying deeply nested objects. It's just a dire lack of decomposition.

**Comment by kbsanders** [comment]
A contrived example for my use case, injecting nested values into a configuration object before being passed onto a parent class, for properties that may or may not already exist in the configuration:

```javascript
class RedWidget extends Component {

    initComponent( cfg ) {

        cfg = cfg || {};

        // ideal
        _.set( cfg, "styles.wrapper[]", "background-color: red;" );

        // less than ideal
        // cfg.styles = cfg.styles || {};
        // cfg.styles.wrapper = cfg.styles.wrapper || [];
        // cfg.styles.wrapper.push( "background-color: red;" );

        super.initComponent( cfg );
    }
}
```

**Comment by StreetStrider** [comment]
@kbsanders I would recommend to try some solution on `merge`/`mergeWith`:
```js
var defaults =
{
  // your desired defaults (may be nested)
  styles:
  {
    wrapper: [ 'background-color: red;' ]
  }
}

cfg = merge({}, defaults, cfg)
```

You may need `mergeWith`'s `customizer` for handling some specific cases. Or you may transform `wrapper` to `{ 'background-color': 'red' }` to evade using customizer.

However, I still think this is a kind of lacking of sub-objects. Like `styles` looks for me as a special manager object with its own methods and responsibilities.

**Comment by synatree** [comment]
@felds There are lots of use cases.  I'm using @kbsanders solution for processing an object coming from another source.
```js
    var subscriptions = [];
    var triggers = {};
    _.each(channels, function (mod, key) {   // channels is an object with string keys and object values.
        _.each(mod, function (path, pathkey) {  // path is an object with string keys and object values.
            _.each(path, function (timing, verb) {  // timing is an int
                // first set up listener.
                _.set(subscriptions, '[]', `${key}/${pathkey}/${verb}`); // add this string concatenation to subscriptions
                _.set(triggers, `${key}/${pathkey}[]`, { command: verb, timer: timing }); // add a new trigger or append to existing.
            })
        })
    });
```

**Comment by amaster507** [comment]
I have often needed to push data to a path and while _.set(...) works well for setting a whole set of data, it does not quite fulfill the need of appending data to an array at a path in an object. While the _.get(...).push(...) method works for setting data to an already existing path, it does not create the path when needed like _.set(object, 'new.path', value) does.

I added two additional parameters to this that is not standard to _.set parameters.

I have needed to pass an array and then merge that array with the array already existing at the path, but also have the option to push an array as the single value as well. So to solve this switch case I have added the Boolean parameter expand.

I have also needed to remove duplicates in the merge process so that an array works more like a JavaScript Set. To solve this switch case I have added the Boolean parameter preventDup

I have wrote a plain JavaScript function using vanilla JavaScript and a few lodash functions to implement my version of this. I have thought about writing an extension and making it publicly available, but would rather like to see it in the core of lodash if possible.

```javascript
const loPush = (object, pathToArray, value, expand = false, preventDup = false) => {
  let a = _.get(object, pathToArray) || [];
  if (expand && value.isArray()) {
    if (preventDup) {
      _.forEach(value, v => {
        if(!a.includes(v)) {
          a.push(v);
        }
      })
    } else {
      a.push(...value)
    }
  } else if (expand) {
    throw new Error('Expand option set to true, but value given was not an array');
  } else {
    if (preventDup) {
      if(!a.includes(value)) {
        a.push(value);
      }
    } else {
      a.push(value);
    }
  } 
  _.set(object, pathToArray, a)
  return object
}
```

The expand and preventDup parameters could be turned into an options group like many other libraries have. This would change the first line into two lines:

```javascript
const loPush = (object, pathToArray, value, options) => {
  const { expand = false, preventDup = false } = options
```

**Comment by matrunchyk** [comment]
@amaster507 I think this

> if (expand && value.isArray()) {

should be changed to 

> if (expand && Array.isArray(value)) {

so it won't throw `value.isArray()` is not a function

**Comment by SimonEast** [comment]
Here's my simple version of `_.push`, similar to original post but correctly handles both string and array-style paths:

```js
/**
 * Push an item onto an array even if the path to the array doesn't exist yet
 * 
 * Example:
 * push({}, 'key', 'value') mutates the object to become {key: ['value']}
 */
function push(baseObject, path, value) {
  let currentArrayLength = _.get(baseObject, path, []).length;
  let pathAsArray = _.toPath(path);
  path.push(currentArrayLength);
  _.set(baseObject, path, value);
}
```

Would be nice to see something similar to this integrated into Lodash at some point.

**Comment by CongAn** [comment]
pushSafe.ts

```ts
import { get, set, isArray } from 'lodash'
import { PropertyPath } from 'lodash'

/**
 * 根据object对象的path路径，
 * 安全向数组（不存则会创建该数组）的末尾添加一个或多个元素，并返回新的长度。
 */
export function pushSafe<V>(object: object, path: PropertyPath, ...items: V[]): number
export function pushSafe<V, T extends object>(object: T,  path: PropertyPath, ...items: V[]): number {
    let array = get(object, path)
    if (array === undefined) {
        set(object, path, array = [])
    }
    if (!isArray(array)) {
        throw new Error('The object path of push is not an array.');
    }
    // @ts-ignore
    return array.push(...items)
}

export default pushSafe
```

**Comment by CongAn** [comment]
pushSafe.ts

```ts
import { get, set, isArray } from 'lodash'
import { PropertyPath } from 'lodash'

/**
 * 根据object对象的path路径，
 * 安全向数组（不存则会创建该数组）的末尾添加一个或多个元素，并返回新的长度。
 * @author https://github.com/CongAn
 */
export function pushSafe<V>(object: object, path: PropertyPath, ...items: V[]): number
export function pushSafe<V, T extends object>(object: T,  path: PropertyPath, ...items: V[]): number {
    let array = get(object, path)
    if (array === undefined) {
        set(object, path, array = [])
    }
    if (!isArray(array)) {
        throw new Error('The object path of push is not an array.');
    }
    return array.push(...items)
}

export default pushSafe
```
