### ISSUE TITLE
Intersection of a single array should be the array itself (?)

### ISSUE THREAD

**Issue by dominykas** [lodash/lodash#1147]
`lodash@3.6.0`:
```
> require("lodash").intersection([ 1, 2, 3]);
[ 1, 2, 3 ]
```

`lodash@3.7.0`:
```
> require("lodash").intersection([ 1, 2, 3]);
[]
```

Possibly caused by the fix for #1085?

**Comment by davidkpiano** [comment]
I think this makes sense because the intersection of a set and an empty set is the empty set. It's as if you're calling `_.intersection([1, 2, 3], []);`

**Comment by jdalton** [comment]
Yah, @davidkpiano is right. The intersection between an array and nothing is nothing. This also aligns with Underscore.

**Comment by spicyj** [comment]
This behavior doesn't make sense to me. Maybe if `_.intersection` took exactly two args, but not if it takes arbitrarily many:

These should return the same thing:

```js
_.intersection([1, 2, 3], [1, 2, 3], [1, 2, 3])  // [1, 2, 3] -- yup!
_.intersection([1, 2, 3], [1, 2, 3])  // [1, 2, 3] -- yup!
_.intersection([1, 2, 3])  // [] -- wrong
```

Adding an empty list is different semantically:

```
_.intersection([1, 2, 3], [1, 2, 3], [])  // [] -- yup!
_.intersection([1, 2, 3], [1, 2, 3])  // [1, 2, 3] -- yup!

_.intersection([1, 2, 3], [])  // [] -- yup!
_.intersection([1, 2, 3])  // [] -- wrong
```

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash/commit/c6ff845ecb3891089afe8b8696f7586a19452f07.

**Comment by spicyj** [comment]
Got it, thank you and sorry for missing that!
