### ISSUE TITLE
_.isNumeric

### ISSUE THREAD

**Issue by brandoncarl** [lodash/lodash#1148]
Hi all –

I know that `isFinite` and `isNumber` and `isNaN` have been discussed ad nauseum, but I think they leave a big gap in functionality.

Given that JS is not typed, when working with third-party data, it's often important to check whether something is "numeric".

This would function as follows:
```js
_.isNumeric() // => false
_.isNumeric(undefined) // => false
_.isNumeric(null) // => false
_.isNumeric(new Number()) // => false
_.isNumeric(Infinity) // => false
_.isNumeric(15.5) // => true
_.isNumeric("15.5") // => true
```
I find that I'm often cobbling together some combination of functions to achieve this. I believe that it could be solved with something like the following.

```js
function isNumeric(x) {
  return !(isNaN(x)) && (typeof x === "object") &&
    (x != Number.POSITIVE_INFINITY) && (x != Number.NEGATIVE_INFINITY);
}
```

Cheers!

**Comment by jdalton** [comment]
I think `isNumeric` is a little wish-washy in terms of definition. I would assume anything that can coerce to a finite number successfully would be numeric so allowing number objects. I think in this case other restrictions apply like you'd want to `floor` the value or something. The built-in `isFinite` of the global object can do that.

**Comment by brandoncarl** [comment]
Thanks for your input @jdalton. A few further thoughts.

1. You bring up a good point about number object coercion. Effectively, we're talking about anything that is immediately coerced into a finite number.

2. As far as definition, these functions do exist in other languages (like Python), although they operate on strings. For example, https://docs.python.org/2.7/library/stdtypes.html#str.isdigit.

3. Along these lines, the better definition/implementation can be found at this jsperf: http://jsperf.com/isnumeric.

4. There are at least two primary use cases with respect to this:
  A) In JS, object keys are stored as strings, even if set as numbers. For example, `Object.keys({ 1 : "HI" }) = ["1"];` This sort of problem arises frequently in stores like MongoDB, where objects must be used over arrays for multiple subdocument indexing.
  B) clean or dirty JSON, often via http methods. It's not uncommon that third-party errors will be reported as "544". 

As far as I'm concerned, you run one of the best maintained and coded repos on the web. I'm deferring to your expertise. I'm not married to the implementation or the precise definition. That said, I do think that there are real use-cases for this.

**Comment by gajus** [comment]
https://www.npmjs.com/package/is-numeric this implementation covers all of the reasonable scenarios. I too would like to see this as part of a lodash tool belt.

**Comment by gajus** [comment]
Here is an extensive coverage of the expected behaviour of this function. http://stackoverflow.com/questions/18082/validate-decimal-numbers-in-javascript-isnumeric

**Comment by jdalton** [comment]
As I [mentioned](https://github.com/lodash/lodash/issues/1148#issuecomment-94480100) before, [isFinite](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isFinite) is your friend.

**Comment by gajus** [comment]
Which is basically what everyone agreed to in the SOF question.

```js
function isNumeric (n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
}
```

What is the reason this cannot be in `lodash`?

**Comment by brandoncarl** [comment]
isFinite is a great function, however, it does not identify "stringified" finites. isNumeric would be intended to resolve that.

**Comment by gajus** [comment]
@jdalton Have you thought of creating/using some sort of system that would allow people to vote what features `lodash` should have?

**Comment by gajus** [comment]
There is very little incentive to contribute even ideas if they are debunked by a single person.

**Comment by brandoncarl** [comment]
@gajus In my experience, @jdalton is really open to new ideas. I think in this case we just need to do a good job at making the use case for it. I do think that this is really important for parsing dirty JSON, as well as examining JS objects, where the keys may be numeric (array-like), but have been input as strings.

**Comment by jdalton** [comment]
@brandoncarl
> isFinite is a great function, however, it does not identify "stringified" finites.

It does though. It's very similar to the results expected, there are a few that don't align but for the most part it does the job.

```js
isFinite(123) true
isFinite(-123) true
isFinite(+123) true
isFinite('123') true
isFinite('-123') true
isFinite('+123') true
isFinite('.123') true
isFinite('-.123') true
isFinite('0.123') true
isFinite('-0.123') true
isFinite('1e100') true
isFinite('1e-100') true
isFinite('-1e-100') true
isFinite(Infinity) false // isNumeric true
isFinite(-Infinity) false // isNumeric true
isFinite('abc') false
isFinite('10%') false
isFinite('#10') false
isFinite('2^10') false
isFinite('2!') false
isFinite('(10)') false
isFinite('10px') false
isFinite('*') false
isFinite('') true // isNumeric false
isFinite(true) true // isNumeric false
isFinite(false) true // isNumeric false
isFinite([]) true // isNumeric false
isFinite(function(){}) false
isFinite({}) false
isFinite(undefined) false
isFinite(null) true // isNumeric false
```

**Comment by brandoncarl** [comment]
@jdalton I'm running 3.9.3 and seeing different results. Going to investigate!

**Comment by jdalton** [comment]
I'm referring to the built-in global `isFinite` method and not the `_.isFinite`.

**Comment by jdalton** [comment]
The lodash `_.isFinite` method is based on [Number.isFinite](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite).

**Comment by brandoncarl** [comment]
@jdalton Ah, so used to using lodash for everything that I'd forgotten about that!

**Comment by brandoncarl** [comment]
@jdalton As you highlighted, it differs in some key ways from the proposed "isNumeric". I do agree with @gajus though that "isNumeric" is really necessary. To my knowledge, nowhere in Javascript do we have a "duck test" for a number. When I see something that looks like a number, I would love to call it numeric!

Would appreciate if you consider adding it under the use cases discussed. Cheers.

**Comment by jdalton** [comment]
It differences are manageable and/or debatably better than `isNumeric`.

You probably don't want to use `Infinity`:
```js
isFinite(Infinity) false // isNumeric true
isFinite(-Infinity) false // isNumeric true
```

These are alright as they coerce to `0` or `0`
```js
isFinite('') // 0
isFinite(true) // 1
isFinite(false) // 0
```

The only odd one is really the empty array which coerces to `0` which isn't an issue in your json string scenario anyways.
```js
isFinite([]) // 0
```

**Comment by jdalton** [comment]
@gajus

> Have you thought of creating/using some sort of system that would allow people to vote what features lodash should have?

So far I use frequency of requests and :+1:'s as a couple metrics.

> There is very little incentive to contribute even ideas if they are debunked by a single person.

Someone's got to lead and keep things chugging along. A part of that job is saying "No" a lot.
On the bright side my "No"s are hardly ever "Never"s.

**Comment by servel333** [comment]
I was curious how the various proposed methods faired so I wrote some tests. Since I wrote the code anyway, I made a Fiddle https://jsfiddle.net/servel333/p61km26L/

**Comment by brandoncarl** [comment]
@servel333 Thanks for putting this together! It made me realize my original code had a typo. It should have read (typeof x !== "object").

Secondly, I've come to realize "isNumeric" is a misnomer. Better language would be "isNumberLike".

As a result, Infinity and -Infinity should not be numbers. Neither should arithmetic operations like 2^10 (in that case you should include 2*10, 2+10, etc.). Finally, given that the main use case for a function like this is parsing, I would personally not include things like new Number().

Nice work!

**Comment by amenadiel** [comment]
@jdalton 
> It does though. It's very similar to the results expected, there are a few that don't align but for the most part it does the job.
> 
> isFinite(123) true
> isFinite(-123) true
> isFinite(+123) true
> isFinite('123') true

At this point ` _.isFinite('123')` returns false, and so does Number.isFinite.

Using Chrome Version 50.0.2661.75 beta (64-bit)

**Comment by mashaalmemon** [comment]
@jdalton, @brandoncarl, did such a function every get added to lodash? It would be handy.

**Comment by gajus** [comment]
> @jdalton, @brandoncarl, did such a function every get added to lodash? It would be handy.

It has not. However, use the thumbs up on the issue to bring attention to this feature.

**Comment by shtse8** [comment]
Any updates on isNumeric()? I need this method very much. it's appreciated if lodash can have this method.

**Comment by amenadiel** [comment]
I believe `_.isNumeric` should check if a given input is a numbe, or a number casted as a string. Which means a string for which `Number(x)` is not NaN.

Something like 

```js
function isNumeric (x) {
  return ((typeof x === 'number' || typeof x === 'string') && !isNaN(Number(x)));
}
```

**Comment by ephetic** [comment]
This seems like a good candidate for a mixin.

**Comment by fjc0k** [comment]
I think `isNumeric` is a useful function for Vue prop validators:

```js
import { isNumeric } from 'lodash'

export default {
  props: {
    speed: {
      type: [Number, String],
      default: 0,
      validator: isNumeric
   }
  }
}
```

**Comment by yamsellem** [comment]
Not sure what has changed since, but, with lodash 4.11.2, `_.isFinite('123')` returns `false`.

**Comment by jdalton** [comment]
@yamsellem 
> Not sure what has changed since, but, with lodash 4.11.2, `_.isFinite('123')` returns `false`.

That's the expected behavior and has been that way since v3 (2015).

**Comment by kaminskypavel** [comment]
```
const isNumeric = (value: any) => {
  return isNumber(value) || (!isEmpty(value) && !isNaN(value));
};
```

gracefully handles empty string ('') and booleans

**Comment by buzzware** [comment]
This seems like a good idea to me, but what I'm often really trying to achieve is to convert a string that may or may not be a number, to a number, but if it really isn't then to null.
A nice way to achieve this would be for toFinite to accept a default value that defaulted to 0 for the current value ie:
_.toFinite('1.2') => 1.2
_.toFinite('') => 0
_.toFinite('',null) => null
_.toFinite('hello',null) => null

**Comment by MaffooBristol** [comment]
After combining loads of these together my personal solution is as follows:

```
import _isNumber from 'lodash/isNumber';
import _isEmpty from 'lodash/isEmpty';
import _isNaN from 'lodash/isNaN';

export default (value) => {
  return _isNumber(value) || (!_isEmpty(value) && !_isNaN(parseFloat(value)));
};
```

<details>
  <summary>isNumeric.test.js</summary>

```
import isNumeric from '../isNumeric';

describe('isNumeric', () => {
  it('1', () => {
    expect(
      isNumeric(123)
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('2', () => {
    expect(
      isNumeric(-123)
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('3', () => {
    expect(
      isNumeric(+123)
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('4', () => {
    expect(
      isNumeric('123')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('5', () => {
    expect(
      isNumeric('-123')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('6', () => {
    expect(
      isNumeric('+123')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('7', () => {
    expect(
      isNumeric('.123')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('8', () => {
    expect(
      isNumeric('-.123')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('9', () => {
    expect(
      isNumeric('0.123')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('10', () => {
    expect(
      isNumeric('-0.123')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('11', () => {
    expect(
      isNumeric('1e100')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('12', () => {
    expect(
      isNumeric('1e-100')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('13', () => {
    expect(
      isNumeric('-1e-100')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('14', () => {
    expect(
      isNumeric(Infinity)
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('15', () => {
    expect(
      isNumeric(-Infinity)
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('16', () => {
    expect(
      isNumeric('abc')
    ).toBe(false);
  });
});
describe('isNumeric', () => {
  it('17', () => {
    expect(
      isNumeric('10%')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('18', () => {
    expect(
      isNumeric('#10')
    ).toBe(false);
  });
});
describe('isNumeric', () => {
  it('19', () => {
    expect(
      isNumeric('2^10')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('20', () => {
    expect(
      isNumeric('2!')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('21', () => {
    expect(
      isNumeric('(10)')
    ).toBe(false);
  });
});
describe('isNumeric', () => {
  it('22', () => {
    expect(
      isNumeric('10px')
    ).toBe(true);
  });
});
describe('isNumeric', () => {
  it('23', () => {
    expect(
      isNumeric('*')
    ).toBe(false);
  });
});
describe('isNumeric', () => {
  it('24', () => {
    expect(
      isNumeric('')
    ).toBe(false);
  });
});
describe('isNumeric', () => {
  it('25', () => {
    expect(
      isNumeric(true)
    ).toBe(false);
  });
});
describe('isNumeric', () => {
  it('26', () => {
    expect(
      isNumeric(false)
    ).toBe(false);
  });
});
describe('isNumeric', () => {
  it('27', () => {
    expect(
      isNumeric([])
    ).toBe(false);
  });
});
describe('isNumeric', () => {
  it('28', () => {
    expect(
      isNumeric(function () {})
    ).toBe(false);
  });
});
describe('isNumeric', () => {
  it('29', () => {
    expect(
      isNumeric({})
    ).toBe(false);
  });
});
describe('isNumeric', () => {
  it('30', () => {
    expect(
      isNumeric(undefined)
    ).toBe(false);
  });
});
describe('isNumeric', () => {
  it('31', () => {
    expect(
      isNumeric(null)
    ).toBe(false);
  });
});


```
</details>

Of course the way you may want it to work may differ. For example should percentages work? Should brackets work?

My takeaway from it is that if you were to try and take a given value, put it through `parseFloat()` and times it by two, would it still come out with a number? Works for my use case at least!

**Comment by charescape** [comment]
```js
import _isNaN from 'lodash/isNaN';
import _isFinite from 'lodash/isFinite';

function isNumeric (value) {
  return !_isNaN(parseFloat(value)) && _isFinite(value);
}
```

**Comment by Thatkookooguy** [comment]
My solution. seemed to work just fine:
```javascript
_.mixin({
  isNumericString(str) {
    return `${ +str }` === str;
  }
});
```

**Comment by wallace-sf** [comment]
> ```js
> import _isNaN from 'lodash/isNaN';
> import _isFinite from 'lodash/isFinite';
> 
> function isNumeric (value) {
>   return !_isNaN(parseFloat(value)) && _isFinite(value);
> }
> ```

The function doesn't pass the tests mentioned above.
