### ISSUE TITLE
Lots of unused files

### ISSUE THREAD

**Issue by kevinsawicki** [lodash/lodash#1149]
It looks like lodash includes lots of files in the npm distro that don't appear to be used.

```sh
$ npm install lodash
lodash@3.7.0 node_modules/lodash
$ find node_modules/lodash | wc -l
     413
```

It doesn't look like these files are required by `index.js` so I was just wondering why they are distributed?

**Comment by megawac** [comment]
So people can require individual modules e.g.

```js
var sortBy = require('lodash/array/sortBy')
```

**Comment by kevinsawicki** [comment]
> So people can require individual modules

Oh okay, is there a version of lodash without these then? When you just want to use the whole thing.

**Comment by AaronO** [comment]
@kevinsawicki I think adding a `.npmignore` should solve the problem. Here's a small experiment :

```
❯ npm i lodash@3.7.0
   ......
❯ find ./node_modules/lodash | wc -l
     134

❯ find ./node_modules/lodash | grep -v vendor | wc -l
      34

❯ find ./node_modules/lodash | grep -v vendor | grep -v test | wc -l
      22

❯ find ./node_modules/lodash | grep -v vendor | grep -v test | grep -v perf | grep -v doc | wc -l
      14
```

Ignoring the `vendor`,`test`,`perf`,`doc` folders should remove a lot of files that are only used for dev.

The `.npmignore` could blacklist a few other files as a further improvement. The only two files that should be shipped are `package.json` and `lodash.src.js`

**Comment by jdalton** [comment]
Thanks but the [lodash package](https://github.com/lodash/lodash/tree/npm) contains exactly what it needs to contain.

**Comment by AaronO** [comment]
@jdalton Sorry about that false positive ... It must seem stupid.

I was experiencing that issue because running `npm i lodash@3.7.0` was hitting `npm`'s local cache in `~/.npm` which resulted in having a copy of the `master` branch in `node_modules` rather than the `npm` package. I wasn't aware `npm` did that ... I thought it was pulling from the `npm` registry, hence the confusion ... (I think they started caching when they made packages "immutable").

Anyway, sorry about that. Thanks for `lodash` !

**Comment by jdalton** [comment]
@kevinsawicki
> Oh okay, is there a version of lodash without these then? When you just want to use the whole thing.

By default, `require('lodash')` just loads the single monolithic `index.js` so if you're bundling that's all you get. If you choose to cherry-pick your methods, `require('lodash/array/chunk')`, then only what you use will be bundled. So you get the best of both worlds in one 172kb lodash.tgz package.

@AaronO
> Sorry about that false positive ... It must seem stupid.

No worries, I've not heard of npm caching the `master` branch before. I donno what that's about.

**Comment by kevinsawicki** [comment]
> So you get the best of both worlds in one 172kb lodash.tgz package.

I understand you are trying to provide flexibility, but having to install 400+ files at 2MB when all you are using is one file that is 400k does not seem like the best of both worlds.

**Comment by StreetStrider** [comment]
I'm kinda agree with @kevinsawicki. For those, who need modularity there're `lodash-node` and one-function packages, like `lodash.merge`. Now, when I'm starting project I'm choosing one of two alternatives: to start with small set of one-function modules (which is the most of cases) or to pull the whole `lodash` (if I'm absolutely sure there will be extensive use of goodies). But (if second) I'll be never using `lodash` package in modular way: `require('lodash/object/merge')`, I'd rather just `var merge = require('lodash').merge;` which will hit the cache any time after first.
Anyway, I'm cool with the current state of things.

**Comment by jdalton** [comment]
@kevinsawicki 
> I understand you are trying to provide flexibility, but having to install 400+ files at 2MB when all you are using is one file that is 400k does not seem like the best of both worlds.

It absolutely is the best of both worlds. Disk space is cheap, npm@3 will be auto-deduping, and allowing devs to cherry-pick gives them a way to create reduced builds for the client-side or third-party integration where it matters.

**Comment by kevinsawicki** [comment]
> Disk space is cheap

In the context of shipping a desktop application that bundles lodash (or libraries that depend on lodash) it can really add up.

[Atom](https://atom.io) currently ships with lodash and lodash-node (via two different libraries that depend on it, xmlbuilder and babel-core) totaling 919 files and 4MB.

That means 10% of Atom's install is just lodash and it slows down the installs and updates since uncompressing 900+ files on a Windows machine with a spinning disk is still sluggish.

**Comment by jdalton** [comment]
I'm not going to sacrifice functionality for thousands of projects that depend on lodash for a desktop install case. Maybe Atom could minify deps or compress packages.

**Comment by kevinsawicki** [comment]
> I'm not going to sacrifice functionality for thousands of projects that depend on lodash for a desktop install case. 

Fair enough, I appreciate the discussion.

> Maybe Atom could minify deps, compress packages, or perform some other build optimization

Yup, we are doing this now.

**Comment by jdalton** [comment]
> Yup, we are doing this now.

What's the end result of that?

**Comment by kevinsawicki** [comment]
> What's the end result of that?

There are several recent changes that have helped shed thousands of files and megabytes of data from the app bundle:

* Whitelists for files that libraries commonly forget to include in their `.npmignore` file like `.travis.yml`, test files and fixtures, etc. https://github.com/atom/atom/pull/6447 and https://github.com/atom/atom/pull/6395
* Not using large libraries when there are other straightforward ways to do the same things https://github.com/atom/notifications/pull/54
* Aggressively de-duping and aligning dependencies of our own libraries https://github.com/atom/atom/pull/5489

**Comment by jdalton** [comment]
It would be neat if part of your build optimization you analyzed the `require.cache` and only include files from it in the build bundle.

**Comment by jdalton** [comment]
> Atom currently ships with lodash and lodash-node (via two different libraries that depend on it, xmlbuilder and babel-core) totaling 919 files and 4MB.

If you upgrade your xmlbuilder dep I believe it's switched from `lodash-node` to `lodash`.
