### ISSUE TITLE
Variable is assigned to itself

### ISSUE THREAD

**Issue by immohuneke** [lodash/lodash#1153]
The code inspection in WebStorm complains:

file .../lodash/lodash.js
Variable is assigned to itself at line 752

The line in question reads
```js
var ...,
    preventExtensions = isNative(Object.preventExtensions = Object.preventExtensions) && preventExtensions, ...
```
I'm a relative newcomer to JavaScript and don't pretend to understand everything that's going on here, but it does look like a potential bug, particularly when compared to the initializer for `getOwnPropertySymbols` three lines earlier.

**Comment by jdalton** [comment]
That actually is a typo. It should read:
```js
preventExtensions = isNative(preventExtensions = Object.preventExtensions) && preventExtensions
```

**Comment by StreetStrider** [comment]
Wow, @immohuneke, good job.

**Comment by immohuneke** [comment]
Thanks!
Actually, I was wondering why it wasn't written like this:preventExtensions = isNative(Object.preventExtensions) && Object.preventExtensions
I'm still starting out learning Javascript, so there's probably some subtlety here that escapes me.

Best regards,Immo 


     On Tuesday, 21 April 2015, 16:45, Strider <notifications@github.com> wrote:
   

 Wow, @immohuneke, good job.—
