### ISSUE TITLE
waitUntil

### ISSUE THREAD

**Issue by ccorcos** [lodash/lodash#1159]
I'm working on some animations right now and I came up with a function that i think could be useful in lodash. Its very similar to throttle, but relies on an async callback rather than a setTimeout. Here's what I have written so far and it seems to work. I'm curious if you have any thoughts or suggestions.

```js
// func gets a callback function as the first argument.
var waitUntil = function(func) {
  var busy, callback, next;
  // the func is busy, queue up the call, and call only the
  // most recent one when func is no longer busy
  next = null;
  busy = false;

  // the async callback passed to func
  callback = function() {
    var f;
    // call the next func that was queued up
    // or set the func as no longer busy
    if (next) {
      f = next;
      next = null;
      return f();
    } else {
      return busy = false;
    }
  };
  return function() {
    var args;
    args = _.toArray(arguments);
    // queue up the next function call
    if (busy) {
      return next = function() {
        return func.apply(null, [callback].concat(args));
      };
    } else {
      busy = true;
      return func.apply(null, [callback].concat(args));
    }
  };
};
```

**Comment by jdalton** [comment]
Can you provide a small usage example.

**Comment by ccorcos** [comment]
Suppose we have some animation or process (like a server call) that we don't want to be interrupted. 

```coffee
transitionTo = waitUntil (done, page) ->
  # animate to the page and call done when animation is complete
```

Then suppose we have a bunch of UI components that execute page transitions. It would look terribly if they all animated on top of each other and clobbered each other. So using `waitUntil` allows one animation to complete before the next one starts. Much like `_.throttle`, there are some configuration options we could use. For example, the default may be to simply forget any function call while the func is busy (maybe one page transition causes another page transition to be unreachable). Or we can queue up all function calls (maybe none of the actions prevents the other actions from happening). Or we can just queue up the latest action (this make sense if you have something like a tab/nav bar with animations between pages).

**Comment by jdalton** [comment]
Thank you @ccorcos! I think `aync` is better suited for something like this.

**Comment by ccorcos** [comment]
Did you forget a link?

**Comment by jdalton** [comment]
Oh sorry. See [async](https://www.npmjs.com/package/async).
