### ISSUE TITLE
SyntaxError: Unexpected token when evoked within function definition

### ISSUE THREAD

**Issue by kyv** [lodash/lodash#1161]
I have the following code (slightly modified from the nodegit examples);
https://gist.github.com/kyv/9b74c03a1a70e5e65770

The calls to Lodash on lines 21 and 27 work as expected. 

Line 25 fails with the error:

> SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by jdalton** [comment]
I don't think this is a lodash issue as `_.first` is pretty straight forward.

**Comment by kyv** [comment]
Yes it is straight forward. Well if you could provide a hint I would appreciate it. Hope I'm not just dumb.

**Comment by dak0rn** [comment]
@kyv I'd suggest changing line 25 to

```javascript
.done(function() {
```

That `_.first( diffList )` doesn't look right there.
Doesn't seem to be a lodash issue.

**Comment by kyv** [comment]
Ok thanks. That comes directly from the nodegit example, but I suppose you must be correct. Maybe I should be asking there. Thanks for your time.
