### ISSUE TITLE
_.intersection does not work on DOMTokenList

### ISSUE THREAD

**Issue by TheRealJoeLinux** [lodash/lodash#1163]
I was trying to get an element's classList to see if it had one of a particular list of classes:
```javascript
var classes = e.currentTarget.classList;
var findClasses = ["foo-1", "foo-2", "bar-7", "foobar-8"];
```
However, while `findClasses` is definitely an instance of `Array`, `classes` is an instance of `DOMTokenList`. This object is iterable, but it is not strictly an instance of `Array`. So I get this:

```javascript
> classes
["foo-1", "col", "activated"]
> _.intersection(classes, findClasses)
[]
> _.intersection(["foo-1", "col", "activated"], findClasses)
["foo-1"]
```

In [lodash.src.js:5297](https://github.com/lodash/lodash/blob/master/lodash.src.js#L5297), the variable `classes` will fail the `isArray()` test, since `Array.isArray(classes)` is `false`. Any other function that depends on `isArray()` will also likely exhibit the same behavior, though I didn't try to find any others.

The same code works in Underscore, since Underscore doesn't seem to use `Array.isArray` as a prerequisite for iterating through the objects.

**Comment by jdalton** [comment]
You're seeing a side effect of Underscore not being consistent with its checks. For example it does restrict for `_.difference` and `_.union`.

**Comment by TheRealJoeLinux** [comment]
Ah, I see about Underscore. That's a tad disconcerting. Anyway... I still believe that's a bug. I think an optimal solution is duck typing to accept an iterable object (in this case, `DOMTokenList`), rather than expect an object to pass the `Array.isArray()` test. I guess I'm thinking of something similar to `isObjectLike`, where you would have a function `isArrayLike` rather than strictly `isArray`. The ECMAScript6 draft has Iterators, so something like this might be worth thinking about.

**Comment by TheRealJoeLinux** [comment]
What about something like this?

```javascript
function isArrayLike(obj) {
  // simple cases
  if (!obj) return false;
  if (Array.isArray(obj)) return true;

  // does it quack?
  if (obj.hasOwnProperty("length")
    && obj.length > 0
    && obj.__proto__.hasOwnProperty("forEach")) {
      return true;
  }
  return false;
}
```

I'm not saying this is the definite solution (I haven't run any tests), but some thinking along these lines?

**Comment by jdalton** [comment]
It's on my todo for the evening to look into loosening the check. We have helper functions internally that can be used to allow array-likes.
