### ISSUE TITLE
Thoughts on a throttling function which leverages requestAnimationFrame?

### ISSUE THREAD

**Issue by MeoMix** [lodash/lodash#1165]
Hey,

I'm currently using a mixin which looks like:

    //  Inspired by: https://gist.github.com/danro/7846358
    //  Leverage requestAnimationFrame for throttling function calls instead of setTimeout for better perf.
    framerateThrottle: function(callback) {
        var wait, args, context;
        return function() {
            if (wait) return;
            wait = true;
            args = arguments;
            context = this;
            requestAnimationFrame(function() {
                wait = false;
                callback.apply(context, args);
            });
        };
    }

Alternatively, I could be using the default throttle function with a timing of 1000/60.

I use this mixin for throttling scroll event handlers and it seems to work very well. Just curious if there's any interest in supporting an animation performant throttle in the future?

**Comment by jdalton** [comment]
Hi @MeoMix! I think this is  a bit too specialized for lodash.
