### ISSUE TITLE
(doc/changelog) _.findWhere (alias -> self contained) migration was not documented

### ISSUE THREAD

**Issue by fredgalvao** [lodash/lodash#1166]
Until **3.0** (I believe) `_.findWhere` was an alias to `_.find`, and thus accepted all 3 kinds of predicate that the later accepts: `(Function|Object|string)`. Recently, it became a self contained method, and only works in the `Object` predicate option.
This split/migration was **not** mentioned on the changelog and breaks any code calling `_.findWhere` with a predicate other than `Object`.

Although I'm kinda late to the party, adding a mention to it now might still help some people who are waiting for whatever reason to migrate to 3.x.

As a matter of curiousity, what's the motivation for spliting generalist methods and its aliases into specialist ones, other than eventual performance optimizations and less edge case intersections?

**Comment by jdalton** [comment]
It was done to align more closely with `_.where` and `_.pluck` in that they are specialized to source objects or property names. This also prevents unintended usage like `_.pluck` with an `iteratee`. I'll add a changelog note (it'll show up on the next bump).
