### ISSUE TITLE
Firefox Array.map builtin 3x faster than _.map

### ISSUE THREAD

**Issue by emosesSfdc** [lodash/lodash#1170]
See this jsperf result: http://jsperf.com/native-vs-array-js-vs-underscore/96.  Lodash greatly outperforms the map builtin on Chrome, but Firefox's map is nearly 3x as fast as lodash's.  Can lodash be made to fall back to native map on Firefox?

**Comment by jdalton** [comment]
Micro-benchmark is micro. I've tested this quite a bit and lodash will be on par with FF built-in in several cases, you've found one where it's not. Using the built-in carries with it baggage around sparse arrays so we won't likely adopt because the cost of branching and guarding for issues is too high.

**Comment by jdalton** [comment]
Here's [an example](http://jsperf.com/native-vs-array-js-vs-underscore/98#chart=bar) of a benchmark showing on par performance. Engines love numeric operations often branching out to other types shows dramatic differences.

**Comment by emosesSfdc** [comment]
Fair enough, thanks for looking.

On Tue, Apr 28, 2015 at 11:31 AM, John-David Dalton <
notifications@github.com> wrote:

> Here's an example
> <http://jsperf.com/native-vs-array-js-vs-underscore/98#chart=bar> of a
> benchmark showing on par performance. Engines love numeric operations often
> branching out to other types shows dramatic differences.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lodash/lodash/issues/1170#issuecomment-97163848>.
>



-- 
Evan Moses
emoses@salesforce.com

**Comment by eugene-moroz** [comment]
Hey guys!
Is it possible to recover somehow those links on jsperf.com? I'd really like to understand what was the difference.
Thanks

**Comment by jdalton** [comment]
Hi @eugene-moroz!

I don't believe so. For benchmarking now-a-days you can checkout [esbench](https://esbench.com/).
