### ISSUE TITLE
_.toArray of arguments 'array-like' object is incorrect when new properties are injected into the object.

### ISSUE THREAD

**Issue by UnbounDev** [lodash/lodash#1171]
You can repo the issue by running the following snippet:

```
var foo = function () {
      arguments[1] = true;
      console.log(arguments); //=> { '0': 'bar', '1': true }
      console.log(_.toArray(arguments)); //=> [ 'bar' ]

      for (var k in arguments) {
        console.log(k, arguments[k]);
      }//=> 0 bar / 1 true
    };

foo("bar");
```

On digging a bit it seems as though the objects base `length` property is calculated to be `1`, which causes only one item to be pushed into the new array in the `arrayCopy` function.

**Comment by jdalton** [comment]
Yap, array-likes like `arguments` objects get their array-like-ness from their `length`. This is by design.

**Comment by UnbounDev** [comment]
My mistake - thanks for the clarification!
