### ISSUE TITLE
_.isBlank(str)

### ISSUE THREAD

**Issue by dwoldrich** [lodash/lodash#1174]
Hi!  Thanks for helping me put bread on my family's table!

Anyhow, I found the isBlank() semantics pretty useful back in the day when doing Java coding with Commons Lang.  I looked for it today in lodash and when I found it wasn't there I rolled my own with `_.isString()` and `_.trim()` and `length > 0`.

Here's the function I'm thinking about:

https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/StringUtils.html#isBlank%28java.lang.CharSequence%29

Perhaps our take on `_.isBlank()` could fallback to `_.isEmpty()` semantics for non-String types.

**Comment by jdalton** [comment]
I think you're on the right track with `_.trim`. Usually you want to cleanup your data and then perform checks. In this case if you `_.trim` your result would end up being falsey for blank strings anyways.

**Comment by dwoldrich** [comment]
Oh yeah, empty strings are falsey!  I always hated that about strings, and now it's finally useful.  ;)  

So, just return _.isString(s) ? !!_.trim(s) : _.isEmpty(s);
