### ISSUE TITLE
3.7.0's npm package lacks most of the source

### ISSUE THREAD

**Issue by nevir** [lodash/lodash#1175]
Might want to yank the `3.7.0` npm release, it only contains the following:

```
doc/
perf/
test/
vendor/
CONTRIBUTING.md
README.md
component.json
lodash.js
lodash.src.js
LICENSE.txt
bower.json
lodash.min.js
package.json
test/
```

**Comment by nevir** [comment]
Err, or I have a screwed up npm cache?

http://registry.npmjs.org/lodash/-/lodash-3.7.0.tgz looks correct, but when I `npm install lodash@3.7.0` I get what I listed above.

**Comment by jdalton** [comment]
Ya not sure about that. The package looks fine http://registry.npmjs.org/lodash/-/lodash-3.7.0.tgz.

**Comment by nevir** [comment]
Yeah, it's all happy for me after a `npm cache clean`

**Comment by jdalton** [comment]
What version of npm are you using?

**Comment by nevir** [comment]
Oh man.  `npm`: `1.4.28`, `node`: `v0.10.38` (installed via `nvm`)

**Comment by jdalton** [comment]
Thanks! I'm aware of some issues in older versions so ensuring the latest and greatest possible supported npm version should help.

**Comment by nevir** [comment]
Yeah, hopefully the great cache refactor of `2.x` helps alleviate a lot of the weirdness :)
