### ISSUE TITLE
_.startCase inconsistencies when two consecutive capitals

### ISSUE THREAD

**Issue by amiramw** [lodash/lodash#1176]
startCase has some inconsistent behavior with consecutive capital letters.
```javascript
_.startCase("ABcde")
"A Bcde"
_.startCase("ABCde")
"AB Cde"
```
Should such strings be splitted at all?

**Comment by jdalton** [comment]
Because `_.startCase` is a casing method it splits compound words up and then applies casing rules, similar to camelCase, kebabCase, and others. This also allows casing methods to be used to transform and undo transforms correctly. It sees `ABcde` as a compound `A` and `Bcde` while `ABCde` is seen as `AB` and `Cde`.

**Comment by amiramw** [comment]
Thanks!
Actually I get different result that what's in the original post for when only the first two letters are upper (they are considered as a word).
```javascript
_.startCase("ABcde")
"AB Cde"
```
Why is it different than the general case?
Another question, why the B stays in upper case?
I'm using version 3.1.0.

**Comment by jdalton** [comment]
> Why is it different than the general case?

It's seen as "AB" and "Cde" just as "XMLHttp" is seem as "XML" and "Http".

> Another question, why the B stays in upper case?

Start case is about capitalization not lowering of other characters

**Comment by amiramw** [comment]
> It's seen as "AB" and "Cde" just as "XMLHttp" is seem as "XML" and "Http".

But if you have "XHttp" it produces "XH" and "Ttp" and not "X" and "Http". Like when it are only two upper case characters they are treated as a word and when there are three it depends on what comes after.

**Comment by jdalton** [comment]
```js
_.words('XHttp')
// => ["X", "Http"]
```

**Comment by amiramw** [comment]
For me it gives this:
```javascript 
_.words("XHttp")
// => ["XH", "ttp"]
```

**Comment by jdalton** [comment]
Well then, you're not on the latest.
