### ISSUE TITLE
Will baseSortBy() always use the native Array.prototype.sort()?

### ISSUE THREAD

**Issue by adamshaylor** [lodash/lodash#1178]
Some people consider the use of [code point sorting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) in `Array.prototype.sort()` to be one of the “bad parts” of JavaScript:

```javascript
['12', '1', '2'].sort() // => ['1', '12', '2']
```

I’m actually counting on this behavior. I’d like to use lodash’s `_.sortBy()` in a chain of other transformations. It looks like lodash uses `Array.prototype.sort()` [under the hood](https://github.com/lodash/lodash/blob/b75041173c9aa35343fb4be44d7a28a8acae03f3/lodash.js#L2671). Can you, the core contributors, think of a reason you might ever to swap out the native sort method for your own? If so, is there a way to use something like `_.thru()` to pipe a lodash-ified array through `Array.prototype.sort()`?

**Comment by jdalton** [comment]
We ensure our sort is stable which is something the spec gives engines wiggle room on. The chaining sugar has the array `sort` baked-in `_(array).sort(...).value()`.

**Comment by adamshaylor** [comment]
Thank you!
