### ISSUE TITLE
Changelog header is confusing

### ISSUE THREAD

**Issue by AgentME** [lodash/lodash#1179]
I check the [Changelog](https://github.com/lodash/lodash/wiki/Changelog) semi-frequently and maybe I'm particularly dim, but this message that gets put inside the top of every new release and retroactively removed from the previous releases always throws me for several loops:

>See the [release notes](https://github.com/lodash/lodash/releases) for overviews & highlights of this & other releases.
>Use [lodash-migrate](https://www.npmjs.com/package/lodash-migrate) to help migrate older lodash code to the latest release.

The release notes link doesn't lead to any useful description about the changes. The changelog page that I'm already on is much more useful! On many occasions I've seen a new lodash version, gone to the changelog page, followed the link to the release notes as I assumed it was trying to tell me the release notes is where the canonical information on releases is, and then gotten lost trying to navigate through github to find the notes on the new release.

The lodash-migrate link is strange because it makes me worry about backwards incompatibilities and wonder why lodash has suddenly stopped following semver, but it doesn't look like the 3.8.0 release actually adds any backwards incompatibilities. I think to myself that every release probably mentions lodash-migrate, but then I see that the previous couple releases don't mention it, so then I double check to make sure that the latest release really doesn't add any backwards incompatibilities. I start to wonder whether or not my memory of seeing that note on the 3.7.0 release in the past is right and if I'm being gaslighted.

If that header was above the releases list in the changelog rather than always being made part of the latest release, it would be a little better I think.

**Comment by jdalton** [comment]
Your opinion is noted. Thanks.
