### ISSUE TITLE
#with

### ISSUE THREAD

**Issue by bcherny** [lodash/lodash#1181]
```js
/*
  mutable
*/

let a = []
a.push(1)
a.splice(a.indexOf(1), 1)

/*
  immutable (today)
*/

let a = []
let b = _.clone(a).push(1)
let c = _.without(b, 1)

/*
  immutable (proposed)
*/

let a = []
let b = _.with(a, 1)
let c = _.without(b, 1)
```

**Comment by jdalton** [comment]
`push` returns the new length not the value so your `b` result is incorrect.
You can currently do:
```js
_([1, 2]).slice().push(3).value();
// => [1, 2, 3]
```

**Comment by bcherny** [comment]
that's right, but the idea is the same. `without` already exists, and it would be nice to have a symmetrical method for the inverse operation.

`without` can also be expressed as a `splice` + `indexOf`, but having a single convenience method is really nice for working with immutable data. why not have the same for `slice` + `push`?

**Comment by megawac** [comment]
@bcherny why not

```js
a = [];
b = a.concat(1);
c = _.without(b, 1)
```

**Comment by bcherny** [comment]
@megawac good call!

**Comment by bcherny** [comment]
however, the syntax is still asymmetrical:

```js
let a = [1,2,3]
let b = _.without(a, 3)
let c = a.concat(4)

// would be nice:
let d = _.with(a, 4)
```

another downside i just realized after implementing #with as a mixin in my project, is since `with` is a reserved word, partial imports (`import { with } from 'lodash'`) are not possible.

**Comment by StreetStrider** [comment]
Interesting that thing like `with` is not a `concat` or `push`. It is an opposite for `without`. How `without` works? It returns array excluding provided elements. It does nothing if element is not present. So, in opposite must be function which adds elements only if one not present (does nothing if element already present). `concat` and `push` add elements unconditionally.
