### ISSUE TITLE
call-n-times

### ISSUE THREAD

**Issue by mightyiam** [lodash/lodash#1183]
May [call-n-times](https://github.com/PolicyStat/call-n-times) be a suitable addition to lodash?
It was [mentioned in the popular DailyJS](http://dailyjs.com/2015/01/13/testharness-call-modern/).

Also, I welcome any comments on it.

**Comment by mightyiam** [comment]
It was [mentioned in the popular DailyJS](http://dailyjs.com/2015/01/13/testharness-call-modern/).

**Comment by mightyiam** [comment]
Also, I welcome any comments on it.

**Comment by d10** [comment]
We have [`_.times`](https://lodash.com/docs#times).

**Comment by mightyiam** [comment]
You're right. I text searched the API docs for the words 'call' and 'repeat' and didn't find `_.times`.

The terms are 'invoke' and 'iterate'.
