### ISSUE TITLE
Support ES6 Map/Set/WeakMap/WeakSet in _.toArray

### ISSUE THREAD

**Issue by brianmhunt** [lodash/lodash#1184]
There is no builtin, widely supported way to create an array from ES6 [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) entities (values or keys). Eventually [Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) will solve this problem, but it is not as widely supported as the data structures.

It would be great if `_.toArray` were able to fill this gap – not just for `Map` and `Set`, but for any [iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols). Both `Set` and `Map` have `.forEach` properties, and `Map` also has `values` and `keys`. All of these conform to the iterator protocol.

:beers:

**Comment by jdalton** [comment]
Hi @brianmhunt! See #858 and #737.

**Comment by brianmhunt** [comment]
Thanks - sorry I missed those. Cheers
