### ISSUE TITLE
Min/Max decimal error, not giving correct

### ISSUE THREAD

**Issue by ilijamt** [lodash/lodash#1185]
I tried this in the browser and in node.js and it's the same issue.

Here is how to reproduce.

```
> var a = ["985.00", "1097.45", "921.88", "1071.21", "922.99", "1053.96", "1073.85", "941.66", "1051.22", "943.08", "1100.63", "1094.04", "1059.44", "1094.95", "924.97", "1115.18", "1035.40", "1115.28", "965.06", "1002.72"];
> _.min(a)
"1002.72"
> _.max(a)
"985.00"
```

**Comment by d10** [comment]
This is because you are comparing strings. When comparing strings, the character’s code unit is compared, not the number. Try `_.min(array, Number)`.
