### ISSUE TITLE
_.merge() does not deep merge nodejs Url's

### ISSUE THREAD

**Issue by koresar** [lodash/lodash#1188]
node.js v0.10.38
lodash v3.8.0
```js
var merge = require('lodash/object/merge');
var url = require('url');

var result = merge({}, { url: url.parse("http://host.com:81/path") }, { url: { b: 2 } });
console.log(result); // prints: { url: { b: 2 } }
// expected result.url.host, port, etc, AND the b property.
```

Whereas this works as expected:
```js
var result = merge({}, url.parse("http://host.com:81/path"), { b: 2 });
```

**Comment by koresar** [comment]
Ok. I see. It does not suppose to deep merge. Is there a way to deep merge objects using lodash?

**Comment by koresar** [comment]
Now I see. I got confused by the docs.

This is docs for `_.defaults`.
```
Arguments
object (Object): The destination object.
[sources] (…Object): The source objects.
```

I though merge is similar and can accept any number of arguments. Although, `_.defaults` does not accept more than arguments. The second must be an array.

This line is kind of confusing. 
```
[sources] (…Object): The source objects.
```

Shouldn't it be?
```
[sources] (Object[]): The source objects.
```

**Comment by koresar** [comment]
@jdalton Closing this one. Would you mind answering the question above? Thank you.

**Comment by koresar** [comment]
Of, crap! Even the conclusion above is wrong. :(
I'm going to kill myself.

**Comment by koresar** [comment]
Then the last question. How to deep merge three objects?

**Comment by jdalton** [comment]
Hold up, hold up. Don't do anything rash. I'll reply in a bit (wrapping up my work day).

**Comment by koresar** [comment]
Too late. I have just published a new module. :)
https://www.npmjs.com/package/supermixer

**Comment by jdalton** [comment]
The issue with the object from `url.parse()` is that it's not a plain object so when you try to merge a plain object onto it the plain object wins and paves the plain. You can customize the merge behavior here with the `customizer` param or convert `url.parse()` to a plain object via `_.toPlainObject(url.parse(...))`.

**Comment by koresar** [comment]
:+1: Works. Thanks!
