### ISSUE TITLE
 a bug of `intersection` lodash@3.8.0

### ISSUE THREAD

**Issue by gordomium** [lodash/lodash#1189]
```javascript
_.intersection.apply(null, [[1, 3, 4]]);
```
- expected: [1, 3, 4]
- got: []

This bug is in lodash@3.8.0 and lodash@3.5.0 or other versions(?) on **NodeJS**.
But it works as expected in lodash@3.6.0 on **Browser**.

**Comment by jdalton** [comment]
This actually the intended behavior because the intersection of `[1, 3, 4]` and nothing is nothing, `[]`.

**Comment by gordomium** [comment]
But it works as i expected in `underscore`. And all my colleagues agree my thought...  I think most of users will agree it.

**Comment by jdalton** [comment]
Underscore is incorrect/inconsistent here. It will return empty for `_.intersection([1, 3, 4], undefined)` or `_.intersection([1, 3, 4], null)`.
