### ISSUE TITLE
Permutations

### ISSUE THREAD

**Issue by pistacchio** [lodash/lodash#1191]
I think an useful addition to the library would be a "permutations" function that given n arrays, returns an array of all the possible permutations of their values. Eg:

```js
_.permutations([0, 1], ['a', 'b']) => [[0, 'a'], [0, 'b'], [1, 'a'], [1, 'b']];
```

**Comment by d10** [comment]
That seems really specialised, and also probably very slow. I don’t think it’s well suited for lodash’s core.

**Comment by jdalton** [comment]
I think @d10 is right. This method would be great as mixin :)

**Comment by thomaswrenn** [comment]
👍

**Comment by daedalus28** [comment]
:+1:

**Comment by lowrey** [comment]
:+1:

**Comment by jdalton** [comment]
You gotta give it [reactions](https://help.github.com/articles/about-discussions-in-issues-and-pull-requests/) y'all or they aren't counted.

**Comment by electic** [comment]
+1
