### ISSUE TITLE
a bug of  _.memoize

### ISSUE THREAD

**Issue by dd1994** [lodash/lodash#1192]
```javascript
var _ = require('lodash');
var i = 0;

func = function(n) {
  i = i + 1;
  return n + 1;
}

memoized = _.memoize(func);

console.log(memoized(1)); // => 2
console.log(memoized(1)); // => 2
console.log(memoized("1")); // => 2

console.log(i); // => 1
```

`memoized("1")` return 2, but it should return `11` , because `func("1")` return `11`
I'm not sure, becasuse I'm a newcomer to javascript...

**Comment by jdalton** [comment]
Hi @dd1994! The the string `"1"` and the number `1` are see as equivalent to memoized functions by default because they are used as keys in the memoize cache, so coerced to strings. You can customize the key values by passing a `resolver` function or changing the `_.memoize.Cache` backing.

**Comment by dd1994** [comment]
thank you @jdalton
