### ISSUE TITLE
TypeError: Class constructors cannot be invoked without 'new'

### ISSUE THREAD

**Issue by tusharmath** [lodash/lodash#1193]
Using ES6 classes, the native bound function works.

```javascript
class A {}
var ABound = A.bind(null, 1, 2, 3)
var a = new ABound()
```
Where as using lodash bind function, it doesn't work.
```javascript
class A {}
var ABound = _.bind(A, null, 1, 2, 3)
var a = new ABound()
```
Following exception is thrown 
```stack
TypeError: Class constructors cannot be invoked without 'new'
    at new A (repl:1:23)
    at /Users/tusharmathur/Documents/Projects/ioc/node_modules/lodash/index.js:3230:27
    at new wrapper (/Users/tusharmathur/Documents/Projects/ioc/node_modules/lodash/index.js:3653:19)
    at repl:1:5
```

Looking at the code it seems obvious why, but is it the expected behaviour?

**Comment by jdalton** [comment]
Hmm I can't seem repro this in io.js 2.0. I also can't repro this in babel generated code or when deleting `Function.prototype.bind` and loading in es5-shim.

**Comment by tusharmath** [comment]
Did you try the io.js attempt with REPL? Can you create a `.js` file and then run it using `iojs example.js`?

**Comment by jdalton** [comment]
> Did you try the io.js attempt with REPL? Can you create a `.js` file and then run it using `iojs example.js`? 

That did it! Ok, so I can repro this with `_.bind` or when using es5-shim after deleting `Function.prototype.bind` which tells me it's not a problem with lodash as shims will hit this too. The generated babel code still doesn't error either.

This looks like a limitation of the `Class` implementation. I'll bring it up to my TC39 rep.

**Comment by tusharmath** [comment]
Can you reopen the issue, untill its resolved?

**Comment by jdalton** [comment]
Naw, if it breaks shims then I see no reason to reopen it.

**Comment by jdalton** [comment]
Increasing vis, @bterlson, @thejameskyle, @sebmck, @ljharb.

Just a heads up. It looks like built-in class constructors don't play well with shims/non-built-in bind implementations. It has an issue with `Ctor.apply(...)` bit.
```js
    function createCtorWrapper(Ctor) {
      return function() {
        var thisBinding = baseCreate(Ctor.prototype),
            result = Ctor.apply(thisBinding, arguments);

        // Mimic the constructor's `return` behavior.
        // See https://es5.github.io/#x13.2.2 for more details.
        return isObject(result) ? result : thisBinding;
      };
    }
```

I could solve this by detecting if built-in bind exists and using it and caching the result when it's needed. I'm avoiding using built-in bind for `_.bind` results because of unavoidable inconsistencies between built-in and shim code. Note that babel generated code works because it doesn't impose the class constructor restriction ( Class constructors cannot be invoked without 'new').

**Comment by jridgewell** [comment]
> Note that babel generated code works because it doesn't impose the class constructor restriction (Class constructors cannot be invoked without 'new').

Babel includes `_classCallCheck`, but that uses simple `instanceof`. See this [repl example](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=function%20createCtorWrapper(Ctor)%20%7B%0A%20%20return%20function()%20%7B%0A%20%20%20%20var%20thisBinding%20%3D%20Object.create(Ctor.prototype)%2C%0A%20%20%20%20%20%20%20%20result%20%3D%20Ctor.apply(thisBinding%2C%20arguments)%3B%0A%0A%20%20%20%20return%20result%20%26%26%20typeof%20result%20%3D%3D%20'object'%20%3F%20result%20%3A%20thisBinding%3B%0A%20%20%7D%3B%0A%7D%0A%0Aclass%20A%20%7B%0A%20%20test()%20%7B%20console.log('test')%3B%20%7D%0A%7D%0A%0AcreateCtorWrapper(A)().test())

**Comment by sebmck** [comment]
@jridgewell That's the only way to get anywhere close with ES5 semantics.

**Comment by sebmck** [comment]
@jdalton Looks like you're SOL. There are a few ES6 semantics that you can't shim and this is one of them.

**Comment by jdalton** [comment]
Hmm the build-in `bind` technique I described doesn't work either when called with `.apply`, `boundCtor.apply(...)`.

**Comment by sebmck** [comment]
Yeah, `apply` and `call` on a class will call the `[[Call]]` internal method which is set to throw for class constructors:

 [9.2.1 [[Call]] ( thisArgument, argumentsList)](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-ecmascript-function-objects-call-thisargument-argumentslist).

> 2. If F’s [[FunctionKind]] internal slot is "classConstructor", throw a TypeError exception.

**Comment by jdalton** [comment]
I guess I could do a gross like switch statement on the `arguments.length` and say like after 10 attempt apply which just reduces the likelihood of hitting it but doesn't remove it completely. Also did I say super gross.

**Comment by jdalton** [comment]
Sooo gross, Brian, I'm so blaming you. Look what you've done! LOL :)

**Comment by jdalton** [comment]
This works:
```js
function createCtorWrapper(Ctor) {
  return function() {
    var args = arguments;
    switch (args.length) {
      case 0: return new Ctor;
      case 1: return new Ctor(args[0]);
      case 2: return new Ctor(args[0], args[1]);
      case 3: return new Ctor(args[0], args[1], args[2]);
      case 4: return new Ctor(args[0], args[1], args[2], args[3]);
    }
    var thisBinding = baseCreate(Ctor.prototype),
        result = Ctor.apply(thisBinding, arguments);

    return isObject(result) ? result : thisBinding;
  };
}
```

**Comment by jridgewell** [comment]
I know this is super slow, you could support all cases:

```javascript
function createCtorWrapper(Ctor) {
  return function() {
    var args = arguments;
    switch (args.length) {
      case 0: return new Ctor;
      case 1: return new Ctor(args[0]);
      case 2: return new Ctor(args[0], args[1]);
      case 3: return new Ctor(args[0], args[1], args[2]);
      case 4: return new Ctor(args[0], args[1], args[2], args[3]);
    }
    if (nativeBind) return new (nativeBind.apply(Ctor, [null].concat(args)));
    // These environments don't have classes anyways...
    var thisBinding = baseCreate(Ctor.prototype),
        result = Ctor.apply(thisBinding, args);

    return isObject(result) ? result : thisBinding;
  };
}
```

**Comment by sebmck** [comment]
@jridgewell That wont work. See my [previous comment](https://github.com/lodash/lodash/issues/1193#issuecomment-100279429), you can't `apply` a class.

**Comment by ljharb** [comment]
fwiw, I think this would not affect shims, because every environment that implements `class` constructors would also have a native `bind`.

**Comment by jdalton** [comment]
Depends on if third party code does something odd. lodash will attempt to use some ES5/6 built-ins if they haven't been tampered with. Classic example is old Prototype paving `Array#reduce`.

**Comment by jdalton** [comment]
@jridgewell
> I know this is super slow, you could support all cases:

That's a neat option but then throws even more complexity into the mix, if `nativeBind` is unavailable for some reason. I'll start the limit at 4 args and if there's problems expand from there.

**Comment by sankargorthi** [comment]
time to remove the `invalid` tag?

**Comment by errorx666** [comment]
Maybe this could help:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construct
