### ISSUE TITLE
Is it possible or any plan to make lodash some compiling language?

### ISSUE THREAD

**Issue by supnate** [lodash/lodash#1194]
Hi,

lodash is really a perfect handy utilities collection for javascript, thank you guys for providing it. But in a real project, not all functions are needed instead usually a small part. So the code size will be a problem for a small or medium browser side application. If it could pre-process project source code and just import those used functions, I believe the code size will significantly reduced. Say that it's just like Babel which translates ES6 features to ES5.

Do you think it's a possible direction? Thanks!

Best,
Nate Wang

**Comment by jdalton** [comment]
Hi @supnate! lodash is modular so you can just cherry-pick the methods you want, like `require('lodash/array/chunk')`, and browserify/webpack will only bundle the things you use. There's also [per method packages](https://www.npmjs.com/browse/keyword/lodash-modularized) available.

There's also packages [find-used-lodash](https://www.npmjs.com/package/find-used-lodash) to find the methods you've used or [lodash-modularize](https://www.npmjs.com/package/lodash-modularize) to generate a build of the methods you've used.
