### ISSUE TITLE
Helper method to return a function that calls the first argument with the current context

### ISSUE THREAD

**Issue by tusharmath** [lodash/lodash#1196]
Is there a way to achieve the following behaviour

```js
_.thisCall = function (func) {
  return func(this)
}
```

Why?
```js
//Power Functions
var power2 = function (val){
  return Math.pow(val, 2)
}

var power3 = function (val){
  return Math.pow(val, 2)
}

var power4 = function (val){
  return Math.pow(val, 5)
}

// List of items
var items = [1, 2, 3, 4, 5]

//To raise them to power 2
_.invoke(items, _.thisCall, power2)

//To raise them to power 3
_.invoke(items, _.thisCall, power3) // and so on ...


```

**Comment by jdalton** [comment]
Can you write the long form, plain js, of what you're wanting.

**Comment by StreetStrider** [comment]
@tusharmath, what about arguments?
```js
function thisCall (fn)
{
  var args = slice.call(arguments, 1);
  return fn.apply(null, [ this ].concat(args));
}
```

And, by the way, #821 looks like a more mature version of this idea.

**Comment by tusharmath** [comment]
@StreetStrider Yes i missed that.

**Comment by jdalton** [comment]
Your usage looks like `_.map`; `_.mapitems, power3)`.

**Comment by StreetStrider** [comment]
@tusharmath 
> mixing the context and arguments is consfusing

Yes and not. It depends on which function is. `this` context isn't enough in many cases, arguments are also required. Anyway, hi-order approach like `demethodize` is much more useful. You can `demethodize` function first, then transform it with stuff like `ary`, `rearg` and `partial`. Using `this` brings more restrictions than advantages, pure arguments is better.
