### ISSUE TITLE
isNative issues

### ISSUE THREAD

**Issue by zloirock** [lodash/lodash#1197]
1. [`lodash` uses `Object#toString` as template for `isNative`](https://gist.github.com/jdalton/5e34d890105aca44399f#file-isnative-js-L32-L43) assuming that is native function. But ES6 changed [`Object#toString` logic for support `Symbol.toStringTag`](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-object.prototype.tostring). [`core-js`](https://github.com/zloirock/core-js) from first versions [adds polyfill for this logic](https://goo.gl/Dh1LwI) and replaces `Object#toString`. `_.isNative` works wrong for **all** native functions with `core-js` / `babel` and some other libraries:
```js
require('core-js');
require('lodash').isNative(Object);   // => false
require('lodash').isNative(Function); // => false
require('lodash').isNative(isNaN);    // => false
```
I will add fallback for `lodash` in next version `core-js`, but `lodash` should use native function whose logic shouldn't be changed in ES6+.
2. `lodash` [uses `isNative` for detect `Set`, `WeakMap`,  some object methods](https://github.com/lodash/lodash/blob/master/lodash.js#L740-L754) - but why? In most polyfills, **native** methods wrapped for correct work by latest spec and, with this check, will not work with `lodash`. Related #981. Better use correct feature detection.

**Comment by jdalton** [comment]
Yap, I picked `Object.prototype.toString` because it's used heavily in other libs and not likely to be mucked with as it's on the `Object.prototype`. I didn't think about those mucking with it using `defineProperty`. Any recommendations on a method you wouldn't likely touch?

**Comment by zloirock** [comment]
> I didn't think about those mucking with it using `defineProperty`.

Wrapping `Object.prototype.toString` not requires native `defineProperty` - it's already non-enumerable.
```js
Object.prototype.toString = 42;
for(var key in {})console.log('key: ' + key); // nothing
```
[+ DontEnum bug](https://developer.mozilla.org/en-US/docs/ECMAScript_DontEnum_attribute#JScript_DontEnum_Bug).
> Any recommendations on a method you wouldn't likely touch?

Should be in ES3, not constructor, not `Object.prototype` method - someone wrapped them for store non-enum properties or something else, not `Array.prototype` method - [most of them replaced in some shims](https://github.com/kangax/compat-table/issues/531), not `Math` method - [also for better accuracy](https://github.com/kangax/compat-table/issues/392). Should be as simple as possible. Possible, global `isNaN` or `isFinite`, their ES6 versions - static `Number` methods, but not sure.

**Comment by jdalton** [comment]
There's bugs in at least some engines where overwriting a built-in does make it enumerable. So there's that. I think you've got the right idea will making its `toString` source match the built-in. I'll kick this around a bit.

Are you working with @ljharb on your shims?

**Comment by zloirock** [comment]
> There's bugs in at least some engines where overwriting a built-in does make it enumerable.

Yep, but in old engines :)

About `es6-shim` - it's not adds  `@@toStringTag` logic and not wrapped `Object#toString`, but second issue similar:
```js
require('es6-shim');
require('lodash').isNative(Object.keys); // => false
require('lodash').isNative(Object.getPrototypeOf); // => false
require('lodash').isNative(Object.preventExtensions); // => false
```

**Comment by jdalton** [comment]
They gotta make sure when they wrap they look like the built-in :)
I like using an `Object.prototype` method as reference because `Object.prototype` is seen as off-limits to many devs. I'll kick around using `constructor` or `toLocaleString`.

**Comment by zloirock** [comment]
> They gotta make sure when they wrap they look like the built-in :)

Instead of `Object#toString` - it's impossible - current `isNative` uses `Function#toString.call(method)`. Using `.bind` for fake native source will break `#name` property.

> I'll kick around using constructor or toLocaleString.

I remember one library that wrapped `Object#toLocaleString`. I think, possible use `hasOwnProperty` - for replace it you'd be crazy :)

**Comment by jdalton** [comment]
Ah ya good old `hasOwnProperty`. I'll make that change then. I'm fine with `isNative` not being 100% bullet proof I just want to put a good effort in.
