### ISSUE TITLE
intersection behaviour unintuitive and documentation unclear

### ISSUE THREAD

**Issue by ravenscar** [lodash/lodash#1199]
I have read #1147 and #1189 regarding the changed behaviour of `intersection()` when applied to a single list.

I am not sure it is sensible behaviour to assume that the caller wanted an empty list silently inserted for comparison.

The documentation does not make this clear: [*"Creates an array of unique values in all provided arrays..."*](https://lodash.com/docs#intersection) certainly the inserted list should not be considered a provided array, as it was not provided. From reading the documentation I would expect the returned array to be equal to a `uniq()` of the single input array.

I understand the argument that from a semantic point of view the word intersection implies `2..n` cardinality, however if this is the case it would be more useful to throw an error than assume that the caller desired an empty array returned - which is almost certainly not what the caller expected.

**Comment by jdalton** [comment]
I'm open to documentation tweaks if you'd like to open a PR.

**Comment by jdalton** [comment]
If you could point to other language implementations that would be helpful as well.

**Comment by ravenscar** [comment]
Clojure docs seem to suggest intersection of one set will return the elements:
https://clojuredocs.org/clojure.set/intersection

Python:

>a = {1,2,3}
>b = {3,4,5}
>a.intersection(b);
>\> {3}    
>a.intersection();
>\> {1, 2, 3}    

Ruby:
>arrays = [[1,2,3],[2,3,4],[3,4,5]]
>arrays.inject(:&)
>\> [3]
>arrays = [[1,2,3]]
>arrays.inject(:&)
>\> [1,2,3]

Java: most recommendations seem to be to use Collection.retainAll(), which works similar to the Ruby example.

Matlab/Octave/Common lisp throw an error with the standard Intersect operator, SQL should give a syntax error.

I also found this link which may be relevant: https://proofwiki.org/wiki/Intersection_of_Singleton

**Comment by jdalton** [comment]
That means it would return a shallow clone with any duolicates?

**Comment by ravenscar** [comment]
That could result in inconsistent behaviour if the single input list has duplicates, e.g.:

    intersection([1,1],[1,1]) => [1]
    intersection([1,1]) => [1,1] // should be [1]

Looking at the code it seems that the args length check could be changed from:

    if (argsLength < 2) {
        return result;
    }

to

    if (argsLength < 1) {
        return result;
    }
and it should work fine.

If it needs to be compared with anything, perhaps it could be compared with itself, e.g.

    if (argsLength === 1) {
        args.push(args[0]);
    }
