### ISSUE TITLE
difference not working for short arrays

### ISSUE THREAD

**Issue by ilyavolodin** [lodash/lodash#1203]
Using lodash version 3.8.0 and 3.1.0 the following code:
```js
_.difference([1], [1,2]);
```
returns an empty array.
```js
_.difference([1,3], [2]);
```
returns `[1,3]` but skips 2
and
```js
_.difference([1,3], [2,4]);
```
also returns `[1,3]`

**Comment by jridgewell** [comment]
`_.difference` returns the values in the first array that are not present in any following array.

```javascript
// What are the values in [1] that are not in [1, 2]
_.difference([1], [1,2]); // => []

// What are the values in [1, 3] that are not in [2]
_.difference([1,3], [2]); // => [1, 3]
```

**Comment by ilyavolodin** [comment]
Ahh.. I was thinking that it returns difference between two arrays. Sorry for the false alarm.

**Comment by StreetStrider** [comment]
@ilyavolodin, maybe u'r looking for [_.xor](https://lodash.com/docs#xor)? It is a symmetric difference.
