### ISSUE TITLE
_.each failing in ie8 when adding a comma to an object

### ISSUE THREAD

**Issue by Vadorequest** [lodash/lodash#1204]
Let's say we have this:

```js
_settingsValidator = [
            {
                key: 'container',
            },
            {
                key: 'debug',
            },
            {
                key: 'layout',
            },
            {
                key: 'token',
            },// THIS COMMA IS THE SOURCE OF THE ISSUE.
        ];

_.each(_settingsValidator, function(validator, key){
console.log(validator)
// Will output the fourth first object as it is in the _settingsValidator 
// Then, will output "undefined" because of the comma, it believes somehow it is an empty object.
});
```

This happens only in Internet Explorer 8, works fine in IE9+. Didn't try in IE7.

**Comment by jdalton** [comment]
IE8 treats that as sparse array and lodash treats holes in sparse arrays as `undefined`. Linters can help with your trailing commas.

**Comment by Vadorequest** [comment]
Sorry but, what is linters?

**Comment by jdalton** [comment]
JS [linters](http://en.wikipedia.org/wiki/Lint_(software)) like [jshint](https://github.com/jshint/jshint), [eslint](https://github.com/eslint/eslint).

**Comment by dak0rn** [comment]
A linter is a tool that checks your code for common pitfalls and improvable style.

Checkout JSLint or JSHint for more details.

**Comment by jdalton** [comment]
This is a no crockford zone.

**Comment by Vadorequest** [comment]
Okay, thanks. :) DIdn't know the word.

2015-05-13 18:01 GMT+02:00 Daniel Koch <notifications@github.com>:

> A linter is a tool that checks your code for common pitfalls and
> improvable style.
>
> Checkout JSLint or JSHint for more details.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lodash/lodash/issues/1204#issuecomment-101724797>.
>



-- 
Cordialement,

M. Ambroise Dhenain.

**Comment by dak0rn** [comment]
@jdalton I am very sorry for that :D
