### ISSUE TITLE
findWhere should fail early

### ISSUE THREAD

**Issue by trashhalo** [lodash/lodash#1205]
I've been working to upgrade my companies lodash from 2.4.1 to 3.x. One of the things that has frustrated the upgrade is findWhere used to be an alias of find and now unlike find only takes objects. 

But findWhere still will gladly accept a function. It hands it to baseMatches sees that it doesn't have length and returns a constant true. So places in our code base that were calling findWhere with a function are always getting back the first element of the collection. 

I think findWhere should error out in the event of using it like find. Having it act like it still accepts a function and even returning s single element. It pushes the failure down stream making it harder to pinpoint what went wrong.

**Comment by jdalton** [comment]
Hi @trashhalo! `_.findWhere` was never documented to accept a callback.

**Comment by trashhalo** [comment]
![screenshot_2015-05-13_19-40-44](https://cloud.githubusercontent.com/assets/177491/7623472/a7acb950-f9a8-11e4-8a17-80fdf818b48b.png)
@jdalton is that not documenting you can pass a function to findWhere?

**Comment by jdalton** [comment]
You're technically correct. My favorite type of correctness! But still the intent was not to use a callback. I still win! To ease your upgrade pains to a find+replaceall of `findWhere` -> `find`.

**Comment by megawac** [comment]
Personally I would of preferred the removal of `pluck` and `findWhere` in v3 but perhaps in another timeline

**Comment by jdalton** [comment]
I was all for it, then kept them for Underscore compat because they weren't hurting anything.
But yes, in v4, lets remove them (I'll add it to the roadmap).

**Comment by jridgewell** [comment]
I'd actually support removing `findWhere` from underscore, too. It's not needed since we got `_.iteratee`.

What would `pluck` be replaced with?

**Comment by megawac** [comment]
_.map

**Comment by jridgewell** [comment]
Man, I need to read better. I was thinking of `pick`. :facepalm:
