### ISSUE TITLE
Provide guidance on how to build the documentation

### ISSUE THREAD

**Issue by kevinburkeshyp** [lodash/lodash#1206]
When I clone github.com/lodash/lodash, I expect to find a `docs/index.html` file or similar which you can open and the docs are there, or a README which explains how to build and view the docs locally. A good example of this is `three.js` which has an index.html, which you can open and all of the links work even when you don't have an internet connection.

There is a doc/README.md, which looks like it's meant to be parsed by a machine more than a person. I also checked the CONTRIBUTING.md file and the main README file; I didn't see any information on how to build the docs.

**Comment by jdalton** [comment]
The markdown is what's generated. Here's [a gist](https://gist.github.com/jdalton/938ea49ab3919f1c046c) I use with various commands (docs building included).

**Comment by jdalton** [comment]
If you're looking for offline docs check out devdocs.io
