### ISSUE TITLE
_.find function's .matchesProperty shorthand producing unusual behavior when undefined is passed as the value

### ISSUE THREAD

**Issue by NeutralAngel** [lodash/lodash#1208]
The ```_.find``` function is supposed to return undefined if an element is not matched.

However, using the ```_.matchesProperty``` callback shorthand produces unusual behavior when undefined is passed as the value.

If ```_.matchesProperty``` is used directly, the behavior is as expected.

```JavaScript
var family = [{id: 0, name: 'Nathan'}, {id: 1, name: 'Julianne'}, {id: 2, name: 'Alex'}];
_.find(family, _.matchesProperty('id', 2)); //=> Object {id: 2, name: "Alex"}
_.find(family, _.matchesProperty('id', undefined)); //=> undefined
```

However, using the shorthand produces the wrong result.

```JavaScript
_.find(family, 'id', 2); //=> Object {id: 2, name: "Alex"}
_.find(family, 'id', undefined); //=> Object {id: 1, name: "Julianne"}
```

My preliminary look seems to indicate that the issue comes from the final ternary return statement in ```baseCallback(func, thisArg, argCount)```.

https://github.com/lodash/lodash/blob/3.8.0/lodash.js#L1733-L1735

If the ternary is removed and ```return baseMatchesProperty(func, thisArg);``` is allowed for cases where ```thisArg``` is ```undefined```, it seems that the issue goes away and all the test cases still pass.

**Comment by jdalton** [comment]
Correct. This is a limitation of our shorthand. If you're wanting to perform a match for `undefined` you'll have to use the long for `_.matchesProperty('id', undefined)` or try the `matches` shorthand `{ 'id': undefined }`.
