### ISSUE TITLE
Exception thrown when `flow` and `partial` are used together

### ISSUE THREAD

**Issue by bjohn465** [lodash/lodash#1210]
If `flow` and `partial` are included on their own (e.g. `require( "lodash/function/flow" )`) and are used together, an exception is thrown.

I have created [a repository](https://github.com/bjohn465/lodash-flow-bug/) with [code that demonstrates the issue](https://github.com/bjohn465/lodash-flow-bug/blob/22230b0baa3ce0a42ce51c1843a723c8a6375a37/index.js).

The exception thrown when running this test code is:
```
TypeError: undefined is not a function
    at C:\code\lodash-flow-bug\node_modules\lodash\internal\createFlow.js:51:90
```

When lodash is included with `require( "lodash" )` and `_.partial` is used with `_.flow`, an exception is not thrown.

**Comment by jdalton** [comment]
Thanks! This will be addressed on the lodash-cli side (patched locally).
