### ISSUE TITLE
collection being added in map function in 3.8.0?

### ISSUE THREAD

**Issue by ilazarte** [lodash/lodash#1212]
http://jsfiddle.net/ilazarte/j14f26rd/1/

Maybe I'm missing something, but shouldn't the resulting collection produce what expected produces?

**Comment by StreetStrider** [comment]
@ilazarte, try change
```js
_.partialRight(_.set, "funny", true);
// to:
_.partial(_.set, _, "funny", true);
```

**Comment by ilazarte** [comment]
That works great, but did I misunderstand something about how partialRight is supposed to work, or are you always supposed to use placeholders?

**Comment by StreetStrider** [comment]
@ilazarte, you understand `partialRight` correctly, but you did not take into account that predicate which passed to functions like `map` are supplied not with `value` argument, but with three arguments: `value`, `key`, `collection`. When you use `partialRight` you just append to this three arguments yours. So you have `_.set(value, key, collection, "funny", true)`. That is common misunderstanding of predicates (here, in LoDash and in JS in general). `partial` with placeholders solves this particular problem (and a couple of others): you can fix some arguments and leave others intact.

Take a look at this:
```js
['a', 'b', 'c'].forEach(console.log);
// would return:
a 0 [ 'a', 'b', 'c' ]
b 1 [ 'a', 'b', 'c' ]
c 2 [ 'a', 'b', 'c' ]
```

**Comment by ilazarte** [comment]
I see.  For some reason my clojure experience told me that I could expect a new arguments context if you well.  It could be I never got those right either!  I tend to use lamdbas in clojure more than partial application since the lambda syntax is very succinct.

So long as it is working as intended I'm happy closing this and learning a little about partials today.  Thanks!

**Comment by StreetStrider** [comment]
@ilazarte, no problem. Take a look at auto-currying functions as well. Here, in [LoDash](https://lodash.com/docs#curry), and in libraries, like [Ramda](http://ramdajs.com/).

**Comment by jdalton** [comment]
@ilazarte You may also be interested in [_.ary](https://lodash.com/docs#ary), [_.rearg](https://lodash.com/docs#rearg), & [lodash-fp](https://www.npmjs.com/package/lodash-fp).
