### ISSUE TITLE
_.get returns undefined when nested value is NULL

### ISSUE THREAD

**Issue by serendipitic** [lodash/lodash#1216]
This could be a result of #1136:

`_.get({ a: { b: null }}, 'a.b')` returns `undefined` instead of `NULL`.

In the example `a.b` is a valid path but instead of returning its value, `undefined` is returned even though the property exists.

**Comment by serendipitic** [comment]
thanks for the fast reaction!

**Comment by jdalton** [comment]
You caught me in the middle of version bumping :)
