### ISSUE TITLE
NPM Error - bufferClone.js

### ISSUE THREAD

**Issue by gfranko** [lodash/lodash#1218]
It looks like a new version of `bufferClone.js` introduces a reference error, since the `root` variable is `undefined`.  [Here](https://github.com/lodash/lodash/blob/npm/internal/bufferClone.js#L5) is where the problem is.  Thank you for taking the time to look at this!

**Comment by pthrasher** [comment]
+1 I can confirm this is actually broken in a bunch of places going from 3.8.0 -> 3.9.0

root is undefined when requiring a specific file using browserify. eg:

```javascript
var isFunction = require('lodash/lang/isFunction');

// the above causes the following error to be thrown:
// Uncaught ReferenceError: root is not defined
```

The error is thrown by this line in the isFunction source file:

```javascript
var Uint8Array = getNative(root, 'Uint8Array');
```

https://github.com/lodash/lodash/commit/9ea15bec224de93cb066d3840a66cebe57817b01#diff-1085cf573b069bf06a01e2d930a9e8d7R17

**Comment by jdalton** [comment]
Interesting. It seems `root` exists in Node which is why our unit tests passed for this.

**Comment by pthrasher** [comment]
Ah, yeah... That makes sense. No worries, I've rolled back for now. Thanks for making such great stuff. :+1: :smile: 

I was about to submit a PR, but I noticed this was an issue in a bunch of places, and I wasn't quite sure what the best solution to the problem was.

**Comment by longlho** [comment]
:+1:

**Comment by jdalton** [comment]
It's a lodash-cli issue. We replace `root` with `global` but missed some. The fact that `root` is valid is doubly tricky. Maybe Browserify should support `root` as an alias of `global` too.

**Comment by koulmomo** [comment]
the issue happens with `webpack` too in case you want to go the route of getting module bundlers to support the `root` alias

**Comment by jdalton** [comment]
I've have this fixed this evening. Sorry about that. I'll also look into integrating `root` checks to avoid this in the future.

**Comment by gfranko** [comment]
@jdalton Thanks for being so awesome

**Comment by koulmomo** [comment]
what @gfranko said. 
Thanks for all the hard work on an super useful and performant package.

**Comment by mridgway** [comment]
Could 3.9.0 be unpublished for now? We have hundreds of projects we would have to lock down to fix our pipeline.

**Comment by jdalton** [comment]
Bumped to v3.9.1 for `lodash` and `lodash-compat` packages.

**Comment by mridgway** [comment]
:+1: thanks @jdalton. We're back in business.

**Comment by gfranko** [comment]
:heart:  Thanks @jdalton !

**Comment by flipstewart** [comment]
🙌thanks for the quick fix @jdalton!

**Comment by jdalton** [comment]
I've poisoned the global `root` alias [in unit tests](https://github.com/lodash/lodash/commit/7010f158234c6f94bf983b9fd1357563fa9b2d45) to ensure this doesn't happen again.
