### ISSUE TITLE
What's the official way to check if the object is wrapped in _(..)?

### ISSUE THREAD

**Issue by dominykas** [lodash/lodash#1220]
I'm trying to allow passing in an array or a lodash wrapped instance into a function. If a lodash instance is passed in - I need to unwrap it (`.value()`), but how do I check if it really is a lodash instance?

I'm looking for something like `_.isLodash`.. or alternatively, I wouldn't care about it if the following were true, but I'm not sure that's a legit wish :)
```js
var wrapped = _([ 1, 2, 3 ]);

console.log(_.toArray(wrapped)); // [ 1, 2, 3 ] 
```

I'm somewhat reluctant to call `.value()` just because it's a function that exists on an object...

**Comment by d10** [comment]
You can use `object instanceof _`.

**Comment by dominykas** [comment]
It might not be an `instanceof _`, if the lodash that constructed the chain is from another `node_modules`...

**Comment by d10** [comment]
You could also just try `_(object).value()`, as `_(object)` would just return `object` if `object` is already a LodashWrapper.

**Comment by davidkpiano** [comment]
Try `something.constructor.name === 'LodashWrapper';`

**Comment by jdalton** [comment]
@davidkpiano 
> Try `something.constructor.name === 'LodashWrapper';`

`Function#name` isn't supported in all modern browsers yet.

@dominykas Internally we duck type off of the `_.has(value, '__chain__')` and `_.has(value, '__wrapped__')` properties.

**Comment by dominykas** [comment]
`Function#name` might also not be present due to minification?

@jdalton any chance of exposing that as a public method?

**Comment by davidkpiano** [comment]
@jdalton Couldn't you also do: `object === _(object);` (*true* if it's a `LodashWrapper` instance), since it returns the exact same object if it's an instance of a `LodashWrapper`?

**Comment by jdalton** [comment]
Yep :)
