### ISSUE TITLE
_.uniq iteratee as comparator

### ISSUE THREAD

**Issue by devlato** [lodash/lodash#1221]
It would be nice if _.uniq could do a deep equality comparison or if iteratee callback could work as custom comparator or if _.uniq can handle a list of properties to compare, because current implementation with single value is ugly & potentially unreliable. 

I.e. if there is some collection: 

```javascript
var data = [{
    "x": 12, 
    "y": "hey",
    "z": "red"
}, {
    "x": 12, 
    "y": "arnold",
    "z": "black"
}, {
    "x": 12, 
    "y": "hey",
    "z": "red"
}]; 
```

With deep equality comparison it could be done like this: 

```
var uniqueData = _.uniq(data); 
console.log(uniqueData);
// {
//     "x": 12, 
//     "y": "hey",
//     "z": "red"
// }, {
//     "x": 12, 
//     "y": "arnold"
//     "z": "black"
// }
```

With comparison callback it can be used that way: 

```javascript
var uniqueData = _.uniq(data, false, funciton(item1, item2) {
    return item1.x == item2.x;
}); 
console.log(uniqueData);
// {
//     "x": 12, 
//     "y": "hey",
//     "z": "red"
// }
```

With property field list it can be done with code like this:
```
var uniqueData = _.uniq(data, false, ["x", "y"]); 
console.log(uniqueData);
// {
//     "x": 12, 
//     "y": "hey",
//     "z": "red"
// }, {
//     "x": 12, 
//     "y": "arnold"
//     "z": "black"
// }
```

**Comment by jdalton** [comment]
Related to #246 for discussion on this. If you're just comparing value `x` you can do that with `_.uniq(array, 'x')`.

**Comment by devlato** [comment]
No, I want to compare by multiple fields, not by single field, did you see my examples?

**Comment by jdalton** [comment]
Well ya from your very last example :P
This looks like something for a mixin.

**Comment by devlato** [comment]
And from the second example, it also allows to compare by multiple fieds :-) 
Mmm, mixin isn't really matches the situation, so if I'll implement this functionality, will it be merged?

**Comment by jdalton** [comment]
> Mmm, mixin isn't really matches the situation, so if I'll implement this functionality, will it be merged?

No, I'm saying it would fit best as a mixin. So you implement it as your own mixin.

**Comment by jdalton** [comment]
I'm adding `_.uniqWith`, `_.differenceWith`, and friends to lodash v4 which accepts a `comparator` function.
```js
_.uniqWith(objects, _.isEqual);
```
