### ISSUE TITLE
_.sortBy not working with non-ASCII characters

### ISSUE THREAD

**Issue by davmoh** [lodash/lodash#1222]
I 've noticed, that _.sortBy function returns wrong result, if strings include non-ascii characters.
Sample:
```js
var items = [{ id: 1, name: 'étest' }, { id: 2, name: 'etest' }, { id: 3, name: 'ùtest' }, { id: 4, name: 'atest' }, { id: 5, name: 'utest' }];
var wrongSortedArr = _.sortBy(items, 'name');
```
Result: `atest, etest, utest, étest, ùtest`.

I 've made custom solution helping with javascript array.sort and localeCompare function.
The result should be: `atest, etest, étest, utest, ùtest`

Is there any option in lodash for sorting objects in array including non-ascii characters?

**Comment by jdalton** [comment]
This is a little outside the functionality of `_.sortBy`. You can `_.deburr` values to get sort of the way there.
