### ISSUE TITLE
Partial arguments for method() aren't documented

### ISSUE THREAD

**Issue by adamboduch** [lodash/lodash#1223]
Unless I'm missing it, I couldn't find any documentation for [method()](https://lodash.com/docs#method) about partially-applying arguments. It let's you do this, and this is a huge win. At least for me anyway - it's not very often that I map method calls *without* arguments.

Even a simple example, I think, would suffice for most folks:
```javascript
_.map('abc', _.method('replace', 'a', 'b')).join('');
```

**Comment by jdalton** [comment]
Oh snao! I could add placeholder support to the method! (ok so that's a separate issue but still rad)

**Comment by adamboduch** [comment]
Awesome, thanks JD.
