### ISSUE TITLE
Be able to control depth of _.isEqual?

### ISSUE THREAD

**Issue by Dashed** [lodash/lodash#1224]
I'm wondering if it's worth to control how deep of a comparison `_.isEqual` performs.

API could be like: `_.isEqual(value, other, [customizer], [thisArg], [depth])`.

So, something like `_.isEqual(value, other, 1)` would do shallow comparison.

**Comment by jdalton** [comment]
I don't think we'll add this. You may be able to hack something together using its `customizer` callback.

**Comment by Parakleta** [comment]
Anyone else coming here looking for a shallow comparison operator I implement it as:

    _.isEqual(value, other, (a,b,k) => (k && (a===b || (a!==a && b!==b))));

This says to use the default behaviour for the root objects (i.e. returns `undefined` if k is `undefined`), but then do a strict comparison (modified to count `NaN` as equal) at the first level (thus preventing further recursion).

**Comment by jdalton** [comment]
In v4 the `_.eq` method is not longer an alias of `_.isEqual` and performs just [SameValueZero](http://ecma-international.org/ecma-262/6.0/#sec-samevaluezero) comparisons.
