### ISSUE TITLE
Undocumented 2.4.1 -> 3.9.0 changes to _.mapValues with string arguments

### ISSUE THREAD

**Issue by nbyarnell** [lodash/lodash#1226]
In lodash 3.9.0, _.mapValues converts string arguments passed in as the object parameter to character arrays. _.mapValues calls baseForOwn, which initiates a chain of calls down to createBaseFor which itself calls toObject() on the object parameter passed to _.mapValues(). toObject explicitly checks for string arguments and converts them into character arrays. (Sorry if this is overly verbose, I'm just documenting what I'm seeing).

In lodash 2.4.1, no such conversion happens. _.mapValues calls forOwn, which checks (on line 2097) if the argument passed in is of type string, and simply returns the string in that case.

I guess my question is, why was this change made? Also, as far as I can tell this change hasn't been documented anywhere.

Here are two jsbins demonstrating the change in behavior I'm talking about:
2.4.1 - http://jsbin.com/bafelarari/1/edit
3.9.0 - http://jsbin.com/derenasici/1/edit

**Comment by jdalton** [comment]
Converting strings to objects is consistent with ES6 built-in behavior of things like `Object.keys` and `Object.assign`. I'll add a doc note.
