### ISSUE TITLE
Minified version on NPM

### ISSUE THREAD

**Issue by qraynaud** [lodash/lodash#1227]
This was probably asked before but I couldn't find the bug related to this so I'm asking anyway, just in case. If this was already discussed somewhere, a *simple reply with a link to the proper topic* would be fine by me.

With the growing number of people using NPM to retrieve their node modules as well as their front modules of which I am part of (I dislike bower and would like an NPM plugin to better handle front packages instead), I believe lodash needs a proper way to get files for the browser from NPM. Some examples might be the number of angular related stuff poping on NPM (including the official lib with its 144 178 downloads per month which is respectful for a latecomer in the available installation processes of this lib).

I don't claim to know how it should be done, maybe by publishing packages with a `front-` prefix containing the files you would get with bower… Another way would be to add a `browser/` folder with those in the existing packages. I'm sure there are other means to achieve this.

What are your thoughts on this?

Thanks a lot for your hard work until now (I LOVE lodash)!

**Comment by jdalton** [comment]
Hi @qraynaud! There are lots of ways to handle client side bundling. For now I think we'll keep it as is and let the dev choose how they should bundle lodash, minifying it or bundling it as they see fit.

**Comment by qraynaud** [comment]
@jdalton: yeah, I know you can easily bundle lodash using lodash-cli. I'm talking about a pre bundled package on NPM for browsers. I believe there isn't any right now. Or am I missing something?

**Comment by jdalton** [comment]
I meant handled by browserify/webpack/uglifyjs/closure-compiler w/ or w/o source-maps or whatever your to-production process involves. There doesn't need to be a package for this. You shouldn't be relying on third-party code to provide their own minified source for your production enviro.

**Comment by qraynaud** [comment]
Ok, never mind. I agree that your recommendation is better for prod envs but it seems a lot to add a build of lodash (& angular, & …) in dev for every bit of code we need. We use sourcemaps to code and thus need minified files whatsoever.

Thanks for your time & input though.

**Comment by jdalton** [comment]
Add dev builds in dev then use your minifiers to bundle preference for the rest. It's pretty easy with things like browserify/webpack/uglify-js.

**Comment by qraynaud** [comment]
1/ There is no dev build for browsers available on NPM either
2/ I use minified versions in dev because I had too much build if not prod outages caused by a different dev env than prod. I try my hardest to work in an ISO environment.

**Comment by jdalton** [comment]
> 1/ There is no dev build for browsers available on NPM either

There is. The `index.js` in both `lodash` and `lodash-compat` are monolithic builds with UMD for browsers.

> 2/ I use minified versions in dev because I had too much build if not prod outages caused by a different dev env than prod.

Your situation seems pretty unique then.

**Comment by tamlyn** [comment]
> The index.js in both lodash and lodash-compat packages are monolithic builds with UMD for browsers.

Aha! I didn't know that. Could that be added to the readme? e.g. below `require` example, add:

In browser:

    <script src="node_modules/lodash/index.js"></script>
