### ISSUE TITLE
Is there a functionality to flatten/deflatten an object?

### ISSUE THREAD

**Issue by moatazelmasry2** [lodash/lodash#1228]
Hi there,

I have the following object/array of objects:
Object1: 

```json
{ id: 2,
    balance: 130,
    'Issue :  { 
         'id': 1,
         'currency': 'EUR'
   }
}```

Object2: 
```json
{ id: 2,
    balance: 130,
    'Issue.id': 1,
    'Issue.currency': 'EUR'
}
```
Is there a way to 'deflatten' object1 into object2 and flatten object2 into object1?

Thanks

**Comment by jdalton** [comment]
Hi @moatazelmasry2! We currently don't have a flatten for objects but I'm keeping an eye on the demand. Related to #1180.

**Comment by moatazelmasry2** [comment]
Hi John,

Would the two way implementation of something that might be interesting for lodash? I need probably to implement this functionality anyway...

**Comment by jdalton** [comment]
Check out [flat](https://www.npmjs.com/package/flat#flatten-original-options).

**Comment by damianobarbati** [comment]
interesting one, somethings like the new native https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat but for objects.
