### ISSUE TITLE
Ability to retrieve current key in customizer functions?

### ISSUE THREAD

**Issue by DylanPiercey** [lodash/lodash#1232]
It would be handy to be able to use the customizer functions of "extend, assign, merge, defaults, etc." and retrieve each object being merged as arguments followed by the current key being merged.

Currently it looks like this:
```javascript
var defaults = _.partialRight(_.assign, function(value1, value2) {
  // I have no idea what attribute is being assigned currently.
  return _.isUndefined(value2) ? value1 : value2;
});

defaults({ 'user': 'barney' ,  _forced: 'hi' }, { 'age': 36, _forced: 'changed!' }, { 'user': 'fred' });
// → { 'user': 'barney', 'age': 36, '_forced': 'changed!' }
```

What it would look like:
```javascript
var defaults = _.partialRight(_.assign, function(value1, value2, value3, key) {
  if (key[0] === "_") { // Force private vars.
     return value1;
  }

  return _.isUndefined(value2) && _.isUndefined(value3) ? value1 : value3 || value2
});

defaults({ 'user': 'barney' ,  _forced: 'hi' }, { 'age': 36 }, { 'user': 'fred' });
// → { 'user': 'barney', '_forced': 'hi', 'age': 36 }
```

The actual thing i'm trying to accomplish with this is to be able to send out nested "change" events using a recursive merge on a backbone model, so if you guys know of a way to do this then that would help me out.

The examples not perfect but I think it illustrates the point.
What do you guys think? Or is this already achievable?

**Comment by jdalton** [comment]
The `customizer` currently receives `customizer(value, source[key], key, object, source)`

**Comment by rill-js** [comment]
Awesome, thanks - didn't see it it the docs but could be blind.

**Comment by DylanPiercey** [comment]
Awesome thanks, didn't see it in the docs but could be blind.

**Comment by renewooller** [comment]
Note:  for the full path, not just the key, you can use lodash-deep variants. EG https://github.com/marklagendijk/lodash-deep

**Comment by ViggoV** [comment]
I've been looking for this information in the docs as well, without luck..
