### ISSUE TITLE
Provide param API for Object/Array, behave like jQuery.param

### ISSUE THREAD

**Issue by Xuhao** [lodash/lodash#1233]
As most libraries not support nested query object when apply an ajax request by it, like jQuery.ajax or Superagent. so it's make sense to provide `param` to serialize object(suport nested) to query string in lodash for non-jQuery uesr.

Currently I create my own `param` helper accord with this [answer](http://stackoverflow.com/a/1714899). But it will be better if I can handy use it by lodash.

**Comment by jdalton** [comment]
Hi @Xuhao! I think this is a bit to specialized for lodash.
I'll continue to track the demand for this feature though.

**Comment by Xuhao** [comment]
@jdalton Okay, thanks for reply!
