### ISSUE TITLE
Merge 2 arrays of objects by ObjectID

### ISSUE THREAD

**Issue by silentwarrior** [lodash/lodash#1234]
Hello.

I have the following problem. I have 2 arrays containing objects, each object has multiple properties but one of them is an ID that is unique.

Array one is some sort of in memory quick database and its semi-permanent as in it will stay in memory, the other one is gathered from ajax calls and I want to store them to make some sort of cache system.
```js
arr1 = [ {id:1, etc}, {id:2, etc}, {id:3, etc} ];

arr2 = [ {id:1, etc}, {id:3, etc}, {id:4, etc}, {id:5, etc}];

newArr1 = mergeById(arr1, arr2, function(item){ return item.id; } );

// newArr1 = [ {id:1, etc}, {id:2, etc}, {id:3, etc}, {id:4, etc}, {id:5, etc} ];
```
where overlapping items, (1 and 3) are now updated with results of `arr2` instead of `arr1`.

Is there a single function that will do this simple use case? Cant seem to find it.

Thank you.

PS: something along the lines of :
```js
newArr1 = _.unique(arr2.concat(arr1), function(i){return i.id;});
```
But without having to remember the correct order of the concat, and without haven't to use `array.contact` that might not be available or work that way exactly or what ever other issues.

**Comment by jlgrall** [comment]
You should try `_.groupBy`, then reduce each group by merging the elements. The documentation doesn't tell if the `_.groupBy` is stable (ie. if it keeps the elements ordered). But if it is the case, you can just merge each group with something like:
```javascript
// define your helper:
var merger = _.spread(_.assign)

// Merge each group by calling merger like:
item = merger(group)
```

**Comment by jdalton** [comment]
@silentwarrior You can also check out our [gitter room](https://gitter.im/lodash/lodash) for questions like this.

**Comment by rickcha** [comment]
I would suggest using _.sortedUniqBy(array, [iteratee]). It avoids duplicates and specify which property you wish to sort by. Please see the doc here: https://lodash.com/docs/4.17.4#sortedUniqBy
