### ISSUE TITLE
Feature: Transform function arguments

### ISSUE THREAD

**Issue by steelsojka** [lodash/lodash#1235]
One feature that I found useful is wrapping a function with argument transformers. Here's a scenario:

```javascript
function getNameList(names) {
  return names.join(', ');
}

function arrayWrap(arg = []) {
  return Array.isArray(arg) ? arg : [arg];
}

let getNames = useWith(getNameList, arrayWrap);

getNames('Joe'); // Joe
getNames(['Joe', 'John']); // Joe, John
``` 

This is a simple example, but could be used for converting arguments to the expected format.

**Comment by jlgrall** [comment]
For your case, you would need an "unspread" function. Then each argument can be processed through a `_.map()` and a flow to combine the "transformers".

Note: I can't make sense of your example. What do you want to join ? Should it not be a split() ? Do you want `getNames()` to return `"Joe, John"` or `["Joe", "John"]` ?

**Comment by steelsojka** [comment]
Basically the point of the example is to be able to run an argument through a transform. So I could do this:

```javascript
const square = useWith(x => x * x, _.parseInt);

square(10); // 100
square('10'); // 100
```
Instead of doing:

```javascript
const square = x => {
  if (!_.isNumber(x)) {
    x = _.parseInt(x);   
  }

  return x * x;
};
```

This can be used in a number of different ways. The examples I gave are pretty bare bones. View Ramda's documentation for [useWith](http://ramdajs.com/docs/#useWith) for more examples and probably a better explanation :/

**Comment by steelsojka** [comment]
Here is essential the bare implementation:

```javascript
function useWith(fn, ...transformers) {
  return function(...args) {
    for (let x = 0, len = transformers.length; x < len; x++) {
      args[x] = transformers[x].call(this, args[x]);
    }
    
    return fn.apply(this, args);
  }
}
```

**Comment by jridgewell** [comment]
That's just `_.flowRight` (`_.compose`).

```js
let getNames = _.flowRight(getNameList, arrayWrap);

getNames('Joe'); // Joe
getNames(['Joe', 'John']); // Joe, John
```

**Comment by steelsojka** [comment]
The 1st example can be accomplished by that but that's not what I'm trying to portray. Each argument can have a separate transform.

```javascript
const add1 = x => x + 1;
const time2 = x => x * 2;

const logNumbers = useWith((x, y) => console.log(x, y), add1, times2);

logNumbers(1, 2); // 2, 4
logNumbers(5, 10); // 6, 20 
```

Compose can transform a single argument through a pipeline of functions but think of it as each argument having it's own pipeline of transforms.

**Comment by StreetStrider** [comment]
@jridgewell, take a look at this:
```js
args[x] = transformers[x].call(this, args[x]);
```
So, this function allows to apply transformer corresponding to its argument. On the other hand, `compose` calls functions in chain, losing all arguments after 1st.

**Comment by jdalton** [comment]
Hey @steelsojka! I'm totally for this. Pretty handy for the more fp crowd.

**Comment by steelsojka** [comment]
@StreetStrider :+1: 
@jdalton Awesome!

**Comment by jlgrall** [comment]
@steelsojka: sry if I was not clear enough in my first comment. (I understood what you wanted. It was only your example that didn't make sense because there was many inconsistencies. Try to run your code with my definition of `useWith()`, ... or don't, it doesn't matter :-) )

 To be more explicit, here is the idea I was talking about with an "unspread" function:

```javascript
// The opposite of _.spread
// Creates a function that invokes func with the this binding
// of the created function and an array of arguments:
function unspread(func) {
	return function() {
		// Clone arguments to array args:
		for(var i = arguments.length, args = Array(i); i--;) args[i] = arguments[i];
		// Call func with arguments turned into an array as the first argument
		return func.call(this, args);
	};
}

// Here is a procedural definition of useWith:
var useWith = function() {
	// Chain the transformers:
	var transformers = _.flow.apply(_, arguments);
	// Create a function that map each argument with the transformers:
	return unspread(_.partial(_.map, _, transformers));
};

// Here is a functional definition of useWith:
_.partial.placeholder = {};	// Needed for nested _.partial()
var useWith = _.flow(_.flow, _.partial(_.partial, _.map, _), unspread);
_.partial.placeholder = _;

// Now you can create an arguments transformer:
var toIntAndAdd1 = useWith(_.parseInt, _.partial(_.add, 1));

// And you can transform your arguments:
toIntAndAdd1("0 $", "10 $", "100 $");	// => [1, 11, 101]

```

**Comment by jdalton** [comment]
@steelsojka Would you be interested in creating a PR for this?

**Comment by steelsojka** [comment]
@jdalton No Problem!

**Comment by steelsojka** [comment]
#1242

**Comment by jdalton** [comment]
Moved to #1242.
