### ISSUE TITLE
isPlainObject throws "Member not found" on element in IE8

### ISSUE THREAD

**Issue by heff** [lodash/lodash#1238]
Using IE8 (mine is a VM from modern.ie), go to lodash.com, open a console, then do:
```js
_.isPlainObject(document.createElement('div'));
```

I get a "Member not found" error. `(document.createElement('div')).toString();` returns "[object]", not "[object Object]", so I'm not sure why isPlainObject is even getting past that. Sorry if I'm missing something obvious.

![screen shot 2015-05-27 at 3 17 19 pm](https://cloud.githubusercontent.com/assets/166/7848770/afb8470a-0483-11e5-94c7-69feb79d7c07.png)
![screen shot 2015-05-27 at 3 17 28 pm](https://cloud.githubusercontent.com/assets/166/7848773/b114a6b6-0483-11e5-8cb0-ba7e22cd0aef.png)

**Comment by jdalton** [comment]
This is because you're using the modern build of lodash. However usually errors aren't thrown in older browsers. I've addressed this in edge so it'll be fixed on the next bump.

**Comment by heff** [comment]
Ah, got it. Thanks! I missed that lodash-modularized was all the modern build.
