### ISSUE TITLE
No product method

### ISSUE THREAD

**Issue by ChrisJefferson** [lodash/lodash#1239]
Ruby has a method called product (sometimes known as outer product), which takes all pairs generated from two arrays. It's hard to explain, here is a Ruby example.

```[1,2,3].product([4,5])     #=> [[1,4],[1,5],[2,4],[2,5],[3,4],[3,5]]```

I can do this for two arrays, for example (using _range(1) as a stand in):

```__flatten(_.map(_.range(10), function(x) { return _.map(_.range(10), function(y) { return [x,y] } ) } ));```

In general I would like two functions: product and productWith, which would mirror zip and zipWith.

I find these functions useful whenever I would normally use two nested loops.

I am happy to provide a neat implementation of these functions (I already have them privately), I wanted to check if they would be accepted, and also I haven't just missed them somewhere (or a shorter way of writing them).

**Comment by StreetStrider** [comment]
#852

**Comment by jdalton** [comment]
Hiya @ChrisJefferson! As @StreetStrider pointed out this seems like a better fit as a mixin. However, if it becomes a popular demand we'll reevaluate.

**Comment by ChrisJefferson** [comment]
Stupid question, what does "as a mixin" mean? Basically add it myself and keep a local copy?

**Comment by jdalton** [comment]
> Basically add it myself and keep a local copy?

Yes. You can create a mixin with [_.mixin](https://lodash.com/docs#mixin).
