### ISSUE TITLE
Feature: add mapProperty function

### ISSUE THREAD

**Issue by id0Sch** [lodash/lodash#1240]
Hey,
I've been working with lodash quite intensely for a while now and first off I love it!!
but - I always add my own mixin for this function that maps a property of an item.
ps. I know its not a big change to the usage, but it comes very handy when working with chains

Thanks!

suggested function
```javascript
function mapProperty(item, property, fn){
      return _.map(item[property], fn)
    }
```
<b>usage</b>
before
```javascript
var newItem = _.map(item.property,myFunc)
_(data.feeds).chain().mapProperty(transformFeed)
```
after
```javascript
var newItem = _.mapProperty(item, property,myFunc)
_(data).chain().mapProperty('feeds', transformFeed)
```

**Comment by d10** [comment]
Currently, you can use `_(data).chain().pluck('feeds').map(transformFeed).value()`.

**Comment by id0Sch** [comment]
this would be cool if I just wanted to mess with the feeds property, but sometimes manipulating the root object is required as well.
if theres a way to do that as well it would be cool.

**Comment by jdalton** [comment]
Hi @id0Sch! I think this would be a good continued as a mixin, but not in lodash. I could also see composition of `_.partial` and `_.result` being used.

**Comment by StreetStrider** [comment]
In the simple case when we need just one property it is a combination of `pluck` and then `map` (as @d10 mentioned above). The issue's @id0Sch talking about makes sense if we need to transform *some property* and return *whole object*, not a projection to that property. This is close to the idea of lenses. I've looked through Ramda now and it has support for lenses, for instance [lensProp](http://ramdajs.com/docs/#lensProp) works such:
```js
↳ repl.js R=ramda
js > xL = R.lensProp('x');
// xL is now a lens, functional getter-setter object
{ [Function] set: [Function: f2], map: [Function: f2] }
// lets use it as getter:
js > [ {x:1}, {x:2} ].map(xL);
[ 1, 2 ]
// and then as setter:
js > [ {x:1}, {x:2} ].map(xL.set(3));
[ { x: 3 }, { x: 3 } ]
```
This is clean and functional style. @id0Sch, maybe you want such stuff. However, I'm not sure it is suits for LoDash and I'm also having some doubts about overhead of this approach. In major of production code this can be replaced with a combination of simpler functions. I'm not using this in my code.
