### ISSUE TITLE
Feature request - deep object walk through

### ISSUE THREAD

**Issue by kof** [lodash/lodash#1244]
Its often needed to camelize all property names of an object and subobjects when for e.g. talking to some json api which uses snake case. We all hate to mix camel and snake case in javascript, right?

There must be also other use cases.

The idea is to have a function which allows to deeply manipulate an object using other functions like camelCase.

```
let obj = {my_name: {something_else: 1}}
rename(obj, camelCase)
// {myName: {somethingElse: 1}}
```

**Comment by kof** [comment]
It could be called "rename"

**Comment by kof** [comment]
Oh its actually a deep version of mapKeys

**Comment by jdalton** [comment]
> Oh its actually a deep version of mapKeys

Yep! At the moment you can tackle this with recursion in the `_.mapKeys` callback.

**Comment by kof** [comment]
yes, but there are also arrays and then you end up with something you wan't copy paste .... its worth having a shortcut

**Comment by jdalton** [comment]
Yep. For now this would be a good mixin. If there's demand we'll reevaluate.

**Comment by kof** [comment]
Here is th demand verification https://www.npmjs.com/package/camelize

**Comment by kof** [comment]
3,600 downloads in the last day
16,857 downloads in the last week
80,138 downloads in the last month

**Comment by kof** [comment]
And its only camelizing, with  recursive mapKeys  and iterator arg you could do much more

**Comment by simpixelated** [comment]
Just for reference, here's a (probably poorly) written example of deep camelizing.

```javascript
function transformKeysDeep (data, keyTransformFunc) {

	function transformKeys (obj, v, k) {
		obj[keyTransformFunc(k)] = _.isObject(v) ? transformKeysDeep(v, keyTransformFunc) : v;
	}

	function transform (data) {
		return !_.isString(data) && !_.isNumber(data) ? _.transform(data, transformKeys) : data;
	}

	return _.isArray(data) ? _.map(data, transform) : transform(data);
}

// usage
transformKeysDeep(response.data, _.camelCase)
```

**Comment by jlreymendez** [comment]
:+1:

**Comment by kof** [comment]
Just stumbled over an issue in my implementation: recursive references. Which means that one needs to reference all objects in an array and check if they has been already processed. 

I still think a deep iterator which can handle recursion is very useful and should have a big demand.

**Comment by vovagusarov** [comment]
I've solved this by writing the following function:
```javascript
mapKeysDeep = function(obj, func) {
    return _.forEach(obj, function(value, key, objReference) {
        if (_.isObject(value)) {
            mapKeysDeep(value, func);
        }
        if (_.isNumber(key)) {
            return objReference[key] = value;
        } else {
            objReference[func(key)] = value;
            return delete objReference[key];
        }
    });
 }

// usage
mapKeysDeep(object, _.camelCase);
```

**Comment by kof** [comment]
@vovagusarov your implementation won't avoid double pass of circular dependencies. In big objects this is a huge performance issue. We had 5s camelization process on an object because of that.

**Comment by vovagusarov** [comment]
@kof that's true, did you finally solve deep mapping in your case?

**Comment by kof** [comment]
Yes, and still hoping we can add it to lodash.

**Comment by Merbs** [comment]
@vovagusarov your implementation also seems to delete keys where `func(key) === key`. For example, `mapKeysDeep({user: "foo"}, _.camelCase)` doesn't work. Also, I don't think the `return` statements do anything. If we choose not to care about recursive elements, you can edit your function slightly to:


```
// Mutates the object to have keys transformed by func
var mapKeysDeep = function(obj, func) {
  return _.forEach(obj, function(value, key, objReference) {
    if (_.isObject(value)) {
      mapKeysDeep(value, func);
    }
    if (_.isNumber(key)) {
      objReference[key] = value;
    } else {
      objReference[func(key)] = value;
      if (func(key) !== key) {
        delete objReference[key];
      }
    }
  });
};

// Returns a copy of an object with all keys converted to snake case
var snakeCaseDeep = function(obj) {
  return mapKeysDeep(_.cloneDeep(obj), _.snakeCase);
};
```

Other than recursion, there may be other edge cases I'm not considering. I would be strongly in favor of adding `_.mapKeysDeep` as a non-mutative function such that `_.mapKeysDeep(obj, _.snakeCase)` does what `snakeCaseDeep` above is intended to do.

**Comment by vovagusarov** [comment]
@Merbs you're right, I've added `if (func(key) !== key)` statement to my code later, just forgot to update it in this discussion. Tnx.

**Comment by dylancwood** [comment]
I'd be very interested in this functionality as well. It is currently offered by the lodash-deep mixin. 

Also, here's another approach that might be more generic: `_.deeply(func)` to recursify any function.
Taken from http://stackoverflow.com/questions/35055731/how-to-deeply-map-object-keys-with-javascript-lodash
```
_.mixin({
    deeply: function (map) {
        return function(obj, fn) {
            return map(_.mapValues(obj, function (v) {
                return _.isPlainObject(v) ? _.deeply(map)(v, fn) : v;
            }), fn);
        }
    },
});


obj = _.deeply(_.mapKeys)(obj, function (val, key) {
    return key + '_hi';
});
```

**Comment by liveresume** [comment]
Is @dylancwood 's posted solution the recommended approach by Lodash devs? 
If not, why was this closed? Seems to be well within scope and very useful.
Is something else in the works?

**Comment by fogine** [comment]
I vote for generic deep object walk through implementation without it being explicitly targeted to object keys/values like `mapKeysDeep` or `mapValuesDeep` would be.

**Comment by xfg** [comment]
+1

**Comment by odub** [comment]
Recursive `_.mapValues`:
```
const mapValuesDeep = (v, callback) => (
  _.isObject(v)
    ? _.mapValues(v, v => mapValuesDeep(v, callback))
    : callback(v)
)
```

**Comment by fabien0102** [comment]
Recursive `_.mapKeys`:
```javascript
const mapKeysDeep = (obj, cb) =>
  _.mapValues(
    _.mapKeys(obj, cb),
    val => (_.isObject(val) ? mapKeysDeep(val, cb) : val),
  )
```

**Comment by mleg** [comment]
+1 for **fogine**'s proposal.
For example, **_.keysDeep()** would be nice to have. Combining it with _.get()/_.set() may cover pretty much every case for deep object manipulating.
One case I am looking for is to validate object structure by another object.

**Comment by fabien0102** [comment]
@mleg You can have a look on https://www.npmjs.com/package/joi for validate object structure :wink:

**Comment by mleg** [comment]
**fabien0102** thanks, already looked at. That's too heavy for my task. 
Ended up using https://www.npmjs.com/package/all-object-keys.

**Comment by mold** [comment]
Here's a version of `mapKeysDeep` that keeps arrays as arrays and doesn't convert arrays into objects with integer keys (but probably still ruins other types of objects):

```javascript
const mapKeysDeep = (obj, cb) => {
    if (_.isArray(obj)) {
        return obj.map(innerObj => mapKeysDeep(innerObj, cb));
    }
    else if (_.isObject(obj)) {
        return _.mapValues(
            _.mapKeys(obj, cb),
            val => mapKeysDeep(val, cb),
        )
    } else {
        return obj;
    }
}
```

**Comment by leontastic** [comment]
The `mapValuesDeep` function described by @odub works if your iteratee only cares about the value of each leaf node, but to preserve the function signature of the `mapValues` iteratee `(value, key, object)` you can use the following:

```javascript
const mapValuesDeep = (obj, fn) =>
  _.mapValues(obj, (val, key) =>
    _.isObject(val)
      ? mapValuesDeep(val, fn)
      : fn(val, key, obj)
  )
```

**Comment by slorber** [comment]
In case you want to filter object/array values by a predicate, you may find this useful:

```js 

const _ = require("lodash");
const {isObject,isArray,pickBy,identity,mapValues} = _;

// Remove all object keys whose values are falsey (null/undefined)
const pickTruthy = object => pickBy(object, identity);

const filterDeep = (item, predicate) => {
  if ( !predicate(item) ) {
    return undefined;
  }
  else if ( isArray(item) ) {
    return array.filter(predicate)
  }
  else if ( isObject(item) ) {
    const objectWithUndefinedValues = mapValues(item, value => filterDeep(value,predicate));
    return pickTruthy(objectWithUndefinedValues);
  }
  else {
    return item;
  }
};

const array = [
  { id: 'a' },
  {
    id: 'b',
    elements: {
      col1: [{ id: 'c' }],
      col2: [],
    },
  },
  {
    id: 'b',
    elements: {
      col1: [{ id: 'd' }, { id: 'e' }],
      col2: [],
      col3: [{ id: 'f' }],
    },
  },
];

console.log(JSON.stringify(array,null,2));

const logResult = (predicate) => {
  const result = filterDeep(array,predicate);
  console.log("\nresult:\n" + JSON.stringify(result,null,2));
};








logResult(item => {
  return !(isObject(item) && item.id === "a" );
});

```

**Comment by iamdanthedev** [comment]
here is map values based on mold's answer:

```
const mapValuesDeep = (obj, cb) => {
  if (isArray(obj)) {
    return obj.map(innerObj => mapValuesDeep(innerObj, cb));
  } else if (isObject(obj)) {
    return mapValues(obj, val => mapValuesDeep(val, cb));
  } else {
    return cb(obj);
  }
};
```

**Comment by Kikobeats** [comment]
I took implementations present in this issue, put some appropriate tests around them for controlling edge cases and shipped [map-values-deep] (https://github.com/Kikobeats/map-values-deep) and [map-keys -deep] (https://github.com/Kikobeats/map-keys-deep) for anyone interested in using this functionality in a centric way.

If in the future, lodash decide to add these methods as part of the API, just I will deprecate them.

**Comment by ughitsaaron** [comment]
I came to this issue recently hoping to find something to help me recursively transform a deeply nested object into a flat array of values (non-array or non-object values). My use case was wanting to transform a deeply nested object of error messages into a flat array of strings. If anybody comes around in the future looking for something similar, here was the solution I landed on.

```javascript
const mapValuesFlat = (obj) => {
  return _.flatMap(obj, (v) => {
    if (_.isPlainObject(v)) {
      return mapValuesFlat(v);
    }

    return v;
  });
};
```

Example
```javascript
let obj = {
  a: 'hello',
  b: {
    c: {
      d: 6,
      e: {
        f: 'goodbye'
      },
      g: {}
    }
  }
};

mapValuesFlat(obj); // => ['hello', 6, 'goodbye']
```

**Comment by klondikemarlen** [comment]
I ended up using this:
> mapKeys lodash function takes two argumens (value, key) and I'm ignoring the "value" argument.
```js
export function mapKeysDeep(obj, fn): any {
  if (isPlainObject(obj)) {
    const objWithTransformedKeys = mapKeys(obj, (_, key) => fn(key));
    return mapValues(objWithTransformedKeys, (value) => mapKeysDeep(value, fn));
  } else if (isArray(obj)) {
    return map(obj, (value) => mapKeysDeep(value, fn));
  } else {
    return obj;
  }
}
```

**Comment by chichilatte** [comment]
A [working example](https://playcode.io/2433666) of odub's function [(above)](https://github.com/lodash/lodash/issues/1244#issuecomment-271850316) with an added `path` parameter in the iterator function...
```js
const mapValuesDeep = (obj, fn, path = '') =>
  _.mapValues(obj, (val, key) => {
    const breadcrumb = (path==='' ? '' : '.') + key

    return _.isPlainObject(val)
      ? mapValuesDeep(val, fn, path + breadcrumb)
      : fn(val, key, obj, path + breadcrumb)
  })
```
