### ISSUE TITLE
bindCallback treats non-functions as 'identity function' leads to confusing behaviour

### ISSUE THREAD

**Issue by ChrisJefferson** [lodash/lodash#1245]
Various functions (including _.times) use bindCallback, which contains the lines:

```
      if (typeof func != 'function') {
        return identity;
      }
```

There might be a good reason for this, but it seems strange to silently ignore non-functions?

I came across this trying to figure out why:

```_.times(3, _.times(3, _.constant(False)));```

returns ```[0,1,2]```. The reason is that ```_.times(3, _.constant(False))``` doesn't return a function, so the outer ```_.times``` becomes equivalent to ```_.times(3, identity)```. A more sensible default behaviour to me would seem to be to just error out (in my case I would like wrapping non-functions in _.constant, but I can imagine that would be confusing sometimes too).

**Comment by ChrisJefferson** [comment]
quick extra post (sorry). I think treating 'undefined' as identity might make sense, mainly not to break code like:

```_.times(3)
[0,1,2]```

which while undocumented (I think), I could imagine being common in the wild.

**Comment by ChrisJefferson** [comment]
Sorry for repeated posts..

I tried changing the test in bindCallback to 'func == null', and all tests pass (typeof func == undefined fails a test which tries passing 'nullish' values in).

**Comment by jdalton** [comment]
The `_.times` is documented to accept a function.
Passing it an array `_.times(3, ...)` doesn't make sense. The nullish check is to allow no iteratee to be provided.

**Comment by ChrisJefferson** [comment]
I agree it makes no sense, that's why I suggested changing the check to 'func == null', which would have made my (incorrect) code error, rather than the current behaviour where the code continues and produces nonsense answers.

**Comment by ChrisJefferson** [comment]
Would you accept a patch which made no correct code change behaviour, but made invalid input like ```_.times(3,1)``` error?

**Comment by jdalton** [comment]
Imma sit on this for a bit. No need to create a PR. I'll ping back.

**Comment by StreetStrider** [comment]
@ChrisJefferson, hi. The real issue here is that JS is very type-tolerated language. LoDash lib just follows this style. You're asking for type guarantees in dynamic, error-ignorant, non-strict typed language. Take a look at languages like TypeScript which supply programmer with more type gurantees. I've found that LoDash has [type definitions](https://github.com/borisyankov/DefinitelyTyped/tree/master/lodash) for it.

**Comment by ChrisJefferson** [comment]
@Streetstrider: I know general type checking is impossible in Javascript :) I just felt in this case the behaviour should be "you gave me something where I expected a function, so I'm going to call it like a function, even though that will crash", rather than the current "you passed me something not a function when I expected a function, so I will act as if you gave the function one less argument".
