### ISSUE TITLE
Pick multiple properties

### ISSUE THREAD

**Issue by kentcdodds** [lodash/lodash#1247]
Would love this to work (or maybe there's a better way to do what I'm trying to do):

```javascript
var foos = [
  { x: 1, y: 2, z: 3 },
  { x: 4, y: 5, z: 6 },
  { x: 7, y: 8, z: 9 }
];

var sortaMapped = _.pick(foos, ['x', 'y']);

_.eq(sortaMapped, [
  { x: 1, y: 2 },
  { x: 4, y: 5 },
  { x: 7, y: 8 }
]);
```

How I accomplish this today:

```javascript
_.map(foos, foo => {x: foo.x, y: foo.y});
```

**Comment by kentcdodds** [comment]
[Original tweet](https://twitter.com/kentcdodds/status/604336742406086656) had a reply with [a suggestion](https://twitter.com/Snapwich/status/604345167957499904):

```javascript
_.map(foos, _.partialRight(_.pick, 'x', 'y'));
```

Not a terrible work-around, but I would still like to have this feature to make it easier to read/understand/maintain/etc.

**Comment by StreetStrider** [comment]
@kentcdodds, is this workaround works properly? I'm asking because of I'm afraid it's not, since map propagates three arguments to partialled function (and two of them become keys).

Speaking of your issue, this sounds like `pluck` with multiple keys. I remember this have been discussed early several times, we should look for it in issues. I'm facing this issue from time to time too.

**Comment by davidkpiano** [comment]
+1, would love this feature.

@StreetStrider I thought that at first too, but `pluck` is mainly for returning values, not exactly key-value pairs.

**Comment by StreetStrider** [comment]
@davidkpiano, yes, yes, you're right. This was maybe a reason to not implement multiple keys for this very function.

**Comment by jdalton** [comment]
```js
_.map(foos, _.partial(_.ary(_.pick, 2),_, ['x', 'y']));
```

**Comment by kentcdodds** [comment]
Thanks again @jdalton. I'll give this a shot as well. Just like #1248, this would be handy to have built-in, but I can make a mixin for it.

**Comment by jdalton** [comment]
Hey @kentcdodds! I hear ya. I tend to punt on methods that can be easily composed to create the desired effect. That said, if this becomes a popular demand we'll totally consider it.

**Comment by kentcdodds** [comment]
:+1:

**Comment by kentcdodds** [comment]
Success. Here's my mixin:

```javascript
import _ from 'lodash';

/* eslint no-underscore-dangle:0 */
export const _mixins = {pickMultiple}; // the actual mixin is added elswhere

if (process.env.NODE_ENV === 'test') {
  require('./_mixins.test')(_mixins);
}

function pickMultiple(array, thingsToPick) {
  return _.map(array, _.partial(_.ary(_.pick, thingsToPick.length), _, thingsToPick));
}
```

And here's my test:

```javascript
/* eslint no-underscore-dangle:0 */
export default _mixins => {
  describe('_mixins', () => {
    describe(`pickMultiple`, () => {
      const {pickMultiple} = _mixins;

      it(`be able to pick multiple items from an array of objects`, () => {
        const foos = [
          { x: 1, y: 2, z: 3 },
          { x: 4, y: 5, z: 6 },
          { x: 7, y: 8, z: 9 }
        ];
        const result = pickMultiple(foos, ['x', 'y']);

        expect(result).to.eql([
          { x: 1, y: 2 },
          { x: 4, y: 5 },
          { x: 7, y: 8 }
        ]);
      });
    });
  });
};
```

Thanks!

**Comment by j0hnsmith** [comment]
I'd love to see this added.

**Comment by Ossip** [comment]
+1

**Comment by kmckee** [comment]
+1

**Comment by dallincoons** [comment]
+1

**Comment by jdalton** [comment]
With `lodash/fp` this is even cleaner:
```js
fp.map(fp.pick(['x', 'y']), foos);
```

**Comment by akobler** [comment]
+1

**Comment by pccjamie** [comment]
+1

**Comment by joeysino** [comment]
Just a suggestion, you could delimit the property names with spaces:

    var sortaMapped = _.pick(foos, 'x y');

This is what mongoose does with [Query.select()](http://mongoosejs.com/docs/api.html#query_Query-select). I find it easy to type and clear to read.

I know this won't work for keys which contain spaces.  But they are quite rare, and could still be handled by passing an Array:

    var sortaMapped = _.pick(foos, ['First Name', 'Last Name']);

Although presumably this would be a breaking change. :/

**Comment by danieldunderfelt** [comment]
This would be great to have in `has`, and I actually thought `['a', 'b']` meant sibling properties. It is quite confusing that `['a', 'b']` and `'a.b'` mean the same thing and this is not explained in the docs.

**Comment by Miges** [comment]
Didn't `_.pluck` use to do this?

Anyway, an ES6 way is `_.map(foos, i => _.pick(i, 'x', 'y'))`

**Comment by sashimigud** [comment]
This might be a really stupid question, and I realize Miges comment is from two years ago.
But when I try this solution it returns an object with both x and y properties.
It returns **{ "x":"x-value", "y":"y-value"}**, and I would like only **x-value y-value** to be returned. Any suggestions would be greatly appreciated!

**Comment by StreetStrider** [comment]
@sashimigud use `_.at`.

**Comment by sashimigud** [comment]
@StreetStrider thanks! Using _.at like this: `_.map(foos, i => _.at(i, 'x','y'))` gave me output like this: **["x-value", "y-value"]** definitely closer but I only wanted the string value of x and y. But I managed to find a way to do exactly like I wanted it. It works, but is most likely very verbose. Here is what I did: 
`return _.map(this.$store.getters.get_klasse, elev => _.pick(elev, 'Etternavn','Fornavn')).map(elev => elev.Etternavn + ' ' + elev.Fornavn)` 

or on a more general form:
`return _.map(foos, i => _pick(i, 'x', 'y')).map(i => i.x + ' ' + i.y)`

**Comment by StreetStrider** [comment]
@sashimigud 
`_.map(X, x => _.at(x, 'x','y').join(' '))`.

**Comment by sashimigud** [comment]
@StreetStrider Thanks alot! thats a much nicer way of writing it! Works like a charm!

**Comment by idbartosz** [comment]
So it seems there's no elegant solution for this problem in classic lodash, even with destructuring it feels kinda odd 👨🏻‍🎨
```js
_.map(foos, ({ x, y }) => ({ x, y }));
```
