### ISSUE TITLE
Reverse Deep Merge

### ISSUE THREAD

**Issue by kentcdodds** [lodash/lodash#1248]
I may just not know what the name for this is, but in my project I have this function that essentially works like `merge` but instead of the "rest" parameters overriding the destination object, it just fills in `undefined values. Something like this:

```javascript
var x = {foo: 'bar'};
var y = {foo: 'baz', foobar: 'eggs'};
_.merge(x, y);
_.eq(x, {foo: 'bar', foobar: 'eggs'}); // <-- evaluates to false, I want it to be true
```

**Comment by kentcdodds** [comment]
If this is useful, this does it for me:

```javascript
var x = {foo: 'bar'};
var y = {foo: 'baz', foobar: 'eggs'};
reverseDeepMerge(x, y);
_.eq(x, {foo: 'bar', foobar: 'eggs'}); // <-- evaluates to true

function reverseDeepMerge(dest) {
  _.each(arguments, function(src, index) {
    if (!index) {
      return;
    }
    _.each(src, function(val, prop) {
      if (_.isUndefined(dest[prop])) {
        dest[prop] = _.clone(val);
      } else if (objAndSameType(dest[prop], val)) {
        reverseDeepMerge(dest[prop], val);
      }
    });
  });
}

function objAndSameType(obj1, obj2) {
  return _.isObject(obj1) && _.isObject(obj2) &&
    Object.getPrototypeOf(obj1) === Object.getPrototypeOf(obj2);
}
```

**Comment by jdalton** [comment]
```js
var defaultsDeep = _.partialRight(_.merge, function defaults(objVal, srcVal) {
  return objVal === undefined ? srcVal : _.merge(objVal, srcVal, defaults);
});
```

**Comment by kentcdodds** [comment]
Awesome, thanks @jdalton, I'll give that a shot. I could make a mixin for myself, but I think having this functionality built-in would be pretty useful.

**Comment by jdalton** [comment]
Similar to #1247, since it's easily composed I want to hold on adding it to core until there's a decent demand for it. @phated this is your cue.

**Comment by kentcdodds** [comment]
:+1:

**Comment by kentcdodds** [comment]
Success, here's my mixin:

```javascript
import _ from 'lodash';

/* eslint no-underscore-dangle:0 */
export const _mixins = {pickMultiple, defaultsDeep: getDefaultsDeep()};

if (process.env.NODE_ENV === 'test') {
  require('./_mixins.test')(_mixins);
}

function getDefaultsDeep() {
  return _.partialRight(_.merge, function defaults(objVal, srcVal) {
    return objVal === undefined ? srcVal : _.merge(objVal, srcVal, defaults);
  });
}
```


and here are my tests:

```javascript
/* eslint no-underscore-dangle:0 */
export default _mixins => {
  describe('_mixins', () => {
    describe(`defaultsDeep`, () => {
      const {defaultsDeep} = _mixins;

      it(`should should deep merge with defaults`, () => {
        const defaults = {
          foo: '(-o-)',
          bar: {
            baz: '|-o-|',
            foobar: [
              {spam: 'eggs'}
            ]
          },
          oof: {
            rab: 32
          },
          raboof: 'maps'
        };
        const defaults2 = {
          whatever: 'tired of making things up'
        };

        const obj = {
          foo: 'ᕕ( ᐛ )ᕗ',
          bar: {
            foobar: [
              {eggs: 'spam'},
              {cool: 'beans'}
            ]
          },
          oof: {
            sgge: 'maps'
          }
        };

        defaultsDeep(obj, defaults, defaults2);

        expect(obj).to.eql({
          foo: 'ᕕ( ᐛ )ᕗ',
          bar: {
            baz: '|-o-|',
            foobar: [
              {eggs: 'spam', spam: 'eggs'},
              {cool: 'beans'}
            ]
          },
          oof: {
            rab: 32,
            sgge: 'maps'
          },
          raboof: 'maps',
          whatever: 'tired of making things up'
        });
      });

    });
  });
};
```

**Comment by phated** [comment]
I'd love a deep defaults.  I don't think it would be super hard to add to the library.  :+1:

**Comment by d10** [comment]
Yep, deep defaults could be really useful. Another :+1: here ;)

**Comment by jdalton** [comment]
What are your use caes @phated / @d10? Mind creating a PR?

**Comment by kentcdodds** [comment]
I can give my use-case. I own the [angular-formly](https://github.com/formly-js/angular-formly) project. One of the best features ever is [Default Options](http://docs.angular-formly.com/v6.11.0/docs/formlyconfig#settype) when creating a generic type ([example](http://angular-formly.com/#/example/custom-types/default-options)).

The default options are specified by whoever creates the field time, then they can be overridden by users of the type. The root configuration for these fields is general stuff that applies to all types (for the most part). Specific configuration for a field happens in a sub-object called `templateOptions`. This is where the bulk of `defaultOptions` is specified and overridden (also, `data` is a free-form object).

I use a deep defaults (what I called reverse deep merge) to enable this.

Unfortunately, as awesome as lodash is, I just can't bring it into my library wholesale. But, if this were implemented and had it's own npm module, then I could bring it in that way :-)

**Comment by kentcdodds** [comment]
I also have an abstraction in my own app for state definition for [ui-router](https://github.com/angular-ui/ui-router) (the de facto angular router) where I use a deep defaults because many default opens can be in the `data` object.

I also have a similar abstraction for [js-data](https://github.com/js-data/js-data)'s `defineResource` in which I do something similar for the `meta` object. As part of this, I actually use the `_.wrap` function a great deal to "merge" functions. This is another issue, but it would be very handy to have something to merge functions as well, though that use-case is probably smaller...
