### ISSUE TITLE
_.delete/_.remove for objects using a path.

### ISSUE THREAD

**Issue by andrewhathaway** [lodash/lodash#1252]
It would be great to be able to remove a value from an object, including it's key using a path just like `_.get` and `_.set`.

```javascript
_.remove(object, 'a[0].b.c');
```

**Comment by jdalton** [comment]
Hi @andrewhathaway! For now see #962.

**Comment by arxpoetica** [comment]
Considering this is a fairly common operation in JS, :+1: :+1: 

(Examples: `delete someVar;`, `localStorage.removeItem('keyPath')`, etc.

**Comment by megawac** [comment]
I agree, `_.remove(object, 'a.b.c')` could be very useful (I'll PR it if you want)

**Comment by jdalton** [comment]
`_.remove` is for arrays.  See #962.

**Comment by megawac** [comment]
I suppose we're still trying to avoid overloading @jdd?

**Comment by jdalton** [comment]
Moving a method to the Collection category is something I want to drag my feet on because it has a lot of baggage with it.

**Comment by megawac** [comment]
How about unset then?

**Comment by arxpoetica** [comment]
Agreed, refactoring `_.remove` as collection === :sob:, but `_.delete` or `_.unset`.

**Comment by jdalton** [comment]
I can dig `unset`.

**Comment by travisdahl** [comment]
I love it when I go searching for something and people are currently talking about it. You guys are awesome.

+1

**Comment by jdalton** [comment]
The next step is for someone to create a PR for `_.unset`.

**Comment by Braincompiler** [comment]
Why not extending `omit`?

**Comment by arxpoetica** [comment]
:zap: :zap: :zap: !!!

**Comment by andrewhathaway** [comment]
:beers:

**Comment by nabati** [comment]
Out of curiosity, why does `unset` return a boolean and not the object itself as does `set`? This behaviour was unexpected for me.

**Comment by jdalton** [comment]
HI @nabati!

It's modeled after `delete x` or `Reflect.deleteProperty` which return boolean values from their operations.
