### ISSUE TITLE
reqiure('lodash') fails with "Illegal access runInContext"

### ISSUE THREAD

**Issue by kimmobrunfeldt** [lodash/lodash#1253]
Trying to require lodash in [Knexfile.js](http://knexjs.org/#knexfile) fails with:

```
/Users/kimmo/code/project/node_modules/lodash/index.js:692
  function runInContext(context) {
                       ^
illegal access
```

My knexfile.js is defined as:

```javascript
var _ = require('lodash');
var dbConfig = require('./src/database').config;

module.exports = _.merge(dbConfig, {
    migrations: {
        directory: __dirname + '/migrations',
        tableName: 'migrations'
    }
});
```

As a workaround, I require only `lodash.merge` package and it works.

**Comment by jdalton** [comment]
Hi @kimmobrunfeldt! I'm not actually sure what the issue there is. It doesn't look like directly a lodash problem though. Maybe the [Knex](https://github.com/tgriesser/knex/issues) folks can help.

**Comment by kimmobrunfeldt** [comment]
I also filed this issue to Knex: https://github.com/tgriesser/knex/issues/850 Let's see what they say

**Comment by DrClick** [comment]
I have the same issue but I dont use Knex. I have not been able to resolve this issue.

**Comment by jdalton** [comment]
Without information I'm not able to help you.

**Comment by DrClick** [comment]
I actually have not seen the issue since I followed the advice on the knex page about removing my node cache and reinstalling.

**Comment by DrClick** [comment]
if it comes up again, I will try and track down the issue

**Comment by jdalton** [comment]
Thanks @DrClick!

**Comment by fritx** [comment]
![image](https://cloud.githubusercontent.com/assets/6647633/10366442/1a8058e2-6dfd-11e5-91f5-34e3ba4a6874.png)

+1 when running in nw.js, don't know why

**Comment by fritx** [comment]
After some time delay, it resumes to work..
It's probably not a lodash problem.. ;)

**Comment by fritx** [comment]
![image](https://cloud.githubusercontent.com/assets/6647633/10384738/de01d5c8-6e72-11e5-9170-3ca27368bd2b.png)

+1 running on nw.js 0.10.5 in Windows. happens occasionally

**Comment by DrClick** [comment]
I think the issues was update node and lodash…

**Comment by fritx** [comment]
Thanks. seems you're right.. But I wonder which version brought the break??
