### ISSUE TITLE
Like Not in python?

### ISSUE THREAD

**Issue by isergey** [lodash/lodash#1255]
Hi all! 
Is there a function whose behavior is similar to the operator NOT in python:
```js
_.isNot([] | {} | '' | 0 | null | undefined | Nan | false) => true;
_.isNot([1, 2] | {a: 1} | 'text' | 1 | function () {} | true | object instance) => false;
```
I know about the function isEmpty, but it returns true for numbers that may not always be convenient.

Thank you for great work!

**Comment by jdalton** [comment]
The `_.isEmpty` method detects empty collections. Lodash doesn't currently have a method like `_.isNot`. I think for now I'd be a good fit as a mixin.
