### ISSUE TITLE
isFunction method is doesn't work in the client-side

### ISSUE THREAD

**Issue by pedramphp** [lodash/lodash#1256]
line 17 is breaking because it is dependent on the ```global``` object
```var Uint8Array = getNative(global, 'Uint8Array');``` 
browser can't understand global.

**Comment by jdalton** [comment]
I'm sorry you're having trouble but lodash is tested in many [browsers](https://saucelabs.com/u/lodash) and [environments](https://travis-ci.org/lodash/lodash). This sounds like some transform/build issue.
