### ISSUE TITLE
generate docs as seen on https://lodash.com/docs ? 

### ISSUE THREAD

**Issue by mc007** [lodash/lodash#1258]
Hi,
I know there is a large Markdown file but I generate it my self as on https://lodash.com/docs ? 
thanks!
g

**Comment by jdalton** [comment]
Hi @mc007. We use [docdown](https://github.com/jdalton/docdown) to generate the markdown and [php-markdown](https://michelf.ca/projects/php-markdown/) to generate the HTML. There's a bit or tweaking (we use an older version of php-markdown at the moment) so milage may vary.

**Comment by mc007** [comment]
Thanks, would love to get this script ;-)

**Comment by georgschlenkhoff** [comment]
@mc007 maybe this helps you: http://dokkerjs.com/. Submit an issue if something does not work.
