### ISSUE TITLE
uncapitalize?

### ISSUE THREAD

**Issue by mzgol** [lodash/lodash#1260]
An `_.uncapitalize` function being the reverse of `_.capitalize` would be useful. I'm currently migrating from lodash 2.4 to 3.9 & this is the only case-related function I had implemented that I couldn't remove in favor of a lodash one.

**Comment by jdalton** [comment]
Heya @mzgol! That's lower casing the first letter of every word?

I think for now it can stay as a mixin. We cover common casing methods so the next one up will likely be pascal case.

**Comment by mzgol** [comment]
> Heya @mzgol! That's lowercasing the first letter of every word, right?

Lowercasing only the first letter of the string, similarly how `_.capitalize` only uppercases the first letter.

I opened it because I feel that other "casing" functions can be "reversed" if you just go between canonical representations, e.g. `_.kebabCase(_.camelCase('a-b')) === 'a-b')` and there is no such method for "reversing" the capitalizing.

From what I see, though, I mostly needed this method because my custom `camelCase` function was not lowercasing the first letter and `_.camelCase` is so it seems I'm covered; I either type `_.capitalize(_.camelCase(input))` or `_.camelCase(input)`. And with `_.pascalCase` implemented it'll just be `_.pascalCase(input)` or `_.camelCase(input)` if I understand correctly.

But I see, it's hard to hit the sweet spot where useful composable methods are included but not too many of them. :) Thanks.
