### ISSUE TITLE
how to create object with keys from array, and values from a function?

### ISSUE THREAD

**Issue by davidmaxwaterman** [lodash/lodash#1261]
I'm looking for something like this :

myObject = _.zipToObject([a, b, c], function () { return makeObject() });
// myObject -> { a: [Object], b: [Object], c: [Object] };

IE, it creates an object whose keys are taken from the array, and for each key, the value is set by a callback.

**Comment by jdalton** [comment]
You can combo `map` or `_.times` and `_.zipObject`:
```js
_.zipObject(keys, _.map(keys, function() { }));
```

**Comment by Pyrolistical** [comment]
:+1: but I feel _.zipObject should just be overloaded such that its second parameter could be a function that does this behaviour

**Comment by evilive3000** [comment]
Hi! I'm agree with @Pyrolistical 
It would be helpful to have such interface for `_.zipObject`:

    // scalar types
    _.zipObject(['a','b','c'], 42) // {'a':42, 'b':42,'c':42}

    // functions
    _.zipObject(['a','b','c'], _.constant(42)) // {'a':42, 'b':42,'c':42}

**Comment by 92arpitgoyal** [comment]
@evilive3000 `_.zipObject(['a','b','c'], 42) // {'a':42, 'b':42,'c':42}` is not working but `_.zipObject(['a','b','c'], [42, 42, 42]) // {'a':42, 'b':42,'c':42}` is working, also this is the way it is mentioned in Docs, am I missing something ?

**Comment by wuliupo** [comment]
@jdalton, as your suggestions,
>```
_.zipObject(keys, _.map(keys, function() { }));
```

can we support,
```
_.zipObject(keys, function() { });
```

**Comment by BlueRaja** [comment]
Why was this closed?  Allowing `zipObject` to take a function or a constant is a _fantastic_ request!

That would help scale down our code a lot because in our code _(which mostly maps data from one service's format to another's)_ we are constantly mapping arrays of objects to key-value pairs.

**Comment by BlueRaja** [comment]
I've created https://github.com/lodash/lodash/issues/2718 which covers the above problem but many more as well

**Comment by xgqfrms-gildata** [comment]
https://stackoverflow.com/a/45687156/8202629
