### ISSUE TITLE
Module import lodash build

### ISSUE THREAD

**Issue by armaanahluwalia** [lodash/lodash#1262]
This is more of a question than an issue i suppose. I'm currently using some lodash modules in some of my files. I want a version of lodash that imports all the individual modules so that in my AMD ( requirejs ) setup my build will see that there is some shared usage of lodash modules and not build them twice. Currently main.js in lodash-amd is an already built version of lodash. 

Any thoughts on this would be appreciated. Thanks!

**Comment by jdalton** [comment]
We keep the monolithic build singular since it's just pulling in everything. You can create a tinydash or other object that holds your cherry-picked methods and import that.

**Comment by armaanahluwalia** [comment]
Fair enough. Just thought it might be useful to have as part of the repo since it should be a fairly common pattern for projects with a build step that want to require lodash.

**Comment by jdalton** [comment]
You can certainly do that (the cli supports it). For the common case though if you go monolithic stick with the monolithic build, if you cherry-pick keep cherry-picking.

**Comment by armaanahluwalia** [comment]
Just noticed that all the lodash-amd sub-modules are defined anonymously. This means that if two different packages are requiring their own versions of the lodash modules relatively the build wouldn't be able to recognize that they are in fact the same AFAIK.

I know i've seen it mentioned that the modules should register themselves under a lodash sub-namespace. This seems to make sense to me.

The reason that I'm coming across that a package would try to require modules relatively AKA ./node_modules/foo/foo is that this way there is no need to configure the require.config file with all dependencies.
