### ISSUE TITLE
Documentation for previous versions

### ISSUE THREAD

**Issue by ashclarke** [lodash/lodash#1263]
Hi John-David,

I was wondering if it would be possible for you to generate docs for historic minor versions. For example, a lot has been added between 3.5.0 and 3.9.3 so some things in the docs do not apply for these previous versions.

No worries if not, just a thought. I usually refer to the changelog, but this might not be obvious for some.

**Comment by d10** [comment]
There are links to previous versions of our documentation in the changelog (another the version number).

**Comment by ashclarke** [comment]
Ah right, so you can access *minor* version docs in the changelog but not
on the docs site?

**Comment by jdalton** [comment]
Yap, I think that's fine.
