### ISSUE TITLE
bindAll doesn't work with chaining

### ISSUE THREAD

**Issue by jerryorr** [lodash/lodash#1264]
The [docs](https://lodash.com/docs#_) state that bindAll is a chainable method, and I think it was at some point in time. However, this doesn't appear to be the case anymore. The following code:

```
var _ = require('lodash')

var A = function (val) {
	this.val = val
	_(this).bindAll('chained')
	_.bindAll(this, 'notchained')
}

A.prototype.chained = function () {
	return this.val
}

A.prototype.notchained = function () {
	return this.val
}

var a = new A('engage!')

console.log('a.chained(): ', a.chained())
console.log('a.notchained(): ', a.notchained())

console.log('a.chained.call(): ', a.chained.call())
console.log('a.notchained.call(): ', a.notchained.call())
```

Produces the following output:
```
a.chained():  engage!
a.notchained():  engage!
a.chained.call():  undefined
a.notchained.call():  engage!
```

 `_.bindAll(this, 'notchained')` is working as expected, but `_.bindAll(this, 'notchained')` is not.

**Comment by jdalton** [comment]
In v3 chaining execution is deferred until an implicit `value()` or explicit `value()` is requested.
