### ISSUE TITLE
npm no longer contains lodash.min.js

### ISSUE THREAD

**Issue by leon** [lodash/lodash#1267]
I'm using npm as my front end package manager, and have been using the /dist/lodash.min.js file for a long time.

Is it a bug or a feature? :P

**Comment by d10** [comment]
The file structure of the npm module changed; for now you can access the monolithic build via `lodash/index.js`.

**Comment by leon** [comment]
@d10 but not as a minified file.

The files seems to be available in the root of the project on github, so why can't we keep the /lodash.min.js and /lodash.js files around?

**Comment by jdalton** [comment]
This is by design. There are lots of ways to go about building, bundling, and minifying. If you're using npm as your front end then I'm sure you're familiar with webpack, browserify, and uglify. Use any combo of them to minify your source.

**Comment by leon** [comment]
I'm using gulp to concat my libraries, but I'd rather not minify it, since this can cause problems with settings and such.

Most other client side libraries supply both a minified ("compiled") version and a raw debug version.
It saves a lot of resources not having to minify every library for every dev iteration.

I'm guessing I'm not the only one that is missing the minified versions.

**Comment by jdalton** [comment]
Ya, you're scenario, taking the npm package and using it for the client side without cherry-picking, isn'r one of our primary targets. With the simplicity of minifiers these days I've put more time into my reply then it would take you to minify or bundle your third-party deps appropriately.

**Comment by sparty02** [comment]
> With the simplicity of minifiers these days I've put more time into my reply then it would take you to minify or bundle your third-party deps appropriately

This is unnecessarily condescending.

The fact remains that @leon has use case that, while you may not encourage, is nevertheless valid.  I would argue that there is a legit concern tied to minifying code you don't own.  Unless you are going to stop publishing the minified uber-build, it seems silly to stop including in the npm distro.
