### ISSUE TITLE
clearing cache for _.memoize question

### ISSUE THREAD

**Issue by hippich** [lodash/lodash#1269]
So I found I can clear cache by setting func.cache.__data__ to empty object, but not sure if this is appropriate. What is general recommendation on this? Should new .cache property be created, or it is appropriate just clear .cache.__data__?

**Comment by hippich** [comment]
Looking through WeakMap documentation on mozilla website I found that WeakMap implements .clear() method. If I make a PR with similar modification to the API, will it be considered?

**Comment by jdalton** [comment]
Clearing isn't enforced because devs can use a `WeakMap` which doesn't have `clear` and I wanted to keep our default interface small. If you'd like to clear caches I'd recommend using a Map (and its shim if needed) for the cache backing `_.memoize.Cache = Map`.
