### ISSUE TITLE
Wrap method call as callback

### ISSUE THREAD

**Issue by amiramw** [lodash/lodash#1271]
Hi,

Sometimes there is a need to work with a method with its context. For example if you have `a.b` you want to pass a function that executes `b` with `a` as its this.
Is there an elegant way of doing this with lodash?
I ended up writing this utility function:
```javascript
function wrapMethod (obj, sMethod) {
	return obj[sMethod].bind(obj);
}
```

Thanks

**Comment by amiramw** [comment]
I don't mind implementing it. Is that ok?

**Comment by jdalton** [comment]
Try [_.bindKey](https://lodash.com/docs#bindKey).
