### ISSUE TITLE
Using lodash functions in lodash.template module

### ISSUE THREAD

**Issue by ld0rman** [lodash/lodash#1272]
In an attempt to optimise build sizes, I'm only installing specific lodash modules from npm. I took [this project's usage](https://github.com/madebymany/sir-trevor-js/blob/master/src/lodash.js) as a starting point.

So, I make a file like so:

```js
// lodash_functions.js

exports.isEmpty = require('lodash.isempty');
exports.isFunction = require('lodash.isfunction');
exports.isObject = require('lodash.isobject');
exports.isString = require('lodash.isstring');
exports.isUndefined = require('lodash.isundefined');
exports.result = require('lodash.result');
exports.template = require('lodash.template');
exports.uniqueId = require('lodash.uniqueid');
exports.forEach = require('lodash.foreach');
```

And use it like so:

```js
// app.js

var _ = require('./lodash_functions.js');

var message = 'I can use lodash in a  modular way';

_.template('<p>{{message}}</p>', { message: message }); 
// above compiles to <p>I can use lodash in a modular way</p>

```

However, I can't use any of the other functions that I have exported to _ within my templates, e.g.

```js
// app.js

var _ =  require('./lodash_functions.js');

var items [ { message: 'foo' }, ... ] // array of objects

var template = _.template([
    '<div>',
      '<% _.forEach(items, function(item) { %>',
        '<span><%= item.message %></span>',
      '<% }); %>',
    '</div>'
].join('\n'));

var generated = template({ items: items }); // error; _.forEach is undefined

```

What do I have to do to import the function I need into the template ?

**Comment by d10** [comment]
Try the `imports` options:
```js
var template = _.template([
    '<div>',
      '<% _.forEach(items, function(item) { %>',
        '<span><%= item.message %></span>',
      '<% }); %>',
    '</div>'
].join('\n'), {
    'imports': {
        '_': _
    }
});
```
See the docs for [`_.template`](https://lodash.com/docs#template) for an example.

**Comment by ld0rman** [comment]
Thanks for pointing me in the right direction. Just for information, I couldn't use the 'imports' option exactly as you suggested, as any variables required in the template (in my example, 'items') would throw undefined errors.

```js

var template = _.template([
    '<div>',
      '<% _.forEach(items, function(item) { %>',
        '<span><%= item.message %></span>',
      '<% }); %>',
    '</div>'
].join('\n'), items, { // I needed to put items here, any way to avoid this?
    'imports': {
        '_': _
    }
});

Cheers

**Comment by d10** [comment]
Ah, I think you're using an older version of lodash. Since v3, the `_.template` function no longer supports the `data` argument. See the [changelog for v3](https://github.com/lodash/lodash/wiki/Changelog#v300).

**Comment by ld0rman** [comment]
Ah! You are indeed correct. Unfortunately I'm working off a fork so I'm not sure I'll be able to get just use v3 without breaking something. Thanks again :+1:
