### ISSUE TITLE
_.method should maybe throw Error when method not found on object

### ISSUE THREAD

**Issue by zaboco** [lodash/lodash#1273]
Right now, `_.method` returns `undefined` when the target object does not have the method. 

I ran into many bugs because of this, which would have been caught earlier if an `Error` would have been thrown.

And, if returning `undefined` is the intended behaviour, maybe a 'safe' version could be added

**Comment by Dashed** [comment]
Pretty sure that's a bug according to docs: https://lodash.com/docs#functions 

Should probably return empty array instead.

**Comment by jdalton** [comment]
@zaboco Like much of our API this is forgiving for missing properties.

@Dashed This is for `_.method` not the `_.methods` alias (that alias will be dropped in v4).

**Comment by zaboco** [comment]
@jdalton 
> Like much of our API this is forgiving for missing properties.

Yes, I saw that, and that is generally a good thing. I was just looking for a way to handle the case when a method is not found, so I can throw an Error myself, because my API assumed that the method existed. And, to make things harder, in my use case I had a chain of methods that where composed, something like:
```
var composedTransformer = _.flow(_.method('a'), _.method('b'), _.method('c'))
var result = composedTransformer(target) // assuming target had chainable methods a, b, c 
```
In this case if any of `a`, `b` and `c` did not exist, the `result` will be `undefined`, and I didn't find a way to tell which method (if any) is missing, or maybe I forgot to make one of them chainable.
