### ISSUE TITLE
_.merge() array with string

### ISSUE THREAD

**Issue by guyellis** [lodash/lodash#1274]
Is this expected behavior?

Below results from Node REPL using Node 0.10.38 and lodash 3.9.3

Also `var ld = require('lodash')`

```
> ld.merge({ foo: 'bar' }, { foo: ['bar', 'baz'] })
{ foo: [ 'bar', 'baz', 'r' ] }
```

**Comment by jdalton** [comment]
When types don't match it can't merge so it overwrites. You can customize the merge behavior by passing `customizer` callback.
