### ISSUE TITLE
should _.wrap copy the own properties of input?

### ISSUE THREAD

**Issue by spalger** [lodash/lodash#1277]
While checking out lodash-migrate I noticed that `_.memoize.Cache` was dropped because:

```js
_.memoize = _.wrap(_.memoize, function () {
  ...
})
```

I am of the opinion that `_.wrap` should assign all of the own properties of the value to the result, but this is quite a bit slower: http://jsperf.com/assign-after-wrap

What do you think?

**Comment by jdalton** [comment]
Wrapping is wrapping I don't think we need to try to assign the own properties of the wrapped value. lodash-migrate was intended for v2 which didn't have `_.memoize.Cache` to v3. You should file an issue with lodash-migrate.
