### ISSUE TITLE
Invoke an array of functions

### ISSUE THREAD

**Issue by tusharmath** [lodash/lodash#1279]
There is no easy way to do something as simple as - 
```javascript
//Invoke multiple functions with the same set of arguments
_.invoke([func1, func2, func3], 1,2,3,4,5);
//Wanting it to execute like - func1(1,2,3,4,5) & func2(1,2,3,4,5) and so on...

```

Currently it doesn't invoke the functions, instead I have to write a hacky iteratee.

```javascript
function () {
        return this.apply(null, arguments);
    }
```

**Comment by jdalton** [comment]
```js
_.invoke([func1, func2, func3], _.call, null, 1,2,3,4,5);
```

**Comment by tusharmath** [comment]
Its not documented ?

**Comment by jdalton** [comment]
`_.invoke` is documented to accept a function for `methodName`. The `_.call` is nothing special its just the `.call` that exists on any other function.

**Comment by tusharmath** [comment]
Got it @jdalton you are amazing!

**Comment by IvanGoncharov** [comment]
If someone referred here by Google or Github search.
In lodash 4.x it should be:
```js
_.invokeMap([func1, func2, func3], _.call, null, 1,2,3,4,5);
```

**Comment by lohfu** [comment]
wouldn't it be easier just to `[ fnc, fnc2, fnc3, fnc4 ].forEach(fnc => fnc(1, 2, 3, 4))`?

**Comment by ChuckkNorris** [comment]
You could also just directly call the functions using `_.forEach` to quickly daisy chain them:

```
   const exampleFn = () => _.forEach([doThis(a), thenDoThis(b)]);
```
