### ISSUE TITLE
Defer calls to a curried function n times.

### ISSUE THREAD

**Issue by tusharmath** [lodash/lodash#1281]
Problem: Is there a way where I can curry all the parameters yet defer the function call one (or n) more time(s)?
Like:

```javascript
function x(a,b,c) {
    return a+b+c;
}
var deferredX = _.currySuperCool(x), 4);
deferredX(1,2)(3)()(); //this returns the sum, without having to pass arguments
```

**Comment by jdalton** [comment]
No there isn't. Once you satisfy the arity of the curried function it will invoke `x`.

**Comment by tusharmath** [comment]
Could it be a feature, may be?

**Comment by jdalton** [comment]
Naw, once arity is satisfied `func` is invoked. That's currying.
