### ISSUE TITLE
API doc generation

### ISSUE THREAD

**Issue by kengz** [lodash/lodash#1282]
This is a question for the author, not an issue - my apology.

How did you generate your [API documentation](https://lodash.com/docs)? Was it by hand? I looked into the HTML source and found no sign of a template name. Honestly I think this way of development – coding and annotating with code examples and doc, which then compile automatically to this HTML – is great.

**Comment by jdalton** [comment]
Hi @kengz! See https://github.com/lodash/lodash/issues/1258.

**Comment by kengz** [comment]
thank you.
