### ISSUE TITLE
_.find & _.findIndex return first element and 0 index respectively, for undefined predicate value

### ISSUE THREAD

**Issue by bimal1331** [lodash/lodash#1284]
Eg.
var keyVal = undefined;
var collection = [{id:'a', val:'ds'}, {id:'b', val:'sd'}];
_.findIndex(collection, 'id', keyVal) returns 0
_.find(collection, 'id', undefined) returns 1st item at 0th index
Is this a bug or did I use it wrong?

**Comment by jdalton** [comment]
This is by design. The `matchesProperty` shorthand won't work with `undefined`. You'll have to try the `matches` shorthand or the `_.matchesProperty` long form.
