### ISSUE TITLE
_.includes not to be found (3.9.3)

### ISSUE THREAD

**Issue by DarwinsBuddy** [lodash/lodash#1285]
Hi guys,

just wanted to point out that I had an issue reg. your _.contains/_.includes function.

In the docs (https://lodash.com/docs#includes) it is mentioned that includes is an alias for contains, but
_.includes can not be found.
Although _.include (without an 's') can be found.
Either this is an error in the docs or in the release.

**Comment by jdalton** [comment]
Just checked, it's there in 3.9.3.
