### ISSUE TITLE
array operations on specific index bounds

### ISSUE THREAD

**Issue by ghuser** [lodash/lodash#1286]
For operations like `_.dropWhile()` it is impossible to apply them to an array only on a specific index range.
We first need to split the array into 3, apply the operation and then concat it again.

I believe it would be useful to have a wrapper that would execute the underlying function on a specific index range, and then it would return the full array (modified). 
I believe somehow this could also be extended to support applying operations on specific properties of objects.
e.g (I know the code is in not so much lodash-oriented, but its an example)

    function rangeExec(func, from, to){
        return function(arr){
    
            var arr1 = arr.slice(0, from);
            var arr2 = arr.slice(from, to);
            var arr3 = arr.slice(to);
                         
            return arr1.concat(func(arr2).concat(arr3));
        }
    }

**Comment by jdalton** [comment]
Thanks @ghuser, this is an interesting idea. I think we'll hold off until there's more demand. However, feel free to experiment with this as a mixin.

**Comment by megawac** [comment]
+1 this sounds useful
