### ISSUE TITLE
Performance of arrayFilter

### ISSUE THREAD

**Issue by arendjr** [lodash/lodash#1287]
While reading the source of the `arrayFilter()` method, I noticed how you're tracking the `resIndex` yourself and then assigning the elements in the result array by index. This made me think, why not simply use the `Array.prototype.push()` method? I figured the answer might be in the performance, so I created a jsperf to compare the two variations: http://jsperf.com/assign-by-index-vs-push

I ran the results on Chrome 43, Firefox 37, Safari 8 and IE 11*. The results are that using `push()` is slightly faster on Chrome, slightly slower on Safari and about equal on IE. The outlier is Firefox for which using `push()` is more than twice as fast.

For this reason I'd say it's better to use `push()` in the `arrayFilter()` method.

Finally, checking the source for `baseFilter()` I see you're using `push()` there as well. So just for consistency's sake I'd also say `push()` is the way to go.

*) IE11 is reported by jsperf as "Other", maybe because I was running it inside a VM.

**Comment by arendjr** [comment]
PS.: I've created a Pull Request for this specific case, but searching for `resIndex` actually shows that the same pattern occurs in many places.

**Comment by d10** [comment]
I can't quite remember, but I think there's a major slowdown on Mobile Safari for this. We did use `Array#push` in the past though.

**Comment by arendjr** [comment]
Just ran the tests on my iPhone (iOS 7) and the performance seems to be about equal (see the linked jsperf). I have to admit, I ran the test 4 times and the first time there was a 33% slowdown when using `push()`, but with the other 3 runs there was barely a difference.

**Comment by arendjr** [comment]
And checked on my colleague's iPhone (iOS 8) and can confirm there using `push()` is consistently slower by about 30% (to the point that using `push()` seems slightly slower on his device than on mine, even though his is an iPhone 5S and mine is a 4S).

**Comment by jdalton** [comment]
Thanks but I'm not interested in mucking with this at this time.
