### ISSUE TITLE
When third debounce parameter is number use it as maxWait

### ISSUE THREAD

**Issue by shakiba** [lodash/lodash#1289]
I think it would be great to use third `debounce(func, wait, options)` parameter as `maxWait` option when it is a `number`, for example `debounce(func, 200, 1000)`.

I can submit a pull request if you are interested.

**Comment by jdalton** [comment]
Hi @shakiba! I want to encourage options object use here. We support passing a boolean as the third param for `leading` because it existed before the options object was added.
