### ISSUE TITLE
_.branch: _.pick and _.omit simultaneously

### ISSUE THREAD

**Issue by dlindenkreuz** [lodash/lodash#1291]
Since I haven't seen this functionality yet, I suggest adding some kind of `_.branch` function that returns an array with two objects — one containing the `pick`ed, the other containing the `omit`ted properties.

This is currently only possible (and please forgive me if I missed something) by doing something like this and thus iterating over object keys twice:

```js
var obj = {a: 0, b: 1, c: 2, d: 'foo', e: 'bar'};

var stringsOnly = _.pick(obj, _.isString);
// {d: 'foo', e: 'bar'}

var otherThanStrings = _.omit(obj, _.isString)
// {a: 0, b: 1, c: 2}
```

Having a function that combines both operations in one single iteration over the object's keys might be more efficient when dealing with huge objects.

A `[picked, omitted]` return value seems pretty unelegant, maybe you guys have some nice ideas to chip in.

**Comment by megawac** [comment]
So you're requesting some sort of `partitionObject`?

**Comment by dlindenkreuz** [comment]
Exactly. Didn't even think of `partition` for arrays in the first place, but yes, that's totally what I'm talking about.

**Comment by jdalton** [comment]
Thanks for the suggestion @dlindenkreuz! I'll keep an eye on the demand for this. Until then you can create a mixin to kick the tires a bit.

**Comment by ghuser** [comment]
+1 for this

**Comment by ghuser** [comment]
I propose that  _.branch could accept a collection of functions and return an array containing collections of elements. Each of the functions would decide whether to add the iterated element to the corresponding collection. 

The functions could be passed an extra boolean informing whether the iterated element has already been picked by one of the previous functions. This way we would optionally be able to add the unmatched elements to the last collection.

**Comment by YourDeveloperFriend** [comment]
+1 for me as well. I keep running into this need, and I search through the docs to see if I missed it last time I needed it.

**Comment by akozhemiakin** [comment]
+1. Would be nice to have it.

**Comment by jordanarseno** [comment]
+1 for this!

**Comment by tuval10** [comment]
+1 for this

also something of that sort for pickBy+ omitBy

**Comment by svey** [comment]
+1 for pick + omit

**Comment by levithomason** [comment]
Hey folks, you need to use the actual 👍 reaction on the issue description.  Issues are sorted by popularity according to the number of votes there.  Your comments here, unfortunately, are not counted but they do spam the poor maintainer.
