### ISSUE TITLE
Support native ES6 Iterable protocol [Symbol.iterator]

### ISSUE THREAD

**Issue by fengb** [lodash/lodash#1292]
This would be a pretty nice stepping stone into ES6 compatibility. Reverse of #737.

I'm not too familiar with the code but here's my high level take:
* Define only if `Symbol.iterator` is defined
* `lodash.prototype[Symbol.iterator]` returns a stateful object with i=0
* `next()` will return `{ value: at(i++), done: false }` or `{ value: null, done: true }`

I'm willing to implement this if you feel like this would be a useful addition.

**Comment by jdalton** [comment]
Hi @fengb! I'm not considering it at the moment but feel free to experiment with this.
