### ISSUE TITLE
improve _.inRange to reflect proper containment.

### ISSUE THREAD

**Issue by kengz** [lodash/lodash#1299]
Currently lodash's `_.inRange` returns `false` for this statement: `0 < 2.9 < 3`, i.e. `_.inRange(0, 3, 2.9)`.
It'd make the function more useful when it can operate on non-Integer values.

An easy and mathematically sound fix would be to make it `left ≤ x ≤ right`, that is to make it a closed interval, which will hold true for arbitrarily (machine precision) close value like 2.99999999999; like so:
```
inRange: function(left, right, x) {
    return left - 1 < x && x < right + 1;
}
```

**Comment by jdalton** [comment]
I think you're using the method incorrectly. The argument signature for `_.inRange` is `inRange(value, start, end)`.

**Comment by kengz** [comment]
ahh my bad. Sorry.
