### ISSUE TITLE
_.findRandom()

### ISSUE THREAD

**Issue by dbeckwith** [lodash/lodash#1301]
Suggestion for a new method: `_.findRandom(collection, [predicate=_.identity], [thisArg])`. Has the same signature as `_.find()`, but instead of finding always the first element that matches, it finds a random element that matches. A simple example implementation (not necessarily the best) would be:
```javascript
_.findRandom = function(collection, predicate, thisArg) {
  return _.sample(_.filter(collection, predicate, thisArg));
};

var list = [ 1, 2, 3, 4, 5, 6 ];
var pred = function(x) { return x > 3; };
_.findRandom(list, pred); // 5
_.findRandom(list, pred); // 6
_.findRandom(list, pred); // 6
_.findRandom(list, pred); // 4
_.findRandom(list, pred); // 6
```
I think it would be a nice variant to `find` that doesn't always return the same element when multiple elements match the predicate. The method name could be different as well, just the first thing I thought of.
I can submit a PR later for this unless someone else wants to do it.

**Comment by jdalton** [comment]
Thanks @dbeckwith! I think this kind of method would work great as a mixin.
