### ISSUE TITLE
Feature request: AtLeast, AtMost

### ISSUE THREAD

**Issue by falafflepotatoe** [lodash/lodash#1302]
heres an easy one, i always hate typing this one out:

 - atLeast (cnt, value, array) returns bool
 - atMost (cnt, value, array)  returns bool

example:

    animals = [ 'cat','dog','bear','cat' ]
    if (_atLeast(2, 'cat', animals))
      feedcats()

replaces

    animals = ['cat','dog','bear','cat']
    cnt = 0;
    for (animal of animals){
      if (animal == 'cat'){
        cnt += 1
      }
    }
    if (cnt > 2){
         feedcats()
    }

**Comment by jdalton** [comment]
I think this is perfect for a [mixin](https://lodash.com/docs#mixin).

Related to https://github.com/jashkenas/underscore/issues/2223.

**Comment by StreetStrider** [comment]
I think implementing a `count` is a good basis for this mixins. #702
