### ISSUE TITLE
Only set difference is supported

### ISSUE THREAD

**Issue by jiaweihli** [lodash/lodash#1304]
`_.difference` does set difference, in that it removes all occurrences of the other elements provided.  This is oftentimes (and I would argue usually) not what you want, since you can achieve the current behavior by calling `_.uniq` on the first array, but you can't achieve 'exact difference' in a clean way as is.

e.g. With set difference:
```javascript
_.difference([1, 1, 2, 3], [1])
Array [ 2, 3 ]
```

'Exact difference' would yield `[1, 2, 3]` here.

`_.without`, etc. suffer from the same issues.

**Comment by jdalton** [comment]
Yep, this is by design. Our methods (difference, intersection, union, xor) are based on set operations.

**Comment by jiaweihli** [comment]
A use case set difference makes very awkward is finding all the duplicates in an array:

```javascript
_(array)
  .countBy()
  .filter(function(count) { return count > 1; })
  .keys()
  .value()
```

With exact difference, this could be expressed in a more straightforward manner:

```javascript
_.difference(
  array,
  _.unique(array)
)
```

Do you have any plans to support exact difference in the future (whether through an option on `_.difference`, or another method entirely)?

Also, can you explain the rationale for basing the methods on set operations?  Given:

>  This is oftentimes (and I would argue usually) not what you want, since you can achieve the current behavior by calling _.uniq on the first array, but you can't achieve 'exact difference' in a clean way as is.

it seems to be less expressive than the alternative.

**Comment by jdalton** [comment]
> Do you have any plans to support exact difference in the future (whether through an option on `_.difference`, or another method entirely)?

No plans at the moment.

> Also, can you explain the rationale for basing the methods on set operations?

It's how it's historically been done in Underscore/Lodash.

> it seems to be less expressive than the alternative.

I haven't needed the alternative yet, but I'll keep an eye out on demand for this.
