### ISSUE TITLE
Support hint param for sortedIndex

### ISSUE THREAD

**Issue by dbkaplun** [lodash/lodash#1306]
[As it is now](https://github.com/lodash/lodash/blob/master/lodash.js#L2767), the first index checked is naturally the midpoint of the array. This is a good default but sometimes the programmer knows some information about a likely insertion position for the value. Would be great if lodash supported an additional `hint` param!

**Comment by jdalton** [comment]
Hi @dbkaplun! Ya it could be tweaked but I think it's fine the way it is. Binary search is already pretty fast I don't see the benefit it tweaking it further.

**Comment by dbkaplun** [comment]
Absolutely, it's fine the way it is! Sorry if it sounded like I was complaining. I just think it could be improved. My particular use case is inserting many values that are close together. According to my benchmarks, using `sortedIndex` is slower than `push`ing then `sort`ing. If I could use the previous index as an initial parameter, it would make things much faster!
