### ISSUE TITLE
Legal/licensing requirements for bundling

### ISSUE THREAD

**Issue by milesj** [lodash/lodash#1307]
I'm currently in the process of rewriting my Toolkit project to version 3.0. This version will be dropping jQuery and will be entirely written in ES6. I'm at a crossroad where a good portion of functionality can be solved by lodash, and was wondering what legal/licensing requirements there are if I bundle parts of lodash in the "production" ready Toolkit code, found here: https://github.com/titon/toolkit/tree/3.0/dist

I'm assuming that I would simply have to place the license in the file. If there's anything else let me know. Or if you guys are against this approach as well. Full credit will be given throughout.

**Comment by jdalton** [comment]
Awesome@milesj!

Lodash is available under [an MIT license](https://github.com/lodash/lodash/blob/master/LICENSE). It looks like you're MIT too so I can see just adding a mention to the copyright headers there (similar to how we've added Underscore to ours). If you want you can always run it by when you're done and I can give feedback.

**Comment by milesj** [comment]
Sounds great, thanks for the quick reply!
