### ISSUE TITLE
Surprising output from map based on array ordering

### ISSUE THREAD

**Issue by mwcz** [lodash/lodash#1309]
I'm kind of stumped:

    _.map( ['B', 'A'], _.partial(_.startsWith, 'BETA'))
    Array [ true, false ] // yes, 'BETA' begins with 'B' but not with 'A'

    _.map( ['A', 'B'], _.partial(_.startsWith, 'BETA'))
    Array [ false, false ] // wuh?

The idea I'm trying to capture is that with a single ("BETA"), I want to check an array and see if "BETA" begins with any of the strings in that array.  I was using `any` at first, but when it was acting strange, I decided to try `map` instead, to help debug.

What am I missing?

**Comment by mwcz** [comment]
I tried out this same thing in underscore, just to validate my thinking.

    function startsWith(str, tar) { str.indexOf(tar) === 0 }

    _.map( ['A', 'B'], _.partial(startsWith, 'BETA'))
    Array [ false, true ]

    _.map( ['B', 'A'], _.partial(startsWith, 'BETA'))
    Array [ true, false ]

**Comment by mwcz** [comment]
Ah, I found my problem.  It's the extra arguments to `startsWith` that I didn't consider.

    function startsWith(string, target, position) {}

`map` and `any` pass value, index, and collection into the predicate, so the index was being passed into my startsWith partial and interpreted as position.

**Comment by jdalton** [comment]
You can use `_.ary(_.startsWith, 1)` to cap its accepted arguments to one.
