### ISSUE TITLE
_.escapeRegExp modifies regular digits

### ISSUE THREAD

**Issue by joshwcomeau** [lodash/lodash#1310]
It looks like the changes in https://github.com/lodash/lodash/commit/10c2232c398e095ff52f2306df08f0a0e0350285 broke a simple validator a co-worker built - essentially we were using `_.escapeRegExp` to remove special chars before searching for email addresses and phone numbers. We take the search term and make a RegExp with it, as an easy way to match substrings.

Running the string `"555-5555"` through `_.escapeRegExp` returns `"\x3555-5555"`. Is this desired behaviour? Are we using the method for a purpose not intended?

**Comment by jdalton** [comment]
It is intended as numbers could effect a capture group references. For example `"a(b)\1" + _.escape('555-5555')`. If that didn't escape the leading digit it would turn the reference into `\1555` which is incorrect. The regexp values produced by `_.escapeRegExp` should still make a valid match:
```js
RegExp(_.escapeRegExp('555-5555')).test('555-5555');
// => true
```

Can you explain a bit more about the issue the changed caused I am testing the waters on a proposed ECMA [RegExp.escape](https://github.com/benjamingr/RegExp.escape) implementation.

**Comment by joshwcomeau** [comment]
Ahh that makes a lot of sense. Thanks!

The issue the change caused was how we were testing the string being escaped. Essentially we have a search parameter and we need to figure out if that search term is a phone number, name, email address or twitter handle. So within a conditional block we have this:

```
search = req.query.s # This string is what gets escaped with the lodash method.
search_regex = new RegExp(search, 'i')

if search.indexOf('@') > 0
  query.email = { $regex: search_regex }
else if /^[\d+-\s]{4,}$/.test(search)
  query.phoneNumber = { $regex: search_regex }
else
  query.$or = [
    { email: { $regex: search_regex }}
    { firstName: { $regex: search_regex }}
    { lastName: { $regex: search_regex }}
    { _id: search }
  ]
```
(it's coffeescript, if that wasn't obvious).

So what was happening was that first 'else' wasn't getting triggered since we didn't allow for control characters, so it was getting passed down to the catch-all 'else' which wasn't searching for phone numbers.

It's a very easy thing to fix, but it took me a while to pin down the problem. What you said makes total sense and I think this is ultimately a good change, but yeah I think it would help people if the docs contained info about this new change =)

Thanks again for your time!
-Josh
