### ISSUE TITLE
Question: How to use curryRight as a callback?

### ISSUE THREAD

**Issue by JemiloII** [lodash/lodash#1312]
I'm trying to do a curryRight in a map.

```js
    var collection = [
        {a:1, b:2, c:3},
        {a:4, b:5, c:6, d: 7, e: 8},
        {a:9, b:10, c:11, d: 12}
    ]
    var keys = ['a', 'b', 'c'];
    var hasKeys = _.map(keys, _.curryRight(_.has))
    _.every(collection, _.curryRight(_.every)(hasKeys))
```
I want the map to return an array of curried _.has functions that are just waiting for an object

**Comment by jdalton** [comment]
For this you'd really want to check out [lodash-fp](https://www.npmjs.com/package/lodash-fp) for auto-curried iteratee-first data-last methods. It also caps arguments provided to callbacks like `map` to one argument which makes composition easy.
```js
var hasKeys = _.map(_.has, keys);

_.every(_.every(_, collection), hasKeys);
// or
_.every(_, hasKeys)(_.every(_, collection));
```

**Comment by JemiloII** [comment]
thanks

**Comment by JemiloII** [comment]
Would it be beneficial if we added the curried versions to regular lodash as _.cmap, _.cetc?

this way, one lib will do i all.

**Comment by jdalton** [comment]
> Would it be beneficial if we added the curried versions to regular lodash as _.cmap, _.cetc?

lodash-fp is lodash with a thin wrapper over its methods. I think they're different enough to keep them separate packages.

**Comment by JemiloII** [comment]
Alright, I'll make an installer function for lodash-fp later. Something like require('lodash-fp).installTo(), with two optional params, first being the install variable of lodash and second being the prefix to lodash-fp functions.

**Comment by jdalton** [comment]
lodash-fp has a convert module: `require('lodash-fp/convert')` which does the heavy lifting on converting methods.

**Comment by JemiloII** [comment]
so if I do `require('lodash-fp/convert')('chas', _.has)` it will make an auto curried version as _.chas?

**Comment by jdalton** [comment]
It's not 100% polished for methods like `map` as it doesn't wrap the callback creation when passed individual methods (it handles it when passed `lodash` itself).
```js
var convert = require('lodash-fp/convert');
var _ = _.runInContext();
_.chas = convert('has', _.has);
```

**Comment by jdalton** [comment]
I'll polish the `convert` method tonight so it can tackle all the things.

**Comment by JemiloII** [comment]
takes a bunch!
