### ISSUE TITLE
_.push or _.append

### ISSUE THREAD

**Issue by msvbg** [lodash/lodash#1314]
This is possibly of greater interest to [lodash-fp](https://www.npmjs.com/package/lodash-fp), but a function that appends an element to an array and returns the array would be neat. For instance:

```js
let collection = [[1, 2], [3, 4]];
_.map(_.push(9))(collection); // [[1, 2, 9], [3, 4, 9]]
```

Thoughts?

**Comment by jdalton** [comment]
These methods wouldn't mutate the array and would instead return a new array, correct?

**Comment by msvbg** [comment]
Hm, the way I presented it would imply an immutable/copying operation, which is not bad but maybe outside the scope of lodash? When I opened the issue I wanted to have a mutating `_.push` in a promise chain, like so: `f().then(_.push(10)).then(g)`.

**Comment by jdalton** [comment]
> When I opened the issue I wanted to have a mutating `_.push` in a promise chain, like so: `f().then(_.push(10)).then(g)`.

As you mentioned earlier the `_.push` usage in the example would be better suited for [lodash-fp](https://www.npmjs.com/package/lodash-fp).

We don't have a `push` method on `_` at the moment however there is a mapping of `Array#push` on the chaining syntax.

I wouldn't be against a non-mutating form of `_.append` which would then lend to making an exposed `_.concat`.

**Comment by msvbg** [comment]
Okay, thanks for the info!

**Comment by andrei-cocorean** [comment]
@jdalton Are you still interested in a non-mutating `_.append`? I can create a pull request.

**Comment by jdalton** [comment]
@andrei-cocorean No need. Just upvote the initial comment as others have done.

**Comment by anton6** [comment]
is lodash/fp going to have immutable push?

**Comment by HermanBovens** [comment]
@anton6  isn't immutable push just `const newCharacters = [ ...characters, 'Luke' ]` ?

**Comment by iddan** [comment]
Yeah, it will be nice to have a auto-curried version of it.

```javascript 
const append = curry((items, array) => [...array, ...items])
```

**Comment by majthehero** [comment]
Upvote for an immutable .append()

**Comment by olivierlacan** [comment]
I'm surprised there hasn't been a stronger... push for this. 😎

**Comment by iddan** [comment]
Can we change this into a GitHub discussion?

**Comment by cyrus-za** [comment]
Why is there no strong `push` for this? I'd love it if someone could `append` this method to the lodash/fp library

**Comment by rebelspirit** [comment]
<img width="1322" alt="Снимок экрана 2021-09-27 в 17 29 48" src="https://user-images.githubusercontent.com/30700954/134928790-a5793c8d-59dc-4323-99ec-a4e3a01aa51a.png">
