### ISSUE TITLE
Support array push notation in _.set

### ISSUE THREAD

**Issue by DylanPiercey** [lodash/lodash#1315]
Currently when using set it will support the computed property notation so that I can go

```javascript
_.set({}, "a[b][c]", 1)
// -> { a: { b: { c: 1 } } }
```

This works great for turning a urlencoded form's input name into an object however it would be nice if the "push" notation was also valid (currently it does nothing).

By that I mean:

```javascript
_.set({ a: [1] }, "a[]", 2)
// -> { a: [1, 2] }

// currently -> { a: 2 }
```

Is this possible? It would be pretty handy.

**Comment by jdalton** [comment]
I can dig it, also negative index to get the last element. Do you want to try your hand at a pull request.

**Comment by DylanPiercey** [comment]
I can attempt it later today - not super familiar with the lodash source but i'll post back here if I can't get it working properly.

**Comment by jdalton** [comment]
Things to consider which may put a damper on this is what happens when the value you're applying this to is not an array?

In [previous issues](https://github.com/lodash/lodash/issues/1145#issuecomment-94345635) I've punted for just doing:
```js
_.get(object, path).push(value)
```

**Comment by DylanPiercey** [comment]
@jdalton - Not sure if it's what we want, but when QS parses forms with something like

```javascript
a[] = 1
a[test] = 2
a[test2] = 3
a[] = 4
```

It simply add's incremental indexes to the object so that that psuedo form becomes:

```javascript
{
  "a": {
    "0": "1",
    "1": "4",
    "test": "2",
    "test2": "3"
  }
}
```

IMO: This is what I would expect.

**Comment by jdalton** [comment]
Ah nice. Ok.

**Comment by DylanPiercey** [comment]
@jdalton is it okay if array paths with empty strings also act as a push operation?

```javascript
_.set({}, ["a", ""], 1)
// -> { a: [1] }
```

It would be consistent with the idea that [] is just an empty path.

**Comment by jdalton** [comment]
At the moment empty strings are considered a key of an empty string which is valid. Let's keep the push syntax to the `[]`.

**Comment by jdalton** [comment]
And with that the problem of consistent behavior across path types rears up. I think we'll punt on this for now.

**Comment by DylanPiercey** [comment]
Alrighty. Don't have time to finish my PR atm anyway.

Thinking it over again though it makes the most sense to simple have [] act as push/pop. I think merging this with negative indexes and empty strings makes it more than it is.

**Comment by jdalton** [comment]
> Thinking it over again though it makes the most sense to simple have `[]` act as push/pop

Ya the problem is `[]` can't be represented in the array form.

**Comment by DylanPiercey** [comment]
> Ya the problem is [] can't be represented in the array form.

Not quite sure what you mean by array form?

**Comment by atrauzzi** [comment]
Would like to see this supported as I need to be able to push values onto an array at a specific key while iterating.

**Comment by mk-pmb** [comment]
How would we assign to the property whose key is the empty string?

@atrauzzi , can you provide example code of how you'd use _.push if it had the feature, doing something that isn't easy at the moment?

**Comment by atrauzzi** [comment]
Assuming this usage:
```
_.push(myData, ["go", "here"], 42);
```

...and this data:
```
const myData = {
};


```

I would get:
```
{
    go: {
        here: [
            42,
        ]
    }
}
```

...and if my data was this:
```
const myData = {
    go: {
        here: [
            2112,
        ]
    }
};
```

I would get:
```
{
    go: {
        here: [
            2112,
            42,
        ]
    }
}
```

**Comment by c-dante** [comment]
Why not use a getOr then? I guess having to 'set' each time is annoying, but you'd be doing that implicitly with push anyway, huh?

```
const myData = {};
for (let i = 0; i < 10; i ++){
  const path = `go.here_${i % 3}`;
  fp.set(
    path,
    fp.getOr([], path, myData).push(i)
    myData
  )
}
```

**Comment by atrauzzi** [comment]
Do you like reading that?

**Comment by c-dante** [comment]
What?

`pushAt(10, 'my.path.here', myData)`?

Yeah that looks fine. And almost literally what you wrote at the top.

**Comment by atrauzzi** [comment]
Right, but you're basically just telling me to author my own method.  The suggestion here is to get something like that included in lodash.

I know that I can write my own.

**Comment by mk-pmb** [comment]
With `getoraddkey-simple` (my proposal for #2288), code would be:

```javascript
goak(myData, ["go", "here"], '[]').push(42);
```
