### ISSUE TITLE
_.set with numeric object keys

### ISSUE THREAD

**Issue by albertywu** [lodash/lodash#1316]
_.set(x, '1.2', 'foo') doesn't return the result I'd expect.

I would have expected the following result:
```javascript
x = {
  "1": {
    "2": "foo"
  }
}
```

Instead I get:
```javascript
x = {
  "1": [
     undefined,
     undefined,
    "foo"
  ]
}
```

Is there any way I can specify numeric Object keys in the setter string?

**Comment by megawac** [comment]
Set the `1` property before calling set. `_.set({1: {}}, '1.2', 'foo')`

**Comment by jridgewell** [comment]
When the property doesn't exists, and the key is numeric, it [creates an array instead of an object](https://github.com/lodash/lodash/blob/7c3e5332e79a8eddfe72fc832d919d7ede4a799c/lodash.src.js#L10186).

**Comment by bcherny** [comment]
the current behavior doesn't seem consistent to me.

```js
_.set({}, 1, 2)         // { 1: 2 }
_.set({}, '1.2', 3)     // { 1: [undef, undef, 3]}
_.set({}, '1.2.3', 4)   // { 1: [undef, undef, [undef, undef, undef, 4]]}
```

specifically, the top-level property set to an object, while inner properties are arrays. this, however, behaves as i would expect, since i'm specifically asking for arrays back:

```js
_.set({}, 1, 2)         // { 1: 2 }
_.set({}, '1[2]', 3)    // { 1: [undef, undef, 3]}
_.set({}, '1[2][3]', 4) // { 1: [undef, undef, [undef, undef, undef, 4]]}
```

a more consistent behavior for the original case would be:

```js
_.set({}, 1, 2)         // { 1: 2 }
_.set({}, '1.2', 3)     // { 1: { 2: 3 }}
_.set({}, '1.2.3', 4)   // { 1: { 2: { 3: 4 }}}
```

**Comment by albertywu** [comment]
:+1: @bcherny

**Comment by jdalton** [comment]
The top level is set to whatever value you provide. It's not going to replace a provided object with an array.

I'd like to avoid forking behavior based on dots of brackets. The common case for indexes is arrays so I think the assumption is fine. All of this is sugar after all so worst case you do it long form for your needs.

**Comment by bcherny** [comment]
i like the idea of being explicit about what you want (`.` vs. `[]`), rather than implicitly duck typing based on the type of key. it's a matter of taste, but it would be great to support both array and object use cases.

**Comment by jdalton** [comment]
Brackets are valid object notation. I rather keep it simple. My hunch is that numeric keys are used for arrays in the majority of cases. I rather not complicate the property syntax with dot and bracket by adding additional meaning here.

**Comment by bcherny** [comment]
Ok, sounds reasonable to me.

**Comment by wyantb** [comment]
Could something be put into the documentation about this, then?  Even simply amending the examples to show that `.#` will produce an array would suffice.  I assumed the behavior that @bcherny is describing (where setting with `key.3` would produce an object, and `key[3]` would produce an object).

**Comment by jdalton** [comment]
Stop creating objects with numeric keys folks ;)

**Comment by bcherny** [comment]
@jdalton https://en.m.wikipedia.org/wiki/Sparse_array :)
