### ISSUE TITLE
_.sortByOrder documentation is wrong I think?

### ISSUE THREAD

**Issue by dkmooers** [lodash/lodash#1318]
https://lodash.com/docs#sortByOrder

Explanation says that orders should be specified by "asc" or "desc", but the algorithm expects boolean values. Does not work with "asc" or "desc".

**Comment by 19379** [comment]
Are you running the latest version? That feature was only added in v3.10.0 on June 30th.

**Comment by dkmooers** [comment]
Ah, I see. I'm using a custom build of 3.9.3 via Meteor (stevezhu/lodash):

https://github.com/stevezhu/meteor-lodash/

... which only accepts boolean orders in compareMultiple(). It was a little confusing b/c the current API docs (3.10.0) still say that sortByOrder > orders expects Boolean values (but the text explanation says to use "asc" or "desc").

Either way, got it working, thanks!

**Comment by rahatarmanahmed** [comment]
The documentation still says it expects a `boolean[]` but the examples use `'asc'` and `'desc'`. It should be updated to be more consistent with what lodash supports now.

**Comment by dkmooers** [comment]
+1 @rahatarmanahmed thanks, that's what I was trying to get across earlier.

**Comment by jdalton** [comment]
I've corrected this in master.

**Comment by dkmooers** [comment]
Thanks!

**Comment by inetfuture** [comment]
This method has been removed from 4.x? Is there change log I can refer to?
