### ISSUE TITLE
_.includes handles empty arrays as target oddly 

### ISSUE THREAD

**Issue by thody** [lodash/lodash#1320]
```
_.includes("foo", []);
// -> true
```
This feels pretty counterintuitive, I would expect a String to _NOT_ include an empty Array. I got here by accidentally swapping args, but it took a little while to track down my error because of the seemingly odd result here.

FWIW, this appears to be handled as I would expect:

```
_.includes("foo", ["bar"]);
// -> false
```

**Comment by megawac** [comment]
That is because `[].toString === ''` and `['a'].toString() == 'a'`

**Comment by jdalton** [comment]
Coercion is fun

```js
"foo".indexOf([]); // => 0
```

**Comment by nikmartin** [comment]
As a follow up to this, I ran into:
```
var undef;
_.contains([123,456],undef) // => -1 
```
which is correct, but there seems to be a performance hit if `typeof target === 'undefined'`, the test is still performed, iterating over the entire collection. Would it be valid to return -1 if target is undefined?  Conversely, is this valid in a collection: ['foo', undefined, 'bar'] ?

**Comment by jdalton** [comment]
@nikmartin `undefined` is a valid target and collections may contain `undefined` values.
