### ISSUE TITLE
A way to clone array on purpose when using chain call.

### ISSUE THREAD

**Issue by le0nik** [lodash/lodash#1323]
Hello!

In 3.10.0:

```
var arr = [1, 2, 3];

var arr2 = _.chain(arr)
    .slice()
    .reverse()
    .value();

console.log('arr2: ', arr2); // [3, 2, 1]

console.log('arr: ', arr); // [3, 2, 1]

// in 3.9.3 and prior to it 'console.log(arr);' would return [1, 2, 3]. The initial array would be untouched.
```
First i'd like to say, that it is unintuitive, undocumented(nothing in the changelog) and it broke a part of our project. Supposing, that the change was intentional(short fusion), the question is: is there a way to clone an array on purpose, considering that `_.clone` and `_.cloneDeep` aren't chainable?

Thank you!

**Comment by jdalton** [comment]
Thanks, you found a bug.
