### ISSUE TITLE
[Question] Implement Title Case?

### ISSUE THREAD

**Issue by Awk34** [lodash/lodash#1325]
Are there any plans to implement a `titleCase` function? Like `startCase`, but without words like 'the' and 'a' being capitalized, unless it is the first word. It would be similar to what's done in #908, with the added functionality of excluding certain words that aren't the starting word. I could probably take a swing at implementing it when I have some free time. I would find it useful.

**Comment by jdalton** [comment]
I want to stay away from methods like that because it get's super complex pretty quickly.

**Comment by ilovett** [comment]
fwiw it may suffice to chain camelCase with upperFirst

**Comment by lijunle** [comment]
I could say everybody is doing **chain camelCase with upperFirst**. So, why not add it to lodash? This is the super utility library!

**Comment by jdalton** [comment]
`camelCase` with `upperFirst` is not title case. See [the wikipedia blurb](https://en.wikipedia.org/wiki/Letter_case#Case_styles)

> ##### Title case 
"The Quick Brown Fox Jumps Over the Lazy Dog." or
"The Quick Brown Fox Jumps over the Lazy Dog."
(depending on how the [house style](https://en.wikipedia.org/wiki/House_style) treats four-letter [prepositions](https://en.wikipedia.org/wiki/Preposition)). Also known as "**headline style**" and "capital case". First character in all words capitalised, except for certain subsets defined by rules that are not universally standardised. The standardisation is only at the level of house styles and individual [style manuals](https://en.wikipedia.org/wiki/Style_manual). (See further explanation below at [Headings and publication titles](https://en.wikipedia.org/wiki/Letter_case#Headings_and_publication_titles).))

**Comment by lijunle** [comment]
Hmm... It sounds like I am not really needing the **real** title case. Just the UpperFirstCamelCase. :joy_cat:

**Comment by pyramidium** [comment]
AKA Pascal Case.

**Comment by jdalton** [comment]
For the `_.pascalCase` request see #942.

**Comment by hackel** [comment]
What I would really want out of a titleCase is:
```js
_.titleCase('someCamelString') == 'Some Camel String'
_.titleCase('some_snake_string') == 'Some Snake String'
_.titleCase('some-kebab-string') == 'Some Kebab String'
```
Having to do this conversion manually each time seems like a perfect candidate for inclusion in lodash to me.

**Comment by jdalton** [comment]
@hackel 

We have [_.startCase](https://lodash.com/docs/4.17.2#startCase) for that.

**Comment by aristidesfl** [comment]
However `_.startCase('MY_UPPERCASE_STRING') === 'MY UPPERCASE STRING'`

**Comment by juanojeda** [comment]
@aristidesfl that can be achieved with `_.startCase(_.toLower('MY_UPPERCASE_STRING'))`
