### ISSUE TITLE
[documentation] compact and holes

### ISSUE THREAD

**Issue by kswope** [lodash/lodash#1327]
>
Creates an array with all falsey values removed. The values false, null, 0, "", undefined, and NaN are falsey.

Compact also seems to remove holes.  Undocumented feature, unintentional side effect, or just general policy against returning array with holes?  Should it be documented either way?

```
log(  _.compact( [ 1, , , , 2 ] )  )  //=> [1,2]
```

**Comment by d10** [comment]
"Holes" in sparse arrays are `undefined`, so they will be removed when compacted.

**Comment by jdalton** [comment]
Lodash methods do not produce sparse arrays and treat holes as `undefined`.
