### ISSUE TITLE
Feature: throw on undefined properties in _.template

### ISSUE THREAD

**Issue by BridgeAR** [lodash/lodash#1329]
`_.template` will throw if you try to use something like ```<%= data.user.email %>``` where `data.user` is not defined. It'll fail silently though if the user exists but has no email. It'll just be an empty string. This should fail in my opinion or result in printing 'undefined' as string instead. This would very likely break stuff so the best way to handle this is probably by inserting a opt-in option.

If any of the named ways is a good idea in your opinion I'd also open a PR if you'd want me too.

**Comment by jdalton** [comment]
I disagree. We have the graceful result because of user feedback. In fact you can make `data.user.email` avoid throwing if you use `_.get(data, 'user.email')` too : D

**Comment by BridgeAR** [comment]
I read about handling it graceful too and I think everyone has different ways to handle these things. I personally want to know if something was not inserted and it's quite difficult to check each result properly right now. We use lodash for our e-mail templates and the e-mail handler get's a lot of different input and we'd have to test each e-mail with all possible values to know if everything has worked fine. And we already had the issue that we sent e-mails with a missing value.
So that's why I suggested to insert a option for opt-in for this behavior.

**Comment by jdalton** [comment]
Validating template data is a bit out of scope for lodash and it can be handled in a variety of ways, like with `_.defaults`.

**Comment by BridgeAR** [comment]
So your suggestion is to use `_.defaults` on all values in all templates? That's not really a good solution ^^. But I did not really want to get a option for mail validation anyway. It's a general purpose thing to be sure that each value you thought you have entered ends up in the result. By just inserting a empty string all users end up not knowing if it worked or not. By throwing on undefined values everyone knows immediately what's wrong and they can solve the issue before the wrong result is ever exposed to customers in any way.

**Comment by jdalton** [comment]
Listen, I'm saying it's a possible solution. I'm telling you I'm not supporting your requested feature and that is very much that.
