### ISSUE TITLE
_.inRange behavior unexpected when end < start

### ISSUE THREAD

**Issue by dbkaplun** [lodash/lodash#1332]
When [`_.inRange`](https://lodash.com/docs#inRange) is used with `end < start`, the values are flipped, so `start = end` and `end = start`. This is undocumented behavior.

IMO, this behavior is incorrect: `_.inRange` should just return `false` when `end < start`. This caused a problem in my code:
```js
$checkbox.prop({indeterminate: _.inRange(selectedCount, 1, items.length)});
```

**Comment by jdalton** [comment]
Hi Dan! We have [reasons](https://github.com/lodash/lodash/issues/1099) for the behavior. I'll add a doc note though.
