### ISSUE TITLE
_.any executes more than is necessary

### ISSUE THREAD

**Issue by wyantb** [lodash/lodash#1333]
I have a use case that involves a relatively expensive mapping process, but cheap checking with `_.any` at the end.  I figured I'd be able to avoid processing mapped items, since `any` will only need to process some subset of array values at the end, but no dice.  `any` forces the entire collection to be mapped.

For clarity, here's an example:

```
_(['a', 'b', 'c'])
  .map(function () { console.log('mapping'); })
  .any(function () { return true; });
```

In this (admittedly trivial) example, "mapping" prints out three times, while we can intuitively see that `any` is going to accept the first result, so we don't really need to process `map` for the second and third values.

Is what I'm imaging here possible, and desirable to lodash?

**Comment by jdalton** [comment]
Hi @wyantb! Currently we don't support shortcut fusion for `some`. I looked into it and supporting it would add quite a bit to the implementation so I want to hold off until the demand is a bit more.

**Comment by wyantb** [comment]
Fair enough.  Thanks!
