### ISSUE TITLE
First doesn't short circuit

### ISSUE THREAD

**Issue by megawac** [lodash/lodash#1336]
Unless I'm missing something, first is documented to short circuit, however it currently doesn't.

```js
var items = [1, 2, 3, 4, 5, 6, 7];
var count = 0;
_(items).map().filter(function(x) {count++; return true;}).first()

count === 7;
```

**Comment by jdalton** [comment]
We apply shortcut fusion when the array is long enough.

**Comment by megawac** [comment]
Whoopsies

On Sun, Jul 12, 2015 at 2:29 PM, John-David Dalton <notifications@github.com
