### ISSUE TITLE
Processing a template that contains `${whatever}` throws an error

### ISSUE THREAD

**Issue by unindented** [lodash/lodash#1339]
This piece of code throws an error:

```js
_.template('<%= foo %> ${bar}')({foo: 'foo'})
```

```
ReferenceError: bar is not defined
    at eval (lodash.templateSources[1]:9:10)
    at repl:1:35
    at REPLServer.defaultEval (repl.js:154:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:308:12)
    at emitOne (events.js:77:13)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
```

I'm using the default `templateSettings`:

```js
_.templateSettings
```

```
{ escape: /<%-([\s\S]+?)%>/g,
  evaluate: /<%([\s\S]+?)%>/g,
  interpolate: /<%=([\s\S]+?)%>/g,
  variable: '' }
```

So I'm not sure why lodash would try to replace `${bar}`. Am I missing something?

**Comment by d10** [comment]
Lodash uses the ES6 syntax `${}` to do replacement as well. To prevent it from doing that, you can just set `_.templateSettings.interpolate = /<%=([\s\S]+?)%>/g`.

**Comment by unindented** [comment]
@d10 Ah, printing `_.templateSettings.interpolate` already showed that same expression, but you are right that overwriting it with the same value makes things work.

Weird, but solved I guess?

**Comment by d10** [comment]
It's a really obscure trick, I guess. When none of the regexes are changed, the default syntax is used which includes both the ERB `<%= %>` and the ES6 `${ }`. When the regex is changed, the default ES6 replacement will not be performed.
