### ISSUE TITLE
where does _.where fit in?

### ISSUE THREAD

**Issue by kswope** [lodash/lodash#1342]
Going through the docs and a book and I can't figure out what _.where can do that _.filter cannot.

The "Lodash essentials" promotes _.where as 
>
"The where() function is great for its concise syntax and intuitive application to collections. " 

which isn't really saying much.

In the doc examples _.where can be replaced with _.filter and still work the same.

Is there a reason _.where isn't just aliased to _.filter.  Is there a performance difference?  If there is a difference, I think it should be clarified in the docs and the example should reflect it.

**Comment by jdalton** [comment]
No special reason. In v4 `_.where` is being removed in favor of `_.filter` :)

**Comment by kswope** [comment]
:+1: 

Same with _.findWhere?

**Comment by jdalton** [comment]
Yap, and `_.pluck`.
