### ISSUE TITLE
Chain - each ?

### ISSUE THREAD

**Issue by bornemix** [lodash/lodash#1345]
Hello,

Is this designed/desired behavior? It surprised me that the following code does not yield any log statements:

```
_.chain([1,2,3])
.filter(function(i){
  return i != 2;
})
.each(function(i){
  console.log(i);
});
```

This does work, though:

```
_.each(
  _.filter(
    [1,2,3],
    function(i){
      return i != 2;
    }
  ),
  function(i){
    console.log(i);
  }
);
```

Tested in 3.10.0.

**Comment by Gamemaniak** [comment]
You have to call the ``value`` method. https://lodash.com/docs#_

```js
_.chain([1,2,3])
.filter(function(i){
  return i != 2;
})
.each(function(i){
  console.log(i);
})
.value()
```

**Comment by jdalton** [comment]
In v4 methods like `each` will implicitly end the chain sequence.
