### ISSUE TITLE
merge with defaults callback corrupts target

### ISSUE THREAD

**Issue by scottfavre** [lodash/lodash#1346]
This is on chrome with lodash 3.10

    var user = { foo: { bar: { baz: 1 } } };
    var defaults = { foo: { bar: { baz: 2 } } };
    var settings = _.merge(user, defaults, _.defaults);

Expected: settings to be { foo: { bar: { baz: 1} } }

Got:
       0: 'f'
       1: 'o'
       2: 'o'
       bar: { baz: 1 }
       foo: << recursive reference to settings object >>

**Comment by scottfavre** [comment]
Obtained by calls to console.dir(...) in Chrome

![image](https://cloud.githubusercontent.com/assets/150353/8681437/5630a34e-2a35-11e5-8c21-757dc4e40eb7.png)

**Comment by jdalton** [comment]
See the [_.merge](https://lodash.com/docs#merge] docs. The `customizer` is provided 5 arguments:
`(objectValue, sourceValue, key, object, source)`

**Comment by scottfavre** [comment]
@jdalton - this used to work in 2.4.1 ... looking at some other issues it looks like I have to write my own customizer now, is that accurate?

**Comment by jdalton** [comment]
Yes we changed things in v3.0 and it was documented in the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v300).

> * Expanded the number of arguments provided to customizer callbacks of `_.assign`, `_.clone`, `_.cloneDeep`, `_.isEqual`, & `_.merge`

You can adjust your customizer by doing:
```js
_.merge(a, b, function(v1, v2) { return _.defaults(v1, v2); });
```
or
```js
_.merge(a, b, _.ary(_.defaults, 2));
```
or you can use [_.defaultsDeep](https://lodash.com/docs#defaultsDeep).

**Comment by scottfavre** [comment]
Thanks. Looks like 

    function(v1, v2) { return _.defaults(v1, v2); }

works for my use case.
