### ISSUE TITLE
doc: unclear how to use Lodash with Backbone via Browserify

### ISSUE THREAD

**Issue by kadamwhite** [lodash/lodash#1347]
https://github.com/lodash/lodash/wiki/Migrating#backbone contains instructions on using the aliasify transform to replace underscore with lodash. Aliasify itself implies it is just an extension of the `"browser":` property in package.json, which cannot impact dependencies within node_modules [per Browserify's docs](https://github.com/substack/node-browserify#browser-field) (the same limitation apparently applies to all transforms). In that context, there does not seem to be any way to use Aliasify to sub lodash for underscore when using Backbone with Browserify.

As an example, with the file `demo.js` as follows:
```js
module.exports = require( 'backbone' );
```
I would expect that running `npm test` after installing this `package.json` file:
```json
{
  "scripts": {
    "test": "browserify app.js --transform aliasify | grep lodash"
  },
  "aliasify": {
    "aliases": {
      "underscore": "lodash"
    },
    "verbose": true
  },
  "dependencies": {
    "backbone": "^1.2.1",
    "jquery": "^2.1.4",
    "lodash": "^3.10.0"
  },
  "devDependencies": {
    "aliasify": "^1.7.2",
    "browserify": "^10.2.6"
  }
}
```
would output a match; but lodash is not substituted, and underscore is bundled instead.

Either the wiki is incorrect, and Aliasify cannot be used to `require( 'backbone' )` in such a way that it will use Lodash internally instead of Underscore, or else my configuration/understanding is incorrect. I'd love any advice you might have to offer—thanks much!

**Comment by jdalton** [comment]
:bell:  @phated

**Comment by jridgewell** [comment]
Backbone actually maintains a [wiki page](https://github.com/jashkenas/backbone/wiki/Using-Backbone-without-jQuery#with-a-different-dom-library) on substituting dependencies.

**Comment by jdalton** [comment]
@jridgewell I'm not seeing the difference in the Lodash wiki advice and that of the Backbone wiki.

**Comment by jdalton** [comment]
Ah the
```json
  "browserify" {
      "transform": ["aliasify"]
   }
```
bit. I assumed folks would get that it's a transform in that we mention it's a transform.

**Comment by kadamwhite** [comment]
Oh, interesting! @jridgewell thanks for that link, it revealed the issue, but it's not actually the `"browserify"` block in package.json—that was handled with the `-t` flag—but rather that the aliasify command must be run as a *global* transform. Changing my test command to either of these options

-  `browserify demo.js --global-transform aliasify`
- `browserify demo.js --transform [ aliasify --global=true ]`

produces the expected results.

I haven't been able to find any variant of the `"browserify": { "transform": [] }` configuration that will make the transform run globally, short of explicitly specifying it in the command. That, I think, is an issue with Browserify's docs, and not Backbone/Lodash/Underscore: for Backbone purposes it should be enough to note that aliasify must be flagged with `-g`/`--global-transform` when invoking browserify.

Thanks much for your help!
