### ISSUE TITLE
clone and cloneDeep only call customizer with one argument when a thisArg is specified, as opposed to the intended arguments of value, index/key, and object.

### ISSUE THREAD

**Issue by Ross-Esmond** [lodash/lodash#1349]
This is due to the customizer, an optional function passed to clone and deepClone, being specified as only taking one argument when it is passed into bindCallback.
    
      return typeof customizer == 'function'
        ? baseClone(value, isDeep, bindCallback(customizer, thisArg, 1))
        : baseClone(value, isDeep);

bindCallback will then wrap the customizer in a function that only passes along one argument, so that even though baseClone does try to invoke the function with three arguments, they aren't passed through.

It should be noted that this only happens when a thisArg is passed into clone, without it bindCallback simply passes back the original customizer function, causing no problems.

**Comment by jdalton** [comment]
Thanks, this has been resolved in edge.
