### ISSUE TITLE
Shouldn't _.at be 'length proof'?

### ISSUE THREAD

**Issue by kswope** [lodash/lodash#1351]
Its my understanding that lodash "Array" functions require arrays, and "Collection" functions prioritize using the length property but don't need it, and "Object" functions ignore it.   Given these three choices I see how _.at fits in, its an Collection function because, in my definition, adding a length property makes it go ape.  But shouldn't it be smarter?  Honestly I'd be worried to use this function for anything but an array.  In other words, the behavior of this function of objects with a 'length' property violates principles of least surprise.

**Comment by jdalton** [comment]
Agreed. There's no need for a length check in this method.

**Comment by kswope** [comment]
Hmm, even _.map has this problem.  Is there not a reliable way to check if an argument is an object or an array?  Is there work to be done to improve "collection" functions that take an "object" as the first argument or is it a lost cause?  I'm almost ready to to accept that its best practice to keep objects away from "collection" functions and only use "object" functions.   But I do see why the underscore folks were tempted to combine object/array functions into their own category.

**Comment by jdalton** [comment]
Naw, not into opening the "What a collection is" conversation. Sorry you're having an issue with coming to terms with it but it's been this way for 6 years.

**Comment by kswope** [comment]
I don't care about the philosophy, I just would expect collection functions to be better type checking before it goes to work.  Is it not possible to distinguish between an object with a length property and an array?

**Comment by jdalton** [comment]
The choice made for collections and what classifies as an array-like aligns with ES2015 and allows things like NodeLists and jQuery collections to be treated as an array.

**Comment by kswope** [comment]
Ok thanks for explaining, that makes sense.  I'm about to start a project that involves a lot of objects with length properties, believe it or not (architectural blueprint type thing), so now I know to use something like ".len" instead!

**Comment by jdalton** [comment]
I've changed `_.at` to an "Objects" method: https://github.com/lodash/lodash/commit/8c2361ce2d5eb6319785499fc6676bcf338d98d2
