### ISSUE TITLE
forEach fails on object when invoked with wrapped object format

### ISSUE THREAD

**Issue by michael-wynn** [lodash/lodash#1354]
example: 
var x = {
    a: 1,
    b: 2
};
/* This call will work: */       _.forEach(x, function(item){return ... })
/* This call will not work:*/  _(x).forEach(function(item){return ... })

Both of the above will work correctly with underscore.

**Comment by jdalton** [comment]
In lodash v3 chained methods are deferred until an implicit or explicit `.value()` is requested. Since `forEach` chains you'll have to call `.value()` to end the sequence. In v4 `forEach` will implicitly end the chained sequenced.
