### ISSUE TITLE
License information in bower.json

### ISSUE THREAD

**Issue by BernhardRode** [lodash/lodash#1355]
Hi,

we are using lodash via bower inside of a project. We need to publish all the license/version informations of libraries we use to our customer. We generate this data automatically by parsing bower,json, package.json and component.json files.

In lodash we have the problem, that when installing via bower:

* the component.json, which has the needed informations is being ignored and not available
* bower.json has no information about license and version

So i would love to get this information into the lodash bower package and i'm willing to do the "hard" work =)

What would be the preferred way?

* Remove component.json from being ignored
* Add the informations to bower.json

I'd prefer the first solution.

Looking forward hearing from you.

**Comment by jdalton** [comment]
Thanks! I added the license field to the bower.json.
