### ISSUE TITLE
Display big-O in docs

### ISSUE THREAD

**Issue by mjgpy3** [lodash/lodash#1356]
As data sets become large this becomes valuable to know. We can easily enough dig through the source code, but having big-O in the docs will make this investigative work easier.

Thoughts?

**Comment by jdalton** [comment]
Thanks. That's something I'm not great with and not wanting to dig into at this time.

**Comment by mjgpy3** [comment]
Alright, thanks for the response.

**Comment by CatGuardian** [comment]
I think it is really important that the big-O notation be displayed in the documents. This issue should be reopened.

**Comment by omarjackman** [comment]
@jdalton 
> That's something I'm not great with and not wanting to dig into at this time.

Maybe you could reopen this issue and let someone else(a willing contributor) take a stab at it 😄

**Comment by jdalton** [comment]
Thanks @omarjackman! But I'm ok with leaving this out still.
