### ISSUE TITLE
[suggestion]  _.condFunctions

### ISSUE THREAD

**Issue by kswope** [lodash/lodash#1358]
This will probably get shot down pretty quickly, or referred over to the contrib library, but I'll just throw it out there since I've found it useful myself already.  Maybe I've overlooked a better alternative, its been known to happen.

With literally just a few lines of code all the "Lang" predicate functions(isNull, isUndefined, isObject, etc) can be turned into "ternary" or "conditional" functions.  (based on the ternary/conditional operator)

```
// basic truthy (not generated but used internally by the others)

_.cond( value, ifTrueValue, ifFalseValue )



// all the following have been generated from the existing code

_.condUndefined(value, trueValue, falseValue)
_.condNull(value, trueValue, falseValue)
_.condNaN(value, trueValue, falseValue)



// example of use, so clean!

function MyConstructor(x,y){
  this.x = _.condUndefined(x, 0, x)
  this.y = _.condUndefined(y, 0, x)
}

```

Example implementation below

```
var _ = require('underscore')

// truthy conditional and foundation of others

_.cond = function(condition, trueValue, falseValue){
  return condition ? trueValue : falseValue
}



var langMethods = ['isUndefined', 'isNull'] // these get turned into condFunctions

_.each(langMethods, function(langMethod){

  _['cond' + langMethod.slice(2)] = function(conditionValue, trueValue, falseValue){
    return _.cond(_[langMethod].call(null, conditionValue), trueValue, falseValue)
  }

})


```

**Comment by jdalton** [comment]
Hi @kswope! This looks similar to other suggestions for an `_.and` or `_.or` like method. I'll continue to keep an eye on the demand for it.
