### ISSUE TITLE
lodash / object / set

### ISSUE THREAD

**Issue by tuchk4** [lodash/lodash#1359]
example:
```js
var result = set({}, 'a.0.b.0', 1);  
equal(result, { 
  a: [{
    b:[ 1 ]
  }]
});
```

But in my case I need result to be (for immutable helpers)
```js
 equal(result, {
      a: {
        0: {
          b: {
            0: 1
          }
        }
      }
    });
```

If there are any case to do this?  Maybe add options to **set** function?
https://github.com/lodash/lodash/blob/3.10.0/lodash.src.js#L10172 change to 
```js
nested[key] = {};
```

**Comment by jdalton** [comment]
Instead of an options object I'll add `_.setWith` which accepts a `customizer` callback.
```js
_.setWith({}, 'a.0.b.0', 1, function() { return {}; });
```
or
```js
_.setWith({}, 'a.0.b.0', 1, _.partial(Object, null));
```

**Comment by tuchk4** [comment]
lgtm thank you

In what version this update is expected?

**Comment by jdalton** [comment]
I have a minor patched queued so after that this should land in v4.

**Comment by tuchk4** [comment]
cool

thanks you a lot

**Comment by jdalton** [comment]
Closed by https://github.com/lodash/lodash/commit/4520e0710dc3fd0f8805e02a086b81213c5c2cfe.

**Comment by mathieug** [comment]
I had the same problem, thanks @jdalton for `_.setWith()`.
Can you explain me a bit how the customizer works in `_.setWith(errors, 'projects.5', 'Invalid project', Object)`?

**Comment by philleepflorence** [comment]
If you expect numbers in the path, do:

```
_.setWith(@object, @path, @value, function (object)
{
    if (object) return object;
     
    return {};
});
```

If there is an object, return that object otherwise, return an empty object. 
Skipping the first return statement could override all subsequent objects in the loop.
