### ISSUE TITLE
Strip html

### ISSUE THREAD

**Issue by DylanPiercey** [lodash/lodash#1361]
To go with _.escape and _.unescape it would be cool to have a utility to remove all html tags from a string.

```javascript
_.mixin({
    // name not important
    removeHTML: function (str) {
        return String(str).replace(/(<([^>]+)>)/ig, "");
    }
});

_.removeHTML("<strong>hello</strong>") //-> hello
```

**Comment by jdalton** [comment]
Hey @DylanPiercey! Removing html is a bit more complex than a simple regexp to handle.
I'm sure there are specialized libs just for this kind of thing. \cc @mathiasbynens

**Comment by mathiasbynens** [comment]
https://github.com/cure53/DOMPurify

**Comment by jdalton** [comment]
:+1:
