### ISSUE TITLE
Terminating chains with size()

### ISSUE THREAD

**Issue by adamboduch** [lodash/lodash#1362]
I often need to filter collections, only to get the size. In other words, I have no use for the filtered collection itself. For example:

```javascript
_(monsterCollection)
    .filter({ enabled: true })
    .size();
```

It'd be cool if this chain recognized "hey, this is terminated with `size()`, so instead of building up a new collection, I just need to increment a counter!".

Maybe there's already something like this in place? Or maybe this isn't a cost-effective optimization? Any thoughts appreciated!

**Comment by jdalton** [comment]
This is neat but doesn't fit into our lazy eval implementation.
