### ISSUE TITLE
Support for npm test in package.json

### ISSUE THREAD

**Issue by jasnell** [lodash/lodash#1363]
I'm currently working on an automated test system (https://github.com/jasnell/citgm) that will eventually be integrated with the Node.js CI to perform a kind of smoke-test on Node builds. The test system will check a selection of the most popular modules on npm. The current design automates the steps of performing an `npm install` followed by an `npm test`. Unfortunately, lodash doesn't currently support `npm test`, which forces us to include lodash in our group of "special cases".

It would be great if you could add the following line into your lodash's package.json:

```
  "scripts": {
    "test": "node test/test.js"
  }
```

**Comment by Starefossen** [comment]
The Node.JS build / test team want to integrate lodash into their automated testing suite for new io.js/Node.jS releases. As I see it, this will be very beneficial for everyone, average Node.JS uses as well of lodash users. It is literally zero effort required on lodash's part; all we need is support for the `npm test` command.

**Comment by Fishrock123** [comment]
@jdalton Hi there, could you explain more the reason this might be tagged with `wontfix`? We'd like to better understand how we can improve this sort of thing if you have feedback. :)

**Comment by jdalton** [comment]
Oh snap, I must have tagged it just before jetting to work. Because lodash is the most depended on package it puts pressure on me to include only what's needed for the package which is still 2.2mb on disk.

**Comment by jdalton** [comment]
That said I'm open to making it easier for your test system. For example I could include a field in the package.json that points to the test file to run.

**Comment by megawac** [comment]
Do you guys address packages that have the test files in `npmignore` @Fishrock123  @Starefossen? As most large packages exclude these files on npm

**Comment by jasnell** [comment]
@jdalton .. thank you!
@megawac ... eventually yes. the tool currently uses `npm pack` to extract a snapshot of the module being tested, then runs `npm install` from the package directory. If we find that some module isn't including it's tests, the tool supports passing in a git url directly (using the same syntax as `npm install`), which tells `npm pack` to go off to github to get the details. It's not bullet proof, but it works so far.

**Comment by Fishrock123** [comment]
> That said I'm open to making it easier for your test system. For example I could include a field in the package.json that points to the test file to run.

Adding a `test` script as per the above would be appreciated, yes. :)

**Comment by jdalton** [comment]
> Adding a `test` script as per the above would be appreciated, yes. :)

It would just be like a github url of the location of the test file but not actually the file. If you all iron out a process I'll jump on board that. The main thing is to avoid putting the file in the actual package.

**Comment by jasnell** [comment]
@jdalton ... take a look here: http://github.com/jasnell/citgm 

The tool attempts to invoke `npm test` to run the tests, you can have that point at a script that does whatever you'd like it to... perhaps, for instance, a small script that does a git download then runs the tests. If it's going to be too difficult, however, we have a work around (as documented in the readme of the citgm tool)

**Comment by jdalton** [comment]
If you have smth in mind totally PR it.

**Comment by Fishrock123** [comment]
Express (or at least express subcomponents) don't actually ship with the tests, but still declare an `npm test` script if they are there. It's just a more reliable way for us to invoke the tests if they are there rather than trying to do per-package stuff. :)

**Comment by jasnell** [comment]
PR here: https://github.com/lodash/lodash/pull/1368
