### ISSUE TITLE
Does lodash have an equivalent for null || undefined?

### ISSUE THREAD

**Issue by xhh2a** [lodash/lodash#1364]
I tried using underscore's !_.has(object, 'property') but that returns true if the value is set to null or undefined. I don't really see anything in underscore or lodash documentation that simplifies something like:
```
if (this._uuid === undefined || this._uuid === null || this._account_type === undefined || this._account_type === null || this.site_id === undefined || this.site_id === null)
```
short of maybe doing
```
_.chain(this).pick(['_uuid', '_account_type', 'site_id']).values().without(undefined).without(null).isEmpty().value();
```

(Another use case not exactly the same is when I have to chain .without(null).without(undefined) which is annoying)

Thanks. :)

**Comment by jdalton** [comment]
We don't have a `_.isNil` method but you always add a mixin or use `== null`.

**Comment by StreetStrider** [comment]
@xhh2a, are you trying to distinguish key which value is `undefined` from absent key?

**Comment by RPDeshaies** [comment]
>>Lodash doesn't have a _.isNil method but you always add a mixin or use == null.

They do now.
https://lodash.com/docs/4.16.4#isNil
