### ISSUE TITLE
Expose the internal toPath method

### ISSUE THREAD

**Issue by w33ble** [lodash/lodash#1365]
I'm building a module that makes a lot of use of `_.get` and `_.set` internally, and I keep finding myself wishing I had access to `toPath`, the method that turns a string path into an array. I don't even need new functionality, I'd just like it to be exposed externally, via `_.toPath` or something.

I'm happy to make a PR for it but wanted to open an issue in case there's some opposition to exposing it.

**Comment by jdalton** [comment]
Good news @w33ble! You can do `require('lodash/internal/toPath')`.

**Comment by w33ble** [comment]
Oh, sorry, I didn't realize the internal methods were all modularized as well. Thank you!!
