### ISSUE TITLE
bower update lodash gets *-npm-packages for patch version != 0

### ISSUE THREAD

**Issue by Delapouite** [lodash/lodash#1366]
Hello.

Here's an extrac of the ouptut of `bower info lodash`

```
...
  - 3.2.3-npm-packages
  - 3.2.2-npm-packages
  - 3.2.1-npm-packages
  - 3.2.0
  - 3.2.0-npm-packages
  - 3.2.0-npm
  - 3.2.0-es
  - 3.2.0-amd
...
```
if this line is specified in a bower.json : 

```
"lodash": "~3.2.0"
```
The command `bower update lodash` will retrieve 3.2.3-npm-packages which does not work client side, because there's no 3.2.3

**Comment by jdalton** [comment]
Yap, that's a known limitation. With bower's future unclear I'm fine with this gotcha. Things work if you specify an exact version so that's what I'd recommend.
