### ISSUE TITLE
trimLeft is not giving proper value when string has forward slash in it.

### ISSUE THREAD

**Issue by sap9433** [lodash/lodash#1367]
``
_.trimLeft("pharma/tenants/65/read_all_tas", "pharma/tenants/65/")
"d_all_tas"
``

where as it should had been ``read_all_tas``

**Comment by jdalton** [comment]
You're using the method incorrectly. The `chars` is a string of characters to remove. So any of those characters will be removed. I may make it accept an array of characters to emphasis this point.

**Comment by jdalton** [comment]
If you're dealing with paths you should check out the [path module](https://nodejs.org/api/path.html) in node (it can be browserified too I believe).

**Comment by StreetStrider** [comment]
@jdalton, yes it can: [path-browserify](https://www.npmjs.com/package/path-browserify).
