### ISSUE TITLE
Please consider supporting _.isDefined

### ISSUE THREAD

**Issue by niyazpk** [lodash/lodash#137]
I know it can be done by:

```
if( ! _.isUndefined(obj.key) ){ }
```

but sometimes it is confusing and takes a few mental cycles to parse the code while it is straightforward and easy to read:

```
if( _.isDefined(obj.key) ){ }
```

**Comment by userpixel** [comment]
I can think of several reasons why `_.isDefined()` makes sense:

* `!._isUndefined()` is **less fluent** when reading code. I think it's an important argument because I suspect that's one of the reasons `_.isUndefined()` is in Lodash core.
* `!._isUndefined()` is longer and considering that in many cases (like when loading Lodash from CDN) it is not minified, that's 2 extra character for every use case.
* `!._isUndefined()` is slightly (very very tinily) less performance because it executes as `(! value === undefined)` as opposed to `value !== undefined`. I guess js runtime optimizers invalidate this point.
* Consistency:  in almost many projects I've seen teams don't have a consistent way of dealing with type checking. Some do `var === undefined`, some `var === 'undefined'` (mistake), some just do `if (var) ...`, etc. Introducing this simple function (as stupid and simple as its implementation might be) can bring a level of consistency and readability to the code base.


---

On the downside, that's one more function to maintain, document and test.

**Comment by nbkhope** [comment]
@jdalton what if the key value is 0?
```
const obj = { key: 0 };
if (obj.key) { ... } // will never execute because 0 is false in JavaScript. It's defined, but falsy. :/
```

**Comment by dwiyatci** [comment]
@jdalton Just out of curiosity, why are you not a fan of `_.isUndefined`?

**Comment by jdalton** [comment]
@dwiyatci You can accomplish the same thing with `o === void 0`.

**Comment by userpixel** [comment]
Yeah but how readable is that too someone who's not fluent in js?
But I guess it's ok if the focus of libraries like lodash is more on bringing FP features to js rather than creating the most readable code. One has to be careful with the library size and API surface too.
I me the original issue but I've grown out of it actually so I'm totally fine with closing it :+1:

**Comment by palamccc** [comment]
```js
if(typeof obj.key !== 'undefined') {
}

if(!_.isUndefined(obj.key)) {
}

if(obj.key !== void 0) {
}

if(obj.key !== undefined) {
}

if(_.isDefined(obj.key)) { /* not yet implemented */
}
```
Even though all of them are technically same, last one is easy to read and preferred by some of us. So we request core developers to reconsider adding _.isDefined()

**Comment by falsyvalues** [comment]
To be precise they are not the same, since `type of` is an operator.

**Comment by richadr** [comment]
@falsyvalues can you elaborate?  Doesn't `typeof o !== 'undefined'` always have the same _result_ as the other methods?

The main reason for using `_.isUndefined` is, next to readability, that you can't wrongly apply it.  `typeof o !== undefined` and `if (o !== 'undefined')` are syntactically correct but also bugs that are hard to detect.  `if (!obj.key)` does not check for undefined but also for false.  That said, `!_.isUndefined()` is a double negative, which impacts readability.  And we shouldn't not avoid double negatives.

I +1'd this issue and hope this explanation further substantiates the request to add `_.isDefined()`.

**Comment by falsyvalues** [comment]
@richadr Sure, take a look on this:
```javascript
typeof neverDeclared // returns "undefined"
neverDeclared === undefined // while this will throw ReferenceError
// with typeof operator it's safe to do things like this
if (typeof neverDeclared !== 'undefined' && neverDeclared === 7)
```
Hope it helps :v:

**Comment by palamccc** [comment]
@falsyvalues @richadr  yes typeof is a operator, and it can't be replaced by any other function.

I hope, the behaviour of typeof doesn't matter on this discussion about _.isDefined() feature request. Let's ignore about typeof behaviour here.

**Comment by markstos** [comment]
I'm favor of adding `_.isDefined()`.   Positive checks are easier to read and less error-prone than double-negative checks, like all the native variants of "not undefined" that can be used instead.

**Comment by palamccc** [comment]
As of now, I am using following hack,

```js
// register mixin, globally once
_.mixin({ isDefined: val => !_.isUndefined(val) }, { chain: false });

// usage
const x = {};
console.log(_.isDefined(x.name));
```

**Comment by userpixel** [comment]
Having it as a function simplifies the calls that get a function:

```javascript
const arr = [1, , 3, , 5, 'hello'];

// The function we wish existed in lodash
const isDefined = val => val !== undefined;

// Cleaning up a sparse matrix
console.log(arr.filter(isDefined)); // [1, 3, 5, "hello"]
```

There's obviously an outcry for adding this from the community. So why not?

**Comment by tariqporter** [comment]
Would love this added. Our entire team at a large company has had to add our own implementation to this and never use `_.isUndefined`

**Comment by ionTW** [comment]
We would like to see this aswell!

**Comment by simondell** [comment]
I like to compose:

```
const isDefined = _.negate(_.isUndefined)
```

Admittedly, you now have a function outside the `_` namespace. I suppose you could add it. I tend to use lodash more like this:

```
import { isUndefined, negate } from 'lodash/fp'

const isDefined = negate(isUndefined)
```
... so the lack of namespace doesn't seem an issue. This may not suit your codebase or style preferences.

**Comment by vedmant** [comment]
Yeah, it would be nice to have this out of the box and not start googling just to find out that there is functions compositions required.

**Comment by hhowe29** [comment]
Another :+1:  for `isDefined`. We have a few conditionals in our code where `null` and `undefined` should fail, but `0` and `''` should pass.

**Comment by realappie** [comment]
Beside readability, a good reason to add this would be its use in callbacks. Like `filter` for example

Imagine having to filter out undefined items from an array, with `_.isUndefined` you would do so like this

```[undefined, undefined, undefined].filter( element => !_.isUndefined(element) )```

In comparison, doing so with a `_.isDefined` would look like this

```[undefined, undefined, undefined].filter( _.isDefined )```

Which is much more readable and less error prone as I personally have sometimes forgotten the `!` when I actually need it.

Also @jdalton, I am pretty new here. But is 50 up votes considered popular enough ? 😅

**Comment by dwiyatci** [comment]
@realappie You can actually negate the predicate like so:
`[undefined, undefined, undefined].filter(_.negate(_.isUndefined));`

But anyway, I'm also for `_.isDefined`. :grin:

**Comment by stephenh** [comment]
Just wandering by, but at some point I think having `isDefined` and `isUndefined` might/should be about the principle of least surprise, e.g. as a ~relatively new user of lodash seeing `.isUndefined` go by in our codebase, I went to use `.isDefined` (for one of the use cases above, a functional parameter to `omitBy`) and had to stop, "oh, huh, it's not there", and here I am on a github issue wondering/learning why.

Seems like adding it for consistency/parallelism would be worth it, especially given the extremely low cost AFAIU of adding it.

**Comment by verekia** [comment]
For those who would be confused like me, this last "Merged" PR is not the Lodash repository.
`isDefined` is *not* in Lodash.

I wish it was though, `!isUndefined` hurts my head!

**Comment by markstos** [comment]
Until this feature is added to Lodash, you can add it yourself as a mixin:

https://www.npmjs.com/package/underscore-is-defined

**Comment by thanpolas** [comment]
`isDefined` is crucial for API input validation. Also reversing `isUndefined` will not do the trick, consider:

```js
const input = {
  first_name: undefined,
};

!!_.isUndefined(input.first_name);
// Prints: false
// Expected: true - this is a defined property with value "undefined"

!!_.isUndefined(input.last_name);
// Prints: false
// Expected: false - this is not a defined property of the object "input"
```

**Comment by markstos** [comment]
@thanpolas A property defined as being "undefined" is considered `undefined` in JavaScript.

```
> a = { firstName : undefined }
{ firstName: undefined }
> console.log(a.firstName === undefined)
true
undefined
> console.log(typeof a.firstName === 'undefined')
true
undefined
```

Whether a property *exists* (but may exist with an undefined value) is a separate concept in JavaScript:

```
> a.hasOwnProperty('firstName')
true
```

**Comment by thanpolas** [comment]
@markstos I understand where you are coming from. However, please understand that this is your interpretetion of the language. `undefined` is a special value that other languages don't actually have. When a property has a value of `undefined` it does have a value, and the value is `underfined` ... Javascript ¯\_(ツ)_/¯

It's quite possible we may never agree on this, however that argument, is beyond the scope of this issue. In this (closed) issue, a new method for lodash was proposed.

My suggestion, for that proposal, is that the proposed `isDefined()` method, returns true when the property has a value of `undefined`. Which suggests that `isDefined()` needs two arguments, the object and the property.

The reason for that is semantics and purpose. My use case is to determine if properties were sent by the client during API validations. Whether those properties have a falsy value (`undefined`, `null`, `false`) is another concern and a next step in the validation process.

```js
function expressRouteHandler = (req, res, next) => {
  if (!_.isDefined(req.body, 'title')) {
    next('title must be defined');
  }
}
```

**Comment by falsyvalues** [comment]
> My suggestion, for that proposal, is that the proposed isDefined() method, returns true when the property has a value of undefined. Which suggests that isDefined() needs two arguments, the object and the property.

This is really against how language works and would be misleading.

We have already [_.has](https://lodash.com/docs/4.17.15#has) for such case.
```js
> _.has({a: {a:undefined}}, 'a.a')
< true
```

**Comment by MikelArnaiz** [comment]
A problem with using `_.negate` is that it's types breaks `isUndefined`'s type guard.

![Screenshot 2021-12-21 at 11 31 59](https://user-images.githubusercontent.com/2076221/146915372-c126961f-e8f1-4a63-b8e2-8c75c2ce6471.png)

You need to recreate the type guard:

```ts
function isDefined<A>(a: A | undefined): a is A {
  return a !== undefined;
}
const foo: number[] = [42, undefined].filter(isDefined) // Ok
```

or 

```ts
const isDefined = <A>(a: A | undefined): a is A => !isUndefined(a);
```

**Comment by aghArdeshir** [comment]
Great point @MikelArnaiz. I was here to mention the same thing, you mentioned it perfectly :+1:

**Comment by hazeled** [comment]
+1!! I would love to have this be a native feature of lodash

**Comment by markstos** [comment]
@hazeled Please don't add "plus one" comments. This generates not-useful for emails for the 20 subscribers here. Instead, this is why is the emoji reaction was added to Github issues. You can add a thumbs up to the top comment or subscribe to an issue for notifications. https://github.com/lodash/lodash/issues/137#issuecomment-1288209331

**Comment by amannn** [comment]
I think in combination with TypeScript there's some value for `isDefined`:

```tsx
const items = [1, 2, undefined];

items
  .filter(cur => cur !== undefined)
  .map(cur => cur * 2); // ❌ 'cur' is possibly 'undefined'.ts(18048)


function isDefined<Value>(value: Value | undefined): value is Value {
  return value !== undefined;
}

items
  .filter(isDefined)
  .map(cur => cur * 2); // ✅
```
