### ISSUE TITLE
[feature] get penultimate element

### ISSUE THREAD

**Issue by jasonLaster** [lodash/lodash#1370]
Maybe this is the rubyist in me showing through, but I'd love to be able to use negative indices get elements from right to left.

Here's what I'm proposing:

```js
var element = _.at(['a','b','c'], -2); // => 'b'
```

**Comment by jdalton** [comment]
Hi @jasonLaster! In the master branch I've made `_.at` into an "Object" method that accepts paths (shallow or deep). So specializing for arrays seems out of place for it now.

**Comment by jasonLaster** [comment]
Oh crazy, I'll have to take a look. Do you think i could find another more appropriate method for array indexing? Someone's gotta standup for the little square guy.

**Comment by jdalton** [comment]
I've considered negative indexes for `get`, `result` and friends but ran into similar issues.

**Comment by StreetStrider** [comment]
@jasonLaster, do you really need to get `-2`, `-3`… in production code? Or you're wanting this for REPL/playground tasks?
I'm asking because (for me) the most common negative index is `-1` which is covered by `_.last` (which is also much more readable than any negative numbers).

**Comment by chrisbolin** [comment]
I think `_.nth` should work for you
```javascript
_.nth(['a','b','c'],-2)
> 'b'
```
