### ISSUE TITLE
_.pluck() bug with 'aaa.bbb' dotted-string field selector

### ISSUE THREAD

**Issue by jurko-gospodnetic** [lodash/lodash#1371]
`_.pluck([{aaa: null}, {aaa: null}], 'aaa')` returns `[null, null]` - and that's expected

But `_.pluck([{aaa: {bbb: null}}, {aaa: {bbb: null}}], 'aaa.bbb')` returns `[undefined, undefined]` - and that is wrong... should be `[null, null]`.

Doing it one layer at a time - first plucking `aaa` and then plucking `bbb` in a second call returns the expected `[null, null]`.

Tested using versions 3.8.0 & 3.10.0.

**Comment by jdalton** [comment]
Hi @jurko-gospodnetic! I can't repro with v3.10.0 it produces `[null, null]` for me.

**Comment by jurko-gospodnetic** [comment]
Yup, my test with 3.10.0 was flawed and I was actually testing with 3.8.0. Retrying it now.

**Comment by jurko-gospodnetic** [comment]
Confirmed - works correctly with 3.10.0.
