### ISSUE TITLE
_.sum bug in 3.10.1

### ISSUE THREAD

**Issue by dimorphic** [lodash/lodash#1372]
Hi! o/

There seems to be a bug in latest lodash version (3.10.1) regarding the _.sum method.

This used to work:

```js
var products = [
	{
		product: { price: 195 },
		quantity: 1
	},
	{
		product: { price: 30 },
		quantity: 6
	},
	{
		product: { price: 75 },
		quantity: 2
	},
	{
		product: { price: 40 },
		quantity: 2
	}
];

var sum = _.sum(products, function(item) {
	return item.quantity * item.product.price;
});
```

But now, sum returns a zero value.

Looking at the docs, there doesn't seem to be a change to this method. Or am i missing something ?

Reverting to 3.10.0 seems to solve the problem.

Cheers!

**Comment by jdalton** [comment]
3.10.1 isn't published yet so I suspect you're testing master which is our pre 4.0 code which has `_.sum` split out into `_.sumBy`.

**Comment by dimorphic** [comment]
I see, my bad then. Thanks for the quick reply.

Keep up the good work :+1:
