### ISSUE TITLE
Merging a string with an array doesn't work as expected.

### ISSUE THREAD

**Issue by dietergeerts** [lodash/lodash#1375]
```
var defaults = {propA: 'someString'};
var userOptions = {propA: ['value1', 'value2']};
var options = _.merge({}, defaults, userOptions);
```

The options are now:

```
{propA: ['value1', 'value2', 'm', 'e', 'S', 't', 'r', 'i', 'n', 'g']}
```

This is not what should be expected. The string should be gone and only the array should be kept.

**Comment by jdalton** [comment]
The [_.merge](https://lodash.com/docs#merge) function accepts a `customizer` function to allow you to control merging.
