### ISSUE TITLE
Allow _.matches or _.matchesProperty to invoke property that is a function

### ISSUE THREAD

**Issue by joeheyming** [lodash/lodash#1376]
Lets say I have an object:
```js
Foo = function(name) {
  this.name = name;
}

Foo.prototype.getName = function() {
  return this.name;
}
```
Given these objects:
```js
a = new Foo('abc')
b = new Foo('123')
```
I already know I can filter like this:
```js
found = _.filter([a,b], function(item) {
  return item.getName() == 'abc';
});
```
But I want to do this without an anonymous function, like
```js
_.filter([a,b], _.matchesProperty('getName', 'abc'));
```
or maybe `_.matchesGetter('getName': 'abc')`  where getter implies the function doesn't take any arguments.

I am aware, I could just say `_.filter([a,b], {'name': 'abc'})`, but sometimes I am using an external library like knockout where you have pure computed functions 
```js
this.excitingName = ko.computed(function() {
  return this.name() + '!!!';
}, this);
```
so it would be ideal to say `_.filter([a,b], {'excitingName': 'Joe!!!'});` 

 no need for unnecessary anonymous functions...

**Comment by jdalton** [comment]
This is a bit more than I want to tackle for shorthand sugar. You can wrap or replace `_.callback` to customize it though. Let me know how it works out.

**Comment by joeheyming** [comment]
Not sure how _.callback works.  Can you give an example?

**Comment by joeheyming** [comment]
nm, got it: x = _.filter([a,b], _.matches(_.callback(Foo.prototype.name), 'abc'))

**Comment by jdalton** [comment]
I meant you could wrap it to customize it as methods like `_.filter` use it internally.
See the [doc example](https://lodash.com/docs#callback).

**Comment by zeelux** [comment]
I've worked up a first revision of adding knockout observables/computeds support to lodash using the _.callback method as jdalton suggested. Take a look at it here https://github.com/zeelux/ko-lodash-bridge
