### ISSUE TITLE
Non-integer n values break takeRight, drop, dropRight, others?

### ISSUE THREAD

**Issue by dwighthouse** [lodash/lodash#1377]
I wished to split a list of items into two lists, with roughly even numbers of items in both, making the first list contain one more than the second list if the count was non-even. When exploring how to accomplish this, I ran into an issue due to my dividing the list count by 2 and using that value as the n value in the `take` and `takeRight` functions. Obviously, an odd number divided by 2 will result in a non-integer value. This led me to discover that certain functions, including `takeRight`, `drop`, and `dropRight` will return incorrect or unexpected results when given an n value that is a non-integer. There may be other functions similarly effected, but I have not tested for them. Looking briefly at the tests, it looks like non-integer n values are ignored as a possibility.

Examples and failures:
```js
> _.VERSION
"3.10.1"

> _.take([1, 2, 3, 4, 5], 2)
[1, 2]

> _.take([1, 2, 3, 4, 5], 3)
[1, 2, 3]

> _.take([1, 2, 3, 4, 5], 2.5)
[1, 2]
// ^ Seems correct, equivalent of using n = 2

> _.takeRight([1, 2, 3, 4, 5], 2)
[4, 5]

> _.takeRight([1, 2, 3, 4, 5], 3)
[3, 4, 5]

> _.takeRight([1, 2, 3, 4, 5], 2.5)
[3, 4]
// ^ Failure case, missing the last array value

> _.drop([1, 2, 3, 4, 5], 2)
[3, 4, 5]

> _.drop([1, 2, 3, 4, 5], 3)
[4, 5]

> _.drop([1, 2, 3, 4, 5], 2.5)
[3, 4]
// ^ Failure case, missing the last array value

> _.dropRight([1, 2, 3, 4, 5], 2)
[1, 2, 3]

> _.dropRight([1, 2, 3, 4, 5], 3)
[1, 2]

> _.dropRight([1, 2, 3, 4, 5], 2.5)
[1, 2]
// ^ Probably failure case, expected same output as using n = 2

This applies to any non-integer that doesn't implicitly convert to an integer due to precision:

> _.takeRight(list, 2.999999999999999)
[3, 4]

> 2.999999999999999
2.999999999999999

> _.takeRight(list, 2.9999999999999999)
[3, 4, 5]

// Because this number is 3 as far as JS is concerned
> 2.9999999999999999
3
```

**Comment by jdalton** [comment]
We tackle this in other methods by simply flooring the `n` value. Would that work for you?

**Comment by dwighthouse** [comment]
@jdalton I have already solved the issue in my code using floor and ceil functions, yes. But I would recommend either making these functions operate as expected with non-integers, or mentioning in the docs that n must be an integer, otherwise one might experience unexpected results.
