### ISSUE TITLE
find() using array with null values causes TypeError

### ISSUE THREAD

**Issue by nkibler7** [lodash/lodash#1378]
Using _.find() with null values in an array causes a TypeError to be thrown if the predicate looks for property values. For example:

    var array = new Array(5);
    _.find(array, {id: 1});

... throws:

    TypeError: Cannot read property 'id' of null

**Comment by jdalton** [comment]
I believe this has been fixed since 3.0.

**Comment by nkibler7** [comment]
Oops, didn't notice how out-of-date my package.json was! Thanks for the quick response!
