### ISSUE TITLE
Chunk by predicate function

### ISSUE THREAD

**Issue by aj0strow** [lodash/lodash#1379]
Hey what are your thoughts on a `chunkBy` method like ruby's [Enumerable#chunk](http://ruby-doc.org/core-2.2.2/Enumerable.html#method-i-chunk). It's useful for threading related posts. 

```javascript
var threads = chunkBy(posts, post => post.user.id)
// [
//   [ "user-1", [ {post}, {post} ] ],
//   [ "user-2", [ {post} ] ],
//   [ "user-1", [ {post} ] ],
// ]
```

It's different from `groupBy` because it groups and maintains order. It feels more general than `chunk` as you could implement `chunk` with `chunkBy` using index division.

Yeah I guess it felt missing is all. Thanks for your time.

**Comment by aj0strow** [comment]
This is from my project, hoping to give back.

```javascript
function chunkBy (collection, predicate, context) {
  var chunks = []
  var prevKey = null
  var chunkValues = []
  each(collection, function (value) {
    var key = predicate.apply(context, arguments)
    if (key == prevKey) {
      chunkValues.push(value)
    } else {
      // Guard against init values
      if (chunkValues.length) {
        chunks.push([ prevKey, chunkValues ])
      }
      prevKey = key
      chunkValues = [ value ]
    }
  })
  // Push hanging values
  if (chunkValues.length) {
    chunks.push([ prevKey, chunkValues ])
  }
  return chunks
}
```

**Comment by jdalton** [comment]
Hi @aj0strow! While I'm not against a `_.chunkBy` method let's wait and see if demand picks up for it.

**Comment by aj0strow** [comment]
Sure, thanks for taking a look.

**Comment by gtrak** [comment]
+1 please, a colleague had to implement clojure's partition-by with reduce today: check out the heatmap for relative usage vs other core clojure functions :-) : http://conj.io/heatmap

**Comment by ahuff44** [comment]
I'd love to see this implemented into lodash

**Comment by saikatguha** [comment]
+1 for round-robin distribution [1,2,3,4,5,6,7,8,9] => [1,4,7] [2,5,8] [3,6,9]

**Comment by jrencz** [comment]
+1 from me as well.
Right now I do groupBy + reduce + sortBy chain to achieve that.

**Comment by maowug** [comment]
+1 for me. `splitWith` makes more sense?
```scala
def splitWith[A](col: List[A], f: A => Boolean): List[List[A]] = ???
```

**Comment by fega** [comment]
+1

**Comment by masaeedu** [comment]
@jdalton What's the average number of votes need for this kind of thing? AFAICT there's no way to split an array/string/whatever by a delimiter, which seems like a pretty basic use case.

**Comment by jdalton** [comment]
There is no set vote goal. Votes are an indicator of popularity.

**Comment by masaeedu** [comment]
@jdalton PR #2452 was turned down until the popularity of this request is a bit higher. How much higher does the popularity need to be in order for the PR to be merged?

**Comment by jdalton** [comment]
I've already said that there is no set goal. I'm not looking to increase the number of methods at this time but when it's time votes help with prioritization of new features.

**Comment by erikamjoh** [comment]
+1 vote for adding _.chunkBy or similar

**Comment by erikamjoh** [comment]
+1 vote for adding _.chunkBy or similar. Being able to chunk an array using null elements in the array as delimiters is helpful for plotting / working with data sets, esp chronological data that needs to be chunked into groups of continuous data points while preserving the order.

**Comment by damianobarbati** [comment]
+1 for this

**Comment by isuvorov** [comment]
May be will be useful:

```js
import get from 'lodash/get';
import set from 'lodash/set';
import forEach from 'lodash/forEach';
import groupBy from 'lodash/groupBy';

export default (collection, predicate) => {
  const chunks = [];
  const counts = {};
  const groups = groupBy(collection, predicate);
  while (Object.keys(groups).length) {
    forEach(groups, (group, key) => {
      const count = get(counts, key, 0);
      let chunk = chunks[count];
      if (!chunk) {
        chunk = [];
        chunks[count] = chunk;
      }
      chunk.push(group.pop());
      set(counts, key, count + 1);
      if (group.length === 0) delete groups[key];
    });
  }
  return chunks;
};
```

Implementation:
https://github.com/lskjs/lskjs/blob/master/packages/utils/src/chunkBy.js

Tests:
https://github.com/lskjs/lskjs/blob/master/packages/utils/tests/chunkBy.test.js
