### ISSUE TITLE
Add clear() to MapCache

### ISSUE THREAD

**Issue by thejameskyle** [lodash/lodash#1380]
Currently building a rich translator using `_.memoize`, it'd be nice to `memoizedFn.cache.clear()` when the language changes.

Since the API is following the native `Map` I figure it should include the `clear` method:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/clear

**Comment by megawac** [comment]
Why not just reset the map? `memoized.cache = {}`

**Comment by thejameskyle** [comment]
@megawac You mean `memoized.cache.__data__ = {}`, and I can, it's just not a nice API.

**Comment by jdalton** [comment]
Hey @thejameskyle! Related to #882, #1269.

**Comment by thejameskyle** [comment]
:hankey:

**Comment by jdalton** [comment]
The route would be to make `_.memoize.Cache = Map`.
The reason we punt on `clear` is because devs can do `_.memoize.Cache = WeakMap`.
