### ISSUE TITLE
.forEach : no `thisArg` argument supported

### ISSUE THREAD

**Issue by srg985** [lodash/lodash#1382]
Documentation for .forEach (https://lodash.com/docs#forEach) describes `thisArg` as 3rd optional param for iteratee this-binding. But there is no support for this param in code of 3.10 version.

**Comment by jdalton** [comment]
Support for the `thisArg` param is in [3.10.0](https://github.com/lodash/lodash/blob/3.10.0/lodash.js#L3342-L3348) and [3.10.1](https://github.com/lodash/lodash/blob/3.10.1/lodash.js#L3342-L3348).

It looks like you're grabbing the master branch copy which is pre 4.0.
