### ISSUE TITLE
combining before and after functions

### ISSUE THREAD

**Issue by oriSomething** [lodash/lodash#1384]
sometimes, i find myself need a function that combine `_.before` and `_.after`. meaning, something like `beforeAfter(beforeFn, afterFn, n)`which create a `function` where there is counter that before `n` it runs the `beforeFn` and after it passes `n` it runs `afterFn`

**Comment by jdalton** [comment]
Hey @oriSomething! Can you kick around a mixin and come back with it. That will help solidify your ideas and give something for others to :+1: around. We'll then be able to better gauge demand for it.

**Comment by oriSomething** [comment]
this is kind of what i use for now
```js
_.mixin({
  beforeAfterTemporaryName: function(before, after, when) {
    when = _.isFinite(when) ? when : 1;
    var counter = 0;

    return function() {
      if (counter < when) {
        counter += 1;
        return before.apply(this, arguments);
      }

      return after.apply(this, arguments);
    };
  }
});
```
