### ISSUE TITLE
normal usage vs. lodash benchmark

### ISSUE THREAD

**Issue by alsotang** [lodash/lodash#1387]
https://github.com/alsotang/fast-js

![image](https://cloud.githubusercontent.com/assets/1147375/9150238/515d712e-3e00-11e5-967c-b255a6670092.png)

is there any project do similar benchmarks that normal usage vs. lodash?

seeeems lodash is always fast, or less twisted

**Comment by jdalton** [comment]
I'm not sure, yours looks like a start :)

You'll find this trend over and over in JS because JS engines just haven't optimized as well as they could.
