### ISSUE TITLE
_.flow([]) -> ferture request

### ISSUE THREAD

**Issue by syzer** [lodash/lodash#1389]
Can we some somehow use flow with arrays of functions?
it would be very very useful at times.

**Comment by StreetStrider** [comment]
@syzer 
```js
var fns = [ fnA, fnB ]
_.flow.apply(null, funcs)
```

**Comment by syzer** [comment]
:+1: thanks!  stupid me :)

**Comment by syzer** [comment]
BTW that would opposite functor to `spread`?

**Comment by StreetStrider** [comment]
@syzer, I'm not sure it exists in LoDash. But for sure there is a gross composition of other functions to achieve this :)

**Comment by StreetStrider** [comment]
@syzer, maybe something like this:
```js
Fargs = _.flow(Array, Flist)
```

**Comment by syzer** [comment]
was thinking along these lines:
function fargs(arr){

}
[args].map()

**Comment by StreetStrider** [comment]
@syzer,
```js
var slice = [].slice
function shrink (fn)
{
  return function ()
  {
    return fn.call(this, slice.call(arguments))
  }
}
```

**Comment by jdalton** [comment]
Nice one with the `_.spread(_.flow)`. As for passing args as an array `_.restParam(fn, 0)`

**Comment by StreetStrider** [comment]
@jdalton, wow, `restParam` starting with 0 is elegant :thumbsup:

**Comment by megawac** [comment]
It will also default to `0`  as the function @StreetStrider showed has 1 argument

**Comment by syzer** [comment]
nice one with `restParam` :+1: i also like `shrink` implentation
