### ISSUE TITLE
bindAll is binding getters

### ISSUE THREAD

**Issue by OSUblake** [lodash/lodash#1390]
When I use `_.bindAll(this)` in my class constructor (TypeScript), it is binding the getters which causes them to be called. Is there a reason for this? Shouldn't it only be for types that are a function?

**Comment by jdalton** [comment]
Here's [the source](https://github.com/lodash/lodash/blob/3.10.1-npm/function/bindAll.js#L38). If you have support question try the [gitter room](https://gitter.im/lodash/lodash).

**Comment by OSUblake** [comment]
Ok. I think I see what's going on. `objToString.call(value)` in the isFunction check is causing the getters to be called, which made me think it was trying to bind them.

[Example](http://codepen.io/osublake/pen/b3d0753cdbe9042bf88cc8fa5c35b09d?editors=001)

**Comment by jdalton** [comment]
You can provide a list of method names to bind to avoid the getter access of the type checks.
