### ISSUE TITLE
sortBy doesn't support a _.property() style nested path

### ISSUE THREAD

**Issue by devinus** [lodash/lodash#1391]
The docs suggest it does:

> If a property name is provided for iteratee the created _.property style callback returns the property value of the given element.

**Comment by devinus** [comment]
JSBin: https://jsbin.com/mefuguwobu/edit?html,js,output

**Comment by jdalton** [comment]
Look to `sortByAll`.

**Comment by devinus** [comment]
@jdalton Why `sortByAll` rather than `sortBy` when I have a single key? `sortByAll` has the same description as `sortBy` in regards to the iteratee:

> If a property name is provided for an iteratee the created _.property style callback returns the property value of the given element.

So what makes `sortByAll` work different?

**Comment by jdalton** [comment]
sortByAll supports multiple iteratees.

**Comment by devinus** [comment]
But it's a single iteratee unless I'm misunderstanding. Does `foo.bar` split it into two iteratees?

**Comment by jdalton** [comment]
> Does foo.bar split it into two iteratees

Yes, `foo.bar` is one and the function is another.
