### ISSUE TITLE
isUndefined violates guidance from eslint

### ISSUE THREAD

**Issue by jeffhandley** [lodash/lodash#1392]
eslint explains why it's a bad practice to check for a value to `=== undefined`.  When addressing eslint issues in our codebase, we started converting those checks over to `_.isUndefined` but then realized that `isUndefined` itself is checking `=== undefined`.

Should `isUndefined` follow the guidance eslint gives and use `typeof foo === 'undefined'`?

http://eslint.org/docs/rules/no-undefined

**Comment by jdalton** [comment]
You shouldn't be linting third party libs. Our code is solid regardless of your particular linting rules.

**Comment by jeffhandley** [comment]
To be clear, we weren't linting lodash. We were linting our code and looked to use isUndefined to improve our code. And then we were curious why you chose to use undefined rather than typeof and if it was an intentional choice over the typeof approach.

**Comment by jdalton** [comment]
I've flip flopped a bit on style, from `typeof` to the `===` checks. It's based on preference. I reference and internal `undefined` var so avoid the issues linters are trying to guard against (es3 enviros that let you redefine `undefined`).

**Comment by jeffhandley** [comment]
Thanks, I appreciate the info.

**Comment by jeffhandley** [comment]
One more follow-up question on this; I hope you don't mind.  We are using lodash on a per-method basis.  Looking at that, it seems `isUndefined` does not use the internal `undefined` var but rather the global.

https://github.com/lodash/lodash/blob/npm-packages/lodash.isundefined/index.js

What would you think about having `lodash.isundefined` define `undefined` as a local?

**Comment by jdalton** [comment]
Looks like a build bug. What environments are you supporting targeting for your code?

**Comment by jdalton** [comment]
Actually not a build bug. We remove the local `undefined` var in all but AMD builds because things like the npm packages run in Node where `undefined` is immutable anyways.

**Comment by jeffhandley** [comment]
Ah - we're using the modularized build for an isomorphic React application, transpiled with webpack. So we're using the same function both from Node and from the browser.

To ensure our client app bundles are as small as possible, we're referencing lodash functions like this:

```
let _ = {
    isObject: require('lodash/lang/isObject'),
    isUndefined: require('lodash/lang/isUndefined')
};
```

The result is our webpack-generated client app bundles have code like this:

```
var _ = {
    isObject: __webpack_require__(286),
    isUndefined: __webpack_require__(23)
};
```

And isUndefined is defined (as `__webpack_require__(23)`) here:

```
/***/ },
/* 23 */
/***/ function(module, exports) {

	/**
	 * Checks if `value` is `undefined`.
	 *
	 * @static
	 * @memberOf _
	 * @category Lang
	 * @param {*} value The value to check.
	 * @returns {boolean} Returns `true` if `value` is `undefined`, else `false`.
	 * @example
	 *
	 * _.isUndefined(void 0);
	 * // => true
	 *
	 * _.isUndefined(null);
	 * // => false
	 */
	function isUndefined(value) {
	  return value === undefined;
	}

	module.exports = isUndefined;
```

It seems like it comes down to the question of whether or not you'd expect lodash to be used after running the per-method modules through webpack, or if you'd just suggest using your minified redist.  We were trying to keep our list of redist libraries to a minimum, driving us to use the webpack approach you see here, resulting in a smaller payload (and fewer HTTP requests).

**Comment by jdalton** [comment]
Seems like smth webpack might add during the bundling process. In web browsers `undefined` is immutable in IE9+ and modern browsers so that shouldn't be an issue either.

**Comment by jridgewell** [comment]
Why not just use `void 0` everywhere?

**Comment by jdalton** [comment]
Because that's hella lame.

**Comment by jdalton** [comment]
It's a horrible hackish solution or a non-issue.

**Comment by jdalton** [comment]
fwiw minifiers tend to convert `undefined` to `void 0`

**Comment by jeffhandley** [comment]
Ah, I see what is happening through webpack (and ultimately babel).  It looks like it is (very subtly) ensuring we're safe.

```
/***/ },
/* 266 */
/***/ function(module, exports, __webpack_require__) {

	/* WEBPACK VAR INJECTION */(function(clearImmediate, process) {(function (global, undefined) {
	    "use strict";
```

But of course when this module is referenced, only the `global` argument is supplied so `undefined` becomes truly undefined, and all methods called from within there would have this undefined `undefined` within scope.

Thanks for helping me track this down -- I think you're right; I think it's a non-issue.
