### ISSUE TITLE
Q: Link to lodash-element for usage as a webcomponent

### ISSUE THREAD

**Issue by Waxolunist** [lodash/lodash#1393]
Hello
I created a webcomponent for importing lodash in other webcomponents for sharing. Nothing fancy.
May I make a PR and link to it in your README? It may be useful to others when they want to use lodash in webcomponents. What's the right way for it?

https://github.com/Waxolunist/lodash-element

/Kind regard

**Comment by jdalton** [comment]
Hi @Waxolunist. There are lots of lodash related things. I'm not sure this meets the bar as it's essentially a script tag. Let's see if `lodash-element` has traction before considering additions to the readme/wiki.

**Comment by Waxolunist** [comment]
Ok, lets wait. I know it's not much. It's just a wrapper for easy integration into webcomponents. It's like having an amd module for webcomponents. You could integrate the html into the lodash repository as well.
Thx for the reply
