### ISSUE TITLE
why isNumber is not isNumeric ?

### ISSUE THREAD

**Issue by alundiak** [lodash/lodash#1394]
I've read closed issues (not refering and no reopening to reduce mess), but not found strict answer. Looks like to use `isNumber()` is expected by LODASH to have pre-casted value from string (if such). So is it correct and designed logic?

` _.isNumber(2.3)` => true
and 
` _.isNumber("2.3")` => false.
For sure we can use casting:
` _.isNumber(+"2.3")` => true, but IMHO, it's not OK from LODASH side.

My team balance now between usage either JQUERY isNumeric
```
$.isNumeric -> function ( obj ) {
    return !isNaN( parseFloat(obj) ) && isFinite( obj );
}
```
or our own isNumeric:
```
function isNumeric(data) {
    return !isNaN(parseFloat(data)) && isFinite(data) && data.constructor !== Array;
}
```
or, which we thought is the best choice to RELY) LODASH.isNumber()
No we doubt ...

It looks like we have powerful lodash, but for simple isNumber check we have to have other way (simple casting by + or dedicated function). I think it's not ok.

**Comment by jdalton** [comment]
Your request for `_.isNumeric` is noted.
