### ISSUE TITLE
add `reductions` fn from Clojure world

### ISSUE THREAD

**Issue by dustingetz** [lodash/lodash#1395]
https://clojuredocs.org/clojure.core/reductions

```javascript
function reductions (coll, iteratee, seed) {
  var steps = [];
  var sum = coll.reduce((acc, val, i) => {
    steps.push(acc);
    var acc = iteratee(acc, val, i);
    return acc;
  }, seed);
  steps.push(sum);
  return steps;
}
```
```
this.measuredHeights = measureChildHeights(domItems);
this.measuredDistances = reductions(this.measuredHeights, (acc, val) => { return acc+val; }, 0);
```

**Comment by jdalton** [comment]
Hi @dustingetz. Lodash has a `_.sum` function so I think this can be achieve through composition instead.

**Comment by dustingetz** [comment]
No, this can't be achieved with `sum`. `reductions` returns a list of the intermediate values as they are accumulated (the last value in the list is the completely reduced value)

**Comment by jdalton** [comment]
Ah cool. I'm still unclear with what this method is handy for. Maybe a simpler example would help.

**Comment by dustingetz** [comment]
My particular use case is an infinite scroll component that needs to measure the heights of his visible children elements once they are in the dom, and also needs to compute each child's distance from the top of the view for scroll logic. [Here is my use case in context](https://github.com/dustingetz/react-infinite/blob/b52d48c3c0ed1f41ac778e3b58c1242325b35d35/src/react-infinite2.jsx#L184-L185). 

Perhaps `reductions` is more useful in clojure since it is lazy and can be used on streamy things.

**Comment by dustingetz** [comment]
```
cljs.user=> (map first (reductions (fn [[a b] _] [b (+ a b)]) [0 1] (range 10)))
(0 1 1 2 3 5 8 13 21 34 55)
```
