### ISSUE TITLE
new function isNil ?

### ISSUE THREAD

**Issue by xixilive** [lodash/lodash#1399]
we need write "var === null || var === undefined" to check a NOTHING value, it's a suggestion to do it better.

```
function isNil(value){
  return value === undefined || value === null;
}
```

**Comment by anthony-redFox** [comment]
@xixilive you can write `value == null`, it is the same  `value === null || value === undefined`

**Comment by xixilive** [comment]
@anthony-redFox  strict equals is recommended in strict mode

**Comment by falsyvalues** [comment]
@xixilive Doesn't mean you have to follow this rule in every case,  ```value == null ``` is very handy and it's operator not function call.

**Comment by oriSomething** [comment]
@xixilive if the strict equal problem is because `jshint` than move to [`ESLint`](http://eslint.org/).

**Comment by jdalton** [comment]
Yap, an `_.isNil` is something that's been needed for a while. @xixilive Want to create a PR?

**Comment by xixilive** [comment]
i'll try my best @jdalton

**Comment by jdalton** [comment]
Moving over to #1402.
