### ISSUE TITLE
_.property: add an optional parameter defaultObject

### ISSUE THREAD

**Issue by thorn0** [lodash/lodash#1400]
So that if the returned function is called with no arguments, it'd evaluate and return the property value on that default object.

```js
var getter = _.('foo.bar', obj);
getter(); // returns obj.foo.bar
```

**Comment by jdalton** [comment]
Let's keep `_.property` simple. You can always partially apply `get` or `result`:
```js
var getter _.partial(_.get, _, _, obj);
```

**Comment by sc0ttyd** [comment]
I know that this is done and dusted, but I agree with @thorn0, I think that having a default for _.property makes sense too. _.property is like a _.partial'ed _.get already and _.get has the default option, so why not _.property?

**Comment by jdalton** [comment]
@sc0ttyd For now you can the [FP module](https://github.com/lodash/lodash/wiki/FP-Guide) like `require('lodash/fp/getOr')`.
