### ISSUE TITLE
Standard utils lib

### ISSUE THREAD

**Issue by kof** [lodash/lodash#1404]
I know, its a kinda bold move but, what if:

1. We create an organization called "standard-utils" or similar
2. Create a repository for every lodash function
3. Allow contributions for every possible utility function, without to fear a big total build size, because there will be no single final build at all.
4. Build every function as small and independent as possible, take the trade off of having bigger total size. Most projects need just a bunch of functions anyways.
5. Just one way to include functions, there should be no different build types to avoid duplication.

**Just one goal in mind:** a standard set of utilities every other lib can use and though achieve an overall smaller size of applications and finally STOP the madness of utility functions being created in every lib over and over.

**Comment by koulmomo** [comment]
are modular requires in v3 not good enough? (see: https://github.com/lodash/lodash/releases/tag/3.0.0, search for the string "Modules, modules, modules")

> The lodash & lodash-compat npm packages now come with modules baked in too. 
Perfect for browserify and webpack!
```
// load the modern build
var _ = require('lodash');
// or a method category
var array = require('lodash/array');
// or a method
var chunk = require('lodash/array/chunk');
The method modules are organized by category so they’re easy to find.
```

**Comment by kof** [comment]
the difference to my proposal is:
1. lodash is a lib, limited in its amount of functions, org will allow to contribute more functions, things which has been rejected for some reason.
2. has lots of different ways to include it -> lots of possibilities to get the same function twice.
3. isn't designed for smaller size of each module (I know you already on the way to change that.)

**Comment by jdalton** [comment]
Hi @kof!

> 1) lodash is a lib, limited in its amount of functions, org will allow to contribute more functions, things which has been rejected for some reason.

As part of lodash v4 we'll offer a 4kb core build (won't get bigger than that) and allow devs to use the kitchen sink if they want.

Managing over 200 separate repos is not doable. For example [these issues](https://github.com/substack/array-reduce/issues) are almost 2 years old.

> 2) has lots of different ways to include it -> lots of possibilities to get the same function twice.

I'm ok giving devs options. The potential for a little overlap isn't a big worry.

> 3. isn't designed for smaller size of each function (I know you already on the way to change this.)

I'm not a fan of promoting code golf as a code style. Our methods are as big as they need to be. In 4 I've removed a lot of the overloading from previous versions to keep the methods focused and made managing the features they support more customizable in v4.

**Comment by kof** [comment]
> Managing over 200 separate repos is not doable. For example these issues are almost 2 years old.

It will need more maintainers, distributed responsibility.

**Comment by kof** [comment]
> I'm ok giving devs options. The potential for a little overlap isn't a big worry.
Then people should just continue include own utils in their libs. Its all or nothing. Buying potentially a bigger size and another dependency can be only justified by a big   idea of a "standard". If standard is sloppy, nothing will change.

**Comment by jdalton** [comment]
> It will need more maintainers, distributed responsibility.

Why? The current way requires fewer maintainers. I manage 300+ packages, and several spin-offs, spawned from 1 project.

> Then people should just continue including own utils in their libs. Its all or nothing. 

Naw, we give devs lots of options and they dig it. Some like cherry-picking, some like individual packages, some like amd, some like es6, some like more FP style. The pizza (utilities) can be sliced up in lots of different ways with lots of flavors (like [lodash-fp](https://www.npmjs.com/package/lodash-fp)) but it's still pizza (utilities).

> Buying potentially a bigger size and another dependency can be only justified by a big idea of a "standard". If standard is sloppy, nothing will change.

What?

**Comment by kof** [comment]
Sloppy because of all the distributions ... there is no single source of truth. All this different builds should be part of user tooling, which is for sure not a problem nowdays.

**Comment by jdalton** [comment]
> Sloppy because of all the distributions ... there is no single source of truth. All this different builds should be part of user tooling, which is for sure not a problem nowdays.

The single source of truth is the lodash source. All others are slices or wrapped forms of that. I tried having users rely on tooling with [lodash-cli](https://www.npmjs.com/package/lodash-cli) but folks avoided it because it didn't align 100% with their package manager of choice or bundling needs.

**Comment by kof** [comment]
I would also try to avoid it)))

I think we need to take a look at use cases. I am sure all of them are covered by webpack, for browserify it may require extra plugin and can be solved by documentation.

**Comment by kof** [comment]
I assume those two are 99% of what people use and I assume all differences is amd vs. commonjs.

**Comment by jdalton** [comment]
>  I am sure all of them are covered by webpack, for browserify it may require extra plugin and can be solved by documentation.

You'd think right? It turns out devs have pretty strong opinions on their tooling. So meeting them where they are worked for lodash.

**Comment by kof** [comment]
Well, maybe its time to change things, lodash can continue serve for this 1-5% users with their custom build needs and "standard-utils" would be the next thing ...

**Comment by jdalton** [comment]
> Well, maybe its time to change things, lodash can continue serve for this 1-5% users with their custom build needs and "standard-utils" would be the next thing ...

I'm happy keeping the utils under one roof. Size isn't an issue so we'll add what's required based on popular demand. I'm also not a fan of the whole "standard" naming biz.
