### ISSUE TITLE
_.isPrimitive

### ISSUE THREAD

**Issue by rafde** [lodash/lodash#1406]
Using MDN Definition of [primitive](https://developer.mozilla.org/en-US/docs/Glossary/Primitive)

> A primitive (primitive value, primitive data type) is data that is not an object and has no methods. In JavaScript, there are 6 primitive data types: string, number, boolean, null, undefined, symbol (new in ECMAScript 2015).

We can have a function 
```
function isPrimitive(value){
  return _.isNil(value) || _.isNumber(value) || _.isBoolean(value) || _.isString(value) || typeof value === 'symbol';
}
```
or use [this PR](https://github.com/lodash/lodash/pull/7)

**Comment by jdalton** [comment]
Hi @rafde!

You can use `!_.isObject(value)` or `_.negate(_.isObject)`

**Comment by rafde** [comment]
That works. thanks.

**Comment by moranje** [comment]
Hi @jdalton,

I just wanted to add the following use case for the team to consider if there may still be merit to adding it. 

I was looking for a way to check if a value is NOT a primitive.
```js
if (_.isNil( value ) || _.isObject( value ) || _.isFunction( value ) ) {
  // Do stuff, throw errors, get a coffee or just don't do anything at all.
}
``` 
which could be written a little more elegant this way:
```js
if ( !_.isPrimitive( value ) ) {
  // Do stuff, throw errors, get a coffee or just don't do anything at all.
}
``` 
Martien
