### ISSUE TITLE
Can I compare arrays without considering the orders or data types?

### ISSUE THREAD

**Issue by kitz17** [lodash/lodash#1408]
I am trying to compare arrays of numbers
```
var a = [0.5, 1];
var b = ['0.5', '1'];
var c = [1, 0.5];
var d = [0.5, 1];
_.eq(a, b); // false
_.eq(a, c); // false
_.eq(a, d); // true
_.eq(c, d); // false
```
I want to make `_.eq(a, b)` and `_.eq(a, c)` to be `true`

**Comment by jdalton** [comment]
Hi @kitz17! You can use the `customizer` callback to handle this:
```js
_.isEqual(a, b, function(a,b) { return a == b; });
```

**Comment by kitz17** [comment]
Thank you for the suggestion, but unfortunately it does not work.
```
> lodash.isEqual([0.5, 1], [1, 0.5], function (a, b) { return a == b; })
false
> lodash.isEqual([0.5, 1], ['0.5', '1'], function (a, b) { return a == b; })
false
```

**Comment by jdalton** [comment]
Sorry, try:
```js
_.isEqual([0.5, 1], ['0.5', '1'], function (a, b) {
  return (_.isObject(a) || _.isObject(b)) ? undefined : a == b;
});
```

**Comment by kitz17** [comment]
It works, but only for comparing `[x, y]` with `['x', 'y']`, not also with `[y, x]` or `['y', 'x']`

**Comment by jdalton** [comment]
I've pointed you in the right direction. Continue down that path.

**Comment by jdalton** [comment]
For more assistance check out our [gitter room](https://gitter.im/lodash/lodash).

**Comment by StreetStrider** [comment]
@kitz17, maybe `difference(A, B) = ∅ and difference(B, A) = ∅`?, but, sadly, `_.difference` uses SameValueZero and not customizable. And this will require two passes :(

**Comment by jdalton** [comment]
> uses SameValueZero and not customizable. And this will require two passes :(

It's customizable just not pretty. You can overwrite `_.indexOf` to affect equality checks of methods like `difference`, `uniq`, `intersection`, etc.
