### ISSUE TITLE
endsWith target param and passing null

### ISSUE THREAD

**Issue by softwarespot** [lodash/lodash#1409]
Shouldn't passing null default to '' (empty string) just like the string param does? I respect if this is a design choice and it does beg the question why would anyone want to check a string ends with '', but then I was thinking about consistency.

**Source:** https://github.com/lodash/lodash/blob/master/lodash.js#L9841

**Comment by jdalton** [comment]
At the moment we follow the spec'ed behavior to coerce the target to a string. The handling nullish handling of strings is really for the `string` itself and not so much for other params.

**Comment by softwarespot** [comment]
Cool. Thanks.

**Comment by jdalton** [comment]
You can see this with `_.includes` or even `String#indexOf` too.
