### ISSUE TITLE
Consider removing exit iteration by explicitly returning false, due to es6 arrow function implicitly returning values 

### ISSUE THREAD

**Issue by gravitypersists** [lodash/lodash#1410]
Consider the line:

`_.forEach([{a:true}, {a: true}], (x) => x.a = false)`

which implicitly returns false, mutating the array to be `[{a:false}, {a:true}]` - probably not what the programmer intended to do here.

(I understand underscore and the underscore build don't exit iteration on false returns)

Or everybody will need to trip up to see that they should be doing this for those special occasions:

`_.forEach([{a:true}, {a: true}], (x) => {x.a = false})`

A suggestion: introduce a _.break() method which exits iterations?

**Comment by jdalton** [comment]
I like exiting early from `_.forEach`, `_.forEachRight`, `_.forIn` `_.forInRight`, `_.forOwn`, & `_.forOwnRight`. Adding `{}` is easy enough.

**Comment by StreetStrider** [comment]
@gravitypersists 
> a _.break() method

I'm interested how this method should work? I consider simpler solution: `_.breaker` object which works like `false`, except it's like a Symbol (`_.breaker = {}`) and does not interfere with `false` (and any other value).

**Comment by jdalton** [comment]
I want to keep it simple. jQuery has had exiting early support in its `$.each` since the beginning.
I find it more powerful than relying solely on `_.every` or `_.some`
