### ISSUE TITLE
Omit nested properties

### ISSUE THREAD

**Issue by sofianito** [lodash/lodash#1411]
Sorry if am posting in the wrong place.

I am looking for a variant of omit function that support nested properties. Example: 
```js
var obj = {a:{b:{c:1,d:2}};
var res = _.omit(obj, 'a.b.d'); // res = {a:{b:{c:1}}
```
Does it already exist? If not, how complicated is it to implement?

Thanks.

**Comment by jdalton** [comment]
This doesn't exist in lodash. It would be similar to a merge but with a list of properties to skip. At the moment we don't have a way, even with the `customizer`, to skip a property assignment.

I'll keep an eye on demand for this feature for the future.

**Comment by jamlen** [comment]
:+1: the fact that `_.get(obj, 'a.b.c')` works but `omit` does not is a real pain.

**Comment by jamlen** [comment]
As a result of `omit` not working for paths, I went searching and found [object-path](https://github.com/mariocasciaro/object-path) which does what I currently need but I would like to see this supported in lodash.

**Comment by REAANDREW** [comment]
:+1:

**Comment by dfairaizl** [comment]
Agreed, while [object-path](https://github.com/mariocasciaro/object-path) does do what I need as well, seeing support for this in lodash would be fantastic :+1:

**Comment by jdalton** [comment]
Can you provide an example usage of *object-path* that satisfies the `omit` case.

**Comment by dfairaizl** [comment]
@jdalton Of course.

We get JSON from a service that needs to be cleaned up - and right now my use case is we know the exact keys and all we do is delete them. Here is an example for this use case: 

```
var badData = {
  badKey: 'this is a bad key that needs to be deleted',
  nested: {
    anotherBadKey: 'This is a bad key, nested, that needs to be deleted'
  }
};

var cleanData = _.omit(badData, 'badKey'); // normal lodash omit
cleanData = _.omit(cleanData, 'nested.anotherBadKey'); // Lodash omit using object path selectors
objectPath.del(cleanData, "nested.anotherBadKey"); // Current workaround using object-path
```

Does that make sense?

**Comment by jdalton** [comment]
I mean can you show the *object-path* usage.

**Comment by dfairaizl** [comment]
It's the last line in the example - sorry that wasn't clear.

**Comment by jdalton** [comment]
In lodash v4 (wip in master branch) we have an `unset` method which is similar to `objectPath.del`.

**Comment by jamlen** [comment]
So I have this in a lodash mixin:

```javascript
var objectPath = require('object-path');

mixins.delPath = function(obj, path) {
    objectPath.del(obj, path);
    return obj;
};  
```

My usage is that I do not know the paths I need to delete directly and I use another mixin to produce a list of paths that match my criteria. Then I want to remove that path. So a cut down version might be:

```javascript
var data = { 
  root: { 
    name: 'abc', 
    parent: { 
      name: 'parent', 
      id: { 
        type: 'fkMapping', 
        value: 123456 
      }
    },
    another: {
       beGone: true
    }
  }
}; 

var paths =  ['root.parent.id', 'root.another.beGone']; //some code to work out the path to delete

_.each(paths, function(path) {
  _.delPath(data, path);
});
```

**Comment by fcamblor** [comment]
:+1: on this (could we reopen the discussion ? or maybe start another issue ?)

@jdalton `_.unset` is not fitting my needs currently as I don't want to mutate object (`_.omit` is returning a new copy of the object)

Currently, the only way I found to workaround this is to combie `_.extend` & `_.omit` in my sub-properties

That is to say :
`var filteredData = _.extend({}, _.omit(obj, "foo"), {foo: _.omit(obj.foo, "bar")});`
which would be much more readable if I would have put something like :
`var filteredData = _.omit(obj, 'foo.bar')`

**Comment by jdalton** [comment]
For an immutable flavor of `unset` you can use the [fp modules](https://github.com/lodash/lodash/wiki/FP-Guide) as `require('lodash/fp').unset` or `require('lodash/fp/unset');

**Comment by OzzieOrca** [comment]
For anyone coming here from Google, this appears to be supported now.
https://github.com/lodash/lodash/wiki/Changelog#v4170
https://github.com/lodash/lodash/compare/4.16.6...4.17.0#diff-c1129c8b045390789fa8ff62f2c6b4a9R16356
