### ISSUE TITLE
feature request: iterate over collections recursivelly deferring callback functions to next tick

### ISSUE THREAD

**Issue by borisdiakur** [lodash/lodash#1412]
Here is what I'm thinking of:

```js
module.exports = function (array, iteratee) {
    var index = -1,
    length = array.length;

    (function rec() {
        if (++index < length) {
            if (iteratee(array[index], index, array) !== false) {
                process.nexTick(rec);
            }
        }
    })();
};
```

__Why would this be usefull?__

```js
_.each(veryLongArray, heavyCalculation); // blocks the process
_.eachRec(veryLongArray, heavyCalculation); // doesn't block the process that much
```

What do you think?

**Comment by jdalton** [comment]
Hi @borisdiakur! This sounds like something for ES6  [generators/iterators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) or [async](https://www.npmjs.com/package/async).

**Comment by borisdiakur** [comment]
Indeed [async](https://www.npmjs.com/package/async) coveres this with [ensureAsync](https://github.com/caolan/async#ensureasyncfn) already:

```js
async.eachSeries(veryLongArray, async.ensureAsync(heavyCalculation), done);
```

**Comment by StreetStrider** [comment]
@borisdiakur,
```js
var Promise = require('bluebird')
Promise.resolve([1, 2, 3]).map(heavyCalculation) // → promise
```

**Comment by StreetStrider** [comment]
@borisdiakur, maybe this lib will be interesting for you: http://highlandjs.org/

**Comment by borisdiakur** [comment]
Thanks @StreetStrider !
