### ISSUE TITLE
Issue when merging an array of typed objects

### ISSUE THREAD

**Issue by wardva** [lodash/lodash#1413]
I think there is a problem with the `_.merge` method. When I try to merge an array with objects, where the one of the arrays is an array of typed objects, and the other array contains plain javascript objects, the result is not correct. When I try to do the same with 2 objects (first object is a typed object, the second object is a plain javascript object), not wrapped in an array, I don't have this problem.

Example
```javascript
var o1 = new MyObject({
    name: 'object name',
    description: 'object description'
});

var o2 = {
    name: 'object name 2',
    color: 'blue'
};

_.merge(o1, o2);
// -> {name: 'object name 2', color: 'blue', description: 'object description'}

_.merge([o1], [o2]);
// -> [{name: 'object name 2', color: 'blue'}]
```

As you can see, the result when merging 2 arrays is not correct.

Currently I fixed this by using the map method to merge each object seperately:
```javascript
var merged = _.map(array1, function(old, index) {
    return _.merge(old, array2[index]);
});
```

**Comment by jdalton** [comment]
Hi @wardva! Oddly enough this behavior is by design. When we run into non-plain objects we avoid merging them as we don't know what we'll get. It could be a DOM element or something more wonky. So they overwrite whatever the destination value is.

You can customize merging with the `customizer` param of `_.merge` though:

```js
_.merge(a, b, function(oldVal, newVal) {
  if (newVal instanceof MyObject) {
    return _.assign({}, oldValue, newVal);
  }
});
```

**Comment by jdalton** [comment]
Ah oops. Misunderstood the issue. I see the problem now.
