### ISSUE TITLE
Feature request: Deep unset()

### ISSUE THREAD

**Issue by joshuaprior** [lodash/lodash#1418]
I'm not sure if this the correct place to make a feature request...

I'm looking for a way to delete an attribute from an object using a deep path similar to _.set(). It doesn't look like lodash currently supports this.

I thought a reasonable name for this function would be _.unset(). Also it would be nice if it returned the value of the attribute before it was deleted from the object, or undefined if the path does not exist.

Assuming there's not a reason against adding this functionality, I would be interested in contributing this enhancement if it's not a super quick change for someone that's experienced with the lodash source. I'm just starting to read through the contributing doc.

Thanks.

**Comment by jdalton** [comment]
I'm not sure about the `return value` part. I think behaving like `delete` and returning `true` if the property was unset and `false` if it wasn't is the way to go.

I've asked for PRs for adding `_.unset` in the past but no one has taken it on. Go for it @joshuaprior!

**Comment by jdalton** [comment]
I'll close this for a PR. Go go PR.
