### ISSUE TITLE
_.has() on property containing zero value returns false

### ISSUE THREAD

**Issue by FrankZZ** [lodash/lodash#1425]
```js
var lodash = require('lodash');
var test = {
    frank: {
        justTesting: 0
    }
};
console.log(lodash.has(test, 'frank.justTesting'));
```
It will log false, but the object has the property, although it has value zero

**Comment by falsyvalues** [comment]
```
_.has({x:0}, 'x')
// => true
```

What version you have there? Check ```_.VERSION```.

**Comment by FrankZZ** [comment]
@falsyvalues I'm sorry, I was under the impression that I was running latest lodash version 3.10.1 from an ```npm install```, but I just discovered that it was 2.4.2 because it was locked in my package.json in the pwd.

This issue can be ignored
