### ISSUE TITLE
Add isInstanceOf function

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#1428]
`isInstanceOf` must be the equivalent of using `instanceof` operator. The problem with using the operator directly is that the negate condition is hard to read, e.g.

```js
if ({} instanceof Error) {
    // Good
}

if (!({} instanceof Error)) {
   // Bad
}
```

Using `isInstanceOf` would prevent a possible error of negating the subject, e.g.

```js
if (!{} instanceof Error) {
   // Unintentional condition.
}
```

`isInstanceOf` is a lot easier to read in both scenarios:

```js
if (_.isInstanceOf({}, Error)) {

}

if (!_.isInstanceOf({}, Error)) {
    
}
```

**Comment by gajus** [comment]
I am happy to create a PR if this is accepted.

**Comment by jdalton** [comment]
Hey @gajus! Let's see if there's a demand for this before jumping into a PR.
I'll bikeshed the name though, `isOf` :)

**Comment by StreetStrider** [comment]
If it would be implemented, it should have Type as first argument for better currying. And if so, it should better have other name to prevent misunderstanding with `instanceof`'s operand order.
