### ISSUE TITLE
Add Œ to _.deburr

### ISSUE THREAD

**Issue by NTag** [lodash/lodash#1430]
It would be very useful that _.deburr replaces Œ with Oe and œ with oe.

I tried to do it, but œ is not in https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block)#Character_table :(

(It is used in French, for example in "œufs" (which means eggs))

**Comment by jdalton** [comment]
Which category is it in?

**Comment by NTag** [comment]
Feature request? enhancement label is good.

**Comment by jdalton** [comment]
I mean unicode category. If not latin1 supplimental.

**Comment by tcrouch** [comment]
The oe ligatures are a part of [Latin Extended A](https://en.wikipedia.org/wiki/Latin_Extended-A).

Œ (`\u0152`): `&#x152;`, `&#338;`, `&OElig;`
œ (`\u0153`): `&#x153;`, `&#339;`, `&oelig;`

**Comment by jdalton** [comment]
Thanks @tcrouch! We'll keep an eye on demand for this. Until then you can always make a mixin to extend support.

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash/commit/316b84536c41ff4869397bac08ce84e48772a781.
