### ISSUE TITLE
Factory function?

### ISSUE THREAD

**Issue by lcarva** [lodash/lodash#1437]
Is there a way to create a function that creates a new instance based on a given "class"?

    function Person(name) {
       this.name = name;
    }

    var makePerson = function(name) {
       return new Person(name);
    }
    // Is there something like this?
    // var makePerson = _.factory(Person);

    var bob = makePerson('bob');
    bob.name; // 'bob'
    bob instanceof Person; // true

**Comment by jdalton** [comment]
Not in lodash. We offer a `_.create` function to create objects that inherit from a given `prototype` value.

**Comment by StreetStrider** [comment]
@lcarva, such thing overwrites constructor's name, you will receive smth like `[Function: wrapper]`.
I'm personally using this [some function of my own](https://github.com/StreetStrider/aux.js/blob/bb2277999f42f945e3bdd62c24fbd8555097ad00/inst.js).
```js
function Foo (a, b)
{
  var foo = inst(Foo) // (1)
  foo.a = a
  // …init
  return foo // (2)
  // (1) + (2) allow to use Foo both as a constructor and as a function
}
```
`Foo` becomes universal constructor and preserves its original name.

**Comment by dcastro** [comment]
@jdalton Would you be open to a PR to add this to lodash?

I've only just started using lodash, and this seems like a really useful feature. I often find myself want to pass a constructor as a regular function.

I whipped something up for my project, but I could put it into a PR if you think this is a good fit for lodash.

**Comment by jdalton** [comment]
@dcastro No. We usually wait for demand to pick up a bit more before opening a feature up to PRs.
