### ISSUE TITLE
Is there a method for automatically combining _.set and _.get?

### ISSUE THREAD

**Issue by MrHen** [lodash/lodash#1441]
Right now I can do this:

```
        var json = JSON.parse(ascii);
        var map = {
            'date': 'd',
            'link.target': 't',
            'link.platform': 'p',
            'link.location.document_type': 'l',
            'link.location.document_id': 'i',
            'link.origin_user_id': 'u'
        };

        var block = _.transform(map, function(result, value, key) {
            return _.set(result, key, _.get(json, value));
        });
```

But what I really want is this:

```
        var json = JSON.parse(ascii);
        var map = {
            'date': 'd',
            'link.target': 't',
            'link.platform': 'p',
            'link.location.document_type': 'l',
            'link.location.document_id': 'i',
            'link.origin_user_id': 'u'
        };

        var block = _.foo(json, map);
```

Is this currently possible? Or do I have the closest variant?

My eventual plan is to store `map` in config files and then just load it like a translation matrix and it would be handy to have a function that could handle that.

**Comment by jdalton** [comment]
There's no combo method. I think you've got it right with `_.get` and `_.set`.

**Comment by MrHen** [comment]
I created a quick variant to just do this: https://www.npmjs.com/package/lodash-setall. If you need/want me to change the name to not include "lodash" let me know. Code is here: https://github.com/MrHen/lodash-setall/blob/master/index.js.
