### ISSUE TITLE
Enhancement: Add fillObject request

### ISSUE THREAD

**Issue by rheh** [lodash/lodash#1442]
Enhancement to add fillObject to the API:

#### Example
```js
var array [
  {'name': 'fred', age: 40},
  {'name': 'bambam', age: 4}
];
 
_.fillObject(array, "child", function(value) {
 return (value.age <= 16);
});

// => [
  {'name': 'fred', age: 40, child: false},
  {'name': 'bambam', age: 4, child: true}
]
```

**Comment by jdalton** [comment]
I think for this case [_.mapValues](https://lodash.com/docs#mapValues) would do.

**Comment by rheh** [comment]
Sorry to be a pain; but, how would I do that with mapValues?  The case uses lodash to create a new property based on the predicate.

**Comment by jdalton** [comment]
Ah hmm I see `child` doesn't already exist.

```js
_.map(array, function(object) {
  object.child = object.age < 16;
});
```

**Comment by rheh** [comment]
I see; graceful.  Cheers.
