### ISSUE TITLE
Add interpose?

### ISSUE THREAD

**Issue by tgriesser** [lodash/lodash#1445]
I see it exists in `lodash-contrib` but didn't see any other tickets here asking for it. I find myself wanting it quite often, could open a ticket to add if it'd be considered.

**Comment by jdalton** [comment]
Hey @tgriesser! What's your use case?

**Comment by tgriesser** [comment]
Actually turned out it wasn't what I needed in this particular case, and I can't think of another off the top of my head. I'll reopen if I run into another situation where I'm looking for it.
