### ISSUE TITLE
question: lodash-y getOrDefault()

### ISSUE THREAD

**Issue by bdkent** [lodash/lodash#1446]
Does lodash natively support a generic `getOrDefault` method?  `_.get` is close.  Essentially, this:

    function getOrDefault(x, defaultVal) {
        return _.isEmpty(x) ? defaultVal : x;
    }

And if not, could it be added in a future release?

I typically find myself doing:

    var x = doBigCalculation();
    return _.isEmpty(x) ? defaultVal : x;

whereas with a `getOrDefault` function, I don't need to name the `x` variable:

    return getOrDefault(doBigCalculation(), defaultVal);

**Comment by jdalton** [comment]
I think _.get and _.result are the closest to what you want.
