### ISSUE TITLE
Fully applied function

### ISSUE THREAD

**Issue by jdart** [lodash/lodash#1447]
What are your thoughts on having a fully applied function helper.

I see this pattern where a callback needs to be called with a certain parameter which means I can't use it directly, and I have to wrap it with an anonymous function.

i.e.

```javascript
var bar = 'baz';
doPromise.then(function() { foo(bar); });
```

It could instead be written as:
```javascript
var bar = 'baz';
doPromise.then(_.fullyApplied(foo, bar));
```

Maybe this already exists and I missed it.

What do you think?

**Comment by jdart** [comment]
A simple implementation:

```javascript
foo = function() {
  var fn = arguments[0];
  var args = Array.prototype.slice.call(arguments);
  var that = this;
  return function() {
    return fn.apply(that, args.slice(1));
  };
};

function bar(val) {
  console.log(val);
}

foo(bar, '2')();
```

**Comment by jridgewell** [comment]
That's just `_.bind`. Or, `_.partial`, if you don't need `this`.

**Comment by StreetStrider** [comment]
@jridgewell, it's not, since @jdart's implementation seals arguments. For the sake of justice I need to say that this behavior is required *from time to time*. But most other cases are covered by `partial`, as you said.

**Comment by jdart** [comment]
It is a lot like partial except that in my case I don't want to execute the original function if all parameters are provided.

**Comment by jdalton** [comment]
I think you might be able to accomplish this with a combo of `_.ary`, `_.partial`, and / or `_.curry`. Try creating a prototype of the method you like as a mixin and we can kick it around. At the moment the use case seems a little narrow but as with other requests if there's demand we'll listen and try to work it out.

**Comment by jdart** [comment]
Are you thinking you'd use ary to prevent extra parameters, and curry to enforce a minimum number of parameters?

**Comment by jdalton** [comment]
Something like that.

**Comment by jdart** [comment]
Something like 

```javascript
function indirect() {
  var curriedFn = _.curry(arguments[0]);
  var args = Array.prototype.slice.call(arguments, 1);
  var that = this;
  return _.ary(function() {
    return curriedFn.apply(that, args);
  }, args.length - 1);
}

function annoyingFn(a, b) {
  console.log(a, b);
}

_.mixin({indirect: indirect});

_.indirect(annoyingFn, 4, 3)();
```

without currying:

```javascript
function indirect() {
  var fn = arguments[0];
  var args = Array.prototype.slice.call(arguments, 1);
  var that = this;
  return _.ary(function() {
    return fn.apply(that, args);
  }, args.length - 1);
}
```

without ary:

```javascript
function indirect() {
  var fn = arguments[0];
  var args = Array.prototype.slice.call(arguments, 1);
  var that = this;
  return function() {
    return fn.apply(that, args);
  };
}
```
