### ISSUE TITLE
_.isEmpty(1) === false ?

### ISSUE THREAD

**Issue by sgarbesi** [lodash/lodash#1448]
```javascript
console.log(_.isEmpty(1));
// Returns `false
```

```json
"lodash": "^2.4.1"
```

Is this intended? Doesn't make much sense to me.

**Comment by jdalton** [comment]
Please read the [_.isEmpty](https://lodash.com/docs#isEmpty).

**Comment by sgarbesi** [comment]
@jdalton Why would number not be included? I guess I'm trying to understand the logic behind that.

**Comment by jdalton** [comment]
Think of it as an this collection `isEmpty`? method. If you pass `1` to `_.map(1, _.identity)` it will return `[]` because `1` is considered empty.

**Comment by Cicko** [comment]
@jdalton I also don't think it makes sense. Most people would not think that the numeric argument will be considered as array.

**Comment by falsyvalues** [comment]
@Cicko Most people don't read documentation at all and raise issues on Github, thats sad truth.
