### ISSUE TITLE
Add `_.flip`.

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash#1449]
To `flip` the argument order of a function.

**Comment by megawac** [comment]
I think I prefer `rearg` over flip

**Comment by jdalton** [comment]
`rearg` is a great but `flip` can't be achieved by `rearg` entirely as `flip` reverses all args provided to a function.

**Comment by falsyvalues** [comment]
:+1:

**Comment by jdalton** [comment]
flip – it's more than just 2 arguments.
