### ISSUE TITLE
node 4.0

### ISSUE THREAD

**Issue by thirdreplicator** [lodash/lodash#1450]
Is lodash compatible with Node 4?

**Comment by jdalton** [comment]
lodash v3.10.1 unit tests pass on Node 4 :grinning:

It should be fine, I don't anticipate problems.

**Comment by aaronmccall** [comment]
@jdalton, I'm seeing a new behavior in lodash.merge@3.3.2 in Node 4. Previously, Buffers were preserved, but now they seem to be being converted into Arrays. To reproduce:

```javascript
var merge = require('lodash.merge');
var target = {}
merge(target, {
  buffer: new Buffer([0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80])
});

console.log(target);
```

Under Node 0.12
```javascript
// outputs:
{ buffer: <Buffer 01 02 04 08 10 20 40 80> }
```

Under Node 4
```javascript
// outputs:
{ buffer: [1, 2, 4, 8, 16, 32, 64, 128] }
```

**Comment by aaronmccall** [comment]
I'm opening a new issue for the above.
