### ISSUE TITLE
Node 4 Buffer merge problem

### ISSUE THREAD

**Issue by aaronmccall** [lodash/lodash#1453]
I'm seeing a new behavior in lodash.merge@3.3.2 in Node 4. Previously, Buffers were preserved, but now they seem to be being converted into Arrays. To reproduce:

```javascript
var merge = require('lodash.merge');
var target = {}
merge(target, {
  buffer: new Buffer([0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80])
});

console.log(target);
```

Under Node 0.12
```javascript
// outputs:
{ buffer: <Buffer 01 02 04 08 10 20 40 80> }
```

Under Node 4
```javascript
// outputs:
{ buffer: [1, 2, 4, 8, 16, 32, 64, 128] }
```

**Comment by jdalton** [comment]
This is due to `new Buffer` being a Uint8Array, typed array, in Node v4. We currently transform a typed array into an array when merging. The assumption is that it's merging into another array when the transformation is done which is not the case here so I've marked this as a bug.

**Comment by aaronmccall** [comment]
@jdalton, I've made the changes in the commit above in my local project to test, and it didn't actually solve my issue.

Here's an example more like my use-case:
```javascript
var merge = require('lodash.merge');

var target = {};
var buffer = new Buffer([0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80]);

merge(target, {
  buffer: buffer
});

merge(target, {
    test: [{
        buffer: buffer
    }]
});

console.log('target.test:', target.test);
```
Expected:
```javascript
[ { buffer: <Buffer 01 02 04 08 10 20 40 80> } ]
```
Actual:
```javascript
[ { buffer: [ 1, 2, 4, 8, 16, 32, 64, 128 ] } ]
```

It seems that, if the Buffer's parent object is itself a member of an Array, the Buffer is still converted to an Array.

**Comment by jdalton** [comment]
I get the expected result on master branch.

**Comment by aaronmccall** [comment]
Oh, I see what's going on. I just made the one-line change to lodash.merge@3.3.2, but master has a number of additional changes as well.

Any idea when what's in master will land in lodash.merge on npm?

**Comment by jdalton** [comment]
It'll be part of our 4.0 bump (not sure how that will shake out on the `lodash.merge` versioning yet.

**Comment by aaronmccall** [comment]
Is 4.0 just around the corner, or does it need a while in the oven yet?

**Comment by jdalton** [comment]
It's just around the corner. You may be able to use merge's `customizer` callback as a workaround until then.

**Comment by jdalton** [comment]
```js
_.merge(a, b, function(a, b) {
  if (b instanceof Buffer) {
    return b;
  }
});
```

**Comment by aaronmccall** [comment]
I'm doing this:
```javascript
if (!tgt || (typeof src === 'object' && tgt === src)) {
  return src;
}
```

Does that seem reasonable?

**Comment by jdalton** [comment]
If it works for you :)

**Comment by aaronmccall** [comment]
Seems to be. Thanks for your time! lodash has really made a lot of things I do much easier.

**Comment by oleksiyk** [comment]
Looks like this is still an issue with recent lodash v4.1.0:

```javascript
var target = {};

_.merge(target, {
    buffer: new Buffer([0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80])
});

console.log(target); // Node 4.2.4 => { buffer: [ 1, 2, 4, 8, 16, 32, 64, 128 ] }
```

**Comment by jdalton** [comment]
No worries :D
