### ISSUE TITLE
Doing an assign or merge assigns a string '[object Object]'

### ISSUE THREAD

**Issue by iq-dot** [lodash/lodash#1454]
Hi guys,

So I have an issue where doing an _.assign or even a _.merge stores a literal string value of '[object Object]' instead of the actual object itself in an array.

This seems to happen on a NodeJS server using Lodash 3.10. (also happened with 3.7) However I can't replicate it on JSBin.

Example:

```
// this is a mongoose object
var basket = {
            "shopping" : {
                "fruits" : {
                    "items" : []
                },
                "vegetables" : {
                    "items" : []
                },
                "others" : {
                    "items" : []
                }
            }
        };


var data = { 
  fruits: { items: [{ type: 'apple', colour: 'red' }] },
  vegetables: { items: [] },
  others: { items: [] } 
};

var result = _.assign(basket.shopping, data);

console.log(result.fruits.items);
// prints ["[object Object]"]
// instead of [ {  type: 'apple', colour: 'red' } ]
```

Any idea whats going on?

**Comment by rhys-vdw** [comment]
That's normal. First argument of `console.log` is coerced to string via `toString()`. You need to do this:

```js
console.log('some string', result.shopping.items);
console.dir(result.shopping.items);
```

**Comment by iq-dot** [comment]
No I think you misunderstood, it really is stored as string value of '[object Object]' I have checked the DB as well.

Anyway it turns out not to be related to Lodash but to mongoose.
