### ISSUE TITLE
Allow import { function name } from lodash

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#1457]
```js
import map from 'lodash/collection/map';
import zipObject from 'lodash/array/zipObject';
```

This is a bit annoying.

```js
import {
    map,
    zipObject
} from 'lodash';
```

would be a lot nicer.

It doesn't necessarily need to come straight from 'lodash' (although I do not see a problem with that), but it needs to come from the same file, e.g.

```js
import {
    map,
    zipObject
} from 'lodash/utils';
```

Remembering which functions belong to which category puts unnecessary mental strain.

**Comment by jdalton** [comment]
I'm adding this to the ES6 build at the moment. You might check out [babel-plugin-lodash](https://github.com/megawac/babel-plugin-lodash) too.

**Comment by gajus** [comment]
@jdalton woah, babel-plugin-lodash is amazeballs.

**Comment by dnutels** [comment]
I'd hate to re-open this, but apparently I can't wrap my head around how it is supposed to work with `lodash-es` (is that the one?) as it is currently constructed.

Ideally, I would love to do that:

```
import {zip} from 'lodash';
```

and (in my case, using webpack) not have anything __other__ than `zip` and its dependencies to be packaged.


It actually works, aside from some odd unrelated webpack/karma-webpack hiccup.

There are however a couple of caveats:

1. looking at the _lodash.js_ in _lodash-es_ I can tell that it does quite a bit of augmentation (lazy wrapping) - which I'd love to get using the above ES6 form

2. using the babel plugin (to somehow overcome 1.) you mentioned is a no-go, since it, by your own admission, doesn't support chaining API, negating a lot of lodash appeal

Am I missing something? Should I be using a different build? How would you go about it?

P.S.

I don't think having me build a specific lodash package is the correct way to go - ES6 and its module system, along with tools like JSPM or webpack, should be taking care of that.

**Comment by jdalton** [comment]
@dnutels The modular form of lodash doesn't support chaining out of the box. It's on my list to augment the `lodash/chain` category package to include the wiring that's normally in the monolithic build to enable chaining.

**Comment by dnutels** [comment]
So, what would be your suggestion to use in the meanwhile?

Am I using `lodash-es` properly, or missing out on lazy wrapping you have in the root?

**Comment by jdalton** [comment]
In the meantime if you want chaining with modules you'd have to recreate the wiring in the root.

**Comment by milesj** [comment]
Does this approach:

```
import {
    map,
    zipObject
} from 'lodash';
```

Only pull in the source code for "map" and "zipObject", because I've been under the impression that ES6 modules will pull in the entire source of the "lodash" path, which would be all exported functions.

**Comment by dnutels** [comment]
Nope. Would get in everything. Hence `'lodash/collection/map'` in the original post.

**Comment by milesj** [comment]
That's what I thought. It only seems useful if you're using the entire lodash. Thanks for the clarification.

**Comment by dnutels** [comment]
@jdalton 

I was thinking, the main issue, as far as I could tell, is with root augmenting the functions, thus preventing them from separate use (to the same extent).

Perhaps an inverse dependency would solve this? Where each separate module (zip, drop etc.) imports an augmentation module, uses it on itself and exports augmented version.

This way each separate function can be used, while still being augmented.

Hope that makes sense.

**Comment by jdalton** [comment]
@milesj 
> Does this approach:
>
```
import {
    map,
    zipObject
} from 'lodash';
```
>
Only pull in the source code for "map" and "zipObject", 

In v4 of [lodash-es](https://www.npmjs.com/package/lodash-es) it will.

@dnutels

> Perhaps an inverse dependency would solve this?

For chaining I'll just make it so that
```
var chain = require('lodash/chain');
chain(array); // returns a chaining wrapper
chain.mixin({ /* add methods */);
```
works.

**Comment by dnutels** [comment]
@jdalton 

Excellent, can't wait.

**Comment by lagden** [comment]
@jdalton or @anyone!!

Can you explain why you write this way?

``` javascript
// https://github.com/lodash/lodash/blob/es/date.js

import now from './date/now';
export { default as now } from './date/now';
export default { now };
```

and not directly:

``` javascript
import now from './date/now';
export default { now };
```
or

``` javascript
export { default as now } from './date/now';
```

If you provide any link with an explanation will be good enough!
Regards

**Comment by jdalton** [comment]
Exporting both supports importing as:
```js
import default from 'lodash-es'
```
and
```js
import {map, cloneDeep} from 'lodash-es'
```
and
```js
import * as _ from 'lodash-es'
```

**Comment by lagden** [comment]
@jdalton :metal: 

Tks!!

**Comment by LukasBombach** [comment]
Um, noob-question: if I import particular methods of lodash like this and pack it with babel / webpack, will it pack only these methods to my file or include all of / big parts of lodash too? I know this may be a webpack-question but I guess it strongly depends on the internal structure of lodash.

**Comment by gajus** [comment]
> if I import particular methods of lodash like this and pack it with babel / webpack, will it pack only these methods to my file or include all of / big parts of lodash too?

If:

* you are using import syntax
* you are using webpack/ Browserify (or any other bundler)

then yes – only the necessary files will be included.

**Comment by LukasBombach** [comment]
Oh sorry yes, I *just* read it. Thank you.

**Comment by jdalton** [comment]
Actually rollup and webpack 2 beta don't support tree shaking with lodash yet. So you're best bet is to use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) (without the commonjs transform if you es6-toes6).

**Comment by LukasBombach** [comment]
Oh cool thanks. This is a pretty broad question and probably cannot be answered generally, but if I import a particular lodash function that itself requires one or more functions internally, logically all of them will be imported. Can you give a general idea of how much of this can be expected or is lodash not really that tied together?

**Comment by jdalton** [comment]
@LukasBombach See the [lodash-cli/lib/mapping.js](https://github.com/lodash/lodash-cli/blob/aa473983607a39351ba6c5c7f2375aadfd39f880/lib/mapping.js#L379-L917).

**Comment by LukasBombach** [comment]
Awesome, thanks!

**Comment by hyperbrave** [comment]
is the es6 build up to date with master?

**Comment by corysimmons** [comment]
Did this ever get fixed? If so, could someone add better docs to explain usage?
