### ISSUE TITLE
How to get an object with all keys sorted?

### ISSUE THREAD

**Issue by stanleyxu2005** [lodash/lodash#1459]
Sometimes, I create an object (dictionary) with some index-able value as key. I want to make sure all keys are sorted alphabetically. Is there a built-in function of lodash to do that? Currently I have an own function to do that.
```
function objectWithKeySorted(object) {
  var result = {};
  _.forEach(Object.keys(object).sort(), function(key) {
    result[key] = object[key];
  });
  return result;
}
```
Example:
```
var a = {2015: '2015', 2011: '2011', 2013: '2013'};
console.log(a); // {2015: '2015', 2011: '2011', 2013: '2013'}
var b = objectWithKeySorted(a);
console.log(b); // {2011: '2011', 2013: '2013', 2015: '2015'}
```

**Comment by jdalton** [comment]
Your example may not be the best as modern engines will auto iterate index keys in ascending order. A map (dictionary) really shouldn't be concerned with order. What are you using it for?

**Comment by stanleyxu2005** [comment]
I have an array of elements. Every element has a property `timestamp`. One demand is to return all these elements without any duplicates and they should be sorted by timestamp. As object's keys will never duplicate, so I tried to return an `object` (key=timestamp) instead of an array. I hope `object` can sort all its keys as nature. But it does not work in that way.

**Comment by jdalton** [comment]
You should check out ES6 Map (shimmable) combo'ed with Babel (transpiler) if needed.
It's keys are uniq (objects can even be keys):
```js
_.sortBy([...map], 0);
```

**Comment by stanleyxu2005** [comment]
I know this method, but the result is an array. But I want object....

**Comment by jdalton** [comment]
What's your keys look like?

**Comment by stanleyxu2005** [comment]
Please check the code in the initial question. 

You inspired me. Actually I should do like this.
```
var a = {2015: '2015', 2011: '2011', 2013: '2013'};
_.forEach(Object.keys(a).sort(), function(key) {
  console.log(a[key]);
});
```

**Comment by jdalton** [comment]
As I mentioned before if that's really your keys there is no sorted needed because that's how modern engines [iterate by](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys).
```js
var a = {2015: '2015', 2011: '2011', 2013: '2013'};
a[2010] = '2010';
Object.keys(a).forEach(function(key) {
  console.log(a[key]);
});
// logs 2010, 2011, 2013, 2015
```

**Comment by stanleyxu2005** [comment]
Cool. Thanks a lot.

**Comment by zorji** [comment]
`_(obj).map((v, k) => [k, v]).sortBy(0).fromPairs().value()`

**Comment by raszi** [comment]
```javascript
_(obj).toPairs().sortBy(0).fromPairs().value()
```

**Comment by sfinktah** [comment]
@stanleyxu2005  Hmmm... seriously?   I just checked the latest Firefox, Chrome and Opera (Win 10) and all return:

    o = {"3a": 1, "3b": 2, "4": 3, "4a": 4, "5": 5}

    Object {4: 3, 5: 5, 3a: 1, 3b: 2, 4a: 4}

The only stand-out was an old copy of Safari 6.0.5 on my Mac (Mountain Lion/10.8.5), which loyally left them in order.

**Ahh crap, I misread your question, you're using an array.**

Still, on the topic of indeterminate Object ordering, it makes me wonder why

    _.values(o, ['3a', '4'])

Isn't **a thing**...

    function values(obj, keys) {
        var i, key, len, values = [];
        keys = _.flatten(arguments).slice(1);
        for (i = 0, len = keys.length; i < len; i++) {
            values.push(obj[keys[i]]);
        }
        return values;
    }

**Comment by sfinktah** [comment]
@stanleyxu2005  Hmmm... seriously?   I just checked the latest Firefox, Chrome and Opera (Win 10) and all return:

    o = {"3a": 1, "3b": 2, "4": 3, "4a": 4, "5": 5}

    Object {4: 3, 5: 5, 3a: 1, 3b: 2, 4a: 4}

The only stand-out was an old copy of Safari 6.0.5 on my Mac (Mountain Lion/10.8.5), which loyally left them in order.

**Ahh crap, I misread your question, you're using an array.**

Still, on the topic of indeterminate Object ordering, it makes me wonder why

    _.values(o, ['3a', '4'])

Isn't **a thing**...

    function values(obj, keys) {
        var i, key, len, values = [];
        keys = _.flatten(arguments).slice(1);
        for (i = 0, len = keys.length; i < len; i++) {
            values.push(obj[keys[i]]);
        }
        return values;
    }

**Comment by bitterloa** [comment]
I just used the lodash `_.sortBy` function and it seems like a simple solution:

```
var stuff = [{sortKey: 3, val: "three"}, {sortKey: 2, val: "two"}, {sortKey: 1, val: "one"}]; 
_.sortBy(stuff, 'sortKey');
console.log(stuff);  // [{sortKey: 1, val: "one"}, {sortKey: 2, val: "two"}, {sortKey: 3, val: "three"}]
```

However this sorts on the object key's _values_ as opposed to the name of the key itself, so unsure if it's exactly what the original poster wanted, but may be helpful to others.

**Comment by kevando** [comment]
I just used a map function to add the key before hand.

``` javascript
const collectionWithKey = _.map(collection, (item, key) => ({...item, _key: key}) )
const sortedCollectionWithKey =  _.sortBy(sessionsWithKey, ['createdAt']) // 
```

**Comment by pratyushcrd** [comment]
A simple function without lodash can do this: 

`const sortObjectKeys = obj => Object.keys(obj)
  // sorting keys
  .sort()
  // putting it back to object
  .reduce((acc, key) => {
    acc[key] = obj[key]
    return acc
  }, {})`
