### ISSUE TITLE
Please consider adding an 'extract' method for nested objects

### ISSUE THREAD

**Issue by niyazpk** [lodash/lodash#146]
`_.extract(object, string)` 

Uses the string as a path finder inside the object to retrieve the specified item
Returns `undefined` if anything went wrong in finding the item.

I have come across this problem multiple times to warrant writing my own method to handle this. Feels like more people could use this if it is available in lodash.

My current implementation looks similar to the first answer here: http://stackoverflow.com/questions/6491463/accessing-nested-javascript-objects-with-string-key

Example:

``` js
var obj = {
  user: {
    order: {
      address : {
        city: 'Bangalore'
      }
    }
  }
};

 _.extract(obj, 'user.order.address.city');
// => 'Bangalore'

_.extract(obj, 'user.home.address.city');
// => undefined
```

**Comment by gitnik** [comment]
:+1: for this

**Comment by cmfatih** [comment]
@jdalton : Any news about this?

**Comment by jdalton** [comment]
@cmfatih Deep property support is in v3.7.0.

**Comment by cmfatih** [comment]
:boom: 

thanks :)

**Comment by cmfatih** [comment]
@jdalton : Any chance for deep picking? ( for example: `_.pick(object, 'foo.bar')` )

**Comment by jdalton** [comment]
The reason I didn't add it is because it's behavior is unclear. Should it map to a property `bar` or try to construct the path up to `bar`. It seems a little messy.

**Comment by cmfatih** [comment]
I see...

What would you do if you need to transform (performance matters);

```javascript
{
  a: '1',
  b: '2',
  c: '3',
  foo: {
    bar: 'qux'
  }
}
```
to
```javascript
{
  a: '1',
  foo: {
    bar: 'qux'
  }
}
```

Basically I want to omit some fields but I have a pick list instead. Should I go ahead with a for loop and manually filter it?

**Comment by megawac** [comment]
Why are `_.pick`, `_.omit` not suitable?

**Comment by cmfatih** [comment]
@megawac : I'm not sure wdym but in my case; I have an array like `['a', 'foo.bar']` and can't do `_.pick(object, ['a', 'foo.bar'])` atm.

**Comment by cmfatih** [comment]
btw probably I should not call it `pick` after at all. Because it picks value with structure...

**Comment by cmfatih** [comment]
@megawac : I've updated the example above (see foo property) sorry for missing example

**Comment by cmfatih** [comment]
Update: If anybody needs it then https://github.com/raisch/lodash-sift

thanks

**Comment by JamesMcGuigan** [comment]
As of lodash 3.7, _.get() and _.set() work with nested selectors

_.get({a:{b:{c:42}}}, 'a.b.c') // = 42
_.set({a:{b:{c:42}}}, 'a.b.c', 69) // = {a:{b:{c:69}}}

**Comment by angadsalaria** [comment]
Can we add an accompanying feature for nested deletes as well?
var obj = { a : {b : 'some value', c : 'some other value'}};
_.delete( obj, 'a.b') 
//=> obj = { a : {c : 'some other value'}}

**Comment by jdalton** [comment]
> Can we add an accompanying feature for nested deletes as well?

This is in our edge master branch as `_.unset` and will be available in lodash v4.

**Comment by Whoaa512** [comment]
Can also be implemented with a simple reduce

```javascript
const paths = ['a', 'foo.bar']
const target = {
    a: 11,
    foo: {
        bar: 'baz'
    }
}

function reducer(target) {
    return (obj, path) => {
        const key = _.last(_.toPath(path))
        if (_.has(target, path)) {
            obj[key] = _.get(target, path)
        }
        return obj
    }
}

_.reduce(paths, reducer(target), {})
```

**Comment by amgando** [comment]
replying to [a comment above](https://github.com/lodash/lodash/issues/146#issuecomment-94853803), it looks like this is working with `pick` now ... just in case anyone else runs across this thread and wonders the same thing I did.

```js
_.pick({a:1, b:2, c:{d:3, e:4}}, ['a', 'c.d'])  // => {a:1, c: {d:3}}
_.pick({a:1, b:2, c:{d:3, e:4, f:{g:5, h:6}}}, ['a', 'c.d','c.f.g']) // => {a:1,c:{d:3,f:{g:5}}}
```

**Comment by ms88privat** [comment]
@amgando doesn't work for me now. Did it change again?

**Comment by fopnet** [comment]
Are there a way to use _.extract method in _conforms to access nested properties ?
