### ISSUE TITLE
Add string splice function

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#1462]
As discussed here, http://stackoverflow.com/q/20817618/368691.

Example implementation:

```js
/**
 * @param {String} str
 * @param {Number} start
 * @param {Number} deleteCount
 * @param {String} add
 */
function spliceString (str, start, deleteCount, add) {
    return str.slice(0, start) + (add || "") + str.slice(start + deleteCount);
}
```

**Comment by gajus** [comment]
A repository with test cases.

https://github.com/sindresorhus/splice-string

Worth asking @sindresorhus to make a PR.

**Comment by jdalton** [comment]
Thanks @gajus! I'll keep an eye on demand for this.
