### ISSUE TITLE
String functions do not work as expected when subject includes astral symbols or ANSI escape codes

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#1463]
`padRight` does not pad the string that has ANSI escape codes, e.g.

```js
_.padRight("\u001b[31mfoo\u001b[39m\u001b[34mbar\u001b[39mbaz", 10, 'X');
```

The same issue applies to all string functions.

The reason this is happening is primarily because the `length` property of the value is affected by ANSI escape codes. `padRight` should only be concerned with visible characters.

Consider using [`string-length`](https://github.com/sindresorhus/string-length) by @sindresorhus.

**Comment by jdalton** [comment]
Pinging @mathiasbynens as he's our resident unicode expert.

**Comment by mathiasbynens** [comment]
> Consider using `string-length` by @sindresorhus.

That still wouldn’t solve the problem you described:

> `padRight` should only be concerned with visible characters.

string-length counts astral symbols correctly and ignores ANSI escape codes, but there are many more invisible symbols in the Unicode standard.

Also, what should happen when Hangul made of conjoining Jamo occurs in the string? What about combining marks? Should `padRight` (and other lodash string functions) account for all these cases?

Things like [counting the number of symbols in a string](https://mathiasbynens.be/notes/javascript-unicode#counting-symbols) are ambigious tasks; the approach to take really depends on what you’re trying to do. A generic utility library like lodash can never perfectly satisfy all use cases without possibly breaking others.

My point is: a line has to be drawn somewhere. The question is where. Personally I’d vote for astral symbol support by default (as `'💩'.length == 2` is arguably a JavaScript language quirk), but ignoring ANSI escape codes by default is a bridge too far IMHO. @jdalton, what do you think?

For now, I’d suggest using `.length` and string-length in your own code to dynamically calculate the `length` parameter to pass to `_.padRight`.

**Comment by gajus** [comment]
> For now, I’d suggest using .length and string-length in your own code to dynamically calculate the length parameter to pass to _.padRight.

That won't work. Though, I have managed to quickly write my own `padLeft`, `padRight` and `pad` using `_.repeat` and `string-length`.

**Comment by mathiasbynens** [comment]
> That won't work because you cannot modify `.length` property value.

Wait, what? I meant something like this (simplified):

```js
var string = '\x1B[31mfoo\x1B[39m\x1B[34mbar\x1B[39mbaz'; // your example string
var desiredVisualWidth = 10; // note: “visual width” as defined based on your specific use case
var actualVisualWidth = lengthWhenAccountingForAstralSymbolsAndWithoutAnsi(string); // note: for your specific use case
// → 9
var difference = desiredVisualWidth - actualVisualWidth;
// → 1
var lengthParameter = string.length + difference; // assuming you pad using a BMP symbol
→ 29 + 1 == 30
_.padRight(string, lengthParameter, 'X');
```

**Comment by gajus** [comment]
That makes sense.
