### ISSUE TITLE
trim, trimLeft, trimRight allow regex

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#1464]
It would be useful if trim functions allowed regex in addition to list of characters, e.g.

```js
_.trimRight('foo<a><b><c>', /\<[a-z]\>$/);
> foo
```

**Comment by jdalton** [comment]
I think at that point it would be something `String#replace` could tackle.

**Comment by gajus** [comment]
It it trivial to write a function to do that, e.g.

```js
let trimRight;

/**
 * Produces a list of the escape codes contained in the input string.
 *
 * @param {String} subject
 * @param {RegExp} rule
 * @return {String}
 */
trimRight = (subject, rule) => {
    let result;

    result = subject.replace(rule, ``);

    if (result !== subject) {
        return trimRight(result, rule);
    }

    return result;
};

export default trimRight;
```

But isn't the idea of lodash is not to have to write these functions and have them in the utility belt?

**Comment by jdalton** [comment]
```js
'foo<a><b><c>'.replace(/\<[a-z]\>$/, '');
```

`String#replace` is great for regexes.

**Comment by gajus** [comment]
That alone will not work.

```js
'foo<a><b><c>'.replace(/\<[a-z]\>$/, '');
```

will produce:

```
foo<a><b>
```

**Comment by jdalton** [comment]
Ah ya, recursion is something we won't likely tackle and not something great for regexes in JS at least.

**Comment by gajus** [comment]
Well, no reason for using recursion... just turn that into a `while` cycle.

**Comment by jdalton** [comment]
Looks like you've got all the answers, feel free to create a mixin.
