### ISSUE TITLE
Lodash issue, works fine locally fails @ heroku

### ISSUE THREAD

**Issue by pulkitnandan** [lodash/lodash#1465]
Using sailsjs 0.11, node 4.0, and curlrequest latest. Does it have anything to do with copying from windows to linux or linux to windows git showed some warning regarding modes or mods. Does this looks familiar works awesome locally while bloating with error on heroku.

![image](https://cloud.githubusercontent.com/assets/5687927/9839846/61140fec-5aa2-11e5-930c-f80997bbfd1c.png)

**Comment by jdalton** [comment]
Hi @pulkitnandan!

I'm not aware of any issues on the lodash side of things related to this. You might ping  heroku support on it.

**Comment by pulkitnandan** [comment]
This is with npm and lodash only even my local thing went corrupted when I deleted whole of the directory and started project from scratch.

npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/nodejs',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose' ]
npm info using npm@2.12.0
npm info using node@v4.0.0
npm verb readDependencies loading dependencies from /home/rohit/backend/package.json
npm verb install where, deps [ '/home/rohit/backend',
npm verb install   [ 'curlrequest',
npm verb install     'ejs',
npm verb install     'grunt',
npm verb install     'grunt-contrib-clean',
npm verb install     'grunt-contrib-coffee',
npm verb install     'grunt-contrib-concat',
npm verb install     'grunt-contrib-copy',
npm verb install     'grunt-contrib-cssmin',
npm verb install     'grunt-contrib-jst',
npm verb install     'grunt-contrib-less',
npm verb install     'grunt-contrib-uglify',
npm verb install     'grunt-contrib-watch',
npm verb install     'grunt-sails-linker',
npm verb install     'grunt-sync',
npm verb install     'include-all',
npm verb install     'rc',
npm verb install     'sails',
npm verb install     'sails-disk',
npm verb install     'sails-postgresql' ] ]
npm verb install where, peers [ '/home/rohit/backend', [] ]
npm verb installManyTop reading for lifecycle /home/rohit/backend/package.json
npm info preinstall kickpac@0.0.0
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/curlrequest/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/ejs/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt-contrib-clean/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt-contrib-coffee/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt-contrib-concat/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt-contrib-copy/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt-contrib-cssmin/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt-contrib-jst/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt-contrib-less/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt-contrib-uglify/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt-contrib-watch/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt-sails-linker/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/grunt-sync/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/include-all/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/rc/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/sails/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/sails-disk/package.json
npm verb installManyTop reading scoped package data from /home/rohit/backend/node_modules/sails-postgresql/package.json
npm info package.json curlrequest@0.5.3 No license field.
npm info package.json ejs@0.8.8 No license field.
npm info package.json grunt-contrib-clean@0.5.0 No license field.
npm info package.json grunt-contrib-coffee@0.10.1 No license field.
npm info package.json grunt@0.4.2 No license field.
npm info package.json grunt-contrib-concat@0.3.0 No license field.
npm info package.json grunt-contrib-copy@0.5.0 No license field.
npm info package.json grunt-contrib-cssmin@0.9.0 No license field.
npm info package.json grunt-contrib-jst@0.6.0 No license field.
npm info package.json grunt-contrib-less@0.11.1 No license field.
npm info package.json grunt-contrib-uglify@0.4.1 No license field.
npm info package.json grunt-contrib-watch@0.5.3 No license field.
npm info package.json grunt-sync@0.0.8 No license field.
npm info package.json rc@0.5.5 No license field.
npm info package.json sails@0.11.0 No license field.
npm verb readDependencies loading dependencies from /home/rohit/backend/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/curlrequest/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/ejs/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt-contrib-clean/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt-contrib-coffee/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt-contrib-concat/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt-contrib-copy/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt-contrib-cssmin/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt-contrib-jst/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt-contrib-less/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt-contrib-uglify/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt-contrib-watch/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt-sails-linker/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/grunt-sync/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/include-all/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/rc/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/sails/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/sails-disk/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/sails-postgresql/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/.bin/rc/package.json
npm verb targetResolver reading package data from /home/rohit/backend/node_modules/.bin/sails/package.json
npm verb already installed skipping grunt@0.4.2 /home/rohit/backend
npm verb already installed skipping grunt-contrib-clean@~0.5.0 /home/rohit/backend
npm verb already installed skipping grunt-contrib-coffee@~0.10.1 /home/rohit/backend
npm verb already installed skipping grunt-contrib-concat@~0.3.0 /home/rohit/backend
npm verb already installed skipping grunt-contrib-copy@~0.5.0 /home/rohit/backend
npm verb already installed skipping grunt-contrib-cssmin@~0.9.0 /home/rohit/backend
npm verb already installed skipping grunt-contrib-jst@~0.6.0 /home/rohit/backend
npm verb already installed skipping grunt-contrib-less@0.11.1 /home/rohit/backend
npm verb already installed skipping grunt-contrib-uglify@~0.4.0 /home/rohit/backend
npm verb already installed skipping grunt-contrib-watch@~0.5.3 /home/rohit/backend
npm verb already installed skipping grunt-sails-linker@~0.9.5 /home/rohit/backend
npm verb already installed skipping grunt-sync@~0.0.4 /home/rohit/backend
npm verb already installed skipping include-all@~0.1.3 /home/rohit/backend
npm verb already installed skipping rc@~0.5.0 /home/rohit/backend
npm verb already installed skipping sails@~0.11.0 /home/rohit/backend
npm verb already installed skipping sails-disk@~0.10.0 /home/rohit/backend
npm verb already installed skipping sails-postgresql@^0.10.16 /home/rohit/backend
npm verb already installed skipping curlrequest@^0.5.3 /home/rohit/backend
npm verb already installed skipping ejs@~0.8.4 /home/rohit/backend
npm info build /home/rohit/backend
npm info linkStuff kickpac@0.0.0
npm verb linkBins kickpac@0.0.0
npm verb linkMans kickpac@0.0.0
npm verb rebuildBundles kickpac@0.0.0
npm verb rebuildBundles [ '.bin',
npm verb rebuildBundles   'curlrequest',
npm verb rebuildBundles   'ejs',
npm verb rebuildBundles   'grunt',
npm verb rebuildBundles   'grunt-contrib-clean',
npm verb rebuildBundles   'grunt-contrib-coffee',
npm verb rebuildBundles   'grunt-contrib-concat',
npm verb rebuildBundles   'grunt-contrib-copy',
npm verb rebuildBundles   'grunt-contrib-cssmin',
npm verb rebuildBundles   'grunt-contrib-jst',
npm verb rebuildBundles   'grunt-contrib-less',
npm verb rebuildBundles   'grunt-contrib-uglify',
npm verb rebuildBundles   'grunt-contrib-watch',
npm verb rebuildBundles   'grunt-sails-linker',
npm verb rebuildBundles   'grunt-sync',
npm verb rebuildBundles   'include-all',
npm verb rebuildBundles   'rc',
npm verb rebuildBundles   'sails',
npm verb rebuildBundles   'sails-disk',
npm verb rebuildBundles   'sails-postgresql' ]
npm info install kickpac@0.0.0
npm info postinstall kickpac@0.0.0
npm info prepublish kickpac@0.0.0
npm verb validateInstall loading /home/rohit/backend/package.json for validation
npm verb exit [ 0, true ]
npm info ok 

It gives following error 



info: Starting app...

module.js:338
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/rohit/backend/api/blueprints/find.js:5:9)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/rohit/backend/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/home/rohit/backend/node_modules/include-all/index.js:44:9)
    at buildDictionary (/home/rohit/backend/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.optional (/home/rohit/backend/node_modules/sails/node_modules/sails-build-dictionary/index.js:160:9)
rohit@ubuntu:~/backend$ npm install --verbose 2> 1

**Comment by pulkitnandan** [comment]
Sync up with heroku and look if the have blacklisted lodash as heroku give's this exclusive error lodash is not found.

I certainly do not know anything about this lodash so I never touced it. The only thing I was doing was to add curlrequest package and also installed then uninstalled two node based curl packages which never worked with --save option(yes I use --save while nm install and npm uninstall), It was to edit js with no autocomplete in linux so I copied to windows the relavent js files and copied back after editing. It's fixed locally but doing npm install lodash but it's not fixed with heroku and I repeat I have done nothing fancy anywhere editing only the files in api only.

**Comment by jdalton** [comment]
Sorry you're having problems. This is not heroku support.

**Comment by d10** [comment]
I'm not too sure, but is lodash missing from your package.json? It doesn't seem to be mentioned in the npm log you posted.
