### ISSUE TITLE
memoize a function which returns an object

### ISSUE THREAD

**Issue by jvitela** [lodash/lodash#1466]
Using memoize on a function which returns a non primitive can lead to accidentally modifying the cache, here's a naive example:
```
function calcTotal( net, taxes, curr) {
   return {
      amount: net + taxes,
      curr: curr
   };
}

var calcTotal = _.memoize(calcTotal);
var a = calcTotal(100, 50, 'eur');
var b = calcTotal(100, 50, 'eur');
a.amount += 10;
console.log(b.amount); // 160
```

I am not sure if this is something memoize should take care of, but I think at least this should be addressed in the docs.

**Comment by jridgewell** [comment]
You need to set a [`resolver`](https://lodash.com/docs#memoize) function to avoid using `[object Object]` as the cache key.

**Comment by jdalton** [comment]
Hi @jvitela!

The docs do cover it:
> By default, the first argument provided to the memoized function is coerced to a string and used as the cache key.

As @jridgewell pointed out you could use `resolver` to come up with your own key based on the object or you could use ES6 Map (similar to the doc example)
```js
_.memoize.Cache = Map;
```

**Comment by jvitela** [comment]
Thanks for the fast answer,

The problem in the example I pasted is not in the cache key generated. The problem is that the function I want to memoize returns an object, in this cases every time the cache is used, it returns the same object reference and this allow to modify the cache contents indirectly.

**Comment by StreetStrider** [comment]
@jdalton, @jridgewell what he saying about is not the input (key) but the output (return value). If the return value is not primitive it will be returned by ref, so cache can be accidentally modified on the receiving side. I'm not thinking this is an problem, but on the other hand @jvitela is right, docs does not covers it (as well as for `_.constant`, it has the same nature).

**Comment by jdalton** [comment]
`const` has the same nature. That's how objects work. There is `Object.freeze` in ES5+ enviros.
