### ISSUE TITLE
allow .filter to return the unfiltered 

### ISSUE THREAD

**Issue by goldensunliu** [lodash/lodash#1468]
```
_.filter([4, 5, 6], function(n) {
  return n % 2 == 0;
});
// → [4, 6]
```

it would be awesome we can also get the unfiltered as well so I don't have to the call the negative of the predicate function to get the filter result again:
```
_.filter([4, 5, 6], function(n) {
  return n % 2 == 0;
});
// → { filtered: [4, 6], unfiltered: [5] }
```
just an idea

**Comment by jdalton** [comment]
Hi @goldensunliu! You can use `_.partition` it will return an array of two arrays, one contianing all the values the predicate returned truthy for and one containing all the values the predicate returned falsey for.
