### ISSUE TITLE
Possibly support chaining returning a function

### ISSUE THREAD

**Issue by tsclaus** [lodash/lodash#1469]
Currently, to force a chain to evaluation (as opposed to implicitly ending it with certain chain functions) you have to call .value(). Is there any merit to making the chain object a function, with the same fields and behavior as current, to allow you to end the chain by directly calling the return? From the given example for _(value) :

    _.isArray(squares.value());

to

    _.isArray(squares());

It would take slightly more memory, but the speed would be unchanged (except for ending the chain which would actually be faster as no dereferencing of the method).

**Comment by jdalton** [comment]
Hi @tsclaus! That's an interesting idea. However, we're pretty tied to prototypal inheritance. I don't think theirs an easy way to accomplish this without putting more overhead into each method.

`value` does have a few aliases (run, toJSON, valueOf).
