### ISSUE TITLE
Add flush to debounce/throttle cancel.

### ISSUE THREAD

**Issue by Parakleta** [lodash/lodash#1470]
I would like to request the addition of a flush mechanism on the `cancel` function for debounced/throttled functions.  i.e. if the first argument is true-ish and there is a pending call fire the pending call immediately and then cancel all timers.

I have a situation where I am cancelling pending debouncers in a destructor but I still want the last pending state update to synchronise, which I am having to do manually.  It would be nice to be able to flush that last state change automatically when I cancel the debouncer.

**Comment by jdalton** [comment]
Hi @Parakleta! The point of cancel is to cancel so I think inducing a final call is a bit awkward. That said, I'll keep an eye on this request to see if there's demand for something like it.

**Comment by Parakleta** [comment]
I had just thought it would be the simplest place to put it, but you could add an extra function call `flush` to give the desired behaviour if you don't like overriding `cancel` (I had thought of it as cancel-with-flush).  I don't think this should override the current default behaviour which is correct.

Without this there is no way to retrieve the pending event in a debouncer.

**Comment by jdalton** [comment]
> Without this there is no way to retrieve the pending event in a debouncer.

Yap, because it was cancelled with the `cancel` call.

**Comment by Parakleta** [comment]
I think my referencing `cancel` may have confused the core issue.  Consider maybe instead thinking of it like the `MutationObserver.takeRecords` for example.  The situation may exist where I have a debounce timeout generally set but then something arises where I need to finalise (not cancel) any pending events immediately.

This could be useful for example if I have multiple debouncers but when one of them expires I may want to opportunistically pull/flush others that are pending so I can aggregate to a single bulk update.

I'm not trying to argue for the change here, I'm happy to wait and see if there is further interest, I just want to make sure that I have clearly expressed the idea and that we're on the same page.

**Comment by jdalton** [comment]
Cool. Any similar methods to base a name off of?

**Comment by LeJared** [comment]
I really like this idea. As of now I always have to ensure that final call on my own whenever I want to stop a debouncer.

**Comment by Parakleta** [comment]
For a method name `flush` is the convention for buffered IO which is the closest analogy I can think of to a debouncer.

**Comment by StreetStrider** [comment]
Maybe `.finish()`.

**Comment by Parakleta** [comment]
In a similar vein to `finish` would be `expire`, since we are really just making the timeouts expire now.

**Comment by jdalton** [comment]
I added `flush` in https://github.com/lodash/lodash/commit/57da7a000760c06027e4d09c221871bd81ddbab1.
