### ISSUE TITLE
"where" for object

### ISSUE THREAD

**Issue by henhal** [lodash/lodash#1471]
I have found that I quite frequently need to filter a single object against a set of properties. Basically same as `_.where` for lists, but for a single object.

Example:

    return (obj && obj.name == 'Bob' && obj.age == '42') ? obj : undefined;

Using `_.isMatch` I can make it slightly more compact:

    return (_.isMatch(obj, {name: 'Bob', age: 42}) ? obj : undefined;

Sure, there's not a huge amount of characters to be saved, but it would be more compact and elegant if there was a dedicated function with the same semantics as `_.where`, basically performing the same test as `_.isMatch` but returning the object instead of true in case of a match:

    return _.match(obj, {name: 'Bob', age:42});

Is there such a function already that I'm missing? If not, would it be considerable to accept contribution of one?

Typical usecase: `where` is useful e.g. when retrieving a collection of objects from a database and where you for some reason need to perform additional filtering in code. A `match` function would serve the same purpose for cases where a single object is retrieved, in a very clean and compact way.

**Comment by jdalton** [comment]
Hi @henhal!

Because this is so close to `_.isMatch` I think this would fit in as a mixin.
I'm most likely going to add `_.ifElse` in a bit which would allow composition as:
```js
var myMatch = _.ifElse(_.isMatch, _.identity, _.constant(undefined));
```

**Comment by henhal** [comment]
Ok cool. Thanks.
