### ISSUE TITLE
Map Parses Long Arrays Incorrectly

### ISSUE THREAD

**Issue by devmanhinton** [lodash/lodash#1472]
Is this a repeat or known issue?
It is because JS stores large Arrays as multi-dimensional arrays

Great Library!
FYI: `_.each` instead of `.map` behaves correctly (which is the solution I used)
```js
// In Javascript console on lodash.com (chrome)
var input = _.fill(Array(10000), 0)
var reducer = function(g1,g2) {return g1 + g2}
var chunked = _.chunk(input,2)
var output = _.map(chunked, reducer)

output[0]
// "0,00"
output[1]
// "0,01"
// etc...
```

**Comment by jdalton** [comment]
The callback signature for map is `value, index, array`. I can't repro an issue with that.
