### ISSUE TITLE
[idea] modular architecture

### ISSUE THREAD

**Issue by trusktr** [lodash/lodash#1473]
It'd be nice if all the functions were requireable/importable without having to import the entire library. f.e.:

```js
import isEqual from 'lodash/isEqual'
```

We'd get the library by installing with NPM. Doing

```
import _ from 'lodash'
```

would import everything, like normal. With the use of static analyzers and ES6, we could do

```js
import { isEqual, after } as _ from 'lodash'
```

to import selective things.

For this to work properly, each function would have to be stored in it's own file and `import` whatever it needs (or `require` if you prefer CommonJS). There'd be an index.js file which would import everything and export everything, and that what you'd get when you `import _ from 'lodash'`.

**Comment by trusktr** [comment]
Check out [this branch](https://github.com/trusktr/react-famous/tree/joe) of my fork of react-famous to get an idea of how it could be done. Everything is in `src`, and on `prepublish` it compiles to the root (leaving `src` intact for package managers like [jspm](http://jspm.io) to handle ES6 modules directly). There's also an `build-global` script that builds a global for those `<script>` tag users. Included in dev dependencies are both webpack and browserify package in order to support those build systems, and there's a `jspm` property to support jspm. In my case, the global build can actually be improved by not including other globals like React or Famous (if I don't do it by the time you read this).

**Comment by Parakleta** [comment]
I've been just looking at this too, but the problem you have is that the

    import { isEqual, after } as _ from 'lodash'

syntax isn't valid ES6.

There is the lodash-es branch (npm lodash-es module) which gives you ES6.

**Comment by jdalton** [comment]
Hi @trusktr!

The good news is lodash already is modular.

It's in the readme, it's on the site, it's on the npm package page. It's kind of hard to miss.
The better news is that with v4 the lodash-es build will allow cherry-picking without requiring paths so instead of
```js
import chunk from "lodash/array/chunk"
```
you'll be able to do
```js
import chunk from "lodash"
```
