### ISSUE TITLE
About _.has

### ISSUE THREAD

**Issue by 285858315** [lodash/lodash#1474]
console.log(
        _.has(req.kms,"redis"),
        _.has(req.kms,"redis.comment_rule"),
        req.kms.redis.comment_rule.length
    )

output
true false 1

why?

**Comment by jdalton** [comment]
The `_.has` method looks for own properties of an object. My guess is that `comment_rule` is inherited.
In lodash v4 I've added `_.hasIn` to work with own and inherited props.
