### ISSUE TITLE
How does _.difference work?

### ISSUE THREAD

**Issue by berlincityboy** [lodash/lodash#1475]
Hi,

I have just created a little jsfiddle that shows how I would expect _.difference works. The lodash version in jsfiddle is *2.2.1*. https://jsfiddle.net/97bdb7ak/

The two arrays are 

["55fa3e2d9268d7127b6a2ad6","55f608920c7a8baf417a68eb","55f6053a0c7a8baf417a68e1","55fa3dfa9268d7127b6a2ad4","55f6083b0c7a8baf417a68e9","55f605800c7a8baf417a68e3","55f5f53b0c7a8baf417a68dd",**"55f62b020c7a8baf417a68f1"**]

["55fa3e2d9268d7127b6a2ad6","55f608920c7a8baf417a68eb","55f6053a0c7a8baf417a68e1","55fa3dfa9268d7127b6a2ad4","55f6083b0c7a8baf417a68e9","55f605800c7a8baf417a68e3","55f5f53b0c7a8baf417a68dd"]

However, in my node application I am using *lodash 3.10.0* and the output for the same invocation is

>> added 55fa3e2d9268d7127b6a2ad6
>> added 55f608920c7a8baf417a68eb
>> added 55f6053a0c7a8baf417a68e1
>> added 55fa3dfa9268d7127b6a2ad4
>> added 55f6083b0c7a8baf417a68e9
>> added 55f605800c7a8baf417a68e3
>> added 55f5f53b0c7a8baf417a68dd
**>> added 55f62b020c7a8baf417a68f1**
>> added 55f607870c7a8baf417a68e7

Actually, it should only contain the one I marked bold, right?

**Comment by jdalton** [comment]
The difference implementation for your usage hasn't changed between 2.2.1 and 3.10.0. Double check your node usage just in case.
