### ISSUE TITLE
map / each break when an object has length property

### ISSUE THREAD

**Issue by adityav** [lodash/lodash#1477]
I am using lodash 3.10.1

On console, type 
```
_.map( { length : 5 } , function(val, key) { return key; } )
[0, 1, 2, 3, 4]
```

Is this the correct behaviour? I feel that an object with length property is a very valid scenario and lodash should not break like this.

**Comment by jdalton** [comment]
The `_.map` and `_.each` methods are "Collection" methods which means they work on arrays, array-likes, and objects. The priority is on arrays and array-likes. An object with is considered array like and so is treated as an array.

What you want is `_.mapKeys`, `_.mapValues`, `_.forOwn`, and/or `_.forIn`.
