### ISSUE TITLE
sortBy not stable when sorting on NaN

### ISSUE THREAD

**Issue by kahlin** [lodash/lodash#1482]
When running the following code: 

```
var before = [0, 1, 2];
var after = _.sortBy(before, function(x) { return NaN; });
```
`after` will be `[2, 1, 0]` which is a bit unexpected given that `sortBy()` should be stable. This behavior has changed at least since lodash version 2.4.1.

(A jsfiddle is here: https://jsfiddle.net/yacu5x49/1/)

**Comment by jdalton** [comment]
The sort you where seeing in 2.4.1 was the result of sorting `NaN` to the beginning of the array, in later versions `NaN` values where sorted to the end of the array.
