### ISSUE TITLE
v3.10.1: Arguments mixup when combining _.find and _.partialRight

### ISSUE THREAD

**Issue by bbottema** [lodash/lodash#1483]
Somehow the arguments needed are mixed up in the following example:

https://jsfiddle.net/x3nury37/

```javascript
function One() {};
function Two() {};

function matchesType(obj, type) {
    return obj instanceof type;
}

var fPartial = _.partialRight(matchesType, One);

console.debug(fPartial(new One())); // true, as expected
console.debug(fPartial(new Two())); // false, as expected

// so far so good, now it starts to get weird
var arr = [new One(), 3, new Two(), new Two(), new One()];
console.debug(_.find(arr, fPartial));

// matchesType: Uncaught TypeError: Expecting a function in instanceof check, but got 0
```

Strangely, it works perfectly if you add a hard version as well and call that one first (they both start to work correctly):

https://jsfiddle.net/x3nury37/1/

```javascript
function One() {};
function Two() {};

function matchesType(obj, type) {
    return obj instanceof type;
}

var fPartial = _.partialRight(matchesType, One);
var fHard = function(obj) { return matchesType(obj, One); };

var arr = [new One(), 3, new Two(), new Two(), new One()];
console.debug(_.find(arr, fHard));
console.debug(_.find(arr, fPartial)); // now this works fine!!
```

**Comment by jdalton** [comment]
`partialRight` will append arguments to those provided so if you pass partially apply `'c', 'd'` and provide `'a'` then it would be `'a', 'c', 'd'` but if you provide `'a', 'b'` then it would be `'a', 'b', 'c', 'd'`.

In the case of `find` it's providing `value, index|key, object` and then your partially applied arguments are appended to that.

Instead what you want to use is `_.partial` with a placeholder:
```js
var fPartial = _.partial(matchesType, _, One);
```

**Comment by bbottema** [comment]
Ahh, I see now. I was wondering why the index was provided, I overlooked it in the API docs. Thanks for clarifying.
