### ISSUE TITLE
Decapitalize?

### ISSUE THREAD

**Issue by MeoMix** [lodash/lodash#1485]
Heya,

I had a scenario where I wanted to decapitalize a string, i.e. "FOO" => "fOO" and noted that only a `capitalize` method existed in lodash.

Is that something that'd be of interest for core to provide parity, or not widely used enough?

**Comment by russplaysguitar** [comment]
:+1:

**Comment by jdalton** [comment]
My gut feeling is that this isn't widely used enough to warrant inclusion. But as with other requests user demand (+1's) help shape that picture. @MeoMix can you explain your use case for this.

**Comment by MeoMix** [comment]
Sure.

Our application consists of a C# back-end and JavaScript front-end. Common C# naming convention for property is "Foo" where as JavaScript convention is "foo."

We serialize an object from the server to the client and, in the serialization process, perform a deep conversion of property names from C# to JS conventions.

So, we had something like:

    RowKeys: ["Foo", "Bar"],
    RowData: [{ Foo: "..."}, { Bar: "... "}]

which was converted to:

    rowKeys: ["Foo", "Bar"],
    rowData: [{ foo: "..."}, { bar: "..."}]

I now needed to correlate "Foo" to "foo" while honoring JS syntax. So, I wasn't so much interested in capitalizing "foo" so much as I was interested in decapitalizing "Foo"

The example's a bit contrived -- there was some extra processing which made using capitalize more verbose -- but that's the gist of how I came about desiring this.

**Comment by jdalton** [comment]
@MeoMix You might dig `_.camelCase`.

**Comment by MeoMix** [comment]
Yeah. I knew about it, but it modifies spacing. Our process... wasn't so smart and would lowercase the first letter without taking into account spaces (not proper camel casing, although it should've been doing that). Thus the need for something else. The more I talk about this though the more it sounds like an edge case not worth adding :p

**Comment by Delapouite** [comment]
A middle ground could be a new function inversing the case of each letters : lOdASh -> LoDasH
This way one could compose this new method with `capitalize`

**Comment by StreetStrider** [comment]
@Delapouite, wow, I had the same idea.

**Comment by jdalton** [comment]
That would over reach as `capitalize` just changes the case of the first letter.
