### ISSUE TITLE
_.sortByOrder with null values

### ISSUE THREAD

**Issue by vovagusarov** [lodash/lodash#1491]
Lodash  3.10.1
Trying to sort objects with null value

```javascript
var users = [
  { 'user': 'fred',   'age': 48 },
  { 'user': 'barney', 'age': 34 },
  { 'user': 'fred',   'age': null },
  { 'user': 'barney', 'age': 36 }
];

_.pluck(_.sortByOrder(users, ['age', 'user'], ['desc', 'desc']), "age");
```
and result is:
```javascript
[null, 48, 36, 34]
```
expected to be like:
```javascript
[48, 36, 34, null]
```
or i'm wrong?
Thanks.

**Update:**
seems like it's related to _.sortBy realisation, look the following examples for the same array:
- Lodash 3.10.1:
```javascript
_.pluck(_.sortBy(users, 'age'), "age");
// [34, 36, 48, null]
```

- Lodash 3.6.0:
```javascript
_.pluck(_.sortBy(users, 'age'), "age");
// [null, 34, 36, 48]
```

**Comment by jdalton** [comment]
Correct, is now moved to the end when sorted (ascending) so when sorting descending will be at the front of the array. Could you `_.compact` your results before sorting?

**Comment by vovagusarov** [comment]
Sorry for misleading you.
I need a complete array even if "age" of whatever key is ```null``` the other one for ex. "name" is filled, so i can't just ```_.compact``` it and throw it away.
Is there any Lodash solution to get this array sorted as I mentioned?

**Comment by jdalton** [comment]
You could pass iteratees (functions). If you're just concerned with `null` you can coerce them to `0` with `Number`.
```js
var byAge = _.flow(_.property('age'), Number);
_.map(_.sortByOrder(users, [byAge, 'user'], ['desc', 'desc']), 'age');
// => [48, 36, 34, null]
```
