### ISSUE TITLE
feature: function for boolean pattern-matching

### ISSUE THREAD

**Issue by lukewestby** [lodash/lodash#1492]
For now I'll refer to the function as `_.guard()`, although I know that name is used internally, since the behavior is adapted from the guard feature of other functional languages.

`_.guard()` could be called with a variadic list of arrays as follows:

```javascript
const input = 1;
const result = _.guard(
  [ input === 2, 'two' ],
  [ input === 3, 'three' ],
  [ input === 4, 'four' ],
  [ input === 1, 'one' ],
  [ true, 'default was reached' ]
);
// result === 'one'
```
My colleague @lambdahands introduced me to it and I've been using this functionality a lot recently to clean up functions with a lot of complex branching on conditions. I thought it might be useful as a part of lodash, so let me know what you think!

**Comment by lambdahands** [comment]
For more information about pattern guards, checkout [how they're used in Haskell](https://en.wikibooks.org/wiki/Haskell/Control_structures#if_and_guards_revisited) as well. They're very handy for flattening nested logic branches!

**Comment by jdalton** [comment]
I'm not sure this syntax is much better than vanilla alternatives. I'll be adding a logic/composition methods for if/if-else/else cases but not the raw value form. Let's wait and see if there's demand for something like this. Until then you can always add it as a `mixin`.

**Comment by lukewestby** [comment]
Sounds good, thanks for taking a look.

**Comment by tusharmath** [comment]
Pattern matching is a must have. Especially if one wants to work with lazy evaluations or dynamically append conditions.

From a syntax point of view how about —

```
const val = 10

_.match(val)
  .case(val < 10, 'less')
  .case(val > 10, 'greater')
  .case('10', (x, i) => 'type is string') // x should be val & i should be '10'
  .default('equal') // default should be required so that we know when to start the pattern matching.
```

I am myself using a mixin right now.

**Comment by tusharmath** [comment]
@jdalton ping!!!

**Comment by jdalton** [comment]
@tusharmath Still not up for adding this as is.

**Comment by tusharmath** [comment]
A peny for your thoughts?

**Comment by jdalton** [comment]
See https://github.com/lodash/lodash/issues/1492#issuecomment-143816220.
