### ISSUE TITLE
lodash + jshint + Komodo Edit issue

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1493]
jshint, as of 2.7.0, have moved from using underscore to using lodash. They have done a straight swap out of libraries. I am using Komodo Edit which can use jshint in its editor. With jshint 2.6.3 and Komodo, I have no issues but as soon as I move to 2.7.0+ then it no longer functions. I replaced lodash in jshint 2.8.0 with the latest underscore 1.8.3 and everything works again. The problem seems to be with detecting the context in runInContext. I don't know who owns the fault, is it Komodo, jshint or lodash? I have opened issues with the other projects in the hope that a future solution can be found (other than me copying and pasting in underscore as a replacement of lodash). 
https://github.com/jshint/jshint/issues/2696
https://github.com/Komodo/KomodoEdit/issues/603

**Comment by jdalton** [comment]
Hi @Xotic750! We've patched a couple issue related to the UMD in v4 (master branch) but it has some breaking changes for jshint (like we no longer have the `_.contains` alias). If you were to drop lodash v4 in with the aliases added you could see if that resolves the issue.

**Comment by Xotic750** [comment]
@jdalton I replaced _.contains with _.includes in jshint 2.8.0 and then dropped in lodash from the master branch, reloaded it into Komodo Edit and hey presto it works. So the UMD changes seem to have been a success. Thanks for the information, I'll report this back to Komodo team and close the issue with them. Then I guess I wait for a new release of lodash and jshint.

**Comment by jdalton** [comment]
Rock, I'll see about doing a patch bump before 4.0 to knock this out sooner than later.
