### ISSUE TITLE
sliceAt which returns the opposite of slice

### ISSUE THREAD

**Issue by jcrben** [lodash/lodash#1494]
If I slice a section of an array, I get that array, but it seems like it could be handy to get the balance of the array that's being thrown away. So if I have an array with elements [1..100] and I want elements [1..50, 60..100], I'd like to be able to grab that without doing a couple steps to slice each side and concatenate them. Is there a function like this? It seems like there's a few functions which return the removed elements (`_.remove`, `_.pull`) and none which do what I'm looking for. There is `_.reject`, but I'd rather not have to iterate through the array if I know the range of indexes to remove. In the `_.remove` issue discussion, [someone suggested this](https://github.com/lodash/lodash/issues/281#issuecomment-18384938) for `_.pull` and someone pointed to `_.without`, but without is a fair bit broader since it removes matching values.

**Comment by jdalton** [comment]
I think two `slice()` calls is the answer, it'd be that way under the hood and handles this situation (which I think is a rare one to be in) well.
