### ISSUE TITLE
lodash deepclone scales poorly

### ISSUE THREAD

**Issue by iarna** [lodash/lodash#1496]
I encountered this in particular in cloning huge cross linked tree structures for npm.

Per discussion on Twitter, this is due to the circular dependency check:
```
 * @param {Array} [stackA=[]] Tracks traversed source objects.
 * @param {Array} [stackB=[]] Associates clones with source counterparts.
```
```
  var length = stackA.length;
  while (length--) {
    if (stackA[length] == value) {
      return stackB[length];
    }
  }
```

Now, if lodash could count on access to Maps or WeakMaps then this could be easily worked with of course.  This led me to investigating how es6 map shims work– many of them work like lodash, doing a linear scan of a keys array, but core-js does not:

https://github.com/zloirock/core-js

It's implementation is here:

https://github.com/zloirock/core-js/blob/master/modules/es6.map.js

Which in turn has the bulk of its implementation here:

https://github.com/zloirock/core-js/blob/master/modules/%24.collection-strong.js

If you dig into that, you can see that ultimately they add a non-enumerable element named `ID` with a unique id they generate and use that as the key for their Map objects.

Uh... I'm not exactly sure what I'm suggesting here. The current behavior works fine for small objects but goes very very bad with large ones. At the same time, mutating the original object is super ugly. =/ I kind of don't like either option.

My colleague @zkat suggested maybe having deep-clone take an optional additional argument that's a function that, given an object returns a unique identifier for it.  If this was passed in then deep-clone could use this to compute a key to be used in a fast property lookup instead of scanning a list– with the list scan as a fallback if such a function doesn't exist. The end user could then choose to either mutate their objects or use knowledge of how their data structures to select an already existing unique property…

**Comment by jdalton** [comment]
In 2.x versions of lodash we implemented our own [set-like optimization](https://github.com/lodash/lodash/blob/2.4.1/lodash.js#L206-L258). In v3.x we moved away from that to using built-in `Set` [when available](https://github.com/lodash/lodash/blob/8f431cff529afaf6495f625ac2da22fa2a0f3223/lodash.js#L1771-L1818).

I'll rework the linear searches to use the existing Set optimizations which should avoid the issue.

**Comment by jdalton** [comment]
@iarna Out of curiosity (and to help with future heuristics) do you happen to know how many circular reference checks it was performing?

**Comment by iarna** [comment]
I don't know for certain, we're talking a 2566 packages– any given module is probably linked to three times, so maybe something in the 7000-8000 range? Oh, but each of those objects ALSO has a package.json object, which has a bunch of sub objects so... maybe 20000-30000 overall?

**Comment by jdalton** [comment]
Awesome!!! Totally geeking out on this case :D

**Comment by jdalton** [comment]
What versions of Node does npm v3 support?

**Comment by jdalton** [comment]
I'll try to mush the `MemCache` and `Stack` map shims together tonight.

**Comment by iarna** [comment]
npm supports >= 0.8

**Comment by jdalton** [comment]
I took it a step further and combined `MemCache` and `Stack` into `MapCache`. This has a couple of benefits.

 * Less code as there's 1 shared map cache
 * `_.memoize` now works with object keys out of the box
 * Older environments get the benefits of map-like wins (avoiding linear lookups for all but objects)
 * I went ahead and optimized the string key case while I was at it

**Comment by jdalton** [comment]
Bonus I implemented the `SetCache` by way of `MapCache`.
