### ISSUE TITLE
Lodash templating doesn't work as expected

### ISSUE THREAD

**Issue by lifeiscontent** [lodash/lodash#1500]
put this testcase together.

getting an error on parsing of the template.

http://codepen.io/lifeiscontent/pen/OyWWvz

**Comment by jdalton** [comment]
Lodash's `_.template` isn't like other logic-less template engines as it constructs a function. You can coerce the template method to a string to see the source it generates for the template.

**Comment by lifeiscontent** [comment]
@jdalton I'm not quite sure what you mean.

**Comment by jdalton** [comment]
The use of the `interpolate` delimiter is incorrect as it's used to resolve data property values and related expressions. The `evaluate` template is more along the lines of what you're wanting but then you'll want though you may need to use the `print()` helper. Review the [_.template docs](https://lodash.com/docs#template) for examples of each delimiter type.

You can get the compiled source of the template to see how things are compiled by:
```js
console.log(_.template($('#things-template').html()).source);
```

**Comment by lifeiscontent** [comment]
@jdalton thank you very much for your explanation.
