### ISSUE TITLE
Unexpected behavior with _.escapeRegExp

### ISSUE THREAD

**Issue by albertywu** [lodash/lodash#1502]
`_.escapeRegExp('abc')`

returns "\x61bc"

I would expect it to return "abc" since there are no regex characters to escape.

Seems like it comes from here:
https://github.com/lodash/lodash/blob/3.10.1/lodash.src.js#L10548
https://github.com/lodash/lodash/blob/3.10.1/lodash.src.js#L100

**Comment by jridgewell** [comment]
Related discussion here: https://github.com/lodash/lodash/issues/1310

I think this is intentional since `a` is a valid hex character.

**Comment by jdalton** [comment]
Ya. I was experimenting with a context safe approach in coordination with the `RegExp.escape` spec proposal. I have since reversed that and gone with the simpler approach in v4.
