### ISSUE TITLE
Add _.isInteger

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#1503]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

```js
Number.isInteger(0.1);     // false
Number.isInteger(1);       // true
Number.isInteger(Math.PI); // false
Number.isInteger(-100000); // true
Number.isInteger(NaN);     // false
Number.isInteger(0);       // true
Number.isInteger("10");    // false
```

**Comment by jdalton** [comment]
It's in master now via https://github.com/lodash/lodash/commit/49266dce89b7ac62b45a193a14d05188212d1eca :D

**Comment by gajus** [comment]
Amazing. Sorry, should have looked. There was an issue for that already (https://github.com/lodash/lodash/issues/1020).
