### ISSUE TITLE
Minified build for Node Modules

### ISSUE THREAD

**Issue by dthree** [lodash/lodash#1505]
Hey there. First of all, congrats on `0` open issues over `1170+` closed - that's impressive. :)

I'm very aware that there's a ton of customization options for building minified / broken up versions of `lodash` for use in browsers. I am also aware the NPM module size is not *usually* considered a concern.

With those points in mind, let me bring up my consideration:

I've been working a few CLI apps in node, which means a human being (developer) is going to download them and use them as tools. In this case, when the user types `npm install mycliapp`, he is staring at the screen, waiting for every KB to download. Optimally, I want these applications as small as possible.

The full `lodash` you get with an `npm install lodash` is huge - `822kb`. This compares to the `50k` full minified version. In an attempt to solve this, I turned to the individual builds (`lodash-isobject`, etc.). By the time I pulled in the 12 `lodash` modules that my project used, the size exceeded `822kb`, due to the added on luggage of licenses, readmes, duplicate dependencies, etc.

This seems like an unnecessary problem.

I thought of building my own minified version and publishing it to NPM, but I know I'm not going to maintain it as much as we both would like, and you don't seem to like that idea either:

https://github.com/ide/ld-min/issues/1

Is there any way you could guys could add on to all of your awesome build automation the publishing of an official `lodash-min` Node module?

That'd be totally awesome, and given the popularity of `lodash`, you'd probably save terabits of web bandwidth over time :)

**Comment by jdalton** [comment]
The package .tgz is 176kb (what's downloaded) and cached by npm.
