### ISSUE TITLE
_.downcase and _.upcase requested.

### ISSUE THREAD

**Issue by Droogans** [lodash/lodash#1510]
For some reason, I'm not able to pass in `String.prototype.toLowerCase.call` as a function object to `.then` in protractor. Not sure it'd be a major priority for you, but I'd appreciate it if I could pass in `_.downcase` to `.then` and not have to write it all out everytime.

```js
return myElement.getText().then(function (text) {
    return text.toLowerCase();
});
```

versus

```js
return myElement.getText().then(_.downcase);
```

I feel this would compliment `camelCase`, `snakeCase`, and other casing helpers.

**Comment by jdalton** [comment]
If you do a pull request for `_.lowerCase` and `_.upperCase` I'll add it.

**Comment by jdalton** [comment]
Moving to #1511.
