### ISSUE TITLE
Minification failing when using Microsoft's System.Web.Optimization (the default minification provider) 

### ISSUE THREAD

**Issue by ichpuchtli** [lodash/lodash#1512]
I'm hesitant to open this issue as it's probably an issue with System.Web.Optimization, but anyway just letting you know since 3.7.0 minification has been failing with System.Web.Optimization which is asp.net's default bundling/minification provider.   

I've lodged an issue on their code repository but It's not very active.
https://aspnetoptimization.codeplex.com/workitem/169

Below is the response you get from my asp.net mvc project.
https://gist.github.com/ichpuchtli/4383a95f1912fcd92067  

If you look at the top of the response copied below, the minifier reports an error which it prepends to the response. 
```js
/* Minification failed. Returning unminified contents.
(19,462-469): run-time error JS1019: Can't have 'break' outside of loop: break n
 */
/**
 * @license
 * lodash 3.7.0 (Custom Build) lodash.com/license | Underscore.js 1.8.3 underscorejs.org/LICENSE
 * Build: `lodash modern -o ./lodash.js`
 */
...
```
The line number 19 does not map to your source as it was partially minified even though it said it returned the unminified contents.

I will update this issue with news from their codeplex site. 

Regards,
Sam

**Comment by jdalton** [comment]
Thanks for the heads up. This sounds like a bug on their end so closing here but feel free to post updates to their bug status.

**Comment by alexandrevtukh** [comment]
I see this issue again in version 1.6.0
