### ISSUE TITLE
Add `thisArg` to `_.defer`?

### ISSUE THREAD

**Issue by superscript18** [lodash/lodash#1515]
Could `_.defer` have a context argument (`_.delay(func, wait, thisArg, [args])` or something) like `_.each` has?

Is there a reason this shouldn't exist?

**Comment by jdalton** [comment]
In v4 we've removed `thisArg` params from methods opting for simply using `_.bind` instead.

**Comment by superscript18** [comment]
Does that make `_.each`'s `thisArg` deprecated?

**Comment by jdalton** [comment]
Yep.
