### ISSUE TITLE
Add isGeneratorFunction(fn)

### ISSUE THREAD

**Issue by callumlocke** [lodash/lodash#1523]
Looks like there's a bunch of ways to check if a function is also a generator function...
http://stackoverflow.com/questions/16754956/check-if-function-is-a-generator

Could lodash decide on the most bulletproof approach and implement it?

**Comment by jdalton** [comment]
Please read search before posting. There have been two other issues filed.
This issue has been tackled in the master branch.

**Comment by d10** [comment]
@jdalton I think you kinda misunderstood the issue; it was meant to be a feature request to add a new `_.isGeneratorFunction` function.

**Comment by jdalton** [comment]
Ohhhh, no that won't happen.

**Comment by callumlocke** [comment]
> Ohhhh, naw I'm not interested in that kind of method at the moment.

ok. any reason why? :)

**Comment by jdalton** [comment]
I'd like to keep things simple for now and treat a function like a function like a function.
If demand for `_.isGeneratorFunction` and `_.isGeneratorObject` grows I'll reevaluate.

In regards to the SO thread the way to detect them would be:
```js
Object.prototype.toString.call(genFunc) === '[object GeneratorFunction]';
Object.prototype.toString.call(genObj)   === '[object Generator]';
```

**Comment by charliegroll** [comment]
I would also be interested in this. For now, we use the following:

```
if (variable.constructor.name === 'GeneratorFunction') {
  yield variable.call(this, param);
}```
