### ISSUE TITLE
Allow _.where and similar functions to match on an array of values

### ISSUE THREAD

**Issue by abgivant** [lodash/lodash#1524]
Would it be possible to modify the underlying matching function behind _.where and similar functions to allow matching on arrays of values in addition to the standard simple key:value matching? I understand this might add too much of a performance hit, but I feel like this would be a pretty useful addition.

**Example:**

``` JavaScript
var arr = [{val: 1}, {val: 2}, {val: 3}];

var filter = {val: [1, 3]};

_.where(arr, filter);
// Ideally would return => [{val: 1}, {val: 3}]
```

The matching function could potentially look something like this:
``` JavaScript
function isMatch(obj, filter) {
  for (var prop in filter) {
    if (filter.hasOwnProperty(prop)) {
      if (_.isArray(filter[prop])) {
        if (filter[prop].indexOf(obj[prop]) === -1) return false;
      }
      else {
        if (obj[prop] !== filter[prop]) return false;
      }
    }
  }

  return true;
}
```

**Comment by jdalton** [comment]
As the feature is outlined here, no, but I am looking into adding a [predicate based matcher](https://github.com/jashkenas/underscore/issues/2318).

**Comment by StreetStrider** [comment]
@jdalton, can you tell which function is used under the hood to transform the filter/map/etc predicate-ish argument? I was remembering it was something like `_.create-something` (`_.createPredicate`/`_.createProperty`?), but now is it `_.property` or what?

I think many of similar issues can be solved in terms of `_.flow`/`_.conj`/`_.disj` composition. This allows developers to construct their own predicates in very terse manner and not to overload default LoDash behavior.

**Comment by jdalton** [comment]
> can you tell which function is used under the hood to transform the filter/map/etc predicate-ish argument? 

The internal method for `_.conj`, `_.disj`, and `_.juxt` is the generically named `createInvoker` (I gotta call it something).

>  I think many of similar issues can be solved in terms of `_.flow`/`_.conj`/`_.disj` composition.

Share a snippet of how it could be composed.

**Comment by StreetStrider** [comment]
@jdalton, no, not `createInvoker`, but I found it `_.callback`. The main idea is to `_.conj`/`_.disj` «callbacked» arguments.

The TS' issue is a little more difficult, since he wants to `or` combination for a certain property.

```js
_.disj(_.callback({ val: 1 }), _.callback({ val: 3 }))
```
If  `_.conj`/`_.disj` is not casted to boolean.
