### ISSUE TITLE
_.capitalize() doesn't format uppercase strings.

### ISSUE THREAD

**Issue by pdxbmw** [lodash/lodash#1528]
It may be intentional functionality, but `_.capitalize()` only formats lowercase strings and not uppercase strings. 

Example:
 `_.capitalize('UPPERCASE') => 'UPPERCASE'` (current)
`_.capitalize('UPPERCASE') => 'Uppercase'` (desired)

**Comment by jdalton** [comment]
Hi @pdxbmw! It was intentionally designed this way. It was based on how other libs (underscore.string, mootools, etc) handled it.

**Comment by pdxbmw** [comment]
Hi @jdalton! That's good to know. I suppose it's easy enough to lowercase the string first anyway. Thanks for the quick response.

**Comment by jdalton** [comment]
The more I read into the meaning of capitalization the more I question everything :D

**Comment by pdxbmw** [comment]
Yeah, by strict punctuation rules, *capitalization* would only uppercase the first letter and lowercase all remaining letters. It seems confusing to me that the `_.capitalize()` function would output an uppercase string, but I suppose it's up for interpretation. ;)

**Comment by jdalton** [comment]
The solution is to make `_.capitalize` follow capitalization rules and have `_.lowerFirst` and `_.upperFirst` methods :D

**Comment by Shwetabh1** [comment]
@jdalton  The [Documentation](https://lodash.com/docs/4.17.5#capitalize) gives an explicit example where it takes UPPERCASE String 'FRED' and using `_.capitalize` converts it to 'Fred'.
Isn't it a bit misleading as capitalize doesn't work that way?
