### ISSUE TITLE
index.js -> lodash.js

### ISSUE THREAD

**Issue by Diokuz** [lodash/lodash#1529]
Hi there.

In my project, for some reasons, I have to put lodash var to window (I cannot use require() for dependence management).

jQuery, React, Backbone and many other js libraries has dist file named as library itself.
`backbone.js`
`dist/jquery.js`
etc.

But for lodash I have to use `gulp-rename` to copy `index.js` to `lodash.js`.

Why main file is named `index.js` ?

For defining main file there is an package.json option
`"main": "lodash.js"`

**Comment by jdalton** [comment]
Because you're using the npm package which is designed for node environments or those that bundle (like browserify or webpack).

If you're looking for client side packages try bower or [cdnjs](https://cdnjs.com/).

**Comment by ocombe** [comment]
I disagree with that opinion, npm is now used by client side applications as well, and having a correct "main" seems to be a legitimate request.

**Comment by jdalton** [comment]
The "main" is correct it's just named index.js.

**Comment by ocombe** [comment]
You're right, my bad :)

**Comment by jdalton** [comment]
It's trivial to tweak so if it's causing grief our v4 can switch to being named lodash.js.

**Comment by ocombe** [comment]
I'd rather have a minified version in the npm repo, that would save me some trouble :)

**Comment by jdalton** [comment]
For v4 there's now a `lodash.js` in the package.
