### ISSUE TITLE
Expected behaviour of _.has({ test: 1}, 'test.'), true or false?

### ISSUE THREAD

**Issue by lazywithclass** [lodash/lodash#1531]
Which of the following is correct?

1. `_.has({ test: 1}, 'test.') // true`
2. `_.has({ test: 1}, 'test.') // false`

I could not find a test or a previous issue about this, sorry if there's one.

If it's 1 so what about adding an example to the docs specifying this edge case? 
I am happy to help with a PR either way (docs or code), what do you think?

**Comment by jridgewell** [comment]
Great edge case. Currently, the first is correct, but I think the second should be instead (`''` is a valid key).

**Comment by lazywithclass** [comment]
I am adding the required code to submit a PR. I have a few problems understanding how to do it though:

 * if I run `_.has({test: 1}, 'test.')` in the console at http://lodash.com I get `true`
 * if I run `require('./lodash').has({test: 1}, 'test.')` from the project root I get `false`

I am a bit confused about these different outputs. 

Right now on http://lodash.com it says the latest version is v3.10.1, I am testing this on `master`, should I test on a different branch?

**Comment by d10** [comment]
The master branch no longer contains this issue.

**Comment by lazywithclass** [comment]
Ah good then, I've seen that `has` is different now. Thanks, I will close this.
