### ISSUE TITLE
A _.del counterpart to _.get and _.set

### ISSUE THREAD

**Issue by Industrial** [lodash/lodash#1533]
Hi.

I'm using `_.get` and `_.set` for configuration objects but I'm missing a delete functionality that actually uses the delete statement to remove a key from an object (I guess a `.splice` from an array? or just a `_.without`?). Right now I'm using `_.set(k, undefined);` but that's a pretty bad solution, right?

**Comment by jdalton** [comment]
This is in edge master branch as `_.unset`.

**Comment by Industrial** [comment]
Great! How do I use this branch / when will it be available in a build?

**Comment by d10** [comment]
The latest lodash.js in the master branch will be released as lodash v4.0 soon.
