### ISSUE TITLE
jQuery Dev Summit ’15 Items

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash#1534]
- [x] Add `_.lowerCase`, `_.lowerFirst`, `_.toLower`, `_.toUpper`, `_.upperCase`, `_.upperFirst` tests
- [x] Add [lodash-fp](https://github.com/lodash/lodash-fp) `convert` module to lodash as `fp`
- [ ] Break [lodash-cli](https://github.com/lodash/lodash-cli) bin/lodash into multiple modules
- [ ] Contribute to the [lodash website](https://github.com/lodash/lodash.github.io/issues/8)
- [ ] Add `foo.default.js` modules for the [lodash-es](https://github.com/lodash/lodash/tree/es) build.
- [ ] Sanity check lodash [perf](https://github.com/lodash/lodash/tree/master/perf) compared to v3
- [ ] Blog drafts/outlines for lodash v4
- [ ] Outstanding [docdown issues](https://github.com/jdalton/docdown/issues)
- [ ] Outstanding [lodash-fp issues](https://github.com/lodash/lodash-fp/issues)

**Comment by mathiasbynens** [comment]
`r=me`:

- [ ] Add `_.lowerCase` tests
- [ ] Add `_.lowerFirst` tests
- [ ] Add `_.toLower` tests
- [ ] Add `_.toUpper` tests
- [ ] Add `_.upperCase` tests
- [ ] Add `_.upperFirst` tests

**Comment by d10** [comment]
I’ll try to help out with the website and docdown/lodash-fp issues. Also fine with helping to draft a blog post for v4, ping me if you need help :)

**Comment by jdalton** [comment]
Closing as this was intended as an easy way to group issues from multiple repos during the summit.
