### ISSUE TITLE
Rounding error in _.range

### ISSUE THREAD

**Issue by zachhale** [lodash/lodash#1539]
Using version 3.10.1:

`_.range(0, 0.6, 0.1)`

returns

`[0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5]`

That's not right.

**Comment by jridgewell** [comment]
That's a JS issue, not a lodash one.

```js
i = 0;
i += .1; // 0.1
i += .1; // 0.2
i += .1; // 0.30000000000000004
```

**Comment by zachhale** [comment]
Is there something lodash can do to improve the result here regardless?

**Comment by Xotic750** [comment]
Perform its own arbitrary-precision arithmetic instead of using Javascript's built in IEEE 754? Can't see it happening.

**Comment by jridgewell** [comment]
> Is there something lodash can do to improve the result here regardless?

Unfortunately not. You're able to get around this by using `_.range` and `_.map`:

```js
_.map(_.range(0, 6), function(i) { return i / 10; }); // => [0, 0.1, 0.2, 0.3, 0.4, 0.5]
```

**Comment by jdalton** [comment]
We've avoided floating-point issues in [our round methods](https://github.com/lodash/lodash/pull/1487) so I'm open to tackling it if its doable and not too much trouble. @zachhale if you have suggestions or approaches I'd totally be up for a PR.

**Comment by exogen** [comment]
Don't throw in the towel so easily! The problem is accumulated summing, which people have worked around in the past. Might be able to use this as guidance: http://alex.uwplse.org/2015/10/16/improving-accuracy-summation.html

**Comment by exogen** [comment]
https://en.wikipedia.org/wiki/Kahan_summation_algorithm

**Comment by exogen** [comment]
So here's a quick and dirty test (there may be bugs):

```
lodash = require('lodash');

function range(start, stop, step) {
  var sum = start;
  var err = 0;
  var nums = [];
  while (sum < stop) {
    nums.push(sum);
    err = step - (((sum + step + err) - sum) - err);
    sum = sum + step + err;
  }
  return nums;
}

a = lodash.range(0, 600, 0.1);
b = range(0, 600, 0.1);

function countInexact(arr) {
  var total = 0;
  arr.forEach(function(n) {
    if (n.toString().length > 12) {
      total += 1
    }
  });
  return total;
}

console.log('lodash:', countInexact(a));
console.log('with err compensation:', countInexact(b));
```
Some numbers are just hopeless – we still get the `0.30000000000000004` and other rounding errors. But we get far fewer:

```
lodash: 5981
with err compensation: 2391
```

**Comment by exogen** [comment]
Even better results, just multiplying `step` by which iteration you're on:

```
function range2(start, stop, step) {
  var sum = start;
  var nums = [];
  var i = 1;
  while (sum < stop) {
    nums.push(sum);
    sum = start + step * i;
    i++;
  }
  return nums;
}
```

Inexact numbers produced:
```
lodash: 5981
with err compensation: 2391
with i * step: 2023
```

**Comment by jdalton** [comment]
@exogen Keep kicking it around :)

**Comment by jridgewell** [comment]
Normalize all digits to integers, do the range, denormalize. But that's banking on no rounding issues with dividing an int by a power of 10.

**Comment by exogen** [comment]
@jridgewell Yeah, trying that out now – it's promising so far!

**Comment by jdalton** [comment]
> But that's banking on no rounding issues with dividing an int by a power of 10.

See https://github.com/lodash/lodash/pull/1487/files#diff-001d0647fb00f8336795faccdec19a31L3702.

**Comment by Xotic750** [comment]
How about implementing the bits you need internally from something like https://github.com/MikeMcl/big.js/ and limit the range? Slow probably but should be accurate. Just a thought.

**Comment by jdalton** [comment]
> How about implementing the bits you need internally from something like https://github.com/MikeMcl/big.js/ and limit the range?

Lodash is a general utility lib so if this is a can of worms we can always punt to a more specialized lib (e.g. [he](https://www.npmjs.com/package/he) for html encoding).

**Comment by Xotic750** [comment]
Limit what lodash can answer authoritatively and have `_.range` work only with safe integers.

**Comment by zachhale** [comment]
Or at a minimum in the interim maybe there should be docs about floating point issues.

**Comment by jdalton** [comment]
> Limit what lodash can answer authoritatively and have _.range work only with safe integers. :/

Naw, this gets into the territory of input validation which introduces overhead we simply don't need for these kinds of edge cases. 

> Or at a minimum in the interim maybe there should be docs about floating point issues.

I'm cool with adding a doc note. @zachhale would you be up for doing the PR?

**Comment by zachhale** [comment]
@jdalton I'll take a cut

**Comment by exogen** [comment]
Here's my current solution, which seems to produce as good results as possible in every case I've tried.

Will post a PR later tonight. Could use some careful review:

```
function range(start, stop, step) {
  var result = [];
  var descend = stop < start;
  if (descend ? step < 0 : step > 0) {
    // If `step` is fractional, we may multiply it to get more exact results.
    var multipliedStep = step;
    var factor = 1;
    // Only do extra work for fractional `step` values.
    if (step % 1 !== 0) {
      var exponentParts = step.toExponential().split('e');
      // If the step looks inexact already, and would result in a very large
      // `factor`, don't even attempt to get more exact results.
      if (exponentParts[0].length < 16) {
        multipliedStep = +(exponentParts[0].replace('.', ''));
        // We know `factor` should be a power of ten. Do we need to potentially
        // use `round` or `floor` here to ensure this float division doesn't
        // screw that up?
        factor = multipliedStep / step;
      }
    }
    var multipliedStart = start * factor;
    var sum = start;
    var i = 1;
    while (descend ? sum > stop : sum < stop) {
      result.push(sum);
      sum = (multipliedStart + i * multipliedStep) / factor;
      i++;
    }
  }
  return result;
}
```

@zachhale, you'll be happy to see that with this, `range(0, 0.6, 0.1)` gives `[ 0, 0.1, 0.2, 0.3, 0.4, 0.5 ]`. All the other methods I tried didn't. :)
