### ISSUE TITLE
Documemtation about limit using _.random

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1540]
Following up an another discussion regarding `_.range` (https://github.com/lodash/lodash/issues/1539). I think it would be worth adding documentation regarding `_.random` limits if they cause the calculation to exceed max or min safe integer. Alternatively throw a RangeError when the calculations exceed these limits.
```
function baseRandom(min, max) {
      return min + nativeFloor(nativeRandom() * (max - min + 1));
}
```

A reference: http://stackoverflow.com/questions/28461796/randomint-function-that-can-uniformly-handle-the-full-range-of-min-and-max-safe

**Comment by jdalton** [comment]
I'm not up for throwing, lodash tries to avoid throwing. If you'd like to add a doc note create a PR with the addition.

**Comment by Xotic750** [comment]
If I can get my brain into gear, when my 2 year old is not crying and screaming, I will see if I can come up with something legible. Would it be as comments in the source with function or in some particular file in the project?

**Comment by jdalton** [comment]
It would be as a continuation of the comments [in the description block](https://github.com/lodash/lodash/blob/08cd8adfdbe061e4a93868c261a110e7ba0260fc/lodash.js#L10935-L10938) of `_.random`.

**Comment by jdalton** [comment]
Open the PR at any time. No hurry.

**Comment by Xotic750** [comment]
I'll get there eventually ;)

**Comment by Xotic750** [comment]
@jdalton I'm thinking something like this?
```
     * Note: Javascript uses IEE 754 which can take the programmer by surprise
     * with unexpected precision errors. In the case of random, one example is
     * when the integer range between max and min near or exceed the
     * MAX_SAFE_INTEGER value then rand will not return the full range that you
     * may expect: numbers can no longer be represented accurately. Similar is
     * also true when the values for max and min are small or are not integer
     * representations: rounding errors can occur. This is not something that
     * lodash has control over.
```

**Comment by jdalton** [comment]
That's a good start. I'll wordsmith it a bit.

**Comment by Xotic750** [comment]
Do you still want this as a PR?

**Comment by jdalton** [comment]
Yap.
