### ISSUE TITLE
_.throttle synchronous invocation

### ISSUE THREAD

**Issue by jareware** [lodash/lodash#1542]
I don't think there's anything in the documentation that would indicate either way, but will `_.throttle()` actually invoke its callback **synchronously** if its wait period has already passed?

If so, this is rather surprising when you think of throttling as a fundamentally asynchronous operation, and has the potential to cause subtle code path changes (sync vs. async) when you manage to block your main thread just long enough to surpass the wait period.

Asking for a friend.

**Comment by jdalton** [comment]
I believe the documentation is sufficient for `_.throttle`. There's even a link to blog post that takes a deep dive into it.  Executing on the trailing end of the wait timeout is configurable. The documentation covers the default options for `_.throttle` and the invocation behavior.

**Comment by jareware** [comment]
Fair enough. :)
