### ISSUE TITLE
Enhancement: isDate or isDateValid

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1546]
Another one if find myself using. Either enhance _.isDate 
```
    function isDate(value, andIsValid) {
      var confirmed = isObjectLike(value) && objToString.call(value) == dateTag;
      if (confirmed && andIsValid) {
        confirmed = isDate(value) && isFinite(value.getTime());
      }
      return confirmed;
    }
```
or create _.isDateValid
```
    function isDateValid(value) {
      return isDate(value) && isFinite(value.getTime());
    }
```
Just going through my personal library and seeing what I have and what might fit. ;)

**Comment by jdalton** [comment]
I'd like to stay away from date validation for the time being punting to more specialized libs like [moment.js](http://momentjs.com/).

**Comment by Xotic750** [comment]
I can appreciate that, not that I'd want to load a whole specialised date library to check a Date object is valid. This is really just a short cut for the long hand (lazy). ;)

**Comment by StreetStrider** [comment]
@Xotic750, well, you personally don't want to use specialized libs, I personally don't want LoDash contains stuff I'm not using :) (Date validation). Just put very simple `package.json` in your module, place it as a repo here on GitHub, then install it like a boss:
```
$ npm i Xotic750/date-module
```
You can even mix it in LoDash later in your code.

**Comment by Xotic750** [comment]
@StreetStrider Of course with any library you get stuff you're not using, but if I'm going to load one then I prefer to get one with all the things I use regularly, if possible. Anyway, I'm just floating some possibilities, I'm not expecting them to be adopted. ;)
