### ISSUE TITLE
Enhancement: _.isNegative and _.isPositive

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1550]
Detect if a number (object or literal) is positive or negative, including -0 and +0
```
function isPositive(value) {
  var result = false;
  if (_.isNumber(value)) {
    value = Number(value);
    if (value === 0) {
      result = 1 / value === Infinity;
    } else {
      result = value > 0;
    }
  }
  return result;
}
```
```
function isNegative(value) {
  var result = false;
  if (_isNumber(value)) {
    value = Number(value);
    if (value === 0) {
      result = 1 / value !== Infinity;
    } else {
      result = value < 0;
    }
  }
  return result;
}
```

**Comment by jdalton** [comment]
We'd want to follow ES6 [Math.sign](http://www.ecma-international.org/ecma-262/6.0/#sec-math.sign) here. I want to hold off and see what the demand for it is before adding though.

**Comment by Xotic750** [comment]
Ok, Math.sign would coerce anything and check whereas this is number specific.

**Comment by Xotic750** [comment]
So you would prefer more general like this
```
function isPositive(value) {
  value = Number(value);
  return Math.sign(value) ? value > 0 : 1 / value === Infinity;
}
```
```
function isNegative(value) {
  value = Number(value);
  return Math.sign(value) ? value < 0 : 1 / value !== Infinity;
}
```

**Comment by jdalton** [comment]
No, I was saying I'm more open to implementing something along the lines of `_.sign` instead of `_.isPositive` or `_.isNegative` but want to wait and see if there's demand.

**Comment by Xotic750** [comment]
Ok, so you are more open minded to something that returns -1 or 1 rather than -1, -0, 0 and 1
