### ISSUE TITLE
Enhancement: _.sort a stable sort algorithm

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1553]
Difference environments implement  different Array#sort algorithms, some of which are stable, some unstable  and some which are stable for certain array lengths. I would like a implementation that is known stable full stop. I have one coded in my personal library that I would be willing to convert for lodash if you are interested.

**Comment by d10** [comment]
`_.sortBy` and related methods already do a stable sort.

**Comment by Xotic750** [comment]
Really? It looks like it uses Array#sort and is environment dependant.
```
  function baseSortBy(array, comparer) {
    var length = array.length;

    array.sort(comparer);
    while (length--) {
      array[length] = array[length].value;
    }
    return array;
  }
```
What is being done to stabilise the Array#sort algorithm?

**Comment by jdalton** [comment]
@Xotic750 
The stable sort stuff is in `compareMultiple`, we have unit tests for it and everything.
Our `_.sortBy` is different than `sort`. I could see in the future making our `_#sort` stable too but it's a lower priority as it's covered in `sortBy`.

**Comment by Xotic750** [comment]
No problem. If I get bored then I may convert what I have and post it for future consideration or demand. ;)
