### ISSUE TITLE
Number.constrain method to Number section

### ISSUE THREAD

**Issue by Alexsey** [lodash/lodash#1554]
It would be nice to have with `.inRange` method `.constrain` (or any other name) with common behavior but Number as return value type:
```
function constrain (n, min, max) {
    if (arguments.length == 2) {
        max = min
        min = 0
    }
    if (n < min) 
        return min
    if (n > max) 
        return max
    return n
}
```
```
_.constrain(1, 2, 3) // 2
_.constrain(1, 0, 3) // 1
_.constrain(1, 4, 3) // 3
_.constrain(5, 10)   // 5
_.constrain(-1, 10)  // 0
```

**Comment by jdalton** [comment]
Hi @Alexsey! Just committed `_.clamp` [yesterday](https://github.com/lodash/lodash/blob/64e98d897f3a3312680b131839037060083ce8b3/lodash.js#L10918-L10932).

**Comment by Alexsey** [comment]
Super cool, thank you!
