### ISSUE TITLE
'where' behaves differently than underscore - in specific cases causes browser to hang (infinite loop?)

### ISSUE THREAD

**Issue by bjnsn** [lodash/lodash#1556]
In specific cases when used with Backbone.Relational I have found that using lodash rather than underscore causes the browser to hang indefinitely. My guess is that lodash is caught in a recursive infinite loop when iterating over model attributes that are themselves models.

The test cases are identical except for the loading of underscore/lodash. 

*To actually run the 'where' call you'll need to uncomment the final lines of the javascript.*
**In the lodash version, you'll need to force quit your browser, when the final lines uncommented.**

Underscore
http://jsfiddle.net/my6fvvrk/4/

Lodash
http://jsfiddle.net/my6fvvrk/5/

Note that this can readily be solved by switching out `where` on a per-use basis with a simple `filter` method that does the comparisons.

Thanks! I love lodash!

**Comment by jdalton** [comment]
If possible for future repros it'd rock to use something like [jsbin.com](https://jsbin.com) which doesn't hide away all parts of the repro and makes it easier to spot the important bits (version of Backbone used, JS snippets, repro setup).

For lib support try hitting up the [Backbone](https://gitter.im/jashkenas/backbone) or [Lodash](https://gitter.im/lodash/lodash) gitter rooms.

**Comment by jdalton** [comment]
If I remember correctly @jridgewell may have some experience with this issue. Justin, for context the repro tested is using the latest stable Lodash and Backbone.

**Comment by jridgewell** [comment]
It's going into an infinite loop in `isEqual` inside the matcher.

I think this is actually a valid bug with `_.matches`, where it can't tell if `source === source`, because we cloned the `source` to prevent later modifications to the matching function's behavior.

**Comment by jridgewell** [comment]
Oh, and `isEqual` probably shouldn't go into an infinite loop. :wink:

**Comment by jridgewell** [comment]
Ok. It's actually an issue with deeply cloned `source` used inside the matching function, and `isEqual`. Not sure where the fix is yet.

**Comment by jdalton** [comment]
We track visited objects so circular references shouldn't be an issue. @bjnsn can you try our master branch [lodash.js](https://github.com/lodash/lodash/blob/master/lodash.js).

**Comment by bjnsn** [comment]
@jdalton Its working in that version:

http://jsfiddle.net/my6fvvrk/7/

**Comment by jdalton** [comment]
Rock!
