### ISSUE TITLE
Lodash wrapper doesn't work properly

### ISSUE THREAD

**Issue by akwuh** [lodash/lodash#1557]
Hi.
I try to create lodash collection in this way:
```javascript
var x = _([]);
```
According to [the documentation](https://lodash.com/docs#_) Javascript Array's method `push()` is still available:
```javascript
x.push(2);
```
Actually, my created collection is still empty:
```javascript
console.log(x.toArray());
```
What am I doing wrong?
Thanks a bunch.

**Comment by jridgewell** [comment]
lodash wrappers are [lazy](https://lodash.com/docs#_) when they can be. You'll need to cap the chain with `#value` to execute the wrapper:

```js
var x = _([]);
x.push(1);
x.toArray().value(); // => [1]
```

**Comment by jdalton** [comment]
Just is close because it's in a chain sequence and each sequence can spawn new separate sequences you'll want to call `push` and use the returned wrapper to continue queuing actions on. You can see examples [in the 3.0 changelog](https://github.com/lodash/lodash/wiki/Changelog#v300).

```js
_([])
  .push(1)
  .toArray()
  .value(); // => [1]
```

**Comment by akwuh** [comment]
Thank you, guys. @jdalton @jridgewell then how can I create lodash Collection from my Array? I want to wrap an array in order to use `x.pluck(name)` instead of `_.pluck(x, name)`

**Comment by jridgewell** [comment]
```js
_([]).push({ x: 1 }).pluck('x').value(); // => [1]
```

**Comment by akwuh** [comment]
@jridgewell ok, please look at the example:
```javascript
var Test = {
	x: _([]),
	add: function(){
		this.x = this.x.push({"name": 2});
	},
	get: function(){
		return this.x.value();
	}
};
Test.add();
Test.get(); // [{"name": 2}]
Test.get(); // [{"name": 2}, {"name": 2}]
```
At the same time `get` method should be consistent.

**Comment by jdalton** [comment]
You may want to commit the actions in your sequence in `add`:
```js
this.x.push(...).commit();
```
It would return a new wrapper but also apply the modification since the wrapped value in both are the same you wouldn't need to assign the resulting wrapper to `this.x = ...`.

**Comment by akwuh** [comment]
@jdalton yes, thank you a lot. Really works.
