### ISSUE TITLE
Enhancement: _.uniqueId extended counter range

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1558]
I would guess that you haven't had any problems reported, but it is possible with a long running script that uses the function `_.uniqueId` often that it could hit the max safe integer value with the counter and would no longer generate unique values. This enhancement addresses that possible issue.
```
var idCounter = [0];

function uniqueId(prefix) {
  var result = [],
    length = idCounter.length,
    howMany = Math.max(length, 1),
    carry = 0,
    index = -1;
  while (++index < howMany || carry) {
    var zi = carry + (index < length ? idCounter[index] : 0) + !index;
    result.push(zi % 10);
    carry = Math.floor(zi / 10);
  }
  idCounter = result;
  return _.toString(prefix) + idCounter.join('');
}
```
http://jsfiddle.net/pjhk63jc/

**Comment by d10** [comment]
I think this is far too complicated a solution to what would be a very extreme edge case.

**Comment by Xotic750** [comment]
Complicated?

**Comment by jdalton** [comment]
There are lots of places in lodash that could hit theoretical limits such as our deep clone and equivalence methods but I've avoided tackling them until real world issues arise to keep things simple and reduce overhead.

**Comment by Xotic750** [comment]
Sure I understand that, if it should arise then at least you have a proposed solution. ;)
