### ISSUE TITLE
Enhancement: Development branch for non-breaking PRs?

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1561]
I was thinking that it would be nice if you had a development branch to allow PRs for non-breaking PRs, you know additions to the library that do not cause breaking change but are considered enhancements but wontfix currently, things that you want to see if they become popular/requested. That way contributions could be made that you could later merge into the master. Maybe it already exists somewhere and I just missed it.

**Comment by jdalton** [comment]
Hi @Xotic750! I don't want a lot of scraps and forgotten bits cluttering up things. Popular requests do bubble up pretty regularly there's no real need for an incubation branch.

**Comment by Xotic750** [comment]
I was wondering how this could be handled in my fork, I'd like to be able to add some stuff directly into it because it needs access to internal methods/variables but I don't like the idea of branching for every idea that I implement. I don't really see a nice way of doing it, and still be able to send you clean PRs if there is something that you would accept. Maybe my Git knowledge isn't great enough.

**Comment by jdalton** [comment]
It may take time but individual branches per pull request is ideal. As you've seen most of the time requests get a "let's wait and see" however some, like `_.clamp` and `_.toSafeInteger` get the go-ahead. Also to save yourself time you can always open an issue asking about a potential feature before putting in the effort of a PR.

**Comment by Xotic750** [comment]
Yeah. that's kind of what I've been doing, just floating the idea. But now I'd actually like to code some things up, even if just for my own use. I just couldn't see a painless way of doing it that would allow me to future submit them to you too. I guess I'll play and learn a little. :)

**Comment by StreetStrider** [comment]
@Xotic750, git-idea for you:
1. Fork LoDash.
2. add remote for «home» LoDash `git remote add home <jdalton's lodash/lodash>`
3. Do your feature-commits on the top of `master`.
4. When LoDash home updates — run `git fetch home; git pull --rebase home/master` on yours `master`.
5. Use your fork in `npm i my-lodash-fork`

When your changes will become incompatible with `home` you'll know :smile: 

Also, I was thinking that you might find interesting `lodash-contrib` project.

**Comment by Xotic750** [comment]
I had a little look at the project, a few interesting methods. My main interest has been improving the main lodash, as that is what I mostly want to use. But I've got nothing against any ideas being taken over to that project, don't think that I have the spare time just now to add proposals there too though. ;)
