### ISSUE TITLE
Enhancement to thru

### ISSUE THREAD

**Issue by AdamBrodzinski** [lodash/lodash#1563]
I've made a new function for lo-dash and thought i'd share it here in case it's something you might be interested in. If anything it might make sense to enhance `thru` as it's essentially the same but takes additional arguments and passes them to the function. More than happy to PR if it's not bloat.

The main feature is that you can use a normal function without having to use `mixin` for each one. In this example it's named `call`.

```javascript
_.chain("555 1212-3232")
  .call(removeChars, '-', ' ')
  .call(removeChar, '+')
  .value();
```

In ES6 it looks like this (more verbose in ES5 of course)
```javascript
function pipesCall(firstParam, func, ...restParams) {
  func(firstParam, ...restParams);
}
```

I ended up using this to implement Elm/Elixir/F# style pipes for a new compile-to JS language that's utilizing Lo-Dash in case you're curious: [RedScript pipes] (https://github.com/AdamBrodzinski/RedScript#think-in-pipes-instead-of-nesting-functions),  &  [RedScript LoDash support](https://github.com/AdamBrodzinski/RedScript#built-in-support-for-lo-dash)

**Comment by jdalton** [comment]
Hi @AdamBrodzinski! Thanks for sharing your mixin idea. I want to avoid naming something `.call` as that shadows `Function#call`. In this case if you're using ES6 I don't see much benefit over `thru` + arrow functions.
