### ISSUE TITLE
Enhancement: Extend parseInt to handle binary and octal string literals.

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1575]
Although not specified in ES6, both Number() and the ternary + now support them. It seems logical, and would be a nice feature for parseInt to also support them. Linked to https://github.com/lodash/lodash/issues/1574

**Comment by jdalton** [comment]
Our `parseInt` is really just a shim for older buggy environments. With lodash v4 dropping older environment support though I could see removing the method.

**Comment by Xotic750** [comment]
Fair enough. especially if you are intending to drop it, toNumber would handle it anyway.

**Comment by jdalton** [comment]
Actually I checked and Node 0.10.0 still has a buggy implementation so I'll probably keep the method around.

**Comment by Xotic750** [comment]
It would be a fairly simple mod, especially if you are taking some of those other enhancements. Just shout if you feel you want it. ;)

**Comment by jdalton** [comment]
> Just shout if you feel you want it. ;)

Cool, not at the moment. It's not a very popular method so not worth sinking any more source or effort into at the moment.
