### ISSUE TITLE
No method for testing if var is integer

### ISSUE THREAD

**Issue by scmorse** [lodash/lodash#1578]
`_.isNumber` exists, but there isn't a test for just integers, with no decimal value.

Ex. 

```
_.isInt = function(n) {
  return _.isNumber(n) && n % 1 === 0;
};
```

https://github.com/lodash/lodash/issues/1020 Says that it was added, but it's not in the docs (https://lodash.com/docs).

**Comment by jdalton** [comment]
Hi @scmorse! It's in our edge master branch, not released yet.
