### ISSUE TITLE
_.pluck's path cannot be an array. Documentation correction

### ISSUE THREAD

**Issue by ranadeep47** [lodash/lodash#1579]
According to documentation, `path` in `_.pluck` can be an array, but in code i find it can only accept a string which is a key of one of the objects in the collection, or am i missing something ?

**Comment by ranadeep47** [comment]
Also it would be great if can be an array, currently im doing something like this
`arr.map(function(obj) { _.pick(obj, fields) })` where `fields` is any array

**Comment by jdalton** [comment]
Make sure you're using a newish version of lodash as it does support a [property path as an array](https://github.com/lodash/lodash/blob/3.10.1/lodash.src.js#L6956-L6958) and `_.pick` accepts and array of fields already. Two for two on this one :P
