### ISSUE TITLE
Null-conditional Operators - call method if object is non-null

### ISSUE THREAD

**Issue by mbana** [lodash/lodash#1581]
Hi All, to avoid having to always do:

```javascript
if (object_x != null) {
object_x.destroy();
}
```

I instead do:

```javascript
 _.invoke([object_x], 'destroy');
```

C# has something similar, see https://msdn.microsoft.com/en-us/library/dn986595.aspx:

```
PropertyChanged?.Invoke(e)
```

***

I have yet to run performance tests to see if this is feasible, however just looking at path the code could potentially take in `_.invoke` it seems, I am guessing now, that this might not be optimal.

Is there a better way and less costly way of doing this?

**Comment by megawac** [comment]
Why do you want to avoid a null check so badly. I'd say the first method is more optimal

**Comment by jdalton** [comment]
Avoiding nullish checks is pretty nice feature of lodash :D
On the api front @megawac right there's [_.result](https://lodash.com/docs#result).
Internally we have `invokePath` which I might expose.

**Comment by mbana** [comment]
I take it you enjoy writing `null` checks? I certainly don't.
I can't imagine the amount of times that I've had to type this out. It becomes annoying, especially since it's repetitive and boring.

I just looked at `_.result` and likewise the method is similarly complicated.

**Comment by mbana** [comment]
Can I kindly ask why this was closed?

**Comment by jdalton** [comment]
There's nothing left to say really.
