### ISSUE TITLE
Enhancement: fix _.range extra item when using floats

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1585]
In https://github.com/lodash/lodash/pull/1541#issuecomment-149766371 @exogen mentions:
>I'm not concerned with intermediate inexact terms – like 5/3 != 5 * (1/3) – that seems unavoidable whether we sum or multiply, even with error correction. But rather what that leads to: we've picked up an extra result – intuitively there should be 7 items, not 8. It's because of n, which after calculating (7/3) / (1/3) to be 7.000000000000001 and running ceil on that, tells us we should produce 8 results.

I think a simple fix would be:
```
    var n = nativeMax(nativeCeil((end - start) / (step || 1)), 0);
    var result = _.times(n, function (index) {
        return index ? (start += step) : start;
    });
    if (result.slice(-1) >= end) {
        result.pop();
    }
    return result;
```
http://jsfiddle.net/ccrkom2f/1/

I don't there are ever any situations where you'd expect >= end, and I don't think there are any situations where this would fail.

**Comment by jdalton** [comment]
I'm fine punting on this for now.

**Comment by Xotic750** [comment]
:) Floating point range creation is a tricky one, even when using a specialised library.
