### ISSUE TITLE
_.some(collection, array) support ?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [lodash/lodash#1586]
I just see that parameter 2 supports Function|Object|string

Thinking of such a use case:

    var selectedTags = ['a', 'b'];
    var items = [
        {
            id: 0,
            tags: []
        },
        {
            id: 1,
            tags: ['a', 'x', 'y']
        },
        {
            id: 2,
            tags: ['b', 't', 'u']
        },
        {
            id: 3,
            tags: ['a', 'b']
        },
        {
            id: 4,
            tags: ['t', 'u']
        }
    ];

So `_.filter(items, function(item){ return _.some(item.tags, selectedTags); });` would return item 1,2,3, but not 0,4.

**Comment by jdalton** [comment]
You can use `_.difference(array, itemsToExclude)`.
