### ISSUE TITLE
Object.prototype properties conflict with `_.defaults`

### ISSUE THREAD

**Issue by qbolec** [lodash/lodash#1588]
I've recently reported this as [an issue in Backbone.js](https://github.com/jashkenas/backbone/issues/3842), but the more I dive in the code the more I think this is actually an issue with lodash.
Consider this simple code:
```
_.defaults({},{watch:true})
```
When executed in Chrome, it returns: `Object {watch: true}` 
When executed in Firefox, it returns: `Object {  }`.
In particular, Firefox reports that  `typeof _.defaults({},{watch:true}).watch` is `"function"`, as the native Object has a method `watch`.

I can see that this is somewhat consistent with other Object.prototype 'magic' functions - for example
```
_.defaults({},{valueOf:true})
```
gives an "empty" object in both Chrome and Firefox.

I think this implementation is not intentional, not intuitive and rarely beneficial to the developer.
My guess is that there is some (unintended?) asymmetry in how arguments of _.defaults are treated, namely that propertyIsEnumerable is not checked for the first argument, but is (implicitly) checked for the others (as the for..in loop extracts only fields which are enumerable).
It looks like the code is iterating over fields of the second argument, (and this is good, and this is why `watch` is considered for merging at all), but then lodash sees that field `watch` is not `undefined` in the first object, so it doesn't override it - I think that this condition should be strengthened to not only being defined, but also being enumerable (in the sense of belonging to the result of `keys()` just as it is required for the second argument).

This issue causes some problems which are difficult to predict in advance - an app which worked just find a few months back, now is completely broken for Firefox users, simply because they added `watch` to the prototype of Object, and now this name is "troublesome".

**Comment by gibson042** [comment]
This behavior is [documented](https://lodash.com/docs#defaults) ("…for all destination properties that resolve to `undefined`"), but can be worked around. Modern environments let you replace `{…}` with `Object.create(null, {…})`, and replacing `_.defaults(obj, …)` with `_.defaults(_.toPlainObject(obj), …)` should work everywhere (but is slightly less accurate).

**Comment by jdalton** [comment]
The solutions for this get a pick hacky and not balanced. For example I could check if the value matches those on `Object.prototype` but there's no inheritance walk so it might be an intermediate object value in the prototype chain. I could check for enumerability but that's kind of an odd restriction for an existence check.

Lodash's `_.assign` is customizable:
```js
var defaults = _.partialRight(_.assign, function(objValue, srcValue, key) {
  return (objValue === void 0 || objValue === Object.prototype[key])
    ? srcValue
    : objValue;
})
```

In lodash v4 this:
```js
var defaults = _.partialRight(_.extendWith, function(objValue, srcValue, key) {
  return (objValue === void 0 || objValue === Object.prototype[key])
    ? srcValue
    : objValue;
})
```

which would solve the issue.
