### ISSUE TITLE
Lazy evaluation on lodash 3.10.1 

### ISSUE THREAD

**Issue by DiegoCardoso** [lodash/lodash#1593]
First, sorry if this is not the right place to make this kind of question.

When I was trying the library on JSBin, I tried to see the lazy evaluation in action by adding some `console.log()` inside the functions. Then, I downloaded the current version (3.10.1), expecting the same behavior. But that wasn't what happened. I realized that JSBin was actually using 3.0.1 version and I, in the other hand, am using the current version of the library. I've searched if there was any configuration or change that was made from the last versions to the current one, but I couldn't find any help.

So, here is my tests:

```
_(_.range(10)).filter((x) => {
  console.log('FILTER: ' + x);
  return x % 2;
}).map((x) => {
  console.log('MAP: ' + x);            
  return x * 2;
}).value();
```

3.0.1 output:

```
"FILTER: 0"
"FILTER: 1"
"MAP: 1"
"FILTER: 2"
"FILTER: 3"
"MAP: 3"
"FILTER: 4"
"FILTER: 5"
"MAP: 5"
"FILTER: 6"
"FILTER: 7"
"MAP: 7"
"FILTER: 8"
"FILTER: 9"
"MAP: 9"
```

3.10.1 output:

```
"FILTER: 0"
"FILTER: 1"
"FILTER: 2"
"FILTER: 3"
"FILTER: 4"
"FILTER: 5"
"FILTER: 6"
"FILTER: 7"
"FILTER: 8"
"FILTER: 9"
"MAP: 1"
"MAP: 3"
"MAP: 5"
"MAP: 7"
"MAP: 9"
```

**Comment by jdalton** [comment]
In later versions of lodash I adjusted the heuristic to kick in on arrays larger than 200 because shortcut fusion disables method inlining (an implementation detail).

**Comment by gibson042** [comment]
How much is that optimization actually buying? Iteration over small lists tends to be fast no matter what, and size-based behavior changes can be frustrating (e.g., this is analogous to Chrome's `sort` (in)stability).

**Comment by jdalton** [comment]
> How much is that optimization actually buying?

Potentially lots where shortcut fusion is concerned. Instead of something being 40,000 iterations it could be something like 8.

> and size-based behavior changes can be frustrating (e.g., this is analogous to Chrome's sort (in)stability).

The difference is ours has heuristics in place to avoid causing issues with callbacks expecting the traditional behavior. So the perf gains without the headaches.

**Comment by gibson042** [comment]
I think you misunderstood my question. I was asking about how much the _small array exemption_ buys you over always using the current "large array" logic, given that inefficient iteration over small arrays generally isn't a problem (e.g., even bubble sort looks good for small N).

> > and size-based behavior changes can be frustrating (e.g., this is analogous to Chrome's sort (in)stability).

> The difference is ours has heuristics in place to avoid causing issues with callbacks expecting the traditional behavior. So the perf gains without the headaches.

I think this issue and those it duplicates are evidence to the contrary—the headaches come from observing behavior that diverges from public claims (and from large-scale load) during small-scale experimentation.

**Comment by jdalton** [comment]
Naw, this issue is those trying to sniff it out and not with real code. To my knowledge real code hasn't hit an issue. This can be addressed with documentation.

**Comment by jdalton** [comment]
I'll document the heuristic here to transfer to inline docs in a bit.

Portions of a chain sequence may qualify for lazy evaluation if the original value or intermediate values are arrays. Any iteratees or predicates provided must accept 1 argumen, and the array should at least 200 elements in length.

**Comment by jdalton** [comment]
Doc note added https://github.com/lodash/lodash/commit/ee9339e73b93dfc564bbd2275f26bf8aeb36f450.
