### ISSUE TITLE
_.has returning false even though property is there.

### ISSUE THREAD

**Issue by Gacnt** [lodash/lodash#1595]
Hi guys just trying to simplify some workflow by implementing `lodash`

I have an object, we'll simplify it as:
```
    {
    
        session:  {
    
          passport: {
    
            user: 5
    
          }
    
      }
    }
```
so we'll say `var req;` is that object now if I go

`_.has(req, 'session.passport.user');` 
it returns `false`

but if I do `req.hasOwnProperty()` on each individual part it eventually returns true with `req.session.passport.hasOwnProperty('user');`

so I'm just curious as to what I'm doing wrong, I'm using the latest version of lodash. Thanks!

I even explicitly copied the example on `_.has` in the lodash documentation and it still returned false so I'm curious as to what I'm doing wrong, I'm using the latest version of lodash. Thanks!

This is on `node` using `SailsJs`, I've tried deleting my` node_modules` folder and reinstalling

**Comment by Xotic750** [comment]
What version of node? I tried it with lodash 3.10.1 on chromium 45.0.2454.99 and it worked.
http://jsfiddle.net/st6x3rfd/

**Comment by Gacnt** [comment]
I guess it was an issue with the SailsJS config,

it comes prepackaged with its own version (2.4.1) of lodash which is included globally for your app,

updating lodash to 3.10.1 and requiring it in the file that I needed to use it in seemed to fix the issue.

**Comment by jdalton** [comment]
Rock, yep deep property access was not available in 2.x.
