### ISSUE TITLE
Question: ufeff or ufffe in tests?

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1597]
In the tests there is 
```
      // Zero-width space (zws), next line character (nel), and non-character (bom) are not whitespace.
      var problemChars = '\x85\u200b\ufffe',
```
but should it read?
```
      var problemChars = '\x85\u200b\ufeff',
```
just curious about what it is actually testing.
> In UTF-16, a BOM (U+FEFF) may be placed as the first character of a file or character stream to indicate the endianness (byte order) of all the 16-bit code units of the file or stream. If an attempt is made to read this stream with the wrong endianess, the bytes will be swapped, thus delivering the character U+FFFE, which is defined by Unicode as a "non character" that should never appear in the text.

https://en.wikipedia.org/wiki/Byte_order_mark#UTF-16

**Comment by jdalton** [comment]
It's to ensure we don't regress if we ever adopt built-in `String#trim`.

**Comment by Xotic750** [comment]
Was there a known issue in some environment with `ufffe`? I never heard anything about it?

**Comment by jdalton** [comment]
See https://github.com/es-shims/es5-shim/issues/219.

**Comment by Xotic750** [comment]
Excellent, thanks. I'd never heard of that issue with Opera.
