### ISSUE TITLE
Feature request: function _.isBlank() for all types

### ISSUE THREAD

**Issue by melnikaite** [lodash/lodash#1600]
Function `_.isEmpty` works only for `object`, `array`, `string`, or jQuery-like collection. I faced situation when I had to check if passed value is not empty, however I got `true` for `integer`, `boolean`, `date`, `regexp`, `function`, `infinity`. I know that I can check type of value before using `_.isBlank`, but I'd like something more compact. In addition `date` can be invalid and I have to also check `_.isNaN((new Date('')).getDate())`

**Comment by Xotic750** [comment]
A related query regarding Date https://github.com/lodash/lodash/issues/1546

**Comment by d10** [comment]
`_.isEmpty` is used for collections, i.e. arrays, array-like-objects and objects. For other types, you can probably just check `value != null` too ensure that a value is not `null` or `undefined`.

**Comment by melnikaite** [comment]
Unfortunately I can't without checking type (`!false`, `!0`), such additional type checks makes conditions in application hard readable

**Comment by jdalton** [comment]
Hi @melnikaite! Date validation gets into more of the area of [moment.js](http://momentjs.com/).
For falsey values a method could be composed as:
```js
var isFalsey = _.negate(Boolean);
```

**Comment by melnikaite** [comment]
Ok guys, I see your point
Anyways for those who still looking for `_.isEmpty` for all types:
```
_.mixin({
  'isValuable' : function(value) {
    switch (true) {
     case _.isDate(value):
	  return !_.isNaN(value.getDate());
      break;
     case _.isError(value):
     case _.isNaN(value):
	  return false;
      break;
     case _.isFunction(value):
     case _.isBoolean(value):
     case _.isNumber(value):
     case _.isRegExp(value):
	  return true;
      break;
     default:
	  return !_.isEmpty(value);
      break;
    }
  }
});
```

**Comment by StreetStrider** [comment]
@melnikaite, you might be interested in checking [is.js](http://arasatasaygin.github.io/is.js/).
I'm not using it personally, but if I would like to determine types widely I would prefer it over Underscore/LoDash. However, I cannot find `isEmpty` there though :laughing:, looks like libs don't implement one since any single person has it's own opinion on what should be considered as «empty» :)
