### ISSUE TITLE
Enhancement: Identify implicit type conversions that would benefit from `toNumber` consistency

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1602]
An example may be
```
    function baseRandom(min, max) {
      return min + nativeFloor(nativeRandom() * (max - min + 1));
    }
```
as
```
    function baseRandom(min, max) {
      min = toNumber(min);
      max = toNumber(max);
      return min + nativeFloor(nativeRandom() * (max - min + 1));
    }
```
(Ok, `baseRandom` is an internal, it is just an example of meaning.)
therefore type conversion becomes more consistent (are not left to environmental chance) and benefit from the ES6 like string conversions implemented in `toNumber`.

**Comment by jdalton** [comment]
The base methods is not the place for type coercion as they should already have the correct type of value passed to it.

**Comment by Xotic750** [comment]
I agree. But if you would like, then I'd be willing to look through and submit individual PRs for approval.

**Comment by jdalton** [comment]
Let's work through where it would be needed here and take it out in 1 PR.

**Comment by Xotic750** [comment]
Ok, I'll begin making a list of possible candidates.

**Comment by Xotic750** [comment]
I haven't gone very far yet but what I have noticed so far is that `baseSlice` and `baseFill` are performing type conversion rather than the methods that are using them.

**Comment by Xotic750** [comment]
These are potential candidates for `toNumber`
createRound
clamp
inRange
random
range
add
sum
sumBy
(baseSum - but it was agreed base isn't the correct place)

I also saw areas where I thought, `toInteger` seems appropriate here, or `toSafeInteger` or `toLength` seem more appropriate there. Just a small selection of examples may be.

debounce
delay
throttle

 The other 2 major areas that seemed strange to me were (as mentioned) `baseSlice` and `baseFill`.

**Comment by jdalton** [comment]
> createRound
clamp
inRange
random
range
add
sum
sumBy

Yes, `_.toNumber`!

> debounce
delay
throttle

Yes, `_.toInteger`!

>  baseFill

Lets move the `toInteger` use to `fill`.

Lets not touch `baseSlice` yet.

**Comment by Xotic750** [comment]
Ok, I'll start working my way through them.

**Comment by Xotic750** [comment]
I'm a little unsure about the intention with the method `add`, as the docs state
>      * @param {number} augend The first number to add.
     * @param {number} addend The second number to add.
     * @returns {number} Returns the sum.

But the code and the tests show something altogether different.

If the logic is to remain the same then we need to perform checks to see if strings are binary, octal or hexadecimal. So I feel the intention needs to be clarified, my guess is that you want the logic to remain and additional checks to be performed?

**Comment by jdalton** [comment]
Ah yes, don't worry about `add` or `sum` methods. No coercion needs to happen. I want an undocumented case of concatenation with `add` for a bit to test the waters.

**Comment by Xotic750** [comment]
Is there any use for `baseFill`, it's only used by `fill`?

**Comment by jdalton** [comment]
Not at the moment, I want to keep it base though.

**Comment by Xotic750** [comment]
Looking a little closer at it, then I'm thinking that it is best as is it is. I see a couple of possible improvements that I'll send in and you can see what you think. Otherwise I think this review is done.
