### ISSUE TITLE
Enhancement: isFunction( v ) ? v( v, ...args ) : v

### ISSUE THREAD

**Issue by Centril** [lodash/lodash#1603]
(I apologize if this has already been suggested, I couldn't find it in any issue tho...)

## What?

I propose a quite simple addition to lodash, a function that if given a function, calls it with any other arguments, or if given a value, simply returns that value.

## In code:

```js
/**
 * Returns the value of v called with any additional arguments if _.isFunction(v) holds,
 * otherwise it returns v.
 *
 * @param {*|Function} v  A value, or a function.
 * @param {...*}  args  Any other arguments.
 * @return {*}  v or v(...args).
 */
_.voc = (v, ...args) => isFunction(v) ? v(v, ...args) : v;
```

Perhaps an addition to this could be to bind `this`, but I think this plays bad with `args`.

## Naming

Here are some naming ideas:

+ `voc` (`value` or `call`)
+ `voi` (`value` or `invoke`)
+ `invokeIf`
+ `val`
+ `value`

**Comment by Centril** [comment]
I think this has plenty of use cases, so why `wontfix`?

**Comment by jdalton** [comment]
Thanks @Centril! You beat me to my reply.

I want to hold off until there's strong enough user demand for such a method. Until then you can totally add this as a `_.mixin`.

**Comment by StreetStrider** [comment]
Looks similar to [result](https://lodash.com/docs#result), but not the same. I also remembering some people wanted to pass arguments to `result`, have been wantfixd too.

**Comment by Jokero** [comment]
+1 for this. Custom implementations are used in some popular projects (for example, https://github.com/ansman/validate.js/blob/master/validate.js#L248)

**Comment by jdalton** [comment]
Lodash v4 will address this partially with a repurposed `_.invoke` method.
```js
_.invoke(object, 'a.b.c', arg0, arg1, arg2);
```

**Comment by Jokero** [comment]
Path is not always necessary

**Comment by jdalton** [comment]
> Path is not always necessary

I said partially address you Joker.

**Comment by just-boris** [comment]
Also got a use case for this. I have an object that formats string according to some `type`.

Currently, I solved this with `_.invoke` and using `_.constant` for static values

```js
const formatDisplayValue = {
  person: (object) => `${object.firstName} ${object.lastName}`,
  post: (object) => `${object.title}`,
  comment: _.constant('Constant')
};

_.invoke(formatDisplayValue, type, object);
```

But when you have only one or two functions and all other are constant, it seems like a bit overhead, that could be solved by proposed helper function.

**Comment by StreetStrider** [comment]
@just-boris, well `formatDisplayValue` is overhead itself. It should be implemented as polymorphic method on the side of the formatted objects, which will allow to throw out this hashmap and not to bother actualizing it any time you implement new `type`.

**Comment by just-boris** [comment]
@StreetStrider This is kind of off-topic, but my data are plain javascript object. This is okay for typical React+Redux projects, so I have solved my issue with the mentioned code put in some of React components.

**Comment by StreetStrider** [comment]
@just-boris, OK. I agree this is offtopic. I'm not offending but I want to mention that this is the main scenario — people have loose types and POD or over the place and then wanna push to LoDash weird things like deep pickers, deep omitters, recursive walking, i.e. things which can be solved as a simple composition of picks/omits/finds/filters in corresponding objects (as a methods of well-constructed types).
