### ISSUE TITLE
On Safari - _.keys does not work but Object.keys does

### ISSUE THREAD

**Issue by optikalefx** [lodash/lodash#1614]
_.keys gives way more key data, often incorrect, compared to Object.keys. Doing a phonegap app using lodash proved this to be a very big issue.

**Comment by Xotic750** [comment]
Which version of lodash and Safari? Do you have an example of the issue?

**Comment by jdalton** [comment]
Our `_.keys` uses `Object.keys` under the hood. In v4 we drop many of the older environment fixes around it, clearing up any extra keys provided.

**Comment by optikalefx** [comment]
We were using lodash v 3.10.1 Safari 9.0.1 to debug and mobile safari on iOS 9.1 as the engine behind the phonegap app. If it's fixed in v4. Great
