### ISSUE TITLE
_.set does not work correctly when a path component is a number

### ISSUE THREAD

**Issue by CensoredUser** [lodash/lodash#1616]
**Problem**
When a path component used in the `_.set` method contains a number, lodash will incorrectly create an array of that size. 

**Steps to reproduce**

```javascript
var bla = {
  test: "ok",
  200: "ok"
};

console.log(_.get(bla, '200', 'fail'));
console.log(_.get(bla, 'test', 'fail'));

_.set(bla, 'bla.200.bla', 'wow');

console.log(_.get(bla, 'test.200', 'fail'));
console.log(bla);
```

**Expected result**

```json
{
  "test": "ok",
  "200": "ok",
  "bla": {
    "200": {
      "bla": "wow"
    }  
  }
};
```

**Actual result**

```json
{
   "200":"ok",
   "test":"ok",
   "bla":[
      null,
      null,
      ... [198 more nulls]
      {
         "bla":"wow"
      }
   ]
}
```

**Comment by Xotic750** [comment]
I tried with lodash v3.10.1 and with the trunk and got your expected result. Which version of lodash?

**Comment by CensoredUser** [comment]
I was using v3.10.1 - here's an example: http://codepen.io/anon/pen/zvLgre

**Comment by Xotic750** [comment]
So, your problem is actually with `JSON.stringify` and not `lodash`. You could use a custom `replacer` to alter the behaviour of `JSON.stringify`

**Comment by CensoredUser** [comment]
Ah right. Doh! Can confirm JSON.stringify is the problem. 
I was put off my Chrome's Dev Tools also showing `bla.bla` as an `Array[201]`. Thanks for the quick resolution!

**Comment by CensoredUser** [comment]
Actually, the problem was _not_ `JSON.stringify`. The issue was that the 'object' that was to be the parent node of the object with a numerical key did not exist yet. 

For example the following will work just fine: 

```javascript
var bla = { 'test': {} };
_.set(bla, 'test.200.bla', {}); // Will produce { 'test': { '200': { 'bla': {}}}}
```

However this won't:

```javascript
var bla = {};
_.set(bla, 'test.200.bla', {}); // Will produce { 'test': [ 200: { 'bla': {}}]} , where 200 is an index
```

So it _does_ seem like a bug in lodash.

**Comment by koulmomo** [comment]
I think this is a dupe of: https://github.com/lodash/lodash/issues/1359

**Comment by CensoredUser** [comment]
Ah indeed it is. Thanks @koulmomo.
Closing this as dupe of #1359
