### ISSUE TITLE
Problem with _.difference

### ISSUE THREAD

**Issue by dengyaolong** [lodash/lodash#1617]
I want to the set difference arrayA - arrayB , but when the arrayA include array, it does not work.
e.g
```
console.log(_.difference([[1]],[[1]]));
// -> [[1]] ,not []
```
I see samevalueszero <http://ecma-international.org/ecma-262/6.0/#sec-samevaluezero>
seems like `Return true if x and y are the same Object value. Otherwise, return false.`
We alwasy compare two arrays use Array.toString() and compare the string
```
var arrayA = [1], arrayB = [1];
arrayA.toString() === arrayB.toString() // true
arrayA == arrayB //false;
```
How can i get the difference in that times?

**Comment by Xotic750** [comment]
Do you actually want the difference or to compare two objects for equivalence?

**Comment by jdalton** [comment]
This is coming in v4 as `_.differenceWith(array, other, _.isEqual)`.
