### ISSUE TITLE
_.find doesnt return truthy results

### ISSUE THREAD

**Issue by bobmoff** [lodash/lodash#1618]
The documentation states "returning the first element predicate returns truthy for".

Using the example in the docs with this array:

```javascript
var users = [
  { 'user': 'barney',  'age': 36, 'active': true },
  { 'user': 'fred',    'age': 40, 'active': false },
  { 'user': 'pebbles', 'age': 1,  'active': true }
];
```

using find like below, returns undefined, but should return the pebbles object.

```javascript
_.find(users, { age: '1' })
```

Maybe I am totally wrong about what truthy means, but isnt that when the code below returns true ? 

```javascript
'1' == 1
```

**Comment by jdalton** [comment]
Passing the object `{ 'age': '1' }` creates a predicate as if by using `_.matches`. This performs a partial deep equality comparison as if by `_.isEqual` which means the number `1` and string `'1'` are seen as different values so the predicate fails the match and returns `false`.
