### ISSUE TITLE
Any interest in Haskell's iterate?

### ISSUE THREAD

**Issue by chocolateboy** [lodash/lodash#1622]
lodash is only an `iterate` away from supporting an [elegant implementation](http://neilmitchell.blogspot.com/2012/01/pascals-triangle-in-haskell.html) of [Pascal's Triangle](https://en.wikipedia.org/wiki/Pascal's_triangle) (which, apparently, is a [common interview question](https://www.reddit.com/r/javascript/comments/3rb88w/ten_questions_ive_been_asked_most_more_than_once/)):

```javascript
import _ from 'lodash';

function nextRow (row) {
    return _.zipWith([ 0, ...row ], [ ...row, 0 ], _.add);
}

function pascal (rows) {
    return (rows === 0) ? [] : _.iterate(rows, [ 1 ], nextRow);
}  
   
let rows = parseInt(process.argv[2]) || 6;

console.log(pascal(rows));
```

It's useful for other things as well, of course. It encapsulates the concept of generating a list by repeatedly applying a function to the previous value in the same way that `reduce` encapsulates the concept of reducing a list by repeatedly applying a function to the next value.

Happy to submit a PR if there's any interest.

**Comment by jdalton** [comment]
Hi @chocolateboy!

I'm not entirely sure what this method produces can you produce output of the logged `pascal(rows)`.
As with other requests I tend to hold off of inclusion in core until there's a bit stronger user demand though requesting it is the first step :D

**Comment by chocolateboy** [comment]
`iterate` produces an array with the initial value as the first value, the result of calling the function on that value as the second value, the result of calling the function on the second value as the third value &c.

So `iterate(4, value, fn)` is equivalent to `fn(fn(fn(fn(value))))`.

```javascript
function iterate (_count, value, fn, _this) {
    let count = _count - 1;
    let results = [ value ];

    while (count--) {
        results.push(value = fn.call(_this, value));
    }

    return results;
}
```

In the Pascal Triangle example:

1. the initial value is `[1]`
2. `nextRow([1])` returns `[1, 1]`
3. `nextRow([1, 1])` returns `[ 1, 2, 1 ]`
4. `nextRow([ 1, 2, 1 ])` returns `[ 1, 3, 3, 1 ]`
5. `nextRow([ 1, 3, 3, 1 ])` returns `[ 1, 4, 6, 4, 1 ]`
6. `nextRow([ 1, 4, 6, 4, 1 ])` returns `[ 1, 5, 10, 10, 5, 1 ]`

`iterate` returns:

```
[ [ 1 ],
  [ 1, 1 ],
  [ 1, 2, 1 ],
  [ 1, 3, 3, 1 ],
  [ 1, 4, 6, 4, 1 ],
  [ 1, 5, 10, 10, 5, 1 ] ]
```

**Comment by chocolateboy** [comment]
> As with other requests I tend to hold off of inclusion in core until there's a bit stronger user demand

This is from the same prelude as [`zipWith`](https://github.com/lodash/lodash/issues/1128) :-)

**Comment by StreetStrider** [comment]
I will glad to see this in LoDash. This thing is as fundamental as `reduce`. I remembering implementing this myself; remembering this looked like terrible `reduce` with terrible running state in reduce's accumulator :smile:
