### ISSUE TITLE
_.transform() in wrong category?

### ISSUE THREAD

**Issue by NicBright** [lodash/lodash#1623]
Hi there,

I'm not really sure if _.transform() is correctly categorized as a "object" function. In my understanding, if it were truly an "object" only function, then transforming an Array should not work as it does (which is great btw):

See e.g.:
```
var myArr = [2, 3, 4];
myArr.test = 5;

_.transform(myArr, function(result, n) {
  result.push(n *= n);
});
// [4, 9, 16] // 25 missing here!

_.forOwn(myArr, function(value, key) { console.log(key); })
// 0
// 1
// 2
// test

```

As one can see, _.transform() "correctly" iterates `myArr` as an Array. But if _.transform() was object only, then it should have iterated over myArr similiar to _.forOwn(), shouldn't it?

### Conclusion
Shouldn't _.transform() rather be categorized as a 'collection' function?

**Comment by jdalton** [comment]
This is by design. Its not a collection category because it doesn't prioritize array-like over object.

**Comment by NicBright** [comment]
Ok I understand this point. But there still seems to be a slight flaw when looking at the docs:

> "An alternative to _.reduce; this method transforms object to a new accumulator object which is the result of running **each of its own enumerable properties** through iteratee, with each invocation potentially mutating the accumulator object" 

According to this, `myArr` in my example should have printed `25` as well. So I agree, _.transform() is not a collection function, but then it's not an object function either.

**Comment by jdalton** [comment]
It fits enough because it'll use `Object.create()` for other values passed to it so it's more Object category than Collection category.

**Comment by NicBright** [comment]
That seems right but this point is missing from the docs. Imho, it should explicitly tell what type the accumulator will be. Also, it should be mentioned that Arrays are iterated over like Arrays. 

Maybe this will do?

```
    /**
     * An alternative to `_.reduce`; this method transforms `object` to a new
     * `accumulator` object which is the result of running each of its own enumerable
     * properties through `iteratee`, with each invocation potentially mutating
     * the `accumulator` object. The `iteratee` is bound to `thisArg` and invoked
     * with four arguments: (accumulator, value, key, object). Iteratee functions
     * may exit iteration early by explicitly returning `false`.
     *
     * If `object` is an Array, it is actually treated as an Array (i.e. it is not iterated over 
     * the own enumerable properties). 
     * 
     * If no custom accumulator is passed, you will get a new object of the same 
     * type as `object` (including the same prototype chain) if possible. As a fallback,
     * an empty Object {} is passed.
     *
     * @static
......
```

Besides that, I'm curious why you've decided to make it not prioritize array-like over object?

**Comment by jdalton** [comment]
Hey @NicBright! Sorry the documentation isn't to your liking. TBH I'm not really feeling this discussion so I'll probably not engage too much.  I may scale back on `_.transform` in v4 as it does do a bit more than other object methods. I'll kick it around a bit.

**Comment by NicBright** [comment]
That's OK with me :-). Thanks for the always very quick responses. That's what counts most.
