### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined at runInContext with stripe module

### ISSUE THREAD

**Issue by Aishwarya-K** [lodash/lodash#1624]
I am integrating Stripe Api and Authorize.net Api as payment gateways in a Nodejs Web platform. Both of the module use Bluebird library and Lodash Js . While i run the code with correct api key/Secret key infos I am getting error

>TypeError: Cannot read property 'prototype' of undefined at runInContext on (../node_modules/stripe/node_modules/lodash/index.js)
After some research, I have found a solution by adding 

``` if (typeof context.Object !== 'function') context = this; ```

But after adding this, another error is generated.

>An error occurred : Cannot read property 'call' of undefined

My current version of nodejs is v4.2.1. The Api keys/ and secret infos is correct, I am not sure what the problem is. Does anyone have any ideas?

**Comment by jdalton** [comment]
Hi @Aishwarya-K!

I have more questions :D

* What version of lodash is stripe depending on?
* Are you using `runInContext` explicitly?
* Are you using lodash in the `vm` module?

**Comment by Aishwarya-K** [comment]
Hi @jdalton 
1) Lodash Version : 3.10.1.
2) No I am not using runInContext explicitly. 
3) I am not using vm module

I am using this  [Authorize.net](https://github.com/continuous-software/node-authorize-net) module and using the code

'''
var AuhorizeNet = require('authorize-net');
    var client = new AuthorizeNet({
      API_LOGIN_ID: '6***********c',
      TRANSACTION_KEY: '35a3**********aaqQ'
    });
'''

**Comment by jdalton** [comment]
I don't see any `runInContext` use in `stripe` and don't see anything out of the ordinary. Is your environment modified in some way, for example is the Node environment not the normal one? Is it running in NW.js? Is it transpiled in some way or executing in a web worker?
