### ISSUE TITLE
`_.(...).times(...);` is not working in 3.10.*

### ISSUE THREAD

**Issue by Domiii** [lodash/lodash#1628]
1. As [this fiddle](http://jsfiddle.net/W4QfJ/905/) shows: `_(5).times(function() { console.log('hi'); } );` still works in v2.4.2

2. However, as [this fiddle](http://jsfiddle.net/W4QfJ/906/) shows: `_(5).times(function() { console.log('hi'); } );` does not work anymore in v3.10.0

**Comment by jridgewell** [comment]
lodash implemented lazy chaining in v3. Adding a `.value()` call to the end will evaluate the chain.

```js
_(5).times(function() { console.log('hi'); } ).value();
```

**Comment by jdalton** [comment]
In v4 `_#each` will auto end a sequence, I could see this being extended to `_#times` too.

**Comment by jdalton** [comment]
@Domiii I've made `_.times` implicitly end a chain sequence via https://github.com/lodash/lodash/commit/c1b7679cac571da7c66c7a0d2fb6fb03aa022ce0.

**Comment by Domiii** [comment]
:+1:
