### ISSUE TITLE
Missing Documentation in the changelog: _.take is always returning array now

### ISSUE THREAD

**Issue by KeKs0r** [lodash/lodash#1629]
Hi,

I just upgraded from 2.4 to 3.10 and I encountered a change in behaviour that I did not see in the changelog:

```Javascript
// 2.4
_.take([2,3,4,5])  // 2

// 3.10
_.take([2,3,4,5]) // [2]
```
Not sure where exactly that change was made, I assume from 2.x to 3. but I did not find a comment about it.

It might make sense to add it to the changelog.

**Comment by jdalton** [comment]
Hi @KeKs0r! It's covered under the [compatibility warnings](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings) section at the block with
> Split _.first & _.last into _.take, _.takeWhile, _.takeRight, & _.takeRightWhile

**Comment by KeKs0r** [comment]
I have read that you split first and last into _.take etc. but where exactly does it say the change in behaviour of `_.take([2,3,4,5])`

**Comment by jdalton** [comment]
Splitting out implies the change, it also linked to the docs. I'm not interested in revisiting or rehashing v3 since v4 is almost out the door.

**Comment by KeKs0r** [comment]
okay. For me it was just not clear that splitting out means that change in behaviour. Thought it could be clearer.

**Comment by jdalton** [comment]
No worries.
