### ISSUE TITLE
isMatch depends on argument order for arrays.

### ISSUE THREAD

**Issue by gmaughan** [lodash/lodash#1631]
When using isMatch (v3.10.1) the result differs depending on the order of the arguments when arrays and nested arrays have differing lengths.

```javascript
var obj1 = [1, 2, 3];
var obj2 = [1, 2];

var result1 = _.isMatch(obj1, obj2); // returns true, should be false.
var result2 = _.isMatch(obj2, obj1); // returns false

var obj3 = { a: [1, 2, 3] };
var obj4 = { a: [1, 2] };

var result3 = _.isMatch(obj3, obj4); // returns true, should be false.
var result4 = _.isMatch(obj4, obj3); // returns false
```

Unless I misunderstand how isMatch is supposed to work.

Fiddle: https://jsfiddle.net/gmaughan/bony3v3r/

**Comment by jdalton** [comment]
The `_.isMatch` method compares `object` against a `source` object. It returns true if it partially matches `source` so returning `true` for `_.isMatch(obj1, obj2)` is correct as `obj1` contains values `1` and `2`.

**Comment by gmaughan** [comment]
I understand now. Thanks.

Is there anything in lodash that will perform an "exact match" of two objects? If not, is this something that could be added?

I'm frequently coding an AngularJS pattern whereby I `_.cloneDeep()` a model object, bind the clone properties to a dialog view, and then enable the "OK" button only if modifications have been made. To determine if modifications have been made I compare the original with the clone. Rather than having to write custom compare methods (which often forget to compare newly added properties), it would be nice to have an `_.exactMatch()` method that would provide a generic solution.

**Comment by jdalton** [comment]
You're looking for something like `_.isEqual`.

**Comment by gmaughan** [comment]
Thank you. Exactly what I was after.

I'm going to pretend I was using that all along and didn't spend hours trying to use `_.isMatch` the wrong way. And I'm also going to hope that no-one (other than yourself) noticed I raised an issue on it.

Thanks for the quick responses.

**Comment by jdalton** [comment]
@gmaughan No worries. Feel free to ask a question any time. You can also pop in to our [gitter room](https://gitter.im/lodash/lodash), folks there are happy to help as well.
