### ISSUE TITLE
Question about the the Roadmap plan on _.each

### ISSUE THREAD

**Issue by Alexsey** [lodash/lodash#1634]
Now ```_.each``` is an alias for ```_.forEach```. The Roadmap says that ```_.each``` will end a chain sequence. So two questions are:
1. Does it means that ```_.each``` become a separate method with slightly different behavior than ```_.forEach``` or this change is about ```_.forEach``` (while ```_.each``` is it alias no matter what)?
2. How would it end chain sequence? Would it still return initial Collection but just not wraped, or it starts to return ```undefined``` like native ```Array.prototype.forEach```?

Thanks

**Comment by jdalton** [comment]
No `_.each` is not becoming a separate method. `_.forEach` will end a chain sequence meaning that by default `_.each(array, func)` will execute immediately instead of requiring `_.each(array, func).value()`.

**Comment by Alexsey** [comment]
You probably means that ```_(array).each(func)``` will execute instantly. Ok, than I can count on it return value as ```array```. Thanks!
