### ISSUE TITLE
Bug with filtering by String value

### ISSUE THREAD

**Issue by Zelios1** [lodash/lodash#1635]
I trying to filter array by string value.

// Example http://jsfiddle.net/W4QfJ/917/
var arr = ["1", "1"];
alert(_.filter(arr, "1").length);

I think, expected result array is length 2

**Comment by Alexsey** [comment]
The thing is that ```_.filter``` method is an instrument to work mainly with Collections of objects. That is why when you pass String as a second argument it is not comparing each element with it, but trying to read properties with such name on each element and take only those how are truly

For example this
```
var arr = [{a: 1}, {a: 0}]
alert(_.filter(arr, "a").length)
```
will alert 1.

Your problem could be solved, for example, like this
```
var arr = ["1", "1"];
alert(_.filter(arr, _.eq.bind(_, '1')).length);
```

**Comment by jdalton** [comment]
Hi @Zelios1! You're using the method incorrectly. Passing a string for the `iteratee` param is a shortcut for `_.property('1')` which creates a function like:
```js
_.filter(arr, function(element) { return element[1] });
```

**Comment by Zelios1** [comment]
@Alexsey @jdalton Thank you for your response
