### ISSUE TITLE
Lazy optimization for `at`

### ISSUE THREAD

**Issue by dcherman** [lodash/lodash#1636]
When using `at` to pull specific indexes from an array mapped using lazy evaluation (and maybe other operations too), it seems like we're missing the potential for more optimizations

    var testFixture = [];
    
    Object.defineProperty(testFixture, '0', { get() { console.log('Get', 0); return 0; }})
    Object.defineProperty(testFixture, '1', { get() { console.log('Get', 1); return 1; }})
    Object.defineProperty(testFixture, '2', { get() { console.log('Get', 2); return 2; }})

    _(testFixture).map(item => item + 1).at(1).value();

In that example, it seems like it should be possible to optimize the chain such that only the mapping function for the indexes provided in `at` are executed.  Currently, it looks like the mapping function is executed for all indexes

**Comment by jdalton** [comment]
You're right we could add support for this. I'd like to keep the lazy evaluation code simple (not too large) as it has a more narrow use case (any time shortcut fusion can be applied). Is this something you're wanting because of a project, like a Mozilla project, or just a neat to have?

**Comment by dcherman** [comment]
This is going to assume a bit of knowledge about AngularJS, so please let me know if clarification is needed.

So the specific use case is that I've implemented virtual tree structures in AngularJS in order to support lists containing hundreds of thousands of items.  In certain cases, I need the next item in the tree, however there is no true tree structure in memory, the relations are all built up via expressions.  It's insanely expensive to construct the entire tree at once which is why my `children` property is currently is only evaluated when requested (then cached), however that doesn't solve the case of "I want a specific node at this index".  In order to do that, I currently fall back to manual construction of that node by wrapping the value at the provided index in the resolved expression.

What would be awesome would be able to do something like

```js
class VirtualBranch {
  children() {
    return _(this.values).map(value => new VirtualNode(value));
  }
}
```

Given lazy evaluation, I'd then be able to do

```js
thisBranch.children().at(60000).value();
```

Which should allow me access to the 60000th child without requiring construction of all others.  I've implemented this in my own code so it's not high priority for me, however my initial attempt was writing that exact code line of code above since intuitively it felt like it should work

**Comment by jdalton** [comment]
I'll kick something around. This would be doable for a single index by using our lazy `slice` under the hood, for more indexes it would require re-working our lazy implementation as it's currently set up to handle `start` and `end` index ranges and not individual indexes. This optimization would also not apply if there's a `filter` in the sequence before it.

**Comment by jdalton** [comment]
After digging it looks like support for this fully will cost too much in implementation. Our `_.at` method can work on arrays or objects and can accept deep paths. That said I can support the case of an array selecting a single index pretty easily so in that case shortcut fusion will kick in.

**Comment by jdalton** [comment]
The implementation looks like:
```js
    LazyWrapper.prototype.at = rest(function(paths) {
      paths = baseFlatten(paths);
      return (paths.length == 1 && isIndex(paths[0]))
        ? this.slice(paths[0], paths[0] + 1)
        : new LazyWrapper(this);
    });
```
