### ISSUE TITLE
_.random should use the CSPRNG when available

### ISSUE THREAD

**Issue by Risto-Stevcev** [lodash/lodash#1638]
`_.random` should use the CSPRNG when available, and default to `Math.random` when it isn't available.

    crypto.getRandomValues(new Uint8Array(1))[0]
    // 162

**Comment by AjaxSolutions** [comment]
What's the benefit?

**Comment by jdalton** [comment]
Hi @Risto-Stevcev! Thanks for the suggestion. It [looks like](https://github.com/EFForg/OpenWireless/pull/195/files#diff-8cddc026f79ea9a8ce95eb6112cc3a50R59) the work required to use this as a `Math.random` replacement is rather high for our cases. I think for a general purpose util lib like lodash `Math.random` is fine.

**Comment by Risto-Stevcev** [comment]
@AjaxSolutions `crypto.getRandomValues` is cryptographically secure, which ensures a high degree of entropy from the PRNG. It can be used in situations where cryptography is needed on the browser side, which inspired the creation of the W3 Web Cryptography API. Braintree, which offers a SaaS solution for a payment gateway/merchant services, also uses this PRNG for its browser side payments API. The implementation is dependent on the JS engine and uses an OS level entropy source:

From the [Web Cryptography API](https://dvcs.w3.org/hg/webcrypto-api/raw-file/tip/spec/Overview.html#RandomSource-method-getRandomValues):
> **Note:** Implementations should generate cryptographically random values using well-established cryptographic pseudo-random number generators seeded with high-quality entropy, such as from an operating-system entropy source (e.g., "/dev/urandom").

There's also a [note on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random) about it in the `Math.random` article.

@jdalton I don't think it should be that much work. If performance or choice is an issue, you could just add it as something like `_.csRandom`:

```javascript
if ((crypto || msCrypto) && Uint8Array) {
   return (crypto || msCrypto).getRandomValues(new Uint8Array(1))[0]; // divide by 256 for a number between 0 (inclusive) and 1 (inclusive)
}
else {
  // ...
}
```

**Comment by jdalton** [comment]
@Risto-Stevcev By work required I mean feature testing typed arrays and the crypto API then forking our method implementation and mucking with trying to make it fit our existing expectations. All of that seems like too much for very little gain. Lodash shuffles arrays or has a bit of sugar around `Math.random`.

**Comment by polkovnikov-ph** [comment]
Isn't CSPRNG _much_ slower than a simple PRNG? What's the point of making any PRNG-dependent function slower when most likely there's no such need? The `_.csRandom` would be used only by cryptographers while all the other users will get that 1KiB extra traffic.
