### ISSUE TITLE
What is the WALTR link in the docs? Is this an ad? 

### ISSUE THREAD

**Issue by NickHeiner** [lodash/lodash#1640]
![docs screenshot](https://cloud.githubusercontent.com/assets/829827/11170315/7b166322-8b9e-11e5-8e6c-54ae915dc0bd.png)

What is this? I don't recognize the url it's going to (`http://www.launchbit.com/taz/9533-6215-111/`). Is this supposed to be an ad? If so, it should be clearly labelled as such. Is this a malicious link?

**Comment by NickHeiner** [comment]
Ah, nevermind, I see this now: https://twitter.com/jdalton/status/665681583853015040. 

I would still suggest that this be labelled in a way to make it obviously not malicious.

**Comment by jdalton** [comment]
Yep, it's an add. It should look like:
<img width="333" alt="screen shot 2015-11-15 at 10 59 34 am" src="https://cloud.githubusercontent.com/assets/4303/11170396/cd69dd5a-8b87-11e5-9e1e-6574ace324f8.png">

Do you have any other extensions that could be augmenting the page?

**Comment by jdalton** [comment]
I've checked Chrome 46, FF 41, Safari 9, Edge 13, IE 11 and IE 11 (9 compat) and all display it correctly.

**Comment by NickHeiner** [comment]
yeah, it looks better when I view it in Incognito. I must have an extension that's messing with it. Thanks, and sorry for the confusion.

**Comment by jdalton** [comment]
Let me know if you narrow it down.

**Comment by ricardograca** [comment]
It's also messed up on my side. It's Privacy Badger, and not all ads are blocked. Some look ok. Others which are probably attempting to track me are blocked. `launchbit.com` seems to be blocked.

**Comment by jdalton** [comment]
Thanks, I'll let cardonads know.

**Comment by toddynho** [comment]
A fresh install of Privacy Badger shows the LaunchBit ads OK on lodash. Maybe there is another extension at play here?

![screen shot 2015-11-17 at 8 45 22 am](https://cloud.githubusercontent.com/assets/410565/11213068/fd43807c-8d07-11e5-91d6-af209a035502.png)

Carbon was recently whitelisted by AdBlockPlus (an unpaid whitelisting, fwiw). LaunchBit is associated with Carbon, and for Carbon-specific ads was also whitelisted by AdBlockPlus at the same time. I understand that Privacy Badger doesn't use AdBlockPlus whitelists, but figure it's worth mentioning that both domains recently went through some sort of vetting process.

**Comment by ricardograca** [comment]
Today every ads seems to be loading fine actually, so I guess Privacy Badger changed something. I did see a lot of "Ad placeholder ❤︎︎" though.

**Comment by jdalton** [comment]
Another user reporting issues:
<img src="https://cloud.githubusercontent.com/assets/4303/11230077/6f91f148-8d50-11e5-8648-110ededb0f93.png" height=70% width=70%>

**Comment by toddynho** [comment]
@ricardograca Thank you for the reply! What do you mean by "Ad placeholder :heart:"?

@jdalton I understand it might be difficult to get, but any way to figure out which browser extensions this user might have installed? A fresh install of both Privacy Badger & AdBlockPlus enabled at the same time yields me this:

<img width="1155" alt="screen shot 2015-11-18 at 7 38 10 am" src="https://cloud.githubusercontent.com/assets/410565/11241286/943eb022-8dc7-11e5-8721-7f24f2e0f6c8.png">

**Comment by ricardograca** [comment]
I also got the messed up display as @jdalton reported the first time I accessed the docs after not having accessed it for about a week (maybe more, maybe less?) but after a few refreshes it was displaying correctly, so my guess is that some css file was not getting updated due to caching.

@toddynho I can't reproduce it anymore, but it was basically just the empty ad rectangle with that text (including the heart) at the bottom instead of any actual ad text.

**Comment by jdalton** [comment]
@ricardograca 
> so my guess is that some css file was not getting updated due to caching.

Nice.

@toddynho @ricardograca
> What do you mean by "Ad placeholder :heart:"?

If you view the site with an ad blocker on that doesn't allow non-intrusive ads then I created a placeholder to be shown to preserve layout and let developers know there would be an ad there.
<img src="https://cloud.githubusercontent.com/assets/4303/11248702/838617ce-8dd7-11e5-8757-6ab41d59bddc.png" height=40% width=40%>

Let me know if that's against policy or if there's a suggest/standard way to do that.

**Comment by toddynho** [comment]
@jdalton ah, yes, I should have known to test with and without the Acceptable Ads filter checked off. My fault, thanks for letting me know! And no, not against any policy whatsoever... I am thinking we (Carbon) should come up with something that could be displayed in the place of the ad that helps explain that the ad being blocked is part of the "Acceptable Ads" initiative. Will chat with the team about it.
