### ISSUE TITLE
first() is no longer chainable

### ISSUE THREAD

**Issue by zorji** [lodash/lodash#1641]
In the previous version _([1, 2, 3]).first(2)
return a lodash chainable object

but now it returns 1.

**Comment by jdalton** [comment]
Hi @zorji! In [v3](https://github.com/lodash/lodash/wiki/Changelog#v300) the `_.first` method was split out into `_.first` and `_.take`. You'll want to use `_(array).take(2)` now.

**Comment by zorji** [comment]
Thanks @jdalton 
I just saw it in the LoDash change logs too
