### ISSUE TITLE
asking about _.difference 

### ISSUE THREAD

**Issue by emaniacs** [lodash/lodash#1642]
Hi all.

Iam using _.difference with two variables but got different result if i swap the argument.
Here the example.

```
var a = [1,2,3,4];
var b = [1,2,3,4,5];
console.log(_.difference(a,b)) // got []
console.log(_.difference(b,a)) // got [5]
```

Is that normal?
So i need put the longest variable as the first arguments?

**Comment by emaniacs** [comment]
i use 3.10.0

![image](https://cloud.githubusercontent.com/assets/314789/11175171/de7ce3e6-8c61-11e5-983f-87be1c33ea56.png)

**Comment by jdalton** [comment]
> Is that normal?

Yes

The [documentation states](https://lodash.com/docs#difference):
> 
`_.difference(array, [values])`
Creates an array of unique `array` values not included in the other provided arrays using SameValueZero for equality comparisons.
