### ISSUE TITLE
Compounder functions should not break apart [0-9][a-z]

### ISSUE THREAD

**Issue by leftmostcat** [lodash/lodash#1649]
Currently, passing isoCode2b or iso_code_2b to .snakeCase() will return iso_code_2_b. Additionally, iso_code_2b passed to .camelCase() gives isoCode2B, though I would expect isoCode2b. In general, this behavior seems a more consistent means of breaking apart "words", given that no uppercase follows.

**Comment by jdalton** [comment]
Hi @leftmostcat!

This is resolved on our edge master branch.
