### ISSUE TITLE
Does isEqual support FormData?

### ISSUE THREAD

**Issue by toranb** [lodash/lodash#1652]
First up, thank you for maintaining such a powerful/ valuable piece of software. Without all your time we would each spend countless time re-inventing the wheel.

** **

I'm new to lodash and mostly want to be educated on how isEqual works/or doesn't with FormData. My limited understanding is that isEqual offers a "deep" equality check. This works great for Array when I expect 2 diff Arrays to match (when the primitive values they contain are equivalent). When I do something similar w/ FormData it seems I get false. Is this intentional? If yes, do you suggest (or have) another api I could use to assert equality?

It does appear that calling $(mockData).serializeArray(); will produce something isEqual can compare against (like Array). Is it possible you would accept a PR to improve isEqual (to add support for FormData)?

Thanks again for helping provide such a great open source library/ecosystem!

![screen shot 2015-11-19 at 11 51 42 am](https://cloud.githubusercontent.com/assets/147411/11279146/74eaf350-8eb4-11e5-87e4-fa6608ac956a.png)

**Comment by toranb** [comment]
For anyone who might follow up, here is the workaround I've got in place currently

```js
    function eql(first, second) {
        if (first instanceof FormData && second instanceof FormData) {
            first = $(first).serializeArray();
            second = $(second).serializeArray();
        }
        return _.isEqual(first, second);
    }
```

**Comment by jdalton** [comment]
The `_.isEqual` implementation checks if objects are of the same constructor which may be causing an issue here. Can you check if your `mockData.constructor` is `===` that of `realData.constructor`.

**Comment by toranb** [comment]
![screen shot 2015-11-19 at 2 11 16 pm](https://cloud.githubusercontent.com/assets/147411/11282911/77eea264-8ec7-11e5-9896-a0ede2157165.png)

**Comment by jdalton** [comment]
Can you report the `_.keys(x)` and `_.keys(y)` results.

**Comment by toranb** [comment]
![screen shot 2015-11-19 at 2 26 49 pm](https://cloud.githubusercontent.com/assets/147411/11283289/9b4b84f0-8ec9-11e5-8ff2-db666875a8db.png)

**Comment by jdalton** [comment]
`_.isEqual` only compares own properties of objects so it would be seeing that both are empty and then doing an inheritance check.  Can you create a [jsbin](https://jsbin.com/?js,console) and I'll dig in a bit.

**Comment by toranb** [comment]
Honestly I'm not sure a jsbin is required :)

```js
var first = new FormData();
var second = new FormData();
```

I think the above is all I'm doing actually - thanks for attacking this problem so quickly btw!

**Comment by jdalton** [comment]
Rock. It's because `new FormData` objects have a `Object.prototype.toString.call(new FormData)` output of `[object FormData]` which is an unknown type. We could handle these as plain objects. So I'll treat this issue as the feature request.

**Comment by toranb** [comment]
Wow - glad I could help find something like this :)

Thanks for the deep dive/education today!

**Comment by jdalton** [comment]
After looking at this a bit more the `FormData` objects have no enumerable properties so wouldn't work well for comparison by default in `_.isEqual` even if I treat them as plain objects. You can customize `_.isEqual` with:

In v3:
```js
var eql = _.partialRight(_.isEqual, function(first, second) {
  if (first instanceof FormData && second instanceof FormData) {
    return _.isEqual($(first).serializeArray(), $(second).serializeArray());
  }
});
```

In v4:
```js
var eql = _.partialRight(_.isEqualWith, function(first, second) {
  if (first instanceof FormData && second instanceof FormData) {
    return _.isEqual($(first).serializeArray(), $(second).serializeArray());
  }
});
