### ISSUE TITLE
lt, lte, gt, gte, add and other 'binary' functions with single argument

### ISSUE THREAD

**Issue by Alexsey** [lodash/lodash#1655]
For now there is no sense in functions that represents binary operation to be called with single argument. My proposal is to make them return a function in such case. It is almost like make them auto curry but in this case we should bind not first, but second parameter. So
```
let gt3 = _.gt(3)
```
Would be the same as
```
let gt3 = _.partial(_.gt, _, 3)
```
so it could be used like
```
let a = [1, 2, 3, 4, 5]
_.filter(a, _.gt(3)) // [4, 5]
_.map(a, _.add(3)) // [4, 5, 6, 7, 8]
```

**Comment by jdalton** [comment]
Auto curried methods will be possible with `require('lodash/fp')()` in v4.

**Comment by Alexsey** [comment]
But this is not auto curring. The```_.gt```, I've used here as example, and others will have opposite to expected behavior with auto curring:
```
let a = [1, 2, 3, 4, 5]
_.filter(a, _.curry(_.gt)(3)) // [1, 2]
```
That is why I'm talking about specific behavior for functions that represents binary operations
