### ISSUE TITLE
Partials, partials everywhere

### ISSUE THREAD

**Issue by thaumant** [lodash/lodash#1656]
When used with promises, streams and nested structures, `_.partial` is a common and very useful tool but it often piles up with other functions and decreases readability.

Scala short syntax for anonymous functions suggests a way to simplify things a bit: `list.map(_*2)`. The idea is to return partial function whenever `_` is provided as an argument. Some examples:

```javascript
// from this:
_.map(objects, _.partial(_.set, _, 'index', _))
// to this:
_.map(objects, _.set(_, 'index', _))


// from this:
getUsers()
    .then(users =>
        _.map(users, _.partial(_.omit, _, ['password', 'salt', 'email']))
// to this:
getUsers().then(_.map(_, _.omit(_, ['password', 'salt', 'email'])))
```

This is a breaking and maybe controversial change, and I'm curious if you would consider implementing or at least discussing it.

**Comment by Alexsey** [comment]
This would awesome

**Comment by StreetStrider** [comment]
@thaumant, it is a great improvement, but there's a greater one: auto-curried functions. The main player (in my opinion) here is Ramda, but LoDash has lodash-fp, which is as far as I know, implement auto-currying. You can check this libs, maybe you'll find them interesting.

But your partial idea is a good one too. In some cases you need to not to bind left argument or arguments in the middle. This was the main reason for LoDash to support placeholders in partial.

**Comment by Alexsey** [comment]
From my experience auto-partial will simplify more cases then auto-curring

**Comment by StreetStrider** [comment]
@Alexsey, auto-currying is an auto-partial with no need in explicit call of `partial`. So it covers all the cases which is covered by partial. Prove an counter-example, if I wrong.

**Comment by Alexsey** [comment]
@StreetStrider both examples from initial post. While first one is quite specific (usage of indexes is specific by itself :) ) second one is kind of I run in to quite often. Or here is a fresh one from just closed nearby issue
```
let a = [1, 2, 3, 4, 5]
a.filter(_.partial(_.gt, _, 3)) // [4, 5]
```
would become just
```
let a = [1, 2, 3, 4, 5]
a.filter(_.gt(_, 3)) // [4, 5]
```
while auto curring will just

```
let a = [1, 2, 3, 4, 5]
a.filter(_.gt(3)) // [1, 2]
```

**Comment by jdalton** [comment]
Adding partial sugar to each method is not practical and will over complicate dependencies, cherry-picking, & add extra perf overhead. In lodash v4 fp- auto-curried, iteratee-first data-last, immutable methods will be available via `require('lodash/fp')()`.

**Comment by StreetStrider** [comment]
@Alexsey, your example IS actual an auto-currying with additional feature: placeholder. So we both speak about the same thing. As for `gt` example, it can be reversed with `lte` and then curried. In most of the cases data-argument is last, so currying works good (so you can specify first argument to `pluck`, `pick` and others to create «pluckers», «pickers» etc :smile:)

**Comment by Alexsey** [comment]
@StreetStrider I was not aware of ```lodash/fp``` will also be iteratee-first data-last. If it will also accept placeholders, and as far as ```curry``` does - it should also, it will really solve the all issues here. About ```gt``` - yes, it could be replaced with ```lte```, but it would be misleading for some one who will read your code
