### ISSUE TITLE
_.invoke change.

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash#1658]
I'd like to bring up changing `_.invoke` to an Object method. In master I've exposed `_.invokePath`.
I'd like `_.invokePath` to be named `_.invoke` and the old `_.invoke` renamed to `_.mapInvoke`. 

I'm interested in feedback, specifically @jridgewell and @megawac, as you all contribute to Backbone which would need updating if the rename was to happen.

**Comment by megawac** [comment]
I'm always going to :-1: these method renames unless they are absolutely necessary. This would be another change that would be difficult to address for some libraries which try to support multiple versions of lodash/underscore (Marionette).

I'm :+1: on the addition of some sort of `invokePath` which takes arguments (unlike `_.result`). As a side note, there is [`invoker`](http://ramdajs.com/0.18.0/docs/#invoker) in ramda which returns a function. Not sure which I would prefer

**Comment by Alexsey** [comment]
@megawac Ramda's ```invoker``` is LoDash's ```method```

**Comment by megawac** [comment]
Oh right! Thanks! Then I'd argue the _.invokePath use case is already
covered

**Comment by Alexsey** [comment]
Such naming will come to situation when we have ```invoke``` and ```mapInvoke``` which is actually not ```map(invoke)``` but ```map(method)```. So better naming for current ```invoke``` will become ```mapMethod```. Or ```method``` should become ```invoker``` as in Ramda. Then ```invoke```, ```invoker``` and ```mapInvoke``` will looks really good with each other.

I don't feel my self confident to speak about resonability of having such new function (if we'll have it - I will use it :) ) but generally having ```invoke``` and ```result``` which solves different halves of the same problem does not looks good. But here I don't see any obvious good solutions :(

**Comment by jdalton** [comment]
I think `_.method` and `_.methodOf` are great companions to `_.property` and `_.propertyOf` and don't need their names to change to align with `invoke`.

I don't think the use case for `_.invokePath` is covered by `_.method` anymore than `_.get` is covered by `_.property`.

I could see `_.invokeOn` as being an alternative name to `_.invokePath` if renaming `_.invoke` is out, though I'm still on the fence on the whole renaming thing.

As to the cross-lib issue, I think it'd be a shame to hold up refactoring or clarity for the sake of cross-lib compat esp when the other lib is effectively stalled.

<img src="https://cloud.githubusercontent.com/assets/4303/11340877/d9b0b196-91b4-11e5-866c-1692409293f0.png" height=100% width=100%>

It may be time to bring up tough questions like: Should Backbone switch to lodash, since @braddunbar has npm publish rights to Backbone and can work with lodash to update in a more timely manner?

**Comment by jridgewell** [comment]
It would make more sense if we renamed `_.invoke` to `_.mapInvoke`, but renaming `_.invokePath` to `_.invoke` will cause mayhem for badly versioned dependencies (e.g. Backbone, but a ton of pre-bundle-era frontend code). I'd say :-1:

**Comment by jdalton** [comment]
Would you all be against changing the one [_.invoke use in Backbone](https://github.com/jashkenas/backbone/blob/33c7e1806916b782fc01c171d8160f5fc381a540/backbone.js#L1014) to:
```js
return _.map(this.models, function(model) {
  return model.get(attr);
});
```

Also opinion on the dep swap in Backbone? Has the topic Jeremy's leave of absence and releases been covered by the core of the various projects he owns?

**Comment by jdalton** [comment]
>  but renaming `_.invokePath` to `_.invoke` will cause mayhem for badly versioned dependencies 

The v4 version of Lodash will only work with Backbone v1.2.3 at the moment and I can push that to a future version of Backbone if needed.

**Comment by megawac** [comment]
I'm indifferent to a default dep swap in Backbone, you can file an issue on
the appropriate repo.

Changing the behaviours of methods can affect a lot of peoples code; it's
not hard to fix but its annoying, especially when its caused by a third
party lib (e.g. invoke->invokeMap in Backbone caused by lodash). If you
want to rename a method and reuse the method name for something else I
would personally prefer the method not being used for 1 major version.

In the case of marionette _.invoke is used 20 some odd times between core
and tests

On Mon, Nov 23, 2015 at 3:22 PM, John-David Dalton <notifications@github.com

**Comment by jdalton** [comment]
Could this be tackled with a v2 of Backbone to then use Lodash v4? That way it's super explicit. I'm ok if that means slower adoption on packages like Marionette since v3 works at the moment.

Do you have other suggestions other than `_.invoke` for `_.invokePath` (`invokeOn`)?

**Comment by jridgewell** [comment]
> Would you all be against changing the one _.invoke use in Backbone to:

Actually, that wouldn't be bad. But with Backbone specifically, a the libraries built on top don't have control of the underscore/lodash version. Instead, they just rely on the website including the right script tag beforehand.

> Do you have other suggestions other than _.invoke for _.invokePath (invokeOn)?

`_.invokeOn` sounds alright.

**Comment by jdalton** [comment]
Thanks @jridgewell! Time to bring in @akre54 and @michaelficarra for input.

**Comment by akre54** [comment]
So this thread started as a petition to rename a method (ok...) and quickly spun into a @jashkenas power grab in absentia. Jesus. This is depressingly common from you.

The method name is fine, an extra method is fine. `_.invokeMap` is fine. But you didn't need any external input to add yet another method to Lo-Dash. Just keep doing you dude.

Underscore is mostly done. If you want to make this change, go for it. I'm -1 on breaking b/c in Underscore without a good reason though.

**Comment by jdalton** [comment]
@akre54
Thanks for the input.
This is less about a breaking change with Underscore and more for the Lodash api.

**Comment by akre54** [comment]
Great, lets keep it there.

Also please don't edit my posts. It's tasteless and shows you can't stand up to even the slightest scrutiny.

**Comment by jdalton** [comment]
Thanks for your input but it's not an invitation for you to be toxic. I'll moderate as needed.

**Comment by akre54** [comment]
:expressionless:

**Comment by jdalton** [comment]
Thanks all for your feedback :clap: 

I'll kick around names for a few more days.
It looks like based on feedback `invokeOn` is in the lead for what is currently `invokePath` and `mapInvoke` for what is currently `_.invoke`.

**Comment by jdalton** [comment]
Ok, I've settled on `_.invokeMap(collection, methodName)` and `_.invoke(object, methodName)`. This is a breaking change for libs build with both util libs in mind so I'll likely create an adapter to smooth things over.

**Comment by paulfalgout** [comment]
:crying_cat_face: https://github.com/marionettejs/backbone.marionette/commit/8d302a2a54422eb6ce7988776ab56766e57d6e96  :sob:

**Comment by jdalton** [comment]
> :crying_cat_face: https://github.com/marionettejs/backbone.marionette/commit/8d302a2a54422eb6ce7988776ab56766e57d6e96  :sob: 

Look at it glass half full and that you get ES6 arrow functions!

**Comment by paulfalgout** [comment]
heh yeah.  It's not _that_ big of a deal.
