### ISSUE TITLE
Feature request: _.returns. Returns the first argument of the wrapped function.

### ISSUE THREAD

**Issue by jamesrom** [lodash/lodash#1662]
This pattern is not uncommon, especially with Promises:

```js
get('/data.json')
    .then(function(data) {
        doSomeSideEffect();
        return data;
    })
    .then(function(data) {
        doSomeOtherSideEffect();
        return data;
    })
    .then(doSomeDataTransform)
    .then(actuallyUseData);
```

It would be cool to be able to streamline this a bit with something like `_.returns`.

```js
get('/data.json')
    .then(_.returns(doSomeSideEffect))
    .then(_.returns(doSomeOtherSideEffect))
    .then(doSomeDataTransform)
    .then(actuallyUseData);
```

Basically, `_.returns` should take a function and return a wrapped version of that function that returns the first argument passed to it.

There's a couple of ways this to do this already, for example something like:

```js
_.returns = function (fn) {
    return _.partial(_.tap, _, fn);
}
```

But having built in support for something like this would be great. Does this feature already exist?

**Comment by jdalton** [comment]
Hi @jamesrom!

I'm very interested in adding more methods for Promises. I can see the need for them has grown over time. I'd like to hold off though until there's more demand for specific methods before adding them to core. That said if you can think of others keep the ideas coming.
