### ISSUE TITLE
startCase replaces Umlauts

### ISSUE THREAD

**Issue by mrwonko** [lodash/lodash#1663]
I expect `_.startCase("ätzender döner")` to produce `"Ätzender Döner"` - instead I get `"Atzender Doner"`. Same with `kebapCase`, `snakeCase` and `camelCase`, while `capitalize` works.

**Comment by J3remyD** [comment]
Hi @mrwonko ,

I'm not sure this is an issue since it uses a function deburr() which converts latin-1 letters to basic latin ones and removes diacritical marks like deburr's comment says

**Comment by jdalton** [comment]
Any of our compound word methods like `_.camelCase`, `_.kebabCase`, `_.snakeCase`, and `_.startCase` will deburr to simplify their implementation and allow values to be more easily transformed between them.

In v4 we're introducing `_.upperFirst`, `_.lowerFirst` which will not deburr and allow for similar transformations.
