### ISSUE TITLE
_.flattenDeep errors on arrays with circular references. 

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash#1664]
```js
var arr = [1, 2, 3];
arr.push(arr);

_.flatten(arr);
// => Uncaught RangeError: Maximum call stack size exceeded(…)flatten
```

Result could be:
```js
[1, 2, 3, 1, 2, 3]
```

**Comment by jdalton** [comment]
Related to https://github.com/jashkenas/underscore/issues/2363#issuecomment-159675177.

**Comment by megawac** [comment]
:-1: on this behaviour

**Comment by jdalton** [comment]
I rather it not error. Lodash avoids erroring in other similar cases.

**Comment by megawac** [comment]
I'd argue the error is reasonable and not worth the code to support the edge case

**Comment by jdalton** [comment]
The code to support it is minimal. The dependency on the other hand is a bit heftier but I should really come up with a good low level to make it swappable with (webpack magic).

**Comment by megawac** [comment]
Also were there any noteable perf side affects from this?

**Comment by jdalton** [comment]
I donno yet. I have no real competition in the utilities space at the moment so I have some breathing room. As normal I'll evaluate and adjust for perf before I release.
