### ISSUE TITLE
Question: isLength and isArrayLike npms?

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1665]
Hi there! I don't know how your release process works but I was wondering if you may be releasing `isLength` and `isArrayLike` as npms in the near future? I see them in the npm branch, but not in the npm_packages branch. Is this something that you wait for requests for, if so the yes please. ;)

**Comment by jdalton** [comment]
Hi @Xotic750! They will be released with v4 as `lodash.islength` and `lodash.isarraylike` packages.

**Comment by Xotic750** [comment]
Damn, I guess I'll be making my own until then. You said that would be early next year sometime?

**Comment by jdalton** [comment]
Yep, Jan 12 or 16. If you create your own I'd just ask that you avoid the `lodash.*` package naming scheme so it's free for our use.

**Comment by Xotic750** [comment]
No problem, I'm doing everything camelcase with -x at the end. :)

**Comment by StreetStrider** [comment]
@Xotic750, you could use `lodash-` to make it clear it is a mixin. @jdalton, am I correct?

**Comment by jdalton** [comment]
@StreetStrider
I'm fine with anything other than `lodash.*` : P

**Comment by Xotic750** [comment]
https://www.npmjs.com/package/is-length-x
https://www.npmjs.com/package/is-array-like-x
Just say if you have any problem with these.

**Comment by jdalton** [comment]
Looks good
