### ISSUE TITLE
_.recurse

### ISSUE THREAD

**Issue by levithomason** [lodash/lodash#1666]
Recursion is a common operation, it would be handy to be able to recursively call an iteratee on any object.  Would love to have a util like this in lodash.  Needs some beefing up to be implemented, would be nice if it worked on any collection. Any interest?

```js
/**
 * Invokes `iteratee` recursively on the `object`.
 * The `iteratee` is bound to `thisArg` and invoked with three arguments: (value, key, object)
 * @param {{}} object The object to recursively loop through.
 * @param {function} iteratee The function invoked per iteration.
 * @param {*} thisArg The `this` binding of `iteratee`.
 */
function recurse(object, iteratee, thisArg = null) {
  Object.keys(object).map(key => {
    iteratee.call(thisArg, object[key], key, object)
    if (Object.prototype.toString.call(object[key]) === '[object Object]') {
      recurse(object[key], iteratee)
    }
  })
}
```

**Comment by jdalton** [comment]
Hi @levithomason!

Thanks for the suggestion. I want to hold of for now, but can see some kind of recursive or deep crawling function in lodash's future.
