### ISSUE TITLE
NaN as number

### ISSUE THREAD

**Issue by bernardolm** [lodash/lodash#1669]
Hello, I found something odd here.

Imagine the following code:

```javascript
parseInt ({}, 10);
```

This should return *NaN* 'cause an *object* can't turn in a *number*.

But if *NaN* is *Not-A-Number*, although the type of *NaN* is *number* (sic), I guess *_.isNumber(NaN)*  should be false.

Why? When normally uses *_.isNumber* is wanted to know if I really have a number to calculate, to iterate, anyway... not?

**Comment by Xotic750** [comment]
You mean you want to test `_.isNumber(value) && _.isFinite(value)`?

**Comment by jdalton** [comment]
`NaN` will return `true` from `_.isNumber` because it's a number type and has a `ToStringTag` of `Number`. Just as an invalid date, `new Date(NaN)`, is still `_.isDate(...)` of `true`.

If you're wanting to validate numbers then something like `_.isFinite` is the way to go.
