### ISSUE TITLE
Why did `where` stopped working with `String` source?

### ISSUE THREAD

**Issue by Ajaxy** [lodash/lodash#1670]
In 2.x it was possible to find elements like this:

```
var users = [{ id: 1, online: true }, { id: 2, online: false }];
_.where(users, 'online');
```

Now in 3.x it's not working. I haven't find any clue in docs or changelog.

Thank you.

**Comment by dtinth** [comment]
`_.where` compares property values. To test for truthy property value, use `_.filter` instead.

**Comment by jdalton** [comment]
Hi @Ajaxy.

In v2, `_.where` was an alias for filter.
