### ISSUE TITLE
_.clone(someFunction) gives {} in v3, when lodash@v2.x gives someFunction

### ISSUE THREAD

**Issue by anodynos** [lodash/lodash#1672]
`_.clone(someFunction)` gives `{}`, when lodash@v2.x gives `someFunction`
I think the old behavior is the correct, cause you can't really clone a Function, so v2.0 did the right thing leaving it as it is. If its left as it is, it should at least be in the docs.

**Comment by jdalton** [comment]
In this case since it's the initial return value we side with an object being returned. I'll take your issue into consideration though.

**Comment by anodynos** [comment]
Thanks John-David . Sorry to be a bugger, but why are you closing the issue if you're going to consider it ?

**Comment by jdalton** [comment]
Because chances are nothing will change. If it does I'll update you.
