### ISSUE TITLE
Code of Conduct bug

### ISSUE THREAD

**Issue by wavebeem** [lodash/lodash#1673]
The text `[INSERT EMAIL ADDRESS]` is in the code of conduct right now. It should be replaced with the project maintainer's email address.

https://github.com/lodash/lodash/commit/999975ae916dff40716043293d359a1be71e59b2#diff-a1ee87dafebc22cbd96979f1b2b7e837R38

**Comment by jdalton** [comment]
Ah, that's new! I'll set up coc@lodash.com.

**Comment by jdalton** [comment]
Want to do the PR?

**Comment by wavebeem** [comment]
Sure! Just a sec.

**Comment by jdalton** [comment]
Thanks! Moving to #1674.
