### ISSUE TITLE
Named export vs default export

### ISSUE THREAD

**Issue by flekschas** [lodash/lodash#1675]
I have been playing around with `lodash-es` and I was wondering why an augmented object is returned rather than a set of all public methods?

Right now the export looks like this:
```
import a from './a';
import b from './b';
import c from './c';

export default {
  'a': a,
  'b': b,
  'c': c
};
```

In order to use a method I am forced to import that whole package, e.g. `lang`, like so:
```
import lang from '../node_modules/lodash-es/lang';
```

(Which is essentially the same as `import default as lang from '../node_modules/lodash-es/lang';`)

While this is convenient when I am planing to use all methods it would be great to be able to let just import certain pieces, like for example `isNumber`.

At the moment I cannot do `import {isNumber} from '../node_modules/lodash-es/lang';` because nothing with the name `isNumber` is being exported.

My suggestion would be export single methods instead. Here's what my example from above would look like:

```
import a from './a';
import b from './b';
import c from './c';

export { a, b, c };
// Optional
export default {
  'a': a,
  'b': b,
  'c': c
};
```

Now there is no default object but we can still achieve exactly the same behavior as before; all we need to do is `import * as lang from '../node_modules/lodash-es/lang'` and we will import everything and scope it as `lang`. At the same we have the flexibility to import a single or multiple functions, plus tools like Rollup.js are able to create bundles that only contain the methods used. The default export could even be kept just for convenience.

Maybe I am missing something but for me the biggest advantage of ES6 modules is the fact that I can easily import the things I need and bundle everything up the way I need it.

**Comment by jdalton** [comment]
I'm working on it. You can see [here](https://github.com/lodash/lodash/tree/es) that modules are isolated correctly.

**Comment by flekschas** [comment]
Great thanks!

**Comment by StreetStrider** [comment]
Man, ES modules are makin me sad. :confused: CommonJS modules is a gift of Gods, why should someone leave it in a sane mind. :confused: why the whole Enterprise leave it.
