### ISSUE TITLE
npm WARN deprecated lodash@ warning is scary

### ISSUE THREAD

**Issue by vladikoff** [lodash/lodash#1678]
Hey @jdalton! getting a lot of these recently:

"I don't know what's up with the lodash error..." regarding the lodash deprecation warnings.

We avoided using this npm feature in some grunt plugins because it confuses plugin users. It is a good thing to communicate to package maintainers, but not users.

Just something to reconsider doing in the future. I think this mostly affects developers who do not deal with node / npm much.

**Comment by jdalton** [comment]
Let's upgrade those deps and deps of deps :D

**Comment by renovera** [comment]
i have the same problem 
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
any idea? and how to upgrade lodash?
