### ISSUE TITLE
The migration docs should mention the difference between which properties lodash's and Underscore's _.clone method copies

### ISSUE THREAD

**Issue by ExplodingCabbage** [lodash/lodash#1679]
A colleague of mine just got bitten by a difference between lodash's `_.clone` and Underscore's `_.clone` that isn't mentioned at https://github.com/lodash/lodash/wiki/Migrating

He was using `_.clone` on an [Immutable JS](https://facebook.github.io/immutable-js/) Map object. (Yes, this was probably an entirely wrong thing to do in the first place.) With Underscore, this produced an object that retained all the methods of the original object. After swapping to Lodash, it produces an object without any Immutable JS methods.

While our particular use case was admittedly unique, there are probably more reasonable situations in which people could be bitten by the same behaviour difference.

I haven't looked at the code, but I'd guess that Underscore is copying all enumerable properties whereas lodash is copying all properties that are direct properties of the object and not of its prototype?

**Comment by d10** [comment]
lodash.clone returns `{}` when cloning functions since they can't be cloned. I'm not too sure, but this should be in a doc note somewhere.

**Comment by ExplodingCabbage** [comment]
> lodash.clone returns `{}` when cloning functions since they can't be cloned. I'm not too sure, but this should be in a doc note somewhere.

Underscore does the same thing; perhaps this is worth noting somewhere, but this isn't a lodash/Underscore incompatibility.

**Comment by jdalton** [comment]
> I haven't looked at the code, but I'd guess that Underscore is copying all enumerable properties whereas lodash is copying all properties that are direct properties of the object and not of its prototype?

That's correct.

**Comment by jdalton** [comment]
Your colleague can use [_.toPlainObject](https://lodash.com/docs#toPlainObject).

**Comment by jdalton** [comment]
Updated the wiki entry.
