### ISSUE TITLE
Feature suggestion: asymmetric size for _.chunk

### ISSUE THREAD

**Issue by jrencz** [lodash/lodash#1681]
Please consider the following case: I'm willing to chunk an array of 100 elements, but I want each element to be twice as big as the previous one so that after chunking:
- the first one has 5 elements
- the second one has 10
- the third+ ones have 20 each

Now `_.chunk` only allows to split evenly. Whet if it allowed to split unevenly? I don't yet know how to express the rule in a flexible way (maybe a numerical sequence?) but it looks to me like a nice improvement to what `_.chunk` can do now.

Real life example:
I'm batching elements of infinite scroll list. I want first chunk to be small, next one to be bigger and so on (with some limit off course)

**Comment by jdalton** [comment]
Hi @jrencz!

I think this would make a great [mixin](https://lodash.com/docs#mixin) to start out with.

**Comment by jrencz** [comment]
This definitely sounds like a plan.

**Comment by StreetStrider** [comment]
The good idea for implementation here is might be to allow `_.chunk` to accept sizing function in place of `size`. Such function must return size for the next chunk on each invocation. Such mixin can replace `_.chunk` because it's compatible with it.

**Comment by jdalton** [comment]
@StreetStrider 
> The good idea for implementation here is might be to allow `_.chunk` to accept sizing function in place of `size`. 

Yes! Like a `_.chunkWith`.
