### ISSUE TITLE
_.include finds numbers in strings

### ISSUE THREAD

**Issue by athomschke** [lodash/lodash#1682]
_.include('12345', 3) returns true, whereas http://ecma-international.org/ecma-262/6.0/#sec-samevaluezero states that types are included in matching elements.

However, _.include(_.toArray('12345'), 3) returns false, as expected.

Is that desired behavior?

**Comment by jdalton** [comment]
Hi @athomschke!

The `_.inculdes` method pulls double duty as [String#includes](http://ecma-international.org/ecma-262/6.0/#sec-string.prototype.includes) and `Array#includes` so when you pass a string it takes on the `String#includes` behavior.

**Comment by jdalton** [comment]
I'll add a doc note.

**Comment by leoselig** [comment]
>I'll add a doc note.
+1

**Comment by jdalton** [comment]
Added https://github.com/lodash/lodash/commit/1cbb6f1405c40a565255bd518bf19dc77a62e8b5.
