### ISSUE TITLE
Support for ECMA2015 classes in _functions()

### ISSUE THREAD

**Issue by mgoldsborough** [lodash/lodash#1683]
The _.functions() method does not support ECMA2015 classes.

For example:

```
// test.js
'use strict';

var EventEmitter = require('events'),
    _ = require('lodash');

class MyClass {
    constructor() {
    }

    foo() {
        console.dir('In foo()');
    }

    bar() {
        console.log('In bar()');
    }
}

var c = new MyClass();

console.dir(_.functions(c));
```

Results in an empty array. e.g.

```
$ node test
[]
```

I would expect this to return an array containing ```['foo', 'bar']```, right?

**Comment by jridgewell** [comment]
Related to https://github.com/lodash/lodash/issues/649

**Comment by jdalton** [comment]
Hi @mgoldsborough!

The `_.functions` method works on enumerable properties. A quick way to sanity check this is to use
`Object.keys(c)` and see if the keys are reported back,

**Comment by mgoldsborough** [comment]
```
// test.js
'use strict';

var EventEmitter = require('events'),
    _ = require('lodash');

class MyClass {
    constructor() {
    }

    foo() {
        console.dir('In foo()');
    }

    bar() {
        console.log('In bar()');
    }
}

var c = new MyClass();

console.log('Using lodash:');
console.dir(_.functions(c));

console.log('Using keys():');
console.dir(Object.keys(c));
```

Output:

```
Using lodash:
[]
Using keys():
[]
```

**Comment by jdalton** [comment]
Yep :)

**Comment by megawac** [comment]
@jdalton would an option be to call lodash functions explicitly (ala underscore) so that it makes it easier to override internal functionality? This would make `_.runInContext` far more useful as it could be used to tweak the functionality of the entire library (I wanted this functionality for `extend` and `merge`) for users that don't care about complete consistency/compatibility. E.g.

```js
var lodashProperties = require('lodash').runInContext();

lodashProperties.mixin({
  keys: function(obj) {
     return obj ? Object.getOwnPropertyNames(obj) : [];
  }
})
```

**Comment by jdalton** [comment]
@megawac Webpack's [NormalModuleReplacementPlugin](https://github.com/webpack/docs/wiki/list-of-plugins#normalmodulereplacementplugin) is great for that.

**Comment by megawac** [comment]
Sure, but I'm not using webpack and I think it should be considered for core functionality.

**Comment by megawac** [comment]
Also, it may be interesting to only allow `mixin` if the user does a `runInContext`

**Comment by jdalton** [comment]
> Also, it may be interesting to only allow `mixin` if the user does a `runInContext`

I can dig. That's something for v5 for sure.

**Comment by jdalton** [comment]
> Sure, but I'm not using webpack and I think it should be considered for core functionality.

Ya that starts to cause friction with lodash being modular (being anchored to a `_`) though I could build-step it away.

**Comment by megawac** [comment]
Yeah, I suppose it would have to rely on non modular build.

> I can dig. That's something for v5 for sure.

Yeah, definitely a v5+ thing.
