### ISSUE TITLE
New function: scan

### ISSUE THREAD

**Issue by andreasgruenh** [lodash/lodash#1684]
Hello everyone,

I just wanted to ask, if you ever thought about implementing haskells scanl function. It works like a fusion of map and reduce in the way, that every returned value of the function is added to the result array and the last result is available in that function. An example implementation could look a little like this:

    function scan(array, fn, seed, thisArg) {
      var accumulator = seed;
      var results = [];
      if (seed === undefined) {
        accumulator = _.head(array);
        array = _.tail(array);
      }
      results.push(accumulator);
      _.forEach(array, function (nextValue) {
        accumulator = fn.call(thisArg, accumulator, nextValue);
        results.push(accumulator);
      });
      return results;
    };

**Comment by jdalton** [comment]
Hi @andreasgruenh!

I'm totally open to it. I think I've seen similar requests before. Let's track the request to get a gauge on user demand for it.

**Comment by conradreuter** [comment]
:+1: (I'm the author of the given implementation)

**Comment by polkovnikov-ph** [comment]
:+1:

**Comment by tbindrup** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by jdalton** [comment]
@tbindrup lol, props for the big thumbs up.

**Comment by majorgilles** [comment]
:thumbs:

Would definitely be a nice addition

**Comment by kurzweil** [comment]
:thumbsup:

**Comment by mbixby** [comment]
👍

**Comment by jdalton** [comment]
Just a reminder you all need to use the [:+1: reaction](https://help.github.com/articles/about-discussions-in-issues-and-pull-requests/). The thumbs up emojis alone aren't counted by [the query](https://github.com/lodash/lodash/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc).

**Comment by polkovnikov-ph** [comment]
@jdalton AFAIR, reactions were added after this ticket was created. So even though there were votes you won't count them because you decided to use some new kind of a query?

**Comment by dmethvin** [comment]
@polkovnikov-ph there are dozens of requested enhancements in this repo. It is definitely possible for someone to write some more complex code to try and count thumbs up or "me too" comments--sounds like you want @jdalton to write that code.

However, consider this: Every time anyone comments on a ticket like this, the previous commenters are notified unless they've muted the thread. If they still want this feature they can just come back here and add their thumbs-up to the original requester's comment. As of now, some of the previous commenters like @mbixby have done that but for example you have not. Why ask someone else to do extra work when you haven't even taken the time to click?

**Comment by polkovnikov-ph** [comment]
@dmethvin I don't like when someone coerces a group of people to do useless actions due to his own arbitrary opinionated actions. It takes (i.e. wastes) asymptotically more time and is disrespectful. I feel no shame in being either the first or the only commenter to tell that, sorry.

**Comment by jdalton** [comment]
Sorry folks. Soapbox free zone here. Github gives me the option to sort by reactions so that's what I'm using. If they had other options I'd use that. Just a heads up I'm going to cut back the thread to before this jazz as it's derails a bit into a squabble.

**Comment by jdalton** [comment]
From time to time I also clean out the non-reaction based thumbs up as they're just noise.

**Comment by Izhaki** [comment]
One thing that is perhaps worth considering here is the actual API of scan.

You are proposing the most basic implementation, but [ramda](http://ramdajs.com/docs/#mapAccum) uses:

    (acc → x → (acc, y)) → acc → [x] → (acc, [y])

The first interesting to note is that the aggregator returns a tuple. The second is that the final return value also include the final accumulator, albeit the last value in `[y]`.

This is also the [implementation in haskell](http://hackage.haskell.org/package/base-4.7.0.1/docs/Data-List.html#v:mapAccumL), and there is some use cases for this api [are discussed here](https://github.com/ramda/ramda/issues/632).

This become of some interest to me whilst implementing a lazy tree - I had to deliberate on how to distinguish the mapped value and the children accumulator, and the api above solves it quite neatly.

**Comment by devdoomari** [comment]
@jdalton is this the right way to do it?
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 
is this 1 vote or a lot of votes?

**Comment by leontastic** [comment]
A functional ES6 implementation of `scan` for arrays:

```javascript
const scan = (arr, reducer, seed) => {
  return arr.reduce(([acc, result], value, index) => {
    acc = reducer(acc, value, index);
    result.push(acc);
    return [acc, result];
  }, [seed, []])[1];
};
```

Example usage:

```javascript
scan([1, 2, 3, 4, 5], (total, num) => total + num, 0)
// [1, 3, 6, 10, 15]
```

**Comment by polkovnikov-ph** [comment]
@leontastic It's a bad idea to use `reduce` and other built-in methods, because they're [extremely slow](https://jsperf.com/foreach-vs-reduce-vs-for-loop).

**Comment by leontastic** [comment]
@polkovnikov-ph You're right, using native `reduce` is ~30% slower than `for` loops as given in the implementation above. Here's a test directly comparing the two implementations: https://jsperf.com/scan-for-loops-vs-native-reduce

**Comment by polkovnikov-ph** [comment]
@leontastic You're using `fn.call(...)`, which is the source of lag this time. `_.forEach` is not fast. Having a pre-sized array of the same size as input would be several times faster than `results.push`. The call to `_.tail` is `O(n)` unless JS implementation uses deques instead of arrays. You shouldn't use `undefined` in library code, because in non-strict mode it may be `var undefined = true;`. `void 0` is preferred both due to being stable and shorter.

**Comment by leontastic** [comment]
I copied and pasted the implementation posted by @andreasgruenh. I didn't try to optimize it, but I'd love to see a JSPerf of a more performant `scan` if you'd like to take a stab at it.

**Comment by andreasgruenh** [comment]
@polkovnikov-ph I really don't think, that `array[array.length - 1]`, which is  roughly what `tail` does, really needs  `O(n)`. On top of that, we should rather discuss, whether the function itself is useful for the lodash package (making it bigger), as you can implement it pretty easily with other lodash functions.

**Comment by polkovnikov-ph** [comment]
@andreasgruenh This is in no way what `tail` does. I'm afraid you've mistaken `array[array.length - 1]` with `array.slice(1)` or `array.shift()`.

You can implement pretty easily all the functions, including `scan`, but as you clearly see @leontastic and you failed to do it properly. Why do you expect other people to do it right?

**Comment by andreasgruenh** [comment]
Oh yeah, you're right, I was thinking about `_.last`.
The current version  of lodash does not take a `thisArg` in other functions so I think we can skip this.

**Comment by polkovnikov-ph** [comment]
Just for the sake of completeness of disussion:

1. Previous solutions act differently when there is no `seed` and array is empty. We should figure out what's the correct answer in this case. I'd prefer a `throw`.

2. To cut on amount of code we could pessimize calls to `scan` without `seed`. These calls are rare in my code, but I'm not sure about others.

```javascript
function scan(array, fn, seed) {
    if (seed === void 0) return scan(seed = array.shift(), fn, seed, thisArg);
    var size = array.length, results = Array(size + 1), i;
    for (i = 0; i < size; ++i) {
        results[i] = seed;
        seed = fn(seed, array[i]);
    }
    results[i] = seed;
    return results;
}
```

3. To optimize performance we could use original array. The only problem is that we cannot store `seed`.

```javascript
function scanish(array, fn, accumulator, thisArg) {
    if (thisArg) fn = fn.bind(thisArg);
    for (var i = 0, size = array.length; i < size; ++i) {
        array[i] = accumulator = fn(accumulator, array[i]);
    }
    return accumulator;
}
```
