### ISSUE TITLE
_.set creates arrays when sees integres in paths (and this weird behaviour isn't documented)

### ISSUE THREAD

**Issue by mik01aj** [lodash/lodash#1685]
I just spent almost an hour debugging this.

```
var obj = {};
_.set(obj, ['collection', 1170798506, 'stuff'], 'value');
console.log(obj);
```

When I run this in Node, it hangs and then crashes. When I run this in browser, it works fine.

The problem is that when `_.set` sees an integer in path, it creates an array, and when Node's `console.log` sees that `obj.collection.length` is 1170798507, it hangs and then crashes saying "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory".

I can understand that this behaviour is usually convenient, but in situations like this it can cause major pain. I'd actually expect `_.set` to always create plain objects, but creating arrays would also be fine for me **as long as it's documented**.

**Comment by jdalton** [comment]
Hi @mik01aj!

In v4 (due in Jan) we've added `_.setWith` to allow customization of values created.
I'll add a doc note on the array creation behavior.

**Comment by megawac** [comment]
@jdalton slightly related on the topic of array setting `set( <array>, <path>, <val> )`, I think there should be a way to denote the next element (i.e. push)

**Comment by jdalton** [comment]
> I think there should be a way to denote the next element (i.e. push)

Ya, that's been brought up a couple times. I've been avoiding it because tips things it complicates things a bit more.

**Comment by mik01aj** [comment]
@megawac I think you could do this with `_.setWith` (then the adding logic is up to you).

**Comment by jdalton** [comment]
@mik01aj
> @megawac I think you could do this with `_.setWith` (then the adding logic is up to you).

Oh snao!

**Comment by megawac** [comment]
> @megawac <https://github.com/megawac> I think you could do this
with _.setWith(then the adding logic is up to you

Yeah, I'm just anticipating this to be a common request
