### ISSUE TITLE
Undeprecate older lodash versions on npm

### ISSUE THREAD

**Issue by phated** [lodash/lodash#1686]
The issue https://github.com/npm/npmlog/issues/25 was closed as won't fix and breaks Windows environments.  The deprecation command can be undone in npm so I think it should be until Windows or npm changes their behavior.

Ref https://github.com/gulpjs/glob-watcher/issues/23
Ref https://github.com/shama/gaze/issues/207
Ref https://github.com/cowboy/node-globule/pull/22

None of which will be fixed anytime soon and it's actually lodash that broke Windows users.

**Comment by jdalton** [comment]
\cc @othiym23.

**Comment by jdalton** [comment]
@phated Is the deprecation message that's causing issues just for `lodash` or is the ones for `lodash-node` and `lodash-amd` also issues?

**Comment by jdalton** [comment]
For what it's worth I tried to un-deprecate with an empty message and npm errors:
```bash
npm deprecate lodash@"<3.0.0||0.5.0-rc.1||<=1.0.0-rc.3" ""
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "deprecate" "lodash@<3.0.0||0.5.0-rc.1||<=1.0.0-rc.3" ""
npm ERR! node v5.1.0
npm ERR! npm  v2.14.11
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 0.1.0." : lodash
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

**Comment by aredridel** [comment]
You can remove deprecation by setting it to `''` AFAIK

**Comment by jdalton** [comment]
@aredridel Yep, I've tried passing it `''` and it errors with the message above.

**Comment by jdalton** [comment]
@phated I don't think these are build fails on Windows and just the normal deprecation warning complaints (which is fine). I'll close this until a critical issue, like build fails, pops up.

The npm issue with not being able to un-deprecate still exists though so should continue to be tracked on their end.

**Comment by phated** [comment]
Sounds good!  I will keep closing the annoying issues as invalid :wink:

**Comment by jdalton** [comment]
> Sounds good!  I will keep closing the annoying issues as invalid :wink: 

To nudge folks in the right direction for upgrading you can point them to our 3.0 [release notes](https://github.com/lodash/lodash/releases/tag/3.0.0), [changelog entry](https://github.com/lodash/lodash/wiki/Changelog#v300), and [lodash-migrate](https://www.npmjs.com/package/lodash-migrate).

**Comment by SgtPooki** [comment]
@phated be sure to inform the annoying issue openers instead of annoyingly closing the issue without sharing your knowledge ;) It will help to reduce the number of annoying issues opened.

**Comment by SgtPooki** [comment]
Deprecation is a good thing, and old ass packages should not be undeprecated unless they're a critical issue that is breaking an ecosystem. You should not be ignoring the fact that you're using extremely old and stale versions of a package. That is what is wrong with the JavaScript/Node community and why most people think Node will fail. 

PSA: Node will fail if people continue with that attitude. Look at Python 3.

**Comment by jdalton** [comment]
@SgtPooki  I donno about all that.

@phated The npm issue with un-deprecating packages is now resolved.
