### ISSUE TITLE
issue/bug with partial

### ISSUE THREAD

**Issue by bijoythomas** [lodash/lodash#1687]
I'm not sure if this is a bug or I'm doing something weird, but running below in the NodeJS (v0.12.0) prompt shows

> ['1', '2', '3', '4', '5', '7'].every(function(d) {return lodash.contains('712345', d);})
true

> ['1', '2', '3', '4', '5', '7'].every(lodash.partial(lodash.contains, '712345'))
false

Why is the behavior different?

**Comment by jdalton** [comment]
This is because `_.contains` accepts a `fromIndex` argument which is now getting populated by the `index` param of the `_.every` iteratee. You can resolve this using  a placeholder
```js
['1', '2', '3', '4', '5', '7'].every(lodash.partial(lodash.contains, '712345', lodash, 0))
```

**Comment by bijoythomas** [comment]
Thank You. I overlooked that third argument :-)
