### ISSUE TITLE
problem with words

### ISSUE THREAD

**Issue by seeden** [lodash/lodash#1689]
For

```js
import words from 'lodash/string/words';

words('Mikuláš');
```
I will get

```js
['Mikulá']
```

As you can see there is missing latest letter
I am using latest lodash 3.10.1

**Comment by AlcaDesign** [comment]
This issue has since been resolved. (I think in this commit: e9bfaa7d51b985684ed907d58faff8d3b32c4355)

```javascript
_.words('Mikuláš');
// ["Mikuláš"]
```

**Comment by seeden** [comment]
I think that you are wrong.
I have this issue in latest version 3.10.1

**Comment by AlcaDesign** [comment]
v3.10.1 was released in August but the referenced commit is from September.

**Comment by seeden** [comment]
I see. Thanks @AlcaDesign. Do you know why they stopped with releases ?

**Comment by d10** [comment]
lodash has not stopped releasing, we've still been developing actively; adding new features and cleaning our API in preparation for lodash v4, due out in January.

**Comment by seeden** [comment]
I saw that you fixed tons of bugs from August. I am happy but your library are using thousands of developers. And a lot of them are using your latest released version which is 4 months old. Do you have any special reason why you are not releasing a new version when you fix reported bug? It is not very easy to find issues in your backlog. Yes we can use latest #commit but it is mess. Thanks

**Comment by jdalton** [comment]
Hi @seeden! I'm not a fan of the 1 fix 1 release style package management. Lodash has several builds (which will be reduced in v4) when require more effort than a simple `npm publish` command. I like to let things settle and stabilize a bit. So when not prepping for a major release the bug fix and minor releases come at bi-weekly or monthly intervals. However, with heads down on a major release they tend to drag as backcompat changes make it harder to rewind and publish.
