### ISSUE TITLE
mapValues for objects

### ISSUE THREAD

**Issue by kennknowles** [lodash/lodash#169]
Hello!

Any chance of including `mapValues` into lodash? This would be a function that produces a new object by applying a function to each of the values contained in a source object.

I'll reproduce the code from documentcloud/underscore#220 here:

``` javascript
_.mixin({
  mapValues: function (input, mapper, context) {
    return _.reduce(input, function (obj, v, k) {
      obj[k] = mapper.call(context, v, k, input);
      return obj;
    }, {}, context);
  }
});
```

I don't have strong feelings about the idiomatic way to implement the function, but it should behave as this pseudocode:

```
onSecond f (x, y) = (x, f y)
_.mapValues f = _.object ∘ _.map (onSecond f)  ∘ _.pairs
```

This would definitely fall under "consistency" and "extra features" relative to underscore. It is small but I don't want to copy it everywhere or maintain a fork of either project. There's plenty of discussion on the other ticket, if you like.

 -- Kenn

**Comment by MattyKuzyk** [comment]
+1 for mapKeys, ran into an issue today where this would be useful.

**Comment by jdalton** [comment]
I can dig it, probably easy enough to tackle `mapKeys` and `mapValues` with an internal creator function to reduce code duplication.

**Comment by ahdinosaur** [comment]
:+1: for `mapKeys` and thanks for adding `mapValues`. :smile_cat:

**Comment by davidkpiano** [comment]
Another +1 for `mapKeys()` please =)

**Comment by jdalton** [comment]
I'll add it to the roadmap to tackle after our 3.7 release.

**Comment by sholladay** [comment]
When `mapKeys()` is implemented, I would _really_ appreciate a convenient way to specify a list of `from`/`to` keys.

For example:
````javascript
var start = {a: 1, b: 2, c: 3, d: 4},
      changes = {a: 'e', b: 'f', c: 'g'},
      end = _.mapKeys(start, changes);  // => {d: 4, e: 1, f: 2, g: 3}
````

Would save a lot of trouble for me and could hopefully be optimized much better than what we could do in the callback.

**Comment by whather** [comment]
+1 for _.mapKeys
