### ISSUE TITLE
_(obj).omit() call with wrapped object

### ISSUE THREAD

**Issue by hinell** [lodash/lodash#1691]
Works fine:
```javascript
var obj = {foo: 'foo', bar:'bar', zzz: 'bar'};
_.omit(obj,'bar') // => {foo: "foo", zzz: "zzz"}
```
But these two don't:
```javascript
_(obj).omit('bar');
_.chain(obj).omit('bar')
```
There is obviously expected the obj with the 'foo' and 'zzz'  properties are not omitted
but in both calls the same lodash wrapper is returned. 
Second case also has a  \_\_chain\_\_ property's value assigned to the true,
while of the first case it is not. Docs say the omit() is chainable.
Don't know exactly bug :bug: or feature. Help is needed.:)

Lodash version 3.10.1
Tested in Chrome 48.0.2564.22 dev-m (64-bit)

**Comment by jdalton** [comment]
This looks to work fine. The method is chainable. To resolve a chain you need to call the `.value()`:
```js
_(obj).omit('bar').value();
```
