### ISSUE TITLE
_.max bug?

### ISSUE THREAD

**Issue by scriptguru** [lodash/lodash#1692]
```js
		function maxChannelDifference(arr1, arr2, debug){
			if( debug ){
				console.log('maxChannelDifference');
				console.log( arr1 );
				console.log( arr2 );
			}
			return _.max(
				arr1,
				function(val, index){
					if( debug ) console.log([ val, arr2[ index ], val - arr2[ index ] ]);
					return Math.abs( val - arr2[ index ] );
				}
			);
		}
```
being called with parameters
`[126, 56, 120, 255], [126, 56, 120, 255], true`
returns 126, while it should be 0

The logs are:
```js		
		maxChannelDifference
		[126, 56, 120, 255]
		[126, 56, 120, 255]
		[126, 126, 0]
		[56, 56, 0]
		[120, 120, 0]
		[255, 255, 0]
```

Checked it 5 times, can't see an error in my code, so I guess the problem could be in `_.max`?

**Comment by jdalton** [comment]
Hi @scriptguru! 

The `iteratee` is used to generate the value by which the max value is computed but does not transform the value.

**Comment by scriptguru** [comment]
Thanks, got it!
I did not think that it would transform the value, but because of some bug in my brains I still thought it should return the value generated by `iteratee`.

**Comment by StreetStrider** [comment]
@scriptguru, well technically you're right, the return value is used, but not as «value» but as «key-to-sort-by» thing.
```js
_.max(['small value','big value'], _.constant(0))
```
