### ISSUE TITLE
isFunction for NPMethod

### ISSUE THREAD

**Issue by nikravi** [lodash/lodash#1694]
Hello,

The function `_.isFunction` returns false for methods defined by QuickTime player. While I obey that html5 video tag is the future, the reality is that quick time player is still around. Can lodash support 'object NPMethod' as valid function? or, maybe, add _.isNPMethod?

<img width="703" alt="screen shot 2015-12-09 at 9 07 27 am" src="https://cloud.githubusercontent.com/assets/911849/11687384/67215afc-9e54-11e5-88f7-ebfd775fc249.png">

To see this in action, add 

```html
<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" height="100%" width="100%" id="videoViewPort" scale="Aspect">
<param name="autoplay" value="false">
<param name="enablejavascript" value="true">
<param name="postdomevents" value="true">
<param name="src" value="http://url-to-file.mov">
<embed src="http://url-to-file.mov" height="100%" width="100%" type="video/quicktime" scale="Aspect" pluginspage="http://www.apple.com/quicktime/download/" enablejavascript="true" postdomevents="true" autoplay="false" name="videoViewPort"></object>
```
then `document.videoViewPort.SetURL` would be defined, but `_.isFunction(document.videoViewPort.SetURL) === false`.

Thank you for great work

**Comment by rafde** [comment]
You could always create your mixin for this
```
_.mixin({ 
  'isNPMethod': function(obj){ 
    return Object.prototype.toString(obj) === '[object NPMethod]'; 
  } 
});
```
considering how niche this request is.

**Comment by jdalton** [comment]
Hi @nikravi!

Host objects and host methods have a history of not playing by the conventions of the language. In this case our `_.isFunction` method is doing it's job and the host method is reporting things incorrectly. @rafde is right that a mixin is the way to go.
