### ISSUE TITLE
Deprecation warning should expose offending package name

### ISSUE THREAD

**Issue by Rleahy22** [lodash/lodash#1695]
It would be more helpful if if a dependency has an old version of lodash the deprecation warning included the name of that dependency to make it easier to take action.

**Comment by jdalton** [comment]
Hi @Rleahy22!

That's out of our hands. You may want to request this over on [npm's issue tracker](https://github.com/npm/npm/issues).

**Comment by Rleahy22** [comment]
Figured that'd be the case, but might as well ask : )
