### ISSUE TITLE
Question: immutable version of _.set

### ISSUE THREAD

**Issue by rstacruz** [lodash/lodash#1696]
Is there an immutable version for `_.set`? It's currently mutative, like how this will modify `obj`:

```js
obj = { user: { name: 'john', email: 'john@example.com' }}
obj2 = _.set(obj, 'user.name', 'jake')

console.log(obj)    //=> { user: { name: 'jake', email: 'john@example.com' }}
console.log(obj2)   //=> undefined
```

Immutable.js has a `setIn` method, which does the same but ensures that new objects/arrays are created when necessary. It seems like a perfect fit for Lodash:
```js
// hypothetical example
obj = { user: { name: 'john', email: 'john@example.com' }}
obj2 = _.setIn(obj, 'user.name', 'jake')

console.log(obj)    //=> { user: { name: 'john', email: 'john@example.com' }}
console.log(obj2)   //=> { user: { name: 'jake', email: 'john@example.com' }}
```

**Comment by jdalton** [comment]
There isn't an immutable form in `lodash` yet though in v4 there will be as part of the `require('lodash/fp')()` command.

**Comment by rgbkrk** [comment]
Is this expected behavior for `_.set` with lodash fp mode?

```
> object = _.set(object, 'a[0].b.c', 4);
{ [Number: 4] '5': 'a[0].b.c' }
> var object = { 'a': [{ 'b': { 'c': 3 } }] };
undefined
> object = _.set(object, 'a[0].b.c', 4);
{ [Number: 4] 'object Object': 'a[0].b.c' }
```

**Comment by rgbkrk** [comment]
Oh I see, it's iteratee first. You can't swap lodash code out for lodash/fp code.

**Comment by rgbkrk** [comment]
Note for random folks who end up here (I sure did):

When using `_.set` from lodash/fp with Redux style state setting, it looks like:

```
_.set(value, path, state)
``` 

whereas if you're transitioning from using/thinking with Immutable.js it would be:

```
return state.setIn(path, value)
```

**Comment by jvitela** [comment]
With Lodash 4 the correct way to update the state for Redux is using setWith function:

`const newState  = _.setWith(_.clone(state), 'users.user01.name.first', 'John Doe', _.clone);`

This will shallow clone only the objects in the path that changed

**Comment by SneakyMax** [comment]
Building on @jvitela's answer, here's a `lodash/fp`-like version of the above code (w/ es6 modules):

```
import { clone, setWith, curry } from 'lodash/fp';
export const setIn = curry( ( path, value, obj ) => setWith( clone, path, value, clone( obj ) ) );
```

**Comment by VictorQueiroz** [comment]
The problem is that these methods mutate the object. Should be an environment option or even a immutable option like `lodash/immutable` for Lodash to behave differently

**Comment by erquhart** [comment]
With the spread operator (requires a polyfill in IE11 and Node 4 - [source](https://kangax.github.io/compat-table/es6/#test-spread_(...)_operator)):

```js
const newObject = set({ ...oldObject }, ['path', 'to', 'change'], 'new value');
```

**Comment by jeremejevs** [comment]
If you're using TypeScript, you should consider utilizing some standalone typing-aware "immutable set" library, like [monolite](https://github.com/kube/monolite) or [immutable-assign](https://github.com/engineforce/ImmutableAssign).
