### ISSUE TITLE
_.unset issue with arrays

### ISSUE THREAD

**Issue by NinjaBanjo** [lodash/lodash#1697]
When using _.unset with an array item (ie. _.unset(obj, 'key[0]') the length of the array isn't updated due to use of the delete operator causing unexpected results.

**Comment by jdalton** [comment]
The `_.unset` method is in the unreleased WIP of v4. It's intended as an Objects category method. Technically it is unsetting the value and creating a hole in the array. I'll look in to adding an `_.unsetWith` to allow customization.

**Comment by NinjaBanjo** [comment]
Could one check the last char of the key string for a `] ` and use slice
instead?

On Thu, Dec 10, 2015, 12:10 John-David Dalton <notifications@github.com>
wrote:

> The _.unset method is in the unreleased WIP of v4. It's intended as an
> Objects category method. Technically it is unsetting the value and creating
> a hole in the array. I'll look in to adding an _.unsetWith to allow
> customization.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lodash/lodash/issues/1697#issuecomment-163705750>.
>
-- 


- Derek Persons
Sent from my Android device

**Comment by jdalton** [comment]
That won't do because bracket notation is valid for all objects, not just arrays.

**Comment by Omniroot** [comment]
I'm having troubles with this as well. It seems that this would be a standard use case. Here is my code:
```
let d = {'a': ['b', 'c']};
_.unset(d, ['a', '0']);
```
now d.a is left having the length property set to 2.

**Comment by jdalton** [comment]
@Omniroot That's because you've created a sparse array.

**Comment by br0wn** [comment]
Hi! I just came around the same issue as here. I was wondering would it be possible to add a special case for handling arrays. I see from the source that `unset` uses `baseUnset`
```javascript
function baseUnset(object, path) {
      path = castPath(path, object);
      object = parent(object, path);
      return object == null || delete object[toKey(last(path))];
}
```
Would it be possible to add a check if parent is an array and then doing splice on it ? Something like this?
```javascript
function baseUnset(object, path) {
      path = castPath(path, object);
      object = parent(object, path);

      // --- add
      if( Array.isArray( object ) ){
            object.splice(toKey(last(path)), 1);
            return true;
      }
      // --- 

      return object == null || delete object[toKey(last(path))];
}
```

**Comment by jdalton** [comment]
Unset unsets a property. It's not splicing an array. I have no desire to mix array/object mutation here.

**Comment by br0wn** [comment]
```
Unset unsets a property. It's not splicing an array. I have no desire to mix array/object mutation here.
```
I would argue semantics but you've set your mind. Then, would it be possible to provide a general use method like that? It really comes in handy to have set/unset methods that work general for objects and arrays alike (when handling dynamic structures for instance) :)

Or perhaps expose methods for getting the parent of property at `path` and part/slice of the path? This would make custom implementation easier.
