### ISSUE TITLE
FB Flowtype declarations?

### ISSUE THREAD

**Issue by magicpat** [lodash/lodash#1698]
Hi,
I wondered if lodash ever planned to support Facebook's flowtype by providing a declaration file, or if there are any problems in doing so?

Would definitely contribute to this, if I can get a grasp on how to integrate the results into the project ;-)

**Comment by jdalton** [comment]
I'm not aware of any. We haven't tackled supporting them in core at the moment.
I know for TypeScript at least there's [DefinitelyTyped](https://github.com/DefinitelyTyped).

**Comment by ctrlplusb** [comment]
For people who find this issue via google, check here: https://github.com/marudor/flowInterfaces

**Comment by martinschayna** [comment]
For people who find this issue via google, part 2, check here: https://github.com/flowtype/flow-typed/

**Comment by darky** [comment]
@martinschayna, sorry, but at this moment flow-typed lodash definitions sucks, even, ramda better here.

**Comment by maximderbin** [comment]
+1
