### ISSUE TITLE
splitBy

### ISSUE THREAD

**Issue by pistacchio** [lodash/lodash#1700]
Hi,
I think a function that would turn out to be quite useful in many situations is "split by" that splits an array in chunks based on the application of a function to each item of the array. It is a sort of repeated "takeWhile". This is a very rough implementation just to serve as an example of what I mean

    const splitBy = (arr, fn) => {
        const _splitBy = (_arr) => {
            const taken = _.takeWhile(_.last(_arr), fn);

            if (_.isEmpty(taken)) return _.reject(_arr, _.isEmpty);

            let rest  = _.dropWhile(_.last(_arr), fn);
            rest      = !fn(rest[0]) ? _.rest(rest) : rest;

            return _splitBy(_.initial(_arr).concat([taken, rest]))
        }
        return _splitBy([arr])
    };

    splitBy([1, 2, 3, 0, 4, 0, 5, 6, 7, 0, 8], i => i === 0) => [[1, 2, 3], [4], [5, 6, 7], [8]]

**Comment by jdalton** [comment]
Hi @pistacchio! I'll count this has a :+1: for https://github.com/lodash/lodash/issues/1379.

**Comment by ahuff44** [comment]
I'd love to see this implemented into lodash
