### ISSUE TITLE
Feature Request: _.move() element in an array

### ISSUE THREAD

**Issue by blindstuff** [lodash/lodash#1701]
I needed this in the implementation of a drag and drop gallery and found it was not on the lodash docs. If this already exists or is implemented in a different way I apologize as I could not find it.

A simple method to move an element inside of an array from one position to another.

````
_.move = function(array,fromIndex,toIndex){
    array.splice(toIndex, 0, array.splice(fromIndex, 1)[0] );
}
````
Example usage
````
_.move([1,2,3,4,5],0,2);
// -> [2,3,1,4,5]
````

Solution taken from (and more detail / verifications needed available at):
http://stackoverflow.com/a/5306832/474883

**Comment by jdalton** [comment]
Hey @blindstuff!

This looks like a nice complement to the [_.insert](https://github.com/lodash/lodash/issues/890) proposal.
While working with `splice` is a bit cumbersome I'll defer to it until there's more user demand for these methods.

**Comment by granteagon** [comment]
I did this too, but in a pure function (doesn't affect arguments) in #1978 jdalton referenced above.

**Comment by dropfen** [comment]
This is would be a nice feature, implementation example as a pure function
https://gist.github.com/dropfen/827ebf5110a154551f0ea5df7f8f222b

**Comment by granteagon** [comment]
I created a repo with simple tests [here](https://github.com/granteagon/move).  Hope it helps.

**Comment by granteagon** [comment]
Also just published `lodash-move` on npm.

**Comment by superandrew213** [comment]
+1

**Comment by jtheoof** [comment]
[As noted](https://github.com/lodash/lodash/issues/1978#issuecomment-225573475) by @granteagon, this would be a nice touch for drag and drops :)

**Comment by c-dante** [comment]
Would it make more sense to just add a permutation function? Reorders arrays based on a permutation function or re-index array? Maybe a list of swaps to perform or what have you?

```js
const arr = [1, 2, 3, 4, 5]
_.permute(arr, [0, 2, 1, 3, 4]); // [1, 3, 2, 4, 5]

const fn = (idx) => idx + 1;
_.permute(arr, fn); // [_, 1, 2, 3, 4, 5] ?
```

No matter what, questions are:
* What do you expect to happen if you move out of bounds?
* What happens if you move multiple elements to the same index?
* Can you only do 1 swap at a time?
* Does it make sense to just be `_.move(arr, fromIdx, toIdx)` or something more... useful?

**Comment by granteagon** [comment]
@c-dante I think undefined stuff should either raise an error or just insert undefined values.  I like the permute idea, but a definite flaw I see is the array move is hand coded.  If you were to use it in real code, wouldn't you still need to `.slice()` or something to get the array of numbers illustrated above?

**Comment by c-dante** [comment]
You can implement it in a few ways -- especially since you're creating a new array each time.

Your implementation uses spread a bunch to reorder it, you could use the permute array to select elements, I'd avoid `slice` since it mutates the input (although that might be desired in some cases).

Yes, my example is hard coded, but there's no reason you the signature has to be that. Second example is a mapping function that goes from old to new index. Alternatively, you can have a vararg of swaps.

```js
_.permute(arr, newIndices);
_.permute(arr, ...swaps);
_.permute(arr, mapFn);
```

are a few signiture ideas.

**Comment by jtheoof** [comment]
I like the `_.permute` idea as well as long as it remains easy for "simple swaps" (drag and drops). But it looks like `_.permute(arr, ...swaps)` has this covered.

**Comment by granteagon** [comment]
Interesting.  That would still work for the drag n' drop examples above so I'm good.  `permute` is a better name than `arrayMove` IMO.

**Comment by DrogoNevets** [comment]
+1

**Comment by granteagon** [comment]
@c-dante et. al, I created a _.permute mixin on github and npm you can find here: https://github.com/granteagon/lodash-permute

Feedback welcome!

**Comment by PatrickWilding** [comment]
@c-dante `slice` doesn't mutate the input.

**Comment by eMarek** [comment]
Anyone, why `move` function is still not a part of lodash?

**Comment by granteagon** [comment]
@eMarek https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests

**Comment by BrunnerLivio** [comment]
Does this feature request still don't have enough likes? Whats the state?

**Comment by charlieclark** [comment]
Using https://www.npmjs.com/package/lodash-move in the meantime but would love to see this in lodash officially!

**Comment by stepovat** [comment]
how many likes should we gather

**Comment by jdalton** [comment]
@stepovat There is no set number. Likes are used as an indicator of popularity of a request to help make API decisions as they come.

**Comment by DrJonnie** [comment]
Would be a nice feature!

**Comment by granteagon** [comment]
_.permute is probably the better one to use if it does get added eventually.

**Comment by matheo** [comment]
@jdalton This seems quite popular and have a mixin already, and still no joy? wow

**Comment by lyle45** [comment]
this would be useful and should be very simple to implement. also an api for `_.swap(array, index1, index2)` would be very useful and shouldn't be to hard to implement

**Comment by granteagon** [comment]
@lyle45 agreed.  Very useful for drag and drop.  Just not sure that the bloat to the base library is necessary. 

To me, the question is how many different kinds of apps need these two bits of functionality.  The only time I've required it is in implementing drag/drop on a list.  I'm not sure there are greater than 10-15% of apps that have something like that.  So I understand why it hasn't been added yet.

It's a balancing act.  I'm sure @jdalton is just guarding against excessive bloat.

**Comment by bravecow** [comment]
Would be nice for drag and drop 👍

**Comment by CalebKester** [comment]
What we're wanting is the befit knowing that lodash is the #1 function library and everything there is rock solid with no worries about the maintainer/bugs.

With module loading in it adds zero bloat if you only load in what you need. Sure not everyone who uses lodash uses it (I'm sure it's a low adoption rate). It'd be great if lodash would be able to add in these functions that would even be helpful if 10-15% of it's users wanted it but would only be available for module loading.

**Comment by granteagon** [comment]
@CalebKester 0.00022552099920371465% usage on NPM in the past month.  Lodash is one of, if not the most, popular library on NPM.

![image](https://user-images.githubusercontent.com/133823/36453144-1056516a-1665-11e8-9510-b72f924e86ea.png)
![image](https://user-images.githubusercontent.com/133823/36453171-23e6b0bc-1665-11e8-90e2-29e6cfa6d978.png)

**Comment by CalebKester** [comment]
And it deserves it.

I just put my thumbs up here to be a stat. I appreciate all the team does.

**Comment by gardezii** [comment]
+1

**Comment by brianespinosa** [comment]
@jdalton I feel like it is worth noting that this issue is the highest ranked feature request in the closed backlog based on reactions: https://github.com/lodash/lodash/issues?q=is%3Aissue+is%3Aclosed+sort%3Areactions-%2B1-desc

Thanks for all your work on lodash and esm. 👏

**Comment by matheo** [comment]
@brianespinosa he went pretty inactive around April, this needs some community love :\

**Comment by jdalton** [comment]
![](https://user-images.githubusercontent.com/4303/60943155-df350280-a299-11e9-8bdf-36aea7bedec0.gif)

**Comment by iwan-aucamp-emerson** [comment]
Ramda provides a move function: https://ramdajs.com/docs/#move

**Comment by MadDeveloper** [comment]
https://github.com/ramda/ramda/blob/master/source/move.js

**Comment by pycraft114** [comment]
is ```move``` function implemented?

**Comment by jdalton** [comment]
@pycraft114 Nope.

**Comment by c-dante** [comment]
@pycraft114 check out #89 for the open thread.

**Comment by Dmitra** [comment]
popular alternative https://www.npmjs.com/package/array-move

**Comment by ImanMahmoudinasab** [comment]
@jdalton Long time and numerous votes, isn't it time to implement this function? I can do that if you think votes are enough.

**Comment by papeloto** [comment]
This seems like a no-brainer to add :heart:

**Comment by QuotableWater7** [comment]
Came here today for this 😢

**Comment by marcnewton** [comment]
5 Years later from original thread, still nothing accomplished?

**Comment by djmisterjon** [comment]
heuuum serious, no swap sugar coding ??? common

**Comment by OrbitalJeffL** [comment]
Nothing yet?

**Comment by villeneuve-michael** [comment]
Would love to see it in #2020

**Comment by nzayatz14** [comment]
I also, would enjoy this

**Comment by MitchellBouwman** [comment]
Hi from 2020!

<img src="https://media4.giphy.com/media/9SIXFu7bIUYHhFc19G/giphy-downsized-medium.gif">

**Comment by hiporox** [comment]
Bumping this again, 🤞 we get this in 2021

**Comment by mustkem** [comment]
As Yoda says - Always hope, there is

**Comment by darkguy2008** [comment]
2021, nothing yet? Whoa, 5+ years and no work on this so far...

**Comment by Abdulmanan0315** [comment]
Still looking for this feature to be implemented. Please loadash make a move.

**Comment by Abdulmanan0315** [comment]
As drag and drop features using the help of array and objects are more on the boat, So this should be implemented

**Comment by gzapata2** [comment]
I would love to see this.

**Comment by broofa** [comment]
@jdalton: Landed on this issue after reading about "lodash style issue management" in the 11ty repo ([here](https://github.com/11ty/eleventy/issues/108#issuecomment-386182137), specifically).   I like the concept, but came here to see how it's working for you.

Given that this issue (top-voted FR for several years) hasn't been acted on, does that mean you've given up on [this practice](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests)?  Would you recommend it for other projects?  Any caveats or pitfalls to be aware of?

**Comment by spierala** [comment]
Is lodash still actively developed? 

2 commits on master in 2021 let me doubt a bit (https://github.com/lodash/lodash/commits/master)

**Comment by koolamusic** [comment]
shocked this hasn't made it yet

**Comment by LuciKritZ** [comment]
This is a very important feature and it will actually be used in a lot of implementations. Still waiting.... :)

**Comment by Vincz** [comment]
Same here. Would love to see this feature.

**Comment by Yorksh1re** [comment]
I'm waiting, too...

**Comment by gvolluz** [comment]
Well... I have exactly that kind of thing to 'build', which is of course a no brainer, but thought 'oh well, maybe lodash...' 

and there is a request, many people, since 2015... come on guys, in what strange world would _.move or _.permute be *bloating* the library, when you have such things as _.isNull that brings 0 thing to the world 😄

**Comment by AndrewKiri** [comment]
It would be a very much handy function to have as a part of lodash...

**Comment by riotrah** [comment]
Hi, please forgive if "bump+1" comments on issues is the wrong kind of vote (per your docs), but am not sure given the radio silence - so I'm adding both.

I also wanted to also thank you (the maintainers) and y'all(?) (the community) so damn much for creating and maintaining js' missing standard library, and pushing the js world further into the world of immutable fn-ish programming - I know I personally owe a lot of my love for that world (and transition into clojure prob lol) to lodash.

**Comment by c0ncentus** [comment]
move will be helpfull for slide component... 
live exemple here : 
https://persona-dance.jp/p3d/character/

tricky animation you know : / .

**Comment by sarab5000** [comment]
The corona came and is almost gone and we are still waiting..

**Comment by ImanMahmoudinasab** [comment]
> This looks like a nice complement to the `_.insert` proposal. While working with `splice` is a bit cumbersome I'll defer to it for now. We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

@jdalton How many reactions would be considered as **popular**? And if you see it as a popular request now, would be there any plan to implement this?

**Comment by chadwtaylor** [comment]
+1

**Comment by MSerj** [comment]
Seriosly, such a simple and usefull util func, and no feedback after 7 years?

**Comment by CarlosVergikosk** [comment]
Still nothing? Its really usefull

**Comment by matthew-dean** [comment]
Ha, just came here because I expected Lodash to have this function. Seems more useful than a lot of other Lodash methods.

**Comment by Akronae** [comment]
Oh wow really? I hardly understand how this can be overlook

**Comment by buondevid** [comment]
I opened a PR [here](https://github.com/lodash/lodash/pull/5637).

**Comment by jegors-at-levelpath** [comment]
LOL.

**Comment by buondevid** [comment]
I remade another PR after the issues-bankruptcy [here](https://github.com/lodash/lodash/pull/5745) 🤞.
