### ISSUE TITLE
ES6 and FP in Lodash 4

### ISSUE THREAD

**Issue by billyjanitsch** [lodash/lodash#1704]
I keep seeing this shim referenced in discussions about bringing FP to Lodash 4:

```js
require('lodash/fp')()
```

I assume that in ES6, this would have to look something like:

```js
import initFp from 'lodash/fp'
import {some, zip} from 'lodash'

initFp()
zip(...)
```

Perhaps I'm missing something, but this doesn't seem very idiomatic to me.
- Is that idea that this should be called once at the top of my project's main entry point(s)? If so, do I also need to include it at the top of all of my tests, assuming they don't import from the main entry?
- Either way, doesn't this add a fair bit of overhead on app init?
- What is the compatibility here with the new Lodash ES build? I'd hate to lose tree-shaking just because I want FP.

What I seem to want is an interface more like the one that exists for lodash-fp:

```js
import {some, zip} from 'lodash/fp'

zip(...)
```

What are your thoughts on this?

Thanks for your work on Lodash!

**Comment by jdalton** [comment]
The current approach is:
```js
var _ = require('lodash/fp')();
```
so in ES6 that would be
```js
import fp from 'lodash/fp';
const _ = fp();
```
for cherry-picked methods you can do
```js
import {some as _some } from 'lodash/fp'
const some = fp('some', _some);
```

**Comment by billyjanitsch** [comment]
Hm. Could you share your reasoning in preferring something like:

```js
import fp from 'lodash/fp'
import {map as _map, filter as _filter, reduce as _reduce, take as _take} from 'lodash'

const map = fp('map', _map)
const filter = fp('filter', _filter)
const reduce = fp('reduce', _reduce)
const take = fp('take', _take)
```

over:

```js
import {map, filter, reduce, take} from 'lodash/fp'
```

I realize that it takes more work to precompile the latter and you're looking to consolidate the Lodash builds, but the former seems incredibly verbose. It also incurs runtime overhead for each import in each file (if I want `map` in another file, I have to call `fp` again).

I'm aware of the advantages of Lodash over Ramda and I'd like to switch, but the former is going to be a tough sell when I can already just do:

```js
import {map, filter, reduce, take} from 'ramda'
```

**Comment by jdalton** [comment]
The `fp` module is the convertor. I could change things up to allow a module to export a lodash that's already converted so a:
```js
import {map, filter, reduce, take} from 'lodash/smth'
```
would work though you wouldn't get tree shaking. There's also [Babel plugins](https://github.com/megawac/babel-plugin-lodash) to ease cherry-picking.

**Comment by megawac** [comment]
@jdalton so lodash/fp will have an 'import _ from "lodash"' to support the 'fp=fp()' case? If so won't that force the entirity of lodash to get bundled in webpack/browaerify builds?

**Comment by jdalton** [comment]
>  If so won't that force the entirity of lodash to get bundled in webpack/browaerify builds?

If it did, then yes it would.

**Comment by epeli** [comment]
What about precompiling wrapper files like

js```
import map from 'lodash/fp/map'
import pick from 'lodash/fp/pick'
```

This way there would be no need for tree shaking or special compilation to make cherry-picking easy.

**Comment by megawac** [comment]
@epeli that would significantly increase the DL size of lodash as all the `fp/` methods would need a unique file. It's better to just let users import they're methods and use the `convert` module

```
import map from 'lodash/collection/map'
import pick from 'lodash/object/pick'
import map from 'lodash/fp/convert'

let fp = convert({
   map, pick
})
```

**Comment by epeli** [comment]
Do you mean the npm download size or the webpack/browserify/rollup bundle size downloaded by browsers?

**Comment by megawac** [comment]
npm download size, the bundled size difference should be non consequential

On Sat, Jan 9, 2016 at 5:01 AM, Esa-Matti Suuronen <notifications@github.com

**Comment by jdalton** [comment]
@epeli
> What about precompiling wrapper files

I could automate the building of such files though I'm not sure it would make it in the initial release.

@megawac 
> that would significantly increase the DL size of lodash

I'm not so sure it would increase it too much. I could see the on disk size increase but the tarball size would probably be impacted less.

Tree shaking won't work with webpack or rollup anyways. That's where [babel-plugin-lodash](https://github.com/megawac/babel-plugin-lodash) comes in to enable tree-shaking without folks having to worry about paths or cherry-picking.

**Comment by epeli** [comment]
> I'm not so sure it would increase it that much. I could see the on disk size increase but the tarball size would likely be impacted less.

My thinking exactly. Wouldn't the contents of an one file be just something like:

```js
module.exports = require('lodash/fp/convert')(require('lodash/collection/map'));
```

which should gzip really well since they are so similar.

> I could automate the building of such files though I'm not sure it would make it in the initial release.

That would be awesome. No hurry. I'd like to help if possible?

**Comment by jdalton** [comment]
@epeli 
> I'd like to help if possible?

Boom! You've been given commit rights. I usually handle builds from `lodash-cli` but this is different as it's not transforming the lodash source. So I imagine more work done in the `lodash/lib` area to generate the files. I imagine the code would [crawl the npm package](https://github.com/lodash/babel-plugin-lodash/blob/master/src/lodash-modules.js) like `babel-plugin-lodash` combined with the [fp method mapping](https://github.com/lodash/lodash/blob/master/lib/fp/mapping.js) to generate the modules.

**Comment by epeli** [comment]
Cool, thanks!

I'm pretty new to lodash-cli, so sorry if I have misunderstood something, but I was initially thinking it should be part of the `lodash modularize`.

When the files are created 

```
number
number/random.js
number/inRange.js
...
```

it should also create the fp equivalents:

```
fp/number
fp/number/random.js
fp/number/inRange.js
...
```

Where each one would have a contents like

ex. `fp/number/random.js`
```js
var convert = require("../path/to/the/fp/convert");
module.exports = convert(require("../../number/random")); // Not sure whether convert can be used like this
```

and it should respect the `exports` option and generate the appropriate content.

Or are you saying it can be done in a simpler way in the build scripts in`lodash/lib`?

**Comment by jdalton** [comment]
> Or are you saying it can be done in a simpler way in the build scripts in `lodash/lib`?

`lodash-cli` is really just for chopping up `lodash.js`. Since these fp-wrappers are an addition to it makes shoe-horning them into `lodash-cli` awkward. Instead we could use the `lodash/lib` to create the fp additions.

> `// Not sure whether convert can be used like this`

It's `convert(name, func)`. It wraps `func` based on the name given.

**Comment by jdalton** [comment]
Many methods won't need wrapping and they could just point to the lodash modules unwrapped. The [fp mapping](https://github.com/lodash/lodash/blob/master/lib/fp/mapping.js) can help identify them.

**Comment by epeli** [comment]
> Since these fp-wrappers are an addition-to it makes shoehorning them into lodash-cli awkward

Right, it's also quite involved at first glance :)

Another question: How the final npm package is created? I'm mainly wondering how the files from `lodash modularize` get stuffed in?

**Comment by jdalton** [comment]
> Right. It's also quite involved piece of code at first glance :)

It started in v0.2.0 and snowballed. There's an open issue to help [modularize and simplify](https://github.com/lodash/lodash-cli/issues/5) that too. It's lame but it's been working for almost 4 years now.

The [amd](https://github.com/lodash/lodash/tree/amd), [es](https://github.com/lodash/lodash/tree/es), [npm](https://github.com/lodash/lodash/tree/npm), and [npm-packages](https://github.com/lodash/lodash/tree/npm-packages] branches are compile targets of `lodash-cli`. The addition of `fp` and the process around modularizing it haven't been ironed out yet.

**Comment by boneskull** [comment]
> The addition of fp and the process around modularizing it haven't been ironed out yet.

I'm interested in using `lodash-es` w/ `fp`.  

I apologize if this was mentioned above somewhere; what if `fp` was its own compile target?

If I was going to use `lodash/fp`, I probably *wouldn't* want to use `lodash` proper.  What's the use case for having both available?

**Comment by jdalton** [comment]
> I'm interested in using `lodash-es` w/ `fp`.  

That will probably come in a future release.

> I apologize if this was mentioned above somewhere; what if `fp` was its own compile target?

`lodash-cli` is really about slicing up the monolithic `lodash.js` file. It's not about additional wrappers and all that comes with it.

> If I was going to use `lodash/fp`, I probably *wouldn't* want to use `lodash` proper.  What's the use case for having both available?

By pulling it into core we get more eyes on it and allow it, it gives a sense of higher priority, it also allows folks to drop in and out when needed (some of the fp behaviors aren't suitable for all situations).

**Comment by QuantumInformation** [comment]
Has anyone managed to get `es6 import` to work in create react app?

Eg I can do
` let debounce = require('../../node_modules/lodash/debounce.js')`
but not 

` import {debounce} from 'lodash'`

**Comment by StreetStrider** [comment]
@QuantumInformation `lodash-es`: I usually do `import debounce from 'lodash-es/debounce`.

**Comment by QuantumInformation** [comment]
oh there is lodash-es, nice

**Comment by QuantumInformation** [comment]
I tried `import debounce from 'lodash-es/debounce'`
and have `@types/lodash-es`


but get

(16,22): error TS7016: Could not find a declaration file for module 'lodash-es/debounce'. '/Users/nikos/WebstormProjects/client/node_modules/lodash-es/debounce.js' implicitly has an 'any' type.
  Try `npm install @types/lodash-es/debounce` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash-es/debounce';`

**Comment by StreetStrider** [comment]
@QuantumInformation try install them, then: `npm i @types/lodash-es`. If no luck, try do renames; like `cp -r node_modules/@types/{lodash,lodash-es}` and rename module name inside decl.

**Comment by QuantumInformation** [comment]
i done it again and it worked thanks
