### ISSUE TITLE
`reduce` fails on objects with "length" key

### ISSUE THREAD

**Issue by Machyne** [lodash/lodash#1705]
When an object with the key `"length"` is passed as the collection to reduce, reduce fails.
Ex:
```
reduce = require("lodash").reduce;
reduce({ foo: 'bar', length: 12 }, function (res, val, key) {
  res[key] = val;
  return res;
}, {})
```
results in:
```
{ '0': undefined,
  '1': undefined,
  '2': undefined,
  '3': undefined,
  '4': undefined,
  '5': undefined,
  '6': undefined,
  '7': undefined,
  '8': undefined,
  '9': undefined,
  '10': undefined,
  '11': undefined }
```

Perhaps it gets interpreted as an array? However, `isArray` does the right thing, i.e. :
```
> require('lodash').isArray({length:12})
false
```

**Comment by jdalton** [comment]
Hi @Machyne!

This is by design because `reduce` is a Collection method which means it prioritizes array-like objects over objects. You can use [_.transform](https://lodash.com/docs#transform) instead.
