### ISSUE TITLE
Broken link on lodash.com "Home" page

### ISSUE THREAD

**Issue by NicBright** [lodash/lodash#1706]
Hi there,

inside the "Features" section, the link in the _.bindKey() item pointing to the "lazy" defined methods is broken. Instead of "http://michaux.ca/articles/lazy-function-definition-pattern" (broken) the link seems to have changed to http://peter.michaux.ca/articles/lazy-function-definition-pattern

Regards,
Nicolas

**Comment by jdalton** [comment]
Thanks, fixed :D
