### ISSUE TITLE
Will lodash 4.0 still support IE8?

### ISSUE THREAD

**Issue by AjaxSolutions** [lodash/lodash#1708]
Will lodash 4.0 still support IE8?

**Comment by jdalton** [comment]
No. Lodash v4 is dropping support for older IEs because on Jan 12, 2016 Microsoft is dropping support [for them too](https://support.microsoft.com/en-us/lifecycle#gp/Microsoft-Internet-Explorer). Essentially IE11 and Edge are the only ones left to worry about. I have designed Lodash v4 to work with es5-shim and es6-shim though if you still need older environment support.

**Comment by barsh** [comment]
As far as I can tell the `es5-shim` doesn't help with Lodash v4 in IE8.  

Sample.html
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.0.0/lodash.min.js"></script>
```

Open in any version of IE, press F12, then change document mode to IE8.
![image](https://cloud.githubusercontent.com/assets/2644202/13555391/08662120-e385-11e5-9a31-feda3e235f26.png)

**Comment by jdalton** [comment]
Could you use unminified and also the latest v4.6.1.

**Comment by jdalton** [comment]
Lodash v4 uses `Object.create` and `Object.getPrototypeOf` [are covered](https://github.com/es-shims/es5-shim#shams) by [es5-sham](https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-sham.js). So you'll need to include both.

**Comment by ijdickinson** [comment]
I concur that, even with `es5-shim` and `es5-sham` loaded before lodash, it still fails in IE8 with an `Object expected` error.

**Comment by jdalton** [comment]
Works for me. Try [this](https://jsbin.com/miyure/1/).

**Comment by ijdickinson** [comment]
Hmm. Ok, thank you. That's essentially what my code is doing, except that I'm loading the AMD version of Lodash via requireJS. But I don't think that should make a difference. I'll keep digging. Thanks for your help!
