### ISSUE TITLE
Cannot visit lodash.com due to SSL error

### ISSUE THREAD

**Issue by havrlant** [lodash/lodash#1710]
Hi, since today I cannot visit lodash.com because of some SSL error. Is it my problem or something wrong with the site? I have Linux, Chrome Version 46.0.2490.86 (64-bit). See screenshot. 

![privacyerrorlodash](https://cloud.githubusercontent.com/assets/442040/11891816/7a456f82-a562-11e5-90e4-587f074eb435.png)

**Comment by jdalton** [comment]
Maybe a hiccup. I can't reproduce. \cc @mathiasbynens

**Comment by mathiasbynens** [comment]
Works for me, too.
