### ISSUE TITLE
question: how to chain properly with modularized build?

### ISSUE THREAD

**Issue by boneskull** [lodash/lodash#1712]
```shell
nesh> var chain = require('lodash/chain/chain');
nesh> chain(['foo']).reject('foo').value()
TypeError: chain(...).reject is not a function
```

Use case:  instead of `require('lodash')` everywhere, I'm attempting to keep a browserified build of my app lean.  This was working fine until I wanted to chain methods.  

I was hoping to avoid a custom build this way, but that may be what needs to happen.

**Comment by jdalton** [comment]
Chaining requires a bit of scaffolding that is not provided.
There's a babel plugin that can help though https://github.com/megawac/babel-plugin-lodash.
