### ISSUE TITLE
_.random float performance

### ISSUE THREAD

**Issue by sergebat** [lodash/lodash#1713]
Floating-point version of _.random implementation has quite a non-trivial overhead (in terms of memory allocation and cpu).

We use lodash for mobile web games, random is often used in time-critical per frame loops. The following test illustrates the problem:
http://jsperf.com/lodash-random

I suggest to consider three options:

* Drop the requirement for _.random to include max (for floating point version only!). In most practical scenarios support for inclusivity of "max" for floating point version really does not worth the overhead. 
* Precompute `delta` part on initialization (though I am not sure I fully followed how it is intended to work).
* At the very least - warn about this quite unexpected characteristic in the documentation. 

``` javascript
if (floating || min % 1 || max % 1) {
        var rand = nativeRandom();
        return nativeMin(min + (rand * (max - min + parseFloat('1e-' + ((rand + '').length - 1)))), max);
}
```

**Comment by jdalton** [comment]
You can try the master edge branch but I suspect not much better.
Lodash is a general purpose utility lib and I think a perf signature of several million ops/sec for random+float is fine. In your specialized case you're better off implementing exactly what you need tailored to your performance concern.

**Comment by jdalton** [comment]
Also for perf critical measurements you should measure minified code because v8 has a goofy inlining heuristic based on function source side which includes comments.
