### ISSUE TITLE
Find deep value

### ISSUE THREAD

**Issue by russplaysguitar** [lodash/lodash#1714]
As far as I know, it is not possible to perform a `find()` and return a deeply-nested value. 

I've implemented my own version, but it might be nice if this was built in to lodash?
```
// Recusively iterates over elements of `collection`, returning the first element `predicate` returns truthy for.
// The predicate is bound to `thisArg` and invoked with three arguments: `(value, index|key, collection)`.
var findDeepValue = function (collection, predicate, thisArg) {
    var result;

    _.each(collection, function (value) {
        if (_.isObject(value) && !_.isFunction(value)) {
            result = findDeepValue.call(this, value, predicate, thisArg);
        }
        else {
            var isMatch = predicate.apply(thisArg, arguments);
            result = isMatch ? value : undefined;
        }

        if (!_.isUndefined(result)) {
            return false;// break out of the loop early
        }
    }, this);

    return result;
};
```

**Comment by jdalton** [comment]
Hi @russplaysguitar!

Thanks for the suggestion. I can see more deep methods in lodash's future for sure.

Before adding these other deep forms though  I'd be for a generic `walk` or `crawl` method. Like `_.walk` or `_.walkDeep`.

**Comment by jdalton** [comment]
If you'd like to open a PR for the the walk function I'd take it.

**Comment by russplaysguitar** [comment]
I'm not familiar with either of those functions. The closest I can find is PHP's [array_walk](http://php.net/manual/en/function.array-walk.php)-- is that the sort of behavior you're referring to?

**Comment by jdalton** [comment]
Similar, this would invoke an `iteratee` over every property of an object.
It may be more appropriate to name it `_.forOwnDeep` and `_.forInDeep`.

**Comment by StreetStrider** [comment]
`walk` and `crawl` are pretty comprehensive (and also just pretty).

**Comment by russplaysguitar** [comment]
Are there any functions in lodash that already use recursive iteration that would be a good example for implementing `_.forOwnDeep` and `_.forInDeep`?

**Comment by jdalton** [comment]
There's `_.merge`,`_.cloneDeep`, and `_.isEqual` (which each break down into smaller functions).

**Comment by Xotic750** [comment]
I have been doing something similar myself, how about this as somewhere to start?
```
function baseWalk(object, predicate) {
  if (!_.isObject(object) || !_.isFunction(predicate)) {
    return;
  }
  for (var prop in object) {
    var value = object[prop];
    var result = predicate(value, prop, object);
    if (result === true) {
      break;
    }
    if (result !== false && _.isObject(value)) {
      baseWalk(value, predicate);
    }
  }
}

Array.prototype.blah = true;

var test = {
  a: [1, 2, 3],
  b: {
    x: 1
  },
  c: 'abc',
  d: Object('xyz'),
  e: new Date(),
  f: /pattern/
};

baseWalk(test, function(value, prop, object) {
	if (object.hasOwnProperty(prop)) {
    if (_.isString(value)) {
    	console.log('ignored: ' + value.toString());
			return false;
    }
    if (_.isDate(value)) {
    	console.log('date and break: ' + value.toISOString());
			return true;
    }
  	console.log(arguments);
    return;
  }
  console.log('not mine: ' + prop);
});
```
https://jsfiddle.net/7mq0ob96/

**Comment by russplaysguitar** [comment]
That looks pretty good to me, thanks @Xotic750 ! What do you think @jdalton ?

**Comment by jdalton** [comment]
@russplaysguitar
I'd like it based on our current recursive crawl which does track circular references.
