### ISSUE TITLE
Chain interruption

### ISSUE THREAD

**Issue by calebmer** [lodash/lodash#1715]
I have a lodash chain which looks something like this:

```js
chain(req.headers.cookie)
.thru(parseCookie)
.property(stateCookie)
.thru(JSON.parse) 
```

At a couple of points, the value might be `undefined` or another falsey value. Is there a way to interrupt chain execution when there is a falsey value and just return that falsey value?

**Comment by jdalton** [comment]
You can `tap` and `thru` a chain but not exit it early.
