### ISSUE TITLE
Deep Cloning sparse array inserts spurious 'undefined' values

### ISSUE THREAD

**Issue by cefn** [lodash/lodash#1719]
Was surprised to find that a _.cloneDeep call on a sparse array causes undefined values to be inserted, instead of leaving unassigned numerical indexes. Below is a node REPL session which shows the problem. 

Note the difference between JSON.stringify of the original sparse array in which numbers are not assigned, and of the cloned sparse array in which numbers are assigned with the value 'undefined'. 

```javascript
> var arr = []
undefined
> arr[2]="val"
'val'
> arr
[ , , 'val' ]
> arrClone = lodash.cloneDeep(arr)
[ undefined, undefined, 'val' ]
```

This variation between items and their clones has already created some gnarly bugs from comparisons generated according to the JSON patch IETF RFC 6902. In particular the comparison algorithms of fast-json-patch generates a 'remove' changeset between a previously snapshotted clone (with its undefined values) and the original (which has no undefined values at the same relative paths).

**Comment by jdalton** [comment]
That's correct and by design. The arrays produced by lodash are dense and not sparse.
