### ISSUE TITLE
Add _.findWhere()

### ISSUE THREAD

**Issue by ghost** [lodash/lodash#172]
Combination of the syntax for `where()` with the single-result nature of `find()`. Added by documentcloud/underscore@89060f0dbde080b1f0f5c8e99719987f31ae2990

**Comment by samme** [comment]
The docs are a bit coy on this. You have to read through the **Example** to discover the alternative predicate types.

> [predicate=_.identity] (Function): The function invoked per iteration.

<https://lodash.com/docs/#find>
