### ISSUE TITLE
About _.set

### ISSUE THREAD

**Issue by 285858315** [lodash/lodash#1720]
``_.set({},"a['1']","test").a``
the result is array and not object?how get object type?
sorry, my english is very poor.

**Comment by iam-peekay** [comment]
@jdalton feel free to correct me if I'm wrong..

@285858315 It looks like when you're accessing a['1'], it's coercing it to a[1] and so when you access the "a" property on the object, it's returning an array. You can try changing the '1' to not be a number (e.g. 'c').

when I do: 

console.log(_.set( {}, "a['c']", "test" )).a;   //  Object { a: { c: 'test' } }

**Comment by jdalton** [comment]
@285858315 In lodash v4, due out in Jan, you can use `_.setWith` to customize object creation.
