### ISSUE TITLE
Is lodash providing a similar functionality with this function

### ISSUE THREAD

**Issue by nikoskalogridis** [lodash/lodash#1722]
Excuse me for my shameless question, I am using the following function in my code extensively:
```
function (value) {
  return function (f) {
    return f(value);
  };
}
```
I was trying to find a related function in lodash but although I have searched through the API docs I could not find something similar. Am I missing something here or simply the above pattern is not useful to anyone else

**Comment by jdalton** [comment]
We don't though you can come close with `_.curry` or `_.partial`.
