### ISSUE TITLE
_.flatten on array like objects

### ISSUE THREAD

**Issue by matias-capeletto** [lodash/lodash#1724]
Given that other Array methods like _.difference, _.intersection, _.uniq, & _.xor accept array-like values, would it be possible to allow _.flatten to work on array like objects?

**Comment by jdalton** [comment]
The `flatten` methods are in the tricky position of needing to be able to crawl deeply which gets tricky with array likes. It's an "Array" method for simplicity and as such just as with other "Array" methods only arrays are guaranteed to be supported.

**Comment by matias-capeletto** [comment]
Thanks for the answer, hoping browsers implements ES2015 native array subclassing soon.
Good luck with v4 release!
