### ISSUE TITLE
_.set treats numbers as arrays

### ISSUE THREAD

**Issue by BorisKozo** [lodash/lodash#1725]
tl;dr 
"a[10].b" is interpreted the same as "a.10.b"

I am trying to create a deep path where one of the properties is a number. When I put the number as part of the path it creates an array instead of creating a property.
I debugged _.set very superficially and saw that both the expression "a[10].b" and "a.10.b" are broken into the same three pieces ["a","10","b"] and therefore have the same meaning.

Is this an issue or the intended behavior? 
If this is the intended behavior then what do I need to write to create an object with a number property?

**Comment by jdalton** [comment]
Hi @BorisKozo!

See #1359, #1720, #1685.

**Comment by BorisKozo** [comment]
Oops, sorry. Should have searched better in the closed issues.
