### ISSUE TITLE
cloneDeep with TypeScript

### ISSUE THREAD

**Issue by gbouteiller** [lodash/lodash#1726]
Hello,
As I am moving my code from JS to TS, I am facing an issue with cloneDeep : if I try to clone an object that contains typed objects, types are lost. For now, I'm using another lib just for this part but I'd like to stick entirely with your great library ! What are the options here :) ?
Thanks in advance

**Comment by jdalton** [comment]
You mean objects with a `constructor` that's not `Object` and not a built-in like array or date object?
That's a limitation of our clone implementation. We punt on it because simply getting inheritance may not be enough to be considered a clone.

**Comment by gbouteiller** [comment]
Yes, I mean instance of a typescript class. Do you plan to add another method that will implement such algorithm like https://www.npmjs.com/package/owl-deepcopy ? If not, is there a workaround to have the same result using the customizer function on cloneDeep?
In fact, I'm using redux that needs immutable data and used to use cloneDeep in my reducer but now that I moved to Typescript, I'm stuck.
Any help would be appreciated.

**Comment by jdalton** [comment]
>  If not, is there a workaround to have the same result using the customizer function on cloneDeep

Yep. Something like

```js
var cloneDeep = _.partialRight(_.cloneDeep, function(value) {
  if (!_.isObject(value) && !_.isArray(value)) {
    return _.cloneDeep(_.toPlainObject(value));
  }
});
```
