### ISSUE TITLE
Expose module functionality to produce a lodash compatible wrapper

### ISSUE THREAD

**Issue by megawac** [lodash/lodash#1727]
Hey @jdalton we discussed this previously last spring when I was working on [lodash-modularize](https://github.com/megawac/lodash-modularize) over gitter. It would be nice if it were possible to create lodash compatible wrapper -- lazy functionality and all.

[Currently the behaviour can be approximated using mixin and calling the `LodashWrapper` through a wrapper](https://github.com/megawac/lodash-modularize/blob/master/templates/chain-build.tpl) (wrapper required as `runInContext` also is not in the modular build) similar to as follows:

```js
import lodash from 'lodash/chain/lodash';
import LodashWrapper from 'lodash/internal/LodashWrapper';

import create from 'lodash/object/create';
import mixin from 'lodash/utility/mixin';

function _(value) {
  if (!(this instanceof _)) {
    return new _(value);
  }
  LodashWrapper.call(this, value);
}
_.prototype = create(lodash.prototype);

mixin(_, {
  // lodash methods
}, true);
```

However, in the modular builds the lazy code is only about a quarter present, with some implementations of `chain` methods considering lazyWrappers. Also the `lazyWrapper` is included in the modular builds despite no decent way of using it.

------------------------

I'd like a way to use lazy functionality with modular builds. **Rather than exposing this through the `chaining` api I'd suggest it be accessible through the `lift` and `compose` APIs.** (ALA ramda who expose their lazy features for modular builds). This would make it easier for the end user (or transpiler ^^) as they would not have to spoof the lodash wrapper. Further, all of the chaining API features are can be easily written through `lift` or `compose`.

On a tangent why were `lift` and `liftRight` removed from v4 builds?

Along with this proposition I would suggest that the chaining api is no longer exposed in the modular build as its use is kind of impractical.

I realize this proposition would require significant refactoring as I expect it would require the chaining api to be implemented through `lift` and `compose`.

**Comment by jdalton** [comment]
I believe our lazy implementation, while not perfect, provides the biggest bang for the size/complexity giving developers the benefits of transducers without requiring them to write code any differently. We even use lazy sequences in `flow` and `flowRight` to enable shortcut-fusion in composed methods. At the end of the day though shortcut fusion and chaining are a nice-to-have and not something that's mission critical to provide in all scenarios. Our implementation cherry picks a handful of cases to support lazy evaluation which makes modularizing it a bit tricky.

>  Also the lazyWrapper is included in the modular builds despite no decent way of using it.

I've left them in so folks can compose or proof-out their own chain module if needed.

> On a tangent why were `lift` and `liftRight` removed from v4 builds?

Lodash hasn't had a `lift` or `liftRight` method.

I'm not against adding support in the `lodash/chain` module. If you'd like to mock-up what that would look like with the existing modular chaining API that would rock.

**Comment by megawac** [comment]
*whoops mixed up the names `lift` and `flow`
