### ISSUE TITLE
Object wrapper broken

### ISSUE THREAD

**Issue by deckar01** [lodash/lodash#1731]
I used npm which installed `lodash@3.10.1`

The wrapper ```_(obj).forEach``` doesn't do anything, but ```_.forEach(obj, ...)``` is working fine.

Example:

```js
var _ = require('lodash');

var obj = {'test': 'seems', 'very': 'broken'};

_(obj).forEach(function(value, key) {
  console.log(key + ': ' + value);
});
```

Produces no output.

**Comment by jdalton** [comment]
Chained execution is deferred until an implicit or explicit `.value()` is requested.
See http://lodash.com/docs#_.

**Comment by deckar01** [comment]
Thanks for the help. I did not notice ```.value()``` in the documentation.

**Comment by jdalton** [comment]
Np :grinning:
