### ISSUE TITLE
Check if `collection` path exists in `size` method

### ISSUE THREAD

**Issue by danemacmillan** [lodash/lodash#1732]
It would be handy if the `size` method could automatically check if the collection provided to it exists.

For example:

```
var foo = {};
console.log(_.size(foo.bar)); // undefined, and returns 0
console.log(_.size(foo.bar.baz)); // undefined, but JS errors out: TypeError: foo.bar is undefined
```

This is the typical workflow for checking the size of a nested object:
```
if (_.has(foo, 'bar.baz') && _.size(foo.bar.baz) > 2) {
    // Do something
}
```

That `has` check will always need to be performed before verifying the size of a collection with `size`. As it is, single-level nested collections that do not exist return `0`, as expected, because an `undefined` type cannot be iterated over, but going beyond that single level of nesting will throw a `TypeError` without additional logic, even though it is still true that a non-existent, `undefined` value nested several layers deep cannot be iterated over, either. It would make sense to implicitly check whether a collection passed to `size` exists. Doing this would make the following possible:

```
if (_.size(foo.bar.baz) > 2) {
    // Do something
}
```

I'm aware that `get` can be called with a default fallback, and then that can be wrapped in `size`, but this is for those cases when you don't care to store the value of `foo.bar.baz`, but just want to check if it is iterable.

**Comment by jdalton** [comment]
Since _.size doesn't have a path param it feels odd adding support for it. Instead you can do _.size(_.get(o, path)).
