### ISSUE TITLE
volo, component, bower support

### ISSUE THREAD

**Issue by boneskull** [lodash/lodash#1733]
Will v4.x support these?  Component is dead afaik, I don't know anyone using Volo, and Bower is [somewhat useless](http://npmcdn.com).  

I ask because `README.md` still mentions them.  I was going to send a PR, then I decided I knew better.

**Comment by jdalton** [comment]
Lodash v4 will drop component, volo, and bower.
You can totally send a PR :D

**Comment by smokinguns** [comment]
so why are you dropping support for bower? Do you have stats on the number of people using bower vs npm. I only started using bower because I kept coming across packages that were in bower, but not npm. I now have to change my build script to pull in the lodash from npm, when all other packages are coming from bower. Granted in time, bower will likely fade out as people add support for npm. I just would like to know why you chose this release to drop support.

**Comment by omeid** [comment]
Please return bower support.

**Comment by jdalton** [comment]
Bower filled a gap before npm but as things like jQuery plugins shifted to npm and with Lodash v4 shedding much of its legacy support it's time to drop the baggage. Component is abandoned, Volo has almost no usage, and Bower is overshadowed by npm.

**Comment by boneskull** [comment]
@smokinguns change your build scripts to use npm and encourage package authors to publish to npm. Bower is goin down by the wayside

**Comment by antoinebrault** [comment]
So if i'm still using npm 2 on older projects, or if code/build is already based on bower, i'm basically stuck on lodash 3 because you guys decided bower is dead?

**Comment by jdalton** [comment]
>  So if i'm still using npm 2 on older projects

Lodash works with npm 2.

> or if code/build is already based on bower, i'm basically stuck on lodash 3 because you guys decided bower is dead?

Bower works with github tags/branches so just:
```js
bower install lodash#4.0.1
```

will grab the master branch at 4.0.1 :P

**Comment by pribilinskiy** [comment]
@boneskull [Stats](http://bower.io/stats/) says the opposite :P

**Comment by jdalton** [comment]
The bower stats site was recently updated to remove details that were collected by google analytics. I'm not interested in hashing this out. Bower is a dead end <period>. Folks used to be just as adamant about component support and that has fallen away. The same is happening to bower. I've already shown that you can still install lodash with bower so there's nothing much more to say.
