### ISSUE TITLE
Async support in ```_.template(...)```

### ISSUE THREAD

**Issue by mitchdenny** [lodash/lodash#1736]
Hi there,

I'm currently looking at taking lodash in a small little utility that I'm working (currently I'm using underscore). Specifically I'm looking at using the ```template(...)``` function. The syntax of the templates that I use is as follows (where the code evaluated between brackets is the executable code):

```
"[function1()]blah[function2()]blah[function3()]"
```

That works fine, but I run into trouble when some of the functions need to execute code asynchronously, for example, lets say that functions 1 & 2 simply return a string based on computations that can be done locally, but function 3 needs to make a call to a REST API. At the moment I would need to use a library such as sync-request which spins of a child process.

I was thinking however that it would be awesome if lodash could look at the values of the objects being returned from the functions it is calling and determine whether it looks like a Promise, then setup a promise that would them be returned from the template function.

Perhaps it would be better to have a different function for a Promise aware version of ``template(...)```.

Anyway - thought I would start the conversation here just to see what people think.

**Comment by jdalton** [comment]
Hi @mitchdenny!

Lodash's `_.template` is pretty simple, no frills, template function. For anything more there are plenty of template specific libs that may provide you will the functionality you're looking for.
