### ISSUE TITLE
The opposite of _.where? _.exclude?

### ISSUE THREAD

**Issue by jamesrom** [lodash/lodash#1737]
The opposite of `_.where`. Instead of filtering each element in the array for items matching the source object, it filters items that *do not* match the source object.

It could be called `_.exclude` but that might be confused with `_.include`.

For example:
```js
var users = [
  { 'user': 'barney', 'age': 36, 'active': false, 'pets': ['hoppy'] },
  { 'user': 'fred',   'age': 40, 'active': true, 'pets': ['baby puss', 'dino'] }
];

_.pluck(_.exclude(users, { 'age': 36, 'active': false }), 'user');
// → ['fred']

_.pluck(_.exclude(users, { 'pets': ['dino'] }), 'user');
// → ['barney']
```

**Comment by jdalton** [comment]
In v4 `_.where` has been removed because it's just `_.filter(obj,{'active':false})`
so the opposite is `_.reject(obj,{'active':false})`
