### ISSUE TITLE
Feature request: function to coerce strings to other primitive types

### ISSUE THREAD

**Issue by nfcampos** [lodash/lodash#1738]
Hi,

Is there a method in lodash to convert strings to number/boolean?
something like this:
```
function parse(val) {
  if (val === 'true') return true
  if (val === 'false') return false
  if (! Number.isNaN(+val)) return +val
  else return val
}
```
Do you think it makes sense to add something like this?
(use case is eg. parsing cookie values, parsing input values)

**Comment by jdalton** [comment]
Hi @nfcampos! I'll leave parsing up to `JSON.parse`.

**Comment by nfcampos** [comment]
JSON.parse is not great for this because `JSON.parse('an actual string')` throws, making it unusable for parsing a string that may be a number, boolean, or a string...

**Comment by jdalton** [comment]
Then some mix of the two. This kind of addition is better suited as a `mixin`.

**Comment by nfcampos** [comment]
alright, thanks!
