### ISSUE TITLE
toArray documentation possibly misleading

### ISSUE THREAD

**Issue by fyyyyy** [lodash/lodash#1740]
https://lodash.com/docs#toArray

It says `Converts value to an array.`
However `_.toArray(1)` does return `[]`, so it only works with objects, arguments, array, string. Not with any type of value.
It depends how you read `convert value to array` so i would expect `_.toArray(1) => [1]`
So clearer documentation would be nice :)

Relates to #953

**Comment by StreetStrider** [comment]
So it should mention that `value` is an array-like or in common an iterable object.

**Comment by jdalton** [comment]
I'll change the behavior of `_.toArray` to convert primitives to `[primitive]`.

**Comment by jridgewell** [comment]
@jdalton: Wouldn't that be better left to an array wrap method?

**Comment by jdalton** [comment]
I don't think there's enough use for a separate method just for primitives.

**Comment by jdalton** [comment]
Let's take it [to a poll](https://twitter.com/jdalton/status/686610113126256640).

**Comment by jdalton** [comment]
Ok, after reviewing it. Let's keep `_.toArray` the way it is and go @jridgewell route for a method to wrap. Maybe an `_.asArray`.
