### ISSUE TITLE
(Docs) Safari 9.0.2 won't scroll the side-nav-bar sometimes

### ISSUE THREAD

**Issue by DomiR** [lodash/lodash#1741]
So the left sidebar will stopp scrolling after the right side was scrolled down. Somehow only the main content will scroll after that, even when hovering the sidebar. The sidebar will only start scrolling again after scrolling the main content to the top. 

Chrome does not have this issue. I noticed that chrome will always show the scrollbars on both, while Safari hides them. Maybe there is a css fix...

**Comment by jdalton** [comment]
Hi @DomiR!

Can you redirect this issue to https://github.com/lodash/lodash.github.io/issues.

**Comment by ELLIOTTCABLE** [comment]
For others who stumble across this, while trying to report the same issue: see lodash/lodash.github.io#17!
