### ISSUE TITLE
_.remove with undefined second argument truncates the array

### ISSUE THREAD

**Issue by Alexsey** [lodash/lodash#1742]
```
let a = [1, 2, 3]
_.remove(a)
console.log(a) // [ ]
```
the problem case is when second parameter is provided, but is ```undefined``` or ```null```. Consider 
```
let a = [1, 2, 3]
let badElement = getBadElement()
_(a).remove(badElement)
```
if ```badElement``` may or may not exists - you need to check it for ``` != null``` before remove

I propose to change current behavior and remove nothing when second parameter is ```undefined``` because while first example with single argument just don't make any sense to be written, second is an unpleasant surprise when you ask method to remove ```undefined``` and it removes just all. But if you think it's ok - at list it should be described in the docs

Thanks

**Comment by jdalton** [comment]
That's because the default `iteratee` is `identity`.

**Comment by Alexsey** [comment]
Sorry, that is true, it is in docs. Will be more attentive next time
