### ISSUE TITLE
Find if array includes all elements from another array

### ISSUE THREAD

**Issue by slavafomin** [lodash/lodash#1743]
Hello!

Thank you for this great library.

However, please consider adding a function to find if specified array includes all elements from another specified array.

Here's the related question on SO: http://stackoverflow.com/questions/8628059/check-if-every-element-in-one-array-is-in-a-second-array

Concept:

```javascript

var array1 = ['A', 'B', 'C', 'D', 'E'];
var array2 = ['B', 'C', 'E'];
var array3 = ['B', 'C', 'Z'];

_.includes(array1, array2); // => true
_.includes(array1, array3); // => false

```

Solution in vanilla JavaScript for modern browsers:

```javascript
/**
 * Returns TRUE if the first specified array contains all elements
 * from the second one. FALSE otherwise.
 *
 * @param {array} superset
 * @param {array} subset
 *
 * @returns {boolean}
 */
function arrayContainsArray (superset, subset) {
  return subset.every(function (value) {
    return (superset.indexOf(value) >= 0);
  });
}
```

Thank you!

**Comment by megawac** [comment]
You can do _.difference(arr1, arr2).length > 0 to achieve this currently

**Comment by slavafomin** [comment]
Thank you @megawac, that's a good point. Consider my proposition as a syntactic sugar then )

**Comment by Alexsey** [comment]
@slavafomin to have even a little bit more straightforward check you could ```_(arr1).difference(arr2).isEmpty()```

**Comment by slavafomin** [comment]
Why closed? It's feature request, not a question.

**Comment by jdalton** [comment]
>  It's feature request, not a question.

Ah, corrected. Thanks for the request. As with other requests we'll track the popularity of the request to see if it's worth adding to core.

**Comment by megawac** [comment]
Should also note this is a dupe of https://github.com/jashkenas/underscore/pull/2100

**Comment by slavafomin** [comment]
@megawac, I believe your suggestion is not valid by the way:

```javascript
_.difference(['A', 'B', 'C', 'D', 'E'], ['A', 'B', 'D']);
// => ["C", "E"]

_.difference(['A', 'B', 'C', 'D', 'E'], ['A', 'B', 'Z']);
// => ["C", "D", "E"]
```

**Comment by megawac** [comment]
@slavafomin wrong order of arrays ^^

```js
_.difference(['A', 'B', 'D'], ['A', 'B', 'C', 'D', 'E']);
// => []
```

**Comment by slavafomin** [comment]
Oh, that makes sense, sorry ))

**Comment by dorthwein** [comment]
+1

**Comment by arcanis** [comment]
This kind of function would be useful for objects too (to check if an object is a superset or subset of another one).

**Comment by PapePathe** [comment]
How can we check if an array includes any of the values of another array

**Comment by arcanis** [comment]
Probably more a StackOverflow question, but anyway

```
a.some(value => b.includes(a))
```

**Comment by PapePathe** [comment]
Cool

**Comment by PapePathe** [comment]
the arrow?

**Comment by megawac** [comment]
Another option is

```js
_.difference(b, a).length === 0
```

Where `b` is the subset array

**Comment by megawac** [comment]
** Amended ** another option is to use intersects, like the original approach

```
_.intersects(subset, superset).length > 0
```

**Comment by navalarya** [comment]
@megawac wouldn;t intersection be wrong ? Intersection doesn;t mean its is really subset. May be we can have _.intersection(subset, superset).length === subset.length

**Comment by megawac** [comment]
@navalarya I think you're confused what I was responding to:
> How can we check if an array includes any of the values of another array

**Comment by navalarya** [comment]
oh ok. my bad. :)

**Comment by ierceg** [comment]
@megawac it's a non-equivalent option: `intersection` does not do short-circuit evaluation which is what is optimal in this case.

**Comment by megawac** [comment]
This really depends on if you're a pestimest (worst case) versus optimist (best case) in terms of O(n). In terms of algorithmic complexity best case is O(n) (`some`+`includes`) or worst case O(n^2) (`difference().length`)

**Comment by ierceg** [comment]
Sure, you will *sometimes* get the worst case and then and only then the
two expressions are equivalent. But this is an edge case. For all the other
cases they are not equivalent and full blown `difference` will just be
wasting your cycles.

**Comment by jdalton** [comment]
Underthehood `intersection` uses `Set` so perf isn't a problem.

**Comment by bhatikuldeep** [comment]
@slavafomin thanks, this is exactly something i was looking for, but it does not work when `subset` is an empty array;

**Comment by slavafomin** [comment]
@bhatikuldeep What the function should return in this case? I think the `false`?

@jdalton How many votes are considered *enough* to implement the feature?

**Comment by jdalton** [comment]
@slavafomin There is no set vote, voting is used as an indicator of request popularity.

**Comment by bhatikuldeep** [comment]
@slavafomin yes, should return `false` but it does not.
```javascript /**
 * Returns TRUE if the first specified array contains all elements
 * from the second one. FALSE otherwise.
 *
 * @param {array} superset
 * @param {array} subset
 *
 * @returns {boolean}
 */
function arrayContainsArray (superset, subset) {
  return subset.every(function (value) {
    return (superset.indexOf(value) >= 0);
  });
}

var array1 = ['A', 'B', 'C', 'D', 'E'];
var array2 = ['B', 'C', 'E'];
var array3 = ['B', 'C', 'Z'];
var array4 = [];


console.log(arrayContainsArray(array1, array4));

**Comment by slavafomin** [comment]
@bhatikuldeep Thanks, I've updated the first comment.

**Comment by thereis** [comment]
@bhatikuldeep Thanks, it works perfectly!

**Comment by DVLP** [comment]
+1
Two small improvements. I bet in lodash there are already this kind of optimizations but I have 2 performance changes I'd add:

- Instead of finding if each element is present with `every` use `some`  to break on first not found element. 
- If subset is larger than superset also return false, depends if we care about **repeated values**
  i.e. arrayContainsArray([1,2,3,4,5], [1,3,3,4,5,5])

```javascript

function arrayContainsArray (superset, subset) {
  if (0 === subset.length || superset.length < subset.length) {
    return false;
  }

  return !subset.some(function (value) {
    return superset.indexOf(value) < 0;
  });
}
```

**Comment by Akxaya** [comment]
Try using Lodash some 
`_.some(arrValues,'Sam') => true /false`

**Comment by tshinnic** [comment]
@DVLP I am concerned about your first point above
> Instead of finding if each element is present with `every` use `some` to break on first not found element.

`.every` and `.some` are alike in that they will early exit when the false condition is detected.  The description of `.every` mentions:
> The every method executes the provided callback function once for each element present in the array until it finds one where callback returns a falsy value. If such an element is found, the `every` method immediately returns false. 

I do appreciate your mentioning that a possible presence of repeated values makes the short length checks useless.  [1,2] is a subset of [1,2,3] but not of [2,2,2]

**Comment by developper89** [comment]
@megawac , your solution does not work for empty subset
_.difference([],[16, 28, 35]).length == 0;

**Comment by Alexsey** [comment]
@developper89 you probably have missed the arguments order: first is `subset` and second is `superset`. So the `_.difference([], [16, 28, 35]).length == 0` means that `[]` is a subset of `[16, 28, 35]` and that is really true

**Comment by developper89** [comment]
@Alexsey Oh yes you are absolutely right ! 
this case has confused me, but mathematically it is 100% true !

**Comment by primeloop** [comment]
Or you can just do

let a = [4,6,7,8,3,6]
let b = [4,2,3,6]

let x = b.map(x=> a.includes(x))
x.includes(false) // Returns True if its not a subset, and False if it's a subset

**Comment by Alexsey** [comment]
@primeloop you can do it even in one line
```javascript
b.every(v => a.includes(v)) // true if b is a subset of a and false otherwice
```
but the complexity of this solution would be `O(a.length * b.length)` while `differenct` (from what I remember) is using `Set` inside, so the complexity would be `O(a.length + b.length)`

**Comment by ashoksahoo** [comment]
let a = [4,6,7,8,3,6]
let b = [4,2,3,6]

_.intersection(a,b).length === b.length;

**Comment by Jokero** [comment]
Looks like a lot of people are interested in the new function 😄

**Comment by urlimited** [comment]
> Hello!
> 
> Thank you for this great library.
> 
> However, please consider adding a function to find if specified array includes all elements from another specified array.
> 
> Here's the related question on SO: http://stackoverflow.com/questions/8628059/check-if-every-element-in-one-array-is-in-a-second-array
> 
> Concept:
> 
> ```js
> var array1 = ['A', 'B', 'C', 'D', 'E'];
> var array2 = ['B', 'C', 'E'];
> var array3 = ['B', 'C', 'Z'];
> 
> _.includes(array1, array2); // => true
> _.includes(array1, array3); // => false
> ```
> 
> Solution in vanilla JavaScript for modern browsers:
> 
> ```js
> /**
>  * Returns TRUE if the first specified array contains all elements
>  * from the second one. FALSE otherwise.
>  *
>  * @param {array} superset
>  * @param {array} subset
>  *
>  * @returns {boolean}
>  */
> function arrayContainsArray (superset, subset) {
>   if (0 === subset.length) {
>     return false;
>   }
>   return subset.every(function (value) {
>     return (superset.indexOf(value) >= 0);
>   });
> }
> ```
> 
> Thank you!

But, this is not correct, since if superset array, for example:
[0,0,0], and subset is [1,0,2], the arrays are not identical, however, the algorythm provided by you would lead to wrong results

**Comment by gino8080** [comment]
> You can do `_.difference(subset, superset).length === 0` to achieve this currently

great and clean solution

**Comment by strottos** [comment]
Thanks for the workaround but I personally think the original suggestion is clearer still. I'd prefer to see in code:
```
_.includes(subset, superset)
```
than
```
_.difference(subset, superset).length === 0
```
as it's much more readable and could be added in lodash with the workaround. Though it's not a bad workaround and thanks for it all the same, I will still use it most likely.

**Comment by ar-to** [comment]
not sure if this was solved exactly. I was working on a simple version of this and ended up going with the `isSuperSet` function at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#implementing_basic_set_operations instead of the solutions with `_.includes` or `_.difference` because the boolean returned was not correct. Below is my basic training set 

```javascript


function isSuperSet(set, subset) {
  // if the set does not have it then its not a superset
  for (let e of subset) {
    if (!set.has(e)) return false;
  }
  return true;
}

setA = new Set(["admin","editor","visitor","demo"])
setB = new Set(["demo", "visitor"])
setC = new Set(["demo2"])
setD = new Set([])

const isSS = isSuperSet(setA, setB)
const isSS2 = isSuperSet(setA, setC)
const isSS3 = isSuperSet(setD, setA)// supports empty superset
console.log('isSS: ',isSS, 'isSS2: ',isSS2,'isSS3: ',isSS3) // => isSS:  true isSS2:  false isSS3:  false
```
Maybe I did something wrong but i got opposite booleans so if the solution exists may we can update the documentation. Or I would recommend adding set operations to lodash in general.

**Comment by isti115** [comment]
In case anyone ends up looking at this issue in the future, they might be interested to know that an [`.isSubsetOf` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/isSubsetOf) has been added to JavaScript `Set`s and is now [pretty widely available](https://caniuse.com/?search=isSubsetOf).
