### ISSUE TITLE
add _ getter for value call for lodash v4+

### ISSUE THREAD

**Issue by Alexsey** [lodash/lodash#1744]
There is a very handful sugar to ```chain``` method when we could just wrap value in ```_``` call. Now, when ```Lodash``` finally drop support of IE 8 and IE 9 is supporting getters we could add symmetric sugar to ```value``` with adding getter ```_``` that is calling ```value``` on read and so unwrap would become as easy as wrap. Example:
```
let a = [{x: 1}, {x: 2}, {x: 3}]

_(a).map('x').takeWhile(v => v < 3).value() // was

_(a).map('x').takeWhile(v => v < 3)._       // become
```

**Comment by jdalton** [comment]
Hi @Alexsey!

I like the explicitness of a function call over a getter.
