### ISSUE TITLE
importing methods with rollup

### ISSUE THREAD

**Issue by ritz078** [lodash/lodash#1745]
Is there something wrong with this ?

```js
import cloneDeep   from 'lodash-es/lang/cloneDeep'
import merge       from 'lodash-es/obj/merge'
```

rollup is showing the following error.

```
/Users/ritz078/projects/embed.js/node_modules/lodash-es/internal/root.js: 'import' and 'export' may only appear at the top level (31:0)
```

rollup plugin config : 

```js
plugins      : [
	npm({
		jsnext: true,
		main  : true
	}),
	commonjs({
		include: 'node_modules/**'
	}),
	babel()
]
```

**Comment by jdalton** [comment]
I know rollup works with our v4 release (publishing in the morning).
I haven't heard of issues with earlier ones though.

\cc @megawac

**Comment by megawac** [comment]
I see you have rollup-plugin-babel included. Possibly related
https://github.com/rollup/rollup-plugin-npm/issues/4

On Mon, Jan 11, 2016 at 2:48 PM, John-David Dalton <notifications@github.com

**Comment by brandonaaron** [comment]
Stumbled upon this older/closed issue via google and thought I'd contribute what worked for me. It appears the commonjs plugin is also trying to parse through lodash-es. So, I added the following to my config to resolve the issue:

```
commonjs({
  exclude: ['node_modules/lodash-es/**']
})
```
