### ISSUE TITLE
[Question] object method to map keys and values

### ISSUE THREAD

**Issue by cbargren** [lodash/lodash#1746]
I was wondering if there's a method that does the behavior of both `mapKeys` and `mapValues` in one. So for example:
```javascript
var obj = { 'key': 'value' };
_.mapBoth(obj, keyFunc, valueFunc);  // { 'newKey': 'newValue' }
```
If not, would this be something that would be desirable for the lodash library?

**Comment by jdalton** [comment]
If you're in to transforming both you could use `_.transform` (it's a fancy `reduce`).

**Comment by cbargren** [comment]
Awesome, thanks so much!
