### ISSUE TITLE
Release notes missing for 4.0

### ISSUE THREAD

**Issue by piotrd** [lodash/lodash#1748]
Hi,

An oversight, I think: in Changelog there is a link to Release notes for v.4.0.0 (https://github.com/lodash/lodash/releases/tag/4.0.0), but there's nothing under that location yet.

**Comment by megawac** [comment]
The release notes are stored on the Wiki: https://github.com/lodash/lodash/wiki/Changelog

**Comment by jdalton** [comment]
Yay! :tada: Release notes will  happen once a release is tagged. Sometime today.
