### ISSUE TITLE
_.flatten function changed?

### ISSUE THREAD

**Issue by bbkingtw** [lodash/lodash#1749]
Hi, I wrote a small piece of code for test _.flatten. the code is as below
```js
objects = [{ 'a': [1] }, { 'a': [2, 3] }];
console.log(_.flatten(objects, 'a')); 
version<=2.4.2 the result is [ 1, 2, 3 ]
```
but while I use version>=3.0.0 result is `[ { a: [ 1 ] }, { a: [ 2, 3 ] } ]`

I got some confused here, is there any definition change for this function?

So I try `_.flattenDeep`, the result is the same==> `[ { a: [ 1 ] }, { a: [ 2, 3 ] } ]`

Is there any compatible way to return `[1,2,3]` as usual?

**Comment by jdalton** [comment]
In Lodash v2 `_.flatten` flatten supported an `iteratee`.
In Lodash v3 support was dropped in favor of method composition.
In Lodash v4 it was added as `_.flatMap`.

**Comment by bbkingtw** [comment]
Thanks a lot, _.flatMap solve my problem..
