### ISSUE TITLE
Can the version 3 docs be put online?

### ISSUE THREAD

**Issue by curiousdannii** [lodash/lodash#1750]
Congratulations on publishing version 4! I will definitely be taking a look at it.

But until we all migrate our projects over, could you please add the version 3 docs back online?

(If anyone else is looking for them, you can read them [here](https://github.com/lodash/lodash/tree/3.10.1/doc).)

**Comment by jdalton** [comment]
Hi @curiousdannii!

I've updated the dropdown in the docs to [include a link](https://github.com/lodash/lodash/blob/3.10.1/doc/README.md) to the v3.10.1 docs.

**Comment by lolmaus** [comment]
Why did you removed the web-friendly version in favor of raw text?

**Comment by jdalton** [comment]
Old docs have always gotten the redirect to the tagged release while the site is for the current. Nothing new there.
