### ISSUE TITLE
Flip arguments in split

### ISSUE THREAD

**Issue by ncammarata** [lodash/lodash#1752]
Couldn't find this listed in any other issues, but perhaps I'm looking in the wrong place. For some reason I can't post issues in lodash/fp, and my understanding is that lodash/fp and lodash are merging. Happy to change where this is posted if it's not listed correctly.

```js
import { flow, flip, map, capitalize, toUpper, take, split } from 'lodash/fp'

const initials = flow(
  (s => s.split(' ')),
  map(take(1)),
  map(toUpper)
)
```

it seems to make more sense to flip the arguments so I can use 

```js
import { flow, flip, map, capitalize, toUpper, take, split } from 'lodash/fp'

const initials = flow(
  split(' '),
  map(take(1)),
  map(toUpper)
)
```

splitting on the value isn't as valuable with this paradigm of coding as a curried function to split something

**Comment by jdalton** [comment]
Thanks for checking it out. I'll bump tonight. <Waves hands, you seen nooothing nooothing>

**Comment by ncammarata** [comment]
Wow that was fast. Thank you!

**Comment by jdalton** [comment]
Thank you for testing. I expect a few more to shake out. I've also added [replace](https://github.com/lodash/lodash/commit/7dcf8692bbbac3917beacc3ee3d1bf330cb23d21) to the fp mapping. Let me know if you see any others.
