### ISSUE TITLE
Question: Congrats on v4 release, npm packages release?

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1756]
Congratulations on your v4 release, I've been looking forward to getting my hands on some of these elements.

Any idea, roughly, when you will be publishing the npm packages?

Again, congrats!

**Comment by jdalton** [comment]
Probably in the next day or so. I usually stagger it a bit to make sure I didn't miss something critical.

**Comment by jdalton** [comment]
Thanks for your help!

**Comment by Xotic750** [comment]
Ok, that's great! You're welcome.
