### ISSUE TITLE
lodash-es you no longer import by category - not mentioned in changelog

### ISSUE THREAD

**Issue by lukeapage** [lodash/lodash#1757]
previously

```
import arrayRemove from 'lodash-es/array/remove';
```
now
```
import arrayRemove from 'lodash-es/remove';
```

I can't find this in the changelog.. so is it intentional or a bug?

**Comment by jdalton** [comment]
It's intentional. I mention paths in the [release notes](https://github.com/lodash/lodash/releases/tag/4.0.0) but will add a note to the changelog.

**Comment by lukeapage** [comment]
thanks, FYI I hit this bug in rollup with lodash v4 - https://github.com/rollup/rollup-plugin-commonjs/issues/30

**Comment by jdalton** [comment]
Thanks for the added info!
