### ISSUE TITLE
Wrong dependency in lodash.merge 

### ISSUE THREAD

**Issue by michaelcontento** [lodash/lodash#1759]
`lodash.merge` depends on `lodash._stack@3.0.0` which is not published at all. 

Source: https://github.com/lodash/lodash/blob/npm-packages/lodash.merge/package.json#L20

So if one tries to install `lodash.merge` npm will fail with:

```
npm ERR! No compatible version found: lodash._stack@^3.0.0
npm ERR! Valid install targets:
npm ERR! ["4.0.0"]
```

IMHO the required version should be `4.0.0`!?

**Comment by jdalton** [comment]
Dep of #1760.
