### ISSUE TITLE
Mapcache Dependency Error in lodash.memoize

### ISSUE THREAD

**Issue by cwbuecheler** [lodash/lodash#1760]
Greets,

I'm try to install lodash.memoize via NPM. It's failing on a dependency error both when installed via package.json with `npm install` and when installed manually with `npm install lodash.memoize`. Here's the error:

```
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/chris/.nvm/versions/node/v5.4.1/bin/node" "/Users/chris/.nvm/versions/node/v5.4.1/bin/npm" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12

npm ERR! No compatible version found: lodash._mapcache@^3.0.0
npm ERR! Valid install targets:
npm ERR! 4.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

The line in my package.json is: `"lodash.memoize": "^3.0.4",` and I get the same error if I change that to `"loadash.memoize": "^3.1.0"` which seems to be the latest version of memoize.

If I'm screwing something up, please let me know!

**Comment by inakianduaga** [comment]
Same here, it was working about 1 hour ago (I had just tried pulling all dependencies), and now doesn't anymore

**Comment by jdalton** [comment]
Yap, looks like the dep for `lodash_.setcache`, `lodash._stack`, and `lodash._mapcache` got messed up.

**Comment by alvov** [comment]
Also seems like loadesh.rest@4.0.0 cannot be found:
```
npm ERR! version not found: lodash.rest@4.0.0
```

**Comment by jdalton** [comment]
@alvov https://www.npmjs.com/package/lodash.rest

**Comment by cwbuecheler** [comment]
Seems to be working now. Thanks!

**Comment by franksama** [comment]
I'm still getting

```
No compatible version found: lodash._stack@'>=3.0.0 <4.0.0'
```

**Comment by jdalton** [comment]
Fixed with lodash.memoize@3.1.1 and bumped to lodash.memoize@4.0.0.

**Comment by franksama** [comment]
thanks, works now!
