### ISSUE TITLE
Auto Currying in lodash/fp

### ISSUE THREAD

**Issue by RGBboy** [lodash/lodash#1764]
Is this a bug or is my understanding of the new `lodash/fp` incorrect. Can I call `isEqual` as if it is auto-curried?

``` Javascript
const isEqual = require('lodash/fp').isEqual;

console.log(isEqual(1, 1)) // true
console.log(isEqual(1)) // false ???
console.log(isEqual(1)(1)) // Error
```

**Comment by jdalton** [comment]
It was an oversight. Thanks for spotting it.

**Comment by RGBboy** [comment]
Thanks for the quick fix :+1: 

(And all your other work on lodash)
