### ISSUE TITLE
Arguments for pickBy predicate

### ISSUE THREAD

**Issue by juriejan** [lodash/lodash#1765]
It seems that the ```pickBy``` function in latest version (4.0.0) doesn't provide the ```(value, key)``` arguments as before. Is this intentional or something that still needs to be implemented?

**Comment by jdalton** [comment]
Yes this is intentional all "By" methods are restricted to passing just the `value`.

**Comment by jridgewell** [comment]
What's the reasoning?

**Comment by jdalton** [comment]
Simplicity and ease of composition. "By" methods are really only interested in transforming a value to use  in place of the real value.

**Comment by geoffreak** [comment]
How do you recommend I filter out key/value pairs of an object depending on the key then?

**Comment by jridgewell** [comment]
Likely `_.transform` will be your best bet.

**Comment by geoffreak** [comment]
Wow, what a regression.

**Comment by geoffreak** [comment]
Sorry if I came off as rude with that last comment, but how can you argue that this is for ease of composition?

```coffee
# Lodash 3.x
namesObj = _.pick namesObj, (count, name) -> count > 1 or name.length >= 4

# Lodash 4.x
namesObj = _.transform namesObj, (result, count, name) ->
  result[name] = count if count > 1 or name.length >= 4
, {}
```

**Comment by billyjanitsch** [comment]
I also find it surprising that `pick` is *only* by key, whereas `pickBy` is *only* by value.

```js
const obj = {a: 1, b: 2, c: 3}
pick(['a, b'], obj)
pickBy(x => x % 0, obj)
```

Given that `pick` specifically is meant to pick keys, it's especially weird that `pickBy` can't access those keys at all.

**Comment by megawac** [comment]
+1

**Comment by jdalton** [comment]
@billyjanitsch 
> I also find it surprising that `pick` is *only* by key, whereas `pickBy` is *only* by value.

It's key vs. transformed value

The primary focus of these "By" methods is on the element and the transformation to them. Providing 1 argument simplifies things and improves consistency. As with other FP mentions it also helps with common transforms like using `parseInt`. 

You can see bits of this even in Underscore with their `_.sortedIndex` method which is our `_.sortedIndexBy`.

**Comment by billyjanitsch** [comment]
> It's key vs. transformed value

Right, but what about transformed key? Does that not seem like a case worth supporting?

**Comment by jdalton** [comment]
> Right, but what about transformed key? Does that not seem like a case worth supporting?

That's outside the scope of the method and outside the general use case for methods like this. I'm fine suggesting folks create their own mixins when things go outside the supported and common case.

**Comment by jdalton** [comment]
On top of that lodash is modular with v2, v3, and v4 [method packages available](https://www.npmjs.com/browse/keyword/lodash-modularized) if you really want to cherry-pick older functionality.

**Comment by billyjanitsch** [comment]
My point is that the general form of `x` and `xBy` methods is: `xBy(...args, identity) === x(...args)`. This is the case for:

- `difference`
- `intersection`
- `pullAll`
- `sortedIndex`/`sortedLastIndex`
- `uniq`/`sortedUniq`
- `union`
- `xor`
- `max`/`min`
- `sum`

`pick` and `omit` are the only exceptions, where `pickBy` and `omitBy` are fundamentally different operations.

Happy to write my own mixin; this just seems odd from a consistency standpoint.

**Comment by jdalton** [comment]
Yap, `pick` and `omit` are odd ones. Not really a `without` and not really ` filter`.
I rather expose the internal object variants.

**Comment by billyjanitsch** [comment]
> Lodash v4 focused on splitting out overloaded functionality and simplifying the scope of methods

This is a great goal and I realize you don't want to bloat the lodash API. Thanks for tolerating this discussion. One more perspective:

 | Map | Filter
----- | ----- | -----
Default | `map` => Array | `filter` => Array
Keys | `mapKeys` => Object | ?
Values | `mapValues` => Object | ~~`filterValues`~~ `pickBy` => Object

The current `pickBy` is essentially a `mapValues` for `filter` in that it does the same operation as `filter` but preserves the original keys. The only difference is that `mapValues`'s iteratee gets (value, key, collection) instead of just (value). What is the logic behind giving key and collection to `mapValues`?

I almost want to propose renaming the current `pickBy` to `filterValues`, because, behaviorally, `map`:`mapValues`::`filter`::`pickBy` is a lot more symmetric than `sum`:`sumBy`::`pick`:`pickBy`.

That also begs the question of `filterKeys`, whose absence was the catalyst for this discussion.

**Comment by jdalton** [comment]
>  Thanks for tolerating this discussion.

I'm not a fan of discussion for the sake of discussion. I prefer less typing to walls of text.

> What is the logic behind giving key and collection to `mapValues`?

It's a map function so treated more like `_.map`.

> That also begs the question of `filterKeys`, whose absence was the catalyst for this discussion.

There is no need for a two flavors of an object filter because an omission is an omission regardless of key or value. Map on the other hand can map to a key or value.

**Comment by billyjanitsch** [comment]
> It's a map function so treated more like `_.map`.

`pickBy` is a filter function so treat it more like `filter`? (which also receives key/collection)

> an omission is an omission regardless of key or value

But you can't decide to omit a key with an iteratee if it only receives the value.

**Comment by jdalton** [comment]
> `pickBy` is a filter function so treat it more like `filter`? (which also receives key/collection)

Naw that functionality was crammed in after the fact. Like I said it's not really a `without` function and not really a `filter` function.

> But you can't decide to omit a key with an iteratee if it only receives the value.

Map provides both.

**Comment by curiousdannii** [comment]
Hi @jdalton, I'm trying to figure out how to port my v3 .pick() code to v4.

Say I had this, to filter out objects with even keys

```
_.pick( { ... }, function( value, key ) { return +key % 2 } )
```

_.map won't remove elements which get replace with falsey, and _.filter returns only the values, losing the keys.

The simplest solution I can think of is the following. Is there a better option?

```
_.pickBy( _.map( { ... }, function( value, key ) { if ( +key % 2 ) return value } ) )
```

**Comment by jdalton** [comment]
Y'all are gonna make me add back the `key` param aren't y'all.

**Comment by juriejan** [comment]
I was using v3 ```pick``` in the following fashion:

```
var a = {a:1, b:2, c:3}
var b = {a:true, b:false, c:true}
var result = _.pick(a, function (v, k) { return b[k] })
assert.equal(result, {a:1, c:3})
````

I can achieve the same goal in v4 using the following:
```
var a = {a:1, b:2, c:3}
var b = {a:true, b:false, c:true}
var result = _.pick(a, _.keys(_.pickBy(b)))
assert.equal(result, {a:1, c:3})
```

Another way to solve the problem posed by @curiousdannii would be using the following:
```
var a = {1: 'a', 2: 'b', 3: 'c'}
var result = l.pick(a, l.filter(l.keys(a), function (key) { return +key % 2 }))
assert.equal(result, {'1': 'a', '3': 'c'})
```

It takes a bit of mental gymnastics to get to these solutions, but no more than it would take to solve similar problems. The reasoning behind this change appeals to me.

**Comment by jdalton** [comment]
Naw the alt ways are super gross. The proper way to handle this would have been with exposed object-forms of the collection methods. I'll note that for the next go. For now I'll bend and allow `key` for `omitBy` and `pickBy` for lack of a better option.

**Comment by screendriver** [comment]
:+1: 
Same here. I have used the old `pick` to compare two objects by key equality. Now with `pickBy` I can't do that easily.

**Comment by thomaswrenn** [comment]
👍

**Comment by demoneaux** [comment]
The `key` argument has already been added back to `_.pickBy` and `_.omitBy` in 3eaa7b3.
