### ISSUE TITLE
Needs to address zipObject v.s. fromPairs backwards incompatibility on Changelog

### ISSUE THREAD

**Issue by chibicode** [lodash/lodash#1766]
It seems that in `3.1.0`, `zipObject` accepts a single array:
https://github.com/lodash/lodash/blob/3.10.1/doc/README.md#_zipobjectprops-values

But in `4.0.0`, it only accepts two arrays, and `fromPairs` is now used for single array arguments.
https://lodash.com/docs#zipObject
https://lodash.com/docs#fromPairs

This seems like a backwards-incompatible change but it doesn't seem to be documented here:
https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings

Wanted to confirm before making any changes on the wiki.

**Comment by jdalton** [comment]
You're right feel free to edit the wiki.

**Comment by EyePulp** [comment]
This just bit me - @chibicode Good catch, lots of code to fix. =)

**Comment by jdalton** [comment]
This has been addressed in edge master branch with _.zipObjectDeep.

**Comment by jdalton** [comment]
Related to #1790.
