### ISSUE TITLE
[website] Minified build download link points to 'compat' build

### ISSUE THREAD

**Issue by ronjouch** [lodash/lodash#1767]
Looks like https://lodash.com/#download links are incorrect:

* Core build (4kB minified) → As expected, links to https://raw.github.com/lodash/lodash/4.0.0/dist/lodash.core.js and https://raw.github.com/lodash/lodash/4.0.0/dist/lodash.core.min.js
* Full build (20kB minified) → First link is https://raw.github.com/lodash/lodash/4.0.0/dist/lodash.js (good), but 'minified' link goes to lodash-compat rather than lodash : https://raw.github.com/lodash/lodash-compat/4.0.0/lodash.min.js

Sounds wrong, right?

**Comment by jdalton** [comment]
Fixed thanks!
