### ISSUE TITLE
lodash.trim broken

### ISSUE THREAD

**Issue by julien-f** [lodash/lodash#1769]
Same thing for lodash.trim@3 and lodash.trim@4:

```
> npm i lodash.trim
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "lodash.trim@3"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.2

npm ERR! No compatible version found: lodash._charsstartindex@^3.0.0
npm ERR! Valid install targets:
npm ERR! 4.0.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
```

It broke our software :/

**Comment by chadly** [comment]
Just to confirm this is happening for us, too

**Comment by jdalton** [comment]
Yep, it's a bug I'll be tackling today. Related to #1760.

**Comment by memoryhole** [comment]
We are seeing this as well. @jdalton do you have an ETA on getting the packages back into the registry?

**Comment by chadly** [comment]
@memoryhole a workaround is to change your `package.json` to `"lodash.trim": "~3.0.1"` from `"lodash.trim": "^3.0.1"`

This will make it pull `v3.0.x` rather than `v3.x` until the issue with `v3.1` is fixed.

**Comment by jdalton** [comment]
I bumped lodash.trim@3.1.1 to resolve the dependency issue.

**Comment by memoryhole** [comment]
@jdalton Thanks!
