### ISSUE TITLE
Looking for non-existent lodash.keys 4.0.0

### ISSUE THREAD

**Issue by rmechamatadobe** [lodash/lodash#1771]
Hi, I'm not sure if this is really a lodash issue or even if this is write place to report it but after some release done on Jan 12, 2016 release I cannot npm install without getting the error:

No compatible version found: lodash.keys@'>=4.0.0 <5.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["2.0.0","2.1.0","2.4.0","2.4.1","2.2.0","2.2.1","2.3.0","3.0.0","3.0.5","3.0.6","3.0.7","3.0.1","3.1.0","3.0.2","3.1.1","3.0.3","3.1.2","3.0.4"]
npm ERR! notarget 

Tried installing:
npm install lodash.keys@4.0.0 with no success.

As I stated above, this may have nothing to do with lodash but thought I'd report it in case there was something someone knew about my problem.

Thanks in advance for any help or guidance you can provide.

**Comment by jdalton** [comment]
That's odd. I see it here https://www.npmjs.com/package/lodash.keys. Smth is fishy. I wonder if a hiccup happened while I was publishing or maybe a registry glitch. Will keep an eye on it.
