### ISSUE TITLE
In lodash/fp, `flow`, `flowRight`, etc. should implement auto-currying

### ISSUE THREAD

**Issue by billyjanitsch** [lodash/lodash#1775]
In Ramda (and fp in general), functions created by `pipe` and `compose` are automatically curried.

```js
const times = (a, b) => a * b
const plusFive = c => c + 5

// Ramda
const timesPlusFive = pipe(times, plusFive)
timesPlusFive(5, 3) // => 20
timesPlusFive(5)(3) // => 20

// lodash/fp
const timesPlusFive = pipe(times, plusFive)
timesPlusFive(5, 3) // => 20
timesPlusFive(5)(3) // => TypeError (timesPlusFive isn't curried)
```

Thoughts on aligning these?

**Comment by jdalton** [comment]
I believe there was some discussion and back and forth on this. We don't try to preserve `function.length` so arity would have to be inferred. For now we'll punt to `_.curry` for that.
