### ISSUE TITLE
lodash/fp _.lte is not curried

### ISSUE THREAD

**Issue by N0ps32** [lodash/lodash#1776]
I updated from lodash 3.x to 4.0 and suddenly \_.lte is not curried.
This is not a huge deal because you can just do something like "const lte = \_.curry(\_.lte)" but I was a bit surprised by that behavior.

Is this intentional?

**Comment by jdalton** [comment]
`_.lte` was never curried in `lodash`. Are you thinking of `lodash-fp`?
If you want that you can do `require('lodash/fp').lte`.

**Comment by N0ps32** [comment]
That is what I imported. I was using lodash-fp and updated to lodash/fp 4.0 sorry for wording it weirdly.
I required the "lodash/fp.js" file using browserify and the object does not have curried lte. Other methods are curried though and work as expected.

You can reproduce it by running this with node:
```
var _ = require('lodash/fp');
console.log(_.lte(0));
```
Expected output would be a function but instead you get "false".

**Comment by jdalton** [comment]
Thanks for clarifying. I've added them to the fp mapping.

**Comment by N0ps32** [comment]
Awesome, thank you very much! :)

**Comment by jdalton** [comment]
I'll be bumping tonight with updates. I expect these things to shake out in the next day or so.
It's the normal major bump bug out that comes when it goes from 1 pair of eyes on code to thousands.
