### ISSUE TITLE
No compatible version found: lodash._stack@^3.0.0

### ISSUE THREAD

**Issue by chrissrogers** [lodash/lodash#1778]
Looks like older versions of `lodash._stack` may have been unpublished from npm following the v4.0.0 release.

See npm/npm#11133 for detailed log information

**Comment by jdalton** [comment]
Hi @chrissrogers!

This is related to #1760. I scripted the wrong version version. I have it fixed locally will bump soon.

**Comment by janitza-jamu** [comment]
still not working

**Comment by jdalton** [comment]
@janitza-jamu Which package?

**Comment by chrissrogers** [comment]
Looks like `lodash._stack` is still only released as 4.0.0 and 4.0.1

```bash
$ npm view lodash._stack
{ name: 'lodash._stack',
  description: 'The internal lodash function `Stack` exported as a module.',
  'dist-tags': { latest: '4.0.1' },
  versions: [ '4.0.0', '4.0.1' ],
...
```

**Comment by jdalton** [comment]
Which package is trying to access an earlier version?

**Comment by jdalton** [comment]
The issue is no package should be referencing an earlier version of `lodash._stack` because it was only released as 4+. So if a package is referencing v3 that would be an error. But until you tell me the package I cannot fix the issue.

**Comment by janitza-jamu** [comment]
We are using so many packages and we are not using lodash ourselfs... i am going to find out...

**Comment by jdalton** [comment]
Make sure you're using a range like `^4.0.0` so you get the updates I did for `4.0.1`.

**Comment by janitza-jamu** [comment]
lodash.merge is downloaded as version 4.0.0 and uses lodash._stack in ^3.0.0

**Comment by janitza-jamu** [comment]
this dep is coming from "grunt-compile-handlebars@2.0.0" which wants "lodash.merge@>=2"

**Comment by jdalton** [comment]
Have you cleared your `node_modules` folder and cache. You should be getting `lodash.merge` v4.0.1.

**Comment by jdalton** [comment]
See https://www.npmjs.com/package/lodash.merge

**Comment by janitza-jamu** [comment]
Just did... i guess its now only a proxy related issue... thank you very much
