### ISSUE TITLE
Curry placeholder in lodash/fp

### ISSUE THREAD

**Issue by billyjanitsch** [lodash/lodash#1780]
It would be nice if lodash/fp could alias `curry.placeholder` to either `_` or `__`, as in:

```js
import {_, add} from 'lodash/fp' // or __
add(_, 2)(3) // => 5
```

Because it's overly verbose to do:
```js
import {curry, add} from 'lodash/fp'
add(curry.placeholder, 2)(3) // => 5
```

The following works, but it's surprising and semantically weird to have to do this. It also prevents tree-shaking if a shakeable `fp` ever finds its way into `lodash-es`.
```js
import _, {add} from 'lodash/fp'
add(_, 2)(3) // => 5
```

(We currently lint against importing the monolith `_`, preferring named imports.)

**Comment by StreetStrider** [comment]
@billyjanitsch, you could `import as`, couldn't you?

**Comment by billyjanitsch** [comment]
Not really, because you can't destructure imports:

```js
// the best you can do is:
import {add, curry as _} from 'lodash/fp'
add(_.placeholder, 2)(3)

// this doesn't work, and is really verbose anyway:
import {add, curry: {placeholder as _}} from 'lodash'
```

**Comment by jdalton** [comment]
I'll add the placeholder wiring to `lodash/fp`. It's only a few lines to setup.

**Comment by billyjanitsch** [comment]
@jdalton 

By the looks of it, 7544166d11a547cc14588c9c65378d856195425a doesn't actually alias the placeholders to `_`/`__`. Do you mind giving my original post another look?

**Comment by jdalton** [comment]
I added placeholder support I didn't alias them. Aliasing them would be another request.

**Comment by jdalton** [comment]
@billyjanitsch Want to create a PR for the `__` alias?
