### ISSUE TITLE
_.reduce()(obj) from lodash/fp does not send in Key

### ISSUE THREAD

**Issue by FuzzOli87** [lodash/lodash#1781]
```javascript
import { reduce } from 'lodash/fp';
import { reduce as normReduce } from 'lodash';

const testObj = { hello: 12, hi: 21 };

const red = reduce((arr, n, key) => {
  arr.push({ [n]: key });
  return arr;
}, []);

const redNorm = normReduce(testObj, (arr, n, key) => {
  arr.push({ [n]: key });
  return arr;
}, []);

const resultFP = red(testObj);

console.log(resultFP); // => [ { '12': undefined }, { '21': undefined } ]
console.log(redNorm); // => [ { '12': 'hello' }, { '21': 'hi' } ]

```

The FP version of reduce, as you can see, does not return the key correctly. Judging from the release notes, it should work like I imported it, right?

**Comment by jdalton** [comment]
The fp style limits the number of params for callbacks to aid in composition.
If you'd like to create a wiki page to start documenting these that would rock.

**Comment by billyjanitsch** [comment]
I'm happy to work on the wiki if I can find the time.

In this case, how does limiting the number of params help with composition? I don't see why calling the iteratee with (potentially) extra arguments would ever be a problem.

**Comment by jdalton** [comment]
The classic example is:
```js
_.map(['6', '8', '10'], parseInt);
// → [6, NaN, 2]
fp.map(parseInt)(['6', '8', '10']);
// → [6, 8, 10]
```

**Comment by billyjanitsch** [comment]
I understand, but I don't see why it's an fp-specific issue (your example seems to confirm this).

It only crops up in rare edge cases, and you can use `ary` to guard against it. In general, having extra argument(s) is either useful or has no impact. I assume that's the logic for including the extra args in lodash -- why does the same argument not apply for lodash/fp?

**Comment by jdalton** [comment]
fp is designed to cater more towards the fp and compositional crowd.
In those circles extra params cause problems for composition, as the example shows, and fp avoids those issues.

**Comment by jdalton** [comment]
@DrBoolean, care to summarize why capping args helps with composition?

**Comment by DrBoolean** [comment]
@jdalton is totally correct. Mainly it's a currying issue:

```
var greet = curry(name, job) => `My name is ${name} and I am a ${job}`)
var partially_applied_greets = map(greet, ['bob', 'ann'])

map(f => f('programmer'), partially_applied_greets)
map(f => f('alcoholic'), partially_applied_greets)
```
If we got an extra index the whole thing would fall apart because `greet` would be called with two args. Basically currying and variadic arguments aren't compatible.

**Comment by billyjanitsch** [comment]
@jdalton From my experience in fp, I wouldn't characterize it quite that way. *Optional* (variadic) arguments certainly cause problems for composition, and capping arguments to exclude such arguments is very useful. But this isn't a case of optional arguments; we're not talking about *sometimes* passing the key. We're just proposing a different function signature -- (accumulator, value, key) vs. (accumulator, value) -- which fp is perfectly capable of handling. fp's `map` and `reduce` typically don't include the index/key, but that's only by convention; the use case for it comes up a *lot* in JS development.

@DrBoolean's example has an easy fix, when map is called with (value, index):

```js
const greet = curry((name, job) => `My name is ${name} and I am a ${job}`)
// knowing map's iteratee signature, we guard against the extra argument:
const partially_applied_greets = map(x => greet(x), ['bob', 'ann'])

// these now work fine:
map(f => f('programmer'), partially_applied_greets)
map(f => f('alcoholic'), partially_applied_greets)
```

Consider this comparison:

 | (accumulator, value) | (accumulator, value, key)
------------- | ------------- | -------------
Iteratee needs key  | impossible | default
Iteratee is agnostic to key | default | default
Iteratee can't handle key | default | requires guarding

I'd argue that in modern fp-centric JS, the first row is a much more common case than the third row. And in the first column, the first row can't be accommodated at all, whereas in the second column, the third row just requires guarding.

If that doesn't convince you, it would at least be nice to include `mapIndexed` and `reduceIndexed` functions, or provide something like Ramda's `addIndex`.

**Comment by DrBoolean** [comment]
I think you're solution suggests that we don't use first class functions and instead use lamdas to manually thread through arguments. I dislike that solution as I prefer a pointfree style when I can achieve it.

The `reduce` above is a formal implementation of a catamorphism, which does not take more than 2 arguments. The FP spec most follow in JS these days is fantasyland which this `reduce` follows perfectly: https://github.com/fantasyland/fantasy-land#foldable

The standard JS version of map and reduce are being "helpful" at the cost of losing some properties that are well known. Here's a (overly complicated) way to to pass an index using comonads for map:
https://gist.github.com/DrBoolean/ee644862f58c4539f371

This comes up often in languages like haskell. One easy solution is to first `zip` the list with a range of indexes. Another is to use the indexed versions as you suggested.
['a', 'b', 'c']

**Comment by jdalton** [comment]
@billyjanitsch 
Our current implementation follows those of existing FP libs and is catered for folks coming from and familiar with it. I'm fine with that being the default for `/fp` as it gets devs where they're at now. Because this is all just fancy wrapping around Lodash we could introduce options to allow devs to dial up or down the fp-ness:

```
var convert = require('lodash/fp/convert');
var _ = convert({
  'capArgs': true,
  'autoCurry': true,
  'immutable': true,
  'rearg': true
});
```

**Comment by billyjanitsch** [comment]
@jdalton 

> Our current implementation follows those of existing FP libs [...] it meets devs where they're at now. 

FWIW, we're coming from Ramda. Their default iteratees are unary, but they also support the indexed case (though they've struggled to find the right API -- first `.idx` and now `addIndex`), which makes Ramda -> lodash/fp migration tricky.

> we could introduce options to allow devs to dial up or down the fp-ness down the road

That sounds great, though I think "capping" ought to be split into two options: variadic arguments (necessary for currying to work at all) and specific arguments (to better conform to fp conventions, like `reduce`).

@DrBoolean 

> The FP spec most follow in JS these days is fantasyland which this reduce follows perfectly: https://github.com/fantasyland/fantasy-land#foldable

Thanks for this link -- that clarifies the convention, and it seems much more reasonable as a default knowing this.

That said, I still think the indexed cases are useful and expected; @jdalton at some point [argued the same](https://github.com/ramda/ramda/issues/452). It would be great to see them supported somehow.

**Comment by jdalton** [comment]
> @jdalton at some point argued the same.

Yep, and `fp` is optional. I'm fine having `fp`the way it is. Lodash has all the methods necessary to wrap and augment methods. I'll treat this like any other feature request. If user demand is there we'll revisit it.

**Comment by jdalton** [comment]
Btw if you want a better guage on the popularity of various FP methods. I [performed a crawl](https://gist.github.com/jdalton/9423cb06f08f7992f3e8) a few months back. I'm pretty happy with Lodash's coverage esp of the top used functions.

**Comment by billyjanitsch** [comment]
> I'll treat this like any other feature request. If user demand is there we'll revisit it.

Totally sensible. One data point:

I just did [a similar crawl](https://gist.github.com/billyjanitsch/5711048dd8b8d7ea6b48) on a modern slice of our codebase. We use both Lodash and Ramda because we prefer the FP style, but occasionally dip into Lodash's more expansive API. We'd like the unify them.

All the instances of Lodash's `map`, `filter`, etc. are places where we need the key/index which Ramda's equivalents don't provide by default.

**Comment by jdalton** [comment]
> I just did [a similar crawl](https://gist.github.com/billyjanitsch/5711048dd8b8d7ea6b48) on a modern slice of our codebase. We use both Lodash and Ramda because we prefer the FP style, but occasionally dip into Lodash's more expansive API. We'd like the unify them.

Great. Once 4.0 shakes out the bugs (give it a 4.0.1 or so) you could use `require('lodash')` and its `require('lodash/fp')` :D

**Comment by ozan** [comment]
Just an FYI that I encountered an analogous gotcha, this time args to `transform`'s iteratee being capped to two. I would suggest that the arity choice is less intuitive than that for `reduce` given than `transform` is listed under "Object" in the docs and is stated to prioritize Object use cases over Array use case. Surely then it is natural to assume that the iteratee arity would be three (i.e. including `key`) rather than two (only `memo` and `value`).

Of course I have a number of ways to work around it, just letting you know that I spent a good chunk of time correcting my mistaken assumption 😄

**Comment by jfmengels** [comment]
Just so you guys know, I made an ESLint rule to warn you when you declare too many args for your iteratee function: https://github.com/jfmengels/eslint-plugin-lodash-fp/blob/master/docs/rules/no-extraneous-iteratee-args.md.

**Comment by gunar** [comment]
For further reference, this is the solution I was able to come up with:
```js
_.reduce((sum, [ key, val ]) => {
  // ...
})({})(_.toPairs(myObject))
```

**Comment by jfmengels** [comment]
In a more compositional pattern:
```js
_flow(
  _.toPairs,
  _.reduce((result, [key, val]) => {
    // ...
  }, initialValue)
)(myObject);
```
The use of destructuring is a nice touch @gunar :)

**Comment by iMoses** [comment]
@jdalton Just a question, should it have been the other way around?
Shouldn't the FP API keep consistency with the original API, as well as the language itself, and the case in which you want to cap arguments be made into the exception?
I suggest that in the next major version it will be changed.
What is your opinion about it?

**Comment by Andarist** [comment]
imho caping them is really good, as most times you dont need them

However I've found myself troubled when Ive actually needed them. Maybe there could be provided some way of using functions with the iteratee uncaped? somethind like `mapValues.uncaped((val, key) => { ... }, obj)`

**Comment by LeoAref** [comment]
@jdalton ☝️

**Comment by dilipkumar2k6** [comment]
Why `'cap': true` as default? Why not default as `false` so that it can match with nonfunctional programming definition?

**Comment by jdalton** [comment]
Hi @dilipkumar2k6!

FP composition favors capping of callback arguments because many don't account for things like `index, object` parameters which can unintentionally complete curries with unexpected inputs.

**Comment by andrew-aladev** [comment]
@jdalton, FP version is not compatible with traditional one. You made it because "many don't account for `index`"? Really?
