### ISSUE TITLE
_.bindAll seems to not be binding anything in 4.0.0

### ISSUE THREAD

**Issue by royvandewater** [lodash/lodash#1782]
I created a gist to demonstrate this issue:
   
https://gist.github.com/royvandewater/bfa94f7e291c467c2778

This code sample works using lodash 3.10.1, but not in 4.0.0.

**Comment by jridgewell** [comment]
Binding all methods was deprecated, you'll need to pass the methods you want to bind now. You can easily do that with:

```js
_.bindAll(obj, _.functions(obj));
```

**Comment by jdalton** [comment]
@royvandewater For more info on changes see the [changelog](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings).

**Comment by ryannichols** [comment]
Why change this? Seems arbitrary, and now inconvenient. Previously we had the terse:
`var myObj = _.bindAll({
...lots of methods
});`

Now you only see the bound behavior if you HAPPEN to scroll all the way to the bottom and notice:

``var myObj = _.bindAll({
...lots of methods
});`
_.bindAll(myObj, _.functions(myObj));`

Very easy to miss, and largely an unnecessary signature change.

**Comment by jdalton** [comment]
Change is part of life. And in this case its a change for the better. Binding all values to an object is sloppy and forcing you to explicitly specify all methods is the lumps you'll have to take.

**Comment by jdalton** [comment]
For what it's worth it also aligns closer to Underscore. So there's no escaping it.

**Comment by jacksonrayhamilton** [comment]
Sorry if the answer is obvious, or if I am missing a previous conversation on this topic...

But why would `_.bindAll` binding all methods automatically be "sloppy?" On the contrary, shouldn't that functionality save one from having to manually maintain a list of methods? e.g., having to remember to edit an array every time someone adds or removes a method could result in errors, such as if you forget to do that, or mishandle a VCS merge conflict on the array.

**Comment by jdalton** [comment]
I've found being explicit helps others know exactly what's being bound and helps prevent accidental issues.

**Comment by megawac** [comment]
Agreed, I've witnessed a lot of bugs spawn from bindAll on an object. @jacksonrayhamilton easy enough to mixin the old behaviour anyway

```js
_.mixin({
  oldBindAll: function(obj) {
      return _.bindAll(obj, _.keys(obj));
  }
})

```

**Comment by jdalton** [comment]
Or use the `lodash.bindall@^3.0.0` https://www.npmjs.com/package/lodash.bindall

**Comment by sourcevault** [comment]
I can see situations where binding to **all** methods would cause issues - especially if the objects are created in an *external* source.

Also for objects with large numbers of methods - binding *each one* all the time would create unnecessary closures if the methods are not used.

However because this is something that is a strong function of use case, I presume its best left to the user to make that call.

anyway @ryannichols @jacksonrayhamilton you could check out the API for [bindall](https://github.com/importvault/bindall).

**Comment by jacksonrayhamilton** [comment]
Why was my comment here deleted?  Also, I've never really got a clear explanation on how bugs spawned from this, and am still curious.

**Comment by jdalton** [comment]
This is an old issue that's been covered with proposed alternatives.
I'm sorry it's not to your satisfaction. You're free to use whatever you want but I'm not interested in humoring you on this. Sorry.

**Comment by jdalton** [comment]
Polluting issue threads with discussions on long settled or removed features isn't great and probably better suited for our [gitter chat](https://gitter.im/lodash/lodash).
