### ISSUE TITLE
_.defaultsDeep is converting 1st level function values to objects

### ISSUE THREAD

**Issue by maddin77** [lodash/lodash#1783]
In 4.0.0
```js
_.defaultsDeep({}, {
    fn: function () {}
});
```
results in:
```js
{
    fn: {}
}
```
which in 3.10.1 resulted in
```js
{
    fn: function ()
}
```

It didn't say anything about this change in the docs/changelog, so i want to make sure that it's supposed to work like that.

For what it's worth:
```js
_.defaultsDeep({}, {
    obj: {
        fn: function () {}
    }
});
```
results in
```js
{
    obj: {
        fn: function ()
    }
}
```
and
```js
_.defaults({}, {
    fn: function () {}
});
```
results in
```js
{
    fn: function ()
}
```
as well.

**Comment by jdalton** [comment]
This is an issue in the way we clone sources to ensure one doesn't augment another.
