### ISSUE TITLE
_.callback removed in v4 instead of _.iteratee

### ISSUE THREAD

**Issue by philBrown** [lodash/lodash#1785]
I noticed the v4 changelog states that the `_.callback` *alias* has been removed however I see in the v3 docs that `_.iteratee` is the alias. Shouldn't `_.iteratee` have been removed instead?

I only ask as I've tried to use the actual methods instead of their aliases for just this reason (in case they're removed).

**Comment by jdalton** [comment]
We dropped `callback` and elevated `iteratee` to the real method to align more closely with Underscore.
