### ISSUE TITLE
fp/replace is broken

### ISSUE THREAD

**Issue by epeli** [lodash/lodash#1788]
I think this should return a function

    var removeJSExt = replace(/\.js$/, "");

but instead it returns `'/\\.js$/'`;

**Comment by jdalton** [comment]
Yep, this is [fixed in our master edge](https://github.com/lodash/lodash/commit/027c5727589b3e6aff9f321c71623a8f5e4a60ce). Though it could use a [unit test](https://github.com/lodash/lodash/blob/master/test/test-fp.js).
