### ISSUE TITLE
_.fromPairs treats pair keys as an object path

### ISSUE THREAD

**Issue by h4l** [lodash/lodash#1790]
The docs say (emphasis mine):

> The inverse of _.toPairs; this method returns an object composed from **key**-value pairs.

It's not acting as the inverse when keys contain `.`, as it's splitting keys on `.` and creating nested objects:

```
$ node
> var ld = require('lodash');
undefined
> ld.VERSION
'4.0.0'
> var pairs = ld.toPairs({'foo.bar': {b: 123}, b: 9})
undefined
> pairs
[ [ 'foo.bar', { b: 123 } ], [ 'b', 9 ] ]
> ld.fromPairs(pairs)
{ foo: { bar: { b: 123 } }, b: 9 }
```

3.10.1 behaviour:

```
$ node
> var ld = require('lodash')
undefined
> ld.VERSION
'3.10.1'
> var pairs = ld.pairs({'foo.bar': {b: 123}, b: 9})
undefined
> pairs
[ [ 'foo.bar', { b: 123 } ], [ 'b', 9 ] ]
> ld.object(pairs)
{ 'foo.bar': { b: 123 }, b: 9 }
```

**Comment by jdalton** [comment]
Related to #1626. \cc @jasonkarns. As a side effect of splitting out the `zipObject` method `fromPairs` is also affected. I think it would be fitting for a `zipObjectDeep`?

**Comment by ucamhal** [comment]
Thanks for the change, that's great.

**Comment by h4l** [comment]
Thanks for the change, that's great.

**Comment by jdalton** [comment]
Added [_.zipObjectDeep](https://github.com/lodash/lodash/commit/dc6e82d5c020452e13987f1c6a6f37a709803eaf).
