### ISSUE TITLE
Docs: forEach / forOwn / forIn incorrectly categorized as chainable

### ISSUE THREAD

**Issue by NicBright** [lodash/lodash#1791]
Hi there,

congrats to the v4 release!

After reading the changelog I've looked some things up in the [docs](https://lodash.com/docs#_) and I think that they're not up-to-date regarding this change:

    Made _.forEach, _.forIn, _.forOwn, & _.times implicitly end a chain sequence

Shouldn't the first three be categorized as  `... wrapper methods that are not chainable by default ...`?

Also: what about the right-to-left versions (e.g. `_.forEachRight`). Does this change apply to them, too? 

Thanks and Regards,
Nicolas

**Comment by jdalton** [comment]
Hi, was wondering if simplifying the changelog would cause confusion. In this case yes right associative forms are also included and yes it's the chained form. I've updated the changelog.

**Comment by NicBright** [comment]
Mhm, I'm still not sure if _.forEach (and _.forIn and _.forOwn and so on) are correctly categorized as "chainable". Because they're not according to the changelog (e.g. _.forEach() implicitly ending chain sequences) ?!

Btw. there seems to be a rendering bug around "The wrapper methods that are **not** chainable by default are:<br>" (markdown and html <br> are shown).

**Comment by jdalton** [comment]
They aren't in the "Sequence" category because they aren't sequence specific. Chaining applies to all static methods and I think the modified changelog covers the difference in behavior fine.

**Comment by jdalton** [comment]
As to the formatting bug it's been fixed in the source, the site will update on our next bump for 4.0.1.

**Comment by NicBright** [comment]
Ah ok I think we're talking past each other. As a screenshot can say more than thousand words:

Here is what I **mean**:

![image](https://cloud.githubusercontent.com/assets/1225659/12350383/fa4e217c-bb76-11e5-8363-36a0686c92ce.png)


Regards,
Nicolas

**Comment by jdalton** [comment]
Ahhhhhhh, thank you!

**Comment by jdalton** [comment]
https://github.com/lodash/lodash/commit/b3d60256c5399ceaf0ec5849891b26c4627cdc77
