### ISSUE TITLE
_.defaultsDeep doesn't handle functions correctly

### ISSUE THREAD

**Issue by n6g7** [lodash/lodash#1792]
In version 4, defaultsDeep doesn't handle assigning defaults functions in objects : 
```js
'use strict';

let _ = require('lodash');

let a = {
  b: {
    c: x => 2 * x
  }
};

_.defaultsDeep(a, {
  b: {
    c: _.identity,
    d: _.identity
  }
});

console.log(a.b.c(1)); // 2 - OK
console.log(a.b.d(1)); // 2 - Meh, was expecting 1 :(
```
I believe this is linked to the use of `_.identity` (or perhaps it is simply because `b.c === b.d` in the source object) because using custom (and different) functions for `b.c` and `b.d` fixes it.

**Comment by n6g7** [comment]
I've experimented further and I discovered more weird behaviours : 
```js
'use strict';

let _ = require('lodash');

let a = {
  b: {}
};

_.defaultsDeep(a, {
  b: {
    c: _.identity
  }
});

console.log(a.b.c(1)); // TypeError: a.b.c is not a function
```

**Comment by jdalton** [comment]
Hi @n6g7! 

Dup of #1783.

**Comment by n6g7** [comment]
Hi @jdalton, that was a quick fix ! Thanks !
