### ISSUE TITLE
`_.merge`: unexpected behavior when merging nested functions and objects

### ISSUE THREAD

**Issue by timkendrick** [lodash/lodash#1794]
I recently upgraded to v4 of lodash.merge, and some of the behavior seems to have changed:

```javascript
var merge = require('lodash.merge');

var fn = function fn() {};
var obj = { obj: true };

var result = merge({}, { prop: fn }, { prop: obj });

console.log(result);
```

in v3, this outputs: `{ prop: { obj: true } }`
in v4, this outputs: `{ prop: { [Function: fn] obj: true } }` (i.e. the original `fn` function, which now has an added `obj` key)

To me, the v4 result is surprising: I would expect it just to replace `fn` with `obj` in the output, but instead it attempts to merge the function and the object together. It appears to do this by defining an extra property on the `fn` function itself, and returning the function. Is this the intended behavior?

**Comment by jdalton** [comment]
Lets tone down the dangerously and alarming jargon.

**Comment by timkendrick** [comment]
Sorry, got a bit carried away there (long debugging session) – will edit it :)

**Comment by jdalton** [comment]
Rock!

**Comment by jdalton** [comment]
The support was so that destination functions could get static methods assigned to them. It's covered as a todo in our roadmap. In v4 we clone sources to avoid one source tampering with another but you're right functions can't be helped there.

I could track source values and note to avoid assigning to a source.

**Comment by timkendrick** [comment]
Thanks for the super-fast response!

> I could track source values and note to avoid assigning to a source.

...am I correct in thinking that means you'd end up with the following?

```javascript
var merge = require('lodash.merge');

var fn = function fn() {};
var obj = { obj: true };

var copied = merge({}, { prop: fn }, { prop: obj });
console.log(copied);
 // => { prop: { obj: true } }

var merged = merge({ prop: fn }, { prop: obj });
console.log(merged);
 // => { prop: { [Function: fn] obj: true } }
console.log(typeof merged.prop);
 // => 'function'
console.log(merged.prop.obj);
 // => true
```
...that'd be perfect!

---

**BACKGROUND** (feel free to ignore): for my real-world use-case I've been using the HTMLBars library, which allows you to specify a set of custom 'keywords' to use as plugins for the rendering engine. Now a 'keyword' can *either* be a function, *or* a plain object containing a `setupState` method and `render` method. There's a default set of keywords to use as a starting point, but these can be individually overridden as need be. I was effectively doing the following to get the set of keywords (this is abridged of course):

```javascript
// library.js
var defaultHelpers = { ... };
var defaultKeywords = {
  'if': function() { ... },
  'each': function() { ... },
  'partial': function() { ... }
};

// file1.js
var customKeywords = {
  'partial': {
    setupState: function() {},
    render: function() {}
  },
  'debugger': function() {}
};

var myConfig = merge(
  {},
  { helpers: defaultHelpers, keywords: defaultKeywords },
  { keywords: customKeywords }
);
```

...my problem is that as it stands, the custom `partial` object is merged into the default `partial` function, which has far-reaching and unexpected consequences whenever the default one is later used elsewhere in the codebase. For now I've just split the merge into two steps (first keywords, then the rest of the config) – just thought some context might be useful to explain why I was surprised at the new behavior.

**Comment by Willever1984** [comment]
J

**Comment by jdalton** [comment]
Yep, I'll fix it.

**Comment by timkendrick** [comment]
amazing, thanks!

**Comment by timkendrick** [comment]
I'm blown away by how quickly you responded and implemented this – thanks for the fantastic work!
