### ISSUE TITLE
What's the meaning of Dropped boolean `options` param support in `_.debounce`, `_.mixin`, & `_.throttle` in changelog?

### ISSUE THREAD

**Issue by XGHeaven** [lodash/lodash#1795]
In changelog, 

> Dropped boolean `options` param support in `_.debounce`, `_.mixin`, & `_.throttle`

What's the meaning of this?

I search for api docs, and I find the `options` param still used in v3.10.1 and v4.0.0. 
No Dropped. No Different.

**Comment by jdalton** [comment]
It was a legacy option of v2 which we kept around in v3. You could pass just a boolean value `_.debounce(func, wait, true)` to specify executing on the leading edge of the timeout similar to `{ 'leading': true }`
