### ISSUE TITLE
_.toArray does not parse keycap emojis correctly

### ISSUE THREAD

**Issue by beaugunderson** [lodash/lodash#1796]
The #️⃣ emoji is composed of (like the other keycap emojis):

- a starting symbol, in this case `#`
- a `\uFE0F` variation selector
- a combining enclosing keycap `\u20E3`

`_.toArray` on a #️⃣ emoji returns an array of length two, with the first two items in index 0 and the combining enclosing keycap in index 1.

```js
var _ = require('lodash');

console.log(_.toArray('5️⃣'));
//= [ '5️', '⃣' ]
console.log(_.toArray('#️⃣'));
//= [ '#️', '⃣' ]
console.log(_.toArray('*⃣'));
//= [ '*', '⃣' ]
```

**Comment by jdalton** [comment]
Related to https://github.com/beaugunderson/emoji-aware.

**Comment by jdalton** [comment]
Hi @beaugunderson! I read your tweets. Can you create a PR of just unit tests for this. Tthey'll fail which is ok and I can use them while implementing the feature.

**Comment by jdalton** [comment]
Wow fast lol

**Comment by beaugunderson** [comment]
Beat you to it by about a second. :smile_cat:

**Comment by beaugunderson** [comment]
BTW I'm very excited to have this in lodash, awesome work! My test suite didn't find any other failures, so I think it's just the keycap emojis; will let you know if I find any other weirdness.

**Comment by jdalton** [comment]
> My test suite didn't find any other failures so I think it's just the keycap emojis; will let you know if I find any other weirdness.

Wow awesome, thank you!

Have you signed [our CLA](http://dojofoundation.org/about/cla)?

RE [this](https://twitter.com/beaugunderson/status/687715537447600128) That [reComplexWord](https://github.com/lodash/lodash/blob/4.0.0/lodash.js#L164-L221) regexp tho ;)

**Comment by beaugunderson** [comment]
Just signed the CLA. :)

Haha reComplexWord is awesome--I used parser combinators as an excuse to play with them but clearly the all-regex approach is much faster!

**Comment by jdalton** [comment]
In many methods I check with [reHasComplexSymbol](https://github.com/lodash/lodash/blob/4.0.0/lodash.js#L1170-L1179) before doing the heavy lifting.

**Comment by beaugunderson** [comment]
OK, the only other quirk I found is that two sequential `EMOJI MODIFIER FITZPATRICK` characters (like "🏿🏿") get grouped together with _.toArray, but I'm not sure if the behavior there is defined.

**Comment by jdalton** [comment]
I based our implementation off of http://unicode.org/reports/tr51/#Emoji_Sequences.

**Comment by jdalton** [comment]
I think they should be broken up (so a bug on our end).

**Comment by jdalton** [comment]
A failing test for that would be rad too :sunglasses:

**Comment by beaugunderson** [comment]
OK, test added for that too. :)

**Comment by jdalton** [comment]
Cool! Moving to #1796
