### ISSUE TITLE
_.sampleSize() limited to max length of sample and uses Fisher-Yates shuffle?

### ISSUE THREAD

**Issue by Anima-t3d** [lodash/lodash#1802]
It seems to me that using `_.sampleSize(collection, [n=0])` is limited to return at most the total number of the samples in the collection and they are non-repeating random (using [Fisher-Yates shuffle](https://en.wikipedia.org/wiki/Fisher-Yates_shuffle))? This is not clearly explained in the docs: https://lodash.com/docs#sampleSize

```javascript
var test = _.sampleSize([1,2,3], 5);
console.log('sampleSize()',test);
```
Returns `sampleSize() [3, 1, 2]`

I expected it to be more like a shorthand for:
```javascript
var arr = [];
var ii;
for (ii = 0; ii < 5; ++ii) {
	arr.push(_.sample([1,2,3]));
}
console.log('arr',arr)
```

**Comment by jdalton** [comment]
Good point @Anima-t3d. Patched.
