### ISSUE TITLE
Error : _.contains() is not a function in the latest version of lodash.

### ISSUE THREAD

**Issue by VaibhavP17** [lodash/lodash#1804]
In the latest version(4.0.0) of lodash, _.contais() method is not defined. It was available in version "3.10.0". Can you please help

**Comment by jdalton** [comment]
Hi @VaibhavP17! The `contains` alias is one of 17 others that was [removed in v4](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings).

You should use `_.includes` instead.

**Comment by jancervinka** [comment]
Shouldn't this be mentioned in the migration docs at https://github.com/lodash/lodash/wiki/Migrating ? Underscore has _.contains, _.unique and possibly other differences as well.

**Comment by jdalton** [comment]
Sure! @jancervinka would you mind adding it to the Migrating wiki?

**Comment by nkohari** [comment]
It would be really helpful to have a list of the replacement names for the removed aliases included in the migration guide. For example, `_.object()` used to be an alias of `_.zipObject()`, but now there's a new function called `_.zipObject()` whose behavior is slightly different, so instances of `_.object()` actually need to be replaced with `_.fromPairs()`.

**Comment by jancervinka** [comment]
I'd love to help but I have just started using lodash and have no idea what exactly has changed and where it became incompatible. I can add the two differences I have noticed but that doesn't really solve the problem.

**Comment by nkohari** [comment]
@jancervinka Same here -- I was going to document the changes I've found, but I think a list that isn't comprehensive might actually be worse than none at all. :)

**Comment by jdalton** [comment]
For a list of changes see [the changelog](https://github.com/lodash/lodash/issues/1804#issuecomment-176833758).

**Comment by nkohari** [comment]
@jdalton I've seen the changelog, which is great, but when it comes to the removed aliases in particular, it just says:

>
> Removed 17 aliases
> _.all, _.any, _.backflow, _.callback, _.collect, _.compose, _.contains, _.detect, _.foldl, _.foldr, _.include, > _.inject, _.methods, _.object, _#run, _.select, & _.unique

It would be really helpful if this was a table indicating the new/correct name of the removed functions. That'd make it a really simple find and replace, whereas right now it takes a lot of digging into the old documentation.

**Comment by jdalton** [comment]
Since they're aliases the correct names tend to be the things they were aliasing. The old documentation lists aliases to or you can pull up lodash v3.10.1 and look at the method assignments at the bottom. It's all there.

**Comment by nkohari** [comment]
What about the example I gave, `_.object()`?

This function used to alias `_.zipObject()`:
https://github.com/lodash/lodash/blob/3.10.1/doc/README.md#_zipobjectprops-values

But now `_.zipObject()` has a different behavior, and the actual function I'm looking for is `_.fromPairs()`.

I don't mean to be difficult here -- in the end migrating is just a simple find-and-replace, which is great, and the changelog is very comprehensive. It doesn't seem that difficult to add the correct functions to the changelog for clarity. I'd be happy to put the list together myself if you'd be willing to double-check it.

**Comment by jdalton** [comment]
>  It doesn't seem that difficult to add the correct functions to the changelog for clarity. 

Look at [my github activity](https://github.com/jdalton) then tell me it's not difficult. I'm pretty busy so if you'd like extra documentation the wiki is, and has been, open to external contributions without explicit approval needed.

**Comment by nkohari** [comment]
Yikes. No need for hostility. I appreciate your work and I'm just trying to help. Other people will undoubtedly run into this problem and come take up more of your time with the same questions. :) I'll update the wiki with the alias replacements.

**Comment by jdalton** [comment]
Maybe I have a case of the Mondays.
