### ISSUE TITLE
lodash/fp _.has is not curried and takes arguments in wrong order

### ISSUE THREAD

**Issue by N0ps32** [lodash/lodash#1805]
When importing lodash/fp  _.has is not curried and takes the object as the first and the property as the last argument.

I am using lodash 4.0.0.

**Comment by N0ps32** [comment]
Anybody else that has this problem you can use this fix:
```
const has = _.curry((prop, obj) => {
     return _.flowRight(
        _.negate(_.isUndefined),
        _.prop(prop)
     )(obj);
 });
```

**Comment by jdalton** [comment]
Thanks @N0ps32! I've updated the fp map to include it. Please let me know if you find any other glitches. I'm hoping to have these smoothed out for the v4.0.1 release.
