### ISSUE TITLE
Merge vs Extend object reference

### ISSUE THREAD

**Issue by jaxesn** [lodash/lodash#181]
This might be by design.  Basically, when using merge, if the source object has a child object which does not exist in the destination object, the child object is recreated.  If you use extend, the child object is not recreated,

``` javascript
var foo = {x:1},
    merged = _.merge({}, {foo:foo}),
    extended = _.extend({}, {foo: foo});

console.log(merged.foo === foo); // false 
console.log(extended.foo === foo); // true
```

Wanted to point it out, in case it was not intentional.

**Comment by dwelle** [comment]
I'd like to get back to this - why should the source's props be merged _recursively_ even when target prop _doesn't_ exist in target object? Apart from wasting time, you have to do some nasty reference juggling if you somewhere keep references to the source array/ object assigned to the to-be-merged-in property.

Why not simply check if prop exists in target object, and if not, simply copy the value/ ref, there?

**Comment by jdalton** [comment]
> Why not simply check if prop exists in target object, and if not, copy the value/ ref, there?

Consistency.

**Comment by dwelle** [comment]
Fair enough.

Out of interest, though, is it because of consistency with other libs, or consistency within lodash itself? Because to me it seems it is inconsistent (e.g. with `_.extend`, as stated above).

Anyway, for anyone wanting the discussed behavior, I've made this mixin:

```
_.mixin({
  mergeStable: _.partialRight( _.merge, function customizer ( target, source ) {
    return ( !target || !_.isPlainObject(target) || !_.isPlainObject(source) )
      ? source
      : _.merge( target, source, customizer );
  })
});
```

**Comment by StreetStrider** [comment]
@dwelle, firstly it is a consistensy with the `merge` itself. Unexplicit different ref saving behavior depending on what data is — this is certainly not what one want. One time you'll end up with wrapping this stuff in `_.clone` :)

**Comment by jdalton** [comment]
>  firstly it is a consistency with the `merge` itself. Unexplicit different ref saving behavior depending on what data is — this is certainly not what one would want.

Yap, this.

**Comment by dwelle** [comment]
K, thanks for expl.
