### ISSUE TITLE
isEqual broken in 4.0.0 - ordering of object properties matters

### ISSUE THREAD

**Issue by brimsey** [lodash/lodash#1810]
Using lodash 3.10.1
var obj1 = {'a':'a', 'b':'b'}
var obj2 = {'a':'a', 'b':'b'}
var l = require('lodash')
l.isEqual(obj1,obj2)
true
var obj3 = {'b':'b', 'a':'a'}
l.isEqual(obj1,obj3)
true

Using lodash 4.0.0
var obj1 = {'a':'a', 'b':'b'}
var obj2 = {'a':'a', 'b':'b'}
var l = require('lodash')
l.isEqual(obj1,obj2)
true
var obj3 = {'b':'b', 'a':'a'}
l.isEqual(obj1,obj3)
false

Example:
> var obj1 = {'a':'a', 'b':'b'}
undefined
> var obj2 = {'a':'a', 'b':'b'}
undefined
> var l_3 = require('lodash_3_10_1')
undefined
> var l_4 = require('lodash')
undefined
> var obj3 = {'b':'b', 'a':'a'}
undefined
> l_3.isEqual(obj1, obj2)
true
> l_3.isEqual(obj1, obj3)
true
> l_4.isEqual(obj1, obj2)
true
> l_4.isEqual(obj1, obj3)
false

**Comment by jdalton** [comment]
Thanks for reporting @brimsey! This is a dup of #1758 which has been patched in our edge master branch.
