### ISSUE TITLE
minBy, maxBy with object

### ISSUE THREAD

**Issue by klimashkin** [lodash/lodash#1812]
Hi John!
In our project we have a lot of places, where we search min/max object by some property.
And such objects are in other object, not in array.

In lodash 3.x it was ok to use _.max with objects, in 4.x with _.maxBy/minBy we cant.
We need everywhere transform object to array(with checking if it not array)

Would be great if such check exists within maxBy/minBy!

**Comment by jdalton** [comment]
It was unfortunate that support existed in v3. It complicated the methods and began to spread to other math/number methods. Instead you can use `_.maxBy(_.values(object), 'a')`.

**Comment by abhelaksh** [comment]
These kinds of changes will require huge code refactoring and prevent folks from upgrading.

**Comment by jdalton** [comment]
Upgrades to v4 are doing p well. It's usage is growing at a faster rate than v3.
