### ISSUE TITLE
Disable deep paths

### ISSUE THREAD

**Issue by taylor1791** [lodash/lodash#1813]
When upgrading to lodash v4.0.0 I discovered that it "Added support for deep paths to _.zipObject". Is there a way to disable deep paths for functions?

One use case is when you have a list of email and users and you want to create a map of them.

```
_.zipObject(['john@example.com'], ['john doe']) // => {"john@example": {"com": "john doe"}}
```

I know that I can use other methods like reduce, but it seams like there should be a way to disable path behavior when working in such cases.

**Comment by jdalton** [comment]
In the master edge branch I've simplified `_.fromPairs` (no deep path support) so you can go that route in v4.0.1.

**Comment by dohse** [comment]
`_.fromPairs()` is not equivalent to `_.zipObject()`. The former takes an array of tuples while the later takes two arrays.

I am looking for a drop-in replacement for `_.object(keys, values)`. I will probably have to resort to `_.fromPairs(_.zip(keys, values))`. Unfortunately that one is longer and less efficient, while `_.zipObject()` is useless for us.

**Comment by dohse** [comment]
The special treatment of property names should be mentioned in the documentation.
