### ISSUE TITLE
throttled.flush() not working

### ISSUE THREAD

**Issue by prontiol** [lodash/lodash#1816]
I am expecting this to work:
```
> var throttled = _.throttle(console.log.bind(console, 'throttle'), 1000);
> throttled.flush();
undefined
```
But it does not.
Neither this one:
```
> var throttled = _.throttle(console.log.bind(console, 'throttle'), 1000);
> throttled();
throttle
> throttled.flush();
undefined
```
`throttled.flush()` never invokes throttled function, no matter when it is called.
Is this expected behaviour?

**Comment by jdalton** [comment]
The docs say a trailing call will only happen if invoked more than once
