### ISSUE TITLE
keys/keysIn may fail on prototypes with computed 'length' property

### ISSUE THREAD

**Issue by bluekeyes** [lodash/lodash#1818]
```js
function Path() {
  this.points = [];
}

Object.defineProperty(Path.prototype, 'length', {
  get: function () {
    return this.points.length;
  }
});

_.keys(Path.prototype);
// => TypeError: Cannot read property 'length' of undefined
//      Object.defineProperty.get @ zahipiwaqe.js:7
//      indexKeys @ lodash.js:4912
//      keys @ lodash.js:10994
```
http://jsbin.com/zahipiwaqe/edit?js,console

`Object.keys` returns `[]`, as expected. This also breaks `assign`, `assignIn`, and any other functions that use `keys` or `keysIn` internally. Since these are all "object" functions, I was surprised that `length` is used.

For background, I found this while trying to convert [jonobr1/two.js](https://github.com/jonobr1/two.js) from Underscore to Lodash - it uses `_.extend` with prototypes to inherit methods and the root prototype has a computed `length` property.

**Comment by jdalton** [comment]
Length checks are required for consistent treatment of arrays, arguments objects, and string. Lodash has lots of length checks that cannot be avoided. I thinks its reasonable to fix the bug in the computed property instead.
