### ISSUE TITLE
`fp.unionWith` is not be curried

### ISSUE THREAD

**Issue by morlay** [lodash/lodash#1820]
`fp.unionWith` is not be curried, 
`fp.unionWith(fp.isEqual)` will not return a function.
`fp.unionWith(fp.isEqual, objects)` will return the objects.

but the result is not same as original method with all arguments.  

```js 
const objects = [
    { x: 1, y: 2 },
    { x: 2, y: 1 }
];
const others = [
    { x: 1, y: 1 },
    { x: 1, y: 2 }
];
_.unionBy(objects, others, _.isEqual); // [ { x: 1, y: 2 } ]
fp.unionBy(fp.isEqual, others)(objects); // [ { x: 1, y: 2 } ]

_.unionWith(objects, others, _.isEqual); // [ { x: 1, y: 2 }, { x: 2, y: 1 }, { x: 1, y: 1 } ]
fp.unionWith(fp.isEqual, others, objects); // [ { x: 1, y: 1 }, { x: 1, y: 2 }, { x: 1, y: 2 }, { x: 2, y: 1 } ]
```

`fp.unionBy` is correct, strange ...
they are in the same fp map.

**Comment by jdalton** [comment]
This is patched in the edge master branch. It was missing the the v4 release.

**Comment by jdalton** [comment]
See #1800
