### ISSUE TITLE
possibility to add update method

### ISSUE THREAD

**Issue by hzamani** [lodash/lodash#1823]
What about having an `update` method as in [clojure](https://clojuredocs.org/clojure.core/update)? Specially useful in functional programming. Something like this:  
```js
function update(object, path, func, ...args) {
  set(object, path, func(get(object, path), ...args);
  return object;
}
```

**Comment by jdalton** [comment]
I think that's a pretty neat idea. Let's wait a bit to see if others dig it.

In the meantime can you post a usage example?

**Comment by hzamani** [comment]
For example in a todomvc app with lodash/fp one would have:
```js
var state = {todos: {}, uid: 1}

function logicalNot(x) { return !x; }
function inc(n) { return n+1; }

function addTodo(text) {
  var id = state.uid;
  _.update(state, 'uid', inc);
  _.update(state, 'todos', _.set(id, {text: text, id: id, completed: false}));
}

function toggleTodo(id) {
  _.update(state, ['todos', id, 'completed'], logicalNot);
}

function toggleAllTodos(checked) {
  _.update(state, 'todos', _.mapValues(_.set(checked, 'completed')));
}

function destroyTodo(id) {
  // Also currently unset is not added to lodash/fp :-\
  _.update(state, 'todos', _.unset(id));
}

function clearCompleted() {
   // omitBy wrongly places in aryMethodMap 3 :-|
  _.update(state, 'todos', _.omitBy(_.get('completed')));
}
```

**Comment by hzamani** [comment]
Is it necessary to open separate issues for mentioned bugs on fp?

**Comment by StreetStrider** [comment]
Ramda has [`over`](http://ramdajs.com/docs/#over) which works in complex with various [Lenses](http://ramdajs.com/docs/#lens).

**Comment by jdalton** [comment]
> Is it necessary to open separate issues for mentioned bugs on fp?

Yep. Though check to see if [it's been corrected](https://github.com/lodash/lodash/blob/master/fp/_mapping.js) in the edge master branch.

**Comment by hzamani** [comment]
In the [edge master branch](https://github.com/lodash/lodash/blob/master/fp/_mapping.js) unset is in `aryMethod[1]` witch is wrong, it must be in 2

**Comment by jdalton** [comment]
Thanks pached https://github.com/lodash/lodash/commit/5f78d3ae26ff27407b21ac0cd0498981cc1e50a3.

**Comment by jfmengels** [comment]
I was about to make a similar proposal. I have just started to use lodash/fp and writing in a FP style, and use this function pretty abundantly.

```js
const applyTo = _.curry((selector, fn, obj) => { // update might be a better name for it
  const value = fn(_.get(selector, obj))
  return _.set(value, selector, obj)
})
```

It is really useful when updating deeply nested values
```js
const state = {
  players: [
    {points: 12, resources: 40},
    {points: 23, resources: 26}
  ],
  foo: 'bar'
}

const exchangePointsForResources = (playerIndex, amount) => _.flow(
  applyTo(`players[${playerIndex}].points`, (n) => n + points),
  applyTo(`players[${playerIndex}].resources`, (n) => n - points)
)

// Which would, without applyTo/update probably look like something like this
// which gets worse with every nesting level

const exchangePointsForResourcesWithoutApplyTo = (playerIndex, points) => (state) => {
  const players = _.map((player) => {
    if (player !== players[playerIndex]) return player
    return _.assign({
      points: player.points + points,
      resources: player.resources - points
    }, player)
  }, state.players)

  return _.assign({players}, state)
}
```

**Comment by hzamani** [comment]
```js
applyTo(`players[${playerIndex}].points`, (n) => n + points)
```
is same as
```js
applyTo(['players', playerIndexp, 'points'], (n) => n + points)
```
which is more readable.

And yes. `update` may make code more readable and also shorter.

**Comment by jfmengels** [comment]
That is indeed better, I forgot about that syntax. Thanks :)
@jdalton If you don't mind me asking, how do you figure out whether this is interesting for other people? Do you wait for others to make the same proposal or to find this closed issue?

**Comment by jdalton** [comment]
> Do you wait for others to make the same proposal or to find this closed issue

Both :)

**Comment by dashed** [comment]
I have some interest in this as I was fond of this style when using Immutable.js API, and wished for something akin to `updateIn` for plain JS objects. 

Nearly every Immutable.js collection type makes use of the following common API scheme, each of which have a corresponding lodash method (except for `updateIn`) for JS objects:

* `hasIn => _.has` 
* `getIn => _.get`
* `setIn => _.set`
* `deleteIn => _.unset`
* `updateIn => _.update` (missing from lodash API)

e.g. http://facebook.github.io/immutable-js/docs/#/Map

**Comment by billyjanitsch** [comment]
I'm also interested in `update`. It would very useful for tersely iterating over fields:

```js
import {map, update, set, get} from 'lodash/fp'

const data = [
  {myDeeply: {nestedProp: 1}},
  {myDeeply: {nestedProp: 4}},
]

const nestedPath = ['myDeeply', 'nestedProp']
const increment = x => x + 1

// with update:
map(update(nestedPath, increment), data)

// without (reimplementing) update:
map(obj => set(nestedPath, increment(get(nestedPath, obj)), obj), data)
```

**Comment by arathunku** [comment]
Well, another person here that wishes for Clojure functions in JavaScript without using CLJS. I'm using normalizr with redux and my state is quite "nested" so updateIn would make updates much more readable. For instance, my props(in React) look like this (simplified):
```
const id = 1;
const props = { state: { entities: { foos: { [id]: { bars: [1,2,3] } } } } 
```

and if I wanted to remove or add a value to "bars" without mutating the props, you can imagine it'll be quite ugly :cry:

**Comment by epeli** [comment]
I'd like to see this too. Currently I'm using [updeep](https://github.com/substantial/updeep) in addition to lodash.

I'm using only two functions from it

  - `update` https://github.com/substantial/updeep#uupdates-object
  - `updateIn` https://github.com/substantial/updeep#uupdateinpath-value-object

I find those very invaluable when working with [Redux](http://redux.js.org) using vanilla JS data structures.

**Comment by aaronjensen** [comment]
As the author of [updeep](https://github.com/substantial/updeep) I'd be quite happy to see the two functions epeli mentions be absorbed into lodash. That'd be great.

**Comment by epeli** [comment]
Another argument for `updateIn`* is that it is a general version of `set`. Set can be implemented easily in terms of `updateIn`:

```js
const set = (path, value, target) => updateIn(path, () => value, target);
```

I think it's weird to have only one special case of `updateIn` in Lodash :)

\* I think `updatePath` would be a better name as it would align with the `assocPath` alias.

**Comment by slorber** [comment]
also interested by this feature

this is a missing one that most FP React users would probably want if they already use lodash

**Comment by jdalton** [comment]
Let's add this. Anyone want to take the PR?

**Comment by jfmengels** [comment]
There was already a PR made here https://github.com/lodash/lodash/pull/1832 by @hzamani. If it looks ok, we might take that, otherwise check if he is still willing to take the time to update it.

**Comment by aaronjensen** [comment]
@jdalton how much do you want to add? Do you want to add just the simple update path with function like #1832 or the "specification style" update like updeep: https://github.com/substantial/updeep#full-example

**Comment by jdalton** [comment]
Lets do simple first. We added [_.conforms](https://lodash.com/docs#conforms) a bit later I can see a spec style added as an enhancement down the road.

**Comment by slorber** [comment]
@jdalton thanks !

What should be the final spec for this feature exactly? 


# Immutable or Side-effect?

I've seen @dashed mention `_.set` and other lodash methods but for me it is not equivalent of ImmutableJS `setIn` at all from an immutable data point of view.

From doc of `_.set`: 
> Note: This method mutates object.


So @jdalton there may be 2 different needs for this feature: the ones that want to update in place data of data, and the ones that want to return new objects. and leave the original object parameter untouched. 


If an implementation has to be done on top of `_.set`, ie

```javascript
function update(object, path, func, ...args) {
  set(object, path, func(get(object, path), ...args);
  return object;
}
```

it would not satisfy immutability as the object parameter is mutated. It is not a side-effect free function as we are returning the initial object.

If an implementation is done on top of _.set, it will be just a syntactic sugar but will not solve the immutable data problem that most React/VDom lib users need right now.

**Comment by jdalton** [comment]
We handle mutation via a separation of styles.
lodash has mutation methods while our `lodash/fp` side doesn't mutate.

**Comment by jfmengels** [comment]
I would argue to make it a side-effect function to make it kind of like `set`, but I'm biased as I will probably only ever use the fp version of it (but at least this allows to have both versions).

Related question though: what will the cap for this function in fp be? I'd guess (and vote for 3), which would remove the use of `...args`, but which is okay as there is `curry` and `partial` and arrow functions to make that not that much of a problem.

I notice that having `...args` as last values will be odd though in fp, as the value will be the `data`, and data is usually last in fp. Maybe call fn with `fn(...args, get(path))` rather than `fn(get(path), ...args)`?

**Comment by jdalton** [comment]
The `args` bit will likely be cut from the PR.

**Comment by jfmengels** [comment]
:+1:

**Comment by epeli** [comment]
I see that this is in the new [release](https://github.com/lodash/lodash/wiki/Changelog#v460). Thanks!

**Comment by dashed** [comment]
Ah slick! :tada: 

Thanks for adding _.update :+1:

**Comment by epeli** [comment]
How about the object version? :)

As heavy updeep user I've found that the object version is much more readable for complex updates:

```js
const fixImageUrls = update(["media_details", "sizes"], map(update("source_url", url => {
    if (url.startsWith("http")) return url;
    return API_END_POINT + url;  
})));
```

vs

```js
const fixImageUrls = updateObject({
    "media_details": {
        "sizes": map(updateObject({
            "source_url": url => {
                if (url.startsWith("http")) return url;
                return API_END_POINT + url;
            },
        })),
    },
});
```


The path updating is a bit more terse but I think the object based update more clear as it communicates the target object shape more clearly to the reader.

**Comment by epeli** [comment]
Could we overload the current `update` function with a type check and do the object update if the `path` is an object?

**Comment by jdalton** [comment]
> Could we overload the current `update` function with a type check and do the object update if the `path` is an object?

I think it'd be more approp as a new method.
