### ISSUE TITLE
lodash-fp 4.0 on browser

### ISSUE THREAD

**Issue by vshesh** [lodash/lodash#1825]
Question - 

is there a way to link to lodash-fp directly in a browser (i.e, from CDN?) cdnjs only has lodash proper.

**Comment by jdalton** [comment]
Hi @vshesh! Check out https://github.com/lodash/lodash/tree/4.0.0/dist.

**Comment by vshesh** [comment]
Just to be clear, I have to add *both* lodash and lodash-fp? (lodash-fp by itself doesn't seem to work)
And I don't need the mapping file?

**Comment by jdalton** [comment]
Now you just need to pass `_` to `fp`:
```js
var f = fp(_);
```

**Comment by jdalton** [comment]
This allows it to work with lodash full, core, or custom builds.

**Comment by vshesh** [comment]
aaaaah very interesting!
thank you for the answer :)

**Comment by prashantpawar** [comment]
According to the [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide) just loading the fp js file makes _ become functional. I just tried this myself and @jdalton's solution works for me, so does this mean that FP-Guide needs to be corrected?

**Comment by pavel** [comment]
@jdalton It does seem like `lodash.fp.min.js` is not included in `npm` build though.

**Comment by pavel** [comment]
@jdalton It does seem like `lodash.fp.min.js` and `lodash.fp.js` are missing in `npm` build.

**Comment by jdalton** [comment]
@pavel that's intended, use the cdn.

**Comment by pavel** [comment]
@jdalton But I can not, due to the application is "enterprise" and by internal policies the server, application is running have no access to the internet.

**Comment by jdalton** [comment]
You can always download the script.

**Comment by pavel** [comment]
@jdalton This also means that I need to step from `npm` based managed libraries and add `lodash` as an exception and do "my own version management for lodash".

**Comment by pavel** [comment]
Don't get me wrong though, I'm not trying to say you're wrong at what you do. Just looking for suggestion/advice.

**Comment by jdalton** [comment]
For advice hit up the [gitter chat](https://gitter.im/lodash/lodash).
