### ISSUE TITLE
lodash v4 core: npm availability

### ISSUE THREAD

**Issue by wbinnssmith** [lodash/lodash#1826]
Hi John-David,

Thanks for lodash. You're incredible.

Is the new v4 core build available with `npm install`? The index export is the complete build, and functions are available alongside it, but I can't seem to find the core build in the distribution.

Maybe it could be `var _ = require('lodash/core')` or something along those lines. What do you think?

Thanks again.
Will

**Comment by jdalton** [comment]
You're right it isn't in the npm build but it could be and I think `core` is a fine name for it. So in the next release we'll do that.

**Comment by wbinnssmith** [comment]
Thanks so much!

On Sun, Jan 17, 2016 at 7:50 PM, John-David Dalton <notifications@github.com

**Comment by jcrben** [comment]
Is core actually on npm? I can't find it.

**Comment by jdalton** [comment]
`lodash/core`.
