### ISSUE TITLE
_.words behaves differently between V4 and V3.10.1 wrt lowercased strings

### ISSUE THREAD

**Issue by ycheapopo** [lodash/lodash#1827]
The following code snippets returns different values between lodash V4.0.0 and V3.10.1 :
```js
  var _ = require('lodash')
   var name = '2QN';
   console.log(_.words(name));
   nameLowerCase = name.toLowerCase();
   console.log(_.words(nameLowerCase));   // different values
```
output V3.10.1:
```js
[ '2', 'QN' ]
[ '2', 'qn' ] // (notice the 2 and qn are separated)
```
output v4:
```js
[ '2', 'QN' ]
[ '2qn' ] // (notice the 2 and the qn are not separated!)
```

**Comment by jdalton** [comment]
This is by design to work with things like units (`px`, `in`, `em`). Though I could see it both ways. With capitals its usually separate words butting up against another.

Can you explain more about the use case where you were expecting it to work. What is 'qn'?

**Comment by ycheapopo** [comment]
Please re-consider your solution: (for general public, I myself have a workaround) : 
with v4 implementation there is no symmetry between words with upper case vs lower case words and this surprises API users (especially, as the name 'words' doesn't imply this split, and that in documentation no such idiosyncratic is mentioned).
IMHO, adding an option (e.g. 'splitOnMeasurmentsUnits:true') would more honestly reflect what this API is doing without breaking symmetry
