### ISSUE TITLE
Lodash Core build and Missing assign-function with template precompilation

### ISSUE THREAD

**Issue by bungle** [lodash/lodash#1828]
When I precompile templates with `lodash-cli` `4.0.0` and use Lodash 4.0.0 Core build, I do get error:

```
Uncaught TypeError: _.assign is not a function
```

If I use previous `lodash-cli` `3.10.1` the templates work even with Lodash 4.0.0 Core.

It seems that `lodash-cli` `4.0.0` generates at the end of the template this:

```javascript
_.templates=_.assign(_.templates||{},templates)
```

While `3.10.1` generates something like this:

```javascript
_.templates=_.extend(_.templates||{},templates)
```

So either the `assign` (there seems to be `assignIn`) is missing from the Core build or the precompilation doesn't generate right output.

**Comment by jdalton** [comment]
I've moved this to https://github.com/lodash/lodash-cli/issues/79.

**Comment by bungle** [comment]
Thanks, I was thinking about posting it there first, but I didn'r knew exactly where the problem was. Thanks for moving and fixing this.
