### ISSUE TITLE
_.forEach binding (thisArg) doesn't work on 4.*

### ISSUE THREAD

**Issue by swfall** [lodash/lodash#1829]
```
var _ = require('lodash');

var A = function() {
    this.foo = 42;
    _.forEach([1,2,3,4], function() { 
        console.log(this);
    }, this);
}

var a  = new A();
````

output 4.0.0:
... 4 global objects (`this` of the global scope)

output 3.10.1, as expected:
```
{ foo: 42 }
{ foo: 42 }
{ foo: 42 }
{ foo: 42 }
```

tested with node 0.10.36

**Comment by d10** [comment]
`thisArg` arguments for Lodash methods are no longer supported (see the [v4 changelog](https://github.com/lodash/lodash/wiki/Changelog#400). You can use `_.bind` instead.

**Comment by jdalton** [comment]
Yep, `_.bind`, `Function#bind`, or arrow functions will do.
