### ISSUE TITLE
map() over output of countBy() when using lodash/fp

### ISSUE THREAD

**Issue by nfcampos** [lodash/lodash#1831]
```js
import _ from 'lodash'
let arr = [1, 2, 2, 3]

_(arr)
  .countBy()
  .map((count, value) => ({value, count}))
  .map(...)
```
Is it possible to do something similar with `lodash/fp`, ie. to use the output of countBy further down in the chain, and be able to access both the value and the respective count?

**Comment by jdalton** [comment]
the `fp` wrapper doesn't support chaining. Chaining in `fp` is just like chaining in primary `lodash`.

**Comment by nfcampos** [comment]
What do you mean doesn't support? It appears to work... The only difference appears to be that the iteratee (in eg. map() ) is invoked with just 1 arg, which in this case makes it much less useful, so certainly not `just like chaining in lodash`

**Comment by jdalton** [comment]
Beyond capped iteratee calls chaining is very much like `lodash` as methods aren't auto-curried, aren't iteratee-first data-last, and aren't immutable.

**Comment by nfcampos** [comment]
So should methods even be capped? The reason for capping (no surprises with currying) (sort of) doesn't apply since they're methods.

And not all methods are immutable, right?
```
var chain = _([1,2,3]).map(a => a*2)
chain.map(a => a/2)
console.log(chain) //[2,4,6]
```
I know that native map returns a new array and doesn't change the original one,  but when chaining it's kind of surprising that some methods mutate the chain while others return a new chain.

**Comment by jdalton** [comment]
> So should methods even be capped? 

It's a side effect of customizing the `_.iteratee` method. It's fixable so I should probably fix it ;)

> but when chaining it's kind of surprising that some methods mutate the chain while others return a new chain

Each chained method invocation creates a new chained wrapper which can be stored. As you add method calls you're adding to the chained sequence (one references the other which references another) in a chain. The fp-methods themselves should not mutate passed params.

**Comment by nfcampos** [comment]
> Each chained method invocation creates a new chained wrapper which can be stored.

I didn't realise that. I thought methods like .push() would not behave like that, but that does make more sense.
