### ISSUE TITLE
Note: Breaking Change in behaviour of filter between v3 and v4

### ISSUE THREAD

**Issue by cefn** [lodash/lodash#1836]
Here's two node REPLs showing the behaviour of filter in version 3 and version 4 (in particular, I was previously using 3.10.1 and upgraded to 4.0.0 and the change broke my code which relied on this signature. 

* Version 3

'''
> lodash.filter([{hello:"world"}], "hello", "world")
[ { hello: 'world' } ]
> lodash.filter([{hello:"world"}], "hello", "mars")
[]
'''

* Version 4

```
> lodash.filter([{hello:"world"}], "hello", "world")
[ { hello: 'world' } ]
> lodash.filter([{hello:"world"}], "hello", "mars")
[ { hello: 'world' } ]
```

I cannot see where this change in behaviour is documented in the changelog. There's a comment about _.where being deprecated in favour of _.filter, but there doesn't seem to be a statement about the behaviour of _.filter itself changing.

The new syntax equivalent of the three-arg signature seems to be this two-arg signature instead...

```
lodash.filter([{hello:"world"}], {hello:"world"})
```

This is just an issue so that people can confirm the change if they encounter it independently. Close if this is an intended breaking change.

**Comment by jdalton** [comment]
It' documented under the [compatibility warnings](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings) as
> Changed `matchesProperty` shorthand from separate params to an array of `[path, srcValue]`
