### ISSUE TITLE
_.words v4 doesn't return capitalized words surrounded by numbers (changing behaviour to v3.10.1)

### ISSUE THREAD

**Issue by ycheapopo** [lodash/lodash#1837]
Following code: 
var _ = require ('lodash');
name = '1PERSON1VOTE';
console.log(_.words(name));

Returns different results between words version 3 and 4
v3: [ '1', 'PERSON', '1', 'VOTE' ] // seems legit
v4: [ '1', '1', 'VOTE' ] // Where did the person go?

Also, if name were 1person1vote
the result would be 1person 1vote which is also a non consistent API

I understand that these quirks? might be part of change in requirements in words implementation, 
but I would really like a backward 'normal' option to be still alive.

**Comment by d10** [comment]
Seems related to #1833.

**Comment by jdalton** [comment]
Yep, fixed by #1833.
