### ISSUE TITLE
_.indexBy not in main docs

### ISSUE THREAD

**Issue by DarkMarmot** [lodash/lodash#1840]
Wasn't sure if _.indexBy was replaced or deprecated -- but I was looking for this method and noticed it is still in the DevDocs but not appearing at the main site: https://lodash.com/docs#indexBy

**Comment by jdalton** [comment]
indexBy was renamed to keyBy

**Comment by DarkMarmot** [comment]
awesome sorry and thanks for the info!

**Comment by jaepage** [comment]
This threw me too. Could the docs include "formerly known as" notes, or would they get unwieldy? Thank you.

**Comment by jdalton** [comment]
Np. To the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v400)!
