### ISSUE TITLE
Update to 4.0 on the docs page.

### ISSUE THREAD

**Issue by adamboduch** [lodash/lodash#1843]
I've come to rely on lodash being embedded in the [docs](https://lodash.com/docs), it's just an awesome way to play with stuff. Please update this from _3.10.1_ to _4.0_.

Thanks!

**Comment by d10** [comment]
The docs page currently has the latest 4.0.0 docs. Perhaps you’re encountering a cache issue?

**Comment by adamboduch** [comment]
I meant lodash itself that's included on the page so that readers can play
with it in the console while reading docs.

**Comment by jdalton** [comment]
The [lodash included in the site](https://lodash.com/_js/lodash.js) is lodash v4.
Make sure to clear your cache. I guess I could cache bust too.
