### ISSUE TITLE
_.typeOf

### ISSUE THREAD

**Issue by fyyyyy** [lodash/lodash#1845]
Sometimes useful for these kind of checks.
Would also properly identify Arrays and Objects, contrary to (val) => { return typeof val }

```javascript
_.map([value1, value2, value3], _.typeOf)
// => [Object, String, Array]

**Comment by jdalton** [comment]
Thanks for the request @fyyyyy! I've avoided something like this in the past because it makes modularizing more difficult but if there's demand from users I'll reconsider.

**Comment by kownacki** [comment]
I like this idea. But I would rather see it to only work with objects, and it should return class of object. Just like in your example. But for primitive string I wouln't return `"String"` as it implies class name by using capital. Instead for primitives it should return `undefined` or even throw error depending on what is usually done in situations like that in lodash

**Comment by kownacki** [comment]
I published my own module which has functionality I described in #2454 https://www.npmjs.com/package/true-typeof I think it better suits `_.typeof`
But I would prefer to have it in lodash, of course if others like it.

**Comment by beausmith** [comment]
Until this feature is added, here's a function to get the type of anything passed to it:

```js
var toType = function(obj) {
  return ({}).toString.call(obj).match(/\s([a-zA-Z]+)/)[1].toLowerCase()
}
```

Sources:
- [Better way to get type of a Javascript variable?](https://stackoverflow.com/questions/7390426/better-way-to-get-type-of-a-javascript-variable)
- [Fixing the JavaScript typeof operator](https://javascriptweblog.wordpress.com/2011/08/08/fixing-the-javascript-typeof-operator/)

**Comment by thangbn** [comment]
+1

**Comment by Kreijstal** [comment]
I liked this version 
https://stackoverflow.com/a/41457071
