### ISSUE TITLE
`pad*()` will fail to padding if the string tailing with `\0`

### ISSUE THREAD

**Issue by twang2218** [lodash/lodash#1847]
```javascript
const _ = require('lodash');

const buf = new Buffer([49, 50, 51, 52, 0, 0, 0, 0]);
const str = buf.toString('utf8');

console.log('[' + str + ']');
console.log('[' + _.padEnd(str, 7) + ']');
```

Like the above code, the string is converted from buffer with `\0` padding on the end, and the output is:

```javascript
[1234]
[1234]
```

It failed to padding as the converted string contains `\u0000` as part of the string, although it's not visible. The correct result should be:

```javascript
[1234]
[1234   ]
```

The problem was raised in Node.js project nodejs/node#4775, however, they thought `\u0000` should be part of the string. In that case, I think the lodash might need to handle those invisible characters in Unicode, including `\u0000`, so the padding can be corrected.

**Comment by jdalton** [comment]
As https://github.com/nodejs/node/issues/4775 noted there are lots of invisible characters and the current behavior is correct.

**Comment by twang2218** [comment]
Yes, there are a lot of invisible characters, but why lodash.pad*() count those characters when do the padding? Doesn't make any sense.

**Comment by jdalton** [comment]
There's lots of invisible non-whitespace characters that won't get caught by built-in `String#trim` either. It's the nature of the beast. If you don't want those characters you can create a mixin to `trimUnprintables` or something.
