### ISSUE TITLE
lodash/fp 4.0.0 _.flip in combination with _.merge weird behaviour

### ISSUE THREAD

**Issue by N0ps32** [lodash/lodash#1850]
I needed a flipped version of _.merge in lodash/fp so I flipped the function:
```javascript
_.flip(_.merge)({checked:false}, {checked:true})
```
this returns the expected result {checked: true}.
However when I take advantage of currying then I get a different result:
```javascript
_.flip(_.merge)({checked:false})({checked:true})
```
{checked: false}.

Is this intentional behavior?

**Comment by jdalton** [comment]
Dup of #1754

**Comment by N0ps32** [comment]
Is this really a duplicate?
I am not saying that the order of merge is wrong but combining merge with flip leads to weird results.
Wouldn't this also occur if the arguments of merge were reversed and I would call this?

**Comment by jdalton** [comment]
The `_.merge` argument order is incorrect in v4.0.0.
