### ISSUE TITLE
lodash 4 overwrites global `_` variable even when browserified

### ISSUE THREAD

**Issue by AgentME** [lodash/lodash#1852]
Lodash v4 overwrites the global `_` variable even when browserified.

This caused issues for me because I have an application which depends on the global `_` being Lodash v3, and one of my browserified dependencies updated to depend on Lodash v4 recently.

**Comment by AgentME** [comment]
I see from https://github.com/lodash/lodash/issues/1798 that this looks intentional, but I'm still unclear how I can make a module/library like https://github.com/AgentME/contain-by-screen use lodash v4 without having it overwrite the global `_`.

I can't have my library call `_.noConflict()` on the Lodash object, because if the application is also using Lodash v4, then `require('lodash')` in the library will get me the same instance of Lodash that the application is using and unset the global that it might be depending on.

**Comment by jdalton** [comment]
Lodash is only exposed in browsers. If you don't handle it in your apps initialization you could always tackle it in a proxy module (one that loads it, noConflicts it and then exports it). I'll patch `noConflict` to not replace the `_` unless it is `===` to the lodash instance calling `noConflict`.

**Comment by AgentME** [comment]
>If you don't handle it in your apps initialization

The contain-by-screen module is just some library to be used by applications. I don't want to require applications using my modules (or users of modules that depend on my modules that depend on lodash, or event further on) to have to have to do anything about globals when they `require` my library, whether or not I depend on lodash.

>I'll patch noConflict to not replace the _ unless it is === to the lodash instance calling noConflict.

That change to `noConflict` wouldn't fix the issue. If the application uses the same version of Lodash as my module, then when my module calls `require('lodash')`, the already-initialized version used by the application will be returned and === itself, and my module calling .noConflict() would remove the global possibly used by the application.

>you could always tackle it in a proxy module (one that loads it, noConflicts it and then exports it).

Could Lodash include this module so that I could do something like `var _ = require('lodash/no-global')`? Though it would have to do something other than just calling noConflict. I guess its code would have to look like this:

```js
var preexistingGlobalLodash = (typeof window !== 'undefined' ? window :
  typeof self !== 'undefined' ? self : {})._;
var _ = require('lodash');
if (preexistingGlobalLodash !== _) {
  _.noConflict();
}
module.exports = _;
```

Actually, that would fail to work if the application required my module before lodash v4, because then the application will get the instance of lodash already initialized by my library and no global will be remade.

**Comment by jdalton** [comment]
> There doesn't currently seem to be a way for browserify/webpack compatible libraries to depend on lodash without clobbering globals.

That was the reason for it. If you're worried about conflicts you can always cherry-pick the modules used and avoid the issue completely, i.e. `require('lodash/uniq')`.

**Comment by AgentME** [comment]
Can the lodash chaining functionality be loaded directly? It doesn't seem to have any methods on it when I use it after requiring it directly.

**Comment by jdalton** [comment]
>  Can the lodash chaining functionality be loaded directly?

Nope. You'd have to drop that.

**Comment by AgentME** [comment]
The lazy chaining specifically is a feature a lot of our code is designed around. There's no way to use that now without clobbering globals?

**Comment by jdalton** [comment]
You could always exclude it from your bundle (bundlers have options to do that) so that folks can include it as an external dep.

**Comment by AgentME** [comment]
contain-by-screen is a library that other people build into a bundle by using Browserify or Webpack. I'm not the one building bundles. My modules ought to work with Browserify and other bundlers without any special steps, like most libraries do with them. I'd rather not have to add special instructions for the common bundlers to each of my modules that depend on lodash (and to the modules that depend on modules that depend on lodash, etc).

**Comment by jdalton** [comment]
I've patched it https://github.com/lodash/lodash/commit/9a57b41b4ddd0f2b2aa25b61e793fc758c5dd5ff.

> That change to `noConflict` wouldn't fix the issue. If the application uses the same version of Lodash as my module, then when my module calls `require('lodash')`, the already-initialized version used by the application will be returned and === itself, and my module calling .noConflict() would remove the global possibly used by the application.

Meh. They could always expose it again. I mean look, I'm already bending over backwards for folks. I'm sorry I don't 100% cover your case but that's as far as I'm going to go.

**Comment by AgentME** [comment]
>They could always expose it again.

Only if they noticed `_` being replaced with a different version immediately. More likely (and unfortunately my experience) is that it escapes immediate notice and then breaks things when a code path depending on the global `_` being an older version of Lodash or underscore is used.

I don't think modules that depend on lodash and are browserifiable is an unusual use-case. Tons of modules depend on Lodash. I'm a little frustrated that Lodash quietly clobbers `_` in a way not possible to correctly avoid even when used in Browserify, apparently(?) in order to cater to people that bundle Lodash and don't know that they need to use `require` to reference bundled modules. If it wasn't this way, they could at least be told to use `window._ = require('lodash')`.

Could Lodash at least be made so that when it's in a browserify bundle to only set `_` when it's currently unset, and avoid overwriting an existing `_` global? That would at least solve the problem of it clobbering a different Lodash/underscore version being already globally set.

**Comment by jdalton** [comment]
> I don't think modules that depend on lodash and are browserifiable is an unusual use-case. Tons of modules depend on Lodash. 

If you're making this for others to consume via a bundle it's bananas to include the kitchen sink of lodash. I'd stick with cherry-picked methods regardless of losing lazy chaining.

> 'm a little frustrated that Lodash quietly clobbers _ in a way not possible to correctly avoid even when used in Browserify, apparently(?) 

I've patched `_.noConflict()` to correct it.

> in order to cater to people that bundle Lodash and don't know that they need to use require to reference bundled modules.

Not the case I'm catering to.

> If it wasn't this way, they could at least be told to use `window._ = require('lodash')`.

The `window` object is not always available (think web-worker).

> Could Lodash at least be made so that when it's in a browserify bundle to only set `_` when it's currently unset, so that it would avoid overwriting an existing `_` global? That would at least avoid the problem of a bundled Lodash silently clobbering a different already globally set version of Lodash or Underscore.

Naw. It needs to expose to the  global to enable code to access it outside the bundle. If that's not desired you can always call `noConflict`. I'm not a super fan of having multiple versions of Lodash or Underscore on a page so avoid it if possible.

**Comment by jdalton** [comment]
Annnnd lock.

**Comment by chadwilken** [comment]
Im running this through webpack, lodash is included in some modules but underscore is on the page's global object for use with Backbone (legacy code). I have tried to use noConflict, but continue to have issues with it overwriting the global _ object.
