### ISSUE TITLE
_.templateSettings with node.5.4.1 npm 3.5.2

### ISSUE THREAD

**Issue by mgamperl** [lodash/lodash#1857]
Hi,
I have just hat a encountered a problem with `._.templateSettings`

We are using node `5.4.1` and npm `3.5.2` and it seems that npm now shares dependencies (seems to use the same instance) with the same version of different modules.

example:
we are using lodash `3.10.0`
and a dependant module also uses lodash `3.10.0`

this means that both `require("lodash")` seem to reference the same instance because when we change the `._.templateSettings` property it also effects the dependant modules lodash and because that module is also using `_.template` it throws syntax errors and stops working.

I know that this is not really a bug of lodash but I would like to bring this issue to the table because the usage of `_.templateSettings`seems rather dangerous to me and this should maybe be mentioned in the docs. 

I am also thinking about raising an issue for npm because I imagine that this could be a problem in other situations too..

Hopefully my concern is clear..
Regards

**Comment by jdalton** [comment]
Yep that's how modules work. You can always pass template options to `_.template` directly.
For your use you can also use [_.runInContext](https://lodash.com/docs#runInContext) to create a pristine lodash instance which can be augmented without modifying the primary `lodash` package.

```js
var _ = require('lodash').runInContext();
```
