### ISSUE TITLE
ES6 docs

### ISSUE THREAD

**Issue by granteagon** [lodash/lodash#1860]
I'd love to see ES6 code examples / hints in the docs.  I'm learning ES6 now and it would be helpful to see shorter/sleeker syntax or "do this instead" type of hints.

**Comment by phated** [comment]
I've often received criticism (from newer and veteran devs) that ES2015+ in docs is a huge detractor and increases mental overhead for them.  Maybe this could be a separate project someone wants to work on but not integrated into the main docs.

**Comment by jdalton** [comment]
I'm wanting to simplify the existing doc examples further so moving to ES6 would just add complexity. I really want to focus on the methods as much as possible and cut anything distracting.

**Comment by StreetStrider** [comment]
> ES2015+ in docs is a huge detractor and increases mental overhead for them
Damn right. New ES is weird.

**Comment by jdalton** [comment]
> New ES is weird.

Naw I :heart: ES6+ but it's another thing to grok when lib usage should have the spotlight.

**Comment by milesj** [comment]
Destructuring is probably the only feature that can be really confusing. There's no reason to not use ES6 syntax when applicable, especially considering that ES5 code is currently dated, and will be so even more within the next year.

**Comment by jdalton** [comment]
Everyone knows plain ES3 JS let's not create unnecessary barriers for lodash adoption.

**Comment by milesj** [comment]
Simply stating that if the example permits the use of a let, spread, rest, or something similar, there should be no reason not to use it. It's not like the Lodash documentation examples are that complex to begin with -- it's merely function with arity calls.
