### ISSUE TITLE
isEqual malfunction on version 4.0.0

### ISSUE THREAD

**Issue by bnadim** [lodash/lodash#1863]
Hi, 

isEqual seems to be malfunctioning on object in lodash (at least under nodejs).
Simple example :
 - on lodash 4 : _.isEqual({a:1, b:1}, {b:1, a:1}) -> return false
 - on lodash 3 : _.isEqual({a:1, b:1}, {b:1, a:1}) -> return true

Based on documentation, lodash 3 seems to be the right answer.

Thank you for your help

**Comment by S-YOU** [comment]
may be it is fixed in 4.0.1, #1758, #1859

**Comment by bnadim** [comment]
Yes your are right sorry it's a duplicate.
