### ISSUE TITLE
Redundant comparison in the new toInteger function?

### ISSUE THREAD

**Issue by SyRenity** [lodash/lodash#1864]
Looking at the new toInteger function in lodash 4.0, I see the following comparison at line:
https://github.com/lodash/lodash/blob/4.0.0/lodash.js#L10179

```
return value === value ? (remainder ? value - remainder : value) : 0;
```

It looks to me as it could be simplified as
```
return remainder ? value - remainder : value
```
Or I'm missing something?

**Comment by joyvuu-dave** [comment]
NaN does not equal itself, thus the initial check.

**Comment by SyRenity** [comment]
@joyvuu-dave Makese sense :)
