### ISSUE TITLE
_.merge performance

### ISSUE THREAD

**Issue by elado** [lodash/lodash#1865]
`_.merge` seems to have really bad performance, compared to manual work (`Object.assign`s).

```js
var bench = fn => { let s = Date.now(); fn(); return Date.now() - s }
var users = _.times(1000).map(i => ({ type: 'user', id: i, name: `user ${i}` }))

bench(() =>
  users.reduce((state, u) => {
    return _.merge({}, state, { [u.type]: { [u.id]: u } })
  }, { user: {} })
)
```

Here's a jsbin with the comparison - http://jsbin.com/tuzaji/3/edit?js,console

**Comment by jdalton** [comment]
You're thinking of `_.assign`, `_.merge` does heavier lifting

**Comment by elado** [comment]
@jdalton  I referred specifically to `merge`.

In my example `{ user: {} }` is the initial value, and for each user the intention is to append it to the inner object, so eventually you have `{ user: { '1': { id: 1, name: 'user 1', type: 'user' }, '1': { id: 2, name: 'user 2', type: 'user' }, ... } }`.
Each user insertion creates a new immutable object with the entire state tree.
If there are 2 entries with same id in the array it would just merge the latter's data with the former's.

`_.assign` discards the value of the inner object.

The manual *nested* `Object.assign` (or `_.assign`) does the same work with significant performance improvement, but it requires knowledge of what's being merged, and how to merge it.

```js
users.reduce((state, u) => {
  return {
    ...state,
    [u.type]: {
      ...state[u.type],
      [u.id]: { ...state[u.type][u.id], ...u }
    }
  }
}, { user: {} })

users.reduce((state, u) => {
  return Object.assign({}, state, {
    [u.type]: Object.assign({}, state[u.type], {
      [u.id]: Object.assign({}, state[u.type][u.id], ...u)
    })
  })
}, { user: {} })
```

**Comment by jdalton** [comment]
Yep, _.merge does more than _.assign and Object.assign so expect it to be more expensive.
