### ISSUE TITLE
Difference of sets (array of objects)

### ISSUE THREAD

**Issue by azbshiri** [lodash/lodash#1867]
I have two array of objects, like below:
collection one:
```
[{
	"sku": "33220",
	"barcode": "",
	"name": "Lenovo S930 Dual SIM Mobile Phone"
}, {
	"sku": "TN2A",
	"price": 73000000.0,
	"barcode": "8412544031648",
	"name": "BOTELLA TRITAN BLUE 0.75 L"
}]
```
collection two:
```
[{
	"sku": "8440.60",
	"name": " SIGG FARMYARD SHEEP",
	"barcode": "7610465844069",
	"category": "SIGG",
	"price": "1,070,000.00"
}, {
	"sku": "TN2A",
	"name": "BOTELLA TRITAN BLUE 0.75 L",
	"barcode": "8412544031648",
	"category": "LAKEN",
	"price": "730,000.00"
}, {
	"sku": "TN2V",
	"name": "BOTELLA TRITAN GREEN 0.75 L",
	"barcode": "8412544031662",
	"category": "LAKEN",
	"price": "730,000.00"
}, {
	"sku": "TN2O",
	"name": "BOTELLA TRITAN ORANGE 0.75 L",
	"barcode": "8412544031655",
	"category": "LAKEN",
	"price": "730,000.00"
}]
```
how can I get the difference of sets?

**Comment by d10** [comment]
You can use [_.union](https://lodash.com/docs#union) to do that (or [_.unionWith](https://lodash.com/docs#unionWith) to enable using your own comparator).

**Comment by azbshiri** [comment]
_.difference(collection_one, collection_tow) returns 2

**Comment by d10** [comment]
Sorry, didn't really get what you meant just now. You can try [_.intersection](https://lodash.com/docs#intersection).

**Comment by azbshiri** [comment]
how can I get only the duplicate element?

**Comment by jdalton** [comment]
You can use [_.intersectionWith](https://lodash.com/docs#intersectionWith) to resolve the comparisons since the objects don't contain all the same properties, or `_.intersectionBy` to compare a single property. For more help check out our [gitter chat](https://gitter.im/lodash/lodash).
