### ISSUE TITLE
Regression in documentation website

### ISSUE THREAD

**Issue by alitaheri** [lodash/lodash#1869]
If I understand correctly with the version 4 of lodash. Requiring categories are no longer supported. 

But in the main page of the documentation https://lodash.com > Installation > **In Node.js:**

We still have:

```js
// or a method category
var array = require('lodash/array');
```

This will confuse new users very harshly.

**Comment by demoneaux** [comment]
Requiring categories is still supported, but requiring specific methods does not require knowing the category it is in, which simplifies the process of cherry picking (`lodash/array/chunk` to `lodash/chunk`, which does not need people to know the function category).
