### ISSUE TITLE
_.map(object, ...) fails when object contains a 'length' attribute

### ISSUE THREAD

**Issue by jabadia** [lodash/lodash#1870]
see this example:

var good = {
  'the': 4,
  'state': 3,
  'of': 2,
  'the': 6,
  'art': 15
};

var a = _.map(good, function(c, w) {
  return {
    word: w,
    count: c
  };
});
console.assert(a.length == _.keys(good).length, "bad array");
console.table(a);

var troublesome = {
  'the': 4,
  'state': 3,
  'of': 2,
  'the': 6,
  'art': 15,
  'length': 1
};

var b = _.map(troublesome, function(c, w) {
  return {
    word: w,
    count: c
  };
});
console.assert(b.length == _.keys(troublesome).length, "bad array");
console.table(b);
console.log('ok');

**Comment by alexlur** [comment]
I think this is the expected behavior.

> **Note**: As with other “Collections” methods, objects with a “length” property are iterated like arrays. To avoid this behavior use `_.forIn` or `_.forOwn` for object iteration. (See [Documentation](https://lodash.com/docs#forEach))

You can use either `_.mapKeys` or `_.mapValues`, which are specifically designed for objects.

**Comment by demoneaux** [comment]
@alexlur is right; as they are collection methods, objects with `length` are treated as arrays. For your specific purpose, you can also use something like [_.tranform](https://lodash.com/docs#transform), which will iterate through all the keys of the object.:

```js
_.transform(object, function(array, count, word) {
  array.push({ 'count': count, 'word': word });
}, []);
```
