### ISSUE TITLE
Adding prod method

### ISSUE THREAD

**Issue by yujiosaka** [lodash/lodash#1871]
numpy has a method called prod, which is to calculate prod of each element.
It is similar to _.sum except that prod multiplies elements instead of adding them.
Here is an example:

```
>>> np.prod([1, 2, 3])
6
```

Here is the document:
http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.prod.html

I created this issue because having this feature is consistent with sum method.

**Comment by jdalton** [comment]
Thanks for the request @yujiosaka! We'll keep an eye on user demand for it.
