### ISSUE TITLE
4.0.0 version of the _.chain(...).filter(RegExp.prototype.test, /abc/) shorthand

### ISSUE THREAD

**Issue by Zjaaspoer** [lodash/lodash#1872]
First of all, thank you for you absolutely amazing dedication to this project. For quite a while now this is the one library that my projects most heavily depend on. Please keep up the great work!

My issue:

I just switched to the new 4.0.0 release. Pre 4.0.0 I used variations of this shorthand a lot:

`_.chain(...).filter(RegExp.prototype.test, /abc/)`

Basically, being able to filter/reject etc strings in an array based on a regexp. In 4.0.0 this no longer works (also not with the _.matchesProperty shorthand)

I haven't really seen the above shorthand documented that often so its use is probably a bit hacky.

Does the 4.0.0 release support a similar shorthand?

Thanks!

**Comment by jdalton** [comment]
What you're referring to is `thisArg`. The remove is covered in the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v400). Instead you can do
```js
_.chain(...).filter(RegExp.prototype.test.bind(/abc/))
```
or
```js
_.chain(...).filter(_.bind(RegExp.prototype.test, /abc/))
```

**Comment by Zjaaspoer** [comment]
Did not know that, tried it out and works as advertised :) thanks for the quick reply!
