### ISSUE TITLE
npm release for v4.1.0 and v4.0.1?

### ISSUE THREAD

**Issue by screendriver** [lodash/lodash#1875]
Hi,

will there be a [npm release](https://www.npmjs.com/package/lodash) for `v4.1.0` and/or `v4.0.1`? I need that second argument for `omit()` and `pick()` :wink:

**Comment by jdalton** [comment]
Of course they will be published. Just as the ~120+ others have been. It'll shake out in a day or so.

**Comment by screendriver** [comment]
Thank you for the quick response :+1:
