### ISSUE TITLE
suggestion: _.hasDuplicates

### ISSUE THREAD

**Issue by qsona** [lodash/lodash#1876]
I often want to use a function that should be called `_.hasDuplicates`, which means

```
_.hasDuplicates([1, 2, 3]) // false
_.hasDuplicates([1, 2, 2]) // true
_.hasDuplicates([1, -1, 2], Math.abs) // true
```

lodash already has `_.uniq` so it can be written as `array.length !== _.uniq(array).length`, but it is a little difficult to read and has some extra calculations. 

I often use it to validate request parameters.
`const isValid = _.isArray(arr) && _.every(arr, _.isString) && !_.hasDuplicates(arr);`

I would be glad if you think about it.

**Comment by jdalton** [comment]
Thanks @qsona! We'll keep an eye on demand.

**Comment by qsona** [comment]
:+1: Thank you!
