### ISSUE TITLE
Too many changes are NOT backwards compatible!

### ISSUE THREAD

**Issue by artknight** [lodash/lodash#1878]
I am not sure what philosophy you guys are after, but upgrading to v4 should not require project re-writes across the board. I do understand that new features and optimizations are necessary but they come at a very high price!

Here are some examples where migration script did not do jack.

lodash v.3.1
_.each(this.files, function(file){...});

lodash v.4
_.each(this.files, _.bind( function(file){...} )); //have to use _.bind to keep the context

Another idea, once methods are introduced and adopted, please DO NOT change their behavior. You can add additional functionality, but do not take it away. Example *_.functions* was returning all methods in a scope ( including the ones on the prototype ) .... now it only returns the immediate methods. THIS BREAKS STUFF. *So please do not take away existing functionality* 

Changes like that should NOT be necessary when upgrading!

**Comment by StreetStrider** [comment]
@artknight, theh. semver, u know? When major version upgrades any breaking changes possible. To receive only safe updates one should stick with certain major version, like `^3`.

**Comment by artknight** [comment]
@StreetStrider I am sticking with major versions. v4 seems like a major version, does it not?

**Comment by StreetStrider** [comment]
@artknight, if you stick to `v4` you'll receive only compatible changes (from one 4.x to another), but update from 3 → 4 contain non-compatible ones. That's the meaning of major release.

**Comment by artknight** [comment]
This is just saying *you do not care* what happens to all the folks who have been using lodash.

**Comment by jdalton** [comment]
@artknight Lodash follows [semver](http://semver.org/), the versioning scheme for npm packages, and as such a major release (bump from 3 to 4 signified breaking changes).

**Comment by jdalton** [comment]
For a list of breaking changes see the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v400).

**Comment by max-l** [comment]
I have to agree that one should expect breaking changes when semver is used. 

But I'm wondering about this particular change, the need to wrap functions with _.bind(), is there something I could read about the rational for this change ?

**Comment by jdalton** [comment]
The `thisArg` param is largely unused, complicates implementations, and in modern environments can be tackled with `Function#bind` or arrow functions.

**Comment by max-l** [comment]
Unused by whom ?  I use it all over the place, I did not know I was so unique ;-)

**Comment by jdalton** [comment]
Yep, and know the language is to a place you don't need the param.
