### ISSUE TITLE
lowerCase is removing '.' characters in version 4.1

### ISSUE THREAD

**Issue by thematho** [lodash/lodash#1881]
The functions `_.lowerCase` or `_.toLower` removes all the '.' characters in the returned String.
[Here](https://plnkr.co/edit/3WiETl) is a plunker with the example
 Didn't notice this issue with the version 3.X
e.g.:
`_.lowerCase("1.2.3")`
`// returns  '1 2 3'`

Regards

**Comment by jdalton** [comment]
The `_.toLower` and `_.lowerCase` methods didn't exist in v3.

The `lowerCase` method is like other "case" methods in that it handles compound words.
The `_.toLower` is not a case method and so will return `'1.2.3'`.
