### ISSUE TITLE
Using lodash in real use-cases (1)

### ISSUE THREAD

**Issue by justinhelmer** [lodash/lodash#1882]
Is there a better way to take advantage of lodash to accomplish the same result?

**Goal:** return a promise that resolves with `true` if `[ A && (B || C) ]`
```js
// Q.all() resolves with an array of fulfillment values.
return Q.all([
  truthyPromiseA(),    // resolves with true
  Q.all([
    truthyPromiseB(),  // resolves with false
    truthyPromiseC()   // resolves with true
  ])
]).then(_.partialRight(_.isEqual, [true, [false, true]]));
```

**Comment by justinhelmer** [comment]
Removed temp `[Question]` label

**Comment by jdalton** [comment]
This is better tackled in our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by justinhelmer** [comment]
thanks for the info.
