### ISSUE TITLE
Possible error in documentation?

### ISSUE THREAD

**Issue by ErikBean** [lodash/lodash#1889]
Hello,
Let me say that I :heart: lodash and get a lot of awesome stuff done with it, so thank you for contributing to this great project.
Here's the issue: I think there is an error in the 4.0.1 docs. I have been scratching my head over this for a bit:
The entry for [_.unset](https://lodash.com/docs#unset) says that it returns true if the property is deleted, else false. 
However, In the second usage example: 
```
var object = { 'a': [{ 'b': { 'c': 7 } }] };
_.unset(object, 'a[0].b.c');
// → true

console.log(object);
// → { 'a': [{ 'b': {} }] };

_.unset(object, 'a[0].b.c');
// → true
```
Am I correct in thinking that the second "true" return value should be "false"? 
My interpretation here is  that the property at a[0].b.c was removed in the first example, and the property is no longer there when _.unset is called a second time, so the property was not deleted. 
I just wanted to make you aware of this issue in case my hunch here is right. 
Thanks,
-Erik

**Comment by jdalton** [comment]
The example is correct. Think of it like the `delete` operator. It will return `false` if it's unable to remove the properties. If the properties are removed already then its still unset.

**Comment by demoneaux** [comment]
@jdalton maybe you misread? The second demo should return `false` IMO.

**Comment by jdalton** [comment]
Nope. It's correct. The only time it will return false is if it's a read only property.
For example:
```js
var o = {};
delete o.foo; // true
```

**Comment by demoneaux** [comment]
Cool, never knew about that :)
