### ISSUE TITLE
_.first with callback broken, or documentation misleading

### ISSUE THREAD

**Issue by ciddan** [lodash/lodash#189]
Hey,

I've been using lodash and loving it, apart from one thing. Either `_.first`called with a callback is broken or the documentation is misleading/wrong.

Docs state: `If a callback function is passed, the first elements the callback returns truthy for are returned.`.

That's not what happens though. Here's [a jsFiddle](http://jsfiddle.net/Af7eN/2/) showing the problem. It seems like `_.first` always shortcuts out on the first falsy result.

**Comment by davis** [comment]
can we still use _.first for takewhile?

**Comment by jdalton** [comment]
@davis 
> can we still use _.first for takewhile?

Not in v3, you'd use `_.takeWhile`

**Comment by davis** [comment]
oh. duh. haha thanks :)
