### ISSUE TITLE
is _.compact a special case of _.filter?

### ISSUE THREAD

**Issue by bcherny** [lodash/lodash#1890]
if so, why not rm .compact?

```js
const myArray = [0, 1, 2, null, undefined, 'foo']
assert.deepEqual(_.compact(myArray), _.filter(myArray))
```

**Comment by jdalton** [comment]
Yep `_.compact` is a form of `_.filter`. I left it in because the leap to no-iteratee `_.filter` is something folks are less familiar with than say iteratee shorthands.

**Comment by bcherny** [comment]
makes sense. thanks for the quick response.
