### ISSUE TITLE
Is this the behaviour of _.remove

### ISSUE THREAD

**Issue by SridharGS** [lodash/lodash#1892]
**_.remove**

_Arguments_

_array (Array): The array to modify.
[predicate=_.identity] _(Function|Object|**string**)_: The function invoked per iteration.
[thisArg] (*): The this binding of predicate._

Consider

var temp=[ {"test":"test"},{"test1":"test1"}];
_.remove(temp,{"test":"test"})

this removes object {"test":"test"}

but when

var temp =["test","test1"]

_.remove(temp,"test")

this wont remove anything. Is this a bug please let me know
 
![screen shot 2016-01-28 at 9 29 19 am](https://cloud.githubusercontent.com/assets/8552839/12634671/aa4d979a-c5a1-11e5-89e0-ddf77c37b15e.png)

**Comment by jdalton** [comment]
The `_.remove` method accepts a predicate function or predicate shorthand not the actual value to remove. What you're looking for is `_.pull`.

**Comment by bsonntag** [comment]
I bashed into this, too.
Could maybe `_.remove`'s documentation point to `_.pull`?

**Comment by jdalton** [comment]
> Could maybe `_.remove`'s documentation point to `_.pull`?

Yes! Would you be up for sending a PR? All you would have to do is modify the jsdoc in the [lodash.js](https://github.com/lodash/lodash/blob/master/lodash.js) file. No doc building needed.

**Comment by bsonntag** [comment]
> Yes! Would you be up for sending a PR?

Sure!

By the way, I noticed the CONTRIBUTING.md file is missing in master. Is [this](https://github.com/lodash/lodash/blob/3.10.1/CONTRIBUTING.md) still valid?
Also, this broke "Contributing" links in lodash.com and the repo's readme.

**Comment by jdalton** [comment]
> Links are still broken, tho.

Updated the site link :)
