### ISSUE TITLE
Question: How to invoke method recursively?

### ISSUE THREAD

**Issue by richzw** [lodash/lodash#1893]
I want change the keys of this object

```js
var obj = { a: 10, b: { c: 20, d: { e: 30 } } };
```

to

```js
var obj = { a1: 10, b1: { c1: 20, d1: { e1: 30 } } };
```

which is add `1` to every key of object `obj`.

I try to do it with `mapKeys`

```js
_.mapKeys(obj, function (val, key) {
	return key + '1';
});
```

However, it just change key `a` and `b`, without the embedded object. So I want to invoke `mapKeys` recursively. Is it possible? If so, how to do that?

**Comment by jdalton** [comment]
We currently don't have a `mapKeysDeep` method. If you search the issues I believe it has been requested so you could jump on the relevant thread and :+1: it.
