### ISSUE TITLE
ifFunction(cb, cb(someArg))

### ISSUE THREAD

**Issue by granteagon** [lodash/lodash#1894]
Does the callback for you if the argument is a function.  Might be useful, although trivially.

**Comment by alitaheri** [comment]
if the `cb` is not a function you will still see the error. This is because the `cb(someArg)` is evaluated anyway. so it should be: `ifFunction(cb, ...args)`, so `ifFunction` can call `cb` like this: `cb(...args)`.

**Comment by jdalton** [comment]
I think this would be more appropriate as a `mixin` or composed with `_.cond`, `_.flow`, or `_.partial`.
