### ISSUE TITLE
_.curryRight should ignore arguments in excess of arity

### ISSUE THREAD

**Issue by smockle** [lodash/lodash#1896]
I did not expect for `sum10(2, 3)` in the following code to ignore the partial application of `sum10`. I’ve tested this with the master branch of lodash.

With `_.curryRight`:
```
$ node
> var curryRight = require('lodash/curryRight');
undefined
> curryRight
[Function: curryRight]
> function add(a, b) { return a + b; }
undefined
> var sum = curryRight(add);
undefined
> var sum10 = sum(10);
undefined
> sum10
{ [Function: wrapper] placeholder: undefined }
> sum10(2, 3)
5
```

For comparison, here is the same partially-applied function with `_.curry`:
```
$ node
> var curry = require('lodash/curry');
undefined
> curry
[Function: curry]
> function add(a, b) { return a + b; }
undefined
> var sum = curry(add);
undefined
> var sum10 = sum(10);
undefined
> sum10
{ [Function: wrapper] placeholder: undefined }
> sum10(2, 3)
12
```

**Comment by jdalton** [comment]
Yep, we allow that. It's by design.

**Comment by smockle** [comment]
Okay, thanks @jdalton! Is there a reason the behavior is different for `_.curry`?

**Comment by jdalton** [comment]
Ah, I misread your issue. The way `curryRight` works is by applying arguments to the right.

If args are applied to the left they can push those to the right out. In this case you're complete args would be `[2, 3, 10]`

**Comment by smockle** [comment]
Oh, that makes perfect sense. Sorry I was confused, and many thanks for taking the time to explain! I appreciate it.
