### ISSUE TITLE
v3 _.pick vs v4 _.pickBy removed key field

### ISSUE THREAD

**Issue by AndreasPresthammer** [lodash/lodash#1900]
The following in v3 works:

`_.pick({ foo: 'bar', baz: 'brrr' }, function(val, key) { return key === 'foo'; });`
gives: {foo: "bar"}

But the same in v4 using _.pickBy() doesn work

`_.pickBy({ foo: 'bar', baz: 'brrr' }, function(val, key) { return key === 'foo'; });`
gives: {}

The callback in _.pickBy only provide the value, but not the key from the object your picking from. Is this intended? The above use case can be solved in a different way, but it's still a surprising breaking change which doesn't seem to be documented.

**Comment by demoneaux** [comment]
The `key` param was since added back in v4.1.0.
