### ISSUE TITLE
Distributed builds shouldn't have "Custom Build" in the header

### ISSUE THREAD

**Issue by FayneAldan** [lodash/lodash#1903]
'nuff said.

**Comment by jdalton** [comment]
They are generated from `lodash-cli`.

**Comment by FayneAldan** [comment]
But the builds distributed on the website shouldn't say "Custom Build," as it isn't custom.
https://raw.github.com/lodash/lodash/4.0.1/dist/lodash.js

**Comment by jdalton** [comment]
If you have an issue with `lodash-cli` its repo is more appropriate to file bugs.
