### ISSUE TITLE
The website shows incorrect sizes for the gzipped builds

### ISSUE THREAD

**Issue by FayneAldan** [lodash/lodash#1904]
For 4.0.1, the website says the gzipped builds are 4 kB for the core build and 20 kB for the full build, but they're actually 13.16 kB and 62.233 KB, respectively.

**Comment by jdalton** [comment]
No minified and gzipped they're 4 and 20. You're on a roll today.

**Comment by FayneAldan** [comment]
Okay. I'll be honest, I didn't even really know what gzipped meant. However, the Chrome network log shows that I'm actually receiving both the gzipped files as 437 B, not as 4 and 20...

**Comment by jdalton** [comment]
> I'm actually receiving both the gzipped files as 437 B, not as 4 and 20 kB.

No worries. Keep learning and digging. You'll get there.

**Comment by FayneAldan** [comment]
Caching is so annoying sometimes... The files are actually 5.6 KB and 21.1 KB, not 4 and 20.
`(THOROUGHLY JAPED AGAIN BY THE GREAT PAPYRUS!!!)`
(and yes, i just referenced undertale)

**Comment by jdalton** [comment]
It depends on the tool you're using. I got my sizes from `gzip-size-cli`.

**Comment by jdalton** [comment]
and the level of gzip
