### ISSUE TITLE
update isHostObject in lodash-compat

### ISSUE THREAD

**Issue by olmobrutall** [lodash/lodash#1905]
Hi guys, 

I'm using react-bootstrap that depends on lodash-compat. Unfortunately the version v3.10.2 contains an old implementation of `isHostObject` that throws an exception when is being defined, not the first time is used. 

FROM https://github.com/lodash-archive/lodash-compat/blob/master/lodash.js
```
    /**
     * Checks if `value` is a host object in IE < 9.
     *
     * @private
     * @param {*} value The value to check.
     * @returns {boolean} Returns `true` if `value` is a host object, else `false`.
     */
    var isHostObject = (function() {
      try {
        Object({ 'toString': 0 } + ''); <-------- ANNOYING EXCEPTION HERE 
      } catch(e) {
        return function() { return false; };
      }
      return function(value) {
        // IE < 9 presents many host objects as `Object` objects that can coerce
        // to strings despite having improperly defined `toString` methods.
        return typeof value.toString != 'function' && typeof (value + '') == 'string';
      };
    }());
```

This means that if you have `Pause On Caught Exception` in Chrome you'll get stopped in the wrong place every single time that you refresh the page. It's quite annoying.   
 
Looks like the new version has solved this problem. FROM https://github.com/lodash/lodash/blob/bc8efe4cac92dc2dee7dfd855fe713cb54efc929/dist/lodash.core.js

``` /**
   * Checks if `value` is a host object in IE < 9.
   *
   * @private
   * @param {*} value The value to check.
   * @returns {boolean} Returns `true` if `value` is a host object, else `false`.
   */
  function isHostObject(value) {
    // Many host objects are `Object` objects that can coerce to strings
    // despite having improperly defined `toString` methods.
    var result = false;
    if (value != null && typeof value.toString != 'function') {
      try {
        result = !!(value + '');
      } catch (e) {}
    }
    return result;
  }
```

I know lodash-compat is discontinued but, is there any chance that the new implementation is ported back to v3.10.2?. React-bootstrap can not update to v4 because they need IE8 compatibility https://github.com/react-bootstrap/react-bootstrap/issues/1635#issuecomment-176689227

Thanks in advance.

**Comment by jdalton** [comment]
> I know lodash-compat is discontinued but, is there any chance that the new implementation is ported back to v3.10.2

Probably not.

> React-bootstrap can not update to v4 because they need IE8 compatibility

React [dropped IE8 support](https://facebook.github.io/react/blog/2016/01/12/discontinuing-ie8-support.html). For older environment support lodash v4 will work with [es5-shim](https://github.com/es-shims/es5-shim) and (optionally) [es6-shim](https://github.com/es-shims/es6-shim) added.
