### ISSUE TITLE
Docs about _.isEqual change in 400

### ISSUE THREAD

**Issue by klimashkin** [lodash/lodash#1908]
Hi!
There is no info about _.isEqual changes in 400 changelog, about third parameter.
And because of that we spent couple of hours figuring out what's wrong in out big big project in some part of it.
Could you add in changelog that _.isEqual was split to _.isEqual and _.isEqualWith? Thank you

**Comment by jdalton** [comment]
Done!

**Comment by jdalton** [comment]
For future reference the changelog is unlocked to allow anyone to contribute, tweak, and update.
