### ISSUE TITLE
lodash/fp alias set to assoc?

### ISSUE THREAD

**Issue by billyjanitsch** [lodash/lodash#1911]
Lodash/fp aliases `omit` to `dissoc`, so it's kind of surprising that it doesn't alias `set` to `assoc`.

**Comment by jdalton** [comment]
Moved to #1912

**Comment by jfmengels** [comment]
Would it make sense now (because I feel like `assoc` and `dissoc` should be polar functions with opposite behaviors) to add deeply nested omitting with `omit`?
SInce you can do
```js
var object = { a: { c: 20 } };
_.set(object, 'a.b', 100)
// { a: { b: 100, c: 20 } }
```
but not
```js
_.omit(object, ['a.b'])
// { a: { c: 20 } }
```
