### ISSUE TITLE
lodash/fp docs

### ISSUE THREAD

**Issue by willfrew** [lodash/lodash#1914]
I found out about `lodash/fp` yesterday whilst browsing some issues, and realised there's not much in the docs to let people know that it's there! I thought about sending a PR to add it into the module formats in the README, but since it's a part of the module, that didn't seem right.

Where's the best place to add a blurb about fp into the docs?

P.S. _Thank you so much_ for adding support for this into core. The JS ecosystem just got a little better.

**Comment by demoneaux** [comment]
lodash will soon be getting generated docs for `lodash/fp` due to @jfmengels’s work in #1897.

**Comment by willfrew** [comment]
Oh, nice one!
