### ISSUE TITLE
Lodash breaks when transpiled twice

### ISSUE THREAD

**Issue by gaearon** [lodash/lodash#1916]
Original issue: https://github.com/rackt/redux/pull/611#issuecomment-177625155

Basically we started using Lodash as a dependency of Redux, and I noticed that UMD builds can no longer be tested from our Mocha tests. After more investigation I realized that they break *if they are transpiled twice* because Babel inserts `use strict` in the code, and then Lodash `function () {return this;}` global detection returns `undefined`.

I'm not sure whether this can be considered a Lodash issue. Definitely transpiling twice is wrong but some people do that due to bad configurations. We used to support transpiling twice, but now due to our new dependency on Lodash, transpiling twice is broken.

What do you think?

**Comment by jdalton** [comment]
The `Function('return this')` is our Hail Mary attempt.

That means it's failing

 `freeGlobal` or `((freeWindow !== (thisGlobal && thisGlobal.window)) && freeWindow)` or `freeSelf` and `thisGlobal`

Is there a global it can attach to?

**Comment by gaearon** [comment]
Oh, I see. I tried [these steps](https://github.com/rackt/redux/pull/611#issuecomment-177644683) and, if I recall correctly, I used `require()` in a `node` shell to verify that it breaks. It also definitely was breaking in Mocha tests when I made them `require()` that double-transpiled UMD build.

**Comment by gaearon** [comment]
Or, to be more precise, it broke in Mocha tests with a normal UMD build *because* our Mocha configuration was transpiling it with Babel. That's how I discovered the issue in the first place.

**Comment by gaearon** [comment]
Please see https://github.com/jdalton/redux/pull/1 for steps to reproduce

**Comment by gaearon** [comment]
Interesting. Apparently `return this` is not even your code. It's what Webpack inserts:

```js
	module.exports = isPlainObject;
	/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))
```

Could this be an attempt to polyfill a `global` reference?

**Comment by jdalton** [comment]
Yes, that's it. Ours, using `Function('return this')` is immune to the strict mode rules, but theres because it uses a function literal will inherit the strict mode rules.

**Comment by jdalton** [comment]
Our `Function(...)` use is a last attempt because it can cause issues in CSP restricted environments.

**Comment by gaearon** [comment]
```
  node: {
    global: false
  }
```

in the Webpack config solved the issue.
I'll report this to Webpack.

**Comment by jdalton** [comment]
Without that though won't `global` be an undefined variable reference?

**Comment by gaearon** [comment]
Oh right, it would in browser.

**Comment by jdalton** [comment]
I have a fix. Refining it. I :heart: webpack, so nice!

**Comment by jdalton** [comment]
Add this as a plugin in the `webpack.config.base.js`
```js
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    {
      'apply': function(compiler) {
        compiler.parser.plugin('expression global', function() {
          this.state.module.addVariable('global', "Function('return this')()");
          return true;
        });
      }
    }
  ]
```

**Comment by jdalton** [comment]
You can make that `global` var as complicated as needed I just used the `Function(...)` flavor to show it working.

**Comment by jdalton** [comment]
Closing as `invalid` as it's not a Lodash specific issue (and we've resolved it).

**Comment by jdalton** [comment]
See https://github.com/jdalton/redux/blob/84f223b949a30e80b0bff55511db395136330718/webpack.config.base.js

**Comment by jdalton** [comment]
I updated the `global` replacement with
```js
"(function() { return this; }()) || Function('return this')()"
```
so that under normal cases it avoids `Function(...)`.

Related to https://github.com/webpack/webpack/issues/1963.
