### ISSUE TITLE
[lodash/fp] padStart don't accept padding characters

### ISSUE THREAD

**Issue by tarossi** [lodash/lodash#1917]
`padStart` (and maybe also `pad` and `padEnd`) doesn't allow one to specify other padding characters, as it does its standard *Lodash* counterparts.

**Comment by jdalton** [comment]
This is by design as fp functions don't dig optional args. We'd have to create another method name for the case that supports `chars`. Maybe `padChars`, `padCharsStart`, & `padCharsEnd`?

**Comment by tarossi** [comment]
Yeah, I kinda see that coming. That's fine by me.
