### ISSUE TITLE
Re-state purposes of _.tap and _.thru in docs

### ISSUE THREAD

**Issue by jjt** [lodash/lodash#1921]
`_.thru` seems like a better recommendation for _altering_ intermediate results in a chain, and `_.tap` for _triggering side-effects_ based on the intermediate results (console.log, fs write, etc).

The only way `_.tap` can change the intermediate values in the chain is by mutative side-effects, which isn't something to be encouraged, IMO.

**Comment by jdalton** [comment]
The `_.thru` method allows more than just augmenting it allows replacing. I'm satisfied with the docs for them as is but if you'd like to open a PR with tweaks I'm open to reviewing changes.

**Comment by jjt** [comment]
Yup, `_.thru` seems like the better candidate for anything that will augment/mutate/replace the intermediate value, where `_.tap` is a good candidate for anything that _won't_ augment/mutate/replace the intermediate value (ie. side-effects).

**Comment by parshwamehta13** [comment]
@jjt As you mentioned `_.thru` is a method for mutation of argument and supplying it as the argument for the next method (or more appropriately node in the method chain pipeline) and `_.tap` should be used for side-effects the example for tap shows mutation hence the purpose is defeated if we go by the docs.
