### ISSUE TITLE
Add _.trunc (Math.trunc) 

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#1930]
Is there a reason [`Math.trunc()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc) is not available as `_.trunc` under Math?

The [implementation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc#Polyfill) is straightforward:

```js
Math.trunc = Math.trunc || function(x) {
  return x < 0 ? Math.ceil(x) : Math.floor(x);
}
```

**Comment by jdalton** [comment]
I renamed String to `_.truncate` on the off chance that we'd add it. As with other requests let's see if there's user demand before adding to core : D

**Comment by jdalton** [comment]
It may shake out of the ES6 parity too.
