### ISSUE TITLE
what happens when debounce.maxWait is triggered?

### ISSUE THREAD

**Issue by vvo** [lodash/lodash#1934]
Hey hi, I am trying to understand a behavior in my app that may be related to how maxWait in debounce is handled.

Basically I am debouncing keystrokes on an input and in some rare cases the last keystroke will never be catched.

Options used:

```js
debounce(inputCallback, 100, {
  leading: true,
  maxWait: 200,
  trailing: true
});
```

While using those options (lodash 3), is there a possibility that the last keystroke is not triggered and trailing: true is not working as I thought?

A suite of events:

- t0: keystroke 1
- t0+25ms: keystroke 2
- t0+200ms: keystroke 3
- t0+220ms: keystroke 4

It seems that I only get keystroke 1 and keystroke 3

While I would have thought I would get keystroke 1, 3 and 4 (trailing: true).

The bug in my app (not getting the last keystroke) is hard to trigger/track so maybe you have a pointer here?

If I do not use maxWait then everything is fine.

**Comment by jdalton** [comment]
The `maxWait` option kicks in if the default `wait` is never completed in a given period. Think of it as fail safe to get at an invocation in even if the call is being non-stop debounced (kicked down the road).
