### ISSUE TITLE
lodash - lodash-fp inconsistency for .map in v4.2.0

### ISSUE THREAD

**Issue by arronmabrey** [lodash/lodash#1937]
I'm using the new lodash-fp 4.2.0 

I found an inconsistency with the `map`  function, that was surprising and took a little while to track down.
I wanted to raise an issue to find out if it is a bug or if I'm using the lib wrong.

The expectation is to have the same output from both the `_.map` and `__.map` functions.

```js
const __ = fp(_.runInContext());
const input = {foo: 42};
const fn = (v,k) => [v,k];

_.map(input, fn)
// [
//   [
//     42,
//     "foo"
//   ]
// ]
__.map(fn, input)
// [
//   [
//     42,
//     null
//   ]
// ]
```

**Comment by jdalton** [comment]
This is by design. The fp flavors of methods tend to drop extra args in iteratees like `index,array` and just provide `value` to enable easier composition.

We'll likely make this configurable in the future.

**Comment by arronmabrey** [comment]
@jdalton thanks, for the explanation. This is okay with me, I can easily adjust to accommodate for this difference. Just wanted to make sure it wasn't a bug ;-)

**Comment by jdalton** [comment]
BTW If anyone wants to help with docs [our wikis](https://github.com/lodash/lodash/wiki/Build-Differences) allow editing.
