### ISSUE TITLE
Where to start contributing? 

### ISSUE THREAD

**Issue by Xavdidtheshadow** [lodash/lodash#1938]
I've got a method I'd like to add. Looking through the repo, there's a lot of folders and files, but it's not obvious what I should edit to add this method. My guess is `lodash.js`, but i'm not sure if that's where changes start or that's a file compiled by build tools and there's another folder where all of the base source goes. 

Anyway, it'd be awesome to have a short section in the readme with important contributing points such as: 

* edit X file
* add corresponding tests in Y file
* add documentation with style Z (and where)

**Comment by jdalton** [comment]
All you need to do is update the lodash.js file in the root and add a test to the test/test.js file. If you're up for it you could send a PR clarifying things in the contributing.md.

**Comment by tmoc** [comment]
Out of curiosity, why is there just 1 source file (lodash.js)?

I was looking at Ramda's source and they have it organized with a main dir containing a file per public API method, then an internal dir with the private functionality. I found it very easy to understand how the library fit together with that structure.

**Comment by jdalton** [comment]
I find hunting down modules and sub modules and their sub modules makes it harder to understand and try to grok everything. A single searchable file is great.

If you dig the modularized form by all means [have at it](https://github.com/lodash/lodash/tree/npm).

**Comment by tmoc** [comment]
Thanks, didn't know about that.

**Comment by jdalton** [comment]
There's also [amd](https://github.com/lodash/lodash/tree/amd), [es](https://github.com/lodash/lodash/tree/es), & [npm packages](https://github.com/lodash/lodash/tree/npm-packages) branches too :sunglasses:
