### ISSUE TITLE
Missing fp.md file in /docs? 

### ISSUE THREAD

**Issue by ErikBean** [lodash/lodash#1939]
Hello you wonderful lodashians. 
I am really excited about lodash/fp, and I noticed that running lib/doc/build.js --fp generates a documentation file that lives alongside README.md called fp.md. [Here is a Gist](https://gist.github.com/ErikBean/c9c0a9e9db7672750aa7) with the generated file
I was surprised to find that the fp.md file is not included in the source of the gitHub repo. I was looking for a branch to view this file on, or some link on https://lodash.com/docs.

Is this intentional? Is the documentation for /fp not yet complete? Just trying to get the full picture here. 

I was about to open a PR adding this file, but I noticed that the contribution guidelines say "Don’t worry about regenerating the dist/ or doc/ files" so I held off.

Thanks,
-Erik

**Comment by jdalton** [comment]
Hi @ErikBean!

> Is this intentional? Is the documentation for /fp not yet complete? Just trying to get the full picture here.

The fp docs are not fully baked yet. I've pushed the 2 relevant commits after our 4.2.1 bump until I can have time to review and cleanup. That said if you'd like to contribute to our [wiki](https://github.com/lodash/lodash/wiki/Build-Differences) that would rock.

**Comment by ErikBean** [comment]
Thanks for the quick response!
Not sure what I would do in the wiki space, add a custom fp build? I would think that fp docs would not be in the wiki but on the lodash site, right?

**Comment by jdalton** [comment]
It's if you wanted to add a bit about what the fp build does.

**Comment by ErikBean** [comment]
Ok, thanks. I may do that tonight.
