### ISSUE TITLE
_.each should accept another arg `context`

### ISSUE THREAD

**Issue by lichenhao** [lodash/lodash#1941]
example:
```
_.each([1,2,3], function () {
console.log(this.name); // => output: Alfred.
}, {
 name: 'Alfred'
})
```

**Comment by Florian-R** [comment]
This was the case in the past, but it has been removed in V4 to simplify the signature.
See the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v400), you' ll have to use `_.bind` instead

**Comment by jdalton** [comment]
or arrow functions ;)

**Comment by jtakalai** [comment]
This is a real problem for those who would like to use lodash as a drop-in replacement for underscore. This change breaks e.g. https://github.com/dhruvaray/backbone-associations

Any chance you could support thisArg / context as third argument for compatibility's sake?

**Comment by jdalton** [comment]
> This is a real problem for those who would like to use lodash as a drop-in replacement for underscore. 

Lodash hasn't been a drop-in replacement for Underscore since v1 (3 yrs ago)

> Any chance you could support thisArg / context as third argument for compatibility's sake?

Folks should make the migration regardless of being drop-in or not.

**Comment by jtakalai** [comment]
Well, I'll try kicking backbone-associations to fix their code; put in a pull request for the _.bind solution. Let's see if they can get their act together. Until then we'll just use old lodash; or look into stuff like https://github.com/misantronic/lodash-context/blob/master/lodash-context.js
