### ISSUE TITLE
Include "since" metadata for functions in docs/jsdoc

### ISSUE THREAD

**Issue by robations** [lodash/lodash#1942]
Every time I get an `... is not a function` error with lodash it triggers a hunt through the respository, PRs and issues etc, to work out when the feature was first added (and then work out why I'm pegged back to an older version). If there was a "since version 1.2.3" data added to each function it would make this a little easier.

**Comment by jdalton** [comment]
Instead of hunting you can always check the [changelog](https://github.com/lodash/lodash/wiki/Changelog). A `@since` tag would rock but with over 200 methods I don't have time to add them. I'd accept a pull request though.

**Comment by jdalton** [comment]
If you make a PR be sure to modify the lodash.js source and not the generated docs.

**Comment by robations** [comment]
Thanks, I was not aware of the wiki changelog.

I'll add to my list of candidate OSS PRs though time isn't my friend this month!

**Comment by jdalton** [comment]
:rocket: !
