### ISSUE TITLE
please add the option to sort by descending members in sortBy 

### ISSUE THREAD

**Issue by vzaidman** [lodash/lodash#1944]
for example with one of the following syntax:
`_.sortBy(people, {age: -1}, {name: 'asc'}, {lastName: false}, '!aaa', 'bbb'); `

**Comment by jdalton** [comment]
You're looking for [_.orderBy](https://lodash.com/docs#orderBy).

**Comment by vzaidman** [comment]
right! why sortBy exists then?

**Comment by jdalton** [comment]
Convenience of not having to specify an array of iteratees for an established common case.

**Comment by kanstantsin-chernik** [comment]
orderBy is not stable
