### ISSUE TITLE
`lodash/fp/reject`'s predicate does not get called with index

### ISSUE THREAD

**Issue by aaronjensen** [lodash/lodash#1945]
This may apply to other `fp` functions, I haven't tested them all, but at least w/ `reject` only the value gets passed to `reject`

Expected:

```js
reject = require('lodash/fp/reject')
reject((_, index) => index === 1, [1, 2, 3]) // => [1, 3]
```

Actual:

```js
reject = require('lodash/fp/reject')
reject((_, index) => index === 1, [1, 2, 3]) // => [1, 2, 3]
```

**Comment by jdalton** [comment]
This is by design to aid in fp composition. In a future release this will be configurable via `lodash/fp/convert`.

**Comment by aaronjensen** [comment]
how does this aid in fp composition?

**Comment by jdalton** [comment]
It helps avoid issues caused by function which accept optional secondary params.

```js
['6', '08', '10'].map(parseInt);
// => [6, NaN, 2]
```

**Comment by aaronjensen** [comment]
So, you're saying it is worth differentiating from the existing lodash functions and docs so that users of fp functions do not get bit by attempting to map with `parseInt` or other functions that accept optional secondary args (are there many of these?). Was there an original issue that was opened where someone was bit by this? 

Does this mean that all fp functions that take predicates have this limitation? This greatly reduces their utility and is quite surprising, especially since I can't seem to find any documentation for the fp functions, so I was left guessing/thinking this was a bug.

Is there another way you would recommend dropping the item at index 1 with lodash/fp like I was trying to do in my example?

**Comment by jdalton** [comment]
> Does this mean that all fp functions that take predicates have this limitation? 

Yes.

>  Was there an original issue that was opened where someone was bit by this?

Aligning with other FP libs.

> This greatly reduces their utility and is quite surprising

Turns out not so much but it will be configurable in the future for those that want those extra params.

> especially since I can't seem to find any documentation for the fp functions, so I was left guessing/thinking this was a bug.

Our [wikis](https://github.com/lodash/lodash/wiki/Build-Differences) our open if you'd like to contribute. You could also help spruce up [the WIP doc builder](https://github.com/lodash/lodash/blob/master/lib/doc/apply-fp-mapping.js) for fp.

> Is there another way you would recommend dropping the item at index 1 with lodash/fp like I was trying to do in my example?

You could do some ugly wrapping or you could compose your own curried for with the normal lodash methods for now.

**Comment by aaronjensen** [comment]
> You could do some ugly wrapping or you could compose your own curried form with the normal lodash methods for now. In the next minor bump we'll make it configurable.

Thank you for this link, the additional context in that issue was helpful.
