### ISSUE TITLE
_.merge looses prototype of source object values

### ISSUE THREAD

**Issue by thabemmz** [lodash/lodash#1946]
On Lodash v4.1.0 / Node 4.2.6 I have the following case:

```
var _ = require('lodash');

function Car() {
  this.color = 'black';
}

Car.prototype = {
  brand: 'ford'
};

var car = new Car();
console.log('Brand:', car.brand); // => Brand: ford

var merged = _.merge({
  bike: 'Bianchi'
}, {
  car: new Car()
});
console.log('Brand:', merged.car.brand); // => undefined
```

It seems like the `prototype` object is lost in the merge. I would expect the prototype of the `car` property of `source` to be merged onto the `object`, especially because the `car` property does not exist in the `object`.

I'd expect that when a top-level property of `source` is `undefined` in `object`, it is assigned directly instead of recursively traversing it.

Sidenote: when replacing `_.merge` with `_.assign`, it does work. Also, when I add `Car.prototype.constructor = Car;` to the prototype, it does work.

**Comment by jdalton** [comment]
Yep. `_.merge` clones sources to ensure they aren't modified. Since your object didn't have its constructor wired up correctly it treated it as a plain object.

**Comment by thabemmz** [comment]
Thanks for the clarification.
