### ISSUE TITLE
Upgrading from 3 to 4: array path for _.pluck does not work with _.map

### ISSUE THREAD

**Issue by mark-rushakoff** [lodash/lodash#1949]
I'm not sure if this is a bug or a documentation issue.

```js
objs = [{foo: {num: 1}}, {foo: {num: 3}}, {foo: {num: 100}}]

_.map(objs, 'foo.num') // as expected
// [1, 3, 100]

_.map(objs, ['foo', 'num']) // surprising
// [false, false, false]
```

In v3, `_.pluck(objs, ['foo', 'num'])` returned (correctly IMO) `[1, 3, 100]`.

However, `_.map(objs, ['foo', 'num'])` *is* behaving consistently with v3.

The [changelog](https://github.com/lodash/lodash/wiki/Changelog) only says

> Removed _.pluck in favor of _.map with iteratee shorthand

which implies that you do not need to change the arguments to pluck.

**Comment by jdalton** [comment]
In v4 the 
> Changed `matchesProperty` shorthand to an array of `[path, srcValue]`

**Comment by mark-rushakoff** [comment]
@jdalton Sorry, I'm having trouble understanding your reply. Can you elaborate?

[The 4.2.1 docs for _.map](https://lodash.com/docs#map) do not mention `matchesProperty`. 

Is the answer that using `_.map` alone requires the dot syntax, and that to use the array syntax you must use something like `_.map(objs, _.property(['foo', 'num']))`?

**Comment by jdalton** [comment]
It's part of the callback shorthand supported by most methods. It's over doing it a bit to copy/paste the same text blurb on it for every method. You get a feel for it the more you use the methods.
