### ISSUE TITLE
Support for insertion sorts

### ISSUE THREAD

**Issue by zvxy** [lodash/lodash#1951]
With lodash we can sort arrays and the like, however when you try to push values using chaining it doesn't behave as expected:

`_([6,5,3,2,1]).sort().push(4).value() // => [ 1, 2, 3, 5, 6, 4 ]`

It would be nice to have an insertion sort function that either replaces the behavior of `.push()` when chained, or a new function like `.insert()`

This would greatly extend the usage of chaining functions together. If you wanted to created a sorted index for a database all you would have to do is:

```
var docs = _(db.docs).orderBy('name');
docs.insert({ name: "Eric" });
```

Here's an example for insertion sort I just made:

```
function insertionSort(array, value, comparator) {
    var head = -1,
        tail = -1,
        length = array.length;

    if (length === 0) {
        array.push(value);
        return 0;
    }

    for (var index = 0; index < length; index++) {
        if (comparator(array[index], value)) {
            head = index;
        } else {
            tail = index;
            break;
        }
    }

    if (head === -1) {
        array.unshift(value);
    } else if (tail === -1) {
        tail = array.push(value) - 1;
    } else {
        array.splice(tail, 0, value);
    }

    // return index of insertion point
    return tail;
}

var array = [ 1, 2, 3, 5, 6 ];

insertionSort(array, 4, function(a, b){
    return a < b;
});

console.log(array); // => [ 1, 2, 3, 4, 5, 6 ]

```

**Comment by jdalton** [comment]
Why not just push the values before sorting?

**Comment by zvxy** [comment]
Well for my specific use case.. I was working on a library that used lodash as a database. The lazy eval makes lodash extremely well suited to this task, the only issue is indexes. If you can't do an insertion sort you can't really maintain an index.

If lodash had an insert function, it'd be as easy as saving `_(docs).orderBy('name')` into a variable. Otherwise, I have to rebuild that index every time a document is inserted.

There's really no way to maintain a sort using lodash. You can only do an initial sort which greatly reduces the usefulness of lodash in this respect.

**Comment by jdalton** [comment]
Ah thanks for explaining @zvxy! As with most requests I close the issue but encourage folks to :+1: if they dig it. This helps me gauge the popularity of a specific feature that may, if popular enough, make its way into core.

**Comment by zvxy** [comment]
Roger that.

Can you point me to where I need to look for how you added the code to creep the LodashWrapper so I can extend it to support this functionality?

**Comment by jdalton** [comment]
Lazy wrapper stuff can be found [here](https://github.com/lodash/lodash/blob/04ceea2bcba35c91f397b6f6a39360157e87f520/lodash.js#L1629-L1676) and [here](https://github.com/lodash/lodash/blob/04ceea2bcba35c91f397b6f6a39360157e87f520/lodash.js#L14402-L14553).

**Comment by zvxy** [comment]
Thanks! I watched your talks before by the way, would love to see you do more on jsperf :) I'll let you know if I get this project working to my standards.

**Comment by polarathene** [comment]
:+1: Writing some layout logic at the moment where I have a sorted array of numbers for column heights and a large array of element heights where I identify the min column height to assign the element and increase that columns height. 

I could just get the min column height val with `_.min()`, but then I need to get the index each time too. Better to have the array sorted and know the min value is always index 0, update the value and do insertion sort to fix the order. Lodash doesn't seem to provide control over sorting algorithm or describe the kind used in the docs(besides that it's stable), from the video's I assume lodash doesn't use the browser defaults [which vary](http://blog.rodneyrehm.de/archives/14-Sorting-Were-Doing-It-Wrong.html).
