### ISSUE TITLE
_.merge behaves differently for undefined values in version 4.2.1 vs. 3.10.1

### ISSUE THREAD

**Issue by eugeneiiim** [lodash/lodash#1956]
The following behaves differently in v4.2.1 vs. v3.10.1:
```
var _ = require('lodash');
var output = {};
_.merge(output, { a: { b: undefined } });
console.log(output);
```

v4.1.2 gives:
```
{ a: { b: undefined } }
```

v3.10.1 gives:
```
{ a: {} }
```

(I don't see any mention of this change in the [changelog](https://github.com/lodash/lodash/wiki/Changelog))

**Comment by jdalton** [comment]
Yep this is by design. Would you edit the changelog to add it to the 4.0.0 breaking changes section?

**Comment by eugeneiiim** [comment]
Will do.

**Comment by eugeneiiim** [comment]
https://github.com/lodash/lodash/wiki/Changelog/7d6efa7eb2171629f07309506af0873f75b0c67e

**Comment by jdalton** [comment]
Thanks!
