### ISSUE TITLE
_.has not working with arrays

### ISSUE THREAD

**Issue by rabbitcore** [lodash/lodash#1959]
`testvariable = {a: 'foo', b: 'foo', c: 'foo'}`

When I use `x = _.has(testvariable, ['a', 'b'])` the result is `false`. If I use `x = _.has(testvariable, 'a') and y = _.has(testvariable, 'b')` both x and y return `true`.

The documentation found on loadash.com indicates that I can use arrays when testing for properties. It therefore seems there is an issue with Lodash.

?

**Comment by jfmengels** [comment]
You can use arrays, but not in the way you expect
`_.has(testvariable, ['a', 'b', 'c'])` is equivalent to `_.has(testvariable, 'a.b.c')`, not to `_.has(testvariable, 'a') && _.has(testvariable, 'b') && _.has(testvariable, 'c')`

**Comment by rabbitcore** [comment]
Ok that explains. So no way to test for several properties without looping through `_.has` x-number-of-properties-to-test-for times I guess ... (?)

**Comment by jfmengels** [comment]
Yeah, you should loop through it. If you feel like it's a useful feature, go ahead and make a proposal for a new function that would do what you were hoping for, and if others are looking for something similar, it may be added in.

**Comment by megawac** [comment]
Related: https://github.com/jashkenas/underscore/issues/2315 https://github.com/lodash/lodash/issues/750

**Comment by rabbitcore** [comment]
thank you @jfmengels and @megawac. 

Well the composition part is definitely better than looping. But using arrays as the second argument to `_.has` definitely is more intuitive and makes the code appear more compact and beautiful. Will consider making a feature request.

**Comment by StreetStrider** [comment]
@rabbitcore, the main reason for supporting arrays as path-like argument is to programmatically construct paths (avoiding concatting string by hand, which is ugly, you can neatly concat arrays instead).
`_.every` / `_.some` solution by jridgewell is good. I believe newly added `_.overSome` & `_.overEvery` can be handy too (btw, naming is crap, I want to note that :D).

**Comment by jdalton** [comment]
@StreetStrider 
>  (btw, naming is crap, I want to note that :D).

Hey now, I bikshedded many days on those : P

@rabbitcore

You should also check out [_.conforms](https://lodash.com/docs#conforms) to create a validation function.
```js
var conforms = _.conforms({
  'a': _.isString,
  'b': _.isNumber,
  'c': _.isObject
});

conforms({ 'a': 'string', 'b': 1, 'c': {} }); 
// => true
conforms({ 'a': 'string', 'c': {} });
// => false
```
