### ISSUE TITLE
How to get rid of iterable methods (question v4)

### ISSUE THREAD

**Issue by razvanz** [lodash/lodash#1960]
Updating from `v3` I noticed that when `_.omit` iterable methods are added to the value:

```
{
  ...
  get: [Function],
  values: [Function],
  keys: [Function],
  forEach: [Function],
  ...
}
``` 

Is there an option to not add those methods, or a method to get rid of them after omitting? My `deepEqual` tests are failing because of that.

Also, why are they enumerable?

**Comment by jdalton** [comment]
Because you are omitting we start with grabbing all enumerable properties (own and inherited) then filter out the ones you want to omit. You can flip it and be explicit using `_.pick` to grab just the properties you want.

**Comment by razvanz** [comment]
I can't use `_.pick` since the other columns are variable. 

I didn't realize that the properties appearing in the object were coming from the constructor's prototype:

```
> 'use strict';
> 
> const lo = require('lodash');
> 
> function Row() {}
> 
> Row.prototype.get = function() {
...   return 'get';
... };
> 
> const row = new Row();
> row['a'] = 1;
> row['b'] = 2;
> 
> console.log(row);
Row { a: 1, b: 2 }
>
> console.log(row.__proto__)
Row { get: [Function] }
>
> console.log(lo.omit(row, 'b'));
{ a: 1, get: [Function] }
```

Is this desired behavior? Shouldn't `_.omit` leave / copy  prototypal properties in the prototype? It seem wrong to me to add them as members since the functionality is not the same.

**Comment by jdalton** [comment]
This is the desired behavior since it's an omit action we give you everything we can except the methods omitted.

**Comment by razvanz** [comment]
But taking the `prototype` props and appending them as members is a **big** difference. 

This could create downsides as:
  - Possibly introducing bugs (prototype is shared between instances while members are not)
  - Performance decrease (rather than having 1 version of a prop, each object will have it's own)

**Comment by jdalton** [comment]
It's been that way for 4 years now. If you have a better implementation feel free to shoot me the gist.

**Comment by razvanz** [comment]
I looked a bit over the code, and I think I would like to propose a `_.omitOwn` and `_.pickOwn` which will not interact with `prototype`. This means the reference will be altered.

Should I prepare a PR when I find some time?

**Comment by jdalton** [comment]
I think `_.omitOwn` and `_.pickOwn` are great mixins but not necessarily a good fit for core.
