### ISSUE TITLE
[4.3.0] Debounce/Throttle inconsistent

### ISSUE THREAD

**Issue by roblav96** [lodash/lodash#1964]
I've noticed that when updating to 4.3.0 my debounce and throttle functions were out of whack.

The first time they are called, they work properly. Any times after that, the function is invoked at the leading **and** trailing. Even if only called once.

I reverted back to 4.2.1 and everything is working properly.

**Comment by jdalton** [comment]
\cc @dcorb

Related to #1952.

**Comment by jdalton** [comment]
@roblav96 What options are your debounced and throttled functions using?

**Comment by roblav96** [comment]
Time 3000, and no options.

**Comment by jdalton** [comment]
Can you provide a failing test or small repro.

**Comment by jdalton** [comment]
(repro could be using http://jsbin.com)

**Comment by roblav96** [comment]
Sure let me try. It's produced on my bosses code so I can't share the exact stuff, but I'll try and make a repro

**Comment by jdalton** [comment]
I can't repro with `_.debounce`:
```js
var d = _.debounce(function() { console.log('hey') }, 32);
var t = _.throttle(function() { console.log('hey') }, 32);
```

Trying 
```js
d();
setTimeout(d, 20);
setTimeout(d, 40);
// => async logs "hey" once
```
then
```js
d();
setTimeout(d, 40);
// => async logs "hey" twice
```

or for `_.throttle`
```js
t();
// => logs "hey"
setTimeout(t, 20);
setTimeout(t, 40);
// => async logs "hey" 2 more times
```
and
```js
t();
// => logs "hey"
setTimeout(t, 40);
// => async logs "hey"
```

**Comment by roblav96** [comment]
I'm using it on a prototype method if that helps.
```javascript
DB.prototype.save = _.debounce( function () {

}, 3000, {
	trailing: true,
	maxWait: 5000
} )
```
I'll try and repro it for you tomorrow. :sleeping:

**Comment by dcorb** [comment]
Sorry for introducing the bug

I have been trying to reproduce it. It's a bug only when maxWait is used.
```
 var d = lo.debounce(function() { console.log('hey') }, 32, {maxWait:40});
  d();
  setTimeout(d,100);  
```
Looks like lastCalled might be overloaded, being used for two different tracking purposes, maybe it's needed a second variable, if we want to keep #1952 . But I can't think straight now. I will look at it tomorrow with fresh eyes

**Comment by jdalton** [comment]
Awesome thank you both! Y'all the real MVPs.

**Comment by dcorb** [comment]
Great!

**Comment by jdalton** [comment]
When a `maxWait` is specified Lodash's debounce and throttle will execute on the leading edge of an invocation even when `leading` is `false`. This is to protect it from tight loops (like a while-true loop) from delaying invocation. If a debounce/throttle is in a tight loop there will already be a `maxDelay` queued (a `maxTimeoutId` set). So we now check for that to avoid accidentally invoking the loop-bust invocation outside a loop.
