### ISSUE TITLE
_.size does not return the actual size if an object has a key "length"

### ISSUE THREAD

**Issue by davidgruebl** [lodash/lodash#1966]
Ran into this unexpected behaviour:

```js
var _ = require('lodash')

var obj = {foo: 1, length: 15}
var size = _.size(obj)

console.log(size) // 15
```

Ist this intended?

**Comment by jdalton** [comment]
Yes because `_.size` is a Collection method which means it prioritizes array-like objects over plain objects. You can use `_.keys(object).length` instead.

**Comment by davidgruebl** [comment]
thanks!
