### ISSUE TITLE
_.delta

### ISSUE THREAD

**Issue by pashasadri** [lodash/lodash#1968]
how about a delta function

`_.delta(arrayA, arrayB, addCallback, delCallback)`

compute additions and deletion between two arrays.

a = [1, 2, 3]
b = [3, 4, 5]

adds = [4, 5]
dels = [1, 2]

example usage: 

Imagine a multiple selection list scenario.  The selection list can change by addition or removal of items.  On each change, you want to add event listeners to newly added items, and remove previously added listeners from the ones no longer in the list.

**Comment by jfmengels** [comment]
Could you elaborate on what `delta` would do, and its use case? I may be missing something, but I have no idea what its supposed to do.

**Comment by megawac** [comment]
I assume he is suggrsting a function merging intersection and difference

**Comment by jdalton** [comment]
I'm pretty sure there are libs that specialize in object and operation diffing / patching.
I'd defer to those instead.

**Comment by pashasadri** [comment]
Thanks for the consideration.  I'll use two invocations of _.difference.
