### ISSUE TITLE
(lodash/fp) findKey predicate receives key instead of object

### ISSUE THREAD

**Issue by mcamac** [lodash/lodash#1971]
```javascript
import {findKey} from 'lodash/fp'
findKey(k => {console.log(k)}, {k1: 'v1', k2: 'v2'}) // logs 'k1', 'k2'
```

In the regular docs the example is
```javascript
var users = {
  'barney':  { 'age': 36, 'active': true },
  'fred':    { 'age': 40, 'active': false },
  'pebbles': { 'age': 1,  'active': true }
};

_.findKey(users, function(o) { return o.age < 40; });
```
where the predicate gets the value.

**Comment by jdalton** [comment]
This is by design. FP methods limit the args provided to iteratees (though it will be fully customizable in the next release). Since this is a "key" method when picking which value to inspect the `key` was seemed appropriate.

In the next release if you'd like to avoid the iteratee caps you'll be able to do something like

```js
var fp = require('lodash/fp/convert')({
  'cap': false
});
```

**Comment by StreetStrider** [comment]
Baad. This totally kills the class of tasks when you need to find key by value. This is not a map-like or filter-like conveyor where you need to pass key in and pass key out, this is where you might want to find key for some specific object. It is like a reverse for picking value by key by simply `obj[key]`.

**Comment by mcamac** [comment]
@StreetStrider  agree.

In addition this is inconsistent with both the docs and also `findIndex` (the same method for arrays), which yields
```javascript
import {findIndex} from 'lodash/fp'
findIndex(k => {console.log(k)}, ['a','b','c']) // logs 'a', 'b', 'c'
```

**Comment by jdalton** [comment]
@mcamac
> In addition this is inconsistent with both the docs and also findIndex (the same method for arrays), which yields

That's an oversight on my part.

@StreetStrider
> Baad. 

It's easy enough to fix. I'll adjust it.

**Comment by mcamac** [comment]
Great, thanks for the quick replies!

**Comment by StreetStrider** [comment]
@jdalton, thanks. I agree that 1-arity functions is a great idea for fp-style libs, but this time it really nullifies wide class of situations where it becomes handy. I remembering Ramda guys even have special `addIndex` function which force other function to pass additional argument «index» to its iteratee. But this is not the ideal too, code becomes verbose very quiclky.

**Comment by jdalton** [comment]
>  I agree that 1-arity functions is a great idea for fp-style libs, but this time it really nullifies wide class of situations where it becomes handy. 

Which is why all of those knobs will be configurable in the next release.

**Comment by jmilkiewicz** [comment]
I know it is already a closed thread, but how to find/pick object by key in lodash/fp.
I see no function in lodash (pickBy, find, findKey )that takes 'key' as parameter to predicate - all take 'value' only. Is convert https://github.com/lodash/lodash/wiki/FP-Guide#convert the only way to get access to keys (both keys and values ) ?

**Comment by jdalton** [comment]
@jmilkiewicz Yes use `.convert`.
