### ISSUE TITLE
full vs. modular npm build

### ISSUE THREAD

**Issue by billyjanitsch** [lodash/lodash#1973]
I noticed that the npm build contains both [the entire lodash build](https://github.com/lodash/lodash/blob/npm/lodash.js) ("main" of [`package.json`](https://github.com/lodash/lodash/blob/npm/package.json)) and the [full set of modules](https://github.com/lodash/lodash/tree/npm).

I'm surprised that `lodash.js` doesn't just export all of the (public) modules -- is this a mistake?

It's atypical for npm packages, and has large implications for bundle sizes. If I depend on some libraries that do:

``` js
const map = require('lodash/map')
const reduce = require('lodash/reduce')
// etc.
```

But my project uses enough Lodash to warrant the convenience of:

``` js
const _ = require('lodash')
```

Then obviously I get all of Lodash in my bundle -- that's fine -- but I'd expect the lib imports to share code with my global import (s/o npm@3 deduping). Instead, my bundle contains (almost) the entire Lodash build twice.

(Sorry if this has been brought up -- couldn't find it in the issue history)

**Comment by jdalton** [comment]
Loading modules 500+ modules has a cost which is multiplied by each different version of Lodash. The monolithic build allows for a single load which can also be used for folks wanting to run it in the browser (it happens from npm). If you're cherry-picking then you're likely doing it for all cases in your bundle. I'm not as worried about deps of deps because collisions there happen all the time so not worth trying to avoid.

**Comment by billyjanitsch** [comment]
> Loading 500+ modules has a cost which is multiplied by each different version of Lodash loaded.

Fair point, I figured this might be a perf concern.

> If you're cherry-picking then you're likely doing it for all cases in your bundle

Suppose that you use enough Lodash that the difference in lib coverage between importing the monolith and cherry-picking is trivial. It makes sense to want the convenience of importing from the monolith:

``` js
import {map, reduce, filter} from 'lodash'
// vs.
import map from 'lodash/map'
import reduce from 'lodash/reduce'
import filter from 'lodash/reduce'
```

But if you're using libraries that cherry-pick ([many](https://github.com/rackt/redux/blob/master/src/createStore.js#L1) [do](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/compose.js#L1)), this convenience currently comes at the cost of duplicating Lodash in your bundle. Should this really force you to cherry-pick yourself to avoid duplication?

Would you consider including another file in the build that just exports all of the public modules, so that projects which consume Lodash-cherry-picking libraries can import from *that* instead of the monolith?

``` js
import {map, reduce, filter} from 'lodash/suite' // hm, naming is hard
// doesn't duplicate when consuming lib code that does:
import map from 'lodash/map'
```

That way, the performant monolith remains the default, but an option exists to handle this case.

**Comment by jdalton** [comment]
> It makes sense to want the convenience of monolith imports:

That's why there's [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash).

**Comment by megawac** [comment]
@jdalton it does es6->es6 transformation by default. As long as you don't use https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs it won't modify imports

**Comment by jdalton** [comment]
@megawac  Oh ya, that's right. Can you add a readme example?

**Comment by megawac** [comment]
I feel like that is more just babel documentation, don't know where it belongs

**Comment by jdalton** [comment]
>  don't know where it belongs

At least an FAQ mention.
