### ISSUE TITLE
Implicit unwrapping of lodash objects

### ISSUE THREAD

**Issue by daniel-pedersen** [lodash/lodash#1975]
When working extensively with lodash, one would sometimes like to pass around lodash wrapped objects as return values. Currently, this is inconvenient as lodash does no implicit unwrapping of the underlying value, forcing one to call .value() before returning.

Since lodash also supports lazy evaluation and shortcut fusion, large performance gains could also potentially be made if unwrapping was done lazily and implicitly.

Is there any good reason for not doing this? [lazy.js](https://github.com/dtao/lazy.js/) does this, for example.

**Comment by jdalton** [comment]
I want to avoid the unwrapping overhead in all methods. The only place that we currently unwrap is for comparing to wrapped values in methods like `_.isEqual`.

That said you could always wrap Lodash's methods
```js
var _ = require('lodash').runInContext();
_.each(_.functions(_), function(methodName) {
  _[methodName] = _.wrap(.....);
});
```
