### ISSUE TITLE
JSDoc @type annotation

### ISSUE THREAD

**Issue by magnushiie** [lodash/lodash#1976]
[JSDoc documentation](http://usejsdoc.org/tags-type.html) indicates that `@type` annotation's contents should be wrapped in curly braces. Lodash's JSDoc `@type` annotations are currently without the braces, e.g. for [`isArray`](https://github.com/lodash/lodash/blob/4.3.0/lodash.js#L9452):

```javascript
/**
     * Checks if `value` is classified as an `Array` object.
     *
     * @static
     * @memberOf _
     * @type Function
...
     */
```

I found this in association to a [TypeScript compiler issue](https://github.com/Microsoft/TypeScript/issues/7002).

**Comment by jdalton** [comment]
I probably based ours off of https://code.google.com/archive/p/jsdoc-toolkit/wikis/TagType.wiki.

**Comment by magnushiie** [comment]
Wow, that was quick, thank you!
