### ISSUE TITLE
_.move(array, fromIndex, toIndex) function

### ISSUE THREAD

**Issue by granteagon** [lodash/lodash#1978]
Here's a function example for moving an item in an array.  I needed it so I wrote it up for others.

```es6
export default function move (array, moveIndex, toIndex) {
  /* #move - Moves an array item from one position in an array to another.

     Note: This is a pure function so a new array will be returned, instead
     of altering the array argument.

    Arguments:
    1. array     (String) : Array in which to move an item.         (required)
    2. moveIndex (Object) : The index of the item to move.          (required)
    3. toIndex   (Object) : The index to move item at moveIndex to. (required)
  */
  let itemRemovedArray = [
    ...array.slice(0, moveIndex),
    ...array.slice(moveIndex + 1, array.length)
  ]
  return [
    ...itemRemovedArray.slice(0, toIndex),
    array[itemRemovedArray],
    ...itemRemovedArray.slice(toIndex, itemRemovedArray.length)
  ]
}

// Examples
// --------

move(['a', 'b','c'], 2, 0)

// -> ['c', 'a', 'b']



move([{name: 'Fred', name: 'Barney', name: 'Wilma', name: 'Betty'}], 2, 1)

// -> [{name: 'Fred', name: 'Wilman', name: 'Barney', name: 'Betty'}]
```

I hope these submissions aren't annoying, John-David.  I do notice you keep the issues very clean.  If you'd rather I not submit them, let me know.

**Comment by jdalton** [comment]
> I hope these submissions aren't annoying, John-David. 

No way, keep them coming! MOAR I SAY!

> I do notice you keep the issues very clean. If you'd rather I not submit them, let me know.

I tend to close out non-actionable issues. API requests tend to be closed out rather quickly since new API  suggestions take some time to get traction. The process so far is folks will search for a similar issue and then :+1: features they'd like to see added. Once there's enough demand we add the method to core.

Dup of #1701.

**Comment by dropfen** [comment]
Hello @granteagon 

the function seams to have a bug:

```
move([0,1,2,3,4,5,6,7], 3, 5)
// => [0, 1, 2, 4, 5, undefined, 6, 7]

```
heres the fix
```
...itemRemovedArray.slice(0, toIndex),
array[itemRemovedArray], // change to ->  array[moveIndex],
...itemRemovedArray.slice(toIndex, itemRemovedArray.length)
```
Anyway, thanks for this ;)

**Comment by granteagon** [comment]
Thanks for the heads up @dropfen.  I'll write some tests sometime soon and post them here.

**Comment by piascikj** [comment]
:+1:  Really like to see this one soon!  Good work

**Comment by granteagon** [comment]
@piascikj pretty handy for things like drag and drop.

**Comment by dropfen** [comment]
@granteagon could you fix the bug in your code, because copy pasting does not work ;)

**Comment by jdalton** [comment]
Let's keep this thread focused on the feature and not the throw out implementation code.

**Comment by piascikj** [comment]
yeah, exactly what I'm planning on using it for

On Mon, Jun 13, 2016 at 7:59 AM, Grant Eagon <notifications@github.com>
wrote:

> @piascikj <https://github.com/piascikj> pretty handy for things like drag
> and drop.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lodash/lodash/issues/1978#issuecomment-225573475>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAOQIbNBWuKfk-dHYs4159eAYebQzQ_oks5qLVQ5gaJpZM4HXkRj>
> .
>



-- 
*Jesse Pia**ś**cik*
Founder @imdoneIO <https://twitter.com/imdoneIO> | imdone.io
about.me/jesse.piascik

**Comment by dropfen** [comment]
@jdalton I just realized, that it could be made a bit better in terms of performance, without creation of a new array and reaction of it.. It was inspired by this thread, but with some performance benefits in mind.

1. No need to create a separate `itemRemovedArray`
2. No need to do slicing at all if from and to are equal, just return the array

```
/**
 * move an item 'from' position 'to' position,
 * without moving if the position is the same
 *
 * array (Array)
 * from  (Int) old item position
 * to    (Int) new item position
 */
export default function move(array, from, to) {
  let item = array[from];
  let length = array.length;
  let diff = from - to;

  if (diff > 0) {
    // move left
    return [
      ...array.slice(0, to),
      item,
      ...array.slice(to, from),
      ...array.slice(from + 1, length)
    ];
  } else if (diff < 0) {
    // move right
    return [
      ...array.slice(0, from),
      ...array.slice(from + 1, to + 1),
      item,
      ...array.slice(to + 1, length)
    ];
  } else {
    // Dont move if from == to
    return array;
  }
}
```

**Comment by jdalton** [comment]
Future discussion should be at #1701.
