### ISSUE TITLE
_.get from lodash/fp doesn’t use defaultValue

### ISSUE THREAD

**Issue by andrewbranch** [lodash/lodash#1980]
I imagine this is because of the automatic transformation from the non-FP version to the FP version, so maybe it is intentional, but my expectation was that `get` from lodash/fp, when invoked with 3 arguments, would be equivalent to the normal `_.get`. Instead, the 3rd argument seems to be ignored, returning `undefined` instead of using the provided defaultValue.

Is this a bug or a known/intentional limitation?

```js
import normalGet from 'lodash/get';
import { get as functionalGet } from 'lodash/fp';

normalGet({ a: 'b' }, 'c', 'default');     // "default"
functionalGet({ a: 'b' }, 'c', 'default'); // undefined

**Comment by jfmengels** [comment]
Hi @andrewbranch. This is indeed intentional, and you will se this for other methods. This will be configurable though probably in the next release.

**Comment by andrewbranch** [comment]
Ok, thanks! Feel free to close.

**Comment by jdalton** [comment]
@andrewbranch You can use
```js
import getOr from 'lodash/fp';
```
or
```js
import getOr from 'lodash/fp/getOr';
```

**Comment by jotaen** [comment]
@jdalton correction of the JS imports:

```JS
import {getOr} from 'lodash/fp'; // note the curly braces for deconstructing
import getOr from 'lodash/fp/getOr';
```

and just for the records, the signature is:

```JS
getOr(defaultValue, path, object)
```
