### ISSUE TITLE
Unexpected behaviour of _.curryRight

### ISSUE THREAD

**Issue by channikhabra** [lodash/lodash#1981]
If I curry a function which takes 2 arguments, e.g `_.curryRight(func(a, b))`, then create a partial function `funcP` with second argument (i.e expected first argument of new function), then when I call `funcP` again with 2 arguments, it assume those 2 be the original arguments and discard the earlier partial call (for example when using `funcP` in _.map). Expected behaviour is that it would discard extra arguments after it has received `function.length` arguments.

http://jsbin.com/qisohotafa/edit?js,console

Or Is it the expected behaviour of curry in lodash?

**Comment by jdalton** [comment]
See https://github.com/lodash/lodash/issues/1896.
