### ISSUE TITLE
lodash core's _.has() doesn't work with nested properties

### ISSUE THREAD

**Issue by GhanPatel** [lodash/lodash#1982]
From what I observe in lodash core 4.3.0, _.has(object, "prop1.another.prop") doesn't work. I can load the regular copy of has() via 'lodash/has', and that seems to work properly. Anyone else see this?

**Comment by jdalton** [comment]
It works for me.

**Comment by demoneaux** [comment]
If you're referring to the lodash core build, the deep property support doesn't work currently as the code build has a smaller API subset.

**Comment by jdalton** [comment]
Ah, I didn't even catch the "core" mention. Thanks @demoneaux!

**Comment by GhanPatel** [comment]
Any thoughts to add the full functionality in core? I think that deep property support is the strongest aspect of _.has(), otherwise I don't see a need to use _.has(). 

Or, at the very least, document that lodash/core's _.has() functions differently than normal.

**Comment by GhanPatel** [comment]
Also, are there any other methods in core that function differently than normal?

**Comment by jdalton** [comment]
> Any thoughts to add the deep property functionality in core? I think that's is the strongest aspect of _.has(), otherwise I don't see a need to use _.has().

The idea for core is that it's basic and small. Adding features eat away at both those areas.

> Or, at the very least, document that lodash/core's _.has() functions differently than normal.

Are you up for editing the [build differences wiki](https://github.com/lodash/lodash/wiki/Build-Differences)?

* Lazy evaluation is removed
* Placeholder support is removed
* Support for cloning complex values is removed
* Support for deep property paths is removed
* Support for maps, sets, & typed arrays is removed
* The iteratee `_.matchesProperty` shorthand is removed

**Comment by GhanPatel** [comment]
Ok updated the wiki. Thanks for the info!

**Comment by jdalton** [comment]
:rocket:!

**Comment by jaydge** [comment]
This took me a while to figure out. Until I compared the full vs the core I didn't know why _.has was not working to spec for deep paths. 

It would be nice if you called out a link to the build differences wiki on the Core build and download pages.
