### ISSUE TITLE
Undocumented incompatibility from v3 to v4

### ISSUE THREAD

**Issue by mattjdev** [lodash/lodash#1983]
In Lodash v3, we were using the following functionality (as described [here](https://github.com/lodash/lodash/blob/3.10.1/doc/README.md#example-35))
```javascript
_.zipObject(['key1', 'value1'],['key2', 'value2'])

// resulting in:
{
  key1: 'value1',
  key2: 'value2'
}
```
but that is incompatible with Lodash v4. It should be `_.fromPairs`:
```javascript
_.fromPairs(['key1', 'value1'],['key2', 'value2'])
```

Please add this incompatibility to the wiki. Thanks!

**Comment by jdalton** [comment]
It'd be great if --you-- added it to the wiki.

**Comment by jdalton** [comment]
@mattjdev Thank you for taking the time to edit it :beer:
