### ISSUE TITLE
cloneDeep performance

### ISSUE THREAD

**Issue by elado** [lodash/lodash#1984]
Compared to https://github.com/jonschlinkert/clone-deep or a simple `JSON.parse(JSON.stringify(o))`, `_.cloneDeep` is extremely slow. While `JSON` isn't always a good fit (e.g. when copying a function) jonschlinkert's implementation is still 6.5x faster.

```
"lodash.cloneDeep x 2,056 ops/sec ±4.06% (54 runs sampled)"
"jonschlinkert/clone-deep x 13,117 ops/sec ±1.17% (62 runs sampled)"
"json x 18,926 ops/sec ±2.01% (61 runs sampled)"
```

http://jsbin.com/nojiha/edit?js,console,output

Is there anything `_.cloneDeep` is doing that the other implementation doesn't?

**Comment by jdalton** [comment]
Hi @elado!

Our deep clone perf compared to `JSON` will be slower. Ours tackles array buffers, buffers, dates, maps, nulls, regexes, sets, symbols, typed arrays, boolean/number/string objects, and circular references. If you know the data you're going to clone is `JSON` compatible then go for it. However, knowing if your data is `JSON` compatibile isn't always straight forward (See [npm/pull/11306](https://github.com/npm/npm/pull/11306#issuecomment-178071900))

**Comment by elado** [comment]
Thanks @jdalton 

Might be worth writing about it in the docs that `_.cloneDeep` takes care of many cases and therefore it's a slow process, and should be used wisely.

I used it in several place in my app (inside a loop) and realized it was the bottleneck. I can switch to JSON in my case.

**Comment by jdalton** [comment]
Naw, I'm not going to document that.

**Comment by mateodelnorte** [comment]
Anecdote - A perf comment would have been useful for me. Just got to the bottom of a migration issue that only showed itself in production, where _.cloneDeep is eating up far more time than expected when cloning nested ES2015 Maps.

**Comment by albertbuchard** [comment]
Hi,

Just to let you know that cloning Meshes in babylonJS is exponentially slower at each clone : 

var tilesArray = [];
for (var i = 0; i < taskObject.assets.tiles.length; i++) {
  var tile = _.cloneDeep(taskObject.assets.tiles[i]);
  tile._scene = scene;
  scene.addMesh(tile);
  tilesArray.push(tile);
}

Around the 8th clone I am above the minute...

**Comment by jdalton** [comment]
@albertbuchard It sounds like you should use a more specialized solution.

**Comment by runvnc** [comment]
I think you should call out performance explicitly while at the same time mentioning that other cloning modules may not handle all of the cases you do.

cloneDeep performance issues have become the biggest slowdown in my current application so I will have to find another module.  The reason I had used this clone rather than other modules, and also had not considered it was giving a problem was because of the reputation of lodash.

**Comment by jdalton** [comment]
I've come to the point with Lodash (Billions or downloads, 3x more dependants than any other package, more users than almost all SPA frameworks) that the threat of leaving for lesser packages does little. Use the tool that's best for your situation. If a generic recursive deep clone doesn't fit your needs then by all means go somewhere else.
