### ISSUE TITLE
Using _.invert() on Maps?

### ISSUE THREAD

**Issue by pillowfication** [lodash/lodash#1985]
Is there something like

```javascript
function invertObjOrMap(thing) {
  if (_.isMap(thing)) {
    var inversion = new Map();
    thing.forEach(function(val, key) {
      inversion.set(val, key);
    });
    return inversion;
  }

  return _.invert(thing);
}
```

So that I may also invert my Maps?

```javascript
var map1 = new Map([[true, 1], ['foo', 1]]);
// Map { true => 1, 'foo' => 1 }

var map2 = invertObjOrMap(map1);
// Map { 1 => 'foo' }
```

**Comment by jdalton** [comment]
There isn't but I'll take this as the request. We'll keep an eye on demand for the feature.

 What use case do you have?

**Comment by pillowfication** [comment]
We're doing some bidirectional mapping. We'd like to define a single Map for one direction, then use its inversion for the other direction. The Map we are using requires some non-string keys and values so that using a plain Object with `_.invert()` won't work.

Basic example (although this can be solved with an Object instead of Map):

```javascript
var ColorToHex = new Map([
  ['red', 0xFF0000],
  ['green', 0x00FF00],
  ['blue', 0x0000FF]
]);
var HexToColor = _.invert(ColorToHex);

ColorToHex.get('red');    // 0xFF0000;
HexToColor.get(0xFF0000); // 'red'
```

**Comment by jdalton** [comment]
Rad. I'll seriously consider it. We'd get it for free if we treat maps/sets as a collection.

**Comment by fisher-** [comment]
I have the same issue as @pillowfication, I will try to prepare PR.

**Comment by jdalton** [comment]
Hi @fisher!

Hold off on a PR until there's a bit more demand.

**Comment by fisher** [comment]
Ok, nevermind.

**Comment by lubeskih** [comment]
Sorry for pinging on such an old issue. What happened with this one? Is there a chance it can get into lodash? It is useful.

**Comment by jdalton** [comment]
Hi @lubeskih!

There's low user interest at the moment.

**Comment by canibanoglu** [comment]
Interestingly enough, I was brimming with hope that this was implemented. What would it take to get this done? With some pointing in the right direction I'd be more than happy to send in a PR

**Comment by jgreen210** [comment]
There would be various possibilities for handling collisions. E.g. overwriting earlier keys/values, throwing an exception, or avoiding them (using Object not Map syntax here for simplicity):

```
{ 'a': [1, 2], 'b': [2, 3] } -> { 1: ['a'], 2: ['a', 'b'], 3: ['b'] }
```

I guess all could be useful in general.
