### ISSUE TITLE
Deprecation warnings are noisy

### ISSUE THREAD

**Issue by remko** [lodash/lodash#1992]
I have some projects that depend (either directly or indirectly) on lodash 2. The deprecation warning that was recently introduced is generating noise in `npm install` that may be hiding more important issues. In the indirect case, I can't take action on this deprecation, and in the direct case, taking action on it is very costly and risky (since it involves upgrading old code to accommodate for breaking API changes, with no net win).

I'm not sure if this how important it is to tell people about deprecation of lodash; if there was a bug in it, I would probably have noticed by now, and I'm not very worried about security issues. I would have thought `npm deprecate` is more intended for the case of critical problems with specific releases (in which case you really *do* want to upgrade).

Any thoughts on this, or workarounds to not have to change code and not get deprecation warnings?

thanks!

**Comment by jdalton** [comment]
It is what it is. I'd encourage you to ping the author of your deps to upgrade or find other deps.
