### ISSUE TITLE
camelCase().capitalize() chain behaviour is different then 3.x

### ISSUE THREAD

**Issue by radical-edo** [lodash/lodash#1995]
Hi,

in version `3.10.1` (and previous ones as far as I know) the following chain:

```js
_.chain('john_doe').camelCase().capitalize().value()
```
gave as a result `JohnDoe`. In version `4.3.0` the result is `Johndoe`. If you switch the chain it will be `johnDoe`. Basically the last function applied gives the result. Not sure if it's deliberate or not... Please let me know. And if possible, return the old behaviour?... :smile:

**Comment by jdalton** [comment]
The behavior of capitalize [changed](https://github.com/lodash/lodash/wiki/Changelog#v400)
> Made `_.capitalize` uppercase the first character & lowercase the rest

You can use [_.upperFirst](https://lodash.com/docs#upperFirst).
