### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by zrosenbauer** [lodash/lodash#1996]
https://lodash.com/docs seems to be down......

``
curl: (7) Failed to connect to lodash.com port 443: Connection refused
``

``
http: error: ConnectionError: ('Connection aborted.', error(61, 'Connection refused'))
``

**Comment by jdalton** [comment]
Yep, looking into it.

**Comment by jdalton** [comment]
Until its up you can use http://devdocs.io/lodash~4/.

**Comment by jdalton** [comment]
\cc @mathiasbynens

**Comment by mathiasbynens** [comment]
Works for me.

**Comment by jdalton** [comment]
Works for me too. @mathiasbynens gets all the +1's.
