### ISSUE TITLE
Errors after upgrade

### ISSUE THREAD

**Issue by jmcollin78** [lodash/lodash#1997]
Hello,

After upgrading lodash from 3.5.0 to 4.3.0 some functions I used desapears : _.pluck, _.contains for example. 
I don't find any portability guides in documentation to help me in my upgrade process.

Can someone help me to get this methods back ?

JM.

**Comment by jmcollin78** [comment]
OK. I just find the changelog here: https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings
Maybe you should reference this page in the README.md to make it more easy to find.

**Comment by jdalton** [comment]
Added https://github.com/lodash/lodash/commit/a9e8c0ba760ef10781e5ad0e21da8f6aee6ab4cb.
