### ISSUE TITLE
isMatch does not work as expected.

### ISSUE THREAD

**Issue by EugeneBichel** [lodash/lodash#1999]
1. case:
var object = { 'user': 'fred', 'age': 40 };
 _.isMatch(object, { 'age': 40 });
 // => true

2. case:
var object = { 'user': 'fred', 'age': 40 };
 _.isMatch({ 'age': 40 }, object);
 // => **false**
But the expected result is **true**

Can someone take a look at this?

**Comment by kafeltz** [comment]
It seems to be param order dependent. I'm not sure if it's intended.
```
_.isMatch({ 'user': 'fred', 'age': 40 }, { 'user': 'fred', 'age': 40 })
_.isMatch({ 'age': 40 }, { 'user': 'fred', 'age': 40 })
```

**Comment by EugeneBichel** [comment]
So, if we have isMatch(object, source), then isMatch checks that  source is a part of object. But it does not mean that the object is a part of source.

**Comment by kafeltz** [comment]
Maybe the name method is misguiding. It could be something like: Contains, isContained.

**Comment by jdalton** [comment]
See the [_.isMatch](https://lodash.com/docs#isMatch) docs.
> Performs a deep comparison between `object` and `source` to determine if `object` contains equivalent property values. 

By flipping the order to `_.isMatch({ 'age': 40 }, object)` you're performing a check if `{ 'age': 40 }` contains the props `user: 'fred'` and `age:40` which it fails.
