### ISSUE TITLE
_.valuesIn({...}) is returning an empty array

### ISSUE THREAD

**Issue by abbotto** [lodash/lodash#2000]
**Lodash v4.3.0**

`_.valuesIn({ x: 'y' }) === Array []`

**Tested against the following browsers on OS X (El Capitan):**
- Firefox 43.0.4
- Chrome 48.0.2564.109
- Safari 9.1

The function works as expected in **Lodash v3.10.0**.

**Comment by jdalton** [comment]
Wow all of our covered missed that. Bananas. Expect a release in a day or so.

**Comment by abbotto** [comment]
Thanks.
