### ISSUE TITLE
support to transform arguments into a key value pair

### ISSUE THREAD

**Issue by tusharmath** [lodash/lodash#2004]
Hi,

Does it makes sense to have a function — `targs` that transforms an argument object to a key value pair?

```javascript

const targs = function () {
  const toArr = x => [].slice.call(x)
  const keys = toArr(arguments)
  return function () {
    const out = {}
    const values = toArr(arguments)
    values.forEach((x, i) => out[keys[i]] = x)
    return out
  }
}

```

*PURPOSE*

Though the example is specific to RxJS but I think it can be applied at a lot of other places —

```javascript
const resize = Rx.Observable.fromEvent(window, 'resize')
const scroll = Rx.Observable.fromEvent(window, 'scroll')

// original
Rx.Observable.combineLatest(resize, scroll, (resize, scroll) => ({resize, scroll}))

// vs
Rx.Observable.combineLatest(resize, scroll, targs('resize', 'scroll'))
```

**Comment by jdalton** [comment]
Hey @tusharmath!

This seems a little too specialized. That said there's [_.overArgs](https://lodash.com/docs#overArgs) which you can use to transform arguments.

**Comment by tusharmath** [comment]
Thanks for responding @jdalton!
I would really appreciate if you could explain what "too specialized" means here, so that I don't make such silly requests in future. Thanks.

**Comment by jdalton** [comment]
It means I think its use case is too narrow for a general utility library. That said don't be shy about making suggestions. If there's enough user demand it'll get into core.

**Comment by tusharmath** [comment]
Cool! I have put some more examples and would keep posting as an when I get new ones.

For other people who are looking for the same thing I have created a package [argtoob](https://www.npmjs.com/package/argtoob) which is short for *arguments to object*. 

@jdalton Hope you wouldn't mind me putting a link of an alternative that one could use if he needs this function. 

Thanks!

**Comment by jdalton** [comment]
> Hope you wouldn't mind me putting a link of an alternative that one could use if he needs this kind of functionality.

Nope, go for it :)
