### ISSUE TITLE
True array ordering

### ISSUE THREAD

**Issue by ChrisJefferson** [lodash/lodash#2005]
I am always surprised in Javascript that `[-1] < [-2]` is true. I would like a method, which did ordering of ints, arrays, lists (and objects?) in a more sensible way.

Then (wanting everything), it would be nice to have `_.sortWith`, to use this new comparator.

**Comment by jdalton** [comment]
Hi @ChrisJefferson!

The `Array#sort` method has a comparator param. Have you tried that?

**Comment by ChrisJefferson** [comment]
Hi. It does have a comparator argument (didn't notice that, sorry)

I would like a comparator such that: 1 < 2 < 11 < 22, and similarly [1] < [2] < [11] < [22] (and also sort longer arrays, and arrays of arrays).

This seems like the sensible way of wanting to order things, but does not seem to exist in lodash? ( `_.lt([2],[11])` returns false)

**Comment by jdalton** [comment]
@ChrisJefferson 
You should check out our [gitter chat](https://gitter.im/lodash/lodash).
There's lots of folks there to help.
