### ISSUE TITLE
Throw an error when _.uniq is called with a superfluous argument

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#2006]
I have just spent the last few hours tracing back how did suddenly our database got polluted with duplicate records.

It turns out that between v3 and v4 `_.uniq` was separated to `_.uniq`, `_.uniqBy` and `_.uniqWith`. Our codebase was using `_.uniq(data, 'id')`. The extra argument was neither throwing an error nor supporting the legacy feature.

This looks like something thats easy to overlook. What about throwing an error if function is called with a superfluous argument?

**Comment by jdalton** [comment]
We've tried to reduce or limit throwing. For migration helpers see [lodash-migrate](https://www.npmjs.com/package/lodash-migrate).

**Comment by captbaritone** [comment]
@gajus, this might be a good candidate for a linting rule. I've proposed one here: https://github.com/wix/eslint-plugin-lodash/issues/26

**Comment by gajus** [comment]
@captbaritone Sounds good.

**Comment by jdalton** [comment]
@captbaritone That's a really useful linting plugin. I'll add it to the `lodash-migrat`e mention in our changelog and its readme.

**Comment by captbaritone** [comment]
@gajus looks like @ganimomer has implemented a generic rule that warns you if your arguments exceed the arity of a function (given your version of Lodash).
