### ISSUE TITLE
FP-style functions don't accept non-functions as iteratees (Error: func is not a function). Regression?

### ISSUE THREAD

**Issue by lolmaus** [lodash/lodash#2007]
```js
const arr = [{score: 1}, {score: 2}];

// This works:
_.map(arr, 'score'); // => [1, 2]

// This doesn't:
_mapFP('score')(arr); // => Error: func is not a function

// Works, but is ugly:
_mapFP(item => item.score)(arr); // => [1, 2]
```

This is a huge regression for me. Using strings/objects for iteratees has been one of the most important lodash features for me.

Now I'm trying to import lodash methods individually in order to minimize distro size. That forces me to replace chaining with `flow`, and `flow` needs FP-style lodash functions.

Compared to chaining, `flow` is a huge hit on readability by itself, and the inability to use objects/strings for iteratees makes it even worse! :sob:  The longer the `flow` chain, the harder it is to read all those callbacks.

Please let FP-style lodash functions accept non-functions as iteratees. If this is planned, please add it to the [roadmap](https://github.com/lodash/lodash/wiki/Roadmap), mentioning the target version number.

:bow:

**Comment by lolmaus** [comment]
You rock!

When this will be on npmjs.org?

**Comment by jdalton** [comment]
We just released a few hours ago. So it'll be this evening or the next morning.
