### ISSUE TITLE
When merging modified primitive type objects, added properties get dropped

### ISSUE THREAD

**Issue by mattjdev** [lodash/lodash#2008]
Bug when using v4.4.0
We use a pattern where we add properties to a string object. When we try to merge that string property into another object, all the properties originally added are dropped.
I'm not sure if this is specifically an issue with merge, or if other functions are affected.

```javascript
> var testStr = new String('testStr');
> testStr.prop1 = 'testStr.prop1'
> testStr
{ [String: 'testStr'] prop1: 'testStr.prop1' }

// It seems to work 1 level deep.
> _.merge({}, { testStr: testStr })
{ testStr: { [String: 'testStr'] prop1: 'testStr.prop1' } }

// but any deeper and it doesn't work as expected.
> _.merge({}, { testStr: { testStr: testStr } })
{ testStr: { testStr: [String: 'testStr'] } }
```

**Comment by jdalton** [comment]
This is a lodash wide behavior. When cloning or comparing boolean, number, & string objects any added properties are ignored. The use of those is so rare that I could see putting them down the plain object path.

**Comment by mattjdev** [comment]
This behavior seemed to change from 4.3 to 4.4, why might that have changed between minor versions?

**Comment by jdalton** [comment]
Our clone/equality behavior did not change between 4.3 and 4.4. We did fix an issue where we weren't cloning a value properly which may be what you're seeing. Lodash has never supported expando properties on the object form of primitives.

**Comment by jdalton** [comment]
I'll add support for it though. It'll slow those paths down but they aren't used nearly as often as arrays and plain objects so it's cool.
