### ISSUE TITLE
_.partial treats string partials as arrays of characters

### ISSUE THREAD

**Issue by stephenlam** [lodash/lodash#2009]
The docs for _.partial include this example:

```
var greet = function(greeting, name) {
  return greeting + ' ' + name;
};

var sayHelloTo = _.partial(greet, 'hello');
sayHelloTo('fred');
// → 'hello fred'
```

However, when I run this, I find the result is "h e" instead of "hello fred". This is because the first character in 'hello' gets assigned to greeting, and the second character 'e' gets assigned to name.

**Comment by jdalton** [comment]
I can't repro. I get "hello fred".

**Comment by stephenlam** [comment]
See this JSBin that is running on the latest 4.5.0 release. http://jsbin.com/jiwojogile/edit?html,js,console,output

It does not happen on vanilla lodash. It only happens when I include lodash.fp.js.

**Comment by jdalton** [comment]
Usage for fp is `_.partial(greet, ['hello']);` where the secon param is an array of arguments.

**Comment by stephenlam** [comment]
Great, that works for me. Is this documented anywhere?

**Comment by jdalton** [comment]
> Great, that works for me. Is this documented anywhere?

I need to add it to the [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide)
