### ISSUE TITLE
fp mapKeys iteratee signature change

### ISSUE THREAD

**Issue by billyjanitsch** [lodash/lodash#2012]
There's a difference in behavior that doesn't seem to be reflected in the Changelog; looks to have been introduced in 784ee6a086742d606985f6e5259488b109cccc3e:

``` js
mapKeys(x => x + 'Thing', {a: 'test', b: 'test'})
// in 4.3 => {aThing: 1, bThing: 2}
// in 4.5 => {testThing: 'test'}
```

I'm guessing this is unintentional? I know FP caps iteratee args, but I'd expect to get the key rather than the value, e.g. for cases like:

``` js
const camelKeys = mapKeys(camelCase)
```

**Comment by jdalton** [comment]
This is intentional. See #1971.

**Comment by billyjanitsch** [comment]
#1971 addresses `findKey`, which I agree should receive the value rather than the key (being an analog of `findIndex`). But why should `mapKeys` receive the value?

**Comment by jdalton** [comment]
I'll kick it around.

**Comment by jdalton** [comment]
Would the exception be only for `mapKeys` ?

**Comment by jdalton** [comment]
Can you think of any other method?

**Comment by billyjanitsch** [comment]
`mapKeys` is the only `xKeys` method, so I don't think it's too strange for it to be an exception.

Maybe `pickBy`/`omitBy`? But based on #1765 I'm guessing that you disagree.

**Comment by jdalton** [comment]
> pickBy/omitBy

They are uncapped (accept 2 arguments).

**Comment by jdalton** [comment]
Feedback requested from @mcamac  and @StreetStrider.

**Comment by billyjanitsch** [comment]
> They are uncapped (accept 2 arguments).

Not in FP:

``` js
pickBy((x, y) => {console.log(x, y)}, {a: 1, b: 2})
// => 1 undefined
// => 2 undefined
```

**Comment by jdalton** [comment]
Hmm that would be a bug then as their cap isn't specified. It should default to uncapped.

**Comment by mcamac** [comment]
I support this exception for mapKeys - in this particular case the original function is mapping keys to keys, which wasn't the case for findKey (val -> key).

**Comment by StreetStrider** [comment]
In my practice `pickBy`/`omitBy` (`pick`/`omit`) logic is always based on key to satisfy some criterias. If one want to work with values this is more a filter-like task.

**Comment by jdalton** [comment]
@StreetStrider I should have clarified (we're all on the same page with `pickBy` and `omitBy`). My feedback request was for the `mapKeys` change request to make it provide the `key` instead of `value`.

**Comment by StreetStrider** [comment]
@jdalton, I'm not remembering myself using `mapKeys` at all, but I admit that many people can use it both in `key` → `key` and `value` → `key` scenario. For key it is important two things: 1. it's uniq, 2. it can be used to access value. I don't care my keys looks like `a` or `a-1`, so I don't map my keys. If keys becomes data-holders I can `invert` my object and throw full power of LoDash on it.

**Comment by jdalton** [comment]
The `mapKeys` rearg issue is patched https://github.com/lodash/lodash/commit/23768398c505bfd83b5bc18138b5ed8be114e0a8
The `pickBy` and `omitBy` issue is patched https://github.com/lodash/lodash/commit/48dbf203a57330fc65586c861ceec7f12188853f
