### ISSUE TITLE
_.keyBy behaves very strange with invalid arguments

### ISSUE THREAD

**Issue by mik01aj** [lodash/lodash#2014]
![screenshot 2016-02-18 12 28 15](https://cloud.githubusercontent.com/assets/3027415/13142093/33a0392c-d63b-11e5-84c7-24b4c5956a65.png)

Shouldn't this throw an error?

**Comment by jdalton** [comment]
In this case you're hitting the "_.matches" shorthand so the predicate produced for an empty object matches everything which cases every generated key for the string (indexes 0-3) to be `true`.

**Comment by mik01aj** [comment]
Why not throw an error when the first argument is a string?

**Comment by jdalton** [comment]
In modern environments string are iterable.
