### ISSUE TITLE
_.sortBy

### ISSUE THREAD

**Issue by przemyslawpluta** [lodash/lodash#2015]
Based on `lodash 4.5.0` I'm sorting array of objects ascending by `won` and `votes`

``` js
[
    {
      "abbr": "A",
      "won": 1,
      "votes": 0
    },
    {
      "abbr": "B",
      "won": 0,
      "votes": 0
    },
    {
      "abbr": "C",
      "won": 0,
      "votes": 0
    },
    {
      "abbr": "D",
      "won": 0,
      "votes": 0
    },
    {
      "abbr": "E",
      "won": 0,
      "votes": 0
    }
  ]
```

using `_.sortBy(data, ['won', 'votes']).reverse()` which produces `A, E, D, C, B` order? My assumption would be that the order should be `A, B, C, D, E` as the rest of the values for `won` and `votes` are at `0` so there is no change there overall?

Thanks.

**Comment by przemyslawpluta** [comment]
I assume I should be using `_.orderBy` instead? e.g. `_.orderBy(data, ['won', 'votes'], ['desc', 'desc'])`

**Comment by jdalton** [comment]
Yep.

Using `_.sortBy` your results were:
```js
[{"abbr":"B","won":0,"votes":0},{"abbr":"C","won":0,"votes":0},{"abbr":"D","won":0,"votes":0},{"abbr":"E","won":0,"votes":0},{"abbr":"A","won":1,"votes":0}]
```
So when you reversed it you got `A, E, D, C, B`.

**Comment by przemyslawpluta** [comment]
@jdalton Thanks
