### ISSUE TITLE
Add _.none

### ISSUE THREAD

**Issue by megawac** [lodash/lodash#2016]
Worth considering this again?

Reason I want it, had some logic similar to

```js
var fn;
if (condition) {
  fn = _.every;
} else if (condition2) {
   fn = _.any;
} else {
   fn = (arr, fn) => !_.any(arr, fn);
}
```

`_.none` can also be a useful function for `fp` cases where it would otherwise be written `fp.negate(fp.any))`.

Ref to previous discussion: https://github.com/jashkenas/underscore/issues/2118
Ref2: https://github.com/ramda/ramda/pull/881

Anyway, as mentioned in the referenced issue the implementation is straightforward and it has clear use cases.

**Comment by jdalton** [comment]
I'm surprised this hasn't been brought up yet on our tracker. It's a good request.

**Comment by jdalton** [comment]
As with other requests we'll wait for demand to pick up. But we'll keep an eye on it. Thanks for bringing this to our tracker.

**Comment by graingert** [comment]
@jdalton out of interest what's the threshold for popular enough?

**Comment by jdalton** [comment]
There isn't one. Votes are a measure of interest and an indicator of popularity.

**Comment by pranaygp** [comment]
@jdalton, I had the same question @graingert has about the "threshold" for something being popular.

If there isn't one, I'm curious as to how and when an issue is deemed worthy to be considered. (I'm assuming you have some tool that just looks at all issues on github with the 'votes needed' tag, and sorts them by 👍 reactions)

Also, (and this has probably been asked before), but why the system of closing issues till they receive enough votes. People are a lot less likely to find these issues (and then vote on them). I feel like it'd make more sense to leave them all open while they garner votes, and just close the issues that haven't gained enough votes after a long period of time and have become stale.

**Comment by jdalton** [comment]
If I left them open there would be hundreds of open issues with no intent of closing them. This way I can measure interest in features when I want to add some.

**Comment by vjsingh** [comment]
Seems like this one has quite a few 👍 ? What's the threshold to make it in?

**Comment by jobjen02** [comment]
Are there plans to sill add this? Or why is this issue closed?

**Comment by risalfajar** [comment]
Commenting eight years later...

I'm coming from Kotlin, and is a bit surprised that JS doesn't have `none()`, Lodash should do this.
