### ISSUE TITLE
Unnecessary copy in fp/set?

### ISSUE THREAD

**Issue by jbalboni** [lodash/lodash#2017]
I was trying out the set function and was surprised by some behavior. It looks like unchanged objects are copied:

```
var set = require('lodash/fp/set');
var test = { firstObj: { prop: 1 }, secondObj: { otherProp: 1 } };
var test2 = set(['firstObj', 'prop'], 3, test);
console.log(test.secondObj === test2.secondObj); //this prints false
```

If fp/set is meant to treat data as immutable, there's no need to copy secondObj, since it wasn't changed. Other libraries related to immutability in JS work this way (e.g. seamless-immutable's setIn function) and I was hoping that lodash/fp (which is really awesome overall) would, too. One of the nice benefits of immutability is that you can detect changes by doing a === compare, but using set doesn't give you that.

Thanks!

**Comment by jdalton** [comment]
Sure it can totally be tweaked! Thanks for trying it out!

**Comment by jdalton** [comment]
I'll look into it. I don't want to get into fancy object diffing though so no promises.
