### ISSUE TITLE
Merge sometimes loses the prototype on nested objects

### ISSUE THREAD

**Issue by blowery** [lodash/lodash#2018]
Seen on 4.5.0

Repro at http://jsbin.com/fuwagareme/1/edit?html,js,console

I expected the `offset` function to be exist in the merged moment instance.

It seems to only happen when an existing sub-object is added to. Showing this with Moment because that's what tickled the problem for us.

Surfaced in https://github.com/Automattic/wp-calypso/pull/3288

**Comment by blowery** [comment]
A simpler repro is at http://jsbin.com/zanofiqanu/1/edit?html,js,console

**Comment by jdalton** [comment]
This is likely a side effect of us trying to clone the source of a merge to prevent modifications to source objects. I'll dig in.

**Comment by jdalton** [comment]
Usually I'll resolve this by the evening and have a bump by the morning or earlier.

**Comment by blowery** [comment]
Thanks @jdalton! We worked around it with `Object.assign`, but I appreciate the effort!

**Comment by jdalton** [comment]
Ah if you're using O.assign there's `lodash/assign`.

**Comment by jdalton** [comment]
The `_.merge` function is much heavier than either because it recursively merges objects together.

**Comment by jdalton** [comment]
Tests added https://github.com/lodash/lodash/commit/8698a5e0e81d180f78c0f01be86d8d9e1a5d237e.
