### ISSUE TITLE
Uncaught TypeError: _.concat is not a function

### ISSUE THREAD

**Issue by vamsikrishnamannem** [lodash/lodash#2021]
Getting the  `Uncaught TypeError:_.concat is not a function` in version 4.5.0

**Comment by jdalton** [comment]
I can't repro. If you're in the REPL be sure to read https://nodejs.org/api/repl.html#repl_repl_features

**Comment by adamlwgriffiths** [comment]
I had this issue with an older version of lodash ("lodash": "^3.1.0").
Updating to a newer version ("lodash": "^4.16.1") resolved the issue.
