### ISSUE TITLE
In v4.5.0 _.create does not create properties from objects with value 1

### ISSUE THREAD

**Issue by swarajgiri** [lodash/lodash#2022]
Using `_.create` to create objects out of a constructor and another object does not create properties with have a value 1 but creates every other property. Below is a script to reproduce the issue.

```js
var _  = require('lodash'); // v4.5.0

function User()
{
    this.name = null;
    this.canPushNotify = 1;
    this.isSearchable = 1;
    this.isActive = 1;
}

var input = {
    canPushNotify: 1,
    isSearchable : 1,
    isActive     : 0,
    name         : 'Test'
};

var created = _.create(new User(), input);

console.log(created);
```

**Comment by jdalton** [comment]
What you're hitting is by design though maybe it shouldn't be in this case. When we assign values we don't overwrite them if they exist and are the same value. In this case I think it needs a `hasOwnProperty` check.

**Comment by swarajgiri** [comment]
What would then be the ideal workaround for this, unless and more importantly if a fix for this is incorporated in lodash, set properties as 0 or use something like builder pattern?

**Comment by jdalton** [comment]
Yep. This bug has existed since early v3.

**Comment by swarajgiri** [comment]
Wow, that was quick. Thanks @jdalton . Any ETA on npm release?

**Comment by jdalton** [comment]
Since this bug has existed since v3 I'm not in as much of a hurry. Most likely Friday evening.

**Comment by swarajgiri** [comment]
My first open source bug report that got patched and is going to be released. I will drink to that. Cheers @jdalton

**Comment by jdalton** [comment]
:beers:
