### ISSUE TITLE
immutability consistency

### ISSUE THREAD

**Issue by continuata** [lodash/lodash#2025]
I've noticed that quite a lot of the lodash methods mutate the original state e.g. `_.set()`
In the spirit of functional programming can I request that these methods be changed so that they just return a new data structure instead of both returning new data and mutating the original data structure?

lodash is an extremely powerful collection of methods, but this really does let it down

This would be pretty easy to implement (using `_.clone` first in each method to create a local copy), and I'm more than happy to make a start and create a PR.

**Comment by demoneaux** [comment]
Lodash has a functional programming wrapper, [`lodash/fp`](https://github.com/lodash/lodash/wiki/FP-Guide), which has functions such as `_.set` that are immutable, and return a new function, as in functional programming.

**Comment by continuata** [comment]
oh perfect ... thanks so much

**Comment by VictorQueiroz** [comment]
@bnjmnt4n Does it mutate the old object?

**Comment by ephetic** [comment]
@VictorQueiroz  nope.
https://repl.it/MbQg
