### ISSUE TITLE
Feature Request: Ability to skip caching for memoize

### ISSUE THREAD

**Issue by FayneAldan** [lodash/lodash#2029]
Allow skipping caching for memoize, in cases where randomness might be used depending on the function input. My proposal is to skip caching when the resolver returns `_`, like how you specify placeholders for `_.partial`.

### Example use
**TL;DR:** Allow the user to input "random" along with other possible inputs. Only cache if the user did not input "random"

In my scripts, when I allow the user to input a color (eg. for customization), I usually also allow the user to enter "random" to get a random color. However, I also accept multiple color formats (hex, rgb, hsv, hsl) and color manipulation filters (saturate, grayscale, etc.) for input. Because of all the calculations in place, I have the function memoized using this function for the resolver:
```javascript
function(col) { return /^rand(om)?(;|$)/i.exec(col) ? _.uniqueId() : '>' + col; }
```
However, I'd rather not cache the random values since they're only taking up RAM that will never be read, and I'd also rather not prefix the non-random values (which I do because I scream at the thought of the user deciding to input "random_1", especially since the JavaScript version I target doesn't have symbols).

**Comment by jdalton** [comment]
Hi @FayneAldan!

Have you tried using the `cache` of the [memoized function](https://lodash.com/docs#memoize)?
I think that should cover your case.

**Comment by FayneAldan** [comment]
I'm aware of the cache property, but I'm the kind of person who likes to avoid workarounds. 
On Feb 20, 2016 11:23 PM, John-David Dalton <notifications@github.com> wrote:Hi @FayneAldan!

Have you tried using the cache of the memoized function?
I think that should cover your case.
