### ISSUE TITLE
Improve `_.where` function to be able to filter if attribut is no equal to certain value.

### ISSUE THREAD

**Issue by polinom** [lodash/lodash#203]
For example:

``` javascrip
var stooges = [
  { 'name': 'moe', 'age': 40 },
  { 'name': 'larry', 'age': 50 }
];

_.where(stooges, { 'age__gt': 40 });
// → [{ 'name': 'larry', 'age': 50 }]
```

Can be used example from Django framework where:
1.  `__gt` - equals grate than value
2.  `__gte` - grate than or equal to value
3. `__ne` - not equal to value
4. `__lt` - less than value
5. `__lte` - less than or equal to value

**Comment by avimar** [comment]
Not sure if I should open this ticket up, but Ramda has an lt, lte, gt, gte which would allow...
`var maxPrice = 0.2;`
`fp.filter(function(n){ return n.rate<=maxPrice;}) `
to be
`fp.filter(fp.lte('rate',maxPrice))`

in the lodash-fp version (but not normal version), where 'rate' calls the .property. (I think I got the arg order OK..?)

Not such a big deal, but I've been seeing that I often don't need to write ANY of my own functions!

**Comment by jdalton** [comment]
@avimar Close but they don't have property selectors built in so would require an additional function call to a `property` like method. Additions lik, `lt, `lte`, `gt`, & `gte` can be found in [lodash-contrib](https://github.com/TheNodeILs/lodash-contrib/blob/master/_.util.operators.js#L138-L163). We'll keep an eye on demand & include them in core if it picks up.
