### ISSUE TITLE
countBy / groupBy methods that use ES6 Map instead of an object

### ISSUE THREAD

**Issue by nfcampos** [lodash/lodash#2030]
Hi,

Would you consider adding similar methods (or adding an option to the current methods) that use an ES6 Map instead of an object, so that the values (keys) don't have to be stringified?
```js
innerArr = [3, 4]
arr = [1, '2', innerArr]
countBy(arr) // {1: 1, 2: 1, '3,4': 1}
es6MapCountBy(arr) // {1: 1, '2': 1, innerArr: 1}
```
Thanks,
Nuno

**Comment by jdalton** [comment]
That seems like a lot of API splintering. I rather wait until there's a bit more demand for it.

**Comment by hoeni** [comment]
demand ;-)
