### ISSUE TITLE
Documentation per module

### ISSUE THREAD

**Issue by tnrich** [lodash/lodash#2031]
Hey there,

I understand that it might be slightly tedious to keep up to date, but I'd really like it if there could be documentation per module, as well as having the normal docs.

I find I run into the situation where I'll find a lodash package on npm:
![image](https://cloud.githubusercontent.com/assets/2730609/13208422/8ef53860-d8cd-11e5-82be-c9488d4e3ac3.png)

Because the docs aren't available per module, I then have to navigate to the lodash docs, and do another search for the documentation for that module. Not the biggest deal, but definitely a little time consuming..

Thanks for the great utility library, lodash is awesome!
Thomas

**Comment by jdalton** [comment]
The "documentation" link in the readme links right to the method. It's right there in the readme.

**Comment by tnrich** [comment]
Oh, thanks I didn't realize that.

On Sun, Feb 21, 2016 at 7:06 PM, John-David Dalton <notifications@github.com
