### ISSUE TITLE
flatten's default isShallow parameter when callback provided doesn't make sense

### ISSUE THREAD

**Issue by bytenik** [lodash/lodash#2032]
The default behavior of flatten, when called with a callback and no value for shallow, should be to default to `true` for shallow.

https://github.com/lodash/lodash/commit/d0c9371c3a9f589d2b7af639514ec916e0d57118#diff-e3b258a6af20e616c3a40e00504bdf66R3372

**Comment by jdalton** [comment]
In lodash v2 the `_.flatten` method was deep by default.

**Comment by bytenik** [comment]
Right, but when you add a callback it makes little sense for it to be deep.

**Comment by jdalton** [comment]
Back then `flatten` + `callback` was just like `map` + `flatten`.
