### ISSUE TITLE
Thoughts on how to import parseInt unambiguously?

### ISSUE THREAD

**Issue by MeoMix** [lodash/lodash#2037]
Hey there,

I've started importing methods from LoDash using ES6 destructuring. Looks something like:

```js
import { map } from 'lodash';
```

This works great in all scenarios except `parseInt`. If I obtain a reference to the `parseInt` method through destructuring -- ESLint complains that I am not passing a radix to window.parseInt.

Is this a common issue? Is this ambiguous enough that I should just not destructure when wanting to use parseInt, or ?

**Comment by jdalton** [comment]
Sounds like a bug in ESLint.
