### ISSUE TITLE
_.toString() definition throws in IE11

### ISSUE THREAD

**Issue by pke** [lodash/lodash#2039]
In IE11 there is `Symbol` defined with `__proto__` but no `Symbol.prototype`.
So the following code in `_toString` fails when assigning symbolToString because the check condition is wrong.

```
var symbolProto = Symbol ? Symbol.prototype : undefined,
    symbolToString = Symbol ? symbolProto.toString : undefined;
```

Shouldn't it be:
`symbolToString = symbolProto ? symbolProto.toString : undefined;`

**Comment by jdalton** [comment]
Hi @pke!

`Symbol` does not exist in IE11.
See the [es6 compat table](https://kangax.github.io/compat-table/es6/#ie11)

<img src=https://cloud.githubusercontent.com/assets/4303/13245484/7a4fbaca-d9c2-11e5-93a5-848a13fb99d2.png width=50%>

**Comment by pke** [comment]
It does exist, according to F12 tools in IE. Anyway, the lodash code does not load on IE11. So the Symbol handling is broken.

![image](https://cloud.githubusercontent.com/assets/164625/13245722/593c1ebc-da0f-11e5-890f-3c36aa3cc3da.png)

**Comment by jdalton** [comment]
IE11 does not support Symbol. Lodash is tested in IE11. It looks like you have a bad shim.

**Comment by pke** [comment]
That is lodash 3.1, included by babel-cli. Maybe its broken?

**Comment by jdalton** [comment]
Lodash 3.1 was tested in IE11 too. I'm guessing it's a bug in core-js, their shim layer.

**Comment by zloirock** [comment]
@jdalton where you see `core-js`? O_o

**Comment by jdalton** [comment]
babel + symbols in an enviro without Symbol support. It's an educated guess.

**Comment by zloirock** [comment]
`core-js` `Symbol` definitely a function and has `.prototype.toString`, in this issue `Symbol` hasn't `prototype` -> it's not a function.
