### ISSUE TITLE
flatten() with callback parameter

### ISSUE THREAD

**Issue by SLaks** [lodash/lodash#204]
If I have an array of objects that have array properties, I want to be able flatten the properties without creating an extra intermediary array.

For example:

``` js
var data = [ 
  { name: "a", stuff: [...] },
  { name: "b", stuff: [...] },
  { name: "c", stuff: [...] }
};

var allStuff = _(data).pluck('stuff').flatten();
```

Calling `pluck()` (or `map()` for more-complex scenarios) creates an extra array of arrays that I don't want.

Can you add a `flattenWith()` method (or just a `flatten(callback)`) method that does this all at once (and takes a callback or a property name)?

This would let me write

``` js
var allStuff = _.flattenWith(data, 'stuff');
```

(this is equivalent to C#'s [`SelectMany()`](http://msdn.microsoft.com/en-us/library/system.linq.enumerable.selectmany.aspx))

**Comment by vp-hwood** [comment]
Are we back to square one with 3.0 ?
