### ISSUE TITLE
Removing pluck makes extracting a path from a set of objects harder

### ISSUE THREAD

**Issue by nathanmesserbbc** [lodash/lodash#2041]
The removal of pluck from lodash 4 has made things like the following harder:

`var item1 = { a : { b : { c : 'value' }}};`
`var item2 = { a : { b : { c : 'value2' }}};`
`var collection = [item1, item2];`

`_.pluck(collection,['a','b','c']); // => ['value', 'value2']` 

I can see chaining maps, or using map, get and partial as the only ways to achieve the same thing.

Would adding support for paths as well as properties to map be a sensible approach?
If so, would it be possible to get that on the road map, and would a PR be welcome?

**Comment by jdalton** [comment]
You can always use `_.property(['a', 'b', 'c'])`.
