### ISSUE TITLE
_.sum('1.5','2.5') numbers with decimals 

### ISSUE THREAD

**Issue by georgebatalinski** [lodash/lodash#2048]
Would this be something that would need to be fixed? Reason: It worked in 3.9.0 
Happy to do a PR - if it fits the framework 

```
QUnit.test('should not have issue with decimal numbers', function(assert) {
      assert.expect(1);

      assert.strictEqual(_.sum(['1.5', '2.5']), '4');
    })
```

Result 
```
FAIL | EQ | ok | Expected: 4, Actual: 1.52.5
```

**Comment by jdalton** [comment]
In v3.9.0 the result would be the number `4` and not the string `'4'`.

In v4 we relaxed the coercion. It allows folks to use things like `add` as a concat and document that values should be numbers.

**Comment by jdalton** [comment]
You can use `_.sumBy(['1.5', '2.5'], Number)`

**Comment by jdalton** [comment]
I've updated [our changelog](https://github.com/lodash/lodash/wiki/Changelog#v400).

**Comment by georgebatalinski** [comment]
you are awesome - thank you :)

**Comment by asahlali** [comment]
**I'd like to Sum by a filed in my JSON Object**
**My Code** 
     var formatted_data = _(sr)
     .groupBy('workItem.id')
     .map((v, k) => ({
         country: k,
         sessions: _.sumBy(v, 'timeSpent')
     })).value(); 

**as result**
0: {country: "614851", sessions: "28800002880000288000028800002880000"}
1: {country: "912579", sessions: "21600000"} 

**expected**
0: {country: "614851", sessions: "14400000"}
1: {country: "912579", sessions: "21600000"}

**Comment by asahlali** [comment]
Many thanks Dav.
