### ISSUE TITLE
uniqBy throw an error when target property is undefined

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#2049]
It is near impossible to track down the issue when accidentally referring to non-existent property, e.g.

```js
cinemas = _.uniqBy(cinemas, 'id');
```

This was in the code. However, there is no property `cinemas[].id`. There is `cinemas[].result.id`. As it is, the function behaves without any waning returning a single result.

**Comment by jdalton** [comment]
```js
_.uniqBy([null, {}], 'id') // does not error
```

**Comment by gajus** [comment]
But ... thats what I am saying - it doesn't. When I am suggesting it should. It would nice to have some sort of strict mode.

**Comment by jdalton** [comment]
Ohh no. We don't be doing that.

**Comment by megawac** [comment]
You can override _.iteratee to use a stricter property matcher if desired (on mobile so no example)

**Comment by jdalton** [comment]
> You can override _.iteratee to use a stricter property matcher if desired (on mobile so no example)

That's a pretty neat idea! It would also make it togglable.
