### ISSUE TITLE
How to convert a custom function to an fp function?

### ISSUE THREAD

**Issue by simoami** [lodash/lodash#2051]
How to convert a custom function to an iteratee-first data-last methods, just like the fp functions?

I tried the following but it does wrap the function:

```
var findWhere = convert('findWhere', function (obj, attrs) {
   return find(obj, matches(attrs));
 });
```

Any tips?

**Comment by jdalton** [comment]
The `lodash/fp/convert` module is for converting lodash methods. Other methods can be converted with [_.ary](https://lodash.com/docs#ary), [_.curry](https://lodash.com/docs#curry), & [_.rearg](https://lodash.com/docs#rearg).

**Comment by simoami** [comment]
thanks!
