### ISSUE TITLE
Problem testing debounce with sinon

### ISSUE THREAD

**Issue by pladaria** [lodash/lodash#2054]
It is not possible to test debounce using sinon and fake timers:
```
    t.test('debounce happy case', t => {
        const clock = sinon.useFakeTimers();
        const spy = sinon.spy();
        const func = debounce(spy, 500);

        func();
        func();
        func();

        clock.tick(499);
        t.ok(spy.notCalled);

        clock.tick(1);
        t.ok(spy.calledOnce); // this fails

        clock.restore();
        t.end();
    });
```
This problem is caused because debounce() uses a local copy of Date.now().

**Comment by jdalton** [comment]
Dup of #304.

**Comment by pladaria** [comment]
None of the suggested solutions seems to be valid when using debounce as npm module with ES6 imports.

(Previous example updated)

Is there any reason to use the local copy of Date.now in debounce instead of directly calling to Date.now?

In general, I think it is a bad practice to tweak the tests and attach them to some specific library implementation.

Please, take my pull request into consideration.

**Comment by jdalton** [comment]
You're mocking at the wrong level. Don't bother with the PR. It will be closed instantly.

**Comment by jdalton** [comment]
This is a sinon level fix. The first script on the page has the power. It's unreasonable to think all scripts should not hold method references for sinon to do its thing. Instead sinon could wrap the timing methods `setTimeout`, `setInterval`, `Date.now` to allow them to swap implementations without overriding the reference after the wrap. For example:
```js
setTimeout = (function(_setTimeout) {
  return function setTimeout() {
    return sinon.mockEnabled
      ? sinon.mockTimeout.apply(sinon, arguments)
      : __setTimeout.apply(undefined, arguments);
  };
}(setTimeout));
```

**Comment by jdalton** [comment]
That would allow it to work in more places without this b-a-n-a-n-a-s notion that I or anyone else should give up their method references. That's silly.

![](https://media.giphy.com/media/Ic97mPViHEG5O/giphy.gif)

**Comment by Offirmo** [comment]
@jdalton that would require being sure that sinon setup to happen before loading lodash.debounce. This is tricky to do.

I'm stuck with this problem, wanting to test that an expected debounce is correctly implemented by my code. I'm having a hard time advocating unit tests in my company precisely because of such problems.

Even if you have arguments, removing this useless caching would make our lives easier without harming lodash at all... Caching Date.now makes no sense today.

**Comment by jdalton** [comment]
After several requests for improved sinon support I've allowed `clearTimeout`, `setTimeout`, and `Date.now` to be mocked https://github.com/lodash/lodash/commit/023cfdb0c3a3e05723ea81d408d0854618d31c52.
