### ISSUE TITLE
Question: _chain()....map and this

### ISSUE THREAD

**Issue by finalcut** [lodash/lodash#2055]
I am having some trouble figuring out how to do something I had working fine in an older version of lodash.

Here is the old code:

```js
return _.chain(this.instructorIds)
  .unique()
  .map((id)=> this._accountService.get(id))
  .value()
```

In the latest version I try this:

```js
return _.chain(this.instructorIds)
  .uniq()
  .map((id)=> this._accountService.get(id))
  .value()
```

But it fails at the this._accountService.get saying that accountService is undefined.  It seems "this" is being lost but I'm not really sure how to bind my the correct this into the chain.  I used the arrow function initially to avoid this kind of problem.

If you have a moment would you please provide some guidance?

Thanks

**Comment by jdalton** [comment]
Yap, arrow functions should avoid this issue. Unless you're using a transpiler and something got mucked up there. This looks like it's not a lodash issue. Though if you want more help digging in head over to our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by finalcut** [comment]
thanks.  I was just brain dead for a bit; sorry to have bothered you with it.

**Comment by jdalton** [comment]
No bother. Feel free to pop in here or our gitter chat.
