### ISSUE TITLE
pad{left,right} 4.5.1-npm-packages release (and other releases as well?)

### ISSUE THREAD

**Issue by traviskaufman** [lodash/lodash#2057]
Hey all!

I noticed that `_.padleft` and `_.padright` packages only contained `LICENSE` files within them for the `4.5.1-npm-packages` release.

* https://github.com/lodash/lodash/tree/4.5.1-npm-packages/lodash.padleft
* https://github.com/lodash/lodash/tree/4.5.1-npm-packages/lodash.padright

Also noticed they're not in the docs anymore, so I'm assuming they've been dropped from the API. Was wondering if keeping these packages is a bug or if they exist for backwards compatibility?

Thanks! Also sorry if this isn't the most appropriate place for this question; let me know if there's a google group or something better.

**Comment by jdalton** [comment]
Thanks! Fixed.

**Comment by traviskaufman** [comment]
Thank you!
