### ISSUE TITLE
sumBy returns bool instead of integer when the result equals 1

### ISSUE THREAD

**Issue by JonWallsten** [lodash/lodash#2058]
I've noticed that sumBy in Lodash 4 returns bool true instead of 1 if the sum is 1. If the sum is 2 or more it returns an integer as usual. Is this expected behavior?

**Comment by jdalton** [comment]
```js
_.sumBy([{ 'x': 1 }], 'x')
// 1
```

**Comment by JonWallsten** [comment]
```
//list.items
//[{isNew: true}]
list.newItemCount = _.sumBy(list.items, {isNew: true});
//true

//list.items
//[{isNew: true}, {isNew: true}]
//list.newItemCount = _.sumBy(list.items, {isNew: true});
2
```

**Comment by jdalton** [comment]
See next time, lead with an example.

**Comment by jdalton** [comment]
You're using the `iteratee` a bit odd by using the `matches` shorthand as it will produce a boolean which is what will be used to compute the sum.

```js
true + true // 2
```

**Comment by JonWallsten** [comment]
That's a weird behavior for "sum". So how do I count the number of occurrences of isNew: true in one line? I mean, this code was working until I updated to Lodash 4.

**Comment by JonWallsten** [comment]
```
_.countBy(list.items, 'isNew').true; seems a bit ugly?
```

**Comment by jdalton** [comment]
> So the problem is that 'isNew' is a bool?

Yes. 
```js
_.sumBy(list.items, _.flow(_.property('isNew'), Number));
```

**Comment by jdalton** [comment]
or 
```js
_.countBy(list.items, 'isNew')['true']
```

**Comment by JonWallsten** [comment]
Cool, I guess I have to live with that from now on.

**Comment by thadd** [comment]
Why is this closed as invalid? This is really counter-intuitive behavior. I can't see any reason why `sumBy` should every return anything except for a number.
