### ISSUE TITLE
Feature request: support the Closure Compiler in advanced mode

### ISSUE THREAD

**Issue by trkjgrdg** [lodash/lodash#2063]
Could lodash support the Closure Compiler in advanced mode? (Or if it already does, that should be documented.)

As far as I can tell, the Closure Compiler in advanced mode is the only minifier that does non-trivial property renaming, and is widely agreed to be best minifier if one can follow the restrictions it imposes.

According to #1051, "it requires lots of property escaping and corrections for overly aggressive minifications".  Is that still the case?  If it is, are you open to contributions in this direction?

**Comment by jdalton** [comment]
We handle the property escaping on the [lodash-cli](https://github.com/lodash/lodash-cli) side of things. I'm not interested in mucking with lodash's normal source for advanced mode.
