### ISSUE TITLE
_.merge behaves differently for first and second level properties

### ISSUE THREAD

**Issue by koresar** [lodash/lodash#2064]
Case one. _First_ level. Object + Array.
```
$ n_
n_ > _.merge({bar: 'bam'}, ['a','b','c']);
{ '0': 'a',
  '1': 'b',
  '2': 'c',
  bar: 'bam' }
```
Produces object.

Case two. _Second_ level. Object + Array.
```
n_ > _.merge({foo: {bar: 'bam'}}, {foo: ['a','b','c']});
{ foo: [ 'a', 'b', 'c' ] }
```
Produces array. ¯\\\_(ツ)\_/¯

That is very unexpected. Although, the same happens in lodash v3.

Bug?
If not then how to make the two cases consistent?

**Comment by StreetStrider** [comment]
@koresar, I presume this is because `merge` is meant to work on objects. It expects Object on a top level and Any on sublevels. `merge` also mutates object, so it is not possible at all to «replace» type of first argument.

**Comment by jdalton** [comment]
@StreetStrider is right.

**Comment by jdalton** [comment]
To support your case you can always have a dummy prop.
```js
_.merge({ 'output': object }, { 'output': source }).output
```
