### ISSUE TITLE
Add _.toBoolean()

### ISSUE THREAD

**Issue by GreenPioneer** [lodash/lodash#2065]
Hello, 

I have a use case were i am parsing what the user sends me in the string of the url 
```javascript
// http://localhost:3000/api/v1/campaigns?where=funded&ne=true
req.query  =  { where:'funded' , ne:'true' }
// http://localhost:3000/api/v1/campaigns?where=paid&equals=false
req.query  =  { where:'paid' , equals:'false' }
// It always comes in as a string
```
In my Package [BuildREQ](https://github.com/GreenPioneer/buildreq) i will know based off the schema that it is a boolean field so all i need to do next is evaluate what the object is saying from the user. i was gonna just write a small checker but i already use lodash for everything so i figured i would contribute and hopefully see this get added.

GP

**Comment by jfmengels** [comment]
When is see `toBoolean`, the first thing I think of is an equivalent to `!!value`. In this case, especially in regard of strings (and the implementation I see in #2066), it's more like a `parseBoolean`, isn't it?

**Comment by jdalton** [comment]
Hi @GreenPioneer!

This looks like a better fit as a [mixin](https://lodash.com/docs#mixin).

**Comment by StreetStrider** [comment]
@jfmengels, this time it's not `!! value`.
What he wants is not actually a `!! value`, but `value == 'true'`.

**Comment by jfmengels** [comment]
Yeah. I just meant it was a confusing name, since I would think that toBoolean is ~ equivalent to `!!value`

**Comment by GreenPioneer** [comment]
Hey  
I looked at what all of you were saying and placed it in a [JsFiddle](https://jsfiddle.net/greenpioneer/rs9upLqd/) . @StreetStrider 
 hit the nail on the head though because of my use case i cant get away from not evaluating  a true string .
@jfmengels what would you think of calling this then in this use case ?

@jdalton is the js fiddle kinda what you had in mind?

Let me know you thoughts

**Comment by jdalton** [comment]
> is the js fiddle kinda what you had in mind

Yep.

**Comment by jfmengels** [comment]
@GreenPioneer Something like `parseBoolean`? In effect, what you are looking for is an improved `JSON.parse()`, so it would make sense IMO to call it that. Anyway, I agree that this would be a better fit as a mixin.

**Comment by jwerre** [comment]
You could user underscore.string [`toBoolean`](https://github.com/epeli/underscore.string#tobooleanstring--boolean):

    npm install underscore.string
    _.mixin(require('underscore.string').toBoolean);

or if you want a bunch of handy string utilities:

    _.mixin(require('underscore.string').exports());
