### ISSUE TITLE
Webpack + lodash AMD + IE runtime error

### ISSUE THREAD

**Issue by andybeeching** [lodash/lodash#2070]
Hi lodash maintainers,

We have encountered a runtime issue in IE when bundling lodash methods via AMD with a vanilla webpack config and lodash 4.5.1. It seems to choke on the `toString` method file, specifically at [line 11](https://github.com/lodash/lodash/blob/amd/toString.js#L11). 

Changing the `Symbol` expression to `symbolProto` resolves this problem. I guess the `Symbol` polyfill in IE is missing a `prototype` method?

I have attached a zip file containing a simple test case with the webpack config used to generate the bundle. I also note that the test case executes fine in Chrome (I don't have access to Edge, Safari or Firefox to test it at this moment).

Thanks for such a great library and hope this can be addressed easily.

[amdtest.zip](https://github.com/lodash/lodash/files/152812/amdtest.zip)

**Comment by jdalton** [comment]
This was addressed https://github.com/lodash/lodash/commit/f644c82da4be29be01ce9a9d5bbc733d0fa12a81. Do you know the shim being used off hand?

**Comment by andybeeching** [comment]
Ah, sorry for the dupe, Github's filter on the issues defeated my search. Live and learn - thanks for the fix! :)

**Comment by jdalton** [comment]
\cc @zloirock.
I'm not familiar with the shims webpack uses. Would you know were best to direct a bug report?

**Comment by zloirock** [comment]
Sorry, I'm not an expert in WebPack and I didn't know that they use shims.

**Comment by jdalton** [comment]
Ya, weird. I don't see any shim in the `amdtest.zip` source either. Thanks anyways.
