### ISSUE TITLE
_.flip does not work correctly with lodash/fp

### ISSUE THREAD

**Issue by N0ps32** [lodash/lodash#2071]
When using _.flip with lodash/fp I experienced weird behavior.

\_.flip(\_.includes)([2, 5], 5);
Result: true
\_.flip(\_.includes)([2, 5])(5);
Result: false

Expected outcome:
\_.flip(\_.includes)([2, 5], 5);
Result: true
\_.flip(\_.includes)([2, 5])(5);
Result: true

Am I doing something wrong here?

**Comment by jdalton** [comment]
Which `_` is fp are they both FP?

**Comment by jdalton** [comment]
This is by design at the moment. It gets a little tricky but you flip the args so the first value received is the last `array` then you curry the function but it's curried form is not flipped so end up with the args `5, [2, 5]`.

**Comment by jdalton** [comment]
Our `_.flip` does a `args.reverse()` which may not be what you're looking for. You can use placeholders though `_.includes(_, array)(5)`

**Comment by N0ps32** [comment]
Thank you that makes sense.
I'll just not use flip then.

**Comment by vancouverwill** [comment]
yeah I agree the below is the expected behavior as that is the functional way. 
```
_.flip(_.includes)([2, 5], 5);
// Result: true
_.flip(_.includes)([2, 5])(5);
// Result: true
```
I couldn't understand why I could not curry the flipped `_.includes` the same way it normally runs until I came across this issue.
