### ISSUE TITLE
_.has returns true for inherited nested properties

### ISSUE THREAD

**Issue by ar7n** [lodash/lodash#2073]
`var a = _.create({b: {c:true}});
_.has(a, 'b.c'); // true`

[https://jsfiddle.net/q2mhc5mb/3/](https://jsfiddle.net/q2mhc5mb/3/)

**Comment by jdalton** [comment]
This is currently the expected behavior.

The current behavior is to walk the path and once at the parent, `b`, to do the own property check.  Since `c` is an own property of `b` it returns `true`.

That said it does seem counter intuitive and I think we should change it.

**Comment by sashamjolnir** [comment]
wow, so fast. :+1:
