### ISSUE TITLE
Memoize property paths given to stringToPath

### ISSUE THREAD

**Issue by megawac** [lodash/lodash#2075]
In many applications `stringToPath` will be indirectly called with the same path multiple times. These paths may be complex and relatively expensive to convert to an array path.

It probably is worth considering memoizing the results of `stringToPath` for an easy perf which I suspect will outweigh any of the memory considerations.

**Comment by jdalton** [comment]
Yeah this could be an area to look into.
If you want to drive it (perf investigation, implementation, etc). I'm up for it.

**Comment by jdalton** [comment]
I've added this item to our [Roadmap](https://github.com/lodash/lodash/wiki/Roadmap). Feel free experiment and kicking around implementation ideas (no rush).

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash/commit/e4b3cde0a4ebe99589425c87cb1d9bd957893917.

**Comment by deseman** [comment]
Why has this been added within the get and set methods of lodash? If you want to cache the results you can always call memoize yourself before calling the get or set.

Is it possible to disable memoize caching?

**Comment by megawac** [comment]
@deseman it's memoizing the path lookups, i.e. `foo.bar` to `['foo', 'bar']` not the results of the lookup

**Comment by deseman** [comment]
We're using _.get, _.set, _.has, etc. in our services many times with unique paths. All these paths are now being cached which results in a heap that never stops growing. At first we we're searching for a memory leak but it turns out the memoize function in lodash is causing this behaviour.

Although memoize is a great feature, it should be optional when calling _.set, _.get, _.has, etc.

**Comment by jdalton** [comment]
I'm not going to make it optional. I'll add a cap though.

**Comment by jdalton** [comment]
@deseman I'm adding a cap. What do you think is a reasonable cap to reset the memoize cache. How many entries were cached before it became an issue?

**Comment by deseman** [comment]
@jdalton 
This is a hard question to answer as it depends on the path's being used, the amount of heap that is available and if caching is desired.

Personally I would like to see a maximum memory footprint of 1MB for caching in this use case.
I did not yet find any reliable way of testing the exact memory of the cache.
