### ISSUE TITLE
lodash/fp : mapValues iteratee missing arguments

### ISSUE THREAD

**Issue by jeanbaptiste-brasselet-planorama** [lodash/lodash#2077]
Hello,

I have this strange behavior with mapValues, maybe I am doing something wrong here but it seems like an issue.

```
var _ = require('lodash/fp');

var users = {
  'fred':    { 'user': 'fred',    'age': 40 },
  'pebbles': { 'user': 'pebbles', 'age': 1 }
};

_.mapValues(function(value) { 
  console.log(arguments)
  //{
  //  '0': { user: 'fred', age: 40 },
  //  '1': 'fred',
  //  '2': {
  //    fred: { user: 'fred', age: 40 },
  //    pebbles: { user: 'pebbles', age: 1 }
  //  }
  //}
  //{ '0': { user: 'pebbles', age: 1 },
  //  '1': 'pebbles',
  //    '2':
  //  {
  //    fred: { user: 'fred', age: 40 },
  //    pebbles: { user: 'pebbles', age: 1 }
  //  }
  //}
}, users);

_.mapValues(function(value, key) { 
  console.log(arguments)
  //{ '0': { user: 'fred', age: 40 } }
  //{ '0': { user: 'pebbles', age: 1 } }
}, users);
```

**Comment by jfmengels** [comment]
If you're talking about the odd "shape" of the arguments object, it is the normal one, and is not linked to Lodash.

```js
function add(a, b) {
  console.log(arguments);
  return a + b;
}
undefined
> add(2, 3)
// logs: { '0': 2, '1': 3 }
// => 5
```

**Comment by jdalton** [comment]
The iteratee cap is by design. You can read more on that in the [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide#capped-iteratee-arguments). It's also [completely customizable](https://github.com/lodash/lodash/wiki/FP-Guide#convert).

**Comment by Restuta** [comment]
@jdalton would you mind clarifying why it's by design? Our entire team is confused by that since we all new to fp and google doesn't help. Docs mention 

>Iteratee arguments are capped to avoid gotchas with variadic iteratees

but what gotchas?

**Comment by jdalton** [comment]
@Restuta The go to example is with `Array#map` and `parseInt`.
```js
['6', '8', '10'].map(parseInt);
// ➜ [6, NaN, 2]
```
