### ISSUE TITLE
_.omit removes Symbol properties

### ISSUE THREAD

**Issue by jrencz** [lodash/lodash#2081]
Documentation (4.6.1) states that `_.omit`:

> creates an object composed of the own and inherited enumerable properties of object that are not omitted

Which is only true for `string` properties. `Symbols` - even though they are `enumerable` are omitted as well.

```js
const symb = Symbol('symbol declared as global variable');
const obj = {
  foo: 1,
  bar: 2,
  [symb]: 3,
};
```

```js
Object.getOwnPropertyDescriptor(obj, symb)
// Object {value: 3, writable: true, enumerable: true, configurable: true}
```

```js
const afterOmit = _.omit(obj, ['foo']);
'foo' in afterOmit
// false
'bar' in afterOmit
// true
symb in afterOmit
// Expected:
// true
// As is (4.6.1)
// false
```

**Comment by jdalton** [comment]
Would you mind opening a PR to clarify with "string" properties?

**Comment by jdalton** [comment]
You just need to modify the lodash.js source file in root. No need to regenerate the markdown file.

**Comment by jdalton** [comment]
Thinking on this more I think the use of "string properties" would cause more confusion. Symbols are generally though of as pseudo private and lacking of a better way to classify this I'm going to close it as `wontfix`.

**Comment by jdalton** [comment]
I take back my take back. I used the term "string keyed properties".

**Comment by jrencz** [comment]
Despite your "take back" I'd like to discuss the case of considering Symbol properties as pseudo private

> Symbols are generally thought of as pseudo private

I'm leaning towards thinking that `enumerable` is enough to express the "pseudo privacy" you probably meant.

The other valid use case for Symbol properties I can think of (and I'm actually using) is adding properties to some object which is passed through a queue of middlewares to be sure no other middleware can modify that property.

I think it's counterintuitive for `_.omit` to drop such properties because they can be dropped by mistake, even though the docs are clear now.

**Comment by jdalton** [comment]
I just patched `_.omit` and friends to support symbols.

**Comment by jrencz** [comment]
@jdalton thank you for reconsidering

**Comment by jdalton** [comment]
Hi @dietergeerts!

Supporting symbols in `_.assign` made it considerably slower.
You can use `Object.assign` though with `_.rearg` and `_.curry` to create an auto-curried version.

**Comment by dietergeerts** [comment]
Thx for the explanation. Maybe I should not use Symbols. Making sure the string is unique in our project should suffice....
