### ISSUE TITLE
isPlainObject false positive with unusual prototypes

### ISSUE THREAD

**Issue by gibson042** [lodash/lodash#2085]
Cf. https://github.com/jquery/jquery/issues/2968

When the prototype of an object has no `constructor` property of its own (e.g., `Object.create({ foo: "bar" })`), `_.isPlainObject` can find an inherited Object constructor and falsely conclude that the object is plain. This can be remedied by verifying that `constructor` is an own property of the object's prototype: http://jsbin.com/hezeqilega/edit?js,output

P.S. What is the purpose of the `Ctor instanceof Ctor` [check](https://github.com/lodash/lodash/blob/cf74ebeb71028590e12d49d14a888bbef3c3169f/lodash.js#L10546)? The following Function#toString verification seems strictly stronger... is there a performance advantage to the former?

**Comment by jdalton** [comment]
This is by design [by design](https://lodash.com/docs#isPlainObject):
> Checks if value is a plain object, that is, an object created by the Object constructor or one with a [[Prototype]] of null.

> P.S. What is the purpose of the `Ctor instanceof Ctor` check? The following Function#toString verification seems strictly stronger... is there a performance advantage to the former?

Ya, I try to make the string comparisons the last resort.

**Comment by jdalton** [comment]
Ah not by design. You're right.

**Comment by jdalton** [comment]
Thank you for thinking to cross-post this for awareness. You rock!

**Comment by mitar** [comment]
I am glad that I managed to trigger this series of events across multiple projects. :-)

**Comment by AnthonyYY** [comment]
> Ctor instanceof Ctor
Curious about any failed case by `Ctor instanceof Ctor` because i think `toString` call is unnessary
