### ISSUE TITLE
_.assign should copy Symbol properties like Object.assign()

### ISSUE THREAD

**Issue by brandonhorst** [lodash/lodash#2088]
```js
var obj = {[Symbol()]: 1}

_.assign({}, obj); // {}
Object.assign({}, obj) // Object {Symbol(): 1}
```

What are your thoughts?

**Comment by jdalton** [comment]
We tried this in [v3.7.0](https://github.com/lodash/lodash/wiki/Changelog#v370) and [v3.8.0](https://github.com/lodash/lodash/wiki/Changelog#v380) but had complications because it made things slower and forced strict mode-like behavior for little benefit.

**Comment by menocomp** [comment]
In the mean time this is working!!
`
var obj = {test: {[Symbol()]: 1}};
_.assign({}, obj2);
`
Looks like it is not working only if it is first level properties.
