### ISSUE TITLE
sortBy comparator is called on arrays with a single item

### ISSUE THREAD

**Issue by Silverwolf90** [lodash/lodash#2090]
Can be reproduced with the following:

```javascript
_.sortBy([1], (a, b) => { console.log('I WAS CALLED'); return a; })
//=> I WAS CALLED
[1]
```

This is particularly problematic if you are comparing values returned from a function.

```javascript
_.sortBy([{ ... }], (a, b) => a.getLeft() > b.getRight())
// BOOM
```

**Comment by jdalton** [comment]
Hi @Silverwolf90!

This is by design. The `sortBy` uses the `iteratee` to produce the value by which sort order is calculated.
You may be looking for just [Array#sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).

**Comment by Silverwolf90** [comment]
Ah my mistake! Figured it was a drop in. 

Has there been any demand for a something similar to array#sort? Would be nice to have that in lodash/fp. Although it's not particularly hard hand-roll that... :)

**Comment by jdalton** [comment]
> Has there been any demand for a something similar to array#sort?

Most just defer to `Array#sort`. The lodash/fp angle is a new one though. I'll keep an eye on it.

**Comment by teohhanhui** [comment]
Array.prototype.sort is not necessarily stable. It's not a viable alternative.

**Comment by ockham** [comment]
Here's another cause for having a (stable) `sortBy` that accepts a comparator: default args. If I want to specify my comparator (to allow custom ordering) and at the same time be able to specify a default comparator that leaves the array order untouched, I'm currently out of luck.

See https://github.com/Automattic/wp-calypso/pull/10709#discussion_r96639039 for a bit of background.

**Comment by teohhanhui** [comment]
https://www.npmjs.com/package/stable worked well for me.
