### ISSUE TITLE
_.kebapCase removed some accent but not others

### ISSUE THREAD

**Issue by ducdigital** [lodash/lodash#2091]
Seem like `deburr` doesn't support a lot of UTF-8 characters. Isn't it better to just simple `kebapCase()` without `deburr` and let the programer decide how they gonna trim out the accent?

Sample case:
```
_.kebabCase("tôi tên là đức tạ")
"toi-ten-la-đức-tạ"
```

**Comment by jdalton** [comment]
The case methods like `kebabCase`, `snakeCase`, `startCase`, `upperCase`, etc. are made to break apart words (and compound words) and re-combine them with specific casing rules. As such there is a limit to it's scope of what it knows as words. Our [_.deburr](https://lodash.com/docs#deburr) converts [latin-1 supplementary letters ](https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block)#Character_table) to basic latin letters and removes [combining diacritical marks](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks) to aid with the casing rules and transforms between various cases.
