### ISSUE TITLE
FP Guide Wiki could lead with examples

### ISSUE THREAD

**Issue by deanius** [lodash/lodash#2092]
The [FP Guide Wiki](https://github.com/lodash/lodash/wiki/FP-Guide) has alot of information that is useful for setting configuration options, but to a FP n00b, they'll go away wondering if they should try learning something easier like a monoid in the category of endofunctors.

But seriously, an illustrative code example above the fold would not hurt - that was actually what I was looking for when I found what was there. 

D

**Comment by jdalton** [comment]
Please edit the wiki with your tweaks.

**Comment by jdalton** [comment]
@deanius are you up for making the change in the wiki?

**Comment by deanius** [comment]
Sorry, no, just leaving a suggestion.
