### ISSUE TITLE
_.sortBy nested object property

### ISSUE THREAD

**Issue by patriciocordova** [lodash/lodash#2094]
Considering implementing:

var users = [
  { 'user': 'fred',   'age': 48,   'login': { 'hour': '13', ... } },
  { 'user': 'barney',   'age': 36,   'login': { 'hour': '23', ... } },
  { 'user': 'fred',   'age': 42,   'login': { 'hour': '01', ... } },
  { 'user': 'barney',   'age': 34,   'login': { 'hour': '02', ... } }
];

_.sortBy(users, ['login.hour']);
// → objects for [['fred', 42, 'login': { 'hour': 01 }], ['barney', 34, 'login': { 'hour': 02 }], ['fred', 48, 'login': { 'hour': 13 }], ['barney', 36, 'login': { 'hour': 23 }]]

**Comment by jdalton** [comment]
You'll be happy to know this already works :)
