### ISSUE TITLE
no groupby or orderby when installing from npm

### ISSUE THREAD

**Issue by dagda1** [lodash/lodash#2095]
I have just installed lodash via npm:

npm install --save lodash

```groupBy``` and ```orderBy``` are not  in the source, am I missing something?

**Comment by jdalton** [comment]
Ensure you've cleared your npm cache and make sure it's v4.6.1.

**Comment by dagda1** [comment]
It is v4.6.1 and I deleted the node_modules folder before re-installing, still no cigar.

**Comment by jdalton** [comment]
I'm sorry you're having problems. This is not a lodash issue. It's not reproducible and we have tests for these methods (~100% test coverage in fact).
