### ISSUE TITLE
how do i get a Map with _.keyBy?

### ISSUE THREAD

**Issue by bcherny** [lodash/lodash#2096]
do i need to manually convert the resulting object to a Map?

**Comment by jdalton** [comment]
> do i need to manually convert the resulting object to a `Map`?

Yes.

**Comment by bcherny** [comment]
bummer, would be nice to have this built in. since keyBy uses an object as the intermediate representation, we lose type info for the key. eg.

```js
const as = [
  { a: [1,2] },
  { a: [3,4] }
]
_.keyBy(as, 'a') // doesn't work as expected
```

**Comment by jdalton** [comment]
Ya, I could see a whole group of methods that could use a `Map`. If you help define them it may make it easier to categorize and create down the road.

**Comment by binki** [comment]
@jdalton is there an issue tracking `Map` support?

**Comment by jdalton** [comment]
I'm not going to add `Map` support in the v4 timeframe. I may check back with v5.
