### ISSUE TITLE
get() when keys contain a dot(.) should work

### ISSUE THREAD

**Issue by ehartford** [lodash/lodash#2097]
var v = { 'a': { 'b.c': 'd' }};
    console.log(_.get(v, 'a.b.c'));

Expected: 'd'
Observed: undefined

**Comment by jdalton** [comment]
You can see how the path will be interpreted by doing:
```js
_.toPath('a.b.c');
// => ['a', 'b', 'c']
```
For your case you can pass an array
``js
_.get(v, ['a','b.c'])
// => 'd'
```
