### ISSUE TITLE
mapKeys doesn't work when chained in lodash/fp

### ISSUE THREAD

**Issue by 9point6** [lodash/lodash#2099]
`mapKeys` doesn't behave correctly when used in a chain in `lodash/fp` mode for `4.6.1`. 

```javascript
var _ = require('lodash/fp');
const obj = {
  'max-age': 1000,
  'stale-while-revalidate': 1000
};

console.log('A', _(obj).mapKeys(_.camelCase).value());
console.log('B', _.mapKeys(_.camelCase, obj));
```

outputs: 
```javascript
"A" {
  1000: 1000
}

"B" {
  maxAge: 1000,
  staleWhileRevalidate: 1000
}
```

**Comment by jdalton** [comment]
Chaining is not fp-converted. For fp style you should favor `_.flow` or `_.flowRight`. See [Why Using `_.chain` is a Mistake](https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba) for more on this.
