### ISSUE TITLE
_.uniqBy - {latitude: undefined, longitude: undefined}

### ISSUE THREAD

**Issue by georgebatalinski** [lodash/lodash#2100]
Would this be a bug? There is 2x undefined?
```
var toGiveBack = _.uniqBy(_.flattenDeep([[{latitude: 2, longitude: 3}], [{latitude: 2, longitude: 3}, {latitude: undefined, longitude: undefined}]]), function(item) {
        return item.latitude && item.longitude;
      });
```

Result:

toGiveBack - contains
```
[Objectlatitude: 2 longitude: 3__proto__: Object, 
Objectlatitude: undefinedlongitude: undefined__proto__: Object
```

**Comment by jdalton** [comment]
The results are correct. The `_.uniqBy` method uses the result of the `iteratee` as the criteria to compute uniqueness. The result of `item.latitude && item.longitude` is `undefined` meaning it will be the only result that resolves to `undefined` in the uniq set.

**Comment by jdalton** [comment]
You can filter your results if you want to remove those with `undefined` property values.
