### ISSUE TITLE
repeat should break when n equals 0

### ISSUE THREAD

**Issue by libreninja** [lodash/lodash#2103]
_.repeat(string, n) concatenates the input string with itself on every iteration of the do-while loop, including the last iteration when the concatenated result will never be used. If n, or the the length of the input string is large enough, repeat will generate a "RangeError: Invalid string length" exception. Breaking before `string += string` in the final iteration would prevent exceptions in some cases.

```javascript
do {
  if (n % 2) {
    result += string;
  }
  n = nativeFloor(n / 2);
  
  // guard against unnecessary "Invalid string length" exceptions
  if(n === 0) {
    break;
  }
  string += string;
} while (n);
```

**Comment by jdalton** [comment]
Thanks, moving to #2104.
