### ISSUE TITLE
defaults in fp does not mutate the destination object

### ISSUE THREAD

**Issue by boneskull** [lodash/lodash#2105]
```js
import {defaults} from 'lodash/fp';

const foo = {};
defaults({bar: 'baz'}, foo);
foo; // {}
```

I'm not sure *if it should*, but there's no documentation anywhere to the contrary, unless I missed something.

**Comment by jdalton** [comment]
See the [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide).

**Comment by boneskull** [comment]
ty
