### ISSUE TITLE
Lodash development workflow

### ISSUE THREAD

**Issue by Diokuz** [lodash/lodash#2106]
Im trying to understand what lodash development workflow is, and how exactly code from master branch goes to `npm` branch?

In `master` I see many commits in one big `/lodash.js` file. Just one single JS file. And all pull-request are made to `master`.

But there is an `npm` branch for npm publishing, where all code splitted to many files. Where the source of lodash? Is it the `npm` branch, and there is some non-published build logic? Or source is `master` branch, and all changes goes to `npm` (and also to `npm-packages`) branch by copy&paste from `master` single file?

**Comment by demoneaux** [comment]
The source is based on lodash.js in master. The files in the other branches are generated using [lodash-cli](https://github.com/lodash/lodash-cli).
