### ISSUE TITLE
Migrating from underscore.js: context-parameter is missing

### ISSUE THREAD

**Issue by misantronic** [lodash/lodash#2107]
Hey there,

I tried to migrate from underscore 1.8.3 to lodash with your [wiki-entry](https://github.com/lodash/lodash/wiki/Migrating).
Problem is, that my app + plugins use the `context`-parameter all over, f.e. in [`_.each`](http://underscorejs.org/#each). As far as I know, [lodash `_.each`](https://lodash.com/docs#forEach) does not support this.

Is there a workaround to this?

**Comment by jdalton** [comment]
Hi @misantronic!

You can use `_.bind` or ES6 arrow-functions.

**Comment by misantronic** [comment]
Hi @jdalton,

thanks for your fast reply!

If these plugins were mine, I would totally do that. Unfortunately, I cannot (or don't want) to change them for compatibility reasons. 
I am wondering, that nobody came across this issue when migrating.
Do you think it might be a good idea to write a lodash-plugin to support a `context`-parameter?

**Comment by jdalton** [comment]
I'm not interested in supporting Underscore.
Devs will migrate or they'll get left behind. It's beyond time now.

**Comment by jdalton** [comment]
If you're in a situation where you're stuck with Underscore you can supplement with Lodash modules.

**Comment by jtakalai** [comment]
That's an interesting attitude, given how much code is written for Underscore, and of course some fraction of that code WILL use every possible mis-feature it has. Telling people to "migrate" code that they don't control is not a constructive suggestion.

**Comment by misantronic** [comment]
I made an approach for lodash to support context-parameters:
https://github.com/misantronic/lodash.context

**Comment by jdalton** [comment]
@jtakalai If they don't control their code it's really out of our hands.
