### ISSUE TITLE
propose _.filterBy

### ISSUE THREAD

**Issue by guatedude2** [lodash/lodash#2108]
I think there should be a filter by similar to pick where you can filter out by a given object:
e.g.
`{ a: { b: { c:1, d:2, e:3 }, f: { g:4, h:5 }, i:6 }`
cherry pick with a given object:
`{ a: { b: { e: true}, f: true} }`
and the output would be:
`{ a: { b: { e:3 }, f: { g:4, h:5 } }`

Here's a prototype:
```
function filterBy(obj, map) {
  var result = {};
  if (map === true) return obj;

  Object.keys(obj).forEach((k) => {
    if (map[k] !== undefined && Object.keys(obj[k]).length > 0) {
      result[k] = filterBy(obj[k], map[k]);
    }
  });
  return result;
}
```

**Comment by jdalton** [comment]
Hi!

I don't think this method is a good fit for core atm.
