### ISSUE TITLE
lodash fp immutability off

### ISSUE THREAD

**Issue by rickmed** [lodash/lodash#2109]
is there a way to turn immutability off by default all methods on lodash fp?
thanks!

**Comment by demoneaux** [comment]
You can [customise the creation of the FP methods](https://github.com/lodash/lodash/wiki/FP-Guide#convert):

```js
var lodash = require('lodash'),
    convert = require('lodash/fp/convert');

// Convert lodash
lodash = convert(lodash.runInContext(), {
  // Specify immutable operations.
  'immutable': false
});
```

**Comment by rickmed** [comment]
@demoneaux thanks!

**Comment by jdalton** [comment]
In the next release we're adding `convert` helpers to each lodash method so you can do:
```js
var runInContext = _.runInContext.convert({ 'immutable': false });
```
I'll expand that to adding it on the `fp` export itself so you can do:
```
var fp = require('lodash/fp').convert({ 'immutable': false });
```

**Comment by jdalton** [comment]
Here's the commit for the addition of `fp.convert` https://github.com/lodash/lodash/commit/1bbb24fa0c364cb4495ff95ee684389d36fcc026.
