### ISSUE TITLE
Feature request: zfill

### ISSUE THREAD

**Issue by Droogans** [lodash/lodash#2110]
One of my projects uses this nice little npm library for `zfill` functionality: https://github.com/andrewrk/node-zfill.

Would it makes sense to replace it with `_.zfill(number, paddingLength)`?

**Comment by c-dante** [comment]
Is that just https://lodash.com/docs#pad ?

**Comment by jdalton** [comment]
Yep, @c-dante is right. You can do:
```js
_.padStart(9, 3, '0')
// => '009'
```

**Comment by Droogans** [comment]
Thank you!

**Comment by c-dante** [comment]
Or even better...

```
var _ = require('lodash/fp');
var zfill = _.padStart('0');
```

...I'll stop now...

**Comment by jdalton** [comment]
Using placeholders would be better as this prevents issues if they try to provide additional arguments.
```js
var zfill = _.partial(_.padStart, _, _, '0');
```
or using `lodash/fp` in the next release
```js
var zfill = _.padStartChars('0');
```
