### ISSUE TITLE
add _.getter that always returns the current value of a property on an object

### ISSUE THREAD

**Issue by metaist** [lodash/lodash#2113]
I often find myself passing around functions like:
```javascript
function () { return obj.prop; }
```
When all I want to write is:
```javascript
_.getter(obj, 'prop')
```
Naive implemenation would be something like:
```javascript
_.getter = function(object, path, defaultValue) {
  return function () {
    return _.get(object, path, defaultValue);
  };
};
```

**Comment by jdalton** [comment]
Use _.property or the fp form of _.get.

**Comment by metaist** [comment]
Hi @jdalton!

Thank you for making me realize that what I really wanted was a way to [_.bind] args to [_.property].

[_.bind]: https://lodash.com/docs#bind
[_.property]: https://lodash.com/docs#property

For future searchers:

```javascript
var object = { prop: 'value' };
var getter = _.bind(_.property('prop'), _, object);
getter();
// => 'value'

object.prop = 'new value';
getter();
// => 'new value'
```
