### ISSUE TITLE
Feature request: _.debugger

### ISSUE THREAD

**Issue by russplaysguitar** [lodash/lodash#2114]
`function() { debugger; }` is a useful debugging tool. It would be nice if there were a lodash function for this, such as: `_.debugger`. 

Examples:

```js
// break on click
jQuery(element).on('click', _.debugger);

// break once the stack has cleared
_.defer(_.debugger);

// tap into method chain to inspect the state of intermediate results
_([1,2,3]).tap(_.debugger).reverse().value();
```

**Comment by jdalton** [comment]
Hi @russplaysguitar!

I think this would make a good [mixin](https://lodash.com/docs#mixin).
However, if there's sufficient demand we'll re-evaluate its inclusion in core.

**Comment by russplaysguitar** [comment]
Sounds good, thanks!
