### ISSUE TITLE
sortedUnion

### ISSUE THREAD

**Issue by MyLittleRobo** [lodash/lodash#2117]
Having `sortedUniq` it would be also nice to have `sortedUnion` that would benefit from the knowledge that all collections are sorted.
`sortedUnion` should work just like `union`, but expecting all arrays to be sorted.
It's not clear though whether the result should be sorted or be in order of first element appearance (like in `union`).

**Comment by jdalton** [comment]
So like:
```js
_.sortedUnion([1, 1, 2], [2, 3, 3], [4, 5, 5]);
// => [1, 2, 3, 4, 5]
```

I'm not against it but because the sort forms are the less common usage I want to hold off until there's more user demand for it.

**Comment by jdalton** [comment]
The benefit in the simplified linear pass while searching for duplicates. This makes the case pretty narrow for when it would be useful. For example this would work:
```js
_.sortedUnion([1, 1, 2], [1, 2, 3], [2, 4, 4]);
```

**Comment by MyLittleRobo** [comment]
Yes, of course this function would require something more complicated than linear pass because of situation you described. I just hoped optimized algorithms exist for this task.

**Comment by MyLittleRobo** [comment]
E.g. here's obvious special case for two sorted arrays, that's nearly linear pass. Generic function on arbitrary number of arguments using the same idea would be nightmare of course.

```

var arr1 = [3,5,8,10,10,11];
var arr2 = [2,2,6,9];

var index1 = 0;
var index2 = 0

var result = [];

while(index1 < arr1.length && index2 < arr2.length)
{   
    if (arr1[index1] == result[result.length-1]) {
        index1++;
    } else if (arr2[index2] == result[result.length-1]) {
        index2++;
    } if (arr1[index1] < arr2[index2]) {
        result.push(arr1[index1]);
        index1++;
    } else {
        result.push(arr2[index2]);
        index2++;
    }
}

if (index1 == arr1.length) {
    for (;index2<arr2.length; ++index2) {
        if (arr2[index1] != result[result.length-1]) {
            result.push(arr2[index2]);
        }
    }
}
    
if (index2 == arr2.length) {
    for (;index1<arr1.length; ++index1) {
        if (arr1[index1] != result[result.length-1]) {
            result.push(arr1[index1]);
        }
    }
}

console.log(result);
```
