### ISSUE TITLE
findIndex issue

### ISSUE THREAD

**Issue by jeremy24** [lodash/lodash#2119]
when comparing with an undefined  object, findIndex doesn't output an error message,  it just hangs without failing, or throwing any kind of warnings

**Comment by jdalton** [comment]
Hi @jeremy24!

I can't repro the issue you've described.

**Comment by megawac** [comment]
When you pass undefined (or no arguments) to `findIndex` the predicate function that will be used is `_.identity`. In regards to `findIndex` this means that the first "truthy" value will result in the index being returned and if there are no truthy items it will result in -1.

```js
_.findIndex([false, 0, null, undefined, 1], undefined) // => 4
_.findIndex([false, 0, null, undefined, 1]) // => 4
```
