### ISSUE TITLE
<a id="_"> in docs

### ISSUE THREAD

**Issue by seiyria** [lodash/lodash#2120]
Can this please get removed? The primary place I go to test lodash is the lodash docs and having this override the global `_` makes it impossible to test lodash without spinning up a local repl. Currently this is a problem for me in Google Chrome 50.0.2661.26 beta. It's located [here](https://dl.dropboxusercontent.com/u/28522694/ShareX/2016/03/chrome_2016-03-16_14-04-33.png).

**Comment by jdalton** [comment]
I'm aware of implicit globals created form element ids however it doesn't seem to be an issue as the global `_` exported by Lodash trumps the implicit global of the element in stable browsers. You should file a bug on Chrome's beta (chances are it's a regression).

**Comment by tyscorp** [comment]
For anyone googling: simple refreshing has fixed this for me every time.

I've been getting this in Chrome dev-m for the past few weeks, (`51.0.2687.0 dev-m` currently) but I'm unable to consistently reproduce it...
