### ISSUE TITLE
`_.without` can only remove one value in FP

### ISSUE THREAD

**Issue by jfmengels** [lodash/lodash#2122]
In vanilla Lodash, you can use `_.without` with an arbitrary number of values to remove args
```js
_.without([1, 2, 1, 3], 1, 2);
// => [3]
```
In lodash/fp, I expected to get the same results by putting the args in an array
```js
_.without([1, 2], [1, 2, 1, 3]);
// => expected [3]
// => got [1, 2, 1, 3]

// it is not even removing corresponding arrays, so it's not even
// because it might be useful to remove array values
_.without([1, 2], [1, [1, 2]]);
// => [ 1, [ 1, 2 ] ]

// works fine with one argument though
_.without(1, [1, 2, 1, 3]);
// => [2, 3]
```

In this case, you get the correct result by using `pullAll`, but it's pretty confusing.

**Comment by jdalton** [comment]
I can make `_.without` accept an array but then it's really an alias for `_.difference`.

**Comment by jfmengels** [comment]
It would be the same as `difference` when `without` has an array of values, not when it has a single value. But yeah, otherwise they'd  be the same.
I think it would be fine for it to have the same behavior as `difference`, fp was bound to make some methods similar anyway.
I think it's more problematic to have a behavior inconsistent with the docs, especially if the user doesn't know Lodash well and doesn't even know there is `difference` or `pullAll`.

**Comment by jdalton** [comment]
I won't want to overload on that because you may want to omit an array value.
