### ISSUE TITLE
Update website to assist in migration from 3.x to 4.x

### ISSUE THREAD

**Issue by thinkingmedia** [lodash/lodash#2123]
**Please** update the website to help developers migrate from 3.x to 4.x

On the home page http://www.lodash.com add another section labelled "Migration from 3.x"

Right now the home page contains the following labels

- Documentation
- Download
- Installation
- Why Lodash?
- Module Formats
- Further Reading
- Support

Can you insert "Migration from 3.x" after Download or Installation?

It should read something like this

## Migration from 3.x

Lodash API has changed since version 3.x. 

- [Change logs since 4.0 release](https://github.com/lodash/lodash/wiki/Changelog#jan-12-2016--diff--docs).
- [Lodash-Migrate to assist in updating your code](https://github.com/lodash/lodash-migrate)

**Comment by jdalton** [comment]
The further reading mentions changelog which is a natural place to look and where migration and other helpers are referenced.

**Comment by thinkingmedia** [comment]
You guys suck.
