### ISSUE TITLE
is lodash/fp#includes working properly ?

### ISSUE THREAD

**Issue by namlook** [lodash/lodash#2126]
lodash/fp intend to put the object to the end, but it seem that it is an automatically process which can produce unintended behavior. It can be the case of `includes`:

What I want to do is something like that:
```javascript
const _fp = require('lodash/fp');

const validValues = ['foo', 'bar', 'blah'];

const isValid = _fp.inludes(validValues);

isValid('foo');
```

In this example, the `isValid` method will always return `false`. To make this example to work, we have to change the arguments order:

```javascript
const isValid2 = (o) => return _fp.includes(o, validValues);
```

This is because the "regular" lodash `includes` method takes the object first...

Is is the correct behavior and I am missing something, or should lodash/fp have some exception about the arguments inversion ?

**Comment by jdalton** [comment]
See the [FP-Guide](https://github.com/lodash/lodash/wiki/FP-Guide#rearranged-arguments).
In its FP form `_.includes` has a fixed arity of 2 and an arg order of `(b, a)`.

**Comment by namlook** [comment]
Then I guess I will have to use `partial` to construct the `isValid` function...

Thank you for your answer.

**Comment by jdalton** [comment]
You can use a placeholder instead.
```js
const isValid = _fp.includes(_fp, validValues);
```

**Comment by namlook** [comment]
Much better ! thank you :beer:
