### ISSUE TITLE
every() function returns "true" on empty array argument

### ISSUE THREAD

**Issue by mmelnik** [lodash/lodash#2129]
Hi, I'm new to lodash, but it seems that there is a mistake in every() function implementation.

Possible reason lies inside arrayEvery() func. Looks like we should return "false" by default and check inverted predicate and return "true" only if condition is satisfied.

Here is code:
```
function arrayEvery(array, predicate) {
    var index = -1,
        length = array.length;

    while (++index < length) {
      if (!predicate(array[index], index, array)) {
        return false;
      }
    }
    return true;
  }
```

Can you comment this situation, am I wrong? Thank you.

**Comment by jdalton** [comment]
See [Array#every](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every)
> every acts like the "for all" quantifier in mathematics. In particular, for an empty array, it returns true. (It is [vacuously true](http://en.wikipedia.org/wiki/Vacuous_truth#Vacuous_truths_in_mathematics) that all elements of the [empty set](http://en.wikipedia.org/wiki/Empty_set#Common_problems) satisfy any given condition.)

**Comment by mmelnik** [comment]
Thank you for sharing rules you're based on.
But is this consistent with some() behaviour that works in opposite way?

**Comment by jdalton** [comment]
It's consistent with JavaScript and its method precedents. You might dig more into set theory to find out more on the reasons for such behaviors.

**Comment by mmelnik** [comment]
Thank you for clarification!
