### ISSUE TITLE
Better FP argument order for `isEqualWith`

### ISSUE THREAD

**Issue by mhelvens** [lodash/lodash#2131]
Hi. It seems to me there is (at least) one lodash operation left that would benefit from a custom argument order for the FP version: `isEqualWith`. The argument order should probably be `(c, a, b)`. I'm guessing it was missed by accident, since you did fix `isMatchWith`.

**Comment by jdalton** [comment]
@mhelvens Awesome. Would you be up for creating a PR?

**Comment by jdalton** [comment]
You should just have to modify the `fp/_mapping.js` and the `test/test-fp.js`.

**Comment by mhelvens** [comment]
Be happy to. (I just wanted to make sure, since there might be some people who now depend on the current version.)

**Comment by jdalton** [comment]
We'll treat it as a bug.

**Comment by jdalton** [comment]
Moved to #2132.
