### ISSUE TITLE
@jdalton

### ISSUE THREAD

**Issue by mhelvens** [lodash/lodash#2134]
Sorry for putting this here, but you locked comments on #2132. I need to get this out, and I see no other way. Go ahead and delete this when you've read it.

I really did not expect this reaction. But I'm usually oblivious to this kind of thing. So I genuinely apologize if I offended you (or anyone). It was just meant as a joke, if a stupid one. I hardly gave it a second thought, but I guess I should have.

To be clear: I greatly support open source and creative commons, so I gladly waive copyright. (Even though I did not submit any code samples, so for this particular pull request, the issue was moot.)

I'd be happy if you could just go ahead with the pull request and pretend I didn't make any stupid jokes.

**Comment by jdalton** [comment]
That's cool. No worries.
