### ISSUE TITLE
Deep clone map with nested maps.

### ISSUE THREAD

**Issue by sergej-s** [lodash/lodash#2137]
Hello,

I'm stuck with issue of deep cloning map which contains other maps. It seems that values of nested map are not cloned. Please look at the next code:

```js
let m1 = new Map([
  [1, {a: '1'}],
  [2, {b: '2'}]
])

let m2 = new Map([
  [3, {c: '3'}],
  [4, {d: '4'}]
])

let m3 = new Map([
  ['m1', m1],
  ['m2', m2]
])

let m4 = _.cloneDeep(m3);

console.log(m4===m3); // log false - Ok
console.log(m4.get('m1')===m3.get('m1')); // log true - but should be false also`
```
Is this bug or am I doing something wrong?

Tested with lodash 4.6.1 [http://jsbin.com/jubiwaquma/1/edit?html,js,output](http://jsbin.com/jubiwaquma/1/edit?html,js,output)

**Comment by jdalton** [comment]
Deep cloning maps isn't currently supported. It can be though. I'll dig into it.

**Comment by sergej-s** [comment]
Thanks you for reply!

**Comment by jdalton** [comment]
Added support at https://github.com/lodash/lodash/commit/461e5b4ede0852b6e8ddd1edbc1568138962710c.

**Comment by Xplouder** [comment]
+1, would be a cool feature.
