### ISSUE TITLE
Split `̀fp/divide` into two methods

### ISSUE THREAD

**Issue by jfmengels** [lodash/lodash#2138]
I saw the `divide` method appear in https://github.com/lodash/lodash/commit/6eb0cb156505adfb5356fd67255c131055c637c8.
For `divide`, do you think it might be interesting, or is it too confusing, to have two functions in `fp`?
- `_.divideBy(10)(2) // => 5` (arg order reversed compared to current), for when you know the dividend, and the data is the divisor (I have 10 pies, but I don't know how many people will attend the birthday party).
- `_.divide(10)(2) // => 0.2` (current arg order in both vanilla and fp), for when you know the divisor, and the data is the dividend (10 people will attend the birthday party, but I don't know how many pies I will be able to make).

My aim by proposing this is to help avoid the use of `partial` (or custom functions) in a flow construct. It's easy enough to call divide with args in one order or the other if you have all the data and/or variables, but in a flow construct, depending on whether you want the known value be divided or for it to divide the data, you may have to use partial or a new function calling divide.

**Comment by jdalton** [comment]
I want to avoid arg order variants for now. This is why we have placeholders and `convert`.

**Comment by jfmengels** [comment]
Ah, didn't even know about placeholders! (or at least without partials)
Ok, well that's great then, forget about this :)

**Comment by jdalton** [comment]
Yep! Methods like `_.bind`, `_.bindKey`, `_.partial`, `_.partialRight`, `_.curry`, & `_.curryRight` support arg placeholders as well as all curried methods.

**Comment by jfmengels** [comment]
I knew about `partial`, not about the rest though, thanks for that info.
Man, this makes `lodash/fp` so much cooler than before! (and you know I was already a big fan of it)
