### ISSUE TITLE
Document old names for functions inside the documentation

### ISSUE THREAD

**Issue by eranimo** [lodash/lodash#2139]
As someone who has used lodash for a while, it's very confusing when I remember a function name and I look through the docs and it's missing, only to find it on the changelog. It would be very useful it we could have a line next to each function like "previously known as pluck [link to changelog]"

**Comment by jdalton** [comment]
This is covered in the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v400). A [deprecations](https://github.com/lodash/lodash/wiki/Deprecations) page was recently added as well.

**Comment by jdalton** [comment]
I don't want to clutter the docs with these bits as it's an issue that naturally shakes out over time. In the next release we're adding `@since` tags give context to when methods were added.
