### ISSUE TITLE
chain with map not getting object from find result. 

### ISSUE THREAD

**Issue by kentonbmax** [lodash/lodash#2141]
Consider the following:
```js
var record = _.chain(JsonObject)
                .find(function(o){
                    return o.MachineName === $scope.series[i];
                })
// note that o inside the find function works and returns the correct object if i end the chaing wiht .value().
                .map(function(current){
                     // current = 190 which is my Id. 
                    return Math.abs(current.Availability * 100);
                })
                .value(); // value becomes undefined because current = 190 and not my object. 
```
![image](https://cloud.githubusercontent.com/assets/15804484/13956678/f84a7370-f01f-11e5-85c9-4d2bde5f0493.png)

![image](https://cloud.githubusercontent.com/assets/15804484/13956735/38f896b8-f020-11e5-844c-b673e796a767.png)

**Comment by jdalton** [comment]
`_.map` returns an array. You should try [_.mapValues](https://lodash.com/docs#mapValues).

**Comment by kentonbmax** [comment]
the value passed in to _.mapValues or _.map = 190. Shouldn't it be the object returned by my _.find?

**Comment by jdalton** [comment]
For support questions try our [gitter chat](https://gitter.im/lodash/lodash).
