### ISSUE TITLE
New feature: Array with auto expires

### ISSUE THREAD

**Issue by nodesocket** [lodash/lodash#2143]
Interested in an implementation of an array where elements automatically expire **(delete)** after a set time.

```
// elements persist for 5 seconds
let cache = _.expiresArray(5000);
cache.push('foo');
setTimeout(function() {
     console.log(cache); // []
}, 6000);

**Comment by jdalton** [comment]
I don't think this is a good fit for Lodash. Feel free to keep hammering on it as a [mixin](https://lodash.com/docs#mixin) though.
