### ISSUE TITLE
Proposal: _.meanBy

### ISSUE THREAD

**Issue by TuckerWhitehouse** [lodash/lodash#2148]
Similar to `_.minBy`, `_.maxBy` & `_.sumBy`, seems fitting to include a `_.meanBy`.
I've implemented a solution using `_.sumBy(array, [iteratee]) / array.length`.

**Comment by c-dante** [comment]
I mean... Does moving that division into lodash do anything to help...? I guess you can compose averages then?

**Comment by TuckerWhitehouse** [comment]
It just felt like a method that would be fitting considering the similar methods in that category, and that it happened to be the exact functionality I was looking for, so instead of having to require `lodash.sumby` and create my own wrapper function to sum and divide by the length, I would just require `lodash.meanby`.

**Comment by jdalton** [comment]
@TuckerWhitehouse we should have a `meanBy` as a companion to `mean` and consistency with the other APIs. Would you like to create a PR?

**Comment by c-dante** [comment]
Oops, didn't notice that lodash has `mean` -- yay symmetry!

**Comment by jdalton** [comment]
Moving to #2150.
