### ISSUE TITLE
Nearly impossible to navigate documentation on Mac OS X / Safari

### ISSUE THREAD

**Issue by mrusme** [lodash/lodash#2152]
It's nearly impossible to scroll the left sidebar of the lodash documentation inside Safari on Mac OS X, as scrolling only makes the right pane scroll up and down. Check out the video (.mov packed as .zip) attached to this issue for a visual documentation of the issue.

[lodash.zip](https://github.com/lodash/lodash/files/189445/lodash.zip)

**Comment by jdalton** [comment]
Dup of https://github.com/lodash/lodash.github.io/issues/12. If you have a patch suggestion that would probably go a long way in fixing it.
