### ISSUE TITLE
[FEATURE] - uniqDeep alias uniqBy

### ISSUE THREAD

**Issue by michaelBenin** [lodash/lodash#2155]
Example:

```
var list = [{ id: { un_id: 1 } }, { id: { un_id: 1 } }, { id: { un_id:2 } }];
_.uniqDeep(list, 'id.un_id');

// compared to 

_.uniqBy(list, 'id.un_id');
```

To some people, maybe the name uniqDeep be more self descriptive than uniqBy?

**Comment by jfmengels** [comment]
A lot of methods use the convention <operation>By, and I think it's fine.
Besides, it's not an operation that is inherently deep, so the proposed alias is not that appropriate IMO.

**Comment by michaelBenin** [comment]
My use case was making a list unique by a nested property, I first used uniq and found it was not accessing the nested property correctly. 

I've noticed that many other methods use deep in their names when doing anything with nested properties. 

The docs have this, but I think others may find the alias to be useful. 

Thank you for replying so fast.
