### ISSUE TITLE
Proposal: More logic functions -- ifElse/when/unless

### ISSUE THREAD

**Issue by Silverwolf90** [lodash/lodash#2158]
Since we now have `_.cond` it might be good to add more logic functions. These would be particularly useful for people using `lodash/fp`

I would propose the following (names taken from Ramda):
* `_.ifElse(predicate, onTrue, onFalse, value)`
* `_.when(predicate, onTrue, value)`
* `_.unless(predicate, onFalse, value)`

`when`/`unless` return the result of calling `onTrue`/`onFalse` with `value` if the predicate is met/not-met, otherwise `value` is returned untouched.

**Comment by jdalton** [comment]
Thanks @Silverwolf90 for bringing these up. I added `_.cond` because it seemed like the most generic one (able to handle multiple cases). As with other requests we'll wait for user demand to pick up before including in core.

**Comment by Silverwolf90** [comment]
Sounds good. Let the lobbying begin! :D

A quick amendment as well, for the sake of consistency with `_.cond`, the `value` argument should be omitted and these functions should return a function which passes down any arguments to `predicate`/`onTrue`/`onFalse`

**Comment by jfmengels** [comment]
Sounds good :+1:

> the value argument should be omitted and these functions should return a function which pass down any arguments to predicate/onTrue/onFalse

:+1: for value being passed to all the fns. For it being omitted, it doesn't matter much since all fp methods are curried, but it might make more sense for vanilla Lodash (no opinion here)

@jdalton How do you actually feel about Lodash turning into a full-fledged fp library?

**Comment by jdalton** [comment]
> How do you actually feel about Lodash turning into a full-fledged fp library?

In prep for v4, to better accomidate incorporating the fp module, I moved the primary build closer in that direction. I still like the separation. We'll keep adding methods as needed though.

**Comment by guy-kdm** [comment]
+1 was looking for it! (logical functions and unless, when, fixedPoint ext.)

**Comment by guy-kdm** [comment]
@jdalton  Would you accept a PR?

**Comment by jdalton** [comment]
I'm waiting for there to be a bit more interest in the feature.

**Comment by guy-kdm** [comment]
👌

**Comment by dancras** [comment]
We've been exploring more functional concepts in our code lately, and the ability to compose conditional logic functionally shows good potential for some elegant, declarative code. Unfortunately the syntax to achieve what we have been doing using existing lodash functions is a little ugly:

```js
_.cond([
    [predicate, doSomething],
    [_.stubTrue, _.identity]
]);
```

We defined `_.condBranch` as a syntax improvement for the above. It was actually easy to define `_.cond` using `_.condBranch`, which seemed like a compelling case for the addition of this more general building block. The implementation can be seen here:

https://github.com/Casumo/lodash/tree/feature-cond-branch

There is probably a better name for it. Personally I think that `_.cond` is a better name for the single conditional branch, and today's `_.cond` would be more suitable as `_.condSwitch` or `_.condMatch`, as it is closer to a switch statement or a conditional matching statement. Perhaps `_.cond` could support both during a period of migration?

**Comment by chevin99** [comment]
Similarly, I was looking to find an alternative to `switch`, and have been using this lately a lot and I love it about as much as I love lodash and would love if it were part of lodash:
```
let value = 'case-3'

switchy(value, {
  'case-1': () => console.log('case 1'),
  'case-2': () => console.log('case 2'),
  'case-3': () => console.log('case 3'),

  default: () => console.log('default')
})

// logs 'case 3'
```
What that above would look like with the native `switch` statement:

```
let value = 'case-3'

switch(value) {
  case 'case-1': 
    console.log('case 1')
    break
  case 'case-2': 
    console.log('case 2')
    break
  case 'case-1': 
    console.log('case 3')
    break
  default:
    console.log('default')  
}
```


I got the idea from Joel Thoms here: https://hackernoon.com/rethinking-javascript-eliminate-the-switch-statement-for-better-code-5c81c044716d.  I modified the code from that page a bit to fit my preferences.  Here's how that `switchy` function is defined (that is used above):
```
const switchcase = (cases) => (defaultCase) => (key) => cases.hasOwnProperty(key) ? cases[key] : defaultCase
const execIfFn = (f) => f instanceof Function ? f() : f
const switchy = (key, cases) => execIfFn(switchcase(cases)(cases.default || undefined)(key))
```
