### ISSUE TITLE
_.isEmpty returns incorrect result with Sets

### ISSUE THREAD

**Issue by not-an-aardvark** [lodash/lodash#2159]
```js
var s = new Set();

_.isEmpty(s) // => true (as expected)

s.add('value');

_.isEmpty(s) // => true, even though the set is no longer empty
```

Even though a Set's keys aren't enumerable, the behavior is somewhat unintuitive because an "empty set" is typically defined as "a set with no elements".

**Comment by jdalton** [comment]
From the [_.isEmpty docs](https://lodash.com/docs#isEmpty):
> Checks if `value` is an empty object or collection. A value is considered empty if it's an `arguments` object, array, buffer, string, or jQuery-like collection with a length of `0` or has no own enumerable string keyed properties.

Since we don't support iterating sets they're seen as empty.

**Comment by jdalton** [comment]
On second thought we did just add support for sets/maps to `_.size`.

**Comment by not-an-aardvark** [comment]
I see, thanks for the clarification. I was looking at #737 (regarding treating Sets, WeakMaps, etc. as iterables), and I saw that the "wontfix" label was removed awhile ago. Would a PR to change _.isEmpty with Sets (or to treat Sets as iterable in general) be useful?
