### ISSUE TITLE
Suggestions for the Documentation

### ISSUE THREAD

**Issue by xhh2a** [lodash/lodash#2161]
There's a tremendous amount of methods in lodash/underscore. The documentation is getting hard to navigate. I think funcy's documentation (for python) is more navigable due to the organization into sequences/collections as well as sub-dividing each section into the purpose I'm looking for (unite, transform, select, etc).

I know there is a difference between Arrays, Collections, and Objects but from a usability standpoint it's hard to navigate because it means I have to look in different sections most of the time if I do not find what I want. For Collections and Objects I have to check both in order to find what I want. For Arrays I need to check all three and not all collections or object functions work on arrays as the name implies. I think it would be useful to merge collections and objects into a single section or find some way of allowing filters for what works with the object type.

Real example:
Before I found _.omit today (the first word that came to mind was 'without' but _.without acts only on Arrays) I thought to use _.reject (in collections section) with a iterator using _.has. This was not a pleasant searching experience. I originally thought of 'contains' or even using _.find because _.has was not in the top two sections. I finally found _.has after reading every function name from the top. It's a long read. It turns out _.has also works for arrays. Given that _.has is all the way down in the objects section it means that if I were to look for that behavior for an array I may not find it for quite a while.

Another improvement for the documentation would be the grouping or hiding of variations of the same function in the list (_.[command]By, [command]With, [command]Right, etc. etc.)

**Comment by jdalton** [comment]
You have opinions. That's great. However, if you're not willing to do the work it won't get done. Feel free to contribute over at https://github.com/lodash/lodash.github.io/issues/15.

**Comment by jdalton** [comment]
Erm https://github.com/lodash/lodash.github.io/issues/8
