### ISSUE TITLE
Wrong Sorting by _.orderBy of insensitive string values

### ISSUE THREAD

**Issue by kalimulhaq** [lodash/lodash#2162]
I am trying to sort an array by string values (insensitive) but it gives wrong result. First it sorts from **A to Z** and than **a to z**. 

My Code Is

```javascript
var arr = [
    {
      "count": 1,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "547de635e4b07709fd5cfb0c",
      "name": "Zong"
    },
    {
      "count": 2,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "54d0d2b6e4b0f29b1bb0eaac",
      "name": "ISNA Splash"
    },
    {
      "count": 2,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "547de615e4b07709fd5cfb0b",
      "name": "ufone"
    },
    {
      "count": 3,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "54cb4d8fe4b074b65f76e273",
      "name": "Coca Cola"
    }
  ]

arr = lodash.orderBy(arr, ["name","count"],  ["asc","asc"]);
```

RESULT is (Which  is Wrong)
```javascript
[
    {
      "count": 3,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "54cb4d8fe4b074b65f76e273",
      "name": "Coca Cola"
    },
    {
      "count": 2,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "54d0d2b6e4b0f29b1bb0eaac",
      "name": "ISNA Splash"
    },
    {
      "count": 1,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "547de635e4b07709fd5cfb0c",
      "name": "Zong"
    },
    {
      "count": 2,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "547de615e4b07709fd5cfb0b",
      "name": "ufone"
    }
  ]
```

Expected Result is 
name: "ufone" should come first from "name": "Zong"
```javascript
[
    {
      "count": 3,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "54cb4d8fe4b074b65f76e273",
      "name": "Coca Cola"
    },
    {
      "count": 2,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "54d0d2b6e4b0f29b1bb0eaac",
      "name": "ISNA Splash"
    },
   {
      "count": 2,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "547de615e4b07709fd5cfb0b",
      "name": "ufone"
    }
    {
      "count": 1,
      "type": "EXPO_VENDOR_DETAIL",
      "vendorId": "547de635e4b07709fd5cfb0c",
      "name": "Zong"
    },
  ]
```

If I convert all names to lower case than it works fine.

**Comment by jdalton** [comment]
It sounds like you're wanting a [natural sort order](https://en.wikipedia.org/wiki/Natural_sort_order) which is a bit more involved then our [ascending comparison](https://github.com/lodash/lodash/blob/4.6.1-npm/_compareAscending.js).

**Comment by jdalton** [comment]
An example implementation of a natural sort comparator can be found [here](https://github.com/jdalton/docdown/blob/0.5.0/lib/util.js#L13-L41).

**Comment by arthurkirkosa** [comment]
Is there a way to use natural sort in `orderBy` or `sortBy`?

**Comment by jdalton** [comment]
@arthurkirkosa No.

**Comment by johannes-z** [comment]
How can this be with `_.orderBy` and multiple columns? Basically `_.orderBy` would need some way to override the built in comparator with the natural sort one you posted.

## Example

```js
        rows = _.orderBy(rows, orders.columns.map(column => {
          return row => {
            let value = row[column]
            return value != null ? value.toString().toLowerCase() : ''
          }
        }), orders.directions)
```

**Comment by econic** [comment]
Basically you should be able to pass a custom comparator to sortBy / orderBy, right?

**Comment by travisdahl** [comment]
At the least, a  parameter to be case insensitive would be nice! Ran into this today.

**Comment by rubanraj54** [comment]
Hi all, 

@johannes-z solution was perfect and it's only working if we access the attributes from top level in the object, and it doesn't work if the attribute is nested inside an object.

For example, if i want to sort based on `first_name` which is inside a `name` then it doesn't work.

```
let row = {
  name: {
   first_name: "ruban"
  }
}
```

I will update @johannes-z solution in my answer. 

```
rows = _.orderBy(rows, orders.columns.map(column => {
  return row => {
    let value = _.get(row,column)
    return value != null ? value.toString().toLowerCase() : ''
  }
}), orders.directions)
```

Instead of accessing `row[column]`, I used lodash _.get() method to access the nested attributes too.

This may help someone (like me) who want to sort a column which is nested inside another object.

Cheers
Ruby.

**Comment by siebmanb** [comment]
Be careful @rubanraj54  your code will sort number by their first digit, then second etc. So 3 will be after 22... The `toString` needs to be applied only on strings
