### ISSUE TITLE
_.startCase changes - lowering cases

### ISSUE THREAD

**Issue by meirotstein** [lodash/lodash#2163]
Hello,

We have recently upgraded lodash from 3.1.0 to 4.6.0 and find out a significant behavior changes with _.startCase:
 
in 3.1.0:
`_.startCase('QwErty') //Qw Erty`
`_.startCase('QWErty') //QW Erty`
In 4.6.0
`_.startCase('QwErty') //Qw Erty`
`_.startCase('QWErty') //Qwerty` --> CHANGE

I haven't seen any note about it for any version on the [Changelog](https://github.com/lodash/lodash/wiki/Changelog) page

Is startCase should lower the other cases as well?

anyhow, if that by design, is there any suggestion for keeping the old behavior?

Thanks

**Comment by jdalton** [comment]
This is a bug. It's been patched in our master branch here https://github.com/lodash/lodash/commit/9735961090f6f4d1c404246c1fce55efe02fa2cb.

**Comment by meirotstein** [comment]
Hi,

Thanks!

However this change fixes only the lowering cases issue - there's still some inconsistency with this utility behavior.

For instance:

`_.startCase('QWerty') //QWerty`
VS
`_.startCase('QWertyQWerty') //Q Werty Q Werty`
`_.startCase('qWERTy') //Q WER Ty`

it is not clear what this command behave with two or more capital trailing letters - if it comes only on the beginning of the word it does nothing, while if there's any additional capital anywhere else it split it into several words.

Thanks.

**Comment by jdalton** [comment]
Ah nice. Patched too!

**Comment by meirotstein** [comment]
:+1: 
Thanks!
