### ISSUE TITLE
Async version of _.attempt

### ISSUE THREAD

**Issue by Alexsey** [lodash/lodash#2165]
Since ES7 would probably contain `async/await` pattern it would be nice to have a version on `_.attempt` that would work with it. For example
```
const response = await _.attemptAsync(makeRequest, requestOptions)
if (_(response).isError()) return console.error('Fail to request:', response)
const responseData = response.map(......)
```
In practice this means that `_.attemptAsync` returns a `Promise` that will never be rejected and resolve with either result or error

I understand that it may be a little bit early for such feature, but may be you may consider it for future versions

**Comment by jdalton** [comment]
Ya, for async helpers I'm inclined to defer to [async](https://github.com/caolan/async).
We'll keep tabs on the request though.

**Comment by pnedelko** [comment]
+1 for this feature

**Comment by dpikt** [comment]
Ended up writing this locally for a project.
```js
async function attemptAsync (func, ...args)  {
  try {
    return await func(...args)
  } catch(e) {
    return e
  }
}

// Usage
const dataOrError = await attemptAsync(async () => { ... })
```

**Comment by arash-bizcover** [comment]
@jdalton still not interested in adding this to lodash ?

**Comment by JamesGelok** [comment]
It's too bad that attempt hangs forever if a Promise is rejected, but lodash doesn't handle promises at the time of writing :(

For anyone else who stumbles upon this while trying to make `async/await` error handling clean:

<details><summary>I ended up trying @dpikt's solution but with Typescript types.</summary><br/>

<pre lang="typescript">
export function attemptAsync&lt;T extends (...args: any) =&gt; any&gt;(
  func: T,
  ...args: Parameters&lt;T&gt;
): ReturnType&lt;T&gt; | Error {
  try {
    return func(...args)
  } catch (e) {
    return e as Error
  }
}
</pre>

</br></details>

But, after reading the MDN documentation I realized I can have clean `async/await` error handling in TypeScript like this:

```ts
  const val = await sleep(1234).catch<Error>(_.identity)
  if (_.isError(val)) return console.log("IT WAS AN ERROR :(", val)
```

Full example below:

```ts
import _ from "lodash"

const sleep = (milliseconds) =>
  new Promise<"sleep">((resolve) => setTimeout(() => resolve("sleep"), milliseconds))
const die = (milliseconds) =>
  new Promise<void>((__, reject) => setTimeout(() => reject(new Error("die")), milliseconds))

async function main() {
  console.log("trying")

  const val = await sleep(1234).catch<Error>(_.identity)
  if (_.isError(val)) return console.log("IT WAS AN ERROR :(", val)

  console.log("no error found :)", val)
}
```
