### ISSUE TITLE
maybe a bug of _.trim

### ISSUE THREAD

**Issue by dd1994** [lodash/lodash#2167]
I find that `_.trim('img-cli.git', '.git')` return `img-cl`, but it shuld return `img-cli`
here is demo on the jsbin:

<a class="jsbin-embed" href="http://jsbin.com/qepahoquko/embed?js,console">JS Bin on jsbin.com</a><script src="http://static.jsbin.com/js/embed.min.js?3.35.11"></script>

**Comment by jdalton** [comment]
The `chars` param is a string of chars (individually) to remove not a pattern to remove.
