### ISSUE TITLE
Feature request: Implement a rotate function

### ISSUE THREAD

**Issue by jpleclerc** [lodash/lodash#2173]
I'm not sure how it should be implemented in Lodash but it would probably look like that:

Rotate to the left:
```
function rotateLeft(array, steps = 1){ ... }
rotateLeft(['a','b','c'], 1);
// Result: ['b','c','a']
```

Rotate to the right:
```
function rotateRight(array, steps = 1){ ... }
rotateRight(['a','b','c'], 1);
// Result: ['c','a','b']
```

**Comment by jdalton** [comment]
Thanks @jpleclerc! We'll [keep an eye on demand](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) for this kind of method.

**Comment by gabrielstuff** [comment]
Specs look perfect :)

**Comment by jpleclerc** [comment]
@jdalton I am curious, how many upvotes is enough to give this FR the "sufficient interest" status. I would be interested in making a PR if you tell me that it wont be discarded.

**Comment by jdalton** [comment]
@jpleclerc 
There isn't a concrete number though I can say at moment the current 4 upvotes isn't quite enough.

**Comment by jfmengels** [comment]
Would it make sense to have only 1 `rotate` method which would rotate left or right based on whether `steps` is positive or negative (right and left respectively probably)?

**Comment by gabrielstuff** [comment]
Yup
Le lun. 18 avr. 2016 à 21:34, Jeroen Engels <notifications@github.com> a
écrit :

**Comment by StreetStrider** [comment]
This looks like a `cycle` («to cycle»). `rotate` is more a matrix thing (zip/unzip/transpose, #645).

**Comment by jpleclerc** [comment]
@jfmengels I agree

**Comment by gabrielstuff** [comment]
So how would one do simple rotateLeft / rotateRight with transformation matrix and transpose ? Even if it is easy to do, a short-handler such as `_.rotate(Array, K)` or `_.cycle(Array, K)` would be nice. The matlab function is pretty : http://fr.mathworks.com/help/matlab/ref/circshift.html

**Comment by StreetStrider** [comment]
@gabrielstuff, you are right, you can't circle rotate array with `rotate`. My concerning was just about the naming. My statement was `rotate` is more approp for matrices. `cycle` is better (imo). `circshift` is a good one too (imo), very descriptive.

**Comment by jpleclerc** [comment]
@StreetStrider I am not against `cycle` since it makes mathematically more sense. But, personally, when I looked for this feature on Google, I searched for "how to rotate an array with lodash" . If you compare the results in google between "rotate array" and "cycle array", you will see that rotate seems to be the term people are looking for.

**Comment by sanex3339** [comment]
+1 for this feature

**Comment by tedeh** [comment]
This has been closed, but for anyone else coming here it's a pretty simple operation: `arr.unshift(arr.pop())` rotate right and `arr.push(arr.shift())` to rotate left.
