### ISSUE TITLE
SortBy, OrderBy string comparison

### ISSUE THREAD

**Issue by Duskfall** [lodash/lodash#2174]
Hello,
I have a case where the sorting doesn't work properly, or perhaps i am doing something wrong
Use case:

`_.orderBy(['10','3','2'])`
`_.sortBy(['10','3','2'])`

Should return ['2','3','10'] but returns ["10", "2", "3"]

`_.orderBy(['10','3','2'],[],['desc'])`

Should return ['10','3','2'] but returns ["3", "2", "10"]

**Comment by demoneaux** [comment]
Since you want to compare them by numbers, you should do `_.orderBy(data, Number, ['desc'])`, otherwise they will be sorted as strings using their character codes.

**Comment by Duskfall** [comment]
Yup tested and it works thanks!

**Comment by greggootz** [comment]
Thanks for the help!

Just small example if your data is a collection:

`var orderedCollection = _.orderBy(unOrderedCollection, [{'KEYtoSort': Number}], ['desc'])`

Good luck!

**Comment by ayozebarrera** [comment]
@greggootz can't see it on documents... where do you found it?

**Comment by cody-elhard** [comment]
@greggootz I am unable to replicate these results...

![screen shot 2018-08-09 at 10 19 59 am 2](https://user-images.githubusercontent.com/32208000/43908500-cba907f4-9bbd-11e8-9705-7bd28e1af023.png)

**Comment by mfauzaan** [comment]
@cody-elhard here is working alternative to solve your problem.

`var orderList = _.orderBy(collection, function (o) { return new Number(o.objectKey); }, ['desc'])`
