### ISSUE TITLE
Unexpected behaviour between 3.x and 4.x

### ISSUE THREAD

**Issue by jamlen** [lodash/lodash#2178]
From reading the change log and the deprecation wiki page, I need to change `_.any(_.where(values, expected))`  to `_.some(_.filter(values, expected))` but this does not give the same behaviour:

### v3.10.1
```js
var values = [['a', 'b', 'c'], 123];
var expected = ['a', 'b'];
_.any(_.where(values, expected)); // -> true
```
### v4.6.1
```js
var values = [['a', 'b', 'c'], 123];
var expected = ['a', 'b'];
_.some(_.filter(values, expected)); // -> false
```

Is there something else I should be doing?

**Comment by jdalton** [comment]
In v4 the methods accept a [matchesProperty](https://lodash.com/docs#matchesProperty) shorthand which is `[propName, value]` as an alternative to the common case of `{ propName: value }`.

**Comment by jdalton** [comment]
Passing an array as the `_.matches` source isn't ideal as it will lock to the index values so for example:
```js
// 3.10.1
var values = [['b', 'a', 'c'], 123];
var expected = ['a', 'b'];
_.any(_.where(values, expected)); // false
```
