### ISSUE TITLE
New math method - Mode

### ISSUE THREAD

**Issue by SHAHRUKH-KHAN** [lodash/lodash#2184]
I would like to add a new method: Mode, which would calculate the mode of a collection.

**Comment by jdalton** [comment]
Thanks for the request @SHAHRUKH-KHAN!
We'll keep an eye on user demand. (be sure to upvote with the :+1: reaction).

Related to #2182.

**Comment by jfmengels** [comment]
Not sure what a mode is, but for consistency you might want a `modeBy` function too.

**Comment by SHAHRUKH-KHAN** [comment]
@jfmengels mode is the maximum number of occurrences of a number in an array.
eg -> _.mode([1,1,2,2,3,3,3,3]) should give you [3].

**Comment by StreetStrider** [comment]
@SHAHRUKH-KHAN, in your example you got 2 of ones, 2 of twos and 4 of threes, so mode = `4`, why is it `[3]`?

**Comment by SHAHRUKH-KHAN** [comment]
@StreetStrider sorry My Bad ! . The number which has the highest frequency is the `mode`

**Comment by SHAHRUKH-KHAN** [comment]
@jfmengels We can have `_.modeBy` too.

**Comment by arieljake** [comment]
could we also add median while we are at it?

**Comment by SHAHRUKH-KHAN** [comment]
@arieljake Surely we can ! 
First let this one go through :)

**Comment by jpleclerc** [comment]
Why not add a statistic module? It would contain things like variance, standard deviation, coefficient of variation, mean, mode, median, trimmed mean...

**Comment by jfmengels** [comment]
Wondering whether the method should be called `mode` or something like `mostCommon`. A few reasons:
- `mode` might be the appropriate statistical/mathematical name, but it's not meaningful to me. For the same reason, I would never search for `mode` if I searched for this functionality (it's not even a problem with English, the same word is used for the same thing in my native language).
- Having `_.mode` will pretty much lead to having a `_.modeBy`, which should probably return the first item whose `iteratee` value is the "mode".
Example:
```js
var votes = [
  {nominee: 'future president'},
  {nominee: 'future president'},
  {nominee: 'future president'},
  {nominee: 'future president'},
  {nominee: 'not future president'},
  {nominee: 'not future president'},
  {nominee: 'not future president either'}
];
_.modeBy(votes, 'nominee');
// => {nominee: 'not future president'},
```
But in this case, since it's not a number, it's not a `mode` really. Even for `_.mode`, it should probably work for other primitives like strings (otherwise the functionality is pretty limited...), which is also not a number.

Btw, would still like to know what use cases you see for this functionality. There seems to be some demand, so I'm curious.

**Comment by SHAHRUKH-KHAN** [comment]
@jfmengels 
```
_.modeBy(votes, 'nominee');
// => {nominee: 'future president'}
```

Let's say you are a finance manager of a company and want to know which product of your company was sold the most.You have the data for ten years for hundreds of products. 
I guess, `mode` will come handy, helping you to figure out the demand.
There is a possibility that you maintain a record that how much a particular product sold and from there you pick up the max value.
But what if there are two products with same sales figure and you want to pull them out, I guess `_.modeBy()` can come handy.
What do you think ?

**Comment by jfmengels** [comment]
@SHAHRUKH-KHAN Thanks, sounds good.

**Comment by SHAHRUKH-KHAN** [comment]
@jdalton  
Should I continue to work on it as of now ?

**Comment by jdalton** [comment]
There's no urgent need until more votes come in. But if you want to kick something around in your own fork/branch or proof out a mixin or mixin package that's great.

**Comment by jrencz** [comment]
I missed this report and I filed my own. I did some digging and came up with a good-enough solution (see #2284). Maybe someone will benefit from it until `_.mode` and `_.modeBy` find their way to the lodash core.

**Comment by abibell** [comment]
Plus +1 from me. Most commonly used statistical functions - mode, median, variance and standard deviation are missing. We can include their "By" variants.

**Comment by arieljake** [comment]
I recognize the ...By pattern but would modeOf make more sense?

**Comment by drico** [comment]
+1, definitly missing this kind of statistics methods

**Comment by lenjoseph** [comment]
Here is a potential implementation to return modes of arrays of primatives for both single-mode and multi-mode cases:

```
const modeBy = (arr) => {
    let instanceCounts = arr.reduce((a, c) => {
        a[c] = (a[c] || 0) + 1;
        return a;
   }
   let maximumCount = Math.max(...Object.values(instanceCounts));
   let mode = Object.keys(instanceCounts).filter(item => 
       instanceCounts[item] === maximum
   );
   return mode;
}
```
