### ISSUE TITLE
4.7.0 does not work with latest Firefox

### ISSUE THREAD

**Issue by juliusosokinas** [lodash/lodash#2185]
The console outputs: `TypeError: Function.prototype.toString called on incompatible object.`

**Comment by mitrae** [comment]
confirm

**Comment by jdalton** [comment]
I can't repro.

We test in Firefox 45 and [it's passing](https://saucelabs.com/u/lodash) I've confirmed locally that tests pass in FF 45.

**Comment by jdalton** [comment]
Tests pass in Firefox Nightly (48) too.

**Comment by jdalton** [comment]
Are you using some kind of es6/7 shim on your page?

**Comment by juliusosokinas** [comment]
Firefox 37.0.2 on OS X 10.11.3 throws when running this:

https://plnkr.co/edit/RSMyVtNxpt89V0iDEqxa

This results in any other scripts to break.

See the screen shot taken with 4.6.1:
![4.6.1](https://cloud.githubusercontent.com/assets/7352358/14179791/5ce96d4c-f758-11e5-960a-0227f289ec97.png)

And with 4.7.0:
![4.7.0](https://cloud.githubusercontent.com/assets/7352358/14179775/4b91b4aa-f758-11e5-96ca-8b040690ff1c.png)

**Comment by jdalton** [comment]
Ah thanks. Firefox 37 is over a year old and outside our support range. I'll still look into it though.

**Comment by jdalton** [comment]
Looks like Firefox 37 will error in a web worker only when attempting to coerce the `Promise` function to a string.

**Comment by juliusosokinas** [comment]
I don't use Firefox myself, so was surprised it didn't auto update itself to 45 (or any other from 37). However, manually installing the latest version on my local machine solved the problem.

**Comment by jdalton** [comment]
Cool. I'll add a try-catch around the check in `isNative` for the next release.

**Comment by jdalton** [comment]
https://github.com/lodash/lodash/commit/f953d34c7b422aeb09fa4427932692e045ef18ad

**Comment by puzrin** [comment]
@jdalton just for info: such problem breaks testing with `slimerjs` (headless FF, alternative to phantomjs) and is critical enougth.

**Comment by redonkulus** [comment]
@jdalton when is the next release scheduled to go out?

**Comment by uevilwizard** [comment]
I'm seeing this error in FF 42.

**Comment by jdalton** [comment]
Folks it's been patched.

**Comment by jdalton** [comment]
The next release will go out in a day or so.
