### ISSUE TITLE
_.unset doesn't work with Array of paths

### ISSUE THREAD

**Issue by knicefire** [lodash/lodash#2186]
In the documentation it is said that we can pass either string or an array

```javascript
/**
 * @param {Array|string} path The path of the property to unset
 */ 
```
So I expect the following code should work fine
```javascript
_.unset(response, sensitiveProps);
```
but the properties remain

When I explicitly iterate over the array it works just fine

```javascript
sensitiveProps.forEach((prop) => _.unset(response, prop));
```

Example:
```javascript
const sensitiveProps = ['user.email', 'user.phone'];
const response = {user: {name: 'Joe', email: 'joe@example.com', phone:'+2123123'}};

_.unset(response, sensitiveProps);

// > response
{ user: { name: 'Joe', email: 'joe@example.com', phone: '+2123123' } }

sensitiveProps.forEach((prop) => _.unset(response, prop));

// > response
{ user: { name: 'Joe' } }
```

So either it's a bug, or typo in documentation, or I just didn't get it right

**Comment by jfmengels** [comment]
The path can be an array, but not in the sense that you expect: the path, when as an array, is a an array of strings/numbers that describe a path (look at the [`_.toPath`](https://lodash.com/docs#toPath) doc to see what it's like).

```js
_.unset({ user: { name: 'Joe', email: 'joe@example.com', phone: '+2123123' } }, 'user.email');
// => { user: { name: 'Joe', email: 'joe@example.com' } }

// equivalent to

_.unset({ user: { name: 'Joe', email: 'joe@example.com', phone: '+2123123' } }, ['user', 'email']);
// => { user: { name: 'Joe', email: 'joe@example.com' } }
```

What you were doing was equivalent to unsetting the value at `value['user.email']['user.phone']`.

In your case, using a forEach is the right solution I think.

**Comment by knicefire** [comment]
I see. Thanks a lot for the explanation. That makes much more sense to me now. 
I'd guessed that I'd had misunderstood the documentation.

**Comment by jdalton** [comment]
I'll add a doc example with `path` as an array.

**Comment by jdalton** [comment]
https://github.com/lodash/lodash/commit/5121d6ebd63e310f5c22066597c07972d30c2d3d
