### ISSUE TITLE
Deep Find

### ISSUE THREAD

**Issue by shanimal** [lodash/lodash#219]
I am looking for a key ("dateCreated") someplace in a huge object. _.find only seems to work up to one nested level deep. and it only returns the first instance. I'd like to have a function that works similar to the way xpath did returning an array of references to all objects containing that key within the collection.
```js
_.find({ 'a': 1, 'b': 2, 'c': {'d':{'e':7}}}, "d"); // Object {d: Object}
_.find({ 'a': 1, 'b': 2, 'c': {'d':{'e':7}}}, "e"); // undefined
_.find({ 'aa': 1, 'bb': 2, 'cc': {'d':{'x':9}}, dd:{'d':{'y':9}}}, 'd'); // Object {d: Object} d: Object x: 9
```
1) it seems strange that _.find found something one level deep (i.e o.c.d) but couldn't find something two levels deep (i.e. `o.c.d.e`) 
2) how do i find additional instances of 'd' (i.e. `cc.d`, `dd.d`...)
OR can i get an array instead (e.g. `[cc.d, dd.d]`)

I ran a quick test against 1.1.0
http://codepen.io/anon/pen/bnqyh

As usual big props for an awesome library. Fanboy here, spreading the word. Thanks!

**Comment by xfg** [comment]
@jdalton I try to use `_.where` style callback but seem it doesn't work with arrays. My example

```javascript
const post = {
  id: 1,
  comments: [
    {
      id: 1,
      author: {id: 1}
    }
  ]
};

_.find(post, {author: {id: 1}}); //undefined
```

How to solve this issue?

**Comment by jdalton** [comment]
@xfg For support questions visit [our gitter chat](https://gitter.im/lodash/lodash).

**Comment by usman250994** [comment]
I have created a package/ function which can search deep down in nested Object or in array of nested Objects. and returns the required key/s and value/s. as a new object.  Please have a look to it.  
https://www.npmjs.com/package/uas-get-my-keys
https://github.com/usman250994/getMyKeys
