### ISSUE TITLE
lodash 4.7.0 _.has returns true for null nested object values

### ISSUE THREAD

**Issue by nkhoshini** [lodash/lodash#2190]
In lodash 4.7 the following returns true
```javascript
_.has({a:null}, 'a.b.c');
```

Whereas in 4.6.1, it'll return false as expected.

It looks like the null object exits out of the hasPath function successfully:
https://github.com/lodash/lodash/blob/master/lodash.js#L5356

```javascript
while (object != null && ++index < length) {
  var key = path[index];
    if (!(result = hasFunc(object, key))) {
      break;
    }
    object = object[key];
}
```

Adding this after the while loop could catch the case in which the null sub-object falls through the cracks:
```
result = result && (object || index == length);
```

**Comment by jdalton** [comment]
Ewww super gross. We'll release a patch fix this evening.
