### ISSUE TITLE
TypeError: Function.prototype.toString called on incompatible object

### ISSUE THREAD

**Issue by georgespyropoulos** [lodash/lodash#2191]
Hi,

I'm running lodash v4.7 and received the following error using Firefox v43.

`TypeError: Function.prototype.toString called on incompatible object`

The error occurred at this line of code:  https://github.com/lodash/lodash/blob/master/dist/lodash.js#L10842

The error can be triggered simply by loading lodash in Firefox v43.

I am not experiencing the error in latest version of Firefox (v45) and the error is not present in lodash 4.6.

Please let me know if you would like any further details.

Thanks.

**Comment by jdalton** [comment]
Dup of #2185.
