### ISSUE TITLE
Add iterator to filter doc

### ISSUE THREAD

**Issue by aug-riedinger** [lodash/lodash#2192]
I just tried to write:

```
_.filter([1, 0, 2, 5, 3, 9], function(n, i) { return i%2});
```
and it worked. Why not mentioning (though guessable I agree) in the doc that the `i` is the second argument of the function?

**Comment by demoneaux** [comment]
The [docs state that](https://lodash.com/docs#filter)

  > The predicate is invoked with three arguments: `(value, index|key, collection)`.

**Comment by aug-riedinger** [comment]
Correct. Sorry about that, I did not see this.

But maybe adding it in the examples would help (unless this is not an encouraged use):

```
_.filter(users, function(o, index) { return !o.active; });
```

**Comment by jdalton** [comment]
Naw, it's documented. Anything more is redundant.
