### ISSUE TITLE
_.set using a string (that is a number) is broken

### ISSUE THREAD

**Issue by yawhide** [lodash/lodash#2198]
`var l = require('lodash')`

actual:
```
> o={}
{}
> l.set(o, 'foo.2', 5)
{ foo: [ , , 5 ] }
```

expect:
```
> o={}
{}
> l.set(o, 'foo.2', 5)
{ foo: { '2': 5 } }
```

you can crash node if you do:
```
> o={}
{}
> l.set({}, ['x', '1234567890'], 1)`
** node crashes ** as its trying to set an array that is 1234567890 large
```

**Comment by jdalton** [comment]
See the [_.set](https://lodash.com/docs#set).

**Comment by yawhide** [comment]
solution:
use [_.setWith](https://lodash.com/docs#setWith)

**Comment by jfmengels** [comment]
(sorry, out of context, but) @yawhide you might want to try https://github.com/borisdiakur/n_ to have a REPL containing Lodash as `_`

**Comment by StreetStrider** [comment]
@jfmengels, my [REPL](https://www.npmjs.com/package/repl.js) is way better.
