### ISSUE TITLE
Fix functional comparisons

### ISSUE THREAD

**Issue by bben86** [lodash/lodash#2199]
I would expect the following to be true:

    import {some, gt} from 'lodash/fp';
    let anyPositive = some(gt(0));
    expect(anyPositive([1, 0, 0]), true);

However, it doesn't work for me.  Is this a bug or bad expectations?

**Comment by jdalton** [comment]
`gt` is `(a,b)` so you'll want to do
```js
let __ = gt.placeholder;
let anyPositive = some(gt(__,0));
```
or
```js
import {some, _gt} from 'lodash/fp';
let gt = _gt.convert({ 'rearg': false });
let anyPositive = some(gt(0));
```

**Comment by jdalton** [comment]
Erm that's `_gt.convert({ 'rearg': true })`
