### ISSUE TITLE
_.where collection filter function

### ISSUE THREAD

**Issue by tbranyen** [lodash/lodash#22]
The `_.where` method accepts a collection of objects and based on a key: value object, a shallow copy match is returned.  This is used in the case where you have a filter function that is only ever checking a `key=>val` match.

``` javascript
var people = [
  { name: "Tom", age: 19 },
  { name: "John". age: 3 },
  { name: "Seven", age: 37 },
  { name: "John", age: 42 }
];
```

The arguments are a collection of objects and an object literal to compare:

``` javascript
var seven = _.where(people, { name: "Seven" });
```

While the above example shows a single key, val filter you can also combo:

``` javascript
var littleJohn = _.where(people, { name: "John", age: 3 });
```

If no match is found, return `null`.  If multiple objects are found, return an Array.

**Comment by sgarbesi** [comment]
@jdalton Is it possible to do a multi-value where without having to write a manual loop?

Ex:

```javascript
var people = [
  { name: "Tom", age: 19 },
  { name: "John". age: 3 },
  { name: "Seven", age: 37 },
  { name: "John", age: 42 }
];

_.where(people, {
  name: ['Tom', 'John']
});
```

Results being the 1st, 2nd and 3rd members of the Array?

**Comment by jdalton** [comment]
> Is it possible to do a multi-value where without having to write a manual loop?

Not with the `_..matches` shorthand as that would try to match an array value. You'd have to create a callback and use `_.filter`.

**Comment by martinburch** [comment]
@sgarbesi and anyone else seeking example code:

```javascript
var people = [
  { name: "Tom", age: 19 },
  { name: "John", age: 3 },
  { name: "Seven", age: 37 },
  { name: "John", age: 42 }
];

var filtered_people = _.filter(people, function(p){
  return _.includes(['Tom', 'John'], p.name);  
});

console.log(filtered_people); // Array[3]
```
