### ISSUE TITLE
isNan behaviour different from native isNan

### ISSUE THREAD

**Issue by AJamesPhillips** [lodash/lodash#2200]
> _.VERSION
    "4.7.0"
    > _.isNaN(new Date('asdf'))
    false
    > isNaN(new Date('asdf'))
    true

Not sure if this is a bug or intended behaviour (as with most `isNaN` questions! :P )

**Comment by jdalton** [comment]
Look to the docs for [_.isNaN](https://lodash.com/docs#isNaN). Our `_.isNaN` is implemented like [Number.isNaN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN).
