### ISSUE TITLE
4.8.0 [overEvery] Seems to have a regression

### ISSUE THREAD

**Issue by Grobim** [lodash/lodash#2202]
Hello, I'm having an issue with the last version of lodash (4.8.0) expecially with the overEvery method.

The provided plunkr shows the different behaviours :

in 4.7.0 : http://plnkr.co/edit/nEgkg8?p=preview
in 4.8.0 : http://plnkr.co/edit/My6cuX?p=preview

(everything happens in the console)

In 4.7.0 we can see that the filtering is happening as intended, I get first the items with lbl === 'A', then with the color === 'blue', and finally the both combined.

But in 4.8.0, every calls return an empty array.

In both plunkr, the only DELTA is the url from the cdn.

Anyway, thanks for your awesome work, I use lodash everyday and I love it.

Best regards,
Nico

**Comment by Grobim** [comment]
Seeing the doc, I can see that the arguments changed

from 
predicates (...(Function|Function[])): The predicates to check.

to 
predicates (...Function): The predicates to check.

I think you should add this as breaking changes in your changelog.

+

Can you please provide an example of how I can deal with my use case ? (I can't ES2015, with the **... spread** and the filters are added dynamically)

Regards,
Nico

**Comment by Grobim** [comment]
May I know why is my issue invalid ?

**Comment by jdalton** [comment]
It was a by design change and you found a workaround. The fix that causes this issue was a little aggressive, I'll see if we can work back in the old behavior.

**Comment by Grobim** [comment]
Ok I see, thanks !

(please don't forget to mention the breaking change in the changelog, I advertised this function passing a Function[] in many kata/dojo/teams I played/worked with ^^)

Regards,
Nico

**Comment by jdalton** [comment]
Reverted https://github.com/lodash/lodash/commit/c2073cd635f840d11ff257d061685741f592c3b3.
