### ISSUE TITLE
syntax error in `lodash/fp/_falseOptions.js`

### ISSUE THREAD

**Issue by SpainTrain** [lodash/lodash#2204]
After updating to lodash 3.8.0, I am receiving `Line 7: Unexpected token )` in `lodash/fp/_falseOptions.js`.  `cat`ing the file, the syntax error is apparent:

```
$ cat node_modules/lodash/fp/_falseOptions.js
module.exports = {
  'cap': false,
  'curry': false,
  'fixed': false,
  'immutable': false,
  'rearg': false
});
```

**Comment by jdalton** [comment]
Bumped 4.8.1 to fix this. Sorry about that I missed it while testing.
