### ISSUE TITLE
Feature request: fp.assign should have arguments reversed

### ISSUE THREAD

**Issue by bgerstle** [lodash/lodash#2205]
## Use case
Using `fp.assign` to create helper functions which assign key/value pairs to objects, e.g. `assignFoo` which assigns the `foo` field of an object to `'bar'`:

```
> var assignFoo = fp.assign({foo: 'bar'})
```

### Expected/desired behavior
Being able to use partial function in compositions to assign desired value to new objects: `readJSON('foo.json').then(assignFoo);`

### Actual/current behavior
Partial function returned by `fp.assign` assigns 2nd argument to the first, not the other way around.  In this case, `assignFoo` actually assigns its argument to `{foo: 'bar'}`:

```
> assignFoo({baz: 'buz'})
{ foo: 'bar', baz: 'buz' }
> assignFoo({foo: 'baz'})
{ foo: 'baz' }
```

**Comment by jdalton** [comment]
Yeah the arg order is totally debatable. We went with what was established by existing FP libs.
You can customize it though:
```js
var assign = require('fp/assign').convert({ 'rearg': true });
```

**Comment by jfmengels** [comment]
Or use
```js
var assignFoo = _.assign(_, {foo: 'bar'})
```

If it's just setting a field, you can also use `_.set` for the same purpose.

**Comment by bgerstle** [comment]
Thanks everyone! @jfmengels forgot about the magic placeholder, but would that need to be `fp.assign`, or would `_.assign` return a function in that case?

**Comment by jfmengels** [comment]
That would be `fp.assign`, no extra magic with vanilla Lodash ;)

**Comment by billyjanitsch** [comment]
@bgerstle you can also use `_.defaults` for this case. (The idea of the convention is that the data structure *is* the default object.)

**Comment by jdalton** [comment]
Really digging the Lodash community pitching in here:
[](http://www.reactiongifs.us/wp-content/uploads/2014/01/thumbs_up_cat.gif)

**Comment by jdalton** [comment]
Would one of you all edit the [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide) wiki to add a section on placeholders. Don't worry about modifying the jst doc template.

**Comment by jfmengels** [comment]
I've added [one](https://github.com/lodash/lodash/wiki/FP-Guide#placeholders). I'm not sure I convey the message properly, but at least people will be able to build on it ;)
