### ISSUE TITLE
Bower.json

### ISSUE THREAD

**Issue by HarelM** [lodash/lodash#2206]
Hi,
Can you please add a bower.json file?

**Comment by jdalton** [comment]
Hi @HarelM!

With v4 we pulled explicit Bower support. Because Bower works on tags though things will still work.

**Comment by HarelM** [comment]
I'm new to bower etc, I'm trying to make it work with bower-installer in order to copy the relevant files to my js folder, in this case all files are copied instead of just the relevant.
Should I be using another tool?

**Comment by jdalton** [comment]
You'll get a few extra files yes but that shouldn't matter the paths to the `dist/` folder would be th same.

**Comment by HarelM** [comment]
I don't want to extra files, I want it neat. but that's just my OCD speaking. :-)
I need to invest some time in studying bower, npm and all this mess...
Thanks for the help.

**Comment by bcardiff** [comment]
Having a bower.json will also please rails-assets.org
If someone include lodash as exposed in https://rails-assets.org/#/components/lodash you get

```
$ bundle install
...
This component doesn't define main assets in bower.json.
Please open new pull request in component's repository:
https://github.com/lodash/lodash
```

This is not a blocker issue though.

**Comment by jdalton** [comment]
Hi @bcardiff!

Bower has been superseded by [yarn](https://yarnpkg.com/).
