### ISSUE TITLE
invalid metas found when attempting to install using bower

### ISSUE THREAD

**Issue by wschmrdrNS** [lodash/lodash#2208]
bower update was run on an application using lodash, and the following was seen:

bower lodash#4.8.2                   invalid-meta lodash is missing "main" entry in bower.json
bower lodash#4.8.2                   invalid-meta lodash is missing "ignore" entry in bower.json

I recall also seeing this on a version of the application that uses lodash 4.6.1, but I don't know the true origin of the issue.

**Comment by jdalton** [comment]
Lodash doesn't explicitly support Bower. Bower works because it's based on git tags.
