### ISSUE TITLE
Is there a nested keys function?

### ISSUE THREAD

**Issue by eyphka** [lodash/lodash#2210]
In other words, is there a function which takes an object, e.g.
```js
var foo = {
  bar: {
    zee: [
      {
         dee: 1
       }
    ],
    shee: 2
  }
};
```
and returns
```js
{'foo.bar.zee[0].dee': 1, 'foo.bar.shee': 2}
```

**Comment by jdalton** [comment]
Hi @eyphka!

There isn't, but we'll keep an eye on [demand for one](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
