### ISSUE TITLE
fp.lt argument order not reversed

### ISSUE THREAD

**Issue by olsonpm** [lodash/lodash#2211]
According to the [FP-Guide](https://github.com/lodash/lodash/wiki/FP-Guide#fixed-arity)

> Methods with a fixed arity of two:
> ...
> `lt`

along with the [rearranged arguments](https://github.com/lodash/lodash/wiki/FP-Guide#rearranged-arguments)

> Methods with a fixed arity of two have an argument order of:
> (b, a)

Meaning I would expect the following assertion to pass:

```
const fp = require('lodash/fp')
  , _ = require('lodash')
  , assert = require('assert');

assert.notEqual(fp.lt(1, 2), _.lt(1, 2));
```

however it throws an error as they both resolve to 'true'

am I missing something? or is this a bug

lodash 4.8.2

**Comment by jdalton** [comment]
It's covered in the next section:
> Methods with unchanged argument orders:<br>
`add`, `assign`, `assignIn`, `bind`, `bindKey`,
`concat`, `difference`, `divide`, `eq`, `gt`,
`gte`, `isEqual`, `lt`, `lte`, `matchesProperty`,
`merge`, `multiply`, `overArgs`, `partial`, `partialRight`,
`random`, `range`, `rangeRight`, `subtract`, `without`,
`zip`, & `zipObject`

Maybe we should move that section higher. Would you like to do that? (the wiki is open).

The order is totally debatable. We took our lead from other FP libs. You can customize this with:
```js
var gt = _.gt.convert({ rearg: true });
```
Or placeholders
```js
_.gt(_,2)
```

**Comment by olsonpm** [comment]
Ah - terribly sorry.  Maybe an asterisk instead of an order change.  I'll think about it.

**Comment by jdalton** [comment]
Thanks!

**Comment by olsonpm** [comment]
The least I can do.  Just started working with fp yesterday and am really enjoying it.

**Comment by macrozone** [comment]
can we have something like isGt which is an alias for lte?

It's really confusing as it is now (other libs struggle the same problem: https://github.com/ramda/ramda/issues/1497)

**Comment by olsonpm** [comment]
It's going to be confusing for people either way.  The only way to make it not confusing would be to add a variable wrapper like:

```js
function number(aNum) {
  return { isGt, isLt, ... };
}

number(2).isGt(1) // unarguably true
```

I've read that ramda thread before - this whole discussion just doesn't lead anywhere productive unfortunately.  The best you can do for now is use placeholders or your own [fp conversions](https://github.com/lodash/lodash/wiki/FP-Guide#convert)
