### ISSUE TITLE
Documentation to mention if groupBy algorithm is stable or not.

### ISSUE THREAD

**Issue by elhigu** [lodash/lodash#2212]
Could it be also mentioned in documentation that groupBy will produce stable result where relative order of elements in each group is the same that original array had?

http://stackoverflow.com/questions/28860526/lodash-sortby-then-groupby-is-order-maintained

Would be great to have this as an official feature and not just by undefined behavior.

**Comment by jdalton** [comment]
While there is a defacto iteration order and ES6 has specified it. I rather not draw attention to or have devs rely on object iteration order.

**Comment by jdalton** [comment]
Though you're probably talking about the order of the grouped elements :P

**Comment by elhigu** [comment]
Awesome thanks!
