### ISSUE TITLE
Can not use some functions (e.g. array functions) in my app

### ISSUE THREAD

**Issue by VeljkoBogosavljevic** [lodash/lodash#2213]
I am developing some Angular app and I installed Lodash using Bower:

"lodash": "3.10.1"

Also, I have added lodash.js in my index.html page:

<script src="bower_components/lodash/lodash.min.js"></script>

I am using Lodash Collection functions with no problems (e.g. _.forEach, _.filter), but when I try to use for example some of Lodash Array functions (e.g. _.remove), I get:

TypeError: _.remove is not a function

What causes the problem and how I can solve it ?

**Comment by jfmengels** [comment]
Could you show a code sample reproducing the problem? Thanks!

**Comment by VeljkoBogosavljevic** [comment]
Sure.

I wrote a function in which I want to remove some objects from array based on some condition:

```
function removeDetachedEntities (type, detachIds, event) {

      if (type === eventConstants.MERGED_EVENTS) {
        _.remove(event.mergedEvents, function (mergedEvent) {
          return detachIds.indexOf(mergedEvent.id) !== -1;
        });
      }

      if (type === eventConstants.IMPORTED_BARCODES) {
        _.remove(event.importedBarcodes, function (importedbarcode) {
          return detachIds.indexOf(importedbarcode.id) !== -1;
        });
      }

    }
```

When I call this function in my app I get:

angular.js:11706 TypeError: _.remove is not a function
    at Object.removeDetachedEntities (event.utilities.js:282)
    at ticketSources.controller.js:67
    at processQueue (angular.js:13318)
    at angular.js:13334
    at Scope.$eval (angular.js:14570)
    at Scope.$digest (angular.js:14386)
    at Scope.$apply (angular.js:14675)
    at angular.js:14965
    at completeOutstandingRequest (angular.js:4940)
    at angular.js:5328(anonymous function) @ angular.js:11706(anonymous function) @ angular.js:8619processQueue @ angular.js:13326(anonymous function) @ angular.js:13334Scope.$eval @ angular.js:14570Scope.$digest @ angular.js:14386Scope.$apply @ angular.js:14675(anonymous function) @ angular.js:14965completeOutstandingRequest @ angular.js:4940(anonymous function) @ angular.js:5328
ticketSources.controller.js:73 Error while detaching token sources:  TypeError: _.remove is not a function(…)

Instad I had to use _.reject function and to assing array property to the result of _.reject function. It works like expected in this way, but I was wondering why I can not just use _.remove function. 

Here is function implementation using _.reject:

```
 function removeDetachedEntities (type, detachIds, event) {

      if (type === eventConstants.MERGED_EVENTS) {
        event.mergedEvents = _.reject(event.mergedEvents, function (mergedEvent) {
          return detachIds.indexOf(mergedEvent.id) !== -1;
        });
      }

      if (type === eventConstants.IMPORTED_BARCODES) {
        event.importedBarcodes = _.reject(event.importedBarcodes, function (importedbarcode) {
          return detachIds.indexOf(importedbarcode.id) !== -1;
        });
      }

    }
```

**Comment by jdalton** [comment]
This kind of support is better suited for our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by jdalton** [comment]
or better yet the [angular gitter chat](https://gitter.im/angular/angular).
