### ISSUE TITLE
Believe `valueOf` alias has been removed from v4.7+ docs

### ISSUE THREAD

**Issue by ashclarke** [lodash/lodash#2214]
Just a heads up that there no longer seems to be a reference to the `valueOf` alias in the [4.8.2](https://github.com/lodash/lodash/blob/4.8.2/doc/README.md#seq) or [4.7.0](https://github.com/lodash/lodash/blob/4.7.0/doc/README.md#seq) docs, but I can see it in  [dist/lodash.js#L15874](https://github.com/lodash/lodash/blob/master/dist/lodash.js#L15874) and in the [4.6.1](https://github.com/lodash/lodash/blob/4.7.0/doc/README.md#seq) docs.

I didn't see a mention of removal in the changelog.

LoDash migrate also throws a warning that the function has been renamed to `_.function valueOf` which is possibly related.

```
lodash-migrate: Method renamed
  v3.10.1 => _.valueOf
  v4.8.2 => _.function valueOf() { [native code] }

lodash-migrate: _.valueOf()
  v3.10.1 => { '1': 
   { '0': 
      { x: [Getter],
        y: [Getter],
...
  v4.8.2 => [TypeError: Cannot read property 'apply' of undefined]
```

**Comment by jdalton** [comment]
Thanks for the heads up. This looks like a [docdown](https://github.com/jdalton/docdown) bug.
I also can't repro the lodash-migrate warning.

**Comment by jdalton** [comment]
I couldn't repro the lodash-migrate issue in the REPL but I added a unit test for lodash-migrate and repro'ed the issue there.

**Comment by ashclarke** [comment]
You're welcome! Thank you for the update!

**Comment by jdalton** [comment]
Patched lodash-migrate @ https://github.com/lodash/lodash-migrate/commit/c4efebe115ce82c0684cbe73c6746779c2ff4625.
