### ISSUE TITLE
in map, being abble to call method of iteratee

### ISSUE THREAD

**Issue by AquariusFR** [lodash/lodash#2215]
example :
```
_(collection)
.map('::toJson');
```

will do the same as :
```
_(collection)
.map(function(o){return o.toJson());
```

**Comment by Florian-R** [comment]
See [_.invoke](https://lodash.com/docs#invoke) and [_.invokeMap](https://lodash.com/docs#invokeMap)

**Comment by demoneaux** [comment]
Yep, for your use case you can run:

```js
_(collection).invokeMap('toJson').value();
```

**Comment by jdalton** [comment]
For the cases that don't map well to `invoke` or `invokeMap` there's also [_.method](https://lodash.com/docs#method).
```js
_(collection).map(_.method('toJSON'));
```

**Comment by AquariusFR** [comment]
A suger would be nice to have a lighter code.
But this solution fits well.
Thanks @jdalton  !
