### ISSUE TITLE
Update modularized packages in npm

### ISSUE THREAD

**Issue by astrism** [lodash/lodash#2216]
Most of the modularized packages seem to be fairly out of date. In particular I'm using lodash.has which lets in null values see #2190 
https://www.npmjs.com/browse/keyword/lodash-modularized

**Comment by jdalton** [comment]
The modularized packages were bumped for 4.7.0. I've held off bumping them for 4.8.0 until it stabilizes (we had 1.8.1 and 1.8.2) just a couple days ago. I expect to bump them within the week.

**Comment by astrism** [comment]
Awesome, no worries, I reverted to an older version.
