### ISSUE TITLE
_.isEqual failing deep comparison when declaring func in prop assignment of object

### ISSUE THREAD

**Issue by zrosenbauer** [lodash/lodash#2217]
version: 4.3.0

The documentation states that in the `_.isEqual` function, Functions and DOM nodes are not supported. Does this mean they are ignored in the comparison (which would be preferred) vs. automatically returning false.?

Example:
```javascript
var foo = {
	a: 1,
	b: '2',
	c: {
	  a: 1,
	  b: function() {console.log('foo')}
	}
}

var bar = {
	a: 1,
	b: '2',
	c: {
	  a: 1,
	  b: function() {console.log('foo')}
	}
}
_.isEqual(foo, bar); // => false
````

From the way the documentation is worded it seems easy to reason that `bar.c.b` and `foo.c.b` would be ignored. If this is not the case I'd recommend adding a small note to the docs such as "Functions and DOM nodes will automatically return false as they are not supported". If it is preferred that Functions are ignored then before it hits the equalByTag function in the baseIsEqualDeep.

example 

```javascript
//old
if (isSameTag && !(objIsArr || objIsObj)) {
   return equalByTag(object, other, objTag, equalFunc, customizer, bitmask);
}

// proposed
if (isSameTag && objTag !== funcTag && !(objIsArr || objIsObj)) {
  return equalByTag(object, other, objTag, equalFunc, customizer, bitmask);
}

// return true to ignore.....or do this higher up
if (objTag === funcTag) {
  return true; 
}
```

How I ran into this....

I am using this in some choke points to compare props in React => 
```javascript 
_.isEqual(nextProps, this.props);
```
Which works great except in the instance I passed in a callback...

**Comment by jdalton** [comment]
It means they are treated as reference equality. You can use [_.isEqualWith](https://lodash.com/docs#isEqualWith) to customize comparisons for functions.
```js
var isEqual = _.partial(_, _, function(value, other) {
  if (typeof value == 'function' && typeof other == 'function') {
    return true;
  }
});
```

**Comment by zrosenbauer** [comment]
Just a note in _.partial first param needs to be a func, followed by the partials. But thanks for quick response!
