### ISSUE TITLE
Not loading in Bower

### ISSUE THREAD

**Issue by funzeye** [lodash/lodash#2219]
Getting error:
bower lodash#*                 ECMDERR Failed to execute "git clone https://github.com/lodash/lodash.git -b 4.8.2 --progress . --depth 1", exit code of #-532462766

**Comment by jdalton** [comment]
Lodash doesn't explicitly support Bower, however Bower works because it looks to git tags. This looks like some git/github hiccup.

**Comment by funzeye** [comment]
Okay cool, ya Githubs been on the blink lately, could be to do with that...
