### ISSUE TITLE
npm module for lodash._baseclone hasn't been updated as per 4.

### ISSUE THREAD

**Issue by jtq** [lodash/lodash#2221]

**Comment by jdalton** [comment]
The [lodash._baseclone](https://www.npmjs.com/package/lodash._baseclone) package was updated for days ago. See #2216.

**Comment by jtq** [comment]
Apologies - I wasn't aware I'd even created this issue.  I must have mis-clicked/pasted and hit enter without meaning to.

Thanks for answering (both of) my queries though. ;-)
