### ISSUE TITLE
The npm-packages branch is still on 4.7.0, so npm modules are still lacking fix f953d34/ec92292

### ISSUE THREAD

**Issue by jtq** [lodash/lodash#2222]
I noticed lodash v4.8.0 was released three days ago (and the lodash npm module is already at v4.8.2), but the lodash.* npm modules (lodash._baseclone, etc) still appear to be based off v4.7.x.

Is there any ETA for the fix for [issue 2185](https://github.com/lodash/lodash/issues/2185) to make its way into the "method" npm modules?  I appreciate these things take time, but it's breaking all our FF integration tests. ;-)

Many thanks (and thanks for an excellent library!)

P.S.  Apologies if this is not the correct medium to ask questions like this, but I couldn't find a more appropriate place to ask.

**Comment by jdalton** [comment]
Same as the other dup. See #2216.

**Comment by jtq** [comment]
Ah - thanks.  Looks like I might need to work out some sort of workaround/temporary fork in that case so we can do releases in the mean-time.

Thanks again.

**Comment by jdalton** [comment]
Pin your dep to an earlier version (one back from latest or so)
