### ISSUE TITLE
Make sum/sumBy return 0 on empty array

### ISSUE THREAD

**Issue by tals** [lodash/lodash#2224]
```js
const items = getItems();
const totalScore = _.sumBy(items, 'score');
```

`totalScore` will be either a number, or in the case of empty arrays, `undefined`. This has bitten us more than once.
I feel that since `sum` and `sumBy` are geared toward numerics, it makes since to just return the number 0 for empty input.

(doing string concatenation with it is technically possible, but doesn't make a lot of sense given `Array.prototype.join`)

Similar to #1838, but strictly regarding an empty array (unsure why it was marked invalid).

**Comment by jdalton** [comment]
They both currently return `0` for empty arrays.

**Comment by tals** [comment]
Oh, I had not noticed that it was changed! Thank you :)

**Comment by tylercollier** [comment]
tals had mentioned `sumBy`. It looks like jdalton was referrring to `sum`. However, `sumBy` was given the same behavior in v4.16.2, released Sep 25, 2016.
