### ISSUE TITLE
Firefox 43.0.1 - TypeError using `defaultsDeep`

### ISSUE THREAD

**Issue by abacaj** [lodash/lodash#2225]
Soon as I type this code:

`import defaultsDeep from 'lodash.defaultsdeep';`

and compile using webpack I get the following console error, mind you there is zero javascript in the file just the import:

`TypeError: Function.prototype.toString called on incompatible object`

**Comment by jdalton** [comment]
Dup #2223, #2185 and #2216.

**Comment by abacaj** [comment]
Your references say it has been resolved, yet I pulled latest package and still get that error,
>Folks, it's already been patched. The next release will go out in a day or so.

**Comment by jdalton** [comment]
It was patched in v4.8.0
> The modularized packages were bumped for 4.7.0. I've held off bumping them for 4.8.0 until it stabilizes (we had 4.8.1 and 4.8.2) just a couple days ago. I expect to bump them within the week.

**Comment by abacaj** [comment]
Ok will be waiting :)
