### ISSUE TITLE
filter, result differs from doc

### ISSUE THREAD

**Issue by blue-lemming** [lodash/lodash#2226]
in here:
https://lodash.com/docs#iteratee
the doc said:
_.filter(['abc', 'def'], /ef/);
// → ['def']
but I obtain
// → ["abc", "def"]
I have tested on my chrome F12 console that i opened on the same page there is the doc.
That's the first time I noticed a bug. Ask me anything if you need. And thanks for your amazing job :)

**Comment by demoneaux** [comment]
For that demo to work, you must customize `_.iteratee` which is used to generate callbacks for all of lodash’s shorthand methods. The code you used was not the full example, which is:

```js
// Create custom iteratee shorthands.
_.iteratee = _.wrap(_.iteratee, function(iteratee, func) {
  return !_.isRegExp(func) ? iteratee(func) : function(string) {
    return func.test(string);
  };
});

_.filter(['abc', 'def'], /ef/);
// → ['def']
```

**Comment by blue-lemming** [comment]
oh. ok, Sorry.
So I guess I will go with _.filter(['abc','def'], _.partial(_.includes,_,'ef')); 
:)
Thank you.
