### ISSUE TITLE
Bug with with latest version of lodash._baseflatten@4.2.0

### ISSUE THREAD

**Issue by nikolenkoanton92** [lodash/lodash#2227]
Hello, our team found a bug with the latest version of `lodash._baseflatten@4.2.0`. With version `4.1.1` all works perfect.

```
if (depth > 0 && predicate(value)) {
  ^
 TypeError: predicate is not a function
```

These errors occur of the following modules:
` "lodash.difference": "4.1.2"`, `"lodash.union": "4.2.1"`

https://github.com/lodash/lodash/blob/299b191da1337be703dda1582663cbd733bf5cf0/dist/lodash.core.js#L657

Thanks, Anton

**Comment by jdalton** [comment]
Update your `difference` and `union` deps. Earlier versions used `^` ranges for their pseudo private deps, newer ones use `~` to avoid these issues.
