### ISSUE TITLE
_.replace replaces only one match

### ISSUE THREAD

**Issue by pashkasan** [lodash/lodash#2228]
_.replace([string=''], pattern, replacement)
_.replace('Hi Fred Fred', 'Fred', 'Barney');
"Hi Barney Fred" should be "Hi Barney **Barney**" depending on api docs

> Replaces matches for pattern in string with replacement.

**Comment by jdalton** [comment]
_.replace is a proxy for String#replace.

**Comment by StreetStrider** [comment]
#1084 #1123
