### ISSUE TITLE
Debounce with maxWait misses some calls

### ISSUE THREAD

**Issue by mb-dev** [lodash/lodash#2229]
I noticed there's an issue with debounce and maxWait. On subsequent calls right after the maxWait, the debounced function is not getting called. 

Check this jsfiddle with an open console:
https://jsfiddle.net/9fjt512m/

My output (Chrome on Max OSX) looks like this:
calling debounce
calling debounce
debounced run
calling debounce
calling debounce

I would expect another "debounced run" at the end, but none is happening. Might be related to the #2093 that was merged a month ago.

**Comment by jdalton** [comment]
Why are you specifying a wait and maxWait of the same time?

**Comment by mb-dev** [comment]
I thought wait is a basic parameter, that says "I don't want this function to be called no more than once every X time". For me, it's: I want to delay the initial call by 5 seconds, so if subsequent calls are made, they are all going to be captured together after that time.

At the same time, if the function gets called repeatedly for 10 seconds, I still want to capture the results in 5 seconds intervals.

Another way of saying this - I want the function to be called exactly every five seconds (if it gets called repeatedly)

**Comment by jdalton** [comment]
Denounce will delay a call until wait Ms have past since last invoke attempt

**Comment by mb-dev** [comment]
Right. But if the function keeps getting called, debounce will keep delaying it, possible longer than wait Ms. That's why maxWait is needed.

**Comment by mb-dev** [comment]
Thanks for looking into this!
