### ISSUE TITLE
Release notes missing for the latest releases

### ISSUE THREAD

**Issue by Turbo87** [lodash/lodash#2231]
At least the 4.8.0 and 4.9.0 releases seems to be missing their release notes.

**Comment by jdalton** [comment]
We write release notes for major releases. Everything else gets [changelog](https://github.com/lodash/lodash/wiki/Changelog) entries.

**Comment by Turbo87** [comment]
I see, I didn't find a change log in the repo and didn't think of looking into the wiki.

**Comment by jdalton** [comment]
It's referenced in the readme and site under the "Further reading" section.

**Comment by Turbo87** [comment]
must've been blind, sorry
