### ISSUE TITLE
`partial` not exists in core 

### ISSUE THREAD

**Issue by darrrk** [lodash/lodash#2232]

**Comment by darrrk** [comment]
Also, some other methods may be not exist in *lodash/core*, but exist in *underscore*.

**Comment by jdalton** [comment]
Yep, this is [by design](https://github.com/lodash/lodash/wiki/Build-Differences).

**Comment by darrrk** [comment]
Aaaa, but I think, that *lodash/core* it method by method underscore replace...
How to resolve this task now?

**Comment by jdalton** [comment]
It's not. Take the leap and upgrade fully to Lodash.
