### ISSUE TITLE
feature request: extend check type modules to return error when returning false...

### ISSUE THREAD

**Issue by MeKarina** [lodash/lodash#2233]
are you open for feature request..??

would be great if lodash extend check type modules such as isString isNumber isObject etc to return error when it returning false...

something like this..

```js
function isStringCheck(value) {
	if (isString(value)) {
		return true;
	} else {
		throw new Error();
	}
}
```

this is useful for security check like argument check... if the check return false then computation must be stopped..

i know there are a lot package doing this but would be great if i could avoid another installation that doing similar purpose for someone that depend a lot to lodash,, like me....

thank Youu...

**Comment by jdalton** [comment]
Hi @MeKarina!

Lodash avoids throwing errors when possible. This would make a good mixin or collection or mixins.

**Comment by StreetStrider** [comment]
@MeKarina, use [expect-style](http://chaijs.com/guide/styles/#expect) checks on top of your functions so you can achieve exactly the thing you need.
```js
expect(foo).to.be.a('string');
// I prefer:
expect(foo).a('string');
```

**Comment by MeKarina** [comment]
i see i see i see... thank Youu @jdalton @StreetStrider ... =))
