### ISSUE TITLE
_.pick with props with subprops

### ISSUE THREAD

**Issue by Mirodil** [lodash/lodash#2235]
is it possible fetch object sub-properties? here is example:
```
_.pick({ a:1,b:2,c:3, d:{ a:11, b:22, c:33 } }, ['a', 'b', 'd.b','d.c'])
// {a: 1, b: 2}
```

**Comment by jdalton** [comment]
We currently don't have an `omitDeep` or `pickDeep`. It has been requested before though, so search the issue tracker and [give the relevant issue a :+1: reaction](https://help.github.com/articles/about-discussions-in-issues-and-pull-requests/).
