### ISSUE TITLE
sortedUniq doesn't sort and doesn't remove duplicates

### ISSUE THREAD

**Issue by DaSchTour** [lodash/lodash#2236]
From what I understand the following
`_.sortedUniq([37, 38, 39, 40, 41, 42, 36, 37, 39, 40, 41, 42, 43, 44, 48])`
should return
`[36, 37, 38, 39, 40, 41, 42, 43, 44, 48]`
But what I get is
`[37, 38, 39, 40, 41, 42, 36, 37, 39, 40, 41, 42, 43, 44, 48]`

And there is no difference if I insert string or integer.

**Comment by jfmengels** [comment]
`This method is like _.uniq except that it’s designed and optimized for sorted arrays.`

It doesn't sort and remove duplicates: it remove duplicates from an already sorted array. This is just a faster implementation if your array is already sorted.
