### ISSUE TITLE
lodash doesn't install on windows after last update

### ISSUE THREAD

**Issue by adampastusiak** [lodash/lodash#2237]
I'm using lodash 3.8.0 and after last release (https://github.com/lodash/lodash/releases/tag/3.8.0-npm-packages) i found that it doesn't install on windows because of problem with too long path name of file " node_modules/gulp-concat/node_modules/gulp-ut
il/node_modules/lodash.template/node_modules/lodash.escape/node_modules/lodash._
escapehtmlchar/node_modules/lodash._htmlescapes". This is whole stack from my CMD: 

`Note: checking out 'e3c6d1db2ada49cbd38b40ec8d29800aaa7b769f'. You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by performing another checkout.`

`If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
git checkout -b new_branch_name
fatal: cannot create directory at 'node_modules/gulp-concat/node_modules/gulp-ut
il/node_modules/lodash.template/node_modules/lodash.escape/node_modules/lodash._
escapehtmlchar/node_modules/lodash._htmlescapes': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'`

I know that Windows has lenght limitations in filenames, but structure of my project didn't change and efore that last release everything worked fine. I don't really know what changed in your project, probably some dependencies but because of it i'm unable to checkout my project.
I use bower to install dependencies such as lodash.

Would be great if you could help here, because lodash is great tool and I don't want to get rid of it from my project.

Thanks in advance.

**Comment by jdalton** [comment]
You should [upgrade to npm@3](https://github.com/felixrieseberg/npm-windows-upgrade) which has maximally flat dependencies and avoids nested node_modules folders.

**Comment by digitaldrummerj** [comment]
You may also need to add long paths to git since the error is related to bower and the git checkout that it does to put it in the bower cache before copying it to your bower_components directory.

```bash
git config --global --add core.longpaths true
```
