### ISSUE TITLE
Why do "By" functions only provide a single param to iteratees?

### ISSUE THREAD

**Issue by thabemmz** [lodash/lodash#2238]
According to the changelog in Lodash v4:

> Made “By” methods like _.groupBy & _.sortBy provide a single param to iteratees

I'm curious about the reason to ditch the other params that were provided to iteratees in previous versions of Lodash. Especially for the `key|index` parameter, there are some valid use-cases for using it (for instance when you'd like to turn an Object into an Array, where the Array order is determined by the keys of the provided Object).

**Comment by jdalton** [comment]
Hi @thabemmz! 

When we expanded our "By" methods in v4 we changed them to accepting a single param to simplify and make them consistent. Since their primary goal is to transform an element to be used as the criterion for whichever method the other args are less useful in that context.

**Comment by thabemmz** [comment]
Thanks for your quick reply!

I agree consistency and simplicity are important, but I'd opt for keeping the `key|index` here, especially since the `key` within objects can contain relevant information about an object. For the use-case I defined above this does not make things more simple. Also, consistency across "By" methods doesn't hold for the `pickBy` function and for instance the more regular `map` and `mapValues` functions.

Of course, I only see things from my perspective here, but for me this change does not make things simpler.

**Comment by jdalton** [comment]
Originally `pickBy` and `omitBy` were one arg too but we had to change because it was used as an object form of `filter` and `reject`. In v5 will have proper methods for them.

**Comment by thabemmz** [comment]
Ok, clear. Thanks for the info.
