### ISSUE TITLE
camelCase(...) bug in v4.10.0

### ISSUE THREAD

**Issue by YouriT** [lodash/lodash#2239]
In v4.10.0 `_.camelCase(..)` doesn't return the same value as in v4.6.1.
Example:
```js
_.camelCase('MICs'); // becomes "miCs" in 4.10.0
_.camelCase('MICs'); // becomes "mics" in 4.6.1
```
As I didn't find any change about that in the changelog, I guess this is a bug?

**Comment by jdalton** [comment]
This was the result of [resolving another issue](https://github.com/lodash/lodash/issues/2091#issuecomment-193314618). I'm fine with the 4.10.0 behavior as it becomes ambiguous on how to handle it.

**Comment by jdalton** [comment]
Corrected bug link https://github.com/lodash/lodash/issues/2163#issuecomment-202406816

**Comment by YouriT** [comment]
Okay but why keeping the "C" as an uppercase?

**Comment by YouriT** [comment]
And if you want to keep it like this, wouldn't you notify it as a breaking change in the changelog to avoid other comments like mine?

**Comment by jdalton** [comment]
>  Okay but why keeping the "C" as an uppercase?

It sees "MICs" as two words
```js
_.words('MICs');
// => ["MI", "Cs"]
```

> And if you want to keep it like this, wouldn't you notify it as a breaking change in the changelog to avoid other comments like mine?

It's a bug fix. You relied on broken functionality. It happens from time to time.

**Comment by jdalton** [comment]
BTW what is `MICs`?

**Comment by YouriT** [comment]
Ok, I'm fine with the new logic behind. Not a breaking change then but there is nothing mentioned in the changelog about camelCase, just startCase. Anyhow your call :)

MICs in my case is the name of a file containing MIC entries which is ISO 10383 convention about codes for exchanges and market identification. MIC stands for Market Identification Codes. So the "s" in my case doesn't make sense as C stands already for "Codes". Thanks for the comments and keep doing great job like you do with lodash!

**Comment by YouriT** [comment]
But let's say you have MIE that would stand for Market Identification Entry, you would be tempted to add a "s" to make MIEs and then it doesn't work out anymore. Anyhow!

**Comment by jdalton** [comment]
Yep, it didn't work in v3, was a mistake in v4, and it was corrected. It sounds like you're at the point where you should normalize your input with `_.toLower` first.

**Comment by YouriT** [comment]
Just capitalized the "s" in the file name to be honest, was too deep to be changed quickly. Thx!

**Comment by jdalton** [comment]
I'm experimenting with adding support for `ALLCAPSz` (one lower case letter). We'll see if it breaks folks.
