### ISSUE TITLE
why doesnt minBy takes in object?

### ISSUE THREAD

**Issue by peonmodel** [lodash/lodash#2241]
referring to: https://github.com/lodash/lodash/issues/1812

why doesnt _.minBy and some other functions takes in an object
while _.each still do?

i am interested in the why

what does it complicate? was it confusion or problems with optimisation?

**Comment by jdalton** [comment]
In v4 we've tried to reduce the "Collections" case opting for array/object/string specific methods instead. It also helped ensure other math methods didn't have to worry about supporting collections either.
