### ISSUE TITLE
Lodash causing Gulp issues?

### ISSUE THREAD

**Issue by reintroducing** [lodash/lodash#2242]
Hello,
I just went to upgrade my project from v3.10.1 to v.4.10.0 of lodash and I'm getting an issue when trying to run gulp.

Pre update `gulp -v` produces:
```
[08:29:50] Requiring external module babel-core/register
[08:29:50] CLI version 3.9.0
[08:29:50] Local version 3.9.0
```

Post update `gulp -v` produces:
```
[08:30:20] Failed to load external module babel-core/register
[08:30:20] Failed to load external module babel/register
[08:30:20] CLI version 3.9.0
[08:30:20] Local version 3.9.0
```

I'm using an ES6 gulpfile with ES6 all throughout my tasks and this all worked prior to upgrading lodash versions.  

Of note is that I also see a lot of warnings like this when installing the new lodash version:
```
npm WARN unmet dependency /Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/write-file-webpack-plugin requires lodash@'^3.10.1' but will load
npm WARN unmet dependency /Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/lodash,
npm WARN unmet dependency which is version 4.10.0
```

What am I doing wrong here?

**Comment by jdalton** [comment]
Hi @reintroducing!

Try hitting up the [gulp gitter chat](https://gitter.im/gulpjs/gulp).

**Comment by reintroducing** [comment]
@jdalton just wanted to update for reference in case anyone else ever ran into this.  I ran an `npm cache clean` and the issue was resolved.  Apologies for wasting anyone's time who looked at this :)
