### ISSUE TITLE
orderIndexBy

### ISSUE THREAD

**Issue by megawac** [lodash/lodash#2243]
Had a need to identify the position where to insert an element in an array sorted by `orderBy`. Seems like `orderIndexBy` is a natural complement for `sortedIndexBy`

John-David Dalton's thoughts:
> Neat orderedIndexBy!

**Comment by jdalton** [comment]
Cool! While we wait for the [reactions to come in](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests). What would the arg signature look like?

**Comment by omgoshjosh** [comment]
What is the best way to do this if lodash does not support it?
