### ISSUE TITLE
Chaining custom method subset

### ISSUE THREAD

**Issue by aldendaniels** [lodash/lodash#2246]
Thanks for this incredible library. I'm interested in using a subset of the available lodash methods, but I'd like to retain chaining. I can accomplish this via a custom build, but I'd much rather be able to load lodash directly from NPM.

Thanks to https://github.com/lodash/lodash/issues/966#issuecomment-74384259, I'm able to get this work like so:

```javascript
const lodash = require('lodash/wrapperLodash');
const baseForOwn = require('lodash/_baseForOwn');
const mixin = require('lodash/mixin');

// Add methods that return wrapped values in chain sequences.
lodash.map = require('lodash/map');

// Add methods to `lodash.prototype`.
mixin(lodash, lodash);

// Add methods that return unwrapped values in chain sequences.
lodash.get = require('lodash/get');

mixin(lodash, (function() {
  var source = {};
  baseForOwn(lodash, function(func, methodName) {
    if (!hasOwnProperty.call(lodash.prototype, methodName)) {
      source[methodName] = func;
    }
  });
  return source;
}()), { 'chain': false });

// Add chain sequence methods to the `lodash` wrapper.
lodash.prototype.chain = require('lodash/wrapperChain');
lodash.prototype.value = require('lodash/wrapperValue');


console.log(lodash([1,2]).map((x) => x * 2).get('0')); // 2
console.log(lodash.get([1,2], '0')); // 1
```

This seems l likely to break, however, since it looks at LoDash internals and is pretty involved to get right. Is there (or should there be) a more standard way of accomplishing this?

**Comment by jdalton** [comment]
You can always use `lodash/forOwn` or a for-in loop if you want. There probably should be a more standard way, like using `lodash/seq`, but I haven't created it yet (it's low priority).

**Comment by aldendaniels** [comment]
Thanks, @jdalton for the quick reply! My concern isn't using `baseForOwn`. It's about how hard it is to create a clean copy of Lodash that includes only certain methods and is chainable.

**Comment by jdalton** [comment]
Check out [this post](https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba) on using functional composition as an alternative to chaining.

**Comment by aldendaniels** [comment]
Useful - thanks!
