### ISSUE TITLE
omit and without aliases ?

### ISSUE THREAD

**Issue by sylido** [lodash/lodash#2247]
`omit` works well for collections, but doesn't work with arrays of values.
   ```
 var a = ["result", "something", "else"];
 _.omit(a, "result");
 >> Object {0: "result", 1: "something", 2: "else"}
```

Whereas `without` performs nicely
```
_.without(a, "result", "else");
>> ["something"]
```

Can `omit` and `without` be made aliases where if `omit` detects an array of non-objects it defaults to use `without's` functionality and vice versa for `without` detecting an object instead of an array ?

**Comment by jdalton** [comment]
Hi @sylido!

This is a no-go for me because I want to favor functions that return a consistent type and want to avoid overloading when possible.

**Comment by sylido** [comment]
Thanks @jdalton makes sense.
