### ISSUE TITLE
partial breaks function.length

### ISSUE THREAD

**Issue by tyrchen** [lodash/lodash#2248]
When using partial, the wrapped function lose the capability to get the arity. See this example:

```bash
> function f(a,b,c,d,e) { return {a, b, c, d, e}; }
undefined
> f1 = lodash.partial(f, 1, 2);
[Function: wrapper]
> f1.length
0
> f2 = f.bind(null, 1, 2);
[Function: bound f]
> f2.length
3
```

**Comment by jdalton** [comment]
From [the docs](https://lodash.com/docs#partial):
>  **Note:** This method doesn't set the "length" property of partially applied functions.

If you're relying on function.length you're in for a bad time, esp with things like default params in ES6.

**Comment by tyrchen** [comment]
oh, my bad. Thanks for the explanation.
