### ISSUE TITLE
Possible problem on _.pullAt

### ISSUE THREAD

**Issue by mibaraho** [lodash/lodash#2254]
When using `_.pullAt` on arrays with length greater than 11, the mutation fails:

`var arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10 , 11, 12];`
`var evens = _.pullAt(arr, 1, 3, 5, 7, 9, 11);`
`console.log(evens)`
`//[2, 4, 6, 8, 10, 12]`
`console.log(arr)`
`//[1, 3, 5, 7, 9, 11, 12]`

It works fine when the array length is 11 or less. As seen in the [documentation](https://github.com/lodash/lodash/blob/4.11.1/lodash.js#L6839) :

`var arr = [1, 2 , 3, 4];`
`var evens = _.pullAt(arr, 1, 3);`
`console.log(evens)`
`//[2, 4]`
`console.log(arr)`
`//[1, 3]`

Lodash version tested: `v4.11.1`

**Comment by jdalton** [comment]
Ah sorting by string indexes
```
"11" < "3" // true
```
