### ISSUE TITLE
_.has() no longer works with DOM elements

### ISSUE THREAD

**Issue by roblav96** [lodash/lodash#2255]
Recently updated to the latest lodash and I now notice that using _.has() no longer works when using it with an element.

https://jsfiddle.net/e64x5ra4/1/

Version 4.7.0 is when it broke.
> Ensured _.has returns false for nested inherited properties

**Comment by jdalton** [comment]
```js
lol1.hasOwnProperty('children'); // false
```
You're wanting to use `_.hasIn`:
```js
_.hasIn(lol1, 'children.lol2'); // true
```
