### ISSUE TITLE
lodash-es/find import side effects with Rollup

### ISSUE THREAD

**Issue by rdmurphy** [lodash/lodash#2257]
I've been working on a library that depends on specific functions from `lodash-es` — and every thing gets compiled via Rollup. And overall it has worked great!

However, I've noticed a side effect of using the `lodash-es/find` import. I understand that some portions of `lodash` aren't fully amendable to "tree-shaking" yet, so this may just be a manifestation of that. Even if the `find` function is not used (which would cause Rollup to not include it — which is does do successfully!), there are imports throughout its dependency chain that add variables and functions. So even if you don't use `find`, you end up with around 800 lines of code that Rollup doesn't know it does not need.

A test case:

#### package.json
```js
{
  "private": true,
  "scripts": {
    "build": "rollup -c"
  },
  "devDependencies": {
    "rollup": "^0.25.8",
    "rollup-plugin-node-resolve": "^1.5.0"
  },
  "dependencies": {
    "lodash-es": "^4.11.1"
  }
}
```

#### rollup.config.js
```js
import node from 'rollup-plugin-node-resolve';

export default {
  entry: 'index.js',
  dest: 'bundle.js',
  format: 'iife',
  plugins: [
    node({
      jsnext: true
    })
  ]
};
```

#### index.js
```js
import find from 'lodash-es/find';
```

#### bundle.js
So it doesn't dominate the page, [I've created a gist](https://gist.github.com/rdmurphy/149bde913ec4692b80b924fcca59f4c0).

Is there something I'm missing? Or is it still a work in progress? (Not sure if this may be on the Rollup side of things, but I figured I'd start here.)

Thank you!

**Comment by rdmurphy** [comment]
Just to add — I know I'm reporting an un-minified line count here. I left out my use case!

My library will have scripts that can be imported as ES6 modules as well — and this is causing the extra `find()` functions and variables to be added to bundles that do not attempt to import the script that imports `find()`. My guess is that as Rollup walks through the dependencies, they get appended because it has no way to know `find()` is the only thing that'd need them.

**Comment by jdalton** [comment]
Lodash's es6 export is on point as far I can tell. The fact that utils can't grok it seems like a third party issue. Until then babel-plugin-lodash is the way to go

**Comment by rdmurphy** [comment]
Gotcha. I'll check that out. Thanks!
