### ISSUE TITLE
Feature request: _.isEmptyValues()

### ISSUE THREAD

**Issue by coreyc** [lodash/lodash#2258]
Hi,
I came across a scenario recently in which I needed to check if an object had no values ("",null), only properties.  I'm still kinda new to lodash, but haven't yet come across any existing method that does this.  Opening as feature request for now.  Let me know if I'm overlooking something.

Thanks for the library

**Comment by jfmengels** [comment]
I don't think there is anything that does that, but I think
```js
_.compact(_.values(object)) === 0
```
covers your use-case. If a lot of people want this functionality, it'll probably get into Lodash, but since this is pretty simple to implement, I don't see the need for it.

**Comment by jdalton** [comment]
Hi @coreyc!

You can compose this with `lodash/fp`
```js
var _ = require('lodash/fp');
var isEmptyValues = _.flow(_.filter(_.isNil), _.size, Boolean);
```

**Comment by nfantone** [comment]
Either I'm not following the original request right or the given workaround for this doesn't work.

```js
var _ = require('lodash/fp');
var isEmptyValues = _.flow(_.filter(_.isNil), _.size, Boolean);

> isEmptyValues({}); // should be `true`
false
> isEmptyValues({foo: undefined}); // should be `true`
true
> isEmptyValues({foo: undefined, bar: 42}); // should be `false`
true
```

For anyone interested out there, here's a working solution:

```js
import { filter, size, compose, isNil, negate } from 'lodash/fp';
const isObjectEmpty = compose(negate(Boolean), size, reject(isNil));

> isObjectEmpty({});
true
> isObjectEmpty({foo: undefined});
true
> isObjectEmpty({foo: null});
true
> isObjectEmpty({foo: null, bar: 42});
false
> isObjectEmpty({foo: 'life', bar: 42});
false
```

**Comment by nfantone** [comment]
Also, solution by @jfmengels compares an array to `0`.

```js
// _.compacts returns an Array
// See https://lodash.com/docs/4.17.4#compact
_.compact(_.values(object)) === 0;
```

I believe the intention was to compare the size of the compacted Array?

```js
_.size(_.compact(_.values({}))) === 0;
```

☝️ That actually behaves as proposal [posted above](https://github.com/lodash/lodash/issues/2258#issuecomment-278087756):

```js
const isEmptyValues = (o) => _.size(_.compact(_.values(o))) === 0;

> isEmptyValues({});
true
> isEmptyValues({foo: undefined});
true
> isEmptyValues({foo: null});
true
> isEmptyValues({foo: 42});
false
```
