### ISSUE TITLE
Custom lodash compatible objects?

### ISSUE THREAD

**Issue by leshy** [lodash/lodash#2260]
Hi, is there a specification on an interface lodash expects from different types its working with (collection, array, etc)?

For example which methods does lodash expect out of a "collection"? 

I'd like to make my own custom higher order class, on whose instances lodash can for example map and each through.

is this possible/expected?

PS,
I'm sure this has been asked before, sorry for asking again, I couldn't search/google out anything with regards to this.

**Comment by jfmengels** [comment]
If you look for example at the definition for [`_.find`](https://lodash.com/docs#find), the first argument is a `collection`. If you look at the definition of the argument a bit below, you'll see `collection (Array|Object): The collection to search.`. A collection, for Lodash, is either an JavaScript array (`[1, 2, 3]`) or an object (`{a: 1, b: 2}`).

I don't know how it works internally so I wouldn't know what is needed for custom types to work with it though.

If you have other questions, feel free to hit the [Gitter chat](https://gitter.im/lodash/lodash) :)

**Comment by leshy** [comment]
Hm, yeah, but there must be a piece of code within _.find that doesn't know which of the builtin types the input was, and is interacting with lodashes internal concept of a "collection"

I was hoping to implement such "collection" interface to get all the lodash functions working on my own type.

This doesn't seem as a particularly extravagant thing to do as its very ugly to implement map and fold five times depending on what you are working with. Anything you can iterate through should be able to be treated as a collection / seq by lodash, if it implements some necessary methods you'd expect from a collection.

to give a concrete example, I have a collection of time ranges which is a range tree data structure in the background, nothing like an object or an array, but all of the collection functions make sense in its context.

**Comment by jdalton** [comment]
Hi @leshy!

The only thing we key off of is a valid `length` property to determine if a value is array-like or not so it either goes down the array-like path or the object path.
