### ISSUE TITLE
Rails _.isBlank ?

### ISSUE THREAD

**Issue by aug-riedinger** [lodash/lodash#2261]
Coming from the rails world, I keep using the [`.blank?`](http://api.rubyonrails.org/v4.2/classes/Object.html#method-i-blank-3F) method, which works pretty much as expected:

```
_.isBlank(undefined) : true
_.isBlank(null) : true
_.isBlank('') : true
_.isBlank(0) : false
```

I can't find *the Lodash way* to test this. The `_.isEmpty` sounded promising, but `_.isEmpty(0)` is `true`...

Any suggestion?

In my case I have a form and I apply a specific behavior if the value is empty, which sometimes will be `null`, `undefined`, `''`, but if a `<select>` has option 0 selected, it mustn't be considered as empty...

**Comment by jfmengels** [comment]
In JS, you can simply use the unary `!` operator:
```js
!undefined: true
!null: true
!'': true
!0: true
!1: false
!{field: 'value'}: false
```
FYI, you could use `!!value` to ask whether a value is not blank (not needed in `if` conditions though).

**Comment by aug-riedinger** [comment]
Thank you. I asked it on [SO](http://stackoverflow.com/questions/36691125/lodash-isblank) first, and after some hate sent by JS-only supporters, I finally got a nice solution:

```
_.isBlank = function(value) {
    return _.isEmpty(value) && !_.isNumber(value) || _.isNan(value);
}
```

If it were me, I'd discuss integrating this to Lodash, otherwise, please feel free to close the issue.

Best,

**Comment by jfmengels** [comment]
Ah yes, sorry, you wanted to have true for `0`.

I'm pretty sure it won't get into Lodash then, because it's counter-intuitive to what JS developers are used to (in that sense, it's not a "clear" method, as you mentionned on SO), and is an edge case (one that you will not encounter often, hopefully).

Sorry about the hate responses on SO though :/

**Comment by jdalton** [comment]
Hi @aug-riedinger!

I remember something like this [from Prototype.js](http://api.prototypejs.org/language/String/prototype/blank/) too.
As [with other requests](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) we'll keep tabs on demand for such a method.

Related to #1174 and #1600.

**Comment by kevinmtrowbridge** [comment]
No votes for this?  Also Rails dev, also missing this.
