### ISSUE TITLE
_.conforms: no way to express some key may be missing

### ISSUE THREAD

**Issue by jrencz** [lodash/lodash#2262]
When I want to express that object:
- contains of 2 keys `keyA` and `keyA `
- `keyA` may be missing, but if is defined it's an integer
- `keyB` is an array of integers

I try:

```js
const isValid = _.conforms({
  keyA: _.overSome(_.isInteger, _.isUndefined),
  keyB: _.overEvery(_.isArray,  _.partial(_.every, _, _.isInteger)),
});
```

```
isValid({keyA: 1, keyB: [1,2]});
// true

isValid({keyB: [1,2]});
// false
```

So far I found no way to express that `keyA` may be missing (I assumed passing `_.isUndefined`) either in `_.over*` or passed as a sole requirement will do the job.

I'm not certain whether `_.conforms` is not the right tool for the job or is it missing some feature?

**Comment by jdalton** [comment]
The `_.conforms` method [has a check](https://github.com/lodash/lodash/blob/4.11.1-npm/_baseConforms.js#L24-L25) for the existence of `undefined` values. I'll review the policy behind it and see if it make sense to remove the restriction.

**Comment by dietergeerts** [comment]
Any news if this restriction can be removed? 
I think it can, as your predicted can check for it, which I had done initially, as if the value is undefined, that means it's or not there, or actually undefined, which would mean it's not there in JS.

I create helper functions for the undefined cases:
```
export const isSubjectGroupTimings = _conformsTo({
  groupId: _isString,
  scheduledFrom: isUndefinedOr(_isDate),
  calculatedFrom: _isDate,
  calculatedUntil: _isDate,
});
```

This can then be used as a custom validator in a vue component and given the popularity of Vue, it would be great if the restriction would be removed in favor of letting the user decide in the predicates themselves.

**Comment by dietergeerts** [comment]
as a workaround, I did the following:
```
export const isSubjectGroupTimings = _overEvery([
  _conformsTo({
    groupId: _isString,
    calculatedFrom: _isDate,
    calculatedUntil: _isDate,
  }),
  _flow(_get('scheduledFrom'), isUndefinedOr(_isDate)),
]);
```

**Comment by StreetStrider** [comment]
There's a bunch of nice (but majority of are abandoned) projects for such tasks, like `tcomb`, `sanctuary-def`, `shapely`, `runtypes`.
