### ISSUE TITLE
Chaining uniqBy and uniqWith not a function error

### ISSUE THREAD

**Issue by Jks15063** [lodash/lodash#2264]
I see all three functions (uniq, uniqBy, uniqWith) listed under chainable methods but using `uniqBy` or `uniqWith` throws `[TypeError: _(...).uniqWith is not a function]` while uniq works just fine.

Nothing fancy, even a little test like `_([1,2,3,4]).uniqWith(function(a, b) { ... });` throws.

**Comment by jdalton** [comment]
I can't repro:
```js
_([1, 1, 2, 3]).uniqWith(_.eq).value()
// => [1, 2, 3]
```

Make sure you're using Lodash v4.

**Comment by Jks15063** [comment]
yea derp old version, oops
