### ISSUE TITLE
Feature request: _.same, _.isSame for strict equality comparison

### ISSUE THREAD

**Issue by jamesrom** [lodash/lodash#2265]
Utility for strict equality (`===`). _.isSame would be similar to _.isMatch, but unlike _.isMatch, it returns true if and only if `source === obj`.

_.same would return a function, i.e., _.isSame partially applied with `source`.

Therefore, _.same : _.isSame :: _matches : _.isMatch

```js
// example implementation
_.isSame = function(source, obj) {
  return source === obj
};

_.same = function(source) {
  return _.partial(_.isSame, source);
};
```

This would be particularly useful for the object methods such as _.findKey, _.findLastKey, _.omitBy. But would also be useful for many array methods too.

For example:

```js
var users = {
  'alice': { age: 20 },
  'bob': { age: 20 },
  'charlie': { age: 20 }
};
var everyoneElse = _.omitBy(users, _.same(users.alice));
// → {'bob': { age: 20 }, 'charlie': { age: 20 }}

**Comment by jdalton** [comment]
We have [_.eq](https://lodash.com/docs#eq) which is close, though it matches `NaN`.
