### ISSUE TITLE
Difference between _.chain() and _.()

### ISSUE THREAD

**Issue by thoraage** [lodash/lodash#2266]
Both creates wrapper, but I thought it was exactly the same. However for:

    _.chain([1,2,3]).forEach(function(a){console.log(a);});

... i will need to add `.value()` to get the same result (logging in console) as this:

    _([1,2,3]).forEach(function(a){console.log(a);});

**Comment by Alexsey** [comment]
While <a href="https://lodash.com/docs#_">```_.()```</a> says ```Methods that retrieve a single value or may return a primitive value will automatically end the chain sequence and return the unwrapped value```

<a href="https://lodash.com/docs#chain">```_.chain```</a> says ```The result of such sequences must be unwrapped with _#value```

It means that usually you would like to use ```_.()``` but sometimes you would like to use ```_.chain()``` instead of doing additional ```_.()``` on intermediate results

**Comment by thoraage** [comment]
Thanks for the clarification
