### ISSUE TITLE
kebabCase not working with endash

### ISSUE THREAD

**Issue by pixel2** [lodash/lodash#2268]
`_.kebabCase('kebab case with - normal dash with – emdash');`

Gives the following result `kebab-case-with-normal-dash-with-–-emdash`

The expected result would be `kebab-case-with-normal-dash-with-emdash`

This seems to have changed in lodash 4. Running the same code in 3.x gives the correct result.

**Comment by jdalton** [comment]
In v4 we're a bit more forgiving in our `_.words` detection.
