### ISSUE TITLE
Question: about .map with string as second parameter

### ISSUE THREAD

**Issue by Alexsey** [lodash/lodash#2269]
Hello
```
const a = [{x: {y: 1}, 'x.y': 'a'}, {x: {y: 2}}, {'x.y': 'c'}]
_.map(a, 'x.y') // ['a', 2, 'c']
```
May I rely on behavior that if collection element has a property with dot - it will use firstly, and if it hasn't - dot will be used for deep value search? Or it's just the way it appears for now and it could be changed? As far as I can see such nuance is not documented

**Comment by jdalton** [comment]
Our path shorthand will first try `o['x.y']` and then go to `o.x.y`

**Comment by jdalton** [comment]
You can always be super explicit and use:
```js
_.map(a, _.property(['x', 'y']));
// or
_.map(a, _.property(['x.y']));
```
depending on which property you want.

**Comment by Alexsey** [comment]
Yes, I can see that :) Question is about is it reliable? My concern is coming from general approach that if something is not in the doc - it isn't.

**Comment by Alexsey** [comment]
Current behavior is EXACTLY what I need, but it's quite non-obvious that is why I'm so picky :)

**Comment by jdalton** [comment]
Yep it's reliable. Unit tests and everything for it.

**Comment by Alexsey** [comment]
Cool! Thank you once again
