### ISSUE TITLE
Surprising results when _.find'ing properties with array values

### ISSUE THREAD

**Issue by mwcz** [lodash/lodash#2270]
Very sorry if this has been addressed already.  I ran into this behavior that surprised me, when trying to find an element within an array using the `matches` shorthand.

    const sprites = [
        { pos: [4,2] },
        { pos: [5,4] },
        { pos: [1,1] },
        { pos: [1,2] },
        { pos: [2,1] },
    ];

    _.find(sprites, { pos: [2,2] }); // expected undefined but returns { pos: [4,2] }
    _.find(sprites, { pos: [2,1] }); // expected { pos: [2,1] } but returns  { pos: [1,2] }

While perusing the code I found that `baseIsEqual` is called with `PARTIAL_COMPARE_FLAG` (explains first find) and `UNORDERED_COMPARE_FLAG` (explains second find).

I'm quite sure there's a good reason for applying those flags, but I wanted to mention it since it surprised me and I couldn't find any prior questions about it.

<3 lodash

**Comment by jdalton** [comment]
Hi @mwcz!

When doing a partial match index order isn't generally a concern.
The match of `[2, 2]` is a bit odd so I'll look at that.
