### ISSUE TITLE
Proposal: _.overObject

### ISSUE THREAD

**Issue by Silverwolf90** [lodash/lodash#2272]
Proposing `_.overObject` which acts like `_.over`, but instead of an array of iteratees, it takes an object where each value is an iteratee.

```javascript
const firstAndLast =_.overObject({
  first: _.first,
  last: _.last,
});

firstAndLast([5, 6, 7, 8, 9]);
//=> { first: 5, last: 9 }
```

**Comment by jdalton** [comment]
Hi @Silverwolf90!

Thanks for [the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests). We'll keep an eye on user demand.

**Comment by jetpacmonkey** [comment]
I've found myself wanting this while using `lodash/fp` more than once. Is there any fixed measure of how many votes is enough for a feature to make its way into lodash?

Also, for those who want this functionality and don't want to wait, it should actually be a fairly straightforward one-liner (using ES2015 fat-arrow lambda functions, at least).

```javascript
const overObject = (src, fns) => _.mapValues(fns, (fn, key) => fn(src[key]))
```

Or the fp version,

```javascript
const overObject = _.curry((fns, src) => _.mapValues(fns, (fn, key) => fn(src[key])))
```

**Comment by jetpacmonkey** [comment]
My mistake, my sample code was misremembering `_.over`'s signature. It would just be...

```javascript
const overObject = fns => src => _.mapValues(fns, fn => fn(src))
```

**Comment by jedwards1211** [comment]
I think `mapShape` is a better name for this
