### ISSUE TITLE
Error in _.concat

### ISSUE THREAD

**Issue by mborecki** [lodash/lodash#2273]
Using: 4.11.1
Browser: Chrome

Trying example from docs:

```
var array = [1];
var other = _.concat(array, 2, [3], [[4]]);

console.log(other);
// → [1, 2, 3, [4]]

console.log(array);
// → [1]
```

I get:

```
other -> [1, undefined]
array -> [1]
```

**Comment by jdalton** [comment]
I can't repro that in our edge bits.
```js
_.concat([1], 2, [3], [[4]]);
// => [1, 2, 3, [4]]
```

**Comment by mborecki** [comment]
I double check this, and find that it is only in lodash.core.js no i lodash.js

**Comment by jdalton** [comment]
Ah nice!

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash-cli/commit/8167596667aa09427cae5c7f0589e3e84e8d3b6b.
