### ISSUE TITLE
`lodash-es` UglifyJS error

### ISSUE THREAD

**Issue by calebmer** [lodash/lodash#2274]
I am using Webpack `^2.1.0-beta.5` with `lodash-es` `^4.11.1`. When trying to build the following file:

```js
import { camelCase } from 'lodash-es'

console.log(camelCase('hello world'))
```

with the UglifyJS plugin with the default config I get the following error:

```
ERROR in index.js from UglifyJs
Unexpected token punc «[», expected punc «:» [./~/lodash-es/array.default.js:67,0]
```

Thanks so much for the library 👍

**Comment by calebmer** [comment]
Upon further investigation, this is a webpack error.

**Comment by calebmer** [comment]
If anyone in the future is interested, I reported the error here: https://github.com/webpack/webpack/issues/2380

**Comment by calebmer** [comment]
I'm actually going to reopen this again because it might actually be `lodash`. If you look at the issue, I post this piece of code from `lodash-es`:

```js
import chunk from './chunk';
import compact from './compact';
import concat from './concat';
import difference from './difference';
…

export default {
  chunk, compact, concat, difference, …
};
```

This contains invalid ES5 code (minus imports/exports). If you can't see it, look at this:

```js
import chunk from './chunk';
import compact from './compact';
import concat from './concat';
import difference from './difference';
…

var myDefault = {
  chunk, compact, concat, difference, …
};
```

`lodash-es` is incorrectly assuming an environment which has destruct/construct capabilities. The fix is easy, we'd be looking at something like:

```js
export default {
  chunk: chunk, compact: compact, concat: concat, difference: difference, …
};
```

I believe that should fix the error. I'd submit a PR but I'm not sure where the code is to generate `lodash-es` 😖

**Comment by jdalton** [comment]
Our es build is valid es6.

**Comment by jdalton** [comment]
UglifyJS will need to receive transpiled ES5 code.

**Comment by calebmer** [comment]
Ok, that makes sense. It wasn't incredibly clear that `lodash-es` would still need a transpilation step for use with webpack 👍
