### ISSUE TITLE
Feature requests about the documentation

### ISSUE THREAD

**Issue by eGavr** [lodash/lodash#2276]
Hi!

I'm using `lodash` for a long time,  but still I need the documentation sometimes in order to find some methods or to research whether this or that method is chainable or not, so I find the current variant of the documentation a little bit inconvenient for my purposes. It will be great if you add two features in the documentation:

1. `search` in order to find this or that method very quickly (using of `cmd + f` is rather inconvenient)
2. label for each method which can sign whether it is chainable or not

Thank you!

**Comment by jdalton** [comment]
Hi @eGavr!

You can help shape the documentation over at [lodash/lodash.github.io](https://github.com/lodash/lodash.github.io/issues/15#issuecomment-212708481).
