### ISSUE TITLE
fp.assign with empty object

### ISSUE THREAD

**Issue by tycho01** [lodash/lodash#2278]
Lodash regular (4.11, docs page):

    _.assign({a:1},{b:2})
    _.assign({a:1},{b:2},{})
    _.assign({a:1},{},{b:2})
    _.assign({},{a:1},{b:2})
    // all: {a: 1, b: 2}

Lodash FP (4.7):

    _.assign({a:1},{b:2})
    // {a: 1, b: 2}
    _.assign({a:1},{b:2},{})
    // {a: 1, b: 2}
    _.assign({a:1},{},{b:2})
    // {a: 1}
    _.assign({},{a:1},{b:2})
    // {a: 1}

I hadn't expected for those last two to behave differently. Is this an intended diversion in FP?

**Comment by demoneaux** [comment]
lodash fp's version of `assign` only expects two arguments, as mentioned [here](https://github.com/lodash/lodash/wiki/FP-Guide#fixed-arity).
