### ISSUE TITLE
[Feature Request] A chain method based on flow.

### ISSUE THREAD

**Issue by AriaFallah** [lodash/lodash#2280]
`_.chain` carries the downside that you can't only choose to use part of the lodash library, you have to basically import the whole thing to be able to use it.

After reading [this](https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba#.vz2a9x9dn) I ended up making a method chaining function of my own based on `_.flow` instead of `_.chain`.

It's extremely simple

```js
import { flow } from 'lodash'

function chain(data, funcs) {
  return flow(...funcs)(data)
}
```

but I think it's extremely useful as well

```js
import { filter, map, pick, sortBy, take } from 'lodash/fp'

// SELECT name, age FROM users WHERE age > 18 ORDER BY age LIMIT 1
chain(users, [map(pick(['name', 'age'])), filter((x) => x.age > 18), sortBy('age'), take(1)])
```

I think the biggest benefits it has over the regular `_.chain` is that you don't have to call `.value()` and that  you can choose which parts of lodash you want to use instead of using the whole thing.

What do you think? Also even if you don't add it, do you see any potential downsides to this approach that could be improved?

**Comment by jdalton** [comment]
Very nice @AriaFallah!

We'll [keep an eye on](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) demand.

**Comment by jdalton** [comment]
Internally our `flow` and `flowRight` use chain sequences to enable lazy evaluation so this is right along with that. Totally makes sense.

**Comment by AriaFallah** [comment]
> Internally our flow and flowRight use chain sequences to enable lazy evaluation so this is right along with that.

Could you elaborate on that a bit? I'm pretty interested in the implementation, and the ideas behind how it works.

**Comment by jdalton** [comment]
You can dig into it more [here](https://github.com/lodash/lodash/blob/npm/_createFlow.js). The gist is it detects if the method has a chain sequence counterpart and if so starts to build the chain sequence. Then when the composed method is executed it plants the argument as its chain sequence seed value and executes the chain sequence.
