### ISSUE TITLE
_.isIterable

### ISSUE THREAD

**Issue by Aprillion** [lodash/lodash#2282]
I was surprised by the behaviour of `_.isEmpty(new Date())`.

The examples in https://lodash.com/docs#isEmpty do not say how to check for empty-able types, what condition do I need so that integers, Dates and other non-empty-able types return false, while iterable types like plainObjects, Arrays, Strings, Maps, Sets, Generators, ... will be checked by isEmpty and return true/false based on their empty-ness.

It would be very useful to have such an example and/or to have a new helper method for that use case:

`if (_.isIterable(value) && _.isEmpty(value)) {...}`

e.g. to display string `"(empty)"` for values retrieved from JSON string: null, "", [], {}, but not if the value is a Number or Date

**Comment by jdalton** [comment]
An `isIterable` wouldn't be what you're looking for as the name would suggest something similar to the current `isEmpty` behavior. You can always add a mixin for `isEmptyJSON` or something.
