### ISSUE TITLE
Version of lodash/fp/get that invokes a get method if it exists.

### ISSUE THREAD

**Issue by joeytrapp** [lodash/lodash#2287]
When using objects from frameworks like Ember, where the objects expect your to call a `object.get("propName")` method, you can't use curried `_.get` in a composition. I find myself writing this across projects:

```
const get = curry((k, o) => _.isFunction(o.get) ? o.get(k) : _.get(k, o));
```

I like that I can have POJO's or `Ember.Object`s, and this works for both. Could this pattern justify a new function or is there a better way?

**Comment by jdalton** [comment]
Can you explain more why curried `_.get` can't be used?

**Comment by joeytrapp** [comment]
Unless I'm mistaken, `_.get("keyName", object)` will effectively do `object["keyName"]`. If `object` is an `Ember.Object` with a computed property defined for `keyName`, then you must do `object.get("keyName")` or else the computed property won't be computed.

**Comment by jdalton** [comment]
Ah you can use `_.result` which will execute the property if its a function.

**Comment by joeytrapp** [comment]
Not sure that `_.result` applies here:

```
_.result("keyName", { keyName: () => "foo" }); // = "foo"
```

In the case of an Ember.Object, property access always goes through the `.get()` method:

```
let object = Ember.Object.extend({
  keyName: Ember.computed(function() {
    return "foo";
  })
}).create();

object.get("keyName"); // = "foo";
```

**Comment by jdalton** [comment]
If you're wanting to invoke a method you can use `_.invoke`:
```js
fp.invoke('get')(object);
```
or
```js
fp.invokeArgs('get')(args)(object);
```

**Comment by jcheroske** [comment]
Took me a while to find this. Would it be possible to add to the fp docs and describe in more detail the differences between `method`, `invoke`, and `invokeArgs`? Maybe throw `methodOf` in for the sake of completeness. I still don't really get how `method` differs from `invoke`. Thanks for a fantastic lib.
