### ISSUE TITLE
Feature request:  _.push

### ISSUE THREAD

**Issue by bholben** [lodash/lodash#2288]
When transforming data structures and adding to nested arrays (or creating an array on the fly), we frequently see the following pattern:

```javascript
if (_.has(o, 'arr')) {
  o.arr.push(val);
} else {
  _.set(o, 'arr', [val]);
}
```

It would be convenient to replace this with a nice, readable single line.  A lodash push method could follow the same signature as _.has, _.get, _.set, and friends:

```javascript
_.push(o, 'arr', val);
```

For example, when looping through a data set...

```javascript
if (_.has(myCalendar.eventsLookup, [userid, dateKey, 'calendarEntries'])) {
  _.get(myCalendar.eventsLookup, [userid, dateKey, 'calendarEntries']).push(calendarEntry);
} else {
  _.set(myCalendar.eventsLookup, [userid, dateKey, 'calendarEntries'], [calendarEntry]);
}
```
could be simplified to a single line...

```javascript
_.push(myCalendar.eventsLookup, [userid, dateKey, 'calendarEntries'], calendarEntry);
```

**Comment by jdalton** [comment]
I use this pattern in Lodash too though I'm not digging the name `push` as that seems too `Array#push` without the object property angle. I think there's something here but think it needs a bit more baking.

Internally I have a `castSlice` method that performs a slice if it's needed else returns the array without slicing. This may fit into a `cast` method. As with [other requests](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) we'll let the votes roll in.

**Comment by bholben** [comment]
Yeah, the name may be debatable, but I think the pattern is worthy.

I do like having push in the name as `Array#push` is the heart of the operation.  Casting to an array feels more like a backup plan if the array does not exist.  And in this case, I think it's a set that I'm seeking.

Perhaps `_.pushSet()` might make it more clear that it behaves like Lodash has/set/get (at least that's the signature I have in my head at the moment).

**Comment by jisaacks** [comment]
Great idea!! I think a more universal approach would be if `_.get`'s default value optionally `_.set` it on the given path.

What I mean is, you can currently do this:
```javascript
let a = {foo: { bar: [] }};
// exists
_.get(a, ['foo', 'bar']); // []
// not exists
_.get(a, ['foo', 'baz']); // undefined
// not exists with default
_.get(a, ['foo', 'baz'], []); // []

// but the default is not set on the original object:
a.foo.baz === undfined
```

If you could optionally set the default value:
```javascript
a.foo.baz === undfined
_.get(a, ['foo', 'baz'], [], true); // []
a.foo.baz === []
```

Then you could do:
```javascript
_.get(myCalendar.eventsLookup, [userid, dateKey, 'calendarEntries'], [], true).push(calendarEntry);
```

or even other things like:
```javascript
_.get(myCalendar.eventsLookup, [userid, dateKey, 'calendarEntries'], [], true).concat(calendarEntries);
```

Without having to add a `_.concat` or any other needed functionality.

**Comment by jisaacks** [comment]
Actually I just realized that concat wouldn't work still because it doesn't modify in place. Shrugs.

**Comment by bholben** [comment]
Some more thoughts after letting this ferment a little bit...

If we use has/get/set throughout, it looks like this:

```javascript
if (_.has(o, 'arr')) {
  _.get(o, 'arr').push(val);
} else {
  _.set(o, 'arr', [val]);
}
```

I view the second line as the heart of the operation and the fourth line as a backup plan if the array is not already in place.  Since the name `_.push` makes us think it should behave like `Array#push`, perhaps a name like `_.getPush` would work.

I recently did the same thing with `unshift`.  If there is interest, maybe we could create a cousin called `_.getUnshift`...

```javascript
if (_.has(o, 'arr')) {
  _.get(o, 'arr').unshift(val);
} else {
  _.set(o, 'arr', [val]);
}
```

**Comment by jdalton** [comment]
Almost like an `ensureSet`.

**Comment by bholben** [comment]
`set` to me says I'm writing to a plain object, but the underbelly of this is an array operation.  The two scenarios I've outlined thus far are either pushing to the back end of the array or unshifting to the front.  Maybe something like `ensurePush` or `safePush` or `pushSafe`.

This leaves us some flexibility to expand to other array operations later, whereas I think having `set` in the name feels limiting in the future.

**Comment by jdalton** [comment]
> Maybe something like `ensurePush` or `safePush` or `pushSafe`.

:+1:

**Comment by StreetStrider** [comment]
> Maybe something like `ensurePush` or `safePush` or `pushSafe`.

Yeaaah! More prefixes/postfixes/suffixes!!!

**Comment by jdalton** [comment]
@StreetStrider I've noticed your replies becoming a bit less constructive as of late. Try to curtail that.

**Comment by StreetStrider** [comment]
@jdalton, sorry. You're right, I'll try to be a bit more constructive next time.

**Comment by mk-pmb** [comment]
Name idea: getOrAddArray

**Comment by mk-pmb** [comment]
Here's my first draft of [getOrAddKey](https://github.com/mk-pmb/getoraddkey-simple-js). Feel free to join me in testing.

**Comment by thorn0** [comment]
```js
_.set(o, 'arr[]', val);
```
Why not  make `_.set` understand such syntax?

**Comment by jdalton** [comment]
@thorn0 See #1315.

**Comment by mk-pmb** [comment]
Adapted [getoraddkey-simple](https://www.npmjs.com/package/getoraddkey-simple) to now [support paths](https://github.com/mk-pmb/getoraddkey-simple-js/blob/master/doc/demo/fruit.js).

**Comment by yhaiovyi** [comment]
Excuse me for stupid question, but why it's closed? Do we already have any way to add element to the end of an Array? Thanks.

**Comment by yhaiovyi** [comment]
Well I mean FP style, for example `flow(push(4), sortBy(gt))([1, 3, 2])`.

**Comment by mk-pmb** [comment]
@yhaiovyi:
> Excuse me for stupid question, but why it's closed?

It means this issue is not currently on the maintainers' todo list. From the [.github/CONTRIBUTING.md](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md):

> Feature requests […] remain closed until sufficient interest,

Give a thunbs-up reaction on the opening post to vote for it.

**Comment by yhaiovyi** [comment]
Ok thanks.

**Comment by CongAn** [comment]
pushSafe.ts

```ts
import { get, set, isArray } from 'lodash'
import { PropertyPath } from 'lodash'

/**
 * 根据object对象的path路径，
 * 安全向数组（不存则会创建该数组）的末尾添加一个或多个元素，并返回新的长度。
 */
export function pushSafe<V>(object: object, path: PropertyPath, ...items: V[]): number
export function pushSafe<V, T extends object>(object: T,  path: PropertyPath, ...items: V[]): number {
    let array = get(object, path)
    if (array === undefined) {
        set(object, path, array = [])
    }
    if (!isArray(array)) {
        throw new Error('The object path of push is not an array.');
    }
    // @ts-ignore
    return array.push(...items)
}

export default pushSafe
```

**Comment by CongAn** [comment]
pushSafe.ts

```ts
import { get, set, isArray } from 'lodash'
import { PropertyPath } from 'lodash'

/**
 * 根据object对象的path路径，
 * 安全向数组（不存则会创建该数组）的末尾添加一个或多个元素，并返回新的长度。
 * @author https://github.com/CongAn
 */
export function pushSafe<V>(object: object, path: PropertyPath, ...items: V[]): number
export function pushSafe<V, T extends object>(object: T,  path: PropertyPath, ...items: V[]): number {
    let array = get(object, path)
    if (array === undefined) {
        set(object, path, array = [])
    }
    if (!isArray(array)) {
        throw new Error('The object path of push is not an array.');
    }
    return array.push(...items)
}

export default pushSafe
```
