### ISSUE TITLE
Certain Object functions unnecessarily activate getters/Proxy handlers

### ISSUE THREAD

**Issue by not-an-aardvark** [lodash/lodash#2291]
For example:

```js
var myObj = {
  a: 1,
  b: 2,
  get length () {
    console.log('getter for `length` was activated');
    return 3;
  }
}

console.log(_.keys(myObj))

/* Output:
getter for `length` was activated
getter for `length` was activated
getter for `length` was activated
[ 'a', 'b', 'length' ]
*/
```

The issue comes from the fact that `_.keys` internally calls `_.isArrayLike`, which checks for the `length` property. Since several other functions also call `_.keys` internally (such as `_.omit`, `_.pickBy`, etc.), these functions activate the getter as well.

In a similar vein, this also occurs with ES6 Proxies:

```js
var myProxy = new Proxy({}, {get: function (target, key) {
  console.log('getting property for key ' + String(key));
  // do a possibly-time-consuming operation
  return target[key];
}})
```

(The Proxy issue could be solved by adding a `'length' in value` check in `_.isArrayLike`, although this would have a slight performance impact.)

Admittedly, Lodash makes no guarantees about which properties it will/won't access, and this is a fairly uncommon use-case. However, it seems like accessing the `length` property is unnecessary in this case since `Object.keys` could be used instead.

**Comment by jdalton** [comment]
Yap, not going to bother trying to avoid this. Checking for `length` is part of the package and not something we will avoid.

**Comment by not-an-aardvark** [comment]
Thanks for looking into it. I figured as much, but thought I may as well bring it up.
