### ISSUE TITLE
Trailing periods cause unexpected results in any path related function (get, set, ..)

### ISSUE THREAD

**Issue by cjke** [lodash/lodash#2292]
When a given path includes one or more trailing periods, path is evaluated instead of returning `defaultValue`. 

```
console.log(_.get({
  house: {
    pets: {
      dog: {
        name: "Max",
        age: 5
      }
    }
  }
}, 'house.pets.dog.', false)); // Outputs { name: "Max", age: 5 }
```

It's not world ending, but led to a few strange bugs that were weird to track down. For now, I am `_.trim(path, '.')`'ing paths before passing them into `get`. 

Totally cool if it's a non-issue, or if I misunderstood the expected behaviour. 

Btw: Fantastic library, thanks for all the work

http://jsbin.com/jaqexobusu/edit?js,console

**Comment by jdalton** [comment]
Hi @cjke!

Our path method will try to make a path out of your input. You can test it by doing:
```js
_.toPath('house.pets.dog.');
// => ["house", "pets", "dog"]
```

**Comment by cjke** [comment]
Ah nice one! Ironically I was doing `join(fields, ".")` to get the path in the first place, where fields is an array. Talk about a derp moment!

Second Btw: Thanks for all the good work, and thanks for being so open to communication on github.

**Comment by jdalton** [comment]
>  Ironically I was doing join(fields, ".") to get the path in the first place, where fields is an array.

:P our methods accept a path array.

> Thanks for all the good work, and thanks for being so open to communication on github.

Thanks for bringing up the path issue. I went back and forth when implementing it on its behavior around cases like this.
