### ISSUE TITLE
lodash.reject 4.3.0 does not pull in lodash._baseeach

### ISSUE THREAD

**Issue by leftmostcat** [lodash/lodash#2295]
After running `npm install --save lodash.reject` and adding lodash.reject to the requires for a module, which is then built with browserify, I receive an error when it attempts to access lodash._baseeach. Looking at the package.json for the module, _baseeach is not on the list of requirements.

**Comment by jdalton** [comment]
Looks fine to me.
```bash
lodash.reject@4.3.0 /Users/jdalton/Projects/bar/node_modules/lodash.reject
├─┬ lodash._basefilter@4.0.1
│ └── lodash._baseeach@4.1.2
└─┬ lodash._baseiteratee@4.6.1
  └── lodash._stringtopath@4.7.1
```

**Comment by leftmostcat** [comment]
On further investigation, this may be an interaction with lodash.filter. The failure is happening in a browserify "dup" entry for lodash._baseeach. Unsure whether the root of this issue would be browserify or lodash, so I'll investigate further.
