### ISSUE TITLE
lodash/fp cherry picking

### ISSUE THREAD

**Issue by epiloque** [lodash/lodash#2296]
Hello,

require `lodash/isString` brings in 1.13 kB, while `lodash/fp/isString` 159.39 kB. In my understanding it should be possible to precompile the `lodash/fp/convert.js` functionality. If this is planned I would like to help, where should I start?

Thank you

**Comment by jdalton** [comment]
Hi @epiloque!

When dealing with size please report sizes minified and gzipped. 
lodash/fp will have a ~2kb base size regardless of build for the conversion script.

**Comment by epiloque** [comment]
@jdalton thank you for clarification!
