### ISSUE TITLE
Reason why isEqual failed

### ISSUE THREAD

**Issue by kownacki** [lodash/lodash#2297]
Hi,

your isEqual function is totally great but it's difficult to print what is different in two objects. Can you provide something like [here](https://www.npmjs.com/package/is-equal), that is an additional function named something like isEqualWhy which prints some concise human-readable info.

I can do something like that by myself but I will never can be sure that my message will be valid.

**Comment by jdalton** [comment]
Hi @kownacki!

I think this! I think it avoids bringing in heavier diffing methods.
We'll keep an eye on [user demand](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) for it.

**Comment by bholben** [comment]
This would be really cool as an optional third arg in `_.isEqual`.

**Comment by jdalton** [comment]
@bholben I want to avoid overloading methods more so it'd likely be a separate method.

**Comment by StreetStrider** [comment]
@kownacki, why not just use is-equal then?

**Comment by kownacki** [comment]
@StreetStrider Because I found bugs in https://github.com/ljharb/is-equal . You can see I even created an issue :( . Lodash seems more trustworthy, though lacks **that** functionality.

**Comment by kownacki** [comment]
@jdalton I'm still searching for solution of this problem. It actually boils down to a good object diff library. There is a nice library https://www.npmjs.com/package/diff for strings in javascript, but I can't find a good reliable diff maker for objects. Most of them are buggy (for example fail on circular objects) or don't provide sufficient configuration and options. Are you planning on providing some kind of solution - best if it would be compatible with `_.isEqual` - or I was thinking about writing something like this myself and I could make a pull request.

**Comment by jdalton** [comment]
@kownacki 
> Are you planning on providing some kind of solution

I probably won't dig in until there's a little more interest in the feature from others.

> or I was thinking about writing something like this myself and I could make a pull request.

You could write it as a mixin first, but don't bother with a pull request until there's more interest.
