### ISSUE TITLE
isEqual checks constructor but should check prototypes?

### ISSUE THREAD

**Issue by kownacki** [lodash/lodash#2298]
```javascript
var _ = require("lodash");

function A() {}
function B() {}
B.prototype.constructor = A.prototype.constructor;

var a = new A;
var b = new B;

console.log(_.isEqual(a, b));
```

Hi,

I was just thinking if the way that `isEqual` works is 100% right. In the example we can (even though it's questionable) change constructor, now objects share constructor but don't share prototypes, and `isEqual` returns true. 

Wouldn't be smarter to compare prototypes like that: `Object.getPrototypeOf(a) === Object.getPrototypeOf(b)` to assure the same "class". Then we are also sure that constructors are the same. Also changing prototype of an object is more restricted than changing constructor.

**Comment by jdalton** [comment]
The `_.isEqual` method is an equivalence method as such there's some wiggly room for its detections. I think it's reasonable to see these values as equiv.

**Comment by kownacki** [comment]
@jdalton Thanks for the answer. It's reasonable indeed, but IMO it would be nice to have it documented in the API what you understand by equivalence. :)
