### ISSUE TITLE
connection between `_.clone` and `_.isEqual`

### ISSUE THREAD

**Issue by kownacki** [lodash/lodash#2299]
Is it guaranteed that: `_.isEqual(a, _.clone(a))` and  `_.isEqual(a, _.cloneDeep(a))` ?

**Comment by jdalton** [comment]
It depends on if the value is cloneable or not.

**Comment by kownacki** [comment]
So if cloning succeeds, it is true?

**Comment by Alexsey** [comment]
while ```a``` may be clonable it may contain some inner values that are not clonable. So clone would have empty objects on those places and ```_.isEqual``` will return ```false```

**Comment by kownacki** [comment]
So if cloning all inner values succeeds then... ?

**Comment by jdalton** [comment]
What are you driving at?

**Comment by jdalton** [comment]
Are you looking to file a bug? Is this an issue you've hit in your usage?

**Comment by kownacki** [comment]
@jdalton Yes I want to use in that way. I need to make a deep copy and then compare it to - maybe the original object from which the copy was made or other equal one :)

**Comment by jdalton** [comment]
It should be fine unless you hit a value that's unsupported by clone.

**Comment by kownacki** [comment]
I thought so :) . Thank you!
