### ISSUE TITLE
no gulpfile.js

### ISSUE THREAD

**Issue by fernandofas** [lodash/lodash#2301]
Hi there,

I installed gulp-template and followed the instructions, but seems like there is an issue as the gulpfile.js is not generated and because of this issue, I can't use it.

Any idea why this is happening or is missing some instructions?

https://github.com/sindresorhus/gulp-template

Also, when you posted:

Usage

src/greeting.html

<h1>Hello <%= name %></h1>

It does not mean anything to me as I can't find the gulpfile.js.

Cheers,

fernando fas
fernandofas@gmail.com

**Comment by jdalton** [comment]
Hi @fernandofas!

This is not a Lodash issue.
Ping [gulp-template/issues](https://github.com/sindresorhus/gulp-template/issues).
