### ISSUE TITLE
Feature Request: Distribute Array

### ISSUE THREAD

**Issue by prose100** [lodash/lodash#2302]
This feature would distribute the elements of an input array into output arrays consisting of every nth element.  For example:

Arguments:
array (Array): The array to process.
nth (number):  The number of indicIes between the elements of the output arrays.

_.distribute(array, nth)
_.distribute(['a', 'b', 'c', 'd','e','f'], 2);
// → [['a', 'c', 'e'], [b', 'd', 'f']]

_.distribute(['a', 'b', 'c', 'd', 'e', 'f'', 'g', 'h'], 3);
// → [['a', 'd', 'g'], [b', 'e', 'h'],['c', 'f']]

Use cases:
1) Take sequential data (input array) and place it into categories (output arrays).
2) Distribute the elements of an array as though one is dealing cards.

**Comment by jdalton** [comment]
Hi @prose100!

I think you're looking for [_.chunk](https://lodash.com/docs#chunk).

**Comment by jfmengels** [comment]
@jdalton Doesn't look like `chunk` to me.
Looks like @prose100 wants a `chunk` like function, but that doesn't take the `n` first elements and then the `n` second elements, but takes all the `n*k`th element for every `k`, until the end of the array is reached.
`chunk` would create `length / n` sub-arrays, while `distribute` would create `n`

```js
_.chunk([1, 2, 3, 4, 5], 2);
// => [[1, 2], [3, 4], [5]]

_.distribute([1, 2, 3, 4, 5], 2);
// => [[1, 3, 5], [2, 4]]
```

**Comment by jfmengels** [comment]
@prose100 We'll keep an eye on [user demand](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) for it.

**Comment by prose100** [comment]
Sounds good.  Thanks, guys.

**Comment by martinbean** [comment]
Just came across the need for this, so would definitely be handy if it were added to lodash.

**Comment by aaronpeterson** [comment]
No comments for 2 years and then...

**Comment by EdwardDrapkin** [comment]
literally 3 lines of code https://repl.it/repls/SmoothFondNet

**Comment by martinbean** [comment]
@EdwardDrapkin No one said it wasn’t possible in a few lines of code. Would just be nice to use a library method to do so in literally 1 line.
