### ISSUE TITLE
Feature request: _.isCloneable

### ISSUE THREAD

**Issue by kownacki** [lodash/lodash#2304]
Hi

There is a lot of cases when `_.clone` falls down to returning empty object. One can create such function by himself/herself, just checking for supported values from docs. But it would be great to have such thing already available :)

**Comment by jdalton** [comment]
Hi @kownacki!

We'll [keep an eye on](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) user demand.
