### ISSUE TITLE
What is the reason _.includes does not allow a custom callback?

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#2305]
I often see a code that looks like:

```js
const isLoading = !!_.find(seriesIds, seriesId => loading[seriesId]);
```

The reason for this is that `_.includes` does not allow a custom callback, i.e.

```js
const isLoading = _.includes(seriesIds, seriesId => loading[seriesId]);
```

Is there a reason for this?

**Comment by gajus** [comment]
Furthermore, the `!!_.find` would result in false positives when searching for a falsy value (observation by: http://stackoverflow.com/a/34485152/368691).

**Comment by jdalton** [comment]
The `_.includes` method is based on `String#includes` and `Array#includes`. Internally we have an `includesWith` like helper but I haven't exposed that yet.

**Comment by jfmengels** [comment]
@gajus I think that _.any / _.some would do trick in most cases.

**Comment by gajus** [comment]
@jfmengels Good point. `_.some` makes sense.
