### ISSUE TITLE
toNumber vs toInteger

### ISSUE THREAD

**Issue by triadium** [lodash/lodash#2306]
I need convert some attributes from "string" to "integer" and "float" values. I try use "toNumber" and "toInteger" functions and  "toInteger" function works as expected,  but "toNumber" does not.
```javascript
_.toNumber(null) === _.toInteger(null) // true
_.toNumber(void 0) === _.toInteger(void 0) //false
_.toNumber('abc') === _.toInteger('abc') //false
```

**Comment by jdalton** [comment]
The `_.toNumber` and `_.toInteger` methods are distinct and different.

The `_.toNumber` method will convert values to a number type which includes `NaN` and `Infinity`.

**Comment by triadium** [comment]
I'm understood, thank you.
Is there a symmetric function for fractional numbers? (toFloat?)

**Comment by jdalton** [comment]
There isn't yet, but there should probably be.
