### ISSUE TITLE
omitBy if using babel-polyfill

### ISSUE THREAD

**Issue by klimashkin** [lodash/lodash#2308]
Hi!
In IE browser if I use babel and `_.omitBy`, some values are suddenly `undefined`, because core.js (part of babel-polyfill) inserts, for example, some Symbols in object prototype.
So sometimes I can get an error in IE, whilst other modern browsers work correct.

Is it possible to split omitBy by two methods: over only own and own and inherited properties? Something  like `omitBy` and `omitInBy`

**Comment by jdalton** [comment]
Symbols can't reliably be shimmed so by using the babel-polyfill you'll run into issues like this.

**Comment by jdalton** [comment]
Can you point me to the shim. Might be a bug for babel-polyfill to tackle.

**Comment by klimashkin** [comment]
I now, that's why I'm asking about `omit` (and `pick`) methods alternatives to iterate only by own properties. How `_.assign`, `_.for` have

**Comment by jdalton** [comment]
The `_.omit` method is tricky because it's greedy and makes the assumption that you want all-the-things except whatever you omit.

**Comment by jdalton** [comment]
core-js does a lot of hacky things to get pseudo/partial support.
My recommendation is to avoid it and use something like [es-shim](https://github.com/es-shims/es6-shim) as they're more conservative in their approach.

**Comment by klimashkin** [comment]
Maybe @zloirock could help to figure out how to avoid Symbols in object prototype?..

**Comment by klimashkin** [comment]
Because core-js is very popular http://npm-stat.com/charts.html?package=core-js&author=&from=2015-05-06&to=2016-05-05
And we can't just say everybody: just don't use it and don't use anything that extends object prototype

**Comment by jdalton** [comment]
> don't use anything that extends object prototype

That's a basic JS thing. See [Object.prototype is verboten](http://erik.eae.net/archives/2005/06/06/22.13.54/).

**Comment by klimashkin** [comment]
Yes, of course, nobody, being of sound mind and body, extends Object.prototype in application project by themselves. 
But thousands use babel with polyfill or just core-js. And they can't just switch to something else)
That's why something should be done on one of side (core-js or lodash)

**Comment by klimashkin** [comment]
As workaround I will use `_.transform` for now

**Comment by jdalton** [comment]
> But thousands use babel with polyfill or just core-js. And they can't just switch to something else)

When using projects that modify `Object.prototype` it's user beware. If the `Object.prototype` issue is causing you grief then you have options. One of those options is to cherry-pick which shims you import. 

This is not a Lodash issue. I'm not inclined to help promote bad practices.

**Comment by zloirock** [comment]
> Maybe @zloirock could help to figure out how to avoid Symbols in object prototype?

Sure. See [this section](https://github.com/zloirock/core-js#caveats-when-using-symbol-polyfill). You can call `Symbol.useSimple()`.

> My recommendation is to either cherry-pick from core-js or avoid it and use something like es5-shim and es6-shim as they're more conservative in their approach.

And forget, for example, about half `babel` features like `for-of`, spread, destruction.

> That's a basic JS principle.

Some other JS basic principles - iterate only over own properties and ignore non-enumerable properties. It's the first issue about `core-js` `Object.prototype` properties for 2 year and tens of million downloads.

**Comment by klimashkin** [comment]
Yes, I don't know why we should iterate by default over own _and_ inherited properties.
it's very rare when developers need to work with full inheritance chain be default, to be honest I can't recall in my mind such case for the last several years.
Iterate over inherited properties - it's the exception rather than the rule, don't know why `lodash` have such behavior by default (but only in some methods, others have options for it)

**Comment by jdalton** [comment]
@zloirock
> And forget, for example, about half babel features like for-of, spread, destruction

Maybe though many of the Babel helpers like
```js
a(...b);
```
generates
```js
function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

a.apply(undefined, _toConsumableArray(b));
```
which leaves wiggly room for shims.

> Some other JS basic principles - iterate only over own properties and ignore non-enumerable properties. 

Naw, there's a place for inherited enumerable properties.  As I mentioned it's user beware with projects that augment `Object.prototype`. I don't know many projects that support it. I know for example jQuery doesn't.

Thanks for offering a workaround with `Symbol.useSimple()`.

**Comment by zloirock** [comment]
> Naw, there's a place for inherited enumerable properties.

Here they should be non-enumerable.

**Comment by jdalton** [comment]
@klimashkin Which version of IE are you testing?

**Comment by klimashkin** [comment]
IE11

**Comment by jdalton** [comment]
Do you know which property is getting enumerated that's causing a problem?

**Comment by klimashkin** [comment]
If I write this:
```
_.omitBy({}, (value, key) => {console.log(value, key)});
```
I get in IE11 this:
```
undefined Symbol(react.element)_l.x1qrsso0w71
undefined Symbol()_m.x1qrsso0w71
undefined Symbol()_n.x1qrsso0w71
```

**Comment by jdalton** [comment]
Cool so those are symbol values. Lodash will include symbols. I'm guessing because it's a shim that these symbols show up as enumerable properties when reassigned. Can you take the result:
```js
var o = _.omitBy({}, _.noop);
Object.keys(o);
```

**Comment by jdalton** [comment]
Oh also can you post the result of
```js
Object.keys(Object.prototype);
```
If `Object.keys` is also wrapped to avoid them you can try:
```js
for (var key in Object.prototype) console.log(key);
```

**Comment by klimashkin** [comment]
`Object.keys(_.omitBy({}, _.noop)));` returns empty array

`Object.keys(Object.prototype)` returns empty array also

`for (var key in Object.prototype) console.log(key);` no logs

**Comment by klimashkin** [comment]
If I put `Symbol.useSimple();` before `_.omitBy({}, (value, key) => {console.log(value, key)});` result is the same
```
 undefined Symbol(react.element)_l.onflshlvowe 
 undefined Symbol()_m.onflshlvowe 
 undefined Symbol()_n.onflshlvowe 
```

**Comment by jdalton** [comment]
Right. Lodash will include inherited symbols if present (it's greedy).
I think that just means someone put symbols on the `Object.prototype`.
Try:
```js
Object.getOwnPropertySymbols(Object.prototype)
```

**Comment by klimashkin** [comment]
`Object.getOwnPropertySymbols(Object.prototype)`:
```
Symbol(react.element)_l.888c745tpn5, Symbol()_m.888c745tpn5, Symbol()_n.888c745tpn5
```

**Comment by jdalton** [comment]
Woot! So not an issue in Lodash or core-js! :tada:

Looks like react smth smth.

**Comment by jdalton** [comment]
On second thought lets [cover our bases](https://github.com/zloirock/core-js/blob/38801b56dcf67d9a6a01186a4fd1152417c06119/modules/es6.symbol.js#L127-L133).

Can you try this one with `Symbol.useSimple()` and `Symbol.useSetter()` in isolation (no react or other code):
```js
console.log('before');
console.log(Object.getOwnPropertySymbols(Object.prototype));
var o = {};
o[Symbol('a')] = 'apple';
console.log('after');
console.log(Object.getOwnPropertySymbols(Object.prototype));
```

**Comment by jdalton** [comment]
The result should be:
```js
before
Array[0]
after
Array[0]
```

**Comment by th0r** [comment]
@jdalton So maybe reopen this issue until it will be clear what causes a problem?
I understand that `Issues 0` warms your heart but it won't solve a problem.

**Comment by StreetStrider** [comment]
Haha, polyfills!
![polyfill users](https://cloud.githubusercontent.com/assets/2124761/15071959/905e20c8-13a0-11e6-9208-62cd3ad94d56.gif)

Just use ES5.

**Comment by jdalton** [comment]
@th0r 
> So maybe reopen this issue until it will be clear what causes a problem?

Naw. It's not a Lodash problem.

@klimashkin 
You might have better luck with the Symbols shim [es-shims/get-own-property-symbols](https://github.com/es-shims/get-own-property-symbols).

**Comment by zloirock** [comment]
If you uses `getOwnPropertySymbols(Object.prototype)` and, after that, `propertyIsEnumerable` or `getOwnPropertyDescriptor` for check enumerability on `Object.prototype` - it can be an issue with `core-js`. `core-js` here isn't fully strict for better performance.

I'll explore it and if it's related I will fix it.

`get-own-property-symbols` package has the same problem with `getOwnPropertySymbols(Object.prototype)` and (strange) crashes on `propertyIsEnumerable` or `getOwnPropertyDescriptor` with `Object.prototype` and symbol arguments.

**Comment by klimashkin** [comment]
@jdalton So, with your example, clean project in IE, only `lodash` and `babel-polyfill`:
With or without `Symbol.useSetter()`:
```
 before 
 []
 after 
 [Symbol(a)_l.2ao371za8jq]
```

With `Symbol.useSimple()`:
```
 before 
 []
 after 
 []
```

`_.omitBy({}, (value, key) => {console.log(value, key)});` 
==> nothing

_But_ if I also add `import React from 'react';`

And result of your example becomes:
With or withou `Symbol.useSetter();`:
```
 before 
 [Symbol(react.element)_l.lj09h3miq9c]
 after 
 [Symbol(react.element)_l.lj09h3miq9c, Symbol(a)_m.lj09h3miq9c]
```

With `Symbol.useSimple();`:
```
 before 
 [Symbol(react.element)_l.8apqahh90om] 
 after 
 [Symbol(react.element)_l.8apqahh90om]
```

`_.omitBy({}, (value, key) => {console.log(value, key)});` 
==> `undefined Symbol(react.element)_l.kw4ozctwn15`

So, you are right, reason in React, but I don't understand what does it do. I thought, it just must have used Symbol object, regardless its origin - native or polyfill

**Comment by klimashkin** [comment]
@zloirock 
console.log(Object.getOwnPropertySymbols(Object.prototype)); // []
console.log(Object.propertyIsEnumerable('prototype')); // false

If I add React:
console.log(Object.getOwnPropertySymbols(Object.prototype)); // [Symbol(react.element)_l.lupdr038qx8]
console.log(Object.propertyIsEnumerable('prototype')); // false

**Comment by klimashkin** [comment]
This line in react:
`typeof Symbol === 'function' && Symbol['for'] && Symbol['for']('react.element')`

With babel-polifyll, if I type:
`Object.keys(typeof Symbol === 'function' && Symbol['for'] && Symbol['for']('react.element'))`

in Chrome: `[]`
in IE: 
```
_k {
	0 : "_k"
} 
```

**Comment by zloirock** [comment]
@klimashkin I mean
```js
Object.prototype.propertyIsEnumerable(Object.getOwnPropertySymbols(Object.prototype)[0]);
```

**Comment by klimashkin** [comment]
@zloirock ok, got it!

```
import 'babel-polyfill';
console.log(Object.prototype.propertyIsEnumerable(Object.getOwnPropertySymbols(Object.prototype)[0])); 
// false
```

```
import 'babel-polyfill';
import React from 'react';
console.log(Object.prototype.propertyIsEnumerable(Object.getOwnPropertySymbols(Object.prototype)[0])); 
// true
```

**Comment by jdalton** [comment]
@klimashkin 
> With or without `Symbol.useSetter()`:
```
 before 
 []
 after 
 [Symbol(a)_l.2ao371za8jq]
```

Sweet. Looks like a core-js issue. Mind filing an issue [there](https://github.com/zloirock/core-js/issues).

**Comment by klimashkin** [comment]
@jdalton Yea, seems like not lodash. But It would'n happened if lodash had `omit` only over own properties ;)

**Comment by jdalton** [comment]
Take a hike.
