### ISSUE TITLE
_.roundTo(number, interval);

### ISSUE THREAD

**Issue by RealAdamSinger** [lodash/lodash#2310]
```
_.roundTo = function(number, interval){
  return (_.round(number / interval) * interval);
}
```

Would a "round to" serve a place in lodash? 
It would be used to round a value to a certain interval. 
Useful for applications such as 
- humanizing certain values like duration where you would want the value to be rounded to an interval of 1/4 hour or percentages if you only care about half or whole percents.
- matching a value to a measurement's lowest form such as imperial's 1/64 or matching points to an axis' interval.
- smoothing applications where you would not want a calculated value to change until it has changed by a certain interval

**Arguments**
number (number): The number to round.
interval (number): The interval used to round the number to.
**Returns**
(number): Returns the rounded number.

**Example**
```
_.roundTo(42.2, 0.25);
// → 42.25

_.roundTo(42.6, 0.25);
// → 42.5

_.roundTo(42.2, 0.5);
// → 42

_.roundTo(42.6, 0.5);
// → 42.5

_.roundTo(42.2, 5);
// → 40

_.roundTo(42.6, 5);
// → 45
```

**Comment by jdalton** [comment]
It's something to consider!
Right now we have a `precision` param for [_.round](https://lodash.com/docs#round).

**Comment by RealAdamSinger** [comment]
yeah, I was thinking of the relationship between `_.roundTo` and `_.round` and really `interval` is just a more granular form of `precision` since it accomplishes the same thing when you pass in an interval of base 10 but opens up some new possibilities..
```
_.roundTo(10.545, 10)
// → 10
_.roundTo(10.545, 1)
// → 11
_.roundTo(10.545, .1)
// → 10.5
_.roundTo(10.545, .01)
// → 10.55
```
Technically this could replace round but the current functionality of `_.round` is very nice too

**Comment by gajus** [comment]
@jdalton Do you have some sort of a script that extracts issues with the most votes? (Votes being the thumbs up reactions.)

**Comment by jfmengels** [comment]
@gajus You can do it with GitHub's sort: https://github.com/lodash/lodash/issues?q=is%3Aissue+label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc

**Comment by gajus** [comment]
This would be a nice addition, although I am unsure about the name. `roundTo` is as generic as existing `round`. "round to" could equally mean "round to precision" (which is the current `_.round` function).

Can it be named something more specific, e.g. `roundToInterval`?

**Comment by RealAdamSinger** [comment]
@galus I've been thinking that completely replacing `_.round` with this functionality would probably be best. It would require an API change which can be messy for developers updating to the next version but its also important to keep this library concise and free of redundancies

**Comment by RealAdamSinger** [comment]
I should to point out is my posted function suffers from floating-point issues. So that would need to be solved.

**Comment by Galus** [comment]
And I thought I was popular or something.

**Comment by c-dante** [comment]
This feels a little awkward, since you can argue the same functionality for `_.floor` and `_.ceil`

You could have a `_.nice` or `_.interval` or `_.bin` -- things similar to [D3's `.nice()`](https://github.com/d3/d3/wiki/Quantitative-Scales#linear_nice).

Feels weird to have round take a predicate -- almost a different method.

I'd also be interested in a signature like:
```js
_.floorInterval( value, predicate )
_.ceilInterval( value, predicate )
_.roundInterval( value, predicate )
```

Where `predicate` determines what "interval size" to round by.

**Comment by gajus** [comment]
> I'd also be interested in a signature like:

Would it not make more sense to accept the rounding function as the third parameter?

**Comment by RealAdamSinger** [comment]
> This feels a little awkward, since you can argue the same functionality for _.floor and _.ceil

Ah good catch, you're right, they should have matching API's. 
In that case, the same justification I propose for modifications to round's API would also apply to `_.floor` and `_.ceil` 
I recommend the following api. No need to add new functions
```
_.floor( value, interval )
_.ceil( value, interval )
_.round( value, interval )
```
the behaviour of interval would be the same as my recommendation for `_.round` but with flooring and ceiling behaviour of course.

```
_.floor(42.2, 0.25);
// → 42

_.floor(42.6, 0.25);
// → 42.5

_.floor(42.2, 0.5);
// → 42

_.floor(42.6, 0.5);
// → 42.5

_.floor(42.2, 5);
// → 40

_.floor(42.6, 5);
// → 40
```

```
_.ceil(42.2, 0.25);
// → 42.25

_.ceil(42.6, 0.25);
// → 42.75

_.ceil(42.2, 0.5);
// → 42.5

_.ceil(42.6, 0.5);
// → 43

_.ceil(42.2, 5);
// → 45

_.ceil(42.6, 5);
// → 45
```
Passing intervals of base 10 would cover the current functionality of these functions
```
_.floor(425, 10);
// → 420

_.ceil(425, 10);
// → 430

_.floor(42.2, 1);
// → 42

_.ceil(42.2, 1);
// → 43

_.floor(42.255, .01);
// → 42.25

_.ceil(42.255, .01);
// → 40.26
```
 
> It would require an API change which can be messy for developers updating to the next version but its also important to keep this library concise and free of redundancies.

**Comment by c-dante** [comment]
I'd be okay with this as well -- precision is a special case of "interval" where you use base 10 numbers.
