### ISSUE TITLE
_.clone returns empty object in ie10/11

### ISSUE THREAD

**Issue by peterver** [lodash/lodash#2312]
i have a nested object with integers as keys for object values, which in turn have more nested objects inside of them. 

_.clone for some reason returns an empty object in ie10/11, i also tried _.cloneDeep, but this returns the same result. When doing ( a little bit hacky i know ) JSON.parse(JSON.stringify(myObject)); it does return  a 'clone' of the object.

I am using lodash 4.6.1

**Comment by jdalton** [comment]
I can't repro with a plain object. For unsupported object we return an empty object.
Is there anything special about your object (is it a property of a plugin or host object)?

**Comment by peterver** [comment]
the object itself is used in an angular ng-repeat, so it might be that there is some funky stuff going on due to angulars internals (such as $$hashkey) being mapped to it.

I use _.clone quite often and this is the first time i've seen it happen, strange thing is that this works perfectly in chrome/ff/safari. But ie10 is going haywire on it :').

For now i'm perfectly fine with JSON.parse + JSON.stringify, but if i encounter this issue again, i'll report in more detail.

**Comment by jdalton** [comment]
It may be detected as a host object. What does coercing it to a string do?

myObj+''

**Comment by peterver** [comment]
the output is the same on both chrome and ie, tried with the following statements to determine if there was a difference : 

`
console.log(typeof myObj);
console.log(myObj + '');
console.log(_.isObject(myObj));`

and the output was 

`object
[object Object]
true`

**Comment by jdalton** [comment]
What is
```js
typeof myObj.toString
```

**Comment by peterver** [comment]
string

**Comment by jdalton** [comment]
In modern enviros:
```js
ar o = { 'toString': '' };
o+''
// => Uncaught TypeError: Cannot convert object to primitive value(…)
```

**Comment by jdalton** [comment]
In older IE it's allowed and usually something on host-objects so that hits a `isHostObject` check and returns `true` and host-objects are not supported by clone so an empty object is returned.

**Comment by peterver** [comment]
i've commented out a large chunk of the mapping code, and even this is returning {}

var newData = {};

_.forOwn($scope.myData, function (val, key) {
     newData[key] = {
          varA : [],
     };
});

_.clone(tmp);

**Comment by peterver** [comment]
could it be that IE behaves differently to objects with numeric literals as keys ?

**Comment by jdalton** [comment]
I don't believe that would be the case here. What does `_.keys(newData)` report?

**Comment by peterver** [comment]
i'm still having this issue, for the time being i have written this replacement : 

`function copy (cursor) {
        //  Array
        if (_.isArray(cursor)) {
            return cursor.reduce((cursor_acc, cursor_value) => {
                cursor_acc.push(copy(cursor_value));
                return cursor_acc;
            }, []);
        }

        //  Object
        if (_.isObject(cursor)) {
            return (cursor.hasOwnProperty('clone') && _.isFunction(cursor.clone))
                ? cursor.clone()
                : Object.keys(cursor).reduce((cursor_acc, cursor_key) => {
                    cursor_acc[cursor_key] = copy(cursor[cursor_key]);
                    return cursor_acc;
                }, {});
        }

        if (_.isElement(cursor)) return cursor.cloneNode(true);
        if (_.isRegExp(cursor)) return new RegExp(cursor);
        if (_.isDate(cursor)) return new Date(cursor);

        return cursor;
    }`

**Comment by jdalton** [comment]
Ah, [_.clone](https://lodash.com/docs/#clone) doesn't support dom elements and will return an empty object if they are passed as the initial argument. We recommend using [_.cloneWith](https://lodash.com/docs/#cloneWith) to accommodate that.
