### ISSUE TITLE
nth documentation misleading

### ISSUE THREAD

**Issue by olsonpm** [lodash/lodash#2313]
So I understand I'm the only one who was confused by this enough to write an issue and that this is minute, but here goes:

> Gets the nth element of array. If n is negative, the nth element from the end is returned.

When reading "nth" element where the function takes an integer, I naturally replace n with the integer.

4th, 5th, etc. (i.e. 1 based, not 0)

When really what this method is doing is grabbing index n.  Thus I propose changing the documentation to:

> Gets the element at index n of array. If n is negative, the nth element from the end is returned.

Which begs the question why the function is called 'nth' - seems like a silly reason to cause an api change though.

**Comment by jdalton** [comment]
Thanks! Ya `nth` is a bit off in naming but most seem to get the gist.

**Comment by olsonpm** [comment]
Thanks much.
