### ISSUE TITLE
Feature Request: function operations

### ISSUE THREAD

**Issue by jayflo** [lodash/lodash#2315]
Note: I first encountered these patterns using [Haskell arrows](https://hackage.haskell.org/package/base-4.8.2.0/docs/Control-Arrow.html).

In the same way fp operates on collections of data, It would be nice if there were a few more lodash functions that let you build functions from *collections of functions* to operate on those data collections.  Proposed additions:  `split`, `fanout` and `ev` (evaluate).  Quick examples:

```js
var split = _.split(_.min, _.max);
split([1,2,3]) // [1, 3]

var split2 = _.split(_.partialRight(_.pick, 'a'), _.partialRight(_.omit, 'a'));
split2({ a: 1, b: 2, c: 3 }) // [{ a: 1}, { b: 2, c: 3}]

var fan = _.fanout(_.min, _.max);
fan([[1,2,3], [4,5,6]]) // [1, 6]

var fan2 = _.fanout(_.partialRight(_.pick, 'a'), _.partialRight(_.omit, 'a'));
fan2([{ a: 1, b: 2, c: 3 }, { a: 4, b: 5, c: 6}]) // [{ a: 1}, { b: 5, c: 6}]

[_.floor, _.round, _.ceil].map(_.ev(3.14)) // [3, 3, 4]
```

Essentially, 

* `split` takes functions that look like `X -> Y1, X -> Y2, ...` and creates a function that looks like `X -> [Y1, Y2, ...]`. Of course `X` can itself be a collection.
* `fanout` takes functions that look like `X1 -> Y1, X2 -> Y2, ...` and creates a function that looks like `[X1, X2, ...] -> [Y1, Y2, ...]`.  Of course the `X*` can be collections.
* `ev` is just syntactic sugar

`split` and `fanout` can provide more fine grained control of function application when chaining, and fill in some inconvenient holes.  For instance, 

```js
_(la)
.zip(la)
.map(_.spread(function(a, a) {
    return [f(a), g(a)];
}))
.map(_.spread(function(fa, ga) {
    return [h(fa), k(ga),  ga];
}))
.map(_.spread(_.set))
.value();
```

It is not `zip`s fault that `la` is not duplicated, nor should anonymous functions have to piece together the results of functions defined elsewhere.  This should be as clean as

```js
_(la)
.map(_.split(f, g))
.map(_.fanout(h, _.split(k, _.identity)))
.map(_.spread(_.set))
.value()
```

Note: all proposed additions should take any number of arguments, and in the case of `split` and `fanout`, should also accept an array of functions.

I'd be more than happy to write code and submit a PR if this gets enough votes!  I think it would provide a lot of nice functionality!

**Comment by jdalton** [comment]
Thanks @jayflo!

We'll keep an eye [on the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by jamesrom** [comment]
+1 for _.ev

If my understanding is correct, `_.ev(3.14)` is shorthand for `function() { return 3.14 }`.

While ES2016 arrow functions (e.g., `() => 3.14`) might reduce the need for _.ev, it's such a simple feature that makes a lot of sense for those of us that don't have access to arrow functions.

**Comment by jayflo** [comment]
Yah sorry...that's the only one I didn't explain further.  Actually, what you're describing is more similar to  `_.constant`, i.e.

```js
_.constant = function(something) {
    return function() {
        return something;
    };
};
```

`_.ev` is this:

```js
_.ev = function() {
    var args = Array.prototype.slice.call(arguments);

    return function(f) {
        return f.apply(null, args);
    };
};
```

so it just saves up the arguments passed to it and applies them to future functions.  Usually when you map over an array `[...].map(myFunc)` you consider the items in the array as the *arguments* to the `map`ping function `myFunc`.  

`_.ev` on the other hand allows you to map *arguments* over arrays of *functions*.  For example, if you have a data structure `ds` and a sequence `o1, o2, ..., oN` of operations to perform on the data structure that you build up over time, you can then "dispatch" those operations via

```js
[o1, o2, ..., oN].map(_.ev(ds))
```

If you like arrows, (a curried) `apply` works like `(X --> Y) --> X ---> Y` and (a curried) `_.ev` works like `X --> (X --> Y) --> Y`

**Comment by jridgewell** [comment]
`ev` would actually be pretty cool.

**Comment by StreetStrider** [comment]
@jridgewell I personally like all three proposals.

**Comment by jayflo** [comment]
Really `_.ev` should (maybe) probably be called `_.eval` or `_.evaluate` because it returns a function that evaluates other functions with specified arguments.  But I have a math background and this function was typically written `ev` likely for brevity on the chalkboard.

In the context of JS, using `_.eval` might cause confusion with the actual built-in `eval` function...which would be more appropriately named as `reify`.  And for me `_.evaluate` is too long even for typing =) but I wouldn't argue against using this longer name for clarity.
