### ISSUE TITLE
Simple composition

### ISSUE THREAD

**Issue by gampleman** [lodash/lodash#2317]
```javascript
let myFn = _()
  .map(a => a * 2)
  .sortBy(_.identity)
  .uniq()

myFn([7,3,4,4,6]) // => [6, 8, 12, 14]
```

This would be that if you call the lodash chaining with no arguments, you get into an implicit composition mode.

**Comment by Florian-R** [comment]
You mean something like #730 maybe?

**Comment by jdalton** [comment]
Thanks @gampleman!

We use chaining internally when composing functions with `_.flow` and `_.flowRight` to enable shortcut fusion. The secret sauce is using `_#plant` to set a new seed value.

```js
let mySeq = _()
  .map(a => a * 2)
  .sortBy(_.identity)
  .uniq()

mySeq.plant(array).value();
```

Returning a function though is a neat idea for v5.
We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
