### ISSUE TITLE
Question to bower support

### ISSUE THREAD

**Issue by RopoMen** [lodash/lodash#2320]
Hi,

I know that you dropped Bower support for LoDash, but I noticed that you still could install bower through bower.json, how this is possible? I also could not find LoDash through [Bower Search](http://bower.io/search/?q=lodash)
```json
{
   "lodash": "4.12.0"
}
```
I also followed 'pad-left' issue with npm and came a cross with this [jQuery blog post](https://blog.jquery.com/2016/03/24/community-notice-on-npm-dependencies-in-your-projects/)

Have you thought about could someone 'hijack' lodash in Bower and start distributing their own version of the library? Because LoDash is very famous library and has vast number of users that would affect on many projects, without them knowing it.

Or is LoDash still in your hands in bower registry?

Br,
Markku Roponen

**Comment by jdalton** [comment]
Bower is based on github repos@tags which why it still works with lodash.
I didn't have to do much of anything.
