### ISSUE TITLE
Add _.isPromise

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#2321]
`Promise` is now prevalent (supported in Node.js since v4 and in most of the modern browsers http://caniuse.com/#search=Promise).

`_.isPromise` is a simple function that confirms [Promise contract](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise).

**Comment by jdalton** [comment]
Dup of #1935 and #739

**Comment by gajus** [comment]
Sorry. Failed to search properly.

**Comment by gajus** [comment]
Couldn't sleep thinking how did I manage to overlook the existing issues.

Interestingly, [searching for "isPromise" brings no other results](https://github.com/lodash/lodash/issues?utf8=%E2%9C%93&q=is%3Aissue+isPromise+is%3Aclosed+).

**Comment by StreetStrider** [comment]
You need to [keep it simple](https://github.com/lodash/lodash/issues?utf8=%E2%9C%93&q=isPromise) :)

**Comment by gajus** [comment]
Oh, that was a pull request.
