### ISSUE TITLE
_.transform documentation

### ISSUE THREAD

**Issue by PhiLhoSoft** [lodash/lodash#2323]
I am (re)discovering `_.transform` and I am a bit disturbed by some points.
I expose them here, hoping it can help you improving the documentation... :smile: 

First though: how it differs from `_.reduce`?
Yes, one can see that by carefully reading each description and looking at the examples (they were a bit more explicit in 3.10 doc, BTW). But perhaps a little note might help.

Secondly, why is this listed under the **Object** category?
It takes as input either an array or an object, just like `_.reduce`, and can output the same types, so the category is a bit arbitrary there... :wink: 

Thirdly, the `accumulator` object is optional, but you don't specify its default value (while it is explained in `_.reduce`). The 3.10 examples make it clear (it is an empty object of same type (Array or Object) than input), so we loose this information in the 4.x docs.

This function is interesting as it is simpler than `_.reduce` (sensible default accumulator value, no need to return the accumulator, can stop early) so a more thorough doc might help its adoption... :smile:

**Comment by jdalton** [comment]
> First though: how it differs from `_.reduce`?

Transform will create an accumulator for you based on the object provided.
It'll be an instance of the object's constructor. Transform also allows you to exit early by returning `false`.

> Secondly, why is this listed under the Object category?

It's meant for objects. An array is an object too.

**Comment by PhiLhoSoft** [comment]
Well, this issue wasn't really to ask a "question", as I figured out the answers myself, it was about suggesting changes to the documentation...
The sentence you wrote to answer the (rhetorical here) "question" might be interesting to put in the doc., perhaps.

> It's meant for objects. An array is an object too.

Yes, but it is also true for most functions of the **Collection** category, too.
OK, I see the main difference, collection functions are told to work on strings, too, not `_.transform`. Well, `_.transform` also works with strings, but its default accumulator is no longer of the same type (of course!).

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash/commit/52ae769bfa235570fbdc718285b431ec4b0292a8.
