### ISSUE TITLE
`npm i lodash.pad` fails

### ISSUE THREAD

**Issue by jcurtis** [lodash/lodash#2326]
Looks like it's pointing to a bad version of lodash._basetostring

```
❯ npm i lodash.pad
npm WARN package.json cvent-pt-json-schemas@0.6.1-pre.1 No license field.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/jcurtis/.nvm/versions/node/v4.2.6/bin/node" "/Users/jcurtis/.nvm/versions/node/v4.2.6/bin/npm" "i" "lodash.pad"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: lodash._basetostring@'>=4.12.0 <4.13.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["3.0.0","3.0.1"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'lodash.pad'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jcurtis/dev/json-schemas/npm-debug.log
```

**Comment by jcurtis** [comment]
Never mind - it's failing due to an internal npm registry issue. Nothing to see here.

**Comment by donahchoo** [comment]
@jdalton I'm still getting this after removing my node_modules directory and running `npm install` again.  There are at least 4 reports of this problem this morning...  not sure its an individual's issue.

**Comment by jdalton** [comment]
I ran into the issue initially too.
Then I deleted the `node_modules` folder and `npm i lodash.pad` and it worked.

**Comment by jdalton** [comment]
You can confirm the package exists with `npm info lodash._basetostring` or [npmjs.com/package/lodash._basetostring](https://www.npmjs.com/package/lodash._basetostring)

**Comment by donahchoo** [comment]
`npm info lodash._basetostring`
 

> { name: 'lodash._basetostring',
>   description: 'The modern build of lodash’s internal `baseToString` as a module.',
>   'dist-tags': { latest: '3.0.1' },
>   versions: [ '3.0.0', '3.0.1' ],
>

**Comment by jdalton** [comment]
Here's what I get:
```bash
npm info lodash._basetostring

{ name: 'lodash._basetostring',
  description: 'The internal lodash function `baseToString` exported as a module.',
  'dist-tags': { latest: '4.12.0' },
  versions: [ '3.0.0', '3.0.1', '4.12.0' ],
```

**Comment by jdalton** [comment]
Possible registry hiccup @othiym23.

**Comment by vbotnaru** [comment]
have same old version as donahchoo

{ name: 'lodash._basetostring',
  description: 'The modern build of lodash's internal `baseToString` as a module
.',
  'dist-tags': { latest: '3.0.1' },
  versions: [ '3.0.0', '3.0.1' ],

**Comment by BadAsstronaut** [comment]
I'm seeing the same results as vbotnaru and donahchoo.

**Comment by vbotnaru** [comment]
found at least two packages which fails cause of this:
gulp-sass
eslint-plugin-import

**Comment by jdalton** [comment]
Cool. I think it's pretty clear it's an npm registry issue. Please direct feedback to the npm issue as there's nothing I can do from my end.

**Comment by rrazony** [comment]
Commenting out `always-auth = true` in .npmrc did the trick for me.

**Comment by leslc** [comment]
Has anyone contacted NPM yet?  (If not, I can, though not sure what the avenues are)

**Comment by jdalton** [comment]
The npm issue is linked just above.

**Comment by georgesnelling** [comment]
Just a bit of info for the detectives: On my dev mac (node version 4.2.2) this issue does not repro.  On my SmartOs box hosted at Joyent (node version 4.1.2) it does repro.  I had to downgrade all the way to:

    "lodash": "<4",

on the SmartOs box. After that lodash installed properly.
