### ISSUE TITLE
function chaining does not mutate array as expected

### ISSUE THREAD

**Issue by jusopi** [lodash/lodash#2328]
If I do this manually I get the expected results:

    var a = [
          { id:1, name:'foo' },
          { id:2, name:'bar' },
          { id:3, name:'bingo' },
          { id:4, name:'fingo' }
     ]

    var idx = _.findIndex( a, { id:2 })
    _.pullAt( a, idx ) //mutates the array per API docs
    console.log( _.map( a, 'id' )) // [1, 3, 4]

However if I chain this together, I get the original array:

    _.chain( a ).findIndex({ id:2 }).pullAt()
    console.log( _.map( a, 'id' )) // [1, 2, 3, 4]

And the same for find/pull:
   
    _.chain( a ).find({ id:2 }).pull()

Should not these function chains also mutate the original array?

**Comment by jfmengels** [comment]
The function chains mutate the original array, but you're not using it as expected.
When chained, the `pullAt(idx)` method removes the element at position `idx` of the value in the chain at that step. After you used `findIndex({id:2})`, the value in the chain is `1`, not `a` as you expected. Thus `pullAt` is implicitly called with `pullAt(1)` and not `pullAt(a, 1)` as you expected. Here you're actually attempting to pull a value from `1`, which fails kind of silently.

I don't think this is really chainable all the way, so I recommend using it the way you showed it in your first example, or like the following if you need to chain other things

```js
var idx = _.findIndex( a, { id:2 });
_.chain( a )
  .foo() // some other operations...
  .pullAt(idx)
  .value()
```

**Comment by jusopi** [comment]
Ok, I see the error of my thinking.  Thank you for the speedy response.
