### ISSUE TITLE
Add `_.findIndexFrom` and `_.findLastIndexFrom` in Lodash/fp

### ISSUE THREAD

**Issue by jfmengels** [lodash/lodash#2329]
The `fromIndex` param has been (re-)added to `_.findIndex` and `_.findLastIndex` in master, but the functionality is not available in `lodash/fp`.

I'm proposing `_.findIndexFrom(predicate, fromIndex, array)` for the param order.

Willing to try my hand at adding it :)

**Comment by jdalton** [comment]
Sure thing! PRs away!

**Comment by jdalton** [comment]
Moved to #2332.
