### ISSUE TITLE
Add `_.insert(array, item, afterIndex)` in lodash

### ISSUE THREAD

**Issue by sagiavinash** [lodash/lodash#2330]
currently to add an element to an array without mutating - 
```
let array = [
  ...array.slice(0, afterIndex),
  newItem,
  ...array.slice(afterIndex + 1),
]
```
its very verbose. can I create a PR with this method.

**Comment by jdalton** [comment]
Dup of #89.

**Comment by daedalus28** [comment]
FYI, this is available in futil-js as `insertAtIndex`

https://smartprocure.github.io/futil-js/#api-array-insertatindex
https://github.com/smartprocure/futil-js#insertatindex
