### ISSUE TITLE
No compatible version found: lodash._baseiteratee

### ISSUE THREAD

**Issue by praetorian122002** [lodash/lodash#2334]
There seems to be an issue with lodash?
npm ERR! notarget No compatible version found: lodash._baseiteratee@'>=4.7.0 <4.8.0'
[ERROR] npm ERR! notarget Valid install targets:
[ERROR] npm ERR! notarget ["4.4.0","4.5.0","4.5.1","4.5.2","4.6.0","4.6.1"]
[ERROR] npm ERR! notarget 
[ERROR] npm ERR! notarget This is most likely not a problem with npm itself.
[ERROR] npm ERR! notarget In most cases you or one of your dependencies are requesting
[ERROR] npm ERR! notarget a package version that doesn't exist.
[ERROR] npm ERR! notarget 
[ERROR] npm ERR! notarget It was specified as a dependency of 'lodash.map'

**Comment by demoneaux** [comment]
Hi @praetorian122002!

This issue is a duplicate of #2326. The issue isn't lodash's fault, but rather on the npm registry.

**Comment by praetorian122002** [comment]
Hi, thank you for the fast reply.

**Comment by jdalton** [comment]
@praetorian122002 It'd be ran if you could help npm debug the issue over at https://github.com/npm/registry/issues/18.
