### ISSUE TITLE
convert's `cap` should be an integer instead of a boolean

### ISSUE THREAD

**Issue by olsonpm** [lodash/lodash#2335]
Currently with cap being a boolean, `mapValuesWithKey` can be converted via the following

```js
const mapValuesWithKey = fp.ary(2, fp.mapValues.convert({ cap: false }));
```

This could be more concise by making cap an integer:

```js
const mapValuesWithKey = fp.mapValues.convert({ cap: 2 });
```

One non-trivial issue this presents is tackling methods with rearg'd iteratees - currently just `mapKeys`.  This seems like a code-smell, but I'm not nearly familiar enough to determine whether more rearg'd iteratees will be added in the future.  Point being - if it's just the one, then hacking a solution and documenting it seems like a reasonable solution.  If more will be added in the future, then I'd have to think about it more.

Finally: I think passing 0 should signal uncapped.

**Comment by jdalton** [comment]
Thanks @olsonpm!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
