### ISSUE TITLE
Bug in the "reduce" method when object has the "length" property

### ISSUE THREAD

**Issue by jagi** [lodash/lodash#2338]
Hi, I think there is a bug in the `reduce` method when dealing with objects that have the `length` property. In such situations object is treated as an array. I don't know if it's expected but the `reduce` method is supposed to work with both arrays and object. Let's try this example.
```js
_.reduce({
  a: 1, length: 4
}, function(result, value, key) {
  console.log(result, value, key);
  result[key] = value;
  return result;
}, {});
```

**Comment by jdalton** [comment]
The `_.reduce` method is a "Collection" method and as such prioritizes array-like values over objects.
You might give the "Object" method `_.transform` a try instead.

**Comment by jagi** [comment]
Ok thanks!
