### ISSUE TITLE
Suggestion: _.intersperse

### ISSUE THREAD

**Issue by AaronHarris** [lodash/lodash#2339]
A feature request wherein a single entity may be inserted between each element in an Array.

    _.intersperse([1, 2, 3], "&") //=> [1, "&", 2, "&", 3]

I think this is something that could be useful (it's there in [Haskell](http://zvon.org/other/haskell/Outputlist/intersperse_f.html)!) and using existing functions results in a lot of extra computation (eg. `map`, `flatten`, and `slice`). However it may be too simple of a function / doesn't do enough for lodash. Not sure how popular this would be, so curious to see what people think.

Also, if I'm willing to submit a PR for this, should I go ahead and do it or wait for votes?

**Comment by jdalton** [comment]
Thanks @AaronHarris!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by jtheisen** [comment]
I for one would have expected this to be in lodash. You need this in list pretty printing, for example, when the built-in `Array.join` isn't enough.

**Comment by kromit** [comment]
how many :+1:  are needed to be considered as worthy?

**Comment by jtheisen** [comment]
After implementing something like that for a special use case, I figured that the proposed signature may not be quite enough. I suggest the following (additional) more complex usage:

```
_.intersperse([1, 2, 3], (x, y) => x + y) //=> [1, 3, 2, 5, 3]
```

There are two things that are sometimes needed here:

- The interspersed object may need to have distinct object identities (think HTML DOM elements) and thus be created individually and
- sometimes the interspersed object need to depend on the surrounding elements. I needed this in a case where I interspersed a `<span>,<span>` in a React JSX expression and React was telling me I should put unique keys on the interspersed elements.

Obviously the simple usage should also work.

**Comment by jtheisen** [comment]
I would propose an additional, more sophisticated usage as well:

```
_.intersperse([1, 2, 3], (l, r) => l + r) // => [1, 3, 2, 5, 3]
```

I would suggest this because of some experience I just made with implementing an intersperse for a specific use case:

* The interspersed elements sometimes need to be newly created copies rather than the references to a single instance - think DOM elements.
* Sometimes the interspersed elements depend on the neighbors. In my case, I needed to have a `key` property defined on React elements for React to be happy. It was natural to have the key be derived from one of the neighboring elements.

There's another usage suggestion that may also be useful for the common case of formatting elements as "one, two *and* three":

```
_.intersperse([1, 2, 3], (l, r, isLast) => isLast ? 'and' : ',') // => [1, ',', 2, 'and', 3]
```

**Comment by jtheisen** [comment]
Ok, it appears that there already is (the original form of) intersperse in Lodash under the name [join](https://lodash.com/docs/4.17.2#join).

**Comment by jtheisen** [comment]
I have [an implementation for an intersperse supporting both usages](https://gist.github.com/jtheisen/f680afab642454fc0747b21ec3b11e02) for those looking for one.

**Comment by jtheisen** [comment]
@jdalton If I do a pull-request for this with proper tests and documentation changes, is this something you think should come in?

**Comment by jdalton** [comment]
>  is this something you think should come in?

@jtheisen Not at the moment.

**Comment by AaronHarris** [comment]
I think _.intersperse could be seen the intermediate step in _.join. I could also see a more powerful version of this, probably better called "interpolate", where you can pass a function (a, b) => {} that returns the value that goes in between two given values, or simply a static value. I like the more powerful/flexible option, but up to @jdalton how complex he'd want the code to be. I think either way it would still be under 10 lines.

**Comment by maxmx** [comment]
This is super useful to coma separate jsx object.

**Comment by gajus** [comment]
@jdalton This has over 50 👍 . How many 👍 does it need to be considered?

**Comment by jdalton** [comment]
There is no set limit, the votes help prioritize features when we feel it's time to add.

**Comment by gravitypersists** [comment]
`(arr, inter) => flatten(arr.map((a, i) => i ? [inter, a] : [a] ))`

**Comment by neopunisher** [comment]
add it!

**Comment by neopunisher** [comment]
```
if (!Array.prototype.intersperse) {
  Object.defineProperty(Array.prototype, 'intersperse', {
    value: function(something /*, initialValue*/) {
      if (this === null) {
        throw new TypeError( 'Array.prototype.intersperse ' + 
          'called on null or undefined' );
      }
      var isFunc = (typeof something == 'function')
      
      return this.concat.apply([], 
        this.map(function(e,i) { 
          return i ? [isFunc ? something(this[i-1]) : something, e] : [e] }.bind(this)))
    }
  });
}
```

**Comment by neoziro** [comment]
https://yarnpkg.com/en/package/intersperse 1.9K downloads

**Comment by ProfNandaa** [comment]
Is this going to be re-opened? :)

**Comment by FranzSkuffka** [comment]
Bumpity

**Comment by RedTn** [comment]
@OliverJAsh 
Thanks! I've modified the helper as well so you don't need to pass in a function with index

```
const intersperse = (delimiter, arr) =>
    arr.reduce(
        (acc, currentElement, currentIndex) => {
            const isLast = currentIndex === arr.length - 1;

            const newDelimiter = React.isValidElement(delimiter) ?
                React.createElement(React.Fragment, { key: currentIndex }, delimiter) :
                delimiter;

            return [
                ...acc,
                currentElement,
                ...(isLast ? [] : [newDelimiter]),
            ];
        },
        [],
    );
```

Usage: `intersperse(<SingleStat>|</SingleStat>, [<div>1</div>, <div>2</div>])`

**Comment by OliverJAsh** [comment]
@RedTn You need to pass a unique `key` to each separator, which is why I passed the index.

**Comment by slorber** [comment]
For TS users here are 2 useful implementations, based on examples above.

I prefer to use a separator as a function because sometimes we want a different separator according to the index

```ts
export const intersperse = <T>(arr: T[], separator: (n: number) => T): T[] =>
  arr.reduce<T[]>((acc, currentElement, currentIndex) => {
    const isLast = currentIndex === arr.length - 1;
    return [
      ...acc,
      currentElement,
      ...(isLast ? [] : [separator(currentIndex)]),
    ];
  }, []);
```

```ts
export const intersperse = <T>(arr: T[], separator: (n: number) => T): T[] => 
  arr.flatMap(arr, (a, i) => i > 0 ? [separator(i - 1), a] : [a]))
```

Here's how it can be used in React:

![image](https://user-images.githubusercontent.com/749374/74416621-b2575800-4e45-11ea-8cb5-f9f20be3976d.png)
