### ISSUE TITLE
Shallow object comparison

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [lodash/lodash#2340]
So, this is precisely the sort of iteration-related, actually-relatively-simple task that I usually rely on Lodash to implement for me; so, in that vein, would the following function, or an approximation thereof, be welcome?

    function isShallowEqual(v, o) {
        for(var key in v) {
            if(!(key in o) || v[key] !== o[key])
                return false

        for(var key in o)
            if(!(key in v) || v[key] !== o[key])
                return false

        return true }

**Comment by jdalton** [comment]
Thanks @ELLIOTTCABLE!

This is something you could compose with [_.isEqualWith](https://lodash.com/docs#isEqualWith) but I can see the benefits of having it as its own method.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by ELLIOTTCABLE** [comment]
Perfect. <3 @jdalton

~Ｔｈｅ ｗｏｒｋ ｙｏｕ ｄｏ ｉｓ ａｐｐｒｅｃｉａｔｅｄ！(✿ヘᴥヘ) ~

**Comment by DrYSG** [comment]
right now I am adding npm shallow-equal in addition to lodash. But I think this this will be very popular for redux programmers such as myself

**Comment by sassanh** [comment]
@jdalton how many votes is enough to consider a feature request popular?

**Comment by jjant** [comment]
@jdalton Any updates on this?

**Comment by jdalton** [comment]
@jjant 
> Any updates on this?

Nope, though I'm [supporting a PR](https://github.com/nodejs/node/pull/16084) to expose equivalence methods in Node.

**Comment by jjant** [comment]
I can throw in a PR to add this if you'd like.

**Comment by monodop** [comment]
I'd like to actually point out a typo in the original code snippet, just in case anyone copies and pastes this into their code-base without looking... like me...

The first for loop has an extraneous left curly brace that groups both for loops together and breaks the logic. Make sure to remove that. To be fair, the original code won't run as-is, but still.

```function isShallowEqual(v, o) {
    for(var key in v)
        if(!(key in o) || v[key] !== o[key])
            return false;

    for(var key in o)
        if(!(key in v) || v[key] !== o[key])
            return false;

    return true }```

**Comment by prmichaelsen** [comment]
@monodop hey nice find 😉

**Comment by ELLIOTTCABLE** [comment]
@monodop nice catch — I didn’t copy the code out of a production codebase, iirc, i just typed it out as an example on-the-fly when writing the Issue 🤣

Fixed!

**Comment by arelra** [comment]
For reference this is Facebook's implementation of a shallowEqual:

https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/core/shallowEqual.js

Has quirks handling and minor performance optimisations compared to the above example.

**Comment by wdanilo** [comment]
It's really surprising its not available in lodash. @jdalton any particular reason it was not accepted?

**Comment by jdalton** [comment]
Hi @wdanilo!

Moving forwards I think folks should push more on Node to expand its `util.isDeepStrictEqual` to the non-deep form.

**Comment by allpro** [comment]
It has annoyed me for years that Lodash lacks such a _basic_ comparison as `isShallowEqual`. This is needed _more often_ than deep-equal comparisons so is something a 'data library' should include. 

Gauging popularity is simple. Just look at the _millions_ of users of the numerous shallow-equal npm packages. Many of these projects _also_ use Lodash, but must import an extra package to fill this 'hole' in an otherwise amazingly complete library. Personally, I usually add my own shallowEqual helper rather than import a package, but I'd rather not need to!

**Comment by gasolin** [comment]
FYI there's a polupar lib (2686k / week) that provide the same syntax as `isEqualWith` but for shallow equal https://github.com/dashed/shallowequal

**Comment by ganqqwerty** [comment]
So, what's the progress or the justification of not doing this feature?

**Comment by wodenx** [comment]
const isShallowEqual = isEqualWith(a, b, (aval, bval, index) => (index === undefined ? undefined : Object.is(aval, bval)));

**Comment by slavafomin** [comment]
This is really awkward that lodash doesn't have this in 2023, eight years since the original proposal. Could someone share a good alternative at least? :)

**Comment by slavafomin** [comment]
This is really awkward that lodash doesn't have this in 2023, eight years since the original proposal.

A quick analysis shows that shallow comparison libraries on npm has around 15 millions downloads each week. I don't know if this is a bad popularity indicator.

**Comment by Fabioni** [comment]
please implement this finnally 🙈
