### ISSUE TITLE
Suggestion: info if a method has chaining, shortcut fusion, etc

### ISSUE THREAD

**Issue by jonyeezs** [lodash/lodash#2341]
It'll be nice to see at first glance on a method whether it can be chained or has shortcut fusion, or able to use it some sort of sequencing;

Rather than scrolling all the way to "seq" methods and looking at the list.

edit with example:
For instance...

**_.find(collection, [predicate=_.identity])**

**shortcut fusion** yes

**chainable wrapper** not by default

**Comment by jdalton** [comment]
Thanks @jonyeezs!

We'll keep these in mind.
