### ISSUE TITLE
_.throttle does not throttle when system clock is at 0

### ISSUE THREAD

**Issue by nhardy** [lodash/lodash#2342]
I've come across an issue when unit testing with `_.throttle` when using `_.runInContext(global).throttle` in unit tests. I'm using sinon's `useFakeTimers()` which, by default, sets the clock to `0`.
This appears to break `_.debounce()`'s `shouldInvoke()` when lastCallTime is `0` as `0` is `false`-y.

Offending line: https://github.com/lodash/lodash/blob/e156459176c1f35964fc443b39f04c4cb0a96763/lodash.js#L9648

**Comment by jdalton** [comment]
I'm open to a PR but otherwise will not be addressing this issue.

**Comment by jdalton** [comment]
On second thought, it was easy enough to address https://github.com/lodash/lodash/commit/e124e7fb5fb15a8eca8f12d57fc3393f979cf0ae.
