### ISSUE TITLE
`batched` option for `_.throttle`

### ISSUE THREAD

**Issue by pillowfication** [lodash/lodash#2343]
and `_.debounce`.

Currently a throttled function will be invoked with the last arguments provided. I'm looking for a way to batch all the arguments provided (while the function is being throttled), and then invoking the function with those batched arguments. Normally the arguments are objects and `_.assign` is used to batch them.

Example:
```javascript
var func = _.throttle(
  function update(values) { ... },
  100,
  {batched: true}
);

func({a: 'foo', b: 'hello'});
func({a: 'bar'});
func({c: 'world'});

// `update` is invoked with ({a: 'bar', b: 'hello', c: 'world'})
```

**Comment by jdalton** [comment]
Hi @pillowfication!

This looks a bit too specialized for core. You might be able to manage this by wrapping your debounced function.
