### ISSUE TITLE
fp version minified

### ISSUE THREAD

**Issue by darrrk** [lodash/lodash#2345]
Uncomfortably for development

**Comment by darrrk** [comment]
Here means, that `require('lodash/fp')`give minified versions of js code.
I think, `require('lodash/fp.min')` more proper for this, but `require('lodash/fp')` should give normal code.
All identical `require('lodash')` and `require('lodash.min')`

**Comment by jdalton** [comment]
Thanks @darrrk!

This is by design at the moment. I'll keep an eye on mentions though.
