### ISSUE TITLE
fp.mapValues iteratee function receive only value as parameter

### ISSUE THREAD

**Issue by darrrk** [lodash/lodash#2346]
Maybe some other have similar behaviour

**Comment by demoneaux** [comment]
This is intentional as all fp methods are [capped by default](https://github.com/lodash/lodash/wiki/FP-Guide#capped-iteratee-arguments). You can change this via `method.convert`.

**Comment by Restuta** [comment]
@bnjmnt4n do you know _why_ this is intentional and what are the gotchas mentioned in the docs?
