### ISSUE TITLE
Feature Request: _.pushAll

### ISSUE THREAD

**Issue by danthegoodman** [lodash/lodash#2347]
Lodash has `pullAll`, which removes items from the source array, but it doesn't have anything that will add items to the source array. So I propose a `pushAll` function which does this.

Example:

    var items = [1,2,3];
    var items2 = [4,5,6];
    _.pushAll(items, items2);
    console.log(items) //[1,2,3,4,5,6]

This would be similar to calling `Array.prototype.push.apply`, but can have the added benefits:

* tolerates null or undefined inputs
* handle more items than `Array.prototype.push.apply` can

**Comment by jdalton** [comment]
Thanks @danthegoodman!

We actually [use a helper function like](https://github.com/lodash/lodash/blob/4.12.0-npm/_arrayPush.js) this internally.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by c-dante** [comment]
Alternatively, if you're using babel or look forward to the future, you can just use the ES2015 spread operator

```
var items = [1,2,3];
var items2 = [4,5,6];
items.push(...items2);
console.log(items) //[1,2,3,4,5,6]
```
