### ISSUE TITLE
Chaining Filter

### ISSUE THREAD

**Issue by eyphka** [lodash/lodash#2348]
It looks like filter always returns an array, even if the input is an object. This results in unexpected behavior when chaining filter e.g.
```
var foo = {
  bar: 1,
  zee: 2,
  fee: 3
};

_(foo)
  .filter((value, key) => value % 2 === 1)
  .filter((value, key) => key === 'fee')
  .value();
// []
```

I would expect it to return { fee: 3}? In other words, current functionality means that it is impossible to filter on the key past the first filter.

**Comment by jdalton** [comment]
The `_.filter` method is a collection method which returns an array. If you're wanting to return an object try `_.pickBy`.
