### ISSUE TITLE
Feature request: lazy concatenation

### ISSUE THREAD

**Issue by tmct** [lodash/lodash#2349]
I want to be able to concatenate two (or more) lodash chains, such that the second one isn't iterated through unless it needs to be.

Sadly I can't find a way to do this with the current lodash... Is there a way?

If not, here's a suggested behaviour that I'd expect:
```javascript
var chain1 = _([1,2,3]);
var chain2 = _([4,5,6]);
var res = chain1.concat(chain2).take(5).value()
// I want this to return [1,2,3,4,5] without ever getting to 6;
// it currently returns [1,2,3,LodashWrapper]
```

This would have to be extended to dealing with multiple arguments in a manner consistent with `_.concat`.

p.s. The motivation is that in real-life my `chain1` and `chain2` have each come from a chain of filters.

p.p.s This request might be equivalent to requesting "Make `concat` support shortcut fusion"

**Comment by tmct** [comment]
Also, I'd be happy to have a go at implementing this if it's desired.

**Comment by jdalton** [comment]
Thanks @tmct!

The only place we support unwrapping values of chain sequences is in `_.isEqual` and other methods that rely on its shared internals. Support for shortcut fusion is done sparingly. So if you support that it's implementation size would be a factor. That said I think it would be neat to investigate this. If you'd like to kick something around that would be rad (maybe in just a branch of your fork).

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
