### ISSUE TITLE
fill produces unexpected behaviour when manipulating filled array afterwards

### ISSUE THREAD

**Issue by renewooller** [lodash/lodash#2351]
After using fill to create an array, then mapping or for looping over the contents of the array to update it using an index, the result is as though the value the index within each iteration is the same as the last index. 

When using a pure JS fill, it behaves as expected. 

I've written a test case comparing javascript fill with lodash fill.

```js
var _ = require('lodash');
var a = new Array(3).fill(undefined);

for(var i = 0; i< a.length; i++) {
    a[i] = {"a":i}
}

console.log(a);

for(var i = 0; i< a.length; i++) {
    a[i]['a'] = i+10
}

console.log(a)

a = a.map((v, i) => {v['b'] = i; return v})

console.log(a);

console.log("lodash fill");

var b = _.fill(Array(3), {"a":"b"})

console.log(b)

b = b.map((v,i) => {v['a'] = i; return v})

console.log(b);

for(var i=0; i<b.length; i++) {
    b[i]['a'] = i*2;
}

console.log(b);
```

**Comment by jdalton** [comment]
Hi @renewooller!

I'm sorry you're running into difficulties. Once you get the output from `_.fill` the rest is outside the scope of Lodash and Lodash has no part in further changes to the result. You might try hitting up [our chat](https://gitter.im/lodash/lodash).

**Comment by renewooller** [comment]
I'm not so sure about this explanation. The results indicate there is a definite difference between using lodash and pure JS. Did you try running it?

**Comment by jdalton** [comment]
Yep, but I don't have time to debug the logic after the method output. The method output looks correct and both `Array#fill` and `_.fill` produce the same result when given the same input object.

**Comment by renewooller** [comment]
Ok, cheers. I think this is still a valid issue despite not having time to debug, as it could easily affect more people. Do you know who implemented the lazy evaluation? I think that might have something to do with it - could be worth running it past them. I know theoretically it shouldn't apply as we're not using the chain method, but the evidence is there in the test script.

**Comment by jdalton** [comment]
I wrote the lazy evaluation. Lazy evaluation only kicks in for chain sequences.

To help get your issues addressed you should post a simple method invocation with the expected output and the actual output.

**Comment by jdalton** [comment]
Example:
```js
 _.fill(Array(3), {"a":"b"})
// actual => [{"a":"b"},{"a":"b"},{"a":"b"}]
// expected => [{"x":"y"},{"x":"y"},{"x":"y"}]
```

**Comment by renewooller** [comment]
Ok thanks for the clarification and thanks for your time. 

Here's a snippet showing more clearly the expected and actual. 

I'm a little skeptical that JS has the referential integrity that you're implying, ie, that there could not possibly be any side effects related to lodash after the fill method has been invoked. Lodash is still within scope after the array has been filled. Importantly, these results aren't evident when the array is created using pure JS, which indicates that it has something to do with how lodash is filling the array.  

Thanks again - I really don't mean to be annoying, I mean to be helpful. I already have a work around via pureJS, but I like lodash, so I'm trying to help you see that there is an issue here that could be worked on to improve the library. 

```console.log("lodash fill");

var b = _.fill(Array(3), {"a":"b"})

b = b.map((v,i) => {v['a'] = i; return v})

console.log(`expected output: [ { a: 0 }, { a: 1 }, { a: 2 } ]`)
console.log(`actual outuput ${JSON.stringify(b)}`);

for(var i=0; i<b.length; i++) {
    b[i]['a'] = i;
}

var c = _.fill(Array(3), {"a":"b"})

for(var i=0; i<c.length; i++) {
    c[i]['a'] = i;
}

console.log(`expected output: [ { a: 0 }, { a: 1 }, { a: 2 } ]`)
console.log(` actual output  ${JSON.stringify(c)}`);```

**Comment by renewooller** [comment]
actually maybe it is just because fill is a function

**Comment by renewooller** [comment]
I'll try replicate using my own function

**Comment by renewooller** [comment]
Ok - I've replicated it, FYI

```js
var _ = require('lodash');

function myFill (size, contents) {
    return new Array(size).fill(contents);
}

var z = myFill(3, {"a":"b"});

console.log("my fill before: ", z)

for(var i = 0; i< z.length; i++) {
    z[i]['a'] = i
}

console.log("my fill after: ", z);
```

**Comment by renewooller** [comment]
We've figured it out - it's because the object being passed to fill is passed by reference.
