### ISSUE TITLE
_.each(), _.reduce() work incorrectly on an object having a field named 'length'

### ISSUE THREAD

**Issue by raven29** [lodash/lodash#2352]
It seems that instead of `obj instanceof Array` it simply checks presence of a field 'length'.
If this field exists - it runs corresponding cycles obj.length times (at least if 'length' value is an integer).
Example:
```javascript
console.log(_.reduce({b:2, length:5}, function(res, v, k){res[k]=v; return res;}, {}));
```
It returns an ```Object```
```javascript
{0: undefined, 1: undefined, 2: undefined, 3: undefined, 4: undefined}
```
Tested on 3.10.1 and 4.12.0 versions.

**Comment by jfmengels** [comment]
Hi @raven29!

This is by design, see #1172 or #1705.
