### ISSUE TITLE
How to use _.round to round to a nearest multiple X

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#2353]
Expected behavior:

```js
> round(2.004, 0.005)
2.005
> round(2.001, 0.005) 
2
> round(22, 5)
20
> round(23, 5)
25
```

Current behavior:

```js
> _.round(2.004, -0.005)
2
> _.round(2.004, 0.005)
2
```

**Comment by jfmengels** [comment]
The `precision` argument is an integer, that rounds to `10^(-precision)`.
```js
_.round(2.0041, 2);
// => 2
_.round(2.0041, 3);
// => 2.004
_.round(2.0041, 3);
// => 2.0041
```
`_.round` is not built to work with your use case. You can try to find other similar libraries for this use case, or help `_.round` manually like the following:
```js
var n = 2.004;
_.round(_.round(n * 5, 3) / 5, 3) 
```

**Comment by gajus** [comment]
Thank you.

Would it not be a worthy addition to have `_.roundToMultiple`?

**Comment by jfmengels** [comment]
That could be useful :+1:

Would you mind creating a new issue with that as a proposal, with the examples above, a description of the use-case, etc?

**Comment by dmethvin** [comment]
A call like  `_.roundToMultiple(n, fraction)` will itself have the problem that the fraction cannot be exactly represented in a floating point number. This is a variation of the classic `0.1 + 0.2 !== 0/3` problem.

**Comment by jdalton** [comment]
Related to #2310.
