### ISSUE TITLE
_.round returns NaN when precision is greater than 100

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#2354]
```js
> _.round(10.0000001, 1000)
NaN
> _.round(10, 1000)
NaN
> _.round(10, 100)
10
```

**Comment by jdalton** [comment]
This is by design. You're getting into infinity numbers.
See https://mdn.io/round#Examples.

**Comment by jfmengels** [comment]
Couldn't we just return the passed number when the precision is too big?

**Comment by jdalton** [comment]
@gajus Would you be up for creating a PR to cap the limit to `307` with a unit test.
```js
precision = nativeMin(toInteger(precision), 307);
```

**Comment by gajus** [comment]
Will do in the next 24 hours.

**Comment by gibson042** [comment]
> Would you be up for creating a PR to cap the limit to `307` with a unit test.

That's an arbitrary cutoff, since the input to `Math` functions [depends on both `number` and `precision`](https://github.com/lodash/lodash/blob/56b397b506cb0121d6e3c20b55d13026f79c9474/lodash.js#L4916) (e.g., `_.round(0.0123456789, 310)` is perfectly valid, but `_.round(12345678910, 300)` will yield `NaN`). If you really want to prevent `NaN`, something _much_ more involved would be required.

**Comment by jdalton** [comment]
Not so arbitrary, I based it on [Number.MAX_VALUE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_VALUE) being E+308 so thought 307 would avoid issues with numbers like `_.round(1.8, 308)`.

**Comment by jdalton** [comment]
Large numbers and large precisions are a total edge case so I'm fine punting on one or the other.

**Comment by jdalton** [comment]
The max `precision` for `Number.MAX_SAFE_INTEGER` before hitting `NaN` is `292` so we can use that as the cut off.

**Comment by gajus** [comment]
> @gajus Would you be up for creating a PR to cap the limit to 307 with a unit test.
> 
>     precision = nativeMin(toInteger(precision), 307);

I am lacking familiarity with lodash code base. I am no longer working on this issue. Someone else please take over.

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash/commit/a044d8a24c1999bd3e45ba26aa26e699ad92be2b.
