### ISSUE TITLE
Set does not work properly for several empty paths in string mode

### ISSUE THREAD

**Issue by furstenheim** [lodash/lodash#2357]
Multiple path on string mode do not work

This works as expected
```
var mobject = {}
_.set(mobject, "", 1)
> {"" : 1}
```
This as well
```
var mobject = {}
_.set(mobject, ["", ""], 1)
> {"": {"" :1}}
```

However
```
var mobject = {}
_set(mobject, ".", 1)
> {}
```

**Comment by jfmengels** [comment]
The following does work though.
```js
var a = {}
 _.set(a, ["."], 1)
// => { '.': 1 }
```
The `.` when using "string mode" is used to do stuff like
```js
var a = {}
 _.set(a, 'b.c', 1)
// => { b: {c: 1} }
```
This is a pretty edgy case. Has this caused a bug for you, or did you just happen to notice it?

**Comment by furstenheim** [comment]
It was indeed a bug for me, I basically solved using the array format instead of the string format. In any case, both should behave alike, right?

**Comment by jfmengels** [comment]
Not necessarily.
```js
_.set({}, "a.b", 1)
// => { a: { b: 1 } }

_.set({}, ["a.b"], 1)
// => { 'a.b': 1 }
```

**Comment by furstenheim** [comment]
What I meant was
```
_.set({}, somePath, 1) 
```
would be the same as 
```
_.set({}, somePath.split('.'), 1)
```
Which is not the case with ```"."```

**Comment by jdalton** [comment]
That's assuming our path resolution code is `somePath.split('.')`
but it's not really as it supports `a[0].c` or `a["b"][c].d`. In string paths dots are delimiters and are melted away so since "." has no path in front or after the "." the path is seen as empty `[]`.

**Comment by jdalton** [comment]
On second thought, more than a few people have been thrown by this behavior.
I'll treat it as a bug fix. https://github.com/lodash/lodash/commit/91242440fc2c602b5e27228b22c6021b22216e2d
