### ISSUE TITLE
How to modify a subset of data without using variables

### ISSUE THREAD

**Issue by gaurav21r** [lodash/lodash#2358]
Since I'm more familiar with Underscore I'm going to elicit my question in `_ ` but the question is equally valid for Lodash!

If I have some (semi-accurate) data like this:

    var data = {
      people: [
        {name: 'Vishwanathan Anand', age: 46},
        {name: 'Garry Kasparov', age: 52},
        {name: 'Magnus Carlsen', age: 25},
      ],
      computers: [
        {name: 'Deep Blue', age: 26},
        {name: 'Deep Fritz', age: 21},
        {name: 'Deep Thought', age: 28},
      ]
    }

I wish to transform it to

    var data = {
      people: [
        {name: 'Vishwanathan Anand', age: 46, rank: 0},
        {name: 'Garry Kasparov', age: 52, rank: 1},
        {name: 'Magnus Carlsen', age: 25, rank 2},
      ],
      computers: [
        {name: 'Deep Blue', age: 26},
        {name: 'Deep Fritz', age: 21},
        {name: 'Deep Thought', age: 28},
      ]
    }

*Note how only the `people` substructure got `rank`*.

In Underscore, I know I can,

    _.extend({
      computers: _.map(data.people, (p, i) => {
        p.rank = i;
        return p;
      })}, {
        computers: data.computers
      })

But what if I need to do this without using any variables (no more access to `data`!) using underscore's `chain` (Lodash's Equivalent?) ?

Something like

    _.chain(data).subset('people').map((p, i) => {
      p.rank = i;
      return p;
    })

**NOTE** This is a real problem and not a matter of convenience. I am working on a project that involves creating a sort of environment for functional operators and ***variables*** are not allowed.

It seems Lodash and the like operate on the ***entire*** structure (Array / List). Is there any way I can ask it to operate on a substructure while preserving the rest?

**Comment by jfmengels** [comment]
Would this do the trick?
```js
_.update(
  data,
  'people',
  (people) => _.map(people, (value, index) => _.extend(value, {rank: index}))
);
// or
_.update(
  data,
  'people',
  _.partial(_.map, _, (value, index) => _.extend(value, {rank: index}))
);
```

By the way, if you can't use variables and are doing more like functional programming, might be worth checking out [lodash/fp](https://github.com/lodash/lodash/wiki/FP-Guide) (but by default it never mutates data).

I'm closing as this is not an issue. Feel free to hit the [Gitter](https://gitter.im/lodash/lodash) for questions like this :)

**Comment by gaurav21r** [comment]
@jfmengels @jdalton Sorry my Bad will use Gitter from now on! Thanks a lot of your reply @jfmengels  that works! And Underscore has no equivalent it seems! 

Can I just say it seems this is also called a ***lens*** in FP? I'm not sure, but if you agree maybe a note in its docs? It'll help normalize names that are disparate in FP implementations of JS?

**Comment by jfmengels** [comment]
I'm not accustomed to lenses, but if you think it might be an worth it, while staying simple and accessible (which I'm not sure it is, I will take a look at lenses) to beginners, feel free to make a PR :)

**Comment by StreetStrider** [comment]
@gaurav21r, hello. I wanted to investigate your issue earlier, but I haven't enough time. Anyway, it looks like you're in the right direction. Yes, it is a lenses. Ramda has good support for it. LoDash has support too, but its not mentioned anywhere and functions named differently. Take a look at LoDash fp's `at`, `get` & `set`. They are specific cases of lenses. You can leverage it to work with `map` & `mapValues` and thanks to currying it will look (and work) good.

**Comment by gaurav21r** [comment]
@StreetStrider @jfmengels @jdalton Thanks!

@jfmengels Whenever you have some time, do have a look at https://medium.com/@drboolean/lenses-with-immutable-js-9bda85674780 and http://ramdajs.com/0.21.0/docs/#lens
