### ISSUE TITLE
Allow _.ary from right

### ISSUE THREAD

**Issue by voyti** [lodash/lodash#2363]
This is my first post on this repo so hello all and great job. I was looking for a convenient way to use _.ary in a way that would ignore arguments from left rather than right. I think it's best to jump straight to an example to see what I mean. I'm using node fs functions that execute callbacks with two arguments, i.e.:

`fs.readFile('/etc/passwd', (err, data) => {
  // callback body
});`

Now, let's suppose I have a callback function ready, but it doesn't expect the *err* argument. If I could use, for example, _.aryRight, I'd go:

`fs.readFile('/etc/passwd', _.aryRight(customCallback, 1));`

Or, even better, if \_.ary accepted negative number to work from right, (e.g. like fromIndex in \_.indexOf/\_.includes or n in \_.nth):

`fs.readFile('/etc/passwd', _.ary(customCallback, -1));`

I know I could use _.filp or _.rearg for that, but still it's a bit hacky and the above I think would look cleaner.

**Comment by jdalton** [comment]
Hi @voyti!

I could see something like this.
```js
function foo(func, start, end) {
  var args = [func];
  args.push.apply(args, Array(start));
  return _.ary(_.partial.apply(_, args), end);
}
```
I don't think it's name should be associated with `ary` though.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
