### ISSUE TITLE
FP: Confusing order of arguments for pick/omit and without

### ISSUE THREAD

**Issue by andreasgruenh** [lodash/lodash#2365]
Hey everybody! Love lodash and just started using lodash/fp today and I'm struggling quite a bit with the mapping between normal and fp build.

I'm seeing this conflig atm.:

`_.pick(['key1', 'key2', 'key3'], obj)
_.without(array, ['1', '2', '3'])`

Why is without with data first and pick/omit not?

**Comment by jdalton** [comment]
The FP flavor of `_.without` is essentially `_.difference`. The `_.difference` method is the only set method where argument order is significant. For example  `_.difference([1,2,3],[2,3,4])` is `[1]` while  `_.difference([2,3,4],[1,2,3])`.

We aligned its ordering with similar methods of other FP libs.

**Comment by jdalton** [comment]
Thinking on this a bit more we could have `_.without` flipped arg order to give folks more options.

**Comment by andreasgruenh** [comment]
Wouldn't this mean that without is an alias in default but not an alias in lodash/fp or do you want to flip args in both versions?

**Comment by jdalton** [comment]
In FP is when `fp.without` was like `fp.difference`. This would just make the `fp.without` args flipped.
