### ISSUE TITLE
_.pick is not by reference

### ISSUE THREAD

**Issue by peterver** [lodash/lodash#2368]
When cherrypicking an array from an object, the array is cloned instead of passed by reference.

It would be a neat idea to have an option that can be passed to _.pick to define whether or not it should be cloned or passed by reference ( on non-primitive variables )

**Comment by jdalton** [comment]
Hi @peterver!

I think this is better suited thru a mixin or composition:
```js
var myPick = _.flow(_.pick, _.cloneDeep);
```

**Comment by c-dante** [comment]
I'm getting that it is passing by reference. In that case, @jdalton's works as a way to clone as well.

```js
var x = { a: [1, 2, 3], b: 'test' };
_.pick(x, 'a').a === x.a
// true
```
