### ISSUE TITLE
.js extension in import lines

### ISSUE THREAD

**Issue by dmvt** [lodash/lodash#2373]
https://github.com/lodash/lodash/commit/35cdf6513b2655e2accc83a191fdf6edf24ed33f

In the above commit all of the import lines were changed to include the file extension `.js`. This is causing  build issues for me since I have both es5 and es6 code compiled by brunch. In order to make that work, I have a script which rewrites the file extensions to differentiate between the file types (`.js` for es5 and `es6` for es6). The easy short term solution is to keep using 4.12. Longer term I can rewrite my script to rewrite the import lines as well, but thought I'd first check in with you to make sure that change was intentional and would be sticking around in future versions. Seemed kind of arbitrary...

Thanks in advance for the info

**Comment by jdalton** [comment]
This is by design.
ES6 module loading in places like the browser require the file extension which is why it was added.

**Comment by dmvt** [comment]
Good to know... thanks for addressing the question.
