### ISSUE TITLE
Allow subtract to work as sum does

### ISSUE THREAD

**Issue by grillorafael** [lodash/lodash#2374]
Currently, we have `_.sum` that works receiving an array of Numbers. It is useful to have a similar operation that operates subtracting elements.

It could operate on top of arguments list or array of input (So it does not change current behaviour).

Example:

```javascript
_.subtract(3, 2) // 1 --> (3 - 2)
_.subtract(3, 2, 1) // 0 --> (3 - 2 - 1)
_.subtract([3, 2, 1]) // 0 --> (3 - 2 - 1)
_.subtract(-1, -1, -3) // 3  --> (-1 - (-1) - (-3))
```

**Comment by grillorafael** [comment]
If approved, I can write the implementation and submit a PR.

**Comment by Mathius17** [comment]
The problem is that with substraction, the order of the items does affect the result. Although that would be pretty neat for `_.multiply( )`

**Comment by grillorafael** [comment]
Yes, it does. I don't think it is wrong to assume from left to right (as native javascript does).

And yes, this version for multiply seems interesting as well.

**Comment by fdegiuli** [comment]
`_.product`?

**Comment by jfmengels** [comment]
`_.subtract` is more like `_add` (which doesn't accept an array) than like `_.sum`.

As @Mathius17 said, the order is important, and it's kind of weird IMO to have one of the items be treated different than the others.

Do you have a use-case for this?

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by jdalton** [comment]
The `_.sum` method, which was added by popular demand, is just sugar around
`_.reduce(nums, operator, 0)`.

**Comment by StreetStrider** [comment]
`add` is commutative / symmetric, `subtract` isn't.
