### ISSUE TITLE
Add default value to _.find( )

### ISSUE THREAD

**Issue by Mathius17** [lodash/lodash#2375]
Hi! First of all, thanks for this amazing project. Now to the request, it would be really nice if we could return a default value if the `find` method doesn't find anything.

Simple use case:

Let's say we have to return the age of the first person with name 'Mateo'. Normally we would need to do it like this:

```javascript
let people = _([
  { name: 'Adam', age: 27 },
  { name: 'Jane', age: 24 },
  { name: 'David', age: 26 },
  { name: 'Jeffrey', age: 32 },
  { name: 'Evan', age: 26 },
]);

let person = people.find({ name: 'Mateo' });

if (person) {
  return person.age;
}

return 0;
```

But wouldn't it be nicer if could just simply do this:

```javascript
return people
         .find({ name: 'Mateo' }, 0, { name: ' ', age: 0 })
         .age;
```

This gets even more relevant when you start to use `Null Objects` with it's own methods. It saves the check to see if something was found.

If approved, I can write the implementation and submit a PR.

**Comment by Mathius17** [comment]
If approved, I can write the implementation and submit a PR.

**Comment by jfmengels** [comment]
Hi @Mathius17!

Used in that context, I think it's simpler to do
```js
let person = people.find({ name: 'Mateo' }) || {age: 0};
return person.age;
```

What do you think?

**Comment by Mathius17** [comment]
Yes, that's nice, but it's a simplified example. The cases I'm really interested in, is when the objects have a method that needs to be executed.

Example:

```javascript
let nullPerson = {
  name: '',
  age: 0,
  speak: () => console.log("I'm an imaginary person"),
};

// Prefer this
return people.find({ name: 'John' }, 0, nullPerson).speak();

// to this
let person = people.find({ name: 'John' });

if (person) return person.speak();
return console.log("I'm an imaginary person")

```

**Comment by jdalton** [comment]
I'd prefer to tackle this with a method that like `defaultTo` that could be used in method composition:
```js
fp.flow(fp.find(predicate), fp.defaultTo(defaultValue));
```
Where `defaultTo` would produce a function that returns `defaultValue` if its input is `undefined`.

**Comment by Mathius17** [comment]
I actually like your approach more. Is even more readable with chaining methods than my request.

**Comment by jdalton** [comment]
@Mathius17 If you want to try your hand at a PR for it that would rock.

**Comment by jfmengels** [comment]
Ha, was thinking of the same thing. Big :+1: here! :D

**Comment by Mathius17** [comment]
I'll try to implement it and submit a PR

**Comment by jdalton** [comment]
We currently have default values in other methods as hitting with `undefined`.

**Comment by Mathius17** [comment]
I'll do it with `undefined` then

**Comment by jfmengels** [comment]
Sure, that makes sense for methods like `get` where you're "likely" to get undefined because you're reading fields from an object, and not using the default value when you're reading 0, but if `defaultTo` is to be used with custom functions, where people rather return `null` (speculation? I do at least), this is not very useful.

```js
_.flow(
  fooThatReturnsANumberOrNull,
  _.defaultTo(100)
)
```

I don't mind having a method that defaults only with `undefined`, but then I'll open a request for another new one which defaults at least with `null`. Ramda seems to have one too (http://ramdajs.com/0.21.0/docs/#defaultTo) which defaults if `null`, `undefined` and `NaN` (so not all falsy values), which I'd be fine with too.

**Comment by jdalton** [comment]
Let's start simple with `undefined`.

**Comment by Mathius17** [comment]
Help! I implemented it, made some tests. It passes all `test.js` but not `test-fp.js`, it throws me this unpassed test:
```javascript
method arity checks: should wrap methods with an arity > `1` (1, 0, 1)
Expected: 	
[]
Result: 	
[
  "defaultTo"
]
Diff: 	
[
  "defaultTo"
]
Source: 	
    at Object.<anonymous> (file:///Users/Mathius/www/lodash/test/test-fp.js:337:14)

```
If I modify `dist/lodash.fp.js` and add `'defaultTo'` to the `aryMethod.2` array (line 615), all tests pass. What should I do to pass this test? I know I shouldn't be modifying `dist/lodash.fp.js`

**Comment by jfmengels** [comment]
@Mathius17 Try adding `defaultTo` in the list here (arity 1) https://github.com/lodash/lodash/blob/master/fp/_mapping.js#L56.

**Comment by Mathius17** [comment]
@jfmengels shouldn't it have an arity of 2? I mean, from what I understood of the FP Guide is that in this case, if the normal behaviour is `_.defaultTo(input, defaultValue)`, in FP the `input` should go last and the `defaultValue` first, thus letting me do things like `fp.defaultTo(0)(undefined)`.

And I tried putting it the array of arity 1 and arity 2 but only passed the tests inside in arity 2.

**Comment by jdalton** [comment]
The `_.defaultTo` method would have arity of 1, `defaultTo(defaultValue)`. It's a function that creates a function that accepts a single arg.

**Comment by jfmengels** [comment]
Hmm... in FP that sounds just like a curried function with arity 2 (and defaultValue as the first arg).

In vanilla, that is a bit trickier to do without currying, but having it have an arity of 1 will make it not available in a chaining construct (I think)
```js
// chaining
_(foo)
  .map(fn)
  .find(fn2)
  .defaultTo(defaultValue);
```

and weird to use outside of a flow construct (in vanilla Lodash)
```js
var value = _.defaultTo(100)(_.find(...));
// vs
var value = _.defaultTo(100, _.find(...));
```

Could it be a curried function with arity 2 in FP at least, or is that tricky to do?

**Comment by jfmengels** [comment]
The last request would be confusing, so forget it, but I think it would be better suited with an arity of 2.

Better chaining interface, better curry and still usable with vanilla Lodash. You'd lose the ability to use (easily, you can still use partial) it in a flow construct with vanilla Lodash, but I always thought any flow construct is just odd there, since you need to use partial so much.

**Comment by Mathius17** [comment]
Guys to be honest I don't even know where to start, I've been wrapping my head around it since yesterday, but there are too many things in `lodash` that I don't fully understand its implementation, chaining, lazy evaluation, FP, etc.

My main use case would be for chaining, as @jfmengels showed:
```javascript
// chaining
_(foo).map(fn).find(fn2).defaultTo(defaultValue);
```
But if `find` returns a `undefined` I don't even know how `defaultTo` would be invoked

**Comment by jdalton** [comment]
Y'all are right for the Lodash form it would be `defaultTo(value, defaultValue)` when it is wrapped for fp use it would be `defaultTo(defaultValue, vale)` and curried as `defaultTo(defaultValue)(value)`.

**Comment by jdalton** [comment]
Checkout [this commit](https://github.com/lodash/lodash/commit/b40b55538643b4f5bc85e96a6ba9e34c29f99cc9) as an example of adding a method. Also don't worry about adding all the unit tests and things if you're blocked. It's better to get the PR out than have it help up over this stuff.

**Comment by Mathius17** [comment]
Thanks @jdalton! I'll keep trying and submit the PR when ready
