### ISSUE TITLE
`_.union[By|With]` have very unexpected behavior in chains

### ISSUE THREAD

**Issue by fdegiuli** [lodash/lodash#2376]
All the `_.union` family of functions are chainable, but don't actually work when used in a chain. The problem is that  `union()` takes multiple array arguments instead of a collection of arrays, but the whole chained value is passed as the first argument without being split. So this happens:

```js
// Use u instead of _ in the repl
u([[1,2,3,5],[1,2,4,8]]).union().value();
// [ [ 1, 2, 3, 5 ], [ 1, 2, 4, 8 ] ]
u([[1,2,3,5],[1,2,4,8]]).unionBy(u.identity).value();
// [ [ 1, 2, 3, 5 ], [ 1, 2, 4, 8 ] ]
u([[1,2,3,5],[1,2,4,8]]).unionBy('a').value();
// [ [ 1, 2, 3, 5 ] ]  both == 'undefined'
```

This was referenced in https://github.com/lodash/lodash/issues/1105 and the solution was to just use `_.spread`, which only really works for plain `_.union` but more importantly defeats the point of `_.union` being chainable at all. 

Right now, the behavior of `union()` in a chain is the same as `uniq()`:

```js
u([1,2,2,3,23]).union().value();
// [ 1, 2, 3, 23 ]
```

It's doubtful that anyone is using it this way intentionally. 

I would either not make `_.union` and its buddies chainable at all, or automatically `spread()` when union is invoked on a chain.

Let me know what you think, I'll happily make a PR.

**Comment by jdalton** [comment]
Hi @fdegiuli!

Chaining works on a single seed value with queued sequence operations.
In the case of `union` that means common usage is:
```js
_(array1).union(array2, array3).value();
```

**Comment by fdegiuli** [comment]
Gotcha. Mind if I add this to the `_.union` docs?

**Comment by jdalton** [comment]
I think the `_.union` docs are sufficient.
