### ISSUE TITLE
Flow type specification for lodash

### ISSUE THREAD

**Issue by tryggvigy** [lodash/lodash#2377]
Would there be interest in accepting a PR implementing [flowtype](http://flowtype.org/) specifications for the whole API surface?

I'm writing out these type signatures for personal use but I'm sure they could benefit others.

Example: 
https://gist.github.com/tryggvigy/96029d1154eaa7bf4343e252c0dda308
The gist is an untested prototype so don't take the types too seriously.

**Comment by jdalton** [comment]
Hi @tryggvigy!

If there's a [DefinitelyTyped](https://github.com/DefinitelyTyped) equiv we'd defer to that. Maintaining definition files is a lot of work and not something we'd be able to do well since we don't use them in our day to day use.

**Comment by montogeek** [comment]
What about now?

**Comment by jdalton** [comment]
Hi @montogeek!

There's no change in stance.
