### ISSUE TITLE
lodash v4 _.cloneDeep significant performance decrease in node.js 0.10

### ISSUE THREAD

**Issue by koresar** [lodash/lodash#2378]
lodash@4 `_.cloneDeep` is about three times slower than lodash@3 on node.js 0.10.*.

```sh
┌vasyl@192-168-1-10 ~/tmp
└> node -v
v0.10.33
┌vasyl@192-168-1-10 ~/tmp
└> npm i lodash@3
lodash@3.10.1 node_modules/lodash
┌vasyl@192-168-1-10 ~/tmp                                                                                                              
└> node
> var l = require('lodash');
undefined
> var json = require('./3MB.json');
undefined
> console.log(new Date()); l.cloneDeep(json); console.log(new Date());
Tue May 24 2016 11:42:41 GMT+1000 (AEST)
Tue May 24 2016 11:42:47 GMT+1000 (AEST)
undefined
> ⏎                                                                                                                                    
┌vasyl@192-168-1-10 ~/tmp
└> npm i lodash@4
lodash@4.13.1 node_modules/lodash
┌vasyl@192-168-1-10 ~/tmp                                                                                                              
└> node
> var l = require('lodash');
undefined
> var json = require('./3MB.json');
undefined
> console.log(new Date()); l.cloneDeep(json); console.log(new Date());
Tue May 24 2016 11:43:20 GMT+1000 (AEST)
Tue May 24 2016 11:43:37 GMT+1000 (AEST)
undefined
```

**Comment by koresar** [comment]
Tested node.js v4 and v6. The `_.cloneDeep` works very fast. Instant cloning of that 3MB.json document.

v4.0 and onwards is also similarly slow as v4.13.1.

**Comment by tjdavey** [comment]
Some quick benchmarks with Benchmark.js from my local machine with a large Javascript object on lodash v4.13.1. 

Node 4.4.2
> cloneDeep x 4.07 ops/sec ±2.80% (15 runs sampled)

Node 0.10.35
> cloneDeep x 0.03 ops/sec ±8.87% (5 runs sampled)

**Comment by jdalton** [comment]
This is likely by design. More things are supported and objects will have their symbols cloned (which is slower). If you can pin point a specific thing to tweak I'm open to it. But as for Node 0.10, it's on the chopping block. We'll drop support for it in lodash v5.

**Comment by koresar** [comment]
I observed the lodash v4 `baseClone` function. I reverted the circular references check algorithm to the one which was in lodash v3. The performance got 3 times better with my 3MB file. In other words, the bottleneck is this new file: https://github.com/lodash/lodash/blob/npm/_Stack.js

P.S. Irrelevant. If I remove the algorithm altogether then instead of 20000 ms the `_.cloneDeep` takes about 130 ms on my large 3MB JSON object.

**Comment by jdalton** [comment]
The culprit is most likely [_stackSet](https://github.com/lodash/lodash/blob/npm/_stackSet.js).
Once it hits `LARGE_ARRAY_SIZE` it bumps values into a `MapCache` which has a fixed cost lookup in enviros with `Map`. Without `Map` though its the same as `ListCache` so bumping values in without a benefit.

**Comment by koresar** [comment]
Ah. Good to know. Thank you.

**Comment by jdalton** [comment]
@koresar Try this tweak manually https://github.com/lodash/lodash/commit/e18b577d20f9719f393971260856c1e4ed25e72d.

**Comment by koresar** [comment]
Did it like this (otherwise it crashes):
```js
var isMap = typeof Map !== 'undefined';

function stackSet(key, value) {
  var cache = this.__data__;
  if (isMap && cache instanceof ListCache && cache.__data__.length == LARGE_ARRAY_SIZE) {
    cache = this.__data__ = new MapCache(cache.__data__);
  }
  cache.set(key, value);
  return this;
}
```

Performance is exactly the same. No win.

**Comment by jdalton** [comment]
You're not shimming anything are you? You could use `var Map = require('./_Map')`.

**Comment by koresar** [comment]
I am not. Here is the full "source code":
```js
$ node -e "var l = require('lodash/cloneDeep'); var json = require('./3MB.json'); var t = Date.now(); l(json); console.log(Date.now() - t);"
23390
$ node -v
v0.10.33
```

**Comment by koresar** [comment]
I can borrow you the `3MB.json` file (if you promise to keep it secret).

**Comment by jdalton** [comment]
Naw, no worries. I'll keep kicking it around.

**Comment by jdalton** [comment]
@koresar
```js
    function stackSet(key, value) {
      var cache = this.__data__;
      if (cache instanceof ListCache) {
        var pairs = cache.__data__;
        if (!(Map && pairs.length == LARGE_ARRAY_SIZE)) {
          pairs.push([key, value]);
          return this;
        }
        cache = this.__data__ = new MapCache(pairs);
      }
      cache.set(key, value);
      return this;
    }
```

**Comment by koresar** [comment]
This version is about twice faster than the latest v4.13. 23390->11415 ms
```sh
$ node -v
v0.10.40
$ npm ls lodash
/Users/vasyl/tmp
└── lodash@4.13.1

$ node -e "var l = require('lodash'); var json = require('./3MB.json'); var t = Date.now(); l.cloneDeep(json); console.log(Date.now() - t);"
11415
```

Same time, it's still about 2 times slower than the lodash v3.10 5746 ms
```sh
$ node -v
v0.10.40
$ npm ls lodash
/Users/vasyl/tmp2
└── lodash@3.10.1

$ node -e "var l = require('lodash'); var json = require('./3MB.json'); var t = Date.now(); l.cloneDeep(json); console.log(Date.now() - t);"
5746
```

**Comment by jdalton** [comment]
I'll take it :)

**Comment by jdalton** [comment]
I'll keep digging but I think this comes down to using the best tool for the job. Since this is JSON, which has no circular references and can only contain simple data types you can simply read the file in as text and use `JSON.parse()` or take the text and create a factory function:
```js
var fs = require('fs');
var path = require('path');
var jsonText = fs.readFileSync(path.join(__dirname, '3MB.json'), 'utf8');
var factory = Function('return' + jsonText);

var t = Date.now();
factory();
console.log(Date.now() - t);
// => 66
```

**Comment by koresar** [comment]
> this comes down to using the best tool for the job

That's true. In fact `JSON.parse` is exactly the hotfix we did (yeah, this hit us on production servers yesterday).

This issue was created more like "JFYI", than an actual bug. But it is great to see the improved version which works twice faster than the current one! Great job! 👍

**Comment by jdalton** [comment]
A little more detail into why `cloneDeep` takes a hit. Most methods that use `stack` release the tracked objects after their recursive walk. For example:

```js
stack.set(array, other);
// < recursive array crawl >
stack['delete'](array);
```
This keeps the list of tracked values scoped to just those within `array`. If the same value exists in a sibling property then it will be re-evaluated.

However in a deep clone if an `o.a == o.b.c` then you'd want the clone to have the same result. This means that the tracked objects cannot be released. So in the case of the 3MB json object it's searching 10,000 objects (over and over) for each object it clones.

**Comment by jdalton** [comment]
This is why modern Node with `Map` get a perf win because maps have a fixed cost lookup unlike arrays which are linear.

**Comment by koresar** [comment]
I assume it's not possible to utilize plain JS object instead of array in here?

**Comment by jdalton** [comment]
There are ways without tracking with an array but they require bolting on non-enumerable properties to see if it's been visited (which I want to avoid). Gotta get off that older version of Node.

**Comment by jdalton** [comment]
I patched places to pop the stack where possible https://github.com/lodash/lodash/commit/dfb71a3a50869e4aa356c34b890f3ca04de13467.
Even in `baseClone` when not performing a full clone :)

**Comment by koresar** [comment]
You're a robot!
11415 -> 8677 msec !!!
```sh
$ node -e "var l = require('./lodash_test.js'); var json = require('./3MB.json'); var t = Date.now(); l.cloneDeep(json); console.log(Date.now() - t);"
8677
```
That's fast enough already. :)
