### ISSUE TITLE
Could not find module `lodash/at.js` imported from `lodash/collection`

### ISSUE THREAD

**Issue by fpauser** [lodash/lodash#2379]
Looks like something is broken in collection.js and collection.default.js.
`./at.js` gets imported to collection although it is a function of `lodash/object`, and therefore should be moved to `object.js` and `object.default.js`.

**Comment by jdalton** [comment]
The module is misclassified but still exists. You shouldn't be getting module not found errors (https://github.com/lodash/lodash-cli/commit/f553f0c8913d94f16bb8b92b85f10f49f071fe08).
