### ISSUE TITLE
Is function turned into an alias equal to function being deprecated?

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#2380]
I cannot find this in the documentation anywhere. Whats the significance of an alias? Does the fact that function A is an alias of function B mean that function A will eventually be deprecated?, e.g. the case of `_.each` being an alias of `_.forEach`.

**Comment by jdalton** [comment]
An alias isn't a sign of deprecation. In v4 we reduced the number of aliases in `lodash` primary to simplify the API. Aliases are just shorter or alternative names.
