### ISSUE TITLE
_.sum can introduce rounding errors

### ISSUE THREAD

**Issue by bbottema** [lodash/lodash#2382]
Recently I've encountered an issue where [adding fractional numbers results in rounding errors](http://stackoverflow.com/questions/588004/is-floating-point-math-broken). This can be solved by using a rounding implementation (lodash' _.round seems to be a proper implementation, but there's some controversy around rounding in javascript and people tend to resort to the manual [Firefox rounding implementation](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Math/round#Decimal_rounding)).

Case in point:

```javascript
var a = 14.38;
var b = 148.95;
var c = a + b;

console.log(c); // 163.32999999999998
console.log(_.round(c, 2)); // 163.33

// similar error with 0.1 + 0.2 and so on
```

Normally we can compensate for these rounding errors by rounding after the addition. _.sum doesn't support this: given enough numbers to summate the result _.sum gives forces us to reduce the decimals we must round to, in order to eliminate the rounding error.

I've prepare a jsFiddle with an example. https://jsfiddle.net/plantface/f0h2rj5a/

**Comment by jdalton** [comment]
This is outside the scope of Lodash. Lodash is simple sugar around the pattern of
`reduce(nums, (n1, n2) => n1 + n2, 0)`.
