### ISSUE TITLE
When using fp, what is the best way to get the key|index and collection?

### ISSUE THREAD

**Issue by jshthornton** [lodash/lodash#2387]
Given the follow case:
```
fp.map((value, key, collection) => {
  return 'x';
})({
  0: 'a',
  1: 'b',
  2: 'c',
  3: 'd'
}));
```
The arguments `key` and `collection` are undefined.

Is there a way to access these arguments like in `_.map`?

**Comment by jfmengels** [comment]
You could use vanilla Lodash in that case, or you could `convert` to disable the iteratee `cap` on the whole of Lodash/fp, or on only a single method, see https://github.com/lodash/lodash/wiki/FP-Guide#convert for more info.

I don't think there's an established best way yet, but I'd go for either importing `map` from vanilla Lodash (`const vanillaMap = require('lodash/map');`), which can be a bit confusing (so maybe give it a name that shows it's not a "normal" map), or convert only the `map` method. I'd discourage from converting the whole `fp` object.

**Comment by just-boris** [comment]
@jshthornton sorry, but I don't get your answer.

You mean that I have to create my own lodash build to achieve desired map behavior?

**Comment by jfmengels** [comment]
@just-boris You could either use the map method from vanilla (non-FP) Lodash like `const vanillaMap = require('lodash/map');`, or you could use the convert method
`const map = fp.map.convert({cap: false})` to remove the argument capping (it returns a new method, but does not mutate `fp` or `fp.map`).

**Comment by just-boris** [comment]
@jfmengels thank you!
The option

```js
const map = fp.map.convert({cap: false})
map(console.log)([1,2,3]); 
// prints
// 1 0 [1, 2, 3]
// 2 1 [1, 2, 3]
// 3 2 [1, 2, 3]
```
 worked perfectly for me.

**Comment by CodeFalling** [comment]
```js
const iter = ([key, value]) => console.log(key, value);
fp.flow(fp.entries, fp.map(iter))([1, 2, 3]);
// prints
// 0 1
// 1 2
// 2 3
```

may be another way
