### ISSUE TITLE
Syntax sugar on top of _.isUndefined

### ISSUE THREAD

**Issue by grillorafael** [lodash/lodash#2388]
My use case is:

I have an array and I map into possible elements. So I might return something or not. At the end, I filter using `_.negate(_.isUndefined)`.

It would be useful to have a `_.isDefined` with wraps `_.negate(_.isUndefined)`

**Comment by Archimidis** [comment]
Why not using _.reject instead?

**Comment by jdalton** [comment]
Dup of #137.
