### ISSUE TITLE
fp wiki wording

### ISSUE THREAD

**Issue by olsonpm** [lodash/lodash#2390]
I thought about this a bit and am not confident in a proper fix, so I'll describe the issue:

Under 'Exceptions to the rules'
> Methods that accept an array of arguments as their second parameter:
`invokeArgs`, `invokeArgsMap`, `partial`, `partialRight`, & `without`

This isn't correct for `without`.  I think the two ways to this would placing another section above e.g.
> Methods that accept an array of arguments as their first parameter

Or rewording it e.g.
> Methods that accept an array of arguments in lieu of the rest parameter

I also couldn't decide whether moving it down by the New Methods section would make sense because it's not actually an exception to the argument order, just a result of fixing arity.

If you think this is too minute, feel free to close.

**Comment by jdalton** [comment]
Thanks! For now I just removed the argument number specifier from the note.

**Comment by olsonpm** [comment]
That's definitely the simplest solution.  Thanks much
