### ISSUE TITLE
Build custom bundle

### ISSUE THREAD

**Issue by yesvods** [lodash/lodash#2391]
Hi，I just want few function of lodash and want to pack the few function together. How can I build them as slim as possible.

**Comment by demoneaux** [comment]
You can use [lodash-cli](https://github.com/lodash/lodash-cli) to create custom builds, or use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash)/[lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) if you're using Babel/Webpack.
