### ISSUE TITLE
FP: round has a fixed arity of one?

### ISSUE THREAD

**Issue by jamesrom** [lodash/lodash#2393]
It's understandable that the FP version of `_.round` has a fixed arity of one, but it would be nice to have a `roundBy`/`roundTo` function with a fixed arity of two. So you can pass a precision argument, like regular lodash.

**Comment by jdalton** [comment]
Thanks @jamesrom!

We've been adding multi arity forms of these kinds of methods as folks request them.
We've had requests for different methods to be named [roundTo](https://github.com/lodash/lodash/issues/2310) so I'm not sure naming this as such is the best choice.
Maybe `_.roundPrecision`? Or if we use `_.roundTo` then we'd need an alternative for #2310.

**Comment by jdalton** [comment]
🚲 🏠 time!

**Comment by jdalton** [comment]
Until this is bikeshedded some more we'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by jfmengels** [comment]
:+1: for the feature.

Don't have much of an opinion on the name. If I had to choose on my own, I'd probably go for `roundTo` for this, and `roundInterval` on #2310.

**Comment by jdalton** [comment]
Keep in mind there are other round methods too `ceil` and `floor` too so it would be `ceilTo` and `floorTo` and then potentially `ceilInterval` and `floorInterval` (kinda gross)

**Comment by jfmengels** [comment]
Hmm, so we need to find a consistent non-gross naming convention... sounds familiar.

**Comment by macrozone** [comment]
just run into this.

ended up with this:

```
import roundClassic from 'lodash/round';
const roundTo = p => partial(roundClassic, [__, p]);
```

but It feels awkward. I would also have expected round to be binary, not unary.

**Comment by chmac** [comment]
Just hit this myself. Any plans to add `roundTo` or `roundPrecision`?

**Comment by Mr-Wallet** [comment]
@jdalton I think this and #2559 are duplicates, which could be splitting the upvotes.

**Comment by jdalton** [comment]
Thanks @Mr-Wallet! I marked #2559 a dup of this since this issue is older & has more doots.

**Comment by macrozone** [comment]
@jdalton and now both are closed ;-)

**Comment by lennerd** [comment]
Any news on this?

**Comment by ryanhomer** [comment]
+1
This would be great since JavaScript doesn't have this either.

I'm doing this for now, but there must be a more optimal, less yucky way 😝

    export const roundTo = _.curry((precision, value) => {
      const e = Math.pow(10, precision);
      return Math.round(value * e) / e;
    });

**Comment by pmaier983** [comment]
+1
Mb this is out there somewhere after four years, but i have found it. Would love this feature!

**Comment by bganicky** [comment]
Is this at least achievable by using `round.convert`? I couldn't figure out how. For the time being I ended up with this:

```js
import _round from 'lodash/round'
import curryN from 'lodash/fp/curryN'
import flip from 'lodash/fp/flip'

export const round = curryN(2, flip(_round))
```

**Comment by dmitry-mashkov** [comment]
@jdalton shouldn't we reopen the issue since after I looked through all related links to this topic and to #2559 I haven't found any activity or PRs. Is there a voting problem? There are currently 42 likes for the [first post](https://github.com/lodash/lodash/issues/2393#issue-157886080)
It would be great to have a working roundTo function out of the box.
