### ISSUE TITLE
_.set with own delimiter

### ISSUE THREAD

**Issue by Waize** [lodash/lodash#2395]
Hi,

I wonder if it is possible to provite the _.set-method with a given delimiter. 

Currently it only split the object at dots. 

But I would like to define the delimiter:
_.set(object, path, value, delimiter) while path = "ab_ha_k" and delimeter "_"

Regards.

**Comment by jdalton** [comment]
You can pass an array instead.
This allows you to split by whatever you want and pass the result as the path.
