### ISSUE TITLE
Counterintuitive `includes` behavior

### ISSUE THREAD

**Issue by chrisallenlane** [lodash/lodash#2397]
Hi, guys

The behavior I'm seeing for [includes](https://lodash.com/docs#includes) really doesn't make much sense to me:

```js
const lodash = require('lodash');

var a = [1, 2, 3];

console.log(lodash.includes(a, 1));       // true
console.log(lodash.includes(a, 2));       // true
console.log(lodash.includes(a, 1, 2));    // false
console.log(lodash.includes(a, 1, 2, 3)); // true
```

(Similar behavior is even noted in the second example of the docs linked above.)

I would expect the `false` in the third case to also be `true`, because `a` includes both `1` and `2`.

Is this behavior intentional, or might we have a bug?

If it **is** intentional, may I ask what the rationale is? I can't make sense of this.

FWIW, I'm running `node v4.0.0` on Crunchbang Linux, which is basically Debian Wheezy.

Thanks!

**Comment by chrisallenlane** [comment]
Sorry, I'm dumb. I developed tunnel-vision regarding how I expected this to work, and accidentally overlooked the optional `fromIndex` parameter. Closing.

**Comment by jfmengels** [comment]
Well, no, actually, what you're hitting is the use of the optional, and undocumented (at least not shown in the docs), `guard` param, which looks like it's disabling the `fromIndex` param.

I see that in the code, the jsdoc entry for the `guard` starts `@param-`, and the extra `-` makes the parm undocumented. @jdalton is that a bug or a feature?

**Comment by jdalton** [comment]
> is that a bug or a feature?

That's a feature.
