### ISSUE TITLE
_.iteratee doc example 

### ISSUE THREAD

**Issue by Spown** [lodash/lodash#2399]
in the end of [_.iteratee doc example](https://lodash.com/docs#iteratee) there is this piece

```js
_.filter(['abc', 'def'], /ef/);
// → ['def']
```

1. what does it have to do with ``_.iteratee``?
2. it doesn't even work as described:

```js
_.filter(['abc', 'def'], /ef/);
// -> ["abc", "def"]
```
3\. How do I actually do it right? theoretically ``_.filter(['abc', 'def'], /ef/.test)`` should do, but I get ``TypeError: undefined is not a non-null object`` instead... I mean without wrapping it in an additional function.

Thank you in advance.

**Comment by jdalton** [comment]
It's showing how the customization of `_.iteratee` the line above can be used to create new shorthands.
