### ISSUE TITLE
copyArray speed too low

### ISSUE THREAD

**Issue by SuunZhu** [lodash/lodash#2402]
Why _.copyArray() do not use Array.slice(), Array.slice() is five times speed then  _.copyArray(). the test code like this:

`function copyArray(source, array) {
    var index = -1,
    length = source.length;

    array || (array = Array(length));
    while (++index < length) {
    array[index] = source[index];
    }
  return array;
}
function main()
{
	var arr = [10000000];
	var arr2 = [10000000];
	var arr3 = [10000000];
        var i = 0;
	while(++i < 1000000){
		arr.push(i);
	}
	var t1 = new Date();
	arr2 = arr.slice();
	var t2 = new Date();
	copyArray(arr,arr3);
	var t3 = new Date();
	
	console.log('sliceTime = ' + (t2 -t1) +
				'copyTime='+(t3 - t2));
	console.log(arr2 == arr )
	console.log(arr3 == arr)
	
}`
// The test result :sliceTime = 5copyTime=36

**Comment by jdalton** [comment]
`copyArray` is handy as it treats arrays as dense (which Lodash methods should).
Your `arr`, `arr2` and `arr3` arrays are all single element arrays.
