### ISSUE TITLE
throttle/debounce only if the arguments are the same

### ISSUE THREAD

**Issue by bfred-it** [lodash/lodash#2403]
Example situation, reuse of the same throttled function in different contexts:

```js
const log = throttle(console.log.bind(console), 1000);
AA.onscroll = log;
B.onscroll = log;
C.onscroll = log;
D.onscroll = log;

///

AA.scrollTo(0, 3); //--> "event {...}"
AA.scrollTo(0, 3); //--> no log // ok!
B.scrollTo(0, 6); //--> no log // not ok
C.scrollTo(0, 3); //--> no log // not ok
D.scrollTo(0, 6); //--> no log // not ok
```

Ideal solution, like with memoize's resolver:

```js
const log = throttle(console.log.bind(console), 1000, {
  resolver: e => e.currentTarget
});
AA.onscroll = log;
B.onscroll = log;
C.onscroll = log;
D.onscroll = log;

///

AA.scrollTo(0, 3); //--> "event {...}"
AA.scrollTo(0, 3); //--> no log // ok!
B.scrollTo(0, 6); //--> "event {...}"
C.scrollTo(0, 3); //--> "event {...}"
D.scrollTo(0, 6); //--> "event {...}"
```

Current solution:

```js
AA.onscroll = throttle(console.log.bind(console), 1000);
B.onscroll = throttle(console.log.bind(console), 1000);
C.onscroll = throttle(console.log.bind(console), 1000);
D.onscroll = throttle(console.log.bind(console), 1000);

///

AA.scrollTo(0, 3); //--> "event {...}"
AA.scrollTo(0, 3); //--> no log // ok!
B.scrollTo(0, 6); //--> "event {...}"
C.scrollTo(0, 3); //--> "event {...}"
D.scrollTo(0, 6); //--> "event {...}"
```

In short currently I have to create as many throttled functions as there are elements. Not a big deal though, it might be easier than implementing the resolver in `_.throttle`

**Comment by jdalton** [comment]
Hi @bfred-it!

Have you tried using `_.memoize` + `_.throttle`?

**Comment by bfred-it** [comment]
I thought about that but I don't think that would work unless I manually clear memoize's cache after the time's up, right?

**Comment by bfred-it** [comment]
At that point I might as well just use the last solution I showed, ^_^" especially because I import lodash functions selectively

**Comment by semikolon** [comment]
I did this for a React/Reflux app I'm working on:

**Comment by zeroasterisk** [comment]
@jdalton thanks for lodash (et. al.) 

seems like it might be a moderately common use-case.

would you mind telling me if I missed anything with the following mixin as you recommended?

```js
// add a mixin to expose a debounceReduce
// this makes debounce only bounce if arguments match
// note that you can pass options.resolver function to memoize
// https://lodash.com/docs/4.17.4#memoize
_.mixin({
  debounceReduce: (func, wait = 0, options = {}) => (
    _.debounce(_.memoize(func, options.resolver), wait, options)
  ),
});
```

**Comment by Galadirith** [comment]
@zeroasterisk I've been playing around with this and I think I have a simplified memoize debounce function. However it is simplified so works only for a single parameter function and doesn't accept options, but I think its definitely possible to extend it to handle those.

**Code**

```javascript
_.mixin({
  memoizeDebounce: function(func, wait=0) {
    var mem = _.memoize(function(param) {
      return _.debounce(func, wait)
    });
    return function(param){mem(param)(param)}
  }
});
```

**Example**

```javascript
md = _.memoizeDebounce(console.log, 2000);

md('hello, world');

// Output: 'hello, world' (after 2s)

md('hello, world');
md('hello, world, again');

// Output: 'hello, world' (after 2s)
// Output: 'hello, world, again' (<2s after the previous output)

md('hello, world');
md('hello, world, again');
md('hello, world');

// Output: 'hello, world, again' (after 2s)
// Output: 'hello, world' (<2s after the previous output)
```

**Comment by Galadirith** [comment]
@zeroasterisk Heres a slightly more complicated mixin that I think would work for an arbitrary number of arguments, however I haven't tested this

```javascript
_.mixin({
  memoizeDebounce: function(func, wait=0, options={}) {
    var mem = _.memoize(function() {
      return _.debounce(func, wait, options)
    }, options.resolver);
    return function(){mem.apply(this, arguments).apply(this, arguments)}
  }
});
```

**Comment by andrewluetgers** [comment]
@Galadirith that works great, thanks!

**Comment by xerosanyam** [comment]
is there a way to get the parameters as a list ?

**Comment by vipcxj** [comment]
How can we just clean memoize cache just after the time's up?

**Comment by derekgreer** [comment]
@vipcxj There should be no need to clear the cache that's used by memoize.  What is being cached are functions which call debounce, not the return values of the function being debounced.  That is to say, what is cached is which debounce function to call, not the value the function ends up returning.  This works by directing calls to different debounce function invocations depending on the value of the first parameter (or the value returned by the options.resolver).

**Comment by akhrabrov** [comment]
Just wrote gist for memoized async debounced  function based on arg
Could be useful

https://gist.github.com/nzvtrk/1a444cdf6a86a5a6e6d6a34f0db19065

**Comment by baileytincher** [comment]
> @zeroasterisk Heres a slightly more complicated mixin that I think would work for an arbitrary number of arguments, with the cache keyed in the same way as `memoize` (use the first argument unless a resolver is provided through `options`). However I haven't tested this
> 
> ```js
> _.mixin({
>   memoizeDebounce: function(func, wait=0, options={}) {
>     var mem = _.memoize(function() {
>       return _.debounce(func, wait, options)
>     }, options.resolver);
>     return function(){mem.apply(this, arguments).apply(this, arguments)}
>   }
> });
> ```

Building off the work of @Galadirith and @zeroasterisk I wanted to provide a TypeScript compatible version for those using more modern syntax. Lodash's use of type generics with functions is a bit strange so I had to do casts in a few spots to get around it. Someone else may be able to clean those up.

```typescript
import _ from 'lodash';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export interface MemoizeDebouncedFunction<F extends (...args: any[]) => any> {
  (...args: Parameters<F>): void;
  flush: (...args: Parameters<F>) => void;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function memoizeDebounce<F extends (...args: any[]) => any>(
  func: F,
  wait = 0,
  options: _.DebounceSettings = {},
  resolver?: (...args: Parameters<F>) => unknown
): MemoizeDebouncedFunction<F> {
  const debounceMemo = _.memoize<(...args: Parameters<F>) => _.DebouncedFunc<F>>(
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    (..._args: Parameters<F>) => _.debounce(func, wait, options),
    resolver
  );

  function wrappedFunction(
    this: MemoizeDebouncedFunction<F>,
    ...args: Parameters<F>
  ): ReturnType<F> | undefined {
    return debounceMemo(...args)(...args);
  }

  wrappedFunction.flush = (...args: Parameters<F>): void => {
    debounceMemo(...args).flush();
  };

  return (wrappedFunction as unknown) as MemoizeDebouncedFunction<F>;
}
```

**Comment by JonParton** [comment]
@baileytincher  - Took me ages struggling with your typescript function to spot the mistake here... In your declaration of `wrappedFunction` you have a `this` parameter that makes no sense and is breaking the whole way this debouncing works. 

> ```ts
> .......... removed code ......
>   function wrappedFunction(
>     this: MemoizeDebouncedFunction<F>, // THIS BUGGER!!!
>     ...args: Parameters<F>
>   ): ReturnType<F> | undefined {
>     return debounceMemo(...args)(...args);
>   }
> 
>   wrappedFunction.flush = (...args: Parameters<F>): void => {
>     debounceMemo(...args).flush();
>   };
> 
>   return (wrappedFunction as unknown) as MemoizeDebouncedFunction<F>;
> }
> ```

If you remove `this` then everything starts working. 

Full code for anyone else that may want to use it in the future: (Although I'm not a fan of the type castings either but I don't have the brain power to try and fix right now 😂)

```ts
import _ from 'lodash';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export interface MemoizeDebouncedFunction<F extends (...args: any[]) => any> {
  (...args: Parameters<F>): void;
  flush: (...args: Parameters<F>) => void;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function memoizeDebounce<F extends (...args: any[]) => any>(
  func: F,
  wait = 0,
  options: _.DebounceSettings = {},
  resolver?: (...args: Parameters<F>) => unknown
): MemoizeDebouncedFunction<F> {
  const debounceMemo = _.memoize<
    (...args: Parameters<F>) => _.DebouncedFunc<F>
  >(
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    (..._args: Parameters<F>) => _.debounce(func, wait, options),
    resolver
  );

  function wrappedFunction(...args: Parameters<F>): ReturnType<F> | undefined {
    return debounceMemo(...args)(...args);
  }

  wrappedFunction.flush = (...args: Parameters<F>): void => {
    debounceMemo(...args).flush();
  };

  return wrappedFunction as unknown as MemoizeDebouncedFunction<F>;
}
```
Contrived Example usage: 
```ts
const debouncedfunction = memoizeDebounce(
  (firstName: string, lastName:string, message: string) => {
    console.log(`${message}`);
  },
  1000,
  {}, // Debounce options here
  (firstName, lastName:string) => (firstName + "-" + lastName)
);

debouncedfunction("dave", "smith","Hey Jim")
debouncedfunction("tom", "smith","Hey Tom")
debouncedfunction("dave", "smith","Hey Dave")

// Console output:
// "Hey Tom"
// "Hey Dave"

// "Hey Jim won't show as it was debounced as it had the same "firstName" and "lastName" as the 3rd call. 

```

**Comment by baileytincher** [comment]
@JonParton I believe you may be a bit mistaken on how "this" works in TypeScript. It is a fake arg that allows you to specify a more narrow type, but is not exposed to the caller. See the reference docs on it: https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters

In this case it is unused and doesn't need to be specified. Just copied above from someone else's code example. I'd be curious to see how it broke in your use case, as I never had an issue with it.

**Comment by JonParton** [comment]
> @JonParton I believe you may be a bit mistaken on how "this" works with functions in TypeScript. It is a fake arg that allows you to specify a more narrow type, but is not exposed to the caller. See the reference docs on it: https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters
> 
> In this case it is unused and doesn't need to be specified. Just copied above from someone else's code example. I'd be curious to see how it broke in your use case, as I never had an issue with it.

It was breaking as the 1st passed argument to the wrapped function was becoming discarded by the this parameter declaration so the 2nd passed argument to the debounced wrapper was being passed as the first argument to the memoization  and the execution of the actual function. (ie in the Contrived example usage I put in `lastName` was being passed to the function as `firstName`, `message` as `lastName` and `undefined` as `message` to both the momoization `resolver` and the passed `func`) 

At the point `this` is being used above it is not an typescript  type declaration but an actual parameter definition and use! 

In the original code it is an `apply` and is written as a mixin so I think there is vastly different behaviour.

If I get time later I'll set up a code sandbox but feel free to try using the exact code!

**Comment by HeroBanana** [comment]
import memoize from "lodash/memoize";
import throttle from "lodash/throttle";

Another typescript sample:

```
export function memoizeThrottle<T extends (...args: any[]) => any>(
  func: T,
  wait = 0,
  options?: Parameters<typeof throttle<T>>[2],
  resolver?: Parameters<
    typeof memoize<(...args: Parameters<T>) => ReturnType<typeof throttle<T>>>
  >[1]
) {
  const mem = memoize<
    (...args: Parameters<T>) => ReturnType<typeof throttle<T>>
  >(function () {
    return throttle<T>(func, wait, options);
  }, resolver);

  return function (...args: Parameters<T>) {
    return mem(...args)(...args);
  };
}
```

**Comment by AlexErrant** [comment]
Thanks Bailey, Jon, Nick. Minor suggestion - you can avoid `any` by using `Parameters<_>` and `ReturnType<_>`:

```
function memoizeThrottle<F extends (...args: Parameters<F>) => ReturnType<F>>(
```

`any` should be avoided for reasons given in [the eslint rule](https://typescript-eslint.io/rules/no-explicit-any/):

> Using `any` disables many type checking rules and is generally best used only as a last resort

**Comment by ljharb** [comment]
@robross0606 `Object.defineProperties(memoizedDebounce, Object.getOwnPropertyDescriptors(debounce))`?
