### ISSUE TITLE
_.reduce on a array like object skips property 0

### ISSUE THREAD

**Issue by licaon** [lodash/lodash#2404]
Hi

If i have an array like object: { 0: 1, 1: 2 }, if i call a reduce on it, it skips the 0 property.
quick test:
```
const obj = {
  0: 1,
  1: 2
}

_.reduce(obj, (a,v,i) => console.log(i,v));
```
output: 1 2

Lodash version 4.13.1

**Comment by jdalton** [comment]
The object `{ 0: 1, 1: 2 }` is not seen as array-like because it's missing a `length` property. What you're seeing is the first value, at `0`, being used as the `accumulator` in the absence of one being provided.
