### ISSUE TITLE
_.multiply with no arguments should return 1

### ISSUE THREAD

**Issue by emil-mi** [lodash/lodash#2405]
To ensure consistency with _.add _.multiply with no args should return 1 so:
* _.multiply() === 1
* _.multiply(value) === value
* _.multiply(value1, value2) === value1*value2

**Comment by jridgewell** [comment]
Ooo, math. I like it, these should return the [identity elements](https://en.wikipedia.org/wiki/Field_(mathematics)#Definition_and_illustration) by default.

**Comment by jdalton** [comment]
@emil-mi 
> To ensure consistency with `_.add`, `_.multiply` with no args should return `1` so:

`_.add` with no args returns `0` (so does `_.multiply`)

@jridgewell 
> Ooo, math. I like it, these should return the identity elements by default.

If you provide 1 argument then they act as identity functions.

**Comment by jdalton** [comment]
I'm not clear on why `_.multiply` should return `1`.

**Comment by jdalton** [comment]
Ah this is because it's used as the default multiplicand for when you pass one arg, `multiplier` its `multiplicand` is `1`. I feel ya.

**Comment by jridgewell** [comment]
> If you provide 1 argument then they already act as identity functions.

Not identity elements as in `_.identity`, identity elements as in the identity of the field you're in. The math meaning, not the JS meaning.

**Comment by Delapouite** [comment]
> The math meaning, not the JS meaning.

Yes it's useful to define Monoids.
