### ISSUE TITLE
Support Fantasy Land / Custom Types

### ISSUE THREAD

**Issue by JAForbes** [lodash/lodash#2406]
Thank you everyone for their hard work on this project and lodash/fp.  Anything that encourages composition is a huge win for the JS ecosystem.

I'm proposing that Lodash supports dispatch to methods on custom types.  This is the number one feature I miss when using lodash/fp in place of Ramda.

An example: say I am using a Bluebird promise that has the methods `filter`, `reduce` and `map`.  With Ramda I can use `R.filter`, `R.reduce` and `R.map`to dispatch to these methods on the Promise.

```js
var R = require('ramda')
var Promise = require('bluebird')

var numbers = Promise.all([1,2,3,4])

var f = R.pipe(
  R.map(R.multiply(2))
  ,R.filter( R.gt( R.__, 4))
  ,R.sum // dispatches to Promise::reduce
)
await f(numbers) //=> 14

f([1,2,3,4]) //=> 14
```

This dispatch allows you to write one function that can traverse multiple data types.  You could just as easily pass in a fantasy land compatible stream like most.js or flyd.  Or a Future, Task, Maybe, Either etc.  And most importantly it would support any type that the user may want to develop within their own code base.

Note that above we don't need to concern ourselves with chaining `.then` calls.  We have abstracted away the specifics of the underlying type.  And now the function `f` (from above) would work equally well on an array, or a hundred other types.

Lodash is such an important part of the JS ecosystem, I would see supporting this functionality as both extremely useful and also a vote of confidence in composition.

**Comment by jdalton** [comment]
Thanks @JAForbes!

Underscore, and so Lodash, used to dispatch to methods here and there. Over time that was pulled. I can see the benefits for sure but it can also introduce unintended or accidental dispatching since it just duck types. That said I dig giving devs options and I'm curious if lodash/fp could implement it in a configurable way.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by TylorS** [comment]
As a user and contributor to [most.js](https://github.com/cujojs/most) which implements a large amount of the fantasy-land specification, I would absolutely love this. Currently I use ramda, but as most.js is heavily focused on performance I would find lodash to be a great compliment to most.js

:+1:

**Comment by barneycarroll** [comment]
Accidental duck typing is theoretically precluded by the fantasy land specification, no? By opting in to APIs that explicitly conform to the spec, the user should be able to isolate any such accidents — and by deferring to the spec, any implementation ~~washes it's hands~~ shares responsibility for producing rational outcomes. Which isn't to say fantasy land adherence guarantees a totally procedural conversion task for Lodash's entire API — but duck typing is part and parcel of the exercise, as it were.

I think this should be developed as a persistent fork with the aim of replacing / providing a 'stronger' flavour of the current FP branch.

**Comment by Avaq** [comment]
> It can also introduce accidental dispatching since it's just duck typing

It's worth noting that Fantasy Land might move to prefixing its functions (https://github.com/fantasyland/fantasy-land/issues/122), to reduce the chances of ducktyping clashes.

**Comment by ChetHarrison** [comment]
yo JD let's do this 👍

**Comment by ChetHarrison** [comment]
I have spent 3 years looking at the same interface with different names and it is a serious waste of time trying to piece it together.

**Comment by ChetHarrison** [comment]
js just got supremely functional with 2015 and we need to get some kind of spec. Your lib pretty much controls the js world so this is a chance akin to A+. If dev time is a major issue let's quantify that and recrute.

**Comment by dgreene1** [comment]
👍

**Comment by JAForbes** [comment]
@jdalton The Fantasy Land spec now prefixes all function names.  So name collisions are no longer an issue when implementing the specification.

**Comment by jrsinclair** [comment]
I'd love to see support for the fantasy land specification in lodash/fp. When I'm writing lodash code, I end up writing shell functions to do exactly the kind of dispatch @jdalton describes. Implementing fantasy land support would save me writing those functions by hand all over the place.

**Comment by gabejohnson** [comment]
@jdalton would you accept a PR addressing this issue?

**Comment by jdalton** [comment]
Not at this time. You'll know when the issue is opened to PRs.

**Comment by gunar** [comment]
How many more votes do we need?

**Comment by jdalton** [comment]
Voting is used as an indicator to see what features folks are interested. There is no magic number that will force me to implement something. I use this metic to better make informed API decisions.
