### ISSUE TITLE
merge array of strings

### ISSUE THREAD

**Issue by dnfrolov** [lodash/lodash#2408]
Hey, I can't get merged array of strings:

`_.merge({a: ['a']}, {a: ['b']});`

Output:
`{ a: [ 'b' ] }`

_.VERSION is 4.13.1

**Comment by dnfrolov** [comment]
I found example with **mergeWith** but why it's it a default behavior?

**Comment by jdalton** [comment]
We opted to match the behavior of jQuery's deep extend by default, `$.exend(true, ...)`.
