### ISSUE TITLE
_.clone documentation for Core vs. Full

### ISSUE THREAD

**Issue by iccir** [lodash/lodash#2409]
Per the [Build Differences](https://github.com/lodash/lodash/wiki/build-differences) wiki page, the Core build doesn't support robust cloning.

That's fine; however, it's not clear in the [clone documentation](https://lodash.com/docs#clone) that there is different behavior.  The documentation implies that array buffers / dates / regexes will be cloned.

**Comment by jdalton** [comment]
Hi @iccir!

The site documentation is for the full build. Feel free to update the [Build Differences](https://github.com/lodash/lodash/wiki/build-differences) wiki page if you'd like bits clarified or tweaked.

**Comment by iccir** [comment]
Thanks!  The Build Differences page is clear once I re-read it.  Having a caveat on the main site that the API documentation is for the full build may be useful.  Then again, anybody using the Core build will ideally do additional research.
