### ISSUE TITLE
[Documentation] Expose _ variable to window

### ISSUE THREAD

**Issue by roblav96** [lodash/lodash#2412]
It would be great if you could expose the _ variable to window on the documentation page to allow users to play around with lodash while reading the documentation.
[Docs](https://lodash.com/docs)

**Comment by roblav96** [comment]
### Edit:
I press refresh and _ is exposed to the window. Spooky 👻

**Comment by jdalton** [comment]
May be related to https://twitter.com/mattzeunert/status/738853366734950400.

**Comment by roblav96** [comment]
### Thank you! 😄
