### ISSUE TITLE
Manipulated argument order of getOr is not reflected in subsequent functions within currying sequence

### ISSUE THREAD

**Issue by jameshopkins** [lodash/lodash#2413]
Hi there,

I've been using `lodash/fp` for the past week and love it already. However, I've come across an issue where the currying sequence of `getOr` doesn't seem to be updated after reordering it's arguments via `rearg`.

```js
const map = {
  test: 'hello'
};

rearg([0, 2, 1], getOr)(null, map, 'test') //$
// $> 'hello'

rearg([0, 2, 1], getOr)(null)(map)('test') //$
// $> null
```

I'd expect the second invocation to be no different than the first, and therefore return `hello`.

Please let me know if I'm doing something wrong and there's an easy workaround.

Cheers

James

**Comment by jdalton** [comment]
Thanks!

**Comment by jameshopkins** [comment]
Cheers for fixing so quickly, @jdalton. How frequent is the release cycle with Lodash?

**Comment by jdalton** [comment]
At least once a month or so.
