### ISSUE TITLE
_.conforms and _.matches

### ISSUE THREAD

**Issue by jfmengels** [lodash/lodash#2415]
I have just noticed the existence of `conforms` and found it kind of odd, or at least impractical that you can only have predicate functions associated to each key, and not a direct value like `matches` does.

That means that if I have multiple properties to check, some with a predicate, and some where the values are fixed, I'd need to use both `matches` and `conforms`, and have two `source` objects, one for each of them.

```js
const object = {
  a: 10,
  b: 100
}; // imagine a bigger object in practice

const doesMatch = _.matches({a: 10})(object) && _.conforms({
  b: (b) => b > 100
})(object);
```

Wouldn't it be more useful if one of those methods accepted both predicates and values? (probably `conforms`, as it wont be breaking change for this one). I'm not sure I actually see the point of having both methods in the long run, except if people actually use `matches` to check whether objects have the same function in two objects.

By the way, another thing that I noticed while writing this: `conforms` doesn't accept nested paths, which looks very impractical to me.

**Comment by jdalton** [comment]
Ya. I thought about mixing them but wanted to keep a separation to start. Nested functionality is neat but more complicated so I'll punt on that until there's more demand.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
