### ISSUE TITLE
sortBy behaviour 4.10.0 vs. 4.11.0

### ISSUE THREAD

**Issue by stschaefer** [lodash/lodash#2418]
Hi guys,

I experience a different sorting behaviour between version 4.10.0 and 4.11.0

I made a Codepen with version 4.10.0...
http://codepen.io/hoody/pen/oLxeQb

...and version 4.11.0...
http://codepen.io/hoody/pen/ZOWJVP

Expected behaviour: Items are ordered by _labelPosition_

Did I miss a syntax change of this function? Do you have a hint for me?

Greetings,
Stefan

**Comment by jdalton** [comment]
Probably came down to [this change](https://github.com/lodash/lodash/commit/bfe6e06b5a3b36f3d43f103913c73745e5d4e6e7).
