### ISSUE TITLE
can i use keyword `import` with webpack

### ISSUE THREAD

**Issue by taoqf** [lodash/lodash#2419]
i can not use `import`:
import chunk from 'lodash/chunk';
insteadof
var chunk = require('lodash/chunk');

**Comment by jdalton** [comment]
You totally can 😸 ! See [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin).

**Comment by c-dante** [comment]
As an aside, this also works fine:

```js
import { chunk } from 'lodash';
```

**Comment by taoqf** [comment]
@c-dante, i know that `import { chunk } from 'lodash';` works fine, i just don't want require the whole file. it is really to big for me.
thanks @jdalton , i will have a try.

**Comment by taoqf** [comment]
I knew it.
```
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
```

**Comment by taoqf** [comment]
why do not lodash just support es6?
[https://github.com/lodash/lodash-webpack-plugin/issues/29](https://github.com/lodash/lodash-webpack-plugin/issues/29)
use lodash-webpack-plugin could not resolve my problem.

**Comment by jdalton** [comment]
It does. Sorry you're having trouble. Feel free to hit up out [gitter chat](https://gitter.im/lodash/lodash).
