### ISSUE TITLE
question: how to find a string in a collection

### ISSUE THREAD

**Issue by PolGuixe** [lodash/lodash#2420]
My strategy is to use `_.includes(_.flatMapDeep(Collection, (o) => {return o}), stringToFind)`. 

However when using `_.flatMapDeep()` in: 
``` javascript
collection =
{
"_id": "1a2b3c",
"products": [
 { "productId": "12345"},
 { "productId": "67890"}
],
"orders": [
  "abcde",
  "fghij"
]
}
```
it returns `["1a2b3c", Object, Object, "abcde", "fghij"]` and `_.includes()` is not checking in nested fields. 
Hence in `_.includes(_.flatMapDeep(collection, (o) => {return o}), "12345")`, it will return false, but I want it to return true. 

How would you approach this problem?

**Comment by jdalton** [comment]
Hi @PolGuixe!

This kind of question is perfect for our [gitter chat](https://gitter.im/lodash/lodash)!
