### ISSUE TITLE
lodash4 _.has(): incorrect behaviour with window.window in IE11

### ISSUE THREAD

**Issue by IgorAufricht** [lodash/lodash#2423]
Code to reproduce:
```
window.value = 123;

console.log(window.value);
console.log(window.window.value);

console.log(_.has(window, 'value'));
console.log(_.has(window, 'window.value'));
```

Expected result (correct in Chrome with lodash 3 & 4, in IE11 with lodash 3):
```
123
123
true
true
```

Actual result in IE11 with lodash 4:
```
123
123
true
false
```

Context:
* [`window.window` is a reference to `window`](https://developer.mozilla.org/en-US/docs/Web/API/Window/window)

Fiddles:
* lodash 4: https://jsfiddle.net/rkp6aLtc/1/
* lodash 3: https://jsfiddle.net/rkp6aLtc/2/

**Comment by jdalton** [comment]
The method is a `Object#hasOwnProperty` check. I'm guessing that IE 11 has that as another form. You can try `_.hasIn` instead.
