### ISSUE TITLE
_.assignWith unexpected result when customizer returns undefined.

### ISSUE THREAD

**Issue by wawyed** [lodash/lodash#2424]
According to the documentation "This method is like _.assign except that it accepts customizer which is invoked to produce the assigned values. **If customizer returns undefined, assignment is handled by the method instead**. The customizer is invoked with five arguments: (objValue, srcValue, key, object, source)." 

So I would have assumed that if you don't return anything on the customizer it should do what assign does, although that doesn't seem to be the case. Is the documentation wrong?

Code to reproduce:

``` javascript
  var dest = {};
  var src = { a: '1', b: '2' };
  
  _.assignWith(dest, src, function(srcValue, destValue, key) {
     if(key === 'a') {
      	return destValue + 'mod';
      }
  });
  
  console.log(dest);
```

Expected result:

` {a: '1mod', b: '2' }`

Actual result:

`{a: '1mod', b: undefined }`

Fiddle demonstrating issue:

https://jsfiddle.net/bz5Lswqs/

**Comment by jdalton** [comment]
Thanks!

**Comment by fraziermork** [comment]
The npm lodash.assignwith package still has this problem.
