### ISSUE TITLE
Hoping for explanation on `kebabCase` numbers logic.

### ISSUE THREAD

**Issue by bbudd** [lodash/lodash#2425]
Can you please explain the logic behind `kebabCase` when dealing with numbers? If, for example, I do `_.kebabCase('x1')`, I'd expect it to just do the equivalent of `identity`, but I see `x-1`. Likewise with `_.kebabCase('r2d2)`, I'd expect the output to be `r2-d2`. Would a second parameter for dealing with numbers make sense? 

(I know this is an edge case)

**Comment by jdalton** [comment]
Hi @bbudd!

Numbers are considered their own word.
```js
_.words('r2d2');
// => ["r", "2", "d", "2"]
```
