### ISSUE TITLE
Lodash as AMD module

### ISSUE THREAD

**Issue by beruic** [lodash/lodash#2426]
I noticed at https://github.com/lodash-archive/lodash-amd that it is discontinued in favor of https://github.com/lodash/lodash/tree/amd. Does that mean that I can just get `lodash` from bower and use it as an AMD module?

It would be nice with clearer documentation on the matter,

**Comment by jdalton** [comment]
Bower supports git tags so you can access any of the tags we have.

**Comment by beruic** [comment]
I'm sorry, but I don't understand what you mean.

Right now I have put `"lodash": "~4.13.1",` in my `bower.json`. If I try to get the package `lodash-amd` i get the old discontinued version. I build my RequireJS config automatically from `bower.json`, whoch results in the entry `lodash: "lib/lodash/lodash",`.
Will this work?

**Comment by jdalton** [comment]
>  I'm sorry, but I don't understand what you mean.

See bower's documentation for how to reference tags.

**Comment by elijahsmith** [comment]
@jdalton which tags are you suggesting we reference for a particular lodash amd build?  the only tagged releases are on the master branch -- not on the amd branch.

We *can* reference a particular commit -- "bower install lodash#2ab869e88a1238ec908fce05c7b77933361aadfe" for the 4.13.1 release on the amd branch -- but that's pretty ugly and non-transparent (which version is that???)  

Would it be possible to add tags for the amd branches specifically?  Perhaps for the npm, npm packages, etc branches as well?

**Comment by jdalton** [comment]
See their [documentation](https://bower.io/docs/api/#install):
<img src="https://cloud.githubusercontent.com/assets/4303/16349344/39436fbc-3a0d-11e6-9e5a-c944308671ad.png" height=70% width=70%>

<img src="https://cloud.githubusercontent.com/assets/4303/16349358/4b071bae-3a0d-11e6-8a48-696e29b5b93b.png" height=70% width=70%>

So then you specify it as:
```bash
bower install lodash#4.13.1-amd
```
