### ISSUE TITLE
_.merge behaves incorrect when Object.prototype has any custom method in Lodash 3.10.1, 4.x behaves normal.

### ISSUE THREAD

**Issue by xieranmaya** [lodash/lodash#2431]
Run the below code and see the result:
```js
s = {albums:{"1000":{dayDetails:{},days:[]}}}
t = {albums:{"1000":{dayDetails:{love:true}}}}
v = _.merge(s,t)


console.log(v)


Object.prototype.xxoo = function(){}


s = {albums:{"1000":{dayDetails:{},days:[]}}}
t = {albums:{"1000":{dayDetails:{love:true}}}}
v = _.merge(s,t)


console.log(v)
```

jsbin demo: http://jsbin.com/fenama/edit?html,js,console

Screenshot:
![image](https://cloud.githubusercontent.com/assets/2993947/16139806/c849ee2e-347d-11e6-8a82-3a21e2c3adca.png)

The later loses the `days` field

**Comment by jdalton** [comment]
Hi @xieranmaya!

I'm glad v4 is working for ya :)

**Comment by xieranmaya** [comment]
@jdalton OK, then I'll upgrade~~
