### ISSUE TITLE
FR : Support for _.isEmpty on nested field

### ISSUE THREAD

**Issue by thatisuday** [lodash/lodash#2433]
As of now, **_.isEmpty** only works field who's parent exists.

For example
```
var test = {nested:{}};
_.isEmpty(test.nested.sub); // true (works as 'sub' has parent 'nested')
```

But for a field who's parent doesn't exist, for example
```
var test = {nested:{}};
_.isEmpty(test.nested.sub.deep);
```
Gives JavaScript error `Uncaught TypeError: Cannot read property 'deep' of undefined(…)` as **sub** is unknown to JavaScript .

If we could achieve this feature, it would be very useful.

**Comment by jfmengels** [comment]
```js
var test = {nested:{}};
_.isEmpty(test.nested.sub.deep);
// => Uncaught TypeError: Cannot read property 'deep' of undefined(…)
```

That is a normal JS error, nothing Lodash can do about.
You can use `_.get` though
```js
_.isEmpty(_.get(test, 'nested.sub')); // => _.isEmpty({}); => true
_.isEmpty(_.get(test, 'nested.sub.deep')); // => _.isEmpty(undefined); => true
```
