### ISSUE TITLE
How to orderby/sort a collection on a column ? 

### ISSUE THREAD

**Issue by monera23** [lodash/lodash#2434]
I have a collection projects that I want to order by according to the number of likes in desc order ? Any way to do it. I am using _.orderBy but it is not giving the correct output. This is the current code I am using. 

_.orderBy(proj_coll, [function (proj) {
                 proj.get('likes');
            }], ['asc']);

**Comment by jfmengels** [comment]
You are not returning anything in your iteratee function.
```js
_.orderBy(proj_coll, [function (proj) {
proj.get('likes');
}], ['asc']);
// -->
_.orderBy(proj_coll, [function (proj) {
  return proj.get('likes');
}], ['asc']);
```

For troubleshooting, feel free to hit up out [gitter chat](https://gitter.im/lodash/lodash) :)

**Comment by monera23** [comment]
Yes there is a return in it. Sorry for the typo
