### ISSUE TITLE
Allow path shorthand in `flow`

### ISSUE THREAD

**Issue by jfmengels** [lodash/lodash#2435]
When using `flow`, I often find myself having to add another step to use a certain property of an object, and end up with something like this (using `lodash/fp`)
```js
const takePlentyOfApples = _.flow(
  _.get('foo.items'),
  _.filter(_.overSome([
    {type: 'apple'},
    _.flow(
     _.property('count'),
     _.gt(_, 10)
    )
  ]))
);
```

What I'd like to propose, is to allow `flow` to use path shorthand notations, in order to be able to write the previous example like the following
```js
const takePlentyOfApples = _.flow(
   'foo.items',
  _.filter(_.overSome([
    {type: 'apple'},
    _.flow('count', _.gt(_, 10)))
  ]))
);
```

It would be nice if it supported both direct property access, nested property and array path access
```js
_.flow(
  'property',
  'nested.property',
  ['path', 0, 'access']
)
```

I became kind of envious when I saw this ability in Elm to create property functions really simply
```
> .name bill
"Gates"

> List.map .name [bill,bill,bill]
["Gates","Gates","Gates"]

// .name === _.property('name') in JS
```

**Comment by jdalton** [comment]
I'd like to avoid adding callback shorthand sugar to `flow` and friends for the time being but we'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by wtgtybhertgeghgtwtg** [comment]
May I ask why you would like to avoid adding callback shorthand sugar to `flow` and friends for the time being?

**Comment by jdalton** [comment]
Hi @wtgtybhertgeghgtwtg!

It complicates custom builds. I may remove shorthands in v5. I haven't made a decision yet though.

**Comment by FranzSkuffka** [comment]
@jfmengels the FP version is the remedy for all your struggles!
