### ISSUE TITLE
Feature request - add  "index" argument for the _.keyBy iteratee

### ISSUE THREAD

**Issue by vladimiry** [lodash/lodash#2439]
Current behavior is (https://lodash.com/docs#keyBy):
```
The iteratee is invoked with one argument: (value).
```

**Comment by vladimiry** [comment]
What I was trying to do (I don't want neither define any new variables not clone `keys` to do `keys.shift()`)
```
var keys = ['key1', 'key2'];
var values = [{name: 'o1'}, {name: 'o2'}];
var result = _.keyBy(values, (value, index) => keys[index]);
```
Anyway thanks for the response.

**Comment by septagram** [comment]
@jdalton Why?

What I'm trying to do is to change keys according to a rule, e.g.

	_.keyBy ({ camelCased, functionNames }, (action, key) => {
		return key.replace (/[A-Z]/, letter => '_'+letter).toUpperCase()
	})
