### ISSUE TITLE
Confused by `_.groupBy` behaviour after upgrading 3 - 4

### ISSUE THREAD

**Issue by alex-wilmer** [lodash/lodash#2445]
I have a collection of items that have the key `category`. When running:

    let result = _.groupBy(coll, 'category')

I get a result that looks something like this:

    {data_file: Array[23], index_file: Array[1], analysis: Array[9], biospecimen: Array[4] ... }

After upgrading to lodash 4 my result now looks like this:

    { false: [ 'c', 'a', 't', 'e', 'g', 'o', 'r', 'y' ] }

"lodash": "^3.10.1" -> "lodash": "^4.13.1"

**Comment by jfmengels** [comment]
Looks to me like you are using `lodash/fp` and not vanilla Lodash.
What I get using Lodash v4.13.1
```js
// lodash
_.groupBy([{category: 1, foo: 1}, {category: 1, foo: 2}, {category: 2, foo:3}], 'category')
// => { '1': [ { category: 1, foo: 1 }, { category: 1, foo: 2 } ],
  '2': [ { category: 2, foo: 3 } ] }

// lodash/fp
_.groupBy([{category: 1, foo: 1}, {category: 1, foo: 2}, {category: 2, foo:3}], 'category')
{ false: [ 'c', 'a', 't', 'e', 'g', 'o', 'r', 'y' ] }
```

In lodash/fp, the arg order is inversed, so you are actually grouping `"category"` by `coll`, wich doesn't make much sense here and returns you an odd result.

**Comment by alex-wilmer** [comment]
How do I check? I just did `npm install --save lodash`.

package.json: 

    "lodash": "^4.13.1",

in my file:

    import _ from 'lodash';

**Comment by jfmengels** [comment]
If you are indeed doing that, then you are doing it correctly.
```js
import _ from 'lodash'; // lodash, good
import _ from 'lodash/fp'; // lodash/fp, not what you expect
```
Hmm, not sure what is happening then.

**Comment by jdalton** [comment]
This looks like something that our [gitter chat](https://gitter.im/lodash/lodash) can help with.
