### ISSUE TITLE
[enhancement request] Lazy filter => slice chain

### ISSUE THREAD

**Issue by AnthonyAstige** [lodash/lodash#2446]
With the following code I would like the method `odd` to be called 3 times, but it's called 20 times.

```
var arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

_(arr)
  .filter(odd)
  .slice(0, 2)
  .value()
```

http://codepen.io/anthonyastige/pen/jryPxZ

More abstractly: If all chained methods before `slice` are pure (no side effects), cease execution once slice quota filled.

**Comment by jdalton** [comment]
Hi @AnthonyAstige!

Lazy filter already exists for `slice` but it must meet [the criteria](https://lodash.com/docs#_).

**Comment by AnthonyAstige** [comment]
@jdalton Ah got it, thanks!

From [the criteria](https://lodash.com/docs#_)
> Sections of a chain sequence qualify for shortcut fusion if the section is applied to an array of **at least 200 elements** and any iteratees accept only one argument

It would be nice if the heuristic was configurable.  I've updated my enhancement request to reflect.

**My use case**

Somewhat expensive filter method. 99%+ of calls expected to return the first 10 results of an about 100 item array. In very rare cases slice may not fill up so full execution may happen. It effects initial rendering of a page that's locked by this calculation, so deciseconds count, but if the occasional user has a slow response it would be okay.

**My workaround**

Optimized my filter method at the cost of code complexity
