### ISSUE TITLE
first() not working with lazy evaluation, head() does.

### ISSUE THREAD

**Issue by tvedtorama** [lodash/lodash#2447]
I wanted to verify that lazy evaluation works with "first()", and set up this test:

`let zz = _(_.range(240)).filter(x => { console.log(x); return x == 3 }).first()`

This did not work as expected, as all items were enumerated.

Then I tried this:

`let zz = _(_.range(240)).filter(x => { console.log(x); return x == 3 }).head() `

This works, only items up to the target is evaluated.  Seems first and head behaves differently in this respect?

Version (in package.json): ^4.13.1

People coming from LINQ will perhaps be tempted to use first(), missing the lazy performance boost.

**Comment by jdalton** [comment]
Thanks for the heads up :)
