### ISSUE TITLE
_.memoize causes v8 deopt

### ISSUE THREAD

**Issue by STRML** [lodash/lodash#2448]
Still tracing down why exactly this happens, but run the following script with the latest Lodash 4.x:

```js
var _ = require('lodash');

function foo(a, b, c) {
  return a * b * c;
}

function printStatus(fn) {
    switch(%GetOptimizationStatus(fn)) {
        case 1: console.log("Function is optimized"); break;
        case 2: console.log("Function is not optimized"); break;
        case 3: console.log("Function is always optimized"); break;
        case 4: console.log("Function is never optimized"); break;
        case 6: console.log("Function is maybe deoptimized"); break;
        case 7: console.log("Function is optimized by TurboFan"); break;
        default: console.log("Unknown optimization status"); break;
    }
}

var memoizedFoo = _.memoize(foo);

// Once to get it memoized,
memoizedFoo(1,2,3);
// 2 calls are needed to go from uninitialized -> pre-monomorphic -> monomorphic
memoizedFoo(1,2,3);
memoizedFoo(1,2,3);

%OptimizeFunctionOnNextCall(memoizedFoo);
memoizedFoo(1,2,3);

printStatus(memoizedFoo);
```

Run:

```
node --trace_opt --trace_deopt --allow-natives-syntax foo.js
```

The deopt:

```
[compiling method 0x243a0804ff59 <JS Function memoized (SharedFunctionInfo 0x1897f288ec99)> using Crankshaft]
[aborted optimizing 0x243a0804ff59 <JS Function memoized (SharedFunctionInfo 0x1897f288ec99)> because: Bad value context for arguments value]
[disabled optimization for 0x1897f288ec99 <SharedFunctionInfo memoized>, reason: Bad value context for arguments value]
```

**Comment by jdalton** [comment]
Hi @STRML!

I'm not too worried about that. The big win from memoization is avoiding heavy computation if a result has already been resolved. These minor optimizations can't compare with that.

**Comment by STRML** [comment]
Thanks for responding @jdalton. I'm seeing it actually take up a somewhat significant portion of my flame graphs in a section that I have been trying to speed up. I may spend a small amount of time on it to see if I can get the deopt out without breaking the method. If so I'll open up a PR.

**Comment by jdalton** [comment]
You can try removing the memoization and see if that helps. There is an overhead to memoization and your method may not benefit from it.

**Comment by STRML** [comment]
So this is a quite strange property of V8 and I am not sure if other engines have the issue. I thought I'd document it here for Googlabilty in any case.

The following patch fixes the deopt:

```
function memoize(func, resolver) {
  if (typeof func != 'function' || (resolver && typeof resolver != 'function')) {
    throw new TypeError(FUNC_ERROR_TEXT);
  }
  var memoized = function() {
    var args = arguments,
        key = resolver ? resolver.apply(this, args) : args[0],
        cache = memoized.cache;

    if (cache.has(key)) {
      return cache.get(key);
    }

+   args = new Array(arguments.length);
+   for (var i = 0; i < arguments.length; i++) {
+     args[i] = arguments[i];
+   }
+
    var result = func.apply(this, args);
    memoized.cache = cache.set(key, result);
    return result;
  };
  memoized.cache = new (memoize.Cache || MapCache);
  return memoized;
}
```

It appears that the special rule that makes `arguments` *not* cause deopt when using `Function.prototype.apply()` does not work if you sometimes bail out of the function early. Yeah, weird.

Microbenchmark results with 100,000,000 invocations of `memoizedFoo(1,2,3)`:

Without patch:

```
$ time node --allow-natives-syntax foo.js
Function is not optimized
        8.41 real         8.29 user         0.05 sys
```

With patch:

```
$ time node --allow-natives-syntax foo.js
Function is optimized
        4.15 real         4.09 user         0.03 sys
```

Not sure if this makes sense to include or not. Could be the kind of thing that is really implementation-specific and will hopefully be fixed in V8 later on.

**Comment by jridgewell** [comment]
> The following patch fixes the deopt:

That'll be very slow with a few more params. Try:

```js
function memoize(func, resolver) {
  if (typeof func != 'function' || (resolver && typeof resolver != 'function')) {
    throw new TypeError(FUNC_ERROR_TEXT);
  }
  var memoized = function() {
    var args = arguments,
        key = resolver ? resolver.apply(this, args) : args[0],
        cache = memoized.cache,
        result;

    if (cache.has(key)) {
      result = cache.get(key);
    } else {
      result = func.apply(this, args);
      memoized.cache = cache.set(key, result);
    }

    return result;
  };
  memoized.cache = new (memoize.Cache || MapCache);
  return memoized;
}

**Comment by STRML** [comment]
> That'll be very slow with a few more params. Try:

In my testing even with 10 params the performance is identical.

Unfortunately your code doesn't kill the deopt. Performance is actually a tiny bit worse (?) with the branch.

**Comment by jdalton** [comment]
There are places where optimizing this away makes sense and there are places where it doesn't and memoizing is a place where it doesn't fit. The cost of the function you're memoizing should outweigh the memoize scaffolding. If it doesn't then don't memoize it.
