### ISSUE TITLE
_.isArrayLikeObject(value)

### ISSUE THREAD

**Issue by thatisuday** [lodash/lodash#2450]
From version : 4.13.1
This method is like `_.isArrayLike` except that it also checks if value is an object.

So, does this method suppose returns true for object or false? Because `_.isArrayLikeObject({});` returns `false`.

**Comment by jdalton** [comment]
Hi @thatisuday!

It means
```js
_.isArrayLikeObject("hello");
// => false
_.isArrayLikeObject(document.body.children);
// => true
```
