### ISSUE TITLE
The download links are broken

### ISSUE THREAD

**Issue by eyal1990** [lodash/lodash#2451]
Both the "Core build" and the "Full build" download links are broken.
When you click on either of them you'll get **404: Not Found**

links: [core](https://raw.githubusercontent.com/lodash/lodash/4.14.0/dist/lodash.core.js), [full](https://raw.githubusercontent.com/lodash/lodash/4.14.0/dist/lodash.js)

**Comment by jdalton** [comment]
Yap, the links on the repo readme won't be valid until I add the tag.
