### ISSUE TITLE
Enhancement: _.typeof

### ISSUE THREAD

**Issue by kownacki** [lodash/lodash#2454]
Hi,

ECMAScript defines (currently) 7 so-called langage types in JS http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-types

Undefined, Null, Boolean, String, Symbol, Number, and Object

As everybody knows JS has operator `typeof` which is broken as it returns `"object"` for null. Also returns `"function"` for functions which is OK but I think it would be nice to have something which gives us one of the 7 language types for given value. It would be under `_.typeof` and it would suggest that it's the correct `typeof` that always returns language type.

Implementation would be dead simple:

```javascript
function(value) {
    if (_.isNull(value)) {
        return "null";
    }
    
    if (_.isFunction(value)) {
        return "object";
    }

    return typeof value;
}
```

Or something equivalent.

I've seen similar request but it's a little different: https://github.com/lodash/lodash/issues/1845
It makes sense but IMO should be under some other name like `_.class`.

**Comment by jdalton** [comment]
Hi @kownacki!

I'll defer to https://github.com/lodash/lodash/issues/1845#issuecomment-173225269.
