### ISSUE TITLE
Inconsistent _.get() Behavior With Ambiguous Keys

### ISSUE THREAD

**Issue by mhoc** [lodash/lodash#2455]
Tested with v4.13.1

I'm curious what lodash's documented behavior is when `_.get()` is given an ambiguous key on a potentially ambiguous object.

```
const obj1 = { a: { b: { c: 1 }, 'b.c': 2 }, 'a.b.c': 3 }
_.get(obj1, 'a.b.c') 
//=> 3
delete obj1['a.b.c']
obj1 
// => { a: { b: { c: 1 }, 'b.c': 2 } }
_.get(obj1, 'a.b.c') 
//=> 1
```

The behavior becomes most obvious when working with, say, Mongo statements.

```
const update = { $set: { 'profile.firstName': 'Bob' } };
_.get(update, '$set.profile.firstName')
//=> undefined
_.get(_.get(update, '$set'), 'profile.firstName');
//=> 'Bob'
```

Correct me if I'm wrong, but the behavior appears to be "if a root level key matches the query, return it. Otherwise, treat every period as a nested object and return the most deeply nested result of the query."

Would more consistent behavior be preferable? Like "always returns the least nested matching key"? Otherwise, would more complete documentation about this behavior be desirable?

Thanks!

**Comment by jfmengels** [comment]
> Would more consistent behavior be preferable? Like "always returns the least nested matching key"? 

Do you mean that the following should be correct?
```js
const obj1 = { a: { b: { c: 1 }, 'b.c': 2 }};
_.get(obj1, 'a.b.c') 
//=> 2
```

I agree that this would probably make more sense, so I would probably be in favor of changing. But in the case of ambiguous keys, you should use an array as the path anyway, which removes all ambiguity

```js
const obj1 = { a: { b: { c: 1 }, 'b.c': 2 }, 'a.b.c': 3 }
_.get(obj1, ['a.b.c']) 
//=> 3
_.get(obj1, ['a', 'b.c']) 
//=> 2
_.get(obj1, ['a', 'b', 'c'])
//=> 1

const obj2 = { a: { b: { c: 1 } }
_.get(obj2, ['a', 'b', 'c']) 
//=> undefined
```

**Comment by mhoc** [comment]
An array is definitely the right way to do it to avoid ambiguity. 

I think the current behavior is fine, but I feel it should receive a short bit of documentation to emphasize that the array param should be used to avoid ambiguity when dealing with objects containing periods in their key names. Something similar to:

> Gets the value at `path` of `object`. If the resolved value is `undefined`, the `defaultValue` is used in its place. _If `path` is a String, each period is treated as a path separator, with the exception of matching the entire `path` to a root value in the object if possible._

I'm actually not sure if there's a way to make the behavior more consistent without a potentially significant performance impact ¯\\\_(ツ)\_/¯
