### ISSUE TITLE
Live & Interactive code snippets for lodash

### ISSUE THREAD

**Issue by viebel** [lodash/lodash#2456]
It would be very cool and very helpful to underscore.js beginners to add live and interactive code snippets to [lodash documentation](https://lodash.com/docs), with the klipse plugin.

Here is a demo of the klipse plugin: http://blog.klipse.tech/javascript/2016/06/20/blog-javascript.html

Disclaimer: I'm the klipse author.

**Comment by jdalton** [comment]
Hi @viebel!

Thanks for the heads up. The lodash site is going through an overhaul and will be using [devtonic](https://tonicdev.com/) for its interactive snippet repl.

**Comment by viebel** [comment]
I understand.

Anyway, take a look at how neat would be the integration of klipse on https://lodash.com/docs.

![lodash](https://cloud.githubusercontent.com/assets/955710/16551157/5ebaba7c-41bd-11e6-8b1c-e25ef6295fb5.gif)


1. No server side at all
2. Code is evaluated as you type (the delay is configurable)
3. Minimalistic UI 
4. The `klipse` plugin is just  `javascript` + `CSS` files that you can host where you want.

What do you think?

- Yehonathan
