### ISSUE TITLE
Initial missing parameter for count

### ISSUE THREAD

**Issue by dangrie158** [lodash/lodash#2457]
Hi all,
in underscore there is the method initial which has an optional parameter **n** which makes it possible to remove the last n elements in an array. lodash currently does not have this parameter.

I think this would only make sense because initial without any parameter makes not so much sense to read. e.g.: `_.initial([2, 6, 3])` reads not as "everything but the last", however `_.chain(longArray).initial(5)` does IMHO read nicely as "the initial 5 elements"

**Comment by dangrie158** [comment]
I just found dropRight which does exactly this, however my main point is still the same.

Shouldn't initial and dropRight be aliases?

**Comment by jdalton** [comment]
Hi @dangrie158!

We try to avoid extraneous aliases.
