### ISSUE TITLE
Feature request: get all regex matches of a String

### ISSUE THREAD

**Issue by RodolpheGohard** [lodash/lodash#2459]
I want to get a simple array of all matches for a regex, and there is'nt any simple available way to have it:
http://stackoverflow.com/questions/6323417/how-do-i-retrieve-all-matches-for-a-regular-expression-in-javascript

I expected to see it in lodash, but couldn't find it. Here is how I imagine it

```javascript

const sourceText = "send your feedback to john.doe@example.com or person2@lodash.ru";
const emailRegex = /\S+@\S+\.\S+/;

_.findMatches(sourceText, emailRegex );
// returns  [ 'john.doe@example.com', 'person2@lodash.ru' ] 

```

**Comment by jdalton** [comment]
Thanks @RodolpheGohard!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by G07cha** [comment]
I met a similar problem but in your case, this could be resolved by using a native `sourceText.match` function. I had to write quite of code to get matches with their indexes like that: `{ '22': 'john.doe@example.com', '47': 'person2@lodash.ru' }` and lodash function that will return similar structure will be good for me.

**Comment by RodolpheGohard** [comment]
Yes, and there's also the case where you need capturing groups like:

```javascript
[{
   idx: 22,
   groups: ['john.doe@example.com','john.doe','example.com']
}]
```

I'm not sure what the best API would be here, but we need one for sure.

**Comment by RodolpheGohard** [comment]
Here is a sample implementation in es6:
```javascript
const getAllMatches = (source, regex) => {
	const matches = [];
	source.replace(regex, function() {
		matches.push({
			match: arguments[0],
			offset: arguments[arguments.length-2],
			groups: Array.prototype.slice.call(arguments, 1, -2)
		});
		return arguments[0];
	});
	return matches;
}
```

**Comment by mbukosky** [comment]
+1

**Comment by WillAvudim** [comment]
Here's one in typescript:

`export function* MatchAll(s: string, regex: RegExp): IterableIterator<string[]> {
  let each: RegExpExecArray | null
  while (each = regex.exec(s)) yield each
}
`
