### ISSUE TITLE
comparator for set/array functions (_.difference, _.union etc)

### ISSUE THREAD

**Issue by anodynos** [lodash/lodash#246]
I want to use these set functions, but with a different equals semantic than `===`, like `_.isEqual` or others.

There are many ways to do this, 2 sprang to mind:
- have an `_.setEquals` or smthng that registers an `isEquals`-like function that is then used for equals comparisons
- use alternative calling semantics, like `_.union([arr1, arr2], isEqualsFn)`

I m fine with both, but IMHO the 2nd could be more elegant...

**Comment by ilanbiala** [comment]
It would be much nicer to pass a comparator function to `_.difference`, `_.uniq`, and `_.union` because that is much cleaner for developers than overwriting _.indexOf.

**Comment by jdalton** [comment]
The matching of values is in `difference`, `includes`, `intersection`, `omit`, `pull`, `union`,  `uniq`,  `without`, & `xor`. I rather knock it out in 1 method than expand all of the existing and future ones. We provide the utils to take care of it in a line or two allowing devs to have their clean code.

**Comment by ilanbiala** [comment]
So why not make a base matching value function and have those functions inherit from that?

**Comment by jdalton** [comment]
> So why not make a base matching value function and have those functions inherit from that?

We have `_.indexOf` which all of those methods use. You change `_.indexOf` you change the matching behavior of all the other methods.

**Comment by ilanbiala** [comment]
@jdalton but who says I want to change the matching of every method, or I want to change it forever. Usually matching methods are case specific, so that means I would have to keep changing it every time instead of just passing in a function and making the code more readable.

**Comment by jdalton** [comment]
As I mentioned earlier you can use `_.runInContext` to create a pristine lodash instance, modify the the `_.indexOf` of it and use it's methods when you want that specialized behavior.

**Comment by ilanbiala** [comment]
@jdalton can you give an example of `_.runInContext` and `_.indexOf` modifying `_.difference` comparators?

**Comment by ilanbiala** [comment]
I can't find any documentation on modifying `_.indexOf`. @jdalton Can you provide an example?

**Comment by jdalton** [comment]
In a meeting. Will reply when done.

**Comment by jdalton** [comment]
```js
var lo = _.runInContext();
lo.indexOf = customIndexOf;

lo.difference(array, other); // => uses customIndexOf
_.difference(array, other); // => does not use customIndexOf
```

**Comment by bioball** [comment]
+1

Is the fear that this would be a breaking change? Or is it just that it will touch a lot of source code? Currently, all these functions that require comparisons aren't all that useful, and overwriting `indexOf` seems pretty hacky to me.

**Comment by ashneo76** [comment]
+1 overwriting _.indexOf seems hacky. I don't need to modify _ run's context. Also, since the matching of values is in all those methods, making a change there seems like a much better plan.

The real issue here seems to be not adding a feature in favor of a breaking change.

**Comment by jdalton** [comment]
If you want something customized you can always create a mixin. Lodash does it's equality comparison thing consistently across relevant methods. If you don't like it, implement you own method.

**Comment by jdalton** [comment]
I'm adding `_.uniqWith`, `_.differenceWith`, and friends to lodash v4 which accepts a `comparator` function.
```js
_.uniqWith(objects, _.isEqual);
```

**Comment by bioball** [comment]
Hooray!!

**Comment by StreetStrider** [comment]
Yeeeaa :tada:

**Comment by timorantalaiho** [comment]
@jdalton , any chance of getting a custom comparator option also for sort methods?

My use case is sorting with lodash _.sortBy with a natural comparator, such as http://stackoverflow.com/a/15479354

**Comment by trojanc** [comment]
Still no workaround for the above comment? I'd also like to use _.sortBy with a natural comparator.

**Comment by kamranayub** [comment]
@jdalton Did this fall by the way side? Was just looking for this 👍 Trying to do easy `without` using case-insensitive string comparer.

**Comment by jdalton** [comment]
@kamranayub Try [_.differenceWith](https://lodash.com/docs#differenceWith).

**Comment by kamranayub** [comment]
@jdalton Thanks, that's what I was looking for!

**Comment by peabnuts123** [comment]
Still looking for a way to do sortBy with a natural comparator
