### ISSUE TITLE
With lodash/fp, _.truncate becomes _.trunc

### ISSUE THREAD

**Issue by tansongyang** [lodash/lodash#2462]
When I include the following scripts:

```HTML
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.5.1/lodash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash-fp/0.10.4/lodash-fp.min.js"></script>
```

The function `_.truncate` is undefined, but `_.trunc` is defined and appears to do the same thing. I couldn't find any documentation for this anywhere. Is there a reason for this, and, if so, can it be documented somewhere?

Demo is [here](https://jsfiddle.net/ftan/afnt2jxk/).

Note that, in the fiddle, if you remove the script for `lodash-fp`, you'll get `_.truncate` defined and `_.trunc` undefined.

**Comment by jdalton** [comment]
The [lodash-fp](https://github.com/lodash-archive/lodash-fp) lib is discontinued in favor of [lodash/fp](https://github.com/lodash/lodash/wiki/FP-Guide) you should be using the builds from https://www.jsdelivr.com/projects/lodash.
