### ISSUE TITLE
_.isEqual quirky circular case

### ISSUE THREAD

**Issue by kownacki** [lodash/lodash#2463]
1.
```javascript
var a = {};
var b = {x: a};
a.x = a;
console.log(isEqual(a, b)); // true
```
2.
```javascript
var a = {};
var b = {x: {x: a}};
a.x = a;
console.log(isEqual(a, b)); // false
```

Can someone explain to me: Why the second one is false? Why both aren't false? Why both aren't true.

What are the rules for determining equality in such cases ?

**Comment by lluia** [comment]
1.
Comparing *a* `{x: a}` against *b* `{x: a}`. Apart from their names, both objects **a** and **b**, have the same _key/value_ pairs, which I guess is what `isEqual` compares.

2.
Here *a* is `{x: a}` and *b* is `{x: {x:a}}` so they have different  _key/value_ mappings so `isEqual` throws an error?

**Comment by jdalton** [comment]
In the first example they're both circular at the same property. In the second example they aren't.

**Comment by StreetStrider** [comment]
3.3(3) == 3.(3).
They are structurally equal :trollface: we can't compare them as true just because of language limitations.

**Comment by kownacki** [comment]
@StreetStrider I don't get your example. Did you used some kind of theory of connection between graphs and real numbers? Can you elaborate?

@jdalton How will you explain the example below?
```javascript
var a = {};
var b = {};
a.x = b;
b.x = a;
console.log(isEqual(a, b)); // true
```
And even this?
```javascript
var a = {x: {}};
var b = {x: {}};
a.x.y = b;
b.x.y = a;
console.log(isEqual(a, b)); // true
```

**Comment by StreetStrider** [comment]
@kownacki I mean that you are right. `isEqual` checks for structural equality and not referential, so in your first example we have two structurally equal recursive data objects and thus `isEqual` *should* treat them as equal. It should do so even if they have self-reference on *different levels*. This reminds me of repeating decimals, like 0.33(3) == 0.3(3) == 0.(3), which are in fact the same but represented slightly different.

**Comment by jdalton** [comment]
@kownacki It goes back to the [same explanation](https://github.com/lodash/lodash/issues/2463#issuecomment-230008104).

**Comment by kownacki** [comment]
@jdalton But `a` goes to `b` and `b` goes to `a`, but in my previous example they both went to `a`. It really puzzles me :) .

**Comment by jdalton** [comment]
It's simple all your examples had equiv circular references except for:
```js
var a = {};
var b = {x: {x: a}};
a.x = a;
console.log(isEqual(a, b)); // false
```

**Comment by kownacki** [comment]
@jdaltonWhat you mean by "equiv circular references".

It seems that equality by `_.isEqual` is not [transitive](https://en.wikipedia.org/wiki/Transitive_relation), which buggers me a bit.

```
var a = {};
a.x = a;
var b = {x: a};
var c = {x: b};

console.log(isEqual(a, b)); // true
console.log(isEqual(b, c)); // true
console.log(isEqual(a, c)); // false
```

Visualisation:
![wtf](https://cloud.githubusercontent.com/assets/16342517/16541382/4ec69f88-4081-11e6-9d2c-546408a80637.gif)

Was it intended? Can i have some negative effects on users?

**Comment by kownacki** [comment]
I think I found a bug. When we switch arguments `a` and `c` in above example we get different results!!

```javascript
console.log(isEqual(c, a)); // true
console.log(isEqual(a, c)); // false!!!!!!!!!!!!
```

**Comment by jdalton** [comment]
Sounds like you're on to something. Keep kicking it around.

**Comment by kownacki** [comment]
@jdalton I think that's it. [This](issuecomment-230111268) cannot be correct behaviour.

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash/commit/953c8e53121b19f77b26630732c44ea8eccf6bc8

**Comment by kownacki** [comment]
Thanks @jdalton . I even assured that this is true:

For every n>=0, all a are equal.  
![nice](https://cloud.githubusercontent.com/assets/16342517/16541763/c5be1b10-408c-11e6-8297-5f7c02ca4f82.gif)

**Comment by kownacki** [comment]
Thanks @jdalton . But it's still not fully transitive, and it can still lead to funny bugs.

```javascript
var a = {};
a.x = a;
var b = {x: a};
var c = {x: b};
var d = {x: c};

console.log(isEqual(a, b)); // true

console.log(isEqual(a, c)); // true <- that got fixed
console.log(isEqual(b, c)); // true

console.log(isEqual(a, d)); // true <- and that also got fixed
console.log(isEqual(b, d)); // false <- this is still wrong
console.log(isEqual(c, d)); // true
```

Visualisation:
![4 nodes](https://cloud.githubusercontent.com/assets/16342517/16541814/fe3e304a-408e-11e6-8135-44b9ab9ad1bb.gif)

---

Actually this should be true: *For every n>=0 all a's are equal* (if objects are connected like that)

![n nodes](https://cloud.githubusercontent.com/assets/16342517/16541827/56284ca0-408f-11e6-8197-ba095b2aa4c6.gif)

**Comment by jdalton** [comment]
I think that's pushing it as `b` is a object with a prop `x` that contains an object (`a`) with a prop `x` that has a circular reference. On the other hand `d` is an object that has a prop `x` that contains an object (`c`) with a prop `x` that contains an object (`b`) with a prop `x` that contains an object (`a`) with a prop `x` that has a circular reference.

Catching these requires going down the stack which hits recursive limits.
