### ISSUE TITLE
What about a nice lodash logo.?

### ISSUE THREAD

**Issue by ironmaniiith** [lodash/lodash#2466]
I was looking at the lodash documentation which is very well maintained, the only thing that I found missing was a cool lodash logo on the site. Thought of giving this suggestion to the community.

**Comment by demoneaux** [comment]
I’ve grown rather attached to the [current lodash logo](https://github.com/lodash). Also, the lodash site has undergone a [redesign](https://lodash.github.io/) to fit it better with the logo (although it’s still WIP).

**Comment by jdalton** [comment]
Yeah, part of the redesign was giving our logo a bit more visibility.
