### ISSUE TITLE
Documentation Request: Links for array mutation equivalent functions.

### ISSUE THREAD

**Issue by Y-Less** [lodash/lodash#2467]
The documentation for `_.remove` states:

> Note: Unlike `_.filter`, this method mutates array.

This is very handy, but the documentation for `_filter` has no equivalent statement.  If I know that I want the mutation version of a function, but don't know what it is, currently the only way I know to find it is to search for `_.filter` until I find a link like this back to it.  It would be very useful to have these equivalent functions linked both ways, including others like `_.without`/`_.pull`, `_.difference`/`_.pullAll` etc (I've not searched for a comprehensive list).

**Comment by jdalton** [comment]
@Y-Less would you be up for creating a PR for this? All you have to do is modify the jsdoc in the lodash.js file.

**Comment by Y-Less** [comment]
I can try, no guarantee it will be comprehensive.

**Comment by jdalton** [comment]
Moved to #2468.
