### ISSUE TITLE
_.set function modify to accept an overwrite argument

### ISSUE THREAD

**Issue by FISTUDIO-Dev** [lodash/lodash#2469]
Hi:
I am currently using Lodash in one of my projects and i found that with the set function currently does not support overwriting. For example, if I input `var obj = { '1' : '2' }`  and `_.set(obj,['1','2'],'3')` , i am expecting the '2' in the obj to be overwritten and and obj becomes `{'1':{'2':'3'}}` , but currently no changes are happening currently to the obj. 
So I propose this modification to this function, add a fifth arg called "overwrite' default to true. 
and change the function body to : 
`var index = -1,
          length = path.length,
          lastIndex = length - 1,
          nested = object;

      while (nested != null && ++index < length) {
        var key = toKey(path[index]);
        if (isObject(nested)) {
          var newValue = value;
          if (index != lastIndex) {
            var objValue = nested[key];
            newValue = customizer ? customizer(objValue, key, nested) : undefined;
            if (newValue === undefined) {
                newValue = objValue == null
                ? (isIndex(path[index + 1]) ? [] : {})
                : objValue;
            }
          }
          assignValue(nested, key, newValue);
        }
        if (overwrite){
          if (index != lastIndex) {
            nested[key] = isObject(nested[key]) ? nested[key] : {};
          }
        }
        nested = nested[key];
      }
      return object;`

**Comment by demoneaux** [comment]
You can use `_.setWith` which comes with a `customizer` function to configure how to set. See the [docs](https://lodash.com/docs#setWith) for more info and examples.

**Comment by FISTUDIO-Dev** [comment]
Hi:
It's true but for such a common action, requiring extra efforts to do seems unnatural.

**Comment by jdalton** [comment]
Hi @FISTUDIO-Dev!

This is an interesting case I'll have to think on it a bit. You could always `_.unset` before setting.
