### ISSUE TITLE
cloneDeep() does not copy an Array root key/value property

### ISSUE THREAD

**Issue by bartonsprings** [lodash/lodash#2472]
In a deep nested JSON, I am trying to cloneDeep() an object where there are some arrays of objects also present.

But my arrays also have root level key: value item present in addition to array items. Example:

Choices: [
selectedId : 34,
{object1},
{object2},
{object3},
...
]

On cloneDeep(), I do get all the original item cloned but not the root key/value - selectedId: 34
Manually doing this copies all the properties but not with lodash. Is this by design, I am using it incorrectly or a bug? I need the root properties in my arrays because I use the arrays also as objects in some cases.

Thanks!

**Comment by jdalton** [comment]
Hi @bartonsprings!

Lodash only clones index values (and some meta values) of arrays.
I'm not so sure your example is valid json though.

You can customize cloning with [_.cloneDeepWith](https://lodash.com/docs#cloneDeepWith).
