### ISSUE TITLE
How to use "bignumber" with "_.sumBy()"?

### ISSUE THREAD

**Issue by thearabbit** [lodash/lodash#2473]
I use `sumBy(.....)`, but the result show `123.219999999999999999........`.
So I would like to use with `BigNumber`.
Please help me.

**Comment by c-dante** [comment]
As far as I know, JS doesn't allow operation overloading.

Using `sum` or `sumBy` will [reduce using the `+` operator](https://github.com/lodash/lodash/blob/es/_baseSum.js#L18)

`sumBy` lets you transform values before they get `+`'d, but that won't work for your `bignumber` implementation.

Depending on how the library adds them, this is probably all you need to do (you can add it as a mixin if you want)

```js
const sumBigNums = (arr) => arr.reduce((a, b) => {
// Depending on BigNum implementation
return a.add(b);
// Or BigNum.add(a, b)
}, BigNum(0));

const myNums = [ BigNum(2/3), BigNum(1/16), BigNum(4/5) ];

sumBigNums(myNums);
```

**Comment by jdalton** [comment]
For questions like this you can also hit up our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by thearabbit** [comment]
Very thanks for your reply.
I will tried.
