### ISSUE TITLE
_clone/_cloneDeep incorrectly clones arrays with deleted elements

### ISSUE THREAD

**Issue by kownacki** [lodash/lodash#2476]
When cloning, values like length, properties should stay the same, which is not happening here.

```js
var x  = ["a", "b", "c"];

delete x[2];

// cloned/deepCloned x should have these parameters identical as original x
console.log(x); // [ 'a', 'b',  ] this is strange but that's how JS works
console.log(x.length); // 3
console.log(Object.keys(x)); // [ '0', '1' ]

var xDeepCloned = _.cloneDeep(x);

console.log(xDeepCloned); // [ 'a', 'b', undefined ] FAIL
console.log(xDeepCloned.length); // 3 OK
console.log(Object.keys(xDeepCloned)); // [ '0', '1', '2' ] FAIL

var xCloned = _.clone(x);

console.log(xCloned); // [ 'a', 'b', undefined ] FAIL
console.log(xCloned.length); // 3 OK
console.log(Object.keys(xCloned)); // [ '0', '1', '2' ] FAIL
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete#Deleting_array_elements

Please also handle both cases when non-last or last element of array was deleted.

**Comment by jdalton** [comment]
Hi @kownacki!

Thanks for digging in. I really appreciate it!

In this case this is intended. Lodash doesn't give special treatment for sparse arrays. It treats their missing entries as `undefined` literals.

**Comment by kownacki** [comment]
I understand. Then how about adding a short note about it to documentation?

**Comment by jdalton** [comment]
It's hit so few times it's not worth a doc block.

**Comment by kownacki** [comment]
OK. I understand we don't want a bloated documentation :)
