### ISSUE TITLE
Query about pull request

### ISSUE THREAD

**Issue by Y-Less** [lodash/lodash#2477]
Firstly, sorry for making this an issue - it is more of a question but I wasn't sure where else to put it.  There are three questions:

1) I made a few potential additions: `_.intersperse` and `_.mapMaybe`, both based on the haskell functions of the same names:

```javascript
function squareEven(v) { if (_.isEven(v)) return v * v; } // undefined (not falsy) return as "skip".
_.intersperse([0, 1, 2], 9) // => [0, 9, 1, 9, 2]
_.mapMaybe([0, 1, 2], squareEven) // => [0, 4]
```

I read the article on making issues to collect votes for feature requests.  Is it the same or a similar procedure for "unsolicited" new features with implementations and tests?  Do I just make a pull request, or first do something to gague desire for the feature?

2) I looked at making a pull request for these features, but that pull request seems to still include d30e41e, which was already integrated - I'm not sure why or how to stop it trying to resubmit that (I merged with the latest upstream version).

3) As the two new features are different, I put them in separate branches, with the intention to make them both separate pull requests.  However, this causes an issue with tests.  They both modify the `lodash methods` test module, increasing the number of expected "falsy" and "array return" tests by two.  Individually that is fine, but collectively that should be an increase of four.  Woudl it be better to combine them and submit all together?  Or do them very sequentially?

For reference, the changes I am talking about are here:

https://github.com/lodash/lodash/compare/master...Y-Less:Branch_intersperse?expand=1
https://github.com/lodash/lodash/compare/master...Y-Less:Branch_mapMaybe?expand=1

I tried twice to get a cleaner version of just my new changes on top of your upstream, but couldn't without just pulling a whole new one and manually inserting the changes.

**Comment by jdalton** [comment]
@Y-Less opening up an issue is best for feature requests. No need for PRs yet. You can sync your repo with Lodash by rebasing it:
```bash
git fetch https://github.com/lodash/lodash
git reset --hard b69a4ecca
git push origin +master
``` 
The hash after `--hard` can be whatever the latest commit hash for the lodash repo.
