### ISSUE TITLE
npm is behind

### ISSUE THREAD

**Issue by c-dante** [lodash/lodash#2478]
Don't know why but despite the npm branch at `4.14.0`, npm is stuck on `4.13.1`

https://www.npmjs.com/package/lodash

**Comment by jdalton** [comment]
There is no tag yet because I haven't published them. Related #2468, #2474.

**Comment by jdalton** [comment]
I hold off on tags until I'm totally ready because there are bots which detect the tag and auto-publish to cdns. Once published to a cdn they never revisit the tag which makes tagging something to be weary of until it's totally ready.

**Comment by c-dante** [comment]
No worries! Just was wondering since the branch was updated -- only assumed that it was in sync.

I wanted `fp/getOr` -- s'why I noticed :B
