### ISSUE TITLE
_.is

### ISSUE THREAD

**Issue by kownacki** [lodash/lodash#2479]
Hi,

Lodash has a lot of useful `_.is<something>` methods, although I sometimes need to create a predicate that will return true if argument is equal to my value. I can do it like this:

```js
var is5 = _.partial(_.eq, 5);
```

But why not have an even more convenient method: `_.is`

```js
var is5 = _.is(5);
```

And maybe if passing more values you can create an alternative:

```js
var is1or2or3 = _.is(1, 2, 3);
```

**Comment by StreetStrider** [comment]
@kownacki 
```js
var eq  = require('lodash/fp/eq')
var is5 = eq(5)
```

**Comment by kownacki** [comment]
Thanks, that's a nice solution.
