### ISSUE TITLE
Seperate rest into rest and baseRest

### ISSUE THREAD

**Issue by megawac** [lodash/lodash#2480]
Can `rest` be split into `rest` and `baseRest`. I want to avoid including all the `toInteger`  logic in asyncjs. Including `toInteger` ends up including:  `toFinite`, `toNumber`, `isSymbol`, `isFunction`, `isObject` and a bunch of primitives. This ends up being 1.26KB minified, 6.7 KB unminified.

I would be fine if this meant the start parameter was not optional for `baseRest`

**Comment by jdalton** [comment]
Sure, I'll look into that. If you used [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) it would take care of that for you.

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash/commit/ec4ae5978beef70660cdf95f41a2015625475391.
