### ISSUE TITLE
_.isEqual for sets doesn't work in PhantomJS

### ISSUE THREAD

**Issue by velveret** [lodash/lodash#2481]
I'm using es5-shim, es6-shim, and lodash 4.13.1, and the following outputs true instead of false in PhantomJS 2.1.1:
```
var initialSet = new Set();
var newSet = new Set(["test"]);
console.log(_.isEqual(initialSet, newSet));
```
After some digging, it looks like the problem is that `_.isEqual` uses the object tag. In Chrome, for instance, the tag for the set is [object Set], but in PhantomJS the tag is [object Object], so `_.isEqual` in PhantomJS doesn't go to the `equalByTag` method when comparing two sets.

**Comment by jdalton** [comment]
Since those aren't real `Sets` Lodash doesn't know how to handle them, they look like any other user made constructor.

**Comment by velveret** [comment]
I see, thanks!

**Comment by jdalton** [comment]
I may look into adding support for the shimmed forms by detecting their `_es6map` and `_es6set` properties.
