### ISSUE TITLE
_.foreach passing non-collection object

### ISSUE THREAD

**Issue by kownacki** [lodash/lodash#2487]
Hi,

What happens when we pass neither object nor array to `_.forEach`?

It seems it does nothing, just returning the value passed and not executing iteratee.

Can it be used when we have undefined instead of array under a variable and just use `_.forEach` instead of doing explicit cast to array?

```js
var x = undefined;
_.forEach(x, iteratee);
```

**Comment by jdalton** [comment]
> Can it be used when we have undefined instead of array under a variable and just use `_.forEach` instead of doing explicit cast to array?

Yes :)

**Comment by kownacki** [comment]
Thank you!
