### ISSUE TITLE
Feature request: Inverted slice function

### ISSUE THREAD

**Issue by G07cha** [lodash/lodash#2488]
I've got the case when I need to extract part of the string by a range of indexes and return the remaining part. There is a similar function [pull](https://lodash.com/docs#pull) but it works with array of indexes, not ranges.

Example:
```javascript
_.slice('test', 1, 2); // -> 'tst'
_.slice('test', 2); // -> 'te'
```

Will be happy to implement this if it's suitable for lodash and receive enough votes.

**Comment by jdalton** [comment]
Thanks @G07cha!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
