### ISSUE TITLE
wrong first call of customizer of _.isEqualWith 

### ISSUE THREAD

**Issue by Alexsey** [lodash/lodash#2490]
Consider code
```
var a = [1, 2, 3]
var b = [1, 2, 3]
_.isEqualWith(a, b, (av, bv, i) => {
  console.log(av, bv, i)
  if ([+av, +bv].every(_.isFinite))
    return true
})
```
will output
```
[1, 2, 3] [1, 2, 3] undefined
1 1 0
2 2 1
3 3 2
```
so the first time `customizer` function is invoking not with _`objValue, othValue`_ as it says in the docs, but with _`object, other`_.

This is really a problem if `customizer` knows how to compare specific types of values but not arrays

**Comment by jdalton** [comment]
This is by design to allow folks to customize the initial values provided. You can always return `undefined` to defer to the internal comparison.

**Comment by Alexsey** [comment]
Customize the initial values provided? Could you, please, provide an example of how it could be used?

Return on `undefined` on comparing of _`object`_ and _`other`_ is obviously a bad idea because if I'm writing my own customizer that is equivalent that default `isEqual` is not suiting the case

**Comment by Alexsey** [comment]
If you give some example of how you plane it to be used I could make a PR to docs

**Comment by Alexsey** [comment]
Oh, I can see now that `the method` in documentation doesn't mean 'isEqual`. Even in the example from doc the first iteration returns `undefined` on comparison of two different arrays and it doesn't stop the process. Any way it doesn't explain how it could be useful because if we naturally simplify
```
  if (isGreeting(objValue) && isGreeting(othValue)) {
    return true;
  }
```
to 
```
return isGreeting(objValue) && isGreeting(othValue)
```
it would become broken. So running first iteration with _`object`_ and _`other`_ seems like negative even from position of example in doc

**Comment by khullah** [comment]
Got the same issue. I'm trying to replace `isEqual` with a non-strict mode (`==`) but if fails because `array == array` is false, and the iteration stops

Even with the bad practice of "if (index===0) return true" to invalidate this behavior, it doesn't work because none of the other 4 arguments are passed to the function (the docs mention 6 arguments). All I get is 4 undefineds.

Please solve this.

**Comment by Alexsey** [comment]
@khullah I think the cleanest way to get over this bug is to wrap callback in to `_.after(1, ...)`. Of course, it would be nice if this one would be solved but even if there would be such planes - it's a breaking change and can be introduced only in new major version

**Comment by Alexsey** [comment]
@khullah I can't reopen this issue. Only jdalton can

**Comment by khullah** [comment]
great idea with the `_.after`, hadn't thought of that
Instead I did something really ugly and thought of turning into a mixin:

```
var isEqual = true;
_.each(g, function(value, prop){
    _.each(r, function(v, p){
        if (prop == p){
            isEqual = isEqual && (value == v)
        }
    })
})
```

**Comment by khullah** [comment]
Actually, I don't know how to use `after` after all (LoL).. could you give us a sample @Alexsey ?

**Comment by Alexsey** [comment]
Sorry, `_.after` is also a little confusing - it's first argument n means not "after n" but "on n" :) So to make it `==` code would look like
```js
const a = [1, '2', 3]
const b = [1, 2, '3']
console.log(_.isEqualWith(a, b, _.after(2, (av, bv) => av == bv))) // true
```
