### ISSUE TITLE
Lodash 4.13.1 "some" function does no work properly for plain array

### ISSUE THREAD

**Issue by Zvenigora** [lodash/lodash#2491]
Hi there,

I have just found that Lodash "some" function has a bug in case of array. As workaround I can use another Lodash function "indexOf" which works properly.

var arr=[1,2,3];
var exists = _.some(arr, 2);
alert(exists); // false, should be true

var exists = _.indexOf(arr, 2) >= 0;
alert(exists); // true, it's correct

Please take a look to the sample https://jsfiddle.net/wdo1gsvh/

With the best regards,

Mikhail Klygin

**Comment by jfmengels** [comment]
@Zvenigora `_.some` does not expect an integer, or in general an element to find, as its second argument.

You should either:
- Pass a function to `_.some`: `_.some(arr, function(elt) { return elt === 2; });
- Use `_.indexOf` as you showed
- Use `_.includes`, and **this** is probably what you were looking for in the first place ;)
