### ISSUE TITLE
Consider _.toggle function

### ISSUE THREAD

**Issue by jaketodaro** [lodash/lodash#2492]
This is not the same request as #1677. Consider a simple utility function to toggle a value between one of two possible values. This would be useful to replace the following ternary statement.

`foo = foo === a ? b : a;`

`foo = _.toggle(foo, a, b);`

Thanks.

**Comment by jdalton** [comment]
Thanks @jaketodaro!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by jaketodaro** [comment]
👍

**Comment by StreetStrider** [comment]
@jaketodaro it'll become more helpful if you swap arguments and make it auto-currying:
`toggle(L, R, value)`
```js
// init phase
var toggler = toggle('a', 'b')
var foo = 'a'

// usage in code
foo = toggler(foo)
```
