### ISSUE TITLE
orderBy of columns with mixed types

### ISSUE THREAD

**Issue by avin** [lodash/lodash#2494]
Hello guys! Can you tell how to use orderBy for objects with various field types. (strings and numbers)
For example
`_.orderBy([{a: 3}, {a: 2}, {a: 'a'}, {a: 1}, {a: 'c'}, {a: 'b'}], ['a'], ['asc'])`
I've got
`[{"a":2},{"a":3},{"a":"a"},{"a":1},{"a":"b"},{"a":"c"}]`
but how can I get something like
`[{"a":1},{"a":2},{"a":3},{"a":"a"},{"a":"b"},{"a":"c"}]`

**Comment by wyuLiang** [comment]
_.orderBy([{a: 3}, {a: 2}, {a: 'a'}, {a: 1}, {a: 'c'}, {a: 'b'}], ['a', 'asc'])

**Comment by jdalton** [comment]
Hi @avin!

Head over to your [gitter chat](https://gitter.im/lodash/lodash) for help.
