### ISSUE TITLE
lodash/fp proper import

### ISSUE THREAD

**Issue by Brakkar** [lodash/lodash#2496]
Hi,
in an es2015 node / typescript environment:

> import * as _ from 'lodash/fp'

Says it can't find the module.
And the require version looses all the typings.

So what's the proper way to use lodash/fp with proper import and typings ?

**Comment by jdalton** [comment]
Related to https://github.com/jashkenas/underscore/issues/2564.

**Comment by jdalton** [comment]
Hi @Brakkar!

Have you given [this definition](https://github.com/typed-typings/npm-lodash) a try?
If it's not covered there you might open an issue on that project to add support.

**Comment by jdalton** [comment]
You might also try our [gitter chat](https://gitter.im/lodash/lodash) for help.
