### ISSUE TITLE
_.defaultsDeeps doesn't override null

### ISSUE THREAD

**Issue by andreineculau** [lodash/lodash#2499]
Is it by design/choice that `_.defaultsDeep({a: {b: null}}, {a: {b: 'c'}})` will keep to `{a: {b: null}}` ?

If so, what would be the equivalent call to treat `null` as `undefined` in this context (deep object)?

**Comment by jdalton** [comment]
> Is it by design/choice that `_.defaultsDeep({a: {b: null}}, {a: {b: 'c'}})` will keep to `{a: {b: null}}` ?

Yes.

> If so, what would be the equivalent call to treat `null` as `undefined` in this context (deep object)?

You should check out [_.mergeWith](https://lodash.com/docs#mergeWith).


mergeWith

**Comment by abernier** [comment]
for reference: https://stackoverflow.com/a/50770949/133327

**Comment by DimaRGB** [comment]
how about this ?

```
import { mergeWith, isPlainObject, defaultTo } from 'lodash/fp';

const nilDefaultsDeep = mergeWith(
  (defaultObject, sourceObject) =>
    isPlainObject(defaultObject)
      ? nilDefaultsDeep(defaultObject, sourceObject)
      : defaultTo(defaultObject, sourceObject),
);
```
