### ISSUE TITLE
sortedIndexBy with comparator?

### ISSUE THREAD

**Issue by jedierikb** [lodash/lodash#2500]
I've an array sorted using a comparator
```array.sort( comparator )```

What is the suggested way to use that comparator with ```sortedIndexBy```?

**Comment by jdalton** [comment]
The `By` methods use an `iteratee` to transform values for use as the criteria to perform operations by. There is no `comparator` alternative of `sortedIndexBy`.

**Comment by StreetStrider** [comment]
@jedierikb comparator-methods suffixed with `With`.
