### ISSUE TITLE
_.filter does not work with []

### ISSUE THREAD

**Issue by gargleblaster** [lodash/lodash#2501]
After a painful debugging session, I've discovered that _.filter(arr, ['type', type]) fails where _.filter(arr, {'type: type}) succeeds.  I'm using 3.10.1.

```
var _ = require('lodash')
var arr = [{x:1, type:'abc'},{x:2, type:'abc'},{x:3, type:'def'},{x:4, type:'def'}]
console.log(_.filter(arr, ['type', 'abc']))
console.log(_.filter(arr, {'type': 'abc'}))
```
Output:
$ node lodashtest.js
[]
[ { x: 1, type: 'abc' }, { x: 2, type: 'abc' } ]

So, either I'm misunderstanding the docs, or something is broken.

**Comment by jdalton** [comment]
Yep, that shorthand, with the array syntax, is supported in v4.

**Comment by gargleblaster** [comment]
Got it.  Sorry.  :)
