### ISSUE TITLE
_.setDefault(object, path, toSet)

### ISSUE THREAD

**Issue by RealAdamSinger** [lodash/lodash#2506]
this would be a lot like `_.get`, but if the object path returns `undefined` the `defaultValue` would be set on the object path and then returned. 

The code would look a lot like this
```
_.setDefault = function(object, path, toSet){
    return _.get(object, path, _.set(object, path, toSet));
};
```
this would be great for when you want to share references of objects or classes at a particular path but create new instances if it does not yet exist.

Usage 
``` Javascript
var SomeClass = FrameworkClass.extend(<someObject>);
var x = {}
_.setDefault(x, 'y.z', new SomeClass())
// → <newClass>
// x = { y: { z: <newClass>}}

var x = { y: { z: oldClass}}
_.setDefault(x, 'y.z', new SomeClass())
// → <oldClass>
//var x = { y: { z: <oldClass>}}
```

deciding on the name came from google searching and discovering python has this function

**Comment by jdalton** [comment]
Thanks @RealAdamSinger!

I can dig the functionality, but the name would need to be different.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by RealAdamSinger** [comment]
Cool, no problem.

I settled on the name based on [a function found in python's docs](https://docs.python.org/3/library/stdtypes.html#dict.setdefault)

i was considering other names such as `_.getSet` or `_.exist` but couldnt settle on anything. That's all I have for suggestions at the moment!

**Comment by staticshock** [comment]
A reasonable alternative that handles the shallow path use case is [`_.defaults`](https://lodash.com/docs#defaults):

```javascript
_.defaults({ 'foo': 1 }, { 'foo': 2 })
>> { foo: 1 }
```

There's also a `_.defaultsDeep`, though the syntax might be slightly less nice than a path string.

**Comment by jgalvan2** [comment]
Working pretty well for me:
```
  _.mixin 'setDefault': (object, path, d) ->
    value = _.get(object, path)
    if _.isUndefined(value)
      _.set(object, path, d)
    _.get(object, path)
```

**Comment by SeregPie** [comment]
@jgalvan2 
This is 'too slow', because you walk through the path 3 times. But it is possible to implement it in a way, so it walks once.

**Comment by jfmengels** [comment]
This sounds to me like something really close to what [update()](https://lodash.com/docs/4.17.2#update) does. I'm not necessarily against adding this, but know that `update()` does almost exactly what you want.

```js
_.update(object, path, value => value === undefined ? newValue : value);
```

**Comment by pingvinen** [comment]
This sounds like something that I was going to propose :) My name for it is `_.ensure(object, path, defaultValue)`.

My use-case is an object representing a document being passed around. Some places need to add stuff to the same array (in this case), but none can be certain that the array already exists. Currently I am using the following "implementation":

```
const must = _.get(modifiedQuery, 'body.query.bool.must', []);
_.set(modifiedQuery, 'body.query.bool.must', must);
```

Despite being able to achieve this with `_.update` I would think that wrapping this behavior with a good name would be nice, as it makes the consuming code more readable/semantic.

**Comment by deinspanjer** [comment]
I was searching for something like getOrSetDefault that would return the value if it has been previously computed, otherwise, compute, store, and return the value.
_.update is close, but it returns object rather than value, so you have to wrap that in a _.get(_.update()) which requires two path traversals.
Is there a better way to do this?

**Comment by cdhowie** [comment]
What about this?  It only traverses the path once.  Unlike `_.update()`, it returns the value at that path (after any assignment) rather than the original object.

```js
_.mixin({
    ensure(object, path, defaultValue) {
        let value;
        _.update(object, path, existing =>
            value = _.isUndefined(existing) ? defaultValue : existing
        );
        return value;
    }
});
```
