### ISSUE TITLE
fp/debounce does not accept options argument

### ISSUE THREAD

**Issue by willmcclellan** [lodash/lodash#2508]
I'm not sure what the behaviour should be here, but it's currently not possible to supply debounce with the `options` object in a functional way. [The FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide) state it has a fixed arity of 2.

```
// does work
debounce(timeout)(function)

// does not work
debounce(timeout)(options)(function)
```

**Comment by jdalton** [comment]
That is correct and by design. We do add variadic variants upon request though.
Do you have a preferred name?

**Comment by willmcclellan** [comment]
Yeh makes sense.. is there any existing conventions used previously? 'debounceOn' seems a good fit to accommodate any of the options:

debounceOn.. leading
debounceOn.. trailing
debounceOn.. maxWait

or 2 additional variants of 'debounceLeading` & `debounceTrailing` as it probably doesn't make sense to have those options both enabled?

**Comment by jdalton** [comment]
Oh I meant just for the options bit. Maybe `debounceOpts`?

**Comment by willmcclellan** [comment]
Ah right.. Do you mean a separate debounce function that accepts the 3 arguments for opts instead of 2? If so `debounceOpts` works for me.

**Comment by c-dante** [comment]
```
fp.debounceOpts(options, wait, fn)

const debounceLeadTrail = fp.debounceOpts({ leading: true, trailing: true });
debounceLeadTrail(500, () => console.log('Neat'));
```

I'm into it.

**Comment by willmcclellan** [comment]
Just wondering if there's been any movement on this? It keeps cropping in our projects and we keep having to fallback to vanilla debounce so would be nice to see this get added

**Comment by keenahn** [comment]
Hello all, here's what I'm using for now, with a quick example for `{ leading: true }`

```js
const {
  curry,
  debounce,
} = require('lodash/fp')

const debounceNotFixed = debounce.convert({ fixed: false })
const debounceLeading = curry((wait, fn) => debounceNotFixed(wait)(fn, { leading: true }))

const a = debounceLeading(1000)(() => console.log('hi'))

a() // => 'hi'
a() // nothing
a() // => 'hi' after 1000ms

```js

**Comment by arian-woopra** [comment]
wouldn't it be better if it worked like so:
debounce(wait, options?)(fn);

**Comment by Nivani** [comment]
Or maybe like so:
`debounce(wait | options)(fn);`

That way, we keep the fixed arity of 2:
```javascript
const debounce = require('lodash/fp/debounce');

const a = debounce(1000)(() => console.log('still works, just like before'));
const b = debounce({ wait: 1000, leading: true })(() => console.log('also works with options object'))

// ...
```
