### ISSUE TITLE
Consider a _.equalIgnoringIndex function to do collection/set equality ignoring elements position

### ISSUE THREAD

**Issue by sarod** [lodash/lodash#2509]
It is often useful to check if a collection contain the same elements ignoring their position if the collection is supposed to represent a set of value.

However there is no easy way to do that even when using ES6 Set there is no easy way to compare two sets for elements equality as `new Set([1, 2, 3]) == new Set([1, 3, 2])` yields `false`.

Currently using lodash one can write things like `_.isEmpty(_.xor(array1, array2))` or `_.isEmpty(_.difference(array1, array2)) && _.isEmpty(_.difference(array2, array1))`.

However having a dedicated method would make code more readable and would reveal the intent better.

A simple implementation could be the following
```javascript
function equalIgnoringIndex(collection1, collection2) {
  return _.every(collection1, function(element) { return _.includes(collection2, element) }) 
      && _.every(collection2, function(element) { return _.includes(collection1, element) });
}
```

**Comment by jdalton** [comment]
Thanks @sarod!

> However there is no easy way to do that even when using ES6 Set there is no easy way to compare two sets for elements equality as `new Set([1, 2, 3]) == new Set([1, 3, 2])` yields `false`.

Lodash supports comparing sets:
```js
_.isEqual(new Set([1, 2, 3]), new Set([1, 3, 2]));
// => true
```

> However having a dedicated method would make code more readable and would reveal the intent better.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
