### ISSUE TITLE
sortedIndexBy for reverse sorted strings?

### ISSUE THREAD

**Issue by jedierikb** [lodash/lodash#2510]
I've an array of reverse sorted strings `["AAZ", "AAY", "AAA"]`

How would I use sortedIndexBy to find the correct index?  It seems this function assumes a forward sorted array?   Currently I am calling `reverse`, then `sortedIndexBy`, `splice`, and then `reverse` again.

Some (incomplete) attempts at solving this with help of others on stackoverflow:
http://stackoverflow.com/questions/38448568/sortedindex-for-reverse-sorted-array/

**Comment by jdalton** [comment]
Hi @jedierikb 

For these kinds of questions you can hit up our [gitter chat](https://gitter.im/lodash/lodash).
