### ISSUE TITLE
Feature suggestion: function to remove diacritics

### ISSUE THREAD

**Issue by jrencz** [lodash/lodash#2511]
I suggest there should be a function that does a bit more than `_.deburr` - it should replace all non latin1 characters with their latin1 counterparts (ą -> a) and remove those that have no counterpart at all.

There are characters in latin1 other than supplementary characters which _.deburr handles, what may be required to be removed in certain use cases.

My use case: latin1 extended, diacritic characters in Polish language. I wish to reliably compare names on credit cards, which have no diacritics, and names defined by users, which may have diacritics.

I mean something between `_.deburr` as it is now and [FGRibreau/node-unidecode](https://github.com/FGRibreau/node-unidecode) which is an overkill, especially for front-end use cases.

#1430 may be related.

**Comment by jdalton** [comment]
Thanks @jrencz!

Like #1430, we'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
Until then you can always make a mixin to extend support.

**Comment by jrencz** [comment]
@jdalton got it.

BTW: when you count the popularity do you consider duplicates as votes or should I vote #1430 is I'm willing to support that idea?

**Comment by jdalton** [comment]
I think this is a bit different than #1430 (which is why I removed the dup tag).

**Comment by ashclarke** [comment]
I've also recently come across a need for characters such as `č` and `ů` to be deburred.

**Comment by jdalton** [comment]
Just to confirm @jrencz the  diacritic characters in Polish language are covered by latin1 extended?

**Comment by jrencz** [comment]
@jdalton most of them are not

- Ą U+0104
- ą U+0105 
- Ć U+010A
- ć U+010B
- Ę U+0118
- ę U+0119
- Ł U+0141
- ł U+0142
- Ń U+0143
- ń U+0144
- Ś U+015A
- ś U+015B
- Ź U+0179
- ź U+017A
- Ż U+017B
- ż U+017C

are not in latin-1

- Ó U+00D3
- ó U+00F3 

are.

**Comment by jdalton** [comment]
Cool. I think adding extended-A is reasonable and doable. I'll look into it this evening.
