### ISSUE TITLE
curryRight after curry seems return wrong wrapper

### ISSUE THREAD

**Issue by TylerYang** [lodash/lodash#2514]
Hi folks, seems `curryRight` the wrapper which generate by `curry` method didn't work as expected. 

```javascript
function test (a, b, c) {
    return [a, b, c];
}
var curried = _.curry(test)(1);
console.log(curried(2)(3));         //[1, 2, 3]
var recurried = _.curryRight(curried)(3);
console.log(recurried(2)); // [1 3 2]  should be [1, 2, 3] ?
```
Am I missing something?  Would appreciate if anyone could help. Thx...

**Comment by Archimidis** [comment]
The _curried_ function accepts 2 arguments given which are the _b_ and _c_ from the _test_ function.
So currying right the _curried_ function will 1st set the _c_ parameter and then _b_.
So you have the [1, 3, 2] you see in the log.

**Comment by TylerYang** [comment]
@Archimidis  Shouldn't it be [1, 2, 3] ?
If we compare these two examples below,

#### example A
```javascript
function test (a, b, c) {
    return [a, b, c];
}
var curried = _.curry(test)(1);
var recurried = _.curryRight(curried)(3);     
console.log(recurried(2)); // [1 3 2]  should be [1, 2, 3] ?
```

####  example B
```javascript
function test(b, c) { return [b, c]; }
_.curryRight(test)(2)(3)
[3, 2]
```

In example A  I pass 3 before 2, so the `curryRight` would pass the 3 to the last arguments `c`.  Then I invoke the `recurried` function with argument `2`.  The result should be `[1, 2, 3]` not `[1, 3, 2]`. (Just like the result of **example B**)

**Comment by jdalton** [comment]
@TylerYang 

You'll need to specify the expected arity because once curried the `length` hint isn't available.
```js
var recurried = _.curryRight(curried, 2)(3);
console.log(recurried(2)); // [1, 2, 3]
```

**Comment by TylerYang** [comment]
@jdalton  That's what I want. I should look into the document first.  Thx for your help...
