### ISSUE TITLE
Support ECMAScript 6 typed arrays

### ISSUE THREAD

**Issue by max0x7ba** [lodash/lodash#2515]
I have tried `_.flatMap` with `UintArray32[]` and it does not seem to work:

![lodash-and-typed-arrays](https://cloud.githubusercontent.com/assets/765202/17017460/4e1524ac-4f2b-11e6-947a-a82db098913f.png)

**Comment by jdalton** [comment]
Hi @max0x7ba!

Our `flatten` methods are for arrays only.
I'm not inclined to support typed arrays unless it makes it's way into the ECMAScript specification.

**Comment by max0x7ba** [comment]
Is it not in ECMAScript specification already? http://www.ecma-international.org/ecma-262/6.0/#sec-typedarray-objects

**Comment by jdalton** [comment]
I'm talking about `flatten` and `flatMap`. See https://bterlson.github.io/proposal-flatMap/.

**Comment by max0x7ba** [comment]
Typed arrays' elements are scalars. In other words, the typed arrays are already "flat". `flatten` method of a typed array would return the original array, would it not?

**Comment by jdalton** [comment]
I don't believe out of the box the `Array#flatten` and `Array#flatMap` proposals will flatten arrays containing typed arrays.

**Comment by jdalton** [comment]
I added support for flatten methods to honor the `Symbol.isConcatSpreadable` symbol https://github.com/lodash/lodash/commit/0f6247ff6d001d4021ca38da2ddc222d714d7f70.
