### ISSUE TITLE
Feature request: toRange(...) - Casts/maps a number from one range to another

### ISSUE THREAD

**Issue by alexanderwallin** [lodash/lodash#2517]
I searched the grounds here but couldn't find a similar request.

`toRange(...)` is for casting a number from one range to another. I've bumped into this method mainly while working with audio/music and 3D graphics, and I've found it very useful.

Proposed syntax is `toRange(number, fromLower, fromUpper, toLower, toUpper)`.

Here are some example uses:

* Casting periodic values to a positive range: `const height = _.toRange(Math.sin(x), -1, 1, 0, window.innerHeight)`
* Translate the mouse's position into a color parameter: `const hueShift = _.toRange(mouseX, 0, window.innerWidth, -10, 10)`
* Setting a boosting `GainNode`'s gain value from an `<input type="range" min="1" max="10" />`: `boostGain.value = _.toRange(input.value, input.min, input.max, 1, MAX_GAIN)`

I think it would be quite handy functional style:

```js
import { toRange, mean } from 'lodash/fp'

const toWidth = toRange(0, window.innerWidth)
const sinToWidth = toWidth(-1, 1)
const numKeyToWidth = toWidth(48, 57)

const toReviewScore = toRange(1, 6)
const avgThumbsUpDownToScore = toReviewScore(-1, 1)
const movieScore = avgThumbsUpDownToScore(mean(thumbsUpDown))
```

Example implementations:

* http://stackoverflow.com/questions/10756313/javascript-jquery-map-a-range-of-numbers-to-another-range-of-numbers#23202637
* http://rosettacode.org/wiki/Map_range#JavaScript

I am unsure how nisched a problem this is, so it would be interesting to hear thoughts on this!

**Comment by demoneaux** [comment]
This seems like a pretty specific problem. There’s already another library out there which can map numbers from one range to another: https://github.com/d3/d3-scale.

**Comment by jdalton** [comment]
Hi @alexanderwallin!

I agree with @demoneaux on this but we'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by JamieDixon** [comment]
I've been looking to replace our custom implementation of this same function recently. We realise it's only a small function but finding a place for shared code is often more hassle than we want.

Would be very grateful for an lodash implementation of this.

**Comment by stevenpetryk** [comment]
I was also looking for this, but I understand lodash will likely never add it. For those wanting this:

```js
function mapRange(number, fromLeft, fromRight, toLeft, toRight) {
  return toLeft + (number - fromLeft) / (fromRight - fromLeft) * (toRight - toLeft)
}
```
