### ISSUE TITLE
map, weakmap, set, weakset support?

### ISSUE THREAD

**Issue by rickmed** [lodash/lodash#2518]
:)

**Comment by a-x-** [comment]
why is it invalid?

E.g. `_.mapValues(new Map([['a',1]]), v=>v*v)` and another methods are not working
And it'll be cool to support them.

**Comment by a-x-** [comment]
I have an issue with unordered Objects and i have to use Maps
But i cannot, because lodash does not support it.

**Comment by jdalton** [comment]
@a-x- You can use spread:
```js
_.mapValues([...map], ({1:v})=>v*v)
```

**Comment by a-x-** [comment]
but it'll convert my ordered Map into unordered Object and it'll not solve my problem

**Comment by jdalton** [comment]
`[...map]` spreads map as an array of key-value entries. From there you can perform any transform you wish and convert back to a map with `new Map(entries)`

**Comment by a-x-** [comment]
Ok, thank you!

but i does not work in latest chrome still and in simple projects (w/o build process) it's not appliceble

**Comment by jdalton** [comment]
If you're using Map and Set and targetting older environments then you should also be using babel to transpile.

**Comment by damianobarbati** [comment]
@jdalton it would be nice to support the `Map` object since sometimes you need to use it to preserve keys insertion order in object for further loops.

```
{ map(values, (value, key) => (
  ok for plain objects but breaks with maps returning empty array 
)) }
```
