### ISSUE TITLE
Add a `test` function like ramda for fp code

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash#2519]
Test makes it easier to deal with regexes when writing code in the fp style.

Here's a link to ramda's docs: http://ramdajs.com/0.21.0/docs/#test

Personally I have a function like this defined in my source `test = x => y => x.test(y)` (which can even be generalized further to a thing like `z => x => y => x[z](y)` but that's perhaps a bit obtuse), but it'd be great for this to live in lodash-fp for it to be a better ramda alternative (which I believe it generally is).

**Comment by megawac** [comment]
I'd rather see something like [R.invoker](http://ramdajs.com/0.21.0/docs/#invoker) which would let you do

```js
let testFn = invoker(regex, 'test')
testFn(string)
```

Then again we can easily define this invoker method:

```js
const invoker = _.curry(_.invoke, 3)
```

**Comment by jdalton** [comment]
We have `fp.invokeArgs` which is `fp.invokeArgs(methodNameOnThing, args, thing)`
