### ISSUE TITLE
Feature request: add Ruby's `each_cons` and `each_slice` methods

### ISSUE THREAD

**Issue by utkarshkukreti** [lodash/lodash#252]
It would be nice to have the equivalent of `each_cons` and `each_slice` methods Ruby's [Enumerable](http://ruby-doc.org/core-2.0/Enumerable.html) module has.

Something like:

```
_.eachCons([1, 2, 3, 4], 2) => [[1, 2], [2, 3], [3, 4]]

_.eachCons([1, 2, 3, 4], 3) => [[1, 2, 3], [2, 3, 4]]

_.eachSlice([1, 2, 3, 4], 2) => [[1, 2], [3, 4]]

_.eachSlice([1, 2, 3, 4], 3) => [[1, 2, 3], [4]]
```

and probably also accept a callback as second param like many existing functions do.

Let me know if you'd like this to be in lodash, I would try to send in a pull request if I can.

**Comment by hugoferreira** [comment]
I know this is an old request, but I would really like to understand the rationale behind these rejections. I mean, almost everything in this library is a `fold` (or `reduce`) special case. And `chunk` is nothing but *this*, with a stride equal to its length. How's this (and underscore's) request any different from having `chunk`?

**Comment by KurtRMueller** [comment]
This would have been nice to have in this package!

**Comment by KurtRMueller** [comment]
Just as an FYI to anybody else searching for functionality similar to Ruby's `eachCons`, Ramda has this functionality named as [aperture](https://ramdajs.com/docs/#aperture).

**Comment by windmaomao** [comment]
in `Kotlin`, i believe this is called `windowed(n)`. Maybe a quick way to do this without a new function is to drop one element first and use the rest to go through the index.

**Comment by vincerubinetti** [comment]
https://stackoverflow.com/a/48541301/2180570

```ts
const zipAdjacent = function<T> (ts: T[]): [T, T][] {
  return zip(dropRight(ts, 1), tail(ts));
};
```

by [Oliver Joseph Ash](https://stackoverflow.com/users/5932012/oliver-joseph-ash)

---

https://stackoverflow.com/a/67602261/2180570

```ts
const pairWise = a => a.slice(1).map((k,i) => [a[i], k]);
```

by [loop](https://stackoverflow.com/users/3070613/loop)
loop
