### ISSUE TITLE
Random does not produce floats or does not randomize?

### ISSUE THREAD

**Issue by sebastiaanluca** [lodash/lodash#2520]
For example:
``` js
let arr = [];
for (var i = 0; i < 100; ++ i) {
    arr.push(_.random(1.2, 5.2));
}
console.log(arr);
```

Outputs:
```
Array [ 3.2, 2.2, 4.2, 1.2, 3.2, 1.2, 5.2, 3.2, 2.2, 4.2, 90 more… ]
```

So the decimal number is not random at all. 

- `_.random(1, 100.99)` returns only integers.
- `_.random(1.20, 100.99)` returns random floats with `.2` as decimal

Am I perhaps missing something?

**Comment by jdalton** [comment]
I can't repro this from master branch.

**Comment by craigmichaelmartin** [comment]
FYI, I'm seeing this in underscore, not lodash.
