### ISSUE TITLE
_.merge doesn't overwrite destination collection with empty source collection

### ISSUE THREAD

**Issue by yefim** [lodash/lodash#2521]
```` javascript
_.merge({'foo': ['bar']}, {'foo': []})
// Expected: {'foo': []}
// Actual: {'foo': ['bar']}
_.merge({'foo': {'hello': 'world'}}, {'foo': {}})
// Expected: {'foo': {}}
// Actual: {'foo': {'hello': 'world'}}
````

I started looking into this and it looks like the `arrayEach` in `baseMerge` is the culprit. Something like `if (isEmpty(props || source)) { ... }` will probably solve this.

**Comment by jdalton** [comment]
This is the intended behavior. You can customize with [_.mergeWith](https://lodash.com/docs#mergeWith).
