### ISSUE TITLE
Document breaking change to `_.debounce` in 4.11.1

### ISSUE THREAD

**Issue by islemaster** [lodash/lodash#2524]
Hi there!  While upgrading code-dot-org from lodash 3.10.0 to 4.13.1 I ran across a change to `_.debounce` in [4.11.1](https://github.com/lodash/lodash/wiki/Changelog#v4111) that broke [some of our tests](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/test/unit/netsim/NetSimTable.js#L568):

> Ensured `_.debounce` doesn’t immediately call `func` when `wait` is `0`

To elaborate, `_.debounce(func, 0)` now behaves like `setTimeout(func, 0)`.

```javascript
let func = sinon.spy();

// Under 4.11.0
_.debounce(func, 0)();
expect(spy.callCount).to.equal(1);

// Under 4.11.1
_.debounce(func, 0)();
expect(spy.callCount).to.equal(0);
setTimeout(() => {
  expect(spy.callCount).to.equal(1);
}, 0);
```

It's entirely possible that this means my tests are badly written; we definitely _should_ be using `lolex` for this stuff, but there [are still problems with getting `lodash` to use the replaced window.Date object in tests](https://github.com/sinonjs/sinon/issues/343#issuecomment-233666906).  So instead, I've turned my debounce/throttle waits down to zero and let most of my tests run serially.  After this change, I had to add additional `setTimeout(_, 0)` calls to my tests.

I'm not entirely opposed to this change, but I was irritated that a patch version broke our tests, and that neither the details of this particular behavior nor the behavior change at 4.11.1 [have been documented](https://github.com/lodash/lodash/blob/master/doc/README.md#_debouncefunc-wait0-options-optionsleadingfalse-optionsmaxwait-optionstrailingtrue).  I'm opening this issue to get a discussion going around why this change was made in a patch version, whether it's really the ideal behavior for `_.debounce`, and to get the documentation updated to describe the spec'd behavior of `_.debounce` when `wait` is zero.

Tagging @jdalton and @b3nj4m who introduced the 'breaking' change.

Thanks! -Brad

**Comment by jdalton** [comment]
Thanks @islemaster!

I considered this a bug fix, so by design.

**Comment by islemaster** [comment]
Cool. I'm all for keeping the new behavior, and I understand it's not a "breaking" change since the documented API doesn't say anything about the behavior of `_.debounce(_, 0)`.  It still seems like this edge case is worth calling out in the documentation, especially since 0 is the default value for `wait`.  Would you be open to a pull request updating the `_.debounce` docs?

**Comment by islemaster** [comment]
Something like this: #2530
