### ISSUE TITLE
isEqual and invalid dates

### ISSUE THREAD

**Issue by phated** [lodash/lodash#2532]
In the latest release, the behavior of `isEqual` on invalid dates has changed.  Previously: `isEqual(new Date(undefined), new Date(undefined)) === false` but now it is `true`.  This was a breaking change to the gulp test suite.

**Comment by jdalton** [comment]
Related to https://github.com/gulpjs/vinyl-fs/blob/master/lib/file-operations.js#L54-L82.

**Comment by jdalton** [comment]
Yeah, invalid dates will coerce to `NaN` and it made sense to track them as equiv.
Related to https://github.com/moment/moment/issues/3156.

A solution could be to change:
```js
var fsTimes = { 'mtime': fsStat.mtime, 'atime': fsStat.atime };
var vlTimes = { 'mtime': vinylStat.mtime, 'atime': vinylStat.atime };

if (isFinite(vlTimes.mtime) &&
    isFinite(vlTimes.atime) && isEqual(vlTimes, fsTimes)) {
  return;
}
```

**Comment by jdalton** [comment]
The built-in `isFinite` use will ensure they're valid times and since the shape of the objects are made identical you can use a single `isEqual` call on them.

**Comment by jdalton** [comment]
If it's a hot method you can bypass `isEqual` and just coerce the dates to numbers and compare them. Something like:
```
var vmStamp = +vinylStat.mtime;
var vaStamp = +vinylStat.atime;
var fmStamp = +fsStat.mtime;
var faStamp = +fsStat.atime;

if (isFinite(vmStamp) && vmStamp === fmStamp &&
    isFinite(vaStamp) && vaStamp === faStamp) {
  return;
}
```

**Comment by jdalton** [comment]
Actually it can be simplified further. See above.
