### ISSUE TITLE
Injectable dependencies on Core build

### ISSUE THREAD

**Issue by Javiani** [lodash/lodash#2535]
Hi, first of all, thanks for this great library =)

I'll use it on a large scale application and one thing I notice on setup step is that I have only 2 available builds in my case, the core or the entire library. 

The greatest things about lodash for me are the chainning pattern and lazy evaluation. If I choose the modular way by requiring functions or by requiring the Core bundle I will miss those features I just said...

I was wondering.. it would be great if I could have only the basic funcionality like this:

```
_( [ 1, 2, 3 ] ) // Do nothing...
```

```js
import 'lodash/map' // Map injected
_([1, 2, 3])
.map( item => log( item ) )
.value() // [1, 2, 3]
```

```js
import 'lodash/collection'
var youngest = _([
	{ 'user': 'barney',  'age': 36 },
	{ 'user': 'fred',    'age': 40 },
	{ 'user': 'pebbles', 'age': 1 }
])
.sortBy('age')
.head()

console.log( youngest.value() )
```

Would it be better? Is it possible ?
This is not a issue, it is a enhancement instead.

**Comment by jdalton** [comment]
Hi @Javiani!

See #2246.

**Comment by Javiani** [comment]
Ohh  sorry, I should search more about that question instead of create a duplicated issue...

I just read the post you  mentioned on that issue... I'm so sad to know that chain is considered a bad practice ... I really like that chaining style ='( so much nice and better to understand...

Thank you very much!

**Comment by jdalton** [comment]
I don't consider it a bad practice btw, the post referenced in #2246 just highlights an alternative to chaining.
