### ISSUE TITLE
SQL-like queries over huge files with lodash

### ISSUE THREAD

**Issue by d180cf** [lodash/lodash#2536]
I'm using lodash to write something like SQL requests to large log files: the main program writes various logs in the json format, then the file is read and parsed with `JSON.parse` and the result is fed to lodash. This gives me some insight into how the program performs. The approach is somewhat similar to collecting telemetry.

Here is an example of the logs file:

```
...
{ "a": 1, "b": 2 },
{ "a": 2, "b": 3 },
...
```

Here is an example of my lodash queries:

```js
_(data)
  .filter(x => x.a > 0)
  .countBy("b")
  ...
```

The weak point in this approach is `JSON.parse` - it doesn't work well with > 1 GB files because it needs to have the entire file in memory. The solution looks simple: since the first query is usually a `filter` which picks a tiny subset of all the records, the json file can abstracted with an iterator. However it seems that lodash doesn't work with iterators:

```js
> lodash = require("lodash"); lodash.VERSION
'4.14.0'
> G = function * () { yield * [1, 2, 3]; }
[Function]
> [...G()]
[ 1, 2, 3 ]
> lodash(G()).sum()
0
> lodash(G()).map(x => -x).value()
[]
```

It's also not clear to me how to implement a custom data source for lodash, to make it work with all these `map` and `filter` functions.

**Comment by jdalton** [comment]
Hi @d180cf!

You might have some luck with [JSONStream](https://www.npmjs.com/package/JSONStream).
