### ISSUE TITLE
As of 4.14.0, certain _.defautsDeep operations fail to detect circular references

### ISSUE THREAD

**Issue by johannes-scharlach** [lodash/lodash#2537]
There seems to be a bug with 4.14.0 where certain (complex) circular references are not detected in _.defaultsDeep anymore. Instead, after a couple of seconds the process crashes and I get the following:

```
<--- Last few GCs --->

   95339 ms: Mark-sweep 1384.0 (1458.0) -> 1383.5 (1458.0) MB, 1291.6 / 0 ms [allocation failure] [GC in old space requested].
   96300 ms: Mark-sweep 1383.5 (1458.0) -> 1383.5 (1458.0) MB, 960.5 / 0 ms [allocation failure] [GC in old space requested].
   97388 ms: Mark-sweep 1383.5 (1458.0) -> 1383.5 (1458.0) MB, 1087.9 / 0 ms [last resort gc].
   98644 ms: Mark-sweep 1383.5 (1458.0) -> 1383.5 (1458.0) MB, 1256.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x13ae381b4629 <JS Object>
    1: assignValue(aka assignValue) […/node_modules/lodash/lodash.js:~2247] [pc=0x105f210b33b0] (this=0x13ae381041b9 <undefined>,object=0x3139e681c879 <an Object with map 0x1035acf4899>,key=0x18560bfdb309 <String[9]: updatedAt>,value=0x3417b2026791 <an Object with map 0x7922ee5e831>)
    2: /* anonymous */(aka /* anonymous */) [...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    75312 abort      gulp test
```

I'm having problems to construct a minimal example, since it seems to be working with almost anything I can currently imagine. My best hint is currently that this worked with no problems up to `4.13`, so something must have changed.

The way this problem initially occurred for me was when using `_.deepDefaults` on https://github.com/sequelize/sequelize associations.

**Comment by jdalton** [comment]
Hi @johannes-scharlach!

It could be related to this commit https://github.com/lodash/lodash/commit/dfb71a3a50869e4aa356c34b890f3ca04de13467.

**Comment by jdalton** [comment]
Was the issue with `_.cloneDeep` and `_.defaultsDeep` ?

**Comment by johannes-scharlach** [comment]
Sorry, I meant to write `_.defaultsDeep`

**Comment by jdalton** [comment]
If you can get a repo I'd dig it. Releasing our stack per property keeps it manageable so I'd like to do that when possible.

**Comment by johannes-scharlach** [comment]
I've just tested it with the current master and the problem still exists after your fix. However, I also tested when exactly it was introduced and it seems that https://github.com/lodash/lodash/commit/dfb71a3a50869e4aa356c34b890f3ca04de13467 is the cause of it, as you expected.

**Comment by jdalton** [comment]
How about reverting parts of the patch, https://github.com/lodash/lodash/commit/dfb71a3a50869e4aa356c34b890f3ca04de13467, until you stuff works. That would identify which part is causing you problems.
