### ISSUE TITLE
`_.pickBy` and Symbol polyfill (core-js) do not play well together

### ISSUE THREAD

**Issue by jrencz** [lodash/lodash#2538]
### Introduction:
I'm updating dependencies in my project and after updating lodash from `4.11.1` to `4.14.0` I found out that one of my tests failed.
I'm using `_.pickBy` like this:

```js
const matchesState = view => view.stateName === stateName;
const pickDestinationViews = views => _.pickBy(views, matchesState);
```

(context: I'm filtering Ionic views but this does not seem to be relevant).

Sometimes `view` is `undefined`, but that's supposed to be happening: `views` is an object with string-keyed properties only (`ion\d+` in fact). And each has an object as value.
I checked the key (2nd argument of the predicate) and I found out that it's a Symbol. `views` object is not supposed to have any symbols. What's more: in my tests I mock this object and I'm in full control if it has symbols.

I can only spot this problem in PhantomJS 2.1.1 (which happens not to have Symbol implemented). I run [core-js Symbol polyfill](https://github.com/zloirock/core-js/blob/master/modules/es6.symbol.js) for this case.

BTW: I'm aware that my `matchesState` can be implemented with `_.matchesProperty` like this:
```js
const matchesState = _.matchesProperty('stateName', stateName);
```
but that's not the point.

### What I found out:
`_.pickBy` iterates the object keys **and symbols** deeply (at least this is the conclusion I came up with). I'm not sure if it's by design or if it's by accident (maybe it's 80dbd4cbfab6a800668602b955eaa98de9b691c2, maybe it's how lodash interacts with the polyfill)

I run `console.log('getOwnPropertySymbols', Object.getOwnPropertySymbols(Object.prototype));` in Chrome (which implements Symbol) and in PhantomJS. In PhantomJS I got a lot of symbols while in Chrome I got none. I dumped all those symbols to strings and I found out that those are all the symbols I created in the application. Apparently that's how polyfill works.

I modified lodash locally like this:

```js
function pickBy(object, predicate) {
  getAllKeysIn(object).forEach(function (propertyOrSymbol) {
    console.log(propertyOrSymbol + '');
  });
  return object == null ? {} : basePickBy(object, getAllKeysIn(object), getIteratee(predicate));
}
```
and I saw symbols again. I think the problem may be in `getSymbolsIn`. `keysIn` which has the same responsibility as `getSymbolsIn` have some additional checks with `hasOwnProperty`. `getSymbolsIn` just uses `while` if there are no native symbols getter. Polyfill gives `Object.getOwnPropertySymbols` which lodash probably uses. I'm falling short in knowledge to debug it deeper.

I'm concerned about whether `_.pickBy` should reach as deep as `Object.prototype` when it gets symbols (supposing it's by design).
`_.pickBy` does not reach ownProperties of `ObjectPrototype` (probably because of how `keysIn` is implemented).

**Comment by jdalton** [comment]
Hi @jrencz!

This should be fixed https://github.com/zloirock/core-js/commit/78770786a4e5f2f87ea32b4dada46b9ce0a92887. Let the babel folks know if they need to bump any packages.

**Comment by jrencz** [comment]
@jdalton it turned out the project had some ancient babel-polyfill version installed (someone exposed it to bower publicly and it was used). Thank you for helping me detect that!
