### ISSUE TITLE
Cannot access original function attributes after wrapped by _.bind (__bindData__ vs metaMap)

### ISSUE THREAD

**Issue by alex-kowalczyk** [lodash/lodash#2539]
Current 4.x version of lodash `_.bind` does not use `__bindData__` variable anymore. 
Private `metaMap` weakmap is used instead. 
Client's code have no way to access original function. 

While this is valid and useful scenario for my case
For instance, we use decorators/marking functions to flag functions which do not require authentication. Then the functions are bound by lodash `_.bind`.

In older lodash our routing code could check that flag: 
`var flag = wrapped.__bindData__[0].flag`

In 4.x lodash we have no access at all to the original function and flags we set on the original function. 

Exposing `getData` private function to the public interface would restore required functionality.

**Comment by jdalton** [comment]
This is by design.
