### ISSUE TITLE
v4.14.0 caused 100% CPU on both Chrome & Firefox?

### ISSUE THREAD

**Issue by joyfulelement** [lodash/lodash#2540]
Hi:

Yesterday the React Web App I had in the continuous integration system `npm install`-ed the latest version of lodash (v4.14.0 upgraded from v4.13.1) with the following library lineup. Then every tests started failing. 

After some investigation, it was found that both the Chrome (Version 52.0.2743.82 beta-m (64-bit) & Firefox browser (47.0.1) would ***not respond*** when using the Web App. The process explorer shows that the **_browser had consumed 100% CPU with the increased memory footprint overtime_**.

Initially, I suspected there were other libraries might have caused the issue, since there were several library upgrades that had occurred between the builds. However, by reverting all the library upgrades, and test the Web App by reinstalling one library at the time, the leads were pointing to the lodash library. 

Several attempts were made to try enabling the profile runs on both browsers, but it did not work, since the browser itself was already unresponsive. Not sure if the information provided here are useful to help with troubleshooting, any suggestions for how to debug the issue on the busy browser would be wonderful too. Thanks!

```
"dependencies": {
    "d3": "3.5.17",
    "deep-equal": "1.0.1",
    "intl": "1.2.4",
    "isomorphic-fetch": "2.2.1",
    "lodash": "4.14.0",
    "material-ui": "0.15.2",
    "object-assign": "4.1.0",
    "radium": "0.18.1",
    "react": "15.2.1",
    "react-addons-shallow-compare": "15.2.1",
    "react-bootstrap": "0.30.0",
    "react-dom": "15.2.1",
    "react-intl": "2.1.3",
    "react-motion": "0.4.4",
    "react-redux": "4.4.5",
    "react-router": "2.6.0",
    "react-split-pane": "0.1.43",
    "react-tap-event-plugin": "1.0.0",
    "react-vendor-prefix": "0.0.1",
    "react-waypoint": "3.1.0",
    "redux": "3.5.2",
    "redux-logger": "2.6.1",
    "redux-thunk": "2.1.0",
    "shallowequal": "0.2.2",
    "velocity-react": "1.1.5",
    "warning": "3.0.0"
  }
```

**Comment by jdalton** [comment]
Probably related to #2537. Let me know if you find out anything more.
