### ISSUE TITLE
Git tags or releases for 3.x versions seem to be missing

### ISSUE THREAD

**Issue by brentonhouse** [lodash/lodash#2542]
You can download the full builds by tag using something similar to:  https://raw.githubusercontent.com/lodash/lodash/2.4.2/dist/lodash.js and https://raw.githubusercontent.com/lodash/lodash/4.0.0/dist/lodash.js but the 3.x versions are generating a 404:  https://raw.githubusercontent.com/lodash/lodash/3.0.0/dist/lodash.js

I am not sure if these are tags or releases or if there was a different format used for the 3.x releases.

Thanks!!

**Comment by jfmengels** [comment]
They still exist (see [here](https://github.com/lodash/lodash/tags?after=4.2.0))

Here is the [package.json](https://raw.githubusercontent.com/lodash/lodash/3.10.1/package.json) of v3.10.1, which shows that the `main` was not `dist/lodash.js` but [lodash.src.js](https://raw.githubusercontent.com/lodash/lodash/3.10.1/lodash.src.js)

**Comment by brentonhouse** [comment]
Thank you @jfmengels !
