### ISSUE TITLE
4.14.0 is not available on the CDN

### ISSUE THREAD

**Issue by pixelzoom** [lodash/lodash#2544]
When will 4.14.0 be available on the CDN? (https://www.jsdelivr.com/projects/lodash)

**Comment by jdalton** [comment]
4.14.0 is already there.

**Comment by pixelzoom** [comment]
Where?  Screenshot of current CDN site and menu of what's available:

![screenshot_71](https://cloud.githubusercontent.com/assets/3046552/17223371/8482cc0e-54b9-11e6-9e3d-42b0b447c36c.png)

**Comment by megawac** [comment]
@pixelzoom it's on jsdelivr, you likely just have a cache issue

https://cdn.jsdelivr.net/lodash/4.14.0/lodash.js

**Comment by megawac** [comment]
Also in the future, this is a jsdelivr issue and not a lodash issue. Please report issues to https://github.com/jsdelivr/jsdelivr

**Comment by pixelzoom** [comment]
No cache issue here, just following the CDN link provided on the lodash project page at https://lodash.com/. 

Understood on future jsdelivr issues.
