### ISSUE TITLE
Lodash no longer added to window obj on docs site

### ISSUE THREAD

**Issue by billyjanitsch** [lodash/lodash#2547]
Not sure whether this or lodash.github.io is the better place for this issue.

As of either 4.14.0 or 4.14.1, it looks like `_` is no longer added to the window object on the (old) [docs site](https://lodash.com/docs) (it's nice to have it there as a playground). I assume this is due to the recent exports changes. Was this intentional?

**Comment by jdalton** [comment]
It's there. Probably a caching issue.
