### ISSUE TITLE
I’m using the astral regex in another library

### ISSUE THREAD

**Issue by sallar** [lodash/lodash#2549]
Hi there,

I’m using the Astral regex in lodash in another library called `stringz`: https://github.com/sallar/stringz
The reason I’m doing so is I wanted the library to be small and zero-dep. I also included a link to Lodash and it’s license.

Just to make sure, is this OK, or should I take the library down?
Thank you.

**Comment by jdalton** [comment]
Thank you for the heads up! 

The notice in the readme is fine. I'd caution against copypasta for the sole goal of zero deps. You're shifting support from domain experts to yourself and further fragmenting support (as fixes for either will not likely make it into the other). npm has local caches on everyones machine so a package at a given version is less likely to be re-downloaded again.

**Comment by sallar** [comment]
True. I’ll try to find a better solution :)
