### ISSUE TITLE
Use native `inlcudes` method for Array or String if possible

### ISSUE THREAD

**Issue by miraage** [lodash/lodash#2552]
The subj.

**Comment by jdalton** [comment]
Hi @miraage!

There's little benefit to forking for native `Array#includes` and `String#includes` esp. when having to ensure a compat path (they handle `fromIndex` differently from each other).

**Comment by miraage** [comment]
```
Syntax
var boolean = array.includes(searchElement[, fromIndex])
Parameters

searchElement
The element to search for.
fromIndex
Optional. The position in this array at which to begin searching for searchElement. A negative value searches from the index of array.length + fromIndex by asc. Defaults to 0.
```

```
Syntax
str.includes(searchString[, position])
Parameters

searchString
A string to be searched for within this string.
position
Optional. The position in this string at which to begin searching for searchString; defaults to 0.
```

@jdalton what about this?

**Comment by jdalton** [comment]
The difference is around their handling of `fromIndex`. See compare steps 5 and 6 of [Array#includes](http://www.ecma-international.org/ecma-262/7.0/#sec-array.prototype.includes) to step 8 of [String#includes](http://www.ecma-international.org/ecma-262/7.0/#sec-string.prototype.includes).
