### ISSUE TITLE
Docs: invalid signature of baseDelay return

### ISSUE THREAD

**Issue by Ginden** [lodash/lodash#2553]
Documentation of [baseDelay](https://github.com/lodash/lodash/blob/4.14.1/lodash.js#L2482) says about return value of type "number". The same issue apply to public `defer` and `delay` functions.

But it directly uses return value of `setTimeout` that returns [timeout object](https://nodejs.org/dist/latest-v4.x/docs/api/timers.html#timers_settimeout_callback_delay_arg) in Node.js.

**Comment by jdalton** [comment]
Thanks! Super neat! I''ll update the docs.
