### ISSUE TITLE
Regression in v4.14.1 -  _.get() not working with '.' character

### ISSUE THREAD

**Issue by JamesSkinner** [lodash/lodash#2554]
I am seeing a regression (breaking change?) in version 14.4.1:

to reproduce
```
var _ = require('lodash');
var x = { y : 1 };
console.log(_.get(x, 'y')); // 1
console.log(_.get(x, '.y')); // undefined
```

v14.4.0 returns `1` for both these combinations.

**Comment by jdalton** [comment]
This is by design. It should treat leading `.` as `['', 'y']`.

**Comment by JamesSkinner** [comment]
@jdalton thanks.

If this is by design then it should be a major version change right? Upgrading from 14.4.0 to 14.4.1 will break code - in my case quite a lot of code as I have always treated these as two equivalent.

**Comment by jdalton** [comment]
Nope, it's a bug fix. You were relying on unspecified behavior.

**Comment by JamesSkinner** [comment]
Thanks, but I think this is a case of going through and updating code to remove this. I take your point about relying on unspecified behaviour. Still feels more like an undocumented feature than a bug though. 

`_.get(a, '.b.c')` always seemed more natural and readable than `_.get(a, 'b.c')` - would be surprised if this does not catch others out too...or maybe its just me.
