### ISSUE TITLE
Feature request: fp.roundAt

### ISSUE THREAD

**Issue by albertorestifo** [lodash/lodash#2559]
In LoDash FP the `round` method has a fixed arity of one.

It would be useful to add a new method `roundAt` to accept the optional parameter of `_.round`.

```js
const values = [
  3.4953,
  7.3215,
  4,
  // ...
];

const roundValues = fp.map(fp.roundAt(2));

roundValues(values);
```

**Comment by jdalton** [comment]
Thanks @albertorestifo!

We add alternative API for variadic methods on demand. The hardest part is bikeshedding a name 😄 .
I think `_.roundAt` sounds good.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by jdalton** [comment]
Dup of #2393.
