### ISSUE TITLE
Unable to resolve some modules:"./_listCacheHas" in /xxx/node_modules/lodash/_ListCache.js (os.osx.x86_64)

### ISSUE THREAD

**Issue by rnarayan** [lodash/lodash#2561]
My project is suddenly giving this error when I try to use (four levels deep) nested object. The error is not coming from my own code but it seems from from react-redux. Looks like react-redux uses listCache to save objects in its "store". 

I don't get this error if I remove the nested object. 

My package.json has this - "lodash": "^4.14.1",
react-redux node-module package.json has - "lodash": "^4.2.0",

I checked lodash folder in node_modules and listCacheHas.js is indeed missing. The related files that are present are - _ListCache.js, _listCacheClear.js, _listCacheDelete.js, _listCacheGet.js, and _listCacheSet.js

**Comment by jdalton** [comment]
It's there https://npmcdn.com/lodash@4.14.1/_listCacheHas.js.

**Comment by rnarayan** [comment]
Thanks. I uninstalled lodash and then installed again. The error is gone. I see the _listCacheHas.js. file now. I wonder what happened that this file got deleted. Anyway, sorry to open this issue. I should have tried uninstalling and reinstalling before I opened this issue.
