### ISSUE TITLE
Clarify default omission string for _.truncate

### ISSUE THREAD

**Issue by mk-pmb** [lodash/lodash#2562]
Hi, thanks for lodash!
While the docs [clearly state](https://lodash.com/docs#truncate) that the default omission is `…` (U+2026), lodash@4.14.1 seems to produce three dots:

```bash
$ nodejs -p 'require("lodash").truncate("foo", { length: 1 }).split("")'
[ '.', '.', '.' ]
```

Which one is in error (lodash or the docs), and what will be the future default?

**Comment by jdalton** [comment]
Thanks. That's a doc bug. It's been fixed on our [wip redesign](http://lodash.github.io/).
