### ISSUE TITLE
The arguments of _.transform iteratee in lodash/fp

### ISSUE THREAD

**Issue by jyjunyz** [lodash/lodash#2565]
I meet a problem today when I use the fp.transform, this is the code:

         var foo =function(obj, key, value, item) {
                arguments;
                console.log(key, obj);
                obj[key] = value + 1;
                return obj;
            }

            var test = f.transform(foo, {})({a:1, b:2, c:3})

however I  get undefined in value and item, I find the code in the source:

    'iteratee': function(iteratee) {
	      return function() {
	        var func = arguments[0],
	            arity = arguments[1],
	            result = iteratee(func, arity),
	            length = result.length;

	        if (config.cap && typeof arity == 'number') {
	          arity = arity > 2 ? (arity - 2) : 1;
	          return (length && length <= arity) ? result : baseAry(result, arity);
	        }
	        return result;
	      };
	    },

does it mean I can't use iteratee with 4 arguments? How can I get the key? Thanks~

**Comment by jyjunyz** [comment]
I know iteratee cap is  designed by default, however transform is used for Object. Is it reasonable when use to manipulate Object?

**Comment by jdalton** [comment]
Hi @jyjunyz!

You can remove iteratee argument capping by using [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert):
```js
var transform = fp.transform.convert({ 'cap': false });
```
