### ISSUE TITLE
Kebab and snake case are backwards!

### ISSUE THREAD

**Issue by atrauzzi** [lodash/lodash#2568]
Forgive me for pointing this out, but aren't the mnemonics used for these names reversed?

`kebabs-go-through-the-food`

`you_re_looking_good_just_like_a_snake_in_the_grass` (to quote ELO)

**Comment by jdalton** [comment]
See [_.kebabCase](https://lodash.com/docs#kebabCase) and [_.snakeCase](https://lodash.com/docs#snakeCase).

**Comment by atrauzzi** [comment]
@jdalton - I'm telling you that they're backwards.

**Comment by dmethvin** [comment]
http://jsbin.com/nijirijoru/1/edit?html,js,output

**Comment by jdalton** [comment]
Our `_.kebabCase` is `a-b-c` and `_.snakeCase` is `a_b_c`. For more info see [wikipedia.org/wiki/Letter_case](https://en.wikipedia.org/wiki/Letter_case#Stylistic_or_specialised_usage)and  [wikipedia.org/wiki/Snake_case](https://en.wikipedia.org/wiki/Snake_case).

**Comment by dmethvin** [comment]
Isn't that everyone's kebab and snake case? I don't see how it is backwards, even the example @atrauzzi gave seems like what lodash already does.

**Comment by JosephClay** [comment]
[The Wiki Gods](https://en.wikipedia.org/wiki/Snake_case) have spoken in favor of @dmethvin

**Comment by atrauzzi** [comment]
Ah!  You guys are right, I was confusing the input with the output.  Bright green vs. dark grey.

Apologies!
