### ISSUE TITLE
Weird behaviour on zipObjectDeep

### ISSUE THREAD

**Issue by 0x7b1** [lodash/lodash#2569]
Hey there, I've been finding a function for build a nested object based on a string structure, so I found that `zipObjectDeep` make that but I noticed a strange nesting on array, apparently it injects the terminal node on every array prototype. Here is my example.

```
 _.zipObjectDeep(['foo.bar','foo.bar.baz','foo.qux'],Array(3).fill([]));
```

The inspector shows me this
![image](https://k60.kn3.net/C/D/A/A/D/D/E43.png)

Edit: I expect the following output

```
  {
    "foo": {
       "bar": {
          "baz": []
        },
        "qux": []
    } 
  }
```

Thanks for the support.

**Comment by jdalton** [comment]
Ah, not a bug. The `Array#fill` is by reference so you're using the same `[]` array for all three values (that's why you see the recursive reference).

**Comment by jdalton** [comment]
Try:
```js
 _.zipObjectDeep(['foo.bar','foo.bar.baz','foo.qux'], _.times(3, _.stubArray));
```

**Comment by 0x7b1** [comment]
Oh, I see. Thank you
