### ISSUE TITLE
Push into array - Performance

### ISSUE THREAD

**Issue by aggarwalankush** [lodash/lodash#2574]
Hi,

I'm sorry, this is definitely not an issue. Couldn't find any place to directly ask lodash developers so asking here.

Consider we have 2 very large arrays of size N and M,
```
 var array1 = [1,2,3...N],
       array2 = [a,b,c...M];
```

I want to push array2 to array1. 

Using native javascript, 
`Array.prototype.push.apply(array1,array2) 
`

Using lodash, I can do
`array1 = _.concat(array1,array2)
`

But concat will copy array1, so I guess it's performance will reduce by O(N). Is there any other way of pushing one array to another using lodash? or Is there any way to provide option to modify existing array to increase performance?

-Thanks

**Comment by jdalton** [comment]
Yep, our `_.concat` is similar to `Array#concat`. We currently don't have an `_.append` method.
Internally we have a `lodash/_arrayPush` helper but I wouldn't rely on it.
