### ISSUE TITLE
_.merge and _.extend modifies the original Arrays

### ISSUE THREAD

**Issue by vinay-naik** [lodash/lodash#2576]
Hi recently i have faced an issue with lodash merge where instead of just returning the modified array/object, the otiginal array/objects are als0 modified.

Here is a link to my fiddle : [Merge Fiddle](https://jsfiddle.net/Vinay_Naik/ca9sdvr5/4/)

As you can see all the arrays now contain the merged values. How do i make sure that the original arrays are not changed?

**Comment by jdalton** [comment]
You can use [lodash/fp](https://github.com/lodash/lodash/wiki/FP-Guide):
```js
var fp = require('lodash/fp');
fp.merge(first, second);
```
or add an empty object to the front
```js
_.merge({}, first, second);
```
