### ISSUE TITLE
_.trimEnd returning incorrect value.

### ISSUE THREAD

**Issue by ReedD** [lodash/lodash#2578]
`_.trimEnd` is returning an empty string when it should return `APP`.

```
_.trimEnd('APP_GET_PATH', '_GET_PATH');
// Expected ➜ 'APP'
// Actual   ➜ ''
```

**Comment by jdalton** [comment]
The `chars` param is not a substring match but a stirng of chars to remove.
For example `_.trim('[abcd]', '[]')` will return `'abcd'`.

**Comment by jshado1** [comment]
@jdalton This is very counter-intuitive (and bizarre) behaviour, and the documentation does not suggest it in the least. Our entire team expected what @ReedD described. Please add your first sentence as a note to the docs.

**Comment by blaskovicz** [comment]
For anyone that happens upon this: https://gist.github.com/blaskovicz/ac9444c5efd2869ed259fcea0e06e3e6

**Comment by iptaylortechnical** [comment]
I have to agree with @jshado1, this is some truly bizarre behavior.

```js
console.log(_.trimEnd('test.txt', '.txt'));
```

Output:

```
tes
```

Docs needs to be much clearer on this. I still do not understand the purpose of this function. Even the example in the doc makes no sense and doesn't seem to align with the description. It seems useless and its definitely misleading. I would suggest making `trimEnd` to **only** trim trailing whitespace, update the doc accordingly, and separate out whatever this other (very unpredictable) functionality is to another function. And then define it well in the doc.
