### ISSUE TITLE
FP page error

### ISSUE THREAD

**Issue by tomByrer** [lodash/lodash#2579]
Thanks for your FP page!  Might have found an error:
https://github.com/lodash/lodash/wiki/FP-Guide
```
// The `lodash/map` iteratee receives three arguments:
// (value, index|key, collection)
_.map(['6', '8', '10'], parseInt);
// ➜ [6, NaN, 2]
```
Result doesn't seem right?

**Comment by jdalton** [comment]
That's correct. The non-FP flavor of `_.map` provides 3 arguments. The second argument trips up `parseInt` because `parseInt` accepts 2 params, the second being the `radix`.
