### ISSUE TITLE
Option to return [ ] with Nil values in castArray

### ISSUE THREAD

**Issue by chamini2** [lodash/lodash#2582]
Hi!

When using `castArray` I found it very weird that it literally just wraps it's value in an array, not checking for `undefined` or `null` values. I was wondering since only the first value is considered for the _casting_ (`_.castArray(1,2,3) // [ 1 ]`), we could add an option to receive a function for which a `true` output should create an empty array:

```
_.castArray(undefiend) // [ undefined ]
_.castArray(undefiend, _.isNil) // [ ]
_.castArray(undefiend, _.isNull) // [ undefined ]
```

Or maybe a boolean?

**Comment by jdalton** [comment]
Hi @chamini2!

The current behavior is by design. I'm not looking to expand on it at this time.
You can compose one with `_.cond`:
```js
var castArray = _.cond([
  [_.isNil, _.stubArray],
  [_.stubTrue, _.castArray]
]);
```
