### ISSUE TITLE
a bug of _.upperCase

### ISSUE THREAD

**Issue by ManitoYu** [lodash/lodash#2583]
lodash
`_.upperCase('ABC1abc')`
`=> ABC 1 ABC`

native code
`'ABC1abc'.toUpperCase()`
`=> ABC1ABC`

is this normal ?

**Comment by panzerdp** [comment]
@ManitoYu 
What you're looking for is ` _.toUpper('ABC1abc') => 'ABC1ABC'`.
`_.upperCase('ABC1abc')` considers the string as a sentences and splits it into words, then upper case it.
