### ISSUE TITLE
Missing exe.png

### ISSUE THREAD

**Issue by tamarmot** [lodash/lodash#2586]
css file references nonexistent image exe.png
```
.sourceRow[exe_line="true"] > .sourceLine {
103	    background-image: url(chrome://firebug/skin/exe.png);
…	
116	    background-image: url(chrome://firebug/skin/breakpointDisabled.png);
117	}
```

**Comment by jdalton** [comment]
Hi @tamarmot!

Are you sure that's not from an extension?

**Comment by tamarmot** [comment]
No clue, my build process found the issue.

It's with this file:

lodash
<https://github.com/lodash/lodash/tree/1c3a5cd8c2ccf9772640949c0836c37596d30252>
/vendor
<https://github.com/lodash/lodash/tree/1c3a5cd8c2ccf9772640949c0836c37596d30252/vendor>
/firebug-lite
<https://github.com/lodash/lodash/tree/1c3a5cd8c2ccf9772640949c0836c37596d30252/vendor/firebug-lite>
/skin
<https://github.com/lodash/lodash/tree/1c3a5cd8c2ccf9772640949c0836c37596d30252/vendor/firebug-lite/skin>
/xp
<https://github.com/lodash/lodash/tree/1c3a5cd8c2ccf9772640949c0836c37596d30252/vendor/firebug-lite/skin/xp>
/debugger.css

On Thu, Aug 18, 2016 at 8:41 PM, John-David Dalton <notifications@github.com

**Comment by jdalton** [comment]
Ah cool. It looks like your build process is overreaching. It shouldn't lint in `bower_components`.
