### ISSUE TITLE
why does does 'git pull' often fail to merge origin/master onto master in this repository?

### ISSUE THREAD

**Issue by robohack** [lodash/lodash#2588]
First off I should preface by saying that I don't actually use lodash myself -- it is included as part of a much larger project I work on.  I should also say I'm not really a Git expert (I have to RTFM almost every time I use it directly on the command line), though I do have a huge amount of experience with version control systems in general.

I frequently (3-10 times per week on at least two different systems) update a group of well over 40 repositories from github.com, lodash being one.  Many are quite active with daily changes, release branches, and so on.   I've only got the 'master' branch checked out in each, and I never make any changes of any kind in these repositories, and so normally my pulls result in fast-forward merges from 'origin/master'.

However lodash is the only one from this group that I regularly have trouble pulling (on both systems).  Quite regularly a pull fails with some kind of merge conflict.  Usually I remove the whole local repo and clone again (though I don't do this every time there's a problem -- I pull all the repos in this group with a script and I only fix things when I think the blast of errors from lodash might be obscuring some other error in another repo).

Today I tried to do a little more digging.

First I did this to try to clean up the mess (i.e. reset and move back to 'master'):

    $ git status
    # Not currently on any branch.
    # Unmerged paths:
    #   (use "git reset HEAD <file>..." to unstage)
    #   (use "git add/rm <file>..." as appropriate to mark resolution)
    #
    #       both modified:      .travis.yml
    #
    no changes added to commit (use "git add" and/or "git commit -a")
    $ git reset --hard HEAD
    HEAD is now at 74fa09a Change category names of "Utility" to "Util" and "Chain" to "Seq".
    $ git status
    # Not currently on any branch.
    nothing to commit (working directory clean)
    $ git checkout master
    Warning: you are leaving 3 commits behind, not connected to
    any of your branches:
    
      74fa09a Change category names of "Utility" to "Util" and "Chain" to "Seq".
      a4385d6 Bump to v4.0.0.
      6135c5b Rebuild lodash and docs.
    
    If you want to keep them by creating a new branch, this may be a good time
    to do so with:
    
     git branch new_branch_name 74fa09aa3fbdbe59defe9dee9e5cd0da18610ccd
    
    Switched to branch 'master'
    Your branch and 'origin/master' have diverged,
    and have 1 and 1362 different commits each, respectively.

So I did create a branch this time as suggested to see how/where it seemed to be in the history:

    $ git branch what-the-heck 74fa09aa3fbdbe59defe9dee9e5cd0da18610ccd

Git log now shows me how this new branch fits into things:

    * | commit ddd5318bb0075946284b76bccb0bf81ee63d1d26
    | | Author: John-David Dalton <john.david.dalton@gmail.com>
    | | Date:   Mon Jan 11 17:40:02 2016 -0800
    | | 
    | |     Change category names of "Utility" to "Util" and "Chain" to "Seq".
    | |     
    | | * commit 74fa09aa3fbdbe59defe9dee9e5cd0da18610ccd (refs/heads/what-the-heck)
    | | | Author: John-David Dalton <john.david.dalton@gmail.com>
    | | | Date:   Mon Jan 11 17:40:02 2016 -0800
    | | | 
    | | |     Change category names of "Utility" to "Util" and "Chain" to "Seq".
    | | |    
    | | * commit a4385d61cbbd2afee4793080c8b625e8f5c6a797
    | | | Author: John-David Dalton <john.david.dalton@gmail.com>
    | | | Date:   Sun Jan 10 13:44:36 2016 -0800
    | | | 
    | | |     Bump to v4.0.0.
    | | |    
    | | * commit 6135c5bd76e5d83623d8ace2defe24d2f8f65bc3
    | |/  Author: John-David Dalton <john.david.dalton@gmail.com>
    |/|   Date:   Sun Jan 10 13:43:51 2016 -0800
    | |   
    | |       Rebuild lodash and docs.
    | |   
    * | commit 3d44135df548fa22f36d16f50d28c884a62763ed
    | | Author: John-David Dalton <john.david.dalton@gmail.com>
    | | Date:   Mon Jan 11 16:13:32 2016 -0800
    | | 
    | |     Remove `run` alias.
    | |   

I've not been able to reproduce the issues I'm having in a test repo, so I'm not exactly sure what's going wrong here.

I was thinking this was some kind of manual error combined with moving the 'master' ref from one branch to another, but given the identical timestamp on the two "identical" commits at the top of this section of the log, that seems less likely.  It does still look like there was an accidental commit after a release tag on a release branch, one that was repeated on the master branch again.  It would also seem that the 'master' ref was on that release branch at the time I did the last pull where everything worked normally.  The next time I pulled the 'master' ref seems to have moved and a commit with identical content is on the new 'master' branch, so trying to merge it with what I had last checked out fails and a fast-forward merge is not possible.

I may be completely wrong of course, but I would like to figure this out -- I've been having issues with pulling the lodash repository for many months now.

**Comment by jdalton** [comment]
Hi @robohack!

I rebase a lot, which can cause merge issues.

**Comment by robohack** [comment]
I wondered, but it wasn't clear to me from the history it that' was really what was happening.

Thanks for letting me know!

(Perhaps you shouldn't rebase so often though, at least not after you've pushed to github -- it makes tracking your project a royal pain in the butt.  :-))

**Comment by jdalton** [comment]
Rebase 4 life!
