### ISSUE TITLE
_.result extra parameters

### ISSUE THREAD

**Issue by arcanis** [lodash/lodash#2589]
Everytime I needed to use `_.result`, I ended up rewriting a custom one because I needed to pass arguments to the underlying function. I've just stumbled upon this issue again, so I figured I could ask if something could be done about this (maybe in another new function, since the `defaultValue` parameter kinda prevents extending the function prototype).

I've seen [this post](https://github.com/lodash/lodash/issues/1603#issuecomment-153279939) that mentions that it apparently has already been asked and wontfixed, but I haven't been able to find the original issue.

**Comment by jdalton** [comment]
Hi @arcanis!

See #1603, #108, https://github.com/jashkenas/underscore/pull/927#issuecomment-11785973, & https://github.com/jashkenas/underscore/pull/886#issuecomment-11093659.
