### ISSUE TITLE
_.defaults and _.extends (assign) with Arrays

### ISSUE THREAD

**Issue by mgonto** [lodash/lodash#259]
Hey,

I'm using an Array with some extra properties to know some Metadata. For example, an array with values which have a metadata property with number of total pages.

I've tried using both extends and defaults and neither of them copy properties from sources when they're arrays. They just copy elements (I've checked code, this is intentional as there's an `isArray`)

I just wanted to know why, when it's an array you don't do both things. Copy properties + copy elements. I think it makes sense.

Thanks!

**Comment by Jainil** [comment]
That _.assign etc. works with arrays is pretty sweet. It saved me a bunch of time and I think it would be very helpful to many people if it was mentioned in the docs with some examples.
