### ISSUE TITLE
String "__proto__" results in strange behaviour in _.groupBy

### ISSUE THREAD

**Issue by Ginden** [lodash/lodash#2591]
Steps to reproduce:
```javascript
var q =  lodash.groupBy([{id: '__proto__'}], 'id')
q.__proto__; // [ { id: '__proto__' } ]
q instanceof Array; // true
```

I think it isn't expected behaviour, especially for user input.

**Comment by jdalton** [comment]
Hi @Ginden!

`__proto__` is a special property in JS that will [set the `[[Prototype]]`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto) of the object. So in this case it's creating an object `{ '__proto__': [{ 'id': '__proto__' }] }` which creates an object literal with a `[[Prototype]]` of an array containing the object `{ 'id': '__proto__' }`.

**Comment by Ginden** [comment]
Yes, I know why this happens, but I'm convinced that it isn't expected
behaviour to fire Object.prototype getters/setters on groupBy.

**Comment by jdalton** [comment]
Welp it is. If you can think of a way to continue to have `Object.prototype` inheritance and short-circuit `__proto__` consistently across all tested environments without a performance hit then I'd be interested.

**Comment by Ginden** [comment]
It's obviously impossible without performance hit, but changing certain property assignments to custom function that fallbacks to `Object.defineProperty` on property `"__proto__"` shouldn't result in observable performance hit. On my laptop it's 263k assignments per seconds vs. 410k assignments per second on Spidermonkey and and 660k/680k on V8 ( (for `Math.random()` keys; it never hits `__proto__` branch because it's rare edge case).

Hoverer, it will break assumption that `obj.__proto__ === Object.prototype`. 

```
function setProp(obj, prop, value) {
    if (prop === '__proto__') {
        Object.defineProperty(obj, prop, {value, enumerable: true});
    } else {
        obj[prop] = value;
    }
    return value;
}
```

**Comment by jdalton** [comment]
Yep. That works for me. Would you be up for creating a PR?
