### ISSUE TITLE
_.isNumber of NaN returns true

### ISSUE THREAD

**Issue by nickiewooster** [lodash/lodash#2593]
NaN means 'Not A Number' and should return 'false'

**Comment by dmethvin** [comment]
```js
> typeof(NaN)
"number"
```

The [lodash docs](https://lodash.com/docs#isNumber) say,

> **Note:** To exclude Infinity, -Infinity, and NaN, which are classified as numbers, use the _.isFinite method.

**Comment by jdalton** [comment]
Hi @nickiewooster!

See the explanation at https://github.com/lodash/lodash/issues/1669#issuecomment-160163179.
