### ISSUE TITLE
_.invokeMap does not throw errors if path does not point to a valid function

### ISSUE THREAD

**Issue by aweidner-ct** [lodash/lodash#2594]
Is this the correct behavior for `_.invokeMap`

    var test = { hello: function() { console.log("world") } };
    _.invokeMap([test, test, test], "heello") // [undefined, undefined, undefined]
    _.invokeMap([test, test, test], test.heelo) // [undefined, undefined, undefined]

If path doesn't point to a function then subtle bugs can be potentially introduced.  Any reason not to throw an error when path doesn't point to a valid function?

**Comment by jdalton** [comment]
Hi @aweidner-ct!

Lodash tends to avoid erroring when possible. The `_.invokeMap` method accepts a function as a second arg as well. See [_.invokeMap](https://lodash.com/docs#invokeMap).
> If `path` is a function, it’s invoked for, and this bound to, each element in collection.
