### ISSUE TITLE
Expose the bitmask comparison flag in _.isEqual()

### ISSUE THREAD

**Issue by jcready** [lodash/lodash#2596]
Similar to #2362, I would to be able to compare object while ignoring their constructors. It seems that the [`baseIsEqual` function already accepts a `bitmask` parameter](https://github.com/lodash/lodash/blob/171ca53c29470c2f49add21a805410bf7ca146b0/lodash.js#L3135-L3158) to allow for this type of comparison. Would it be possible for `_.isEqual()` to accept that bitmask as an additional parameter so it could pass it on to `baseIsEqual`?

**Comment by jdalton** [comment]
Hi @jcready!

I don't want to expose bitmask params to any users.
While they're super handy for internal use I don't think they're very user friendly.

**Comment by jdalton** [comment]
You can use [_.isEqualWith](https://lodash.com/docs#isEqualWith) to customize comparisons.

**Comment by jcready** [comment]
Can it just be a `isLoose` boolean like [`baseIsEqual` took in v3](https://github.com/lodash/lodash/blob/3.10.1/lodash.src.js#L2255)?
