### ISSUE TITLE
Importing direct modules (like lodash/cloneDeep) creates an error

### ISSUE THREAD

**Issue by ryanzec** [lodash/lodash#2599]
So when I try to import the cloneDeep function like this:

```javascript
import cloneDeep from 'lodash/cloneDeep';
```

and then try to use it, it results in the following error:

`Uncaught TypeError: keysFunc is not a function`

If I try to import the cloneDeep function like this:

```javascript
import {cloneDeep} from 'lodash';
```

It works fine.

Unless I am doing something wrong, this seems like a bug to me.

**Comment by ryanzec** [comment]
Some additional details, this is also happening for others. forEach causes this error:

`bootstrap 1f64caa…:50Uncaught TypeError: Cannot read property 'call' of undefined`

While that is a webpack file, the root of the error is from the `lodash/forEach` import as when I import it the other way, that error no longer shows up. I am also use 4.15.0

Is the importing of separate modules not supported or something?

**Comment by jdalton** [comment]
Hi @ryanzec!

I can't repro this. We have unit tests for all modules and nothing is failing. I'm guessing you have a plugin that's causing interference.

**Comment by martynchamberlin** [comment]
I just now got this error. It happens when you are splitting up your code using DllReferencePlugin. The `keysFunc` parameter is created from this:

```js
keys = __webpack_require__(126);
```

That require resolves as `undefined`. Hence the "Cannot read property 'call' of undefined" error.

**Comment by sorenhoyer** [comment]
Got the same error with Create React App

**Comment by JanBN** [comment]
Got the same error. How to solve this ?
