### ISSUE TITLE
Enhancement - filterfirst and filterlast function

### ISSUE THREAD

**Issue by fastcodejava** [lodash/lodash#2603]
I propose a new **filterfirst** and **filterlast** 

The **filterfirst** will return the first elements of the filtered array, and **filterlast** will return the last elements.

If we have an array of products as shown below, products are ordered by name and then my pricing. 

**filterfirst** will return the cheapest products and **filterlast** religion the most expensive products.
```js
[
    {
      "productId": "123456",
      "name": "Daiper",
      "category": "Home",
      "store": "store1",
      "pricing": 10
    },
    {
      "productId": "123457",
      "name": "Daiper",
      "category": "Home",
      "store": "store2",
      "pricing": 20
    },
    {
      "productId": "123458",
      "name": "Daiper",
      "category": "Home",
      "store": "store3",
      "pricing": 30
    },
    {
      "productId": "123466",
      "name": "Paint",
      "category": "Home",
      "store": "store2",
      "pricing": 25
    },
    {
      "productId": "123467",
      "name": "Paint",
      "category": "Home",
      "store": "store1",
      "pricing": 36
    },
    {
      "productId": "123468",
      "name": "Paint",
      "category": "Home",
      "store": "store3",
      "pricing": 80
    }
]
```

`_.filterfirst(products, "name")` will return 

[
    {
      "productId": "123456",
      "name": "Daiper",
      "category": "Home",
      "store": "store1",
      "pricing": 10
    },
    {
      "productId": "123466",
      "name": "Paint",
      "category": "Home",
      "store": "store2",
      "pricing": 25
    }
]

`_.filterlast(products, "name")` will return 

    [
       {
         "productId": "123458",
         "name": "Daiper",
         "category": "Home",
         "store": "store3",
         "pricing": 30
       },
       {
         "productId": "123468",
         "name": "Paint",
         "category": "Home",
         "store": "store3",
         "pricing": 80
       }
    ]

**Comment by jdalton** [comment]
Hi @fastcodejava!

This looks like to `_.takeWhile`, `_.takeLastWhile`, or `_.uniqBy`.
