### ISSUE TITLE
Feature Request: Math sumProduct

### ISSUE THREAD

**Issue by Blacksmoke16** [lodash/lodash#2605]
A feature that I would find useful is a sumProduct function.  This method would iterate over an array of objects and return the sum product of the specified attributes.

EX
```
items =
{
     {value: 5, quantity: 10, multiplier: 1},
     {value:15, quantity: 1, multiplier: 2},
     {value, .5, quantity: 500, multiplier: 1.75}
}

_.sumProduct(items, ['value','quantity','multiplier'])
```

 Which would return 517.5

**Comment by jdalton** [comment]
Hi @Blacksmoke16!

This looks like something you could compose with `_.sumBy` and `_.reduce`.
