### ISSUE TITLE
_.deburr erroneously converts 'ſ' (the long s, \u017f) to 'ss'

### ISSUE THREAD

**Issue by thorn0** [lodash/lodash#2606]
It should be just 's'. See https://en.wikipedia.org/wiki/Long_s

**Comment by jdalton** [comment]
Looks like it's a bit of both.
>  (e.g. "ſinfulneſs" for "sinfulness" and "ſucceſsful" for "successful").

Is this something that you've hit or is this just nit picky?

**Comment by jdalton** [comment]
Ah I see it's just part of the others there.
