### ISSUE TITLE
package.json main file - increase application start time

### ISSUE THREAD

**Issue by neophob** [lodash/lodash#2607]
hi

I try to increase the start time of my application, I measure the time using require-time on a ARM (armv7) machine

```
#echo 3 > /proc/sys/vm/drop_caches
#node_modules/.bin/require-time

..
634ms	lodash
..

```

now when I change the `  "main": "lodash.js",` to `  "main": "lodash.min.js",` in `package.json` then the startup time increase by about 150ms:

```
#echo 3 > /proc/sys/vm/drop_caches
#node_modules/.bin/require-time

..
467ms	lodash
..

```

I know there are other ways to improve the boot time of an app (like use lodash packages) - but due maintenance reasons I wont do it.

**Comment by jdalton** [comment]
Hi @neophob!

I've gone back and forth on leading with the minified file. I tend to favor debuggability.
It looks like you have pretty special requirements and have found a way to tackle them.

**Comment by jdalton** [comment]
You can also use the individual method modules like:
```js
var chunk = require('lodash/chunk');
```
which may improve start time.

**Comment by neophob** [comment]
Thanks @jdalton for your reply. You wrote "pretty special requirements" - well it depends on your view, but this affects all constraint devices like mobile phone, iot device etc. So for my view it's not the pretty special.

about debuggability, wouldn't source map's resolve this issue. 

another idea: should I open a new issue at npm, that npm selects the minimized version of a package when the --production flag is used?
