### ISSUE TITLE
Custom builds: whole list of excluded methods

### ISSUE THREAD

**Issue by thorn0** [lodash/lodash#2609]
When creating a custom build, it'd be nice to get the whole list of the methods that were excluded from it. Why? It was a surprise for me that `lodash minus="deburr"` created a build that also didn't include `kebabCase` and the other `*Case` methods. (BTW, in this specific case I'd prefer that `deburr` were replaced with `identity` in those methods as I'm pretty sure my code won't work with non-ASCII characters.) Now, it's too easy to miss that the methods you don't want to exclude are excluded.

**Comment by jdalton** [comment]
Hi @thorn0!

I'm discontinuing `lodash-cli` in v5 so not planning on expanding its features.
