### ISSUE TITLE
reverse of zipObjectDeep?

### ISSUE THREAD

**Issue by andreineculau** [lodash/lodash#2611]
I cannot find a reverse function for zipObjectDeep, that is if there is a built-in one?

```
_.zipObjectDeep(['a.b[0].c', 'a.b[1].d'], [1, 2]);
// ➜ { 'a': { 'b': [{ 'c': 1 }, { 'd': 2 }] } }
```

but what would be
```
_.???({ 'a': { 'b': [{ 'c': 1 }, { 'd': 2 }] } });
// ➜ [['a.b[0].c', 'a.b[1].d'], [1, 2]]
// ➜ { 'a.b[0].c': 1, 'a.b[1].d': 2 }

**Comment by jdalton** [comment]
Hi @andreineculau!

We currently don't have an `unzipObject` or `unzipObjectDeep`.
We have a [_.toPairs](https://lodash.com/docs#toPairs) which is a close `unzipObject`.
If you're looking for pseudo `JSON.stringify` and `JSON.parse` may be better choices.

**Comment by erquhart** [comment]
@jdalton no chance of this in the future? We currently have to use `toPairs` followed by `unzip` to mimic what `unzipObject` would do. Any reason not to provide it, or are you open to a PR?
