### ISSUE TITLE
Strange "has" behavior with sparse arrays.

### ISSUE THREAD

**Issue by re5et** [lodash/lodash#2614]
I am seeing behavior I do not expect when using "has" with an object containing a sparse array.

```Javascript
const _ = require('lodash')

const path = 'foo[2].a.b.c'
console.log(_.has({ foo: []}, path))
console.log(_.has({ foo: [0,1,]}, path))
console.log(_.has({ foo: [0,1,,]}, path))
```

outputs:

```
false
false
true
```

Seems odd to get that `true`.  Installed lodash@4.15.0 from npm, used node v6.2.0 to test, have seen the same in the browser.

**Comment by jdalton** [comment]
Thanks @re5et!
