### ISSUE TITLE
add `#forceInterval` function

### ISSUE THREAD

**Issue by alsotang** [lodash/lodash#2616]
The code of lodash seems too complex, so I write this issue instead of pr.

----

I think there is a useful function `#forceInterval` could be add in lodash.

When we use `setInterval` in code and the main loop block, the function in setInterval would omit some cycle.

For a `setInterval` example,

```js
var count = 0;

setInterval(function () {
  count++;
}, 100)

var startTime = +new Date()
while ((new Date - startTime) < 2000) {
}

setTimeout(function () {
  console.log('after 2000ms:', count) // count is only 1
}, 50)
```

`count` is expected to be `20`, while the main loop block, it is only `1`.

----

If we use `forceInterval`:

```js
function forceInterval(fn, time) {
  var lastRunTime = new Date();

  return setInterval(function () {
    var currentTime = new Date()
    if ((new Date - lastRunTime) < time) {
      fn();
    } else {
      var count = ~~((new Date - lastRunTime) / time)
      for (var i = 0; i < count; i++) {
        fn()
      }
    }

    lastRunTime = currentTime;
  }, time)
}

var count = 0;

forceInterval(function () {
  count++;
}, 100)

var startTime = +new Date()
while ((new Date - startTime) < 2000) {

}

setTimeout(function () {
  console.log('after 2000ms:', count) // count is 20
}, 50)
```

Then `count` would be `20`. It is in line with our expectations.

----

For many webpage, we have some setInterval logic in it, but sometimes some heavy compute occurs, then the setInterval logic would show wrong result for us. Such as clock chart, or some animation.

`forceInterval` can replace `setInterval` in many scenes seamlessly, and its usecase is common. So I hope this function can be added in lodash.

**Comment by jdalton** [comment]
Hi @alsotang!

Thanks for the suggestion but I'm not interested in adding anymore async functions at this time.

**Comment by alsotang** [comment]
ok
