### ISSUE TITLE
[flow] alternative to call void functions

### ISSUE THREAD

**Issue by umidbekkarimov** [lodash/lodash#2617]
What I want to do is:

```javascript
const handleClickOnLink = (event) => {
  _.forEach([preventDefault, preventBubbling, handleClick], (handler) => handler(event))
}
```

But in more clean way like:

```javascript
const handleClickOnLink = _.flowVoid(preventDefault, preventBubbling, handleClick)
```

**Comment by umidbekkarimov** [comment]
Use case in `react-bootsrap` - [createChainedFunction](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/createChainedFunction.js#L10]) (same in `material-ui` - [createChainedFunction](https://github.com/callemall/material-ui/blob/next/src/utils/helpers.js#L63)) shows that `_.flowVoid` is not appropriate name, because It collects all arguments, pass to all functions and doesn't bother about output

**Comment by jdalton** [comment]
Hi @umidbekkarimov!

You can take advantage of the `Function.prototype.call` reference `_.call` and do:
```js
_.invokeMap(funcs, _.call, event);
```
