### ISSUE TITLE
boolean indicating if debounced is queued or not

### ISSUE THREAD

**Issue by thenewguy** [lodash/lodash#2618]
It would be nice if the debounced function wrapper exposed if function execution is pending

Example use case:  Search input and submit button.  The search input automatically submits onChange using the lodash debounce utility.  The submit button should be disabled unless there is a debounced onChange call.  Something like debouncedFoo.pending or debouncedFoo.isPending() would make this simple

**Comment by thenewguy** [comment]
this seems to do the trick:
```
  debounced.isPending = function () {
      return !!timeout;
  }
```

**Comment by jdalton** [comment]
Thanks @thenewguy!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
How would you use `isPending` to toggle the state of the submit button?

**Comment by thenewguy** [comment]
It works with react like this on render:
```
                        <Button disabled={!this.propagateSearchState.isPending()}>
                            &nbsp;
                            <Glyphicon glyph="search"></Glyphicon>
                            &nbsp;
                        </Button>
```

**Comment by thenewguy** [comment]
I just realized I copy and pasted from search output which returned the debounced function from the vendored underscore library but the functionality would be the same
