### ISSUE TITLE
Module documentation

### ISSUE THREAD

**Issue by peterjwest** [lodash/lodash#2619]
Since people are using ES6 bundlers and specific module imports much more these days, it would be handy to have each function's module in the documentation.

I know that you can guess most of these from the sidebar, however if you're navigating by search or reading through the functions it can be time consuming to match back up to the sidebar.

**Comment by jdalton** [comment]
Hi @peterjwest!

I want to avoid cluttering up the documentation with various import techniques.
It's covered in the install usage folks can connect the dots from there.

**Comment by peterjwest** [comment]
Then might I suggest some kind of indication of which category you are in for each function; such as a sticky header, sidebar highlighting or colour coding.

As someone who uses the docs a lot, this would be a big time saver.

**Comment by jdalton** [comment]
You don't need to be aware of categories to import a methods.
```js
require('lodash/chunk');
```

**Comment by peterjwest** [comment]
Oh cool, that solves my problem!
