### ISSUE TITLE
Add deepPluck / deepPlant

### ISSUE THREAD

**Issue by brianmhunt** [lodash/lodash#262]
Just an idea for thought, it would be nice to access and set "deep" values from an object/array with a string or array of identifiers, like this:

``` js
a {
  b: {
    c: [0, 42]
   }
}

deepPluck("a.b.c.1") // == 42
deepPlant("a.b.c.0", 12) // a.b.c[0] == 12
```

I rolled my own, and thought to share in case you might want to include something like this in lodash. It's in Coffeescript, below.

There is a related [stackoverflow question](http://stackoverflow.com/questions/12785377)

Two notes:
1. My implementation uses `_.result` to get values unless the reference ends with a `*`.
2. I add an `endsWith` to the `string.prototype`, which does what one would expect - returns true when a string has the given suffix.

``` coffeescript
  #
  # Deep pluck
  # ~~~~~~~~~~
  # Pull a deeply nested element out based on an array of arguments
  #
  # e.g. array['abc'][0] == deepPluck(array, ['abc', 0])
  #
  utils.deepPluck = (obj, array_or_string, _default=undefined) ->
    if _.isString(array_or_string)
      keys = array_or_string.split('.')
    else # it is an array
      keys = array_or_string

    result = obj

    for key in keys
      if key.endsWith('*')
        # dereference; i.e. do not unwrap
        key = key.substring(0, key.length - 1)
        result = result[key]
      else
        # _.result acts like ko.utils.unwrapObservable, as needed,
        #or calls the given function
        result = _.result(result, key)

    if _.isUndefined(result) then return _default
    return result
```

And for planting:

``` coffeescript
  utils.deepPlant = (obj, array_or_string, value) ->
    if _.isString(array_or_string)
      keys = array_or_string.split('.')
    else # it is an array
      keys = array_or_string

    pinpoint = keys.pop()

    holder = if _.isEmpty(keys) then obj else utils.deepPluck(obj, keys)

    target = holder[pinpoint]

    if _.isFunction(target)
      target(value)
    else
      holder[pinpoint] = value

    return
```

I hope the above seems like an interesting idea.

**Comment by ahamid** [comment]
Dealing with a lot of complex data I find myself repeatedly reducing or `_.pluck`ing and `_.flatten`ing to accumulate all leaf values, so another vote here for some sort of pluckDeep or iterative reduce.

**Comment by jdalton** [comment]
Nested property support is on our [roadmap](https://github.com/lodash/lodash/wiki/Roadmap) for consideration in the future though the specifics of the API and support have not been worked out.

**Comment by marklagendijk** [comment]
@jdalton when this is picked up it might be a good idea to take a look at the latest version of my [lodash-deep](https://github.com/marklagendijk/lodash-deep) mixins module. It might be a good starting point.

Here are a few points that may be of interest.
1. Nearly all methods in lodash-deep work based on a propertyPath. Such a propertyPath can be specified either as a string in dot/bracket notation, or as an array.
2. For all methods which support a `_.pluck` style callback, there is a method which can be called with a propertyPath, so you get a `_.deepPluck` style callback. All these methods are implemented with a simple iteratee which does a `_.deepGet`
3. When this is picked up, you could add `_.deepPluck` style callbacks to the existing methods, but only if you would just support the propertyPath as array. Supporting the string notation on the existing methods would require a breaking change, as dots are valid characters in property names.

Btw, I really love the 3.x release! I could remove more than 5 mixins which I was using, which had exactly the same name, and did exactly the same thing :). Really nice to see that Lo-Dash keeps improving.

**Comment by sap9433** [comment]
I so wish _. deepPluck was available in lodash core . or may be _.pluck it self could had called _. deepPluck if there were ```.``` in search params.

**Comment by marklagendijk** [comment]
Lodash currently already supports this. See the documentation on [_.pluck](https://lodash.com/docs#pluck): `path (Array|string): The path of the property to pluck.`.

**Comment by ahmadalibaloch** [comment]
@marklagendijk I checked your module and I support it. Can you also tell how to specify path in lodash to deep pluck?

**Comment by jdalton** [comment]
@ahmadalibaloch
```js
_.map(collection, 'a.b.c')
```

**Comment by brianmhunt** [comment]
@jdalton @ahamid Is it not `_.get(collection, 'a.b.c')`?

**Comment by jdalton** [comment]
If you want to get one property sure but the request for for a deep `_.pluck`. I suggested `_.map` because `_.pluck` is being removed in v4.

**Comment by brianmhunt** [comment]
@jdalton I see, I see. How would one map something like this, then:

```javascript
[  { "a.b": "1" },
   { "a.b": "2" }, ]
```

i.e. what's going to be the way to handle properties with periods in them. Does the deep algorithm check for a property name (or partial property name) before delving down?

**Comment by jdalton** [comment]
> Does the deep algorithm check for a property name (or partial property name) before delving down?

Yes.

**Comment by brianmhunt** [comment]
Very snazzy. :grin:
