### ISSUE TITLE
lodash/fp `_.tap` should rearg

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash#2621]
In fp, `_.tap` would be more useful if it was rearged so it can be used with flow/compose.

**Comment by daedalus28** [comment]
I'll happily submit a PR for it if you agree that it's the right path.

**Comment by jdalton** [comment]
Heya @daedalus28!

The `fp.tap` is already rearged. Are you wanting to make it like the unmodified `_.tap`?

**Comment by daedalus28** [comment]
You're right - it is. Looks like it was an environment issue from having both fp and non fp versions used in the same project.
