### ISSUE TITLE
May I rely on uniqBy following array's order?

### ISSUE THREAD

**Issue by gunar** [lodash/lodash#2622]
The [docs](https://lodash.com/docs#uniqBy) don't state it, but I've looked through the [source code](https://github.com/lodash/lodash/blob/d47123779ed1f78a4c32abdde85f816160ba13dd/lodash.js#L4165) and `uniqBy` indeed processes arrays from start to end.

Could we add this "feature" of `uniqBy` to the docs?

Otherwise, could we have a new alias? (e.g. `orderedUniqBy`).

Thank you so much. Lodash/fp is AWESOME. :balloon:

**Comment by jdalton** [comment]
Thanks!
