### ISSUE TITLE
Enhancement: _.getBy

### ISSUE THREAD

**Issue by Mr-Wallet** [lodash/lodash#2623]
`_.getBy(object, path, iteratee, [defaultValue])`
This would be `_.get` except that it invokes `iteratee` at each step. Currently (as far as I can tell) the best way to drill into an object algorithmically is with `_.reduce` but then one needs to clutter the iteratee with undefined checks and a default value. `_.getBy` would keep that under the hood.

Example:
```
const thing = {
  a: () => ({
    b: () => ({
      c: () => 'first'
    }),
    x: {
      y: () => 'second'
    }
 })
};

_.getBy(thing, 'a.b.c', (x) => x()) // first
_.getBy(thing, 'a.x.y', (x) => _.isFunction(v) ? v() : v) // second
```

This would allow people to write arbitrarily complex get logic:
```
const thing = {
  a: () => ({
    boolToString: (b) => b ? 'T' : 'F',
  })
};

const invokeA = (invokeFunc) => {
  return _.getBy(
    thing,
    `a.${invokeFunc}`,
    (v, k) => k=== 'boolToString' ? v(true) : v(),
    null
  );
}

invokeA('boolToString') // 'T'
invokeA('notFound') // null
```

**Comment by jdalton** [comment]
Thanks @Mr-Wallet!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
