### ISSUE TITLE
Safari - [Error] SyntaxError: Invalid regular expression: missing terminating ] for character class 

### ISSUE THREAD

**Issue by joshikeerti** [lodash/lodash#2625]
Hi,
I am using lodash version 4.15 in one of my projects and the below error is thrown in safari when the application is rendered for japanese language.

'Error] SyntaxError: Invalid regular expression: missing terminating ] for character class '

The error is thrown on this line in the source code
 var rsApos = "['\u2019]"

When the application is rendered in English, the source code shows  Yn = "['â€™]"
In Japanese its Yn = "['窶兢",

There is a bracket missing when its in japanese and the error is thrown.

**Comment by joshikeerti** [comment]
Changing the source code to below fixed the issue.

var rsAposTemp = '\'\u2019'
var rsApos = '[' + rsAposTemp + ']'

**Comment by jdalton** [comment]
Hi @joshikeerti!

This doesn't look like a Lodash issue. Maybe more an encoding issue?
I'm not sure how rendering would effect source code processing.

**Comment by cbarbosa2** [comment]
I had a similar problem and it happened because I'm using WebPack's uglify which does the compression of unicode characters to UTF-8 and the server wasn't specifying UTF-8 as the charset causing the browser to fail to properly parse it.

**Comment by ndfhsledk** [comment]
Did you forget to set charset in <head>?
If the answer is Yes, add <meta charset="utf-8"/> to <head>
