### ISSUE TITLE
New update prevents me from testing lodash commands in the console.

### ISSUE THREAD

**Issue by rochestb** [lodash/lodash#2626]
Before adding lodash to my code I would often times go to https://lodash.com/docs/, open the console and start testing commands. Seems that with the new site update lodash is no longer available. Would love to have a playground or something I can do this again.

**Comment by zackhall** [comment]
Hey @rochestb – all of the code examples on the docs page now have a "Try in REPL" button in the bottom right corner of the code sample. You can use that as a playground for testing the code sample or using it as a playground for other commands.

**Comment by jdalton** [comment]
Dup of https://github.com/lodash/lodash.github.io/issues/46.
