### ISSUE TITLE
Question: is there a merge function that doesn't overwrite?

### ISSUE THREAD

**Issue by crh225** [lodash/lodash#2627]
I have two object that I would like to merge together without overwriting. Is this possible with merge and possibly I am doing something wrong?

example:
object1 =
`[
  {
    "name": "2014",
    "children": [
      {
        "name": "October 2014",
        "children": [
          {
            "name": "2014-10-03 Typing excercise",
            "children": []
          }
        ]
      }
    ]
  }
]`

object2 = 
`[
  {
    "name": "2013",
    "children": [
      {
        "name": "September 2013",
        "children": [
          {
            "name": "2013-09-12 Angular 2 projects",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "name": "2014",
    "children": [
      {
        "name": "September 2014",
        "children": [
          {
            "name": "2014-09-14 Last project",
            "children": []
          }
        ]
      }
    ]
  }
]`

Then I use the merge function

let result = _.merge(object1,object2);

**Comment by jdalton** [comment]
You might be able to use [_.mergeWith](https://lodash.com/docs#mergeWith).
Be sure to ping our [gitter chat](https://gitter.im/lodash/lodash) for help too.

**Comment by crh225** [comment]
@jdalton and for future google searchers. MergeWith is too much work. Use https://github.com/bigShai/extendify instead. It is a wrapper around lodash. Usually it is used in webpack config merging.
