### ISSUE TITLE
_.without should accept arrays and/or values

### ISSUE THREAD

**Issue by nmehta6** [lodash/lodash#2628]
Accepting arrays and/or values seems pretty consistent in methods such as
- `_.concat`
- `_.difference`

However, `_.without` only accepts values and not arrays. For example:

`_.without([1,2], [1,2])` returns `[1,2]` instead of `[]`

Would you be willing to accept a PR for this?

**Comment by jdalton** [comment]
The behavior of `_.without` is by design. If it were to accept an array it would be `_.difference`.
