### ISSUE TITLE
delegate collection calls to underlying objects

### ISSUE THREAD

**Issue by rachidbch** [lodash/lodash#2629]
Does it makes sens for Lodash to try to delegate function call to underlying objects: for instance calling ```_.includes(my_custom_collection)``` would first try to locate an call an ```includes``` method on ```my_custom_collection``` before doing it's own thing if it can't delegate.

Such a behaviour would allow to build custom structures that would comply to lodash API.
Ramda does just that and it's works pretty well and I would love to have that on Lodash.

**Comment by jdalton** [comment]
Hi @rachidbch!

Over the years we've moved away from duck-typing. Opting for the `xyzWith` form of methods for customization.

**Comment by rachidbch** [comment]
Thanks for your rapid answer @jdalton,
So which approach would you recommend if i want a custom developped data structure to be transparently processed as an array by lodash ?

**Comment by jdalton** [comment]
We haven't exposed an `includesWith` yet so we'd need to do that in your use case.
Then you'd roll your own custom flavor. See the [_.mergeWith](https://lodash.com/docs#mergeWith) doc example.

**Comment by rachidbch** [comment]
Well I forced my custom structure to be ArrayLike and so far Lodash can play with it.
Your reactivity is impressive! Thanks @jdalton !

**Comment by StreetStrider** [comment]
@rachidbch looks like you're trying to achieve collections polymorphism. You can dig fantasy-land and transducers to see what other people do in that direction. Another interesting approach is to use Symbols for implementing interfaces.

**Comment by rachidbch** [comment]
Sorry for the delay @StreetStrider,

I'v already played (quite superficially) fantasy-land approach and transducers and ramda is helpfull there.
Lodash is obviously not fantasy-land compatible and I find it quite hard to have easy 'collection polymorphism' with loadash. If you have lodash specific approaches that works please let me know.

**Comment by jdalton** [comment]
FWIW Ramda isn't fantasy-land 1.0 compatible either and may pull its delagation code.

**Comment by StreetStrider** [comment]
@rachidbch I always end up implementing my own custom interfaces/protocols for specific cases.
You can vote up for #2406 , by the way. :point_up: if not already.

**Comment by rachidbch** [comment]
#2406  voted! Thanks for your answer @StreetStrider

**Comment by rachidbch** [comment]
Yes @jdalton my bad: could we say 'Ramda is fantasy-land friendlier than lodash' ?
By the way huge thanks for all the good work invested in Lodash, this lib is amazing!
