### ISSUE TITLE
Expose lodash on window on docs page

### ISSUE THREAD

**Issue by bcherny** [lodash/lodash#2630]
So while browsing docs at https://lodash.com/docs, I'm able to open devtools and test out lodash functions.

**Comment by jdalton** [comment]
Dup of #2626.

**Comment by jdalton** [comment]
Lodash is loaded on the page.
Your console context is mis-set. Dup of [lodash.github.io/#46](https://github.com/lodash/lodash.github.io/issues/46).

**Comment by bcherny** [comment]
Good catch - thanks @jdalton
