### ISSUE TITLE
Adding key/value pair values

### ISSUE THREAD

**Issue by ev1stensberg** [lodash/lodash#2631]
Hey! Sorry for polluting the issue tracker, but I've got a problem with an array I want to solve. The array has objects with keys 1,2,3,4,5 etc and I want to merge the object values ( 63 && 26 ) together in a new array, so if I got 

`newArray[0` , that would be `89`.

Do you know how that is possible / how do I combine the values of keys 1 and 2 ?

![skjermbilde 2016-09-03 kl 15 36 37](https://cloud.githubusercontent.com/assets/16735925/18225151/78d6cd9c-71ec-11e6-85a9-7c5a7c63bb89.png)

**Comment by jdalton** [comment]
Looks like something to implement on your own though you can try [_.mergeWith](https://lodash.com/docs#mergeWith). Also for help you should check out our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by ev1stensberg** [comment]
Great, thanks for helping out!
