### ISSUE TITLE
Unexpected behavior with `flowRight`, `partialRight`, and `mapValues`

### ISSUE THREAD

**Issue by dmsnell** [lodash/lodash#2632]
Today I was caught off-guard when I converted a function into a point-free style utilizing `flowRight`. The returned values turned into undefined objects. When I inserted a logger in the `flowRight` chain, the results were correct! After this, I discovered that if I started my `flowRight` chain with `identity` everything works as I expect it to, but if I leave that off, it fails.

This is really stumping me and I would be super grateful for some feedback, whether this is buggy behavior or if I'm just missing something obvious. Thanks!

```js
import { flowRight, identity, map, mapValues } from 'lodash';
const l = m => console.log( m );

const identityMap = flowRight(
  partialRight( map, o => Object.assign( {},
    { type: 'number' },
    o.value % 2 && { value: o.value },
  ) ),
  identity // this is the only difference
);

const justMap = flowRight(
  partialRight( map, o => Object.assign( {},
    { type: 'number' },
    o.value % 2 && { value: o.value },
  ) ),
);

const values = {
  first: [
    { value: 1 },
    { value: 2 },
    { value: 3 },
  ],
  second: [
    { value: 4 },
    { value: 5 },
    { value: 6 },
  ]
}

l( mapValues( values, identityMap ) ) // succeeds as expected
l( mapValues( values, justMap ) ) // fails with [false, false, false] for values
```

Also there is a working example on [jsbin](http://jsbin.com/konolagunu/2/edit?js,console)

**Comment by jdalton** [comment]
Hi @dmsnell!

The `_.mapValues` method provides 3 arguments to its iteratee.
So when those are applied to the partialed function it does something like:
```js
var f = _.partialRight((a,b,c) => [a,b,c], 1)

f(2);
// => [2, 1, undefined]

f(2, 3)
// => [2, 3, 1]
```

**Comment by dmsnell** [comment]
> The _.mapValues method provides 3 arguments to its iteratee.

thanks @jdalton - I poured over the docs for all of the functions but forgot about the iteratee args!

so thankful for your help! so quick!
