### ISSUE TITLE
Not possible provide custom Cache to memoize

### ISSUE THREAD

**Issue by Kikobeats** [lodash/lodash#2633]
Docs says:

> Note: The cache is exposed as the cache property on the memoized function. Its creation may be customized by replacing the _.memoize.Cache constructor with one whose instances implement the Map method interface of delete, get, has, and set.

So I'm trying to pass a custom Map-like to cache:

```js
const mem = require('lodash/memoize')
mem.Cache = require('lru-cache')
```

The problem is that in the implementation `cache.has` is used before be assigned, so always I have `cache.has is not a function`.

Check [this](https://github.com/lodash/lodash/blob/master/dist/lodash.js#L10235) line and [this](https://github.com/lodash/lodash/blob/master/dist/lodash.js#L10244).

**Comment by jdalton** [comment]
Hi @Kikobeats!

We have unit tests to verify our support. The references you point out are called within the memoized function so after anything has been set `memoize.Cache` itself. You should ensure `lru-cache` can be called with the `new` operator.

**Comment by Kikobeats** [comment]
👍
