### ISSUE TITLE
_ is not defined on lodash doc

### ISSUE THREAD

**Issue by alsotang** [lodash/lodash#2634]
![image](https://cloud.githubusercontent.com/assets/1147375/18268875/5224e33c-7458-11e6-8826-e64fc6e3d13a.png)

I think provide a `_` is convenient for test functions.

**Comment by Florian-R** [comment]
Same comment as in jashkenas/underscore#2585, the script is [included](https://github.com/lodash/lodash.github.io/blob/3fa4f6261e406b17ef1712704dc813cd67ab8fb8/_layouts/docs.html#L34) in the docs, I suspect some network error.

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/18269491/d5cde704-745a-11e6-953b-f453a619086e.png)


I made some mistake. Sometimes the inspector not on `top` but other frame.

**Comment by jdalton** [comment]
Dup of [lodash.github.io/#46](https://github.com/lodash/lodash.github.io/issues/46).
