### ISSUE TITLE
isPlainObject node 4 vs 6

### ISSUE THREAD

**Issue by AdriVanHoudt** [lodash/lodash#2635]
Hi, 

I noticed that using hapijs `lodash.isPlainObject(request.query)` returns true on node 4 and false on node 6. I know that node 6 changed something (see https://github.com/nodejs/node/pull/6055) but I would suspect it still working. 
`request.query` is being set here https://github.com/hapijs/hapi/blob/master/lib/request.js#L199
I do know `request.query` is also being validated by Joi so I'm ccing @marsup to see if he has some insights.

I hope someone knows what's up

**Comment by AdriVanHoudt** [comment]
So by debugging I got to https://github.com/lodash/lodash/blob/85ca1f45b6361865a0f21426f34b45f12ff80877/lodash.isplainobject/index.js#L135 stating `typeof Ctor == 'function'` is `false`

**Comment by AdriVanHoudt** [comment]
Talked to @marsup and he can't reproduce with Joi so it is probably hapi/node

**Comment by jdalton** [comment]
Hi @AdriVanHoudt!

If [_.isPlainObject](https://lodash.com/docs#isPlainObject) is too strict you can also try [_.isObject](https://lodash.com/docs#isObject) or [_.isObjectLike](https://lodash.com/docs#isObjectLike).

**Comment by AdriVanHoudt** [comment]
@jdalton it is not though, I only want a "pure" object no array or function or string
