### ISSUE TITLE
Website : broken Left Nav 

### ISSUE THREAD

**Issue by delmotte** [lodash/lodash#2636]
Your left nav bar is broken (at least Chrome and Firefox)
![screencapture-lodash-docs-4-15-0-1473176141379](https://cloud.githubusercontent.com/assets/6682231/18280144/5e7b0224-7458-11e6-872c-1a188234051e.png)

**Comment by tsheils** [comment]
just signed in to open the same issue. Chrome for Mac.

**Comment by jdalton** [comment]
Dup of https://github.com/lodash/lodash.github.io/issues/58.
