### ISSUE TITLE
Feature Request: _.split with negative limit

### ISSUE THREAD

**Issue by roberto-naharro** [lodash/lodash#2637]
Is possible to make the [split function](https://lodash.com/docs/4.15.0#split) start from the end if the limit argument is negative?

For example:

```
_.split('obj.field1.subfield2', '.', 2);
// => ['obj', 'field1']

_.split('obj.field1.subfield2', '.', -1);
// => ['field2']
```

Thanks!

**Comment by jdalton** [comment]
Hi @roberto-naharro!

Our `split` method mimics [String#split](https://mdn.io/split).

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
