### ISSUE TITLE
_.get(object, []) does not seem to return the object itself

### ISSUE THREAD

**Issue by dashed** [lodash/lodash#2638]
I expected this:

```js
const root = {'a': 42};
_.get(root, []) === root; // => true
```

Instead, `undefined` is returned. I'm unsure if this is intentional behaviour; I cannot seem to find a github issue on this.

----

Fix for this seems to be to replace this line:
https://github.com/lodash/lodash/blob/84270a6a398d6ab065f8d1cf6901c5fc1da917ae/lodash.get/index.js#L466

with:

```js
return (index >= 0 && index == length) ? object : undefined;
```

or simply,

```js
return (index == length) ? object : undefined;
```

**Comment by jdalton** [comment]
Hi @dashed!

The current behavior is intentional. See #1270.

**Comment by dashed** [comment]
Haha. I didn't realize I reported this. 👍
