### ISSUE TITLE
Logging a wrapper commits it?

### ISSUE THREAD

**Issue by eggers** [lodash/lodash#2639]
Is this to be expected:

```js
var array = [1, 2];
var wrapped = _(array).push(3);
 
console.log(array);
// => [1, 2] 

console.log(wrapped);
// => LodashWrapper { ...

console.log(array);
// => [1, 2, 3] 
```

It appears that logging the wrapper works the same as `commit()`

**Comment by jdalton** [comment]
Hi @eggers!

The chaining syntax create a sequence of actions.
They are deferred until an implicit or explicit `.value` is called.

**Comment by eggers** [comment]
@jdalton Yes, I understand chaining. The question was if logging the chain implicitly calls `.value()` or `.commit()` on it?

Note, before logging, the array is `[1, 2]`, and after logging the chain it is `[1, 2, 3]`
