### ISSUE TITLE
_.update Last Element in Array

### ISSUE THREAD

**Issue by jacobp100** [lodash/lodash#2640]
Would it be possible to allow `_.nth`-like indices for paths when the object is an array?

```js
import { update, add } from 'lodash/fp';
const addOneToLastElement = update(-1, add(1));
```

**Comment by jdalton** [comment]
Hi @jacobp100!

This gets into specializing for arrays which I've tried to avoid.
That said, we'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

Related to #1315.

**Comment by jacobp100** [comment]
@jdalton What if paths allowed functions? Then you could do `update(['a, 'bArray', last], ...)`.

**Comment by jdalton** [comment]
I don't want to increase the scope of paths.
