### ISSUE TITLE
groupBy/partition iteratees don't have index access

### ISSUE THREAD

**Issue by sparty02** [lodash/lodash#2641]
the groupBy/partition functions (maybe others in that family) are only invoked with the value in their iteratee functions.  Was it a design/perf decision not to also invoke them with the index?

In my case, I'm trying to split an array into chunks based on odd/even.  My intial thought was:
```js
let [odd, even] = _.partition(collection, (item, index) => index % 2 !== 0);
```

**Comment by jdalton** [comment]
Dup of #2238.

**Comment by jdalton** [comment]
All routes lead to reduce 😀

**Comment by Kerrick** [comment]
> When we expanded our "By" methods in v4 we changed them to accepting a single param to simplify and make them consistent.

This makes sense for `By` methods, but what about `partition`? One common use-case for `partition` was to take an array of objects and "columnize" them, like so:

```js
_.partition(things, (thing, i) => i % 2 === 0);
```

It's fair to say "all routes lead to reduce" but those routes can get pretty ugly:

```js
things.reduce(
   ([a, b], thing, i) => i % 2 === 0 ? [[...a, thing], b] : [a, [...b, thing]],
  [[], []]
);
```

OR:

```js
const partitioner = test => [
  ([a, b], x, i) => test(x, i) ? [[...a, x], b] : [a, [...b, x]],
  [[], []]
];
things.reduce(...partitioner((x, i) => i % 2 === 0))
```

**Comment by matthewharwood** [comment]
@Kerrick I'm running across this problem as we speak.  I'm curious if there is any common util for "columnize" https://stackoverflow.com/questions/49289410/how-to-order-a-sorted-array-into-columns-when-there-are-remainders-with-lodash/49289727#49289727

**Comment by elmigranto** [comment]
@Kerrick, make a clojure.

``` js
partitionWithIndex = () => {
  let index = 0
  return (item) => index++ % 2 === 0
}

_.partition(things, partitionWithIndex());
```

**Comment by mcmar** [comment]
Same situation as @Kerrick and @elmigranto 
Partitioning by `idx % 2` is necessary when working with redis sorted sets, which returns all your data as a flat array of `[member, score, member, score, ...]`
Partitioning by odd-even seems like a common pattern that deserves a better use-case than `reduce`.

I think the real answer here is that there's nothing wrong with "by" functions having access to index. Seems like ideology-driven form over function. But also, it's really not clear why `partition` is considered a "by" function

**Comment by elmigranto** [comment]
It is certainly confusing given how a lot of other (older) functions have an index argument, reference to originial connection and support for `this` bindings. But I don't see it as purely ideological:

- if you have a clojure that adds call count (or reference to original, or w/ever), you write that once and use it everywhere
- if it were in the library, its every function must support this common yet limited protocol which beyond being "not enough" for everyone brings confusion to certain other situations (say, when there are multiple arguments and not just the item, or why do you need collection+index AND the item)
- can't get rid of it in old functions in order not to break anything's
