### ISSUE TITLE
isMap() is not working in server side

### ISSUE THREAD

**Issue by coolmsd** [lodash/lodash#2642]
Hi, I made a new map and isMap return false.
But it works in the browser (console of developer tools in Chrome)
This is so wired.. Is it bug or something?

let info = new Map();
console.log(_.isMap(info));

**Comment by jdalton** [comment]
Which Node version.

**Comment by coolmsd** [comment]
It's 4.4.7 should I upgrade?

**Comment by jdalton** [comment]
Nope. It works there too.
I'm guessing you have a shim that's replacing or wrapping the built-in map.

**Comment by coolmsd** [comment]
I just tried 
`    let k = new Map();
    console.log((_.isMap(k)));`
It returned false.

**Comment by jdalton** [comment]
<img width="306" alt="screen shot 2016-09-11 at 3 19 23 pm" src="https://cloud.githubusercontent.com/assets/4303/18420939/0a31bb34-7833-11e6-8db6-5c2a53de098a.png">

We also run unit tests again Node v4 [per commit](https://travis-ci.org/lodash/lodash).

**Comment by coolmsd** [comment]
Ok. This is so wired..... I will try after reinstall module. Thanks.
