### ISSUE TITLE
Does _.partition maintain sort order?

### ISSUE THREAD

**Issue by jasonkarns** [lodash/lodash#2643]
I've done some quick testing and it appears so, but I'm curious if this can be relied upon.

That is, will a sorted array, once partitioned, result in two sorted arrays?

**Comment by jdalton** [comment]
> That is, will a sorted array, once partitioned, result in two sorted arrays?

Yep. It should.

**Comment by denis-sokolov** [comment]
Would you accept a PR adding this guarantee into the documentation and a test ensuring it stays that way? @jdalton
