### ISSUE TITLE
set.forEach is not a function

### ISSUE THREAD

**Issue by binarykitchen** [lodash/lodash#2644]
Thrown in this function

```
  function setToArray(set) {
    var index = -1,
        result = Array(set.size);

    set.forEach(function(value) {
      result[++index] = value;
    });
    return result;
  }
```

on a quite old Firefox version 13.0

**Comment by jdalton** [comment]
Of course this issue is marked invalid.

That version of Firefox is not supported and fell off the market share radar in 2013 will lower than 0.2% back then.

**Comment by BenderV** [comment]
Note that is error is present on Firefox 15 to Firefox 24.
