### ISSUE TITLE
lodash/fp is heavy

### ISSUE THREAD

**Issue by bfred-it** [lodash/lodash#2645]
I never used the fp version of lodash before and thought I'd give it a go. Thankfully my build shows the package size and I noticed a 50KB increase of the minified file.

Here's a reduced test:

```sh
$ echo "require('lodash/pick')" | browserify - | uglifyjs | gzip-size
2044
$ echo "require('lodash/fp/pick')" | browserify - | uglifyjs | gzip-size
22301
```

Not sure what can be done about it and it does look like the sudden increase only applies to the first `fp` import, but I ended up avoiding it and just using `obj => pick(obj, 'prop')` instead of `fpPick('prop')`

To easily see all the extra modules I used

```sh
echo "require('lodash/fp/pick')" | browserify --full-paths - | uglifyjs | discify --open
```

**Comment by jdalton** [comment]
You can use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) and [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) with the settings:

```js
new LodashModuleReplacementPlugin({ currying: true, placeholders: true })
```

**Comment by jdalton** [comment]
For example
```js
import { pick} from 'lodash/fp';

console.log(
  pick(['a', 'c'])({ 'a': 1, 'b': 2 , 'c': 3 })
);
```
when bundled is 7 kB min+gzip

**Comment by bfred-it** [comment]
That doesn't seem to be working for me, tried with `import {pick} from 'lodash/fp';` nor `import pick from 'lodash/fp/pick';` through babelify. Don't have time for a reduced test case right now, but both the transform and the plugin seem to be loaded correctly (if absent either browserify or babelify throw an error)

This is in my package.json:

```json
{

  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "plugins": [["lodash", { "currying": true, "placeholders": true }]]
        }
      ]
    ]
  }
}
```

Also I thought that those plugins were only useful to avoid having to load files separately (`lodash/fp/pick`) rather than remove unused imports. I'm wondering why they're imported in the first place given how modular lodash is

**Comment by jdalton** [comment]
The settings are for the `lodash-webpack-plugin`.

**Comment by bfred-it** [comment]
I see, but I'm not using webpack, so for me lodash/fp still carries 50K

**Comment by jdalton** [comment]
Using only `babel-plugin-lodash` the size is 14.12 kB min+gzip.

**Comment by bfred-it** [comment]
14K gzipped is still pretty large for that function though. I'd love to [Using Lodash as a Collection of Micro-Libraries](http://knpw.rs/blog/using-lodash) but seeing `lodash/flatMap` increase my build by, again, 50K made me question it (and try a [different function](https://github.com/inca/flatmapjs/blob/master/index.js))

**Comment by jdalton** [comment]
If you're concerned about size I'd suggest moving away from browserify as it generally produces larger bundles than others.

**Comment by jdalton** [comment]
Our `flatMap` has iteratee shorthand support which adds some overhead. With `lodash-webpack-plugin` the size is 630 bytes min+gzip.

**Comment by bfred-it** [comment]
"Some overhead" shouldn't be that much, I even see a memoize in there. As is you're agreeing that lodash is heavy unless you use webpack + the plugin, none of the other bundlers. I _will_ be moving to webpack for newer projects (this one was 2014+) but I'll stick to rollup for my own modules.

**Comment by jdalton** [comment]
> "Some overhead" shouldn't be that much, I even see a memoize in there.

Deep partial matching of [_.matches](https://lodash.com/docs#matches) and [_.matchesProperty](https://lodash.com/docs#matchesProperty) aren't cheap. That said if you use a handful of methods they cost evens out a bit more.

I wrote a plugin for webpack because it had the process and exposed the hooks needed to rewire modules. For what it's worth rollup and webpack 2 still don't tree-shake Lodash properly so you'll still need to use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash).

**Comment by jdalton** [comment]
If you'd like to create a Browserify or Rollup plugin that consumes [lodash-webpack-plugin/src/mapping](https://github.com/lodash/lodash-webpack-plugin/blob/master/src/mapping.js).
