### ISSUE TITLE
Hope for the kindle and epub versions of docs

### ISSUE THREAD

**Issue by hustcer** [lodash/lodash#2647]
Thanks for the awesome work !
`lodash` is the most commonly used package in my everyday work. Actually, It's so important and helpful that I hope I can put all the docs in my kindle, that way, I can read the docs whenever I have no laptop by hand.
BTW: The new docs are great.

**Comment by jdalton** [comment]
Hi @hustcer!

While not perfect there is Lodash docs available on http://javier.xyz/docs2epub/.

**Comment by hustcer** [comment]
Thanks. That helps, but kindle version will be better.

**Comment by jdalton** [comment]
If you want to spend time designing , maintaining, and updating it that would be great.
Be sure to make it free and open source too.

**Comment by hustcer** [comment]
I have got a working solution: use `calibre` to convert the `epub` to `mobi`, and it's fine to read on kindle. Thanks.
