### ISSUE TITLE
_.lowerCase bug

### ISSUE THREAD

**Issue by admorphit** [lodash/lodash#2650]
```
_.lowerCase('HELLOworld')
```
yields
```
"hell oworld"
```

Expected
```
"helloworld"
```

version: 4.15.0

**Comment by jdalton** [comment]
Hi @admorphit!

You're looking for [_.toLower](https://lodash.com/docs/#toLower). The [_.lowerCase](https://lodash.com/docs/#lowerCase) method follows casing rules like `kebabCase`, `snakeCase`, or `startCase`.

**Comment by admorphit** [comment]
Thanks @jdalton, noticed after posting.
