### ISSUE TITLE
Best way to initialize an array when attempting to add a member, or append if exists

### ISSUE THREAD

**Issue by atrauzzi** [lodash/lodash#2651]
Assuming the following:

```
const state = {
}

const value = {message: "Hello!"};
```

I'm wondering if lodash has a nice concise syntax to get `state` to this point:

```
{
    messages: [
        {
            message: "Hello!"
        }
    ]
}
```

The main idea here is that `messages` needs to be an array, and if the key is `undefined`, I'd like to initialize it to an array.  If the key already exists and is an array, I'd like to `push` onto it.

I've tried searching around, but might not be using the right terminology to get the right approach.

My thought is there might be something like:

```
_.arrayPush(state, ["messages"], value);
```

**Comment by jdalton** [comment]
Hi @atrauzzi!

For these kinds of questions you should hit up our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by atrauzzi** [comment]
Done! :)

https://gitter.im/lodash/lodash?at=57dc1323c3e7045a30556c40
