### ISSUE TITLE
Do you have plan to make sortBy() and orderBy() lazy?

### ISSUE THREAD

**Issue by Tony9** [lodash/lodash#2653]
We note that ds.sortBy().slice(start, end) and ds.orderBy().slice(start, end) can be calculated effectively on large data set, which time cost is O(n), not O(nln(n)).

Using algorithm like quick sort. Please read : https://en.wikipedia.org/wiki/Selection_algorithm#Partial_selection_sort

Step 1. find the start-th, end-th smallest element; (which is O(n))
Step 2. find all element between the two elements; (also O(n))

So, Do you have plan to make sortBy() and orderBy() lazy and more effectively?
Or Do you have any other good suggestions?

Thanks!

**Comment by jdalton** [comment]
Hi @Tony9!

> Do you have plan to make sortBy() and orderBy() lazy and more effectively

No plans.

**Comment by Tony9** [comment]
Oh, what a pity!
