### ISSUE TITLE
_.multiply(0.2673, 100)=26.729999999999997

### ISSUE THREAD

**Issue by wm370857724** [lodash/lodash#2654]
_.multiply(0.2673, 100)=26.729999999999997，

**Comment by wm370857724** [comment]
![image](https://cloud.githubusercontent.com/assets/6982765/18614906/d48a7406-7dca-11e6-99f2-5739f94f53cb.png)
ng2 lodash  can't find declaration

**Comment by jdalton** [comment]
Hi @wm370857724!

We don't maintain TS or flow definitions. Gaps in them should be brought up with their maintainers.
