### ISSUE TITLE
npm ERR! Cannot find module 'lodash._baseflatten'

### ISSUE THREAD

**Issue by dbilovd** [lodash/lodash#2655]
Help needed. Don't know what happened, can no longer use npm. Throws the following error:

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save" "lodash._baseflatten"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'lodash._baseflatten'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dbilovd/Dev/Projects/ITC/tfsdd/npm-debug.log

```

I've tried ```npm i --save lodash._baseflatten``` but is also being blocked by the error.

Thanks

**Comment by jdalton** [comment]
Hi @dbilovd!

I haven't changed anything or published anything recently so it's probably an npm hiccup.
You can try clearing your `node_modules` folder and trying again.
