### ISSUE TITLE
differenceBy is not commutative

### ISSUE THREAD

**Issue by radjivC** [lodash/lodash#2656]
Hi guys,

DifferenceBy is not commutative

```js
var _ = require('lodash');
var list_a, list_b;

list_a = [{id: 1}];
list_b = [{id: 1}, {id: 2}, {id: 3}];

console.log('a', _.differenceBy(list_a, list_b, 'id'));
console.log('b', _.differenceBy(list_b, list_a, 'id'));
```
Is it a bug, or is it normal ?

**Comment by jdalton** [comment]
See the documentation for [_.differenceBy](http://lodash.com/docs#differenceBy).
>  Result values are chosen from the first array.

**Comment by radjivC** [comment]
@jdalton I still don't get it
```
a cat is different from a dog
```
in this case:
```
a cat is different from a dog, but a dog is a cat
```
and it should be:
```
a cat is different from a dog but a dog is still different from a cat
```

**Comment by erikdesjardins** [comment]
@radjivC `_.differenceBy` is set difference (anticommutative), not symmetric difference (commutative)
