### ISSUE TITLE
Is there a Lodash Function which will mask the values of provided keys ?

### ISSUE THREAD

**Issue by SameerSiddiqui** [lodash/lodash#2657]
We log our payloads so we want to mask the keys of PII and PCI related information, like SSN/PIN and so forth...

I came up with JSON.stringify solution, but wasn't able to find something like _.mask(object/array,['pin','ssn'], *)..

May be there might be a solution available combining multiple methods  ? 

Thanks,
Sameer

**Comment by jdalton** [comment]
Hi @SameerSiddiqui!

We have [_.mapKeys](https://lodash.com/docs/#mapKeys).
Don't forget to check out our [gitter chat](https://gitter.im/lodash/lodash) for help too.

**Comment by fastcodejava** [comment]
I think that he wants to leave the keys intact. he wants to only mask the values.

**Comment by jdalton** [comment]
Then [_.mapValues](https://lodash.com/docs#mapValues).

**Comment by SameerSiddiqui** [comment]
Yeah, but i just noticed. it will not handle Arrays 

_.mapKeys(object, [iteratee=_.identity])


anyPlans to make to compatible ? _.map does takes array why _.mapKeys does not ? 

Thanks,
Sameer

**Comment by jdalton** [comment]
No plans. `_.mapKeys` and `_.mapValues` are specialized for objects. `_.map` is a collection method which will iterate over array-likes and objects.

**Comment by fastcodejava** [comment]
I think the OP wants the function for a single object, with an **array of keys** to change!

**Comment by fastcodejava** [comment]
I think the OP wants the feature for a single object, with an **array of keys** to change!
