### ISSUE TITLE
Using ES6 template delimiters with _.template to evaluate expression

### ISSUE THREAD

**Issue by reaktivo** [lodash/lodash#2658]
Current implementation of _.template with ES6's style of template delimiters don't work as expected, they don't evaluate expressions. 

The following will fail:

```
_.template('hello ${ user() }')({user: () => 'marcel'})

```

I can of course set the reEsTemplate manually, but not reference it:

```
_.template('hello ${ user() }', { evaluate: /\$\{([^\\}]*(?:\\.[^\\}]*)*)\}/g } );
```

I understand the reasoning behind not exposing it in _.templateSettings, so that's why I'm asking what's a good place to expose the [reEsTemplate](https://github.com/lodash/lodash/blob/4.15.0/lodash.js#L162) pattern so we can reuse it without copying from source.

**Comment by jdalton** [comment]
Hi @reaktivo!

I can't repro in v4.15.0.
```js
_.template('hello ${ user() }')({user: () => 'marcel'})
// => "hello marcel"
```
