### ISSUE TITLE
Include lodash for testing in browser's console when viewing documentation

### ISSUE THREAD

**Issue by cchen408** [lodash/lodash#2661]
Dear Lodash Developers,

Before your most recent update, our team of engineers and I would test out lodash functions while viewing documentation through the console. This was very not only convenient for us but it also drove up the usage of your website.

We are no longer able to do so with the latest update.

Can you please include lodash in a place that we are able to access it and test out your functions in the browser's console?

Thank you!

Best,
Chris

**Comment by craigmichaelmartin** [comment]
See lodash/lodash.com#46

**Comment by cchen408** [comment]
Thank you! :)
