### ISSUE TITLE
NPM front-end

### ISSUE THREAD

**Issue by albertbuchard** [lodash/lodash#2663]
Hey everyone,

Do you have a workflow in mind for front-end dev who want to use the npm repo for lodash ?
Do we have to minify ourselves ?

Thanks

**Comment by jdalton** [comment]
Hi @albertbuchard!

The npm package contains minified versions [lodash.min.js](https://unpkg.com/lodash@4.16.1/lodash.min.js) and [core.min.js](https://unpkg.com/lodash@4.16.1/core.min.js). That said you're free to use your own minifier or bundler.
