### ISSUE TITLE
_isUndefined errors when property is undefined

### ISSUE THREAD

**Issue by beauxjames** [lodash/lodash#2665]
_.isUndefined(fooprop) errors when fooprop has never been initialized or defined, which would be the most appropriate means of testing for whether a property exists or not. 

Currently, the method is testing if 
`fooprop === undefined`
when there should be a more pojo means of testing, such as 
`typeof (fooprop) === 'undefined'`

**Comment by jfmengels** [comment]
Do you mean you get the following error?
```js
> _.isUndefined(foo)
ReferenceError: foo is not defined
   // ... stacktrace
```

That is normal JavaScript behavior, and not something that Lodash can do anything about.

**Comment by jdalton** [comment]
See #2486.
