### ISSUE TITLE
export castpath function for repeated _.get requests on same path

### ISSUE THREAD

**Issue by shreyagarwal** [lodash/lodash#2666]
Can lodash export castpath function as well?

I want to get same paths on different objects repeatedly.

Running benchmark

```
var m = { 'a' : { 'b' : { 'c' : 2 } } };

var suite = new Benchmark.Suite();
suite
.add('lodash get', function() { _.get(m, 'a.b.c', null); })
.add('native', function() { m.a.b.c; })
.add('lodash ++', function() {
var index = 0, length = 3, o = m, p = ["a", "b", "c"];
while (o != null && index < length) { o = o[p[index++]];}
o
})
```
lodash get x 2,029,091 ops/sec ±3.71% (77 runs sampled)
native access x 56,556,627 ops/sec ±6.45% (67 runs sampled)
lodash pre-compiled castpath x 20,986,649 ops/sec ±4.16% (81 runs sampled)

**Comment by jdalton** [comment]
Careful with micro benchmarks. What you think is being tested and what's actually being tested can be two different things.

As for castPath you can access it via `require('lodash/_castPath')`.

**Comment by shreyagarwal** [comment]
@jdalton 
Thanks for ```require('lodash/_castPath')``` !

I understand that the benchmarks' ops/sec can be relied upon, but the result pre casted path is faster than _.get for repeated operations on same path ( by factor of 5-10 times ) can relied upon ?
