### ISSUE TITLE
Can't get _.throttle to work

### ISSUE THREAD

**Issue by NuzumPat** [lodash/lodash#2667]
I'm using Node.Js, Express, and want to use this throttle function, but in my simple case, it does not output "Throttled" to Debug log. I'm using Node,js 4.4.7.

    $ npm i --save lodash.throttle
    $ npm install -g n_

    var _ = require('lodash');

    _.throttle(function() {
        console.log("Trottled");
    }, 100);

**Comment by jdalton** [comment]
Hi @NuzumPat!

For support questions please visit our [gitter chat](https://gitter.im/lodash/lodash).
