### ISSUE TITLE
Problem With findIndex and partial-ed startsWith

### ISSUE THREAD

**Issue by machineghost** [lodash/lodash#2668]
When I use a `partial`-ed `startsWith` with `findIndex` I get a different result from the equivalent arrow function.  In other words, if I do:

    const v1StartsWith = _.partial(_.startsWith, _, 'baz');
    const v2StartsWith = (x) => _.startsWith(x, 'baz');

    v1StartsWith('foobar'); // false
    v2StartsWith('foobar'); // false

    v1StartsWith('bazqux'); // true
    v2StartsWith('bazqux'); // true

So far so good, but when we use `_.findIndex` ...

    _.findIndex(['foobar', 'bazqux'], v1StartsWith); // -1
    _.findIndex(['foobar', 'bazqux'], v2StartsWith); // 1

Since both versions return `true`, it seems like `_.findIndex` should return `1` both times, but for some reason that's not the case with the `partial`-ed version.

**Comment by machineghost** [comment]
Never mind, just realized findIndex is getting an extra `fromIndex` arg in the broken case.

**Comment by jdalton** [comment]
Or use `lodash/fp`
```js
fp.startsWith('baz')
```

**Comment by machineghost** [comment]
I would, but I lived through the prototype.js era, and "though shalt not modify native prototypes" is a mantra that has been burned in to my brain ;)

**Comment by jdalton** [comment]
It not modifying any built-in prototypes. See more at our [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide).

**Comment by machineghost** [comment]
Oh I see (I didn't realize `fp` was like `_` in that code).

I hadn't heard about the FP project, but it seems interesting.  On the face of it it looks like I'd have to re-learn the Lodash library (in the sense of having to learn the new signatures of everything, new methods, new aliases, etc), all  just so I can `partial` less, but I'll definitely check it out and see if that opinion changes.

**Comment by jdalton** [comment]
What's great is you can cherry-pick and mix-n-match.
```js
import { findIndex } from 'lodash';
import { startsWith } from 'lodash/fp';
```
