### ISSUE TITLE
Babel transpiling issue w/ LD4, Jasmine, and Angular 1

### ISSUE THREAD

**Issue by icfantv** [lodash/lodash#2672]
We're upgrading from LD 3 to 4 and trying to update our tests.  There may be a different way to do this so we're totally game on something else.

When Babel transpiles `import * as _ from 'lodash';` it creates this:
```
'use strict';

var _lodash = require('lodash');

var _ = _interopRequireWildcard(_lodash);

function _interopRequireWildcard(obj) {
	if (obj && obj.__esModule) {
		return obj;
	} else {
		var newObj = {};
		if (obj != null) {
			for (var key in obj) {
				if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key];
			}
		}
		newObj.default = obj;
		return newObj;
	}
}
```
However, since lodash does not specify the `__esModule` property on the `_` object, it falls through to the `else` block and creates a new object every time.

One of the ramifications of this are that when we use the `import * as _ from 'lodash';` line in both our `.spec.js` file and our Angular service class, the references are different and the following `callFake` function in `spyOn` won't get executed:
```
spyOn(_, 'debounce').and.callFake(fn => (app) => {
  $timeout(fn(app));
});
```
We can confirm that adding the `__esModule` property to `_` just after the `var _ = runInContext();` line in the export section causes the error to go away but we aren't saying that this is the right solution.

What's the right way we should be solving this problem?  Thanks.

**Comment by jdalton** [comment]
The easy solution is not to use the namespace import style and use `import _ from 'lodash'` instead.

**Comment by icfantv** [comment]
@jdalton, thanks for the quick response.  We've tried that as well and it does not work.  Might it be a Webpack issue?

**Comment by jdalton** [comment]
Hmm I donno. I haven't had problems with a combo of webpack+lodash+es6.

**Comment by icfantv** [comment]
@jdalton no worries, mate.  cheers.  we'll keep playing with it.
