### ISSUE TITLE
extend own enumerable string keyed properties of target?

### ISSUE THREAD

**Issue by varun-dev** [lodash/lodash#2673]
Hi,

Is there any function to achieve the following?
```
_.func(object, [sources])
_.func({ 'a':1, 'b':2 },{ 'a':4,'c':5 })
// => { 'a': 4, 'b': 2 }
```
I only want to get new value if the destination object has that key, ignoring any new keys from sources.

Thanks

**Comment by jdalton** [comment]
Hi @varun-dev!

We have the opposite which is [_.defaults](https://lodash.com/docs/#defaults). You might be able to create a customized form with [_.assignWith](https://lodash.com/docs/#assignWith).
