### ISSUE TITLE
Lodash 4.16.1 slowed some methods

### ISSUE THREAD

**Issue by Katochimoto** [lodash/lodash#2674]
Hi.
I did not conduct a comparison of all methods.
But the example `_.sampleSize` seen a noticeable drop in performance.
Maybe it's not critical, but still.

4.16.1
https://jsbin.com/sameficoxe/edit?html,output
`lodash#sampleSize x 37.41 ops/sec ±2.65% (39 runs sampled)`

4.15.0
https://jsbin.com/koneyajexu/edit?html,output
`lodash#sampleSize x 234 ops/sec ±0.98% (59 runs sampled)`

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2871.0 Safari/537.3

**Comment by jdalton** [comment]
Thanks for the heads up.

I'll check it out. I'm not super concerned since the benchmark was clocking 1,000 iterations per sample so the actual result was something around  35,046 ops/secs for an array of 1,000 elements.

I'm marking this as invalid since it's not really a code bug

**Comment by jdalton** [comment]
All better https://jsbin.com/fihohod/1/. Patched https://github.com/lodash/lodash/commit/91064a11589483b51f1cf62cf9860ed7afe0d1c8.

**Comment by Katochimoto** [comment]
All the way, I'm over-dramatizing )
Thank you!
