### ISSUE TITLE
API proposal for _.replaceAll

### ISSUE THREAD

**Issue by mk-pmb** [lodash/lodash#2675]
Splitting from #1084 in order to suggest a specific API.

Re-considering my question about how a potential `replaceAll` method should handle search strings, I arrived at the decision that hiding a call to the RegExp constructor would be confusing, especially when there's no slot for RegExp flags. With that option discarded, I now recommmend this API:

```
_.replaceAll(what[, better[, text]])
```

  * All arguments are required, but not at the same time. If called with incomplete arguments, returns a partially pre-filled version of itself.
  * Ensure `text` is a string, or convert it to string.
  * If `what` looks RegExp-compatible, use native `text.replace`; otherwise, ensure it is a string and replace verbatim.

Example implementation:

```javascript
_.replaceAll = function replaceAll(what, better, text) {
  if (what === true) { what = this; }
  if (arguments.length < 3) {
    return Function.bind.apply(replaceAll,
      Array.prototype.concat.apply([null], arguments));
  }
  return (what.exec ? String(text).replace(what, better)
    : String(text).split(String(what)).join(better));
};

var eq = function (v, e) { if (v !== e) { throw new Error(v); } },
  checkAll = _.replaceAll('[ ]', '[x]'),
  uncheck  = _.replaceAll(/(\x5B|\x28)[x•](\x29|\x5D)/g),
  boxes =                     '[ ] yes   [ ] no   [x] really   (•) radio';
eq(checkAll(boxes),           '[x] yes   [x] no   [x] really   (•) radio');
eq(uncheck('$1 $2', boxes),   '[ ] yes   [ ] no   [ ] really   ( ) radio');
eq(uncheck('$1?$2', boxes),   '[ ] yes   [ ] no   [?] really   (?) radio');
eq(_.replaceAll('   ', ':', boxes), '[ ] yes:[ ] no:[x] really:(•) radio');
```

Depending on smartness of the VM's optimizer, it might be possible to increase performance by assuming a partially pre-filled function will be reused, do some checks and conversions upfront and return specialized functions.

**Comment by jdalton** [comment]
@mk-pmb Thanks for the walkthrough of your idea.

**Comment by mk-pmb** [comment]
Since there's no "votes needed" tag: Is this proposal eligible for votes at this stage, or only when the main thread reaches some threshold or something?
