### ISSUE TITLE
remove() is not in version 4.16.2 yet it is listed in the documentation

### ISSUE THREAD

**Issue by amahfouz** [lodash/lodash#2678]
The docs of 4.16.2 (https://lodash.com/docs/4.16.2) list a remove() function that is nowhere to be found in the core distributable file https://raw.githubusercontent.com/lodash/lodash/4.16.2/dist/lodash.core.js

The same applies to 4.16.1.

**Comment by jdalton** [comment]
Please read our wiki entry on over [build differences](https://github.com/lodash/lodash/wiki/Build-Differences).

**Comment by amahfouz** [comment]
Thanks for the quick response.
