### ISSUE TITLE
Impossible to print lodash docs

### ISSUE THREAD

**Issue by jakub-g** [lodash/lodash#2679]
When you go to a page like https://lodash.com/docs/4.16.2 it's impossible to print this page, as the browser thinks it has just 1 page to print (instead of 100+ pages)

Probably a `media="print"` stylesheet like this would do the job (removing a sidebar and `display:flex` which confuses the browsers) though I'm having troubles with building docs locally, I might try it later, but feel free to incorporate this yourselves

```
html.docs body {
  display: block !important;
}
html.docs .toc-container {
  display: none !important;
}
```

**Comment by jdalton** [comment]
Hi @jakub-g!

 Our docs repo is located at [lodash/lodash.com](https://github.com/lodash/lodash.com). Feel free to submit a PR over there. Until then you can always print our [markdown version](https://github.com/lodash/lodash/blob/4.16.2/doc/README.md).

**Comment by jdalton** [comment]
@jakub-g I added a print stylesheet https://github.com/lodash/lodash.com/commit/4c4bead884525285c3e727ca169ffe32c89e6b79.
