### ISSUE TITLE
Union fails on empty arrays?

### ISSUE THREAD

**Issue by ekryski** [lodash/lodash#2680]
I'm not sure if this is expected behavior or not but using `lodash.union` `^4.6.0` if you call it with:

```js
union([ [] ]);
```

It returns the original array `[ [] ]`. The same thing happens with multiple empty arrays as sub-arrays.

Is this expected? I was expecting it simply return `[]`.

**Comment by jdalton** [comment]
Hi @ekryski!

See the [_.union docs](https://lodash.com/docs/#union). It creates a union of the given arrays.
This method doesn't flatten values within the arrays.

**Comment by ekryski** [comment]
Ah ok cool. Thanks JD! 😄
