### ISSUE TITLE
How to access templateSettings when using module build of lodash.template?

### ISSUE THREAD

**Issue by rightaway** [lodash/lodash#2682]
The example in https://lodash.com/docs/4.16.2#template shows changing the default delimiters with

```js
// Use custom template delimiters.
_.templateSettings.interpolate = /{{([\s\S]+?)}}/g;
var compiled = _.template('hello {{ user }}!');
compiled({ 'user': 'mustache' });
// => 'hello mustache!'
```

But with the module build of it, `require('lodash.template')` only gives access to the `template` function. I can pass options into that function but is there a way to make the setting global like in this example?

**Comment by jdalton** [comment]
Hi @rightaway!

You can provide them as fields on the options object
>
```
[options.escape=_.templateSettings.escape] (RegExp): The HTML "escape" delimiter.
[options.evaluate=_.templateSettings.evaluate] (RegExp): The "evaluate" delimiter.
[options.interpolate=_.templateSettings.interpolate] (RegExp): The "interpolate" delimiter.
```

**Comment by rightaway** [comment]
Doesn't seem to work

```
import tpl from 'lodash.template'
let opts = { interpolate = /{{([\s\S]+?)}}/g }
let compiled = tpl('{{ test }}', opts)
console.log(compiled({test: 'STRING'}));
```

However this doesn't print 'STRING'

**Comment by jdalton** [comment]
It works for me when testing the snippet using cjs style.
You have  a typo in your `opts` assignment.
