### ISSUE TITLE
Differentiating split() from vanilla / proposal for explode()

### ISSUE THREAD

**Issue by dsl101** [lodash/lodash#2684]
The _very first time_ I've come across something which is easier in PHP; I have some data elements like this:

    data-identifier-12345
    data-somethingelse-56789

and the first part ('data') is the same so I want to remove them. In PHP, this can be done with:

    explode('-', string, 2)[1]  // Returns ['data', 'identifier-12345'] when limit == 2

but I couldn't find a concise JS equivalent. Would lodash consider either an `explode()` function which does the same, or, and I realise this is probably too breaky, to change the behaviour of `split()` to provide that when a limit is specified? I can't currently see the reason you'd use `_.split()` over plain `string.split()` in JS, but perhaps I missed something? Possible code (from [StackOverflow](http://stackoverflow.com/a/19034693/1454454)):

    _.explode = function(separator, limit)
    {
        var arr = this.split(separator);
        if (limit) arr.push( arr.splice(limit-1).join(separator) );
        return arr;
    }

**Comment by jdalton** [comment]
Hi @dsl101!

Our `_.split` mimics [String#split](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split).

```js
_.split('data-identifier-12345', '-', 2)
// => ["data", "identifier"]
```

Related to #2637.

**Comment by dsl101** [comment]
Erm - yes, that was my point I think. If `_.split()` and `String.split()` are effectively the same, then what does `_.split()` add?

And specifically I was after different / better functionality in that scenario...

**Comment by jdalton** [comment]
Having `split` on our API allows our chaining syntax to support it.

**Comment by dsl101** [comment]
OK - that makes sense. So, how about the 'explode' functionality, but not in `split()`. Some thoughts:

- `_.explode(string, delimiter, [limit])` - to mimic the PHP version
* `_.stringSlice(string, delimiter, [start = 0], [limit]` - to align with array slice, but allow you to slice up a string and get just the components you want

Is there somewhere specific for feature suggestions?
