### ISSUE TITLE
throttle(f, 10) calls f 3 times in < 20ms

### ISSUE THREAD

**Issue by jedwards1211** [lodash/lodash#2685]
Is this a bug or is it impossible to be precise with a 10ms wait?

```js
var throttle = require('lodash.throttle')

var f = throttle(function () {
  console.log('throttled f: ', Date.now())
}, 10)

setTimeout(f, 10)
setTimeout(f, 10)
setTimeout(f, 20)

var g = throttle(function () {
  console.log('throttled g: ', Date.now())
}, 100)

setTimeout(g, 100)
setTimeout(g, 100)
setTimeout(g, 200)
```

Outputs:
```
throttled f:  1475161405424
throttled f:  1475161405427
throttled f:  1475161405438
throttled g:  1475161405500
throttled g:  1475161405602
```
Notice that with the same timing scaled by 10 throttled g gets called one less time.

### Versions
lodash.throttle: `4.1.1`
node: `5.12.0`

Thanks!

**Comment by jdalton** [comment]
Hi @jedwards1211!

I don't believe there's a bug. Timers like `setTimeout` and `setInterval` [don't guarantee exact timings](http://ejohn.org/blog/how-javascript-timers-work/). Node may be a little funkier with their timings.
