### ISSUE TITLE
What is the recommended way to handle "this" using fp?

### ISSUE THREAD

**Issue by musicalshore** [lodash/lodash#2688]
Some days, you just can't get rid of mutations. In our Knockout ecosystem, there's no getting around mutating `this` without significantly altering our architecture. With core lodash, we'd keep things neat and tidy using `_.extend(this, { .. })`. Since fp doesn't mutate, it doesn't look like we can keep using this pattern without using `convert`.

**Comment by jdalton** [comment]
Hi @musicalshore!

If you'd like you could cherry-pick a bit of both:
```js
var extend = require('lodash/extend');
var chunk = require('lodash/fp/chunk');
```
or you could overwrite references:
```js
this.options = extend(this.options, { ... });
```
