### ISSUE TITLE
npm publish individual methods.

### ISSUE THREAD

**Issue by mikeal** [lodash/lodash#269]
I've come across this a few times now.

I'd really love to depend on `lodash.clone` in a few modules rather than pulling in all of lodash everytime. It would be great if builds of the individual methods were published to npm so that people could depend on just one or two.

I'm sure this could all be automated. If anyone is squatting on a name that begins with "lodash." I'm sure we can get isaacs to remove it.

**Comment by afraser** [comment]
@jdalton Any chance I can get a look at the code you wrote to do this?

I'm looking at your package.json and I see: 
`"build:main-modules": "node lib/main/build-modules.js"`
...which looks like what I want.

I'm working on a component library and would like to publish each component individually when they are updated as well as the entire library. On the surface this seems like a simple thing to do but I suspect it's easier said than done. : ]
