### ISSUE TITLE
isEmpty() doesn't work with Error objects

### ISSUE THREAD

**Issue by UnsungHero97** [lodash/lodash#2690]
I'm invoking `_.isEmpty()` on an `Error` object, and it is returning `true`, but I expect it to return `false`. Why is this?

<img width="639" alt="screen shot 2016-09-29 at 5 28 31 pm" src="https://cloud.githubusercontent.com/assets/440299/18976871/51132750-866a-11e6-862d-9f70fffcb3bd.png">

**Comment by jdalton** [comment]
Hi @UnsungHero97!

The key is that the [_.isEmpty](https://lodash.com/docs/#isEmpty) method looks for own-enumerable properties. If it doesn't find them it considers the collection empty.

**Comment by UnsungHero97** [comment]
Hey @jdalton, thanks for the quick response!

I think I understand how `_.isEmpty()` works, but I still think it's incorrectly returning `true` for an `Error` object. Take this example:

<img width="1485" alt="screen shot 2016-09-29 at 5 51 41 pm" src="https://cloud.githubusercontent.com/assets/440299/18977272/b4e11938-866d-11e6-951d-25ddfb7b1577.png">

`ReferenceError` has at least `message` on its prototype. What am I missing here?

**Comment by jdalton** [comment]
The it's either missing the own or enumerable bit.
If the result of the following is `[]` that would explain it.
```js
console.log(Object.keys(e));
```

**Comment by UnsungHero97** [comment]
Correct. `Object.keys(e)` does return `[]`, but `Object.getOwnPropertyNames(e)` returns `["stack", "message"]`. Is that not good enough?

**Comment by jdalton** [comment]
`Object.getOwnPropertyNames` returns all own properties *(even those that are non-enumerable)*.

**Comment by UnsungHero97** [comment]
ok, thanks! I'll just have to use `_.isError()` :)
