### ISSUE TITLE
Lodash migrating guide does not mention absense of _.all method

### ISSUE THREAD

**Issue by akoshelev** [lodash/lodash#2691]
Hi @jdalton,

I am currently migrating some quite old project from Underscore to Lodash using the migration guide (which is quite awesome, thanks for your work!) from [wiki](https://github.com/lodash/lodash/wiki/Migrating). 
Currently I am getting type errors stating that `_.all` function is not available and it seems the guide does not say anything about it.
Do you think it's worth mentioning that there is no such method in Lodash and devs should use `_.every` instead?

**Comment by jdalton** [comment]
Hi @akoshelev!

You should check out [eslint-plugin-lodash](https://www.npmjs.com/package/eslint-plugin-lodash) for a more thorough check. I'll add a note that the list is not exhaustive.
