### ISSUE TITLE
_.remove doesn't remove falsy values

### ISSUE THREAD

**Issue by thunghan** [lodash/lodash#2692]
Hi there, according to the 4.16.2 docs, the function signature for `_.remove` is

`_.remove(array, [predicate=_.identity])`

..so I expected the following:

```
var x = [1, 0, 1, 2, 3, 4, 0, -1, -5];
var y = _.remove(x);
// y contains [1, 0, 1, 2, 3, 4, 0, -1, -5]
// x contains []
```

but instead, I get:

```
var x = [1, 0, 1, 2, 3, 4, 0, -1, -5];
var y = _.remove(x);
// y contains [1, 1, 2, 3, 4, -1, -5]
// x contains [0, 0]
```

Is this a bug?

**Comment by jdalton** [comment]
Hi @thunghan!

The default predicate is [_.identity](https://lodash.com/docs#identity) which means the values are passed thru. Since falsey values are falsey they fail the predicate and are not removed.
