### ISSUE TITLE
fp/transform with objects

### ISSUE THREAD

**Issue by mpneuried** [lodash/lodash#2693]
if i use the functional transform method with an object the thrid key argument is missing.

Here a running example: https://runkit.com/mpneuried/57ee4372751b541400b39472

```js
let transform = require("lodash/transform")
let transformFp = require("lodash/fp/transform")

// a collection to convert
var coll = {
    foo: { val: 13 }, 
    bar: { val: 42 }, 
    buzz: { val: 23 }
}

// transform with regular method
transform( coll, function ( acc, val, key ){
    val.key = key
    acc.push( val )
}, [] )

// transform with fp version
transformFp( function ( acc, val, key ){
    val.key = key

    // ####################
    // #  key is undefined !!
    // ####################

    acc.push( val )
}, [] )( coll )

**Comment by Archimidis** [comment]
The answer lies [in the docs](https://github.com/lodash/lodash/wiki/FP-Guide#capped-iteratee-arguments)

**Comment by mpneuried** [comment]
Thanks for the fast answer!
OK ... sorry, that i missed that!
Is there a plan to change this, so the fp methods are equal to teh regular?

**Comment by jdalton** [comment]
Hi @mpneuried!

The capped iteratee args is actually a feature of the FP wrapper.
That said, you can customize it with [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert).
