### ISSUE TITLE
lodash/fp in browser does not handle lodash having been called with `noConflict`

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash#2694]
These lines check if `_` is a function, but should really check if it is actually a lodash instance:
https://github.com/lodash/lodash/blob/master/fp/_convertBrowser.js#L15-L17

In our case we still (unfortunately) have some legacy code that needs underscore - we call lodash with noConflict but some code requires underscore to be global. We're working to rip it out completely, but ideally the check here would either be stricter or support some way of opting out of the automatic check (even if it's wrapped in an `if (!window.dontAutoFP)` or something that we can set before the script loads)

**Comment by jdalton** [comment]
Thanks for the heads up!

**Comment by daedalus28** [comment]
You replied and fixed it within _12_ minutes - awesome! Any idea when the next release with this will be? It's affecting some stuff we have in production.

**Comment by jdalton** [comment]
Probably Sunday.
