### ISSUE TITLE
throttleUntilParamsChange function

### ISSUE THREAD

**Issue by vaukalak** [lodash/lodash#2696]
Sorry if was already discussed, but I didn't find that. There a lot of situations when we have to write ugly code like that:
```
if (value != this.value) {
  this.value = value;
  valueChanged(value);
}
```
This forces state introduction, which is sad. I think a function named `throttleUntilParamsChange` or something like that could be added to lodash. Toy implementation would look like:
```
const throttleUntilParamsChange = cb => params => {
  let latestParams = undefined;
  if (_.isEqual(latestParams, params)) {
    latestParams = params;
    return cb(...params);
  }
};
```

So we could write that code better:
```
const valueChangedCallback = _.throttleUntilParamsChange(valueChanged);
valueChangedCallback(1); //invoked
valueChangedCallback(1); //not invoked
valueChangedCallback(2); //invoked
valueChangedCallback(1); //invoked
```

**Comment by jdalton** [comment]
Hi @vaukalak!

Thanks for the suggestion. I think this is better suited as a mixin.
