### ISSUE TITLE
Migration to ESLint

### ISSUE THREAD

**Issue by gyandeeps** [lodash/lodash#2697]
Since [JSCS is no longer supported](http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint), @jdalton would their be any interest to migrate over to ESLint?

If Yes, then I would be happy to do the work. Wanted to know before doing the work.

**Comment by jdalton** [comment]
Thanks for the offer @gyandeeps!

I'm aware they've merged but I'm still happy with JSCS for now. When the time comes that JSCS causes me grief then I'll re-evaluate.
