### ISSUE TITLE
startCase does not format correctly if string contains a number

### ISSUE THREAD

**Issue by despreston** [lodash/lodash#2698]
_.startCase('test_test1hello') should be "Test Test1hello" but it is being converted to "Test Test 1 Hello"

**Comment by jdalton** [comment]
Hi @despreston!

Handling numbers gets a bit tricky.
You can see by using [_.words](https://lodash.com/docs/#words) that Lodash treats it as a separate word group:
```js
_.words('test_test1hello');
// => ["test", "test", "1", "hello"]
```
