### ISSUE TITLE
[fp] Expose placeholder as a module

### ISSUE THREAD

**Issue by Andarist** [lodash/lodash#2700]
Would be nice to be able to import just a placeholder, while using a module bundler it's undesirable to import whole `lodash` just to get a placeholder reference.

More about the problem here - jfmengels/eslint-plugin-lodash-fp#40

**Comment by jdalton** [comment]
Hi @Andarist!

You can import just [the placeholder](https://github.com/lodash/lodash/blob/npm/fp/__.js) with:
```js
const ph = require('lodash/fp/__');
// or
const ph = require('lodash/fp/placeholder');
```

**Comment by jdalton** [comment]
Each curried function itself also has a `placeholder` property on it
```js
const map = require('lodash/fp/map');
console.log(map.placeholder);
// => {}
