### ISSUE TITLE
lodash.assign deprecated?

### ISSUE THREAD

**Issue by IgorAufricht** [lodash/lodash#2701]
After installing the `lodash.assign` package there is a deprecation warning:

```
$ npm install lodash.assign
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
C:\dev\tmp
`-- lodash.assign@4.2.0
```

Is this by design or is this a mistake?
* The deprecation is not mentioned in the [lodash docs](https://lodash.com/docs/4.16.3#assign) nor in the [package's readme](https://github.com/lodash/lodash/tree/4.2.0-npm-packages/lodash.assign).
* The deprecation message suggests using [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign), which seems to not be supported in IE, so it can't be used as a replacement yet.

**Comment by megawac** [comment]
https://twitter.com/jdalton/status/779735179636137985

**Comment by jdalton** [comment]
Hi @IgorAufricht!

Not a mistake. For the individual package it makes more sense to use `Object.assign` when writing code for Node 4 and 6.
