### ISSUE TITLE
Breaking change in _.merge for a patch release (4.16.2 to 4.16.3)?

### ISSUE THREAD

**Issue by kunagpal** [lodash/lodash#2702]
**4.16.2**
```javascript
_.merge({}, { a: undefined }); // {}
```

**4.16.3**
```javascript
_.merge({}, { a: undefined }); // { a: undefined }
```

Is this expected behaviour?

**Comment by AlexChesters** [comment]
We've also spotted this and have had to lock down to `4.16.2` 😞

**Comment by shamasis** [comment]
This is a hugely breaking change for a `patch`. And would consequently break a lot of packages depending on it. Many will not even know until real-world use case is encountered.

cc @jdalton

**Comment by jdalton** [comment]
Hi @kunagpal!

Yep, this is expected behavior and a correction of regressed behavior.

There was even a v4 (Jan. 12) changelog entry for it
> Enabled _.merge to assign undefined if the destination property doesn’t exist


Related to #2676 and #1956.

**Comment by shamasis** [comment]
@jdalton - As per what I can observe, the behaviour was similar to `v4.16.2` in loads v3 as well (v3.10.1 to be precise.) No disrespect, but it seems like a forced classification as regression. The cost of dependency on loadash with such core behaviour change is creeping up a lot.

**Comment by jdalton** [comment]
The `v4.16.2` behavior was a bug. You were relying on undocumented behavior. The current `v4.16.13`+ way aligns with `_.assign`, `_.assignIn`, `_.defaults`, & `_.defaultsDeep`. And is more consistent with `_.merge` itself as the [changelog example](https://github.com/lodash/lodash/wiki/Changelog/7d6efa7eb2171629f07309506af0873f75b0c67e) showed.
