### ISSUE TITLE
toBoolean/isBoolean revisted & all-in-one parse

### ISSUE THREAD

**Issue by GreenPioneer** [lodash/lodash#2703]
Part in reference to this issue i created before #2065 

Hey @jdalton ,

I know more than likely this is gonna stay a mixin but i wanted to see if you could talk a look and the fiddle and see if thats the best way to do it or is it something you might be interested in for lodash. Any thoughts or critiques would be much appreciated

my use case  has evolved a little now but basically still is the same premises . i need to really take anything the user sends me wether it is a string || boolean || number then i need to parse it for what it is so that i can then use it .for example you will see below the console log the `' TrUe'`. if some user for what ever reason enters that i need to figure out that is should be true(boolean) not just a string.

[JsFiddle Example](https://jsfiddle.net/greenpioneer/4y744xyd/)

EX.
``` Javascript
// parse = 'Green Pioneer'
console.log(_.parse('Green Pioneer'), '- String') 
// parse =  26
console.log(_.parse('26'), '- Number')
// parse = 26
console.log(_.parse(26), '- Number')
// parse = true
console.log(_.parse(true), '- Boolean')
// parse = true
console.log(_.parse('TrUe '), '- Boolean')
```
 
Check it out let me know

GP

**Comment by GreenPioneer** [comment]
@jfmengels @StreetStrider let me know your thoughts if you guys have the time

**Comment by jdalton** [comment]
Hi @GreenPioneer!

I think this still is categorized as a dup of #2065.
I still think it's better as a [mixin](https://lodash.com/docs/#mixin).

**Comment by StreetStrider** [comment]
@GreenPioneer I my practice there're two solutions I usually use:
1. Simple «hand-made» parsers, which are stupid as `Number(x)` or `Boolean(x)`. In most of the cases they are sufficient, and they are both reliable and bug-proof.
2. If I need complex parsing I defer to `JSON.parse` which works with very strict subset of JS-types  thus it is robust and bug-proof approach too. (I can apply validations/transformations after, if needed)
Sometimes (2) is a code smell of overengineering, so I usually try to decompose my arch into such simple entities so it can be described in terms of (1).
