### ISSUE TITLE
Symbol.toStringTag may fool isPlainObject()

### ISSUE THREAD

**Issue by trevnorris** [lodash/lodash#2705]
If a normally plain object with `Symbol.toStringTag` set is considered a plain object, it's currently fooled by `isPlainObject()`. Example:
```js
var o = {};
o[Symbol.toStringTag] = 'Foo';
Object.prototype.toString.call(o) === '[object Foo]';
```

**Comment by jdalton** [comment]
Hey @trevnorris!

We usually don't try to get around folks using `Symbol.toStringTag`.
For example folks can do:
```js
var o = { [Symbol.toStringTag]: 'Date' }
_.isDate(o);
// => true
```

Is there a use case were this is causing problems?

**Comment by jdalton** [comment]
I'm leaning towards being OK with objects with custom `Symbol.toStringTag` being treated as non-plain. For example `arugments` objects, error objects, etc are not considered plain objects.

**Comment by jdalton** [comment]
@trevnorris ping
> Is there a use case where this is causing problems?

**Comment by trevnorris** [comment]
@jdalton Cool. That was the same approach I took. Thanks.

**Comment by jdalton** [comment]
I later moved it's own helper `getRawTag` since I have to wrap it in a try-catch. Built-ins like typed arrays, data views, and others have read-only `Symbol.toStringTag` values which will throw in strict mode.

**Comment by not-an-aardvark** [comment]
For what it's worth, this can still be fooled by adding a getter for `Symbol.toStringTag`:

```js
// (running latest master, e7ddcad)

_.isPlainObject({get [Symbol.toStringTag]() { return 'Foo'; }})
// => false
```

I don't think it's possible to account for all cases like this (e.g. a Proxy could spoof all of its observable properties to look like a non-plain object). But I think it's worth noting that cases like this exist.

**Comment by jdalton** [comment]
@not-an-aardvark Yap, though as long as it's configurable I could muck with it I guess.

**Comment by jdalton** [comment]
I don't think we're trying to be super robust here. I just want to make sure there's communication in case there is a Node issue since @trevnorris is reporting.

**Comment by jdalton** [comment]
I have a sneaky suspicion there's some investigation or discussion going on related to this that I'm not aware of.

**Comment by not-an-aardvark** [comment]
No, this isn't related to a Node issue as far as I know -- I just happened to be looking at the Lodash issue list.

**Comment by jdalton** [comment]
Ok 😎 !

**Comment by jdalton** [comment]
Just to be clear though. If there was something Node folks needed. Just give me the word.

**Comment by trevnorris** [comment]
nothing needed here. just happened upon this while i was writing tests for another library.
