### ISSUE TITLE
Ensure the individual npm packages won't be deprecated

### ISSUE THREAD

**Issue by phated** [lodash/lodash#2706]
It's understandable (and I'm fine with) not shipping lodash 5.0 stuff as individual npm packages; however, I think the 4.x npm packages will be stable and good for many people's usage.  We plan to continue to use them into the gulp 4 release.

Will you commit to not adding `npm deprecate` messages to those packages?

**Comment by jdalton** [comment]
Sure! I'll commit to making gulp a gab free experience. While we may deprecate packages if it's causing the good gulp users grief we'll keep it ghostly quiet.
