### ISSUE TITLE
Breaking changes in _.merge 4.16.2 -> 4.16.3

### ISSUE THREAD

**Issue by eastlondoner** [lodash/lodash#2707]
https://github.com/oleksiyk/kafka/issues/124

**Comment by jdalton** [comment]
Dup of #2699.

**Comment by eastlondoner** [comment]
> smallBuffer = new Buffer(2)
<Buffer 58 7d>
> abomination = lo.merge({},{a:smallBuffer})
{ a: <Buffer 00 00 00 00 00 00 00 00 00 20 00 00 00 00 00 00 50 2d 30 01 01 00 00 00 50 6c 04 02 01 00 00 00 0a 00 00 00 00 00 00 00 78 6c 04 02 01 00 00 00 05 00 ... > }
> abomination.a.length
8192
> smallBuffer.length
2
>

**Comment by eastlondoner** [comment]
ah, sorry you're right. I will shut up
