### ISSUE TITLE
Bug in fp _.map(_.flow(_.toPairs, _.reduce))

### ISSUE THREAD

**Issue by code-guru** [lodash/lodash#2709]
Having the code below, 
expected result was:
```
   [ { '1': 0.7682942721240236,
    '2': 0.496076636651156,
    '3': 0.06455059653771134},
  { '4': 0.7301202809536087,
    '5': 0.8767494201616899,
    '6': 0.8276803825486887 } ]
```
But the returned result is:
```
[ { '1': 0.7682942721240236,
    '2': 0.496076636651156,
    '3': 0.06455059653771134,
    '4': 0.7301202809536087,
    '5': 0.8767494201616899,
    '6': 0.8276803825486887 },
  { '1': 0.7682942721240236,
    '2': 0.496076636651156,
    '3': 0.06455059653771134,
    '4': 0.7301202809536087,
    '5': 0.8767494201616899,
    '6': 0.8276803825486887 } ]
```
```javascript
_.map(
        _.flow(
                _.toPairs,
                _.reduce((acc, pair) => {
                    acc[pair[1]] = Math.random();
                    return acc;
                }, {})
        )
)([[1, 2, 3], [4, 5, 6]]);
```

**Comment by chigia001** [comment]
@code-guru I think this is the correct solution for your code.
`
_.map(
        _.flow(
                _.toPairs,
                _.reduce((acc, pair) => {
                    acc = _.clone(acc);
                    acc[pair[1]] = Math.random();
                    return acc;
                }, {})
        )
)([[1, 2, 3], [4, 5, 6]]));
`

**Comment by code-guru** [comment]
@chigia001, I knew the bug is that it mutate the parent map function data. Using _.clone is not a solution, it is a lazy fix to make it work. It should be fixed in lodash, that does not mutate map iterations.

**Comment by chigia001** [comment]
Map does not mutate anything.
The problem is
'''
_.flow(
                _.toPairs,
                _.reduce((acc, pair) => {
                    acc[pair[1]] = Math.random();
                    return acc;
                }, {})
        )
'''
This block of code return the same object every time it run, because the initial object for reduce is the same. The only code mutate object is
'
acc[pair[1]] = Math.random();
'

**Comment by code-guru** [comment]
After changing your solution from _.clone to _.set, it is more acceptable, definitely it is a solution, and a good one. 
My argument is there are 2 reduce function executions, with their own initial value set to empty object acc = {}. There is no reason that the resulting acc is passed on to the second reduce.
In functional programming reduce does not have any side effect.

I am very keen on getting the opinion of John-David on this.

**Comment by chigia001** [comment]
Let me rewrite you code to make my point clear:
Your code is equivalence to this code:
```
var initialReduceObject = {};

var result = [_.flow(
	_.toPairs,
	_.reduce((acc, pair) => {
		acc[pair[1]] = Math.random();
		return acc;
	}, initialReduceObject)
)([1, 2, 3]),
_.flow(
	_.toPairs,
	_.reduce((acc, pair) => {
		acc[pair[1]] = Math.random();
		return acc;
	}, initialReduceObject)
)([4, 5, 6])];
```
Do you see for both _.reduce function using the same initial object. This is what happen in your code.
The statement _.reduce(function() {}, new Object()) only run 1(the statment in the function block may be run more than one) So the intial object for the _.reduce statement is the same object.

**Comment by code-guru** [comment]
That is not rewrite of my code, at least I did not mean that. That is what happens inside Lodash, that is wrong, cause the problem, and should be fixed.

**Comment by chigia001** [comment]
I will add one piece of code to your original code
```
_.map(
        _.flow(
                _.toPairs,
                _.reduce((acc, pair) => {
                	acc[pair[1]] = Math.random();
                  return acc;
                }, {id : _.uniqueId()})
        )
)([[1, 2, 3], [4, 5, 6]])
```
How many time do you expect the _.uniqueId() will be run?

**Comment by code-guru** [comment]
In my example there should "two" completely separated reduce operation (as we map an array of two items), in which reduce operations should not share "accumulator". 

Although I appreciated your answers and solutions, but I did not opened this issues as a question, this is a bug report for the project maintainers. If this is not a bug, they can close it. Thanks again for trying to help.
