### ISSUE TITLE
Any object with name && message fields is considered an error?

### ISSUE THREAD

**Issue by JCarran0** [lodash/lodash#2710]
This doesn't seem right to me and has been causing me some headaches:

```
 var _ = require('lodash');

  var obj = {
    name: 'jared',
    message: 'I am a message'
  };

  _.isError(obj); //true
```

**Comment by jdalton** [comment]
Hi @JCarran0!

Yes. The `_.isError` checks for values with a `toStringTag` of `Error` as well as those with both a `name` and `message` property to allow for custom error objects.

**Comment by jdalton** [comment]
Related to #1994.
