### ISSUE TITLE
Invalid `exports` entry passed: es & commonjs

### ISSUE THREAD

**Issue by anodynos** [lodash/lodash#2712]
In `lodash` / `lodash-cli` version `4.16.4` when I use 

```lodash exports=es``` 

I get 

```Invalid `exports` entry passed: es```

Same for `commonjs`

```Invalid `exports` entry passed: commonjs```

either when used alone or independently.

*UPDATE* Docs say `The exports values “es” & “npm” may only be used in conjunction with the modularize command`, and in fact `modularize` & `es`work (this message could be part of the error meesage). The commonjs is not working with or wihtout `modularize`.

**Comment by jdalton** [comment]
Hi @anodynos!

Glad you worked it out. If you have `lodash-cli` issues or questions in the future you can post them to its repo https://github.com/lodash/lodash-cli/issues.

**Comment by harshes53** [comment]
@jdalton there isn't `issues` tab present at [lodash-cli repo](https://github.com/lodash/lodash-cli/)

I am trying to build ES modules by doing: 

`lodash modularize exports=es -o ./node_modules/lodash-es`

Good thing is there are modules exported in the `node_modules/lodash-es` directory, BUT the process does not exit at all..

Any suggestions? 

Thanks!

**Comment by jdalton** [comment]
Hi @harshes53!

You can use [lodash-es](https://www.npmjs.com/package/lodash-es) instead.

**Comment by harshes53** [comment]
@jdalton thanks, I am using it in my project but somehow it isn't doing what it is suppose to do.. tree-shaking! I have a webpack driven project(not using babel anyplace to transpile), some how when importing selected modules like below, it imports lot more along with it in the build.
```
import find from 'lodash-es/find'
import findIndex from 'lodash-es/findIndex'
import take from 'lodash-es/take'
import pick from 'lodash-es/pick'
```

any suggestion to make tree shaking work without using `babel-plugin-lodash` & `lodash-webpack-plugin`?? thanks!

**Comment by jdalton** [comment]
The promise by tools of tree-shaking was a bit of an oversell. It turns out in practice many of them are too conservative and see side-effects, that prevent tree-shaking, where there are none. This is why Webpack has proposed a "pure" module field to provide a hint to it. Until then you'll need to manually cherry-pick has your input example or just the babel plugin to do it for you.
