### ISSUE TITLE
.every function keeps checking values in list after falsey values

### ISSUE THREAD

**Issue by robinrob** [lodash/lodash#2713]
The following code:
```
var _ = require('lodash')
a = null
b = [!_.isNil(a), a.b]
```

Produces this error:
```
TypeError: Cannot read property 'b' of null
```

I'd expect it to just stop after realising that the first value is `false`.

**Comment by Archimidis** [comment]
This is how js evaluates expressions. You are getting this error because it will first evaluate both expressions inside the array in order to construct the array and then assign it to b.
What you probably want is the following:

`const b = !_.isNill(a) && a.b`

**Comment by robinrob** [comment]
Ah thanks, yeah you're right, pretty obvious. The reason i was doing it that way was to find a neater way of doing the && condition.

**Comment by StreetStrider** [comment]
@robinrob, ye, the rule of thumb here is that JS is not lazy. It will evaluate all function's arguments or all array items due construction. `||` however, is lazy by its nature (and historical, etc..). Funny thing that in Lisp lists are not lazy too, but you can achieve lazyness by quoting and defining macroses. JS does not have such mechanisms, in JS it can be slightly achieved by creating functions (neat: arrows) and evaluate them on demand (and it is obviously not shorter than `||`).
