### ISSUE TITLE
Feature request: return function from chain when no initial value passed

### ISSUE THREAD

**Issue by dbkaplun** [lodash/lodash#2715]
Here's what I'm proposing:
```js
> let squareEvens = _()
  .filter(n => n%2 == 0)
  .map(n => n*n)
  .toFunction();
> squareEvens([1, 2, 3, 4]);
[2, 4]
```

**Comment by jdalton** [comment]
Thanks @dbkaplun!

Under the hood our [_.flow](https://lodash.com/docs/#flow) and [_.flowRight](https://lodash.com/docs/#flowRight) methods use a chain sequence.
I could see this as a way to convert a sequence into a composed function, which is pretty cool!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
