### ISSUE TITLE
Feature request:  _.toObject() to convert array to object

### ISSUE THREAD

**Issue by BlueRaja** [lodash/lodash#2718]
Converting a collection of objects to key/value pairs is a common problem.  For example:

* [This Stackoverflow question](http://stackoverflow.com/questions/10416424/underscore-js-create-a-map-out-of-list-of-objects-using-a-key-found-in-the-obje) has 36,000 views
* [This CodeReview.SE question](http://codereview.stackexchange.com/questions/57614/convert-object-array-to-hash-map-using-lodash) has over 50,000 views

The most common solution, which I see _all the time_, looks like this:

```
inputs.reduce((returnObj, input) => {
  returnObj[keyFunc(input)] = valFunc(input);
  return returnObj;
}, {});
```

You can clean this up a bit using spread syntax:

```
inputs.reduce((returnObj, input) => ({ ...returnObj, [keyFunc(input)]: valFunc(input) }), {});
```

There are also multiple clean-ish ways to do it using lodash:

```
_.zipObject(inputs.map(keyFunc), inputs.map(valFunc));
_.fromPairs(inputs.map(input => [keyFunc(input), valFunc(input)]));
```

I think this problem is common enough that it should have its own function.  It would be nice to just be able to do

```
_.toObject(inputs, keyFunc, valFunc);
```

Note that we already have something similar, `_.keyBy`, but `keyBy` is less generic:

```
_.keyBy = (array, keyFunc) => _.toObject(array, keyFunc, val => val);
```

Like `keyBy`, we should allow`_.toObject` to take strings as shorthand.

**Comment by BlueRaja** [comment]
Er, why do you consider this 'invalid'?

**Comment by jdalton** [comment]
Hi @BlueRaja!

> Converting a collection of objects to key/value pairs is a common problem. 

Yes and...

> There are also multiple clean-ish ways to do it using lodash:

Yes.

> I think this problem is common enough that it should have its own function. It would be nice to just be able to do

I don't know about that but we'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by BlueRaja** [comment]
I've added examples + additional arguments to the post.

Additionally, I'd like to point out that `_.keyBy` already exists, but is less useful than `_.toObject`.  `_.keyBy(array, key)` is equivalent to `_.toObject(array, key, val => val)`.  Both take about the same mental effort to grok, but `_.keyBy` cannot be used to solve the examples in the above post.

**Comment by thorn0** [comment]
In .NET, [`System.LINQ.Enumerable.ToDictionary`](https://msdn.microsoft.com/en-us/library/system.linq.enumerable.todictionary(v=vs.110).aspx) works just like described here. It's much more readable than any "current best solution" written above and on SO.

**Comment by BlueRaja** [comment]
I seem to run into a problem at least once a week that would benefit from `toObject()`.  Here is one [from today](http://stackoverflow.com/a/40533888/238419):  sorting the keys in an object _(for eg. cleaner JSON output - yes, [keys are ordered](http://stackoverflow.com/a/31102605/238419))_

Current best solution:
```
_.fromPairs(_.keys(obj).sort().map(key => [key, obj[key]]));
```
With `toObject()`:
```
_.toObject(_.keys(obj).sort(), key => key, key => obj[key]);
```

**Comment by jdalton** [comment]
```js
_.keys(obj).sort().reduce((o, k) => (o[k] = obj[key], o))
```

**Comment by BlueRaja** [comment]
@jdalton The code you posted does not work, because the initial value of `accumulator` is the first value passed to `reduce`.  You can fix it by changing it to
```
_.keys(obj).sort().reduce((o, k) => (o[k] = obj[k], o), {})
```
However this only further justifies my point: if the author of lodash itself can't get it right on the first try, it's clear the existing options are too complex.

**Comment by jshado1** [comment]
`_.toObject` does not appear to be in lodash anymore—looks like it was too convenient ☹️

**Comment by jlutzhbo** [comment]
@jdalton @BlueRaja How many 👍  are you looking for until this is deemed popular enough to merit inclusion into the library? I look for this feature a lot, and I was somewhat surprised Lodash doesn't support it.

**Comment by vieiralucas** [comment]
If I understand correctly the issue I believe you can use [_.keyBy](https://lodash.com/docs/4.17.4#keyBy) or [_.groupBy](https://lodash.com/docs/4.17.4#groupBy).

**Comment by BlueRaja** [comment]
@vieiralucas You cannot.  `keyBy` is a less powerful version of `toObject` (you cannot map to a different value), and `groupBy` is unrelated.

**Comment by BlueRaja** [comment]
@vieiralucas You cannot.  `keyBy` is a less powerful version of `toObject` (you cannot map to a different value), and `groupBy` is unrelated.

@jdalton Out of curiosity, how many upvotes are necessary before this will be considered?

**Comment by jdalton** [comment]
> Out of curiosity, how many upvotes are necessary before this will be considered

There is no set number. Upvotes are used as an indicator for future module additions.

**Comment by kamikazechaser** [comment]
This should be a feature for lodash.

**Comment by BlueRaja** [comment]
Not sure why my previous comment was deleted, but:  that's incorrect.  `_.keyBy` is a less powerful version of `_.toObject()` _(it can only map to keys, not values)_, and `_.groupBy` is simply unrelated.

**Comment by xuantai** [comment]
Can somebody help me how to get the output
//Desired output
[
  {
    'name1': { key: '1', val: 'a' },
  },
  {
    'name1': { key: '2', val: 'b' },
  },
  {
    'name1': { key: '3', val: 'c' },
  }
]

from the input 
[
    { key: '1', val: 'a' },
    { key: '2', val: 'b' },
    { key: '3', val: 'c' }
]
using lodash, thank you

**Comment by jdalton** [comment]
> Can somebody help me

Head over to our [support chat](https://gitter.im/lodash/lodash).

**Comment by iddan** [comment]
Seems pretty popular..

**Comment by tauren** [comment]
Take a look at [keyBy](https://lodash.com/docs/4.17.4#keyBy)

**Comment by NetoriaN** [comment]
Seems pretty popular!

**Comment by GuillaumeLeclerc** [comment]
I think so too. It's very frustrating when coming from python since this is just basically a dict comprehension:

```
{x: f(x) for x in obj}
```

**Comment by ephetic** [comment]
Would this not be close enough to your python example (without native JS support for comprehensions)?

```
_.fromPairs(_.map(obj, x => [x, f(x)]));
```

**Comment by iddan** [comment]
This is ugly :(

**Comment by ephetic** [comment]
And the proposed 
```
_.toObject(obj, x => x, x => f(x));
```
wouldn't be?

**Comment by GuillaumeLeclerc** [comment]
I think the use case when you want to map the key is way less common (in my python example, i'm not doing it).

so it would more look like this:

```javascript
_.toObject(keys, f)
```

**Comment by ephetic** [comment]
Where `f` is implicitly mapped across `items` to generate pairs? I like the explicit version better. /opinion

**Comment by GuillaumeLeclerc** [comment]
I don't really see anything implicit here.

With only two arguments for the `toObject` function, it would be equivalent to:

```javascript
_.toObject(inputs, valFunc);
_.zipObject(inputs, inputs.map(valFunc));
```

To be entirely fair this might not be worth a new function in lodash...

However it just sounds more readable to me.

**Comment by BlueRaja** [comment]
Actually I think the case where you only want to map the key is more common.  That is probably why there's already a lodash function for it - [keyBy](https://lodash.com/docs/4.17.4#keyBy).  However, I need to map the value or both often enough _(about once a week since I made this request)_ that I still think `toObject` would be extremely useful.

I definitely _don't_ like the idea of only mapping the value.  In that case it'd make more sense to call it `valueBy()`, but a `toObject()` function would already fill that niche, _and_ be more powerful.

**Comment by GuillaumeLeclerc** [comment]
I actually need to map the values in my case, not the key. But I support your point of view

**Comment by dpikt** [comment]
You could combine the key and value iterators by having the iteratee return an object that's merged into the result object, eg:
```
//Input
[
    { key: '1', val: 'a' },
    { key: '2', val: 'b' },
    { key: '3', val: 'c' }
]

_.toObject(input, i => ({ [i.key]: i.value }));
```
This is equivalent to `merge(...map(collection, iteratee))`.
The only issue is that it relies on the ES6 `ComputedPropertyName` to really be useful.

**Comment by farhansalam** [comment]
You can use lodash [keyBy](https://lodash.com/docs/4.17.4#keyBy)

```javascript
//Input
[
    { key: '1', val: 'a' },
    { key: '2', val: 'b' },
    { key: '3', val: 'c' }
]

_.keyBy(input, 'key');

//=> {1: { key: '1', val: 'a' }, 2: { key: '2', val: 'b' }, 3: { key: '3', val: 'c' }}
```

**Comment by virtual-marat** [comment]
+1

**Comment by rickyk586** [comment]
I ended up using this:
```
function toObject(arr, keyPath, valuePath){
	return _.fromPairs(_.map(arr, i => [_.get(i, keyPath), _.get(i, valuePath)]));
}
```

**Comment by davidsonsns** [comment]
I solved this way

```js
const ar = [
    { key: '1', val: 'a' },
    { key: '2', val: 'b' },
    { key: '3', val: 'c' }
]

const obj = keyBy({ ...ar }, 'key')
```

**Comment by mbrowne** [comment]
@davidsonsns I don't see how that's in any way an improvement on:

    const obj = _.keyBy(ar, 'key')

...and anyway you still end up with the same objects from your original array; there's no callback being applied to return a custom value for each item, which I think is one of the main goals here...

**Comment by mbrowne** [comment]
Alternative naming idea, in case this gets reconsidered in the future: `mapToObject`. `toObject` is OK but is a little vague...Converting to an object how? From what? Also, `keyBy` also converts an array/collection to an object.

**Comment by SeregPie** [comment]
Another solution would be to extend `fromPairs` with an iteratee as second argument.

```js
let object = _.fromPairs(input, ({key, value}) => [key, value]);
```

**Comment by mbrowne** [comment]
@SeregPie that could be a good solution.

Also, I retract my naming suggestion. I was thinking of it as "map an array to an object", but just realized it could be misread as "convert a Map to a plain object" or something like that.

**Comment by mbrowne** [comment]
I discovered that there is an ESNext proposal for this:
https://github.com/tc39/proposal-object-from-entries

So another option would be to add a method called `fromEntries` (which will hopefully eventually be a native method, but good to have in lodash in the meantime). This name makes sense because the proposed `Object.fromEntries()` is the inverse of `Object.entries()`.

On the other hand, just adding a new parameter to the existing `fromPairs` method might be simpler from an API design perspective for lodash. I'm on the fence on this one...

**Comment by BlueRaja** [comment]
As far as I can tell, `fromEntries` is exactly the same as `fromPairs`, so naming this new method `fromEntries` could only cause unnecessary confusion.

The whole point is that we can currently accomplish this using
```
_.fromPairs(inputs.map(input => [keyFunc(input), valFunc(input)]));
```
but it'd be much cleaner if we only had to write
```
_.toObject(inputs, keyFunc, valFunc);
```

I'm also opposed to the name `mapToObject`, since `map` implies the output is an array, which it is not.

**Comment by BlueRaja** [comment]
As far as I can tell, `fromEntries` is exactly the same as `fromPairs`, so naming this new method `fromEntries` could only cause unnecessary confusion.

The whole point is that we can currently accomplish this using
```
_.fromPairs(inputs.map(input => [keyFunc(input), valFunc(input)]));
```
but it'd be much cleaner if we only had to write
```
_.toObject(inputs, keyFunc, valFunc);
```

I'm also opposed to the name [`mapToObject`](https://github.com/lodash/lodash/issues/2718#issuecomment-377637970), since `map` implies the output is an array, which it is not.

I'm _also_ opposed to the [`fromPairs` iteree suggestion](https://github.com/lodash/lodash/issues/2718#issuecomment-377674644).  `frompairs` takes an array of arrays, not an array of objects.  It would be confusing for one overload to expect a completely different input format.

**Comment by mbrowne** [comment]
@BlueRaja you're right, `Object.fromEntries` will do the same thing as `fromPairs`; I wasn't thinking clearly on that one. On another note, in your example the main reason `toObject` is more concise is that `keyFunc` and `valFunc` are already defined...if you inline a function that returns both the key and the value because you don't already have existing functions for that, which I'm guessing is the more common case, it's more of a toss-up...

**Comment by ehaynes99** [comment]
This is something I need to do all the time. I'm actually a quite surprised that its utility is even in question. Essentially, "Given an array of keys, calculate some value for each and return an indexed object".

The above examples all seem to doing this from an array of objects where the key is a property of that object which I think distracts from the **much** more common case of simply wanting an indexed object whose values are derived from some keys.

```javascript
const itemIds = [1, 3, 5, 7, 9]
const getItem = id => itemContainer[id]

// whatever it's called
const items = mapToObject(itemIds, getItem)
```
That's clean and succinct, and IMO plainly obvious at a glance what it's doing. It's going to require at least a little mental stop-and-examine when coming across any of these:
```javascript
const items = chain(ids).keyBy(identity).mapValues(getItem).value()

const items = fromPairs(ids.map(id => [id, getItem(id)]))

const items = zipObject(ids, ids.map(getItem))

const items = reduce(ids, (result, id) => ({...result, [id]: getItem(id)}), {})
```

In my opinion, the key mapping shouldn't be part of it. If you want to map some values to keys, just map the keys first and pass them into this. If they key mapping is part of it, I think it should definitely be an optional SECOND argument. So it can be easily omitted.

**Comment by denis-shostik** [comment]
`_.map({...arr}, (item) => ([item.id]: item))`

**Comment by maciej-gurban** [comment]
Over the years I've this functionality replicated across different projects countless times, through very different, often suboptimal or incomprehensible implementations. The issue has now ~250 people who would love for it to materialize and many comments explaining how valuable such utility would. What would it take for you to reconsider your stance and accept a PR with a solution?

**Comment by jdalton** [comment]
Thanks @maciej-gurban!

The 👍 reaction is used as an indicator of developer interest in a feature, not as a mandate to add such feature. The high number of 👍 is recorded and searchable by me so this issue needs no further feedback. With that I can lock this issue and continue to use it for reference when the time comes to add more features.
