### ISSUE TITLE
_.attempt & _.isError question/proposal

### ISSUE THREAD

**Issue by lobo-tuerto** [lodash/lodash#2719]
Hello guys,

I was looking at an example that uses `_.attempt` for parsing JSON.
And then uses `_.error` to check if it indeed failed.

The problem with this example is that, if you happen to deserialize an object that happen to have `name` and `message` attributes, it will fail even though the parsing was successful.

What I was wondering is, would it be possible to further differentiate the error object created by `_.attempt` to cover this use case?

For example, do you think that setting a prototype for the error object that includes a property like `type: 'Error'` when creating it with `_.attemp` is a good idea? Then you could also check for that condition in `_.isError` at this line:
https://github.com/lodash/lodash/blob/4.16.4/lodash.js#L11539

The particular example I'm talking about is mentioned in this link: http://colintoh.com/blog/lodash-10-javascript-utility-functions-stop-rewriting#10)_error_handling_for_json.parse

I know it's a very specific case, but I think it'll improve the library as it could be used in a broader number of use cases.

**Comment by jdalton** [comment]
Hi @lobo-tuerto!

For the rationale for the `_.isError` inference see #1994. I'm open to better detections if available.

**Comment by lobo-tuerto** [comment]
Awesome! thanks for the quick response and action! :)
