### ISSUE TITLE
Reduce missing from list of chainable methods?

### ISSUE THREAD

**Issue by gamebox** [lodash/lodash#2722]
I noticed that in the Typescript typings, that reduce is not a member of the LoDashExplicitArrayWrapper(i.e., the object returned by_.chain()), and looking at the documentation you don't see `reduce` in the list of chainable methods. But, opening a console right on the lodash.com website and entering the following

`_.chain([1,2,3]).map(x => x * 2).reduce((acc, x) => acc + x).value()`

Returns 12 as one would expect.  Is this a documentation error, or an error in my understanding of what the list of chainable methods is?  I think if this is a chainable method, then adding it to the documentation would also create the support for adding it to the typings as well.

**Comment by jdalton** [comment]
Hi @gamebox!

Our `reduce` method doesn't implicitly chain by default.
Using `chain` will force all methods to chain.

**Comment by gamebox** [comment]
Interesting.  Thanks for the clarification.  So what should be expected for
typings?  It feels gross to use a type system, and then ignore errors it
throws when the type system doesn't represent the actual reality(ie, reduce
will be present)

**Comment by jdalton** [comment]
>  So what should be expected for typings?

File a bug on the typings I guess *(which we don't own)*.

**Comment by gamebox** [comment]
Copy that, thanks for the feedback and quick replies. Oh, and the great
library.
