### ISSUE TITLE
Feature request : insertString(string, index, substring)

### ISSUE THREAD

**Issue by yvele** [lodash/lodash#2723]
Hi, it would be nice to have an insertString function :
```js
/**
 * @param {string} string
 * @param {number} index
 * @param {string} substring
 * @returns {string} New string
 */
export default function insertString(string, index, substring) {
  return [string.slice(0, index), substring, string.slice(index)].join("");
}
```

  - There is already a `_.insert` on the road #89
  - Underscore.string [have it](http://epeli.github.io/underscore.string/#insert-string-index-substring-gt-string)
  - Popularity indicator based [on a SO question](http://stackoverflow.com/q/4364881/1480391)

**Comment by jdalton** [comment]
Thanks @yvele!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
