### ISSUE TITLE
Issue "Merge" starting with 4.16.3

### ISSUE THREAD

**Issue by fabianuribe** [lodash/lodash#2724]
It appears a regression got introduced on `merge` version 4.16.3 since it is now merging in keys with undefined values.

### Sample
```
var merge = require('lodash').merge;

var translations = merge(
        {
            hello: 'hola'
        },
        {
            goodBye: 'adios',
            goodNite: undefined
        }
    );

console.log(translations);
```

`Node v6.6.0`

With `4.16.2` >>> `{ hello: 'hola', goodBye: 'adios'}`
With `4.16.3` >>> `{ hello: 'hola', goodBye: 'adios', goodNite: undefined }`
With `4.16.4` >>> `{ hello: 'hola', goodBye: 'adios', goodNite: undefined }`

**Comment by jdalton** [comment]
Dup of #2702.
