### ISSUE TITLE
Diacritics removal

### ISSUE THREAD

**Issue by ferhatelmas** [lodash/lodash#2726]
We were using [node-diacritics](https://github.com/andrewrk/node-diacritics) package. Realized lodash extended its diacritics support. However, it's still not equivalent. 
``` javascript
require('diacritics').remove("Iлｔèｒｎåｔïｏｎɑｌíƶａｔï߀ԉ"))
// prints "Internationalizati0n"
require("lodash").deburr("Iлｔèｒｎåｔïｏｎɑｌíƶａｔï߀ԉ")
// prints "Iлｔeｒｎaｔiｏｎɑｌiƶａｔi߀ԉ"
```
Since we're using lodash anyway, would be perfect if we can drop other dependency. Is there any plan to extend support for other blocks?

**Comment by jdalton** [comment]
Hi @ferhatelmas!

At the moment we support Latin-1 Supplement and Latin Extended-A blocks. We'll evaluate more as demand grows. Do you have specific blocks in mind?

**Comment by ferhatelmas** [comment]
Since I was checking if I can replace other package, I blindly expected the same output. 

Other package can handle following blocks:
 * Latin Extended-B
 * Cyrillic
 * Cyrillic Supplement
 * Halfwidth amd fullwidth forms
 * NKo

However, they are a bit esoteric and I think, we can live with current supported blocks. Thanks!
