### ISSUE TITLE
fp versions of individual functions

### ISSUE THREAD

**Issue by rightaway** [lodash/lodash#2727]
If I'm getting a particular function I can install just the dependency (e.g. `lodash.set` instead of `lodash`). Are there `fp` versions of these individual function packages, (something like `lodash.fp.set`), or do I have to install all of lodash and then import `lodash/fp/set`?

**Comment by jdalton** [comment]
Hi @rightaway!

While we don't offer individual packages, you can cherry-pick them using:
```js
var set = require('lodash/fp/set');
```
or using [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash):
```js
import { set } from 'lodash/fp';
```
