### ISSUE TITLE
Lodash/fp convert on fp specific `all` methods like `extendAll` doesn't work

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash#2728]
The issue seems to be [here](https://github.com/lodash/lodash/blob/master/fp/_baseConvert.js#L357). It seems like it's looking for the method name on `pristine`, which I think is non-fp lodash. This line should consider falling back to the actual function that's passed in or perhaps change something with the `isLib` check.

Here's a failing test:

```js
var _ = require('lodash/fp');
describe('lodash/fp', function() {
    it('should convert', function() {
        var extendAll = _.extendAll.convert({
            immutable: false
        });
        // Explosion in baseConvert
    })
})
```

**Comment by daedalus28** [comment]
In case it was unclear, this happens with all of the lodash fp specific methods, including `mergeAll` and others. Which would make sense - `_baseConvert` can't find them on the pristine lodash since they don't exist.

**Comment by jdalton** [comment]
Thanks @daedalus28!
