### ISSUE TITLE
What is the use case of _.head()?

### ISSUE THREAD

**Issue by griii2** [lodash/lodash#2732]
I am probably missing something obvious but what is the use case of _.head()? How is it different from [0]?

**Comment by griii2** [comment]
Also, how is _.join() different from Array.join()? What am I missing?

**Comment by griii2** [comment]
Also, how is _.slice() different from Array.slice()? There is a note in the docs saying "This method is used instead of Array#slice to ensure dense arrays are returned." but no actual information is provided in the description of the function or the description of the returned array.

**Comment by griii2** [comment]
What is the use case of _.negate and how is it different from ! operator?

**Comment by StreetStrider** [comment]
@griii2 all of that you can use in compositions, like:
```js
.then(head)
// or
var do_smth = flow(head, negate)
// etc…
```
You can't use operators in composition at all.

`_.slice` is working on array-like objects directly, without requiring to use `apply`.

`join` can be used in lodash chain.
