### ISSUE TITLE
fp partial right and fp curry

### ISSUE THREAD

**Issue by c-dante** [lodash/lodash#2734]
Not sure if this is by design, but it looks like currying something that you've already partially applied fails.

```
const add = (a, b, c) => a + b + c;
const partial = fp.partialRight(add, [5]); // c = 5
cosnt curried = fp.curry(partial);

curried(1, 2); // does not call the function!!!
curried(1, 2, 3); // Calls 1 + 2 + 3
```

It seems that currying stomps over partial application -- is there a good reason for them to not be compatible?

**Comment by jdalton** [comment]
The arity of a partialed or wrapped function is not preserved. You'll want to use `fp.curryN` to specify the arity:
```js
fp.curryN(2, partial);
```

**Comment by c-dante** [comment]
Thanks -- is there a particular reason to preserve the airy from the partial application? I would figure that the intention is to reduce it down.

**Comment by jdalton** [comment]
arity gets tricky so we punt and allow folks to be explicit when necessary.

**Comment by c-dante** [comment]
That sounds good -- the solution for me would invert, and instead force the arity down when I partial (I hand the function off to someone that may or may not curry it without knowing the arity ahead of time).
