### ISSUE TITLE
Feature Request: make the range function work with characters

### ISSUE THREAD

**Issue by benjaminmcdonald** [lodash/lodash#2735]
-> _.range('A', 'C')
  ['A', 'B', 'C']

**Comment by jdalton** [comment]
Hi @benjaminmcdonald

I don't think I'll be overloading `_.range` for this. It reminds me of Prototype's `String#succ` which is based on [Ruby](http://apidock.com/ruby/String/succ). We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by mk-pmb** [comment]
I prefer a separate function. With current lodash, I can safely pass in string from form fields, and if they are not numbers, I get an empty array for my loop, aka no processing instead of strange processing.
