### ISSUE TITLE
[q] call a function only once at a time

### ISSUE THREAD

**Issue by andreineculau** [lodash/lodash#2736]
Hi!

I'm just wondering if there's a lodash function that can make sure "function foo" is only called once at a time?

* if it's called while it is already running, the call is ignored
* if it was called while it was already running, the function will be called with the last parameters

Thanks

**Comment by jdalton** [comment]
Hi @andreineculau!

We don't have one exactly like that though we have [_.debounce](https://lodash.com/docs/#debounce) & [_.throttle](https://lodash.com/docs/#throttle)
which have traits of what you described.
