### ISSUE TITLE
In lodash/fp, add standard mapping for non-flipped but still autocurried, immutable methods

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash#2738]
I often find that I have a need for the non flipped versions as well when doing fp stuff - for example, with `includes` or `get` I often have the case where the part that varies is actually the data. In these cases, I generally add use `_.flip` on the fp functions and have started building a standard mapping for these where it is the method name concatenated with `From` - e.g. `includesFrom = _.flip(_.includes)`, `getFrom = _.flip(_.get)`.

It would be great for this to be part of the core mapping itself as I'm sure I'm not the only one with this common use case. You may want a different convention that `From` as that might conflict with the current convention like `findFrom` - but I think that a solid convention here would be beneficial on non fp lodash as well.

If you don't end up implementing it in fp, I'd still love to get your input on what the convention should be so I can release a small library that just sets up some conversions like fp's convert does.

**Comment by jdalton** [comment]
Hi @daedalus28!

You can use the [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert) method:
```js
import { include } from 'lodash/fp';
const _include = include.convert({ rearg: false });
```

**Comment by daedalus28** [comment]
That's true about `rearg: false` (which has the same effect as `_.flip`), but my point is that I'm using it a lot and I'd like to standardize the naming convention instead of converting all over the code base.

In practice I think this is something most fp users will end up needing. I understand if you don't want these non-rearged aliases in the core, so I can publish a separate library that just reargs some methods like a lodash/fp contrib sort of thing. Do you agree on the naming convention of appending 'From' for non-rearged methods? Even as a separate util I'd still like your buy in on the names.
