### ISSUE TITLE
Add minimal support for lazy evaluation to chaining syntax

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash#274]
Project's like [Lazy.js](https://github.com/dtao/lazy.js) prove that lazy evaluation can be implemented in a way that generally performs well. For a future release I'd like to bake-in limited support for this in some of our chained methods.

**Comment by tom-field** [comment]
good

**Comment by cyrilchapon** [comment]
Where can we find a list of which methods are supported ?

**Comment by syzer** [comment]
+2

**Comment by jdalton** [comment]
@cyrilchapon See https://lodash.com/docs/#lodash.

**Comment by cyrilchapon** [comment]
> Lazy evaluation allows several methods to support shortcut fusion

My question is => which one ?

**Comment by demoneaux** [comment]
From [the `_` docs](https://lodash.com/docs/#lodash):

 > The wrapper methods that support shortcut fusion are:
`at`, `compact`, `drop`, `dropRight`, `dropWhile`, `filter`, `find`, `findLast`, `head`, `initial`, `last`, `map`, `reject`, `reverse`, `slice`, `tail`, `take`, `takeRight`, `takeRightWhile`, `takeWhile`, and `toArray`

**Comment by cyrilchapon** [comment]
Wow I'm an idiot. Oo

I read it thrice wtf.

Thanks @demoneaux sorry bout this
