### ISSUE TITLE
.lowercase is not working appropriately

### ISSUE THREAD

**Issue by saurabh0118** [lodash/lodash#2746]
I tried to do a lowercase on a word which is in camel case and its putting a space in doing the lowercase operation.

console.log(_.lowerCase('CulinaryCouncil')); 

culinary council
9:50:02 AM web.1       |  culinary council
9:50:02 AM web.1       |  culinary council
9:50:02 AM web.1       |  culinary council
9:50:02 AM web.1       |  culinary council
9:50:02 AM web.1       |  culinary council
9:50:02 AM web.1       |  culinary council
9:50:02 AM web.1       |  culinary council
9:50:02 AM web.1       |  culinary council
9:50:02 AM web.1       |  culinary council

**Comment by jdalton** [comment]
Hi @saurabh0118!

This is by design because its a "case" method, like `camelCase`, `snakeCase`, `kebabCase`, etc.
You're looking for [_.toLower](https://lodash.com/docs/#toLower).

**Comment by saurabh0118** [comment]
Thanks for correcting @jdalton
