### ISSUE TITLE
Documentation header broken in Safari

### ISSUE THREAD

**Issue by DaSchTour** [lodash/lodash#2747]
There is some issue in Safari with the header in documentation. I guess that position relative is used wrong. It would work with `position: absolute` and `width: 100%` than there is only the spacing of overlapped content missing. So the content in sidebar needs padding to top.

![lodash documentation 2016-10-21 10-51-39](https://cloud.githubusercontent.com/assets/1907266/19592588/c3b2c4a0-977c-11e6-95ac-c874d188d208.png)

**Comment by jdalton** [comment]
Hi @DaSchTour!

Our website repo is over at https://github.com/lodash/lodash.com.
That said, I cannot reproduce the issue. If you're able to patch it then by all means open a PR.

**Comment by DaSchTour** [comment]
Even reproducible her: https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/?url=https%3A%2F%2Flodash.com%2Fdocs%2F4.16.4
 * Android 5.0 https://www.browserstack.com/screenshots/c76775316ca7cda742d6a9fc2f0a2cb2e14325bf/android_Google-Nexus-9_5.0_portrait.png

Sadly iOS and Safari don't work on at microsofts page.

**Comment by jdalton** [comment]
Here's what I see in Safari 10:
<img width="578" src="https://cloud.githubusercontent.com/assets/4303/19603102/bea0bf98-9764-11e6-9d25-d9e7fb5d3d3f.png">

**Comment by jdalton** [comment]
Again if you want to help show it with a PR on the right repo.

**Comment by DaSchTour** [comment]
It's closed and "not reproducible", so why put work into it? Seams not to be worth it, just for the some users still using Safari 9.
