### ISSUE TITLE
each/forEach method broken if key 'length' exist in object

### ISSUE THREAD

**Issue by jurekt** [lodash/lodash#2748]
Hi, 

today found some error with _.each / _.forEach method. 

If we have object with key 'length':

`
var dimensions = {
   'length': 5,
   'width': 3,
   'depth': 1
};
`

...method will iterate through 'length' value (in example it will each to 2).

![each_bug](https://cloud.githubusercontent.com/assets/3917470/19600764/bb55a276-97a6-11e6-86dd-f2fef8dee14c.png)

**Comment by jdalton** [comment]
Hi @jurekt!

This is by design because it's a "Collection" method which means it works with and prioritizes array-like values over objects. Related to #1172, #1705, or #2352.
