### ISSUE TITLE
Feature Request: _.divmod

### ISSUE THREAD

**Issue by nhardy** [lodash/lodash#2749]
Python has a useful builtin function, `divmod(dividend, divisor)` that returns an array containing the `quotient` and `remainder` for the floored division of `dividend` by `divisor`.
See https://docs.python.org/3/library/functions.html#divmod

I find `divmod` particularly useful in this situation:

```javascript
const SECONDS = 3723; // 1 hour, 2 minutes and 3 seconds

const [totalMinutes, seconds] = divmod(SECONDS, 60);
const [hours, minutes] = divmod(totalMinutes, 60);

console.log(hours, minutes, seconds); // logs '1 2 3' 
```

I think an implementation would be something like:

```javascript
/**
 * @param {Number} dividend
 * @param {Number} divisor
 * @returns {Array} [quotient, remainder]
 */
function divmod(dividend, divisor) {
  return [Math.floor(dividend / divisor), dividend % divisor];
}
```

**Comment by jdalton** [comment]
Thanks @nhardy!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
