### ISSUE TITLE
Feature request: lodash/fp wrapper for the "new" operator

### ISSUE THREAD

**Issue by EvgenyOrekhov** [lodash/lodash#2752]
To make composition of constructors easier I propose a new method, let's call it `_.make()`, for example.
It would accept a constructor and its argument and call the constructor with the `new` operator, so the following two lines would work equivalently:
```js
const object = _.make(Constructor, argument);
const object = new Constructor(argument);
```
So instead of writing
```js
_.compose((message) => new Error(message), translate)("some message")
```
we would write
```js
_.compose(_.make(Error), translate)("some message")
```

**Comment by jdalton** [comment]
Thanks  @EvgenyOrekhov!

The ES6 form is so small and flexible I don't know if adding a more rigid method has much value, but we'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
