### ISSUE TITLE
Documentation: Callback arguments in argument list?

### ISSUE THREAD

**Issue by MannyC** [lodash/lodash#2753]
Was there ever any thought given to listing the arguments of a callback function in the argument list?  Currently they're just in the main documentation body.  I think it's one of the more likely things that a user would have to check the docs for, and having it in the arguments list would make it easier to find.  

Personally, I find if I haven't used the lodash docs in a while this will always catch me out.

**Comment by jdalton** [comment]
I don't believe we've attempted it. Would you provide an example of what you had in mind.

**Comment by MannyC** [comment]
This is an example of what I was thinking of: 

https://github.com/MannyC/lodash/commit/aa0cef6a5e066556d314dd310ba5b9623f791ce7

That isn't italicizing correctly at the moment with your sitehtml build, but it's just an example.

**Comment by jdalton** [comment]
Ah ok. I'll hold off on these kinds of doc juggles until I begin work on v5.
