### ISSUE TITLE
no takeWhile function?

### ISSUE THREAD

**Issue by cocodrino** [lodash/lodash#276]
Hi..I'm not sure but I can't find in the doc something similar to take-while, which is really useful...here is the prelude-ls example

http://preludels.com/#take-while
 take-while
(a → Boolean) → [a] → [a]

Takes the first items of the list which pass the test.

take-while odd, [1 3 5 4 8 7 9] #=> [1, 3, 5]

also drop-while seems useful

what do u think about add these to next release??

**Comment by robey** [comment]
According to your docs, `_.first` doesn't take a callback.

**Comment by jdalton** [comment]
In v3 we have [_.takeWhile](https://lodash.com/docs#takeWhile).
