### ISSUE TITLE
indexOf for strings with underscore inside

### ISSUE THREAD

**Issue by deser** [lodash/lodash#2764]
Consider bug shown on the picture:
![indexof](https://cloud.githubusercontent.com/assets/3010698/19761902/7309a26c-9c40-11e6-9327-584d3738e014.png)

**Comment by jdalton** [comment]
The `_.indexOf` method is an "Arrays" method. Because strings are array-like it's treating it like an array of `['A', 'T', 'T', 'A', 'C', 'H', ...]`.

**Comment by deser** [comment]
The problem here in design. As _.indexOf is very similar to "".indexOf or [].indexOf

**Comment by ghostuz** [comment]
Hi all. about use indexOf for string
As I know. for now, _.indexOf is suite for Array. but today. I found my guys use indexOf for the string. and I think this method is too closed to native string.indexOf.
can we add this feature something like

function indexOf(target, value, fromIndex) {
	const length = target == null ? 0 : target.length
	if (!length) {
		return -1
	}
	**if (isString(target)) {
		let testSource = target.substr(fromIndex);
		return testSource.indexOf(value);
	}**
	let index = fromIndex == null ? 0 : +fromIndex
	if (index < 0) {
		index = Math.max(length + index, 0)
	}
	return baseIndexOf(target, value, index)
}
