### ISSUE TITLE
_.inRange() logic?

### ISSUE THREAD

**Issue by futhr** [lodash/lodash#2765]
Hi, thanks for a great lib but this is not very portable or logic behaviour?

**lodash**
```js
_.inRange(0, 50, 50) // => false
```

**ruby**
```ruby
(0..50).include? 50 # => true
```

**Comment by Florian-R** [comment]
This is in symmetry with `_.range` which does not include its `end` parameter.

**Comment by jdalton** [comment]
Hi @futhr!

The param order for `_.inRange` is `number, start, end`.
If you invoke it with two arguments then it's `number, end`.

**Comment by futhr** [comment]
Well I got the order "ruby styled" in my sample above, but still do not understand the reason why the method do not add up to similar methods in other languages. It might be useful when working with indices but not very useful for numbers and floats. `_.mixin()`to the rescue unless I missed anything essential.

```js
var match = 50;
_.inRange(match, 0, 50); // => false
_.inRange(match, 50); // => false
```

Thanks anyway for a quick answer.

**Comment by jridgewell** [comment]
`_.range` and `_.inRange` map to ruby's `...` range, not the `..` range.
