### ISSUE TITLE
_.until(method, predicate) utility function. While-loop equivelant

### ISSUE THREAD

**Issue by mindfullsilence** [lodash/lodash#2769]
Whipped this up while writing a function that returns a random string with a given length. Wondering if this is something that would be useful in the library. Returns a function that will recursively call a passed function until a test returns truthy:

```js
  _.until = (run, predicate) => {
    let method = (subject) => {
      if (!predicate(subject)) {
        return method(run(subject))
      } else {
        return subject
      }
    }
    return method
  }
```

Oversimplified Example Use:

```js
  const desiredValue = 20
  const addOne = (num) => _.add(num, 1)
  const isDesired = (num) => _.eq(num, desiredValue)
  const addOneUntilVal = _.until(addOne, isDesired)
  addOneUntilVal(1) // 20
```

My usecase (still fairly simple)

```js
const generateRandomString = (entropy) => {
  entropy = _.default(entropy, 10)
  let randChar = () => Math.random().toString(36).substr(3, 1)
  let isAtEntropy = (str) => _.gte(str.length, entropy)
  let addOneChar = (str) => str + randChar()
  let concatUntilLen = _.until(addOneChar, isAtEntropy)

  return concatUntilLen(randChar())
}

generateRandomString(20) // t7rx1nvg3uazos64xhet

**Comment by jdalton** [comment]
Thanks @mindfullsilence!

I use something like this internally to handle short circuiting hot functions.
We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
