### ISSUE TITLE
Possible regression in 4.14.1? path ".[0]" has changed behaviour.

### ISSUE THREAD

**Issue by mkulke** [lodash/lodash#2770]
4.14.0 seems to to discard the leading dot:

```
l.toPath('.[0]')
[ '0' ]
```

while in 4.14.1 (with c253e8d) the behaviour changed:

```
> l.toPath('.[0]')
[ '', '0' ]
```

is this intended (i'm not sure, i cannot find a spec for paths expressions in lodash)?

**Comment by jdalton** [comment]
Dup of #2554.
