### ISSUE TITLE
Possible regression in xor in 4.16.5

### ISSUE THREAD

**Issue by jbblanchet** [lodash/lodash#2776]
I've not yet been able to reproduce the error outside our own codebase, but with 4.16.5, xoring identical arrays will sometimes return `[undefined]`. Rolling back to 4.16.4 fixes the issue.

I have no idea what the exact combination of factors is. I'm still working on reproducing the issue. Will update this post once I know more.

**Comment by jbblanchet** [comment]
Got it! Xoring the *same* array return `[undefined]`.

To reproduce:

```javascript
const arr = ['a'];
console.log(_.xor(arr, arr));
```

**Comment by jdalton** [comment]
Thanks for the heads up!
