### ISSUE TITLE
parseInt throws toString(string).replace is not a function

### ISSUE THREAD

**Issue by screendriver** [lodash/lodash#2782]
If I call `parseInt()` with a number like `parseInt(123)` I get 

```
TypeError: toString(string).replace is not a function. (In 'toString(string).replace(reTrim, '')', 'toString(string).replace' is undefined)
```

It seems that `toString(string)` does not make a string for it:

```
> typeof toString(123)
< "number"
```

My code is running on iOS if that matters.

**Comment by jdalton** [comment]
Hi @screendriver!

I'm sorry but I can't repro this.

**Comment by screendriver** [comment]
Is there anything I can do for you? It is reproducible on my machine. Sample project? Console statements? Any debug informations / screenshots? Anything else?

**Comment by jdalton** [comment]
Sure you can specify which version of Lodash you're using and provide an example snippet. So far based on your descriptions it looks like your using the `window.toString` function and the `window.parseInt` function.

**Comment by screendriver** [comment]
I'm using the latest version `4.16.6`. Also I'm using `babel-plugin-lodash@3.2.9` and `webpack@1.13.3`

![screenshot](https://cloud.githubusercontent.com/assets/149248/19957007/b5785aa6-a192-11e6-941d-58836c34bba2.png)

**Comment by jdalton** [comment]
I'm guessing you're also using the `lodash-webpack-plugin` and need to enable the `guards` feature set.

**Comment by screendriver** [comment]
Yes, I am using the `lodash-webpack-plugin`. 

Ok, I enabled `guards`:

```js
new LodashModuleReplacementPlugin({
  guards: true,
}),
```

but nothing has changed. Same error.

**Comment by screendriver** [comment]
Second try: I completely disabled `lodash-webpack-plugin` and now it's working 😳

**Comment by jdalton** [comment]
or `coercions` feature set.

**Comment by screendriver** [comment]
`coercions` did work! 👍 This should be in the docs somewhere 😉

**Comment by jdalton** [comment]
It is, in the [lodash-webpack-plugin repo](https://github.com/lodash/lodash-webpack-plugin) under [feature sets](https://github.com/lodash/lodash-webpack-plugin#feature-sets).

**Comment by screendriver** [comment]
I read that but I don't know what that means: `Coercion methods like _.toInteger, _.toNumber, & _.toString`. Coercion for what?

**Comment by jdalton** [comment]
Value type coercions like coercing values to integers, to numbers, to strings. I've added `_.parseInt` to the overrides mapping to auto enable the `coercions` feature set when `_.parseInt` is used (https://github.com/lodash/lodash-webpack-plugin/commit/f592fa107ca319107cfa30f3ab2a5fa2b16d2319).

**Comment by screendriver** [comment]
Ah ok. I understand. Thank you for the help! Great support! 😎
