### ISSUE TITLE
[fp] negate + curried functions

### ISSUE THREAD

**Issue by Andarist** [lodash/lodash#2784]
Would it be possible for `negate` to support accepting curried functions? I would expect this:
`_.negate((n, m) => (n + m) % 2 === 0)(2)`
return curried function instead of running predicate right away

**Comment by jdalton** [comment]
The `negate` method creates a simple wrapper around a function to `!` its return value. There's no way to detect if the provided function is curried.

**Comment by Andarist** [comment]
Well, you could probably check if its `lodash/fp` function (so curried) or wrapped by `_.curry`. That would probably need some flag, but its not like `lodash` is not setting anything on its utils - i.e. `convert` and `placeholder` are available on every `lodash/fp` function

**Comment by jdalton** [comment]
We have no way to track across environments how many args are required to complete the curried function.

**Comment by Andarist** [comment]
Hm, I think that's simply not true, as `curry` itself needs to check function arity and that could be stored.

**Comment by jdalton** [comment]
> Hm, I think that's simply not true, as curry itself needs to check function arity and that could be stored.

We have `curryN` to allow explicit arity specification since `func.length` isn't always reliable. We don't set the `func.length` though so everything that's wrapped has a `.length` of `0`.

**Comment by Andarist** [comment]
Well, I wasnt suggesting seting the `length` property, but some other - new one, like `curryArity` (or whatever other name). Though I understand that the gain might not be that much and such polluting isnt the nicest thing. Just wondering out loud :)

**Comment by jdalton** [comment]
I want to avoid setting magic properties on functions or limiting the creation of functions to an arity range (e.g. 0-10).
