### ISSUE TITLE
When called multiple times, _.set creates different result based on the order of the calls 

### ISSUE THREAD

**Issue by sstendal** [lodash/lodash#2787]
Our object keys follows a pattern where they are a combination of numbers and underscores like
  1
  1_2
  1_44_3
etc.
Our object tree also includes arrays.

This code creates an array with an object inside
    let x = {}
    _.set(x, "y[2].3_4", "value 2")
    _.set(x, "y[2].5", "value 1")

This code creates an array with an array inside. 
    let x = {}
    _.set(x, "y[2].5", "value 1")
    _.set(x, "y[2].3_4", "value 2")

It is not possible to solve this issue by using setWith, since the customizer cannot see if bracket notation or dot notation was used.

**Comment by jdalton** [comment]
> It is not possible to solve this issue by using setWith, since the customizer cannot see if bracket notation or dot notation was used.

However you can use `setWith` to always create an object and avoid the array creation.

**Comment by sstendal** [comment]
Yes, I can use setWith to always create an object and avoid array creation. But the problem with this is that we need both array and object creation.

let x = {}
_.set(x, "y[2].5", "value 1")
_.set(x, "y[2].3_4", "value 2")

I believe the natural functionality for the code above would be to create:

{ y: [undefined, undefined, { 5: 'value 1', 3_4: 'value 2'}] }

That is, a combination of arrays and objects. This is also what I would get if I made the calls in the opposite order.

It is not possible to solve this issue by using setWith, since the customizer would have to create both objects and arrays depending on if the bracket notation was used or not. The customizer cannot see if bracket notation or dot notation was used.

**Comment by jdalton** [comment]
It looks like you may need a more specialized function or mixin.
