### ISSUE TITLE
Documentation minsinforms on breaking changes to API, e.g. _.find

### ISSUE THREAD

**Issue by Stuey2** [lodash/lodash#2790]
There should be some indication of when a breaking change happens to the  API of a particular command. (In fact a diff tools for easy upgrading to see which commands had breaking changes between two random versions would be helpful)

An example of this is the _.find command. The documentation for version 4.16.6 shows that _.find has been available since v0.1.0. Whilst it may be true that the command has been available, it is not true to say that _.find API has been available since v0.1.0 in its current form.

Here is a picture of the documentation for v.4.16.6 and below that one for v3.10.1, where the API has changed - what's more a breaking change.

![image](https://cloud.githubusercontent.com/assets/14346963/20029213/4705026a-a33e-11e6-8166-02f02ede7c78.png)

![image](https://cloud.githubusercontent.com/assets/14346963/20029249/26971c24-a33f-11e6-9553-cab73acd93be.png)

**Comment by jdalton** [comment]
> , it is not true to say that _.find API has been available since v0.1.0 in its current form.

I think you're reading a bit more into a `@since` tag than needed and I get a whiff that you're trying to assign malicious intent which isn't the case.
