### ISSUE TITLE
flattenDeep => pass a string, get U

### ISSUE THREAD

**Issue by ORESoftware** [lodash/lodash#2791]
I used flattenDeep like this:

_.flattenDeep('some string')

when I meant to do

_.flattenDeep(['some string']);

I would have expected lodash to barf on this.

But instead I got 'U'

  => Suman uncaught exception => AssertionError:  => Suman implementation error => path should be absolute here => 'U'
    at /Users/Olegzandr/WebstormProjects/oresoftware/suman/lib/watching/add-watcher.js:32:7

seems pretty strange

now I realize it is picking up the U as in Users/ in the filesytem path.

I guess it can work with strings, but maybe it's not supposed to?

**Comment by jdalton** [comment]
Hi @ORESoftware!

A string is array-like and so will kind-of work in "Arrays" methods but I wouldn't recommend it.
