### ISSUE TITLE
_.toLower and _.toLowerCase

### ISSUE THREAD

**Issue by guillaumegarcia13** [lodash/lodash#2792]
Hi,

I read about other "issues" with these 2 methods but I was wondering why they behave differently with accented characters?

For instance:
> _.toLower("Développement Web")  --> "d**é**veloppement web"
> _.lowerCase("Développement Web")  --> "d**e**veloppement web" 

**Edited**:
Actually, I think that `_.toLower( _.deburr( <string> ) )` is what I was looking for

**Comment by jdalton** [comment]
The `lowerCase` is a case method like `camelCase`, `kebabCase`, `snakeCase`, or `startCase`. These casing methods deburr and separate words, and compound words, and then re-join them together based on their casing rules.
