### ISSUE TITLE
Add typings to individual modules

### ISSUE THREAD

**Issue by sheerun** [lodash/lodash#2795]
Hey,

When trying to use `lodash.assign` with typescript `2.1.0-dev.20161019` I get "error TS2307: Cannot find module 'lodash.assign'" error.

Might it be because individual packages don't have matching `@types` on npm? For example https://www.npmjs.com/package/@types/lodash.assign

Could you create them?

**Comment by jdalton** [comment]
Hi @sheerun!

I'm not in the typings business just yet. Usually those more familiar with the typing of choice create them for things like TypeScript or Flow. There may be a way to disable required typings for things like node_modules but I'm not :100: on that.

**Comment by Squiggle** [comment]
That's a real shame :(

Lots of people are developing in TypeScript 2.x and are heavily dependent on types. This means duplicated effort by anyone who wants to use these modules in typescript projects.

**Comment by jdalton** [comment]
Requiring types for third-party code is a bad move.
It would be like requiring all third-party code align to your preference on linting rules.

**Comment by jdalton** [comment]
You should have the ability to opt-out third party code and if not you should request the ability to do so from the TypeScript and Flow teams.

**Comment by fcamblor** [comment]
```
Requiring types for third-party code is a bad move.
It'd be like requiring all third-party code align to your specific linting preferences or code style.
```
I don't understand the parallel with linting.
Code style is different than describing your functions inputs/outputs.

You already did a huge work describing those inputs/output in the documentation using [a finite list of types](https://github.com/lodash/lodash/blob/master/dist/lodash.core.js#L34) (which are, for most of them, standard JS raw types).
I regularly use lodash in my Typescript projects, and having a "non official" typings brought by the community is somewhat misleading :
- Only a few lodash versions are described (for instance, on DefinitelyTyped, [we only have typings for lodash 3.10](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/lodash) currently), meaning that if we rely on another lodash version than 3.10, at best, function descriptors will be missing, and at worst, it will compile well and fail at runtime
- The quality of those typings may vary from one project to another : having an "official" support from project maintainers would greatly increase this

I think there might be something achievable parsing lodash documentation stuff and automatically transforming it into a Typescript / Flow type descriptors.
