### ISSUE TITLE
Intersection with deep-comparison

### ISSUE THREAD

**Issue by bernardocs** [lodash/lodash#2796]
Hey guys...

Any ideia on how to make use of `_.intersection(foo, bar)`, given that `foo` and `bar` are arrays of complex objects.
```javascript
/* 
consider objects with a format similar to this:
{ name: '', category: '', product_list: [], main: { id: 2, name: '',  ... } }
*/
let foo = [obj1, obj2, obj3];
let bar = [obj4, obj5, obj6];
_.intersection(foo, bar);
```
I have a hint that, in my case, in a behavior like "Preview Step" of a multistep form, the `bar` array is "repopulated" when the component is reloaded (angular reloads the directive for some reason), with the same list with the same values... but it loses the references from the old ones.

Any suggestions?

**Comment by jdalton** [comment]
Hi @bernardocs!

Try [_.intersectionWith](https://lodash.com/docs/#intersectionWith):
```js
var objects = [{ 'x': 1, 'y': 2 }, { 'x': 2, 'y': 1 }];
var others = [{ 'x': 1, 'y': 1 }, { 'x': 1, 'y': 2 }];
 
_.intersectionWith(objects, others, _.isEqual);
// => [{ 'x': 1, 'y': 2 }]
```

**Comment by bernardocs** [comment]
I'm using 3.10.1 version and dealing with legacy code... but it's the fourth time that I'm in need of something from the current version.
I think I'll enforce the upgrade and deal with the compatibilty problems.

Anyways... thanks. 😄
