### ISSUE TITLE
No tags for releases after 4.15.0

### ISSUE THREAD

**Issue by srudchandran** [lodash/lodash#2797]
There are no tags for releases after 4.15.0. Please tag.

**Comment by jdalton** [comment]
Hi @srudchandran!

It looks like [there is a tag](https://github.com/lodash/lodash/tree/4.15.0).

**Comment by srudchandran** [comment]
I meant 4.15.0 is the last tag. Tags for 4.16.x releases are missing.

**Comment by jdalton** [comment]
Oh, there's [plenty](https://github.com/lodash/lodash/tree/4.16.6) of those too.

**Comment by srudchandran** [comment]
I meant [tags](https://github.com/lodash/lodash/tags)

**Comment by jdalton** [comment]
They [are there](https://github.com/lodash/lodash/tags?after=3.0.8-npm-packages too).
```shell
git tag -l "4.16.*"
```
will output
```
4.16.0
4.16.0-amd
4.16.0-es
4.16.0-npm
4.16.1
4.16.1-amd
4.16.1-es
4.16.1-npm
4.16.2
4.16.2-amd
4.16.2-es
4.16.2-npm
4.16.3
4.16.3-amd
4.16.3-es
4.16.3-npm
4.16.4
4.16.4-amd
4.16.4-es
4.16.4-npm
4.16.5
4.16.5-amd
4.16.5-es
4.16.5-npm
4.16.6
4.16.6-amd
4.16.6-es
4.16.6-npm
```

**Comment by pravi** [comment]
tags page on github is not showing the latest release on the first page, so debian cannot find the latest versions https://tracker.debian.org/pkg/node-lodash (the latest version it can find is 4.15.0) github.com tags page does not give any other option to sort the page.

**Comment by jdalton** [comment]
Looks like they have a scraping issue. They should probably avoid scraping and rely on git.
