### ISSUE TITLE
_.intersectionWith() calling comparator with wrong parameters

### ISSUE THREAD

**Issue by wineet1** [lodash/lodash#2798]
When I call `_.intersectionWith()` with two different object arrays, the comparator function is sometimes called with items in the first array as a parameter to the second.

Ex.

```
let docs = [
  {_id: 'DOC-1'},
  {_id: 'DOC-2'},
  {_id: 'DOC-3'},
  {_id: 'DOC-4'}
];

let products = [
  {_id: 'PRODUCT-1', offeringData: {tasks: {content: {docId: 'DOC-1'}}}},
  {_id: 'PRODUCT-2', offeringData: {tasks: {content: {docId: 'DOC-2'}}}},
  {_id: 'PRODUCT-3', offeringData: {tasks: {content: {docId: 'DOC-3'}}}}
];

let duplicateList = _.intersectionWith(docs, products,
  (doc, product) => {
    console.log('Doc Id     - ' + doc._id);
    console.log('Product Id - ' + product._id);
    return doc._id ===
      product.offeringData.tasks.content.docId;
  }
);
```

The output of the above is 
```
Doc Id     - DOC-1
Product Id - PRODUCT-1
Doc Id     - DOC-2
Product Id - DOC-1      <-- This was supposed to be an item from `products`

And then it errors because it couldn't find `offeringData.tasks` in the elements of `docs`
```

To resolve this I can check for the type of the parameter say `doc` or `product` and then make the comparison. 

But I think the comparator must be called with the items in the same respective arrays.

**Comment by jdalton** [comment]
Hi @wineet1!

The comparator is currently being called as `(firstArrayValue, otherArrayValue)`.
The `otherArrayValue` is sometimes an item in `result` because it scans it to avoid duplicates.

**Comment by wineet1** [comment]
Got it... Thanks! :)

**Comment by davidshepherd7** [comment]
Hi, can I just clarify: does this means that all of the arrays must be of the same type?

Would it be worth explicitly stating this in the documentation? It took me quite a while to figure out a similar problem. Happy to make a PR if so.

**Comment by jdalton** [comment]
@davidshepherd7 Object instances are unique so using something like `intersectionBy` or `intersectionWith` can help different but a-like objects to be processed as if they were the exact same object instance.
