### ISSUE TITLE
_.defaultsDeep work incorrect

### ISSUE THREAD

**Issue by keyiis** [lodash/lodash#2799]
Below is code
```
let a={aa:'aaa'};
_.defaultsDeep(a,{aa:'bbb'});
console.log(a);
```
i hope get {aa:'bbb'} but still get {aa:'aaa'} ,why?

**Comment by demoneaux** [comment]
`_.defaults` and `_.defaultsDeep` only assign properties to the object if they are `undefined`. If they are already defined, `_.defaults` and `_.defaultsDeep` will not assign properties to the object. If you do want to override properties which already exist, you can use [`_.assign`](https://lodash.com/docs/#assign).

**Comment by keyiis** [comment]
@demoneaux thanks reply?
```
let a={aa:'aaa',b:null};
_.defaultsDeep(a,{aa:null,b:100});
console.log(a);
```
i want get {aa:'aaa',b:100},how to?

**Comment by jdalton** [comment]
@keyiis you'd have to get creative with [`_.assignWith`](https://lodash.com/docs/#asignWith).

**Comment by keyiis** [comment]
@jdalton thanks reply!maybe need implement this function by own,but i think this is common requirement。
