### ISSUE TITLE
Some problem with sumBy function

### ISSUE THREAD

**Issue by AnsonHwang86** [lodash/lodash#2800]
Hi, i find there is some problem with sumBy

when i use it with vuejs in computed property which will caculate value many time.

```
totalQuantity () {
          return _.sumBy(this.itemList, function (o) {
            return o.quantity
          })
      }
```
The first time i caculate in the right way.
But after i chang this.itemList.item.quantity. it caculate second time with a large number ,seem the sumBy treate this.itemList.item.quantity as string.
I change the code as below to fix this.
```
totalQuantity () {
          return _.sumBy(this.itemList, function (o) {
            return _.parseInt(o.quantity)
          })
      }
```
Is it needly to add parseInt method in the source code ?

**Comment by jdalton** [comment]
Hi @AnsonHwang86!

> Is it needly to add parseInt method in the source code ?

Yes. You can do `return +o.quantity`.

**Comment by AnsonHwang86** [comment]
@jdalton thanks!
