### ISSUE TITLE
_.defaultsDeep incorrectly works with array values.

### ISSUE THREAD

**Issue by seth2810** [lodash/lodash#2801]
When I apply `_.defaultsDeep` for objects which have properties represented as array I got strange behavior: 

```
_.defaultsDeep({config: ['a/b']}, {config: ['b/a', 'c/d']}) // {config: ["a/b", "c/d"]} 
```

I expect that `config` property value doesn't change because it already has value. Could somebody tell me why it's possible?

**Comment by seth2810** [comment]
After some research I found this line https://github.com/lodash/lodash/blob/master/lodash.js#L6530 and as I know `_.isObject` returns `true` for arrays.

**Comment by jdalton** [comment]
Moved to #2802.
