### ISSUE TITLE
Add lodash functional programming document

### ISSUE THREAD

**Issue by nhducit** [lodash/lodash#2804]
I love lodash, but I found that it's hard to apply lodash/fp to my project because I just geting fimilar with functional programming and lodash is lack of functional programming document like Ramda.js

**Comment by jdalton** [comment]
Hi @nhducit!

See https://github.com/lodash/lodash/wiki/FP-Guide.

**Comment by zhaoyao91** [comment]
Thanks for this guide, but I think it's better to have a fp documentation like the one of normal lodash. In this way we can reference what function we need directly, instead of finding the normal version and try to mapping it into fp version.

**Comment by rpadovani** [comment]
@jdalton that's cool :) There is any way to have it in a cool website like https://lodash.com/docs/4.17.4 ?
Do you accept community contributions on that?

**Comment by jfmengels** [comment]
@rpadovani I started working on https://github.com/jfmengels/lodash-fp-docs a long time ago. The result can be seen [here](https://gist.github.com/jfmengels/6b973b69c491375117dc) (a bit outdated though, I should at least update it).

It's working for most of the cases, but there are certain errors.
If the generated document is well-mae, I think it wouldn't be too hard to add it to the Lodash official docs. But at the moment, it's too buggy for an official documentation...
I haven't worked on it in a while, guess I found more interesting problems to tackle. And this did already solve my own itches (I still look at it from time to time, and it's correct often enough for it to be useful to me).

**Comment by jdalton** [comment]
I think once we split `lodash/fp` back out into `lodash-fp` it will help it have its own identity and then we can have a separate documentation effort around it.

**Comment by jfmengels** [comment]
Will lodash-fp also be a different repo, or simply a different package?

**Comment by jdalton** [comment]
I'll move lodash-fp from `lodash/lodash-archive` to the `lodash/lodash`.
