### ISSUE TITLE
function that maps arguments onto functions

### ISSUE THREAD

**Issue by MoeSattler** [lodash/lodash#2805]
Hey!
I am looking for a method in which I can do this:

`func = ([f1, f2, f3], [a1, a2, a3]) => [f1(a1), f2(a2), f3(a3)]`

Does something like that exist yet?

**Comment by jdalton** [comment]
Hi @MoeSattler!

Not exactly. We have some "over" methods like [_.over](https://lodash.com/docs/#over) and [_.overArgs](https://lodash.com/docs/#overArgs) which are close.
