### ISSUE TITLE
Getting Error: (SystemJS) XHR error (404) loading.............................lodash

### ISSUE THREAD

**Issue by j-tee** [lodash/lodash#2806]
I have been trying to get lodash to work in my app without success.
after the installation everything looks fine until i tried importing lodash

This "import * as _ from 'lodash';" doesn't work
I get the error "module not found"
but this  "import * as _ from '@types/lodash';" works fine 
until runtime the n my nightmares begin. I get the error message
"Error: (SystemJS) XHR error (404) loading https://localhost:44382/libs/@types/lodash(…)"
the following is a link to the file where I am importing lodash
https://github.com/j-tee/ReportBook1/blob/master/ReportBook.Web/scripts/services/shared/items.service.ts
I am using Visual Studio 2015 Update 3

**Comment by jdalton** [comment]
Hi @j-tee!

We don't maintain the `@types/lodash` package or support for it. That said you're trying to do a namespace import which may be the problem. Try doing a default member import instead:
```js
import _ from 'lodash';
```

**Comment by j-tee** [comment]
I did resolve issue. It turned out to be  a compartibilty issue with the
version of typescript I was using
