### ISSUE TITLE
_.mapValuesPreservingType

### ISSUE THREAD

**Issue by oprogramador** [lodash/lodash#2807]
I would like to have the following method:
```javascript
var array = [1, 5, 3];
console.log(_.mapValuesPreservingType(array, value => value * 2)); // [2, 10, 6]
var object = { foo: 1, bar: 5, baz: 3 };
console.log(_.mapValuesPreservingType(array, value => value * 2)); // { foo: 2, bar: 10, baz: 6 }
```

Unfortunately `_.mapValues` for array returns an object.
Are PR with such a method welcome?

**Comment by jdalton** [comment]
Hi @oprogramador!

You could create small that juggles between `_.map` and `_.mapValues`.
