### ISSUE TITLE
Performance regression in _.omit in 4.17.0

### ISSUE THREAD

**Issue by molily** [lodash/lodash#2812]
When using `_.omit` on an object with large object properties, the performance drops. When profiling, I see that the time is mostly spent in `baseClone`. It seems `baseClone` calls itself recursively for all properties. Looks like a deep clone for no reason. Will investigate further.

https://github.com/lodash/lodash/blob/4.17.0/lodash.js#L13481
https://github.com/lodash/lodash/blob/4.17.0/lodash.js#L2721

Quick perf comparison:
https://jsperf.com/lodash-4-17-0-omit3

**Comment by jdalton** [comment]
Hi @molily!

This is by design. With this release I added a note the [_.omit](https://lodash.com/docs/4.17.0#omit) docs as a heads up too. The `_.omit` method must basically grab all it can and then omit what you don't want which is heavier than just `_.pick`ing what you do want.

**Comment by jdalton** [comment]
I've [address the perf issue](https://github.com/lodash/lodash/commit/6c427b7a260183685b16d2624351529cda25ce81) by avoiding a deep clone for the common case.
