### ISSUE TITLE
lodash/fp doesn't have WithKey variants.

### ISSUE THREAD

**Issue by phadej** [lodash/lodash#2814]
I expect there to exist:

```js
_.eachWithKey((k, v) => console.log(k, v), { k1: "v1", k2: "v2" });
// k1 v1
// k2 v2
```

and at least:
```js
mapWithKey
someWithKey
everyWithKey
```

**Comment by jdalton** [comment]
Hi @phadej!

We don't offer `WithKey` variants because you can [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert) to it with a `cap` of `false`.

**Comment by phadej** [comment]
thanks!

**Comment by phadej** [comment]
comment: is it possible to cap to `n` arguments?, i.e.
```
fp.each.convert({ cap: 2 });
```

**Comment by jdalton** [comment]
>comment: is it possible to cap to exactly `n` arguments?, i.e.
```js
fp.each.convert({ cap: 2 });
```

Not at the moment, but it could be. I'll look into it.
