### ISSUE TITLE
_.pickBy and _.pick seem broken in 4.17.0

### ISSUE THREAD

**Issue by felixjung** [lodash/lodash#2815]
Hi,

I've noticed there've already been some now closed issues regarding `_.omitBy` (#2811), or `_.pickBy` (#2808) behavior when used with keys containing periods in 4.17.0. In addition to the addressed case with periods, the functions seem to break when object keys contain brackets ("[]"). Here's an example:

```javascript
const foobar = {
  'foo[]': [1, 2, 3],
  'bar[]': []
};

_.pickBy(foobar, value => !_.isEmpty(value));
/*
 * Expected:
 *  { 'foo[]': [1, 2, 3] }
 * Actual:
 *  { foo: { : [1, 2, 3] } }
 */

_.pick(foobar, 'foo[]')
/*
 * Expected:
 *  { 'foo[]': [1, 2, 3] }
 * Actual:
 *  { foo: { : [1, 2, 3] } }
 */
```

I guess this is not intended behavior, right?

**Comment by jdalton** [comment]
Dup of #2808.
