### ISSUE TITLE
yarn.lock

### ISSUE THREAD

**Issue by stephenmathieson** [lodash/lodash#2816]
Seems like we shouldn't have a `yarn.lock` file here, since yarn itself doesn't support it in library code.

Read more here: https://medium.com/@boennemann/avoid-yarn-for-packages-and-fully-enjoy-its-benefits-for-application-development-8bdd4deb33cf#.ioey0xwl1

**Comment by jdalton** [comment]
The `yarn.lock` file isn't in the [npm package](https://github.com/lodash/lodash/tree/npm) branch. The master branch is for testing, package generation, & dev deps.

**Comment by stephenmathieson** [comment]
Ahhhhhhh, got it. Didn't notice all that jazz :p

Thanks!
