### ISSUE TITLE
omitBy + merge behaving differently in v4.17.0

### ISSUE THREAD

**Issue by CoryG89** [lodash/lodash#2818]
It seems that the following usage of `omitBy` and `merge` is behaving differently in the latest version `4.17.0`. It seems that it is handling differently the merging of objects w/ properties that contain the dot (".") character in their names.

The return value of this is different depending on whether you are running 4.16.6 or 4.17.0:

```js
var obj1 = {
  "foo.bar": "hello"
};

var obj2 = {
  "baz": "hi",
  "boo": null
};

console.log(_.omitBy(_.merge(obj1, obj2), function (val) { return val === null; }));

/*
   On 4.16.6 this returns -- {foo.bar: "hello", baz: "hi"}
   On 4.17.0 this returns -- {foo: {bar: "hello" }, baz: "hi"}
*/
```

I see that both merge and omit had some changes in 4.17.0.

Here are two jsfiddles, only difference is lodash version being used:

4.16.6: https://jsfiddle.net/2cr85151/ (working as expected)
4.17.0: https://jsfiddle.net/mzccgqha/ (???)

Is this new behavior expected?

**Comment by jdalton** [comment]
Dup of #2808.
