### ISSUE TITLE
omit doesn't behave the same since 4.17

### ISSUE THREAD

**Issue by tleunen** [lodash/lodash#2819]
I'm using omit() to remove a few properties before checking if 2 objects are equals with shallowEqual and since the update, I have a few failing tests in my project. After a quick investigation, I've found out objects are causing the issue.

This returns false instead of true:
```
shallowEqual(
  omit({
    source: {}
  }, 'sth'),
  omit({
    source: {}
  }, 'sth')
)
```

**Comment by jdalton** [comment]
Dup of #2810.
