### ISSUE TITLE
add index.js? (lodash-es)

### ISSUE THREAD

**Issue by Shyam-Chen** [lodash/lodash#2820]
```js
import defaults from 'lodash-es/defaults';
import partition from 'lodash-es/partition';

console.log(defaults({ 'a': 1 }, { 'a': 3, 'b': 2 }));
console.log(partition([1, 2, 3, 4], n => n % 2));
```

```js
// with tree-shaking (via Rollup)
import { defaults, partition } from 'lodash-es';

console.log(defaults({ 'a': 1 }, { 'a': 3, 'b': 2 }));
console.log(partition([1, 2, 3, 4], n => n % 2));
```

**Comment by jdalton** [comment]
Hi @Shyam-Chen!

The main file in `lodash-es` is [/lodash.js](https://github.com/lodash/lodash/blob/es/package.json). Unfortunately tree-shaking support via rollup or webpack 2 isn't quite there yet so you'll need to use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash).

**Comment by andresgutgon** [comment]
What is the state of this now that Webpack 2 is out? 
I tryed installing `lodash-es` and just importing `import map from 'lodash-es/map'` but it looks like the whole lodash is on generated webpack bundle.
