### ISSUE TITLE
pickBy expands keys with '.' in them

### ISSUE THREAD

**Issue by sean-shirazi** [lodash/lodash#2821]
Using lodash 4.13.1:

```js
_.pickBy({'asdf.fds.wer': 'abc'}, x => true)
// output: { asdf: { fds: { wer: 'abc' } } }
// expected output: {'asdf.fds.wer': 'abc'}
```

**Comment by jdalton** [comment]
Congrats @sean-shirazi. You'r the 6th person today to not check issues before filing them 🎉 

Dup of #2809.

**Comment by sean-shirazi** [comment]
@jdalton oops :D should've checked closed issues as well.
