### ISSUE TITLE
_.clone does not clone objects with Symbol.toStringTag

### ISSUE THREAD

**Issue by DerFlatulator** [lodash/lodash#2822]
LoDash Version: 4.16.2.

```js
_.clone({
  prop: 'val',
  [Symbol.toStringTag]: "Foo"
})
```
**Expected:**
* A copy of the object

**Actual:**
* Produces a new plain object with no properties.

This is because `'[object Foo]'` is not in `cloneableTags`.
https://github.com/lodash/lodash/blob/master/lodash.js#L2697

Not sure how related this is to #2705.

**Comment by jdalton** [comment]
Hi @DerFlatulator!

This has been resolved in later versions.

**Comment by DerFlatulator** [comment]
Ah, my bad. For one reason or another I thought I was on the latest.

Thanks for the quick response.
