### ISSUE TITLE
_.pick picks wrongly and messes up result when using deep path

### ISSUE THREAD

**Issue by frakti** [lodash/lodash#2823]
Version: 4.17.1
After recent changes I would expect given test case to pass:

```js
    QUnit.test('should support deep paths', function(assert) {
      assert.expect(1);

      var object = { 'a.b.c': 1, a: {b: {c: 2}}},
          actual = _.pick(object, ['a.b.c']); // or  _.pick(object, 'a.b.c');
 
      assert.deepEqual(actual, {a: {b: {c: 2}}});
    });
```
but `actual` is `{"a":{"b":{"c":1}}}`.
The same happens with `_.omit`but since it's the same code base, I'm not creating separate issue.

Also suggest update docs which are not clear about deep paths/properties.

**Comment by ernoaapa** [comment]
:+1: Oh yes same happens here! I wonder why my tests suddenly started to fail (thank god I had tests :) )
Will use @frakti [workaround](https://github.com/lodash/lodash/issues/2824#issuecomment-260604358)  `_.pick(object, [['a.b.c']])`

**Comment by frakti** [comment]
Actually it's not workaround but new way of handling dot in the path.

**Comment by jdalton** [comment]
Hi @frakti!

Because `_.pick` has traditionally accepted an array of keys this `_.pick(o, ['a', 'b', 'c']) is seen as picking `o.a`, `o.b`, & 'o.c'. So to use an array path you'll want to do `_.pick(o, [['a', 'b'], 'c'])` which picks `o.a.b` and `o.c`.
