### ISSUE TITLE
forEach + spread behaviour changed in 4.17

### ISSUE THREAD

**Issue by Loghorn** [lodash/lodash#2825]
If you try this simple program with Lodash 4.16.6 and 4.17.1 you'll get two very different results:

    var _ = require('lodash');
    var test = _.spread(function(a, b, c, d) { console.log(a, b, c, d); });
    _.forEach([
	  ['X', 'Y'],
	  ['Z']
    ], test);

With Lodash 4.16.6

    X Y undefined undefined
    Z undefined undefined undefined

With Lodash 4.17.1

    X Y 0 [ [ 'X', 'Y' ], [ 'Z' ] ]
    Z 1 [ [ 'X', 'Y' ], [ 'Z' ] ] undefined

**Comment by jdalton** [comment]
Hi @Loghorn!

Interesting use case!

**Comment by Loghorn** [comment]
Thank you for the quick fix
