### ISSUE TITLE
pick behaviour changed in 4.17

### ISSUE THREAD

**Issue by pjanuario** [lodash/lodash#2826]
If you try this simple program with Lodash 4.16.6 and 4.17.1 you'll get two very different results:

```
var _ = require('lodash');
_.pick({ 'abc:1.0': true }, 'abc:1.0');
```

With lodash 4.16.6

`{ 'abc:1.0': true }`

With lodash 4.17.1

`{ 'abc:1': [ true ] }`

**Comment by jdalton** [comment]
Thanks @pjanuario!

This has uncovered that we need to tighten up our `_.toPath` method.

**Comment by pjanuario** [comment]
No worries I just come accross with it because was caught in a Integration test of our client. The problem is also mentioned in the microservices library. I will try to look into the problem in the upcoming week to see if I can create PR. I am not familiar with codebase, but I will try to! :)

**Comment by jdalton** [comment]
I think we can handle this like we do with `_.get` and `_.has` where if a property exists use that instead of treating it like a deep path.

**Comment by jdalton** [comment]
I'll have a v4.17.2 patch release out sometime today.
