### ISSUE TITLE
Reducing array that returns objects with function values for keys

### ISSUE THREAD

**Issue by granteagon** [lodash/lodash#2827]
This is a tricky one and it doesn't work in Vanilla JS either.  But I thought I would show the example here and possibly make it a feature request if it seems valid.

Here's a plunker to explain what I'm trying to do: https://plnkr.co/edit/NEidazmhdiZddNe6MBIz?p=preview

**Comment by jdalton** [comment]
Hi @granteagon!

I think something like that is perfect for [_.reduce](https://lodash.com/docs/#reduce) or [_.transform](https://lodash.com/docs/#transform).

**Comment by granteagon** [comment]
The problem is if you try to assign a function to a key on the accumulator, it never gets defined.

**Comment by Archimidis** [comment]
Hey @granteagon , you output the JSON.stringify [which omits functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description). If you check the console.log output you'll see what you expect.
