### ISSUE TITLE
Lodash documentation website search

### ISSUE THREAD

**Issue by Ephapox** [lodash/lodash#2828]
The search bar for the lodash documentation site isn't working. I'm assuming it's an issue with Fuse, the fuzzy search library.

![screen shot 2016-11-16 at 3 13 25 pm](https://cloud.githubusercontent.com/assets/8016648/20369710/7f24c7d2-ac0f-11e6-82f0-d903e34e17a1.png)

**Comment by jdalton** [comment]
Dup of https://github.com/lodash/lodash.com/issues/106.
