### ISSUE TITLE
_.template: "interpolate" and "escape" delimiters act as the "evaluate" delimiter

### ISSUE THREAD

**Issue by EvgenyOrekhov** [lodash/lodash#2829]
```js
_.template("<%= JSON %>")(); // returns "[object JSON]"
_.template("<%- console.log(123) %>")(); // logs 123 to the console
```

Lodash version: 4.17.2

**Comment by jdalton** [comment]
Hi @EvgenyOrekhov!

Lodash's template function treats stuff inside the delimiters as expressions so the result of the expression is what's evaluated.

In the case of `_.template("<%= JSON %>")()` the `JSON` object is coerced to a sting.
In the case of `_.template("<%- console.log(123) %>")();` the console log is executed and the result `undefined` is treated as empty `''`.
