### ISSUE TITLE
_.skip to drop first arguments by function call

### ISSUE THREAD

**Issue by SeregPie** [lodash/lodash#2830]
I didn't find any similar functions, so I'm using this.

```javascript
_.mixin({skip: function(func, n) {
	// n default 1
	return function() {
		return func.apply(this, _.drop(arguments, n));
	};
}});
```

The use cases are particularly the jQuery event listeners. Here is a simplified example.

```javascript
function addItem(text) {
	$(this).append($('<div>', {text: text}));
}
$('#foo').on(':addItem', _.skip(addItem));
/* ... */
$('#foo').triggerHandler(':addItem', ['Hello World!']);
```

Without `_.skip` I would need to write something like this ...

```javascript
$('#foo').on(':addItem', function(event, text) {
	addItem.call(this, text);
});
```
... or this ...
```javascript
$('#foo').on(':addItem', function() {
	addItem.apply(this, _.tail(arguments));
});
```

It would be nice to have this feature as a standard.

**Comment by jdalton** [comment]
Thanks @SeregPie!

I'd prefer folks start using arrow functions and spread for this kind of thing.

**Comment by SeregPie** [comment]
Arrow functions and spread are not supported in all used browsers.
And eeeeh... how do you use arrow functions and spread in this kind of thing? Can you give me an example? I think you didn't understand the issue.

**Comment by jdalton** [comment]
> Arrow functions and spread are not supported in all used browsers.
I don't understand, how do you use arrow functions and spread here? 

That's where something like [babel](https://babeljs.io/) comes in. It even has [a preset](https://github.com/babel/babel-preset-env) to scope transpiling to a minimum environment bar of your choice.

**Comment by Andarist** [comment]
@SeregPie 

version without configurable amount of skipped values - `const skip1 = (fn) => (_, ...args) => fn(...args)`

version with that being configurable:
`const skip = (fn, n = 1) => (...args) => fn(drop(n, args))`

not much different from yours, just written in alternate, more concise syntax
