### ISSUE TITLE
Difference between 2 complex objects

### ISSUE THREAD

**Issue by pasmoi75** [lodash/lodash#2831]
Hello,

I have a problem that's , I have one complex object A, i'm deepCloning it in a object B ( with deepClone ). I want to check if their values are equals, so i'm using isEqual that throws "true" , but when I call an another just after which use isEquals, the answer is "false". 
Thank you

```
init() {
this.treeObject = tree; 
this.treeObjectCopy = cloneDeep(this.treeObject);
console.log(isEqual(this.treeNodes, this.treeNodesWithoutModification));
}

isTrue() {
console.log(isEqual(this.treeNodes, this.treeNodesWithoutModification));
}

// response is 'true'
init();

// response is 'false'
isTrue();
```

**Comment by jdalton** [comment]
Hi @pasmoi75!

Based on the example I'm not too sure what the root issue is.
You should visit our [gitter chat](https://gitter.im/lodash/lodash) for help.

**Comment by pasmoi75** [comment]
The problem was that my front view changed my tree between the init and the isTrue call .
Thank you
