### ISSUE TITLE
[question] lodash/fp compiled file not included

### ISSUE THREAD

**Issue by jdkschang** [lodash/lodash#2832]
After installing lodash via npm I have been including the dependency by referencing the lodash.min.js under `[node_modules]/lodash/lodash.min.js`.  I also wanted to leverage the fp library, but can't seem to find a similarly compiled version; 

Although I could reference the cdn link shown in the [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide), I would appreciate if there was a similarly compiled lodash/fp file I could include in my build process- or if someone could direct me to said file

Thanks in advance

**Comment by jdalton** [comment]
Hi @jdkschang!

The cdn'd copy is built via `npm run build:fp` from the `master` branch. We don't ship it with the package since the package will leverage modules under the hood to create the function wrappers.

**Comment by jdkschang** [comment]
hi @jdalton!

Brilliant- makes sense. Thanks for the quick response!
