### ISSUE TITLE
Function remove seems broken 

### ISSUE THREAD

**Issue by poupougnac** [lodash/lodash#2833]
Hi,
I can't delete any element. I also tried remove() with predicate, it's not working.
```
const low = require('lowdb')
const storage = require('lowdb/lib/file-sync')
const dbLibrary = low('db/library.json', { storage })

// display correctly my element
console.log(dbLibrary.get('library').find({id: '283c7121-c4ee-4202-909d-31cae07f6c6d'}).value())
// ouput the element

console.log(dbLibrary.get('library').remove({id: '283c7121-c4ee-4202-909d-31cae07f6c6d'}).value())
// doesn't remove the element and display [ ]
```

I finally found a way with "reject" but I don't know why remove doesn't work for me.
Thank you.

**Comment by jdalton** [comment]
Hi @poupougnac!

I think you may have the wrong place.
This is the `lodash` repo issue tracker and not the `lowdb` issue tracker.

**Comment by poupougnac** [comment]
My bad, wrong page :( sorry

**Comment by jdalton** [comment]
No worries @poupougnac 😅
