### ISSUE TITLE
Links to documentation line numbers aren't resolving

### ISSUE THREAD

**Issue by danielehrlich** [lodash/lodash#2838]
In the documentation file, the links that reference source code line numbers underneath method names have the postfix '-pre' appended to the version number part of the link: 

`https://github.com/lodash/lodash/blob/4.17.2-pre/lodash.js#L6876`

These links won't resolve and give a 404 error. However if you remove '-pre', the link works fine. I'm about to create a pull request for this and link to this issue, but wanted to document this here.

**Comment by jdalton** [comment]
Moved to #2839.
