### ISSUE TITLE
isEqual seems to ignore symbol key properties

### ISSUE THREAD

**Issue by mightyiam** [lodash/lodash#2840]
```js
_.isEqual({[Symbol()]: undefined}, {})
// true
```

**Comment by mightyiam** [comment]
Hints:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1318933
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols

**Comment by jdalton** [comment]
Thanks for the report. No thanks for the issue cc spam :lock:

I'm aware of symbols. It appears you're blanket posting a bunch of projects. You should be aware that getting symbols is not cheap and will drag down the perf of any method that adds support. 

That said, we support cloning them with `_.clone` and `_.cloneDeep` I just haven't added support here for them in `_.isEqual`, yet. I'm not against it, though.

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash/commit/fd4808147d762ba40299bc67b5ae3807f20d6145.

**Comment by mightyiam** [comment]
Coming across this issue downstream in ava again and again. Mind releasing one, please?

**Comment by XeniaSiskaki** [comment]
I didn't want to create a new ticket before I know if my problem is really a bug.

That said, it seems to me that many lodash functions are ignoring Symbol keys.

Here is a small use case:

```
var data = {};
var x = Symbol("test");
data[x] = "test";
console.log(data) // prints {Symbol(test): "test"}
data = _.mapKeys(data, function(v, k) { return v; });
console.log(data); // prints {}
```

Why doesn't it work? Am I missing something?

**Comment by jdalton** [comment]
Hi @XeniaSiskaki!

The [`_.mapKeys`](https://lodash.com/docs#mapKeys) iterates over own string keys of an object. I like the separation and may provide alternative APIs in the future to cover the symbol case.
