### ISSUE TITLE
chained _.map with _.property iteratee shorthand

### ISSUE THREAD

**Issue by chamini2** [lodash/lodash#2841]
I had code that plucks an objects arrays in the `id` property

```js
_.map(objs, 'id')
```

and had to sort it first, so I changed it to

```js
_.sortBy(objs, 'position').map('id')
```

And lodash complained that `'id'` is not a function, wouldn't it be more consistent if the `_property` shorthand applies to chained functions too?

**Comment by jdalton** [comment]
Hi @chamini2!

You're not using the chaining syntax so you're calling [`Array#map`](mdn.io/Array/map) instead.
For chaining you'll want:
```js
_(objs).sortBy('position').map('id').value();
```
