### ISSUE TITLE
global leaks if webpack uses AMD

### ISSUE THREAD

**Issue by yinghaochan** [lodash/lodash#2842]
https://github.com/lodash/lodash/blob/master/dist/lodash.core.js#L3815

webpack by default transpiles 

` if (typeof define == 'function' && typeof define.amd == 'object' && define.amd) {`

to:

![image](https://cloud.githubusercontent.com/assets/7133601/20504993/3f38837c-afff-11e6-9f4b-73003bbfa920.png)

and exposes a global unless you specifically disable AMD.

**Comment by jdalton** [comment]
Hi @yinghaochan!

This is by design because Lodash's doesn't know the intent of the user. For example it could be loaded on a page that uses AMD but not loaded through AMD. If you don't want to leak the global you can call `_.noConflict()`.

**Comment by yinghaochan** [comment]
@jdalton  Ah, I see. Thanks for that explanation!

While reading intent looks like something for AMD, is there a reason for defaulting to overwriting an existing `root._`? 

Instead of doing something like `root._ = root._ || _;` 

_This would change our assumptions about lodash users slightly:_ 
that one _might_ want to load a lodash through a srcipt tag... 
and _perhaps_ also might have AMD floating around...
... but at least not dumb enough to mess up the loading order of scripts and intentionally overwrite a bunch of globals. 

because people here might have millions of LOC depending on some old version of underscore, and `import { guy_fieri } from 'babel-tower-of-modules' ` which depends on lodash could blow everything up.

**Comment by jdalton** [comment]
> Instead of doing something like `root._ = root._ || _;` 

It goes back to the [initial explanation](https://github.com/lodash/lodash/issues/2842#issuecomment-262103731). Since we don't know if the library is to be loaded by the AMD loader we have to treat it like a regular non-AMD enabled script too.

**Comment by jdalton** [comment]
It turns out this issue is due to a Webpack transform [that's catered to end users and not libraries](https://github.com/webpack/webpack/issues/4465#issuecomment-285850829), like Lodash, that have AMD support. For the time being, Webpack recommends [opting-out of their AMD parsing](https://github.com/webpack/webpack/issues/3017#issuecomment-285954512) if you're running into issues.
