### ISSUE TITLE
Question about kebabCase() with mixed strings & numbers

### ISSUE THREAD

**Issue by kaelig** [lodash/lodash#2843]
I couldn't find any spec about kebab-case so I'm asking the question here directly.

Steps to reproduce:

```
var _ = require('lodash');
_.kebabCase('string1')
```

Expected: `string1` (maybe? - again… I couldn't find a spec)
Actual: `string-1`

I guess the question is: should `string` and `1` be considered as two separate words or not?

The npm package `kebab-case` (see https://www.npmjs.com/package/kebab-case) seems to consider `string` and `1` are part of a single word, and returns `string1`.

Here's a reduced test case:
https://runkit.com/58342f752aa75b00141c162a/58342f762aa75b00141c162b

**Comment by jdalton** [comment]
Hi @kaelig!

> Expected: `string1` (maybe? - again… I couldn't find a spec)

`_.kebabCase` like other casing methods relies on `_.words` to separate compound words. The specs are with `_.words`.

> The npm package `kebab-case` (see https://www.npmjs.com/package/kebab-case) seems to consider `string` and `1` are part of a single word, and returns `string1`.

I'm a bit confused why you're using the `kebab-case` package, a package with 2 commits, 5 tests, and released a year after Lodash introduced kebabCase, as your standard by which you measure Lodash.

We treat numbers as separate in most cases:
```js
'walk500Miles' // is treated as words "walk 500 miles"
'12ft' // is "12 ft"
'tooLegit2Quit' // is "too legit 2 quit"
'isISO8601' // is "is ISO 8601"
```
The exceptions are
```js
'1st' // is '1st'
'14th' // is '14th'
```

**Comment by kaelig** [comment]
Thanks for your detailed answer!

> Why are you using the kebab-case package, a package with 2 commits, 5 tests, and released a year after Lodash introduced kebabCase, as your standard by which you measure Lodash? It seems kind of arbitrary.

You're right, absolutely arbitrary! Again, I couldn't find a spec so I looked around npm and found this other package.

The reason I asked is I have a use-case where `string1` needs to be kept as is, while transforming the rest of the set of strings as kebab-case, which I think I'll treat as an edge case instead of using the kebabCase function since there's no spec.

Thanks again for your answer and thanks for the awesome work on Lodash!
