### ISSUE TITLE
CreateListFromArrayLike called on non-object

### ISSUE THREAD

**Issue by hpurmann** [lodash/lodash#2844]
Hey @jdalton!
Lodash `4.17.2` broke the build of [yourchoice](https://github.com/actano/yourchoice/pull/46). Here is the [build log](https://travis-ci.org/actano/yourchoice/builds/176295227).

It says
```
  1) rangeTo - range selection change current range when selecting new range range select after deselection happened when deselecting the anchor with remove "before each" hook for "should return range using bottommost selected item as anchor":
     TypeError: CreateListFromArrayLike called on non-object
      at node_modules/lodash/fp/_baseConvert.js:88:12
      at l (node_modules/lodash/lodash.min.js:50:176)
      at r (node_modules/lodash/lodash.min.js:5:194)
      at u (node_modules/lodash/lodash.min.js:47:481)
      at src/operations.js:152:15
      at l (node_modules/lodash/lodash.min.js:50:176)
      at node_modules/lodash/lodash.min.js:49:159
      at Context.<anonymous> (test/range-to.unit.js:290:22)
```

I can reliably reproduce this with lodash `4.17.2` as opposed to `4.17.1` where this bug doesn't appear. Do you know what could cause this?

**Comment by jdalton** [comment]
Are you using  _.spread?

**Comment by hpurmann** [comment]
We are using [these](https://github.com/actano/yourchoice/blob/d4e8369a90a234dcb8830975e2379234acaf9eb3/src/operations.js#L1-L10)

**Comment by jdalton** [comment]
I don't see much. Maybe `_.without` which uses an fp spread helper under the hood.
You can [see our changelog](https://github.com/lodash/lodash/wiki/Changelog) for anything that might jump out.

**Comment by hpurmann** [comment]
Ok thanks! I'll investigate further and get back to you here. Seems like a pretty rare issue since nobody has reported it yet.

**Comment by jdalton** [comment]
If you find it let me know and I'll re-designate the issue.

**Comment by hpurmann** [comment]
Ok so I found the problem to be in our tests. We called `without` and passed a string as first argument. Apparently, this got implicitly converted to an array in `4.17.1` and before. Since this was never part of the official API, the mistake was of course ours. Thanks for the quick response.
