### ISSUE TITLE
Exclude non-enumerable symbol-key properties

### ISSUE THREAD

**Issue by mightyiam** [lodash/lodash#2845]
Following up from https://github.com/lodash/lodash/commit/fd4808147d762ba40299bc67b5ae3807f20d6145#commitcomment-19932280
I'd like to see the code for that. Loop over all of the retrieved symbol keys, examine with `getOwnPropertyDescriptor` and `splice` out if non-enumerable?

Perhaps in the future with [`Object.getOwnPropertyDescriptors`](https://tc39.github.io/ecma262/#sec-object.getownpropertydescriptors)? I do not know what may be less performant and in which situations. But, perhaps it doesn't return symbol keys.

**Comment by jdalton** [comment]
I'd use `propertyIsEnumerable` to check in a loop is all.
