### ISSUE TITLE
cloneDeepWith doesn't use customizer when recursing

### ISSUE THREAD

**Issue by sfinktah** [lodash/lodash#2846]
Test:

```
a = {b: 1, c: {d: [1, 2, 3]}, d: [1, 2]};
x = _.cloneDeepWith(a, o => { return console.log(o), o; })
```

Output:
```
Object {b: 1, c: Object, d: Array[2]}
```

Expected Output:
```
Object {b: 1, c: Object, d: Array[2]}
Object {c: Object}
Object {d: Array[2]}
etc...
```

**Comment by jdalton** [comment]
Hi @sfinktah

If you return a value from the customizer then you're saying "this is the value I want to use as the deep clone result" so there is no more processing done by `_.cloneDeep` at that point for the given value.

**Comment by mzedeler** [comment]
I think the documentation could be much clerarer on this point. I've just spent 30 minutes trying to make it work and couldn't until I found this. Would you accept a PR for a doc clarification?

**Comment by roni-frantchi** [comment]
Just encountered the same issue... This is really confusing.
What's the suggested approach to achieve what's described here?

**Comment by pauloavelar** [comment]
If I am getting it right we are supposed to write the recursion logic ourselves.  
If that's the case, then it's just as fast (and readable) to pass the object to be cloned to the customizer itself and have it spread the object on return.

What's the point of using lodash in this case?

**Comment by mzedeler** [comment]
I agree with @pauloavelar - the customizer function is useless if it isn't being used recursively, so if this is the intended behavior, I propose deprecating the customizer to avoid confusion.
