### ISSUE TITLE
Documentation: make the documentation about _.isEqual clearer

### ISSUE THREAD

**Issue by lovasoa** [lodash/lodash#2848]
The documentation of `_.isEqual` [states that](https://github.com/lodash/lodash/blob/4.17.2/lodash.js#L11509-L11510):

> Functions and DOM nodes are **not** supported.

Which made me think that giving such objects to the function raises an error, that they don't behave in a coherent way when given to the function, or at least that comparing them is discouraged. Is that on purpose ?

If not, this sentence could be rewritten as:

> Functions and DOM nodes are simply compared with the `===` operator.

**Comment by jdalton** [comment]
Feel free to open a PR if I don't get to it sooner.

**Comment by jdalton** [comment]
Moved to #2849.
