### ISSUE TITLE
The second param of the 'baseIteratee'

### ISSUE THREAD

**Issue by wmzy** [lodash/lodash#2851]
What is the '3' mean? Is it a slip of the pen?
https://github.com/lodash/lodash/blob/4.17.2-es/_createFind.js#L16

**Comment by jdalton** [comment]
Hi @wmzy!

It's an iteratee arity hint used by the [fp wrapper](https://github.com/lodash/lodash/blob/20eac46a5f90e0f5078174d0e76a990b1c987060/fp/_baseConvert.js#L206-L217).
