### ISSUE TITLE
Why FP merge convert getter to primitive?

### ISSUE THREAD

**Issue by bentinata** [lodash/lodash#2852]
This two yield different result.
While merge still retain `[Getter]`, FP merge make it primitive value.

```javascript
require(`lodash`).merge({
  val: `parent`,
  get getter() { return this.val; },
}, {
  val: `child`,
});

require(`lodash/fp`).merge({
  val: `parent`,
  get getter() { return this.val; },
}, {
  val: `child`,
});
```

**Comment by jdalton** [comment]
Hi @bentinata!

Our clone doesn't support getter/setters yet.
Since fp methods are immutable by default cloning is used.
You can change this with [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert).
