### ISSUE TITLE
Allow to provide a default value for _.invoke, similar to _.get(obj, 'noProp', 'default')

### ISSUE THREAD

**Issue by ArturBaybulatov** [lodash/lodash#2853]
This is a feature request (enhancement)

Having an object:

```javascript
var obj = {
    a: 'foo',
    b: undefined,
    A: function() {return 'FOO'},
    B: function() {return undefined},
}
```

<table>
<tr>
<th>Current _.get</th>
<th>Current _.invoke</th>
<th>Desired _.invoke</th>
</tr>

<tr>
<td>_.get(obj, 'a')<br>// =&gt; "foo"</td>
<td>_.invoke(obj, 'A')<br>// =&gt; "FOO"</td>
<td>same</td>
</tr>

<tr>
<td>_.get(obj, 'b')<br>// =&gt; undefined</td>
<td>_.invoke(obj, 'B')<br>// =&gt; undefined</td>
<td>same</td>
</tr>

<tr>
<td>_.get(obj, 'x')<br>// =&gt; undefined</td>
<td>_.invoke(obj, 'X')<br>// =&gt; undefined</td>
<td>same</td>
</tr>

<tr>
<td></td>
<td>_.invoke(obj, 'a')<br>// &gt;&gt; Error</td>
<td>_.invoke(obj, 'a')<br>// =&gt; undefined</td>
</tr>

<tr>
<td>_.get(obj, 'b', 'default')<br>// =&gt; "default"</td>
<td>add</td>
<td>_.invoke(obj, 'B', 'default')<br>// =&gt; "default"</td>
</tr>

<tr>
<td>_.get(obj, 'x', 'default')<br>// =&gt; "default"</td>
<td>add</td>
<td>_.invoke(obj, 'X', 'default')<br>// =&gt; "default"</td>
</tr>
</table>

**Comment by jdalton** [comment]
Hi @ArturBaybulatov!

It may be better if the result was a default function to invoke and not the default result. 

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by StreetStrider** [comment]
@jdalton 
> It may be better if the result was a default function to invoke and not the default result.

Good point. It is always a more flexible to have a «default function» rather than a default value. Default value `def` is a `constant(def)` in terms of default function, but latter allows custom behavior based on some input (like key).
