### ISSUE TITLE
Breaking change in omit combined with recursive objects

### ISSUE THREAD

**Issue by scholtzm** [lodash/lodash#2855]
Here's an example that crashes right away when using `v4.17` but works correctly with `v4.16`:

```js
const _ = require('lodash');

const obj = {
  foo: 'bar',
  get baz() {
    return _.omit(this, 'baz');
  }
};

console.log(obj.baz);
```

[Here's a complete example.](https://github.com/scholtzm/lodash-omit-issue)

**Comment by jdalton** [comment]
Hi @scholtzm!

This is a side effect of changes in the `_.omit` implementation. I recommend storing the `baz` value as a vanilla property instead of creating a new object each access with `_.omit`. This will also avoid the recursive getter access gotcha.

**Comment by scholtzm** [comment]
> This is a side effect of changes in the _.omit implementation.

Wouldn't this warrant a major version bump?

**Comment by jdalton** [comment]
We never claimed to support getter/setters. You've written bad code and got bit by an edge case. I'm not supporting that.
