### ISSUE TITLE
how to use "round" with always "up,down,general"?

### ISSUE THREAD

**Issue by thearabbit** [lodash/lodash#2858]
I would like to use `round` with always`up, down or general`
```js
_,round(1.234, 2); // general => 1.23

_.round(1.231, 2, 'up'); //always up=> 1.24

_.round(1.239, 2, 'down'); //always down => 1.23
```
please help me.

**Comment by javadev** [comment]
Yoy may add custom methods roundUp and roundDown, I think.

**Comment by jdalton** [comment]
@thearabbit You can also check out our [gitter chat](https://gitter.im/lodash/lodash) for help.

**Comment by thearabbit** [comment]
Thanks for your reply.
