### ISSUE TITLE
_.isFunction does not work with async functions

### ISSUE THREAD

**Issue by BigstickCarpet** [lodash/lodash#2860]
Chrome and Node.js now natively support ES2017 async/await.  However, `_.isFunction()` does not properly detect an async function as a function.  This is because internally, `_.isFunction()` checks for three specific `toString()` tags: `[object Function]`, `[object GeneratorFunction]`, and `[object Proxy]`, but async functions return `[object AsyncFunction]` instead.

```javascript
async function foo() {};
Object.prototype.toString.call(foo);           // --> [object AsyncFunction]
_.isFunction(foo);                             // --> false
```

**Comment by jdalton** [comment]
Dup of #2768.
