### ISSUE TITLE
Trim/increase array to a size

### ISSUE THREAD

**Issue by liviutudor** [lodash/lodash#2861]
Given an array I want to ensure it has a certain size. This has 2 cases:

* if the array has a larger size than requested then it needs to be trimmed. For this I want to specify the index where I want to remove the excess elements from -- e.g. `_.ensureSize(NEW_SIZE, {indexStart: 2})`
* if the array has a lower size than requested then I need to add items to the array. For this I want to specify the index where the items to be inserted (or at the end by default) and the value to be added each time -- e.g. `_.ensureSize(NEW_SIZE, {indexStart:-1, newValue:{}})` to append at the end or `_.ensureSize(NEW_SIZE, {indexStart: 3, newValue: "new value"})` to insert items starting at index 3.

**Comment by jdalton** [comment]
Hi @liviutudor!

You can do this with a combo of [Array#length](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/length) and [Array#fill](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/fill).
