### ISSUE TITLE
FP: Argument-less calls ignore default parameters

### ISSUE THREAD

**Issue by monk-time** [lodash/lodash#2863]
I was surprised to discover it is impossible in lodash/fp to partially fill in into any library function its default 
parameter. My expectation was that if I make an argument-less call of a curried function, lodash would use the default parameter for that arg, just like expected in JS or Python. For example: 
```
// JavaScript
let add = (x = 1) => y => x + y;
add()(5)  // 6
add(2)(5) // 7
// Python
add = lambda x=1: lambda y: x + y
add()(5)   # 6
add(2)(5)  # 7
```
But it seems lodash/fp ignores all empty calls until the function has received enough args (all examples here have a fixed arity of two):
```
_.sortBy(_.identity)([3, 1, 2])           // Array [ 1, 2, 3 ]
_.sortBy()([3, 1, 2])                     // function wrapper()
_.sortBy()()()()()([3, 1, 2])             // function wrapper()
_.sortBy()()()()()(_.identity)([3, 1, 2]) // Array [ 1, 2, 3 ]
_.drop()([1, 2, 3])                       // function wrapper()
_.drop(1)([1, 2, 3])                      // Array [ 2, 3 ]
_.random()()                              // function wrapper()
_.random(0)(1)                            // 0
```

Puzzlingly the only mention of this behavior I could find was [one line ("`flow(sortBy())([1, 6, 2]);`")](https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba#8e81) from the "Why using `_.chain` is a mistake" article, where the author seems to have made the same mistake I did in assuming how an empty call would work.

Am I correct in thinking it would be too complicated to fix this at this stage? Or does it WAI?

I am using lodash/fp v4.17.2 in the browser console.

**Comment by jdalton** [comment]
Hi @monk-time!

This is how auto-currying works. The curried methods expect a certain number of arguments before it will be executed so default param values aren't possible.

**Comment by monk-time** [comment]
I see. Just so that I understand it correctly: it is impossible full stop, or because of the architecture of lodash/fp? It seems to me in theory an auto-curried wrapper might be able to check if it is called with no args, look up a relevant default value for the function it wraps and use it instead. But I would understand if it's unfeasible to implement without a total overhaul of how currying and defaults are implemented. 

Or are there some details about auto-currying that I miss that would prevent it from being possible?

**Comment by jdalton** [comment]
> Or are there some details about auto-currying that I miss that would prevent it from being possible?

A curried function returns a new function to accept additional arguments until the desired arity is met. It's a fixed goal. There is no missing params.

**Comment by monk-time** [comment]
I think I understand how currying works in general. But what prevents an auto-"currier" to curry functions not only to accept arguments one by one when they are given, but also to react to argument-less calls (check if the arguments array is empty) and pretend as if a default value for that argument (if it exists) was sent and wait for the rest of args? Are there any downsides to such approach?

**Comment by jdalton** [comment]
> Are there any downsides to such approach?

A call with no arguments is an incomplete curried call.
There's no way to distinguish between a method with a default value and one without and doing the empty-call-means-a-default-value gives a default value to the first argument but not to the rest so seems uneven from that standpoint too.

**Comment by monk-time** [comment]
> There's no way to distinguish between a method with a default value and one without

I don't know much about js introspection capabilities, it is sad if that is the case. An ugly workaround might be to reimplement that part of ES6 manually by keeping track of which functions use which constructors for which args to get their defaults values.

> doing the empty-call-means-a-default-value gives a default value to the first argument but not to the rest so seems uneven from that standpoint too

Well, in my imagination such an auto-"currier" should treat all empty calls equally, not only the first, and curried functions receive only 0- or 1-argument calls and error out if called with more anyway. Just like it is already in JS for "pseudo-curried" nested lambdas, for example:
```
> var sum = a => (b = 1) => c => (d = 2) => (e = 5) => a + b + c + d + e;
> sum(10)()(10)()(10) // 33
> sum(0)(0)(0)(0)() // 5
```

**Comment by monk-time** [comment]
My motivation for this issue was that I thought it would make point-free style and lodash/fp more appealing by keeping very useful default params from lodash and thus making calls that use them shorter. E.g., instead of this:
```
_.flow(_.filter(_.identity), _.sortBy(_.indentity), _.drop(1))([3, 1, 0, 2, false]) // Array [ 2, 3 ]
```
it would be natural to a new lodash/fp user coming from lodash to use this:
```
_.flow(_.filter(), _.sortBy(), _.drop())([3, 1, 0, 2, false]) // Array [ 2, 3 ]
```

IIUC, lodash/fp already uses lists of functions in the wrapper to determine their fixed arity and argument order, wouldn't it be theoretically possible to do the same for default params? And I fear I don't understand your last point about my suggestion applying only "to the first argument but not to the rest", it would apply to all args on a case-by-case basis, one call to a curried function at a time.
