### ISSUE TITLE
[Question] Why don't you have "js:next"

### ISSUE THREAD

**Issue by havenchyk** [lodash/lodash#2864]
Hey @jdalton!

just a question: why don't you have `js:next` in the package.json, is it by intention? 
https://github.com/rollup/rollup/wiki/jsnext:main

sorry for posting as an issue, but I know you're so responsible here :)

I've also found your comment, but don't quite understand, what does it mean https://github.com/webpack/webpack/issues/1979#issuecomment-235174714

**Comment by jdalton** [comment]
Hi @havenchyk!

It's in the [lodash-es](https://github.com/lodash/lodash/blob/es/package.json) package.

**Comment by havenchyk** [comment]
awesome, thanks. 

btw, @jdalton will "tree shaking" work for lodash-es by default?

**Comment by jdalton** [comment]
Tree shaking via Web Pack 2 or Rollup isn't supported because those tools aren't robust enough yet. However, you can use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) to handle it.
