### ISSUE TITLE
`indexAt` String method

### ISSUE THREAD

**Issue by jaridmargolin** [lodash/lodash#2865]
Perhaps this is a limited use case and not a good fit for lodash, but I found myself needing a method `indexAt(line, column)`. Method seems reusable enough to pull out of the lib it was created in. I personally am not a huge fan of standlone repo for a single util method, but if its not a good fit for lodash that is probably the route I will take.

current implementation:

```js
  indexAt: function (str, row, column) {
    row = parseInt(row); column = parseInt(column);

    let i = 0;
    for (var r = 1; r < row; r++) {
      if ((i = str.indexOf('\n', i +1)) === -1) { return -1; }
    }

    const i2 = str.indexOf('\n', i+1);
    const boundary = i2 !== -1 ? i2 : str.length;

    i += column || 0;
    return i < boundary ? i : -1;
  }
```

**Comment by jdalton** [comment]
Hi @jaridmargolin!

What's the use case?

**Comment by jaridmargolin** [comment]
My particular use case is highlighting specified char in src code from callsite object, which contains file, line, and column.

**Comment by jdalton** [comment]
Thanks for clarifying. I think this is a bit too use case specific for Lodash.
