### ISSUE TITLE
documentation add issues

### ISSUE THREAD

**Issue by jsnoble** [lodash/lodash#2866]
I apologize if this is the wrong spot to place this, don't know the appropriate channel. I just wanted to point out that while reading the documentation on lodash.com, there is an ad (via carbon) that appears and directly blocks a portion of the listed api's on the left side of the page on desktop. At least on my screen it blocks the viewing of the methods flatten, flattenDeep, flattenDepth and fromPairs. Its totally fine if you have ads, just wasn't sure that your intention was to block usability of your site. Thanks, I appreciate all your hard work for this project!

**Comment by jdalton** [comment]
Hi @jsnoble!

Hmm, I can't repro the issue.
For future reference the site repo is located at [lodash/lodash.com](https://github.com/lodash/lodash.com).
