### ISSUE TITLE
Feature Request: `trim*` minimum length

### ISSUE THREAD

**Issue by mathieumg** [lodash/lodash#2870]
Do you think there would be interest/room for an extra `minimumLength` parameter to the `_.trim*` functions? The use case would be eliminating "meaningless" characters as long as it doesn't make the output shorter than `minimumLength`. In the case of the `_.trim` function, it could either not support that feature or the side on which the `chars` are removed could be alternated until the limit is reached, a bit like `_.pad` does.

```js
_.trimStart('-_-abc-_-', '_-', 7);
// => '-abc-_-'

_.trimEnd('-_-abc-_-', '_-', 7);
// => '-_-abc-'

_.trim('-_-abc-_-', '_-', 7);
// => '_-abc-_'
```

Thank you!

**Comment by jdalton** [comment]
Hi @mathieumg!

I think at that point you may be better off with a custom implementation. I'd like to avoid expanding this method beyond its cutrrent signature.
