### ISSUE TITLE
Problem with ads on lodash documentation page

### ISSUE THREAD

**Issue by bertyhell** [lodash/lodash#2871]
When scrolling the overview list of the lodash functions, the add scrolls with it, obscuring some lodash functions.

Tried on:
chrome: 54.0.2840.99 m
Window 10 x64
With and without adblock

![image](https://cloud.githubusercontent.com/assets/1710840/20963066/2580c4e8-bc6c-11e6-9dac-1f3b73ca949b.png)

**Comment by Archimidis** [comment]
I believe that this should be reported here https://github.com/lodash/lodash.com

**Comment by jdalton** [comment]
Hi @bertyhell!

I can't spot the repro the problem.
Maybe it's another extension causing the issue.

If you find the problem you can submit a PR to [lodash/lodash.com](https://github.com/lodash/lodash.com).

**Comment by bertyhell** [comment]
Ok, i've created a PR here (for reference)
https://github.com/lodash/lodash.com/pull/117
