### ISSUE TITLE
[Question] merge does not concat arrays?

### ISSUE THREAD

**Issue by dragonprojects** [lodash/lodash#2872]
Hi,

hey, I have a (hopefully only understanding) problem with lodash and the merge, I had in mind merge works like Object.assign, but recursively and arrays will be concatinate. 
But currently also arrays runs through the Object.assign and overrides the elements with the same index.
I'm wrong with it or I had the wrong function in mind does this?

Example (https://jsfiddle.net/r8xxs3vm/):
```
const a = ['a'];
const b = ['b'];
console.log(_.merge(a, b)); // expected: ['a', 'b'], actual: ['b']
```

Background:
We had a upcoming bug in our software that an array inside a config object I use merge gets partly overwritten instead of concatenate without any changes in this part of code.

**Comment by Reda-bx** [comment]
@dragonprojects according to the [docs](https://lodash.com/docs/4.17.2#merge) merge accept only Object and you are trying to pass two arrays, if you want `['a', 'b']` as an input you better use [_.concat](https://lodash.com/docs/4.17.2#concat) which accept arrays

**Comment by jdalton** [comment]
Hi @dragonprojects!

By default our [_.merge](https://lodash.com/docs/#merge) follows the behavior of jQuery's deep extend. To make arrays merge by concatenation you can use [_.mergeWith](https://lodash.com/docs/#mergeWith).

**Comment by dragonprojects** [comment]
Ah and the example is exactly what I need, thx for the answer.

**Comment by ShaojieLiu** [comment]
exactly what i need, thx!
