### ISSUE TITLE
_.omit with Object.prototype[Symbol.iterator]

### ISSUE THREAD

**Issue by jschmidt42** [lodash/lodash#2873]
Hi,

If I add: 
```js
Object.prototype[Symbol.iterator] = function () {
    let keys = Object.keys(this)[Symbol.iterator]();
    let obj = this;
    return {
        next: function () {
            let it = keys.next();
            if (!it.done)
                it.value = [it.value, obj[it.value]];
            return it;
        }
    };
};
```

To be able to do a for..of on any object, then when I use `_.omit` on an object that has this new prototype function, then I end up with new object that that has this function inside the object instead of in the object's prototype.

I.e.:
`o = {a:1, b:2, c:3}` gives:
![image](https://cloud.githubusercontent.com/assets/4054655/20968957/cdb3fbe8-bc54-11e6-80a0-cbf717838f35.png)
So far, so good.

Then if I do:
`_.omit(o, 'b')`
I end up with:
![image](https://cloud.githubusercontent.com/assets/4054655/20968985/ea7ca11c-bc54-11e6-92ab-5dc46a5a858c.png)

The biggest issue with this is that now the equality function does not work anymore:

`_.isEqual({a:1, c:3}, o)` returns `false`.

Is there something I can do better or is that expected?

Thanks,

**Comment by jdalton** [comment]
Hi @jschmidt42!

Adding stuff to the `Object.prototype` isn't a great idea. After our next release we should no longer see non-enumerable symbols so you could avoid the problem by making the symbol non-enumerable.

Our `_.omit` method flattens inherited properties. It has to start out with everything and then remove the bits you want to omit.
