### ISSUE TITLE
feature: force lazy evaluation of chain

### ISSUE THREAD

**Issue by binki** [lodash/lodash#2874]
I have an expensive `map` function but my array size is only about 36 elements. I want to be able to return implicitly chained lodash wrappers for my array so that I can shortcut the evaluation when using `.first()` but still be able to iterate the whole lodash wrapper when necessary. I.e., I’d like to be able to get behavior similar to .net’s `IEnumerable` so that I can put expensive transformations into a chain without worrying about things because I know `.first()` will only pull the first value that matches filters through.

Currently, the only way I can figure out how to do this somewhat safely is quite ugly, so it seems to me like there should just be an API to request lazy evaluation:

```
    var getLodashForceLazyUndefinedArray = _.memoize(function () {
        for (var i = 2; ; i *= 2) {
            var candidate = _.times(i, _.constant());
            var sawFirst = false;
            _(candidate).map(function (x) {
                if (sawFirst) {
                    // Got called a second time even though .first() was used.
                    candidate = undefined;
                }
                sawFirst = true;
            }).first();
            if (candidate) {
                return candidate;
            }
        }
    });
```

With usage like this:
```
> _([1,2,3].concat(getLodashForceLazyUndefinedArray())).filter().map(x => {console.log(`running for ${x}`); return x;}).value()
running for 1
running for 2
running for 3
[ 1, 2, 3 ]
> _([1,2,3].concat(getLodashForceLazyUndefinedArray())).filter().map(x => {console.log(`running for ${x}`); return x;}).first()
running for 1
1
```

Instead, I’d like to be able to do:

```
_([1,2,3]).lazy().…
```

EDIT: Bother, pressed ctrl-enter accidentally before finishing this.

**Comment by c-dante** [comment]
You should check out [transducers](https://github.com/jlongster/transducers.js), seems like a better approach for what you want to do.

**Comment by jdalton** [comment]
The reason I chose a limit of 200 was because so many devs performed really crappy microbenchmarks that would tend to be screwed negatively because of the overhead to handle lazy evaluation. They would test things like multiplying 2 numbers (super cheap operations) and then post these results in their marketing. That said, Lodash v4 is wrapping up it's dev cycle in prep for v5 so I think removing the limit is fine.
