### ISSUE TITLE
add support for comparing inherited properties with _.isEqual

### ISSUE THREAD

**Issue by finnigantime** [lodash/lodash#2876]
Feature request. _.isEqual() only checks own properties when comparing two objects and doesn't check inherited properties. It would be nice to have a codepath to also check inherited properties (we need this in a project where many properties are stored on the prototype). This should be opt-in to avoid affecting perf for the normal case.

Note that a way to achieve this currently is to use `_.toPlainObject()` to flatten the inherited properties down, but this is more expensive than just allowing `_.isEqual()` to compare properties without creating any new objects.

**Comment by jdalton** [comment]
Hi @finnigantime!

Thanks for making the PR. With Lodash v4 wrapping up I'm not wanting to make changes to its API beyond API additions (new methods). You may have better luck and perf with a custom comparison method.

**Comment by finnigantime** [comment]
@jdalton Understood that v4 is wrapping up. This is a new parameter and new opt-in codepath so it should be safe. Would you be open to taking this addition in v5?

**Comment by jdalton** [comment]
Folks use APIs in goofy ways like passing as partially applied iterator methods. In those cases an extra param can accidentally be provided and trigger the opt-in behavior. For v5 we can consider more granular comparison methods.
