### ISSUE TITLE
[feature request] support Map and WeakMap in _.get & _.set & _.update

### ISSUE THREAD

**Issue by SeregPie** [lodash/lodash#2879]
It would be a nice feature to have.
```javascript
let a = {a: 11};
let b = {b: 22};
let map = new Map();
_.setWith(map, [a, b], 'hi!', Map);
console.log(map.get(a).get(b) === 'hi!'); // => true
```

**Comment by jdalton** [comment]
Hi @SeregPie!

I can dig it.

**Comment by jdalton** [comment]
Are you up for creating a PR?

**Comment by SeregPie** [comment]
Hi! I will try.

**Comment by brianneisler** [comment]
I had to tackle roughly this same issue for [mudash](https://github.com/brianneisler/mudash). These methods might provide a point of reference.

https://github.com/brianneisler/mudash/blob/master/src/core/base/baseGet.js
https://github.com/brianneisler/mudash/blob/master/src/core/base/baseSet.js

Something to consider is what the result should be in a deep `_.set` like the following
```
map = new Map()
_.set(map, 'a.b', 'value')
```

I took the approach of preserving the data type based on input value. So result of above would be...
```
Map { a : Map { b: value' } }
```

Also consider the idea that you may want to traverse mixed data types on `_.get`
```
{ a : Map { b: 'value' } }
```

**Comment by SeregPie** [comment]
Hello. Didn't had much time. Just started right now to watch into source.

The 'read' functions are not a big deal... for Maps. For WeakMaps I'm missing a sort of `isPrimitive` function. Also I don't know how to handle a primitive key when current object is a WeakMap. Should it return default/undefined in this situation or handle the WeakMap as plain object and proceed with object[toKey(pathItem)]?

```javascript
function baseGet(object, path) {
  path = castPath(path, object);

  var index = 0,
      length = path.length,
      pathItem;

  while (object != null && index < length) {
    pathItem = path[index++];
    object = baseIsMap(object)
      ? object.get(pathItem)
      : object[toKey(pathItem)];
  }
  return (index && index == length) ? object : undefined;
}
```

```javascript
function result(object, path, defaultValue) {
  path = castPath(path, object);

  var index = -1,
      length = path.length;

  // Ensure the loop is entered when path is empty.
  if (!length) {
    length = 1;
    object = undefined;
  }
  while (++index < length) {
    var value = object == null
      ? undefined
      : baseIsMap(object)
          ? object.get(path[index])
          : object[toKey(path[index])];
    if (value === undefined) {
      index = length;
      value = defaultValue;
    }
    object = isFunction(value) ? value.call(object) : value;
  }
  return object;
}
```

**Comment by jdalton** [comment]
With v4 wrapping up *(I only plan on having 1 more v4 release)* I want to avoid introducing new functionality with a possibility of a long bug tail. Since this functionality isn't :100: fleshed out I'm going to table it until v5 or so.
