### ISSUE TITLE
Expose `castPath` and/or `stringToPath` for use

### ISSUE THREAD

**Issue by Mr-Wallet** [lodash/lodash#2880]
Trying to parse out a string path intended for lodash, and manipulate it, is pretty daunting. It would be very helpful if they could be parsed into arrays at-will.

In my particular use case, if a `_.get` fails, I want to test if at least the containing object exists. This would be trivially easy if I could use something like `_.castPathToArray`, drop the last element of the result, and throw that into another `_.get`.

**Comment by jdalton** [comment]
Hi @Mr-Wallet!

We have [_.toPath](https://lodash.com/docs/#toPath).

**Comment by Mr-Wallet** [comment]
Holy cow, that was fast! Thanks and sorry, I thought I got through that whole page searching for "path" but I guess I goofed.
