### ISSUE TITLE
Add lodash "decide" function

### ISSUE THREAD

**Issue by sateffen** [lodash/lodash#2881]
Hey,

I've got a feature idea, that I couldn't find in the issue tracker, so I'll propose it here:

When "promisyfing" function, I tend to write code like (just examples, eslint wouldn't allow such code^^):

```js
new Promise((resolve, reject) => {
  doSomething(arg, (error, result) => {
    error ? reject(result) : resolve(result);
  });
});
```

Round about that. That is a lot of duplicated code, so I wrote a helper like this:

```js
function helper(resolve, reject) {
  return function () {
    arguments[0] ?
      resolve.apply(this, Array.prototype.slice.call(arguments, 1)) :
      reject.apply(this, Array.prototype.slice.call(arguments, 0))
  }
}
```

so my code gets simplified like:

```js
new Promise((resolve, reject) => {
  doSomething(arg, helper(resolve, reject))
});
```

Which is simpler to read and maintain. "promisyfing" is not the only usecase, there are a few more while working with callback-based flows, but I think this is something worth implementing in lodash.

**Comment by StreetStrider** [comment]
@sateffen looks like you've implemented [fromCallback](http://bluebirdjs.com/docs/api/promise.fromcallback.html).

**Comment by jdalton** [comment]
Hi @sateffen!

I dig promises but I want to leave their utils to more promise focused libraries at this time.
