### ISSUE TITLE
Return Object in Array

### ISSUE THREAD

**Issue by rohmanhm** [lodash/lodash#2885]
I have object like this,
`{id: 1, firstName: 'john', email: 'john@doe.com'}`

I need just return object in array `['firstName', 'email']`

So the result is this 
`{firstName: 'john', email:'john@doe.com'}`

How can I do that?

**Comment by demoneaux** [comment]
I think you're looking for [`_.pick`](https://lodash.com/docs#pick).

**Comment by rohmanhm** [comment]
Thanks, @demoneaux ,
**lodash** had a lot of documentation, and I'm beginner using it. I feel little confusing 😅.
