### ISSUE TITLE
_.has() doesn't work (v 4.17.2)

### ISSUE THREAD

**Issue by BobbyT** [lodash/lodash#2886]
Hi,

I encountered as misbehaviour of the _.has() function.

I want to test a flat object if it has an array of attributes.
The result is always false.

Then I ran the exmaples from the docs in jsFiddle https://jsfiddle.net/hqwek615/
and results that should've been true are actually false.

Am I mistaken or is this a bug?

best regards
bobbyt

**Comment by jdalton** [comment]
Hi @BobbyT!

I can't repro this on our master branch.

**Comment by abelsky** [comment]
Same issue here... Lodash 4.17.4, Node v6.3.1 and v4.3.2

`_.has(item, fieldNames)` - seems to return _false_ if fieldNames.length > 1
This seems to work as expected when only 1 element is specified in the array.

My current workaround - check each fieldName:
`fieldNames.every( (fieldName) => { return _.has(item, fieldName) } )`

**Comment by jdalton** [comment]
Naw you're using the API wrong. If fieldNames is an array that's a path. So `['a', 'b', 'c']` is `object.a.b.c`. Super simple folks.
