### ISSUE TITLE
invert function changes type from number to string

### ISSUE THREAD

**Issue by sudarsangp** [lodash/lodash#2887]
The lodash docs shows the following example for invert:

![image](https://cloud.githubusercontent.com/assets/2398969/21179071/5fe158f2-c22d-11e6-9509-8e21ca15de29.png)

Any reasons why the type has been changed from **number** to **string**?
e.g. **1** has become **'1'**

**Comment by jfmengels** [comment]
That is standard JS behaviour. Just try defining an object with `1` as the key, and it will construct an object with `'1'` as the key. Your data can still be accessed through `object[1]` though.

![image](https://cloud.githubusercontent.com/assets/3869412/21179448/7206b074-c1f4-11e6-836b-fc6853eb4a5e.png)
