### ISSUE TITLE
yieldable/thenable compose/pipe

### ISSUE THREAD

**Issue by joshperry** [lodash/lodash#2888]
I'd like to be able to more easily compose async functions using `compose` or `pipe`.

Any thoughts on adding something similar to [Ramda's pPipe and pCompose](https://github.com/ramda/ramda/pull/524)?

We are currently using generator functions for yieldable async code (behind babel `async`/`await` transform), I think it would be optimal if a feature like this could handle thenables and yieldables.

An example of some code that I'm working on right now (that doesn't work): 
```javascript
export async function api(action, data) {
  let resp = await axios.post(`/gworchest_160803A/gdc/${action}.php`, querystring.stringify(data));

  if(resp.data.status === 200) {
    return resp.data;
  } else {
    throw new Error(resp.data.ErrorMessage);
  }
}

// rawCredentials => apiCredentials
let genCredentials = _.curry(async (UserId, password) => {
  return _.compose(
    Password => ({ UserId, Password }),
    blowpassword,
    r => r.baseprm,
    await api('InitialApp', {
      initial_app_strings
    })
  )(password);
});

// apiCredentials => profile
let userLogin = async (credentials) => {
  return await api('UserLoginRequest', {
    RegionCode,
    initial_app_strings,
    ...credentials
  });
};

// rawCredentials => profile
let authenticate = _.compose(userLogin, genCredentials);

// rawCredentials => (apioperation => apiresults)
let loginSession = _.compose(
  s => async (action, data) => await api(action, { ...s, ...data }),
  p => ({ custom_sessionid: getsessionid(p), VIN: getvin(p) }),
  authenticate
);

(async function() {
  let session = await loginSession('bobbytables@gmail.com', 'Tr0ub4dor&3');
  let data = await session('BatteryStatusRecordsRequest');
  console.log(data);
}());
```

**Comment by jdalton** [comment]
I usually punt more async style methods to the [async](https://github.com/caolan/async) package or [async-p](https://github.com/jgornick/asyncp). That said, I think the `pPipe` and `pCompose` APIs may be going away.

**Comment by joshperry** [comment]
Appreciate it! I noticed that those weren't in their online docs, that would explain why.
