### ISSUE TITLE
Error on React-Native v0.39 (lodash/find)

### ISSUE THREAD

**Issue by thinnakrit** [lodash/lodash#2889]
`Unknowk named module: 'lodash/find'`

How to fixed it ?

**Comment by thinnakrit** [comment]
![screenshot_1481865447](https://cloud.githubusercontent.com/assets/11704846/21252469/acf59ab0-c389-11e6-81bc-529c16bf956f.png)

**Comment by demoneaux** [comment]
What version of lodash are you using? Perhaps you could also try deleting your lodash folder in node_modules and reinstalling.

**Comment by thinnakrit** [comment]
I using lodash version 4.17.2.
I will try to delete and reinstall repeated.

**Comment by thinnakrit** [comment]
I can solve the problem
Cache is due to render problem.
