### ISSUE TITLE
An inconsistency in zipObjectDeep

### ISSUE THREAD

**Issue by xdptdr** [lodash/lodash#2892]
The following snippet shows an inconsistency in zipObjectDeep:

`console.log(_.zipObjectDeep(['a.1','a.p','b.p','b.1'],[1,2,3,4]));`

Which displays this in my (nodejs) console:
`{ a: [ , 1, p: 2 ], b: { '1': 4, p: 3 } }`

`a` is instanciated as an array, wile `b` is instanciated as an object, only because the order in which the property paths were specified is different.

I'm sure that in all practical cases, especially practical cases involving numbers used as object property keys, the effects of this should be quite limited, but yet... that's an inconsistency. Also, if I really had wanted an array, I would have said so, writing `a[1]` instead of `a.1`.

Thanks for the nice "little library :).

**Comment by jdalton** [comment]
Hi @xdptdr!

This is by design. Other methods have  `*With` form to customize the object creation. We don't treat `a[1]` vs. `a.1` differently because they resolve to the same path.
