### ISSUE TITLE
_.debounce() breaks fake timers

### ISSUE THREAD

**Issue by aldendaniels** [lodash/lodash#2893]
# _.debounce() breaks fake timers

In tests, it's common to replace JS timer methods such as `setTimeout` and `setInterval` with fake methods in order to control the passage of time. See [Jest Timer Mocks](https://facebook.github.io/jest/docs/timer-mocks.html) and [Sinon Fake Timers](http://sinonjs.org/docs/#clock). Doing this allows you to march the clock forward in tests, executing all timers synchronously. 

Recursive calls to `setTimeout` pose a problem when doing this, because the recursive `setTimeout` calls are executed synchronously, causing infinite recursion.

A non-recursive debounce implementation would solve this. See [David Walsh's Debounce Function](https://davidwalsh.name/javascript-debounce-function) for an example of non-recursive debounce.

**Comment by jdalton** [comment]
Dup of #2533.

**Comment by aldendaniels** [comment]
@jdalton not a dupe. #2533 addresses being unable to mock timers. Now we can  mock timers (:thumbsup:), but the timers recurse infinitely when mocked.

**Comment by jdalton** [comment]
I haven't had folks using Sinon complain, maybe it's a Jest issue?
If you're up for creating a PR that would rock. It may not get into the v4 release since I'm winding it down in prep for v5.

**Comment by aldendaniels** [comment]
@jdalton thanks for the quick response! The fake timers implementation I'm using is an internal one. From the docs, however, it appears that Jest has the same issue:

> There are also scenarios where you might have a recursive timer -- that is a timer that sets a new timer in its own callback. For these, running all the timers would be an endless loop… so something like jest.runAllTimers() is not desirable
\- [Jest Docs](https://facebook.github.io/jest/docs/timer-mocks.html)

Perhaps sinon doesn't have the issue - I'm not sure. I'll look into making a PR, depending on how much rework it's going to require to remove recursion. For now I'm using a simpler debounce implementation outside of lodash.

**Comment by jdalton** [comment]
Issues might be avoidable by mocking `Date.now` as well.

**Comment by spudly** [comment]
For what it's worth, here's how I solved this problem using jest:

```js
test('blah blah', () => {

  jest.useFakeTimers();
  Date.now = () => 0;

  debouncedFn('t');
  debouncedFn('te');
  debouncedFn('tes');
  debouncedFn('test');

  expect(originalFn).not.toHaveBeenCalled();

  Date.now = () => 400;
  jest.runTimersToTime(400);

  expect(originalFn).toHaveBeenCalledTimes(1);
  expect(originalFn).toHaveBeenCalledWith('test');
});
```

The key here is to stub both the timers **AND** Date.now.

**Comment by rimunroe** [comment]
I'm still seeing the same issue with it in v4.17.4 of Lodash. I tried it with Jest 18 & 19 on Node 4 & 6.

``` javascript
jest.useFakeTimers();

var _ = require('lodash');

test('fails to mock Lodash timers correctly', function() {
  var test = jest.fn();
  var debounced = _.debounce(test, 1000);

  debounced();
  debounced();

  jest.runAllTimers();

  expect(test).toHaveBeenCalledTimes(1);
})
```

Running that with Jest causes it to say "Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...". Do you think this is a Lodash issue, or is this something I should pursue on Jest's end?

**Comment by jdalton** [comment]
Lodash doesn't hold on to references to `setTimeout`, `clearTimeout`, or `Date.now` so your guess is as good as mine.

**Comment by jkettmann** [comment]
@rimunroe Did you solve your issue somehow? Having a similar problem

**Comment by rimunroe** [comment]
I ended up just avoiding using it, or actually waiting in tests when I absolutely had to. I opened https://github.com/facebook/jest/issues/3465 about the problem though.

**Comment by NickHeiner** [comment]
I believe I know what the problem with Jest is: https://github.com/facebook/jest/issues/3465#issuecomment-424193697.

**Comment by skyboyer** [comment]
@jdalton so what could we(library consumers) do here? do we need mocking `Date.now` alongside using fake timers to mock `_.debounce`? should it help?

**Comment by jdalton** [comment]
@skyboyer I'd go for trying to mock `_.debounce`.
