### ISSUE TITLE
_.filter: Property "In" Array Support

### ISSUE THREAD

**Issue by chukkwagon** [lodash/lodash#2894]
I would like to add support for the following syntax for `_.filter`:

> _.filter(collection, {'property': ['value1', 'value2',  'value3']});

This is similar to the [`__in` filter in django](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#in) as it would allow filtering a collection by items with a property that matches one of *several* values. Currently the `_.iteratee` shorthand only supports single value lookups. The behavior I'm describing can be accomplished easily enough with a custom `func` like so:

> _.filter(collection, item => _.includes(['value1', 'value2', 'value3'], item['property']));

... but this is a fairly common operation and (warning opinion ahead) I think the former syntax is cleaner. 

If I put together a PR that adds support for this feature would you consider it?

**Comment by jdalton** [comment]
Hi @chukkwagon!

We currently reserve that syntax as a [_.matches](https://lodash.com/docs#matches) so won't be changing it anytime soon.

**Comment by chukkwagon** [comment]
@jdalton thanks for your response! could you elaborate on how `_.matches` accomplishes the same syntax as what i am describing? An example would be helpful, as the documentation example looks a lot like the `_.iteratee` shorthand. Thanks!

**Comment by jdalton** [comment]
See the [`_.filter` docs](https://lodash.com/docs/#filter) for an example.

**Comment by chukkwagon** [comment]
Gotcha, yea that example is what i'm suggesting could be *extended* to support the functionality I'm talking about. 

What about a new function: `_.matchesIn` that can be used like `_.matches`, but that explicitly supports multiple values via an array. A function like this:

> _.filter(collection, _.matchesIn({'property': ['value1', 'value2', 'value3']}));

whose iteratee shorthand would be:

> _.filter(collection, {'property': ['value1', 'value2', 'value3']});

**Comment by jdalton** [comment]
The shortcut already exists for `_.matches` and cannot be expanded.

**Comment by chukkwagon** [comment]
i get what you mean, but you would just need to a `typeof` switch in the `getIteratee` method that would delegate to `_.matches` if the value was a string or `_.matchesIn` if it was an array.
