### ISSUE TITLE
Does _.intersection in version 3.10.1 preserve sort order of the first array?

### ISSUE THREAD

**Issue by christynwegner** [lodash/lodash#2896]
This question has been previously asked in issue #779

In version 4.17.2 it is stated in the API documentation that "order and references are determined by the first array" however this is not documented in version 3.10.1

Looking at the source in 3.10.1, it appears to be preserving the order of the first array provided as it is iterating over the elements in arrays[0] and pushing the intersecting elements to the result array.

**Comment by jdalton** [comment]
It should. You can always just try it out on the v3 doc page by opening the dev console.
