### ISSUE TITLE
[Question] the order of platforms for cross-browser testing

### ISSUE THREAD

**Issue by junghyun87** [lodash/lodash#2898]
Hi,
I ask for a research purpose. Is there a criterion to set the order of platforms for cross-browser testing?
In lodash/test/saucelabs.js, the order of platforms is as follows:

```
  ['Linux', 'android', '5.1'],
  ['Windows 10', 'chrome', '54'],
  ['Windows 10', 'chrome', '53'],
  ['Windows 10', 'firefox', '50'],
  ['Windows 10', 'firefox', '49'],
  ['Windows 10', 'microsoftedge', '14'],
  ['Windows 10', 'internet explorer', '11'],
  ['Windows 8', 'internet explorer', '10'],
  ['Windows 7', 'internet explorer', '9'],
  ['OS X 10.11', 'safari', '9'],
  ['OS X 10.10', 'safari', '8']
```

Thanks.

**Comment by jdalton** [comment]
Yep.

**Comment by junghyun87** [comment]
@jdalton Thank you for the response. Can I ask you what criterion lodash is using?

**Comment by jdalton** [comment]
The current and previous release of most browsers except IE which goes to 9 for now.

**Comment by junghyun87** [comment]
@jdalton  What about the order of web browsers?

**Comment by jdalton** [comment]
Order isn't important it's an automated test run.
