### ISSUE TITLE
Function that throws when attempting to access invalid path on an Object?

### ISSUE THREAD

**Issue by christophercliff** [lodash/lodash#2900]
`get()` returns `undefined` if the path is invalid. Is there a pattern in Lodash that will throw instead? E.g. `get({}, 'bogus_path') // throws error`.

**Comment by jdalton** [comment]
Hi @christophercliff!

There's no pattern for this. Lodash tries to avoid erroring so you won't find much in it's API that does unless it's a choice of erroring sooner than later (like with some wrapper functions).

**Comment by christophercliff** [comment]
There's a common pattern where an object of key value pairs is exported and treated like an enum (e.g. see the [Redux docs](https://github.com/reactjs/redux/blob/a1817d4d83b9525c53ac8cb95401f06502e61033/docs/basics/Actions.md#actionsjs)).

For example:

```js
export const MyTypes = {
    SOMETHING: 'SOMETHING',
    SOMETHING_ELSE: 'SOMETHING_ELSE',
}
```

Then it's accessed somewhere else like:

```js
if (foo === MyTypes.SOMETHING) // etc.
```

With this pattern it's possible to introduce a programmer error like:

```js
if (foo === MyTypes.SOMETHING_THAT_DOES_NOT_EXIST) // etc.
```

To prevent these types of errors, I suggest adding a method with the same signature as `_.get` without `[defaultValue]`. If the path doesn't exist in `object` it throws a runtime error that can be caught during testing. For example:

```js
export const MyTypes = keyBy([
    'SOMETHING',
    'SOMETHING_ELSE',
])

if (foo === grab(MyTypes, 'SOMETHING_THAT_DOES_NOT_EXIST')) // throws
```

Any interest in this?
