### ISSUE TITLE
Why _.some is not lazy evaluated?

### ISSUE THREAD

**Issue by jswiniarski** [lodash/lodash#2901]
I've noticed that some function doesn't support lazy evaluation. Is there any reason behind that? According do documentation of _.some 
>  Iteration is stopped once predicate returns truthy.

Take a look

```javascript
var largeArray = _.range(300);

// evaluates only first
var head = _(largeArray)
    .map(item => {console.log(item); return item;})
    .head();
console.log("head: " + head);

// evaluates up to 5 items
var take5 = _(largeArray)
    .map(item => {console.log(item); return item;})
    .take(5)
    .value();
console.log("take5: " + take5);

// evaluates up to 5 items
var find5 = _(largeArray)
    .map(item => {console.log(item); return item;})
    .find(item => item === -2);
console.log("find5: " + find5);

// evaluates all !
var some = _(largeArray)
    .map(item => {console.log(item); return item;})
    .some(item => item === 5);
console.log("some: " + some);

// workaround, evaluates only 5 items
var some2 = _(largeArray)
    .map(item => {console.log(item); return item;})
    .find(item => item === 5) !== undefined;
console.log("workaround: " + some2);
```
https://jsfiddle.net/jarecky/3u7pqm89/3/

**Comment by jdalton** [comment]
Not all methods are lazy evaluated. See the doc note [here](https://lodash.com/docs#lodash) for a rundown.

**Comment by jswiniarski** [comment]
Thanks for answer. But still, why _.find() can be lazy evaluated and _.some() can not if it is logically equivalent to _.find() !== undefined?

**Comment by jdalton** [comment]
Under the hood lazy `find` is `filter(predicate).head()` and a value in an array may be a literal `undefined`.
