### ISSUE TITLE
difference function does not work with LodashWrapper'd values

### ISSUE THREAD

**Issue by raymanoz** [lodash/lodash#2903]
I am in the process of converting an `underscore` codebase to `lodash`. Unfortunately I have found the `LazyWrapper` to be causing me some problems.

As an example
This works for me:
```javascript
$ _([1,2,3,4]).difference([3,4,5,6]).size()
2
```
Doesn't work for me:
```javascript
$ _(_([1,2,3,4]).map(_.identity)).difference(_([3,4,5,6]).map(_.identity)).size()
4
```

Here I am just using identity to get the `LazyWrapper` instances. In my real code, I am mapping a value out of a object.

**Comment by raymanoz** [comment]
Sorry, I just realised this is a major difference between underscore and lodash's usage of _(values).

**Comment by jdalton** [comment]
The `difference` method accept arrays not wrapped values.
