### ISSUE TITLE
_.trim ,  _.trimLeft issue.

### ISSUE THREAD

**Issue by void666** [lodash/lodash#2904]
For version : 3.10.1

`_.trim('sifg_source','sifg_'))  // returns 'ource' instead of 'source' ;
 _.trim('_hhash','_h') // returns 'as' instead of 'has'`

**Comment by ashoksahoo** [comment]
+ "V4.17.2" also.

**Comment by void666** [comment]
https://github.com/lodash/lodash/issues/2167
The chars param is a string of chars (individually) to remove not a pattern to remove. Closing this
