### ISSUE TITLE
Should _.gt(undefined, Number) behave the same as _.size(undefined) > Number?

### ISSUE THREAD

**Issue by luisgregson** [lodash/lodash#2905]
When using `_.gt(undefined, Number)`, `TypeError: Cannot read property 'length' of undefined` error is thrown.

I would assume that `undefined` would resolve to `0`, as `_.size(undefined)` returns `0`.

Is there are a reason for this difference? If not, I'm happy to fork and raise a PR.

**Comment by jdalton** [comment]
Hi @luisgregson!

I can't repro this in the current master branch. Your usage is a bit odd as `Number` is a function constructor but even with `_.gt(undefined, 3)` it returns `false` as expected.
