### ISSUE TITLE
Add note about curry/curryRight and rest parameter/default values

### ISSUE THREAD

**Issue by gabejohnson** [lodash/lodash#2906]
In reference to a gitter conversation https://gitter.im/lodash/lodash?at=585ad8f061e516c1578ea1a7

`_.curry` and `_.curryRight` don't work "as expected" when used with functions containing rest parameters or parameters with defaults. And they shouldn't considering how Function::length is specified.

Though I don't believe it is the job of Lodash to educate JS devs about the features of their language, I suspect this knowledge is far from common. A note or discussion would be helpful to anyone attempting, unsuccessfully, to use these sorts of functions w/ `_.curry` and `_.curryRight`.

**Comment by jdalton** [comment]
Hi @gabejohnson!

I checked the documentation for `_.curry`, just in case, and noticed it does cover the `func.length` limitation.

**Comment by gabejohnson** [comment]
@jdalton I read that note. My point was that I think many devs are likely unaware of the relationship between `func.length` and rest parameters/initializers and thus will have difficulty figuring out why their curried functions don't work as expected.

**Comment by gabejohnson** [comment]
@jdalton I swear I added a comment after you closed this issue last week.

I read about the `func.length` limitation before I submitted this issue. My point was that I suspect there are many devs unaware of the affect rest parameters and parameters with initializers have on the length property.

I think it's going to be a difficult to diagnose problem.

Like I said, I don't think it's your job to educate devs, but this seems like an inexpensive way to be helpful.

**Comment by danielo515** [comment]
Hello @jdalton 
Regarding the doc update, I think that this

> The arity of func may be specified if func.length is not sufficient.

May be more useful if it is enforced with an example case:

> Example (but not limited to) ES6 functions with default values or using rest parameters

Regards
