### ISSUE TITLE
.assign result not correct if object key is a numeric number

### ISSUE THREAD

**Issue by mickyma** [lodash/lodash#2909]
I write a function which wants to append nested object inside a object and the key of object is dynamic and a numeric string, but the result is not I expect and help me auto sorted. If the object key is not a numeric string, object not auto sorted, Here is the  code.
```js
const _ = require('lodash');

let obj1 = {
		"stats": {}
	};

let objMarks50 = {
	"50": {
		"studentName": [
			"Peter",
			"Mary"
		]
	}
};

// add marks 50
obj1.stats["50"] = null;
_.assign(obj1.stats, objMarks50);

let objMarks40 = {
	"40": {
		"studentName": [
			"Amy",
			"John"
		]
	}
};

// add marks 40
obj1.stats["40"] = null;
_.assign(obj1.stats, objMarks40);

console.log(obj1);
//result is
// { stats: 
//   { '40': { studentName: [Object] },
//     '50': { studentName: [Object] } 
//   } 
// }

// but I expect should be
//result is
// { stats: 
//   { '50': { studentName: [Object] },
//     '40': { studentName: [Object] } 
//   } 
// }

// since I assign '50' first
```

**Comment by jdalton** [comment]
This isn't a Lodash thing. What you're seeing is a JS thing. Object iteration order was recently defined in [ES2015](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys). That said, dev consoles and inspectors may represent them in a different order.
