### ISSUE TITLE
customizer of only used functions

### ISSUE THREAD

**Issue by Rafi993** [lodash/lodash#2910]
Lodash is very huge but generally we tend to use a small portion of it for project. It would be better if a customizer that would allow us to select only functions that we use and download lodash.min.js with only those functions. It would be even awesome if that customizer if part of Lodash documentation.

**Comment by jdalton** [comment]
@Rafi993 the kitchen sink build of Lodash is 23kb min+gzipped. If you're wanting to customize builds Lodash is modular so you can just `require('lodash/pick')` your methods or use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) and [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) to create smaller bundles. There's even the older [lodash-cli](https://lodash.com/custom-builds) for creating smaller builds.
