### ISSUE TITLE
This package has over 30k dependants.

### ISSUE THREAD

**Issue by GusCaplan** [lodash/lodash#2911]
HOLY SHIT!!!

**Comment by GusCaplan** [comment]
Just to name a few of my favorite methods,
`isArray` (literally Array.isArray)
`getValue` (takes {object, key} and returns object[key])
and `join` (literally `nativeJoin.call(array, separator)`)

**Comment by c-dante** [comment]
Out of curiosity, where are you getting this dependency list from?

**Comment by c-dante** [comment]
Our of curiosity, are you calling out exporting each symbol? A lot of the utility stuff lodash provides is safe/standard ways of type checking in JS (isBoolean, isArray, etc), which either fills the place of a polyfill or native if possible.
