### ISSUE TITLE
_.omit is deleting keys in deep omit

### ISSUE THREAD

**Issue by HeleneDroal** [lodash/lodash#2912]
Hi,

Between the 4.17.2 and the 4.17.3 versions, I noticed that the _.omit function is deteriorating the object when this is in deep level.

For example : 
```js
const object1 = { a: { b: 'c' } };
const object2 = _.omit(object1, 'a.b');

console.log(object1);  // { a: {} }
```

**Comment by jdalton** [comment]
Thank for the heads up @HeleneDroal!

**Comment by jdalton** [comment]
Thank for the heads up @HeleneDroal!
