### ISSUE TITLE
[Question] normal / es builds

### ISSUE THREAD

**Issue by Andarist** [lodash/lodash#2913]
This is just a general question, but you might be the person knowing the ultimate answer ;)

I'm exploring possibilities for structuring other package and searching for the way to:
- support both umd and es builds (thanks to main and jsnext:main used by 'modern' bundlers)
- with cherry-picked features like in lodash

I would like to keep the same package name, and it would be great if cherry-picks could also be imported in the same way (like `import assign from 'lodash/assign'`) for both builds.

So far I've came to conclusion that this is simply not possible and I feel you have explored the area in the past and could confirm/deny this conclusion.

Thanks in advance and sorry for bothering with this on the `lodash` issues, but in the same time it could be treated as a question if `lodash` could be organized in such a manner so wehn switching bundler type all of the code could stay exactly the same in order to leverage tree-shaking.

**Comment by jdalton** [comment]
Hi @Andarist!

I think cramming too much into a package can be a bad thing. In this case 50% won't be used in a given scenario. You could make your primary package the more common cjs/umd then register a npm user of with the same name as the package and create scoped packages for other variants. So you would have package `foo` and `@foo/es`.

**Comment by Andarist** [comment]
yeah, this was one option I was considering, but it doesnt allow for `foo/es`, `@` is required as prefix

problem is that we are allowing and recommend in the docs `main-package/sub-folder` form, but this is done by proxying `./sub-folder.js` to `./lib/sub-folder.js`, which is the outputted build, but the umd one. 

es build is available under `./es/sub-folder.js` and there is no known way to me to check in `./sub-folder.js` what type of bundler is used so I could conditionally `require` the other one from `lib`/`es`. And that breaks tree-shaking for `rollup` users. 

The ultimate goal would be to reorganize this in some way without making it a breaking change, but it seems that this is not possible unfortunately
