### ISSUE TITLE
Add `_.isEmpty(undefined); // => true` to the docs

### ISSUE THREAD

**Issue by userpixel** [lodash/lodash#2915]
It could save me some time if I knew about this behaviour. Would be nice to add a one liner to the docs 👍 thanks!

**Comment by jdalton** [comment]
Hi @userpixel!

I believe the documentation for [_.isEmpty](https://lodash.com/docs/#isEmpty) is sufficient.

**Comment by zealitude** [comment]
Agree to add this example.
null, undefined, 0, false .... it always make people confusing . It shouldn't make any assumption that people can predict the behavior of _.isEmpty

**Comment by coffenbacher** [comment]
We're just supposed to guess that isEmpty(undefined) // => true? It's just as confusing as isEmpty(null) IMO, which is documented.
