### ISSUE TITLE
Debounce Trailing Documentation Unclear

### ISSUE THREAD

**Issue by baldwmic** [lodash/lodash#2916]
### Issue
From [the docs](https://lodash.com/docs/4.17.4#debounce):
> Note: If leading and trailing options are true, func is invoked on the trailing edge of the timeout only if the debounced function is invoked more than once during the wait timeout.

To me, this makes it seem like if the debounced function is only called once, it will _not_ be called on the trailing edge.

#### Reproduce
However, the reality is that even if the debounced function is only called once, it will wait until the timeout completes before it is invoked. I made a [Codepen here](http://codepen.io/baldwmic/pen/GrgYNg) to confirm this.

#### Example
For example, we debounce a function as follows
```
const debouncedFunction = _.debounce(() => {
  console.log('Function invoked!');
}, 1000, { trailing: true });
```

And if we call it only once
```
debouncedFunction();
```

The docs make it seem like this will not wait 1 second to invoke the function that logs to the console.

### Discussion
Does that make sense?

**Comment by jdalton** [comment]
The key is if both "leading and trailing options are true".

**Comment by baldwmic** [comment]
Thank you! That makes much more sense
