### ISSUE TITLE
Q: How can I find index in array of objects using substring?

### ISSUE THREAD

**Issue by swp44744** [lodash/lodash#2918]
Hello,
How can I find index in array of objects using substring?

`var users = [`
  `    { 'user': 'barney', 'age': 36, 'active': true },`
    `  { 'user': 'fred',   'age': 40, 'active': false }
   ` ];`

`_.findIndex(users, {'user':'barney'}); // returns correct index = 0`
But 
How can I achieve by providing partial string, as below?
`_.findIndex(users, {'user':'barn'}); // returns -1`

Appreciate any help.

**Comment by jdalton** [comment]
Hi @swp44744!

For general support questions please visit our [gitter chat](https://gitter.im/lodash/lodash).
