### ISSUE TITLE
Explain "Many lodash methods are guarded to work as iteratees"

### ISSUE THREAD

**Issue by danvk** [lodash/lodash#2923]
The [docs for _.map][1] say:

> Many lodash methods are guarded to work as iteratees for methods like _.every, _.filter, _.map, _.mapValues, _.reject, and _.some.
>
> The guarded methods are:
> ary, chunk, curry, curryRight, drop, dropRight, every, fill, invert, parseInt, random, range, rangeRight, repeat, sampleSize, slice, some, sortBy, split, take, takeRight, template, trim, trimEnd, trimStart, and words

I haven't been able to find an explanation of what "guarded to work as iteratees" means in the documentation or elsewhere. Some detail or an example here would be greatly appreciated.

[1]: https://lodash.com/docs/4.17.4#map

**Comment by jdalton** [comment]
Hi @danvk!

This means they they can work as iteratees for methods like `_.map`. For example:
```js
_.map([_.map(['6', '8', '10'], _.parseInt);
// => [6, 8, 10]
```

**Comment by danvk** [comment]
Makes sense, thanks for the explanation @jdalton.

In case anyone else is curious:

```
_.map(['6', '8', '10'], parseInt);
// => [6, NaN, 2]
```

because `_.map` passes the array index as a second parameter to `parseInt`, which makes no sense as a radix.

**Comment by StreetStrider** [comment]
@danvk, of course they do. Besides, `['6', '8', '10'].map(Number)`, using `Number` is a better solution, cause you don't parse any integers, you just want to simply convert numeric strings. `parseInt` is a real parser already, that's why it has radix and everything.
