### ISSUE TITLE
forEach is not a function error in some browsers

### ISSUE THREAD

**Issue by hyperknot** [lodash/lodash#2924]
I am getting Sentry errors from a small subset of users telling me that there is a problem:
`TypeError: n.forEach is not a function` when loading lodash (n is from minifying).

The user agent strings of the browsers are the following:
```
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/7.0)
Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:20.0) Gecko/20100101 Firefox/20.0
Mozilla/5.0 (Windows NT 6.1; rv:18.0) Gecko/20100101 Firefox/18.0
```

Now it seems like Firefoxes are really old as well as IE is some weird version or compatibility mode, so I'm totally OK to just have these browsers brake.

I've opened this ticket for the following reasons:
1. It might be useful for you to know that n.forEach is breaking on some browsers.
2. Ask what minimum IE and Firefox versions can I safely say are compatible with lodash? Readme says IE11+ but tests are run on IE9+. So which one? 

Lodash is 4.x latest.

**Comment by jdalton** [comment]
Hi @hyperknot!

What you're seeing is probably related to the `forEach` method of a `Map` or `Set`. This was known to be buggy in ancient and unsupported versions of Firefox and buggy experimental flags of EOL Node versions. As for the IE fail I think that could be related to a bad shim as we support IE10 and test on IE10 without issue.

**Comment by FelixSchwarz** [comment]
@jdalton Sorry to hijack this thread but what is an "ancient" version of Firefox? E.g. 24.0? (September 2013)
