### ISSUE TITLE
unterminated comment : lodash 3.10.1

### ISSUE THREAD

**Issue by priyabrat1801** [lodash/lodash#2926]
We are having below issue which started to show up since yesterday.

err  SyntaxError: jspm_packages/npm/lodash@3.10.1/index.js: Unterminated comment (2492:4)
       2490 |     }
       2491 | 
> 2492 |     /**
       |     ^

Any help is appreciated

**Comment by jdalton** [comment]
Hi @priyabrat1801!

Our 3.10.1 release hasn't been touched since 2015.
It may be a jspm issue.
