### ISSUE TITLE
Webpack 2 Breaking Change breaks lodash-es

### ISSUE THREAD

**Issue by wirmar** [lodash/lodash#2927]
In the [v2.2.0-rc-4 Release](https://github.com/webpack/webpack/releases/tag/v2.2.0-rc.4) webpack introduced a Breaking Change: 
"Using CommonJS or AMD export stuff in a ES2015 module will emit errors."

This now causes builds to exit with an Error when using lodash-es:
```
...
    ERROR in ./~/lodash-es/isBuffer.js
    8:91-97 module is not allowed in EcmaScript module: This module was detected as EcmaScript module (import or export syntax was used). In such a module using 'module' is not allowed.

    ERROR in ./~/lodash-es/_nodeUtil.js
    4:25-32 exports is not allowed in EcmaScript module: This module was detected as EcmaScript module (import or export syntax was used). In such a module using 'exports' is not allowed.
...
```
Related: https://github.com/webpack/webpack/issues/3917

**Comment by jdalton** [comment]
Hi @wirmar!

Thanks, I'm on the thread you linked to. This is not a Lodash issue.

**Comment by wirmar** [comment]
Reading the thread I linked, it sounds to me that the errror message does indicate a "wrong" usage of UMD by lodash.
https://github.com/webpack/webpack/issues/3917#issuecomment-272094962

**Comment by jdalton** [comment]
Naw. In our case it's more of a generic environment check instead. It's valid JS and should work in environments that support ES modules. In face [https://jsbin.com/cazurag/1/](https://jsbin.com/fapuyec/1/) does work in the latest [Safari Technical Preview](https://developer.apple.com/safari/technology-preview/) which supports `type=module`.
```html
  <script type="module">
    import lodash from "https://unpkg.com/lodash-es@4.17.4/lodash.js";
    import { chunk } from "https://unpkg.com/lodash-es@4.17.4/lodash.js";
    
    log(`lodash.VERSION is ${ JSON.stringify(lodash.VERSION) }`);
    log(`chunk([1, 2, 3, 4], 2) is ${ JSON.stringify(chunk([1, 2, 3, 4], 2)) }`);
  </script>
```

**Comment by wirmar** [comment]
Oh ok, thanks for the info and for posting it in the webpack issue as well.
