### ISSUE TITLE
Systemjs Dependencies

### ISSUE THREAD

**Issue by rizwanhussain-vteams** [lodash/lodash#2928]
Hi,
Just a question. How do i import `sortBy` without loading all the dependencies using Systemjs?
I'm trying this 
```
import * as sortBy from "lodash/sortBy";

```
But obviously the object is tied to the module and loads all the deps. Any ideas?

**Comment by jdalton** [comment]
If you want to load just the bits to make `sortBy` work you can do:
```js
import sortBy from 'lodash/sortBy';
```
If you're using something like [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) then you can just write:
```js
import { sortBy } from 'lodash';
```

Either flavor includes code to make iteratee shorthands work. You can reduce bundles further with [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) which removes features, like iteratee shorthands, by default. Allowing you to opt-in to features instead.
