### ISSUE TITLE
.startCase() doesn't preserve umlaut characters (äöü)

### ISSUE THREAD

**Issue by aforty** [lodash/lodash#2929]
Examples:
```
_.startCase('äpple') // => "Apple"
_.startCase('bürger') // => "Burger"
```

**Comment by jdalton** [comment]
Correct. This is by design for "case" methods which [deburr](https://lodash.com/docs/#deburr) strings.

**Comment by aforty** [comment]
I see... May I ask why that was designed that way?

**Comment by jdalton** [comment]
Sure! We deburr to make things more consistent. When we started we had methods like `camelCase` and `kebabCase`.

**Comment by aforty** [comment]
Sure, I understand that `startCase`, `camelCase`, and `kebabCase` all deburr, but I'm trying to understand why they deburr. Some compatibility issue with umlauts that I'm not aware of?

**Comment by jdalton** [comment]
They were designed primarily for the common usage for property names and url hashes.
That said, I'm not super attached to keeping them deburred in other major releases.

**Comment by aforty** [comment]
URL's and and JS objects both support umlauts. I'm not super keen on changing existing behavior but I guess the fact that `startCase` deburr's surprised me when I discovered it because it isn't documented and I expected it to just upper case the each word and not do anything additional.

Perhaps default behavior can stay as is for backwards compatibility but allow users to turn off deburr'ing?

**Comment by jdalton** [comment]
No worries! The next release will be v5 so breaking changes are OK (I'm doing plenty of other changes).

**Comment by aforty** [comment]
Ok. Hope this makes it in! Thanks for the conversation on this.

**Comment by jdalton** [comment]
Done https://github.com/lodash/lodash/commit/b856263af6ff759601cbde207efe69b7366764fb.
