### ISSUE TITLE
Removal of _.omit in v5.0.0?

### ISSUE THREAD

**Issue by billyjanitsch** [lodash/lodash#2930]
I noticed that `_.omit` has been removed in master, [slated for v5.0.0](https://github.com/lodash/lodash/wiki/Roadmap). I couldn't find any discussion of the decision; I'm just wondering why you've chosen to remove it.

FWIW, it's one of my most frequently used Lodash methods. The roadmap suggests using `_.pick` instead, but it's not clear how that supports my typical use case: I want to remove keys `x` and `y`, but I don't know the structure of the rest of the object, so I don't know which remaining keys to pick. Maybe I'm missing something?

Cheers.

**Comment by jdalton** [comment]
Hi @billyjanitsch!

The `omit` method is less optimal and more complex since it has to pull in the universe *(inherited and own enumerable string key properties and symbols)* and then exclude a handful of properties. On the other hand `pick` is explicit and simply picks what you want without a lot of fuss.

**Comment by billyjanitsch** [comment]
I understand that it's a more complicated & nuanced function, and not as easy to support. However, consider the following scenario:

```js
// `foo` is an object, but I don't know all of its properties until runtime
// (they may be dynamic, obtained from an API or user input, etc.)
import {foo} from './somewhere'

// I want a copy of `foo` without `a`
const bar = _.omit(foo, ['a'])
```

I can't use `_.pick`, because I don't know the properties of `foo` until runtime, so I don't know which properties I want to retain -- only those I want to exclude.

1. Do you agree that this can't be accomplished with `_.pick`?
2. Do you not think that this is a common enough use case to warrant support in Lodash?

TC39 plans to [support it natively](https://github.com/sebmarkbage/ecmascript-rest-spread#rest-properties). Wide browser support is years away but IMO this speaks to its usefulness.

**Comment by jdalton** [comment]
> Do you agree that this can't be accomplished with _.pick?

My guidance would be to be explicit. You should know the properties you're consuming.
If not you can always [delete](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete) the desired ones.

> Do you not think that this is a common enough use case to warrant support in Lodash?

I'm removing it so no. There's always [lodash.omit](https://www.npmjs.com/package/lodash.omit).

> TC39 plans to support it natively. Wide browser support is years away but IMO this speaks to its usefulness.

I was just going to mention that. Using the [babel-plugin](https://babeljs.io/docs/plugins/transform-object-rest-spread/) is a great way to handle that.

**Comment by billyjanitsch** [comment]
Yea, there are various alternatives -- just letting you know that it's one of my most frequently used methods and I'll miss having it in a util lib. Maybe other users will chime in when v5.0.0 ships.

In any case, thanks for explaining your rationale. Excited for some of the other v5 changes 👌

**Comment by ypconstante** [comment]
There is a lot of cases that I use omit too. 
I've made this little alternative that works for my use case, maybe someone else will want it too.

```javascript
function omit(object, paths) {
    return _.pick(object, _.pullAll(_.keys(object), paths))
}
```

**Comment by rafde** [comment]
[`_.pickBy`](https://lodash.com/docs/4.17.4#pickBy) is probably a nice alternative for `_.omit`

**Comment by lukeapage** [comment]
We use omit a lot and it's mostly when using objects as maps. We also require immutability, but I guess we can clone and then delete or use object spread even though it's not stage 4 yet.

**Comment by olsonpm** [comment]
@billyjanitsch - Out of curiosity, are you passing `_.omit` objects with prototypes?  I know my personal usage is strictly plain objects where the `in` operator is unnecessary.  I carry a personal version of `_.omit` that iterates over `Objects.keys`, populating a new object with those not specified.  I assume this is the common use-case, but I wouldn't know.

**Comment by jskrzypek** [comment]
I'm currently using `_.omit` and passing it property paths to leave out some nested properties. Is the future-proofed way of doing this to iterate over the array pf paths and use `_.unset`?

**Comment by olsonpm** [comment]
unset mutates whereas omit doesn't.  unset also doesn't take multiple paths (at least in v4, haven't checked if this was changed for v5)

**Comment by sinall** [comment]
Sad too hear this, since I'm looking for 'omit' then find this lib.

**Comment by jdalton** [comment]
Hi @sinall!

I've explained the reasoning [here](https://github.com/lodash/lodash/issues/2930#issuecomment-272298477). It's a bad pattern and there are other, better, ways to accomplish it.

**Comment by danielrob** [comment]
But I didn't come to `omit` to slim down to the keys I do want, I came to _remove the keys I don't want from an unknown collection of keys_ (from a plain object).

Please excuse my ignorance, is the implementation not as simple as something like: 

```
function omit(object, paths) {
   const objCopy = deepCopy(object)
   paths.forEach(path => _.unset(objCopy, path)
   return objCopy
}
```

This seems quite a loss to the library. 

Other language libraries seem to handle this just fine: https://laravel.com/docs/5.6/collections#method-except

**Comment by olsonpm** [comment]
the problem isn't the complexity of the algorithm, it's the poor performance of it.  This should be explained in the related comments

**Comment by danielrob** [comment]
> the problem isn't the complexity of the algorithm, it's the poor performance of it. This should be explained in the related comments

Seems to me the performance is `O(_.cloneDeep) + O(n _.unset)` = `O(_.cloneDeep) + O(n)*O(1)` ~ `O(_.cloneDeep)` for large objects. Should we also remove `_.cloneDeep` 🤔?

**Comment by jdalton** [comment]
Sorry folks, this design choice is not up for debate.
