### ISSUE TITLE
Feature request: Support Regular Expressions (RegExp) for any "match"

### ISSUE THREAD

**Issue by DiegoZoracKy** [lodash/lodash#2933]
Hi, 

IMHO, this feature could give us some super powers by using lodash, without the need of creating new functions/modules or APIs. For example when using _.filter, we would have right away: 

* **A way to define an OR clause** (e.g. property matches with *'this'* or *'that'*)
* **Partial matching** (e.g. look for *'th'* to match *'this'* or *'that'*)
* **Case-Insensitive** (e.g. *'JavaScript'* will match with *'javascript'*)

I will give some use cases examples through code:

```javascript
const modules = [{
	name: 'filterBy1',
	language: 'JavaScript',
	version: '1.0.0'
},{
	name: 'sortBy1',
	language: 'JavaScript',
	version: '2.1.0'
}, {
	name: 'filterBy2',
	language: 'Python',
	version: '1.2.1'
}, {
	name: 'sortBy2',
	language: 'Go',
	version: '3.2.1'
}];

// Only languages JavaScript or Python (OR CLAUSE + CASE-INSENSITIVE)
_.filter(modules, { language: /javascript|Python/i });

// Only versions 1.* (PARTIAL MATCHING)
_.filter(modules, { version: /^1.*/ });

// Only modules which has "filter" in the name, for JavaScript language (CASE-INSENSITIVE + PARTIAL MATCHING)
_.filter(modules, {
	name: /filter/i,
	language: /javascript/i
});

// SOME EXAMPLES USING _.isMatch instead of _.filter

// Is the first module language equal to JavaScript or Python
_.isMatch(modules[0], { language: /JavaScript|Python/i }); // true

// Is the first module language equal to Python or Go
_.isMatch(modules[0], { language: /Python|Go/i }); // false
```

This code shown above is real, and it is already working at my local version, where i tweaked a bit lodash source code to implement this support to RegExp. I can send you a PR. 

I have a module, [data-query](https://github.com/DiegoZoracKy/data-query), which has this feature, and i use it always when working with data sets. Recently i started to work on a project which relies heavily on lodash and just then i started to know better this library. Once i stumbled upon some nested or multiple filters to implemente an OR clauses, or filters with functions just to `.toLowerCase()` before comparison, or indeed to use a `RegExp`, i thought about using my own library, but then, as i liked a lot the lib, i decided that probably would be better to bring here this feature and improve lodash.

What do you think about it?

**Comment by jdalton** [comment]
Hi @DiegoZoracKy!

For v5 I'm simplifying things a bit so this would be adding too much to the shorthands.
Related to #971.
