### ISSUE TITLE
Question - another name for map & pick?

### ISSUE THREAD

**Issue by dsl101** [lodash/lodash#2934]
Apologies if this is a newbie question. I keep finding myself writing this:

    var someArray = [{  // Array of objects, each of which contains several properties
        uid: 0,
        useful: 'something important',
        other: 'meta data which can be ignored',
        ...
    },{
    ...
    }]
    _.map(someArray, item => _.pick(item, ['uid', 'useful']))  // Get an array of 'slimmed down' objects

to get a version of the array of objects containing only a subset of properties. Is there a simpler / combined `_` function which does the job of map and pick together? Something like:

    _.pickAll(someArray, ['uid', 'useful'])

I wondered if `_.invokeMap()` could be used, but I couldn't figure out how to pass `_.pick()` as the 'path'

**Comment by dsl101** [comment]
Update - I found `_.mixin()` and did this:

	function pickAll(array, toPick) {
		return _.map(array, item => _.pick(item, toPick))
	}
	_.mixin({'pickAll': pickAll})

which seems to work - unless there is already a lodash function that I just don't know the name of...

**Comment by jdalton** [comment]
Hi @dsl101!

Looks like you worked it out. The [_.mixin](https://lodash.com/docs/#mixin) is the way to go.
