### ISSUE TITLE
_.get from object with numeric keys

### ISSUE THREAD

**Issue by anlek** [lodash/lodash#2935]
I have my object looking like this:
``` javascript
let x = {
  users: {
    1: {
      firstName: "foo"
    },
    2: {
      firstName: "bar"
    }
  }
}
```

but when I try to do a `_.get(x, 'users.1')` it returns a `undefined`, I assume because it thinks `users` object is an array because of how I'm trying to fetch it.
I'm not sure how to get around this outside of renaming the numbers to something like `id1`, `id2`... this way I could use `'users.id1'` but this will make nested users much harder to map out.

Help?

Thanks for your time,
Andrew

**Comment by jdalton** [comment]
Hi @anlek!

It should work. Make sure you're using the latest Lodash v4 release.

**Comment by anlek** [comment]
Never mind, it seems I was calling an my own internal function which messed things up. My bad.
