### ISSUE TITLE
Feature request: implement _.removeAt

### ISSUE THREAD

**Issue by villesau** [lodash/lodash#2936]
It would be exactly like [_.pullAt](https://lodash.com/docs/4.17.4#pullAt), but it would instead return an array without values at indexes anymore. This would balance the api a bit. Also other vice versa functions compared to pullX -functions would be good to have. 

I know there is _.remove, but it's a bit cumbersome as you need to pass function to it instead of index.

E: Umm.. I was thinking about drafting a pr of this, but i couldn't find tests from master. Is master branch currently in some transition phase to es6 modules perhaps?

**Comment by jdalton** [comment]
Hi @villesau!

The `remove` method is predicate based so there wouldn't be a `removeAt` since that functionality is handed by `pullAt`. The repo is in flux as we're starting v5 rework.
