### ISSUE TITLE
Inconsistent behavior for JS and TS 'result' method

### ISSUE THREAD

**Issue by denver-HJS** [lodash/lodash#2938]
Hi,

I'm not sure if you have any affiliation with the **@types/lodash** NPM package contained in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo or not, but I thought you may be able to help.

I'm using the @types/lodash package from NPM and getting inconsistent behavior for it's `_.result(object, path, [defaultValue])` method.

You are supposed to be able to provide a nested path as the second parameter, but the @types/lodash version is only working for top level properties on the object.

Using `_` from [lodash docs](https://lodash.com/docs/4.17.4#result)
![lodash_screen](https://cloud.githubusercontent.com/assets/1916018/22046546/406a909c-dcd6-11e6-9332-45c4a57a57c5.png)

Using `_` in my personal app that's using @types\lodash
![typed_lodash_screen](https://cloud.githubusercontent.com/assets/1916018/22046545/406a2fbc-dcd6-11e6-837e-2ba9cbd206ab.png)

I'm at version **4.14.45**. Could these unmet peer dependencies be causing an issue?
![screen shot 2017-01-17 at 5 05 48 pm](https://cloud.githubusercontent.com/assets/1916018/22046711/604282b6-dcd7-11e6-86c2-fad9ed9866e3.png)

Thanks!

**Comment by jdalton** [comment]
Hi @denver-HJS!

We don't maintain the TS typings. That falls to the folks at DefinitelyTyped.
