### ISSUE TITLE
fp/throttle expecting arguments in wrong order

### ISSUE THREAD

**Issue by manuelbieh** [lodash/lodash#2939]
Not sure if I'm just doing it wrong, but using `throttle` from `lodash/fp` seems to receive arguments in a wrong order. 

Testcase:

`npm i lodash`

**testcase-working.js**
```
const _ = require('lodash');

function notSoFast() {
  console.log('Throttled');
}

_.throttle(notSoFast, 1500)();
```

`node testcase-working`
`> Throttled`

**testcase-broken.js**
```
const throttle = require('lodash/fp/throttle');

function notSoFast() {
  console.log('Throttled');
}

throttle(notSoFast, 1500)();
```

`node testcase-broken`
```
TypeError: Expected a function
    at throttle (W:\temp\testcase\node_modules\lodash\throttle.js:60:11)
    at wrapper (W:\temp\testcase\node_modules\lodash\_createHybrid.js:87:15)
    at Object.<anonymous> (W:\temp\testcase\test.js:9:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

I have added the following 3 lines to `lodash/throttle.js`:
```
console.log('FUNC:', func);
console.log('WAIT:', wait);
console.log('OPTIONS:', options);
```

and the broken version says:
```
FUNC: 1500
WAIT: function notSoFast() {
  console.log('Throttled');
}
OPTIONS: undefined
```

//edit:
I added the same 3 console.logs to throttle() in `lodash.js` and it correctly says:
```
FUNC: function notSoFast() {
  console.log('Throttled');
}
WAIT: 1500
OPTIONS: undefined
```

**Comment by manuelbieh** [comment]
Ok, I found out that adding `throttle: true` to [`skipReargs`](https://github.com/lodash/lodash/blob/npm/fp/_mapping.js#L339) works. However I have no idea what other consequences this might have.

**Comment by olsonpm** [comment]
@manuelbieh - check out the [fp wiki](https://github.com/lodash/lodash/wiki/FP-Guide#user-content-most-methods-follow-these-rules)

Most importantly

> Methods with a fixed arity of two:
> ... throttle, ...

and as my link directs you to:

> Most methods follow these rules
> A fixed arity of two has an argument order of:
> (b, a)

So in short, the fp version expects
throttle(1500, notSoFast)();

which works (I just tested it)

**Comment by manuelbieh** [comment]
Yes, it works. I just think it's pretty confusing that you cant just replace `_.throttle(a, b)` with the fp version of the same function without switching the argument order … Seemed more like a bug for me.

**Comment by olsonpm** [comment]
At the top of the wiki:

> The lodash/fp module promotes a more functional programming (FP) friendly style by exporting an instance of lodash with its methods wrapped to produce immutable auto-curried iteratee-first data-last methods.

So definitely on purpose and for a good reason (also considering it explicitly says what it's doing, not a bug at all).  Takes a bit of getting used to if you haven't programmed functinoally before.  Lodash is what introduced me to functional programming so it took me a few months to get a grasp of it.  Functional programming isn't for everyone, but I really like it.

**Comment by olsonpm** [comment]
I guess if the complaint is the function should go first, then the fix would be to add throttle and debounce to the list of exceptions (which are documented in the wiki as well).  I can see a PR being accepted for that.

**Comment by jdalton** [comment]
Hi @manuelbieh!

The order is by design. The argument order flipping is designed to make the curried methods more easily consumed. So in this case you can create a throttle factory of a given `wait`.

**Comment by manuelbieh** [comment]
Ok, thank you! I just wanted to make sure that it's not a bug and my code breaks once it is fixed when I'm using the diverging arguments order! :smiley:
