### ISSUE TITLE
Feature Request: Implement _.distinctParams

### ISSUE THREAD

**Issue by romulof** [lodash/lodash#2943]
A simple function wrapper that calls the wrapped function only when params have changed from a previous call.

Example:

```es6
import distinctParams from 'lodash/distinctParams';

function callMeWhenChanged(param1, param2) {
  console.log('Changed!', param1, param2);
}

const wrapped = distinctParams(callMeWhenChanged);

wrapped('foo', 'bar')
// > Changed! foo bar
wrapped('foo', 'bar')
// Nothing
wrapped('foo', 'circle')
// > Changed! foo circle
```

This would be great to use together with `debounce` to process input onChage before requesting a search query to server. Example:

```es6
import distinctParams from 'lodash/distinctParams';
import debounce from 'lodash/debounce';

function requestSearch(query) {
  ...
}

const requestSeachWhenUserIsCalm = debounce(distinctParams(requestSearch), 300);

function onChange(event) {
  requestSeachWhenUserIsCalm(event.target.value);
}

const inputElement = document.getElementById('searchInput')
inputElement.addEventListener('change', onChange);
```

PS: I'm terrible naming things. Name this functionality any way you like 😄

**Comment by jdalton** [comment]
Hi @romulof!

Thanks for the suggestion. I think this is a better fit as a standalone package or mixin.

**Comment by romulof** [comment]
Further thinking on it:

I think a simple memonization library with cache size 1 will do the trick.

Thanks for the quick response.
