### ISSUE TITLE
I would like an ability to get a random value from an array

### ISSUE THREAD

**Issue by NickDMansfield** [lodash/lodash#2944]
I already wrote the code in a fork, and figured it would be a handy shorthand.

The use case I had was that I am procedurally generating something and use lodash for my randomization.  Since I kept having to wrap it, I figured I could just provide it as an overload to _.random

**Comment by jdalton** [comment]
Hi @NickDMansfield!

You're looking for [_.sample](https://lodash.com/docs/#sample).

**Comment by NickDMansfield** [comment]
Thanks!!
