### ISSUE TITLE
Support for Keyed collections

### ISSUE THREAD

**Issue by AesaKamar** [lodash/lodash#2945]
ES6 has a few builtin collection types 
- Map
- Set
- WeakMap
- WeakSet

Does lodash support, or plan to support these? If not, is there a reason that they are not included?

**Comment by jdalton** [comment]
Hi @AesaKamar!

At the moment I'm leaning towards leveraging ES6 spread to convert values to arrays instead.

**Comment by AesaKamar** [comment]
@jdalton Thanks for the update, that's exactly what I needed.
