### ISSUE TITLE
[Question] Lodash modularize

### ISSUE THREAD

**Issue by rockchalkwushock** [lodash/lodash#2947]
So I'm trying to make my application more performant and see that lodash is quite large in context to other modules. This performance stuff is undeclared territory so I'm first looking at making sure I'm only using what I need for the application to run and that the imports aren't bloating my code. I brought  Lodash into my project through `yarn add lodash`. I am only using the `throttle` method so I originally just had it like so:
```javascript
import { throttle } from 'lodash';

// changed to...

import throttle from 'lodash/throttle';
```

The I started to read about the Lodash CLI and Lodash Modularize. So if I'm understanding correctly I could use the CLI to create my own custom build of Lodash that contains only the method I am needing (plus core packages I imagine)? Would this be a more viable approach?

**Comment by mcmire** [comment]
I have this question as well. I looked at the roadmap and the FP Guide document in the wiki which seemed to indicate that Lodash CLI/Modularize and the per-method packages are going away in favor of saying `import whatever from 'lodash/whatever'`. Does that work now?

**Comment by jdalton** [comment]
The `lodash-cli` is on its way out (to move to `lodash/lodash-archive`). With modern bundlers you can just use the `lodash` package and cherry-pick the modules you want or use something like [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) to cherry-pick for you.

**Comment by mcmire** [comment]
Fantastic!! I've never seen Babel used that way but it's absolutely genius. 😎  🍺

**Comment by rockchalkwushock** [comment]
@jdalton 

Sorry this is my first time really doing any kind of performance re-write like this...or diving into source code for that matter; I also apologize for this not being really where I should have reopened an issue. I just figured for continuity of the question asked it was best asked here.

I first swapped out, I guess you would call it _modules_, and went with:

```javascript
import throttle from 'lodash-es/throttle';
```

This led to about a 100kb reduction, a good start.

 I then looked at the `babel-plugin-lodash` and for starters am just running it in `development` mode in my `.babelrc`:

```rc
{
  "env": {
    "development": {
      "presets": ["env", ["es2015", {"modules": false}], "react", "stage-0"],
      "plugins": [
        "lodash",
        "transform-class-properties",
        "react-hot-loader/babel"
      ]
    },
    "production": {
      "presets": [["es2015", {"modules": false}], "react", "stage-0"]
    },
    "test": {
      "presets": ["env", ["es2015", {"modules": false}], "react", "stage-0"],
      "plugins": ["istanbul"]
    }
  }
}
```
My question for the plugin refers to the _optionsObject_:
```rc
 ["lodash", { "id": "lodash-es", cwd: "???" }],
```
I'm a little unsure what is required in the _current working directory_ key. Is that possibly the location of the lodash method being used in my code, or is that the path to `lodash-es`? The name being `cwd` I feel the latter is probably not right.

My other question is about `lodash-webpack-plugin`:

I looked at the _mapping.js_ file to see what the feature would be for _throttle_ and did not find it so I originally just went with using `"lodash"` in the `.babelrc` & using `new LodashModuleReplacementPlugin(),` in my `webpack.dev.config.js`. I was meet with about a 24kb reduction in `lodash@4.17.4` (I used `webpack-dashboard` to get a break down of the modules):

_webpack.dev.config.js_
```javascript 
require('dotenv-safe').load();

const webpack = require('webpack');
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const DashboardPlugin = require('webpack-dashboard/plugin');
const LodashModuleReplacementPlugin = require('lodash-webpack-plugin');

const VENDOR_LIBS = [
  'axios', 'lodash-es', 'react', 'react-dom', 'react-redux',
  'react-redux-multilingual', 'react-redux-toastr', 'react-router',
  'react-router-redux', 'redux', 'redux-auth-wrapper',
  'redux-form', 'redux-pack', 'redux-promise-middleware',
  'semantic-ui-react'
];

module.exports = {
  entry: {
    bundle: [
      'babel-polyfill',
      'react-hot-loader/patch',
      'webpack-dev-server/client?http://localhost:9000',
      'webpack/hot/only-dev-server',
      './client/index.js'
    ],
    vendor: VENDOR_LIBS,
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].js',
    publicPath: '/'
  },
  module: {
    rules: [
      {
        use: 'babel-loader',
        test: /\.js$/,
        exclude: /node_modules/,
      },
      {
        loader: ExtractTextPlugin.extract({
          loader: 'css-loader'
        }),
        test: /\.css$/
      }
    ]
  },
  performance: {
    hints: false
  },
  devtool: 'inline-source-map',
  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 9000,
    hot: true,
    inline: true,
    historyApiFallback: true,
    open: true,
    quiet: true,
    proxy: {
      '/api': 'http://localhost:3000'
    }
  },
  plugins: [
    new LodashModuleReplacementPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
        CLOUD_NAME: JSON.stringify(process.env.CLOUD_NAME),
        UPLOAD_PRESET: JSON.stringify(process.env.UPLOAD_PRESET),
      }
    }),
    new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest']
    }),
    new DashboardPlugin(),
    new HtmlWebpackPlugin({
      template: 'public/index.html'
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
    new ExtractTextPlugin('style.css'),
  ]
};
```

I do get an interesting error message when adding `new LodashModuleReplacementPlugin(),`:

![screen shot 2017-01-24 at 11 20 21 pm](https://cloud.githubusercontent.com/assets/19720404/22278860/314da926-e28c-11e6-8746-04ceb13d2df6.png)

It's only when this new instance is declared that the error appears; but it seems to be breaking something in my store (probably the _throttle_) and thus causes any `connect()` components to fail with this error message. However when I looked at the source code for the `lodash-es/throttle` method I did not see anything referring to an _iteratee_ that could some how be getting passed as a prop. It very well could correlate as well to not passing the `cwd` key in the `.babelrc`.

Any guidance or explanation to my questions would be greatly appreciated. The error could likely be conflict with different techs and I will have to dive in to find that fix. Thanks!

**Comment by jdalton** [comment]
You only need to specify an "id" in the `babel-plugin-lodash` options if you're using more than 1 lodash module. By default the plugin will sniff out which one you're using. The "cwd" option is used to set the directory where lodash modules [are looked for](https://github.com/lodash/babel-plugin-lodash/issues/56). You won't likely need to set that either.

The `lodash-webpack-plugin` issue you're seeing is because by default the plugin disables iteratee shorthands. To enable that feature set you'll want to set its `'shorthands': true` option.

**Comment by rockchalkwushock** [comment]
Thanks for the clarification and the heads up on what the error message was coming from @jdalton
