### ISSUE TITLE
Why is `lower` optional in `clamp`?

### ISSUE THREAD

**Issue by arosequist** [lodash/lodash#2949]
Would changing this function from `_.clamp(number, [lower], upper)` to `_.clamp(number, lower, upper)` be considered for the next major version? I don't understand the value of allowing `lower` to be optional.

- If I'm intentionally excluding that parameter (`_.clamp(n, 100)`), isn't that just `_.max`?
- If I'm unintentionally excluding it (`_.clamp(n, min, max)`, where `max` is sometimes `undefined`), then I get very unexpected results (`min` is sometimes treated as `max`).

**Comment by jdalton** [comment]
Sure! Let's nix the optional `lower` bit.

**Comment by felds** [comment]
@arosequist it is counter-intuitive but `_.clamp(number, max)` would actually be the same as `Math.min()`, as `clamp(1, 9)` and `clamp(9, 1)` would both return `1`.

btw, a quick way to make your own clamp is like so:
```js
const clamp = (min, max, n) => Math.max(min, Math.min(max, n))
```

**Comment by arosequist** [comment]
Ah, yeah, I had that backwards. I'm still not sure about the practical value of the `_.clamp(number, max)` behavior (and it can act very unexpectedly sometimes).
