### ISSUE TITLE
Should `toPairs` take a `Collection`?

### ISSUE THREAD

**Issue by Mr-Wallet** [lodash/lodash#2950]
So far I have not found any instance where `toPairs` fails to work on a simple array (though admittedly, the output of array indices as strings is a bit of a "gotcha"). However in the official documentation, the parameter for `toPairs` is an Object. This makes me nervous to use `toPairs` on arrays because the lack of documentation implies that my use case could possibly receive a breaking change in even a patch-level version bump.

I assume that the `Object` parameter is not intended to also include `Array` because there's a separate `Collection` parameter type.

Would it be possible to enshrine the use of `toPairs` on arrays in the docs by re-specifying it as a `Collection` method? If I've misunderstood the relationship between `Object`, `Array`, and `Collection`, could the docs add clarification on that point?

Thanks for your time.

**Comment by jdalton** [comment]
The `toPairs` method is an "Objects" category method because it's intended and will treat values like objects. Array are objects so they'll work. It may just respect sparse arrays in this case where normally it treats holes as literal `undefined` values.

**Comment by Mr-Wallet** [comment]
Can you please clarify the distinction between "Objects" and "Collections"? There doesn't seem to be anything clarifying this in the docs. I intuited that Collection meant "really _all_ objects, including arrays that are often not thought of as objects", but that intuition was clearly wrong. My request for that clarification to end up in the docs in some form still stands (unless it _is_ in the docs and I simple missed it - in which case, very sorry!)

**Comment by jdalton** [comment]
An "Objects" category means it treats things as plain object with no distinctions. A "Collections" method will prioritize array-like values over objects and forks behavior for array-like values and objects.
