### ISSUE TITLE
`clone` with extended Array throws Exception

### ISSUE THREAD

**Issue by inner-peace** [lodash/lodash#2951]
Were I `clone()` extended Array (`class Foo extends Array`) I'd catch `TypeError: Class constructor Foo cannot be invoked without 'new'`. 
Would you add `new` op in [this row](https://github.com/lodash/lodash/blob/59a9eb6e0175198c4ec45e48764edb6858597d2d/.internal/initCloneArray.js#L13)? Thanks!

**Comment by jdalton** [comment]
Hi @inner-peace!

Our code path assumes if you've gotten that far you're array-like enough. The array constructor can be called without the `new` operator.

**Comment by inner-peace** [comment]
Hi @jdalton!

But why did you use `array.constructor` instead `Array`? It looks like support for inheritance

**Comment by jdalton** [comment]
Because I want to support arrays from other realms.

**Comment by SylvainEstevez** [comment]
Seems like this is actually fixed: https://github.com/lodash/lodash/commit/b0980a90fc83bc92e040f905ebed8196f895949c#diff-c98b19a4629c791fefaceea05556df52R152

But I can't find the fix in the latest NPM version. Any specific version I should look at?
