### ISSUE TITLE
`get` and `set` strip backslashes from paths when using array notation and quotes

### ISSUE THREAD

**Issue by Mr-Wallet** [lodash/lodash#2952]
I'm working on a node application that needs to run on Windows, which includes Windows paths. I want to set a key on an option that refers to a path in Windows. Normally set interprets periods as property access:
```javascript
const obj = _.set({}, 'C:\\valid.folder.name', true)
// obj equals { 'C:\\': { valid: { folder: { name: true } } } }
```
To avoid this with other (non-file-path) keys that include periods, we've used array notation and quotes:
```javascript
const key  = 'single.key.with.periods' 
const obj = _.set({}, `['${key}']`, true)
// obj equals { 'single.key.with.periods: true }
```
This trick only works with square brackets _and_ quotes, but it has worked great so far.

However, this strips backslashes from the path, which is unexpected:
```javascript
const path = 'C:\\valid.folder.name'
const obj = _.set({}, `['${path}']`, true)
// EXPECTED: obj equals { 'C:\\valid.folder.name': true }
// ACTUAL: obj equals { 'C:valid.folder.name': true }
```

Right now we can try to band-aid by replacing `\\` with `\\\\` when calling `get` or `set`, which results in the intended path being used. However this is pretty brittle since we only need to forget to do it once before something blows up. Since `\\` doesn't (to my knowledge) have any particular reserved meaning with regard to object properties or how lodash object "paths" are documented, the way the path is being resolved doesn't seem like deliberate behavior.

**Comment by jdalton** [comment]
Hi @Mr-Wallet!

Escaping gets a bit tricker when you nesting strings.
It should be:
```js
_.toPath('["a\\\\v"]')
// -> ['a\v']
```
To avoid that you can always provide an array as the path:
```js
_.set({}, [path], true)
=> { 'C:\valid.folder.name': true }
```
