### ISSUE TITLE
_.mapKeys(object, ...) fails in TypeScript if object is type Object

### ISSUE THREAD

**Issue by Shingyx** [lodash/lodash#2955]
I noticed that in TypeScript, if I call _mapKeys(object, ...) with object being type Object, TypeScript gives the following error when it tries to compile:
`error TS2345: Argument of type 'Object' is not assignable to parameter of type 'List<{}> | Dictionary<{}>'`
Is this expected behaviour?

Thanks.

**Comment by jdalton** [comment]
Hi @Shingyx!

We don't maintain the lodash typings. You're best bet would be to file an issue on whoever produces them (ex: DefinitelyTyped).

**Comment by Shingyx** [comment]
Thanks for the fast response. I'll do just that.
