### ISSUE TITLE
Lodash/fp functions

### ISSUE THREAD

**Issue by Cinderella-Man** [lodash/lodash#2956]
Hi,

I moved recently from Ramda to lodash/fp and first of all thank you for a great library!

I have problems finding some functions in lodash:
- `and` and `or` functions that would take pair (or array) of boolean values and return false/true
- `.ap` - applicative function that will dispatch `ap` function on functor/monad
- `.map` / `.filter` / `.chain` / `.flatMap` - just to be sure - they are dispatching second argument's map, if present?
- lenses? do you have any support for them?

Thanks in advance,

Kamil

**Comment by jdalton** [comment]
Hi @Cinderella-Man!

We don't dispatch so you won't find that in `lodash/fp`.  I'm up for adding `and` and `or` modules though. If you'd like to do a pull request that would rock.

**Comment by Cinderella-Man** [comment]
@jdalton thanks for quick feedback - I will follow up with pull request. Only questions are:
- are we staying with names `and` and `or`?
- should they take 2 values or array of values?
- should they be strict?

**Comment by jdalton** [comment]
Let's keep the names `and` and `or`. Keep it 2 arguments. Since they're ES6 modules they'll be implicitly strict mode.
