### ISSUE TITLE
Cache does not need to implement the full Map interface... or does it?

### ISSUE THREAD

**Issue by DavidBruant** [lodash/lodash#2957]
This issue is more a discussion than a proper lodash issue right now. Depending on the outcome, it's likely to become a docs issue.

I'm starting this discussion because I found myself interested in implementing various cache strategies but didn't feel comfortable with what the doc was asking from me.

>  **Note:** The cache is exposed as the `cache` property on the memoized function. Its creation may be customized by replacing the `memoize.Cache` constructor with one whose instances implement the [`Map`](http://ecma-international.org/ecma-262/7.0/#sec-properties-of-the-map-prototype-object) method interface of `clear`, `delete`, `get`, `has`, and `set`.

[source](https://github.com/lodash/lodash/blob/3c5b828d7e0460812e2a24605a91ed5c8130d287/memoize.js#L10-L14)

However, the only methods [used](https://github.com/lodash/lodash/blob/3c5b828d7e0460812e2a24605a91ed5c8130d287/memoize.js#L53-L57) by `memoize` are get/set/has.
So, for memoize to work, the Cache constructor does not need to create objects that implement more than that. Note that it's the reason `WeakMap` is a valid option despite lacking a `clear` method.

There exists a usage of [cache.clear and cache.size](https://github.com/lodash/lodash/blob/3c5b828d7e0460812e2a24605a91ed5c8130d287/.internal/memoizeCapped.js#L17-L18) in the internals.
The bad news is that WeakMap does not implement either. The good news is that the only user of `.internal/memoizeCapped` so far is [stringToPath](https://github.com/lodash/lodash/blob/085dc1aa01783e0ce924f39f2b2ed5464c4572e1/.internal/stringToPath.js) and in a way that does not enable user code to change `memoize.Cache` before the `memoizeCapped` call.

It's not 100% clear (pun intended) whether the good news is luck or deliberate. In case of luck, then it means WeakMap is disqualified? should any Cache also implement a `size` property?
In case it's deliberate, maybe a comment in `.internal/memoizeCapped`/`stringToPath` would be useful to express intent.

**Comment by jdalton** [comment]
The choice of `memoizeCapped` using `clear` and being internal was deliberate. We have unit tests for working with `WeakMaps` for external use. Feel free to tweak the docs and send a PR.

**Comment by DavidBruant** [comment]
Sorry to bother, but where are the tests? I cannot find the `test` directory and git clone + npm i + npm test leads to an error right now.

**Comment by jdalton** [comment]
Look to the [release tags](https://github.com/lodash/lodash/blob/4.17.4/test/test.js) it looks like I added `clear` to the custom map test implementation so I should have one without but yes. It's intended to work with weak maps.
