### ISSUE TITLE
fast-memoize

### ISSUE THREAD

**Issue by Gregoor** [lodash/lodash#2959]
Hi,

been using lodash for a few years and very happy with it. Thanks for creating it and keeping it awesome 👍 

Today I stumbled over [this](https://github.com/caiogondim/fast-memoize.js) repo and the article that goes with it and was curious to know whether the lodash community would be interested in a faster and more feature-rich memoization (it also does memoization for functions with more than 1 argument)?

**Comment by jdalton** [comment]
Hi @Gregoor!

I've been aware of that one for a while and it's not for me because

  * it uses `JSON.stringify` to serialize arguments
  * it treats arguments like the number `1` and string `'1'` or `null` and `'null'` as the same value
  * it's optimized for a single environment

**Comment by jdalton** [comment]
Basically if you're fast but end up with the wrong result you're speed was pointless. Lodash is robust enough to get the correct result while being speedy. This is a common issue with "fastest" implementations. They look great as long as you don't look too closely.

**Comment by Gregoor** [comment]
Good points, thanks. I wasn't aware of that and I wonder if the author was.

**Comment by jdalton** [comment]
I'm guessing since they made it configurable they have an idea that there's some gotchas.
