### ISSUE TITLE
Preserve object type in returned values

### ISSUE THREAD

**Issue by topicus** [lodash/lodash#2960]
I've noticed assign allows to override arrays by their index. That's useful when you need to create a list with default values and allow users to change them later. For example:

```javascript
// Returns ['John', 'Lucas', 'default-3']
_.assign(['default-1','default-2','default-3'], ['John','Lucas']);
```
Even when the function signature says it should return an object it's preserving the original type.

However I've expected omit function also preserve the type but instead it is casting the returned value to an object.

```javascript
// Returns Object {1: 10, 2: 20, 3: 2, 4: 0}
_.omit([3,10,20,2, 0], 0);
``` 
I want to use omit like I did with assign. 

I'm not sure if there is a reason behind that behavior so this is question rather than an issue.

Thanks in advance

**Comment by jdalton** [comment]
You really should treat arrays as arrays and keep object mutation to object Objects. While mutation methods may work on arrays while treating them as plain objects you shouldn't assume other "Objects" methods like "omit" will sniff out the kinds of objects. Sub-classing would be a major pain.

**Comment by topicus** [comment]
Wow, that was fast. Thank you for you answer.
