### ISSUE TITLE
Duplicate code in baseClone.js ?

### ISSUE THREAD

**Issue by westrem** [lodash/lodash#2961]
Hi,

I was just browsing the internal implementation of [baseClone.js](lodash/.internal/baseClone.js) and realized, that some of the `*Tag` constants are duplicated. Example:

`const boolTag = '[object Boolean]';`

[can be found on line 32](https://github.com/lodash/lodash/blob/master/.internal/baseClone.js#L32)
[can be found on line 97](https://github.com/lodash/lodash/blob/master/.internal/baseClone.js#L97)

How is this even possible? This should throw an Error.

Or am I missing something?

@jdalton

**Comment by demoneaux** [comment]
This is probably just some errors in the process of refactoring for v5. Seems like the tests have also been removed?

**Comment by jdalton** [comment]
Yep, pardon the mess.
