### ISSUE TITLE
Lodash tslint error

### ISSUE THREAD

**Issue by anvesh48** [lodash/lodash#2962]
I have updated the library as part of my update i am seeing the following error in the console:

...\node_modules\@types\lodash\index.d.ts:245:25                                                
    Cannot find name 'Partial'.                                                                                                                            
[default] Checking finished with 1 errors

**Comment by jdalton** [comment]
Hi @anvesh48!

We don't maintain `@types/lodash`.

**Comment by anvesh48** [comment]
Thanks for your reply.
