### ISSUE TITLE
require('./_falseOptions')

### ISSUE THREAD

**Issue by ghoshnirmalya** [lodash/lodash#2963]
Why is `require('./_falseOptions')` present in some files (https://github.com/lodash/lodash/blob/npm/fp/isArray.js#L2) but not present in others (https://github.com/lodash/lodash/blob/npm/fp/find.js)?

Isn't this necessary while importing using the `lodash/fp` build?

**Comment by jdalton** [comment]
Hi @ghoshnirmalya!

No `falseOptions` is just a helpful options fp convert options preference used for modules that don't need conversion.
