### ISSUE TITLE
_merge converts Buffer property to Array when dest property is also a buffer

### ISSUE THREAD

**Issue by TomaszKasowicz** [lodash/lodash#2964]
Hi
When working with "merge" function i noticed than when destination and source properties are Buffers then destination property is converted to Array which results in stack trace (missing toString function).
This issue only exists when source property exists.

example:
```
var _ = require('lodash');
var testStr = 'Lorem Ipsum';
let obj1 = { foo: Buffer.from(testStr) };
let obj2 = { foo: Buffer.from(testStr) };

_.merge(obj1,obj2);
console.log('isBuffer(obj1.foo) = ', Buffer.isBuffer(obj1.foo));
console.log('isBuffer(obj2.foo) = ', Buffer.isBuffer(obj2.foo));
```

The Results are:
```
isBuffer(obj1.foo) =  false
isBuffer(obj2.foo) =  true
```

**Workaround is to use "lodash/fp" or use "mergeWith" and a customizer function**

Is this OK?
- If Yes then the issue can be closed
- If No then the solution would be to modify baseMergeDeep function and change the order of checking of objValue (move isArrayLikeObject(objValue) after checking if "isBuff" is true), but I'm not sure if this would be the right solutions.

Thank You
Tomasz

**Comment by jdalton** [comment]
I can't repro any error being thrown but I can speak to the merging behavior. It is by design to convert to arrays when merging array-like values. That said you can customize the merge behavior with [_.mergeWith](https://lodash.com/docs/#mergeWith).

**Comment by TomaszKasowicz** [comment]
In my case (node 7.2.1) i just had to add 
`console.log('obj1.foo = ', obj1.foo)`
at the end of the code above
The result is 
```
buffer.js:463
        return this.hexSlice(start, end);
                    ^

TypeError: argument should be a Buffer
    at Array.slowToString (buffer.js:463:21)
    at Array.Buffer.toString (buffer.js:500:27)
    at Array.inspect (buffer.js:524:16)
    at formatValue (util.js:352:36)
    at inspect (util.js:186:10)
    at exports.format (util.js:130:20)
    at Console.log (console.js:43:37)
    at Object.<anonymous> (/home/tomek/lodash/test.js:25:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

I will use _mergeWith in my case.
Thanks
