### ISSUE TITLE
_.remove doesn't play nice with Vue

### ISSUE THREAD

**Issue by rtheunissen** [lodash/lodash#2965]
There's an issue when using lodash with Vue when you want to remove a value from a reactive array. The situation is explained clearly here: https://github.com/vuejs/vue/issues/2673

Vue captures the `splice` call on the array, but because lodash uses Array.splice directly, that capture never takes place, and the observer is never notified.

Q: Why does lodash use `Array.prototype` instead of calling `splice` directly on the subject array?

**Comment by rafde** [comment]
It seems like [Vuejs](https://github.com/vuejs/vue/blob/dev/dist/vue.js#L608-L650) is using [bad practice](https://www.nczonline.net/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/).

**Comment by Elevista** [comment]
Bypass solution:
```js
export let wrapLodashArrForVueMixin = _(['pull', 'pullAll', 'pullAllBy', 'pullAllWith', 'pullAt', 'remove'])
  .map(fnName => {
    let fn = _[fnName]
    return [
      fnName,
      function (v, ...args) {
        let ret = fn(v, ...args)
        if (v instanceof Array) v.push()
        return ret
      }]
  })
  .fromPairs()
  .value()
```
(wrap lodash array functions)

usage:
```js
_.mixin(wrapLodashArrForVueMixin)
_(foo).pull(1)
```

**Comment by rosemalejohn** [comment]
To make the array reactive I normally do this. I re-assign the filtered array into Vue data property

```
this.items = [
   ...this.items
]
``
