### ISSUE TITLE
Lodash web page not working

### ISSUE THREAD

**Issue by santigarcor** [lodash/lodash#2968]
When i try to access the web it says `Page Not found`, and it doesn't matter which page i try to access

**Comment by jdalton** [comment]
It looks like it's back up 🎉

**Comment by jdalton** [comment]
Did you have JS disabled or on a browser without appcache/serverworker support? I only noticed an issue when I nixed the app caches for the page.

**Comment by santigarcor** [comment]
Now it's working again :smile: .

Thanks!
