### ISSUE TITLE
fp/merge converts arrays to object

### ISSUE THREAD

**Issue by SevInf** [lodash/lodash#2970]
When given arrays as arguments, `lodash/merge`returns an array. However, this is not true for `lodash/fp/merge`. For example:

```js
const merge = require('lodash/merge');
const mergeFp = require('lodash/fp/merge');

merge([1, 2], [3]);
  // returns [3, 2]
mergeFp([1, 2], [3]);
  // returns { '0': 3, '1': 2 }
```

**Comment by jdalton** [comment]
Hi @SevInf!

That's because `fp` is immutable and will create a new object. I'll mull over adding type detection but that could be a drag where the common case is to merge plain objects.
