### ISSUE TITLE
Dead Link to 3.10.1 Documentation

### ISSUE THREAD

**Issue by Grets** [lodash/lodash#2977]
The page that used to hold the 3.10.1 documentation and is still linked to from the main docs page is now a 404.

https://lodash.com/docs/3.10.1 - I get a 404

![image](https://cloud.githubusercontent.com/assets/4066500/22653982/483e7058-ec59-11e6-817b-44d480fa7838.png)

**Comment by Grets** [comment]
I'm going to use http://devdocs.io/lodash~3/ for now.

**Comment by jdalton** [comment]
Dup of https://github.com/lodash/lodash.com/issues/130.
