### ISSUE TITLE
ucwords implementation

### ISSUE THREAD

**Issue by bogomips** [lodash/lodash#2978]
Hi, since the "string" section has some useful methods, I think it could be appropriate to add something similar to php ucwords().
I've personally adopted a method found online that looks well developed: http://locutus.io/php/strings/ucwords/

**Comment by jdalton** [comment]
Hi @bogomips!

You're looking for [_.startCase](https://lodash.com/docs#startCase).

**Comment by bogomips** [comment]
You're actually right, I was a little confused by this example:
_.startCase('__FOO_BAR__');
// => 'FOO BAR'
while i expected 'Foo Bar'
I can reach the same result by using  _.toLower() followed by _startCase()
