### ISSUE TITLE
Add word "compose" to flow / flowRight documentation

### ISSUE THREAD

**Issue by rohanorton** [lodash/lodash#2979]
I just spent an embarrassing amount of time looking for a function that does composition in the docs. Previously this function was called "compose", but has since been renamed to "flow". I have no issue whatsoever with the rename of this. However, for the sake of searchability, it would be really nice if there was some reference to the fact that this function used to be called "compose" or saying that what it does is "compose" functions together, as this is a very familiar term coming from functional programming.

Thanks! :)

**Comment by jdalton** [comment]
No problem! Thanks for the suggestion 😄

**Comment by n1ru4l** [comment]
After searching for compose I ended here. It hasn't changed yet :sweat:

**Comment by aludvigsen** [comment]
Same thing here! 😆 :rofl:

**Comment by elhesuu** [comment]
It's on master: https://github.com/lodash/lodash/blob/master/flow.js#L2 but for some reason not in the docs: https://lodash.com/docs/4.17.4#flow

**Comment by ragboyjr** [comment]
Same here. It's a bit odd to use the name `flowRight` instead of `compose` which is the standard name in functional languages for composing functions together.

**Comment by jdalton** [comment]
Pull requests accepted.
