### ISSUE TITLE
support Set for set operations

### ISSUE THREAD

**Issue by fletom** [lodash/lodash#2981]
currently, `Set` objects are not supported for set operations like `difference`

```
> lodash.difference(new Set([2, 1]), new Set([2, 3]))
[]
```

I asked about this on Gitter and was told it would be best to open a new issue

**Comment by jdalton** [comment]
Hi @fletom 

These are "Arrays" methods. You could spread your sets into arrays to be processed.

**Comment by jfmengels** [comment]
That sounds like a good solution for Lodash <= v4, but won't there be any support for Set/Map operations in v5 (either allowing the arguments to be of those types, or having separately named methods for those types)?

**Comment by jdalton** [comment]
None planned. I don't want the overhead. Considering how simple it is to do:
```js
difference([...set1], [...set2])
```

**Comment by jfmengels** [comment]
Ok. Honestly, I think it's weird it's not even in the JS spec. `union`/`intersection`/`difference` sounds so inherently useful and linked to Sets that I find it weird that it's not in there.

I think that having Set be popularized, this request (and/or issues) will come up more often though.

**Comment by jdalton** [comment]
Trying to get anything into the spec is a major pain and then it comes out wrong. Library land is where it's at 💪

**Comment by jfmengels** [comment]
Yes. Even if it was implemented right, I'm pretty sure a library could do it better, as some libraries (hint hint) have done so.

**Comment by fletom** [comment]
agreed on the spec itself being weirdly lacking, though of course there are all kinds of deficiencies in JS that utility libraries are there to make up for.

it's your project and entirely up to you all, so I won't press the issue further than to say that in my opinion the fact that's it's "easy" to write `[...set1]` does not make it at all nice to read or write, and that casting to `Array` every time is probably also a performance concern in some cases

on the other hand, if this is truly wontfix, I would suggest that the documentation should be updated to clarify that `Set` is not supported, since it's very counterintuitive for anyone coming from a math background or from other languages like Python (where `difference` and `intersection` are *only* available as methods on the `set` type). these are set operations after all.

I would also suggest that my example above raise an error instead of incorrectly returning `[]`, since otherwise it's hard to figure out that your code is not working. but @jfmengels informed me that this is intentional and that lodash policy is to always fail silently, so I assume that will be wontfix as well.

**Comment by jdalton** [comment]
> I would suggest that the documentation should be updated to clarify that Set is not supported,

The method is documented to accept arrays only. Supporting iterators in general would be a drag on the utils.

> I would also suggest that my example above raise an error instead of incorrectly returning `[]`

That's not really the Lodash way™
