### ISSUE TITLE
seq.chain ES6 import

### ISSUE THREAD

**Issue by sospedra** [lodash/lodash#2982]
Can I import `chain` with a limited number of methods? Currently, if `chain` is imported by cherry picking: `import { chain } from 'lodash/seq'` it simply doesn't work.

Here's a working demo: http://www.webpackbin.com/Vkkb_GN_G
Note the `wrong` variable.

So far, what I understand is that `chain` needs to be loaded from the whole `_` (lodash) in order to activate the chainable API. Would be nice - following the ES6 import/export logic - to being able to pick whatever methods do we need at every moment.

**Comment by jdalton** [comment]
Hi @sospedra!

The the `lodash/seq` collection doesn't wire up chaining. It was on our backlog but we never got around to it. This means you'll have to connect things up as it's done in the monolithic source. I believe there's an issue that covered it (not seeing it in my quick search though).

**Comment by jdalton** [comment]
Found it https://github.com/lodash/lodash/issues/966#issuecomment-74384259
