### ISSUE TITLE
Wrong array/object detection in _.each/_.foreach functions

### ISSUE THREAD

**Issue by DennyBravo** [lodash/lodash#2989]
If Object{} for iterating have "length" field function trying to iterate this Object{} as Array[], 
etc.:

```
var someObject = {
    id: 1,
    text: 'some text here',
    length: 20
};
_.each(someObject, function(v, k){ console.log(k, v); });
```

result:
```
0 undefined
1 undefined
2 undefined
```

**Comment by falsyvalues** [comment]
As far as I know it is intended behavior, take a look for example at this issue #1477

**Comment by DennyBravo** [comment]
You are right, thanks.
