### ISSUE TITLE
Enhancement: Adding context argument to scoped functions

### ISSUE THREAD

**Issue by benshewmake** [lodash/lodash#2990]
### Overview
I am implementing a web app that is using [Backbone.js](http://backbonejs.org/#). Within the app I am using several plugins for **Backbone.js**. 

### The Problem
**Backbone's** main dependency is [Underscore.js](http://underscorejs.org), but they also add that it can be replaced by **LoDash**. I would really like to implement LoDash, but I have run into several issues during implementation.

The main issue is that the **Backbone.js** plugins were also implemented using **Underscore.js**. After some digging through several of the plugins that I am using, the main problem that I came across is that **Underscore.js** allows you to pass in the context as an argument to most of their methods. **LoDash** does not. Therefore, when using **LoDash** instead of **Underscore.js** in my application, the plugins don't work as intended because they are also utilizing the context function parameter.

i.e., 
**Underscore:**
```javascript
_.each = _.forEach = function(obj, iteratee, context) {}
_.map = _.collect = function(obj, iteratee, context) {}
_.filter = _.select = function(obj, predicate, context) {}
...
And so on..
```
**LoDash:**
```javascript
function forEach(collection, iteratee) {}
function map(collection, iteratee) {}
function filter(collection, predicate) {}
...
And so on..
```
**Simplified Use Case:**
```javascript
var context = {
    sum: 0
};

/**
 * Demonstrate the ability to pass in a context existing out of current function scope.
 */
function f1() {
    _.each([{a: 1, b: 2},{a:3, b:4}], function(object, index) {
        context.sum += (object.a + object.b);
    }, context);
}

f1();
console.log(context.sum);      // outputs: 10
```

### The Desired Enhancement Solution
I would like to be able to utilize **LoDash** and it's amazing functionality alongside my **Backbone.js** web app. To do that, it would require allowing the context to also be passed in as a parameter.

Without this enhancement, any **Backbone.js** app that is using additional **Backbone plugins** cannot utilize the power of **LoDash**.

**Comment by jdalton** [comment]
Lodash works with Backbone just fine. In fact we run Lodash against Backbone's unit tests.
You can use `_.bind`, `Function#bind` or arrow functions to bind without the need for the third param.

**Comment by benshewmake** [comment]
Please read over my original post again.

I am not saying that Lodash doesn't work with Backbone. Testing against Backbone doesn't necessarily mean that you are also testing against available plugins for Backbone. 

What I am trying to say is that the plugins developed for Backbone used Underscore functions passing in context as a function argument. Thus when I shim Lodash as a replacement for Underscore, the following example breaks across all plugins:

Example 1: With Underscore, this works fine:
```javascript
 _.each([{a: 1, b: 2},{a:3, b:4}], function(object, index) {
     context.sum += (object.a + object.b);
}, context);
```

Example 2: With Lodash as a replacement for Underscore, the equivalent:
```javascript
 _.each([{a: 1, b: 2},{a:3, b:4}], function(object, index) {
     context.sum += (object.a + object.b);
}.bind(this));
```

My point being that I cannot simply go into the source code of the Backbone plugins and change their implementation to use **Example 2** implementation when they have used **Example 1** implementation. So the **_problem_** is backwards compatibility breaks for _all_ Backbone plugins when trying to use Lodash instead of Underscore.

Because of that, I (as well as anyone using a Backbone plugin/extension) cannot use Lodash instead of Underscore.
