### ISSUE TITLE
isFunction is slow

### ISSUE THREAD

**Issue by ziflex** [lodash/lodash#2995]
Recently, I was doing benchmarking for our app and I noticed that _.isFunction is very slow comparatively to plain 'typeof' approach. I understand, that the function makes more accurate check than 'typeof', but performance hit is very huge.
Here is a benchmark:
https://jsperf.com/lodash-isfunction-vs-typeof

**Comment by jdalton** [comment]
Naw. Be careful of microbenchmarks. Our `isFunction` is heavier because it's working around environment bugs with normal `typeof`.
