### ISSUE TITLE
Getting a hold of the code for all unit tests

### ISSUE THREAD

**Issue by lohfu** [lodash/lodash#2997]
I'm playing around with making a lo-dash compatible module with the absolute smallest footprint for only using in the browser... as such i would like to make sure all functions pass the same tests that lo-dash passes. but i cant find the code for the units tests anywhere... how would i get a hold of them?

**Comment by jdalton** [comment]
Hi @lohfu!

You can checkout our [4.17.4 tag](https://github.com/lodash/lodash/tree/4.17.4).

**Comment by lohfu** [comment]
many thanks!
