### ISSUE TITLE
new math function (quantile)

### ISSUE THREAD

**Issue by ericrange** [lodash/lodash#2998]
hey what about a quantile function in the math section?

e.g. something like:
```js
const quantile = (array, percentile) => {
  array.sort((a, b) => a - b);
  const index = percentile / 100 * (array.length - 1);
  const floor = Math.floor(index);
  return floor === index ? array[index] :
    array[floor] + (array[floor + 1] - array[floor]) * (index - floor);
}
```

**Comment by jdalton** [comment]
Thanks @ericrange!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
