### ISSUE TITLE
Lodash vs Lodash FP, performance-wise

### ISSUE THREAD

**Issue by jeremejevs** [lodash/lodash#3003]
I've tried my best to find some sort of analysis or at least a benchmark, but got nothing.

I'm aware that `lodash/fp` merely wraps the existing functions, instead of re-implementing them, but it would be nice to have a definitive performance-based answer to **"Should I use the FP variant or the regular one in this case?"**. For example, is there some sort of a penalty, when running `fp.reduce(reducer, '')(arr)` instead of `_.reduce(arr, reducer, '')` many times in a loop? Would that put more load on GC, or consume more memory, or introduce other types of overhead?

I've tried benchmarking myself, but jsPerf isn't working properly, and I'm getting weird/inconsistent results on alternative services, and I just don't have time to make something custom, unfortunately.

**Comment by jdalton** [comment]
Hi @jeremejevs!

Though I've tried to minimize it, there will be some overhead to the `lodash/fp` variants. That said, most users of `lodash/fp` prioritize style over anything else (including performance).

**Comment by jeremejevs** [comment]
Hi @jdalton,

Thanks for the prompt reply! Yep, I understand that it's all about style, but I've profiled a client app utilizing `lodash/fp` the other day, and noticed that a lot of CPU time is spent on cleaning up throwaway curried functions, which made me think that maybe the performance penalty isn't small enough to be negligible. Anecdotal, but still.

**Comment by jdalton** [comment]
@jeremejevs The curried usage is really intended to store a reference to the partially curried functions and not partially curry them per invocation.

**Comment by jeremejevs** [comment]
@jdalton Okay, that's misuse. However, it would be helpful to have a number somewhere, saying that FP equivalents are ~1.??? times slower (or, if there are too many leading zeroes, saying that it's not a concern). Just to reassure people like me 🙂
