### ISSUE TITLE
lodash.com/docs filter does not filter

### ISSUE THREAD

**Issue by wheelerlaw** [lodash/lodash#3005]
- Problem: the filter field in the docs does not filter the functions based on what was typed. 
- Expected behavior: When I type in the name of a function, only functions that match (or are closely similar to) should show up.
- Steps to reproduce: 
1. Go to https://lodash.com/docs/
2. Type in `zipWidth`. Notice that many (many, many) other functions are present instead of ones that are similarly named to `zipWidth`.

**Comment by jdalton** [comment]
Hi @wheelerlaw!

It looks like a bug in Inferno. If I swap back to React it works as expected.
For future site bugs you can post them to our site repo at [lodash/lodash.com](https://github.com/lodash/lodash.com).

**Comment by jdalton** [comment]
Closed by https://github.com/lodash/lodash.com/commit/8ec0b70ca8ce49057750402c42bc2bdeec566b2d.
