### ISSUE TITLE
lodash/fp range

### ISSUE THREAD

**Issue by continuata** [lodash/lodash#3006]
I don't see how to use lodash/fp `range` method.
If I do the following 
```js
_.range(4)()
```
it still returns a curried function ... what am I doing wrong?

**Comment by jdalton** [comment]
You must provide a `start` and `end` param.

**Comment by continuata** [comment]
Hey thanks for the quick response.
There really should be some clear documentation on that then, just having it listed in a 2-arity list
doesn't really cut it.
Is anyone working on proper docs for lodash/fp? Would be happy to get involved.

**Comment by rafde** [comment]
@continuata would https://github.com/lodash/lodash/wiki/FP-Guide#fixed-arity ?

**Comment by dcmwong** [comment]
I find the lodash/fp documentation shocking.  Would like to start something if anyone has any suggestions

**Comment by continuata** [comment]
@dcmwong I've forked the lodash website and created a sub-folder called 'fp' in docs. I copied the latest version docs `4.17.4.html` for the normal lodash into there. We can just start editing that so that all the entries make sense for `lodash/fp`. Do you want me to add you to the project?
