### ISSUE TITLE
How to merge object without Prototype?

### ISSUE THREAD

**Issue by Elevista** [lodash/lodash#3009]
![merge](https://cloud.githubusercontent.com/assets/9513647/22967591/6f88755c-f3aa-11e6-8352-439a74a60d9d.PNG)

'_.merge' merges second argument object's prototype properties to first argument object's properties

**Comment by jdalton** [comment]
Hi @Elevista!

You could make the `foo` property non-enumerable.
See [Object.defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty).

**Comment by Elevista** [comment]
```javascript
var HasProto = function(){};
Object.defineProperties(HasProto.prototype,_.mapValues({
    foo:[1,2,3],
    foo2:{a:1}
}, function (v) {return {value: v, enumerable: false};})
_.merge({}, new HasProto());
```
=> {}

Works great. thank you!
