### ISSUE TITLE
TypeError: _.omitBy is not a function

### ISSUE THREAD

**Issue by lukepolo** [lodash/lodash#3011]
Lodash V : 14.17.4

`TypeError: _.omitBy is not a function`

Also 

`TypeError: _.pickBy is not a function`

happens in chrome and safari (newest versions)

let me know if you need more information

**Comment by jdalton** [comment]
Hi @lukepolo!

I can confirm both exist in Chrome/Safari. Make sure `_.VERSION` reports the correct one and that `_` is exposed properly. Also clearing your cache probably wouldn't hurt.
