### ISSUE TITLE
Split string at index and return parts in array

### ISSUE THREAD

**Issue by devboell** [lodash/lodash#3014]
Hi!

  Just wondering if this is something worth having

```
const splitAt = index => it => 
  [it.slice(0, index), it.slice(index)]

console.log(
  splitAt(1)('foo'), // ["f", "oo"]
  splitAt(2)([1, 2, 3, 4]) // [[1, 2], [3, 4]]
)
```
  
(found here: http://stackoverflow.com/questions/16441770/split-string-in-two-on-given-index-and-return-both-parts)

**Comment by jdalton** [comment]
Thanks @devboell!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by lonewarrior556** [comment]
Hey I just opened an issue related to this is related.  Provided some useful examples
https://github.com/lodash/lodash/issues/4734

I disagreed on the name and I think it should be expanded to multiple arguments.

**Comment by lonewarrior556** [comment]
@devboell currently the shortest non lodash implementation I can think of.
```js
const splitAt = (slicable, ...indices) => [0, ...indices].map((n, i, m) => slicable.slice(n, m[i+1]))

splitAt('foo', 1)
// ["f", "oo"]

splitAt([1,2,3,4], 2)
// [[1, 2], [3, 4]]

splitAt('fooBAr', 1,4)
//  ["f", "ooB", "Ar"]
```
