### ISSUE TITLE
Depending on lodash.x seems to load all 5mbs of this library

### ISSUE THREAD

**Issue by ORESoftware** [lodash/lodash#3017]
Hi all
Sorry if this is a dupe I am on mobile - 

I have this in package.json for a backend only project

```json
"dependencies":{
  "lodash.merge":"x.y.z"
}
```

When I run "$ du ." it seems clear that all of lodash gets installed.

Maybe another library that I depend on is using *all* of lodash. I will have to check.

In any case, my question is - if I only depend on lodash.x, it shouldn't load all of lodash, right?

**Comment by jdalton** [comment]
@ORESoftware It should be pretty easy to look up `node_modules/lodash.merge`. I think you get that this isn't our issue.

**Comment by ORESoftware** [comment]
Yeah it's a little confusing between lodash.merge and lodash/merge. Are
there docs that specify the diff? I think I know, but any docs would help
on this.

**Comment by jdalton** [comment]
@ORESoftware read up on minifiers like uglify-js and how to get gzip sizes.

**Comment by ORESoftware** [comment]
:) i wrote that this a backend project, not web, maestro :)
