### ISSUE TITLE
_.reduce doesn't work without supplying accumulator 

### ISSUE THREAD

**Issue by wheelerlaw** [lodash/lodash#3019]
The signature of `_.reduce` indicates that the accumulator is an optional argument. However, in TypeScript, not supplying the accumulator results in the compiler throwing an error:

```
Type '{}' is not assignable to type 'number'.
```

Here is an example: 
```
let numbers: number[] = [1, 2, 3];
let result = _.reduce(x, (accum, value, idx, coll) => value + accum);
```

As soon as I provide a value for the accumulator, the error goes away.

**Comment by jdalton** [comment]
Hi @wheelerlaw!

We don't maintain the typings for Lodash. That's done by a third-party.

**Comment by StreetStrider** [comment]
There must be a tag for that kind of tickets ☝️
