### ISSUE TITLE
Feature request: _.reargAt function wrapper

### ISSUE THREAD

**Issue by nlepage** [lodash/lodash#3021]
Hello,

I recently ran into a case where I had to implement a wrapper function in order to destructure its argument :
`const saveStatusValue = ({ value }) => saveStatus(value)`

I didn't find anything helpful in lodash, I would have liked a combination of `rearg` and `at` like this :
`_.reargAt(func, paths)`
with arguments :
`func (Function)`: The function to rearrange arguments for.
`[paths] (...(string|string[]))`: The property paths to use as arguments.

Which in my case would give :
`const saveStatusValue = _.reargAt(saveStatus, '0.value')`

Another example with several arguments :
`saveOrderStatusValue = (status, order) => saveOrderStatus(order.id, status.value)`
would give :
`saveOrderStatusValue = _.reargAt(saveOrderStatus, ['1.id', '0.value'])`

Hope this could be helpful to other people :smile:

**Comment by jdalton** [comment]
Hi @nlepage!

As we move in to v5 we're trying to rely more on ES6+ syntax. So in this case since what you're wanting can be accomplished through destructuring we'd defer to that.

**Comment by bsonntag** [comment]
@nlepage, what you want can be achieved with `compose` and `get` from `lodash/fp`:

```js
import { compose, get } from 'lodash/fp'

const saveStatusValue = compose(
  saveStatus,
  get('value')
)

**Comment by nlepage** [comment]
Thanks @bsonntag I hadn't thought of lodash/fp.

It made me realise it's still possible without lodash/fp, but less pretty :
```js
import { flow, partialRight, get } from 'lodash'

const saveStatusValue = flow(
  partialRight(get, 'value'),
  saveStatus
)
```

Just for the fun, in my original feature request there was also the idea of handling several arguments and reorganising them.
So here's a working implementation of my `reargAt` :
```js
import { flow, rest, partialRight, at, spread } from 'lodash'

const reargAt = (func, paths) => flow(
  rest(partialRight(at, paths)),
  spread(func)
)
```
allowing to do something like this :
```js
const saveOrderStatus = (orderId, statusValue) => { /* impl */ }
const saveOrderStatusValue = reargAt(saveOrderStatus, ['1.id', '0.value'])
saveOrderStatusValue(status, order)
```
