### ISSUE TITLE
Changes to _.reject() not listed in changelog

### ISSUE THREAD

**Issue by jkjustjoshing** [lodash/lodash#3022]
In v3.10.1, `_.reject()` takes up to 3 arguments https://lodash.com/docs/3.10.1#reject
In v4.0.0, `_.reject()` takes only 2 arguments https://lodash.com/docs/4.17.4#reject

This is a breaking change yet it is not mentioned in the changelog at https://github.com/lodash/lodash/wiki/Changelog, which it should be.

**Comment by jdalton** [comment]
Hi @jkjustjoshing!

It's covered by this note:
> Removed thisArg params from most methods because they were largely unused, complicated implementations, & can be tackled with _.bind, Function#bind, or arrow functions

**Comment by jkjustjoshing** [comment]
Thanks for the quick response! That makes ctrl+f on the changelog very ineffective, which seems to be quite an issue. Thanks anyway!

**Comment by jdalton** [comment]
For help upgrading you should check out [lodash-migrate](https://www.npmjs.com/package/lodash-migrate), [lodash-codemods](https://www.npmjs.com/package/lodash-codemods), &
[eslint-plugin-lodash](https://www.npmjs.com/package/eslint-plugin-lodash).
