### ISSUE TITLE
Add variadic unionAll to FP

### ISSUE THREAD

**Issue by Treora** [lodash/lodash#3025]
The FP versions of `union`, `unionBy` and `unionWith` accept only two arrays, unlike the 'normal' lodash versions. Adding corresponding functions `unionAll`, `unionAllBy` and `unionAllWith` would be nice.

**Comment by jdalton** [comment]
Thanks @Treora!

I agree! We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
