### ISSUE TITLE
U+0131 (dotless little i) problem when using toLower, lowerCase, capitalize

### ISSUE THREAD

**Issue by barisusanmaz** [lodash/lodash#3026]
I would like to convert "AYNI" string into "Aynı" but capitalize converts it into "Ayni". I tried other methods and had the same result. Can I achieve this? Thanks

**Comment by jdalton** [comment]
Hi @b3nj4m!

Our case methods will deburr words in v4 (that will change in v5). The other methods like `toLower` are deferring to `String#toLowerCase` so you'll probably have to come up with a custom solution.
