### ISSUE TITLE
Should toNumber handle commas ?

### ISSUE THREAD

**Issue by mjarraya** [lodash/lodash#3027]
Hello,

The toNumber (valid for toInteger as well) converts a valid number composed string into a number. 

`_.toNumber('13.37')` will return 13.37 as a number
Why doesn't `_.toNumber('4,2')` return 4.2 as a number ?

If it is a wanted behaviour then please ignore this question, but if it is not it could avoid the use of `.replace(',', '.')`

**Comment by jdalton** [comment]
Hi @mjarraya!

Our `toNumber` is a type coercion method.
I don't think we should unless JS naturally handles them that way.
