### ISSUE TITLE
Function proposal: _.exists(value)

### ISSUE THREAD

**Issue by StevePotter** [lodash/lodash#3028]
Hello, often I want to check whether a variable is set to a value that could include true or 0.  So a truthy test won't work.  Specifically, I want to be sure the value isn't null, isn't undefined, and isn't nan.  Like so (using vanilla js):
```
function exists(value) {
   return value !== undefined && value !== null && !isNaN(value) 
}
```
I'd be happy to make the PR for this.  Is that better than using Issues?

**Comment by jdalton** [comment]
Hi @StevePotter!

I think instead of this we'd like an `and` or `or` method to combine the existing `isNil` and `isNaN` methods.

**Comment by StevePotter** [comment]
@jdalton that's not a problem at all.  I'd just switch it to:
```
function exists(value) {
   return !_. isNil(value) && !_.isNaN(value) 
}
```

Is that something you'd consider?  If so, I'll send over the PR.

**Comment by jdalton** [comment]
I mean favoring a composition method like an `_.and` or `_.or` method to enable folks to compose their own `exists` variant.

**Comment by StevePotter** [comment]
Thanks @jdalton but I'd rather see that function in the library directly.  I have a few others I would like to see in it.  Should I submit those separately?
