### ISSUE TITLE
Could we reduce lodash size?

### ISSUE THREAD

**Issue by jakwuh** [lodash/lodash#3030]
Hi!

I see lodash es6 build is on the go, this is amazing, thank you @jdalton & contribs a lot!

The problem I've recently faced with was the following: I never use Buffers / Streams (obviously) & ArrayViews / Symbols / Maps / Sets (because of a browser support) on the client. Thus I don't need any related code to be bundled in my final client build. As far as there are no more libs like lodash, our current solution was to reimplement most of the lodash methods and port the tests, which resulted into reducing the final bundle size by 3 times.

I wonder if we can do something similar with lodash? The most obvious way to do this (as I see it) is to cover code with guards:
```
if (IS_SERVER_BUILD) {
 // code which work with buffers
}
```
then strip it out with `uglify` and ship 2 builds: `lodash-server` & `lodash-client`.

Actually, I'm not sure this is important to many lodash users, but still think it worth asking.

**Comment by jdalton** [comment]
Hi @jakwuh!

You're looking for [lodash-webpack-plugin](https://www.npmjs.com/package/lodash-webpack-plugin) which creates smaller bundles by disabling many features by default (allowing you to opt-in to feature sets).
