### ISSUE TITLE
Maybe capitalize method should return title-cased string

### ISSUE THREAD

**Issue by cope** [lodash/lodash#3032]
Based on [this tool](https://convertcase.net/), it seems that [capitalize](https://github.com/lodash/lodash/blob/master/capitalize.js) should return a [title-cased](https://en.wikipedia.org/wiki/Capitalization#Title_case) string, and not a [sentence-cased one](https://en.wikipedia.org/wiki/Capitalization#Sentence_case), as it does now?

**Comment by jdalton** [comment]
Hi @cope!

Our capitalize method is no-frills method and is not aware of sentence or words.
