### ISSUE TITLE
Cannot Build with aot.

### ISSUE THREAD

**Issue by suraj22kar** [lodash/lodash#3035]
Facing following errors-

@types/lodash/index.d.ts:244:13: Duplicate identifier '_'.
@types/lodash/index.d.ts:17112:19: Cannot find name 'Many'.
@types/lodash/index.d.ts:244:16: Cannot find namespace '_'.
@types/lodash/index.d.ts:17926:39: Cannot find name 'TemplateSettin
gs'.

My versions of libraries are = 
os: linux x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/compiler-cli: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/platform-server: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0

**Comment by jdalton** [comment]
Hi @suraj22kar!

We don't maintain the typings.
