### ISSUE TITLE
Cannot build angular2 app with lodash

### ISSUE THREAD

**Issue by suraj22kar** [lodash/lodash#3036]
got these errors while build-

@types/lodash/index.d.ts:18909:40: Cannot find name 'Many'
@types/lodash/index.d.ts:15856:21: Cannot find namespace '_'.
@types/lodash/index.d.ts:11444:21: ']' expected.

My dependencies versions=

os: linux x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/compiler-cli: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/platform-server: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0

**Comment by jdalton** [comment]
Dup of #3035.
