### ISSUE TITLE
.camelCase() issue (?) when string contains numbers

### ISSUE THREAD

**Issue by dwiyatci** [lodash/lodash#3037]
Hi, :-)

When:
1. `_.camelCase('i18n-locales')`
2. ` _.camelCase('r2d2Voice')`
3. `_.camelCase('c8yHello-widget')`

Expected:
1. `i18nLocales`
2. `r2d2Voice`
3. `c8yHelloWidget`

Actual:
1. `i18NLocales`
2. `r2D2Voice`
3. `c8YHelloWidget`

Is this behaviour expected somehow?

**Comment by jdalton** [comment]
Hi @dwiyatci!

Yes, this is the intended behavior. You can see this by
```js
_.words('r2d2Voice')
// => ["r", "2", "d", "2", "Voice"]
```

Numbers are considered their own word.
