### ISSUE TITLE
_.get Documentation Update Proposal

### ISSUE THREAD

**Issue by jdconner** [lodash/lodash#3038]
What
-
The documentation for the `_.get` function does not fully portray its functionality.

Why
-
I've had to explain and show 4 people today that the `_.get` function works with arrays by pulling up the source code and giving examples in the console. This is a tell-tale sign of poor documentation for the function. 

Proposal
-
We should update the documentation for the `_.get` function to something along the lines of:
```js
 import baseGet from './.internal/baseGet.js'

/**
 * Gets the value at `path` of `object`. If the resolved value is
 * `undefined`, the `defaultValue` is returned in its place.
 *
 * @since 3.7.0
 * @category Object
 * @param {Object|Array} collection The collection to query.
 * @param {Array|string} path The path of the property to get.
 * @param {*} [defaultValue] The value returned for `undefined` resolved values.
 * @returns {*} Returns the resolved value.
 * @see has, hasIn, set, unset
 * @example
 * const array = [{ 'b': { 'c': 3 } }]
 * const object = { 'a': array }
 *
 * get(object, 'a[0].b.c')
 * // => 3
 *
 * get(object, ['a', '0', 'b', 'c'])
 * // => 3
 *
 * get(object, 'a.b.c', 'default')
 * // => 'default'
 *
 * get(array, 0)
 * // => { 'b': { 'c': 3 } }
 *
 * get(array, '[0].b')
 * // => { 'c': 3 }
 *
 * get(array, 1)
 * // => undefined
 */
function get(object, path, defaultValue) {
  const result = object == null ? undefined : baseGet(object, path)
  return result === undefined ? defaultValue : result
}

export default get
```
Example Explanations
-
The examples within the new documentation will show that arrays can:
- return resolved values when passed an index
- return resolved values when passed a path
- return `undefined` when passed an index that is out of bounds instead of throwing a runtime error

P.S.
-
This technically doesn't add new functionality since it is already implemented but does provide a feature to those who strictly adhere to documentation over reading source code. As documented, this codebase requires issues for features so here it is.

I am willing to update tests and the documentation if this proposal is accepted.

**Comment by jdalton** [comment]
Hi @jdconner!

Thanks for bringing this up. The next time the question comes up simple point them to the documentation. It's had an array as a `path` example since v3.

**Comment by jdconner** [comment]
Hey @jdalton

It's not that there isn't an example for an array as path, it's that the documentation says the first parameter is only able to take in objects when in reality it can take in arrays as well.

So at minimum I would [this line](https://github.com/lodash/lodash/blob/master/get.js#L9):
```js
* @param {Object} object The collection to query.
```
to
```js
* @param {Object|Array} collection The collection to query.
```

**Comment by jdalton** [comment]
@jdconner Ah, thanks for clarifying. This is an "Objects" method so it's designated to accept objects. Arrays are objects so that will do. Dates, regexes, maps, sets, weakmaps, are objects too but not worth calling out individually in the param specification.

**Comment by jdconner** [comment]
@jdalton Gotcha. Thanks for the consideration!
