### ISSUE TITLE
Undocumented limitations on _.template delimeter RegExps

### ISSUE THREAD

**Issue by cspotcode** [lodash/lodash#3039]
I tried doing the following with _.template, using a multiline RegExp as the `interpolate` delimeter.

    const customJsFn = template(fs.readFileSync(input, 'utf8'), {
        escape: /$( )^/,
        evaluate: /$( )^/,
        interpolate: /^\s*\/\*\*===(.*?)===\*\*\/$/gm
    });

However, since LoDash recompiles all 3 delimeters into a single RegExp, the `m` flag is lost and the RegExp never matches.  I think some documentation should be added to explain this limitation as well as any others I might not be aware of.

**Comment by jdalton** [comment]
Hi @cspotcode!

I think this is edge case enough (outside the common use case) to avoid a doc note.
In v5 we'll be switching to ES6 tagged template strings.
