### ISSUE TITLE
Add _.first

### ISSUE THREAD

**Issue by jamesob** [lodash/lodash#3040]
I'm searching for a lodash function that'll return me the first element in a collection matching some predicate. This would be equivalent to something like 
```js
def first(coll, predicate) {
  var got = _.filter(coll, predicate);
  return got ? got[0] : null;
}
```

Happy to provide an implementation if this is something that the lodash maintainers are interested in offering.

**Comment by erinknight242** [comment]
@jamesob isn't that what _.find already does? https://lodash.com/docs/4.17.4#find

**Comment by jamesob** [comment]
D'oh! You're totally right. Thanks.
