### ISSUE TITLE
startCase incorrectly handles plural acronyms (e.g. IVAs & CCJs)

### ISSUE THREAD

**Issue by penfold** [lodash/lodash#3041]
Using v4.17.3

var output = _.startCase('IVAs');

Output gives 'IV As' instead of 'IVAs' - i.e. no change.

**Comment by jdalton** [comment]
Hi @penfold!

The casing methods work with compound words. Based on our rules IVAs is seen as a compound of `IV` and `As`.

**Comment by penfold** [comment]
So your rules have an issue? Can you explain why the rule is such.

**Comment by jdalton** [comment]
Naw, not an issue.
