### ISSUE TITLE
Specific lodash chain freezes IE11

### ISSUE THREAD

**Issue by andreasgruenh** [lodash/lodash#3042]
Hello guys,

just encountered a weird bug which can be reproduced with the following line:

`_.chain([1]).map(function(x) { return x + 2; }).get('1') >= 1`

Enter this line in the console in IE 11 (for example on the lodash homepage) and the browser window will freeze.

**Comment by jdalton** [comment]
Oh super interesting. The freeze happens on the comparison bit `>= 1`.

**Comment by jdalton** [comment]
It can be simplified to `_() > 1`

**Comment by jdalton** [comment]
It looks like it goes back to at least v2. It doesn't seem to matter if there's a `toNumber` or `toString` method set on the comparison. Since this is a far reaching bug we'll probably not address it. I'll still try to root cause it and report it to Microsoft.

**Comment by jdalton** [comment]
Ok I reduced it:
```js
var o = {};
o.valueOf = function() {};
o >= 1 // freeze
```

**Comment by andreasgruenh** [comment]
Nice work, found it very interesting as well.
