### ISSUE TITLE
`cloneDeep()` does not preserve ES5 property attributes

### ISSUE THREAD

**Issue by mbrowne** [lodash/lodash#3043]
Consider the following example:

	var o = {};
	Object.defineProperty(o, 'foo', {enumerable:true, writable:false, value:'f'});
	var o2 = _.clone(o);

	console.log(Object.getOwnPropertyDescriptor(o2, 'foo'));

The property descriptor on the copied object specifies the property as `writable` even though the original property wasn't writable.

I also noticed that `clone()` and `cloneDeep()` only copy enumerable properties, but that's mentioned in the documentation so I assume it's deliberate (might be nice to add an option to copy them if desired).

**Comment by jdalton** [comment]
Hi @mbrowne!

This is by design. Preserving attribute descriptors is super expensive. It's part of the tradeoffs we make for being a general purpose util.

**Comment by mbrowne** [comment]
Thanks for the quick clarification! The docs could be clearer on this, but I just looked again and it does say that properties "are cloned as plain objects", which I'm guessing might have been meant to indicate that.
