### ISSUE TITLE
cancel a _.delay

### ISSUE THREAD

**Issue by andreineculau** [lodash/lodash#3044]
I'm wondering if there was any thought into adding the same `.cancel` to `_.delay`, a functionality that exists in `_.throttle` for example.

**Comment by jdalton** [comment]
Hi @andersonaguiar!

The `_.delay` and `_.defer` methods return a timer ID that you can use with `clearTimeout`.

**Comment by andreineculau** [comment]
I know, I know, but I was advocating for consistency along lodash functionality.

PS: wrong mention
