### ISSUE TITLE
Feature request: _.indexOfDeep

### ISSUE THREAD

**Issue by Trung0246** [lodash/lodash#3046]
Find index of a value in deeply nested array, return array of index to point out specifically where it is.

    function indexOfDeep(array, value) {
      var result;
      array.some(function iter(path) {
        return function (a, i) {
          if (a === value) {
            result = path.concat(i);
            return true;
          };
          return Array.isArray(a) && a.some(iter(path.concat(i)));
        }
      }([]));
      return result;
    }

Example: 

    indexOfDeep([0,1,2,[3,4,[6,7,8],9,10],11,12,[13,[14,15],16,17],18,19], 15);
    //=> [6, 1, 1]
    
    indexOfDeep(['a', 1, ['b', 2, ['c', 3, 'd'], 4, ['e', 5], 'f'], 6, 'g', 7], 4);
    //=> [2, 3]

    indexOfDeep(['h', 'e', ['l', 'l', 'o'], ['w', 'o', ['r'], ['l']], 'd'], '!!!');
    //=> undefined (because '!!!' is not exist in array)

**Comment by jdalton** [comment]
Hi @Trung0246!

This looks a bit to specialized for Lodash. It's probably better as a mixin.
