### ISSUE TITLE
trimStart brokes on slashes

### ISSUE THREAD

**Issue by fronteed** [lodash/lodash#3048]
Here's the example:
https://runkit.com/58c1cdd62329e3001453e3e9/58c1cdd62329e3001453e3ea/branches/master

`_.trimStart('/profile/address/shipping', '/profile/address')` produces `hipping`

Excepted result: `/shipping`.

**Comment by jdalton** [comment]
Hi @fronteed!

The "chars" param is a string of chars to trim not the substring to trim.
