### ISSUE TITLE
Zero length (root) object property path for get, pick and others

### ISSUE THREAD

**Issue by futpib** [lodash/lodash#3049]
It seems natural for the empty path (like `[]` or `''`) to mean the target object itself instead of `undefined`.

```js
const o = {
  a: {
    b: {
      c: 'bingo',
    }
  }
};

t.is(_.get(o, ['a', 'b', 'c']), o.a.b.c);
t.is(_.get(o, ['a', 'b']), o.a.b);
t.is(_.get(o, ['a']), o.a);
t.is(_.get(o, []), o); // actually undefined
```

**Comment by jdalton** [comment]
Hi @futpib!

This has been brought up before. I don't think it makes sense to return the source when you're wanting to select properties from it. In the case of an empty path your specifying selecting no properties from it so the result is `undefined`. In the transaction of "give me the property on the object" it doesn't make sense to ever say "Naw, here's the object", to which I'd say "but I didn't want the object, I wanted properties off the object".

**Comment by StreetStrider** [comment]
Root path is a zero element for object paths, like zero for numbers or `[]` for `Array`. I'm pretty sure not having it will lead to workarounds for some devs.

**Comment by futpib** [comment]
@jdalton Sorry, I tried to find an existing issue and could not.

> In the transaction of "give me the property of the object" it doesn't make sense to ever say "Naw, here's the object", to which I'd say "but I didn't want the object, I wanted a property of the object".

Only in the most trivial cases I imagine it would never make sense. "give me the property of the object" is what `get` does for paths of length 1, otherwise it's "give me the property of the property ...".

Of course it does not make sense to write `_.get(o, [])`, you could just use `o` right away, but imagine a function that uses `_.get` and accepts a path as an argument. And maybe you have an algorithm that involves reducing initials of a path (like repeatedly taking `_.initial` of a path) and calling that function. Then, with current `_.get`, you would have to have a special case for the "root" path.
