### ISSUE TITLE
_.reduce works incorrectly without accumulator

### ISSUE THREAD

**Issue by dizel3d** [lodash/lodash#3054]
_.reduce works incorrectly without accumulator
```
_.reduce({a: 1, b: 2}, (res, value, key) => value === 1 ? key : res)
```
![image](https://cloud.githubusercontent.com/assets/593571/23892837/4f36a770-08ad-11e7-8263-2400f50724dd.png)

**Comment by jdalton** [comment]
Hi @dizel3d!

This is the correct behavior and based on [Array#reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce).
