### ISSUE TITLE
Need documentation clarification on replacing value of .cache property of memoized functions

### ISSUE THREAD

**Issue by Ginden** [lodash/lodash#3055]
Currently we use code like:
```javascript
const stripTagsMemoized = _.memoize(require('striptags'));
stripTagsMemoized.cache = new WeakMap;
```

It works right now ([because of this line](https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L10561)), but documentation doesn't state if it's intended to work like this or is it relying on implementation detail.

**Comment by jdalton** [comment]
The docs for [_.memoize](https://lodash.com/docs#memoize) call out customizing the cache.
We have unit tests for this too. I don't think any more detail needs to be added to it.
