### ISSUE TITLE
lowerCase replaces åäö with aao

### ISSUE THREAD

**Issue by pinn3** [lodash/lodash#3056]
This seems to be a consistent issue with all casing functions using `createCompounder.js`.
Example:
```js
_.lowerCase('räven-åt-i-köket')
// returns 'raven at i koket'
```

However, when replicating the `lowerCase` function it returns the expected string:
```js
const reApos = /['\u2019]/g
const lc = (str) => _.reduce(
  _.words(_.toString(str).replace(reApos, '')),
  (result, word, index) => result + (index ? ' ' : '') + word.toLowerCase(),
  ''
)

lc('räven-åt-i-köket')
// returns 'räven åt i köket'

**Comment by jdalton** [comment]
Hi @pinn3!

This is by design for "case" methods. In v4 they deburr characters automatically. In v5 we'll not deburr them to allow for special characters to remain.

**Comment by pinn3** [comment]
Oh okay!
Where exactly is the deburring done? I've been looking for where it happens for about 30 min and still curious.

**Comment by jdalton** [comment]
It's done [here](https://github.com/lodash/lodash/blob/4.17.4-npm/_createCompounder.js#L20).
