### ISSUE TITLE
mutators should throw if object frozen

### ISSUE THREAD

**Issue by dwelle** [lodash/lodash#3057]
IMO `_.assign` and related methods should throw if target is frozen (which is the behavior of e.g. `Object.assign` or plain assignments). Looked at source and can't find any reason why it doesn't. Seems to be the case for pretty much every mutating lodash method.

```
(function () {
    "use strict";
    const o = Object.freeze({});
    _.assign(o, { val: 42 })
})()
```

Thoughts?

**Comment by jdalton** [comment]
Hi @dwelle!

It could be that Lodash's methods are not in strict mode so that it is a silent noop. The `lodash-es` package should transpile to strict mode which would throw for you.

**Comment by dwelle** [comment]
Begs the question why it isn't set on by default. Doesn't strict mode have perf benefits, alongside catching potential bugs such as the extending-frozen-objects above?

**Comment by jdalton** [comment]
>Begs the question why it isn't set on by default.

I tried it on by default and it broke folks in the Node ecosystem at the time.

> Doesn't strict mode have perf benefits

Not really. It was actually a tiny bit slower initially.
