### ISSUE TITLE
Feature request: `exists`

### ISSUE THREAD

**Issue by fiznool** [lodash/lodash#306]
I often find myself checking for the existance of a variable - i.e. that the variable is neither undefined or null. This often means code such as:

``` js
if(!(_.isUndefined(obj) || _.isNull(obj))) {
  // do something
}
```

A nice shorthand for this could be:

``` js
if(_.exists(obj)) {
  // do something
}
```

Kinda like the existential operator from coffeescript, for those of us who don't use coffeescript.

**Comment by PhiLhoSoft** [comment]
The `!=` solution cannot be used (concisely) in `omit`, for example.
Something like `_.omit(obj, _.exists)` would be nice and elegant to remove all properties set to `undefined` or `null`.

Or, more generic, we would need a function to combine functions?
`_.omit(obj, _.or(_.isUndefined, _.isNull))`
`_.filter(obj, _.and(_.isArray, _.isObject))`

**Comment by jridgewell** [comment]
> Or, more generic, we would need a function to combine functions?

https://github.com/lodash/lodash/issues/1072
