### ISSUE TITLE
group by null value coverts to "null" as a string

### ISSUE THREAD

**Issue by remohy1** [lodash/lodash#3060]
lets say you have an array:

var x = [{id: null, value: "cat"}, { id: null, value: "dog"}]

now if you tried to group by the id which is null, the map function will convert the null to "null". I am trying to check for null keys to replace it with "No Data", but I do not want to write specific check for "null" if it is not original in the data. Is there a fix for this? Am I doing something wrong? 

It works fine if I do not have a map function, but with the map like below, it will replace the null with "null"

_.chain(x).groupBy("id").map((value, key) => {return { key: key, value: value} }).value()

**Comment by jdalton** [comment]
Hi @remohy1!

You can always do falsey check or nullish check:
```js
value == null ? 'No Data' : value
```

**Comment by remohy1** [comment]
This will not apply if lodash is changing my null value to a string that = "null"

**Comment by remohy1** [comment]
Please, re-open. Here is an example: https://plnkr.co/edit/V68xX5WgbjxGu7oQRhrX

**Comment by jdalton** [comment]
Adjust the ternary to taste. Lodash issues aren't for general JS support.
You might check out our [gitter chat](https://gitter.im/lodash/lodash) for that.

**Comment by remohy1** [comment]
Solution was _.chain(x).groupBy('id', (value, key) => { return { key:key,  value: value} }).value()

No need to use map function. I am not sure why map function acts like this, but the above worked for me.
