### ISSUE TITLE
Combine two objects based on the first one

### ISSUE THREAD

**Issue by FlappyHeart** [lodash/lodash#3061]
Hi there,

Thanks for your works with this lib. What I need is combining two objects based on the first one, but I cannot found a method in the document after hours of reading. 

var foo = {a: 0, b: 0};

var bar = {a:123, b: 234, c: 345);

var result = _.someMethod(foo, bar);

console.log(result);
// {a: 123, b: 234} without c

Any help will be great appreciated!

**Comment by Alexsey** [comment]
You could do just ```_.pick(bar, _.keys(foo))```

**Comment by FlappyHeart** [comment]
@Alexsey  Thanks a lot! It works !
