### ISSUE TITLE
Support ES6 Map/Set in _.each?

### ISSUE THREAD

**Issue by rambo-panda** [lodash/lodash#3062]
`_.each` method cannot be used on `Map` or `Set` now。

This is my solution。 **Sorry to modify your code**

```javascript
    // in your createBaseEach
    if(!isArrayLike(collection)){
	 if(/^\[object (Map|Set)\]$/.test(toString(collection)){
	    return collection.forEach(iteratee);
	 }
         return eachFunc(collection, iteratee);
    }
```

**Comment by jdalton** [comment]
Hi @rambo-panda!

I've sided on punting support for map/set and instead recommend folks use spread:
```js
_.each([...map], iteratee)
```

**Comment by rambo-panda** [comment]
@jdalton Thanks - sorry I missed those. Cheers

**Comment by rambo-panda** [comment]
@jdalton In fact, I still need to determine the type of parameters

Not every parameter has `Symbol.iterator`

```javascript 
> var t = {a:1}
undefined
> [...t]
TypeError: t[Symbol.iterator] is not a function
```

**Comment by bfred-it** [comment]
You don't need the spread operator on regular objects:

```js
_.each({a:1}, iteratee)
```
