### ISSUE TITLE
_.set updates old references

### ISSUE THREAD

**Issue by thatisuday** [lodash/lodash#3064]
Look at following example
```
var a = {x:1};
var b = a;
_.set(b, 'y', 2);
```

Now `b` should be
```
Object {x: 1, y: 2}
```

But then why a is 
```
Object {x: 1, y: 2}
```

Why it's not like 
```
a = 1;
b = a;
a = 2;
b == 1 // true
```

**Comment by jdalton** [comment]
Hi @thatisuday!

The `_.set` method mutates the input. Since `a` and `b` both reference the same object when you modify one, you modify the other. If you want immutable you can use `lodash/fp/set`.
