### ISSUE TITLE
.sort() on chaining crashes on IE

### ISSUE THREAD

**Issue by amiramw** [lodash/lodash#3065]
The following chaining expression works on chrome and crashes on IE:
```
var entitySets = [
	{
		name: "B",
		key: "b"
	},
	{
		name: "A",
		key: "a"
	},
	{
		name: "C",
		key: "c"
	}
];
_(entitySets)
.filter(function (oEntity) {
	return oEntity.key === "a";
})
.sort(["key"])
```

The error I get in IE is:
```
SCRIPT5014: Array.prototype.sort: argument is not a JavaScript object
lodash.js (16908,21)
```

The problem reproduces in lodash-amd 4.17.4.

**Comment by jdalton** [comment]
See [Array#sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).
