### ISSUE TITLE
More complete JSDoc for shorthand parameters

### ISSUE THREAD

**Issue by d4kris** [lodash/lodash#3066]
I really like that most functions can take a shorthand version of the iteratee or predicate parameter. But the JSDoc for that parameter only states {Function} with the risk of confusing both developers and IDEs - although the excellent examples should be enough for humans I get warnings from IDEA about wrong parameter types. 

Happy to create a PR if wanted!

**Comment by jdalton** [comment]
Hi @d4kris!

We used to have a more explicit JSDoc param signature but it junked up the docs. I like focusing on the primary case here and leaving the rest as doc examples. Also in v5 I'm moving shorthands to a plugin so they'll be less to highlight in the docs.

**Comment by d4kris** [comment]
Fair enough, thanks for clarifying!
