### ISSUE TITLE
lodash.isequal package too big

### ISSUE THREAD

**Issue by SiqiTian-minted** [lodash/lodash#3067]
Hi, I found in my webpack output that the `lodash.isequal` package is as big as a full build:
```
   [6] ./~/lodash.isequal/index.js 49.6 kB {0} [built]
```
Is this normal? My local has `"lodash.isequal": "4.5.0"`.

**Comment by SiqiTian-minted** [comment]
Originated from https://github.com/bringking/react-web-animation/issues/48

**Comment by jdalton** [comment]
If you minify and gzip size is like 5kb or so. You can use Lodash + Lodash-wepback-plugin to get it down to 1.5kb or so

**Comment by SiqiTian-minted** [comment]
Sure, but should the un-minified-&-un-gzipped `isEqual` function itself be 49 kb?

**Comment by jdalton** [comment]
Unminified ungzipped size doesn't really matter. It's got inline documentation and comments and stuff. It has no impact on your production size.
