### ISSUE TITLE
_.template erroneously escapes HTML when called multiple times in quick succession

### ISSUE THREAD

**Issue by singularityfx** [lodash/lodash#3068]
When _.template function is called multiple times in quick succession it may fail to correctly process the argument string. 

Here is a [JS Fiddle](https://jsfiddle.net/cLfdog0u/3/) that illustrates the problem.

**Expected result:**
Text "SOME TEXT" in bold red Helvetica is displayed.
The HTML shall look like this:
`<div class="target"><span class="blah1 blah2 blah3">SOME TEXT</span></div>`

**Actual result:**
Text `<span class="blah1 blah2 blah3">SOME TEXT</span>` is displayed.
The HTML looks like this:
`<div class="target">&lt;span class="blah1 blah2 blah3"&gt;SOME TEXT&lt;/span&gt;</div>`

If you decrease MAX_CYCLES to 0 you will see the expected output.

Note that MAX_CYCLES == 1000000 is a much exaggerated value. This issue was detected in an enterprise project where number of successive invocations required to reproduce it was around 2-digit number (on a developer's machine). I was able to reproduce it on JS Fiddle with a number of cycles around 10000.

**Comment by jdalton** [comment]
I can't reproduce in Chrome 56. This sounds like a JIT bug. You should file it with the relevant browser vendor (which browser and version is it). You can avoid the issue until they fix their JIT bug by compiling the templates using [lodash-cli](https://lodash.com/custom-builds).

**Comment by jdalton** [comment]
I'm going to guess Safari.

**Comment by singularityfx** [comment]
It's Chrome 56.0.2924.87 (64-bit).

**Comment by jdalton** [comment]
Ah you're right. So you'll want to file it with https://crbug.com.

**Comment by bmeurer** [comment]
Does indeed look like a JIT bug in Chrome M56. Note that Chrome M57 is stable now and Chrome M56 is no longer supported, so please upgrade to a more recent version.

cc @natorion

**Comment by singularityfx** [comment]
Yep, I can confirm that it works well in Chrome 57. Thanks a lot for your quick feedback! And you great library! :)
