### ISSUE TITLE
v4.14.2 has broken _.set behavior

### ISSUE THREAD

**Issue by fogine** [lodash/lodash#3069]
```javascript
var data = {};
_.set(data, `.[test]`, 'value');
console.log(data);
```

Output prior `v4.14.2` (I used `v4.13.1`):  
```javascript
{ test: 'value' }
```

Output since `v4.14.2`:
```javascript
{ '': {test: 'value'} }
```

The dot in the path makes the difference. The https://github.com/lodash/lodash/commit/a4947139a6ca791c9758a5a52afce2b90e2f0e22 probably brakes the behavior.

**Comment by jdalton** [comment]
The result of v4.14.2 is preferred. It looks like you're in edge case territory. You may do better to be explicit about your paths by passing an array.
