### ISSUE TITLE
Docs: missing methods in the Seq (_) docs

### ISSUE THREAD

**Issue by ganimomer** [lodash/lodash#3070]
Hi, 
While fixing [this issue in eslint-plugin-lodash](https://github.com/wix/eslint-plugin-lodash/issues/143), I noticed that the latest v4 docs for `_(value)` don't mention the methods `sortedUniq` and `sortedUniqBy` on the list of chainable methods (or on the list on methods that are *not* chainable).

**Comment by jdalton** [comment]
Thanks for the heads up! Patched https://github.com/lodash/lodash.com/commit/73fe7d3d0f4f6b1d825aafa980841053270619d7.
