### ISSUE TITLE
(Possibly) undocumented breaking change in _.findKey

### ISSUE THREAD

**Issue by boeserwolf** [lodash/lodash#3071]
I've had a hard time to track down an error in a huge web application after upgrading from version 3.x to 4.17.4.

In version 3.x this worked:
`_.findKey(myObj, 'name', name);`

With version 4.17.4 I had to change this to:
`_.findKey(myObj, { 'name': name });`

Please correct me if I'm missing something. Otherwise it would be great if you could add this to your change log.

Thanks!

**Comment by jdalton** [comment]
Hi @boeserwolf!

It's covered in the [changelog](https://github.com/lodash/lodash/wiki/Changelog) for v4 as the change item:
```
Changed _.matchesProperty shorthand to an array of [path, srcValue]
```

**Comment by boeserwolf** [comment]
Hi @jdalton, thanks for your quick response! 

As a suggestion, it would be great if the affected lodash functions were mentioned by their name within the changelog. I checked for every function I could find in the changelog, but were not aware about _.matchesProperty affecting _.findKey.

**Comment by jdalton** [comment]
It's the `_.matchesProperty` shorthand. It affects many functions. Listing all of them would unnecessarily clutter up the changelog. You might try using something like [lodash-migrate](https://www.npmjs.com/package/lodash-migrate), [lodash-codemods](https://www.npmjs.com/package/lodash-codemods), &
[eslint-plugin-lodash](https://www.npmjs.com/package/eslint-plugin-lodash) to help migrate.

**Comment by boeserwolf** [comment]
lodash-migrate is exactly what I was looking for. Thank a lot @jdalton.
