### ISSUE TITLE
is it somehow to use it less files?

### ISSUE THREAD

**Issue by patrikx3** [lodash/lodash#3072]
right now lodash is uses 1052 files.
isn't it a little too much?

it is like windows vs linux? (i copy 200k files in windows it is 30 seconds in linux it is 3 seconds )

lodash is becoming like windows. 

**sometimes 5 lines is 1 file. often.**

just asking. not criticising.

**Comment by jdalton** [comment]
Hi @patrikx3!

The Lodash v5 package will use less files and be considerably less on disk.

**Comment by patrikx3** [comment]
thanks very much! PRO!
