### ISSUE TITLE
Default the _.debounce options

### ISSUE THREAD

**Issue by Bertuzb** [lodash/lodash#3073]
So from 4.0.0 onwards, the third argument of `_.debounce(func, [wait=0], [options={}])` no longer accepts a boolean value.

I have this function many times in my code, how can I extend/edit it easily so it uses the following options by default:

```
_.debounce(func, wait, {
    leading: true
});
```

While also being able to override it? So calling just `_.debounce(func, wait)` should use the options above, but passing the third parameter as `{leading: false}` should be possible as well.

Thx in advance

**Comment by jdalton** [comment]
Hi @Bertuzb!

You can partially apply the arguments with either `_.partial` or `_.partialRight`:
```js
var debounce = _.partial(_.debounce, _, _, {
    leading: true
});
// or
var debounce = _.partialRight(_.debounce, {
    leading: true
});
```

**Comment by Bertuzb** [comment]
Alright, however could you explain this fiddle related to that:

https://jsfiddle.net/6924p3y2/1/

When using `_.partial(greet, _, 'fred');`, the second function argument (`'fred'`) does not seem to be overwriteable. However it is overwriteable when using `_.partialRight`

**Comment by jdalton** [comment]
For how-tos and what-fors related questions you should check out our [gitter chat](https://gitter.im/lodash/lodash).
