### ISSUE TITLE
forEach seems to be much slower than native for

### ISSUE THREAD

**Issue by fabiogallo-blueprint** [lodash/lodash#3074]
Please see this test: https://jsperf.com/lodash-map-vs-foreach/6

The performance difference seems quite noticeable between `_.forEach` and the native `for` when looping an array of simple objects. 

Is this a known behaviour?

**Comment by jdalton** [comment]
Hi @fabiogallo-blueprint!

Yes, this is known. A for-loop is pretty bare metal. Our `_.each` is comparable or better than `Array#forEach`.

**Comment by fabiogallo-blueprint** [comment]
Thanks for the quick reply!
