### ISSUE TITLE
Not all of Backbone's Underscore-proxied methods are supported by Lodash 4

### ISSUE THREAD

**Issue by russplaysguitar** [lodash/lodash#3075]
Backbone provides proxies for some Underscore methods, such as `invoke` and `pick`. These methods have been changed in Lodash v4 to `invokeMap` and `pickBy` (when using an iteratee), but Backbone does not provide proxies to these new Lodash methods, it continues to proxy to the same methods, which is now incorrect. 

I've created two codepens with the same code, one with Underscore and one with Lodash 4. 

Underscore + Backbone:
http://codepen.io/anon/pen/ryKqXV?editors=0011

Lodash 4 + Backbone:
http://codepen.io/anon/pen/bqKmRL?editors=0011

You can clearly see that the Lodash codepen does not work with Backbone as expected. Note: Although I've only demonstrated a problem with `invoke` and `pick`, this same issue also exists with various other Underscore-proxied methods in Backbone. 

I understand that Backbone clearly defines Underscore as a dependency, so it's OK by me if Lodash doesn't work correctly with Backbone. However, I recommend either fixing these issues OR removing Backbone support from the Lodash documentation (such as: "Lodash works great with Backbone" on https://github.com/lodash/lodash/wiki/Migrating).

**Comment by jdalton** [comment]
Hi @russplaysguitar!

This is known. We support their core functionality and work with Backbone core to ensure that support. We also run against their unit tests. Proxied methods are bonus and it's expected if a method doesn't exist in Lodash that a proxy for it wouldn't work.
