### ISSUE TITLE
Add another example to 'use custom delimiters' section for documentation about _.template

### ISSUE THREAD

**Issue by timurista** [lodash/lodash#3076]
When implementing the `_.template` method for our company, we ran into an issue where we wanted to define a custom interpolate method but it failed when we attempted to define it using the `_.templateSettings` in multiple places in our app (we were using react and redux). After a little digging I discovered that you can just pass it in through the options parameter (which solved our issue). I know the documentation does specify that you can do this already (if you read about options), but I would like to add another example to help out future developers who run into this problem and are just skimming the examples section.

I don't know where the documentation lives, but can you add another example where you pass interpolate method as an inline argument. Maybe like this after the `//Use custom template delimiters`:
```
// You can also use custom template delimiters as inline options
var compiled = _.template('hello {{ user }}!', {template: /{{([\s\S]+?)}}/g} );
compiled({ 'user': 'curly mustache' });
// => 'hello curly mustache!'
```
Thank you!

**Comment by jdalton** [comment]
Hi @timurista!

Thanks for the suggestion. I'm on the fence with my plans for `_.template` in v5. I'm thinking of turning it into an [ES6 template tag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

**Comment by timurista** [comment]
I checked out template tag, it looks like it's not easy to override the default template `${ person }` and replace it with say `<< person >>.` I suggest you keep this feature because our java server escapes particular expressions (like ${}) and so lodash offers a nice way to match the way our server sends the templates. But I didn't realize that ES6 will be adding more features for their templates! It's nice to see
