### ISSUE TITLE
fp.tryCatch 

### ISSUE THREAD

**Issue by umidbekkarimov** [lodash/lodash#3077]
I have never used `_.attempt` but cause all lodash methods are really easy to understand I wrote this without looking to docs:

```javascript
fp.flow(
  fp.attempt(event => {
    const text = event.clipboardData.getData("Text");

    event.preventDefault();

    return text;
  }),
  fp.cond([
    [fp.isString, fp.flow(fp.split("\n"), fp.map(fp.trim), input.onChange)]
  ])
);
```

Expecting that `fp.attempt(func)` will create a function that accepts arguments of `func` but instead it just called `func`.

So I had to rewrite it like this:

```javascript
fp.flow(
  event =>
    fp.attempt(() => {
      const text = event.clipboardData.getData("Text");

      event.preventDefault();

      return text;
    }),
  fp.cond([
    [fp.isString, fp.flow(fp.split("\n"), fp.map(fp.trim), input.onChange)]
  ])
);
```

I understand that this API is old enough to proof it's value, but I think that it's bit confusing.

And method like [ramdajs.tryCatch](http://ramdajs.com/docs/#tryCatch) would be a great addition to `lodash/fp` toolkit.

**Comment by jdalton** [comment]
Thanks @umidbekkarimov!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by oliver-foggin** [comment]
I have been hit by this a few times. I gave up using attempt until I just saw this.
