### ISSUE TITLE
Why is "lodash.min.js" part of the "lodash" module?

### ISSUE THREAD

**Issue by wsmd** [lodash/lodash#3079]
I noticed that `lodash.min.js` is part of the bundle itself which will also end up being minified. So what I have here is a minified lodash including a `lodash.min.js`!

![screen shot 2017-03-28 at 2 22 47 pm](https://cloud.githubusercontent.com/assets/2100222/24420800/0be76c0a-13c2-11e7-818c-fa208c0b65c4.png)

`fp.js` is the only place where `lodash.min` is required.

```js
// lodash/fp.js

var _ = require('./lodash.min').runInContext();
module.exports = require('./fp/_baseConvert')(_, _);
```

I am using both `lodash` and `lodash/fp` in my app. I don't really mind including the entire/full lodash since I heavily rely on it. However, as far as I can tell, including `lodash.min.js` is kind of redundant. 

I tried to experiment with some ways to get rid of the `lodash.min.js` in my bundle while keeping `lodash/fp`. Therefore, I added this to webpack (which does seem weird and hacky 🤞):

```js
resolve: {
  alias: {
    './lodash.min': path.resolve(path.join(__dirname, 'node_modules', 'lodash/lodash')),
  }
}
```

I think this does the trick. The `min` version is now gone and everything seems to work just fine.

![screen shot 2017-03-28 at 2 37 33 pm](https://cloud.githubusercontent.com/assets/2100222/24421411/255a93e0-13c4-11e7-9f5b-9c7cc8180307.png)

Is there a better way to do this and not include multiple builds in my bundle? Like I said, I do use regular `lodash` and `lodash/fp` in my codebase and I don't mind including the entire full lodash build (all methods).

**Comment by jdalton** [comment]
Folks use the package for client-side too which is why the min is included. I went with min as the default deploy with lodash fp since it helps with execution performance. Remapping is a good solution if you're using both. You could also just do ` require('lodash/fp/_baseConvert')(_, _)` your lodash instance too.

**Comment by jdalton** [comment]
If you use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) it should take care of your lodash dep and it will just use the modules required (you won't get either monolithic builds included in your bundle. You should also look into [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) with `currying` enabled to reduce things even further.

**Comment by wsmd** [comment]
> Folks use the package for client-side too which is why the min is included

Sorry about the confusion. I'm working on a client-side app as well.

> require('lodash/fp/_baseConvert')(_, _)

Modifying the source code won't be option since I'm using lodash via npm. 

Do you see any implications for what I did with aliasing/mapping min to the regular lodash in my webpack config?

**Comment by florian-bd** [comment]
I have the same issue and the babel-plugin-lodash doesn't help.
Is there any documentation about the lodash-webpack-plugin it feels like you should really know what you can remove otherwise lodash would stop working in some cases?

**Comment by dortzur** [comment]
I solved this by using webpack's alias feature:
```javascript
config.resolve.alias['lodash/fp']  = 'node_modules/lodash';
```

**Comment by i4got10** [comment]
This issue should be reopened, the problem still exists.
