### ISSUE TITLE
Provision for _.unset to remove intermediate path properties if empty

### ISSUE THREAD

**Issue by rtrg** [lodash/lodash#3082]
```js
var x= {};
_.set(x, ['a', 'b', 'c'], 1)
// {"a":{"b":{"c":1}}}

_.unset(x, ['a','b', 'c'])
// {"a":{"b":{}}}
```
I am expecting `x` to be `{}`

```js
var x= {};
_.set(x, ['a', 'b', 'c'], 1)
// {"a":{"b":{"c":1}}}

_.set(x, ['a', 'y', 'c'], 1)
// {"a":{"b":{"c":1},"y":{"c":1}}}

_.unset(x, ['a','b', 'c'])
// {"a":{"b":{},"y":{"c":1}}}
```
Here I am expecting `x` to be `{"a":{"y":{"c":1}}}`

If this can't be a default behavior, can there be a provision to do this somehow with `_.unset`?

Underlying reason for this expectation is to avoid memory leak when using _.set and `_.unset` in conjunction

**Comment by Archimidis** [comment]
Why `_.unset(x, ['a','b'])` in the above cases is not suitable for you?

**Comment by rtrg** [comment]
var x= {};
_.set(x, ['a', 'b', 'c'], 1)
// {"a":{"b":{"c":1}}}

_.set(x, ['a', 'b', 'd'], 1)
// {"a":{"b":{"c":1,"d":1}}}

_.unset(x, ['a','b', 'c'])
// {"a":{"b":{"d":1}}}
I can't use `_.unset(x, ['a','b'])` here though.

My intention here is to unset ['a', 'b', 'c'], I could have used `_.unset(x, ['a','b'])` but for that I should know the fact that 'b' doesn't have any more keys other than 'c'.

For a given path I should start processing keys in path to check this fact and do _.unset(..) there(as you suggested `_.unset(x, ['a','b'])` for the example in my first post).

I felt it would be good if this can be implemented by default or have some provision with _.unset() itself.

**Comment by jdalton** [comment]
Hi @rtrg!

If you're wanting to snip properties at a lower level then you should use a shallower path.
