### ISSUE TITLE
omit doesn't omit keys longer than 1 char

### ISSUE THREAD

**Issue by pokle** [lodash/lodash#3089]
With Lodash 4.17.4, in Chrome:

```js
var omit = require("lodash/omit");
omit({ 'aa': 'a' }, ['aa'])
```
incorrectly results in: 

`{aa: "a"}`

- Instead, if you omit a single char string, it works (`omit( { 'a': 'a' }, ['a'])`)
- omit works fine in nodejs.

**Comment by jdalton** [comment]
I can't repro this. Sounds like it might be related to https://github.com/lodash/lodash-webpack-plugin/issues/102.

**Comment by pokle** [comment]
Yes, that's exactly what it was. Thanks!
