### ISSUE TITLE
Shortcut execution is not working for obvious filter-map combination

### ISSUE THREAD

**Issue by Saisuryakattamuri** [lodash/lodash#3092]
I've come across the concept of shortcut fusion in lodash documentation.
Is that similar to vertical execution?
(where items propagate through pipeline functions vertically and not after finish one operation completely)
If yes why shortcut fusion is not triggered for filter-map combination even the array size is more than 200.
Eg used
```
var persons = [{
                name: 'abc',
                id: 2,
                profession: 'xyz'
            }...]; //size is 202
```

```
_.chain(persons).filter(person => person.id % 2 == 0).map(person => {
                    return {
                        name: person.name,
                        profession: person.profession
                    };
                }).value();
```

when I've used console.log stmt in filter and map, I've observed the total code is running 202*2 times rather than 202 times.(**assuming all ids are even**)
What is the problem with the above code ? what is stopping it from passing the person item to map function immediately after filter operation?

Please clarify...Thanks in advance

**Comment by Archimidis** [comment]
That is correct. Each function will be executed once for each object and this is why you see 202 * 2 calls. 
To see fusion in action try this:

```
let count = "";
_(persons)
  .filter(person => {
    count += `filter ${person.id} `;
    return person.id % 2 === 0;
  })
  .map(person => {
    count += `map ${person.id} `;
    return { name: person.name, profession: person.profession };
  })
  .take(10)
  .value();
```

**Comment by Saisuryakattamuri** [comment]
@Archimidis but that is not an efficient way right.I don't want to use take() operation.Instead of executing them twice the size of the array, why can't we execute them vertically,so that number of iterations are less, hence performance.
Also I've observed one more thing with take.Shortcut fusion is working only when take has a param which is less than the size of target array.If take's parameter is equal to size of array it is executing in horizontal manner only.
