### ISSUE TITLE
Support caching inside _.template

### ISSUE THREAD

**Issue by arosenb2** [lodash/lodash#3093]
Abstract engine libraries such as [Consolidate](https://github.com/tj/consolidate.js/) support conventions for developers to specify whether or not to use caching for templates. Swig, though discontinued, has a fairly simple method of in-memory caching of compiled templates (see [here](https://github.com/paularmstrong/swig/blob/master/lib/swig.js#L200)). It should be a fairly low cost for the performance gains.

Apologies if this has already been listed as an issue before!

**Comment by jdalton** [comment]
Hi @arosenb2!

The `_.template` method compiles a method for reuse.
You can also pre-compile templates with [lodash-cli](https://lodash.com/custom-builds).

**Comment by arosenb2** [comment]
Thanks @jdalton!
