### ISSUE TITLE
Curried version of _.set

### ISSUE THREAD

**Issue by dwiyatci** [lodash/lodash#3094]
:wave:, is there a curried version of `_.set`?

I'd like to have a shortcut for writing something like:

`promise.then(_.curry(_.set)(vm, 'result'));`

`promise.then(result => vm.result = result);`

**Comment by ds82** [comment]
The ``lodash/fp/set`` function is auto-curried (but care, argument order of the fp functions is different)

See: https://gist.github.com/jfmengels/6b973b69c491375117dc#_setpath-value-object
