### ISSUE TITLE
valueBy proposal

### ISSUE THREAD

**Issue by Alexsey** [lodash/lodash#3095]
There is a `keyBy` in `lodash` that allows to build an object base on array where objects keys are generated by the iterator. Proposal is to add paired to `keyBy` - `valueBy` function that will also traverse over the array but iterator would build values

Example:
```
const names = ['Kate', 'Justin', 'Bob']
_.valueBy(names, name => `Hello ${name}`) 
```
Would output
```
{
  Kate: 'Hello Kate', 
  Justin: 'Hello Justin', 
  Bob: 'Hello Bob'
}
```

**Comment by jdalton** [comment]
Thanks @Alexsey!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by Alexsey** [comment]
As far as I can see there are people who are periodically come into this issue. The shortest solution I have found for now is
```js
const names = ['Kate', 'Justin', 'Bob']
_(names).mapKeys().mapValues(name => `Hello ${name}`).value()
```

**Comment by mikez302** [comment]
I found some more readable (IMO) solutions:
```javascript
const names = ['Kate', 'Justin', 'Bob'];
return _.zipObject(names, _.map(names, name => `Hello ${name}`));
```

Or if you don't mind using the native `map` method on arrays:
```javascript
const names = ['Kate', 'Justin', 'Bob'];
return _.zipObject(names, names.map(name => `Hello ${name}`));
```

**Comment by Xotic750** [comment]
[Or even :)](https://jsfiddle.net/op2t692q/)
```js
const valueBy = (array, mapFn) => array.reduce(
  (acc, value) => ({ ...acc, [value]: mapFn(value)}), 
  {},
);

const names = ['Kate', 'Justin', 'Bob'];
const mapFn = name => `Hello ${name}`
console.log(valueBy(names, mapFn));
```

**Comment by elias6** [comment]
Yet another way:
```javascript
const names = ['Kate', 'Justin', 'Bob'];
return _.fromPairs(names.map(name => [name, `Hello ${name}`]));
```

**Comment by ConnorSinnott** [comment]
Hey @jdalton! Curious how many thumbs up are needed as the threshold for a feature add. I see we have 30, but is that a lot? A little? In my experience I find myself reaching for a `valueBy` equivalent more than `keyBy`. I see others have posted some nice shortcuts, but usually lodash's methods _are_ my shortcut lol.
