### ISSUE TITLE
_.cloneDeep does not clone objects within objects.

### ISSUE THREAD

**Issue by jonteferm** [lodash/lodash#3097]
Hey,

I have a trouble with cloning js-objects. I have an object and that object can contain properties which are strings, ints and other objects. The trouble is that when i use _.deepClone() - the properties which are other objects is set to null in the clone. It seems like that is not the case for the _.clone() method, but that makes the clone keep references to the original object so to use that is not an option in this case. I was under the impression that the deepClone would do an exact copy. 

Best Regards,
jonteferm

**Comment by falsyvalues** [comment]
@jonteferm Hi, could you post some examples? This doesn't look like lodash problem. Take a look at [docs](https://lodash.com/docs/4.17.4#cloneDeep).

**Comment by jonteferm** [comment]
I'm in angular. Having this:
`vm.object1 = {property1: 'blblblabla', property2: {property1: {}, property2: {}}};
vm.object2 = {property:1 'Hello hello', property2: _.cloneDeep(vm.object1.property2) };`

if i then check object2 - it looks like this:
`{property:1 'Hello hello', property2: null};`

**Comment by jdalton** [comment]
There are some unclonable values you can create a custom clone method to handle them using [_.cloneDeepWith](https://lodash.com/docs/4.17.4#cloneDeepWith):
> **Note:** This method is loosely based on the structured clone algorithm and supports cloning arrays, array buffers, booleans, date objects, maps, numbers, Object objects, regexes, sets, strings, symbols, and typed arrays. The own enumerable properties of arguments objects are cloned as plain objects. An empty object is returned for uncloneable values such as error objects, functions, DOM nodes, and WeakMaps.
