### ISSUE TITLE
[Question] Recommended usage with webpack 2

### ISSUE THREAD

**Issue by Vanuan** [lodash/lodash#3098]
AFAIK, webpack 2 has tree shaking and dead code elimination if you use `module: false` in babel options.

So the question is whether babel & webpack plugins for lodash are necessary if we use `lodash-es`.

I see that it still might help for external modules. But should we ditch `lodash` and switch to `lodash-es` going forward? If might help to switch off commonjs babel support and going 100% webpack/esmodule.

**Comment by jdalton** [comment]
I get this a lot. I think despite the marketing if you try it out you'll find neither webpack 2 nor rollup are tree shake friendly to Lodash. That's why there's [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash).
