### ISSUE TITLE
What is this syntax?

### ISSUE THREAD

**Issue by tylerbhughes** [lodash/lodash#3100]
Hi, I took over a project a while back, one of the first things I tried doing was updating all the dependencies. The project was using lodash version 0.10.0. I've never actually used lodash before and for the most part I haven't had any issues using the docs to figure out what each piece is doing. However, I have several lines of code that looks like this: 
```js
_(this.assets).each(function(typedAssets, type) {
```
I know the .each is an alias for the array for each method but I can't find any thing that talks about the 
```js
_(this.assets)
```
part. Is this a DOM selector of some sort? If so, where can I find this in the documentation?

**Comment by jdalton** [comment]
Hi @tylerbhughes!

This is part of our [chaining syntax](https://lodash.com/docs#lodash).
For more help on these kinds of questions visit our [gitter chat](https://gitter.im/lodash/lodash).
