### ISSUE TITLE
Parameters of debounce is reduced from 3 to 2?

### ISSUE THREAD

**Issue by qiansen1386** [lodash/lodash#3104]
_.debounce can take 3 paramters, 2 of them are optional. 
But in the fp repo, debouce is a function with a fixed arity of two? Is it a bit confusing

Em.. so which 2? 

I get an "Expected a function" error every single time 😿

**Comment by jdalton** [comment]
It's `func` and `wait`. If you'd like to remove the arguments cap you can with [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert).
