### ISSUE TITLE
Update Many

### ISSUE THREAD

**Issue by iddan** [lodash/lodash#3106]
Like _.update but applies on multiple paths and combines the results.

### FP Implementation:
```JavaScript
/**
 * @param {Object<func>} updaters - Obejct of path strings and update functions to apply on object
 * @param {Object} object
*/
const updateMany = (updaters, object) => fp.reduce.convert({ cap: false })(
  (acc, updater, path) => fp.update(path, updater, acc),
  object,
  updaters
);
```

**Comment by jdalton** [comment]
Thanks @iddan!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by hgwood** [comment]
@iddan Am I correct if I say this would work like [Ramda's `evolve`](http://ramdajs.com/docs/#evolve)?

**Comment by iddan** [comment]
Indeed!
