### ISSUE TITLE
Master branch missing lib and test directories and lodash.js?

### ISSUE THREAD

**Issue by joeycozza** [lodash/lodash#3107]
I'd like to fork the repo and submit a PR, but it appears that the master branch here on github doesn't have the lib and test directories, as well as the lodash.js file. Am I missing something obvious?

**Comment by jdalton** [comment]
Hi @joeycozza!

See [the contributing notice](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#construction-notice-construction). If you're doing a PR to add a method, don't. Request it first to allow it to get votes.

**Comment by joeycozza** [comment]
It isn't a new method, just a tweak to an existing method, which seemed to me to fall under the Pull Requests section of the contributing guide, not the Feature Request.  But I'll open a new issue with exactly what I was going to do.
