### ISSUE TITLE
toFinite currently has some unnecessary logic

### ISSUE THREAD

**Issue by joeycozza** [lodash/lodash#3108]
Here is the line that I believe has some unneeded logic.

https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L12374

I believe that the code could just be
```javascript
if (!value) {
  return 0;
}
```

If I don't understand something, let me know, but it seems redundant to have that ternary operator.

**Comment by jdalton** [comment]
The bit is needed to support `-0` (it's a thing).
```js
-1/Infinity // -0
