### ISSUE TITLE
words and snakeCase for alpha-numerics

### ISSUE THREAD

**Issue by x3mka** [lodash/lodash#3109]
Is it correct behavior?
_.snakeCase("S3Key")  -  s_3_key
_.words("S3Key") - ["s", "3", "key"]

Ruby active support equivalent for snakeCase String.underscore returns "s3_key". 
Is it an easy way to get the same result with lodash functions?

**Comment by jdalton** [comment]
Hi @x3mka!

Nope. You can create your own helper though.
