### ISSUE TITLE
Support Typed Arrays and Buffers in clone/deepClone

### ISSUE THREAD

**Issue by phated** [lodash/lodash#311]
Feature detect for them and support them if they exist in the env.

**Comment by metamatt** [comment]
@jdalton: this is a blast from the past, but did what you mentioned in https://github.com/lodash/lodash/issues/311#issuecomment-44144266 actually happen? From a quick read of https://github.com/lodash/lodash/blob/master/lodash.js#L178 I believe it did.

But, not for NodeJS's `Buffer` type. I realize that's a Node thing and not a JS/ES thing, and I don't know what lodash's stance is on NodeJS-specific types, but the result of `lodash.clone` on a Buffer is pretty bad (never what you want, can be a performance nightmare); the customizer trick works but we need to specify that on every call to `lodash.cloneDeep` that might have a Buffer lurking somewhere in there; any chance of adding builtin support for Buffer along these lines?

**Comment by jdalton** [comment]
Yap typed array and their array buffers are cloneable but not the Node specific ones. I'm open to supporting it just because lodash is used so heavily in Node land. The customizer function can be composed to avoid re-applying:
```js
var _ = require('lodash').runInContext();
_.mixin({ 'clone': _.partialRight(_.clone, customizer) });
```

Would you mind sharing your customizer?

**Comment by metamatt** [comment]
Oh, neat. Thanks for the note about `runInContext`.

The customer that I'm using for node Buffer is simple and seems to work:

```
_.clone(obj, function dealWithBuffers(val) {
   if (val instanceof Buffer) {
      return val.slice();
   }
});
```
