### ISSUE TITLE
_.unzipWith takes only first two arrays in 4.17.4

### ISSUE THREAD

**Issue by Neil-Ni** [lodash/lodash#3110]
Hi, I came across a weird behavior in _unzipWith in 4.17.4. Take a look at the outcome from two versions:

v3.10.1
_.unzipWith([[1, 2],[4, 8, 16],[32]], _.add)
result: [37, 10, 16]

v4.17.4
_.unzipWith([[1, 2],[4, 8, 16],[32]], _.add)
result: [5, 10, 16]

Examples in Plunker, where results are console logged:

3.10.1: https://plnkr.co/edit/hyPndS
4.17.4: https://plnkr.co/edit/6oRloQ

Also noticed that the lib/test scripts are missing due to https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#construction-notice-construction, but if there's a way for me to write unit tests, please point a way and I'd be glad to submit a PR for it : )

**Comment by jdalton** [comment]
Hi!  This is by design and covered in the changelog
