### ISSUE TITLE
Using Array.prototype.slice.call(array ...) instead of array.slice(...) may break reactivity in some frameworks

### ISSUE THREAD

**Issue by Toilal** [lodash/lodash#3111]
Is there any reason to [use call here](https://github.com/lodash/lodash/blob/master/.internal/basePullAt.js#L26) ?

I'm a [Vue](https://vuejs.org/) user, and Vue overrides `splice` method to make array properties reactive. 

So using this pattern in lodash sources breaks reactivity when using lodash in a Vue application, because it always use the default array slice method, instead of the overriden one.

Workaround is to use `_.find(...)` followed by a vanilla `Array.splice(...)`, instead of `_.remove(...)` for instance.

**Comment by jdalton** [comment]
Hi, neat but overwriting builtins isn't super stable thing

**Comment by medikoo** [comment]
@jdalton note it's not perfectly ES2015+ friendly approach, which plays nice with array extensions.
e.g. native `splice` will return the array of same type (initialised with same constructor) as context array (assuming it's an array specie).

**Comment by akaibukai** [comment]
Hello,
I just [hit the same problem](https://github.com/vuejs/vue/issues/3434#issuecomment-314985710) with lodash `_.remove()` function using VueJS..
You can use the non-mutating `_.reject()` function instead.

But what a pity to have this situation:
> This is a wontfix as explained above. It seems there's no particular reason to use call instead of direct splice. _"@yyx990803 [from VueJS](https://github.com/vuejs/vue/issues/3434#issuecomment-239445013)"_

and

> Neat! But overwriting builtins isn't a super stable thing. _"@jdalton [from lodash](https://github.com/lodash/lodash/issues/3111#issuecomment-294222147)"_

I mean it would be just great to improve inter-operability between such useful frameworks/libraries..
