### ISSUE TITLE
mapKeys, first Key returns undefined

### ISSUE THREAD

**Issue by pungggi** [lodash/lodash#3112]
Let me explain my issue with a picture:
![image](https://cloud.githubusercontent.com/assets/5635709/25073256/154efda0-22e3-11e7-8a99-c0d764e5d86a.png)
![image](https://cloud.githubusercontent.com/assets/5635709/25073267/500cafc8-22e3-11e7-9d67-032f4aa021ec.png)
using ver. 4.17.4

**Comment by jdalton** [comment]
If a value isn't returned it will be undefined.

**Comment by pungggi** [comment]
how avoid that?

**Comment by jdalton** [comment]
One way is to return something in an `else` statement. For more help check out our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by yxuecheng** [comment]
m
