### ISSUE TITLE
does Object : commonKeys exists ?

### ISSUE THREAD

**Issue by thifranc** [lodash/lodash#3114]
Hi,  
I've used this function a lot :  
```
  commonKeys (a, b) {
    return Object.keys(a).filter((key) => {
      return key in b;
    });
  };
```
Is there any equivalent in Lodash ?  
If no, would you consider adding it ? I'd be glad to PR this useful project !  
Cheers,

**Comment by citycide** [comment]
You could always do a mixin of `_.intersection(_.keys(a), _.keys(b))`.

**Comment by jdalton** [comment]
Hi @thifranc!

No, Lodash doesn't have a `commonKeys` module, however as @citycide points out you can create one from other Lodash modules.

**Comment by thifranc** [comment]
nicer code that my function !
Thanks a lot !
