### ISSUE TITLE
Argument reversal in 'loadash/fp/debounce'

### ISSUE THREAD

**Issue by asolopovas** [lodash/lodash#3116]
Hi, 

For some reason when I do `import debounce from 'loadash/fp/debounce`  function reverses arguments so func becomes time and time becomes fine. Basically 

```
debounce(function(){ console.log('test') }, 500) // throws TypeError expecting function
debounce(500, function() {console.log('test')) // works without problems
```

Such behaviour disappears if I do `import debounce from 'loadash/debounce`

**Comment by falsyvalues** [comment]
Hi @asolopovas did saw [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide)? Especially this part:

> The lodash/fp module promotes a more functional programming (FP) friendly style by exporting an instance of lodash with its methods wrapped to produce immutable auto-curried iteratee-first data-last methods.

**Comment by asolopovas** [comment]
So its me being lazy
