### ISSUE TITLE
Make MapCache be Map if available?

### ISSUE THREAD

**Issue by wmertens** [lodash/lodash#3117]
Since MapCache implements a subset of the `Map` API, and presumably native `Map` implementations can be faster, would it not make sense to set `MapCache` to `Map` if it is available?

Just wondering… Not everybody will think to do `memoize.Cache = Map`, and of course I have no idea if it is a win or not.

**Comment by jdalton** [comment]
Hi @wmertens!

In JavaScript never assume built-in are faster. For ES5/6/7 built-ins there's a pretty good chance they're slower. In our case we use built-in `Map` for what it's good at, using objects as keys. For everything else we use our internal implementation since it's faster.
