### ISSUE TITLE
cannot use with typescript

### ISSUE THREAD

**Issue by epitka** [lodash/lodash#3118]
Not sure if this is the right place to post this issue. I am having trouble with using lodash with typescript as described in this SO post. Any ideas on how to address this?

http://stackoverflow.com/questions/43551047/cannot-use-typescript-arrayt-with-lodash?noredirect=1

**Comment by jdalton** [comment]
This isn't the place. Try the [TypeScript gitter chat](https://gitter.im/Microsoft/TypeScript).
