### ISSUE TITLE
_.replace() replace only first occurence

### ISSUE THREAD

**Issue by gop-aroy** [lodash/lodash#3119]
Hi,

I just noticed that the method `_.replace()` only replace the first occurence of the **pattern** by the **replacement** in the **string** to modify.
For example, if i do `console.log(_.replace('Hi Fred Fred Fred', 'Fred', 'Barney'));` I'll have `Hi Barney Fed Fred`. I personally expected `Hi Barney Barney Barney`

The documentation does not specify this so is it the documentation which is not up to date or the method which as a little anomaly ?

Thank you in advance you guys :)

**Comment by falsyvalues** [comment]
Hi @gop-aroy take a look on docs https://lodash.com/docs/4.17.4#replace especially the note: This method is based on [String#replace](https://mdn.io/String/replace) and this is how String#replace works. You may use regexp with global flag to address this.

**Comment by gop-aroy** [comment]
Yup I saw that, but this was not obvious enough for me that it was "only" an alias.
