### ISSUE TITLE
Add first-class support for WHATWG URL objects?

### ISSUE THREAD

**Issue by JamesMGreene** [lodash/lodash#3121]
Any chance of adding specially cased first-class support for WHATWG URL objects for functions like `_.isEqual`, `_.isMatch`, etc.?
 - https://nodejs.org/docs/latest-v7.x/api/url.html#url_the_whatwg_url_api
 - https://url.spec.whatwg.org/
 - https://developer.mozilla.org/en/docs/Web/API/URL

The trouble is that these URL objects are, IMHO, essentially un-semantic in nature as they have prototypally inherited `get` property descriptors rather than owned properties.

Related issue, with utilizing `_.isEqual` and `_.isMatch`, both of which fail for these URL objects:
https://github.com/JamesMGreene/chai-deep-match/issues/2

**Comment by jdalton** [comment]
They are detectable as `[object URL]` so it's totally possible.

**Comment by jdalton** [comment]
Would you be up for creating a PR (don't worry about the tests at the moment since things are under construction).

**Comment by jdalton** [comment]
Closing as abandoned. Feel free to ping back to revive.

**Comment by JamesMGreene** [comment]
@stevenvachon Any interest in pursuing this on the LoDash side?

**Comment by stevenvachon** [comment]
Nope. I have no use for lodash nor underscore.

**Comment by jdalton** [comment]
You can always use [_.isEqualWith](https://lodash.com/docs/#isEqualWith) and [_.isMatchWith](https://lodash.com/docs/#isMatchWith) to add in customized support for `URL` objects.

**Comment by JamesMGreene** [comment]
@stevenvachon Except that you want URL support in chai-deep-match. 😛

**Comment by JamesMGreene** [comment]
@jdalton: Yeah, that'd be almost perfect.  It'll get me through the equality comparisons, anyway... then I just need to handle diffing the un-owned properties for display purposes. :+1:
