### ISSUE TITLE
cloneDeep throws RangeError for Sets with circular references

### ISSUE THREAD

**Issue by ajgreenb** [lodash/lodash#3122]
If you have an Object containing a Set with a reference to the Object and you `_.cloneDeep` it, you get `RangeError: Maximum call stack size exceeded`. In the same situation, but with an Array instead of a Set, there's no problem. Here's how you can reproduce it:

```js
var objSet = { x: new Set() };
objSet.x.add(objSet);
_.cloneDeep(objSet);
// RangeError: Maximum call stack size exceeded

var objArr = { x: [] };
objArr.x.push(objArr);
_.cloneDeep(objArr);
// Properly deep-cloned object
```

Seems like circular dependencies aren't properly handled when they're in Sets? From #2137 I saw that support for deep-cloning Sets, Maps, and Symbols was added at 24cef1a. Is this behavior expected? If not, I'd be happy to attempt a fix. Seems like I would need to patch the `baseClone` function?

**Comment by jdalton** [comment]
Range errors aren't expected so if you're up for making a patch that would rock.

**Comment by jdalton** [comment]
Moved to #3123.
