### ISSUE TITLE
faltten method error

### ISSUE THREAD

**Issue by lidongcn** [lodash/lodash#3124]
document：
_.flatten([1, [2, 3, [4]]], true);
// => [1, 2, 3, 4]

result：
_.flatten([1, [2, 3, [4]]], true)
// => [1, 2, 3, [4]]

**Comment by jdalton** [comment]
Hi @lidongcn!

The [_.flatten](lodash.com/docs/#flatten) method doesn't accept a boolean flag.
You're looking for [_.flattenDeep](lodash.com/docs/#flattenDeep).

**Comment by lidongcn** [comment]
@jdalton  Thank you，  I was wrong！
