### ISSUE TITLE
_.throttle() on mouse events prevents event.offsetX/offsetY from working in Firefox

### ISSUE THREAD

**Issue by sandermarechal** [lodash/lodash#3126]
It appears that, if you use `_.throttle()` or `_.debounce()` on mouse events in Firefox, it can sometimes prevent the event offsetX and offsetY parameters from working. Those properties sometimes contain '0' instead of the proper values.

I don't know if this is a Lodash issue or a Firefox issue,. but perhaps this should be dealt with in Lodash either way.

Here is a JSFiddle that reproduces the issue: https://jsfiddle.net/amoc1dqj/

When I scroll with my mousewheel when over the div labeled "Native", the JS console always shows the proper offsets. When I scroll the mousewheel over the div marked "Throttled", I sometimes get the proper offset, but sometimes I get zero. If I scroll fast with the mousewheel, the first event usually has the proper offset but later events do not.

I am using Firefox 53.0 64-bit official version by Mozilla on Linux (Debian Jessie AMD64)

**Comment by sandermarechal** [comment]
Als tested with Firefox 53.0 32-bit on Windows. Same thing.

**Comment by jdalton** [comment]
Hi @sandermarechal!

Not a Lodash issue. File [a bug with mozilla](https://bugzilla.mozilla.org/).

**Comment by sandermarechal** [comment]
Thanks. I have reported it at Mozilla.
