### ISSUE TITLE
lodash/get & lodash/result not work with nested keys

### ISSUE THREAD

**Issue by malyusha** [lodash/lodash#3127]
When lodash (`4.17.4`) installed via npm and used with webpack `get` and `result` methods are not working as expected with nested keys. After i installed `lodash.get` and `lodash.result` separately it's working as expected. I've made little test to show it:
```javascript
import get from 'lodash/get';
import separatedGet from 'lodash.get';
import result from 'lodash/result';
import separatedResult from 'lodash.result';

const testObject = {some: true, nested: {is_nested: 'yes', callback: () => 'hello from func!'}};
console.log('---test get and result', get(testObject, 'nested.is_nested'), result(testObject, 'nested.func'));
console.log('---test separated get and result', separatedGet(testObject, 'nested.is_nested'), separatedResult(testObject, 'nested.callback'));
```

Outputs:
```
---test get and result undefined undefined
---test separated get and result yes hello from func!
```

But if i use last library version (`4.17.4`), included directly from cdn, everything works fine. What can be the reason of this problem? Thank you.

**Comment by jdalton** [comment]
It sounds like you're using [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) without the "paths" feature set.

**Comment by malyusha** [comment]
@jdalton 
Oh.. yes. That was the problem.
Thank you and sorry for  my stupidness...

**Comment by jdalton** [comment]
No worries. Happy to help 😃
