### ISSUE TITLE
math _.add is not working as expected

### ISSUE THREAD

**Issue by forest90** [lodash/lodash#3128]
![image](https://cloud.githubusercontent.com/assets/10866219/25434441/a321a280-2a8c-11e7-88c3-4bda2b7f7906.png)

**Comment by yeshwanth-reddy** [comment]
i think its expected to behave like that

If one of the argument is string it converts both arguments to string and add

```
if (typeof value == 'string' || typeof other == 'string') {
        value = baseToString(value)
        other = baseToString(other)
} else {
        value = baseToNumber(value)
        other = baseToNumber(other)
      }
```
refer [https://github.com/lodash/lodash/blob/6cb3460fcefe66cb96e55b82c6febd2153c992cc/.internal/createMathOperation.js](here)

**Comment by forest90** [comment]
No You are wrong. Doc's says it's MATH function. I do see some serious thread in case of use this function.

Let's take this situation into account:
![image](https://cloud.githubusercontent.com/assets/10866219/25483140/e20a1f0e-2b54-11e7-9d01-0d5a5c7f6cb8.png)

It is not acceptable behaviour of MATH function. 

Since i can get some string instead number, becouse getting input value using jQuery or whatever
this function will return some weird stuff.

As far as it is math fuction it should cast params to int. Otherwise move this function away MATH section, becouse MATH function should return NaN in worst case. 

Here is exactly what is in doc:
![image](https://cloud.githubusercontent.com/assets/10866219/25482912/005f6cc6-2b54-11e7-921d-67c1fc59c864.png)
