### ISSUE TITLE
request: make _.delay synchronous if `wait` is false

### ISSUE THREAD

**Issue by dwelle** [lodash/lodash#3130]
Common case for me is APIs that take `delay` param which, if (positive) integer, delays the API call. But since `_.delay` is regarding falsy `wait` args as `0`, I have to do something like this:

```
function _api () {
   ...
}
function api ( delay = false ) (
if ( !delay ) {
  _api();
} else {
  _.delay( _api , delay );
}
```

Which requires to factor the `api` body outside so it can be called synchronously.

Do you think it's too much a breaking change to regard `false` passed to `_.delay` as indicating we want a synchronous call?

**Comment by jdalton** [comment]
Hi @dwelle!

I don't want to mix sync/async here.
