### ISSUE TITLE
include hyphen in _.escapeRegExp

### ISSUE THREAD

**Issue by pathurs** [lodash/lodash#3132]
Run the following on in your console:

var regex = new RegExp('[' + _.escapeRegExp('!?.,:;(){}\[\]<>\-+=$%&#@*^"\'_|/\\') + ']')

Observe the error:

SyntaxError: invalid range in character class

This is because in a character set, or square brackets, a hyphen indicates a range, such as: 0-9

Yes, I could include the hyphen at the beginning of the character set.

**Comment by jdalton** [comment]
Dup of #2573.
