### ISSUE TITLE
Enhance _.cloneDeepWith() customizer

### ISSUE THREAD

**Issue by NicBright** [lodash/lodash#3133]
Right now it's not possible to specify that a property shouldn't be cloned at all (or that it should be cloned as undefined). This is, because when returning "undefined", lodash takes over. And there is no way to tell lodash to omit a property from being cloned. 

**In my case, however, I want certain properties NOT to appear in the clone at all.** E.g. in our frontend code we use a lot of "private" properties that start with `$`. There are several cases where we need to deep clone the business objects with the private properties removed. Right now, what we're doing is using _.cloneDeep() and only afterwards are we able to iterate over the object once more in order to remove the unwanted properties. As we have rather large business models (of up to 10 MB in rare cases), this double iteration adds up in time, resulting in a lousy performance.

**Comment by jdalton** [comment]
If you want to not clone something in the customizer you can simply return the value uncloned.
The clone method really doesn't skip properties as that's a bit outside the scope. You may be better off with a custom clone method tailored to your exact scenario.

**Comment by Alexsey** [comment]
Had the same issue. Can be solved with `cloneDeepWith`. For example, we want to remove (do not clone) deeply all `undefined` from the object:
```js
const object = {
    x: 1,
    y: undefined,
    z: {
        a: 2,
        b: 'b',
        c: undefined,
        d: {
            k: 3,
            p: undefined,
            q: null
        }
    }
}
const filteredObject = _.cloneDeepWith(object, function customizer (v) {
    return _.isObject(v)
        ? _.cloneDeepWith(_.omitBy(v, _.isUndefined), _.after(2, customizer))
        : undefined
})
```
where `_.omitBy(v, _.isUndefined)` is a part that is responsible for remove (do not clone) logic and any other shallow modifications that need to be performed
