### ISSUE TITLE
lodash types update for lodash (@types/lodash)

### ISSUE THREAD

**Issue by DogaIster** [lodash/lodash#3135]
My lodash dependency is updated to 4.17.4 but I get errors as follows:

ERROR in C:/Users/dister/Desktop/watchdog-w-autotuner/remoteClient/node_modules/@types/lodash/index.d.ts (12898,29): Cannot find name 'object'.

ERROR in C:/Users/dister/Desktop/watchdog-w-autotuner/remoteClient/node_modules/@types/lodash/index.d.ts (19638,15): All declarations of 'WeakMap' must have identical type parameters.

ERROR in C:/Users/dister/Desktop/watchdog-w-autotuner/remoteClient/node_modules/@types/lodash/index.d.ts (19638,33): Cannot find name 'object'.

Can you please provide which version of @types/lodash I should use. I tried 4.14.63 and 4.17.4, these didn't solve my problem.

Thanks

**Comment by jdalton** [comment]
Hi @DogaIster!

We don't maintain the typings. I believe that's Definitely Typed.
