### ISSUE TITLE
assignIn, extend source type checking gone

### ISSUE THREAD

**Issue by chriswininger** [lodash/lodash#3136]
I've noticed in newer version of lodash
```
_.extend({}, 'abc');
=>
{ 0: 'a', 1: 'b', 2: 'c' }
```
In underscore and earlier versions of lodash, the extend function included the guard, `if (iterable && objectTypes[typeof iterable])` which prevented the object from being extended with a string; so, 

```
_.extend({}, 'abc');
=>
{}
```
Garbage in garbage out I guess, but this seemed like a useful guard to me.

Was this change intentional or do you consider this a regression?

**Comment by jdalton** [comment]
Hi @chriswininger!

This feels like an edge concern but our implementation aligns with that of the built-in which coerces non null/undefined values to an object.
```js
Object.assign({}, 'abc')
// => { 0: 'a', 1: 'b', 2: 'c' }
```

**Comment by chriswininger** [comment]
OK, thanks for the quick response and clarification.
