### ISSUE TITLE
Throttle options in FP

### ISSUE THREAD

**Issue by kownacki** [lodash/lodash#3137]
`throttle` in FP is capped to 2 arguments (`options` cannot be passed). So how can I set trailing to `false`? There is method like `padCharsStart` which fixes similar problem for `padStart`, but I couldn't find anything for `throttle`. No `throttleLeading` or anything.

**Comment by kownacki** [comment]
I found solution myself: https://github.com/lodash/lodash/wiki/FP-Guide#convert

**Comment by palnes** [comment]
@kownacki care to outline your solution? :)

**Comment by kownacki** [comment]
Sure. I used `convert` to create customized `throttle` that takes `options` as third argument.
``` js
const throttleWithOptions = _.throttle.convert({fixed: false});
```
