### ISSUE TITLE
_.clamp doesn't check lower vs. upper bounds

### ISSUE THREAD

**Issue by ScottTrenda** [lodash/lodash#3139]
It seems to me that if we provide three arguments to `_.clamp`, we're specifying a range of numbers that it should be clamped to. In v4.17.4, incorrect results occur when `lower` is greater than `upper`. 
![image](https://cloud.githubusercontent.com/assets/5911505/25669642/b69f58d0-2fef-11e7-98fd-445568f50781.png)
It seems to me that the clamp code could be made smarter, so that it recognizes which of the two range endpoints is lower. That way, the caller doesn't have to do additional logic to ensure that it's passing the lower endpoint first.

**Comment by jdalton** [comment]
Garbage in garbage out.
