### ISSUE TITLE
repository directory structure messed up?

### ISSUE THREAD

**Issue by craigmichaelmartin** [lodash/lodash#3140]
Is the repository directory structure messed up? There seems to be no `lib` directory.

```bash
git clone git@github.com:lodash/lodash.git
cd lodash
npm install
```
`npm run build` fails with `Cannot find module '/Users/craigmartin/projects/lodash/lib/main/build-dist.js'`

I apologize if I'm just sleep deprived and missing something really basic :)

**Comment by craigmichaelmartin** [comment]
Apologies, just saw https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md

**Comment by JoshuaBelden** [comment]
> 
> 
> Apologies, just saw https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md

Craig, what was your revelation? I'm running into the same issue and don't see any content in CONTRIBUTIN.md that would resolve the problem.

**Comment by craigmichaelmartin** [comment]
Hmm, I don't recall. What are you trying to achieve?

**Comment by JoshuaBelden** [comment]
Sorry for the newb questions. I'd eventually like to contribute in some way and thought the most appropriate path forward would be to fork, test, and build out of master. Following the readme.md, when I run the build script with npm, the `build:fp` process runs `node lib/fp/build-dist.js`, but then complains that the `build-dist.js` module is not present.

Checking out the latest tag does in fact build without error. If I was to submit a pull-request, I would need to pr against the main branch, right?

**Comment by JoshuaBelden** [comment]
I'm clearly not reading closely enough. I'm finding answers under the PR section of contributing. Sorry for the interrupt, ignore me for now.
