### ISSUE TITLE
[FEATURE REQUEST] argmax/argmin

### ISSUE THREAD

**Issue by pranaygp** [lodash/lodash#3141]
> NOTE: This difference between these proposed functions and `minBy` and `maxBy` is that for collections, the index of the min/max value is returned instead of the actual value (refer to examples below). This function is often used in math.

This was an issue that was opened on underscore here: https://github.com/jashkenas/underscore/issues/1275

There was a discussion there about this, and I believe a good base implementation of this could be used as so

```js
// _.argmin(collection, [iteratee=_.identity])
// _.argmax(collection, [iteratee=_.identity])

// examples
const vals = [50, 150, 100]
_.argmin(vals)
// => 0
_.argmax(vals)
// => 1

_.argmin(vals, x => 1/x)
// => 1
_.argmax(vals, x => 1/x)
// => 0

const users = [{ name: 'Phil', karma: 12 }, { name: 'Amy', karma: 15 }]

// The `_.property` iteratee shorthand.
_.argmax(users, 'karma')
// => 0

const karmaHash = {
  Phil: 12,
  Amy: 15
}

// The `_.property` iteratee shorthand.
_.argmax(users, 'karma')
// => 'Amy'

// real world use case (motivation behind this request)

const wordPositionsHash = {
  'the': [1, 5, 7, ..., 130],   // occurrences of this word in a document by word position indices
  'a': [4, 9, ..., 120],
  ...
  'word': [54, 72]
}

// The `_.property` iteratee shorthand.
_.argmax(users, 'length')
// => 'a' (the most common word in document)

// The `_.property` iteratee shorthand.
_.argmin(users, 'length')
// => 'word' (the least common word in document)

```

**Comment by jdalton** [comment]
Thanks @pranaygp!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by pranaygp** [comment]
@jdalton I'm working on a PR to implement this. Given the process with these feature requests, and the codebase refactor for v5, is my work on the PR worth the time, or should I wait till later (or an implementation maintainers?

**Comment by jdalton** [comment]
Hold off on a pull requests until we open the issue to it.
For now let's see how much demand there is for a feature like this.

**Comment by pranaygp** [comment]
Sounds good 👍

**Comment by xgbuils** [comment]
Why is the name `argmin/argmax`? I didn't catch what means. I prefer something like:

indexOfMax(array)
indexOfMin(array)
indexOfMinBy(array, compare)
indexOfMinBy(array, compare)

Cheers!

**Comment by pranaygp** [comment]
@xgbuils

`argmin` and `argmax` is the right mathematical terminology for this

https://en.wikipedia.org/wiki/Arg_max
https://en.wikipedia.org/wiki/Arg_min

**Comment by xgbuils** [comment]
Cool!

**Comment by pranaygp** [comment]
@jdalton seems like this issue has a few thumbs ups. Is it worth investing time in making a PR to include these into the API?

**Comment by jdalton** [comment]
Hi @pranaygp!

Not at this time. However, you can always make a one-off package or mixin to experimental with the API, options, etc.

**Comment by baltar** [comment]
The mathematical definition of argmax/argmin is that they are the _sets_ of argument values for which the given function is max/min. Therefore I'd suggest that if this is implemented, it should return an array of indexes (or an array of the elements themselves) for whom the argument is max/min. I.e. 
```js
const vals = [50, 150, 50, 100];
_.argmin(vals); 
// => [0, 2]
```

**Comment by auroranil** [comment]
@jdalton Is there a set goal to see how many likes we need for the feature request to be made into a PR? Or does it depend on the feature request itself, and see how valuable it is in relation to the lodash library?

**Comment by jdalton** [comment]
@auroranil The likes are used to help me gauge user interest in a feature when I'm thinking about adding something is all.

**Comment by Ghost---Shadow** [comment]
Reopen maybe?
