### ISSUE TITLE
wrapped instance

### ISSUE THREAD

**Issue by enniel** [lodash/lodash#3143]
How to check instance of LodashWrapper. I'm tried this code.

```js
const LodashWrapper = require('lodash/_LodashWrapper')

console.log(foo instanceof LodashWrapper)
// false
```

**Comment by jdalton** [comment]
Hi @enniel!

For wrappers you can use:
```js
_() instanceof _
```

For any other questions please visit [our gitter chat](gitter.im/lodash/lodash).
