### ISSUE TITLE
Allow _.inRange() to be inclusive

### ISSUE THREAD

**Issue by rentalhost** [lodash/lodash#3147]
Currently, `_.inRange()` is not inclusive to `end`. Then it acts like `start <= value < end`. It is bad for some reasons, like when you need check if value is inside some percentage. For instance:

* If `x` is range of 0% to 50% (_should not be inclusive_)
* If `x` is range 50% to 100% (_should be inclusive_)

In second case, currently we should do something like `_.inRange(x, 50, 100.1)`. But it sounds bad because it could allow the value 100.05 (_okay, it do not fit on this context, but could fix in context where exists more precision/decimals_).

**Solution:** create a 4th boolean parameter that turn this function inclusive to `end` parameter. It should avoid breaking changes and hacks like that.

**Comment by jdalton** [comment]
Hi @rentalhost!

Our [_.inRange](https://lodash.com/docs/4.17.4#inRange) method is made to work with [_.range](https://lodash.com/docs/4.17.4#range).

**Comment by andreabreu-me** [comment]
maybe some optional param to be inclusive?

**Comment by rentalhost** [comment]
Unfortunatelly, it haven't. The way is you do something like `if (_.inRange(x, 50, 100) || x == 100)`

**Comment by fritx** [comment]
+1

**Comment by kwitte** [comment]
Agree, this function is named in such a way as to imply the bounds of the range are inclusive. 

Suggest renaming to better convey its exotic nature.

> **Me**:  Give me a number between 1 and 10.
> You:  10
> **Me**:  Sorry, that's not in the range.  Give me a number between 1 and 9.
> You: Is 1 in range?
> **Me**:  I'm not sure I'll look it up in lodash docs.
> You: Ok, how about 9?
> **Me**:  Yes, that is between 1 and 10. 
> You: :facepalm:

**Comment by StreetStrider** [comment]
@kwitte I got no position on this issue, but I must note that current behavior is similar to `slice`'s one:

```js
[ 0, 1, 2, 3 ].slice(0, 3) // → [ 0, 1, 2 ]
```
Note that `3` is not included in slice. I believe this is commonly made for things like:

```js
 [ X.slice(0, POS), X.slice(POS, X.length) ]
```
 to work as expected (split `X` without missing or duplicate items). Which isn't the case if both ends were included.

**Comment by kwitte** [comment]
I think this is because *slice* is an array function and so asks 'what position in the array do you want to start' and 'what position do you want to end'?

*.inRange* meanwhile is not an array function, but rather asks 'give me two numbers and I'll tell you if a third number is inside or outside'.
