### ISSUE TITLE
fp.set doesn't work

### ISSUE THREAD

**Issue by sarimarton** [lodash/lodash#3148]
`var o = {};
fp.set('prop', 5)(o);
o;`

will result in an empty object, instead of { prop: 5 }. Probably because Lodash clones arguments.

**Comment by jdalton** [comment]
Hi @sarimarton!

The `fp` flavors of methods do not mutate objects.
You'll want to store the result of `fp.set` in a variable.

**Comment by sarimarton** [comment]
Thanks @jdalton
