### ISSUE TITLE
bindAll is missing from master

### ISSUE THREAD

**Issue by wayou** [lodash/lodash#3149]
I'm wondering why the source code for `_.bindAll` is missing from master.

**Comment by jdalton** [comment]
Hi @wayou!

It's being removed from Lodash v5.

**Comment by rafde** [comment]
@jdalton I don't think most are aware of that by reviewing the docs for deprecation notices or looking at the [roadmap](https://github.com/lodash/lodash/wiki/Roadmap), which has helped in preemptively update the code base I am working on to account for removals. 
Any chance you can include more info on what else is getting removed?

**Comment by jdalton** [comment]
v5 is a major update with breaking changes as every major version update. If you're on v4 you're fine.
