### ISSUE TITLE
Auto deburr on some string methods

### ISSUE THREAD

**Issue by Lukasz-pluszczewski** [lodash/lodash#3150]
When calling some string methods all diacritics are stripped (or in fact changed to their latin counterpart - exactly the behaviour of deburr method):
```javascript
_.camelCase('zażółć gęślą jaźń') // zazolcGeslaJazn
```
It applies also to à ä æ å ā ö ø ë.

I found following methods suffer from that:
- camelCase
- kebabCase
- lowerCase
- snakeCase
- startCase
- upperCase

Following methods do not have that behaviour and work correctly:
- capitalize
- lowerFirst
- toLower
- toUpper
- upperFirst

I did not check any other methods.

EDIT: I found that all above methods use `createCompounder` which explicitly calls `deburr`. Is it the intended behaviour? It seems that in case of changing case [sic!] it is not needed for e.g. capitalize works perfect without removing diacritics.

**Comment by jdalton** [comment]
Hi @Lukasz-pluszczewski!

See https://github.com/lodash/lodash/issues/3056#issuecomment-286577169.
