### ISSUE TITLE
lodash/fp - gt

### ISSUE THREAD

**Issue by kandl** [lodash/lodash#3151]
Is the argument order in curried gt from lodash/fp intentional?
Because now it works like this:

```
import { gt } from 'lodash/fp';

const isGreaterThanZero = gt(0);
isGreaterThanZero(1) // false
```

I think argument order should be reversed.

Using Lodash 4.17.2

**Comment by simondell** [comment]
@falsyvalues Could you, or anyone else, explain why this is invalid? 

This way round seems odd to me too. Most of the other functions that compare or iterate take their operator first and their operand last. This permits currying with the operator, as in @kandl 's example. If the `gt()` and `lt()` functions would curry this way, then they would compose comfortably. 

```
// The current way means you can't do:
const longArrays = filter(flow(size, gt(5)))(myArrays)

// I imagine you'd have to do:
const longArrays = filter(array => gt(size(array), 5))(myArrays)
```

The first one seems more idiomatic.  Ramda does `gt()` the same way as Lodash, so I assume I'm missing something.

**Comment by jokka** [comment]
Why is this labeled as invalid? FP version is improperly curried for sure.

If we can all agree that `_.get(object, 'id') === get('id')(object)`, then `_.gt(1, 0) === gt(0)(1)` must be true, but it’s not (checked in 4.17.14).

**Comment by jdalton** [comment]
Hi @jokka!

I hear ya. Our argument order for `gt` is the way it is to better align with other similar libraries in the ecosystem.

**Comment by jokka** [comment]
Maybe I don’t get it, but I’d favor API quality over this “alignment”.

This just does not look right:

```javascript
const isAdult = flow(
  get('age'),
  lt(18) // ?!?!?!
);
```

Thanks @jdalton for replying anyway!

**Comment by jdalton** [comment]
Yep. Your inclination is how we initially had it before the ecosystem review. I will totally reevaluate on our next major bump though.

**Comment by jcjolley** [comment]
Did this ever get re-evaluated?  Given lodash/fp argument re-ordering rules, this is backwards and unintuitive.

**Comment by s-rayed** [comment]
Bumpppppp. This is so annoying.
