### ISSUE TITLE
isEqual and NaN

### ISSUE THREAD

**Issue by mfulton26** [lodash/lodash#3152]
`isEqual` treats `NaN` equal to `NaN` but this should not be the case:

```js
NaN == NaN;
// => false
NaN === NaN;
// => false
_.isEqual(NaN, NaN);
// => true
```

**Comment by jdalton** [comment]
Hi @mfulton26!

The [_.isEqual](https://lodash.com/docs#isEqual) method is an equivalence method so it does see `NaN` as equiv to `NaN`. This also allows you to deep compare objects that may contain an `NaN` property value.

**Comment by mfulton26** [comment]
Odd, okay. Thanks. I am still confused as to why `_.isEqual(NaN, NaN)` or even `_.isEqual({ a: NaN }, { a: NaN })` should return `true` as `NaN != NaN` (as far as equivalence is concerned).

I think it would be worthwhile to specify this behavior in the [documentation](https://lodash.com/docs/4.17.4#isEqual).
