### ISSUE TITLE
isEqual: Maps compare as equal even though insertion / value order is different

### ISSUE THREAD

**Issue by tp** [lodash/lodash#3155]
# Current Behavior

```js
const mapA = new Map([['a', 1], ['b', 2]]);
const mapB = new Map([['b', 2], ['a', 1]]);
 
_.isEqual(mapA, mapB);
// => true
```

# Expected Behavior

The above comparison should return `false`, as JS `Map`s have an explicit contract to track insertion order and hence the two maps are not equal. (One could use the `Map` as and "ordered map", but `_.isEqual` would discard those differences and just return true).

I came across this issue with a `Map` nested deep inside another data structure, so it's not easily possible to switch to a `Map` specific comparison function on the top level.

**Comment by tp** [comment]
As an aside I was surprised to how it comes to this behavior.

I dug into the code and found this function, where map value get converted to an array:
https://github.com/lodash/lodash/blob/master/.internal/mapToArray.js#L8

I checked and `_.isEqual` on array obviously correctly checks the order.

Since the above function is use [`Map.prototype.forEach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach) which should call the callback in insertion order I can't yet see why the above happens.

**Comment by tp** [comment]
An the array conversion is happening correctly:

```js
const mapA = new Map([['a', 1], ['b', 2]]);
const mapB = new Map([['b', 2], ['a', 1]]);
 
_.isEqual(mapA, mapB);

function mapToArray(map) {
  let index = -1
  const result = new Array(map.size)

  map.forEach((value, key) => {
    result[++index] = [key, value]
  })
  return result
}

console.log(JSON.stringify(mapToArray(mapA))) // "[[\"a\",1],[\"b\",2]]"
console.log(JSON.stringify(mapToArray(mapB))) // "[[\"b\",2],[\"a\",1]]"
```

**Comment by jdalton** [comment]
Hi @tp!

This is by design. Maps and sets are a collections. We treat objects with different key order but equiv values as equivs too.

**Comment by tp** [comment]
@jdalton: I get that the behavior is on purpose, but how would one then go about actually creating something that has "OrderedMap" semantics and ensuring that in tests?

Is I stated initially, if this were on the top-level of the data object if would be easy to just call the `entries()` method to get an ordered comparison.

But support for this it would be inadvisable for us to ever have `Map`s and `Set`s nested anywhere that require an ordered semantic.

(Why do I event want to use Maps with explicit ordering instead of just passing an array with key/value pairs: Because it encodes the uniqueness of the key in the data structure itself. If that approach is inadvisable I would appreciate any feedback here.)

**Comment by jdalton** [comment]
You can always use [_.isEqualWith](https://lodash.com/docs#isEqualWith) to customize map comparisons.
