### ISSUE TITLE
set() if source is defined, and/or merge() for defined source values

### ISSUE THREAD

**Issue by unenglishable** [lodash/lodash#3157]
Hello,

I've recently come across somewhat of a puzzle that I wasn't able to solve easily with lodash.  I would like to assign properties in a destination object, recursively, if the source is deeply defined.  In other words, the destination property should only be recursively created if the source has a defined value (that is *not an object*), or recursively so for its children.

Just wanted to share my experience in case others are interested in the feature.  I am using these ideas for setting (or not setting) nested configurations from environment variables, which are inherently flat.  It's also entirely possible that there's a way for me to do this that I haven't figured out 😅 

It may be a bit complicated, so let me know if there's anything I should clarify, or additional information necessary.  Thanks for taking a look!

*Sanity check note:
I'm only using these operations to set values that may have different object structures based on the type of configuration.  This type of checking could also be handled (and is currently being handled) by users of the configuration.  (eg: setting and checking `config.field.type` before processing any of the pertinent values)*

set() if defined
-----

My "dumb" implementation, using `_.set()` checks that the source value exists before calling `_.set()` for each property I want to populate.

```javascript
if (someSourceProperty) { _.set(destObject, `path`, someSourceProperty); }
```

...or more specifically in my case:

```javascript
if (process.env.SOME_CONFIGURATION_VALUE) {
  _.set(config, `some.configuration.value`, process.env.SOME_CONFIGURATION_VALUE);
}
```

With a `setIfDefined` kind of method, it would look like this:

```javascript
  _.setIfDefined(config, `some.configuration.value`, process.env.SOME_CONFIGURATION_VALUE);
```

merge() if defined
--------

The implementation for merges is not as simple, since it would have to check all object children for values before setting destination values.

```javascript
var dest = { //anything };

var source = {
  ...
  // this should be set in dest
  field: value,
  ...
  // These should not be set in dest
  otherField: {
    noValue: undefined,
    otherNoValue: undefined
  },
  ...
};

_.mergeIfDefined(dest, source);

// dest = {
//  ...
//  field: value,
//  ...
// }

// (dest does not have otherField)
```

This implementation would be quite powerful in my case, when setting configuration values:

```javascript
// process.env.VALUE = 'toplevel value';
// process.env.ANOTHER_VALUE = 'nested value';
// process.env.SOME_CONFIGURATION_VALUE = 'doubly nested value';
// process.env.OTHER_CONFIGURATION_VALUE = undefined;

// the resulting config
var config = {};

// a bunch of nested values set through process.env
var envConfig = {
  value: process.env.VALUE,
  another: {
    value: process.env.ANOTHER_VALUE
  },
  some: {
    configuration: {
      value: process.env.SOME_CONFIGURATION_VALUE
    }
  },
  other: {
    configuration: {
      value: process.env.OTHER_CONFIGURATION_VALUE
    }
  }
};

_.mergeIfDefined(config, envConfig);

// config = {
//  value: 'toplevel value',
//  another: {
//    value: 'nested value'
//  },
//  some: {
//    configuration: {
//      value: 'doubly nested value'
//    }
//  }
// };
```

**Comment by jdalton** [comment]
Thanks @unenglishable!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
