### ISSUE TITLE
_.some(collection, Object) returns true when Object is {}

### ISSUE THREAD

**Issue by tpeiffer** [lodash/lodash#3160]
We just converted from version 2.4.2 to 4.17.4 (yes, about time) and I noticed a difference in _.some that I don't see explained in the breaking changes and I can't find any closed issue on it.

### Given these values
```js
const collection = [
  {prop: 'first'}, 
  {prop: 'second'}
];
const objectToFind = {}; // yes, an empty object
```

### And this usage of 2.4.2
```js
const isFound = _.any(collection, objectToFind);
// isFound = false;  As I would expect because there are no empty objects in the collection
```

### And this usage of 4.17.4
```js
const isFound = _.some(collection, objectToFind);
// isFound = true.  Huh?  collection contains no empty objects...
```

It seems unlikely this is a bug, but it is possible.  I'm getting around it by doing a checking `_.isEqual(objectToFind, {})` before executing the _.some.

Any ideas or can you point me to the doc that explains this?

Thanks!

**Comment by jdalton** [comment]
Hi @tpeiffer!

Yes, this is by design. Since the match shorthand performs a partial deep match an empty object will match everything.
