### ISSUE TITLE
Add percentageChange and relationTable

### ISSUE THREAD

**Issue by JohnCS** [lodash/lodash#3162]
Some suggestions for Math

`percentageChange( 45, 72 )   ===  60   // from 45 to 72 is 60% change
`

`relationTable( [ 12, 23, 41, 10 ] )   === [ 29, 56, 100, 24 ]  // Assuming that the biggest number (41) is equal to 100, what are values of the others?  Useful for percentage calculations/charts/css
`

```
var percentageChange = function ( from , to ) {
    return 100 * ( (to - from) / Math.abs(from) );
};
```

```
var relationTable = function ( t ) {
    var max = Math.max.apply( this, t ), i = 0, l = t.length;
    for ( ; i < l; i++ ) {
        t[i] = Math.round( 100 * t[i] / max );
    }
    return t;
};
```

**Comment by jdalton** [comment]
Thanks @JohnCS!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
