### ISSUE TITLE
Question: Why don't lodash handle Set and Map instances?

### ISSUE THREAD

**Issue by nrser** [lodash/lodash#3163]
Why don't collection functions handle [Set][] and [Map][] instances?

Performance, preference, difficulty implementing across different environments / polyfills? I know they're relatively new but they've been in JS for a minute now and certainly seem there to stay.

I Googled around and searched the issues but the overlap in terms made it pretty difficult; didn't find anything.

[Set]: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Set
[Map]: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map

It seems weird to me that this doesn't work:

```js
const s = new Set();
s.add(1);
s.add(2);
_.each(s, x => console.log(x));
```

I wanted to ask before I started hacking in wrappers to handle them. Thanks for your time, and, of course, your great contribution with this library.

**Comment by jdalton** [comment]
Hi @nrser!

You can use spread.
```js
_.each([...s], x => console.log(x));
```

**Comment by nrser** [comment]
Yeah, of course i can use lodash once I've converted sets and maps to objects and arrays. I was wondering why lodash doesn't handle them as-is. You can iterate Set and Map without converting them into Array and Object.

**Comment by jdalton** [comment]
I don't want to special case 200+ methods for `Set` and `Map`. Their iteration is pretty basic (just `forEach`) so I'll punt and say "use spread".

**Comment by nrser** [comment]
Thanks, that answers my question, and I totally understand... Set and Map have pretty poor integration into the language in my opinion and don't seem to be widely used.
