### ISSUE TITLE
_.fillWith

### ISSUE THREAD

**Issue by fabiospampinato** [lodash/lodash#3164]
Perhaps a `_.fillWith` might be added, something like:

```
_.fillWith ( array, customizer, [start=0], [end=array.length] )
```

Where the only argument `customizer` gets passed is the current index to fill.

This would enable things like:
```
_.fillWith ( Array ( 3 ), () => [] ); // => [[], [], []]
_.fillWith ( Array ( 3 ), () => _.cloneDeep ( myObj ) ); // => [{...}, {...}, {...}]
_.fillWith ( Array ( 3 ), index => 2 * index ); // [0, 2, 4]
```

Nothing super important, but seems like a nice thing to have, especially for filling an array with non-primitives. What do you think?

**Comment by jdalton** [comment]
Thanks @fabiospampinato!

This seems like a nice addition.
We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
