### ISSUE TITLE
_.isEmptyAll()

### ISSUE THREAD

**Issue by JeffML** [lodash/lodash#3169]
I find the need for an isEmptyAll() method for checking if one or none of several data properties exist.  Missing properties could be null, undefined, or [].

The closest I can think of to getting what I want is something like:

```
const fields = [...]

var allEmpty = [fields].every(f=>{ return _.isEmpty(f);}) 
```

which isn't bad (in ES6), but would be more convenient if it was built into lodash:

`var allEmpty = _.isEmptyAll(fields);`

**Comment by davezuko** [comment]
What about `_.every(_.isEmpty)` with [lodash/fp](https://github.com/lodash/lodash/wiki/FP-Guide)?
