### ISSUE TITLE
_.isInteger()

### ISSUE THREAD

**Issue by maicong** [lodash/lodash#3170]
`_.isInteger(0.3)` return`true`, but `Number.isInteger(0.3)` return `false`

```js
console.log(0.3,  _.isInteger(0.3),  Number.isInteger(0.3)) // -> 0.3 true false
```

**Comment by poldixd** [comment]
Not in my browser Chrome 58.0.3029.110 (64-bit) and lodash@4.17.4

```
console.log(0.3,  _.isInteger(0.3),  Number.isInteger(0.3))
0.3 false false
```

**Comment by jscheffner** [comment]
Also not with Node.js

**Comment by jdalton** [comment]
Hi @maicong!

Thanks for taking the time to open an issue. I can't seem to repro this on 4.17.4.
If you have more details or narrow down a repro feel free to ping back in.

**Comment by maicong** [comment]
I know why, this is a feature of `lodash-webpack-plugin`. I have been enabled. Tks!

**Comment by jdalton** [comment]
Be sure to enable the "coercions" feature set. I'll patch it so that will auto-enable it if `isInteger` is used.
