### ISSUE TITLE
fp.placeholder doesn't play well with fp.flow

### ISSUE THREAD

**Issue by davidgoli** [lodash/lodash#3171]
```js
const normalizeKeyName = fp.flow(
  fp.replace(fp.placeholder, ''),
  fp.replace(/^Id$/, 'userId')
)
```

Expected:

```js
> normalizeKeyName('foo ')('hello foo world')
'hello world'
```

Actual:

```
> normalizeKeyName('foo ')
'functionWrappedWithAryCurryPartialReargVarNArgumentsTZuN0Return3NLengthTTReplaceN1N2'

> normalizeKeyName('foo ')('hello foo world')
TypeError: normalizeKeyName(...) is not a function
    at repl:1:24
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:334:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:531:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:189:7)
    at REPLServer.Interface._onLine (readline.js:238:10)
    at REPLServer.Interface._line (readline.js:582:8)
```

But:

```js
> normalizeKeyName('foo ', 'hello foo world')
'hell world'
```

```js
const normalizeKeyName2 = fp.flow(
  fp.replace(fp.placeholder, '')
)
```

```js
> normalizeKeyName2('foo ')('hello foo world')
'hello world'
```

**Comment by davidgoli** [comment]
I would expect using `placeholder` would increase the arity of the curried function but that doesn't appear to be the case; instead, calling the curried function with a single arg appears to execute the entire flow, but the placeholder is not fulfilled.

**Comment by jdalton** [comment]
Flow has no idea of the arity of the methods it consumes. It wasn't designed to.

**Comment by davidgoli** [comment]
It appears `fp.flow` is not curried and it also returns a function which is not curried, which is not expected given the documentation's description of "its methods wrapped to produce immutable auto-curried iteratee-first data-last methods". I would also say the case can be made that the design should either be changed or documented: `fp.flow` is a NON-curried method that returns a function of fixed arity 1.

Having read the documentation closely, however, it is not at all clear that this is by design. It seems that `flow` should be able to return a *curried* function with an arity equal to the sum of the placeholders used in its consumed methods plus 1. This would enable much more powerful function composition using fp. I would be happy to submit a pull request with this behavior.
