### ISSUE TITLE
partition an object?

### ISSUE THREAD

**Issue by mockdeep** [lodash/lodash#3172]
I'm finding myself in need of a function that partitions an object into two, e.g.:

```js
const sourceObj = { a: 'b', c: 'd' };
const [obj1, obj2] = _.partition(sourceObj, (value, key) => key === 'a');
// obj1 -> { a: 'b' }
// obj2 -> { c: 'd' }
```

This would help sift through an object and pick out bits that need different treatment. For example, when updating a client-side model, some attributes I want to persist to the server and others I want to only update client side. Looks like it would combine something like `_.omitBy` and `_.pickBy` into one. The current equivalent:

```js
const sourceObj = { a: 'b', c: 'd' };
const obj1 = _.pickBy(sourceObj, (value, key) => key === 'a');
const obj2 = _.omitBy(sourceObj, (value, key) => key === 'a');
```

**Comment by jdalton** [comment]
Thanks @mockdeep!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by stereokai** [comment]
Any news...?

**Comment by DVLP** [comment]
just bumping popularity here

**Comment by zslucky** [comment]
same issue, need to partition object by key...

**Comment by IlCallo** [comment]
I'll leave here a typed implementation (TS 2.9), based on @DVLP one.
It can probably be enhanced further

```typescript
function partitionObject<T extends { [ index in K ]: any }, K extends keyof T>(
    obj: T,
    filterFn: (value: any, key: keyof T) => boolean
): [ { [ index in K ]?: T[ K ] }, { [ index in K ]?: T[ K ] } ] {
    // Object.keys(obj) must be explicitly casted to K[] when using TS2.9+ because it returns only strings keys,
    //  but TS recognizes also 'symbol' and 'number' in keyof
    return (Object.keys(obj) as K[]).reduce((result, key) => {
        result[ filterFn(obj[ key ], key) ? 0 : 1 ][ key ] = obj[ key ];
        return result;
    },
        // Must be re-typed due to poor tuple recognition problems in TS
        ([ {}, {} ] as [ { [ index in K ]?: T[ K ] }, { [ index in K ]?: T[ K ] } ]));
}
```

**Comment by PaulSearcy** [comment]
Ran into this issue as part of filtering through form submission fields to ensure that I'm recording valid input fields into their proper columns in a SQL table.

 While at the same time recording and  serializing additional fields, special cases, into a catch all column something like 'AdditionalFields' .

**Comment by natew** [comment]
Very useful for React, partitioning props is a common pattern.

**Comment by fedemengo** [comment]
Would love to have this
