### ISSUE TITLE
value = (comparator || value !== 0) ? value : 0; does it work?

### ISSUE THREAD

**Issue by fi3ework** [lodash/lodash#3175]
``` javascript
value = (comparator || value !== 0) ? value : 0;
```
in https://github.com/lodash/lodash/blob/master/.internal/baseDifference.js#L46
what does this sentence mean? Is it useless? :-)

**Comment by jdalton** [comment]
Hi @fi3ework!

That bit ensures that a positive `0` is used because `-0` is a thing in JS.

**Comment by fi3ework** [comment]
@jdalton 
yeah, I know the exist of -0, but why change -0 to +0 ? Why not just use -0 directly? :-)

**Comment by jdalton** [comment]
Because internally we use `Set` for deduping and `Set` doesn't distinguish between the two.
