### ISSUE TITLE
Slash configuration

### ISSUE THREAD

**Issue by franciscop** [lodash/lodash#3176]
Hi, lodash is a great reference as a super-high quality package and I love many of the design decisions that you made. Speciall I like being able to do:

```js
const kebabCase = require('lodash/kebabCase');
```

And similar. In creating [the server.js package](https://github.com/franciscop/server) I am trying to achieve something similar for:

```js
const router = require('server/router');
```

Is setting all of the files to be included like this in the root the only way that you found of achieving this? Or are all the files in *lodash* on the root for other reasons? My files are in `/src` and I'd like to be able to include them straight from there as in the code examples above, but if it's not possible I'd follow lodash file configuration and just put those in the root.

**Comment by jdalton** [comment]
In other versions I had put files into sub folders but found that the sub folders were hard to remember and that keeping things on root simplified imports.
