### ISSUE TITLE
Documentation for `slice` does not contain examples

### ISSUE THREAD

**Issue by AesaKamar** [lodash/lodash#3177]
As seen here, most other methods have examples given to illustrate their use and behavior. 
https://lodash.com/docs/4.17.4#slice

I think a simple example would be useful for readers, and would feel more consisted with the rest of the documentation.  

```javascript
//Examples:
var array = ['Banana', 'Orange', 'Lemon', 'Apple', 'Mango'];

_.slice(array, 1, 3)
// => ['Orange','Lemon']

_.slice(array, 0, 5)
// => ['Banana', 'Orange', 'Lemon', 'Apple', 'Mango']
```

**Comment by jdalton** [comment]
Thanks for the heads up @AesaKamar!

This method will likely not make the cut for Lodash v5.

**Comment by realtebo** [comment]
I added that this method changes the inpput array and also return ... array ... with what?

Docs is definetively needed !
