### ISSUE TITLE
toLower performs join while used in chain wrapper

### ISSUE THREAD

**Issue by matanlb** [lodash/lodash#3178]
## Description
Using the `toLower()` as part of a chain results in a join+toLower effect.

## Example
```javascript
let stringArray = ['START', 'middle', '', 'End', ''];
let result = _.chain(stringArray)
  .reject(_.isEmpty)
  .toLower()
  .value();
console.log('result', result);
``` 
### Expected Result
```javascript
[ 'start', 'middle', 'end' ]
```
### Actual Result
```javascript
'start,middle,end'
```

## Usage
Usage is pretty simple, wherever batch string manipulation is needed. (parsing and transforming data files in my case).

While this is the behavior of `_.toLower` when used directly and passing in an array of string, the notion of chain is that values are  "piped" one-by-one through the methods unless the method is an aggregator-method by nature (like `min`/`max`/`reduce` etc). I don't think this is the case for `toLower`, especially since the current result can be achieved by adding `join(',')` as the next step in the chain.

**Comment by jdalton** [comment]
Hi @matanlb!

The [toLower](https://lodash.com/docs#toLower) is a string method and so coerces values to a string. An array coerced to a string will look like a join.
