### ISSUE TITLE
find.js use to findIndex.js,But i not found findIndex.js

### ISSUE THREAD

**Issue by zhangfu-git** [lodash/lodash#3179]

**Comment by jdalton** [comment]
Hi @zhangfu-git!

Make sure you're in the appropriate version of lodash.

**Comment by zhangfu-git** [comment]
thank you~ I am learning github code，I should take a version of the study

**Comment by iki** [comment]
@jdalton Interesting, I also don't see `findIndex.js` in current master, both when browsing on github, or after checkout. At the same time, the current `find.js` imports from `./findIndex.js`. Where does it come from? Can you please link the source?
