### ISSUE TITLE
_.find is returning different results between browser and node

### ISSUE THREAD

**Issue by JemiloII** [lodash/lodash#3180]
Chrome = 58.0.3029.110;
Node = 6.9.2;
Lodash = 4.17.4
Used lodash-cli to build.

In node:
```js
_.find([{n:1},{n:2}], {n:3});
> []
```
In browser

```js
_.find([{n:1},{n:2}], {n:3});
> undefined
```

I don't think that this is suppose to happen... Am I doing something wrong?

**Comment by jdalton** [comment]
> I don't think that this is suppose to happen... Am I doing something wrong?

Probably. In your browser one are you using a webpack plugin like `lodash-webpack-plugin`? If so be sure to enable `shorthands` or better yet avoid them in favor of the long form.

```js
_.find([{n:1},{n:2}], o => o.n === 3)
```

**Comment by JemiloII** [comment]
I figured it out, I had to rebuild node. The console was acting strangely. Sorry for the confusion. It works as expected now.
