### ISSUE TITLE
_.isValidEnumValue

### ISSUE THREAD

**Issue by michaeljota** [lodash/lodash#3181]
I made a little function to check if a given value belongs to a enum like object, and I would like to share it here to see if you would like to add it. 

```js
function isValidEnumValue(enumlike = {}, value = '') {
  return Object.keys(enumlike)
    .map(key => enumlike[key])
    .some(type => type === value);
}
```

It even works with the objects that Typescript transpiles to JavaScript, besides the usual objects enum-like that are being used regularly. I search for this before and did not find anything, so if there is something like this, I'm sorry.

**Comment by jdalton** [comment]
Thanks @michaeljota!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
