### ISSUE TITLE
floating random

### ISSUE THREAD

**Issue by loveLibra** [lodash/lodash#3183]
I found this in `random`
```javascript
if (floating || lower % 1 || upper % 1) {
    const rand = nativeRandom()
    const randLength = `${ rand }`.length - 1
    return Math.min(lower + (rand * (upper - lower + freeParseFloat(`1e-${ randLength }`)), upper))
 }
```
what's the meaning of **freeParseFloat(`1e-${ randLength }`)** here? what if it's removed?

**Comment by jdalton** [comment]
It's basically:
```js
parseFloat('1e-' + randLength)
```
It's using [exponential notation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toExponential).

**Comment by loveLibra** [comment]
thanks, @jdalton, I knew the syntax sure. My doubts are, what's the effect of this float number generated by **freeParseFloat(1e-${ randLength }) ** in this sentence.

`rand` between 0 and 1, so `lower + rand * (upper -lower) ` less than upper definitely,why need **freeParseFloat(1e-${ randLength }) ** here?

**Comment by jdalton** [comment]
Try it in your dev console and see what it does.
