### ISSUE TITLE
Is there some kind of "nearest" function for collections?

### ISSUE THREAD

**Issue by idchlife** [lodash/lodash#3186]
Imagine you have array of objects, and you would want to get elements nearest by some parameter:

```javascript
const objects = [{amount: 30}, {amount: 35}, {}];

// will be [{amount: 30}]
const nearest = lodash.nearest(objects, {amount: 31}, 1);
```

where lodash.nearest = function(collection, params, amount) { ... }

**Comment by jdalton** [comment]
Hi @idchlife!

There isn't. If you'd like help implementing one you can [visit our chat](https://gitter.im/lodash/lodash).
