### ISSUE TITLE
Update _.clamp documentation to denote `lower` as a required param

### ISSUE THREAD

**Issue by reddyesha** [lodash/lodash#3190]
Based on changes from this PR: https://github.com/lodash/lodash/commit/868fd1253b18699d81fef478ad13218bbccbfd05

`lower` is no longer an optional param for `_.clamp`. [Documentation](https://lodash.com/docs/4.17.4#clamp) should be updated to make this clear.

**Comment by jdalton** [comment]
Hi @reddyesha!

This is a change in the master (unpublished) version and the inline docs are updated for that.
