### ISSUE TITLE
`_.every` and `_.some` naming inconsistency

### ISSUE THREAD

**Issue by radekn** [lodash/lodash#3191]
In previous versions of lodash, there were more aliases and `_.every` was the same as `_.all` and `_.any` was the same as `_.some`. These aliases were dropped, and now there is only one of each of them, and that's fine, but I find the particular choice of which ones to keep very surprising.

I would argue that, linguistically, these words form two distinct groups, "every" and "any" in one of them (because we tend to say "every **x**" and "any **x**"), and "all" and "some" (and, arguably, "none") in the other one (because "all _of_ **xs**", "some _of_ **xs**", and "none _of_ **xs**). But instead of `_.every` `_.any`, or `_.all` `_.some` `_.none` (if I were to choose, I'd pick the latter), we have `_.every` `_.some`.

It might feel nitpicky, and it is, but it strikes me as a departure from what appears to be the Obviously Right Choice&trade;. Is there any good reason for this?

**Comment by jdalton** [comment]
Keeping aliases to a minimum helps focus the API and avoid confusion. We based our names off of those that [exist in the language](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every?v=example).
