### ISSUE TITLE
Question - Importing single function with typescript, lodash, jest

### ISSUE THREAD

**Issue by vojty** [lodash/lodash#3192]
I am writing a library using typescript, jest and lodash and I would like to ship it as 2 modules -
 commonjs (for webpack 1) and with es2015 modules (for webpack 2 with tree-shaking).

What i tried:
1. `import { cloneDeep } from 'lodash';` includes whole lodash, that's no go for me
2. `import cloneDeep = require('lodash/cloneDeep');` syntax, but that can't be compiled to es2015
3. `import cloneDeep from 'lodash/cloneDeep';` doesn't work (error TS1192: Module @types/lodash/cloneDeep/index has no default export)
4. `import { cloneDeep } from 'lodash/cloneDeep';` or `import * as cloneDeep from 'lodash/cloneDeep';` doesn't work (error TS2497: Module @types/lodash/cloneDeep/index resolves to a non-module entity and cannot be imported using this construct)
5. `import * as cloneDeep from 'lodash-es/cloneDeep';` can be compiled and looks good BUT jest (I am using jest + ts-jest) fails with `SyntaxError: Unexpected token import`. This can be fixed with this approach https://stackoverflow.com/questions/42260218/jest-setup-syntaxerror-unexpected-token-export BUT then everyone with commonjs modules will have to resolve it in their setup since lodash-es is my dependency

I ended up with  `import * as cloneDeep from 'lodash.clonedeep';` which finally worked.
Is this the only way to do this? Am I missing something? If it's more typescript related problem, feel free to close this.

**Comment by jdalton** [comment]
Hi @vojty!

It looks like a TypeScript support issue as
```js
import cloneDeep from 'lodash/cloneDeep'
```
should work fine and is how it's done for folks using Babel. Folks using Babel can also use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash).

**Comment by xaviergonz** [comment]
I know this is really old, but try this instead:
```import cloneDeep = require('lodash/cloneDeep');```

**Comment by hipertracker** [comment]
Import assignment cannot be used when targeting ECMAScript modules. The should be ```const sortBy = require('lodash/sortBy')```

**Comment by gangsthub** [comment]
@hipertracker you have to adjust your `tsconfig.app.json` to have the `compilerOptions.module` value to accept this syntax: I think `esnext` will do the trick ;)

**Comment by hipertracker** [comment]
@gangsthub not for that case. After switching to `esnext`:

- For `import cloneDeep from 'lodash/cloneDeep'` I get: `[ts] Module '"node_modules/@types/lodash/cloneDeep"' has no default export.`

- But for for `import * as cloneDeep from 'lodash/cloneDeep'` I get another error" `[ts] Module '"node_modules/@types/lodash/cloneDeep"' resolves to a non-module entity and cannot be imported using this construct.`

node_modules/@types/lodash/cloneDeep.d.ts is:
```typescript
import { cloneDeep } from "./index";
export = cloneDeep;
```
According to [TypeScript docs](https://www.typescriptlang.org/docs/handbook/modules.html):

> "When importing a module using export =, TypeScript-specific import module = require("module") must be used to import the module."

But for unknown reason, I cannot use their recommendation syntax:

```typescript
import cloneDeep = require('lodash/cloneDeep')
```

This is what I get here:

> [ts] Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

**Comment by hipertracker** [comment]
Finally, 

```typescript
import cloneDeep = require('lodash/cloneDeep')
```

works only with `tsconfig.json`:
```javascript
{
  "compilerOptions": {
    "module": "commonjs"
  }
}
```

**Comment by gangsthub** [comment]
Sorry, misunderstood that. I will try this.

**Comment by yanni4night** [comment]
But that's not friendly to rollup.

**Comment by oleersoy** [comment]
Noticed that lodash uses default exports ... and just curious whether ... even though it's not typescript ... it will run into these types of refactoring issues:
https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html

**Comment by no23reason** [comment]
@vojty Hi, as stated before
```
import cloneDeep from 'lodash/cloneDeep'
```
but you have to have `"allowSyntheticDefaultImports": true,` in your `tsconfig.json`.

**Comment by kctang** [comment]
I managed to run my app using:

```
// using the single function lodash package
import cloneDeep from 'lodash.clonedeep'
```

... but it fails in Jest unit test - `TypeError: lodash_clonedeep_1.default is not a function`.

After searching a bit, this is the solution i found: `"esModuleInterop": true` in `tsconfig.json`. Details [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html) and I found this solution form [here](https://github.com/kulshekhar/ts-jest#supports-synthetic-modules).

**Comment by nadavsinai** [comment]
enabling esModuleInterop might be helpful for folks that can upgrade to Typescript 2.7 and newer but for those the are stuck with older versions the sad truth is that there is not solution , or is there? @jdalton

**Comment by cmawhorter** [comment]
@yanni4night and my future self: the `import/const blah = require()` doesn't work with rollup but this would: `import { whatever } from 'lodash'`.  The concern OP suggests in 1 doesn't matter for rollup bc it's smart enough to only include what it needs.
