### ISSUE TITLE
Unexpected _.method behaviour when function is not defined

### ISSUE THREAD

**Issue by dcastro** [lodash/lodash#3193]
Although this is not formalized in the docs, I expected the following law to hold

> for any object `x` and method `f`, `_.method('f')(x)` === `x.f()`

However, this does not hold for `var x = {}`:

```
> x.f()
VM451:1 Uncaught TypeError: x.f is not a function

> _.method('f')(x)
< undefined
```

This behaviour is rather [surprising](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), and it caused a couple of my tests to report false negatives.

Is it by design? Is there a chance we could see this being changed in a future version?

**Comment by jdalton** [comment]
Hi @dcastro!

This is by design. Lodash tries to avoid erroring for missing or nullish properties when possible.
If you like a simpler form you can use ES2015 arrow functions.

```js
(x) => x.f()
```

**Comment by dcastro** [comment]
Thank you for the quick response @jdalton.

Unfortunately, we're not using ES2015 on this project yet, so arrow functions are not an option for now. Welp, back to basics I guess.

Thanks again

**Comment by jdalton** [comment]
Ok, although with Babel or TypeScript ES2015 syntax is doable.
