### ISSUE TITLE
Add `fromPairsDeep`

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash#3194]
We have `zipObject` and `zipObjectDeep`, but only `fromPairs` and no `fromPairsDeep`. The API should be consistent.

**Comment by jdalton** [comment]
Thanks @daedalus28!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
Do you have an idea of what the expected output would be?

**Comment by jdalton** [comment]
Thanks @daedalus28!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
Do you have an idea of what the expected output would be?

**Comment by daedalus28** [comment]
It would have the a similar output as `zipObjectDeep` and would look something like this:

```js
_.fromPairsDeep([['a.b', 1], ['c.d', 2]]) == { a: { b: 1 }, c: { d:2 } }
```

**Comment by blackdynamo** [comment]
This would be great. I have been playing around with all the lodash options and this seems to be missing. I need the functionality that @daedalus28 listed. I want to translate dot paths to full nested objects from pairs. Below is perfect:

```
_.fromPairsDeep([['a.b', 1], ['c.d', 2]]) // { a: { b: 1 }, c: { d: 2 } }
```
