### ISSUE TITLE
FP uniq() not removing duplicate within compose()

### ISSUE THREAD

**Issue by JasonSooter** [lodash/lodash#3195]
```
const filter = require('lodash/fp/filter');
const map = require('lodash/fp/map');
const uniq = require('lodash/fp/uniq');
const startCase = require('lodash/fp/startCase');
const sortBy = require('lodash/fp/sortBy');
const compose = require('lodash/fp/compose');
const isUndefined = require('lodash/fp/isUndefined');
const isNull = require('lodash/fp/isNull');

const isValid = val => !isUndefined(val) && !isNull(val);
const names = [
  'alonzo church',
  'Haskell curry',
  'stephen_kleene',
  'John Von Neumann',
  'stephen_kleene'
];

console.log(uniq(names));

const formatNames = compose(
  sortBy(x => x),
  map(startCase),
  uniq(),
  map(s => s.replace(/_/, ' ')),
  filter(isValid)
);
console.log(formatNames(names));
```

My first console.log results in the duplicate being removed but the 2nd within the composed function does not remove the duplicate. What do I happen to be missing? Thanks for any help

**Comment by jdalton** [comment]
Hi @JasonSooter!

The `uniq` method itself is not curried since it receives only 1 param. So you should pass it as `uniq,` instead of `uniq(),`.

**Comment by JasonSooter** [comment]
Hi @jdalton,

Thanks for your help! 

I've got some learning to do. The 1 param makes sense but when I brought in ramda's uniq() function while troubleshooting it ended up working. Digging into the difference should be enlightening.

Have a good night ;-)

Jason
