### ISSUE TITLE
Operation between arrays

### ISSUE THREAD

**Issue by Tiagoperes** [lodash/lodash#3197]
Hello guys, this is not actually an issue, but rather a request. I usually find myself in need of making an operation between the elements of multiple arrays, for example, sometimes I need to sum the elements of array A with elements of array B, obtaining array C, which is [a[0]+b[0], a[1]+b[1], ..., a[i]+b[i], ..., a[n]+b[n]]. See the following numeric example:

    A: [1,3,5]
    B: [4,7,8]
    --------------
    C: [5,10,13]

In my code, I currenty use the following operations between arrays _.add, _.subtract, _.multiplicate, _.divide, _.gt and _.lt. I don't know if there is already a method for this, I couldn't find anything in the documentation. To achieve this I extended Lodash with the following method:

    _.applyOperationBetweenArrays = function () {
        var operation = _.head(arguments),
            arrays = _.tail(arguments),
            result = _.clone(_.head(arrays));
    
        for (let i = 1; i < arrays.length; i++) {
          for (let j = 0; j < arrays[i].length; j++) {
            result[j] = operation(result[j], arrays[i][j]);
          }
        }
    
        return result;
      };

To perform a sum between arrays A and B, for example, I call ```_.applyOperationBetweenArrays(_.add, A, B)```. I think this might be usefull in many cases and it would be very cool to see it as part of the core library.

**Comment by peteranny** [comment]
It looks like an extended version of `_.zip`

**Comment by peteranny** [comment]
`zipWith` seems to achieve what you need?
https://lodash.com/docs/#zipWith

**Comment by Tiagoperes** [comment]
Cool, zipWith is simmilar enough to the function I proposed. I'm sorry I didn't find it in the docs before.
