### ISSUE TITLE
_.and()

### ISSUE THREAD

**Issue by iddan** [lodash/lodash#3199]
Applies an array of comparators on a value. If one fails returns false otherwise returns true.

```JavaScript
const obj =  { name: 'Dan', age: 29 };

fp.and([
    _.matches({ name: 'Dan' }),
    (dan) => dan.age > 27
], obj) // => true
```

**Comment by jdalton** [comment]
Thanks @iddan  !

I'm fairly certain this has been requested before (and has another issue tracking it). That said, GitHub search is bad around "and" and "or" so it's hard to say for sure. We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by StreetStrider** [comment]
#1072

**Comment by iddan** [comment]
Thanks, tried to search but as you said @jdalton it is hard to locate
