### ISSUE TITLE
_.keys(object) - doc not correct?

### ISSUE THREAD

**Issue by AjaxSolutions** [lodash/lodash#3200]
`_.keys(new Foo);
// => ['a', 'b'] (iteration order is not guaranteed)`

I believe this issue has been addressed in ES6.

ES6 enforces object property traversal order. All string keys are traversed in the order they were added to the object.

ES5 didn't define the enumeration order of object properties. This was left to the discretion of JS engine vendors.

**Comment by jdalton** [comment]
Since we don't know the environment you're running `_.keys` in we cannot guarantee order.
