### ISSUE TITLE
isBlank or isEmptyOrNull method

### ISSUE THREAD

**Issue by isergey** [lodash/lodash#3201]
I need like this behavior.
_.isBlank(undefined) : true
_.isBlank(null) : true
_.isBlank(NaN) : true
_.isBlank('') : true
_.isBlank('a') : false
_.isBlank(0) : false
_.isBlank(1) : false
_.isBlank({}) : true
_.isBlank([]) : true
_.isBlank({foo: 'bar'}) : false
_.isBlank(['foo', 'bar']) : false

In lodahs exist two method: isEmty and isNull. But often requires isEmptyOrNull comparation. Why this method is not implemented? Thanks a lot!

**Comment by jdalton** [comment]
Hi @isergey!

The name `isBlank` is a bit overloaded. I think it's 👌 at the moment to create a mixin for your needs.

**Comment by daedalus28** [comment]
You can use `isBlank` from futil-js:

https://github.com/smartprocure/futil-js#isblank
https://smartprocure.github.io/futil-js/#api-lang-isblank
https://github.com/smartprocure/futil-js/blob/master/src/lang.js#L17
