### ISSUE TITLE
Is there `splice` func for string.

### ISSUE THREAD

**Issue by hustcc** [lodash/lodash#3202]
We hava `splice` func for Array.
```js
[1, 2, 3].splice([1,1,0]); // insert element=0 at index =1, and delete 1 element.

will get [1, 0, 3]
```

Is there some function like Array.splice on String?

```js
// simple code.
function splice(str, index, del, element) {
    return str.substring(0, index) + element + str.substring(index + del);
}
```

**Comment by jdalton** [comment]
Hi @hustcc!

There isn't. My preferred string method for such things is `String#slice`.

**Comment by jamespedid** [comment]
It's also worth mentioning that a such a function cannot be created on Javascript, provided you want to preserve the fact that the splice function for arrays mutates the calling array. Javascript strings are immutable, and cannot be mutated in this way. The return value of Array#splice is the elements that were removed.
