### ISSUE TITLE
Don't cache function result in _.once() when error thrown

### ISSUE THREAD

**Issue by edwmurph** [lodash/lodash#3204]
If the first invocation of a once'd function happens to return an error then every subsequent call will also just get that cached error. It's possible that some implementations might want that error to be cached but I think most use cases wouldn't. Maybe a good compromise would be to add a flag to indicate whether or not to cache the function result if an error was thrown? The same also applies to _.memoize().

**Comment by jdalton** [comment]
Hi @edwmurph!

Our `once` implementation is unlikely to change. That said, you can always create a custom [mixin](https://lodash.com/docs/#mixin).

**Comment by edwmurph** [comment]
@jdalton Why not? Just curious.

**Comment by jdalton** [comment]
It's been the way it's been for roughly 8 years.
