### ISSUE TITLE
Introduce a reduceWhile function?

### ISSUE THREAD

**Issue by jamespedid** [lodash/lodash#3205]
Hello. I can't seem to find this as a suggestion, so sorry if it is a duplicate, but I don't think this is quite missing in the library. The purpose of this feature request is to have a reduceWhile function.

Motivation:
We have a data structure that we are sifting through and concatenating the text, but we want to stop after the text has reached 150 characters; we just want to return the shortened string. Right now we are doing a map to the text property, a concatenation, and then a truncation from lodash. However, this seems gratuitious.

```javascript
let myObjs = [{text: 'this has some length'}, {text: 'this has more length'}, {text: 'are we at 150 yet?'} ...]
let shortenedString = lodash.chain(myObjs).map(mo => mo.text)
  .join(' ')
  .truncate({ length: 150 })
  .value();
```

We would like to so some sort of reduce pattern, but using reduce will still iterate over the entire array, and this is a little wasteful. We also looked into transform, but that seems to miss the mark for this use case because it would mutate the input array and not allow a string to be stored without using additional structure. 

My suggestion is simple: a reduceWhile function that will behave similarly to takeWhile in that it will continue to apply the accumulator function to a result while the returned value of the accumulator satisfies a condition.

```javascript
// reduceWhile(collection, accumulatorFn, predicate, accumulator) 
let shortenedString = lodash.reduceWhile(myObj, (shortString, mo) => {
   return shortString + mo.text.substring(0, 150 - shortString.length);
}, (shortString, mo) => shortString.length < 150, "");
```

Thanks for reading and I hope the intention is clear.

**Comment by jdalton** [comment]
Thanks @jamespedid!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
