### ISSUE TITLE
Partitioner - Splitting Array into Even # Buckets (Chunkify)

### ISSUE THREAD

**Issue by alohaninja** [lodash/lodash#3206]
`lodash` should [add a new method  to handle splitting an array into equal buckets of N indexes](https://stackoverflow.com/questions/40166199/split-a-group-array-of-items-into-n-groups) => the existing `chunk` method splits an array by N items in each new array index, 

.NET has a [`Partitioner`](https://msdn.microsoft.com/en-us/library/system.collections.concurrent.partitioner(v=vs.110).aspx)  class which achieves this when parallelizing items for batch processing scenarios or map/reduce operations.

**Comment by jdalton** [comment]
Thanks @alohaninja!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
