### ISSUE TITLE
Consider changing default _.set behavior for v5

### ISSUE THREAD

**Issue by nickclaw** [lodash/lodash#3207]
I know you addressed this in #1316 but I can't comment in that one. While I think that it makes sense for setting numeric keys in existing arrays (duh), it's almost always a bug to create sparse arrays like `[undefined x 15, 'foo']`, especially considering how lodash functions differ from native array methods when handling them. Cheers!

**Comment by levithomason** [comment]
There are a lot of issues and SO posts about this.  Curious as to why a non-existent numeric key results in an array instead?  I cannot think of a use case for this.
