### ISSUE TITLE
FP Guide does not exist

### ISSUE THREAD

**Issue by trustedtomato** [lodash/lodash#3209]
The title is self-explanatory.
[The Guide](https://github.com/lodash/lodash/wiki/FP-Guide) doesn't exist.

**Comment by TrySound** [comment]
@pengzhiqiang Why you removed fp guide?

**Comment by pengzhiqiang** [comment]
it's my fault,i'm so sorry.

**Comment by TrySound** [comment]
I reverted page by hands.)

**Comment by trustedtomato** [comment]
OK, I'll close the issue.
