### ISSUE TITLE
flatMapDeep: misunderstanding or bug?

### ISSUE THREAD

**Issue by legendar** [lodash/lodash#3210]
```
_.flatMapDeep(
  [{
      id:1,
      childs: [{
          id: 2,
          childs: [{
              id: 3,
              childs: []
          }]
      }]
  }],
  item => [item, item.childs]
).map(item=>item.id)
```

This example returns returrns `[1,2]`. I have test it locally and in chrome dev tools on lodash.com (both v 4.17.4)
I supposed it should return `[1, 2, 3]`. So is it a bug?

**Comment by jdalton** [comment]
Hi @legendar!

Our flat map implementation is just `map` + `flatten`. In the case of [_.flatMapDeep](https://lodash.com/docs/4.17.4#flatMapDeep) it's performing `map` and then a recursive flatten.

**Comment by legendar** [comment]
so flatMapDeep is just and short alias for map+flattenDeep, and there no sense to have this separate method:
```
_(array).map(iteratee).flattenDeep().value()
```

for those who find solution for my question:
```
function flatMapDeep(array, iteratee) {
  if(!array || array.length == 0) return []
  return array.concat(
    flatMapDeep(_.flatten(array.map(iteratee)), iteratee)
  )
}
flatMapDeep(array, item => item.childs))
```

**Comment by jdalton** [comment]
> so flatMapDeep is just and short alias for map+flattenDeep, and there no sense to have this separate method

The reason it's a separate method is that it's a common enough request to have one.
