### ISSUE TITLE
_startCase is removing umlauts (äöü)

### ISSUE THREAD

**Issue by MrStobbart** [lodash/lodash#3211]
Hi, 

I was using _.startCase on a string and experienced a remove of umlauts (äöü).

Here is an example of what I mean:
http://requirebin.com/?gist=9872293acf147cc2280aa924e9f26c74

**Comment by jdalton** [comment]
Hi @MrStobbart!

This is by design for Lodash 4 and below. In v5 we'll stop [deburring](lodash.com/docs/#deburr) case methods.
