### ISSUE TITLE
Rationale question about _.isArrayLike & _.isArrayLikeObject

### ISSUE THREAD

**Issue by searls** [lodash/lodash#3215]
I'm trying to figure out the rationale behind `isArrayLike` & `isArrayLikeObject`. Judging by their names, I reached for it on the presumption that it would cover some not-quite-array-but-array-like iterable things (like, say, `arguments` objects or custom types that extend `Array`), but the actual behavior is surprising to me, so I'd love to hear the intention from @jdalton or other maintainers.

Here's the example that surprised me:

```js
_.isArrayLikeObject('abc') // false
_.isArrayLike(new String('abc')) // true
_.isArrayLikeObject(new String('abc')) // true
```

In my particular case, this means these method aren't suited for my needs, but I'm curious what the perceived benefit of the function is, if it's treating object/boxed strings as array-like

**Comment by jdalton** [comment]
Hi @searls!

Check out the descriptions of [_.isArrayLike](lodash.com/docs/#isArrayLike) and [_.isArrayLikeObject](https://lodash.com/docs/4.17.4#isArrayLikeObject). That pretty much covers it. One works with primitives one adds an object check to the mix.
