### ISSUE TITLE
isEmpty returns true when a number is passed in

### ISSUE THREAD

**Issue by hellojosh** [lodash/lodash#3216]
`_.isEmpty(1234)` is true
`_.isEmpty('1234')` is false

This doesn't seem right to me.

**Comment by jdalton** [comment]
Hi @hellojosh!

This is by design. The [_.isEmpty](https://lodash.com/docs#isEmpty) method checks if a collection-like value is empty. Since `_.forEach(1234, func)` will be treated as an empty collection `isEmpty` returns `true`.
