### ISSUE TITLE
_ not defined for orderBy using npm package

### ISSUE THREAD

**Issue by ilkovulchev** [lodash/lodash#3217]
Hello,

I am trying to use the orderBy function in vuejs, but it says that _ is not defined. I only imported the lodash orderBy package, since this is the only thing i need. I am also trying this with the example from the documentiation https://lodash.com/docs/4.17.4#orderBy:

var orderBy = require('lodash.orderby');

var users = [
{ 'user': 'fred',   'age': 48 },
{ 'user': 'barney', 'age': 34 },
{ 'user': 'fred',   'age': 40 },
{ 'user': 'barney', 'age': 36 }
];
console.log(users);

// Sort by `user` in ascending order and by `age` in descending order.
_.orderBy(users, ['user', 'age'], ['asc', 'desc']);
console.log(users);

But then I get this: Uncaught ReferenceError: _ is not defined

As an addition. Installing and importing the whole library works: import _ from 'lodash';

However it is really big, my file jumps from 200kb to 325kb just from that, so i would prefer using just the orderby package.

**Comment by jdalton** [comment]
Hi @ilkovulchev!

If you're only importing the `orderBy` method then you'll need to reference it as `orderBy` and not with the `_`.

**Comment by ilkovulchev** [comment]
Hi @jdalton 

Yes it worked. Really obvious but did not think of it.

Thank you.
