### ISSUE TITLE
FP version of update does not work on function properties

### ISSUE THREAD

**Issue by mewdriller** [lodash/lodash#3219]
## Expected Behavior

Calling `update` on a key-path that resolves to a function causes the updater to be passed the function.

## Observed Behavior

Calling `update` on a key-path that resolves to a function causes the updater to be passed `undefined`.

## Steps to Reproduce

```js
import { update } from 'lodash/fp';

const obj = { a: 1, b: n => n * 2 };

console.log(obj.b(2)); // 4

const updatedObj = update('b', fn => n => fn(n) + 1, obj);

console.log(updatedObj.b(2)); // TypeError: fn is not a function
```

## Notes

For comparison, this works in the normal version of `lodash`:

```js
import { update } from 'lodash';

const obj = { a: 1, b: n => n * 2 };

console.log(obj.b(2)); // 4

update(obj, 'b', fn => n => fn(n) + 1);

console.log(obj.b(2)); // 5
```

**Comment by jdalton** [comment]
Hi @mewdriller!

Dup of #3203.

**Comment by mewdriller** [comment]
Whoops! Sorry I missed that before opening this one. Glad to hear it's taken care of already @jdalton.
