### ISSUE TITLE
Better documentation for 'predicate=_.identity'

### ISSUE THREAD

**Issue by soygul** [lodash/lodash#3221]
Given a method signature like [`_.remove(array, [predicate=_.identity])`](https://lodash.com/docs/4.17.4#remove), it is not immediately apparent that you can pass an object as the predicate, i.e. `_.remove([...], {id: 'lorem'})`.

Parameter docs state: `[predicate=_.identity] (Function): The function invoked per iteration.` which doesn't give a hint about the non-function argument possibility either. Parameter description can have a link to a section in the docs describing this possibility also.

**Comment by jdalton** [comment]
Hi @soygul!

It's a balance between providing info and avoiding doc bloat. In this case it's simpler to note the availability of shorthands and let users connect the dots rather than bloat every method that supports shorthands.

**Comment by soygul** [comment]
👍 Alright that's fair.
