### ISSUE TITLE
Generate Array of Objects from Redux Reducer in Selector for FlatList

### ISSUE THREAD

**Issue by MarcelBlockchain** [lodash/lodash#3222]
Hi,

to use the new FlatList Component in React you need to provide an Array of Objects
`<FlatList
  data={[{key: 'a'}, {key: 'b'}]}
  renderItem={({item}) => <Text>{item.key}</Text>}
/>
`
I use several reducers that store different sorts of cryptocurrency data.
Reducer1 stores prices: 
`'btc-usd' : 2640,
  'ltc-usd': 40`
Reducer2 stores the amount of crypto you have:
`'btc-usd': 2.533,
 'ltc-usd': 10.42`

My goal is to iterate through these values and create an array of Objects like
```
[ { name: 'Bitcoin', amount: 2.533, value: 2640, id: 'btc-usd' },
 { name: 'Litecoin', amount: 10.42, value: 40, id: 'ltc-usd' }, ...
]
```
So far, I think the proper way is to do it in a Selector with reselect. The part missing is the lodash Part in the createSelector.
Surprisingly I didn't find anything combining lodash and FlatList on the internet. 
Thanks a lot for helping.

```
import { createSelector } from 'reselect';
import _ from 'lodash';

export const selectRate = (state) => state.rate;
export const selectCryptoBalance = (state) => state.cryptoBalance;


export const createCoinArray = createSelector(
  selectRate, selectCryptoBalance,
  (rate, cryptoBalance) => {
     const coinArray = []; //better load array from state?

//IMPROVEMENT NEEDED HERE
     _.forIn(selectRate, () => {
        coinArray.push(_.assign({ [selectRate.id]: 0 }, cryptoBalance));
        console.log('coinArray in loop ', coinArray);
     });
     return coinArray;
  }
);
```

**Comment by jdalton** [comment]
Hi @MarcelBlockchain!

This is outside the scope of the Lodash project, however you can visit our [support chat](https://gitter.im/lodash/lodash) for help.

**Comment by MarcelBlockchain** [comment]
updated the question. Now it should be 100% lodash related
