### ISSUE TITLE
before.js was using if statement instead of while loop?

### ISSUE THREAD

**Issue by shadeofgod** [lodash/lodash#3223]
Hey there,
So I was studying source code of lodash and found this.
[Check link here](https://github.com/lodash/lodash/blob/master/before.js#L22)

At line 22, if using if statement here it only calls the function we passed in once even if we want it to be called multiple times.

Should it be like this:
```javascript
while (--n > 0) {
    result = func.apply(this, args)
}
```

**Comment by jdalton** [comment]
Hi @shadeofgod!

We don't want to use a `while` loop there because that will call the function repeatedly `n` times.

**Comment by shadeofgod** [comment]
> Creates a function that invokes `func`, with the `this` binding and arguments of the created function, while it's called less than `n` times.

But is that before.js designed for?

> jQuery(element).on('click', before(5, addContactToList)) // => Allows adding up to 4 contacts to the list.

It only do it once actually.
