### ISSUE TITLE
Why are there so many loose equal (eqeq) ?

### ISSUE THREAD

**Issue by aretecode** [lodash/lodash#3227]
example: [baseGet](https://github.com/lodash/lodash/blob/master/.internal/baseGet.js#L21)

in the internal functions especially I do not see why they are there

are there an environment where
- [castPath](https://github.com/lodash/lodash/blob/master/.internal/castPath.js) or [stringToPath](https://github.com/lodash/lodash/blob/master/.internal/stringToPath.js) (which return an `Array`) would not have `.length` as a number?
- [toKey](https://github.com/lodash/lodash/blob/master/.internal/toKey.js) `(1 / value)` would ever return something that is not `Number` ? or where `Infinity !== Infinity`?

thanks

**Comment by jdalton** [comment]
The v4 style preference was to use loose `==` when both types are known to be the same or when comparing a value to nullish (`null` or `undefined`).
