### ISSUE TITLE
why lodash/fp haven't 'not' function

### ISSUE THREAD

**Issue by Qquanwei** [lodash/lodash#3228]
logic not

```
not(true) -> false
not(false) -> true
```

thanks

**Comment by jdalton** [comment]
Hi @Qquanwei!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by cnexans** [comment]
@Qquanwei I like this feature. But I would prefer:

not(proposition : boolean) => !proposition
not(predicate : Function) = (...args) => !predicate(...args)

This would be very useful to negate predicates used for map and filter operators within lodash, or yet another operators in other libraries such as Rxjs.

**Comment by StreetStrider** [comment]
@Qquanwei 
1. `var not = (it) => ! it`
2. [`_.negate`](https://lodash.com/docs/4.17.4#negate)
