### ISSUE TITLE
suggestion for a new lodash/fp function: 'setIf'

### ISSUE THREAD

**Issue by continuata** [lodash/lodash#3229]
I find it really useful to chain `set` methods together in a `flow` for Redux reducers or when creating sparsely populated objects for testing.
What I've been missing in lodash is a conditional assignment, it makes `set` much more flexible and readable.
Here's what I'm proposing (for the FP version):
```es6
const setIf = _.curry(
  (path, value, condition, source) => 
    condition ? _.set(path, value, source) : source
)
```
It can be used like this
https://jsbin.com/fugeha/1/edit?js,console
```es6
const state = {
  foo: 'bar'
}
const value = ''
console.log(
  _.flow(
    setIf('foo', value, !_.isEmpty(value)),
    setIf('boo', 'far', !_.isEmpty('far')),
    setIf('hi', 'there', false)
  )(state)
)
// => [object Object] { boo: "far", foo: "bar" }
```

**Comment by jdalton** [comment]
Hi @continuata!

Instead of `setIf` I'd like to refine our conditional helpers like [_.cond](https://lodash.com/docs/4.17.4#cond).

**Comment by continuata** [comment]
@jdalton how would you suggest that work for my use-case? i.e. what would it look like semantically?

**Comment by stefanmaric** [comment]
Just passing by while searching for something unrelated.

> @jdalton how would you suggest that work for my use-case? i.e. what would it look like semantically?

@continuata not sure what you want to achieve, but your example defines the condition at the _.flow call, so this is equivalent:

```javascript

console.log(
  _.flow(
    _.isEmpty(value) ? _.identity : _.set('foo', value),
    _.isEmpty('far') ? _.identity : _.set('boo', 'far'),
    false ? _.set('hi', 'there') : _.identity
  )(state)
)
```
