### ISSUE TITLE
Request ".quote()"

### ISSUE THREAD

**Issue by teh-botol** [lodash/lodash#3232]
Just like [string.quote()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/quote) from Mozilla, which obsolete and non-standard.
> The non-standard quote() method returns a copy of the string, replacing various special characters in the string with their escape sequences and wrapping the result in double-quotes (").

`_.quote(string, [char='"']);`
```
_.quote('Hello world!');
\\ => '"Hello world!"'

_.quote('Hello world!', "'");
\\ => "'Hello world!'"

_.quote('Hello world!', "-");
\\ => "-Hello world!-"
```
It's more readable than this:
`'"' + variable + '"'`

**Comment by jdalton** [comment]
Thanks @teh-botol!

But not as readable as
```js
`"${variable}"`
```
I think we'll defer to template literals.
