### ISSUE TITLE
sumBy should always return a number

### ISSUE THREAD

**Issue by okonet** [lodash/lodash#3234]
Type definitions saying that `sumBy` always returns a `Number` but running it with this code will return `true`:

```js
var objects = [{ 'n': true }];
_.sumBy(objects, 'n');
```

and following example:

```js
var objects = [{ 'n': 'aaa' }, { 'n': 'bbb' }];
_.sumBy(objects, 'n');
// => 'aaabbb'
```

concatenates strings 🤷‍♂️  

Reproducible case: https://runkit.com/okonet/5953c05c261f8900124b0edc

**Comment by jdalton** [comment]
Yep, this an allowed edge case.

**Comment by okonet** [comment]
Hmm, then the documentation should probably be updated?

**Comment by jdalton** [comment]
I'm fine not
