### ISSUE TITLE
_.sumBy returns undefined when there's no object property matched

### ISSUE THREAD

**Issue by wonyoung** [lodash/lodash#3236]
When I use _.sumBy with property iteratee shorthand, an object with no property is counted as 0.
```javascript
_.sumBy([{name: 'a', value: 1}, {name: 'b'}], 'value')
// ==> 1
```

But, there's no object with property in list, it returns undefined.
```javascript
_.sumBy([{name: 'b'}], 'value')
// ==> undefined
```

**Comment by jdalton** [comment]
Hi @wonyoung!

This is by design because we don't want to force a number value result.
