### ISSUE TITLE
isFunction has unreachable condition

### ISSUE THREAD

**Issue by aretecode** [lodash/lodash#3237]
[isFunction](https://github.com/lodash/lodash/blob/master/isFunction.js#L27)
using [baseGetTag](https://github.com/lodash/lodash/blob/master/.internal/baseGetTag.js)

```js
return tag == '[object Function]' || tag == '[object AsyncFunction]' ||
    tag == '[object GeneratorFunction]' || tag == '[object Proxy]'
```

to polyfill on safari 9, which [does not have support for Proxy](http://caniuse.com/#search=proxy)
and even if it did, the getGetTag will not return proxy 

<img width="608" alt="screen shot 2017-06-29 at 6 36 35 pm" src="https://user-images.githubusercontent.com/4022631/27717474-56c9b7ec-5cfa-11e7-935e-408b7912f198.png">

**Comment by jdalton** [comment]
Hi @aretecode!

The condition was probably for another environment. When github stops unicorning I'll post back the commit reference.
