### ISSUE TITLE
unset multiple keys not working

### ISSUE THREAD

**Issue by edgracilla** [lodash/lodash#3238]
Tried on lodash page with RunKit

![untitled](https://user-images.githubusercontent.com/20719860/27727290-75c99138-5db0-11e7-9ce0-d0d0f7ee4ce0.png)

this one works
```
var object = { a: 'a', b:'b', c: 'c' };
_.unset(object, ['a']);
// => {b: "b", c: "c"}
```

**Comment by Archimidis** [comment]
> path (Array|string): The path of the property to unset.

The second argument of unset contains the path to the single property you want to remove. Passing `['a', 'b']` will try to remove `object.a.b`

**Comment by edgracilla** [comment]
`path `type `Array `is a bit misleading, it can be interpreted as multiple path to remove like below

```
var obj = {
  a: { b: 'c' },
  x: { y: 'z' }
}

_.unset(obj, ['a.b', 'x.y'])
```

my mistake, closing it
