### ISSUE TITLE
.camelCase() strips colon (:) from the string

### ISSUE THREAD

**Issue by gkcgautam** [lodash/lodash#3240]
When:
`_.camelCase('1:2:3')`

Expected:
`1:2:3`

Actual:
`123`

Is this the expected behaviour?

This was causing use few problems, and so we have temporarily started using the [camelcase](https://www.npmjs.com/package/camelcase) package.

**Comment by jdalton** [comment]
Hi @gkcgautam!

This is the expected behavior. We treat numbers as separate [_.words](lodash.com/docs#words).

**Comment by gnapse** [comment]
This seems related to this other behavior:

```javascript
camelCase('*')  // returns ''
```

Is this also expected behavior?

**Comment by jdalton** [comment]
Yes.

**Comment by gnapse** [comment]
Can you explain a bit what's the rationale for this? Not just around this specific character, but what's the expected treatment for punctuation characters in general. Are all punctuation characters stripped off the output or something?

**Comment by jdalton** [comment]
Our case methods are ways to compose compound words. So they split the string into words and then join them together in various ways.
