### ISSUE TITLE
isNaN

### ISSUE THREAD

**Issue by loveLibra** [lodash/lodash#3243]
```javascript
function isNaN(value) {
      return isNumber(value) && value != +value;
}
```
What's the function of `+` in `value !== +value`? To exclude some scene? With condition `value !== value`, only NaN missmatched，isn't ?

**Comment by jdalton** [comment]
Hi @loveLibra!

Some host objects in IE would error when comparing them with `value != +value` first.

**Comment by loveLibra** [comment]
Thanks @jdalton , I had missed that the comparison is not **strict**,  for the comparison between numeric object and it's origin value... Got it now
