### ISSUE TITLE
Does _.some return true for empty collections like _.every?

### ISSUE THREAD

**Issue by s4ayub** [lodash/lodash#3244]
In the docs for "_.every", it states in a note:

> Note: This method returns true for empty collections because everything is true of elements of empty collections.

Is the functionality the same for _.some?

**Comment by jdalton** [comment]
No. You could have tried it in the doc repl or the dev console. See [Array#some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some).
