### ISSUE TITLE
A bug with 'every'

### ISSUE THREAD

**Issue by weishaoboBrian** [lodash/lodash#3246]
The code is that:
`var a='105';
var result=_.every(a,Number);
console.log(result);
`
The result is 'false', but a is a Number;

**Comment by TrySound** [comment]
@weishaoboBrian Number do not check numbers, it converts to number if not. So you are trying to iterate string chars and get `Number('1') && Number('0') && Number('5')` which will look like `1 && 0 && 5` which is false, because zero is falsy value. So, it's not a bug.

**Comment by weishaoboBrian** [comment]
@TrySound  Thank you very much!!!!!!
