### ISSUE TITLE
Throttle and callbacks

### ISSUE THREAD

**Issue by int0h** [lodash/lodash#3248]
When I write code like this:
```js
const throttledFn = _.throttle(fn, 1000);
```
I expect `fn` to be called not more often than once per 1000 ms no matter how `throttledFn` be called.
But I've faced a problem with callbacks:
```js
// this function logs its invocation time and calls a callback after 10 ms delay
// (and also passes callback to itself to make this example run сontinuously)
const asyncFn = (cb) => {
    console.log(Date.now() % 10000);
    setTimeout(() => cb(cb), 10)
};

// at this point I expect that no any action with throttledAsyncFn 
// could lead to calling asyncFn with period less than 1 second
const throttledAsyncFn = _.throttle(asyncFn, 1000);

throttledAsyncFn(throttledAsyncFn)
```
It logs first 2 line with proper delay, but then it's sometimes called with interval of ~10 ms.
There is codepen: https://codepen.io/Int0h/pen/mwGyVp?editors=1111

There is simplier example: https://codepen.io/Int0h/pen/gRdbKQ?editors=1111
In my case it logs 3 and 4 line with delay of ~10 ms.

Is it expected behaviour? If so it would be reasonable to mention this in docs

**Comment by jdalton** [comment]
Hi @int0h!

You can customize whether throttle triggers a leading or trailing invocation.

**Comment by int0h** [comment]
I'm a bit confused. If I understand the documentation correctly...

> Creates a throttled function that only invokes func at most once per every wait milliseconds

...a `func` throttled with any options should be called 'at most once per every wait milliseconds'

So it's already not my case (in my example throttled function was called with an interval less than 'wait')

Speaking about `leading` and `trailing` options, I beleive they configure behaviour which I want to keep default. When I run this code:
```js
throttledAsyncFn(throttledAsyncFn)
```
I expect asyncFn to be called immediately at first time, and after `wait` ms (when it'll be fired from callback).

In other words:  I expect this code:
```js
throttledAsyncFn(throttledAsyncFn)
```
 to call a `asyncFn`  in the same way as the following code does:
```js
setInterval(throttledAsyncFn, 10)
```
interval version: https://codepen.io/Int0h/pen/jwveKV?editors=1111 (it works fine by the way) 

Anyway I've tried `leading` and `trailing` options:

- when `trailing` is set to `false` it fires only once (https://codepen.io/Int0h/pen/YQOJYB?editors=1111)
- when `leading` is set to `false` it fires almost as I expect but it does not fire immediately (https://codepen.io/Int0h/pen/mwGzrv?editors=1111). This is pretty reasonable (due to leading=false) but I don't want to skip leading invocations.
