### ISSUE TITLE
"createWrap.js" cannot be found

### ISSUE THREAD

**Issue by luckyhalley** [lodash/lodash#3251]
ary.js line 1
```JavaScript
import createWrap from './.internal/createWrap.js'
```
Does the source code exclusive this file?

**Comment by falsyvalues** [comment]
Hi @luckyhalley The `master` branch is in flux while we work on Lodash v5. Take a look on [CONTRIBUTING](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md) guide.

**Comment by sunchenguang** [comment]
` Lodash v5` where can i find it ? 
I still can not find `createWrap.js`

**Comment by jdalton** [comment]
@sunchenguang 

From the [contributing guide](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md):
> Pardon the mess. The `master` branch is in flux while we work on Lodash v5. This
means things like npm scripts, which we encourage using for contributions, may
not be working. Thank you for your patience.
