### ISSUE TITLE
Why is `sameValueZero` used by default?

### ISSUE THREAD

**Issue by xgbuils** [lodash/lodash#3252]
Hi!

I'm trying to found the decision to use `sameValueZero` as default comparison instead of strictly equal `===`. I don't know if using `sameValueZero` is something decided because is more intuitive (NaN is equal to NaN) or for other technical reasons that I don't know.

Thanks!

**Comment by jdalton** [comment]
Hi @xgbuils!

We use `sameValueZero` because it aligns with ES6+ comparisons mechanisms for things like `Map`, `Set`, & `Array#includes`.

**Comment by xgbuils** [comment]
Ok! thanks!
