### ISSUE TITLE
fp: mapKeys not working with convert({cap: false})

### ISSUE THREAD

**Issue by super-cache-money** [lodash/lodash#3253]
I'm using (and loving) fp.
But:
```
const fp = require('lodash/fp').convert({cap: false});
var test = {x: 1, y: 2};
print(fp.mapKeys(x=>x+x)(test));
```
Gives:
```{ '2': 1, '4': 2 }```

When leaving off `convert({cap: false})`, it prints the correct output:
```{ 'xx': 1, 'yy': 2 }```

**Comment by jdalton** [comment]
Hi @super-cache-money!

When you're not capping the arguments the iteratee arguments are `value, key`.

**Comment by super-cache-money** [comment]
😅
