### ISSUE TITLE
add function _.filterBlank

### ISSUE THREAD

**Issue by ershing** [lodash/lodash#3255]
sometimes we want an object that filters the blank properties.
we can use the function _.filterBlank( ), just like this:
var example = { a:1 , b:'',c:'' };
var b = _.filterBlank(example);
so that we van get b={a:1}

**Comment by jdalton** [comment]
Hi @ershing!

You can use [_.pickBy](https://lodash.com/docs#pickBy).

**Comment by ershing** [comment]
but i can not find a function to check if value is null or undefined or '' , i just find _.isNil

**Comment by gre** [comment]
@ershing `value => !value` is that function? true if value is null, or undefined, or ""

**Comment by ershing** [comment]
@gre i don't think so ,  we put 0 in the function value=> !value , we also get true

**Comment by ershing** [comment]
@jdalton but i can not find a function to check if value is null or undefined or '' , i just find _.isNil

**Comment by gre** [comment]
why not passing your own function?

**Comment by ershing** [comment]
@gre i only want to filter undefined , null , ''  ,i don't want to filter 0 ,if you use value=>!value to filter, it will filter 0, if i get var example={a:1,b:undefined,c:null,d:'',e:0 },  i want to get {a:1 , e:0}

**Comment by gre** [comment]
@ershing I get that! but then why not doing your own function that you pass in?

```js
function isValid (value) {
  return value || value === 0;
}
_.pickBy(example, isValid);
```

**Comment by ershing** [comment]
@gre i think that it should be like this:
```javascript
function isOther (value) {
    return value===0?false:!value;
}
_.pickBy(example, !isOther);
```
but i think i am too lazy to write my own function , haha

**Comment by jamespedid** [comment]
If you use lodash.pickBy(collection), it will filter out any objects that are not truthy without an extra parameter.
