### ISSUE TITLE
isMap does not work in Safari 9

### ISSUE THREAD

**Issue by jshado1** [lodash/lodash#3256]
It appears the issue arrises when [lodash tries to use Node's util.isMap](https://github.com/lodash/lodash/blob/master/isMap.js#L6) method to do the actual detection; this method does not exist. [Util's docs](https://nodejs.org/api/util.html) list all of the other is* methods as deprecated, so perhaps `isMap` has already been removed.

Meantime, the workaround we're using is `instanceof`:
```js
if (obj instanceof Map) // is a Map
```

I'm happy to send you a PR for isMap, but I think the deprecation of the other Util methods is likely to be a larger problem.

**Comment by jdalton** [comment]
Hi @jshado1 !

We check that the method exists before using it. I believe your issue is elsewhere.

**Comment by jshado1** [comment]
After further investigation, we discovered there is interaction with Babel, where it polyfills the Map constructor, which fools lodash.
