### ISSUE TITLE
lodash call all functions in array/object without collecting results

### ISSUE THREAD

**Issue by jurchiks** [lodash/lodash#3257]
I wanted something extremely simple, but it seems there is no built-in way to do this in lodash.

The example code:

```
    function loadThings(name) {
        var map = {
            foo: function () { console.log('foo'); },
            bar: function () { console.log('bar'); }
        };
        
        if (name && map[name]) {
            map[name]();
        } else {
            _.each(map, function (item) { item(); });
            // What I wanted:
            // _.each(map, _.call);
        }
    }
```

I know it's extremely easy to implement in my own code, but I just thought there would be a way to do this already.

I tried looking through the docs for something similar but couldn't find anything. Perhaps someone else knows better? If not, perhaps turn this into a feature request?

**Comment by jdalton** [comment]
There's ways to bind a `_.call` or a `Function.prototype.call` but really using an arrow function is ideal.

```js
_.each(map, item => { item() })
```

**Comment by jurchiks** [comment]
Yeah well, I can't use arrow functions in the browser, it does not have enough support.

**Comment by jdalton** [comment]
Babel is great for those cases 😺

**Comment by jurchiks** [comment]
It's not when you have a large project and no time to rework it to babel.
