### ISSUE TITLE
Add a _.shift function that shifts arguments

### ISSUE THREAD

**Issue by ngryman** [lodash/lodash#3259]
Hey,

I have a simple use case where I use `cond` to basically emulate a switch. It gets called with the first argument being the *pivot* (a type defined as a `string`). I would then like to call different functions depending on the value of the *pivot*. All those functions are not interested by the *pivot*, but the rest of the arguments. I know I could use a simple object indexed by types, but I want a generic pattern that work when the *pivot* is a complex type (`object`, `function`, ...).

I've experimented several ways of doing so with Lodash and couldn't find a *simple* way. Perhaps I missed it, and if so sorry for the issue.

The only short way is to use splats like so:
```js
const handleActions = cond([
  [matches('create'), (type, ...args) => handleCreate(...args)]
])
```

My proposal would be to add a new `_.shift` function with the following signature: `_.shift(func, [increment=1])`

It would work as the `shift` operator but for args and would shift a given number of arguments defined by an `increment`. Depending of the sign of `increment`, those arguments would be shifted left or right. By default (and because it's the most common use case), a positive value would shift arguments to the left, a negative to the right.

Example use case:
```js
const add(a, b) => a + b
const sub(a, b) => a - b

const apply = cond([
  [matches('add'), shift(add)],
  [matches('sub'), shift(sub)]
])

apply('add', 1, 2)
// => 3
```

**Comment by jdalton** [comment]
Hi @ngryman !

When it comes to shifting arguments and partial application I think we'll side on using arrow functions. They're so thin and give folks the flexibility to juggle arguments any way they see fit.

**Comment by ngryman** [comment]
Thanks for the answer, seems legit.
