### ISSUE TITLE
_.invert() throws an error on a specific JSON object

### ISSUE THREAD

**Issue by radekk** [lodash/lodash#3260]
**JSFiddle:** https://jsfiddle.net/mem9e9r9/
**Error:** TypeError: Cannot convert object to primitive value
**Description:**
It seems like `invert()` function is triggering an error when converting json object with `builtin -> toString` property present. I tried with standard JSON files and it does work properly.

It fails to run `_.invert()` on this JSON object:

```json
{
  "builtin": {
    "toString": false
  }
}
```

**Comment by jdalton** [comment]
Thanks @radekk!

**Comment by radekk** [comment]
@jdalton Thanks John for fixing this issue. How should I install this fix through `npm`? I tried with:

```
npm i 'lodash/lodash#01148a1df881b7b1f2cd92626bbdb330176ca1b1' --save
```

But it's not generating the `index.js` file in `node_modules/lodash/` directory and furthermore node.js is not able to load that module.

**Comment by jdalton** [comment]
It'll be in v5 (whenever that's released).
