### ISSUE TITLE
Can't access non-enumerable keys

### ISSUE THREAD

**Issue by gunar** [lodash/lodash#3261]
Hi there, John! Thanks again for lodash.

I would expect there to be a way to configure functions to acknowledge the non-enumerable keys of objects.

```js
const { values, keys, get } = require('lodash/fp')

const A = Symbol()
const B = Symbol()
const C = Symbol()
const SIZES = {
  [A]: '16x16',
  [B: '32x32',
  [C]: '164x64',
}

values(SIZES) // []
keys(SIZES) // []
```

Thanks in advance.

**Comment by jdalton** [comment]
Hi @gunar!

There isn't a through the lib. There is built-ins like `Object.getOwnPropertyNames` and `Object.getOwnSymbolNames` though.

**Comment by gunar** [comment]
Thanks!

For posteriority, here's `values` but for Symbols:
```js
const symbolValues = obj =>
  map(get(__, obj))(Object.getOwnPropertySymbols(obj))
// e.g.
symbolValues(SIZES) // ['16x16', '32x32', '164x64']
```
