### ISSUE TITLE
Question: computed === computed

### ISSUE THREAD

**Issue by dferber90** [lodash/lodash#3265]
I was looking through the source code and found this check:
`if (isCommon && computed === computed)` in [baseDifference.js](https://github.com/lodash/lodash/blob/master/.internal/baseDifference.js#L47).

I'm wondering what `computed === computed` checks for. The only thing I could come up with where this would result in`false` is when the value of `computed` is `NaN`.

Is that what is going on?

**Comment by jdalton** [comment]
Hi @dferber90!

Yes, that's a `NaN` check.

**Comment by codTango** [comment]
@jdalton I just found this today, so I'm wondering why not check directly using `isNaN(computed)`, that might be more readable? Or it's just a preference in lodash?
