### ISSUE TITLE
fp.partial not accepting simple values

### ISSUE THREAD

**Issue by gunar** [lodash/lodash#3266]
Docs make it seem like `fp.partial` accepts an array optionally, but it seems mandatory.

```js
const { partial } = require('lodash/fp')

const foo = partial((a, b) => a+b)([1])
t.equal(foo(2), 3) // ok

const foo = partial((a, b) => a+b)(1)
t.equal(foo(2), 3) // TypeError: CreateListFromArrayLike called on non-object
```

#### Exceptions to the rules
> Methods that accept an array as their last or only argument:
assignAll, assignAllWith, assignInAll, assignInAllWith, defaultsAll, defaultsDeepAll, invokeArgs, invokeArgsMap, mergeAll, mergeAllWith, partial, partialRight, without, & zipAll

Source
> https://github.com/lodash/lodash/wiki/FP-Guide

**Comment by madnight** [comment]
"Methods that accept an array as their last or only argument" well this sounds very clear to me, you have to provide an array either as last argument or as one and only argument, but you have to provide it, not optional

**Comment by gunar** [comment]
Certainly wasn't clear to me. Care to change the wording to "Methods that *expect* as array..."?

**Comment by jdalton** [comment]
Sure thing!
