### ISSUE TITLE
_.forEach and _.reduce treat object literals with a "length" property as an array

### ISSUE THREAD

**Issue by seanmcgary** [lodash/lodash#3269]
I noticed today with the latest version of lodash (4.17.4) that passing an object literal like this:

```javascript
{
    length: 10,
    width: 50,
    height: 25
}
```

to _.forEach and _.reduce results in it treating it like an array.

```javascript
_.forEach({ length: 10, width: 50, height: 25 }, (val, key) => {
    console.log(key, val);
});
/*
0 undefined
1 undefined
2 undefined
3 undefined
4 undefined
5 undefined
6 undefined
7 undefined
8 undefined
9 undefined
*/
```

```javascript
_.reduce({ length: 10, width: 50, height: 25 }, (acc, val, key) => {
    console.log(key, val);
    acc[key] = val;
    return val;
}, {});
/*
1 undefined
2 undefined
3 undefined
4 undefined
5 undefined
6 undefined
7 undefined
8 undefined
9 undefined
*/
```

Removing the length property resolves this issue:

```javascript
_.reduce({ width: 50, height: 25 }, (acc, val, key) => {
    console.log(key, val);
    acc[key] = val;
    return val;
}, {});
/*
width 50
height 25
*/

_.forEach({ width: 50, height: 25 }, (val, key) => {
    console.log(key, val);
});
/*
width 50
height 25
*/
```

Looking through the code for 4.17.4, it seems that the [```baseEach```](https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L4907) function could be the issue, as ```isArrayLike``` will return true, even if the collection is an object literal that happens to have a numeric length property, causing it to loop over the object for the length of ```collection.length``` when it should be iterating over it's keys.

**Comment by JakeGlascock** [comment]
That's a link to a 404 page, @falsyvalues.  I think you meant to link to [this documentation](https://lodash.com/docs/4.17.4#forEach).

**Comment by ematipico** [comment]
From documentation

> Note: As with other "Collections" methods, objects with a "length" property are iterated like arrays. To avoid this behavior use _.forIn or _.forOwn for object iteration.

**Comment by falsyvalues** [comment]
@JakeGlascock yes, thanks!
