### ISSUE TITLE
It would be nice if debounce time can be changed on debounced instance

### ISSUE THREAD

**Issue by jarben** [lodash/lodash#3272]
Once a debounced is returned, it is not possible to change debounce time. It would be useful if this is possible by calling debounced.wait(500)? 

This can be useful if different triggers share one debounced, for example, key event can have different debounce time than mouse event  where it's important they both share one debounce instance.

**Comment by jdalton** [comment]
Hi @jarben!

This is a neat idea but out of scope for our `debounce` at the moment. You can always kick around an implementation as a mixin and report back when you get it working.
