### ISSUE TITLE
Rollup bundling not working

### ISSUE THREAD

**Issue by albpara** [lodash/lodash#3274]
When executing the aot rollup on an angular 2 project I am getting this errors:

```
Export 'forEach' is not defined by '/app/src/components/home/home.component.js'
Export 'groupBy' is not defined by '/app/src/components/home/home.component.js'
```

The import is done this way

```
import * as _ from 'lodash'
```

The app works, and the aot compiler is not showing errors but the rollup step fails with a bunch of those errors

Any clue about the problem?

**Comment by TrySound** [comment]
@albpara Do you use rollup-plugin-commonjs? Rollup out of the box works only with es6. To make work better replace `lodash` package with `lodash-es` - an official es modules package.
