### ISSUE TITLE
Why does `_.get(obj, path)` return `undefined` when path is empty?

### ISSUE THREAD

**Issue by bartvanandel** [lodash/lodash#3276]
I'd like to use `_.get(obj, path)` with generic paths, including empty ones to return the whole data structure. Unfortunately, when the path is empty (i.e., `''` or `[]`, or `null` or `undefined` for that matter), `baseGet` is hardwired to return `undefined`. Is there a specific reason for this? It isn't mentioned in the docs.

**Comment by jdalton** [comment]
Hi @bartvanandel!

There's some debate over this. I've sided with since you're querying for a path of an object if you don't provide a path then it is a failed match. Similar to `document.querySelector("")` (which errors).

**Comment by bartvanandel** [comment]
I see where you're coming from, but the selector in `document.querySelector(s)` isn't necessarily a path, whereas in the case of `_.get(obj, path)` it is always a path. Running `document.querySelector('div')` results simply in the first `div` on the page, whereas `_.get(obj, 'div')` will only ever result in `obj.div`.

With this in mind, I'd like to propose differentiating between providing the root path on purpose (i.e. `''` or `[]`), and providing nothing at all, or `null` or `undefined`, which is arguably an invalid path.

**Comment by jdalton** [comment]
I understand that `_.get` and `QSA` aren't 1:1 but you get the gist. If you're selecting a path and provide an `undefined` path then there is nothing to select and so nothing is returned.

**Comment by bartvanandel** [comment]
Yes, `undefined`. I'd argue `''` or `[]` are different though. But I'll hack around it if it's not going to change.

FYI I tried to look up any discussion, but the word "get" is a bit too common to find nice results...
