### ISSUE TITLE
Questions about comments in baseIsNaN.js

### ISSUE THREAD

**Issue by Dcatfly** [lodash/lodash#3277]
The baseIsNaN.js file is
```
/**
 * The base implementation of `isNaN` without support for number objects.
 * @private
 * @param {*} value The value to check.
 * @returns {boolean} Returns `true` if `value` is `NaN`, else `false`.
 */
function baseIsNaN(value) {
  return value !== value
}

export default baseIsNaN

```
I would like to know why he said "without support number objects"？

**Comment by jdalton** [comment]
Hi @Dcatfly!

Number objects are those like `new Number(2)` which produces a number object.

**Comment by Dcatfly** [comment]
Hello @jdalton !
I know what's `new Number(2)`, but I mean the function named `baseIsNaN` also works on `new Number()`.
So I would like to know why he said "without support number objects".

**Comment by jdalton** [comment]
`baseIsNaN` does not work with `new Number(NaN)`.

**Comment by Dcatfly** [comment]
Thank you for your reply.
But, `baseIsNaN(new Number(NaN)) === false` and `Number.isNaN(new Number(NaN)) === false`.
So I think `baseIsNaN` also works on `new Number(NaN)`.
And if you are saying `isNaN(new Number(NaN)) === true`, then `isNaN(new Object(NaN)) === true`. But you say "without support number objects".

**Comment by jdalton** [comment]
Our `_.isNaN` works with number objects but our `baseIsNaN` doesn't.
