### ISSUE TITLE
Feature idea : allowing to filter arrays with pick

### ISSUE THREAD

**Issue by chris-verclytte** [lodash/lodash#3279]
Hi,

Would you consider update the pick function to allow filtering on array as it is done on MongoDB.
Here is a quick example.
```javascript
// Input
const a = {
 b: 1,
 c:  {
    a: 4,
    b: '2'
  },
 d: [{
     e: 'e',
     f: 'f',
  }, {
     e: 'e1',
     f: 'f1',
  }, {
     e: 'e2',
     f: 'f2',
  }] 
}

// Expected output
const result = _.pick(a, ['b', 'c.a', 'd.e']);
// result a = { b: 1, c: { a: 4 }, d: [{ e: 'e' }, { e: 'e1' }, { e: 'e2' }] }
```

**Comment by jdalton** [comment]
Thanks @chris-verclytte!

I can dig it but I'm a bit worried on the implementation side of the complexity around making it work. We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by cemulate** [comment]
I've occasionally felt a need for this as well. 

As an alternative implementation idea, what about a wildcard for array index in a property path?
Using your same example from above, we might do:

    const result = _.pick(a, ['b', 'c.a', 'd.*.e']);
    // result = { b: 1, c: { a: 4 }, d: [{ e: 'e' }, { e: 'e1' }, { e: 'e2' }] }

This mirrors how one can use `d.0.e`, `d.1.e`.

**Comment by freddi301** [comment]
I think a good idea could be to allow predicate functions to pick
```javascript
const result = _.pick(a, ['b', 'c.a', key => /^d\..+\.e/.test(key)])
```
