### ISSUE TITLE
[Question] Could lodash-cli support load config from a file

### ISSUE THREAD

**Issue by poppinlp** [lodash/lodash#3282]
Seems i can't open issue in lodash-cli repo, so i open this issue here. Sry for that.

This issue is for a easy way to use lodash-cli since there could be many params in lodash-cli build command and it's a little bit not convenient to maintain.
I have made a tool for myself to read params from a YAML file and then do the build job. I think it's more  clear for many params in a config file since there could be some structures to use such as Map to specify params and Array for method list e.t.c.
So could there be such a feature in lodash-cli to support this? :)

**Comment by jdalton** [comment]
Hi @poppinlp!

The `lodash-cli` is discontinued.
It's recommended folks use webpack for their bundling needs instead.

**Comment by poppinlp** [comment]
OK. Got it. Thanks
