### ISSUE TITLE
Why is this a separate package?

### ISSUE THREAD

**Issue by maroshluskasc** [lodash/lodash#3283]
I'm just curious why this is a separate package? If my project uses `lodash-es` and various other packages in my dependency tree use various versions of `lodash`, aren't I going to end up with at least one copy of `lodash` and one copy of `lodash-es` in my bundle?

**Comment by jdalton** [comment]
Hi @maroshluskasc!

The `lodash-es` package is a separate package because it's raw ES6 code which has limited support at the moment. You can use Webpack to alias `lodash` as `lodash-es` though.
