### ISSUE TITLE
Iteratee property short hand yields different result than passing function to _.map()

### ISSUE THREAD

**Issue by joshribakoff** [lodash/lodash#3284]
I expect the 2 console logs to yield the same result. One gives an array with an element undefined (does not give me the ID). The property shorthand seems buggy.

```js
var foo = JSON.parse('[{"_id":{"$id":"597a3c5e8a54859f058b4569"},"product_name":"test 2"}]');

var ids = _.map(foo, '._id.$id');
 console.log(ids); // Does not give me the ID

var ids = _.map(foo, function(o) {
    return o._id.$id;
});
console.log(ids); // Gives me the ID
```

Lodash 4.17.4

Plunkr to repro the issue - https://plnkr.co/edit/6QtalfLGl5XU9i38QCwx?p=preview (open console)

UPDATE

Looks like the issue was I accidentally included a prefixing "." on my property short hand, should that have thrown an error? Was very nefarious to debug. If that's not an error, what is the defined behavior for that, where is that documented?

**Comment by Sieabah** [comment]
Since '.' would be a valid key in an object it's a case which can't be caught as an Error.

**Comment by joshribakoff** [comment]
If I pass `_.map()` a property shorthand of `.foo.bar` against this object:

`{".foo.bar":"foo", ".foo":{"bar":"bar"}}`

It seems ambiguous. I'm sure its defined in a test suite somewhere but its not user friendly.

**Comment by jdalton** [comment]
Hi @joshribakoff!

You should be able to use an array with `_.property(arrayPath)` helper.

**Comment by joshribakoff** [comment]
Ah that makes sense now. So the shorthand DSL is ambiguous, but I can get more specific with `_.property()` if desired, to avoid the ambiguity.

Thank you for clearing that up.
