### ISSUE TITLE
'desc' acts differently than 'asc' when using _.orderBy

### ISSUE THREAD

**Issue by chrillewoodz** [lodash/lodash#3285]
I'm doing some unit testing and found an odd bug, and that is `_.orderBy` working differently for `asc` and `desc`:

 ```
 it('should sort items by value in ASC order', () => {
    expect(pipe.transform([{value: '200'}, {value: 100}, {value: '50'}], ['value', 'ASC'])).toEqual([{value: 100}, {value: '200'}, {value: '50'}]);
  });

  it('should sort items by value in DESC order', () => {
    expect(pipe.transform([{value: '200'}, {value: 100}, {value: '50'}], ['value', 'DESC'])).toEqual([{value: '50'}, {value: '200'}, {value: 100}]);
  });
```

First test passes, second one does not. For that one I get 

`Expected [ Object({ value: '200' }), Object({ value: 100 }), Object({ value: '50' }) ] to equal [ Object({ value: '50' }), Object({ value: '200' }), Object({ value: 100 }) ]`

When using `desc` it seems to order by the value rather than the first character, as the `asc` does and what the `desc` should do. 

Is this a bug or am I missing something? I find it really odd that the two acts differently.

**Comment by jdalton** [comment]
Hi @chrillewoodz!

You're specifying the order param incorrectly.
Please review the docs.

**Comment by chrillewoodz** [comment]
I have. What is wrong exactly?

**Comment by jdalton** [comment]
https://lodash.com/docs/#orderBy

Orders are supposed to be in a separate array.

**Comment by chrillewoodz** [comment]
@jdalton That's what I'm doing.. 

I removed the actual pipe implementation and still getting the same result. Look:

```
  it('should sort items by value in ASC order', () => {
    expect(_.orderBy([{value: '200'}, {value: 100}, {value: '50'}], ['value'], ['asc'])).toEqual([{value: 100}, {value: '200'}, {value: '50'}]);
  });

  // Doesn't give me what it should be giving me. Issue can be found here https://github.com/lodash/lodash/issues/3285
  it('should sort items by value in DESC order', () => {
    expect(_.orderBy([{value: '200'}, {value: 100}, {value: '50'}], ['value'], ['desc'])).toEqual([{value: '50'}, {value: '200'}, {value: 100}]);
  });
```

**Comment by jdalton** [comment]
The wonky sort order is expected when mixing number and string values. You can avoid that by coercing your values to strings or numbers (whichever you want)
```
_.orderBy([{value: '200'}, {value: 100}, {value: '50'}], [(o) => +o.value], ['asc'])
```

**Comment by chrillewoodz** [comment]
Well that's not the point I'm trying to make. The point is that asc and desc aren't giving me same "wonky" sort order. If it gives me `100`, `'200'`, `'50'` for `'asc'` it should give me the reverse for `'desc'` or the function is not doing what it should be doing. It's not giving consistent output, if you disregard that the types aren't what they should be. That's why the test is there in the first place, to assure the correct behaviour. I hope my point has been made clear and that it will be taking into consideration to fix.

**Comment by jdalton** [comment]
> If it gives me `100`, `'200'`, `'50'` for `'asc'` it should give me the reverse for `'desc'` or the function is not doing what it should be doing

We're just [toggling the multiplier](https://github.com/lodash/lodash/blob/4.17.4-es/_compareMultiple.js#L31) `1` or `-1` based on `'desc'`. I suspect you're running into a JavaScript sorting issue which is the wonky bit. I'm not interested in fixing that.

**Comment by Qsaws** [comment]
I had a similar issue with an array containing two identical values, asc was sorting the array correctly but desc wouldn't.

So I did this which solved my issue.

`_.reverse(_.orderBy(..., ..., ['asc']))`

**Comment by ufojava** [comment]
> I had a similar issue with an array containing two identical values, asc was sorting the array correctly but desc wouldn't.
> 
> So I did this which solved my issue.
> 
> `_.reverse(_.orderBy(..., ..., ['asc']))`

very cleaver, worked a treat.
