### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by sarabs3** [lodash/lodash#3287]
While installing lodash with npm getting the following error.

Cannot read property '0' of undefined

Node version is 8.2.1

Other Notes : I have deleted my node_modules and run the npm install command again

**Comment by jdalton** [comment]
Hi @sarabs3!

I don't think this is a lodash issue.

**Comment by sarabs3** [comment]
when i run npm install lodash

then this error message appears.
