### ISSUE TITLE
lodash.js / lodash.min.js: IBM AppScan finding: Web Application Source Code Disclosure Pattern Found

### ISSUE THREAD

**Issue by DaddyJJ** [lodash/lodash#3288]
IBM AppScan security testing tool (Standard 9.0.2.1, Rules: 1932) is flagging lodash.js and lodash.min.js as low severity issues.
The suspected code pattern is "<%".
Is this valid? If valid, how to fix?
I'm very inclined to define it as a false positive.

Other info from ApScan:
- Risk: It is possible to retrieve the source code of server-side scripts, which may expose the application
logic and other sensitive information such as usernames and passwords
- Causes: Latest patches or hotfixes for 3rd. party products were not installed
Temporary files were left in production environment
Debugging information was left by the programmer in web pages
- Fix: Remove source code files from your web-server and apply any relevant patches
- Reasoning: The response contains source code of script files, which may expose sensitive information
about the site and the application logic.

**Comment by jdalton** [comment]
Hi @DaddyJJ!

It looks like it's false flagging our own [_.template](lodash.com/docs#template) implementation.
