### ISSUE TITLE
debounce with class instance method does not work.

### ISSUE THREAD

**Issue by yoshiokatsuneo** [lodash/lodash#3290]
Calling "debounce" with instance method does not work.
"debounce" looks trying to keep "this". But actually, on the contrary, it breaks "this" for the instance method.

```
_ = require('lodash');
class A{
  func(){
    console.log('this=', this.constructor.name);
  }
}
const a = new A();
a.func();
_.debounce(a.func, 1000)();
```

```
$ node a.js 
this= A
this= Object
```

**Comment by jdalton** [comment]
Hi @yoshiokatsuneo!

You should probably bind it
```js
_.debounce(a.func.bind(a), 1000)();
```

**Comment by yoshiokatsuneo** [comment]
@jdalton Yes, it is a workaround. But, I think the "debounce"'s behavior is not intuitive and confused me.

**Comment by jdalton** [comment]
That's not a debounce thing, that's a JavaScript thing.

**Comment by yoshiokatsuneo** [comment]
@jdalton Actually, it *is* "debounce" thing because "debounce" override "this".

```
  function invokeFunc(time) {
    const args = lastArgs
    const thisArg = lastThis

    lastArgs = lastThis = undefined
    lastInvokeTime = time
    result = func.apply(thisArg, args)
    return result
  }
```
https://github.com/lodash/lodash/blob/master/debounce.js#L79

**Comment by jdalton** [comment]
@yoshiokatsuneo Naw. Read more [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Creating_a_bound_function).

**Comment by yoshiokatsuneo** [comment]
@jdalton Ah, I got ! It was my mistaken! Thanks.

**Comment by elisechant** [comment]
For anyone in the future _still_ struggling with this https://stackoverflow.com/questions/23123138/perform-debounce-in-react-js
