### ISSUE TITLE
_.difference

### ISSUE THREAD

**Issue by NandiniArjun** [lodash/lodash#3291]
I have 2 array of object something like [Object, Object, Object, Object, Object] and each object look like 0
0:Object
accountId:580
default:true
guid:"AE922279-2DEA-41B5-B494-1177D0A28D89"
htmlCode:"&pound;"
id:672
longDesc:"British Pounds Sterling"
modifiedDate:1501084730000
rate:1
shortDesc:"GBP"
syncId:null
unicodePattern:"0xA3"

I want to filter the 2 arrays with id using the _.difference function. How do i achieve this?

**Comment by jdalton** [comment]
Hi @NandiniArjun!

Try [_.differenceBy](https://lodash.com/docs/#differenceBy) or [_.differenceWith](https://lodash.com/docs/#differenceWith).

**Comment by NandiniArjun** [comment]
Hi,
I am using _.difference(globalCurrencies, currencies,'id') which didn't work. Could you please provide the example code with difference with and difference by?
