### ISSUE TITLE
import _ from 'lodash/core' //  _.bind placeholder invalid

### ISSUE THREAD

**Issue by lfyfly** [lodash/lodash#3292]
// import _ from 'lodash' // _.bind placeholder valid
import _ from 'lodash/core' //  _.bind placeholder invalid

function greet(greeting, punctuation) {
  console.log(greeting + ' ' + this.user + punctuation) ;
}
 
var object = { 'user': 'fred' };
 
var bound = _.bind(greet, object, _, '!');
bound('hi');
// log:
// function lodash(value) {
//     return value instanceof LodashWrapper
//       ? value
//       : new LodashWrapper(value);
//   } fred!

**Comment by jdalton** [comment]
Hi @lfyfly!

This is by design. The core build is a stripped down build.
