### ISSUE TITLE
Documentation fix `set()`

### ISSUE THREAD

**Issue by Mtnt** [lodash/lodash#3296]
In the documentation the `set` method takes an `object` as first argument. But actually it can work with arrays.

http://take.ms/K7024

UPD:
I know that I can just use it with an array =) But thirdparty libs such as flow-typed are based on your documentation.

**Comment by jdalton** [comment]
Hi @Mtnt!

An array is an object so I'm fine letting it slip by. I rather not explicitly list all object types as that would clutter the documentation.
