### ISSUE TITLE
Case sensitive flag as a prop for _.orderBy() ??

### ISSUE THREAD

**Issue by NarasimhaReddyY** [lodash/lodash#3297]
Why we can we have a flag, to implement case insensitive  sorting based on the flag? by default it will be flase. Does it make sense?

**Comment by jdalton** [comment]
Hi @NarasimhaReddyY!

More sorting options may be a good thing. We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by vesrah** [comment]
I would say have it default to being case sensitive, as it is currently case sensitive and changing the default behavior would be a breaking change.
