### ISSUE TITLE
How to use `chain` with `lodash-es` while supports tree shaking?

### ISSUE THREAD

**Issue by e-cloud** [lodash/lodash#3298]
As we all know, [`lodash-es`](https://github.com/lodash/lodash/tree/es) is built with a more modular syntax for supporting tree shaking by build tools.

However, `chain` related features means some functions are attached to a object/prototype chain.

I can see `chain` is published with `lodash-es`, but I am not sure how to use it with proper imports with other chained method.

A usecase may look like this:

    import { chain } from 'lodash-es'
    
    export function double(input) {
        return chain(input)
            .without(null)
            .map(val => val * 2)
            .value()
            .join(', ')
    }

The point is not about how is `chain` imported, but about **how are other `chained` functions imported**.

> Here is a SO question created: https://stackoverflow.com/questions/45462193/how-to-use-chain-with-lodash-es-while-supports-tree-shaking

### Further question:
What is the actual usecase of `chain` under `lodash-es`?
If we should not use `chain` under `lodash-es`, shouldn't it be published?

**Comment by jdalton** [comment]
Hi @e-cloud!

The short answer is you can't.

**Comment by e-cloud** [comment]
I may be a little annoying. But I have to keep asking. Since I can't use it that. What's the purpose of exposing `chain` under `lodash-es`? I haven't found any related blog/discussion about this with reasonable explanation.

**Comment by jdalton** [comment]
Long answer is the pieces are there so folks can hack up chaining manually (not recommended).

**Comment by lukeapage** [comment]
This would allow tee shaking and chain (by effectively making chain syntactic sugar) https://github.com/lodash/babel-plugin-lodash/pull/176

**Comment by testerez** [comment]
Another solution could be to build your own chain function that includes only the functions you use:

```js
import map from 'lodash-es/map';
import filter from 'lodash-es/filter';
import mapValues from 'lodash-es/mapValues';
import toPairs from 'lodash-es/toPairs';
import orderBy from 'lodash-es/orderBy';
import groupBy from 'lodash-es/groupBy';
import sortBy from 'lodash-es/sortBy';

// just add here the lodash functions you want to support
const chainableFunctions = {
  map,
  filter,
  toPairs,
  orderBy,
  groupBy,
  sortBy,
};

export const chain = (input) => {
  let value = input;
  const wrapper = {
    ...mapValues(
      chainableFunctions,
      (f) => (...args) => {
        // lodash always puts input as the first argument
        value = f(value, ...args);
        return wrapper;
      },
    ),
    value: () => value,
  };
  return wrapper;
};
```

you can then use your custom chain exactly as the original one.

If you are using **typescript**, you can re-use the typings from `@types/lodash`:
```ts
import map from 'lodash-es/map';
import filter from 'lodash-es/filter';
import mapValues from 'lodash-es/mapValues';
import toPairs from 'lodash-es/toPairs';
import orderBy from 'lodash-es/orderBy';
import groupBy from 'lodash-es/groupBy';
import sortBy from 'lodash-es/sortBy';

// just add here the lodash functions you want to support
const chainableFunctions = {
  map,
  filter,
  toPairs,
  orderBy,
  groupBy,
  sortBy,
};

export const chain = <T>(input: T) => {
  let value: any = input;
  const wrapper = {
    ...mapValues(
      chainableFunctions,
      (f: any) => (...args: any[]) => {
        // lodash always puts input as the first argument
        value = f(value, ...args);
        return wrapper;
      },
    ),
    value: () => value,
  };
  return wrapper as _.LoDashExplicitWrapper<T>;
};
```
