### ISSUE TITLE
_.pick() has (possibly) unintended behaviour when picking object properties that are objects

### ISSUE THREAD

**Issue by mcosletjr** [lodash/lodash#3299]
I've come across the issue described in the following code snippet:
```js
var initialObject = {
  data: {
    name: 'spark'
  },
  someOtherValue: 42
};
var pickedObject = _.pick(initialObject, ['data']);

pickedObject.data.name = 'labs';

console.log(pickedObject.data.name);  // 'labs'
console.log(initialObject.data.name);  // 'labs'
```
It seems that it doesn't return a new `object` but a refference to the initial one (but with the picked properties). It doesn't happen when picking "`non-object`" values, for example (having the same `initialObject`):

```js
var pickedObject = _.pick(initialObject, ['someOtherValue']);

pickedObject.someOtherValue = 0;
console.log(pickedObject.someOtherValue);  // 0
console.log(initialObject.someOtherValue);  // 42
```

I've solved the bug that has bugged me for days (pun intended) by wrapping the `_.pick()` call with the `_.cloneDeep()` to sever the ties between the `objects`.

I wouldn't have submitted a new issue had the [documentation](https://lodash.com/docs/4.17.4#pick) not stated that it `Returns the new object.` (the same problem applies when using `_.omit()`)

**Comment by jdalton** [comment]
Hi @mcosletjr!

This is intended. `pick` just picks values by reference and doesn't clone them.

**Comment by mcosletjr** [comment]
May I suggest that you add this to the documentation of `_.pick()` and `_.omit()`?
