### ISSUE TITLE
additional argument for _.memoize to revert/refresh memoized values

### ISSUE THREAD

**Issue by lgersman** [lodash/lodash#330]
I use lodash together with angularjs. 

i have often the case the a filter condition is used to populate a filtered result set.

it will be really useful to have an additional parameter "condition" (value or function returning the condition) which should be used by _memoize to evaluate if the current cached value is valid or if the cached value should be reverted & replaced by the result of a fresh call to the func argument.

or is there already an option to to this using lodash ?

**Comment by ahamid** [comment]
it's easy to discover the internal object used to cache the data:

` this.__data__ = {};`

but it might be nice to add a simple `clear` method to just clear/reassign it without requiring the caller to mess with the internal field.  (unless there is a better practice for invalidating the entire cache, such as assigning an entirely  new `Cache` object or even re-`memo`-izing the function)

**Comment by jdalton** [comment]
@ahamid Lodash v4 will add the `.delete` method of the `Map` interface.

**Comment by borisdiakur** [comment]
The `clear()` method on the cache object is not documented yet.

**Comment by lgersman** [comment]
+1!

**Comment by sahilkhan99** [comment]
@jdalton , I have written my custom function to clear the cache after 30 seconds like this. Do you see any issue with my implementation?


function timedCustomerProduct(customerNumber, productId, isCard) {
    
    _.delay(function (text) {
        memoizeGetCustomerProduct.cache.delete(productId);
    }, 30000, productId);
    
    return getCustomerProduct(customerNumber, productId, isCard);
}

let memoizeGetCustomerProduct = _.memoize(timedCustomerProduct, function (customerNumber, productId) {
       console.log("cache id " + productId);
        return productId;
    });

export {memoizeGetCustomerProduct};
