### ISSUE TITLE
Request: sortedFind

### ISSUE THREAD

**Issue by Mr-Wallet** [lodash/lodash#3306]
Suppose one wants to perform a binary search on an array in order to find a non-primitive element.

Right now this is impossible in lodash without hand-rolling one's own binary search. However if it were possible to pass lodash a transformation, this would let people get at lodash's binary search capability.

For example, suppose a large sorted array of objects of the shape `{ value: Number }`. Unless I'm mistaken, there's no way to find a specific element except linearly. This need would be served by `_.sortedFind(arr, item => item.value)`.

This might need some workshopping, but basically if it were easier to access the binary search then a common pain point for me would be met.

**Comment by jdalton** [comment]
Hi @Mr-Wallet!

I want to stay away from adding more sorted method variants. It seems like maybe those should be in their own specialized library.
