### ISSUE TITLE
Possible memory leak with _.get(), _.set()

### ISSUE THREAD

**Issue by tlhunter** [lodash/lodash#3307]
I'm doing a bit of experimenting and it appears that the path values provided to `_.get({}, path)` are not being garbage collected. I'm not sure if this issues is in Lodash or in V8, or if it's even an issue at all. While sifting through heapdumps of an application which generates dynamic paths (e.g. `".x.y[id].z"`) I'm seeing a lot of these paths stick around.

Node.js: v8.2.1 / v6.11.2
Lodash: 4.17.4

Here we can reproduce the issue:
```
$ node --inspect --expose-gc
> var _ = require('lodash');
Expression assignment to _ now disabled.
undefined
> gc()
undefined
> process.memoryUsage().heapUsed.toLocaleString()
'6,757,728'
> _.get({}, '.leak'.repeat(Math.floor(Math.random() * 899999 + 100000)));
undefined
> _.get({}, '.leak'.repeat(Math.floor(Math.random() * 899999 + 100000)));
undefined
> _.get({}, '.leak'.repeat(Math.floor(Math.random() * 899999 + 100000)));
undefined
> _.get({}, '.leak'.repeat(Math.floor(Math.random() * 899999 + 100000)));
undefined
> gc()
undefined
> process.memoryUsage().heapUsed.toLocaleString()
'127,944,824'
```

We can even execute those `_.get()` calls in another stack and the memory still leaks.

```js
setTimeout(function() { _.get({}, '.leak'.repeat(Math.floor(Math.random() * 899999 + 100000)));}, 10);
```

While using the Chrome developer tools we can see the strings sticking around:

![2017-08-08-113707_593x285_scrot](https://user-images.githubusercontent.com/551402/29088458-f8b2c74a-7c2d-11e7-82df-9a803e3ee37a.png)

Simply generating the strings doesn't cause them to stick around:

```
$ node --inspect --expose-gc
gc()
undefined
> process.memoryUsage().heapUsed.toLocaleString()
'5,597,176'
> void (x = '.leak'.repeat(Math.floor(Math.random() * 899999 + 100000)))
undefined
> x.length
3448415
> void (x = '.leak'.repeat(Math.floor(Math.random() * 899999 + 100000)))
undefined
> void (x = '.leak'.repeat(Math.floor(Math.random() * 899999 + 100000)))
undefined
> void (x = '.leak'.repeat(Math.floor(Math.random() * 899999 + 100000)))
undefined
> void (x = '.leak'.repeat(Math.floor(Math.random() * 899999 + 100000)))
undefined
> x.length
1498265
> delete x
true
> gc()
undefined
> process.memoryUsage().heapUsed.toLocaleString()
'5,700,472'
>                                                                             
```

**Comment by arboreal84** [comment]
Paths are memoized with a limit of 500 entries.

**Comment by tlhunter** [comment]
https://github.com/lodash/lodash/blob/d8b5183b1d6133a856aebe7b0cfda70e54b7e296/.internal/memoizeCapped.js#L4

Yeah it appears to be intentional feature. Not sure why one would want the cache to reset every 500th time, seems like it would cause a sawtooth in memory. Also, if we somehow skip the 500th entry, jumping to 409 to 501, then the cache would never clear.

**Comment by jdalton** [comment]
Your usage is not the common case. Memoizing helps optimize for the common case which is considerably below 500 unique paths. If this a problem for you feel free to use something else. This is by design and not up for changing.
