### ISSUE TITLE
#contains does not recognize NaN

### ISSUE THREAD

**Issue by bouchard** [lodash/lodash#331]
According to the documentation,
`_.contains([NaN], NaN)` should equal `true`.

Currently:
`> _.contains([NaN],NaN)
false`

**Comment by jonapgar** [comment]
"We smooth over this with methods like _.isEqual and _.where, but not for methods that use strict equality checks."

Just ran into an issue related this "smoothing". This should probably be in the docs. 

Given `NaN!=NaN` I think it is normal to assume `_.isEqual(NaN,NaN)` should return `false`.

**Comment by jdalton** [comment]
`isEqual` is a deep equivalence method. Think of it as a deep form of [Object.is](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is).
