### ISSUE TITLE
Inconsistent return value using `_.round`

### ISSUE THREAD

**Issue by peterbakonyi05** [lodash/lodash#3311]
Using `_.round` you get `NaN` if you pass `undefined` as the first parameter but you get `0` if you pass `null`. This seems like an inconsistent behavior. I think in both cases it should return `NaN` (or maybe 0).

```js
_.round(null, 2); // returns 0
_.round(undefined, 2); // returns NaN
```

Thanks!

**Comment by jdalton** [comment]
Hi @peterbakonyi05!

This is expected behavior of coercing values to numbers.
