### ISSUE TITLE
In FP all of the object iterators have capped iteratees 

### ISSUE THREAD

**Issue by ppalladino** [lodash/lodash#3312]
All of the object iterators (forIn, forInRight, mapKeys, mapValues, transform, etc..) now have capped iteratees. However, many times you need the object `keys` AND `values` when iterating over an object. Especially when order is not guaranteed. I don't believe this is a mistake as I see capping in the code and mentioned in the FP docs. Any suggestions? Oh BTW - FP is a GREAT improvement! Thanks!!

**Comment by jdalton** [comment]
Hi @ppalladino!

You can use [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert).

**Comment by ppalladino** [comment]
Who hoo! Thanks for the clue!
