### ISSUE TITLE
Ask Performance benchmark Uniq lodash

### ISSUE THREAD

**Issue by ardani** [lodash/lodash#3314]
![20728809_1907837189457519_3380745404851219039_o](https://user-images.githubusercontent.com/2499777/29175126-660922d6-7e12-11e7-91dd-efa1f70f5be5.jpg)
it is true?

**Comment by jdalton** [comment]
Hi @ardani!

It depends on the number of elements in the array.
Lodash has heuristic in place to switch techniques internally.
Once an array is big enough it will switch to using built-in `Set` which is faster for large arrays.
