### ISSUE TITLE
Thread last (clojure) support

### ISSUE THREAD

**Issue by itaied246** [lodash/lodash#3315]
Using the `loadsh/fp` library, it could be very useful to add a function like `clojure`'s [thread-last](https://clojuredocs.org/clojure.core/-%3E%3E).

For example:

```
fp_.threadLast(collection, [
    filterPositives,
    filterEvens,
    fp_.map(add5),
    fp_.sum,
])
```

Instead of:

```
fp_.compose([
    fp_.sum,
    fp_.map(add5),
    filterEvens,
    filterPositives,
])(collection)
```

**Comment by jdalton** [comment]
Hi @itaied246!

That looks closer to Lodash's traditional syntax.

We have [flow](https://lodash.com/docs/#flow) which is left-to-right `compose`, but it still produces a function that you'd pass `collection` too.
