### ISSUE TITLE
_.isNumber(NaN) result is true ? 

### ISSUE THREAD

**Issue by heke2929** [lodash/lodash#3318]
confusing~

**Comment by ephetic** [comment]
```
> typeof NaN
"number"
```
JavaScript~

**Comment by heke2929** [comment]
@ephetic i have to use `!_.isNaN()` to judge whether a parameter is a number or not  :(

**Comment by ephetic** [comment]
@heke2929 
```
> !_.isNaN(Infinity)
true
```
[Check out](http://devdocs.io/lodash~4/index#isFinite) `_.isFinite`.

**Comment by heke2929** [comment]
@ephetic i see. thx~

**Comment by jdalton** [comment]
The `isNumber` method checks a value's type not value validation just as `isDate` doesn't validate the date object entry. `Infinity` is a number too but you can use `isFinite` to validate a given number.

**Comment by heke2929** [comment]
@jdalton nice explanation, thanks a lot~
