### ISSUE TITLE
[FR] Third argument to _.memoize - CacheConstructor

### ISSUE THREAD

**Issue by Ginden** [lodash/lodash#3319]
I propose third argument to `_.memoize` function - `CacheConstructor`.

```js
// Before:
const memoized = _.memoize(func, resolver);
memoized.cache = new WeakMap; 

// After:
const memoized = _.memoize(func, resolver, WeakMap);
```

Benefits:

* Can be written in single line
* Harder to miss `.cache` assigment

I can create pull request for it, but I'm not sure if it will be welcome.

**Comment by jdalton** [comment]
Hi @Ginden!

I rather not add another optional param. That would make `memoize` really need an options object.
If there's demand though I'll totally look into making `memoize` accept an options arg.
