### ISSUE TITLE
support Regular Expressions for _.where et al

### ISSUE THREAD

**Issue by jasonkuhrt** [lodash/lodash#332]
For example http://lodash.com/docs#where could accept a regexp for `properties`.

The pattern would be matched
- For arrays, against the value (obvious)
- For objects, against the value (not obvious, how do we support keys?)

I have a use-case right now that equates to this:

```
_.reject(items, new RegExp(removeThing === 'all' ? '.*' : removeThing))
```

**Comment by jperkelens** [comment]
Just curious if this would be pulled in if I implemented it. Seems like it would be a useful to have it baked in to library proper.

**Comment by jdalton** [comment]
@jperkelens I think this is better left as something a dev can mixin so not really open to a PR on it.

**Comment by panuhorsmalahti** [comment]
:+1:, would be quite useful.
