### ISSUE TITLE
customizable fp reduce arity and auto-curry

### ISSUE THREAD

**Issue by doug-numetric** [lodash/lodash#3320]
Best explained with an example

`
a = _.flow(
  _.reduce(_.add)
)([1,2,3])
// f(n,t,r)... expected: 6
`

This can be fixed with:
`
a = _.flow(
  _.reduce(_.add, 0)
)([1,2,3])
`

The docs say that if `accumulator` is not supplied, the first element would be used as the initial `accumulator` value.  With the fixed arity and auto-curry, it's hard not not supply the accumulator argument.

Is there a way to convert `lodash\fp\reduce` so that is has a fixed arity of 2 -- thus always returns a function, It would be easier to spot mistakes like this if the `collection` parameter was required to be applied in isolation to the function that reduce returns.

**Comment by jdalton** [comment]
Hi @doug-numetric!

Your best bet would be to check out the [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert) method.

**Comment by doug-numetric** [comment]
I'm familiar with the convert method, but I don't see how to use it to modify the function arity number.

This seems to to work though...

    const reduceFactory = (f,acc) => _.reduce(f,acc)
    a = _.flow(
      reduceFactory(_.add)
    )([1,2,3])
