### ISSUE TITLE
memoize resolver in lodash/fp

### ISSUE THREAD

**Issue by mvolkmann** [lodash/lodash#3321]
The FP Guide says that memoize has a fixed arity of one.
The non-FP version takes a function to be memoized and an optional resolver function.
How can a resolver be specified in the FP version?

**Comment by jdalton** [comment]
Hi @mvolkmann!

You can checkout the [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert) method. It allows you to toggle fixed arity and argument capping.

**Comment by mvolkmann** [comment]
Cool! This worked for me:
```js
const memoizeWithResolver = fp.memoize.convert({fixed: false});
```
