### ISSUE TITLE
_.isEmpty returns incorrect result for FileList object in IE11

### ISSUE THREAD

**Issue by ajtakrajta** [lodash/lodash#3323]
```
<input id='inputTypeFile' type='file'>

document
  .getElementById('inputTypeFile')
  .addEventListener('change', function(event) {
    var files = event.target.files;
    console.log(files.length); // 1
    console.log(_.isEmpty(files)); // false in Firefox and Chrome; true in IE 11
  });
```
https://jsfiddle.net/jvokvg12/1/

**Comment by jdalton** [comment]
Hi @ajtakrajta!

This is likely because you're dealing with a host object. They're known to not represent themselves properly to JavaScript. For example the `files` value may not appear to be an array that passes `Array.isArray(files)`.

**Comment by ajtakrajta** [comment]
@jdalton, thanks a lot for the quick response. There are two reasons why I would like to ask you to check this issue again:

* `isEmpty` supports several array-like objects and FileList is passing this condition.
* `isEmpty` does not return the same result in IE11 and modern browsers for similar argument. I can describe the reason why this is happening if it would help.

Thank you for you time.

**Comment by olsonpm** [comment]
@ajtakrajta I ran into this now and just created a project utility `isEmpty` which is implemented as `!!_.size`.
