### ISSUE TITLE
is there a fun just like the sql sentence 'left join' ?

### ISSUE THREAD

**Issue by ershing** [lodash/lodash#3325]
is there a fun just like the sql sentence 'left join' ? 
just like this:
```javascript
var x = [{a:1,b:3},{a:2,b:9}];
var y = [{a:1,d:20},{a:2,d:30}];
```
i want to get something like ' select * from x left join y where x.a= y.a'
maybe there is fun like this :
```javascript
var z = _.leftJoin(x,y,a,a)  //  [{a:1,b:3,d:20},{a:2,b:9,d:30}]
```
but i'm confused cause i cannot find it

**Comment by jdalton** [comment]
Hi @ershing!

I don't believe so. If you find a mixin though feel free to post a reference here.
