### ISSUE TITLE
_.toNumber('') returns 0 not NaN

### ISSUE THREAD

**Issue by wangzi6147** [lodash/lodash#3326]
Because `parseInt('')` pr `parseFloat('')` in JS return NaN. The same as '   '.

But in Lodash `_.toNumber('')` or `_.toNumber('   ')` returns 0.

I'm thinking is there any special consideration about this? Returning NaN seems to make sense.

**Comment by jdalton** [comment]
Strings are trimmed and then coerced with `+value` which is why `""` is `0`.
