### ISSUE TITLE
Eval usage

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [lodash/lodash#3328]
I use debounce from lodash in a Web Extension, Mozilla validation get me a warning about Eval used. Is it safely used? (it's the latest version used, taken from the npm package)

![screenshot at 00h04m54s](https://user-images.githubusercontent.com/7016954/29490418-4f825aac-853b-11e7-8b73-7d0ad045beb0.png)

**Comment by jdalton** [comment]
The `eval` function itself is not used but the `Function(...)` constructor is in our [_.template](https://lodash.com/docs#template) method. If you don't use `_.template` you'll be fine. For extension use you can use pre-compiled templates generated using the [lodash-cli](https://lodash.com/custom-builds).

**Comment by ZatsuneNoMokou** [comment]
```
  /** Used as a reference to the global object. */
  var root = freeGlobal || freeSelf || Function('return this')();
```

It's used on the global object, for the browser version, I guess

**Comment by jdalton** [comment]
That branch isn't likely hit either.

**Comment by DrewDennison** [comment]
@ZatsuneNoMokou not completely sure of your use case, but can't you use the https://www.npmjs.com/package/lodash.debounce package if you just need the `debounce` function? If you need a CDN, you can pull it in using https://cdn.jsdelivr.net/npm/lodash@4.17.4/debounce.min.js

**Comment by ZatsuneNoMokou** [comment]
I'm using a custom build with only debounce, and it's in a Web Extension, so external resources isn't the best idea.
