### ISSUE TITLE
es6 Single-Line Arrow Functions

### ISSUE THREAD

**Issue by mmoconnor23** [lodash/lodash#3329]
We've found that es6 single-line arrow function (without curly braces) don't work when used with Lodash's **_.forEach** (could be others, this is what we've encountered). They appear to only be working for one iteration of the loop, instead of for every iteration. 

Here's an example of what happens with Lodash:
![lodash foreach](https://user-images.githubusercontent.com/4010544/29530389-9090134a-8671-11e7-9b35-c5c5646a0fba.PNG)

Here's what happens when using native **forEach**. Note, the same behavior is obtained by using Lodash's **_.map**. This is the expected behavior. 
![native foreach](https://user-images.githubusercontent.com/4010544/29530394-95ed4ba0-8671-11e7-8439-81a9ec29b03b.PNG)

Please let us know if this is expected behavior, or if we can expect a patch to be submitted. Thanks!

**Comment by jdalton** [comment]
Hi @mmoconnor23!

This is expected because our `_.each` methods allow exiting the `each` early if the return value from the iteratee function is `=== false`.

**Comment by mmoconnor23** [comment]
Thanks @jdalton. I guess we were just extremely thrown off by the difference between Lodash and the native implementation.

**Comment by jdalton** [comment]
Ya, it's become a bit of a gotcha with the introduction of arrow functions for sure. I don't know if exiting early will continue in later versions.
