### ISSUE TITLE
function concat minor code issue 

### ISSUE THREAD

**Issue by saintstarrow** [lodash/lodash#3330]
https://github.com/lodash/lodash/blob/912d6b04a1f6b732508a6da72a95ec4f96bda154/lodash.js#L6928
In function concat, index-- should be replaced by --index, or the resulting args would get an unwanted -1 index element.

**Comment by jdalton** [comment]
Hi @saintstarrow!

That's not the case. When index is `0` because the length of the array is `0` then the `while` will exit because `index` of `0` is evaluated before the trailing `--`.

**Comment by saintstarrow** [comment]
Hi, 
When index is 1, while(index--) evaluates to true. When it gets into the loop, index has been turned to 0.  args[index - 1] = arguments[index]; will be  args[ - 1] = arguments[0];
The above logic has been tested with real data as well.
