### ISSUE TITLE
Tag new version?

### ISSUE THREAD

**Issue by dbpolito** [lodash/lodash#3333]
Hey, it's been a time there is no new version on this lib, i'm facing a problem that was fixed on this commit:

https://github.com/lodash/lodash/commit/08a3f533b7f67a0d36f31c92cba5cb1d1c579fea

Basically i'm using Vue and it overwrites `splice` to react to a array value deletion, and right now on current version i simply can't.

With this change it works again.

------

In summary:

Current version of `lodash` `_.remove` isn't compatible with VueJS reactivity.

**Comment by jdalton** [comment]
Hi @dbpolito!

There won't likely be a new version until v5 is released. This is the usual cycle. We're in the heads down prepping v5 phase so fixes for Vue doing goofy things with arrays will have to wait.
