### ISSUE TITLE
Native Promise.resovle in a lodash flow fails

### ISSUE THREAD

**Issue by c-dante** [lodash/lodash#3334]
Putting the native `Promise.resolve` into a lodash flow crashes.

```
const myFlow = _.flow(x => x + 1, Promise.resolve);
myFlow(10);

Uncaught TypeError: #<Window> is not a constructor
    at resolve (<anonymous>)
    at lodash.min.js:49
    at <anonymous>:1:1
```

~~Is there any reason this would happen? If I use other "Promise" implementations, this semantic works.~~

Checked it out -- the following fails as well:
```
Promise.resolve.call({}, 10)
VM177:1 Uncaught TypeError: #<Object> is not a constructor
    at Object.resolve (<anonymous>)
    at <anonymous>:1:17
(anonymous) @ VM177:1
```

Seems you can't pass the native `Promise.resolve` as a function to run ".call", at least in Chrome. You also cannot capture and call Promise. TIL. Closing this issue.

**Comment by c-dante** [comment]
Not a problem with lodash.

**Comment by StreetStrider** [comment]
@c-dante, ye, there're some issues with such functions that not fully behave as functions (especially with `Promise`). This sad me and my «no-so-many-dots» style of programming.
