### ISSUE TITLE
pick should allow deep paths?

### ISSUE THREAD

**Issue by WickyNilliams** [lodash/lodash#3336]
```js
var object = { 'a': 1, 'b': '2', 'c': { d : 3 }};
 
_.pick(object, ['a', 'c.d']);
```

I'd expect this to return:

```js
{
  a : 1,
  d : 3
}
```

but it actually returns

```js
{
  a : 1,
  c: {
    d : 3
  }
}
```

which is equivalent to `_.pick(object, ["a", "c"])`

**Comment by jdalton** [comment]
Hi @WickyNilliams!

Lodash supports deep pick, just not in the way you want. It will construct an object of your picked properties leaving the object namespaces in place. What you want is a bit of a flattening. Maybe this could be done with `reduce`

```js
_.reduce(['a','c.d'], (o, p) => _.set(o, _.get(object, p)), {})
  ```

**Comment by WickyNilliams** [comment]
Aha! That makes sense. I would have realised that had my example been the following:

```js
var object = { 'a': 1, 'b': '2', 'c': { d : 3, e : 4 }};
 
_.pick(object, ['a', 'c.d']);
```

The `d.e` property is excluded from the result.

Thanks!
