### ISSUE TITLE
Feature Requests: reverseByBlock() function

### ISSUE THREAD

**Issue by ariyankhan** [lodash/lodash#3339]
Suppose someone wants to reverse an array by blocks i.e. blocks will be reversed but block contents will not be reversed.

An example:
```javascript
var arr =  [1, 2, 3, 2, 4, 56, 66, 22, 111, 3, 1];
// blocks are A = [1, 2, 3], B = [2, 4, 56, 66], C = [22, 111, 3, 1] so arr = [A, B, C]

var arr2 = reverseByBlock(arr, 2, 6, 10); // only give the last index of every block
// now arr2 = [22, 111, 3, 1, 2, 4, 56, 66, 1, 2, 3] i.e. arr2 = [C, B, A]
// So, blocks are reversed but block contents are not reversed.
```
This function can be used to swap two parts of an array easily.
It can be achieved by _.reverse() function but reverseByBlock() function is a syntactical sugar.

**Comment by jdalton** [comment]
Hi @ariyankhan!

This seems less appropriate for a general utility lib and might be a better fit as a [_.mixin](https://lodash.com/docs#mixin).
