### ISSUE TITLE
map does not work properely on the following data

### ISSUE THREAD

**Issue by siciarek** [lodash/lodash#3342]
const dat = {
    "limit": 10,
    "length": 10,
    "max_pages": 10
  }
// Invalid output:
  map(dat, (key, val) => {
    console.log([key, val])
  })
  
// Works properely:
  Object.keys(dat).map(key => {
    const val = dat[key]
    console.log([key, val])
  })

**Comment by jdalton** [comment]
Hi @siciarek!

Map is a "Collections" method which means it prioritizes array-like values over objects.
You'll want to use "Objects" methods [_.mapKeys](https://lodash.com/docs/4.17.4#mapKeys), [_.mapValues](https://lodash.com/docs/4.17.4#mapValues), or [_.keys](https://lodash.com/docs/4.17.4#keys)+`map`.
