### ISSUE TITLE
SortBy Multiple array numbers

### ISSUE THREAD

**Issue by CarlosSoares** [lodash/lodash#3343]
Hey guys

I found a small issue or at least I think is an issue 😄 .

Basically I want to sort by an simple array but with multiple sorts:
```
sortBy([8, 20, 1], (m) => {
  return m === 1 ? [3, 1] : [0, m];
})
```
The result is `[20, 8, 1]`.

If I change the array to a array of objects
```
sortBy([{key: 8, field: 0}, {key: 20, field: 0}, {key:1, field: 1}], ['field', 'key'])
```
The result is 
```
[{key: 8, field: 0}, {key: 20, field: 0}, {key: 1, field: 1}]
```
So the second example is right but the first one I was expecting in the first example is to give the order `[8, 20, 1]`.

**Comment by jdalton** [comment]
Hi @CarlosSoares!

Using an `iteratee` for `sortBy` you're returning the value by which sorted will be based. In this case you're returning an array which means it will be compared with `>` or `<` or `===`.
