### ISSUE TITLE
Design Question: Why the split for object vs array functions in 5.0?

### ISSUE THREAD

**Issue by nwhatt** [lodash/lodash#3345]
Personally, I think it's a good idea - so 👍 for that. 

I see lodash/lodash gets a lot of asking why a property called "length" breaks _.map, so that has to be part of it. 

Part of me wants to know if there is a deeper philosophical reason. My personal crusade is having people be explicit when decomposing objects - be it via an array literal, `object.keys()`,`object.entries()`, or the future` _.mapObject`. Either way you do it, Object and Array are different, and a developer needs to be somewhat thoughtful of that. 

Also wondering how much changes on the roadmap should be planned for - obviously would like to minimize the amount of re-factor needed to upgrade out apps. 

Also apologies if the issue tracker is not the right place for this - I did an exhaustive search of the repo and couldn't find anything that answered my question.

**Comment by jdalton** [comment]
Hi @nwhatt!

Splitting keeps implementations simpler with fewer interdependencies. The roadmap is our way of giving a heads up. It's not set in stone but it's our plan to date.

**Comment by nwhatt** [comment]
Thanks @jdalton ❤️
