### ISSUE TITLE
[ QUESTION ] create modular lib like Lodash

### ISSUE THREAD

**Issue by hyphaene** [lodash/lodash#3346]
Hi,

I'm heavily interested by the principle of building a little 'utils' library which would be as modular as lodash ( => have the ability to import each function separately, without destructuring the global import ) .

I've read the source code but I don't get how the architecture allows it, nor how npm scripts achieve it.

Could you point out the files or the the ressources you use to do so ?

Since I wasn't able to choose a label, I made it on my own on the title ( please indicate me if i misread something ;) )

Cheers.

**Comment by jdalton** [comment]
Hi @hyphaene!

I originally started out with a monolithic build and used the hand crafted [lodash-cli](https://lodash.com/custom-builds) to split it up. However, this tightly coupled `lodash-cli` to the Lodash source and made maintenance a pain. So for v5 I made one last modular build then retired `lodash-cli`. Now that we have modules we can use a bundler, like webpack, to mush them together when needed.

**Comment by hyphaene** [comment]
Hi,

Thanks for your quick answer. 
And is this build accessible somewhere? 
I'd like to use it a basis to provide a similar experience on imports ! 

Thanks for the label, wasn't able to see where to choose..

**Comment by jdalton** [comment]
> Oups .. I guess you were suggesting me to check to the CLI code ...

I wouldn't recommend it. The code is super Lodash source specific and full of really gross regexes. It's one of the reasons I retired it 😋

**Comment by hyphaene** [comment]
Would you have any suggestion, or any process to indicate me in order to achieve it ?
If you work on your side on such a process, it would be great to be able to contribute to it, and why not design it as tool which would be enough generic to be a basis such the one i need ?
Since I'm starting to be a 'not-so-dumb' javascript developer, I'm willing to contribute whenever I can..
Let me know how our own needs could find a mutual path, I'd be glad to walk on it !

**Comment by jdalton** [comment]
Modularizing your code is a slow and steady process. You can start small with helper functions and spread from there.

**Comment by hyphaene** [comment]
Ok thanks !
