### ISSUE TITLE
Idea: lodash protocols

### ISSUE THREAD

**Issue by spion** [lodash/lodash#3350]
Synopsis: 

Allow external collections (e.g. mobx, immutablejs, mori, etc) to declare lodash compatibility by implementing lodash-specific symbols.

Details:

Whenever someone builds a new collection library, they need to re-implement data manipulation methods. These range from bare minimum (e.g. mobx) to okay (immutablejs) - however, none of them could hope to match the extensive lodash collection.

It seems like ES6 is moving towards a direction where protocols (interfaces) will be more common, with ES6 iterables being one of the more interesting examples.

It would be great if there was a lodash-symbols package which contains symbols of various lodash protocols. A collection library could implement some of these symbols, and lodash could check whether passed objects contain them and attempt to use them.

For example, reduce could be implemented in terms of "lodashIterable"

```js
function reduce(collection, reducer, initialValue) {
  if (typeof collection[lodashIterableSymbol] === 'function') {
    let iterator = collection[lodashIterableSymbol](), reduced = initialValue
    while (iterator.next()) { reduced = reducer(reduced, iterator.value) }
    return reduced
  } else {
    // default impl.
  }
}
```

This can be taken a step further to support existing libraries without monkey patching by providing definition maps. lodash could look up the "getIterator" method from a (weak)map which can be amended by other libraries `definitionMap.get(lodashIterableSymbol).get(obj.constructor)`. Then we would be able to add lodash support to things such as HTML collection elements like `HTMLCollection`, or any other library that doesn't want to implement lodash support itself.

**Comment by jdalton** [comment]
Hi @spion!

This is neat but not really the direction Lodash is going. Lodash v5 will remove the monolithic namespace entirely leaving just modules with nothing to anchor to.

**Comment by spion** [comment]
Sounds great! But those modules still wont work with anything except built-in collections, right? Perhaps the protocol modules could also be separate for different protocols, and then anyone would be able to mix-and-match?

I suppose its a bit too much to expect from a stable and established library. I just thought that lodash has the unique opportunity to set precedent here and pave the cowpaths for a new era in JS... one that has a rich protocol ecosystem where all libraries work together.
