### ISSUE TITLE
Async chainable functional operators

### ISSUE THREAD

**Issue by HeberLZ** [lodash/lodash#3353]
Hi,

I was wondering if there are any plans of supporting chainable async operators on Lodash or in a sibling project in order to be able to better leverage async/await in a functional manner now that it's natively supported in a good chunk of browsers.

Cheers!

**Comment by TrySound** [comment]
I guess it's more rx/most/xstream libraries purpose.

**Comment by jdalton** [comment]
Hi @HeberLZ!

As @TrySound mentioned there are full libraries dedicated to this 😋
