### ISSUE TITLE
Changing Case with plural initialisms

### ISSUE THREAD

**Issue by Gidgidonihah** [lodash/lodash#3354]
Attempting to change case with plural initialisms results in an unpleasant result.

For example `_.kebabCase('orgUUIDs')` becomes `org-uui-ds`. Expected output would be `org-uuids`.

See https://runkit.com/gidgidonihah/lodash-case-initialisms for examples across all case changing functions.

**Comment by jdalton** [comment]
Hi @Gidgidonihah!

We've try to find a good balance when supporting things like this. In this case we opt to treat it as a separate word. For this case you'll have to implement your own helper.
