### ISSUE TITLE
master branch of lodash.sampleSize having incorrect code

### ISSUE THREAD

**Issue by ramesh901** [lodash/lodash#3357]
I copied the code from https://github.com/lodash/lodash/blob/master/sampleSize.js and ran it in my local machine. 
Two issues found:
1) The length of 'array' and length of 'result' are same which is incorrect. The length of 'result' should be n
2)random selection happen within first n elements which is incorrect. The random selection should happen in entire array. Please check the attached snapshot for the code and output. During each run, the first 3 values get swapped and the last 3 values remains same.
![image](https://user-images.githubusercontent.com/29668266/30025040-541dfed0-9194-11e7-9636-b6cfe3275efd.png)
![image](https://user-images.githubusercontent.com/29668266/30025223-12a7618e-9195-11e7-8f57-b6acba7c1b2b.png)

**Comment by jdalton** [comment]
Hi @ramesh901!

Please see the [note here](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#construction-notice-construction).
