### ISSUE TITLE
new functions: find value in collection and create array based on references

### ISSUE THREAD

**Issue by kay999** [lodash/lodash#3360]
I use those often, and they are quite small, so maybe they would be of use for others 

---

'firstFor' gives the first non-undefined value from applying an iterator to a collection. It's similar to find, but while find gives the found element, this gives some calculated value.

```
function firstFor(c, it) {
	const f = iteratee(it);
	let res;
	some(c, (v, k, a) => {
		res = f(v, k, a);
		return res !== undefined;
	});
	return res;
}
```
Example: 
```
data = [{ id:1, name:'x' }, { id:2, name:'y' }];
firstFor(data, v => { if (v.id === 1) return v.name })   // returns 'x'
```

edit: This example may not be very convincing because it can easily solved via 'find'. But most real-world cases work more like this:
```
firstFor(data, v => { 
   const r = someExpensiveCalculation(v);
    if (r >= 1) return r;
})  
```

While this could also be solved via "find", the expensive calculation would be done twice then.

---

'follow' follows a path thru a structure, returning the elements as a list. It doesn't checks for cycles (which could of course be added as an option). 

```
function follow(c, it) {
	let res = [];
	const f = iteratee(it);
	while(c != null) {
		res.push(c);
		c = f(c);
	}
	return res;
}
```

Example: Let there be some objects linked by a 'parent' field, using `follow(o, 'parent')` returns the chain of objects from o to the root.

**Comment by jdalton** [comment]
Hi @kay999!

I think this is better suited as a [mixin](https://lodash.com/docs/4.17.4#mixin).
