### ISSUE TITLE
Outdated standalone functions on npm

### ISSUE THREAD

**Issue by lledey** [lodash/lodash#3361]
Hi, I saw on npm that the standalone function packages are not up to date compared to the ["full" lodash](https://www.npmjs.com/package/lodash) package. For example, [omit](https://www.npmjs.com/package/lodash.omit) is at version 4.5.0 whereas I can see in the changelog that it has been updated a couple times since this version.

Would it be possible to update these standalone packages on npm (pretty please)?

**Comment by jdalton** [comment]
Hi @lledey!

> Would it be possible to update these standalone packages on npm (pretty please)?

Probably not. They won't be continued in v5 and are a major pain for v4. The recommended usage is to use the primary `lodash` package and cherry-pick the methods you want:
```js
import omit from "lodash/omit"
```
