### ISSUE TITLE
webpack tree-shaking is not work with lodash-es.

### ISSUE THREAD

**Issue by zhanfang** [lodash/lodash#3362]
@jdalton When I see you twitter, I found you can use tree-shaking and pure module.
Can you give a example or demo. I have see you issue in webpack https://github.com/webpack/webpack/issues/1750, but it not work.

**Comment by jdalton** [comment]
Hi @zhanfang!

As far as I know the `pure` modules thing of webpack is just a proposal. When it gets further along I'll add support. Until then you can use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash).
