### ISSUE TITLE
feature: inlineSortBy

### ISSUE THREAD

**Issue by reeddunkle** [lodash/lodash#3363]
On a recent task, I needed to mutate the original array.

I ended up with:

```
import sortBy from 'lodash/sortBy';
import tap from 'lodash/tap';

function inlineSortBy(collection, criteria) {
  return tap(collection, () => sortBy(collection, criteria).forEach((value, index) => {
    collection[index] = value;
  }));
}
```

Such as with `_.filter()` vs `_.remove()`, we could have a mutating option.

**Comment by jdalton** [comment]
Hi @reeddunkle!

I think this would be a better fit as a [mixin](lodash.com/docs/#mixin).

**Comment by reeddunkle** [comment]
I'm getting a 404 error on your mixin link

**Comment by ephetic** [comment]
[mixin](https://lodash.com/docs/4.17.4#mixin)
