### ISSUE TITLE
trimLeft and trimRight aliases for v4+

### ISSUE THREAD

**Issue by kptan** [lodash/lodash#3366]
I know a couple of plugins have been provided for lodash v3 to v4 migration but given that trimLeft and trimRight were pretty common functions. Would a request to include these as aliases to trimStart and trimEnd respectively be reasonable?

**Comment by jdalton** [comment]
Hi @kptan!

> Would a request to include these as aliases to trimStart and trimEnd respectively be reasonable?

We've tried to keep aliases to minimum as we've progressed. The fewer aliases the better 😋
