### ISSUE TITLE
Integrity corruption with string case conversion?

### ISSUE THREAD

**Issue by kerbyfc** [lodash/lodash#3367]
Hi, I'm confusing a little by this results:
```js
_.snakeCase(_.camelCase('geo2_json')) !== "geo2_json" // true, result is geo_2_json
```

I found it is not expecting result...
Maybe adding of additional parameter like `skipNumbers` should help?

```js
_.snakeCase(_.camelCase('geo2_json'), true) === "geo2_json" // true
```

**Comment by jdalton** [comment]
Hi @kerbyfc!

We consider the number `2` to be a separate word, using `_.words` you get `["geo", "2", "json"]`. 
Our case methods take compound words split them into separate words and then join them back together in various ways. I'm not looking to expand the options to these methods at this time.

**Comment by elado** [comment]
fwiw - +1 on that.
