### ISSUE TITLE
_.random doc

### ISSUE THREAD

**Issue by AjaxSolutions** [lodash/lodash#3369]
The doc should be changed: random --> pseudo-random.

Wherever the word random is used, it should be changed to pseduo-random.

_Produces a pseudo-random number between the inclusive lower and upper bounds._

This method uses the Math.random method which returns pseudo-random numbers.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

There's a huge difference between a random and pseudo-random number.

A computer is not able to generate random numbers and it's not even possible to prove that a sequence of numbers is random or not.

**Comment by jdalton** [comment]
Hi @AjaxSolutions! 

I'm ok using 'random' since it's the random JS devs know.

**Comment by AjaxSolutions** [comment]
I hear you.  Most JS devs don't care, but some people can be fussy about incorrect terms.

Mozilla doc correctly uses the term pseudo-random, not random.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

**Comment by Billy-** [comment]
@AjaxSolutions If you are aware of the difference between the two, then you know that computers can't generate real randoms. So I don't think this is a problem.
