### ISSUE TITLE
lodash/fp flatMap doesn't behave as regular flatMap : only the value is passed to the iteratee

### ISSUE THREAD

**Issue by iRyusa** [lodash/lodash#3371]
Hi there! 

Don't know if this is intended or not, but `flatMap` in `lodash/fp` doesn't pass extra args to the iteratee func.

As you can see in the regular `lodash` flatMap receive the extra arg :

Step to reproduce : 
```sh
➜  bin git:(next-cli) ✗ node -v
v8.2.1
➜  bin git:(next-cli) ✗ node
> const _fp = require('lodash/fp')
undefined
> const _ = require('lodash')
undefined
> _fp.flatMap((v, k) => console.log(v, k))({a: 'b'})
b undefined
[ undefined ]
> _.flatMap({a: 'b'}, (v, k) => console.log(v, k))
b a
[ undefined ]
> _.VERSION
'4.17.4'
> _fp.VERSION
'4.17.4'
```

**Comment by jdalton** [comment]
Hi @iRyusa!

This is by design. You can customize it with [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert).

**Comment by iRyusa** [comment]
Thanks for the fast answer !

Love the project here, big ❤️ for this awesome lib 👍
