### ISSUE TITLE
differenceWith doesnt spot boolean values

### ISSUE THREAD

**Issue by DiedeGu** [lodash/lodash#3374]
Hi, I might be doing something wrong but I think the differenceWith function does not considered boolean true and false values as different. 

I have done the following:
 _.differenceWith([true, true], [true, false], _.isEqual)
// []
 _.differenceWith([1, 1], [1, 0], _.isEqual)
// []
 _.differenceWith(["true", "true"], ["true", "false"], _.isEqual)
// []
 _.differenceWith(["foo", "foo"], ["foo", "fa"], _.isEqual)
// ["fa"]

**Comment by jdalton** [comment]
Hi @DiedeGu!

The key bit is from the [_.difference](https://lodash.com/docs/4.17.4#difference) doc note:
> Creates an array of `array` values not included in the other
```js
_.difference([2, 1], [2, 3]);
// => [1]
```

From your example
```js
_.differenceWith(["foo", "foo"], ["foo", "fa"], _.isEqual)
// returns [] not ["fa"]
