### ISSUE TITLE
Module size of lodash.findindex

### ISSUE THREAD

**Issue by valorize** [lodash/lodash#3376]
My webpack bundle output revealed that findindex is 62KB big.
"lodash.findindex: 62.79 KB (38.9%)"

Isn't findindex just a simplified version of

```
var index;
arr.some((el, key) => {
  if(condition(el)) { index = key; return true }
  return false;
});
```
?

Is it possible to reduce the size of the npm package / module output?

**Comment by jdalton** [comment]
Hi @valorize!

Keep in mind the largest Lodash can generally be is 24kB minified+gzip for the kitchen sink *(everything)*. Anything else is build-tool theater. You should be using [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) and to take it up a notch use [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin).

**Comment by valorize** [comment]
The plugins are quite cool, and I absolutely will use them. But still I think 62kb (unminified and unzipped) are a bit heavy for a simple method like findindex.

**Comment by ematipico** [comment]
Probably there's something wrong about how you import the function

**Comment by jdalton** [comment]
@valorize 
> (unminified and unzipped) are a bit heavy for a simple method like findindex.

You're right, I should just not ship developer code with inline documentations, comments, and dev helpers because dev builds need to be cautious of their size.
