### ISSUE TITLE
assignIn/extend doesn't include class methods

### ISSUE THREAD

**Issue by wch** [lodash/lodash#3377]
`_.assignIn` does not copy class methods. For example:

```js
class A {
    f() { return 1; }
}

var a = new A;
a.f()  // 1

var a1 = _.assignIn({}, a)
a1.f() // error: a.f is not a function
```

In contrast, for normal objects, it does copy the properties from the prototype:

```js
var B = function() { }
B.prototype.f = function() { return 1; }

var b = new B;
b.f()  // 1

var b1 = _.assignIn({}, b)
b1.f() // 1
```

Both objects get `f` from their prototype:

```js
// Both true:
a.__proto__.hasOwnProperty('f')
b.__proto__.hasOwnProperty('f')
```

Is this expected?

**Comment by jdalton** [comment]
Hi @wch!

That's because class methods are non-enumerable by default.

**Comment by wch** [comment]
@jdalton thanks for the quick reply! That makes sense.

For future reference, this makes the method `f` enumerable:

```js
Object.defineProperty(A.prototype, "f", {enumerable: true})
```
