### ISSUE TITLE
range() function not returning empty array for start>end

### ISSUE THREAD

**Issue by hotaru355** [lodash/lodash#3378]
I expect the following to return an empty array:

`_.range(2, 1) === []`

But, what it returns is:

`_.range(2, 1) === [2]`

Workaround: providing the default step of `1` creates the correct result

`_.range(2, 1, 1) === []`

Is this a defect or expected?

**Comment by jdalton** [comment]
Hi @hotaru355!

If `start` is greater than `end` and `step` is not provided then it's treated as a step of `-1`.
