### ISSUE TITLE
issue api _.map on collection should to send index as well!

### ISSUE THREAD

**Issue by simonjoom** [lodash/lodash#3379]
Hello 

just i wanted to say it's really a pity that you don't send the index for the _.map function then we work on collection too.

For react we need the index when we create on array of component , 

for now i added 
for map on collection

iteratee(value, key, collection,index);  // a 4th parameters index !

What do you think to add this in your api?

**Comment by jdalton** [comment]
Hi @simonjoom!

Folks iterating an object usually aren't looking for an index too. If you want though you can use your own counter variable or simply `push` to the array.

**Comment by simonjoom** [comment]
yes i understand but when we use an object to display a array of component the lack of this give the developper an extra code to add (the counter) . Why not just send the index to the callback as well? (it's what i did)

**Comment by ephetic** [comment]
@simonjoom Why not use the key as the react key? It doesn't need to be a number.
