### ISSUE TITLE
_.literal (like RethinkDB r.literal) to stop recursion of _.merge and _.defaultsDeep

### ISSUE THREAD

**Issue by doug-numetric** [lodash/lodash#3380]
literal could be an ES6 Symbol:
`const literal = {[Symbol('_.literal')]: true};`

Which would be applied to a merge source:

```javascript
let state = { version: 1, person: { name: { first: 'John', middle: 'Q', last: 'Doe' }, phone: '555-555-5555' } };
merge(state, { version: 2, person: { name: { ...literal, ...{ first: 'Jane', last: 'Doe' } } } });
// returns { version: 2, person: { name: { first: 'Jane', last: 'Doe' }, phone: '555-555-5555' } }
```

In some cases it can be a lot more readable than mixing nested assign merge calls.

**Comment by jdalton** [comment]
Hi @doug-numetric!

I think there's something here. Would you mind keeping this as a mixin until it bakes a bit more?

**Comment by doug-numetric** [comment]
@jdalton,

Sure, Is there an example of a similar type of mixin so I can see how that might work? Or are you suggesting that implement a mixin for now until this idea gets more popularity and feedback?
