### ISSUE TITLE
lodash/fp _.includes bug

### ISSUE THREAD

**Issue by JelF** [lodash/lodash#3381]
```
> require('lodash').includes([], 'asd')
false // As expected
> require('lodash/fp').includes([], 'asd')
true // WTF
```

lodash version 4.27.4
node version v7.9.0

**Comment by ephetic** [comment]
I think the answer is in the `Rearranged Arguments` section of https://github.com/lodash/lodash/wiki/FP-Guide

**Comment by jdalton** [comment]
Yep!

Doing `.includes([], "asd")` in FP is like `.includes("asd", [])` in the traditional API.
Since `[]` is coerced to a string which is `""` then `.includes("asd", "")` is `true`.
