### ISSUE TITLE
startCase removes ampersand, all symbols

### ISSUE THREAD

**Issue by benterprise** [lodash/lodash#3383]
_.startCase("one & two") returns "One Two", ideally it'd return "One & Two". Is there a workaround?

**Comment by jdalton** [comment]
Hi @benterprise!

> Is there a workaround?

Not for our casing methods. They break a string into [words](https://lodash.com/docs#words) and then apply transformations on them.

**Comment by KidA001** [comment]
Odd that this method is destructive in terms that it removes characters. I would have expected it to title case what it can and leave everything else.

**Comment by mukeshkamboj** [comment]
@benterprise this is workaround.

```
 "JHON&JOHN C/O DR. BLah".replace(/\w+/g, _.capitalize);
```
result:-

"Jhon&John C/O Dr. Blah"

**Comment by animir** [comment]
This is weird. If function's name is `startCase`, then the only thing developer expects from it is making all words' first letter in capital case. 

I see, this behaviour is shown in examples in docs, but still not clear. It should be clearly mentioned in docs, that it removes any spec symbols.

The best would be to have some option to disable removing spec symbols.

Thanks.

**Comment by thefilmmaking** [comment]
I have to agree with the comments. Had to use the workaround mentioned by mukesh. I can imagine the usefulness of removing all the spec symbols, but I'd say split that into a separate function.

**Comment by seanlindo** [comment]
This caused a mess in our search engine...we really were not expecting this to be a destructive operation.

**Comment by dhasilva** [comment]
Completely agree. A function called `startCase` should do just that and nothing else.
My case is with diacritics: 'não' becomes 'Nao'. That makes absolutely no sense.

**Comment by chryssajones** [comment]
@benterprise's workaround didn't work for me because it capitalized the first letter after a diacritical mark: pōmaikaʻi becomes "PōMaikaʻI", which is not the desired result.

**Comment by DarioLopes** [comment]
And yet as of late 2019, it still not working as expected... for once I started to try this tool a little more deeper and it isn't working

**Comment by jdalton** [comment]
Hi folks!

In v5 we will revisit this.
