### ISSUE TITLE
Shortcut fusion is not working when use drop combined with filter

### ISSUE THREAD

**Issue by galenjiang** [lodash/lodash#3385]
When I use shortcut  fusion below, I find a strange case
```
_(Array(100).fill(1)).filter((i) => {console.log(i);return i}).drop(95).value()
```
it printed 100 times

```
_(Array(100).fill(1)).map((i) => {console.log(i);return i}).drop(95).value()
_(Array(100).fill(1)).filter((i) => {console.log(i);return i}).take(5).value()
_(Array(100).fill(1)).map((i) => {console.log(i);return i}).take(5).value()
```
printed 5 times
why? Is something difference with usage of drop width filter from other combination?

**Comment by ephetic** [comment]
How would it know which 95 are the first to drop without evaluating the filter?  Try `Array(200)` and see if the shortcutting is more satisfying.
