### ISSUE TITLE
`get` cannot be used to get "complete object"

### ISSUE THREAD

**Issue by Domiii** [lodash/lodash#3386]
I would hope to `get` the entire object (the root of the object tree if you will) in case, an empty path is provided. This would put it more in line with traditional data structure behavior: Getting the node at "empty path" within a tree should return it's root in my book. But maybe there are other considerations at hand?

Is there a reason for the extra `index &&` in [baseget#L21](https://github.com/lodash/lodash/blob/master/.internal/baseGet.js#L21)?

What about:

```js
return index == length ? object : undefined
```

instead of:

```js
return (index && index == length) ? object : undefined
```

?

**Comment by jdalton** [comment]
Hi @Domiii!

This is by design.

**Comment by Domiii** [comment]
Ok...

Could you produce some references or information on the design principles behind the decision?

**Comment by jdalton** [comment]
Related to #3276.
