### ISSUE TITLE
Add `pending` property to throttled functions

### ISSUE THREAD

**Issue by chriscalo** [lodash/lodash#3387]
Is there some way of knowing if there are pending invocations of throttled functions? Take this example of a throttled function that sends data in the browser to be saved on the server:

```javascript
const throttledSave = _.throttle(() => {
  server.save(getLatestLocalData());
}, 2000, {
  leading: false,
  trailing: true,
});
```

Because this throttled function can be called many times a second, elsewhere I'd like to be able to track whether there are pending invocations of the throttled function so that I can do useful things like inform users about the status of syncing with the server. If there were a boolean or integer `pending` property on throttled functions, I could do:

```javascript
displayedStatus = throttledSave.pending ? "Saving…" : "Saved";
```

Thoughts? Is there some other workaround I should consider?

**Comment by jdalton** [comment]
@chriscalo I like it. Want to do a PR?

**Comment by chriscalo** [comment]
Eek, I am honored by the vote of confidence, but that's likely not something I would know how to do. 😬

Glad to hear to seems useful, though.

If there are *very* clear and explicit instructions for beginners I could try, but I'd be fumbling through this for the first time.

**Comment by jdalton** [comment]
> Eek, I am honored by the vote of confidence, but that's likely not something I would know how to do. 😬

No worries. Our build and test infrastructure is down for pre-v5 restructuring so it's really just modifying the debounce.js. Things may not be 💯 : but we'll catch them once we spin up *(should be soon as [@std/esm](https://github.com/standard-things/esm) is approaching v1.0)*.

**Comment by chriscalo** [comment]
I was able to get the changes in [this fork](https://github.com/chriscalo/lodash/tree/patch-1) working locally by copying the [debounce.js](https://github.com/chriscalo/lodash/blob/patch-1/debounce.js), [throttle.js](https://github.com/chriscalo/lodash/blob/patch-1/throttle.js), and [isObject.js](https://github.com/chriscalo/lodash/blob/patch-1/isObject.js) files down to my machine, but I did not run any tests.

Is that useful? (In case it is, I'll preemptively send a PR. Feel free to reject it if not.)

Here's the rough implementation I ended up using. It's pretty convoluted, so perhaps there's a cleaner way to accomplish this.

```javascript
const throttledSave = _.throttle(() => {
  api.save(getLatestLocalData()).then(() => {
    setTimeout(() => {
      if (!throttledSave.pending()) {
        setStatus("Saved");
      }
    }, 500);
  })
}, 2000, {
  leading: false,
  trailing: true,
});

const onEdit = () => {
  setStatus("Saving…");
  throttledSave.apply(this, arguments);
};
```

**Comment by jdalton** [comment]
Moved to #3388 😄
