### ISSUE TITLE
Is it possible to deep-clone a Proxy with lodash?

### ISSUE THREAD

**Issue by JanisE** [lodash/lodash#3389]
My proxied object contains an object as a property, so I cannot use `Object.assign` which does a shallow copy. But lodash's `cloneDeep` (and `clone`) returns a clone of the proxied object losing the functionality of `Proxy`.

Is there a way to clone a `Proxy` properly?

**Comment by jdalton** [comment]
Ho @JanisE!

I don't believe so. If you come up with one though you can use [_.cloneWith](https://lodash.com/docs#cloneWith) with [_.partial](https://lodash.com/docs#partial) to create a flavor of clone that does.
