### ISSUE TITLE
each can not work with data which contains length key

### ISSUE THREAD

**Issue by zdwalter** [lodash/lodash#339]
example coffee code:

coffee> _.forEach {a:1, length:1}, (v, k) -> console.log k, v
0 undefined
{ a: 1, length: 1 }

**Comment by mikila85** [comment]
forOwn handles the object as an array anyway! 
It checks if it has .length and sends it to forEach and go through all the 13Milion of undefined records untill it reaches 13Mil which has 1 record in my object key..  amazing..

**Comment by mikila85** [comment]
@jdalton, @tsabolov @janmeier @falsyvalues @zdwalter
