### ISSUE TITLE
IsFunction is slow

### ISSUE THREAD

**Issue by xahon** [lodash/lodash#3390]
Here is a benchmark: https://jsperf.com/lodash-isfunction-vs-typeof-func-function/1

It's by 86% slower than `typeof`
![image](https://user-images.githubusercontent.com/18731681/30771269-7830bd16-a086-11e7-822e-9efbc407f153.png)

I think it is because of this line
https://github.com/lodash/lodash/blob/f5ea579db357e82d46456f3385f6830074275b21/isFunction.js#L25

**Comment by xahon** [comment]
so `async`, `generator` functions typeof also 'function', so i think there is no reason to use `baseGetTag`

**Comment by jdalton** [comment]
Hi @xahon!

Feel free to use `typeof`. The `_.isFunction` is a bit more robust and works in buggy environments that report the wrong value for `typeof`.

**Comment by xahon** [comment]
So may be it'll be better to check env for 'bugs' and then select checking strategy?

**Comment by xahon** [comment]
Perfomance is important for me when i making react-native app where is only one js thread. So if i use `typeof` code doesn't look like one style
