### ISSUE TITLE
Why does the function work differently with the type conversion?

### ISSUE THREAD

**Issue by steeply** [lodash/lodash#3391]
```
lodash.subtract(5, 3)   # => 2
lodash.subtract(5, '3')   # => 2
lodash.subtract('5', '3')   # => 2

lodash.add(2, 3)   # => 5
lodash.add('2', 3)   # => 23 -- ???
```

I use the 'subtract' as an automatic type conversion when performing operations. I would like that the 'add' also converted the string into a number, if suddenly it accidentally hits.

**Comment by jdalton** [comment]
The methods like `add`, `subtract`, and friends all share a common base implementation. What you're seeing is just how JS works.
```js
'5' - '3' // 2
'2' + 3 // "23"
```
