### ISSUE TITLE
[lodash-cli] Support custom extensions

### ISSUE THREAD

**Issue by DanielRamosAcosta** [lodash/lodash#3392]
In the CLI utility, the extension is forced to be `.js`, but Node 8.5.0 ES Modules only support `.mjs`.

Maybe is good to parametrize this setting with a parameter, so ES Modules version works natively in Node.

**Comment by jdalton** [comment]
Hi @DanielRamosAcosta!

The `lodash-cli` package is no longer maintained *(there will be no more releases)*. Instead folks should use the modular `lodash` package + bundler of choice.

**Comment by DanielRamosAcosta** [comment]
Thanks @jdalton, maybe could be good to place a deprectation notice in the README.md?
