### ISSUE TITLE
Wrong documentation or wrong behavior of _.defaultsDeep with empty arrays (different from the _.defaults one)

### ISSUE THREAD

**Issue by rpadovani** [lodash/lodash#3393]
An empty array is not undefined:

```
▶ nodejs
> let a = {b: []}
undefined
> a.b
[]
> a.b === undefined
false
> a.c === undefined
true
> 
```

`_.defaults` documentation (which `_.defaultsDeep` refers to) says `Assigns own and inherited enumerable string keyed properties of source objects to the destination object for all destination properties that resolve to undefined.`

Nonetheless, empty arrays are always overwritten in `_.defaultsDeep`:

```
_.defaultsDeep({a: []}, {a: [1]})
Object { a: Array[1] }

_.defaultsDeep({a: [1]}, {a: []})
Object { a: Array[1] }
```

while they are not in `_.defaults`:

```
_.defaults({a: [1]}, {a: []})
Object { a: Array[1] }

_.defaults({a: []}, {a: [1]})
Object { a: Array[0] }
```

I see that `_.defaultsDeep` uses `_.mergeWith`, and then I understand the behavior, but still I think `_.defaults` and `_.defaultsDeep` should have the same behavior or the difference in the behavior should be well documented

**Comment by jdalton** [comment]
Hi @rpadovani!

That's the nature of a deep recursive assign. Objects will be crawled and augmented.
