### ISSUE TITLE
is there a way to make lodash available in IE10?

### ISSUE THREAD

**Issue by zzzgit** [lodash/lodash#3394]
![image](https://user-images.githubusercontent.com/1060733/30838551-b7ee7d52-a29e-11e7-9ca3-aa79f0f547ab.png)

is there a way to make lodash available in IE10?

**Comment by jdalton** [comment]
Hi @zzzgit!

Lodash is tested in IE11 that doesn't mean it won't work in IE10. Give it a try. If that fails you can always use a polyfill for the missing lang features.
