### ISSUE TITLE
Lodash Memoize Issue

### ISSUE THREAD

**Issue by Kiran554** [lodash/lodash#3395]
When I used `_.memoize` function for my angular filter(with array of objects), it worked like charm. But in one of the cases, I add and delete the data(array items) on the UI which is rendered by `_.memoize` method. I don't see any issue with addition(new array item), for any new item being added `_.memoize` is being called every time as expected. But when I delete(existing array item) an item, I don't see `_.memoize` getting called. which is leading to some headaches. Any directions/help is much appreciated. Thanks!

**Comment by TrySound** [comment]
@Kiran554 And how do you add and delete those items?

**Comment by jdalton** [comment]
Hi @Kiran554!

You'll find general support over at [our gitter chat](https://gitter.im/lodash/lodash).
