### ISSUE TITLE
How to use _.words in lodash/fp?

### ISSUE THREAD

**Issue by gabrielhpugliese** [lodash/lodash#3397]
What exactly am I doing wrong here? (Lodash 4.17.4)

```
> var fp = require('lodash/fp'); var _ = require('lodash');
undefined
> fp.words(/[^/]+/g, '/aaa/bbb-ccc/ddd/')
[ 'g' ]
> fp.words('/aaa/bbb-ccc/ddd/', /[^/]+/g)
[ 'aaa', 'bbb', 'ccc', 'ddd' ]
> _.words('/aaa/bbb-ccc/ddd/', /[^/]+/g)
[ 'aaa', 'bbb-ccc', 'ddd' ]
```

**Comment by jdalton** [comment]
Hi @gabrielhpugliese!

Based on [the guide](https://github.com/lodash/lodash/wiki/FP-Guide) `words` has a fixed arity of `1`. You can customize this with [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert).
