### ISSUE TITLE
How is lodash published?

### ISSUE THREAD

**Issue by afraser** [lodash/lodash#3398]
I found this issue from 2013 (https://github.com/lodash/lodash/issues/269) that requests publishing of individual methods. I'd like to understand how this works but it appears that the script that does this isn't included in this repo.

It looks like this script referenced in package.json is the one that does it: `"node lib/main/build-modules.js"`

Is there any way you could point me to this code or make it public? Thanks.

**Comment by jdalton** [comment]
Hi @afraser!

We used to use `lodash-cli` to modularize and bundle individual method packages. However, in v5 we'll stick to a single modular package.

**Comment by afraser** [comment]
Thanks @jdalton !
