### ISSUE TITLE
find with index does not work as expected

### ISSUE THREAD

**Issue by KamBha** [lodash/lodash#3400]
The [documentation ](https://lodash.com/docs/4.17.4#find) states that the third argument to find is an index.

_.find(collection, [predicate=_.identity],  [fromIndex=0])

However, I can't seem to get this to work.  That is, when I specify the from index in the example below:-

```
var users = [
  { 'user': 'barney',  'age': 36, 'active': true },
  { 'user': 'fred',    'age': 40, 'active': false },
  { 'user': 'pebbles', 'age': 1,  'active': true }
];
 
_.find(users, function(o) { return o.age < 40; }, 1);
```

I would expect to see pebbles returned.  Instead, I see Barney.  Am I misunderstanding the documentation?

**Comment by ephetic** [comment]
What version?  Your sample code works for 4.17.4: https://repl.it/LgBy

**Comment by KamBha** [comment]
Sorry, my mistake (I think).

Let me do some further testing and get back to you.

**Comment by KamBha** [comment]
@ephetic I am seeing some weirdness on my unit test.  I am not sure what I am doing wrong, but I must be doing something wrong.  I cannot replicate.  I am closing this issue.
