### ISSUE TITLE
getIfHas performance versus has->get

### ISSUE THREAD

**Issue by vitaly-t** [lodash/lodash#3401]
This is just to share some comparative performance figures of `lodash` versus custom implementation, and possibly a suggestion for a hybrid method for `has -> get` logic.

Copied from here: https://github.com/vitaly-t/pg-promise/issues/407

```js
// returns object {has, value}
function getIfHas(obj, prop) {
    const result = {};
    if (prop.indexOf('.') === -1) {
        result.has = prop in obj;
        result.value = obj[prop];
    } else {
        const names = prop.split('.');
        for (let i = 0; i < names.length; i++) {
            const n = names[i];
            if (obj && typeof obj === 'object' && n in obj) {
                obj = obj[n];
            } else {
                result.has = false;
                return result;
            }
        }
        result.has = true;
        result.value = obj;
    }
    return result;
}
```

Performance advantage versus `has -> get` calls in `lodash`:

* 300% when `prop` contains nested properties
* 500% when `prop` is a simple property name

Tested on Windows 10, under Node.js 8.5.0

---

P.S. Sorry for the ES6 syntax, this shouldn't be an issue ;)

**Comment by vitaly-t** [comment]
@jdalton pardon, what is `invalid` here?

**Comment by jdalton** [comment]
Oh boy
