### ISSUE TITLE
Getting different deep path results with packaged version of `pick`

### ISSUE THREAD

**Issue by peteboere** [lodash/lodash#3402]
Using latest of both am getting different deep path results with packaged version of `pick`

```json
{
    "lodash": "4.17.4",
    "lodash.debounce": "4.0.8",
    "lodash.merge": "4.6.0",
    "lodash.pick": "4.4.0"
}
```
```js
let pick = require('lodash.pick');
// let {pick} = require('lodash');

var object = { 'a': 1, 'b': '2', 'c': {d: 3} };
var result = pick(object, ['a', 'c.d']);

console.log(result);
// With lodash => { a: 1, c: { d: 3 } }
// With lodash.pick => { a: 1 }
```

**Comment by jdalton** [comment]
Hi @peteboere!

That's expected since they're different versions.
Deep property support for pick was added after v4.4.0.

The individual method modules like `lodash.pick` are being discontinued in favor of just the modular `lodash/pick` usage.
