### ISSUE TITLE
_.getOr Documentation

### ISSUE THREAD

**Issue by jjerome00** [lodash/lodash#3403]
I can't find any documentation for the `_.getOr` function.  

I've been able to figure it out by looking at other code for the project I'm working on, but I think that others may never know this function exists.  Am I missing something?

**Comment by jdalton** [comment]
Hi @jjerome00!

Our `_.getOr` method is only part of `lodash/fp` which has a [guide wiki](https://github.com/lodash/lodash/wiki/FP-Guide). The `_.getOr` method flavor accommodates the variadic arg signature of `get` which allows providing a default value.
