### ISSUE TITLE
dropRightWhile treats 1 = true and 0 = false

### ISSUE THREAD

**Issue by alanelias** [lodash/lodash#3406]
```javascript
let items = [
    {
        id: 0,
        title: "Item 0"
    },
    {
        id: 1,
        title: "Item 1"
    },
    {
        id: 2,
        title: "Item 2"
    }
];

_.dropRightWhile(items, { id: 0 }); // it doesn't work because 0 is `false` in the object

_.dropRightWhile(items, { id: 1 }); // it doesn't work because 1 is `true` in the object

_.dropRightWhile(items, { id: 2 }); // it work because 2 is integer in the object

```

I don't wanna search for ~boolean~ i wanna search for integer

I know i can pass a custom function but it would be nice to pass it as object thanks!

@param {Function} predicate The function invoked per iteration.

**Comment by jdalton** [comment]
Hi @alanelias!

Passing an object as the `iteratee` param is shorthand for creating a `match` like predicate function that returns `true` for partial deep matches of objects. You should try using a plain function and see how that goes.
