### ISSUE TITLE
lodash-es modules should be published to NPM with ".mjs" extension

### ISSUE THREAD

**Issue by jacksonrayhamilton** [lodash/lodash#3407]
Using lodash-es 4.17.4, if I try to run the following file in Node 8.5.0:

test.mjs:

```js
import {map} from 'lodash-es';
```

```
node --experimental-modules test
```

Then the following error occurs:

```
SyntaxError: The requested module does not provide an export named 'map'
    at checkComplete (internal/loader/ModuleJob.js:86:27)
    at moduleJob.linked.then (internal/loader/ModuleJob.js:69:11)
    at <anonymous>
```

This is because the files published to NPM do not have the ".mjs" extension.  Can you please publish the package with the files with Node-compatible extensions so the package can be used natively?

**Comment by jdalton** [comment]
Hi @jacksonrayhamilton!

I won't be publishing Lodash modules as `.mjs`. I'm discontinuing `lodash-es` for v5 and moving `lodash` to ES modules using [`@std/esm`](https://github.com/standard-things/esm).

**Comment by jacksonrayhamilton** [comment]
Great!  [`@std/esm`](https://github.com/standard-things/esm) seems like a transparent solution to the backwards compatibility issue that was imminent for Node modules.

When can we expect v5 to be released so that Lodash methods can be importable?

**Comment by jdalton** [comment]
> When can we expect v5 to be released so that Lodash methods can be importable?

I'll start ramping up v5 development after `@std/esm` goes v1.0 *(should be in a couple of weeks)*.

**Comment by DanielRamosAcosta** [comment]
Any updates on this?

**Comment by jdalton** [comment]
Hi @DanielRamosAcosta!

The [`esm`](http://npmjs.com/esm) has been released and can be used to publish and consume ESM modules.
