### ISSUE TITLE
_.findIndex, _.findLastIndex returning -1 

### ISSUE THREAD

**Issue by duvemula** [lodash/lodash#3410]
Hi @jdalton,
 I observed that _.findIndex(), _.findLastIndex() returning -1 even we have element in array
Example:
var names = ['E', 'A', 'O', 'I', 'M'];
_.findIndexOf(names,'O');//Expected value: 2
                                       //actual value: -1
Can you please take a look.
Regards,
Durga Prasad

**Comment by Hank-wood** [comment]
There is no findIndexOf method
```
var names = ['E', 'A', 'O', 'I', 'M'];
_.indexOf(names,'O')
```

**Comment by duvemula** [comment]
Can you please try with _.findIndex().
and _.indexOf() also returning -1 .

Regards,
Durga Prasad

**Comment by evenfrost** [comment]
It's working as expected on [lodash.com](https://lodash.com/).
```js
_.indexOf(['E', 'A', 'O', 'I', 'M'], 'O') // 2
_.findIndex(['E', 'A', 'O', 'I', 'M'], val => val === 'E') // 2
```
@duvemula please check your code once again.

**Comment by duvemula** [comment]
I checked on  lodash.com.
I used like _.findIndex(['E', 'A', 'O', 'I', 'M'], 'O') then it returning -1.
when used like _.findIndex(['E', 'A', 'O', 'I', 'M'], val => val === 'E') it returning expected output(i.e: 0)

Thanks for information
