### ISSUE TITLE
toNumber(null) returns 0

### ISSUE THREAD

**Issue by joelove** [lodash/lodash#3411]
The **toNumber** function returns `NaN` if given `undefined` or a string that doesn't parse as a number. And, as expected, `toNumber(1)` and `toNumber(0)` return `true` and `false` respectively. However, I was extremely surprised to find out that `toNumber(null)` returns `0`.

In my understanding, null means "no value provided", which is quite distinct from the value zero. For example, if you're working with the value of a currency field in an API response, you might expect the value to be a valid number (or a number as a string) or null. I might use `toNumber(cashAmount)` to make sure I was working with a number value before doing arithmetic. This could be extremely problematic for obvious reasons.

Is this the intended behaviour of the function? And, if so, why?

P.S. If not, I'm happy to submit a PR.

**Comment by jdalton** [comment]
Hi @joelove!

Yes, this is intended. The language will coerce `null` to `0` so we used that hint to do the same.
