### ISSUE TITLE
Add ability to start _.flow() with an expression

### ISSUE THREAD

**Issue by lindem** [lodash/lodash#3412]
I'd like to be able to do elixir-pipe-operatoresque flows, like this:

    _.flow(1,
        x => x + 1
        x => x * 5)()

so that I wouldn't be required to look at the lower right to find the parameter, but find it right at the beginning of the chain. I am aware that I could just use `_.constant` or an arrow function like `() => 1`; however, maybe there is a chance that expressions might become allowed as the first parameter? Maybe someone in here has an alternative proposal?

Thoughts?

**Comment by c-dante** [comment]
Flow creates a function that composes together n functions. It's not an implementation of the pipeline proposal.

**Comment by lindem** [comment]
That's a real shame, but thanks.
