### ISSUE TITLE
_.get and _.set sometimes treat a string number for an object key as an array element index

### ISSUE THREAD

**Issue by justinmealey** [lodash/lodash#3414]
When attempting to do the following:

```
var myObject = {
	1: {
		a: {
			2: 'test'
		}
	}
};

_.set(myObject, ['a','3','d'], 'test');
```

Produces the odd result:
```
{
  "1": {
    "a": {
      "2": "test"
    }
  },
  "a": [
    null,
    null,
    null,
    {
      "d": "test"
    }
  ]
}
```

**Comment by jdalton** [comment]
Hi @justinmealey!

This is by design. By default we treat index values as creating an array if an object value doesn't exist. You can customize this behavior with [_.setWith](https://lodash.com/docs/4.17.4#setWith).
