### ISSUE TITLE
Feature request: _.isNodeList()

### ISSUE THREAD

**Issue by etoxin** [lodash/lodash#3415]
There is currently no method to check for the NodeList type.
https://developer.mozilla.org/en-US/docs/Web/API/NodeList

NodeList objects are collections of nodes such as those returned by properties such as Node.childNodes and the document.querySelectorAll() method.

It can also be returned like so:

```
var parent = document.getElementById('parent');
var child_nodes = parent.childNodes; // the type of child_nodes is NodeList
```

lodash currently has all other "isXXX" types. eg. `isString()`, `.isElement`, etc.

For full coverage of types, I'd assume you would want NodeLists. You already support browser-specific methods like `_.isElement()`

**Comment by etoxin** [comment]
You will also want to look into `HTMLCollection`
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection

**Comment by etoxin** [comment]
A simple way to currently do it is with:
```
NodeList.prototype.isPrototypeOf(document.querySelectorAll('div'))
```

**Comment by samhunta** [comment]
What is a real world example use case for this functionality?

**Comment by jdalton** [comment]
Hi @etoxin!

Lodash has `_.isElement` which I'm not super happy with. I'll let DOM related libs tackle this kind of thing.

**Comment by samhunta** [comment]
Agreed
