### ISSUE TITLE
isEqual is returning true for objects that are not the same

### ISSUE THREAD

**Issue by melvsparks** [lodash/lodash#3419]
IsEqual is returning true when comparing two arrays of Objects. The exact failure case is between these two location array items.

using version 4.5.0

"[{"persona":{"postalAddress":{"Street":"","City":"Steilacoom","State":"Washington","Country":"United States","PostalCode":"","PostOfficeBox":null,"Type":"Home","Latitude":47.173,"Longitude":-122.598,"LocationUri":"https://www.bingapis.com/api/v6/localentities/351a29b6-f904-0906-4ec1-cd0eaf47f9bd","LocationSource":"LocationServices"},"displayName":"Steilacoom"},"isContextMenuOpen":false,"isSelected":false,"isPersonaCardOpen":false}]"

"[{"persona":{"displayName":"Nordstrom","postalAddress":{"Street":"500 Pine St","City":"Seattle","State":"WA","Country":"United States","PostalCode":null,"PostOfficeBox":null,"Type":"Business","Latitude":47.6123,"Longitude":-122.336,"FormattedAddress":"500 Pine St, Seattle, WA","LocationUri":"https://www.bingapis.com/api/v6/localbusinesses/YN873x128951300","LocationSource":"LocationServices"},"displayAddress":"500 Pine St, Seattle, WA, United States","initials":"N","textBoyColor":0,"personaBlob":{"blobUrl":"blob:https://outlook-sdf.office.com/b72b9e18-67a2-48e4-9a99-0f2acafa62f5","isPendingFetch":false,"hasFetchFailed":false},"selectionSource":"LocationWell","personaType":"Place","personaControlId":"https://www.bingapis.com/api/v6/localbusinesses/YN873x128951300","relevanceData":{"relevanceHint":"NonHistory","locationIndex":0,"transactionId":"16861766-3c28-48b4-a9ff-6ffece997241","locationFeedbackId":"https://www.bingapis.com/api/v6/localbusinesses/YN873x128951300","queryString":"nordstrom"}},"isPersonaCardOpen":false,"isContextMenuOpen":false,"isSelected":false}]"

**Comment by ephetic** [comment]
The `_.isEqual` of these returns false for me: 
https://repl.it/M0as

**Comment by melvsparks** [comment]
I'm using isEqual version 4.5.0

**Comment by melvsparks** [comment]
@jdalton what is the latest version for isEqual and lodash?

**Comment by melvsparks** [comment]
Looks like it was mobx observable arrays causing the issue. The repro is here
https://repl.it/M0as/4

**Comment by ephetic** [comment]
Cool.  Weirdness.

**Comment by akraines** [comment]
I had a similar issue, and calling toJS to convert it to a regular js object didn't work for a nested array.
I solved this issue by using _.isEqualWith:
```
const mobxArrayCustomiser = (first,other)=>{
            let reInvoke = false;
            if (isObservableArray(first) || isObservableArray(other)) {
                first = first.peek();
                reInvoke = true;
            }
            if (isObservableArray(other)) {
                other = other.peek();
                reInvoke = true;
            }
            if (reInvoke) {
              return _.isEqualWith(first,other,mobxArrayCustomiser);  
            } 
        }
        const prev = this.props; 
        const cur = nextProps; 
        if (!_.isEqualWith(prev,cur,mobxArrayCustomiser)) {
}
```
