### ISSUE TITLE
type in typescript findKey

### ISSUE THREAD

**Issue by theGABS** [lodash/lodash#3422]
I look in your code  (or typescript .d.ts not you?)

`node_modules/@types/lodash/index.d.ts line: 15221`

```
findKey<TValues, TObject>(
   object: TObject,
   predicate?: DictionaryIterator<TValues, boolean>
): string;
```
You say findKey return just string, but why you did not write more specifically

```
findKey<TValues, TObject>(
   object: TObject,
   predicate?: DictionaryIterator<TValues, boolean>
): keyof TValues;
```

So if i use something like 

`findKey({a: 5,b: 6,c: 7}, item => item === 6) `
result type be 'a' | 'b' | 'c'. 

My lodash v = 4.17.4

**Comment by falsyvalues** [comment]
Hi @theGABS!
We don't maintain the typings. I believe that's Definitely Typed.

**Comment by jdalton** [comment]
@theGABS Look to [@types/lodash](https://www.npmjs.com/package/@types/lodash).
