### ISSUE TITLE
How to zipObject for an array of array

### ISSUE THREAD

**Issue by booker-laputa** [lodash/lodash#3423]
Input:
var keys = ["a", "b"],
var data = [ ["1", "1"], ["2", "2"], ["3", "3"] ];

Expected Output:
[
    {a: "1" , b: "1"},
    {a: "2" , b: "2"},
    {a: "3" , b: "3"},
]

How can I do this with lodash?

**Comment by elhesuu** [comment]
```
var keys = ["a", "b"];
var data = [ ["1", "1"], ["2", "2"], ["3", "3"] ];
_.map(data, _.partial(_.zipObject, keys));
```

**Comment by falsyvalues** [comment]
Hi @booker-laputa!

For general support questions please visit lodash [gitter chat](https://gitter.im/lodash/lodash).
