### ISSUE TITLE
Too many files

### ISSUE THREAD

**Issue by Klemen1337** [lodash/lodash#3424]
Hi,
I'm working on a project that uses nwjs where at the end of the day file count is important. Your package has 1051 files that contains 10 or so lines. Would you consider merging files in one large file? That way window/linux/osx have less files to copy.

Cheers,
K

**Comment by TrySound** [comment]
@Klemen1337 You can bundle them by yourself. Small chunks let's to optimize scripts for web. Your requirements are quite specific.

**Comment by jdalton** [comment]
Hi @Klemen1337!

The file count in a package doesn't necessarily correlate to files loaded. For package apps though you should be bundling (with webpack or other) and optimizing to remove unused files.

**Comment by Klemen1337** [comment]
Fixed, removed 2100 files! :beer: 
find node_modules/lodash -type f -name "*js" -not -name "lodash.js" -not -name "lodash.min.js" -delete
