### ISSUE TITLE
lodash anonymous define issue

### ISSUE THREAD

**Issue by zeeshan1001** [lodash/lodash#3426]
I am facing a problem with anonymous define. My code base uses lodash as a dev dependency and I am trying to use Cylindo 360 viewer. I get the following error.

require.min.js:8 Uncaught Error: Mismatched anonymous define() module: function () {
      return _;
    }
http://requirejs.org/docs/errors.html#mismatch
    at G (require.min.js:8)
    at Q (require.min.js:15)
    at Object.e [as require] (require.min.js:27)
    at requirejs (require.min.js:33)
    at Function.k.config (require.min.js:33)
    at viewer.js:4434

**Comment by jdalton** [comment]
Hi @zeeshan1001!

Lodash defines itself as an anonymous AMD module (to allow aliasing it as "underscore") but that can sometimes cause conflicts. That is a require.js error. You should ping their tracker. I've forgotten the specifics of it.
