### ISSUE TITLE
Test ?

### ISSUE THREAD

**Issue by andreGarvin** [lodash/lodash#3427]
Does this project have test @bnjmnt4n @jfmengels @jridgewell

**Comment by jdalton** [comment]
Hi @andreGarvin!

Yes, [it does](https://github.com/lodash/lodash/tree/4.17.4). The master branch is a bit of a mess in prep for v5 but you can find tests in our release branches. We test on [various Node versions](https://travis-ci.org/lodash/lodash/builds) and [various browsers](https://saucelabs.com/beta/builds/81d54ba2fef74daf9fe20c82fb4c4a3c).

**Comment by tpoisseau** [comment]
@jdalton why do you put that mess on master instead of create a branch `dev` or `dev-v5` or what ever.

master is the default branch, only fonctionnal code should be here, not WIP code.
