### ISSUE TITLE
`Map` equality with `_.isEqual()`

### ISSUE THREAD

**Issue by escKeyStroke** [lodash/lodash#3428]
Hi. Please take a look at this:
``` javascript
const m1 = new Map([['y','x']]);
const m2 = new Map([['x','y']]);
_.isEqual(m1,m2); // true, SHOULD BE false
```
To be sure that `m1` and `m2` are different:
``` javascript
m1.get('y'); // "x"
m1.get('x'); // undefined
m2.get('y'); // undefined
m2.get('x'); // "y"
```
Thanks!

**Comment by jdalton** [comment]
Hi @escKeyStroke!

Nice find! For v5 we'll be deferring to Node's [soon to be `util.isDeepStrictEqual`](https://twitter.com/jdalton/status/917408196553187328). It looks like it has the same issue so you should [file a bug on Node](https://github.com/nodejs/node/issues) for it's `assert.deepStrictEqual`.

**Comment by josephg** [comment]
`deep[Strict]Equal` checking for maps and sets was only added in node version 8. Update nodejs.

**Comment by mbostock** [comment]
Are there any plans on fixing this bug in v4?

**Comment by hoeni** [comment]
To be honest, I use lodash in many aspects to *not* rely on the underlying platform, but get a consistent behavior assured, so this answer is very unsatisfying :-(

**Comment by That3Percent** [comment]
This is still broken.

**Comment by mcintyret** [comment]
Still broken... pretty scary that such a widely-used library mishandled such a widely-used data structure!!
