### ISSUE TITLE
Missing `concatAll`?

### ISSUE THREAD

**Issue by jazen** [lodash/lodash#3429]
I'm just opening the issue here because Google didn't provide a "top hit answer" and a colleague wondered why there's a `mergeAll` but no `concatAll`.

Correct me if I'm wrong but imho the reason is you don't need it because it's already there:

```
const concatAll = Array.prototype.concat.bind([])
```

Please close the issue if that's all what needs to be said.

**Comment by jdalton** [comment]
Thanks @jazen!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

Related to #828.
