### ISSUE TITLE
Why does maxBy return an object instead of a number?

### ISSUE THREAD

**Issue by josh-egan** [lodash/lodash#3430]
I was surprised today when using `_.maxBy` for the first time to find that instead of returning a number, like `sumBy`, `meanBy`, and other functions do, `maxBy` returns the entire object that contains the max value.

I can see how some people may find that useful to have the object returned, but it could also be a bit misleading. There may be multiple objects that all share the maximum value, but only one of them is going to get returned. It seems more consistent with other lodash functions for `maxBy` to return a number, and in the event that the entire object was needed, the developer could specify in the next line of code the rules for getting the object[s] with the maximum value.

So I guess I'm wondering why the decision was made to return the object instead of the numerical value, and if it would be possible to change this behavior in a future release.

**Comment by jdalton** [comment]
Hi @josh-egan!

The `maxBy` method will return the element in the array that is computed to be the max by the `iteratee`. It turns whatever element that is *(an object or otherwise)*.

**Comment by josh-egan** [comment]
Thanks @jdalton .

Any thoughts in regards to these questions?

> So I guess I'm wondering why the decision was made to return the object instead of the numerical value, and if it would be possible to change this behavior in a future release.

**Comment by jdalton** [comment]
Returning the element gives devs the freedom to do with the element what they wish. Also the criteria for sorting may not be a single point of data.

**Comment by ephetic** [comment]
@josh-egan you could make your own mixin consistent with the other math methods:

```
const _ = require('lodash')
_.mixin({
  maxValue: (xs, it) => {
    const fn = _.isFunction(it) ? it : _.property(it)
    return fn(_.maxBy(xs, fn))
  }
})

const data = [{a:11}, {a:44}, {a:44}, {a:0}]
_.maxValue(data, 'a')  // 44
```
