### ISSUE TITLE
some question about .internal/assignValue

### ISSUE THREAD

**Issue by Dcatfly** [lodash/lodash#3432]
```javascript
function assignValue(object, key, value) {
  const objValue = object[key]
  if (!(hasOwnProperty.call(object, key) && eq(objValue, value)) ||
      (value === undefined && !(key in object))) {
    baseAssignValue(object, key, value)
  }
}
```
I think this statement(`(value === undefined && !(key in object))`) will never be passed.
Because if `hasOwnProperty.call(object, key) === true` then `(!(key in object)) === false`.

**Comment by jdalton** [comment]
Hi @Dcatfly!

One is a own property check and the other is an inherited property check.

**Comment by Dcatfly** [comment]
Hi @jdalton 
Thank you for your reply, but you don’t understand what I mean。
Suppose:
A = `!(hasOwnProperty.call(object, key) && eq(objValue, value))`
B = `(value === undefined && !(key in object))`
C = `hasOwnProperty.call(object, key)`
D = `!(key in object)`
I think if the implementation of the B, then it means that A is false, that is, C is true, so D is false.
So when B is executed, B must be false.

**Comment by brickmaker** [comment]
I have same question and don't understand...
