### ISSUE TITLE
Looping over object collections containing a property "length" treated as array

### ISSUE THREAD

**Issue by andimeier** [lodash/lodash#3435]
When trying to find out if any of an object's properties is undefined, you might want to use this construct:

    _.some({ a: 1, b: 2, len: 10 }, v => _.isUndefined(v))
    => false

Result: `false` (as expected). No undefined values.

But when the property `length` is used:

    _.some({ a: 1, b: 2, length: 10 }, v => _.isUndefined(v))
    => true // !!

Result: `true`.

The same problem with other functions:

    _.map({ a: 1, b: 2, length: 10 }, v => _.isUndefined(v))
    => [true, true, true, true, true, true, true, true, true, true]

(tested with v4.17.4)

Note: as a workaround, I used this construct:

    _.values({ a: 1, b: 2, length: 10 }).some(v => _.isUndefined(2))

**Comment by falsyvalues** [comment]
Hi @andimeier !

Please read the [documentation](https://lodash.com/docs/4.17.4#forEach), especially the **note** part.
