### ISSUE TITLE
New function proposed: isUndefinedDeep

### ISSUE THREAD

**Issue by leoyli** [lodash/lodash#3437]
Hi, I'm proposing a new function checking if an arbitrary nested key in an object is undefined, namely `isUndefinedDeep`, which takes this object represented by a string as its argument.

Typically, we can check if an objet, `obj`, is existed and with a meaningful value by `!!(typeof obj !== 'undefined')`, if `obj` is not declared or undefined. In lodash, I know we have `isUndefined` which can check if an variable is `undefined`, but it may not work upon an nested objet with a missing parent key. But what if we want to check `parent.child`?  If `parent` is not existed, it will resulted in a `ReferenceError`. In this case we have do something like `!!(typeof parent !== 'undefined')&&(typeof parent.child !== 'undefined')`, but what if I have a very deep nested structure? So here comes `isUndefinedDeep`.

Basically, this function required the user have some knowledge for his/her data structure. Because we can not pass an object with a missing parents as an argument at all time in JS; but we can pass a string instead and do an evaluation by eval function in a loop. The loop will break if finding an undefined in any layer and pass `false`, and resulted in `true` if all defined.

The useful scenario, for example, I want to know if `area.garden.apple.size` is existed first, then do some stuff based on the information of the apple size. But somehow not all of my garden in all area have planted that apple tree. Since I know my data structure, i.e. I know I can get the `size` information under `apple` properties, I'm just have no idea if `apple` is available in some `garden`. Then I can just call `isUndefinedDeep('area.garden.apple.size')` to check if `size` is available for me and have no `ReferenceError` due to missing parent keys.

Here is a raw idea on how the codes should look like:
```javascript
function isUndefinedDeep (string) {
  if (typeof string !== 'string') throw new SyntaxError('invalid argument');

  const nestedKeyArray = string.split('.');
  let accumulatedSequence = nestedKeyArray[0];

  for(let i = 1; i < nestedKeyArray.length+1; i++) {
    if (typeof eval(accumulatedSequence) === 'undefined'){
      return true;
    }
    accumulatedSequence = `${accumulatedSequence}.${nestedKeyArray[i]}`;
  }

  return false;
}
```

Any thoughts?

**Comment by jdalton** [comment]
Hi @leoyli!

You can use [_.has](https://lodash.com/docs#has) or [_.hasIn](https://lodash.com/docs#hasIn) to check if a property exists and then check the value.

**Comment by c-dante** [comment]
I also want to point out to you `_.get` and `_.getOr` if you intend to use the value as well.
