### ISSUE TITLE
Support Asynchronous Iteratees

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash#3438]
When using lodash, we often have cases where we'd like iteratees to do async things. Most of the time, we can get away with things like `_.map` in conjunction with a `Promise.all`, but there are some cases where this falls apart. A great example of this (and the use case that triggered this issue) is `find` - I want to return the first item in a list that matches some async criteria, and support early exiting to avoid wasting computation when it's not needed.

Now that both native promises and async/await are shipped in all modern browsers and node, I think it's safe to say that it's here to stay as a core part of the JS ecosystem. Is there a plan to support asynchronous iteratees in lodash?

**Comment by jdalton** [comment]
Hi @daedalus28!

No plans. I punt async concerns to [async](https://www.npmjs.com/package/async) :yum:

**Comment by daedalus28** [comment]
That's fair, but there are so many awesome lodash methods that aren't in asyncjs, asyncjs is callback based instead of promise based (so async/await requires promisification), and asyncjs doesn't have something like lodash/fp.

It seems like it could be something implemented via an API like fp's `convert` and (assuming you've abstracted the actual iteration) seems like it might be possible without too many changes. I really hope you'll reconsider 🙏  And if not, would you be open to an extraordinarily ambitious PR?
