### ISSUE TITLE
isEqual behavior

### ISSUE THREAD

**Issue by shrynx** [lodash/lodash#3439]
**NOT AN ISSUE**
Just curious is it intended behavior to match primitives with their primitive objects.
`isEqual` matches primitives compared with their objects result

```javascript
_.isEqual(new String('abc'), 'abc')
// true

_.isEqual(new Boolean(true), true)
// true

_.isEqual(new Number(100), 100)
// true
```
shouldn't these be false ?

**Comment by TrySound** [comment]
@shrynx Shouldn't. There is native operator `===` for your purpose. Lodash and other libraries are used to hide language effects and shortcomings.

**Comment by jdalton** [comment]
HI @shrynx!

This is one of the trickier parts of `isEqual` is that it's an equivalence method (so a bit loose). Over time I've seen strict forms split out of these methods. In Lodash v5 I plan to defer to Node's soon to be `util.deepStrictEqual` when available.

**Comment by shrynx** [comment]
@TrySound 
Thanks for responding, i understand that, was just wondering since ramda doesn't consider them equal
https://github.com/ramda/ramda/blob/master/test/equals.js#L30-L35

@jdalton 
Thanks for clarifying, was just confused as ramda was treating it differently. 
Looking forward to v5 :)
