### ISSUE TITLE
Placeholder doesn't work for converted functions unless explicitly recurried

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash#3440]
When using `convert` on functions from lodash fp, they seem to lose their support for using `_` as a placeholder. If I explicitly call `curry` on the result, they regain their placeholder support. Here's a full test case showing a failing test:

```js
import _ from 'lodash/fp'

describe('lodash test', () => {
  it('placeholder for converted functions', () => {
    let mutableUnset = _.unset.convert({ immutable: false })
    let x = {
      a: 1,
      b: 1
    }
    console.log(mutableUnset.placeholder) // <-- Seems to be lodash
    console.log(mutableUnset.placeholder == _) // <-- false

    let unsetInX = mutableUnset(_, x)
    unsetInX('a') // <--- throws `TypeError: unsetInX is not a function`
    console.log(x)
  })
  it('placeholder for explicitly curried converted functions', () => {
    let mutableUnset = _.curryN(2, _.unset.convert({ immutable: false }))
    let x = {
      a: 1,
      b: 1
    }
    console.log(mutableUnset.placeholder) // <-- Seems to be lodash
    console.log(mutableUnset.placeholder == _) // <-- true

    let unsetInX = mutableUnset(_, x)
    unsetInX('a') // <--- works because of the explicit curry above
    console.log(x) // { b: 1}
  })
})
```

**Comment by jdalton** [comment]
Hi @daedalus28!

Is there a `.placeholder` property on the `mutableUnset` function?

**Comment by daedalus28** [comment]
Yes, there is. It appears to be a lodash instance, but it is not the same one as what's imported. I'm updating my original post to include the lines I added to test for placeholder

**Comment by daedalus28** [comment]
In the one with the explicit curry, `mutableUnset.placeholder == _` is true

**Comment by jdalton** [comment]
Can you try using the `mutableUnset.placeholder` placeholder for the `unsetInX` assignment.

**Comment by daedalus28** [comment]
Yup, using `mutableUnset.placeholder` instead of `_` works. It seems like something in the conversion is creating a clone of lodash or something like that - it doesn't seem to be an issue with the function of placeholder itself

**Comment by jdalton** [comment]
Nice!

This [is by design](https://github.com/lodash/lodash/blob/4.17.4-npm/fp/_baseConvert.js#L374) and also why we bolt on the `.placeholder` prop to methods. Lodash allows creating its world again to avoid cross contamination of state and settings. This is part of that.

**Comment by daedalus28** [comment]
I don't think anyone would expect that behavior. Why does simply calling convert create an entirely new instance of lodash?

**Comment by daedalus28** [comment]
In practice, this means every method I convert I'll also have to manually re-curry. If nothing else, converting should optionally allow preserving the placeholder instance.

Also, does that mean every time I call convert on a method, I'm creating a whole new instance of lodash in memory? That seems less than ideal from a performance standpoint.

**Comment by jdalton** [comment]
`lodash` itself is converted to `lodash/fp` so converting methods. You might be able to avoid currying by simply replacing the `.placeholder` value.
```js
mutableUnset.placeholder = _
```

**Comment by jdalton** [comment]
If that works I'll patch `fp` to automatically do that.

**Comment by daedalus28** [comment]
Yup, reassigning works:

```js
it('placeholder for converted functions', () => {
    let mutableUnset = _.unset.convert({ immutable: false })
    let x = {
      a: 1,
      b: 1
    }
    mutableUnset.placeholder = _
    console.log(mutableUnset.placeholder == _) // <-- true

    let unsetInX = mutableUnset(_, x)
    unsetInX('a') // <--- Works :D
    console.log(x)
  })
```

**Comment by daedalus28** [comment]
I would happily do the PR myself but I'm not sure where the code for convert is - it doesn't seem to be in this repo

**Comment by jdalton** [comment]
Rock :yum:!

Don't worry, our master branch is a mess with v5 prep, I'll patch in an isolated branch.

**Comment by daedalus28** [comment]
@jdalton not to be annoying, but any idea on an ETA for that fix being published?

**Comment by jdalton** [comment]
@daedalus28 
> not to be annoying, but any idea on an ETA for that fix being published?

No ETA yet. Thanks for keeping it on my radar though.

**Comment by daedalus28** [comment]
@jdalton is it possible to push a 4.17.5 that just adds this in?

**Comment by daedalus28** [comment]
@jdalton Not to be annoying, but it's been almost 2 months. Any chance of getting the patch released as 4.17.5?

**Comment by jdalton** [comment]
When we do a backport of webpack's `sideEffects` flag this will likely get swept up with that. I'm not actively working on v4 right now. My attention is on v5.

**Comment by daedalus28** [comment]
@jdalton There's been a couple of fix revision releases, but I haven't seen this in yet. Was it just missing in the changelog, or is this still open?

**Comment by jdalton** [comment]
Ah @daedalus28!

This totally did not get fixed. I missed it 😱
I can prepare a patch to do a minor release by end of day Friday.

**Comment by daedalus28** [comment]
@jdalton did that happen?

**Comment by jdalton** [comment]
Annnnd I missed it. _(the three day weekend got me)_.

**Comment by jdalton** [comment]
It's in my email marked as `important` so I should keep seeing it :)

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash/commit/2de676fe76bc68fb279ac84c1c87d59511ced8cc.
