### ISSUE TITLE
sortBy: Change example to demonstrate ordering with multiple iteratees

### ISSUE THREAD

**Issue by danthegoodman** [lodash/lodash#3441]
https://lodash.com/docs/4.17.4#sortBy

The current example for `_.sortBy` yields the same result regardless of the ordering of the iteratees.

```js
var users = [
  { 'user': 'fred',   'age': 48 },
  { 'user': 'barney', 'age': 36 },
  { 'user': 'fred',   'age': 40 },
  { 'user': 'barney', 'age': 34 }
];

_.sortBy(users, ['user', 'age']);
// => objects for [['barney', 34], ['barney', 36], ['fred', 40], ['fred', 48]]

_.sortBy(users, ['age', 'user']);
// => objects for [['barney', 34], ['barney', 36], ['fred', 40], ['fred', 48]]
```

My suggestion is to change the age of one of the fred or barney users to highlight the priority of the iteratees ordering.

```js
var users = [
  { 'user': 'fred',   'age': 48 },
  { 'user': 'barney', 'age': 46 },  //<-- Changed to 46 from 36
  { 'user': 'fred',   'age': 40 },
  { 'user': 'barney', 'age': 34 }
];

_.sortBy(users, ['user', 'age']);
// => objects for [['barney', 34], ['barney', 46], ['fred', 40], ['fred', 48]]

_.sortBy(users, ['age', 'user']);
// => objects for [['barney', 34], ['fred', 40], ['barney', 46], ['fred', 48]]
```

**Comment by jdalton** [comment]
Would you be up for creating a PR?

**Comment by danthegoodman** [comment]
@jdalton Thanks for the quick response!

Sorry to be a bother, but I can't find the `_.sortBy` function on the master branch. If I read between the lines, it looks like you're dropping it in favor of the `orderBy` function. How would you like me to submit such a PR? If you are getting rid of the `sortBy` function, then I no need is required on my end.

**Comment by jdalton** [comment]
Ah drat, you're right. We are dropping it in favor of just `orderBy`.
Got so excited about a doc contrib that I didn't look 😊 

If you find anything else feel free to send a PR our way.
