### ISSUE TITLE
Feature Request for _get

### ISSUE THREAD

**Issue by ahedreville** [lodash/lodash#3442]
Hi all
_get is returning the property path object value.
But what if I need the property object itself?
I would do like to get the property path object reference instead of the value.
Can we have a new utiliy feature called i.e.  "_getRef" that will return the property path object reference?
Sometimes we need access to the object reference, not the value.
i.e. when we want add knockout observers to it, or on other edges cases, etc.

**Comment by c-dante** [comment]
What are you referring to? There is no such thing as a reference to a primitive in JavaScript.

```
const playerA = { name: 'c-dante', score: 123 };
const playerB = { name: 'ahedreville', score: 456 };
const myObj = {
  gameState: {
    players: [ playerA, playerB ],
    time: 10,
  },
};

// Path to an object returns the reference
_.get(myObj, ['gameState', 'players', 0]) === playerA;
_.get(myObj, ['gameState', 'players', 1]) === playerB;

// A number isn't a reference -- unsure what you intend?
_.get(myObj, ['gameState', 'players', 0, 'score']) === 123;
```

**Comment by jdalton** [comment]
Hi @ahedreville!

If you're talking about getting the parent object you can always pop or slice the last element of your path. If you're talking about empty paths returning the object you can use a ternary operator to avoid the method call if your path is empty.
