### ISSUE TITLE
Why number is response empty = true ?

### ISSUE THREAD

**Issue by phattranky** [lodash/lodash#3443]
Hi there,

I got a strange issue, Is it right? Please help me check the picture

![1](https://user-images.githubusercontent.com/6443154/31850316-17997042-b67a-11e7-82c1-462dc4178364.PNG)

**Comment by brandon93s** [comment]
This is the expected behavior. 

Docs: https://lodash.com/docs/#isEmpty

> Checks if value is an empty object, collection, map, or set.

> Objects are considered empty if they have no own enumerable string keyed properties.

> Array-like values such as arguments objects, arrays, buffers, strings, or jQuery-like collections are considered empty if they have a length of 0. Similarly, maps and sets are considered empty if they have a size of 0.
