### ISSUE TITLE
_.xor returns 

### ISSUE THREAD

**Issue by EliazTray** [lodash/lodash#3444]
[https://runkit.com/eliaztray/59edc6ccf4d03e00120cccea](link)

VERSION = 4.17.4 

the code return [2,3,4]

but in Version = 4.16.1

return [2,3,1,4]

base on `Symmetric_difference`, the result should be in version 4.16.1

**Comment by jdalton** [comment]
Hi @EliazTray!

The expected result of `_.xor([1,2],[1,3],[1,4])` is `[2, 3, 4]`.

Related to #3355.
