### ISSUE TITLE
_.forEach is not a  function in template 

### ISSUE THREAD

**Issue by zhangya5847** [lodash/lodash#3446]
version: 4.17.4
when i get data from API,i need to render a template with the data.Then,i have an error.

![image](https://user-images.githubusercontent.com/15855773/31987091-5358bef4-b930-11e7-99be-541397f679c0.png)
I refer to the example from the official website.
`// Use the "evaluate" delimiter to execute JavaScript and generate HTML.
var compiled = _.template('<% _.forEach(users, function(user) { %><li><%- user %></li><% }); %>');
compiled({ 'users': ['fred', 'barney'] });
// => '<li>fred</li><li>barney</li>'`

**Comment by jdalton** [comment]
Hi @zhangya5847!

I can't reproduce the issue. From the website I've opened the dev console and tried the snippet and it works.
