### ISSUE TITLE
In .internal/stringToPath.js, the rePropName works weird...

### ISSUE THREAD

**Issue by BuptStEve** [lodash/lodash#3447]
Hi~ @jdalton 

Since [this commit](https://github.com/lodash/lodash/commit/5e38259044047c1a5f2e2e7010800872ed29a0f7),  the rePropName cannot match some path like 

```js
'a[0].b[0].c'
```
In `.internal/stringToPath.js`, the result is 

```js
stringToPath('a[0].b[0].c') // ["a", "0].b[0", "c"]
```

**Comment by jdalton** [comment]
Neat!

But this isn't in a released bit. For example the following works in v4.17.4:
```js
_.toPath('a[0].b[0].c')
// => ["a", "0", "b", "0", "c"]
```
If you'd like to patch our WIP bits feel free to submit a PR.
