### ISSUE TITLE
After changing _.templateSettings.interpolate, old templates delimiters throw errors.

### ISSUE THREAD

**Issue by thirdcreed** [lodash/lodash#3449]
If I change the interpolation options.  Like this:
`_.templateSettings.interpolate = /_ooo_([\s\S]+?)_ooo_/g;`
This works:
`var compiled = _.template('_ooo_foo_ooo_')({foo:'a'});`
But this throws an error:
`var compiled = _.template('_ooo_foo_ooo_ <%= bar %>')({foo:'a'});`
like this:
```
SyntaxError: Unexpected token =
    at Function (<anonymous>)
```

It's a weird use case but essentially I have a large string that gets decorated across several services on completely different machines.  I need to be able to fill out some details at one point and leave some to be filled out later.  I feel like ideally lodash should treat `<%=` as an unremarkable string, if I've changed it's interpolation options.

**Comment by thirdcreed** [comment]
Figured it out.  
So even though I changed the interpolation delimiter (`<%=`), the evalutate delimiter (`<%`) is still triggering.  

So it's reading this `<%=  %>` , as `<%    =   %>`, and then throwing a syntax error due to that = sign not making sense in an evaluation.

If you want to preserve those `<%= %>`'s you have to change the evaluation delimiter as well.

**Comment by jdalton** [comment]
Thanks for working through it @thirdcreed!
