### ISSUE TITLE
Don't import whole lodash

### ISSUE THREAD

**Issue by srigi** [lodash/lodash#3450]
You're importing whole `lodash` module in your sources just to call one or two methods of it.
Either import individual packages (`lodash.forown`, `lodash.pick`) or change deps. to `lodash-es` and import like 

```js
import pick from 'lodash-es/pick'
```

Otherwise users of this library are penalised that their bundle.js contains whole lodash.js even if they're not using it.

**Comment by falsyvalues** [comment]
Hi @srigi!

As you may see on `master` branch lodash v5 will be fully modularized.

**Comment by harshes53** [comment]
Hi @falsyvalues, I’ve been tracking master branch for sometime, and I’d like to know that do we have any milestone or a target release/beta date for v5? 

Thanks!

**Comment by jdalton** [comment]
Hi @harshes53!

I try to target January releases for major versions of Lodash.

**Comment by falsyvalues** [comment]
@harshes53, @jdalton was faster and more accurate I guess :heart:

**Comment by harshes53** [comment]
@falsyvalues yes he's active on github. 

@jdalton thanks for the heads up mate!
