### ISSUE TITLE
[Doc] Update document for _.set to include Array

### ISSUE THREAD

**Issue by yuit** [lodash/lodash#3452]
Hi~ thank you for all  the work you do!. I have one minor request to update the doc. (I can't find instruction to send PR on updating documentation 😢)

_.set supports Array as well (https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L13651)  However, the document only include `_.set` under `Object`

**Comment by jdalton** [comment]
Hi @yuit!

This is by design. I don't want to have to list all the object-ish value types so in an effort to simplify things I went with just "Object" which is the bigger basket to lump other object sub types into.
