### ISSUE TITLE
Slice

### ISSUE THREAD

**Issue by KingJeason** [lodash/lodash#3453]
`
start = start == null ? 0 : start
end = end === undefined ? length : end // Why not write the following situation =>end = end == null ? length : end 
`

**Comment by jdalton** [comment]
Hi @KingJeason!

Because null is converted to 0.

**Comment by KingJeason** [comment]
console.log(0 == null) // false
why null is converted to 0?

**Comment by jdalton** [comment]
```js
Number(null) // 0
```

**Comment by KingJeason** [comment]
I'm sorry, I don't understand,
where is Number(null)
Why not write the following situation:
end = end == null ? length : end // when end is null, end = length, when end is undefined ,end = length
`
// from lodash
start = start == null ? 0 : start
 end = end === undefined ? length : end
`
i dont know why start use == null but  end use === undefined,

**Comment by KingJeason** [comment]
My English is not good. If there is any improper speech, please forgive me

**Comment by ephetic** [comment]
Are you asking why the [implementation of slice](https://github.com/lodash/lodash/blob/master/slice.js#L20) defaults the values of `start` and `end` differently?
```js
  start = start == null ? 0 : start
  end = end === undefined ? length : end
```

I believe it is to get the following behavior (which matches `Array.prototype.slice()`)

```js
_.slice([11,22], undefined, undefined) //=> [11,22]
_.slice([11,22], null, undefined) //=> [11,22]
_.slice([11,22], null, null) //=> []
```
The assumption must be that if you omit the `end` argument (`undefined`) you want it to default to `length`, but if you explicitly pass `null` then you want something else.  (That something else in this implementation is just letting the `null` fall through where it ends up acting like a `0` in the comparisons and arithmetic.)

**Comment by KingJeason** [comment]
Thank you @jdalton @ephetic !
