### ISSUE TITLE
clone behaviour on references

### ISSUE THREAD

**Issue by mifi** [lodash/lodash#3454]
Consider this example
```
const obj1 = {b: 1};
const obj2 = {a: obj1, b: obj1};
const cloned = _.clone(obj2);

cloned.a === cloned.b // true
```
These sub-objects are equal also in `cloned`. But when doing the same with `JSON.parse(JSON.stringify(obj2))` the outputted sub-objects are not equal.
I'm assuming this is what's intended, but at least for me, I expected cloneDeep to work similarily to JSON.parse(JSON.stringify) in this regard. Maybe we could clarify and add this example to the lodash docs?

This causes issues for me when I use it for cloning a state object with React.

**Comment by jdalton** [comment]
Hi @mifi!

The `_.clone` method performs a shallow clone (so just one level deep). Beyond that things are assigned by reference (not cloned).

**Comment by mifi** [comment]
Ah, sorry, I put the wrong method in the example. What I meant was _.cloneDeep, like this:

```
const obj1 = {b: 1};
const obj2 = {a: obj1, b: obj1};
const cloned = _.cloneDeep(obj2);

cloned.a === cloned.b // true
```

**Comment by jdalton** [comment]
Ah okay, our `cloneDeep` method supports cloning circular references :yum:
