### ISSUE TITLE
_.create(null)

### ISSUE THREAD

**Issue by sebastien-p** [lodash/lodash#3455]
Hello,

Looks like [9 months ago](https://github.com/lodash/lodash/commit/b0980a90fc83bc92e040f905ebed8196f895949c) you refactored `_.create` to handle passing `null` as `prototype` just like `Object.create` does.

But, as today, version 4.17.4 still doesn't include this refactoring. When do you plan on publishing a new version?

Thanks for the good work 👍

**Comment by jdalton** [comment]
Hi @sebastien-p!

With [@std/esm](https://github.com/standard-things/esm) stabilizing I'd guess Lodash v5 will land Jan 2018 *(so in a couple months)*
