### ISSUE TITLE
The wrap function expose the fn as the first param

### ISSUE THREAD

**Issue by shikelong** [lodash/lodash#3456]
I want use _.wrap to add some behavior to my function. But the return value of _.wrap expose the fn param.

Example: 
![2017-10-30_142717](https://user-images.githubusercontent.com/4499997/32157880-2f66b87a-bd81-11e7-83d5-556490adf9d0.png)

p('text') work well.
But p(otherFn, 'text') will override the _.escape's behavior.

So how to get a clean wrapper only has the wrapped function's arguments list?

Regards.

**Comment by jdalton** [comment]
Hi @shikelong!

This method is not appropriate for obfuscation.

**Comment by shikelong** [comment]
Thank you.  I noticed the thing that the param name of _.wrap is value instead of fn.
