### ISSUE TITLE
Cannot find module 'lodash.escaperegexp'

### ISSUE THREAD

**Issue by m1m6** [lodash/lodash#3457]
Hi, i'm facing this error when attempting to run my project, i think this utility is broken that's why i got an exception in my project, early today it was working correctly without any error, i didn't add any code to the project, after i got this error, i removed the node-modules and reinstall the dependencies and still got it 

"lodash": "^4.17.2",

**Comment by jdalton** [comment]
Hi @m1m6!

`npm info lodash.escaperegexp` still returns something.
If you want to use it in the `lodash` package the path is `lodash/escapeRegExp`.
