### ISSUE TITLE
_.trimStart didn't return as expect

### ISSUE THREAD

**Issue by jchuai** [lodash/lodash#3459]
_.trimStart('replay_postman_order', 'replay_') expect return 'postman_order', but return 'ostman_order'. 

Test with version 4.17.4

**Comment by coyotte508** [comment]
It returns `_postman_order` (test: https://runkit.com/embed/qdqzng9r85av)

**Comment by jdalton** [comment]
Hi @jchuai!

The second param to the trim methods is `chars` a string of characters to remove (individually).
