### ISSUE TITLE
Lodash fails to install on NPM

### ISSUE THREAD

**Issue by AwesomeTech10** [lodash/lodash#3461]
I am trying to work on a project, and that project uses Lodash.

My problem is during 

```bash
finalize: sill finalize /node_modules/@types/lodash
```
Lodash does this:
```bash
npm ERR! path /node_modules/@types/lodash
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/node_modules/@types/lodash' -> '/node_modules/@types/.lodash.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

My log is attached here:
https://gist.github.com/AwesomeTech10/5883744574839b1489fe53070e4365c8

**Comment by jdalton** [comment]
Hi @AwesomeTech10!

Probably just an npm hiccup. That's `@types/lodash` btw which is not related to the `lodash` package.
