### ISSUE TITLE
Add string functions to compare with ignore case

### ISSUE THREAD

**Issue by ghafran** [lodash/lodash#3463]
Would be great to have new functions that help with string comparisons (with ignore case) similar to https://www.npmjs.com/package/ignore-case.

```
_.stringEqual(string1, string2)
_.stringIncludes(string, searchString[, position])
_.stringStartsWith(string, searchString[, position])
_.stringEndsWith(string, searchString[, position])
_.stringIndexOf(string, searchString[, position])
```

Adding options to auto trim,  ignore case, and check for null, undefined, empty would be nice. 

By default enable ignore case, auto trim.

**Comment by buoyantair** [comment]
I can work on this =D

**Comment by jdalton** [comment]
Thanks @ghafran!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by buoyantair** [comment]
Ohh Cool.

**Comment by ro31337** [comment]
This needs to be done

**Comment by DRSDavidSoft** [comment]
Considering the other features that `lodash` offers, this seems to be a necessity.

**Comment by dkretsch12** [comment]
@jdalton Is this popular enough yet?

**Comment by Velua** [comment]
I can see a few of these have been implemented, anything for ignoringCase though?

**Comment by joewelds** [comment]
I found this page looking for this option.
