### ISSUE TITLE
Suggestion: add note in documentation for APIs that will become deprecated in a future version

### ISSUE THREAD

**Issue by fr0** [lodash/lodash#3464]
For example, v5 will remove `_.omit` according to the [roadmap](https://github.com/lodash/lodash/wiki/Roadmap). It would be wonderful if the current documentation for `omit` contained a note for this function saying that it isn't long for this world, so people who might add call sites to their code are aware that their code will break when they upgrade.

**Comment by jdalton** [comment]
Hi @fr0!

There's no hurry for folks to upgrade once a major release is issues as current apps that work will continue to work. I want to avoid tying myself too tightly to the roadmap.
