### ISSUE TITLE
Question: Duplicate NaN check ?

### ISSUE THREAD

**Issue by Nbsaw** [lodash/lodash#3466]
`toFinite` method has been checked `NaN`. Why checked again in `toInteger` last line ...

https://github.com/lodash/lodash/blob/102d9e34d71838c027b5fc3d9153187f50842c95/toInteger.js#L32

https://github.com/lodash/lodash/blob/102d9e34d71838c027b5fc3d9153187f50842c95/toFinite.js#L37

**Comment by jdalton** [comment]
@Nbsaw would you like submit a PR to remove the extra check?

**Comment by Nbsaw** [comment]
@jdalton of course !
