### ISSUE TITLE
lodash/fp get does not have an arity of two

### ISSUE THREAD

**Issue by danielo515** [lodash/lodash#3468]
Hello,

I understand that you don't have time to write extensive documentation for the fp variant of lodash. Today I found that get is reported to have an arity of two. Seems that the default value option is missing on the FP variant.
Despite you are not going to add this to the FP version of get, I think you should spend some lines explaining what the "fixed arity" actually means. I though that it meant that the first function (the curried one) has an arity of X, representing the values the non-fp version takes, and then it returns a function taking the actual data.
Something like

```js
const getX = get('x','default')({x:'hello'}
```

It's hard to figure how functions work just by looking at the FP docs.

Regards

**Comment by jdalton** [comment]
Hi @danielo515!

You can use the FP `_.get` variant of `_.getOr`.

**Comment by danielo515** [comment]
Hey @jdalton thanks for pointing to it. Where in the documentation is this kind of relation specified ?

thanks

**Comment by galenjiang** [comment]
I think lodash is bralliant. But it's lack of fp document, I don't wanna find the document in issue. Thank you all the same.

**Comment by jdalton** [comment]
See the [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide) for more info.
