### ISSUE TITLE
_.clone throws on arrays, maps and sets whose constructor is no longer a function

### ISSUE THREAD

**Issue by fmartin5** [lodash/lodash#3474]
``` 
console.log(_.VERSION); // '4.17.4'

const myArray = [];
myArray.constructor = null;
_.clone(myArray);
```
`TypeError: array.constructor is not a function`
``` 
const myMap = new Map();
myMap.constructor = null;
_.clone(myMap);
```
`TypeError: map.constructor is not a function`
``` 
const mySet = new Set();
mySet.constructor = null;
_.clone(mySet);
```
`TypeError: set.constructor is not a function`

**Comment by jdalton** [comment]
Hi @fmartin5!

This is a known limitation. In order to clone values from the correct realm we'll need a reference to their constructor.

**Comment by fmartin5** [comment]
Alright I get it, thanks for your quick reply @jdalton!

So, `_clone` and `_.cloneDeep`  are not free of possible side-effects, because not only native constructors but also custom constructors can be called during the operation? I could not tell it from the documentation (no occurence of the strings "constructor" or "side-effects" at [clone](https://lodash.com/docs/4.17.4#clone), [cloneDeep](https://lodash.com/docs/4.17.4#cloneDeep) nor in the linked [MDN article](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)). Though I think this is an important point, enough to be mentioned in the docs. For example I am a bit worried about users calling `_clone` or `_.cloneDeep` on objects from untrusted sources. I am not saying the algo should be changed, just that users should be warned.

Also, regarding my original use case, I think a custom error message, from Lodash itself, could be useful to let the user know s/he has stumbled on a well-known limitation and not on a bug. 

For example, something like:
`"Cannot clone the given object: its constructor is missing or not callable."`

**Comment by jdalton** [comment]
For built-ins we're a bit more trusting than for generic user-land objects.
