### ISSUE TITLE
_.sum should type cast to Number or throw an error when summing strings

### ISSUE THREAD

**Issue by brunoluiz** [lodash/lodash#3477]
# Expected:

The `sum` method is located on the Math section of the docs, which should mean that only numeric operations will be done. It should throw an error when the user try to sum a string value to an int as the default JS behavior will be a string typecast together with a concat (see Example 2 and Example 3).

# Code and Output

```
const _ = require('lodash')

console.log(_.sum([1, 1, 1])) // Example 1: Returns an int of value 3
console.log(_.sum([1, 1, '1'])) // Example 2: Returns a string of value 21
console.log(_.sum(['1', 1, 1])) // Example 3: Returns a string of value 111
```

# Fix suggestions:

- Check the input type and throw an error
- Typecast the input var to `Number` (_.sum will return a NaN if a string + int operation is done)
- Move _.sum from Math to Util section

**Comment by jdalton** [comment]
Hi @brunoluiz!

The current behavior is expected. It's a bit of a one-off but there's an append case I like covering in FP composition so `sum` and `add` methods are left generic enough to accommodate those.

**Comment by brunoluiz** [comment]
Okay, though I would at least add an example/comment on the docs notifying the developer about this behavior. As I said, as it is in the Math sections one would expect it would only do numeric operations.

**Comment by dushyantbangal** [comment]
@jdalton it also happens in case of `max`.

```
var arr=["1","2","3","100"];
console.log(_.max(arr));
```
It returns with 3 instead of 100. Is this expected as well or it should be a bug?
I noticed it works as @brunoluiz and I expected in v3 but not in v4.

**Comment by falsyvalues** [comment]
Guys, seriously are you expecting that the library will validate or catch all errors in your data :see_no_evil: :hear_no_evil:? If you `sum` array of strings using `Array#reduce` you wont get a number as a result.

**Comment by dushyantbangal** [comment]
@falsyvalues it was doing the casting in v3 but now it does not in v4, so I just came to ask if its a bug or expected behavior.
Nice username btw :)

**Comment by falsyvalues** [comment]
@dushyantbangal The previous version was doing things that should not be there and moving from version to version they are removed. You know as developer types are important especially in math :smile: 
Name came from JS :smile_cat:

**Comment by StreetStrider** [comment]
I don't see any reason why function defined in Number domain must do anything that have sence outside of that domain. Even if it did, it's a non-declared side behavior.
Just do `arr = arr.map(Number)` and you'll be fine.
