### ISSUE TITLE
Demonstrate ESNext import syntax

### ISSUE THREAD

**Issue by ORESoftware** [lodash/lodash#3480]
In a README like so:

https://www.npmjs.com/package/lodash.isequal

it would be nice to document `import` syntax

I have to guess about what the ESNext import syntax might be

```js
import {isEqual} from 'lodash.isequal';
```

that syntax would be "my preference" but not sure if that's the case

**Comment by ORESoftware** [comment]
Ok I did my due diligence, I see this:

```js
// Type definitions for lodash.isEqual 4.5
// Project: http://lodash.com/
// Definitions by: Brian Zengel <https://github.com/bczengel>, Ilya Mochalov <https://github.com/chrootsu>, Stepan Mikhaylyuk <https://github.com/stepancar>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.2

// Generated from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/scripts/generate-modules.ts

import { isEqual } from "lodash";
export = isEqual;

```

so the reason I wanted to use `lodash.isequal` instead of lodash as a whole, was because I hoped it would avoid importing the entire library, but that does not seem to be the case.

**Comment by jdalton** [comment]
Hi @ORESoftware!

There's nothing to demonstrate. Knowing how CJS works mapping it to ESM is straight forward. Your incorrect snippet of
```js
import {isEqual} from 'lodash.isequal';
```
would not be expected.

**Comment by ORESoftware** [comment]
@jdalton yes in this case, true, but sometimes modules have more than one export

**Comment by ORESoftware** [comment]
And I also, @jdalton one thing I would like to see, if it's not the case, is a way to import individual functions without importing the whole library - last time I checked this was not possible - but I can't remember 100%.

**Comment by jdalton** [comment]
> is a way to import individual functions without importing the whole library

You can do that by
```js
const pick = require('lodash/pick')
```
or
```js
import pick from 'lodash/pick'
```
---
If you want to do
```js
import { pick } from 'lodash'
```
then you'll need to use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash).

**Comment by ORESoftware** [comment]
Thanks, and I actually I meant installing too, not just importing (my bad) and it looks like if you install 'lodash.pick', then it doesn't install all of lodash.  So we are good, thanks.
