### ISSUE TITLE
Cannot find module flatmap

### ISSUE THREAD

**Issue by wellmotta** [lodash/lodash#3482]
Hi, I have a problem. I followed the steps:

    $ sudo npm i -g npm
    /usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
    /usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
    + npm@5.5.1
    updated 1 package in 11.849s

    $ npm i --save lodash.flatmap
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

    + lodash.flatmap@4.5.0
    added 114 packages and updated 1 package in 16.628s

When I try to start the project

    Error: Cannot find module 'lodash/flatmap'

Sorry my english is not good.

**Comment by TrySound** [comment]
@wellmotta `lodash/flatMap` and `lodash.flatmap` are different packages. Anyway single package version will be deprecated soon, so
```
npm i -S lodash
```
```
import flatMap from 'lodash/flatMap';
```

**Comment by wellmotta** [comment]
Thank you very much, solved my problem.
