### ISSUE TITLE
allow affecting all  elements in an array with set

### ISSUE THREAD

**Issue by Billy-** [lodash/lodash#3484]
I am trying to use set to modify properties of objects that are inside arrays, and I'd like to be able to set on all elements in an array, like so:

`set(obj, 'a.b[*].c', 'foo')`

Note that in my actual use-case I have properties very deeply nested in multiple arrays, i.e I will need this functionality multiple levels deep (`a.b[*].c.d[*].e` etc.); so doing without this functionality means I have some nasty recursive functions to implement! :stuck_out_tongue_closed_eyes:

**Comment by jdalton** [comment]
Hi @Billy- !

> so doing without this functionality means I have some nasty recursive functions to implement! 😝

I think that's probably the best way forward.
