### ISSUE TITLE
debounced.cancel() example in documentation is incorrect

### ISSUE THREAD

**Issue by cbj4074** [lodash/lodash#3485]
The `_debounce()` example provided in the manual ( https://lodash.com/docs/4.17.4#debounce ) includes the following example to illustrate canceling the trailing debounced invocation:

```javascript
// Cancel the trailing debounced invocation.
jQuery(window).on('popstate', debounced.cancel);
```

Isn't `cancel()` a method, not a property? Shouldn't it be as follows instead?

```javascript
// Cancel the trailing debounced invocation.
jQuery(window).on('popstate', debounced.cancel());
```

**Comment by jdalton** [comment]
The example is using `debounced.cancel` as a popstate event handler.

**Comment by cbj4074** [comment]
Oh, shame on me. Thanks for clarifying and apologies for the distraction.

**Comment by cbj4074** [comment]
On second though, might I suggest adding a less complicated example to the docs? One that demonstrates the regular, straightforward usage of `debounced.cancel()`?

Indeed it is beneficial to show the more complex use-case with `popstate`, but it seems like it couldn't hurt to include both.

Anyway, thanks again. :+1:

**Comment by poppabear8883** [comment]
I personally agree with @cbj4074 on this. +1 for adding both use-cases to the docs.

**Comment by jdalton** [comment]
jQuery and event handlers are fairly ubiquitous. As such I'm not going to touch the doc example.
