### ISSUE TITLE
The lodash method exported as lodash.isfunction does not work as expected with async function

### ISSUE THREAD

**Issue by captify-vkazantsev** [lodash/lodash#3486]
The lodash method _.isFunction exported as a Node.js module.
Does not work as expected with async function.

Code example here
https://runkit.com/embed/5c23g2rwhabp
```javascript
const lodashIsfunction = require("lodash.isfunction");
console.log(lodashIsfunction(() => null), 'Should be true'); // true
console.log(lodashIsfunction(async () => null), 'Async function should be true'); //false
```

The lodash works as expected
https://runkit.com/embed/z1dkat0izbgj
```javascript
var _ = require("lodash");
console.log(_.isFunction(() => null), 'Should be true'); // true
console.log(_.isFunction(async () => null), 'Async function should be true'); // true
```

**Comment by jdalton** [comment]
Hi @captify-vkazantsev!

This is a known issue with `lodash.isfunction`. I'm tore with if I should bother updating it as I've stopped shipping updates to those packages. I'd prefer if you just drop `lodash.isfunction` use and stick with `typeof`.
