### ISSUE TITLE
Unexpected behaviour _.assign with getter/setter

### ISSUE THREAD

**Issue by wawyed** [lodash/lodash#3488]
If I have a getter defined on my destination object, when assigning a source object the getter will not get overridden by the source. Is this by design?

Code to reproduce:

```
  var dest = { get a() { return 'initialValue';  } };
  var src = { a: '1', b: '2' };

  _.assign(dest, src);

  console.log(dest);
```
Expected result:

`{a: '1', b: '2' }`

Actual result:

`{a: 'initialValue', b: '2' }`

Fiddle demonstrating issue:

https://jsfiddle.net/q1gtg4z0/

**Comment by jdalton** [comment]
Hi @wawyed!

That won't work because your `dest` object doesn't have a setter.

**Comment by wawyed** [comment]
I understand that, but what if I wanted to override the getter with my value?

**Comment by jdalton** [comment]
@wawyed You'd want to be explicit and use `Object.defineProperty`

**Comment by wawyed** [comment]
Yeah, that's what I end up doing. I guess it's quite an edge case for lodash to handle it.
