### ISSUE TITLE
fp.method is fixed arity of one

### ISSUE THREAD

**Issue by lgy87** [lodash/lodash#3489]
hi everybody,

i attampt to change 

`const endsWithPeriod = str => str.endsWith(".")`

to

`const endsWithPerild = _.method("endsWith", ".")`

everything goes well.

but if i use **fp.method**, it goes wrong.

i know that fp.method is fixed arity of **one**, but `fp.method.convert({cap: false})` doesn't work too.

who can help me on this?
thank you in advance.

**Comment by jdalton** [comment]
Hi @lgy87!

I can't repro:
```js
_.method.convert({ fixed:false })('a',1, 2)({ a: function(b,c){ console.log("a", b, c) } })
// logs "a", 1, 2
```
