### ISSUE TITLE
Crashing in FireFox 13-24:  "set.forEach is not a function"

### ISSUE THREAD

**Issue by Kri0-Gen** [lodash/lodash#3490]
Here is the check for `Set` existance and call `setToArray` function: https://github.com/lodash/lodash/blob/41a8d2272e827fd43ddf11c29489ebeb6960e1fc/.internal/createSet.js#L13
Here in `setToArray` call `set.forEach` method: https://github.com/lodash/lodash/blob/5f2a03076dd1f391f419c1f910787b92dab4a74b/.internal/setToArray.js#L12

Unfortunately `Set` appeared from FireFox 13 while `Set.forEach` only from FireFox 25. Proof: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set (`Browser compatibility` section)

**Comment by jdalton** [comment]
Firefox no longer supports those version ranges.

**Comment by Kri0-Gen** [comment]
Guys, all you need is to merge that simple fix: https://github.com/lodash/lodash/pull/3491
Many people still use there FireFox versions.
That shall we do for them? Remove lodash from our project? Or say them that we will not support them because of simple stupid bug in lodash?

**Comment by Xotic750** [comment]
Load [es6shim](https://github.com/paulmillr/es6-shim) and it will be fixed.

**Comment by jdalton** [comment]
> Guys, all you need is to merge that simple fix

It's not just that 1 simple fix. Supporting older versions run into many issues. Issues I've been able drop as the sliding window of evergreen browsers, of which Firefox is one, continues to move.

> Many people still use these FireFox versions.

They [don't really](https://en.wikipedia.org/wiki/Template:Firefox_usage_share). 

> That shall we do for them?

If you're a contractor I'd say you should inform your customer that these browsers are dead and should no longer be supported. If they insist I suggest you raise your rate to cover the inconvenience.

> Remove lodash from our project?

That's an option, sure. You can also use an older version of Lodash. I think version 3 should work for those dead browser versions. Or as @Xotic750 mentioned you can use shims (which you're probably already doing to support older browsers).

> Or say them that we will not support them because of simple stupid bug in lodash?

Supporting older or dead versions of browsers is challenging. You'll likely run into more issues than just Lodash.

**Comment by Kri0-Gen** [comment]
That sounds reasonable.
Sorry for offending :)
But why do you support browsers that does not support `Set` at all?
I was a little confused that there is a check of `Set` existence so the code works for old browsers, but no check of full `Set` support.

**Comment by jdalton** [comment]
@Kri0-Gen 
> I was a little confused that there is a check of `Set` existence so the code works for old browsers, but no check of full `Set` support.

For IE 9+ support. In v5 though we'll be raising the support bar to IE11+.
