### ISSUE TITLE
isEmpty does not work correctly with Symbols

### ISSUE THREAD

**Issue by gkaran** [lodash/lodash#3492]
`isEmpty` does not work properly when an object uses only symbols as keys.

For example given any of the following objects we get back `true` instead of the expected `false`:

```
const test1 = { [Symbol('name')]: 'George' };
const test2 = { [Symbol('name')]: 'George', [Symbol('foo')]: 'bar' }
```

**Comment by jdalton** [comment]
Hi @gkaran!

Please read the doc entry for [_.isEmpty](https://lodash.com/docs/4.17.4#isEmpty).
