### ISSUE TITLE
Feature request: support arr[].prop path in _.unset

### ISSUE THREAD

**Issue by ghuser** [lodash/lodash#3493]
I am trying to find a simple way to remove the following properties from an object:
`a[0].b.c, a[1].b.c, a[2].b.c...`. But it seems that in order to achieve this I need to already know the array size.

I would find it quite useful to be able to use something like this: 

    _.unset(object, 'a[].b.c');

or this: 

    _.unset(object, 'a[*].b.c');

**Comment by jdalton** [comment]
Hi @ghuser!

I've avoided this so far but the request frequency is starting to pick up. I'm keeping an eye on the `[*]` usage request and may add it in the future.
