### ISSUE TITLE
MIT licence is not clearly stated in the licence file

### ISSUE THREAD

**Issue by deepu105** [lodash/lodash#3496]
The package.json states MIT licence but the licence file doesn't mention it hence its a bit confusing

**Comment by jdalton** [comment]
Ya, it's [not required](https://github.com/ternjs/acorn/blob/master/LICENSE) but would be [nice to have](https://github.com/angular/angular.js/blob/master/LICENSE). Would you be up for creating a PR to mimic that of [Angular](https://github.com/angular/angular.js/blob/master/LICENSE) with line 1 being *"The MIT License"*.

**Comment by deepu105** [comment]
I could i think
