### ISSUE TITLE
the 'this' problem in Vue

### ISSUE THREAD

**Issue by yxuecheng** [lodash/lodash#3497]
i have searched the issue and no result got!

i use it in Vue
```vue
method: {
    saveCondition: _.debounce((eid, sid, type, totalRadioLength) => {
	    let data = { eid, sid, type }
	    this.saveSubEvalData(data)
    }, 1000),
}
```
and invoke this method ,the babel trans it to es3 and  throw 'this' problem 
![image](https://user-images.githubusercontent.com/18499153/32871840-52eef7d6-cabe-11e7-9c2e-63cd12dbf8fb.png)

```js
saveCondition: _.debounce(function(eid, sid, type, totalRadioLength) {
	let data = { eid, sid, type }
	this.saveSubEvalData(data)
}, 1000)
```
when i don't use => method this problem solved, i was so confused

**Comment by jdalton** [comment]
Hi @yxuecheng!

That's not a Lodash issue. It looks like a Babel transpilation issue.

**Comment by yxuecheng** [comment]
ok

**Comment by TrySound** [comment]
@yxuecheng It's javascript. Context in toplevel arrow function (which does not have own context) is undefined in modules. Well, it's not an issue. And post full example next time. It's not obvious from screen how you that function.

**Comment by yxuecheng** [comment]
ok i will do it next time
