### ISSUE TITLE
Performance of `mapValues`

### ISSUE THREAD

**Issue by morgs32** [lodash/lodash#3501]
Could be improved by using a for loop?

See: https://jsperf.com/object-keys-vs-for-in-with-closure/3

**Comment by jdalton** [comment]
Hi @morgs32!

Maybe. We used a function helper to work around environment bugs with property iteration. Since Lodash v5 is raising the min support bar we could drop those. I'll kick it around, but no guarantees.

**Comment by morgs32** [comment]
@jdalton I'm curious. what's the function helper you mean and what type of environment bugs? Links or "google this" will suffice. Thanks for the trouble

**Comment by jdalton** [comment]
When I replied I was looking at our last stable release bits and not our master branch. In the last v4 release you'll see `mapValues` uses helper functions to work around iteration bugs *(bugs usually in some older IE release)*.

I see we're currently using `Object.keys` + `Array#forEach` and I know their slower. One of the things that wow'ed folks initially with Lodash was that I could make methods faster than built-ins. But with this release I'm wanting to pull things back a bit and simplify. So I'm using the syntax a bit more and will wait and see where folks complain about perf before making adjustments.
