### ISSUE TITLE
question: Which lodash function does something similar to JSON.parse?

### ISSUE THREAD

**Issue by bhutaninitin** [lodash/lodash#3502]
Is there a lodash function to validate whether argument is a valid JSON/Javascript string?

**Comment by jdalton** [comment]
Hi @bhutaninitin!

No there isn't. You usually handle this by wrapping `JSON.parse` in a try-catch.

**Comment by bhutaninitin** [comment]
Thanks. Then, is there a function that checks whether the argument is a valid javascript object? I found 

_.prototype.toJSON -> value 

Here is a usage:
var x=_({a: 1},{b: 2}).value();
typeof x
// =>object

I am trying to validate whether the input is a well-formed javascript object that lodash functions like _.defaultsDeep() accept as an argument. 

Thanks,
Nitin

**Comment by jdalton** [comment]
You can always try converting the object to a JSON string though I'm sure there's a validation package out there somewhere.
