### ISSUE TITLE
cloneDeep does not clone object that was initialized as array

### ISSUE THREAD

**Issue by ddfridley** [lodash/lodash#3503]
I ran into a problem using cloneDeep to clone an object. I am using 4.17.4 from npm.  The variable was initialized as an array, and then object properties were assigned to it.  I agree that the code is bad, but it seems to work in every other way and for my environment has been around for a while.  It behaves the same way on node and chrome. 

It's your call if you want to do anything about it, but I wanted document it if it helps anyone.

```
'use strict';

var cloneDeep = require('lodash/cloneDeep');

var objWasArray=[];
objWasArray.a='a';
objWasArray.b=['b'];
var clonedObj=cloneDeep(objWasArray);
console.info("objectWasArray:", objWasArray); // objectWasArray: [ a: 'a', b: [ 'b' ] ]
console.info("clonedObj",clonedObj); // clonedObj []
console.info(typeof objWasArray); // object
console.info(Array.isArray(objWasArray)); // true
console.info(objWasArray.length); // 0
console.info(JSON.stringify(objWasArray)); // []

```

**Comment by jdalton** [comment]
Hi @ddfridley!

Yep, this is by design. Lodash treats arrays special and doesn't iterate over custom properties of them.
