### ISSUE TITLE
.internal/root.js not CSP-safe

### ISSUE THREAD

**Issue by tephyr** [lodash/lodash#3504]
`lodash/.internal/root.js` includes `Function('return this')()` on line 7, which throws a [CSP](https://en.wikipedia.org/wiki/Content_Security_Policy) violation.

I was unable to use `lodash-cli` to create a custom build to exclude this feature.  Manually commenting out that last clause fixed the CSP violation.

Could a flag be added to the custom build process to drop that clause?

Related: #832.

**Comment by jdalton** [comment]
Hi @tephyr!

In your case you can just delete the fallback value, though I'm curious where your code is being used that the other two root values aren't populated first.

**Comment by tephyr** [comment]
Thanks for clearing that up.  I'll continue with a custom build & manual removal of the fallback value.

This code runs in a [CouchDB](http://couchdb.apache.org/) view, which apparently provides no root objects.  Here's the relevant section [from their docs](http://docs.couchdb.org/en/2.1.1/query-server/javascript.html):

    Each module has access to additional global variables:

    module (object): Contains information about the stored module
        id (string): The module id; a JSON path in ddoc context
        current (code): Compiled module code object
        parent (object): Parent frame
        exports (object): Export statements
    exports (object): Shortcut to the module.exports object
