### ISSUE TITLE
orderBy with number array

### ISSUE THREAD

**Issue by dartzki** [lodash/lodash#3506]
We are using the `orderBy` method to sort an array of Objects. Since the ordering may be defined by the Server using a number field, we want to use that field or else some other fields as defaults.
For this every object has a field 'orderBy' of type `(string|number)[]`. However, when we use that field as `_.orderBy(collection, (o) => o.orderBy)` the numbers in the array are sorted by their ASCII value instead of their number value.

a minimal example from the docs:
```js
var users = [
  { 'user': 'fred',   'age': 34 },
  { 'user': 'barney', 'age': 400 },
  { 'user': 'fred',   'age': 42 },
  { 'user': 'barney', 'age': 36 }
];
 
_.orderBy(users, function(o) {return [o.age];});
// => objects for [['fred', 34], ['barney', 36], ['barney', 400], ['fred', 42]]
```

**Comment by dartzki** [comment]
I just realised, that array comparison as we're using it, is not supported by lodash. Instead the array is coerced into a string which then leads to the observed behavior :/

Would this be a desirable feature to be added?

I know we could use `_.orderBy(users, ['age', 'user'])`, but we want to define the iteratee once and reuse it in multiple places. 
Also we want to use it on Objects that are a composition of the object the iteratee was defined for and other properties. In that case a constant `['age', 'user']` would not help. Instead we would need `['user.age', 'user.user']`...

**Comment by jdalton** [comment]
A custom orderBy method may be your best bet.
