### ISSUE TITLE
Lodash.fp.sortBy() is not working as expected for arrays

### ISSUE THREAD

**Issue by mattlubner** [lodash/lodash#3507]
I am attempting to sort an array of numbers using `lodash.fp.sortBy`, but it doesn't seem to work as expected.

I am doing the following:
```js
import fp from 'lodash/fp';

// sorting objects works as expected:
const objects = [{ key: 3 }, { key: 1 }, { key: 4 }];
console.log(fp.sortBy('key')(objects));
// => [{ key: 1 }, { key: 3 }, { key: 4 }]

// sorting numbers doesn't work as expected:
const numbers = [3, 1, 4];
console.log(fp.sortBy()(numbers));
// [expected] => [1, 3, 4]
// [actual] => (a string representation of the fp.sortBy function)
```

Live example: https://codepen.io/mattlubner/pen/NwyLVM?editors=0011

Do I need to pass an argument to `fp.sortBy` to get it to work with an array? If so, what should I be passing? Or is there a way to restrict the arity of `fp.sortBy` to "1" so it could be invoked as `fp.sortBy(array)`?

**Comment by mattlubner** [comment]
It just occurred to me to pass `fp.identity` as the argument to `fp.sort`, which then works. But shouldn't the identity function be the default value when the argument is omitted?

**Comment by jdalton** [comment]
Hi @mattlubner!

Optional params don't mesh with the FP style since things are auto-curried. You'll need to provide the iteratee.

**Comment by mattlubner** [comment]
It'd be helpful if the FP Guide mentioned that little tidbit! :)

**Comment by jdalton** [comment]
@mattlubner I can dig it! Would you be up for editing the wiki entry?

**Comment by mattlubner** [comment]
@jdalton Yeah, definitely!
