### ISSUE TITLE
reverse of _.merge()

### ISSUE THREAD

**Issue by IIslam** [lodash/lodash#3508]
I need to remove a certain property in a tree object that I created using merge the tree with the new branch 
ex:
var tree = {1:{
                       2:{
                           5:"a",
                           7:"b"
                          }
                      },
                   3:{20:"c"}
                 };
var branchToRemove ={1:{
                                         2:{
                                             5:"a"
                                            }
                                         }
                                     };
var  result = diff(tree, branch);
expected result = {1:{
                       2:{
                           7:"b"
                          }
                      },
                   3:{20:"c"}
                 };

**Comment by jdalton** [comment]
Hi @IIslam!

Object diffing is its own sub category of utils that we haven't gotten into. There should be several options on npm though. If you find one that works out well please share it here.
