### ISSUE TITLE
Flipped fp/concat yields different result when using partial application.

### ISSUE THREAD

**Issue by Nimelrian** [lodash/lodash#3510]
I'm currently in the process of porting a project from ramda to lodash/fp.

Since lodash doesn't offer a direct equivalent to ramda's `append`, I resorted to use concat.

Situation: I have a list and want to append another value at its end, but the result changes if the function is invoked using partial application:

```js
import _ from "lodash/fp";

const concatAfter = _.flip(_.concat);

const items = [0, 1, 2, 3, 4];
const toAppend = 5;

concatAfter(toAppend, items); // [0, 1, 2, 3, 4, 5] <-- Desired result
concatAfter(toAppend)(items); // [5, 0, 1, 2, 3, 4] <-- Note that the "appended" value is in the front
concatAfter(toAppend, _.__)(items); // [0, 1, 2, 3, 4, 5] <-- Works but isn't pretty to look at, only a workaround
```
As shown above, using the placeholder fixes the problem, but isn't really pretty to look at.

Am I missing something here?

**Comment by jdalton** [comment]
Hi @Nimelrian!

The `_.flip` method will flip arbitrary arguments that are provided, so bad for expected argument order or amount. Instead you can use `_.rearg`:

```js
const concatAdter = _.rearg([1,0], _.concat)
```
