### ISSUE TITLE
_.omit not working as expected with lodash/fp

### ISSUE THREAD

**Issue by popo63301** [lodash/lodash#3511]
Omit works good with lodash but not the fp version.

This is my code with the log I get.

```
var _ = require('lodash/fp');


var object = { 'a': 1, 'b': '2', 'c': 3, 'd': {'a':1,'b':2} };
 
var man = _.omit(object, ['a', 'c']);


console.log(man);


//With lodash
// // => { b: '2', d: { a: 1, b: 2 } }

//With lodash/fp
// => { '0': 'a', '1': 'c' }

```

How comes?

**Comment by jdalton** [comment]
Hi @popo63301!

The argument order of `omit` is flipped for the FP version. For more info see the [FP guide](https://github.com/lodash/lodash/wiki/FP-Guide).

**Comment by popo63301** [comment]
May I ask why haven't you let the order as it is with the normal lodash version?

**Comment by jdalton** [comment]
Making things data last is easier for FP style composition.
