### ISSUE TITLE
The default iterator for `_.find()` does not seem to be identity as per documentation

### ISSUE THREAD

**Issue by renehamburger** [lodash/lodash#3512]
I was surprised that `_.findIndex([{a:1}], {a:1});` returns `0` rather than `-1`, considering that the documentation states that its default iterator is `_.identity()` rather than `_.isEqual()`. This is the case for other find-methods, too.

It would be worth updating the documentation or am I missing something obvious here?

**Comment by jdalton** [comment]
Hi @renehamburger!

The second `{a:1}` is shorthand for [_.matches](https://lodash.com/docs#matches).

**Comment by renehamburger** [comment]
Of course! Thanks for the clarification.
