### ISSUE TITLE
'map' type mismatch

### ISSUE THREAD

**Issue by oreqizer** [lodash/lodash#3513]
## Expected behavior:

`map` should return the same functor-ish type. Mapping an object should return an object.

```
import _ from "lodash/fp";

_.map(v => v.toUpperCase(), { kek: 'bur' }); // returns { kek: 'BUR' }
```

## Actual behavior:

`map` returns an array when mapping objects.

```
import _ from "lodash/fp";

_.map(v => v.toUpperCase(), { kek: 'bur' }); // returns ['BUR'] :(
```

I know that `mapValues` exists, but it doesn't make sense having two maps when only one `map` is the correct `map`.

**Comment by jdalton** [comment]
Hi @oreqizer!

Our `_.map` method is a "Collections" type method. You're wanting [`_.mapKeys`](https://lodash.com/docs#mapKeys) or [`_.mapValues`](https://lodash.com/docs#mapValues).
