### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by younesfkihi** [lodash/lodash#3514]
The following modules are imported from `.internal` but don't exist:

* `createAssigner`
* `createFind`
* `createWrap`
* `customDefaultsAssignIn`
* `replaceHolders`

The above modules are imported in the following public modules:

* `ary` imports `createWrap`
* `assignWith` imports `createAssigner`
* `bindKey` imports `createWrap` and `replaceHolders`
* `curry` imports `createWrap`
* `curryRight` imports `createWrap`
* `findLast` imports `createFind`
* `merge` imports `createAssigner`
* `mergeWith` imports `createAssigner`
* `template` imports `customDefaultsAssignIn`

-----

The following public modules are imported but don't exist:

* `assignInWith`
* `findIndex`

The above modules are imported in the following public modules:

* `find` imports `findIndex`
* `template` imports `assignInWith`

**Comment by jdalton** [comment]
Hi @younesfkihi!

Yes things [are a bit messy at the moment](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#construction-notice-construction). Feel free to file PRs to cleanup any imports you like.

**Comment by waynebloss** [comment]
Where do the missing modules actually come from though? I was trying to take a look at `createAssigner`...

**Comment by waynebloss** [comment]
I found it over on the _es_ branch - https://github.com/lodash/lodash/blob/es/_createAssigner.js

I guess _master_ is built from _es_ or something like that. Thanks.
