### ISSUE TITLE
sumBy not working properly 

### ISSUE THREAD

**Issue by raphcadiz** [lodash/lodash#3515]
I have this code 
`total_sales: _.sumBy(sales, 'total_amount')` 
total amount is of type `DECIMAL` in the database instead of adding the values, it behaves like 2 string joined together
values:
```
[640.00, 71.00]
expected: 711:00
actual result: 640.0071.00
```
I'm on `"lodash": "4.13.1"`

**Comment by jdalton** [comment]
Hi @raphcadiz!

If it's concatenating values that means one is probably a string.
You'll want to pass a function to coerce the value to a number yourself.
