### ISSUE TITLE
Allow cond to accept not only functions

### ISSUE THREAD

**Issue by Alexsey** [lodash/lodash#3516]
Right now `_.cond` works only for the pairs of functions:
```js
const person = 'Roy'

const makeAGift = _.cond([
  [name => name == 'Helen', _.constant('There is a bouquet of flowers waiting for you!')],
  [name => name == 'Roy', _.constant('There is a new boots for you!')],
  [_.stubTrue, _.constant('Here, take some candies')]
])

makeAGift(person)
```

Proposal is to add an ability to pass non-function values as the first and the second argument of the tuple

Consider naming
```js
const condFn = _.cond([
  ...,
  [fn1, fn2],
  ...
]

condFn(arg)
```

For the `fn1` proposed behavior is
* In case if `fn1` and `arg` are primitives - use `() => fn1 === arg` instead of `fn1`
* (optional) In case if `fn1` is a regex and `arg` is a string - use `() => arg.match(fn1)` instead of `fn1`
* (optional) In case if `fn1` is a string and `arg` is a regex - use `() => fn1.match(arg)` instead of `fn1`
* In any other case - use as `_.identity(fn1)` (like for `_.filter` and others)

For the `fn2` proposed behavior is
* If `fn2` is not a function - use `() => fn2`
* If second argument is a function - use `fn1RunResult => fn2(fn1RunResult)`

In this case initial example could looks like
```js

const person = 'Roy'

const makeAGift = _.cond([
  ['Helen', 'There is a bucket of flowers waiting for you!'],
  ['Roy', 'There is a new boots for you!'],
  [_.stubTrue, 'Here, take some candies']
])

makeAGift(person)
```

**Comment by jdalton** [comment]
Hi @Alexsey!

I want to hold off complicating `cond` for now.
