### ISSUE TITLE
Is not there a deep alternative of assignIn?

### ISSUE THREAD

**Issue by neyaoz** [lodash/lodash#3517]
As we know, merge is just like `_.assign` except that it recursively merges own and inherited enumerable string keyed properties of source objects into the destination object.

But what about deep alternative of `_.assignIn`?

**Comment by jdalton** [comment]
Hi @neyaoz!

You might be able to do something with _.mergeWith.

**Comment by neyaoz** [comment]
Thanks, @jdalton. It is brilliant.

For the people who want to have the functionality of `_.assignIn` on `_.merge`:

```javascript
_.mergeWith(object, source, (objValue, srcValue) => assignIn(objValue, srcValue));
```
