### ISSUE TITLE
I can't get index in map (FP)

### ISSUE THREAD

**Issue by fortil** [lodash/lodash#3519]
Hi guys

I'm using the FP library, but I can't get index in map method, I don't see in documentation about that.

Thanks
Code:
```
var data = _.range(0, 10000)
var maping = (num, idx, array) => {
  return {
    num: num + 1,
    idx: idx + 1,
    sum: num + idx
  }
}
var LodashFPMap = _.map(maping)
console.log(LodashFPMap(data))
```
Result: 
```
[{num: 1, idx: NaN, sum: NaN}, ....]
```
Link reproduction problem https://jsfiddle.net/ejfw6f8t/

**Comment by jdalton** [comment]
Hi @fortil!

This is by design. If you'd like the index param you can use [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert) to set `cap` as `false`.

**Comment by fortil** [comment]
Ok, thanks!
