### ISSUE TITLE
set unexpected behaviour with keys looking like numbers

### ISSUE THREAD

**Issue by hleumas** [lodash/lodash#3520]
Consider following code:

```js
let a = {}
_.set(a, ['prefix', '47'])
_.keys(a.prefix).length
```

Expected value: 1
Actual value: 48

It is because lodash tries to be too clever by guessing that `'47'` can be coerced to number and so instead of object, it creates an array.

This is confusing and may cause bugs that are hard to debug, because they show up only when string key can be parsed as integer.

I would suggest to create an array only if the key is number, not in the cases where it can be parsed as a number.

This may create an issue with `_.keys` method which returns array of strings even for arrays.

This may be considered ok as `_.keys` is defined on Objects and not general collection, or it may be modified to return numbers for arrays. In a similar fashion that native `Array.keys()` works.

**Comment by hleumas** [comment]
Btw. I think this is easy to fix and I am happy to submit pull request, if you consider this desired behaviour.

**Comment by jdalton** [comment]
Hi @hleumas!

This is because Lodash treats arrays as dense so its `_.keys` method will do so too.
If you'd like to avoid that you can always just use `Object.keys`

**Comment by hleumas** [comment]
@jdalton I see your point. Still, I think the problematic part is when:

`_.set({}, ["prefix", "#4"], "whatever")` and _.set({}, ["prefix", "4"], "whatever") behave differently.

The latter one creates Array, while the first one creates Object.

The behaviour when the **value of a string key** determines whether you get an Array or an Object is confusing.

This is especially error prone behaviour especially if you use Object as a dict.

Take a look at how Rambda solves the very same problem: [link to Rambda repl](http://ramdajs.com/repl/?v=0.25.0#?var%20xLens%20%3D%20R.lensPath%28%5B%27x%27%2C%20%271%27%2C%20%272%27%2C%203%5D%29%3B%0A%0AR.set%28xLens%2C%204%2C%20%7B%7D%29%3B%20%20%2F%2F%3D%3E%20%7Bx%3A%204%2C%20y%3A%202%7D%0AR.set%28xLens%2C%208%2C%20%7B%7D%29%3B%20%20%2F%2F%3D%3E%20%7Bx%3A%208%2C%20y%3A%202%7D)

They treat all string keys as keys in Object and only keys that are number can get you Array created.

**Comment by jdalton** [comment]
That's by design. You can use [`_.setWith`](https://lodash.com/docs#setWith) to customize the object creation behavior.

**Comment by hleumas** [comment]
@jdalton I respect that. I am just suggesting, maybe that is not the best design decision? It seems to violate [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

If you want to use `Object` as a dictionary with string keys, this clearly is very unfortunate behaviour.

I understand that `Object` is not the best implementation of dictionary out there, but lets face it, what better alternatives are there? `Map`? Lodash don't even support `Map`.

I also know the shortcomings, e.g. the need to create all Objects with `Object.create(null)` to be safe, but still, it seems to be the best string hashmap out there.

Now, I know that you don't have to discuss this with me, you put long unpaid hours into maintaining this project and I have no right to tell you what to do. I respect that and I don't want to steal your time, so if you deem this discussion irrelevant, no need to reply. I'll understand.

Again, thanks for you time, work, and help:-)
