### ISSUE TITLE
clone does not copy array properties

### ISSUE THREAD

**Issue by hleumas** [lodash/lodash#3521]
Consider following code

```
let a = [1, 2, 3]
a.specialFlag = true
let b = _.clone(a)
b.specialFlag // => undefined
```

Adding non-numeric keys to array is rare yet valid use case. Correct behaviour for `clone` would be to copy them too.

Happy to contribute with pull request, if this gets accepted.

**Comment by jdalton** [comment]
Hi @hleumas!

This is by design. Lodash generally treats arrays as straight lists of items and doesn't go beyond that in terms of covering properties.
