### ISSUE TITLE
fp.reduce reuses accumulator when currying

### ISSUE THREAD

**Issue by timhwang21** [lodash/lodash#3522]
Hi, was wondering if this was intended behavior:

```javascript
import reduce from 'lodash/fp/reduce';

const curriedReduce = reduce((acc, el) => { acc[el] = true; return acc; }, {});

const result1 = curriedReduce([1,2,3]); // { '1': true, '2': true, '3': true }
const result2 = curriedReduce([4]); // { '1': true, '2': true, '3': true, '4': true }
```
If this is intentional, is there a suggested way to avoid this? This strikes me as pretty confusing. I found a workaround with `const curriedReduce = reduce((acc = {}, el) => { whatever }, undefined);` but that doesn't read very clearly.

I ended up just doing `const curriedReduce = (arr = []) => arr.reduce(reducer, {});`.

Thanks!

**Comment by jdalton** [comment]
Hi @timhwang21!

Yes this is intended behavior.
What you ended up doing with `curriedReduce` is a good way to handle it.

**Comment by timhwang21** [comment]
Thanks for the quick response!

I realize that my confusion came from mutating in my accumulator function instead of updating immutably since I didn't want `O(n^2)` for updating a list. My mistake!
