### ISSUE TITLE
Usecase isEmpty(Boolean)

### ISSUE THREAD

**Issue by konradjurk** [lodash/lodash#3523]
I was instinctively using _.isEmpty on a Boolean field, however it returns `false` if the boolean value is `false`. I feel like it should return `true` if _.isBoolean returns `true` for that field.

What do you think?

**Comment by jdalton** [comment]
HI @konradjurk!

The [_.isEmpty](https://lodash.com/docs#isEmpty) is primarily used to see if a collection is empty. It works best with values that are passed to *"Collections"* methods.
