### ISSUE TITLE
Two evaluate delimiters lodash template

### ISSUE THREAD

**Issue by danziamo** [lodash/lodash#3526]
Hello. 
Is it possible to use two evaluate delimiters?
I know it is silly to have it, but i have a request for it

I tried to use smart regular expression, but because javascript has weak regex engine, i failed to implement it. couldn't match and capture group at the same time

Thank you

**Comment by jdalton** [comment]
Hi @danziamo!

You can next `_.template` use using the expression delimiter to evaluate a template within a template.

**Comment by danziamo** [comment]
@jdalton 
i have two evaluate delimiters `{{ }}` and `<% %>`
i tried using this
```js
const source = `
<% console.log('magic'); %>
{{ console.log('also magic'); }}
`;
const compiled = _.template(source, { 'evaluate': /{{([\s\S]+?)}}/g });
const res = compiled();
```
and it worked only for second delimiter.
Can you please give me more hints about how to do it?

**Comment by jdalton** [comment]
```js
var compiled = _.template(`<%= _.template(other)(obj) %>`);
compiled({ other: otherTemplateString })
```

**Comment by danziamo** [comment]
I think i understand this, but it works for delimiter inside delimiter.
Unfortunately for me i cannot change template sources, i can change only js code that runs them. And in my case i needed two different types of evaluate delimiters that would work on same level.

I guess having several delimiters doing one job is really bad...
Anyway, thank you for your time and help!
