### ISSUE TITLE
New feature: anyToBoolean

### ISSUE THREAD

**Issue by igor-savin-ht** [lodash/lodash#3528]
Converts any value type to boolean.
Conversion rules:
 * Boolean: returns original value
 * String: returns TRUE if 'true' (case-insensitive) or '1', FALSE otherwise;
 * Number: returns TRUE if 1, FALSE if 0, throw an error otherwise;
 * Null or undefined: default if default value is provided, FALSE otherwise;
 * Object: throw an error.

Main use case for this function is for parsing boolean parameters in configuration files which are typically recognized as String and require manual conversion.

If this change is approved, I can provide PR with the new function and unit tests.
Better name for the function is most welcome.

**Comment by jdalton** [comment]
I think this is fine for a mixin. The standard to boolean is `Boolean(value)`.

**Comment by ephetic** [comment]
@igor-savin-ht Check out [yn](https://www.npmjs.com/package/yn).
