### ISSUE TITLE
_.set with string object keys with dots

### ISSUE THREAD

**Issue by happyshows** [lodash/lodash#3529]
Hi,

I'm trying to understand how to replace the following syntax with lodash:
```
dashboardDataSources = {};
for loop {
dashboardDataSources[dataSource.id] = dataSource;
}
```

the dataSource.id is in the form of  datagengine.42019.618651678240, which I don't have control.

If I do _.set(dashboardDataSources,dataSource.id,dataSource);  it would create Object like
{dataengine: Array[42020]}
instead of 
{dataengine.42019.618651678240: DataSource}

Is there anyway to escape the dot in the 2nd parameter so that it will be treated as naming not path?

**Comment by jdalton** [comment]
HI @happyshows!

Try [_.setWith](https://lodash.com/docs#setWith).

**Comment by happyshows** [comment]
Hi @jdalton 

Could you be more specific by providing an snippet?

I don't get how to configure the customizer to fit my use case.

**Comment by MatheusArleson** [comment]
@jdalton The doc example is not clear. 
A coverage of basic/advanced scenario will definitely help other devs not create issues like this one.

**Comment by MatheusArleson** [comment]
the same question was done on #2395 and no clear answer as provided.

**Comment by joniba** [comment]
For anyone looking for a way to set a string that has dots within an object:
```
var o = {}
_.set(o, 'a["b.c"]', 1)
// returns { a: { 'b.c': 1 } }
```

**Comment by jcollum-nike** [comment]
@joniba that should be in the docs -- good concise example
