### ISSUE TITLE
set, unset, get, update, toPath with period (.) in key

### ISSUE THREAD

**Issue by chrisblossom** [lodash/lodash#3530]
When there is a period in the key name, set, unset, get, update, toPath do not know how to handle it.

```js
const obj = {
    a: {
        'b.c': true
    }
};
```

[sindresorhus/dot-prop](https://github.com/sindresorhus/dot-prop) and [a8m/deep-keys](https://github.com/a8m/deep-keys) handle this by escaping periods with ``\\.``.

I currently workaround this by converting converting all paths to the format: ``a.b.c.d`` --> ``['a']['b']['c']['d']``, or with period keys: ``a.b\\.c`` --> ``['a']['b.c']``.

Is this the recommended way to handle this? Or should Lodash do this?

**Comment by jdalton** [comment]
Hi @chrisblossom!

To support that pass a path array.

**Comment by chrisblossom** [comment]
Thank you! I appreciate the quick feedback.
