### ISSUE TITLE
Feature request: andmap and ormap

### ISSUE THREAD

**Issue by samvv** [lodash/lodash#3532]
First of all thanks for the great library, it has saved me lots of time.

I was wondering if it is possible to add `andmap` and `ormap` to the library. Having a Scheme background, there are regularly cases where such a function would be useful, and I think it would be a good addition to the library. Here follows an example for each:

```js
import * as andmap from "lodash/andmap"

function isEven(num) {
  return num % 2 === 0;
}

// will return false
andmap([1, 2, 3, 4], isEven)

// will return true
andmap([2, 4, 8], isEven)
```

```js
import * as ormap from "lodash/ormap"
import * as isString from "lodash/isString"

// will return false
ormap([1, true, null, { bar: 1 }], isString)

// will return true
ormap([1, true, "foo", { bar: 1 }], isString)
```

For reference, [here](https://docs.racket-lang.org/reference/pairs.html#%28def._%28%28lib._racket%2Fprivate%2Fmap..rkt%29._andmap%29%29) is the documentation for `andmap` in Racket and [here](https://docs.racket-lang.org/reference/pairs.html#%28def._%28%28lib._racket%2Fprivate%2Fmap..rkt%29._ormap%29%29) for ormap.

This is just a thought, but it could also be overloaded to work on own enumerable properties of an object, with the second argument in the callback being the key. For this, too, I regularly find some cases.

What do you think?

**Comment by StreetStrider** [comment]
`Array.prototype.every`, `Array.prototype.some`.

**Comment by samvv** [comment]
Whoops, my bad! Never noticed that function, thanks!
