### ISSUE TITLE
Feature: Batched function

### ISSUE THREAD

**Issue by sanchitgn** [lodash/lodash#3536]
`batch(fn: Function, size: Number, interval: Number) => Function` 

Takes a function and returns a batched function. Invoking it multiple times will automatically batch and call it

```js
const batchedLog = _.batch(console.log, 2, 1000)

for (var i = 0; i < 5; i++) {
  batchedLog(i);
}

/* Output
00:00
1
2
00:01
3
4
00:02
5
*/
```

**Comment by jdalton** [comment]
Hi @sanchitgn!

I think this would be good as a mixin for now.
