### ISSUE TITLE
Lodash, React-Native, Android builds

### ISSUE THREAD

**Issue by anwarhamr** [lodash/lodash#3537]
Can someone please see if they can help me with this issue/question?

[https://stackoverflow.com/questions/47701939/react-native-and-lodash-chaining-seems-to-fail-in-builds-only-verified-in-andro](https://stackoverflow.com/questions/47701939/react-native-and-lodash-chaining-seems-to-fail-in-builds-only-verified-in-andro)

**Comment by jdalton** [comment]
Hi @anwarhamr!

For this kind of support try our [gitter chat](https://gitter.im/lodash/lodash).
