### ISSUE TITLE
Feature Suggestion: _.uniform

### ISSUE THREAD

**Issue by GCHQDeveloper500** [lodash/lodash#3538]
I've found the following function quite useful when summarising collections and validating user input;
```
_.uniform([1,2,3])                    // true
_.uniform([1,"2",3])                // false
_.uniform([1,null,3])                // false
_.uniform([1,2,3], 'number');  // true
_.uniform([1,2,3], 'string');     // false

const even = d => !(d%2)
_.uniform([1,3,5], even)         // false
_.uniform([2,4,6], even)         // true
```
Every time I need to use it I always assume it'll be in lodash and then find that it isn't and end up writing it as either an independent function or a mixin. This time I thought I'd raise an issue to suggest merging it into core. What do you think?

**Comment by elhesuu** [comment]
How about using `every`:

```
_.every([1, 2, 3], _.isNumber); // true
_.every([1, "2", 3], _.isNumber); // false
const even = d => !(d%2)
_.every([1, 3, 5], even) // false
_.every([2, 4, 6], even) // true
```

**Comment by GCHQDeveloper500** [comment]
Thanks @elhesuu - I agree that is a much more preferable solution than introducing a new function to the API.

@jdalton please feel free to close this issue.
