### ISSUE TITLE
FF and IE 11 Error orderBy

### ISSUE THREAD

**Issue by samimw** [lodash/lodash#3539]
Am using _.odereby(items, 'severity', 'asc') and works fine in Chrome.

But IE11 and FF is throwing error: 

FF : Error: _.orderBy is not a function
IE: TypeError: Object doesn't support property or method 'orderBy'

If I use sortBy works fine on both.

**Comment by GCHQDeveloper500** [comment]
Both of these errors you're seeing suggest that lodash is not included properly. You can achieve the error by just doing this in the console of each;
```
var _ = {}
_.foo()
```
It's weird that this is working for you in chrome and not the others - to me this suggests a race condition where chrome is loading lodash and initializing `_` fast enough that it works. Another possibility is that you're using a flaky CDN and it's just pure serendipity that it worked in Chrome and not the others.

Either way I don't think this is a problem with lodash - I just tested it here and it looks to be behaving as expected. 

Without knowing more about how you're including the library it's difficult to assist and to be honest that's more of a question for StackOverflow than for here. Hopefully this has pointed you in enough of the right direction to get you unstuck.

**Comment by jdalton** [comment]
Hi @samimw!

As @GCHQDeveloper500 mentioned it's probably something else. We test in IE11 and Firefox with and without AMD and a variety of AMD loaders.
