### ISSUE TITLE
Sorted array filter

### ISSUE THREAD

**Issue by alonisser** [lodash/lodash#3540]
Feature request/question: there is a sortedUniq for running uniq on (presumed) sorted arrays, thus allowing performance benefits. I couldn't find an equivalent function/filter option/ a way to break out of filter when the property filtered on changes (which in a sorted array by that property would mean there would be no more filtered results). Is there a built in/recommended way to to this? is this an interesting feature?

**Comment by jdalton** [comment]
Hi @alonisser!

See [_.sortedUniq](https://lodash.com/docs/4.17.4#sortedUniq).

**Comment by alonisser** [comment]
Hi @jdalton thanks for replying so quickly. I'm aware of _.sortedUniq, my question was about a _.sortedFilter functionality, I was just giving sortedUniq as an example.. can't see a way I can hack _.sortedUniq for doing that.. 

Also a good opportunity to thank you for lodash, probably the first dependency in any project of mine

**Comment by jdalton** [comment]
Thanks @alonisser! Ah, sorry I misread the initial question. Can you explain this bit some more:
>  I couldn't find an equivalent function/filter option/ a way to break out of filter when the property filtered on changes

**Comment by alonisser** [comment]
consider the following sorted array as example:
```js
let sortedAges = [{age:13}, {age:17}, {age:17}, {age:21}, {age:53}, {age:90}, {age:120}]
let filteredAges = _.filter(sortedAges, (item)=>{
   return item.age > 17 && item.age < 55;
})

```


There are two optimizations a _.sortedFilter method could do here (perhaps to use only on long arrays):

1. Start in the right place ({age:21}), instead of iterating from the beginning use a binary search or something similar to start where needed, on big arrays this can remove lots of unnecessary iterations.
2. Finish  in the right place (when reaching the first age not in the criteria) . since finishing iterating over the whole array won't yield more results for a sorted array when we filter on the sorted property).

This would work of course only when the array is sorted on the element used for filtering

**Comment by jdalton** [comment]
Ah ok.

That looks close to shortcut fusion but in this case I think you'd be better off using a for-loop and `break` out when needed.
