### ISSUE TITLE
Recursively unset empty path

### ISSUE THREAD

**Issue by meirotstein** [lodash/lodash#3541]
Hello,

I was wondering - is there's a way in lodash to unset an empty path recursively?
For instance - on the following object:
```javascript
{
  a: {
    b: {
      d: {
        e: 'value'
      }
    },
    c: 'value'
  }
}
```
when I unset `a.b.d.e` I would like to get the following object:
```javascript
{
  a: {
    c: 'value'
  }
}
```
If such not exists, I was thinking about adding additional function `_.unsetDeep` for this matter, or add additional boolean parameter to the `_.unset` function for recursive behaviour.

**Comment by jdalton** [comment]
Hi @meirotstein!

```js
const path = ["a", "b", "d", "e"]

do {
  _.unset(o, path)
} while (--path.length)
```

**Comment by meirotstein** [comment]
Hi @jdalton 

Thanks for your response!

However - this not return the desired result as it entirely remove the given path - in my example it will return an empty object.

What I'm interested is to unset only the empty path sections that are left after unsetting certain certain path - in my example I expect to get the following in result:

```javascript
{
  a: {
    c: 'value'
  }
}
```

**Comment by lunelson** [comment]
@meirotstein I just ran in to this; this was my solution—adapted to your example

```js
let path = ["a", "b", "d", "e"]
_.unset(obj, path);
while (--path.length && _.isEmpty(_.get(obj, path))) {
  _.unset(obj, path);
}
```
