### ISSUE TITLE
assignIn_1.default is not a function

### ISSUE THREAD

**Issue by bozhidarc** [lodash/lodash#3542]
My env is:
TypeScript 2.4.2
Angular 4.4.1
types/lodash-es: ^4.17.0
lodash-es: ^4.17.4

When I import the `assignIn` method everything is ok.
`import assignIn from "lodash-es/assignIn";`
But if it's called after the build I'm receiving the following error 
`JS ERROR TypeError: assignIn_1.default is not a function. (In 'assignIn_1.default({}, {...},{...})', 'assignIn_1.default' is undefined)`

I see that in the compiled js file it is required like that `assignIn_1 = require("lodash-es/assignIn")` and if I call it manually in the console `assignIn_1(...,...)` it works fine, but where I used it is called like that `assignIn_1.default()` which throws the error.

**Comment by jdalton** [comment]
Hi @bozhidarc!

Compilation is out of scope for Lodash. You might have better luck pinging the support channel for TS or whatever you're using to transpile.

**Comment by cjke** [comment]
@bozhidarc Not sure if you resolved your problem over on the other repo, but any future visitors, you need to do:

`import * as isNil from 'lodash/isNil'`
