### ISSUE TITLE
has with symbol and a function with at least one arg throws an error

### ISSUE THREAD

**Issue by oren-hollander** [lodash/lodash#3543]
```
import { has } from 'lodash/fp'
has(Symbol(), () => {}) // ok
has(Symbol(), x => {}) // throws 'Cannot convert a Symbol value to a string'
```

If the function has the symbol, `has` returns true in both cases

**Comment by jdalton** [comment]
Hi @oren-hollander!

Fixed by https://github.com/lodash/lodash/commit/bacaaaef8a18cbc5264b31f63f03434ac16e3204.

Dup of #3189.
