### ISSUE TITLE
flapMap is not working as expected

### ISSUE THREAD

**Issue by GiancarlosIO** [lodash/lodash#3545]
I have a strange bug. I was using the default exported module from lodash but now i'm trying to use the babel and webpack lodash plugin and the 'flapMap' function is not working as expected, i don't know why:

this is how i use the modules:
![captura de pantalla de 2017-12-13 17-55-21](https://user-images.githubusercontent.com/17274950/33966603-36ebb300-e02e-11e7-918b-f4253a56990f.png)

And this is the log in the console:
![captura de pantalla de 2017-12-13 17-51-56](https://user-images.githubusercontent.com/17274950/33966599-3450720c-e02e-11e7-9fc9-dcdd523ca1ae.png)

I should expect to get a array like:
`[1, 1, 2, 2, 3, 3]`

lodash: 4.17.4
babel-plugin-lodash: 3.3.2
lodash-webpack-plugin: 0.11.4

Thanks!

**Comment by jdalton** [comment]
Hi @GiancarlosIO!

It's likely a feature being turned off by lodash-webpack-plugin. Try enabling them one by one until your example works. Let me know which option it is and I'll see if it's intended or not.

**Comment by GiancarlosIO** [comment]
@jdalton thanks for the reply!
I just added a `flattening: true` option to the lodash webpack plugin and now it works as expected.

![captura de pantalla de 2017-12-14 10-02-25](https://user-images.githubusercontent.com/17274950/33998407-64b2baa4-e0b5-11e7-83bd-c6496384a84b.png)

thanks!

**Comment by jdalton** [comment]
That's odd. The `lodash-webpack-plugin` should be [auto-adding](https://github.com/lodash/lodash-webpack-plugin/blob/2ed13d386414004cc919ff8d31689c94fe51e420/src/mapping.js#L149) the "flattening" feature.
