### ISSUE TITLE
IsMatchWith, MergeWith, ... not calling customizer for initial Arrays

### ISSUE THREAD

**Issue by f-aubert** [lodash/lodash#3546]
With the latest lodash available via npm, 4.17.4, I found a strange behaviour possibly affecting the *With methods, such as isMatchWith or mergeWith. If arrays are passed at the top level, they don't match and the customizer is not called with the array itself...

Code:
`_.isMatchWith(myTgtArray, mySrcArray, myCustomizer); `

Expected:
- should match if both array contains the same elements in different order
- myCustomizer to be called with myTgtArray and mySrcArray as whole, and then possibly with the pairs of elements inside the arrays

Actual:
- does not match / false
- myCustomizer is called only with the pairs of elements inside the arrays

Workaround with Dummy Wrapper:
`_.isMatchWith({array: myTgtArray}, {array: mySrcArray}, myCustomizer); `

Something similar also happen with mergeWith...
`_.mergeWith(myTgtArray, mySrcArray, myCustomizer);`
     
I apologize if I did miss something obvious. Have a nice day

**Comment by jdalton** [comment]
Hi @f-aubert!

The match methods aren't really intended for arrays. They match parts of Object objects.

**Comment by f-aubert** [comment]
Hi @jdalton !
Thanks for stating it, it wasn't clear for me. However could they be extended to support array, or could another similar isMatchArrayWith, and mergeArrayWith, as the code should already be there to handle array properties of an object. Consider this maybe as a feature request/wish.
I have many use cases where I need to know if array A of partial objects matches array B of full objects (= A and B must have the same size, all objects of A must have a match in B, irrelevant of order, matching only on the properties the items in A have). I also have such use cases to merge these arrays (= all matched object by a given property such as 'id' should copy properties over to the corresponding B object, non matching objects should simply be appended to the resulting array). I gladly discuss usage, design and api and implementation in private with you, but I'm not yet comfortable with the code base of lodash to propose a push request.
Best regards and thanks for your time,
