### ISSUE TITLE
Multiple agrument iteratee breaks lazy evaluation

### ISSUE THREAD

**Issue by generalov** [lodash/lodash#3547]
_.VERSION
"4.17.4"

`_(_.range(10)).map((x) => { console.log(x); return x }).find(x => x == 3)`
Outputs 0, 1, 2, 3 as it expected, but:
`_(_.range(10)).map((x, i) => { console.log(x); return x }).find(x => x == 3)`
prints 10 numbers. 

The difference just in an additional argument to the map functions callback.
It seems to me that lazy evaluation is broken in the second case. I can't find any reason in documentation.

**Comment by jdalton** [comment]
Hi @generalov!

This is by design. See the [doc note](https://lodash.com/docs/4.17.4#lodash).
The reason is because it's observable by the iteratee and so shortcut fusion will not kick in.

**Comment by generalov** [comment]
@jdalton thanks you so much for explanation, I've understood the point. So, `toPairs` need to be used as workaround in case of arrays:
`_(_.range(10)).toPairs().map(([x, i]) => { console.log(x); return x }).find(x => x == 3)`
It works as expected.
