### ISSUE TITLE
Documentation of pick is not complete

### ISSUE THREAD

**Issue by danielo515** [lodash/lodash#3548]
Hello,

As usual, first thanks for this great library.

I spent a lot of time reading lodash documentation, and that's why it is important to me that it is clear and easily understandable. The documentation of pick is making me spent more time trying to understand the functionality than actually using it. Many times I found myself on a repl making tests to see what is capable of and what not.
The first confusing part is the parameter naming. The function signature includes `paths` as part of the input arguments, but the description says properties.
The example being too simplistic does not help neither. At the end of the pick section you don't know if you can use object paths or if you can only use plain properties.
I made some experiments with different and unexpected results. For example, taking the example as base and making a small modification the result is as expected:

```js
var object = { 'a': 1, 'b': '2', 'c': { d: 99, e: 88 }};
 
_.pick(object, ['a', 'c.d']);
// => { 'a': 1, 'c': { d: 3 } }
```

Trying to go further and adding an array, the result is also satisfactory:

```js
object2 = { 'a': 1, 'b': '2', 'c': [{ d: 99, e: 88 }]};
_.pick(object2, ['a', 'c.0.d']);
// => { 'a': 1, 'c': [{ d: 3 }] }
```

However none of those functionalities is documented, and it is hard to figure them out. Specially the array paths. One can think that the correct way of defining them may be `c[0].d` but it is not.
I think expanding the base example a bit further will help immensely.

Thanks in advance.

**Comment by danielo515** [comment]
Hello I just discovered that `lodash.pick` behaves differently than `_.pick`
All the above examples works with `_.pick` but does not produce any result with `lodash.pick`.
This is another important root of confusion.

**Comment by jdalton** [comment]
Hi @danielo515!

The docs state *"The property paths to pick."* in other methods property paths can be in string or array form and can be deep properties.

**Comment by danielo515** [comment]
Hello @jdalton,
How bad would be to add a more complex example? What about the other problem I have discovered? How should I report it?
