### ISSUE TITLE
_.get() support for a "named index" for defining the path

### ISSUE THREAD

**Issue by dnmd** [lodash/lodash#3550]
For the `_.get` method an index must be used when defining a path that contains an Array. For example `_.get(object, 'a[0].b.c');`. Using an index may lead to unexpected results when for example the number / order of values in an Array are not constant. Therefore I'd like to suggest a "named index" for defining such a path. Currently, incorporating the `_.findIndex` can be used as a workaround but is far from elegant.

````javascript
// suggested path
_.get(obj, ['contact', ['key' : 'workPhone'], 'value'])
// or
_.get(obj, 'contact['key':'workPhone'].value')
````

````javascript
var obj = {
  'contact':
    [{
      'key': 'mobilePhone',
      'value': '555-555-551'
    },
    {
      'key': 'workPhone',
      'value': '555-555-552'
    }]
};

// current implementation
// var index = _.findIndex(obj.contact, ['key', 'workPhone']);
var workPhone = _.get(obj, 
                      [
                       'contact', 
                       // use index or an _.findIndex(...)
                       _.findIndex(obj.contact, ['key', 'workPhone']), 
                       // ...
                       'value'
                      ]
                     );
````

**Comment by jdalton** [comment]
Hi @dnmd!

That's the nature of an array index.
I don't want to expand the path resolution to iterating an array and searching for values at this time.
