### ISSUE TITLE
Webpack 4 and sideEffects flag

### ISSUE THREAD

**Issue by Guymestef** [lodash/lodash#3551]
Hello,

Webpack released a v4-alpha version 2 weeks ago. Have you tried the sideEffects flag to test if the treeshaking succeeds to optimize the bundling of lodash?

**Comment by jdalton** [comment]
Hi @Guymestef!

Already merged #3533.

**Comment by damianobarbati** [comment]
Is it supposed to work of the box with webpack@4? Because with `lodash-es@4.17.5` I get the whole lodash-es into the bundle using the following snippet:

```
import { capitalize } from 'lodash-es';
document.write(capitalize('yo'));
```

**Comment by jdalton** [comment]
That would be a question for webpack folks

**Comment by damianobarbati** [comment]
👍🏻
