### ISSUE TITLE
Start Case and Lower Case feature removes special character from string.

### ISSUE THREAD

**Issue by anilrathod04** [lodash/lodash#3554]
Not sure if you guys already aware of this or not. But when I used 'StartCase' & 'LowerCase' feature removes special character from the string. 

_.startCase('juices & drinks') => 'Juices Drinks'
_.lowerCase('JUICES & Drinks') => 'juices drinks'

**Comment by falsyvalues** [comment]
Hi @anilrathod04,
This is how [_.words](https://lodash.com/docs/4.17.4#words) works, which is used under the hood, take a look on example.
