### ISSUE TITLE
Feature Request: could there be a option in pick which change the picked key name?

### ISSUE THREAD

**Issue by mytharcher** [lodash/lodash#3555]
For example:

~~~
var obj = {a: 1, b: 2};

var output = _.pick(obj, ['a', {key: 'b', as: 'c'}]);

console.log(output); // {a: 1, c: 2}
~~~

This idea was inspired from `AS` in SQL query.

**Comment by jdalton** [comment]
Thanks @mytharcher!

I can see the benefits to something like that.
We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by felds** [comment]
It looks useful but the syntax is a little bit clumsy, while giving the original function too many responsibilities. Maybe the _moving/renaming_ could be its own function?

Something like this, maybe? https://repl.it/repls/EnlightenedValuableArchaeopteryx

**Comment by mytharcher** [comment]
Thanks @felds . It is also a good idea if `as` could not be implemented in `pick`. I can accept this.

**Comment by Alexsey** [comment]
Another shorter syntax for this could be
```js
const obj = {a: 1, b: 2}
const output = _.pick(obj, 'a', ['b', 'c'])
// or
const output = _.pick(obj, ['a', ['b', 'c']])
console.log(output) // {a: 1, c: 2}
```
