### ISSUE TITLE
Can lodash throttle wait parameter be decimal level?

### ISSUE THREAD

**Issue by JHanLu** [lodash/lodash#3557]
Like 0.5ms or 0.01ms? What is the minimum level ？

**Comment by jdalton** [comment]
Hi @JHanLu!

The minimum level is whatever `setTimeout` and friends support. So I'm assuming whole millisecond values.

**Comment by JHanLu** [comment]
@jdalton I just googled it, it's 4ms.

**Comment by jdalton** [comment]
Browsers may throttle or pause timeouts on inactive tabs too.
