### ISSUE TITLE
cloneDeep(function),seem like have a bug

### ISSUE THREAD

**Issue by jintangWang** [lodash/lodash#3558]
when I use `_.cloneDeep(function() {})` with the latest lodash, it make a mistake like this.
![image](https://user-images.githubusercontent.com/12557847/34292258-2d2182b4-e73b-11e7-98ae-3314327187f9.png)
![image](https://user-images.githubusercontent.com/12557847/34292303-5b67368c-e73b-11e7-98ca-113311e2d575.png)

**Comment by Justineo** [comment]
As mentioned in https://github.com/lodash/lodash/issues/3097#issuecomment-292548335, I think giving `{}` is the expected result. Functions are considered as uncloneable so it returns an empty object. But in fact we got this:

```js
import { cloneDeep } from 'lodash'

import { cloneDeep } from 'lodash'

console.log(typeof cloneDeep({ fn () {} }).fn) // 'function'
```

It looks like there's some inconsistency here. @jdalton

**Comment by jdalton** [comment]
See the [docs](https://lodash.com/docs/4.17.4#clone).

**Comment by Justineo** [comment]
The structured clone algorithm doesn't support functions. The docs for [`clone`](https://lodash.com/docs/4.17.4#clone) says:

> **An empty object** is returned for uncloneable values such as error objects, **functions**, DOM nodes, and WeakMaps.

If [`cloneDeep`](https://lodash.com/docs/4.17.4#cloneDeep) is a recursive version for `clone`, the expected result of `cloneDeep({ fn () {} })` should be `{ fn: {} }` as I understand, which is not the current behavior.

**Comment by jdalton** [comment]
Turns out folks don't dig that. The main sticking point is the return value be a clone not necessarily the properties of the value.
