### ISSUE TITLE
Jest's runTimersToTime does not execute a function that is debounced using lodash's debounce.

### ISSUE THREAD

**Issue by cameron-martin** [lodash/lodash#3559]
For more information, [see the issue on the jest repository](https://github.com/facebook/jest/issues/5160).

[This issue](https://github.com/lodash/lodash/issues/304) seems to be related.

**Comment by jdalton** [comment]
> [This issue](https://github.com/lodash/lodash/issues/304) seems to be related.

It's not. That was from 2013 and is no longer the case with v4.

**Comment by cameron-martin** [comment]
This issue is still valid even though the related issue is not related. I'm not sure why this was closed.

**Comment by jdalton** [comment]
I don't believe it's a Lodash issue. Looks like a jest issue to me.
