### ISSUE TITLE
Feature Request: _.throttle using requestAnimationFrame via options flag

### ISSUE THREAD

**Issue by mattlubner** [lodash/lodash#3560]
Hi there!

Similar to #1165 (hat tip to @MeoMix), but instead of a whole new specialized function, what if we just add support to `_.throttle` directly, behind an options flag (eg. `options.requestAnimationFrame=true` perhaps?).

`_.throttle` could then degrade gracefully to its default implementation (with a default 1000/60 wait interval) whenever `window.requestAnimationFrame` is unavailable (such as in NodeJS).

Anyone else in favor of this? I, for one, would love to have this sort of utility within Lodash itself! 😀

**Comment by jacob-beltran** [comment]
I have submitted a pull request to add this feature (#3562). Comments and feedback much appreciated.

**Comment by jdalton** [comment]
Moved to #3562.
