### ISSUE TITLE
_.words handles numbers differently when converting cases

### ISSUE THREAD

**Issue by jonathanseneris** [lodash/lodash#3561]
Several previous issues state that numbers are considered words, but regular language strings do this differently from camelCase or snakeCase.

When:

1. `_.words('my 1st birthday')`
2. `_.words('my_1st_birthday')`
3. `_.words('my1stBirthday')`

Expected:
All would return either 
`["my", "1", "st", "birthday"] `
or 
`["my", "1st", "birthday"]`
 
Actual:

1. `["my", "1st", "birthday"]`
2. `["my", "1", "st", "birthday"]`
3. `["my", "1", "st", "birthday"]`

Is it expected that 'nth' is viewed differently in a regular string vs camel or snake case?

**Comment by jdalton** [comment]
They should all be treated like `1.`.

**Comment by jdalton** [comment]
Thanks @jonathanseneris!
