### ISSUE TITLE
Where is createWrap file?

### ISSUE THREAD

**Issue by pertrai1** [lodash/lodash#3563]
I was looking at the `curry` file and saw the import of `createWrap` but I am not able to find the file

https://github.com/lodash/lodash/blob/master/curry.js#L1

**Comment by jdalton** [comment]
Hi @pertrai1!

Lodash is [under construction](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#construction-notice-construction) for v5 so some files may be missing.
