### ISSUE TITLE
Standalone pick does not understand array notation

### ISSUE THREAD

**Issue by danielo515** [lodash/lodash#3565]
Hello,

I've noticed an important difference between the version of pick that is included in the monolithic build of lodash vs the standalone package `lodash.pick`. I Think it better explains with examples 

```js
// Load the full build of lodash
var _ = require('lodash');
const pick = require('lodash.pick');

const object2 = { 'a': 1, 'b': '2', 'c': [{ d: 99, e: 88 }]};

console.log('Monolithic', _.pick(object2, ['a', 'c.0.d']));
// => { 'a': 1, 'c': [{ d: 99 }] }
console.log('Standalone: ',pick(object2, ['a', 'c.0.d']));
// => { 'a': 1 }

const object = { 'a': 1, 'b': '2', 'c': { d: 99, e: 88 }};

console.log('Monolithic', _.pick(object, ['a', 'c.d']));
// => { 'a': 1, 'c': { d: 99 } }
console.log('Standalone', _.pick(object, ['a', 'c.d']));
// => { 'a': 1, 'c': { d: 99 } }
```

As you can see, the second example works, but the first one, where I'm using array notation only works on the monolithic build.
Is this intentional ? Are they different versions ?

Thanks and regads

**Comment by jdalton** [comment]
Hi @danielo515!

Yes, they are different versions as indicated by their version numbers. Supper for property paths was added in a later version and won't likely be ported to the individual method package. Individual method packages aren't being updated. It's recommended that you cherry-pick from primary `lodash` package, like `lodash/pick`.

**Comment by danielo515** [comment]
Hello @jdalton 
I was fearing an answer like that. It was not hard to suppose that `lodash.pick` was an older version. Which is hard to guess is the reason. There is no deprecation notice on any package, and the documentation of lodash does not say anything about it neither. I was very used to make use of individual packages, and this is a surprise for me.
Could you tell me why are you not maintaining the separate packages anymore ?

Thanks in advance

**Comment by jdalton** [comment]
Focus is moving to a single smaller modular core package. You'll get nothing but inflated module sizes with no hope of reduction with the individual module packages. It's a completely false sense of modularity and size reduction. The 🍰 is a lie.

**Comment by danielo515** [comment]
Thanks as usual @jdalton 

> The 🍰 is a lie.

😄 

I can understand that, in fact I though about that several times: using just one function may feel smaller, but as long as any (just one is enough) of your deps uses the regular build of lodash you will end with a duplicated function having it's own entire package.
I suppose you are talking in the context of browser apps, I'm using lodash heavily on my backend code too, where at the end size is not a concern.

In any case, I think a deprecation warning will be a good thing to have, instead having to test for differences and open an issue to realize this fact.

Thanks and regards
