### ISSUE TITLE
i want to delete inner object from an tree using javascript.........

### ISSUE THREAD

**Issue by kalyanimanu** [lodash/lodash#3566]
var res={

a:10,
b:20,
audit:
{
created:xxx,
modified:yyy,
deleted:zzz
}
}

in this object i want to delete inner object audit,
can anyone please help me how to delete inner object

}

**Comment by jdalton** [comment]
`delete res.audit`.

**Comment by kalyanimanu** [comment]
ya i got it.
earlier i thought delete for property deletion..

Thanks
