### ISSUE TITLE
Cannot curry such a function?

### ISSUE THREAD

**Issue by yjhmelody** [lodash/lodash#3568]
lodash 4.17.4

```js
// _.chunk 's definition
function chunk(array, size, guard) {...}
```
but doc says: 
`_.chunk(array, [size=1])`.

So when I want to curry such a function which has not given a `default parameters`,
I do not know how to curry it correctly.

```js
const chunk = _.curry(_.chunk)
// I have to call chunk([1, 2, 3])(2)()
// But I think it should be called twice.
```

**Comment by jdalton** [comment]
See the documentation for [curry](https://lodash.com/docs/#curry). You can provide a second `arity` argument to `curry`.
