### ISSUE TITLE
sortedIndex has unexpected behaviour

### ISSUE THREAD

**Issue by kriadmin** [lodash/lodash#3569]
`_.sortedIndex([5,3,2,1], 4);` should return `1` but it returns `4` .
I would recommend using the following code from [30-seconds-of-code](https://github.com/Chalarangelo/30-seconds-of-code)
``` js
const sortedIndex = (arr, n) => {
  const isDescending = arr[0] > arr[arr.length - 1];
  const index = arr.findIndex(el => isDescending ? n >= el : n <= el);
  return index === -1 ? arr.length : index;
};```

**Comment by jdalton** [comment]
The [sortedIndex](https://lodash.com/docs/#sortedIndex) uses a binary search to determine the lowest index at which `value` should be inserted.

**Comment by kriadmin** [comment]
@jdalton But I think it should take descending arrays in account too.

**Comment by Adam13531** [comment]
@kriadmin you probably don't need this anymore, but for anyone who finds this in the future, [here's an article](http://www.boduch.ca/2014/07/lodash-descending-sorted-index.html) that talks about how to solve it.

The summary is that if you're working with numbers, you can simply call into `sortedIndexBy` and negate all of the values when comparing:

```js
_.sortedIndexBy([5,3,2,1], 4, (num) => -num); // returns 1
```
