### ISSUE TITLE
_.round() does not take into account numbers preceding precision

### ISSUE THREAD

**Issue by mrts** [lodash/lodash#3570]
I would expect that

    _.round(89.6849593495935, 2) === 89.69

but actually

    _.round(89.6849593495935, 2) === 89.68

This is not a contrived issue, the problem arose while calculating taxes with Lodash and feeding the results to government forms that reported errors in calculations.

I'm using v4.17.4 via [LodashGS](https://github.com/oshliaer/lodashgs).

Here's my workaround that feels like an ugly hack:

    _.round(_.round(value, 3), 2);

**Comment by jdalton** [comment]
Hi @mrts!

The interesting bit is:
```js
Math.round("89.6849593495935e2")
// => 8968
```

I can see maybe doing:
```js
value = Math.round("89.6849593495935e3") // precision+1
// 89685
value = Math.round(value + "e-1")
// 8969 which will result in 89.69
```

I'm open to a PR if you feel up to tweaking [the helper](https://github.com/lodash/lodash/blob/master/.internal/createRound.js).

**Comment by mrts** [comment]
Thanks for the suggestion! Yes, `Math.round()` is the culprit.

Adding one to the precision does not fix the root problem though, the difference may bubble up from deeper in the fractional part:

```
_.round(89.684449, 2)
89.68
_.round(89.684449, 3)
89.684
_.round(89.684449, 4)
89.6844
_.round(89.684449, 5)
89.68445
_.round(_.round(89.684449, 5), 4)
89.6845
_.round(_.round(_.round(89.684449, 5), 4), 3)
89.685
_.round(_.round(_.round(_.round(89.684449, 5), 4), 3), 2)
89.69
```

**Comment by jdalton** [comment]
I can see maybe tracking the value after the `precision`, so `precision+1`, but beyond that defeats specifying the precision in the first place. You can always `Math.round(n).toFixed(2)`.

**Comment by mrts** [comment]
Right, let's be pragmatic. I'll see if I can come of with a pull request and some tests.

**Comment by mrts** [comment]
After investigating this a bit more, I think that it is actually better to retract the issue.

[Java](https://docs.oracle.com/javase/8/docs/api/java/math/RoundingMode.html#HALF_UP) works [like this](http://www.javarepl.com/):
```java
java> import java.math.BigDecimal;
java> new BigDecimal("89.6849").setScale(2, BigDecimal.ROUND_HALF_UP).toString();
java.lang.String res0 = "89.68"
```

Python works like this:
```python
>>> import decimal
>>> d = decimal.Decimal('89.6849')
>>> d.quantize('.01', rounding=decimal.ROUND_HALF_UP)
Decimal('89.68')
```

So, both work like `_.round()` currently does.

Thus, even though this looks counterintuitive from pure math perspective, based on Java and Python precedence I'd say my initial problem report is misguided. (The tax values might be off because I round too late or too eagerly in my application code, need to investigate more.)

Please feel free to reopen if you see rounding could be still improved.

**Comment by robshep** [comment]
Either some weird coincidence, or there's a floating point gremlin lurking in these numbers but .....

I just had a long standing unit test fail which performs monte-carlo (10000 iterations) on RNG derived doubles comparing Java against lodash in harness.

It failed on the random number: 89.68499965828052

However, I was also using ROUND_HALF_UP which (on my specific fraction) does not match lodash. 

Not sure what's right or wrong here.  

If I trigger Jenkins, it'll pass again then I can just forget about it right? :)

Splitting the precision, I can find that

    _.round(89.684999, 2) == 89.68

but

    _.round(89.6849996, 2) == 89.68

**Comment by robshep** [comment]
And it's almost exactly a year to the day that you were discussing this last.

**Comment by robshep** [comment]
Urgh, ignore this. 

My line:

    Double lodashRounded = (Double) engine.eval(String.format("_.round(%f, 2)", toTest));

...stitched in the number under test using sprintf formatting and....

    String.format("%f", 89.68499965828052) == 89.685000

A fault on my part for not specifying the precision in printf.   

Ignore.
