### ISSUE TITLE
import  "lodash" show a  error  

### ISSUE THREAD

**Issue by X-sirs** [lodash/lodash#3571]
when i use "import _ from lodash" in my project,it show me the error that's content is "cannot read property 'prototype' of undefined"   (lodash@4.17.4).   please help me ,thanks

**Comment by jdalton** [comment]
Hi @X-sirs!

This is likely related to your transpiler. What browser, browser version, and transpiler (if any) are you using?

**Comment by X-sirs** [comment]
thank you , i think i has found the question ,i has fixed the bebal file.

**Comment by jdalton** [comment]
Okay!
