### ISSUE TITLE
Feature Requests: Pick one or more random entries out of an array, string, or object

### ISSUE THREAD

**Issue by taichunmin** [lodash/lodash#3572]
Pick one or more random entries out of an array, string, or object.

* Use case: string

```js
// in Bulls and Cows game
function genSecret() {
  return _.shuffle("0123456789".split("")).slice(0, 4).join("")
}
// with new method
function genSecret() {
  return _.randomItem("0123456789", 4)
}
```

* Use case 2: array

```js
// in template
_.template("${['Hello', 'Hi', 'Bonjour'][_.random(0, 2)]}")()
// with new method
_.template("${_.randomItem(['Hello', 'Hi', 'Bonjour'])[0]}")()
```

* Use case 3: object

```js
let obj = {a: 1, b: 2, c: 3, d: 4}
_.randomItem(obj, 2)
// return {a:1, d:4}
```

**Comment by jdalton** [comment]
Hi @taichunmin!

We have [_.sample](https://lodash.com/docs/#sample) and [_.sampleSize](https://lodash.com/docs/#sampleSize). Though I will say "Collections" methods are being split out into their value specific, object, array, string, etc., forms.

**Comment by taichunmin** [comment]
Thanks
