### ISSUE TITLE
concat is not working as expected

### ISSUE THREAD

**Issue by pavinthan** [lodash/lodash#3575]
```
let answers = map(this.question.answerGroups, 'answers');
console.log(answers, concat(answers));
```

<img width="836" alt="screen shot 2018-01-04 at 10 47 41 am" src="https://user-images.githubusercontent.com/13897936/34551134-bf1e471e-f13c-11e7-924d-666ec7e28f92.png">

**Comment by pavinthan** [comment]
@jdalton what is wrong with this?

**Comment by StreetStrider** [comment]
@pavinthan what behavior do you expect?

**Comment by pavinthan** [comment]
@StreetStrider I expected the arrays concat inside the array like
```
[ 0: [0: [], 1:[] ]] => [[], []]
```

**Comment by StreetStrider** [comment]
@pavinthan why is that? That's not how std's or lodash' `concat` is working. You need use either `concat.apply` or spread.

**Comment by pavinthan** [comment]
@StreetStrider I've achieved it with `reduce`, Thanks guys

**Comment by StreetStrider** [comment]
@pavinthan `concat(...answers)`. You could also use `flatten`.
