### ISSUE TITLE
New feature: contains

### ISSUE THREAD

**Issue by LeonardoHabitzreuter** [lodash/lodash#3578]
Return true if an array contains the element.

var array = [2, 3, 4]

_.contains(array, 2)
// => true

_.contains(array, 1)
// => false

If this change is approved, I can provide PR with the new function and unit tests.

**Comment by HiDeoo** [comment]
Isn't it the same as [`_.includes`](https://lodash.com/docs/4.17.4#includes)?

**Comment by jdalton** [comment]
Hi @LeonardoHabitzreuter!

As @HiDeoo points out we have [`_.includes`](https://lodash.com/docs/#includes) though modern browsers have [Array#includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes).
