### ISSUE TITLE
lowerCase problem

### ISSUE THREAD

**Issue by raduanastases** [lodash/lodash#3579]
If I use `_.lowerCase('ABCd')` this becomes `ab cd`.
This is because of the use of `words` here https://github.com/lodash/lodash/blob/master/lowerCase.js#L25 

Is this the desired behavior?

**Comment by jdalton** [comment]
Hi @raduanastases!

You're wanting the [_.toLower](https://lodash.com/docs#toLower) method.

**Comment by raduanastases** [comment]
@jdalton I knew about that method, but it seemed weird for that to act that way.

**Comment by jdalton** [comment]
The `lowerCase` method is a casing method like `snakeCase`, `camelCase` and others which work on compound words.

**Comment by raduanastases** [comment]
Ow, I see. Thanks for the clarification. Keep up the good work!
