### ISSUE TITLE
Is there `if Expression` in lodash?

### ISSUE THREAD

**Issue by thegatheringstorm** [lodash/lodash#3581]
In Scala,we can write `if` like this:
```scala
val result: String = if(marks >= 85)  "A" else "B"
println("You've got " + result + ".")
```
The if expression has return value
In JavaScript,we can do this:
```js
const result = (marks >= 85) ? "A" : "B"
```
But we can't do this:
```js
const result = (marks >= 85) ? ( const a = "A" ;a):(const b = "B";b)
```
Because we can't use assignment statement in ?:
But it is clear(not in this example)

Thanks!

**Comment by thegatheringstorm** [comment]
Should I use `_.cond` ?

**Comment by felds** [comment]
It doesn't look like it's lodash related.

Your example is invalid JS. And even if it wasn't, `const` is block-scoped (meaning it would only be visible inside the block in which it was defined).

**Comment by thegatheringstorm** [comment]
@felds Thanks!
Everything has return value is the basic principle of Functional Programming including `if/else`. So I make this issue.
Yes,my third example is invalid.
:smile:

**Comment by StreetStrider** [comment]
@thegatheringstorm ye, `_.cond` is a way to go. May be an overkill in some cases, because of `cond`'s more generic nature. There was also a multiple discussions related to introduction of predicate-ish functions, like `conj` and `disj`. For instance #1072

**Comment by thegatheringstorm** [comment]
@StreetStrider Thanks!
