### ISSUE TITLE
`cloneWith`: not the customizer function with _key|index_ parameters

### ISSUE THREAD

**Issue by eran-nussbaum** [lodash/lodash#3582]
The docs say: 
> The `customizer` is invoked with up to four arguments; _(value [, index|key, object, stack])_.

But in actuality I see only `value`.
When I declare `key` (or `index`) as second parameter – it is always `undefined`.

**Comment by jdalton** [comment]
That's a doc bug. You're wanting [`_.cloneDeepWith`](lodash.com/docs#cloneDeepWith).
