### ISSUE TITLE
Is Rhino still supported?

### ISSUE THREAD

**Issue by lucasvanhalst** [lodash/lodash#3585]
I've been trying to get templates working, but when trying to compile a template with Rhino it gives me the following:

```javascript
_.templateSettings.interpolate = /{{([\s\S]+?)}}/g;
_.template('test {{ abc }}')({abc: 'test'});
// ReferenceError: Invalid assignment left-hand side
```

Works as expected in the browser

Used a newly created build of lodash using `lodash include=template` and rhino 1.7.7

**Comment by jdalton** [comment]
Hi @lucasvanhalst!

We don't actively test in Rhino anymore. If our v4 isn't working you can always try v3 or v2.

**Comment by lucasvanhalst** [comment]
Allright, thanks
