### ISSUE TITLE
lodash/fp/setWith customizer 

### ISSUE THREAD

**Issue by BarryThePenguin** [lodash/lodash#3587]
I'm struggling to understand how the customizer works when using `setWith` from `lodash/fp`

Essentially I'm trying to use it to calculate a new value on an object...

```js
var assert = require('assert');

var _ = require("lodash/fp");

var createGreg = _.flow(
  _.set('firstname', 'greg'),
  _.set('lastname', 'bob'),
  _.setWith(calculateFullname, 'fullname', ''),
);

function calculateFullname(val, key, person) {
  return person.firstname + ' ' + person.lastname;
}

var greg = createGreg({});

assert.equal(greg.fullname, 'greg bob');

console.log(greg);
```

The assertion in the example fails, as I expect `fullname` to be `'greg bob'`.

Changing the `setWith` call to `_.setWith(calculateFullname, 'fullname.anything', ''),` passes assertion.

Is this a bug? Or am I using it incorrectly? Would also be open to suggestions to achieve the same result in a different way. Thanks!

**Comment by jdalton** [comment]
Hi @BarryThePenguin!

The [argument order](https://github.com/lodash/lodash/wiki/FP-Guide#exceptions-to-the-rules) of `fp/setWith` is `(d, b, c, a)`,
so that means for [setWith](lodash.com/docs#setWith) it's `(customizer, path, value, object)`.

**Comment by BarryThePenguin** [comment]
Isn't that the order that I have?

**Comment by jdalton** [comment]
It looks like the order of

> Changing the setWith call to _.setWith(calculateFullname, 'fullname.anything', ''), passes assertion.

**Comment by BarryThePenguin** [comment]
Thanks for the quick reply :)

When the `path` is `fullname.anything.else` the customizer function is called and the calculated value is set.

But if the path is just `fullname` the customizer function isn't called.

I'm not sure why the behaviour is changes for different path values.

**Comment by BarryThePenguin** [comment]
The same thing happens when not using `lodash/fp`

```js
var assert = require('assert');

var _ = require("lodash");

var greg = { firstname: 'greg', lastname: 'bob' };

_.setWith(greg, 'fullname', '', calculateFullname);

function calculateFullname(val, key, person) {
  return person.firstname + ' ' + person.lastname;
}

assert.equal(greg.fullname, 'greg bob');

console.log(greg);
```

The assertion only passes if I change the path from `'fullname'` to `'fullname.foobar'`

**Comment by jdalton** [comment]
The `customizer` is called for creating the objects of `path`.
