### ISSUE TITLE
Ready for PascalCase? / _.pascalCase placeholder

### ISSUE THREAD

**Issue by no-stack-dub-sack** [lodash/lodash#3589]
I know this issue has been raised in the past, and that it does lend itself well to composition, however, a dedicated method would be easier and more obvious to beginners who might not think to go that route. Would you be willing to consider reviewing/accepting a PR? If so, I'd be happy to pitch in! 

Or, if not, what about a placeholder for `_.pascalCase` in the docs (since it is such a common casing), that points users to the `_.mixin` option (which tbh I would not have thought of right away without finding #942)?

Thanks!

**Comment by jdalton** [comment]
Hi @no-stack-dub-sack!

I want to hold off for now. Theirs clearly demand for `pascalCase` so it's on the shortlist of additions when the time comes.

**Comment by no-stack-dub-sack** [comment]
Thanks @jdalton! Just curious, I see no open issues, but are there any other opportunities for contributing to lodash or any other projects you're involved with that you might be able to point me to? I'm interested in getting a bit more experience contributing to open source.

**Comment by ryall** [comment]
@jdalton Maybe some more info other than just "I want to hold off"? What's the blocker on this? It's the only major case conversion I can see that is missing in Lodash and there's high demand, yet it keeps just being brushed off.

**Comment by jdalton** [comment]
Hi @ryall!

There is no threshold for 👍reactions.
They are used as an indicator of interest when we're looking to add new methods is all. I recommend using a mixin or one-off package until such time that it lands in Lodash. If those interested have moved to a specific implementation, this can also help us when we're looking to implement.
