### ISSUE TITLE
 _Promise.default.resolve is not a function

### ISSUE THREAD

**Issue by nullrocket** [lodash/lodash#3590]
I'm seeing this in in firefox and edge intermittently using lodash-es.  If I refresh a few times it doesn't happen any ideas where / what I should be looking for to track it down.

**Comment by jdalton** [comment]
Hi @nullrocket 

Maybe related to [this module](https://github.com/lodash/lodash/blob/4.17.4-es/_Promise.js). Nothing fancy going on our side. Might be a ESM just-landed in browsers so shaking out bugs kinda thing. Let me know if you find out more though.

**Comment by nullrocket** [comment]
I've removed the babel polyfill and I don't hit that error anymore. I'm just puzzled that it worked fine previously using browserify to load the non-es version. I will keep digging because removing the polyfill isn't a solution I can work with... yet.
