### ISSUE TITLE
Can functions be aliased?

### ISSUE THREAD

**Issue by jschank** [lodash/lodash#3592]
If so, Please, alias _.any to _.some.
Many is the time people on my team have searched for an _.any method, only to implement some strange inverse _.every call, because they don't see the _.some method.

Thanks
Schank

**Comment by jdalton** [comment]
Hi @jschank!

Over the releases I've tried to reduce the number of aliases as it adds to confusion and API inconsistencies. You can add aliases though through the [_.mixin](lodash.com/docs#mixin) method.

**Comment by jschank** [comment]
Hmm, ok. I getcha. I don’t know about mixin, but I’m not sure it would help.
Maybe just something as simple as in the docs have a _.any that just shows the _.some method

I’m not sure if that’s the same thing as an alias :)

but the problem I’m trying to tickle is that folks might come into lodash with familiarity with linq. And search for the equivalent to any. I’ve had 3 different folks all end up using !_.every because they thought there was no _.any. When there actually is. Its just called _.some.

I don’t think the API needs to support _.any, but it would be nice if _.some was easier to find, when looking for _.any
