### ISSUE TITLE
_.defaults performance issue?

### ISSUE THREAD

**Issue by NeoyeElf** [lodash/lodash#3593]
I have found a performance issue in my application in production env. according to the V8 profiling log analysis, I found that the copyObject() func in lodash/core.js cost the most cpu time, which is used by the defaults() func. **Is the func just need to take so much time to do the necessary job or still has improvement?**

more detail please check my question on stackoverflow: https://stackoverflow.com/questions/48296788/why-defaults-in-lodash-takes-a-lot-of-cpu-time. 

Thanks!

**Comment by jdalton** [comment]
Hi @NeoyeElf!

Based on your SO:
> Btw, I use the _.defaults() in a for-loop, and input data is large.

Yep, it's likely the data size. You can try removing the method and using a more bare bones approach.

**Comment by NeoyeElf** [comment]
Oh, Thanks！Would you mind telling me which part or sub func of the copyObject() func cause the  most cpu time : ) ?

**Comment by jdalton** [comment]
@NeoyeElf  You can just do
```js
const { hasOwnProperty } = Object.prototype

function defaults(object) {
  let i = 0
  const argCount = arguments.length

  while (++i < argCount) {
    const source = arguments[i]

    for (const key in source) {
      if (hasOwnProperty.call(source, key) &&
          (object[key] === void 0 ||
           ! hasOwnProperty.call(object, key))) {
        object[key] = source[key]
      }
    }
  }

  return object
}
```

**Comment by NeoyeElf** [comment]
I get it! compared the defaults() source code with the code above, In my situation, the forEach() and Object() func is unnecessary, also cost additional cpu time. Am I right?
