### ISSUE TITLE
_createWrap.js arg['partials'] is undefined..

### ISSUE THREAD

**Issue by chiaweilee** [lodash/lodash#3595]
- used babel-plugin-lodash(^3.3.2)
- webpack

in **PROD mode ONLY**
in DEV mode everything fine

`import { add, map, ... } from 'lodash/fp'`

- normal usage, worked
`add(1)(2) // 3`

- worked
`const Lo = function () {
    this.add = () => add(1)(2)
}
`
`new Lo().add() // 3`

- **not worked in PROD** (but worked in DEV)
`const addone = x => add(1)(x)`
`const Lo = function () {
    this.add = () => addone(2)
}
`
`new Lo().add()`

[_createWrap.js] 
TypeError: Cannot read property 'length' of undefined
    at Object.a [as add] (_createWrap.js:28)
`function createPartial (func, bitmask, thisArg, partials) /* <----partials undefined */`
`function wrapper ()`
`var leftLength = partials.length /* <---- error */`

It seems like a problem when webpack build vendor,
it might caused by my code style,
please help me find out why.

Thanks.

**Comment by jdalton** [comment]
Hi @chiaweilee!

That is interesting. Have you tried it without `babel-plugin-lodash` or different `uglify-es` settings to see if the issue resolves itself with slightly different settings?

I don't think the issue is on our end since we test with both dev and minified builds.

**Comment by chiaweilee** [comment]
of course resolves without babel-plugin-lodash, but I didn't wanna.
I will try another setting next.
