### ISSUE TITLE
Faulty implementation of Fisher-Yates shuffle in sampleSize.js

### ISSUE THREAD

**Issue by Crysinyan** [lodash/lodash#3597]
The current implementation selects it's random indices from 
`current index -> n`
instead of
`current index -> last index`

It also fails to set the variable 'n' to 1 when omitted. 

It then returns the entire original array with the first 'n' elements shuffled instead of the subset 'n' number of elements requested.

PR #3596 fixes these problems.

**Comment by jdalton** [comment]
Moved to #3596.
