### ISSUE TITLE
pick with arrays

### ISSUE THREAD

**Issue by rightaway** [lodash/lodash#3599]
```js
object = { item: true, inner: [ { value: 'a', other: true }, { value: 'b', other: true } ]}
pick(object, 'item', 'inner.value')
```
I would like to find a way to have `pick` return the following

```js
{ item: true, inner: [ { value: 'a' }, { value: 'b' } ]}
```

It only returns 

```js
{ item: true }
```

As a path I can do `'item', 'inner.0.value'` which will return

```js
{ item: true, inner: [ { value: 'a' } ]}
```

If `inner.value` isn't meant to work, `inner.*.value` could be the path for this.

**Comment by jdalton** [comment]
Hi @rightaway!

Our paths are for known paths. I don't want to combine paths plus search at this time as it complicates all methods that consume paths.
