### ISSUE TITLE
how to use _.differenceBy to comparison two array difference attribute

### ISSUE THREAD

**Issue by chaoxihailing** [lodash/lodash#3600]
I have two array Object, I want to find different attribute, but these property is not same , how can I do? I not good at english
`_.differenceBy([{"policeNumber": 101, "name": "bob"}],[{"userId": 101, "name": "bob"}], "policeNumber=userId");
`

**Comment by jdalton** [comment]
Hi @chaoxihailing!

That's not really what `difference` will do. You'll want to find a [good object diffing library](https://www.npmjs.com/search?q=object+diff).
