### ISSUE TITLE
Explicit chain sequences cannot Lazy evaluation?

### ISSUE THREAD

**Issue by mengfankitty** [lodash/lodash#3601]
I'm using lodash 4.17.4, but I find a problem when using chain sequences, e.g:

```
_([1,2]).chain().map(e => {console.log('map', e); return e;}).filter(e => {console.log('filter', e); return e;}).head().value()
```
**explicit**, the map func & filter func all execute **twice**

```
_([1,2]).map(e => {console.log('map', e); return e;}).filter(e => {console.log('filter', e); return e;}).head()
```
**implicit**, map func & filter func only execute **once**

Is it an issue? Or is right?

**Comment by jdalton** [comment]
Nice find @mengfankitty!

It's unexpected but is what it is for now. I'm not carrying over chaining into Lodash v5 so no other work will be done on them.

**Comment by mengfankitty** [comment]
@jdalton thank you
