### ISSUE TITLE
Current module `lodash.isfunction` is outdated // bug not recognizing async functions

### ISSUE THREAD

**Issue by frankthelen** [lodash/lodash#3603]
Hi,

I am using the most recent module versions.
It seams that the latest `lodash.isfunction` is not in sync with the latest `lodash`.

```
const _ = require('lodash'); // 4.17.4
console.log(_.isFunction(() => {})); // true -> OK
console.log(_.isFunction(async () => {})); // true -> OK

const lodashIsfunction = require("lodash.isfunction"); // 3.0.8
console.log(lodashIsfunction(() => {})); // true -> OK
console.log(lodashIsfunction(async () => {})); // false -> BUG
```

Thanks. :-)

**Comment by jdalton** [comment]
Hi @frankthelen!

Our individual method packages are no longer being updated. The `isFunction` method was handy when there were buggy environments with `typeof`. However, nowadays all environments support it properly so you can just use `typeof`.

**Comment by frankthelen** [comment]
@jdalton Thanks for the quick information. On `npm`, it's not really very clear that these packages are no longer updated.

**Comment by skeggse** [comment]
@jdalton maybe it makes sense to deprecate these
