### ISSUE TITLE
Add a one method to ensure that there is only 1 occurence in the collection

### ISSUE THREAD

**Issue by emaincourt** [lodash/lodash#3605]
Hi,

First of all thank you so much for your great work on lodash. I was thinking about a potential use case, in the same vein of `some` and `every`. Let's figure the following one where we need to ensure there is only one occurence :

```javascript
const arr = [1, 2, 3]
if (filter(arr, 2).length === 1) {
	// do something
}
```

In this case, it wouldn't require too much computation but in case of a pretty large array, this could be quite heavy. I've been thinking about this kind of implementation :

```javascript
function one(array, predicate) {
    let index = -1
    let counter = 1
    const length = array == null ? 0 : array.length
    
    while(++index < length) {
        if(predicate(array[index], index, array)) {
            if (!counter) {
                return false
            }
            counter--
        }
    }
    return true
}
```

You can find a comparison benchmark here :

https://jsperf.com/filter-vs-one/1

**Comment by jebarjonet** [comment]
Great! 🎉  I would suggest a boolean version to make it a bit more readable though:

```js
function one(array, predicate) {
  let index = -1
  let alreadyFound = false
  const length = array == null ? 0 : array.length
  
  while (++index < length) {
      if (predicate(array[index], index, array)) {
          if (alreadyFound) {
              return false
          }
          alreadyFound = true
      }
  }

  return true
}
```

**Comment by jdalton** [comment]
Hi @emaincourt!

In cases where you want one of something in a collection I recommend using builtin `Set`.

**Comment by StreetStrider** [comment]
👍 for this. This sounds like a thing of one family with `filter`, `count`, `pick` and others. Kinda basic primitive. The naming should be something like `single`, not `one`.

**Comment by emaincourt** [comment]
Hi @jdalton !

Thank you for your answer. I actually don't think `Set` would match the case. It is more about checking that any value is **only** one time inside of a collection, not to check if the collection includes **at least** one time this value.

**Comment by jdalton** [comment]
A `Set` only contains unique values which is why if that's a thing you're concerned with it's a better data type to work with.

**Comment by emaincourt** [comment]
Well I actually didn't know it, thank you. That's a good point. But as said it's more in case you want to use the unicity as a condition to perform or not an operation. Moreover, in case of objects' collection, we could not take advantage of this feature.

**Comment by jdalton** [comment]
If it's an object collection you should be using a `Map` data type instead. I rather folks use the best data type for their scenario than try to shoehorn it in.

**Comment by jebarjonet** [comment]
A `Set` forces its values to be unique, but the `single` method would be used to detect if a value is present only once in a regular array. Other values could be present multiple times in it (which does not work with a `Set`). Also for a `Set` of objects the native uniqueness comparison method might not be the same as the predicate one would use with this `single` method. I would also argue that I personally use objects and arrays (which work fine with Lodash), not `Set` and `Map`, hence the interest of such a method without having to update my entire codebase.

**Comment by jdalton** [comment]
I think this would make a great mixin. Lets see where it goes from there.
