### ISSUE TITLE
_.set(obj, array, value) unexpected result with numbers

### ISSUE THREAD

**Issue by adoyle-h** [lodash/lodash#3606]
## Code

`lodash.set({}, ['1', '2'], 3)`

Actually: `{ '1': [ <2 empty items>, 3 ] }`
Expected: `{'1': {'2': 3}}`

## Version
- lodash 4.17.4
- node v8.9.1

**Comment by jdalton** [comment]
Hi @adoyle-h!

This is by design. See [_.setWith](https://lodash.com/docs#setWith).
