### ISSUE TITLE
Is _.flow the same as using the pipeline operator?

### ISSUE THREAD

**Issue by AjaxSolutions** [lodash/lodash#3608]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Pipeline_operator

Are there any differences?

**Comment by felds** [comment]
Nope.

`_.flow` creates a new function combining the given functions.

They can be used to achieve similar things, though:

```ts
import {flow, toUpper, kebabCase} from 'lodash/fp'

const str = "Foo bar"

const a = flow([
  kebabCase,
  toUpper,
])(str)

const b = str
  |> kebabCase
  |> toUpper

// a == b
```

The biggest difference is that you can store the composed function for later use (`f = flow([kebabCase, toUpper])`).
