### ISSUE TITLE
When use chrome debugger，encountered forEach method directly skipped

### ISSUE THREAD

**Issue by ringcrl** [lodash/lodash#3609]
![wx20180126-143656](https://user-images.githubusercontent.com/16740021/35427776-63ebb612-02a6-11e8-9b08-0eb1e3ce86b8.png)

When you come here, will go directly to forEach at the end, will not enter the forEach method to go down layer by layer

**Comment by jdalton** [comment]
Hi @ringcrl!

This isn't a lodash issue. You may have your dev tools configured to skip third-party code.
