### ISSUE TITLE
DropWhile/TakeWhile is not working properly when the object missing target property

### ISSUE THREAD

**Issue by clauzf** [lodash/lodash#3610]
```
var obj = [{a: 'xxx' }, {b: 'xxx'}, {a: 'xxx'}]
_.dropWhile(obj, 'a')
```

Expect: `[{b: 'xxx'}]`
Actual: `[{b: 'xxx'}, {a: 'xxx'}]`

```
var obj = [{a: 'xxx' }, {b: 'xxx'}, {a: 'xxx'}]
_.takeWhile(obj, 'b')
```

Expect: `[{b: 'xxx'}]`
Actual: `[]`

```
_.VERSION
"4.17.4"
```

**Comment by jdalton** [comment]
Hi @clauzf!

Please read the descriptions for these methods again.
For `takeWhile` it will take while the predicate returns truthy. So your object in `array[0]` fails the predicate so it stops taking right off the bat.

**Comment by clauzf** [comment]
Thx. I did misread `Elements are dropped until predicate returns falsey.` as `Elements are dropped unless predicate returns falsey.`

Can we improve the wording a bit to emphasis `Only first elements are...`.
I found the original requirement ticket [Issue 155](https://github.com/lodash/lodash/issues/155), mentioning [preludels#take-while](http://www.preludels.com/#take-while)

Their wordings are more straightforward mentioning "first" and the example clearly shows, `take-while odd, [1 3 5 4 8 7 9] #=> [1, 3, 5]`, `7, 9` is not returned. 

While the current [lodash#takeWhile](https://lodash.com/docs/4.17.4#takeWhile)/[lodash#dropWhile](https://lodash.com/docs/4.17.4#dropWhile) documents are not showing this early exit behaviour clearly. 

> Only last example shows early exit
```
var users = [
  { 'user': 'barney',  'active': false },
  { 'user': 'fred',    'active': false },
  { 'user': 'pebbles', 'active': true }
];
 
_.takeWhile(users, function(o) { return !o.active; });
// => objects for ['barney', 'fred']
 
// The `_.matches` iteratee shorthand.
_.takeWhile(users, { 'user': 'barney', 'active': false });
// => objects for ['barney']
 
// The `_.matchesProperty` iteratee shorthand.
_.takeWhile(users, ['active', false]);
// => objects for ['barney', 'fred']
 
// The `_.property` iteratee shorthand.
_.takeWhile(users, 'active');
// => []
```

> No example shows early exit
```
var users = [
  { 'user': 'barney',  'active': false },
  { 'user': 'fred',    'active': false },
  { 'user': 'pebbles', 'active': true }
];
 
_.dropWhile(users, function(o) { return !o.active; });
// => objects for ['pebbles']
 
// The `_.matches` iteratee shorthand.
_.dropWhile(users, { 'user': 'barney', 'active': false });
// => objects for ['fred', 'pebbles']
 
// The `_.matchesProperty` iteratee shorthand.
_.dropWhile(users, ['active', false]);
// => objects for ['pebbles']
 
// The `_.property` iteratee shorthand.
_.dropWhile(users, 'active');
// => objects for ['barney', 'fred', 'pebbles']
```
