### ISSUE TITLE
cannot run tests

### ISSUE THREAD

**Issue by piotr-s-brainhub** [lodash/lodash#3611]
OS: Mac OS X 10.12.6
Node.js: 8.9.4
npm: 5.6.0
Lodash last commit: 47a6d538f5759fc5788f1bbb147caa7fde6b0a92

I did `npm i && npm t`

I got:
```
Error: Cannot find module '/Users/me/projects/lodash/lib/main/build-dist.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by jdalton** [comment]
Yep, our unit tests are out of commission at the moment. See our [contributing notice](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#construction-notice-construction).
