### ISSUE TITLE
Feature request: `defaultTo` with multiple values

### ISSUE THREAD

**Issue by eran-nussbaum** [lodash/lodash#3613]
Hi,
I really like to use `_.defaultTo(a, b)` because it is much more readable than `a || b` (and works with `0`, `false` and `''` as valid values for `a`).
Sometimes I find myself doing this:
```js
var foo = _.defaultTo(bar, baz);
foo = _.defaultTo(foo, bax);
```
or its less readable sibling:
```js
var foo = _.defaultTo(_.defaultTo(bar, baz), bax);
```

I wish I could do this:
```js
var foo = _.defaultTo(bar, baz, bax);
```
Which returns the first argument whose value is not one of `undefined`, `null` or `NaN`.
Maybe its name should be different, like `_.defaultToAny`.

Any chance you're ever going to support such functionality?
Thank you very much!

**Comment by jdalton** [comment]
This sounds like a great enhancement. Would you be up for making a PR?

**Comment by radi-cho** [comment]
I'm able to add this and can open PR tomorrow!

**Comment by jdalton** [comment]
Thanks @radi-cho, I'd like to give @eran-nussbaum dibs first though.

**Comment by eran-nussbaum** [comment]
@jdalton oh, wow, I'm honored. If I do this it is going to be my very first contribution to an open-source project. There's no project I'd be happy to contribute to more than the legendary *Lodash*. I'd be happy to try and hope it will be good enough.

**Comment by jdalton** [comment]
@eran-nussbaum Awesome!

Don't worry about tests for now. As things [are a bit of a mess](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#construction-notice-construction). You can post usability tests in the PR comments.

**Comment by eran-nussbaum** [comment]
@jdalton, here it is: https://github.com/lodash/lodash/pull/3615
Please review and comment. :)
Thanks

**Comment by jdalton** [comment]
Moved to #3615.
