### ISSUE TITLE
`initCloneArray()` to use `new`

### ISSUE THREAD

**Issue by SylvainEstevez** [lodash/lodash#3614]
### Issue

Currently, in the NPM version, cloning an instance of an `Array` subclass raises a `TypeError` because ES6 classes require the `new` when instantiating.

Unlike the `Array` constructor, subclasses don't allow function constructors.

### Example

```javascript
import * as Lodash from 'lodash';

class MyArray extends Array {}

const instance = new MyArray();

Lodash.clone(instance); // TypeError: Class constructor MyArray cannot be invoked without 'new'
```

### Resolution

Make [`initCloneArray()`](https://github.com/lodash/lodash/blob/npm/_initCloneArray.js#L16) instantiate the new array using the `new` keyword.

Note that `master` [already fixes this](https://github.com/lodash/lodash/blob/master/.internal/baseClone.js#L131) but the npm branch doesn't seem up to date. So maybe the fix is simply to update that branch / the underlying modules.

**Comment by jdalton** [comment]
Thanks @SylvainEstevez!

Glad to hear it's fixed on `master`!

**Comment by SylvainEstevez** [comment]
@jdalton Any plan on publishing an update for NPM?

**Comment by jdalton** [comment]
The next update will be for v5. There may be some minor v4 updates to better support Webpack 4 tooling but I can't promise any fixes in master will make it into that.

**Comment by SylvainEstevez** [comment]
Gotcha. Thanks for the precision 👍
