### ISSUE TITLE
How about to enhancement Date object?

### ISSUE THREAD

**Issue by jsister** [lodash/lodash#3617]
Lodash has implemented many many many functions to make coding easier. 👍 

...and I have a bit of question:  

# Does it is a good idea to enhancement Date object?
such as date formatting, date calculation, etc.

**Comment by jdalton** [comment]
Hi @jsister!

For dates please check out [moment.js](https://github.com/moment/moment).

**Comment by jsister** [comment]
moment.js is so heavy! 😢 , and lodash is very popular. 
and .... I got it, thanks!

**Comment by StreetStrider** [comment]
@jsister check [date-fns](https://github.com/date-fns/date-fns), it looks modularized and got the same features as Moment.
