### ISSUE TITLE
Sets the value at path of object. 

### ISSUE THREAD

**Issue by Erushenko** [lodash/lodash#3619]
Sets the value at path of object. 
Expect object 'key' when path equal 'key.1' instead of the array.

```
_.set({}, 'key.1', 3)
// => { key: [ empty, 3] }

Expect 
// => { key: { 1: 3 }}
```

**Comment by jdalton** [comment]
Hi @Erushenko!

See [_.setWith](https://lodash.com/docs#setWith).
