### ISSUE TITLE
Includes Case Sensitive

### ISSUE THREAD

**Issue by kalyanimanu** [lodash/lodash#3621]
Hi Everyone,

I worked with  Includes in Loadash,

Includes is case sensitive:
_.includes("kalyani","al")--->true
now my requirement is 
_.includes("kalyani","AL")--->needs to be true because my requirement is need to match only charecters not case sensitive and case insensitive..

Please help me how to achieve this issue with cases of string.

**Comment by kalyanimanu** [comment]
Please help me the above issue.its bit urgent in my solution.

**Comment by jdalton** [comment]
Hi @kalyanimanu!

You can use plain JS:
```
/al/i.test(string)
```
If you have more questions head over to our [gitter chat](https://gitter.im/lodash/lodash) for help.
