### ISSUE TITLE
Use "memoizeCapped" instead of "memoize" while caching the results

### ISSUE THREAD

**Issue by MaciejBaj** [lodash/lodash#3622]
Use of `memoize` function and caching result for every `path` provided for `get` function can lead to memory leaks when `path` variable will be changed frequently for the following calls.

The issue is linked only with `lodash.get` installable package:
https://github.com/lodash/lodash/tree/4.4.2-npm-packages/lodash.get

The same `get` function from the main `lodash` repository uses `memoizeCapped` which limits the cached values to 500.

**Comment by jdalton** [comment]
Hi @MaciejBaj!

This is fixed in Lodash v4.17.4.
I recommend using `lodash/get` instead of the individual method modules.
