### ISSUE TITLE
_.isFinite/isInteger/isLength returns false from Number() constructor

### ISSUE THREAD

**Issue by clujin** [lodash/lodash#3623]
```
_.isFinite(new Number(0)) => false
_.isInteger(new Number(0)) => false
a = {length: new Number(1)}
_.isLength(a.length) => false
```

As such, the _.isFinite implementation is different from the global isFinite implementation. Consider this case:

```
_.isFinite([]) => false
isFinite([]) => true
```

I believe this is a bug. The code only checks that the value passed in is of `type x == 'number'` but it doesn't check them as `instanceof Number`. The only correct check I saw is from the _.isNumber() method which checks for isObjectLike(). Maybe have them all use _.isNumber to first check?

**Comment by jdalton** [comment]
Hi @clujin!

Try
```js
Number.isFinite(new Number(0)) // false
```

**Comment by clujin** [comment]
Wait, how is this invalid? Usage of _.isFinite aside, the _.isInteger() and _.isLength() bugs are still there.

**Comment by jdalton** [comment]
Try
```
Number.isInteger(new Number(0)) // false
```

**Comment by clujin** [comment]
And what of _.isLength()? I'm not sure that's addressing the root issue which is the in correctness of the methods. It seems like you're just telling me to not use these methods.

**Comment by jdalton** [comment]
The `_.isLength` is testing for array-like values with a valid `length`. As arrays don't have `.length` properties that are `Number` objects I'm fine with the method the way it is.

You're free to use whatever methods you like for whatever reasons you like 😋

**Comment by clujin** [comment]
If each of these 3 methods have alternatives, then what's the point of having them in the current library when they are obviously incorrect?

**Comment by jdalton** [comment]
They aren't obviously incorrect 🙃 . There is no alternative for `_.isLength` and not all supported environments have `Number.isInteger` or `Number.isFinite`.

**Comment by clujin** [comment]
So are you advocating not to fix this even for environments that doesn't have Number.isFinite/isInteger? Because I just checked Underscore.js, and they got this implementation correct.

**Comment by jdalton** [comment]
Our methods are different. You're kind of missing the point. Feel free to read up on those newer method on MDN for [Number.isInteger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger) and [Number.isFinite](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite).
