### ISSUE TITLE
Safe to assume object keys are iterated in original order?

### ISSUE THREAD

**Issue by leoskyrocker** [lodash/lodash#3624]
I thought js objects are unordered collections and iteration order is not guaranteed,
but from many suggestions I see in the issues or stackoverflow it seems people are relying on
the fact that the iteration order is left-to-right in original order.

I was looking for a Map equivalent in lodash for ordered collection but didn't find any.
I understand that it would be the safest to use an ordered collection,
but is it *fairly safe* to make the above assumption on unordered collections too?

**Comment by jdalton** [comment]
Hi @leoskyrocker!

Later version of the js spec did specify object iteration order for own properties but it depends on engine and environment. Use a `Map` polly fill if you need one.
