### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by vko-online** [lodash/lodash#3625]
https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L2804

**Comment by jdalton** [comment]
Yes, it's a way to ensure the value isn't `NaN`.

**Comment by falsyvalues** [comment]
@jdalton That will be top asked question sooner or later :speak_no_evil:

**Comment by StreetStrider** [comment]
@falsyvalues I believe topics like "why some *-case method works as not expected by me" and "please add new semantics to path getting/setting" still are on the top :D

**Comment by jdalton** [comment]
I need to make it less magic in some cases (auto creating arrays for paths with indexes) and more magic in others (supporting `*` indexes).

**Comment by falsyvalues** [comment]
@StreetStrider You are right, but this is trending for sure :chart_with_upwards_trend: :smiley: .
@jdalton I like magic, this how people learning new things :+1:

**Comment by StreetStrider** [comment]
But the *absolute* top is «Why `.map(parseInt)` yields wrong result?»

**Comment by falsyvalues** [comment]
I totally forgot about it :smile_cat: 

@jdalton maybe we should make some faq?
