### ISSUE TITLE
maxBy, minBy return undefined when iteratee consistently returns null, undefined or NaN

### ISSUE THREAD

**Issue by jonapgar** [lodash/lodash#3629]
```javascript
let x = _.maxBy([1,2,3],n=>null)
//expect x to equal 1, instead it equals undefined
```
I would expect maxBy, minBy to always return an element from the collection, regardless of what value the iteratee returns.

**Comment by jdalton** [comment]
Hi @jonapgar!

This is by design. Iteratees returning `null` or `undefined` are ignored and if nothing can be computed then `undefined` is returned.

**Comment by jonapgar** [comment]
Ok thanks for letting me know. I actually encountered this with NaN specifically, so I suppose that is ignored as well.

**Comment by acjohnso25** [comment]
I just ran into this as well.  

My code was calling `minBy(shares, 'shareTime')` where `shares` consisted of only one object with `shareTime = null`.  The null value was bad and originated from an incorrect DB record elsewhere, but `minBy` returning `undefined` caused a crash when I tried to access properties on the result.  (I was doing a check for `shares.length > 0` before calling `minBy`, on the assumption that this guaranteed it would return an item from the list.) 

Took me a while to figure out what was going on, and I was about to submit a bug report when I came across this one.  I understand the explanation, but it still seems a bit counter-intuitive to pass a single object to the function and have it return `undefined`.  Strikes me as a bit of a "gotcha" at the very least...

**Comment by MikeyBurkman** [comment]
I know this is an old issue, but this just bit me pretty badly. It's really unintuitive for `minBy` or `maxBy` to ever return `undefined` for a non-empty array, and I believe is counter to implementations in most other languages I've seen. Can we at least get this behavior documented somewhere?

The `min` and `max` functions are also similar -- if I do `min([null])` it returns `undefined`, which is also undocumented behavior.

**Comment by danvk** [comment]
This behavior is surprising and should at least be mentioned in the documentation for [`_.minBy`](https://lodash.com/docs/4.17.11#minBy) and [`_.maxBy`](https://lodash.com/docs/4.17.11#minBy) 

Perhaps change:

> (*): Returns the minimum value.

To:

> (*): Returns the minimum value, or `undefined` if the iteratee returns `null`, `undefined` or `NaN` for all values.

re: being unusual, in Python, for example:
```
>>> min([0], key=lambda x: math.nan)
0
```

**Comment by mrwillis** [comment]
Agreed. It is not intuitive. There should be an option to return a default value or something.
