### ISSUE TITLE
Please consider adding 'pickDeep' and 'pickDeepWith' functions

### ISSUE THREAD

**Issue by phobos-labs** [lodash/lodash#3632]
At the moment, by using the 'pick' function it is possible to create an object out of another object's properties subset at level zero only. Given that 'get' already supports the retrieval of a nested property's value, please consider introducing a 'pickDeep' function that under the hood utilizes 'get''s functionality. I can image the usage to be like:

_.pickDeep(object, ['a', 'b.c', 'd[3].e.f']);

Thanks for your time!

**Comment by jdalton** [comment]
Dup of #723.
