### ISSUE TITLE
Lodash/String/template leaks the memory

### ISSUE THREAD

**Issue by Guobacai** [lodash/lodash#3633]
In our app, we are using the lodash template(_template) to compile a very large string converted by JSON.Stringfy(around 4.2MB) in the runtime. The code is similar to the following:

In moduleA: 

module.exports = {
  a: function() {
    var _tpl = _template(str1);
    return _tpl(data);
  }
}

In moduleB: 

var utils = require('moduleA');

module.exports = {
  b: function() {
    return Promise.resolve().then(function() {
       utils.a();
    });
  }
}

Every time the b function is called, I compare the heap snapshots and it shows a large string held by Global Handles. The large string looks like the _tpl.source

Is there anything that I did wrong? Could someone suggest me how to get that large string GC?

**Comment by jdalton** [comment]
Hi @Guobacai!

You can delete the `delete _tpl.source` property.

**Comment by Guobacai** [comment]
Sorry, I tried,but it doesn't solve the issue.

var compileStr = function(str, compiledData) {
  var compiledTpl = _template(str);
  delete compiledTpl.source;
  var compiledStr = compiledTpl(compiledData);
  return compiledSchema;
};

I am still able to see that large string when compare two snapshot.

Thanks.

**Comment by jdalton** [comment]
🤷
