### ISSUE TITLE
About handling 'undefined' in lodash.merge

### ISSUE THREAD

**Issue by littlepad** [lodash/lodash#3634]
The handling of 'undefined' in lodash.merge differs between 4.6.0 and 4.6.1.
4.6.0 is skip 'undefined', but 4.6.1 is contain it.

lodash.merge@4.6.0

```
merge({ a: 1 }, { b: undefined });
// -> { a: 1 }
```

lodash.merge@4.6.1

```
merge({ a: 1 }, { b: undefined });
// -> { a: 1, b: undefined }
```

**Comment by falsyvalues** [comment]
Hi @littlepad In v4.17.5 its like this:
```
_.merge({ a: 1 }, { b: undefined });
{a: 1, b: undefined}
```

**Comment by jdalton** [comment]
Hi @littlepad!

The lodash.merge@4.6.0 behavior was considered a bug.
Explicit `undefined` values should be merged.
