### ISSUE TITLE
Copying Set and Map in 4.17.5

### ISSUE THREAD

**Issue by ilgiznice** [lodash/lodash#3638]
Hello!

With recent changes to how `Set` and `Map` are being copied, custom properties are not getting copied to new object.

So, this doesn't work anymore:

```javascript
const { cloneDeep } = require('lodash');

const set = new Set();
set.refs = new Map(); // Set { refs: Map() }

cloneDeep(set);  // Set {}
// In 4.17.4 it was equal to Set { refs: Map() }

new Set(set); // Set {}
```

**Comment by jdalton** [comment]
Ah I see. Yes this was outside our intended support. We usually don't clone custom properties on specialty value types like arrays, dates, regexps, (maps, sets), etc.

**Comment by jdalton** [comment]
Thank you! I'll keep an eye on it and if it ends up breaking a lots of things I'll revisit.
