### ISSUE TITLE
when property is +0, _.get() can't get correct result;

### ISSUE THREAD

**Issue by noshower** [lodash/lodash#3639]
_.get({'-0' : 'a'},-0)  //return "a"
_.get({'+0':'b'},+0) //return undefined

sound code: 

       function toKey(value) {

            if (typeof value == 'string' || isSymbol(value)) {

                return value;

            }

            var result = (value + '');
    
            return (result == '0' && (1 / value) == -INFINITY) ? '-0' : result;

        }

**Comment by jdalton** [comment]
There is no way to detect a difference between a number `0` and `+0`. You should use a string key of `"+0"`

**Comment by bfred-it** [comment]
[Sure there is 😐](https://npms.io/search?q=negative+zero)

```js
function isNegativeZero(number) {
	return number === 0 && (1 / number) === -Infinity;
}
```
