### ISSUE TITLE
isEqual does not respect the order of Arrays contained within Sets

### ISSUE THREAD

**Issue by ChristopherChudzicki** [lodash/lodash#3640]
I would have expected (lodash 4.17.5. )

```
_.isEqual(
  new Set([1, [2, 3]]),
  new Set([1, [3, 2]])
)
```

to return `false` because the set items are not equal. It seems as if `isEqual` does not respect the order of arrays contained within sets.

This seems like a bug, or is it intended?

repl: [isEqual does not respect the order of Arrays contained within Sets](https://repl.it/@cchudzicki/isEqual-does-not-respect-the-order-of-Arrays-contained-withi)

**Comment by jdalton** [comment]
Hi @ChristopherChudzicki!

This was intended as a set is really a bag of values. It's in the set or it isn't the order shouldn't really matter.

**Comment by ChristopherChudzicki** [comment]
@jdalton I agree that the order of items in a set should not matter. 

But notice the sets in this example contain arrays: The first set contains the array [2, 3], the second set contains the array [3, 2]. These arrays are items of the set, and are not equal.

**Comment by jdalton** [comment]
Ah, you're right! For v5 I'm dropping `isEqual` in favor of Node [utils.isDeepStrictEqual](https://nodejs.org/api/all.html#util_util_isdeepstrictequal_val1_val2) 
```js
util.isDeepStrictEqual(new Set([1, [2, 3]]),new Set([1, [3, 2]]))
// => false
util.isDeepStrictEqual(new Set([1, [2, 3]]), new Set([1, [2, 3]]))
// => true
```
