### ISSUE TITLE
Unexpected behavior with _map and _pickBy

### ISSUE THREAD

**Issue by dkesler** [lodash/lodash#3641]
It seems like using `_.map([...], _pickBy)` is resulting in very unexpected behavior.  All examples are run in the REPL on https://lodash.com/docs/4.17.5#pickBy

`_.map([{'a': null}, {'a': 'x'}, {'a' : 'y'},{'a': null}, {'a': 'z'}], _.pickBy)` => `[{}, {}, {}, {}, {}]`
`_.map([{'a': 'x'}, {'a' : 'y'},{'a': null}, {'a': 'z'}], _.pickBy)` => `[{'a': 'x'}, {}, {}, {}]`
`_.map([{'a': 'x'}, {'a' : 'y'},{'a': null}, {'a': 'zzzz'}], _.pickBy)` => `[{'a': 'x'}, {}, {}, {'a' : 'zzzz'}]` (the field is not present in the last object with 2 or 3 `z` characters either, but appears once you add 4)

interestingly, the behavior is as expected when creating a lambda around _.pickBy:
`_.map([{'a': null}, {'a': 'x'}, {'a' : 'y'},{'a': null}, {'a': 'z'}], (v) => _.pickBy(v))` => `[{}, {'a': 'x'}, {'a': 'y'}, {}, {'a': 'z'}]`
`_.map([{'a': 'x'}, {'a' : 'y'},{'a': null}, {'a': 'z'}], (v) => _.pickBy(v))` => `[{'a': 'x'}, {'a': 'y'}, {}, {'a': 'z'}]`
`_.map([{'a': 'x'}, {'a' : 'y'},{'a': null}, {'a': 'zzzz'}], (v) => _.pickBy(v))` => `[{'a': 'x'}, {'a': 'y'}, {}, {'a' : 'zzzz'}]`

I haven't been able to detect any pattern to why sometimes fields are picked or not in the first pattern, these are just some use-cases i came across trying to determine the behavior

**Comment by jdalton** [comment]
Hi @dkesler!

The `_.pickBy` method expects an predicate so really isn't suited for use as an iteratee itself in `_.map`.

**Comment by dkesler** [comment]
according to the docs _.pickBy has a default predicate of _.identity, which is actually the predicate that i want.  (See https://stackoverflow.com/questions/30812765/how-to-remove-undefined-and-null-values-from-an-object-using-lodash which put me on that path).

i'm not seeing how it's not a bug.  if i call `_.map([...], _.pickBy)`, i expect _.pickBy to be applied to each member of the list.  It's perfectly valid to apply _.pickBy to every member of the list.  So I'm not sure how a combining two valid operations is somehow an invalid thing to do.

**Comment by jdalton** [comment]
The `map` iteratee is provided 3 arguments `value, index, array` and that effects what is provided to `pickBy`.

**Comment by dkesler** [comment]
Bleh, sorry, I didn't realize map was passing additional stuff into the iteratee function.  Thanks for the help.

**Comment by falsyvalues** [comment]
@StreetStrider :champagne: :smiley:
