### ISSUE TITLE
Add _.tee

### ISSUE THREAD

**Issue by yordis** [lodash/lodash#3642]
https://en.wikipedia.org/wiki/Tee_(command)

This becomes useful when you are debugging chained commands

```
_
.chain(something)
.filter(...)
.takeRight(...)
.tee(console.log) // <--- debugging the values
.map(...)
.value()
```

**Comment by jdalton** [comment]
Hi @yordis!

Thewre is [_#tap](lodash.com/docs#tap)

**Comment by yordis** [comment]
@jdalton sorry about that.
