### ISSUE TITLE
MongoDb like unwind?

### ISSUE THREAD

**Issue by jlaustill** [lodash/lodash#3645]
I find myself today in need of an unwind feature like mongoDB has.   Here's what I came up with in the form of a fiddle.

[unwind](http://jsbin.com/mizubatiwa/edit?html,js,console)

This seems to work great, but I'm curious, A. does lodash already contain this?  If not, B. would you be interested in a PR that adds it?  C. Is there just a way better way to accomplish this?

Here's the code in case the fiddle dies.

```
const input = [{
  id: 1,
  name: "Jack Doh",
  scores: [2,3,4],
  assets: [5,6,7],
},{
  id: 2,
  name: "Jane Yay",
  scores: [12,23,34],
  assets: [45,56,67],
}];

const unwind = (array, field) => {
  if (_.isArray(array)) {
    return _.flatten(array.map((input) => {
      if (_.isArray(input[field])) {
        return input[field].map((i) => {
          const output = { ...input };
          output[field] = i;

          return output;
        });
      }
      return input;
    }));
  }
  return array;
};

const unwound = unwind(input, 'scores');

console.log(unwound);
```

And here is the output

```
[ {
  assets: [5, 6, 7],
  id: 1,
  name: "Jack Doh",
  scores: 2
}, {
  assets: [circular object Array],
  id: 1,
  name: "Jack Doh",
  scores: 3
}, {
  assets: [circular object Array],
  id: 1,
  name: "Jack Doh",
  scores: 4
}, {
  assets: [45, 56, 67],
  id: 2,
  name: "Jane Yay",
  scores: 12
}, {
  assets: [circular object Array],
  id: 2,
  name: "Jane Yay",
  scores: 23
}, {
  assets: [circular object Array],
  id: 2,
  name: "Jane Yay",
  scores: 34
}]
```

**Comment by jlaustill** [comment]
Thumbs down with no explanation when my entire purpose here was to get feedback.  Kinda odd haha

**Comment by jdalton** [comment]
Hi @jlaustill!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by SwenChan** [comment]
I think this feature is awesome! It's useful in some case i have met.

**Comment by mohaqqani** [comment]
This feature wold be awesome to have in Lodash

**Comment by kdong007** [comment]
_.flatMap is exactly $unwind

**Comment by ArkInnovationsPH** [comment]
+1 here

**Comment by evrastil** [comment]
Looks good also you can try to use my npm package [unwind-array][1] see some [example usages][2].


  [1]: https://www.npmjs.com/package/unwind-array
  [2]: https://www.npmjs.com/package/unwind-array#ex1-unwind-shallow-path
