### ISSUE TITLE
Feature request: destructure()

### ISSUE THREAD

**Issue by gunar** [lodash/lodash#3646]
It's very practical that `get()` allows you to access subkeys by using the dot notation e.g. `obj.file.name`. I wish I could use this for destructuring as well.

Here's where my head is at.
Thank you in advance for your time.

### Object
```js
const obj = {
  file: { name: 'lodash' },
  person: { name: 'gunar', age: 17 },
}
```
### With the proposed feature
```js
const {
  'file.name': fileName,
  'person.name': personName,
  'person.age': personAge
} = destructure(obj)
```

### Without the proposed feature
```js
// I find this slightly confusing
const {
  file: { name: fileName },
  person: { name: personName, age: personAge }
} = obj

//  and this is not really DRY
const fileName = get('file.name')(obj)
const personName = get('person.name')(obj)
const personAge = get('person.age')(obj)
```

**Comment by jdalton** [comment]
This is a dup of #2240 but with a super cool use case. I dig it. Would you mind posting a reference to this issue in #2240.
