### ISSUE TITLE
Custom iterable objects

### ISSUE THREAD

**Issue by AlesMenzel** [lodash/lodash#3649]
Hello,
custom iterable objects (= objects implementing `Symbol.iterator`) are not behaving the same as native iterables (i.e. arrays or strings), consider this example: https://jsfiddle.net/AlesMenzel/W4QfJ/6834/

![](https://image.prntscr.com/image/AqCH2EzzQtWTmVtcGppzOw.png)

**Comment by jdalton** [comment]
Hi @AlesMenzel!

Yes, they are not the same. I'm not interested in supporting them. I'm sure there are other libs for supporting the  iterator protocol.
