### ISSUE TITLE
fp/reduce does not work as expected

### ISSUE THREAD

**Issue by pyxarez** [lodash/lodash#3652]
Hello!!

Today I've tried to use fp version of reduce helper and found out that a callback passed to it does not receive all the documented arguments, especially key if i pass object as a collection.

E.g.
```javascript
const reduce = require('./fp/reduce');

reduce(
  (acc, ...args) => { console.log(args); return acc; },
  {},
  { test: 1, test2: 2, test3: 3 },
);

// [ 1 ]
// [ 2 ]
// [ 3 ]
```

**Comment by simondell** [comment]
The FP guide says that reduce's iteratee function has its [arguments caped](20848609) at two. As the collection/accumulator is passed as the first, and the "next" value passed as the second, your code snippet looks correct to me.

**Comment by pyxarez** [comment]
@simondell That's it! Thanks, I should be a little more attentive next time:)
