### ISSUE TITLE
How to map a Functor?

### ISSUE THREAD

**Issue by galenjiang** [lodash/lodash#3653]
When i use Ramda, I found the 'map' type defination
Functor f => (a → b) → f a → f b
Takes a function and a functor, applies the function to each of the functor's values, and returns a functor of the same shape.

```
map(i => { return i * 2 })({map: (f) => f(1)})
```
Can lodash deal like above?

**Comment by jdalton** [comment]
Hi @galenjiang!

We don't have a map type.

**Comment by galenjiang** [comment]
Sorry @jdalton , I did not clearly present it. map type is not exactly, It is a Functor in fp.
I mean that _.map can dispatches to the map method of the second argument(Functor type). 
see the link [ramda-map](http://ramdajs.com/docs/#map)
