### ISSUE TITLE
jQuery Examples

### ISSUE THREAD

**Issue by DimaZuien** [lodash/lodash#3654]
In documentation and here, on Github, there are examples of using lodash methods that are written with jQuery (those ones I've found are `before`, `debounce` and `throttle`). Isn't it better to rewrite it with native JavaScript?

**Comment by jdalton** [comment]
Hi @DimaZuien!

Folks tend to know `jQuery` so it simplifies my documentation example.

**Comment by DimaZuien** [comment]
Oh, I see. I just thought that it might be a little bit outdated. It was a little bit weird to see these examples among all bunch of those ones with native JS.

Nonetheless, thanks for your work, I'm new to this, but it looks awesome!
