### ISSUE TITLE
Merge behaviour with `null`/`undefined` and arrays

### ISSUE THREAD

**Issue by nunocastromartins** [lodash/lodash#3655]
```js
_.merge({a: null}, {a: [1]})
// => {a: [1]}
_.merge(null, [1])
// => {'0': 1}
```
Not sure if this happens by design, but I'd say that the result for both expressions is inconsistent. Also note that the same happens for `undefined` instead of `null`.

I would expect the second expression to either:
- Return an array (`[1]`) instead of an object (`{'0': 1}`);
- Return `null`/`undefined`/throw an exception, documenting that the destination object may not be `null`/`undefined`.

**Comment by jdalton** [comment]
Hi @nunocastromartins!

It's really an object merging method so when you don't provide an object one is created. In the case of the array as the object source that's more an edge use of the API that could happen but isn't really  the primary focus.
