### ISSUE TITLE
[question] any timeline for v5 release?

### ISSUE THREAD

**Issue by harshes53** [lodash/lodash#3656]
Hi @jdalton, 

I have been checking regularly on the lodash repo, as you mentioned is past that you prefer having major updates in the beginning of the year, preferably Jan, just wanted to know the timeline for the release of v5.

thanks!

**Comment by jdalton** [comment]
Hi @harshes53!

Thanks for checking in. I'm trying to get ESM (ECMAScript modules) in Node in a good place to be able to ship. It currently requires [a ton of my attention](https://github.com/standard-things/esm/graphs/contributors). The good news is things are starting to level off on that front which means I can shift focus back to utils on top of ESM.
