### ISSUE TITLE
lodash newbie gets a different result than what i see in docs

### ISSUE THREAD

**Issue by edwardsmarkf** [lodash/lodash#3657]
hello -

[this lodash _.has doc page](https://lodash.com/docs/4.17.5#has) shows the following examples:

> var object = { 'a': { 'b': 2 } };
> var other = _.create({ 'a': _.create({ 'b': 2 }) });
>  
> _.has(object, 'a');
> // => true
>  
> _.has(object, 'a.b');
> // => true

however, when i run this in my browser console, i see false not true:

```
var lo = document.createElement('script');
lo.src = "https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.5/lodash.core.min.js";
document.getElementsByTagName('head')[0].appendChild(lo);
var object = { 'a': { 'b': 2 } };
_.has(object, 'a.b');   // returns false!
```
but looking at `object.a.b` shows "2".

suggestions?

**Comment by jdalton** [comment]
Hi @edwardsmarkf!

You're using the [core build](https://github.com/lodash/lodash/wiki/Build-Differences) which has less functionality including lack of deep path support.
