### ISSUE TITLE
Documentation warning: _.get() with default value returning null

### ISSUE THREAD

**Issue by Miriloth** [lodash/lodash#3659]
Consider adding a warning to **_.get()** documentation saying that if null is found, _.get() will return it even though it has default value set. It might be unclear at first glance.

Example:
```
const parent = {
  child: null
}

_.get(parent, 'child', 'default')   // null
```

**Comment by joelove** [comment]
The documentation specifies this behaviour:
> Gets the value at _path_ of _object_. If the resolved value is _undefined_, the _defaultValue_ is returned in its place.

**_.get()** attempts to get a value from an object at the specified path. In JavaScript, `null` is a value so it returns that. The default value is only used if there is no matching key set on the object (or the value of that key is set to `undefined`, which is essentially the same thing).

**Comment by pkoniu** [comment]
In JavaScript 'null' is also a Falsy value. Having a way to define on your own which values should be replaced with a default would be great.

**Comment by Miriloth** [comment]
I am aware of all the things @joelove pointed out, and I am not questioning **_.get()** behaviour. In this issue I am just proposing to add a Note emphasizing this case to the documentation. I know bunch of people who were not aware of that fact.

**Comment by jdalton** [comment]
@Miriloth Feel free to make a PR.
