### ISSUE TITLE
_(collection).reduce not returning wrapped collection intentionally ?

### ISSUE THREAD

**Issue by alesmenzelsocialbakers** [lodash/lodash#3660]
Hello!

Lodash version: **4.17.5**

**The issue:**
I believe `_.reduce` should return lodash collection wrapper in case the collection is wrapped in lodash `_(collection).reduce`, but it returns the result instead. This behavior can be seen with other  functions (i.e. `_.transform` or `_.map`)

**Here is a reproduction:**
https://jsfiddle.net/AlesMenzel/n8nopvh0/17/

**Comment by jdalton** [comment]
Hi @alesmenzelsocialbakers!

By default Lodash uses implicit chaining. Since `reduce` is a reduction it will implicitly end the chain. You can opt in to explicit chaining though with `_(collection).chain().reduce
