### ISSUE TITLE
`fp/update` doesn't copy Symbol props in IE

### ISSUE THREAD

**Issue by jeron-diovis** [lodash/lodash#3661]
```js
import "es6-symbol/implement"
import update from "lodash/fp/update"

const sym = Symbol("foo")
const o = { [sym]: "symbol value" }
const o2 = update("a", x => x + 1, o)
alert(o2[sym])
```

Being built with babel/webpack, this script in IE 11 it outputs `undefined`. In modern browsers it is `symbol value`.

**Comment by jdalton** [comment]
Hi @jeron-diovis!

That looks like a shim problem and not a Lodash problem.
