### ISSUE TITLE
[FP] defaultTo doesn't work like explained

### ISSUE THREAD

**Issue by dietergeerts** [lodash/lodash#3662]
The fp docs state that the value is always last, so we can configure the function and then use it with the value, so when doing the following with defaultTo:

```
const test = _flow(_defaultTo(something));
```

it doesn't work. When executing the flow, defaultTo gives back a wrapper instead. So can't this be used FP like?

**Comment by jdalton** [comment]
Hi @dietergeerts!

I can't repro with
```js
_=require('lodash/fp')
_.flow(_.defaultTo(3))(null) // 3
```

**Comment by dietergeerts** [comment]
Nope, it's not working completely:

```
const test = _flow(
    _defaultTo({'A': 'A'}), 
    _merge({'B': 'B'})
);

console.log(test());          // {B: 'B', placeholder: {}}
console.log(test(undefined)); // {B: 'B', A: 'A'}
console.log(test(null));      // {B: 'B', A: 'A'}

const test = _flow(
    _defaultTo({'A': 'A'}), 
    _merge.convert({immutable: false})({'B': 'B'})
);

console.log(test());          // {B: 'B', placeholder: {}}
console.log(test(undefined)); // {B: 'B', placeholder: {}, A: 'A'}
console.log(test(null));      // {B: 'B', placeholder: {}, A: 'A'}
```
My use case is the second where I don't give the argument, as it's optional. 
This function is to be used to create an object to be used in forms, where we use 2-way binding, therefore I need the immutable to false as I introduce getters/setters for the properties that depend on each other, so if one changes in the form, the rest updates. The argument is optional as it can be for creation or editing of an object. It's strange that the placeholder is being left behind.

**Comment by dietergeerts** [comment]
It seems that `_flow` needs to have an actual argument to be able to execute in most cases, even if it's 'undefined'. Using the following does work now:

```
const test = obj => _flow(
    _defaultTo({'A': 'A'}), 
    _merge.convert({immutable: false})({'B': 'B'})
)(obj);
```

I just don't understand why this is needed?

**Comment by jdalton** [comment]
@dietergeerts  The fp method is curried and won't complete until it receives its expected number of arguments.

**Comment by dietergeerts** [comment]
True, but wrapping it, and then executing that wrapper without any argument does work, why? Because the wrapper make the argument explicitly undefined?

**Comment by jdalton** [comment]
Yes.
