### ISSUE TITLE
passing .bind argument through debounce throwing type error

### ISSUE THREAD

**Issue by dkebler** [lodash/lodash#3664]
@jdalton  no one took a shot at my stack question.  Can you take a quick look.  I'm Having trouble binding an argument via debounce without getting a type error even though I confirmed passed is a function.  

https://stackoverflow.com/questions/48977714/passing-bound-argument-through-debounce-to-wrapped-function.

```
[INTERRUPT-ERROR] TypeError: Expected a function
    at Function.debounce (/opt/uci/uci-examples/node_modules/lodash.debounce/index.js:144:11)
    at Gpio.emit (events.js:160:13)
```

```
    const pinDebounce = function (processor, wait, options, packet) {
      console.log(processor,wait,options,packet)
      return debounce.bind(processor.bind(this,packet),wait, options)
    }

    console.log(`starting interrupt on pin ${this.pin} with debounce wait/max:${this.wait},${this.maxwait} (0=off)`)
    let cb = {}

    if (this.wait===0) cb = this.interruptProcess.bind(this,this.packet)
    else cb = pinDebounce(this.interruptProcess,this.wait,{ 'maxWait': this.maxwait },this.packet)
    this.interrupt.on('interrupt',cb)
    // rock n roll!!, start the pigpio interrupt
    console.log('edge=',this.edge)
    if(!this.mock) this.interrupt.enableInterrupt(this.edge)
```

**Comment by jdalton** [comment]
Hi @dkebler!

Have you confirmed that `this.interruptProcess` is always a function?
I'd also start by making the default `cb` value a noop instead of an object.

**Comment by dkebler** [comment]
yes both` this.interruptProcess` and debounced are functions (see console output).  
The cb I added later but starting with noop made no difference.
latest version below, with console output showing both are functions.

So either how I did the bindings somehow corrupted the function(s) or there is some bug?

I also stringified `interruptProcess` to make sure it was the expected code and it is.

as I said `this.wait=0`  the functioned is not debounced and the listener works fine with no errors only when wrapped in debounce.

```
ready
starting interrupt on pin 24 with debounce wait/max:250,1000 (0=off)
[Function: interruptProcess] 250 { maxWait: 1000 } { pin: 24, cmd: 'interrupt', count: 0 }
[Function: bound debounce]
TypeError: Expected a function
    at Function.debounce (/opt/uci/uci-interrupt/node_modules/lodash.debounce/index.js:144:11)
    at Gpio.emit (events.js:160:13)
    at Gpio.<anonymous> (/opt/uci/uci-interrupt/node_modules/pigpio/pigpio.js:133:10)
```
```
    const pinDebounce = function (processor, wait, options, packet) {
      console.log(processor,wait,options,packet)
      return debounce.bind(processor.bind(this,packet),wait, options)
    }

    console.log(`starting interrupt on pin ${this.pin_num} with debounce wait/max:${this.wait},${this.maxwait} (0=off)`)
    let cb = () => {}
    if (this.wait===0) cb = this.interruptProcess.bind(this,this.packet)
    else cb = pinDebounce(this.interruptProcess,this.wait,{ 'maxWait': this.maxwait },this.packet)
    console.log(cb)
    this.pin.on('interrupt',cb)
```

for grins I dropped the binding using this
` else cb = debounce(this.interruptProcess,this.wait,{ 'maxWait': this.maxwait })`
when I run it the console shows
`{ [Function: debounced] cancel: [Function: cancel], flush: [Function: flush] }` and the error goes away....so does the binding I need to my callback function :-(.

my theory is the bound debounce is not the same functionally as not bound so the listener callback is unhappy???

**Comment by dkebler** [comment]
If  you have no other thoughts then I will make up a little repo with just this binding scenario and a simple listener/emitter so you might track it down.

**Comment by dkebler** [comment]
I tried Sindre's debounce and the error message was a bit more informative.
`TypeError: Expected the first argument to be a function, got `object`
    at Function.require.module.exports (/opt/uci/uci-interrupt/node_modules/debounce-fn/index.js:6:9)`

So apparently binding my function before passing it to yours somehow flags it as not a function.  Maybe there is no real error other than your code testing for a function and deciding it wasn't when it was throwing the error without actually trying it.

**Comment by jdalton** [comment]
> Do bound functions fail certain type checking for function?

They shouldn't.

**Comment by dkebler** [comment]
are you using your own isFunction?   maybe it doesn't properly identify bound functions as functions
https://github.com/lodash/lodash/blob/3.0.9-npm-packages/lodash.isfunction/index.js
I'm not very saavy on this but bound functions have no prototype property?
https://stackoverflow.com/questions/35686850/determine-if-a-javascript-function-is-a-bound-function
Does your type check for function make use of prototype property?

**Comment by dkebler** [comment]
duh...I forgot to include the context as the first argument to bind even if null.
`return debounce.bind(processor.bind(this,packet),wait, options)`
should be either
`return debounce.bind(null, processor.bind(this,packet),wait, options)`
or
`return debounce.bind(this, processor.bind(this,packet),wait, options)`

I can't get the debounce to fire now but at least the type error has gone away when I use these.
...nevermind :-1:
