### ISSUE TITLE
Object to string request.

### ISSUE THREAD

**Issue by darklightblue** [lodash/lodash#3665]
Hi, I wasn't able to find this in the docs but I think it would be very helpful to have a function that converts this object:

```
{
   foo: 'bar',
   lazy: 'dog',
}
```

into:
`foo=bar,lazy=dog`.

The parameters is the object and a separator (Example above is the comma).

This is will be helpful when doing a url parameters like `foo=bar&lazy=dog` and for the request headers like: 

```
const obj = {
    token, // abc
    secret' // def
};

const str = _.fnName(obj, ','); // this will return 'token=abc,secret=def'
const authHeader = `Oauth ${str}`;
```
Instead of hardcoding it:  

```
const authHeader = `Oauth token=${token},secret=${secret}`
```

What do you guys think?

**Comment by jdalton** [comment]
Hi @darklightblue!

That looks more fitting for a URL library or maybe a WHATWG URL shim.
