### ISSUE TITLE
Floating point accuracy is lost

### ISSUE THREAD

**Issue by xyy94813** [lodash/lodash#3666]
https://github.com/lodash/lodash/blob/c1f805f4972843b675056b2786f1165f7db81737/multiply.js#L16

```javascript
_.multiply(8.7, 100) === 870 // false
```
is it a bug?

same thing in `add` function

```javascript
_.add(0.1, 0.2) === 0.3  // false
```

**Comment by jdalton** [comment]
```js
0.1 + 0.2
// 0.30000000000000004
(0.1 + 0.2) === 0.3 // false
```

**Comment by xyy94813** [comment]
so, why not to handle this behavior? 

let `_.add(0.1, 0.2) === 0.3`, is it bad?

**Comment by StreetStrider** [comment]
@xyy94813, [How to deal with floating point number precision in JavaScript?](https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript)
