### ISSUE TITLE
[Improvement] unescape() method does not covert &#039; to ' character

### ISSUE THREAD

**Issue by SirAuron** [lodash/lodash#3667]
While using lodash unescape method, I've noticed that it does not covert `&#039;` into a ' character, but it explicitly requires the `&#39;` codification.

The `&#039;` codification, as specified [here](http://php.net/manual/en/function.htmlentities.php), is the result of PHP
```
// Output: Exam&#039;ple to pa&#039;rse
echo htmlentities( 'Exam\'ple to pa\'rse', ENT_COMPAT | ENT_HTML401 |  ENT_QUOTES);
```

I was wondering if other users have encountered my same problem and if there is a reason why only `&#39;` is being parsed to '.

**Comment by nuflowx** [comment]
You sure this is about lodash changing the value and not `htmlentities`?
Haven't coded in php in years, but my guess at first glance is it's being output by the php-method

**Comment by SirAuron** [comment]
@nuflowx Yes, exactly : PHP converts `'` to `&#039;`, but browsing through `htmlentities` options I've not found something to enable a different type of conversion.

Then, after having a look in lodash's unescape.js
```
/** Used to map HTML entities to characters. */
const htmlUnescapes = {
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&quot;': '"',
  '&#39;': "'"
}
```
and since putting `&#039;` into an `<input>` or `<textarea>` tag and then getting its value, it returns (correctly) a `'` character, I thought that `&#039;` should be treated as an alias for `&#39;`.

In all honesty, I didn't search for codification standards or why PHP follows this behavior.

In addition to this, another thing that leaves me a little bit puzzled is that I could not find among lodash issues someone having this problem.

Maybe I'm missing something, but even if I do, I don't know what it could be.

**Comment by jdalton** [comment]
Hi @SirAuron!

Please read [the docs](https://lodash.com/docs/#escape), especially the doc note.
