### ISSUE TITLE
 is it an extra judgment?

### ISSUE THREAD

**Issue by noshower** [lodash/lodash#3668]
`assignValue` function ：

      function assignValue(object, key, value) {

            var objValue = object[key];
            
            if (!(hasOwnProperty.call(object, key) && eq(objValue, value)) ||

                (value === undefined && !(key in object))) {

                baseAssignValue(object, key, value);

            }

           }

I think ` (value === undefined && !(key in object)` is an extra judgment. I really do not quite understand.

**Comment by jdalton** [comment]
Hi @noshower!

A property value can be `undefined` but the property may still exist on the object.
This checks to ensure the value is `undefined` and the property doesn't exist on the object.

**Comment by noshower** [comment]
Hi @jdalton 

I know what you mean. eg: `var obj = {}; var key = 'name';  var value = undefined; var objValue = obj[key]`;

Although objValue === value is true , the property doesn't exist on the obj. the `obj` needs to  assign a property.

so, I want to say:

on the one hand, if the property doesn't exist on the object, the `hasOwnProperty.call(object, key) `return `false` . on the other hand ,if ` key in object ` return ` false`,  `hasOwnProperty.call(object, key) ` must return `false` .

so,  `hasOwnProperty.call(object, key) ` == `false` or  ` key in object` == `false` can prove something that the property doesn't exist on the object.
