### ISSUE TITLE
_.assign and Object.assign  show inconsistent behavior

### ISSUE THREAD

**Issue by noshower** [lodash/lodash#3669]
Hi @jdalton 

I like `lodash.js`，and I am studying your source code.😝

today, I find some  difference，You see the following example：

    let obj = {};
    let a = Symbol("a");
    let b = Symbol.for("b");

    obj[a] = "localSymbol";
    obj[b] = "globalSymbol";
    console.log(_.assign({},obj)); //result:  {}
    console.log(Object.assign({},obj)); //result: { [Symbol(a)]: 'localSymbol', [Symbol(b)]: 'globalSymbol' }

Is there a problem?

**Comment by jdalton** [comment]
Hi @noshower!

No problem. Lodash `_.assign` doesn't iterate over symbol properties.
