### ISSUE TITLE
Docs for `omitBy` not correct

### ISSUE THREAD

**Issue by dietergeerts** [lodash/lodash#3670]
It says:

> The opposite of _.pickBy; this method creates an object composed of the own and inherited enumerable string keyed properties of object that predicate **doesn't return truthy for**. The predicate is invoked with two arguments: (value, key).

`doesn't return truthy for` should be changed to `does return truthy for`, OR the function is not working like explained, though I think it works correctly.

So should I update the docs and do a pull request?

**Comment by jdalton** [comment]
Hi @dietergeerts!

The doc entry and example states the correct intended behavior. If you're finding something else we can troubleshoot it.

**Comment by dietergeerts** [comment]
OMG, don't know what I had been drinking. Reading the doc didn't click the first time. I think it's because of the very long sentence and being English isn't my native language. Sorry for the issue....

**Comment by jdalton** [comment]
No worries @dietergeerts!
