### ISSUE TITLE
lodash-es/core.js as a target for browsers

### ISSUE THREAD

**Issue by markbrown4** [lodash/lodash#3672]
ES Modules in the browser are well on their way. Have you thought about how lodash can be exported for direct use in the browser?

```html
<script type="module">
import _ from 'https://unpkg.com/lodash-es'
// 640 requests

// I know! I'll just import the 1 function I need
import cloneDeep from 'https://unpkg.com/lodash-es/cloneDeep'
// 119 requests

// How about this?
import _ from 'https://unpkg.com/lodash-es/dist/core.js'
// 1 request
</script>

**Comment by StreetStrider** [comment]
@markbrown4 
> are well on their way

Throw me a thing to read.

**Comment by markbrown4** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Browser_compatibility

**Comment by jdalton** [comment]
Hi @markbrown4!

Lodash v5 will be all ESM.

**Comment by markbrown4** [comment]
And there will be the whole lodash / core as single module bundles?

**Comment by jdalton** [comment]
I'm leaving that up to bundlers for now as you can pick what you want to bundle.
