### ISSUE TITLE
_.curry with arity ignores length on last call

### ISSUE THREAD

**Issue by LandonSchropp** [lodash/lodash#3674]
I've run into an issue where the last call to a function that's been curried with an explicit arity that's less than `function.length` passes the remaining arguments to the provided function. It seems like any extra arguments are still passed to the underlying function, even if they should be discarded.

Here's a simplified version of my real-world scenario:

``` js
let mapValue = _.curry(_.get, 2);
let applesToOranges = mapValue({ gala: "mandarin", fuji: "blood", envy: "navel" });
```

When I call `applesToOranges` with a value contained in the object, and I include extra arguments, everything is fine:

``` js
applesToOranges("envy", "banana") // "navel"
```

However, because the third argument to `_.get` is the default value, if the provided value is not contained inside the object, the next argument is returned.

``` js
applesToOranges("yellow", "banana") // "banana"
```

Because I passed `2` as the arity, I would expect thing function to discard the extra argument and return `undefined`.

**Comment by jdalton** [comment]
Hi again @LandonSchropp!

The `arity` will give `curry` the know-how to end the curry but we still allow extra args in by design.
You can cap the args allowed to a function with [_.ary](https://lodash.com/docs#ary).

**Comment by LandonSchropp** [comment]
Hello. 😃 Thanks for the explanation!

**Comment by LandonSchropp** [comment]
That's good to know!
