### ISSUE TITLE
cloneDeep() memory leak?

### ISSUE THREAD

**Issue by jorisroling** [lodash/lodash#3676]
We used `cloneDeep()` on a (serve side) endpoint on a high traffic site for a while, and saw it loosing memory. We replaced all instances (2) of cloneDeep with the `JSON.parse(JSON.stringify())` trick, and after that the memory was stable again.

Is it possible that `cloneDeep()` has a memory leak?

Regards, J*

**Comment by jdalton** [comment]
`cloneDeep` is a very heavy method. Far more heavy than `JSON.parse` and `JSON.stringify`. If your data structure can support simpler/native methods like `JSON` then please use it.

**Comment by jorisroling** [comment]
heavy = leaking memory ?

**Comment by jdalton** [comment]
Heavy `===` doing much much more which can use considerably more CPU and has more places for things like a leak to creep in.

**Comment by jorisroling** [comment]
Understood and appreciated. 
(I would then mark this function 'experimental' , and to be used at own risk)

**Comment by jdalton** [comment]
Leaks can happen for a variety of reasons. I won't mark it experimental but for the next major release I'll heavily encourage other methods if at all possible. The `_.cloneDeep` method should never be the thing you reach for first.

**Comment by ematipico** [comment]
@jorisroling  I had the same problem. We switched to `JSON.parse` + `JSON.stringify` because our object was simple and didn't have any special cases (e.g. functions, `Symbol`, etc.)

**Comment by StreetStrider** [comment]
`cloneDeep` handles circular references, so this method require some registry to store already visited objects. However, I see no reason for it to fail to be garbage collected between calls. :thinking:

**Comment by jorisroling** [comment]
I understand the complexity of circular references, I don't understand the memory leak

**Comment by falsyvalues** [comment]
Without basic information like env setup and test case it will really hard to track this (if it exists at all).
