### ISSUE TITLE
Have an Option or a New Method that Removes First Instance of Items to Remove Using "_.without"

### ISSUE THREAD

**Issue by vbullinger** [lodash/lodash#3677]
I have a requirement to essentially call _.without, but just remove the first instance of each item, not all of them. I wrote it, but not in the context of lodash. I could make a PR, I suppose. My code looks like this:

```
function withoutOnce<T>(array: T[], itemToRemove: T): T[] {
  var index = array.findIndex(item => item === itemToRemove)
  if (index > -1) {
    array.splice(index, 1)
  }

  return [...array]
}
```
It's TypeScript and only accounts for one item, not an array of items to remove. Easily extensible.

**Comment by jdalton** [comment]
Hi @vbullinger!

I think this makes for a good one-off mixin for now.
