### ISSUE TITLE
[Suggestion] Improve lodash.difference

### ISSUE THREAD

**Issue by zaclummys** [lodash/lodash#3678]
If both arrays point to the same object, return a clean array before the comparison iteration.

They will always have the same values.

```js
import 'lodash' from 'lodash';

const arr = [1, 2, 3]

const result = lodash.difference(arr, arr)
```

**Comment by jdalton** [comment]
@zaclummys Good idea!

Would you be up for creating a PR?

**Comment by zaclummys** [comment]
Due to `...values`, even though all the arguments point to the same object:

- The rest arguments won't be won't be strictly equal to the first, because they are wrapped in a new array.

- To verify the equality between the rest arguments and the first, it would be
 necessary an iteration ala `Array#every`.

**Comment by jdalton** [comment]
Moved to #3679.
