### ISSUE TITLE
FP :: trimStart & trimEnd are not working.

### ISSUE THREAD

**Issue by GheorgheP** [lodash/lodash#3685]
Using the `trimStart` and `trimEnd` functions from `fp` will return wrong result.

```js
const trimEnd = require('lodash/fp/trimEnd');
const trimStart = require('lodash/fp/trimStart');

console.log( trimEnd('/', 'test//') ); // Expected `test`, but got `/` 
console.log( trimStart('//test') );  // Expected `test`, but got `/` 
```

**Comment by jdalton** [comment]
Hi @GheorgheP!

The [FP flavors](https://github.com/lodash/lodash/wiki/FP-Guide) of `trimStart` and `trimEnd` have an arity of 1. You may be able to customize this with [`convert`](https://github.com/lodash/lodash/wiki/FP-Guide#convert).
