### ISSUE TITLE
Curious about `sortedIndex`

### ISSUE THREAD

**Issue by tangweikun** [lodash/lodash#3686]
```js
_.sortedIndex([1, 2, 3, 3, 11, 12, 34, 2, 1, 11, 11], 5)
```
I get `4` when I run above code, is't the expected behavior?

**Comment by jdalton** [comment]
Sorted index works on sorted arrays. The array provided isn't sorted though the result of `4` is correct. The 4th index is where `5` would fit.

**Comment by tangweikun** [comment]
```js
_.sortedIndex([1, 2, 3, 3, 33, 2], 5)
```
As you have said, I should get `4` when I run the above code, but I get `6`, is't the right behavior? @jdalton

**Comment by jdalton** [comment]
Your array still isn't sorted and still is invalid usage.
