### ISSUE TITLE
Map  with cloneDeep()

### ISSUE THREAD

**Issue by guo88nihhao** [lodash/lodash#3687]
I was debugging a production issue, find this:

Say an object is used as a map, but never use get() or set(). Instead, set all values like: map[key_1]=value_1

When calling cloneDeep(), it will pass all type checks as a map, but forEach() won't be able to find anything, in the end, return an empty map.

![untitled](https://user-images.githubusercontent.com/6863891/37535075-09042b24-291d-11e8-90b3-2283055355a7.jpg)

The old version actually handled it well.

The commit is here:
[https://github.com/lodash/lodash/commit/67a3fb99ef173a8beda2b414effd1e3ffb2f4f01#diff-c98b19a4629c791fefaceea05556df52](url)

**Comment by jdalton** [comment]
Hi @guo88nihhao!

Then you're not really using a map for its intended purpose. Lodash doesn't support cloning bolted on properties to non-plain objects.
