### ISSUE TITLE
Feature request:  "get" with function which tries to access a nested property

### ISSUE THREAD

**Issue by kof** [lodash/lodash#3688]
Discovered recently this utility https://github.com/facebookincubator/idx. It seems like it would make a good addition to the get function and can be optional.

```js
idx(props, _ => _.user.friends[0].friends)
```

**Comment by jdalton** [comment]
Thanks for the heads up @kof!

I'm aware of this technique but would rather hold off and just use the [optional-chaining proposal](https://github.com/tc39/proposal-optional-chaining) once it advances  [a bit more](https://docs.google.com/presentation/d/1XDUB1gGRmD6cIUu2-bVXEA-ZrWUIfQfhWxFKALCAXOQ/edit#slide=id.p).
