### ISSUE TITLE
_.template: reversed <%- %> and <%= %>

### ISSUE THREAD

**Issue by axelpale** [lodash/lodash#3689]
[An issue in Webpack's ejs-loader](https://github.com/okonet/ejs-loader/issues/24) seems to be caused by unexpected behavior of Lodash's `_.template` function.

All resources I found on EJS templates associate `<%=` with escaped output and `<%-` with raw unescaped output. See [tj/ejs features](https://github.com/tj/ejs#features), [ejs.co docs](http://ejs.co/#docs) and their implementation: [Line 764 of ejs.js at GitHub](https://github.com/mde/ejs/blob/master/lib/ejs.js#L764).

In contrast, [Lodash's implementation](https://github.com/lodash/lodash/blob/f73b35bb497dd8948dcfa97a6924bf5ee860d467/template.js#L74) has things other way around, associating `<%-` with escaped output and `<%=` with raw output. Lodash might have taken a wrong step here. The [_.templateSettings docs](https://lodash.com/docs/4.17.5#templateSettings) refer the default settings to follow [Embedded Ruby](https://puppet.com/docs/puppet/5.3/lang_template_erb.html#tags) and [template literals of ES2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Description) but neither has a strong opinion on the matter. Embedded Ruby associates `<%-` with whitespace slurping and ES2015 uses `String.raw` prefix for unescaped template strings.

The default syntax should follow the convention. I believe the convention has been set by tj/ejs and ejs.co.

An earlier issue https://github.com/lodash/lodash/issues/2829 lightly touched the problem but the purpose was rather different and was quickly closed.

**Comment by jdalton** [comment]
Hi @axelpale!

Our implementation is by design. I'm not revising Lodash's template methods at this time and may not carry them into v5. I'd recommend using another template lib for functionality or if possible ES6 template strings.
