### ISSUE TITLE
.set nested object with dot in key 

### ISSUE THREAD

**Issue by newasmod** [lodash/lodash#3690]
Dudes, please help! i have object key properties with dots in name. I need to set nested properties, it doesnot work. set(object, 'a.b.c.d',12345) sets obj = {a: {b: {c:{d:12345}}}} ,
but i need obj = {'a.b.c.d' : 12345
anyway to do this?

**Comment by jdalton** [comment]
@newasmod Check out our [gitter chat](https://gitter.im/lodash/lodash) for help.
