### ISSUE TITLE
_.intersection - what should be type of param

### ISSUE THREAD

**Issue by krzywiecki** [lodash/lodash#3691]
As far as I understand type of parameter for `_.intersection` should be `array of arrays` not each array as parameter. IMO also would be easier to maintain with such parameter type. Please let me know what do you think guys.

**Comment by monkindey** [comment]
You mean 

```js
_.intersection([[2, 1],[2, 3]]);
```
instead of 

```js
_.intersection([2, 1], [2, 3]);
```
?

**Comment by jdalton** [comment]
Hi @krzywiecki!

The param type [is just array](https://lodash.com/docs/#difference).
