### ISSUE TITLE
[Question] How can I get a custom build including `baseDifference`?

### ISSUE THREAD

**Issue by zaclummys** [lodash/lodash#3694]

**Comment by jdalton** [comment]
Hi @zaclummys!

If you're looking to simplify your lodash bundle you should check out [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin).

**Comment by zaclummys** [comment]
@jdalton,

I'm benchmarking the PR https://github.com/lodash/lodash/pull/3679. But **lodash-cli** and **lodash-webpack-plugin** don't export internal methods like `baseDifference`, so I can't get a small and objective workspace without having to clone the entire repo.
