### ISSUE TITLE
Question: groupBy and orderBy on integer property

### ISSUE THREAD

**Issue by flip111** [lodash/lodash#3696]
Hello,

I have an array of objects i would like to groupBy a property a and then sortBy (descending) a property (or should it be the other way around) ? This works well for when using strings (a single character in this case). See https://jsfiddle.net/crswll/pb0t0xbs/43/ But when i add an integer property the sorting is no longer descending but ascending. See https://jsfiddle.net/pb0t0xbs/72/ Am i doing something wrong in my code or this not supported / a bug?

Thanks for the support.

P.S. it's remarkable to see that all issues are closed o_O

**Comment by jdalton** [comment]
Hi @flip111!

For these kinds of question you should visit our [gitter chat](https://gitter.im/lodash/lodash) for help.

**Comment by flip111** [comment]
Oh ok, i didn't know there was a gitter. Would you consider putting it into the readme so it's visible on github?

**Comment by jdalton** [comment]
It's [there](https://github.com/lodash/lodash/blame/master/README.md#L10) 😋

**Comment by flip111** [comment]
In case someone else stumbles upon this ... in the end it was possible to make this work with a `map`

```js
_.chain(this.characters)
        .groupBy(character => character.rating)
        .map((characters, rating) => ({ rating, characters }))
        .orderBy(group => Number(group.rating), ['desc'])
        .value()
```

https://jsfiddle.net/crswll/pb0t0xbs/106/
