### ISSUE TITLE
Request: missing bower builds for lodash

### ISSUE THREAD

**Issue by rbatllet** [lodash/lodash#3697]
I would appreciate to have the bower version of lodash as it has been generated up to now.

The 4.17.6 and 4.17.7 versions for Bower are mysteriously missing.

**Comment by jdalton** [comment]
Bower is EOL. Lodash doesn't explicitly support it anymore though you can get versions using their github#tag syntax.

**Comment by rbatllet** [comment]
Thanks for leaving us in the lurch without notice!

**Comment by jdalton** [comment]
@rbatllet 
Bower has been soft EOL'd of a couple years now and Lodash pulled explicit support with the v4 release in 2016. While we don't explicitly support it as I mentioned you can still reference versions of Lodash through Bowsers support of `repo/name#tag` syntax for dependencies.
