### ISSUE TITLE
no documentation for findFrom(), findIndexFrom(), etc.

### ISSUE THREAD

**Issue by liz-mars** [lodash/lodash#3699]
If I'm wrong, please point me at it :)

**Comment by jdalton** [comment]
Hi @liz-mars!

Those are FP variants of Lodash methods. You can read more about there in our [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide).

**Comment by liz-mars** [comment]
Hi @jdalton ! While the FP guide mentions findFrom in three places, none of these explain what it does. In fact, it occurs only in lists of functions present in lodash/fp. You may want to dilate on what these functions do, as generally, the standard (non-FP) lodash manual is the canonical documentation, and  (reasonably) omits these, because they're FP-only. Yet there is no concomitant FP documentation to pick up the load. 

While I understand the challenges of maintaining two variants of the same API, this is precisely the sort of thing that tends to get me eyeing Ramda. :) Fortunately the rest of lodash is so sensible I don't get those feelings much. <3. Please reopen this ticket and improve your documentation. I would submit a PR but I can't, because I don't know what these functions do -- hence, my original ticket ;D

**Comment by jdalton** [comment]
The [find](https://lodash.com/docs/#find) and [findIndex](https://lodash.com/docs/#findIndex) methods accept an option `fromIndex` parameter. Since the FP style doesn't support optional parameters these variants are exposed as their own methods.

**Comment by sherodtaylor** [comment]
@jabclab it still doesn't show what the arguments are. is the optional argument the optional return in `const shouldNotBeUndefined = _.find({}, 'someArr', [])`
