### ISSUE TITLE
_.defaultsDeep and arrays with different lengths

### ISSUE THREAD

**Issue by mukundgoel** [lodash/lodash#3702]
Hi Lodash team!

I had a question on how _.defaultsDeep works using arrays with different lengths.

Lodash version - 4.17.5 (latest)

For example

------------------------------------------------------------------------------------------

**code snippet 1:**
`_.defaultsDeep({
    sources: ["a"],
    test: {
        abcd: ["abc"]
    }
}, {
    sources: ["a", "b"],
    test: {
        abcd: ["abc", "defa"]
    }
});`

outputs `{sources: ["a", "b"], test: { abcd: ["abc", "defa"] } }`

note: here both source and default array had the **different** lengths

------------------------------------------------------------------------------------------

**code snippet 2:**
`_.defaultsDeep({sources: ["a"], test: { abcd: ["abc", "cde"] } }, {sources: ["b"], test: { abcd: ["abc", "defa"] } });`

outputs `{sources: ["a"], test: { abcd: ["abc", "cde"] } }`

note: here both source and default array had the **same** length

------------------------------------------------------------------------------------------

The observation is if both the arrays are not of the same length, lodash is overriding with the defaults, but if arrays are of the same length, the defaults are not being assigned.

For code snippet 1, the expected output was `{sources: ["a"], test: { abcd: ["abc"] } }``.

Thanks for any help!

**Comment by jdalton** [comment]
Hi @mukundgoel !

With deep `defaults` it's applying `defaults` logic to nested values. In the case of an array if the indexed value is `undefined` then it replaces it with the source value.

**Comment by mukundgoel** [comment]
ok @jdalton but why would the length of the array matter? Is that method traversing through all the array index in source and comparing it with default?

**Comment by jdalton** [comment]
It's a side effect of the fact that the length of an array affects what indexed values are available.
