### ISSUE TITLE
unset array items without leaving a null value behind

### ISSUE THREAD

**Issue by SachaG** [lodash/lodash#3703]
I needed to unset an array item based on a path, but without leaving behind a `null` value. This is what I came up with:

```
_.mixin({
  unsetCompact: (object, path) => {
      const parentPath = path.slice(0,path.lastIndexOf('.'))
      _.unset(object, path); 
      _.update(object, parentPath, _.compact);
  }
});
```

As you can see, I'm unsetting the array item, and then compacting the array. 

I don't know if that's the best way, but I couldn't really find any documentation about this use case. So I thought I'd share this here just in case?

**Comment by jdalton** [comment]
Hi @SachaG!

You might try using [Array#splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)
```
array.splice(indexToRemove, 1)
```

**Comment by SachaG** [comment]
Sorry, I guess I should've given more details. 

Here's a sample array: 

```
x = {a: {b: [[5,6,7,8, null], [1,2,3,4], [10, undefined, 11],]}};
```

Where I want to remove `2`:

```
_.unsetCompact(x, 'a.b.1.1');
```

Since I'm dealing with complex nested object I wanted to be able to use `unset`'s path syntax. 

See example here: https://runkit.com/sachag/5ab4d0a190b38400135fe653
