### ISSUE TITLE
memoize cache requires clear() method; is this intended or a mistake?

### ISSUE THREAD

**Issue by cspotcode** [lodash/lodash#3705]
Documentation for the `cache` of a memoized function says that the cache must implement a `clear()` method.  ECMAScript `WeakMaps` no longer have that method, so they technically can't be used as a memoize cache.  Also, the lodash source code doesn't call `clear()` anywhere.  Is this requirement intentional, or an oversight in the documentation?

If lodash has no intention of requiring a `clear()` method in the future, the requirement should be removed from the docs.  Also, I can remove the requirement from [@types/lodash](npm.im/@types/lodash).

### References:

https://lodash.com/docs/4.17.5#memoize
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap/clear
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/common/function.d.ts#L697-L699
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/common/common.d.ts#L154-L157

**Comment by jdalton** [comment]
Hi @cspotcode!

It's general guidance. The `clear` method is not required.

**Comment by edmundo096** [comment]
It would be nice if a parenthesis note could be added on memoize docs some time.
