### ISSUE TITLE
Packaging tests

### ISSUE THREAD

**Issue by ferranpujolcamins** [lodash/lodash#3706]
Hi, I contribute to [Mixxx](https://www.mixxx.org/), an open-source Dj software. We ship a custom build of lodash so our users can use it in their midi controller scripts. Our midi controller scripting engine is based on QtScript, which in turn is based on ECMAScript.

Currently our custom build just includes the assign function. We now want to ship a complete lodash build, however we would like to test lodash in our environment.

It's super easy for me to generate a build with lodash-cli. Is there a way to package test/test.js with its dependencies in a similar way? Can the tests even run outside a browser or node?

**Comment by jdalton** [comment]
Hi @ferranpujolcamins!

Awesome to see Lodash used in another JS engine!
Our [test/test.js](https://github.com/lodash/lodash/blob/4.17.5/test/test.js) will attempt to load [`qunit-extras`](https://github.com/jdalton/qunit-extras) and `qunit`. Then it's just up to modifying test.js to do any environment specific juggles.
