### ISSUE TITLE
Any webpack plugin can automatically precompile templates?

### ISSUE THREAD

**Issue by Folyd** [lodash/lodash#3707]
I know there is an awesome way to precompile templates by [custom build](https://lodash.com/custom-builds).

> Use the template command to pass the file path pattern used to match template files to precompile.
> **Note**: Precompiled templates are assigned to the` _.templates` object.
```
lodash template="./*.jst"
```

Well, the **lodash-cli** is a manual thing,  not efficient. There is any webpack plugin can achieve an automation workflow to precompile the lodash templates? 

I know there is a lodash-webpack-plugin, but it seems like it no supports this feature?

**Comment by jdalton** [comment]
Hi @Folyd!

I'm not aware of one, but I haven't really dug into it. What `lodash-cli` doesn't isn't hard so I suspect there are other ways to do it. I know there used to be grunt plugins to do it, which means those could likely have been converted to webpack plugins.
