### ISSUE TITLE
Deprecated 'with statement' in the lodash precompiled template files

### ISSUE THREAD

**Issue by Folyd** [lodash/lodash#3709]
As we know [**with** statement is deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with). But there still exists `with statement` in the precompiled template files.

## How to reproduce
`$ lodash template="./test.html" -d -o templates.js`

#### test.html
```html
<div>Test: lodash precompile template file.</div>
```

#### templates.js
```js
...
  templates['test'] =   function(obj) {
    obj || (obj = {});
    var __t, __p = '';
    with (obj) {
    __p += '<div>Test: lodash precompile template file.</div>';

    }
    return __p
  };
...
```

**Comment by jdalton** [comment]
Hi @Folyd!

I'm not removing `with` from the template method as it's the secret sauce that makes it just work. You can remove it yourself though by [providing an `options.variable` value](http://lodash.com/docs#template).

**Comment by Folyd** [comment]
@jdalton Thanks for replying. I see. But here is an error caused by `with statement` when I build my js code:
```
ERROR in ./src/js/script/templates.js
Module build failed: SyntaxError: 'with' in strict mode (36:4)

  34 |     obj || (obj = {});
  35 |     var __t, __p = '';
> 36 |     with (obj) {
     |     ^
  37 |     __p += '<div>Test: lodash precompile template file.</div>';
  38 | 
  39 |     }
```

I'm sorry for I don't know how to fix this. 😢

**Comment by Folyd** [comment]
Another problem is there is no way to specify `options.variable` value when precompiling the templates file. Did I miss something?

**Comment by jdalton** [comment]
With `lodash-cli` you can use the [`lodash settings=...` option](https://lodash.com/custom-builds) to configure pre-compiled templates.

**Comment by Folyd** [comment]
Thanks. Work like a charm! 
Here is my solution in convenient for other people.

**test.html**
```html
<div>Hello <%- data.name %>! Test: lodash precompile template file.</div>
```

**Precompile your lodash templates**
```
lodash settings="{variable:'data'}"  template="./src/templates/*.html" -d -o src/js/script/templates.js
```
**src/js/script/yourcode.js**
```js
require('./templates.js');
import _ from "lodash";

 console.log(_.templates['test']({name:'Jack'}));
```

**output**
```
Hello Jack. Test: lodash precompile template file.
```
