### ISSUE TITLE
Why is lodash isEqual so much slower than underscore isEqual

### ISSUE THREAD

**Issue by AjaxSolutions** [lodash/lodash#3710]
https://jsperf.com/lo-dash-vs-underscore-vs-json-stringify-isequal/2

Why there is a big difference on Mac/Chrome?

**Comment by jdalton** [comment]
Hi @AjaxSolutions!

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.2.1/lodash.min.js"></script>
```
Those are super old versions to compare against. However, the gist seems reasonable. Lodash supports comparing more types of values and while we do our best to optimize you'll always be better off with a tailored solution for your given data types.
