### ISSUE TITLE
forEach can exit loop? 😕

### ISSUE THREAD

**Issue by jimmywarting** [lodash/lodash#3711]
It feels like you are trying to mimic some of the core vanilla js functions like Array#forEach

You have renamed `.each` to `.forEach` so... and done so many other simular vanilla js apis

> https://lodash.com/docs/4.17.5#forEach
> 
> Iteratee functions may exit iteration early by explicitly returning false.

I feel like `_.some()` should be used instead if you intend to exit the loop early.

unlike Array#forEach it can never exit the loop, so this was somewhat unexpected to me

Now with more newer syntax as shorthanded array function being used more often you might not explicit mean to return something that could potentially return a `false` value and exit the loop

```js
// Dose something that might or might not return a false value
function doSomething(item) {
  return false
}

_.forEach(array, item => doSomething(item))
_.forEach(array, item => { doSomething(item) }) // what you actually meant to do...
```

---

I'm one of the guys that try to convert lodash function into vanilla js function whenever i can or see something that don't necessary need the hole lodash library. so Array#forEach and lodash#forEach is not one way korrelation in that way, you are doing more then what Array#forEach are able to do.

I know it's hard to make breaking changes, So I don't really expect any changes in the api. Maybe you will reconsider... how knows? 
But maybe you will make some changes in the documentation at least and say that it's better to use `_.some()` to break the loop?

**Comment by jdalton** [comment]
Hi @jimmywarting!

Yep, `_.forEach`, `_.forIn`, `_.forOwn`, `_.forEachRight`, `_.forInRight`, and `_.forOwnRight` can all exit their iteration early.
