### ISSUE TITLE
Why toPairs does not guarantee iteration order

### ISSUE THREAD

**Issue by abdoolly** [lodash/lodash#3712]
I know it is said in the documentation that (iteration order is not guaranteed) but , I wanna know is there any workaround for that in lodash ? that I can guarantee with it to make toPairs output with the same order give.

Thanks

**Comment by jdalton** [comment]
Hi @abdoolly!

The guaranteed bit is because some older JavaScript engines didn't guarantee iteration order. Now with ES6 though own property order is specified.

**Comment by abdoolly** [comment]
Thanks @jdalton
