### ISSUE TITLE
Add a version of `_.matches` that allows partial matches

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash#3713]
`_.matches` requires all properties to match. Often times a partial match is sufficient. Since there are other methods in lodash that follow that kind of pattern, it seems like there is a missing `matchesSome` method in lodash. I've created a quick working draft here to clearly document what I'm describing (in case there's something already in lodash I'm missing).

https://runkit.com/daedalus28/futil-matchessome-draft

**Comment by jdalton** [comment]
Hi @daedalus28!

I dig your use of function composition, combining util libs, and runkit!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) for sure.

**Comment by daedalus28** [comment]
Thanks for the kind words, @jdalton!

I just shipped [`futil-js`](https://www.npmjs.com/package/futil-js) version 1.44.0 with `matchesSome`, so anyone stumbling on this from the internet can use that in the meantime.
