### ISSUE TITLE
Timestamps on files in lodash-es in 1969

### ISSUE THREAD

**Issue by thomaswelton** [lodash/lodash#3714]
Originally posted here as it was a suspected issue in yarn
https://github.com/yarnpkg/yarn/issues/5577

The timestamps of the files in the lodash-es archive in the nam registry are set to 1969
https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.7.tgz

This causes issues when trying to create a zip of the node_modules with the error `ZIP does not support timestamps before 1980`

**Comment by jdalton** [comment]
This sounds familiar to what `acorn` was seeing https://github.com/acornjs/acorn/issues/680 related to https://github.com/npm/npm/issues/19968 and patched https://github.com/npm/npm/commit/58d2aa58d5f9c4db49f57a5f33952b3106778669. It looks like the solution is to republish.

**Comment by jdalton** [comment]
I republished as [lodash-es@4.17.8](https://github.com/lodash/lodash/tree/4.17.8-es) with [`npm@5.8.0`](https://github.com/npm/npm/releases/tag/v5.8.0) which should resolve the issue.

**Comment by thomaswelton** [comment]
Thank you, I can confirm this is resolved in the latest version.
