### ISSUE TITLE
_.size() return value of length property instead of Object size 

### ISSUE THREAD

**Issue by Mahammad8564** [lodash/lodash#3716]
example:-

_.size({a:5, length:50, b:10}) => 50 //should be 3

**Comment by Xotic750** [comment]
`_.keys({a:5, length:50, b:10}).length`

**Comment by Mahammad8564** [comment]
why should i use _.keys({a:5, length:50, b:10}).length
INSTEAD OF 
Object.keys({a:5, length:50, b:10}).length

or how can I get the direct length of an object?

**Comment by jdalton** [comment]
Use `Object.keys`
