### ISSUE TITLE
FP documentation is difficult to understand compared to normal documentation

### ISSUE THREAD

**Issue by mimshwright** [lodash/lodash#3717]
When I work with Lodash FP I typically need to have two sets of documentation open on my screen. The regular docs and the FP guide. Even then, it's not always clear exactly how to correctly use the function. I often search the page for the function I am looking for to see if it's mentioned in arity count or special cases. 

I would like to request a separate set of documentation for the FP functions that shows a complete listing of the functions and how to use them. 😬

**Comment by jdalton** [comment]
Hi @mimshwright!

You might dig https://github.com/jfmengels/lodash-fp-docs.
