### ISSUE TITLE
Inconsistent sort order for NaN values across browsers

### ISSUE THREAD

**Issue by noppa** [lodash/lodash#3718]
**Lodash version:** 4.17.5
**Minimal reproducible example:**
```javascript
_.sortBy([1, 2, 3], function(x){ return NaN; });
```
**Result in IE11 and Edge (v 41):**
```javascript
[1, 2, 3]
```
**Result in Chrome (v 65) and FF (dev edition, v 60):**
```javascript
[3, 2, 1]
```

(all tests were run in lodash.com/docs on Windows 10)

I’m not sure what the intended behavior here is or if the sort order for `NaN`s is even “guaranteed”.
#1482 seems to indicate that `[3, 2, 1]` would be expected here.

**Comment by jdalton** [comment]
Thanks @noppa!

This looks like a legit bug 🙌

**Comment by jdalton** [comment]
Actually this is a bug in JS engines.

Chrome, Safari
```js
[1,2,3].sort(() => 1)
// [3, 2, 1]
```
IE, Edge, Firefox
```js
[1,2,3].sort(() => 1)
// [1, 2, 3]
```

I'll report back with engine issue references.

**Comment by noppa** [comment]
The `comparefn` that `Array.prototype.sort` eventually gets here does indeed violate the contract because the [compareAscending function that lodash uses returns `1`](https://github.com/lodash/lodash/blob/master/.internal/compareAscending.js#L31) for both  
`comparefn(a, b)` and `comparefn(b, a)` when both `a` and `b` are `NaN`.

Does that have to mean that `NaN` values can't be consistently sorted using `_.sortBy`, though? As far as I can see, this could be quite easily fixed with

```diff
diff --git a/.internal/compareAscending.js b/.internal/compareAscending.js
index 47037e0bb..21d5dfded 100644
--- a/.internal/compareAscending.js
+++ b/.internal/compareAscending.js
@@ -20,6 +20,10 @@ function compareAscending(value, other) {
     const othIsReflexive = other === other
     const othIsSymbol = isSymbol(other)
 
+    if (!valIsReflexive && !othIsReflexive) {
+      return 0
+    }
+
     const val = typeof value == 'string'
       ? value.localeCompare(other)
       : -other
```
https://github.com/lodash/lodash/compare/master...noppa:master
