### ISSUE TITLE
Avoid creating sparse arrays in v8

### ISSUE THREAD

**Issue by blowery** [lodash/lodash#3719]
According to [an article last year](https://v8project.blogspot.com/2017/09/elements-kinds-in-v8.html), `new Array( length > 0 )` and `Array.prototype.map` create sparse arrays in v8, which causes deopts when working with common array types. It would be interesting to investigate changing out all of the `Array(length)` creations to simply `[]` to avoid this deopt. Having lodash's `map` produce a dense array might give it a leg up on native `map` in some cases.

Also curious if other engines deopt in a similar way.

**Comment by jdalton** [comment]
Hi @blowery!

I saw that post but don't give it too much thought. Preallocation of array length has worked well for years and years. I suspect they'll not muck too much with it. If they de-opt and hit perf critical issues (with Lodash) we carry enough ecosystem weight for them to revert or rethink their optimization heuristics.

**Comment by blowery** [comment]
Hi @jdalton! Yeah, I suspected you'd either already poked at this or had an opinion. :) It was quite counter-intuitive that spec'ing an length would force an array to be treated as sparse, which is why I thought it might warrant investigation. But it would be quite engine specific and validating it would be challenging...

Thanks for chiming in!
