### ISSUE TITLE
lodash.pick behavior differs from lodash/pick

### ISSUE THREAD

**Issue by knksmith57** [lodash/lodash#3720]
I'm sure this is the result of something dumb I've done.

It was my understanding that `lodash.pick` behaved the same as `lodash/pick`; I'm observing otherwise on `4.4.0`:
```js
// index.js
const _pick = require("lodash/pick")
const pick = require("lodash.pick")

const ORIGINAL = {
  one: 1,
  and: {
    two: "2",
    three: 3,
    another: {
      four: 4
    }
  }
}

const PATHS = ["one", "and.three", "and.another.four"]

console.log(_pick(ORIGINAL, PATHS))
console.log(pick(ORIGINAL, PATHS))
```

Produces:
```sh
❯ node index.js
{ one: 1, and: { three: 3, another: { four: 4 } } }
{ one: 1 }
```

Repro ==> https://gist.github.com/knksmith57/a43ed55b52212e0974ae1cae69fa9b3c

Environment:
```
❯ node -v
v8.9.4

❯ npm -v
5.7.1

❯ npm ls lodash.pick lodash
/Users/kbsmith/Projects/scratch/lodash-pick-differences
├── lodash@4.17.5
└── lodash.pick@4.4.0
```

Please let me know if there's any additional info I can provide. Thanks!

**Comment by jdalton** [comment]
Hi @knksmith57!

Deep property path support was added after 4.4.0. 
Stick to the cherry-picked form `lodash/pick` and you'll be good to go.

**Comment by knksmith57** [comment]
excellent, thanks for the quick response and clarification!
