### ISSUE TITLE
Custom builds are too large

### ISSUE THREAD

**Issue by fabiospampinato** [lodash/lodash#3722]
Creating a custom build with the following command:

```
lodash -p include=wrap
```
produces a ~8.5k file, which seems excessively large to me.

As I understand it `lodash-cli` is going to get discontinued in v5 in favor of WebPack, that's fine, but you might want to check that WebPack is able to create smaller builds.

**Comment by jdalton** [comment]
Hi @fabiospampinato!

The `lodash-cli` was created before Babel or Webpack were things. For building today you might check out [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) combined with [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin). See [this great blog post](https://nolanlawson.com/2018/03/20/smaller-lodash-bundles-with-webpack-and-babel/) for more details.
