### ISSUE TITLE
Clone method documentation incorrect?

### ISSUE THREAD

**Issue by cameronperry** [lodash/lodash#3723]
Under clone:

"An empty object is returned for uncloneable values such as error objects, functions, DOM nodes, and WeakMaps."

Under cloneDeep

"This method is like _.clone except that it recursively clones value"

When I cloneDeep an object that references a function, it keeps the function reference. Am I misunderstanding something, or is the documentation incorrect and empty objects are not put in place of functions?

**Comment by jdalton** [comment]
Hi @cameronperry!

The note on uncloneables is for when you pass the uncloneable value in directly.
For example `clone(func)` or `cloneDeep(func)`.

**Comment by YuriGor** [comment]
It was surprising for me too. It will be good to describe this behavior in the docs explicitly.
