### ISSUE TITLE
Fast way to compare values

### ISSUE THREAD

**Issue by nomi-ramzan** [lodash/lodash#3727]
Hi I have this kind of data
```
var sample = [[null, 1], [null, 0], [null, 0], [null, 0], [null, null]]
var success = [0, 1]
var target = '[1]' || '1'
```
And my current solution is 
```
_(sample)
  .map(target)
  .difference(success)
  .value().length === 0;
```
Is there any more fast or efficient way to do that ?
Thank you

**Comment by falsyvalues** [comment]
Hi @nomi-ramzan!

For these kinds of question you should visit our [gitter chat](https://gitter.im/lodash/lodash) for help.
