### ISSUE TITLE
Question: why does fp/concat add to front of array?

### ISSUE THREAD

**Issue by timhwang21** [lodash/lodash#3728]
```javascript
import concat from 'lodash/fp/concat';

concat('new')([1,2,3]); 
// => ['new', 1, 2, 3];
```
Wondering why this is the case. My understanding is that `concat` / `append` type functions generally add to the tail of a list, while `cons` adds a head.

From a practical standpoint, is there any way to get tail-end concatenation besides using `fp/rearg`? Thanks!

**Comment by c-dante** [comment]
According to [FP-Guide](https://github.com/lodash/lodash/wiki/FP-Guide), concat has unchanged argument order.

Which personally, I agree with -- `concat([1, 2, 3])(4, 5, 6])` would be awkward if it flips, and saying `concat([5])` means "I'm concat-ing [blank] to [5]".

**Comment by timhwang21** [comment]
Thanks @c-dante , I agree it makes it more usable, but I find it much less intuitive :)
