### ISSUE TITLE
Maybe always TRUE

### ISSUE THREAD

**Issue by zbitname** [lodash/lodash#3730]
https://github.com/lodash/lodash/blob/97e9edc53d2cc55df7adf765a003c800c54a6bda/lodash.js#L4291
https://github.com/lodash/lodash/blob/master/.internal/baseUniq.js#L51

It's looks like bug...

**Comment by jdalton** [comment]
HI @zbitname!

The `computed === computed` check is for `NaN` values.

**Comment by zbitname** [comment]
Perhaps if you use a function called `isNaN`, instead of a simple comparison, less questions will be created, and the code will be better read and/or understood.
