### ISSUE TITLE
tslint gives trailing comma error

### ISSUE THREAD

**Issue by stansongman** [lodash/lodash#3731]
node_modules/@types/lodash/common/array.d.ts(1408,71): error TS1013: A rest parameter or binding pattern may not have a trailing comma.
node_modules/@types/lodash/common/array.d.ts(1447,71): error TS1013: A rest parameter or binding pattern may not have a trailing comma.

Lodash 5.6.0, tslint 5.9.1

Removing the trailing commas from those lines stops the linter from complaining.

**Comment by jdalton** [comment]
Hi @stansongman!

We don't lint for others.

**Comment by cancerberoSgx** [comment]
I don't think this is a ts lint error but typescript error, see https://github.com/Microsoft/TypeScript/pull/22262/files/0a32978779c11052600ba6e24461143ebb87a02f#diff-c3ed224e4daa84352f7f1abcd23e8cca

(merged 28 days ago)

In the conversation they say why  a comma after rest parameter is an error, I didn't get it though but I think you should reopen this issue and compile with latest but I think you should check these files with latest tsc

thanks!

**Comment by cancerberoSgx** [comment]
I'm sorry, I just realized that probably the project @types/lodash is not yours so ignore my previous comment and keep the good work - this project don't have a line of ts
