### ISSUE TITLE
has() not returning correct value

### ISSUE THREAD

**Issue by dcorb** [lodash/lodash#3732]
This is more a support request than actually bug report, because I can't replicate it from scratch. Maybe it's GraphQL/Apollo making something strange under the hood (__typename, Symbol(id), etc)

Using "lodash": "4.7"

As you can see `currentRoleInstance` is null, so why `has()` returns true for all these expressions (except the last)?

I tried different signatures, and also trying to strip-down the object using `parse(stringify())` in `person2` variable:

![image](https://user-images.githubusercontent.com/881333/38322242-c83df060-3831-11e8-92fb-12ae39acaebb.png)

Do you have any clue why `has()` misbehave here?

**Comment by jdalton** [comment]
Hi @dcorb!

The `has` method returns `true` if there is an own property on the object.
The property can have any value.

**Comment by dcorb** [comment]
Hi John-David! As quick as always :) Thank you for the reply.

I'm not sure if I follow you.

I understand if the path would be just `currentRoleInstance` (that exists and is null), but the path is `currentRoleInstance.roleID`, and `roleID` key does not even exist. So it must be looking in the prototype chain, or what other reason could be?

**Comment by jdalton** [comment]
The `has` method accepts two arguments. In some of your examples you are passing three.

**Comment by dcorb** [comment]
oops
Thanks!
I narrowed it down a bit more... These 2 signatures should behave the same way? 

![image](https://user-images.githubusercontent.com/881333/38324187-72f70118-3837-11e8-89df-f4c8ad4788c0.png)

I will have a break now and try later to replicate it again in isolation. Thanks!

**Comment by jdalton** [comment]
No, now you are specifying a single property named `"employmentInstances.0.currentRoleInstance"` and a child property of `"roleID"`.
