### ISSUE TITLE
Commit in master breaks sorting

### ISSUE THREAD

**Issue by ribizli** [lodash/lodash#3734]
see my comments in commit 47a6d538f5759fc5788f1bbb147caa7fde6b0a92

**Comment by ribizli** [comment]
I also would rather have a feature to customize sorting logic in some way, so one can sort strings by bytes or `localeCompare`. I have no idea how this can fit into the API however.

**Comment by ribizli** [comment]
Custom comparison could be maybe added in the `orders` parameter as a comparator function (additionally to `'asc'` and `'desc'`). Or the values `'localeAsc'` and `'localeDesc'` maybe?

**Comment by jdalton** [comment]
Thanks @ribizli!

It does make sorting different but that's not necessarily a bad thing. It is for a v5 major release so breaking changes are okay.

**Comment by ribizli** [comment]
You just missed my warning about the issue in the `compareAscending.js`. The sorting won't work with non-strings. See the comment in the linked commit.

**Comment by jdalton** [comment]
I didn't miss your warning. Your warning was just incorrect and I didn't feel like calling you out on it.
