### ISSUE TITLE
Default orders for orderBy when ordering by multiple iteratees.

### ISSUE THREAD

**Issue by Gusis93** [lodash/lodash#3735]
Unless I'm mistaken, the [current behaviour](https://github.com/lodash/lodash/blob/master/orderBy.js) of orderBy makes you set an order for each iteratees you are ordering by, there is no default option when you want the same order for all.

This makes you have to write:

` orderBy(arr, ['it1', 'it2', 'it3'], ['desc', 'desc', desc']);`

When you could just write:

` orderBy(arr, ['it1', 'it2', 'it3'], 'desc');`

And have this:

```
if (!Array.isArray(orders)) {
   orders = orders == null ? [] : [orders]
}
```

Be:

```
if (!Array.isArray(orders)) {
   orders = orders == null ? [] : [...Array(iteratees.length)].map(arrPos => orders);
}
```

**Comment by jdalton** [comment]
Hi @Gusis93!

You are correct. If you'd like to tweak it please feel free to submit a PR.
