### ISSUE TITLE
 [Feature Request] OrderBy locale option

### ISSUE THREAD

**Issue by ayZagen** [lodash/lodash#3739]
Localization should be implemented for ordering strings in other locales.

Here is the pen that showing it doesn't sort correctly. 
[https://codepen.io/trd3v3lop/pen/GxYVYw](https://codepen.io/trd3v3lop/pen/GxYVYw)

**Comment by jdalton** [comment]
Hi @ayZagen!

I'm open to a PR if you're up for it.
