### ISSUE TITLE
escapeRegExp doesn't match its doc example result

### ISSUE THREAD

**Issue by snikobonyadrad** [lodash/lodash#3740]
From the [docs][1]:
```
_.escapeRegExp('[lodash](https://lodash.com/)');
// => '\[lodash\]\(https://lodash\.com/\)'
```
Actual result from the doc's `repl`:
```
"\\[lodash\\]\\(https://lodash\\.com/\\)"
```

Am I doing something wrong? Also slashes `/` must be escaped to `\/` as well. Did I misunderstood this function?

[1]: https://lodash.com/docs/4.17.5#escapeRegExp

**Comment by jdalton** [comment]
Hi @snikobonyadrad!

The `\\`is the way of escaping `\` so depending on the REPL it will show as `\\` or `\`.

**Comment by snikobonyadrad** [comment]
Not sure if I understand it. Escaping the literal string `http://apple.com` to something that regex understands will make it `http\\:\\/\\/apple\\.com`. But `escapeRegExp` returns `http://apple\\.com`. Is this not what this function is supposed to do?

**Comment by snikobonyadrad** [comment]
Got it now. Thanks very much.
