### ISSUE TITLE
_.reverse() incorrect behavior some times

### ISSUE THREAD

**Issue by squidwardthetentacles** [lodash/lodash#3742]
lodash version: 4.17.5

<img width="328" alt="capture" src="https://user-images.githubusercontent.com/15376332/38463692-d9f0bece-3b32-11e8-8e6b-d65ec03ba987.PNG">

<img width="353" alt="captures" src="https://user-images.githubusercontent.com/15376332/38463696-027a6322-3b33-11e8-9c1c-3fe11b5690b1.PNG">

the parents(array) is not reversed sometimes.

**Comment by jdalton** [comment]
Hi @squidwardthetentacles!

I don't believe this is our problem.
However, if you find the issue is, then a PR would be appreciated.

**Comment by squidwardthetentacles** [comment]
Actually the lodash function is not reversing the array as it should. Sometimes it happens.

**Comment by jdalton** [comment]
Our code has no conditional reversing branches so I'm going to assume the error is elsewhere.
