### ISSUE TITLE
javascript

### ISSUE THREAD

**Issue by imoiseyev** [lodash/lodash#3743]
Роман, здравствуй. Меня зовут Иван - я ищу "Старшего JS разработчика" на проекты Компании ISS Art. Работа предполагается из офиса.
Рассматриваешь ли ты предложения по работе? От какой суммы?

Нам нужен JS разработчик. Увидел твой профиль на МоемКруге и обратил внимание на твои навыки: JavaScrip. 
Задачи: разработка и поддержка Front-end на крупных проектах, участие в выработке архитектурных решений на проектах, обучение коллег.

Если коротко, то: 
ЗП вилка от 60 т.руб - 150 т.руб 
английский - intermediate 
технологии - JS

Мы работаем с Западом: США, Канада, Германия, Швейцария, у нас все в белую и нас 100 + человек. Офисы в Омске и Красноярске. 
Подробнее о Компании смотри здесь

Ты работал с AngularJS, ReactJS или другим современным фреймворком? Расскажи подробнее о проектах.
Почта для связи: ivan_moiseyev@issart.com

**Comment by falsyvalues** [comment]
Hi @imoiseyev
I think this is a [place](https://jobs.github.com/) you are looking for.
