### ISSUE TITLE
Pick is broken

### ISSUE THREAD

**Issue by senyaak** [lodash/lodash#3744]
The pick method do not work with chained path 

Expected:
```js
    var object = { 'a': 1, 'b': '2', 'c': { d : 3 }};

    _.pick(object, ['a', 'c.d']);
    // => { 'a': 1, 'c': 3 }
```
Got:
```js
    var object = { 'a': 1, 'b': '2', 'c': { d : 3 }};

    _.pick(object, ['a', 'c.d']);
    // => { 'a': 1}
```
Funny is that this work on the lodash doc page :D

**Comment by telaoumatenyanis** [comment]
It works fine for me, works in lodash doc, and you can find a working bin here :
https://jsbin.com/lojegiquwu/edit?html,js,console,output

What is your lodash version ?

**Comment by falsyvalues** [comment]
Hi @senyaak 
Please inspect your version, building process and so on. You can go on [lodash.com/docs](https://lodash.com/docs/4.17.5) and try your self on dev tools, it works as expected.

**Comment by senyaak** [comment]
Tested it on npm package https://www.npmjs.com/package/lodash.pick
Test: https://runkit.com/embed/5l68o0r2upt4 
as you can see its wrong - perhaps npm get an old version?

**Comment by zappan** [comment]
Same issue here, using the modularized lodash.pick package, and it's broken, and it's an outdated version, 2 years old on the npm. 

Why are the modularized versions even kept, if they aren't being published with the updates?

**Comment by jdalton** [comment]
Hi @zappan!

That's correct. The individual modularized packaged were too much of a burden to continue to maintain (hundreds of them) and produced larger bundles than cherry-picking from `lodash-es` or `lodash` with tools like Webpack v4, `babel-plugin-lodash`, or `lodash-webpack-plugin`.

**Comment by zappan** [comment]
@jdalton how about officially deprecating them, and/or marking that somewhere in big bold letters, we are so used to use them from the past, that it would be nice for it to advertise somehow that they are no longer maintained. It's not clear at all from the docs website or anything.

Thanks for the feedback.
