### ISSUE TITLE
Lodash v5 approach to ESM.

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash#3745]
I'm labelling this `question` since we don't have a `discussion` tag _(no need to create one for this)_.

Since [`esm`](https://github.com/standard-things/esm) is stable, I want to start moving to Lodash v5.

The plan for Lodash v5 was always that it would be ESM but the execution of it wasn't clear until now.
With Lodash v5 taking a dependency on `esm` we can make an ESM entry point that imports all modules available to CJS. The individual cherry-pickable modules though would be ESM and would require folks to use a loader, like `esm`, a bundler, or the package.json "mode" option _(if and when that is available)_. Since the cherry-pickable modules will be ESM no additional work will be needed for bundlers like webpack, rollup, and parcel.

So this means folks using just CJS would get
```js
const _ = require("lodash")
```
but if they wanted cherry-picked forms they'd need to write ESM
```js
import { pick } from "lodash"
// or
import pick from "lodash/pick"
```
and use a bundler or [`esm`](https://github.com/standard-things/esm).

**Comment by rafde** [comment]
So there's no real change happening? I don't follow what the question is.
 
I think it's fine for the cherry-picking to go through bundlers. Not sure how else to do that sort of thing. That's how I have my webpack build doing builds with babel-plugin-lodash.

Is this approach going to take anything away from what is working now in Lodash 4?

**Comment by jdalton** [comment]
> So there's no real change happening? I don't follow what the question is.

There is no `question` I explained that in the first sentence :yum:

> I think it's fine for the cherry-picking to go through bundlers. Not sure how else to do that sort of thing. That's how I have my webpack build doing builds with babel-plugin-lodash.

Ya, I think this approach aligns with with that workflow.

> Is this approach going to take anything away from what is working now in Lodash 4?

Nope. Lodash v4 (and any other major version) is not affected by other major version bumps.

**Comment by jdalton** [comment]
> Will cherry picking still work if I use namespace imports? Webpack can follow namespace imports only if imported module is in ESM.

If weppack supports that now then it will continue to just work.
