### ISSUE TITLE
Confusion in `times.js`

### ISSUE THREAD

**Issue by H2rmone** [lodash/lodash#3746]
Hello,

I'm confused about the following code in `times.js`
```javascript
index = MAX_ARRAY_LENGTH
n -= MAX_ARRAY_LENGTH
while (++index < n) {
  iteratee(index)
}
```

Now, assuming the first param is between `MAX_ARRAY_LENGTH ` and `MAX_SAFE_INTEGER `. For better debugging, I change MAX_ARRAY_LENGTH to `5`. 

Then, I run this
```javascript
const MAX_ARRAY_LENGTH = 5

function times(n, iteratee) {
  // as before
}

let i = 0
const result = times(15, () => i++)
console.log(result) // [0, 1, 2, 3, 4]
console.log(i) // 9
```

What is expected in **my opinion**?

The `result` should be `[0, 1, 2, 3, 4]`.
The `iteratee` should be executed 15 times.
The variable `i` should be 15.

What is actually happening?
The result is `[0, 1, 2, 3, 4]` as expected.
The `iteratee` **only** executed 9 times.
The value of variable `i` finally becomes 9.

**Additional guess**
If I change the code on the top like this
```javascript
index = MAX_ARRAY_LENGTH
while (++index <= n) {
  iteratee(index)
}
```
This has met my expectations.😂😂😂

I‘ll be very grateful if someone can answer my question.😃

**Comment by jdalton** [comment]
That code doesn't match what I'm seeing in `times` source. If you have a bug that's fine file a clear report. I'm not interested in this form of after the fact code review.
