### ISSUE TITLE
Debounce arrow function is not seeing variable. 

### ISSUE THREAD

**Issue by Abdulla1995** [lodash/lodash#3749]
Im using Vue js 2.5 version.  Todat I have faced this issue. When I use arrow function like below debounce cant see my data. I have console.log this.searchedUser but shows undefined.

**searchOpponent: debounce(() => {
                axios.post('api/users/search', {name: this.searchedUser})
                    .then(({data})=> {
                        console.log(data)
                    });
            }, 500),**

But when I use old version function like below it worked. 

 **searchOpponent: debounce(function() {
                axios.post('api/users/search', {name: this.searchedUser})
                    .then(({data})=> {
                        console.log(data)
                    });
            }, 500),**

What is the problem here?

**Comment by jdalton** [comment]
Hi @Abdulla1995!

For these kinds of support questions head over to our [gitter chat](https://gitter.im/lodash/lodash).
