### ISSUE TITLE
lodash/fp and tree-shaking

### ISSUE THREAD

**Issue by jeremejevs** [lodash/lodash#3751]
Are there any plans to make `lodash/fp` tree-shakeable, like `lodash-es`? Perhaps with the release of Lodash v5? Or is it still `babel-plugin-lodash` for the foreseeable future?

I've seen #3247, but the "Webpack 4" update doesn't provide an updated answer.

**Comment by jdalton** [comment]
Hi @jeremejevs!

For `lodash/fp` your best best is `babel-plugin-lodash`.

**Comment by jeremejevs** [comment]
Alright, thanks!
