### ISSUE TITLE
Inconsistent merging of multiple sources to function property

### ISSUE THREAD

**Issue by inwotep** [lodash/lodash#3752]
lodash v4.17.5

The following test fails:

```
    QUnit.test('should merge first source object properties to function', function(assert) {
      assert.expect(1);

      const fn = function () {};
      var object = { prop: {} },
          actual = _.merge({prop: fn}, object);

      assert.deepEqual(actual, object); // Fails
    });
```

but the following test succeeds:

```
    QUnit.test('should merge first and second source object properties to function', function(assert) {
      assert.expect(1);

      const fn = function () {};
      var object = { prop: {} },
          actual = _.merge({prop: fn}, {prop: fn}, object);

      assert.deepEqual(actual, object);
    });
```
I would expect both of these to succeed.

**Comment by pistis** [comment]
I also checked this.

I think this is the code that causes it.
https://github.com/lodash/lodash/blob/224a256f699a52e7a032d2c6d1059dfb98135878/.internal/baseMergeDeep.js#L74

As a result, neither of the two conditions in the above code is considered true.
(srcIndex && typeof objValue == 'function')
or
! isObject (objValue)

Eventually, newValue does not become an empty object.

I can not be sure if this is the intended or bug.

I want to know if this is a bug.

@inwotep 
But. I think you can solve with mergeWith what you want.

You can use the custormizer.

`
   const fn = function () {}
   let obj1 = {prop: {}
   let obj2 = {prop: fn}
   function customizer (objValue, srcValue) {
     if (typeof objValue === 'function') {
       return srcValue
     }
   }
   var actual = mergeWith (obj2, obj1, customizer)
`

**Comment by sinaabadi** [comment]
Hi @jdalton 
May I take this issue?

**Comment by jdalton** [comment]
Yes, please!

You can patch it so that it works as `lodash/merge`.

**Comment by sinaabadi** [comment]
@jdalton 
I think this line should be edited as @pistis said: 
`else if (!isObject(objValue) || (srcIndex && isFunction(objValue)))`
if I omit the srcIndex condition then this problem will be solved correct?

**Comment by falsyvalues** [comment]
Hi @sinaabadi
Add test case that will cover this bug and it will be easier to play with it.

**Comment by sinaabadi** [comment]
Hi @falsyvalues 
I can't see test directory in project. where must I put my tests?

**Comment by falsyvalues** [comment]
You have to checkout on tag `4.17.10`.

**Comment by sinaabadi** [comment]
@falsyvalues  I think this test is wrong an must be modified 
 ```
QUnit.test('should not merge onto function values of sources', function(assert) {
      assert.expect(3);

      var source1 = { 'a': function() {} },
          source2 = { 'a': { 'b': 2 } },
          actual = _.merge({}, source1, source2);

      assert.deepEqual(actual, { 'a': { 'b': 2 } });

      actual = _.merge(source1, source2);

      assert.strictEqual(typeof actual.a, 'function');
      assert.strictEqual(actual.a.b, 2);
    });
```
I should remove this line right ? 
`assert.strictEqual(typeof actual.a, 'function');`

**Comment by jdalton** [comment]
Moved to #3840.
