### ISSUE TITLE
Question on reducing bundle size with lodash-es

### ISSUE THREAD

**Issue by indefinitelee** [lodash/lodash#3756]
I've just read [this article](https://nolanlawson.com/2018/03/20/smaller-lodash-bundles-with-webpack-and-babel/) by Nolan Lawson about reducing the size of lodash in your bundle and want to make sure I understand it correctly and how to implement some of the suggestions. 

Currently the vast majority of my codebase uses the
 `import {map, values, find, isNil} from 'lodash';` format. 

My understanding of lodash-es is that I can replace my current lodash package with lodash-es 
( so `npm uninstall --save lodash` and `npm install --save lodash-es` )  and then simply add `-es` to all of my import statements and I will get the benefit of smaller import sizes as I would if I wrote my imports as 
`import map from 'lodash/map';`
`import values from 'lodash/values';`
`import find from 'lodash/find;'`
`import isNil from 'lodash/isNil';`  

Is my understanding correct?

**Comment by jdalton** [comment]
Hi @indefinitelee!

With webpack you don't have to change your imports it should cherry-pick with either `import` syntax.
