### ISSUE TITLE
Clarify _.union example in docs

### ISSUE THREAD

**Issue by tyrw** [lodash/lodash#3757]
Currently in the docs, the example for `_.union` is

```
_.union([2], [1, 2]);
// => [2, 1]
```

It's not clear from this that `union` is taking all unique values in either array rather than all values contained in both arrays.  Suggest changing the example to

```
_.union([2, 3], [1, 2]);
// => [2, 3, 1]
```

Seems like this might not warrant a PR, but I can do one if preferred.

**Comment by jdalton** [comment]
Sure, a PR would be great! Just modify the in source example.

**Comment by tyrw** [comment]
PR here https://github.com/lodash/lodash/pull/3758

**Comment by jdalton** [comment]
Moved to #3758
