### ISSUE TITLE
Should we integrate isOdd function into lodash?

### ISSUE THREAD

**Issue by ithinco** [lodash/lodash#3759]
What do you think about lament like this? 
[The Node.js Ecosystem Is Chaotic and Insecure](https://medium.com/@caspervonb/the-internet-is-at-the-mercy-of-a-handful-of-people-73fac4bc5068)
[The Node.js Ecosystem Is Chaotic and Insecure • r/node](https://www.reddit.com/r/node/comments/8crlra/the_nodejs_ecosystem_is_chaotic_and_insecure/)

**Comment by jdalton** [comment]
Hi @ithinco!

Don't feed the trolls. npm has done lots of work in this area to prevent another left-pad. With `npm@6` due out today you can expect plenty of good things (including security features).
