### ISSUE TITLE
indexOf improvement propose

### ISSUE THREAD

**Issue by ghostuz** [lodash/lodash#3760]
Hi all. about use indexOf for string
As I know. for now, _.indexOf is suite for Array. but today. I found my guys use indexOf for the string. and I think this method is too closed to native string.indexOf.
can we add this feature something like

```javascript
function indexOf(target, value, fromIndex) {
	const length = target == null ? 0 : target.length
	if (!length) {
		return -1
	}
	if (isString(target)) {
		let testSource = target.substr(fromIndex);
		return testSource.indexOf(value);
	}
	let index = fromIndex == null ? 0 : +fromIndex
	if (index < 0) {
		index = Math.max(length + index, 0)
	}
	return baseIndexOf(target, value, index)
}
```

**Comment by jdalton** [comment]
Hi @ghostuz!

With Lodash v5 we're moving away from overloading methods and focusing on more simplified forms. As part of that transition methods like `indexOf` may melt away.

**Comment by ghostuz** [comment]
thanks. look forward to the new version.
