### ISSUE TITLE
Dependency on root in es branch

### ISSUE THREAD

**Issue by rugk** [lodash/lodash#3761]
In the esbranch `now` still depends on root. Could not you just hardcode `window` directly in this case, as in the es branch only EcmaScript (i.e. browsers) are supported AFAIK? Or is not this how that branches thing is meant to be…

**Comment by jdalton** [comment]
Hi @rugk!

The `root` module may be different things in different environments so I can't hardcode to `window`.

**Comment by rugk** [comment]
Ah, so even the branch "es" is not 100% browser-optimized. Thanks FYI.

**Comment by jdalton** [comment]
ES is not a browser-only thing FYI.
