### ISSUE TITLE
Bug in omit fp for deep omit 

### ISSUE THREAD

**Issue by mike-down** [lodash/lodash#3765]
lodash version : 4.17.5.

When using `omit` from `lodash/fp` on a object, i want to omit a deep attribute in my object, and the source object get mutated. 

example :

```
> const fp = require("lodash/fp")
undefined
> let x = {id: 3, d : [ {id: 4}], j:0}
undefined
> const y = fp.omit(["id","d[0].id"],x)
undefined
> y
{ d: [ {} ], j: 0 }
> x
{ id: 3, d: [ {} ], j: 0 }
>
```

**Comment by jdalton** [comment]
Hi @mike-down!

That's an issue with regular `omit` as well. We are removing `omit` from Lodash v5. I'd suggest moving to picking the properties you want or manually `delete`ing the ones you don't.
