### ISSUE TITLE
Bug in dropWhile the lodash VERSION = '4.17.5';

### ISSUE THREAD

**Issue by qiaoqia6448** [lodash/lodash#3766]
the function of  dropWhile  can't drop the latest one! 
`_.dropWhile(yuyuelist,function(o){return ((o.t=='学术报告厅'));})
`
(7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}]
0: {t: "第二会议", hy: "答辩", st: "2018-04-24 14:00", et: "2018-04-24 16:30"}
1: {t: "第二会议", hy: "扩大会", st: "2018-04-25 09:00", et: "2018-04-25 10:30"}
2: {t: "第二会议", hy: "在职集体学习", st: "2018-04-25 13:00", et: "2018-04-25 15:00"}
3: {t: "第二会议", hy: "在职一支部学习", st: "2018-04-25 15:20", et: "2018-04-25 16:50"}
4: {t: "第二会议", hy: "董事会", st: "2018-04-27 09:00", et: "2018-04-27 12:00"}
5: {t: "第二会议", hy: "总结会议", st: "2018-04-28 14:00", et: "2018-04-28 16:00"}
6: {t: "学术报告厅", hy: "学术交流", st: "2018-04-24 09:00", et: "2018-04-24 13:00"}
length: 7__proto__: Array(0)

**Comment by jdalton** [comment]
Hi @qiaoqia6448!

The [`dropWhile`](https://lodash.com/docs/#dropWhile) method drops items from the front of an array for as long as the predicate is true. If the predicate fails on the first element then nothing is dropped.
