### ISSUE TITLE
_.zip produces unexpected output

### ISSUE THREAD

**Issue by jreina** [lodash/lodash#3768]
When using the `zip` function on arrays of differing lengths, the standard implementations of `zip` will produce a list which is only as long as the shortest input. lodash appears to always use the longest source array and the output values contain `undefined` where an element does not exist. 

An example:
![image](https://user-images.githubusercontent.com/2089820/39196315-65e1185e-47a7-11e8-9b02-5738cfcf9c10.png)  
The expectation in this case would be an output array with only two items.

**Comment by jdalton** [comment]
Hi @jreina!

There are a couple ways to handle this and our implementation does not clip.
