### ISSUE TITLE
_.sortedIndex question or feature request

### ISSUE THREAD

**Issue by wood1986** [lodash/lodash#3772]
I am looking for a method to achieve this

```
const array = [
  { a: { b: 0, c: 2 } },
  { a: { b: 2, c: 5 } },
  { a: { b: 4, c: 3 } },
  { a: { b: 8, c: 7 } }
] // it is sorted by a.b

_.method(array, 3, (obj) => obj.b)) // return 2
```

I would expected a binary search and the result will be similiar to `_.sortedIndex*`. I know I can achieve this with `_.sortedIndexBy(array, { a: { b: 3 } }, "a.b"))`. But I have to create an object. What if the object is too deep?

Is it worth to have this feature? If so, I want to contribute

**Comment by jdalton** [comment]
Hi @wood1986!

I think for your case a more custom tailor made method would be the best fit.
