### ISSUE TITLE
Suggestion: Add pairwise function

### ISSUE THREAD

**Issue by yewmint** [lodash/lodash#3773]
I'm working on some map stuff which usually requires to get segments between coordinates. But I found there's no elegant way to complete this with lodash like below:

```` javascript
let points = [[0, 0], [1, 1], [2, 2]]
let segments = points.pairwise((current, next) => new segment(current, next))
````

**Comment by jdalton** [comment]
Hi @yewmint!

This sounds very use case specific. You might consider adding it as a [mixin](http://lodash.com/docs/#mixin).

**Comment by StreetStrider** [comment]
In general, I vote up, because when I was in need of smth like that, I end up with ugly reduce, where `accumulator = { real_accumulator, prev_value }` (or reducer with 4 params, if you like that).
