### ISSUE TITLE
Documentation for create should indicate that prototype is optional

### ISSUE THREAD

**Issue by cdhowie** [lodash/lodash#3776]
In the documentation for `_.create()`, the prototype argument appears to be required, but this is not the case.  If the prototype argument is not an object, lodash simply returns `{}`.

This is an important distinction from `Object.create()`, which throws an error if the prototype argument is not an object (this means `null` is permitted as `typeof null === 'object'`, but `undefined` is not permitted).

```
> _.create();
{}
> Object.create();
TypeError: Object prototype may only be an Object or null: undefined
```

**Comment by jdalton** [comment]
Hi @cdhowie!

Lodash tends to be more forgiving when omitting arguments than builtins. I prefer though pushing folks in the right direction by specifying the `prototype` param should be provided.

**Comment by cdhowie** [comment]
I'm not sure I agree that that's necessarily the "right direction."  In FP style we frequently want to reuse functions.  In this case, `_.once(_.ary(_.create, 0))` (something I've done before) would be better style than `_.once(() => ({}))`, but it's not immediately clear from the documentation that `_.create` can be used this way.

Once you realize it's possible, it's unclear if it's even _supported_, which makes me hesitant to rely on this behavior in any production code.  This is why I think the documentation should be tweaked.  An argument that isn't required shouldn't be notated as such.  (Or at least, can we specify that a null/undefined prototype is the same as specifying `Object.prototype`?)
