### ISSUE TITLE
map does not handle iterators

### ISSUE THREAD

**Issue by kumavis** [lodash/lodash#3780]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators

```js
const iterator = createIterator()
_.map(iterator, (x) => console.log(x))

function* createIterator() {
  yield 1;
  yield 2;
}
```

for example code
observed: iterates over 0 elements
expected: iterates over 2 elements

**Comment by kumavis** [comment]
Here is an implementation of `map` that handles iterators, though may not meet your other requirements
```js
function map(collection, iterator) {
  let index = 0
  for (let value of collection) {
    iterator(value, index, collection)
    index++
  }
}
```

**Comment by kumavis** [comment]
note that `iterator.length === undefined`

**Comment by jdalton** [comment]
Hi @kumavis!

Yep, Lodash's `map` only supports arrays and objects (not specialized for iterators).
