### ISSUE TITLE
Security Vulnerability Prototype Pollution

### ISSUE THREAD

**Issue by xlcrr** [lodash/lodash#3782]
Hi,

I am just getting started with react-native and installed this package:

https://github.com/NewOldMax/react-native-validator-form/issues/3

I was prompted with 4 vulnerabilities, one of which links to lodash.

More info for lodash vulnerability:
https://nodesecurity.io/advisories/577

says 

Update to version 4.17.5 or later.

I am running "lodash": "^4.17.10"

Can anyone advise on how to proceed? Thanks

**Comment by jdalton** [comment]
Hi!

You're prolly seeing the warning for a dep of a dap.
