### ISSUE TITLE
getOwn function?

### ISSUE THREAD

**Issue by gakada** [lodash/lodash#3784]
Is there a function like `get` but only for own properties?

Currently
```js
> _.get({a: 1}, 'a')
1
> _.get({a: 1}, 'b')
undefined
> _.get({a: 1}, 'toString')
[Function: toString]
> _.has({a: 1}, 'a')
true
> _.has({a: 1}, 'b')
false
> _.has({a: 1}, 'toString')
false
```
so something like
```js
_.has(xs, x) ? _.get(xs, x) : undefined
```
has to be used.

**Comment by jdalton** [comment]
Thanks @gakada!

I can dig it. 

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
