### ISSUE TITLE
Debounce "ES" version does not contain requestAnimationFrame

### ISSUE THREAD

**Issue by rugk** [lodash/lodash#3789]
The version from master contains `requestAnimationFrame`: https://github.com/lodash/lodash/blob/d985dbffb89e5fa13505ed93449b9fec1fbf973b/debounce.js

The ES version not: https://github.com/lodash/lodash/blob/es/debounce.js

Why? Is the second version outdated?

**Comment by jdalton** [comment]
Hi @rugk!

The master branch is bleeding edge while the other branches are cut stable releases. You'll see things in the master branch that are not in other branches yet.

**Comment by rugk** [comment]
Makes sense, but [requestAnimationFrame has been added 4 months ago](https://github.com/lodash/lodash/commit/d985dbffb89e5fa13505ed93449b9fec1fbf973b) and the [last releasewas just 19 days ago](https://github.com/lodash/lodash/releases/tag/4.17.10), so did you maybe missed to port it to that branch?

**Comment by jdalton** [comment]
Nope. Our master branch is totally separate from the v4 release branches. So even as work was done in the v4 branches after v5 work they wouldn't mix.
