### ISSUE TITLE
Why the dist lodash.js was not minified ?

### ISSUE THREAD

**Issue by brunoosilva** [lodash/lodash#3790]
When used in projects with Babel, it generates a warning because the file exceeds the size of **500kb**, shown below:

```
[BABEL] Note: The code generator has deoptimised the styling of ".../node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
```

I noticed that in **package.json**, the `main` option does not point to the file **lodash.min.js**

**Comment by jdalton** [comment]
Hi @brunoosilva!

We ship both copies because it simplifies things like CDNs based on the package. We don't ship the minified as the default at the moment because it has been known to make debug harder.
