### ISSUE TITLE
_.intersection on sorted arrays

### ISSUE THREAD

**Issue by gorhawk** [lodash/lodash#3792]
Hi!
I was looking for packages on npm that can perform a fast intersection for sorted arrays (like merge join). I had not found any that would have solved my problem (not in lodash either), so I wrote my own functions.

I'd just like to know if lodash has this or if not then why? Didn't find it among the issues either.

**Comment by jdalton** [comment]
Hi @gorhawk!

We have a `sortedUniq` method but no `sortedIntersection`.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by gorhawk** [comment]
I'm planning to create a pr on this. Should it be a simple tape merge or Hwang-Lin algorithm? Is it up to me? Don't want to waste time on misunderstandings.

**Comment by falsyvalues** [comment]
@gorhawk We don't add new functionality right now until there is a demand for that.
