### ISSUE TITLE
set/unset per method package is using memoize, not  memoizeCapped as in lodash proper

### ISSUE THREAD

**Issue by justinbarry** [lodash/lodash#3793]
We discovered an unbounded usage of memory recently while using the per method packages. 

Demonstrated here: https://github.com/justinbarry/lodash-mem-leak-example

## Individual unset package
https://github.com/lodash/lodash/blob/b4e92842db2a69138ac7b31eb1a207482ef84059/lodash.unset/index.js#L655

## Individual set package
https://github.com/lodash/lodash/blob/ca149bd66c18a9b56eea28e89fac4548e09cb9dd/lodash.set/index.js#L654

## In lodash proper:
https://github.com/lodash/lodash/blob/aff1928482b7bfd6f37d6bb07ff2ca34a10c1d5c/.internal/stringToPath.js#L26

**Comment by jdalton** [comment]
Hi @justinbarry!

The per method packages are soft deprecated. For the most up-to-date v4 you should stick with the primary `lodash` package and cherry-pick your methods `lodash/unset`.

**Comment by justinbarry** [comment]
@jdalton is that information documented anywhere? If not, could I help with that?
