### ISSUE TITLE
deburr not works with utf-8 special characters

### ISSUE THREAD

**Issue by throrin19** [lodash/lodash#3795]
Hi, I've a problem with the `deburr` function :

I have a string contains some `éèà`, ... in UTF-8. When I use deburr, the string is already the same in result :

```
const text = 'déjà vu';
const deburred = _.deburr(text);

console.log(deburred); // show 'déjà vu'
```

**Comment by jdalton** [comment]
Based on the example github is rendering I get the correct deburred value of `"deja vu"` _(but they could be switching things up)_. See the [docs](https://lodash.com/docs/4.17.10#deburr) for the encodings it supports.
