### ISSUE TITLE
[bug] _.set(obj, path, -0)

### ISSUE THREAD

**Issue by peonmodel** [lodash/lodash#3798]
```
a = { b: 1 };  // { b: 1 }
_.set(a, 'b', 0);  // { b: 0 }
_.set(a, 'b', -0);  // { b: 0 } ???
_.set(a, 'b', 1);  // { b: 1 }
_.set(a, 'b', -0);  // { b: -0 }
_.set(a, 'b', 0);  // { b: -0 }  ???
```

since -0 === +0, _.set tried to short-circuit and not set the value
however this causes issue for me as i am using _.set to help set some `<input />` element and i want user to be able to key in "-0", as a precursor to typing "1" in between for -10

**Comment by jdalton** [comment]
Thanks @peonmodel!
