### ISSUE TITLE
WARNING in ./~/lodash/isPlainObject.js

### ISSUE THREAD

**Issue by subhranshudas** [lodash/lodash#3799]
```
WARNING in ./~/lodash/isPlainObject.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* ~Projects/node_modules/lodash/isPlainObject.js
    Used by 1 module(s), i. e.
    ~Projects/node_modules/lodash/_baseMergeDeep.js
* ~Projects/node_modules/lodash/isplainobject.js
    Used by 1 module(s), i. e.
   ~Projects/node_modules/babel-loader/lib/index.js??ref--0!/Users/xyz/Projects/modules/utils.js
```

I am getting this warning when i build in Webpack. As per `https://www.npmjs.com/package/lodash.isplainobject` i use 
```
import _isPlainObject from 'lodash/isplainobject';
```

to use `_isPlainObject`, not sure if this is the correct reference from lodash's bundle or there is a more canonical way of doing it.

The code which uses _isPlainObject works though perfectly fine. Just curious about the warning.

**Comment by jdalton** [comment]
The warning isn't anything on our end. We don't have two files in the same package that only differ by casing.
