### ISSUE TITLE
Unable to find createWrap which was imported in Ary definition?

### ISSUE THREAD

**Issue by isaaclem** [lodash/lodash#3800]
Ary was defined as below

<Pre>
import createWrap from './.internal/createWrap.js';

function ary(func, n) {
  n = (func && n == null) ? func.length : n
  return createWrap(func, WRAP_ARY_FLAG, undefined, undefined, undefined, undefined, n)
}
</Pre>

However I cant locate the file `./.internal/createWrap.js`

**Comment by falsyvalues** [comment]
Hi @isaaclem 

The master branch is bleeding edge and is a bit messy right now, take a look on our [contributing 
 note](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#construction-notice-construction).
