### ISSUE TITLE
[Feature Request]: toSchemaPath, object to an array of paths

### ISSUE THREAD

**Issue by Angel8D** [lodash/lodash#3801]
Hi, 

I'm being making some unit test where the test needs to prove an object has the same "schema" than other.
In other words the object must have the same properties that the original in form of a recursive validation.

Actually im using a custom function like this:

```js
var foo1 = {a:1,b:{b1:2,b2:3},c:[{c1:1},{c2:"a"}]}    //original
var foo2 = {a:1,b:{b1:2,b2:3},c:[{c1:1},{c2:"b"}]}   //diferent value
var foo3 = {a:1,b:{b1:2,b2:3},c:[{c1:1},{d2:"a"}]}   //c.d2 doesn't exist
var schema = function(baz,prefix) {
    return _.flattenDeep(_.transform(baz,
    function(r,v,k){
        var scope = (prefix?(prefix+'.'):'') + (_.isInteger(k)?'['+k+']':k) ;
        r.push(scope);
        if(_.isObjectLike(v)){
            r.push(schema(v,scope))
        }
    },
    []))
}
schema(foo1);
_.every(schema(foo1),(val)=>_.has(foo1,val))
_.every(schema(foo1),(val)=>_.has(foo2,val))
_.every(schema(foo1),(val)=>_.has(foo3,val))
```
And in return I have someting like this
```Json
 [ "a", "b", "b.b1", "b.b2", "c", "c.[0]", "c.[0].c1", "c.[1]", "c.[1].c2" ]

true
true
false
```
For me is very useful to validate "schemas" but it can play very nice with 
_.toPath
_.result
_.set
_.update
_.at

**Comment by Angel8D** [comment]
maybe with 2 control variables that let you decide if null and c.[0] be printed, 
and other to change it to and object with the "ObjectType" in the value.

:P 

Thanks

**Comment by jdalton** [comment]
Thanks @Angel8D!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
