### ISSUE TITLE
undefined maxWait on debounce defaults to wait

### ISSUE THREAD

**Issue by rbideau** [lodash/lodash#3802]
In the following code, `maxWait` will default to `wait`:
```javascript
const makeOnInputChange = ({wait, maxWait /*, ... */}) => 
   _.debouce(onInputChange, wait, { maxWait });
```
Used with a React component and when `maxWait` comes from the `props`, `maxWait` is often `undefined`. But because of how it's handled in [debounce](https://github.com/lodash/lodash/blob/4.17.10/lodash.js#L10323), in this case it defaults to `wait`. 

This is a bit counter intuitive to me, but reading through the code, this seems to be the way options are handled in lodash. I don't know what is the best way, but perhaps it's possible to update the doc to reflect this ?

**Comment by jdalton** [comment]
Hi @rbideau!

If you expect `maxWait` to be meaningful and it's `undefined` then you could check for that and assign it whatever value you wanted in that case.
