### ISSUE TITLE
orderBy put value always last

### ISSUE THREAD

**Issue by danielbartsch** [lodash/lodash#3803]
Is it possible to define a custom comparator function for `orderBy` that sorts specific values always last?

I've read about that before. If you return `''`, it should always come last, and if you pass `null` or `undefined`, it's always first. But I cannot get it working when sorting numbers that contain `0`.

See: https://runkit.com/embed/gmnma7sxfajl

**Comment by jdalton** [comment]
Hi @danielbartsch!

For help with this check out our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by danielbartsch** [comment]
documentation about this would probably be good as well
