### ISSUE TITLE
uniqBy with shorthand produces unexpected results if the property not exists 

### ISSUE THREAD

**Issue by syahiaoui** [lodash/lodash#3805]
Hello,
I have this array, and i would like remove duplicate object using property id, but some times this value is not present in the object

 let array = [{
        "quantity": 1,
        "stockMvtDate": "2018-05-29 05:39:00.000",
        "mvtType": "Reception",
        "id": "1234"
    }, 
  {
        "quantity": 1,
        "stockMvtDate": "2018-05-29 05:39:00.000",
        "mvtType": "Reception",
        "id": "1234"

    },`
    {
        "quantity": 1,
        "stockMvtDate": "2018-05-29 05:40:00.000",
        "mvtType": "Reception"
    },
    {
        "quantity": 1,
        "stockMvtDate": "2018-05-29 05:40:00.000",
        "mvtType": "Reception"
    }
];
console.log(_.uniqBy(array, 'id')); 

Result =>
[ { quantity: 1,
    stockMvtDate: '2018-05-29 05:39:00.000',
    mvtType: 'Reception',
    id: '1234' },
  { quantity: 1,
    stockMvtDate: '2018-05-29 05:40:00.000',
    mvtType: 'Reception' } ]

Expect =>
[ { quantity: 1,
    stockMvtDate: '2018-05-29 05:39:00.000',
    mvtType: 'Réception',
    mvtidentifier: '1234' },
  { quantity: 1,
    stockMvtDate: '2018-05-29 05:40:00.000',
    mvtType: 'Réception' },
  { quantity: 1,
    stockMvtDate: '2018-05-29 05:40:00.000',
    mvtType: 'Réception' } ]

Idea to solve this probleme 

thank's

**Comment by jdalton** [comment]
Hi @syahiaoui!

For this kind of help check out our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by syahiaoui** [comment]
Hi @jdalton 
I solved issue using javascript function(filter, map, concat):

    const uniqBy = (myArr, prop) => {
        let array = new Array();
        return myArr.filter((obj, pos, arr) => {
            if (obj[prop]) {
                return arr.map(mapObj =>
                    mapObj[prop]).indexOf(obj[prop]) === pos;
            } else {
                array.push(obj);
            }
            return array.concat(arr);
        });
    };
