### ISSUE TITLE
Uncaught TypeError: _lodash2.default.contains is not a function

### ISSUE THREAD

**Issue by johnsanthosh** [lodash/lodash#3806]
Version used with React : 
"lodash": "^4.17.10"

`_.contains(['1', '2'], '2')`

Error : 
Uncaught TypeError: _lodash2.default.contains is not a function

**Comment by jdalton** [comment]
Hi @johnsanthosh!

The `contains` alias was removed in [v4.0.0](https://github.com/lodash/lodash/wiki/Changelog#v400) in favor of `includes`.

**Comment by johnsanthosh** [comment]
@jdalton Sorry for the trouble.
