### ISSUE TITLE
_.startsWith on Arrays

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash#3808]
Lodash's `startsWith` works perfectly with arrays, but the [docs](https://lodash.com/docs/4.17.10#startsWith) say it only supports strings. Is this supported, and if so, can we update the docs?

**Comment by jdalton** [comment]
Hi @daedalus28!

The `startsWith` method will coerce the given value to a string so working on arrays may be incidental. The official supported value is strings.

**Comment by StreetStrider** [comment]
`startsWith` for arrays looks like a specific case of a more generic mechanism like pattern-matching. It would be great to have one in LoDash, but it's a complicated deed. I believe, there's a bunch of such stuff on npm. People in JS love to invent pattern-matching.

**Comment by daedalus28** [comment]
@jdalton got it, my use case is an array of strings so that's why it works. It might be worth mentioning that explicitly on the docs because those situations can be relied on if you understand the behavior. It would probably work for just about any array of primitives 🤔
