### ISSUE TITLE
How to implement of "curry.js'

### ISSUE THREAD

**Issue by D-kylin** [lodash/lodash#3810]
Hi,I want to implement of "curry.js",but no found the "createWrap" in “.internal' or anywhere.Where can i find it?This lib is excellent.Thank you for your coding.

**Comment by jdalton** [comment]
Hi @D-kylin!

You'll have better luck building from a stable release branch like [this](https://github.com/lodash/lodash/tree/4.17.10-npm).

**Comment by D-kylin** [comment]
Hi @jdalton 
Thanks for your help.
