### ISSUE TITLE
difference between different casing imports in lodash

### ISSUE THREAD

**Issue by subhranshudas** [lodash/lodash#3814]
Hi, 

I am trying to use the import per function used approach to use lodash as follows -

(all inside `app.js`)
**Method 1**
```
import _isPlainObject from 'lodash/isplainobject';
```
(referring to https://www.npmjs.com/package/lodash.isplainobject)

**Method 2**
```
import _isPlainObject from 'lodash/isPlainObject';
```
Suprisingly both work but,
By using **method 1** i get the WARNING when building using webpack as follows
```
WARNING in ./~/lodash/isPlainObject.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* ~/node_modules/lodash/isPlainObject.js
    Used by 1 module(s), i. e.
   ~/node_modules/lodash/_baseMergeDeep.js
* ~/node_modules/lodash/isplainobject.js
    Used by 1 module(s), i. e.
    ~/node_modules/babel-loader/lib/index.js??ref--0!/~/app.js
```
Though under `node_modules/lodash` i see the target function present as `isPlainObject.js`.

SO i am bit confused which is the correct way to import a single function with all lowercasing or camelCasing?? As in what is lodash's recommended way of doing it.
Also if the file name under node_modules is camelCased then how importing the lowercased file also still works??

Thanks.

**Comment by jdalton** [comment]
Hi @subhranshudas!

Case sensitivity may come down to your operating system. You should stick with the actual case of the file though.

**Comment by subhranshudas** [comment]
Thanks @jdalton for the reply!
> You should stick with the actual case of the file though.

I take it should be the one present in the `node_modules`. 

As an after thought, shouldn't https://www.npmjs.com/package/lodash.isplainobject be updated then to the proper casing?
