### ISSUE TITLE
entityValue is not defined

### ISSUE THREAD

**Issue by riteshsainju** [lodash/lodash#3816]
Hi i get an error of entityValue is not defined as following: 

![lodash error](https://user-images.githubusercontent.com/19466365/40970141-71abf23c-68d9-11e8-8aef-4cafd13d7b8a.PNG)

**Comment by jdalton** [comment]
Hi @riteshsainju!

It looks like `entityValue` is a template object or value not being provided. Probably not a Lodash bug.
