### ISSUE TITLE
Different implementation of `findIndex` under 4.10.17 and 4.10.17-npm tags

### ISSUE THREAD

**Issue by xprazak2** [lodash/lodash#3817]
I found out that `findIndex` under 4.10.17-npm tag uses [baseIteratee](https://github.com/lodash/lodash/blob/4.17.10-npm/findIndex.js#L52) while under 4.10.17 tag it is [getIteratee](https://github.com/lodash/lodash/blob/4.17.10/lodash.js#L7258). While `getIteratee` returns a function, `baseIteratee` returns unmodified value and the subsequent call to `baseFindIndex` errors out because it expects `predicate` arg to be a function:

![](https://i.imgur.com/kqh6sQs.png)
![](https://i.imgur.com/sDMhXNb.png)

Maybe `findIndex` in just did not get updated somehow?

**Comment by jdalton** [comment]
Hi @xprazak2!

This looks like you're using `lodash-webpack-plugin` with `shorthands` disabled. I'd recommend continuing to keep `shorthands` disabled and use an arrow function instead as it will save you ~5kB.

**Comment by xprazak2** [comment]
Thanks!
