### ISSUE TITLE
document feature request - reference related functions. With @see for example

### ISSUE THREAD

**Issue by elpdpt** [lodash/lodash#3819]
Suggestion:
For each function jsdoc, add a [@see](http://usejsdoc.org/tags-see.html) segment to reference related functions.

Example:
In `pick` function, there could be a referernce as: `See also: omit` for instance.

Use case: 
I used before ramda in previous projects. I use lodash now in existing one. I find myself always wondering what is the name of the function I need. In ramda docs, for each function there is "See also" segment that helps in that.

I could open some PRs to the functions I have searched for. 

1. Would PR adding @see be welcomed?
2. Any guidelines on the structure and format wanted for them?

**Comment by jdalton** [comment]
Hi @elpdpt!

I think we may have a few `@see` uses but we could always use more. A PR would be great!

**Comment by elpdpt** [comment]
ok, thank you.
