### ISSUE TITLE
Is there has some Function to PickTop Element in Array?

### ISSUE THREAD

**Issue by cocody** [lodash/lodash#3820]
For my case, I want to change the Array like this: 
var foo = [1,2,3,4,5,6,7,8]
=>
var fooChange = [6,4,1,2,3,5,8]
Number 6 and 4 need to PickTop from origin array

Is there has some Function to PickTop Element in Array on LoDash(4.17.5)?
If not, have project to dev this?

**Comment by jdalton** [comment]
Hi @cocody!

There may be a way using a combination of Lodash methods. 
You can visit our [gitter chat](https://gitter.im/lodash/lodash) for help with that.

There's also handy builtin methods like [splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) and [unshift](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/unshift).
