### ISSUE TITLE
Let's discuss a possible `_.groupBySeveral` (or a similar name)

### ISSUE THREAD

**Issue by reyronald** [lodash/lodash#3821]
I came across this scenario recently and thought I could achieve it in one go using lodash but apparently that's not the case (correct me here if I'm wrong), so I ended up writing it myself for my case.

Let's say I have an array of objects and I want to perform several groupings on it based on different properties. I could achieve this by calling `_.groupBy` as many times as I need, but that would iterate linearly through the collection each time, meaning that if I have to group by, say, 10 properties, that solution would require looping through the list 10 times and writing ten lines of code (or writing a function to do it).

```js
const people = [
	{ nationality: 'American', gender: 'male', name: 'John'},
	{ nationality: 'American', gender: 'female', name: 'Mary'},
	// ...
]

const byNationality = _.groupBy(people, p => p.nationality)
const byGender = _.groupBy(people, p => p.gender)
// ...possibly other calls
```

The main goal is to have a utility function that not only does the many groupings for me at once, but also get them in only one linear pass through the collection. For the above example, the usage could be something like this:

```js
const groups = _.groupBySeveral(people, 'nationality', 'gender')

// Result =>
{
  nationality: {
    American: [
      /*..*/
    ]
  },
  gender: {
    male: [
      /*..*/
    ],
    female: [
      /*..*/
    ]
  }
}
```

What do you think? Is there actually an obvious way to achieve this using lodash with the specified constraints that I missed?

The implementation would be simple and actually very similar to the existing `_.groupBy`. I don't know how welcoming or accepting of external contributions this project is, but this is something that I could contribute myself if given the green light.

Looking forward to your comments, and thank you for giving this wonderful library to the world! You've done an amazing job! ❤️

**Comment by jdalton** [comment]
Hi @reyronald!

Like a `groupByAll`. If you dig it you should totally create it as a standalone mixin/package first.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by reyronald** [comment]
Hi @jdalton , thank you for the quick response!

> Like a `groupByAll`

Did you mean to say this is already known as a `groupByAll` function somewhere? Or where you suggesting it as a more appropiate name?

**Comment by jdalton** [comment]
Ah, just suggesting a name :D
