### ISSUE TITLE
Feature Request - Deep Copy Everything with recursion - Array/Objects/Array of Objects

### ISSUE THREAD

**Issue by IamManchanda** [lodash/lodash#3822]
I have been working on a project where we had a serious need of deep copy. We use Lodash and there is thing called clone/cloneDeep but problem with that I found was it was just for objects ... but we also needed were arrays and more specifically array of objects

So we made a util for our internal use and now I would like to contribute to this project

Here is my Util, test version can be found at https://codepen.io/IamManchanda/pen/XYpVPY?editors=0012

```javascript
function deepCopy(value) { // deepCopy by Value
  let val;
  if (value && Array.isArray(value)) {
    val = [...value]; // Copy by Value instead of Reference - ES6 Spread
  } else if (value && typeof value === 'object') {
    val = { ...value }; // Copy by Value instead of Reference - ES6 Spread
  } else {
    return value; // Returns original value and stops!
  }

  Object.keys(val).forEach((key) => {
    if (val[key]) {
      if (Array.isArray(val[key]) || (typeof val[key] === 'object')) {
        val[key] = deepCopy(val[key]); // Recursion
      }
    }
  });
  return val; // Returns Final Value
};
```

----

But as much I understood lodash and you guys... you might be looking for non es6 spread way 🤔 
So here is another version for the same (Test version can be found here => https://codepen.io/IamManchanda/pen/ZReNLx?editors=0012)

```javascript
function deepCopy(value) { // deepCopy by Value
  let val;
  if (value && Array.isArray(value)) {
    val = [].concat(value); // Copy by Value instead of Reference - Array.prototype.concat
  } else if (value && typeof value === 'object') {
    val = _.clone(value); // Copy by Value instead of Reference - Lodash `clone` util
  } else {
    return value; // Returns original value and stops!
  }

  Object.keys(val).forEach((key) => {
    if (val[key]) {
      if (Array.isArray(val[key]) || (typeof val[key] === 'object')) {
        val[key] = deepCopy(val[key]); // Recursion
      }
    }
  });
  return val; // Returns Final Value
};
```

**Comment by jdalton** [comment]
Hi @IamManchanda!

Thanks for the suggestion. I'm happy to defer to user-land packages for this. My hope is that a built-in deep clone comes to browsers and Node (based on the structured cloning algorithm) then there would be no need for user-land implementations.

**Comment by IamManchanda** [comment]
Hmmnn...

> My hope is that a built-in deep clone comes to browsers and Node 

Would you suggest me to repost this in TC39 in that case ... I mean requesting for built-in deep clone instead of user land?

---

> I'm happy to defer to user-land packages for this?

Any specific reasons for that buddy? :D
