### ISSUE TITLE
_.merge but for arrays

### ISSUE THREAD

**Issue by rjerue** [lodash/lodash#3825]
Ran into something today that I think might be a good fit for lodash.

Right now in JS, if you want to merge one array into another you have to use concat or a hacky form of `push.apply()` like `Array.prototype.push.apply([1, 2, 3], [4, 5, 6])`

The push.apply works fine if the second array is small, but I was working with arrays thousands of indexes long. I actually peeked into lodash's documentation to see if there was anything useful, but couldn't find anything really.

All this would do is leverage `.push()` to merge one array into another.

```
function merge(array, ...args){
    for(i in args){
        for(j in args[i]){
            array.push(args[i][j])
        }
  }
}
```

**Comment by jdalton** [comment]
Hi @rjerue!

I'd like to defer to the language here if possible with spread.
```js
[...a, ...b]
//or
a.push(...b)
```

If there are perf issues with that we should let the engine folks know.

**Comment by rjerue** [comment]
The first example returns a new array, when working with the limits of chrome's memory, that's a problem. I did not though know that the second would work though. Thanks
