### ISSUE TITLE
[Feature Request] `setSafeInterval` wanted

### ISSUE THREAD

**Issue by Maledong** [lodash/lodash#3826]
Hello all:

For an interval, we can make this loop after a period of time. However there's a problem when the body the execution function of `setInterval` takes for a long time larger than interval time. 

A typical example is:

```javascript
setInterval(()=>
{
   //Suppose this takes 2000 milliseconds
},1000);
```
Because the body of the execution function takes 2 seconds, which is larger than interval time (1 second). Sometimes this is a serious problem because the first loop hasn't been totally executed, and the next comes.

I'd like to offer a new function called `setSafeInterval`, made up of double setTimers：

```javascript
function setSafeInterval(exeFunc,intervalTime = 1000){

     let delayTime = intervalTime; 

     setTimer(function(){
               let _self = this;
    
                try{
                     exeFunc(function(){
                              setTimer(_self, delayTime);
                      });
                }catch(e){
                     //Ignore the error, we don't continue to execute the `exeFunc`.
                }
     },0);  
}
```

You can call something like this following:
```javascript

setSafeInterval(function(callBack){
//Here do what you want......
callBack(); //MUST call this for the next loop
},1000);   
```
This will make you fell comfortable to execute a function whose time is larger than the interval time safely.

What do you think of this?  I think this will solve the problem of `setInterval` and this is a common method used in many areas.

**Comment by StreetStrider** [comment]
@Maledong looks like an async primitive. Take a look onto [async](http://caolan.github.io/async/) or [bluebird](http://bluebirdjs.com/docs/api-reference.html), maybe it's already there. When I personally face such issue I just replace timing function with tail call, like:
```js
function target ()
{
  return do_stuff()
  // optional .delay(ms)
  .then(target)
}
```
Btw, your snippet can be definitely rewritten in promises and win in lower complexity and better reading.

**Comment by jdalton** [comment]
Ah yes, async libs are better suited for this kind of thing.

**Comment by StreetStrider** [comment]
@Maledong [forever](http://caolan.github.io/async/docs.html#forever) with possible replacement in [doWhilst](http://caolan.github.io/async/docs.html#doWhilst). You'll need to apply a delay on target function.

**Comment by Maledong** [comment]
@StreetStrider ：
Many thanks for your reply of `async` lib. 

@jdalton ：
Just a very simple version to satisfy what we need for most of users in lodash:)
