### ISSUE TITLE
_.get returns null when value at path is 0 or false

### ISSUE THREAD

**Issue by kaligrafy** [lodash/lodash#3831]
falsy values returns null. Is it a normal behaviour?
It is a real problem when storing 0 (zero) integer or booleans:
```
const foo = {a: 0, b: 1, c: '0', d: false};
_.get(foo, 'd'); // null
_.get(foo, 'a'); // null
```

**Comment by c-dante** [comment]
Not sure what build you're working off of, but:
```js
> const x = { a:  100, b: 0, c: false, d: 'true' }
undefined
> _.get(x, 'a')
100
> _.get(x, 'b')
0
> _.get(x, 'c')
false
> _.get(x, 'd')
"true"
```

![image](https://user-images.githubusercontent.com/6332726/41490716-4d42d2a2-70c3-11e8-82b1-cbbada3b635a.png)

that was tested on https://lodash.com/

**Comment by jdalton** [comment]
Hi @kaligrafy!

If you're using `lodash-webpack-plugin` you might have to enable `paths`. Else provide it params like`_.get(x, ['a'])`.

**Comment by kaligrafy** [comment]
Well, it didn't work in https://codepen.io/travist/full/jrBjBz/ but I see it works when I launch node from the command line, so now it works in my react project. Thanks and sorry for this!
