### ISSUE TITLE
[enhancement] implicit casting within 'maskSrcKey' func

### ISSUE THREAD

**Issue by svr93** [lodash/lodash#3832]
Hi,
i use runtime checks for Array objects (via Symbol.toPrimitive) to prevent some kinds of type errors.
Function
```
var maskSrcKey = (function() {
  var uid = /[^.]+$/.exec(coreJsData && coreJsData.keys && coreJsData.keys.IE_PROTO || '');
  return uid ? ('Symbol(src)_1.' + uid) : '';
}());
```
uses implicit casting - ```('Symbol(src)_1.' + uid)``` - so i have an error message in console:
```
TypeError: implicit coercion:  ["csrbs9spgt", index: 19, input: "Symbol(IE_PROTO)_2.csrbs9spgt", groups: undefined]
```
(you can see it on https://test.cognita.ru/contacts page)

Is there any possibility to rewrite function with explicit ```String(uid)``` usage or with getting the value by index?

**npm package**: lodash.merge
**version**: 4.6.1

**Comment by jdalton** [comment]
Hi @svr93!

We've removed this bit of code in our master branch so it won't be in the next major release.

**Comment by svr93** [comment]
OK, thanks!
