### ISSUE TITLE
What's the build-in syntax for curry? (roadmap question)

### ISSUE THREAD

**Issue by dietergeerts** [lodash/lodash#3833]
Hi,

I saw on the roadmap that in v5, curry will be removed for build-in syntax. I was wondering what this build-in syntax is, that is like completely the same like what curry does? Can you give an example please? I currently use this function a lot, to give the ability to use a function in any way needed, like a normal function, or with partial application, or full currying. I know you can use bind, but that's something the user of the function has to do then, while with curry, it's already done. Unless I don't know about some new thing added to JS?

**Comment by jdalton** [comment]
Hi @dietergeerts!

Currying methods can be simulated with arrow functions, spread, and rest syntaxes.

**Comment by dietergeerts** [comment]
So instead of doing the following, with gives you all possible usage:

```
const myFunc = _curry((a, b, c, d) => a + b + c + d);
const myFuncPartial = myFunc(1, 2);
console.log(myFuncPartial(3, 4));
```
it's more preferred to have a normal function, and let the user decide on how to use it with the help of arrow functions, spread, rest, and probably bind?
```
const myFunc = (a, b, c, d) => a + b + c + d;
// const myFuncPartial = myFunc.bind(null, 1, 2);
const myFuncPartial = (c, d) => myFunc(1, 2, c, d);
console.log(myFuncPartial(3, 4));
```
I agree with this for the fact that it's more explicit, you work with normal functions and the user will decide how to use it. But I don't agree on the fact that this makes more code, slightly less readable in longer chains and removes the point-free part of what I love about lodash/fp.

So does this also mean that lodash/fp methods will not be auto-curried anymore? As that is what the proposal is (remove auto-curry for arrow func, rest, spread, bind, ...)

**Comment by dietergeerts** [comment]
@jdalton , can you please give any insight on my question:

> So does this also mean that lodash/fp methods will not be auto-curried anymore? As that is what the proposal is (remove auto-curry for arrow func, rest, spread, bind, ...)

If this will be the case, I can understand, but if auto-curried is being kept, then it breaks consistency with own code style.

**Comment by jdalton** [comment]
Ah sorry, I had the tab open to reply but got side-tracked. The Lodash v5 primary package will be significantly smaller (at the moment it's more than 4mb) in v5 it will be more like 90kB. Part of this slimming down is to remove the heavier wrapper code (esp. if newer syntax can make it close enough). Auto-currying is part of the cut. I'd be interested in other one-off auto-curry modules that might be helpful on that front.
