### ISSUE TITLE
 A problem encountered in using an implicit chain

### ISSUE THREAD

**Issue by changk99** [lodash/lodash#3834]
Loadsh:  v4.5.0   Node: v7.4.0

```
var search = "id=12&url=https://beautify.com";
var search = _(search).split('&').map(value => _.split(value, '=')).value();
console.log(search); 
var search = "id=12&url=https://beautify.com";
var search = _(search).split('&').map(_.partial(_.split, _, '=')).value();
console.log(search);
console.log((value => _.split(value, '='))('id=12'))
console.log((_.partial(_.split, _, '='))('id=12'))
```
output:
```
[ [ 'id', '12' ], [ 'url', 'https://beautify.com' ] ]
[ [], [ 'url' ] ]
[ 'id', '12' ]
[ 'id', '12' ]
```

I expect the second output is [ [ 'id', '12' ], [ 'url', 'https://beautify.com' ] ] but not.

**Comment by jdalton** [comment]
Hi @changk99!

What you've hit is that [`String#split`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split) accepts a second param `limit` and when passes as an iteratee to map, map will provide an `index` value as the second param to the iteratee.

**Comment by changk99** [comment]
Thanks
This is my mistake, 
I try this
`var search = _(search).split('&').map(_.unary(_.partial(_.split, _, '='))).value();`
This is ok
Loadsh is amazing

**Comment by jdalton** [comment]
You can keep it simple and defer to native:
```js
var search = search.split('&').map((part) => part.split('='))
```
