### ISSUE TITLE
Mocha fails - Unexpected token export

### ISSUE THREAD

**Issue by lavor** [lodash/lodash#3837]
After moving from lodash to lodash-es and to named imports our testing environment fails.

```
export { default as add } from './add.js';
^^^^^^
SyntaxError: Unexpected token export
```

Our code already uses ES6 imports and exports and until move to the lodash-es they were testable.
I am using named imports of lodash-es like this:

`import {trimEnd} from 'lodash-es';`

I found the same stackoverflow question, but without any useful answer:
(https://stackoverflow.com/questions/46175770/lodash-es-is-not-working-with-mocha-and-babel)

**Comment by jdalton** [comment]
Hi @lavor!

The syntax is valid. You can use the [`esm`](http://npmjs.com/esm) package with mocha:
```
mocha -r esm
```

**Comment by lavor** [comment]
Thanks, @jdalton. It works like a charm :).

**Comment by jdalton** [comment]
Great 🤩

The [`esm`](http://npmjs.com/esm) loader can also be used to publish npm packages that use ES module syntax!
If you want to create a new package with esm you can use `npm init esm` _(with npm6+)_.
