### ISSUE TITLE
deprecate modular build packages?

### ISSUE THREAD

**Issue by jedwards1211** [lodash/lodash#3838]
I recently discovered that all of the `lodash.assign`, `lodash.isstring`, `lodash.isobject`, etc. packages I've been using were larger than I would have expected, and take up quite a bit of space in my webpack bundles, and that I could save plenty of space by requiring `lodash/assign`, `lodash/isString`, etc. instead.  It seems like all libraries that depend on modular build packages should make this switch.  Deprecating would encourage library authors to get the ball rolling on this change.  (I have my own `jscodeshift` script I've been using to make this change to my own packages and would be happy to release it publically).

Or is there something I misunderstand?  Do the modular build packages really have any advantages over `lodash` anymore?

**Comment by jdalton** [comment]
Hi @jedwards1211!

>  (I have my own jscodeshift script I've been using to make this change to my own packages and would be happy to release it publically).

Yes, please release it :D

The individual module packages won't be carried over to Lodash v5. I can't deprecate them with the `npm deprecate` method since that sends a log to stderr and causes some build scripts to fail. So I will simply let it fade away without a v5 update.

**Comment by jedwards1211** [comment]
Okay here it is: https://github.com/jcoreio/jscodeshift-replace-lodash-method-packages
