### ISSUE TITLE
Tree-shaking with TypeScript + Webpack

### ISSUE THREAD

**Issue by vertic4l** [lodash/lodash#3839]
How do we achieve correct tree shaking within TypeScript + Webpack setups?

`import debounce from "lodash/debounce";`

imports the whole library in vendor bundle ?!

**Comment by TrySound** [comment]
Use `lodash-es` with esm. I'm not sure it will work though because of this useless file.
https://unpkg.com/lodash-es@4.17.10/lodash.default.js

**Comment by vertic4l** [comment]
@TrySound ya, tried `lodash-es` already, which gave me both in the bundle at the end.

I 've got some more packages which are using lodash. Don't know if it's coming from these packages.

**Comment by TrySound** [comment]
You should configure an alias lodash -> lodash-es to solve this. Since lodash is not treeshakable it's recommended to use [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin).

**Comment by vertic4l** [comment]
@TrySound i will give that a try. thx

**Comment by jdalton** [comment]
Hi @vertic4l!

There's plenty of resources online for  bundling, aliasing, and cherry-picking. You might check out [this post](https://nolanlawson.com/2018/03/20/smaller-lodash-bundles-with-webpack-and-babel/).

**Comment by vertic4l** [comment]
Tree-shaking seems to work with lodash-es without issues, will try with lodash itself soon.

My issues was another npm package which required lodash twice.... *facepalm*

**Comment by siluri** [comment]
I have a similar Problem:

Try to treeshaking lodash with lodash-es module in combination of Typescript / Webpack 4 and Jest.

Webpack build runs as intended - But got following issue by running tests:

```
Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\xxx\workspaces\xxx\node_modules\lodash-es\lodash.js:10
    export { default as add } from './add.js';
    ^^^^^^

    SyntaxError: Unexpected token export

    > 1 | import { isPlainObject } from 'lodash-es';
        | ^

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/service/api/xxxUtil.ts:2:1)
```
same with treeshaking syntax:
```
 Test suite failed to run

    C:\xxx\workspaces\xxx\node_modules\lodash-es\isPlainObject.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import baseGetTag from './_baseGetTag.js';
                                                                                                    ^^^^^^^^^^

    SyntaxError: Unexpected identifier

      1 | import { AxiosPromise } from 'axios';
    > 2 | import isPlainObject from 'lodash-es/isPlainObject';
        | ^
      3 | import { ApiError } from '../../util/error';
      4 |
      5 | /**

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/service/api/xxxUtil.ts:2:1)
```

**Comment by rrdlpl** [comment]
I have the same error as @siluri  is there way to fix this?

**Comment by rakeshsinghranchi** [comment]
@siluri , see this : https://medium.com/@martin_hotell/tree-shake-lodash-with-webpack-jest-and-typescript-2734fa13b5cd for Jest issue.
