### ISSUE TITLE
Deep Compare of Two Objects

### ISSUE THREAD

**Issue by ThornWinters** [lodash/lodash#3842]
This is a feature request.

I would find it useful to have a function to do a deep verification of two objects and see if they have the same values.

I could make this function myself but I wanted to open the discussion about if it added enough value to the library to justify it.

Let's go over some examples of behavior. Let's call this function sameValues for these examples.

Examples
```
    const obj1 = {
      a: 1,
      b: [{a: 1}, {b: 2}]
    }
    const obj2 = {
      a: 1,
      b: [{a: 1}, {b: 2}]
    }
    const result = sameValues(obj1, obj2)) 
    console.log(result)
```
This should print `true`

```
    const obj1 = {
      a: 1,
      b: [{a: 2}, {b: 2}]
    }
    const obj2 = {
      a: 1,
      b: [{a: 1}, {b: 2}]
    }
    const result = sameValues(obj1, obj2)) 
    console.log(result)
```
This should print `false` as obj1.b[0].a does not equal obj2.b[0].a

**Comment by rafde** [comment]
@ThornWinters why doesn't `_.isEqual` work for this example?
