### ISSUE TITLE
How to make packing files less when using webpcak for lazy evaluation

### ISSUE THREAD

**Issue by changk99** [lodash/lodash#3844]
// Cherry-pick methods for smaller browserify/rollup/webpack bundles.
```
var at = require('lodash/at');
var curryN = require('lodash/fp/curryN');
```
I know this can make bundles less but I want to use the lazy evaluation to improve performance
like this
```
var _ = require('loadsh');
_([1, 2]).map().take() or 
_.chain([1, 2]).map().take()
```
But the package file contains the entire loadsh.
The webpack is not very smart, i just want to contain two methods what i use

**Comment by jdalton** [comment]
Hi @changk99!

If size and performance are a concern you could avoid chaining and implement the equivalent in a single for-loop _(what lazy evaluation tries to flatten down to in practice)_.
