### ISSUE TITLE
[Feature Request] Insert Element Between Each Two Array Items

### ISSUE THREAD

**Issue by rockmandash** [lodash/lodash#3846]
First, Thank you for this wonderful library!
I want a method which can Insert Element Between Each Two Array Items.
It looks like this.
![image](https://user-images.githubusercontent.com/7580792/41954333-6713fdf2-7a0d-11e8-8de7-1f5000914706.png)
I couldn't find one in the lodash docs, so I made one.
```javascript
import flowRight from 'lodash/fp/flowRight';
import zip from 'lodash/zip';
import dropRight from 'lodash/fp/dropRight';
import fill from 'lodash/fill';
import flatten from 'lodash/fp/flatten';

const InsertElementBetweenEachTwoArrayItems = (targetArray, insertItem) => {
  return flowRight(
    dropRight(1),
    flatten
  )(zip(targetArray, fill(Array(targetArray.length), insertItem)));
};

export default InsertElementBetweenEachTwoArrayItems;
```

I wonder if this method can add into lodash.
But I don't know if this is the "most performant".
And I have no idea what writing test is. (sorry)

**Comment by StreetStrider** [comment]
#2339

**Comment by jdalton** [comment]
@rockmandash Thank you for the diagram!
