### ISSUE TITLE
_.getValueForFirstExistingKey on any object

### ISSUE THREAD

**Issue by milap1296** [lodash/lodash#3847]
Hi,

I was looking for something like getting value for the first existing key in my object.
I ended up with this piece of code.
```obj.key1 || obj.key2 || obj.key3 || ...```

So, instead of this, if we can
```getValueForFirstExistingKey(obj, [key1, key2, key3, ...])```

I have written this snippet of code:- 
```
getValueForFirstExistingKey = (obj, keyList) => {
  let resolvedValue;
  if (_.isObject(obj)) {
    _.some(keyList, key => {
      resolvedValue = _.get(obj, key);
      return !_.isUndefined(resolvedValue);
    });
  }
  return resolvedValue;
};
```

**Comment by StreetStrider** [comment]
> getValueForFirstExistingKey

Nice name. I peronally prefer word «coalesce» for that task. BTW, such function is present in [object-path](https://www.npmjs.com/package/object-path).

**Comment by jdalton** [comment]
Hi @milap1296!

This is related, but different, to #3615.
We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by kenbellows** [comment]
Definitely would love to see this, I'm constantly writing stuff like "_.get(obj, 'first.path') || _.get(obj, 'second.path') || ...", or else "_(obj).at('first.path', 'second.path', ...).omit(_.isNil).first()", both of which are slightly wrong and difficult to read. A built-in method to do the real thing the right way would be amazing.

**Comment by hetpatel33** [comment]
It would be a great feature to be added, we used to repeat a similar code for finding the same thing where we have to maintain an object to store the data. It will surely make the current approach easy to understand and clean. Love to see this in upcoming updates.

**Comment by milap1296** [comment]
@jdalton should I make a pull request for the proposition ?

**Comment by jdalton** [comment]
@milap1296 Not at this time. Thanks though.
