### ISSUE TITLE
Version issue on npm

### ISSUE THREAD

**Issue by ThomasPCG** [lodash/lodash#3849]
Hi,

Not sure if this is the right place but I notice this strange issue for [lodash on npm](https://www.npmjs.com/package/lodash). If you look at the version of lodash on npm, it's showing 4.17.10 but apparently there is a security issue with 4.17.10(https://nodesecurity.io/advisories/577) so everyone is encouraged to upgrade to 4.17.15 (https://www.npmjs.com/package/lodash/v/4.17.5) but this is not the default version npm install when you execute `npm install lodash`

Any reasons why that's the case?

**Comment by graingert** [comment]
@ThomasPCG you linked to the wrong version: https://www.npmjs.com/package/lodash/v/4.17.15

**Comment by graingert** [comment]
The recommendation is to:

> Update to version 4.17.5 or later.
