### ISSUE TITLE
_.set, path include number,  length exception,  it's a bug?  

### ISSUE THREAD

**Issue by ccjoe** [lodash/lodash#3851]
var object = { 'a': [{ 'b': { '2018': 3 } }] };
_.set(object, 'a[0].b.2018', 4);

var object = { 'a': [] };
_.set(object, 'a[0].b.2018', 4);

![_20180628160009](https://user-images.githubusercontent.com/4242643/42021122-5bd928f6-7aec-11e8-9d56-2e15df77c8f6.png)

**Comment by jdalton** [comment]
Hi @ccjoe!

To side-step the default behavior of `set` you'll want to use [`setWith`](https://lodash.com/docs/#setWith).

```js
var object = {};
 
_.setWith(object, '[0][1]', 'a', Object);
// => { '0': { '1': 'a' } }
```
