### ISSUE TITLE
_.words and the single quote/apostrophe character (')

### ISSUE THREAD

**Issue by thorn0** [lodash/lodash#3856]
In many orthographies, the apostrophe, despite not being part of the alphabet, is used as a letter, by which I mean it is considered part of the word, not a punctuation mark. E.g. Ukrainian:
```js
_.words(`Кам'янець-Подільський`); // ["Кам", "янець", "Подільський"]
```
Expected: `["Кам'янець", "Подільський"]`

I see there has been implemented a special-case handling for English contractions like "isn't" and"aren't", but in all other cases, `_.words` treats an apostrophe in the middle of a word as a word separator (punctuation). Why is it so? I'm rather surprised by this behavior because I can't see how it's useful.

**Comment by jdalton** [comment]
Hi @thorn0!

I think you'll be better off with a more customized solution than using `_.words`.

**Comment by thorn0** [comment]
Would be interesting to hear from the Francophones what is their expected result for calls like `_.words('Côte d'Ivoire')`.
