### ISSUE TITLE
Load all Lodash modules

### ISSUE THREAD

**Issue by jwerre** [lodash/lodash#3858]
I've created a modularized version of Lodash using lodash-cli:

    lodash exports=amd,node,global --output lodash modularize

This works great when I want to load a few functions individually but there are some cases where I want to load the entire library. Is there a way to compile something like lodash/index.js or lodash/lodash.js (similar to the one created by npm) which loads all the lodash modules into a single export? Currently I'm running a second command which works but not ideal.

    lodash exports=amd,node,global --output lodash/lodash.js core

**Comment by jdalton** [comment]
Hi @jwerre!

You should check-out comboing the `lodash-es` npm package with `webpack` to create your customize bundles. There's even `lodash-webpack-plugin` to reduce your bundles beyond that of `lodash-cli`.

**Comment by jwerre** [comment]
@jdalton I'm stick in `require.js` land so no `webpack` for me.

**Comment by jdalton** [comment]
Webpack has AMD targets for bundles too.
