### ISSUE TITLE
New feature in object category: findKeyDeep

### ISSUE THREAD

**Issue by biruelrick** [lodash/lodash#3859]
Hi there, 

This new feature returns some details (path, parentPath and value) from a matched key. I implemented this method (see attached file) because I needed it in a specific situation and I didn't find it in any library. I use lodash and think it fit perfectly in this package in the Object category.

This new feature returns some details (path, parent path, and value) of a corresponding key. I implemented this method because I needed it in a specific situation and I did not find it in any library. I use lodash and I think it fits perfectly into this package in the Object category.

[findKeyDeep.txt](https://github.com/lodash/lodash/files/2161483/findKeyDeep.txt)

Thanks to all
Ricardo Biruel

**Comment by jdalton** [comment]
Thanks @biruelrick!

Nice, use of the attachment functionality in GitHub 👌  
We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
