### ISSUE TITLE
How to get nested key of object?

### ISSUE THREAD

**Issue by rekhasinghal08** [lodash/lodash#3860]
For example, I have following object.

var a : { b: {c : {d : "hello"}}}

In result, I want : 
'a.b.c.d'

**Comment by jdalton** [comment]
Hi @rekhasinghal08!

Lodash doesn't have a method for that. 
However, you might visit our [gitter chat](https://gitter.im/lodash/lodash) and ask the helpful folks there for assistance.

**Comment by biruelrick** [comment]
Hi @rekhasinghal08, I created a methods called 'findKeyDeep' that do exactly it, returning an object with **path**, **parentPath** and **value**) like this:

```
const users = {
  'biruel': {
    'age': 38,
    'location': {
      'liveIn': {
        'country': 'brazil',
        'flag': 'br.jpg',
      },
      'WorkOn': {
        'country': 'spain',
        'flag': 'es.jpg',
      },
    },
  },
};

findKeyDeep(users, 'flag').then(x => console.log(x));
// out => [
  {
    item: 1,
    path: 'biruel.location.liveIn.flag',
    value: 'br.jpg',
    parentPath: 'biruel.location.liveIn'
  },
  {
    item: 2,
    path: 'biruel.location.WorkOn.flag',
    value: 'es.jpg',
    parentPath: 'biruel.location.WorkOn'
  }
];

findKeyDeep(users, 'since').then(x => console.log(x));
// out => false;
```

here's do source code for this: https://github.com/lodash/lodash/issues/3859
...enjoy to vote to include in the lodash.

Ricardo Biruel
