### ISSUE TITLE
lodash.pick module problems 

### ISSUE THREAD

**Issue by gtamas** [lodash/lodash#3865]
I recently refactored my code to make use of lodash modules instead of the big lodash library. Everything works fine, except the pick function.

I used to be able to do this:

_.pick(someObject, ['some.nestedKey']);

This used to return the right value.

But since I installed the NPM module lodash.pick (https://www.npmjs.com/package/lodash.pick), this doesn't seem to work anymore! I'm still able to use simple prop names, but the dot notation doesn't return anything. I thought the .pick() function in the "big" lodash library and the one provided by lodash.pick module are supposed to be identical. Is this not true?

I mean, if I try to run the code example on the lodash website, dot notation works, but it doesn't work with the the module provided function.

I want to use the "modular lodash" (https://www.npmjs.com/search?q=keywords:lodash-modularized), so I can import only the functions I need. Are these modules not up-to-date?

Thanks in advance!

**Comment by jdalton** [comment]
Hi @gtamas!

Tooling has shifted to using the single `lodash` package in a modular way. For example `lodash-es`.

```js
import { pick } from "lodash-es"
```

**Comment by gtamas** [comment]
Ahh thanks for the info., OK I see.
So the basically npm packages are not maintained anymore, right? 
The up-to-date code is only available in the main library.
