### ISSUE TITLE
isTruthy is needed

### ISSUE THREAD

**Issue by jasonxia23** [lodash/lodash#3868]
I have searched by Google to find a isTruthy function in lodash, but I find nothing. So is there any reason why lodash do not provide this kind of function:
```javascript
isTruthy([])
// => false
isTruthy({})
// => false
isTruthy(0)
// => false
isTruthy(new Set())
// => false
```

**Comment by jdalton** [comment]
Hi @jasonxia23!

I generally defer to `Boolean()` for that kind of thing. I notice it would return a different result for `isTruthy([])`or `isTruthy(new Set())` but I wouldn't want those cases to return `false` either.
