### ISSUE TITLE
_.template variable names

### ISSUE THREAD

**Issue by kunaakos** [lodash/lodash#3869]
Passing data to templates with keys that aren't valid JS variable names (but valid object property names) throws errors. Example:
```
const compiled = _.template('Some are like <%= this:var %>');
compiled({ 'this:var': ':(' });
```
This is kind of an edge case, but is caused by the `with` statement being used in compiled templates. A possible solution could be using property accessors with the bracket notation : `obj['this:var']` instead of `with (obj) { /* ... */ }` in compiled template functions? 
Saw some related issues that were closed ([most recent](https://github.com/lodash/lodash/issues/3709)) - and this would also 'fix' global variables being available in templates, which is, weird.
Would love to give this a go if it's considered useful.

**Comment by jdalton** [comment]
Hi @kunaakos!

This isn't a `with` statement limitation, it's just a JS identifier one. Our `template` method is not fancy. You should look to more advanced ones (preferably logicless ones).
