### ISSUE TITLE
Create an `unsetWith` or use splice instead of delete on arrays

### ISSUE THREAD

**Issue by cusspvz** [lodash/lodash#3870]
I need to unset/splice a value from the array and I was expecting that the `unset` method was using splice if the item was an array children.

`example.js`
```js
var obj = { 
  users: [
    'cusspvz'
    'lodash'
  ]
}
unset( obj, 'users[0]' )
console.log(obj)

// expected: { users: [ 'lodash' ] }
// output: { users: [ empty, 'lodash' ] }
```

We can either have an unsetWith where we could replace the delete logic with a method, or have the splice being the default for parent arrays.

**Comment by jdalton** [comment]
Thanks @cusspvz!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
