### ISSUE TITLE
Unify ES and CommonJS packages using pkg.main and pkg.module

### ISSUE THREAD

**Issue by andrewpeterprifer** [lodash/lodash#3871]
Currently I have the problem that I want to make use of tree shaking with Webpack + ES modules, but on the other hand I don't want to transpile my node_modules on the server.

This could be easily solved if lodash would specify a CommonJS module in the `main` field of `package.json` and an ES module in the `module` field. A perfect example of this is semantic-ui-react.

I think it is a little awkward having two separate packages for CommonJS and ES exports. I think it would be useful to have a build that unifies the two, now that it is possible.

I know this is a long shot, especially because I can just as well use babel-plugin-lodash, but I was just curious, would a setup like this make sense for the future?

**Comment by jdalton** [comment]
Hi @andrewpeterprifer!

I'm trying to cut file size of our npm package for the v5 release. It's currently over 4mB because of all of the various builds. For v5 I'm going to ship an ESM only build using [`esm`](http://npmjs.com/esm). You can use `esm` as well to ship just ESM for Node 6+.

**Comment by andrewpeterprifer** [comment]
@jdalton thank you for bringing esm to my attention! :) That sounds really good.
