### ISSUE TITLE
Make a tiny optimization in `baseIsEqual()`

### ISSUE THREAD

**Issue by silent-tempest** [lodash/lodash#3874]
Look at the first part of the condition (`value == null || other == null`):
```javascript
if (value == null || other == null || (!isObjectLike(value) && !isObjectLike(other))) {
  ...
}
```
Then look at the second part: `(!isObjectLike(value) && !isObjectLike(other))`, now imagine this:
```javascript
if (value == null || other == null || ((value == null || typeof value != 'object') && (other == null || typeof other != 'object'))) {
  ...
}
```
`value == null` and `other == null` is repeated twice, therefore it is best to use `typeof value != 'object' && typeof other != 'object'`.

**Comment by NeetishRaj** [comment]
Yes looks like few extra condition check of 
value == null
can be avoided there

**Comment by jdalton** [comment]
Hi @silent-tempest!

Thanks for the suggestion. It's a balance between readability and unrolling for sure. Moving forward though I'd like to defer to Node's builtin comparison method [`util.isDeepStrictEqual()`](https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_util_isdeepstrictequal_val1_val2).
