### ISSUE TITLE
Tarball files is missing

### ISSUE THREAD

**Issue by ThemeSama** [lodash/lodash#3878]
Hi! I looking your https://registry.npmjs.org/lodash/ and tarball files is missing after than https://registry.npmjs.org/lodash/-/lodash-4.14.0.tgz

Last available tarball file is https://registry.npmjs.org/lodash/-/lodash-4.13.1.tgz

I can't install ember-cli
10894 http fetch GET 403 http://registry.npmjs.org/lodash/-/lodash-4.17.10.tgz 3336ms

What can I do?

Regards,
Themesama

**Comment by jdalton** [comment]
Hi @ThemeSama!

I guessing it's a temporary npm hiccup. There's certainly nothing we can do on our end.
