### ISSUE TITLE
Potential Bug: _.has() with property names that include square brackets

### ISSUE THREAD

**Issue by ZechyW** [lodash/lodash#3879]
Hi,

I'm trying to test for the existence of a property whose name contains square brackets, but _.has() is checking for the property with the square brackets stripped instead.
That is:
```
const test = {
  foo: "bar"
};
console.log(_.has(test, "foo"));
console.log(_.has(test, "[foo]"));
```
Output:
```
true
true
```
I'm not sure if this is intended behaviour or counts as an edge case, but if it is intended, perhaps the documentation could be updated to describe it somewhere?

Thanks!

**Comment by jdalton** [comment]
Hi @ZechyW!

That's part of our deep path syntax that is supported (_brackets and dots)_, 
e.g. `_.has(test, "a.b[c]")`.

**Comment by ZechyW** [comment]
Hi @jdalton,

Got it, thanks for the clarification!
