### ISSUE TITLE
isEmpty issues with FormData

### ISSUE THREAD

**Issue by eloytoro** [lodash/lodash#3880]
In a browser `_.isEmpty(new FormData())` returns `true` for all cases.
But when using the `form-data` polyfill in node it returns `false` for all cases

**Comment by jdalton** [comment]
Hi @eloytoro!

I'm guessing the polyfill puts enumerable properties on an the data object where the builtin one doesn't. You might file a bug on the polyfill to be a bit closer to the builtin in that regard.
