### ISSUE TITLE
Can we have a new release?

### ISSUE THREAD

**Issue by BlindDespair** [lodash/lodash#3881]
It looks like it's been a while since last release was published to npm. There are quite many new commits. It would be nice to have them a live if possible. I am personally interested about custom comparators for orderBy introduced [in this commit](https://github.com/lodash/lodash/commit/79dc90dfcb743b57d348a0ac134ff9694ae937e7). I tried to google if there is release planned, but didn't find any info, there creating an issue.

**Comment by jdalton** [comment]
Hi @BlindDespair!

The commit you referenced is in a v5 branch and won't be in v4. Any release coming out until the v5 release will be v4 patches (mostly bug fixes).
