### ISSUE TITLE
Prototype pollution

### ISSUE THREAD

**Issue by Berkmann18** [lodash/lodash#3882]
`npm audit` flagged a lot of vulnerabilities that traced back to this package with the following report: https://nodesecurity.io/advisories/577

**Comment by jdalton** [comment]
Hi!

The disclosure shows the range to use to get the patched version

**Comment by jdalton** [comment]
Hi!

The disclosure shows the range to use to get the patched version

**Comment by Berkmann18** [comment]
What? That doesn't make sense and there's no patched version released.

**Comment by jdalton** [comment]
There is a patched release. The current released version is 4.17.10. The disclosure says to use
> Update to version 4.17.5 or later.

**Comment by Berkmann18** [comment]
The thing is that it affects v4.17.10 as well as v4.17.5.

**Comment by jdalton** [comment]
Maybe you've found a different issue than the one covered by that specific report. That specific one was verified fixed by the patch.

**Comment by jdalton** [comment]
It sounds like you're wanting to disclose a potential security issue. I'd encourage you to do so through emailing `security@lodash.com`.

**Comment by Berkmann18** [comment]
You're probably right, I'll clone this package and try to look deeper.

**Comment by Berkmann18** [comment]
I've sent the email to the address you gave with the report and some of the things I did to attempt to resolve all issues.
