### ISSUE TITLE
Direct import of sortBy in 4.17.10 throws Error

### ISSUE THREAD

**Issue by igorski** [lodash/lodash#3886]
Consider the following example:

```
const list = [
    { category: 'b', variant: 0 },
    { category: 'a', variant: 1 }
];
```

When importing the entirety of lodash, it works as expected when invoking:

```
import _ from 'lodash';
const result = _.sortBy(list, ['category', 'variant']);

// result being:
// [{ category: 'a', variant: 1 }, { category: 'b', variant: 2 }];
```

When importing solely the sortBy method:

```
import sortBy from 'lodash/sortBy';
const result = sortBy(list, ['category', 'variant']);
```

it will throw _TypeError: iteratee is not a function_ in baseOrderBy.

**Comment by jdalton** [comment]
Hi @igorski!

I can't reproduce locally. Usually this error means you're using `lodash-webpack-plugin` and have disabled shorthands (they should be disabled if you want the bundle size savings). You can rework your shorthands into

```js
sortBy(list, [o=>o['category'], o=>o['variant']]);
```
