### ISSUE TITLE
isMatch returns true with empty object or null

### ISSUE THREAD

**Issue by le-frank** [lodash/lodash#3887]
`isMatch( { a: 1 }, {} )` returns `true`
same for `isMatch( { a: 1 }, null )`

If it's not a bug I'd like to suggest it should return `false`

Cheers
Frank

ps: many thanks to everyone involved with Lodash 👍

**Comment by jdalton** [comment]
Hi @le-frank!

I've gone back and forth on this. I'm digging the existing behavior since there is no nothing to match, everything is matched. The matching of the absence of something isn't really what `isMatch` is about.

**Comment by razerduy** [comment]
Same here, 
isMatch( { a: 1 }, {} ) return true
isMatch( {}, { a: 1 } ) return false
