### ISSUE TITLE
Feature Request: _.queue

### ISSUE THREAD

**Issue by poonzah** [lodash/lodash#3890]
Hi,

I think it's good to have a higher-order function to make an async function calls go one by one and keep them in a queue, so if there's still a pending promise from the last call, the new call should wait.
I hope i made my point clear and if it's not clear enough, I already made it work in [this commit](https://github.com/poonzah/lodash/commit/a0c08e2433125561fa77b9dc9d33393f3a02b181).

Any thumbs up for that?

**Comment by StreetStrider** [comment]
@poonzah [async.series](http://caolan.github.io/async/docs.html#series), [bluebird.each](http://bluebirdjs.com/docs/api/promise.each.html).

**Comment by poonzah** [comment]
@StreetStrider they are completely different things. I'm not talking about making an array of tasks in the first place. It's about calling a function again and again, without knowing how many times or where in the code it may happen, and still make them all get invoked one by one FIFO.

**Comment by StreetStrider** [comment]
@poonzah like [async.queue](http://caolan.github.io/async/docs.html#queue)?

**Comment by jdalton** [comment]
Hi @poonzah!

For async functions I usually defer to our friends at `[async](https://www.npmjs.com/package/async)` or one-off packages.
