### ISSUE TITLE
Invalid or unexpected token when key starts with a number

### ISSUE THREAD

**Issue by AlaricCalmette** [lodash/lodash#3892]
Hi!

When I try to use `_.template()` with keys that start with a number, I get this error: `Invalid or unexpected token`

If you try this code: 

```js
const text = "<h1>[[01_foo_bar]]</h1>";
const data = {'01_foo_bar':"foo bar"};
const INTERPOLATE_REGEX = /\[\[([\s\S]+?)\]\]/g;
compiled = _.template(text, {interpolate: INTERPOLATE_REGEX});
result = compiled(data)
```

You'll get the error. However, the `INTERPOLATE_REGEX` match this key and if you just remove the first three characters `01_` it works perfectly.

I'd expect the `template` function to work the same regardless of how the keys are formed.

**Comment by jdalton** [comment]
Hi @AlaricCalmette!

That's because JS variable identifiers cannot start with numbers. However, you can reference them from the data `obj["01_foo_bar"]` (you customize the `obj` var name via the `variable` option).
