### ISSUE TITLE
omit: Property 'x' does not exist on type 'Pick<Y, never>'.

### ISSUE THREAD

**Issue by envil** [lodash/lodash#3893]
I'm using lodash-es in my Angular (with NgRx) application. While call the omit function, the build is broken. Here is how I'm using it:

```
import omit from 'lodash-es/omit';
...
export class SomeEffects {
...
  @Effect()
  someEffect$ = this.actions$
    .ofType(action.SOME_ACTION)
    .concatMap((action: action.SOME_ACTION) => {
      const payload = omit(action.payload, ['accounts', 'superiors']);
      // ERROR occurred at the following line durring the build:
      payload.status = SomeEnum.SomeValue;
      ...
    });
...
}
```

> ERROR: Property 'status' does not exist on type 'Pick<FooType, never>'.

If I change this line:

```
const payload = omit(action.payload, ['foo', 'bar']);
```
to
```
const payload = pick(action.payload, ['prop1', 'prop2', 'prop3', ...]);
```

Then the problem is gone. Did I do something wrong or this's a bug?

**Comment by jdalton** [comment]
Hi @envil!

With subclassed values omitting can be tricky since it has to clone everything to omit a few things where as `pick` will simply pluck requested values.
