### ISSUE TITLE
Idea: sumBy return dictionary to increase performance

### ISSUE THREAD

**Issue by gil-m** [lodash/lodash#3895]
Let the user inform more than one property for the sumBy function, thus keeping him from calling sumBy multiple times and having multiple iterations, which takes more time to finish the task.

That's the same of doing:
```
for (let item of array){
    sum_a = sum_a + item.a;
    sum_b = sum_b + item.b;
    sum_c = sum_c + item.c;
}
```

Instead of:
```
for (let item of array)
    sum_a = sum_a + item.a;
for (let item of array)
    sum_b = sum_b + item.b;
for (let item of array)
    sum_c = sum_c + item.c;
```

**Comment by jdalton** [comment]
Hi @gil-m!

This sounds like the making of a different method. Could you flesh out a full implementation and see where that takes you?
