### ISSUE TITLE
Evaluate behavior of isEmpty

### ISSUE THREAD

**Issue by samuelpadua** [lodash/lodash#3896]
I was testing something quite simple in my app, and I noticed that the `isEmpty` method might have a small flaw in one type of validation.
When the value of a variable or property of an object is zero, it returns that the input is empty
Ex:
```js
const number = 0
const obj = {
   number: 0
}

_.isEmpty(number) // true
_.isEmpty(obj.number) // true
```
Is this an expected behavior of the method?

Thanks!

**Comment by daedalus28** [comment]
This behavior is why we added `isBlank` to `futil-js`. If this is changed in lodash, we would happily deprecate it! In the meantime, you're welcome to use `isBlank` while we wait for @jdalton to comment.

https://github.com/smartprocure/futil-js#isblank
https://smartprocure.github.io/futil-js/#api-lang-isblank
https://github.com/smartprocure/futil-js/blob/master/src/lang.js#L17

**Comment by robludwig** [comment]
Per the docs, `_.isEmpty`

> Checks if value is an empty object, collection, map, or set.
> Objects are considered empty if they have no own enumerable string keyed properties.

Numbers have no own enumerable string-keyed properties so they are empty

**Comment by daedalus28** [comment]
Great point - that also holds true for boolean values, so `_.isEmpty(true)` returns true as well. Same for plain functions.

@samuelpadua If you'd expect `0`, `true` and `() => {}` to not be empty, it sounds like you're thinking in terms whether not something has a value, which is the use case of `isBlank`. Based on the docs it seems like this will not change in lodash, so I'd recommend using `isBlank`.

**Comment by jdalton** [comment]
Hi @samuelpadua!

See #3201.
