### ISSUE TITLE
Wrong sorting on alphanumeric string like "site 1", "site 19", "site34", "4site"etc. using _orderBY

### ISSUE THREAD

**Issue by BigShanJohn** [lodash/lodash#3898]

**Comment by BigShanJohn** [comment]
hello, i am getting wrong value by using  return _.orderBy(records, key, order);  
records is [{a: "site 1"}, {a: "site 11"}, {a: ' site 2'}, {a: "site 3"}, {a: 'site23me'}, {a: 'site9'}];

**Comment by BigShanJohn** [comment]
does _lodash support mixed alpha/numberic sorting?

**Comment by jdalton** [comment]
Hi @BigShanJohn!

You'll want to provide an iteratee (instead the `key` shorthand) that returns a value that can be sorted.
