### ISSUE TITLE
When using .remove on array, splice is avoided causing array to not be reactive in vue

### ISSUE THREAD

**Issue by maritaria** [lodash/lodash#3900]
When you perform _.remove() on an array that contains only one element then instead of calling splice the array unsets the 0 property path. This causes bindings in vue to not react to this change.

**Comment by jdalton** [comment]
Hi @maritaria!

Lodash isn't especially Vue friendly. Vue monkey patches arrays to try to wire-up its two-way data binding and falls a bit short. Our use of arrays is valid so this is more of a Vue issue and not a Lodash issue.
