### ISSUE TITLE
mergeWith: get the current path inside customizer function

### ISSUE THREAD

**Issue by SachaG** [lodash/lodash#3901]
Let's say I'm trying to merge these two objects:

```
{
 a: {
    list: [1, 2, 3]
 },
 b: {
   list: ['foo', 'bar', 'baz']
 }
}
```

and

```
{
 a: {
    list: [4, 5, 6]
 },
 b: {
   list: ['foo', 'baz']
 }
}
```

In my use case, I would like to define different merging behaviors for `a.list` and `b.list`. For example, I'd like to concatenate `a.list` (resulting in `[1, 2, 3, 4, 5, 6]`) while overwriting `b.list` (resulting in  `['foo', 'baz']`).

One idea I had to accomplish this was to check for the current path (whether it's `a.list` or `b.list`) inside my merge customizer function. The issue is that I don't know how to access that path…

I did see that the `stack` argument had getter and setter functions which let you pass data from one iteration of the customizer function to the next but I wasn't able to figure out how to use them properly. 

Any help will be appreciated, thanks!

**Comment by jdalton** [comment]
Hi @SachaG!

Please head over to our [gitter chat](https://gitter.im/lodash/lodash) for assistance.

**Comment by SachaG** [comment]
Are questions not allowed in issues? Can I still direct people here if they want to provide an answer?

**Comment by jdalton** [comment]
Sure, feel free to post back if you find an acceptable solution.

**Comment by stambata** [comment]
Hi @SachaG! Did you manage to find a solution? I needed the exact same functionality but also couldn't figure out how to achieve it by using the `stack` argument. 
I  managed to do it though but I had to wrap the `lodash.mergewith` function:
```js
const mergeWith = require('lodash.mergewith');

const merge = (...objects) => {
    const stack = [];
    return mergeWith(...objects, (targetVal, sourceVal, key, target, source) => {
        var path;
        while (true) {
            if (!stack.length) stack.push({source, path: []});
            const prev = stack[stack.length - 1];
            if (source === prev.source) {
                path = prev.path.concat(key);
                stack.push({source: sourceVal, path});
                break;
            }
            stack.pop();
        }
        // here path is an array of the keys (in nesting order) pointing to sourceVal
    });
}
```
