### ISSUE TITLE
attempt + default value

### ISSUE THREAD

**Issue by sreevisakh** [lodash/lodash#3903]
a function to like attempt which will catch error and return a default value if there is an error. lot of try catch statements can be reduced to single lines

eg:
### without
```js
try{
  value = JSON.parse(str);
}
catch(e){
  //dont care
  value = [];
}
```
### with
```js
value = attempt(JSON.parse.bind(null, str), [])
//or
value = attempt(JSON.parse, [str], [])

```

**Comment by jdalton** [comment]
Hi @sreevisakh!

I've wanted something like that myself though I usually handle it with one off `tryXyz` methods now.
That said I could see this as something like an `_.attemptOr` method.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by biiiipy** [comment]
I'm actually **very** surprised that there is not a simple function for this. I assumed that lodash 100% has this

**Comment by Tonkonozhenko** [comment]
Hi
It was also strange for me that it's not supported by default. Our use case is parsing a string to JSON with fallback to the default

**Comment by wojtiku** [comment]
+1, this would be great to have

**Comment by kyrylo-soulandwolf** [comment]
+1
