### ISSUE TITLE
unescape should also handle &#039

### ISSUE THREAD

**Issue by AndrWeisR** [lodash/lodash#3904]
Currently, the lodash unescape function only unescapes &#39 for apostrophe. It should also handle &#039, as some escapings use this sequence with a leading zero.

Current code in lodash.js:
`var reEscapedHtml = /&(?:amp|lt|gt|quot|#39);/g,`

**Comment by jdalton** [comment]
Hi @AndrWeisR!

If you're looking for more thorough encoding/decoding you should use [`he`](https://www.npmjs.com/package/he).
