### ISSUE TITLE
Need more examples on the front page

### ISSUE THREAD

**Issue by techtonik** [lodash/lodash#3908]
I am Python guy, who needs to process some text in JavaScript, so I was referenced to this library. However, the front page lacks a newbie examples for people like me, who just want to see how to use Python's `"highdash!\n".strip('!\n').replace('high', 'lo')` convention in JavaScript.

**Comment by Berkmann18** [comment]
Have you checked the [website](https://lodash.com)?

**Comment by techtonik** [comment]
I already choose another way. Copy/paste, no library. =) Website says it is delivering "modularity, performance & extras." so I thought it is some kind of plugin system. Two examples at the top are only about collections. "modular methods" sound like working with modules.

**Comment by Berkmann18** [comment]
Fair enough.
