### ISSUE TITLE
Adding declaration files for modules

### ISSUE THREAD

**Issue by athJ** [lodash/lodash#3909]
When I am using Lodash in VS code and importing individual submodules I am getting this message ,
I don't have any issue with the functionality .My code runs perfectly 
<img width="502" alt="screen shot 2018-08-14 at 4 54 53 pm" src="https://user-images.githubusercontent.com/16134050/44088992-d211e006-9fe2-11e8-8fb6-f59b5b98c660.png">

**Comment by jdalton** [comment]
Hi @athJ!

Might be a vscode hiccup. It usually handles these kinds of typings automagically (I assume) without Lodash having to do anything.
