### ISSUE TITLE
Group By with multiple keys

### ISSUE THREAD

**Issue by bernardocs** [lodash/lodash#3910]
Hey there!

Is there any way to groupBy a collection of objects that are identified by 3 of those properties?
Sample format:
```javascript
const arr = [
  { key1: 123, key2: 'abc', key3: 'a1b2'  /* ... other properties */ },
  // ...
];
```

Right now I can achieve a similar desired result by doing:
```javascript
_.groupBy(arr, obj => {
  const keys = [obj.key1, obj.key2, obj.key3];
  return _.compact(keys).join(':'); // that's because some may be empty
});
```
And that would group by the stringified keys separated by `:` (`'123:abc:a1b2'` would be one of the keys, using the sample)...

Is there any way of doing this in a more _clean_ way?

**Comment by jdalton** [comment]
Hi @bernardocs!

This is a great question for our [gitter chat](https://gitter.im/lodash/lodash). Please feel free to post back any results from the chat.
