### ISSUE TITLE
getIteratee is not defined when using lodash-cli to create custom build 

### ISSUE THREAD

**Issue by teddycoleman** [lodash/lodash#3911]
lodash version: `4.17.5`

command: `lodash core plus="get,set,cloneDeep,omit,method,union,includes,findKey,pickBy,uniq,uniqBy,intersection,isInteger" exports="global" -d`

In the file generated, getIteratee is not defined, but is called twice (see below). Can you please update to include the function definition? Thanks in advance!

```
  arrayEach(['filter', 'map', 'takeWhile'], function(methodName, index) {
    var type = index + 1,
        isFilter = type == LAZY_FILTER_FLAG || type == LAZY_WHILE_FLAG;

    LazyWrapper.prototype[methodName] = function(iteratee) {
      var result = this.clone();
      result.__iteratees__.push({
        'iteratee': getIteratee(iteratee, 3),
        'type': type
      });
      result.__filtered__ = result.__filtered__ || isFilter;
      return result;
    };
  });
```

```
  LazyWrapper.prototype.reject = function(predicate) {
    return this.filter(negate(getIteratee(predicate)));
  };
```

**Comment by jdalton** [comment]
Hi @teddycoleman!

Development on `lodash-cli` is archived for the time being. You can try using an earlier version to see if that resolves your issue.
