### ISSUE TITLE
_.sumBy() returns boolean if iterating on an array of 1 element

### ISSUE THREAD

**Issue by Kleemer** [lodash/lodash#3912]
Hi,
First of all thanks for the library !

I am using the _sumBy function, and today I just found out that if it's used with an array of one element, it will return a boolean instead of a number, see this CodePen :
https://codepen.io/Kleemer/pen/oMrVeG
When it iterates in a list of more than one element then even if the answer is 1 (or 0) it won't return a boolean, I was just wondering if this is an expected behaviour ?

Thanks !

**Comment by falsyvalues** [comment]
Hi @Kleemer!

In both case I get 4 as a result:
```
var objects = [{ 'n': 4 }];
 _.sumBy(objects, function(o) { return o.n; });
// => 4
 
// The `_.property` iteratee shorthand.
_.sumBy(objects, 'n');
// => 4
```

**Comment by jdalton** [comment]
@Kleemer In your example you're summing by a boolean `.active`. When you add multiple booleans together they coerce to numbers.

**Comment by falsyvalues** [comment]
@Kleemer You can simply fix that by doing:

```
result = _.sumBy(users, (user) => {
  return user.active ? 1 : 0
})
```

**Comment by Kleemer** [comment]
I see !
I guess I was confused by the documentation that specifies that this function will return a number, it looks weird that it returns a boolean but at least I see why now. Maybe the documentation should make that more explicit ?
For now I'll use this workaround indeed, thanks !

**Comment by falsyvalues** [comment]
@StreetStrider 😍
