### ISSUE TITLE
_.lowerCase('#') issue

### ISSUE THREAD

**Issue by sanyamagrawal** [lodash/lodash#3913]
Hi Team , 

When I try to execute this _.lowerCase('#') command , it returns me an empty string. 
Any reason why it does so , is this an expected behaviour?

**Comment by SaleemManjoo** [comment]
It does not return an empty string. It returns a single space (" "). That is expected behaviour for that function, and it will behave the same with any symbol. 

If you want the symbols to remain, use _.toLower() instead.
