### ISSUE TITLE
Implement function(s) to check for duplicates in array

### ISSUE THREAD

**Issue by lloydjatkinson** [lodash/lodash#3915]
Currently there are uniqueness functions such as `uniq`, `uniqBy`, `uniqWith`. These return a new duplicate free array based on the given array.

This proposal is for a new set of functions that will simply return a boolean indicating if the given array contains unique values or not.

```
containsUniq()
    Arguments
        array (Array): The array to inspect.
    Returns
        (Boolean): Returns true if the array only has unique items.

containsUniqBy():
    Arguments
        array (Array): The array to inspect.
        [iteratee=_.identity] (Function): The iteratee invoked per element.
    Returns
        (Boolean): Returns true if the array only has unique items.

containsUniqWith():
    Arguments
        array (Array): The array to inspect.
        [comparator] (Function): The comparator invoked per element.
    Returns
        (Boolean): Returns true if the array only has unique items.
```

Example usage:

```
const unique = [1, 2, 3, 4, 5];
const notUnique = [1, 1, 2, 3, 4, 5];

containsUniq(unique) // true
containsUnique(notUnique) // false

const uniqueObjects = [
    { name: 'A', value: 1 },
    { name: 'B', value: 2 },
    { name: 'C', value: 3 },
];

const notUniqueObjects = [
    { name: 'A', value: 1 },
    { name: 'B', value: 2 },
    { name: 'A', value: 1 },
];

containsUniq(uniqueObjects) // true
containsUnique(notUniqueObjects) // false
```

`containsUniqBy` and `containsUniqWith` work on the same principle as `uniqBy` and `uniqWith`.

**Comment by jdalton** [comment]
Hi @lloydjatkinson!

I'm not too keen on adding these kinds of methods but I'll leave it up to user-demand for such things.
We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by lloydjatkinson** [comment]
That's a shame. What is the reasoning for something is common as this?

**Comment by jdalton** [comment]
> What is the reasoning to reject something as common as this

I believe this is the first request for this kind of functionality _(maybe not so common)_. Holding out for user feedback (please read the link in my comment) is not a hard rejection _(you'd see a `wontfix` if it was that)_.

**Comment by lloydjatkinson** [comment]
OK thanks. One use case would be for validating user input by not allowing duplicate entries in a form.

For now a work around is `_.difference(a, _.uniqBy(a, 'name')).length`.

**Comment by lloydjatkinson** [comment]
Hang on, how is anyone going to vote if the issue is closed? People don’t usually search closed issues.

**Comment by TAGC** [comment]
This seems like it would be a nice addition.

**Comment by c-dante** [comment]
@lloydjatkinson, you can also solve your uniq problem by just doing `_.uniqBy(a, 'name').length === a.length`, no need to also compute the diff of the array.

**Comment by TAGC** [comment]
@c-dante Wouldn't that potentially be a lot less efficient, though? If you had a function that specifically checked whether a sequence contained only unique values, you could make it return early as soon as it encounters a repeat element.

Doing the check the way you recommend would involve going through the entire sequence even if non-unique elements are encountered right at the start.

**Comment by c-dante** [comment]
Depends on the set. When doing the uniq, no matter what you're keeping track of everything you visited, so in the worst case (when it is in fact distinct) you're going to be duplicating the set.

I think this isn't really a thing for lodash to solve, unless it wants to expose its inner uniq functionality. There's *probably* space for a simple boolean check, but it's no different from you just running:

```js
const isDistinct = (arr, accessor) => {
  const set = new Set();
  for (item of arr) {
    const c = accessor(item);
    if (set.has(c)) return false;
    set.add(c);
  }
  return true;
}
```

So, it really depends on your data for this "duplicate check" function. There's just not much use in knowing "yes, this set has duplicates" vs other things like, "which indexes are duplicates" or "what are the duplicate sets", etc.

I can't think of many instances where you're working on a large set to determine if it's already distinct that just computing uniq and using the result isn't better.

**Comment by lloydjatkinson** [comment]
`I think this isn't really a thing for lodash to solve`.

I mean, it's already doing that *harder* part of it by returning a collection of duplicate items. A simpler bool check should be much less work.

**Comment by c-dante** [comment]
Lodash isn't here to compute every desired property of a collection. In any case, the policy for adding new features/functions to the api is pretty clear. See if enough people need this in lodash vs throwing together their specific use case if the `uniq` + `length` compare doesn't suit their needs.

**Comment by lloydjatkinson** [comment]
`Lodash isn't here to compute every desired property of a collection.`

So by that logic, why do the `uniq` set of functions even exist to begin with?

` In any case, the policy for adding new features/functions to the api is pretty clear.`

Yes, it is clear the maintainers do not wish to work on the library further.

**Comment by c-dante** [comment]
Okay, I'm out of this discussion because you're not quite understanding how a well maintained codebase avoids things like scope creep and bloat, and you seem to be fixated on the idea that your use case isn't adequately solved by the toosl provided. [There is a very clear process for feature requests](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), which has been identified to you.


I'm sorry that this very successful and well maintained library that is very much a cornerstone to most javascript projects has let you down. Good luck out there, buddy.

**Comment by jdalton** [comment]
Let's keep it positive folks.

@lloydjatkinson As we progress to more ES6 implementations it's tempting to simplify `uniq` down to `[...new Set(array)]`. This is great but it doesn't provide the boolean result you're looking for. This means implementing a uniq like method to do that. It would make more since if it was required to implement `uniq` (we could just extract it out). In addition, we currently have 3 uniq-related methods (`uniq`, `uniqBy`, and `uniqWith`) and I'm not excited about adding 3 more variations for this use case. This is why I'm OK waiting for user-interest (by way of 👍 reactions) to increase before considering it.

**Comment by ManishJainGitHubUser** [comment]
+1 for isDuplicate function. I need it all the time.
