### ISSUE TITLE
[Meta] Keep issues open while in voting phase

### ISSUE THREAD

**Issue by Inzanit** [lodash/lodash#3916]
It isn't particularly useful to close issues that are deemed necessary to have votes cast on them. A vote usually implies there will be a decision _after_, not prior to the vote. It makes finding existing issues, which may duplicate what I want to suggest, harder to find and will lead to me not voting on an original issue someone is already waiting for votes on.

I propose you no longer just close issues and wait for them to actually be voted on, after a while, make the call to close or pursue the issue.

**Comment by jdalton** [comment]
Hi @Inzanit!

I'm not a fan of polluting the issue tracker with hundreds or thousands of open feature requests. I'll close them since they are not actionable and are used as just a metric for me to gauge user interest.

**Comment by Inzanit** [comment]
But that's my point, you cannot gauge user interest from closed issues? @jdalton

**Comment by lloydjatkinson** [comment]
How do you expect to gauge interest when the community can’t even see the issue? People in general are used to open issues as “active and can engage with” and closes issues as “gone and can no long engage with”.

**Comment by jdalton** [comment]
GitHub allows sorting issues by label and reaction. So for gauging interest I use [this query](https://github.com/lodash/lodash/issues?utf8=%E2%9C%93&q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc+).

**Comment by jdalton** [comment]
This btw is covered in our [contributing text](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) and linked to in most all `votes needed` issues.
