### ISSUE TITLE
takeRightWhile

### ISSUE THREAD

**Issue by McsNick** [lodash/lodash#3918]
example:
```
var users = [
  { 'user': 'barney',  'active': true },
  { 'user': 'fred',    'active': false },
  { 'user': 'pebbles', 'active': false }
]
_.takeRightWhile(users, ['active', true])
```

The result of the output is []

**Comment by elhesuu** [comment]
From the docs:
> Creates a slice of array with elements taken from the end. Elements are taken until predicate returns falsey

**Comment by McsNick** [comment]
I understand , thanks!
