### ISSUE TITLE
array selection in "path" is better to support wildcard.

### ISSUE THREAD

**Issue by wjh000123** [lodash/lodash#3919]
Hi,

I have a object like this:

```javascript
{
  id: 123,
  title: 'ok, this is title',
  content: 'this is content',
  updatedAt: '2018-08-22',
  author: {
    id: 3322,
    name: 'Bill',
    level: 'high'
  },
  comments: [{
    id: 1,
    description: 'cool~',
    createdAt: '2018-08-20'
  }, {
    id: 2,
    description: 'awesome',
    createdAt: '2018-08-21'
  }]
}
```

What I'm going to do is to define a group of private fields. Using `omit`, for instance, I can define the `path`as `'id, updatedAt, author.id, comments[*].createdAt, comments[*].id'`, but it's not work for sub collection(the `comments` part).

I know I can implement it myself, it's better if `path` in `omit` supports deep collection.

Thanks!

**Comment by jdalton** [comment]
Hi @wjh000123!

This gets into a weird space as a path can normally be translated into a single file property path. With an `*` you end up with unlimited possibilities so it can no longer be translated into a single path. I think this would be a better fit as a custom implementation.

**Comment by wjh000123** [comment]
Hi, @jdalton 

The path should have been `string[]`, it's my fault. The wildcard was just an option, another solution could be `comments[].id`. The point is to **be able to select all sub elements in some array**, now the path only supports element at the specific index.

For example, current path supports, `['id', 'updatedAt', 'author.id', 'comments[0].createdAt', 'comments[0].id', 'comments[1].createdAt', 'comments[1].id']`, which means I have to tell the max index of comments, and add all sub elements' index to the array, like `[0]`, `[1]`.

What if **`someArray[].property1`**, **`someArray[].property2`** or something like that, means all sub elements of comments should be matched.

Thanks!
