### ISSUE TITLE
lodash support for .NET

### ISSUE THREAD

**Issue by joshstevens19** [lodash/lodash#3920]
Hi i use your library for all my JavaScript projects, was wondering has a .NET implementation been written or supported by yourself? If not would you guys be open if someone wrote one and had it under the lodash namespace?

Thanks
Josh

**Comment by jdalton** [comment]
Hi @joshstevens19!

I did a quick search and found that someone has created a Lodash flavor for .Net. See [this](https://github.com/shirbr510/lodash.net).

**Comment by joshstevens19** [comment]
Hey mate, 

Well in fact that library is not good at all, it is lacking in most aspects. My main question was if i developed a really useful one for .NET would you guys ever consider listing it under lodash namespace?

**Comment by jdalton** [comment]
Ah, sorry! 

I'm OK with Lodash-like libraries for other languages but the JS Foundation holds the trademark for "Lodash" so I wouldn't be OK with another language utility library calling itself "Lodash" too. I'm not interest-in or have-the-bandwidth-for maintaining Lodash implementations for other languages. That said, feel free to create your own utility library for .Net inspired by Lodash. That's super rad!

**Comment by joshstevens19** [comment]
That is cool thanks for letting me know. Was hoping to help with lodash but seems you have everything covered. Unless there is any tasks which you need help with? 

If there are any GitHub repos you need any free help with give me a shout 👍
