### ISSUE TITLE
_.isAsyncFunction

### ISSUE THREAD

**Issue by pecliu** [lodash/lodash#3923]
What about to add a new method like _.isAsyncFunction to check whether the function is an async function ?
Like MDN' doc: [AsyncFunction](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction)

```js
function isAsyncFunction (value) {
  return value && value.constructor && value.constructor === Object.getPrototypeOf(async function(){}).constructor
}
```

**Comment by jdalton** [comment]
In more recent Node releases there is `util.types.isAsyncFunction()`. There are a few function variants _(async, generator, async generator)_ that I have punted on resolving. You can also do:
```js
Object.prototype.toString.call(asyncFnc) === '[object AsyncFunction]'
```

**Comment by pecliu** [comment]
@jdalton Thank you so much!
