### ISSUE TITLE
Add docs for edge cases: slice with end > array.length

### ISSUE THREAD

**Issue by jagij** [lodash/lodash#3927]
When slice is called with end > array.length, array.length is used (which is expected).

I'd like to be able to read this in the [docs](https://lodash.com/docs/4.17.10#slice), instead of reading it in the [sources](https://github.com/lodash/lodash/blob/4.17.10/lodash.js#L4072).

Since it currently isn't documented, I'm obliged to truncate end myself or I'm using undefined (or at least undocumented) behaviour. Because the feature currently is undocumented, it could be removed in a future version, which would break my code if I were to rely on it.

Is there an interest in documenting the edge case behaviour? A negative number (between -array.length and 0) for end is also allowed, for instance.

Is there a repository for the documentation, so people can add pull requests for them too?

**Comment by jdalton** [comment]
Hi @jagij!

I want to keep our docs on `slice` light since it's just a dense array producing form of [`Array#slice`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) _(linked to in the docs)_.

**Comment by jagij** [comment]
Hi @jdalton !

Oh ok, I didn't interpret the documentation like that. Might I suggest a different wording?

Original:
`This method is used instead of Array#slice to ensure dense arrays are returned.`

Proposed:
`Same as Array#slice, but returns a dense array.`

I actually went and looked at [`Array#slice`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice), but didn't assume the boundary conditions were all implemented alike.
