### ISSUE TITLE
Unclear fp documentation section https://github.com/lodash/lodash/wiki/FP-Guide#exceptions-to-the-rules

### ISSUE THREAD

**Issue by DenyVeyten** [lodash/lodash#3929]
I'm trying to convert `invokeMap` to `invokeArgsMap` with no success

Code example
```
const _ = require('lodash');
const fp = require('lodash/fp');

const data = [[1], [2]];
console.log(_.invokeMap(data, 'map', v => v * 2)); // [[ 2 ], [ 4 ]]
console.log(fp.invokeArgsMap(v => v * 2)('map')(data)); // error
```

`invokeArgsMap` has fixed arity of three, so I'm using the same pattern as from example for `padCharsStart`

But there is exception in section below: `Methods that expect an array as their last or only argument:`
This is unclear note for me, could you please give an example for this exception?

Thanks!

**Comment by jdalton** [comment]
Hi @DenyVeyten!

The `invokeArgsMap` method accepts `(method,args,data)`:
```js
fp.invokeArgsMap('map', [v => v * 2], data)
```
