### ISSUE TITLE
Include extra combining ranges

### ISSUE THREAD

**Issue by dracos** [lodash/lodash#3930]
rsComboRange  in UnicodeSize.js does not include the Combining Diacritical Marks Extended (1AB0–1AFF) and Combining Diacritical Marks Supplement (1DC0–1DFF) ranges – I'm guessing these should also be included?

**Comment by jdalton** [comment]
Hi @dracos!

Maybe! Can you explain a bit how they're used and what they would map to for our [_.deburr](http://lodash.com/docs/#deburr) method.

**Comment by dracos** [comment]
I didn't realise you defined the ranges in multiple places, sorry. They're combining marks in the same way as the ones in e.g. \u0300-\u036f - see e.g. page 8 of https://www.unicode.org/L2/L2011/11202-n4081-teuthonista.pdf . And for example, 1DC0 is http://www.fileformat.info/info/unicode/char/1dc0/index.htm - "COMBINING DOTTED GRAVE ACCENT".
A JavaScript string "\u0041\u1dc0" should have length 1, but lodash's `unicodeSize("\u0041\u1dc0")` is 2.

I imagine this would map to deburr in just the same way, they should be stripped (in fact your documentation for deburr links to a page listing these ranges, so people may assume they're already included :) ).

**Comment by jdalton** [comment]
What would the deburr mappings look like?

**Comment by dracos** [comment]
I'm not sure what you mean? In `deburr.js` where you currently have 

```
const rsComboMarksRange = '\\u0300-\\u036f'
const reComboHalfMarksRange = '\\ufe20-\\ufe2f'
const rsComboSymbolsRange = '\\u20d0-\\u20ff'
const rsComboRange = rsComboMarksRange + reComboHalfMarksRange + rsComboSymbolsRange
```

you would have:

```
const rsComboMarksRange = '\\u0300-\\u036f'
const reComboHalfMarksRange = '\\ufe20-\\ufe2f'
const rsComboSymbolsRange = '\\u20d0-\\u20ff'
const rsComboMarksExtendedRange = '\\u1ab0-1aff'
const rsComboMarksSupplementRange = '\\u1dc0-1dff'
const rsComboRange = rsComboMarksRange + reComboHalfMarksRange + rsComboSymbolsRange + rsComboMarksExtendedRange + rsComboMarksSupplementRange
```

These are extra combining mark ranges, which are removed - there's no need to map them to anything.

**Comment by jdalton** [comment]
See https://github.com/lodash/lodash/blob/4.17.10/lodash.js#L326-L381.

**Comment by dracos** [comment]
The main deburr line is `string.replace(reLatin, deburrLetter).replace(reComboMark, '')`.

Those mappings are for the `reLatin` part, whereas I am talking about adding to the combining mark ranges used in `reComboMark` which does not need any mappings, because they are all mapped to nothing.

**Comment by jdalton** [comment]
Ah great! Would you be up for making a PR?

**Comment by jdalton** [comment]
Moved to #3932.
