### ISSUE TITLE
setWith/baseSet customizer: not enought information from provided arguments

### ISSUE THREAD

**Issue by wvh** [lodash/lodash#3931]
Hello,

`baseSet` takes a _customizer_ function that can set the object for path elements that don't exist. If the newValue is undefined, `baseSet` looks at the next path element and creates either an empty object or array.

The problem is that the custom function has no access to the path, so it can't know if it needs to create an array or object to emulate the default way `baseSet` works.

What I'm really trying to do is use `setWith` to invoke Vue.set() to insert an empty object/array instead of a bare empty object `{}`, because Vue needs some magic to detect new keys and stay reactive.

It would be helpful if the _customizer_ function would also be able to know if it needs to provide an object or an array, and I don't think there's a way to do that with the current arguments.

**Comment by jdalton** [comment]
Hi @wvh!

The customizer has access to the `key` though. You can wrap your `setWith` use to keep a breadcrumb of the traversed keys to track your way through the property path.
