### ISSUE TITLE
_.explode

### ISSUE THREAD

**Issue by cztomsik** [lodash/lodash#3933]
It would be great if there was `_.split` alternative which is consistent with `.join` so you could:

```
const arr = ['one', 'two']

assert.strictDeepEquals(_.explode(arr.join(' '), ' '), arr)
```

**Comment by jdalton** [comment]
Hi @cztomsik!

Can you explain where `String#split` fails your scenario?

**Comment by cztomsik** [comment]
Hi!
Sorry for that, it would not work for empty array (`arr = []`)
For example `[].join('-').split('-')` gives `['']`

**Comment by jdalton** [comment]
Ah ok. For your use case I think you can continue to use the basic lang APIs and just bail early for empty arrays.
