### ISSUE TITLE
isFlattenable and isArrayLikeObject

### ISSUE THREAD

**Issue by joecox** [lodash/lodash#3935]
Hi!

I have a (somewhat historical) question about `isFlattenable` and the use of `isArrayLikeObject`.  

The context is: I am using [MobX](https://github.com/mobxjs/mobx), and they have something called an `ObservableArray`.  It's an object which has a `length` property.

When I tried using this object as a value in `_.concat`, I observed that it wasn't flattened as I expected. Given its `length` property, it should work fine with `arrayPush`.  Investigating why, I found the `isFlattenable` utility and its `spreadableSymbol` check.

Unfortunately, the `ObservableArray` doesn't support `isConcatSpreadable` yet, for some [stated reasons](https://github.com/mobxjs/mobx/issues/1490#issuecomment-379812490).  There are [concrete indications](https://github.com/mobxjs/mobx/commit/109eaf4a47e5e057bd5f0999364521078266cdaf#diff-011c6ab8f1ccbfa906d790a35a44dfd3) that MobX will support the symbol in their next major release, which will resolve this surprise.

But I also found that `isFlattenable` [used to support](https://github.com/lodash/lodash/commit/05c32044e970cd04f9c8422531217e9a9af77b4f) array-like objects in general (a check that `ObservableArray` fulfills).  What was the reason that this condition was removed?

**Comment by jdalton** [comment]
Hi @joecox!

We were aligning with the proposed `Array#flat` proposal at the time. I think it has changed, again, since then though so we should revisit it.
