### ISSUE TITLE
_.has functionality changed in 4.17.5 breaking backwards compatibility

### ISSUE THREAD

**Issue by mike-zipit** [lodash/lodash#3936]
In commit [b6a426a](https://github.com/lodash/lodash/commit/b6a426a10deeacbbaf067cfe45b099153127b9b7), you changed the functionality of `_.has` to be `hasOwnProperty`.  This is not backwards compatible.  

Here's an example:  This function returns the `id` of the passed object.  It supports that `id` being a string, mongo ObjectID, and numeric id:

```
function ToId(obj) {
	if (typeof obj == 'string') return obj;
	if (_.has(obj, '_bsontype')) return obj.toHexString();
	if (typeof obj == 'object' && obj && obj.id) return ToId(obj.id);
	return obj;
}
```

It took way too long for me to track down `if (_.has(obj, '_bsontype'))` no longer works in 4.17.5 as I expected.  

Instead of `_.has` changing to `hasOwnProperty` and `_.hasIn` being the equivalent of 4.17.4 functionality, would it not be more appropriate to:

- `_.has` -- prior functionality
- `_.hasOwn` -- new `hasOwnProperty` functionality

**Comment by jdalton** [comment]
Hi @mike-zipit!

The commits you linked to are in our master branch and not related to v4.
