### ISSUE TITLE
Merge two json objects into single object

### ISSUE THREAD

**Issue by ytliuSVN** [lodash/lodash#3938]
I have two json objects like these:

```
var object = [{name: 'John', age: 23}]
var other  = [{name: 'Wilmer', age: 17}]
```

I want them merge into single json object by using `_.merge` method. I'd rather not use concat().

`[{"name":"John","age":23},{"name":"Wilmer","age":17}]`

but it doesn't contain the destination object. Is there any other way to merge this?

`var finalObj = _.merge(object, other);`

**Comment by jdalton** [comment]
Hi @ytliuSVN!

It doesn't appear `_.mergeWith` will help here.
You might ping our [gitter chat](https://gitter.im/lodash) for ideas.
