### ISSUE TITLE
Poor performance from "uniq" on large arrays in IE11

### ISSUE THREAD

**Issue by reinseth** [lodash/lodash#3939]
When running `uniq` on a large array (e.g. 25k items), the performance is really poor in IE11. Using a crudely written for-loop with an intermediate Set results in much better performance.

See the following jsperf (https://jsperf.com/lodash-uniq-vs-for-loop-and-set/1):
![screenshot-firefox](https://user-images.githubusercontent.com/154842/44991127-74d57680-af93-11e8-89f1-79be37e4b715.png)
![screenshot-ie11](https://user-images.githubusercontent.com/154842/44991200-a2babb00-af93-11e8-8c37-e56671690b3c.png)

The culprits are `baseUniq` and `createSet`. `createSet` becomas a noop function in IE11 since it doesn't support the Set constructor with arguments, and thus `baseUniq` falls back to its own implementation.

I propose to update `createSet` to handle browsers which doesn't support the constructor with arguments.

I'm happy to create a PR if you are open for it.

**Comment by jdalton** [comment]
Hi @reinseth!

This was a design trade off when implementing `uniq`. I didn't want to switch to `set.add` because it was slower than `new Set([....]`, and didn't want to produce a code fork for just IE11. I'm OK with IE11 being slower than a specialized IE11 branch here. You may want to use your own custom implementation to get the right mix of perf and functionality for your browser support needs.

**Comment by reinseth** [comment]
I can understand your reasoning, but it isn't just that it is a bit slower. We have a case at my job where we are transforming an array of plot data and getting unique x coordinates from some 20-50k data points. This works well with other browsers, but with IE11 it took a staggering 25 seconds to calculate. We then rewrote it using regular for loops and an intermediate Set, and the time dropped to 1 s! Which means that lodash's own implementation is completely useless for large datasets.

You might wonder why we would support IE11 at all, but quite a number of our clients are stuck with that browser because of enterprise policies.

A second branch in your feature test of Set in `createSet` will hardly amount to any work or maintenance considering the specificity of the problem, and you do aim to be cross browser, right?

**Comment by jdalton** [comment]
> Which means that lodash's own implementation is completely useless for large datasets.

Naw, it doesn't mean that.

> You might wonder why we would support IE11 at all,

I'm not 
_(I was the performance program manager for the JS engine in IE11, check out my GitHub profile)_

> A second branch in your feature test of Set in `createSet`

I'm not interested in maintaining another branch in that code for just IE11. IE11 will not be supported by Lodash v5 _(shims will enable it though)_. As I said you're likely better off implementing your own more-scenario specific `uniq` anyways. You mentioned you're dealing with coordinates _(that likely means primitives, just numbers)_. You can have a pretty fast `uniq` by using a null-prototypes object as a store:

```js
function uniq(array) {
  var store = Object.create(null)
  var result = []

  var index = -1
  var length = array.length

  while (++index < length) {
    if (! store[index]) {
      var value = array[index]
      result.push(value)
      store[value] = true
    }
  }

  return result
}
```

**Comment by reinseth** [comment]
I forgot to say: thanks for the swift replies.
