### ISSUE TITLE
Feature request: rsplit

### ISSUE THREAD

**Issue by JesseAldridge** [lodash/lodash#3940]
Coming from Python to Javascript, I miss this function.

I'm not the only one. Note the 11 upvotes on this question:
https://stackoverflow.com/questions/5202085/javascript-equivalent-of-pythons-rsplit

Multiple potential implementations are provided in the StackOverflow thread.

**Comment by JesseAldridge** [comment]
Looks like someone took at stab at this at one point:   https://github.com/lodash/lodash/pull/3876/commits/c21ad73b45cfd61cecd2477f1b92d70d0c9f22ed

**Comment by JesseAldridge** [comment]
One obvious usecase is splitting file extensions: "mr. mcgoo.txt"

**Comment by jdalton** [comment]
Hi @JesseAldridge!

This is a dup of #3876. You should give #3876 a 👍 reaction.

**Comment by JesseAldridge** [comment]
@jdalton I'm confused...  you're asking me to 👍 a closed pull requst?
How are people going to become aware that this closed PR is something that they can vote on?

**Comment by JesseAldridge** [comment]
Ok, I see how the system works. Still seems like there might be some discoverability issues, but /shrug
