### ISSUE TITLE
Using map on array of objects breaks breaks in flow (React)

### ISSUE THREAD

**Issue by eaharonoff** [lodash/lodash#3941]
I have an array of objects that I want to map like so:
```
type Person = { 
name: string,
};
...
const content = [ { name: 'jim' }, { name: 'jane' } ];
const people = map(content, (person: Person): React$Element<*> => {
  return (
    <div>
       { person.name }
    </div>
});
```
The error I am receiving is `Cannot call map because Person [1] is incompatible with string [2] in the first argument.`
`     flow-typed/npm/lodash_v4.x.x.js
 [2] 634│       iteratee?: (char: string, index: number, str: string) => any`

So does this mean that I am not supposed to use an object as the iteratee's first argument as it was only intended to have a string as the first argument? If so, is there a lodash method that allows me to return an array, similar to map, that allows for the iteratee's first argument to be an object? Or is it possible to change the flow-typed rules to allow for a object as the iteratee's first argument? I've never contributed but I'd be open to helping out on that front. Thanks in advance!

**Comment by jdalton** [comment]
Hi @eaharonoff!

I'm not much of a flow type expert so you might have better luck asking in a flow chat/slack. You could also try your luck in our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by eaharonoff** [comment]
@jdalton thanks for the response. Keep up the great work, lodash rules!
