### ISSUE TITLE
Add (inc) and (dec) math functions!

### ISSUE THREAD

**Issue by poteat** [lodash/lodash#3945]
By "decrement" we mean decrease by one.  Say you want to decrement all elements of an array:
 (any traversable)

`maxa = _.zipWith(maxa, x => {return x - 1;})`

Currently you need to define your own function.  However, if we add a "math" util function _.dec, we can make the above code arguably more elegant:

`maxa = _.zipWith(maxa, _.dec)`

**Comment by StreetStrider** [comment]
I vote up, but:
```js
x => x - 1
```

**Comment by jdalton** [comment]
Hi @poteat!

Prototype.js had similar methods. As @StreetStrider mentions the new syntax is as short _(within a character or so)_ as the method name itself. Arrow functions make the syntax short enough in many cases to avoid these kinds of little helpers. That said, I'll still leave the issue as `votes needed` to keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
