### ISSUE TITLE
how to build the directory of 'lib'

### ISSUE THREAD

**Issue by MuYunyun** [lodash/lodash#3946]
When I look up the scripts in `package.json`, I find a number of scripts based in the directory of 'lib'. But I can't find how to build the directory of 'lib'. Can anyone help me ? Thanks.

**Comment by jdalton** [comment]
Hi @MuYunyun!

It's just left-overs from our stable release branch that hasn't been cleaned/re-wired yet is all.

**Comment by MuYunyun** [comment]
I understand 👍
