### ISSUE TITLE
intersection Not Working

### ISSUE THREAD

**Issue by alobban** [lodash/lodash#3949]
https://lodash.com/docs/4.17.10#difference

**System**
Node 9.9.0
NPM 5.6.0
OSX 10.13.4

**Current Behavior**: I provide a function 2 arrays of Mongo ObjectIds, I expect to obtain any ObjectIds that are the same amongst the arrays. However, I am always being returned an empty array from the method.

    function memberSync(oldMembers, updatedMembers) {
      oldMembers = oldMembers.filter((objId) => {
        return objId.toString();
      });
      updatedMembers = updatedMembers.filter((objId) => {
        return objId.toString();
      });
      console.log('old ', oldMembers);
      console.log('updated ', updatedMembers);
      const sameMembers = _.intersection(oldMembers, updatedMembers);
      console.log('same ', sameMembers, _.VERSION);
      const addMembers = _.difference(updatedMembers, sameMembers);
      console.log('new ', addMembers);
    }

    // **OUTPUT**
    old  [ 5aaefd867e5df7147351c1f3, 5b1ddf1672c13933a94c9861 ]
    updated  [ 5aaef9b445f09213c4fc331c, 5aaefd867e5df7147351c1f3 ]
    same  [] 4.17.10
    new [ 5aaef9b445f09213c4fc331c, 5aaefd867e5df7147351c1f3 ]

**Expected Behavior**
If the method was working I would expect the `sameMembers` array to be `[ 5aaefd867e5df7147351c1f3 ]` and the `addMembers` array to be effectively `[ 5aaef9b445f09213c4fc331c ]`.

    // **OUTPUT**
    old  [ 5aaefd867e5df7147351c1f3, 5b1ddf1672c13933a94c9861 ]
    updated  [ 5aaef9b445f09213c4fc331c, 5aaefd867e5df7147351c1f3 ]
    same  [ 5aaefd867e5df7147351c1f3 ] 4.17.10
    new [ 5aaef9b445f09213c4fc331c ]

Based on the documentation and REPL, I am using it correctly. Am I the only one having this issue?

**Comment by jdalton** [comment]
Hi @alobban!

You should try [_.differenceBy](https://lodash.com/docs/4.17.10#differenceBy).
