### ISSUE TITLE
Why array filter does not check for undefined values?

### ISSUE THREAD

**Issue by AjaxSolutions** [lodash/lodash#3950]
See this code:
https://github.com/lodash/lodash/blob/master/filter.js
It ignores undefined values, why?

The native filter is not invoked for indexes which have been deleted or which have never been assigned values.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by jdalton** [comment]
Hi @AjaxSolutions!

This is by design. Lodash aimed for consistent array iteration so opted for the simpler `i -> length` approach instead of also checking for sparse arrays _(which were handled inconsistently across-browsers when Lodash was starting out)_.
