### ISSUE TITLE
when cloneDeep with Map, value is empty 

### ISSUE THREAD

**Issue by eltonchan** [lodash/lodash#3951]
problem： when cloneDeep with Map, value is empty 
test demo: [see this code](http://jsbin.com/vitukujija/edit?html,js,console)
version： ^4.17.10

**Comment by eltonchan** [comment]
4.17.4 version can work, but The latest version can't

**Comment by jdalton** [comment]
Thanks @eltonchan!

Yep. This is a regression. I have this patched locally.

**Comment by jdalton** [comment]
I'm prepping a 4.17.11 bump today but the CDNs have already picked it up. This fix will make it into 4.17.12 _(right after, I won't even bother updating the docs to 4.17.11 and will just wait for 4.17.12)_.

**Comment by jdalton** [comment]
Closed by https://github.com/lodash/lodash/commit/e0cbb4c8e6f58122d1afaf69f93e0d85bc5fea64.
