### ISSUE TITLE
pick select only the key with dot if exists

### ISSUE THREAD

**Issue by ofirmalka** [lodash/lodash#3952]
if
```
object = {
  'a.b': 1,
  a: {
    b: 1,
  }
};
```
`pick(object, ['a.b'])` will return `{ 'a.b': 1}` instead of `{ 'a.b': 1, a: { b: 1 }}`

test demo: [code]( http://jsbin.com/yimewigoqo/edit?html,js,console)

**Comment by jdalton** [comment]
Hi @ofirmalka!

The `pick` method picks the properties specified. In this case you requested property `"a.b"`, so it picked it. If you wanted `["a", "b"]` you could specify that too.

**Comment by ofirmalka** [comment]
But if there is no 'a.b' in the object it picks ['a', 'b']

**Comment by jdalton** [comment]
Ah, that's no good.

**Comment by jdalton** [comment]
Closed by https://github.com/lodash/lodash/commit/39a7eae40d7b97921bca466ccb65969f0cc49332.

**Comment by ofirmalka** [comment]
Not sure about how pick suppose to work
you said i should use `pick(object,[['a.b']]).`
but also from
`pick(object,['a.b']).`
`pick(object,'a.b').`
I'm getting the same result: `{ 'a.b': 1 }`

so as i understand to get `{ a: { b: 1 } }` I must use pick like this: `pick(object, ['a', 'b'])`
otherwise i might get `{ 'a.b': 1 }` (if exists) and `{ a: { b: 1 } }` (if not exists) unless I'm using like that: `pick(object,[['a.b']]).`
