### ISSUE TITLE
Why does `lodash.throttle` not rely directly on `lodash.debounce` and have a duplicate built in?

### ISSUE THREAD

**Issue by MinJieLiu** [lodash/lodash#3954]
Why does `lodash.throttle` not rely directly on `lodash.debounce` and have a duplicate built in?

**Comment by jdalton** [comment]
Hi @MinJieLiu!

Because devs complained about the number of dependencies these modules had. See developers often want to opposing things at the same time. In this case they wanted module code but not too modular.
