### ISSUE TITLE
Can I merge / assign at a specific path then return the entire merged object?

### ISSUE THREAD

**Issue by simkessy** [lodash/lodash#3961]
My entire application is one big object like so: `let client = client || {}`  and I have different files for various "namespaces" and I just assign each namespace back to the `client` object. 

I want to keep doing this but into a nested property, for example "client.forms" and extract out each form into it's own file because the current forms.js file is getting large.  

Is it possible to use assign or merge to set the path where I'm merging then return the parent object? 

forms-finance.js:

```
let client = client || {}; 

let financeForm = {
    init: () => {console.log("form loaded")}
}

_.assign(client, "forms.finance", financeForm)

Result: 
client = {
  forms: {
    finance: {
      init: () => {
        console.log("form loaded");
      }
    }
  }
};

```

**Comment by mvastola** [comment]
You're looking for `_.set`. That one doesn't merge, but if you need that functionality you can presumably use `_.setWith` and specify a customizer that does the merging.

**Comment by simkessy** [comment]
@mvastola  could you show me an example please?

**Comment by mvastola** [comment]
Literally just `_.set(client, "forms.finance", financeForm)`

**Comment by simkessy** [comment]
@mvastola I tried: 

`_.setWith(app, "forms.tabs.finance", financeForm, _.merge);`

But I ended up with:

![image](https://user-images.githubusercontent.com/5871660/45656230-28ad2a80-ba99-11e8-9223-83b44a44c577.png)

**Comment by mvastola** [comment]
Okay, so apparently `setWith` doesn't do what I imagined it did.
Do this instead:
If you have:
```js
let x = {
	a: {
  	b: {
    	c: 1,
      e: 4
    }
  }
};

let y = {
  b: {
   	c: 2,
    d: 3
  }
};
```
..and say you want to merge `y` into `x.a`, use:
```js
_.merge(_.get(x, 'a'), y);
```

In your case, that would be:
```js
 _.merge(_.get(app, 'forms.tabs.finance'), financeForm);
```

Note this won't work if `app.forms.tabs.finance` doesn't exist, so you might want to do:
```js
let current = _.get(app, 'forms.tabs.finance', {});
let new = _.merge({}, current, financeForm);
_.set(app, 'forms.tabs.finance', new);
```
