### ISSUE TITLE
_.defaultsDeep vs _.merge inconsistency

### ISSUE THREAD

**Issue by mvastola** [lodash/lodash#3962]
So I have code where I need to override the `.toString` accessor for a plain object.
An example is the following: 
```js
let x = { foo: 'bar' }
x.toString = function() { return this.foo; };
console.log(x + ""); // outputs 'bar' (correct)
```
..which, as intended, outputs the value of a property of the object.
I, however, need to merge this object with another because I have some default values.

It makes sense to me that if I do:
```js
let y = _.defaultsDeep({}, x);
console.log(y + ""); // outputs "[object Object]"
```
I lose my string converter, because `.toString` is a built-in method that I overwrote, and it is already defined in `{}` and therefore not overridden. 

Correctly, `_.merge` does preserve this string accessor because in the case of a property being defined in multiple arguments, the rightmost one wins.

An odd artifact appears though, if I use `_.defaultsDeep` on a multi-dimensional object like so:
```js
let y = { x: x };
let z = _.defaultsDeep({}, y);
console.log(y.x + ""); // outputs "[object Object]"
```
The expected output here is `bar` again, since the empty object in the first argument has no property `x` set and thus `z.x` should be identical to `x`. 

This, however, does not happen.

**Comment by jdalton** [comment]
Hi @mvastola!

I've gone back and forth on this over the years. Historically `_.defaults` would count inherited properties when considering if a property value existed. At one point in time _(Lodash v2 or so)_ I changed it to own-properties only but changed it back in v3-or-v4 because of friction in the Underscore/Backbone community.

**Comment by mvastola** [comment]
I'm confused. If it was last changed back, doesn't that mean it should work? Or was it changed yet again after that?
