### ISSUE TITLE
FP: fp.transform function maintaining previously transformed Object

### ISSUE THREAD

**Issue by GitIanWilliams** [lodash/lodash#3963]
Hi, I'm new to javascript FP, so perhaps this is by design. I would like to be able to create a function to transform an array of objects of this format: 

`[
   {
       filter_name: 'fruit',
       values: ['apple', 'banana']
   }, ...
]`

into an object that looks like this:

`{
   fruit: ['apple', 'banana'],
   ...
}`

The method I have seems to continuously push object properties to the same object, instead of creating individual separate objects. How do I create a function that processes each array separately?

    const transformFilterArrayToObject = (result, value) => result[val.filter_name] = val.values;
    const mapFilterValues = fp.transform(transformFilterArrayToObject, {});

    const firstArrayToTransform = [
      {
        filter_name: 'fruit',
        values: ['apple', 'banana']
      }
    ]
   
    const secondArrayToTransform = [
      {
        filter_name: 'veggies',
        values: ['spinach', 'arugula']
      }
    ]       
                
    const firstObject = mapFilterValues(firstArrayToTransform);
    const secondObject = mapFilterValues(secondArrayToTransform);

    console.log(firstObject);
    console.log(secondObject);
    //  BOTH RETURN { fruit: ['apple','banana'], veggies: ['spinach', 'arugula'] }

**Comment by jdalton** [comment]
Hi @GitIanWilliams!

The reason it's keeping the values is because you're using 1 object reference in
```js
fp.transform(transformFilterArrayToObject, {});
```

To make it unique it would need to be created once for each. You should check out our [gitter chat](https://gitter.im/lodash/lodash). 
I'm sure there are some FP folks there who can help.
