### ISSUE TITLE
vue 里使用 throttle 会触发两次

### ISSUE THREAD

**Issue by Johnson-huang** [lodash/lodash#3964]
`
import _ from 'lodash';
`
`
nativeChange: _.throttle(function () {
      console.log(123);
}, 10000),
`
使用 click 事件触发，狂点，第一个console立刻打印出来，第二个console在设定的间隔时间打印
例如上例，第一个马上打印，第二个在10s时打印

不确定是哪里的问题

**Comment by Johnson-huang** [comment]
vue 版本 2.5.2
lodash 版本 4.17.11

**Comment by olivewind** [comment]
use english instead of chinese

**Comment by Johnson-huang** [comment]
when use lodash.throttle in Vue.js, it will work twice.

for example
`nativeChange: _.throttle(function () { console.log(123); }, 10000),`
if a html dom trigger click event  and the frequency of clicks is fast
function name is nativeChange
this function will work twice, the first 123 will be printed as soon as possible, and after sometime(this example is 10s), the second 123 will be printed too.
this time is the same as the interval time.

**Comment by jdalton** [comment]
Hi @Johnson-huang!

What you're seeing is the trailing invocation. 
You can use the [`trailing` option](https://lodash.com/docs/#throttle) of `false` to stop it.
