### ISSUE TITLE
_.rename renaming key name

### ISSUE THREAD

**Issue by satishnani** [lodash/lodash#3965]
I looking at lodash funcitons but i dont see any function for renaming the key

**example :** 
<pre>
const destinations = [
    {
      "lat": 40.73005400028978,
      "lon": -73.99106999861966,
      "lid": "poinysnyd1"
    },
    {
      "lat": 40.73046499853991,
      "lon": -73.99250799849149,
      "lid": "poinysnyd401"
    }
  ];
</pre>

**result should be:**
<pre>
[
    {
      "lat": 40.73005400028978,
      "lon": -73.99106999861966,
      "id": "poinysnyd1"
    },
    {
      "lat": 40.73046499853991,
      "lon": -73.99250799849149,
      "id": "poinysnyd401"
    }
  ];
</pre>
I want all the **lid** keys to be renamed to **id** do we have any function similar to this.

**Comment by jdalton** [comment]
Hi @satishnani!

You can do:
```
object.newkey = object.oldkey
delete object.oldkey
```

**Comment by satishnani** [comment]
can we do it using lodash

**Comment by jdalton** [comment]
You could use `_.set` and `_.unset` to do the same thing
