### ISSUE TITLE
Offline docs in Dash

### ISSUE THREAD

**Issue by honzajavorek** [lodash/lodash#3966]
Thank you for `lodash/fp`! There is this macOS app called [Dash](https://kapeli.com/dash), which allows people to have and search various docs offline (e.g. in a train, plane, ... and sometimes it's just faster to look up than the web versions). There's an official Lodash docset:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/283441/45740669-10065700-bbf6-11e8-82ed-228436dad85e.png">

There is no docset for the `lodash/fp` though. Would you consider [adding it](https://kapeli.com/docsets)?

Also it looks like there is [other popular software](https://alternativeto.net/software/dashexpander/) which does the same thing, such as [Zeal](https://zealdocs.org/), so maybe the docset could be even compatible with those?

I think the main problem is the FP part of lodash isn't even a part of your HTML docs. There's this [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide), but there are many differences and it’s very hard to search the regular docs and to just guess what the FP equivalent would be or to scan the FP guide for changes between those two. E.g. function `invokeArgs` doesn't even exist in the regular docs, but it’s crucial to know about it when you want to use `invoke` from FP. I spent hours figuring out this one in particular. Do you have any plan to extend the regular docs with a full FP documentation? That would be probably sufficient to solve my issue as I can imagine the documentation would bubble up to the official docset.

**Comment by jdalton** [comment]
Hi @honzajavorek!

I'm glad there are doc apps out there but they just re-process our docs. I wouldn't want to do work specifically for each doc app out there. There have been doc efforts in the past but they never went anywhere so until then the markdown guide is what we have.

**Comment by def14nt** [comment]
@jdalton Good job clearing all of the issues :smile: Just wondering why you can't use the normal docs template with the fp docs?
