### ISSUE TITLE
Equal By function

### ISSUE THREAD

**Issue by Caballero77** [lodash/lodash#3967]
Hello. While using lodash I decided that it will be great if there will be function that will provide functionality as equalBy. 

Examle: 
```
const x = { a: 1, b: 2};
const y = { a: 2, b: 2};

_.equalBy(x, y, 'a'); // false
_.equalBy(x, y, 'b'); // true
_.equalBy(x, y, el => el.a); // false
```

Name for the function could be eqBy, isEqualBy or equalBy.
Could I create PR for this feature?

**Comment by jdalton** [comment]
Hi @Caballero77!

Now that arrow functions are a thing and can be used to reduce the syntax needed to create functions that pluck properties I want to avoid adding these kinds of methods.
