### ISSUE TITLE
fp/map callback does not provide key parameter

### ISSUE THREAD

**Issue by lishine** [lodash/lodash#3968]
fp/map((value, key) = ..., object)
Key is undefined

**Comment by jdalton** [comment]
Hi @lishine!

This is by design to be more-FP friendly.
You can however tweak this using the [`fp.convert` method](https://github.com/lodash/lodash/wiki/FP-Guide#convert) and setting `cap` to `false`.

**Comment by lishine** [comment]
Thanks!
Silly me

**Comment by andrewpeterprifer** [comment]
@jdalton I think the confusion would be somewhat eliminated if the fp guide would be explicit about this. IIRC right now it says that fp/map iteratee also takes index/key.
