### ISSUE TITLE
_.round/_.floor/_.ceil do not work under lodash/fp

### ISSUE THREAD

**Issue by philippefutureboy** [lodash/lodash#3970]
**lodash version:** ^4.17.11
**npm version:** 6.4.1
**node version:** 8.11.1

**Bug or feature ?** Bug

**Expected behaviour:**
```js
$ node
> const _ = require('lodash/fp');
undefined
> _.ceil(135020, -4)
140000
> _.floor(135020, -4)
130000
> _.round(135020, -4)
140000
```

**Actual behaviour:**
```js
$ node
> const _ = require('lodash/fp');
undefined
> _.ceil(135020, -4)
135020
> _.ceil(135020)(-4)
TypeError: _.round(...) is not a function
> _.floor(135020, -4)
135020
> _.ceil(135020)(-4)
TypeError: _.round(...) is not a function
> _.round(135020, -4)
135020
> _.round(135020)(-4)
TypeError: _.round(...) is not a function
```

Most likely this is due to introducing a fixed arity of 1 to the functions for the /fp version of the package.

**Comment by jdalton** [comment]
Hi @philippefutureboy!

Methods like `round` hav a [fixed arity of one](https://github.com/lodash/lodash/wiki/FP-Guide#fixed-arity). You can customize this with [`convert`](https://github.com/lodash/lodash/wiki/FP-Guide#convert).

**Comment by philippefutureboy** [comment]
I understand that they have a fixed arity of one – the issue here is that this restriction essentially removes the usefulness of such a function.

Don't you think that without the ability to add the precision level, it defeats the purpose of these functions being there in the first place?
