### ISSUE TITLE
map iteratee in lodash/fp doesn't receive object key

### ISSUE THREAD

**Issue by andrewpeterprifer** [lodash/lodash#3971]
I haven't tested other functions, only map, and only with objects. It might occur with others as well.

The below function outputs `[undefined]`:

```js
var obj = {
    a: 2
}

map((value, key) => key, obj)
```

The normal lodash counterpart works as expected.

Happens under lodash 4.17.11.

**Comment by jdalton** [comment]
Hi @andrewpeterprifer!

Dup of #3968.
