### ISSUE TITLE
Why is _.throttle its own function?

### ISSUE THREAD

**Issue by NickHeiner** [lodash/lodash#3972]
I don't have a specific problem. I'm just curious about the design philosophy.

Here's the source of `_.throttle`, as seen in `lodash.throttle`:

```js
function throttle(func, wait, options) {
  var leading = true,
      trailing = true;

  if (typeof func != 'function') {
    throw new TypeError(FUNC_ERROR_TEXT);
  }
  if (isObject(options)) {
    leading = 'leading' in options ? !!options.leading : leading;
    trailing = 'trailing' in options ? !!options.trailing : trailing;
  }
  return debounce(func, wait, {
    'leading': leading,
    'maxWait': wait,
    'trailing': trailing
  });
}
```

It seems like it's just a proxy to `debounce` with the `wait` option changed to `maxWait`. Is `throttle` just a convenience wrapper? Or is there some other reason to have it be a separate function that I'm missing?

**Comment by jdalton** [comment]
Hi @NickHeiner!

The `_.debounce` and `_.throttle` methods started out as 2 separate methods. Over time I realized I could implement `_.throttle` by way of `_.debounce`.

**Comment by StreetStrider** [comment]
@NickHeiner as far as I know, both methods originates from Underscore. It was a bare-bones implementations of two different strategies, without many options on them. At the certain point, in LoDash this methods was upgraded to accept additional options (leading, trailing, maxWait…), so it is became possible to implement one of them via another. It still (without options) a *different* strategies, like `throttle` guarantees execution of target in every X ms, while `debounce` may postpone indefinitely.
