### ISSUE TITLE
Feature request: _.builder()

### ISSUE THREAD

**Issue by Mariosunny** [lodash/lodash#3973]
`_.builder(func, ...params)` takes a function and a variable number of parameters, and returns an object that can be used to progressively 'build' the arguments for the function, al la the [Builder Pattern](https://sourcemaking.com/design_patterns/builder).

**Example:**
```node
function createStudent(firstName, lastName, major, age, address) {
  return new Student(firstName + " " + lastName, major, age, address);
}

let createStudentWith = _.builder(createStudent, 'first', 'last', 'major', 'age', 'address');

let henry = createStudentWith
  .first("Henry")
  .last("Smith")
  .major("CS")
  .age(26)
  .address("1100 Placeholder street");

let john = createStudentWith
  .first("John")
  .last("Doe")
  .major("EE")
  .age(34)
  .address("1839 Hill Dr.");
```
The main advantage of using a builder is that the arguments are named. This is especially useful with functions with several parameters, where the programmer may have a hard time remembering the order of the arguments. [Several languages already support named arguments](https://docs.scala-lang.org/tour/named-arguments.html), but Javascript (sort of) does not. The builder is intended to closely simulate the traditional named arguments syntax.

**Implementation:**
```node
function builder(func, ...params) {
    return builderHelper(func, params);
}

function builderHelper(func, params, ...args) {
  if(params.length > 0) {
      let obj = {};
      obj[params[0]] = function(arg) {
          return builderHelper(func, _.slice(params, 1), ..._.concat(args, arg));
      };
      return obj;
  }
  else {
      return func(...args);
  }
}
```

**Comment by jdalton** [comment]
Hi @Mariosunny!

I think this would be a better fit as its own standalone package/util.
