### ISSUE TITLE
_.snakeCase Unexpected Behavior?

### ISSUE THREAD

**Issue by jessemorton** [lodash/lodash#3975]
According to #561 and this [comment](https://github.com/lodash/lodash/issues/561#issuecomment-43519167), it seems like something like `address1` should be considered its own word and not be converted to `address_1`, but it is. Did the behavior change at some point or am I misunderstanding something?

**Comment by jdalton** [comment]
Hi @jessemorton!

>  Did the behavior change at some point or am I misunderstanding something?

The behavior changed over time.

**Comment by jessemorton** [comment]
Thanks for the reply @jdalton, though is there a reference somewhere of the expected behavior then?
