### ISSUE TITLE
_.defaultsDeep can mutate source at some cases

### ISSUE THREAD

**Issue by Vovch** [lodash/lodash#3978]
Please see https://plnkr.co/edit/J7svOBeIMZKnvLelzUya?p=preview

There is a moment and lodash example. Currently I was not able to reproduce it with any other objects.

After running the next code: 
`_.defaultsDeep({}, a, b);`
`console.dir(a);`

We can see that in the source `a.settings.min` has all the properties that the appropriate `moment` object has, including the ones from its prototype. Also please note, that somehow `max` object does not go to the `a.settings.max`, so this looks like a problem with rewriting only existing properties.

**Comment by jdalton** [comment]
Hi @Vovch!

The object is assigned by reference to the destination if there is nothing to merge into. So then when you deep merge additional properties the object on the destination it's augmenting the same object as the source.

**Comment by Vovch** [comment]
So do I understand correct that it is okay that it mutated the source (object `a` in this case, but not the new object)? Is this worth mentioning somewhere in documentation then? For me this behavior is counter-intuitive.

**Comment by eLeontev** [comment]
Agree with @Vovch. Looks like the defect such that will lead to a lot of unexpected results. Why should user  worry about with undocumented unexpected result. At lest it's confuse. @jdalton please comment that.

**Comment by jdalton** [comment]
@eLeontev 

Would you be up for making the doc change? 
_(To do that create a PR that edits the JSDoc for the method in the module source.)_
