### ISSUE TITLE
_.set does not work when an array exists along the path

### ISSUE THREAD

**Issue by christianbasch** [lodash/lodash#3980]
### Object to be manipulated:
```
const obj = {
  toBeSet: ['any-value'],
};
```

### Set operation
`_.set(obj, 'toBeSet.shouldHaveAChildNow', 'any-child');`

### Expected result:
```
obj = {
  toBeSet: {
    shouldHaveAChildNow: 'any-child',
  }
}
```

### Current result:
```
obj = {
 toBeSet: ['any-value'],
}
```

This works for primitive data types, just not for arrays.

**Comment by jdalton** [comment]
Hi @christianbasch!

The `_.set` method is actually still setting a value on the array object.
You can see it if you log it out
```js
obj.toBeSet.shouldHaveAChildNow // => 'any-child'
```
The `_.set` method won't replace the array with a plain object though.
