### ISSUE TITLE
Partial placeholder present as curried function argument

### ISSUE THREAD

**Issue by JasonPollman** [lodash/lodash#3981]
When currying with placeholders, the placeholder value is sometimes passed to the original function:

```js
const triples = _.curry((a, b, c) => [a, b, c]);
triples(_, 2, _)(_, 3)(_, 1); // => [f, 2, 3]
triples(_, 2)(_, 3)(_, 1);    // => [f, 2, 3]
triples(_, 2)(3, _)(_, 1);    // => [f, 2, 3]
// Where f === lodash (placeholder)
```

Expected:
```js
triples(_, 2)(_, 3)(_, 1);    // => triples
triples(_, 2)(_, 3)(_, 1)(1); // => [1, 2, 3]
```

However, this works:
```js
triples(_, 2)(_, 3)(_)(1); // => [1, 2, 3]
```

This seems to be an issue when the arity of the function is exceeded and maybe placeholders are considered in some arity calculation?

Another strange example:
```js
const pairs = _.curry((a, b) => [a, b]);
pairs(1, _, 0) // => [1, "__lodash_placeholder__"]
```

Here I would expect the `0` to be ignored, since it is "outside" the arity of the original function and the curried function to be returned, allowing for:

```js
pairs(1, _, 0)(2) // => [1, 2]
```

*Lodash Version 4.17.10*
*Chrome Version 68.0.3440.106*

**Comment by brodeynewman** [comment]
Going to try taking a whack at this.

**Comment by jdalton** [comment]
Moved to #3990.
