### ISSUE TITLE
Wrong document description at cloneDeepWith API

### ISSUE THREAD

**Issue by thieuanh1995hn** [lodash/lodash#3983]
This API: https://lodash.com/docs/4.17.10#cloneDeepWith.
I think the description should be : "This method is like _.cloneWith except that it has a call back function." instead of "This method is like _.cloneWith except that it recursively clones value." because cloneWith  API also do recursively clones value.

**Comment by jdalton** [comment]
Hi @thieuanh1995hn!

The `_.cloneWith` method should not be deeply recursive like `_.cloneDeepWith`.
