### ISSUE TITLE
Proposal: fromPairsBy

### ISSUE THREAD

**Issue by jedwards1211** [lodash/lodash#3984]
Not sure if this is the best method name but I think it would be handy to have a function that takes an array, a function to extract the key from each element, and a function to extract the value from each element, and creates an object from the extracted key/value pairs.  I'm happy to make a PR, just wanted to get your approval before I spend time on it.

Here's what the method would look like:
```
> fromPairsBy([{key: 'a', value: 1}, {key: 'b', value: 2}], x => x.key, x => x.value)
{a: 1, b: 2}
```
With property shorthand it's fantastic:
```
> fromPairsBy([{key: 'a', value: 1}, {key: 'b', value: 2}], 'key', 'value')
{a: 1, b: 2}
```
I started wanting this while seeking to transform the following AWS output:
```
$ aws cloudformation describe-stacks --stack-name clarity-db --query 'Stacks[0].Outputs'
[
    {
        "OutputKey": "DBInstance",
        "OutputValue": "clarity"
    },
    {
        "OutputKey": "RecordSet",
        "OutputValue": "redacted"
    },
    {
        "OutputKey": "SecurityGroup",
        "OutputValue": "redacted"
    }
]
```
(wish I could pipe the output to `| lambduh 'json => require("lodash").fromPairsBy(json, "OutputKey", "OutputValue")'`)

FP version:
```
> fromPairsBy('key', 'value')([{key: 'a', value: 1}, {key: 'b', value: 2}])
{a: 1, b: 2}
```
The shortest way I know of to do this with existing API is not too bad but a bit more cumbersome (and requires ES2015):
```
> fromPairs([{key: 'a', value: 1}, {key: 'b', value: 2}].map(({key, value}) => [key, value]))
{a: 1, b: 2}
```

**Comment by jdalton** [comment]
Hi @jedwards1211!

Moving forward I'd like to reduce or at least cut down on the "By" variants of methods. My hope is that new language features such as arrow functions make it easier to accomplish without adding method variants.

**Comment by jedwards1211** [comment]
@jdalton fair enough, `fromPairs(array.map(...))` isn't too bad with arrow functions

**Comment by cdoublev** [comment]
I was searching feature request for `toPairsBy`. Do you see a straitghforward way to get the same result as below?

```js
const obj = { a: 'foo', b: 'bar', c: 'baz' }
const toPairsBy = curry((key, f, obj) => [obj[key], typeof f === 'function' ? f(obj) : obj[f]])
// ['foo', 'bar']
```
