### ISSUE TITLE
Proposal: _.thunk

### ISSUE THREAD

**Issue by sagiavinash** [lodash/lodash#3985]
**Motivation:**
Lot of times we need to pass a function that does this:
`(cb) => cb(arg)`

**Example:**
Dependency injection 
```js
const apiHandlers = _.mapValues(apiHandlerCreators, (handler) => handler(config));
```
due to such repeated occurrences I refactored it to
```js
_.mixin({
  thunk: (...args) => (cb) => cb(...args)
});
const apiHandlers = _.mapValues(apiHandlerCreators, _.thunk(config));
```

**Comment by jdalton** [comment]
Hi @sagiavinash!

I like how small ES6+ style syntax makes the method implementation!

That also makes me think that moving forward it'd be great on its own outside of Lodash. That said, we'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
