### ISSUE TITLE
throttle should be always executed asychronously

### ISSUE THREAD

**Issue by pjasiun** [lodash/lodash#3988]
`throttle` function is executed synchronously if it the throttled function is executed after the `wait` time after the previous call. It may change the context of the execution and causes bugs which are very hard to debug.

Note that, most probably because of this reason promises are executed always asychronously:

```js
console.log( '1' );
Promise.resolve().then( () => {
	console.log( '3' );
} );
console.log( '2' );
```

In my case, the problem was connected with the way how browsers executed timeouts in the background tabs.

The following code CAN return true if the tab is in the background:
```js
let sync = false;

const throttledFoo = _.throttle( () => { console.log( sync ) }, 300, { leading: false } );

setInterval( () => {
	sync = true;
	throttledFoo();
	sync = false;
}, 500 );
```

My proposal is to change the way how `throttle` (and `debounce`) works to ensure they are always asynchronous.

**Comment by jdalton** [comment]
Hi @pjasiun!

The `_.throttle` method only handles the trailing call as async. Everything else is synchronous at the time of invocation.
