### ISSUE TITLE
Sort object by string-keyed property names

### ISSUE THREAD

**Issue by LendaVadym** [lodash/lodash#3989]
It would be good to have an extension that helps to sort object by property names (string-keyed);
For example:
```
let a = { b, a, c };
let b = _.sortKeys(a);
console.log(b);
// {a, b, c}
```

**Comment by jdalton** [comment]
Hi @LendaVadym!

JS allows customizing sorting with `Array#sort`: `Object.keys(o).sort(comparator)`
