### ISSUE TITLE
isEmpty is not working with FormData

### ISSUE THREAD

**Issue by JoniJnm** [lodash/lodash#3991]
isEmpty allways return true with FormData object, even if there are keys.

```js
let formData = new FormData();
formData.set('test', 'value1');
_.isEmpty(formData);
```

The problem is here:

https://github.com/lodash/lodash/blob/master/isEmpty.js#L61

A possible solution:

```js
if (tag === '[object FormData]') {
	if ('keys' in value) {
		return !formData.keys().next().done;
	}
	else {
		// we can't know if it's empty, no native keys function
		return false;
	}
}
for (const key in value) {
	if (hasOwnProperty.call(value, key)) {
	  return false
	}
}
```

**Comment by jdalton** [comment]
Hi @JoniJnm!

Our `_.isEmpty` looks for enumerable keys. If there are non then it is determined to be empty, as in an empty collection.

**Comment by JoniJnm** [comment]
Should it work with [Iterators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols)? 

```js
_.isEmpty(formData.keys());
```

**Comment by jdalton** [comment]
`isEmpty` is an indicator of an empty collection. Our collection methods don't perform anything specific to Iterators.
