### ISSUE TITLE
Convert string to snake case behavior.

### ISSUE THREAD

**Issue by scvhost** [lodash/lodash#3992]
Hi, I curious about the behavior of snakeCase in lodash.
In this case, if i want to convert the "itemV2" to snake case.
The result should be "item_v2" , but the result from using snakeCase method is "item_v_2".
So, do you have any idea about this ?

**Comment by jdalton** [comment]
Hi @scvhost!

We've found splitting words up to not be so cut and dry. We now side with treating `itemV2` as 3 compound words.

**Comment by jdalton** [comment]
Hi @dwjft!

You're better off using a one-off custom snake case module or  package.
