### ISSUE TITLE
Is lodash support judge multiple value and return finally total value  by only one function?

### ISSUE THREAD

**Issue by LaiHuanMin** [lodash/lodash#3994]
For example:    
**before**:
```javascript
if(_.isNil(a) && _.isNil(b) && _.isNil(c)){
    // do sth when a,b,c all nil
}
```

**after**
```javascript
if(_.isMatchCond([a,b,c],_.isNil)){
    // do sth when a,b,c all nil
}
```

I wrote the simple code to archive **isMatchCond** function:   
```javascript
function isMatchCond(target,func){
    var isAnyMatch = true;
    _.every(target,x=>{
       isAnyMatch = func(x);
       return isAnyMatch;
   })    
   return isAnyMatch;
}
_.isMatchCond = isMatchCond;
```

The first args is mainly for array, the second is user define function.      
If any item of those array contains a false value which judged by the secondly args in arguments, the isMatchCond function will be return soon.    

Because I always need to judge multiple condition, and have to wrote a lots of those && symbol. Is there's already a lodash function can archive this feature?If not, can you add this code please?  

Thanks for reading and lodash!

**Comment by rafde** [comment]
```js
// untested but I think this works
const allMatch = fp.every(_.isNil);
if(allMatch([a,b,c]){
    // do sth when a,b,c all nil
}
```

**Comment by LaiHuanMin** [comment]
@rafde Thanks for reply and wrote code! I still hope lodash can have a  direct function to archive without config, it's can make code more simple and geek, especially if/while/for those control block condition  ^_^

**Comment by jdalton** [comment]
Hi @LaiHuanMin!

Since this looks like it can be tackled relatively easy with method composition.
I'll defer to that route for now.
