### ISSUE TITLE
Set function in fp doesn't seem to work. 

### ISSUE THREAD

**Issue by asolopovas** [lodash/lodash#3996]
Hi,

I am using fp version of lodash and set function doesn't seem to work. I tried to place arguments in same order as shown here [fp set docs](https://gist.github.com/jfmengels/6b973b69c491375117dc#_setpath-value-object),
but the object doesn't change. 

Here are to code pen examples one is fp version the other one is standard and standard works where fp doesn't

[fp version](https://codepen.io/asolopovas/pen/vVxbxL)
[standard](https://codepen.io/asolopovas/pen/RepvgR)

**Comment by brodeynewman** [comment]
Apologies if i'm mistaken, but I don't see the FP _.set used in the first codepen link.

The below behavior works as expected:

```js
const fp = require('lodash/fp');

const obj = { name: 'Bob' };
console.log(fp.set('name', 'Tony')(obj)); // { name: 'Tony' }
```

**Comment by asolopovas** [comment]
the way I am doing it is
```
import _set from 'lodash/fp/set'
```
but than it doesn't work in comparison to 
```
import _set from 'lodash/set'
```
same works with other functions though.

**Comment by brodeynewman** [comment]
I see.

Below works for me:

```js
const set = require('lodash/fp/set');

const obj = { name: 'Brodey' };

console.log(set('name', 'Tony')(obj));  // { name: 'Tony' }
```

**Comment by asolopovas** [comment]
yes it does work the way you did. The problem is that  I am mutating state in vuex, which requires me to change the nested property on state object.  I think fp function it's just not applicable for my usecase, as fp concept does not mutate the initial data, and I need it mutated. So  `import set from `lodash/set` does mutate the obj where `lodash/fp/set` does not.
