### ISSUE TITLE
_.get with multiple fallbacks

### ISSUE THREAD

**Issue by davidfregoli** [lodash/lodash#3997]
Hi folks, is there a nifty way to have the convenience of `_.get` for checking multiple fallback paths?
Like `_.get(data, 'a.b', 'a.c', 0)` where it would check `data.a.b` then `data.a.c` then finally settle for `0` if none of the others is defined.

I know I could nest `get`s but I don't particularly like it.

**Comment by jdalton** [comment]
Hi @davidfregoli!

There isn't a way to do multiple fallbacks. You can nest or if values are expected to be truthy you can always do
```js
const value =
  _.get(o, "a.b") ||
  _.get(o, "a.c") ||
  _.get(o, "a.d") ||
  0
```

**Comment by poeapp** [comment]
@davidfregoli You could also define your own method such as:

```javascript
const getFallback = (object, ...paths) => {
  let found;
  const pathsSize = paths.length;

  for (let index = 0; index < pathsSize; index++) {
    const path = paths[index];

    // Assume last path is the defaultValue
    if (index === (pathsSize - 1)) {
      found = path;
      break;
    }

    found = _.get(object, path);

    if (typeof found !== 'undefined') {
      break;
    }
  }

  return found;
};

// Usage

const a = { a: { b: 2 }, b: 3, c: { a: 4 }};
getFallback(a, 'a.c', 'd.a', 'a.b', 5);
```

**Comment by StreetStrider** [comment]
#3847

**Comment by StreetStrider** [comment]
[object-path](https://github.com/mariocasciaro/object-path).
