### ISSUE TITLE
react native debounce not working on android when params passed.

### ISSUE THREAD

**Issue by stevenmathers** [lodash/lodash#4008]
this.onPressDebounced = _.debounce((...params) => this.onPressed(...params), 500 , {
             'leading': true,
             'trailing': false
         })

the above works with expected behaviour for IOS, but fails completely to debounce for android.

If I skip the params all together, I get the same debouncing beahviour on IOS and android, but it isnt quite what I want (Id like action on leading edge and not on trailing edge obviously)

cheers

**Comment by jdalton** [comment]
Hi @stevenmathers!

You might try asking folks in a react-native support chat/slack for assistance.
