### ISSUE TITLE
Unexpected element in comparator by _.intersectionWith

### ISSUE THREAD

**Issue by brussee** [lodash/lodash#4012]
The comparator receives 2 elements from array A, but I expect it to always get 1 element of array A and 1 element of array B (as the 2 input arguments to the comparator function, respectively).

Minimum example:
```
<html>
  <head>
    <title>Minimum example</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.js"></script>
  </head>
  <body>
    <script type="module">
      console.log(_.VERSION)
      const A = [{
        id: 'f'
      }, {
        id: 'b'
      }]
      const B = [{
        Name: 'foo'
      }, {
        Name: 'bar'
      }, {
        Name: 'foobar'
      }]
      const comparator = (a, b) => {
        console.log({a, b})
        return b.Name.startsWith(a.id)
      }
      const expectedResult = [A[0], A[1]]
      const result = _.intersectionWith(A, B, comparator)
      console.log({expectedResult, result})
    </script>
  </body>
</html>
```

**Comment by jdalton** [comment]
Hi @brussee!

The `comparator` is called on the arrays provided as well on the results array to avoid duplicates. What you're seeing is the comparing of the results array.

**Comment by brussee** [comment]
Thanks for responding so quickly!

Indeed it makes sense to avoid duplicates when array `A` does not contain duplicates and the comparator does return true for multiple combinations of an element `a` of array `A` with elements of array B.

However, what about the case where array `A` intentionally contains duplicates, then these would be filtered out, correct? This use case does not make sense in set theory of course, but since _.intersectionWith takes arrays one might make the argument it should keep duplicates in `A`. This is not my use case, to be clear. (I ran into the issue that Name is not an attribute of elements of `A` in the example above.)

Perhaps your answer can be added to the documentation for clarity? Because apparently the comparator has double duty to also filter out duplicates within the intersection (by comparing them).

Thanks a lot again!
