### ISSUE TITLE
inRange

### ISSUE THREAD

**Issue by Vladinho10** [lodash/lodash#4016]
_.inRange(4, 2, 4); // false, but important, that it will be true. Why? It's necessary to know the end of the range. Please fix it.

**Comment by Seymur** [comment]
Let's say you want to know if number is in the first half or second half of range 0 - 9.
`
// if number is less than 5, then it is in the 1st half, else it is in the 2nd half
var halfPoint = 5;
// if _.inRange method would include the end of range, this would be result:
var inFirstHalf = _.inRange(4, halfPoint); 
`

**Comment by Seymur** [comment]
Let's say you want to know if number is in the first half or second half of range 0 - 9.
    
    // if number is less than 5, then it is in the 1st half, else it is in the 2nd half
    var halfPoint = 5;
    // if _.inRange method would include the end of range, this would be result:
    var inFirstHalf = _.inRange(5, 0, halfPoint); // would return true
    var inSecondHalf = _.inRange(5, halfPoint, 9):  // would return true

Oops! Number 5 cannot be in both halves of a range at the same time.  That is why _.inRange method and many other similar functions (like builtin `Array.prototype.slice`) does not include the end of range.
