### ISSUE TITLE
Use string as object in _.set or _.setWith

### ISSUE THREAD

**Issue by PazzaVlad** [lodash/lodash#4017]
Hi everyone!
If we run
```js
_.set({},[ 'data', '2019', 0, 'price' ], 'zzz',)
```
**we get:** 
object -> array -> array -> object

**I want to get:**
object -> object -> array -> object

So String '2019' will be treated as index of array, not as key of an object.
Is it possible to use with _.set or _.setWith so that any string type like '2019' (even it can be coerced to number) will be treated as object key, and any number type as array index? 

I tried some variants like this, but it makes number 0 key of an object too.
```js
_.setWith({},[ 'data', '2019', 0, 'price' ], 'zzz', (nsValue, key, nsObject) => {
  if(!nsValue) {
    if (typeof key === 'string') return {}
  }
})
```

**Comment by jdalton** [comment]
Hi @PazzaVlad!

You're on the right track with `_.setWith`. You check if the key is numeric and within a certain length or range. You can coerce a numeric string to a number with `+key`.

**Comment by dhaldankar** [comment]
You can just say 'Object' 
``
var object = {};
_.setWith(object, '[0][1]', 'a', Object);
// => { '0': { '1': 'a' } }
``
