### ISSUE TITLE
isEqual blows stack on nested objects

### ISSUE THREAD

**Issue by wchargin** [lodash/lodash#4019]
For example, if you have a tree of Git commits, each pointing to its
parents, you can blow the stack with a very reasonable depth:

```js
const isequal = require("lodash.isequal");
function gen(n) {
  let result = {};
  for (let i = 0; i < n; i++) {
    result = {parents: [result]};
  }
  return result;
}
isequal(gen(1000), gen(1000));
```

This throws “RangeError: Maximum call stack size exceeded”.

I see that [a while ago you said][1] (if I interpret correctly) that
many of Lodash’s functions, which happen to be implemented recursively,
are known to blow the stack on large inputs, and that this is wontfix.
Is this correct, and is it still the case? I see that the `isEqual`
implementations already track some parts of the stack manually.

[1]: https://github.com/lodash/lodash/issues/978#issuecomment-74978220

**Comment by jdalton** [comment]
Hi @wchargin!

Yes, it is known and it is still the case.

**Comment by wchargin** [comment]
Okay. Thanks for the quick response, and thanks for all your work on
lodash. :-)
