### ISSUE TITLE
Find or FindLastIndex , FindIndex  return 1 when we try to find null value

### ISSUE THREAD

**Issue by EsmeraldiBejolli** [lodash/lodash#4020]
```javascript 
const arr = [1,2,3,4,5,6,7,8,9]

console.log(_.find(arr, null))

code above return 1 instead of undefined when we look for null values

**Comment by jdalton** [comment]
Hi @EsmeraldiBejolli!

The [`_.find`](http://lodash.com/docs#find) method accepts a predicate function and not the value to find. By passing `null` as the predicate it defaults to an `_.identity` function which passes the first value `1`, which is truthy and completes the search.
