### ISSUE TITLE
map: add optional third argument to specify accumulator object

### ISSUE THREAD

**Issue by fresidue** [lodash/lodash#4021]
At present, map is basically a special case reduce, where the acc object is always an array. Sometimes it would be nice to use map on objects and return another object

An example of how I would like to use it:
```js
const a = {a: 'a', b: 'b'}
const b = _.map(a, val => val + 'c', {})  // => {a: 'ac', b: 'bc} instead of ['ac', 'bc']
```
At present the most convenient way to accomplish this general type of transformation (as far as i can tell) is:
```js
const b = _.assignWith({}, a, (xx, val) => val + 'c') // placeholder variable needs to be included
```
Another option is the even lengthier:
```js
const b = _.transform(a, (acc, value, key) => {
  acc[key] = value + 'c'
}, {})
```

In the end, I feel like the syntax would look a little cleaner for a use-case that seems to pop up every now  and then, and backwards compatibility would be maintained.

**Comment by jdalton** [comment]
Hi @fresidue!

I'm not looking to overload functionality like this. I'm moving away from overloading methods into creating more specialized ones (it makes cherry-picking easier and bundle sizes smaller). From a per JS lang side of things you can use `Object.entries()` or `Object.keys` plus `Array#reduce`.

**Comment by StreetStrider** [comment]
@fresidue since you're not afraid of reduce, look on transducers, they allow to specify accumulator type.

**Comment by fresidue** [comment]
Thanks for responding, and I guess I mainly agree with you. I realize that there are many ways to implement this use-case. I suppose my main point would be that in the same way that map is effectively a special-case implementation of reduce
```js
const map = (obj, func) => _.reduce(obj, (acc, val) => {
  acc.push(func(val, index, obj))
  return acc
}, [])
```
it would be nice/convenient to have a corresponding shortcut for when you want to transform object values while preserving the keys. Implementing this as a separate specialized function would be fine, but it seems like all the obvious good words (like transform, copy) are already taken :)
```js
const mapObj = (obj, func) => _.reduce(obj, (acc, val, key) => {
  acc[key] = func(val, key, obj)
  return acc
}, {})
```
Just some food for thought..

**Comment by StreetStrider** [comment]
@fresidue If we speak about distinct function, there's `mapValues`.

**Comment by fresidue** [comment]
Yeah. I feel like a dolt.. thanks @StreetStrider
