### ISSUE TITLE
Support arrow function in debounce

### ISSUE THREAD

**Issue by Pranav-Dakshina** [lodash/lodash#4022]
Hi,

- When I try use debounce with arrow functions, it throws an error saying expected a function. 
```
if (typeof func != 'function') {
        throw new TypeError(FUNC_ERROR_TEXT);
      }
```
- This is because `typeof` of arrow function is `undefined`
- We need to find a way to prevent this from happening

**Comment by Pranav-Dakshina** [comment]
p

**Comment by jdalton** [comment]
Hi @Pranav-Dakshina!

I'm not super sure what you're experiencing but a `typeof` check will result in `'function'` for arrow functions so that's not the issue.
