### ISSUE TITLE
Lodash omit converts array to map

### ISSUE THREAD

**Issue by shreychaturvedi123** [lodash/lodash#4024]
var a = [1,2,3]
a= _.omit(a,'key');

a becomes {0: 1, 1: 2, 2: 3, 3: 4}

It mutates array and converts it to map.

**Comment by jdalton** [comment]
Hi @shreychaturvedi123!

The `_.omit` method isn't mutating the array. You're assigning the result of `_.omit()` to the variable `a` overwriting its previous value. The `_.omit` method is an "Object" category method and will return an object.
