### ISSUE TITLE
Add mapSeries to lodash

### ISSUE THREAD

**Issue by codejamninja** [lodash/lodash#4025]
Is there an equivalent mapping function in lodash that works asycronously in a series? Bluebird has a function called mapSeries that I use for this purpose all the time, but I don't like importing bluebird just for that function.

http://bluebirdjs.com/docs/api/promise.mapseries.html

**Comment by jdalton** [comment]
Hi @codejamninja!

We tend to defer async helpers to [async](https://www.npmjs.com/package/async) or [async-es](https://www.npmjs.com/package/async-es) which is modular so you can cherry-pick.

**Comment by codejamninja** [comment]
Ah ok, thanks for the direction
