### ISSUE TITLE
No sideEffects false field in node_modules/lodash/package.json

### ISSUE THREAD

**Issue by artaommahe** [lodash/lodash#4028]
v4.17.11
There is no sideEffects: false field in `node_modules/lodash/package.json`, only this
```
{
  "name": "lodash",
  "version": "4.17.11",
  "description": "Lodash modular utilities.",
  "keywords": "modules, stdlib, util",
  "homepage": "https://lodash.com/",
  "repository": "lodash/lodash",
  "icon": "https://lodash.com/icon.svg",
  "license": "MIT",
  "main": "lodash.js",
  "author": "John-David Dalton <john.david.dalton@gmail.com> (http://allyoucanleet.com/)",
  "contributors": [
    "John-David Dalton <john.david.dalton@gmail.com> (http://allyoucanleet.com/)",
    "Mathias Bynens <mathias@qiwi.be> (https://mathiasbynens.be/)"
  ],
  "scripts": { "test": "echo \"See https://travis-ci.org/lodash-archive/lodash-cli for testing details.\"" }
}
```

so webpack cant tree-shake lodash (no one uses him but it's still in bundle)

repro
- `yarn add lodash`
- open `node_modules/lodash/package.json`
- no `sideEffects: false`

**Comment by jdalton** [comment]
Hi @artaommahe!

You'll want to use `lodash-es`.

**Comment by artaommahe** [comment]
@jdalton its another case than some lib with common modules uses lodash in some modules, you import other (pure) module, every other modules are correctly treeshacked by webpack but bundle still contains lodash due to no sideEffects false option
repro here
https://github.com/angular/angular-cli/issues/12779

**Comment by artaommahe** [comment]
@jdalton minimal repro for this case
https://github.com/artaommahe/webpack-lib-sideeffects
```js
// lib.js
import * as _ from 'lodash';

export function smth1() {
  console.log('###smth1###');
}

export function smth2() {
  console.log('###smth2###');
  _.map();
}
```
```js
// index.js
import {smth1} from './lib';

smth1();
```
- clone, `yarn install`
- `yarn webpack`
- open `./dist/bundle.js` and see lodash + `###smth1###` call and no `###smth2###`
- open `./node_modules/lodash/package.json` and add `"sideEffects": false`
- `yarn webpack`
- no lodash in `./dist/bundle.js`

**Comment by artaommahe** [comment]
@jdalton anything about this case?

**Comment by jdalton** [comment]
I'm not super sure about that. Maybe that's a webpack bug? 
I don't think it should apply to CJS modules.

**Comment by artaommahe** [comment]
@jdalton as i understand module type does not matter at all. Webpack can treeshake whole lib if it's unused at all but is imported somewhere (as in my case) if sideEffects is set to false.
We can ask @TheLarkInn about this

**Comment by CoderK** [comment]
Is there something going on? I added ```sideEffects:false``` to my local lodash package installed by npm, but tree shaking wasn't worked. It's weired.

**Comment by artaommahe** [comment]
@CoderK it works only for treeshacking lodash package wholly, not by operators. For treeshaking operators use lodash-es

**Comment by CoderK** [comment]
@artaommahe I get the point. Thanks!
