### ISSUE TITLE
cloneDeep is changing the timestamp while copying the data

### ISSUE THREAD

**Issue by webmastervishal** [lodash/lodash#4033]
I am using lodash with my react js where I am generating graphs by getting the data from the backend.
I am using `lodash cloneDeep()` to clone the props. 

But the problem I noticed here is, when I see the timestamp values after cloning the props object, timestamp gets changed automatically.

My code

```
console.log('original props', this.props.queries);
const props = _.cloneDeep(this.props);
console.log('cloned props',props.queries);

```

Console output

https://drive.google.com/file/d/1rY1_dDsc0xf7l3jO5adp9JWRZS7X1yp_/view?usp=sharing

Check the first object is the original props and second one is cloned props.
See the `device_timestamp` for both, how after cloning it gets modified.

**Comment by jdalton** [comment]
Hi @webmastervishal!

I suspect those timestamps aren't simple strings and are objects that `toString()` to a value. If that's the case you should checkout [_.isEqualWith](http://lodash.com/docs#isEqualWith) to customize the comparison.
