### ISSUE TITLE
lodash.debounce npm needs to be updated to ^4.17.5

### ISSUE THREAD

**Issue by trevorhreed** [lodash/lodash#4034]
Github is issuing a security alert against repos that have as a dependency `lodash.debounce` because it's version is behind the version in which a known security vulnerability has been fixed.

I would be happy to help if there is a way for me to contribute, but my guess is, the `lodash.debounce` npm package just needs to be updated by someone with access.

**Comment by jdalton** [comment]
That sounds like a github bug. Can you verify that a dep of a dep of a dep isn’t using the effected version ?
