### ISSUE TITLE
Security Scan 

### ISSUE THREAD

**Issue by chullak** [lodash/lodash#4037]
Some of the packages are not updated in last 2 year , black duck security scan (https://www.blackducksoftware.com/ ) is reporting that as vulnerability .  
Could you please update the following packages .

lodash.includes
lodash.isstring
lodash.isequal
lodash.mergewith
lodash.clonedeep
lodash.assign

**Comment by jdalton** [comment]
Hi @chullak!

Unfortunately without more info I'd assume that it's probably a false positive for more than a couple of those listed. You can always switch to cherry-picking methods, e.g. `const mergeWith = require("lodash/mergeWith")`, if you want.
