### ISSUE TITLE
Template does not escape ES template literals

### ISSUE THREAD

**Issue by Atekon** [lodash/lodash#4039]
About version 4.17.11

although the `template` function allows using ES template literals it does not allow it to be escaped. Case in point:

With lodash's template:
```javascript
let lodashTemplate = _.template('\${foo}')({foo: 'bar'}); 
console.log(lodashTemplate); // prints 'bar'
```

With template literals:
```javascript
let foo = 'bar';
let esTemplate = `\${foo}`;
console.log(esTemplate); // prints '${foo}'
```

Is this a bug or does `template` not allow to escape template literals (as it can be disabled with a custom interpolator function)?

**Comment by Atekon** [comment]
By reading the code, it seems to me that it only uses the es template regex if no interpolation is given (as per the docs as well), but it does not have any kind of logic for the escape regex (it always uses the  one provided/the default). 

https://github.com/lodash/lodash/blob/39a7eae40d7b97921bca466ccb65969f0cc49332/lodash.js#L14788-L14793

Wouldn't it be the same to make the default regex one that includes both the es delimiter (`${}`) and the `<%` delimiters? By using the same logic the escape template can easily get both escape characters as well.

**Comment by jdalton** [comment]
Hi @Atekon!

Our template method is pretty simple you can customize the regexes it uses to match delimiters though as [`_.templateSettings`](https://lodash.com/docs/#templateSettings) or options to the `_.template` method.
