### ISSUE TITLE
lodash/fp extends doesn't work with multiple sources

### ISSUE THREAD

**Issue by MikeYermolayev** [lodash/lodash#4040]
Looks like _.assignIn doesn't work as it's documented.

When I try to pass multiple sources like `_.extend({a:1}, [{c:3}, {a: 2, c:1}])` the output is 
```
{
  "0": { "c": 3 },
  "1": { "a": 2, "c": 1 },
  "a": 1
}
```
but should be
```
{
  a: 2,
  c: 1
}
```

Looks like a bug for me. Probably the same issue is happening with some other similar functions like _.defaults, _.merge

Tested in http://dexters-lab.io/ with lodash versions 4.17.4 and with 4.17.11

Thanks in advance

**Comment by jdalton** [comment]
Hi @MikeYermolayev!

I think you're looking for `_.assignInAll`.

**Comment by MikeYermolayev** [comment]
@jdalton thanks for you answer but docs https://gist.github.com/jfmengels/6b973b69c491375117dc#_assigninobject-sources look incorrect then. Shouldn’t it be corrected? Or it’s not the source of truth?

**Comment by jdalton** [comment]
That gist is incorrect. Check out our [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide).
