### ISSUE TITLE
is isUndefined secure?

### ISSUE THREAD

**Issue by lzl124631x** [lodash/lodash#4041]
I [remember](https://stackoverflow.com/a/34782448/3127828) months ago lodash used the following code to detect `undefined`. 

```
var undefined;
function isUndefined(value) {
  return value === undefined;
}
```

IIRC, this was for preventing the `undefined` from being assigned some other value by hacker in old browsers. I just tested on my chrome that assigning `undefined` some value doesn't work.

![image](https://user-images.githubusercontent.com/5824517/47961993-ee5d0580-dfd2-11e8-9798-e8d79172686d.png)

[The new implementation](https://github.com/lodash/lodash/blob/4ea8c2ec249be046a0f4ae32539d652194caf74f/isUndefined.js#L17) directly uses `undefined` for comparison. Does it mean "assigning `undefined` other value" is no longer a security concern?

**Comment by jdalton** [comment]
Hi @lzl124631x!

In ES5 browsers it's not a concern. I will likely end up using `void 0` for comparisons.

**Comment by lzl124631x** [comment]
@jdalton Agreed for `void 0`. Thanks!
