### ISSUE TITLE
Update individuals packages so they are up-to-date with the main one

### ISSUE THREAD

**Issue by juanjoDiaz** [lodash/lodash#4042]
I guess this is the same request as https://github.com/lodash/lodash/issues/4030

It's currently blocking me from fixing https://github.com/zemirco/json2csv/issues/333 which is produced by https://github.com/Automattic/mongoose/issues/6507

Does Lodash use any kind of CI/CD?
Would it be possible to automate it so it deploys the main package and all the individual packages at one?

**Comment by jdalton** [comment]
Hi @juanjoDiaz!

Yes we have CI runs, but no I don't want to automate releases. If you're in a pinch you should switch to the primary `lodash` package and cherry-pick the method you need, e.g; `lodash/pick`.

Dup of #4030.
