### ISSUE TITLE
Unexpected truncate() behavior

### ISSUE THREAD

**Issue by flats** [lodash/lodash#4044]
`truncate()` appears to have some strange and unpredictable behavior when the provided 'separator' includes a comma.

From the docs:
```
_.truncate('hi-diddly-ho there, neighborino', {
  'length': 24,
  'separator': /,? +/
});
// => "hi-diddly-ho there..."
```

However, with a slightly different 'length', the comma is still present in the result.
```
_.truncate('hi-diddly-ho there, neighborino', {
  'length': 22,
  'separator': /,? +/
});
// => "hi-diddly-ho there,..."
```

Moreover, the truncation can sometimes happen mid-word:
```
_.truncate('a longer string what the heck is happening here', {
  'length': 22,
  'separator': /,? +/
});
// => "a longer string wha..."
```

It can also sometimes happen after a space:
```
_.truncate('a longer string what the heck is happening here', {
  'length': 24,
  'separator': /,? +/
});
// => "a longer string what ..."
```

And that same behavior is present when using a string instead of a regular expression:
```
_.truncate('a longer string what the heck is happening here', {
  'length': 24,
  'separator': ', '
});
// => "a longer string what ..."
```

Perhaps I'm just misunderstanding the documentation? Many thanks for a wonderfully useful library.

**Comment by jdalton** [comment]
Hi @flats!


The omission of `...` is subtracted from the length and then the separator is applied.
This is why in your second example with a `length` of `22` the separator regexp does not match.

The example
```js
_.truncate('a longer string what the heck is happening here', {
  'length': 24,
  'separator': /,? +/
});
```
results in `"a longer string what..."` (no space after "what").

**Comment by flats** [comment]
@jdalton This makes sense, though I'm surprised that the separator pattern `/,? +/` doesn't match a space, given that the comma is optional. Also, this means that there's no way to guarantee not having any trailing commas with this function alone:

```
_.truncate("Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit, fugit.", {
  'length': 284,
  'separator': /,? +/
}
// => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit,..."
```

Not the end of the world, though - just means that I need to do some additional sanitizing.

Thanks very much for the prompt reply!

**Comment by jdalton** [comment]
```js
"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit, fugit.".slice(0, 284)
```
is
```js
"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit, fu"
```
now add the to it the omission `...` and it's
```js
"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit,..."
```
the `,...` does not match the separator regexp.

**Comment by flats** [comment]
@jdalton Yes, I understand. It's just somewhat unintuitive behavior, in my opinion - I would expect this function to match the separator regex before adding the omission, not after. But this is how it works! Anyway, thanks again for your time & your work on lodash.
