### ISSUE TITLE
Improve _.invoke by adding isFunction test into last check

### ISSUE THREAD

**Issue by hellamps** [lodash/lodash#4045]
Now if you are calling _.invoke with some bad path it is nicely returns undefined. But if property exists, but not a function type we are getting the runtime exception. It will be nice to add _.isFunction to last return check as well and return undefined too.

**Comment by jdalton** [comment]
Hi @hellamps!

Our APIs tend to be forgiving, they avoid erroring, unless the value resolved is supposed to be a function and it's not a function. In those cases we error early. In the case of a missing path the value is not resolved so not checked to be a function. However, once a value is resolved the method is assumed to be a function and will be executed.

**Comment by hellamps** [comment]
Hi, @Jdalton

Correct me if i'm wrong, but I'm using the _.get and _.invoke for some incoming objects which i do not trust as a module/library. So _.get gives me a nice way to pass some property to next function without long object && object.a && object.a.b ... code. 
So my intention is to use invoke instead of _.get(..) && isFunction(_.get(..._) && ...(parameter). 
What the use case for this exception when the last object is not a function?
