### ISSUE TITLE
I have no idea what this line is trying to do.

### ISSUE THREAD

**Issue by mdsantosdev** [lodash/lodash#4046]
Any ideas?
https://github.com/lodash/lodash/blob/0843bd46ef805dd03c0c8d804630804f3ba0ca3c/lodash.js#L3278

**Comment by jdalton** [comment]
Hi @mdsantosdev!

Yes! That lines raises some questions from time to time. The line is checking for a `value` and an `other` of `NaN` because `NaN` values are non-reflexive _(meaning they don't `===` themselves)_.

**Comment by mdsantosdev** [comment]
> Hi @mdsantosdev!
> 
> Yes! That lines raises some questions from time to time. The line is checking for a `value` and an `other` of `NaN` because `NaN` values are non-reflexive _(meaning they don't `===` themselves)_.

You're the man, thanks!
