### ISSUE TITLE
Is there a function could prevent a function be processed twice at same time?

### ISSUE THREAD

**Issue by cnwangjie** [lodash/lodash#4049]
Sometimes I don't want a function could be processed again if it is processing, so I need to add a flag to indicate it is processing and set it as false after the function is finished. Similar to the effect of the following code. 

```js

let _processing = false

const doSth = async () => {
	if (_processing) return
	_processing = true
	try {
		// some task that may spend a lot of time ...
	} catch (e) {
		throw e
	} finally {
		_processing = false
	}
}

```

I think it is a common need to control function likes `debounce` & `throttle`. Is there already a library that implements this feature? Or is it worth adding one such method to lodash?

**Comment by jdalton** [comment]
Hi @cnwangjie!

There isn't but this looks like very scenario specific code so you'd likely be better off keeping your custom solution.
