### ISSUE TITLE
Sum numbers in nested arrays with _.zipWith

### ISSUE THREAD

**Issue by ytliuSVN** [lodash/lodash#4050]
Let's say I have this:

```
const arr = [
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
];
arraySum(arr);

function arraySum(arr) {
  var result = _.zipWith(...arr, function(a, b, c) {
    return a + b + c;
    // => [3, 6, 9, 12, 15, 18, 21, 24, 27, 30]
  });
}
```

How can I amend the function if I have more arrays as arguments (e.g. a, b, c, ... , z).

```
_.zipWith(...arr, function(a, b, c, ... , z) {
  return a + b + c + ... + z;
}
```
I tried with `_.add`, but I got weird result.

```
function arraySum(arr) {
  var result = _.zipWith(...arr, _.add);
  // => [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
}

```

**Comment by jdalton** [comment]
Hi @ytliuSVN!

You can try:
```js
arr.map(_.sum)
```

**Comment by ytliuSVN** [comment]
Hi @jdalton!

Thanks for your reply, but I would like to sum elements at the same index in the array of arrays into a single array.

My original arrays were` [1,2,3,4,5,6,7,8,9,10]`, `[1,2,3,4,5,6,7,8,9,10]` and `[1,2,3,4,5,6,7,8,9,10]` the result should be `[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]`.

**Comment by jdalton** [comment]
Ah
```js
const sums = []
const maxLength = _.max(arrays.map((array) => array.length))

_.times(maxLength, (index) => sums[index] = _.sum(arrays.map((array) => array[index])))
```

**Comment by louMoxy** [comment]
Although this is closed, I did find a solution using ES6 spread, just in case anyone stumbles across this issue like I did. 
`
_.zipWith(...arr, (...args) => _.sum(args));
`

**Comment by ytliuSVN** [comment]
@louMoxy Good and reliable answer. Thank you so much!
