### ISSUE TITLE
[isNumber] returning false positive

### ISSUE THREAD

**Issue by gp187** [lodash/lodash#4051]
```javascript
_.isNumber(+'1'); >>>> true
_.isNumber(+'dasdad'); >>> true

+'dasdad' === NaN
```

**Comment by jdalton** [comment]
Hi @gp187!

Our `isNumber` is more like the [brand check](https://tc39.github.io/ecma262/#sec-terms-and-definitions-number-type). Since it's classified as a number, just like `Infinity` and `-Infinity`, the result is `true`.

**Comment by jdalton** [comment]
You might check out [`_.isFinite`](http://lodash.com/docs#isFinite).
