### ISSUE TITLE
_.chain mutates implicit lodash objects

### ISSUE THREAD

**Issue by bshevlin** [lodash/lodash#4052]
Calling `_(obj)` creates an implicit lodash chain. Calling `_.chain(obj)` creates an explicit one. 

But in the following snippet, the original chain is mutated instead of merely being wrapped:
```
let original = _(obj);
let wrapped = _.chain(original);
```
In this scenario, `original` will have to explicitly call `.value()` because it was modified to become an explicit chain.

**Comment by jdalton** [comment]
Hi @bshevlin!

Passing the `original` wrapper to `chain()` is just like calling `original.chain()` which converts to the sequence to an explicitly chained one.
