### ISSUE TITLE
DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by masterbater** [lodash/lodash#4056]
Nodejs 10, this error shows when using _.merge and _.extend

**Comment by jdalton** [comment]
Hi @masterbater!

I don't believe `lodash` adds an `inspect` method on its own. You might be merging or extending your own `inspect` method onto an object.

**Comment by masterbater** [comment]
I solve the issue, its because of mongoose, when iterate a mongoose result then use _.merge or _.extend, will cause that error. To solve 
`_.map(readings, async value => {
      const lastSevenDays = moment().subtract(7, "days");
      const readings = await Book.find({
        user: field.receivedFrom._id,
        date: { $gte: lastSevenDays }
      });
  //merge value._doc instead of value
      return _.extend({}, value._doc, { readingsSevenDays: readings });
    })`
