### ISSUE TITLE
add `_.centipede` alias of `_.flow`

### ISSUE THREAD

**Issue by cbray** [lodash/lodash#4057]
The results of polling a possibly statistically relevant sample of people (including several developers) strongly indicates that both the utility and the behavior of the `flow` function would be more intuitively understandable via the aliased name `centipede` (well, clearer for anyone that has seen the movie "The Human Centipede" -- and probably if they've only even seen one of the sequels). For everyone else it may or may not help, depending upon how imaginative they are; so why not?. Thanks!

**Comment by jdalton** [comment]
Hi @cbray!

Moving forward we're trying to cut-down on and remove aliases. You can always add your own aliases with `_.mixin`.
