### ISSUE TITLE
_#first() seems to be broken

### ISSUE THREAD

**Issue by fatcerberus** [lodash/lodash#4058]
Repro:
```
$ npm install underscore lodash
```
```js
const _ = require('lodash');
const __ = require('underscore');

const numbers = [];
for (let i = 0; i < 1e6; ++i)
	numbers[i] = i;

const loResult = _.chain(numbers)
	.filter(n => n % 3 === 0 || n % 5 === 0)
	.first(100)
	.map(n => n * 812)
	.reduce((a, it) => a + it)
	.value();

const usResult = __.chain(numbers)
	.filter(n => n % 3 === 0 || n % 5 === 0)
	.first(100)
	.map(n => n * 812)
	.reduce((a, it) => a + it)
	.value();

console.log(`Lodash says ${loResult}`);
console.log(`Underscore says ${usResult}`);
```

Output:
```
Lodash says undefined
Underscore says 8613696
```

If I remove the `.first()` then all seems well so apparently `first` is broken:
```
# after .first() is commented out in both chains

Lodash says 189466531334416
Underscore says 189466531334416
```

**Comment by jdalton** [comment]
Hi @fatcerberus!

Your use of [_.first](https://lodash.com/docs/#head) is incorrect.
See [this wiki](https://github.com/lodash/lodash/wiki/Migrating#underscore) for more tips migrating from Underscore.

**Comment by fatcerberus** [comment]
I actually don't use either - I was benchmarking performance of different query libraries and noticed Lodash was the only one where `.first` acted differently, so assumed it was a bug.  Weird because I could have sworn I tried `_#take` and it didn't work... but now it does.  Huh.
