### ISSUE TITLE
Idea - would love a debouncedFunction.resolve() method to cut short the wait

### ISSUE THREAD

**Issue by jamesalexmorgan** [lodash/lodash#4060]
Thanks for maintaining this awesome library awesome lodash team! I use it for everything!

Regarding `_.debounce`...

Similar to `myDebouncedFunction.cancel()`, it would be awesome if we could manually tell the function to resolve instantly instead of waiting for the rest of the timeout.

Maybe something like `myDebouncedFunction.resolve()`

When it resolves, it could resolve with the same resulting output as if we waited for the timeout to end.

Any thoughts?

**Comment by jdalton** [comment]
Hi @jamesalexmorgan!

I'm down with it. Feel free to create a PR against the `4.17.12-pre` branch.

**Comment by jamesalexmorgan** [comment]
My bad, I just saw the flush method does this, right? Sorry the name 'flush' wasn't clear to me.

Ok to close 👍

**Comment by jdalton** [comment]
Oh yeah!
