### ISSUE TITLE
vscode struggles to auto-import lodash

### ISSUE THREAD

**Issue by tnrich** [lodash/lodash#4062]
Hey there, does anyone know why vscode struggles to auto-import lodash modules?

Here I'm looking for lodash's array.compact method, but while recompose has an auto-import suggested, lodash's auto-import doesn't seem to want to show up: 
![image](https://user-images.githubusercontent.com/2730609/48576928-a7bcb480-e8ca-11e8-9871-ce0a7a1358e3.png)

If this could be remedied that would be awesome because lodash is a great library!

**Comment by jdalton** [comment]
Hi @tnrich!

I'm not too sure. You might have better luck on the vscode repo. I'm going to guess maybe it has to do with the way they prioritize their typing hints.

**Comment by tnrich** [comment]
Any response to this sentiment @jdalton : 
>It's possible that vscode needs to do something on their end, but... this functionality does seem to work fine with most other popular packages. That makes me think it probably has something to do with how lodash is exporting its modules or how lodash is arranging its declaration files.

>If most other packages work it seems like one as popular as lodash should work as well.

?

It seems like it could be fixed on our end? (And maybe has to because I'm not really getting anywhere with https://github.com/Microsoft/vscode/issues/63239 and  https://github.com/microsoft/TypeScript/issues/29039)

Thanks!

**Comment by jdalton** [comment]
Lodash is a popular package (the most popular in fact) so the pressure, if the issue is wide spread enough, should raise the priority for vscode. You're likely seeing an issue with `lodash` or `lodash-es` compared to others because Lodash has ~643 modules for it to possibly pull in.

**Comment by ricsam** [comment]
To just fix the problem I do the following:
```
yarn add lodash@npm:lodash-es
yarn add @types/lodash@npm:@types/lodash-es
```

**Comment by xuych** [comment]
`npm i -d @types/lodash`， restarted vscode, then it works.

**Comment by sarimarton** [comment]
> `npm i -d @types/lodash`， restarted vscode, then it works.

Adding @types does not make it work for me.
