### ISSUE TITLE
Difference in behaviour for _.set

### ISSUE THREAD

**Issue by smmribeiro** [lodash/lodash#4063]
Hello, I was upgrading lodash in a project and caught a difference in behaviour in the following code:

		var arr = [{a: 1}, {a: 2}, {a: 3}];
		_.set(arr, '[0].a.b', {});
		var result = JSON.stringify(arr);

In v4.14.0: [{"a":1},{"a":2},{"a":3}]
In v4.17.11: [{"a":{"b":{}}},{"a":2},{"a":3}]

Doing some tests I think the difference appeared in v4.15.0 (didn't test v4.14.2).

Why did this happen?
Was it deliberate? Was it a bug that existed and got fixed? Or is it a bug now?

Thank you.

**Comment by jdalton** [comment]
Hi @smmribeiro!

The 4.17.11 behavior appears to be correct.
