### ISSUE TITLE
Inconsistent behavior of _.merge

### ISSUE THREAD

**Issue by enyosolutions** [lodash/lodash#4064]
Hello,

I have a question because i have an inconstistent behavior on my lodash (`"4.17.10"`)
```
_.merge({roles:['a']}, {car: 1, roles:['b']})

{roles: Array(1), car: 1}
car: 1
roles: ["b"]
```

```
_.merge({roles:['a']}, {car: 1, roles:['b', 'd']})
{roles: Array(2), car: 1}
car: 1
roles: (2) ["b", "d"]
```

is it by design ?

**Comment by jdalton** [comment]
Hi @enyosolutions!

It's not really inconsistent. The `roles` values from the source object are being merged into that of the destination object just as `_.merge({ a: 1, b: 2 }, { a: 2 })` will merge `a` of source into destination to make `{a: 2, b: 2}`

**Comment by enyosolutions** [comment]
Damn sorry i wasnt paying attention. i must be more tired than i seems.
