### ISSUE TITLE
`sortBy` evaluates all iteratees even on non-ties

### ISSUE THREAD

**Issue by wchargin** [lodash/lodash#4067]
Upon evaluating

    lodash.sortBy([2, 1], (x) => x, (x) => void console.log(x))

I was a bit surprised to see that two log statements are in fact printed
to the console, even though there are no ties on the first iteratee and
so the second iteratee need never be evaluated.

Upon looking at the implementation, it becomes clearer why this is the
case: you precompute all the `criteria` for each element so that they
only have to be computed once. But this makes use cases in which there
is a potentially expensive “fallback iteratee”, like

    sortBy(
        objects,
        (x) => x.id,  // almost all objects have distinct IDs
        (x) => JSON.stringify(x)  // expensive, but should happen only rarely!
    );

much more costly.

(All this holds the same for `orderBy`, of course.)

One could imagine an implementation that computes each criterion lazily,
only as it is needed to break a tie. From reading the docs, this would
appear to be a backward-compatible change; you don’t currently specify
under which circumstances the iteratees are invoked (which is good!).

Would you be interested in making or accepting such a change?

**Comment by jdalton** [comment]
Hi @wchargin!

I'm totally interested. If you're up for it you can make the PR against the `4.17.12-pre` branch.

**Comment by wchargin** [comment]
I’ve been sitting on a patch for this that I’ve tested but not
benchmarked… I’ll try to get to that this weekend and report back.

**Comment by jdalton** [comment]
Moved to #4140.
