### ISSUE TITLE
_.find not work properly

### ISSUE THREAD

**Issue by YuriiChornyi** [lodash/lodash#4068]
why !null shows trur values but not false 
![image](https://user-images.githubusercontent.com/17709640/48840264-ca514080-ed96-11e8-8b08-238400fe5145.png)

**Comment by YuriiChornyi** [comment]
How to write _.find(users, ['active', ???]) to result true and false

**Comment by Page-** [comment]
`!null` is equivalent to writing `true`, I don't think it's possible to do what you want with the shorthand version but you can try:
```js
var users = {
  'barney':  { 'age': 36, 'active': null },
  'fred':    { 'age': 40, 'active': false },
  'pebbles': { 'age': 1,  'active': true }
};
 
_.find(users, function(v) { return v.active != null });

**Comment by YuriiChornyi** [comment]
> `!null` is equivalent to writing `true`, I don't think it's possible to do what you want with the shorthand version but you can try:
> 
> ```js
> var users = {
>   'barney':  { 'age': 36, 'active': null },
>   'fred':    { 'age': 40, 'active': false },
>   'pebbles': { 'age': 1,  'active': true }
> };
>  
> _.find(users, function(v) { return v.active != null });
> _.find(users, _.conforms({ active: _.negate(_.isNil) }));
> ```

thanks a lot
