### ISSUE TITLE
_.sortedIndex return question

### ISSUE THREAD

**Issue by kimsangyeon** [lodash/lodash#4072]
```
 * @returns {number} Returns the index at which `value` should be inserted
 *  into `array`.
 * @example
 *
 * sortedIndex([30, 50], 40)
 * // => 1
```

NaN is returned if the first argument to sortedIndex is a non-array value. Don't you think you need to modify the annotation or exception to the return value?

- sortedIndexBy.js
- sortedLastIndex.js
- sortedLastIndexBy.js
@returns {number}

**Comment by jdalton** [comment]
Hi @kimsangyeon!

`NaN` is still a number type.
