### ISSUE TITLE
Difference behavior between lodash.js and core js

### ISSUE THREAD

**Issue by Vnthf** [lodash/lodash#4073]
lodash.js works below code
```
var users = [
  { 'user': 'barney',  'age': 36, 'active': true },
  { 'user': 'fred',    'age': 40, 'active': false },
  { 'user': 'pebbles', 'age': 1,  'active': true }
];
 
// The `_.matchesProperty` iteratee shorthand.
_.find(users, ['active', false]);
```
But In core.js, it dose not work. It returns undefined. Becuase baseIteratee function is different. It does not contain matchesProperty. Why is this happening?

**Comment by jdalton** [comment]
Hi @Vnthf!

The core build contains what we consider to be core functionality without a lot of the extras. For more info on build differences see our [wiki entry on them](https://github.com/lodash/lodash/wiki/Build-Differences).
