### ISSUE TITLE
camelCase calls toLowerCase twice

### ISSUE THREAD

**Issue by SeanMeyer** [lodash/lodash#4075]
The camelCase function code is calling toLowerCase on each word:
https://github.com/lodash/lodash/blob/136d5253e724838ca701fb54db09f18b618c127e/camelCase.js#L23-L28

The capitalize function also calls toLowerCase though, so this is being performed twice on each word (except the first):
https://github.com/lodash/lodash/blob/136d5253e724838ca701fb54db09f18b618c127e/capitalize.js#L16

Since string manipulations can be pretty costly, I think this is worth fixing. 

This is my first contribution to this project, so I apologize if I've missed anything.

**Comment by jdalton** [comment]
Hi @SeanMeyer!

If you'd like to create a PR against our `v4.17.12-pre` branch that would rock!
