### ISSUE TITLE
 _.upperFirst('LODASH') return 'LODASH' 

### ISSUE THREAD

**Issue by h2ck4u** [lodash/lodash#4086]
Hello, I'm front-end developer in South Korea.
I have some question in `._upperFirst` method

i have seen comment on method.
 @example
 _.upperFirst('fred');  => 'Fred'
 _.upperFirst('FRED'); => 'FRED'

 1. _.upperFirst('lodash') => 'Lodash'
 2. _.upperFirst('loDASH') => 'LoDASH'
 3. _.upperFirst('LODASH') => 'LODASH'

i expect example of 1,2,3 result => 'Lodash' 

If my expectation is correct can i fix `._upperFirst` ?

thank you,

**Comment by blikblum** [comment]
try capitalize
