### ISSUE TITLE
Make promised 4.17.12 release with fix for issue 3951

### ISSUE THREAD

**Issue by hlovdal** [lodash/lodash#4088]
Could you please make a 4.17.12 release like [intended earlier](https://github.com/lodash/lodash/issues/3951#issuecomment-420547807)?

I have several tests that break every time I run `npm audit fix` and forget that lodash currently must be locked to version 4.17.4.

**Comment by jdalton** [comment]
Hi @hlovdal!

Thanks for the ping. I'll look into publishing in a few days.

**Comment by hlovdal** [comment]
Ping again. https://github.com/lodash/lodash/releases only lists a `4.17.12-pre` version and https://www.npmjs.com/package/lodash lists 4.17.11 as latest.

**Comment by jdalton** [comment]
As you may have noticed I'm holding off on the release for the time being. We'll be applying some security patches soon and the release will follow.
