### ISSUE TITLE
Optionally extend Array / Object prototypes with lodash functions

### ISSUE THREAD

**Issue by pistacchio** [lodash/lodash#409]
While extending base types like Object and Array is generally a bad idea, being able to make lodash extend those types with the functions it provides could turn into a much more readable and chainable code, in controlled environments.

For example, string.js (http://stringjs.com) is a popular library that provides string utilities not found in String (trimming, padding...). It has a function (http://stringjs.com/#methods/extendprototype) that extends the String prototype, so that one can write the clearer

```
'Your name is JP'.right(2); 
```

instead of the default

```
S('Your name is JP').right(2).toString();
```

It would be great if lodash would do the same

``` javascript
_.extendPrototypes()
[1, [2], 2, 4].flatten().uniq();
_.restorePrototypes();
```

**Comment by msafi** [comment]
Why not extend with `_` namespace? Like `[1, [2], 2, 4]._flatten()._uniq();`? What can go wrong by extending with a namespace like this?

**Comment by d10** [comment]
This could cause unexpected issues with code iterating over native prototypes.

**Comment by msafi** [comment]
@d10 why would some code want to iterate over native prototypes? Isn't there a way for them to detect non-native properties dynamically? Still, wouldn't that be their problem since JavaScript allows anyone to extend native prototypes?

**Comment by pistacchio** [comment]
I second msafi's proposal. I think this kind of integrations is much clearer if one prefers OOP-style. Plus, it'd be optional, so I don't see what could be wrong in offering a richer library.

**Comment by jdalton** [comment]
I stand by my [earlier comments](https://github.com/lodash/lodash/issues/409#issuecomment-29527543).
