### ISSUE TITLE
Use Map instead of MapCache in memoize

### ISSUE THREAD

**Issue by blikblum** [lodash/lodash#4094]
By replacing MapCache by Map a considered amount of code (implementations of MapCache, Hash and ListCache) can be saved for those using only memoize

Even if MapCache is [still faster](https://github.com/lodash/lodash/issues/3117) than Map (may not be true anymore due to [recent](https://v8.dev/blog/hash-code) browser optimizations) probably is not relevant is real world usage. So IMO the trade off is worth.

Alternatively MapCache can be exposed to those that need this specific kind of optimization

**Comment by jdalton** [comment]
Go for it @blikblum!
