### ISSUE TITLE
Implement tests for master (v5) branch

### ISSUE THREAD

**Issue by blikblum** [lodash/lodash#4096]
I'm willing to add tests to master branch, but before doing any work i would like to know if there's already any idea of how should be implemented

The way i visualized was creating a temporary build with rollup will all functions and hook it into the tests

Let me know if/how i should implement

**Comment by jdalton** [comment]
I'd like to break them into smaller test files. The large test file of the past became too hard to work with. Using mocha is fine. You can load the modules with [`esm`](http://npmjs.com/esm).

**Comment by StreetStrider** [comment]
I use mocha with structure like this:
```json
"unit": "mocha -r esm -r test/globals test/*.test.js",
```
Where in globals I add `expect` and other frequently required stuff. Tests are subdivided by module with almost 1-to-1 parity in most of the cases. Like `test/forOwn.test.js` which will correspond to `forOwn`.

**Comment by blikblum** [comment]
> 
> 
> I'd like to break them into smaller test files. The large test file of the past became too hard to work with. Using mocha is fine. You can load the modules with [`esm`](http://npmjs.com/esm).

The test suite is quite large, so doing those tasks (splitting tests and migrating to mocha) manually is infeasible. 

Recently i looked how to automate the conversion of a QUnit test suite (backbone) to mocha or jest and did not find any tool

So until there's a automated way of doing it, i will hold this task for now
