### ISSUE TITLE
FP docs for invokeArgs slightly misleading

### ISSUE THREAD

**Issue by chmac** [lodash/lodash#4097]
Here's what the wiki currently says:

> Methods that expect an array as their last or only argument:<br>
> `assignAll`, `assignAllWith`, `assignInAll`, `assignInAllWith`, `defaultsAll`,
`defaultsDeepAll`, `invokeArgs`, `invokeArgsMap`, `mergeAll`, `mergeAllWith`,
`partial`, `partialRight`, `without`, & `zipAll`

The argument order for `invokeArgs` is `(path, [args], object)`. Therefore the array is the second argument, not the last. I've replaced the paragraph above with two paragraphs in the wiki:

> Methods that expect an array as their last or only argument:<br>
> `assignAll`, `assignAllWith`, `assignInAll`, `assignInAllWith`, `defaultsAll`,
`defaultsDeepAll`, `invokeArgs`, `invokeArgsMap`, `mergeAll`, `mergeAllWith`,
`partial`, `partialRight`, `without`, & `zipAll`
> 
> Methods that expect an array as their second argument:<br>
> `invokeArgs`, & `invokeArgsMap`

Not sure if any of the other methods there also expect an array as their second argument. I'm filing this issue here only because it seems like the wiki edit is unlikely to be noticed by anyone, and perhaps I've misunderstood something and the docs were actually correct.

**Comment by jdalton** [comment]
HI @chmac!

Go ahead and edit the wiki, I'll transfer the changes to the doc wiki builder.

**Comment by chmac** [comment]
@jdalton 👍 I edited the wiki as I was submitting the issue, just wanted to make sure the edit was reviewed.

**Comment by dietergeerts** [comment]
I came here after getting confused with `invokeArgs`, as I thought that the second and last arguments needs to be an array. I think that they should only be listed in the second group, and not in the ones that says 'Methods that expect an array as their last or only argument', no?
