### ISSUE TITLE
isMatchWith doesn't call customizer when targetObject does not contain some property of sourceObject

### ISSUE THREAD

**Issue by Kobico** [lodash/lodash#4098]
example: 
**calling the customizer**
isMatchWith({a:'b'}, {a: 'f'}, (t,c) => console.log(t,c))
**b f**
false

**not calling the customizer**
isMatchWith({a:'b'}, {a: 'f',b:'c'}, (t,c) => console.log(t,c))
**[nothing output here, not even the propeties that exist in the targetObject like 'a']**
false

**expected**
customizer will be invoke on every match
**actual**
customizer is not called if source object contain properties that are missed in the target object

**Comment by jdalton** [comment]
Hi @Kobico!

The customizer kicks in if a value is there to customize. In the case of `isMatch` it does a pre-flight to detect if the keys are present. If they aren't then the match fails before progressing to a deeper comparison.
