### ISSUE TITLE
baseMerge and baseClone does not works because of missing keysIn 

### ISSUE THREAD

**Issue by blikblum** [lodash/lodash#4099]
baseMerge and baseClone imports keysIn which does not exists anymore

For the record baseKeysIn was removed [here](https://github.com/lodash/lodash/commit/58e484f389762750a13b0d8f952eb80235a31649)

should baseKeysIn be restored or do the same as [here](https://github.com/lodash/lodash/commit/58e484f389762750a13b0d8f952eb80235a31649#diff-5c9720962ba84f94900532fc93850ba5L12)?

**Comment by jdalton** [comment]
Hi @blikblum!

You can use a simple `for-in` loop.
