### ISSUE TITLE
[request] filterOut and keep

### ISSUE THREAD

**Issue by andreineculau** [lodash/lodash#4108]
the docs for `_.filter` mention

> Note: Unlike _.remove, this method returns a new array.

yet `_.remove` is not the equivalent of `_.filter`, except for the mutability.

AFAICS there is no function that returns a new array without those where the predicate returns true.

The equivalent functions that I expect would be smth like
* `_.filter` vs `_.keep` (new, mutates, returns removed items)
* `_.filterOut` (new, doesn't mutate) vs `_.remove`

The functionality of say `_.remove` can be achieved with `_.filter`, no doubt. **But one cannot use the shorthand predicates**, thus this request.

**Comment by jdalton** [comment]
Hi @andreineculau!

This is where helpers like [_.negate](https://lodash.com/docs#negate) and [_.iteratee](https://lodash.com/docs/#iteratee) can be used to get the desired `_.filter` behavior.
