### ISSUE TITLE
Size statistics of modules plus its dependencies (master/v5 branch)

### ISSUE THREAD

**Issue by blikblum** [lodash/lodash#4109]
I've gathered the size statistics of the modules.
Both own size and bundled ones. Used rollup and minified with terser

The raw results can be found at https://gist.github.com/blikblum/68880bc62dbac727d107013be4c2fa19
The script used to generate at https://github.com/blikblum/lodash/blob/query-size-rollup/tools/getsize.js
The formatted data, with sorting can be found at: https://codepen.io/blikblum/pen/dwyoZy?editors=1100

This can be useful to see where the size is coming and to inform users of the size cost of the modules

**Comment by jdalton** [comment]
Wow, thank you @blikblum!

You might also dig [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer).
