### ISSUE TITLE
sumBy and sum for null value aren't consistent

### ISSUE THREAD

**Issue by swchen** [lodash/lodash#4110]
```
var objects = [{ 'n': null }, { 'n': null }];
_.sumBy(objects, function(o) { return o.n; });
// => 0

_.sum([null, null]);
// => 0
```

```
var objects = [{ 'n': null },];
_.sumBy(objects, function(o) { return o.n; });
// => null

_.sum([null]);
// => null
```

**Comment by jdalton** [comment]
Hi @swchen!

This is more a JS thing. Our `sum` methods don't coerce values to numbers so when they are `+`'d together you get the coercion. In this case `null + null` is `0`.

**Comment by swchen** [comment]
Yes, you're right.

But, it depends on `sum` 's implementation. We may define `sum` like : 
```
const sum = arr => _.reduce(arr, (rst, it) => {
  return rst + it;
}, 0);
sum([null, null]);
// => 0
sum([null]);
// => 0
```

Actually, the inconsistency may make bugs. cause the `sum` result depend on the array's length, if just test `array = null` and `normal array` , bug will be hide. 

It can be easily avoided, just like 
```
_.sum(xxx) || 0;
// or 
_.sum(xxx) + 0;
```
But someone may not notice this inconsistency.

**Comment by borkxs** [comment]
@swijw predicted the future

> cause the `sum` result depend on the array's length

This is surprising behavior:

```
  _.sum([]),                 // 0
  _.sum([null]),             // null
  _.sum([null, null]),       // 0
  _.sum([null, null, null])  // 0
```
