### ISSUE TITLE
Webpack module concatenation is prevented by use of injected variable (module)

### ISSUE THREAD

**Issue by blikblum** [lodash/lodash#4119]
When bundling `cloneBuffer.js`, `nodeTypes.js` and `isBuffer.js`, webpack prevents module concatenation. The following message is show:

```
ModuleConcatenation bailout: Cannot concat with ./node_modules/lodash/.internal/cloneBuffer.js (<- Module uses injected variables (module))
```

**Comment by jdalton** [comment]
This is a false positive by webpack (you should file a bug on them for it). We don't access the value unless it exists. We preface our access with typeof checks. There may be a way to tell webpack it's OKAY and filing an issue will surface that.

**Comment by blikblum** [comment]
For the record, in webpack v5 this will be fixed: https://github.com/webpack/changelog-v5/blob/master/README.md#minor-changes
