### ISSUE TITLE
`uniqWith` with objects

### ISSUE THREAD

**Issue by pranshuchittora** [lodash/lodash#4121]
Recently I wanted to compare an array of objects by using `uniqWith(arr, isEqual)` in order to create a unique array (set) of objects. But each object has it's own timestamp. So is it possible to compare on the basis of specific key's?

**Comment by jonathanhughes** [comment]
Have you tried a custom comparator function?  Passing in a comparator that checks the specific keys you want to compare `(o1, o2) => o1.prop1 === o2.prop1` for example, instead of `isEqual` should produce the results you are looking for.

**Comment by jdalton** [comment]
You could combo @jonathanhughes' approach and create a `customizer` that for a specific key does the direct comparison else uses `isEqual`.
