### ISSUE TITLE
Status on next lodash major version

### ISSUE THREAD

**Issue by davidhouweling** [lodash/lodash#4122]
The roadmap has the next lodash version as ~2018 but we're now basically at the end with no new version, and from what I can see no branch of active development for it.

A lot has changed since the last major version was first published and it would be great to see a lot of internal code and dependencies replaced with ES based code (benefiting bundle size by passing more responsibility to babel/transpiler... If you didn't want to support older ways of doing things by dropping browser support, that is left purely to the transpiler to worry about and not lodash).

**Comment by jdalton** [comment]
Hi @davidhouweling!

It looks like the ~2018 is going to be ~2019. Getting ESM syntax 💯 in Node has been a bit more challenging than expected. It's getting there though with [`esm`](npmjs.com/esm).

**Comment by jdalton** [comment]
For those that may not know I'm on the TC39, the technical committee that defines ECMAScript (JavaScript), a Node core member, and a Node Modules Working Group member. In prep for Lodash v5 I saw that Node was lacking voices to represent the developer experience and headed towards an outcome not super appealing to anyone, so I decided to get involved. I'm pushing on Node from two sides, the ecosystem with the [`esm`](https://npmjs.com/esm) loader to show what an ideal "just works" outcome is like and from within Node/TC39 to nudge them in a more developer experience centric way of thinking. This is a slooow process, but with Lodash for the most part stable I thought getting ESM ironed out was the better thing to invest in. You can see this from a contribution standpoint, by looking at the contribution chart for [Lodash](https://github.com/lodash/lodash/graphs/contributors) and [`esm`](https://github.com/standard-things/esm/graphs/contributors), as one drops off the other picks up.

On the [`esm`](https://npmjs.com/esm) loader front I'm wrapping up major features like Jest support, WASM support, 💯 test262 test pass for relevant tests, and integration into some key ecosystem projects. For 2019, the last thing to tackle in [`esm`](https://npmjs.com/esm) is performance. I have ideas for how to make it considerably faster than native. So with that I think I'll be able to shift focus back to delivering a v5 for Lodash in 2019.

**Comment by davidhouweling** [comment]
Thank you @jdalton for the detailed response, and with that I definitely agree to the priorities you have for yourself. Look forward to seeing what comes of both ESM and Lodash in 2019.
