### ISSUE TITLE
A problem about _.camelCase()

### ISSUE THREAD

**Issue by asilinwei** [lodash/lodash#4124]
Hi, I want to know the implement of _.camelCase(), I try a test case like this:
`_.camelCase('Foo\'s Bar');  // => 'foosBar'`
The result is normal.
But, when I try this:
`_.camelCase('Foo"s Bar') // => 'fooSBar'`
The letter 'S' is **upper case**, it's not correct. 'S' should be in **lower case** like the first test case.
So I see the code of _.camelCase(), `var rsApos = "['\u2019]"` is lack of **double quote**. It should be `"['\u2019\"]"`.

**Comment by jdalton** [comment]
Hi @asilinwei!

I believe a double quote as an apostrophe would not be valid. It looks like you'd be better off with your own custom one-off version of `camelCase`.
