### ISSUE TITLE
Giving reduce() a function as an initial value

### ISSUE THREAD

**Issue by insonifi** [lodash/lodash#4125]
I am wondering for long time, but haven't found any answer on the web. Why lodash `reduce()` doesn't accept stub-functions as an initial value?
I see very natural to do something like this:
```
const stubState = () => ({avg: 0, count: 0});
const countedAvg = reduce(
    (state, {value}) => ({
        avg: (state.avg + value) / 2,
        count: state.count + 1
    }),
    stubState
);

countedAvg(samples);
```
https://runkit.com/insonifi/5c17bc61317a9a001575595f

And yet, it doesn't recognize it work. Can it be useful?

**Comment by jdalton** [comment]
Hi @insonifi!

The initial value is a value and not a function which returns a value.

**Comment by insonifi** [comment]
I know. My question is, why not make it accept function, so that curried version of `reduce()` could be initialised each time we call it with iterable.

**Comment by StreetStrider** [comment]
@insonifi :thinking: if do so, how to distinguish function as initializer from function as value? If do your change, all values must be wrapped in `constant(value)` as a consequence.

**Comment by insonifi** [comment]
@StreetStrider, I never thought of that before. What are use-cases for function as an initial value for `reduce()`?

**Comment by StreetStrider** [comment]
@insonifi for instance, function compositon, function decoration.
