### ISSUE TITLE
_.trimStart("link_id", "link_") returns "d" instead of "id"

### ISSUE THREAD

**Issue by loonyhead** [lodash/lodash#4126]
just for reference
https://jsbin.com/humonovihu/edit?js,console

**Comment by jdalton** [comment]
Hi! 

The chars string is a string of individual chars to remove and not a substring match to remove.

**Comment by loonyhead** [comment]
Ah, I see, thanks. I thought it otherwise.

**Comment by lafeer** [comment]
@jdalton is there a method for removing a substring match tho?
