### ISSUE TITLE
sumBy calculated value decimal error for .89

### ISSUE THREAD

**Issue by kn96** [lodash/lodash#4128]
When trying to calculate values with  decimal value .89, the sum changes to `.8899999999999`

`var objects = [{ 'n': 23 }, { 'n': 33 }, { 'n': 36 }, { 'n': 77 }, { 'n': 1023.89 }];
_.sumBy(objects, 'n');`

> 1192.8899999999999

This is happening only when the decimal value is .89 and the range of total is 1024.89 to 1192.89

**Comment by IanSavchenko** [comment]
I guess this is how floats work. If you run in your browser console `1023.89 + 1` you will get `1024.8899999999999`. A more famous example is that `0.1 + 0.2` will result in `0.30000000000000004` and it even has it's own page https://0.30000000000000004.com/
