### ISSUE TITLE
`_.mapFind`?

### ISSUE THREAD

**Issue by RobertFischer** [lodash/lodash#4129]
Coming from a lazily-evaluated language, one of the bad habits that I have in JavaScript is code like the following:

```javascript
const foos = [ /*... some elements ...*/ ];
return _.find(_.map(foos, "isAwesome"));
```

Unfortunately, this maps _all_ the elements of the array, and then performs the `find` operation over the resulting array. It'd be really nice if there was a hybrid of `find` and `map` which performs the `find` on the mapped elements, and only maps those elements until it gets one that resolves to `true`.

I'm aware that I can implement this through a reduce, but that's technically true of anything within spitting distance of a list comprehension. The reason we have simpler utility methods is to make it clearer (and more performant) in our code, and I think this would be a useful addition.

If folks are generally interested and positively disposed towards this addition, I'd be happy to provide a proposed `_.mapFind` implementation (modeled after `find`, unless I'm told otherwise).

**Comment by jdalton** [comment]
Hi @RobertFischer!

Using our chaining syntax [we have a heuristic in place](https://lodash.com/docs/4.17.11#lodash) that can enable shortcut fusion of iteration for `find` and `map`.
