### ISSUE TITLE
Empty slots in array

### ISSUE THREAD

**Issue by YuriGor** [lodash/lodash#4131]
Looks like empty slots are totally not supported and all the array works blindly relies on it's length?

```js
    var o = { a: 0, b: 1, c: 2 };
    delete o.b;

    console.log('a?', _.has(o, 'a')); 
// true
    console.log('b?', _.has(o, 'b')); 
// false
    console.log('c?', _.has(o, 'c')); 
// true

    var a = ['a', 'b', 'c'];
    delete a[1];

    console.log('0?', _.has(a, '0')); 
// true
    console.log('1?', _.has(a, '1')); 
// TRUE?
    console.log('2?', _.has(a, '2')); 
// true

    var slots = ['start', , 'middle', , 'finish'];

    slots.forEach(console.log);
// start 0 [....
// middle 2 [....
// finish 4 [....

    _.forOwn(slots, console.log);
// start 0 [....
// undefined '1' [... // string key?
// middle 2 [....
// undefined '3' [.... // string key?
// finish 4 [....
```

Is it by design? If so, could you please explain why? 

I am working on deep traversal methods, so it's important for me to not produce phantom paths in case of object deep filtering for example, but lodash seems to not use `in` operator when he checks array items for existence.

**Comment by jdalton** [comment]
Hi @YuriGor!

Lodash treats all arrays as dense (non-sparse) for simplicity and consistency. Earlier versions of Lodash which supported IE8 avoided handling sparse arrays because IE8 vs. other browsers would consider different things as sparse for arrays. In general treating all arrays as dense simplifies implementations too.

**Comment by YuriGor** [comment]
Thank you for reply, 
could you please give me an advice:
when developer wants to `filterDeep` object and some excluded paths affected and array in the middle of the object and made this array sparse, will developer expect by default to get result filtered object with sparse array or dense?
```js
    var obj = { a: [{ b: false }, { b: true }, { b: false }] };
    var filtrate = _.filterDeep(obj, (v) => v === true, { leafsOnly: true });
    console.log('filtrate', filtrate);
// filtrate { a: [ <1 empty item>, { b: true } ] }
// or
// filtrate { a: [ { b: true } ] }
```
The main question here is to mutate paths in the result object or not.
I will add an option to control this behavior, but what will be most often use case to set as default?

**Comment by jdalton** [comment]
If you want to treat an array as any other object then you can use an `in` or `hasOwnProperty` check.

**Comment by YuriGor** [comment]
Yes, I already added `in` check and it works, thank you. 
But my question is about what will make more sense by default:
- to return result objects with condensed arrays within (this will mean paths of object changed, since all the arrays are re-indexed) 
- or to keep all the original object paths, but with possible sparse arrays inside.

**Comment by jdalton** [comment]
I'd condense by default, that's what existing filters in the language do - like `Array#filter`, with the option to avoid it as users request it.

**Comment by YuriGor** [comment]
Good point, thank you, I'll make same.
