### ISSUE TITLE
Partition with multiple predicates

### ISSUE THREAD

**Issue by kalashw** [lodash/lodash#4132]
`_.partition` is insanely useful for dividing a set of data into several named subsets.

Quite often, it is needed to divide a set of objects into more than two subsets.
A simple example:
```
const issues = [ 
  { id: 1, state: 'open' },
  { id: 2, state: 'closed' },
  { id: 3, state: 'in-progress' },
  { id: 4, state: 'open' },
];
```
Assume you need all three sets of open, closed and in-progress issues separately.

What you do now, is write:
```
const [ openIssues, notOpenIssues ] = _.partition(issues, { state: 'open' });
const [ closedIssues, notOpenNotClosedIssues ] = _.partition(notOpenIssues, { state: 'closed' });
const [ inProgressIssues, otherIssues ] = _.partition(notOpenNotClosedIssues, { state: 'in-progress' });
```
The other way would be to use multiple filters, that will go through the original array extra times which seems as extra work.

My proposition:
```
const [ openIssues, closedIssues, inProgressIssues, otherIssues ] =
  _.partition(issues, { state: 'open' }, { state: 'closed' }, { state: 'in-progress' });
```

What is expected, that `openIssues` will be all the issues that satisfy first predicate, then `closedIssues` will be all the issues that satisfy second predicate but do not satisfy the first one, etc.

**Comment by jdalton** [comment]
Thanks @kalashw!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by coreyjewett** [comment]
I believe `groupBy` is what @kalashw was looking for:

    > _.groupBy(issues, 'state')
    { open: [ { id: 1, state: 'open' }, { id: 4, state: 'open' } ],
      closed: [ { id: 2, state: 'closed' } ],
      'in-progress': [ { id: 3, state: 'in-progress' } ] }

**Comment by bsurai** [comment]
@coreyjewett  @kalashw @jdalton    I guess, `groupBy` isn’t so good. `partition(...)` could handle other tasks, like below

```
const isSuv = o => o.type === ‘suv’
const isBmw = o => o.brand === ‘bmw’

const cars = [{ type:’suv’, brand:’bmw’ }]

const [allSuv, allBmw] = _.partition(cars, [isSuv, isBmw])
```

Maybe you’ll find a better name for this feature.

**Comment by kalashw** [comment]
Yes, you are right @bsurai.
_.groupBy is useful, when your predicates can be expressed as a function (which is what happens in my example, so my example is not a good one).

But if your predicates are more complex, than _.groupBy unfortunately would not solve the problem.
