### ISSUE TITLE
New function: scan

### ISSUE THREAD

**Issue by polkovnikov-ph** [lodash/lodash#4133]
The bot closed [this issue](https://github.com/lodash/lodash/issues/1684) for "inactivity" during voting. So here's an issue back. I honestly have no idea how you're going to transfer votes from there.

As bot closed all the issues and this is the only and most voted feature request, does it mean that it's going to be implemented soon?

**Comment by jdalton** [comment]
Hi @polkovnikov-ph!

Voting is used as an indicator of developer interest in a feature. The feature request will still show up in queries sorted by votes.

**Comment by polkovnikov-ph** [comment]
That's great but the problem is that closed threads do not let anyone participate in voting, because, well, the thread is closed. What's going on? Please, reopen either of the issues.

**Comment by jdalton** [comment]
No problem. I've updated the config on the lock bot to avoid further locking of "votes needed" issues. As for the scan issue I think there's sufficient enough votes for me to gauge interest.
