### ISSUE TITLE
Calling methods without parameters 

### ISSUE THREAD

**Issue by Semigradsky** [lodash/lodash#4134]
I see that almost all methods can be called without parameters.
For example:
```js
_.concat() // []
_.wrap() // ƒ $u(n){ /* [wrapped with _.partial] */ return n}
_.clone() // undefined
_.isSymbol() // false
_.trim() // ""
```
But this is not documented. (Maybe I just not found it)
Are you planning documenting this or I should avoid using this methods without parameters?

This is important for type checking. For example now I can't write this typescript code:
```ts
interface ISomeInterface { }

function doSmth(...args: ISomeInterface[]) {
    return doSmthAnother(_.assign(...args));
}
```
because by lodash documentation `assign` has one required parameter:
`_.assign(object, [sources])`

**Comment by jdalton** [comment]
Hi @Semigradsky!

The implementation and documentation is by design.
Feel free to make the typings more strict than the Lodash implementation allows though.
