### ISSUE TITLE
questions about _.chunk in Array category

### ISSUE THREAD

**Issue by verymuch** [lodash/lodash#4135]
I have two questions about `_.chunk`:

1. If the param `number` in `_.chunk` is not a number, it will be right using the npm lodash,  return `[]`.
bug it will throw an error using the GitHub lodash.
```
import chunk from './source/chunk.js';

var arr = [1, 2, 3, 4]
console.log(chunk(arr, 's'));
```
![使用github上的源码的报错信息](https://user-images.githubusercontent.com/9148095/50630350-79c72880-0f7b-11e9-84fb-cda62f1ef596.png)

2. If the param `number` in `_.chunk` is not an integer,  it will be treated as an integer (by parseInt) by using the npm lodash, but it will be inconsistent using the Github lodash.

```
import chunk from './source/chunk.js';

var arr = [1, 2, 3, 4]
console.log(chunk(arr, 1.5));
// 使用npm包时，会一直输出[[1], [2], [3], [4]]
```

![image](https://user-images.githubusercontent.com/9148095/50630515-2a352c80-0f7c-11e9-914d-b73d45af59d4.png)

Is it a mistake or is it intentional?

**Comment by jdalton** [comment]
Hi @verymuch!

Our master branch is a bit of a WIP side with the published Lodash behavior.

**Comment by verymuch** [comment]
So it will be consistent with the published Lodash at last?

By the way, could you give me some suggestions as I'd like to read the source code of Lodash. Which version is recommended？
