### ISSUE TITLE
cloneDeep works differently in Jest

### ISSUE THREAD

**Issue by chasen-bettinger** [lodash/lodash#4136]
`Logistics`:

    "react": "^16.3.2",
    "lodash": "4.17.10",
    "webpack": "4.19.1",
    "jest": "^23.2.0",

The code:

```
import cloneDeep from 'lodash/cloneDeep';

content = {
  items: [
     { ... },
     { ... },
     ....
  ]
}

const deepClone= cloneDeep(content.items);
const selectedItem = deepClone.find(item => item.property === target);
```

In the browser / console, deepClone is:

`[ {...}, {...}, ... ]`

In Jest, deepClone is:

`{ items: [ {...}, {...}, ... ]  } `

As a result, my unit tests fail because the find method fails. 

If it helps, here is the unit test:

```
  const wrapper = shallow(<Component {...props} />);

  it('should load `Loader` and call method', () => {
    expect(wrapper.find('Loader').exists()).toBe(true);
    expect(props.method.mock.calls.length).toBe(1);
  });
```

**Comment by jdalton** [comment]
Hi @chasen-bettinger!

This is likely a difference in DOM objects from the browser vs. the simulated ones used by Jest provided by JSDOM.

**Comment by chasen-bettinger** [comment]
@jdalton 

So does that mean I'll just have to provide an edge-case for unit tests?

**Comment by jdalton** [comment]
No. Consistently cloning DOM elements [is not supported](https://lodash.com/docs/#clone).
