### ISSUE TITLE
updating lodash version to 4.17.4 will break the code

### ISSUE THREAD

**Issue by pritisolanki** [lodash/lodash#4137]
Hi,

I updated the lodash . Currently, I am on 4.17.4 and   "@types/lodash": "^4.14.119". For some reason, It breaks my code. Please note I have express+typescript working together, 

TypeError: _.uniqBy is not a function 
TypeError: _.split is not a function

Any pointers will help

**Comment by jdalton** [comment]
Hi @pritisolanki!

We don't maintain the TypeScript typings. You may want to inquire over at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).
