### ISSUE TITLE
debounce not cancel old timer when start a new timer

### ISSUE THREAD

**Issue by anhulife** [lodash/lodash#4138]
When enable `maxWait` in a tight loop, debounce will start a new timer without cancel old timer. thus,  `timerExpired` will invoked many times when thread idle.

https://github.com/lodash/lodash/blob/a7e0428889f7c26fba5c6e7127cbb36a99e0eb44/debounce.js#L195-L199

**Comment by jdalton** [comment]
Moved to #4139.
