### ISSUE TITLE
_.words should not split 2d and 3d

### ISSUE THREAD

**Issue by jmwebservices** [lodash/lodash#4141]
First and foremost, thank you for making such a great project available!

This is related to #2843. I would like to recommend that "2d" and "3d" be added to the list of exceptions. I believe the change, if approved, will need to be made to [unicodeWords.js](https://github.com/lodash/lodash/blob/master/.internal/unicodeWords.js).

**Test case**

```
_.kebabCase( '2d printing' );
// expected 2d-printing
// actual 2-d-printing

_.kebabCase( '3d printing' );
// expected 3d-printing
// actual 3-d-printing

**Comment by jdalton** [comment]
Hi @jmwebservices!

Sure, you can make a PR against the `4.17.12-pre` branch.

**Comment by javadev** [comment]
No, no.  2-d-printing is expected value.

**Comment by jdalton** [comment]
I was thinking over this too and I can see it because it's compound for "two dimensional" but in this case I think its post commonly seen as a single unit. Are there others that might be considered as a single unit?

**Comment by jmwebservices** [comment]
I think this can lead down a very deep rabbit hole. There are *many* special cases that, if this is approved, would warrant equal consideration. F1 (as in Formula 1 racing) is one.

I looked over [unicodeWords.js](https://github.com/lodash/lodash/blob/master/.internal/unicodeWords.js) and the regex made my eyes bleed. So, I will not be the right person for this PR.

**Comment by jdalton** [comment]
Ah okay! We'll leave this as by design for now.
