### ISSUE TITLE
New function: _.onceUnlessThrows

### ISSUE THREAD

**Issue by ackinc** [lodash/lodash#4142]
Hello everyone!

Just wanted to see if there's any interest in adding this function to lodash. It is like _.once, except if the function call throws, it gets "another chance" to run.

An example implementation:

```
function onceUnlessThrows(func, onFail = () => {}) {
	let threw = true;

	return (...args) => {
		if (!threw) return;

		try {
			func(...args);
			threw = false;
		} catch (e) {
			onFail();
		}
	};
}
```

My use case: adding listeners in web extensions (where not having the appropriate permission causes an exception to be thrown)

**Comment by jdalton** [comment]
Hi @ackinc!

I think this would be better suited as a [_.mixin](http://lodash.com/docs#mixin).
