### ISSUE TITLE
_.debounce().cancel() is not working with Vue.js properly

### ISSUE THREAD

**Issue by KunHwanAhn** [lodash/lodash#4144]
# Outline
I wanted to use the `_.debounce()` on the Vue.js, and it works. Unless I called the `cancel()` of it.

# Version Info

## lodash Version
- v4.17.x

## Vue.js Version
- v2.5.x

# Example Codes
```
new Vue(
  ...
  methods: {
    debounced: _.debounce(() => doSomething(), 1000),
    foo() {
      this.debounced()
    },
    cancelDebounced() {
      this.debounced.cancel()
    }
  }
  ...
)
```

# Guessed Reason
- Inside of the `initMethods` function
- [Code line of Vue.js](https://github.com/vuejs/vue/blob/dev/dist/vue.js#L3655)

# Summary
I solved this issue by implementing feature with different way.
BUT, I think it is quite weird for me, that is reason why I created this issue.
I want to hear your(the lodash commiter, organaizer etc...) opinion.
Do you think it is an issue for lodash?

**Comment by jdalton** [comment]
Hi @KunHwanAhn!

Not likely a Lodash issue. I'm not familiar with the magic Vue.js is doing but I'm sure their support avenues can help you narrow down the issue.

**Comment by codenamezjames** [comment]
Yea I ran into this issue just now and the way I worked around it was to define the functions outside of the Vue context and when I referenced the debounced function I was able to reference the non-Vue debounced function.

```
...
const hideMenu = debounce((ref) => ref.hide(), 300)

const showMenu = (ref) => {
  hideMenu.cancel()
  ref.show()
}
export default {
...
  methods: {
    hideMenu,
    showMenu
  }
}
```
