### ISSUE TITLE
_.startcase converts special characters

### ISSUE THREAD

**Issue by GeorgeWL** [lodash/lodash#4147]
example:
```js
let name = 'jórgen henley-trottingham smythe'
_.startCase(name)
// return 'Jorgen Henley Trottingham Smythe'
```
I get that in the majority of cases one would want to deburr, but it would be nice to just add this to the definition:
```ts
_.startCase(string, boolean:deburr=true)
```

**Comment by jdalton** [comment]
Hi @GeorgeWL!

Yes our case-methods deburr before they break strings into words then apply specific compound styling to them. You can do the same thing with [`_.words`](http://lodash.com/docs/#words).

**Comment by gitlab-winnie** [comment]
@jdalton If I understand your comment in https://github.com/lodash/lodash/issues/2929#issuecomment-272269880 correctly, this behavior will change in v5 though. Is that correct?

**Comment by GeorgeWL** [comment]
yeah, I hope so. Cause using the case functions on non-English names makes them wrong when they get put into the data.
