### ISSUE TITLE
Potentially unexpected behavior in null or undefined path elements

### ISSUE THREAD

**Issue by StevenLangbroek** [lodash/lodash#4150]
When using `get` and array property path syntax, if one of the elements of the property path is `null` or `undefined`, but the structure under evaluation has a `"null"` or `"undefined"` as key, it will reach the value of that key:

![image](https://user-images.githubusercontent.com/296796/51111625-e2749780-17fc-11e9-8fd3-014a62bfbdd0.png)

It’s caused by [toKey](https://github.com/lodash/lodash/blob/a7e0428889f7c26fba5c6e7127cbb36a99e0eb44/.internal/toKey.js#L17) not checking for falsiness, casting it to string (`${value}`) and therefore not bailing. My question is, is this intentional design, or is it an oversight?

**Comment by jdalton** [comment]
Hi @StevenLangbroek!

This is by design.
