### ISSUE TITLE
Filter using like or contains

### ISSUE THREAD

**Issue by scosmaa** [lodash/lodash#4158]
Hi, is it possible to filter an array of objects like the following (without use a custom callback function)?

`const list = [
  {"name": "mark"},
  {"name": "CARL"},  
  {"name": "Tom"}
] `

`const filterObj = {"name": "a"}
`

The result will be (note - case insensitive)

`
[
  {"name": "mark"},
  {"name": "CARL"}
] 
`

Thank you!

**Comment by jdalton** [comment]
Hi @scosmaa!

Your example would require a custom callback function.
