### ISSUE TITLE
Access to private methods/fields from mixed in function

### ISSUE THREAD

**Issue by YuriGor** [lodash/lodash#4160]
There are a lot of useful methods hidden in the `.internal`. 
Is there any way to use them? May be from the scope of mixed in function?

Especially I need `castPath` and `parent` private methods to implement my own version of `hasPath` which will consider empty slots in sparse arrays.
Right now I see no other way than implementing my own path parsing, while it's already exists in the lodash.

**Comment by jdalton** [comment]
Hi @YuriGor!

Try not to rely on Lodash's internals. They have no guarantee of support and may change from patch release to patch release. I try to find internal methods that are handy though and expose them. Would you be up for making a PR to expose the `castPath` and `parent` method?

**Comment by YuriGor** [comment]
Ok, thank you, I'll make PR as soon as I'll find some time.
May I do it for 4.xxx branch too, or for master only?
I see no tests in the v5..

**Comment by YuriGor** [comment]
I found there is `toPath` function, it's enough for my case
