### ISSUE TITLE
lodash/fp get and set functions

### ISSUE THREAD

**Issue by Attrash-Islam** [lodash/lodash#4161]
Hi Lodash 👋 

I wanted to clarify why lodash/fp `get` function don't return the same ref for the object if the object didn't have any changes?

![image](https://user-images.githubusercontent.com/7091543/51430585-409ee180-1c26-11e9-8560-84d48b65ead9.png)

In Functional Programming, we can know that the object has changes based on just the reference comparison, but here the `get` is returning a new reference without any changes to the state which seems wrong in FP.

I think that the right thing is to break the ref when setting the state by using `lodash/fp#set` function and then we can know that the object has changed from the prevState by the ref comparison.

I also have an issue when using set as so:
![image](https://user-images.githubusercontent.com/7091543/51430613-b6a34880-1c26-11e9-89da-4a485299ece7.png)

Why I'm getting a String corrupted output?

Thanks in advance ❤️

**Comment by jdalton** [comment]
Hi @Attrash-Islam!

The lodash `get` and `set` methods are not state management. They are simple property getters/setters. In the FP flavor the setter tries not to augment original values and will instead return a new modified object.

**Comment by Attrash-Islam** [comment]
Thanks for the quick respone @jdalton .
What about the set return value in the second screenshot?

**Comment by jdalton** [comment]
The arg order of `set` is `set(path, value, object)`

**Comment by Attrash-Islam** [comment]
![image](https://user-images.githubusercontent.com/7091543/51432130-51a61d80-1c3b-11e9-8167-bdce685a0748.png)

Everything work as expected. The argument order wasn't correct for them both.
