### ISSUE TITLE
Installed package.json contains link to parking/malware

### ISSUE THREAD

**Issue by FauxFaux** [lodash/lodash#4164]
The installed `package.json` (i.e. in `my_project/node_modules/lodash/package.json` contains author information of:
```
  "author": {
    "name": "John-David Dalton",
    "email": "john.david.dalton@gmail.com",
    "url": "http://allyoucanleet.com/"
  },
```

This `url` is currently serving a redirect to malware. Please fix the domain, or remove it from the installed metadata.

(I'm not sure where it comes from.. maybe npmjs.com metadata? It doesn't seem to be in the source tree.)

**Comment by jdalton** [comment]
Hi @FauxFaux!

It used to be my personal blog url but I let it go years ago. I've updated relevant branches and generation tools so it should be removed from future updates to packages.

**Comment by kachkaev** [comment]
Looking forward for 4.17.12 where this is resolved 🙌
