### ISSUE TITLE
Need an `isEmpty` taking Object.getOwnPropertySymbols() into account

### ISSUE THREAD

**Issue by Benew** [lodash/lodash#4167]
Hi! I'm looking for a simple solution to find out if a `sequelize` query object is empty or not.

Using `_.isEmpty` is no good for `sequelize` uses `Symbol` keys for criteria grouping.

I hereby suggest an update to the documentation.

I think it should mention explicitely the call to `Object.prototype.hasOwnProperty` and feature an example with an object with symbols as keys.

**Comment by jdalton** [comment]
Hi @Benew!

I use
```js
function isObjectEmpty(object) {
  for (const name in object) {
    if (has(object, name)) {
      return false
    }
  }

  return true
}
```
