### ISSUE TITLE
Use the merge method to get two different results

### ISSUE THREAD

**Issue by Tommy-White** [lodash/lodash#4168]
What causes the following two cases to get different results? 
```js
// case #1:
var target = [ {m1: console.log}, {m1: console.log}, {m1: console.log} ]
var source = [ { a: 1, b: 2 }, { a: 2, b: 3 }, { a: 3, b: 4 }] 
_.merge(target, source)

// case #2:
var target = Array(3).fill({ m1:  console.log})
var source = [ { a: 1, b: 2 }, { a: 2, b: 3 }, { a: 3, b: 4 }] 
_.merge(target, source)

```

Below is result that I got
![image](https://user-images.githubusercontent.com/24240963/51727857-e8923000-20a8-11e9-8e97-5c3ec6bc8ab9.png)

![image](https://user-images.githubusercontent.com/24240963/51727867-f5168880-20a8-11e9-8f49-f05fd1db4d0c.png)

Is this a logical error in the merge method, or is it because I am trapped ?

**Comment by jdalton** [comment]
Hi @Tommy-White!

`var target = Array(3).fill({ m1:  console.log})` uses the same object reference for all 3 entries.
