### ISSUE TITLE
OrderBy: When using orderby desc, nulls are placed at the front of the array

### ISSUE THREAD

**Issue by wbernest** [lodash/lodash#4169]
Hello,

I am not sure if this is intentional or not, but when I use orderBy with the desc flag, nulls get sorted at the beginning of the array instead of at the end.

For example: 

var stuff =[{oldStuff: 11, newStuff: null, badStuff: 123, goodStuff: 193},{oldStuff: 12, newStuff: 1, badStuff: 123, goodStuff: 193},{oldStuff: 13, newStuff: 2, badStuff: 123, goodStuff: 193},{oldStuff: 4, newStuff: 3, badStuff: 123, goodStuff: 193},{oldStuff: 15, newStuff: 4, badStuff: 123, goodStuff: 193},{oldStuff: 16, newStuff: null, badStuff: 123, goodStuff: 193}];

_.orderBy(stuff,['newStuff'], ['desc'])
(6) [{…}, {…}, {…}, {…}, {…}, {…}]
0: {oldStuff: 11, newStuff: null, badStuff: 123, goodStuff: 193}
1: {oldStuff: 16, newStuff: null, badStuff: 123, goodStuff: 193}
2: {oldStuff: 15, newStuff: 4, badStuff: 123, goodStuff: 193}
3: {oldStuff: 4, newStuff: 3, badStuff: 123, goodStuff: 193}
4: {oldStuff: 13, newStuff: 2, badStuff: 123, goodStuff: 193}
5: {oldStuff: 12, newStuff: 1, badStuff: 123, goodStuff: 193}

_.orderBy(stuff,['newStuff'], ['asc'])
(6) [{…}, {…}, {…}, {…}, {…}, {…}]
0: {oldStuff: 12, newStuff: 1, badStuff: 123, goodStuff: 193}
1: {oldStuff: 13, newStuff: 2, badStuff: 123, goodStuff: 193}
2: {oldStuff: 4, newStuff: 3, badStuff: 123, goodStuff: 193}
3: {oldStuff: 15, newStuff: 4, badStuff: 123, goodStuff: 193}
4: {oldStuff: 11, newStuff: null, badStuff: 123, goodStuff: 193}
5: {oldStuff: 16, newStuff: null, badStuff: 123, goodStuff: 193}

To remedy this issue I am currently splitting my array into two arrays, nulls and nonnulls, based on the sort field (I am only ordering by one field), running orderby on the nonnulls array then contacting the nulls on to the back end of the sorted array.  

Like so:
var nulls = data.filter(x => x[props.sortField] == null);
var nonNulls = data.filter(x => x[props.sortField] != null)
var sortedData = [..._.orderBy(nonNulls, [props.sortField], [(getBool(props.ascending) ? 'asc' : 'desc')]), ...nulls];

This has been tested on lastest npm version of 4.17.11.

**Comment by jdalton** [comment]
Hi @wbernest!

This is by design. When in ascending order `NaN`, nullish, and symbol values are at the end so it fits that when descending they'd be at the beginning.

**Comment by wbernest** [comment]
I figured it might but I wanted to make sure.  It doesn't fit with what I want for this project, but I can continue using my little hack.  Thanks for the help.

**Comment by krunkosaurus** [comment]
Just encountered this issue and found this ticket. `asc` denotes that the smallest values are first. It can't get much smaller than null. This also flies in the face of how mysql and any other sorting system works.

**Comment by marcesdan** [comment]
you just have to add a new parameter: noneFirst or noneLast (if no present noneFirst by default)

**Comment by ethanryan** [comment]
encountered the same problem, i also expected null values to be returned last instead of first,  sorting by `desc`. 

thanks for posting your solution to this problem, as well as your question @wbernest

**Comment by yann120** [comment]
Hello, I have the same problem, I will need to sort again after using orderBy to put all the null values at the end...
If you have a big array, it's not really performant...
Having a noneFirst option would be so cool

**Comment by spiko-md** [comment]
@jdalton Can this be reopened, please? Also #4264 is probably same issue.

**Comment by deathemperor** [comment]
this SO answer works best https://stackoverflow.com/questions/41138820/lodash-orderby-with-null-and-real-values-not-ordering-correctly

**Comment by voroshagyma** [comment]
A possible workaround when using multiple properties:
`orderBy(results, [function(resultItem) { return resultItem.capacity === 0; }, 'displayIndex'], ['asc', 'asc']);`
[source](https://stackoverflow.com/questions/52135009/how-to-use-lodash-orderby-with-a-custom-function)
