### ISSUE TITLE
isEqual returns inconsistent results with cyclic objects 

### ISSUE THREAD

**Issue by grosto** [lodash/lodash#4170]
Somebody opened this issue in Jest's repo and I found a similar bug in Lodash too.
```
const a = {};
a.x = { x: a };

const b = {};
b.x = b;

lodash.isEqual(a, b) // true
lodash.isEqual(b, a) // false
```

The result value of `isEqual` is different if you switch the order of arguments. Other popular libraries have this bug too. Node's `isDeepStrictEqual` returns `false` in both cases.

**Comment by jdalton** [comment]
Thank you @grosto!

In the future I will defer to Node's helper.
