### ISSUE TITLE
Maximum call stack size exceeded on lodash.clonedeep / react native 0.57.5

### ISSUE THREAD

**Issue by webraptor** [lodash/lodash#4175]
We've had some issues in the past few weeks with react native apps throwing "Maximum call stack size exceeded" crashes on iOS devices.

The issue was difficult to track since simulators would crash only with debugger closed (Crash doesn't occur if debugger on and simulator uses browers' stack).

Crash also occurs on iOS physical devices. Testing revealed the issue is triggered by packages that use lodash.clonedeep and affects (at least starting with) react native  version 0.57.5. We didn't test if this occurs with older versions of RN.

Issue was triggered when we upgraded from RN 0.54/0.55 to latest.

**Comment by jdalton** [comment]
Hi @webraptor!

The recursive implementation of `cloneDeep` was by design with the shortcoming that in some rare cases it could run into stack size exceeded issues. I'm not how `cloneDeep` is being used but chances are a more specialized clone tailored to their scenario will be a better option.
