### ISSUE TITLE
Feature request:  _. matchAll

### ISSUE THREAD

**Issue by toshisugimo** [lodash/lodash#4178]
Hi!

I often want to check that a string contains all of the elements in the array.
So, I want the function as below:

```javascript
_.matchAll('A modern JavaScript utility library.', ['javascript', 'library', 'modern']);
 // => true

_.matchAll('A JavaScript library.', ['javascript', 'library', 'modern']);
 // => false
```

For example you can use it when you want to implement an AND search with the search filter on the application index page.

Any chance you're ever going to support such functionality?

Thank you very much!

**Comment by eliashdezr** [comment]
IMHO, there's no need to add this, as it can be built with existing lodash functions.

**Comment by jdalton** [comment]
Thanks @toshisugimo!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by mrGrochowski** [comment]
+1 for this functionality
