### ISSUE TITLE
isMap is always false on IE11

### ISSUE THREAD

**Issue by evanemolo** [lodash/lodash#4180]
version: 4.17.11

From inside the IE 11 console:

```
var m = new Map();
m instanceof Map;   // true
_.isMap(m);   // false
m.toString();  // "[object Object]"  <--- the issue...
```

It appears that IE 11 treats `Map` as an `Object`. `isMap` expects `getTag` to return `"[object Map]"`

**Comment by jdalton** [comment]
Hi @evanemolo!

I cannot reproduce. I visited `lodash.com` in IE11, opened F12 dev tools, and ran `_.isMap(new Map)` which returned `true`. You might have a bad shim that is causing a false fail.
