### ISSUE TITLE
How merge mutil object in array with lodash?

### ISSUE THREAD

**Issue by matamune94** [lodash/lodash#4184]
I have a bit of problems with my code :

```
[
 {
 "key": 0,
 "server": 0
 },
 {
 "key": 0,
 "server": 1
 },
 {
 "key": 1,
 "server": 0
 }
]
```
how i can result to :

```
[
 { key: 0 , server:[0,1] },
 { key: 1 , server:[0] }
]
```
I'm using _.groupBy but it does not return results as expected. How merge mutil object in array with lodash?

**Comment by jdalton** [comment]
Hi @matamune94!

For these kinds of questions head on over to our [gitter chat](https://gitter.im/lodash/lodash).
