### ISSUE TITLE
Flush not called immediately on debounce

### ISSUE THREAD

**Issue by djibarian** [lodash/lodash#4185]
Following on #1816 I noticed that debounce.flush() is called after the timeout and not immediately. Shouldn’t the function be called immediately as stated by the docs?

**Comment by jdalton** [comment]
Hi @djibarian!

The `.flush()` method is executed as soon as you call it. It's source [is here](https://github.com/lodash/lodash/blob/4.17.11/lodash.js#L10398-L10400).

**Comment by djibarian** [comment]
No, is not. The code executes immediately or on the trailing edge depending on `result`. What I had to do is

```
debounced();
debounced.flush();
```
 instead of

```
debounced.flush();
```

which is not very clear from the docs until you read the bit `to cancel delayed func invocations and a flush method to immediately invoke them` twice, noticing that `them` refers to the delayed invocations.

So if there are no pending invocations `flush()` delays execution of `func` to the trailing edge.

If I’m not wrong...

**Comment by illuminist** [comment]
`flush()` **doesn't invoke the function by itself**. It just tells the timer that time is out and need to invoke the pending invocations immediately. Then the timer acknowledges and invoke the pending invocations later.

So it there isn't any pending invocation, `flush()` will do nothing other than return a result from the latest invocation.

And `immediate invocation` isn't same as `synchronized invocation`.

**Comment by mcshaz** [comment]
it would be useful to have a single `invokeImmediate()` option.

**Comment by AndreiSoroka** [comment]
flush return last result, but not current... so this code is not correct:
```javascript
let count = 0;
function saveToDbExample(){
  count+=1;
}
const testFunction = _.debounce(()=>{
  saveToDbExample();
  return true;
}, 3000)

testFunction();

testFunction.flush(); // count === 1 - good
testFunction.flush() // count === 1 - good

// case: we have timeoutId
testFunction();
if (!testFunction.flush()) { // count === 2 - good
  // skipped - good
  saveToDbExample();
}

// case: we have not got timeoutId, but we remember result...
if (!testFunction.flush()) { // count === 2 - bad, shoud be 3
  // skipped - bad
  saveToDbExample();
}

console.log(count);
```

And we shoul develop like that
```javascript
testFunction();
testFunction.flush();

testFunction();
testFunction.flush();

testFunction();
testFunction.flush();
```

It is hack and not readeble...

I think need to add `.invokeImmediate();`
