### ISSUE TITLE
isFunction fail for async generator function

### ISSUE THREAD

**Issue by thangbn** [lodash/lodash#4194]
async generator have tag **[object AsyncGeneratorFunction]** will fail to be recognized by **isFunction**

**Comment by jdalton** [comment]
Hi @thangbn!

You're correct. I don't know if a fix for that will make it in to Lodash v4 though. You'll be better off using `typeof value === "function"`.

**Comment by thangbn** [comment]
fair enough, is a PR welcomed?

**Comment by StreetStrider** [comment]
@thangbn afaik, the course here is to eliminate `isFunction` in v5 (and many others). Chance of anything propagated to v4 is low. You can just overload `isFunction` on your side, like `export default function isFunction (f) { return typeof f === 'function' }` and bulk replace it across codebase, and that's all.

**Comment by jdalton** [comment]
@thangbn You can make a PR against the `4.17.12-pre` branch so that if/when that is bumped it will be included.
