### ISSUE TITLE
why { } required for single statement assignment with _.forEach

### ISSUE THREAD

**Issue by stdeepak22** [lodash/lodash#4195]
If I need to do assignment of the value to one property and I need to do it for collection of the object I used _.forEach 

`_.forEach( tabs, t => t.active = false );`  [not working fiddle](https://jsfiddle.net/stdeepak22/47nuscot/32)

Above doesn't work well, while if I use curly braces { } around arrow function it works well. 

`_.forEach( tabs, t => { t.active = false } );`  [working fiddle](https://jsfiddle.net/stdeepak22/47nuscot/34)

I have provided both- working/non working fiddle.
Just **click on Tab1,2,3 buttons multiple times to reproduce it.**

**Comment by StreetStrider** [comment]
@stdeepak22 cause LoDash's `forEach` treats `false` as a special value for early break. If you do not put braces, return value is `false` at first invocation, thus early break occur.

**Comment by falsyvalues** [comment]
Simply because iteratee function may [exit iteration](https://lodash.com/docs/4.17.11#forEach) early by explicitly returning false and its happening by `t.active = false` which is implicitly `return t.active = false`.
