### ISSUE TITLE
Motivation behind predicate signature

### ISSUE THREAD

**Issue by YuriGor** [lodash/lodash#4197]
HI, I need an advise related to predicate signature.

In most cases the predicate is invoked with three arguments: value, index|key, collection.

I've never used third argument in practice, but I can imagine it can be useful for example to make some decision relying on sibling element's data. 
For example we can check if collection[index+1].flag === true and then return something from predicate accordingly.

I want to refactor predicate signature in the Deepdash extension, to make it conform Lodash.
Now predicate in eachDeep/filterDeep looks like this:
`(value, key|index, path, depth, parentValue, parentKey, parentPath, fullParentsStack(optional))=>{}`

As you see there is no `collection` so I want to add it.

In terms of deep walking, to gain something useful from `collection` we need full current `path`, not only `key|index`
So I want to pass into predicate `value, key|index, path` and `collection` arguments

Rest of the arguments are pretty useful too, so I'll pack them into last object argument `context`

So finally deep version of predicate should be like this:
`(value, key|index,path,collection,context={parentValue, parentKey,parentPath, parents,depth})`

My question is about most rational order of arguments.

Does it make sense to strictly follow Lodash version in first three args:
`value,key,collection,    path,context`
will it have some compatibility benefits in case of mixed Lodash/Deepdash usage? 
In this case predicates has almost identical signatures both for Lodash and Deepdash

Or I'll better choose more intuitive order
`value, key,path,collection,   context`?
because having identical with Lodash signatures has no practical appliance?

**Comment by jdalton** [comment]
HI @YuriGor!

Thank you for pinging me. We chose our order to mimic those of builtin `Array` methods like [`Array#filter`](https://mdn.io/array/filter). I think the `path` param is a `context` candidate too.

**Comment by YuriGor** [comment]
Ok, thank you again, for the same advice. Next time, before asking, I'll try to look back to origins by myself)
