### ISSUE TITLE
Sum gives wrong result with decimal values

### ISSUE THREAD

**Issue by carlkenne** [lodash/lodash#4198]
_.sum([-1000, 684.2, 76.77, -1000, -100, 67.58, 171.45, 100, 453.92, 50, 80.49, 79.54, 83.69, 176.09, 8.02, 68.25]); gives me 9.947598300641403e-14
however, if I rearrange the values to 
_.sum([684.2, 76.77, 67.58, 171.45, 100, 453.92, 50, 80.49, 79.54, 83.69, 176.09, 8.02, 68.25, -1000, -1000, -100]); it gives me 0 as expected. 

tested in the latest version of chrome

**Comment by jdalton** [comment]
Hi @carlkenne!

I'm guessing this is a decimal resolution issue of JS and not of Lodash specifically.

**Comment by carlkenne** [comment]
Could be, what would the recommended approch using lodash to sum these values be?

**Comment by jdalton** [comment]
Maybe something like [math.js](http://mathjs.org/).
