### ISSUE TITLE
Merging an object with an array creates an object with all array functions

### ISSUE THREAD

**Issue by MateuszPrzybyla** [lodash/lodash#4200]
After bumping from version `2.4.2` to `4.17.11` There is a weird behaviour when running 
`_.merge({}, [])`. In `2.4.2` it resulted in an empty object `{}` while in `4.17.11` I'm getting an object that contains all the function of the array:
```
{
    all: ...,
    any: ...,
    clear: ...,
    clone: ...,
    collect: ...,
    ...
}
```

**Comment by jdalton** [comment]
Hi @MateuszPrzybyla!

I cannot repro your result in `4.17.11`. I get an empty object `{}`.

**Comment by MateuszPrzybyla** [comment]
Thanks for the validation. Turns out that it was caused by the `prototype.js` library being loaded. It extends the Array prototype with some functions that are enumerable. Then `keysIn` catches these and as a result they are put into the merged object.
