### ISSUE TITLE
differenceBy and differenceWith return an unexpected result for an edge case

### ISSUE THREAD

**Issue by vecerek** [lodash/lodash#4201]
Version used: `4.17.11`

Steps to reproduce:
```js
const values = [{ a: 'x', b: 2 }, { a: 'y', b: 2 }]
const oldValues = [{ a: 'x', b: 2 }, { a: 'y', b: 1 }]

differenceBy(values, olValues, 'b') // => []; Expected: { a: 'y', b: 2 }

// However, changing the order of values works
differenceBy(oldValues, values, 'b') // => { a: 'y', b: 1 }
```

After looking into the implementation of the [baseDifference](https://github.com/lodash/lodash/blob/master/.internal/baseDifference.js#L21) function I realized that there is a chance this issue might not qualify as a bug. The algorithm loops through each element of the first array and compares its [computed value](https://github.com/lodash/lodash/blob/master/.internal/baseDifference.js#L44) to all the [flattened](https://github.com/lodash/lodash/blob/master/differenceBy.js#L32) values of the second array. Since it finds a corresponding value, it continues with the outer loop effectively moving onto the next element of the array (`values`) and not pushing the expected difference to the result set.

Would anyone expect the same result as me or is this just not the real intention of the implemented difference functions?

**Comment by jdalton** [comment]
Hi @vecerek!

The order is significant. See our docs for [_.difference](https://lodash.com/docs/#difference).
