### ISSUE TITLE
_.get behavior with empty array as path?

### ISSUE THREAD

**Issue by KurtPreston** [lodash/lodash#4204]
```javascript
// Current behavior
_.get(x, []); // returns undefined

// Expected behavior
_.get(x, []); // returns x
```

I understand that string paths have inherent ambiguity, so it makes sense why `_.get(x, "")` may retrieve `x[""]`

However, array-based paths are unambiguous. There is only one possible traversal for any given path. It seems that behavior would be more consistent if `_.get(x, [])` returned `x`. It would look like:

```javascript
_.get(x, ["a", "b"]); // returns x["a"]["b"]
_.get(x, ["a"]); // returns x["a"]
_.get(x, []); // returns x
```

Is there a reason it returns `undefined` instead?

**Comment by jdalton** [comment]
Hi @KurtPreston!

See #3276.
