### ISSUE TITLE
Add `pattern` parameter to case methods

### ISSUE THREAD

**Issue by pillowfication** [lodash/lodash#4205]
I'm proposing adding an optional second parameter `pattern` to case methods, which would be passed to the underlying `_.words` function.

```javascript
_.kebabCase('eg1: 100s of 3D OMGs in the \'90s', /[a-zA-Z0-9]+/g)
// eg1-100s-of-3d-omgs-in-the-90s
```

Could remedy questions like #4141

**Comment by jdalton** [comment]
Hi @pillowfication!

I think I'd rather encourage folks to create their own custom tailored method.
