### ISSUE TITLE
`_.word()` does not support `pattern` as a String

### ISSUE THREAD

**Issue by pillowfication** [lodash/lodash#4206]
The docs state that `pattern` can be a String, but since it's passed directly to `string.match()`, it can only result in errors or non-global regexes.

```javascript
_.words('foo bar', 'foo')
// ["foo", index: 0, input: "foo bar", groups: undefined]

_.words('foo bar', '[')
// Error
```

**Comment by jdalton** [comment]
Hi @pillowfication!

It supports a string as [`String#match`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) does and with the details that implies.
