### ISSUE TITLE
Not compatible with yarn workspaces

### ISSUE THREAD

**Issue by daveisfera** [lodash/lodash#4209]
`lodash` requires the use of `nohoist` and it would be great if this wasn't the case:
https://yarnpkg.com/blog/2018/02/15/nohoist/

**Comment by jdalton** [comment]
Hi @daveisfera!

I don’t believe there is anything for Lodash to do here.

**Comment by daveisfera** [comment]
You're correct. It turns out that this was from the way that I was using yarn workspaces and not an actual issue with lodash.

**Comment by johankasperi** [comment]
We are having the same problem. @daveisfera would you min sharing your solution? Thank you!

**Comment by johankasperi** [comment]
Alright! Will give that a try 😄 Thank you!
