### ISSUE TITLE
Inconsistent behaviour when merging objects with array properties

### ISSUE THREAD

**Issue by Zakini** [lodash/lodash#4210]
I realise this sort of thing has [come](https://github.com/lodash/lodash/issues/1413) [up](https://github.com/lodash/lodash/issues/2872) [a lot](https://github.com/lodash/lodash/issues/4064), but I think I've got a new take on how `_.merge` handles arrays. This all using v4.17.11.

Let's start with the example given for `_.merge` from the docs:
```js
var object = {
  'a': [{ 'b': 2 }, { 'd': 4 }]
};
 
var other = {
  'a': [{ 'c': 3 }, { 'e': 5 }]
};
 
_.merge(object, other);
// => { 'a': [{ 'b': 2, 'c': 3 }, { 'd': 4, 'e': 5 }] }
```

Here we can see that the two arrays at `a` are concatenated.

Now let's tweak the example:
```js
var object = {
  'a': [{ 'b': 2 }, { 'd': 4 }, { f: [6] }]
};
 
var other = {
  'a': [{ 'c': 3 }, { 'e': 5 }, { f: [7] }]
};
 
_.merge(object, other);
// => { a: [{ b: 2, c: 3 }, { d: 4, e: 5 }, { f: [7] }] }"
```

In this example, the two arrays at `a[2].f` are not concatenated.

Okay, so let's try simplifying that path a little:
```js
var object = {
  'a': [{ 'b': 2 }, { 'd': 4 }, [6]]
};
 
var other = {
  'a': [{ 'c': 3 }, { 'e': 5 }, [7]]
};
 
_.merge(object, other);
// => { a: [{ b: 2, c: 3 }, { d: 4, e: 5 }, [7]] }
```

In this case, the two arrays at `a[2]` are not concatenated.

Alright, so let's simplify the path a different way by getting rid of the 'outer' array:
```js
var object = {
  'a': { f: [6] }
};
 
var other = {
  'a': { f: [7] }
};
 
_.merge(object, other);
// => { a: { f: [7] } }
```

Once again, the two arrays at `a.f` are not concatenated.

-----

There's something not right here: `_.merge` should either always concatenate arrays, or never. Given that the docs state that "Array and plain object properties are merged recursively", I assume the intended behaviour is that the arrays in all of the above examples should have been concatenated.

Apologies if this has already been sorted for v5, but I couldn't find an issue that highlighted this behaviour this clearly.

**Comment by jdalton** [comment]
Hi @Zakini!

> Here we can see that the two arrays at `a` are concatenated.

They are not concatenated the objects are merged into each other.

> In this example, the two arrays at `a[2].f` are not concatenated.

Correct, `f[0]` of `6` is merged over with `f[0]` of `7`.

There is no array concatenation by default. You'll have to use [`_.mergeWith`](https://lodash.com/docs/#mergeWith) to accomplish that.

**Comment by Zakini** [comment]
Ah ha, I see now! `_.merge`'s behaviour is more about the path to each property rather than about the type of any value, and array indices are treated in the same way as object properties. For `_.merge`'s purposes, an array such as `[5, 6, 7]` is treated like an object such as `{ 0: 5, 1: 6, 2: 7 }`.

I think this behaviour ought to be more clearly explained in the documentation. The only mention of arrays in `_.merge`'s documentation is the sentence I quoted earlier, and (to me at least) saying that "**Array[s]** and plain object properties **are merged** recursively" implies concatenation, since that's what we're usually trying to achieve when we want to take two arrays and end up with one array.

Maybe adding an example such as the following would help:
```js
var object = {
  'a': [1]
};
 
var other = {
  'a': [2, 3]
};
 
_.merge(object, other);
// => { 'a': [2, 3] }
```
Or perhaps a slightly weird example:
```js
var object = {
  'a': [1, 2, 3]
};
 
var other = {
  'a': [4, undefined, 5]
};
 
_.merge(object, other);
// => { 'a': [4, 2, 5] }
```
Or maybe just outright saying that arrays are not concatenated and referring the reader to `_.mergeWith` would be enough.

In any case, if you @jdalton reckon adding something like this to the documentation would help, I'd be happy to put in a PR for this.
