### ISSUE TITLE
groupBy() don't always preserve the order of array collection

### ISSUE THREAD

**Issue by acaktas** [lodash/lodash#4211]
groupBy() documentation says: The order of grouped values is determined by the order they occur in collection. 

But if you have a list like this, where you have a number in the "name" property:

```
var list = [
  { 'name': 'a' },
  { 'name': 'b' },
  { 'name': 'b' },
  { 'name': 'a' },
  { 'name': '1' },
];
```
groupBy("name") it will always returned this "number group" as a first one.

here is a [jsfiddle](https://jsfiddle.net/acaktas/wj8e5p1n/7/)

**Comment by jdalton** [comment]
Hi @acaktas!

The order was pertaining to the order of values within a given group.

**Comment by alon-s** [comment]
According to the documentation: 

>  The order of grouped values is determined by the order they occur in `collection`.

From that i would guess that the order of the groups should be as the items occur in the original Object.
So for the example in the docs:

>  * groupBy([6.1, 4.2, 6.3], Math.floor)
>  * // => { '4': [4.2], '6': [6.1, 6.3] }

I would actually expect the result to be: { '6': [6.1, 6.3], '4': [4.2] }

**Comment by MathieuDerelle** [comment]
the doc is badly worded

the order of the grouped object seems to be based on the order of the keys
and NOT the order of the original `collection`

it has caused some troubles for me

**Comment by MathieuDerelle** [comment]
This is a chrome/V8 caveat.

When object keys represent integers, the order is not preserved : 
![image](https://user-images.githubusercontent.com/16286023/64355692-f118f480-d001-11e9-869b-9000a23c08fa.png)

more details : 
https://stackoverflow.com/questions/18148903/why-do-numeric-keys-in-javascript-always-sort-to-the-beginning

**Comment by kylewinkler** [comment]
It is auto sorting the result.
So the order is NOT determined by the order they appear in the original collection, unfortunately.

Exp: 
[{id: 5}, {id: 2}, {id: 6}, {id:1} , {id: 2}]

groupBy id => {1: [], 2: [], 5: [], 6:[]}

This makes this function unusable for my project needs, I wish it would retain the original order like:
groupBy id => {5: [], 2: [], 6: [], 1: []}

**Comment by MathieuDerelle** [comment]
the explanation is in my previous comment

**Comment by keeganpoppen** [comment]
btw Map.groupBy *does* preserve the order in the way y'all (and i) seek
