### ISSUE TITLE
clarify _.clone behavior

### ISSUE THREAD

**Issue by dwelle** [lodash/lodash#4212]
Mainly behavior around cloning/copying prototypes.

The [docs say](https://github.com/lodash/lodash/blob/master/clone.js) that `_.clone` uses ["structured clone algorithm"](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm), where MDN links to a w3c spec where it states it's been deprecated:

> This specification used to define a "structured clone" algorithm, and more recently a StructuredClone abstract operation. However, in practice all known uses of it were better served by separate serialization and deserialization steps, so it was removed.

Not sure if lodash then follows the [StructuredSerializeInternal](https://www.w3.org/TR/html5/infrastructure.html#section-structuredserializeinternal) algo, or the previous spec which is nowhere to be found now.

Either way, I couldn't find what's the supposed behavior around cloning object's prototype.

From source/behavior, it's obvious `_.clone` sets the cloned object's prototype to the original object's prototype, but it'd be nice to document it.

MDN states:

> The prototype chain does not get walked and duplicated.

Which isn't super clear whether the prototype should be copied at all.

**Comment by jdalton** [comment]
Hi @dwelle!

Oh bummer! I didn't know they deprecated and removed the docs for this. I'd be up for a doc PR to document the existing `_.clone` behavior.

**Comment by dwelle** [comment]
Yup, I'll open one shortly and we'll figure out the particulars there, if need be.
