### ISSUE TITLE
Unexpected _.startCase spacing of numbers

### ISSUE THREAD

**Issue by planetflash** [lodash/lodash#4213]
_.startCase is adding a space before a number in string. Is this expected?

[https://jsfiddle.net/82dLp4wg/1/](https://jsfiddle.net/82dLp4wg/1/)

`_.startCase("AB1C23")`
// Expected: Ab1c23
// Actual: AB 1 C 23

Happy to accept if it is my misunderstanding of startCase and that "defined by rules that are not universally standardised" ,  but using https://titlecase.com/startcase and https://en.toolpage.org/tool/startcase do not add spaces (although do have different behaviour on the C)

**Comment by jdalton** [comment]
Hi @planetflash!

Yes, the case methods deal with compound words, split them up, and rejoin them in a specific configuration. You're probably looking for [_.capitalize](http://lodash.com/docs#capitalize)

**Comment by planetflash** [comment]
@jdalton thanks for clarifying the behaviour is expected. 

It definitely wasn't _.capitalize I was looking for. It's a bit edge case as I was trying to convert to "SS7 INTERCEPTION" to "SS7 Interception" that was input. I'm not sure there is an easy catch all function to achieve that as it is essentially different behaviour for part 1 and 2 of the string. However, I was surprised by the space.

Happy for this to be closed, but wanted to clarify the case I was trying to solve.
