### ISSUE TITLE
a question about the function assignMergeValue

### ISSUE THREAD

**Issue by caoweiju** [lodash/lodash#4216]
i am reading the source code of lodash, when i see the function assignMergeValue;
````
import baseAssignValue from './baseAssignValue.js'
import eq from '../eq.js'

/**
 * This function is like `assignValue` except that it doesn't assign
 * `undefined` values.
 *
 * @private
 * @param {Object} object The object to modify.
 * @param {string} key The key of the property to assign.
 * @param {*} value The value to assign.
 */
function assignMergeValue(object, key, value) {
  if ((value !== undefined && !eq(object[key], value)) ||
      (value === undefined && !(key in object))) {
    baseAssignValue(object, key, value)
  }
}

export default assignMergeValue
````
which makes me wonder is this condition:
````
(value !== undefined && !eq(object[key], value)) ||  (value === undefined && !(key in object))
````

the second condition is `value === undefined`, and the `key` is in the specified object or object's prototype chain, why not use `Object.prototype.hasOwnProperty`?  in operator will find the  `key` in object or its prototype chain。

i hope it's just my error. hope someone tell me why?

**Comment by caoweiju** [comment]
i am sorry, this is only a question about the source code, not a strict issue, is my fault to open a issue, and i want knoe who can i get the answer of this question.  i will close this issue tomorrow.

**Comment by falsyvalues** [comment]
Hi @caoweiju 

A property value can be `undefined` but the property may still exist on the object.
This checks to ensure the value is `undefined` and the property doesn't exist on the object.

See #3668
