### ISSUE TITLE
Group By limits returning objects

### ISSUE THREAD

**Issue by budysutjijati** [lodash/lodash#4217]
Hi there, is there a limit on the amount of objects the group by method can pass back? Whenever I try to group a JSON file containing around 6K of objects, it will only return the first 5.04K of grouped objects. The below function was used.

`function groupBy(obj){
	return result=_.chain(obj).groupBy("name").map(function(v, i) {
		return {
			name: i,
			unit: v
		}
	}).value()`

**Comment by jdalton** [comment]
Hi @budysutjijati!

The `_.groupBy` method is a "Collection" method. I wonder if your object has ` .length` property on it which would move it into array-like iteration.
