### ISSUE TITLE
Problem with `forEach` method return

### ISSUE THREAD

**Issue by sergik-0013** [lodash/lodash#4219]
Hello!
I noticed one strange bug in the work of the "forEach" method.
If we iterate over the object and use the arrow function, without parentheses, then some of the values are not processed.
Sample code with the result:
```js
let a = {
	a: true,
	b: false,
	c: true,
	d: false
};
const b = [];
const c = [];

_.forEach(a, (item, i) => item && b.push(i));
_.forEach(a, (item, i) => {
	item && c.push(i)
});

console.log(`B: `, b);
console.log(`C: `, c);
```
<img width="2048" alt="2019-03-04 13 41 16" src="https://user-images.githubusercontent.com/22467200/53728838-abc60f80-3e84-11e9-8f3e-4b6e506eb061.png">

**Comment by falsyvalues** [comment]
Hi @sergik-0013! 

It's not a bug. Iteratee function may [exit iteration](https://lodash.com/docs/4.17.11#forEach) early by explicitly returning `false` and its happening by using `item && b.push(i)`which is implicitly `return item && b.push(i)`.

**Comment by sergik-0013** [comment]
Oh. Sorry)
Many thanks for the explanation!
