### ISSUE TITLE
_.merge() does not copy symbol values

### ISSUE THREAD

**Issue by serge1peshcoff** [lodash/lodash#4221]
I am using Sequelize and lodash.merge and I have a default filter/query object and I need to merge it with my custom filter. So that's what I'm doing:

```js
const defaultQueryObj = helpers.getDefaultQuery(req);
const queryObj = merge(defaultQueryObj, {
    where: {
        deleted: false,
        organizers: { [Sequelize.Op.contains] : [{ user_id: req.user.id }] }
    }
});

console.log('merged', queryObj)

const queryObj2 = {
    where: {
        deleted: false,
        organizers: { [Sequelize.Op.contains] : [{ user_id: req.user.id }] }
    }
}

console.log('not merged', queryObj2);
```

Here's the output I am getting:

```js
merged { where:
   { starts: { [Symbol(gte)]: 2019-03-05T19:41:33.232Z },
     deleted: false,
     organizers: {} },
  offset: 0,
  limit: 30 }
not merged { where:
   { deleted: false, organizers: { [Symbol(contains)]: [Array] } } }
```

So when I merge 2 objects with merge(), the `organizers` field is empty, however when I just use the plain object I have the `contains` symbol as a key.

I am getting the same result when I log the `defaultQueryObj` instead.
Is there a way I can merge objects without losing the symbol keys?

I use `lodash.merge@4.6.1`

**Comment by jdalton** [comment]
Hi @serge1peshcoff!

Yes, `_.merge` does not support merging symbols.

**Comment by cjancsar** [comment]
@jdalton do you have a suggestion to achieve that through lodash?

**Comment by jdalton** [comment]
You might try [_.mergeWith](https://lodash.com/docs/#mergeWith).

**Comment by andrejleitner** [comment]
@jdalton, please, do you have an example how to get the symbols working with `_.mergeWith`?

**Comment by std4453** [comment]
> @cjancsar / @jdalton, please, do you have an example how to get the symbols working with `_.mergeWith`?

https://stackoverflow.com/questions/60598225/how-to-merge-javascript-object-containing-symbols
