### ISSUE TITLE
debounce maxWait undefined option has not the same behavior as not passing the option

### ISSUE THREAD

**Issue by ahoehn** [lodash/lodash#4224]
The behavior of debounce is not the same, if I pass a undefined maxWait option instead of not passing this option.
Because this option is a numeric property, the behavior should be the same if the option value is undefined or the option is not present. Otherwise the function caller needs to check if the maxWait value is undefined and in that case not pass the option to the debounce function.

With a undefined maxWait, the function gets called after the wait time:
```
const debounceOpts = {maxWait: undefined };
debounce(() => {console.log('maxWait undefined', 1000, debounceOpts});
```

This works as expected:
`debounce(() => {console.log('no debounceOpts', 1000});`

**Comment by jdalton** [comment]
Hi @ahoehn!

Yes, our current behavior is to coerce whatever value is provided for `maxWait` to a number and use it.
