### ISSUE TITLE
error TS2304: Cannot find name 'Exclude'

### ISSUE THREAD

**Issue by markgrichanik** [lodash/lodash#4225]
Hi,
I'm getting  
[ERROR] [0m[1m[31mERROR in node_modules/@types/lodash/common/object.d.ts(1689,12): error TS2304: Cannot find name 'Exclude'.[39m[22m[0m
[ERROR] [0m[1m[31mnode_modules/@types/lodash/common/object.d.ts(1766,12): error TS2304: Cannot find name 'Exclude'.[39m[22m[0m
[ERROR] [0m[1m[31mnode_modules/@types/lodash/common/object.d.ts(1842,34): error TS2304: Cannot find name 'Exclude'.[39m[22m[0m

We are using TS 2.4.2 version with Angular 5 with lodash-es 4.17.4

**Comment by flavioespinoza** [comment]
Could you give specific typescript code that is throwing error?

**Comment by markgrichanik** [comment]
**TS2304**: Cannot find name 'Exclude' 
Didn't understand your question..
I'm trying to run 'npm run build'

**Comment by PHPSoft** [comment]
Have same issue. Fixed by downgrading Lodash to version 4.17.5 and @types/Lodash to version 4.14.108

**Comment by falsyvalues** [comment]
TypeScript typings aren't maintained by Lodash team :arrow_forward:  [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by bittleshub** [comment]
I am also running into this issue. This is causing a production build to no longer complete successfully. 
using:
"@types/lodash-es": "^4.14.5",
"lodash-es": "^4.17.4",
"typescript": "~2.3.2"

Based on comments seen here: https://stackoverflow.com/questions/55018665/following-lodash-error-on-build-cannot-find-name-exclude it seems like there was a change put in place that relies on Typescript 2.8+.

Can you please provide an update that does not require the typescript version to be updated past 2.3+?

**Comment by KGXarwen** [comment]
> Have same issue. Fixed by downgrading Lodash to version 4.17.5 and @types/Lodash to version 4.14.108

you are so smart!

**Comment by imsheth** [comment]
> Have same issue. Fixed by downgrading Lodash to version 4.17.5 and @types/Lodash to version 4.14.108

Thanks for saving the day and a lot of time !!

**Comment by austzyl** [comment]
You should use typescript 2.8 or newer or install a version of lodash types compatible with your typescript version (example with lodash for typescript 2.3): npm i -D @types/lodash@ts2.3.
