### ISSUE TITLE
Why remove toNumber from clamp.js?

### ISSUE THREAD

**Issue by gu-xionghong** [lodash/lodash#4227]
In this https://github.com/lodash/lodash/commit/bb7c95947914d12af5f79e7369dd59ce29bc61a8#diff-0fa729ad2821dcf5ae39913a31e48a3f commit, why remove 'toNumber' method? It will cause like this:
```js
clamp(Symbol(), -2, -2) 
// TypeError: Cannot convert a Symbol value to a number

```

**Comment by jdalton** [comment]
Hi @gu-xionghong!

It's in an effort to simplify the method logic and reduce dependencies. You can always use something like TypeScript to enforce typings.
