### ISSUE TITLE
Why can't the REPL runner in the document be used?

### ISSUE THREAD

**Issue by Rain120** [lodash/lodash#4229]
The document REPL runner cannot work

![image](https://user-images.githubusercontent.com/20939839/54018958-e9000980-41c4-11e9-8103-72e0da7030a1.png)

**Comment by jdalton** [comment]
Hi @Rain120!

The REPL does work, just not at this very moment. It looks like RunKit is having a slight hiccup. Try back in a bit and see if it resolves itself.
