### ISSUE TITLE
the precision of createRound

### ISSUE THREAD

**Issue by gu-xionghong** [lodash/lodash#4232]
Hello!
I have a question about `.internal.createRound`.
In the https://github.com/lodash/lodash/pull/4085 commit, I think the implementing is not correct. In JavaScript, the `Number.MAX_VALUE` is `1.7976931348623157e+308`, the `Number.MIN_VALUE` is `5e-324`. So I think the maximum exponential should be `+308`, and the minimum exponential should be `-324`. There are some problems about _.ceil():
```js
_.ceil(Number.MIN_VALUE, 294) 
// expect 1e-294, but return 1e-292

_.ceil(1.123e+308,-307) 
// expect 1.2e+308, but return 1.123e+308
```

**Comment by jdalton** [comment]
Hi @gu-xionghong!

There was likely an environment related limitation. Feel free to revisit the implementation with modern environments in mind.
