### ISSUE TITLE
sampleSize doesn't need to exist

### ISSUE THREAD

**Issue by Blanen** [lodash/lodash#4235]
In my opinion, a cleaner API would be a single sample function with an optional size parameter.

`sampleSize`'s size parameter is already somewhat optional. I can give it null and it will set it to `1`, but only with `n == null`
If I send a random other non-number value which`n  != null ` it will just return an empty array, effectively failing silently.

I propose a positive > 0 number check on the parameter instead. Preferably even throwing an error but I don't think anything in lodash does that yet.

**Comment by jdalton** [comment]
Hi @Blanen!

The difference is compatibility. Having a secondary param means it can be non-obvious of issues you'll have when you do something like `array.map(_.sample)`.
