### ISSUE TITLE
Please improve and add ES6 import instructions for lodash and per package modules

### ISSUE THREAD

**Issue by kristianmandrup** [lodash/lodash#4242]
I was just trying to use [lodash.camelcase](https://www.npmjs.com/package/lodash.camelcase) but was unclear how to `import` it.

Always trips me up

```ts
import * as camelcase from "lodash.camelcase";
import * as capitalize from "lodash.capitalize";
```

Normally I find that `*` is used to return an Object where each key is an API method.

`require` is "so ~2010-2015"

I would suggest you keep this for backwards compatibility but also export individual const names and perhaps a default export as well

I now see there is a [lodash-es](https://www.npmjs.com/package/lodash-es) but was too clear from the docs.

**Comment by illuminist** [comment]
```javascript
import camelCase from 'lodash.camelcase'
import capitalize from 'lodash.capitalize'

console.log(camelCase('this will be converted to camel case'))
```

`import camelCase from 'lodash.camelcase'` is equivalent to `var camelCase = require('lodash.camelcase')`.

`import *` is only valid for ES6 named export(aka. non-default export).
