### ISSUE TITLE
Please add support for mathematical intervals within collection paths for get and set methods

### ISSUE THREAD

**Issue by robertdumitrescu** [lodash/lodash#4245]
Hey,

I have the following:

``
it('should get for a path with special characters', async () => {

            let initialCollection = {id: 3, id3: {'(2, 3]': 'bla'}};

            let expectedResult = 'bla';

            let result = Lodash.get(initialCollection, 'id3.(2, 3]');
            expect(result).to.deep.equal(expectedResult);

        });
``

And it returns `undefined`. Lodash should have support for this kind of notations since is so widely used in the mathematical world. The fix for this would be to verify if inside the array notation (E.g: "[1]") is a comma or not.

**Comment by jdalton** [comment]
Hi @robertdumitrescu!

You might try using a path of `id3["(2, 3]"]` or providing a path array of the keys. `["id3", "(2, 3]"]`.
