### ISSUE TITLE
Proposal: findIndex and findLastIndex additional parameter

### ISSUE THREAD

**Issue by beradrian** [lodash/lodash#4246]
Hi,

It will be nice that findIndex and findLastIndex to have an optional additional index parameter `i`. There could be multiple elements matching the given predicate and the method could return the `i`th element matching that predicate. The default value should be 1.

**Comment by YuriGor** [comment]
Hi @beradrian, did you mean something like this?
```js
const _ = require('lodash');
let arr = [0,1,2,3,0,1,2,3,0,1,2,3];

_.mixin({'findNthIndex':(array,predicate,nthIndex=1,fromIndex=0)=>{
  let i=0;
  let res=fromIndex;
  while(res!=-1){
    res = _.findIndex(array,predicate,res+1);
    i++;
    if(i==nthIndex){
      break;
    }
  }
  return res;
}})

console.log('1: '+_.findNthIndex(arr,(a)=>a==2,1));
//> 1: 2
console.log('2: '+_.findNthIndex(arr,(a)=>a==2,2));
//> 2: 6
console.log('3: '+_.findNthIndex(arr,(a)=>a==2,3));
//> 3: 10
console.log('4: '+_.findNthIndex(arr,(a)=>a==2,4));
//> 4: -1
```

**Comment by beradrian** [comment]
@YuriGor, yep, like this.

**Comment by jdalton** [comment]
Hi @beradrian!

Thanks for the suggestion. We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by beradrian** [comment]
How many votes does it need? If it helps I can prepare a PR for it.

**Comment by beradrian** [comment]
@jdalton Can we proceed with the implementation?

**Comment by falsyvalues** [comment]
Hi @beradrian!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), no need to rush.
