### ISSUE TITLE
Is the number of callback arguments a safe criteria for optimization?

### ISSUE THREAD

**Issue by YuriGor** [lodash/lodash#4249]
Hi there, need advice, please.

Imagine some iteration method, which passes some data as arguments into the given callback:

_.eachDeep(obj, (value,key,parent,context)=>{});

How do you think, will it be safe enough inside eachDeep to rely on the number of arguments actually expected by given callback ( [callback.length](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Function/length) ) when deciding to omit the last argument and improve performance/resources consumption this way?

`context` is a complex object and extra computations/memory needed to build it. 

So if callback doesn't expect the fourth argument explicitly, there are low chances developer is going to use `arguments` or `rest` parameter to get it anyway.
Am I right? 
I just don't want to make developer specify additional option to turn building `context` on/off manually. Callback declaration is speaking enough in this case.
Is it good practice? 
Did you ever consider such a possibility in some Lodash methods?

**Comment by YuriGor** [comment]
I finally think it will be ok to rely on callback's number of arguments by default, 
but add some optional parameter to force generation all the parameters, regardless of the number of arguments expected by the callback.

**Comment by falsyvalues** [comment]
Hi @YuriGor!
Personally I would use that, without really high demand (use case) for it. For example V8 likes stability of call signatures because it's easier to optimise these calls so there is a trade off and really depends on the case.
