### ISSUE TITLE
Add string methods

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash#425]
For 3.0 I think it's time we adopt a few string methods.

I think we should start with
`capitalize`, `startsWith`, `endsWith`, `repeat`, `trim`, `trimLeft`, `trimRight`, & `truncate`

Are there any others you all think should make the cut for 3.0?

**Comment by uberllama** [comment]
I'll just toss in my vote for humanize and camelize. These are the two string manipulation methods I use constantly.

**Comment by askmatey** [comment]
:+1:

**Comment by uberllama** [comment]
For the record I've started using string.js and its excellent. I could be swayed in either direction: either a "compete enough" string extension in lo-dash that would convince me to drop string.js, or the option to build lo-dash without string extensions and continue to use string.js.

**Comment by jdalton** [comment]
Thanks for the feedback all. Our string methods are locked-in for v3.0.
