### ISSUE TITLE
Documentation: [Function iteratee=_.identity] could be String too

### ISSUE THREAD

**Issue by rentalhost** [lodash/lodash#4250]
A lot of functions we can argument the `iteratee` parameter with a String, but the doc specifics that it allows only `Function`. I think that the best typehint for it is `{Function|String}`.

```js
    /**
     * @see https://github.com/lodash/lodash/blob/4.17.11/lodash.js#L9237-L9260
     * @param {Array|Object} collection The collection to iterate over.
     * @param {Function} [iteratee=_.identity] The function invoked per iteration.
     */
    function flatMap(collection, iteratee) { ... }
```

**Comment by illuminist** [comment]
`iteratee` as an argument imply that the argument accept everything that can be input into `_.iteratee` function. So not only function and string but array and object can be used also.

**Comment by rentalhost** [comment]
@illuminist so in this case, will be better to update doc to be more permissive, like `{Function|String|Array|Object|...}`. It will avoid IDE inspections warning, once that a `String` or `Array` will be valid anyway.

**Comment by jdalton** [comment]
Hi @rentalhost!

I went back and forth on the super verbose jsdoc style.
While you're correct we opted for less detail there.
