### ISSUE TITLE
_.get: clarification on handling of string path vs array path

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [lodash/lodash#4252]
Currently, when passing an array to `_.get`, each element in the array must be one level deeper in the object. I expected that I could compose any paths in the array and `_.get` would be able to resolve each path segment in the array. Below is an example of what I mean. 

```js
const obj = { foo: { bar: [{ baz: 1 }, { baz: 2 }, { baz: 3 }] } }

_.get(obj, 'foo.bar[1].baz') // returns 2
_.get(obj, ['foo', 'bar', '1', 'baz']) // returns 2
_.get(obj, ['foo.bar[1]', 'baz']) // returns undefined
```

This may be intended, but it seems like something that could be supported.

**Comment by YuriGor** [comment]
What about this case:
```js
const obj = { 'foo.bar[1]': { baz: 2 } };
_.get(obj, ['foo.bar[1]', 'baz']); // should it return undefined?
```

**Comment by YuriGor** [comment]
Also, consider [toPath](https://lodash.com/docs/4.17.11#toPath) method, it may help in your specific case.

**Comment by StreetStrider** [comment]
The proposal seems reasonable from composability point of view.

**Comment by a-b-r-o-w-n** [comment]
@YuriGor `toPath` may work for my case, thanks for pointing that out. 

```
const obj = { 'foo.bar[1]': { baz: 2 } };
_.get(obj, ['foo.bar[1]', 'baz']); // should it return undefined?
```
Today this works. I think my proposal makes sense in this case as well because `_.get(obj. 'foo.bar[1]')` returns `{ baz: 2 }` which can then be used for `_.get({ baz: 2 }, 'baz')`.

Basically, my proposal is to recursively `_.get` each value for every path in the array arg.

**Comment by YuriGor** [comment]
Now there are no doubts:
- a single string is always a path(even if it's a one-level path)
- an array of strings is always an array of single fields

And your proposal will not work in this case,
because Lodash will have no idea did you mean a path or field name when you passed a string like 'foo.bar[1]' as an element of an array.

Adding additional options to guide Lodash how it should treat such kind of arguments is a pain. It's easier to let the developer prepare his path as he wishes by himself because it's a rare case.

**Comment by a-b-r-o-w-n** [comment]
I'm not sure why it would make a difference to the api? If the implementation were to recurse on every element in the array and yield the result of `_.get` to the next element it would make no difference to a consumer of the api. The change would make `_.get` more generalized by accepting an array of path-like strings, regardless of if they are nested or not. Peeking at the source, lodash is already determining whether a string arg is a [path or a key](https://github.com/lodash/lodash/blob/master/.internal/castPath.js). I don't see a reason why it couldn't also determine this for an array of strings.

After looking to `toPath`, it wouldn't work for my case. We have objects with a structure like 
```js
{
  'Foo.bar': {
    baz: {
      qux: [...]
    }
  },
  fizz: {...}
}
```
but only have access to a single string representing a path. We cannot deterministically prepare a path since we have no way of knowing if `Foo.bar` represents a nested path or a single property key.

**Comment by YuriGor** [comment]
`I don't see a reason why it couldn't also determine this for an array of strings.`
But do you see a way how to do it?
This is not a question to the source object nor to the given string array element, 
it's a question to the developer, who is asking Lodash to do something ambiguous.

Here is how it currently works:

```js
const obj1 = { foo: { bar: [{ baz: 1 }] } }; // deep object
const obj2 = { 'foo.bar[0]': { baz: 1 } }; // flat object with path-like field name

const log = console.log;

log('string path');

log(_.get(obj1, 'foo.bar[0].baz'));
// > 1

log(_.get(obj2, 'foo.bar[0].baz'));
// > undefined

log(_.get(obj1, '["foo.bar[0]"].baz'));
// > undefined

log(_.get(obj2, '["foo.bar[0]"].baz'));
// > 1

log('array path');

log(_.get(obj1, ['foo','bar','0','baz']));
// > 1

log(_.get(obj2, ['foo','bar','0','baz']));
// > undefined

log(_.get(obj1, ['foo.bar[0]','baz']));
// > undefined
// you suggest to return 1 here, right?

log(_.get(obj2, ['foo.bar[0]','baz']));
// > 1 -- you suggest...? 
// return undefined? There is no such path in the obj2.
// How to get '1' by array path then?

// and to make things even more interesting...
const obj3 = { 
  'foo.bar[0]': { baz: 555 }, 
  foo: { bar: [{ baz: 888 }] } 
};
log(_.get(obj3, ['foo.bar[0]','baz']));
log(_.get(obj3, ['foo','bar','0','baz']));
```
[see code above in the codepen](https://codepen.io/yurigor/pen/jRBKWm?editors=0010)

`We cannot deterministically prepare a path since we have no way of knowing if Foo.bar represents a nested path or a single property key.`
The same issue is with your proposal.

**Comment by a-b-r-o-w-n** [comment]
What would you expect `log(_.get(obj3, 'foo.bar[0]'));` to return?

**Comment by YuriGor** [comment]
for 
`log(_.get(obj3, 'foo.bar[0]'));`
 I'd expect to see
`{ baz: 888 }`

And for 
`log(_.get(obj3, '["foo.bar[0]"]'));`
-> `{ baz: 555 }`

But actually, it returns `{ baz: 888 }` in both cases
Looks like a bug for me, because there is no string path to get `{ baz: 888 }`

**Comment by a-b-r-o-w-n** [comment]
I think you meant `{ baz: 555 }` right? In your codepen I see
![image](https://user-images.githubusercontent.com/3619060/55903301-3683e380-5b82-11e9-941f-d44b43902b53.png)

**Comment by YuriGor** [comment]
Yes, it was a typo. `{ baz: 555 }` returned in both cases.
(I updated Codepen to see it live)

**Comment by YuriGor** [comment]
So Lodash actually checks if given string exists as a field name, if not then it treats it as a path.
As for me - it's wrong behavior. 
Main purpose of `get` method is to return deep values.
Documentation says the same:
```
Gets the value at path of object.
path (Array|string): The path of the property to get.
```
