### ISSUE TITLE
Roadmap clarification: Discontinue per method packages in favor of modular lodash

### ISSUE THREAD

**Issue by luislobo** [lodash/lodash#4253]
In the [Roadmap](https://github.com/lodash/lodash/wiki/Roadmap) it says:

`Discontinue per method packages in favor of modular lodash`

What does it mean? Can you expand? and when is this change supposed to be implemented?

I want to understand what I can continue to use and what I should stop using, so that I don't write future incompatible code.

**Comment by falsyvalues** [comment]
Next lodash version will be fully modular (see current work in progress on master branch). Individual packages like `lodash.clone` and others will be deprecated (as they are now).
