### ISSUE TITLE
Publish per-method NPM packages to fix security vulnerability

### ISSUE THREAD

**Issue by adamkrogh** [lodash/lodash#4254]
We have a few security vulnerabilities being reported by npm and another application ( called Black Duck) that are related to the per-method NPM packages of lodash that a third-party library is using.

Specifically, `sanitize-html` uses `lodash.isstring`, `lodash.mergewith`, and `lodash.clonedeep` which all have the same security issue that was already fixed in the primary lodash package.

This was mentioned a couple months ago in #4193 but looks like the packages still haven't been updated yet.

I noticed in the roadmap that you plan on getting rid of these per-method modules but until then, can we get the latest version published to all these NPM packages?  Thanks!

**Comment by falsyvalues** [comment]
Hi @adamkrogh!

It will be done as @jdalton said in #4193 and #4030. Until then though you can migrate to the primary `lodash` package and cherry-pick from it.
