### ISSUE TITLE
escape and lodash.escape differ in escaping backticks

### ISSUE THREAD

**Issue by no-stack-dub-sack** [lodash/lodash#4257]
Hi there, I had been using the full lodash library in an app, and realized I only need a few functions, so switched out for lodash.* npm modules. When I installed lodash.escape separately, I noticed some different behavior. Namely, lodash.escape _escapes_ backticks, while lodash's escape does not... unless I'm missing something? Here's the versions I'm using and some example output:

"lodash": "^4.17.11",
"lodash.escape": "^4.0.1",

```
import { escape } from 'lodash';

let str = escape('a `Messaging.EmailFileAttachment` array');
console.log(str); // 'a `Messaging.EmailFileAttachment` array'
```
vs.
```
import escape from 'lodash.escape';

let str = escape('a `Messaging.EmailFileAttachment` array');
console.log(str); // 'a &#96;Messaging.EmailFileAttachment&#96; array'
```

**Comment by d3r3kx14o** [comment]
as for `lodash` full library, the escape character mapping in `escape.js` is as following, without character ```, have no clue about the difference between this two.
`
const htmlEscapes = {
  '&': '&amp',
  '<': '&lt',
  '>': '&gt',
  '"': '&quot',
  "'": '&#39'
}
`

**Comment by d3r3kx14o** [comment]
There seem to different definitions from the developers, but only this one remains after a consolidation commit.

**Comment by falsyvalues** [comment]
Hi @no-stack-dub-sack!
The individual method packages are behind the primary one. There is a plan to tackle that.
