### ISSUE TITLE
dropWhile document error

### ISSUE THREAD

**Issue by weihong1028** [lodash/lodash#4260]
https://www.lodashjs.com/docs/4.17.5.html#dropWhile
> Elements are dropped until predicate returns falsey.

should be `Elements are dropped until predicate returns false.`

**Comment by weihong1028** [comment]
Searching for the full text of the document has 10 places to write this question, is it correct?

**Comment by illuminist** [comment]
Falsey value doesn't limited to only boolean `false`. Falsey value are `false`, `null`, `undefined`, `0`, `NaN`, and empty string. The doc stands correct.

https://developer.mozilla.org/en-US/docs/Glossary/Falsy

**Comment by weihong1028** [comment]
Ok, I understand, thank you for your answer.
