### ISSUE TITLE
isEqualWith doesn't loop over all keys if number of keys are different between both objects

### ISSUE THREAD

**Issue by maxcnunes** [lodash/lodash#4263]
I was looking for using `isEqualWith` to compare two objects but ignore a few fields during the comparison. But I found out it doesn't work as I expected. 

```javascript
function compare (value1, value2, key) {
    return key === 'creation' ? true : undefined;
}

var obj1 = { name: 'jack', creation: 1 }
var obj2 = { name: 'jack', creation: 2 }
var result1 = _.isEqualWith(obj1, obj2, compare);
// result is true

var obj3 = { name: 'jack', creation: 1 }
var obj4 = { name: 'jack' }
var result2 = _.isEqualWith(obj3, obj4, compare);
// result is false
```

That happens because internally it uses `equalObjects` which runs a pre-checking that matches the number of keys between both projects.

Is that correct? Shouldn't that checking be disabled on using `isEqualWith`?

**Comment by illuminist** [comment]
The catch is the customizer is also called on the objects themselves as the first check.

In this case, `compare` will once be called with `compare(obj1, obj2)` with undefined key 

Therefore, to bypass whole object checking is to change comparator to:
```javascript
function compare (value1, value2, key) {
    return !key || key === 'creation' ? true : undefined;
}
```

**Comment by jdalton** [comment]
Hi @maxcnunes!

It's by design though could change in the future.
Our comparison algorithm will exit early if property counts are not equal.

**Comment by ramisalem** [comment]
use isMatch instead

**Comment by AndrewKvalheim** [comment]
`isMatch` performs a partial comparison though, which doesn’t help if you want to:

- Ignore a specific set of properties
- Normalize undefined properties to `false`
