### ISSUE TITLE
_.round(Infinity, 2) returns NaN

### ISSUE THREAD

**Issue by jefffriesen** [lodash/lodash#4266]
```
_.round(Infinity) // Infinity
_.round(Infinity, 2) // NaN
```
Logically, it doesn't makes sense to round Infinity and especially round it to 2 decimal places. However, this is not a contrived example. The value being passed into _.round() is often a finite number where I need to round to 2 decimal places. Occasionally, the value is Infinity, which is a valid value in my case and should return Infinity. However, it returns NaN. 

I can put guards in my code to not round if the incoming value is Infinity, but 
a) It's not ideal
b) There is the inconsistency with `_.round(Infinity)` which works as I would expect

Is this an error or an edge case that needs to be guarded against? Thanks

**Comment by jdalton** [comment]
Hi @jefffriesen!

It's an edge case we didn't consider. I'm fine with making it consistent though. If you're up for a PR against `master` or `4.17.12-pre` branch that would be great!

**Comment by jefffriesen** [comment]
Ok, sounds good. I have a deadline right now, but I can try to put a PR together in a few days if that's soon enough (I know you are amazingly diligent about closing tickets).

**Comment by jdalton** [comment]
That'd be great. Thank you @jefffriesen!

**Comment by jefffriesen** [comment]
I see there are already a couple PRs for this. Great. I just want to also note that _.ceil and _.floor have this same problem

**Comment by jdalton** [comment]
Feel free to create your own PR @jefffriesen : )

**Comment by jdalton** [comment]
Closed by #4272.
