### ISSUE TITLE
Carbon ad slows API site when loading

### ISSUE THREAD

**Issue by donnyv** [lodash/lodash#4268]
The carbon ad in the lower left hand corner. Slows the site from loading and locks it until its done loading. This happens on Chrome 73.0.3683.103

**Comment by MitchellBouwman** [comment]
I've already blocked this one with AdBlocker.

**Comment by jdalton** [comment]
Hi @donnyv!

I'm sorry you've experienced a slow-down. I can't generally reproduce it.
