### ISSUE TITLE
_.xor works incorrectly with 3+ arrays

### ISSUE THREAD

**Issue by the-spyke** [lodash/lodash#4274]
Testing on the website
```js
_.xor([3, 4, 1, 6], [0, 1, 2, 3], [3, 2, 7, 6]);
```
gives `[4, 0, 7]`, but should be `[3, 4, 0, 7]`.

**Comment by jdalton** [comment]
Hi @the-spyke!

I believe `[4, 0, 7]` is correct.

**Comment by the-spyke** [comment]
@jdalton If you look at the picture of [symmetric difference](https://en.wikipedia.org/wiki/Symmetric_difference) of 3 sets. The intersection in the center is included. This is the missing number `3`, which is present in all 3 sets.

**Comment by jdalton** [comment]
The diagram in your link is first performing an XOR on A and B and then the result of that on C. In our case we're doing an XOR over all sets at once.

**Comment by poteat** [comment]
@jdalton 

I can confirm the current behavior is per-spec wrong, see the [n-ary symmetric difference](https://en.wikipedia.org/wiki/Symmetric_difference#n-ary_symmetric_difference).

The correct procedure is to count how many times an element has appeared, total.  If it was odd, then that element is included.

The Lodash xor function instead includes elements which are present in only one array.  I agree that this is more useful and intuitive, but the docs shouldn't link to symmetric difference as Lodash xor is objectively not the symmetric difference for any case n >= 3.

**Comment by jdalton** [comment]
Thanks for digging in @poteat!

I'm fine with our behavior.
