### ISSUE TITLE
The way Lodash gets modularized

### ISSUE THREAD

**Issue by YuriGor** [lodash/lodash#4275]
Hi folks, need advice, I am trying to start thinking about how to split Lodash extension lib to allow 'cherry picking'.

Now I just export a function, which expects a Lodash instance(=global _ by default) as an argument, patches it with several methods using _.mixin and returns it back.

Can I expect, that splitting monolithic lib into separate modules per function will be enough to allow tree shaking? Or I need to consider something else?

My lib now depends on Lodash (full). 

So if I want to get modularized - I should remove lodash dependency and use separately imported methods I only need?

In my entry script, I will just import all the methods and do patching of the Lodash instance, while each method will be still importable separately. 
Is that all I need to care about?

babel-plugin-lodash doesn't support _.chain, and I don't see it in the master, is it going to be dropped? I probably should avoid chaining in my lib too?

What will babel-plugin-lodash do if it will see a call for the method not existed int the Lodash?
Leave this line untouched or it will try to import such method blindly?
Any way to extend babel-plugin-lodash, to make it handle side mixins?

Now my lib is es5 compatible (I hope) is there a way to keep it so, but still use es6 modules? Maybe make an es5 build with Rollup?

Should I care about individual NPM modules per method?
I see an attempt to do so for Lodash, but now it looks like not very maintained...

**Comment by jdalton** [comment]
Hi @YuriGor!

The `lodash` package itself supports cherrypicking individual modules, e.g. `lodash/pick`. 
Supporting chaining is tricky, there was an abandoned effort [here](https://github.com/lodash/babel-plugin-lodash/pull/176/files) for it, but generally if you want cherry-picked methods you'll avoid the chaining syntax.

**Comment by YuriGor** [comment]
Thank you @jdalton!
And would you recommend to rely on given lodash instance and hope it will contain all the methods I need?
Or I should cherry pick methods from lodash installed as a dependency?

In the first case, the given instance may miss some methods I need if it was optimized somehow.
Or there may be no instance at all if the client code uses babel-plugin-lodash.

In another case, if I use cherry-picked from lodash dependency methods, but client code already has these methods in the lodash instance it wants to extend - in the final bundle code will be duplicated?

Probably I need a dry module for each method, which expects prepared Lodash instance or just an object with required methods, 
and also second, a pre-imported module with cherry-picked from lodash methods already passed into dry version?

And finally there will be the main script which accepts Lodash instance, imports 'wet' modules for each extension's methods and mixins it into Lodash?

And what do you think about separate NPM modules per method? Do you think it's an inefficient technique?

**Comment by jdalton** [comment]
You can make it a requirement for users to provide `lodash` or the subset you need. However, if you're creating a bundle then cherry-picking is the way to go. I'm not a fan of separate npm modules per method (they're a pain to keep updated).

**Comment by YuriGor** [comment]
Thank you @jdalton, let me please spend some more your time for this, 
I think it's useful to determine the optimal strategy for any other lodash extension libraries.

Let's imagine how usage will look in different cases

Now it supposed to be `require`d:
```js
const lodash = require('deepdash')(require('lodash'));
```
import now looks like this:
```js
import lodash from 'lodash';
import deepdash from 'deepdash';
const _ = deepdash(lodash);
```
full lodash + cherry-pick from extension + mixin into lodash:
```js
import lodash from 'lodash';
import addEachDeep from 'deepdash/addEachDeep';
import addFilterDeep from 'deepdash/addFilterDeep';
const _ = addFilterDeep(addEachDeep(lodash));
```
full lodash + cherry-pick couple of methods from extension + mixin into lodash:
```js
import lodash from 'lodash';
import addEachDeep from 'deepdash/addEachDeep';
import addFilterDeep from 'deepdash/addFilterDeep';
let _ = addFilterDeep(addEachDeep(lodash));
```
cherry pick from lodash + cherry-pick from extension, no lodash instance
```js
// user actually needs this:
import flatMapDeep from 'lodash/flatMapDeep';

// extension method requires this:
import merge from 'lodash/merge';
import clone from 'lodash/clone';
import cloneDeep from 'lodash/cloneDeep';
import isArray from 'lodash/isArray';
import isObject from 'lodash/isObject';
import each from 'lodash/each';
import eachRight from 'lodash/eachRight';
import has from 'lodash/has';
import set from 'lodash/set';
import unset from 'lodash/unset';
import isPlainObject from 'lodash/isPlainObject';

// user needs this extension:
import getFilterDeep from 'deepdash/getFilterDeep';
const filterDeep = getFilterDeep(
  { merge, clone, cloneDeep, isArray, isObject, each, eachRight, has, set, unset, isPlainObject});
```
Looks bad. Latest example is definetly a subject of refactoring/automation.

And if I'll do all this cherry-pick imports inside the es module
so the user will do only:
```js
// user actually needs this 4 lodash methods and he doesn't care about extension's needs:
import flatMapDeep from 'lodash/flatMapDeep';
import eachRight from 'lodash/eachRight';
import has from 'lodash/has';
import set from 'lodash/set';
// and this extension:
import filterDeep from 'deepdash/filterDeep';
```
Will these three methods `eachRight`, `has` and `set` both imported by user's code and by `filterDeep` be tree-shaked or duplicated in the final bundle?

Probably I need to test the latest approach with webpack/rollup first, maybe tree-shaker will handle it, how do you think?
Or I need my own `babel-plugin-deepdash` here?
