### ISSUE TITLE
Insufficient validation in Array methods

### ISSUE THREAD

**Issue by Kirill89** [lodash/lodash#4276]
Most of Array methods in doesn't check if arguments is really arrays.

For example `_.indexOf({length: 9007199254740991}, 'test')` will make node.js stuck.

I believe it could lead to possibility of DoS attack. An attacker with tiny payload could consume a lot of CPU.

**Comment by jdalton** [comment]
Hi @Kirill89!

Our array methods are generic in much the same way built-in array methods are:
```js
Array.prototype.indexOf.call({length: 9007199254740991}, 'test')
```
