### ISSUE TITLE
Can this output (lodash-es/difference.js) be smaller after tree shaking?

### ISSUE THREAD

**Issue by DJAlejandro** [lodash/lodash#4277]
I used 'babel-plugin-lodash' in my testing project and tree shaking with webpack 4.29

```
//index.js
import {difference} from "lodash-es"

const array3 = difference([2, 1], [2, 3]);
console.log("diff=" + array3)
```

![360截图17300331140716](https://user-images.githubusercontent.com/14656317/56478746-18a07200-64e4-11e9-87b7-341e9b31c328.png)

the output verdors chunk size before minizie is above  40kb.I know lodash-es/difference depends on many functions named begin with '_'.

My question is whether this size is normal?

**Comment by jdalton** [comment]
Hi @DJAlejandro!

You should check out [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin). 
Be careful though it turns off all features by default.
