### ISSUE TITLE
Feature request: _.hasValue

### ISSUE THREAD

**Issue by Mahammad8564** [lodash/lodash#4278]
```
_.hasValue(undefined) --> false
_.hasValue(null) --> false
_.hasValue('') --> false
_.hasValue(0) --> true
_.hasValue(false) --> true
_.hasValue(<something>) --> true
```

**Comment by YuriGor** [comment]
Empty string is a good value, just like a zero. Considering this, !_.isNil do the job.

**Comment by jdalton** [comment]
Hi @Mahammad8564!

We've had requests for similar methods in the past. The reason I've punted on them is everyone seems to have a slightly different take on what they perceive as value. In these cases I think it's better for you to create your own mixin or one-off helper method.
