### ISSUE TITLE
A function to find the existence of a sub-sequence in a parent string

### ISSUE THREAD

**Issue by Cazaimi** [lodash/lodash#4280]
Ex: `1jgskdjg123` contains `1s123` as a sub-sequence. 

This is especially useful in fuzzy string matching.

**Comment by jdalton** [comment]
Hi @Cazaimi!

Thank you for the suggestion. I don't believe we've seen this kind of method suggested before. It almost feels like it should be part of a suite of utils for fuzzy matching. Until we get a gauge on user interest it may be a good idea to go about creating such standalone lib for yourself.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

Related to #4279.

**Comment by Cazaimi** [comment]
@jdalton, I understand. Thanks.
