### ISSUE TITLE
let startsWith/endsWith target to be an array

### ISSUE THREAD

**Issue by YuriGor** [lodash/lodash#4281]
It will be handy to let specify search target as an array of possible values:
```js
function startsWith(string,target,position){
  if(isArray(target)){
    return some(target,(t)=>startsWith(string,t,position));
  }
  // ....rest of the current implementation
}
```

**Comment by jdalton** [comment]
Hi @YuriGor!

Moving forward we want to avoid overloading as much as possible to ensure folks get the smallest bundles possible.
