### ISSUE TITLE
how to convert key array object to one object

### ISSUE THREAD

**Issue by bhumin3i** [lodash/lodash#4282]
obj = {
    "businessdepartment" : [
        {
            "_id": "5cc0419a8f6e2012a8287cea",
            "name": "IT Department"
        }
    ],
    "businessunit" : [
        {
            "_id": "5cc0419a8f6e2012a8287cea",
            "name": "IT Department"
            "businessdepartment" : "5cc0419a8f6e2012a8287cea"
        }
    ],
    "hierarchicallevel" : [
        {
            "_id": "5cc0419a8f6e2012a8287cea",
            "name": "IT Department"
            "businessdepartment" : "5cc0419a8f6e2012a8287cea"
        }
    ],
};

convert to single array object:

newOBJ = [  
   {  
      "_id":"5cc0419a8f6e2012a8287cea",
      "name":"IT Department",
      "category":"businessdepartment"
   },
   {  
      "_id":"5cc0419a8f6e2012a8287xc",
      "name":"IT Department",
      "category":"businessunit"
   },
   {  
      "_id":"5cc0419a8f6e2012a8287b2l",
      "name":"IT Department",
      "category":"hierarchicallevel"
   },
   {  
      "_id":"5cc0419a8f6e2012a8287blmn",
      "name":"IT 2",
      "category":"businessdepartment"
   }
]

**Comment by falsyvalues** [comment]
Hi @bhumin3i!

For these kinds of questions head on over to our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by bhumin3i** [comment]
@falsyvalues thanks but can you suggest me some example?
