### ISSUE TITLE
What does "successive invocation" mean in the docs for reduce?

### ISSUE THREAD

**Issue by YuriGor** [lodash/lodash#4283]
I am implementing a deep version of `reduce` and want it to conform to its flat prototype.
From the docs:

> Reduces collection to a value which is the accumulated result of running each element in collection thru iteratee, where each **successive** invocation is supplied the return value of the previous.

Looks like word "successive" reflects nothing in the behavior of this method. 
`undefined` or `false` value returned from iteratee is accepted as a new accumulator value by the same way as any other value.
I also see no try/catch in the sources, so throwing an error is not an option too.
Native Array `reduce` method also doesn't suppose any difference.
Maybe it's some relict from the older versions?

**Comment by jdalton** [comment]
Hi @YuriGor!

I'm sorry there's confusion. See the MDN page on `Array#reduce` to get a better idea of how our [`_.reduce`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) works.
