### ISSUE TITLE
lodash/fp: can you explain the weird results of using push in map of reduce?

### ISSUE THREAD

**Issue by nltesown** [lodash/lodash#4287]
The following code makes 3 computations that I expect to be equivalent. Yet the one (`res2`) using lodash/fp and `push` gives weird results. How can it be caused by the use of the native Array `push` method (which mutates the variable)? Why does the same example work fine with non-FP lodash? (Live demo here: https://runkit.com/nltesown/5cd04f59773a81001b80206d)

```javascript
const _ = require("lodash/fp");
const fp = _.noConflict();

let data = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]];

let res1 = _(data)
  .map(item =>
    _(item).reduce((acc, v) => {
      acc.push(v);
      return acc;
    }, [])
  )
  .value();

let res2 = fp.map(fp.reduce((acc, v) => {
  acc.push(v); // Here we use the native method push. Trouble ahead! But why?
  return acc;
}, []))(data);

let res3 = fp.map(fp.reduce((acc, v) => {
  acc = fp.concat(acc, v);
  return acc;
}, []))(data);

console.log(res1); // => [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
console.log(res2); // => [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], …]
console.log(res3); // => [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
```

**Comment by jdalton** [comment]
Hi @nltesown!

With fp composition the accumulator is not create fresh for each composed reduce function. This is why create a mutationless version of the accumulator with `fp.concat()` works.

**Comment by nltesown** [comment]
Thanks a lot for the answer, @jdalton! I'll ponder on this and certainly learn something from it!
