### ISSUE TITLE
[get] Return an array if path contains an array

### ISSUE THREAD

**Issue by Floriferous** [lodash/lodash#4288]
I'd like to be able to receive an array of mapped values as a result of `get`.

The main use case for this, is to be able to drill down in arbitrary objects, and get consistent results based on the data structure. If you try to use `get` with a path that goes into an array, it doesn't really make sense to receive undefined as a result, just because `array[myFinalPath]` usually never exists, outside of integers.

Here are a few examples:

```js
const obj = { arr: [{ a: 1 }, { a: 2 }] }
get(obj, 'arr.a'); // [1, 2]

const obj = { arr: [{ a: { b: 1 } }, { a: { b: 2 } }] }
get(obj, 'arr.a'); // [{ b: 1 }, { b: 2 }]
```

Maybe this could be done with the current implementation with a "wildcard" path:

```js
const obj = { arr: [{ a: 1 }, { a: 2 }] }
get(obj, 'arr.*.a');

// or
get(obj, 'arr.**.a');
```

A few more nested examples, I believe it makes sense to nest arrays if you encounter multiple ones, which would also be the natural behavior for the recursion:

```js
const obj = { arr: [{ a: { b: '1' } }, { a: { b: '2' } }] }
get(obj, 'arr.a.b'); // [1, 2]

const obj = { arr: [{ a: [{ b: 1 }, { b: 2 }] }, { a: [{ b: 3 }, { b: 4 }] }] }
get(obj, 'arr.a.b'); // [[1, 2], [3, 4]]
```

**Comment by jdalton** [comment]
Hi @Floriferous!

I think this would be a great standalone package or set of utils to query object properties _(there may already be such a library out there)_.
