### ISSUE TITLE
In loadash-es, package.json should include "type":"module"

### ISSUE THREAD

**Issue by jehon** [lodash/lodash#4289]
In nodejs 12 with the "--experimental-modules", es (es6/esm) modules can be loaded.

But for that to work, for the file to be considered by nodejs as a esm module, by either end in .mjs or
because its package.json must specify "type: module".

Since lodash-es is specifically an es module, I suggest that its package.json contain "type: module". So that it can be loaded in nodejs also.

That should have no other side effects.

Documentation for nodejs here: https://nodejs.org/dist/latest-v12.x/docs/api/esm.html#esm_code_package_json_code_code_type_code_field

Why do I want that?

Well, I developp some es modules that need to work on both the server and the client, without any "bundling". So my module use lodash-es. Today, it can not be loaded in nodejs because nodejs consider it as a cjs (commonJS) module. This should do the trick.

**Comment by jdalton** [comment]
Hi @jehon!

Yes please. Feel free to open a PR with the change to the `es` branch.

**Comment by jehon** [comment]
Hi @jdalton 

Here you are...

Rocket-science, as you see :-)

**Comment by jdalton** [comment]
Thanks @jehon!

**Comment by jdalton** [comment]
Closed by #4292.

**Comment by damianobarbati** [comment]
@jehon @jdalton node v14 here in about 3w, and node v13 already has ESM enabled by default: would you reconsider the ESM support?
