### ISSUE TITLE
v8 Allocation - JS heap out of memory

### ISSUE THREAD

**Issue by jennasisis** [lodash/lodash#4291]
![image](https://user-images.githubusercontent.com/26691026/57576510-2edc8680-742f-11e9-928c-1b930473cc61.png)

###  Steps to reproduce:
* Start a program that will not exit unless killed manually ~~until CTRL+C is pressed (SIGINT)~~
* ~~Send SIGINT, in my case that's simply CTRL+C~~
* Wait a few seconds
* Error, crash.

### What was I doing to possibly trigger this crash?
I have no idea, other than I have a watchdog file that keeps my databases in order. Specifically, I use sqlite3 and Sequelize (lodash is dependency) to configure them.. not sure if that matters? Figured I'd put it in there in case. I was having an issue with it a few minutes ago where the DBs were locking up due to performing actions too quickly, stupid me for not async'ing it.

I'm posting this issue here because the stack trace included you guys. Sorry if that wasn't quite the right thing to do, but I'm not sure what else to do.

## Edit - The next morning
Doing some developing again and I noticed that I didn't even have to send a kill signal. It just crashed on its own.
Same problem, still you guys, but different error this time:
![image](https://user-images.githubusercontent.com/26691026/57582519-c07ddf80-7493-11e9-91b8-c6c1610c3f98.png)

Minor edit: Disabled the watchdog and problem no longer occurs.

**Comment by jdalton** [comment]
Hi @jennasisis!

Maybe it's an issue with the watchdog + node version + lodash operation that's causing the problem. I don't think there's anything actionable from our side though.

**Comment by jennasisis** [comment]
I see, yeah I was gonna close this if I kept having issues, thanks for doing it for me 👍
I'll open an issue with Sequelize and see if it's a problem on their end.
