### ISSUE TITLE
Lodash orderBy not sorting array of objects

### ISSUE THREAD

**Issue by sipi41** [lodash/lodash#4293]
I'm sorry to bother you but I'm trying to use the .sortBy() method of lodash to sort an array of objects, I did check the documentation and tried to find a solution online but could not see what I am missing... please help this newbie!

Basically, I'm getting a list of posts from "**https://jsonplaceholder.typicode.com/posts**" which basically return an array of objects, like this:

`[
  {
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
  },
  {
    "userId": 1,
    "id": 2,
    "title": "qui est esse",
    "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
  },
  {
    "userId": 1,
    "id": 3,
    "title": "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    "body": "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut"
  },...
]`

I would like to get the latest post, my idea is to sort the list by "_id_" descending, and then take top 3 from the list... so I did use (also axios):

Axios.get("https://jsonplaceholder.typicode.com/posts")
      .then(response => {
        console.log(**_.sortBy**(response.data, ["id"], ["desc"]));
      })`

in this case, **response.data** contains the json array of objects... the problem is that nothing happens to the array, the same thing is returned, even if I change the order to "asc"... only if I use the "title", I see ascending order, but if I try "desc" using title, nothing happens also... please check the imate below.

![image](https://user-images.githubusercontent.com/688562/57782026-02f02800-76f1-11e9-8742-ca95f1eec1bf.png)

**Would appreciate if you can help me to see what I am missing**... Thank you for your help!

**Comment by YuriGor** [comment]
```js
  // data is already ordered, so
  console.log(_.takeRight(data,3)); // last 3 ordered asc
  // or 
  console.log(_(data).takeRight(3).orderBy('id','desc').value()); // last 3 ordered desc
  // or if in real life you have unordered data
  console.log(_(data).orderBy('id','asc').takeRight(3).value()); //last 3 ordered asc
  console.log(_(data).orderBy('id','desc').take(3).value()); //last 3 ordered desc
```
https://codepen.io/yurigor/pen/yWgWZY?editors=0010

**Comment by sipi41** [comment]
I'm so sorry, my mistake... I was using **sortBy()** instead of **orderBy()** but I will try your solution, it seems different, as you seems to convert the object to lodash then use the property, will check your docs. Thank you Yuri.

**Comment by YuriGor** [comment]
> you seems to convert the object to lodash then use the property
it's [chaining](https://lodash.com/docs/4.17.11#chain) sequence f lodash methods.
Looks nice, but don't use it if you have plans to cherry pick separate lodash methods instead of loading whole lodash lib.
