### ISSUE TITLE
Feature request: _.deepFreeze

### ISSUE THREAD

**Issue by toshisugimo** [lodash/lodash#4295]
Hi!

I want to add a new function `_.deepFreeze` to lodash.

Pure javascript `Object.freeze()` does not freeze nested object.

```javascript
const user = {
  name: 'Taro',
  age: 24,
  email: 'foo@example.com',
  location: {
    country: 'Japan',
    city: 'Tokyo'
  }
}

Object.freeze(user);

user.location.city = 'Kyoto';
// This will work. Because nested objects are not frozen.

console.log(user.location.city);
//=> 'Kyoto'
// Change from 'Tokyo' to 'Kyoto'
```

The `_.deepFreeze` function I want to propose also freezes nested objects.

```javascript
const user = {
  name: 'Taro',
  age: 24,
  email: 'foo@example.com',
  location: {
    country: 'Japan',
    city: 'Tokyo'
  }
}

_.deepFreeze(user);

user.location.city = 'Kyoto';
// This will not work. user.location is immutable!
// TypeErrors will occur here if in strict mode.

console.log(user.location.city);
//=> 'Tokyo'
// Not changed
```

What do everyone think?
Thank you very much!

**Comment by ashclarke** [comment]
Just a note of support as I have a custom implementation in place for this.

**Comment by jdalton** [comment]
Hi @toshisugimo!

I think something like this would be good on its own or in a suite of utils for immutability. For a reference implementation you can check out [deep-freeze-strict](https://www.npmjs.com/package/deep-freeze-strict).
