### ISSUE TITLE
each

### ISSUE THREAD

**Issue by dalang81** [lodash/lodash#4297]

**Comment by dalang81** [comment]
![image](https://user-images.githubusercontent.com/4044561/57931393-ef101600-78ea-11e9-9e9f-93c90afa1a53.png)

**Comment by dalang81** [comment]
![image](https://user-images.githubusercontent.com/4044561/57931864-13202700-78ec-11e9-8176-321626eb2eb5.png)

**Comment by dalang81** [comment]
![image](https://user-images.githubusercontent.com/4044561/57932003-6a25fc00-78ec-11e9-9806-44cbce8cc36b.png)

**Comment by dalang81** [comment]
![image](https://user-images.githubusercontent.com/4044561/57932283-22ec3b00-78ed-11e9-9878-becc771d3d37.png)

**Comment by jdalton** [comment]
Hi @dalang81!

Thank you for the illustrations. Be careful with bracket-less arrow functions as they have implicit return. Lodash's `each` method will break-out of its iteration if the iteratee returns `false`.
