### ISSUE TITLE
Rename lowerCase to something more intuitive like lowerSpaceCase or something

### ISSUE THREAD

**Issue by rehfeldchris** [lodash/lodash#4298]
A quick search of issues here on github, and a quick google search, and my angry coworker (lol) tells me a lot of people get bitten by unexpected string modification behavior when they use the lowerCase() method, as they expect it to behave like toLower() does. I see why, and feel like I easily could have made the same mistake.

I understand the name matches your convention of your other *Case methods, but I still think you should change the name to something that is less likely to be misinterpreted so easily.

**Comment by jdalton** [comment]
Hi @rehfeldchris!

I agree. We'll reevaluate them in our next major bump.
