### ISSUE TITLE
Simple Async ForEach 

### ISSUE THREAD

**Issue by erlanggalab** [lodash/lodash#4300]
hello guys, im new here i want ask
there is such feature likes this ?
`async function eachAsync(obj, handler) {
 for (let i in obj) {
    if (typeof (obj[i]) !== 'function') { await handler(obj[i], i) }
 }
}`
so i can write 

`await eachAsync({a:1,b:2},async () => { 
  proccess....
})`

**Comment by erlanggalab** [comment]
i found library call 'async'.js

**Comment by jdalton** [comment]
Hi @erlanggalab!

Check out our sister library [async](https://www.npmjs.com/package/async).
