### ISSUE TITLE
Rename flowRight -> compose

### ISSUE THREAD

**Issue by GianlucaGuarini** [lodash/lodash#4301]
The `flowRight` method is just a confusing name for `compose`, I end up doing this in every project:
```js
import { flowRight as compose } from 'lodash';
```

My proposal is to rename the `flowRight` to simply `compose` or at least aliasing the `flowRight` method for a couple of releases deprecating it asap.

**Comment by GianlucaGuarini** [comment]
I will be glad to help with a PR in case this breaking change can be considered a step forward for the project.

**Comment by jdalton** [comment]
HI @GianlucaGuarini!

I'm happy with the name as is. I believe `lodash/fp` has `compose` as an alias 😸
