### ISSUE TITLE
Consider adding type=module to package.json?

### ISSUE THREAD

**Issue by damianobarbati** [lodash/lodash#4303]
This would enable consumer of library to use --experimental-modules on node@12 (https://github.com/nodejs/node/issues/27408#issuecomment-495298642).

I tried to add the field manually to node_modules/lodash-es/package.json and it works fine
Would that have unexpected side effects?

**Comment by blikblum** [comment]
See https://github.com/lodash/lodash/pull/4292#issuecomment-495364306

**Comment by damianobarbati** [comment]
Thanks!
