### ISSUE TITLE
_,get function converts unicode code to representation

### ISSUE THREAD

**Issue by znevrly** [lodash/lodash#4307]
Hi,
first of all thanks for awesome library! Now an issue:

having this json
{
	"pattern": "※＼\u001e9EÀ-ÖØ-öø-ÿĀ-ſ]+$"
}
and return value of "pattern" via _.get function is

※＼9EÀ-ÖØ-öø-ÿĀ-ſ]+$

so \u001e is converted to "RS" representation. Is there any way to preserve original string?

**Comment by jdalton** [comment]
Hi @znevrly!

I don't believe our library is converting property values there. You might check that the code is running in the expected content-encoding.
