### ISSUE TITLE
Please fix the search in the docs at the top

### ISSUE THREAD

**Issue by raviteja83** [lodash/lodash#4308]
In the current documentation, when the left nav is scrolled, search also gets scrolled. It would be better if the search is fixed at the top.

OS: Ubuntu 16
Browser: Chrome 74.0.3729.169 (Official Build) (64-bit)

**Comment by jdalton** [comment]
Hi @raviteja83!

If you'd like to try your hand at creating a PR head over to [lodash/lodash.com](https://github.com/lodash/lodash.com).

**Comment by J3m5** [comment]
It would be much better indeed.
You can get it now with a dark theme with [this stylus theme](https://userstyles.org/styles/141292/dark-lodash-docs).
