### ISSUE TITLE
Clipped array access

### ISSUE THREAD

**Issue by SukantPal** [lodash/lodash#4309]
I think a clipped array access method would be great. This method would would return the element at an index in an array. However, if the index is less than zero, it would return the first element in the array; on the other hand, if it were greater than or equal to the length of the array, the method would return the last element in the array.

**Comment by dwesty17** [comment]
Hey @SukantPal is this what you're looking for?

**Comment by jdalton** [comment]
Hi @SukantPal!

Thanks for the request. I think this is better suited for a scenario specific one-off helper in your code-base.
