### ISSUE TITLE
Console warning about iterator being deprecated

### ISSUE THREAD

**Issue by jakeleventhal** [lodash/lodash#4311]
When using the following [sandbox](https://codesandbox.io/s/compassionate-browser-bf9oi), I get this error message:
```iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error```

The error goes away when I comment out the line 12 (the one with the `draft-js` component)

**Comment by jdalton** [comment]
Hi @jakeleventhal!

The check from the log is unrelated to iterables and is just an array-like check. The warning is a false flag and will not effect the code once it goes silent.
