### ISSUE TITLE
Lodash drastically grew in size from v3 to v4

### ISSUE THREAD

**Issue by dr0bz** [lodash/lodash#4312]
Hello,
i've just updated lodash from 3.10.1 to 4.17.11 and the size of partially required functions grew from 16.61kb to 30.79kb (minified). This is how i required necessary functions:

```
var merge = require('lodash/object/merge'),
    clone = require('lodash/lang/clone'),
    isObject = require('lodash/lang/isObject'),
    isUndefined = require('lodash/lang/isUndefined'),
    isString = require('lodash/lang/isString'),
    isEmpty = require('lodash/lang/isEmpty'),
    map = require('lodash/collection/map'),
    each = require('lodash/collection/each'),
    includes = require('lodash/collection/includes'),
    debounce = require('lodash/function/debounce'),
    findIndex = require('lodash/array/findIndex');

module.exports = {
    merge,
    clone,
    isObject,
    isUndefined,
    isEmpty,
    isString,
    each,
    map,
    includes,
    debounce,
    findIndex
};
```
The required paths were rewritten after update like `var merge = require('lodash/object/merge'),` to `var merge = require('lodash/merge'),`
Is there something i'm doing wrong? I don't think the doubling of the size is normal.

Best regards,
dr0bz

**Comment by jdalton** [comment]
Hi @dr0bz!

It looks like you're on the right track for usage. You could reduce things further with bundle plugins like [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin). Keep in mind that plugin disables a lot of functionality by default (you have to opt-in to features).

**Comment by dr0bz** [comment]
Hi @jdalton , 

i didn't use it because of the babel-plugin-lodash limitation: ES2015 modules should be used. My project is using CommonJS as shown above. But i've found out, that bable-lodash-plugin which is mentioned/used in lodash-webpack-plugin isn't necessary at all if the functions are already selectively required. The above code produces 15kb sized lodash import with following lodash-webpack-plugin config:
```
{
  paths: true
}
```
The issue should stay closed. Letting the comment with my findings here for others.

Best regards,
dr0bz
