### ISSUE TITLE
Contributing guide unclear

### ISSUE THREAD

**Issue by sylvainar** [lodash/lodash#4313]
Hey there,

I developed two methods that I needed for my project which could be called `toPairsDeep` and `unzipObjectDeep`. I would like to contribute to lodash by adding those two methods to the codebase, however I don't even know where to start.

The `CONTRIBUTING.md` at your project root hasn't been edited since 2017, and I don't know what branch I should start working on. Seems that `npm test` on `master` doesn't work either.

Would you please update the contributing guide, even if it's temporary, or link to a wiki page detailing how to start contributing to this really popular project? Thanks a lot!

**Comment by falsyvalues** [comment]
Hi @sylvainar!

There is nice big **Notice** on top of CONTRIBUTING doc:

> Pardon the mess. The master branch is in flux while we work on Lodash v5. This means things like npm scripts, which we encourage using for contributions, may not be working. Thank you for your patience.

Regarding new features it depends on their need/speciality and so on, also on 👍 reactions. Everything is in the doc.

If anything was unclear please share.

**Comment by jdalton** [comment]
Hi @sylvainar!

For patches or bug fixes the `4.17.12-pre` branch is the one you want. For new things it would be `master` branch. Though the usual process is to first search for an issue related to the feature you wanted added, as there may already be a request, else create one to collect [feedback](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
