### ISSUE TITLE
_.assign and fp.assign behave differently

### ISSUE THREAD

**Issue by code-surfer** [lodash/lodash#4315]
```
a={foo:1}
b={bar:2}
_.assign(a,b)
// a is {foo:1,bar:2}, b is {bar:2}
```
```
a={foo:1}
b={bar:2}
fp.assign(a,b)
// a is {foo:1}, b is {bar:2}
```

Why isn't `fp.assign` mutating `a`? Since there's no documentation for the `lodash/fp` functions except for the FP guide and the FP guide doesn't point out this difference in behaviour (or does it?), I expect both `_.assign` and `fp.assign` to behave the same. What am I missing?
(`lodash@4.17.11`)
Thanks

**Comment by J3m5** [comment]
This is by design, fp promote immutability so it doesn't mutate a and b.

``` javascript
const a = { foo: 1 }
const b = { bar: 2 }
const c = fp.assign(a, b)
// a is { foo: 1 }, b is { bar: 2 }, c is { foo: 1, bar: 2 }
```

**Comment by code-surfer** [comment]
Thanks. This does restore the behaviour documented for `_.assign`:
```
a={foo:1}
b={bar:2}
fp.assign.convert({immutable:false})(a,b)
// a is {foo:1,bar:2}, b is {bar:2}
```
