### ISSUE TITLE
lodash.isEqual returns different result when order of arguments is switched

### ISSUE THREAD

**Issue by capaj** [lodash/lodash#4320]
As found out by @benjamn here: https://github.com/apollographql/apollo-client/pull/4924#issuecomment-499280139

here is how it runs in a console on lodash.com:
![image](https://user-images.githubusercontent.com/1305378/59087335-aacdcf80-8904-11e9-8cd2-267affbda1b0.png)

**Comment by miscoder** [comment]
@falsyvalues I'll take this issue.

**Comment by benjamn** [comment]
@miscoder I’m sure there are multiple solutions that would work, but [here’s one strategy](https://github.com/benjamn/wryware/blob/50e7d6181b0b937ad54b543118e823ad98e2bca9/packages/equality/src/equality.ts#L121-L129) that I settled on.

**Comment by cukejianya** [comment]
@miscoder Are you still working on this issue?

**Comment by cukejianya** [comment]
If it's alright with @miscoder, I would like to take on this issue. Not sure if he is still working on it.

**Comment by ccjmne** [comment]
It looks like @benjamn pretty much worked out the hard parts already, and @miscoder doesn't seem to have done any progress in the 3+ months he's had the claim to this issue. I think you can go ahead, @cukejianya.
If you aren't interested anymore or don't have the time these days, just let us know 🙂.

**Comment by cukejianya** [comment]
@ccjmne Sounds good.

**Comment by jdalton** [comment]
Closed by #4515.
