### ISSUE TITLE
Custom build configurator?

### ISSUE THREAD

**Issue by katerlouis** [lodash/lodash#4321]
Is there a reason that you do not have a user interface for custom builds? 

If no, I'd like to make one, which creates a zip file or the minified code ready to copy straight away. Bam!

What do you guys think?

**Comment by jdalton** [comment]
Hi @katerlouis!

I rather folks use the lodash modules and their favorite bundler. Custom standalone builds aren't really a thing anymore.

**Comment by katerlouis** [comment]
Okay :)
