### ISSUE TITLE
pending() for debounce and throttle fns

### ISSUE THREAD

**Issue by Narretz** [lodash/lodash#4322]
According to this PR: https://github.com/lodash/lodash/pull/3388 a pending() fn for throttle and debounce has been merged into master in 2017. However, it's not present in the latest release (4.17.11).

Was this intentional or did it fall through?

**Comment by falsyvalues** [comment]
Hi @Narretz!
It was merged to master and its scheduled to v5 (currently).

**Comment by joyrasmussen** [comment]
Is there a tentative release date for v5? Or when a prerelease will be made available?

**Comment by jdalton** [comment]
Hi @joyrasmussen!

There is no tentative date for v5/prerelease.

**Comment by rlue** [comment]
Mind if I ask why it's being reserved for a major version bump? It would be really nice to have in 4.x, and is not a breaking change.

**Comment by oliverdunk** [comment]
@falsyvalues / @jdalton: any thoughts here? It's been a few years and this would be great to have.

**Comment by jainkuniya** [comment]
We also have the same requirement. Bumping this up :)

**Comment by AbreezaSaleem** [comment]
Bump bump bump! I am using `"lodash.debounce": "^4.0.8",` and this is a MAJOR requirement for us!

**Comment by alvaro-berruga-thousandeyes** [comment]
@falsyvalues @jdalton Any plans of considering adding this to 4.x? @rlue made a really good point

**Comment by isonlaxman** [comment]
i would really like this feature as well, do consider adding

**Comment by serenajiang-db** [comment]
bump
