### ISSUE TITLE
set with numbers in path results in arrays containing empty

### ISSUE THREAD

**Issue by everett980** [lodash/lodash#4323]
When a path array contains numbers and the target object does not have a container for the number (i.e.: `_.hasIn(target, path.slice(0, indexOfNumber))` is `false`), then the target is populated with an array that contain as many `empty` entries as the path entry so that the index in the created array that equals the path entry is the specified value. If there are multiple numbers in the path, each number behaves this way.

However, if the target does have a container for the number (i.e.: `_.hasIn(target, path.slice(0, indexOfNumber))` is `true`), then it works as expected.

Below is the code I used to recreate the issue on [npm's runkit](https://npm.runkit.com/lodash):
```
// Load the full build of lodash
var _ = require('lodash');

var path = ['str0', 'str1', 2, 3];
console.log(_.set({}, path, 'value'));
/*
  results in issue:
  {
    str0: {
      str1: [ empty x 2, [ empty x 3, 'value' ]
    }
  }
*/
console.log(_.set({
  str0: {
    str1: {
      2: {}
    }
  }
}, path, 'value'));
/*
  works as expected:
  {
    str0: {
      str1: {
        2: {
          3: 'value'
        }
      }
    }
  }
*/
```
Copying & pasting the code (without the `require`) and running in chrome's dev console on [lodash's website](https://lodash.com/docs/4.17.11) presents the same issue.

**Comment by jdalton** [comment]
Hi @everett980!

You should give [_.setWith](https://lodash.com/docs/#setWith) a try.

**Comment by everett980** [comment]
@jdalton 

`_.setWith` works, thanks!

Out of curiosity, why is `_.set`'s implementation not equivalent to `(...args) => _.setWith(...args, Object)`?
