### ISSUE TITLE
Issue with map and parseInt?

### ISSUE THREAD

**Issue by kenk-ccs** [lodash/lodash#4325]
I came across this issue with 4.17.11 where calling parseInt directly from map returns a NaN for all but the first element but calling it indirectly via an anonymous function works as expected.

text = "39237,40323,50456"
// "39237,40323,50456"
_.map(text.split(','),parseInt) // Fails on second element
// (2) [39237, NaN, NaN]
_.map(text.split(','), function(n) { return parseInt(n); }) // Works as expected
// (2) [39237, 40323, 50456]

I'm baffled. It's consistent across every browser in which I've tried it so I don't think it's a browser issue.

**Comment by jdalton** [comment]
Hi @kenk-ccs!

This is because the iteratee argument signature of `_.map` is `value, index|key, collection` and the `parseInt()` function accepts a secondary argument `radix`.
