### ISSUE TITLE
Is @types/lodash compatible with FP?

### ISSUE THREAD

**Issue by ZYinMD** [lodash/lodash#4326]
I imported some modules from lodash/fp into my Typescript project, for example:
```import groupBy from 'lodash/fp/groupBy;```
and it's working well, however, if I do `npm install @types/lodash`, the linter will give me squiggles when I call `groupBy`, suggesting type errors, although the code still compiles and works.

Am I doing something wrong?

**Comment by jdalton** [comment]
Hi @ZYinMD!

I'm not totally sure. This looks like a question for the DefinitelyTyped folks.
