### ISSUE TITLE
can you provide a method like this?

### ISSUE THREAD

**Issue by changero** [lodash/lodash#4329]
it's very like [keyBy](https://www.lodashjs.com/docs/4.17.5.html#keyBy).

```js
var array = [
  { 'dir': 'left', 'code': 97 },
  { 'dir': 'right', 'code': 100 }
];
_.keyBy(array, 'dir');
// => { 'left': { 'dir': 'left', 'code': 97 }, 'right': { 'dir': 'right', 'code': 100 } }
```

but i hope it like this

```js
var array = [
  { 'dir': 'left', 'code': 97, 'other1': 111 },
  { 'dir': 'right', 'code': 100, 'other2': 222 }
];
_.functionName(array, ['dir', 'code']);
// => { 'dir': ['left', 'right'], 'code': [97, 100] }
// or 
// => [ ['left', 'right'], [97, 100] ]
```
or，Which existing method can be used

thanks

**Comment by trzenaro** [comment]
you could mix **_.reduce** and **_.map** to get what you want.

`var array = [
  { 'dir': 'left', 'code': 97, 'other1': 111 },
  { 'dir': 'right', 'code': 100, 'other2': 222 }
];

myFunc = (array,props) => 
  _.reduce(props,(result,prop) => {
    result[prop] = _.map(array,prop);
    return result;
  },{})

myFunc(array,['dir','code','other1'])`
