### ISSUE TITLE
Get to check for more than just undefined

### ISSUE THREAD

**Issue by reesmanp** [lodash/lodash#4330]
The `get` method only uses the default value if the value it finds is exactly `undefined`. This makes looking for data in an API response more cumbersome if the value is `null` rather than `undefined`.
For example:
```js
const object = { a: null };

get(object, 'a', []); // will return null
get(object, 'a') || []; // will return []
```

I am proposing adding a flag called `checkType` that when set to `true` checks the type of the found value with that of the default value (if one is provided) and returns the default value if the type is wrong.

```js
const object = { a: {} };

get(object, 'a', [], true); // will return []
```

I just believe that the default value should be used in more cases than what it is in.

**Comment by jdalton** [comment]
Hi @reesmanp!

I want to avoid adding a boolean flag (it falls into something called the boolean trap) and makes the API harder to reason about at a glance. In this case you can create your own module that wraps `get()` to create the desired result.
