### ISSUE TITLE
lodash.flowRight mutate params

### ISSUE THREAD

**Issue by yanglin5689446** [lodash/lodash#4331]
`_.flowRight` just return `flow(funcs.reverse())`, which mutate passed-in arguments, is this the expected behavior?

**Comment by jdalton** [comment]
Hi @yanglin5689446!

Our implementation is a bit more involved, but I'm guessing you're getting at the heart of an FP feature, immutability. If you're looking for more of that checkout [`lodash/fp`](https://github.com/lodash/lodash/wiki/FP-Guide).
