### ISSUE TITLE
isEmpty fried my Node server

### ISSUE THREAD

**Issue by mosesoak** [lodash/lodash#4333]
Sorry for the clickbait title, I’m a huge fan of Lodash and rely on it like JS’s missing standard lib. Thanks for the great work!

Using isEmpty fully crippled my Node server without any normal errors being thrown. 

I didn’t dig too deep into the problem but can report that the property being checked was decorated. This leads me to believe that the problem might be with a missing check for typeof ‘function’ prior to trying to dig into the object.

**Comment by jdalton** [comment]
Hi @mosesoak!

Our `isEmpty()` means more is the "collection" empty. For reference see our Collection methods in [the docs](https://lodash.com/docs).
