### ISSUE TITLE
Clone does not do a deep clone

### ISSUE THREAD

**Issue by javahemans** [lodash/lodash#4335]
Steps to reproduce:

Go to https://lodash.com/ and open your developer console.
Copy the below snippet and run it in console

```javascript
(() => {
     //
    let initialObj = [{
        attr1: 'value1',
        attr2: 'value2',
        attr3: 'value3',
        attr4: 'value4',
        attr5: 'value5',
    }];

    // the new constructed object
    let foo = {
        bar: initialObj[0],
        baz: initialObj[0]
    }


    let clonedFoo = _.cloneDeep(foo);

    console.log(clonedFoo);
    clonedFoo.bar[0] = 'valueChanged';
    console.log(clonedFoo);

})()
```

The expected behaviour: 

When the attribute(`bar`) of the cloned object(`clonedFoo`) is changed it will change the other attribute(`baz`) as well. While *deep* clone should be a complete new clone of the object...

**Comment by jdalton** [comment]
Hi @javahemans!

I cannot reproduce the issue. I see `baz` changed as well.

**Comment by javahemans** [comment]
@jdalton yeah exactly. The bug is "Baz is changing as well". Whereas after a deep clone, when you change `bar`, `baz` should not changed. 

Because we did a deep clone not shallow....

**Comment by jdalton** [comment]
The deep clone does not break the referential equality of the clone. So the cloned `bar` is `===` to the cloned `baz`.

**Comment by javahemans** [comment]
The documentation is saying that `This method is like _.clone except that it recursively clones value.` it copies the value. 

If the referential equality is retains, does the document should be changed?

Because based on the documentation, everyone may assume that it clones the values. Like gives the priority to the values....
