### ISSUE TITLE
Feature request: To consider adding immutable update of object

### ISSUE THREAD

**Issue by Lnfra** [lodash/lodash#4338]
Currently there is a mutable update that mutates the object passed in. This is an idea to have an update that will return a copy of the object passed in. Such that the update does not affect the original object.

There are two ideas here:

1) To return a complete new object like a clonedeep of the object + mutation of the copy

2) Another idea would be to just clone the objects along the update path. And reuse the existing objects which are not along the update path. So that the original object is not affected. This is a less expensive operation if the aim was to just not modify the original object 

A possible usage is to update state in a React component. Like a lite version of the [immutability-helper](https://github.com/kolodny/immutability-helper) or [immer](https://github.com/immerjs/immer) library 

An example of the second idea is here: 
https://gist.github.com/Lnfra/7854629987682fee44532cf2f96c73c8

**Comment by jdalton** [comment]
Hi @Lnfra!

Please check out our [`lodash/fp` wiki](https://github.com/lodash/lodash/wiki/FP-Guide).

**Comment by Lnfra** [comment]
Ah, i'll go check it out, didn't realize there was a module for FP. Tks.
