### ISSUE TITLE
Should _.flatten flat anything iterable?

### ISSUE THREAD

**Issue by desaroger** [lodash/lodash#4339]
I think it would be useful if _.flatten flats anything that is iterable, which usually means they implement Symbol.iterator.

The thing is I am currently migrating some of the jquery parts of a web to a native js alternative. The problem comes when I want to migrate something like `$elements.find("input")`. I would like to use `_.flatten(elements.map(e => e.querySelectorAll("input")))`, but querySelectorAll returns a `NodeList`, not an array. Other methods, like `element.childrens()` returns an `HTMLCollection` instead of an array too.

I tried to use `_.flatten`, but it does not work with them. I think it makes sense to work with anything iterable, always understanding that the result will always be an array.

Thanks!

**Comment by jdalton** [comment]
Hi @desaroger!

Lodash has avoided that for now. I'm not sure we'll tackle it in the future either. I'm pretty sure there are libraries specifically for iterables though.

**Comment by desaroger** [comment]
Okk, sure there is a reason for not implementing it. Thanks for answering @jdalton!
