### ISSUE TITLE
I don't understand the role of this part of the `getRawTag` function code.

### ISSUE THREAD

**Issue by wangdanting** [lodash/lodash#4340]
Please explain to me the role of the following code. Why do you need to add the part of the code marked below?
![58597380-D69A-4E51-A01B-6C63AC91A3F2-min](https://user-images.githubusercontent.com/16220538/59963806-f13d4400-952a-11e9-8bad-7ca4e86452a6.jpg)

**Comment by falsyvalues** [comment]
HI @wangdanting!

For these kinds of questions please visit our [gitter channel](https://gitter.im/lodash/lodash).
