### ISSUE TITLE
omit Angular 8 target es2015 TypeError: clone.function is not a function

### ISSUE THREAD

**Issue by A-Boudi** [lodash/lodash#4344]
Hello,

I updated my app to angular 8 where default compilation target have changed from es5 to es2015.

After this change, omit is not cloning objects properly. When functions of the cloned object are called, the following error is thrown: `TypeError: cloned.function is not a function`

example:
```
sheep = new Sheep();
sheep.age(); ==> 2
dolly = omit(sheep, 'whatever');
dolly.age(); ==> TypeError: dolly.age is not a function
```

When switching the compilation target from es5 to es2015, it fails. When switching back it works.

**Comment by jdalton** [comment]
Hi @A-Boudi!

I'm not too sure but, I'd recommend avoiding `omit` use in favor of more direct approach to object creation or cloning. `omit` is really heavy handed and you'll likely be better off with a more specialized approach.
