### ISSUE TITLE
Add support for globalThis when detecting global namespace

### ISSUE THREAD

**Issue by Jack-Works** [lodash/lodash#4345]
I'm working with the Realm proposal's polyfill. The polyfill runs all codes in strict mode.
And lodash-es fails to run in this context.

```
TypeError: Cannot read property 'Symbol' of undefined
at lodash-es/_Symbol.js
at lodash-es/_baseGetTag.js
at lodash-es/isFunction.js
```

Because `freeGlobal || freeSelf || Function('return this')()` all evaluates to undefined.

lodash should add support with `globalThis`

**Comment by jdalton** [comment]
Hi @Jack-Works!

If you're up for a PR I'm fine adding it.
