### ISSUE TITLE
Is there a reverse function of values?

### ISSUE THREAD

**Issue by 839998664** [lodash/lodash#4346]
I am using observable-mongo. Upon calling insertOneObs the objectId of the inserted document is returned. The code calls values function on the ObjectId and I am unable to extract the original value of objectId. The code in the library looks so:

`observer.next(_.values(result.insertedId));`

Calling toString on the returned value results in 

`[ 'ObjectID', <Buffer 5d 18 5d 93 9b 7c dd 56 14 3a fa b7> ]`

Is there a way to extract the value of ObjectID?

**Comment by jdalton** [comment]
Hi @839998664!

I'm not familiar with `observable-mongo`. I think you may find more help on the `observable-mongo` repo/project side of things.
