### ISSUE TITLE
feature request: premade versions of fp merge, assign, and defaults with args switched

### ISSUE THREAD

**Issue by dobesv** [lodash/lodash#4349]
Currently `lodash/fp`'s `merge`, `assign`, and `defaults` use the same argument order as the mutative versions.  However, it would be nice to have reversed arg order versions available without creating them ourselves.  I actually expected the argument order to be reversed already and was unpleasantly surprised to find they were not.

e.g.
```
> require('lodash/fp').merge({a: 1, b:2})({a: 2, c:3})
{ a: 2, b: 2, c: 3 }
> require('lodash/fp').mergeRight({a: 1, b:2})({a: 2, c:3})
{ a: 1, b: 2, c: 3 }
```

My main motivation for making this easy is that it makes these functions more useful in conjunction with `lodash/fp/update` - you can pass in some values to set as a group rather than do separate updates for each property.

The desired effect would be:

```
> require('lodash/fp').update('a', require('lodash/fp').mergeRight({b: 2, d: {e: 5}))({a: { b: 1, c: 3, d: { f: 6}}})
{a: { b: 2, c: 3, d: {e: 5, f: 6}}}
> require('lodash/fp').update('a', require('lodash/fp').assignRight({b: 2, d: 4}))({a: { b: 1, c: 3}})
{a: { b: 2, c: 3, d: 4}}
> require('lodash/fp').update('a', require('lodash/fp').defaultsRight({b: 2, d: 4}))({a: { b: 1, c: 3}})
{a: { b: 1, c: 3, d: 4}}
```

**Comment by dobesv** [comment]
See also https://github.com/lodash/lodash/issues/1754

**Comment by jdalton** [comment]
Hi @dobesv!

You can use our [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert) helper to customize methods to taste.

**Comment by dobesv** [comment]
True, but it's (a) less convenient and (b) doesn't have typescript support
