### ISSUE TITLE
escape() doesn't escape ; properly

### ISSUE THREAD

**Issue by rbirkgit** [lodash/lodash#4350]
escaping &; will return just a simple & in the browser because lodash escape returns & amp; when it should return & amp;; (note the extra ;)

Looking in the code I see the missing ; in all escaped chars.

[had to put a space after & sign above as editor otherwise swallows it]

**Comment by jdalton** [comment]
Hi @rbirkgit!

Our `escape` method is intended to be pretty simple. If you need more please check out [`he`](https://www.npmjs.com/package/he).

**Comment by rbirkgit** [comment]
The issue is not that it's simple. It that it's buggy!! It doesn't work!!

You need to add a ; to all escape codes. It's a simple fix. This bug should be re-opened.

**Comment by rbirkgit** [comment]
For example, the escape code for & is not & amp is in the lodash escape code. It should be & amp; with the ; at the end. It's a very simple fix.

**Comment by jdalton** [comment]
Hmm, I cannot reproduce:
```js
_.escape('&;')
// -> "&amp;;"
```

**Comment by rbirkgit** [comment]
Is this not the latest code?
https://github.com/lodash/lodash/blob/master/escape.js

You can see the missing ; at line 3:

 '&': '&amp',

**Comment by jdalton** [comment]
Please checkout our [release branch](https://github.com/lodash/lodash/blob/4.17.11/lodash.js#L384-L390).

**Comment by rbirkgit** [comment]
Interesting. That code is correct with the ending ;

**Comment by rbirkgit** [comment]
Commit 6cb3460fcefe66cb96e55b82c6febd2153c992cc is where the ; got removed. I guess you were supposed to remove ; at the end of the lines but you also removed the ; inside the escape code strings.
