### ISSUE TITLE
lodash/fp _set method not fully immutable

### ISSUE THREAD

**Issue by dietergeerts** [lodash/lodash#4351]
When using the `_set` method from lodash/fp, it always creates a new object, even when the operation would lead to the same object content-wise:

```
it('must test lodash immutability', () => {
  const base = { prop: 'A' };
  const changed = _set('prop', 'A', base);
  demand(base).to.equal(changed);
});

// AssertionError: {"prop":"A"} must equal {"prop":"A"}
```

To be fully immutable method, I think in the case above, nothing should happen and the same object must be returned, no? Because there will be no actual change. Unless I'm overlooking some reasons why we would not want this.

If this is not wanted for good reasons, then could this be documented? Maybe we also need to add methods for these that are not fully immutable to have ones that are?

**Comment by dobesv** [comment]
I don't think lodash currently makes any assumptions about whether the value being set can be tested for equality.  I guess it could use `SameValueZero` to check whether the value is changing, though.  But that would be a change in behavior, potentially a breaking one if people already wrote code assuming `set` would return a new object regardless of the value passed.
