### ISSUE TITLE
_.first first char of Hebrew string

### ISSUE THREAD

**Issue by ForeverYouth** [lodash/lodash#4352]
Hello. I'm having next issues:
I have next string "‏ריס" and use "first function of lodash". And if you copy and paste this string to console you could see than first char of string is empty char (char code 8207).
So i need to get first symbol of this string. But instead of first letter if get empty string. How can i solve this problem?
I cannot Appeal to second char of string - because sometimes i have English string without char 8207. I always need to get first letter. How can i skip char 8207 using _.first?

**Comment by jdalton** [comment]
Hi @ForeverYouth!

You might check out [`astral-regex`](https://github.com/kevva/astral-regex) for part of the solution and message folks in our [gitter chat](https://gitter.im/lodash/lodash) for suggestions.
