### ISSUE TITLE
Clear all memoization cache

### ISSUE THREAD

**Issue by Tails128** [lodash/lodash#4353]
(I wrote the first 2 params as if it was a story from agile development, I hope it is fine)

As a developer of big applications

I would like to be able to clear all cached functions with a function call (or an assignment) in order to make my application scalable and not having to manually track every memoized function.
An even cooler function would be the possibility to "tag" memoized functions and clear cache by tag.

E.g: Let's suppose I have many setting files and that I update one of them...

Right now I have to manually `export` ALL the memoized functions related to that setting file in a list (array, map, stack, etc...) in order to be able to retrieve it and iterate over it to clear all caches during my boostrap/initialization.

It would be super cool to be able to just do something as:
`_.memoize.clearAllCaches()` 
or
 `_.memoize.caches.foreach((cachedFunction) => cachedFunction.cache = new Map():)`

It would be even more awesome to do something like: `_.memoize.cachedFunctions.get("myTag").foreach((cachedFunction) => cachedFunction.cache = new Map())`

This would also be cool for testing (so that in case your function relies on sub-functions, you can simply clear all the cache, removing complexity from the test function)

**Comment by jdalton** [comment]
Hi @Tails128!

I believe you can do something like that by [customizing `_.memoize.Cache`](https://lodash.com/docs/#memoize). By creating your own `Cache` constructor you can track cache instances and clear them as needed.

**Comment by easypizi** [comment]
Hi @jdalton would you be so kind to provide any example of how to do that correctly? I mean to customize _.memoize.Cache function?
