### ISSUE TITLE
4.7.12 lodash-es broken in browsers

### ISSUE THREAD

**Issue by ascott18** [lodash/lodash#4356]
`ReferenceError: root is not defined`

Chrome 75.0.3770.100 (Official Build) (64-bit)

Caused by https://github.com/lodash/lodash/commit/51c827ffd99d7532c50474a5b4fcab912f6d8040#diff-a3f56cdc79b5cced4fb021ebed6d3255R6

**Comment by jdalton** [comment]
Nothing compliments a version bump, like another version bump :)

**Comment by jdalton** [comment]
`lodash-es@4.7.13` is published :tada:
