### ISSUE TITLE
Wrong type detection in lodash/sortBy with TypeScript

### ISSUE THREAD

**Issue by goodwin64** [lodash/lodash#4360]
Hi!

It seems that `lodash/sortBy` detects the type of 2nd argument of iteratee function (comparator) incorrectly. It relates to both named and default lodash imports.
At the same time, `stable` sorting helper detects it properly.

(sandbox: https://codesandbox.io/embed/priceless-haslett-be2h6)

Question: May I doing smth wrong or there is a problem with _.sortBy with TS?

```typescript
import _ from "lodash";
import sortBy from "lodash/sortBy";
import stable from "stable";

export interface ITableRow {
  accountId: number;
  companyName: string;
}

const rows: ITableRow[] = [];

// TS error
const sortedList1 = sortBy<ITableRow>(
  rows,
  (a, b) => a.accountId - b.accountId
);

// TS error
const sortedList2 = _.sortBy<ITableRow>(
  rows,
  (a, b) => a.accountId - b.accountId
);

// ok
const sortedList3 = stable<ITableRow>(
  rows,
  (a, b) => a.accountId - b.accountId
);

```

**Comment by falsyvalues** [comment]
Hi @goodwin64!

TypeScript typings aren't maintained by Lodash team :arrow_forward:  [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Try to install `lodash` and `@types/lodash` only and test.
