### ISSUE TITLE
What's the difference between v 4.17.12 and 4.17.14

### ISSUE THREAD

**Issue by ygt-mikekchar** [lodash/lodash#4362]
OK.  This is probably a stupid question, but I figured I might as well ask it.  I'm looking at the source code in the tagged revisions 4.17.13 and 4.17.14 and I can't see any code changes -- just a rebuild and bumping of the version numbers.  Am I missing something?

**Comment by falsyvalues** [comment]
Hi @ygt-mikekchar!
How about reading [Changelog](https://github.com/lodash/lodash/wiki/Changelog)?

**Comment by ygt-mikekchar** [comment]
Hi @falsyvalues I did, but I couldn't see any commit that implemented that code.  Is it in a different package?  If I do a diff between those two tags, all I get are updates to the version numbers.  That's why I'm asking.

**Comment by falsyvalues** [comment]
But what is missing here: https://github.com/lodash/lodash/compare/4.17.11...4.17.14? They were merged to non existing branch. Take a look also on [closed pull requests](https://github.com/lodash/lodash/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+head%3A4.17.12-pre).

**Comment by ygt-mikekchar** [comment]
Thanks for the reply.  I realise this is probably annoying.  I'm just scratching my head here and can't figure out what's going on.  It's really this range I'm interested in: https://github.com/lodash/lodash/compare/4.17.12...4.17.14

**Comment by falsyvalues** [comment]
So this is [v4.17.14](https://github.com/lodash/lodash/commit/15421d13b724ccb42a2d4ba7530e0cd2ab363a05#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) change and [v4.17.13](https://github.com/lodash/lodash/commit/078664194c0459afc66b7485a551c7f40148d388#diff-a3f56cdc79b5cced4fb021ebed6d3255) change on es branch.

**Comment by ygt-mikekchar** [comment]
OK.  I think I understand now.  I really appreciate your time.  Thank you!

**Comment by falsyvalues** [comment]
Happy to help 👍

**Comment by jdalton** [comment]
Feel free to ping anytime @ygt-mikekchar!

The changes were a bit tricky to track this go around because many of them were related to our secondary packages (so not the primary `lodash` one). I'll update the changelog links to point to the `-npm` or `-es` branches for those releases.
