### ISSUE TITLE
lodash ES6 and UMD modules should be provided in a single package

### ISSUE THREAD

**Issue by WouterBanckenACA** [lodash/lodash#4366]
Hi, 

We recently started using lodash(-es) in our project and we ran into several issues with the current lodash NPM packages. 

In our project:
* we are running Karma tests in ES5 using the CommonJs module format
* we are using Rollup (which requires ES6 to work) for our bundled file that is used in production

The current bundling of lodash(-es) does not easily support this workflow because:
* the 'lodash' NPM package only provides the UMD module format (and can not be used by Rollup)
* the 'lodash-es' NPM package only provides the ES6 module format (and can not be used in an ES5 setup)

Instead, both these formats can be supported in 1 NPM package by correctly defining 'main', 'module' and 'jsnext:main' in the package.json.

* 'main' should point to a file supporting the UMD module format
* 'jsnext:main' and 'module' should point to a file supporting the ES6 module format

More information: https://github.com/rollup/rollup/wiki/pkg.module

Is there any plan to support this?

Wouter

**Comment by jdalton** [comment]
Hi @WouterBanckenACA!

We are moving away from all-the-things in a package. If you're bundling then you should bundle the sources into the output your prefer. Bundlers like rollup should support aliasing one module like `lodash` as another like `lodash-es` as well.

**Comment by WouterBanckenACA** [comment]
Hi @jdalton 

Thanks for the quick response! Can you clarify some of the statements you made?

_We are moving away from all-the-things in a package._ 

Should I interpret "all-the-things" as the different module formats or as the different lodash features? According to your roadmap you are moving away from method packages. In terms of the different module formats, the common approach for NPM repositories seems to be that the 'module' entry in the package.json is used specifically to make the difference between the UMD format and the ES6 module format (see again https://github.com/rollup/rollup/wiki/pkg.module)

_If you're bundling then you should bundle the sources into the output your prefer_

If I interpret this as having to select a different NPM package of the same code for different use case, I think this makes using `lodash` a lot harder than it should be since all functionality can be provided in a single NPM package and module bundlers/module loaders can select the version they require.

_Bundlers like rollup should support aliasing one module like lodash as another like lodash-es as well._

Aliasing modules during treeshaking seems to be an unnecessary step and boilerplate if there could just be a single exported module name (`lodash`) in a single NPM package.

**Comment by jdalton** [comment]
@WouterBanckenACA 

> Should I interpret "all-the-things" as the different module formats or as the different lodash features? 

As the different module formats and builds. The current `lodash` package is over 4Mb on disk due to it containing monolithic builds, core builds, minified versions of both, cherry-pickable modules, ane FP modules.

> Aliasing modules during treeshaking seems to be an unnecessary step and boilerplate if there could just be a single exported module name (lodash) in a single NPM package.

With the next major version bump `lodash` will only be ES modules (making `lodash-es` deprecated and unnecessary). We'll use something like [`esm`](https://www.npmjs.com/package/esm) to support loading in older Node environments.

**Comment by mesqueeb** [comment]
@jdalton You say "with the next major version", but I see that the [last release](https://github.com/lodash/lodash/releases) was on on 18 Jul 2019, and it seems like the next major version isn't released yet. Am I correct?

Is this package still being worked on?

**Comment by falsyvalues** [comment]
@mesqueeb v5 is still on the road to its final shape.

**Comment by viT-1** [comment]
How to use loadsh without bundlers, for example with SystemJs [I have](https://github.com/viT-1/direct-vuex-systemjs/blob/master/src/importmap.system.json) importmap:
```
{
	"imports": {
		"direct-vuex": "https://cdn.jsdelivr.net/npm/direct-vuex@0.9.3/dist/direct-vuex.umd.min.js",
		"vue": "https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.min.js",
		"vuex": "https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.min.js"
	}
}
```

**Comment by pavel-kolesnikov** [comment]
this is "closed" but still unresolved for 3 years... pity

**Comment by lake2** [comment]
> this is "closed" but still unresolved for 3 years... pity

4 year now
