### ISSUE TITLE
Jest reports memory leak when using lodash/fp

### ISSUE THREAD

**Issue by vunguyenhung** [lodash/lodash#4368]
**Lodash version**: `4.17.14`
**Jest version**: `24.8.0`
**Node version**: `10.16.0`
**Steps to reproduce**: 
- Clone repo: https://github.com/vunguyenhung/jest-profile
- Install deps: `npm i`
- Run the script: `npm run test:lodash-fp-sum`
  This script will run `jest` with `--detectLeaks` flag on `sum` function of `lodash/fp`
- Observe the test result:
```
 FAIL  src/lodash-fp-sum/sum-lodash-fp.test.js
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at node_modules/@jest/core/build/TestScheduler.js:257:24

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.195s
Ran all test suites matching /src\/lodash-fp-sum/i.
```
- Run the script: `npm run test:lodash-sum`
   This script will run `jest` with `--detectLeaks` flag on `sum` function of normal `lodash`
- Observe the result: the test pass with no error.

**Additional info:**
- Adding `--logHeapUsage` flag to see the heap usage, the heap usage of `lodash/fp` version is usually higher than the normal version by `2-4 MB`

**Background:**
We're using `lodash/fp` on production for a while now and notice high memory usage when running on large arrays with nested fields, and at the same time, we notice that our tests fail due to memory insufficient. After tracing down the rabbit hole, this is what we suspect this is one source of memory leaks.

**Comment by jdalton** [comment]
Hi @vunguyenhung!

Yes, the FP flavor will have higher memory due to the wrapped/curried/immutable nature of the methods. If you find the specific leak we'll happily accept a PR, but I don't have the bandwidth right now to go exploring for leaks on my own.
