### ISSUE TITLE
Odd behaviour with lodash get

### ISSUE THREAD

**Issue by fender** [lodash/lodash#4370]
Lodash version: 3.10.1

Slightly stumped here. These 2 lines are run one after the other but the first returns `undefined` whilst the second correctly returns the value. 🤔

```es6
get(state.pages, `${ownProps.location.pathname}.metadata`);
get(state.pages, [ownProps.location.pathname, 'metadata']);
```

This only happens when running the code within our automated integration tests which use Puppeteer. Any thoughts on what the cause of this might be?

**Comment by jdalton** [comment]
Hi @fender!

You might actually have a property named `foo.metadata` in which case it will be returned in your first usage. The second explicitly indicates 2 separate properties of `foo` and `metadata`.

**Comment by fender** [comment]
@jdalton The issue is that the first statement returns `undefined` but the second returns the the property. Are those 2 lines not the same logic? They path to foo.metadata.

What's more interesting is that both lines work fine when running outside of a Puppeteer environment. So I am trying to figure out what is causing the first one to break when run by Puppeteer.

**Comment by jdalton** [comment]
They are not the same logic. The first will look for an actual key of `o["foo.metadata"]` first and then split it into parts of `o.foo.metadata`. Puppeteer toString's a functions source and then `eval`s it on a page so maybe something is getting mucked up there.

**Comment by fender** [comment]
@jdalton Oh wow, so we've been using `get()` wrong all along! Thanks for the explanation. Is this worthy of me raising an issue with the Puppeteer folks?

**Comment by fender** [comment]
If anyone else comes across this and cannot be bothered to update the bajillions of instances of using string paths instead of arrays, I made a VSCode extension.
https://marketplace.visualstudio.com/items?itemName=fender.lodash-get-path-convert
