### ISSUE TITLE
 lodash versions 4.17.12, 4.17.13 and 4.17.14 are not found

### ISSUE THREAD

**Issue by KarthikRocker** [lodash/lodash#4373]
The following lodash versions 4.17.12, 4.17.13 and 4.17.14 are not available or not found while installing it through npm command.

**Check the below link for the screenshot of that issue.**
[Issue Screenshot](https://www.screencast.com/t/5ztQ2Iuq)

**Comment by Xotic750** [comment]
There seems to be a problem with the npm registry, see the same problems with webpack.
