### ISSUE TITLE
lodash clone and lodash merge

### ISSUE THREAD

**Issue by 1omercohen** [lodash/lodash#4375]
var objectA = { a: { b: 0 }}
var objectB = lodash.clone(objectA)

var objectC = lodash.merge(objectB, {a: {b:1})

expected : 
objectA => { a: { b: 0 }}
objectB  => { a: { b: 1 }}

but result is 

objectA => { a: { b: 1 }}
objectB  => { a: { b: 1 }}

**Comment by Xotic750** [comment]
I guess you re looking for cloneDeep

**Comment by 1omercohen** [comment]
thank you
