### ISSUE TITLE
Change documentation for sortBy when use second params as array

### ISSUE THREAD

**Issue by theGABS** [lodash/lodash#4376]
Hi, currently I see next example at `https://lodash.com/docs/4.17.14#sortBy`

```
_.sortBy(users, ['user', 'age']);
// => objects for [['barney', 34], ['barney', 36], ['fred', 40], ['fred', 48]]
```

The problem here - I don't understand users first sorted by age, then by name. Or visa versa ( first by name, then by age).

It will be awesome if you change default data to something like

```
var users = [
  { 'user': 'fred',   'age': 48 },
  { 'user': 'barney', 'age': 50 },  // CHANGES HERE, 36 -> 50
  { 'user': 'fred',   'age': 40 },
  { 'user': 'barney', 'age': 34 }
];
```

**Comment by jdalton** [comment]
Hi @theGABS!

Would you be up for creating a PR with the change?

**Comment by theGABS** [comment]
Okay, I would. Where is repository for documentation?

**Comment by jdalton** [comment]
It's inline. You can work from the `4.17.14` tag if you like and modify the `lodash.js` file from there to make your commit.

**Comment by theGABS** [comment]
@jdalton okay, I fork, and change documentation.
But I don't understand in which branch I should do pull request? 

My code is here https://github.com/theGABS/lodash/tree/4.17.14-fix-documentation-for-sortBy

**Comment by jdalton** [comment]
Try it one way on a tag and if it doesn't work i'll create a branch for you.

**Comment by theGABS** [comment]
I can open page "Comparing changes" 
https://github.com/lodash/lodash/compare/4.17.14...theGABS:4.17.14-fix-documentation-for-sortBy
but there is no button "Create pull request" or similar :(

**Comment by dev-warner** [comment]
is this till open to be taken? it's cool if its not.

**Comment by falsyvalues** [comment]
@jdalton I don't think its working that way. Are you able to create mr to tag?
@theGABS I created 4.17.5-post branch create pull request to it.

**Comment by jdalton** [comment]
Thanks for creating the branch @falsyvalues! It looks like branches are the way to go for PRs :)

**Comment by falsyvalues** [comment]
I made a mistake, it should be `4.17.15-post` :-) as it is now.

**Comment by theGABS** [comment]
I create PR (https://github.com/lodash/lodash/pull/4467)

**Comment by jdalton** [comment]
Moved to #4467.
