### ISSUE TITLE
Why lodash don't have object.diff ?

### ISSUE THREAD

**Issue by lwxbr** [lodash/lodash#4379]
Why lodash don't have a method that diff two objects( deep or shallow, whatever, it could be an option to the user define it) ?

**Comment by jdalton** [comment]
Hi @lwxbr!

I've avoided it because it's very scenario specific and less generally useful. There tend to be existing solutions dedicated to this that are likely a better fit.

**Comment by lwxbr** [comment]
Thanks for answering, @jdalton. Yes, already exist solutions for that purpose. I thought was generally used around.
