### ISSUE TITLE
add placeholder support to _.partial

### ISSUE THREAD

**Issue by davidchambers** [lodash/lodash#438]
jashkenas/underscore#1382

I was about to work on a patch for this, but I'm not sure how to go about it. I'm not familiar with Lo-Dash's internals.

**Comment by iddan** [comment]
What's the status of placeholders by now?

**Comment by jdalton** [comment]
Placeholders have been supported since v3 (2015).

**Comment by jdalton** [comment]
It was literally answered in the comment above yours.
