### ISSUE TITLE
Docs: Weird chrome lag on search

### ISSUE THREAD

**Issue by corby** [lodash/lodash#4380]
Sometime in the last week a change was made in the lodash docs that impacts the search bar in Chrome.

https://lodash.com/docs/4.17.14

When i start entering text in the search field the page chokes and take a very long time to respond.  Each key stroke takes a second or 2 to resolve.

HOWEVER, if I open the dev console (F12) the search is lightning fast and no lag or stutter is observed.
Firefox has no issues.

I've tried it with all extensions disbaled and in incognito mode as well.  Same thing, dev console off, search lags, dev console on, no problems.

**Comment by jdalton** [comment]
Hi @corby!

Nothing code wise has changed on our end.
