### ISSUE TITLE
Lodash/fp transform not working as expected...

### ISSUE THREAD

**Issue by oliverfoggin** [lodash/lodash#4381]
I wanted to contribute a fix for this but thought I should check that I'm not doing something wrong first...

When I use standard lodash in this example...
```
const _ = require('lodash');

run = () => {
  const mapping = {
    a: 'hello',
    b: 'world'
  };

  const object = {
    a: { value: true },
    b: { value: false }
  };

  const transformed = _.transform(
    object,
    (a, v, k, o) => { a[mapping[k]] = _.get(v, 'value'); },
    {}
  );

  console.log(transformed);
};

run();
```

The output is `{ hello: true, world: false }` like I expected.

When logging a, v, k, and o on the above code the output is...

```
1 a: {}
1 v: { value: true }
1 k: a
1 o: { a: { value: true }, b: { value: false } }

2 a: { hello: true }
2 v: { value: false }
2 k: b
2 o: { a: { value: true }, b: { value: false } }
```

However, when I run (what I think is) the equivalent code using `lodash/fp`...

```
const _ = require('lodash/fp');

run = () => {
  const mapping = {
    a: 'hello',
    b: 'world'
  };

  const object = {
    a: { value: true },
    b: { value: false }
  };

  const transformed = _.transform(
    (a, v, k, o) => { a[mapping[k]] = _.get('value')(v); },
    {}
  )(object);

  console.log(transformed);
};

run();
```

The output is `{ undefined: false }`. This is because the parameters to the iterator do not seem to be correct. When I log a, v, k, and o I get the following output...

```
1 a: {}
1 v: { value: true }
1 k: undefined
1 o: undefined

2 a: { undefined: true }
2 v: { value: false }
2 k: undefined
2 o: undefined
```

Am I doing something wrong or is this not working as expected?

Thanks

**Comment by oliver-foggin** [comment]
OK, I understand what I am doing wrong now... but I can't work out what is going on at all. Haha 😄

**Comment by oliver-foggin** [comment]
This has been closed but not actually answered.

Why does the iterated accept only two arguments but in reality it is given 4 arguments.

None of it makes any sense.

**Comment by oliver-foggin** [comment]
@jdalton not sure why this was closed?

**Comment by HenryRLee** [comment]
According to the [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide#capped-iteratee-arguments), the iteratee in `transform` method takes only two arguments.

**Comment by oliver-foggin** [comment]
@HenryRLee https://stackoverflow.com/questions/57149231/lodash-fp-transform-not-working-as-expected/57153272#57153272

The usual transform function takes four arguments. You can actually access them in the fp version too by using `arguments[2]` and `arguments[3]`.

But I found a better way of resolving this thanks to someone on SO.
