### ISSUE TITLE
15774 high level vulnerabilities reported for lodash.inrange individual package

### ISSUE THREAD

**Issue by steveswork** [lodash/lodash#4383]
Tried to install 'lodash.inrange' and received the following npm audit report: 
`
$ npm install --save lodash.inrange
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.1.0 requires a peer of eslint-plugin-import@^2.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-prettier@3.0.1 requires a peer of prettier@>= 1.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ lodash.inrange@3.3.6
added 1 package from 3 contributors and audited 877839 packages in 19.219s
found 15777 vulnerabilities (3 moderate, 15774 high)
  run `npm audit fix` to fix them, or `npm audit` for details

`

**Comment by jdalton** [comment]
Hi @steveswork!

In a fresh project when I do `npm i lodash.inrange` I get:
```bash
+ lodash.inrange@3.3.6
added 1 package from 3 contributors and audited 1 package in 0.279s
found 0 vulnerabilities
```

**Comment by steveswork** [comment]
How is this question invalid? So it works on your computer and you disregard the reported problem. By the way, I also see that you are not targeting the dependencies property of your package.json object in your install. In any case, what do you surmise is causing the vulnerabilities to be reported on my side when I install the same package?
