### ISSUE TITLE
isBuffer does not works in browser even when window.Buffer is defined

### ISSUE THREAD

**Issue by blikblum** [lodash/lodash#4384]
_.isBuffer is always mapped to `stubFalse` in browsers even when window.Buffer is defined.

This occurs because `moduleExports` is always false

Initially i think that it would affect only es version as show in https://codepen.io/blikblum/pen/LwVOmx

But even loading lodash as a script, the bug occurs as seen in https://codepen.io/blikblum/pen/RXPjXy

This will, probably, affect also v5 (master) when running with node with native es module support or a with a bundler that does not injects module automatically (webpack v5 or rollup)

I looked to create a PR for v4 but there's no v4 branch anymore

Should i create a PR for master only?

**Comment by jdalton** [comment]
Our `isBuffer` is really about the Node `Buffer` and not anything else in the browser. BTW with `lodash-es` you don't need the unpkg `module` flag.

**Comment by blikblum** [comment]
And about running in node with native ES module support?

**Comment by jdalton** [comment]
That's still experimental.
_(I'm a Node core member and in the Node Modules working group.)_

I tried adding experimental support for it, via the `type` package.json field but it broke some ecosystem things with older versions of `npm`. So I'm waiting a bit before trying again.
