### ISSUE TITLE
_.isEqualWith() invokes customizer twice, first with wrong (objValue, otherValue)

### ISSUE THREAD

**Issue by ahsan-mian** [lodash/lodash#4385]
Hi,

Am facing the same issue which is already discussed here https://github.com/lodash/lodash/issues/2490

Although the issue is closed by the bot but it's still reproducible, can some one confirm if it's fixed or any resolution.

Thanks.

**Comment by jdalton** [comment]
Hi @ahsan-mian!

The reasoning is covered at https://github.com/lodash/lodash/issues/2490#issuecomment-231597691.
