### ISSUE TITLE
Lodash Prototype Pollution

### ISSUE THREAD

**Issue by OrionStark** [lodash/lodash#4386]
# Bugs and Questions

### Checklist
- [x] I am using the latest version of lodash

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Got this problem when I'm installing lodash >=4.17.12
This is the `npm audit` detail:  
                                                                                
High | Prototype Pollution
----- | --------------------
Package | lodash
Patched in  |  >=4.17.12
Dependency of | @playlyfe/gql
Path  |  @playlyfe/gql > lodash
More info |  https://npmjs.com/advisories/1065

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

- [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

**Comment by wowa1234567** [comment]
Würde das sinnvoll zu löschen?

**Comment by wowa1234567** [comment]
Ich kante mich mit diesen repo nicht aus

**Comment by OrionStark** [comment]
@wowa1234567 I'm sorry. I can't understand what are you saying.

**Comment by falsyvalues** [comment]
Hi @OrionStark!
> I am using the latest version of lodash

Latest version of lodash is v4.17.15 and [advisory](https://www.npmjs.com/advisories/1065) refers to versions <  v4.17.12. Looks like `@playlyfe/gql` is using older one, not latest.

**Comment by OrionStark** [comment]
@falsyvalues  Thank you for your response. Really helpful for me. Thanks
