### ISSUE TITLE
[ question ]why get length of array in this way?

### ISSUE THREAD

**Issue by pimkle** [lodash/lodash#4390]
`const { length } = array`
what's the difference between 
`const length = array.length`
?
is it faster? just curious

And why create an Array in this way?
```
const result = new array.constructor(length)
```
🧐

**Comment by falsyvalues** [comment]
Hi @pimkle!
```
const { length } = array
```
This notation is shorter, we generally prefer new syntax if readability is not suffering on that.

```
const result = new array.constructor(length)
```
In this case we want to access constructor function of passed object (it might be not an Array constructor).

**Comment by jdalton** [comment]
Hi @pimkle!

The reason we do `new array.constructor(length)` in `initCloneArray()` is because the array could be coming from another iframe/realm and if we used simply `new Array` we would create an array from the primary window/realm.
