### ISSUE TITLE
Prototype Pollution vulnerability message on npm audit

### ISSUE THREAD

**Issue by rakoc001** [lodash/lodash#4393]
I am trying to create a nativescript app.

When I update my node-modules, platforms and hooks folders I get a warning about "2 high severity vulnerabilities"

Running `npm audit` shows they are both vulnerabilities from the lodash package

> C:\Users\chris\Documents\EAMS-Prototype-Asset-Survey-
>
> App\PrototypeAssetSurveyApp>npm audit
> 
>                        === npm audit security report ===
> 
> 
>                                  Manual Review
>              Some vulnerabilities require your attention to resolve
> 
>           Visit https://go.npm.me/audit-guide for additional guidance
> 
> 
>   High            Prototype Pollution
> 
>   Package         lodash
> 
>   Patched in      >=4.17.12
> 
>   Dependency of   kinvey-nativescript-sdk
> 
>   Path            kinvey-nativescript-sdk > kinvey-js-sdk > lodash
> 
>   More info       https://npmjs.com/advisories/1065
> 
> 
>   High            Prototype Pollution
> 
>   Package         lodash
> 
>   Patched in      >=4.17.12
> 
>   Dependency of   kinvey-nativescript-sdk
> 
>   Path            kinvey-nativescript-sdk > lodash
> 
>   More info       https://npmjs.com/advisories/1065
> 
> found 2 high severity vulnerabilities in 11942 scanned packages
>   2 vulnerabilities require manual review. See the full report for details.

I have got lodash version 4.17.15 installed so should not be experiencing this issue.

Any and all help will be greatly appreciated.

**Comment by blikblum** [comment]
kinvey-nativescript-sdk should update their dependencies

**Comment by jdalton** [comment]
Hi @rakoc001!

@blikblum is on right track that the dependency is not yours but of [`kinvey-js-sdk`](https://github.com/Kinvey/js-sdk/blob/a15d1d6594e2e3432bed9e3c6a4477a40280bee9/packages/js-sdk/package.json#L31) you may be able to bypass this with `npm audit fix` but I'm not positive.

**Comment by rakoc001** [comment]
> Hi @rakoc001!
> 
> @blikblum is on right track that the dependency is not yours but of [`kinvey-js-sdk`](https://github.com/Kinvey/js-sdk/blob/a15d1d6594e2e3432bed9e3c6a4477a40280bee9/packages/js-sdk/package.json#L31) you may be able to bypass this with `npm audit fix` but I'm not positive.

Unfortunately the npm-audit-fix shows the "2 vulnerabilities require manual review" message.

I'm glad to hear that it's not anything I've done wrong.

Thanks @blikblum and @jdalton for your help

**Comment by Tolson321** [comment]
Did anyone find a solution to this problem? npm audit fix also didn't work for me.

**Comment by Rafi993** [comment]
> Did anyone find a solution to this problem? npm audit fix also didn't work for me.

running ```$ npm audit fix``` fixed it for me

**Comment by YEASIN49** [comment]
if $ npm audit fix doesn't work go to the lodash folder and find package.json file check if it's(lodash) version match with the version mentioned in package-lock.josn file existing in main project folder. If it does not match then upgrade lodash from package.json file existing in lodash folder  to latest/stable version then return to your main project folder and run $ npm install .. I did not have this specific  vulnerabilities however most of cases this worked for me .
