### ISSUE TITLE
Ability to pass a method with arguments as an iteratie

### ISSUE THREAD

**Issue by bogdan** [lodash/lodash#4395]
As far as I understand, only a method with one argument can be an iteratee except the `property` and `matches` iteratee.

I think it would be useful to allow any function to be an iteratee with a syntax like:

```
a = [{a: 1, b: 2}, {a: 3, c:4}]
_.map(a, _.iteratee('pick', ['a'])) // => [{a:1}, {a:3}]
_.map(a, _.iteratee('update', 'b', null)) // => [{a: 1, b: null}, {a: 3, b: null, c: 4}]
```

Alternate syntax:

```
_.iteratees.update('b', null)
_.update.iteratee('b', null)
```

**Comment by cukejianya** [comment]
@bogdan Would the below example suffice for your issue?

```
_.map([{a: 1, b: 2}, {a: 3, c:4}], (obj) => _.pick(obj, 'a'))
// [ { a: 1 }, { a: 3 } ]

_.map([{a: 1, b: 2}, {a: 3, c:4}], (obj) => _.update(obj, 'b', () => null))
// [ { a: 1, b: null }, { a: 3, c: 4, b: null } ]
```


You can simplify this if you want by wrapping it up in a function called iteratee.
```
let _ = require('lodash');

function iteratee(method, ...args) {
  return (obj) => _[method](obj, ...args);
}
```

And you can just call it as such:
```
 _.map([{a: 1, b: 2}, {a: 3, c:4}], iteratee('pick', 'a'));
\\ [ { a: 1 }, { a: 3 } ]

_.map([{a: 1, b: 2}, {a: 3, c:4}], iteratee('update', 'b', () => null));
\\ [ { a: 1, b: null }, { a: 3, c: 4, b: null } ]
```

Let me know if this helped. Hopefully, this was what you were asking about.

**Comment by bogdan** [comment]
Yes, `interatee` function does what I want. I just was thinking that it should be part of lodash itself.
