### ISSUE TITLE
Internal usage of the `Date` class

### ISSUE THREAD

**Issue by Bart76** [lodash/lodash#4398]
There seems to be a discrepancy in internal implementations regarding their usage of the `Date` class, especially the `now` function.

The `now` lodash method uses the lodash `root` object representing the global context to get the `Date` class whose `now` method should be called.

On the contrary, `_shortOut.js` contains the following binding:

    var nativeNow = Date.now;

I personally would have expected, that `nativeNow` would also make use of lodash's `root` object.

Actually, with the current state of the implementation and the absence of specific documentation comments, this difference makes me doubt the correctness of both the implementation of the `now` function and the `shortOut` function.

**Comment by jdalton** [comment]
If you'd like to send a PR to remove the `root` use there I'd be all for it.
