### ISSUE TITLE
Lodash support for Json pointer

### ISSUE THREAD

**Issue by MeCode4Food** [lodash/lodash#4401]
Would be great for lodash to support json pointers as defined in [RFC 6901](https://tools.ietf.org/html/rfc6901), so for example given a JSON:

```
object = {
    "foo" : ["bar", "baz"],
    "pi" : 3.1416
}
```

The following JSON Pointers resolve this JSON as:

```
"/foo" → [ "bar", "baz" ]
"/foo/0" → "bar"
"/foo/1" → "baz"
"/pi" → 3.1416
```

so 
```
_.get(object, "/foo") = [ "bar", "baz" ]
_.get(object, "/foo/0") = "bar"
_.get(object, "/foo/1") = "baz"
_.get(object, "/pi") = 3.1416
```

**Comment by falsyvalues** [comment]
Hi @MeCode4Food!

We may think about adding this in v5. What do You think @jdalton?

**Comment by jdalton** [comment]
Thanks @MeCode4Food!

@falsyvalues Ya, I'm a fan of following an established accessor path syntax.

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by falsyvalues** [comment]
@jdalton I'm a fan of it too, we could have both 😃
