### ISSUE TITLE
Error when using _.isTypedArray on ie11

### ISSUE THREAD

**Issue by Subash** [lodash/lodash#4402]
```js
try {
  _.isTypedArray(Object.getPrototypeOf(document.styleSheets)));
} catch(err) {
  console.error(err); // throws `Invalid calling object` on ie11
}
```

**Comment by jdalton** [comment]
Hi @Subash!

`document.styleSheets` is a host object which may behave unexpectedly. We don't really support host objects since they cause plenty of issues. In this case I think your try catch approach is okay.
