### ISSUE TITLE
Question - using _.cloneDeep with cyclic graph objects

### ISSUE THREAD

**Issue by mnj11** [lodash/lodash#4403]
Project consists of cyclic graph objects. We use JSOG library to stringify the cyclic graph. With v3.10.1 using _.cloneDeep and stringify worked like a charm. However, after upgrading to v4.17.15, we have an issue with it. 

Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'person' -> object with constructor 'Object'
    |     property 'organization' -> object with constructor 'Array'
    --- index 0 closes the circle
    at JSON.stringify (<anonymous>)

Any suggestion how we can somehow continue using _.cloneDeep (or is there anything else that can be used)  ? Thanks in advance.

**Comment by jdalton** [comment]
Hi @mnj11!

I'm not sure what the issue is since we don't use `JSON.parse` or `JSON.stringify` within our library.

**Comment by davalapar** [comment]
Could be a bit unrelated but if looking for alternative to `JSON.parse` & `JSON.stringify` in working with objects with circular references to itself, `flatted` could be the way to go https://www.npmjs.com/package/flatted
