### ISSUE TITLE
_.findBy

### ISSUE THREAD

**Issue by ericrange** [lodash/lodash#4406]
Everytime i use "_.find" i waste 3 lines of code (due to my beautifier).
```
let lookup = _.find(hosts, {
  '_id': hostId
});
```

Maybe a "_.findBy" could solve this by:
```
let lookup = _.findBy(hosts, '_id', hostId)
```

**Comment by ericrange** [comment]
i could think of that this "specific" attribute searching is much faster than object comparisons.
and in most cases you search for an item in an array with a specific identifier. so this function could be very helpful and efficient.

**Comment by jdalton** [comment]
Hi @ericrange!

You're using shorthand syntax for a predicate function so you can do something like this instead:
```js
let lookup = _.findBy(hosts, ({_id}) => _id === hostId)
```
