### ISSUE TITLE
merge: unexpected behavior when merging objects and arrays 

### ISSUE THREAD

**Issue by kfay** [lodash/lodash#4407]
I looked through prior issues, and I'm not sure if this is a bug or expected behavior. I'm using lodash@4.17.15.

Take this example code where the destination object has a property of type array, and the source object has the same property but is an object:

```js
var first = {
    a: ['1', '2']
};
var second = {
    a: { foo: 'bar' }
};
 
_.merge(first, second);
```

In both lodash@2 and lodash@3, the result of this was an Object, `{ a: { foo: 'bar' } }`. i.e. the object completely overwrote the array.

Lodash@2/3:
<img width="1038" alt="Screen Shot 2019-08-15 at 6 08 08 PM" src="https://user-images.githubusercontent.com/1828818/63130200-acacb280-bf87-11e9-998a-d9b232ee2cfd.png">

In lodash@4, the result is an Array with a "named" property "foo":
<img width="1033" alt="Screen Shot 2019-08-15 at 6 07 19 PM" src="https://user-images.githubusercontent.com/1828818/63130168-9272d480-bf87-11e9-8a19-71cb5ec4f5d7.png">

Is this the expected behavior? Thanks!

**Comment by jdalton** [comment]
Hi @kfay!

This is by design (mentioned in the [v4 changelog](https://github.com/lodash/lodash/wiki/Changelog#v400))
> * Ensured `_.merge` merges plain-objects onto non plain-objects

The issue that introduced this change is #1413. The issue was rooted around merging plain objects into non-plain objects. I didn't think about it impacting arrays though.

**Comment by kfay** [comment]
Hi @jdalton, thanks for the quick follow up. So it sounds like it's kind of by design; the fix above was intended to impact the `new Foo()` case, but Arrays weren't specifically taken into consideration? I seem to be able to work around it with this:

```js
_.mergeWith(first, second, function (dest, source) {
    if (_.isArray(dest) && _.isObject(source)) {
        return source;
    }
});
```

However, the code base I'm updating to lodash@4 uses merge quite extensively and it's hard to know for sure all the places where we're getting impacted by this. Is this my only workaround option? Thanks!
