### ISSUE TITLE
feature request: add a memoize for async function

### ISSUE THREAD

**Issue by Jack-Works** [lodash/lodash#4408]
I have my version now

TypeScript:
```ts
import { memoize } from 'lodash-es'
export function memoizePromise<T extends (...args: Args) => PromiseLike<any>, Args extends any[]>(
    f: T,
    resolver: (...args: Args) => any = ((a: any) => a) as any,
) {
    const memorizedFunction = memoize(
        (async function(...args: Args) {
            try {
                // ? DO NOT remove "await" here
                return await f(...args)
            } catch (e) {
                memorizedFunction.cache.delete(resolver(...args))
                throw e
            }
        } as any) as T,
        resolver,
    )
    return memorizedFunction
}

```

JavaScript:
```js
import { memoize } from 'lodash-es'
export function memoizePromise(f, resolver = a => a) {
    const memorizedFunction = memoize(async function(...args) {
        try {
            // ? DO NOT remove "await" here
            return await f(...args)
        } catch (e) {
            memorizedFunction.cache.delete(resolver(...args))
            throw e
        }
    }, resolver)
    return memorizedFunction
}
```

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/63150448-67e15400-c039-11e9-946a-3331638b5588.png)

**Comment by jdalton** [comment]
Hi @Jack-Works!

For async things we like to defer to our sibling package [async](https://www.npmjs.com/package/async).

**Comment by dionyziz** [comment]
Generally, using `_.memoize` on async functions should work fine. Lodash will memoize the promise. When the promise resolves, any subsequent calls to the memoized functions will return the memoized Promise, which is now resolved, and hence will work fine. 

One issue is that, if the unmemoized function errs, the failed promise is also cached and the unmemoized function will not be invoked again. If this is not of concern to you, then the lodash version should work fine. Therefore lodash's memoize applies to many instances such as retrieving data from the database using, say, sequelize.

**Comment by vladgolubev** [comment]
Another alternative is to use https://github.com/sindresorhus/p-memoize package. It has configurable behavior in case a promise rejects (`cachePromiseRejection` parameter).

**Comment by SwiftWinds** [comment]
> Another alternative is to use https://github.com/sindresorhus/p-memoize package. It has configurable behavior in case a promise rejects (`cachePromiseRejection` parameter).

This was super helpful! I also found the example with the timed cache to be super helpful. Good alternative to using `throttle` which didn't quite seem to work for me with async
