### ISSUE TITLE
Should create return an empty object for primitive prototype?

### ISSUE THREAD

**Issue by blikblum** [lodash/lodash#4414]
I'm trying to enable `create` tests and the test that checks for [primitive prototypes](https://github.com/lodash/lodash/blob/master/test/create.js#L67) is failing.

The old implementation [returns an empty object](https://github.com/lodash/lodash/blob/4.17.15-npm/_baseCreate.js#L17) in such cases.

The new (in master) implementation returns e.g. `Number {}` for a 0 prototype or `String {}` for ''

Should the new implementation restore the old behavior?

**Comment by jdalton** [comment]
Hi @blikblum!

We'll go with the new behavior of coercing the primitive to an object.
