### ISSUE TITLE
Wildcard / Glob iterator [Feature discussion]

### ISSUE THREAD

**Issue by jwilson8767** [lodash/lodash#4421]
Hello,
I have a utility (that is currently implemented in Python but is easily implemented in JS) which allows for applying / mapping a function over a dot-notation path with wildcards (such as `some_obj.*.some_array.*`) which was originally based upon some of the Lodash patterns of soft-failure. Specifically, it doesn't care if the wildcards are iterating over an array or an object, and a missing key or level doesn't cause any kind of failure. 

One of the best example uses is for quickly finding and modifying everything at a specific level of a deeply nested structure:
```javascript
function wrap_parens(obj){
  return '('+obj+')'
}

my_massively_nested_object = {
  'foo': {
     'items': [
    {'label': 'bar'},
    {'label': 'barr'},
    // ...
  ]}
  'foo2':  {
    'items': [
    {'label': '2bar'},
    {'label': '2barr'},
    // ...
  ]}
};

glob_apply(my_massively_nested_object, '*.items.*.label', wrap_parens);  // obj, path, func

console.log(my_massively_nested_object );
/* {
  'foo': {
     'items': [
    {'label': '(bar)'},
    {'label': '(barr)'},
    // ...
  ]}
  'foo2':  {
    'items': [
    {'label': '(2bar)'},
    {'label': '(2barr)'},
    // ...
  ]}
};
*/
```

I could also imagine having a `glob_get` function which just returns an array of the values that were found.

Note that at present this only supports a single wildcard per level. I could envision a globstar `**` being implemented, but I think it would be significantly more complex to utilize safely.

Would this feature be welcome in Lodash if I were to re-implement it in JS and submit a PR?

Thanks

**Comment by jdalton** [comment]
Hi @jwilson8767!

I could see a specialized library created for just this kind of iteration. I think it would be a better fit as it's own library.
