### ISSUE TITLE
Need to fix these dependencies

### ISSUE THREAD

**Issue by sanjowinson** [lodash/lodash#4424]
How I can Fix this vulnerabilities after npm install. I tried versioning and made changes in dependencies. Can someone please guide me on this because I am new on this and having facing this issue from last one week

             === npm audit security report ===                        
┌──────────────────────────────────────────────────────────────────────────────┐
│ Manual Review │
│ Some vulnerabilities require your attention to resolve │
│ │
│ Visit https://go.npm.me/audit-guide for additional guidance │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low │ Prototype Pollution │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package │ lodash │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in │ >=4.17.5 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grunt-usemin [dev] │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path │ grunt-usemin > lodash │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info │ https://npmjs.com/advisories/577 │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High │ Prototype Pollution │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package │ lodash │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in │ >=4.17.11 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grunt-usemin [dev] │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path │ grunt-usemin > lodash │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info │ https://npmjs.com/advisories/782 │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High │ Prototype Pollution │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package │ lodash │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in │ >=4.17.12 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grunt-usemin [dev] │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path │ grunt-usemin > lodash │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info │ https://npmjs.com/advisories/1065 │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low │ Regular Expression Denial of Service │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package │ clean-css │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in │ >=4.1.11 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grunt-angular-templates [dev] │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path │ grunt-angular-templates > html-minifier > clean-css │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info │ https://npmjs.com/advisories/785 │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 4 vulnerabilities (2 low, 2 high) in 1448 scanned packages
4 vulnerabilities require manual review. See the full report for details.

**Comment by sanjowinson** [comment]
And am using the latest version 12 for node and using ubuntu 18.04 bionic. Please help me on this

**Comment by falsyvalues** [comment]
Hi @sanjowinson!

You have to report that to the owners of these dependencies, because they are using vulnerable version of lodash. All known issues were resolved in recent lodash versions. Please take a look on our [changelog](https://github.com/lodash/lodash/wiki/Changelog).

**Comment by sanjowinson** [comment]
Thanks
