### ISSUE TITLE
pipeline utility function proposal (for those who don't want to choose between the 3 pipeline operator proposals)

### ISSUE THREAD

**Issue by jedwards1211** [lodash/lodash#4425]
I'm excited about the pipeline operator proposal, but my boss and I agreed we'd rather not start using it since there are 3 competing implementations...

Using `flow` is a pretty suitable alternative, but awkward in that the input value comes last:
```js
flow(
  compact,
  map(x => x * 2)
)([1, 2, null, 3])
// [2, 4, 6]
```
With this simple declaration, we can get the same ordering as the pipeline operator:

```js
const pipeline = (value, ...fns) => flow(...fns)(value)

pipeline(
  [1, 2, null, 3],
  compact,
  map(x => x * 2)
)
// [2, 4, 6]
```

Do you think this `pipeline` function is worthy of being part of Lodash?  Would be nice not to have to define it separately in each of our project.

There doesn't seem to be an easily-discoverable package exporting this function on npm...

**Comment by jdalton** [comment]
Hi @jedwards1211!

I'm in favor of adopting whatever the language feature is instead of making an alternative. The alternative could be a Babel transform for the syntax.

**Comment by jedwards1211** [comment]
Yes there are 3 different babel transforms available, because there was no widespread agreement on which to standardize.  But my boss and I hesitate to pick one since we don't know which is the most futureproof, and prefer to use a function like this instead.  We can easily keep this `pipeline` function in userland, I just thought it might be useful to have in here.
But I was forgetting, there are complexities about whether this function would support async chains or not, so it probably belongs in a separate package anyway.
