### ISSUE TITLE
cloneWith unexpected behaviour

### ISSUE THREAD

**Issue by felixhayashi** [lodash/lodash#4426]
https://lodash.com/docs/4.17.15#cloneWith

> This method is like _.clone except that it accepts **customizer which is invoked to produce the cloned value.**

```
_.cloneWith({ foo: 3, bar: 4 }, () => 'value')
```

returns

```
'value'
```

expected

```
{ foo: 'value', bar: 'value' }
```

or am I misunderstanding `cloneWith`?

**Comment by jdalton** [comment]
Hi @felixhayashi!

The first call to the `customizer` will be the full object value so you can customize the entire clone if you wish.

**Comment by felixhayashi** [comment]
Many thanks @jdalton, I misunderstood the docs and thought that `cloneWith` gives me the opportunity to customize each property's value, not the entire clone :) 

had a closer look and `_.mapValues` is actually what I need.
Thanks for your great tool.
