### ISSUE TITLE
discourage people from using per-method packages on website?

### ISSUE THREAD

**Issue by jedwards1211** [lodash/lodash#4427]
As far as I understand in #3838, there aren't really any great reasons to use per-method packages.  I've still seen a number of libs in the wild that use them, thinking it will reduce their dependency footprint.  They don't realize it will ultimately end up bloating dependencies and webpack bundles since the per-method packages can't share as much code with other libs that depend on lodash methods.

I propose we make the `per-method packages` link on the webpage go to a warning page that explains why people should stop using the per-method packages, before showing them the link to all the per-method packages on npm.

**Comment by jdalton** [comment]
Hi @jedwards1211!

I'm up for that. Would you mind creating a PR on the [lodash/lodash.com](https://github.com/lodash/lodash.com) repo.

**Comment by jedwards1211** [comment]
yup will do
