### ISSUE TITLE
lodash/fp/transform for objects

### ISSUE THREAD

**Issue by knobo** [lodash/lodash#4434]
transform does not reuse the object from the iteratee.

``` javascript
let _transform = _.transform.convert({ 
  'cap': false,
});
_transform( 
  (o, value, key) => _.set(key, value, o),
  { initial: "value" }, 
  { "my.new.values": 42 }
)
// => {initial:"value"}
```

That would be a bug, right?

This works though.
``` javascript
let _transform = _.transform.convert({ 
  'cap': false,
});

let _update = _.set.convert({immutable: false});

_transform( 
  (o, value, key) => _update(key, value, o),
  { initial: "value" }, 
  { "my.new.values": 42 }
)
// => 
{
  "initial": "value",
  "my": {
    "new": {
      "values": 42
    }
  }
}
```

**Comment by jdalton** [comment]
I think `transform` is generally mucked up in FP :p
I'm open for a PR to patch it into a usable state.

**Comment by cukejianya** [comment]
@jdalton has anyone taken this issue? If not, I would like to take it.

**Comment by jdalton** [comment]
Go for it @cukejianya!

**Comment by cukejianya** [comment]
Upon investigation, it looks like, yes, the transform function itself does not mutate the object, but the iteratee function is suppose to if to have any effect on the returned accumulator. The transform function then returns the reference of the passed in accumulator. Thus, why in the first example the transform function returns the original object unchanged since _.set in the iteratee function does not mutate the object, but returns a new object. 

Example:

```
Let arr = [100, 110];

_.transform(function(result, n) {
  result.push(n *= n);  // results
  return n % 2 == 0; // If false, it stops the iteration.
}, arr, [2, 3, 4,]);
// => [100, 110, 4, 9]

console.log(arr); // [100, 110, 4, 9]
```
To answer the reason why the _.transform function is capped at 2 is (just a guess) probably due to handling cases where it is arrays and not objects being iterated over. 

Not sure if there was a particular thing you wanted to change about` _.lodash`? As far as I can tell, there's no true bug and everything is working as intended. @jdalton

**Comment by knobo** [comment]
I would expect transform to ues the return value from the transformer function in the next call, not the initial object.

**Comment by robinpokorny** [comment]
@cukejianya, requiring mutation in the code written in lodash/fp is generally a no-no. The `transform` needs to be changed for the FP case in a more substantial matter.

Also, `transform` is meant to be used on general objects, so its use with arrays is an edge case.

**Comment by cukejianya** [comment]
@knobo I thought the same, but `lo.reduce` already has that functionality. Thus why transform behaves slightly different. Like mentioned before, the returned value in the transform's iteratee is only used as a boolean to check if the transform function should continue iterating over the initial object/array. 

Using lo.reduce (I haven't checked this yet, but it should work):
```
let _reduce = _.reduce.convert({ 
  'cap': false,
});

_reduce( 
  (o, value, key) => _.set(key, value, o),
  { initial: "value" }, 
  { "my.new.values": 42 }
)

// => 
// {
//   "initial": "value",
//   "my": {
//      "new": {
//         "values": 42
//       }
//    }
//}
```

**Comment by cukejianya** [comment]
@robinpokorny I agree. But I'm not sure if we should change the functionality of transform in just FP and not in regular lodash. Or maybe just removing transform from the list of FP functions.  Not sure what the right solution would be for this.

**Comment by falsyvalues** [comment]
> Upon investigation, it looks like, yes, the transform function itself does not mutate the object, but the iteratee function is suppose to if to have any effect on the returned accumulator. The transform function then returns the reference of the passed in accumulator. Thus, why in the first example the transform function returns the original object unchanged since _.set in the iteratee function does not mutate the object, but returns a new object.
> 
> Example:
> 
> ```
> Let arr = [100, 110];
> 
> _.transform(function(result, n) {
>   result.push(n *= n);  // results
>   return n % 2 == 0; // If false, it stops the iteration.
> }, arr, [2, 3, 4,]);
> // => [100, 110, 4, 9]
> 
> console.log(arr); // [100, 110, 4, 9]
> ```
> 
> To answer the reason why the _.transform function is capped at 2 is (just a guess) probably due to handling cases where it is arrays and not objects being iterated over.
> 
> Not sure if there was a particular thing you wanted to change about` _.transform`? As far as I can tell, there's no true bug and everything is working as intended. @jdalton

@cukejianya Its because of `arrayEach` and `baseForOwn` used under the hood. For both of them iteratee functions may exit iteration early by explicitly returning `false` which is happening here.

**Comment by cukejianya** [comment]
@falsyvalues Are you saying that that's a bug? I thought that was the intended functionality?

**Comment by knobo** [comment]
`map` and `transform` are different. `map` returns an array, `transform` can return an object.
When we do functional programming, the initial object should not be modified. So you *must* reuse the return value from the `transformer`

**Comment by cukejianya** [comment]
@knobo Not sure if we're on the same page.`lodash.map` will not satisfy your use case. However, `lodash.reduce` does and it returns an object as well as can iterate over an object (or array) without mutating it. Check out the docs: https://lodash.com/docs/4.17.15#reduce

So you can use `lodash.reduce` in replace of `lodash.transform`.

**Comment by knobo** [comment]
Ah.. yes, I see now. _.reduce does what I want.

**Comment by knobo** [comment]
No it does not. Reduce does not give me the keys, only values.
