### ISSUE TITLE
do "npm run test:wip" report error

### ISSUE THREAD

**Issue by lzf1201** [lodash/lodash#4435]
![image](https://user-images.githubusercontent.com/9412696/63582012-d50d6000-c5ca-11e9-9e76-6e42426b8c19.png)

  308 passing (10s)
  2 failing

  1) merge
       should treat sparse array sources as dense:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\merge.test.js:125:30)
      at process.topLevelDomainCallback (domain.js:121:23)

  2) words
       should prevent ReDoS:

      AssertionError [ERR_ASSERTION]: operation took 6507ms
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\words.test.js:115:30)
      at process.topLevelDomainCallback (domain.js:121:23)

**Comment by falsyvalues** [comment]
Hi @lzf1201!
Since master branch is in [WIP](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#construction-notice-construction) state some tests may fail.
