### ISSUE TITLE
Add possibility to use function as a _.fill value parameter

### ISSUE THREAD

**Issue by ars-java** [lodash/lodash#4437]
Add possibility to use generator function as a value parameter in  `_.fill(array, value, [start=0], [end=array.length])` method.

Examples:
```
_.fill(Array(3), () => _.random(5));
=> [1, 4, 2]
```

```
let b = 0;
_.fill(Array(5), () => {  b+=2; return b; });
=> [2, 4, 6, 8, 10]
```

```
_.fill(Array(7), (array, currentIndex) => {  
    if (index == 0 || index == 1) return 1

    // Indexes < currentIndex have been filled yet
    return array[index - 2] + array[index - 1]
 });
=> [1, 1, 2, 3, 5, 8, 13]
```

**Comment by falsyvalues** [comment]
@blikblum It doesn't mean that we cannot change that. Actually I think that could nice extension for native `fill().

**Comment by ars-java** [comment]
@falsyvalues Will you accept my pull request if I revert fill deletion and implement this functionality?

**Comment by falsyvalues** [comment]
Hi @ars-java!
We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) thats our flow.
