### ISSUE TITLE
[FEATURE REQUEST] _.cascade(...Array<Objects>, 'commonKey')

### ISSUE THREAD

**Issue by duydnguyen07** [lodash/lodash#4439]
I'm not sure if lodash already has a function to cascade objects together based on a common key, like the example below. If not, is it something that can be added? I can also create a PR for this as well if the feature request is considered.

```
let leftArr = [
  {
    "a": "123",
    "b": "ABC"
  },
  {
    "a": "124",
    "b": "ABCD"
  },
  {
    "a": "125",
    "b": "ABCF"
  }
]
let rightArr = [
  {
    "a": "123",
    "b": "NEW_VALUE"
  },
  {
    "a": "127",
    "b": "ABCX"
  },
  {
    "a": "129",
    "b": "ABCL"
  }
]

let result = _.cascade(leftArr, rightArr, 'a')
/* 
result = [
  {
    "a": "123",
    "b": "NEW_VALUE"
  },
  {
    "a": "124",
    "b": "ABCD"
  },
  {
    "a": "125",
    "b": "ABCF"
  },
  {
    "a": "127",
    "b": "ABCX"
  },
  {
    "a": "129",
    "b": "ABCL"
  }
]
*/
```
* Notice that object with same key/value "a":"123" is merged and all new objects are append to the leftArr.

**Comment by jdalton** [comment]
Thanks @duydnguyen07!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
