### ISSUE TITLE
Behavior of flow methods on master branch (v5)

### ISSUE THREAD

**Issue by blikblum** [lodash/lodash#4443]
I've fixed most of flow methods bugs in a local repository

Two tests are not passing:

 - Returning a [identity function when no function is passed](https://github.com/lodash/lodash/blob/master/test/flow-methods.js#L31)
 - Support for [shortcut fusion](https://github.com/lodash/lodash/blob/master/test/flow-methods.js#L54)

These two features should be kept in master?

**Comment by jdalton** [comment]
> These two features should be kept in master?

No. You can go ahead and remove those tests.
