### ISSUE TITLE
_.debounce stops error propagation for async functions

### ISSUE THREAD

**Issue by edudley** [lodash/lodash#4449]
When wrapping an `async/await` function with debounce, errors are not propagated to the calling function.

Expected behavior: The error is logged twice to the console.
```
1 test
2 test
```
Actual behavior: The error is only logged in the debounced function, and the thrown error is outputted to the console as `Uncaught (in promise)`.
```
1 test
Uncaught (in promise)..... test
```
```js

const caller = async () => {
   try {
     const response = await callee();
   } 
   catch(error) {
     console.log('2', error);
   }
}

const callee = _.debounce(async () => {
   try {
     await someAsyncFunction();
     throw new Error('test');
   }
   catch(error) {
      console.log('1', error);
      throw error;
   }
}, 1000);
```

**Comment by squidjam** [comment]
Wait a second... 

> I'm not sure why that's happening. We are not try-catching anything in the `debounce` method.

and then it's closed without further investigation or reasoning? 

Am I missing something?

**Comment by jdalton** [comment]
There's nothing actionable on our end. However, feel free to investigate and please do report your findings.

**Comment by linonetwo** [comment]
I'm also getting `at processTicksAndRejections (node:internal/process/task_queues:94:5)`

Error is catched by nodejs itself?

**Comment by immdevrov** [comment]
This error messing with me all the time. It is happening exactly how it is described in issue.

**Comment by hekatx** [comment]
For anyone trying to make this work, refer to this thread: https://github.com/lodash/lodash/issues/4815#issuecomment-1006573679
