### ISSUE TITLE
Proposal: include ES module output via `.mjs` for `lodash` package 

### ISSUE THREAD

**Issue by JounQin** [lodash/lodash#4455]
It is really bad to let library author or end user to choose between `lodash` and `lodash-es`, why not just `lodash` package but with built-in ESM support.

**Comment by jdalton** [comment]
Hi @JounQin!

I want to avoid adding any more weight to the primary `lodash` package. In `lodash` v5 it will be 💯 ESM but using the `.js` extension, relying on either a loader or whatever Node options enable it to be so.

**Comment by JounQin** [comment]
It seems v5 is a breaking change for commonjs packages?

**Comment by OliverJAsh** [comment]
:+1: to this. We're having to install both `lodash` (used on server, by Node) and `lodash-es` (used on client) whilst manually ensuring the versions are kept in sync. It would be great to have one package which delegates to CommonJS or ES Modules using `package.json` fields `main` and `module` (respectively)—this is [how other libraries are currently doing it](https://unpkg.com/browse/funfix-core@7.0.1/package.json).

**Comment by jdalton** [comment]
I won't have to ship multiple copies with something like [`esm`](https://github.com/standard-things/esm). I can just ship ES modules.

**Comment by JounQin** [comment]
I love ES Module personally and am using it everywhere as possible, but is that great for lib authors which will enforce them adding a building step before publishing?

Of course, it is a great decision which will push ES Module going ahead.
