### ISSUE TITLE
_.defaultToAny is undefined

### ISSUE THREAD

**Issue by elias6** [lodash/lodash#4456]
Does anyone know what is happening with `_.defaultToAny`? I have been wishing for it for a long time. I see the PR (#3615) and it was merged into master. But I don't see it in the latest version of lodash (4.17.15). If I open my browser console on https://lodash.com/ and type `_.defaultToAny`, I get `undefined`.

What is happening with it? Is it going to be available in a future version of lodash?

**Comment by falsyvalues** [comment]
Hi @elias6!
`_.defaultToAny` will be part of next major release.
