### ISSUE TITLE
Did/Does lodash secretly have dependencies?

### ISSUE THREAD

**Issue by MareoRaft** [lodash/lodash#4457]
It is my understanding that lodash has 0 dependencies.

But I am wondering if other libraries are/were "secretly" rolled in at some point.

The reason I am wondering this is because we are using an old `lodash` bower component in a project.  lodash is installed in `node_modules/@bower_components/lodash`.  That folder contains a file called `yarn.lock` (and also `package-lock.json`).  Inside the file, certain dependency information is listed.  For example:

    deep-extend@~0.4.0:
      version "0.4.1"
      resolved "https://registry.yarnpkg.com/deep-extend/-/deep-extend-0.4.1.tgz#efe4113d08085f4e6f9687759810f807469e2253"

Does this mean that lodash depends on deep-extend?  Or perhaps it means just the opposite, that deep-extend depends on lodash.

Thanks in advance for clarifying what this information really means.

**Comment by jdalton** [comment]
Hi @MareoRaft!

I'm not sure about the lock file, but neither Lodash or deep-extend seem to have dependencies.

**Comment by MareoRaft** [comment]
thank you
