### ISSUE TITLE
Add `_.getWith`

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash#4458]
It seems like a `getWith` method missing which would have partity with `setWith`. It would function a lot like `update`, except that it returns the value instead of the whole object:

```js
let obj = {
  a: 1,
  b: 5
}

_.update(obj, 'a', x => x * 2) // { a: 2, b: 5 }
getWith(obj, 'a', x => x * 2) // 2
```

We're considering adding this to [`futil`](https://github.com/smartprocure/futil-js) in the mean-time (where it would have the curried fp API of `b, c, a` arg order so it'd be `getWith(path, customizer, object)`).

**Comment by daedalus28** [comment]
I did find that this was previously brought up in #2168 which was closed saying it can be done with`_.result`, but the lodash/fp version is capped to 2 arguments so that doesn't work here.

Another alternative would be resultWith or resultOr for the fp version, but that definitely feels a bit obtuse.

**Comment by daedalus28** [comment]
Also, for reference, this is the implementation that would head to futil (curried + rearged) if this doesn't land in lodash:

```js
let getWith = _.curry((path, customizer, object) => customizer(_.get(path, object)))
```

**Comment by michsa** [comment]
Slight correction on the futil implementation - it seems fp `setWith` has a custom argument order of `d, c, b, a` (or `customizer, path, value, object`), so for parity, the API would be `getWith(customizer, path, object)`.

As for `_.result`, I don't believe it actually addresses the use case for `getWith`. `result` only executes the value at the given path - there's no way to pass it a function that *acts on* that value, so it's unable to transform arbitrary values post-`get`.

Here's a runkit to illustrate: https://runkit.com/michsa/getwith-vs-result

**Comment by sharmaaditya570191** [comment]
Hey @daedalus28  and @jdalton I have made a PR regarding this. Please have a look.

**Comment by jdalton** [comment]
In this case there really isn't parity as the behavior of `setWith` is to control the creation of incomplete object properties as it walks the path and the `getWith` variant presented here is just a map over the return value of `get`. I think I'll hold off on this for now.

**Comment by daedalus28** [comment]
Ok - and thank you for your time analyzing the request 🤗 

I think there's still a use case for it (for example, we use internally in the implementation of `F.expandObjectBy`), so in the meantime, it is available in [`futil`](https://github.com/smartprocure/futil-js). We will happily deprecate when/if you decide to add it to lodash itself.
