### ISSUE TITLE
uniqWith documentation

### ISSUE THREAD

**Issue by Supacoco** [lodash/lodash#4460]
I stumbled upon a little mistake in [`uniqWith`](https://lodash.com/docs/4.17.15#uniqWith) documentation.

Arguments of uniqWith are `array, [comparator]`. Typescript yelled at me for a few minutes before I tried just to switch to `comparatorFunction, array`.

If I made a mistake sorry for the noise.

Have a good day!

**Comment by falsyvalues** [comment]
Hi @Supacoco!
I'm not sure If I get your question. Bracket notation is used for [optional params ](https://jsdoc.app/tags-param.html#optional-parameters-and-default-values). Regarding TypeScript we don't support typings for Lodash.

**Comment by Supacoco** [comment]
Sorry for the lack of clarity and the useless noise. I found my mistake. I was using the `fp` version of `uniqWith` .
