### ISSUE TITLE
CloneDeep: TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by emahuni** [lodash/lodash#4461]
see [CodeSandbox](https://codesandbox.io/s/vue-template-14s28) in `mounted` hook in `App.vue` file - there is `cloneDeep` statement where I reproduced this.

I am not sure why this is the case, but i think this is related to this [Stackoverflow - why cannot convert a Symbol value to a string](https://stackoverflow.com/questions/44425974/why-cannot-convert-a-symbol-value-to-a-string) question.

There is an answer there that I suppose might end this bug.

This is happening too often such that a fix is required cause there are some operations that cannot be done without this. I often do other undesired workarounds that completely change logic.

**Comment by jdalton** [comment]
Hi @emahuni!

If I remove `cloneDeep` and try to just `console.dir()` the value I get the same error so 🤷‍♂

**Comment by antimonyGu** [comment]
I have the similar problem too. My vue version is @2.5.2. When I tried to deepClone a VM instance in the Vue, I got the same error message. But when I try to use JSON.parse(JSON.stringify()) instead of  _.deepClone I don't have the same problem. Can anybody help me?

**Comment by antimonyGu** [comment]
Forgot to say, my lodash version is @4.17.11.

**Comment by emahuni** [comment]
> Hi @emahuni!
> 
> If I remove `cloneDeep` and try to just `console.dir()` the value I get the same error so 🤷‍♂

Isn't the whole idea solving problems that are happening rather than ignore them because they were not solved by others?
