### ISSUE TITLE
lodash 2 clone(x, true) works, lodash 4 cloneDeep does not

### ISSUE THREAD

**Issue by MareoRaft** [lodash/lodash#4466]
We have a project which must run in RhinoJS.  We were previously using lodash version 2 and had the following code

    var copyIdentityData = _.clone(eventData.identity, true)

which worked perfectly.  After switching to lodash 4.17.15, both `_.clone` and `_.cloneDeep` returned an empty object instead of a copy of our object.

code:

    logger.warn("eventData.identity: " + JSON.stringify(eventData.identity))
    var copyIdentityData = _.cloneDeep(eventData.identity)
    logger.warn("copyIdentityData: " + JSON.stringify(copyIdentityData))

output:

    WARNING: eventData.identity: {"0":{"riskLevel":0,"comments":null,"field":"firstName","displayName":"First Name","certifiable":0,"fieldValue":"Sharon","outcome":null},"1":{"riskLevel":0,"comments":null,"field":"email","displayName":"Email Address","certifiable":0,"fieldValue":"sswanson@hcmlabs.net","outcome":null}}
    WARNING: copyIdentityData: {}

**Comment by jdalton** [comment]
Hi @MareoRaft!

Lodash v4 no longer supports RhinoJS.

**Comment by MareoRaft** [comment]
Thanks for letting me know.  What is the latest version of lodash that *does* support RhinoJS?
