### ISSUE TITLE
can maxBy iterate thru object, not only thru array ?

### ISSUE THREAD

**Issue by theGABS** [lodash/lodash#4468]
Currently, in the documentation I see `_.maxBy(array, [iteratee=_.identity])` 

I am wondering, why I cannot use it with an object?

**Comment by jdalton** [comment]
Hi @theGABS!

Yes it's just arrays. This is because math methods tend to want to average, sum, or perform some other cumulative calculation on a list of numbers. I don't want to increase the scope of the method for more kinds of iterating.
