### ISSUE TITLE
[Enhancement] IsNotUndefined / isDefined

### ISSUE THREAD

**Issue by MarcinAman** [lodash/lodash#4470]
Hi, 
it would be nice to have a `_.isNotUndefined`. In multiple places in our codebase we use `!_.isUndefined` which is not the most readable piece of code.

A simple alias will do, since that I'd simply like to have a negation of current implementation

**Comment by jdalton** [comment]
Hi @MarcinAman!

You can replace `_.isUndefined()` use with `value === void 0` or `value !== void 0`.
