### ISSUE TITLE
Throttle is delaying leading invocation after trailing invocation of previous throttle window

### ISSUE THREAD

**Issue by wanasim** [lodash/lodash#4471]
I'm not sure if my understanding of throttle is correct, but it seems like there is a delay in the leading invocation between throttle 'windows'. 

Using the example below, if a user is consistently clicking on a webpage every second for 10 minutes, there should be 4 logs of "user clicked" - two for the initial throttle window (one leading at the first second and one trailing at the 5 minute mark) and two for the second throttle window (one leading at 5.1 minutes and one trailing at the 10-min mark). 

However, the second leading invocation is skipped....if I wait approximately 1 minute and 20 seconds after the previous trailing invocation, the leading invocation occurs. In fact, it seems like this "time gap" in the leading invocation between throttle windows is roughly 20% of the wait time..?? I'm completely perplexed by this 😆
```
// **Throttle every 5-minutes
const throttledFunc = throttle(function{console.log("user clicked")}, 300000, {
  trailing: true,
  leading: true
});

document.addEventListener("click", throttledFunc);
```
**Expected**:
![image](https://user-images.githubusercontent.com/24991734/64996432-f0a71600-d8ab-11e9-8474-4b3bc567383c.png)

**Actual**:
![image](https://user-images.githubusercontent.com/24991734/64996443-f7ce2400-d8ab-11e9-9043-10f6587a9f3c.png)

**Comment by jdalton** [comment]
Hi @wanasim!

I don't have the bandwidth to debug a 10 minute test case. You might check out [this post](https://css-tricks.com/debouncing-throttling-explained-examples/) by David Corbacho, who helped fix several issues with debounce/throttle.

**Comment by wanasim** [comment]
@jdalton you can try reducing the wait time to 10 seconds in which case the delay is about 2 seconds between the trailing and leading invocation. Again I've noticed the delay is roughly ~20% of the wait time.
