### ISSUE TITLE
curried fp/getOr with an array allows for mutating values

### ISSUE THREAD

**Issue by mattschoch** [lodash/lodash#4472]
**Issue**
When partially applying the `getOr` method with the default value as an array, the reference is retained, and therefore its contents can be altered.

Here's a failing test to demonstrate the issue.

```
  QUnit.module('fp.getOr');

  (function () {
    QUnit.test('should not retain reference to defaultValue when curried', function (assert) {
      assert.expect(1);
      // Partially apply getOr with an empty array, because that's a commonly used default value.
      var getOrEmpty = fp.getOr([]);

      // Get the value, OR give me my empty array.
      var empty = getOrEmpty('path', {});

      // Add some stuff to that empty array.
      empty.push('value that should not be retained');

      // Let's do this again.
      var actual = getOrEmpty('path')({});

      // Wait...I didn't get an empty array?
      assert.deepEqual(actual, []);
    });
  }());
```

**Comment by robinpokorny** [comment]
Yeah, so this is tough. I see what you want to achieve and I understand that it would be useful. I also know it can be confusing if you expect it. Also, as you correctly pointed out, this only shows when currying is in place.

However, strictly speaking, **this is the correct behaviour**. The value you pass as default is always returned when the property is missing. I'd say the problem occurs when a mutation is made–a common thing when mixing pure and non-pure.

**Note:** The same is true for:
* `_.set` & `_.setWith`
* `_.constant`
* `_.defaultTo`
* `_.partial` & `_.partialRight`
* `_.bind` & `_.bindKey`

And possibly others.

---

To achieve what you want, it is needed the empty array gets created again with each run, therefore we need to wrap it in a function:

```js
const getOrEmpty = (...args) => _.getOr([], ...args)
```

This will work as you wish and preserve the currying of the second and third argument.

---

It might be worth exploring if there is interest for a family of functions like:

### `_.getOrInvoke(object, path, defaultFn)`
In FP as `fp.getOrInvoke(defaultFn, path, object)`

Usage:

``` 
const object = { 'a': [{ 'b': { 'c': 3 } }] };

_.getOrInvoke(object, 'a.d', () => []);
// => []
```

What do you think?

**Comment by mattschoch** [comment]
Yeah, that's kinda where I was at - it's technically expected and correct behavior, and once I understood what was happening it totally makes sense.
So it's definitely not a true lodash issue, but since it's a pretty opaque scenario that causes a really obscure bug, I was questioning if there's _something_ that can be done to prevent the accidental misuse. And if it's even the job of lodash to prevent me from using my arrays wrong.

A `_.getOrInvoke` method could be interesting as a way to handle this. Not sure it would've prevented me from using `_.getOr` improperly since I didn't _think_ I was using it improperly, but it would provide a cleaner, documented solution to the scenario. Although then it's totally possible to pass a `defaultFn` that has side effects, leading to a different class of potential misuse.

I'll close this issue since it's not actually an issue with the code. Could even be worth just noting in the FP docs that the `defaultValue` is not immutable.
