### ISSUE TITLE
_.isEqual(NaN, NaN) returns true

### ISSUE THREAD

**Issue by sharmaaditya570191** [lodash/lodash#4473]
In JavaScript, NaN has the distinction of being the only value that is not equal to itself. We can add this functionality to isEqual function by using ES6 Number.isNaN function to check if the parameters are NaN or not.

**Comment by jdalton** [comment]
Hi @sharmaaditya570191!

This is by design.

**Comment by sharmaaditya570191** [comment]
Sorry @jdalton I could not catch your point. Could you please elaborate? Is the stated behaviour treated as a bug. _.isEqual(NaN, NaN) should return false I guess. Also please have a look at my previous PR adding filler option to chunk.Thanks!

**Comment by jdalton** [comment]
In the case of our method `isEqual(NaN,NaN)` returns `true` by design. You can customize this with [_.isEqualWith](https://lodash.com/docs/#isEqualWith).
