### ISSUE TITLE
The func is not invoked when debounce's option trailing is false

### ISSUE THREAD

**Issue by zhangyaoFkr** [lodash/lodash#4475]
like below:
```
_.debounce(
    function() {
      // can not get here
    },
    4000,
    { trailing: false }
)
```

**Comment by zhangyaoFkr** [comment]
I've read the function debounce and found that function cound not work when option leading and trailing are both false. Is it designed like this? It will work as expected in any of them is true.

**Comment by jdalton** [comment]
Hi @zhangyaoFkr!

Yes, when `trailing` is `false` and `leading` is not set defaults to `false`.
So `leading` and `trailing` is `false`.

**Comment by zhangyaoFkr** [comment]
Thanks a lot! @jdalton
