### ISSUE TITLE
Will prevent assign new key with value 0 to Object

### ISSUE THREAD

**Issue by lxjerry** [lodash/lodash#4477]
e.g.  will prevent assign  { girlfriend: 0 } to { age: 10, sex: 'male' }

https://github.com/lodash/lodash/blob/29eb5713f58bad015ccf0a74da741b8c7184dd2f/.internal/assignValue.js#L18

    if (!hasOwnProperty.call(object, key)) {
        baseAssignValue(object, key, value);
    } else if (!eq(objValue, value)) {
        if (value !== 0 || (1 / value) == (1 / objValue)) {
            baseAssignValue(object, key, value);
        }
    } else if (value === undefined && !(key in object)) {
        baseAssignValue(object, key, value);
    }

**Comment by jdalton** [comment]
Hi @lxjerry!

I'm not really following but the current behavior is by design.

**Comment by lxjerry** [comment]
@jdalton I mean with the master code:

![image](https://user-images.githubusercontent.com/4982490/65568997-61c28980-df8e-11e9-8c36-b396bf4fe078.png)

it caused by the (-0/+0) compare logic (append in master code/not in 4.17.15)：
(value !== 0 || (1 / value) == (1 / objValue))

**Comment by jdalton** [comment]
Ah, I cannot repro this in the released version. If you'd like to patch master with a PR that would be fantastic!
