### ISSUE TITLE
'get' function is accepting wrong paths when an extra right square bracket is added

### ISSUE THREAD

**Issue by AndresCardonaDev** [lodash/lodash#4483]
I just got to this scenario by accident after a cat stepped into the keyboard :D

```
_.get({a:{b:{c:'Spanish Inquisition'}}}, 'a[]].b')
```

This returns
`{c:'Spanish Inquisition'}`

**Comment by jdalton** [comment]
Hi @AndresCardonaDev!

Our parser is a little forgiving when it comes to malformed paths. Rather than throw an error we try to complete the path. In this case `[]]` is seen as garbage and ignored.

**Comment by AndresCardonaDev** [comment]
@jdalton Saw the code, got that idea somehow, but wouldn't this diminish the role of the defaultValue parameter,
A line of code like the following is telling me that i shouldn't worry i can rely in the default value if something doesn't make sense, in my case someone entered `]` by accident, that wouldn't happen with any other param and is where i find that doesn't look consistent. In conclusion, one can't rely in this code then
```js
_.get({a:{b:{c:'Spanish Inquisition'}}}, `a[${x}][${y}]`, 'No worries')
```

for example if we try then with another 'valid' garbage
`_.get({a:{b:{c:'Spanish Inquisition'}}}, 'a...', 'No worries')`It will return undefined, which is more clear to be expected

Therefore its a pretty selective garbage allowance system :D, brackets are fine, wait a minute are you a dot!

Just though in something simple to keep things coherent won't you agree?
```js
function _toOnlyBrackets(path)  {
  return path.replace(/[^\[\]]/g, '')
}
function _areBracketsBalanced(onlyBracketsPath){
  if (onlyBracketsPath.length === 0) {
    return true;
  }
  if (onlyBracketsPath.length % 2 === 1){
    return false;
  }
  if (onlyBracketsPath[0] === "]") {
    return false
  }
  let stack = _.reduce(onlyBracketsPath, (stack, bracket) => {
    bracket === ']' ? stack.pop() : stack.push(bracket)
    return stack
  }, []);
  return _.isEmpty(stack)
}

if (!_areBracketsBalanced(_toOnlyBrackets(path)) {
 return undefined
}
```
