### ISSUE TITLE
Documentation for functions supporting iteratee shorthand seems incorrect

### ISSUE THREAD

**Issue by bradlys** [lodash/lodash#4485]
Background: I've been trying to do some cleanup on our codebase and the inspection tool started telling me a variety of lodash functions were being used incorrectly.

Things like:  `_.uniqBy(someArray, 'someKey')` was incorrectly being used because 'someKey' isn't a function. The JSDoc for _.uniqBy that I have currently:
```javascript
/**
 * This method is like `_.uniq` except that it accepts `iteratee` which is
 * invoked for each element in `array` to generate the criterion by which
 * uniqueness is computed. The order of result values is determined by the
 * order they occur in the array. The iteratee is invoked with one argument:
 * (value).
 *
 * @static
 * @memberOf _
 * @since 4.0.0
 * @category Array
 * @param {Array} array The array to inspect.
 * @param {Function} [iteratee=_.identity] The iteratee invoked per element.
 * @returns {Array} Returns the new duplicate free array.
 * @example
 *
 * _.uniqBy([2.1, 1.2, 2.3], Math.floor);
 * // => [2.1, 1.2]
 *
 * // The `_.property` iteratee shorthand.
 * _.uniqBy([{ 'x': 1 }, { 'x': 2 }, { 'x': 1 }], 'x');
 * // => [{ 'x': 1 }, { 'x': 2 }]
 */
```
 Quite a few other functions that use some form of "shorthand" end up giving the same kind of error.

I'm not sure if this was intentional or not but it does make my inspection tool tell me a lot of false-positives when coding using lodash and its shorthands.

Is there a way to improve the documentation that would alleviate this or is it just a known pain point?

**Comment by jdalton** [comment]
Hi @bradlys!

> Is there a way to improve the documentation that would alleviate this or is it just a known pain point?

It's just a pain point. I wanted to avoid bloating the jsdoc with all the forms of the shorthand (there are several) so it's an assumed but not documented exception. There are TypeScript typings that do this though.
