### ISSUE TITLE
Are the docs incorrect for sortBy?

### ISSUE THREAD

**Issue by octogonz** [lodash/lodash#4486]
[The docs](https://lodash.com/docs/4.17.15#sortBy) show the sortBy arguments as being:

> **Arguments**
>
>  `collection (Array|Object)`: The collection to iterate over.
>
>  `[iteratees=[_.identity]] (...(Function|Function[]))`: The iteratees to sort by.

Whereas in Lodash 3, the iteratee [was shown](https://lodash.com/docs/3.10.1#sortBy) as:

> `[iteratee=_.identity] (Function|Object|string)`: The function invoked per iteration.

..with a note that:
> If a property name is provided for iteratee the created _.property style callback returns the property value of the given element.

But it seems that `string` still works.  In fact the Lodash 4 example shows:
```ts
var users = [
  { 'user': 'fred',   'age': 48 },
  { 'user': 'barney', 'age': 36 },
  { 'user': 'fred',   'age': 40 },
  { 'user': 'barney', 'age': 34 }
];
_.sortBy(users, ['user', 'age']);
// => objects for [['barney', 34], ['barney', 36], ['fred', 40], ['fred', 48]]
```
...and it does seem to sort by the named properties.

Does Lodash 4 officially support a property name string as the iteratee?  If so, why don't the Lodash 4 docs list it as `[iteratee=_.identity] (Function|Object|string)`?  In other words, if the behavior hasn't changed since Lodash 3, then why were the docs changed?

**Comment by jdalton** [comment]
Hi @octogonz!

Yes you're right. This was a doc design choice to avoid bloating our jsdoc typings. The shorthand forms are still allowed though.

**Comment by octogonz** [comment]
> Yes you're right. This was a doc design choice to avoid bloating our jsdoc typings. The shorthand forms are still allowed though.

@jdalton I don't get it.  This feature is intentionally removed from the documentation, but it is still supported?  How are people supposed to know that the shorthand forms were not deprecated?  

The point of JSDoc is to document the supported API parameters, so correctly representing the allowed parameters doesn't seem like "bloat".  (?)
