### ISSUE TITLE
[need help]: How can I clone the `File` object

### ISSUE THREAD

**Issue by eviIIt** [lodash/lodash#4487]
Hi there

I read the file `.internal/baseClone.js`

https://github.com/lodash/lodash/blob/898b378f069ecb6c92b7713529985ba78ff34d31/.internal/baseClone.js#L57

From the `cloneableTags` didn't find anything about neither `[object File]` nor `[object Blob]`

So all I wanna know is:

- [ ] Is the `File` object shouldn't clone?
- [ ] Will `lodash.clone*?` support clone `File` object?

> BTW, I will get `{}` when clone a `File` object.

**Comment by jdalton** [comment]
Hi @eviIIt!

We don't support cloning it directly, however you can use [`_.cloneWith`](http://lodash.com/docs/#cloneWith) to customize this.
