### ISSUE TITLE
Vulnerabilities in npm packages

### ISSUE THREAD

**Issue by prog1dev** [lodash/lodash#4489]
After `npm install` I got this output in console:

```
added 751 packages from 918 contributors and audited 4103 packages in 32.255s
found 440 vulnerabilities (5 low, 25 moderate, 407 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Considering a wide usage of lodash its worth fixing

Most of them could be fixed without breaking compatability so I will open PR for that

**Comment by jdalton** [comment]
Hi @prog1dev!

These are all dev deps so low priority. Nothing in our chain is effected by any of the security issues. They're all noise 🙉
