### ISSUE TITLE
_.pick makes multiple calls to property getter

### ISSUE THREAD

**Issue by octogonz** [lodash/lodash#4491]
I'm upgrading a large legacy code base to use to Lodash 4.  This project uses a (somewhat questionable) practice where property getters return promises.  Something like this:

```ts
export class DataModel {
  public get object1(): Promise<string> {
    // Performs a network call, returns a promise
    return this._fetchRestApiResult("https://example.com/object1");
  }
  public get object2(): Promise<number> {
    // Performs a network call, returns a promise
    return this._fetchRestApiResult("https://example.com/object2");
  }
}

interface IFetchedData {
  object1: string;
  object2: number;
}

export class ViewLayer {
  private dataModel: DataModel;

  public render(): void {
    Promise.props(_.pick(this.dataModel, ["object1", "object2"]))
      .then((result: IFetchedData) => {
        console.log(`Got: object1=${result.object1} object2=${result.object2}`);
      });
  }
}
```

**Expected:** In Lodash 2, `_.pick(this.dataModel, ["object1", "object2"])` works fine. The property getters are called once, and then `Promise.props()` waits for the promises to resolve, and then returns the combined result.

**Actual:** In Lodash 4, `_.pick` reads the property getters twice.  This means the first promise chain gets discarded, which causes a number of bad effects:
- The network request may be performed twice, which is inefficient
- The back-to-back calls sometimes reveal a race condition in the implementation
- If the promise chain rejects, we get an uncaught exception failure, because the promise chain was not properly terminated

Lodash doesn't make any formal guarantee about how many reads are performed.  But it would be reasonable for developers to assume the implementation should avoid obviously redundant operations.  It's fairly common for property getters to do nontrivial calculations (although starting promises is admittedly a bit unusual).  Also, it's surprising that Lodash 4 would be less efficient than Lodash 2.

## What's going on

Looking at the code, `pick()` calls `basePick()`:

[`pick.js`](https://github.com/lodash/lodash/blob/4.17.15-npm/pick.js)
```ts
var pick = flatRest(function(object, paths) {
  return object == null ? {} : basePick(object, paths);
});
```

...and `basePick()` calls `basePickBy()`:

[_basePick.js](https://github.com/lodash/lodash/blob/4.17.15-npm/_basePick.js)
```ts
function basePick(object, paths) {
  return basePickBy(object, paths, function(value, path) {
    return hasIn(object, path);
  });
}
```

Then `basePickBy()` calls `baseGet()`:

[_basePickBy.js](https://github.com/lodash/lodash/blob/4.17.15-npm/_basePickBy.js)
```ts
function basePickBy(object, paths, predicate) {
  var index = -1,
      length = paths.length,
      result = {};

  while (++index < length) {
    var path = paths[index],
        value = baseGet(object, path);

    if (predicate(value, path)) {
      baseSet(result, castPath(path, object), value);
    }
  }
  return result;
}
```

And `baseGet()` ultimately reads the value:

[_baseGet.js](https://github.com/lodash/lodash/blob/4.17.15-npm/_baseGet.js)
```ts
function baseGet(object, path) {
  path = castPath(path, object);

  var index = 0,
      length = path.length;

  while (object != null && index < length) {
    object = object[toKey(path[index++])];  // <=== GETTER READ #1
  }
  return (index && index == length) ? object : undefined;
}
```

For the second read, `basePickBy()` invokes the `predicate(value, path)` which calls `hasIn(object, path)` from **_basePick.js** above:

[hasIn.js](https://github.com/lodash/lodash/blob/4.17.15-npm/hasIn.js)
```ts
function hasIn(object, path) {
  return object != null && hasPath(object, path, baseHasIn);
}
```

This calls `hasPath()` which finally performs the read:

[_hasPath.js](https://github.com/lodash/lodash/blob/4.17.15-npm/_hasPath.js)
```ts
function hasPath(object, path, hasFunc) {
  path = castPath(path, object);

  var index = -1,
      length = path.length,
      result = false;

  while (++index < length) {
    var key = toKey(path[index]);
    if (!(result = object != null && hasFunc(object, key))) {
      break;
    }
    object = object[key];  // <=== GETTER READ #2
  }
  if (result || ++index != length) {
    return result;
  }
  length = object == null ? 0 : object.length;
  return !!length && isLength(length) && isIndex(key, length) &&
    (isArray(object) || isArguments(object));
}
```

## Proposed fix

This loop seems to evaluate `object = object[key];` pointlessly:

[_hasPath.js](https://github.com/lodash/lodash/blob/4.17.15-npm/_hasPath.js)
```ts
  while (++index < length) {
    var key = toKey(path[index]);
    if (!(result = object != null && hasFunc(object, key))) {
      break;
    }
    object = object[key];  // <=== GETTER READ #2
  }
  if (result || ++index != length) {
    return result;
  }
```
When `hasFunc()` returns true, then `result` becomes `true`, which ensures that we will call `return result;`.  Thus the `object[key]` value is never used.

So it seems we could avoid the second read by optimizing this logic in `hasPath()`.

**Comment by octogonz** [comment]
It's also worth pointing out that this is a surprising amount of logic for such a basic operation.  We didn't even get into `flatRest()` or `baseSet()` or `castPath()` (both calls) or `toKey()` or `baseHasIn()` or `isLength()` or `isIndex()` or `isArray()` or `isArguments()`, or the other functions called by those functions. 😇

Would it make sense to try to simplify the implementation somehow?  Or at least detect when the advanced callback parameters are not provided, and switch to a streamlined version?

As a comparison, here's a simpleminded implementation of `pick()`.  It's missing the fancy features, but it's roughly two orders of magnitude less operations: (!)

```ts
function pick(input: any, keys: string[]) {
  const result: any = {};
  for (const key of keys) {
    if (Object.prototype.hasOwnProperty.call(input, key)) {
      const value = input[key];
      result[key] = value;
    }
  }
  return result;
}
```

**Comment by jdalton** [comment]
Hi @octogonz!

Feel free to submit a PR and simplify all-the-things 🏗

**Comment by octogonz** [comment]
@jdalton What branch should I create a PR against?  

The `master` branch seems to contain significant entropy for Lodash 5.  Whereas if I create a PR to eliminate the redundant call in `hasPath()`, we'd want it the fix to be published for the 4.17.x series.

**Comment by jdalton** [comment]
Commit it against `master`. That's where all the breaking changes can occur.

**Comment by octogonz** [comment]
I can't figure out how to build the `master` branch.

`npm install` reports a broken peer dependency:
```
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

`npm test` prints:
```

> lodash@5.0.0 pretest D:\Git\lodash
> npm run build


> lodash@5.0.0 build D:\Git\lodash
> npm run build:main && npm run build:fp


> lodash@5.0.0 build:main D:\Git\lodash
> node lib/main/build-dist.js

module.js:550
    throw err;
    ^

Error: Cannot find module 'D:\Git\lodash\lib\main\build-dist.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lodash@5.0.0 build:main: `node lib/main/build-dist.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lodash@5.0.0 build:main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\owner\AppData\Roaming\npm-cache\_logs\2019-10-01T21_25_20_088Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lodash@5.0.0 build: `npm run build:main && npm run build:fp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lodash@5.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\owner\AppData\Roaming\npm-cache\_logs\2019-10-01T21_25_20_128Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lodash@5.0.0 pretest: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lodash@5.0.0 pretest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\owner\AppData\Roaming\npm-cache\_logs\2019-10-01T21_25_20_164Z-debug.log
```

**Comment by octogonz** [comment]
Also I can't seem to run any of the code.  For example:

```
D:\Git\lodash>node
> let pick = require('./pick')
Thrown:
D:\Git\lodash\pick.js:1
import basePick from './.internal/basePick.js'
       ^^^^^^^^
```

I'm using Node 10.16.3.  It doesn't understand this import style.

**Comment by octogonz** [comment]
Maybe I can make a PR against the [4.17.15-npm](https://github.com/lodash/lodash/tree/4.17.15-npm) branch, and then you guys can figure out how to integrate it into `master`?

**Comment by octogonz** [comment]
(This first PR will be a small logic fix to avoid double reads. It won't be a "breaking change.")

**Comment by octogonz** [comment]
Here's a PR: https://github.com/lodash/lodash/pull/4507

**Comment by jdalton** [comment]
Moved to #4507.
