### ISSUE TITLE
lodash.merge v4.6.2 does not get installed

### ISSUE THREAD

**Issue by PAnilReddy** [lodash/lodash#4493]
OS: Windows
Not able to install v4.6.2. At the same time V4.6.1 works.
tried with multiple systems and see the same result.
tried all the options of cleaning cache, deleting folders...

Throws 
npm ERR! code EINTEGRITY
npm ERR! sha512-0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ== integrity checksum failed when using sha512: wanted sha512-0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo
7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ== but got sha512-y7f4VpFmgr4zZ3Q7Qfv6G/DKusIXKv5qgRPq7DeAwgX7B726i5AcjVcQQYtud7dOY4yYLgkyCuu1kUPfOMTGYA==. (864 bytes)

**Comment by exx8** [comment]
can't reproduce on ubuntu 18.04. have you tried with yarn?

**Comment by PAnilReddy** [comment]
Yes, I am still getting the problem.
I tried with Yarn as well.. same result.

**Comment by jdalton** [comment]
I'm guessing it's a registry hiccup as we haven't done anything on our end.
