### ISSUE TITLE
sortedUniqWith

### ISSUE THREAD

**Issue by eternalmatt** [lodash/lodash#4494]
There exists `uniq`, `uniqBy`, `uniqWith` but only `sortedUniq` and `sortedUniqBy`.

The sortedUniq* functions do not take a comparator, and instead run an `eq` (===) comparison.  I have a need for a custom comparator.

**Comment by nahidmbstu** [comment]
have you tried _.sortedIndexBy ?

**Comment by nahidmbstu** [comment]
use Uniqwith and then sort

**Comment by nahidmbstu** [comment]
custom function

**Comment by eternalmatt** [comment]
Thank you for the suggestion, but no those would not work.

`sortedIndexBy` returns an index number.
`uniqWith` works, but is slow.  `sortedUniqWith` would be an optimization.

Keep in mind, the sorted* functions are only for performance boosts.  They don't sort the array for you; instead they _expect_ the argument array is already sorted.

**Comment by sharmaaditya570191** [comment]
Hi @eternalmatt. Could you please give an example to explain the working of the needed sortedUniqWith function?

**Comment by eternalmatt** [comment]
For example, a collection such as 
```
var xs = [ { id: 0, name: 'Foo' }, { id: 0, name: 'Foo' }, { id: 1, name: 'Bar' } ]
```

sortedUniqWith would output
```
_.sortedUniqWith(xs, 'id')
=> [ { id: 0, name: 'Foo' }, { id: 1, name: 'Bar' } ]
```

**Comment by nahidmbstu** [comment]
const _ = require("lodash")

var xs = [ { id: 1, name: 'Bar' },  { id: 0, name: 'Foo' }, { id: 0, name: 'Foo' }, { id: 1, name: 'Bar' },  ]

var ls = _.uniqBy(xs, 'id')

console.log(_.sortBy(ls, 'id'))

**Comment by falsyvalues** [comment]
Hi @eternalmatt!
Simple composition of `orderBy` and `uniqBy`:
```js
_.uniqBy(_.orderBy([ { id: 1, name: 'Bar' },  { id: 0, name: 'Foo' }, { id: 0, name: 'Foo' }, { id: 1, name: 'Bar' }  ], ['id', 'name'], ['asc', 'asc']), 'id');
// => [Object {id: 0, name: "Foo"}, Object {id: 1, name: "Bar"}]
```
