### ISSUE TITLE
[Feature] Retry a method call upto `n` times till it succeeds

### ISSUE THREAD

**Issue by pravesh-curefit** [lodash/lodash#4499]
Many times you need to retry a method call if it throws an error. This would make a good addition to lodash.
If something like this isn't already in the works (couldn't find anything in issues), I could send a PR.

**Comment by jdalton** [comment]
Hi @pravesh-curefit!

I think I'd like to see this as a one-off package leveraging [`_.attempt`](https://lodash.com/docs/#attempt) and maybe another Lodash method.
