### ISSUE TITLE
Incompatibility with Underscore — extending object with read only properties.

### ISSUE THREAD

**Issue by pepkin88** [lodash/lodash#45]
Somewhat TL;DRy, a summary at the bottom.

Today I tried replacing Underscore with Lo-Dash in my current project (thanks for summoning me ;) ) and it didn't go so seamless as expected, nevertheless it was still easy to adjust.
That incompatibility is different behavior when extending properties which are not writable (code for node.js):

``` JavaScript
var underscore = require('./underscore'),
    lodash = require('./lodash'),
    obj = Object.create(Object.prototype, {
        id: {
            value: 'asd',
            writable: false
        }
    });

function test(_, name) {
    try {
        _.extend(obj, {id: 'qwe'});
        console.log(name + ' OK');
    } catch (e) {
        console.log(name + ' Error: ', e.message);
    }
}

test(underscore, 'Underscore');
test(lodash, 'Lo-Dash');
```

That code will print this:

```
Underscore OK
Lo-Dash Error:  Cannot assign to read only property 'id' of #<Object>
```

In my case the `obj` variable was `req.session` from Connect/Express, which apparently has property `id` set as nonwritable.

Summary:
That behavior comes with `'use strict';`, so in Lo-Dash it is probably more preferable to throw an exception there, I just want to point out that not always transfer from Underscore to Lo-Dash is seamless, I think it's better to know about such issues.

**Comment by fatso83** [comment]
I was assuming `lodash` to throw on merging frozen objects, so this bit us recently. Took a decent amount of digging to find this was the cause, as I (falsely) assumed a strict mode function calling a non-strict function from another module would still be in strict mode ...
