### ISSUE TITLE
Consult about how to make a new function to this library?

### ISSUE THREAD

**Issue by ASASCED** [lodash/lodash#4501]
Hello, I'm new in this world about github but I wnat a seria of questions about how to contribute with a new function to this library.

__Before the questions I'm so sorry for my English, my natal language is Spanish.__

-Is it possible to add a new function to lodash or can I only correct errors?
-If I want to correct an error or add a new funtion do I need to work in a new branch? (I think it's an obvious question but I have that doubt)

These are the two questions I have and I would like to know if someone can help me, I am sorry if someone was upset about this but it will be the first time I will work in such a large library.

**Comment by falsyvalues** [comment]
Hi @ASASCED!
We have dedicated page that will answer your questions, see [CONTRIBUTING.md](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md).
