### ISSUE TITLE
Installing via npm I find a different source from that here in github

### ISSUE THREAD

**Issue by stratboy** [lodash/lodash#4503]
Hi, If I `nmp install lodash` and  take a look into the downloaded delay.js source, I find common js syntax `module.exports = delay`; BUT, if I take a look to the github repo (same downloaded version: 4.17.15), I find es6 syntax `export default delay`: why?

**Comment by falsyvalues** [comment]
Hi @stratboy!
We have different branches for different releases. Compare [npm branch](https://github.com/lodash/lodash/blob/npm/delay.js) vs [es branch](https://github.com/lodash/lodash/blob/es/delay.js). 
Hope that helps.
