### ISSUE TITLE
Lodash Deep Object Replacer?

### ISSUE THREAD

**Issue by RizkyArifNur** [lodash/lodash#4504]
Is lodash have a function to deep value replacement for a javascript object? example I have an object : 

```javascript
{
keyOne: "some value",
keyTwo: {
  nestedKey: "some value",
  arrayValue: ["some value"]
}
}
```

and I would like to replace all **some value** string to **new value** like this : 

```javascript
{
keyOne : "new value",
keyTwo: {
  nestedKey: "new value",
  arrayValue: ["new value"]
}
}
```

**Comment by jdalton** [comment]
Hi @RizkyArifNur!

You can use [`_.set`](http://lodash.com/docs/#set) or [`_.update`](http://lodash.com/docs/#update) for this.
