### ISSUE TITLE
why `console.log(_) is undefined; `but `console.log(_.get)` is a function ? ?

### ISSUE THREAD

**Issue by filedwu** [lodash/lodash#4508]
`import _ from 'lodash'
console.log('_', Object.prototype.toString.call(_))
console.log('_.get', Object.prototype.toString.call(_.get))`

result:
_ [object Undefined]
_.get [object Function]

**Comment by filedwu** [comment]
I feel puzzled at this case

**Comment by jdalton** [comment]
Hi @filedwu!

Maybe there is a custom `Symbol.toStringTag` on `_` or a weird Babel shim in place?
