### ISSUE TITLE
Document that over* methods accept matches* shortcuts

### ISSUE THREAD

**Issue by arty-name** [lodash/lodash#4510]
I was pleasantly surprised that `filter` and others can use multiple matchers thanks to `over*` functions:

```javascript
_.filter(input, _.overSome([
    _.matches({'a': 1}),
    _.matches({'a': 2}),
]))
```

Thanks to #2193 this becomes even better:

```javascript
_.filter(input, _.overSome([
    {'a': 1},
    {'a': 2},
]))
```

However that last improvement seems to be undocumented. Could you please document this possibility for `over*` functions? Referring to them in the `matches` documentation could be the cherry on top.

**Comment by jdalton** [comment]
If you're up for making a PR that would rock. You can do it against the `4.17.15-post` branch and modify the `lodash.js` in the root of the repo with the documentation inline in the source.

**Comment by arty-name** [comment]
Here you go!
