### ISSUE TITLE
Own toString method of wrapped functions (like allPass result) breaks redux-saga work

### ISSUE THREAD

**Issue by krutoo** [lodash/lodash#4512]
Hi. I create issue to redux-saga: appPass result not working as pattern for takeEvery/takeLatest etc.

Answer of redux-saga contributor: https://github.com/redux-saga/redux-saga/issues/1950#issuecomment-539390080

In a nutshell, redux-saga check own toString method for work with libraries like redux-actions, which create action creators like:
```javascript
const testAction = foo => ({ type: 'TEST', foo }); 
testAction.toString = () => 'TEST';
``` 

I used allPass and it return function with own property `toString`.

Please explain why result of functions like allPass has redefined `toString` method? Thanks.

**Comment by jdalton** [comment]
Hi @krutoo!

We use a custom toString to help devs debug.
Feel free to remove the custom `toString` method from the Lodash created method with the `delete` operator.
