### ISSUE TITLE
package.json was successfully found however this package itself specifies a main module field that could not be resolved

### ISSUE THREAD

**Issue by irohitb** [lodash/lodash#4516]
<img width="333" alt="Screenshot 2019-10-13 at 1 32 27 AM" src="https://user-images.githubusercontent.com/32276134/66707115-668e8800-ed59-11e9-82ae-dbe573e8e86e.png">

How am I using it?

`import _ from 'loadash'`

and then 

`const mergedPayload = _.defaultsDeep(payload, this.basePayload)`

This works though 

`const _ = require('lodash')`

**Comment by jdalton** [comment]
our package name is `lodash` and not `loadash`
