### ISSUE TITLE
_.template fails when interpolating 'class' key

### ISSUE THREAD

**Issue by kzinovjev** [lodash/lodash#4523]
This works:
`_.template('${a}')({a: 'test'})`

This doesn't (throws "Uncaught SyntaxError: Unexpected token )"):
`_.template('${class}')({class: 'test'})`

Tried with other delimiters listed in docs, throws the same error.

**Comment by falsyvalues** [comment]
Hi @kzinovjev!
Its because `class` is [reserved keywords in JavaScript](https://mathiasbynens.be/notes/reserved-keywords). 
```js
_.template('${try}')({try: 'test'})
```
Will also fail just like other keywords.
