### ISSUE TITLE
Question on  _get method

### ISSUE THREAD

**Issue by anisharknair** [lodash/lodash#4526]
Will lodash-es  **get** method shows error if if we give any wrong path.

For example " **get(this.meta, ['Meta', 0, 'value'], '');** "

If  **this.meta** has an object type which doesnt contain level  "Meta" but has "meta" ,

will **get** method shows error  saying  that  " property doesnt exist on the type" or some thing like that ?

How can we acheive this using lodash get ?

**Comment by anisharknair** [comment]
@jdalton

**Comment by falsyvalues** [comment]
Hi @anisharknair!
See [get docs](https://lodash.com/docs/4.17.15#get), it will return `undefined` missing paths are resolved to `undefined`.
