### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by L2jLiga** [lodash/lodash#4529]
*version*: master

*input*: `_.round(-1.4445, 3)`

*expected*: `-1.445`
*actual*: `-1.444`

**Comment by jamesplease** [comment]
The behavior of Lodash here is consistent with `Math.round`, so I think it is expected. [From MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round) (it's long, sry 🤷‍♂emphasis mine ):

> If the fractional portion of the argument is greater than 0.5, the argument is rounded to the integer with the next higher absolute value. If it is less than 0.5, the argument is rounded to the integer with the lower absolute value.  If the fractional portion is exactly 0.5, the argument is rounded to the next integer in the direction of +∞.  Note that this differs from many languages' round() functions, which often round this case to the next integer away from zero, **instead giving a different result in the case of negative numbers with a fractional part of exactly 0.5**.

Test cases:

```js
Math.round(1.5);
// => 2

Math.round(-1.5);
// => -1
```

**Comment by shauntck** [comment]
i just ran across this myself. It works if you use lodash proper.. but if you use the /fp version the rounding doesn't work.

**Comment by jamesplease** [comment]
@shauntck from [the docs](https://github.com/lodash/lodash/wiki/FP-Guide#fixed-arity), the lodash/fp round has a fixed arity of one, meaning it only takes a single argument.

It’s not clear to me if the behavior provided by that second arg is available in fp. I guess it isn’t?

**Comment by falsyvalues** [comment]
Hi @shauntck!
Like @jamesplease said methods like `round` have a [fixed arity of one](https://github.com/lodash/lodash/wiki/FP-Guide#fixed-arity). You can customize them with [`convert`](https://github.com/lodash/lodash/wiki/FP-Guide#convert).
