### ISSUE TITLE
Add Latin extended-B C and D block to deburr

### ISSUE THREAD

**Issue by funkyremi** [lodash/lodash#4530]
Hi,
The deburr function doesn't work for 'ș' which is in the latin extended B block.
Have you planned to add other latin extended blocks to the deburr function?
Thanks

**Comment by falsyvalues** [comment]
Hi @funkyremi!

As [docs](https://lodash.com/docs/4.17.15#deburr) says we support converting on Latin-1 Supplement and Latin Extended-A.
