### ISSUE TITLE
How can I convert a function with variadic params to a fixed arity one?

### ISSUE THREAD

**Issue by jfstgermain** [lodash/lodash#4535]
I've looked at ary, rearg, bind with placeholders... No luck.  What's the simplest way to convert a variadic params function to a fixed arity one so it can be curried?  

I can do `curry((param0, param1) => fn(param0, param1))` but I was wondering if there was some pointfree way of doing it.

Thanks

**Comment by jdalton** [comment]
Hi @jfstgermain!

Check out [`_.ary`](https://lodash.com/docs/#ary) or [`_.unary`](https://lodash.com/docs/#unary).
