### ISSUE TITLE
IterateeShorthand typescript

### ISSUE THREAD

**Issue by WORMSS** [lodash/lodash#4536]
I know this is technically not maintained by this project, but I was wondering what people thought of the `IterateeShorthand<T> type`
It's currently 
```ts
type PropertyName = string | number | symbol;
type IterateeShorthand<T> = PropertyName | [PropertyName, any] | PartialShallow<T>;
```
I thought a better type would be
```ts
type PropertyNameStrict<T> = keyof T;
type IterateeShorthand<T> = PropertyNameStrict<T> | [PropertyNameStrict<T>, any] | PartialShallow<T>;
```
This would allow stuff like
```ts
const a = [{ a: 1, b: 2 }, { a: 3, b: 4}];
const b = _.uniqBy(a, 'a');
```
but not allow the below which is currently possible.
```ts
const c = _.uniqBy(a, 'noexist');
```

**Comment by falsyvalues** [comment]
Hi @WORMSS!

This discussion should definitely go to ➡️[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) contributors of [@types/lodash](https://www.npmjs.com/package/@types/lodash) will help for sure.

**Comment by WORMSS** [comment]
Definitely Typed issues is a place where things bet buried and forgotten about. It's why I came here. I thought someone would actually respond.

**Comment by falsyvalues** [comment]
@WORMSS  I have quite different experience with them 😃
