### ISSUE TITLE
Prototype Pollution Issue (on npm audit)

### ISSUE THREAD

**Issue by aamirshaikh23** [lodash/lodash#4537]
Issue of Prototype Pollution still persists even after updating the package and its dependent packages and performing required checks. Current version of lodash : 4.17.15

Report:-
Dependency of:   chrome
Path:            chrome > plist > xmlbuilder > lodash
More info:     https://nodesecurity.io/advisories/782

**Comment by falsyvalues** [comment]
Hi @aamirshaikh23!

This issue is related to outdated `xmlbuilder` package and it should be posted there.
