### ISSUE TITLE
Cannot set property 'propertname' of undefined

### ISSUE THREAD

**Issue by mudsye** [lodash/lodash#4539]
We have been getting an error "Cannot set property 'propertname' of undefined" when trying to use .merge to overriding contents with nested properties in it. E.g. below where db.:options:database is something I would like to override. 
Appreciate any help on this. Thanks!

**Destination content**:

    "db": {
      "server": "servername",
      "port": 1433,
      "userName": "user",
      "password": "password",
      "options": {
          "database": "stg-db",
          "encrypt": true,
          "rowCollectionOnRequestCompletion" : true
      }
    },

**Source content**:

    "db": {
      "options": {
          "database": "rel-db",
      }
    },

**Comment by csabat** [comment]
Hey @mudsye.

I have tried to reproduced your error bu it seems everything works fine for me.  I'm not sure your use case but i have created a sandbox.
Please let me know if I can help more.
https://codesandbox.io/s/loving-euler-5ejj1?fontsize=14

**Comment by mudsye** [comment]
Thanks for replying. Yes this worked for me when its in standalone code using lodash.
However when using this in cypress its somehow giving this error. I have gone with alternatives ATM either using .assign to override this property "database" or using a separate config in code to avoid merging.

**Comment by xapai** [comment]
'propertname' looks like a typo for me. Maybe it should be 'propert**Y**name'?
