### ISSUE TITLE
[Feature Request] Showing Time Complexity of Functions In The Documentation

### ISSUE THREAD

**Issue by matthewkwong2** [lodash/lodash#4540]
I would like to know the time complexity (e.g. in Big O notation) of the algorithms, preferably in the documentation.

One of the cases is the differences of the time complexities between `sortedUniq` and `uniq`. My ultimate goal is to display an array of `String` with 1) no duplicates and 2) is sorted. And there are 2 ways to do so.
1. Sort the array, then apply `sortedUniq`
2. Apply `uniq` then sort the array

Currently, there is no way I know which one is better since I have no idea how "optimize" is `sortedUniq`. (For `uniq`, I assume it is `O(n)`)

**Comment by mattmaduzia** [comment]
I don't know if this is helpful, but you can always look at the source code and determine the time complexities yourself. In fact, you could then submit a Pull Request to add them to the documentation!

**Comment by jdalton** [comment]
Hi @matthewkwong2!

For your case you might have better luck putting the keys into a `null` prototyped object then reading them out an sorting them.

```js
const o = { __proto__: null }
// add a bunch of keys
const keys = Object.keys(o).sort(someSortFunc)
```
