### ISSUE TITLE
Case Functions should have option to NOT deburr special characters.

### ISSUE THREAD

**Issue by GeorgeWL** [lodash/lodash#4541]

**Comment by jdalton** [comment]
Hi @GeorgeWL!

This has been changed in our master branch for v5.

**Comment by GeorgeWL** [comment]
ooh awesome. Any idea when that will get released @jdalton ? Or is there a way to try it out on personal projects? (not gonna risk it on a production thing 👅)

**Comment by jdalton** [comment]
You can checkout our master branch, it's still a bit of a mess but it can give you an idea of where we're going.

**Comment by GeorgeWL** [comment]
thanks 👍
