### ISSUE TITLE
feature request: _.isNotNil _.isNotNull

### ISSUE THREAD

**Issue by xiaoxiangmoe** [lodash/lodash#4542]
```ts
function isNotNil<T>(x: T): x is NonNullable<T> {
  return x != null;
}
function isNotNull<T>(x: T): x is T extends null ? never : T {
  return x !== null;
}
```

**Comment by jdalton** [comment]
Hi @xiaoxiangmoe!

We have a [`_.negate`](https://lodash.com/docs/#negate) method to convert our [`_.isNil`](https://lodash.com/docs/#isNil) and [`_.isNull`](https://lodash.com/docs/#isNull).

**Comment by lsdsjy** [comment]
> Hi @xiaoxiangmoe!
> 
> We have a [`_.negate`](https://lodash.com/docs/#negate) method to convert our [`_.isNil`](https://lodash.com/docs/#isNil) and [`_.isNull`](https://lodash.com/docs/#isNull).

@jdalton _.negate(_.isNil) doesn't have TypeScript type guard, which is annoying in some cases, e.g.
```typescript
const array = [1, undefined]
const filtered = array.filter(x => x).map(x => x.toString())  // TypeScript compiler complains `Object is possibly 'undefined'`
```
while @xiaoxiangmoe 's code ensures correct typing. Please consider re-opening this issue.

**Comment by pkondzior** [comment]
It's true, you cannot typeguerd with negate(isNull)()
