### ISSUE TITLE
lodash/cloneDeep

### ISSUE THREAD

**Issue by AdmiralPanFeng** [lodash/lodash#4543]
const [set,setSets] = useState(new Set([1]));
    function onAdd() {
        const set = new Set([1]);
        const cloneSet =clone(set);
        cloneSet.add(2);
        console.log(set,cloneSet); // Set(2) {1, 2}  Set(2) {1, 2}
    
        setSets(cloneSet);
    }

This problem occurs in react production environment；

**Comment by jdalton** [comment]
Hi @AdmiralPanFeng!

I cannot reproduce this on the current stable release of `lodash`.
