### ISSUE TITLE
Proposal to add a new method getPath

### ISSUE THREAD

**Issue by flerko** [lodash/lodash#4545]
How about adding a new method to find the path in an object?

```jsx
export default function getPath(object, predicate, objectPath = []) {
  if (!object || typeof object !== 'object') {
    return;
  }

  for (const [key, value] of Object.entries(object)) {
    const entryPath = [...objectPath, key];

    if (predicate(value, key)) {
      return entryPath.join('.');
    }

    const result = getPath(value, predicate, entryPath);
    if (result) {
      return result;
    }
  }
}
```

Method call:
getPath(object, (value, key) => value === v && key === k)
getPath(object, (value, key) => key === k);

**Comment by rafde** [comment]
```js
const test = {
  some: {
    thing: 'a',
    one: {
      here: 'a',
    }
  },
};
const pathTo = getPath(test, (value) => value === 'a');
```
What is the result of `pathTo`?

**Comment by flerko** [comment]
> ```js
> const test = {
>   some: {
>     thing: 'a',
>     one: {
>       here: 'a',
>     }
>   },
> };
> const pathTo = getPath(test, (value) => value === 'a');
> ```
> 
> What is the result of `pathTo`?

The result of the first occurrence of your value

**Comment by rafde** [comment]
I propose method name should be `findPath` since the `find` prefixed methods look for the first element predicate that returns truthy.
Seems like a nice addition. 
Could be nice to also have a getPaths that will return all the paths a value was found in.

**Comment by jdalton** [comment]
Hi @flerko!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
