### ISSUE TITLE
How to sort the array of objects with string contains using Lodash

### ISSUE THREAD

**Issue by spvjebaraj** [lodash/lodash#4552]
Hi Team,
I am working in Angular 8 and I am using Lodash to perform the filtering and other activities. I want to sort the array of objects with descending order. In that, I want to move the results to last if the field value contains the keyword which I passed. Please consider the below example.

`const searchList = [
    {Title: 'Test1', Url: 'www.google.com'},
    {Title: 'Test2', Url: 'mailto:somemail@example.com'},
    {Title: 'Test3', Url: 'www.gmail.com'},
]`

From the above array, I want second item to be moved to last (I want to sort with the keyword 'mailto'). In the array, we have multiple entries starts with 'mailto' keyword. Kindly help me on this

**Comment by jdalton** [comment]
Hi @spvjebaraj!

For questions like this please visit our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by spvjebaraj** [comment]
Hi,
I did the following code and it is working fine now.
`var sortedItems = _.sortBy(searchList, item => {
            return item.Url.Url.toLowerCase().startsWith("mailto", 0) ? 1 : 0
          });`
