### ISSUE TITLE
Opening this issue to know the state of the tests in lodash source code as they seems to be broken.

### ISSUE THREAD

**Issue by agarwalprashant** [lodash/lodash#4556]
We took a look at a few files in the test directory without the **.test.js** suffix and they seem to have problems that stopped them from running:

- test/__proto__-property-bugs.js: will error on line 48 (groupBy) because the second parameter being passed is a string and groupBy is expecting a function.
- test/ary.js: will error on line 4 because ../ary.js file does not exist.
- test/assignIn.js: will error on line 2 because ../extend.js file does not exist.

In fact, many of the files that contain tests that don't have the **.test.js** suffix appear to be broken (which we assume is why they don't have the suffix). For example, **compact.js** will error with identity is not defined because no variable is defined before it is used on line 32.

I am attaching a screenshot of one of the failing test to better explain the issue.

![Capture1](https://user-images.githubusercontent.com/8237463/69210870-3e791c80-0b82-11ea-956d-2ac3ba6d65f0.PNG)

**Comment by jdalton** [comment]
Hi @agarwalprashant!

Yes, our master branch is a bit of a mess. If you're up for performing a bit of house cleaning for the Lodash unit tests that would be awesome!
