### ISSUE TITLE
_.lowerCase && _.upperCase  removes all special characters  in the original string. 

### ISSUE THREAD

**Issue by yravinderkumar33** [lodash/lodash#4560]
lowerCase & upperCase method removes all special characters in original `string.
Examples:- 

**Command** : _.lowerCase('ravinder-kumar') 
**Output**:  "ravinder kumar"

**Command** : _.lowerCase('ravinder-kumar-fdsfsdf/fds/f/ds/f/ds/f')
**Output**: "ravinder kumar fdsfsdf fds f ds f ds f"

**Comment by SHAPPY0** [comment]
I think you are looking for _.toLower()
Check it out https://lodash.com/docs/#toLower

**Comment by jdalton** [comment]
Hi @yravinderkumar33!

Yes our current case methods will split compound words apart and perform the case operation. This will be revisited in our v5 as it's caused a lot of confusion. As @SHAPPY0 points out there is [`_.toLower`](https://lodash.com/docs/#toLower) and [`_.toUpper`](https://lodash.com/docs/#toUpper).
