### ISSUE TITLE
trimStart sometimes removes more characters than it should

### ISSUE THREAD

**Issue by ofrebourg** [lodash/lodash#4562]
`_.trimStart('User Identity Groups:GuestType_Engineer', 'User Identity Groups:')`

Returns: `"Type_Engineer"`

Expected response: `"GuestType_Engineer"`

**Comment by jdalton** [comment]
Hi @ofrebourg!

Please look at the doc example for [`_.trimStart`](http://lodash.com/docs/#trimStart) closely. The string is not a substring to match and trim but rather a string of individual characters to trim.

**Comment by ofrebourg** [comment]
This makes more sense, thanks. I shouldn't be working too late!
Sorry about that jdalton!
