### ISSUE TITLE
_.unset always return true.

### ISSUE THREAD

**Issue by vsisko** [lodash/lodash#4564]
Run example in REPL (https://lodash.com/docs/4.17.15#unset) and change any path to invalid. F.e.
> var object = { 'a': [{ 'b': { 'c': 7 } }] };
> console.log(_.unset(object, 'a[0].b.invalid'));

will print true when false expected.
_.unset for empty object also return true:
> console.log(_.unset({}, 'invalid'));

**Comment by jdalton** [comment]
Hi @vsisko!

We mimicked the behavior of the `delete` operator.
