### ISSUE TITLE
_.set fails when using a path containing only numbers

### ISSUE THREAD

**Issue by Aljoscha-Ide** [lodash/lodash#4565]
_.set fails when using a path that contains only numbers and '.' as the delimiter. 
The following code for example:
`const path = '1.2';
result = _.set({}, path, 'value');
`
should return 
`{
   "1": {
      "2": "value"
   }
}`
The result however is somehow an array with as many null values as the second number specified:
`{
   "1": [
      null,
      null,
      "value"
   ]
}`

**Comment by jdalton** [comment]
Hi @Aljoscha-Ide!

By default we assume index properties create arrays. You can customize this though with [`_.setWith`](http://lodash.com/docs/#setWith).
