### ISSUE TITLE
sampleWeighted

### ISSUE THREAD

**Issue by YuriGor** [lodash/lodash#4568]
Hi!
It would be great to have a function to pick a random array element but with a chance determined by iteratee/property selector.
Like, for example, [weighted-random](https://www.npmjs.com/package/weighted-random) but applied to array already:
```js
var movies = [
    { rating: 9.2, title: 'The Dark Knight' },
    { rating: 8.7, title: 'Inception' },
    { rating: 8.0, title: 'Jurassic Park' }
];
var movie = _.sampleWeighted(movies, 'rating');
```
sampleSizeWeighted also would be great, because it will be possible to optimise and calculate weights only once.

**Comment by jdalton** [comment]
Hi @YuriGor!

I tinker in the same hobby as you I suspect :)
We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by YuriGor** [comment]
Some game development?) Please share if it's published, cannot find it)
But in my case it's an [emoji bot](https://t.me/KidsEmojiBot) for telegram, so I choose random emojis to respond, but considering their [name\category\tags](https://github.com/YuriGor/unicode-emoji-meta) relevance to incoming emojis.

**Comment by shtse8** [comment]
any updates?
