### ISSUE TITLE
Unable to load lodash/fp from CDN

### ISSUE THREAD

**Issue by otakustay** [lodash/lodash#4569]
The "FP Guide" wiki leaves me to use jsdelivr like:

```html
<script src='https://cdn.jsdelivr.net/g/lodash@4(lodash.min.js+lodash.fp.min.js)'></script>
```

In fact there is no `lodash.fp.min.js` in recent version.

Is there any methods to use both `lodash` and `lodash/fp` from CDN like jsDelivr? It could be better if `lodash.min.js` bundles with fp functions since it does not introduce much size to wrap a fp.

**Comment by jdalton** [comment]
The file loads for me. Can you try again?
