### ISSUE TITLE
Behaviour of _.isEmpty, _.size with ArrayBuffer and SharedArrayBuffer

### ISSUE THREAD

**Issue by popsUlfr** [lodash/lodash#4570]
Hello,

it wasn't immediately clear to me why my code using `SharedArrayBuffer` was behaving strangely and I was scratching my head.

`ArrayBuffer` and `SharedArrayBuffer` simply don't have a `length` property which seems to make `_.isEmpty` or `_.size` not behave as expected.

They have a `byteLength` property which is the actual size of the buffer but I don't understand why a `length` property is not in the spec while every other array like object has it.

Thus, `_.isEmpty` and `_.size` don't behave as would be expected from them on these objects, always returning `true` and `0` respectively.

I think these functions should be in line with what they return for `Buffer` or `Uint8Array`.

References : 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

**Comment by adiSuper94** [comment]
Is help still needed for this issue ?
I'd like to contribute.
