### ISSUE TITLE
iteratee() doesn't work with deep shorthand on Errors

### ISSUE THREAD

**Issue by Alexsey** [lodash/lodash#4571]
Consider code
```js
const x = {}
const y = new (function () {})
const z = new Error
x.prop = 'prop'
y.prop = 'prop'
z.prop = 'prop'

console.log( // shallow shorthand
  [x, y, z].map(
    _.iteratee({prop: 'prop'})
  )
) // [true, true, true] works as expected

console.log( // deep shorthand
  [{obj: x}, {obj: y}, {obj: z}].map(
    _.iteratee({obj: {prop: 'prop'}})
  )
) // [true, true, false] while should be [true, true, true]
```

This bug affects not only specific `interatee()` usage, but all other deep shorthands, because they are used `interatee` under the hood. E.g.:
```js
console.log(
  _.partition(
    [{obj: x}, {obj: y}, {obj: z}],
    {obj: {prop: 'prop'}}
  ) // [ [ { obj: [Object] }, { obj: [Object] } ], [ { obj: [Error] } ] ]
) // while should have all elements in first array
```

**Comment by shubham-rocko** [comment]
Hi, Can I take this issue?

**Comment by ojeytonwilliams** [comment]
Is the following intended `iteratee` behaviour?  When in `matches` mode, I mean:

```js
matches(src) => obj => Object.keys(src).every(key => _.isEqual(obj[key], src[key]))
```

because currently it isn't behaving take way

```js
_.matches({a: [1]})({a: [1, 2]}) // is true
```

It's hinted at by the `_.matches` docs

>Partial comparisons will match empty array and empty object source values against any array or object value, respectively. See _.isEqual for a list of supported value comparisons.

that the values should be compared by `_.isEqual`, but I wasn't sure.

**Comment by rkuykendall** [comment]
@shubham-rocko Yes, I'm told this bug and https://github.com/lodash/lodash/issues/4434 are open to pull requests. Are you still interested?

**Comment by asvsfs** [comment]
Hi  @rkuykendall  i can take this one if still relevant.

**Comment by rkuykendall** [comment]
@asvsfs Hey, sorry for missing your message and not getting back to you. This issue is still wide open, no updates from @shubham-rocko, and looks like a nice one to work on. Let me know if you have any questions!

**Comment by adiSuper94** [comment]
s help still needed for this issue ?
I'd like to contribute.

**Comment by rkuykendall** [comment]
I have been working on this bug. 

- I wrote the test below. It correctly shows the bug.
- To get the test to run, I had to rename `tes/titeratee.js` to `test/iteratee.test.js` and disable a few tests
- This seems to be running against the lodash in nodemodules and not locally
- titeratee seems to no longer exist locally? Is it being removed? I can't find it.

```
  it('should work with deep shorthand on objects, functions, and errors', function() {
    var x = {},
      y = new (function () {}),
      z = new Error;

    x.prop = 'prop'
    y.prop = 'prop'
    z.prop = 'prop'

    assert.deepStrictEqual( // shallow shorthand
      [x, y, z].map(
        iteratee({prop: 'prop'})
      )
      , [true, true, true]);

    assert.deepStrictEqual( // deep shorthand
      [{obj: x}, {obj: y}, {obj: z}].map(
        iteratee({obj: {prop: 'prop'}})
      ), [true, true, true]);
  });
```
