### ISSUE TITLE
_.isEmpty Don't work with Date and Boolean Types

### ISSUE THREAD

**Issue by alonea** [lodash/lodash#4572]
_.isEmpty() method fail to work on Date and Boolean data types

**Comment by ZimGil** [comment]
https://github.com/lodash/lodash/issues/4566#issuecomment-559998726

> Hi
> 
> Our [`_.isEmpty`](http://lodash.com/docs#isEmpty) checks if an object is empty (has no-enumerable properties).

**Comment by hallya** [comment]
I confirm, its not working with Date object. Even if it is not suppose to work, the purpose of isEmpty method remains flacky

**Comment by jdalton** [comment]
See @ZimGil's linked comment.
