### ISSUE TITLE
Best way to use Lodash with react native

### ISSUE THREAD

**Issue by ScreamZ** [lodash/lodash#4575]
Hello,

I see a lot of comparison on whether should I use `lodash`, `lodash-es` or `lodash/fp`.

Like this one
- https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba
- or this one https://www.blazemeter.com/blog/the-correct-way-to-import-lodash-libraries-a-benchmark/

----
**Beside the fact I'm totally lost with all of this, depending on having webpack plugin, babel plugin…**, especially on the web where the bundle size matters.

I would like to ask you what is the advantage of using any of those, because shipped within react native we don't really care much about some small more ko of the bundle.

The only difference I could see is in terms of loading time (but is it really game changer depending on the bundle ?)

**What do you recommend me for React native usage?**

I really appreciate the fact of using lodash chain method, I saw some tutorials with `flow` and `fp`?

Thanks a lot

**Comment by atfzls** [comment]
Hi @ScreamZ,

You should ask these type of questions in stackoverflow.
Github issues should be used for filing bugs and issues with the project.

**Comment by falsyvalues** [comment]
Hi @ScreamZ !

For questions like this please visit our [gitter chat](https://gitter.im/lodash/lodash).

**Comment by cjduncana** [comment]
@ScreamZ Did you ever find your answer? I have the same questions, as well.

**Comment by ScreamZ** [comment]
No... I just ended shipping the whole library as it's react native and not web

**Comment by cjduncana** [comment]
What about the smaller bundle size? Is that no longer relevant for you? Is that not a relevant benefit in the context of mobile phone applications?

**Comment by ScreamZ** [comment]
It's not relevant in the context of a react native application considering the size of the lodash library IMO.

It could be nice but the time it take to make it works is not worth the potential benefit
