### ISSUE TITLE
isUndefined - use typeof instead?

### ISSUE THREAD

**Issue by jack-bliss** [lodash/lodash#4576]
Currently, the implementation for isUndefined uses a strict equality comparison with the value `undefined`. I was wondering why it was decided to use this method (that errors if the variable is undeclared) rather than using `typeof value === 'undefined'`, which doesn't. I have my theories but I'd be interested to hear from contributors!

**Comment by ZimGil** [comment]
I don't think you can get a `ReferenceError` with a declared argument

**Comment by falsyvalues** [comment]
@ZimGil You can't.
@jack-bliss `typeof` operator usage in this case won't change anything.

**Comment by ZimGil** [comment]
@falsyvalues wouldn’t it actually be less efficient?

**Comment by falsyvalues** [comment]
@ZimGil Engines are very efficient nowadays, pretty much there is no difference in performance of these operators.

**Comment by falsyvalues** [comment]
@jack-bliss It won't change anything because `typeof` is an operator and `isUndefined` is a function which doesn't behave like operator.

```javascript
const isUndefined = (v) => typeof v === "undefined";
isUndefined(z);
VM184:1 Uncaught ReferenceError: z is not defined
    at <anonymous>:1:13
```
