### ISSUE TITLE
Request for custom compare function support for min/max and minBy/maxBy functions.

### ISSUE THREAD

**Issue by voroninp** [lodash/lodash#4577]
There is an implemented feature  #3763 for `orderBy` function, but it looks like there is nothing for `min`, `max`, `minBy` and `maxBy` functions.

Sure, you can initially sort the collection in the required order and then take the first element, but it is less efficient because new array will be allocated, whereas simple iteration should be enough.

Actually having `max` and `min` with custom compare functions covers `maxBy` and `minBy`.

**Comment by falsyvalues** [comment]
Hi @voroninp!

Im not sure if I follow but we have [minBy](https://lodash.com/docs/4.17.15#minBy) and [maxBy](https://lodash.com/docs/4.17.15#maxBy) on board.

**Comment by voroninp** [comment]
Ok. How are the values selected by the function in `minBy` and `maxBy` compared?

**Comment by falsyvalues** [comment]
@voroninp `minBy` and `maxBy` accepts iteratee which is invoked for each element in array to generate the criterion by which the value is ranked. Order of input array doesn't matter, see [_.min](https://lodash.com/docs/4.17.15#min) or [_.max](https://lodash.com/docs/4.17.15#max) docs.

**Comment by voroninp** [comment]
@falsyvalues  there is one issue with iteratee 

To establish order relation you need to compare elements pairwise. Sometimes you may define only comparison, but you cannot define rank.

**Comment by voroninp** [comment]
@falsyvalues  Consider an array of persons. Imagine you need first to sort them by age and then by gender, and get the salary of the first one after sorting.

How would you do it with min/minBy?

**Comment by falsyvalues** [comment]
@voroninp Thats not a task for `_.min` or `_.minBy` which returns single value not whole collection. If you have to sort collection in such complex way, then get first result, you can simple access using `_.head`.

**Comment by voroninp** [comment]
@falsyvalues  That's it. I do not need the whole collection.

_orderBy + _.head means new allocation for sorted collection and O(N*log(N)) complexity for sorting, whereas min/minBy has O(N) complexity and does not create new collection.

**Comment by falsyvalues** [comment]
@voroninp `_.min` or `_.minBy`  is not depending on complex sorting like in your case. Comparing complexity of two different cases is just wrong and you cant do tha because they will never have meet.

**Comment by falsyvalues** [comment]
You can also try calculate weight for `_.minBy` or `_.maxBy` base on your conditions.

**Comment by voroninp** [comment]
>  they will never have meet.

What do you mean?


> is not depending on complex sorting like in your case.

That is what my proposal is about. Right now `_.minBy` lets you specify what to compare but not how to do it.

> You can also try calculate weight

I agree, sometimes this is a good option,  but not always. 
Here is a concrete example I had to deal with recently:

- User has some attached collection of items having a timestamp (memento object).
- I need to sort the list of users in the following order: first goes the user having the oldest item. 

My preferred solution would be:

```js
_.orderBy(users, user => _.minBy(user.items, item => item.timestamp, timestampCompareFn).timestamp, timestampCompareFn);
```
I cannot accomplish this because `_.minBy` does not allow me to provide `timestampCompareFn`.
So I need to sort collection of items first for every user.
