### ISSUE TITLE
Truncate function not honouring regexp seperator

### ISSUE THREAD

**Issue by martinholden-skillsoft** [lodash/lodash#4579]
I am trying to use the truncate function to shorten a string and using a regexp seperator, to try and ensure the truncated string before the omission does not have any of my seperator characters.

The truncation works BUT I still get seperator showing.

So:
var str = '123456789012345678 , 9012345678901234567890';
var truncated = _.truncate(str, {length: 20, separator: /[-,.&\s]/, omission: '...'});

I expect this to give me:
"1234567890123456..."
But I get
"1234567890123456 ..." - note the space before the omission

I think the code
https://github.com/lodash/lodash/blob/e51a424513fbbe83a34c1b3c21f8c5478e79389f/truncate.js#L90

Should be:
    if (string.slice(0, end).search(separator)) {

**Comment by sukhbeersingh** [comment]
I am not able to reproduce this error. This is what I get with your code- `12345678901234567...` which is actually 20 characters.

**Comment by martinholden-skillsoft** [comment]
Sorry my bad I had a typo in the str variable
```
const _ = require('lodash');

const str = '1234567890123456 , 789012345678901234567890';
const truncated = _.truncate(str, {length: 20, separator: /[-,.&\s]/, omission: '...'});
console.log(truncated);
```
This returns:
``1234567890123456 ...```
