### ISSUE TITLE
New HIGH vulnerability detected by audit in version 4.17.15

### ISSUE THREAD

**Issue by BorisNaguet** [lodash/lodash#4582]
Hello,

We haven't changed our dependencies recently, but there's apparently a new vulnerability detected by `npm audit`:

```
  High            lodash Package for Node.js lodash.js baseDifference()
                  Function Array Handling Memory Exhaustion DoS Weakness

  Package         lodash

  Patched in

  Dependency of   lodash

  Path            lodash

  More info       https://vulndb.cyberriskanalytics.com/vulnerabilities/218918
```

`npm list |grep lodash` effectively returns me 4.17.15

**Comment by sgeffken** [comment]
Same here, a hotfix would be highly appreciated, whole CI broken down currently.

**Comment by lokhaeri** [comment]
I had a look at the `baseDifference()` and it looks like in:

```
if (iteratee) {
    values = map(values, (value) => iteratee(value))
  }
  if (comparator) {
    includes = arrayIncludesWith
    isCommon = false
  }
  else if (values.length >= LARGE_ARRAY_SIZE) {
    includes = cacheHas
    isCommon = false
    values = new SetCache(values)
  }
```

in ` else if (values.length >= LARGE_ARRAY_SIZE) {`
there is no upper limit which can cause Memory Exhaustion
so the correct would be I assume something like this
```
if (comparator && values.length <= LARGE_ARRAY_SIZE) {
    includes = arrayIncludesWith
    isCommon = false
  }
  // not to allow to dump large amount of array into browser memory cache there should be an upper limit too
  else if (value.length < LARGE_ARRAY_MAX_SIZE) {
    includes = cacheHas
    isCommon = false
    values = new SetCache(values)
  }
```

**Comment by msolwecki** [comment]
Fantastic that this was addressed so quickly, I had just been checking into our npm audit results and saw this vulnerability pop up and the PR get merged.  Do you happen to know when it'll be released?

**Comment by jdalton** [comment]
Hi @BorisNaguet!

I'm not aware of vulndb.cyberriskanalytics and have not been notified in any of our security channels about this issue. If you're up for submitting a PR we'll review it but I'm a little miffed at the lack of communication with the folks creating these reports and the ones broadcasting them to users.

**Comment by BorisNaguet** [comment]
@jdalton : I have no knowledge in vulndb.cyberriskanalytics, 

I actually found it strange that `npm audit` (which I thought was a standard npm tool) reported me an issue with a link to that website, where I can't have any details without paying for VulnDB!

**Comment by imechemi** [comment]
@jdalton Any chance you have words with npm Security? Thanks

**Comment by yingzuo** [comment]
This issue is reported by Jfrog Xray which uses information from cyberriskanalytics. This link has more information: https://hackerone.com/reports/670779.

**Comment by jdalton** [comment]
The resolution of that issue for was a doc PR to be made. There will be no code change.

**Comment by jdalton** [comment]
so the advisory should be removed since there will be no update to code.

**Comment by imechemi** [comment]
@jdalton Can you guide me on documenting this? I just made an attempt on #4614.

**Comment by attritionorg** [comment]
@jdalton This vulnerability came about via HackerOne and the Node.js third-party modules project it looks like: https://hackerone.com/reports/670779 / https://hackerone.com/nodejs-ecosystem

If the lodash team did not receive any notification it would be best to ping them to establish a better reporting method from them to upstream.

**Comment by falsyvalues** [comment]
@imechemi There will no changes regarding that, see @jdalton comment.

**Comment by har1sh** [comment]
When will the doc update go through. I don't see it yet, and i need to stop using lodash if i can't resolve this vulnerability as per our company policy :-(

**Comment by ComputerWolf** [comment]
My company also uses Jfrog Xray and is now blocking lodash until this vulnerability is removed as well.

**Comment by har1sh** [comment]
@jdalton @falsyvalues any updates on this issue?

**Comment by falsyvalues** [comment]
Hi @har1sh!

We don't have any special plans for this. It was closed on [hackerone](https://hackerone.com/reports/670779) as Informative (Closed) because its not a real issue in Lodash. 

```js
Array.prototype.forEach.call({'length': 99999999999}, () =>{}) // hang
```

**Comment by har1sh** [comment]
@falsyvalues am aware of that, but on that hackerone it was agreed to document the usage of difference function for awareness. Without the vulnerability isn't resolved right? I saw a code check in for 5.0.0 that has the updated doc. Not sure when it would be released.

Apart from that my organization wants us to check for the input before we pass it in to the difference function, so in that case wouldn't it be helpful to have that check within the function, so developers needn't handle that every time we use that function.

**Comment by Kashish2394jn** [comment]
Hi, Is there any upcoming patch fix expected to come soon for lodash ?

**Comment by falsyvalues** [comment]
@har1sh In your case you should already wrap `difference` function and add your business validation and reuse within codebase. Lack of this simple approach cannot be justification for making such limitation within library.
