### ISSUE TITLE
Need confirmation that merge does not merge dest's empty object into source for property A, when source's property A is non empty obejct

### ISSUE THREAD

**Issue by dchhetri** [lodash/lodash#4584]
Need confirmation if the following behavior is expected or not
```javascript
const mergedValue = _.merge({ a: { b: 1} }, { a: {} })
/**
 //mergedValue = 
{
  "a": {
    "b": 1
  }
}
**/
```

when property `a` is given another value other than empty object, I see it overriding.

**Comment by falsyvalues** [comment]
Hi @dchhetri!

Everything we explained in our [docs](https://lodash.com/docs/4.17.15#merge). If something is unclear please let us know.
