### ISSUE TITLE
Includes Front-End JavaScript Libraries With Known Security Vulnerabilities

### ISSUE THREAD

**Issue by atishjain29100** [lodash/lodash#4585]
When running lighthouse audit, it shows security vulnerability issues in lodash version 4.17.5

Please get this resolved in the latest update. Attaching the screenshot

<img width="822" alt="Screen Shot 2019-12-11 at 3 10 40 PM" src="https://user-images.githubusercontent.com/35028035/70609938-ade5a780-1c28-11ea-9bcb-668cfe9caf80.png">

**Comment by falsyvalues** [comment]
Hi @atishjain29100!

Current version of Lodash is 4.17.15, please update your dependencies.
