### ISSUE TITLE
npm deprecate modular build packages?

### ISSUE THREAD

**Issue by jedwards1211** [lodash/lodash#4588]
So to follow up on #3838, I realized, probably we should `npm deprecate` all the modular build packages to encourage everyone using them to stop?  We could include my codemod instructions in the deprecation notice.  I get kind of annoyed how often I still see these packages in transitive deps.  Over time these deprecation notices could lead to reductions in virtually everyone's webpack bundle sizes.

**Comment by falsyvalues** [comment]
Hi @jedwards1211!

As @jdalton said in #3838 We won't deprecate these packages because it will cause massive problems and we want to avoid that. We may consider that after v5 release.
