### ISSUE TITLE
get(), keys(), entries(), etc for Map?

### ISSUE THREAD

**Issue by winstonwolff** [lodash/lodash#4590]
With the new Map type in ES6, we need to use different methods or operators to work with Maps vs. Objects. It would be great to have a library that abstracts the differences away. And Lodash seems like an obvious choice. What do the maintainers think? Should Lodash allow this?:
  `_.get(Map({a: {b:2}}), 'a.b')`
as well as this?
  `_.get({a: {b:2}}, 'a.b')`

 If PRs were submitted, would they be considered?

**Comment by jedwards1211** [comment]
`getIn`, `setIn`, `hasIn`, and `Set` would also need to be considered.

```js
`_.hasIn(Map({a: Set(['b'])}), 'a.b')
```

**Comment by georgezouq** [comment]
Any update about this?
