### ISSUE TITLE
collapse all - lodash docs

### ISSUE THREAD

**Issue by makkBit** [lodash/lodash#4592]
I would be awesome if there's a option to collapse all expanded headings to get a view of all heading, so that the user can easility browse to the desired section. Better UX.

Before:
<img width="326" alt="Screenshot 2019-12-14 at 01 40 11" src="https://user-images.githubusercontent.com/14000194/70829071-ba2d5880-1e12-11ea-9898-f51f72d665a2.png">

After selecting *collapse all*:

<img width="330" alt="Screenshot 2019-12-14 at 01 40 04" src="https://user-images.githubusercontent.com/14000194/70829132-e6e17000-1e12-11ea-80e3-f32f3112b7cf.png">

**Comment by jdalton** [comment]
Hi @makkBit!

Feel free to open a PR on [our site repo](https://github.com/lodash/lodash.com).

**Comment by makkBit** [comment]
Hi @jdalton !
Opened a PR ^
