### ISSUE TITLE
variable  `isFlat` is useless

### ISSUE THREAD

**Issue by Cuixote** [lodash/lodash#4593]
variable  `isFlat` is defined at [baseClone](https://github.com/lodash/lodash/blob/master/.internal/baseClone.js#L160), but Its value is always `false`.
I looked up all the places where baseclone is called, which doesn't take `CLONE_FLAT_FLAG ` as a parameter.
So is it possible to remove all `isFlat` related code in the `baseClone` function?

**Comment by falsyvalues** [comment]
Hi @Cuixote!
The `master` branch is in flux while we work on Lodash v5. This means things like npm scripts, which we encourage using for contributions, may not be working.
