### ISSUE TITLE
Isn't there a filter that returns Object?

### ISSUE THREAD

**Issue by panlina** [lodash/lodash#4594]
`filter` accepts both `Array` and `Object`, but always returns `Array`.

**Comment by ZimGil** [comment]
You can make it using `reduce`

```js
_.reduce(obj, (filtered, v, k) => {
  if (someTerm) {
    filtered[k] = v;
  }
  return filtered;
}, {});
```

**Comment by falsyvalues** [comment]
Hi @panlina!

What do You mean by filter that returns Object? One of the options is what @ZimGil proposed but without context its hard to propose something.

**Comment by panlina** [comment]
What @ZimGil proposed is just what I mean, namely, filtering an object/dictionary by value, and remains object/dictionary. I know this does not exist because "returning array version" and "returning object version" cannot be supported both without adding a parameter. Just asking.
