### ISSUE TITLE
Add a closest(object, key) method which will return the value of closest key in self or parent object

### ISSUE THREAD

**Issue by ankurnarkhede** [lodash/lodash#4596]
Sometimes, we need to get any key in the same object or its parent object. There isn't any lodash method available for the same.

e.g. 

```
let object= [
        {
          "listen": "listener 1",
          "listener_id": "89a33a1fcb81",
          "script": {
            "id": "d563d095-05ed-409e-b405-89a33a1fcb81",
            "type": "text/javascript"
          }
        },
        {
          "listen": "listener 2",
          "listener_id": "89a33a1fcb82",
          "script": {
            "id": "316f59fe-4f02-4b40-ad23-51d3dd7875a4",
            "type": "text/javascript"
          }
        }
      ]
```

Here, if I have to find the `listener_id` for a specific `object[0].script.id`, then I should get `object[0].listener_id`.
Basically, it should search for the provided key in the provided object in its all ancestors.
Let me know your thoughts over this. I would love to contribute to lodash!

**Comment by ankurnarkhede** [comment]
@falsyvalues @jdalton @sankargorthi  can you please comment over this?

**Comment by falsyvalues** [comment]
Hi @ankurnarkhede!

We already have [_.find](https://lodash.com/docs/4.17.15#find) and [_.findLast](https://lodash.com/docs/4.17.15#findLast) on board where You can provide own predicate.
