### ISSUE TITLE
Invalid result in findIndex

### ISSUE THREAD

**Issue by renjithspace** [lodash/lodash#4597]
### Code

```
const rates = [ 1, 2, 3, 4, 5 ]
const rating = 2
const ratingIndex = _.findIndex(rates, rating]
console.log(ratingIndex)
```

### Result
```
-1
```

### Expected result

```
1
```

**Comment by falsyvalues** [comment]
Hi @renjithspace!

You're looking for `_.indexOf`. See our [docs](https://lodash.com/docs/4.17.15#indexOf).

```js
>  _.indexOf([ 1, 2, 3, 4, 5 ], 2);
< 1
// or
> _.findIndex([ 1, 2, 3, 4, 5 ], v => v == 2);
< 1
```

**Comment by renjithspace** [comment]
Thanks. I guess it needs a little more clarification here.

1. The naming is little bit confusing with `Array.prototype.findIndex()`.
2. Why we put it in the `Array` group. It should be in `Collection` then, right?
3. Why we added `array` as first parameter to this method in the documentation. It should be a `collection`, right?

![array find index](https://user-images.githubusercontent.com/11629673/71354743-e7ac9b80-25a2-11ea-9e53-d8c482e10a3f.png)
