### ISSUE TITLE
Provides _.isNotEmpty() would be helpful

### ISSUE THREAD

**Issue by yeongjet** [lodash/lodash#4598]
That would be more readability than writing !_.isEmpty(), and in some case when pass _.isEmpty as parameter to a function and expect \_.isEmpty return a opposite value but you can not process in that function, you can't write !\_.isEmpty, it's very inconvenient.

**Comment by ZimGil** [comment]
IMO - There's no need for a function that returns the opposite `Boolean` than a function you already have.

As for passing a callback, you can always pass `((o) => !_.isEmpty(o))`

**Comment by yeongjet** [comment]
@ZimGil I'm using in this way but it's verbose..

**Comment by mathiswiehl** [comment]
Well you can just define it once as `const isNotEmpty = _.negate(_.isEmpty)` and everywhere you use it, it is exactly as verbose as if it were included. It even has to an `_.` less 😉.

**Comment by yeongjet** [comment]
@mathiswiehl Thanks! It's nearly perfect.

**Comment by falsyvalues** [comment]
Hi @yeongjet!

As @mathiswiehl suggested that's the way to go, we won't provide "not" version for each method.
