### ISSUE TITLE
I need a cartesian product

### ISSUE THREAD

**Issue by cumtchj** [lodash/lodash#4599]
It would be nice to have a cartesian product in the array algorithm

**Comment by MelvinVermeer** [comment]
This is a mathematical operation, have you looked at https://mathjs.org/docs/reference/functions/setCartesian.html ?

**Comment by falsyvalues** [comment]
Hi @cumtchj!

Take a look on #852 and add 👍

**Comment by cumtchj** [comment]
> This is a mathematical operation, have you looked at https://mathjs.org/docs/reference/functions/setCartesian.html ?

OK，thank you very much
