### ISSUE TITLE
How about add a _.updateBy func in collection?

### ISSUE THREAD

**Issue by moonrailgun** [lodash/lodash#4600]
Hi. I need a func which can find a item of array and try to set it.

The definition of `_.updateBy` should like:
```js
_.updateBy(collection, [predicate=_.identity], [updater=_.identity])
```

example:
```js
const collection = [{
  name: "Alexander Noyes",
  age: 17
}, {
  name: "Flora Rosa",
  age: 20
}, {
  name: "Ivy Wood",
  age: 24
}];

_.updateBy(collection, (item) => item.name === "Ivy Wood", (item) => ({
  name: item.name,
  age: 26
}))
  
// => [{
//   name: "Alexander Noyes",
//   age: 17
// }, {
//   name: "Flora Rosa",
//   age: 20
// }, {
//   name: "Ivy Wood",
//   age: 26
// }]
```

like `_.update` but use `predicate` to change all matched item in Collection.

Maybe should have a `_.setBy` to set value directly. which match `predicate`

If you think its a good idea. I can implement it by myself.

**Comment by jWpq9Oo6LAeh** [comment]
An implementation of this function would be: https://pastebin.com/G0TbrAvc.
**Remember that it's an unofficial function.** This is made by me for help you!

**Comment by moonrailgun** [comment]
@jWpq9Oo6LAeh Thanks for your code, you are very nice . Its just a proposal for me to add this implement to offical `lodash` because i think this very useful for us to modify list if we manage a large state, like `redux`

**Comment by asingh04** [comment]
Isn't `map` functionality already present in lodash? It could be used for the requirement you have raised.

**Comment by moonrailgun** [comment]
@asingh04  Its very hard to write code to implement it by a functional programming way.

At least i have no idea to write a beautify code to do same thing.

**Comment by asingh04** [comment]
@moonrailgun 
if going by your example, the same functionality can be easily implemented through `_.map`.

`
_.map(collection, (item) => {
    if ( item.name === "Ivy Name"){
        return { 
            name: item.name, 
            age: 26 
        };
    }
    return item;
});
`
I hope this is what you want to achieve.
Please correct me if I have understood wrongly what you intended.

**Comment by moonrailgun** [comment]
@asingh04 this is right code for my mind.

But we all know, lodash provide a functional programming way to write code and this very beautify. and that sorry your code is not functional programming enough, we should organizate our logic. 

We can write all code without lodash, but i think we should check whether this is a frequent requirement we should use.

Lodash have `_.update` to update object data with path. Its also can be write with:
```javascript
_.update(object, 'a[0].b.c', function(n) { return n * n; });
```
=>
```javascript
const val = _.get(object, 'a[0].b.c')
_.set(object, 'a[0].b.c', val * val)
```

Why not have `_.updateBy` apply into object array? In my mind, this more frequently scene.

**Comment by asingh04** [comment]
Okay, now I get it! 
Yup it does seems a functionality similar to what you have explained can be useful for achieving functional programming methodology.

**Comment by falsyvalues** [comment]
Hi @moonrailgun!

I think we have everything thats need to cover such case thru composition including [map](https://lodash.com/docs/4.17.15#map) and [update](https://lodash.com/docs/4.17.15#update) / [updateWith](https://lodash.com/docs/4.17.15#updateWith).
