### ISSUE TITLE
Why _.isString judge value isArray in it's source code?

### ISSUE THREAD

**Issue by tjx666** [lodash/lodash#4604]
[_.isString](https://github.com/lodash/lodash/blob/master/isString.js)

I think It is a useless step, is there any meaning?

![Snipaste_2020-01-01_15-55-47](https://user-images.githubusercontent.com/41773861/71639318-54b0e700-2caf-11ea-9908-c0ae1aac2191.png)

**Comment by jkvyff** [comment]
I believe they are just being wary of the inclusion of isString on `Array`.

As getTag looks like this:
```
function getTag(value) {
  if (value == null) {
    return value === undefined ? '[object Undefined]' : '[object Null]'
  }
  return toString.call(value)
}
```

If toString.call(value) were called on an array in some implementations it could be inferred as:
```
Array.prototype.toString.call(['a', 'b'])
> 'a,b'

// Instead of what we assume
Object.prototype.toString.call(['a', 'b'])
> '[object Array']
```

This would be incorrect and bad in the case of:
```
Array.prototype.toString.call(['[object String]']) == '[object String]'`
> true

Object.prototype.toString.call(['[object String]']) == '[object String]'`
> false
```

So best just to remove arrays and be safe....probably.

**Comment by zhoululu** [comment]
> I believe they are just being wary of the inclusion of isString on `Array`.
> 
> As getTag looks like this:
> 
> ```
> function getTag(value) {
>   if (value == null) {
>     return value === undefined ? '[object Undefined]' : '[object Null]'
>   }
>   return toString.call(value)
> }
> ```
> 
> If toString.call(value) were called on an array in some implementations it could be inferred as:
> 
> ```
> Array.prototype.toString.call(['a', 'b'])
> > 'a,b'
> 
> // Instead of what we assume
> Object.prototype.toString.call(['a', 'b'])
> > '[object Array']
> ```
> 
> This would be incorrect and bad in the case of:
> 
> ```
> Array.prototype.toString.call(['[object String]']) == '[object String]'
> > true
> 
> Object.prototype.toString.call(['[object String]']) == '[object String]'
> > false
> ```
> 
> So best just to remove arrays and be safe....probably.

but，toString is Object.prototype.toString in getTag.js.  Array.prototype.toString It doesn't exist

![getTag](https://user-images.githubusercontent.com/11639934/91634856-34941c00-ea26-11ea-8ce7-4a877c535155.PNG)
