### ISSUE TITLE
"lodash-es" has no exported member "Directory"

### ISSUE THREAD

**Issue by light0x00** [lodash/lodash#4609]
For tree-shaking, I use lodash-es. But it doesn't seem to export some members. Currently, I use `groupBy`, but I can't get the type `Directory` of return.  

![image](https://user-images.githubusercontent.com/29830476/71780759-8c969200-3001-11ea-812c-09ded7f7773f.png)

![image](https://user-images.githubusercontent.com/29830476/71780716-febaa700-3000-11ea-8fb9-ca6a75f28997.png)

![image](https://user-images.githubusercontent.com/29830476/71780720-0b3eff80-3001-11ea-8cef-8ca6beafa627.png)

**Comment by falsyvalues** [comment]
Hi @light0x00!

This discussion should definitely go to ➡️[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) contributors of [@types/lodash-es](https://www.npmjs.com/package/@types/lodash-es) will help for sure.
