### ISSUE TITLE
Deep clone fails for function objects

### ISSUE THREAD

**Issue by RichardHoOoOo** [lodash/lodash#4610]
Deep clone fails when I try to clone a function object.

```
var a = function(){console.log("123");};
var b = _.cloneDeep(a);
b();
```

Error message:
```
TypeError: b is not a function. (In 'b()', 'b' is an instance of Object)
```

But when I wrap a function into an object like this:
```
var a = {
    	fun: function(){console.log("123");}
};
var b = _.cloneDeep(a);
b.fun();
```
It can successfully output 123.
So there seems to be a bug in cloneDeep when a single function object is to be cloned.

**Comment by jkvyff** [comment]
It looks like you are trying to run deepClone on a function rather than on an object resulting from a function.
Perhaps you want something like this:
```
var a = function(){console.log("123");};
var b = _.cloneDeep(new a);
```
or
```
var a = function(){console.log("123");};
var b = _.cloneDeep(a());
```
Otherwise, check the documentation for clone and you will find that functions themselves are unsupported and will return an empty object for both clone and CloneDeep.

**Comment by tangdingga1** [comment]
> It looks like you are trying to run deepClone on a function rather than on an object resulting from a function.
> Perhaps you want something like this:
> 
> ```
> var a = function(){console.log("123");};
> var b = _.cloneDeep(new a);
> ```
> 
> or
> 
> ```
> var a = function(){console.log("123");};
> var b = _.cloneDeep(a());
> ```
> 
> Otherwise, check the documentation for clone and you will find that functions themselves are unsupported and will return an empty object for both clone and CloneDeep.

Hi, can you add a function type into deepClone supports? I also find this problem in my project.
Maybe can use `eval` or `new Function` to resolve it.sorry, My English is not good,I hope you can understand what I said.

**Comment by ruojianll** [comment]
https://lodash.com/docs/4.17.15#clone
Clone function will return an empty object.

**Comment by YuriGor** [comment]
To clone objects with methods you can use [cloneWith](https://lodash.com/docs/4.17.15#cloneWith) or [cloneDeepWith](https://lodash.com/docs/4.17.15#cloneDeepWith) and handle function values by yourself (copy by reference or recreate from string sources)

**Comment by YuriGor** [comment]
Also notice there is kind of [officially ignored bug](https://github.com/lodash/lodash/issues/4781)
when you clone function directly - you will get an empty object as a result.
But when you clone some object with functions inside - cloneDeep will copy these functions by reference.
