### ISSUE TITLE
Add an _.assignOnly method [Feature request][Code proposal]

### ISSUE THREAD

**Issue by danielsum** [lodash/lodash#4611]
# Description of the expected behavior

This method will be like an Object.assign except that it accept only 1 source of copy and have instead a third parameter that will filter only the properties that needs to be assigned. If the third parameter is empty, by default it will only assign the properties of the first parameter object.

# Use cases

This could be really useful when you need to copy only particular properties and prevent to copy other properties and avoid like that "prototype like pollution".

```
function Foo() {
   this.a = 1;
   this.b = 1
}
 
function Bar() {
  this.a = 2;
  this.b = 2;
  this.c = 2;
}
 
Foo = _.assignOnly(Foo, Bar, [a]);
// => Foo = { 'a': 2, 'b': 1 }

Foo = _.assignOnly(Foo, Bar, [a,c]);
// => Foo = { 'a': 2, 'b': 1 ,"c":2}

Foo = _.assignOnly(Foo, Bar);
// => Foo = { 'a': 2, 'b': 2}
```

# Code proposal : 

```
var pick = require('./pick');

/**
 * This method is like `_.assign` except that the third parameter is an array of properties to copy or if is null it will assign only the properties of the first object parameter.
 *
 * @static
 * @since xxxx
 * @memberOf _
 * @category Object
 * @param {Object} object The source object.
 * @param {Object} objectToCopy The object to copy
 * @param {Array} arrayKeysToCopy An array of properties keys to copy
 * @returns {Object} Returns the new object.
 * @example
 *
 * var object = { a: 1, b: 1 };
 * var object2 = { a: 2, b: 2, c: 2 };
 *
 * _.assignOnly(object, object2);
 * // => {a: 2, b:2}
 *
 * _.assignOnly(object, object2; [a,c]);
 * // => {a: 2, b:1,c:2}
 */
var assignOnly = function(object, objectToCopy, arrayKeysToCopy) {

  if (!arrayKeysToCopy) {
    arrayKeysToCopy = Object.keys(object);
  }

  return Object.assign(object, _.pick(objectToCopy, arrayKeysToCopy));
}

module.exports = assignOnly;
```

**Comment by bnjmnt4n** [comment]
Since this is a simple combination of _.assign and _.pick, and can be easily composed with a one liner, I'd like to defer from adding this to lodash.

**Comment by danielsum** [comment]
I think it's much more than 2 simple combinations, actually 3 because most of the times you have to write : 

Object.assign(object, _.pick(objectToCopy, Object.keys(object)); 

And it solve that kind of cumbersome problem : https://stackoverflow.com/questions/40573555/merge-two-objects-but-only-existing-properties, https://stackoverflow.com/questions/57780961/how-to-prevent-prototype-pollution-in-javascript

As a very common pattern and problem (with the "prototype pollution" : [https://portswigger.net/daily-swig/prototype-pollution-the-dangerous-and-underrated-vulnerability-impacting-javascript-applications](https://portswigger.net/daily-swig/prototype-pollution-the-dangerous-and-underrated-vulnerability-impacting-javascript-applications) ) and typically used in a copy of values (for exemple in a form). 

For me it's worst to add it and avoid headache/bugs for multiple developers around the world. I'm a CTO and have seen a lot of wrong object copy, method conflicts with the prototype pollution vulnerability when a junior try to assign values to an other object.

There are other one liner in lodash : https://github.com/lodash/lodash/blob/master/capitalize.js but sometimes avoiding remembering this one liner may save times or here prevent some bugs/vulnerabilities.
