### ISSUE TITLE
unescape method is ignoring &nbsp;

### ISSUE THREAD

**Issue by ermarkar** [lodash/lodash#4612]

**Comment by omkar-joshi** [comment]
I'd like to help with this

**Comment by ermarkar** [comment]
@omkar-joshi yeah please

**Comment by omkar-joshi** [comment]
Sure. On it!

**Comment by omkar-joshi** [comment]
I've opened a PR for this - #4616 Can anyone please look into it?

**Comment by falsyvalues** [comment]
Hi @ermarkar!

`_.unescape` is the inverse of `_.escape` and `_.escape` doesn't handle `&nbsp;`.
