### ISSUE TITLE
High Vulnerability Prototype Pollution

### ISSUE THREAD

**Issue by Serotonn** [lodash/lodash#4628]
=== npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   gym

  Path            gym > lodash

  More info       https://npmjs.com/advisories/577

  High            Prototype Pollution

  Package         lodash

  Patched in      >=4.17.11

  Dependency of   gym

  Path            gym > lodash

  More info       https://npmjs.com/advisories/782

  High            Prototype Pollution

  Package         lodash

  Patched in      >=4.17.12

  Dependency of   gym

  Path            gym > lodash

  More info       https://npmjs.com/advisories/1065

found 3 vulnerabilities (1 low, 2 high) in 452 scanned packages
  3 vulnerabilities require manual review. See the full report for details.

**Comment by mathiswiehl** [comment]
Well all of theses are patched in lodash it looks like [gym](https://www.npmjs.com/package/gym) should update their lodash dependency, or what do you mean with this post?
