### ISSUE TITLE
Importing multiple methods from lodash-es in the same file

### ISSUE THREAD

**Issue by MariusVatasoiu** [lodash/lodash#4631]
I'm facing an issue when I want to import multiple methods from `lodash-es`. I want to import the methods like below, because I want to be sure that the tree shaking is working.

```javascript
import isBoolean from 'lodash-es/isBoolean';
import isEmpty from 'lodash-es/isEmpty';
import isUndefined from 'lodash-es/isUndefined';
```

Importing like this I get this error:

```
Uncaught RangeError: Maximum call stack size exceeded
    at baseGetTag (_baseGetTag.js:19)
```

If I import multiple methods from `lodash` or only one method from `lodash-es` (like below), everything works **correctly**. 
```javascript
import isBoolean from 'lodash/isBoolean';
import isEmpty from 'lodash/isEmpty';
import isUndefined from 'lodash/isUndefined';
```
or
```javascript
import isBoolean from 'lodash-es/isBoolean';
```

I use version **4.17.15**.

**Comment by atilkan** [comment]
Just a note for other people who come here from google. 

`import { isBoolean, debounce } from 'lodash-es'`
