### ISSUE TITLE
What about a conditional caller?

### ISSUE THREAD

**Issue by mathesouza** [lodash/lodash#4633]
My idea is to have a function that calls a callback when condition is true.
e.g.:
```
when(true, () => console.log('Hello world')) - Hello world
when(false, () => console.log('Hello world')) - Nothing happen
```
If you like the idea, i can work on it :)

**Comment by falsyvalues** [comment]
Hi @mathesouza!

We already have proposal for that, please take a look on #1072 #3199 #3581
