### ISSUE TITLE
Wording in documentation of collection methods: "objects for" 

### ISSUE THREAD

**Issue by Catspyjamas** [lodash/lodash#4634]
I just looked up `sortBy()` in the documentation and stumbled on the term "objects for..." in the code example:
<img width="798" alt="Bildschirmfoto 2020-01-22 um 13 42 08" src="https://user-images.githubusercontent.com/5295667/72895111-0080ac00-3d1d-11ea-9f2e-abd82e7e7b18.png">

But if this...
```
var users = [
  { 'user': 'fred',   'age': 48 },
  { 'user': 'barney', 'age': 36 },
  { 'user': 'fred',   'age': 40 },
  { 'user': 'barney', 'age': 34 }
];
_.sortBy(users, ['user', 'age']);
```
... creates a sorted array with four objects:
`// => [{age: 34, user: "barney"}, {age: 36, user: "barney"}, {age: 40, user: "fred"}, {age: 48, user: "fred"}]`
... Don't you agree that the way it's spelled out the docs is a bit of a puzzle?
`// => objects for [['barney', 34], ['barney', 36], ['fred', 40], ['fred', 48]]`

I got so confused by the term "objects for", followed by an array of arrays that I considered opening a pull request, but a quick search showed that the same wording is used in the corresponding collection examples (e.g. `filter()`,`orderBy()` or `partition()`), but not in the array examples (`differenceBy()`, `pullAllWith()`), so it seems to be on purpose. Now I'm curious what's the reason for that? Sorry If I misunderstood, or if this is nitpicking, I'm new here... :)

**Comment by falsyvalues** [comment]
Hi @Catspyjamas!

It's a shorthand which allow us omitting object notation in each example to expose what is important there, the result.
