### ISSUE TITLE
Lodash type errors when build with typescript in NodeJS

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [lodash/lodash#4635]
Hello,

I am using lodash in nodeJS express app, but when I build the project, I get type errors in terminal of lodash methods.

```
src/api/customer/customer.controller.ts:225:75 - error TS2345: Argument of type 'unknown[]' is not assignable to parameter of type 'number[]'.
  Type 'unknown' is not assignable to type 'number'.

225   let status: any = await customerRepsoitory.deleteCustomer(customerIdList);
                                                                              ~~~~~~~~~~~~~~

src/repository/mariaDB/products/product.repository.ts:541:160 - error TS2339: Property 'fieldId' does not exist on type '{ toString: () => string; charAt: (pos: number) => string; charCodeAt: (index: number) => number; concat: (...strings: string[]) => string; indexOf: (searchString: string, position?: number) => number; ... 39 more ...; trimRight: () => string; }'.

541           const insertImage: any = await connection.query(`insert into product_images (product_id, field_id) values (${productDetails.productId}, ${groupId[m].fieldId})`);
                                                                                                                                                                   ~~~~~~~

src/repository/mariaDB/products/product.repository.ts:543:71 - error TS2339: Property 'fieldId' does not exist on type '{ toString: () => string; charAt: (pos: number) => string; charCodeAt: (index: number) => number; concat: (...strings: string[]) => string; indexOf: (searchString: string, position?: number) => number; ... 39 more ...; trimRight: () => string; }'.
```

```
NodeJS - v11.15.0
NPM - 6.7.0
```

I have imported lodash like
`import { isEmpty, uniq } from 'lodash';`

tsconfig.json

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "*": ["types/*"] },
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
            "es2015"
        ],
        "outDir": "./dist/",
        "rootDir": "./",
    },
    
}
```

package.json
```{
  "name": "hd.nodejsapi",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "clean-dist": "./node_modules/.bin/gulp",
    "prebuild": "npm run clean-dist",
    "build": "tsc server.ts --lib ES2015 --outDir dist",
    "start": "node dist/server.js",
    "test": ""
  },
  "author": "Self",
  "private": true,
  "dependencies": {
    "@sendgrid/mail": "^6.3.1",
    "@types/node": "^10.9.4",
    "@types/request": "^2.47.1",
    "async": "^2.6.1",
    "async-request": "^1.2.0",
    "base-64": "^0.1.0",
    "bcrypt": "^3.0.2",
    "body-parser": "^1.18.3",
    "bull": "^3.9.1",
    "compression": "^1.7.3",
    "cors": "^2.8.4",
    "csv-parser": "^2.2.0",
    "dotenv": "^6.2.0",
    "exchange-rates": "^0.1.2",
    "express": "^4.16.4",
    "express-fileupload": "^0.4.0",
    "express-useragent": "^1.0.12",
    "fs-extra": "^6.0.1",
    "gm": "^1.23.1",
    "http": "0.0.0",
    "is-base64": "0.0.4",
    "jimp": "^0.2.28",
    "joi": "^14.0.1",
    "jsonwebtoken": "^8.3.0",
    "lib": "^3.0.2",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "mongoose": "^5.4.5",
    "morgan": "^1.9.0",
    "msg91-sms": "^1.0.1",
    "multer": "^1.4.1",
    "mv": "^2.1.1",
    "mysql": "^2.16.0",
    "node-datetime": "^2.1.0",
    "node-fetch": "^2.2.0",
    "nodemailer": "^4.6.8",
    "numeral": "^2.0.6",
    "promise": "^8.0.1",
    "request": "^2.81.0",
    "ts-node": "^7.0.1",
    "typescript": "^3.1.1",
    "util": "^0.11.0"
  },
  "devDependencies": {
    "@types/lodash": "^4.14.149",
    "gulp": "^4.0.0",
    "gulp-clean": "^0.4.0",
    "@types/node-fetch": "^2.1.2",
    "nodemon": "^1.18.4"
  }
}
```

been stuck in it for nearly 6-8 hours, tried with upgrading/downgrading node, typescript, lodash, but still the issue persists.

all help would be greatly appreciated...

Thanks

**Comment by ysmanohar** [comment]
Did you install type declaration for lodash?
Check this article: https://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html

**Comment by ishaqueahmed-mev** [comment]
@ysmanohar, yes already added the @types/lodash declaration as you can also see in the package.json description, but still facing the issue. I think it may be some version issue with typescript or something, I tried with changing versions also, still nothing.

**Comment by ysmanohar** [comment]
I dont see a '@types/lodash' in package.json that you posted

**Comment by ishaqueahmed-mev** [comment]
oh yeah sorry, I actually added in my code after posting here and doing some research, but still the issue persists, I'll update the description...

**Comment by ysmanohar** [comment]
Can you please post the corresponding code. I'm not able to guess why is throwing that error.

**Comment by ishaqueahmed-mev** [comment]
this is the code which shows issues

```
import { isEmpty, uniq } from 'lodash';

const customerIdList = uniq(validator.value.customerIds);
let status: any = await customerRepsoitory.deleteCustomer(customerIdList);
```
the **validator.value.customerIds** is an array value from API
the deleteCustomer method is called from another file like
```
deleteCustomer(custmomerIds: number[]): Promise<DeleteResponse>;
```
this is just a single part from a single file, am getting almost similar errors in other files as well, wherever the lodash methods are used, also they **work fine if I replace them with normal JS array methods** 

when I do npm run build, this is the error I get in console

```
src/api/customer/customer.controller.ts:225:75 - error TS2345: Argument of type 'unknown[]' is not assignable to parameter of type 'number[]'.
  Type 'unknown' is not assignable to type 'number'.

225                 let status: any = await customerRepsoitory.deleteCustomer(customerIdList);
```

Thanks.

**Comment by ysmanohar** [comment]
May be try this:
const customerIdList: number[] = uniq(validator.value.customerIds);
if(!isEmpty(customerIdList)){
let status: any = await customerRepsoitory.deleteCustomer(customerIdList);
}

**Comment by ishaqueahmed-mev** [comment]
yes it works when I change the types, and I have already tried it before, but the issue is we are working as a team of around 6 developers, all with the same code, not just node, but also in angular, and in everyone's system, its working fine, but mine's throws error on both side, node and angular wherever lodash is being used, and as I described if I changes it to normal array it works fine, but I can't change or convince my colleagues for the change, as they are running it without any trouble.

Thanks.

**Comment by falsyvalues** [comment]
Hi @ishaqueahmed-mev!

Looks like your code is missing some typings for `validator.value.customerIds`. Discussion related to `@types/lodash` should go to ➡️[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) contributors of [@types/lodash](https://www.npmjs.com/package/@types/lodash) because we are not authors of type declarations.

**Comment by CanKattwinkel** [comment]
Adding this did the trick for me:

```
    "typeRoots": [
      "node_modules/@types"
    ]
```

(along making sure that `@types/lodash` was actually installed)
