### ISSUE TITLE
RunKit REPL runner hangs

### ISSUE THREAD

**Issue by MareoRaft** [lodash/lodash#4638]
I had this issue a few weeks ago and I still have this issue today.  I think this issue has persisted for some time.  The RunKit REPL remains frozen indefinitely.

<img width="1083" alt="Screen Shot 2020-01-24 at 11 55 55 AM" src="https://user-images.githubusercontent.com/860303/73087593-baecec00-3ea0-11ea-9db2-360328f14990.png">

I have tried this on both Google Chrome and Firefox with the same results.

**Comment by fernandolujan** [comment]
Currently not sure if it's an issue with RunKit or the lodash documentation implementation of it. I'm getting weird behaviour as well, though slightly different than yours @MareoRaft.

When first opening RunKit, it seems to insert a bunch of special characters into the input. My guess is this is an encoding issue. e.g:
```
varÂ usersÂ =Â [
Â Â {Â 'user':Â 'fred',Â Â Â 'age':Â 48Â },
Â Â {Â 'user':Â 'barney',Â 'age':Â 36Â },
Â Â {Â 'user':Â 'fred',Â Â Â 'age':Â 40Â },
Â Â {Â 'user':Â 'barney',Â 'age':Â 34Â }
];
Â 
_.sortBy(users,Â [function(o)Â {Â returnÂ o.user;Â }]);
//Â =>Â objectsÂ forÂ [['barney',Â 36],Â ['barney',Â 34],Â ['fred',Â 48],Â ['fred',Â 40]]
Â 
_.sortBy(users,Â ['user',Â 'age']);
//Â =>Â objectsÂ forÂ [['barney',Â 34],Â ['barney',Â 36],Â ['fred',Â 40],Â ['fred',Â 48]]
```

Then, when attempting to _run_ the example, I get:
`ReferenceError: _ is not defined`

**Comment by ghoshabhi** [comment]
I too see this:

![orderby_lodash_bug](https://user-images.githubusercontent.com/19292575/73484662-9092a700-4356-11ea-91d5-43f9837c3785.png)

**Comment by falsyvalues** [comment]
Hi @MareoRaft!

The RunKit REPL is working fine (at least for me), maybe the having some minor issues during that time. You can try to reach out @runkitdev team.
