### ISSUE TITLE
"Try in REPL" does not work in Google Chrome 79 or 80, Mac OS X 10.15.3

### ISSUE THREAD

**Issue by charleskoehl** [lodash/lodash#4640]
When I click "Try in REPL" on any function in Google Chrome 79 or 80 on OS X 10.15.3, the output looks like the following image. This does **not** happen in Safari Version 13.0.5 (15608.5.11).

![image](https://user-images.githubusercontent.com/887025/73816281-5842fc80-478c-11ea-957b-9b581e9aea8f.png)

Google Chrome 80.0.3987.87 (Official Build) (64-bit) (and also v 79)

**Comment by manveers96** [comment]
I'm facing similar issues +1

**Comment by falsyvalues** [comment]
Hi @charleskoehl!

We're aware of that, the right place for website related issues is [lodash/lodash.com](https://github.com/lodash/lodash.com).

**Comment by charleskoehl** [comment]
Turns out it works in Chrome incognito mode. Must be one of my extensions.

**Comment by charleskoehl** [comment]
Created https://github.com/lodash/lodash.com/issues/220 for this issue.
