### ISSUE TITLE
Avoid _.memoize multi-agruments functions using mistakes without resolver

### ISSUE THREAD

**Issue by shyr1punk** [lodash/lodash#4641]
I think `_.memoize` function have a design problem. Nobody read the docs. Nobody knows how `_.memoize` actually works. And we have a tons of bugs with multi-arguments functions.

I suggest fix for this problem: we should add check for multiply arguments functions without resolvers. Something like this (this is how we avoid this problem):

```
export const memoize: MemoizationFunction = (func, resolver?) => {
    if (!resolver) {
        if (func.length > 1) {
            console.warn('For memoized function with 2+ arguments use resolver function as second argument. See https://lodash.com/docs/4.17.15#memoize');
        }

        return m(func);
    }

    return m(func, resolver);
};
```

This is may be not an `Error`, just `console.error|warn`. But users should know about potential bug in theirs code.

What you think about it?

**Comment by shyr1punk** [comment]
https://github.com/lodash/lodash/issues/4583
https://github.com/lodash/lodash/issues/2115

**Comment by ahfarmer** [comment]
Why print a warning when we could legitimately fix the issue with nested Maps as I suggested in #2115 ?

**Comment by bnjmnt4n** [comment]
Being a low-level utility library, we want to avoid pollution of the global context. lodash has never utilized console logging, and is unlikely to do so in the future. In this case, providing a warning when invoking a memoized function with more than two arguments seems like a perfect use case for a linting plugin.

**Comment by olejorgenb** [comment]
Yeah, I would much prefer if `memoize((a, b) => b)(1,2)` crashed than silently causing bugs.. I've never come across a memoize implementation that behaves like this..
