### ISSUE TITLE
[Website] repl editor overflows the screen

### ISSUE THREAD

**Issue by MikeYermolayev** [lodash/lodash#4647]
Code editor overflows the screen

![image](https://user-images.githubusercontent.com/8783498/74232217-625b8280-4cd9-11ea-881d-9ecb635cf25b.png)

Looks like this is caused by thee negative margin
![image](https://user-images.githubusercontent.com/8783498/74232260-78694300-4cd9-11ea-9fb3-2426d899c8d3.png)

**Comment by falsyvalues** [comment]
Hi @MikeYermolayev!

We're aware of that  and other REPL related issues, the right place for website related issues is [lodash/lodash.com](https://github.com/lodash/lodash.com).
