### ISSUE TITLE
_.debounce().flush() fix never made it into produciton

### ISSUE THREAD

**Issue by TeaSeaLancs** [lodash/lodash#4648]
Hi lodash team,

Having been tracing an issue through my codebase, I discovered that running `flush` on a debounced function doesn't clear any timeouts.

There was a pull request raised a few years ago for this, https://github.com/lodash/lodash/pull/4078, which was merged, however those fixes don't seem to have made it into production, as can be evidenced at:

https://github.com/lodash/lodash/blob/4d5fdc492feabf6406dd37e5e843a1261414cbf8/debounce.js (esm version of 4.17.15)

https://github.com/lodash/lodash/blob/15e1557b2a97c8bbee22d873832d90ed3ba50ba7/debounce.js (latest update to debounce.js which is in master at time of writing)

I could re-raise this as a PR but was wondering if there was a reason why the fix never made it in?

**Comment by falsyvalues** [comment]
Hi @TeaSeaLancs!

Thanks for catching this I will address that #4656.
