### ISSUE TITLE
lodash.core implementation of `arrayPush` throws for big arrays in browsers

### ISSUE THREAD

**Issue by dianabarsan** [lodash/lodash#4649]
Looking at version `4.17.15`. 
The implementation of `arrayPush` in `lodash.core` is
```
function arrayPush(array, values) {
  array.push.apply(array, values);
  return array;
}
```

Unfortunately. `array.push.apply` throws a `Range error` in Chrome when the source array has more than ~130k elements:
```
[].push.apply([], Array.from({ length: 200000 }).map(() => 'a'));
```
![image](https://user-images.githubusercontent.com/35681649/74317597-67294080-4d84-11ea-9587-b945a62a5b85.png)

Firefox starts to throw at about 600k elements: 
![image](https://user-images.githubusercontent.com/35681649/74317653-7b6d3d80-4d84-11ea-83cd-5ab3fcc53a95.png)

 

The implementation in `lodash` main is:
```
function arrayPush(array, values) {
    var index = -1,
        length = values.length,
        offset = array.length;

    while (++index < length) {
      array[offset + index] = values[index];
    }
    return array;
  }
```
which does not crash in browsers when pushing very long arrays.

**Comment by falsyvalues** [comment]
Hi @dianabarsan!

I'm not sure what you're referring to when speaking `lodash.core`, here is our [arrayPush ](https://github.com/lodash/lodash/blob/4.17.15-post/lodash.js#L652) implementation in latest release `v4.17.15`.

**Comment by dianabarsan** [comment]
I'm talking about the packaged file that you get when requiring with 
```
var _ = require('lodash/core');
```

**Comment by dianabarsan** [comment]
I just checked again - opened the `core.js` file, checked the version (`var VERSION = '4.17.15';`) and checked the implementation of `arrayPush`:
```
function arrayPush(array, values) {
    array.push.apply(array, values);
    return array;
  }
```

Please don't dismiss this without

**Comment by falsyvalues** [comment]
@dianabarsan No worries it won't be dismissed.

@jdalton Take a look, since Im not aware of source of this (npm branch).
