### ISSUE TITLE
Lodash website "Try in REPL" widget is borked

### ISSUE THREAD

**Issue by adamhamlin** [lodash/lodash#4651]
Didn't see anywhere to address this on the website itself, so posting here.

These are before and after pictures when clicking on the `Try in REPL` button:
<img width="1438" alt="Screen Shot 2020-02-12 at 2 45 51 PM" src="https://user-images.githubusercontent.com/18332856/74371446-d4e66400-4da6-11ea-942e-6e00bf83fad0.png">
<img width="1437" alt="Screen Shot 2020-02-12 at 2 46 06 PM" src="https://user-images.githubusercontent.com/18332856/74371452-d879eb00-4da6-11ea-8bb8-76627abd3956.png">

If you delete all that crap, you can still sort of use it, but the layout remains jacked up/cut off.

Saw this on Chrome and Firefox

**Comment by falsyvalues** [comment]
Hi @adamhamlin!

We're aware of that  and other REPL related issues, the right place for website related issues is [lodash/lodash.com](https://github.com/lodash/lodash.com).
