### ISSUE TITLE
Is _.random() generates random numbers in normal distribution or uniform distribution?

### ISSUE THREAD

**Issue by 1isten** [lodash/lodash#4653]
I'm seeking for a simple solution to generate normal distributed random number in JavaScript. According to [this](https://stackoverflow.com/a/25582948/10222165), the built-in `Math.random()` generates uniform distributed random numbers. Just wanna know if lodash's `_.random()` generates random numbers in normal distribution or uniform distribution, or else?

**Comment by ysmanohar** [comment]
_.random() is internally using Math.random to generate a random number. So it will give a uniform distribution. If you are looking for normal distribution, give a try according to this article:
https://riptutorial.com/javascript/example/8330/random--with-gaussian-distribution

**Comment by 1isten** [comment]
> _.random() is internally using Math.random to generate a random number. So it will give a uniform distribution. If you are looking for normal distribution, give a try according to this article:
> https://riptutorial.com/javascript/example/8330/random--with-gaussian-distribution

Thank you. I also just checked the `random.js` source code (I should have checked it before opening this issue 😅...) and it is using Math.random. Anyway, I decided to use [Box–Muller transform](https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform) to convert uniform distribution to normal distribution.
