### ISSUE TITLE
_.get() has trouble with stringified JSON as property path when using dot notation

### ISSUE THREAD

**Issue by jewbetcha** [lodash/lodash#4654]
```javascript
const obj = {
  foo: {
    '{"someProp":"{"someOtherProp":["someArray"],"anotherProp":{"foo":"bar"}}}': 'value'
  }
}


console.log(_.get(obj, 'foo.{"someProp":"{"someOtherProp":["someArray"],"anotherProp":{"foo":"bar"}}}'))
console.log(_.get(obj, `foo.['{"someProp":"{"someOtherProp":["someArray"],"anotherProp":{"foo":"bar"}}}']`))
console.log(_.get(obj, ['foo', '{"someProp":"{"someOtherProp":["someArray"],"anotherProp":{"foo":"bar"}}}']))
// undefined
// 'value'
// 'value'
```

https://jsbin.com/kocilobiru/edit?html,js,output

**Comment by YuriGor** [comment]
`foo.{"someProp":"{"someOtherProp":["someArray"],"anotherProp":{"foo":"bar"}}}'))`
this is not a correct path. 
Path string should be same as you would access this value just in js code:
You can use dot notation only for variable-like field names `/^[a-zA-Z_$]+([\w_$]*)$/`
if field name doesn't fit this requirement - you should use square brackets and enclose field name into quotes (if it's not just integer)
`foo['{"someProp":"{"someOtherProp":["someArray"],"anotherProp":{"foo":"bar"}}}\'))']`

**Comment by bnjmnt4n** [comment]
For complex property names, you can pass an array of each nested property name as you've done in `console.log(_.get(obj, ['foo', '{"someProp":"{"someOtherProp":["someArray"],"anotherProp":{"foo":"bar"}}}']))`.
