### ISSUE TITLE
Capped iteratees on lodash FP

### ISSUE THREAD

**Issue by Jeezy8** [lodash/lodash#4660]
Im wondering why the default behaviour of lodash fp's `reduce` is to cut the iteratee's arguments down to two. I often run into scenarios where i need the key or index on the iteration.

is it common to do a `convert({ cap: false })` and if so should this be done i a file once and then imported, or is it fine performance wise to always go `reduce.convert(...` when i need it?

Also when i do the conversation as illustrated below, the included typescript types dont work anymore, as they dont include the third and fourth argument of reduces iteratee:

```
import baseReduce from 'lodash/fp/reduce';

const getUncappedFn = <T extends Function>(fn: T) =>
  (fn as any).convert({ cap: false }) as T;

export const reduce = getUncappedFn(baseReduce);
```

Thanks for your help

**Comment by czabaj** [comment]
Apologise for such a strong statement, but I think the `cap` feature causes more harm than good. IMHO it is better to explicitly write `map(unary(cb))` then imply all functions would want to `cap`. It makes all iteration functions near useless for object, and I have to use convert very often.

**Comment by daedalus28** [comment]
@czabaj I agree 100% - and as supporting evidence, that's why many of the most commonly imported methods from [`futil-js`](https://github.com/smartprocure/futil-js) end up being our lodash conversions, which simple `cap:false` https://github.com/smartprocure/futil-js/blob/master/src/conversion.js
