### ISSUE TITLE
`orderBy` documentation

### ISSUE THREAD

**Issue by Crisfole** [lodash/lodash#4668]
It works (currently) to pass a single string, function, or object as the iteratees, and a single string for 'asc' or 'desc' like so:

```
const sorted = orderBy(unsorted, 'property', 'desc');
```

This is undocumented. Either this shortcut should be documented somehow, or it should fail. I vote documented.

Coincidentally, I'm unsure how using an object as an iteratee would work, but I'd love to learn (without having to read the source, which is what I'm about to do anyway). Adding top level documentation on the ways iteratees work would be nice...Actually, how having poked through the actual code I'm still unclear how that's legal.

**Comment by Jock924491** [comment]
Agreed, none of the iteratee shorthand usages are documented in the jsdoc. 

Currently the values are 
`@param {Function} [predicate=_.identity] The function invoked per iteration.`

Where it would make more sense to be something like.
`@param {Function|String|object|[]} [predicate=_.identity] The function invoked per iteration.`
