### ISSUE TITLE
Round error

### ISSUE THREAD

**Issue by k1ngdav1d** [lodash/lodash#4670]
Hi, I have found a bug about rounding. Specifically, the _.round function does not handle the rounding of negative numbers with decimals well.

Click the link below.
https://codesandbox.io/s/lodash-sandbox-xn6rm

**Comment by gibson042** [comment]
If you check the same results for related values, you will see that `_.round` behavior matches `Math.round` for analogous cases: https://codesandbox.io/s/lodash-sandbox-hcm05 .
And `Math.round` is [specified](https://tc39.es/ecma262/#sec-math.round) to round half values towards positive infinity (a.k.a. "[round half up](https://en.wikipedia.org/wiki/Rounding#Round_half_up)"), which is precisely what I observe of `_.round`.

**Comment by falsyvalues** [comment]
Hi @k1ngdav1d!
See #4529 for more and [Math.round](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round) docs on MDN.

**Comment by k1ngdav1d** [comment]
Hi, in the meantime, thank you all. I know the Math.round function but I didn't know that _.round depended on it. However, rounding is wrong with both Math.round and _.round (probably depends on Math.round but honestly I have not seen). The negative number -1.585 should become rounded to -1.59 and not -1.58.

**Comment by gibson042** [comment]
The Lodash behavior inherited directly from JavaScript isn't wrong, but it doesn't match the away-from-zero/towards-infinity behavior of many other languages. However, it is not hard to create your own arbitrary rounding functions [just like Lodash](https://github.com/lodash/lodash/blob/377e2d87c88893a8a1e4e3cd04da5a8893ea7a7b/.internal/createRound.js):
```js
function createRound(func = Math.round) {
  if ( typeof func !== "function" ) {
    func = Math[func];
  }
  return (number, precision) => {
    number = +number;
    precision = precision == null ? 0 : Math.max(Math.min(precision, 292), -292);
    if (precision && isFinite(number)) {
      // Shift with exponential notation to avoid floating-point issues.
      let pair = `${number}e`.split('e')
      const value = func(+`${pair[0]}e${+pair[1] + precision}`)

      pair = `${value}e`.split('e')
      return +`${pair[0]}e${+pair[1] - precision}`
    }
    return func(number)
  }
}

roundTiesTowardsInfinity = createRound(x => Math.sign(x) * Math.floor(Math.abs(x) + 0.5));
[-1.595, -1.594, -1.589, -1.585, -1.584, -1.579, 0, 1.579, 1.584, 1.585, 1.589, 1.594, 1.595].map(x => roundTiesTowardsInfinity(x, 2));
// → [ -1.6, -1.59, -1.59, -1.59, -1.58, -1.58, 0,  1.58,  1.58, 1.59,  1.59,  1.59, 1.6 ]

roundTiesToEven = createRound(x => Math.abs(x % 1) !== 0.5 ? Math.round(x) : (+x + Number(x>0)) & ~1);
[-1.595, -1.594, -1.589, -1.585, -1.584, -1.579, 0, 1.579, 1.584, 1.585, 1.589, 1.594, 1.595].map(x => roundTiesToEven(x, 2));
// → [ -1.6, -1.59, -1.59, -1.58, -1.58, -1.58, 0,  1.58,  1.58, 1.58,  1.59,  1.59, 1.6 ]
```
