### ISSUE TITLE
中文版的页面是否能优化下?

### ISSUE THREAD

**Issue by lifetin** [lodash/lodash#4672]
https://www.lodashjs.com/
1,这个网站,点击侧边某个函数或方法时,页面滚动条是否能停留在当前查看的位置?
比喻我正在看这个方法_.debounce(func, [wait=0], [options={}])
但是左边的滚动条跑到上面去了, 导致我不会查看同类的相关方法,必须重新在左边拉动滚动条!
一个体验问题.做页面的人应该能考虑啊

2,还能搜索方法也有问题,搜不了

这个网站上没有留言的,也没有反馈的.只能在这里提下问题.

**Comment by lifetin** [comment]
![44](https://user-images.githubusercontent.com/10474968/75106791-13a7d400-565b-11ea-94a9-775179406b7f.png)

**Comment by lifetin** [comment]
![55](https://user-images.githubusercontent.com/10474968/75109740-510f6000-5661-11ea-9370-50e2d504ac59.png)

**Comment by falsyvalues** [comment]
Hi @lifetin!
Its https://lodash.com/ not lodashjs.com
