### ISSUE TITLE
pickBy functionality

### ISSUE THREAD

**Issue by SanthoshBanavath** [lodash/lodash#4677]
Definition: `Creates an object composed of the object properties predicate returns truthy for`.
Let's say I have an object:
`names = [{'firstName': 'santhosh', 'lastName': 'banavath'},
{'firstName': 'Rama', 'lastName': 'Raj'];
result = pickBy(names, {firstName: 'santhosh'})`
Now the expected `result` is `[{'firstName': 'santhosh', 'lastName: 'banavath'}] `.
But the result is `['1':{'firstName': 'santhosh', 'lastName': 'banavath'}] `
Why this behavior is there?
EDIT: It might not have created for the object of the format I mentioned above. Can we have some `property` to do the above operation, instead of iterating through the object and `find`ing the props?

**Comment by ashifa454** [comment]
As per the documentation, PickBy returns an object and I think you are expecting an array of objects, hence one can try `_.filter(names,{firstName: 'Santhosh'})`. and I think it's a clever use of the object to return index with the result
