### ISSUE TITLE
Remove unnecessary check in getTag.js

### ISSUE THREAD

**Issue by aashutoshrathi** [lodash/lodash#4683]
This check is not required since return toString.call() will be enough to handle even `undefined` and `null`.
https://github.com/lodash/lodash/blob/588bf3e20db0ae039a822a14a8fa238c5b298e65/.internal/getTag.js#L11-L13

**Comment by aashutoshrathi** [comment]
Hi @sapphire135! (Pardon me for mentioning you)
Can you please confirm if this is really an `unnecessary check`? 
If yes, I have already created minor PR for this.
Thanks and sorry for being impatient again.

**Comment by sapphire135** [comment]
Hey @aashutoshrathi . Not sure about this check.
I just saw some discrepency on website so I thought to report it as lodash is used by many and I love the way it is documented.
That's why created a ticket here. https://github.com/lodash/lodash/issues/4749

You can ignore this if it doesn't matter that much.
Thanks

**Comment by aashutoshrathi** [comment]
@sapphire135 mentioned you by mistake 😅

**Comment by bnjmnt4n** [comment]
I believe the intention was to avoid having to call `toString` which is more expensive than simple equality (`==`/`===`) check for the `null` and `undefined` cases.

**Comment by aashutoshrathi** [comment]
`toString` is Expensive as in?
I think it takes less time, right?

![image](https://user-images.githubusercontent.com/21199234/81162612-199b2900-8fab-11ea-8035-1c6a348b7b87.png)

Please correct me if I missed something. @bnjmnt4n

**Comment by bnjmnt4n** [comment]
There’s a mistake with your comparison code, the code to get the internal class of a value should be `Object.prototype.toString.call(value)`. I’m not sure about the exact speed of the function, but maybe a more thorough benchmark can be created, and tested with different input values.

**Comment by aashutoshrathi** [comment]
Yeah, Thanks for pointing out that mistake.
I fixed that here.
The benchmarks are still pretty much the same.

```js
const fnOne = (value) => {
    if (value == null) {
        return value === undefined ? '[object Undefined]' : '[object Null]'
    }
};

const fnTwo = (x) => Object.prototype.toString.call(x);

console.time('if/else');
fnOne(null);
fnOne(undefined);
console.timeEnd('if/else');

console.time('toString');
fnTwo(null);
fnTwo(undefined);
console.timeEnd('toString');
```

Please take a look and let me know if it is worth to remove this check.

**Comment by falsyvalues** [comment]
This may not be entirely true, but I think it may be from IE < 9 times . Because there:
```js
Object.prototype.toString.call(null);
// "[object Object]"
```
Even on Node 0.10 it seems to be correct (`[object Null]`).

**Comment by aashutoshrathi** [comment]
So we can remove this check?
