### ISSUE TITLE
What's going on with lodash?

### ISSUE THREAD

**Issue by rkuykendall** [lodash/lodash#4684]
- Broken build
- No work for a month
- No releases
- 13 months of 5.0 developments
- If I google, I find this [Roadmap](https://github.com/lodash/lodash/wiki/Roadmap) not linked on the wiki homepage that looks relevant, aiming for a 2019 release?

Did something happen to someone? Do you need help? Did the 5.x branch just get out of hand? I would love to help.

**Comment by nainardev** [comment]
Project is dead

**Comment by falsyvalues** [comment]
Hi @rkuykendall!

We are [slowing down](https://twitter.com/jdalton/status/1236016711372959744) a bit, but `v4.17.16` probably will be rolled out soon we have few more things to [tackle](https://github.com/lodash/lodash/pulls?q=is%3Apr+is%3Aopen+head%3A4.17.15-post). 

[Roadmap](https://github.com/lodash/lodash/wiki/Roadmap) is valid except a year 😃

**Comment by rkuykendall** [comment]
@falsyvalues Great! Thanks for answering. The roadmap looks great.

Does this mean the project isn't looking for any help?

**Comment by falsyvalues** [comment]
Hi @rkuykendall!

If You want to tackle  #4571 or #4434  you are welcome :-)
