### ISSUE TITLE
suggesting a _.cycle wrapper method #4686

### ISSUE THREAD

**Issue by 9kartik** [lodash/lodash#4687]
Consider a button which can sort a list in ascending or descending order.
It would call for a function which will just need an extra parameter which keeps toggling like true/false etc.
Extend this to many other 'states' of the button like 'ascending'/'original'/'descending'.
So this is just a suggestion of a wrapper function which will keep on cycling the parameter list provided by the array in the first initialisation call.

Yet to write the test cases for the suggested methods.

something like 
cyclefunc = _.cycle(func, [false,true])
cyclefunc() // would call func with the last extra argument  as false
cyclefunc() // would call func with the last extra argument  as true
cyclefunc() // would call func with the last extra argument  as false
..
.
And so on.
Also provided a method for changing the cycle direction, and two methods for obtaining the current value and the next value.

https://github.com/lodash/lodash/pull/4686

**Comment by ishwarrimal** [comment]
Good point..

**Comment by YuriGor** [comment]
You will often want to know what is current "state"
Also, your function may expect this state arg not only as a first and single parameter but alongside with some other args

Maybe it's better to just return the next value from a given looped array, and not to call some function?

```js
cyclefunc = _.cycle(['A','B','C'])
cyclefunc() // A
cyclefunc() // B
cyclefunc() // C
cyclefunc() // A
...
```

**Comment by 9kartik** [comment]
@YuriGor ,the wrapper does offer properties like **cyclefunc.getCurrentValue()** which returns the current value of the cycle. 

> cyclefunc = _.cycle(func, ['A','B','C'])  
> cyclefunc() // would call func with the last extra argument as 'A'  
> cyclefunc.getCurrentValue() // A  
> cyclefunc() // would call func with the last extra argument as 'B'  
> cyclefunc.getCurrentValue() // B  
> cyclefunc() // would call func with the last extra argument as 'C'  
> cyclefunc.getCurrentValue() // C

And about the function getting called, should I consider passing additional parameters in the returned method which would pass the parameter while the function gets executed? Or would it be an overcomplication.



https://github.com/lodash/lodash/pull/4686/commits/fda37450eb87515afe5ebe9d3e609a903a3cc9a2#r395745033

**Comment by YuriGor** [comment]
Well about arguments order I am wrong, it's always easy to not pass target function directly, but wrap it into callback with compatible signature.

But I still believe it's better to keep things simple and just iterate over given data, and developer will decide what to do with this data by himself.

I think your idea fits well with [next](https://devdocs.io/lodash~4/index#prototype-next)  method if we could reset the iterator automatically,  once it's over.

**Comment by 9kartik** [comment]
@YuriGor ,but I never intended to make this wrapper resettable. It can be virtually 'paused' via the setDirection utility. 
> cyclefunc = _.cycle(func, ['A','B','C']) 
> cyclefunc() // would call func with the last extra argument as 'A'
> cyclefunc.getCurrentValue() // A
> cyclefunc() // would call func with the last extra argument as 'B'
> cyclefunc.setDirection(0) // cycle increments only by zero
> cyclefunc() // would call func with the last extra argument as 'B'
> cyclefunc.getCurrentValue() // B
> cyclefunc() // would call func with the last extra argument as 'B'
> cyclefunc.getCurrentValue() // B

I will consider not passing the function, but let the iterator just return the value.

**Comment by YuriGor** [comment]
here is ['next' implementation](https://github.com/lodash/lodash/blob/4.17.10/lodash.js#L8921):
```js
    function wrapperNext() {
      if (this.__values__ === undefined) {
        this.__values__ = toArray(this.value());
      }
      var done = this.__index__ >= this.__values__.length,
          value = done ? undefined : this.__values__[this.__index__++];

      return { 'done': done, 'value': value };
    }
```
So `reset` could look like:
```js
    function wrapperReset() {
      this.__index__ = 0;
    }
```
And cycle:
```js
    function wrapperCycle() {
      var next = wrapperNext();
      if(next.done) {
        wrapperReset();
        next = wrapperNext();
      }
      return next.value;
    }
```

**Comment by 9kartik** [comment]
Yes @YuriGor ,this does look neat.
If you see the main _.cycle method, it provides setDirection, which proves more beneficial than the just unidirectional next method.
Secondly the reset method would 'always' take it to zero.

The aim of the utility it to leave the control of generating the next sequence item with the cycle-wrapper method.
Think of scenarios like clicking a button and switching the sort between ascending/descending.
Or another scenario where a carousel will move left in cycles and right in cycles.

It is a good suggestion, but will have to rethink of what should happen to __index__ upon reset, and also if I can pass parameters within next, so that I can know by how much to jump(shift the value by) and in which direction.
