### ISSUE TITLE
_.words splits on caseing as well. Which seems unexpected

### ISSUE THREAD

**Issue by jschank** [lodash/lodash#4688]
_.words('BarNey')
=> ["Bar", "Ney"]

That seems strange to me.

**Comment by maniator** [comment]
Seems expected to me. Works nicely with camel-cased strings

**Comment by falsyvalues** [comment]
Hi @jschank!

Its works as expected here. See more in our [docs](https://lodash.com/docs/4.17.15#words). `_.words` is not perfect as we already know, but we will address some issues in future releases.
