### ISSUE TITLE
Number of arguments to iteratee of fp/reduce not limited to 2

### ISSUE THREAD

**Issue by kmamal** [lodash/lodash#4692]
On version 4.17.15

```
const fp = require('lodash/fp')
const a = fp.reduce(Math.max, 0, [ 1, 2, 3 ])
const b = fp.reduce((...args) => Math.max(...args), 0, [ 1, 2, 3 ])
console.log(a, b) // prints => NaN, 3
```

I would have expected `a` and `b` to be the same. Based on the docs `fp/reduce` should limit the number of arguments to the iteratee to 2, so passing `Math.max` directly shouldn't be a problem.

From what I can tell the fp convert code looks at the `iteratee.length` and if it's already 2 it doesn't add a wrapper, as an optimization. Sadly this ignores the fact that `Math.max.length === 2`, as well as spread operators like `((a, b, ...c) => {}).length === 2`.

**Comment by ljluestc** [comment]
const fp = require('lodash/fp')

const customMax = (...args) => Math.max(...args);

const a = fp.reduce(customMax, 0, [1, 2, 3]);
const b = fp.reduce((...args) => customMax(...args), 0, [1, 2, 3]);

console.log(a, b); // prints => 3, 3
