### ISSUE TITLE
Slow response on lodash documentation website on chrome

### ISSUE THREAD

**Issue by eranboww** [lodash/lodash#4696]
When using the docs and starting typing a command for its documentation the browser is freezing...
When using firefox - it works great

**Comment by caffodian** [comment]
Strangely, this seems to only happen to me on Windows - I have the same Chrome profile & extensions on my Mac & Windows machines, but my Windows search is extraordinarily slow (to the extent that one loses keystrokes typing into the search box).  It's been slow on a few friends that are also using Windows + Chrome (though oddly Firefox seems okay) .  Not sure if this is enough to pinpoint or investigate, but wanted to add more info.

**Comment by whaaaley** [comment]
I'm using Microsoft's chromium browser and the problem exists there too.

**Comment by falsyvalues** [comment]
Hi @eranboww!

We have dedicated repo to discuss related to [lodash.com](https://github.com/lodash/lodash.com). See also [rework](https://github.com/lodash/lodash.com/issues/201) issue.
