### ISSUE TITLE
Debounce return undefined if func return promise

### ISSUE THREAD

**Issue by wjw99830** [lodash/lodash#4700]
lodash: `^4.17.4`
```typescript
function request() {
  return Promise.resolve();
}
const debounced = debounce(request, 2000);
console.log(debounced()); //  -> undefined
```
[#4400 ](https://github.com/lodash/lodash/issues/4400) has a same problem, but the solution is enable `leading` option. What should I do if I don't need it ?

**Comment by AChelp** [comment]
@wjw99830 did you find the solution?

**Comment by wjw99830** [comment]
@AChelp

**Comment by wjw99830** [comment]
@AChelp No, because I think it's a reasonable behavior. If we don't enable `leading`, it will be merited when call the function first time.

**Comment by AChelp** [comment]
@wjw99830 ok, thnx.

**Comment by JustusW** [comment]
Kinda have to reopen. This causes a typisation error and makes the generics pointless as it will always carry the pseudo type <T | undefined>. This is problematic for any T incompatible with undefined most prominently Promise.
```
function getSomething<Promise<ResultObj>>(query: string) {
    return fetch("/data/something.json" + new URLSearchParams({q: query}))
}
```

If I want to wrap this I have a problem:
```
let fn = _.debounce<(query: string) => Promise<ResultObj>>(getSomething, 500)
function foo(): Promise<ResultObj> {
    return fn()
}
```
which leads to this:
```
Type 'DebouncedFunc<(query: string) => Promise<ResultObj>>' is not assignable to type '(query: string) => Promise<ResultObj>'
  Type 'Promise<Branch[]> | undefined' is not assignable to type 'Promise<Branch[]>'.

```

You can technically overwrap this:
```
let f = _.debounce<(query: string) => Promise<ResultObj>>(getSomething, 500)
let fn = function (query: string): Promise<ResultObj> {
    let out = new Promise<ResultObj>(((resolve, reject) => {reject()}));
    let res = f(query)
    if (res !== undefined) {
        out = res
    }
    return out
}
```
Which is (in my considered opinion) an abomination and should be purged in the fires of the imperial holy inquisition...
While you can just // @ts-ignore to suppress TS2322 I see that as... not exactly correct. Even if you set leading to true, which technically guarantees the value will never be undefined, it still breaks the chain of type assertion.

My suggestion would be to strongly type it to T (and not T | undefined) with the proviso of a new option fnFailure to return a failed state object appropriate to this context.

```
let fn = _.debounce<(query: string) => Promise<ResultObj>>(getSomething, 500, {
    fnFailure: () => new Promise<ResultObj>((resolve,reject) => reject())
})
```

**Comment by WilliamYkZhang** [comment]
I've found this post by Jordan Papaleo very helpful.
https://www.jordanpapaleo.com/Debouncing%20an%20API%20call%20with%20promise%20chaining/

**Comment by JustusW** [comment]
> I found this post by Jordan Papaleo very helpful.
> https://www.jordanpapaleo.com/Debouncing%20an%20API%20call%20with%20promise%20chaining/

That's just a complicated way to say "you have to break your API". A function that sometimes returns undefined is not compatible to typescript usage. Period.
Any T incompatible with undefined is broken by this. The theoretical ability to fix it in some cases does not cover cases in which this is not possible.

**Comment by ianmacartney** [comment]
Here's an async-friendly version of throttle (same idea applies to debounce) that will always return a promise, but only resolve/ reject the promise if the underlying function is called:
```
/**
 * Throttles an async function in a way that can be awaited.
 * By default throttle doesn't return a promise for async functions unless it's invoking them immediately. See CUR-4769 for details.
 * @param func async function to throttle calls for.
 * @param wait same function as lodash.throttle's wait parameter.
 *             Call this function at most this often.
 * @returns a promise which will be resolved/ rejected only if the function is executed, with the result of the underlying call.
 */
function asyncThrottle<
  F extends (...args: any[]) => Promise<any>
>(func: F, wait?: number) {
  const throttled = _.throttle((resolve, reject, args: Parameters<F>) => {
    func(...args).then(resolve).catch(reject);
  }, wait);
  return (...args: Parameters<F>): ReturnType<F> =>
    new Promise((resolve, reject) => {
      throttled(resolve, reject, args);
    }) as ReturnType<F>;
}
```
working in [a fork of a sandbox](https://codesandbox.io/s/zealous-microservice-qzu3l?file=/src/InputSection.js) from #4815 

non-typescript:
```
function asyncThrottle(func, wait) {
  const throttled = _.throttle((resolve, reject, args) => {
    func(...args).then(resolve).catch(reject);
  }, wait);
  return (...args) =>
    new Promise((resolve, reject) => {
      throttled(resolve, reject, args);
    });
}
```

other approaches to this seem to return cached values. This one minimizes how many calls to the function try to respond to the results

**Comment by DevinXian** [comment]
> Here's an async-friendly version of throttle (same idea applies to debounce) that will always return a promise, but only resolve/ reject the promise if the underlying function is called:
> 
> ```
> /**
>  * Throttles an async function in a way that can be awaited.
>  * By default throttle doesn't return a promise for async functions unless it's invoking them immediately. See CUR-4769 for details.
>  * @param func async function to throttle calls for.
>  * @param wait same function as lodash.throttle's wait parameter.
>  *             Call this function at most this often.
>  * @returns a promise which will be resolved/ rejected only if the function is executed, with the result of the underlying call.
>  */
> function asyncThrottle<
>   F extends (...args: any[]) => Promise<any>
> >(func: F, wait?: number) {
>   const throttled = _.throttle((resolve, reject, args: Parameters<F>) => {
>     func(...args).then(resolve).catch(reject);
>   }, wait);
>   return (...args: Parameters<F>): ReturnType<F> =>
>     new Promise((resolve, reject) => {
>       throttled(resolve, reject, args);
>     }) as ReturnType<F>;
> }
> ```
> 
> working in [a fork of a sandbox](https://codesandbox.io/s/zealous-microservice-qzu3l?file=/src/InputSection.js) from #4815
> 
> non-typescript:
> 
> ```
> function asyncThrottle(func, wait) {
>   const throttled = _.throttle((resolve, reject, args) => {
>     func(...args).then(resolve).catch(reject);
>   }, wait);
>   return (...args) =>
>     new Promise((resolve, reject) => {
>       throttled(resolve, reject, args);
>     });
> }
> ```
> 
> other approaches to this seem to return cached values. This one minimizes how many calls to the function try to respond to the results

Great answer!

**Comment by Sczlog** [comment]
I wonder if current implementation of debounce is wrong(although the implementation has already been widely used), i think a debounced function should always return a promise as debounce itself is alreay an async operation, it will always delay the return you get from the debounced function.
user should be able to choose whether to wait the promise resolve/reject (async request, file io) or not (element event listener).
return an undefined first may cause comfusion about the response, if it returned by debouced function? or just by debouncer.
