### ISSUE TITLE
`.get` works different from standard property accessors

### ISSUE THREAD

**Issue by jas0ncn** [lodash/lodash#4701]
```javascript
const res1 = { data: { text: 'hi' }, 'data.text': '<img />' }

_.get(res1, 'data.text') // "<img />"

res1.data.text // "hi"
```

**Comment by jmm** [comment]
It would be good to document how `.get` handles this situation where there's a literal key matching the path argument, but if you want to be sure you get the path you had in mind you can pass it as an array:

```js
_.get(res1, 'data.text'.split("."))
```

**Comment by jas0ncn** [comment]
@jmm Agree! It should be documented.
