### ISSUE TITLE
_.sortBy does not sort alphabetically correct.

### ISSUE THREAD

**Issue by sulhadin** [lodash/lodash#4704]
I have an object array consists of lowercase and uppercase letters. sortBy sorts them starting with capital letters.

Demo link;
https://runkit.com/sulhadin/5e7b73f2de8893001387f2b7

**Comment by brijeshpanara24** [comment]
ASCII values are as following -
A: 65, Z:90, a: 97, z: 122
So it is sorting according to ASCII values of characters.

If you want to sort according to name irrespective of case(Lowercase/Uppercase), we can do this in following way -
`
const _ = require('lodash');

var users = [
    { 'user': 'yred',   'age': 48 },
    { 'user': 'zarney', 'age': 36 },
    { 'user': 'Ared',   'age': 40 },
    { 'user': 'barney', 'age': 34 },
    { 'user': 'Barney', 'age': 34 },
    { 'user': 'aarney', 'age': 34 },
    { 'user': 'Zarney', 'age': 34 }
  ];

const sortedUsers = _.sortBy(users,(o) => o.user.toLowerCase());

console.log(sortedUsers);
`

**Comment by daedalus28** [comment]
Since this is working as expected, I think this is safe to close

**Comment by jessisar** [comment]
> ASCII values are as following - A: 65, Z:90, a: 97, z: 122 So it is sorting according to ASCII values of characters.
> 
> If you want to sort according to name irrespective of case(Lowercase/Uppercase), we can do this in following way -
> 
> ```
> const _ = require('lodash');
> 
> var users = [
>     { 'user': 'yred',   'age': 48 },
>     { 'user': 'zarney', 'age': 36 },
>     { 'user': 'Ared',   'age': 40 },
>     { 'user': 'barney', 'age': 34 },
>     { 'user': 'Barney', 'age': 34 },
>     { 'user': 'aarney', 'age': 34 },
>     { 'user': 'Zarney', 'age': 34 }
>   ];
> 
> const sortedUsers = _.sortBy(users,(o) => o.user.toLowerCase());
> 
> console.log(sortedUsers);
> ```
> 
> Demo link: https://runkit.com/brijeshpanara24/5e8078778c85b6001ad2e341

But this does not sort upper and lower case. When you put in a list like this

```
 var users = [
     { 'user': 'Barney', 'age': 34 },
     { 'user': 'barney', 'age': 34 },
     { 'user': 'farney', 'age': 36 },
     { 'user': 'Farney', 'age': 34 }
   ];
```

it's not possible to sort it to 

```
     { 'user': 'Barney', 'age': 34 },
     { 'user': 'barney', 'age': 34 },
     { 'user': 'Farney', 'age': 34 }
     { 'user': 'farney', 'age': 36 }
```

or is it?

**Comment by igortas** [comment]
> ASCII values are as following - A: 65, Z:90, a: 97, z: 122 So it is sorting according to ASCII values of characters.
> 
> If you want to sort according to name irrespective of case(Lowercase/Uppercase), we can do this in following way -
> 
> ```
> const _ = require('lodash');
> 
> var users = [
>     { 'user': 'yred',   'age': 48 },
>     { 'user': 'zarney', 'age': 36 },
>     { 'user': 'Ared',   'age': 40 },
>     { 'user': 'barney', 'age': 34 },
>     { 'user': 'Barney', 'age': 34 },
>     { 'user': 'aarney', 'age': 34 },
>     { 'user': 'Zarney', 'age': 34 }
>   ];
> 
> const sortedUsers = _.sortBy(users,(o) => o.user.toLowerCase());
> 
> console.log(sortedUsers);
> ```
> 
> Demo link: https://runkit.com/brijeshpanara24/5e8078778c85b6001ad2e341

not really working for nested structure with iteratee :'(
