### ISSUE TITLE
_.parseInt('0xFFFFFFD0', HEX): Signed 32bit Hex to Number Conversion

### ISSUE THREAD

**Issue by phcontrols** [lodash/lodash#4707]
Hello Sir/Madam,

I am trying to convert Signed 32bit Hex to Number using _.parstInt().
example:  _.parseInt('0xFFFFFFD0', HEX);

The result I am expecting is -48 however the result i am getting is 4294967248.
May I request you to kindly help me to resolve this issue ?
Appreciate all your help in advance !

**Comment by falsyvalues** [comment]
Hi @phcontrols!

`0xFFFFFFD0` doesn't seem to be even close to 48. Try something more like: `_.parseInt('0x30')`
