### ISSUE TITLE
Math method to find both min and max values of array in one pass

### ISSUE THREAD

**Issue by axelboc** [lodash/lodash#4711]
I'd like to suggest adding a Math method, perhaps called `_.bounds`, to find both the minimum and maximum value of an array **in one pass**. The method would return an array of the form `[minValue, maxValue]`.

Lodash includes methods for finding the minimum and maximum value in an array independently, but not both at the same time, in one pass. What I'm after is a more efficient and convenient version of:

```js
const bounds = [_.min(arr), _.max(arr)];
```

In my case, I would use this method to compute the **domain** of a dataset, which I need to create a **color scale** for data visualization purposes (with [d3-scale](https://github.com/d3/d3-scale)). I'm working with very large datasets, in the order of magnitude of 1 million points, so looping through them in a single pass instead of two is a significant optimisation.

Here is a basic vanilla ES5 implementation:

```js
function bounds(array) {
  return array.reduce(
    ([min, max], item) => [Math.min(item, min), Math.max(item, max)],
    [Infinity, -Infinity]
  );
}
```

It's worth noting that a few libraries already exist for this purpose, notably [array-bounds](https://github.com/dy/array-bounds), which additionally allows computing the bounds of a multi-dimensional array.

**Comment by lonewarrior556** [comment]
Just sort it
```js
function bounds(array) {
  const arr = _.sortBy(array);
  return [arr[0], arr[arr.length-1]]
}
```

**Comment by axelboc** [comment]
Thanks @lonewarrior556. Unfortunately, sorting is not as efficient as going through an array in a single pass.

**Comment by hmalik88** [comment]
I don't mind tackling this, does this feature need to be approved to be worked on or can i simply submit a PR?

**Comment by bnjmnt4n** [comment]
Given that there are already various established libraries for that function, we'd prefer to punt to them for now, but we'll keep an eye on the [popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
