### ISSUE TITLE
`lodash/chain` not including prototype functions

### ISSUE THREAD

**Issue by Harris-Miller** [lodash/lodash#4712]
I noticed this in a project I'm working on. We do `import chain from 'lodash/chain';` and we have webpack alias `lodash` to `lodash-es`. But when we run our Jest unit tests, we get and error that `chain(...).groupBy is not a function`

Not sure why, so I loaded up the node REPL and discovered this:

```
> $ node
Welcome to Node.js v12.13.1.
Type ".help" for more information.
> var lodash = require('lodash');
undefined
> lodash.chain([]).groupBy
[Function]
> var { chain } = require('lodash');
undefined
> chain([]).groupBy
[Function]
> var chainDirect = require('lodash/chain');
undefined
> chainDirect([]).groupBy
undefined
>
```

seems `var chain = require('lodash/chain');` is broken as you don't get any of the methods on the return object from `chain()`, but you do if you `require('lodash')`

node v 12.13.1
lodash v 4.17.15

**Comment by kaizvn** [comment]
I checked the sourcecode : seem `.chain()` was removed from project.

**Comment by Harris-Miller** [comment]
> I checked the sourcecode : seem `.chain()` was removed from project.

https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L8737

**Comment by kaizvn** [comment]
> > I checked the sourcecode : seem `.chain()` was removed from project.
> 
> https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L8737

where was it built from?

**Comment by bnjmnt4n** [comment]
> seems `var chain = require('lodash/chain');` is broken as you don't get any of the methods on the return object from `chain()`, but you do if you `require('lodash')`

The `lodash/xyz` modules are intentionally self-contained, so that the whole lodash library does not need to be loaded ande executed, which is useful for cherry-picking individual functions. If you need to use the `_.chain` functionality, you do need to load the whole `lodash` library.

**Comment by HuyAms** [comment]
Are we able to solve this yet? I faced up with the issue

**Comment by chungnq253** [comment]
Bumb!

**Comment by nathggns** [comment]
Just ran into a runtime crash because of this. `import chain from "lodash/chain"` is typed as having the methods but it doesn't at runtime. Really ought to be addressed.

**Comment by JayPuff** [comment]
For anyone else using `lodash-es` which indeed has issues if you try to use _.chain(...).etc in production because of tree shaking.

This might help if you are using lint, to discourage it by the rest of your team, etc.

```
"no-restricted-syntax": [
      "error",
      {
        "selector": "MemberExpression[object.name='_'][property.name='chain']",
        "message": "`lodash-es` is meant to be tree-shaken, therefore `_.chain` causes issues in production. Do not use `_.chain`"
      },
      {
        "selector": "CallExpression[callee.name='_']",
        "message": "`lodash-es` is meant to be tree-shaken, therefore `_(value)` is equivalent of using `_.chain` which causes issues in production. Do not use `_.chain`"
      }
    ]
```

You can also add a rule to implicitly disallow importing 'chain' from 'lodash-es'

**Comment by brendonmatos** [comment]
> We also encountered this issue when migrating from `lodash` to `lodash-es`. Before, we had this import:
> 
> import { chain } from 'lodash';
> then we changed it to:
> 
> import { chain } from 'lodash-es';
> There was no TypeScript error, therefore, we couldn’t spot the issue during compilation. We only noticed it at runtime. The following ways of importing didn’t work either:
> 
> import _ from 'lodash-es';
> import chain from 'lodash-es/chain';
> The solution is to simply not use `chain`. For example, if you have:
> 
> import { chain } from 'lodash';
> 
> const array = [];
> const result = chain(array).groupBy((e) => e.name).map((elements, name) => {}).value();
> you can do:
> 
> import { groupBy, map } from 'lodash-es';
> 
> const array = [];
> const result = map(groupBy(array, (e) => e.name), (elements, name) => {});
> or if you use a few functions, it could be more readable like this:
> 
> import { groupBy, map } from 'lodash-es';
> 
> const array = [];
> const groups = groupBy(array, (e) => e.name);
> const result = map(groups, (elements, name) => {});

Thanks for clarifying that!

FYI When we use lodash-es + Vite, we only see this issue during the build (rollup) because tree-shaking works differently than in esbuild which is used during development.
