### ISSUE TITLE
Update docs for `_.intersectionWith` comparator to avoid confusion regarding comparator argments

### ISSUE THREAD

**Issue by vjpr** [lodash/lodash#4720]
I just ran into the same issue as here: https://github.com/lodash/lodash/issues/2798

It current says "The comparator is invoked with two arguments: (arrVal, othVal).". I assumed that `arrVal` was the first array, and `othVal` would always be one of the other arrays.

When you read "The order and references of result values are determined by the first array", it also makes you think that `arrVal` is always the first array.

Also the signature is written as:

```
_.intersectionWith(objects, others, _.isEqual);
```

It should be made clear that the params of the comparator can be either `objects` or any of the `others` arrays.

**Comment by simplesmiler** [comment]
Ran into this today, guided by `@types/lodash`. Opened a discussion there: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/57484
