### ISSUE TITLE
lodash 3.10.1 minification failure in ASP.net MVC

### ISSUE THREAD

**Issue by sudeepgorai990** [lodash/lodash#4721]
Hello team,
lodash minification still failing in asp.net mvc bundling & minification. could you please provide updated lodash.min.js file version 3.10.1.

**Comment by bnjmnt4n** [comment]
There is a [minified version of lodash v3.10.1](https://raw.githubusercontent.com/lodash/lodash/3.10.1/lodash.min.js) available.
