### ISSUE TITLE
Array swap function proposal

### ISSUE THREAD

**Issue by virtumonde** [lodash/lodash#4723]
I am proposing this simple function to swap elements in an array. Although this is trivial, it saves time.

```
/**
 * Swap two elements in an array
 *
 * @since 4.17.15
 * @category Array
 * @param {array} The array where the elements would be swapped.
 * @param {indexA} The index of the first element.
 * @param {indexB} The index of the second element.
 * @example
 *
 * swap([['a', 'b', 'c', 'd'], 0, 1)
 * // => (['b', 'a', 'c', 'd'])
 */
function swap(array, indexA, indexB) {
    let tmp = array[indexA];
    array[indexA] = array[indexB];
    array[indexB] = tmp;
}

export default swap

**Comment by houssem26** [comment]
I think it would be better to have a function that does not mutate the state of the input array,
so it returns a new array with the elements swapped

**Comment by DevBaweja** [comment]
# Better proposal of Array swap function.

## 1) Design
```
Swap two elements in an array
@since version
@category Array
@param {array} The array where the elements would be swapped.
@param {indexA} The index of the first element.
@param {indexB} The index of the second element.
```

## 2) Pseudo Code
    
    function swap(array, indexA, indexB){
        // Creating new array
        // Swapping the new array elements of indexA and indexB
        // Return new array
    }

## 3) Output

  + ### Basic
  
    ```
    swap([1,2,3], 0, 1)
    => [2,1,3]

    swap(['1','2','3'], 0, 1)
    => ['2','1','3']

    swap([{k1:'v1'}, {k2:'v2'}, {k3:'v3'}], 0, 1)
    => [{k2:'v2'} , {k1:'v1'}, {k3:'v3'}]
    ```

  + ### Out of index

    ```
    swap([1,2,3], 0, 4)
    => [1,2,3]
    ```
  + ### Misc
    In case of invalid input it will return empty array
    ```
    swap(undefined, indexA, indexB)
    => []
    ```

## 4) Test

  + ### Identity
    
  Follows identity when indexA and indexB are identical
  ```
  swap([1, 2, 3], 0, 0)
  => [1, 2, 3]
  ```

  + ### Commutative
    
  Follows commutative when indexA and indexB are interchanged
  ```
  swap([1, 2, 3], 0, 1)
  => [1, 2, 3]
  swap([1, 2, 3], 1, 0)
  => [1, 2, 3]
  ```

  + ### Associative
      
  Doesn't Follow associative 
  ``` 
  swap(swap([1, 2, 3], 0, 1), 1, 2) 
  => [2, 3, 1]
  swap(swap([1, 2, 3], 1, 2), 0, 1)
  => [3, 1, 2]
  ```

## 5) Quality
  + ### Data Immutability
  ```
  Since in creating this function user data is not changed.
  As we will create new array of given array.
  Data Immutability of FP is followed.
  ```

## 6) Ideas
To create an object swap function which will swap the values of given object.
    ```
    swap(object, keyA, keyB)

    swap({ a: 1, b: 2}, 'a', 'b')
    => { a:2, b:1 }
    ```
Inform us if you also want us to implement these ideas.

**Comment by falsyvalues** [comment]
As usual we will keep an eye on the [popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
