### ISSUE TITLE
[typescript] [pick] Type difference between using _.pick and pick 

### ISSUE THREAD

**Issue by zucker-rdrg** [lodash/lodash#4725]
In my example:
![image](https://user-images.githubusercontent.com/19388313/79544796-db87a500-808f-11ea-8fb3-53f4bce415b4.png)
only test4 and test5 will throw a typescript error
![image](https://user-images.githubusercontent.com/19388313/79544991-2f928980-8090-11ea-9e0d-2a3a9c6e29bc.png)
So is there any correlation between import method  (`_` or direct `pick`) and returning type?

My code
```js
public test1(x: {a: number, b: number}): { b: number } {
    return _.pick(x, 'a');
}

public test2(x: {a: number, b: number}): { b: number } {
    return _.pick<{ a: number }>(x, 'a');
}

public test3(x: {a: number, b: number}): { b: number } {
    const result = _.pick(x, 'a');
    
    return result;
}

public test4(x: {a: number, b: number}): { b: number } {
    const result: { a: number } = _.pick(x, 'a');
    
    return result;
}

public test5(x: {a: number, b: number}): { b: number } {
    return pick(x, 'a');
}
```

**Comment by falsyvalues** [comment]
Hi @zucker-rdrg!

This discussion should definitely go to ➡️[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) contributors of [@types/lodash](https://www.npmjs.com/package/@types/lodash) will help for sure.
