### ISSUE TITLE
Incorrect kebabcase transformation 

### ISSUE THREAD

**Issue by sreevisakh** [lodash/lodash#4726]
const name = 'ASTRAv5.7'
const results = _.kebabCase(name);
// returns 'astr-av-5-7';
// expected  'astra-v-5-7

**Comment by maurer2** [comment]
Hello, we also experience this issue when mixing upper- and lower case letters:


```javascript
const _ = require('lodash');

console.log(_.kebabCase('Test-URLs'));

```
(https://repl.it/repls/KindheartedNanoScientificcomputing)

Expected value: `test-urls`
Returned value:  `test-ur-ls`

As a workaround one can convert it to lower- or uppercase via (`toLowerCase()` or `toUpperCase()`) before calling `kebabCase()`

**Comment by internalG** [comment]
#5836  It's a camel case sample.
