### ISSUE TITLE
Push to Path

### ISSUE THREAD

**Issue by amaster507** [lodash/lodash#4727]
Similar to https://github.com/lodash/lodash/issues/1145 but I think I have added to the conversation with the two additional parameters described below as `expand` and `preventDup` and my functioning version of it as a JavaScript function

I have often needed to push data to a path and while `_.set(...)` works well for setting a whole set of data, it does not quite fulfill the need of appending data to an array at a path in an object. While the `_.get(...).push(...)` method works for setting data to an already existing path, it does not create the path when needed like `_.set(object, 'new.path', value)` does.

I added two additional parameters to this that is not standard to `_.set` parameters.

I have needed to pass an array and then merge that array with the array already existing at the path, but also have the option to push an array as the single value as well. So to solve this switch case I have added the Boolean parameter `expand`.

I have also needed to remove duplicates in the merge process so that an array works more like a JavaScript Set. To solve this switch case I have added the Boolean parameter `preventDup`

I have wrote a plain JavaScript function using vanilla JavaScript and a few lodash functions to implement my version of this. I have thought about writing an extension and making it publicly available, but would rather like to see it in the core of lodash if possible.

```javascript
const loPush = (object, pathToArray, value, expand = false, preventDup = false) => {
  let a = _.get(object, pathToArray) || [];
  if (expand && value.isArray()) {
    if (preventDup) {
      _.forEach(value, v => {
        if(!a.includes(v)) {
          a.push(v);
        }
      })
    } else {
      a.push(...value)
    }
  } else if (expand) {
    throw new Error('Expand option set to true, but value given was not an array');
  } else {
    if (preventDup) {
      if(!a.includes(value)) {
        a.push(value);
      }
    } else {
      a.push(value);
    }
  } 
  _.set(object, pathToArray, a)
  return object
}
```

The `expand` and `preventDup` parameters could be turned into an options group like many other libraries have. This would change the first line into two lines:

```javascript
const loPush = (object, pathToArray, value, options) => {
  const { expand = false, preventDup = false } = options
```

**Comment by bnjmnt4n** [comment]
Hi @amaster507! Thanks for the suggestion. Since this is similar in nature to #1145, I've decided to unlock that issue to allow votes, and close this issue instead.
