### ISSUE TITLE
_.defaults has unexpected behaviour where it passes the properties by reference

### ISSUE THREAD

**Issue by glassresistor** [lodash/lodash#473]
What I'm seeing is the source objects properties passed by reference instead of value so making changes to the destination object affects the source.
https://gist.github.com/glassresistor/8967607

**Comment by tetienne** [comment]
Hi, sorry to up this issue, but I'm in the same situation. In the gist example provide here, I have to use `_.clone` to deal with this behavior.

```JS
var a = _.defaults({'a': { 'a': 2}}, _.clone(b));
```

Can I know why this issue has been tag as invalid? Is it on purpose?

**Comment by jdalton** [comment]
The issue is marked as invalid because it's how `_.defaults` and `_.assign` works. They assign by reference so if your source has an array or an object value then it's assigned directly.

**Comment by tetienne** [comment]
Thank you for the clarification. I will keep in my mind this behavior.
