### ISSUE TITLE
`Math.random()` doesn't reliably contain enough state bits to work for shuffling all but very small arrays

### ISSUE THREAD

**Issue by isiahmeadows** [lodash/lodash#4743]
The Fisher-Yates shuffle algorithm [can only generate all the permutations of an array provided there's enough bits in the RNG's state to represent the number of all possible permutations](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#Pseudorandom_generators). In small lists (20 or fewer), this rarely matters, but in even medium-size arrays, this presents a problem:

- [V8](https://v8.dev/blog/math-random),[SpiderMonkey](https://bugzilla.mozilla.org/show_bug.cgi?id=322529), [ChakraCore](https://github.com/microsoft/ChakraCore/blob/c97139d2fa291b2bce34fbd21c421bb94f3dc79f/lib/Runtime/Math/JavascriptMath.cpp#L1305-L1315), and [JSC](https://trac.webkit.org/browser/webkit/trunk/Source/WTF/wtf/WeakRandom.h#L91) all use [XorShift128+](https://en.wikipedia.org/wiki/Xorshift#xorshift+) (128-bit state), can only shuffle lists of up to 34 entries
	- WebKit doesn't make it explicit via comments, but it's pretty obvious when you compare the algorithms that it's 100% identical to Wikipedia's version.
- GraalJS [delegates to Java's `SplittableRandom`](https://github.com/graalvm/graaljs/blob/f4b20be6bda0534030b8eb541f5e8605cda3611c/graal-js/src/com.oracle.truffle.js/src/com/oracle/truffle/js/runtime/JSRealm.java#L2094), and [Java just increments a 64-bit seed by the golden ratio and applies a non-cryptographic hash](https://hg.openjdk.java.net/jdk/jdk/file/372d79aca24a/src/java.base/share/classes/java/util/SplittableRandom.java), so it can only reliably shuffle lists of up to 20 entries.
- [Rhino](https://github.com/mozilla/rhino/blob/47c9fe849ff0f8d766abc8a1a919c13a05bfab9a/src/org/mozilla/javascript/NativeMath.java#L291) and [Nashorn (deprecated as of JDK 11)](https://hg.openjdk.java.net/jdk/jdk14/file/6c954123ee8d/src/jdk.scripting.nashorn/share/classes/jdk/nashorn/internal/objects/NativeMath.java#l625) both delegate to Java's native `Math.random()`, which [only uses 48 bits of state](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/util/Random.html) and so can only support shuffling lists of up to 16 entries before some permutations get missed.
- I ignored engines like XS targeting low-resource embedded as Lodash is unlikely to ever be used there.

Of course, you could go with a heavy-weight Mersenne Twister, but in any case, I don't think it's safe to rely on the runtime's native RNG for shuffling.

**Comment by falsyvalues** [comment]
Hi @isiahmeadows!

I think that's a job for specialized library for randomizing things. We are not planning to expand above `Math.random()` extensions.

**Comment by isiahmeadows** [comment]
Should a note be added to clarify this in the docs, that it's not suitable for larger lists as it can't reach all the permutations of it?
