### ISSUE TITLE
omit doesnt work with object that come from mongoose library.

### ISSUE THREAD

**Issue by dann1609** [lodash/lodash#4746]
## Description
I found omit doesn't work from object that come from mongoose library, it answer back the full object. pick work without problem so its a little weird because I will expect if is an issue with object, neither pick nor omit  work. But that's not the case.

I'm able to bypass using JSON.parse(JSON.stringify(object))
## Context

```
const userSchema = new mongoose.Schema({
  email: {
    type: String,
  },
  password: {
    type: String
  },
  company: {
   type: String
  },
});
```

## Expected

```
_.omit(user,['password']). => 
{
  email: ...,
  company: ...
}

```

## Current
```
_.omit(user,['password']). => 
{
  email: ...,
  company: ...,
  password: ...
}

```

## Bypass

```
_.omit(JSON.parse(JSON.stringify(user)),['password']). => 
{
  email: ...,
  company: ...
}

```

**Comment by daedalus28** [comment]
My understanding of mongoose is that it's `Document` type is not a plain JS object and does some magic to do this on purpose. I believe you can solve this by using [`.toObject`](https://mongoosejs.com/docs/api/document.html#document_Document-toObject) to get something that lodash can work with, which is a common thing to do when working with a library that has its own types. This is similar to the need to call `toJS` if you're using observables in knockoutjs or mobx (at least in v4).

Either way, this is a mongoose issue and not a lodash issue. I think this is safe to close.

**Comment by ummartoor** [comment]
```
const userDoc = await User.findOneAndUpdate(query, update, {
      new: true,
    }).lean();
```
    
    you need to convert the mongo Object to the normal Javascript object by using the `.lean()` fun, now omit will work.

**Comment by GIDEON-BABALOLA** [comment]
Use the toObject method to convert the mongoose object into a Javascript Object first before calling the omit function.
//Something Like This
 const newUser = _.omit(user.toObject(), "refreshToken")
 console.log(newUser) // This object will not contain refreshToken
