### ISSUE TITLE
Search bar in Lodash Documentation Issue

### ISSUE THREAD

**Issue by sapphire135** [lodash/lodash#4749]
https://lodash.com/docs/4.17.15

In the search bar, If I copy paste something which is not present in the docs then we can't be able to erase it.

For example, I copied "abcdef" in Search bar then i can't erase it letter by letter.
I have to select it all and then erase it.

**Comment by aashutoshrathi** [comment]
It happens when you enter more than 4 characters in the query.
They limit the query to 4 characters.

**Comment by sapphire135** [comment]
Thanks for repying @aashutoshrathi Isn't it still a bug ?
Moreover, As far as i can look they are not limiting the query to 4 characters.
It can be less or more, It depends.

You can try typing "differenceWith" and "zzz".

**Comment by aashutoshrathi** [comment]
Yeah, I think it is still a bug.

**Comment by falsyvalues** [comment]
Hi @sapphire135!

We have dedicated place for [website ](https://github.com/lodash/lodash.com) related issues.
