### ISSUE TITLE
NPM latest version of lodash is 4.17.1  while github package.json lists is as "version": "5.0.0",

### ISSUE THREAD

**Issue by aaa-manuelhe** [lodash/lodash#4750]
when I run npm install  lodash I get 4.1.7 but the lodash repo here in github lists it as "version": "5.0.0", in package.json. Why is the npm version out of sync with the latest github version?

**Comment by bnjmnt4n** [comment]
Hi @aaa-manuelhe! The last released version is 4.17.15, but on GitHub we’re currently working on the next version of lodash, which is v5.
