### ISSUE TITLE
FR: replaceLast

### ISSUE THREAD

**Issue by xmedeko** [lodash/lodash#4753]
I would welcome a String function that replaces the last occurrence, not the first one. For string and RegExp, too. E.g.
```js
_.replaceLast('abab', 'b', 'c'); // -> 'abac'
_.replaceLast('abad', /[db]/, 'c'); // -> 'abac'
```

Note: on the other hand [`_.replace`](https://lodash.com/docs/4.17.15#replace) may be removed IMHO.

**Comment by yashshah1** [comment]
Can I take this issue up?

**Comment by mdaj06** [comment]
@xmedeko if its still open i can look at this

**Comment by xmedeko** [comment]
@mdaj06 I am not a lodash project maintainer. I have just raised a suggestion. Some project maintainer should decide, what may be added/changed/removed in the project.
