### ISSUE TITLE
New utility function proposal: _.not

### ISSUE THREAD

**Issue by apadmarao** [lodash/lodash#476]
Hello,

What do you think of adding an "_.not" function, that takes the logical inverse of its input?

```
_.not(value) = function(value) { return !value; }
```

It is super useful creating clean compositions:

```
_.compose(_.not, _.isArray)

function reject(collection, callback) {
  return _.filter(collection, _.compose(_.not, callback));
}
```

To a lesser extent, I wonder why all Javascript arithmetic, comparison, and logical operators have not made available in lodash as functions.

**Comment by servel333** [comment]
Since I found this trying to remember the name of the current method that does this, I'd like to add that it's named [`_.negate`](https://lodash.com/docs/4.17.4#negate) for future reference.
