### ISSUE TITLE
Median value of array

### ISSUE THREAD

**Issue by ali5991jalali** [lodash/lodash#4762]
One of the most important functions any numeric array needs to have is median.
I developed function for loadash to return median of array you can see here

`
const median = (array) => {
    array.sort((a, b) => b - a);
    const length = array.length;
    if (length % 2 == 0) {
        return (arr[length / 2] + arr[(length / 2) - 1]) / 2;
    } else {
        return array[Math.floor(length / 2)];
    }
}
`

**Comment by falsyvalues** [comment]
Hi @ali5991jalali!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
Related to #1703 and #2184.

**Comment by calvinfroedge** [comment]
+1, need median

**Comment by EMMANUEL-07** [comment]
+1, need median

**Comment by UHaider** [comment]
+1

**Comment by JeremyRippert** [comment]
+1

**Comment by mdmahbubhelal** [comment]
+1

**Comment by MarcAMartin** [comment]
+1

**Comment by dangbert** [comment]
Why is this issue closed?

+1 for _.median() !

**Comment by kallewesterling** [comment]
Agreed, yes please!

**Comment by ElixirMike** [comment]
+1

**Comment by AKnowlesAtDigit** [comment]
+1

**Comment by antofa** [comment]
+1

**Comment by CjJordan** [comment]
+1

**Comment by asyndesis** [comment]
+1

**Comment by timotheeg** [comment]
+1

**Comment by PhilDakin** [comment]
+1

**Comment by Guilhermevps** [comment]
+1
