### ISSUE TITLE
TypesScript types for lodash/fp

### ISSUE THREAD

**Issue by jayarjo** [lodash/lodash#4765]
Are there types for `lodash/fp` available?

**Comment by falsyvalues** [comment]
Hi @jayarjo!

Discussion related to types should definitely go to ➡️[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) contributors of [@types/lodash](https://www.npmjs.com/package/@types/lodash) and others. We are not creating or maintaining type definitions for TypeScript.
