### ISSUE TITLE
Check array and return each value with it's number of existence

### ISSUE THREAD

**Issue by ali5991jalali** [lodash/lodash#4766]
One of the most important things in arrays to check all values and get a number of existence for each value as an object.I can add this method to lodash 

return object: 
`{
"apple':1,'orange':5,'banana':3
}`

**Comment by daedalus28** [comment]
I'm not sure I fully understand the request, but from what I gather, this is just `_.countBy(_.isObject)` (using lodash/fp here for conciseness) right?

In my experience, simple compositions are not generally added to lodash unless there are a lot of upvotes. I think the typical lodash org thing to do here would be to close this issue with a message like this:

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by bnjmnt4n** [comment]
Try [_.countBy](https://lodash.com/docs/4.17.15#countBy):

```js
_.countBy(["a", "a", "b", "c"]);
// Object { a: 2, b: 1, c: 1 }
```
