### ISSUE TITLE
security vulnerability for latest Lodash version in ng2-charts.js

### ISSUE THREAD

**Issue by Kashish2394jn** [lodash/lodash#4769]
My code is showing security vulnerability for latest lodash version in latest ng2-charts.js.

Is there any patch fix to be coming soon ???

**Comment by SudharsanSukumar** [comment]
Seeing the same in my repo

**Comment by mdeknowis** [comment]
Is it the same as https://github.com/lodash/lodash/issues/4738 ?

**Comment by falsyvalues** [comment]
Closing as duplicate of #4744
