### ISSUE TITLE
Cannot find module './_baseGetTag'

### ISSUE THREAD

**Issue by phosphotungstic** [lodash/lodash#4772]
Hi, I'm using version 4.17.15 with electron and I'm having issues where when my application starts up, I immediately get the error "Cannot find module './_baseGetTag". It looks like it's from isFunction.js

Is there any reason this could be happening? Thanks!

**Comment by falsyvalues** [comment]
Hi @phosphotungstic!

That might be related to your bundling / build system, please verify this as a first step.

**Comment by kamolins** [comment]
@phosphotungstic I was having similar issues and I just figured it out. Yarn was getting `lodash` from a cache and for some reason the cached version was distorted.
I figured it out by running `yarn --verbose`
Try to run: `yarn cache clean lodash` and see if that helps!

**Comment by beaugunderson** [comment]
adding for future searchers: `yarn cache clean lodash` and a reinstall also fixed this error:

```
Module not found: Can't resolve './_arrayLikeKeys' in '/Users/beau/p/tracking-tool/node_modules/@welldone-software/why-did-you-render/node_modules/lodash'
```

**Comment by dariush-hojabrian-geeksltd** [comment]
Thanks guys, **yarn cache clean** fixed the issue for me too
