### ISSUE TITLE
High severity vulnerability in 4.17.11

### ISSUE THREAD

**Issue by somsharp** [lodash/lodash#4774]
A prototype pollution vulnerability in lodash. It allows an attacker to inject properties on Object.prototype

**Comment by taltal78** [comment]
Also in other versions.. 4.17.13 and 4.17.15

**Comment by mdeknowis** [comment]
Is it the same as https://github.com/lodash/lodash/issues/4738 ?

**Comment by falsyvalues** [comment]
Closing as duplicate of #4744
