### ISSUE TITLE
High severity vulnerability in 4.17.15 in baseZipObject.js │ baseZipObject() 

### ISSUE THREAD

**Issue by Erik-BI** [lodash/lodash#4775]
Run `npm audit` in the project and get thousands of this. 
![image](https://user-images.githubusercontent.com/57289416/81686116-b6723080-949b-11ea-96d0-bfc4234a9176.png)

Lodash Package for Node.js .internal/baseZipObject.js       
│   baseZipObject() Function Property Manipulation Resource      
│   Exhaustion DoS 
│ Package       │ lodash                                                       
│ Dependency of │ @babel/core [dev]                                            
│ Path      │ @babel/core > @babel/helper-module-transforms >              
│               │ @babel/helper-replace-supers > @babel/traverse >             
│               │ @babel/generator > lodash                                    
│ More info     │ https://vulndb.cyberriskanalytics.com/vulnerabilities/228535

**Comment by wrslatz** [comment]
Potential duplicate of #4774 and #4738 ?

**Comment by Erik-BI** [comment]
no, I check both of them before I open this, different method

**Comment by pskfry** [comment]
just encountered this in our enterprise security scanner

**Comment by falsyvalues** [comment]
Closing as duplicate of #4744

**Comment by deepikascetest** [comment]
When is this going to be released? I see that the issues are closed.

**Comment by falsyvalues** [comment]
@deepikascetest Please take a look on connected Pull Requests.
