### ISSUE TITLE
Security issue reported by scanner in 4.17.15

### ISSUE THREAD

**Issue by marcpo** [lodash/lodash#4776]
This security issue is marked as a high vulnerability by WhiteSource scanners.  Could this be addressed ? Or is it a false positive ? 

It was first reported 7 months ago and latest published version 4.15.17 (10 months ago)

> Source: CERT
> Name: https://hackerone.com/reports/712065
> Url: https://hackerone.com/reports/712065

**Comment by falsyvalues** [comment]
Closing as duplicate of #4744
