### ISSUE TITLE
Prototype Pollution reported by Veracode

### ISSUE THREAD

**Issue by EmanuilIvanovv** [lodash/lodash#4777]
Hello, 

Since the last few days Veracode reports a prototype pollution vulnerability in 4.17.15 (and below) version of the lodash library. 

Vulnarability URL: https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-25079/summary

Is there a plan to fix this or is it a false-positive issue?

Best Regards,
Emanuil

**Comment by falsyvalues** [comment]
Closing as duplicate of #4744
