### ISSUE TITLE
cloneDeep does not clone/remove deep functions but keeps references

### ISSUE THREAD

**Issue by YuriGor** [lodash/lodash#4781]
Hi, I found this discussion #3558
But it's closed with an incorrect final decision.
Here is a doc for cloneDeep:
> This method is like _.clone except that it recursively clones value.

So I expect not only cloned object itself will be not a reference to the source,
but all the nested deep values will be also cloned.

But in case of deep function values, it's not true, deeply cloned functions are references to their respective originals in the source object

According to this decision:
> The main sticking point is the return value be a clone or value that isn't === to the one provided, not necessarily the properties of the value.

there is no guaranteed difference between clone and cloneDeep.

**Comment by Sykander** [comment]
If this feature was to be implemented. 

Would you propose to keep references to properties like `prototype` on functions or clone them also ? How about `this` context ?

**Comment by YuriGor** [comment]
I don't suggest cloning functions, this issue is about bug in current cloneDeep implementation.
I expect 'cloneDeep' will behave consistently with 'clone'
Clone is creating empty objects instead of functions, but cloneDeep doesn't do the same for deep functions nested inside cloned object.
As a result deeply cloned object still shares references with its original.
