### ISSUE TITLE
_.pickBy + _.identity removes zero (0 as number) valued items 

### ISSUE THREAD

**Issue by jousepo** [lodash/lodash#4783]
Hi,
i've a problem with _.pickBy and _.identity. Zero valued items are identified as false.
There is an example:
`
var model  = { number: 0 };
var finalModel = _.pickBy(model, _.identity);

console.log(finalModel);
`
finalModel output ---> {}

Lodash Version: "4.17.15"

**Comment by daedalus28** [comment]
This is the expected behavior, because 0 is false in JS. You'll see the same behavior on empty strings, false, null, and undefined:

https://runkit.com/daedalus28/pick-by-identity-gh-question

I suspect you probably want to use `_.isNil` to only omit null/undefined fields

**Comment by jousepo** [comment]
Ok.No problem. 
I thought that the _.identity function it take cares of real identities. Finally i solved using:

`_.omitBy(model, _.isNil);`

Thank you for your answer. Great lib ;-)

**Comment by daedalus28** [comment]
Glad you've got everything sorted out @jousepo, I think we can close this issue.

**Comment by jousepo** [comment]
Of course you can close!!!! Thx again!!!
