### ISSUE TITLE
_.forEach unexpected behaviour with object input

### ISSUE THREAD

**Issue by runk** [lodash/lodash#4785]
Consider this innocent object:

```
const obj = {'height': 10, 'width': 10, 'length': 10 }
```

When running `_.forEach` and some other functions it results in unexpected behaviour since this object is considered "array-like".

```
_.forEach(object, (val) => console.log(val))
```

Prints 10 times `undefined` given `obj` is treated like array of length 10.

Is it expected behaviour by authors? Should I PR it?

**Comment by bnjmnt4n** [comment]
Currently this behaviour is expected as lodash treats all objects with a `length` property as array-like “Collections”. Note that this behaviour is likely expected to change in [lodash v5](https://github.com/lodash/lodash/wiki/Roadmap) as we split “Collection” methods into array and object methods.
