### ISSUE TITLE
Fork initiative to solve the Vulnerability impact

### ISSUE THREAD

**Issue by martinoppitz** [lodash/lodash#4786]
I'm aware of the issue and for me at least this is not a high priority issue. All disclosures and issues are not high priority and this one while technically an issue would require zipping objects based on user provided properties arrays . So yes, I will address this but I'm not letting some report ruin my week or plans.

_Originally posted by @jdalton in https://github.com/lodash/lodash/pull/4745#issuecomment-622477124_

**Comment by martinoppitz** [comment]
Hi @jdalton,
I partly understand your explanation, but you should keep in mind that many prominent tools depend on this lodash version.

In a professional environment, vulnerability are prohibited and appropriate tests are integrated into the DevOps pipelines. Now we have the situation that countless builds break and the developers have to ask for an exception.

I hope we can find a quick way out of it.

**Comment by martinoppitz** [comment]
https://github.com/lodash/lodash/issues/4738#issuecomment-629698149

**Comment by martinoppitz** [comment]
Was the community going to fork out this project and break the blockade?

**Comment by rzr** [comment]
Can you suggest a fork that ship:
https://github.com/lodash/lodash/pull/4745

**Comment by martinoppitz** [comment]
Is a Basic fork...

https://github.com/care-for/lodash
