### ISSUE TITLE
cloneDeep does not clone non-indexed properties

### ISSUE THREAD

**Issue by Mayan-t** [lodash/lodash#4789]
Hi.
cloneDeep method does not clone other than indexed properties of Arrays.

`let arr = ["normal item"];`
`arr.nonindexedProp = "nonindexedValue";`
`let arrClone = _.cloneDeep(arr);`
`Object.keys(arr);  // (2) ["0", "nonindexedProp"]`
**`Object.keys(arrClone); //["0"]`**

**Comment by falsyvalues** [comment]
Hi @Mayan-t!

This is by design. Lodash generally treats arrays as straight lists of items.
