### ISSUE TITLE
assginValue has a bug when I want to assign 0 to object

### ISSUE THREAD

**Issue by bigMeowCoding** [lodash/lodash#4791]
assginValue has a bug when I want to assign 0 to object
```
const obj = {a: 'value'};
const a = 1;
assignValue (obj, 'a', a); // {a: value}
```
I think there is a problem here
```
         if (value! == 0 || (1 / value) === (1 / objValue)) {
             baseAssignValue (object, key, value)
         }
```
Intercepted when the newly assigned value is 0
In addition, whether the judgment of negative 0 is superfluous here, after hasOwnProperty and eq method to judge, if the object existing value is +0, the newly assigned value should be intercepted when it is -0

**Comment by Chandler-Davidson** [comment]
I'm not following. Are you saying that the assignment fails when assigning a property the value 0?

Here's what I was testing and didn't see such:

```javascript
const obj = {a: 'value'};
_.assign(obj, {'b': 0}, {'c': -0});
// obj => { a: 'value', b: 0, c: 0 }
```

**Comment by bigMeowCoding** [comment]
@Chandler-Davidson thanks
