### ISSUE TITLE
浮点精度问题（Floating point precision issues）

### ISSUE THREAD

**Issue by codeooq** [lodash/lodash#4792]
### Floating point precision issues
```javascript
console.log(
  _.gte(0.9999999999999999999999999999, 1), // true
  _.gte(0.9, 1) // false
);
```

**Comment by illuminist** [comment]
JS just cant store 0.99999999999999999 (17 nines) as it is.

**Comment by codee09** [comment]
> JS不能按原样存储0.99999999999999999（17个9）。

then...
```javascript
console.log(
      _.gte(0.3, 0.1 + 0.2), // false
      _.gte(0.3, 0.3) // true
);
```
Sorry i didn't quibble!!!

**Comment by illuminist** [comment]
#4778 #4294 #3675

https://www.quora.com/Why-is-0-1+0-2-not-equal-to-0-3-in-most-programming-languages

**Comment by lvl99** [comment]
You'll need to use another library to get around binary systems' [floating point precision errors](https://floating-point-gui.de/languages/javascript/):

```
// Vanilla JS
console.log(
  0.3 >= (0.1 + 0.2), // false
  0.3 >= 0.3 // true
)

// Lodash
console.log(
  _.gte(0.3, 0.1 + 0.2), // false
  _.gte(0.3, 0.3) // true
)

// Using big.js
console.log(
  Big(0.3).gte(Big(0.1).plus(Big(0.2))), // true
  Big(0.3).gte(Big(0.3)) // true
)
```
