### ISSUE TITLE
Debounce 'object doesn't support this action' in IE11

### ISSUE THREAD

**Issue by confidante20** [lodash/lodash#4793]
I have a function that uses lodash's `_.debounce`. This function works fine in other browsers, but in IE, it raises an error when it hits the debounce:

`Object doesn't support this action'

Does lodash debounce work in IE11? Is this a known bug?

**Comment by falsyvalues** [comment]
Hi @confidante20!

This doesn't look like a problem related to Lodash. Version 4 supports IE 11 as well as others.
