### ISSUE TITLE
Prototype Pollution security warning

### ISSUE THREAD

**Issue by jfoclpf** [lodash/lodash#4795]
We have installed snyk on our npm package `autocosts` and snyk is reporting for some weeks a security vulnerability on behalf of `geoip-lite@1.4.2` via  `lodash@4.17.15`

```
Detailed paths
Introduced through: autocosts@jfoclpf/autocosts#fe2c8b8ce19ad42afba866887180461c51bab964 › geoip-lite@1.4.2 › async@2.6.3 › lodash@4.17.15
Remediation: Open PR to patch lodash@4.17.15.
Introduced through: autocosts@jfoclpf/autocosts#fe2c8b8ce19ad42afba866887180461c51bab964 › geoip-lite@1.4.2 › ip-address@5.9.4 › lodash@4.17.15
Remediation: Open PR to patch lodash@4.17.15.
```

![image](https://user-images.githubusercontent.com/3984909/83135701-84410f80-a0e6-11ea-9166-93f1a718922c.png)

That is, your current latest npm version `4.17.15` is triggering and spreading this vulnerability warning everywhere. I'm not sure how severe is this, most likely minor, but it was just FYI.

**Comment by jensneubauer** [comment]
jdalton has [said that this warning is not worth his time](https://github.com/lodash/lodash/pull/4745#issuecomment-622477124), and nobody else is willing or able to merge a pull request and push out a new version, so I wouldn't hold my breath.

**Comment by daedalus28** [comment]
To be fair, @jdalton did say `So yes, I will address this` in the comment @jensneubauer linked - he just didn't commit to a time frame.

Since this seems to be a duplicate report (e.g. of #4738), I think the appropriate thing is to close this issue.

**Comment by jfoclpf** [comment]
Solved by PR https://github.com/lodash/lodash/pull/4745
