### ISSUE TITLE
_.trimStart issue with . (dot) in string

### ISSUE THREAD

**Issue by kudlar** [lodash/lodash#4796]
```
_.trimStart('lodash.abc', 'lodash'); // => ".abc"
_.trimStart('lodash.abc', 'lodash.');   // => "bc"
```
If characters right after dot are in characters to trim, they're removed.

**Comment by QuentinFchx** [comment]
AFAIK ([and according to the example in the documentation](https://lodash.com/docs/4.17.15#trimStart)), the second params (`chars`) is treated as a list of character to strip _as long as they are contiguous_ and not the exact string to remove.

In your first example, you did no't include the dot `.` so the matching stops at `.abc`
In the second one, you included it, so after the dot, it matches `a` wich is in the pool of chars `lodash.` 

```
// Documentation example
_.trimStart('-_-abc-_-', '_-'); // => 'abc-_-'
```
```
_.trimStart('lodash.abc', 'lodash');   // => ".abc"
_.trimStart('lodash.abc', 'dashlo');   // => ".abc"
_.trimStart('lodash.abc', 'blodasch.'); // => ""
```
