### ISSUE TITLE
Snyk Medium Severity - Prototype Pollution Vulnerability

### ISSUE THREAD

**Issue by andrew-itscript** [lodash/lodash#4798]
Hi guys,

First of all thank you for your great work!

Do you have plans to fix this issue and publish new version? If so, could you give any estimations as security audit companies chasing e-commerce projects to fix it, but obviously a lot of dependencies depends on lodash. Yes there are Snyk PR which can fix it, but it looks so ugly because we start to depend strictly on Snyk itself in our dependecies.

![snyk-lodash-medium](https://user-images.githubusercontent.com/29883742/83481049-fa6abb00-a4c6-11ea-9e13-eae3d44c966c.png)

**Comment by henryglendening-wwt** [comment]
There's a code fix and issue open, but I think they forgot to merge it https://github.com/lodash/lodash/pull/4745

**Comment by henryglendening-wwt** [comment]
There's a code fix available and issue open, but I think they forgot to merge it - https://github.com/lodash/lodash/pull/4745

**Comment by bvandermeersch** [comment]
They didn't forget, the repo owner is just irresponsible.
