### ISSUE TITLE
How to use lodash-es using import in Node 14?

### ISSUE THREAD

**Issue by josdejong** [lodash/lodash#4800]
I'm trying to use `lodash-es` in the latest Node 14, which has out of the box support for ES modules 🎉. This means it we do not need any transformation steps in order to load ES modules in a plain node.js application. 

When I create the following test file `test.js`:

```js
// test.js
import { first } from 'lodash-es'

console.log(first([1, 2, 3])) // should print 1
```
And then run it using Node 14:
```bash
$ node test.js
```
It does not work but gives the following error:
```
$ node test.js
file:///.../test.js:1
import { first } from 'lodash-es'
         ^^^^^
SyntaxError: The requested module 'lodash-es' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
```
This is because node.js treats the files in `lodash-es` as CommonJS instead of ES6 modules. To solve this, `lodash-es` must somehow explain to node.js that it's containing modules, which as far as I know can be done in two ways ([see nodejs docs](https://nodejs.org/api/esm.html#esm_enabling)):

- Add the field `"type": "module"` in `package.json`. I tested this and this works. However, in the past there was an issue with this field, see https://github.com/lodash/lodash/issues/4359, so I'm not sure if we can just do that.
- Give all the files an extension `*.mjs` instead of `*.js`.

**Comment by artemjackson** [comment]
There should be `"exports"` field in `package.json` for correct behavior, see https://nodejs.org/api/esm.html#esm_conditional_exports

**Comment by Ognian** [comment]
I have both:
- my source file is named .mjs 
- and `"type":"module"`in my package.json 

but I get the following error:
```
/Users/ogi/Repositories/IMS/IMS_v2/packages/imsdoctools/node_modules/lodash-es/merge.js:1
import baseMerge from './_baseMerge.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:121:15)
    at ModuleJob.run (internal/modules/esm/module_job.js:138:23)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
```
Any ideas?
Ognian

**Comment by damianobarbati** [comment]
@artemjackson is correct, exports must be set in package.json.
Otherwise you will never use any lodash function requiring another lodash function:
```javascript
import sumBy from 'lodash-es/sumBy.js';
```
Results in:
```
/Users/damians/Desktop/adwords-analytics/node_modules/lodash-es/sumBy.js:1
import baseIteratee from './_baseIteratee.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by xiaoxiangmoe** [comment]
see pr: https://github.com/lodash/lodash/pull/4826

**Comment by bnjmnt4n** [comment]
For reference, we did this in the past but had to revert it due to breakage in older npm versions. See #4289, #4292, #4358 and #4359. It's unlikely that this will happen in `lodash-es` v4, as that would be a breaking change. We'll definitely look into including this in v5, especially given that we've converted our main codebase to use ESM.

**Comment by nickmccurdy** [comment]
npm 3.9.5 is very old. It should be fine to raise the dependency on it in a breaking change, then use the next major for the long-term full ESM conversion

**Comment by rifler** [comment]
also, it would be great to make `lodash` a dual commonjs/es module package:
https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_dual_commonjs_es_module_packages

webpack supported it in v5 - https://github.com/webpack/webpack/issues/9509

after that, `lodash-es` can be deprecated, because `lodash` will work with require and import as well

**Comment by mreinstein** [comment]
>  it would be great to make lodash a dual commonjs/es module package:

I think dual packages are going to be more headache than they are worth. Adds unnecessary complexity to an already complicated module system. The simpler thing would be to fully convert to es modules, drop commonjs, and bump the major version number so it's clear that it's a breaking change. Old codebases stay on < v5, new codebases or the ones that have the resources to update will use v5

**Comment by damianobarbati** [comment]
I totally agree with @mreinstein .

**Comment by rifler** [comment]
> Old codebases stay on < v5, new codebases or the ones that have the resources to update will use v5

Good idea too! It is important to support two versions at once. Also, if there will be new breaking change (by other reason), lodash will release 2 new versions - 6 and 7

**Comment by gilbert** [comment]
Does this mean there is no current workaround for importing lodash in node 14 using esm?

**Comment by mreinstein** [comment]
@gilbert  you could use the `esm` package, which works pretty well: https://www.npmjs.com/package/esm

**Comment by privatenumber** [comment]
I like the solution proposed by @rifler but in the interim, can `type: 'module'` just be added to `lodash-es` (https://github.com/lodash/lodash/pull/4826)?

Seems like a very easy change that can immediately unblock Node.js ESM users.

**Comment by machineghost** [comment]
> @gilbert you could use the `esm` package, which works pretty well: https://www.npmjs.com/package/esm

Except JDD has stopped maintaining that package, so (even though there's a PR waiting that fixes it) you currently can't use modern nullish coalescing operators with `esm` (and JDD has sat on that PR for *months* now, so don't hold your breath waiting for to be accepted).

**Comment by mreinstein** [comment]
> you currently can't use modern nullish coalescing operators with esm

first world problems, man.  ;)

**Comment by machineghost** [comment]
Heh, I know ... but is it really so much to ask for modern ES modules AND modern JS syntax?

**Comment by bnjmnt4n** [comment]
Hi everyone! I've added `type: module` in v4.17.20, so Node.js 14 should be able to import lodash-es without issues!

**Comment by josdejong** [comment]
Thanks a lot Benjamin, I can confirm this solves the issue 🎉

**Comment by bppdddqqqq** [comment]
> 
> 
> Hi everyone! I've added `type: module` in v4.17.20, so Node.js 14 should be able to import lodash-es without issues!
```

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\node_modules\lodash-es\lodash.js
require() of ES modules is not supported.
require() of D:\node_modules\lodash-es\lodash.js from D:\node_modules\@factor\api\utils-lodash.ts is an ES module file 
as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename lodash.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\node_modules\lodash-es\package.json.
```

I am unsure whether the solution should be added as a hotfix. It's a breaking change and it broke Factor package because it uses "^4.17.15" as version of this package.

**Comment by damianobarbati** [comment]
@bnjmnt4n thanks so much, great move forward for the ecosystem!

My 2 cents:
- it should be a major release

- `exports` should be used  if you want to let people do this
```
import sum from 'lodash-es/sum
``` 
instead of this
```
import sum from 'lodash-es/sum.js
```

**Comment by machineghost** [comment]
I don't think the Lodash team has any say in that.  The Node organization (in typical "why did we put these idiots in charge?" fashion) has decided that they can no longer support ES Module imports unless those imports include file extensions.

I can't express how much I disagree with that decision ... but ultimately all JS code (including Lodash) has to abide by it.

**Comment by mreinstein** [comment]
>  The Node organization has decided that they can no longer support ES Module imports unless those imports include file extensions.

That's probably because all of the browsers are using that same convention and they're trying to move away from magic node-only module-isms.

> why did we put these idiots in charge?

c'mon man, not helpful.

**Comment by privatenumber** [comment]
@machineghost 

I suggest you provide your feedback politely and constructively to the appropriate repositories.

This is off-topic but the reasoning is because it's ambiguous. The cost of implicit file resolution is much more obvious over HTTP, but there's still a guessing cost over FS, which adds up with larger dependency trees. On top of that, it creates room for error when there's an extension-less file.

**Comment by machineghost** [comment]
Apologies, I've edited my comment.

**Comment by bppdddqqqq** [comment]
I think the change may bring breaking behaviour for 4.17.15 -> 4.17.20 or packages which use ^ in version number.

One of the packages is Factor CMS, which uses lodash-es@^4.17.15 and the change made the package unlaunchable due to ERR_REQUIRE_ESM error.

**Comment by Akash-Preet** [comment]
![2021-02-26_16h24_56](https://user-images.githubusercontent.com/16293043/109291726-50e70900-784f-11eb-828b-3f343753b1f0.png)
What am I doing wrong ?

**Comment by josdejong** [comment]
@Akash-Preet you're using the library `lodash`, that should be `lodash-es`

**Comment by wesley-spencer** [comment]
> There should be `"exports"` field in `package.json` for correct behavior, see https://nodejs.org/api/esm.html#esm_conditional_exports

What am I suppose to export?

**Comment by josdejong** [comment]
@wesley-spencer that field should be in [the `package.json`](https://unpkg.com/browse/lodash-es@4.17.21/package.json) of the `lodash-es` library

**Comment by wesley-spencer** [comment]
If you're using Nuxt 3 or nuxt-bridge make sure to put lodash-es in your nuxt.config.js file.

```
build: {
    transpile: ["lodash-es"]
  }
```

**Comment by TheBrockEllis** [comment]
> I think the change may bring breaking behaviour for 4.17.15 -> 4.17.20 or packages which use ^ in version number.
> 
> One of the packages is Factor CMS, which uses lodash-es@^4.17.15 and the change made the package unlaunchable due to ERR_REQUIRE_ESM error.
> 
> I've had to resort to setting a hard resolution for 4.17.15, I am on my way to notify the developers about the issue. But I think it's necessary to state it here as well

I can confirm as this just happened to us. We upgraded lodash-es as part of a monthly security audit and it was upgraded to `lodash-es: ^4.17.21` and immediately can ran into issues running our test suite (getting the same `ERR_REQUIRE_ESM` that the OP referenced). We had to revert to hard resolution of 4.17.15 to fix the issue.

@bnjmnt4n mentioned earlier in the thread:

> It's unlikely that this will happen in lodash-es v4, as that would be a breaking change. We'll definitely look into including this in v5, especially given that we've converted our main codebase to use ESM.

I'm curious as to what changed to allow a breaking change to be introduced in a patch version. I understand that each project is unique and we probably have deficiencies in our code that we could get done to avoid this, but I feel like even the possibility of a change breaking some builds should be enough to warrant a major change version in a dependency.

**Comment by rrolla** [comment]
> If you're using Nuxt 3 or nuxt-bridge make sure to put lodash-es in your nuxt.config.js file.
> 
> ```
> build: {
>     transpile: ["lodash-es"]
>   }
> ```

Thanks this help me with nuxt3

**Comment by artuska** [comment]
I still got an error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /app/node_modules/lodash-es/trimEnd.js from /app/dist/src/api/page/controllers/page.js not supported.
Instead change the require of trimEnd.js in /app/dist/src/api/page/controllers/page.js to a dynamic import() which is available in all CommonJS modules.
```

node: 18.18.2
