### ISSUE TITLE
try _.lowerCase('mJ');

### ISSUE THREAD

**Issue by jitension** [lodash/lodash#4802]
When you have uppercase in the middle of the string, then it adds extra space in the result.

I tried native lowercase and it works fine.

`   _.lowerCase('mJ'))  -> 'm j'  
`

![image](https://user-images.githubusercontent.com/23263252/83683842-02545900-a5b4-11ea-9ea0-082c2b0ebc7e.png)

**Comment by aashutoshrathi** [comment]
@jitension I think the same is expected from function.
Check: https://github.com/lodash/lodash/blob/e51a424513fbbe83a34c1b3c21f8c5478e79389f/lowerCase.js

**Comment by jitension** [comment]
@aashutoshrathi thanks for the response. Though that's not what I would expect out of lowercase. what you think?

**Comment by aashutoshrathi** [comment]
Yes, I was surprised at first too.
`_.lowercase` should ideally convert to lowercase, but I here they implemented it so that, it can convert single word to space-separated words (splitting on the basis of the capital letter).
I think the name is ambiguous.

**Comment by antekai** [comment]
- `_.lowerCase` is for **programming case** conversion (from LowerCase, lowerCase, lower_case, LOWER_CASE, lower-case ====> lower case)
- `_.toLower` is for **letter case** conversion
https://lodash.com/docs/4.17.15#toLower

**Comment by agarzola** [comment]
Should this ticket be closed? Does it make sense to propose an alternative name for this method and the eventual deprecation of `lowerCase` as too ambiguous?

**Comment by jitension** [comment]
I agree. We should rename it to its intended behavior. lowercase is ambiguous. We had to change around 30+ location after discovering it.

**Comment by maltebaer** [comment]
What about the scenario where you would have multiple uppercase letters, divided by a lowercase letter (to denote a new word/name), then followed by a capitalized word? I know, it sounds really contrived/special but I ran into this issue and was wondering, if it is a intentional outcome of `_.lowerCase`.

So for example for `"BIGiPhone"` I would expect

- `_.lowerCase("BIGiPhone") // "big i phone"`

but instead I get

- `_.lowerCase("BIGiPhone") // "bi gi phone"`

**Comment by Alan-Liang** [comment]
> `_.lowerCase("BIGiPhone") // "bi gi phone"`

Consider `_.lowerCase('XMLHttpRequest')`, and we would (perhaps) also have `XMLReParser`, so I think that it is an intentional behavior.

**Comment by bnjmnt4n** [comment]
As mentioned, you can use `toLower` to merely convert characters to lower case, while `lowerCase` aligns with the other `*Case` methods and splits strings into separate words before converting their case. The documentation does provide explicit examples on how `lowerCase` works, and I believe we'll reconsider the behaviour of some of lodash's string functions in the next version.
