### ISSUE TITLE
reject(arrayOfVals, val) unexpected behavior

### ISSUE THREAD

**Issue by andrewluetgers** [lodash/lodash#4803]
so was expecting reject to remove any value I plug in via shorthand but apparently this is not the case and requires an iterator function to work as expected. Any possibility this could become an acceptable usage?

```
// expected
reject([1, 2, 3], 2)
[1, 3]

reject(['a', 'b', 'c'], 'b')
['a', 'c']

// actual
reject([1, 2, 3], 2)
[1, 2, 3]

reject(['a', 'b', 'c'], 'b')
['a', 'b', 'c']

// works with iterator
reject([1, 2, 3], val => val === 2)
[1, 3]

reject(['a', 'b', 'c'], val => val === 'b')
['a', 'c']

```

**Comment by Chandler-Davidson** [comment]
I don't see any added benefit outside of shorthand for equality and then it would be more likely you would provide a path to a property on the element instead.

Could you provide a real-world example of filtering an array based on a value literal?

**Comment by andrewluetgers** [comment]
Thanks, looks like I need to peruse the dics a bit more!
