### ISSUE TITLE
Proposal for new Object function _.increment

### ISSUE THREAD

**Issue by willbattel** [lodash/lodash#4805]
The idea is simple. Say you have an object with numeric values, and you want to increment one of those values while also handling the case where it is not yet defined.

Here is where this new function comes in to save the day (read: save 30 seconds of writing two lines of code instead of one)
```
var object = { 'a': [{ 'b': { 'c': 3 } }] };

_.increment(object, 'a[0].b.c', 100);
console.log(object.a[0].b.c);
// => 103

_.increment(object, 'a[0].b.c', -50);
console.log(object.a[0].b.c);
// => 53

_.increment(object, 'x', 20);
console.log(object.x);
// => 20
```
The `_.increment` function is just a simple but handy combination of the existing `_.get` and `_.set` functions. Thoughts?

**Comment by Chandler-Davidson** [comment]
I feel that an `increment` function is too specific of a use-case and redefines existing javascript methods.

**Comment by willbattel** [comment]
Well, it was worth a shot. I would have liked to see it included but I understand it is somewhat niche. I personally think it would be a good lightweight addition to the library that fits the theme of lodash but if that's not the popular opinion then that's that.

**Comment by bnjmnt4n** [comment]
I believe the [update](https://lodash.com/docs/4.17.15#update) function and some simple functional composition provides a simple way to do that:

```js
var increment = (object, path, inc) =>_.update(object, path, function(n) { return n + inc; });
```
