### ISSUE TITLE
Remove Property from Object Array 

### ISSUE THREAD

**Issue by raj-here** [lodash/lodash#4806]
```
const obj = { "a": [{ "b": { "c": 7 } }, { "b": { "c": 7 } }, { "b": { "c": 7 } }, { "b": { "c": 7 } }] };

  console.log(JSON.stringify(obj));
  _.unset(obj, 'a[0].b.c');
   console.log(JSON.stringify(obj));
```

In above snippet of code, 
we are passing index **(a[0])**, 
Is there any way by which we can remove **b.c** from object array

**Comment by Chandler-Davidson** [comment]
Do you mean remove all instances of **b.c**? So your output would be:  
`{ "a": [{ "b": { } }, { "b": { } }, { "b": { } }, { "b": { } }] }; `

If so, you need to iterate through your array and remove each instance. Like the following:
`
const object = { 'a': [{ 'b': { 'c': 7 } }, { 'b': { 'c': 9 } }] };
const removeBC = (el) => _.unset(el, 'b.c');
_.map(object.a, removeBC));

// object = { a: [{ b: { } }, { b: { } } ]}
`

**Comment by bnjmnt4n** [comment]
As @Chandler-Davidson mentioned, you can compose lodash functions to unset properties within arrays.
