### ISSUE TITLE
_.escapeRegExp does not escape '-'

### ISSUE THREAD

**Issue by sirasistant** [lodash/lodash#4807]
The character '-' determines ranges of characters in regexp. 
Not escaping it can generate some regexp to fail when including escaped characters, since it can make RegExp think that it's representing a range.
Example given:
```
const allowedChars = _.escapeRegExp('+-=');
const wrongRegex = new RegExp(`^[${allowedChars}]*$`);
console.log('0'.match(wrongRegex)); // Should not match, but it does, because 0 is between + and =
console.log('0'.match(new RegExp(/^[\+\-=]$/))); // expected escaping, no match
```

**Comment by falsyvalues** [comment]
Closing as duplicate of #4760
