### ISSUE TITLE
High Vulnerability v4.17.15 : HIGH NSWG-ECO-516  Allocation of Resources Without Limits or Throttling

### ISSUE THREAD

**Issue by cristianbriscaru** [lodash/lodash#4809]
Any news on this vulnerability , if/when is it going to be fixed ?

**Comment by cristianbriscaru** [comment]
Hi @falsyvalues, we are using[ trivy](https://github.com/aquasecurity/trivy) to scan our  Docker images as part of our CI/CD pipelines and trivy is now blocking all our builds as it is detecting lodash v4.17.15 as a HIGH Severity vulnerability with id [NSWG-ECO-516](https://github.com/nodejs/security-wg) : Allocation of Resources Without Limits or Throttling. Not sure how reliable it is as I could not find any more info about this particular vulnerability, worth mentioning is that npm audit and snyk do not find this vulnerability. I will open an issue with trivy as well maybe they can provide more info as to the sources of this vulnerability.

**Comment by cristianbriscaru** [comment]
@falsyvalues managed to find a bit more info, this is the commit that added the vulnerability to the   NSWG database : https://github.com/nodejs/security-wg/commit/166fc1d690daeccb63ab6b2b973bfa3ee3cddcdc . Hope this helps

**Comment by cristianbriscaru** [comment]
@falsyvalues apparently there is a PR with a fix for this : https://github.com/lodash/lodash/pull/4759

**Comment by Bessonov** [comment]
Related or dupe of https://github.com/lodash/lodash/issues/4738 ?

**Comment by falsyvalues** [comment]
Closing as duplicate of #4744
