### ISSUE TITLE
Question: How to reduce to specific keys in a collection

### ISSUE THREAD

**Issue by raDiesle** [lodash/lodash#481]
Hi,

My usecase is very common:

``` js
var clutteredCollection = [
  { 'id' : 1, 'name' : 'David', 'password' : 'test'},
  { 'id' : 2, 'name' : 'Peter', 'password' : 'psw'} 
];
```

I'd like to reduce my collection for specific keys, to e.g. make it more visible
in the code, what attributes are actually needed on the whole collection:

e.g.

``` js
var neededAttributes = _.keys(clutteredCollection, ['id', 'name'] );
// -->[
  { 'id' : 1, 'name' : 'David'},
  { 'id' : 2, 'name' : 'Peter'} 
]
```

Is there a shorthand?

**Comment by itaditya** [comment]
@jdalton as now lodash has placeholder support I can surely do
```js
_.map(clutteredCollection, _.partial(_.pick, _, ['id', 'name']));
```

but in the partial function call the second argument is `_` i.e. the complete lodash instance. 
Does this mean to use this I need to require the complete lodash module.
I really like to cherry pick some lodash functions I need. In this case I can't do it right ?

**Comment by StreetStrider** [comment]
@itaditya check `partial.placeholder`.

**Comment by itaditya** [comment]
@StreetStrider thanks for replying so quickly. I tried googling about `partial.placeholder` but could only find issues referencing it on lodash github. Could you point me to some good material..
Thanks in advance

**Comment by StreetStrider** [comment]
@itaditya check [the docs for `_.partial`](https://lodash.com/docs/4.17.4#partial):
> The _.partial.placeholder value, which defaults to _ in monolithic builds, may be used as a placeholder for partially applied arguments.

**Comment by itaditya** [comment]
As I mentioned I already read it but couldn't make out anything. Maybe that's because I don't have in-depth knowledge of lodash (I mostly use map filter and pick functions :wink: ) Anyways thanks
