### ISSUE TITLE
Bug: sortBy and orderBy fail on (string | number) arrays

### ISSUE THREAD

**Issue by bijection** [lodash/lodash#4810]
For all-string or all-number arrays, lodash matches `Array.sort`:
```js
['b', 'a' ,'c'].sort()
// ['a', 'b', 'c']

_.sortBy(['b', 'a' ,'c'])
// ['a', 'b', 'c']
```

But for mixed arrays, it returns an unsorted result:
```js
['b', 1 ,'c'].sort()
// [1, 'b', 'c']


_.sortBy(['b', 1 ,'c'])
// ['b', 1 ,'c']
```

**Comment by sagar-cs03** [comment]
If no one is working on this, let me take this up..

**Comment by bnjmnt4n** [comment]
`Array#sort` converts all elements to strings when you don't provide a comparator function, hence the sorting behaviour for `Array#sort` is different. In lodash, you can customize the behaviour of sorting yourself by providing custom iteratee functions. If you'd like to emulate `Array#sort` behaviour, try:

```js
_.sortBy(['b', 1 ,'c'], String)
// Array(3) [ 1, "b", "c" ]
```

**Comment by bijection** [comment]
@bnjmnt4n Although using `String` as an iteratee is a fine work-around, it remains that `_.sortBy` has unpredictable behavior when mixing arrays of strings and numbers. Here's an example where the same sequence (`'b', 1, 'c'`) ends up sorted differently in two similar arrays:

```js
_.sortBy(['d', 'b', 1, 'c'])
// ['b', 'c', 'd', 1]

_.sortBy(['b', 1 ,'c'])
// ['b', 1 ,'c']
```

This is probably because both  `'b' < 1 == false` and `'b' > 1 == false`, so as far as lodash is concerned, it's valid to put a number anywhere in a string array and vice-versa. This is especially tricky with long arrays, where a result of `sortBy` might begin with a long sorted run (e.g. the first 100 elements, which are broken out in the chrome console), belying a number-string jumble later on.

One solution could be to make lodash ignore mixed-type arrays when an iteratee is not specified. Another could be to fall back to stringifying elements when an iteratee is not specified. Either way, since the current behavior looks like but doesn't actually match other sorting in the js world, it can be hard to notice, and I think it could save some lodash-user heartache if it were changed.
