### ISSUE TITLE
_.debounce doesn't work in React Native Android if params are passed.

### ISSUE THREAD

**Issue by suraj-amc** [lodash/lodash#4818]
Apparently,   
this would work as expected
`this.onPressDebounced = _.debounce((...params) => this.onPressed(...params), 500)`

but as soon as I put the leading, trailing params, it starts to skip the debouncing behaviour in Android React Native

`this.onPressDebounced = _.debounce((...params) => this.onPressed(...params), 500 , {
         'leading': true,
         'trailing': false
     })`
This is a duplicate of #4008

**Comment by jalalazimi** [comment]
Have you ever try to call it with `useCallback` ? According to React document `useCallback` will return a memoized version of the callback that only changes if one of the dependencies has changed. So It would be helpful for methods like `debounce`.

```
useCallback(_.debounce(()=>......., 500), []);
```

**Comment by bnjmnt4n** [comment]
I don't have much experience with React Native, so I can't say for sure, but given that debounce is tested and works in other environments this is likely a bug in React Native. If you could debug and profile the code during execution, and find any source of errors or possible fixes, please provide more info or send a PR.

**Comment by firstpersoncode** [comment]
simply use this snippet to handle your debounce, (work perfectly on both ios and android):

```
function useDebounce(cb, timeout = 300) {
  const timeoutRef = useRef();

  const handler = useCallback(
    (...args) => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }

      timeoutRef.current = setTimeout(() => {
        cb(...args);
      }, timeout);
    },
    [cb, timeout],
  );

  return handler;
}


// in your component

const handler = useDebounce(async (form) => {
   console.log(form)
   // do your API request or whatever here ...
})

return <Button onPress={handler}>Submit</Button>
```
