### ISSUE TITLE
Add _.flip

### ISSUE THREAD

**Issue by dmmalam** [lodash/lodash#482]
I find I often need to change the order of args of a function. ie, `f(a,b) -> f(b,a)`

The [flip function](https://github.com/rhysbrettbowen/Underscore.Extras#flipfunction-number) makes certain higher order [function practices easier](http://www.reddit.com/r/javascript/comments/1l9gqu/hey_underscorejs_youre_doing_functional/)

Some other functional combinators could be worth considering from [underscore-contrib](http://documentcloud.github.io/underscore-contrib/#function.combinators).

**Comment by jdalton** [comment]
In v3 there's [_.rearg](https://lodash.com/docs#rearg) to allow rearranging arguments.
