### ISSUE TITLE
Inconsistent _.rearg behavior

### ISSUE THREAD

**Issue by federicojasson** [lodash/lodash#4820]
This is a bug report.

From the [rearg docs](https://lodash.com/docs/4.17.15#rearg):
> Creates a function that invokes func with arguments arranged according to the specified indexes where the argument value at the first index is provided as the first argument, the argument value at the second index is provided as the second argument, and so on.

What's the issue?
`rearg` is not mapping arguments as expected when the number of input arguments is less than the arity of the wrapped function.

Example:
```
var rearged = _.rearg(function(a, b) {
  return [a, b];
}, [0, 0]);
```

Call: `rearged('b');`
Expected result: `[ 'b', 'b' ]`
Actual result: `[ 'b', undefined ]`

When the function is called with a second argument, the actual result is the expected one:

Call: `rearged('b', 'foo');`
Result: `[ 'b', 'b' ]`

Please let me know if this is expected behavior or an actual bug. I'm willing to work on a fix.

**Comment by joaoGabriel55** [comment]
Hello @federicojasson and @falsyvalues. How can I test this rearg function from lodash source code? Because, I am having problems to find this function implementation and currently this rearg function test is not present when I run `npm test`.

Waiting for your feedback.

**Comment by StasJDM** [comment]
Hello everyone! I found this issue and wanted to fix it, but ran into the same problem as @joaoGabriel55. I cloned this repository and didn't find the `rearg.js` file listed. It only exists in the `tests` folder, however it is not in the library itself.

Please let me know if I am doing something wrong or if there is any news regarding this issue.

**Comment by geareo** [comment]
there is no issued with this function from the point that its just reorganize the arguments otherwise the bad use of it 
rearged('b') -> you have to supply the second argument otherwise you get the undefined for the second reorganized argument.
