### ISSUE TITLE
cloneDeep gets longer and longer

### ISSUE THREAD

**Issue by Lempkin** [lodash/lodash#4821]
I have a component which display list of elements, which can be filtered.
Every time a filter is applied, I have to cloneDeep the list of elements.
Problem is that cloneDeeps is taking longer and longer to process.

I use cloneDeep this way : 
```
import cloneDeep from 'lodash/cloneDeep';
...
this.copyRows = cloneDeep(this.rows); 
...
this.flattenedRows = cloneDeep(this.displayedRows);
```

I've added some console.log() that show that time is approximately x2 each time I apply a new filter.
If I navigate outside the page, and then come back on this page, 1st filter takes normal time, and then increase every time that we ask for a new filter.
NB : It's not about the filter that I used, I've tried with a boolean filter and switch it to true/false many time, and every time the cloneDeep processing time increase.

Is there any cache or something I can force clean?
Many thx

**Comment by thxiami** [comment]
Can u give a more specific example. I'm not really aware of how u calculated the time, like below?
```js
var start = Date.now()
this.copyRows = cloneDeep(this.rows); 
console.log('spend: ', (Date.now() - start)/1000, ' s') // time1
...
start = Date.now()
this.flattenedRows = cloneDeep(this.displayedRows);
console.log('spend: ', (Date.now() - start)/1000, ' s') // time2
```
And 
> I've added some console.log() that show that time is approximately x2 each time I apply a new filter.

You said that  time is approximately x2 each time I apply a new filter, which time u used to compare ? Can u give a more specific example, which helps us understand how u filter data and how to calculate the time

**Comment by YuriGor** [comment]
Is it possible source object is growing each time?
to check it try to use cloneDeepWith and count like this:
```js
...
let count = 0;
this.copyRows = cloneDeepWith(this.rows, ()=>{count++}); 
console.log(`cloned total ${count} nodes from rows`);
...
let count = 0;
this.flattenedRows = cloneDeepWith(this.displayedRows,()=>{count++;});
console.log(`cloned total ${count} nodes from displayedRows`);
```
And check if this count remains the same after each cloning.

If it's also growing - probably your data is mutated somewhere.

**Comment by bnjmnt4n** [comment]
I don't think this is actionable unless we can get a simple reproduction. For now, @YuriGor's advice seems like a good place to start to determine if this is a lodash issue.
