### ISSUE TITLE
merge() doesn't throw any Error when source object is frozen

### ISSUE THREAD

**Issue by sheff146** [lodash/lodash#4822]
### Description
I'm calling **merge()** on a frozen object.
```js
const frozen = Object.freeze({ a: "1" });
merge(frozen, { a: "2", b: "123" });
```

### Expected behavior
I would expect **merge()** to throw an **Error** in this case.

### Actual behaviour
**merge()** silently completes leaving the destination object without change.

Codesadbox illustrating the issue: https://codesandbox.io/s/lodash-merge-frozen-hos4h?file=/src/index.js.

**Comment by gagyibenedek** [comment]
If no one is working on this I'll try my luck wit it.

**Comment by bnjmnt4n** [comment]
This behaviour is intentional, as lodash attempts to avoid throwing errors as much as possible. For the same reason, passing a `null` or `undefined` value to `_.merge` also does not throw an error.

**Comment by lukeapage** [comment]
lodash code is not in strict mode.

If you use lodash-es it works.
