### ISSUE TITLE
Javascript version of C++ equal_range via lower_bound and upper_bound

### ISSUE THREAD

**Issue by claytonjwong** [lodash/lodash#4823]
Hi, since JS lacks a binary search, could we add one to Lodash?  I'm new to JS and Lodash, is there a development guide for getting started with adding new functionality to Lodash?  Here's what I was thinking:

```
/*
 * Javascript version of C++ equal_range via lower_bound and upper_bound
 *
 * Input: The array A in ascending order and a target T
 * Output: The tightly bound indices [i, j] where A[i] <= T < A[j] if T exists in A
 * otherwise [-1, -1] is returned if T does not exist in A
 */

let lowerBound = (A, T) => {
    let N = A.length,
        i = 0,
        j = N - 1;
    while (i < j) {
        let k = Math.floor((i + j) / 2);
        if (A[k] < T)
            i = k + 1;
        else
            j = k;
    }
    return A[i] == T ? i : -1;
};

let upperBound = (A, T) => {
    let N = A.length,
        i = 0,
        j = N - 1;
    while (i < j) {
        let k = Math.floor((i + j + 1) / 2);
        if (A[k] <= T)
            i = k;
        else
            j = k - 1;
    }
    return A[j] == T ? j + 1 : -1;
};

let equalRange = (A, T) => {
    return [lowerBound(A, T), upperBound(A, T)];
};
```

**Comment by Chandler-Davidson** [comment]
In my opinion, this feels too specific for Lodash as the library is typically only expanding on the "standard library" of JavaScript. I think this would fit better in a search/sorting library.

**Comment by bnjmnt4n** [comment]
Lodash does provide [`_.sortedIndexOf`](https://lodash.com/docs/4.17.15#sortedIndexOf) and related functions to perform a binary search for a value. To construct a function with the API you provided, you can do something like the following:

```js
const sortedIndexOf = require("lodash/sortedIndexOf");
const sortedLastIndexOf = require("lodash/sortedLastIndexOf");

const equalRange = (array, value) => {
    const startIndex = sortedIndexOf(array, value);
    const endIndex = sortedLastIndexOf(array, value);
    
    return [startIndex, endIndex];
};
```

**Comment by SyaoranChang** [comment]
Hi,

version: https://raw.githubusercontent.com/lodash/lodash/4.17.10-npm/lodash.js
I try this.
var array = ["2","10","30","40"];
// use lowerBound function
var lowerBound_Result = lowerBound(array , 10);
// use Lodash
var sortedIndexOf_Result= sortedIndexOf(array , 10);

Result:
lowerBound_Result  = 1;
sortedIndexOf_Result = -1;
Seems sortedIndexOf can not be used in a string array.
