### ISSUE TITLE
Which git branch should be based on when submitting a pull request

### ISSUE THREAD

**Issue by thxiami** [lodash/lodash#4827]
Hi, I'd eventually like to contribute in some way but I encountered a problem.

## Brief of question
This is my first time participating in open source work. So I searched for the correct way to submit a PR. Then I found the most appropriate path forward would be to fork, test, and build out of one git branch(e.g. the `master` branch). But after reading the [CONTRIBUTING.md](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md), 
**I was confused about which git branch should I commit to: `master` or `4.17.15-post`**.

## The ways I had tried to solve this problem:

1. Read  [CONTRIBUTING.md](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md)
 In the `Contributing to Lodash` section I found:
> Contributions are always welcome. Before contributing please read the code of conduct & search the issue tracker; your issue may have already been discussed or fixed in `master`. To contribute, fork Lodash, commit your changes, & send a pull request.

It seems like I should checkout a new branch based `master`, but then I found that in the section  `Pull request`:

> For additions or bug fixes you should only need to modify lodash.js. Include updated unit tests in the test directory as part of your pull request. 
 ...
 Before running the unit tests you’ll need to install, npm i, development dependencies. Run unit tests from the command-line via npm test, or open test/index.html & test/fp.html in a web browser. 

I didn't find `lodash.js` under the `master` branch, and `npm run test` also didn't work because of the lack of files needed for building and testing.
But I found the `lodash.js` under the `4.17.15-post` branch,  and `npm run test` could work .

So, if I want to fix a bug, should I develop based on the `4.17.15-post` branch?

Then I found the following paragraph in the `Notice` section:
> Pardon the mess. The master branch is in flux while we work on Lodash v5. This means things like npm scripts, which we encourage using for contributions, may not be working. Thank you for your patience.

Does this mean contributions should not commit to the master branch  for now?

2. Search recent pull requests
To figure it out, I checked some recent pull requests, and found that some were commited based on the `master` branch ([PR#4681](https://github.com/lodash/lodash/pull/4681)), and some were commited based on `4.17.15-post` branch ([PR#4515](https://github.com/lodash/lodash/pull/4515)), so I was  completly confused:

## Detail of  question
1. If I want to fix a bug, which branch should be used for development?

2. If I only modify a document file like `REAMDE.md` or `CONTRIBUTING.md`, which branch should be used to submit?

**Hope someone can help.**

**Comment by thxiami** [comment]
In addition, I have a little question. After cloning the code of the `master` branch to the local, when running `npm run style`, errors :
```
..../lodash/isFunction.js
  16:3  error  Trailing spaces not allowed  no-trailing-spaces
  19:3  error  Trailing spaces not allowed  no-trailing-spaces
  22:3  error  Trailing spaces not allowed  no-trailing-spaces
  25:3  error  Trailing spaces not allowed  no-trailing-spaces

...../lodash/unescape.js
  34:79  error  There should be no space before this paren  space-in-parens
```
Does that expected ? Or the managers will resolve these kind of code style problems before build?

**Comment by thxiami** [comment]
Is anyone could help? Thanks!

**Comment by bnjmnt4n** [comment]
> Pardon the mess. The master branch is in flux while we work on Lodash v5. This means things like npm scripts, which we encourage using for contributions, may not be working. Thank you for your patience.

Hey, as you've noticed the master branch is for lodash's next major version, while the 4.17.15-post branch are for edits to the previous version (v4), which have to be back-ported for bugfixes. So only bugfixes should move into the v4 branch, while other changes should go into master.

**Comment by thxiami** [comment]
@bnjmnt4n First of all thank you very much for your reply!

> Hey, as you've noticed the master branch is for lodash's next major version, while the 4.17.15-post branch are for edits to the previous version (v4), which have to be back-ported for bugfixes. So only bugfixes should move into the v4 branch, while other changes should go into master.

I have added some code locally based on the 4.17.15-post branch, and I plan to submit two PRs later.  But according to your reply above, now I'm a little confused whether they are bugfixes or just enhancements. Can you please help me judge which one they belong to? 

Both PRs are related to` _.clone()` / `_.cloneDeep()`

1. ` _.clone()` and  `_.cloneDeep()` don't clone the `groups` property of array returned by `RegExp#exec `.
```js
let re = /(?<year>\d{4})-(?<month>\d{2})-(?<day>\d{2})/u;
let result = re.exec('2015-01-02');
console.log('result: \n', result)
console.log('result from shallow copy:\n', _.clone(result))
console.log('result from deep copy:\n',_.cloneDeep(result))
```
![image](https://user-images.githubusercontent.com/26535231/86486107-0929e380-bd8d-11ea-9a2c-5b0da625cb49.png)


2. `_.cloneDeep()` dosen't deep clone  the key of `Map`

```js
const obj = {a: 1}
const map = new Map()
map.set(obj, 1)

var deepClonedMap = _.cloneDeep(map)
deepClonedMap.get(obj) // 1, which proves that the key of deepClonedMap is still `obj`

deepClonedMap.forEach((value,key) => {
    console.log('key:', key) // {a: 1}
    console.log('key === obj:', key === obj) // true
})

```

Thanks a lot!

**Comment by thxiami** [comment]
@bnjmnt4n Sorry to bother you, could you please help me solve the above questions? Thanks a lot!
