### ISSUE TITLE
Error: Cannot find module '/lodash/lib/main/build-dist.js'

### ISSUE THREAD

**Issue by parmarmitesh** [lodash/lodash#4833]
I am using npm version:- 6.14.5 and node version:- 12.16.1

Following are steps to build and test the **lodash** package:
1) git clone https://github.com/lodash/lodash
2) npm install
3) npm test

After performing **npm test**, I am getting following error, so can you **help me please** in this or suggest me steps if I missing something.:

> lodash@5.0.0 build /lodash
> npm run build:main && npm run build:fp

> lodash@5.0.0 build:main /lodash
> node lib/main/build-dist.js

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/lodash/lib/main/build-dist.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lodash@5.0.0 build:main: `node lib/main/build-dist.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lodash@5.0.0 build:main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-24T08_20_02_243Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lodash@5.0.0 build: `npm run build:main && npm run build:fp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lodash@5.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-24T08_20_02_303Z-debug.log
npm ERR! Test failed.  See above for more details.

**Comment by bnjmnt4n** [comment]
See [CONTIBUTING.md](https://github.com/lodash/lodash/blob/86a852fe763935bb64c12589df5391fd7d3bb14d/.github/CONTRIBUTING.md):

> Pardon the mess. The master branch is in flux while we work on Lodash v5. This means things like npm scripts, which we encourage using for contributions, may not be working. Thank you for your patience.
