### ISSUE TITLE
_.isEmpty(false) should return false, but returns true

### ISSUE THREAD

**Issue by jhenriquevissotto** [lodash/lodash#4838]
`_.isEmpty(false)` should return `false`, but returns `true`.

`false` is not a empty value.

`null` can be a empty value. `undefined` can be a empty value. But false is a not a empty value.

Thanks

**Comment by Chandler-Davidson** [comment]
The docs, https://lodash.com/docs/4.17.15#isEmpty, state:

> Objects are considered empty if they have no own enumerable string keyed properties.

Because there are no keys on value types, they are considered empty. Same goes for the following:

```javascript
_.isEmpty(true);
// => true
 
_.isEmpty(1);
// => true
```

**Comment by bnjmnt4n** [comment]
As mentioned, this behaviour is intentional and illustrated in the examples on https://lodash.com/docs/4.17.15#isEmpty:

```js
_.isEmpty(null);
// => true
 
_.isEmpty(true);
// => true
 
_.isEmpty(1);
// => true
 
_.isEmpty([1, 2, 3]);
// => false
 
_.isEmpty({ 'a': 1 });
// => false
```

**Comment by jhenriquevissotto** [comment]
No. No, no, no!

I will repeat: `False` condifion IS NOT NOT A EMPTY VALUE and should return true.

**Comment by papb** [comment]
> should return true.

> should return `false`, but returns `true`.

You are contradicting yourself. Which one was a typo?
