### ISSUE TITLE
Prototype Pollution - Bug

### ISSUE THREAD

**Issue by stephanoparaskeva** [lodash/lodash#4841]
<img width="589" alt="Screenshot 2020-07-06 at 18 03 28" src="https://user-images.githubusercontent.com/40718272/86619776-17f1df80-bfb3-11ea-85a8-54f3325a73a3.png">
<img width="589" alt="Screenshot 2020-07-06 at 18 03 41" src="https://user-images.githubusercontent.com/40718272/86619783-1a543980-bfb3-11ea-95ef-96c4739b925e.png">

* I have packages with lodash as a dep, I don't use lodash as part of my project, but over 10 packages I use, rely on it.
* All 6000+ vulnerabilities are from lodash.

**Comment by AgustinAoki** [comment]
https://github.com/lodash/lodash/issues/4837

**Comment by stephanoparaskeva** [comment]
> #4837
