### ISSUE TITLE
[templates] remove empty new lines ("newline slurp")

### ISSUE THREAD

**Issue by fcastilloec** [lodash/lodash#4842]
How can I remove the empty newlines produces by control-flow statements? It seems that lodash doesn't support `-%>` or anything equivalent.
As an example,

```js
const _ = require('lodash')

const template = `%files
/usr/bin/<%= name %>
<% if (_.isObject(icon)) { %>
<% _.forEach(icon, function (path, resolution) { %>
/usr/share/icons/<%= resolution %>/apps/<%= name %>.png
<% }) } else { %>/usr/share/pixmaps/<%= name %>.png<% } %>

More text`

const data = { name: 'lodash', icon: { '16x16': 'lodash16.png', '32x32': 'lodash32.png' } }
_.template(template)(data)
```

The previous code will output :

```
%files
/usr/bin/lodash


/usr/share/icons/16x16/apps/lodash.png

/usr/share/icons/32x32/apps/lodash.png


More text
```

but what I would like to see is:

```
%files
/usr/bin/lodash
/usr/share/icons/16x16/apps/lodash.png
/usr/share/icons/32x32/apps/lodash.png

More text
```

**Comment by nortti** [comment]
You could move the opening tag to the previous line whenever you want a single newline, e.g.

```
...
<% if (_.isObject(icon)) { %><%
 _.forEach(icon, function (path, resolution) { %>
...
```

**Comment by fcastilloec** [comment]
@nortti Thanks for the suggestion! I think I came up with a way to stop any new lines, without compromising readability.

```js
const template = `%files
/usr/bin/<%= name %>
<% if (_.isObject(icon)) {
  _.forEach(icon, function (path, resolution) {
    %>/usr/share/icons/<%= resolution %>/apps/<%= name %>.png
<% }) } else { %>/usr/share/pixmaps/<%= name %>.png<% } %>
```

I still wish that there was a closing that eliminated new lines. It would make things a lot easier to read.

**Comment by bashaus** [comment]
Could you use the `print` function that is available with templates?

```
const template = `<%
if (name) { print(name) }
if (version) { print(version) }
if (description) { print(description) }
%>`

const data = { name: 'Name', version: null, description: 'desc' }

result = _.template(template)(data)
```

**Comment by fcastilloec** [comment]
@bashaus Thanks!!! It seems `print` doesn't insert a new line at the end. I couldn't find any documentation about `print`, do you have a link I could look at?

**Comment by bashaus** [comment]
@fcastilloec I just inferred this from: https://lodash.com/docs/#template
Sorry, I don't have any other documentation for this

**Comment by bnjmnt4n** [comment]
As mentioned, you can use the `print` function within `_.template`. For future reference, the `template` function will likely be removed from v5 as we'll defer to template literals instead.
