### ISSUE TITLE
/fp is absent in NPM package 4.17.16

### ISSUE THREAD

**Issue by gabrielmeridadomain** [lodash/lodash#4843]
Hi, I just upgraded from `4.17.5` to `4.17.16` and the `fp` directory is absent in the package (as seen here https://www.npmjs.com/package/lodash). Is this intended?

**Comment by johnhunter** [comment]
Same here.

**Comment by drjayvee** [comment]
`runInContext` is missing as wel.

The [npm page for this release](https://www.npmjs.com/package/lodash/v/4.17.16) also doesn't look right.

**Comment by adifaidz** [comment]
4.17.17 is out, its working now

**Comment by MikeTaylor** [comment]
This is _not_ fixed in v4.17.17 — see #4848

**Comment by mathiasbynens** [comment]
Closing in favor of #4848.
