### ISSUE TITLE
 [4.17.16] Cannot find module 'lodash/fp' from 'fp.js'

### ISSUE THREAD

**Issue by sharan-salian** [lodash/lodash#4846]
In one of the projects we are facing the issue latest @mathiasbynens 

Force the usage of lodash v4.17.15 solves the problem, so it seems to be a problem with v4.17.16

```js
const { isPlainObject, mapKeys, mapValues } = require('lodash/fp');

const mapKeysDeep = cb => obj =>
  Array.isArray(obj)
    ? obj.map(mapKeysDeep(cb))
    : isPlainObject(obj)
      ? mapValues(mapKeysDeep(cb))(mapKeys(cb)(obj))
      : obj;

module.exports = mapKeysDeep;
```

**Comment by mxschmitt** [comment]
Duplicate of https://github.com/lodash/lodash/issues/4843

**Comment by stefcameron** [comment]
This is a problem with 4.17.17 also.

**Comment by mathiasbynens** [comment]
Please give `lodash@4.17.18` a try. Details here: https://github.com/lodash/lodash/issues/4837#issuecomment-655609600
