### ISSUE TITLE
[4.17.17] lodash/fp still missing

### ISSUE THREAD

**Issue by gemwuu** [lodash/lodash#4848]
Currently, I update `lodash` from v4.17.16 to v4.17.17,  `lodash/fp` is still missing.
![image](https://user-images.githubusercontent.com/4635838/86923066-1f0a2080-c160-11ea-9862-fa323a1ca045.png)

**Comment by CeEv** [comment]
We have the same issue. (v4.17.13 -> v4.17.17)

**Comment by GrzegorzKazana** [comment]
It seems that `lodash/fp/index.js` is missing 🤔

**Comment by dcefram** [comment]
It seems like the lodash team published the "wrong" branch/directory. It seems like `master` was published rather than `4.17.17` branch.

**Comment by MikeTaylor** [comment]
(See #4846 for context)

**Comment by dcefram** [comment]
Yeah, package.json shows the correct version. It's just the files in it that isn't what I'm expecting. Aside from the missing `fp` folder, `core` is also missing.

**Comment by TrySound** [comment]
By the way, you can try `mjml@4.7.0-beta.1` as fast fix. It does not require from `lodash/fp/index.js` anymore.

**Comment by chulanovskyi-bs** [comment]
temp solution, while we all waiting for the `hotfix` - https://github.com/stoplightio/prism/issues/1282#issuecomment-655572843

**Comment by mathiasbynens** [comment]
> It seems like the lodash team published the "wrong" branch/directory. It seems like `master` was published rather than `4.17.17` branch.

See https://github.com/lodash/lodash/issues/4837#issuecomment-655479601 for how this was published. It's not `master`.

> It seems that `lodash/fp/index.js` is missing 🤔

It this really "missing"? v4.17.15 doesn't have this file either. (The `fp` folder was copied from the v4.17.15 release.)

**Comment by TrySound** [comment]
@mathiasbynens https://unpkg.com/browse/lodash@4.17.15/fp.js

**Comment by gemwuu** [comment]
> @mathiasbynens https://unpkg.com/browse/lodash@4.17.15/fp.js

It seems like `4.17.16` and `4.17.17` doesn't have the fp.js file @mathiasbynens

**Comment by stefcameron** [comment]
This is breaking our private packages as well (which have third-party dependencies on `lodash/fp` which can no longer be loaded).

**Comment by TrySound** [comment]
Doesn't lockfile help you?

**Comment by stefcameron** [comment]
> Doesn't lockfile help you?

Sure. I only noticed because Dependabot opened a PR to upgrade our deps from 4.17.15 -> 4.17.17 and our builds broke. So we're not blocked on this because we can lock it to 4.17.15 until the issue is fixed.

**Comment by gstvds** [comment]
> This is breaking our private packages as well (which have third-party dependencies on `lodash/fp` which can no longer be loaded).

Is breaking our private packages too. We also use third-party dependencies, but on `lodash/core`. And it broke in production. We had to reverse and remove our dependencies

**Comment by HHK1** [comment]
>This is breaking our private packages as well (which have third-party dependencies on lodash/fp which can no longer be loaded).

Having the same issue, tried to fix it by specifying the resolutions:

```
"resolutions": {
    "lodash": "4.17.15"
  },
```

but to no avail. I'm currently unable to rebuild our dependencies.

**Comment by cncolder** [comment]
JavaScript quit [FP](https://en.wikipedia.org/wiki/FP_(programming_language)) language today! 😢

**Comment by mathiasbynens** [comment]
> > @mathiasbynens https://unpkg.com/browse/lodash@4.17.15/fp.js
> 
> It seems like `4.17.16` and `4.17.17` doesn't have the `fp.js` and `lodash.min.js` file @mathiasbynens

Awesome, thanks for the pointer! I'll try to publish an amended package asap.

**Comment by mathiasbynens** [comment]
Please give `lodash@4.17.18` a try. Details here: https://github.com/lodash/lodash/issues/4837#issuecomment-655609600

**Comment by gemwuu** [comment]
> Please give `lodash@4.17.18` a try. Details here: [#4837 (comment)](https://github.com/lodash/lodash/issues/4837#issuecomment-655609600)

works for me, much thanks. 😊
