### ISSUE TITLE
[4.17.18] Cannot find module lodash/core

### ISSUE THREAD

**Issue by gstvds** [lodash/lodash#4849]
I saw that something went wrong with the previous version, but the current one is still missing `lodash/core`.
Can't build a new version of my project in production because of that :/

PS: I use a third-part lib that uses lodash@4.17.14 as dependency, and for some reason it is installing the latest so I don't really know what to do.

![image](https://user-images.githubusercontent.com/53450202/86945134-0decef80-c11f-11ea-8e77-a73f3c12d3ec.png)

**Comment by markliu1024** [comment]
Getting the same error.

**Comment by mathiasbynens** [comment]
Thanks! Try v4.17.19: https://github.com/lodash/lodash/issues/4837#issuecomment-655634720

**Comment by AugustoPinheiro** [comment]
thanks
