### ISSUE TITLE
[4.17.18] v4.17.18 missing 3 files in comparison with v4.17.15

### ISSUE THREAD

**Issue by gemwuu** [lodash/lodash#4850]
Since `4.17.18` has published, and fixed the `lodash/fp` not found [issue](https://github.com/lodash/lodash/issues/4848). 

This latest version still missing 3 files in comparison with `4.17.15`, which are `LICENSE`, `core.js` and `core.min.js`. Check out the image below.

![image](https://user-images.githubusercontent.com/4635838/86947008-ca759e00-c17d-11ea-8ad7-1549c84beef6.png)

I think it's necessary to publish a new version, say `4.17.19`, to avoid  feature regression, like issue [4849](https://github.com/lodash/lodash/issues/4849).

And, I think we shall figure out a way to automatically publish this package.

**Comment by wheresrhys** [comment]
I'm getting this error too

```
Error: Cannot find module 'lodash/fp'
```

which I think means the `./fp/index.js` file is probably missing

**Comment by gemwuu** [comment]
> I'm getting this error too
> 
> ```
> Error: Cannot find module 'lodash/fp'
> ```
> 
> which I think means the `./fp/index.js` file is probably missing

Make sure you have updated `lodash` to `4.17.18`.

**Comment by mathiasbynens** [comment]
Thanks! Try v4.17.19: https://github.com/lodash/lodash/issues/4837#issuecomment-655634720
