### ISSUE TITLE
Feature: _.duplicates(array) or _.uniques(array)

### ISSUE THREAD

**Issue by lonewarrior556** [lodash/lodash#4852]
list duplicate values in an array, The order of result values is determined by the order they occur in the array.

```js
var arr = [2, 1, 2, 3, 4, 6, 2, 4];
_.duplicates(arr);
// => [2, 4]

_.uniques(arr);
// [1, 3, 6]

// in contract with current _.uniq
_.uniq(arr)
// => [2, 1, 3, 4, 6]
```

Either can be used to find the other
```js
// find uniques using duplicates
_.difference(arr, duplicates(arr));
// => [1, 3, 6]

/// find duplicates using uniques 
_.difference(arr, uniques(arr));
// => [2, 4]
```

This can be achieved with `countBy` and `pickBy`.. it's just akward..

```js
var arr = [2, 1, 2, 3, 4, 6, 2, 4];
_.countBy(arr);
// => {2: 3, 4, 2, 1: 1, 3: 1, 6: 1}

const duplicates = Object.key(_.pickBy(_.countValues(arr), val => val > 1)).map(Number);
```

Its often one is interested in only the duplicates and I can't seem to figure out a good way to do this using existing lodash methods...  
`_.difference` by itself is no good because it's a set operation,

**Comment by mcraepv** [comment]
Hi, is it alright if I work on this?

**Comment by VigneshMurugan** [comment]
https://github.com/lodash/lodash/pull/4871

**Comment by lonewarrior556** [comment]
So this is Crazy.. 
https://lodash.com/docs/4.17.15#xor can be used for this...
```
_.xor([2], [1], [2], [3], [4], [6], [2], [4]];
// => [1, 3, 6]
```

so ths function would work
```js
const uniques = (arr) => _.xor(...arr.map(a => [a]))
const duplicates = (arr) => _.xor(arr, uniques(arr));

const arr = [2, 1, 2, 3, 4, 6, 2, 4];

uniques (arr);
// => [1, 3, 6];

duplicates(arr);
// => [2, 4];
```

**Comment by bnjmnt4n** [comment]
Given that this can be easily composed with `_.xor`, I'm going to close this for now. That said, we'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
