### ISSUE TITLE
_.curry behavior does not appear correct

### ISSUE THREAD

**Issue by joshuakfarrar** [lodash/lodash#4853]
```
> _.concat(['a'], ['b'])
[ 'a', 'b' ]
> Array.prototype.concat(['a'], ['b'])
[ 'a', 'b' ]
> _.curry(_.concat)(['a'])
[ 'a' ]
> _.curry(_.concat)(['a'])(['b'])
TypeError: _.curry(...)(...) is not a function
> _.curry(Array.prototype.concat)(['a'])(['b'])
TypeError: _.curry(...)(...) is not a function
> _.curry((a, b) => _.concat(a, b))(['a'])(['b'])
[ 'a', 'b' ]
```

expected:

```
> const curry = f => a => b => f.call(a, b)
undefined
> curry(Array.prototype.concat)(['a'])(['b'])
[ 'a', 'b' ]
```

**Comment by papb** [comment]
Question: why do you expect `f.call(a, b)` instead of `f(a, b)`?

**Comment by joshuakfarrar** [comment]
In theory, it shouldn't matter how f is called.

**Comment by bnjmnt4n** [comment]
Since `Array.prototype.concat.length` is `1`, `_.curry` only curries up to the first argument, so calling it a second time would be invalid since you would be invoking the given array as a function.

**Comment by joshuakfarrar** [comment]
I'd simply note here that specifying an arity of 2 still breaks _.curry using Array.prototype.concat because `this` is bound to lodash, hence the return value of `_.curry(Array.prototype.concat)(['a'])(['b'])` is `[_, 'a', 'b']`.
