### ISSUE TITLE
sampleSize slow for large inputs

### ISSUE THREAD

**Issue by laggingreflex** [lodash/lodash#4854]
[lodash.sampleSize][1] ~~basically randomizes the **entire** array and then slices up to the required size.~~

Edit: ~~I misread the code. It seems it only randomizes upto the given `n`. Still, my way seems a lot faster still...~~

Edit²: v5 is the version that randomizes only upto the given `n`, thus fixes the issue. Current version which is on npm - v4.x randomizes entire array and has the issue. So I guess this has technically been resolved. Just gotta wait for or use v5

Edit³: skip to https://github.com/lodash/lodash/issues/4854#issuecomment-656935395

Here's my implementation:

```js
function sampleSize(array, n = 1) {
  const length = array.length;
  n = Math.max(0, Math.min(n, length));
  const sample = [];
  const used = {};
  while (n--) {
    let i;
    do { i = Math.floor(Math.random() * length) } while (i in used);
    used[i] = true;
    sample.push(array[i]);
  }
  return sample;
}
```

Mine's obviously a [lot faster][2]

```
lodash x 420 ops/sec ±5.96% (49 runs sampled)
custom x 84,660 ops/sec ±9.08% (46 runs sampled)
```

Does my implementation satisfy the main requirement just as well or am I overlooking something?

> Gets n random elements at unique keys from collection up to the size of collection.

[1]: https://github.com/lodash/lodash/blob/master/sampleSize.js
[2]: https://jsbin.com/xawubux/1/edit?html,output

**Comment by nortti** [comment]
Unique elements != elements at unique keys. 

`sampleSize([1, 1], 2)` should return `[1, 1]`, your code runs indefinitely.

**Comment by laggingreflex** [comment]
@nortti That issue could be fixed easily by storing keys. But it seems the issue of randomizing **entire** array was still present, at least till v5. v5 is the version that randomizes only upto the given `n`, thus fixes the issue. Current version which is on npm - v4.x randomizes entire array and has the issue. So I guess this has technically been resolved. Just gotta wait for or use v5

**Comment by laggingreflex** [comment]
It seems v4.16.0 was the version that had issues:

version | result
---|---
v4.14.0| [80,837 ops/sec ±9.69% ](https://jsbin.com/gepivin/edit?html,output)
v4.15.0| [75,067 ops/sec ±10.82%](https://jsbin.com/talafes/edit?html,output)
v4.16.0| [**30,123** ops/sec ±11.04%](https://jsbin.com/yujujiq/edit?html,output)
v4.14.0| [71,182 ops/sec ±6.07% ](https://jsbin.com/tatigil/edit?html,output)
v4.14.0| [62,809 ops/sec ±13.58%](https://jsbin.com/solobut/edit?html,output)

**Comment by laggingreflex** [comment]
Actually, reopening as I'm having doubts again after rerunning benchmarks for larger inputs. And all of the versions seem to be performing poorly

Above benchmarks were for array of size 1,000. Below are for array size 1,00,000:

version | result | link
---|---|---
v4.14.0  | lodash x 499 ops/sec ±2.42% | https://jsbin.com/gomakon/edit?html,output
v4.15.0  | lodash x 506 ops/sec ±4.06% | https://jsbin.com/weyihuw/edit?html,output
v4.16.0  | lodash x 282 ops/sec ±5.00% | https://jsbin.com/rinasul/edit?html,output
v4.17.0  | lodash x 525 ops/sec ±3.97% | https://jsbin.com/kenupuz/edit?html,output
v4.17.19 | lodash x 495 ops/sec ±1.38% | https://jsbin.com/xawubux/edit?html,output

Compared to result of my custom function: 83,857 ops/sec lodash seems to be **~150x slower!**

```js
function sampleSize(array, n = 1) {
  const length = array.length;
  n = Math.max(0, Math.min(n, length));
  const sample = [];
  const used = {};
  while (n--) {
    let i;
    do { i = Math.floor(Math.random() * length) } while (i in used);
    used[i] = true;
    sample.push(array[i]);
  }
  return sample;
}
```

**Comment by nortti** [comment]
Your benchmark only runs for n = 20. A proper benchmark would run for several or all values of n, and reveal that your implementation is slower most of the time. Even just experimenting with the sample size in the last jsbin you posted reveals that _.sampleSize is faster around 97.5% of the time (when n>2500).

**Comment by laggingreflex** [comment]
Hmm yeah you're right. It seems my method is only faster in very specific circumstances - when the size is large (10,000+) and n is small (<.25% of the size).
