### ISSUE TITLE
Add error message for _.uniq if not called with array

### ISSUE THREAD

**Issue by sktguha** [lodash/lodash#4856]
If _.uniq is not called with an array but by a number of arguments like _.uniq(1,2,3,1), then I propose that error should be shown 
like , "don't call _.uniq like _.uniq(1,2,3,1) but call it like _.uniq([1,2,3,1])"

if it is greenlighted, then I would like to pick this up as a task

**Comment by Chandler-Davidson** [comment]
I agree with throwing a type error. @sktguha, I'm not a maintainer, but I would go ahead and make the change and open a PR.
