### ISSUE TITLE
Bug: `_.difference` return incorrect result

### ISSUE THREAD

**Issue by Oliferchik** [lodash/lodash#4859]
const x = [
   "B1b9jS0H1v", "Outgoing transfer", "2020-07-10", "2020-07-10", "TEST1", "TEST2", 
   "", "", "DO45", "FTC", "MT05", "FTC", "", "10", "0", "", "10"];
const y = [
  "B1b9jS0H1v", "Outgoing transfer", "2020-07-10", "2020-07-10", "TEST1","TEST2",
  "EUR1", "EUR2", "DO45", "FTC", "MT05", "FTC", "", "10", "0", "", "NaN"
];

console.log(_.difference(x, y));

Should be - `["EUR1", "EUR2", "NaN"]`

But it is `[]`

**Comment by nicholas-l** [comment]
It looks like difference only inspects the first argument (https://lodash.com/docs/4.17.15#difference). I think what you are looking for it is `_.xor` (See https://lodash.com/docs/4.17.15#xor) or flip the order of arguments.
