### ISSUE TITLE
Feature request: a function to check if arrays intersects

### ISSUE THREAD

**Issue by jazzzz** [lodash/lodash#4860]
There is `intersection`, but nothing to check if arrays intersects.

A naive implementation would be `!_.isEmpty(_.intersection(...arrays))` but it can be inefficient for large arrays.

In spatial databases like PostGIS, beside [the intersection function](https://postgis.net/docs/manual-3.0/ST_Intersection.html), there is [an intersects function](https://postgis.net/docs/manual-3.0/ST_Intersects.html).

**Comment by Chandler-Davidson** [comment]
I see the value of this, its essentially a 2d version of Array.includes.

**Comment by falsyvalues** [comment]
Hi @jazzzz!

As usual we will keep an eye on the [popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
