### ISSUE TITLE
A typo in documentation

### ISSUE THREAD

**Issue by mrcat323** [lodash/lodash#4861]
Hey guys, I found lodash useful for my projects. But recently I found a typo in documentation, in **reduce** page https://lodash.com/docs/4.17.15#reduce

![image](https://user-images.githubusercontent.com/23054662/87521123-5c5d3980-c69d-11ea-9a94-7f661d054808.png)
It must be **through** instead of **thru**

**Comment by bnjmnt4n** [comment]
I believe the wording was intentional and meant to serve as a reference to [`_.thru`](https://lodash.com/docs/4.17.15#thru). I remember a little discussion about this, but can't seem to find the issue/PR. Maybe we can think about alternative wording strategies?

**Comment by mrcat323** [comment]
okay, but in **reduce** page, block, I thought there was a typo, *through* exists, but not `_.thru_ I didn't know about that

**Comment by si88hant** [comment]
Is this issue still open for contribution? I am new to open source and would love to rectify it.

**Comment by mjoyce91** [comment]
I have a PR that should resolve this - https://github.com/lodash/lodash.com/pull/276
