### ISSUE TITLE
Outdated changelog for recent releases

### ISSUE THREAD

**Issue by henryglendening-wwt** [lodash/lodash#4863]
The changelog does not indicate what changes have been incorporated into releases 4.17.16 and 4.17.19. See https://github.com/lodash/lodash/wiki/Changelog

**Comment by NuckChorris** [comment]
I can't help but notice there's also no newer versions of lodash-es published since 4.17.15 — seems like something changed after then?

**Comment by MasterOdin** [comment]
I've updated the changelog based on the information available. I skipped 4.17.16 since based on discussions in #4837, it would seem that it was missing some stuff to actually make it fully usable (same with also .17 and .18).

**Comment by bxt** [comment]
For 4.17.20 there is no entry in the Changelog yet. From [the diff](https://github.com/lodash/lodash/compare/4.17.19...4.17.20) it seems there might have been no changes for consumers of the package, but it seems strange and could also create the impression that the new version is somehow not "officially approved" by the lodash maintainers.

**Comment by bnjmnt4n** [comment]
Thanks for the feedback. I've updated the changelog to indicate the changes in the 4.17.20. The thing about using a compiler like lodash-cli to build modularized files means that the diffs don't reflect all the actual changes in the code. In v5, we'll be shifting away from this compiler based approach so diffs will be clearer.
