### ISSUE TITLE
Expand _.pullAt  to take negative index 

### ISSUE THREAD

**Issue by lonewarrior556** [lodash/lodash#4865]
Make `_.pullAt` consistent with `_.nth`
```js
var array = ['a', 'b', 'c', 'd'];
 
_.nth(array, 1);
// => 'b'
 
_.nth(array, -2);
// => 'c';

/* Current Behavior of pullAt*/
_.pullAt(array,[1,-2]) 
// => ["b", undefined]

/* Should be */
_.pullAt(array,[1,-2]) 
// => ["b", "c"]
```

This would make finding the Bounds of an array simpler
```js
_.pullAt(_.sortBy([9,1,8,2,6,4,9,11,1,0,50,1,2,3,4]), 0, -1)
// => [0, 50]
```

**Comment by bnjmnt4n** [comment]
`_.at` is an Object method, meaning it is designed to work on objects primarily. Adding this special handling of negative numbers will does not seem like a good idea for `_.at`, and for consistency, we might also not want to change `_.pullAt`.

**Comment by lonewarrior556** [comment]
@bnjmnt4n updated request to only modify Array: `_.pullAt`

`_.pullAt` is already inconsistent with `_.at` as it mutates the passed array,
