### ISSUE TITLE
lodash.core.js : VERSION has the wrong value

### ISSUE THREAD

**Issue by LarryBattleWork** [lodash/lodash#4866]
The versions for lodash.core.js are wrong for 4.17.16+. I didn't check others.

## Example: 

- https://raw.githubusercontent.com/lodash/lodash/4.17.16/dist/lodash.core.js 
`var VERSION = '4.17.15';`
- https://raw.githubusercontent.com/lodash/lodash/4.17.17/dist/lodash.core.js
`var VERSION = '4.17.16';`
- https://raw.githubusercontent.com/lodash/lodash/4.17.18/dist/lodash.core.js
`var VERSION = '4.17.16';`
- https://raw.githubusercontent.com/lodash/lodash/4.17.19/dist/lodash.core.js
`var VERSION = '4.17.16';`

## Related Issue: 
https://github.com/lodash/lodash/issues/4837

**Comment by bnjmnt4n** [comment]
Fixed in v4.17.20.
