### ISSUE TITLE
Add an esm bundle to lodash per method packages

### ISSUE THREAD

**Issue by remorses** [lodash/lodash#4876]
Some bundlers like `vito` don't support cjs anymore, losash should bundle the esm bundle in the per method packages

In #3871 @jdalton said it was to minimize the npm package size so we can add the "module" field to only the per method packages to overcome this

**Comment by bnjmnt4n** [comment]
The per-method lodash packages will be [deprecated in v5](https://github.com/lodash/lodash/issues/3838#issuecomment-398592530). We'll definitely be sure to release an ESM module in some form (we're still working out the details, see #4800), but you would likely be able to import individual functions for tree-shaking.
