### ISSUE TITLE
Angular 10 Warning

### ISSUE THREAD

**Issue by Christian-Seiler** [lodash/lodash#4877]
Angular 10 now gives a warning to users who are using this library due to it being a CommonJS package.

```
WARNING in my.component.ts depends on lodash/fp. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by txywishes** [comment]
> 
> 
> Angular 10 now gives a warning to users who are using this library due to it being a CommonJS package.
> 
> ```
> WARNING in my.component.ts depends on lodash/fp. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
> ```

Maybe you should use the [lodash-es](https://www.npmjs.com/package/lodash-es) package instead. But note that the latest Prototype Pollution fix (as mentioned here: [https://github.com/lodash/lodash/issues/4837]) has not been pushed to lodash-es yet.

**Comment by Christian-Seiler** [comment]
Sure, what is the difference between 'standard' lodash and lodash/fp?

**Comment by txywishes** [comment]
> 
> 
> Sure, what is the difference between 'standard' lodash and lodash/fp?

Sorry, I'm not familiar with lodash/fp. The lodash wiki has a page on it: https://github.com/lodash/lodash/wiki/FP-Guide 
The following 2 pages describe more of the Functional Programming aspects of lodash/fp:
- https://blog.codeminer42.com/functional-programming-with-lodash-fp-8fe0619b3024/
- https://codingwithjs.rocks/blog/lodash-fp-usage-retrospective

**Comment by bnjmnt4n** [comment]
There's nothing much we can do here regarding this. You can switch to `lodash-es` to avoid the warning, but that does mean you have to give up on lodash/fp, which isn't available for lodash-es. In the future we hope to have a ESM-based lodash and lodash fp.
