### ISSUE TITLE
sortedIndexBy, sortedIndexOf return incorrect results for mixed type arrays

### ISSUE THREAD

**Issue by dianabarsan** [lodash/lodash#4885]
Given this array:
```
var array = [1, 2, 3, 4, 5, 'a', 'b', 'c'];
```

calling `sortedIndexOf` searching for `c` will return -1 instead of 7. 

```
_.sortedIndexOf(array, 'c');
> -1
````

Similarly:
```
_.sortedIndexBy([1, 2, 3, 4, 'a', 'b'], 'c');
> 0
```

This is an unfortunate side-effect of string to number comparison that happens in the `baseSortedIndexBy` function:
```
setLow = retHighest ? (computed <= value) : (computed < value)
```
https://github.com/lodash/lodash/blob/master/.internal/baseSortedIndexBy.js#L54

**Comment by bnjmnt4n** [comment]
This is working as expected. Such arrays of mixed types should be considered invalid input, as we assume that the array has already been sorted, and we can't determine how to sort values of different types. You can use [sortedIndexBy](https://lodash.com/docs/4.17.15#sortedIndexBy) to do some additional customization.
