### ISSUE TITLE
Add _.oneArg to lodash

### ISSUE THREAD

**Issue by sktguha** [lodash/lodash#4892]
I suggest adding a new function called oneArg to lodash. It wraps a function and allows it to be called with one argument only and ignores rest of the arguments.
Implementation: 
 `const oneArg = fn => arg => fn(arg);`

usage:
 Before oneArg:
 ` ['34','11','19','199','201'].map(parseInt);
  // returns [34, NaN, 1, 1, 33]`

 After oneArg:
 `const safeParseInt = oneArg(parseInt);
  ['34','11','19','199','201'].map(safeParseInt)
  // returns [34, 11, 19, 199, 201]`

**Comment by Alan-Liang** [comment]
See `_.unary()`.

**Comment by sktguha** [comment]
Ok . Closing it since it is already available

**Comment by sktguha** [comment]
@Alan-Liang or anyone can u point me to the source code of unary ? I am unable to find it in lodash source code

**Comment by Alan-Liang** [comment]
https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L10930

PS: You can find the source code of any function in the docs.

于 2020年8月12日 GMT+08:00 下午1:03:55, Saikat Guha <notifications@github.com> 写到:
>@Alan-Liang or anyone can u point me to the source code of unary ? I am
>unable to find it in lodash source code
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/lodash/lodash/issues/4892#issuecomment-672574827

-- 
使用 Open Mail 发送自我的Android设备。
