### ISSUE TITLE
_.IsEmpty returns true for a number

### ISSUE THREAD

**Issue by pranav-singhal** [lodash/lodash#4895]
if you pass a number to the argument of _.isEmpty , it returns `true`

```js
console.log(_.isEmpty(666)) // == > true

```

**Comment by dopecodez** [comment]
Looking through the code, I think this is the behavior expected. 
` * Checks if `value` is an empty object, collection, map, or set.
 *
 * Objects are considered empty if they have no own enumerable string keyed
 * properties.
 *
 * Array-like values such as `arguments` objects, arrays, buffers, strings, or
 * jQuery-like collections are considered empty if they have a `length` of `0`.
 * Similarly, maps and sets are considered empty if they have a `size` of `0`.`

This is what the code says, and numbers do not have own enumerable string keyed properties.

**Comment by yufi1213** [comment]
> if you pass a number to the argument of _.isEmpty , it returns `true`
> 
> ```js
> console.log(_.isEmpty(666)) // == > true
> ```

**Comment by falsyvalues** [comment]
Hi @pranav-singhal!

@dopecodez is right see our docs [isEmpty](https://lodash.com/docs/4.17.15#isEmpty).

**Comment by ManushovRodion** [comment]
RU: Надо бы переменовать функцию, а то сбивает с толку, на какой ни-будь  isEmpty => isEmptyObjectValue
EN: It would be necessary to change the function, otherwise it is confusing, for whatever isEmpty => isEmptyObjectValue
