### ISSUE TITLE
In master ,I don't found many files like find.js.

### ISSUE THREAD

**Issue by MagnetLin** [lodash/lodash#4896]
In master ,I don't found many file like `find.js`. but the specify version have `find` function, Where does it come from in specify?

@jdalton Interesting, I also don't see `findIndex.js` in current master, both when browsing on github, or after checkout. At the same time, the current `find.js` imports from `./findIndex.js`. Where does it come from? Can you please link the source?

_Originally posted by @iki in https://github.com/lodash/lodash/issues/3179#issuecomment-357190402_

**Comment by LarryBattle** [comment]
The `master` branch isn't what's published. There's a magical build script somewhere that's builds the published versions. 
Maybe it's [lodash-cli](https://github.com/lodash-archive/lodash-cli) 🤷

You want to checkout the release tag and examine what's inside the `npm-package` directory. 

Here are the files you're looking for the the latest release of lodash `4.17.19`

- https://github.com/lodash/lodash/blob/4.17.19/npm-package/findIndex.js
- https://github.com/lodash/lodash/blob/4.17.19/npm-package/find.js

Extra
- [Viewing Branches in Github](https://docs.github.com/en/github/administering-a-repository/viewing-branches-in-your-repository)

**Comment by bnjmnt4n** [comment]
The master branch is our wip v5, which has not been released. The links provided by @LarryBattle are indeed the source released to npm, which was generated by lodash-cli from the base monolithic lodash file (https://github.com/lodash/lodash/blob/4.17.19/lodash.js).
