### ISSUE TITLE
Loadash files not loaded after installing the package

### ISSUE THREAD

**Issue by azzazkhan** [lodash/lodash#4902]
When I installed loadash from `npm install loadash` it doesn't load necessary files from the **loadash/loadash** repository instead, it only loads the **package.json** and the **readme.md** file only.
These are the content of the `loadash` folder present in my `node_modules` folder of my current project.
![Annotation 2020-08-13 112939](https://user-images.githubusercontent.com/25636920/90101568-6041b180-dd58-11ea-88f1-494656a076ca.png)

Note that I've checked the directory where globally installed npm packages are placed but there was no sign of loadash.

**Comment by bnjmnt4n** [comment]
Hi, you're loading the wrong package. Try `npm i lodash` (not `loadash`).

**Comment by azzazkhan** [comment]
Thanks
