### ISSUE TITLE
proposal for getOrSet

### ISSUE THREAD

**Issue by rejetto** [lodash/lodash#4915]
over the years in my projects I've often needed this function

```
function getOrSet(obj,path,def){
    let ret = get(obj,path)
    if (ret!==undefined)
        return ret
    set(obj,path,def)
    return def
}
```

It is good when you want the default value to also persist in the object.
I was wondering if I'm missing something or, if popular, it would be good to have in lodash.

A similar repo exists
https://github.com/AndersDJohnson/lodash-get-or-set/blob/master/src/index.js
but I don't like it treating null equally to undefined.

**Comment by falsyvalues** [comment]
Hi @rejetto!

As usual we will keep an eye on the [popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
