### ISSUE TITLE
trimStart issue/question

### ISSUE THREAD

**Issue by DemjanUA** [lodash/lodash#4916]
Hello

Today I was working on my task and tried to use trimStart. I faced a problem that I can't get: on the picture below you can see the use case of trimStart in which this function trims for one more character than I expect.

![image](https://user-images.githubusercontent.com/16669415/92115274-d63ab500-edfa-11ea-8535-68ba14116a4d.png)

'BundleTemplates/acbcb701-c2d1-418c-80f4-ca70fb5e68e6'

But it doesn't happen in this case:
![image](https://user-images.githubusercontent.com/16669415/92115636-6842bd80-edfb-11ea-9852-f69eafd89eb4.png)

'BundleTemplates/bcbcb701-c2d1-418c-80f4-ca70fb5e68e6'

**Comment by papb** [comment]
What you did is trim any of the `'B', 'u', 'n', 'd', 'l', 'e', 'T', 'e', 'm', 'p', 'l', 'a', 't', 'e', 's', '/'` chars from the beginning of your string.
