### ISSUE TITLE
Update words() description in the documentation to include the default rules for how it splits phrases

### ISSUE THREAD

**Issue by tehdeadone** [lodash/lodash#4917]
It would be useful in the documentation for lodash's words that it would explain how it splits words.

I only discovered recently when a bug was raised on our code that it couldn't find a "hashtag" in a string and it was because _.words() splits on a hash symbol and also removes it. And that it splits word and number combinations.

_.words('this is a #lodashiscool2020') // => ['this', 'is', 'a', 'lodashiscool', '2020']

Additionally, it's not clear in the docs that if you put your own pattern, it'll still split word and number combinations as well as use the pattern.

**Comment by Jl201835** [comment]
Hello, I am new to open source. Looks like this is a good first issue. I am wondering if I can work on this one? Thanks!
