### ISSUE TITLE
Intersects return boolean

### ISSUE THREAD

**Issue by iwhoppock** [lodash/lodash#4918]
Would love this to be simplified to `_.intersects(a1, a2) -> Boolean`:
```
function intersects(a1, a2) {
  return !_.isEmpty(_.intersection(a1, a2));
}
```

**Comment by bnjmnt4n** [comment]
Given that this request is simply just checking the length of the result of `_.intersection`, it is simple enough to remain outside of lodash.

**Comment by szimek** [comment]
It would be useful if there was such function that returns early, without calculating the whole intersection of 2 arrays.

So something like:
```js
const intersects = a.some(x => b.includes(x));
```
rather than
```js
const intersection = a.filter(x => b.includes(x));
```
