### ISSUE TITLE
uniqueId method

### ISSUE THREAD

**Issue by rumkin** [lodash/lodash#492]
Util `uniqueId` has not generate really unique id. It's generate `lodash-instance-uniqueId` or `lodash-session-uniqueId`. But what's about pseudo-uid based on big numbers like 128 random hash?

**Comment by FREEZX** [comment]
The uniqueId function perhaps needs a way to set it's "seed". In an application i'm working on the user can save work to JSON, refresh, and load the data again. From then on, if i have used _.uniqueId in a previous run, newly generated values will overlap, creating issues as new ids are not really unique now.

**Comment by awe-sim** [comment]
@FREEZX .. I've stumbled across the same problem.. As a result, I'm having a go at creating a singleton class that I persist in JSON as well.. =( sucks!

**Comment by jdalton** [comment]
Our `_.uniqueId` is like 2 lines of JS. You'll get very little sympathy from me that our generic utility method doesn't fit :100: to your use case. Suck it up.

**Comment by rumkin** [comment]
It's name contains `unique` . This is confusing. Actually integers not unique and such name is irrelevant. So it could be renamed into simple `id`.

**Comment by jdalton** [comment]
Every time you call the method it returns a uniq id to itself.
