### ISSUE TITLE
Update lodash-es to 4.17.20

### ISSUE THREAD

**Issue by GintV** [lodash/lodash#4922]
There are a lot of security fixes in between lodash 4.17.15 and 4.17.20, and we are using some packages that use lodash-es ^4.17.15, so it would be nice that we could update lodash-es and get rid of security holes.

**Comment by johnmccabe** [comment]
This was flagged in #4879 and #4837 as well. @bnjmnt4n have you had any luck with the release process for the -es package.

**Comment by bnjmnt4n** [comment]
Marking as duplicate of #4879.

**Comment by scinos** [comment]
What happen to issues #4879 or #4837 ?
