### ISSUE TITLE
BigInt throws error in numerical methods

### ISSUE THREAD

**Issue by FarSeeing** [lodash/lodash#4925]
`BigInt` is not supported and throws error in these methods

- `gt`
- `gte`
- `lt`
- `lte`
- `toFinite`
- `toInteger`
- `toLength`
- `toNumber`
- `toSafeInteger`
- and most of Math methods

Although it is expected that some methods should not work when you mix `BigInt` and `Number` values at least they should not throw errors.

**Comment by Gaurav2048** [comment]
Unable to produce the error. Can you please give an example of what's going wrong.

**Comment by FarSeeing** [comment]
Basically all the listed functions throw error `TypeError: Cannot convert a BigInt value to a number` when you call them with `BigInt` values:
* `_.gt(1n, 2n)`
* `_.toNumber(1n)`
* etc

That happens because unary plus is used to convert value to (supposed) `Number` instance while you cannot do that for `BigInt` values, you need to explicitly call `Number(x)`.
Example of incorrect conversion - https://github.com/lodash/lodash/blob/master/toNumber.js#L56
