### ISSUE TITLE
sortBy doesn't perform a stable sort

### ISSUE THREAD

**Issue by goldylucks** [lodash/lodash#4926]
After reading the docs:
> This method performs a stable sort, that is, it preserves the original sort order of equal elements.

I implemented two sorts one after the other:

```js
  chats = sortBy(chats, c => -last(c.messages).createdAt)
  chats = sortBy(chats, c => !c.isPinned)
```

Each one of them works on it's own, but mixing them will cause the second one to mess the first one.

Am I missing something here?

Thanks for the great project btw :rocket:

**Comment by FelixRilling** [comment]
Hi!
Could you explain further what you mean by "mixing them" and "mess the first one"?

**Comment by goldylucks** [comment]
I mean if I use both of them in the order posted above, I expect chats to be sorted by `isPinned` and then by `createdAt`, but instead it's only sorted by the last sort, `isPinned`

Is that clearer?

Thanks!

**Comment by papb** [comment]
@goldylucks Can you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by goldylucks** [comment]
I made a sandbox but it works fine, so the problem is probably on my end, so I'm closing this :)
