### ISSUE TITLE
I'd like to move my deno-lodash repo to your org

### ISSUE THREAD

**Issue by michael-spengler** [lodash/lodash#4929]
Things are IMO successfully up and running 
here: https://deno.land/x/deno_lodash
and here: https://nest.land/package/deno-lodash

repo: https://github.com/michael-spengler/deno-lodash

**Comment by bnjmnt4n** [comment]
Hey @michael-spengler! Thanks for the effort setting that up. Given that I don't have much experience with Deno, I don't think shifting your repo to the lodash org is a good idea for now. If the ecosystem further matures, that would be something to re-consider (in the future).
