### ISSUE TITLE
Angular9: Cannot assign to read only property 'includes' of function 'function lodash(value)

### ISSUE THREAD

**Issue by kwebster16** [lodash/lodash#4930]
I'm in the process of upgrading my angular project to angular 9.  And everything seemed to go pretty smoothly but when I try to load up the new build I'm getting this error message in the console (references lodash.js:16775).  I tried updating to the latest version (4.17.20), also tried using lodash-es.

imports are done using `import { cloneDeep, ... } from 'lodash;`  I understand that you can import from from individual modules, which I haven't tried yet but I'm not sure that will make a difference.

allowSyntheticDefaultImports is enabled.

Do I need to downgrade maybe?  Or could this be something else entirely causing the issue?

**Comment by papb** [comment]
What is in `lodash.js` line 16775?

**Comment by kwebster16** [comment]
![image](https://user-images.githubusercontent.com/14842470/93132710-8090c300-f6ac-11ea-8d17-55f52436a44b.png)

**Comment by papb** [comment]
Hmm... I have no idea, sorry, good luck :)

**Comment by bnjmnt4n** [comment]
Hi, could you post a minimal reproduction of this issue if you're still getting it?
