### ISSUE TITLE
Vulnerability from WhiteSource

### ISSUE THREAD

**Issue by rlerma** [lodash/lodash#4931]
All versions of lodash are vulnerable to Prototype Pollution. The function zipObjectDeep allows a malicious user to modify the prototype of Object if the property identifiers are user-supplied. Being affected by this issue requires zipping objects based on user-provided property arrays. This vulnerability may lead to Denial of Service or Code Execution.

**Comment by FelixRilling** [comment]
it seems you are referring to https://github.com/advisories/GHSA-p6mc-m468-83gw - The issue is fixed in lodash 4.17.19.

**Comment by rlerma** [comment]
> it seems you are referring to https://github.com/advisories/GHSA-p6mc-m468-83gw - The issue is fixed in lodash 4.17.19.

Thanks!
