### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by pSnehanshu** [lodash/lodash#4932]
[This package](https://www.jsdelivr.com/package/npm/lodash.get) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by falsyvalues** [comment]
Hi @pSnehanshu!

All separated packages like `lodash.get` are deprecated and won't receive any updates.
