### ISSUE TITLE
Searching nonexistant `search`  property in object returns  a function.

### ISSUE THREAD

**Issue by gauravaror** [lodash/lodash#4940]
Below is an example where lodash returns an actual `search` function of string which seems undesirable. I think ideally, we should return the property at the next level only if it was an object.

```
> const lodashGet = require('lodash.get');
> lodashGet({'on': 'work'}, 'on.search', '')
[Function: search]
```

I think expected behaviour should be to return defaultValue here.

**Comment by FelixRilling** [comment]
Agreed, while the current behavior is technically correct (find a string in 'on', return the 'search' method of the string), it seems kind of confusing and rarely useful. However I am unsure how to properly define a fix - should only 'built-in' methods be ignored? should all methods be ignored (probably not)? should this be configurable?

**Comment by ZimGil** [comment]
A possible fix to this case will be to check if the found value is coming from the `prototype` and ignoring it if it is coming from the prototype and the prototype is non-native type,
The problem with this solution is that it will brake any cases of methods coming from the native types.
I'm also unsure about the expected behavior.

```javascript
const nativeTypes = ['Object', 'String', 'Array', 'Number', 'Set', 'Function', 'Symbol', 'Boolean', .......];

class Foo {
  toString() {console.log('lodash')};
}

const foo = new Foo();

foo.toString()
// "[object Object]"

foo.__proto__.toString()
// "[object Object]"

foo.__proto__.toString === foo.toString
// true

nativeTypes.includes(foo.__proto__.constructor.name)
// false

const bar = { toString: () => console.log('lodash') };

bar.toString()
// "lodash"

bar.__proto__.toString()
// "[object Object]"

bar.__proto__.toString === bar.toString
// false
```

**Comment by bnjmnt4n** [comment]
The current behaviour is correct, and I don't believe we will ever implement any checks to see if an object is of a native type before getting. Such behaviour is going to be unsustainable in the long run, as ECMAScript might get more and more data types (modern ES included maps, sets, all the new Array types, etc.).
