### ISSUE TITLE
Truncate Could Use a More Convenient Signature

### ISSUE THREAD

**Issue by machineghost** [lodash/lodash#4946]
Truncate is not a terribly advanced/complicated function, but *at minimum*, unless you want your string truncated at exactly 30 characters, it requires this:

    truncate(aReallyLongString, { length: 100 });

That's not terrible, but it's uncharacteristically verbose for Lodash.  Consider the signature of a very similar method, `pad`:

    pad('abc', 8);

Why not allow a non-object signature of `truncate(string, length, omission, separator)`? Looking at the source, it seems it'd be trivial to add another signature to `truncate`, as it would simply require one new `else if`  clause:

    function truncate(string, options) {
      // ..
       if (isObject(options)) {
         // set variables from options

       // NEW CODE
       } else if (isInteger(options)) {

Surely `truncate` isn't likely to take any new options anytime soon, and this would enable it to be used simply/elegantly, the same way as most Lodash functions:  

    pad('abc', 8);

    truncate(aReallyLongString, 100);

I'd be happy to submit a PR if this is desired.

P.S. And unless someone is currently passing integers to `truncate` now (in place of that object argument, despite said integer doing nothing) .... which I guess is *possible*, but I can't imagine is very common ... this would have zero negative impact on anyone.

**Comment by acagastya** [comment]
@machineghost `truncate`'s second parameter is for options including but not restricted to `length`.  There are also `omission` and `separator`.

It is possible to use `separator` without using `omission`; or `omission` without `length`.  With the new signature, `truncate(string, length, omission, separator)` -- not only that would be a breaking change, one would have to supply `length` every time they want to use `omission` and both `length` and `omission` when they want to use `separator` -- that does not sound like a good design decision.

cf: https://lodash.com/docs/4.17.15#truncate

**Comment by machineghost** [comment]
>It is possible to use separator without using omission; or omission without length. With the new signature, truncate(string, length, omission, separator) -- not only that would be a breaking change,

Again, it would only "break" people currently passing an integer in the object's place ... which should be nobody since that does nothing currently.  Everyone using either of the two current signatures would not be affected in any way.

>one would have to supply length every time they want to use omission and both length and omission when they want to use separator

And right now they can't supply anything. You're literally saying "right now we can only have pie, but your proposal only lets us have pie and cake, not pie and cake and ice cream, so it's no good" ... "but pie and cake" > "just cake"!  And similarly, having more options without hurting anyone is an improvement.
