### ISSUE TITLE
Add JSHint / JSCS linting

### ISSUE THREAD

**Issue by zlatanvasovic** [lodash/lodash#495]
All the things that are specified in the `CONTRIBUTING.md` should be added to the `npm test`, so you can avoid the _bad_ code. JSHint and JSCS can help with the styleguide checking.

I can help with the JSHint / JSCS integration.

**Comment by englishextra** [comment]
The choice is simple: either jshint compliance, or lodash performance. If you start changing ```>>> 0``` to ```Math.floor``` the lib would be broken.
