### ISSUE TITLE
_.get worked abnormally with a nested path like 'a.b.c'

### ISSUE THREAD

**Issue by ChenGuanglin0924** [lodash/lodash#4954]
`lodash` version: 4.17.20
`babel-plugin-lodash` version:  3.3.4
`lodash-webpack-plugin` version:  0.11.5

```
const obj = {
  a: {
    b: 1
  },
  c: 2
}

// error
_.get(obj , 'a.b') => 'a.b'

// success
_.get(obj , ['a', 'b']) => 1

```
I debugged the code and found that the file `_baseGet.js` is wrong. The first one is the degug file, the second is in `node_modules`
![image](https://user-images.githubusercontent.com/22443356/95713761-ae602c00-0c99-11eb-9815-e06a71ace54b.png)
![image](https://user-images.githubusercontent.com/22443356/95713842-ccc62780-0c99-11eb-91a9-4b6ac23b1f00.png)

**Comment by bnjmnt4n** [comment]
See https://github.com/lodash/lodash-webpack-plugin#feature-sets. You might need to enable the `paths` property set for `lodash-webpack-plugin`.
