### ISSUE TITLE
Missing UTF-8 meta tag causes lodash import to break in the browser

### ISSUE THREAD

**Issue by mikemfleming** [lodash/lodash#4959]
I kept getting this error in the browser when importing Lodash's startCase method into my React project. 
```
Uncaught SyntaxError: Invalid or unexpected token
```

For a little while I thought it was an issue with how I was processing it with Webpack. 

Finally, adding a meta tag to my `index.html` file fixed it. The stack trace seemed to point to some strange characters, which seems to support the idea that it was something to do with the charset.
```
<!DOCTYPE html>
<head>
    <meta charset="UTF-8"> <--------------
</head>
<html>
    <body>
        <div id="root"></div>
    </body>
</html>
```

I'm not sure if this requires any action on the part of the maintainers but I hope that filing this issue might help someone else in the future.

**Comment by falsyvalues** [comment]
Hi @mikemfleming!

Looks like it might be related to your specific deployment env.

**Comment by OminousWater** [comment]
@mikemfleming Thank you so much for sharing this fix. I ran into this exact issue today after upgrading to a new release of webpack. Of course the problem only shows up on a minified/Production build which doesn't help😅 I quickly tracked the problem to lodash, but was baffled as to how to resolve it, you saved me hours of my time!
