### ISSUE TITLE
Copyright problem when scanned with Blackduck

### ISSUE THREAD

**Issue by theanha5** [lodash/lodash#4963]
lodash's copyright is MIT, but when I scan with Blackduck, almost all files are reported to be LGPL 3.0+ (related to LibreOffice). Is Blackduck confused?
![122428091_1198470510534803_111459125263606471_n](https://user-images.githubusercontent.com/37961082/97065651-3965ee00-15d9-11eb-9b37-6f9754629270.png)

**Comment by falsyvalues** [comment]
Hi @theanha5!

The one and valid license is located in [our repo](https://github.com/lodash/lodash/blob/master/LICENSE.) and its being attached to released package.

**Comment by SarathPravallika** [comment]
@theanha5 How is the blackduck scan issue resolved?

**Comment by andpor** [comment]
Have the same issue. Our BlackDuck scans log issues labelling them as LibreOffice but the underlinks references point to lodash files...
