### ISSUE TITLE
There is still no pascal case function

### ISSUE THREAD

**Issue by asologor** [lodash/lodash#4966]
See #942

**Comment by falsyvalues** [comment]
Hi @asologor!

Everything is in #942 please don't create unnecessary duplicates.

**Comment by asologor** [comment]
Right. Everything is in #942 but nothing has been done. And we don't have _.pascalCase() in 2020. Cool.

**Comment by falsyvalues** [comment]
No worries. There are plenty of alternatives for [camelcase](https://www.npmjs.com/package/camelcase).
