### ISSUE TITLE
ES6 iterables

### ISSUE THREAD

**Issue by xamgore** [lodash/lodash#4970]
ES6 provides a number of datastructures that are [iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/iterable). It would be nice if lodash supported these. This issue duplicates #737, as reactions can't be set on closed issues.

Let `a` and `b` be iterators yielding an infinite number of values, then:

```js
_.take(_.zip([...a], [...b]), 4) // never stops
_.take(_.zip(a, b), 4)           // is fine
```

**Comment by insonifi** [comment]
I would second that. It would be sweet to be able to iterate over `Map` and `Set`.
