### ISSUE TITLE
_.eq([], [])  == false

### ISSUE THREAD

**Issue by foreverglory** [lodash/lodash#4974]
If the parameter is Array, the result is wrong
```
_.eq([], []) == false
```

**Comment by papb** [comment]
This is the correct behavior.

> Performs a SameValueZero comparison between two values to determine if they are equivalent.

**Comment by blghns** [comment]
what you want to use is `_.isEqual([], [])`

**Comment by foreverglory** [comment]
in Vue, I'm going to use `watch` to listen for changes to the array.
```
export default {
  data(){
    return { files: [] }
  },
  watch: {
    files(newVal, oldVal){
      //Determine if the array is the same
      if(!_.eq(newVal, oldVal)){
          //there
      }
    }
  }
}
```
So _. eq cannot compare arrays.

**Comment by blghns** [comment]
@foreverglory look at the source code for _.eq vs _.isEqual

_.eq
https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L11184

_.isEqual
https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L11531

You're using the wrong method to compare. Eq is for checking if the object references are the same. Use isEqual for value comparison.

**Comment by foreverglory** [comment]
yes. thanks!
