### ISSUE TITLE
[Feature request]: mapValuesAsync

### ISSUE THREAD

**Issue by donaldshen** [lodash/lodash#4975]
An async version of mapValues. Find it hard to write a pull request without an async example.

I paste my TypeScript version down here for your concern.

```typescript
async function mapValuesAsync<T, E>(
  dict: _.Dictionary<T>,
  iteratee: (val: T, key: string) => Promise<E>
): Promise<_.Dictionary<E>> {
  return _.fromPairs(
    await Promise.all(
      _.toPairs(dict).map(async ([k, v]) => {
        return [k, await iteratee(v, k)]
      })
    )
  )
}
```

**Comment by bnjmnt4n** [comment]
Hi @donaldshen!

Generally, we prefer to defer async functionality to [async](https://www.npmjs.com/package/async).
