### ISSUE TITLE
Specials chars removed

### ISSUE THREAD

**Issue by lokomass** [lodash/lodash#4976]
Hi,
3 years after, somes functions don't work...
_upperFirst or _startCase removed automatically specials chars....
"año" become "Ano".
Is it possible to makes this correct please ?

**Comment by pritam-patil** [comment]
Removing non-ascii characters is probably understood but if input to `startCase` is `Mr. John`, it returns `Mr John`. Is it indeed expected? @jdalton @jashkenas

**Comment by OneHoopyFrood** [comment]
Duplicate of #3383
