### ISSUE TITLE
groupBy sorts keys unnecessary

### ISSUE THREAD

**Issue by fairking** [lodash/lodash#4977]
I have already sorted list in my collection based on some certain logic.
I thought that the lodash just performs grouping without any other element movements in the collection.
But just found it is actually also sorting elements by the key.

Is there any way to group elements without sorting?

Docs say it does not touch the order:
![image](https://user-images.githubusercontent.com/13495631/99190134-be69a080-275c-11eb-8b2a-d98be592107e.png)

**Comment by bnjmnt4n** [comment]
Hi @fairking! _.groupBy does not perform any sorting: would you be able to share a minimal reproduction of the issue you're describing?

**Comment by fairking** [comment]
https://jsfiddle.net/qtbcgvjx/1/

**Comment by bnjmnt4n** [comment]
See https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order.

Note also that the console seems to be the one sorting the output on display. Try `console.log(Object.keys(groupedList));` to see that the output follows `["D", "B", "C", "A" ]`.
