### ISSUE TITLE
unsafe eval static analysis warning for all lodash packages

### ISSUE THREAD

**Issue by blimmer** [lodash/lodash#4985]
The core lodash package falls back to a Function constructor when determining the `root` object here:

https://github.com/lodash/lodash/blob/898b378f069ecb6c92b7713529985ba78ff34d31/.internal/root.js#L10-L11

For folks working in privileged environments, like browser extensions, the use of a Function constructor throws static analysis warnings:

![Screen Shot 2020-11-23 at 12 26 11 PM](https://user-images.githubusercontent.com/630449/100006022-16b92780-2d87-11eb-9631-e6829f12b5d0.png)

In our case, this warning triggers a manual review of our extension each time we submit a new version, even though the modern browsers we support will never fall back to the `Function` constructor. It would be great if there were a way for us to somehow not include this fallback.

Maybe instead of using a Function constructor, you could instead fall back to an [Immediately Invoked Function Expression](https://en.wikipedia.org/wiki/Immediately_invoked_function_expression)? e.g.,

```javascript
const root = freeGlobalThis || freeGlobal || freeSelf || (function() { return this; })()
```

I believe this would accomplish the same thing without triggering warnings about CSP.

This ticket is similar to https://github.com/lodash/lodash/issues/4066 and https://github.com/lodash/lodash/issues/3328

**Comment by Alan-Liang** [comment]
In strict mode code the IIFE would yield `undefined`; however there is a [solution without using `eval`](https://mathiasbynens.be/notes/globalthis).

**Comment by dimovpetar** [comment]
Any update on this?

**Comment by rxliuli** [comment]
Is it possible to solve it internally in lodash?
