### ISSUE TITLE
Understanding lodash/fp immutable methods internals 

### ISSUE THREAD

**Issue by viebel** [lodash/lodash#4989]
I'd like to understand how the immutable methods of lodash/fp work. 

Do they deeply clone a collection before changing it or do they implement kind of a structural sharing between the two versions of the object? 

I have tried to understand it "from the outside" and I couldn't come to a clear conclusion.

In this snippet, mutating an updated collection doesn't impact the original collection.

~~~javascript
var data = {
  a: {
    c: {}
  }
}

var updatedData = fp.set(["a", c", "d"], 5, data);

updatedData.a.c.e = 9;

updatedData.a.e  // 9
data.a.c.e // undefined
~~~

In this snippet, mutating an updated collection does impact the original collection.

~~~javascript
var data = {
  a: {
    c: []
  }
}

var updatedData = fp.set(["a", "d"], 5, data);

updatedData.a.c[0] = 9;

updatedData.a.c[0]  // 9
data.a.c[0] // 9
~~~

**Comment by Jarzka** [comment]
https://stackoverflow.com/questions/65055922/how-do-immutable-methods-work-in-lodash-fp

**Comment by viebel** [comment]
Yeah. The link you sent is to the question I asked on SO.
