### ISSUE TITLE
Update documentation of lowerCase

### ISSUE THREAD

**Issue by elboukhari** [lodash/lodash#4993]
I think the related documentation needs to be updated accordingl :
The `lowerCase` is a case method like `camelCase`, `kebabCase`, `snakeCase`, or `startCase`. These casing methods deburr and separate words, and compound words, and then re-join them together based on their casing rules.

_Originally posted by @jdalton in https://github.com/lodash/lodash/issues/2792#issuecomment-258699452_

**Comment by steveetm** [comment]
It is super confusing, also`camelCase(['word1','word2','word3'])`seems to work fine, which is nice, but `@types/lodash` doesn't know about it, and I am not sure if I can rely on this feature of this function or will be changed in the future.
lodash@4
