### ISSUE TITLE
suggest "lodashjs.com" import the library

### ISSUE THREAD

**Issue by Wxh16144** [lodash/lodash#4996]
I noticed that the Chinese document of the lodash library has updated the theme, which is very beautiful, but it lacks a more user-friendly function, **which I cannot use in the developer tool (console);**

**before**
![image](https://user-images.githubusercontent.com/32004925/100703336-46e37480-33de-11eb-986e-cfb52089ab1e.png)

**after**
![image](https://user-images.githubusercontent.com/32004925/100703377-5fec2580-33de-11eb-9ebe-c38107aba113.png)

Thanks

**Comment by bnjmnt4n** [comment]
Hi, the lodashjs.com website is not maintained by the lodash team, so you might need to contact them separately for such requests. A cursory look at their site seems to show that they don't provide any ways of contacting them though, so I'm not sure how you might want to proceed.
