### ISSUE TITLE
_.uniq using the `_.property` callback shorthand not work

### ISSUE THREAD

**Issue by djmisterjon** [lodash/lodash#4997]
Not sure if is related to chromium version or lodash but the example in the demo not work on my side !

if i copy past the code from demo.
`_.uniq([{ 'x': 1 }, { 'x': 2 }, { 'x': 1 }], 'x');`
![image](https://user-images.githubusercontent.com/24865815/100822132-baf23c80-341f-11eb-9bde-44f452a7467e.png)
i get this !!! 
![image](https://user-images.githubusercontent.com/24865815/100821909-4fa86a80-341f-11eb-95cf-4acfaff90aa6.png)

--- 

**Lodash version**
```json
_.VERSION
"4.17.20"
```
**env version**
```json
ares: "1.16.0"
brotli: "1.0.9"
chromium: "85.0.4183.121"
icu: "67.1"
llhttp: "2.1.2"
modules: "83"
napi: "7"
nghttp2: "1.41.0"
node: "14.12.0"
node-webkit: "0.48.4"
nw: "0.48.4"
nw-commit-id: "36d836f-fd6a2d5-d62bfb6-db44bec"
nw-flavor: "sdk"
openssl: "1.1.1g"
unicode: "13.0"
uv: "1.39.0"
v8: "8.5.210.26"
zlib: "1.2.11"
```

----
EDIT:
 ok just update and try in last chromium 87 version, not work ! what happening here ?
![image](https://user-images.githubusercontent.com/24865815/100823083-91d2ab80-3421-11eb-9092-800514edbad6.png)

**Comment by bnjmnt4n** [comment]
Hi, `_.uniq` seems to be working fine. You might be using a different build of lodash (https://github.com/lodash/lodash/wiki/Build-Differences), or using a plugin (https://github.com/lodash/lodash-webpack-plugin) which removes callback shorthands.
