### ISSUE TITLE
`_.isFunction(async function* fn() {})` returns `false`

### ISSUE THREAD

**Issue by anseal** [lodash/lodash#5001]
```js
console.log(_.isFunction(      function* fn() {})) // --> true
console.log(_.isFunction(async function* fn() {})) // --> false
```

**Comment by nleclerc** [comment]
it would be nice to add that.
code is as follows :
`const isAsync = myFunction.constructor.name === "AsyncFunction";`

i don't have time to make a pull request now but i'll do it when i can.
