### ISSUE TITLE
lodash.pick package doesn't match functionality with the main package

### ISSUE THREAD

**Issue by mark-studer** [lodash/lodash#5005]
Some of the functions that get called down the stack in .pick have changed and thus the package published under lodash.pick does not function the same as the .pick function in the lodash package on NPM.

### Test Showing Behavior
```
import { assert } from 'chai';
import pick1 from 'lodash.pick';
import { pick as pick2 } from 'lodash';

it('lodash.pick returns nested values', function () {
    const properties = ['data.name'];
    const object = { data: { name: 'name' } };

    const response = pick1(object, properties);
    assert.deepStrictEqual(response, object);
});

it('lodash returns nested values', function () {
    const properties = ['data.name'];
    const object = { data: { name: 'name' } };

    const response = pick2(object, properties);
    assert.deepStrictEqual(response, object);
});
```

## Output
```
  1) lodash.pick returns nested values
  √ lodash returns nested values      

  1 passing (15ms)
  1 failing

  1) lodash.pick returns nested values:

      AssertionError: expected {} to deeply equal { data: { name: 'name' } }
      + expected - actual

      -{}
      +{
      +  "data": {
      +    "name": "name"
      +  }
      +}
```

### Fix
Can we publish an updated version of the lodash.pick package that incorporates the updated behavior?

**Comment by Parro** [comment]
It seems that it's an issue that has been fixed in the main `lodash` package but not in the single `lodash.pick` package, see
https://github.com/lodash/lodash/issues/4459 and https://github.com/lodash/lodash/issues/5005. Importing the full package should solve the issue, but will also increase the bundle size...
