### ISSUE TITLE
_.gt("3333", "444"). === return  false 

### ISSUE THREAD

**Issue by yaogengzhu** [lodash/lodash#5006]
## String comparison string
```md
Can the API only compare two numbers, or a number and a string? Is there support for comparing two string numbers
```

**Comment by zhuangya** [comment]
according to the source code, if both two parameter's type equal to `string`, two value would compare by the greater than operator directly

and base on [Abstract Relational Comparison](https://tc39.es/ecma262/#sec-abstract-relational-comparison) this is the expected behavior
