### ISSUE TITLE
Are the per method packages behind in releases?

### ISSUE THREAD

**Issue by aljones15** [lodash/lodash#5007]
I noticed this recently:

`lodash.set` was [last updated 4 years ago](https://www.npmjs.com/package/lodash.set) | [source code](https://github.com/lodash/lodash/tree/4.5.0-npm-packages/lodash.set)
`lodash.get` was [last updated 4 years ago](https://www.npmjs.com/package/lodash.get) | [source code](https://github.com/lodash/lodash/tree/4.5.0-npm-packages/lodash.get)
`lodash.template` [was last updated a year ago](https://www.npmjs.com/package/lodash.template) |  [source dode](https://github.com/lodash/lodash/tree/4.5.0-npm-packages/lodash.template)
`lodash.topath` [was last updated 4 years ago](https://www.npmjs.com/package/lodash.topath) | [source code](https://github.com/lodash/lodash/tree/4.5.0-npm-packages/lodash.topath)

The source code for most of these per method packages was updated 17 months ago. The last npm publish though was 4 years ago unless otherwise stated.  What I'm wondering is, does this mean the lodash team is behind on releasing updates to `lodash.set`, `lodash.get`, and `lodash.topath` or is the code just updated from a build process and not in need of an update? The later seems more likely, but I was concerned the per method packages could contain CVEs in them even though not flagged.

**Comment by falsyvalues** [comment]
Hi @aljones15!

See #3943
