### ISSUE TITLE
Deep lodash module dependencies on Windows hit path length limit

### ISSUE THREAD

**Issue by dmethvin** [lodash/lodash#501]
It looks like lodash is using npm to manage its internal dependencies. As a result it creates some pretty deep `node_modules` directory trees and runs up against the limit of 260 characters on Windows paths. Here's what it looks like on my system, [JSCS just wants to pull in _.assign](https://github.com/gustavohenke/grunt-jscs-checker/blob/master/tasks/lib/jscs.js#L83) and ends up with this 268-char path at the point where it dies:

```
C:\wamp\www\jquery-release\__release\repo\node_modules\grunt-jscs-checker\node_modules\lodash.assign\node_modules\lodash._basecreatecallback\node_modules\lodash.bind\node_modules\lodash._createwrapper\node_modules\lodash._basecreatewrapper\node_modules\lodash.isobject
```

There's a way to get around the path limit by prefixing the path name but I assume nothing on node or npm does this: http://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages.
