### ISSUE TITLE
`merge`ing arrays, a bug or expected behaviour?

### ISSUE THREAD

**Issue by sohale** [lodash/lodash#5010]
The following command
```javascript
  const { merge} = require('lodash');
  const s = [ 'a1', 'b2' ];
  const t = [ 'c1', 'd2', 'e3' ];
  merge(t,s);
  console.log(t);
```
This will result in  `[ 'a1', 'b2', 'e3' ] `
While the expected result is `[ 'a1', 'b2', 'c1', 'd2', 'e3' ] `

Is this a bug? or expected behaviour in lodash?

**Comment by seeker1983** [comment]
Think of it as

     _.merge({ 0:'a1', 1:'b2' }, { 0: 'c1', 1: 'd2', 2: 'e3' });

which works as expected.

You can use _.union or _.concat for your expected output
