### ISSUE TITLE
Cannot resolve _arrayMap.js in lodash-es

### ISSUE THREAD

**Issue by c43721** [lodash/lodash#5011]
./node_modules/lodash-es/toPath.js
Module not found: Can't resolve './_arrayMap.js' in 'node_modules\lodash-es'

Using React and Typescript, from the CRA typescript template.

This is where the error is happening:
```
// lodash-es toPath.js
import arrayMap from './_arrayMap.js';  // This line errors, there's no files prefixed with _ in the folder
import copyArray from './_copyArray.js';
import isArray from './isArray.js';
import isSymbol from './isSymbol.js';
import stringToPath from './_stringToPath.j
```

This package was installed from a dependency of Formik.

**Comment by bnjmnt4n** [comment]
I can't reproduce this. This seems like an issue with your install. Try removing your `node_modules` folder and re-installing.

**Comment by RomanZabila** [comment]
@bnjmnt4n I have the same issue, removing and reinstalling not works. In my case, formik library has lodash-es dependency which cause this error.

**Comment by RomanZabila** [comment]
For anyone who will face with this kind of issue, just run
`yarn cache clean`
