### ISSUE TITLE
'Object.getPrototypeOf(value) === null', this is correctly ?

### ISSUE THREAD

**Issue by YXM-fish** [lodash/lodash#5032]
function isPlainObject(value) {
  if (!isObjectLike(value) || getTag(value) != '[object Object]') {
    return false
  }
  if (Object.getPrototypeOf(value) === null) {
    return true
  }
  let proto = value
  while (Object.getPrototypeOf(proto) !== null) {
    proto = Object.getPrototypeOf(proto)
  }
  return Object.getPrototypeOf(value) === proto
}

var a = { x: 1 }
Object.setPrototypeOf(a, null)
Object.getPrototypeOf(a) === null    => true
the variable 'a' is a plain object ? of course not !

**Comment by bnjmnt4n** [comment]
Please see the [documentation](https://lodash.com/docs/4.17.15#isPlainObject):

> Checks if value is a plain object, that is, an object created by the Object constructor or one with a [[Prototype]] of null.
