### ISSUE TITLE
New methods: removeStart and removeEnd

### ISSUE THREAD

**Issue by felipecrs** [lodash/lodash#5038]
Inspired by [Python 3.9's `removeprefix` and `removesuffix`](https://dev.to/delta456/python-removeprefix-and-removesuffix-34jp).

These methods are different from `trim{Start|End}` because `remove{Prefix|Suffix}` will only remove if the string starts with the specified substring:

```js
_.trimStart('-_-abc-_-', '_-');
// => 'abc-_-'

_.removePrefix('-_-abc-_-', '_-');
// => '-_-abc-_-'
```

Another difference is that `remove{Prefix|Suffix}` has a second mandatory parameter, where trim's methods default to `whitespace`.

**Comment by Ramnmo** [comment]
We can these methods this way:
`function removePrefix(string, prefix) {
    if (string.startsWith(prefix)) {
        return string.substr(prefix.length);
    } 
    return string;
}

function removeSuffix(string, suffix) {
    if (string.endsWith(suffix)) {
        return string.substr(0, string.length - suffix.length);
    } 
    return string;
}`

**Comment by Ramnmo** [comment]
We can these methods this way:
```
function removePrefix(string, prefix) {
if (string.startsWith(prefix)) {
return string.substr(prefix.length);
}
return string;
}

function removeSuffix(string, suffix) {
if (string.endsWith(suffix)) {
return string.substr(0, string.length - suffix.length);
}
return string;
}
```

**Comment by Ramnmo** [comment]
We can these methods this way:
`
function removePrefix(string, prefix) {
if (string.startsWith(prefix)) {
return string.substr(prefix.length);
}
return string;
}

function removeSuffix(string, suffix) {
if (string.endsWith(suffix)) {
return string.substr(0, string.length - suffix.length);
}
return string;
}
`

**Comment by Ramnmo** [comment]
We can these methods this way:
```javascript
function removePrefix(string, prefix) {
if (string.startsWith(prefix)) {
return string.substr(prefix.length);
}
return string;
}

function removeSuffix(string, suffix) {
if (string.endsWith(suffix)) {
return string.substr(0, string.length - suffix.length);
}
return string;
}
```

**Comment by felipecrs** [comment]
Hey @Ramnmo, did you take a look at the [current implementation I proposed](https://github.com/lodash/lodash/pull/5039)? 

I wonder which one is the best, or if there is any difference.

**Comment by Ramnmo** [comment]
I suggest you take a loot at time [complexity of replace method](https://stackoverflow.com/questions/47209406/what-is-the-time-complexity-or-big-o-notation-for-str-replace-built-in-funct) with is O(n) and n is dependent on the length of the main string, and time complexity of substr is O(1). because it doesn't have to copy the string, it just has to beginning and ending markers to the main string. so I think my code is more efficient.

**Comment by felipecrs** [comment]
I implemented your suggestion.
