### ISSUE TITLE
lodash structure

### ISSUE THREAD

**Issue by nimasrn** [lodash/lodash#5041]
could anyone explain to me please, how lodash come up with this structure and why not using folders as a category, even though we could have sub-categories if we use folders as categories and index files to use them all in one place?
for example, having something like this: 
what we have like:
1. date/getMonthRange
           /getYearRange
           /getDayRange
why not like this:
2. date/range/getMonthRange or date/range/month
                                                                      /day
                                                                      /year
we also could  import by category or import all,
Maybe the example was not the best idea but I assume that you get me.

**Comment by falsyvalues** [comment]
Hi @nimasrn!

I will try to use a quote to give an answer, we tend to use things that works for us.

> move files around until it feels right

http://react-file-structure.surge.sh/
