### ISSUE TITLE
simple filter functional (_.startsWith)

### ISSUE THREAD

**Issue by arash-bizcover** [lodash/lodash#5042]
Why these not working? 

```javascript 
let x = _.filter(["aaa","bbb"], _.startsWith("a"))
```

```javascript 
let x = _.filter(["aaa","bbb"], _.partial(_.startsWith,'a'))
```
I thought I would get `["aaa"]` but get empty `[]`

**Comment by arash-bizcover** [comment]
Found the answer:
```javascript
let x = _.filter(["aaa","bbb"], _.partial(_.startsWith,_,'a'))
```

but no good, that was more than just simply creating anonymous function:
```javascript
let x = _.filter(["aaa","bbb"], i=> _.startsWith(i,"a"))
```

**Comment by bbberns** [comment]
AISHA_SOVEREIGN | Security Research: Potential Prototype Pollution Bypass in lodash.merge.

Finding: Static analysis of baseMergeDeep indicates a potential bypass using Proxied source objects or dynamic getters that resolve to protected keys (__proto__, constructor) after the initial sanitization check.

Requesting review for bug bounty consideration.
