### ISSUE TITLE
[lodash.camelCase] unexpected output 'orderId' for input 'OrderID'

### ISSUE THREAD

**Issue by iheyunfei** [lodash/lodash#5045]
for input `'OrderID'`,
I get output `'orderId'` from `lodash.camelCase`,
but, i get `'orderID'` from  `'humps.camelize'`.
the main difference is **ID** or **Id**. just want to make sure this is not a bug.

**Comment by Alan-Liang** [comment]
See #561; it seems to be intentional.

**Comment by falsyvalues** [comment]
Hi @iheyunfei!

Nothing changed since #561 #3383 in this topic and won't change until next major release.
