### ISSUE TITLE
[Dark mode] it cannot show lodash logo when I change to dark mode

### ISSUE THREAD

**Issue by JCHappytime** [lodash/lodash#5046]
hi,
  In doc page (https://www.lodashjs.com/), it is great to provide dark mode for users, but there is a problem: when I change to dark mode, it cannot show lodash logo. Please check following picture:
![logo](https://user-images.githubusercontent.com/10249805/103625704-4e1a1700-4f76-11eb-93e5-b58ff8650cfc.png)

**Comment by jiangwenyang** [comment]
I'm not sure this website is being maintained by Lodash，you can visit  https://www.lodash.com

**Comment by jiangwenyang** [comment]
> hi,
> In doc page (https://www.lodashjs.com/), it is great to provide dark mode for users, but there is a problem: when I change to dark mode, it cannot show lodash logo. Please check following picture:
> ![logo](https://user-images.githubusercontent.com/10249805/103625704-4e1a1700-4f76-11eb-93e5-b58ff8650cfc.png)

I'm not sure this site is maintained by Lodash，You can get the latest English documentation at http://www.lodash.com

**Comment by JCHappytime** [comment]
> http://www.lodash.com

yeap, got it. Thanks~

**Comment by JCHappytime** [comment]
> > hi,
> > In doc page (https://www.lodashjs.com/), it is great to provide dark mode for users, but there is a problem: when I change to dark mode, it cannot show lodash logo. Please check following picture:
> > ![logo](https://user-images.githubusercontent.com/10249805/103625704-4e1a1700-4f76-11eb-93e5-b58ff8650cfc.png)
> 
> I'm not sure this site is maintained by Lodash，You can get the latest English documentation at http://www.lodash.com

yeap, got it. Thanks~

**Comment by falsyvalues** [comment]
Hi @JCHappytime!

https://lodash.com/ is only supported by lodash team site. There is a dedicated repo for website issues https://github.com/lodash/lodash.com (but not in this case).

**Comment by JCHappytime** [comment]
> Hi @JCHappytime!
> 
> https://lodash.com/ is only supported by lodash team site. There is a dedicated repo for website issues https://github.com/lodash/lodash.com (but not in this case).

got it, thanks.
