### ISSUE TITLE
The lodash/fp get has wrong order arguments

### ISSUE THREAD

**Issue by DavidHenri008** [lodash/lodash#5048]
The `get` function with lodash/fp has the wrong arguments order compare with the standard `get` function.

The documentation is most likely missing the custom order for the get function: `get(b,a)` 

Thanks.

**Comment by DavidHenri008** [comment]
Ok, I just saw the documentation specifying the arity of two order.

**Comment by chou7888** [comment]
Hello,
Actually, I am nearly illiterate in using the Github.  I've tried to learn,
for about 3 months, but I still don't know anything about how to write, to
read..
Honestly speaking, I am a  mid-aged gay bottom gay, I like to pay some
money to buy an one night sex service.
.If somebody can help me find a sex mate, I'd be very very happy.
Thanks a lot!
Chou Hung Yang
