### ISSUE TITLE
_.every provides incorrect arguments to predicate when called on object with "length" key

### ISSUE THREAD

**Issue by jsspiegel** [lodash/lodash#5052]
When `_.every` is called on an object which contains a key labeled `length` which has an integer value, the predicate seems to be called with `value = undefined` and `key = 0`. This can be seen in the following example:
```
_.every({length: 1}, (value, key) => {
    console.log(value)
    console.log(key)
    return true
})
```
The above logs `undefined` and `0`, though it correctly returns `true`. Additionally, if other keys are added to the object, the `console.log` is seemingly only called once. This can be seen in the following example:
```
_.every({length: 1, foo: "bar"}, (value, key) => {
    console.log(value)
    console.log(key)
    return true
})
```
The above again logs `undefined` and `0` and correctly returns `true`.

**Comment by bnjmnt4n** [comment]
_.every is a Collections method, and treats any object with a length property like an array-like object. Since you've passed in an object with length 1, it tries to access `object[0]` and calls your callback with index 0 and value `undefined`.
