### ISSUE TITLE
startCase separates acronym

### ISSUE THREAD

**Issue by CubeOfCheese** [lodash/lodash#5053]
I have a string that includes an acronym. The acronym is pluralized and it is causing a space to be added inappropriately.
The string: "otherACRs"
Intended output: "Other ACRs"
Actual output: "Other AC Rs"

Is there a technical limitation here or is there an opportunity for this function to be improved to accommodate a case like this?

**Comment by Alan-Liang** [comment]
See #561

TL; DR: `XMLHttpRequest`

**Comment by CubeOfCheese** [comment]
Thanks. So it seems like this rule:
> Begin with a capital letter followed by lower case letters with optional trailing numbers, e.g. Hello or Http2
is the one at play. I wonder if an exception for the letter 's' could be made to account for cases like this one where you have a pluralized acronym. I'm guessing it might create ambiguity though.
"theRCIsland" seems like a case that would be broken by the change I'm suggesting as it would result in "The RCIs Land" instead of "The RC Island"

**Comment by falsyvalues** [comment]
Hi @CubeOfCheese!

Nothing changed since #561 #3383 in this topic (it works as expected) and won't change until next major release. Please search through closed issue.
