### ISSUE TITLE
Different source code in master and 4.17.20 release branches 

### ISSUE THREAD

**Issue by smolk0** [lodash/lodash#5054]
Initially I noticed the inconsistency in i**sPlainObject.js** file

master version - https://github.com/lodash/lodash/blob/master/isPlainObject.js#L30
```js
function isPlainObject(value) {
  if (!isObjectLike(value) || getTag(value) != '[object Object]') {
    return false
  }
  if (Object.getPrototypeOf(value) === null) {
    return true
  }
  let proto = value
  while (Object.getPrototypeOf(proto) !== null) {
    proto = Object.getPrototypeOf(proto)
  }
  return Object.getPrototypeOf(value) === proto
}
```

current 4.17.20 version - https://github.com/lodash/lodash/blob/4.17.20-npm/isPlainObject.js#L49
```js
function isPlainObject(value) {
  if (!isObjectLike(value) || baseGetTag(value) != objectTag) {
    return false;
  }
  var proto = getPrototype(value);
  if (proto === null) {
    return true;
  }
  var Ctor = hasOwnProperty.call(proto, 'constructor') && proto.constructor;
  return typeof Ctor == 'function' && Ctor instanceof Ctor &&
    funcToString.call(Ctor) == objectCtorString;
}
```

then I analyzed commit history for this file and found this:
https://github.com/lodash/lodash/commit/b36f21cbaff7c885223b44267c70e6711b754af6#diff-65f696b2f5c100169c45cb567fd3c19692efaef63a3ddb459a92a43f26a57f91

This commit contains refactoring of isPlainObject function from version which is currently in release branch to master branch version.

I may be wrong but it seems that update version of isPlainObject from master is not build properly in release package and release package contains old version of the function

I do not know what is the build process for release version (is lodash-cli still in active use?) so may somebody check and verify?

P.S. there are also bunch of functions which are different e.g attempt.js

**Comment by Alan-Liang** [comment]
<https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md>：

> Pardon the mess. The master branch is in flux while we work on Lodash v5. This means things like npm scripts, which we encourage using for contributions, may not be working. Thank you for your patience.

**Comment by Alan-Liang** [comment]
<https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md>：

> Pardon the mess. The master branch is in flux while we work on Lodash v5. This means things like npm scripts, which we encourage using for contributions, may not be working. Thank you for your patience.

**Comment by smlkA** [comment]
@Alan-Liang Thanks for the link, have not seen before
But still I think it is worth to check build script as update for **isPlainObject** function is done on 8 Nov 2017 and that code is not in npm.
@timdorr Hey, sorry to mention you, but I am really super confused why your commit is not in current release

**Comment by smolk0** [comment]
@Alan-Liang Thanks for the link, have not seen before
But still I think it is worth to check build script as update for isPlainObject function is done on 8 Nov 2017 and that code is not in npm.

@timdorr Hey, sorry to mention you, but I am really super confused why your commit is not in current release

**Comment by bnjmnt4n** [comment]
Hi! As mentioned by @Alan-Liang, the code in master is in preparation for the v5 branch, which has not been released. The current code in npm is from v4, hence there is a difference.
