### ISSUE TITLE
Lodash.template cannot support OPTIONAL CHAINING

### ISSUE THREAD

**Issue by GloriousFt** [lodash/lodash#5061]
VERSION:
"lodash.template": "^4.5.0"

PLATFORM:
Android Chrome 83 

PROBLEM:
```javascript
lodash.template('
<% if(a?.b?.c) {%>
    <div class="banner-gift__icons">
        <img class="banner-gift__icons__avatar" src="<%=a?.b?.c%>" />
    </div>
<%}%>
', { a: { b: {c : 1}}});
```

It occurs an error: "Uncaught SystaxError: Unexpected token '.'".
It seems like lodash template cannot support optional chaining on Android . iOS is fine with it.

**Comment by bnjmnt4n** [comment]
`_.template` passes your input source code to the JavaScript engine, and does not perform any transpilation. Seems like older versions of Android do not support optional chaining operators, so if you do need to support them you'd have to either perform transpilation yourself or just switch away from optional chaining operators.
