### ISSUE TITLE
suggestion: delete object if exist 

### ISSUE THREAD

**Issue by eladonline** [lodash/lodash#5063]
I want to delete a property from object if it exist for now I do 
```
 if (_.get(mockOverrides,["endpoint", "method", "parameters", "sourceOpenapi"], null)) {
          delete mockOverrides["endpoint"]["method"]["parameters"]["sourceOpenapi"];
     }
```
would be awesome to have `_.delete(mockOverrides ,["endpoint", "method", "parameters", "sourceOpenapi"])`

**Comment by bnjmnt4n** [comment]
Hi! You're looking for https://lodash.com/docs#unset. In the future, please do try to read the documentation throughly to see if there's already such a function before creating an issue.
