### ISSUE TITLE
_.every with nested object values

### ISSUE THREAD

**Issue by silverbullettruck2001** [lodash/lodash#5064]
I have an object that is an array of objects and I want to verify that all objects in the array have the same attribute value.  But I am not able to get the _.every function to return correctly.  Here's what I have:
Object:
`{ 
"foo": [
{"bar1": "something", "bar2": "testing", "bar3": {"item": 4, "price": 5.00}},
{"bar1": "another", "bar2": "grizzly", "bar3": {"item": 3, "price": 5.00}}
]
}`

What I want to verify is that every instance in the array have the same "price" amount.  In the above example I would expect it to return true, but if one had a "price" of 6.00 and the other was still 5.00, then it should return false.

**Comment by raunaqkapoor** [comment]
Are you trying to compare the price to a given value or is it a comparison between all values of the array?

If it's former then you could use something like this
```
const x = {
  foo: [
    { bar1: 'another', bar2: 'testing', bar3: { item: 4, price: 5.0 } },
    { bar1: 'another', bar2: 'grizzly', bar3: { item: 3, price: 5.0 } },
  ],
};

const comparePrice = 5;

_.every(x.foo, ({ bar3: { price } }) => price === comparePrice); // true
```

If it's the latter something like this?
`_.every(x.foo, ({ bar3: { price } }) => price === x.foo[0].bar3.price); // true`

_.every() invokes the function on each iteration whereas you require a comparator function. So this is not the most elegant, but might do the trick.

I think some edge cases might get missed out here, 2 off the top of my head are foo.length == 0 or if the price is undefined.
