### ISSUE TITLE
filter: docs seem incomplete + return value seems wrong for objects

### ISSUE THREAD

**Issue by kaiyoma** [lodash/lodash#5077]
Looking at the docs for filter (https://devdocs.io/lodash~4/index#filter), I can't tell what gets returned if I pass an object to the function. The docs say that "the new filtered array" is returned. Array of what? Values? Keys? Both? I had to resort to trial and error to figure out that it's an array of values.

In addition to a docs update, the example below the docs could be updated to show how this works for collections.

The other issue is something that probably won't get fixed, since it would break backwards compatibility, but the return value for objects seems wrong. Shouldn't filtering an object give you an object in return? If you only want the values, you can easily call `values()` on that result. The current approach is removing data that could be really useful in certain situations.

**Comment by jasonmichaels** [comment]
@kaiyoma -- I'm not a maintainer, but I think the behavior of `_.filter`, as well as the documentation, works as expected and is sensible, respectively. 

You don't pass an object to the function (or, optionally, the `matches`, `matchesProperty`, or `property` shorthand alternative second arguments) -- elements are iteratively evaluated via the `predicate`, and entire elements -- whether primitives or objects, etc. --  that pass the evaluation are added to the new array and returned.

When the docs say `// => objects for ['fred']`, for example, they mean, quite literally, `objects` in their entirety. At its core, albeit with added functionality, it returns arrays quite comparably to the native `Array.prototype.filter` function. 

As to the final paragraph of your comment, it's unclear what you mean. Here's an example, with expected results:

```js
const _ = require('lodash');

const arr = [
  {
    id: 2,
    name: 'fred',
    age: 35
  },
  {
    id: 3,
    name: 'mary',
    age: 22
  },
  {
    id: 4,
    name: 'james',
    age: 27
  },
  {
    id: 5,
    name: 'cathy',
    age: 39
  }
];

console.log(_.filter(arr, ['name', 'fred'])); // returns `fred` entire object in array of length 1
console.log(_.filter(arr, obj => obj.age >= 30)); // entire `fred` and `cathy` objects in array of length 2
console.log(_.filter([1, 2, 3, 4, 5, 99], num => num > 5)); // [99]
```
The purpose of `_.filter` is to weed out elements that fail to meet the given predicate/assertion.

**Comment by kaiyoma** [comment]
> You don't pass an object to the function

Yes you can. The first argument is `collection`, which includes objects. Try it yourself:

```
$ node
Welcome to Node.js v14.15.0.
Type ".help" for more information.
> const _ = require('lodash');
undefined
> const obj = { a: 1, b: 2, c: 3 };
undefined
> _.filter(obj, value => value > 1);
[ 2, 3 ]
```

What I was proposing is that if an object is passed in, then an object should be returned too. In the example above, I wish that this is actually what happens at the end:

```
> _.filter(obj, value => value > 1);
{ b: 2, c: 3 }
```

This seems far more useful and more appropriate, given the type of the input.

**Comment by jasonmichaels** [comment]
No, no -- I meant it's passed imperatively by way of the signature, not directly. The callback arg is the object, of course. 

For your needs, I think there's the `_.find` function, similar to the native `Array.prototype.find`.

```js
const _ = require('lodash');

const arr = [
  {
    id: 2,
    name: 'fred',
    age: 35
  },
  {
    id: 3,
    name: 'mary',
    age: 22
  },
  {
    id: 4,
    name: 'james',
    age: 27
  },
  {
    id: 5,
    name: 'cathy',
    age: 39
  }
];

console.log(_.find(arr, obj => obj.age > 30)); // returns entire `fred` object, sans array
```

**Comment by kaiyoma** [comment]
You're still passing an array as the first argument. I'm talking about passing an object as the first argument to the lodash function.

Also, `find` is not the same as `filter`. `find` returns the first element; I'm talking about `filter`, which returns all matching elements.

**Comment by jasonmichaels** [comment]
Huh. It's weird that you would pass a single object to check whether to return the same object. Perhaps that's why this is a confused thread. Correct me if I'm wrong, but -- [at least according to this comment's result ](https://github.com/lodash/lodash/issues/5077#issuecomment-777945322)-- is this closer to what you're looking for?

```js
const _ = require('lodash');

const obj = {
  a: 1,
  b: 2,
  c: 3
};
  
const result  = _.pickBy(obj, value => value > 1);

console.log(result); // { b: 2, c: 3 }
```

**Comment by kaiyoma** [comment]
Ah yes, that's it! That's exactly what I'm looking for, thanks for pointing that out. I had assumed that this would have been included in the "filter" functionality, but I guess not.

I still think the docs could be improved here, since it's not immediately clear what you'll get from `filter` if you pass an object. For other iterable types (e.g. arrays and strings), it's pretty obvious what'll happen. A simple line of code + a comment in the examples section would suffice I think.

**Comment by jasonmichaels** [comment]
I doubt the maintainers would be against changes to their documentation, so long as it keeps to the style and is well-reasoned.

**Comment by kaiyoma** [comment]
Based on the existing examples and the voice they tend to use, it could be something like this:

```
// When collection is an object.
_.filter({ a: 1, b: 2, c: 3 }, value => value > 1);
// => [2, 3]
```

**Comment by falsyvalues** [comment]
Hi @kaiyoma!

[_.filter](https://lodash.com/docs/4.17.15#filter) docs explicitly says that it will return an array there is no doubt here. Describing every use case doesn't make docs better.

**Comment by kaiyoma** [comment]
> [_.filter](https://lodash.com/docs/4.17.15#filter) docs explicitly says that it will return an array there is no doubt here. Describing every use case doesn't make docs better.

The doubt is what the array contains. I'm not asking to document every use case, but maybe document this one, which is not obvious.
