### ISSUE TITLE
Pick shows strange behavior for missing properties

### ISSUE THREAD

**Issue by avlonder** [lodash/lodash#5078]
Works:
```
pick({ a: 1, b: 2, c: 3 }, ['a', 'c'])
```
Doesn't work:
```
pick({ a: 1, b: 2, c: 3 }, ['a', 'd'])
```
Expected behavior: return { a: 1 }

**Comment by jasonmichaels** [comment]
@avlonder -- not sure about your implementation, but I [ran a `repl`](https://repl.it/@drunkenkismet/Lodash-Pick#index.js) to test out your code and the result was as expected. Check the documentation for `hasIn.js`, which checks via the `predicate` callback whether the key is in the object; if it is, it's added to the result. If not, nada. Or, rather, is that the exact code you were using, and what version of `lodash` are you using in your project?

**Comment by avlonder** [comment]
How embarrassing. I had a quotes typo in my unit test. Thanks for the repro.
