### ISSUE TITLE
Feature Request: Append

### ISSUE THREAD

**Issue by neomedeiros** [lodash/lodash#5086]
It would be great to have an "append" function to add a new string at the end of another one. It would be handy specially on FP:

![image](https://user-images.githubusercontent.com/13244051/108366800-86e51700-71d7-11eb-9feb-5bf36e52db39.png)

**Comment by pereirapy** [comment]
I can't wait for it!!

**Comment by eliasjnior** [comment]
```
const a = 1
const b = 2

const appendResult = pipe(
  append(2),
  append(b)
)(a)
```

Should return `5` or `'122'`?

**Comment by neomedeiros** [comment]
I believe it would make sense considering append as a string function.

"add" already summarize the result:

add(5)(5) = 10
append(5)(5) = 55

**Comment by okuratoshiaki** [comment]
why not?

const appendResult = pipe(
    concat(":"),
    concat(b),
    join("")
)(a)

**Comment by okuratoshiaki** [comment]
will third call work?

append(5)(5)(5)

**Comment by neomedeiros** [comment]
The "concat" approach looks interesting, it definitely does the trick. But the "append" feature would avoid the array operation using "join", being aimed for string operations. 

I think the third or nth call it is a great idea as well.

**Comment by sciffany** [comment]
> will third call work?
> 
> append(5)(5)(5)

No this won't work because curry only works for two parameters e.g. append (5)(5). But, if you use pipe, you can continuosuly apply append on previous appendResults as shown

https://runkit.com/sciffany/lodash-5086
