### ISSUE TITLE
_.merge: Unexpected behavior merging nested objects

### ISSUE THREAD

**Issue by BrianSantoso** [lodash/lodash#5089]
`_.merge` will not recursively merge **nested** objects instantiated from the **same constructor**. Expected behavior is like a recursive Object.assign()

```
class RoomData {
  constructor(room) {
     this._room = room;
  }
}

let base = {_roomData: new RoomData('room')}
let delta = {_roomData: new RoomData()}
let merged = _.merge(base, delta);
console.log(merged)
// expected: Object {_roomData: RoomData {_room: 'room'}}
// got: Object {_roomData: RoomData {_room: undefined}}

// Proof that RoomData objects are not being recursively merged, but rather the _roomData reference is just reassigned
console.log(merged._roomData === delta._roomData)
// expected: false
// got: true

// What if we use object literals?
_.merge({_roomData:{_room: 'a'}}, {_roomData:{}})
// works as expected: Object {_roomData: Object {_room: "a"}}

// What if the objects aren't nested?
_.merge(new RoomData('room'), new RoomData());
// works as expected: Object {_room: "room"}
```

**Comment by bnjmnt4n** [comment]
This is intentional. See https://github.com/lodash/lodash/issues/1455#issuecomment-139306291 for more context. The documentation also states that:

> Source properties that resolve to undefined are skipped if a destination value exists. Array and plain object properties are merged recursively. **Other objects and value types are overridden by assignment.**

**Comment by BrianSantoso** [comment]
Ah, makes sense. What would be the solution for recursively merging all types of Object properties?--essentially a recursive Object.assign?
