### ISSUE TITLE
Update to actions/setup-node@v2

### ISSUE THREAD

**Issue by HonkingGoose** [lodash/lodash#5095]
I propose that this project updates the `actions/setup-node` version used in their GitHub Actions CI.

`actions/setup-node` is stable as of version 2.14, using the `v2` tag will point to the latest `v2` release.
See the change-logs for the `v2` release line at https://github.com/actions/setup-node/releases

**Comment by Jerbrone** [comment]
- [ ] [
[](https://www.apple.com/us/shop/goto/buy_iphone/iphone_12)](https://www.apple.com/us/shop/goto/buy_iphone/iphone_12)

**Comment by falsyvalues** [comment]
Hi @HonkingGoose!

We will consider that, thanks.
