### ISSUE TITLE
How to resolve the high prio Snyk vulnerability raised for all the recent Lodash versions?

### ISSUE THREAD

**Issue by PayelKarmakar06** [lodash/lodash#5096]

**Comment by cheesiangcs** [comment]
Yeah, I'm interested to know as well.

**Comment by RogerHofmann** [comment]
FYI this is Black Duck vulneriibility record https://sap.blackducksoftware.com/api/vulnerabilities/BDSA-2021-0392/overview

**Comment by stof** [comment]
They are resolved in 4.17.21 which has been released on Saturday. But snyk has not updated their advisory database yet to reflect that fact.

**Comment by falsyvalues** [comment]
Hi @PayelKarmakar06!

Lodash v4.17.21 was released on 2nd of Feb and its generally available through [npm](https://www.npmjs.com/package/lodash).

@RogerHofmann this isn't public registry.
