### ISSUE TITLE
_.some and _.every treat empty collections differently

### ISSUE THREAD

**Issue by bolenc** [lodash/lodash#5098]
The documentation says that the `every` method returns true for empty collections because all tests are vacuously true in that case. If so, the same should be true for `some`.

```
_.every([])
true
_.some([])
false
```

**Comment by correcthorsebatterystaple** [comment]
This has to do with quantifiers. Let there be a bus stop, if there is no one at the bus stop then it is true for me to say "Every person at the bus stop is bald", but it would be untrue for me to say "There is some person that is bald at the bus stop". This is a similar logic to why _every_ would return true and _some_ would return false for empty collections.
