### ISSUE TITLE
unionBy documentation has inconsistent method definition compared to example

### ISSUE THREAD

**Issue by devin-liu** [lodash/lodash#5100]
Expected: method definition and examples both show 3 arguments [array1, array2, iteratee]
Actual: method definition shows 2 arguments and examples show 3

![image](https://user-images.githubusercontent.com/7874845/109229368-0ba3d800-7778-11eb-9251-b5be44fa11e4.png)
![image](https://user-images.githubusercontent.com/7874845/109229399-16f70380-7778-11eb-8267-623b9c210120.png)

**Comment by sciffany** [comment]
The `[arrays]` part of the arguments can be set to as many arrays as possible.

As you can see in this example
https://runkit.com/sciffany/6048115e569e41001b0edc42
