### ISSUE TITLE
toNumber (comma separator)

### ISSUE THREAD

**Issue by ShaMan123** [lodash/lodash#5105]
Hi,
Great library! Thanks!
Continuing #3027 in a different angle.

### Expected Behaviour
```js
_.toNumber('3,200') => 3200
```

### Actual Behaviour
```js
_.toNumber('3,200') => NaN
```

### Workaround
```js
_.toNumber(_.replace('3,200', /,/g, ''))
```

I think it should handle this case internally

**Comment by huyennbl** [comment]
As in #3027, @jdalton explained that `_.toNumber()` is a type coercion method, not a kind of number extracting function, then the actual behaviour is expected I guess

**Comment by huyennbl** [comment]
@ShaMan123  A workaround that will extract all number in a string and combine into a single number for your case: 
```
'3,200'.match(/\d/g).join('')
```
