### ISSUE TITLE
Default value using _.get is not working properly when getting an array

### ISSUE THREAD

**Issue by dotamir** [lodash/lodash#5106]
Hi.
I'm using `_.get` a lot in my daily works and it's a really useful tool for me. But I can't use it when I'm working with arrays!
The default value is not working as I'm expecting.

```js
obj = {
	arr: undefined
}
_.get(obj, 'arr', []);
```

As you see I've set the default value to be `[]` if the array is not accessible. But it's returning `undefined` instead of an empty array. And I have to use this way:

```js
obj = {
	arr: undefined
}
_.get(obj, 'arr']) || [];
```

Would you please explain to me to understand how is this possible?

Thanks in advance.

**Comment by Showrin** [comment]
> Hi.
> I'm using `_.get` a lot in my daily works and it's a really useful tool for me. But I can't use it when I'm working with arrays!
> The default value is not working as I'm expecting.
> 
> ```js
> obj = {
> 	arr: undefined
> }
> _.get(obj, 'arr', []);
> ```
> 
> As you see I've set the default value to be `[]` if the array is not accessible. But it's returning `undefined` instead of an empty array. And I have to use this way:
> 
> ```js
> obj = {
> 	arr: undefined
> }
> _.get(obj, 'arr']) || [];
> ```
> 
> Would you please explain to me to understand how is this possible?
> 
> Thanks in advance.

@dotamir I think this isn't happening for lodash. Because, for me, it's working as expected. You can see here >>>
https://runkit.com/showrin/lodash-pr-5106

**Comment by itsdeekay** [comment]
I agree as per code too, this should be working fine. Check the version of lodash and upgrate to latest one in case there is issue with older version
