### ISSUE TITLE
Where is lodash.js file

### ISSUE THREAD

**Issue by Wadprog** [lodash/lodash#5111]
The package.Json file has a property main set to lodash.js but apparently the file does not exist

**Comment by sanketshah19** [comment]
@Wadprog You can find it here -
[https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/dist/lodash.js](https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/dist/lodash.js)

**Comment by Wadprog** [comment]
Thank you for your help
