### ISSUE TITLE
Unexpected behavior by isEqual when comparing objects with undefined values

### ISSUE THREAD

**Issue by bhushan-shah-dev** [lodash/lodash#5114]
I observed some strange behavior with `isEqual`, and I'd like to clarify if this is the intended functionality or is it a bug.

Consider the following snippet:

```javascript
const _ = require('lodash');

console.log('{} === {} evaluates to', {} === {});
console.log('{} === {key: undefined} evaluates to', {} === {key: undefined});
console.log('_.isEqual({}, {}) evaluates to', _.isEqual({}, {}));
console.log('_.isEqual({}, {key: undefined}) evaluates to', _.isEqual({}, {key: undefined}));
```

The output is

```
{} === {} evaluates to false
{} === {key: undefined} evaluates to false
_.isEqual({}, {}) evaluates to true       
_.isEqual({}, {key: undefined}) evaluates to false
```

I would have expected that `isEqual` would either emulate the same functionality as `===` when comparing simple objects with no nesting, or it would emulate comparing the serialized representation of the arguments.

However, when comparing `{}` and `{}`, `isEqual` behaves like comparing the serialized representation of `{}` and `{}` (since `JSON.stringify()` would return the same string for both), but when comparing `{}` and `{key: undefined}`, this is not true (since `JSON.stringify()` would return the same string for both in this case as well), and it behaves like `===` instead.

Is this strange behavior expected? Is it documented somewhere?

**Comment by bhushan-shah-dev** [comment]
In that case, shouldn't `_.isEqual({}, {key: undefined})` evaluate to `true`? Since the value of key `key` is `undefined` in both cases, and both serialize to `"{}"`.

**Comment by itsdeekay** [comment]
@bhushan-shah-dev It does not serialize. There are lot of checks to compare the objects. Here in your case `{key: undefined}`  will result in object which has one element with key as key and value undefined. When isEqual do comparison it extract the keys of both objects and compare the length of key array and return false if do not match.
