### ISSUE TITLE
use subtract 

### ISSUE THREAD

**Issue by weiyunpeng** [lodash/lodash#5120]
use subtract and results in errors, which can be noticeable when subtracting two floating-point numbers。
eg:
```js
_.subtract(10.20, 10.00)
0.1999999999999993
```

**Comment by raguljr** [comment]
@weiyunpeng This is not a problem related to lodash. If you try `10.20 - 10.00` in a browser console, you will get the same result `0.1999999999999993`.
Javascript is based on [IEEE Standard for Floating-Point Arithmetic (IEEE 754)](https://en.wikipedia.org/wiki/IEEE_754) and that is [how it works](https://stackoverflow.com/questions/588004/is-floating-point-math-broken).
