### ISSUE TITLE
Where is the curry.js file?

### ISSUE THREAD

**Issue by Z1hgq** [lodash/lodash#5123]

**Comment by umair-outlier** [comment]
https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L10198

**Comment by umair-outlier** [comment]
https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L10198

**Comment by umairx97** [comment]
https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L10198

**Comment by Z1hgq** [comment]
> https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L10198

thx
