### ISSUE TITLE
Question: Does it exist in the function corresponding to `toPath`?

### ISSUE THREAD

**Issue by LeiHanCN** [lodash/lodash#5124]
such as:

```js
_.fromPath(['a', '0', 'b', 'c'])
// 'a[0].b.c'

_.fromPath(['a', 'b', 'c'])
// 'a.b.c'

```

**Comment by nam288** [comment]
It does not exist. Let's create it:
```js
const isNumericString = (s) => !_.isNaN(_.toNumber(s))

const fromPath = (a) => a.reduce((r, e) => r + (isNumericString(e) ? `[${e}]` : '.' + e))

console.log(fromPath(['a', '0', 'b', 'c']))
// output: a[0].b.c
```

**Comment by wallace-sf** [comment]
> It does not exist. Let's create it:
> 
> ```js
> const isNumericString = (s) => !_.isNaN(_.toNumber(s))
> 
> const fromPath = (a) => a.reduce((r, e) => r + (isNumericString(e) ? `[${e}]` : '.' + e))
> 
> console.log(fromPath(['a', '0', 'b', 'c']))
> // output: a[0].b.c
> ```

You have to keep it safe when starts with number. In this case, would probably crash. For example:

```js
console.log(fromPath(['a', '1a', 'b', 'c']))
```
