### ISSUE TITLE
Question: Is there anyway to sort an array object except few 

### ISSUE THREAD

**Issue by rohitkr0807** [lodash/lodash#5127]
let users = [
  { username: "zebra"},
  { username: "hello"},
  { username: "taco"},
  { username: "ignu"},
  { username: "cric"},
  { username: "ind"},
  { username: "peco"},
  { username: "nice"},
];

// I want all users to be sorted except ind and hello, which comes on top and others are sorted alphabetacally, so my output will be

let users = [
  { username: "ind"},
  { username: "hello"},
  { username: "cric"},
  { username: "ignu"},
  { username: "nice"},
  { username: "peco"},
  { username: "taco"},
  { username: "zebra"},
];

**Comment by nam288** [comment]
The easiest way is to eliminate the top elements then unshift them after sorting. Like:
```js
function sortByWithException(collection, isSortable, orderBy) {
    const unsortableElements = lodash.reject(collection, isSortable)
    const sortableElements = lodash.filter(collection, isSortable)

    return [...unsortableElements, ...lodash.sortBy(sortableElements, orderBy)]
}

console.log(
    sortByWithException(
        users,
        (user) => user.username !== 'ind' && user.username !== 'hello',
        (user) => user.username
    )
)

//   output:
//   [ { username: 'hello' },
//   { username: 'ind' },
//   { username: 'cric' },
//   { username: 'ignu' },
//   { username: 'nice' },
//   { username: 'peco' },
//   { username: 'taco' },
//   { username: 'zebra' } ]
```
