### ISSUE TITLE
CSV to array function

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [lodash/lodash#5130]
We use Lodash for our project [appsmith](https://github.com/appsmithorg/appsmith) a lot and our users would love a way to convert CSV files that they upload to an array of objects that their backends accept. A snippet like this would work great and I'd be happy to raise a PR for the same!
```
function csvToArr(csvText) {
	const csvRows = csvText.split("\n");
	const objArr = [];
	const headers = csvRows[0].split(',');
		for(let i = 1; i < csvRows.length; i++) {
			const rowObj = {};
			objArr.push(rowObj);
			const rowArr = csvRows[i].split(',');
			rowArr.forEach((val, index) => {
				rowObj[headers[index]] = val;
			});
		}
	return objArr;
}()
```

**Comment by faebzz** [comment]
I would love to see a function like this. I would recommend to expand the function with additional two parameters.
`function textToArray(csvData, delimiter=',', hasHeader='false')`
to define the keys in the object array with a header and change the delimiter if necessary.

**Comment by bnjmnt4n** [comment]
In general, code which accurately parses CSV can get much more complicated than the code provided here, so we'd rather defer to specialized libraries which can handle all edge cases correctly, rather than adding this as a lodash function.
