### ISSUE TITLE
isEmpty(new Date) returns true instead of false

### ISSUE THREAD

**Issue by dellyoung** [lodash/lodash#5131]
`_.isEmpty(new Date)`

Actual returns:

`true`

Expected:

`false`

**Comment by dellyoung** [comment]
PR: [https://github.com/lodash/lodash/pull/5132]('https://github.com/lodash/lodash/pull/5132')

**Comment by dellyoung** [comment]
[PR]('https://github.com/lodash/lodash/pull/5132')

**Comment by Tracer1337** [comment]
Why do you expect ``false`` here? I would consider an empty ``Date`` object as an object without a timestamp, but that does not exist (as far as I know).

**Comment by graup** [comment]
According to the documentation, "objects are considered empty if they have no own enumerable string keyed properties." Thus IMO `true` is the expected value for `isEmpty(new Date)` as a date is an object with no own properties.

**Comment by Tracer1337** [comment]
Considering the ``Object.getOwnPropertyNames`` methods, all ``Date`` objects are empty 
```bash
> Object.getOwnPropertyNames(new Date)
[]
> Object.getOwnPropertyNames(new Date())
[]
> Object.getOwnPropertyNames(new Date("01.01.2021"))
[]
```
That is also counterintuitive.

**Comment by jdalton** [comment]
> According to the documentation, "objects are considered empty if they have no own enumerable string keyed properties." Thus IMO `true` is the expected value for `isEmpty(new Date)` as a date is an object with no own properties.

Yes. This method name has always carried with it some confusion. Instead of tweaking the method I think we should rename it. I'm open to PRs for that :)

**Comment by dellyoung** [comment]
> > According to the documentation, "objects are considered empty if they have no own enumerable string keyed properties." Thus IMO `true` is the expected value for `isEmpty(new Date)` as a date is an object with no own properties.
> 
> Yes. This method name has always carried with it some confusion. Instead of tweaking the method I think we should rename it. I'm open to PRs for that :)

Thank you, I was misunderstood by the name, I think it's really necessary to change a clear name.
