### ISSUE TITLE
sortBy method In the example, the return value of this method is wrong

### ISSUE THREAD

**Issue by Quanzhitong** [lodash/lodash#5133]
This is the example in Official document
![image](https://user-images.githubusercontent.com/41983846/113870243-360b9b00-97e4-11eb-84b2-f4906b46a45d.png)

This is the result that chrome console output
![image](https://user-images.githubusercontent.com/41983846/113870703-b29e7980-97e4-11eb-9464-7f2c6048df7f.png)

 Each element of the return value should be object instead of array

**Comment by Calamari** [comment]
I am not a maintainer or did not write that example, but the comment states `// => objects for` which hints to which objects are returned and in which order, it does not say that this is the exact result.
