### ISSUE TITLE
debounce().pending() not part of last release

### ISSUE THREAD

**Issue by wohlben** [lodash/lodash#5146]
Hey,
there is a debounced.pending() check if i look in the [master branch](https://github.com/lodash/lodash/blame/2f79053d7bc7c9c9561a30dda202b3dcd2b72b90/debounce.js#L209), which has been [merged back in 2017](https://github.com/lodash/lodash/pull/3388).

Nonetheless, the simple pending check is not in the [last released lodash version](https://github.com/lodash/lodash/blob/4.17/lodash.js#L10372).

Is this on purpose? I've been unable to figure out what happened there.

**Comment by wohlben** [comment]
i see, its only gonna be available in lodash 5.
sorry for opening this ticket

**Comment by Slapbox** [comment]
Is there some ETA for Lodash 5?

**Comment by DanielStout5** [comment]
Any update on this? That pending() function would be useful..
