### ISSUE TITLE
Prototype Pollution

### ISSUE THREAD

**Issue by ivnavalenca** [lodash/lodash#5147]
<img width="631" alt="Screen Shot 2021-04-23 at 07 05 51" src="https://user-images.githubusercontent.com/6989733/115856454-e42d5c80-a402-11eb-8ae2-b17d5eb387c3.png">

**Comment by pietro909** [comment]
Is this still relevant? On Snyk's website says [versions <4.17.16](https://snyk.io/vuln/SNYK-JS-LODASH-567746) whereas Lodash is currently at 4.17.21
