### ISSUE TITLE
_.assign with const value doesn't return an error.

### ISSUE THREAD

**Issue by ronycohen** [lodash/lodash#5148]
Hello, 

I found a bug : 

`_.assign(const_value, let_value)` does not return an error. 

The const_value is immutable and cannot be set.
We don't get any errors and I think we should.

Best regards,

**Comment by onwd** [comment]
@ronycohen 

In JavaScript you can mutate objects freely, regardless of whether it was defined with `let` or `const`. Even if you consider the following native code, it will work:

```js
const value = {};

value.test = 123; // will not throw

console.log(value); // -> { "test": 123 }
```

However, you can't re-assign variables declared with `const`:

```js
const value = {};

value = { test: 123 }; // will throw TypeError due to invalid assignment
```

What **[_.assign](https://lodash.com/docs/4.17.15#assign)** does is – it basically copies all enumerable properties from the source object into the destination object. It only mutates the object, and doesn't re-assign it (actually you can't even build a function that can re-assign outer variables in JS). Thus, it won't throw any errors.
