### ISSUE TITLE
_.includes('/a/b/c', '/a') return  false

### ISSUE THREAD

**Issue by pengmoumou** [lodash/lodash#5151]
version:
    "lodash": "^4.17.15",
     "react": "^17.0.2",

`_.includes('/a/b/c', '/a')`
`// => false`

**Comment by krishna63** [comment]
@pengmoumou: I have tried to replicate the issue by using the loadash CDN url. But i could not get it, meaning it is returning true.
Could you shed more light on how to replicate it. Attaching the example which i have used for replicating the issue.


![image](https://user-images.githubusercontent.com/5499820/117146482-dfd54c00-add1-11eb-9d70-16a12a1e9556.png)

```html
<!DOCTYPE HTML>
<html>
<body>
<h5>Includes method replication</h5>
<p>Loadash is loaded using CDN url to replicate the issue. I have used <em>"4.7.15"</em> version of Loadash module</p>

<p>Check out the output in console</p>
<code>
console.log('Loadash version  ==> ',_.VERSION);
<br/>
console.log(`_.includes('/a/b/c', '/a') ==> `, _.includes('/a/b/c', '/a'));
</code>
<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js"></script>
<script>

console.log('Loadash version  ==> ',_.VERSION);
console.log(`_.includes('/a/b/c', '/a') ==> `, _.includes('/a/b/c', '/a'));
		
			
			
</script>
</body>
</html>
```

**Comment by pengmoumou** [comment]
@krishna63 
I created a new project to replicate the issue ,I found that the reason is that  I use "lodash-webpack-plugin" to Implement on-demand loading of lodash.

the example [Click Here](https://github.com/pengmoumou/lodash-demo)

When I remove lodash in .babelrc, return true

```
_.includes('/a/b/c', '/a')
// => true
```

**Comment by pengmoumou** [comment]
I add some options to fix it,and refer to [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin#usage)
```
new LodashModuleReplacementPlugin({
  'collections': true,
  'paths': true
});
```

**Comment by benharvie** [comment]
.
