### ISSUE TITLE
Syntax highlighting not working on documentation site

### ISSUE THREAD

**Issue by LandonSchropp** [lodash/lodash#5154]
The syntax highlighting seems to be broken on the documentation site.

<img width="726" alt="Screen Shot 2021-05-05 at 2 08 40 PM" src="https://user-images.githubusercontent.com/361591/117195921-7d695500-adab-11eb-8b7c-ed9b460cad15.png">

I'm using the latest version of Chrome on the latest macOS.

**Comment by LandonSchropp** [comment]
@jdalton Would you mind taking a look at this one? It makes using the docs a little difficult.

**Comment by hellmanhellman** [comment]
@jdalton Same for me. I have to use a browser extension to manually set the background color to make it readable.

**Comment by LandonSchropp** [comment]
@hellmanhellman This mysteriously started working for a couple of months ago again. I thought somebody had fixed it, but maybe it's not an issue that affects everyone. I just checked and it's still working for me.
