### ISSUE TITLE
how is the build process going?

### ISSUE THREAD

**Issue by nico1988** [lodash/lodash#5157]
I didn't found the build process on the master branch, I found the .travis file in the xxx-post or xxx-npm branch
here is my question:
- how is the building process going? from source code to npm
- why there is a lodash.js in the xxx-post branch

**Comment by mohmed1500** [comment]
> I didn't found the build process on the master branch, I found the .travis file in the xxx-post or xxx-npm branch
> here is my question:
> 
> * how is the building process going? from source code to npm
> * why there is a lodash.js in the xxx-post branch
