### ISSUE TITLE
isNaN is not providing correct results

### ISSUE THREAD

**Issue by zandrei** [lodash/lodash#5163]
The isNaN function is not consistent with the javascript isNan for strings and booleans. The following calls return incorrect results:

isNaN('abc') returns false
isNaN("abc") returns false
isNan(true) returns false

Lodash version: 4.14.168

**Comment by ygoyal25** [comment]
The isNaN function provided by lodash is not same as the global isNaN function in Javascript, rather it is an implementation of Number.isNaN. In fact, in pure javascript environment, even isNaN and Number.isNaN behave differently. Please go through the below links for a clearer understanding.

[https://stackoverflow.com/questions/33164725/confusion-between-isnan-and-number-isnan-in-javascript#:~:text=global%20isNaN%20method.-,Number.,the%20provided%20value%20equals%20NaN.&text=So%20isNaN%20just%20checks%20whether,be%20converted%20into%20a%20Number.](Stackoverflow)

[https://lodash.com/docs/4.17.15#isNaN](lodash _.isNaN)

**Comment by zandrei** [comment]
@ygoyal25 Thank you. It would be helpful if the example of lodash isNaN on their documentation page would show the expected result of isNaN on a String and/or boolean instead of "undefined" since the current example is misleading in the sense that it would highlight that the function only behaves differently in terms of how it handles an "undefined" value.
