### ISSUE TITLE
isEmpty check Date return true

### ISSUE THREAD

**Issue by hirosumee** [lodash/lodash#5167]
I have a issue when try to check whether  a variable with Date type if empty . 
This is my code: https://codepen.io/vungoccuong/pen/PopzMBv

**Comment by arash-qc** [comment]
Assholeness + stupidness are combined in lodash maintainers

_.isEmpty(2342141234) must return false

_.isNormal(@jdalton) returning false because its checking only for objects and anything else is not Normal
