### ISSUE TITLE
Huge size for the find method on Lodash

### ISSUE THREAD

**Issue by Sampath-Lokuge** [lodash/lodash#5169]
Hi,

I would like to use Lodash everywhere since it is very familiar to me and a great utility library. But my question here is will Lodash take **69.6K** of size just only for the `find` method or?

![1](https://user-images.githubusercontent.com/5206526/118818726-42e6d880-b8d2-11eb-8bec-75a6c9965175.png)

VS Code Extention Import Cost: https://github.com/wix/import-cost

According to this, it should very small these days no? https://lodash.com/per-method-packages

**Comment by Sampath-Lokuge** [comment]
Hi @jdalton Any feedback here? Thanks!

**Comment by jdalton** [comment]
You likely need to use `lodash-es`.
