### ISSUE TITLE
`get()` is not able to resolve flat keys nested inside an object

### ISSUE THREAD

**Issue by aaarichter** [lodash/lodash#5173]
version: `4.17.15`
function: `get`

Lodash `get` is great to easily access objects. It is especially useful when you use flat keys. For example
 
```json
{
  "modules.x": "foo"
}
```

`get(obj, 'modules.x')` is able to resolve the key and return `foo`

Unfortunately it fails when trying to access flat keys within a nested object
```json
{
  "js": {
    "modules.x": "foo"
  }
}
```
will return null/undefined for `get(obj, 'js.modules.x')`

**Comment by patrickmcdougle-okta** [comment]
In your opinion how should it handle this?
```
{
  "js": {
    "modules.x": "foo",
    "modules": {
      "x": "bar",
    },
  },
}
```
Is "foo" or "bar" returned in this case? Either way, one of these values is shadowed.

**Comment by aaarichter** [comment]
thanks for bringing up this ^ potential conflict @patrickmcdougle-okta  .

I raised this issue while when trying to access an object structured like in my first example, where the keys are flattened for better readability.

I took a look at the 4.x `_.get` code  and realized that it would require a lot of extra steps like recombining the casted path to achieve the requested behavior.

I settled on expanding the keys.

Should I close the issue?

**Comment by patrickmcdougle-okta** [comment]
I am not a code owner, but just a member of the community who wanted to point out the potential issue with your feature request (bug report?). If you feel like your request is no longer desired, feel free to close the issue. Your call.
