### ISSUE TITLE
pick() returns wired values if json has integer key names

### ISSUE THREAD

**Issue by saswat3115** [lodash/lodash#5176]
![image](https://user-images.githubusercontent.com/14299682/119970930-f5ebbc00-bfcd-11eb-9d3e-e44a12bab15c.png)

In above data keys are integers. Pick() returns an array with wired values

**Comment by prasadrails** [comment]
Hi @saswat3115 ,
Yes you are right, it is converting object to array un-ncessary.
var formData = {
  jsq: {
    0: "a"
  }
}
result = _.pick(formData, 'jsq.0')

following output coming:
--------------------------------
{
   "jsq": [
      "a"
   ]
}

**Comment by itsdeekay** [comment]
Hi, this behavior is due to a check that value passed is number, if yes then it is behaved as index instead of property

**Comment by lacieri** [comment]
Just had this issue and its returning an array and the length is from `0` to the integer key.
```javascript
let testObj = {a: {b: {500: {c: 'test-value'}}}}
_.pick(testObj, 'a.b.500')
```
and the length of `b` is 501

**Comment by davidduwei** [comment]
你的来信已收到！ O(∩_∩)O谢谢
