### ISSUE TITLE
loadash/fp unset returns an object

### ISSUE THREAD

**Issue by DavidHenri008** [lodash/lodash#5185]
According to the lodash unset function, it should return a boolean indicating if the delete was successful.
When I execute the loadash/fp unset function, it returns the modified object.

Did I miss a documentation info?

**Comment by mukesh210** [comment]
The first line of lodash/fp wiki page answers your  doubt:
**The lodash/fp module promotes a more functional programming (FP) friendly style by exporting an instance of lodash with its methods wrapped to produce _immutable_ auto-curried iteratee-first data-last methods.**

Immutable is  mentioned in definition itself which  means that object won't be modified. Every method returns new object with modified data.

**Comment by DavidHenri008** [comment]
@mukesh210 Yes after reading your answer it makes much sense that a new object is returned due to the immutability of the fp library.

In the case the normal lodash unset cannot delete the property it will return false. What is happening with the lodash/fp unset? It returns the original object?

Better documentation explaining the behavior of the lodash/fp library would be greatly appreciated.

**Comment by mukesh210** [comment]
yes... you are  right. Lodash/fp unset will return original object if it is not able to delete property. 
`const fp  = require('lodash/fp');

const object = { 'a': [{ 'b': { 'c': 7, 'd': 8 } }] };
const objWithDeletedProp = fp.unset('a[0].b.c', object);
const sameObj = fp.unset('a[0].b.e', object);
console.log('objWithDeletedProp:', JSON.stringify(objWithDeletedProp));   // {"a":[{"b":{"d":8}}]}
console.log('sameObj:', JSON.stringify(sameObj));                                         // {"a":[{"b":{"c":7,"d":8}}]}
`
