### ISSUE TITLE
Suggestion: comparing objects' common properties

### ISSUE THREAD

**Issue by ImRodry** [lodash/lodash#5186]
I'd like to suggest a function similar to isEqual that only compares the common properties between two objects, meaning that it wouldn't throw false for one of them having more or less properties than the other and would simply worry about checking if the properties that they have have the same values. I found a situation in my code where this would be useful and I believe other people could benefit from this too.

**Comment by porziopablo** [comment]
Hi @ImRodry, together with @mariquena we study software engineering, and we're in a course about open source software at our university. We have an assignment in which we have to make a PR for a Linux Foundation project of our choice. We decided to contribute to `lodash` as it is a library we use a lot in our part-time jobs as front-end developers.

We hope this feature satisfies your needs!

**Comment by ImRodry** [comment]
Thank you so much! Looking forward to see this pull request reviewed and accepted and I wish you the best of luck in your assignment!

**Comment by airarrazaval** [comment]
@ImRodry This is a very good idea.  I think it can be further improved by turning them into two functions:

### intersect(object, [sources])

Returns an object whose properties intersect with the sources' properties, maintaining the object's original value if an intersection happens. Returns null if no intersection is found.

**Example**

```js
const obj1 = { a: 1, b: { c: 3, d: 4 } };
const obj2 = { b: { c: 0, e: 5 } };
const obj3 = { f: 1 };

intersect(obj1, obj2);

// output
{
  b: {
    c: 3
  }
}

intersect(obj1, obj3);

// output
null
``` 

### intersectWith(object, [sources], customizer)

The same as `intersect` except that it accepts customizer which is invoked to apply additional intersection rules.

**Example**

```js
const obj1 = { a: 1, b: { c: 3, d: 4 } };
const obj2 = { b: { c: 0, e: 5 } };
const obj3 = { b: { d: 4 }, c: 3 };

function customizer(objValue, srcValue) {
  return objValue === srcValue;
}

intersectWith(obj1, obj2, customizer);

// output
null

intersectWith(obj1, obj3);

// output
{
  b: {
    d: 4
  }
}
```

This will give this function more flexibility and would allow to satisfy more complex scenarios.

**Comment by ImRodry** [comment]
@jdalton why was this closed? Where is the commit that completed this?

**Comment by anurag-roy** [comment]
@ImRodry They closed all open issues and PRs with the `issue bankruptcy` tag.

My best guess would be ([as per this comment](https://github.com/lodash/lodash/issues/5716#issuecomment-1722296694)) lodash v5 is releasing and they want to start with a clean slate?

**Comment by ImRodry** [comment]
That’s just stupid lol but alright, thanks

**Comment by jdalton** [comment]
Issue bankruptcy. Working on v5 with fresh eyes after a few years.

**Comment by ImRodry** [comment]
Alright. I hope this is still considered though and I’d also like to see the codebase updated to today’s standards
