### ISSUE TITLE
Can't find the source file of _.isNaN?

### ISSUE THREAD

**Issue by baiziyu-fe** [lodash/lodash#5191]
https://github.com/lodash/lodash/blob/2f79053d7bc7c9c9561a30dda202b3dcd2b72b90/test/isNaN.js#L4

The "`../isNaN.js`" introduced here does not exist, is there a wrong reference or the file is not uploaded?

**Comment by binvb** [comment]
seems it dosn't run, only test suffix .test.js, 
```
"test": "mocha -r esm test/*.test.js",
```

**Comment by baiziyu-fe** [comment]
This code is only in the packaged file
