### ISSUE TITLE
Why is lodash a dependency of itself?

### ISSUE THREAD

**Issue by rushatgabhane** [lodash/lodash#5197]
Current version 5.0.0
https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/package.json#L20

Why use older version of itself as a dependency?

**Comment by binvb** [comment]
i saw many requires in test case:  
```
import lodashStable from 'lodash';
```
sometimes need lodash method in test case, it dosn' matter
