### ISSUE TITLE
Flatten returns undefined for values of int 0 

### ISSUE THREAD

**Issue by MenachemICTBIT** [lodash/lodash#5205]
If running `flatten()` on an array with zeros, it will return undefined instead of the original value. 

Example: 
```
let example = [0, 1, 2, [0, 3, 4];
example = _.flatten(example);
// example = [undefined, 1, 2, undefined, 3, 4];
```

How can I avoid this?

**Comment by bnjmnt4n** [comment]
This doesn't seem to occur. Can you create a reproduction?
