### ISSUE TITLE
Download 4.17.21 lodash.js file

### ISSUE THREAD

**Issue by ahmadhajali** [lodash/lodash#5209]
Hi,

I'm looking for lodash.js version 4.17.21 but I found that the latest available version is 4.17.15 here: https://lodash.com/ --> Full build.
Where can I find generated full build lodash.js for version 4.17.21?

Best regards,
Ahmad

**Comment by dosullivan557** [comment]
Hi @ahmadhajali - is this what you are looking for 


https://github.com/lodash/lodash/releases/tag/4.17.21

**Comment by ahmadhajali** [comment]
Hi @dosullivan557 - I found the link. This is the link: 
https://raw.githubusercontent.com/lodash/lodash/4.17.21-npm/lodash.js

**Comment by ahmadhajali** [comment]
Thanks a lot
