### ISSUE TITLE
.internal cloneBuffer first condition maybe wrong

### ISSUE THREAD

**Issue by AlexErnsberger** [lodash/lodash#5212]
i think isDeep should be !isDeep

buffer.slice()  is shallow copy

**Comment by rluvaton** [comment]
It is wrong, but I don't think this library is maintained anymore

**Comment by FeliciaAKelley** [comment]
thanks yup well no code should be used on a networks data points or it will always error or 403

**Comment by FeliciaAKelley** [comment]
404 i meant ..sorry

**Comment by rluvaton** [comment]
> thanks yup well no code should be used on a networks data points or it will always error or 403

What?
