### ISSUE TITLE
_.toBoolean() (I know, but...)

### ISSUE THREAD

**Issue by arash-bizcover** [lodash/lodash#5214]
Hi, What is the reason *lodash* should not have `_.toBoolean()` function built-in same as other great Lang conversions:
![image](https://user-images.githubusercontent.com/62287461/125297597-b523e880-e36a-11eb-84cd-85f6b2955550.png)

I know we can have our own `mixin` wrapper and make it work, just curious why not implemented by default as it is very common.

Specifcally I was trying to get "false" to be converted to **false**, ( _my use case was a variable being populated from process.env which is always string_)

**Comment by itsdeekay** [comment]
Hi @jashkenas Can we add this new function into library to convert String/integer to boolean?

**Comment by binvb** [comment]
> Hi @jashkenas Can we add this new function into library to convert String/integer to boolean?

how if make an extend api, people can just push their custom function, e.g.
```
import { myCustomFn } from 'lodash/custom/myCustomFn'
import _ from loash

_.extend(myCustomFn)
```

**Comment by itsdeekay** [comment]
Then we can also use other libraries for this purpose.
