### ISSUE TITLE
feat: `superReplace`  

### ISSUE THREAD

**Issue by mam-nh** [lodash/lodash#5215]
get two values, if property present replaces else merge. I created this custom replace function to update the cache with existing cache data and updated data. 

```js 
const a = {
  name: 'John Doe',
  email: 'john@mail.com',
  location: {
    country: {
      name: 'Japan',
      abbr: 'JP',
    },
    place: 'Tokyo',
  },
  phone: [123, 456],
  age: new Date('2021-05-15T15:28:37.453Z'),
};

const b = {
  email: 'johndoe@mail.com',
  location: {
    country: {
      name: 'Canada',
      abbr: 'CA',
    },
  },
  phone: [123],
  age: new Date('2001-08-15T15:28:37.453Z'),
};

const superReplace = (object, value) => {
  let replace = {};

  Object.keys(object).forEach(prop => {
    if (value[prop] !== undefined) {
      if (Array.isArray(object[prop])) replace[prop] = value[prop];
      else if (value[prop] instanceof Date) {
        replace[prop] = value[prop];
      } else if (typeof object[prop] === 'object' && object[prop] !== null) {
        replace[prop] = superReplace(object[prop], value[prop]);
      } else replace[prop] = value[prop];
    } else replace[prop] = object[prop];
  });

  return replace;
};

console.log(superReplace(a, b));
// {
//   name: 'John Doe',
//   email: 'johndoe@mail.com',
//   location: { country: { name: 'Canada', abbr: 'CA' }, place: 'Tokyo' },
//   phone: [ 123 ],
//   age: 2001-08-15T15:28:37.453Z
// }
```

**Comment by itsdeekay** [comment]
You could reduce some codes as there are conditions which doing same tasks. So you could combine it.
```
const superReplace = (object, value) => {
  let replace = {};

  Object.keys(object).forEach((prop) => {
    if (value[prop] !== undefined) {
       if (typeof object[prop] === 'object') {
        replace[prop] = superReplace(object[prop], value[prop]);
      } else replace[prop] = value[prop];
    } else replace[prop] = object[prop];
  });

  return replace;
};
```

**Comment by usama-asfar** [comment]
> You could reduce some codes as there are conditions which doing same tasks. So you could combine it.
> 
> ```
> const superReplace = (object, value) => {
>   let replace = {};
> 
>   Object.keys(object).forEach((prop) => {
>     if (value[prop] !== undefined) {
>        if (typeof object[prop] === 'object') {
>         replace[prop] = superReplace(object[prop], value[prop]);
>       } else replace[prop] = value[prop];
>     } else replace[prop] = object[prop];
>   });
> 
>   return replace;
> };
> ```

Thanks @itsdeekay 

We need to explicitly check the type of Array and Date Because Array and Date are `object` in JavaScript
```shell
> typeof []
'object'
> typeof new Date()
'object'
```

**Comment by binvb** [comment]
+1

**Comment by itsdeekay** [comment]
Got your point then the easy way to capture object is using `obj.constructor.name` which gives different values for different types of objects unless you create `constructor` method to create objects in that case it would return the constructor name.

**Comment by airarrazaval** [comment]
The "logical" approach would be to use `defaultsDeep` or `merge` but if the destination object (in this case `a`) contains an array in which `b` is missing some of its values, then the array gets concatenated.

### defaultsDeep

```js
_.defaultsDeep(b, a);

// {
//   name: 'John Doe',
//   email: 'johndoe@mail.com',
//   location: { country: { name: 'Canada', abbr: 'CA' }, place: 'Tokyo' },
//   phone: [ 123, 456 ],
//   age: 2001-08-15T15:28:37.453Z
// }
```

### merge

```js
_.merge(a, b);

// {
//   name: 'John Doe',
//   email: 'johndoe@mail.com',
//   location: { country: { name: 'Canada', abbr: 'CA' }, place: 'Tokyo' },
//   phone: [ 123, 456 ],
//   age: 2001-08-15T15:28:37.453Z
// }
```

This issue can be easily fixed using `mergeWith` and using a customizer to prevent this issue from happening:

```js
function customizer(objValue, srcValue) {
  if (Array.isArray(srcValue)) {
    return srcValue;
  }
}

_.mergeWith(a, b, customizer);

// {
//   name: 'John Doe',
//   email: 'johndoe@mail.com',
//   location: { country: { name: 'Canada', abbr: 'CA' }, place: 'Tokyo' },
//   phone: [ 123 ],
//   age: 2001-08-15T15:28:37.453Z
// }
```
