### ISSUE TITLE
_.isNumber(NaN) returns true

### ISSUE THREAD

**Issue by stanley85** [lodash/lodash#5216]
I use _.isNumber(parseFloat('some text var here')) to check if the text results in a number.
The result of parseFloat on text returns NaN which should not be a number, but isNumber returns true. My workaround on this is to check both like this:
```
isNumber (value) {
  return !_.isNaN(parseFloat(value)) && _.isNumber(parseFloat(value));
}
```
But i gues NaN should never be considered a number - or am i wrong and there is reason to do so?

**Comment by tarikjabiri** [comment]
Hi,

`NaN` is considred a number because the `typeof NaN `returns `'number'`
So it is normal for _isNumber(NaN) to return true because under the hood it uses `typeof`.

regards

**Comment by aswinkumar863** [comment]
You can use [`_.isFinite()`](https://lodash.com/docs/4.17.15#isFinite) instead
