### ISSUE TITLE
Lodash typescript _.map doesn't check if iteratee is an array property

### ISSUE THREAD

**Issue by Secretmapper** [lodash/lodash#5218]
https://codesandbox.io/s/trusting-bardeen-wd3lr?file=/src/index.ts

Consider:

```ts
import _ from 'lodash'

const arr = [{ID: 0}, {ID: 1}]

console.log(_.map(arr, 'ID'))
console.log(_.map(arr, 'id'))
```

The first console.log is valid, however, the second console.log does not error out even though `id` is not a property of the array.

Is this impossible to support in lodash due to how much logic is in `lodash.map`?

This was a concern for me because Ramda, which I was aiming to replace properly errors out:

```ts
import { pluck } from 'ramda'

const arr = [{ID: 0}, {ID: 1}]

console.log(pluck('ID', arr))
console.log(pluck('id', arr)) // errors out
```

**Comment by Nicoowr** [comment]
+1 for this 

The doc specifies you can use a property to replace the callback but Typescript does not throw a type error if the property does not exist, which can be dangerous.
<img width="414" alt="Screenshot 2022-04-06 at 11 59 33" src="https://user-images.githubusercontent.com/28652231/161950199-fb007e21-27ef-47b0-81a5-e78ac507781b.png">

**Comment by saadismail** [comment]
+1, ideally we should have a compile-error in this case.

**Comment by anurag-roy** [comment]
Not only `_.map`, but most of the other functions like `_.orderBy`, `_.groupBy`, etc. have this issue 😞
