### ISSUE TITLE
memoize in 4.7.21 build is 3 years out of date

### ISSUE THREAD

**Issue by issacgerges** [lodash/lodash#5219]
I was doing some performance profiling and noticed `memoize` was using a custom `Map` wrapper named `MapCache`. 

After looking through the source it seems that was removed [nearly 3 years](https://github.com/lodash/lodash/commit/508d46a7a4e448ed576cc268556d6bd10b1b994f) ago by @-jdalton.  That said it still appears in the [4.7.21-es build](https://github.com/lodash/lodash/blob/4.17.21-es/memoize.js#L71) (and in the normal [4.7.21 build](https://github.com/lodash/lodash/blob/4.17.21/dist/lodash.js#L10629)) Unsure how widespread this is but it definitely left me scratching my head

In the immortal words of Doc Brown
> Great Scott!

**Comment by issacgerges** [comment]
I think I may see what's going on. It appears `master` is a long lived branch for v5 while the -post branches are where development for the next minor version is made. Still a bit suspicious since that change was made so long ago so will leave this ticket open.

**Comment by rogerleung0411** [comment]
Another year gone. Sorry to bother you but, any progress on this issue ? @jdalton

**Comment by issacgerges** [comment]
I was actually under the impression I closed this one. It was a misunderstanding on my part about the state of `master` and isn't a real issue.

I think @jdalton has had some communication more recently about the possible release of v5. The basic version seems to be a desire to release v5, a want for more fundamental change, complicated by a mix of a lack of time and it not being a priority.

https://twitter.com/jdalton/status/1482210925511774208
https://github.com/lodash/lodash/issues/5486#issuecomment-1195843898
https://twitter.com/jdalton/status/1571863497969119238

**Comment by 1solation** [comment]
another year gone, is there any updates
