### ISSUE TITLE
why lodash slice method need to treat array as dense ? What are the benefits？

### ISSUE THREAD

**Issue by Luobinf** [lodash/lodash#5222]
thanks

**Comment by YuanRuQian** [comment]
My guess is that it's about the `Array.prototype[@@iterator]()`

```typescript

const sparse = [1,,,]

const dense = Array(3).fill(undefined)

const arrayIterator = (arr: any[]) => arr.forEach((el, index) => console.log(`arr[${index}]: ${el}`))

arrayIterator(sparse)
// [LOG]: "arr[0]: 1" 

console.log(sparse.length)
// [LOG]: 3 

arrayIterator(dense)
// [LOG]: "arr[0]: undefined" 
// [LOG]: "arr[1]: undefined" 
// [LOG]: "arr[2]: undefined" 


console.log(dense.length)
// [LOG]: 3 

console.log(sparse.slice(0,2))
// [1, empty]
_.slice(sparse, 0, 2)
// [1,null]
```

As the example above suggests, the "empty holes" in sparse arrays will be skipped in array iterators, which could sometimes lead to confusing behaviors. The length of the `sparse` is 3, yet if we `forEach` `console.log` it, only the first element will be logged into the console. 

Maybe treating arrays as dense arrays could reduce this kind of confusion?

Well, this is just my personal thought. I wish we could hear why it is designed this way from the authors ╭(′▽`)╯
