### ISSUE TITLE
Unexpected _.setWith behavior

### ISSUE THREAD

**Issue by HammurabisCoder** [lodash/lodash#5227]
I'm not sure if this is an issue with the actual `setWith` behavior and/or the "Try in REPL" feature in the [setWith documentation](https://lodash.com/docs/4.17.15#setWith), but it is at least inconsistent from my tests using this snippet:
```
let testo = {'foo':'bar'};
_.setWith(testo, 'foo.newkey', 'NEW STRING', Object);
```

On the lodash docs site, I get `TypeError: Cannot convert a Symbol value to a number`, however testing locally and on some codepens I found, there is no error and it simply does not set any value. (`testo` remains `{"foo":"bar"}`).

I was testing on lodash 4.17.15 and node 16.6.1 to match the docs versions, though I also tested on the latest lodash (4.17.21) and it didn't seem any different.

Personally, I expected this to result in the following, but I could simply be misunderstanding how the `Object` customizer works:
```
{
   "foo": {
      "newkey": "NEW STRING"
   }
}
```

**Comment by YuanRuQian** [comment]
According to [#3211](https://github.com/lodash/lodash/issues/3211)

The lodash team will stop removing umlaut characters in lodash v5 yet the latest version is still [4.17.21](https://github.com/lodash/lodash/releases/tag/4.17.21).

So you might need to write your own `lowerCase` function, at least for now ...

**Comment by Shayan-P** [comment]
I guess by using `_.set` your problem will be resolved. (or by omitting Object: `_.setWith(testo, 'foo.newkey', 'NEW STRING', Object);` )
