### ISSUE TITLE
lodash.omit paths issue

### ISSUE THREAD

**Issue by abezdina** [lodash/lodash#5231]
I am trying to use `lodash.omit` version `4.5.0` with `paths` param to get the partial copy of my initial object, but instead `omit` returns the initial object

```
const state = {
  outerObject: {
    innerObject1: {},
    innerObject2: {},
  },
};
const result1 = omit(state, ["outerObject.innerObject1"]);
console.log(result1); // { outerObject: { innerObject1: {}, innerObject2: {} } }
```

`omit` function from `lodash` version `4.17.21` works correct
I created an example [project](https://github.com/abezdina/lodash-omit-path-issue) to illustrate my issue

**Comment by akashshyamdev** [comment]
Hey,

How are you using version `4.5.0`? The latest (official) version on NPM is `4.17.21`.
![Screenshot 2021-08-31 at 15 30 07](https://user-images.githubusercontent.com/56759828/131483129-bbf1dbc5-0b49-4eb9-89f7-6dc99500fecd.png)

**Comment by dinataranis** [comment]
Hi @akashshyamdev 
I am using a [lodash.omit](https://www.npmjs.com/package/lodash.omit) module not the [lodash](https://www.npmjs.com/package/lodash) library

**Comment by Prusdrum** [comment]
@abezdina, I confirm I experienced the same with exactly the same packages' versions
