### ISSUE TITLE
Need help a UI change from button being clicked with debounce

### ISSUE THREAD

**Issue by sharpk1** [lodash/lodash#5239]
Hey all, I placed this issue in [StackOverflow ](https://stackoverflow.com/questions/68865464/how-do-i-correctly-mock-a-debounce-event-when-unit-testing-ui-in-jest/68865684#68865684) as well. I am wondering what is the best way to simulate how to pass time when unit testing with debounce? I've tried a number of tests using `sinon` and `jest`. Lodash debounce doesn't seem to be affected by `jest.runTimersToTime` or `jest.clearAllTimers`. Any help or insight would be greatly appreciated!

**Comment by geeksilva97** [comment]
Same issue here using Vue
