### ISSUE TITLE
Lodash merge including undefined values

### ISSUE THREAD

**Issue by liangyuqi** [lodash/lodash#5242]
I'm trying to use Lodash to merge object A into object B, but the trouble I am having is that object A has some undefined values and I want these to be copied over to object B.

Lodash docs for _.merge() says:

 "Recursively merges own enumerable properties of the source object(s), that don't resolve to undefined into the destination object."

Is there another function that can do this, or can it be easily overwritten?

Sample input:

```
A = {
  name: "Bob Smith",
  job: "Racing Driver",
  address: undefined
}

B = {
  name: "Bob Smith",
  job: "Web Developer",
  address: "1 Regent Street, London",
  phone: "0800 800 80"
}
```
Expected Output

```
B = {
  name: "Bob Smith",
  job: "Racing Driver",
  address: undefined,
  phone: "0800 800 80"
}
```

ps:
1.  it needs to be a "deep" merge. object may contain nested objects. so assign/extend doesn't work
2. null and undefined are not the same thing ， so i cant replace undefined with null instead.

**Comment by YuanRuQian** [comment]
I don't think there is a way to achieve this using lodash... 

Cuz `merge` and `mergeWith` all fallback to the default merging behavior when you return a `undefined`

`merge`:
> Source properties that resolve to undefined are skipped if a destination value exists

`mergeWith`:
> This method is like _.merge except that it accepts customizer which is invoked to produce the merged values of the destination and source properties. If customizer returns undefined, merging is handled by the method instead. The customizer is invoked with six arguments:
(objValue, srcValue, key, object, source, stack).

Maybe you can write your own deep merge function here

For example:

```javascript
const merge = (target, source) => {
  Object.keys(source).forEach(key => {
    if (_.isObject(source[key]))
      Object.assign(source[key], merge(target[key], source[key]))
  })
  Object.assign(target || {}, source)
  return target
}

const B = {
  name: 'Bob Smith',
  job: 'Web Developer',
  address: '1 Regent Street, London',
  phone: '0800 800 80',
}

const A = {
  name: 'Bob Smith',
  job: 'Racing Driver',
  address: undefined,
  obj: B,
}

console.log(merge(B, A))

{/* <ref *1> {
  name: 'Bob Smith',
  job: 'Racing Driver',
  address: undefined,
  phone: '0800 800 80',
  obj: [Circular *1]
} */}
```

**Comment by bombillazo** [comment]
I wish lodash could add an option to allow undefined values to be passed to the source object... so many common reasons this is needed.

**Comment by SidIcarus** [comment]
This seems to work?

```js
_.mergeWith(this, state, (objValue, srcValue, key, obj) => {
  if (objValue !== srcValue && typeof srcValue === 'undefined') {
    obj[key] = srcValue
  }
})
```
