### ISSUE TITLE
Issue with formatting output when using .fixed in lodash compare output

### ISSUE THREAD

**Issue by MarkPhsd** [lodash/lodash#5257]
I'm using angular 12.

I don't know if there is a way to use a built in lodash PIPE instead of fixed(2) to get a currency. So the best I have found is using fixed(2). But then lodash adds <tt> tags around the interpolated results.  

In the attached image you can see that the HTML result is styled. When I added the fixed(2) - So that I could make sure a number has a currency like format, we see the html formating changed. And investigating the output of lodash shows that lodash adds <tt> tags around the result of the value.

![lodash](https://user-images.githubusercontent.com/16409596/133741736-ebc8856e-a40c-46fd-8fcd-a07fe9fb44fa.png)

**Comment by aadeeshpatni** [comment]
the `fixed()` method itself returns a string embedded in the <tt> tag.
See this : [](https://www.w3schools.com/jsref/jsref_fixed.asp)
