### ISSUE TITLE
Merge mutates source object if nested property is a class instance

### ISSUE THREAD

**Issue by belspirit** [lodash/lodash#5269]
If property of the source objects is created from a class, it will be mutated. But the documentation says that source objects are not mutable.

```
import { merge } from "lodash"

class someClass {
  aa = 0
}

const src1 = { pg: { a: new someClass() } }
const src2 = { pg: { a: { aa: 2 } } }

console.log(JSON.stringify(src1))
console.log(JSON.stringify(src2))

const dest = merge({}, src1, src2)

console.log(JSON.stringify(src1))
console.log(JSON.stringify(src2))
```

Logs:
```
{"pg":{"a":{"aa":0}}} // src1
{"pg":{"a":{"aa":2}}} // src2
{"pg":{"a":{"aa":2}}} // src1 -> expected aa: 0
{"pg":{"a":{"aa":2}}} // src2
```

**Comment by halan** [comment]
I'm investigating that with @iamnoah.

**Comment by halan** [comment]
I'm investigating that with @iagodahlem

**Comment by kokushkin** [comment]
I've encountered the same behavior with "omit"

`
import _ from "lodash";

class A {
  constructor() {
  this.b = "asdasd";
  this.c = "asdfasdas";
  }
}

const obj = {
  a: new A()
};

const obj1 = _.omit(obj, ["a.c"]);
console.log(obj);

`

![1tl04wt2.png](https://user-images.githubusercontent.com/9853656/169505638-fd852a1a-f693-4a13-854b-43604b274d7b.png)

https://codesandbox.io/s/eager-mendel-kw5jlk?file=/src/index.js:23-215

**Comment by kokushkin** [comment]
My use case was to hide session data before logging it

`
const cleanedConfig = _(config).omit(["httpsAgent._sessionCache"])

`

It was super unclear what's going on cause all what I've seen were these messages.. sometimes..

`
TypeError: Cannot read properties of undefined (reading 'list')
  at Agent._evictSession (node:https:**:**)
  at TLSSocket.<anonymous> (node:https:**:**)
  at Object.onceWrapper (node:events:***:**)
  at TLSSocket.emit (node:events:***:**)
  at node:net:***:**
  at TCP.done (node:_tls_wrap:***:*)

`

So  as _sessionCache was undefined on the original object therefore _sessionCache.list crashed.

(I've intentionally hidden (**) the lines numbers)
