### ISSUE TITLE
Add maybe and fluent functional decorators

### ISSUE THREAD

**Issue by bcherny** [lodash/lodash#527]
From allong.es-

https://github.com/raganwald/allong.es#maybe
https://github.com/raganwald/allong.es#fluent

**Comment by jfmengels** [comment]
Starting to [read about decorators such as Maybe](https://github.com/MostlyAdequate/mostly-adequate-guide), and they seem pretty interesting. Would be nice to have them in Lodash, or at least to have a function that works with them, be it `map` (:+1:) or a `fmap`. Now that there is a FP variant of Lodash, time to reconsider it I'd say.

**Comment by jdalton** [comment]
>  Now that there is a FP variant of Lodash, time to reconsider it I'd say.

The time is getting there for sure. I'd like to hold off a bit though.
I could see us jumping into these in a v5 (never too early to start planning though).

**Comment by syzer** [comment]
right now
`_.get` (old `_.pluck`) and `_.at`
are close to Maybe,
I hope for 5.0 :D and `_.maybe`
BTW meanwhile you did awesome work on 4.x!

**Comment by jdalton** [comment]
> Ps. Could you remove wontfix ;) ?

We keep the `wontfix` until there's enough dev interest and development has started.

**Comment by craigmichaelmartin** [comment]
(FWIW, as a casual peruser of lodash, `wontfix` implies to me that such a request is antithetical to the library and by definition will not be included - and, so no amount of upvotes would matter.)

**Comment by jfmengels** [comment]
We're planning for v5 now :)

I still think this would be a nice addition to `fp`, but it would only be useful if
1. Lodash methods properly use them
1. Lodash methods return them (`_.get : path -> object -> Maybe a`)

I definitely would like Lodash/FP to go into this direction. I don't know about forcing every FP user to use `Maybe` and friends though, so I'm thinking about a new Lodash variant for it, though I'd prefer having the least amount of variants possible obviously ^^'

**Comment by dgreene1** [comment]
👍

**Comment by szarouski** [comment]
Please don't get mad at me, as I just got introduced to FP. Wouldn't something like this work?

```js
var {flowRight: compose, chain, identity, curryRight, isNil} = _;

var maybe = (x, fn) => isNil(x) ? x : fn(x);
var cMaybe = curryRight(maybe);
var reportIfNil = (x, message) => {
  if (isNil(x)) {
  console.error(message);
  }
  return x;
};
var cReportIfNil = curryRight(reportIfNil);

//var val = null;
let val = {test: () => 1};

var y = chain(val).thru(cMaybe(compose(x => x.test(), identity))).thru(cReportIfNil('y: value is not defined'))
var z = _(val).thru(cMaybe(identity)).thru(cReportIfNil(`z: value is not defined`)).thru(cMaybe(x => x.test()))

//if lodash would have _.maybe
_.mixin({maybe});
var x = _(val).maybe(identity).thru(cReportIfNil(`x: value is not defined`)).maybe(x => x.test())

console.log(y.value(), z.value(), x.value());
```
