### ISSUE TITLE
UTF-8 characters changed by _.startCase()

### ISSUE THREAD

**Issue by JGNieto** [lodash/lodash#5276]
When using the function _.startCase(), UTF-8 characters are reduced to their ASCII form:

`_.startCase("confirmación de contraseña")` -> "Confirmacion De Contrasena"

Note that `ó` has become `o` and `ñ` has become `n`.

This is unexpected and should not happen.z

**Comment by knutole** [comment]
Same in Norwegian: 

```js
_.startCase('elkjøp') // returns "Elkjop"

```

**Comment by OneHoopyFrood** [comment]
Relates to #3383, probably

**Comment by OneHoopyFrood** [comment]
What's strange is that in JS contexts `"ö".toLocaleUpperCase()` results in Ö, so I'm not sure what lodash must be doing internally that it doesn't rely on this built-in feature. I'll go look at the code and see if I can put in a PR that will close this and #3383.
