### ISSUE TITLE
sortBy using alpha sort in some cases instead of numeric

### ISSUE THREAD

**Issue by TrueWill** [lodash/lodash#5282]
Example:

```js
const items = [
  { id: 21, second: 1 },
  { id: 1, second: 2 },
  { id: 3, second: 3 }
];
 
_.sortBy(items, i => [i.id, i.second]);
```

Result:

`[Object {id: 1, second: 2}, Object {id: 21, second: 1}, Object {id: 3, second: 3}]`

This seems to happen when using a projection function to get the keys; it appears to convert to strings and do an alphanumeric sort behind the scenes (thus '21' sorts before '1').

**Comment by Shayan-P** [comment]
You have to use 
`_.sortBy(items, ['id', 'second'])`
or
`_.sortBy(items, [i=>i.id, i=>i.second])`

instead of
`_.sortBy(items, i => [i.id, i.second])`

**Comment by TrueWill** [comment]
@Shayan-P is correct; perhaps this could be made clearer in the documentation?
