### ISSUE TITLE
`lodash/fp` with ESM

### ISSUE THREAD

**Issue by luiz290788** [lodash/lodash#5285]
Is there anyway to use ESM with `lodash/fp`? I tried `lodash-es` but it looks like fp functions are not published as part of that pacakge.

**Comment by dobernike** [comment]
> Is there anyway to use ESM with `lodash/fp`? I tried `lodash-es` but it looks like fp functions are not published as part of that pacakge.

I only found a way to use it in an ESM package, like: `import compose from 'lodash/fp/compose.js'`.

**Comment by phhu** [comment]
```js
import fp from 'lodash/fp.js'
```
...seems to work.

**Comment by mohit-singh-pepper** [comment]
I don't think tree shaking will work like this.

**Comment by segevfiner** [comment]
Why...? Why wouldn't lodash-es also have the fp functions... Seriously... lodash CJS/ESM is a total mess. It should really be an hybrid CJS/ESM package under the same name with everything available (Using `package.json` entry points and exports)... This will make stuff just work so that bundlers can pick the ESM build and CJS only stuff can pick the CJS build.

**Comment by jdalton** [comment]
It’s because lodash-fp is a wrapper around lodash which makes it difficult to modularize

**Comment by segevfiner** [comment]
Wouldn't it just require yet another specialized transformation in the lodash cli for it? Same way that lodash-fp itself is created?

**Comment by jdalton** [comment]
I would require some tweaking and was technically possible with some back bending however, it’s been like 8yrs now so can say this confidently, FP in JavaScript is an anti pattern for work in teams and anything perf critical. I’m okay not investing in it going forward.

**Comment by segevfiner** [comment]
What would you suggest for use as an alternative to `chain` when you want to tree shake lodash?

**Comment by dword-design** [comment]
To jump into this discussion, I use the [Babel pipeline operator](https://github.com/tc39/proposal-pipeline-operator) and current proposal relies on non-FP functions. So stuff like this should work:

```
const foo = obj
  |> groupBy(%, 'name')
  |> mapValues('foo')
```

Drawback is that it isn't currently supported by TypeScript and that the proposal doesn't proceed a lot. Still I think that nested function calls without pipe doesn't scale.

**Comment by haskelcurry** [comment]
Is there any chance of reviving this topic? Lodash/FP is absolutely needed, ESM is needed too

**Comment by morewings** [comment]
> Is there any chance of reviving this topic? Lodash/FP is absolutely needed, ESM is needed too

Just use Ramda 😉

**Comment by imanabu** [comment]
```
import fp from "lodash/fp.js";
const {first} = fp
```
Works, and also I think this will work too __ with _ and _:
```
import fp from "lodash/fp.js";
const {__} = fp
```
