### ISSUE TITLE
Add an option to ignore undefined in _.concat

### ISSUE THREAD

**Issue by crizzis** [lodash/lodash#5287]
It would be nice for `_.concat` to have an option of ignoring `undefined` parameters. 

Right now, it is pretty counterintiutive that `_.concat(object.arrayProp1, object.arrayProp2)` will contain an extra `undefined` element at the end when `object.arrayProp2` is `undefined`. 

(The actual problem is, of course, that lodash would have to know if the `undefined` represents an undefined object or an undefined array of objects; even if you decide to keep the current behaviour, documenting it better wouldn't hurt)

**Comment by Mochnant** [comment]
This seems like a useful feature.  I noticed the same unintuitive behavior.

**Comment by Lsnsh** [comment]
One method do one thing, if you want avoid `undefined`, i think you can filter it out before concat, like this:

```JS
// Before
_.concat([0], 1, null, 3, undefined, 5, false); // => [0, 1, null, 3, undefined, 5, false]


// After
_.concat(_.filter([[0], 1, null, 3, undefined, 5, false])); // => [[0], 1, 3, 5]
```

**Comment by Mochnant** [comment]
Thanks, @Lsnsh!

I had ended up using ```_.compact(_.concat(...))``` to do (mostly) the same thing.

**Comment by jdalton** [comment]
Nice! Options are tricky here and we want to avoid the "boolean trap". In cases where Lodash doesn't fit, small hand crafted utils will be a better option.
