### ISSUE TITLE
Can't find the location of the `isNaN` function implementation.

### ISSUE THREAD

**Issue by nicu-chiciuc** [lodash/lodash#5305]
Sorry if this is not the place for this question but I've been trying to find the location of the `isNaN()` function. I found the `test/isNaN.js` file which has an import: `import isNaN from '../isNaN.js';` but the `isNaN.js` file just isn't there. Maybe I miss something very obvious but I just can't seem to find it.

**Comment by Hybueno09** [comment]
Maybe you can use native javascript function `Number.isNaN`

**Comment by nicu-chiciuc** [comment]
I was just interested in where the actual implementation of `isNaN` is.

**Comment by Yatin-kathuria** [comment]
I this is the one which you are looking for https://github.com/lodash/lodash/blob/master/.internal/baseIsNaN.js

**Comment by nicu-chiciuc** [comment]
@Yatin-kathuria I found that file, but can't understand how it's imported as `isNaN` since the name is `baseIsNaN`

**Comment by falsyvalues** [comment]
Hi @nicu-chiciuc!

Not sure to which version of `lodash` your question goes, but some of these base function as generated via our cli.
