### ISSUE TITLE
How to test a Vue debounced method?

### ISSUE THREAD

**Issue by geeksilva97** [lodash/lodash#5318]
I have a Vue application that uses the `debounce` function in a search input. I want to test my search input component but it's not being fired. I've tried to test using Jest fake timers but it didn't work, debounce is never fired (then my method is never fired too).

My code is shown below:

```vue
<template>
  <input type="text" @input="onSearchInput" />
</template>

<script>
import { debounce } from 'lodash';

export default {
  name: 'CommonFilter',
  emits: ['change'],
  methods: {
     onSearchInput: debounce(function(e) {
       // do something
      this.$emit('change', {search: e.target.value});
     }, 700),
  }
};
</script>
``` 

I tried to test using the following code.

```js
it('emits @change event when type', async () => {
        jest.useFakeTimers();
        
        const wrapper = mount(CommonFilter);
        const $input = wrapper.find('.search-input');
        await $input.setValue('jackfruit');

        jest.runOnlyPendingTimers();

        expect(wrapper.emitted().change).toBeTruthy();
    });
```

Thank you for any help.

**Comment by ruofanwei** [comment]
@geeksilva97 


```html
<script>
export default {
  name: "Header",
  data() {
    return {
      searchText: "github",
    };
  },
  methods: {
    // If the user types very fast, will allow the execution of func only when the user has stopped typing in the search bar
    DebounceFn: function () {
      if (this.searchText.length >= 3) {
        // schedule the execution after user stopped typing in the search bar
        setTimeout(() => {
          this.$emit("onSearch", this.searchText);
        }, 1000);
      }
    },
  },
};
</script>
```

```js
it("emits an event with search text", async () => {
    jest.useFakeTimers();
    const wrapper = mount(Header);
    // calling emitEvent twice
    wrapper.vm.DebounceFn();
    wrapper.vm.DebounceFn();
    
    jest.runOnlyPendingTimers();

    // you can console it and check
    console.log(wrapper.emitted().onSearch[0]);

    expect(wrapper.emitted().onSearch[0]).toEqual(["github"]);
  });
```
![截圖 2022-01-23 下午3 29 35](https://user-images.githubusercontent.com/32828379/150668859-72902419-fcd8-4f40-aa37-f04e71e804d3.png)

**Comment by mdblj** [comment]
@geeksilva97 How did you solve this? The above answer only applies to setTimeout not _.debounce

**Comment by lynx-r** [comment]
According to this comment https://github.com/facebook/jest/issues/3465#issuecomment-351186130 you can workaround this issue by mocking `debounce` with 
`jest.mock('lodash/debounce', () => jest.fn(fn => fn));`

**Comment by abarbosa-godaddy** [comment]
> @geeksilva97 How did you solve this? The above answer only applies to setTimeout not _.debounce

I couldn't. All the answers here are about mock. Looks like a kind of integration test with the real debounce doesn't work.

**Comment by orlandCasta** [comment]
> De acuerdo con este comentario [jestjs/jest#3465 (comentario),](https://github.com/jestjs/jest/issues/3465#issuecomment-351186130) puedes solucionar este problema burlándote `debounce`de `jest.mock('lodash/debounce', () => jest.fn(fn => fn));`tu archivo `setupJest.js`.

this worked for me, thanks

**Comment by orlandCasta** [comment]
> According to this comment [jestjs/jest#3465 (comment)](https://github.com/jestjs/jest/issues/3465#issuecomment-351186130) you can workaround this issue by mocking `debounce` with `jest.mock('lodash/debounce', () => jest.fn(fn => fn));` in your `setupJest.js`.

this worked for me, thanks

**Comment by geeksilva97** [comment]
> > @geeksilva97 How did you solve this? The above answer only applies to setTimeout not _.debounce
> 
> I couldn't. All the answers here are about mock. Looks like a kind of integration test with the REAL debounce doesn't work.


@geeksilva97 How did you solve this? The above answer only applies to setTimeout not _.debounce

I couldn't. All the answers here are about mock. Looks like a kind of integration test with the REAL debounce doesn't work.

(just realized I had commented with the wrong account)

**Comment by abarbosa-godaddy** [comment]
> @geeksilva97
> 
> ```
> <script>
> export default {
>   name: "Header",
>   data() {
>     return {
>       searchText: "github",
>     };
>   },
>   methods: {
>     // If the user types very fast, will allow the execution of func only when the user has stopped typing in the search bar
>     DebounceFn: function () {
>       if (this.searchText.length >= 3) {
>         // schedule the execution after user stopped typing in the search bar
>         setTimeout(() => {
>           this.$emit("onSearch", this.searchText);
>         }, 1000);
>       }
>     },
>   },
> };
> </script>
> ```
> 
> ```js
> it("emits an event with search text", async () => {
>     jest.useFakeTimers();
>     const wrapper = mount(Header);
>     // calling emitEvent twice
>     wrapper.vm.DebounceFn();
>     wrapper.vm.DebounceFn();
>     
>     jest.runOnlyPendingTimers();
> 
>     // you can console it and check
>     console.log(wrapper.emitted().onSearch[0]);
> 
>     expect(wrapper.emitted().onSearch[0]).toEqual(["github"]);
>   });
> ```
> 
> ![截圖 2022-01-23 下午3 29 35](https://user-images.githubusercontent.com/32828379/150668859-72902419-fcd8-4f40-aa37-f04e71e804d3.png)
> 
> [Vue Testing Handbook](https://lmiller1990.github.io/vue-testing-handbook/testing-emitted-events.html#emitted-syntax)

shouldn't be using lodash's debounce function? The issue was not with Vue itself.
