### ISSUE TITLE
_.split(undefined, ",") returns [ '' ] instead of []

### ISSUE THREAD

**Issue by dyarfaradj** [lodash/lodash#5322]
Problem:
`
const query = undefined;
const list = _.split(query.list, ",");
`
Output 
`[ '' ]`

According to the code of _.split it should return an empty array

**Comment by c0d3-ninja** [comment]
@dyarfaradj 

It seems your code having error (the browser will throw error while accessing query.list) you can't access an undefined type by using '.' operator 
Kindly recheck your code or kindly host it in online platforms like codesandbox.

**Comment by danimajo** [comment]
@dyarfaradj - while your sample code seem to have an error as @c0d3-ninja already stated I could not find the code you are referring to 

> According to the code of _.split it should return an empty array


There is no code and no obvious reason why split would/should replace an empty array here.

Also see [Test for split()](https://github.com/lodash/lodash/blob/master/test/split.js)

**Comment by dyarfaradj** [comment]
@c0d3-ninja @danimajo Here's a codepen with the issue, should've included in the OP.
https://codepen.io/Hoggy32/pen/jOGPPgx

**Comment by danimajo** [comment]
Thank you for your codepen, but why should this split return an empty array?

**Comment by tiagocastro070** [comment]
> Thank you for your codepen, but why should this split return an empty array?

I also think it should return an empty array instea. For instance if you provide an empty string as a first argument it also returns an array with one item, an empty string. Wouldn't it be better to follow the convention of the native `split` method and return an empty array since there is nothing to split.

It also might be very useful if the developer wants to to map the result right next to it:
`_.split(undefined, ',').map(/* it will always run it at least once */)`

What do you think?

**Comment by mohamadaminkarami** [comment]
Hello, I've fixed the bug in #5333 . please consider it.

**Comment by dyarfaradj** [comment]
> Thank you for your codepen, but why should this split return an empty array?

As @tiagocastro070 mentioned above. And I also think it's better to send an empty array if there was nothing to split. So we can later check the returned value from _.split and for some if conditions etc..

**Comment by danimajo** [comment]
@mohamadaminkarami Should we also return [] if string is null ?

**Comment by mohamadaminkarami** [comment]
> @mohamadaminkarami Should we also return [] if string is null ?

Yes, I think it should.
