### ISSUE TITLE
[BUG]: find/findIndex _.property iteratee shorthand doesn't work on array of ObjectId create using MongoDB node driver 4.2.0

### ISSUE THREAD

**Issue by simplecommerce** [lodash/lodash#5324]
**Intended outcome:**

Get the correct array element or element's index when using `_.property` iteratee shorthand with an ObjectId created from MongoDB function.

**Actual outcome:**

Wrong element is returned or wrong index.

**How to reproduce the issue:**

See this instance: https://codesandbox.io/s/lodash-bug-with-find-findindex-and-mongodb-objectid-rizg8?file=/src/index.js

The first example rendered demonstrates my array of object id's using findIndex and find. This is the issue. 

The second example uses `_.matches` iteratee shorthand, which seems to work.
In this example, both examples should return the same results.

**Versions**

Lodash v4.17.21
MongoDB v4.2.0

**Comment by c0d3-ninja** [comment]
https://lodash.com/docs/#find
https://lodash.com/docs/#findIndex

Please read the documentation of find and findIndex by using above links

You can't pass value directly to find the index of the value to the second argument of find or findIndex if first argument is an array.

try below code

```
   findIndex(ids, function (hexObject) {
          return (
          hexObject.toHexString() ==
            ObjectId.createFromHexString(
              "5c95349695c69c5b0bfe44e9"
            ).toHexString()
          );
        })
        
         find(ids, function (hexObject) {
          return (
          hexObject.toHexString() ==
            ObjectId.createFromHexString(
              "5c95349695c69c5b0bfe44e9"
            ).toHexString()
          );
        })
```

**Comment by simplecommerce** [comment]
> https://lodash.com/docs/#find https://lodash.com/docs/#findIndex
> 
> Please read the documentation of find and findIndex by using above links
> 
> You can't pass value directly to find the index of the value to the second argument of find or findIndex if first argument is an array.
> 
> try below code
> 
> ```
>    findIndex(ids, function (hexObject) {
>           return (
>           hexObject.toHexString() ==
>             ObjectId.createFromHexString(
>               "5c95349695c69c5b0bfe44e9"
>             ).toHexString()
>           );
>         })
>         
>          find(ids, function (hexObject) {
>           return (
>           hexObject.toHexString() ==
>             ObjectId.createFromHexString(
>               "5c95349695c69c5b0bfe44e9"
>             ).toHexString()
>           );
>         })
> ```

Sorry about that, I misread and thought it made sense for it to work like that.
I just tested again with a regular array and indeed it doesn't work as I thought.

Thanks for the clarification!

**Comment by simplecommerce** [comment]
@c0d3-ninja the only weird thing about this, is that I was using it in that fashion on my current code and it was working before, so that is why I was assuming there was a change which made it stop working.

**Comment by c0d3-ninja** [comment]
@simplecommerce 
I have checked with their documentation. There are no changes in those methods.
It  seems like working because you might find an element which is always in the 0th index :)

**Comment by simplecommerce** [comment]
@c0d3-ninja from what I understand, is in the node driver prior to the 4.x, ObjectId's would return as objects and not instances of `new ObjectId`, and this is what caused it to stop working from what I gather.
