### ISSUE TITLE
e.currentTarget is not available when using debounce in onChange

### ISSUE THREAD

**Issue by fgblomqvist** [lodash/lodash#5329]
Same/similar problem like the one detailed here:
https://github.com/jashkenas/underscore/issues/1905

Reproduction:
https://codesandbox.io/s/morning-dream-jbwlu?file=/src/App.js

Why is this? I didn't understand the explanation given in the above thread, and maybe it's different for lodash anyway.
To me, it feels like odd behavior/UX.

**Comment by estasjuk** [comment]
It happens because of event bubbling
