### ISSUE TITLE
How to call lodash create object fcuntion in lodash-es?

### ISSUE THREAD

**Issue by evangunawan** [lodash/lodash#5341]
Hello, I am developing angular app, and want to change `lodash` to `lodash-es`, since we want to optimize imports.

I got a problem where there is a line `_(obj)` (creating lodash object), that `the expression is not callable`.
since I use the lodash-es, that funcion can not be called.
Is there any alternative or other function to have the same functionality?

Tried to research `chain` function, is it the same as the `_(obj)` ?
But the chain function seems not available on lodash-es.

Thank you.

**Comment by vivekdev0** [comment]
how is this fixed?, what is the workaround?

**Comment by guoh27** [comment]
+1

**Comment by T3sT3ro** [comment]
scuse me, wtf, why is this closed. How to mitigate?

**Comment by hborchardt** [comment]
For me, replacing `_(...)` with `_.chain(...)` worked with lodash-es. Maybe it was added in the meantime.
