### ISSUE TITLE
_.set behavior is too surprising for string array indices

### ISSUE THREAD

**Issue by jedwards1211** [lodash/lodash#5347]
I just discovered today that `_.set(a, ['b', '0'])` treats the `'0'` as an array index, initializing `a.b` to an empty array if it doesn't exist.

I always assumed it would treat numbers as array indexes, and all strings as object properties, for purposes of initialization, since it's not common to assign an object property using a numeric key, or an array element using a string index...

All the documentation says is

> If a portion of path doesn't exist, it's created. Arrays are created for missing index properties while objects are created for all other missing properties

This is unclear because I thought "index properties" means numbers, not strings that look like numbers.

I've used lodash for many years without realizing this.  One could have code that seems to work properly for a long time until one day a user enters a numeric string.

The documentation should warn that strings which are array indices ([as defined by the ECMAScript spec](https://tc39.es/ecma262/#array-index)) will create arrays at their paths instead of objects.

You might tell me as you have in other threads that I can just use `_.setWith` to create objects for string keys, but since it casts all keys to strings when calling the customizer, I would *only* be able to create objects in that case.

**Comment by dhilt** [comment]
I was also surpised with this behaviour, it forced us to replace lodash-set... Btw here's the original issue with some "explanations" from maintainers: https://github.com/lodash/lodash/issues/1316.
