### ISSUE TITLE
cloneDeep can't clone the groups props of REGEXP matching Array

### ISSUE THREAD

**Issue by MadShura** [lodash/lodash#5354]
System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 8.34 GB / 15.85 GB

//demo: just simple test on chrome  95.0.4638.54
      const str = "i dont know";
      const re2 = /i(?<qwe> dont(?<cat>.))/;
      let qq = str.match(re2);
      var bb = _.cloneDeep(qq);
      console.log('bb is :' ,bb,'\n','qq is :' ,qq);

//what is the reason? the groups is not the standard props?

thanks have a good day~

**Comment by MadShura** [comment]
some wrong on that demo :
please look this: 
![QQ截图20220111032141](https://user-images.githubusercontent.com/45080320/148826196-d271ab5c-4592-4e43-96ae-712d32ee9d08.png)

**Comment by jdalton** [comment]
Hi @MadShura! Yes. That's not supported. However the deep clone method in Node does support this. There is also an emerging `structuredClone` method in browsers and Node that can support this.

**Comment by MadShura** [comment]
> Hi @MadShura! Yes. That's not supported. However the deep clone method in Node does support this. There is also an emerging `structuredClone` method in browsers and Node that can support this.

thanks! have a good day
