### ISSUE TITLE
feature request: string slugify method

### ISSUE THREAD

**Issue by lallenfrancisl** [lodash/lodash#5356]
A function to create slug strings from normal strings would be great. Slug strings are lower case strings that contain no space. For example, 
```js 
_.slugify("A teSt string to slugify") => "a-test-string-to-slugify"
```

**Comment by xpressabhi** [comment]
Fairly popular way is already there https://www.npmjs.com/package/slugify

**Comment by navicstein** [comment]
@lallenfrancisl 
There's already [kebabCase](https://lodash.com/docs/4.17.15#kebabCase)

**Comment by lallenfrancisl** [comment]
Oh yeah. For someone looking for this
`const slugify = (str) => _.kebabCase(str.toLowerCase())`
