### ISSUE TITLE
CloneDeep strange behaviour with references

### ISSUE THREAD

**Issue by Memfisrain** [lodash/lodash#5364]
I ran into a strange behaviour with `cloneDeep` function.

For example:

```
const peopleConfig = {
  fields: ['name', 'age'],
};

const management = {
  employee: {
    config: peopleConfig,
  },
  outsource: {
    config: peopleConfig,
  },
};

const newManagement = _.cloneDeep(management);

newManagement.employee.config === newManagement.outsource.config; // true
```

My expectation here is that after cloning we should break the refs and comparison returns **false.**

It happens cause we store the traversed results in cache and extract it. You can see [here](https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/.internal/baseClone.js#L199)

Could you clarify is it expected behaviour or not?

**Comment by lxs24sxl** [comment]
I found that they are to solve `the circular reference problem`, in fact, they can add a `depth` parameter to determine whether the reference object is in the `same layer`.

If it is in the same layer, then `copy the data`, and if it is in a different layer, then `return the reference`

```js
// Check for circular references and return its corresponding clone.
  stack || (stack = new Stack);
  var stacked = stack.get(value);
  if (stacked) {
    return stacked;
  }
  stack.set(value, result);
 
 // ...
 
 arrayEach(props || value, function(subValue, key) {
    if (props) {
      key = subValue;
      subValue = value[key];
    }
    // Recursively populate clone (susceptible to call stack limits).
    assignValue(result, key, baseClone(subValue, bitmask, customizer, key, value, stack));
  });
```
