### ISSUE TITLE
_.set doesn't set the json name correctly, it splits into two section

### ISSUE THREAD

**Issue by sherinkd** [lodash/lodash#5371]
Code: 
set({}, 'XXXXXXX,YYYYY,DDDDDD, AAAAAA BBBBBBB 2.1%,KJDKS,asdfasdasdf', ['1'])

Expected Result:
{
  "XXXXXXX,YYYYY,DDDDDD, AAAAAA BBBBBBB 2.1%,KJDKS,asdfasdasdf": ["1"]
}

Actual Result:
{
  "XXXXXXX,YYYYY,DDDDDD, AAAAAA BBBBBBB 2": {
    "1%,KJDKS,asdfasdasdf": [
      "1"
    ]
  }
}

**Comment by asingh04** [comment]
I think this is the intended  behaviour. According to the docs, the second argument is the path and the dot (.) in the path string represent a delimiter and consider the next part after the delimiter as a child property
