### ISSUE TITLE
BUG: keyBy doesn't work when mapped value is a function

### ISSUE THREAD

**Issue by juni0r** [lodash/lodash#5372]
**VERSION** 4.17.15

When using `keyBy` with an iteratee that returns a function, it doesn't yield the expected result.

### Example

```js
keyBy([
  'foo',
  'bar',
], key => function() {
  return this[key];
});
```
### Expected Result

```js
{
  foo: ƒ (),
  bar: ƒ ()
}
```

### Actual Result
```js
{"function() {↵    return this[key];↵  }": 'bar'}
```

**Comment by ajitjha393** [comment]
Your approach is wrong, 
`keyBy` is used to generate `key`  based from collection,
It cannot manipulate the value 
And whatever we return from the function that becomes the key 

And here you are returning the entire function and not just the value
```js 
 function () {
    return this[Key]
 }
```

And For Objects key can only be `[number |  string | Symbol]`

Hence this function which is now a key, is coerced into a string and hence the output
![image](https://user-images.githubusercontent.com/42679346/151690070-80f3cb2f-7ecd-43fd-9566-2fec15a5bbcb.png)
 

What are you tryna achieve btw? 
There can be other uitlity for that

See [Implementation of keyBy](https://github.com/lodash/lodash/blob/master/keyBy.js)

**Comment by ajitjha393** [comment]
This is how you can achieve your required output - 
![image](https://user-images.githubusercontent.com/42679346/151690301-0f634c84-ec21-4e03-837b-00888c1e5a0e.png)

**Comment by juni0r** [comment]
I'm terribly sorry for not reading the documentation carefully enough. You were right in guessing what I wanted to achieve and I did in fact use the reduce approach you suggested.

It never came to my mind though to use the spread operator and dynamic keys for accumulation in the way you did. Nice! So there is one more lesson learned for me here.

Thanks for looking into this and the prompt reply.

Cheers!
