### ISSUE TITLE
Feature: use _get to get multiple variables with one statement by specifying in path

### ISSUE THREAD

**Issue by mfissehaye** [lodash/lodash#5374]
`const {chat, from, date} = _get(req, 'body.data.[chat,from,date]', null)`

The same way [destructuring assigment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) works `const { a, b, c } = { a: 1, b: 2, c: 3 }`. Can we have [`lodash.get`](https://lodash.com/docs/4.17.15#get) to be able to fetch multiple variables from a path as mentioned in the example above.

**Comment by ajitjha393** [comment]
My implementation for this ->

(ps: I didn't cover all corner cases, but the gist of the requirement)

Feel free to use this approach, for now,  :D @mfissehaye 

```js
function getMulti(obj, keyString, propList ) {
    const keys = keyString.split('.')
    const parentNode = 
            keys.reduce((acc, k) => acc[k], obj)

   
    return propList.reduce((acc, prop) => ({
        ...acc,
        [prop]: parentNode[prop]
    }), {})    

}

getMulti(req, 'body.data', ['chat', 'from', 'date'])

// -> {chat: 'Dummy chat', from: 'Dummy from', date: 'Dummy Date'}

```

![image](https://user-images.githubusercontent.com/42679346/151691007-a6e76438-a109-4031-819f-029632f94fe8.png)
