### ISSUE TITLE
Lodash FP Documentation

### ISSUE THREAD

**Issue by saiichihashimoto** [lodash/lodash#5381]
It's great that there's a [Lodash FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide) that helps understand how to use this library in an FP flow. However, we still need to mentally derive how to use the functions (how many arguments am I capped to, what's the arity, which functions are exceptions to the reversed arguments rule or have a custom ordering of arguments, etc.) instead of looking at a definitive truth per function.

Are we able to do one of:

1. Generate documentation like the original documentation but for FP
2. Have a section per function in the current documentation that calls out the FP argument ordering
3. The wiki, instead of (or along with) listing how to derive the arguments for the functions, just list out all the functions with their arguments. It could link to the original documentation.

I'm constantly using the functions incorrectly and having to figure out if I'm determining the arguments correctly or if it fits under an exception.

**Comment by saiichihashimoto** [comment]
"issue bankruptcy" lol, I love it

**Comment by jdalton** [comment]
@saiichihashimoto It's time to declare it. Thank you for understanding.
