### ISSUE TITLE
lodash eval/new Function() usage causing Next.js Middleware to fail

### ISSUE THREAD

**Issue by blakewilson** [lodash/lodash#5394]
Next.js middleware runs on a [strict runtime](https://nextjs.org/docs/api-reference/edge-runtime), which does not allow `eval` or `new Function(evalString)`:

>The following JavaScript language features are disabled, and will not work:
>    [eval](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval): Evaluates JavaScript code represented as a string
>    [new Function(evalString)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function): Creates a new function with the code provided as an argument

Can Lodash still run in this environment? For example `trim` imports `_root.js` which uses this type of logic for a global object reference:

```js
/** Used as a reference to the global object. */
var root = freeGlobal || freeSelf || Function('return this')();
```

This results in the following Next.js error during build:

```
Failed to compile.

../../../node_modules/lodash/_root.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/_middleware

Import trace for requested module:
../../../node_modules/lodash/_Symbol.js
../../../node_modules/lodash/_baseToString.js
../../../node_modules/lodash/trim.js
./src/pages/_middleware.tsx
```

In regards to issue https://github.com/lodash/lodash/issues/3328, it seems like this behavior is avoidable. Is this still the case?

**Comment by blakewilson** [comment]
Ref: https://github.com/vercel/next.js/issues/30674

**Comment by tehnorm** [comment]
Also seeing this issue with Deno Deploy - https://deno.com/deploy/docs/runtime-api#limitations - it also restricts the use of `eval()` and `new Function`. Is this call strictly needed or is there another way to handle this?

**Comment by Glavin001** [comment]
Cross-posting from https://github.com/lodash/lodash/issues/5525#issuecomment-1426535044

---


Adding `unstable_allowDynamic` to Next.js API endpoint's `config` worked for me.

`api/<name>.js`:
```diff
 export const config = {
     runtime: "edge",
+    unstable_allowDynamic: [
+        '**/node_modules/lodash/_root.js', // use a glob to allow anything in the function-bind 3rd party module
+    ],
 };
```

**Comment by altechzilla** [comment]
Any plans or ideas on how to make this work without the unstable_allowDynamic param? Even if just for the basic functions like get, merge, isEmpty, etc.?
