### ISSUE TITLE
_.reduce() incorrectly detects object as array

### ISSUE THREAD

**Issue by moos** [lodash/lodash#5396]
✔️  Pass an object:
```
_.reduce({a: 1, len: 3}, function(memo, v, k) {
  return Object.assign(memo, {[k]: v});
}, {});
// => Object {a: 1, len: 3}
```

❌ Pass an **object** that has a `length` key:
```
_.reduce({a: 1, length: 3}, function(memo, v, k) {
  return Object.assign(memo, {[k]: v});
}, {});
// => Object {0: undefined, 1: undefined, 2: undefined}

_.isArray({a: 1, length: 3})
// false

_.isObject({a: 1, length: 3})
// true
```

`isArray()` and `isObject()` correctly detects object with a `length` key.  `reduce()` should use these methods rather than looking just at the `length` key.

**Comment by anyanyan07** [comment]
I think this is to deal with those like array object, for example Arguments, NoteList...

**Comment by moos** [comment]
Perhaps -- but it's not robust and fails pretty bad -- if it accepts an object it shouldn't fail if the object has a `length` key. Spent couple of hours debugging this!

**Comment by WestinSchepper** [comment]
@anyanyan07 is correct here. `length` is the most reliable way to determine if something is array like. `Arguments` for example is array like, however, it only has a `length` key and no higher order functions like map, or reduce.

The `lodash.reduce` method actually uses the [`lodash.isArrayLike`](https://github.com/lodash/lodash/blob/master/isArrayLike.js) method, which is where your specific problem is occurring.

I'm guessing this isn't a common issue, but it is very annoying for you. As a work-around, you could write your own reduce method to handle objects in just a few lines of code:

```javascript
function reduceObject(collection, iterator, accumulator) {
  for (let [key, value] of Object.entries(collection)) {
    accumulator = iterator(accumulator, value, key, collection)
  }

  return accumulator
}

reduceObject({a: 1, length: 3}, function(memo, v, k) {
  return Object.assign(memo, {[k]: v})
}, {})
// {a: 1, length: 3}
```
