### ISSUE TITLE
subtract存在bug

### ISSUE THREAD

**Issue by Simon7520** [lodash/lodash#5402]
```
e.g.
subtract(2.12, 0.01)
that get result 2.1100000000000003
it's a error result
```
and in the Chinese Document (https://www.lodashjs.com/docs/lodash.subtract), there is one error that is '亮数相减'，that should be '两数相减'

**Comment by UndefinedCpp** [comment]
这不是bug，是浮点数精度的底层问题，不信你可以试试 `0.3-0.2===0.1`，返回`false`

**Comment by Simon7520** [comment]
> issue bankruptcy
我当然知道存在浮点数精度的底层问题，但封装JS库的目的不就是为了解决这个问题能够得出正确的结果吗？不然要它何用

**Comment by Lsnsh** [comment]
问题 1: 关于 “亮数相减” 应该是 “两数相减”，这个是第三方文档网站翻译的问题，建议访问官方文档

https://lodash.com/docs/4.17.15#subtract

问题 2: `_.subtract` 似乎存在 BUG ？

这个方法没有提及可以解决浮点数计算精度的问题，不能想当然的认为支持

---

Question 1: About "亮数相减" should be “两数相减”，that is an issue with third-party document website translation, recommend access official document.

https://lodash.com/docs/4.17.15#subtract

Question 2: `_.subtract` seems to have BUG ?

This method does not mention that it can solve the problem of floating point calculation accuracy, and cannot be taken for granted

**Comment by jdalton** [comment]
That domain is not an official Lodash domain. I can' help y'all there.
