### ISSUE TITLE
Gets error running basic functions like add

### ISSUE THREAD

**Issue by toomsie** [lodash/lodash#5403]
Hello I am a newbie and manage to fork project clone a copy of lodesh in vscode
and **npm install esm** at vscode's command line.

Unfortunately I am unable to run any of the projects *.js files without getting and error message and I cannot the import command a new js file without the same error message. I have been working at this for a day and I am truly stuck. Even tried Ramda repo and it did the same thing. 

SyntaxError: Cannot use import statement outside a module

**Comment by niravchavda99** [comment]
Add `"type": "module"` in your `package.json` file
OR
Use `const var = require("package-name");` syntax.

**Comment by sokarax** [comment]
> Hello I am a newbie and manage to fork project clone a copy of lodesh in vscode
> 
> and **npm install esm** at vscode's command line.
> 
> 
> 
> Unfortunately I am unable to run any of the projects *.js files without getting and error message and I cannot the import command a new js file without the same error message. I have been working at this for a day and I am truly stuck. Even tried Ramda repo and it did the same thing. 
> 
> 
> 
> SyntaxError: Cannot use import statement outside a module

**Comment by niravchavda99** [comment]
You cannot directly run modules. You can run `npm run test` after `npm install`
