### ISSUE TITLE
Why  we need to judge null and undefined?

### ISSUE THREAD

**Issue by 836334258** [lodash/lodash#5404]
function getTag(value) {
  if (value == null) {
    return value === undefined ? '[object Undefined]' : '[object Null]'
  }
  return toString.call(value)
}

export default getTag

Why  we need to judge null and undefined?

**Comment by jdalton** [comment]
It's a known value so didn't need to go through another function call.

**Comment by codersjj** [comment]
> function getTag(value) { if (value == null) { return value === undefined ? '[object Undefined]' : '[object Null]' } return toString.call(value) }
> 
> export default getTag
> 
> Why we need to judge null and undefined?

Because in IE7 and 8，both `Object.prototype.toString.call(undefined)` and `Object.prototype.toString.call(null)` return `[object Object]`
see：https://stackoverflow.com/questions/14325792/when-does-object-prototype-tostring-callnull-return-object-object
