### ISSUE TITLE
Deno usage?

### ISSUE THREAD

**Issue by reviewher** [lodash/lodash#5411]
Lodash is featured in https://deno.land/x , yet there's no reference to Deno in the repo.  Does the library actually work with Deno?  If so, are there instructions for use from /x ?

**Comment by yubaoquan** [comment]
look at this https://github.com/lodash/lodash/pull/4316#issuecomment-930716964

**Comment by jabaa** [comment]
@yubaoquan It doesn't seem to work with the current version 4.17.19 and there isn't a version 4.17.19-es

**Comment by yubaoquan** [comment]
> @yubaoquan It doesn't seem to work with the current version 4.17.19 that is linked here: https://deno.land/x/lodash@4.17.19

It seems the author has removed the -es version. Unfortunately.

**Comment by reviewher** [comment]
`4.17.21-es` tag:

```ts
import { add, eq } from 'https://raw.githubusercontent.com/lodash/lodash/4.17.21-es/lodash.js';

const result = await add(1, 2);
console.info(eq(1, 2));
console.info(eq(1, 1));
console.info(result);
```

**Comment by reviewher** [comment]
deno.land is irreparably broken. Repo with `-es` tags work https://raw.githubusercontent.com/lodash/lodash/4.17.21-es/lodash.js

**Comment by gflarity** [comment]
This seems to be one of the best sources for figuring out how to get deno + lodash working together. Here's the full solution I'm using which includes typing for others who stumble upon this issue: 

```
// @deno-types="https://esm.sh/@types/lodash-es/index.d.ts"
import { chunk } from "https://esm.sh/lodash-es";
```
