### ISSUE TITLE
When I pass an object containing a length property to the remove function，I got a Array that filled undefined

### ISSUE THREAD

**Issue by mya-zhang** [lodash/lodash#5412]

**Comment by mingyingzhang** [comment]
`
let obj = {length: 9};
let re =  _.remove(obj,(item)=>{console.log(item);return true});
console.log(re)
`
I wonder if this operation is intentional.

**Comment by cheung-shih** [comment]
when I try to console.log obj.length, I got It's value is 9
haha fun name
