### ISSUE TITLE
fp/gt is really weird ?

### ISSUE THREAD

**Issue by ExcitedSpider** [lodash/lodash#5414]
```
import { gt } from "lodash/fp";

const greaterThan3 = gt(3);

greaterThan3(4); // false
```
I would expect `gt(x)` means greater than x ?

**Comment by DaSchTour** [comment]
Just look at the documentation
`_.gt(value, other)`
Checks if value is greater than other.

`_.gt(3, 4)` -> false

So your function actually checks if 3 is great than the value. So everything is right. Because 4 is not greater than 3.

**Comment by ahmaddynugroho** [comment]
according to [docs](https://github.com/lodash/lodash/wiki/FP-Guide#exceptions-to-the-rules), the function `fp.gt` has it's original argument order. Which is `(a, b)` instead of `(b, a)`
