### ISSUE TITLE
Invalid result of findIndex

### ISSUE THREAD

**Issue by HwangTaehyun** [lodash/lodash#5434]
Thank you for the very useful library for js!

I read this issue (https://github.com/lodash/lodash/issues/4597).

The following explanation of _.findIndex function in the lodash homepage.
the object value is found. but string value is not found in the following code (return -1)
![image](https://user-images.githubusercontent.com/42465090/165335700-66e9bf20-01e5-47bc-965e-fe753279bf90.png)

```
const compared = ['GENERAL', 'ABC'];

// 1)
const index1 = _.findIndex(compared, 'ABC');
// return -1
// 2)
const index2 = _.findIndex(compared, (item)=>_.isMatch(item,'ABC'));
// return 1
```

If the lodash's matches function is used as the explanation on the lodash homepage, then first case also returns 1

Could I fix it?

Ah... I found out  `isMatch` function should take the object type.

However, it would be very useful for the general cases if the primitive type (like string) was also applied to this findIndex function!

**Comment by yishayhaz** [comment]
@HwangTaehyun it's because the second argument should be a function and not a string,

But, I would expect it to throw an error and not just return -1 like it's not found.
