### ISSUE TITLE
Loadash missing ES Lint format.

### ISSUE THREAD

**Issue by Exnadella** [lodash/lodash#5445]
Hi,

We are downloading loadash for our polymer project and all the dependent moduels are in ESM format.  The imported loadash has a file name index.js which is in commonJs format instead it should be in the ES Module format.  

As a workaround, we have copied the content of the loadash.js into the index.js file.

Could you please check this and correct it, so that we don't have to do this workaround every time we install loadash.  This is an issue when we use the CI, as such, we are unable to use load in our CI/CD pipeline.

Thanks,
Ranganath.

**Comment by alexdlm** [comment]
Use the `lodash-es` package

**Comment by xadeayox** [comment]
I cannot find the index.js file when I installed loadash. What could be the problem?
