### ISSUE TITLE
Spacing characters in string

### ISSUE THREAD

**Issue by iutarian** [lodash/lodash#5447]
Hello, developers. During the project, I have faced an issue. I have a piece of text like 0324437972027106872309281149999000400/0020041060245OXP
I should transform it like that to do more readable to the client:
03 24437972 0271 068 72309  28114 9999 0 0 0 4 00/00 20 04 106 0245 OXP
Unfortunately, I couldn't find the right method that does that in documentation. I would be happy, if this feature would be added in coming updates. Thanks!

**Comment by crazoter** [comment]
I have a few points when I look at this problem:
1. To an uninformed observer like me, the way you split the string is arbitrary and random. What rule(s) do you use to decide whether you should inject a whitespace at a location?
2. Once you have decided on the rule(s) to how to split your string up (e.g. via regex or some other rules), you can use [_.split](https://lodash.com/docs/4.17.15#split) or even javascript's native string [split](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split) function (or other string functions) to split the string into multiple strings. Ultimately, your goal would be to generate an array of substrings based on your original text. With your array of strings, you can then [join them back together](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join) using `" "` specified as the separator string.
3. It doesn't make sense to introduce a new function for such a specific use-case when the existing functions can be used to solve your problem.
