### ISSUE TITLE
map function can't work when use lodash-webpack-plugin

### ISSUE THREAD

**Issue by zlm11** [lodash/lodash#5452]
When I use lodash-webpack-plugin to treeshake,the map function can't work in this way.
`map(users, 'user')`

The following error occured.
![image](https://user-images.githubusercontent.com/7533144/172510555-db621bec-f441-4bf8-9d22-33a1fe4c3c87.png)

**Comment by Ruzie** [comment]
`iteratee` expected you must use a callback function.
```js
const arr = [1, 2, 3, 4, 5]
map(arr, e => console.log(e));
```
you can't use `map(users, 'user')` as here "user" is a string but map expected you pass a function and that's why it can't iterate.

**Comment by zlm11** [comment]
Thanks for reply,I know what you mean,but if I don't do treeshake, the example works well and this example come's from official document.
https://lodash.com/docs/4.17.15#map
![image](https://user-images.githubusercontent.com/7533144/172838626-19df3e7c-d432-4e66-8c35-412d173ea7c8.png)


> `iteratee` expected you must use a callback function.
> 
> ```js
> const arr = [1, 2, 3, 4, 5]
> arrayMap(arr, e => console.log(e));
> ```
> 
> you can't use `map(users, 'user')` as here "user" is a string but map expected you pass a function and that's why it can't iterate.

**Comment by Ruzie** [comment]
Hehe great to know you've solve it!
