### ISSUE TITLE
_.toNumber(true) returns 1

### ISSUE THREAD

**Issue by errmayank** [lodash/lodash#5467]
I'm just wondering if this is an intended behavior or not.

```js
_.toNumber(true);
// returns 1

_.toNumber(false);
// returns 0
```

I was expecting both of them to return `NaN`

**Comment by yishayhaz** [comment]
This is not a bug, 
try running this js code:

`Number(false)`
`-true`
`true + 4`

`true` is equal to any number but 0 (negative numbers are `true`), and `false=0`.

**Comment by jahedev** [comment]
Also, in the implementation, booleans would fall in the fourth case: 
`if (typeof value !== 'string') { return value === 0 ? value : +value }`. 

`+true` returns 1, and `+false` returns 0 in JS.

```js
// toNumber.js
function toNumber(value) {
  if (typeof value === 'number') { /* ... */ }
  if (isSymbol(value)) { /* ... */ }
  if (isObject(value)) { /* ... */ }
  
  if (typeof value !== 'string') {
    return value === 0 ? value : +value
  }

   /* ... */ 
}
```
