### ISSUE TITLE
Augment _.invert to work with array valued objects. [Feature Request]

### ISSUE THREAD

**Issue by cbartondock** [lodash/lodash#5470]
Suppose we have an object like `f={"t1": "a", "t2": "a"}`. Currently `_.invert(f)` will produce an object `{"a":"t2"}`. While this is a true functional inverse of the object `f` viewed as a function, it is an arbitrarily chosen inverse (`{"a":"t1"}` would be just as good). Wouldn't it be better to view `_.invert` as inverting a (possibly multi valued) ``function'' to produce another possibly multiply valued function? That is, wouldn't it be better to have `_.invert(f)` produce something like ```{ "a": ["t1", "t2"] }``` ?

Moreover, instead of `_.invert({"t1": ["a","b"]})` yielding something not very useful like like `{"a, b": "t1"}` it would give `{"a": "t1", "b": "t1"}`.

I am using the following code instead of `_.invert` to achieve this behavior, although no doubt it is quite poorly written:

```javascript
function inv(a) {
  let pairs = _.flatten(Object.entries(a).map(x=>[].concat(x[1]).map(y=>[y,x[0]])),1);
  let res = {};
  for(let i=0; i < pairs.length; i++) {
    if(!res[pairs[i][0]]) {
      res[pairs[i][0]]=pairs[i][1]
    } else {
      res[pairs[i][0]]=[].concat(res[pairs[i][0]]).concat(pairs[i][1])
    }
  }
  return res
}
```
Feel free to test it out at https://replit.com/@ChrisDock/FirstWretchedSyntax#index.js. As a quick example:

![ex1](https://user-images.githubusercontent.com/4482454/177194472-5c66382c-1a79-45e2-8d9a-691214e288b7.png)

Note that unlike `_.invert`, `inv` actually correctly undoes itself if applied twice. The only asymmetry this approach has is that `inv(inv(obj))` will "unwrap" all singleton lists in obj, but I should note that `_.inv(_.inv(obj))` also does this:

![ex2](https://user-images.githubusercontent.com/4482454/177193689-271da537-95c5-4ca8-9ed8-f095a7200bd6.png)

Also, like `_.invert`, `inv` will cast all non string or array values to string.

**Comment by yishayhaz** [comment]
First of all, I don't understand why someone would use this function, it seems useless to me.
But hey, fun challenge.

so yes; you are correct, `[a, b]="t1"` is entirely useless, a better solution in my opinion would be using `array.join()`.

in your solution there are couple of problems (if we ignore overrides issues):

```js
const toInvert = { key: ["random-string"*100] }; // 101 items (key & arra)
const inverted = { "random-string": key * 100 }; // suddenly its 100 pairs of key:value

// although this is not the right way to calculate memory, you get the idea
```

so, here's my take:

```js
const toInvert = {
    "name": "superman",
    "favActor": "superman",
    "age": 69,
    "isAlive": true,
    "friends": ["batman", "ironman", "ladygag"]
};

const _invert = obj => Object.keys(obj).reduce((value, crrKey) =>
        ({ ...value, [`${obj[crrKey]}`]: value[`${obj[crrKey]}`] ? `${value[`${obj[crrKey]}`]},${crrKey}` : crrKey }),{})

console.log(_invert(toInvert))

/*
  {
   '69': 'age',
    superman: 'name,favActor',
    true: 'isAlive',
    'batman,ironman,ladygag': 'friends'
  }
*/
```

**Comment by cbartondock** [comment]
The use is to be able to perform a single expensive operation (inv) and store the result, then to be able to much more quickly look up which keys contain a given value. 

Problem: Find out which keys of object `a` have value or contain value `val`.

Without inv:

Search through all entries in `a` looking for `val`.

With inv:

Assume `b=inv(a)` is known. Just look up`b[val]`.
