### ISSUE TITLE
Lodash package appears to break eslint rule

### ISSUE THREAD

**Issue by jt5301** [lodash/lodash#5474]
Hello,
We are currently including Lodash in our project, and noticed that running eslint highlights the following rule in the package: https://eslint.org/docs/latest/rules/no-new-func
Would anyone have any potential suggestions on how to repair?

Thank you,

**Comment by Bytecode-Velocity732** [comment]
Right now you could specify `no-new-func` as `false` in rules in eslintconfig . i don't think there will be an update soon since there is no sign of contributors comments on issues. Also the last publish is over an year ago

`"rules": {
  "no-new-func": false
    }`
