### ISSUE TITLE
Why remove document.all?

### ISSUE THREAD

**Issue by gklinwei** [lodash/lodash#5479]
`_.compact([1, document.all, 2]); // => [1, 2]`

**Comment by jdalton** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/Document/all#conversion_to_boolean.

**Comment by gklinwei** [comment]
> See https://developer.mozilla.org/en-US/docs/Web/API/Document/all#conversion_to_boolean.

But the documentation doesn't mention it.

**Comment by gklinwei** [comment]
@jdalton

**Comment by gklinwei** [comment]
@jdalton See https://lodash.com/docs/4.17.15#compact.
