### ISSUE TITLE
isNullish type check

### ISSUE THREAD

**Issue by JohannCooper** [lodash/lodash#5483]
### :bulb: Description
Similar to the [`isNull`](https://lodash.com/docs/4.17.15#isNull) and [`isUndefined`](https://lodash.com/docs/4.17.15#isUndefined) type checks that already exist in lodash, `isNullish` would check if a value is `null` or `undefined`.

Why the word "nullish"? In ES11, the [nullish coalescing operator (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) was officially added to JavaScript. In this language feature, the word "nullish" refers to a value that is `null` or `undefined`.

### :star: Examples
```js
// Filtering lists
const values = [1, null, 2, undefined, 3];
const numbers = values.filter((value) => !isNullish(value)); // [1, 2, 3]
```
```js
// Conditional logic
const printName = (person) => {
  if (isNullish(person.name)) {
    console.log("No name provided");
  } else {
    console.log(`Hi, my name is ${person.name}.`);
  }
};

const people = [
  { name: null, age: 12 },
  { name: "Alice", age: 34 },
  { age: 56 },
];

people.forEach(printName);
/*
Outputs:
  "No name provided"
  "Hi, my name is Alice."
  "No name provided"
*/
```

**Comment by srn271** [comment]
You can already use `isNil`.

https://lodash.com/docs/4.17.15#isNil

In my opinion, no additional alias is needed.

**Comment by JohannCooper** [comment]
@srn271 
Thanks for pointing this out. I'll leave this issue up in case other people think an alias would be valuable.

Funny enough, the docstring for `isNil` says "Returns `true` if `value` is **nullish**, else `false`."

**Comment by JohannCooper** [comment]
Closing because the `isNil` type check already exists.
