### ISSUE TITLE
[Question] Any updates on version 5?

### ISSUE THREAD

**Issue by Deckstar** [lodash/lodash#5486]
Hello!

Please allow me to use this moment to say that I absolutely love `lodash` and use it in practically all my JS projects! 😄 

I read a while ago in [this tweet](https://twitter.com/jdalton/status/1482210925511774208?s=20&t=915KudC7ZQ03Ngv4QiN4FQ) by John-David Dalton that there was some hope to release lodash 5 sometime this late spring. But it's already late July, so I've been wondering: **have there been any updates on lodash 5?** How's it going in general (if it's not a secret)? 😄 

I haven't found any tweets / articles / github issues on this topic, so I figured the only thing I could do was to just ask 😄 Apologies if this sounds a bit pushy. I'm just very excited, and I'm sure many others like me have been waiting for a v5 release for a long time 😄

Also, is there anything like a lodash blog or something that I could follow for future updates, perhaps?

Thank you for your time! 🙂

**Comment by jdalton** [comment]
Hi @Deckstar!

I started some other daily habits and programming for fun (outside of work) has been hard to find time for. It's still my goal to set some time aside to do this.

**Comment by Deckstar** [comment]
Hey @jdalton,

No worries. Makes sense. Thanks for the update! Good luck and have fun! 🙂
