### ISSUE TITLE
"Named Export 'last' not found" With Latest lodash-es (v4.17.21)

### ISSUE THREAD

**Issue by machineghost** [lodash/lodash#5487]
I'm using the latest version of Lodash ES, but I'm getting:

> import { last } from 'lodash-es';
>          ^^^^
> SyntaxError: Named export 'last' not found. The requested module 'lodash-es' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from 'lodash-es';
> const { last } = pkg;

I'm using the Node options `--experimental-specifier-resolution=node` and  `--loader ./loader.js` (but, as far as I can tell, the custom loader isn't messing with Lodash imports).

Are either of those options known to break `lodash-es` imports, or could there be some other issue?

**Comment by machineghost** [comment]
Just to give a few more details, I've tried all of the following in my custom loader function:

    export function resolve(originalSpecifier, context, defaultResolver) {
      if (specifier === 'lodash-es') {
        // ...

1. Returning it with the default resolver:

    return defaultResolver(specifier);

2. Returning with the default resolver, using `require`:

    return defaultResolver(specifier, {
      conditions: ['node', 'require', 'node-addons'],
    });

3. Returning an object with the Lodash URL:

    return {
       format: 'module',
       url: new URL(specifier, context.parentURL).href
     };

I also tried using `lodash-unified` instead of `lodash-es`, but none of that helped.

**Comment by jdalton** [comment]
Likely because `lodash-es` is ESM written with a `.js` extension.
