### ISSUE TITLE
.range is not good

### ISSUE THREAD

**Issue by leminhhieu98py** [lodash/lodash#5489]
Code:
`_.range(1, 2, 0.1);`

### Current result:
<img width="250" alt="Screen Shot 2022-07-29 at 16 57 28" src="https://user-images.githubusercontent.com/69639199/181734953-42b8e187-4860-4d69-99e1-949d436a624d.png">

### Expect result:
`[1, 1.1, 1.2, ...]`

**Comment by v8686561728** [comment]
Hi  @leminhhieu98py 

I'm not sure if this can be considered a bug. 

For example:-
1.1+0.1=== 1.2  // false 
1.1+0.1===1.2000000000000002 // true
This is an accepted behavior as explained [here](https://stackoverflow.com/questions/588004/is-floating-point-math-broken) 

The same is happening when you are trying to increment by 0.1

**Comment by leminhhieu98py** [comment]
> The problem of this library is that contributors and not responding to the latest issues. last publish is over an year ago. i don't see any new activities on this library anymore

Since Javascript APIs are now faster and we may not need to implement the `lodash` package to our project anymore. But other old projects used `lodash`

**Comment by leminhhieu98py** [comment]
> Hi @leminhhieu98py
> 
> I'm not sure if this can be considered a bug.
> 
> For example:- 1.1+0.1=== 1.2 // false 1.1+0.1===1.2000000000000002 // true This is an accepted behavior as explained [here](https://stackoverflow.com/questions/588004/is-floating-point-math-broken)
> 
> The same is happening when you are trying to increment by 0.1

Yes, I know this problem. But this is a library and I hope it can handle this problem using some techniques
