### ISSUE TITLE
lodash/get doesn't work properly when the data is null

### ISSUE THREAD

**Issue by MaximillianoNico** [lodash/lodash#5494]
Hi guys, i got the issue when i try to access nested data and the value is `null`
seems the default value on the third params is doesn't work

```
const data = {
  test: {
    test1: null
  }
}

result = _.get(data, 'test.test1', 1) || 3
```

the result value is `3` which should be `1`

here is the example code
![Screen Shot 2022-08-01 at 18 35 33](https://user-images.githubusercontent.com/97272533/182141693-01791b73-d71e-401c-bb8c-d2c04fa8f040.png)

**Comment by crazoter** [comment]
Hi, please look more closely at the [documentation](https://lodash.com/docs#get):

Gets the value at path of object. If the resolved value is **undefined**, the defaultValue is returned in its place.

You have used the value **null** there, which is not equal to **undefined**, hence the value returned is **null**. 

Javascript then performs `result = null | 3` and as a result, `result = 3`. This is intended behavior.

Image below to illustrate my point on the difference between null and undefined:
![image](https://user-images.githubusercontent.com/9276766/182395448-bd615711-aac4-446c-86d5-5def71e15960.png)

More information on the difference between null and undefined in the context of Javascript, and why this issue isn't a bug per-se:
1. https://stackabuse.com/javascript-check-if-variable-is-a-undefined-or-null/
2. https://stackoverflow.com/questions/5076944/what-is-the-difference-between-null-and-undefined-in-javascript

**Comment by MaximillianoNico** [comment]
Hi, Ah i see got it
in my case the response API returns a nested object with one of the fields containing null data. 
just want to check if it is possible to use `lodash/get` method and add defaultValue when the data is null or undefined instead of adding extra operator OR `||`

It's pretty clear, Thanks @crazoter  :)
i will close this issue
