### ISSUE TITLE
Snyk reports a high vulnerability for the lodash.set package

### ISSUE THREAD

**Issue by kara-todd** [lodash/lodash#5499]
Snyk is flagging `lodash.set` as having a high vulnerability due to prototype pollution: https://security.snyk.io/vuln/SNYK-JS-LODASHSET-1320032.

There isn't any fixed version reported. Is this still an active issue?

**Comment by francoisihry** [comment]
:+1:

**Comment by kara-todd** [comment]
It looks like a fix was attempted in #5380 but was closed without being merged. Was there an issue with the solution in the PR?

**Comment by hipages-guoxu** [comment]
same issue.
