### ISSUE TITLE
_.template should cache compiled function or implicite declare cache

### ISSUE THREAD

**Issue by guileen** [lodash/lodash#55]
`_.template` should cache compiled function or implicite declare use cache, it will be faster.

**Comment by jkarttunen** [comment]
Given 500 + templates there is a lot repetition of "((__t = ( number )) == null ? '' : __t)"  and "var __t, __p = '', __j = Array.prototype.join;"  If we had a template cache, it could have common parts in separate function or function prototype instead of repeating everything in every function.

**Comment by jdalton** [comment]
> Given 500 + templates there is a lot repetition

Doesn't gzip love repetition?
