### ISSUE TITLE
A type predicate's type must be assignable to its parameter's type. isEmpty(value: T | null | undefined): value is EmptyObjectOf | null | undefined;

### ISSUE THREAD

**Issue by richa20shah** [lodash/lodash#5508]
ERROR in node_modules/@types/lodash.debounce/node_modules/@types/lodash/common/lang.d.ts:577:74 - error TS2677: A type predicate's type must be assignable to its parameter's type.
      Type 'EmptyObjectOf<T> | null | undefined' is not assignable to type 'T | null | undefined'.

getting error like this:

 isEmpty<T extends object>(value: T | null | undefined): value is EmptyObjectOf<T> | null | undefined;

**Comment by ChiZhangCormac** [comment]
I had the same issue. It happened yesterday.

**Comment by grmca2010** [comment]
Give us the suggestion.. We also have the same issue.. Not able to deploy our code 

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/6149055/185295855-2cded11d-948c-438a-ba37-fa4c5b137bb8.png">

**Comment by dmitry-pokhmelnov** [comment]
@grmca2010  You can use "@types/lodash": "4.14.182", it works for me.

**Comment by wsb252** [comment]
No difference / same error message.  This has a production release blocked for me as well.  

  "lodash": "^4.17.21",
    "@types/lodash": "^4.14.182",   (also tried 4.14.183)
    "typescript": "~3.5.3",

**Comment by wsb252** [comment]
just changing the value in package.json was not sufficient.  I had to explicitly add "npm install @types/lodash@4.14.182" to pin to that version.  With that add to my build script, the issue was resolved.

**Comment by thosewerethedays99** [comment]
> just changing the value in package.json was not sufficient. I had to explicitly add "npm install @types/lodash@4.14.182" to pin to that version. With that add to my build script, the issue was resolved.

Thanks a lots, added "npm install @types/lodash@4.14.182" to Dockerfile before "npm install" fixed issue for me.

Typescript 3.5.3 & lodash 4.14.182 look good

**Comment by markb-trustifi** [comment]
I have the same issue with lodash v4.17.21
