### ISSUE TITLE
add a `fillDeep` function

### ISSUE THREAD

**Issue by ricardocastanho** [lodash/lodash#5509]
### Cenario
I need to fill an Array of independent elements to use in my Vue app. Using the `fill` function I don't have cloned objects and when I change the first element of the array, all gets changed too.

### Proposal
```javascript
const obj = { foo: 'bar' };
const arr = _.fillDeep(Array(2), obj);
console.log(arr[0] === arr[1]); // => false
```

### Workaround
```javascript
const obj = { foo: 'bar' };
const arr = _.map(Array(2), () => { ...obj });
console.log(arr[0] === arr[1]); // => false
```

**Comment by ely-saakian** [comment]
Hi, why can't  you use `cloneDeep` with `fill`?
```
const obj = { foo: 'bar' };
const arr = _.fill(Array(3), _.cloneDeep(obj));
```

or am I not understanding you correctly?

**Comment by ricardocastanho** [comment]
> Hi, why can't you use `cloneDeep` with `fill`?
> 
> ```
> const obj = { foo: 'bar' };
> const arr = _.fill(Array(3), _.cloneDeep(obj));
> ```
> 
> or am I not understanding you correctly?

This actually duplicates the elements.

```javascript
const obj = { foo: 'bar' };

const filled = _.fill(Array(2), () => _.cloneDeep(obj));
console.log(filled[0] === filled[1]); // => true

const maped = _.map(Array(2), () => _.cloneDeep(obj));
console.log(maped[0] === maped[1]); // => false
```

**Comment by ely-saakian** [comment]
> > Hi, why can't you use `cloneDeep` with `fill`?
> > ```
> > const obj = { foo: 'bar' };
> > const arr = _.fill(Array(3), _.cloneDeep(obj));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or am I not understanding you correctly?
> 
> This actually duplicates the elements.
> 
> ```js
> const obj = { foo: 'bar' };
> 
> const filled = _.fill(Array(2), () => _.cloneDeep(obj));
> console.log(filled[0] === filled[1]); // => true
> 
> const maped = _.map(Array(2), () => _.cloneDeep(obj));
> console.log(maped[0] === maped[1]); // => false
> ```

Ohh my bad, try this:

```
const filled2 = _.fill(Array(2), (() => _.cloneDeep(obj))());
```

**Comment by ricardocastanho** [comment]
> > > Hi, why can't you use `cloneDeep` with `fill`?
> > > ```
> > > const obj = { foo: 'bar' };
> > > const arr = _.fill(Array(3), _.cloneDeep(obj));
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > or am I not understanding you correctly?
> > 
> > 
> > This actually duplicates the elements.
> > ```js
> > const obj = { foo: 'bar' };
> > 
> > const filled = _.fill(Array(2), () => _.cloneDeep(obj));
> > console.log(filled[0] === filled[1]); // => true
> > 
> > const maped = _.map(Array(2), () => _.cloneDeep(obj));
> > console.log(maped[0] === maped[1]); // => false
> > ```
> 
> Ohh my bad, try this:
> 
> ```
> const filled2 = _.fill(Array(2), (() => _.cloneDeep(obj))());
> ```

This still duplicates the elements, but even if it works, my point is to simplify this behavior and make it simple to use for new users :)
