### ISSUE TITLE
_.nth() accepts incorrect arguments.

### ISSUE THREAD

**Issue by c0dezer019** [lodash/lodash#5517]
_.nth() is typed for taking a _.List<any> and a number|undefined. However, I've been able to successfully pass it an array of objects and a value from the object as a string, and it returns exactly what I was looking for. The documentation and description provides that it is also supposed to be a number and Typescript throws a fit over the use of a string when it's supposed to be a number. I do not know if this is intentional or accidental functionality. Either way, I think it's clever and the types should be updated.

**Comment by razaahmad333** [comment]
```js
const result1 = _.nth( [ { name : "Something" }, { name : "else" } ] ,  2 );

const result2 = _.nth( [ 1, 2, 3, 4 ], 2 );

console.log( { result1, result2 } );
// output ->  {result1: undefined, result2: 3} 
```

its working fine

**Comment by c0dezer019** [comment]
> ```js
> const result1 = _.nth( [ { name : "Something" }, { name : "else" } ] ,  2 );
> 
> const result2 = _.nth( [ 1, 2, 3, 4 ], 2 );
> 
> console.log( { result1, result2 } );
> // output ->  {result1: undefined, result2: 3} 
> ```
> 
> its working fine

No doubt. I wasn't suggesting otherwise. It works, but now taking the first part of your example:

```
const result1 = _.nth( [ { name : "Something" }, { name : "else" } ] ,  "else");

console.log(result1);
// output ->  { name: "Something" }
```

I have reviewed the nth.js file to investigate, and there are no checks to determine if n is a number. Instead, it returns 0 if `n < 0`. So passing a string causes n to become 0. So it WILL return something if [] has a length to it. The issue with this is that in a realistic project, this would return unwanted data. Instead, an additional check should be added.

This is the code that nth uses that I've updated:

```
if (!length || typeof n !== 'number') {
    return
}
```

This would prohibit the user from using anything other than a number (obviously).
