### ISSUE TITLE
_.ceil(2.2 * 3, 3) returns inconsistent value

### ISSUE THREAD

**Issue by kabomi** [lodash/lodash#5518]
I'm using version 4.17.21 and while trying _.ceil / _.round / _.floor methods I came up with the following inconsistency.

In Javascript `2.2 * 3` = 6.6000000000000005

When using `_.ceil(6.6000000000000005, x)` I would like to get consistent values for `x >= 1`
<img width="241" alt="grafik" src="https://user-images.githubusercontent.com/3160460/189103529-8014e173-7faf-4b3d-8445-7e54e6962431.png">

On the picture above we see an inconsistency when `x = 3`.
And on the picture below  inconsistencies also appears when `x = 6, 7, 9, 10, 12, 13 & 16`
<img width="141" alt="grafik" src="https://user-images.githubusercontent.com/3160460/189104579-07749451-9ba8-4fc6-970c-7ded7a8155c4.png">

Using _.floor and _.round is more consistent but still shows it when `x = 16`
<img width="139" alt="grafik" src="https://user-images.githubusercontent.com/3160460/189105722-bbed1e4d-5438-4188-bab9-9afe772d2fd4.png">
<img width="144" alt="grafik" src="https://user-images.githubusercontent.com/3160460/189106051-f45bc676-fe01-4538-aeda-4925e8ca3716.png">

Can someone bring some light to this issue? In the meantime can someone recommend a more accurate way of rounding float numbers?

Thank you!

P.S. Please take a look at this article which provides a description of the problem an accurate implementation (no rounding errors)
https://medium.com/swlh/how-to-round-to-a-certain-number-of-decimal-places-in-javascript-ed74c471c1b8

**Comment by sittingbool** [comment]
i also just had the issue that ceil returned 10.4 when the value was 10.333333333...  
21 devided by 3
I would expect 10.3 as a result. the rounding direction seems off.
