### ISSUE TITLE
_.cloneDeep does not copy an empty value

### ISSUE THREAD

**Issue by jonathancohen0726** [lodash/lodash#5523]
When we are deleting an index of array using delete, and cloneDeep it, the empty value is replaced by undefined.
To reproduce : 

```
let array1 = [1,2,3,4,5]
delete array1[0] // array length is 4
_.cloneDeep(array1) // array length is 5
```

**Comment by chrisanag** [comment]
I think the behavior is correct.
`delete` will delete the object property, but will not reindex the array or update it's length.
So, with your block of code, we have:

```javascript
let array1 = [1,2,3,4,5]
delete array1[0]    // array length is 5 -> [empty, 2, 3, 4, 5]
_.cloneDeep(array1) // array length is 5 -> [empty, 2, 3, 4, 5]
```

Detailed explanation: [https://stackoverflow.com/a/500617](https://stackoverflow.com/a/500617)

**Comment by EthanBnntt** [comment]
Should this be fixed or not?
