### ISSUE TITLE
Cannot use lodash on Netlify Edge Runtime (in NextJS middleware)

### ISSUE THREAD

**Issue by terrabythia** [lodash/lodash#5525]
When I deploy my app to netlify I get an error because it seems lodash uses some function that is not supported in the Edge Runtime (I use it in my middleware). Can somebody with a bit more knowledge about the source code of lodash explain to me why? And if there is any way to use lodash in my next.js middleware without running into this problem?

Node version: 16.17.0
NextJS version: 12.3.0
Lodash version: 14.17.21

```
3:30:14 PM: Failed to compile.
3:30:14 PM: 
3:30:14 PM: ./node_modules/lodash/_root.js
3:30:14 PM: Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime
3:30:14 PM: Import trace for requested module:
3:30:14 PM: ./node_modules/lodash/isBuffer.js
3:30:14 PM: ./node_modules/lodash/_arrayLikeKeys.js
3:30:14 PM: ./node_modules/lodash/keysIn.js
3:30:14 PM: ./node_modules/lodash/_getAllKeysIn.js
3:30:14 PM: ./node_modules/lodash/pickBy.js
3:30:14 PM: ./src/utils/utils.js
3:30:14 PM: ./src/middleware.js
```

**Comment by pheew** [comment]
I traced it to `Function('return this')()` at:

https://github.com/lodash/lodash/blob/master/.internal/root.js#L11

**Comment by 2-fly-4-ai** [comment]
I have the same issue. Lodash is not compatible with cloudflare pages experimental edge.

**Comment by 2-fly-4-ai** [comment]
> I traced it to `Function('return this')()` at:
> 
> https://github.com/lodash/lodash/blob/master/.internal/root.js#L11
 Did you manage to fix this? I tried removing lodash but it's a dependency in so many different packages. Tailwinds and everywhere else. This is a huge issue and the work to remove it from everything in my project is going to be a nightmare.

**Comment by jdalton** [comment]
Will update to using `globalThis` instead of `Function('return this')()`.

**Comment by paales** [comment]
Just ran into this as well! I've locally patched it to use globalThis and that at least allows it to run :) Would be really appreciated if this were to be changed. 😄

**Comment by karmaniverous** [comment]
I described a workaround for this [here](https://karmanivero.us/blog/lodash-nextjs-13-smh/).

TL/DR: individually-packaged functions like [lodash.isplainobject](https://www.npmjs.com/package/lodash.isplainobject) don't appear to break the Next.js build.

**Comment by Glavin001** [comment]
Adding `unstable_allowDynamic` to `config` worked for me:

```diff
 export const config = {
     runtime: "edge",
+    unstable_allowDynamic: [
+        '**/node_modules/lodash/_root.js', // use a glob to allow anything in the function-bind 3rd party module
+    ],
 };
```

**Comment by karmaniverous** [comment]
One of the things that will commonly break Next.js middleware is a logging package like [Winston](https://www.npmjs.com/package/winston). 

I imagine @Glavin001's solution would work there but with all due respect that kind of monkey-patching makes me itch.

So here's [a lightweight logging package](https://www.npmjs.com/package/@karmaniverous/edge-logger) that is guaranteed edge-safe and up to pretty much any task you throw at it.

**Comment by padawanR0k** [comment]
I'm utilizing middleware as well. In my scenario, I added the following code at the beginning of the middleware file, and it resolved the error:

```typescript
export const config = {
  runtime: 'experimental-edge',
  unstable_allowDynamic: [
    '**/node_modules/lodash-es/**/*.js',
  ],
};
```

By adding this configuration, I have enabled the "experimental-edge" runtime and allowed dynamic code evaluation for files within the `lodash-es` package. This resolves the issue related to dynamic code evaluation restrictions.

**Comment by benj-dobs** [comment]
> Will update to using `globalThis` instead of `Function('return this')()`.

Is this waiting for someone to implement the change, or is there something else blocking it?

**Comment by da7a90-backup** [comment]
I've had a similar issue but with jimp and pointing `unstable_allowDynamic` to the library in node modules works locally but not on production for some reason

**Comment by JonasDoe** [comment]
We cannot use `jsonwebtoken` in our middleware because of this. Would be great if it could be fixed soon!

**Comment by jsvelte** [comment]
Had the same problem in my Github Action during run build

**Comment by MarkShawn2020** [comment]
> Adding `unstable_allowDynamic` to Next.js API endpoint's `config` worked for me.
> 
> `api/<name>.js`:
> 
> ```diff
>  export const config = {
>      runtime: "edge",
> +    unstable_allowDynamic: [
> +        '**/node_modules/lodash/_root.js', // use a glob to allow anything in the function-bind 3rd party module
> +    ],
>  };
> ```

sorry, it just not work...
try `yarn build` and it would raise errors ...

**Comment by karmaniverous** [comment]
@MarkShawn2020 the edge runtime is seriously restricted as to what it can run. SOME `lodash` functions run dynamic code, which edge won't allow, but not all of them do.

Depending which `lodash` functions you want to run, you may be able to get around this by just importing the specific functions instead of the whole library.

**Comment by saurabhnemade** [comment]
I am getting error on following:

`../../node_modules/.pnpm/lodash.clonedeep@4.5.0/node_modules/lodash.clonedeep/index.js`

I can't use `jwt-decode` module in my middleware.

Tried following patterns but didn't seem to work:
```
    '**/node_modules/lodash-es/**/*.js',
    '**/**/node_modules/.pnpm/**/node_modules/**/index.js'
```

**Comment by ssbarbee** [comment]
What worked for me was:

```

export const config = {
  runtime: 'experimental-edge',
  unstable_allowDynamic: [
    '**/node_modules/lodash*/**/*.js',
  ],
};

```

Using nextjs 14.1.3. Notice `lodash*` to capture any lodash package

**Comment by MuhammadSawalhy** [comment]
> Using nextjs 14.1.3. Notice

Thanks @ssbarbee, upgrading fixed the problem!

**Comment by MuhammadSawalhy** [comment]
@jdalton Is this issue fixed? We are still facing it!

**Comment by JonasDoe** [comment]
> @jdalton Is this issue fixed? We are still facing it!

I figure he's rewriting lodash v5 from the scretch. I figure you've got to wait until there's a release.

**Comment by MuhammadSawalhy** [comment]
Can't wait for that 🥳

**Comment by agungsb** [comment]
Previously, in Next 14.1.3, the solution was:

```
export const config = {
  runtime: 'experimental-edge',
  unstable_allowDynamic: [
    '**/node_modules/lodash/lodash.js',
  ],
};
```

But in 14.2.3 it doesn't work. After wasting some times, I managed to make it work:

```
export const config = {
  unstable_allowDynamic: [
    '*lodash.js',
  ],
};
```

For your note, I use turborepo.

**Comment by terrymun** [comment]
Sharing the config that works for my team, who's using `lodash.*` packages such as `lodash.startCase`:

```ts
unstable_allowDynamic: ['**/node_modules/lodash.*/index.js'],
```
