### ISSUE TITLE
Lodash rewrite

### ISSUE THREAD

**Issue by viebel** [lodash/lodash#5526]
Could you give more information about the Lodash rewrite mentioned on [Twitter](https://twitter.com/jdalton/status/1571863497969119238)? 

In particular, I'd like to know whether the option to use immutable methods (like in Lodash FP) will be kept or not.

**Comment by jdalton** [comment]
Hi @viebel! The FP variant won't be kept.

**Comment by viebel** [comment]
Hello @jdalton 
Could you explain why you decided not to keep the immutable variants of the Lodash methods?

**Comment by zmaten** [comment]
What a pity. Well, Ramda it is then.
