### ISSUE TITLE
_.isEqual() report two different objects as equal.

### ISSUE THREAD

**Issue by bertolo1988** [lodash/lodash#5527]
```
const _ = require('lodash')

let input1 = Object.create(Object.prototype, {
  foo: {
    value: 'bar',
    writable: true
  }
})

const input2 = structuredClone(input1)

// input1.foo = 'bar'
// input2.foo = undefined
const comparison = _.isEqual(input2, input1)

console.log(comparison) // true
```

Using Node.js v18.8.0

Is there a good explanation for this? Seems like a bug to me.

**Comment by thetutlage** [comment]
I believe `isEqual` checks if two objects have same properties with same values and not if two objects shares the same memory pointer.

**Comment by acnebs** [comment]
That is exactly the purpose of `isEqual()`? If you want to check reference equality, you don't need lodash, you just do `input1 === input2`.
