### ISSUE TITLE
Two objects appear the same, why does isEqual return false

### ISSUE THREAD

**Issue by ggcespia** [lodash/lodash#5529]
Here is the JSON.stringify() of the 2 objects.  They appear identical, so why does isEqual return false?

[s1.txt](https://github.com/lodash/lodash/files/9670671/s1.txt)
[s2.txt](https://github.com/lodash/lodash/files/9670672/s2.txt)

**Comment by de-ar** [comment]
Seems just fine to me.

<img width="683" alt="image" src="https://user-images.githubusercontent.com/47880584/193410729-b5f6cee1-7066-4a39-baa5-dd8b620af47e.png">

**Comment by nlagdhir** [comment]
Working fine for me

![image](https://user-images.githubusercontent.com/17096384/193442180-dbb16af7-5132-4e4f-8df9-cd709bf6135c.png)

I am using latest version of lodash, its 4.17.21, 

@ggcespia with which version you are checking this?

**Comment by ggcespia** [comment]
I removed lodash due to the failure above and wrote my own function due to time constraints.  So, I don't have the version # I used.  Also, I realize JSON.stringify() works, but that is because the properties are in the same order.  I wanted to show that isEqual didn't work, even if the properties are in the same order.  I was using NodeJS 16 running on AWS Lambda.  I'll try to backtrack and get more information for you.

**Comment by pauldevson** [comment]
I am having a similar problem, been stuck here all day and found [this other issue](https://github.com/lodash/lodash/issues/2362) that says that prototypes/constructors matter in the comparison but even the solution proposed there (`_.create`) is not working for me 😞 I also tried a spread operator copy and doesn't work either.

```javascript
_.isEqual({ ...obj1 }, { ...obj2 })
```
I would really appreciate any clue on this.

**Comment by AsimAM** [comment]
help?

**Comment by de-ar** [comment]
> help?

What's up?
