### ISSUE TITLE
Outdated underscoreJS library

### ISSUE THREAD

**Issue by jasonmonroe** [lodash/lodash#5530]
The latest Lodash I'm using v4.17.21 is still using underscore.js v1.8.3 when the latest is v1.13.0.  Is LoDash going to update this library at all or do I need to replace lodash w/ underscore v1.13.0?

**Comment by millette** [comment]
@jasonmonroe [lodash has no dependencies](https://www.npmjs.com/package/lodash). It was written [based on underscore to replace it](https://github.com/lodash/lodash/blob/2f79053d7bc7c9c9561a30dda202b3dcd2b72b90/LICENSE#L5).
