### ISSUE TITLE
The cloneDeep method of lodash has serious performance bug

### ISSUE THREAD

**Issue by jerico-tech** [lodash/lodash#5535]
There is data with size about 15 MB in our system. Using the cloneDeep method of lodash, the execution time needs more than 45 seconds. As a result, the page is blank for a long time. We hope that the bug can be fixed ASAP.Thank you.

**Comment by rilysh** [comment]
Instead of lodash, you can also give it a try with `Object.assign`. However, there are a few more ways to clone objects. Or you can simply use the spread operator. I assume the performance issue happens with the recursive cloning with lodash.

**Comment by jdalton** [comment]
@jerico-tech I'd look for a more native solution. Try `structuredClone` available in browsers and Node 17.
