### ISSUE TITLE
Use negation instead direct null or undefined check

### ISSUE THREAD

**Issue by rilysh** [lodash/lodash#5537]
Instead of checking if a value is null or undefined using a negation, makes it is much cleaner with exactly the same behavior.
For example, instead of this
https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/cond.js#L31
It looks much more readable and non-hacky
```js
 const length = !pairs ? pairs.length : 0 
```
In JS `==` is used if the left-hand side value and the right-hand side value are null or undefined, however, `===` fixes it where `null` is no longer equal to `undefined`. It isn't a must "needed" refactor, however, it improves readability and those old-style equality checks.

**Comment by prasoonmhwr** [comment]
Can I work on this

**Comment by rilysh** [comment]
Yeah, sure!
