### ISSUE TITLE
website social media buttons look weird

### ISSUE THREAD

**Issue by ororsatti** [lodash/lodash#5542]
![Screen Shot 2022-10-27 at 10 40 17](https://user-images.githubusercontent.com/109456266/198221186-f655b229-8b77-4255-b213-e59b6dd0669b.png)

the image says it all. seems that they don't have enough height.
I'd be happy to fix that.

**Comment by saikiransathpadi** [comment]
https://github.com/lodash/lodash.com/pull/270
I have created a Pr fixing this issue.

**Comment by jdalton** [comment]
Thank you @saikiransathpadi!
