### ISSUE TITLE
1.255 x 100   bug!

### ISSUE THREAD

**Issue by 332lfgb6** [lodash/lodash#5546]
![image](https://user-images.githubusercontent.com/51245335/200256159-8cb82852-0129-4196-9ecd-36bcda298cb4.png)
```js
lodash.multiply(1.255, 100)
```

**Comment by 332lfgb6** [comment]
lodash.multiply

**Comment by alienzhangyw** [comment]
https://www.matthewburfield.com/javascript-deep-dive-floating-point-numbers/
