### ISSUE TITLE
forEach error

### ISSUE THREAD

**Issue by xdewx** [lodash/lodash#5548]
```js
import * as lodash from "lodash";

test("forEach-array", () => {
    let obj = {
        name: "id",
        type: "int",
         length: 6,
    }
    let obj2 = { a: false, b: false, c: false, d: false }
    lodash.forEach(obj, (v, k) => {
        console.log(k, v)
    })
})
```

I can't use length as key, if not , it will print :
0 undefined
1 undefined
2 undefined
3 undefined
4 undefined
5 undefined

**Comment by MikeWinter** [comment]
This isn't an error. It's well-defined behaviour. From [the documentation for `forEach`](https://lodash.com/docs/4.17.15#forEach):

> Note: As with other "Collections" methods, objects with a "length" property are iterated like arrays. To avoid this behavior use [_.forIn](https://lodash.com/docs/4.17.15#forIn) or [_.forOwn](https://lodash.com/docs/4.17.15#forOwn) for object iteration.

If you anticipate that you may have a `length` property in the objects you intend to iterate over, use one of the other functions.
