### ISSUE TITLE
When a field from array of object is omitted, the actual object is getting changed, instead of returning new new object.

### ISSUE THREAD

**Issue by jyellapu** [lodash/lodash#5557]
HI 

I'm trying to omit 'type' key from the contact info of employee details, instead of returning new object by omitting that key, it is observed that the original object in the array is getting changed.

For example :
const employeeDetails = {
  'name' : 'lodash',
  'contact': [{type: 'home', no: '1234'}]
}

_.omit(employeeDetails, 'contact[0].type')
console.log(employeeDetails)

Expected Behaviour : employeeDetails should not change, contact info should still contain type
Actual Behaviour :  'type' field is removed from the contact info of employee details.

output : { name: 'lodash', contact: [ { no: '1234' } ] }

**Comment by lanceheld** [comment]
Any progress on this one? We just ran into this unexpected behavior today.
