### ISSUE TITLE
Function 'sortedFindIndex' is missing

### ISSUE THREAD

**Issue by 1993alexey** [lodash/lodash#5559]
What is the suggested approach to finding the index of an element in a sorted array of objects? 

From what I understand, `findIndex` is not performing a binary search and that is expected. However, currently, there is no straightforward way to find an index of a complex array element. 

Here is a made-up example. Assume the array is sorted and contains thousands of elements. How do I find the index of an element with id 'x' using lodash with optimized binary search? I know I can add a binary search method to my utils file, but for such a common use case, it would make sense for it to be a part of this lib. 
```js
const array = [
   {
      id: 1,
      name: 'James',
   },
   {
      id: 2,
      name: 'Katie',
   }
]
```

There was [an attempt to fix this in 2016](https://github.com/lodash/lodash/pull/2427), but still no progress by the end of 2022?

**Comment by Jesse-Lucas1996** [comment]
@1993alexey Cause this is pretty much dead

**Comment by exarus** [comment]
Let's add this to make binary search feature-complete?
