### ISSUE TITLE
Core build throws `'get' is not a function` - introduced in 4.17.20

### ISSUE THREAD

**Issue by NickBolles** [lodash/lodash#5563]
The 4.17.20 build introduces an error thrown in the core build. 
https://github.com/lodash/lodash/commit/ded9bc66583ed0b4e3b7dc906206d40757b4a90a#diff-5dfc0b2e0b7e1ae97e4fe421ebcfaf90d99e8119a8cdc758fec1bc6045fdae35R1187-R1188

`stack` is not a `Stack` in the core build, it's an array, so the `get` function isn't defined. 
here's the stack trace
![image](https://user-images.githubusercontent.com/7891759/205555385-0ed1d331-023c-4a67-918e-71d6c1ef2742.png)
- IsEqual - https://github.com/lodash/lodash/blob/f299b52f39486275a9e6483b60a410e06520c538/dist/lodash.core.js#L2659-L2661
- baseIsEqual 
https://github.com/lodash/lodash/blob/f299b52f39486275a9e6483b60a410e06520c538/dist/lodash.core.js#L657-L665
- baseIsEqualDeep
https://github.com/lodash/lodash/blob/f299b52f39486275a9e6483b60a410e06520c538/dist/lodash.core.js#L657-L665
https://github.com/lodash/lodash/blob/f299b52f39486275a9e6483b60a410e06520c538/dist/lodash.core.js#L729
- equalObjects
https://github.com/lodash/lodash/blob/f299b52f39486275a9e6483b60a410e06520c538/dist/lodash.core.js#L1285
- Error Thrown
https://github.com/lodash/lodash/blob/f299b52f39486275a9e6483b60a410e06520c538/dist/lodash.core.js#L1303

# Code Sandbox Repro (Lodash 4.17.20)
https://codesandbox.io/s/vibrant-mayer-6x8nx5 (thank you @garethbowen )

# Code Sandbox Lodash 4.17.19 works
https://codesandbox.io/s/flamboyant-elgamal-z4uwq7?file=/src/index.js

**Comment by garethbowen** [comment]
@NickBolles You linked the same codesandbox twice... I forked one which reproduces the error here: https://codesandbox.io/s/vibrant-mayer-6x8nx5

What I don't understand is why this isn't getting more attention. I can't find a workaround - isEqual should be broken for comparing objects for everyone.

**Comment by NickBolles** [comment]
@garethbowen shoot. I must not have forked/saved the sandbox correctly. 

The key distinction here is the `core` build my guess is that it's not used very often?
