### ISSUE TITLE
Please add "equalBy" function

### ISSUE THREAD

**Issue by eugene-beliaev** [lodash/lodash#5565]
There was an older issue regarding this, but was closed: https://github.com/lodash/lodash/issues/3967

I still don't see any point why this function wasn't added. We have `isEqual` and `isEqualWith`, why not add `isEqualBy`, at least for consistency?

Personally I need this function to use in a couple of places in my project, and I'm sure I'm not alone who needs it as well

**Comment by poorna-prakash-sr** [comment]
Hi Eugene can explain in detail (more briefly) what is the use case of isEqualBy, so it can be helpful to add the function

**Comment by geareo** [comment]
you can already have it with primitives that lodash gives to you ...
