### ISSUE TITLE
[Question] : Multiple predicates for _.filter

### ISSUE THREAD

**Issue by AD1306** [lodash/lodash#5566]
Hello, I am trying to use lodash and I was wondering when we run multiple `_.filter()` against a data set, can we have a array of predicates as a parameter. 

For example (Current usage) : 
```
const cars = [
  { 'company': 'Honda', 'year': '2019', 'name': 'civic' },
  { 'company': 'Honda', 'year': '2020', 'name': 'civic' },
  { 'company': 'Hyundai', 'year': '2019', 'name': 'elantra' }
];
const civicFilterResult = _.filter(cars, { 'name': 'civic' }); <----- results for civic
const elantraFilterResult = _.filter(cars, { 'name': 'elantra' }); <---- results for elantra
```

Refactored usage : 

```
const cars = [
  { 'company': 'Honda', 'year': '2019', 'name': 'civic' },
  { 'company': 'Honda', 'year': '2020', 'name': 'civic' },
  { 'company': 'Hyundai', 'year': '2019', 'name': 'elantra' }
];
const filteredResults = _.filter(cars, [{ 'name': 'civic' }, { 'name': 'elantra' }]); <---- results for civic and elantra
```
**Note**: Keep in mind I don't mean I want `if(name === 'civic' && name === 'elantra')`, I want both of them in separate result sets. 

**Questions**

- Can the above be achieved in any different way ?
- If we do it the current way is there a performance hit with large data sets like 200 complex collections ? 

Let me know if something is not clear, I'm relatively new to lodash usage and was wondering if this is something possible. Thanks !

**Comment by mahdihadiam** [comment]
There is no implementation for your exact usage I mean multiple objects as parameter but you can do it easily with just an arrow function and your options as array:
`      const predicates = ['civic', 'elantra'];

      const cars = [
        { 'company': 'Honda', 'year': '2019', 'name': 'civic' },
        { 'company': 'Honda', 'year': '2020', 'name': 'civic' },
        { 'company': 'Hyundai', 'year': '2019', 'name': 'elantra' }
      ];

      const civic_elantra = _.filter(cars, o => {
        return predicates.includes(o.name)
      });
      // civic_elantra contains object with name civic or elantra`

**Comment by AD1306** [comment]
that makes sense. Thanks !
