### ISSUE TITLE
isEmpty(number)===true！！！！！！！！！！

### ISSUE THREAD

**Issue by z-jie-web** [lodash/lodash#5567]
isEmpty(number)===true
isEmpty 校验非0数值时  返回结果为true   为什么呀
建议快速修复

**Comment by funczh** [comment]
https://lodash.com/docs/4.17.15#isEmpty
你对这个方法的功能理解错了
![image](https://user-images.githubusercontent.com/16182130/206408820-f21d5232-95a4-40dc-9f03-f94afc7c6af6.png)

示例代码中就有你这个场景。
![image](https://user-images.githubusercontent.com/16182130/206408728-70c8b872-d45c-4dff-a17f-cec928d66afc.png)

**Comment by markuszeller** [comment]
Accordingly to the documentation that is correct, because 1 is either not a object, collection, map nor set and has an iterable length of size 0. So checking any values which are not that kind of type will result in true.

**Comment by arash-qc** [comment]
Assholeness + stupidness are combined in lodash maintainers

_.isEmpty(2342141234) must return false

_.isNormal(@jdalton) returning false because its checking only for objects and anything else is not Normal
