### ISSUE TITLE
lodash.merge npm package version still is 4.6.2 

### ISSUE THREAD

**Issue by neostfox** [lodash/lodash#5569]
[lodash.merge](https://www.npmjs.com/package/lodash.merge) still is 4.6.2
Version before 4.17.w are vulnerable to Prototype Pollution.
Should we update npm package or use lodash in node.js

**Comment by alaAicy** [comment]
你好，4.17版本之后merge是否还有原型污染吗？

**Comment by alaAicy** [comment]
Hello, is merge still contaminated with prototypes after 4.17?
