### ISSUE TITLE
Deprecate using lodash babel plugin

### ISSUE THREAD

**Issue by trajano** [lodash/lodash#5570]
Since `package.json` has indicated the module is `sideEffect: false` there shouldn't be a need for the babel plugin anymore as [tree shaking](https://webpack.js.org/guides/tree-shaking/) will remove the unused portions.

I have at least verified this to be the case in Expo when I did `eas update` and I got the same package size with the plugin and without the plugin enable.

**Comment by jdalton** [comment]
Nice!

**Comment by denkristoffer** [comment]
The babel plugin is still necessary if you use `lodash/fp`, otherwise you end up with both `lodash.js` and `lodash.min.js` in your bundle.

See https://github.com/lodash/lodash/issues/3079 and https://github.com/lodash/babel-plugin-lodash/issues/243
