### ISSUE TITLE
Missing https://github.com/lodash/lodash/wiki/build-differences

### ISSUE THREAD

**Issue by Querela** [lodash/lodash#5571]
The page linked with https://github.com/lodash/lodash/wiki/build-differences at
> Review the [build differences](https://github.com/lodash/lodash/wiki/build-differences) & pick one that’s right for you.

in the [README.md](https://github.com/lodash/lodash/blob/master/README.md) is missing.

**Comment by 2bam** [comment]
Also linked from the web page https://lodash.com/custom-builds

**Comment by jdalton** [comment]
Something odd happened. 🤔

**Comment by Melonfruity** [comment]
Hi @jdalton , could you assign this to me?
