### ISSUE TITLE
Missing `concat.js`

### ISSUE THREAD

**Issue by tzhangpccw** [lodash/lodash#5573]
in /test, there is `concat.js`
Line 3: import concat from '../concat.js';

but in the upper directory, there is no `concat.js`.

Please know, thanks. 

Error is like the 
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'lodash/concat.js' imported from "/lodash/test/concat.js". 
              
---------
  
<img src="https://user-images.githubusercontent.com/107375290/208830232-3e512070-74bd-453f-ac57-d6c21ffa79ef.png" width="400" height="350">

**Comment by chhongzh** [comment]
或许这些文件是给他们测试用的?
Maybe these files are for their testing? 

> 在 /test 中，有`concat.js` 第 3 行： import concat from '../concat.js';
> 
> 但是在上层目录中，没有`concat.js`.
> 
> 请知道，谢谢。
> 
> 错误类似于 错误 [ERR_MODULE_NOT_FOUND]：找不到从“/lodash/test/concat.js”导入的模块“lodash/concat.js”。
> 
> <img alt="" width="400" height="350" src="https://user-images.githubusercontent.com/107375290/208830232-3e512070-74bd-453f-ac57-d6c21ffa79ef.png">
