### ISSUE TITLE
_get returns undefined if a nested path contains an array value

### ISSUE THREAD

**Issue by MartynRobotham** [lodash/lodash#5574]
Hi,

For example if I have the following object

```
var object = {
  "ParentObject": {
    "/child|name": {
      "key": "/foobar"
    },
    "/child|flavour[0]": {
      "key": "/lime"
    }
  }
}

```
The following get function will return undefined

`_.get(object, "ParentObject./flavour[0]")`

If I do not include the [ character, the following function will work

`_.get(object, "ParentObject./child|name")`

However the following is valid

```
var object = {
  "ParentObject": {
    "/child|name": {
      "key": "/foobar"
    },
    "/flavour[0]": {
      "key": "/lime"
    }
  }
}

const abc = _.get(object, "ParentObject")

_.get(abc, "/flavour[0]")
```

Is it possible to get this working without having to break down the object if it contains that character when it is not the parent object

**Comment by thomasengels** [comment]
Hi, as a frequent user of lodash. This would be the perfect first issue I thought. Maybe it's because of the workings/focus on lodash v5 (see contribute.md) or error between keyboard and chair. But Changes to the source files (baseGet.js) do not result in changes in test. Does it have to be packaged or build before you can ran tests (besides the initial npm i)?

**Comment by MartynRobotham** [comment]
> Hi, as a frequent user of lodash. This would be the perfect first issue I thought. Maybe it's because of the workings/focus on lodash v5 (see contribute.md) or error between keyboard and chair. But Changes to the source files (baseGet.js) do not result in changes in test. Does it have to be packaged or build before you can ran tests (besides the initial npm i)?

Hi,

The way I tested this was through the REPL in the lodash docs here - https://lodash.com/docs/4.17.15#get, but I got the same result when running into the same issue in a React project.

**Comment by thomasengels** [comment]
The test I wrote using your input confirms your findings. it is an issue

**Comment by sampathshetty-sharechat** [comment]
Hi @MartynRobotham 
`_.get(object, ["ParentObject", "/child|flavour[0]" ])`

This should help

**Comment by MartynRobotham** [comment]
> var object = {
>   "ParentObject": {
>     "/child|name": {
>       "key": "/foobar"
>     },
>     "/flavour[0]": {
>       "key": "/lime"
>     }
>   }
> }
> 
> const abc = _.get(object, "ParentObject")
> 
> _.get(abc, "/flavour[0]")

Hi @sampathshetty-sharechat 

Thanks for this code snippet. It works for me and allows me to remove the nesting. It's probably worth adding this to the documentation although I admit it's an edge case
