### ISSUE TITLE
why my lodash cloneDeepWith method only run once?

### ISSUE THREAD

**Issue by iamPedram1** [lodash/lodash#5580]
I have a very very very deep nested object state.

and i want to change all id properties at once with lodash cloneDeepWith methods.

i'm using cloneDeepWith and only works on first match. if i dont return the modified object then it won't modifiy anything. and if i return the value i think the function stops. the function its working ok but the only problem is that only will run once.

```
  const handleChangeIds = (value) => {
    if (value === sections) {
      const modifiedObject = cloneDeepWith(value, (sectionsValue) => {

        if (sectionsValue && Object.hasOwn(sectionsValue, 'id')) {

          const clonedObj = cloneDeep(sectionsValue);
          clonedObj.id = generateObjectId();
          return clonedObj;

          // I Also Tried sectionsValue = clonedObj; its the same behavior 
        }
      });

      return modifiedObject;
    }
  };

  const handleDuplicateSection = () => {
    console.log('Original Store', form);
    const store = cloneDeepWith(form, handleChangeIds);
    console.log('Modified', store)
};

```

**Comment by mahdihadiam** [comment]
I think you should use destructuring at each phase:
`var objects = [[{ 'id': 1 }, { 'id': 1 }], { 'id': 1 }];

      function customizer(value) {
        if (typeof value === 'object' && Object.hasOwn(value, 'id')) {
          return { ...value, id: Math.trunc(Math.random() * 200) };
        };
      }

      var deep = _.cloneDeepWith(objects, customizer);`
