### ISSUE TITLE
Incorrect return type for minBy when input array is not empty

### ISSUE THREAD

**Issue by KieraDOG** [lodash/lodash#5586]
I am trying to use the `minBy` function from lodash with TypeScript and I have noticed that the return type is `T | undefined`, however, when the input array is not empty, I expect the function to always return a value of type `T`

```
interface SomType {
  value: number
}

const array: SomeType[] = [{ value: 2 }, { value: 3 }, { value: 4 }]

const minValue = _.minBy(array, 'value');

console.log(minValue) // { value: 2 }

// TypeScript infers the type of `minValue` as `SomeType | undefined`
// but I expect it to be `SomeType` since the input array is not empty
```

I would appreciate if the function could have the correct return type when the input array is not empty.

lodash@4.17.21
typescript@4.9.4

**Comment by JoelRomero97** [comment]
Quick fix could be

```
const minValue = _.minBy(array, 'value') as SomeType;
```
