### ISSUE TITLE
Allow array of function iteratees for minBy, maxBy like orderBy does

### ISSUE THREAD

**Issue by mbyrne00** [lodash/lodash#5593]
`orderBy` allows supplying an array of functions when extracting multiple fields to compare. 

But for quick illustrative purposes here is some simple usage with strings.

```typescript
const arr = ["zz", "aa", "abc", "zzz", "aaa", "bbb"];
orderBy(arr, [(x) => x.length, (x) => x]);

// Produces ['aa', 'zz', 'aaa', 'abc', 'bbb', 'zzz']
```

I'd like to do the following

```typescript
const arr = ["zz", "aa", "abc", "zzz", "aaa", "bbb"];
minBy(arr, [(x) => x.length, (x) => x]);

// Expected to produce 'aa', but produces 'zz'
```

**Comment by mbyrne00** [comment]
Hey @jdalton - what does the bankruptcy label mean, and does closing this issue mean that a release is forthcoming with a fix?

**Comment by jdalton** [comment]
The bankruptcy is meant to start fresh since it's been ~4yrs from the last release and I'm getting back into the swing of things it's not possible to address everything. Once the tech debt dust is brushed off features and requests will be taken again.
