### ISSUE TITLE
Feature request: provide `index` on map, each, ... as fourth argument

### ISSUE THREAD

**Issue by dorianmariefr** [lodash/lodash#5595]
e.g.

```js
parameters = {
  name: { kind: :string },
  pasword: { kind: :password }
}

_.map(parameters, (value, key, object, index) => {
  console.log(index)
})
```

would ouput

```js
0
1
```

**Comment by Hari-Shankar99** [comment]
Can you please tell me a use-case for the index param? Object is not iterated through any particular order. Its order is dependent on the engine which it runs. So i think there won't be any usecase for index.

**Comment by dorianmariefr** [comment]
For instance in a rails nested form, I need to have the index of the current key-value for the name and the id of the inputs

**Comment by dorianmariefr** [comment]
Current workaround is to do `Object.keys(object).indexOf(key)`
