### ISSUE TITLE
Reasoning behind _.lowerCase('YaYa--Ya_-BAR__');  not returning "yaya ya bar"?

### ISSUE THREAD

**Issue by project-tmg** [lodash/lodash#5601]
First time use this package.

Above question - what is the reasoning? currently returns "ya ya ya bar"
Is there another function that returns as "yaya ya bar"?

Thanks.

**Comment by PunitSoniME** [comment]
@project-tmg 

I have created an alternate of this `lodash` library.

You can get your expected result with my library,
Can you give it a try ?

Use `lowercase` method from `alt-lodash`

This is the package - https://www.npmjs.com/package/alt-lodash

This is Github repo - https://github.com/PunitSoniME/alt-lodash

Don't forget to give a star in github 🙂

Thanks

**Comment by eyfantis-signal** [comment]
@project-tmg 
Reasoning:
Accroding to `_.lowerCase` docs: 
"Converts string, `as space separated words`, to lower case."

Solution:
I cannot think of one function that gives you the desired output but you can combine `_.lowerCase` with `_.toLower` to get it, i.e. `_.lowerCase(_.toLower('YaYa--Ya_-BAR__'))`

**Comment by yfa-vagelis** [comment]
@project-tmg

Reasoning:
Accroding to `_.lowerCase` docs:
"Converts string, `as space separated words`, to lower case."

Solution:
I cannot think of one function that gives you the desired output but you can combine `_.lowerCase` with `_.toLower` to get it, i.e. `_.lowerCase(_.toLower('YaYa--Ya_-BAR__'))`
