### ISSUE TITLE
_.map doesn't iterate through object at all

### ISSUE THREAD

**Issue by jonathanturcotte** [lodash/lodash#5604]
I'm not sure what is causing this, but map works with most objects but not the one below:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/6924367/218584799-1896ea65-139c-4d02-9dd5-b9c88126d056.png">

I originally thought that _.map was skipping keys with falsey values, but that doesn't seem correct:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/6924367/218585032-8a1cdac9-edc9-43db-aefc-357972e2eaf1.png">

Any help is much appreciated!

**Comment by pratheshb** [comment]
@jonathanturcotte 

cause:
length property with value 0 in the object results in an Array of length 0 and doesn't invoke the callback function

**Comment by jonathanturcotte** [comment]
Ah, that explains it. I would expect lodash to check using `Array.isArray` or something before short circuiting because of `length: 0`. It looks to me that this project isn't really being maintained though...

**Comment by omarzawahry** [comment]
I've created a PR here that should resolve this issue: https://github.com/lodash/lodash/pull/5609
@falsyvalues any idea who can help with getting this merged?
