### ISSUE TITLE
is this repo no longer maintained?

### ISSUE THREAD

**Issue by artknight** [lodash/lodash#5605]
I am seeing the last commit was on April 2021. That's pretty long ago. Is this repo no longer maintained?

**Comment by jdalton** [comment]
Hi @artknight! It's monitored but not active. I've been recovering from burnout. Getting back into things slowly.

**Comment by ryan-ju** [comment]
https://thejs.dev/jmitchell/its-time-to-let-go-of-lodash-nqc

**Comment by mackwic** [comment]
@ryan-ju how funny, that the link you've given is referencing Core-js as an alternative to lodash. Do you know about its history? Please read it here: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md

While there are alternative libraries, there are no alternative for kindness, the fuel that power open source. Your message is both rude and ignorant. Do better when talking to forums with open source workers, please.

**Comment by OneHoopyFrood** [comment]
Hey @jdalton. Hope you're doing better man! Lodash is still super useful for a lot of cases, despite the platform maturing. I still love niceties like the casing methods (e.g. startCase, camelCase, etc.)

**Comment by Amantini1997** [comment]
Hi @jdalton, hope you got better since :)

I came here for the same reason as the @artknight, without knowing about your burnout. Just wanted to say, your library is amazing and I use it almost everyday, so, thank you!

**Comment by Firevvork** [comment]
Hi @jdalton, you're doing great. Remember to be kind to yourself.
