### ISSUE TITLE
why get({nickName:null},'nickName','-') is null ,why not is '-'

### ISSUE THREAD

**Issue by ohlyf** [lodash/lodash#5607]

**Comment by pratheshb** [comment]
the default value will be returned only if the resolved value is **undefined**.

**Comment by ohlyf** [comment]
> 

so  why not null，do you think the deferent of null and undefined

**Comment by pratheshb** [comment]
**undefined** will be returned when accessing values that don't exist(the value doesn't exist in the compiler)
**null** is the intentional absence of the value
