### ISSUE TITLE
typescript syntax check error

### ISSUE THREAD

**Issue by tangqiang0605** [lodash/lodash#5619]
Many interfaces of this library request that destructing an array is only one of the parameters, not the only one parameter. For example, I cannot use `default (... arr)`, but I must use `default ({},...arr)`, otherwise the syntax check will report an error. I sincerely hope that you can update these definition of the interface to suit this situation.

**Comment by ben-yocum** [comment]
Assuming you mean `defaults()`, you are correct. Its [current typing](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1e6a949794ce2711b6d6e340a74adea3605f123b/types/lodash/common/object.d.ts#L502) is:

```
defaults(object: any, ...sources: any[]): any;
```

It ought to be:

```
defaults(...objects: any[]): any;
```

(Really, `any` ought to be `object`, but at this point it's too late. Tons of people are surely already using the wrong way, and so it would be a breaking change.)

However, lodash is pretty much unmaintained. If you want to see your change, I suggest creating a PR yourself on [the typings package](https://github.com/DefinitelyTyped/DefinitelyTyped). If you want to see an example, you can check out other PRs, like [this one](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63331/files).
