### ISSUE TITLE
[Bug] Incorrect `undefined` return type for `_.sample()`

### ISSUE THREAD

**Issue by wenfangdu** [lodash/lodash#5620]
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZwIbgDYFM4F84BmUEIcA5BhACarIAWAtFsmQFCsDGEAdsvKnAC8KdGGwAKANoBGALoBKOOy68I2AHSUA5uIDUqRQHpDcQLwbgCR24MOsGRwOqbmXgAjHAAMArtypYCwbiwqdzgsADcsbis6CE8tOjh3PihgDhgAOU8MDABhOiwOAGtkENs4HlYgA)

### 💻 Code

```ts
import { sample } from 'lodash-es'

const a = sample([1]) 

console.log(+a) // 👈 this can't be `undefined` even though `strictNullChecks` is on
```

### 🙁 Actual behavior

TS throws `'a' is possibly 'undefined'`.

### 🙂 Expected behavior

TS doesn't throw.

**Comment by ben-yocum** [comment]
`undefined` is a valid return type for the `sample` function. Each of these always returns `undefined`:

```
sample(undefined);
sample(null);
sample([]);
sample([undefined]);
sample({});
sample("");
```

This will sometimes return `undefined`:

```
sample([1, undefined]);
```

You are correct that your specific example cannot return `undefined`, but Typescript typings do not differentiate in that way. You can see something similar with the built-in `Array.prototype.find`:

```
const result = [1].find(() => true);
console.log(+result); //'result' is possibly 'undefined'
```

**Comment by deepam-kapur** [comment]
Can I work on this?
