### ISSUE TITLE
isEmpty of number return true

### ISSUE THREAD

**Issue by hamcher** [lodash/lodash#5622]
Hi, why  isEmpty of any number return true
```js
_.isEpmty(5154)
```

**Comment by VeenaPD** [comment]
_.isEmpty() is used to check if the value passed is an empty `Object`, `String`, `collection`( if length as 0 it returns true),
`map`, or `set` (if size is 0 it returns true)

For `Number`, `Boolean`, `Null` data-types it always returns true

**Comment by codewithwaleed** [comment]
Logically that's right. @hamcher

**Comment by vaynevayne** [comment]
sb design, Is there a substitute for lodash in 2023?
