### ISSUE TITLE
Feature request: function that returns the object itself AND the index of and object inside and array

### ISSUE THREAD

**Issue by deleonjuan02** [lodash/lodash#5623]
eg: 
```
const array = [ {name: 'Jhon'},  {name: 'Susan'} ]

const [object, index] = findOne( ({name}) => name === "Susan" )

console.log(object)
// => {name: "Susan"}

console.log(index)
// => 1
```

**Comment by Sumit2342** [comment]
function findOne(conditionFn, array) {
  for (let i = 0; i < array.length; i++) {
    if (conditionFn(array[i])) {
      return [array[i], i];
    }
  }
  return [null, -1];
} 
Here is the implementation of findOne function. It takes the condition and the array.
