### ISSUE TITLE
Critical Security Issues Report In lodash

### ISSUE THREAD

**Issue by daudmalik06** [lodash/lodash#5626]
Dear maintainers,

I wanted to bring to your attention that the master branch of loadash has 10 vulnerabilities, with several being classified as high or critical. You can review these vulnerabilities at the following link: https://vulert.com/vuln-scan/list/50b83ad3-e881-4ef5-b03f-f1eb156b417a.

Would you please take a moment to review and update the package.json and package-lock.json accordingly?

p.s: we found these vulnerabilities through following lock file: https://github.com/lodash/lodash/blob/master/package-lock.json

Thank you for your attention to this matter.

**Comment by PunitSoniME** [comment]
@daudmalik06 

I have made an alternate of lodash library - https://www.npmjs.com/package/purekit
Github repo - https://github.com/PunitSoniME/purekit

Can you give it a try ?

A ⭐ would be appreciated 

Thanks
