### ISSUE TITLE
unset where path targets an array element does not shrink array

### ISSUE THREAD

**Issue by JakobJingleheimer** [lodash/lodash#5630]
This is the same issue that was reported and auto-closed without resolution in #3703:

```js
const source = { a: ['foo'] };

_.unset(source, 'a[0]');

console.log(source); // { a: [empty] }

console.log(source.a.length); // 1
```

The behaviour does match the util's name, but unset's documentation claims the item is removed; overwriting is not removing.

`_.omit` suffers the same issue, but the name also suggests the array should be compacted.

Leaving holes in the array causes problems that are difficult to track down.

**Comment by ryanzec** [comment]
Not sure is a fix is going to happen for this so mu work around is:

```js
const currentValue = lodash.get(draft, path);

currentValue.splice(removeIndex, 1);

lodash.set(draft, path, currentValue);
```

Not great but it works.
