### ISSUE TITLE
`pending` is set to `true` even when there are no "pendingInvokes" in debounce

### ISSUE THREAD

**Issue by JoSuzuki** [lodash/lodash#5633]
This is more of a question which may possibly be a bug.

I was using the debouce function present on [master](https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/debounce.js) specifically for the feature of `pending`.

The question is: Considering that a function `log` is debounced with `leading: true`, generating `logDebounced`. If `logDebounced` is called only once, during the `wait` period, should pending be `true` or `false`?

Currently it outputs `true`, but I believe that if there are no "pending invokes" it should output `false`. This would be helpful in cases where we are watching this variable to block navigation/show a loading state, since no more calls would be made we shouldn't need to wait for the `wait` time to expire.

The example in code is

```js
import debounce from "./debounce.js";

const WAIT = 1000;

const log = (text) => {
  console.log("log", text);
};

const logDebounced = debounce(log, WAIT, { leading: true });

logDebounced("1");

console.log(logDebounced.pending()); // outputs true

setTimeout(() => {
  console.log(logDebounced.pending());
}, WAIT);
```

**Comment by JoSuzuki** [comment]
A possible patch could be updating the pending function to watch for `lastArgs` (meaning it was called once after being invoked) and if it will call on `trailing`.

```js
function pending() {
  return timerId !== undefined && lastArgs && trailing;
}
```

I think that there is the argument that a `pendingTimer` concept also exists, where we need to see if any timer is currently running.

**Comment by anmol242** [comment]
> The example in code is
> 
> ```js
> import debounce from "./debounce.js";
> 
> const WAIT = 1000;
> 
> const log = (text) => {
>   console.log("log", text);
> };
> 
> const logDebounced = debounce(log, WAIT, { leading: true });
> 
> logDebounced("1");
> 
> console.log(logDebounced.pending()); // outputs true
> 
> setTimeout(() => {
>   console.log(logDebounced.pending());
> }, WAIT);
> ```

Hm, I agree the behavior you described, where logDebounced.pending() outputs true, is expected based on the implementation of the debounce function in `Lodash`. The pending function returns true if there are any pending invocations, regardless of whether they are yet to be executed or have already been executed during the wait period.

I can work on the fix if you want.
