### ISSUE TITLE
merge description doesn't quite match expected behavior when using multiple source parameters

### ISSUE THREAD

**Issue by VividLemon** [lodash/lodash#5634]
Take the following two examples
```ts
const foo = merge({bar: 'str'}, {bar: undefined})
```
According to the description: `Recursively merges own and inherited enumerable properties of source objects into the destination object, skipping source properties that resolve to undefined.`

So, as you would expect, `foo.bar = // 'str'`

However, this is not the case when using multiple sources:
```ts
const foo = merge({}, {bar: 'str'}, {bar: undefined})
```
In this case, `foo.bar = // undefined`

By the exact definition `skipping source properties that resolve to undefined`, 
![image](https://user-images.githubusercontent.com/31498096/233504660-91a4e67f-0702-4ae9-8a5b-b262dd3e5f9c.png)
If you do multiple, source is not actually a parameter, so the definition is correct.

However, I don't think this is actually intentional. I think the likely intention is that any parameter in each subsequent source parameter should be skipped.

This is a dilemma for me... as I actually don't want undefined to be skipped, so this behavior is preferable to me.

**Comment by VividLemon** [comment]
I'm not quite sure what bankruptcy label means but k

**Comment by jdalton** [comment]
Hi @VividLemon! It's been a few years. I'm declaring issue bankruptcy to clear the slate a bit.

**Comment by VividLemon** [comment]
It's possible that the definition of `skipping source properties that resolve to undefined` could refer to exact `undefined` or could be confused with `{someKey: undefined}` which in my case, would be why it would be incorrect. Though, I haven't tasted if exact `undefined` is skipped.

**Comment by jdalton** [comment]
@VividLemon I'm open to a PR to change the documentation (inline jsdoc on the module).

**Comment by VividLemon** [comment]
> @VividLemon I'm open to a PR to change the documentation (inline jsdoc on the module).

I'm not sure what the expected behavior is here, if my assessment that skipping pure `undefined` is correct and my confusion that skipping properties in an object is wrong. Or that I'm just missing "something".
