### ISSUE TITLE
Release lodash.trimend npm 4.17.21

### ISSUE THREAD

**Issue by dweitzman-codaio** [lodash/lodash#5643]
There's a security advisory telling people to upgrade to 4.17.21 (https://github.com/advisories/GHSA-29mw-wpgm-hmr9) but the most recent npm release is 4.5.1: https://www.npmjs.com/package/lodash.trimend

**Comment by guy-microsoft** [comment]
Any news about that?

**Comment by jineshjin** [comment]
Any updates on this?

**Comment by guy-microsoft** [comment]
Still relevant.
