### ISSUE TITLE
_.max does not cast to number

### ISSUE THREAD

**Issue by SimonLandeholm** [lodash/lodash#5644]
In plain old js `Math.max('1','2','11')` returns `11`
In lodash `_.max(['1','2','11'])` returns `'2'`

One could argue that type casting is not responsibility of lodash like in this [slightly condescending conversation](https://github.com/lodash/lodash/issues/3477). **Which is correct.**

However in the lodashian spirit of erroneous types one should expect lodash to return `undefined` whenever the arguments result in an ambiguous answer, like when doing `_.last` of `Infinity` etc. Either this, or not have this function under the "Math" section. Maybe rename it to `compareAndGetLastElementInArray` or something and not let it pose as a drop-in replacement for `Math.max`.

In addition if you mix the types:
`_.max(['1',3,'2','11'])` it _correctly_ returns '11'

But if you throw in a 0 in there:
`_.max(['1',0,'2','11'])` it retorts back to '2' again

Negative number extort the same behaviour:
`_.max(['1',-4,'2','11'])` => '2'

All in all thank you for a great and extremely delightful library, however I'll probably look at other libs for math operations in the future.

**Comment by deepam-kapur** [comment]
Can I work on this?
