### ISSUE TITLE
intersectionWith([arrays], [comparator]) comparator  second param type of comparator is never

### ISSUE THREAD

**Issue by TaurusWood** [lodash/lodash#5645]
I need to take the intersection of multiple array objects, and the length of the array is uncertain. Each object needs to have the same two Keys of `name` and `type` to take the intersection. So I used lodash's intersectionWith method.

```javascript
const data = [
  [
    { name: 'a', type: 'string' },
    { name: 'b', type: 'number' },
    { name: 'c', type: 'date' },
  ],
  [
    { name: 'a', type: 'string' },
    { name: 'f', type: 'number' },
    { name: 'c', type: 'date' },
  ],
  [
    { name: 'a', type: 'string' },
    { name: 's', type: 'number' },
    { name: 'c', type: 'date' },
  ],
  [
    { name: 'a', type: 'string' },
    { name: 's', type: 'number' },
    { name: 'c', type: 'date' },
  ],
];


const res = intersectionWith(...data, (a, b) => {
  console.log(a, b)
  return a.name === b.name && a.type === b.type
})

console.log('res', res)
```

In this example, the running result is correct, but ts will report an error: Property 'name' does not exist on type 'never'.ts(2339)

Then I checked the function signature of the intersectionWith method in the lodash source code：

``` typescript
interface LoDashStatic {
        /**
         * Creates an array of unique `array` values not included in the other
         * provided arrays using [`SameValueZero`](http://ecma-international.org/ecma-262/6.0/#sec-samevaluezero)
         * for equality comparisons.
         *
         * @category Array
         * @param [values] The arrays to inspect.
         * @param [comparator] The comparator invoked per element.
         * @returns Returns the new array of filtered values.
         * @example
         *
         * var objects = [{ 'x': 1, 'y': 2 }, { 'x': 2, 'y': 1 }];
         * var others = [{ 'x': 1, 'y': 1 }, { 'x': 1, 'y': 2 }];

         * _.intersectionWith(objects, others, _.isEqual);
         * // => [{ 'x': 1, 'y': 2 }]
         */
        intersectionWith<T1, T2>(array: List<T1> | null | undefined, values: List<T2>, comparator: Comparator2<T1, T2>): T1[];
        /**
         * @see _.intersectionWith
         */
        intersectionWith<T1, T2, T3>(array: List<T1> | null | undefined, values1: List<T2>, values2: List<T3>, comparator: Comparator2<T1, T2 | T3>): T1[];
        /**
         * @see _.intersectionWith
         */
        intersectionWith<T1, T2, T3, T4>(array: List<T1> | null | undefined, values1: List<T2>, values2: List<T3>, ...values: Array<List<T4> | Comparator2<T1, T2 | T3 | T4>>): T1[];
        /**
         * @see _.intersectionWith
         */
        intersectionWith<T>(array?: List<T> | null, ...values: Array<List<T> | Comparator2<T, never>>): T[];
    }
```

Is this a type definition error? If not, then why use never for the type here, after all, from the running results of the example, its type is the element of the array

**Comment by anmol242** [comment]
hey @TaurusWood I think the current way is to explicitly infer the type with intersectWith and explicitly specify the type of each element in the arrays within the intersectionWith call. Here is the sample code:

```
import { intersectionWith } from 'lodash';

interface DataItem {
  name: string;
  type: string;
}

const data: DataItem[][] = [
  [
    { name: 'a', type: 'string' },
    { name: 'b', type: 'number' },
    { name: 'c', type: 'date' },
  ],
  [
    { name: 'a', type: 'string' },
    { name: 'f', type: 'number' },
    { name: 'c', type: 'date' },
  ],
  [
    { name: 'a', type: 'string' },
    { name: 's', type: 'number' },
    { name: 'c', type: 'date' },
  ],
  [
    { name: 'a', type: 'string' },
    { name: 's', type: 'number' },
    { name: 'c', type: 'date' },
  ],
];

const res = intersectionWith<DataItem>(
  ...data,
  (a: DataItem, b: DataItem) => a.name === b.name && a.type === b.type
);

console.log('res', res);
```

**Comment by anmol242** [comment]
> 



> I need to take the intersection of multiple array objects, and the length of the array is uncertain. Each object needs to have the same two Keys of `name` and `type` to take the intersection. So I used lodash's intersectionWith method.
> 
> ```js
> const data = [
>   [
>     { name: 'a', type: 'string' },
>     { name: 'b', type: 'number' },
>     { name: 'c', type: 'date' },
>   ],
>   [
>     { name: 'a', type: 'string' },
>     { name: 'f', type: 'number' },
>     { name: 'c', type: 'date' },
>   ],
>   [
>     { name: 'a', type: 'string' },
>     { name: 's', type: 'number' },
>     { name: 'c', type: 'date' },
>   ],
>   [
>     { name: 'a', type: 'string' },
>     { name: 's', type: 'number' },
>     { name: 'c', type: 'date' },
>   ],
> ];
> 
> 
> const res = intersectionWith(...data, (a, b) => {
>   console.log(a, b)
>   return a.name === b.name && a.type === b.type
> })
> 
> console.log('res', res)
> ```
> 
> In this example, the running result is correct, but ts will report an error: Property 'name' does not exist on type 'never'.ts(2339)
> 
> Then I checked the function signature of the intersectionWith method in the lodash source code：
> 
> ```ts
> interface LoDashStatic {
>         /**
>          * Creates an array of unique `array` values not included in the other
>          * provided arrays using [`SameValueZero`](http://ecma-international.org/ecma-262/6.0/#sec-samevaluezero)
>          * for equality comparisons.
>          *
>          * @category Array
>          * @param [values] The arrays to inspect.
>          * @param [comparator] The comparator invoked per element.
>          * @returns Returns the new array of filtered values.
>          * @example
>          *
>          * var objects = [{ 'x': 1, 'y': 2 }, { 'x': 2, 'y': 1 }];
>          * var others = [{ 'x': 1, 'y': 1 }, { 'x': 1, 'y': 2 }];
> 
>          * _.intersectionWith(objects, others, _.isEqual);
>          * // => [{ 'x': 1, 'y': 2 }]
>          */
>         intersectionWith<T1, T2>(array: List<T1> | null | undefined, values: List<T2>, comparator: Comparator2<T1, T2>): T1[];
>         /**
>          * @see _.intersectionWith
>          */
>         intersectionWith<T1, T2, T3>(array: List<T1> | null | undefined, values1: List<T2>, values2: List<T3>, comparator: Comparator2<T1, T2 | T3>): T1[];
>         /**
>          * @see _.intersectionWith
>          */
>         intersectionWith<T1, T2, T3, T4>(array: List<T1> | null | undefined, values1: List<T2>, values2: List<T3>, ...values: Array<List<T4> | Comparator2<T1, T2 | T3 | T4>>): T1[];
>         /**
>          * @see _.intersectionWith
>          */
>         intersectionWith<T>(array?: List<T> | null, ...values: Array<List<T> | Comparator2<T, never>>): T[];
>     }
> ```
> 
> Is this a type definition error? If not, then why use never for the type here, after all, from the running results of the example, its type is the element of the array

hey @TaurusWood I think the current way is to explicitly infer the type with intersectWith and explicitly specify the type of each element in the arrays within the intersectionWith call. Here is the sample code:

```
import { intersectionWith } from 'lodash';

interface DataItem {
  name: string;
  type: string;
}

const data: DataItem[][] = [
  [
    { name: 'a', type: 'string' },
    { name: 'b', type: 'number' },
    { name: 'c', type: 'date' },
  ],
  [
    { name: 'a', type: 'string' },
    { name: 'f', type: 'number' },
    { name: 'c', type: 'date' },
  ],
  [
    { name: 'a', type: 'string' },
    { name: 's', type: 'number' },
    { name: 'c', type: 'date' },
  ],
  [
    { name: 'a', type: 'string' },
    { name: 's', type: 'number' },
    { name: 'c', type: 'date' },
  ],
];

const res = intersectionWith<DataItem>(
  ...data,
  (a: DataItem, b: DataItem) => a.name === b.name && a.type === b.type
);

console.log('res', res);
```
