### ISSUE TITLE
Add any example at all for using lodash-es to the README

### ISSUE THREAD

**Issue by TheJaredWilcurt** [lodash/lodash#5646]
There are no instructions on how to install and use `lodash-es`. Since it is a different module, and different import system, there should be at least one example of how to import something from lodash (`_startcase`, `_xorby`, whatever).

* https://www.npmjs.com/package/lodash-es

**Comment by TheJaredWilcurt** [comment]
Here's what I got working for anyone else ending up here:

`npm install --save lodash-es`

```js
import _startCase from 'lodash-es/startCase.js';

console.log(_startCase('fooBar')); // 'Foo Bar'
```

**Comment by smckinney1** [comment]
Agreed, this would be appreciated!
