### ISSUE TITLE
_.defaults won't work as expected when provided with undefined (suggestion)

### ISSUE THREAD

**Issue by jrencz** [lodash/lodash#565]
There's a case:

``` javascript
function provideArgumentWithDefaults (argument) {
    _.defaults(argument, {
        foo: 'bar',
    });
    return argument;
}
```

If `argument` is undefined (one want to create an object with only the default properties) undefined will be returned without the properties which are supposed to be default.
The solution is off course to initialise the new object like this:

``` javascript
function provideArgumentWithDefaults (argument) {
    argument = argument || {}
    _.defaults(argument, {
        foo: 'bar',
    });
    return argument;
}
```

or like this:

``` javascript
function provideArgumentWithDefaults (argument) {
    _.defaults(argument || {}, {
        foo: 'bar',
    });
    return argument;
}
```

What would be nice is something like:

```
_.defaults(object, [source], [initialObject])
```

then instead of doing it manually one could write:

``` javascript
function provideArgumentWithDefaults (argument) {
    _.defaults(argument, {
        foo: 'bar',
    }, {});
    return argument;
}
```

**Comment by MichaelJCole** [comment]
+1 for noting the undefined behavior with an example.  

_.defaults({}, possiblyUndefined, { 'foo': 'bar' })

**Comment by ruimarinho** [comment]
I'm also of the opinion that there is an edge case with `undefined` values on `_.defaults`. For consistency, shouldn't `_.extend({ 'foo': 'bar' }, undefined)` behave similarly to `_.defaults({ 'foo': 'bar' }, undefined)`?

**Comment by jdalton** [comment]
> For consistency, shouldn't _.extend({ 'foo': 'bar' }, undefined) behave similarly to _.defaults({ 'foo': 'bar' }, undefined)?

It does. Empty `source` objects are skipped.

I've clarified the docs more [here](https://github.com/lodash/lodash/commit/d56a8e64162f4db26ef039209ffec25f98c1c644).

**Comment by ruimarinho** [comment]
Indeed. What I actually wanted to know was if `_.defaults(undefined, { foo: 'bar' })` should return `{ foo: 'bar' }` instead, even though the destination object is undefined. Although in that case, I'd rather use `_.defaults({}, undefined, { 'foo': 'bar' })` anyway.

**Comment by jdalton** [comment]
> Indeed. What I actually wanted to know was if `_.defaults(undefined, { foo: 'bar' })` should return `{ foo: 'bar' }` instead

Naw, we pass the `object` param through regardless of what it is.

**Comment by markstos** [comment]
I got bit by this again today. I saw the documentation update, but I think an explicit mention about `defaults()` and `undefined` would be helpful. 

I had a done a refactor like this:

```javascript
     var foo = _.extends(defaults, options);
     // ... became
     var foo = _.defaults(options, defaults);
```

From the current documentation, it appear that these two functions work basically the same, but with the arguments in the reverse order, but the current docs are not clear on the point that they differ in how `undefined` values are handled. The `extends()` syntax will work with `options` being `undefined`. However, the `defaults()` syntax will return an `undefined` value when `options` is undefined, requiring the workaround:

```javascript
     var foo = _.defaults({}, options, defaults);
```

At least, that's how it works with 2.2. I found no ChangeLog to see if there was  documented change in behavior in how `defaults()` work in 3.0. I opened a separate issue to request documentation on the differences in major version changes.

**Comment by jdalton** [comment]
I'm satisfied with the documentation though I may add that *"`_.defaults` is like `_.extend` except..."* similar to other like methods. The `_.defaults` method is implemented by way of `_.extend` so as it turns out both are consistent with how the `object` param falls through.

**Comment by wprl** [comment]
"Bitten" by this as well.

**Comment by jdalton** [comment]
In another thread I'm discussing an immutable flavor of `assign`, `defaults`, and `merge`. If you all could bikeshed a name that would help. Ex: `assignNew` or `assignImm` or `assignCopy`.

**Comment by markstos** [comment]
I won't include the word `New` which evokes a typical constructor. 

Evoking immutability is good, but the "Imm" prefix won't be clear to some.

`Copy` also evokes the idea  the original is not mutated, while also being short and clear. 

I'm voting for `assignCopy`.

**Comment by StreetStrider** [comment]
@markstos, `New` postfix is ugly as any other postfix. So it's in equal rights with others like `Copy` or any other crap.

**Comment by jdalton** [comment]
> or any other crap.

@StreetStrider I like your style :)
