### ISSUE TITLE
sortBy nor orderBy not working properly

### ISSUE THREAD

**Issue by igortas** [lodash/lodash#5650]
Hi,
Nor sortBy, nor orderBy, sorts the data in single table column, asc or desc properly (also the data have empty strings). Column is out of order, only the empty strings goes on top or on the bottom, asc/desc.

```
    orderBy(
    items,
      [
        (item: T, index: number) =>
          item.someArray[
            index
          ]?.moreNested[0]?.moreMoreNested[0]?.toLowerCase(),
        '',
      ],
      'asc'
    );
```

Data is shown is presented like this:

```

Column
---
NULL (means empty cell)
new document 11 2222
Gggg Noc Doc
iiii 123
```

Expected result, iiii 123 to be in the middle

**Comment by bendytree** [comment]
Just ran into this as well. For some reason, sortBy does not receive the key (index in this case):

[          return iteratee(value);](https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L3727)
