### ISSUE TITLE
Command Injection | lodash.template

### ISSUE THREAD

**Issue by rinstonsi** [lodash/lodash#5654]
found a vulnerability in module: lodash.template
Introduced through: final@6.0.1, nuxt@2.15.8 and others

Affected versions of this package are vulnerable to Command Injection via {{{}template{}}}.

h3. Detailed paths

{_}Introduced through{_}: final@6.0.1 ‚Ä∫ nuxt@2.15.8 ‚Ä∫ @nuxt/vue-renderer@2.15.8 ‚Ä∫ vue-server-renderer@2.6.14 ‚Ä∫lodash.template@4.5.0

{_}Introduced through{_}: final@6.0.1 ‚Ä∫ nuxt@2.15.8 ‚Ä∫ @nuxt/server@2.15.8 ‚Ä∫ @nuxt/vue-renderer@2.15.8 ‚Ä∫ vue-server-renderer@2.6.14 ‚Ä∫ lodash.template@4.5.0

{_}Introduced through{_}: final@6.0.1 ‚Ä∫ nuxt@2.15.8 ‚Ä∫ @nuxt/core@2.15.8 ‚Ä∫ @nuxt/server@2.15.8 ‚Ä∫ @nuxt/vue-renderer@2.15.8 ‚Ä∫ vue-server-renderer@2.6.14 ‚Ä∫ lodash.template@4.5.0

can someone help me with this ?

**Comment by agirorn** [comment]
I think PR #5649 fixes this issue.

**Comment by JBustin** [comment]
Hello, this vulnerability detected for this lib has been updated: https://github.com/advisories/GHSA-35jh-r3h4-6jhm
It is now with a high severity.
https://github.com/github/advisory-database/commit/8f5ec32f378584526935420e3156df155edbc759
Is it possible to fix ?

Regards

**Comment by Trott** [comment]
> Is it possible to fix ?

For what it's worth, it's fixed if you use `lodash` rather than `lodash.template`. If I understand correctly, [people are discouraged from using the individual method packages and they do not receive updates](https://github.com/lodash/lodash/issues/3838) (although I don't know if exceptions are made for high-severity vulnerabilities).

**Comment by Trott** [comment]
> If I understand correctly, [people are discouraged from using the individual method packages and they do not receive updates](https://github.com/lodash/lodash/issues/3838) (although I don't know if exceptions are made for high-severity vulnerabilities).

Better link: https://lodash.com/per-method-packages
