### ISSUE TITLE
_.set method did not work as expected.

### ISSUE THREAD

**Issue by ShaofeiZi** [lodash/lodash#5655]
`_.set({},['abc', '300000002'],true)`
### As expected, the data at path object.abc.300000002 should be true. 

![image](https://github.com/lodash/lodash/assets/19340899/23afdfb5-a8a8-476e-a90f-94c21a757f73)

### However, in reality, an array of 300000003 empty elements was created at path object.abc.
![image](https://github.com/lodash/lodash/assets/19340899/855539f3-dbb2-4760-b13d-62fedb11f4ce)

![image](https://github.com/lodash/lodash/assets/19340899/c4a8db26-5c90-4866-ac4e-f00433530d20)

### I tried to convert the path into a string, but got the same result.
![image](https://github.com/lodash/lodash/assets/19340899/967606d2-abe5-43ce-ab00-61794501464a)

**Comment by thomas-reinhold-de** [comment]
Please try this.
```js
var object = {};

_.setWith(object, '[abc][300000002]',true, Object)
```

**Comment by Nmans01** [comment]
> Please try this.
> 
> ```js
> var object = {};
> 
> _.setWith(object, '[abc][300000002]',true, Object)
> ```

This worked for me. For a dynamic array of strings as a path, I'd recommend .join("][") and wrapping the result with "[" and "]".
