### ISSUE TITLE
_.sortedUniq does not work

### ISSUE THREAD

**Issue by xiaorunbao** [lodash/lodash#5662]
![image](https://github.com/lodash/lodash/assets/44248303/d78dbbab-69ab-4e84-a33c-ceb3cd259ed9)

`
const array = ['1111_0005_2023-06-08', '1111_0005_2023-06-09', '1111_0002_2023-06-08','2222_0005_2023-06-08', '1111_0005_2023-06-09','1111_0005_2023-06-08'];
_.sortedUniq(array);
`

result:
**0: "1111_0005_2023-06-08"**
1: "1111_0005_2023-06-09"
2: "1111_0002_2023-06-08"
3: "2222_0005_2023-06-08"
4: "1111_0005_2023-06-09"
**5: "1111_0005_2023-06-08"**

**Comment by urucualex** [comment]
`_.sortedUniq` expects the array to be sorted.

This works as expected:
```
const array = _.sortBy(['1111_0005_2023-06-08', '1111_0005_2023-06-09', '1111_0002_2023-06-08','2222_0005_2023-06-08', '1111_0005_2023-06-09','1111_0005_2023-06-08']); 
console.error(
	_.sortedUniq(array)
);
```
