### ISSUE TITLE
Why are variables still defined with 'var' instead of 'let' and 'const'

### ISSUE THREAD

**Issue by ChenKun1997** [lodash/lodash#5663]

**Comment by rahul-adnabu** [comment]
Can i work on this issue, to replace all vars with let or const ?

**Comment by blikblum** [comment]
Why? Is valid code

**Comment by Rantoledo** [comment]
Not sure about that, but I think it's mainly because there are some old versions of different browsers that do not support let and const, therefore using var is necessary.

**Comment by gvozdenkov** [comment]
@ChenKun1997 performance issue. Let/const have bad performance. Look at Static Semantics stage in EcmaScript.
