### ISSUE TITLE
Shouldn't mergeWith work recursively?

### ISSUE THREAD

**Issue by telmaantunes** [lodash/lodash#5666]
Shouldn't mergeWith work recursively? 

This is what I tested
<img width="1064" alt="Screenshot 2023-06-15 at 16 29 28" src="https://github.com/lodash/lodash/assets/8360946/0fb5b8bc-04e0-47fc-bf39-585e4f5a00bb">

I assumed it should return 
```
{
  'a': [{ 'b': 3 }, { 'd': { 'd1': 'a'  } }],
  'a2': '2',
  'a3': { 'aa': 'x'  }
};
```

If this a bug or should I be using a different function?

**Comment by msuraj11** [comment]
Hello @telmaantunes , As per documentation, it is clear that 'objValue' in the customiser function refers to the object1's 1st value for 1st iteration key i.e `[{ 'b': 2}, { 'd': { 'd1': 'a'  } }]` , where as srcValue would be `[{ 'b': 3 }, { 'd': { 'd1': undefined  } }]`.

for your condition `_.isNil(srcValue) || (_.isObjectLike(srcValue) && _isEmpty(srcValue))` the output would be `false` hence returns srcValue.

**Summary**:
Lodash doesn't check the inner object properties whether it is null or undefined directly in this case. we have to dive inside the array/object to check if they are not null and then you can decide how your merger should return.

I hope, I provided a clear picture. :)

**Comment by telmaantunes** [comment]
Thanks @msuraj11
