### ISSUE TITLE
Cancelling a debounced call

### ISSUE THREAD

**Issue by PaulTondeur** [lodash/lodash#567]
It would be great if there were a way to cancel a debounced call. Say the debounced method is called, it waits 1second before it gets executed, however before it gets executed the object on which the original method exists has to be destroyed getting you into problems with destroying the object and even keeping the GC from cleaning it up.

To get around this it would be good if we could cancel a potentially running debounced call by internally clearing the timeout id.

**Comment by swernerx** [comment]
Was this removed from newest Lodash versions?

Lodash-2.4.1:
_.debounce(function() {}).cancel ==> undefined

Because it's still in the docs. Just wondering. Thanks for feedback.

**Comment by jdalton** [comment]
@swernerx I can't repro. v2.4.1 did not have `cancel` and in v3.x I get
```js
typeof _.debounce(function() {}).cancel // => 'function'
```

**Comment by swernerx** [comment]
Okay, so it was introduced in 3.x - I may have confused this. That's quite unfortunate... would be a great nice addition to the 2.x version line.

**Comment by jdalton** [comment]
> That's quite unfortunate... would be a great nice addition to the 2.x version line.

It's 2015, throw modules at it. You can use [lodash.debouce](https://www.npmjs.com/package/lodash.debounce) of v3 combo'd with lodash v2.
