### ISSUE TITLE
Lodash range RangeError

### ISSUE THREAD

**Issue by jcan1995** [lodash/lodash#5678]
Large `end` param numbers throw a RangeError. The error seems to be thrown from [baseRange](https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/.internal/baseRange.js#L12) method.

Ex: _.range(0, 198863445)
![Screenshot 2023-07-12 at 1 47 51 PM](https://github.com/lodash/lodash/assets/10763136/30a08a5c-fb2f-4848-9fd0-8caa180625b0)

**Comment by kaz1ngton** [comment]
Unfortunately, I don't see any simple solution for this bug. It's easy to handle `RangeError`, but after this step other issues like "Heap out of memory" or "Fatal JavaScript invalid size error" may occur when working with very large arrays.

As pointed out, the original issue (`RangeError`) involves attempting to create an extremely large array with more than 100 million items, and this exceeds the maximum array size that JavaScript can handle.

One attempted solution was to slice the array into chunks to avoid creating a single massive array, but this didn't entirely resolve the issue, and the [Fatal JavaScript invalid size error](https://github.com/nodejs/help/issues/3728) persisted.
