### ISSUE TITLE
isEqual with class object and anonymous object

### ISSUE THREAD

**Issue by robokozo** [lodash/lodash#5679]
According to the isEqual documentation (https://lodash.com/docs/4.17.15#isEqual):

> Performs a deep comparison between two values to determine if they are equivalent.

> Note: This method supports comparing arrays, array buffers, booleans, date objects, error objects, maps, numbers, Object objects, regexes, sets, strings, symbols, and typed arrays. **_Object objects are compared by their own, not inherited, enumerable properties_**. Functions and DOM nodes are compared by strict equality, i.e. ===.

if you have

```
class A {
    constructor(){
        this.a = 1
    }
}

const first = new A()

const second = { a: 1 }

const answer = _.isEqual(first, second) // false
```

Based on the description of the function in the documentation, I would expect `answer` to be true but it returns false.

My current work-around is to stringify and parse the object before passing it into isEqual. 

```
_.isEqual(JSON.parse(JSON.stringify(first)), JSON.parse(JSON.stringify(second)))
```

I think this should be fixed in code or the documentation should be made more clear.

**Comment by kaz1ngton** [comment]
> Non `Object` object instances with different constructors are not equal.

You're right, the documentation doesn't cover that point.
