### ISSUE TITLE
cloneDeep problem vue3

### ISSUE THREAD

**Issue by Mrcheng66** [lodash/lodash#5680]
when params is reactive from sub component in parent component use cloneDeep handel this params.  params like this : const arr = [
    {
        storeCode: '021',
        roomtypeForms: [
            {
                price: 122,
                personalPay: 122,
                aheadClearingForm: 2,
                aheadDayPrice: 122,
                aheadPersonalPay: 122,
                aheadClearingFormSpan: 2,
            },
            {
                price: 122,
                personalPay: 122,
                aheadClearingForm: 2,
                aheadDayPrice: 122,
                aheadPersonalPay: 122,
                aheadClearingFormSpan: 0,
            },
        ],
    },
    {
        storeCode: '022',
        roomtypeForms: [
            {
                price: 122,
                personalPay: 122,
                aheadClearingForm: 2,
                aheadDayPrice: 122,
                aheadPersonalPay: 122,
                aheadClearingFormSpan: 2,
            },
            {
                price: 122,
                personalPay: 122,
                aheadClearingForm: 2,
                aheadDayPrice: 122,
                aheadPersonalPay: 122,
                aheadClearingFormSpan: 0,
            },
        ],
    },
    {
        storeCode: '023',
        roomtypeForms: [
            {
                price: 122,
                personalPay: 122,
                aheadClearingForm: 2,
                aheadDayPrice: 122,
                aheadPersonalPay: 122,
                aheadClearingFormSpan: 2,
            },
            {
                price: 122,
                personalPay: 122,
                aheadClearingForm: 2,
                aheadDayPrice: 122,
                aheadPersonalPay: 122,
                aheadClearingFormSpan: 0,
            },
        ],
    },
]  
const transformRoomtypeForms = (arr, propertiesToTransform) => {
    for (let i = 0; i < arr.length; i++) {
        const ele = arr[i]
        if (ele.roomtypeForms.length === 0) {
            continue
        }
        for (let j = 0; j < ele.roomtypeForms.length; j++) {
            const room = ele.roomtypeForms[j]
            if (room.price && room.aheadClearingForm && room.aheadDayPrice) {
                transformProperties(room, propertiesToTransform)
            } else {
                return false
            }
        }
    }
    return true
}

const transformProperties = (room, props) => {
    props.forEach((prop) => {
        if (room[prop]) {
            room[prop] *= 100 // 修正：应该除以 100
        } else {
            room[prop] = 0
        }
    })
}

const getFrameContractInfo = (obj) => {
    const info = cloneDeep(obj)
    // const info = JSON.parse(JSON.stringify(obj))
    transformRoomtypeForms(
        info.addTeamContractOrderForms,
        propertiesToTransform
    )
    console.log(info.addTeamContractOrderForms)
    transformRoomtypeForms(arr, propertiesToTransform)
    console.log(arr)
    }
    use this function to transformProperties, This will cause the property to be multiplied multiple times

**Comment by Mrcheng66** [comment]
use toRaw() from vue is also invalid

**Comment by qhl123456** [comment]
Try to use ref to define   like:
const arr = ref( [ ])
const arr1 = cloneDeep(arr)
