### ISSUE TITLE
find() seems to be mutating object in list in reactjs ("lodash": "^4.17.21")

### ISSUE THREAD

**Issue by ChumaA** [lodash/lodash#5681]
Lodash version used:  **"lodash": "^4.17.21"** (this is in my package.json file, but other libs my be requiring different versions of lodash).

Example:
```js
var list = [{ key: 'key1lk', val: 'val1lk'}, { key: 'key1', val: 'val1'}, { key: 'key1y', val: 'val1y'}, { key: 'key1d', val: 'val1d'}, { val: 'val1g'}, { val: 'val1p'}]

var obj = find(list, ['val', 'val1'])

console.log(obj) // {key: undefined, val: 'val1'}
```

I guess my question is does `find()` mutate object within list?

**Comment by DEBargha2004** [comment]
![lodash_find_problem](https://github.com/lodash/lodash/assets/104021732/8430dd36-70c5-4fa2-8085-f545af27da1c)

I am using the same version of lodash but in my case i found no issue with find mutating an object. Could this be due to some other code interfering?

**Comment by DEBargha2004** [comment]
![lodash_find_example](https://github.com/lodash/lodash/assets/104021732/ba72acbf-52dc-4fa1-95f8-43c1ed34c03c)
It works as expected with what you have provided in my case.
