### ISSUE TITLE
Having issue: TypeError: cannot read properties of undefined (reading 'cloneDeep')

### ISSUE THREAD

**Issue by pizzascott** [lodash/lodash#5682]
```
import _ from "lodash";
```
```
    TypeError: Cannot read properties of undefined (reading 'cloneDeep')

      27 |
      28 |     beforeEach(() => {
    > 29 |         deals = _.cloneDeep(mockNDBody).deals;
    
    
```
This occurs for any lodash function. 

using node v18.16.1 (npm v9.5.1)

@types/lodash: 4.14.195
lodash: "^4.17.21",

**Comment by vRezn0v** [comment]
It seems to be an issue with the import method, make sure that you are importing lodash correctly.
```import * as _ from "lodash";```

**Comment by CAN1177** [comment]
The error message "TypeError: cannot read properties of undefined (reading 'cloneDeep')" typically means that the object you're trying to access the `cloneDeep` method from is `undefined`.

In the context of lodash, this could mean that lodash has not been correctly imported or installed in your project.

Here are some steps you can take to resolve this issue:

1.  Ensure lodash is installed: You can check if lodash is installed in your project by looking at your `package.json` file and seeing if lodash is listed under the dependencies. If it's not, you can install it by running `npm install lodash` in your terminal.

2.  Correctly import lodash: If lodash is installed but you're still seeing the error, it could be that lodash is not being correctly imported. If you're using ES6 syntax, you can import the `cloneDeep` method from lodash like this:



``` javascript
import { cloneDeep } from 'lodash';
```

Or, if you're using CommonJS syntax, you can import it like this:

``` javascript
const cloneDeep = require('lodash/cloneDeep');
```

3.  Check usage of `cloneDeep`: Ensure that you're using `cloneDeep` correctly. It should be used as a function and passed the object you want to deep clone. For example:



``` javascript
const obj = { a: 1 };
const deepClone = cloneDeep(obj);
```

If you're still seeing the error after following these steps, there might be a problem with your specific usage of `cloneDeep` or your project setup. In that case, it would be helpful to see the specific code that's causing the error.
