### ISSUE TITLE
lodash/get not work

### ISSUE THREAD

**Issue by gauseen** [lodash/lodash#5683]
```js
const obj = {
  a: { b: { fun: () => ({ foo: 'fooo' }) }}
}

_.get(obj, 'a.b.fun().foo')

// expect result 'fooo'
// actual result `undefined`
```

**Comment by nevvada** [comment]
`a.b.fun`'s value is a function definition, and lodash only retrieves values along a path by using object keys. it can't call a function found in the object value.

you could do

```
const obj = {
  a: { b: { fun: () => ({ foo: 'fooo' }) }}
}

const fun = _.get(obj, 'a.b.fun')
const foo = fun().foo

console.log(foo) // "fooo"
```

**Comment by fregante** [comment]
If you define `fun` as a getter, then it will work in a single `_.get('a.b.fun.foo')` call

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get
