### ISSUE TITLE
The isEmpty method is not very rigorous in judging empty objects.

### ISSUE THREAD

**Issue by fsiaonma** [lodash/lodash#5690]
The isEmpty method is not very rigorous in judging empty objects.

```js
const obj = {
  [Symbol('a')]: 1
}
```
when I call `_.isEmpty(obj)`,  it return `true`;

Have you considered using `Reflect.ownKeys()` to solve this problem?

**Comment by dev-davidyoon** [comment]
I would like to be assigned this issue. I am working on pushing up a PR to address this, thanks.

**Comment by fsiaonma** [comment]
@dev-davidyoon thanks

**Comment by angelsupp** [comment]
how about this [PR](https://github.com/lodash/lodash/pull/5702)? Does it solve the issue?

**Comment by deal-talenya** [comment]
Hi, we need this fix because mongoose ObjectId value is identified as empty by isEmpty function
but it looks like earlier it worked as expected

**Comment by n7s4** [comment]
哲哥太强了
