### ISSUE TITLE
FindKeyPath for when you don't know the structure of the object but know the key

### ISSUE THREAD

**Issue by S-Swaroop** [lodash/lodash#5691]
I want to propose a function that would, for a given deeply(maybe) nested object whose structure is not known to us, return the path of a key we want to access. For eg:-

Lets say we have an object 
```
const obj = {
  key1: {
    key2: 'value2',
    targetKey: 'targetValue'
  }
};
```
And we want to access or know if `obj` has a property or a nested property named `targetKey`. 
The proposed function should return `key1.targetKey` as the path. Now it could be like getting the first match or an array paths works too.

**Comment by deprof-dev** [comment]
i think this will be a really good idea. if i get you right, all the method will just have to do is check through an object to see if it includes a specified key - even if it is nested.

**Comment by deprof-dev** [comment]
Alright, great. Might decide to work on that then. I'll give you heads up.
