### ISSUE TITLE
Using lodash-es in a browser, chain().value cause an error

### ISSUE THREAD

**Issue by haoynmail** [lodash/lodash#5692]
Use lodash-es in the browser to create a chain object, and then use value (), for example chain (...). value (). 
The code is packaged using rollup, and the output format is iife. The following error occurred during running

**_Uncaught TypeError: chain (...). value is not a function_**.

Can't use chain in the browser?

**Comment by haoynmail** [comment]
Not resolved

**Comment by jdalton** [comment]
Hi @haoynmail! Because ESM modules are well modular chaining is problematic as chaining assumes a monolithic library state. So you'll have to use the lodash default export and not the modular syntax

**Comment by haoynmail** [comment]
OK, thank you

**Comment by n0099** [comment]
https://github.com/vitejs/vite/issues/11960
