### ISSUE TITLE
`debounce` with `trailing` set to `true` returns stale data for trailing invocation

### ISSUE THREAD

**Issue by jviall** [lodash/lodash#5708]
## Description
When debouncing an `async` function in response to user input, the `trailing` invocation returns stale data, or in some cases `undefined`, **even though the original function is still invoked at the trailing edge**.

## Reproduction
https://codesandbox.io/p/sandbox/musing-pine-83tyzl

The above sandbox makes debounced network requests in response to user input with a `wait` of  250ms. It renders the debounced results to the screen, and `console.log`s the raw `fetch` response to the console. Using the sandbox:
- Type "ada" into the input
- We'll get three results for each character typed, and 2 network requests (one for the leading invocation, and another for the trailing invocation)
- The first two results will correctly correspond to the leading invocation (one fresh, and the second stale).
- The final result will incorrectly correspond to the leading invocation as well, even though the network tab shows that a trailing request was invoked with fresh data in the response.
- We can ensure that the stale data is not due to NextJS nor React caching of the request, as logging of the raw response shows that the fresh data made it to the client, but stale data was returned by the debounced function.
- Similar behavior occurs when leading is false but trailing is still true--a request is made and data is returned, but the debounced function returns undefined. [The documentation](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/common/function.d.ts#L374) specifies that this means the function was never invoked, even though it was.

## Environment
```
  System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 AMD EPYC
    Memory: 5.07 GB / 8.01 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    pnpm: 7.1.0 - /usr/local/bin/pnpm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
 npmPackages:
    @faker-js/faker: 7.6.0 => 7.6.0 
    @types/lodash.debounce: 4.0.7 => 4.0.7 
    @types/node: 20.5.9 => 20.5.9 
    @types/react: 18.0.29 => 18.0.29 
    @types/react-dom: 18.0.11 => 18.0.11 
    classnames: 2.3.2 => 2.3.2 
    lodash.debounce: 4.0.8 => 4.0.8 
    next: 13.4.19 => 13.4.19 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.2.2 => 5.2.2
  Virtualization:
    Docker: 24.0.5 - /usr/bin/docker
```

**Comment by Xutnyt-xudkyv-tuHmo5** [comment]
/ #


> ## descripción
> When debouncing an `async` function in response to user input, the `trailing` invocation returns stale data, or in some cases `undefined`, **even though the original function is still invoked at the trailing edge**.
> 
> ## reproducción
> https://codesandbox.io/p/sandbox/musing-pine-83tyzl
> 
> The above sandbox makes debounced network requests in response to user input with a `wait` of 250ms. It renders the debounced results to the screen, and `console.log`s the raw `fetch` response to the console. Using the sandbox:
> 
> * Escribe "ada" en la entrada
> * Obtendremos tres resultados por cada carácter escrito y 2 solicitudes de red (una para la invocación principal y otra para la invocación final)
> * Los dos primeros resultados corresponderán correctamente a la invocación principal (una nueva y la segunda rancia).
> * El resultado final también corresponderá incorrectamente a la invocación inicial, a pesar de que la pestaña de red muestra que se invocó una solicitud final con datos nuevos en la respuesta.
> * Podemos asegurarnos de que los datos antiguos no se deba al almacenamiento en caché de NextJS ni de React de la solicitud, ya que el registro de la respuesta sin procesar muestra que los datos nuevos llegaron al cliente, pero los datos antiguos fueron devueltos por la función debunced.
> * Un comportamiento similar ocurre cuando el principio es falso, pero el final sigue siendo cierto: se realiza una solicitud y se devuelven los datos, pero la función desecución devuelve sin definir. [La documentación ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/common/function.d.ts#L374)especifica que esto significa que la función nunca se invocó, a pesar de que lo fue.
> 
> ## Medio ambiente
> ```
>   System:
>     OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
>     CPU: (4) x64 AMD EPYC
>     Memory: 5.07 GB / 8.01 GB
>     Container: Yes
>     Shell: 5.1.4 - /bin/bash
>   Binaries:
>     Node: 16.17.0 - /usr/local/bin/node
>     Yarn: 1.22.19 - /usr/local/bin/yarn
>     npm: 8.15.0 - /usr/local/bin/npm
>     pnpm: 7.1.0 - /usr/local/bin/pnpm
>     Watchman: 20220528.183901.0 - /usr/local/bin/watchman
>  npmPackages:
>     @faker-js/faker: 7.6.0 => 7.6.0 
>     @types/lodash.debounce: 4.0.7 => 4.0.7 
>     @types/node: 20.5.9 => 20.5.9 
>     @types/react: 18.0.29 => 18.0.29 
>     @types/react-dom: 18.0.11 => 18.0.11 
>     classnames: 2.3.2 => 2.3.2 
>     lodash.debounce: 4.0.8 => 4.0.8 
>     next: 13.4.19 => 13.4.19 
>     react: 18.2.0 => 18.2.0 
>     react-dom: 18.2.0 => 18.2.0 
>     typescript: 5.2.2 => 5.2.2
>   Virtualization:
>     Docker: 24.0.5 - /usr/bin/docker
> ```

**Comment by jviall** [comment]
@jdalton what the `bankruptcy` label mean? and why was this closed without any explanation?
