### ISSUE TITLE
Is the Current Version Still Usable for Commercial Projects?

### ISSUE THREAD

**Issue by Chieffo2021** [lodash/lodash#5715]
I'm considering using this software in a commercial project, but I've noticed that the current version hasn't seen any updates (no new commits) for a long time. I'm wondering if it's still a good fit for commercial use.

I'm also curious about the software's update plans. Will there be updates in the future? And, if any new vulnerabilities are discovered, can we expect quick fixes?

Appreciate any info you can provide!

**Comment by Chieffo2021** [comment]
@josh @heff @bkudria @mislav Sorry to bother you, but could you please reply?

**Comment by jdalton** [comment]
The current version is stable and tested.
