### ISSUE TITLE
Consider an automation tool for generating changelogs

### ISSUE THREAD

**Issue by Shinigami92** [lodash/lodash#5724]
Right now, changelogs are written to https://github.com/lodash/lodash/wiki/Changelog
This has some downsides like:

- it wont show up on Renovate updates
- community is not used to
- changes are not published together with the source code (example: https://www.unpkg.com/@faker-js/faker@8.0.2/CHANGELOG.md)

Also nowadays it is now possible to create semi-automatic Release Changelogs in GitHub itself: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

A package that could be worth to explore is https://github.com/release-it/release-it
At Faker we are currently satisfied with `standard-version`, but this is deprecated and not maintained anymore :slightly_frowning_face:

**Comment by jdalton** [comment]
Thank you @Shinigami92! I think we'll use the GitHub process for now. I resisted it for a while but one-click generation is too nice!
