### ISSUE TITLE
_.merge merges undefined values

### ISSUE THREAD

**Issue by lazdmx** [lodash/lodash#573]
Is it correct that `#merge` merges undefined values?

So I expected that `_.merge { }, { a: undefined, b: 1 }` will return `{ b:1 }` object, but I got `{ a: undefined, b: 1 }`.

Actually I'm looking for a way to get rid of all undefined values ( even nested ) from object.

**Comment by FdezRomero** [comment]
Hi @jdalton,

I'm desperately trying to remove empty object properties (`undefined` and `null`) from the `_.merge` without luck. This is what I'm trying (using LoDash 3.3.1 in NodeJS):

```
_.merge(origin, add, function(a, b, key, aParent, bParent) {

  // a = undefined;
  // b = null;

  if (!_.isEmpty(a)) {
      return a;
  }

  if (_.isEmpty(b)) {
      bParent[key] = undefined; // Tried making 'merge' skip the property
      delete bParent[key]; // Tried removing the property
      return;
    }

  ...

});
```

It doesn't matter which way I try, it seems the objects and values are already stored before calling the customizer, so setting the source value to `undefined` or removing the source property doesn't affect the merge result.

By reading your former posts doing this seems possible, so I must be doing something wrong. I read the code but got kinda lost with all the dependencies. Can you please give me some direction?

Thanks in advance!

**Comment by jdalton** [comment]
`_.merge` isn't appropriate for removing properties as the name implies its more about merging them. You can recursively use object iteration methods like [_.forOwn](https://lodash.com/docs#forOwn).

**Comment by FdezRomero** [comment]
Thanks @jdalton. I do want to merge properties from the `add` to the `origin`, I just don`t want to merge properties with `null` or `undefined` into it. It seemed like a good idea to use the recursion I'm already doing in `_.merge` to achieve this, but I guess I will just have to deep iterate the `origin` object again afterwards in order to check and remove these values.

**Comment by yvele** [comment]
I also found a way to skip properties during `merge` is a nice feature to have (in the callback?). Then we will be able to filter source properties (on value, on key, etc..).

Can we re open this issue?

PS: @FdezRomero Have you found a workaround?

**Comment by FdezRomero** [comment]
@yvele Never found a workaround. I ended up coding a custom merge function that adapts better to my different corner cases.

It basically grabs two objects and iterates through the properties deciding what to do depending on the value type on each side (for example, when one is `undefined` and the other isn't, when one of them is an `array`, when both are `array`, etc.).

Boring? A lot. Performant? I'm sure it's far from optimal. Fills all my use cases? It certainly does ;-)
