### ISSUE TITLE
Pluralize returns wrong result for "tariff"

### ISSUE THREAD

**Issue by mosquerapaul** [lodash/lodash#5737]
Pluralize for "tariff" is returning "tarifves". The correct result is "tariffs".
I'm not sure about the gramatical rule, but seems that -ff ending needs a different managing...

**Comment by bnjmnt4n** [comment]
Hey @mosquerapaul, I think you might have opened this in the wrong repository. There isn't a `pluralize` method in lodash.

**Comment by mosquerapaul** [comment]
Sorry, you are right
