### ISSUE TITLE
Suggestion: test for existence of nested object key

### ISSUE THREAD

**Issue by austinpray** [lodash/lodash#574]
Calls like `value.transactionUserSetting.userContact.call.details` can raise exceptions if any object in that chain is undefined. It seems a bit of effort is needed to gracefully handle such a situation. This functionality is something I find myself needed pretty much every project that deals with a JSON API. This would would be right at home in a utility belt like lodash.

Something kind of like:
https://github.com/wilmoore/selectn

Some discussion:
http://stackoverflow.com/questions/2631001/javascript-test-for-existence-of-nested-object-key

**Comment by JamesMcGuigan** [comment]
As of lodash 3.7, _.get() and _.set() work with nested selectors

_.get({a:{b:{c:42}}}, 'a.b.c') // = 42
_.set({a:{b:{c:42}}}, 'a.b.c', 69) // = {a:{b:{c:69}}}
