### ISSUE TITLE
_.size() function returns wrong value when one of the key is 'length'

### ISSUE THREAD

**Issue by rahuramC1X** [lodash/lodash#5751]
![Lodash](https://github.com/lodash/lodash/assets/141827898/2a3aa22b-5216-48e1-ad17-393b1dfde7e0)

I have noticed that the `_.size` function in lodash is behaving unexpectedly. When I call `_.size({ 'a': 1, 'b': 2, 'length': 5 })`, I expect it to return `3` as it should count the properties 'a', 'b', and 'length'. However, it's returning `5`, which is unexpected.

Expected behavior:
`_.size({ 'a': 1, 'b': 2, 'length': 5 })` should return `3`.

Actual behavior:
`_.size({ 'a': 1, 'b': 2, 'length': 5 })` returns `5`.

Steps to reproduce:
1. Use the lodash library.
2. Call `_.size({ 'a': 1, 'b': 2, 'length': 5 })`.

I believe this issue might be related to how the `length` property is being handled, as it's not a string-keyed property but is still counted. Please investigate and correct this behavior.

**Comment by jdalton** [comment]
`_.size` is a collection method. You'd want to use object only methods.
