### ISSUE TITLE
Code in tests broken?

### ISSUE THREAD

**Issue by stepancar** [lodash/lodash#5752]
Hi! I wanted to contribute and notice that a lot of tests broken on master
For example, this line has an incorrect js syntax
https://github.com/lodash/lodash/blob/main/test/difference-methods.spec.js#L30

Is it a known issue?

**Comment by moacirosa** [comment]
Just landed here with the same purpose and it looks they are planning new releases and a new approach as [discussed here](https://github.com/lodash/lodash/discussions/5732). It looks the issue above is similar one I was trying to understand [and linked here](https://github.com/lodash/lodash/issues/5767#issuecomment-1811364228).

**Comment by jdalton** [comment]
Closing as dup of https://github.com/lodash/lodash/issues/5767.
