### ISSUE TITLE
_.isNumber is not working with NaN value

### ISSUE THREAD

**Issue by abdullRahman95** [lodash/lodash#5757]
`_.isNumber(NaN)` is returning `true` as it must return `false`, since NaN not a number.
Could you please check?

**Comment by KazooTTT** [comment]
`NaN` means not a number, but it is a number type.

[mdn-NaN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/NaN
)

![image](https://github.com/lodash/lodash/assets/31075337/1fee78a5-20c3-4618-9b96-b5abf63ac74a)

**Comment by abdullRahman95** [comment]
Thanks @KazooTTT 🙏🏻🙏🏻
