### ISSUE TITLE
github.com/lodash.keys returns HTTP 200 body NULL

### ISSUE THREAD

**Issue by turkcankeskin** [lodash/lodash#5770]
Hello,

We use Jfrog artifactory repository in our company.
We have a /virtual-npm repository of virtual type for dependency install.

inside
https://registry.npmjs.com/
https://registry.yarnpkg.com/
https://github.com/
and our internal repositories.

If a project uses the /virtual-npm repository and uses the https://www.npmjs.com/package/lodash.keys library

npm install - process crashes into 409 conflict.

```
16:44:39  npm verb cwd /tmp/workspace/test
16:44:39  npm verb Linux 4.18.0-372.58.1.el8_6.x86_64
16:44:39  npm verb node v16.20.1
16:44:39  npm verb npm  v8.19.4
16:44:39  npm ERR! code E409
16:44:39  npm ERR! 409 Conflict - GET https://artifactory.company.com/artifactory/api/npm/virtual-npm/lodash.keys
16:44:39  npm verb exit 1
16:44:39  npm timing npm Completed in 143638ms
16:44:39  npm verb unfinished npm timer reify 1697550136438
16:44:39  npm verb unfinished npm timer reify:loadTrees 1697550136443
16:44:39  npm verb code 1
```

The error here is that the https://github.com/lodash.keys page returns HTTP/1.1 200 and body NULL.

How do you know this? Because when I create a repository named /virtual-npm-2 on Artifactory and take out https://github.com/, I can install npm successfully.

I really don't know who will fix the problem here, I opened a ticket for this issue at github support, Jfrog enterprise support and github.com/lodash/lodash/issues. Therefore, if you are not the subject of the issue, please close the issue.

https://github.com/lodash.keys HTTP/1.1 200 and body NULL
https://github.com/notlodash.key HTTP 404 (if this was lodash.key 404 on github, this problem would not occur)

**Comment by ben-bertrands-hs** [comment]
@turkcankeskin Did you have any luck with github support or Jfrog enterprise support? We have the same issue
