### ISSUE TITLE
_.difference and _.merge on two different arrays with common elements

### ISSUE THREAD

**Issue by jcubic** [lodash/lodash#578]
I don't know how those functions should work, but this:

``` javascript
_.merge(['asd', 'asd', 1], ['asd', 'asd', 2])
```

don't return `['asd', 'asd', 1, 2]` but `["asd", "asd", 2]`. And:

``` javascript
_.difference(['asd', 'asd', 1], ['asd', 'asd', 2])
```

return `[1]` instead of `[1,2]`.

Is that how those function should work? I'm using version 2.2.1

**Comment by migounette** [comment]
Just to clarify:

You can use _.merge with a customizer, so the right api now is:

_.mergeWith(object, sources, customizer) whereas _.merge(object, [sources])
