### ISSUE TITLE
Cannot import lodash single function in Node

### ISSUE THREAD

**Issue by BadIdeaException** [lodash/lodash#5792]
From the documentation, and everything I see on the internet, I was under the impression that the following should import the `cloneDeep` method in my Node project:

```
import cloneDeep from 'lodash/cloneDeep';
```

Instead I am getting an `ERR_MODULE_NOT_FOUND`: 
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/tmp/test/node_modules/lodash/cloneDeep' imported from /tmp/test/main.js
Did you mean to import lodash/cloneDeep.js?
    at new NodeError (node:internal/errors:400:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

I don't understand why this won't work? Lodash is installed correctly (`npm install lodash`) and I can see it is present in the `node_modules` folder. Additionally, using CommonJS works:
``` 
const cloneDeep = require('lodash/cloneDeep');
```
Appending the `.js` suffix also works
```
import cloneDeep from 'lodash/cloneDeep.js';
```
but it is my impression that this should not be necessary when importing libraries.

**I think you are missing an [`exports` field](https://nodejs.org/api/packages.html#subpath-exports) in your `package.json`.** I would offer a pull request, but since this would need to be done for literally every function in lodash, it should probably be automatically populated in your build pipeline.

**Comment by BadIdeaException** [comment]
Confirmed that adding the following to `node_modules/lodash/package.json` makes it work as expected.
```
"exports": {
  "./cloneDeep": "./cloneDeep.js"
}
```

**Comment by BadIdeaException** [comment]
This is neither a question, nor is it completed.

**Comment by milesj** [comment]
I'm also running into this. Crazy that this was closed for no reason???

Both `lodash/...` and `lodash-es/...` throw the same error when imported in a type=module context.

**Comment by pedroresende** [comment]
@jdalton Any reason to close this issue ?

**Comment by hugoduraes** [comment]
I'm having the same issue. Why is this closed?

**Comment by nunomarks** [comment]
Can we reopen this? This is still an issue.
