### ISSUE TITLE
sort by multiple nested fields

### ISSUE THREAD

**Issue by DanKaplanSES** [lodash/lodash#581]
I think a very useful feature would be described in this StackOverflow question I made: http://stackoverflow.com/questions/24111535/how-can-i-use-lodash-underscore-to-sort-by-multiple-nested-fields

I want to do something like this:

```
var data = [
    {
        sortData: {a: 'a', b: 2}
    },
    {
        sortData: {a: 'a', b: 1}
    },
    {
        sortData: {a: 'b', b: 5}
    },
    {
        sortData: {a: 'a', b: 3}
    }
];

data = _.sortBy(data, ["sortData.a", "sortData.b"]);

_.map(data, function(element) {console.log(element.sortData.a + " " + element.sortData.b);});
```

And have it output this:

```
"a 1"
"a 2"
"a 3"
"b 5"
```

Unfortunately, this doesn't work and the array remains sorted in its original form.  [This would work if the fields weren't nested inside the `sortData`.](http://stackoverflow.com/a/24111473/61624)  How can I use lodash to sort an array of objects by more than one nested field?

I'd like to request that `data = _.sortBy(data, ["sortData.a", "sortData.b"]);` an sort by nested fields.

**Comment by pdme** [comment]
```
var maxLength = 1;
_.sortBy(data, function(item) {
    var bString = _.toString(item.sortData.b);
    if(maxLength > bString.length) {
        bString = [new Array(maxLength - bString.length).join('0'), bString].join('');
    } else {
        maxLength = value.length;
    }

    return [item.sortData.a, bString];
});
```

**Comment by pdme** [comment]
If the problem is that an integer is converted to a string, add zeroes before the integer to make it have the same length as the longest in the collection:

```
var maxLength = _.reduce(data, function(result, item) {
    var bString = _.toString(item.sortData.b);
    return result > bString.length ? result : bString.length;            
}, 0);

_.sortBy(data, function(item) {
    var bString = _.toString(item.sortData.b);
    if(maxLength > bString.length) {
        bString = [new Array(maxLength - bString.length).join('0'), bString].join('');
    }

    return [item.sortData.a, bString];
});
```

**Comment by zivni** [comment]
Why doesn't
```
_.sortBy(data, function(item) {
   return [item.sortData.a, -item.sortData.b];
})
```
reverses the data? It stays the same with or without the minus sing on tem.sortData.b.

**Comment by jdalton** [comment]
@zivni because the array has no special meaning here. You're returning an array for it be used as the comparator (the thing that has `>` or `<` applied to it).
