### ISSUE TITLE
_.isEqual() returns false when array elements order is changed

### ISSUE THREAD

**Issue by jsc-spideo** [lodash/lodash#5822]
Version : 4.17.21

**Issue :** when an object's array elements are not ordered the same way, isEqual() returns false

**Expected behavior:** array elements order shall not impact equality when identical on a key/value basis.

This example returns true (OK) : 
```

var _ = require('lodash')

var p1 = {
    "firstName": "John",
    "lastName": "Doe"
}

var p2 = {
    "lastName": "Doe",
    "firstName": "John"
}

console.log(_.isEqual(p1, p2))
```

While this one returns false (KO):

```
var _ = require('lodash')

var p1 = {
    "firstName": "John",
    "lastName": "Doe",
    "test": [
        {"x": 1},
        {"y": 2}
    ]
}

var p2 = {
    "firstName": "John",
    "lastName": "Doe",
    "test": [
        {"y": 2},
        {"x": 1}
    ]
}

console.log(_.isEqual(p1, p2))
```

**Comment by valerio-pescatori** [comment]
I think that's correct.. in the second example you actually changed the order of the elements inside the array, so those objects are not equal imo.

```js
// this should return false
[0, 1, 2]_.isEqual([2, 1, 0])
```

**Comment by valerio-pescatori** [comment]
Do you need to keep duplicate entries in the array? 
If you don't you could rather use a `Set`

**Comment by valerio-pescatori** [comment]
> I will implement a sorting function to be called prior to comparison.

If I'm not mistaken sorting should be `O(n log n)`, if duplicate values does not matter I recommend converting the array to a `Set` for a better time complexity (should only take `O(n)`). 

Btw I think this issue can be closed! @jdalton

**Comment by jsc-spideo** [comment]
OK, thanks for your time and for your help.
