### ISSUE TITLE
Allow Default Value for toNumber("problem", 0)

### ISSUE THREAD

**Issue by titouandk** [lodash/lodash#5826]
It would be nice to be allowed to pass an (optional) default value for the conversion function `toNumber()`.

Currently, toNumber() returns NaN if the passed value is not a number:
```js
toNumber("problem") // => NaN
```

The following would return 0 instead:
```js
toNumber("problem", 0) // => 0
```

This would be very useful when using this function to parse config files.

**Comment by kapilkumar9395** [comment]
@jdalton I would like to take this up if this change is needed or if it's not done already.

**Comment by kapilkumar9395** [comment]
https://github.com/lodash/lodash/pull/5852

**Comment by Trott** [comment]
I left this comment on the PR, but I think an options object is probably a better API. `_.toNumber(something, somethingElse)` is not, to me, a self-evident API. `_.toNumber(something, {defaultReturnValue: 0})` or something like that is a bit closer to be self-documenting.

**Comment by kapilkumar9395** [comment]
Makes sense, let me make this change

**Comment by Trott** [comment]
It seems like this feature would typically be used to return 0 instead of `NaN`, but that's already what `toFinite()` does, and `toFinite()` has the added bonus of returning usable values for `Infinity` and `-Infinity`.

**Comment by Trott** [comment]
> Not necessarily. Any number could be set as a default for a missing/wrong value in a config file. By example a upper limit for a certain amount of money, ...

That suggests a poorly designed API. A default value is what I would expect when someone provides no value. But this handles situations where invalid information is provided which seems like a footgun/anti-pattern.

As always, I'm not a lodash maintainer, but it does seem like this adds complexity to the API for a usage that is typically better handled in the application itself.

**Comment by titouandk** [comment]
I agree, treating a wrong value like a missing one is very likely to be a bad idea.
And this is encouraged by the change I suggested...

Maybe are we trying to solve a problem that should not be solved at this level, indeed.
