### ISSUE TITLE
lodash-es outdated

### ISSUE THREAD

**Issue by ronakj** [lodash/lodash#5838]
Looking at the latest lodash-es version, it seems to be missing some commits. Specifically, I wanted this commit https://github.com/lodash/lodash/commit/8bc17fe6598bb9e557986030a1feae290b8a968d, because my webpack bundle is not working due to this issue.

Can we get a new version published with the latest code from the repository?

**Comment by jdalton** [comment]
`lodash-es` will be deprecated in favor of a modular modern esm flavor of the lodash package.

**Comment by mgalgs** [comment]
@jdalton Is there more information anywhere about this "modular modern esm flavor of the lodash package"? I had the same concerns as OP with adding `lodash-es` as a dependency in my project since the `es` branch appears to be unmaintained. But I can't find any information regarding a replacement.

**Comment by hocine15** [comment]
any news on this _modular modern esm flavor of the lodash package_ ?
