### ISSUE TITLE
Alias `_.tail` to `_.last`

### ISSUE THREAD

**Issue by danielbayley** [lodash/lodash#5843]
Having just added an optional parameter to `_.last`—to enable plucking the last _n_ elements from an array in #5842, I also propose that `_.tail` be aliased to `_.last`, so that we have better consistency between `_.head`/`_.first`, and `_.tail`/`_.last` methods. The existing functionality of `_.tail`—to `return` all but the first array element—could instead now be done like this:
~~~ js
const array = [1, 2, 3 ,4]
_.tail(array, -1) // [2, 3, 4]
~~~

This might be a breaking change, so maybe one for v5… But could also exist as something like this wrapper `function` in the meantime…
~~~ js
import last from './last.js';

function tail(array, n = -1) {
    const results = last(array, n) || []
    return [results].flat()
}

export default tail;
~~~

See also #5841, which adds similar functionality to `_.head`/`_.first`.

**Comment by jdalton** [comment]
Thank you @danielbayley! Per #5842 we are removing first/last in favor of built-in `Array#at`.

**Comment by danielbayley** [comment]
> Thank you @danielbayley! Per #5842 we are removing first/last in favor of built-in `Array#at`.

@jdalton Same response as https://github.com/lodash/lodash/pull/5842#issuecomment-2050336399 …

> That’s nice, but it doesn’t give you a range as is the point of this PR…
