### ISSUE TITLE
_.deburr() - ț not convert to t

### ISSUE THREAD

**Issue by dejurin** [lodash/lodash#5844]
Source: `Chiar dacă explodăm de furie, îți zâmbesc, jucându-mă cu vâlvătaia.`

Result: `Chiar daca explodam de furie, iți zambesc, jucandu-ma cu valvataia.`

Expected: `Chiar daca explodam de furie, iti zambesc, jucandu-ma cu valvataia.`

ț - not convert to t

version: **4.17.21**

**Comment by Trott** [comment]
> ț - not convert to t

Seems to be working as designed and documented. `ț` is not part of the Latin-1 Supplement or Latin Extende-A character set. If you write it as a `t` with a combining diacritic, then I imagine `deburr()` will return `t`.

**Comment by dejurin** [comment]
Thank you for the clarification.

**Comment by Trott** [comment]
Perhaps not the functionality you're looking for, but for what it's worth, the `slug()` module will convert Romanian alphabet letters (unicode or otherwise) to Latin characters.

```javascript
 const slug = require('slug');
slug('ț') // 't'
```

I imagine `slugify` and many other packages will do something similar.
