### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by sivasankar169** [lodash/lodash#5845]
**TypeScript error in** 
**node_modules/@types/lodash/common/object.d.ts(1025,21):
Type expected.  TS1110**

```
    1023 |     type GetIndexedField<T, K> = K extends keyof T
    1024 |         ? T[K]
  > 1025 |         : K extends `${number}`
         |                     ^
    1026 |             ? 'length' extends keyof T
    1027 |                 ? number extends T['length']
    1028 |                     ? number extends keyof T
```

**Comment by sivasankar169** [comment]
Node : v14.17.3
npm: v6.14.13

Typescript in my local package.json : 3.9.3

**Comment by Trott** [comment]
I could be wrong, but doesn't that seem like it would be an issue to open in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lodash?

**Comment by sivasankar169** [comment]
npm run build throws this error

**Comment by Trott** [comment]
> Node : v14.17.3

I don't know if lodash supports EOL'ed versions of Node.js, but Node.js 14.x support ended almost a year ago.  Node.js 16 support ends very soon. If possible, update to Node.js 20, which will be supported until 2026.

**Comment by Trott** [comment]
No one will be able to debug this with the abolute minimal information provided. Maybe share your package.json at least?

**Comment by jdalton** [comment]
👋 Hello @sivasankar169 @Trott!

We (Lodash) do not maintain the DefinitelyTyped definitions. Please open an issue at: https://github.com/DefinitelyTyped/DefinitelyTyped
