### ISSUE TITLE
Discussion on Performance Issues of `trimStart` and `trimEnd`（关于 `trimStart` 和 `trimEnd` 性能问题的讨论）

### ISSUE THREAD

**Issue by WangJincheng4869** [lodash/lodash#5847]
The current `trimStart` and `trimEnd` have poor performance, and the longer the string, the worse the performance. I have checked the source code and there are many complex operations inside. What is the purpose of these operations?
> 现在的 `trimStart` 和 `trimEnd` 性能很差，并且字符串越长性能越差。我查看了源码，里面有很多复杂的操作，这些操作的目的是什么？

Here are my test results:
> 以下是我的测试结果：
```ts
const abc =
  'abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz';

console.time('trimStart');
for (let i = 0; i < 10000; i++) {
  trimStart(abc, 'abc');
}
console.timeLog('trimStart');

console.time('removeStart');
for (let i = 0; i < 10000; i++) {
  stringUtils.removeStart(abc, 'abc');
}
console.timeLog('removeStart');

console.time('trimEnd');
for (let i = 0; i < 10000; i++) {
  trimEnd(abc, 'xyz');
}
console.timeLog('trimEnd');

console.time('removeEnd');
for (let i = 0; i < 10000; i++) {
  stringUtils.removeEnd(abc, 'xyz');
}
console.timeLog('removeEnd');
```

result:
> 结果：

```
trimStart: 34.89501953125 ms
removeStart: 0.8349609375 ms
trimEnd: 27.68603515625 ms
removeEnd: 1.008056640625 ms
```

```ts
class StringUtils {
  removeStart(str: string, remove: string) {
    if (!str || !remove) {
      return str;
    }
    if (str.startsWith(remove)) {
      return str.substring(remove.length);
    }
    return str;
  }

  removeEnd(str: string, remove: string) {
    if (!str || !remove) {
      return str;
    }
    if (str.endsWith(remove)) {
      return str.substring(0, str.length - remove.length);
    }
    return str;
  }
}
```

**Comment by Trott** [comment]
> I have checked the source code and there are many complex operations inside. What is the purpose of these operations?

Maybe you could be more specific about which operations you're asking about? I don't think anyone is going to be too excited about explaining everything about the implementation of a function without knowing what it is that puzzles you.

A good way to get the answer yourself might be to take a part of the function that you don't understand and simplify the code to what you think it could be. Then run the tests in the lodash source code and see which tests fail due to the changes you've made. That will explain why the code is written the way it is. (If nothing fails and performance is improved, you can submit the change as a pull request.)

**Comment by WangJincheng4869** [comment]
Here is the source code of `lodash`:
> 下面是 `lodash` 的源码:
```js
function trimStart(string, chars) {
    if (string && chars === undefined) {
        return string[methodName]();
    }
    if (!string || !chars) {
        return string || '';
    }
    const strSymbols = stringToArray(string);
    const start = charsStartIndex(strSymbols, stringToArray(chars));
    return castSlice(strSymbols, start).join('');
}
```

Where `stringToArray` Converting it into an array, I don't know what the purpose of this code is, I feel like it just increases the consumption. So is the purpose of this code to eliminate certain side effects?
> 其中 `stringToArray` 将其转换为了一个数组，我不知道这个代码的作用是什么，感觉只是增加了的消耗。那么这段代码的作用是为了清除某些副作用吗？

I'm very sorry, but due to my limited personal abilities, I raised this question here. We apologize for any inconvenience caused.
> 非常抱歉，由于个人能力有限，所以才在这里提出疑问，敬请见谅。

**Comment by jdalton** [comment]
Hi @WangJincheng4869!

Thank you for raising this. In future releases we will defer to `String#trimStart` and `String#trimEnd`. The `chars` param of Lodash has proven to be counter intuitive and clunky to work with.
