### ISSUE TITLE
There may be a bug here

### ISSUE THREAD

**Issue by 12914hh** [lodash/lodash#5853]
Hi,
Thank you for providing such a useful tool.
But here  I found a bug !
When I use the isNaN method in lodash, 
I found that if I execute console.log(_.isNaN('a')), theoretically 'a' is a string, so the result should be true.
But now I'm getting false. 
This is also the case with the RunKit test under the official documentation.
![image](https://github.com/lodash/lodash/assets/73581391/012b682c-558e-495c-b8c7-d15057e9b483)
Thanks again

**Comment by nikwen** [comment]
`NaN` is a special constant in JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN

`_.isNaN()` only checks if your value is that constant.

See the second line in the [documentation](https://lodash.com/docs/4.17.15#isNaN) for pointers to functions that might help you accomplish what you're trying to accomplish:

![image](https://github.com/lodash/lodash/assets/3309657/d2aac1ba-97ec-415d-bcad-5e45a20b62a3)

**Comment by 12914hh** [comment]
Thank you for your response, I indeed didn't understand the difference between isNaN and Number.isNaN. Thank you. 👍
