### ISSUE TITLE
[Vulnerabilities] Current version 4.5.0 has injection vulnerability

### ISSUE THREAD

**Issue by abhilashaSingh4042** [lodash/lodash#5875]
https://github.com/advisories/GHSA-35jh-r3h4-6jhm

**Comment by Trott** [comment]
I don't think there's any intention to publish a new version of lodash.template any time soon and people are advised to use lodash 4.17.21 instead.

**Comment by jdalton** [comment]
As @Trott said. Lodash's `_.template` is based on Underscore's from 2009. Since then logic-less template methods have become a thing and are great. I'd recommend using a more feature rich logic less alternative template solution.
