### ISSUE TITLE
i want to compare two objects, if they are same or not. (data and structure should be same, order can vary)

### ISSUE THREAD

**Issue by pr2897** [lodash/lodash#5898]

**Comment by benzler** [comment]
@pr2897 Have you tried this: https://lodash.com/docs/#isEqual?

**Comment by pr2897** [comment]
yes,
const obj1 = {'name': "piyush", marks: [100,20,33]}
const obj2 = {marks: [33,20,100], name: "piyush"}
console.log(_.isEqual(obj1, obj2)) // getting false.

but i wanted the response to be true. because name and marks contains the same values.
 and i also wanted it to have this check to be done any depth possible.

**Comment by pr2897** [comment]
> @benzler yes, const obj1 = {'name': "piyush", marks: [100,20,33]} const obj2 = {marks: [33,20,100], name: "piyush"} console.log(_.isEqual(obj1, obj2)) // getting false.
> 
> but i wanted the response to be true. because name and marks contains the same values. and i also wanted it to have this check to be done any depth possible.

here the marks values are same but orders differs. similarly for marks and name.

**Comment by benzler** [comment]
> > @benzler yes, const obj1 = {'name': "piyush", marks: [100,20,33]} const obj2 = {marks: [33,20,100], name: "piyush"} console.log(_.isEqual(obj1, obj2)) // getting false.
> > but i wanted the response to be true. because name and marks contains the same values. and i also wanted it to have this check to be done any depth possible.
> 
> here the marks values are same but orders differs. similarly for marks and name.

Ah now I understand. I would suggest this solution: you need to enhance the `isEqual` method by sorting all the arrays. In my suggestion we do that using a recursive function.

```
// Helper function to deep sort arrays within an object
function deepSortArrays(obj) {
  if (Array.isArray(obj)) {
    return _.sortBy(obj.map(deepSortArrays));
  } else if (_.isObject(obj)) {
    return _.mapValues(obj, deepSortArrays);
  } else {
    return obj;
  }
}

// Custom deep equality function with deep sorting
function deepEqual(obj1, obj2) {
  const sortedObj1 = deepSortArrays(obj1);
  const sortedObj2 = deepSortArrays(obj2);
  return _.isEqual(sortedObj1, sortedObj2);
}

const obj1 = {
  name: "test",
  marks: [100, 20, 33],
  details: {
    scores: [5, 3, 8],
    info: {
      grades: [2, 1, 3]
    }
  }
};

const obj2 = {
  marks: [33, 20, 100],
  name: "test",
  details: {
    info: {
      grades: [3, 2, 1]
    },
    scores: [8, 5, 3]
  }
};

console.log(deepEqual(obj1, obj2)); // true
```

Hope this helps. Unfortunately lodash does not support this out of the box because in most use cases the order in an array matters.

**Comment by pr2897** [comment]
@benzler this helps, thanks a ton.
