### ISSUE TITLE
Searching for a lodash function 

### ISSUE THREAD

**Issue by samprasdsouza** [lodash/lodash#5900]
Hello Team, I am looking for a lodash function which converts object {test: 1, child:{ test:2, child:{ test:3, child: {}}}} to array of objects [{test:1}, {test:2} ,...]. If it is not available can we include it / can I take up this issue and contribute ? .
Thank you :)

**Comment by jdalton** [comment]
Hi @samprasdsouza! This looks like more of a custom/specific use case. I'd recommend creating your own small utility method and using that.
