### ISSUE TITLE
Potential false positive: npm audit reports high severity vulnerability in lodash.pick@4.4.0

### ISSUE THREAD

**Issue by QBlockQ** [lodash/lodash#5918]
npm audit is reporting a high severity vulnerability (Prototype Pollution) in lodash.pick@4.4.0, which appears to be a false positive or misclassification. The vulnerability seems to be related to the full lodash library, but lodash.pick is a separate, minimal package.

## Environment
- lodash.pick version: 4.4.0
- native-base version: 3.4.28 (which depends on lodash.pick)
- npm version: 10.8.3
- Node.js version: 18.18.0

## npm audit report
lodash.pick >=4.0.0
Severity: high
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
fix available via npm audit fix --force
Will install lodash.pick@3.1.0, which is a breaking change
node_modules/lodash.pick
native-base >=3.0.0-0
Depends on vulnerable versions of lodash.pick
node_modules/native-base
2 high severity vulnerabilities

## Steps to Reproduce
1. Create a new project with `npm init -y`
2. Install lodash.pick@4.4.0 and native-base@3.4.28
3. Run `npm audit`

## Expected Behavior
npm audit should not report a high severity vulnerability for lodash.pick@4.4.0, as it's a minimal package that shouldn't be affected by the full lodash library's Prototype Pollution vulnerability.

## Actual Behavior
npm audit reports a high severity vulnerability and suggests downgrading to lodash.pick@3.1.0, which is an older version.

## Additional Context
- The suggested fix (downgrading to 3.1.0) seems incorrect, as it's recommending an older version.
- The vulnerability refers to the full lodash library, but lodash.pick is a separate, minimal package.
- This issue is causing false positives in our CI/CD pipeline and security scans.

## Questions
1. Is this a known issue with npm audit misclassifying vulnerabilities for lodash.pick?
2. If this is a genuine vulnerability, are there plans to address it in a future release of lodash.pick?
3. If this is a false positive, can the npm advisory be updated to exclude lodash.pick from this vulnerability report?

Any clarification or guidance on this issue would be greatly appreciated. Thank you for your time and attention to this matter.

**Comment by gorner** [comment]
See https://github.com/lodash/lodash/issues/5809, particularly the comment [here](https://github.com/lodash/lodash/issues/5809#issuecomment-1921709925) which explains why this vulnerability does indeed affect `lodash.pick`, and the comment [here](https://github.com/lodash/lodash/issues/5809#issuecomment-1911616800) about workarounds.

Per-method packages have been deprecated for some time – see https://lodash.com/per-method-packages – and from other issues it seems the maintainers are have decided not to release any patch updates for them. But the full version of Lodash is fully patched. So if (as it seems) you're not using it directly, the workaround linked above is your best short-term bet. 

But ideally the maintainers of https://github.com/GeekyAnts/NativeBase should consider moving away from the deprecated per-method packages and just use the full (and maintained) version of Lodash directly. Again, see https://lodash.com/per-method-packages for the Lodash team's stance on why they now recommend this.

(I am **not** a Lodash team member, I just check this repo occasionally and try to help connect the dots where I can.)

**Comment by gorner** [comment]
Looks like there is already a pending PR in NativeBase to remove lodash.pick, though it's been in that state for several months: https://github.com/GeekyAnts/NativeBase/pull/5799

So you may need to use that [workaround](https://github.com/lodash/lodash/issues/5809#issuecomment-1911616800).

**Comment by jdalton** [comment]
Yes, it's better to use a more tailored version of a `pick`. You can use modern object spread syntax.
