### ISSUE TITLE
security vulnerability flagged

### ISSUE THREAD

**Issue by rgedies1** [lodash/lodash#5941]
hi there,

your package lodash.template has been flagged by Snyk for a high severity vulnerability for Code Injection: https://security.snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054

can you please update this package to remediate?

<img width="539" alt="image" src="https://github.com/user-attachments/assets/be3a3f91-e5b3-4c9f-a4e3-9b35db84a4f8">

**Comment by jdalton** [comment]
@rgedies1 That is the nature of the design of the functionality. Your best course of action is to avoid the method.

**Comment by rgedies1** [comment]
@jdalton apologies, but could you explain? snyk references vulnerable code in these locations of the 

- Snyk ticket: https://security.snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054
- vulnerable code referenced: https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L14851
- associated commit: https://github.com/lodash/lodash/commit/3469357cff396a26c363f8c1b5a91dde28ba4b1c


can you help me with what i'm missing here?

**Comment by gorner** [comment]
@rgedies1 I am **not** part of the Lodash team, but I attempted to explain the situation here: https://github.com/lodash/lodash/issues/5851#issuecomment-2069634388

I understand jdalton's stance in terms of writing new code but if you're simply clearing out security issues on old code, hopefully the linked comment will explain what to do.
