### ISSUE TITLE
https://security.snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054

### ISSUE THREAD

**Issue by rjsprague** [lodash/lodash#5947]
https://security.snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054

_Originally posted by @avembankottu in https://github.com/lodash/lodash/discussions/5897_

Just in case this isn't top of mind, a high-priority injection attack vector that affects Lodash and all projects that use it as a dep (like Shadcn 2.0^). Should we not be worried about this?

**Comment by jdalton** [comment]
This is a limitation of a  _.template method that creates a function to evaluate. Don’t use that method and instead use  logic less template library instead.
