### ISSUE TITLE
_.cloneDeep of MongoDB ObjectId results in malformed object.

### ISSUE THREAD

**Issue by allenhartwig** [lodash/lodash#602]
When performing a _.cloneDeep on an object containing an attribute with a value of a MongoDB ObjectId type, the cloned result is malformed.

The result looks like: 
```js
"_id":{_bsontype:"ObjectID",id:"S­ÐlW\u0005\u0000\u0000Þ\u0007\u000f"}
```
When the original looks like: 
```js
"_id": "53add57c097b3e0000f3b985"
```
This causes issues when performing transitions such as toString() on the attribute. On the original it will produce `"53add57c097b3e0000f3b985"`, and on the cloneDeep version it will produce `"[object Object]"`.

**Comment by honkskillet** [comment]
@allenhartwig What did you final mongo friendly cloneDeep function look like?

**Comment by allenhartwig** [comment]
@honkskillet I don't have the final implementation handy, but essentially you want to do something like this:

```js
var ObjectId = require("mongodb").ObjectID;
var myNewObj = _.cloneDeep(myObj, function(val){
   if (val instanceOf ObjectId){
      return val.toString();
   }
   return val;
});
```

**Comment by alecl** [comment]
I'm having a similar problem I think with _.pick, _.filter, and _.omitBy. Is there a similar style workaround that can be applied? @jdalton

**Comment by pierrekarpov** [comment]
@jdalton your solution didn't work for me. Yes, it changed the id to the actual string, but now the copy is shallow.
Also, `if (val instanceof ObjectId){` would never be true, as val the the entire object, and not the value associated with the field _id and user in my case.

If anyone is interested, here my ugly workaround:

1. Make a deepCopy
2. Loop through keys
3. If value is an object with field `id`, `_bsontype` and if `obj[key]._bsontype == "ObjectID"`
4. Then `obj[key] = String(oldObj[key]);`

Calling String created a new object, so there are no shallow copy issues there, and it saves it as the normal string.
