### ISSUE TITLE
_.isEmpty returns wrong result

### ISSUE THREAD

**Issue by pavlovt** [lodash/lodash#644]
Hi,
I am using Lodash v2.4.1 and
_.isEmpty( 5000 )
returns true.

Is this a bug or there is a reason for isEmpty to return this result?

Regards,
Todor.

**Comment by Zvika88** [comment]
Hi, why does it return true on a legit, non-empty date object?
`          var testDate = new Date();
          console.log("Date=", testDate, ", typeof(testDate)=", typeof(testDate), ", _.isEmpty(testDate)=", _.isEmpty(testDate));`

==>
Date= Wed Sep 14 2016 14:19:48 GMT-0700 (Pacific Daylight Time) , typeof(testDate)= object , _.isEmpty(testDate)= true

**Comment by jdalton** [comment]
Hi @Zvika88!

An object is considered empty if it has no own enumerable properties.

**Comment by Soletiq** [comment]
Why does this not copy the PHP empty protocol? _.isEmpty(true); should be FALSE...
