### ISSUE TITLE
Array#transpose

### ISSUE THREAD

**Issue by brendanstennett** [lodash/lodash#645]
I just noticed there isn't an Array#transpose function in this library. Was this left out intentionally or would this be useful functionality to add?

**Comment by TurplePurtle** [comment]
It seems like _.zip no longer takes in an array of arrays. Therefore, you can use

    var a = [[1, 2], [3, 4], [5, 6]];
    _.zip.apply(_, a);
    // => [[1, 3, 5], [2, 4, 6]]

**Comment by megawac** [comment]
Or equivalently `_.unzip` @TurplePurtle
