### ISSUE TITLE
_.filterValues

### ISSUE THREAD

**Issue by OliverJAsh** [lodash/lodash#657]
Similar to `_.mapValues` for objects, but for filtering.

Use case:

``` js
function filterValues(object, filter) {
    filter = filter || identity;
    return Object.keys(object).reduce(function (x, key) {
        var value = object[key];
        if (filter(value)) {
            x[key] = value;
        }
        return x;
    }, {});
}

filterValues({bar:1, baz: undefined}); // => {bar:1}
```

**Comment by msafi** [comment]
Great. Thanks! But why does `_.pick(object, { objectProperty: valueToFilterBy })` not work like `_.filter(object, { objectProperty: valueToFilterBy })`?

**Comment by jdalton** [comment]
pick returns an object, filter an array.

**Comment by msafi** [comment]
@jdalton Yeah, sorry about the way I phrased my question! I mean providing an object as a predicate to `_.pick` doesn't seem to do what I've expected based on my experience with `_.filter`

```js
var things = { foo: { count: 3 }, bar: { count: 3 }, baz: { count: 1 } }

_.filter(things, { count: 3 }) // Returns [{ count: 3 }, { count: 3 }] ...Cool. That's what I'm expecting.

_.pick(things, { count: 3 }) // Returns {}...Hmmm, why not { foo: { count: 3 }, bar: { count: 3 } }?
```

I know I can write out a function as predicate, but I'm just curious why the object syntax doesn't work as expected. Thanks so much!

**Comment by jdalton** [comment]
It doesn't support the shorthand syntax because you can provide a string `prop` name or an array of prop names to pick, the `_.matches` shorthand can also work with an array so doesn't mesh well with `_.pick`.

**Comment by AndersDJohnson** [comment]
Can use `_.pickBy` now, which takes a predicate, and it even defaults to `_.identity`, which will exclude any falsy values.
