### ISSUE TITLE
Another fix for node-webkit

### ISSUE THREAD

**Issue by mackwic** [lodash/lodash#658]
It seems that in the last version of node-webkit, when loaded in webkit context (via script src), lodash is not correctly exported ("_ is undefined" errors).

This fix corrected the issue for us, but I don't think it's the most canonic way to do:

``` js
// https://github.com/lodash/lodash/blob/master/lodash.js#L9508
// lodash.js line 9508
  else {
    // in a browser or Rhino
    window._ = root._ = _;
  }
}.call(this));
```

**Comment by prep4gmat** [comment]
tried with edge version had the error, made @mackwic's fix and solved my issue..using lodash 2.4.2
