### ISSUE TITLE
make _.omit support collections

### ISSUE THREAD

**Issue by tkellen** [lodash/lodash#690]
Would you be open to a PR that adds support for using omit on collections, or a PR that adds a new method specifically for collections?  something like:

``` js
_.mixin({
  omitCollection: function(collection, keys) {
    return _.map(collection, function (entry) {
      return _.omit(entry, keys);
    });
  }
});
```

**Comment by radkodinev** [comment]
@jdalton , cc @tkellen

There's a use case (I very often have): a resultset returned from database and having to strip one or more attributes from every object in the resultset.
So functions like the proposed `omitCollection` (and `pickCollection` as well) would be very useful.

**Comment by octref** [comment]
Wait. Is what the OP asking for really `_.remove`?
Say you have
`var set = [{a: 1, b: 2}, {a: 3, b: 4}]`
What the OP and @radkodinev want is probably something like:
```
_.map(set, function(entry) {
    return _.omit(entry, 'b');
})
// [{a: 1}, {a: 3}]
```
`_.remove` is like a mutating `_.filter`. If you modify it so it takes a `collection`, the thing it should do, is like mutating `{a: 1, b: 2}` to `{a: 1}` or something. That's `_.omit` 's job.
So even if we change `_.remove` to work on objects, we still need `_.map` to do the job.

Though, I agree keep it as it this.

**Comment by dysfunct** [comment]
I wanted to just give this a bump - feels like use case described by @radkodinev is pretty common. I often fin myself in a similar situation where pulling from a DB contains items with superfluous information that I end up stripping out via `map` and `omit`.

**Comment by jdalton** [comment]
With lodash/fp it's doable as:
```js
var _ = require('lodash/fp');
var collectionOmit = _.map(_.omit(keys));
```

**Comment by thatisuday** [comment]
set = _.map(set, o => _.omit(o, 'b'));
