### ISSUE TITLE
Find a good way to have `lodash.every` and other modules take minimal filesize

### ISSUE THREAD

**Issue by Raynos** [lodash/lodash#696]
I ran into an issue where a module I was using called `rcss` was a 100KB of which 80kb of that was 40 lodash modules.

It would be great if the `lodash.every` module was published in a format that would take up a low amount of kilobytes when browserified.

It's sad when one function is a fifth of the size of lodash itself :(

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages.
