### ISSUE TITLE
Changing _.templateSettings is a problem with dependencies

### ISSUE THREAD

**Issue by tandrewnichols** [lodash/lodash#705]
I just ran into this problem with a package I was writing that used another package I wrote. If a dependency (A) lists lodash as a dependency, and package (B) lists both A and lodash as dependencies, lodash will only be installed once at the B level and A will use that version. Which means, if A changes `_.templateSettings`, and then B requires `lodash` and tries to parse something (expecting the original `templateSettings`), it will get the ones set by A instead.

I can't seem to find anything about this anywhere online which makes me think maybe there's some obvious way around this. But if not, this seems like a major problem.

As a more specific, concrete example:

I wrote a package called "grunt-travis-matrix." It uses lodash templates but sets the interpolate pattern to a mustache style.

I started working on another package called "tinder-cli" (no, it's not related to the dating app), which uses lodash AND grunt-travis-matrix. It uses the default patterns for it's templating, but I keep getting "Unexpected token =" because the interpolate pattern is "{{ }}" and thus "<%= %>" falls through to the evaluate pattern, which then can't parse the "=".

I haven't tried this with underscore, but I'm assuming there's a similar issue there. I realize I can pass these patterns in to the `_.template` call directly, but it would be nice to set them in one place, rather than every time.

There are, undoubtedly, other ways around this as well (like deleting the cache for lodash or adding a postinstall script to "npm install lodash --force"), but they all feel wrong. Any ideas?

**Comment by bathos** [comment]
This is useful info; I just ran into the same problem and the stack trace allowed me to track down _.template() but didn't make it terribly obvious what the cause was (Unexpected token = at Function (native)  at xxxxx/lodash/index.js:10216:16). Is templateSettings the only global setting like this, or are there other gotchas that necessitate _.runInContext() at the library level?

**Comment by jdalton** [comment]
There's [_.templateSettings](https://lodash.com/docs#templateSettings) and [_.support](https://lodash.com/docs#support).

**Comment by totty90** [comment]
Sometimes this is good, but most of the time is better if you send the templateSettings when you call the template function. For example it should be like this:

    _.template('hello {{ user }}!', {interpolate = /{{([\s\S]+?)}}/g})

I understand that you want a easy to use, but this allow to create bugs. Even using your technique, if the same file needs the template function but one expect the default and the 2nd will change the settings, it will mess up the first one.

**Comment by tandrewnichols** [comment]
I disagree with "most of the time." Clearly, `_.runInContext` was created for exactly this purpose. Even the one time you mention when it may not be best is a) an edge case and b) easily worked around.

**Comment by totty90** [comment]
Just imagine a new dev comes into your team and mistakenly don't use _.runInContext and changes the settings. It might mess with code from the other side of the code base. This is why is a bad architecture decision, at least IMO.

**Comment by tandrewnichols** [comment]
But that's not a problem with _.runInContext. They could just as easily blow away the templateSettings _without_ _.runInContext. If anything, _.runInContext makes it _safer_ because they're only blowing away _your local template settings_ rather than every piece of code that might use _.template with that lodash instance (especially important for modules intended for publishing and public consumption). And if they blow away the _main lodash instance_ _.templateSettings, the one you set up with _.runInContext will be unaffected.

**Comment by totty90** [comment]
You are right, as long as every file in your codebase is like this `var _ = require('lodash').runInContext()`. 

But how about when is in the same file. Maybe you wrote the first method of lodash which sets the new settings. The new dev writes the 2nd method and replace settings, now what? This has a less exposure, but even so, unexpected bugs appear.

**Comment by jdalton** [comment]
The `_.templateSettings` object has existed in one way or another for ~5 yrs now (in underscore and then lodash). It's the default template settings. That gives devs a lot of power. If they shoot themselves in the foot with it they can correct easily enough.

**Comment by totty90** [comment]
Therefore if you use npm and any of your packages use the lodash as yours, you might break them or they might break you if you don't use`var _ = require('lodash').runInContext()` every single time. I think a warning should be added.
