### ISSUE TITLE
suggestion: compact() for objects

### ISSUE THREAD

**Issue by boneskull** [lodash/lodash#707]
I may be completely missing some function (since there are many of them), and I apologize if I didn't find a similar previous issue.

Given:

``` js
var foo = {
  bar: 'baz', 
  quux: undefined
};
```

It would be very handy if there was a `compact()`-like function that returns an object.  If I want an object containing _only_ the truthy values of `foo`, the best way I've found thus far is to:

``` js
_.omit(foo, function objectFilter(value) {
  return !value;
});
```

I'd be happy with either of these:
- `omit()` has no default second parameter.  What if `objectFilter()` above became the default second parameter?  
  
  Users of `omit()` who do _not_ specify a second parameter will find themselves with an identical object.  This leads me to guess that _unless the user is mis-using `omit()`_ to create a clone, it's probably not being used in this manner.   Whether or not this constitutes a breaking change is a grey area; is it a breaking change if it broke for users who were misusing the API?
- Some new function that does exactly the above: input is `Object`, output is subset of `Object`, excluding key/value pairs where the value is falsy.

If you like the idea and do not wish to implement for whatever reason, I can supply a PR.

thanks!

**Comment by adjohnson916** [comment]
Just a note that with latest Lodash versions one has to use `_.omitBy` instead of `_.omit` with `_.isUndefined`.

**Comment by tokland** [comment]
So I guess the conclusion is: `_.pickBy(foo)`.

**Comment by sergeylaptev** [comment]
@tokland using `pickBy` in this case may have horrible side-effects. We unintentionally omit ALL falsey values, including zero, and empty string. So if OP wants to filter only undefined values, @AndersDJohnson approach is must have

**Comment by AndersDJohnson** [comment]
`pickBy(Foo)` will behave like `compact` but for objects, removing anything falsey. Whereas `omitBy(foo, isUndefined)` will remove only undefined items.

**Comment by tokland** [comment]
I stand corrected. You usually want to remove null/undefined and leave everything else, so: 

```
_({one: 1, zero: 0, emptyString: "", null: null, undefined: undefined}).omitBy(x => _.isNull(x) || _.isUndefined(x)).value() 
// Object { one: 1, zero: 0, emptyString: "" }
```

**Comment by ronnieoverby** [comment]
@tokland Better?

```js
_.omitBy({a:1,b:null, c: void 0,d:0}, _.isNil)
```

**Comment by MrBlenny** [comment]
For the glass half full types
```js
pickBy({ some: 'object'}, identity)
```
