### ISSUE TITLE
Objects difference and intersection

### ISSUE THREAD

**Issue by klimashkin** [lodash/lodash#72]
How can I get difference and intersection of two objects by keys?

**Comment by granteagon** [comment]
Anyone else looking for a similar solution to @blandman–I needed to compute the difference between two objects–here's what I did:

```js
var a = {'a': 1, 'b': 2, 'c': 3};
var b = {'a': 1, 'b': 2, 'c': 4};

_.reduce(a, function(result, n, key) {
  if (!a[key] || a[key] != b[key]) {
    result[key] = b[key];
  }
  return result;
}, {})

// → {'c': 4}
```

It's not pretty, but it works!

**Comment by jdalton** [comment]
@granteagon  you can *reduce* it a bit more with `_.transform`
```js
_.transform(a, function(result, n, key) {
  if (!a[key] || a[key] != b[key]) {
    result[key] = b[key];
  }
})
```

**Comment by Morgul** [comment]
@jdalton As near as I can tell you can drop the `!a[key]`:

```javascript
_.transform(a, function(result, n, key) {
  if (a[key] != b[key]) {
    result[key] = b[key];
  }
})
```

_However_, this is insufficient for the following reasons:

*  it doesn't pick up new properties that have been added to `b`.
* it doesn't correctly track deletions, because it would write `undefined`, which can only be detected by `_.hasValue` (among other problems).
* arrays and objects will always be in the delta, even if they didn't change.

This should be the most complete, and allow you to correctly duplicate the changes:

```javascript
var changes = _.transform(b, function(result, n, key) {
  if (!_.isEqual(n, a[key])) {
    result[key] = n;
  }
});

var deletions = _.difference(_.keys(a), _.keys(b));
```

**Comment by granteagon** [comment]
@morgul that works well, thanks

**Comment by simkessy** [comment]
How would this work if you had an array of objects?

```
var allUsers = [{id:1},{id:2},{id:3},{id:4},{id:5}]
var  assignedUsers = [{id:1},{id:3}]

How would I return this?
var remainingUsers = [{id:2},{id:4},{id:5}]
```

**Comment by jdalton** [comment]
@simkessy In v4 you can do
```js
_.differenceBy(allUsers, assignedUsers, 'id');
```

**Comment by simkessy** [comment]
Wow, that's really useful.

**Comment by jdalton** [comment]
When it's published in Jan.

**Comment by simkessy** [comment]
Awesome, I'll keep an eye out :D

**Comment by bzin** [comment]
@jdalton that's great, but how would you do if you want to do it differently? 
Returning an array with the objects that are in both arrays without having them in duplicate.

**Comment by jdalton** [comment]
@bzin That's `_.xor` or `_.xorBy`.

**Comment by cyrilchapon** [comment]
Very bad title. You're not looking for differences between objects, you are looking for differences between arrays...

**Comment by kamarajuPrathi** [comment]
@jdalton can i do differenceby multiple fields 

example 
var a = [{ 'a': 1, 'b': 2, 'c': 3 },{ 'a': 3, 'b': 2, 'c': 3 },{ 'a': 4, 'b': 2, 'c': 3 },{ 'a': 4, 'b': 3, 'c': 3 }];
var b = [{ 'c': 3, 'd': 4, 'e': 5,'b':2 }];

can i do difference  with two fields 'b' and 'c'?

**Comment by shtse8** [comment]
@jdalton  I want to do the same thing as @kamarajuPrathi , but I can't find a good way to do it. any ideas?

**Comment by devkam** [comment]
For multiple fields I used `_.differenceWith` function with custom comparator. Example:

```
_.differenceWith(setA, setB, customComparator);

function customComparator(a, b) {
    return a.propertyA === b.propertyA && a.propertyB === b.propertyB;
}
```

**Comment by thiennhank9** [comment]
Can we use 
_.differenceBy(a, b, ['b', 'c']) 
to compare multiple fields of objects of two arrays a and b?

**Comment by digeomel** [comment]
How about:

```
_.differenceWith(setA, setB, customComparator);

function customComparator(a, b) {
    return _.difference(_.keys(a), _keys(b)).length === 0 &&
           _.difference(_.values(a), _.values(b)).length === 0;
}

```

**Comment by lakshaybadak** [comment]
What is the time complexity of _.intersection?
