### ISSUE TITLE
Deep functionality for omit

### ISSUE THREAD

**Issue by ssesfahani** [lodash/lodash#723]
I was wondering if there could be an enhancement to support deep functionality for `_.omit` or if it has been discussed before?

**Comment by adityav** [comment]
would love to see _.deepOmit in the library.

**Comment by aronwoost** [comment]
```
var o = {
  id: 1,
  value: "test",
  child: {
    id: 2,
    childValue: "test"
  }
}
_.omit(o, "value", "child.childValue");
```
... would be super awesome.

**Comment by tejasmanohar** [comment]
+1 for omit deep

**Comment by bbottema** [comment]
> We don't support deep omitting

Why is that, @jdalton, it's surely useful.

**Comment by jdalton** [comment]
> Why is that, @jdalton, it's surely useful.

Nothing against it. Just waiting for a bit more user demand for the feature.

**Comment by PizzaBrandon** [comment]
I needed something like this, too, so I came up with the following:

```javascript
function omitDeep(collection, excludeKeys) {

  function omitFn(value) {

    if (value && typeof value === 'object') {
      excludeKeys.forEach((key) => {
        delete value[key];
      });
    }
  }

  return _.cloneDeepWith(collection, omitFn);
}
```

It can certainly be made to be more generic and I'm sure there are optimizations that could be done here, but it worked for me and got rid of my annoying "Maximum call stack size exceeded" error when doing the same thing recursively myself.

**Comment by code-guru** [comment]
:+1: just where looking for this feature.

**Comment by Paxton** [comment]
Would be useful! 👍

**Comment by broseborough** [comment]
+1 I'd love to see this functionality

**Comment by udnisap** [comment]
thought this supports out of the box.
+1

**Comment by vladimirbuskin** [comment]
i've searched for that, so
+1

**Comment by jdalton** [comment]
Don't forget to vote with [reactions](https://help.github.com/articles/about-discussions-in-issues-and-pull-requests/) as it helps us [sort by popularity](https://help.github.com/articles/about-discussions-in-issues-and-pull-requests/#sorting-issues-and-pull-requests-by-reaction).

**Comment by udnisap** [comment]
`_.unset` can be used like this 
```
const omitList = ['a.b', 'c'];
let obj = {a: {b:6, c: 5}, c: 6, d:5};


omitList.forEach(field => _.unset(obj, field));

// obj = {a: {c:5}, d:5};
```

**Comment by devboxr** [comment]
Would love for both, `_.omit` and `_.pick` to work with paths.

**Comment by sotoer** [comment]
+1 for deep _.pick

**Comment by renehamburger** [comment]
BTW, this one is the most popular issue by now... Would it be worth putting it onto the roadmap?

**Comment by devboxr** [comment]
Agree, there is a lot of popularity for this task and I doubt it can be ignored for longer after closing it on 25 Sep 2014. Time to pick this up? :)

**Comment by mohithg** [comment]
surely a good feature to be

**Comment by iam-peekay** [comment]
agreed! would be awesome.

**Comment by jdalton** [comment]
Thanks for the show of support for this feature!
This request is now open to PRs if anyone want's to give it a try.

**Comment by avivr** [comment]
I would love to give it a try

**Comment by avivr** [comment]
might need help though, first-timer..

**Comment by jdalton** [comment]
@avivr Be sure to check out the [pull request contributing guide](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#pull-requests).

**Comment by doug-numetric** [comment]
Any chance for an array syntax for deep omit?
```javascript
var o = {
  id: 1,
  value: "test",
  child: {
    id: 2,
    childValue: "test"
  }
}
// current way to handle computed key names
// let cv="childValue";
// _.omit(o, `child.${cv}`)
_.omit(o, ["child", "childValue"]);
```
For same reasons `get` supports this syntax.

**Comment by jdalton** [comment]
@doug-numetric
> Any chance for an array syntax for deep omit?

The `omit` methods aren't being carried over to Lodash v5.

**Comment by Billy-** [comment]
@jdalton how come? Is there a replacement?

**Comment by jdalton** [comment]
Omit requires grabbing all possible properties (inherited, own, non-enumerable, symbols, etc.) and then filtering out properties. This is overly complicated. It's better to pick the properties you want or simply delete the rogue ones.

**Comment by antony** [comment]
Lodash giveth, lodash taketh away :)

**Comment by ZephD** [comment]
> Lodash giveth, lodash taketh away :)
* Lodash giveth, lodash omit.
FTFY.

**Comment by bbottema** [comment]
(but not deep)

**Comment by loopmode** [comment]
In my case, `hard-source-webpack-plugin` creates a hash of my webpack config, which is a fairly complex object, to check whether it can reuse previous results.
In production builds, certain properties of the config object contain dynamic values, like a timestamp in an output path, so the hash of the config object is always a new one. This effectively defeats the caching mechanism.
In such a case, picking/whitelisting is almost impossible whereas omitting/blacklisting a few well-known keys would be perfect.

I guess I'll have to clone the object, then somehow delete the rogue keys as mentioned above, then get it's hash.

**Comment by clodal** [comment]
Recursively omit keys from an object by defining an array of keys to exclude in ES6 + Typescript.

`omitDeep(myObject, [omitKey1, omitKey2, ...omitKeyN])`

```
// omitDeep.ts

/**
 * Recursively remove keys from an object
 * @usage
 *
 * const input = {
 *   id: 1,
 *   __typename: '123',
 *   createdAt: '1020209',
 *   address: {
 *     id: 1,
 *     __typename: '123',
 *   },
 *   variants: [
 *     20,
 *     {
 *       id: 22,
 *       title: 'hello world',
 *       __typename: '123',
 *       createdAt: '1020209',
 *       variantOption: {
 *         id: 1,
 *         __typename: '123',
 *       },
 *     },
 *     {
 *       id: 32,
 *       __typename: '123',
 *       createdAt: '1020209',
 *     },
 *   ],
 * }
 *
 * expect(omitDeep(input, ['createdAt, 'updatedAt', __typename']).to.equal(output) // true
 *
 * const output = {
 *   id: 1,
 *   address: {
 *     id: 1,
 *   },
 *   variants: [
 *     20,
 *     {
 *       id: 22,
 *       title: 'hello world',
 *       variantOption: {
 *         id: 1,
 *       },
 *     },
 *     {
 *       id: 32,
 *     },
 *   ],
 * }
 *
 * @param {object} input
 * @param {Array<number | string>>} excludes
 * @return {object}
 */
const omitDeep = (input: object, excludes: Array<number | string>): object => {
  return Object.entries(input).reduce((nextInput, [key, value]) => {
    const shouldExclude = excludes.includes(key)
    if (shouldExclude) return nextInput

    if (Array.isArray(value)) {
      const arrValue = value
      const nextValue = arrValue.map((arrItem) => {
        if (typeof arrItem === 'object') {
          return omitDeep(arrItem, excludes)
        }
        return arrItem
      })
      nextInput[key] = nextValue
      return nextInput
    } else if (typeof value === 'object') {
      nextInput[key] = omitDeep(value, excludes)
      return nextInput
    }

    nextInput[key] = value

    return nextInput
  }, {})
}

export default omitDeep
```

**Comment by Billy-** [comment]
FWIW: here's [my version](https://gist.github.com/Billy-/d94b65998501736bfe6521eadc1ab538)

**Comment by mxmzb** [comment]
`_.omit(o, "value", "child.childValue");` works right now, so no need to do it yourself ;)

**Comment by Billy-** [comment]
@mxmzb the main use-case that isn't supported is arrays (iterate over all items in an array)

**Comment by mxmzb** [comment]
@Billy- If you have explicit values and care about data structure, which I believe you should do, this is a very elegant approach:

```
const myNewObjectWithOmittedParams = Object.assign(
  {},
  {
    ...omit(myOldObject, ["bar", "foo.bar"])
  },
  {
    someChildArrayProp: myOldObject.someChildArrayProp.map(obj => omit(obj, ["bar", "foo.bar"]))
  }
```

**Comment by bdelmas** [comment]
@mxmzb Unless I have the wrong version but `_.omit(o, "value", "child.childValue");` doesn't work for `"child.childValue"`.

**Comment by rwoody** [comment]
@clodal That works (I also had the same use case with `__typename`). I tweaked it a little bit to safely handle null/undefined values

**Comment by blikblum** [comment]
> I tweaked it a little bit to safely handle null/undefined values

Can you post your version?

**Comment by dgsunesen** [comment]
@PizzaBrandon - Awesomesauce solution!

**Comment by jeshio** [comment]
with null fields handle:

> const omitDeep = (input: object, excludes: Array<number | string>): object => {
>   return Object.entries(input).reduce((nextInput, [key, value]) => {
>     const shouldExclude = excludes.includes(key)
>     if (shouldExclude) return nextInput
> 
>     if (Array.isArray(value)) {
>       const arrValue = value
>       const nextValue = arrValue.map((arrItem) => {
>         if (typeof arrItem === 'object' **&& arrItem !== null**) {
>           return omitDeep(arrItem, excludes)
>         }
>         return arrItem
>       })
>       nextInput[key] = nextValue
>       return nextInput
>     } else if (typeof value === 'object' **&& arrItem !== null**) {
>       nextInput[key] = omitDeep(value, excludes)
>       return nextInput
>     }
> 
>     nextInput[key] = value
> 
>     return nextInput
>   }, {})
> }
> 
> export default omitDeep
> ```

**Comment by JetsterDajet** [comment]
@jeshio This is an NPE
```js
} else if (typeof value === 'object' && arrItem !== null) {
```
`arrItem` only exists in the scope of the above `arrValue.map`.

**Comment by alfasin** [comment]
> > Why is that, it's surely useful.
> 
> Nothing against it. Just waiting for a bit more user demand for the feature.

Per all the responses here, it looks like there's a demand IMO.
Can we reopen?

**Comment by ulisesbocchio** [comment]
you can use `cloneDeepWith`:
```js
function omitDeep(input, excludes) {
    const omit = [];
    const clone = _.cloneDeepWith(input, (value, key, object, stack) => {
        if(!_.isUndefined(key) && excludes.includes(key)) {
            omit.push({ key, from: stack.get(object) });
            return null;
        }
    });
    omit.forEach(({ key, from }) => _.unset(from, key));
    return clone;
}
```

I've been using something a bit more involved to omit anything past a given depth or have exclusion rules be regexes on full paths from the root of the input:
```js
function deepCustomizer(customizer) {
    const depthMap = new WeakMap();
    return (value, key, object, stack) => {
        let depth = 0;
        let path = [];
        if (!_.isUndefined(key)) {
            const { depth: parentDepth, path: parentPath } = depthMap.get(object);
            depth = parentDepth + 1;
            path = [...parentPath, key];
        }
        if (_.isObject(value) && !_.isBuffer(value)) {
            depthMap.set(value, { depth, path });
        }
        return customizer(value, key, object, stack, depth, path);
    };
}

function omitDeep(input, excludes, maxDepth = Infinity) {
    const omit = [];
    const isExcluded = pathString => _.some(excludes, exclude => _.isRegExp(exclude) ? exclude.test(pathString) : exclude === pathString);
    const clone = _.cloneDeepWith(input, deepCustomizer((value, key, object, stack, depth, path) => {
        const pathString = _.join(path, '.');
        if(depth > maxDepth || isExcluded(pathString)) {
            omit.push({ key, from: stack.get(object) });
            return null;
        }
    }));
    omit.forEach(({ key, from }) => _.unset(from, key));
    return clone;
}
```
but it would be nice if at least lodash's customizer provides depth/path and a way to instruct omissions, maybe with a Symbol.

**Comment by lveillard** [comment]
> Recursively omit keys from an object by defining an array of keys to exclude in ES6 + Typescript.
> 
> `omitDeep(myObject, [omitKey1, omitKey2, ...omitKeyN])`
> 
> ```
> // omitDeep.ts
> 
> /**
>  * Recursively remove keys from an object
>  * @usage
>  *
>  * const input = {
>  *   id: 1,
>  *   __typename: '123',
>  *   createdAt: '1020209',
>  *   address: {
>  *     id: 1,
>  *     __typename: '123',
>  *   },
>  *   variants: [
>  *     20,
>  *     {
>  *       id: 22,
>  *       title: 'hello world',
>  *       __typename: '123',
>  *       createdAt: '1020209',
>  *       variantOption: {
>  *         id: 1,
>  *         __typename: '123',
>  *       },
>  *     },
>  *     {
>  *       id: 32,
>  *       __typename: '123',
>  *       createdAt: '1020209',
>  *     },
>  *   ],
>  * }
>  *
>  * const output = {
>  *   id: 1,
>  *   address: {
>  *     id: 1,
>  *   },
>  *   variants: [
>  *     20,
>  *     {
>  *       id: 22,
>  *       title: 'hello world',
>  *       variantOption: {
>  *         id: 1,
>  *       },
>  *     },
>  *     {
>  *       id: 32,
>  *     },
>  *   ],
>  * }
>  *
>  * expect(omitDeep(input, ['createdAt, 'updatedAt', __typename']).to.deep.equal(output) // true
>  *
>  * @param {object} input
>  * @param {Array<number | string>>} excludes
>  * @return {object}
>  */
> const omitDeep = (input: object, excludes: Array<number | string>): object => {
>   return Object.entries(input).reduce((nextInput, [key, value]) => {
>     const shouldExclude = excludes.includes(key)
>     if (shouldExclude) return nextInput
> 
>     if (Array.isArray(value)) {
>       const arrValue = value
>       const nextValue = arrValue.map((arrItem) => {
>         if (typeof arrItem === 'object') {
>           return omitDeep(arrItem, excludes)
>         }
>         return arrItem
>       })
>       nextInput[key] = nextValue
>       return nextInput
>     } else if (typeof value === 'object') {
>       nextInput[key] = omitDeep(value, excludes)
>       return nextInput
>     }
> 
>     nextInput[key] = value
> 
>     return nextInput
>   }, {})
> }
> 
> export default omitDeep
> ```

This one breaks when having null values, you can filter them like this:

```
[...]
return Object.entries(input)
    .filter((x) => x[1] !== null) /newline
    .reduce [...]
```

**Comment by lsaadeh** [comment]
For my use case I just needed to remove undefined variables.. here my attempt.

`
const omitDeep = (input: any, omitValue = undefined): any => {
    if (Array.isArray(input)) {
      const arrValue = input.filter((e) => e !== omitValue);
      const nextValue = arrValue.map((arrItem) => {
        return Helpers.omitDeep(arrItem, omitValue);
      });
      return nextValue;
    } else if (typeof input === 'object') {
      return Object.entries(input).reduce((nextInput: any, [key, value]) => {
        const shouldExclude = value === omitValue;
        if (shouldExclude) {
          return nextInput;
        }
        nextInput[key] = Helpers.omitDeep(value, omitValue);
        return nextInput;
      }, {});
    } else {
      return input;
    }
  }
`

`const object = {
    a: '',
    b: undefined,
  };

  const input = {
    a: '',
    b: undefined,
    c: [
      {
        a: '',
        b: undefined,
      },
      [
        {
          a: '',
          b: undefined,
        },
        [
          {
            a: '',
            b: undefined,
          },
          object,
          ['a', 'b', 'c', undefined, 1, 2, 3, ['a', 'b', 'c', undefined, 1, 2, 3, ['a', 'b', 'c', undefined, 1, 2, 3]]],
        ],
      ],
    ],
    d: {
      a: 'abc',
      b: undefined,
      c: {
        a: undefined,
        b: '',
      },
      d: 123,
    },
    e: object,
    f: ['a', 'b', 'c', undefined, 1, 2, 3, ['a', 'b', 'c', undefined, 1, 2, 3, ['a', 'b', 'c', undefined, 1, 2, 3]]],
  };

  const output = {
    a: '',
    c: [
      {
        a: '',
      },
      [
        {
          a: '',
        },
        [
          {
            a: '',
          },
          {
            a: '',
          },
          ['a', 'b', 'c', 1, 2, 3, ['a', 'b', 'c', 1, 2, 3, ['a', 'b', 'c', 1, 2, 3]]],
        ],
      ],
    ],
    d: {
      a: 'abc',
      c: {
        b: '',
      },
      d: 123,
    },
    e: {
      a: '',
    },
    f: ['a', 'b', 'c', 1, 2, 3, ['a', 'b', 'c', 1, 2, 3, ['a', 'b', 'c', 1, 2, 3]]],
  };

  [
    {
      description: 'should remove all values specified by omitDeep in an object',
      input: input,
      output: output,
    },
    {
      description: 'should remove all values specified by omitDeep in an array',
      input: [input],
      output: [output],
    },
  ].forEach((test) => {
    it(test.description, async () => {
      const json = Helpers.omitDeep(test.input);
      expect(json).to.eql(test.output);
    });
  });

`

**Comment by teja123r** [comment]
I just had to deep omit certain keys given an object that might contain Arrays. Here's my attempt

```typescript
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const omitDeep = (obj: any, omitKeys: string[]): any => {
  if (Array.isArray(obj)) {
    return obj.map((v) => omitDeep(v, omitKeys));
  } else if (obj != null && obj.constructor === Object) {
    for (const key in obj) {
      const value = obj[key];
      if (value != null && value.constructor === Object) {
        omitDeep(value, omitKeys);
      } else if (omitKeys.includes(key)) {
        delete obj[key];
      }
    }
  }
  return obj;
};
```

**Comment by esistgut** [comment]
Typescript version of https://github.com/lodash/lodash/issues/723#issuecomment-194385740: 
```typescript
export function omitDeep<T>(collection: T, excludeKeys: string[]): T {
  function omitFn(value: any) {
    if (value && typeof value === 'object') {
      excludeKeys.forEach((key) => {
        delete value[key];
      });
    }
  }

  return cloneDeepWith(collection, omitFn);
}
```

**Comment by azerum** [comment]
Here's a TypeScript types-aware version (doesn't work with Map and Set, but those can be added):

```ts
export type OmitDeep<T, K extends string> = 
  T extends (infer U)[]
    ? OmitDeep<U, K>[]
    : T extends Record<any, any>
      ? { [P in keyof T as P extends K ? never : P]: OmitDeep<T[P], K> }
      : T;

export function omitDeep<
  T extends object,
  K extends string,
>(obj: T, key: K): OmitDeep<T, K> {
  const clone: any = {};

  for (const property in obj) {
    const value = obj[property];

    //@ts-expect-error The types of those values can overlap
    if (property === key) {
      continue;
    }

    if (Array.isArray(value)) {
      clone[property] = value.map((item) => omitDeep(item, key));
      continue;
    }

    if (value !== null && typeof value === "object") {
      clone[property] = omitDeep(value, key);
      continue;
    }

    clone[property] = value;
  }

  return clone;
}
```

**Comment by thomberg1** [comment]
[azerum](https://github.com/azerum) [on Jun 10, 2023](https://github.com/lodash/lodash/issues/723#issuecomment-1585618016)

plus  array of string support and multiple keys
```
export type OmitDeep<T, K extends string[]> =
    T extends (infer U)[]
    ? OmitDeep<U, K>[]
    : T extends Record<any, any>
    ? { [P in keyof T as P extends K[number] ? never : P]: OmitDeep<T[P], K> }
    : T;

export function omitDeep<
    T extends object,
    K extends string[],
>(obj: T, keys: K): OmitDeep<T, K> {
    if (typeof obj === "string" || typeof obj !== "object" || obj === null) return obj as any;

    if (Array.isArray(obj)) {
        return obj.map(item => omitDeep(item, keys)) as any;
    }

    const clone: any = {};
    for (const property in obj) {
        if (keys.includes(property as string)) {
            continue;
        }
        const value = obj[property];
        if (value && typeof value === "object") {
            clone[property] = omitDeep(value, keys);
        } else {
            clone[property] = value;
        }
    }
    return clone;
}
```

**Comment by augustoicaro** [comment]
> Typescript version of [#723 (comment)](https://github.com/lodash/lodash/issues/723#issuecomment-194385740):
> 
> ```ts
> export function omitDeep<T>(collection: T, excludeKeys: string[]): T {
>   function omitFn(value: any) {
>     if (value && typeof value === 'object') {
>       excludeKeys.forEach((key) => {
>         delete value[key];
>       });
>     }
>   }
> 
>   return cloneDeepWith(collection, omitFn);
> }
> ```

This implementation deletes the key from the original object. You can cloneDeep the object first, but you will use the cloneDeepWith only for traverse the object. Memory wise we can skip the cloneDeepWith with:
```ts
omitDeep<T>(collection: T, excludeKeys: string[]): T {
  const clonedCollection = cloneDeep(collection);

  function omitFn(value: any) {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      excludeKeys.forEach((key) => {
        delete value[key];
      });
    }
  }

  function traverse(value: any) {
    if (Array.isArray(value)) {
      value.forEach(traverse);
    } else if (value && typeof value === 'object') {
      omitFn(value);
      Object.keys(value).forEach((key) => traverse(value[key]));
    }
  }

  traverse(clonedCollection);
  return clonedCollection;
}
```

I also found this repo that implements omitDeep and other utilities in the typescript way: https://github.com/tobloef/deep-utility-types
