### ISSUE TITLE
Reusable chains

### ISSUE THREAD

**Issue by arestov** [lodash/lodash#730]
To use chain i should pass `characters` to `.chain()` http://lodash.com/docs#chain

```
var characters = [
  { 'name': 'barney',  'age': 36, 'blocked': false },
  { 'name': 'fred',    'age': 40, 'blocked': true },
  { 'name': 'pebbles', 'age': 1,  'blocked': false }
];

var youngest = _.chain(characters)
  .sortBy('age')
  .map(function(chr) { return chr.name + ' is ' + chr.age; })
  .first()
  .value();
```

So if want to use the same chain i will create new one for each time

```
_.map([characters1, characters2, characters3], function(el) {
  return _.chain(el)
    .sortBy('age')
    .map(function(chr) { return chr.name + ' is ' + chr.age; })
    .first()
    .value();
});
```

This will create 1000 chains for 1000 arrays, so it will be additional job for GC.

I suggest to make possible to reuse the same chain 1000 times

```
var getFirstYoungest = _.chain(characters)
  .sortBy('age')
  .map(function(chr) { return chr.name + ' is ' + chr.age; })
  .first()
  .value();

_.map([characters1, characters2, characters3], getFirstYoungest);
```

or so 

```
_.map(
  [characters1, characters2, characters3],
  _.chain()
    .sortBy('age')
    .map(function(chr) { return chr.name + ' is ' + chr.age; })
    .first());
```

so lazy evaluation https://github.com/lodash/lodash/issues/274 became much more better

**Comment by jdalton** [comment]
I can dig a combo of `value(<val>)` (plants and runs the sequence) and `plant(<val>)` to simply plant a new value the sequence is applied on.

**Comment by jlgrall** [comment]
I am using something close:
```javascript
var filterStuff = _.chain()
				.filter()
				.filter()
				.end();
```

Instead of:
```javascript
var filterStuff = function(stuff) {
	return _.chain(stuff)
		.filter()
		.filter()
		.value();
}
```

Even if I call `filterStuff()` many times, the chain is built only once. Here is the definition of my `.end()`:
```javascript
_.prototype.end = function() {
	var chain = this;console.log(this)
	return function(value) {
		return chain.plant(value).value();
	};
};
```

I know that `_.plant()` clones the chain, but at least it skips the building of the chain.
And from what I saw, if I put a value in `_.chain()` that is the same type as the value that I will then pass to the ended chain, lodash might optimize the chain with the right lazy wrappers.

Any thought on this ? Did you find a better way ?

**Comment by jlgrall** [comment]
Maybe an idea to make it more efficient would be something like that:
```javascript
_.prototype.end = function() {
	var chain = cloneChain(this);
	return function(value) {
		return chain.set__wrapped__(value).value();
	};
};
```

Where:
1. `cloneChain()` would clone the chain without modifying the `__wrapped__`
2. `set__wrapped__()` would change the `__wrapped__` property of the chain (or of the nested `__wrapped__`)

With the benefit that you are working on a private clone of the chain. Allowing the original chain to be reused or modified somewhere else.
