### ISSUE TITLE
Filter is not working Collection have object inside object

### ISSUE THREAD

**Issue by rameshblossom** [lodash/lodash#731]
`_.filter` is not working complex array. Filter can't able too filter if i gave condition like,

`_.filter(characters, { 'person.age': 36 });`

**Comment by fusepilot** [comment]
@jdalton is this still planned? I see that get and set accept dot notation, would be great if filter did as well.

**Comment by jdalton** [comment]
Dot notation is in via `_.filter(objects, 'foo.bar', value)` now though in v4 it'll be `_.filter(objects, ['foo.bar', value])`.
