### ISSUE TITLE
ES6 iterables

### ISSUE THREAD

**Issue by gampleman** [lodash/lodash#737]
ES6 provides a number of datastructures that are [iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/iterable). It would be nice if lodash supported these.

**Comment by hawkrives** [comment]
+1 for supporting iterables.

**Comment by brandonhorst** [comment]
If you are "keeping an eye on the popularity", I'll throw in a +1. It makes a ton of sense to be able to handle iterators the same way I handle every other collection in JS - a _ function or chain.

**Comment by mathieumg** [comment]
+1 :+1:

**Comment by topicus** [comment]
+1

**Comment by overlookmotel** [comment]
+1

**Comment by jdalton** [comment]
Related to https://github.com/jashkenas/underscore/pull/2208#issuecomment-110005072

**Comment by DylanPiercey** [comment]
+1

**Comment by yannickglt** [comment]
:+1:

**Comment by DylanPiercey** [comment]
@jdalton 

```javascript
function* fibonacci(){
  var fn1 = 1;
  var fn2 = 1;
  while (true){  
    var current = fn2;
    fn2 = fn1;
    fn1 = fn1 + current;
    var reset = yield current;
    if (reset){
        fn1 = 1;
        fn2 = 1;
    }
  }
}

_.take([...fibonacci()], 3); // Not going to work.
```

Iterator support would make lodash work well with generators as well - this could be pretty handy.

**Comment by jdalton** [comment]
@DylanPiercey
>  _.take([...fibonacci()], 3); // Not going to work.

I'm fine with that.

> this could be pretty handy.

Maybe, I'm fine for now punting to a specialized mixin or lib.

**Comment by darrentorpey** [comment]
@jdalton, could you please explain what you mean by a specialized mixin or lib? Is there an example of the kind of lib you have in mind?

**Comment by jdalton** [comment]
Before features are included in core many times they are implemented outside of lodash as a [mixin](https://lodash.com/docs#mixin). For example see [lodash-deep](https://github.com/marklagendijk/lodash-deep).

**Comment by lukasolson** [comment]
:+1:

**Comment by jdalton** [comment]
In a step towards this in master lodash wrappers are now iterators and iterable.
```js
var w = _({ a: 1, b: 2 });
Array.from(w);
// => [1, 2]
```

**Comment by darrentorpey** [comment]
That's really helpful, @jdalton -- thanks!

**Comment by mhelvens** [comment]
Awesome. Two comments on that:

1. To stay compatible with ES6 convention as seen in `Map`, `Set` and `Array`, you might want to consider adding `.values()`, `.keys()` and `.entries()` methods to lodash wrappers.

2. Is `.values()` a sensible default behavior for a lodash-wrapped object? I would expect a wrapped array to default to `.values()` and a wapped object to default to `.entries()`.

**Comment by Xotic750** [comment]
I recently became interested in ES6 Genereator and Iterators and began to play with them seriously because ES6 was starting to be available in the leading browsers. I found that what was provided was pretty limited and it was all forward iteration. So I began to write some code to see what could be done for reverse iteration. Anyway, things started to grow beyond my initial experiments and I began thinking how it would be nice if lodash provided compatibility. Here is my experimental project, it does quite a bit already and works quite nicely in older environments too. I'd like to eventually integrate it somehow with lodash, but I haven't got that far yet. Feel free to leave comments and criticisms. :)

**Comment by jvivs** [comment]
+1, iterate all the things!

**Comment by koraa** [comment]
+1, iterators FTW

**Comment by mathieumg** [comment]
Aren't they now supported with https://github.com/lodash/lodash/releases/tag/4.0.0 ?

**Comment by jdalton** [comment]
> Aren't they now supported with https://github.com/lodash/lodash/releases/tag/4.0.0 ?

Our chain/sequence wrapper is an iterator and iterable and some methods like `_.toArray` work with iterators. However most other methods don't support them.

**Comment by nfcampos** [comment]
iterator support in methods like `_.zip` `_.fromPairs` `_.toPairs` would be very useful

**Comment by jdalton** [comment]
@nfcampos For these cases I'm fine with folks doing:
```js
_.zip([...a], [...b]);
```

**Comment by nfcampos** [comment]
yep for small arrays that's fine, for really large arrays you'd be creating two large intermediate arrays, which could be avoided if `_.zip` consumed them as iterators

**Comment by jdalton** [comment]
The array concern is such a micro optimization. It's hardly ever an issue and totally not worth bogging down the entire library to support. It's superstitious nonsense. If it's a --real-- problem then implementing your own flavor is the best route.

**Comment by nfcampos** [comment]
When i say large I mean really large, like over 100.000, that's why it starts to matter, but I get that's probably not what lodash is designed for.
But still seems weird to not be able to do this (since `keys()` is now a native method on arrays):
```js
const names = ['Hi', 'There']
_.zipObject(names, names.keys())
```

**Comment by jdalton** [comment]
> When i say large I mean really large, like over 100.000, that's why it starts to matter, 

Yep, I understand what a large array is.

> But still seems weird to not be able to do this (since keys() is now a native method on arrays):

It's documented to accept an array not an iterator. Pretty simple stuff.

**Comment by olsonpm** [comment]
+1 - though I appreciate all the example workarounds for now.  They do seem clean enough.

**Comment by jedwards1211** [comment]
see https://fitzgen.github.io/wu.js

**Comment by lambrojos** [comment]
:+1:

**Comment by acjay** [comment]
`takeWhile` would be particularly useful with iterators, especially infinite ones

**Comment by code-guru** [comment]
👍

**Comment by arcanis** [comment]
Would a `isIterable` method make sense?

**Comment by nazrhyn** [comment]
I just tried to do this...

```js
_.map(map.values(), 'property');
```

...and found out it doesn't work yet. Definite :+1: from me on Iterator support.

**Comment by jdalton** [comment]
Use the spread operator.
```js
_.map([...map.values()], 'property');
```

**Comment by nazrhyn** [comment]
I am doing that. My comment was more for:
> That said, we'll keep an eye on the popularity of the request.

**Comment by jdalton** [comment]
With the simplicity of spread I'm not sure iterator support is high on my list.

**Comment by nazrhyn** [comment]
I imagine that arguments could be made about the efficiency of creating a new array and depleting the iterator just so that it can be enumerated. Also, any possible deferred execution benefits (e.g. from the chain operations) will only be half-fold, as the iterator depletion will always have to happen immediately at the call site versus only when the enumeration begins as part of the mechanism. There's also the more basic supporting language features argument, as well.

Those arguments are academic, in most cases, though. If the library doesn't support it, then people can just avoid using Map, Set, etc. in situations where that level of efficiency is needed, perhaps.

Still a plus-one from me, though.

**Comment by jdalton** [comment]
I'm going to close this as a `won't` fix since spread handles the Lodash use case.

**Comment by acjay** [comment]
Spread also doesn't work for infinite iterators.

**Comment by jridgewell** [comment]
Side note: locking prevents `+1`-ing the OP. Might want to reopen it tomorrow?

**Comment by jdalton** [comment]
Naw, the votes are in and mostly prompted by a twitter campaign. Regardless of votes it's not happening.
