### ISSUE TITLE
Documentation : add anchor links to relevant methods.

### ISSUE THREAD

**Issue by Delapouite** [lodash/lodash#755]
Hi.

https://lodash.com/docs#findIndex
The description of the `_.findIndex` function says :

> This method is like _.find except that it returns the index of the first element that passes the callback check, instead of the element itself. [...]

Would it be possible to add a link on  `_.find` pointing to the relevant part in the doc?
Note that this is just an example and this could be applied in other places.

**Comment by Delapouite** [comment]
Hi.

I can't find where those internal links between functions were added.

What about using `{ @link }` inline tags as described in jsdoc?
http://usejsdoc.org/tags-inline-link.html

**Comment by StreetStrider** [comment]
> add a link ... to the relevant part in the doc
> this could be applied in other places

I vote up for this. :+1: It's ridiculous not to have this in hypertext environment.

**Comment by jdalton** [comment]
> I can't find where those internal links between functions were added.

Fixed the doc generation script for the site to include these.
