### ISSUE TITLE
_.spread

### ISSUE THREAD

**Issue by Delapouite** [lodash/lodash#756]
Hello.

Sorry to bother you, does lodash currently provide a simple spread like function doing this ? 

```
function spread(func) {
    return function(array) {
        return func.apply(void 0, array);
    }
}
```

I've checked the Functions and Utilities sections in the doc but I may have missed it.
Thanks

**Comment by naholyr** [comment]
@arseniew it should be kept as simple as possible, the latter example is nice but very complicated, and very nicely handled by ES6. I think if one **really needs** such circumvolution, one should embrace ES6 syntax. You will never achieve such usability without a syntax change, so I don't think it worth the try.

I'd keep it like @Delapouite initial suggestion, adding an optional "this-context" to make it look like its cousins:

```js
function spread(func, self) {
  "use strict";
  return function(array) {
    return func.apply(self, array);
  };
}
```

Does this has a chance to get to LoDash soon?

**Comment by jdalton** [comment]
> Does this have a chance to get to LoDash soon?

Open a PR :D

**Comment by naholyr** [comment]
Here we go :)
