### ISSUE TITLE
Lodash error (firefox + greasemonkey)

### ISSUE THREAD

**Issue by pihentagy** [lodash/lodash#759]
Don't know where to report, but anyway, the problem is:
- install greasemonkey on firefox
- install this test script: https://greasyfork.org/en/scripts/5283-testing
- load a greasyfork.org page
- expected: you should see an alert
- actual: nothing, but an error `Permission denied to access property 'toString' lodash.min.js:30`

note: script loads https://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js

**Comment by jdalton** [comment]
Hi @pihentagy!

I'm wanting to simplify the `root` definition. It looks like the guard for this is no longer needed as:
```js
window === this.window // true
```
