### ISSUE TITLE
More documentation on the difference between lodash and underscore would be nice.

### ISSUE THREAD

**Issue by philipwalton** [lodash/lodash#76]
Last night I tried to "drop in" lodash.js on an old project of mine that was using underscore.js and I ran into a few problems. I was using _.mixin() to extend the functionality of the library, and the unit tests for those mixins started failing. I spent a great deal of time debugging the situation before finally discovering that _.forEach() will exit early when the iterator function returns false.

Regardless of the merits of this feature, it did end up causing my code to break and it did take me a while to track down. The problem was further compounded by the fact that I'm using CoffeeScript which, by default, returns the last line of a function, so I was returning false without even thinking about it. Here was my code:

```
# compact arrays, even those nested deep within objects
compactDeep: (obj) ->
  return obj unless typeof obj is 'object' and obj isnt null
  result = if _.isArray(obj) then _.compact(obj) else _.clone(obj)
  _.each(result, (value, key) -> result[key] = _.compactDeep(value))
  result
```

As you can see, it doesn't exactly jump out at you that my _.each() function might be returning false.

In my opinion, I think there are two ways to help prevent this kind of thing from happening in the future:

1) Make lodash and underscore truly have the same API where the only differences are in extra methods or additional parameters in functions. Lodash is advertised as a drop in replacement which gives the impress that the APIs are exactly the same.

2) Have a section in the documentation that clearly lays out all of the differences, however minor, between the APIs. This would allow people to know whether or not they can truly drop in lodash without issue. (I know this is mentioned in the Underscore bug fixes section, but I think it could be more clear than that.)

Anyway, just a thought. In general I love lodash and the extra functionality it contains over underscore, specifically the deep clone option!

**Comment by ExplodingCabbage** [comment]
Note for future people landing on this page - the Wiki page linked to by @jdalton no longer exists, but https://github.com/lodash/lodash/wiki/Migrating contains a list of differences between lodash and Underscore.
