### ISSUE TITLE
`with` in compiled templates incompatible with 'use strict'

### ISSUE THREAD

**Issue by jamesplease** [lodash/lodash#763]
I'm changing over my apps to use an ES6 transpiler loader + Webpack, but the `with` statement output by precompiled templates is incompatible with use strict, so I get a build error.

Are there any known workarounds to this?

**Comment by dhaval-lila** [comment]
I have very similar issue when precompiling ejs templates to js function i get the with error any solution to this?
below is the my jest transformer
```
require('ejs-loader');
const _ = require('lodash');

module.exports = {
  process(src) {
    return `module.exports = ${_.template(src)}`;
  },
};
```
