### ISSUE TITLE
merge overwrites source object

### ISSUE THREAD

**Issue by baweaver** [lodash/lodash#765]
On terms of intuitive bearing of other functionally oriented libraries, merge blitzing the 'source' object is very odd.

``` javascript
var a = {a: 1, b: 2},
    b = {b: 10, c: 20};

_.merge(a,b); // => {a: 1, b: 10, c: 20} Looks good!

console.log(a); // Object {a: 1, b: 10, c: 20} ....why?
```

I realize you can do this:

``` javascript
_.merge({}, a, b);
```

....but that's seriously off to me at least. That's not something I'd be expecting when using the merge function, I'd expect a new object instead to which if I wanted to override I'd do:

``` javascript
a = _.merge(a,b);
```

In terms of chaining or functional style, this can make for a nasty little speed bump to some despite being in the documentation.

**Comment by joeyyang** [comment]
I know this is closed, but the behavior @baweaver described was what I was expecting too. I use Lodash when programming functionally, and having a method destructively modify one of the inputs is really unexpected.

It would be awesome to have a separate method or a flag to set that would leave the original object untouched if I needed to reference it again.

**Comment by StreetStrider** [comment]
@joeyyang, you can always `_.clone` your object before merging. It is explicit and you see what actual perfomance drawback you recieve.

**Comment by joeyyang** [comment]
@streetstrider I guess that's more traditional JS-like. Perhaps this functionality is better left to some other sort of immutable library. Thanks!

**Comment by jdalton** [comment]
> I guess that's more traditional JS-like. Perhaps this functionality is better left to some other sort of immutable library. Thanks!

Mix it in, mix it in :notes: [_.mixin](https://lodash.com/docs#mixin).
