### ISSUE TITLE
How to escape tokens in templates?

### ISSUE THREAD

**Issue by redonkulus** [lodash/lodash#772]
I have the following syntax in my template: `${COVERAGE_DIR:-artifacts}`, when `_.template()` runs, it errors out with: `[SyntaxError: Unexpected token :]`. I've checked the docs but didn't see a way to tell lodash to skip this block from being interpolated. What is the correct way?

**Comment by YoungColor** [comment]
Hi,  I don't want "${appId}" be compiled as variables in my html <scripts>?

I try this in my gulpfile `var _ =  require('lodash');
_.template('appId', null, _.templateSettings);`, but not work.

I am a beginner, can you give me more help?

**Comment by jdalton** [comment]
Hi @YoungColor!

You can do:
```js
 _.template('appId', null, { 'interpolate': /<%=([\s\S]+?)%>/g })
```

**Comment by YoungColor** [comment]
Thanks for help, but it still don't work. And I have tried `_.template('appId', null, { 'interpolate': /${([\s\S]+?)}>/g });`. I use `gulp-wrap` plugin, does it matter?
