### ISSUE TITLE
Wrong number of iterations for objects that contain numeric keys

### ISSUE THREAD

**Issue by evgenyboxer** [lodash/lodash#799]
I have encountered a very strange bug which seems to happen only in iPhone6 (iOS8) running Safari browser.

Consider the following code: ( you can also test the jsfiddle: http://jsfiddle.net/evgenyboxer/rcsz27v1/1/ )

```
var numOfIterations = 10000; 
var counter = 0;
var obj = {
  1: 'foo',
  8: 'bar',
  50: 'baz'
};

var expectedCounter = 3;

for (var i = 0; i < numOfIterations; i++) {
  _.filter([], function() { return true; });
}

_.filter(obj, function() {
  counter++;
  return true;
});

if (counter !== expectedCounter) {
  alert('Incorrect number of iterated keys: ' + counter);
} else {
  alert('Correct number of iterated keys: ' + counter)
}
```

Shockingly the output for iPhone6 is **51** and not **3** as expected.
Why is it **51**? well, it takes the highest key ( which is **50** ) and adds 1 to it.
If you add a new key with a higher value ( such as **500** ) the output will be **501**

If you change the "numOfIterations" to say **10** `var numOfIterations = 10` the problem will **NOT** occur.
The theory behind this problem might be optimisations performed by the nitro JavaScript engine.

The problem reproduces in **lodash 2.4.1 ( modern build )**, but isn't reproduced in Edge / Compat mode. I added a test and saw it failing using iPhone 6.
I guess its the way lodash treats collections. It thinks that the object is an array of the largest key value ( in my example, that was **50** )

```
function filter(collection, callback, thisArg) {
      var result = [];
      callback = lodash.createCallback(callback, thisArg, 3);

      var index = -1,
          length = collection ? collection.length : 0;

     // length is a number, and equals to the highest key value!!!
      if (typeof length == 'number') {
```

One more thing I just found... if the object is a sparse array it returns the **correct** number of iterations! Which probably makes my theory about a possible bug in the nitro JavaScript engine right.

```
var obj = {
   1: 'foo',
   2: 'bar',
   1000: 'baz'
}

// will return 3 iterations
```

**Comment by Diokuz** [comment]
@jsalton +1 here. latest ios, safari.
I think its a safari bug, but it reproduced only on lodash .each

**Comment by d10** [comment]
Related to jashkenas/underscore#2081.
