### ISSUE TITLE
wishlist: flatMap

### ISSUE THREAD

**Issue by trashhalo** [lodash/lodash#812]
Something I use a lot in ruby is [flat_map](http://apidock.com/ruby/Enumerable/flat_map) its equivalent to `_.flatten(_.map(` what makes flatMap especially useful is it can be chained down layers of object hierarchy.

Use case Examples:
- You have a list of boxes that each have a list of items in that box. Your UX wants to show a list of items.
- You have a list of adoption centers, centers have list of adoption records, adoption records list the pet owners. You want to know all pet owners across all centers. flatMap twice, then uniq.

**Comment by AlexGalays** [comment]
For what's it's worth, I would like to +1 @trashhalo even If I know there is a lot of resistance to add this.
I use 'flatMap' on every single project (or in the case of lodash, chaining map and flatten if the arrays are not too big).

I think it would be an excellent addition (unlike the overloading of .flatten) for only a few tiny bytes more in lodash. Extending lodash in user-land is a pain when using commonJS modules.

**Comment by pfultz2** [comment]
Using something like `flatMap` is very useful, especially for list comprehension and generators. Like in python if I want to lazily return the pythagorean triples I could do this:

```python
def triples(numbers):
    for x in numbers:
        for y in numbers:
            for z in numbers:
                if x*x + y*y == z*z: yield (x, y, z)
```

And in Javascript, I can easily do this as well using `flatMap`:

```javascript
function triples(numbers) {
    return _(numbers).flatMap(function(x) {
        return _(numbers).flatMap(function(y) {
            return _(numbers).flatMap(function(z) {
                if (x*x + y*y === z*z) return [[x,y,z]];
                else return [];
            });
        });
    });
}
```

However, using the `_.flatten(_.map(` combo is more cumbersome:

```javascript
function triples(numbers) {
    return _.flatten(_(numbers).map(function(x) {
        return _.flatten(_(numbers).map(function(y) {
            return _.flatten(_(numbers).map(function(z) {
                if (x*x + y*y === z*z) return [[x,y,z]];
                else return [];
            }));
        }));
    }));
}
```

**Comment by jdalton** [comment]
The `_.flatten(_.map(` combo doesn't look that bad.
You could always do:
```js
var flatMap = _.compose(_.flatten, _.map)
```

**Comment by pfultz2** [comment]
> You could always do:

Interesting, how do I add that back to lo-dash? So I can write `_(numbers).flatMap`?

**Comment by jdalton** [comment]
If in Node land first do
```
// use runInContext to create a new pristine lodash instance
var _ = require('lodash').runInContext();
```
then
```js
_.mixin({ 'flatMap': _.compose(_.flatten, _.map) });

_(numbers).flatMap(....);
```

**Comment by trashhalo** [comment]
Oh neat! thanks for taking the time to show how I might add it myself.

**Comment by davinkevin** [comment]
It should be good to have this implementation by default... we find that in many language now. 

Thanks :D

**Comment by jdalton** [comment]
Ya, I think in v4 we'll add it again, as `flatMap`.

**Comment by davinkevin** [comment]
thanks

**Comment by RReverser** [comment]
> Ya, I think in v4 we'll add it again, as flatMap.

Was the decision made not to add it?

**Comment by jdalton** [comment]
See [_.flatMap](https://lodash.com/docs#flatMap).

**Comment by RReverser** [comment]
Ah. Weird. Couldn't see it in console with 4.11.1 installed, but appeared with 4.12.0.
