### ISSUE TITLE
Arity of curried function not taken into account when multiple values provided

### ISSUE THREAD

**Issue by my8bird** [lodash/lodash#814]
The following example shows a bug where setting the arity of the curried function does not prevent the function from using more then that number of arguments.

Here I create a curried function of arity two which allows me to have a set of things and then keep checking if an item is in it.  This is needed since `_.contains` provides a third argument of a starting index which I need to avoid if I want my function to work as part of a `_.filter` or other such method which provides more then a single argument to the callback

**bug** Example

``` javascript
_.curry(_.contains, 2)([1,3,5])(1)
// -> true
_.curry(_.contains, 2)([1,3,5])(1, 2)
// -> false
```

**usage** Example

``` javascript
_.filter(some_items, _.curry(_.contains, 2)(allowed_items));
```

I tried using `_.partial` but this also has the third argument issue and there it makes more sense, IMO.

**Comment by 0xR** [comment]
I am looking at the example of @jdalton, and I would write it without the `rearg` and a `curryRight` instead of a normal `curry`, but this doesn't seem to work. Why doesn't this work? Is this a bug?
```js
var contains = _(_.contains).ary(2).curryRight(2).value();
contains('b')(['a', 'b', 'c'], 2);
// -> false
```

**Comment by jdalton** [comment]
> Why doesn't this work? Is this a bug?

Not a bug, by using `curryRight` the args your passing are:
```
// contains('b') is
contains(_, 'b');
// contains('b')(['a', 'b', 'c']) is
contains(['a', 'b', 'c'], 'b');
// contains('b')(['a', 'b', 'c'], 2);
contains(['a', 'b', 'c'], 2, 'b');
```

Since `2` is not in the array it returns `false`.
