### ISSUE TITLE
Can't remove lodash directory in Windows

### ISSUE THREAD

**Issue by alexewerlof** [lodash/lodash#823]
Yes some of us have to work on Windows where it can't handle very very long file names. We use a bunch of node modules but lodash has caused us a lot of trouble when we want to delete or move directories. Unfortunately for such a popular library the problem is almost inevitable.
So here is the windows error message: 

<img src=https://cloud.githubusercontent.com/assets/835750/5396600/cbb109c8-8153-11e4-9060-f10a8b0b50ec.png height=40% width=40%>

And this is an example of how nested the directory structure is:

<img src=https://cloud.githubusercontent.com/assets/835750/5396577/94b7e6b2-8153-11e4-8f9f-17a473cdb64b.png height=50% width=50%>

Note: the last directory is not the end. Windows is simply unable to show more!

Would it be possible to have less nesting structure inside lodash?

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages.

Related to #501.
