### ISSUE TITLE
_.omit copies enumerable properties from prototype chain as well

### ISSUE THREAD

**Issue by UltCombo** [lodash/lodash#826]
I'm not sure whether this is expected behavior, but if so it would be nice to have this behavior documented.

`_.clone` only copies enumerable own properties, while `_.pick` and `_.omit` copy enumerable properties from the prototype as well. This is rather inconsistent IMO, and should at least be documented.

**Comment by mike-marcacci** [comment]
This one was quite a head scratcher... I couldn't figure out how properties kept working their way down the prototype chain and into my logs. It might be nice to note this quirk in the docs, or perhaps provide another function with the following behavior (which is the vast majority of my use case):

```js
function without(object, predicate, thisArg) {
	return _.omit(_.extend({}, object), predicate, thisArg);
}
```

**Comment by jdalton** [comment]
It's documented.

**Comment by mike-marcacci** [comment]
Haha, yes it is :) Must have missed it. Thanks!
