### ISSUE TITLE
Should noop be implemented as reference to Function.prototype?

### ISSUE THREAD

**Issue by Ginden** [lodash/lodash#846]
`Function()` are few bytes saving in resulting minified code.

```
Function.prototype.toString(); // function () {}
Function().toString(); // function anonymous () {}
```

**Comment by megawac** [comment]
It probably doesn't save much in gzip bytes anyway. I'd say stay well away from this

**Comment by jdalton** [comment]
You can see the behavior shift from [ES5](https://es5.github.io/#x15.4.4) to [ES6](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-properties-of-the-array-prototype-object). However [Function.prototype](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-properties-of-the-function-prototype-object) remains a function.
