### ISSUE TITLE
Any desire for a deep rename with obj/array support in Lodash?

### ISSUE THREAD

**Issue by owenallenaz** [lodash/lodash#847]
In another project I'm working on we frequently come across the need to do deep renames of objects and objects within arrays. I end up needing this a lot when dealing with REST services like social media APIs to extract the useful bits into a simpler structure.

Simple Example

Convert this:

```
{
	id : "5",
	name : "My Name",
	image : {
		resource : {
			url : "http://www.foo.com/image.png"
		}
	}
}
```

into this:

```
{
	recid : "5"
	title : "My Name",
	imageUrl : "http://www.foo.com/image.png"
}
```

Complex Example

Convert this:

```
{
	id : "5",
	docs : [
		{
			name : "Doc 1",
			description : "Doc 1 text"
		},
		{
			name : "Doc 2",
			description : "Doc 2 text"
		}
	]
}
```

into this:

```
{
	recid : "5",
	items : [
		{
			recid : "5",
			title : "Doc 1",
			text : "Doc 1 text"
		},
		{
			recid : "5"
			title : "Doc 2",
			text : "Doc 2 text"
		}
	]
}
```

In some cases we need to reach inside objects and pull keys to the root level. In other cases we need to return more deeply nested objects based on root keys. Either way, the function I have breaks it down so I can do all of it with a single function call with, I think, a fairly natural syntax.

Here's an example that performs the conversion I've outlined above:

```
// the source data we're working with
var data = {
	id : "5",
	docs : [
		{
			name : "Doc 1",
			description : "Doc 1 text"
		},
		{
			name : "Doc 2",
			description : "Doc 2 text"
		}
	],
	created : "10/20/2014"
};

// the map which declares how what that data should become
// if a key is not declared in the map, it won't be returned
// "root." reachs to our original object
// "current." stays at our current iteration point with the current object/array
// at the root level root === current
var map = {
	recid : "root.id", // same as current.id
	items : {
		key : "root.docs",
		map : {
			recid : "root.id", // reaches back to the root and puts the id within each item
			title : "current.name",
			text : "current.description"
		}
	}
}

var result = _.deepMap(data, map);

// result
{
	recid : "5",
	items : [
		{
			recid : "5",
			title : "Doc 1",
			text : "Doc 1 text"
		},
		{
			recid : "5"
			title : "Doc 2",
			text : "Doc 2 text"
		}
	]
}
```

Is there any desire for this in lodash core? If so, I can submit a pull request with unit tests, but I didn't want to bother if it feels to edge-casey.

Related SOs:
http://stackoverflow.com/questions/8747561/is-there-any-way-to-rename-js-object-keys-using-underscore-js
http://stackoverflow.com/questions/19752516/renaming-object-keys-recursively

**Comment by jdalton** [comment]
Deep property helpers are on our [roadmap](https://github.com/lodash/lodash/wiki/Roadmap) for a future release. Is there an npm package that already addresses this functionality?

**Comment by Alexsey** [comment]
Such tool would be super useful. But then we would ask for functions support instead of just text field names, then some instruments for recursive structures... and than we came up with XSLT for JSON. There where some intents to do so, like <a href='http://goessner.net/articles/jsont/'>JsonT</a> (author was using it to create html, but idea is the same). I would applaud standing for something like this (it is also a great part of my work too), but I'm afraid it is more than just a single function to implement.

If anyone knows any other solutions - would be very interesting to know

**Comment by falafflepotatoe** [comment]
similar to graphQL.

`_query("{recid($id),title($name),Imageurl($url)}", "id=1234")`

**Comment by jdalton** [comment]
Deep property helpers were added in v3.7.0.
