### ISSUE TITLE
The opposite of _.pluck method?

### ISSUE THREAD

**Issue by muzuiget** [lodash/lodash#848]
The most common use-case for map, convert array to object, for example

```
var headers = ['name', 'age'];
var characters = [
  ['barney', 36],
  ['fred', 40 ]
];

_.unpluck(characters, headers);
// → [{'name': 'barney', 'age': 36},  {'name': 'fred', 'age': 40}];
```

**Comment by jdalton** [comment]
This looks similar to [_.zipObject](https://lodash.com/docs#zipObject).

**Comment by jdalton** [comment]
In fact you can do this with `_.map(characters, _.partial(_.zipObject, headers))`

**Comment by muzuiget** [comment]
Yes, so why I said "The most common use-case for map", very common when you parse a csv-like file.
