### ISSUE TITLE
_.zipObject(array, function)

### ISSUE THREAD

**Issue by eyy** [lodash/lodash#849]
It would be nice, I think, if _.zipObject accepted a function as a second parameter, and map it over the first array.

```js
function zipMap (arr, fn) {
    return _.zipObject(arr, arr.map(fn));
}

var result = zipMap([ 'a', 'b', 'c' ], function(name) {
    return ' i am ' + name;
})};

// result
{
    a: 'i am a',
    b: 'i am b',
    c: 'i am c'
}
```

**Comment by jdalton** [comment]
I think we'll leave this for composition.

**Comment by CrossEye** [comment]
This can be handled pretty easily with existing tools.  With composition, as JDD suggested, or via `reduce`:

    _.reduce([ 'a', 'b', 'c' ], function(obj, name) {
        obj[name] = ' i am ' + name;
        return obj;
    }, {}); //=> {a: " i am a", b: " i am b", c: " i am c"}

**Comment by jdalton** [comment]
Or `_.transform` too:
```js
_.transform([ 'a', 'b', 'c' ], function(obj, name) {
    obj[name] = ' i am ' + name;
}, {});
```
