### ISSUE TITLE
lodash.underscore doesn't expose noop method

### ISSUE THREAD

**Issue by chicoxyzzy** [lodash/lodash#851]
lodash.underscore doesn't expose `noop` method but it should

version 2.4.1

**Comment by chicoxyzzy** [comment]
Oh sorry now I see version lodash supports is 1.5.2 but `noop` was added in underscore 1.7.0

**Comment by jdalton** [comment]
Yap. Going forward in Lo-Dash v3.0 we're dropping the Underscore build because they have aligned significantly with us so the need to maintain a separate build isn't as strong. For the areas of difference, like `_.extend`, we'll offer an individual `underscore.extend` package.
