### ISSUE TITLE
[Feature Request] zip array as cartesian product

### ISSUE THREAD

**Issue by muzuiget** [lodash/lodash#852]
Like `zip()` but find all combinations of options

```
_.zipProduct([['a', 'b'], [1, 2]])
// → [["a", 1], ["a", 2], ["b", 1], ["b", 2]]
```

I found a implement at http://stackoverflow.com/questions/12303989/cartesian-product-of-multiple-arrays-in-javascript

**Comment by jdalton** [comment]
I think this would be a better fit as a mixin. Though I'd like to see if it could be golfed down further than https://gist.github.com/ijy/6094414.

**Comment by ChrisJefferson** [comment]
Just in case anyone comes across this, the gist jdalton links to above doesn't work with  lodash 3.9.3 (that's the version I'm using), I assume at some point the behaviour of '_flatten' changed. A fixed version is at:

https://gist.github.com/ChrisJefferson/cb8db2a4c67a9506c56c

**Comment by phated** [comment]
I'd actually like to see a cartesian zip sort of method.  The utilities I found on npm for this scenario when I needed it were really bad. @jdalton can we remove the wontfix?

**Comment by jdalton** [comment]
I may be off but I think this is still a bit too narrow a use case to include. However if the demand is there we'll reconsider.

**Comment by pimterry** [comment]
+1, I'd also use this.

**Comment by devinus** [comment]
Wow, I just discovered I needed this as well. :+1:

**Comment by mpetrovich** [comment]
+1

We've found a need for this as well. Specifically, to generate a list of all possible option pairs given two lists of user-selected options (e.g. ages and locations).

**Comment by jotham** [comment]
Me too, super useful for building combinations before supplying to async operations as batches

**Comment by mfine15** [comment]
Echoing everyone else, this would be a big help in reducing boilerplate required for functional use of promises.

**Comment by bjorn-ali-goransson** [comment]
No, this is a given `include`. +1

I was actually sure it was already included!

**Comment by jamiemchale** [comment]
Adding a use case for consideration: fanning out of data to multiple nodes in a data store such as firebase. For example "fan out updates 1, 2 and 3 to users A, B and C".

https://www.firebase.com/blog/2015-10-07-how-to-keep-your-data-consistent.html

**Comment by bameda** [comment]
:+1:

**Comment by DiesIrae** [comment]
:+1:

**Comment by j4hangir** [comment]
:+1:

**Comment by jdalton** [comment]
![](http://i.imgur.com/8zXjYXy.gif)

**Comment by DaZzz** [comment]
:+1:

**Comment by tansongyang** [comment]
I did a lodash/fp implementation [here](https://gist.github.com/tansongyang/9695563ad9f1fa5309b0af8aa6b3e7e3).

**Comment by jdalton** [comment]
You can use `_.flatMap` too.

**Comment by ramadis** [comment]
:+1:

**Comment by danjm** [comment]
+1

**Comment by bbottema** [comment]
yep, cartesian product would be nice to have.

**Comment by danjm** [comment]
+1

Also, a note that there were comments deleted from this thread. I had made a previous comment that is no longer here (and that was not by my doing). When I notified Github two weeks ago, I sent them this screenshot from a version of this page cached on google:

<img width="779" alt="screen shot 2016-07-31 at 9 44 13 pm" src="https://cloud.githubusercontent.com/assets/7499938/17646617/632153b4-61ac-11e6-8d8b-9dc9b357847e.png">

Note the missing comments from March 24 and May 4 (there are also others missing), and how **there used to be 17 participants and now there are only 11**.

I have not heard back from Github yet on the cause or whether the data can be restored.

**Comment by jdalton** [comment]
I only count the reactions since I can sort by them and remove the rest of the noise.

**Comment by robbert-vdh** [comment]
Would be great to have for emulating list comprehensions.

**Comment by jonathan-fulton** [comment]
+1

**Comment by fletom** [comment]
+1

**Comment by cvkline** [comment]
d3-array v1.1 now has  `d3.cross` which does exactly this, if that's an option for you.

**Comment by daniele-orlando** [comment]
+1

**Comment by ZuBB** [comment]
hi @jdalton!

just want to share with you next thing: I also had a need in this functionality and got a lucky search: https://www.npmjs.com/package/lodash.product 

I guess it can be included/merged into lodash. that package has quite big number of downloads which I would say potentially changes amount of requests for this feature 🙄

**Comment by gakada** [comment]
Hm, I was trying to point out that `zipProduct` is a special case of [`lift`](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Applicative.html#v:liftA2), as in
```js
const zipProduct = (...xs) => lift((...args) => args, ...xs)
```
so `lift` also constructs a Cartesian product, but it is more general as it is also applying a function on its elements, so it can be more effective than doing `zipProduct` and then `map`.

**Comment by stevenvachon** [comment]
@jdalton 75 thumbs

**Comment by chillinski** [comment]
I found this one. It does what was originally requested.
https://www.npmjs.com/package/lodash.product

**Comment by jotham** [comment]
Mate this thread is from 2015.  Fuck off aye.

**Comment by mvastola** [comment]
@jdalton can you offer any insight into how many votes on this are needed to connote sufficient interest to implement this?

As @chillinski points out, the popularity of the mixin he linked (which is getting 10k+ weekly downloads) points to a consistent demand for this feature. 

I'm personally a bit wary to use the mixin version though because I (like a huge portion of the userbase) use the ES distribution of lodash to facilitate tree shaking, so I'd need to do something a bit hacky to allow the mixin to do `import _ from 'lodash'` without bundling all of lodash.
