### ISSUE TITLE
Is not instant replacement for underscore

### ISSUE THREAD

**Issue by bitplanets** [lodash/lodash#853]
Please take a look at: https://github.com/harthur/brain/issues/54

**Comment by jdalton** [comment]
Correct, if instant replacement is desired we currently offer a `lodash.underscore` build, `require('lodash/dist/underscore')`.

**Comment by bitplanets** [comment]
Ok, thanks. So what do you suggest to do in this case? I can't change the "brain" lib source code.

**Comment by jdalton** [comment]
Offering a PR to the lib will help go a long way in getting it changed on their end.

**Comment by jdalton** [comment]
If you're doing a PR then go away and make it work with `lodash` primary without the underscore compat build :D

**Comment by jdalton** [comment]
*wow heck of a typo, go away -> go ahead.
