### ISSUE TITLE
#question: does _.partial in lodash provide the argument replacer token _ that underscore does?

### ISSUE THREAD

**Issue by askhogan** [lodash/lodash#854]
I was looking at lo-dash as a replacement for underscore in a few projects.  One concern I had was I utilize the underscore argument replace token _ which was added in underscore 1.6.  I see I can use partialRight, but as far as installing as a drop in replacement, does the _ token break compatibility?

http://underscorejs.org/#partial

**Comment by jdalton** [comment]
We're adding customizable placeholder support in v3.0 to `_.bind`, `_.partial`, `_.partialRight`, `_.curry`, & `_.curryRight`.
