### ISSUE TITLE
Pluck multiple keys

### ISSUE THREAD

**Issue by dandv** [lodash/lodash#855]
Despite repeated requests, [Underscore refused to implement this functionality](https://github.com/jashkenas/underscore/pull/1113).

**Comment by jdalton** [comment]
It does seem like composition should be used here. If not is there something we could add to make composition easier? Related to #698.

**Comment by dandv** [comment]
My brain goes into Inception mode when trying to read

    _.unzip(_.map(props, _.partial(_.pluck, objects)));

vs.

    _.pluck(objects, props)

**Comment by CrossEye** [comment]
If someone does write a mixin, I'd suggest that the proper name is `project`, following [Codd's relational algebra][pr].


  [pr]: http://en.wikipedia.org/wiki/Relational_algebra#Projection_.28.CF.80.29

**Comment by jdalton** [comment]
I don't think overloading `_.pluck` is the answer. This would fit better as a separate mixin, like `_.pluckAll`.
We'll keep an eye on it and add it to our [roadmap](https://github.com/lodash/lodash/wiki/Roadmap) as requests come in.

**Comment by geekflyer** [comment]
@dandv . There's a slightly more readable variant maybe:

var result = _.map(objects,_.partialRight(_.pick,['prop1','prop2']));

**Comment by Vbianshuman** [comment]
What is wrong with:

`_.map(_.pick(['prop1', 'prop2', ....]), data)`

I am using fp/lodash of course

**Comment by timkinnane** [comment]
I came across this and wasn't really happy above solutions. I came up with two alternatives, provided as mixins:

- *hasKeys* returns true if the first argument contains all the keys in the second argument (array).
- *hasPaths* same format but matches paths and/or keys, which is a bit more versatile [but slower](https://jsperf.com/teeks/1).

```
 _.mixin({
    'hasKeys': function(obj, keys) {
      return 0 === _.size(_.difference(keys, _.keys(obj)));
    }
  });
  
  _.mixin({
    'hasPaths': function(obj, paths) {
      return _.every(paths, function(path) {
        return _.has(obj, path);
      });
    }
  });
```

or in the superior coffeescript ;)

```coffee
_.mixin 'hasKeys': (obj, keys) -> 0 is _.size _.difference keys, _.keys obj
_.mixin 'hasPaths': (obj, paths) -> _.every paths, (path) -> _.has obj, path
```

e.g.
```
var myObj = { a: 'foo', b: { c: 'bar' } };

_.hasKeys(myObj, ['a', 'b']);
// => true

_.hasPaths(myObj, ['a', 'b.c']);
// => true

_.hasKeys(myObj, ['a', 'c']);
// => false

_.hasPaths(myObj, ['a', 'c']);
// => false
```
