### ISSUE TITLE
question about expose Lo-Dash in Node.js

### ISSUE THREAD

**Issue by deathfang** [lodash/lodash#857]
https://github.com/lodash/lodash/blob/master/lodash.js#L10716

why
```javascript
(freeModule.exports = _)._ = _;
// (module.exports = _)._ = _;
```
not

```javascript
module.exports = _
```

**Comment by jdalton** [comment]
We do that so there's a consistent way to access Lo-Dash across common-js and node environments:
```
var _ = require('lodash')._
```

as some common js environments lack the Node.js extension of `module.exports`.
