### ISSUE TITLE
Does _.find work for Set?

### ISSUE THREAD

**Issue by et** [lodash/lodash#858]
I may not be using `_.find` properly, but does it work similar as it does for an `Array`?

Consider this test case

```js
var s = new Set();
s.add({"prop": "value"});
_.find(s, { "prop": "value" }) // undefined
 
var arr = [];
arr.push({"prop": "value"});
_.find(arr, { "prop": "value"}); // Object {prop: "value"} 
```

**Comment by jdalton** [comment]
`_.find` works on collections which are things like arrays, strings, objects, & array-like objects. We currently don't support and have no plans to support sets or maps as collections.

**Comment by et** [comment]
Cool, thanks for the quick response.

**Comment by jdalton** [comment]
We do however use `Set` and `WeakMap` internally for optimizations in Lo-Dash v3 :D
