### ISSUE TITLE
Proper way to depend on lodash

### ISSUE THREAD

**Issue by armaanahluwalia** [lodash/lodash#859]
Just wondering what the proper way to depend on lodash is using amd. I'm writing a plugin aka mixin for lodash but wondering whether to explicity state a require(['lodash']) or not. It seems lodash doesn't define itself as anything in AMD environments so it can be used as 'underscore'. However underscore defines itself as 'underscore'.

Should I be requiring 'underscore' even though I'm really trying to state a dependency on lodash. Bit confused. Thanks!

**Comment by jdalton** [comment]
If you're starting with `lodash` then go ahead and use the name `lodash`. Aliasing is handy when devs are in transition from `underscore` to `lodash`. Not there's also [lodash-amd](https://github.com/lodash/lodash-amd/tree/2.4.1). In v3.0 we'll be splitting out `lodash-amd` into [lodash/amd](https://github.com/lodash/lodash/tree/amd) & [lodash-compat/amd](https://github.com/lodash/lodash-compat/tree/amd).
