### ISSUE TITLE
Objects with property `length` iterate incorrectly

### ISSUE THREAD

**Issue by anru** [lodash/lodash#860]
Even in last master (v. 3.0.0-pre).
```js
_.map({a: 4, length: 5}, function(v, k) { return k+'_'+v;} );
// returns "0_undefined,1_undefined,2_undefined,3_undefined,4_undefined"
```

 http://jsfiddle.net/L0vj6b6h/

**Comment by fobos** [comment]
+1. We have a big problem with it in one of our project.

**Comment by Diokuz** [comment]
+1 for _.each

**Comment by jdalton** [comment]
`_.map` and other "Collection" methods treat array-like objects as arrays by design. If you're wanting to iterate an object with a length as an object we have `_.mapValues`. If you're wanting to iterate over an object we have `_.forOwn`, `_.forIn`, and several other "Object" methods.

**Comment by Diokuz** [comment]
jQuery objects has length property for example

**Comment by Diokuz** [comment]
@jdalton the first problem is in iOs safari, which (in some cases) returns for object like {'300': 'qwe'} length property with value 301. It often crashes our app on iOs.

also, second problem is that 'length bug' is in private baseEach method which is used by many public methods like map, each, sort... What we should use instead of all of them when we know what particular Object we have?

Also, mapValues returns object, but we need an array.

**Comment by anru** [comment]
@jdalton its not clear. 
`_.map` returns *different* values and has *different* logic if you pass `{a: 4}` and `{a: 4, length: 4}` objects.

Also object with property `length` *is not* array-like in common case. The only reason to identify this object as array-like is to iterate jquery collection as an array, but it is not common case. 

What kinds of objects are array-like ? 

imho:
is array-like:
```js
{a: 4, length: 1, 0: 12}
```
not is array-like:
```js
{a: 4, length: 4}
```

**Comment by heilage-nsk** [comment]
Is it correct to identify all objects containing 'length' property as an array-like? What if I have an object representing some 3d primitive, like `var tube = {diameter: 10, length: 200}`, and want to convert all of it's property values from cm to inches, for example?
The example is obviously synthetic, but it shows the possible case where loops logic may work not as expected.

**Comment by jdalton** [comment]
@anru 
> its not clear. 
`_.map` returns different values and has different logic if you pass {a: 4} and {a: 4, length: 4} objects.

That's how "Collection" methods work. They prioritize array-like over plain objects.
I'll see about adding a doc note somewhere for it.

Array-like by the ES5/6 is anything with a valid length property only.
We use 

@Diokuz
>  the first problem is in iOs safari

The Safari [JIT bug](#799) is handled on edge.

@heilage-nsk
> Is it correct to identify all objects containing 'length' property as an array-like

Yes.

**Comment by Diokuz** [comment]
@jdalton is edge stable right now? If no, is there a stable lodash version working good in ios safari?

Also, it is very interesting how exactly that bug was handled, can you give a ref to the commit please?

**Comment by jdalton** [comment]
> is edge stable right now?

At the moment yes, you can get the [compat build](https://github.com/lodash/lodash/blob/eb36258391295b7ff0baee26f404546ecae26c20/lodash.src.js) or the [modern build](https://github.com/lodash/lodash/blob/eb36258391295b7ff0baee26f404546ecae26c20/lodash.js).

> Also, it is very interesting how exactly that bug was handled, can you give a ref to the commit please?

It's unclear. The Safari 8 JIT bug reported more than 9 months after our 2.4.1 bump and we haven't dug into why edge works.

**Comment by anru** [comment]
@Diokuz formally Dalton rights. In ES5/6 for the method Function.prototype.apply second parameter can be any object with a valid property length. It might seem like it's related to our case? Well, it's just a convenient and fast way to determine array-like object. And so it turns out that, due to certain features of the language, common objects with the length property is also array-like. Decision in this case is simple: do not use the length property in ordinary objects in favor of a count, size, etc ..

**Comment by jdalton** [comment]
ES6 expands this to [ToLength](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-tolength).
