### ISSUE TITLE
Missing Component,json

### ISSUE THREAD

**Issue by aprilb** [lodash/lodash#861]
Receiving this error during the component build:

cogent "https://raw.githubusercontent.com/lodash/lodash/3.0.0-es6/component.json" is not valid JSON +275ms

**Comment by jdalton** [comment]
We didn't support component in the es6 build because it's raw untranspiled es6 modules. The idea is to allow others to include it as an npm dep and then pull in and integrate into their own transpilation process.

**Comment by aprilb** [comment]
ok thanks.  some component upstream is requiring this which is breaking our build.

**Comment by jdalton** [comment]
> ok thanks. some component upstream is requiring this which is breaking our build.

Which one?

**Comment by aprilb** [comment]
Having a hard this determining that...here is the error:

https://gist.github.com/aprilb/7d304b33229bdc9677cb

**Comment by jdalton** [comment]
It looks like some dep didn't specify a tag and maybe component is trying to take its best guess & grabbing the `3.0.0-es6` tag.

**Comment by aprilb** [comment]
Yeah, makes sense.  Just trying to figure out which dep it is.  O_o

**Comment by aprilb** [comment]
Any chance you know of a way to determine which dep is causing this?

**Comment by sankargorthi** [comment]
@aprilb can you link or paste your dependencies list? Also, if you're on `component@1`, you might want to replace any `"*"` versions with semver.

**Comment by aprilb** [comment]
@sankargorthi not sure the best way to list dependencies.  Tried using https://www.npmjs.com/package/list-dependencies but getting an error.  ugh  I'll go through and replace "*" versions with semver.

**Comment by sankargorthi** [comment]
I meant the dependencies in your `component.json` manifest.

**Comment by aprilb** [comment]
Here is the one for the app --but there are dozens of other component.json files in various directories:
"component/notification": "0.0.5",
    "components/jquery": "2.1.1",
    "treetopllc/noble.js": "v0.9.5",
    "visionmedia/debug": "2.1.0"

**Comment by aprilb** [comment]
This is really aggravating.  It has literally broken all of our builds.

**Comment by jdalton** [comment]
I did a quick search of the deps you listed and looked into deps of deps on most but didn't turn up a `"lodash": "*"` reference. If you're text editor supports recursive search you can look for `.json` files containing `"lodash": "*"` which may narrow down the search.

**Comment by aprilb** [comment]
I grepped for any instance of lodash and ...nothing is returned.

**Comment by aprilb** [comment]
Think I found it: https://github.com/ifandelse/machina.js/blob/master/component.json

**Comment by jdalton** [comment]
Awesome! They'll need to use version `"2.4.1"` instead of `"*"`.

**Comment by aprilb** [comment]
@jdalton thanks for the help.  :+1:

**Comment by aprilb** [comment]
I submitted a PR: https://github.com/ifandelse/machina.js/pull/71

**Comment by ifandelse** [comment]
@aprilb @jdalton My apologies for the headaches and time spent on this - appreciate the heads up! It's taken care of.

**Comment by jdalton** [comment]
:fireworks:
