### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by askmatey** [lodash/lodash#864]
The website is offline since several days. Any news on this issue?

Do you maybe need additional infrastructure? I can offer you PaaS, Domains etc for free.

**Comment by KenanY** [comment]
Online for me.

**Comment by askmatey** [comment]
```[root@batmans_cave]$ wget lodash.com
--2015-01-21 20:44:45--  http://lodash.com/
Resolving lodash.com (lodash.com)... failed: Name or service not known.
wget: unable to resolve host address ‘lodash.com’```

After switching DNS, this was resolved. I've contacted my provider.

**Comment by jdalton** [comment]
@askmatey Ok cool. @mathiasbynens can do a check to make sure we're running on all cylinders too.
