### ISSUE TITLE
Lodash 3.0.0 and angular 1.3.10 does not work

### ISSUE THREAD

**Issue by kschwidder** [lodash/lodash#867]
Bower updated from 2.4 release to 3.0 and then my angular apps are not running anymore.
They can not find the _ methods.
What do I miss ?

**Comment by jdalton** [comment]
Careful updating from 2.4 to 3.0. Our 3.0 is a major release and so has back-compat breaking changes. I'm not sure what your compat issue is off the top of my head. Could you provide a bit more info on the error you're seeing? In the meantime you should ensure your version range is `~2.4.1` to avoid jumping to 3.0.

**Comment by jdalton** [comment]
In our 3.0 we've removed our `dist` folder so now scripts are located at our root directory. I suspect this is the issue you're seeing.

**Comment by kschwidder** [comment]
I am using the _.find method and this function is now undefined when calling. A javascript error is raised.

**Comment by jdalton** [comment]
> I am using the _.find method and this function is now undefined when calling. A javascript error is raised.

Correcting the `lodash` dependency version range should resolve your issue.

**Comment by kschwidder** [comment]
It works now After i updated the Lodash bower directory.

Thx

Von meinem iPhone gesendet

**Comment by jdalton** [comment]
Rock! Though you should really keep the version range locked down a bit more. Something like `~2.4.1` would do and save you grief in the future.
