### ISSUE TITLE
Basic question about baseDifference()

### ISSUE THREAD

**Issue by adamboduch** [lodash/lodash#868]
I was digging around `baseDifference()` and this [if statement](https://github.com/lodash/lodash/blob/master/lodash.js#L1785) has me totally stumped. I was wondering if the check for `isCommon` could be moved *outside* the `while`, just as a general curiosity. But there's also a check for `value === value`. What's that all about?

Thanks!

**Comment by jdalton** [comment]
Hiya @adamboduch! Good Q!

> I was digging around `baseDifference()` and this *if statement* has me totally stumped.

That condition in [baseDifference](https://github.com/lodash/lodash/blob/3.0.0-npm/internal/baseDifference.js#L36) is a fast path for the common case of not having a custom `_.indexOf` method and of not trying to match an `NaN` value as `NaN !== NaN`.

>  I was wondering if the check for `isCommon` could be moved *outside* the `while`, just as a general curiosity. But there's also a check for `value === value`. What's that all about?

We've moved what we could outside the loop and stored it in `isCommon`. The `value` check is to ensure the value is reflexive (not `NaN`). If it is `NaN` or a custom `_.indexOf` method we pass it to `_.indexOf` which handles `NaN`.

**Comment by adamboduch** [comment]
Good stuff, thanks for the explanation.
