### ISSUE TITLE
_.remove throws: Object doesn't support property or method 'remove'

### ISSUE THREAD

**Issue by AtomStar** [lodash/lodash#870]
When I try the following I get an "Object doesn't support property or method 'remove'" error:

```
_.remove(specFilterBoxItems, function (item) { return item.specId == specId });
```
Other methods such as _.pluck() work perfect. Has the remove method been removed? It is still listed under https://lodash.com/docs#remove 
For more detail and plunker see my Stackoverflow question: http://stackoverflow.com/questions/28107416/lodash-remove-throws-object-doesnt-support-property-or-method-remove

**Comment by jdalton** [comment]
Looks like the question was answered on stackoverflow.
