### ISSUE TITLE
Getting root object

### ISSUE THREAD

**Issue by cesarandreu** [lodash/lodash#873]
I was looking at lodash's source, and saw that you get root by comparing multiple values.

Is there any reason why you'd avoid using: `var root = Function('return this')();` 
(or a safer variation like: `var root = (function(){}).constructor('return this')();`)?

Both examples work in strict and loose mode. According to MDN, `Function.constructor` has been available since the initial JS version, so I'm assuming it works in older environments (haven't tested yet).

Would this fail to give the correct root object under any condition or in any environment? It seems like the most reliable way to get the root object in a system-agnostic way.

I'd like to do a feature request to expose root, either as a property (`_.root` or `_.ROOT`) or as a utility (`_.root()`  or `_.getRoot()`).

**Comment by jdalton** [comment]
The reason we don't is because of CSP restrictions. Many enviros don't allow the use of the `Function` constructor (like Chrome extensions).

**Comment by cesarandreu** [comment]
Ah, I wasn't aware, thanks. 

I take it that it's a no to exposing root as a property or utility too?

**Comment by jdalton** [comment]
> I take it that it's a no to exposing root as a property or utility too?

It's so environment and scenario specific that I think it's better left to the dev.
