### ISSUE TITLE
wish: document breaking changes in 3.0.0

### ISSUE THREAD

**Issue by markstos** [lodash/lodash#875]
As a semantic version, 3.0.0 implies some sort of breaking change compared to 2.4 to 2.2. 

While a full ChangeLog would be nice, at least documenting compatibility issues from 2.2 to 2.4 and 2.4 to 3.0 would be helpful for those considering upgrading.

Thanks for lodash-- I use it nearly daily!

**Comment by jdalton** [comment]
We're documenting the compat changes in our [changelog](https://github.com/lodash/lodash/wiki/Changelog) and releasing [lodash-migrate](https://github.com/lodash/lodash-migrate) to help give devs a headsup on compat issues in their code.

**Comment by markstos** [comment]
@jdalton, thanks for the feedback. 

I was not aware that the wiki was in in use. Would you accept a patch to the [top level README](https://github.com/lodash/lodash/blob/master/README.md) that links to the docs available on the wiki? Something like this:

```markdown

## Further  Reading

  * Build Differences
  * Changelog
  * Resources
  * Roadmap
```

**Comment by phated** [comment]
:+1: for referencing on the readme

**Comment by jdalton** [comment]
@markstos Sure go for it. Don't forget to sign [the CLA](http://dojofoundation.org/about/claForm).

**Comment by markstos** [comment]
I've now signed the CLA and submitted the pull request linked above.
