### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Adan0s** [lodash/lodash#876]
Hey there,

I just upgrade my require.js-Config to lodash 3.0.0 and since then I'm getting the following error:

> Uncaught RangeError: Maximum call stack size exceeded lodash-3.00.min.js:43 

Any idea?

Thanks,
Sven

**Comment by jdalton** [comment]
No ideas. Keep digging & report back.

**Comment by Adan0s** [comment]
Found something.
I'm currently using following Mixin which previously worked like a champ with 2.41 on a pretty huge object (200kB of json):
```javascript
_.mixin({
findNested: function(obj, key, memo) {
			if (!_.isArray(memo)) {
				memo = [];
			}
			_.forOwn(obj, function(val, i) {
				if (i === key) {
					memo.push(val);
				} else {
					_.findNested(val, key, memo);
				}
			});
			return memo[0];
		}
});
```

Seems like the _.forOwn doesn't like recursing through such a big object anymore. :(

**Comment by jdalton** [comment]
You have to be careful with recursion as the size of the function can affect the amount it can be recursively called. If call stacks are an issue try rewriting your code to avoid recursion like (maybe using a while-loop).
