### ISSUE TITLE
_.forEach does not work as described

### ISSUE THREAD

**Issue by goloroden** [lodash/lodash#877]
Maybe I am missing something, but it seems as if `_.forEach` did not work exactly as described in the documentation and as described in the [source code](https://github.com/lodash/lodash/blob/master/lodash.js#L5692-L5693).

According to them, this

    * _([1, 2, 3]).forEach(function(n) { console.log(n); });
    * // => logs each value from left to right and returns the array

should work. If I run

    var _ = require('lodash');
    _([1, 2, 3]).forEach(function(n) { console.log(n); });

nothing happens, and nothing is printed to the console. If I instead run

    var _ = require('lodash');
    _.forEach([1,2,3], function(n) { console.log(n); });

everything works as expected. Is this a bug, or am I missing something?

PS: I'm running Node.js 0.10.35 for this.

**Comment by jdalton** [comment]
In v3.0 we've introduced defferred chaining. Nothing will happen when chaining unless `.value()` is explicitly or implicitly called.

**Comment by goloroden** [comment]
Nevertheless, the docs is wrong then.

**Comment by jdalton** [comment]
I've already fixed the doc ;)

**Comment by megawac** [comment]
Duplicate of #785. @jdalton I think you should reconsider this one, `each` generally will only be done at the end of the chain. This is also going to continue to be a reoccurant issue for people upgrading

**Comment by jdalton** [comment]
>  I think you should reconsider this one, each generally will only be done at the end of the chain. This is also going to continue to be a reoccurant issue for people upgrading.

Naw deferred is deferred unless implicit or explicit `value()` is called. The `_.each` method returns the provided `collection` so does not warrant an implicit `value()` call.
