### ISSUE TITLE
_([1, 2, 3]).forEach(function(n) { console.log(n); }); is not firing the console.logs

### ISSUE THREAD

**Issue by mattruby** [lodash/lodash#878]
In the docs, the following example is shown:
```js
_([1, 2, 3]).forEach(function(n) { console.log(n); });
```
In lodash 3.0.0 this does not seem to fire the `console.log`.  It will return the lodash wrapper as expected.

**Comment by megawac** [comment]
Duplicate of https://github.com/lodash/lodash/issues/785

**Comment by jdalton** [comment]
Ah doc bug! Will fix on site now.

**Comment by mattruby** [comment]
You may wish to add that to the change logs as well as I can tell you, it's a breaking change :-)

**Comment by jdalton** [comment]
Yap, deferred/lazy chaining is a compat change. On it. Thanks!
