### ISSUE TITLE
lodash pulls source files from npm

### ISSUE THREAD

**Issue by demisx** [lodash/lodash#879]
Hi,
I am trying to upgrade from v2 to v3 from npm. I have this in my `package.json`:

```json
"dependencies": {
  "lodash": "^3.0.0"
}
```

When I run `npm i` I get project source files from npm instead of `lodash.js` and `lodash.min.js`. It works properly when I install it from bower, though. Am I missing something? Thank you.

**Comment by jdalton** [comment]
This is by design. The npm package looks like [this](https://github.com/lodash/lodash/tree/3.0.0-npm).

**Comment by demisx** [comment]
I see. Thank you for your awesome lib and quick response as usual.

**Comment by mzgol** [comment]
I was relying on the built files being available in the npm package to use them from a browser, not just Node. Is there any other npm package that has those files or is this use case now not supported? :(

**Comment by jdalton** [comment]
@mzgol You're in luck. The [lodash](https://github.com/lodash/lodash/blob/npm/index.js) and [lodash-compat](https://github.com/lodash/lodash-compat/blob/npm/index.js) packages do contain the monolithic builds as `index.js` that you can grab and use (it's the main file).

**Comment by jdalton** [comment]
They even come with all the UMD bells and whistles.

**Comment by mzgol** [comment]
\o/ Thanks! This lets me use lodash 3.0 even before I refactor my build system to rely on ES6 modules and build to production only what's really needed.
