### ISSUE TITLE
require('lodash') returns undefined in node 0.8.9

### ISSUE THREAD

**Issue by mjackson** [lodash/lodash#88]
``` bash
$ node -v
v0.8.9
$ npm install -g lodash
lodash@0.8.1
$ node
> var _ = require('lodash');
undefined
> _
undefined
```

The logic for exporting to CommonJS could be simplified a lot. I'm sure there's a reason for the complexity (looks like Ringo is complicating things) but it would be the best IMO if you just used `freeExports._ = lodash` or something similar. :)

**Comment by hickford** [comment]
https://www.npmjs.com/package/n_

**Comment by jdalton** [comment]
Yep, [_n](https://github.com/borisdiakur/n_) is great or you can upgrade to Node v6 which supports assigning to `_`.

![](https://cloud.githubusercontent.com/assets/4303/15183957/31d91d72-1748-11e6-9c4f-7c73196ecdf4.gif)

**Comment by sitaramyadav** [comment]
Does this issue has fixed or we just have the option to downgrade the node?

**Comment by jdalton** [comment]
@sitaramyadav Node 6 is the minimum version Node supports now and this issue is resolved in Node 6.
