### ISSUE TITLE
Upgrade to 3.0 performance down

### ISSUE THREAD

**Issue by sbiaudet** [lodash/lodash#881]
Hi,

Recently I've contributed to the project search-index https://github.com/fergiemcdowall/search-index with some improvement using lodash.

I'm using lodash with version 2.4.1. I decide to upgrade to version 3.0. After this upgrade performances down ?? For the same unit test I've about 850ms with old version and now 1200ms with new version ?? 

 The existing code part was :

```javascript
 return _(tf)
    .flatten(function (item, key) {
      return _.map(item, function (token) {
        return {
          token: token[0],
          KeyID: key,
          ReverseIndex: [token[1], key]
        }
      })
    })
    .groupBy('token')
    .reduce(function (memo, item, key) {
      memo.reducedTF['TF~' + key] = _.pluck(item, 'KeyID');
      memo.reducedTFSortOnTF['RI~' + key] = _.pluck(item, 'ReverseIndex');
      return memo;
    }, {
      reducedTF: {},
      reducedTFSortOnTF: {}
    }); 
```

I need to change a little bit the code due to new version changes. And now I wrote this.

```javascript
 return _(tf)
    .map(function (item, key) {
      return _.map(item, function (token) {
        return {
          token: token[0],
          KeyID: key,
          ReverseIndex: [token[1], key]
        }
      })
    })
    .flatten()
    .groupBy('token')
    .reduce(function (memo, item, key) {
      memo.reducedTF['TF~' + key] = _.pluck(item, 'KeyID');
      memo.reducedTFSortOnTF['RI~' + key] = _.pluck(item, 'ReverseIndex');
      return memo;
    }, {
      reducedTF: {},
      reducedTFSortOnTF: {}
    });
```

Can you explain to me why?

**Comment by jdalton** [comment]
You've got two difference implementations so I don't think it's a stretch for there to be two different performances. Your second example looks to be doing another `map` that isn't in the first one. You should also keep in mind in lodash v2.x `_.flatten` was deep by default and in v3 it's shallow by default. You can use [_.flattenDeep](https://lodash.com/docs#flattenDeep) or pass `true` to [_flatten](https://lodash.com/docs#flatten) as a second param.

**Comment by sbiaudet** [comment]
I've make another implementation because the first doesn't work with lodash 3

**Comment by jdalton** [comment]
> I've make another implementation because the first doesn't work with lodash 3

Right as we've dropped the callback in `_.flatten`. Profile it and see what shows up different between the two.

**Comment by sbiaudet** [comment]
I'm thinking that performance lack is on group by. I should verify.

Sébastien BIAUDET

**Comment by sbiaudet** [comment]
I confirm that groupBy is slower with lodash 3. I've split chain and measuring time between 2.4.1 and 3.
Up to flatten it's ok, it's the same performance.  With groupBy I've a big gap (X2).

return _(tf)
    .map(function (item, key) {
      return _.map(item, function (token) {
        return {
          token: token[0],
          KeyID: key,
          ReverseIndex: [token[1], key]
        }
      })
    })
    .flatten()
    .groupBy('token').value();

**Comment by jdalton** [comment]
You wouldn't happen to be testing in Firefox would you? I see one spot I can tweak for the `property` shorthand case that gives me some gains in Firefox but not much elsewhere.

**Comment by sbiaudet** [comment]
I've testing with nodejs and jasmine. I'm using this library in my backoffice server.

**Comment by sbiaudet** [comment]
You're old code was more performant than new. Why ? I don't know... really. Assign an empty array and push value is better than assign and array with a value ??

Old :
```
 (key in result ? result[key] : result[key] = []).push(value);
```

New :
```
      if (hasOwnProperty.call(result, key)) {
        result[key].push(value);
      } else {
        result[key] = [value];
      }
```

**Comment by d10** [comment]
It’s probably the `hasOwnProperty` check.

**Comment by sbiaudet** [comment]
no excuse me it's my last test. There's no difference with in and hasownproperty performance.

```
(hasOwnProperty.call(result, key) ? result[key] : result[key] = []).push(value);
```

**Comment by jdalton** [comment]
lodash 2.4.1 did not have code like:
```js
 (key in result ? result[key] : result[key] = []).push(value);
```

We had the `hasOwnProperty` check [in place then](https://github.com/lodash/lodash/blob/2.4.1/dist/lodash.js#L3379-L3381) too. Are you sure you weren't looking at Underscore?
