### ISSUE TITLE
Distributed Lodash 

### ISSUE THREAD

**Issue by moshir** [lodash/lodash#885]
Hi,

Not really an issue here.
Am I the only one striked by similarities between apis of lodash and Apache Spark RDD (Resilient Distributed Datasets) ?
What would it take to make lodash distributed and resilient, so that we could provide a 100% js  server side big data solution ?

**Comment by jdalton** [comment]
Hi @moshir. I'm not familiar with Apache Spark enough to make a call on what's needed. However it sounds a bit specialized for lodash.

**Comment by moshir** [comment]
Hi, thanks,
Leaving Spark aside, what about a distributed version ?
Imagine distributing a zillion items array on several  nodes and being able to use lodash on top ?

**Comment by Dashed** [comment]
@moshir https://github.com/mentum/lambdaws :wink:

**Comment by jdalton** [comment]
Phew! @Dashed to the rescue. This is outside the scope of lodash.

**Comment by moshir** [comment]
Of course it is out of scope.
Just musing wit the best in class :)
Sorry for the new issue, lets close it.
