### ISSUE TITLE
A way to limit arguments to a curried function

### ISSUE THREAD

**Issue by gampleman** [lodash/lodash#886]
I have the following code:

~~~javascript
function createFilterWithKey(usageData, group) {
  // some implementation
}

// ...

function(filters, valGroup, keyGroup) {
  var createFilterWithGroup = _.curryRight(createFilterWithKey), // <- this
      createValFilter       = createFilterWithGroup(valGroup),
      createKeyFilter       = createFilterWithGroup(keyGroup),
      isVal                 = function(filter) { return filter.tag.match('='); },
      isKey                 = _.negate(isVal),
      keyFilters            = _(filters).select(isKey).map(createKeyFilter), // <- fails here
      valFilters            = _(filters).select(isVal).map(createValFilter);

   return keyFilters.concat(valFilters.value()).value();
}
~~~

This code doesn't work since `_.map` passes more than just one argument, so `createFilterWithKey` is called `createFilterWithKey(filter, index, group)`. I've tried numerous variations using `rearg`, `ary` and `curry(..., n)` but I think I'll need to revert to just a plain  `function(group) { return function(filter) {   return createFilterWithKey(filter, group);  };  }`.

Point being I think the `_.curry(..., n)` signature should ignore additional arguments.

**Comment by jdalton** [comment]
If you want to limit the argument cap of a function use `_.ary` before passing it to `_.curry`:
```js
function fn(a, b, c) {
  return [a, b, c];
}
var curried = _.curry(_.ary(fn, 2), 2);

curried('a')('b');
// => ["a", "b", undefined]

curried('a','b','c');
// => ["a", "b", undefined]
```

**Comment by gampleman** [comment]
Yes but:

~~~javascript
var curried = _.curryRight(_.ary(fn, 2), 2);

curried('a')('b', 'c')
// =>["b", "c", undefined]
~~~

**Comment by jdalton** [comment]
```js
var curried = _.curryRight(_.ary(_.partial(fn, undefined), 2), 2);
// => [undefined, "b", "c"]
```

Though at that point I think the plain option may be more clear.

**Comment by gampleman** [comment]
Anyway could it be changed that using `_.ary` with `_.curryRight` would have the behaviour of ignoring the later arguments (temporarily speaking, `fn(a)(b,c)`, here `c` would be ignored) rather than the earlier ones?
