### ISSUE TITLE
Add '_.splitArray'

### ISSUE THREAD

**Issue by Whoaa512** [lodash/lodash#888]
Hey love the new `_.chunk`, though I'm finding the need for something slightly different. I'd like to be able to split my array into N new arrays, even if each new array is not completely filled.

Something like, `_.splitArray(array, size)`

```javascript
var letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'];
var grouped = _.splitArray(letters, 3);
// => [ [ 'a', 'b', 'c', 'd' ], [ 'e,', 'f', 'g', 'h' ], [ 'i', 'j', 'k' ] ]
```

Find myself needing it pretty often. And I usually just end up pulling this [SO answer](http://stackoverflow.com/a/8189268) into my utils, but it would be an awesome addition to lodash :bamboo: 

Cheers

**Comment by jdalton** [comment]
I think for now this will be a better fit as a mixin. You can get this functionality with `_.chunk` by doing `_.chunk(a, Math.ceil(letters.length/3))`.

**Comment by intellix** [comment]
Hi, we needed the ability to chunk vertically instead of horizontally and was doing `Math.ceil(letters.length / rows)` but it doesn't quite work the same. Example: 

```js
var a = [1, 2, 3, 4, 5, 6, 7, 8, 9];
var rows = 4;
_.chunk(a, Math.ceil(a.length / rows)); // [1,2,3], [4,5,6], [7,8,9]
```
We needed to chunk to populate 4 rows like: `[1, 2, 3, 4], [4, 5], [6, 7], [8, 9]`

Here is a filter we're using that allows chunking horizontally and vertically. It also supports preserving keys but maybe that's out of scope:

```js
(function() {
    'use strict';

    angular
        .module('app')
        .filter('chunk', chunk);

    function chunk() {
        return function(value, size, horizontal, preserveKeys) {
            var chunks = [];
            var chunkCount = size;
            var chunkIndex;
            
            horizontal = horizontal || true;
            preserveKeys = preserveKeys || false;

            if (horizontal) {
                chunkCount = Math.ceil(value.length / size);
            }

            for (chunkIndex = 0; chunkIndex < chunkCount; chunkIndex++) {
                chunks.push([]);
            }

            chunkIndex = 0;
            value.forEach(function(value, key) {
                if (preserveKeys) {
                    chunks[chunkIndex][key] = value;
                } else {
                    chunks[chunkIndex].push(value);
                }

                if (++chunkIndex === chunkCount) {
                    chunkIndex = 0;
                }
            });

            return chunks;
        }
    }

})();
```
