### ISSUE TITLE
Using push() and splice() on wrapped arrays in 3.0.0

### ISSUE THREAD

**Issue by adamboduch** [lodash/lodash#889]
The only thing that's really tripped me up while upgrading our source to use 3.0.0 are some of the array methods on wrapped values. In particular, things that modify the wrapped value, like `push()` and `splice()`. This isn't a defect or anything, I just figured I should put in somewhere for those running into similar issues since their usage is slightly different than 2.4.1.

```javascript

// Works as expected in 2.4.1...
var coll = _([ 1, 2, 3 ]);
coll.push(4);
coll.value();
// → [1, 2, 3, 4]

// However in 3.0.0...
var coll = _([ 1, 2, 3 ]);
coll.push(4);
coll.value();
// → [1, 2, 3]

// Which is because push() has no value() call, forcing it to run.
// So if it's not part of a longer chain, you need to manually call it...
var coll = _([ 1, 2, 3 ]);
coll.push(4).value();
coll.value();
// → [1, 2, 3, 4]
```

**Comment by jdalton** [comment]
Thanks, I'll add a compat note to the changelog.

**Comment by adamboduch** [comment]
Rock, thank you.

**Comment by jdalton** [comment]
Actually the difference isn't because of deferred chaining. It's because now each action in the chain produces a new wrapper. In v2.4.1 it wouldn't return a new wrapper if the result of the function call was identical to the wrapped value.

**Comment by jdalton** [comment]
Here's the note I'm adding:

 * Ensured each segment of a chain creates a new wrapper & sequence of actions that may be repeatly applied
  ```js
  var wrapped = _([1]);

  // in 2.4.1
  var a = wrapped.push(2),
      b = wrapped.push(3);

  a === b;   // => true
  a.value(); // => [1, 2, 3]
  b.value(); // => [1, 2, 3]
  a.value(); // => [1, 2, 3]
  b.value(); // => [1, 2, 3]

  // in 3.0.0
  var a = wrapped.push(2),
      b = wrapped.push(3);

  a === b;   // => false
  a.value(); // => [1, 2]
  b.value(); // => [1, 2, 3]
  a.value(); // => [1, 2, 3, 2]
  b.value(); // => [1, 2, 3, 2, 3]
  ```
