### ISSUE TITLE
arr.insert(index, item)

### ISSUE THREAD

**Issue by coolaj86** [lodash/lodash#89]
```
_.insert = function (arr, index, item) {
  arr.splice(index, 0, item);
};
```

I know it's hardly worth including, but I forget all the time that splice does insert - and there's a lot of google traffic for "javascript array insert", y'know.

**Comment by JabbyPanda** [comment]
Good use-case for the using `_.mixin` API in our projects

**Comment by continuata** [comment]
could we re-open this?
Array#splice is not a solution, as it mutates the original array instead of returning a new spliced one.
I thought one of the main points of lodash was to ensure functional versions of javascript methods are implemented.

something like this would work ...
```es6
  _.insert (arr, index, insertObject) {
    let before = _.slice(arr, 0, index)
    let after = _.slice(arr, index)
    return _.flatten([before, insertObject, after])
  }
```

Happy to open a PR for this, if it's considered a useful addition

**Comment by albertogasparin** [comment]
+1 :+1: 
It would be nice to provide a *non mutable* helper for adding elements to an array. I'm suggesting:

``` js
_.insert(array, value, [index])
```

With `index` as an optional argument (falls back to `_.concat` if missing)

**Comment by jdalton** [comment]
Thanks @albertogasparin!

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by TurBas** [comment]
+1

**Comment by prose100** [comment]
It would be nice for the `insert` function to accept a number or an array. 
So instead, `_.insert(array, insertion, [index])` where `insertion` is a number or an array.

It would be documented as follows:
insertion (number or Array): The value or values to insert. 

`_.insert([1,2,6,7], [3,4,5], 2)`
//[1,2,3,4,5,6,7]

`_.insert([1,2,4,5], 3, 2)`
//[1,2,3,4,5]

**Comment by bompi88** [comment]
+1

**Comment by freewind** [comment]
I'm searching 'how to insert an element to array with lodash' and reached this issue

**Comment by elranu** [comment]
Hi
sorry but is there a method that while inserts, inserts in the order specified by a selected property?

lest say something like ` _.insert(arr, itemToInsert, ['age'], ['asc']);` ?

**Comment by elranu** [comment]
I made a performance between insert many items in an array and then sort , and insert in a order way.  
https://jsbin.com/lezanab/1/edit?js,console

Is much better to create the array and at the end sort. A method of insertion with a better strategy should be faster.

**Comment by twig** [comment]
Just wondering how many more votes are needed for this to be added

**Comment by jdalton** [comment]
There's no set number. There's strong demand for this for sure.

**Comment by twig** [comment]
Ahh right. I was surprised this wasn't available in lodash because of the obscure way you have to use splice to make this work.

**Comment by rachidbch** [comment]
So, is there any timeline set for adding this helper ?

**Comment by jdalton** [comment]
@rachidbch No timeline. Based on the popularity of this request it'll likely be in v5 at the latest.

**Comment by yvele** [comment]
Just to let you know that I've made a similar feature request with string #2723

**Comment by rafaelss95** [comment]
Any news on this feature request?

**Comment by darkguy2008** [comment]
So was this implemented or not? I need to do this as well.

**Comment by twig** [comment]
@jdalton any idea when we'll ever hit "enough votes" for a popular request? it's one of the few things missing from lodash I constantly look for in the docs and forget it's not there.

source is there, just wondering if there's any case against the insert function

**Comment by ephetic** [comment]
What's the best fp workaround right now?  Slice then splice?

**Comment by darkguy2008** [comment]
@jdalton thanks for deleting my comment. So I take the developers here just don't care about their user's opinions, right? I have to agree with @twig .

**Comment by jdalton** [comment]
Distracting +1 style comments are cleaned up at will. Read the bit [linked to above](https://github.com/lodash/lodash/issues/89#issuecomment-9326295) to see how to indicate interest in a feature.

**Comment by jdalton** [comment]
@twig Votes are an indicator of user interest in a feature. There is no set of votes to reach for adoption of a feature.

**Comment by darkguy2008** [comment]
@jdalton While I appreciate your link, I'm a bit puzzled about your answer. So, a feature request +1'd by around... 135 people is no indicator of interest? how can a request be considered "popular" if there aren't set rules that define it? (not even in the link you told me to see).

A PR for this would be **minimal** anyways and it would save up a lot of google searches due to a feature that a lot of people is searching for, including me and 135+ people watching or +1'ing this issue.

**Comment by jdalton** [comment]
> So, a feature request +1'd by around... 135 people is no indicator of interest?

I didn't write anything to that effect. There is interest in this feature but I reserve the right to choose when and which features to implement.

**Comment by rgbkrk** [comment]
The proper change for this isn't as minimal as you think, `arr.splice(index, 0, item);` is mutative which conflicts with the `lodash/fp` variant. After implementing it (or even before), there's writing all the tests and having to maintain it over time. It's not a bit flip of a feature.

**Comment by twig** [comment]
Thank you @rgbkrk, that's the sort of response I was looking for.

**Comment by dimitropoulos** [comment]
since someone (@ephetic) was asking about a way to accomplish this, [here is](https://github.com/ramda/ramda/blob/v0.24.1/src/insert.js) an example of an similar thing from `ramda/insert`

**Comment by ephetic** [comment]
@dimitropoulos Nice!  But I was actually wondering what people were using as workarounds in Lodash currently, not how it could be implemented as a feature.  Thanks!

**Comment by gravitypersists** [comment]
@ephetic kinda late to the conversation, but I do this:

`const set = (n, ins, arr) => [...arr.slice(0, n), ins, ...arr.slice(n + 1)]`

**Comment by trungtin** [comment]
@gravitypersists no it does not work, for example
```
set(0, 2, [1]) return [2] instead of [2, 1]
```

**Comment by theGABS** [comment]
Still want this features. 
Array slice, splice etc. is very hard to remember for non english dev.

**Comment by shanimal** [comment]
There's a few libraries out there that handle immutable. This one seems popular.
https://doda.github.io/immutable-lodash/docs/

**Comment by daedalus28** [comment]
FYI, this is available in futil-js as `insertAtIndex`

https://smartprocure.github.io/futil-js/#api-array-insertatindex
https://github.com/smartprocure/futil-js#insertatindex

**Comment by taimoorgit** [comment]
Pretty wild that this request was denied. I would have found this very useful.

**Comment by DoloMike** [comment]
Requesting this to be looked at again. With a few hundred positive reactions, in this thread alone, and the great suggestion by @trungtin :
`_.insert = (n, ins, arr) => [...arr.slice(0, n), ins, ...arr.slice(n)];`

I think this is well deserving of a spot in the codebase. Thoughts?

**Comment by joshdavenport** [comment]
Indeed! This along with https://github.com/lodash/lodash/issues/1701 and https://github.com/lodash/lodash/issues/2339 would add some really nice array manipulation tools and are also [3 out of 5 of the top +1'ed method addition requests in the issue tracker here](https://github.com/lodash/lodash/issues?utf8=✓&q=label%3Aenhancement+sort%3Areactions-%2B1-desc+)

**Comment by jdalton** [comment]
Let's bikeshed names and mutation vs. returning a new array. Opening for a PR.

**Comment by DoloMike** [comment]
I'm proposing the following function signature for inserting items into an array at a given index:

`insert(index = 0, item, array = [])` 

Examples:

      _.insert(1, 123, [1, 2, 3])
     // => '[1, 123, 2, 3]'

      _.insert(2, 123, [1, 2, 3])
     // => '[1, 2, 123, 3]'
      
     _.insert(-2, 123, [1, 2, 3])
      // => '[1, 123, 2, 3]'
      
     _.insert(-27, 123, [1, 2, 3])
      // => '[123, 1, 2, 3]'
      
     _.insert(52, 123, [1, 2, 3])
      // => '[1, 2, 3, 123]'

It does not mutate the array which is passed in and instead returns a new array. It's very flexible in that the index can be positive or negative. And if the index is out of bounds the item is pushed to either the very beginning or the very end. Again, crediting @trungtin for this idea. I am a big fan. Thoughts?

**Comment by JabbyPanda** [comment]
hmmm, speaking of handling negative indexes... shall we treat negative value as 0 index or `Math.abs`? 

I am confused by that code sample in particular 

> ```
>_.insert(-2, 123, [1, 2, 3])
>  // => '[1, 123, 2, 3]'
> ```

**Comment by DoloMike** [comment]
I personally like the idea of using negative indexes to denote a reverse index. In the example you point out, imagine that the array is indexed in reverse.

That means the last item starts at index 0, the second to last item is at index -1, etc.

**Comment by daedalus28** [comment]
This would be a great addition! If this is added, we will happily deprecate our version of the method in [`futil`](https://github.com/smartprocure/futil-js) (which is a complementary tool for lodash if you're unfamiliar).

It should be immutable because otherwise, it doesn't add much over `splice`. We named this method `insertAtIndex` with the signature `(index, value, array)`. We support negative indexes as well because `array.splice` supports it natively, and also made it work on strings in addition to arrays. The more natural lodash approach would probably be `(array, index, value)`, with the fp version following the standard `(b, c, a)` rearg (so the fp version would match the futil implementation).

If it's helpful, here is our implementation:

https://github.com/smartprocure/futil-js/blob/master/src/collection.js#L19-L30
```js
let insertAtStringIndex = (index, val, str) =>
  str.slice(0, index) + val + str.slice(index)
let insertAtArrayIndex = (index, val, arr) => {
  let result = _.clone(arr)
  result.splice(index, 0, val)
  return result
}
export let insertAtIndex = _.curry((index, val, collection) =>
  _.isString(collection)
    ? insertAtStringIndex(index, val, collection)
    : insertAtArrayIndex(index, val, collection)
)
```

and the test cases are here:

https://github.com/smartprocure/futil-js/blob/master/test/collections.spec.js#L37-L47
```js
it('insertAtIndex', () => {
  let arr = [1, 2, 3]
  let x = F.insertAtIndex(1, 5, arr)
  expect(x).to.deep.equal([1, 5, 2, 3])
  expect(arr).to.deep.equal([1, 2, 3])

  expect(F.insertAtIndex(1, 'z', 'abc')).to.deep.equal('azbc')

  var result = F.insertAtIndex(0, '<span>', 'pretty please')
  expect(result).to.equal('<span>pretty please')
})
```

**Comment by daedalus28** [comment]
@jdalton why was my previous comment marked as spam? I directly responded to the open questions around bikeshedding the name and explained my rationale on whether it should mutate, and also commented on what the argument signature should be. I included links to a working implementation and the test cases which demonstrate how it could be even more useful by also working on strings. I even described a willingness to deprecate our existing method once this lands. This seems like a very on-topic, constructive comment in which I put a fair amount of effort.

What about that is spam? I've noticed other comments marked as off-topic as well when mentioning that some of the requested lodash methods are readily available in futil. I don't understand - futil is basically an fp version of something like lodash-contrib 🤔

**Comment by dzoba** [comment]
It would be nice if this worked with nesting in objects. Something like:

```
const foo = {
a: {
    b: [1,3,4]
}
}

insert(foo, 'a.b[1]', 2)

// foo = [1,2,3,4]
```

**Comment by anguskeatinge** [comment]
June 2021 - would love this feature ❤️

**Comment by adrian2x** [comment]
Hi everyone, I've ported this in [atomic-fns](https://atomic-fns.dev/functions/Collections.insert.html) because got tired of waiting around for these issues to be resolved.

**Comment by devlikhon** [comment]
I believe for non-mutable one, we have native support now.

See - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSpliced

**Comment by minlare** [comment]
I would like to see something similar so I can use a predicate function to insert something after (or before), like `findIndex` but to avoid another line:

`insertAfter(arr, newItem, { key: 'somevalue' })`

Instead of

```
const index = findIndex(arr, { key: 'somevlaue' });
arr.splice(index, 0, newItem);
```
