### ISSUE TITLE
Chaining `map` and `reverse` returns unmodified array.

### ISSUE THREAD

**Issue by evanrs** [lodash/lodash#890]
When upgrading to 3.0.0 I had trouble with a code block very similar to 
```javascript
_([{a: 1}, {a: 2}, {a: 3}, null])
  .map(function(v) { return v && v.a })
  .compact()
  .reverse()
  .value()
```
resulting in `[1, 2, 3, null]`, where I had expected `[3, 2, 1]`.

Comparing this example with the following you'll see that while the values can change the order and index will remain the same.
```javascript
// returns [1, 2, 3, null], expected [null, 3, 2, 1]
_([1, 2, 3, null]).map(_.identity).reverse().value()

// returns [1, 2, 3, null], expected [3, 2, 1]
_([1, 2, 3, null]).map(_.identity).compact().reverse().value()
```

**Comment by jdalton** [comment]
That's a bug!

**Comment by DavidAnson** [comment]
This sounds very similar to an issue I was about to raise regarding a significant behavioral change with lodash 3.0.0. Below is a complete demonstration of the problem. Please let me know if you'd like a new issue.

```
C:\T\lodash-demo>type demo.js & npm list & node demo.js
"use strict";

var scenarios = [require("lodash-node"), require("lodash")];
var items = [1, 2, 3, 4, 5];

scenarios.forEach(function(dash) {
  var result = dash.chain(items).map(function(item) {
    return item;
  }).reverse().value();

  console.log(dash.VERSION + ": " + result);
});

C:\T\lodash-demo
├── lodash@3.0.0
└── lodash-node@2.4.1

2.4.1: 5,4,3,2,1
3.0.0: 1,2,3,4,5
```

**Comment by carlsverre** [comment]
A similar issue (to the first one) shows up with the rest and filter functions.  Repro that you can add to the test suite:

```
    test('should be safe', 3, function() {
        var out = _([1,2,3]).rest().filter(function(a) {
            strictEqual(typeof a, 'number');
            return false;
        }).value();
    });
```

It is expected that the function is only called twice (on the values 2 and 3) but instead it is called three times with the values (2, 3, undefined).

**Comment by jdalton** [comment]
Two different bugs in one. I've fixed both locally, adding tests :)

**Comment by carlsverre** [comment]
Awesome to hear!  Looking forward to seeing the diff.  :)  Thanks!

**Comment by evanrs** [comment]
@jdalton thank you!

**Comment by dennismonsewicz** [comment]
I have been trying to play around with shortening a piece of code that looks like this:

```       
groups = _.map(groups, function(group) {
    return _.values(group).reverse();
});
```

To look like `groups = _(_.map(groups, _.values)).reverse().map(_.identity).value();`

`groups` looks like `[{'name': 'Foo Bar', 'account_id': 100}, {'name': 'Bar Foo', 'account_id': 100}]`

But the arrays that are returned are untouched. I'm sure I am missing something here

**Comment by jdalton** [comment]
@dennismonsewicz The output of `_(_.map(groups, _.values)).reverse().map(_.identity).value();` looks correct. For support questions try our [gitter chat](https://gitter.im/lodash/lodash).
