### ISSUE TITLE
Error with _.find in 3.0.0?

### ISSUE THREAD

**Issue by pgkehle** [lodash/lodash#892]
Hi.  I pulled 3.0.0 today from npm.  Seems I am getting issues.  

When I use an object to try to find one element of an array with a known title, I get undefined:

    var adminModule = _.find(asyncData.adminModules, {'title': name});

    output:
    2015-01-28T03:21:28.212Z - info: [routes/api.js] controllers[billing] adminModule: undefined
    2015-01-28T03:21:28.213Z - info: [routes/api.js] controllers[calendar] adminModule: undefined
    ....

However, when I use a function, it works:

    var adminModule = _.find(asyncData.adminModules, function (a) {
        return a.title == name;
    });

    output:
    2015-01-28T03:18:10.352Z - info: [routes/api.js] controllers[billing] adminModule: {"_id":"54c806e5cc3eca945e949dce","__v":0, ... ,"title":"billing"}
    2015-01-28T03:18:10.352Z - info: [routes/api.js] controllers[calendar] adminModule: {"_id":"54c806e5cc3eca945e949dd0","__v":0, ... ,"title":"calendar"}
    ....

Any ideas?  This same object structure worked previously.

Thanks!

**Comment by jdalton** [comment]
I looks like `asyncData.adminModules` contains objects with inherited properties. In v2.4.1 we were inconsistent with our property matching when comparing a `sourc`e object with 1 property vs. those with more than 1. In the case of sources with 1 property we did a straight property access without a `hasOwnProperty` check but on sources with 2 or more we checked only own properties of objects as we passed them to our internal `baseIsEqual` helper. In v3 things are now consistently checking own properties of sources and objects regardless of the number of properties on `source`. You can check objects with inherited properties by first converting them to plain objects

```js
_.find(_.map(asyncData.adminModules, _.toPlainObject), {'title': name});
```

Though for your cause of matching a single property a simple callback may be the better option.

**Comment by pgkehle** [comment]
The adminModules is the result of a fetch from MongoDB.  I essentially would want to pull out one from that list based on the title.  I guess I'm not understanding how in v2 this was allowed but no longer is allowed directly, especially when the documentation is pretty clear that this is how it's expected to work.  

    var users = [
      { 'user': 'barney',  'age': 36, 'active': false },
      { 'user': 'fred',    'age': 40, 'active': true },
      { 'user': 'pebbles', 'age': 1,  'active': false }
    ];

    // using the "_.matches" callback shorthand
    _.result(_.find(users, { 'age': 1 }), 'user');
    // → 'pebbles'

Should it really matter that I pulled my array from a database in order for this to work?  Maybe there's an alias y'all could provide that would do that mapping as part of the library?  I doubt I'd be the only one out there who has to now find all of those examples in every project to change it to add that fix, or to change it to a callback. 

Thanks.

**Comment by jdalton** [comment]
> I guess I'm not understanding how in v2 this was allowed but no longer is allowed directly, especially when the documentation is pretty clear that this is how it's expected to work.  

Reiterating what I mentioned above the documented examples do work because they have own properties not inherited. Your 2.4.1 code would not have worked as it did if you passed two properties or more for `source`:

```js
_.find(asyncData.adminModules, {'title': name, '__v': 0 });

>  Maybe there's an alias y'all could provide that would do that mapping as part of the library?

```js
var adminModules = _.map(asyncData.adminModules, _.toPlainObject);
```

> I doubt I'd be the only one out there who has to now find all of those examples in every project to change it to add that fix, or to change it to a callback. 

You should give [lodash-migrate](https://www.npmjs.com/package/lodash-migrate) a try.

**Comment by jdalton** [comment]
With lodash v3.2.0 you can now use the [_.matchesProperty](https://lodash.com/docs#matchesProperty) shorthand:
```js
_.find(asyncData.adminModules, 'title', name);
```

**Comment by pgkehle** [comment]
Thanks for the update. The _.matchesProperty shorthand will be helpful.
