### ISSUE TITLE
Documentation for v2.4.1 -- Gone or just hidden? Please re-provide it.

### ISSUE THREAD

**Issue by NicBright** [lodash/lodash#893]
Hi there,

Congrats on the new version! I really like what you've done to the library :-)
But I'm wondering, whether there is a way to get back the documentation for the previous version (2.4.1)? I could not find it, maybe I'm blind or just missing something?

Regards,
Nicolas

**Comment by jdalton** [comment]
Hi Nicolas! For future reference each release in our [changelog](https://github.com/lodash/lodash/wiki/Changelog) links to docs from the tagged release. The docs for 2.4.1 can be found [here](https://github.com/lodash/lodash/blob/2.4.1/doc/README.md). It also looks like [devdocs](http://devdocs.io/lodash/) is still at 2.4.1 too.

**Comment by NicBright** [comment]
Thank you very much for the quick response and clarificaiton :-)
