### ISSUE TITLE
_.merge() ends up to DOMException when "sources" contains Element object(s)

### ISSUE THREAD

**Issue by Jesus-21** [lodash/lodash#895]
Hi,
I was trying to update to version 3.0.0 but I had unfortunate experience due to this upgrade.
If I try to merge objects that contain Element, I end up with the following error:
```
DOMException: Failed to set the 'outerHTML' property on 'Element': This element has no parent node.
```

As far as I understand, it happens at the very last step of baseMerge, object[key] = result;

For a better understanding, here is a simple example:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
</head>
<body>
<div id="foo">FOO</div>
<div id="bar">BAR</div>
<script src="lodash-3.0.0.js"></script>
<!-- <script src="lodash-2.4.1.js"></script> -->
<script>
  var a = {el: document.getElementById("foo")};
  var b = {el: document.getElementById("bar")};

  var c;
  try {
    c = _.merge({el: null}, b); // FAIL
    console.log(c);
  } catch (err) {
    console.error(err);
  }

  try {
    c = _.merge(a, b); // FAIL
    console.log(c);
  } catch (err) {
    console.error(err);
  }

  try {
    c = _.merge(a, {el: null}); // Object {el: null}
    console.log(c);
  } catch (err) {
    console.error(err);
  }
</script>
</body>
</html>
```

So it works, unless the *sources* (var b) contains an Element.
It is IMPORTANT to note that _.merge() of such objects worked on 2.4.1 version of lodash.

Is it a misuse of the merge function on my hand or is this a regression?

Thanks.

**Comment by jdalton** [comment]
That's a regression! Thanks for digging.

**Comment by jdalton** [comment]
I'll post tests tonight.
