### ISSUE TITLE
_.chunk returns empty array for sizes larger than array 

### ISSUE THREAD

**Issue by nullrocket** [lodash/lodash#896]
I would have expected the following to just return the largest chunk it could for myArray if passed a chunk size greater than myArray.length instead of an empty array.
```
var myArray = [1,2,3,4];
var chunkedArray = _.chunk(myArray,100);
// => []
```
This works as I expect
```
var myArray = [1,2,3,4];
var chunkedArray = _.chunk(myArray,Math.min(100,myArray.length));
// => [[1,2,3,4]]

**Comment by jdalton** [comment]
Hmm. I can't repo this. Here is what I get:
```js
var myArray = [1,2,3,4];
_.chunk(myArray,100);
// => [[1, 2, 3, 4]]
```

**Comment by nullrocket** [comment]
@jdalton Looks like the issue is lodash-contrib v241.4.13 it includes a chunk function that was overwriting the 3.0 lodash chunk.

**Comment by jdalton** [comment]
\cc @refack
