### ISSUE TITLE
Consider renaming value() to run() or evaluate() or execute() for clarity

### ISSUE THREAD

**Issue by DavidAnson** [lodash/lodash#898]
Before version 3.0.0, the name `value()` made sense for the name of the function to extract the "one, true, unchanging value" from a chained sequence wrapper.

However, with the introduction of lazy evaluation in 3.0.0 the chained sequence wrapper no longer represents *one* value and instead represents a "sequence of actions that may be repeatedly applied" (quoting the changelog). The example in the changelog of using `value()` to repeatedly invoke `push()` on an array is an excellent example of why the term "value" is outdated: a chained sequence wrapper may correspond to an infinite number of values.

Most people will expect code that calls `value()` to return the same value every time - whereas code that calls `run()`, `evaluate()` or `execute()` is obviously doing work each time and may return different results. By renaming `value()` to something that more closely corresponds to what it does - "executes the chained sequence" (quoting the documentation) - potential confusion might be avoided.

**Comment by jdalton** [comment]
I'm open to alias suggestions. So far the list is `run`, `evaluate`, `execute`. If we go the JS namey route it could be `.exec` like `RegExp#exec`.

**Comment by mathiasbynens** [comment]
`.get()` (cfr. jQuery)

**Comment by jdalton** [comment]
@mathiasbynens do you know if they also have an api for replacing the root value to apply the sequence to?

**Comment by mathiasbynens** [comment]
Not that I know of (but @cowboy would know for sure).

**Comment by cowboy** [comment]
I actually have no idea what jQuery does, and I'm a bit late to the conversation, but if your behavior is iterator-like, how about `.next()` like [python](http://anandology.com/python-practice-book/iterators.html#the-iteraton-protocol) and [ruby](http://ruby-doc.org/core-1.9.3/Enumerator.html#method-i-next) do it?

**Comment by jdalton** [comment]
I'll add it to our [roadmap](https://github.com/lodash/lodash/wiki/Roadmap) as API for replacing the root value in the sequence and an alias for `value` are things we want to do. We can bikeshed until then.
