### ISSUE TITLE
_.findWhere not working with complex source

### ISSUE THREAD

**Issue by sgoo** [lodash/lodash#899]
In 3.0.0 `_.findWhere` fails when `source` contains a complex object.

This code won't find the object in 3.0.0 but does find it when executed with 2.4.1
```
function TestObject() {}

testObject = new TestObject();

listItem = {test: testObject, otherProp: false};

var testList = [listItem];
var foundObject = _.findWhere(testList, {test: testObject});
```
It seems to be caused by the clone that is done in `baseMatches`, it looks like in 2.4.1 the properties were checked for `===` equality and if that passed no deep equals was needed.

Working Example here: http://jsbin.com/guqawa/2/edit?html,js,output

**Comment by jdalton** [comment]
This is because of a fix `_.matches`. So it only matches own properties of objects. Related to #892.
To handle this you can use `_.toPlainObject`:
```js
testList = _.map(testList, _.toPlainObject);
```

**Comment by jdalton** [comment]
With lodash v3.2.0 you can now use the [_.matchesProperty](https://lodash.com/docs#matchesProperty) shorthand:
```js
_.find(testList, 'test', testObject);
```
