### ISSUE TITLE
Minified lodash is invalid javascript

### ISSUE THREAD

**Issue by pyrokinetiq** [lodash/lodash#900]
Including lodash in my project, I get:
`Uncaught SyntaxError: Unexpected token ILLEGAL`

Generated at `lodash.min.js:2055`

Seems the minified version changes all the quotes to double quotes, resulting in some triple quotes:

```
'"': """,
```
If changed to
```
'"': '"',
```
or
```
'"': "\"",
```
allows it to work.

**Comment by jdalton** [comment]
Hi @pyrokinetiq! I don't see this in either the modern or compat minified builds. Our automated unit tests also test minified builds and we've not seen any failures.

**Comment by rgriffith** [comment]
I'm actually running into this error as well when compiling lodash with my RequireJS project using r.js and `uglify2` as the optimization method. Using `uglify`; however, does not produce the error.

Additionally, I confirmed that 2.4.0 does not produce an error when compiling with `uglify2`, but 3.x does produce the error. I tried the minified, full, and AMD versions of 3.x and none seemed to work for me.

Any help would be greatly appreciated. Please let me know if you need any additional information from my end.

**Comment by jdalton** [comment]
We test with uglify-js v2.4.16. Can you try it with that.

**Comment by rgriffith** [comment]
Thank you for the quick reply. Just tried upgrading from v2.4.8 to v2.4.16 and I'm still running into the error.

**Comment by jdalton** [comment]
Here are[ the uglify options](https://github.com/lodash/lodash-cli/blob/3.1.0/lib/minify.js#L437-L455) we're using. See if you get it working with those.

Since I cannot repro on our builds you should file a bug against uglify.

**Comment by rgriffith** [comment]
Possible breakthrough, I set the `output.ascii_only` option to `true` and I am not seeing the error. Going to see if perhaps just that option is all I need. 

Any thoughts on whether this might have a negative impact on the rest of the compiled code?

**Comment by jdalton** [comment]
> Any thoughts on whether this might have a negative impact on the rest of the compiled code?

We minify with `ascii_only` as `true` too so should be fine.

**Comment by rgriffith** [comment]
I figured as much, but wasn't entirely sure where `this.isTemplate` was coming from. 

Just wondering in general if it would have an affect on the other libraries we're compiling together. In any event, it looks like that was the only option I needed so I think we're good to go. 

Thank you for showing me the light!

**Comment by jdalton** [comment]
> I figured as much, but wasn't entirely sure where this.isTemplate was coming from.

The `!this.isTemplate` is if lodash-cli compiling someone's template. So if it's compiling a template it won't escape Unicode characters in the template's strings.

**Comment by niemyjski** [comment]
I'm seeing this also with https://github.com/gruntjs/grunt-contrib-uglify

**Comment by jdalton** [comment]
@niemyjski Using [ASCIIOnly](https://github.com/gruntjs/grunt-contrib-uglify#asciionly) should solve your issue. 

There is an uglify option, `quote_style`, to control its handling of quotes. It defaults to `0` which means changing quotes to double quotes, though there is a `3` option to leave quotes alone. Let me know if using `3` solves the issue. This seems like a bug in Uglify though as it should know better.

**Comment by jdalton** [comment]
Commented on the Uglify issue https://github.com/mishoo/UglifyJS2/issues/495#issuecomment-74587590.

**Comment by niemyjski** [comment]
Setting  ASCIIOnly to true did not resolve the issue for me.

**Comment by jdalton** [comment]
Try the quote style.

**Comment by niemyjski** [comment]
Did and it didn't work :( https://github.com/exceptionless/Exceptionless.UI/blob/master/src/Gruntfile.js#L246-L260

**Comment by niemyjski** [comment]
I need this up and running so I'm pulling from cdn for now :(

**Comment by jdalton** [comment]
Can you try manually using [uglify-js](https://www.npmjs.com/package/uglify-js) (without grunt) with the `quote_style` setting to see if it's a something to suggest until the issue is addressed.

**Comment by niemyjski** [comment]
What would I need to run from the command line (sorry, time is a bit limited)? The weird thing is if I run the grunt task locally it works but from the build server to deployment it breaks...

**Comment by jdalton** [comment]
So since you're not familiar with the command line, you may try adjusting your `quote_style` option in your Grunt file. It's a `beautify` command so should be under:
```js
options: {
    beautify: {
        quote_style: 3
    }
}
```

**Comment by niemyjski** [comment]
I got this error:

Running "uglify:main" (uglify) task
{ msg: '`quote_style` is not a supported option',
  defs: 
   { indent_start: 0,
     indent_level: 4,
     quote_keys: false,
     space_colon: true,
     ascii_only: false,
     unescape_regexps: false,
     inline_script: false,
     width: 80,
     max_line_len: 32000,
     beautify: false,
     source_map: null,
     bracketize: false,
     semicolons: true,
     comments: false,
     preserve_line: false,
     screw_ie8: false,
     preamble: null } }
>> Uglifying source dist/app.js failed.

**Comment by jdalton** [comment]
Ah the `quote_style` option appears to be available in their master (edge) but not a published package yet.

**Comment by jdalton** [comment]
You can use their edge by making your package dep:
```json
"uglify-js": "git://github.com/mishoo/UglifyJS2.git#ae07714927f44790e40628cde4fa57bc2c4cb076"
```

**Comment by niemyjski** [comment]
I'll try and visit this later this week when things calm down a bit. I'll let you know how that works out. Thanks for your help.
