### ISSUE TITLE
bindKey should accept placeholder for object param

### ISSUE THREAD

**Issue by kaleb** [lodash/lodash#901]
It would be nice if `_.bindKey` could use a placeholder for the first parameter like this:

    var fruit = ['cherry', 'banana', 'apple', 'pear', 'strawberry', 'grape'];
    var value = _(fruit).sort(_.bindKey(_, 'localeCompare'));

Instead of doing this:

    var fruit = ['cherry', 'banana', 'apple', 'pear', 'strawberry', 'grape'];
    var value = _(fruit).sort(function(a, b) {
        return a.localeCompare(b);
    });

Perhaps there is a better way to do this.

I could always use `_.bind(Function.prototype.call, ''.localeCompare)` as my compare function, but figured there was a more succinct lodash way of doing this.

**Comment by jdalton** [comment]
I think the `_.bind(Function.prototype.call, ''.localeCompare)` approach is the way to go here. You can reduce it to
```js
_.bind(_.call, ''.localeCompare)
```

**Comment by kaleb** [comment]
I should have read the docs better. I never noticed _.call. Thanks!

**Comment by jdalton** [comment]
It's not documented it's just a side effect of `_` being a function ;)

**Comment by kaleb** [comment]
I cam back here once that realization hit me! :laughing"

**Comment by johnrix** [comment]
Trying to figure out how I could use _.orderBy to sort an array of objects by a couple of properties while using String.prototype.localeCompare. Found this issue in my Googling and looks like the suggestion above could be adapted, but I'm struggling to figure it out. Any suggestions appreciated!
