### ISSUE TITLE
How to approach callbacks in Angular expressions?

### ISSUE THREAD

**Issue by iskuhar** [lodash/lodash#902]
Hello,
First of all, big thanks for Lodash, it's simply amazing!

It's more of a question than issue.
AngularJS can parse expressions in the context of scope.
I have a form with dependencies between fields.
Lodash is available on dependencies scope.

Single dependency can look like this:
```javascript
{
"value": "field1.value + field2.value"
}
// field3.value = field1.value + field2.value
```
It works well. 
But there are also sections (parents for fields), which are accessible by id the same way. 
Sections can be repeatable, so then section id = array of sections.

And sometimes I need to handle crazy dependencies like:
"give me the sum of every repeatable section1's field2.value, including only sections where field1.value == 1";

First idea that came to my mind was to use _.map() or any other looping method.
But it's impossible to create anonymous functions in the expression (bye bye callbacks).
Somehow I managed to handle this before and it looked just ugly and complicated as hell (around 7 nested lodash methods used for such simple task).

Today, I had to tackle even more complicated dependency, so I had to find a better way.
I decided to use Angular's $parse service and came up with this mixin (which works, btw): 

```javascript
_.mixin({
    expCb: expCb // expression callback?
});

function expCb(func, collection, expression, data) {
    var scope = $rootScope.$new(); // create new scope that inherits from $rootScope
    scope._ = _; // add lodash to the scope
    _.assign(scope, data); // add additional data to the scope 

    return func(collection, function(value) {
        scope.value = value; // current item is accessible as "value" in expression
       
        return $parse(expression)(scope); // parse expression in the scope context
    });
}
```

Example usage:
```javascript
_.expCb(_.map, [1, 2, 3], 'value * otherValue', {otherValue: 2});
// -> [2, 4, 6]
```

How would you handle that "Lodash way" without depending on Angular?
Is it possible to run code in the context of scope without Angular?

Cheers,
Igor

**Comment by jdalton** [comment]
Hi Igor! My Angular-fu isn't strong so I'm not the best person to answer your question.
The `$parse` function looks a lot like `_.template` in that you can do
```js
_.template('<%= value * otherValue %>')(_.assign({}, scope, data));
```

**Comment by iskuhar** [comment]
For a moment I thought that you solved my angular dependency problem.
I also noticed that I don't need to pass dependencies scope, because I have data object for it.

Anyway, I still have one more issue with new solution:
```javascript
function expCb(func, collection, expression, data) {
        var scope = _.assign({}, data);
       template = _.template('{{' + expression + '}}');
        return func(collection, function(value) {
            scope.value = value;
            return _.template('{{' + expression + '}}', scope);
            // return template(scope);
        });
    }
```

**Comment by jdalton** [comment]
> Any thoughts? :)

There's not a lodash way to tackle that without implementing `$parse`.

**Comment by iskuhar** [comment]
Ok, thank you.
