### ISSUE TITLE
Lodash 3 doesn't sort negative numbers properly

### ISSUE THREAD

**Issue by cazgp** [lodash/lodash#903]
This used to work in the previous version:

`L([{priority: -1, createdAt: 1}, {priority:-2, createdAt: 2}]).sortBy(['priority']).first() # {priority: -2}`

but now it reports `{priority: -1}`.

The docs say it's supposed to sort in ascending order. `-2 < -1`...

I need negative numbers to get around the fact that you can't sort by desc!

**Comment by cazgp** [comment]
Never mind... it looks like it's an API breaking change whereby `sortBy` is now `sortByAll`.

**Comment by jdalton** [comment]
Yap!
