### ISSUE TITLE
rearg of includes - expected behaviour?

### ISSUE THREAD

**Issue by jamiegudgeon** [lodash/lodash#904]
(_.rearg(_.includes,1,0))("102573")

I expect this to produce a function essentially equivilant* to f(a){return a.indexOf("102573") !== -1}

instead it returns false. 

As work around, I am currently doing:

_.partial((_.rearg(_.includes,1,0)), "102573")

But when it comes to the first way I tried to write it - am I doing something hideously wrong?

*Appreciate _.includes does more than that...

**Comment by jdalton** [comment]
The `_.rearg` function alone doesn't curry the function for you. You need to combine it with [_.curry](https://lodash.com/docs#curry):

```js
var includes = _.curry(_.rearg(_.includes,1,0), 2);
includes("b")("abc");
// => true
```

If you're using the produced function as a callback to say `_.map` then you may also want to cap the number of arguments it's allowed to receive using [_.ary](https://lodash.com/docs#ary).
```js
var includes = _(_.includes).rearg(1, 0).ary(2).curry(2).value();
includes("b")("abc");
// => true
```

If you want lodash functions with their args flipped and auto-curried you can use [lodash-fp](https://www.npmjs.com/package/lodash-fp).
