### ISSUE TITLE
Upgrade from 2.4.1 to 3.0.1 _.where & _.reject results changed when using undefined

### ISSUE THREAD

**Issue by djtregear** [lodash/lodash#909]
Firstly, thanks very much for writing and maintaining this great library.

I appreciate that this is a major change, and that in the changelog it states that:
```
Ensured _.where handles source objects with undefined property values
```
But, if possible I'd like a little help with the following issue, so that I can understand whether I'm doing something wrong or whether this is a bug?

I have some code running in Node (v0.10.33) with the following array:
```javascript
var array = [ 
  {
    id: 'E6KvN1aXQnFRvAlNkAjv',
    _id: 54ccf74869b6194e54233f0c,
    ps: '2015-02-01T06:35:15.796Z'
  },
  {
    id: '96aO8jEp59FrmAjd4AMO',
    _id: 54ccf8df69b6194e54233f12
  }
];
```
This array is split into two separate arrays using the following lodash methods:
```javascript
var pauseOff = _.where(array, { 'ps': undefined });
var pauseOn = _.reject(array, { 'ps': undefined });
```
In lodash@2.4.1 the result was:
```javascript
pauseOff = 
[
  {
    id: '96aO8jEp59FrmAjd4AMO',
    _id: 54ccf8df69b6194e54233f12
  }
];

pauseOn =
[
  {
    id: 'E6KvN1aXQnFRvAlNkAjv',
    _id: 54ccf74869b6194e54233f0c,
    ps: '2015-02-01T06:35:15.796Z' 
  }
];
```
In lodash@3.0.1 the result is:
```javascript
pauseOff = [];

pauseOn =
[
  {
    id: 'E6KvN1aXQnFRvAlNkAjv',
    _id: 54ccf74869b6194e54233f0c,
    ps: '2015-02-01T06:35:15.796Z' 
  },
  {
    id: '96aO8jEp59FrmAjd4AMO',
    _id: 54ccf8df69b6194e54233f12
  }
];
```
As I say, is this something I'm doing wrong?

Thanks for your time.

David

**Comment by jdalton** [comment]
This is because of a fix to `_.matches` so it only matches own properties of objects. 
You can use
```js
var pauseOff = _.reject(array, 'ps');
var pauseOn = _.filter(array, 'ps');
```

Related to #892 & #899.

**Comment by jdalton** [comment]
With lodash v3.2.0 you can now use [_.matchesProperty](https://lodash.com/docs#matchesProperty) to match `undefined` properties.
```js
var pauseOff = _.where(array, _.matchesProperty('ps', undefined));
var pauseOn = _.reject(array, _.matchesProperty('ps', undefined));
```
