### ISSUE TITLE
support _.uniq to lazy chaining

### ISSUE THREAD

**Issue by qsona** [lodash/lodash#912]
Hi, congratulations for the release of lodash v3! I appreciate for your work very much.

I want the support of `_.uniq` for lazy chaining, but it seems to be not in your roadmap. Is it possible to implement it?
```js
var execCount = 0;
var ary = [0,1,2,3,4,5,6,7,8,9];
_.chain(ary).uniq(function(val){execCount++; return val;}).slice(0,2).value();
console.log(execCount); // 10, so it’s not lazily evaluated
```

p.s. We have used lodash 3.0.0-pre since about 4 months ago on our server-side project with Node.js, and we get along well with it. All bugs that I found are fixed at the edge so it works perfectly now.

**Comment by jdalton** [comment]
At the moment we aren't planning it. That said if you have an implementation in mind I wouldn't mind looking at it.

**Comment by qsona** [comment]
Thanks. I'm planning to send PR.

**Comment by qsona** [comment]
@jdalton I implemented it roughly. Would you please check it?
https://github.com/qsona/lodash/commit/b28e2d9ede6df3a9ac53a63e195f64b0fda154b3
It worked as far as I tested. If you are positive to take it and #944 is solved, I'll clean up the codes and add some test codes.

**Comment by jdalton** [comment]
Thanks, I'll try to review it today.
