### ISSUE TITLE
Underscore compatibility

### ISSUE THREAD

**Issue by gsantome** [lodash/lodash#914]
Hello, I'm trying to build the new version of lodash 3.0.1 with Underscore compatibility and I noticed the underscore command is not available any more... so how I could use lodash instead of Underscore?

```
Gonzalos-MacBook-Pro:Downloads gonzalo$ lodash underscore exports="amd,commonjs,global,node" -o lodash/lodash.underscore.js

Invalid argument passed: underscore
For more information type: lodash --help
Gonzalos-MacBook-Pro:Downloads gonzalo$
```

Thanks

**Comment by jdalton** [comment]
Hi @gsantome! See the [release notes](https://github.com/lodash/lodash/releases/tag/3.0.0):

> ### Breaking changes
>
lodash v3 is a major bump & we’ve introduced several back-compat breaking changes. One such change is that we’re no longer supporting an Underscore/Backbone build. Over the last year we’ve seen Underscore align more & more with lodash’s API so the need for a separate Underscore build has diminished. If you still need compatibility around some of the edges we recommend leveraging modules in lodash v3  to supplement your Underscore use.
>
Be sure to check out the [changelog](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings) for a full rundown of changes & give  [lo-dash-migrate](https://www.npmjs.com/package/lodash-migrate) a spin to help migrate older lodash code to the latest release.
