### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by nikku** [lodash/lodash#915]
It is not save to rely on `global` being available in browserified bundles (i.e. users may choose to [disable insertion of global variables](https://github.com/substack/node-browserify#var-b--browserifyfiles-or-opts) to keep the bundle minimal.

In case browserify (or webpack) did not expose a `global` variable [support.js](https://github.com/lodash/lodash-node/blob/master/modern/support.js#L10) throws an error saying

```
Uncaught ReferenceError: global is not defined
```

I am not sure what the right approach would be to solve this issue. I would probably check for `window` as a global variable because that should (_?_) always be available in DOM environments.

**Comment by nikku** [comment]
`global` is the conventional root in commonJS thought. It may be safe to assume users do not exclude it unless they know what they are doing.

**Comment by jdalton** [comment]
> `global` is the conventional root in commonJS thought. It may be safe to assume users do not exclude it unless they know what they are doing.

Right and the [lodash-node](https://github.com/lodash/lodash-node) bundle is a build of lodash exported as Node.js/io.js modules.

**Comment by nikku** [comment]
Is there any npm compatible build of of lodash that is compatible with the browser + browserify then?

**Comment by jdalton** [comment]
There's [lodash](https://www.npmjs.com/package/lodash) and [lodash-compat](https://www.npmjs.com/package/lodash-compat) though they only have UMD in the monolithic `index.js` files and not the other modules included. Browserify has `opts.detectGlobals` as `true` by default so things should work. Others have used Browserify with lodash without problems so I think this is a case of use the right Browserify options for the job.
