### ISSUE TITLE
_.curry doc problem

### ISSUE THREAD

**Issue by octref** [lodash/lodash#916]
https://lodash.com/docs#curry
Although you have the optional argument `arity` under "Arguments" section, you didn't have it in function signature.
![2015-02-02-204206_391x370_scrot](https://cloud.githubusercontent.com/assets/4033249/6012893/cf1a5ee2-ab1b-11e4-8ce5-fceea5d5c721.png)

**Comment by jdalton** [comment]
Break this issue into two issues please. Keep this one as the doc one. Open a new one for the other.

**Comment by octref** [comment]
@jdalton 
Done. TY for such a prompt response!

**Comment by jdalton** [comment]
This looks like a bug in our doc parser. I'll fix it and update the site docs tonight.

**Comment by jdalton** [comment]
Fixed on site by way of [docdown commit/9239e5f6](https://github.com/jdalton/docdown/commit/9239e5f64f5cd2abe44142e47c660d5811158017).
