### ISSUE TITLE
Learn which values of an array are non-unique?

### ISSUE THREAD

**Issue by MeoMix** [lodash/lodash#918]
Hey,

I have an array that is: [1, 1, 2, 3, 6, 7, 7, 9] and I would like to transform this into [1, 7]

I was a bit surprised that there doesn't seem to be a clear path to achieving this. Am I missing something really obvious? _.uniq is close, but doesn't tell me which ones it removed. I'd think I should be able to diff _.uniq and original, but that'll remove all of the elements...

Right now I'm rocking something ugly:

    var nonUnique = _.chain([1, 1, 2, 3, 6, 7, 7, 9])
          .groupBy(function (val) { return val; })
          .filter(function (arr) { return arr.length > 1; })
          .map(function (arr) { return arr[0]; })
          .value();

or maybe

    var foo = [1, 1, 2, 3, 6, 7, 7, 9];
    var nonUnique = _.transform(_.groupBy(foo), function(data, value, key) {
        if (value.length > 1) {
            data.push(parseInt(key));
        }
    }, []);

**Comment by jdalton** [comment]
Hi @MeoMix. You can do:
```js
_.transform(_.countBy([1, 1, 2, 3, 6, 7, 7, 9]), function(result, count, value) {
  if (count > 1) result.push(value);
}, []);
```
