### ISSUE TITLE
Chaining with modularized functions

### ISSUE THREAD

**Issue by danielnaab** [lodash/lodash#920]
I see there is no chain function as a part of the modularized [builds](https://www.npmjs.com/browse/keyword/lodash-modularized), which makes clear sense considering the method calling syntax used with `_.chain`.

However, is there a way chaining could be handled (to benefit from lazy evaluation), such as via a function that takes a collection and an array of functions to chain? Does this exist or would it be something worth adding?

**Comment by jdalton** [comment]
There's no practical way to do that. If you want chaining and lazy eval the monolithic build is for you. You could create a custom build via [lodash-cli](https://www.npmjs.com/package/lodash-cli) that has just the chaining methods:
```js
lodash modern category=chain -o ./lodash.chain.js
```

You could expand it to chaining plus other methods too
```js
lodash modern category=chain,array -o ./lodash.chain.js
```
