### ISSUE TITLE
Each doesn't execute callbacks when wrapped

### ISSUE THREAD

**Issue by MikaAK** [lodash/lodash#921]
I recently upgraded to v3.1.0 and i noticed that the each method has broken when using it via a lodash wrapper. 

I also tested these in the console on the lodash website. Perhaps there's a change I'm unaware of but to break the functionality of each seems weird! 

##### Not Working
```javascript
_([1,2,4,5,6,9]).each(function(c) { 
  console.log('hi')
})
```
#### Working
```javascript
_.each([1,2,4,5,6,9], function(c) { 
  console.log('hi')
})
```

**Comment by jdalton** [comment]
Please read the [changelog](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings).

Chaining is now deferred until an implicit or explicit `value()` is requested. The `_.each` method returns the provided `collection` so does not warrant an implicit `value()` call.

Related to #785, #877, #878.
