### ISSUE TITLE
_.chunk jsdoc typo

### ISSUE THREAD

**Issue by xuyang2** [lodash/lodash#923]
@param {numer} [size=1] The length of each chunk.

numer shoud be number.

**Comment by jdalton** [comment]
Thanks, fixed on site.

**Comment by xuyang2** [comment]
There are some other jsdoc issues. eg

     * @param {Object} source The object to inspect.

shoud be

     * @param {Object} object The object to inspect.

I think you should consider using some smarter IDE, like IntelliJ IDEA.

**Comment by jdalton** [comment]
LOL it's just me, but thanks for helping :wink:
