### ISSUE TITLE
Merge without overwritting

### ISSUE THREAD

**Issue by khanh-nguyen** [lodash/lodash#924]
I'm trying to merge an array of objects, but I want to throw error if at least 2 objects having the same key but different values.
```js
let mergeNoOverwrite = _.partialRight(_.merge, function(objectValue, sourceValue, key) {
        if (objectValue && objectValue !== sourceValue) {
            let err = new Error('Values conflict.');
            err.name = key;   // it's always `undefined`
            throw err;
        }
        return sourceValue;
    });

    mergeNoOverwrite.apply(null, objArr); 
```

Is there anyway I can get the key of those objects with conflict values? 
Thanks,

**Comment by jdalton** [comment]
The customizer callback accepts `(objectValue, sourceValue, key, object, source)` so you should be able to work something up with that (I hope).

**Comment by khanh-nguyen** [comment]
@jdalton That's right, but I got `key, object, source` all `undefined`. I've seen the code [here](https://github.com/lodash/lodash/blob/master/lodash.js#L2321) but I got `key` as `undefined`.

**Comment by jdalton** [comment]
If the values are `undefined` then it hasn't gotten to the point of iterating the objects, so the initial object compares.

**Comment by khanh-nguyen** [comment]
Sorry for wasting resources. It turns out I was using version 2.4.1 which does not provide `key` in `customizer`

**Comment by jdalton** [comment]
Ah, that's ok. Glad you found the issue.
