### ISSUE TITLE
How to understand composition of functions with multiple arguments?

### ISSUE THREAD

**Issue by ysmood** [lodash/lodash#925]
Such as:
```javascript
var foo = function (a, b) { return a + b; };
var bar = function (a, b) { return a * b; };

var fn = _.flow([foo, bar]);
```
How to understand the `fn`?

**Comment by jdalton** [comment]
It's `fn = _.flow(foo, bar); fn(a, b, c, d);` is like `bar(foo(a, b, c, d))`.

**Comment by matths** [comment]
To reverse your answer into a question, how would one compose a function, where arguments are spread across the functions?

```
var fn = _.howto?(foo, bar);
fn(a, b, c);
```

which shall be like
```
bar(b, foo(a, c))
```

**Comment by jdalton** [comment]
@matths Moving to [gitter](https://gitter.im/lodash/lodash?at=56a905838fbaf4220af9acd3).
