### ISSUE TITLE
_.find() in version 3.0.1 is not compatible with version 2.4.0

### ISSUE THREAD

**Issue by puncha** [lodash/lodash#927]
For the call of this style:_.find(tasks, {name: 'something'}), the 2.4.0 will not check if the property 'name' is task's own property but version 3.0.1 will. Is this an expected change? If there a way to make it behaves as version 2.4.0?

**Comment by jdalton** [comment]
The change is covered in the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v300).
You can use convert objects to plain objects using [_.toPlainObject](https://lodash.com/docs#toPlainObject).
