### ISSUE TITLE
FEATURE REQUEST: _.setTimeout and _.setInterval

### ISSUE THREAD

**Issue by jhiver** [lodash/lodash#928]
When writing coffeescript, `setTimeout()` and `setInterval()` look terrible, i.e.
```js
setTimeout (argument) ->
  doStuff(argument)
, 1000, "foo"
```
It would be much nicer to write:

  `_.timeout 1000, "foo", (argument) -> doStuff argument`

Do you think it's worth considering? It's pure syntactic sugar, but callbacks placed at the end of the argument list make a lot more sense...

**Comment by d10** [comment]
You can try `_.bind`.

**Comment by jdalton** [comment]
We have `_.delay` but not looking to expand at the moment. You can use [_.mixin](lodash.com/docs#mixin) & [_.runInContext](lodash.com/docs#runInContext) to add your own methods though.
```js
var _ = require('lodash').runInContext();
_.mixin(...);
```
