### ISSUE TITLE
Allowing passing arguments to _.attempt'ed invocation

### ISSUE THREAD

**Issue by jareware** [lodash/lodash#929]
Would it be possible to change the signature of `_.attempt(func)` so that any arguments after `func` would be passed to the invocation of `func`? i.e. exactly as you can `_.defer(func, "hello")`.

Looking at [the source](https://github.com/lodash/lodash/blob/3.1.0/lodash.src.js#L10163), the extra arguments aren't currently used in any way, and consistency with other auto-invoking methods would be nice.

**Comment by jdalton** [comment]
Ya, that's doable.

**Comment by jdalton** [comment]
@jareware Would you mind creating a PR with the patch & tests?

**Comment by jareware** [comment]
Sure! I'll get back to this in a bit.

**Comment by jdalton** [comment]
Ping.

**Comment by jareware** [comment]
Rats, I had literally just gotten my laptop out to do this. :) Well something else to keep me occupied this Saturday morning, then...

Thanks!

**Comment by jdalton** [comment]
You can add [_.spread](https://github.com/lodash/lodash/issues/756) instead :)
