### ISSUE TITLE
Binding all predicates in all functions to specific this object

### ISSUE THREAD

**Issue by ynosa** [lodash/lodash#930]
Most of lodash function can accept an optional argument [thisArg] allowing to bind the predicate. Is there any way to implicitly bind this to all of the predicated in functions in lodash object or single chain wrapper object. I thought  that `_.runInContext` can be used, but it exists for other purpose.

**Comment by jdalton** [comment]
You can use `_.partial` with placeholders or `_.partialRight` to create a version that passes a `thisArg`.
```js
var filter = _.partial(_.filter, _, _, someThisArg);
filter(array, predicate); // executes `predicate` with the `this` binding of `someThisArg`

// or
var filter = _.partialRight(_.filter, someThisArg);
filter(array, predicate); // executes `predicate` with the `this` binding of `someThisArg`
```
