### ISSUE TITLE
Calling `push` on wrapped array returns unexpected results.

### ISSUE THREAD

**Issue by evanrs** [lodash/lodash#931]
While migrating to 3.1.0 I encountered some unexpected results, specifically:
```javascript
var wrap = _([])
wrap.push(1).push(2)
wrap.value()
// => []
```
I expected push to mimic an arrays native push function, updating the existing array. But we'll just reassign `wrap` and move on
```javascript
var wrap = _([])
wrap = wrap.push(1).push(2)
wrap.value()
// => [1, 2]
```
Everything seems fine now, until performing an operation on the reassigned wrapped array.
```javascript
var wrap = _([])
wrap = wrap.push(1).push(2)
wrap.find({})
wrap.value()
// => [1, 2, 1, 2]
```
```javascript
var wrap = _([])
wrap = wrap.push(1).push(2)
wrap.find({})
wrap.find({})
wrap.value()
// => [1, 2, 1, 2, 1, 2]
```
I'm not yet familiar with how 3.x.x works to tackle this one, but I'm looking forward to the PR that addresses it.

**Comment by jdalton** [comment]
Hi @evanrs!

This is covered in the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v300).
Deferred chaining creates a sequence of actions that can be (re)applied. In this case you're applying the sequence several times over with implicit and explicit `value()`.

**Comment by jdalton** [comment]
We things being deferred we could use some sequence APIs to smooth over these areas. I'm open to suggestions for things like an alias for `value()` a way to reseed the origin of the sequence, a way to resolve the value & re-wrap.

**Comment by jdalton** [comment]
I imagine something like:
```js
var wrap = _([]);

wrap = wrap.push(1).push(2).commit();
wrap.find({})
wrap.find({})
wrap.value()
// => [1, 2]
```

**Comment by jdalton** [comment]
Thoughts? Opinions on naming?
