### ISSUE TITLE
Binding all predicates in all functions to specific this object

### ISSUE THREAD

**Issue by ynosa** [lodash/lodash#934]
Thanks John for your response, I considered using _.partial with placeholders or _.partialRight for binding this to predicate, but it that case I need to do it for every function I need. Instead I would like to do have like embedded data transformation DSL:

 
```
var object = {
                       data : [],
                       otherData:[],
                       process: function(..){...}
                       getQuery: function(){ 
                                                        var tr = _.runInContext();
                                                        \\tr.bindToAllPredicates(this);
                                                         return tr(data);
                                                        }
                   };

object.getQuery().map(function(row){ this.process(row); console.log(this.otherData)}).value();
```
Is there something like"tr.bindToAllPredicates(this)" available without manual partial application and replacement of all function that have thisArgs in the arguments?

**Comment by jdalton** [comment]
You'll need to use `_.partial` or the like. You can automate it a bit. For example [here is how I handle wrapping](https://github.com/lodash/lodash-fp/blob/0.2.0/index.js#L83-L96) lots of methods in [lodash-fp](https://www.npmjs.com/package/lodash-fp).
