### ISSUE TITLE
takeRightWhile seems to be ignoring order of the elements in some cases

### ISSUE THREAD

**Issue by agzam** [lodash/lodash#935]
Either something I'm doing wrong, or maybe it's a bug. takeRightWhile just failed for me on grabbing array of DOM elements. Completely messed the order. I'll keep testing, hope it's a false alarm.

**Comment by jdalton** [comment]
Careful [_.takeRightWhile](https://lodash.com/docs#takeRightWhile) will only take the values from the right until the predicate fails.

**Comment by agzam** [comment]
Sorry, no it seems I missed something. No it's working just fine.
