### ISSUE TITLE
Observable streams

### ISSUE THREAD

**Issue by ccorcos** [lodash/lodash#936]
I just saw this really cool talk about observable streams:

https://www.youtube.com/watch?v=XRYN2xt11Ek

I thought it may be relevant for this project -- maybe it would be cool to incorporate these patterns at some point.

**Comment by jdalton** [comment]
Hi @ccorcos. @mattpodwysocki and I are buds. I think this is better suited for [RxJS](https://github.com/Reactive-Extensions/RxJS).

**Comment by ccorcos** [comment]
haha go figure! cool stuff.
