### ISSUE TITLE
_.where() ignores prototype members in v3.1.0...

### ISSUE THREAD

**Issue by busticated** [lodash/lodash#937]
Should this work?

    var lo = require('lodash');
    
    function Obj(){};
    Obj.prototype.is = false

    lo.where([ new Obj, new Obj, new Obj ], { is: false }); // []
    'is' in new Obj // true

result is an empty array. i would expect an array of `Obj` instances w/ length 3. this is how v2.4.1 behaved.

    lo.where([{ is: false }, { is: false }, { is: false }], { is: false }); // [ { is: false }, { is: false }, { is: false } ]

returns what i expect.

if this is expected behavior, is there a more appropriate way to do what i want?

thanks in advance!

**Comment by jdalton** [comment]
Totally covered in the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v300) and in several other issues #892,  #899, #909.

In v3 iteration and matching is now consistent with iterating own properties of sources & destination objects.Think of it like how `_.isEqual(a, b)` works.

In v3 there is [_.toPlainObject](https://lodash.com/docs#toPlainObject) to flatten inherited enumerable properties to own properties of an object.

**Comment by busticated** [comment]
got it. thanks. it might be helpful to note (given that this has come up a bunch it seems) that `_.matches` is used by `_.where` and others. personally, i spun thru the changelog just looking for changes to `_.where`.

**Comment by jdalton** [comment]
Will do.

**Comment by jdalton** [comment]
Also let me know how `_.toPlainObject` works out for ya.

**Comment by busticated** [comment]
aw man, yr awesome :)

i ended up just going with a filter + callback - e.g. `_.filter(objs, function(o){ return o.is === false; });` 

typing the extra ~19 characters got me winded but i guess the exercise is helpful.

:-D

**Comment by jdalton** [comment]
It's a bit of a bummer that there's a compat issue but in the end I think having consistent iteration is a good thing. This way our iteration of properties on `_.assign`, `_.defaults`, `_.mixin`, `_.isEqual`, `_.matches`, `_.isMatch` is consistent and aligns with ES6 (ES2015).

In v2.4.1 
```js
function Foo() {}
Foo.prototype.a = true;

var foo = new Foo,
      obj = { 'a': false };

var objects = [obj, foo];
_.where(objects, { 'a': true });
// => [foo]

// but deep woudn't match
var objects = [{ 'o': obj }, { 'o': foo }];
_.where(objects, { 'o': { 'a': true } });
// => []
```

**Comment by jdalton** [comment]
Btw if you're matching falsey you can just use the `property` shorthand & [_.reject](https://lodash.com/docs#reject)
```js
 _.reject(objs, 'is');
```

**Comment by busticated** [comment]
yup, makes sense. going thru the upgrade now, it's not too painful all told. especially considering how much i'm using the lib (basically everywhere, haha!)

> Btw if you're matching falsey you can just use the property shorthand & _.reject:

nice! but, yeah, i'm specifically testing for `false` in this case.

**Comment by jdalton** [comment]
@busticated What do you think of this. The common case is to do a property lookup for 1 value. What if we extend the "property" shorthand to allow a value:
```js
_.filter(objs, 'is', false);
```

**Comment by busticated** [comment]
ah, yeah, that's nice. i'd go for that :)

just thinking out loud here - i wonder if that implies `.some()` and `.every()` (perhaps others?) would support the same signature? another approach could be to have `_.property()` accept a 2nd `value` arg - e.g. `_.filter(objs, _.property('is', false));`

**Comment by jdalton** [comment]
>  i wonder if that implies .some() and .every() (perhaps others?) would support the same signature?

Yes

>  another approach could be to have _.property() accept a 2nd value arg - e.g. _.filter(objs, _.property('is', false));

It would be tied into the first as part of the "property" shorthand. So `_.property` would also accept a second arg. Since the `_.property` method is just a property getter it avoids the whole own/inherited thing and gets the value regardless.

**Comment by busticated** [comment]
got it. yeah, that'd be great :+1:

**Comment by jdalton** [comment]
This would also be significantly faster than `{ 'is': foo }` as that has to get the keys then iterate and check where as `name, value` is straight forward.

**Comment by jdalton** [comment]
The only thing it wouldn't be able to match would be `undefined`. Hmm.

**Comment by jdalton** [comment]
With lodash v3.2.0 you can now use the [_.matchesProperty](https://lodash.com/docs#matchesProperty) shorthand:
```js
_.filter(objs, 'is', false);
```
