### ISSUE TITLE
_.compose called with no arguments returns a function that always returns undefined

### ISSUE THREAD

**Issue by tjwallace** [lodash/lodash#938]
In version 3.1.0:
```javascript
var a = _.compose();
a(1) // => undefined
```

In version 2.4.1:
```javascript
var a = _.compose();
a(1) // => 1
```

**Comment by jdalton** [comment]
Thanks, I'll add that to the compat notes. Is there a use case for `_.compose()` will no arguments?

**Comment by tjwallace** [comment]
We wrote our own serializer, and use `_.compose.apply(null, serializers)(object)` to generate the serialized object where `serializers` is an array of functions. `serializers` is initialized as an empty array, so in 2.4.1 it worked, but in 3.1.0 it returns `undefined`. To fix I now initialize `serializers` to `[ _.identity ]`.

**Comment by jdalton** [comment]
Ya, the `identity` behavior of pre 2.4.1 wasn't really intended but I can see the utility. I'll flag this as a bug.

Related to #352.

**Comment by tjwallace** [comment]
Thanks @jdalton
