### ISSUE TITLE
Sequelizejs ResultSet cannot filter/find matches instances Using Lodash 3.x _.matches()

### ISSUE THREAD

**Issue by jchbh-duplicate** [lodash/lodash#939]
SequelizeJS use get() method to make access by object.property translate into object.get(property)
And Because the _.matches will check the hasOwnProperty in object, SequelizeJS instances will return false and cause the filter/find result set return Array[0];

in 2.4 ->
_.findIndex(instances, {id: 1}) => will return index of instance whose id is 1
in 3.1 ->
_.findIndex(instances, {id: 1}) => will return -1

and we should hard code in 3.1 ->
_.findIndex(instances, {dataValues: {id: 1}} ) => will return index of instance whose id is 1

but if some magic instance "Get" function setup, it will not be found by {dataValues:xxx}.
How can I deal with this problem?

**Comment by jdalton** [comment]
Convert the objects to plain objects with [_.toPlainObject](https://lodash.com/docs#toPlainObject) or use the long for `function(v) { return v.id == 1}`.

**Comment by jchbh-duplicate** [comment]
Using _.map(_.toPlainObject) will change the original instances but it is useless, as I say those instance's property is not direct access by _.keys. 

Long form must be ok but it looks not elegant. 

Can add some customised parameter to make those object style _.matches backward compatible with 2.4?
Or what's the reason why should restrict only filter the values belong to the properties of object itself? Does it safety if remove call of hasOwnProperty in current BaseMatches.js

**Comment by jdalton** [comment]
> Using `_.map(_.toPlainObject)` will change the original instances but it is useless, as I say those instance's property is not direct access by `_.keys`.

```js
var myObjects = _.map(arrayOfObjects, _.toPlainObject)
```

> Can add some customised parameter to make those object style _.matches backward compatible with `2.4`?

No. Read some of the related issues I linked to. It's a consistency issue.

**Comment by jdalton** [comment]
You could add your own `propertyMatches` mixin.
```js
_.mixin({
  'propertyMatches': function(property, value) {
    return function(object) {
     return object != null && object[property] === value);
   }
  }
});
```

**Comment by jdalton** [comment]
Ok so I've thought about it and the demand is high enough that I think a `_.matchesIn` makes sense. It can be used like `_.matches` to create a function that matches inherited properties too.

**Comment by jdalton** [comment]
With lodash v3.2.0 you can now use the [_.matchesProperty](https://lodash.com/docs#matchesProperty) shorthand:
```js
// in 2.4.1
_.findIndex(instances, {id: 1});

// in 3.2.0
_.findIndex(instances, 'id', 1);
// =>  will return index of instance whose id is 1
```
