### ISSUE TITLE
humanize for String methods?

### ISSUE THREAD

**Issue by justin808** [lodash/lodash#941]
@jdalton, any consideration for adding a humanize String method?

http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-humanize

humanize(lower_case_and_underscored_word, options = {}) Link
Tweaks an attribute name for display to end users.

Specifically, humanize performs these transformations:

* Applies human inflection rules to the argument.
* Deletes leading underscores, if any.
* Removes a "_id" suffix if present.
* Replaces underscores with spaces, if any.
* Downcases all words except acronyms.
* Capitalizes the first word.
The capitalization of the first word can be turned off by setting the :capitalize option to false (default is true).

humanize('employee_salary')              # => "Employee salary"
humanize('author_id')                    # => "Author"
humanize('author_id', capitalize: false) # => "author"
humanize('_id')                          # => "Id"
If “SSL” was defined to be an acronym:

humanize('ssl_error') # => "SSL error"

**Comment by jdalton** [comment]
I'd like to keep the transformations simple. This gets bit complicated around inflection rules.

**Comment by luiz-brandao** [comment]
For those looking for this functionality, the [_startCase](https://lodash.com/docs/4.17.4#startCase) method might be enough for you.
