### ISSUE TITLE
Lodash's _.rest is different from Underscore's

### ISSUE THREAD

**Issue by monovertex** [lodash/lodash#943]
From what I read in the other issues, I understand that with 3.0, Lodash has dropped the Underscore replacement build for Backbone because they are compatible. However, Underscore.js 1.7 has a different `_.rest` definition (`_.rest(array, [index])`) from Lodash.js 3.1 (`_.rest(array)`).

This breaks a Backbone plugin, namely Backbone.Stickit. I cannot switch back to underscore, because I use certain features that are only available in Lodash.

I was under the impression that Lodash is providing what Underscore provides and more (and faster). I only found this issue so far, but there could be more. Could you advise me what do to in this situation?

**Comment by jdalton** [comment]
In lodash v3 we've split the functionality out into `drop`. In Underscore `drop` is an alias for `rest` so you can simply use `_.drop(array, index)` for cross-lib support.

**Comment by jdalton** [comment]
Also I'm not seeing any `rest` use in [backbone.stickit](https://github.com/NYTimes/backbone.stickit/blob/master/backbone.stickit.js).

**Comment by monovertex** [comment]
It is, in their official [v 8 release](https://github.com/NYTimes/backbone.stickit/blob/0.8.0/backbone.stickit.js). I generally try not to use the master branch version as it can be unstable sometimes.

Anyway, thanks for the help, using stickit's master version did solve that.

**Comment by rafde** [comment]
Stickit release 0.9.0 this morning.

**Comment by triumphalism** [comment]
thanks
