### ISSUE TITLE
problem about the array passed to iteratee as the 3rd arg while chaining

### ISSUE THREAD

**Issue by qsona** [lodash/lodash#944]
```
var ary = [1, 2, 3];
var addOne = function(x) { return x + 1; };

// case (A)
_.takeWhile(_.map(ary, addOne), function(value, index, array) {
  console.log(array); // [2, 3, 4]
});

// case (B): use chaining
_.chain(ary).map(addOne).takeWhile(function(value, index, array) {
  console.log(array); // [1, 2, 3]
}).value();
```

The 3rd argument passed to callback at case (A) and the one at case (B) are different. I guess it is not an expected result at case (B).

But if we want to correct it (to pass `[2, 3, 4]` at case (B)) it cannot be evaluated lazily anymore because `[2, 3, 4]` cannot be got unless the _.map operation is entirely executed.
Personally I haven’t used this 3rd arg so I cannot imagine how it’s useful, but I think the advantage of lazy evaluating should be prior.
 
Same problem occurred when I was implementing the lazy version of `_.uniq` (#912). While my personal opinion is to obsolete this 3rd argument at some cases, I want to hear your opinion. Thank you.

**Comment by qsona** [comment]
To clarify the current behavior of it, I add one more example.

```
var ary = [3, 2, 1];
var addOne = function(x) { return x + 1; };
_.chain(ary).sortBy().map(addOne).takeWhile(function(value, index, array) {
  console.log(array); // [1, 2, 3], which is the result after sorted and not mapped yet
}).value();
```

**Comment by jdalton** [comment]
@qsona Thank you for digging into this. I hadn't thought about the third callback param. I think it's fine not updating as it's a side effect of lazy evaluation similar to others when trying to observe all possible iterations. I'll add a test for this behavior though.

**Comment by qsona** [comment]
Thanks!
It may make sense even though we should be careful if we use the third param in chaining.

**Comment by jdalton** [comment]
See https://github.com/lodash/lodash/issues/997. With https://github.com/lodash/lodash/commit/b872bc9146bba33d35623dbd80a834c1934cd079 if you pass an iteratee with more than `1` param it will disable shortcut fusion.
