### ISSUE TITLE
_.find in 3.x can not cope with getters

### ISSUE THREAD

**Issue by randing89** [lodash/lodash#945]
Please see this for the problem http://plnkr.co/edit/NNUlgJQYsDNCqcbR8csP?p=preview 
Method return undefined in 3.x but works fine in 2.4.1. I am using Chrome 40.0.2214.111

**Comment by jdalton** [comment]
Related to #892, #899, #909, #937, #939.

**Comment by jdalton** [comment]
With lodash v3.2.0 you can now use the [_.matchesProperty](https://lodash.com/docs#matchesProperty) shorthand:
```js
// in 2.4.1
_.find(arr, { one: 1 });

// in 3.2.0
_.find(arr, 'one', 1);
// => [sub]
```
