### ISSUE TITLE
_.isUndefined performance

### ISSUE THREAD

**Issue by sevin7676** [lodash/lodash#947]
Why does lodash use an incredibly slow method for isUndefined?

``` javascript
function isUndefined(value) {
      return typeof value == 'undefined';
}
```

Is there a case when this function would not work properly?

``` javascript
function isUndefined(value) {
      return value === undefined;
}
```

This [jsPerf test] (http://jsperf.com/lodash-isundefined-vs-triple-equals/6) shows that the method currently used is 2.7x slower than the method I'm suggesting.

**Comment by jdalton** [comment]
Sorry not interested. Don't use the method if that's you're issue.

**Comment by sevin7676** [comment]
My mistake, I copied someone else's jsPerf test and just added to the end of it without paying much attention. 

I wrote a [proper test](http://jsperf.com/typeof-vs-undefined-check/23) and it looks like my suggestion was invalid as this test shows that my propsed method is actually 2% slower in chrome and firefox and 25% faster in IE (I don't care about IE).

Thanks for the quick response.

**Comment by jdalton** [comment]
No problem. Sorry for my grouchy tone.
