### ISSUE TITLE
not to be bounded to window by default

### ISSUE THREAD

**Issue by pasupulaphani** [lodash/lodash#948]
Hi all,

In my scenario where one of my client has different version of Lodash and my library is using different version of Lodash.

We ended up overriding our window._

Is there a way to source underscore and not to be bounded to window. Instead bind to the reference provided.

Sorry if there is something already out there but I'm unaware of.

Kind regards,
Phani.

**Comment by d10** [comment]
You can use `_.noConflict` after requiring lodash:

```
// Before:
// _ → lodash
var lodash = _.noConflict();
// After:
// _ → original _
// lodash → lodash
```

**Comment by pasupulaphani** [comment]
Thank you

**Comment by erykpiast** [comment]
What about ES6 and `import` statement? It has to be on top of the file, before any code. If I do it like this:

   import lodash from 'lodash';
   import 'a';

   lodash.noConflict();
   
module `a` still has access to `_` global variable. The question is, why, NPM-ed lodash has to export itself to global?

**Comment by jdalton** [comment]
The UMD for v3 doesn't sport to global if it catches the node `module.exports` path.
