### ISSUE TITLE
_.rest no longer works in the same manner.

### ISSUE THREAD

**Issue by SecretDeveloper** [lodash/lodash#951]
Previously we could use something like

    _.rest(['a','b','c'], 2)
    // result is ['c']

but now we are seeing ['b','c'] as the result regardless of the value provided for the second parameter.

Using _.drop instead appears to work and checking the documentation it seems as though the API has changed for this method so perhaps this is by design.  It did catch us out on an application because the changelog appears to reflect the old manner in which it used to work.

From the changelog:

    var array = [1, 2, 3],
    _.rest(array, 2); // → [3]  

The second line here is not correct and is not what we see happening in version 3.1.0.  Instead we get [2,3].

Can it be changed to work with the count parameter or else the changelog needs to be more explicit as this is a subtle change that you don't see unless testing for it directly.

Thanks

**Comment by jdalton** [comment]
Yap this is a by design [change](https://github.com/lodash/lodash/wiki/Changelog#v300).
You can use [_.drop](https://lodash.com/docs/#drop) instead.

Related to #946.
