### ISSUE TITLE
Publish browserified bower packages

### ISSUE THREAD

**Issue by andrezero** [lodash/lodash#952]
Hi!

I have been using a couple of lodash functions in frontend code.

I believe it would be great if we could pull them in as bower dependencies so that we could avoid having to bundle them with our own bower packages (avoid repetition, let bower pull the necessary lodash deps at install time).

I'm not sure about this, but I'm under the impression bower does not allow to register/publish several pkgs from the same repo.

So, have you ever looked into this and do you think it's viable to generate individual bower packages?  

Do you agree the ideal target format for each package would be bower.json + browserfied lib?

Do you think this process could be automated?

Let me know what you think, I can definitely help if needed.

**Comment by jdalton** [comment]
I'm not interested in publishing browserified packages. Use browserify and integrate that into your workflow.

**Comment by andrezero** [comment]
The point was more about making individual components available on **bower**.

Adding browserify/webpack workflows in an individual workflow is good for apps but doesn't work for libraries that depended on lodash functionality.

As it stands, the only bower dependency we can use is the existing monolithic bower lodash. Doesn't seem sensible to do it for a micro library with less than 1K if all the library needs to consume is a couple of lodash methods.

Congrats for the great work, anyways.

**Comment by jdalton** [comment]
> Adding browserify/webpack workflows in an individual workflow is good for apps but doesn't work for libraries that depended on lodash functionality.

If you're a lib dev author then you shouldn't be using bower to try to integrate custom bits. Use node+npm+browserify/webpack. See https://github.com/postaljs/postal.js/issues/91#issuecomment-73159144 for an example.

**Comment by andrezero** [comment]
Thanks again for the response. 

Somehow I don't think I am able to communicate what I have in mind. It's either that or I'm not wiz enough to find the answer I'm looking for in all the PR/issue I've browsed so far.

But I'm guessing that by **integrate** you mean "distribute the lib bundled with a custom build of lodash".

And that's not what I have in mind.

Imagine you have 5 micro libs that consume arbitrary lodash functionality. Ideally, I would be able to distribute them independent bower pkgs with their dependencies on "lodash-merge", etc...

**bower.json:**
```
{
  "dependencies": {
    "angular": "~1.3.8",
    "lodash-merge": "~3.0.0"
  }
}
```

Bower takes care of resolving the `lodash-merge` deps and grabbing everything else, delegating to the user any version conflict resolution. The user ends up with a single instance of each of the necessary components and it's up for the lib consumer to decide how to build the app. 

Also, typically, bower libs are browser ready, hence my `browserify` question.

Cheers

**Comment by jdalton** [comment]
If bower could automatically consume and browserify npm packages that would rock. At the moment bower requires a branch or tag and that would clutter things up. Have you checked out [Duo](http://duojs.org/). It may be able to do what you're looking for.

**Comment by andrezero** [comment]
Thanks a lot for that link. Checking it now and I'm really impressed.

On one hand, I am glad I could finally explain the whole thing. Thanks for taking the time.

On the other hand, unfortunately, my guess about bower limitations was right in the first place. :-( it's a shame.

I will try out Duo, of course. But I'm focused on converging into tools that are widely adopted and documented (even if they're fundamentally flawed). 

That's why I was looking into DRYing out all this code in these micro libs around lodash. But dropping bower is a deal breaker. 

Until I can find a "browser ready" util suite, with the quality of lodash, that is available as micro-packages, I'll probably not DRY as much. 

Or, alternatively, rely on other micro-libs and their limitations. I'll just have to document that my lib will break if provided data with circular references ;-) and hope that the owners don't fuu their pkgs.

**Comment by jdalton** [comment]
> Or, alternatively, rely on other micro-libs and their limitations. I'll just have to document that my lib will break if provided data with circular references ;-) and hope that the owners don't fuu their pkgs.

So gross :P
