### ISSUE TITLE
Ensure something is array

### ISSUE THREAD

**Issue by callumacrae** [lodash/lodash#953]
I think this is a feature request, but it's possible it already exists and I just can't find it.

I often find myself writing the following:

```js
_.isArray(something) ? something : [something]
```

It would be useful if there were a function called something like ensureArray that did this:

```js
_.ensureArray([1, 2]); // [1, 2]
_.ensureArray(1); // [1]
```

I'd be willing to write this if other people think it would be useful in the core. Also, not a fan of `ensureArray`—if anyone could think of a better name, that would be useful.

**Comment by jdalton** [comment]
I've seen this requested a few times in Underscore, one as `ensureArray`, others suggested `wrapArray` or `asArray`. A nice name would help for sure.

**Comment by callumacrae** [comment]
Of those three, I prefer the first one: the other two imply that you're turning something into an array, and you're not, necessarily.

**Comment by megawac** [comment]
I think the best name that we came up with last time this was discussed was `_.list`

**Comment by callumacrae** [comment]
`list` in Python is for converting sequence types into lists, that's pretty different. Also not very descriptive

**Comment by jdalton** [comment]
I've got this in my own code from lodash-cli:
```js
_.isArray(identifier) ? _.clone(identifier) : [identifier]
```

So I can see that cases come up. It's going to come down to naming and naming things stinks.

**Comment by jdalton** [comment]
`_.castArray`:
![image](https://cloud.githubusercontent.com/assets/4303/6132757/a9970758-b109-11e4-80f8-1eed9087346d.png)

**Comment by cowboy** [comment]
So if it's already an array, you're returning a copy?

**Comment by Ky6uk** [comment]
```_.wantArray``` as in Perl

**Comment by steveoh** [comment]
Seems a bit like [setdefault](https://docs.python.org/2/library/stdtypes.html#dict.setdefault) in python?

**Comment by terpinmd** [comment]
toArray

**Comment by olegafx** [comment]
`_.letArray`

**Comment by dkempner** [comment]
_.arrayOfSunshine

**Comment by deanh** [comment]
I like asArray or ensureArray. I get that asArray is a bit more ambiguous, but an array as an array being trivially true makes sense to me.

**Comment by JonAbrams** [comment]
`_.array` is available.

Also, this is how I've solved this issue before: `value = [].concat(value)`. I have no clue if it's performant or how it works in edge cases though.

**Comment by vivainio** [comment]
_.array()

**Comment by heff** [comment]
Would this essentially do the same as ` _.flatten([something]);`?

**Comment by factormystic** [comment]
`_.toArray` or `_.asArray`

**Comment by davidkpiano** [comment]
+1 for `_.array()` or `_.asArray()`.

`_.ensureArray()` might be a bit unintuitive.

**Comment by rasmusfl0e** [comment]
+1 for `_.toArray()` - reminds me of `toString`.

**Comment by nicinabox** [comment]
We have `ensureArray` in our codebase. I've never found it to be unintuitive. 

I also like `_.array`

**Comment by jquense** [comment]
I've always called this method `splat` which doesn't make sense in a larger programming context, but that's what the first lib I saw it in called it and it stuck. Nice and short, and the negation isn't awkward: `unsplat`

**Comment by megawac** [comment]
> I've always called this method splat which doesn't make sense in a larger programming context, but that's what the first lib I saw it in called it and it stuck.

Mootools?!! :D

**Comment by riyadhalnur** [comment]
there's already a `_.toArray` method that does that already, init?

**Comment by jdalton** [comment]
Thanks all. I'll reference @coyboy's [comment](https://github.com/lodash/lodash/issues/953#issuecomment-73747407).
>  So if it's already an array, you're returning a copy?

Since the code required is trivial `_.isArray(value) ? value : [value]` and behavior could vary (cloning vs. not cloning) I'm going to leave this out.

**Comment by jasonkarns** [comment]
+1 for `_.toArray` or `_.array`

In Ruby, the idiom is to use the desired type/class as a function. So `Array(x)` would convert a thing into an Array, String -> String, etc. They're called Conversion Methods.

It works the same as desired here: return the argument if already of the correct type (no alteration), otherwise, convert into the desired type in whatever way makes sense given the current type.

Hence why I think `_.array` makes sense as well. But `_.toArray` is a nice complement to `toString`. `ensureArray` or `asArray` are too cutesy, IMO, and don't draw on existing idioms in JS or other langs.

**Comment by jdalton** [comment]
Also folks we already have [_.toArray](https://lodash.com/docs#toArray) but it's behavior is slightly different (for converting collections to array).

**Comment by StreetStrider** [comment]
In vanilla JS I usually use `[].concat(value);`, that's pretty idiomatic for me.
In contrib-modules there's a function called `cat` ([lodash-contrib](https://github.com/TheNodeILs/lodash-contrib/blob/ff8bd8a922e3eeab1421c3501ae579b329c1ec34/docs/_.array.builders.js.md#cat)) it concatenates arrays and array-like objects. It also works as my snippet above and suits for TS' request.
So I personnaly stay for this function. It can solve vast range of array converting problems.
I also implemented such function myself: [cat](https://github.com/StreetStrider/aux.js/blob/a939eafa2f31e1a8bf2e645740b7eaaac714fea7/array/cat.js).

**Comment by jdalton** [comment]
> [].concat(value)

Other threads have pointed out the downside there is if `value` is `undefined` you end up with `[undefined]` where you may want `[]` instead. Tricky edge cases all around.

**Comment by StreetStrider** [comment]
@jdalton, right, exactly. I'm usually eliminate falsy on earlier stage, but thanks to `_.compact` it is also possible directly in collection. Or something like `[].filter(Boolean)` can be used (but maybe you know some corner case for this snippet too :D).

However, I'm sorry for posting into wontfixed task, but thing like `cat` is really good. Typical examples: working with arguments, working with path joining, anywhere we need to combine some «fixed» values with arrays and array-like objects (where length is unknown). Looks like new ES helps us with rest & spread features. Anyway I think stuff like `cat` can be useful. Just wanted to attract notice to that.

**Comment by jdalton** [comment]
> Anyway I think stuff like `cat` can be useful. Just wanted to attract notice to that.

There's `concat` in the chaining syntax, I could see it moving to the static methods.

**Comment by elado** [comment]
Joining late to the party,

@jdalton, is there a lodash way to achieve that?

`_.concat` seems problematic because it turns primitives into wrapped version, so `_.concat(1)[0] !== _.concat(1)[0]` (because `new Number(1) !== new Number(1)`)

What's the reasoning behind converting primitives anyway?

Thanks

**Comment by jdalton** [comment]
@elado Not yet. But lets never forget https://github.com/lodash/lodash/issues/953#issuecomment-73746507.

**Comment by elado** [comment]
@jdalton only if it comes with an easter egg `_.wilson`!

Anyway, would love to see something like Ruby/ActiveSupport's `Array.wrap`.

```ruby
Array.wrap([1, 2, 3])     # => [1, 2, 3]
Array.wrap(1)             # => [1]
Array.wrap(nil)           # => []
Array.wrap({a: 1, b: 2})  # => [{:a=>1, :b=>2}]
```

I currently use

```js
_.mixin({
  arrayWrap(thing) {
    return _.isArray(thing) ? thing : thing != undefined && thing != null ? [thing] : []
  }
}
```

I saw poll results from https://github.com/lodash/lodash/issues/1740#issuecomment-170634927

They favored (just by a bit!) `_.asArray(undefined) => [undefined]` over `_.asArray(undefined) => []`. The latter is Ruby's implementation.

Use case is mostly an argument of a function that can get a single value or an array (without spread `...` or `arguments`)

```js
// example 1
function destroy(ids) {
  ids = _.asArray(ids)
  _.each(ids, id => console.log('destroying', id))
}

destroy(1)
destroy([1,2,3])
destroy()

// example 2
function combine(a, b, someLogic) {
  a = _.asArray(a)
  b = _.asArray(b)
  return a.concat(b).filter(someLogic)
}

combine(5, 6, i => i > 4) // => [ 5, 6 ]
combine(5, [6, 10], i => i > 4) // => [ 5, 6, 10 ]
combine(5, undefined, i => i > 4)  // => [ 5 ]
```

On the last `destroy()` the `ids` are `undefined` and it makes sense not to do anything (I think)
And the `combine` (not a great example) would also make sense that `undefined` aren't taken into account.

In both `[]` and `[undefined]` there's a tradeoff...

**Comment by StreetStrider** [comment]
[lodash-contrib#cat](https://github.com/node4good/lodash-contrib/blob/97dd3b5337ad26c4330fbdb3d45748859a292aab/docs/_.array.builders.js.md#cat)

**Comment by jdalton** [comment]
It's time to add this to core. First one to PR it gets dibs. Let's call it `_.asArray`.

**Comment by ypresto** [comment]
I wanna use `_.castArrayLike` for `document.querySelector('form')['checkboxes']`, which is a RadioNodeList if many, and an Element if only one input tag.
Can I send PR for it?

**Comment by jdalton** [comment]
Hi @ypresto!

I think you're better off with a custom solution.
