### ISSUE TITLE
Using #find removes chain wrapper.

### ISSUE THREAD

**Issue by DylanPiercey** [lodash/lodash#954]
```JavaScript
_(arr).find({ id: id }) // Returns object.
_(arr).find({ id: id }).defaults({ name: 'hi' }).result('name').value(); // Breaks at defaults.
```

The example is a bit odd and perhaps this is the intended behaviour, but I think it would be nice to continue the chain using object functions after a #find.

**Comment by jdalton** [comment]
Since `find` resolve a value it implicitly ends the chain. To force chaining you can simple do `_(arr).chain().find(...).defaults(...).result(...).value()`

**Comment by yairEO** [comment]
what a **nightmare**
