### ISSUE TITLE
lazy slice after filtering may be broken

### ISSUE THREAD

**Issue by qsona** [lodash/lodash#955]
`_([1, 2, 3]).filter().slice(1, 3).value();` // expected [2, 3] but actual [2]

I digged by using `git bisect` and it seems to be occured since commit 
6dfc2aca4beaabd758404b1191f7d8044c0b6c23

Sorry if I'm wrong. Thanks.

**Comment by AaronO** [comment]
Hi @jdalton, this issue was troubling us for [GitbookIO/gitbook](https://github.com/GitbookIO/gitbook). Any idea when this fix will be shipped as part of a new release ?

(We could use a `git+https:// ...` dependency, but that's less than ideal).

**P.S:** Thanks for the great work on `lodash` :+1:

**Comment by jdalton** [comment]
A bump will happen this evening or in the morning. It will be v3.2.0.
