### ISSUE TITLE
slice in chained methods

### ISSUE THREAD

**Issue by SamyPesse** [lodash/lodash#958]
Since I switched to version `3.1.0` (from `2.4.1`), this code is not working anymore:

```
var _ = require("lodash");

var a = _.chain([1,2,3])
    .slice(0, 1)
    .reverse()
    .find(function(v) {
        return v > 1;
    })
    .value();
```

If I remove the `.slice`, it's working fine. It looks like `slice` can't be used anymore just after `.chain`.

**Comment by jdalton** [comment]
It's not just `slice`, this is an issue with tracking the `__chain__` value.

**Comment by jdalton** [comment]
Narrowed it down to `reverse` not tracking `__chain__`.
