### ISSUE TITLE
groupBy no longer chainable (in 3.1.0)?

### ISSUE THREAD

**Issue by radudh** [lodash/lodash#960]
In version 3.1.0, it seems groupBy is no longer chainable (or I'm doing something wrong):

    var data = [
      {value: 1, info: "unuunu"},
      {value: 1, info: "unudoi"},
      {value: 2, info: "doiunu"}
    ];

    _.chain(data).groupBy("value").each(function(item) {
      console.log(item);
    });

The above snippet writes nothing in the console.
Tested in latest Chrome and Firefox 35.0

**Comment by ricardomatias** [comment]
You need to add `.value()` at the end and return the item inside `.each`

	_.chain(data).groupBy('value').each(function(item) {
		console.log(item);
	  	return item;
	}).value();

This works for me in Chrome.

**Comment by radudh** [comment]
Thank you, it works, even without a return item in the each loop.

A bit strange though, to call value() at the end, I think in version 2.4.0 worked without it.

**Comment by jdalton** [comment]
@radudh For a rundown on the breaking changes in v3 see the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v300).

Chaining is now deferred until an implicit or explicit `value()` is requested. The `_.each` method returns the provided `collection` so does not warrant an implicit `value()` call.
