### ISSUE TITLE
`delete` method for better FP

### ISSUE THREAD

**Issue by barneycarroll** [lodash/lodash#962]
The fact that `delete` is an operator while `Array.prototype.splice` makes functional composition difficult. Would a delete method be viable?

Something like:
```javascript
_.delete = ( collection, key ) => {
	if( collection instanceof Array ){
		return collection.splice( key, 1 );
	}
	else if( collection instanceof String ){
		return collection.slice( 0, key ) + collection.slice( key + 1, collection.length );
	}
	else {
		delete collection[ key ];
		return collection;
	}
}

**Comment by jdalton** [comment]
We have a [_.remove](https://lodash.com/docs#remove) for arrays. I want to avoid "remove" for collections as that can be handled a couple different ways for objects (`delete` or nulling/undefining). For making this a mixin you can use:

```
var _ = require('lodash').runInContext();
_.mixin({ 'delete': ... });
```

**Comment by barneycarroll** [comment]
@jdalton fair enough.

**Comment by jdalton** [comment]
Just a heads up `_.unset` has landed in the master branch.
