### ISSUE TITLE
Question about commonjs module export

### ISSUE THREAD

**Issue by brianc** [lodash/lodash#963]
Howdy.

I love this module and __love__ the work y'all have been doing recently. +100. Sorry for asking this question here but I've searched the docs and issues & can't find an answer.

I generated a commonjs style module for client side development with `lodash-cli` & it worked fine, but it's uncomfortable to have to do `var _ = require('lodash')._` instead of what I would _like_ which is `var _ = require('lodash')`.  Is there any option or config anywhere to do that? I'm tempted to just generate a non-minified version & modify it myself to do that, but I'd rather just use a command-line flag from `lodash-cli`

**Comment by brianc** [comment]
Nevermind! Figured it out - just generate it with `node` style exports. Works with systemjs like a champ! :star: :heart: :dancer:

**Comment by jdalton** [comment]
Hi @brianc! Yap, the `module.exports` feature of Node is an  extension to CommonJS so is available with `exports` as `node`.
