### ISSUE TITLE
Replacement of underscore in Backbone...still viable?

### ISSUE THREAD

**Issue by bazineta** [lodash/lodash#964]
The Wiki has an article regarding replacement of underscore with lodash in environments that use Backbone.  That article was written for 2.4.1, and it was accurate at that time and release.

However, with the breaking changes listed in 3.0, is this still a viable course of action?

If so, could that statement be made clear, and, if not, could the link to the Wiki article be modified so as to indicate that it's no longer applicable?

**Comment by jdalton** [comment]
We still [test](https://saucelabs.com/u/lodash) against the Backbone's unit tests. As you noted there are some differences but in general it should still work.
