### ISSUE TITLE
Chaining in per-method build

### ISSUE THREAD

**Issue by erykpiast** [lodash/lodash#966]
When using lodash from separate packages, it's not possible to chain functions  - it's clear and obvious. But without chaining, complex operations get more and more unreadable, so usually I use helpers like [this one](https://gist.github.com/erykpiast/01514a6a4c05d8422c5a#file-patterns). I wonder if there is a place in lodash for util like that? I mean, in per-module build? I can imagine it working exactly like chaining functions in "full" library (without passing arguments to interceptor).

```
var chain = require('lodash.chain');
var assign = require('lodash.assign');
var groupBy = require('lodash.groupby');
var pick = require('lodash.pick');

chain([ 42 ])
  .thru((v) => groupBy(v))
  .thru((v) => assign(v, { "24": "24" }))
  .tap((v) => console.log(v))
  .thru((v) => pick(v, '42'))
  .value()
```
Do you find it can be useful?

**Comment by jdalton** [comment]
Individual packages like `lodash.assign` won't likely get chaining. The modularize `lodash` package may in the future. I could maybe see the `chain` category module, `require('lodash/chain')`, being used to add such sugar though not sure exactly how it would know what to add to be chainable. Using the monolithic module `require('lodash')` for reference you can recreate the chaining sugar using `require('lodash/foo/bar')`.

**Comment by erykpiast** [comment]
To be honest, I don't get it :)

> Using the monolithic module index.js , require('lodash'), for reference you can recreate the chaining sugar using require('lodash/foo/bar') modules.

Could you elaborate it more? Some examples?

**Comment by jdalton** [comment]
I figured it might need an example:
```js
var LodashWrapper = require('lodash/internal/LodashWrapper'),
    lodash = require('lodash/chain/lodash')
    baseForOwn = require('lodash/internal/baseForOwn'),
    mixin = require('lodash/utility/mixin');

// Ensure `new LodashWrapper` is an instance of `lodash`.
LodashWrapper.prototype = lodash.prototype;

// Add functions that return wrapped values when chaining.
lodash.chunk = require('lodash/array/chunk');
// ...

// Add functions to `lodash.prototype`.
mixin(lodash, lodash);

// Add functions that return unwrapped values when chaining.
lodash.capitalize = require('lodash/string/capitalize');
// ...

mixin(lodash, (function() {
  var source = {};
  baseForOwn(lodash, function(func, methodName) {
    if (!lodash.prototype[methodName]) {
      source[methodName] = func;
    }
  });
  return source;
}()), false);

// Add chaining functions to the lodash wrapper.
var chain = require('lodash/chain');
lodash.prototype.chain = chain.wrapperChain;
lodash.prototype.value = chain.value;
```

**Comment by erykpiast** [comment]
Got it! But apparently I was misunderstood :) I don't try to find a way to chain per-method modules like methods of full lodash. I just want to notice, that extracting `chain`, `thru`, `tap` and `value` methods can help with chaining lodash functions from per-method modules.

Example above seems over-complicated to me, and, what is more important, it requires explicit declaration, what functions will be used in whole app. When used like that, single module can't specify its dependencies anymore. When I use per-method build, I can declare that module A requires functions `assign`, `group By`, `pick` and nothing more, what is awesome for me. Of course, I don't reject jQuery or Rx if they don't provide that kind of separation, but lodash provides and I want to use it if I can :P

Summarizing, if you see possibility to extract`chain`, `thru`, `tap` and `value` methods (with lazy-evaluation!) without much effort, I find it useful. I would to get know more opinions, I wonder if you can reopen the thread and let people talk? I want to know if I'm just insane or have good idea indeed  ;)

**Comment by jdalton** [comment]
>  I just want to notice, that extracting chain, thru, tap and value methods can help with chaining lodash functions from per-method modules.

Maybe though the process would be similar. The chaining methods are left out of the individual npm packages because it is awkward to setup chaining on a per method basis. I don't see a clean way to do it.

> Example above seems over-complicated to me, and, what is more important, it requires explicit declaration, what functions will be used in whole app.

Yes, there is no magic there. It requires manually hooking up which methods are chained.

> Summarizing, if you see possibility to extract`chain`, `thru`, `tap` and `value` methods (with lazy-evaluation!) without much effort, I find it useful.

I don't see a way without adding specialized API which doesn't mesh well with lodash's non modularized form. I think it's nice to give the monolithic build some carrots (like chaining, lazy eval, & runInContext).

**Comment by bfred-it** [comment]
Would it make sense to make that code part of lodash? That's a lot of boilerplate. 
To enable a simpler API, e.g.:

```js
const _ = require('lodash/chainHelper')({capitalize, groupBy});
