### ISSUE TITLE
applyDiffDeep?

### ISSUE THREAD

**Issue by mohsen1** [lodash/lodash#967]
I have a situation that none of  `_.defaults`, `_.extend` and `_.assign` methods are working for me. In [Swagger Editor](https://github.com/swagger-api/swagger-editor) project I have a text editor which is constantly updating a JavaScript object. I get this JavaScript object and do some massaging to it (converting hashes to arrays and so on). Then I set this newly created object to my AngularJS scope and AngularJS will render the new preview based on the new object. It all works but because I'm setting a new object to the scope on each key press AngularJS have to re-render the entire preview pane every time. AngularJS has an awesome diff detecting mechanism but I'm not using it because every time I set a new object to the scope.

To solve this, I wrote a little function that deeply compares two objects and apply new changes to the destination object. With this, I could just apply the changes instead of re-assigning the object. 
[Here is a link to this function](https://github.com/swagger-api/swagger-editor/blob/26561263b05cc17b96c63472fb33974d0a2d1bb9/app/scripts/controllers/preview.js#L193-L268)

If it's possible to do the same operation with lodash please let me know. If this functionality is not part of lodash, I would really like to use lodash instead of writing my own function. How possible is it to have such function in lodash?

**Comment by jdalton** [comment]
[_.extend](https://lodash.com/docs#assign) and [_.merge](https://lodash.com/docs#merge) have a customizer callback you can use to inspect values. Both `extend` and `merge` should skip value assignment when the new value is the old value.

**Comment by mohsen1** [comment]
Thanks for the reply. How about deleting the no-longer-exist keys in destination? 

For example
**source**
```js
{
 a: 1,
 b: 3
}
```
**destination**
```js
{
 a: 0,
 b: 3,
 c: 4
}
```
**result**(expected by my use case)
```js
{
 a: 1,
 b: 3
}
```

**Comment by jdalton** [comment]
Iteration is based on the `source` object so deleting keys wouldn't be possible on merging. You can get the keys of the `source` and `_.pick(destination, _.keys(source))`.

**Comment by mohsen1** [comment]
Correct. My use-case is a little different. I basically want to avoid assigning `destination` to `source` (`destination = source`) and keep what is not touched in `destination` in place. How can I do this with lodash bits? My own function seems to be doing it but I wonder if I can do better by using more of lodash?

**Comment by jdalton** [comment]
I think sticking with your own function is the way to go.
