### ISSUE TITLE
Regexp predicates?

### ISSUE THREAD

**Issue by chocolateboy** [lodash/lodash#971]
I'm porting a script from (bash to) Perl to JavaScript, part of which uses lodash's `partition` function.

It's straightforward in Perl:

### Perl

```perl
my ($options, $dirs) = partition { /^-/ ? 0 : 1 } @ARGV;
```

It's pretty verbose in ES5:

### ES5

```
var parts = _.parition(process.argv.slice(2), function (arg) { return /^-/.test(arg) });
var options = parts[0];
var dirs = parts[1];
```

It's better, of course, in ES6, but IMO the functional boilerplate still gets in the way:

### ES6

```javascript
let [ options, dirs ] = _.parition(process.argv.slice(2), arg => /^-/.test(arg));
```

I was hoping this would work:

### lodash?

```javascript
let [ options, dirs ] = _.parition(process.argv.slice(2), /^-/);
```

\- but it doesn't. Instead, the regex is treated as an object and generates a `_.matches`-style callback, which doesn't seem to be particularly useful in the case of a regex. Any interest in making it DWIM?

I know I could roll my own wrapper or use a third-party library e.g.:

```javascript
let match = require('predicate').match;

let [ options, dirs ] = _.parition(process.argv.slice(2), match(/^-/));
```

\- but one of lodash's strengths is its built-in support for common patterns like this.

(While I'm at it, perhaps the `partition` documentatiion could mention `groupBy` e.g. "To partition a collection into more than two groups, see `groupBy`." And vice versa.)

**Comment by jdalton** [comment]
You can use `_.bind`:
```js
_.parition(process.argv.slice(2), RegExp.prototype.test, /^-/);
```
