### ISSUE TITLE
Implicit chaining functions not consistent

### ISSUE THREAD

**Issue by brandonhorst** [lodash/lodash#972]
Could you explain why `_({x: 1}).has('x')` works fine, but `var y = _({x: 1}).has; y('x')` throws a TypeError?

Ultimately, I was hoping to be able to use code like this:

```js
_.every(types, _(validTypes).has)
```

rather than

```js
_.every(types, function (type) {return _.has(validTypes, type)})
```

**Comment by jdalton** [comment]
The wrapped methods reference `this` and when you assign `has` to `y` it's no longer associated with the wrapper. For what you're wanting you can use `_.partial`:
``js
_.every(types, _.partial(_.has, validTypes));
```
