### ISSUE TITLE
_.remove by index

### ISSUE THREAD

**Issue by dwelle** [lodash/lodash#974]
e.g. `_.remove( arr, 999 )` to remove one specific element by its idx. Looking at docs, `number` datatype as `predicate` is still available, so why not to allow it? Can be useful for large arrays if you already know the idx in advance.

EDIT: in fact, you could implement similar logic to Resig's [JavaScript Array Remove][inIUhw] to allow for slice-like behavior for removing array elements (e.g. supplying `-1` to remove last element).

[inIUhw]: http://ejohn.org/blog/javascript-array-remove/

**Comment by StreetStrider** [comment]
@dwelle, hi. Does not `Array.prototype.splice` solves this particular task? By the way, LoDash supports it in chaining, but not in lodash object.

**Comment by d10** [comment]
@StreetStrider is right, you could just use [Array#splice](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/splice):

```js
// Remove 1 element at `index`
array.splice(index, 1);
```

In fact, lodash uses that internally for `_.remove`, so it would be more efficient to just use it without another function wrapping it.

You can also use it when chaining, as @StreetStrider mentioned:

```js
_(array)
  .chain()
  .splice(index, 1)
  .value();
```

**Comment by dwelle** [comment]
Does not address the slice-like behavior of Resig's implementation. Also, the fact you can use `#splice` doesn't mean `_.remove` couldn't support indexes for easier and a bit more consistent workflow of modifying Arrays.

**Comment by jdalton** [comment]
The `_.remove` method accepts a callback and will not accept indexes. If you like Resig's implementation feel free to use `_.mixin` and add it yourself.

**Comment by jdalton** [comment]
Oh, lol, there's [_.pullAt](https://lodash.com/docs#pullAt).

**Comment by d10** [comment]
Lol, also forgot about that. lodash has too many functions to remember ;)

**Comment by jdalton** [comment]
But so few mutator methods.

**Comment by dwelle** [comment]
Ok, cool, didn't know about `_.pullAt` either. At least now I know I'm not the only one who forgets about his own API methods :) (unless you weren't the one who wrote it).

**Comment by jdalton** [comment]
I'm over 30, which is ancient in JS dev years.

**Comment by jetpack3331** [comment]
@jdalton No worry. I'm almost 30 too. JS will always have a small place at the world :)
