### ISSUE TITLE
Difference in working

### ISSUE THREAD

**Issue by Delagen** [lodash/lodash#977]
```
_.deepPluck(obj, "prop1.prop2") // from lodash-deep
 _.where(obj, {prop1: {prop2: true}})
```
works differ
prop1 is custom object with prop2 bool initialized in constructor via this.

first returns items
second returns empty array

**Comment by jdalton** [comment]
[lodash-deep](https://www.npmjs.com/package/lodash-deep) is not officially associated with lodash. In [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) we [made iteration of destination object properties consistent](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings) by comparing only own properties. 

In v3.2.0 we introduced [_.matchesProperty](https://lodash.com/docs#matchesProperty) and its [shorthand](https://lodash.com/docs#filter) to allow matching a property regardless of whether it's own or inherited.
```js
_.filter(obj, 'prop1', {'prop2': true});
```
