### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mgcrea** [lodash/lodash#978]
Probably not a bug but I got some weird error after upgrading from `~v2.4`, haven't really dug into yet but  it might help anyone encountering this suddenly:

Using a "standard" _.defaultsDeep like this (eg. like [merge-defaults](https://github.com/balderdashy/merge-defaults)):

```
var defaultsDeep = _.partialRight(_.merge, function deep(value, other) {
  if (_.isArray(value) || _.isDate(other)) return value;
  return _.merge(value, other, deep);
});
```

This is now crashing with `RangeError: Maximum call stack size exceeded`:

```
defaultsDeep('{,modules/*/}{views,scripts,modules}/**/*.{jade,html}', '{views,modules/*}/**/*.{html,jade}');
```

Somehow the `_.merge` gets stuck on merging the `{` char, Haven't found something that could explain this by reading the changelog yet.

Worked in the v2.4 branch.

**Comment by jdalton** [comment]
Yap, many recursive methods are susceptible to call stack limits which vary for enviros and fun too size. It's not a common enough problem to address at the moment (would mean large perf hits for an edge issue)

**Comment by jdalton** [comment]
@mgcrea can you gist the object your iterating over.

**Comment by mgcrea** [comment]
@jdalton https://gist.github.com/mgcrea/523ef0ea0b37ee9b330b

Fixed it with this for now, looks like to be working:
```
var defaultsDeep = _.partialRight(_.merge, function deep(value, other) {
  if (_.isString(other) || _.isArray(value) || _.isDate(other)) return value;
  return _.merge(value, other, deep);
});
```

**Comment by jdalton** [comment]
These objects are tiiiiny. I'll dig in this evening.

**Comment by mgcrea** [comment]
@jdalton 

Indeed, the base test-case does crash and is only merging two strings:

```
defaultsDeep('{,modules/*/}{views,scripts,modules}/**/*.{jade,html}', '{views,modules/*}/**/*.{html,jade}');
```

**Comment by jdalton** [comment]
The method isn't intended for strings so I think its probably iterating them as a string object (so iterating the index proprerties of both strings)

**Comment by jdalton** [comment]
This is a bug on `_.merge` handling of string values.

**Comment by jdalton** [comment]
Added tests https://github.com/lodash/lodash/commit/89ed40e4a4f76c86fcd99be9a5deac020af15407.

**Comment by recurrence** [comment]
Ran into this as well with a defaultsDeep implementation when upgrading from 2.4.1 to 3.2.

**Comment by jdalton** [comment]
Expect a bump, 3.3.0, by Friday evening.

**Comment by recurrence** [comment]
Thanks!
