### ISSUE TITLE
Docs request: Link from docs to npm module on npmjs.com

### ISSUE THREAD

**Issue by jasonkarns** [lodash/lodash#979]
It's awesome that lodash is modularized so we can require individual lodash functions here and there. However, npmjs' registry search is... lacking.

(the modularized filter is linked from lodash homepage to: https://www.npmjs.com/browse/keyword/lodash-modularized. But one cannot simply search within that result set because npm's search box doesn't pre-populate so attempting to refine the search results in an npm-wide search, not lodash-specific.)

Generally we know which modules we want to pull in, so finding them in the lodash docs is easiest. So a simple link right next to the source/TOC links would be perfect.

<img src="https://cloud.githubusercontent.com/assets/119972/6276938/720d33e2-b858-11e4-8c10-3d480b8f9f3e.png" height=70% width=70%>

Thoughts on a unicode glyph that could concisely represent the module's page on the npmjs registry?

**Comment by jdalton** [comment]
Let's do it. 

> Thoughts on a unicode glyph that could concisely represent the module's page on the npmjs registry?

Halp from the stylishly inclined!

**Comment by jdalton** [comment]
Maybe Ⓝ

**Comment by jasonkarns** [comment]
:thumbsup: works for me.

_sesame street voice_: Ⓝ is for node and npm!

On Thu, Feb 19, 2015 at 5:04 PM, John-David Dalton <notifications@github.com

**Comment by jdalton** [comment]
Fixed https://github.com/lodash/lodash/commit/d2dc918a619d7207d214fd95fc1858d0578ab86e. It'll show up on the site when we bump v3.3.0.
