### ISSUE TITLE
Aliases for Underscore 1.8 methods 

### ISSUE THREAD

**Issue by thejameskyle** [lodash/lodash#980]
I think this is all of them, I'm still trying to sort out everything that has happened.

- `_.keysIn` to `_.allKeys`
- `_.mapValues` to `_.mapObject`
- `_.assign` to `_.extendOwn`
- `_.matcher` to `_.matches`

https://github.com/jashkenas/underscore/issues/2061

**Comment by jdalton** [comment]
Thanks James, I'll add these. I planned to bump tonight (before all this went down) but may delay it a day to review these changes.

**Comment by jdalton** [comment]
I'm going to hold off on these until the dust settles on the Underscore release(s). This won't make it in to v3.3.0 (this week's bump) but may in the next week's.

**Comment by jdalton** [comment]
These name are pretty horrible and were added without any discussion so I'm not going to reward rotten behavior with support. Underscore is on it's way out. Within a month it'll fall from its top spot on npm to number 3 with no sign of recovery.

**Comment by thejameskyle** [comment]
Damn concern trolls. _Shakes fist_

**Comment by jdalton** [comment]
:D
