### ISSUE TITLE
Timeout support for cached values in _.memoize

### ISSUE THREAD

**Issue by corporatepiyush** [lodash/lodash#988]
Currently _.memoize support either permanent cached values or registering WeakMap.
Can we have facility to set expiry period as given below

_.memoize(functionWhichInvolvesHeavyComputations, { expire : 10 })

where 10 is 10 seconds (or  10000 ms)

**Comment by jdalton** [comment]
That would eat into the `resolver` param. We allow customizing the cache with anything with a Map like interface so you could had a custom one with a timeout baked in or create a `mixin` to.

**Comment by corporatepiyush** [comment]
ouch ! how hard is it to inspect second argument is a function(resolver) or options object ?

**Comment by jdalton** [comment]
Overloading is something we're trying to avoid moving forward. `_.memoize` makes it easy to customize the memoize cache and lodash makes it easy to add your own mixins.

**Comment by corporatepiyush** [comment]
Thanks for prompt response.
If overloading is the only concern, can we have function with different name ?  
Is there any way I could achieve it with combination of _.throttle and other helper function.

**Comment by jdalton** [comment]
> If overloading is the only concern, can we have function with different name ?

I think this fits well as a `mixin` for now.

> Is there any way I could achieve it with combination of _.throttle and other helper function.

A combo of `_.delay` or `_.throttle` with other helper functions may do.

**Comment by corporatepiyush** [comment]
Thanks John

**Comment by shtse8** [comment]
So how can I do the memorize with expire? any example provided? thanks.
