### ISSUE TITLE
Feature: Named arguments method

### ISSUE THREAD

**Issue by DrSammyD** [lodash/lodash#989]
[bob.js](http://www.bobjs.com/) has a method that allows you to create named functons as part of an options object and map them to parameters of the function;

So you could write a function like this
```
var func = function (name, age, gender, shape, width, height) { ... };
```
And call like this
```
func = _.named(func)
func({ shape: 'Rectangle', width: 20, height: 30 }); 
```
instead of this
```
func(null,null,null,'Rectangle',20,30);
```

I'd do a pull request, but I don't know how to integrate it with your existing `createWrapper/createHybridWrapper` function

So Here's some sudo implementation
```
_.mixin({
   named:function(func) {
        argNames = func.toString();
        argNames = argNames.slice(argNames.indexOf("(") + 1, argNames.indexOf(")")).match(/([^\s,]+)/g);


        return function(argObj) {
            var args=_.map(argNames,function(arg){
                return argObj[arg];
            });
            return func.apply(this, args);
        };
    }
});
```

**Comment by DrSammyD** [comment]
You could even curry it so that you can give the curry a list of arguments that must be included before it runs, and then call it like

```
var func = _.named(function (name, age, gender, shape, width, height) { ... },{curried:[['shape','width','height'],['name','age','gender']]});
```
And then only run the function if each set is fulfilled
```
func({shape:"oval",width:"20"})//doesn't run
({age:10})//doesn't run
({height:10})//runs
```

**Comment by jdalton** [comment]
Hi @DrSammyD! I made something like this in PHP once. I don't want to sniff arguments. This fits as a `mixin`.

**Comment by DrSammyD** [comment]
What if we make it explicit? `_.named(function(name,age){}, ['name','age'])` where order of the array matches the argument names?

**Comment by jdalton** [comment]
I still think it's be better as a `mixin`. If demand is there it'll be reconsidered.

**Comment by DrSammyD** [comment]
Ok cool. I was just reading a [why use dart](https://gist.github.com/khoomeister/4976475#dart-wins) article, and one of the reasons they listed was named parameters. I thought to myself "I bet I can make javascript can do that".

**Comment by StreetStrider** [comment]
@DrSammyD, you should probably think about function which has 5 or more (!) positional arguments. It's a code smell. Instead of introducing workaround, let us just don't write such functions. If function has so many arguments they are probably an options, so they can be collected in plain object by function's author.

Also, as you've discussed above, the name of arguments in not a something you can rely on. I can `bind` function and it will lose all names in arguments. In angular community this problem is well-known too, because they created similar bad design.

**Comment by DrSammyD** [comment]
@StreetStrider, I agree, and that makes sense with a green field, however if I want to use a legacy function without breaking it's api, but I don't want my code to have to call a function with 6 arguments, then this seems like the best of both worlds. The point about bind is taken though, so I think the explicit array is a good alternative to sniffing, and it makes 'renaming' the named variables possible.

Another feature for this, It could also introduce a default options
`_.named(function(name,age){}, ['shape','height'],{default:{shape:'circle'}})`

**Comment by davidkpiano** [comment]
@DrSammyD @jdalton here's a tiny mixin for this. Its second argument takes in an array of the named arguments because, you know, minification. ;-)

```javascript
function named(func, args, thisObj) {
  return function(namedArgs) {
    var namedFunc = _.rearg(func, _.map(_.keys(namedArgs), _.ary(_.partial(_.indexOf, args), 1)));
    
    return namedFunc.apply(thisObj || null, _.values(namedArgs));
  }
}

_.mixin({named: named});
```

And here's how you'd use it:
```javascript
var divide = function(a, b) { return a / b; };

var divideNamed = _.named(divide, ['a', 'b']);

divideNamed({b: 2, a: 4}); // 2
```

I think it suits a `_.mixin` well.

**Comment by DrSammyD** [comment]
@davidkpiano How might you go about doing something like this

```
var curriedNamed=_(function(a, b, c) {
  return [a, b, c];
}).named(['a','b','c']).curry();

curriedNamed({a:1,b:2})({c:3});
// → [1, 2, 3]
```

**Comment by megawac** [comment]
@DrSammyD looks like you want `pluckMany` + a `extend`?? See https://github.com/lodash/lodash/issues/855, #698, #581

**Comment by ruimarinho** [comment]
Can't this be left for ES6 destructuring?

**Comment by DrSammyD** [comment]
@megawac @ruimarinho not sure how either of those would make curry work with that mixin.
