### ISSUE TITLE
Chaining takeWhile and last does not work

### ISSUE THREAD

**Issue by niom** [lodash/lodash#990]
When using chaining with takeWhile and last return undefined instead of the correct value.

example:
```javascript 
    _
    .chain([1, 2, 3])
    .takeWhile(function(item) {
        return item < 3
    })
    .last()
    .value()
    // ==> undefined
```

making the same thing without chaining works correctly
```javascript
    _.last(
        _.takeWhile([1, 2, 3], function(item) {
            return item < 3
        })
    )
    // ==> 2
```

maybe some issue with lazy evaluation?

I created a jsfiddle from this issue with the latest lodash (3.3.0)
http://jsfiddle.net/zyx2rkfa/

**Comment by jdalton** [comment]
Ah, I introduced this regression in v3.2.0.

**Comment by jdalton** [comment]
I'll release 3.3.1 Monday evening.

**Comment by niom** [comment]
Cool, I'll test this when you get the 3.3.1 out.

**Comment by niom** [comment]
Fix confirmed. Thanks.
