### ISSUE TITLE
No `guard` arg in _.words documentation

### ISSUE THREAD

**Issue by royaldark** [lodash/lodash#992]
I didn't see a separate docs repo, so I hope this is the right place to report a documentation issue.

Inspecting `_.words` on the command line, I can see it is of the form `function words(string, pattern, guard)`. However, the documentation at https://lodash.com/docs#words only lists the first two arguments, with no mention of the `guard` argument.

**Comment by jdalton** [comment]
The `guard` param [is not intended for public use](https://github.com/lodash/lodash/blob/3.3.0-npm-packages/lodash.words/index.js#L28) an is part of allowing it to work in `_.map` and others as an iteratee.
