### ISSUE TITLE
Include "version added" on methods in API Docs

### ISSUE THREAD

**Issue by thejameskyle** [lodash/lodash#993]
@coredumperror brings up a good point in https://github.com/jashkenas/underscore/issues/2080. Lots of documentation included the version something was added inline with the rest of the docs. This seems like it'd be really useful.

**Comment by jdalton** [comment]
Moving this to [docdown](https://github.com/jdalton/docdown/issues/23).

**Comment by antch** [comment]
I should have this done in the next few days. Does it make sense to re-open this since there will need to be updates to the lodash docs to add the metadata?

**Comment by jdalton** [comment]
You can just reference this in the PR commit message `[closes #993]`.

**Comment by jfmengels** [comment]
Part of it is done in #2079
