### ISSUE TITLE
Lodash 3.3 breaking on isIterateeCall

### ISSUE THREAD

**Issue by tgriesser** [lodash/lodash#994]
> TypeError: Cannot convert object to primitive value
      at isIterateeCall (/home/travis/build/tgriesser/bookshelf/node_modules/lodash/index.js:3679:25)

See: https://travis-ci.org/tgriesser/bookshelf/jobs/51937726 on https://github.com/tgriesser/bookshelf/commit/999b9cdc9d3296f8e169f4d7daf9374d2d3675b0 didn't immediately see what was going wrong, works fine on the rest of the `3.x`

**Comment by jdalton** [comment]
Try using [lodash-migrate](https://www.npmjs.com/package/lodash-migrate) for a heads up on changes between versions. I'm not sure this is a legit bug on lodash at the moment.

**Comment by jdalton** [comment]
Ah, it's a bug ;)

**Comment by tgriesser** [comment]
Cool, thanks.

Also, oddly enough `lodash-migrate` seems to break things in different ways when using versions of 3.x that do work. It seems it's having some issues with Bluebird's Promises resolving in the proper order or something. I'll need to take a closer look later.
