### ISSUE TITLE
Publish as Google Script Library

### ISSUE THREAD

**Issue by jakesjews** [lodash/lodash#995]
I'm currently writing some scripts for google docs and really missing Lodash. Unfortunately, [Google Scripts are strict about including libraries](https://developers.google.com/apps-script/guide_libraries) and I was only able to find a [published version of underscore](https://sites.google.com/site/scriptsexamples/custom-methods/underscoregs). Would it be possible to get an official published version of lodash available to Google Scripts?

In the worst case I can paste it in myself but I think there could be a lot of other people who would find lodash useful in this situation.

Thanks a ton for lodash!

**Comment by jdalton** [comment]
I believe you should be able to add lodash on your own. I know the underscore version you found isn't officially supported either.
