### ISSUE TITLE
chaining and indexing work funny

### ISSUE THREAD

**Issue by niom** [lodash/lodash#997]
There's something funny with indexes when using chaining compared to use direct method calls.

example

```javascript
    _.filter(
        _.rest([1, 2, 3]), 
        function(item, index) {
            return index < 2
        }
    )  
   //==> [2, 3]
```

```javascript
    _
    .chain([1, 2, 3])
    .rest()
    .filter(
        function(item, index) {
            return index < 2
        }
    ).value()
   // ==> [2]  
```
http://jsfiddle.net/w1k7650f/2/

**Comment by arseniew** [comment]
Version 2.2.1 works as expected: [2, 3] for both examples. It seems to be 3.x issue.

**Comment by jdalton** [comment]
v3 introduced lazy evaluation and shortcut fusion. Part of shortcut fusion is that the `index` and `collection` iteratee params may not be the same as if the calls were executed sequentially.

**Comment by niom** [comment]
IMHO this feels really dirty. 
First of all it's not very apparent that the indexes can get messed up when shortcut fusion occurs. 
Second it would be great that there would be some warnings in the documentation to avoid using indexes while chaining. 

This also breaks the equality contract with the examples when considering the indexes.

**Comment by jdalton** [comment]
You're right. We can have our cake and eat it too. I can detect an iteratee with a .length > 1 and disable the optimization for them.

**Comment by srlmproductions** [comment]
Is this fixed? The following code does not work for me:

```javascript
var data = [{a: 1}, {b: 2}, {c: 3}];
_.chain(data).map(function (v, index) {
    console.log('index: ' + index);
    return v;
}).value();
```
```
index: undefined
index: undefined
index: undefined
```

I'm using the latest lodash from bower: 3.4.0 (`lodash modern -o ./lodash.js`).

**Comment by jdalton** [comment]
Nice! You saved me from bumping (v3.4.0 hasn't been published yet). I didn't catch one case.
