### ISSUE TITLE
Should _.matches(<emptything>)(<anything>) === true?

### ISSUE THREAD

**Issue by mpolichette** [lodash/lodash#999]
Hey friends, love lodash, really great work!

I was just trying to use _.matches to do a _.reject.  However, sometimes my `source` object is undefined, and this causes the matches to always be true.  Is this by design?

I've walked the code and it looks like anything w/o any properties (E.G. empty array, empty object, undefined, null) will do this because it doesn't actually run any comparisons and instead immediately returns `true`.

If this is by design, I think there should be a note in the docs, since it is unexpected behavior to me.

Thanks!
Matt

**Comment by megawac** [comment]
Yes, the behaviour was primarily designed for the case 

```js
var spec = {};
var obj = {a: 1};
_.matches(spec)(obj)
```

We decided this was true as every key:value pair is the same on the spec as the object as there are no keys on the spec. This is the same design as for `_.every` and `Array.prototype.every`, consider `[].every(_.constant(false))`

**Comment by mpolichette** [comment]
Interesting, is there a function which behaves like _.matches but internally runs something more similar to `_.isEqual` to do the comparison?

I was trying to use `_.matches` as a convenience method for something like this:
```javascript
function deepWithout(array, value){
  var isValue = _.partial(_.isEqual, value);
  return _.reject(array, isValue)
}
```
Hoping i could replace that with a one liner
```javascript
_.reject(array, _.matches(value))
```
Am I overlooking a function lodash offers for that?

**Comment by mpolichette** [comment]
I didn't mean to close :(

**Comment by jdalton** [comment]
I'm in a live MVA course presenting all say so slow to respond

**Comment by jdalton** [comment]
`_.match` performs a deep partial match do if you're wanting something like `_.isEqual` composition is your friend.

**Comment by mpolichette** [comment]
Thanks for the fast and thorough response @megawac and @jdalton. You (and everyone helping) are doing a great job maintaining lodash.  I'm impressed.
